var searchData=
[
  ['_5faligner_0',['_Aligner',['../structtcg_1_1___aligner.html',1,'tcg']]],
  ['_5faligntype_1',['_AlignType',['../structtcg_1_1___align_type.html',1,'tcg']]],
  ['_5faligntype_3c_20alignment_2c_20char_20_3e_2',['_AlignType&lt; alignment, char &gt;',['../structtcg_1_1___align_type.html',1,'tcg']]],
  ['_5faligntype_3c_20alignment_2c_20double_20_3e_3',['_AlignType&lt; alignment, double &gt;',['../structtcg_1_1___align_type.html',1,'tcg']]],
  ['_5faligntype_3c_20alignment_2c_20float_20_3e_4',['_AlignType&lt; alignment, float &gt;',['../structtcg_1_1___align_type.html',1,'tcg']]],
  ['_5faligntype_3c_20alignment_2c_20int_20_3e_5',['_AlignType&lt; alignment, int &gt;',['../structtcg_1_1___align_type.html',1,'tcg']]],
  ['_5faligntype_3c_20alignment_2c_20long_20_3e_6',['_AlignType&lt; alignment, long &gt;',['../structtcg_1_1___align_type.html',1,'tcg']]],
  ['_5faligntype_3c_20alignment_2c_20longdouble_20_3e_7',['_AlignType&lt; alignment, longdouble &gt;',['../structtcg_1_1___align_type.html',1,'tcg']]],
  ['_5faligntype_3c_20alignment_2c_20longlong_20_3e_8',['_AlignType&lt; alignment, longlong &gt;',['../structtcg_1_1___align_type.html',1,'tcg']]],
  ['_5faligntype_3c_20alignment_2c_20short_20_3e_9',['_AlignType&lt; alignment, short &gt;',['../structtcg_1_1___align_type.html',1,'tcg']]],
  ['_5faligntype_3c_20alignment_2c_20tcg_3a_3a_5fmaxalign_20_2a_20_3e_10',['_AlignType&lt; alignment, tcg::_MaxAlign * &gt;',['../structtcg_1_1___align_type.html',1,'tcg']]],
  ['_5faligntype_3c_20alignment_2c_20void_20_2a_20_3e_11',['_AlignType&lt; alignment, void * &gt;',['../structtcg_1_1___align_type.html',1,'tcg']]],
  ['_5faligntype_3c_20alignment_2c_20void_28_2a_29_28_29_3e_12',['_AlignType&lt; alignment, void(*)()&gt;',['../structtcg_1_1___align_type.html',1,'tcg']]],
  ['_5faligntypedetail_13',['_AlignTypeDetail',['../structtcg_1_1___align_type_detail.html',1,'tcg']]],
  ['_5faligntypedetail_3c_20t_2c_20false_20_3e_14',['_AlignTypeDetail&lt; T, false &gt;',['../structtcg_1_1___align_type_detail_3_01_t_00_01false_01_4.html',1,'tcg']]],
  ['_5faligntypedetail_3c_20t_2c_20true_20_3e_15',['_AlignTypeDetail&lt; T, true &gt;',['../structtcg_1_1___align_type_detail_3_01_t_00_01true_01_4.html',1,'tcg']]],
  ['_5fdummyreader_16',['_DummyReader',['../class_t_rop_1_1borders_1_1___dummy_reader.html',1,'TRop::borders']]],
  ['_5fexternaledgesigner_17',['_ExternalEdgeSigner',['../struct_t_rop_1_1borders_1_1___external_edge_signer.html',1,'TRop::borders']]],
  ['_5fi_5fpixel_18',['_I_PIXEL',['../struct___i___p_i_x_e_l.html',1,'']]],
  ['_5finternaledgesigner_19',['_InternalEdgeSigner',['../struct_t_rop_1_1borders_1_1___internal_edge_signer.html',1,'TRop::borders']]],
  ['_5flist_5fnode_20',['_list_node',['../structtcg_1_1__list__node.html',1,'tcg']]],
  ['_5fmaxalign_21',['_MaxAlign',['../uniontcg_1_1___max_align.html',1,'tcg']]],
  ['_5fperm_5frng_5ftraits_22',['_perm_rng_traits',['../structtcg_1_1__perm__rng__traits.html',1,'tcg']]],
  ['_5fquadraticsedgeevaluator_23',['_QuadraticsEdgeEvaluator',['../classtcg_1_1polyline__ops_1_1___quadratics_edge_evaluator.html',1,'tcg::polyline_ops']]],
  ['_5fquadreader_24',['_QuadReader',['../classtcg_1_1polyline__ops_1_1___quad_reader.html',1,'tcg::polyline_ops']]],
  ['_5fraster_25',['_RASTER',['../struct___r_a_s_t_e_r.html',1,'']]],
  ['_5fts_5fstrack_5finfo_26',['_TS_STRACK_INFO',['../struct___t_s___s_t_r_a_c_k___i_n_f_o.html',1,'']]],
  ['_5fttwain_5fdata_5f_5f_27',['_TTWAIN_DATA__',['../struct___t_t_w_a_i_n___d_a_t_a____.html',1,'']]],
  ['_5fuc_5fpixel_28',['_UC_PIXEL',['../struct___u_c___p_i_x_e_l.html',1,'']]],
  ['_5fus_5fpixel_29',['_US_PIXEL',['../struct___u_s___p_i_x_e_l.html',1,'']]]
];
