opentoonz: VectorizerParameters Class Reference
VectorizerParameters Class Reference final
Container class for scene-bound vectorizer options.
#include <vectorizerparameters.h>
Public Member Functions
CenterlineConfiguration getCenterlineConfiguration (double weight) const
NewOutlineConfiguration getOutlineConfiguration (double weight) const
VectorizerConfiguration * getCurrentConfiguration (double weight) const
Builds a copy of the currently active configuration allocated using the new operator.
void saveData (TOStream &os) override
void loadData (TIStream &is) override
Public Member Functions inherited from TPersist
virtual void loadData (TIStream &is)=0
virtual void saveData (TOStream &os)=0
std::string getStreamTag () const
virtual const TPersistDeclaration * getDeclaration () const =0
Public Attributes
int m_cThreshold
int m_cAccuracy
int m_cDespeckling
int m_cMaxThickness
double m_cThicknessRatioFirst
double m_cThicknessRatioLast
bool m_cMakeFrame
bool m_cPaintFill
bool m_cAlignBoundaryStrokesDirection
bool m_cNaaSource
int m_oDespeckling
int m_oAccuracy
int m_oAdherence
int m_oAngle
int m_oRelative
int m_oMaxColors
int m_oToneThreshold
TPixel32 m_oTransparentColor
bool m_oPaintFill
bool m_oAlignBoundaryStrokesDirection
unsigned int m_visibilityBits
bool m_isOutline
Additional Inherited Members
Public Types inherited from TPersist
typedef TPersist * CreateProc()
Static Public Member Functions inherited from TPersist
static void declare (CreateProc *)
static TPersist * create (const std::string &name)
Detailed Description
Container class for scene-bound vectorizer options.
Constructor & Destructor Documentation
VectorizerParameters()
VectorizerParameters::VectorizerParameters ()
    : m_visibilityBits(-1)  // All visible by default
    , m_isOutline(false) {
  CenterlineConfiguration cConf;
  convert(cConf, *this);
  NewOutlineConfiguration oConf;
  convert(oConf, *this);
}
Member Function Documentation
getCenterlineConfiguration()
CenterlineConfiguration VectorizerParameters::getCenterlineConfiguration (double weight) const
{
  CenterlineConfiguration conf;
  conf.m_outline      = false;
  conf.m_threshold    = m_cThreshold * 25;
  conf.m_penalty      = 10 - m_cAccuracy;  // m_cAccuracy in [1,10]
  conf.m_despeckling  = m_cDespeckling * 2;
  conf.m_maxThickness = m_cMaxThickness / 2.0;
  // conf.m_thicknessRatio   = m_cThicknessRatio;
  conf.m_thicknessRatio =
      (1 - frame) * m_cThicknessRatioFirst + frame * m_cThicknessRatioLast;
  conf.m_leaveUnpainted                = !m_cPaintFill;
  conf.m_alignBoundaryStrokesDirection = m_cAlignBoundaryStrokesDirection;
  conf.m_makeFrame                     = m_cMakeFrame;
  conf.m_naaSource                     = m_cNaaSource;
  return conf;
}
getCurrentConfiguration()
VectorizerConfiguration * VectorizerParameters::getCurrentConfiguration (double weight) const inline
Builds a copy of the currently active configuration allocated using the new operator.
Parameters
weight Position of the requested configuration in an abstract frame range, normalized to the [0, 1] range.
{
    return m_isOutline ? (VectorizerConfiguration *)new NewOutlineConfiguration(
                             getOutlineConfiguration(weight))
                       : (VectorizerConfiguration *)new CenterlineConfiguration(
                             getCenterlineConfiguration(weight));
  }
getOutlineConfiguration()
NewOutlineConfiguration VectorizerParameters::getOutlineConfiguration (double weight) const
{
  NewOutlineConfiguration conf;
  conf.m_outline                       = true;
  conf.m_despeckling                   = m_oDespeckling;
  conf.m_adherenceTol                  = m_oAdherence * 0.01;
  conf.m_angleTol                      = m_oAngle / 180.0;
  conf.m_relativeTol                   = m_oRelative * 0.01;
  conf.m_mergeTol                      = 5.0 - m_oAccuracy * 0.5;
  conf.m_leaveUnpainted                = !m_oPaintFill;
  conf.m_alignBoundaryStrokesDirection = m_oAlignBoundaryStrokesDirection;
  conf.m_maxColors                     = m_oMaxColors;
  conf.m_transparentColor              = m_oTransparentColor;
  conf.m_toneTol                       = m_oToneThreshold;
  return conf;
}
loadData()
void VectorizerParameters::loadData (TIStream & is) override virtual
 This is a pure virtual function and must be overridden with a method
that implements the object loading from a stream (i.e take the object's features from a formatted data stream). For example the TStageObject class use his implementation to take the values of the parameters that characterizes a stage object as name, coordinates, etc... from a file. is is an input file stream
Implements TPersist.
{
  VersionNumber version;
  std::string tagName;
  int val;
  while (is.matchTag(tagName)) {
    if (tagName == s_version)
      is >> version.first >> version.second, is.matchEndTag();
    else if (tagName == s_outline)
      is >> val, m_isOutline = (val != 0), is.matchEndTag();
    else if (tagName == s_visibilityBits) {
      is >> val, is.matchEndTag();
      if (version ==
          l_versionNumber)  // Restore visibility bits only if the parameters
        m_visibilityBits =
            val;  // version is current - defaulting them is no big deal.
    } else if (tagName == s_Centerline) {
      while (is.matchTag(tagName)) {
        if (tagName == s_threshold)
          is >> m_cThreshold, is.matchEndTag();
        else if (tagName == s_accuracy)
          is >> m_cAccuracy, is.matchEndTag();
        else if (tagName == s_despeckling)
          is >> m_cDespeckling, is.matchEndTag();
        else if (tagName == s_maxThickness)
          is >> m_cMaxThickness, is.matchEndTag();
        else if (tagName == s_thicknessRatioFirst)
          is >> m_cThicknessRatioFirst, is.matchEndTag();
        else if (tagName == s_thicknessRatioLast)
          is >> m_cThicknessRatioLast, is.matchEndTag();
        else if (tagName == s_makeFrame)
          is >> val, m_cMakeFrame = (val != 0), is.matchEndTag();
        else if (tagName == s_paintFill)
          is >> val, m_cPaintFill = (val != 0), is.matchEndTag();
        else if (tagName == s_alignBoundaryStrokesDirection)
          is >> val, m_cAlignBoundaryStrokesDirection = (val != 0),
                     is.matchEndTag();
        else if (tagName == s_naaSource)
          is >> val, m_cNaaSource = (val != 0), is.matchEndTag();
        else
          is.skipCurrentTag();
      }
      is.matchEndTag();
    } else if (tagName == s_Outline) {
      while (is.matchTag(tagName)) {
        if (tagName == s_despeckling)
          is >> m_oDespeckling, is.matchEndTag();
        else if (tagName == s_accuracy)
          is >> m_oAccuracy, is.matchEndTag();
        else if (tagName == s_adherence)
          is >> m_oAdherence, is.matchEndTag();
        else if (tagName == s_angle)
          is >> m_oAngle, is.matchEndTag();
        else if (tagName == s_relative)
          is >> m_oRelative, is.matchEndTag();
        else if (tagName == s_maxColors)
          is >> m_oMaxColors, is.matchEndTag();
        else if (tagName == s_toneThreshold)
          is >> m_oToneThreshold, is.matchEndTag();
        else if (tagName == s_transparentColor)
          is >> m_oTransparentColor, is.matchEndTag();
        else if (tagName == s_paintFill)
          is >> val, m_oPaintFill = (val != 0), is.matchEndTag();
        else if (tagName == s_alignBoundaryStrokesDirection)
          is >> val, m_oAlignBoundaryStrokesDirection = (val != 0),
                     is.matchEndTag();
        else
          is.skipCurrentTag();
      }
      is.matchEndTag();
    } else if (tagName ==
               "CenterlineConfiguration")  // Old tags, not saved anymore
    {
      CenterlineConfiguration conf;
      ::loadData(conf, is), is.matchEndTag();
      convert(conf, *this);
    } else if (tagName == "NewOutlineConfiguration")  //
    {
      NewOutlineConfiguration conf;
      ::loadData(conf, is), is.matchEndTag();
      convert(conf, *this);
    } else
      is.skipCurrentTag();
  }
}
References loadData(), m_isOutline, m_visibilityBits, TIStream::matchEndTag(), TIStream::matchTag(), and TIStream::skipCurrentTag().
Referenced by loadData(), and TSceneProperties::loadData().
saveData()
void VectorizerParameters::saveData (TOStream & os) override virtual
 This is a pure virtual function and must be overridden with a method
that implements the object saving to a data stream (i.e put the object's features on a formatted data stream). For example the TStageObject class use his implementation to save the values of the parameters that characterizes a stage object as name, coordinates, etc... on a file os is an output file stream.
Implements TPersist.
{
  os.child(s_version) << l_versionNumber.first << l_versionNumber.second;
  os.child(s_outline) << (m_isOutline ? 1 : 0);
  os.child(s_visibilityBits) << int(m_visibilityBits);
  os.openChild(s_Centerline);
  {
    os.child(s_threshold) << m_cThreshold;
    os.child(s_accuracy) << m_cAccuracy;
    os.child(s_despeckling) << m_cDespeckling;
    os.child(s_maxThickness) << m_cMaxThickness;
    os.child(s_thicknessRatioFirst) << m_cThicknessRatioFirst;
    os.child(s_thicknessRatioLast) << m_cThicknessRatioLast;
    os.child(s_makeFrame) << (m_cMakeFrame ? 1 : 0);
    os.child(s_paintFill) << (m_cPaintFill ? 1 : 0);
    os.child(s_alignBoundaryStrokesDirection)
        << (m_cAlignBoundaryStrokesDirection ? 1 : 0);
    os.child(s_naaSource) << (m_cNaaSource ? 1 : 0);
  }
  os.closeChild();
  os.openChild(s_Outline);
  {
    os.child(s_despeckling) << m_oDespeckling;
    os.child(s_accuracy) << m_oAccuracy;
    os.child(s_adherence) << m_oAdherence;
    os.child(s_angle) << m_oAngle;
    os.child(s_relative) << m_oRelative;
    os.child(s_maxColors) << m_oMaxColors;
    os.child(s_toneThreshold) << m_oToneThreshold;
    os.child(s_transparentColor) << m_oTransparentColor;
    os.child(s_paintFill) << (m_oPaintFill ? 1 : 0);
    os.child(s_alignBoundaryStrokesDirection)
        << (m_oAlignBoundaryStrokesDirection ? 1 : 0);
  }
  os.closeChild();
}
References TOStream::child(), TOStream::closeChild(), m_isOutline, m_visibilityBits, and TOStream::openChild().
Member Data Documentation
m_cAccuracy
int VectorizerParameters::m_cAccuracy
m_cAlignBoundaryStrokesDirection
bool VectorizerParameters::m_cAlignBoundaryStrokesDirection
m_cDespeckling
int VectorizerParameters::m_cDespeckling
m_cMakeFrame
bool VectorizerParameters::m_cMakeFrame
m_cMaxThickness
int VectorizerParameters::m_cMaxThickness
m_cNaaSource
bool VectorizerParameters::m_cNaaSource
m_cPaintFill
bool VectorizerParameters::m_cPaintFill
m_cThicknessRatioFirst
double VectorizerParameters::m_cThicknessRatioFirst
m_cThicknessRatioLast
double VectorizerParameters::m_cThicknessRatioLast
m_cThreshold
int VectorizerParameters::m_cThreshold
m_isOutline
bool VectorizerParameters::m_isOutline
Specifies the currently active parameters selection (outline / centerline).
Referenced by loadData(), and saveData().
m_oAccuracy
int VectorizerParameters::m_oAccuracy
m_oAdherence
int VectorizerParameters::m_oAdherence
m_oAlignBoundaryStrokesDirection
bool VectorizerParameters::m_oAlignBoundaryStrokesDirection
m_oAngle
int VectorizerParameters::m_oAngle
m_oDespeckling
int VectorizerParameters::m_oDespeckling
m_oMaxColors
int VectorizerParameters::m_oMaxColors
m_oPaintFill
bool VectorizerParameters::m_oPaintFill
m_oRelative
int VectorizerParameters::m_oRelative
m_oToneThreshold
int VectorizerParameters::m_oToneThreshold
m_oTransparentColor
TPixel32 VectorizerParameters::m_oTransparentColor
m_visibilityBits
unsigned int VectorizerParameters::m_visibilityBits
Variable storing the visibility of each parameter in the VectorizerPopup. Reset on version change is considered acceptable in case params layout does not match any more.
Referenced by loadData(), and saveData().
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/toonz/vectorizerparameters.h
E:/opentoonz/toonz/sources/toonzlib/vectorizerparameters.cpp