opentoonz: ToonzExt::StrokeDeformation Class Reference
ToonzExt::StrokeDeformation Class Reference
This class is the interface for manipulation algorithms.
#include <StrokeDeformation.h>
Public Member Functions
void activate (const ContextStatus *)
Init deformation and add control points.
void update (const TPointD &delta)
Modify stroke.
TStroke * deactivate ()
Return a stroke deformed.
void reset ()
Clear inner status of Deformation.
void check (const ContextStatus *)
Just select correct Deformation.
void draw (Designer *)
Apply a designer on current deformation.
ToonzExt::Interval getExtremes () const
Retrieve valid extremes for current manipulator/deformator.
const TStroke * getStroke () const
Return the stroke selected from user.
const TStroke * getCopiedStroke () const
Return the stroke selected from user.
const TStroke * getTransformedStroke () const
Return a reference to the stroke created to be manipulated.
const ContextStatus * getStatus () const
Return the internal status of current deformation.
int getCursorId () const
Retrieve cursor associated to current deformator.
Detailed Description
This class is the interface for manipulation algorithms.
StrokeDeformation is a wrapper for for StrokeDeformationImpl, its function is to verify state and parameteres before to call the implementation methods of deformation.
There is an internal status to verify that actions:
CREATED on constructor
ACTIVE on active
UPDATING on updating
DEACTIVE on deactive
If some error of state occurs reset method is called. ContextStatus contains information about deformation parameter, and it occurs to reduce the number of parameters required.
Constructor & Destructor Documentation
StrokeDeformation()
StrokeDeformation::StrokeDeformation ()
{
  state_           = CREATED;
  deformationImpl_ = SmoothDeformation::instance();
}
~StrokeDeformation()
StrokeDeformation::~StrokeDeformation ()
{}
Member Function Documentation
activate()
void StrokeDeformation::activate (const ContextStatus * status)
Init deformation and add control points.
{
  QMutexLocker sl(&s_mutex);
  assert(status && "Status is null!!!");
  if (!status) return;
  if (state_ == RESETTED) delete this->deactivate();
  if (state_ == CREATED || state_ == DEACTIVE) {
    deformationImpl_ = this->retrieveDeformator(status);
  } else {
    // if it is a not valid entry state_ recover
    assert(deformationImpl_ && "Can not find a valid deformator!!!");
    if (!deformationImpl_) return;
    deformationImpl_->reset();
    deformationImpl_ = DeformationSelector::instance()->getDeformation(status);
  }
  assert(deformationImpl_ && "Deformation is null!!!");
  if (!deformationImpl_) return;
  if (!deformationImpl_->activate_impl(status)) {
    deformationImpl_->reset();
    state_ = DEACTIVE;
    return;
  }
  state_ = ACTIVE;
}
References ToonzExt::StrokeDeformationImpl::activate_impl(), deactivate(), and ToonzExt::StrokeDeformationImpl::reset().
check()
void StrokeDeformation::check (const ContextStatus * status)
Just select correct Deformation.
{
  QMutexLocker sl(&s_mutex);
  if (state_ != UPDATING) deformationImpl_ = this->retrieveDeformator(status);
}
deactivate()
TStroke * StrokeDeformation::deactivate ()
Return a stroke deformed.
Returns
A stroke deformed.
{
  QMutexLocker sl(&s_mutex);
  if (!deformationImpl_) {
    state_ = DEACTIVE;
    return 0;
  }
  if (state_ != ACTIVE && state_ != UPDATING) {
    state_ = DEACTIVE;
    deformationImpl_->reset();
    return 0;
  }
  state_           = DEACTIVE;
  TStroke *out     = deformationImpl_->deactivate_impl();
  deformationImpl_ = 0;
  return out;
}
References ToonzExt::StrokeDeformationImpl::deactivate_impl(), and ToonzExt::StrokeDeformationImpl::reset().
Referenced by activate(), and PinchTool::onImageChanged().
draw()
void StrokeDeformation::draw (Designer * designer)
Apply a designer on current deformation.
{
  QMutexLocker sl(&s_mutex);
  assert(designer && "Designer is null!!!");
  if (!deformationImpl_ || !designer) return;
  // this is to draw the icon
  deformationImpl_->draw(designer);
  // this is to draw stroke when change something
  designer->draw(this);
}
References ToonzExt::StrokeDeformationImpl::draw().
getCopiedStroke()
const TStroke * StrokeDeformation::getCopiedStroke () const
Return the stroke selected from user.
{
  QMutexLocker sl(&s_mutex);
  if (deformationImpl_) return deformationImpl_->getCopiedStroke();
  return 0;
}
getCursorId()
int StrokeDeformation::getCursorId () const
Retrieve cursor associated to current deformator.
{
  QMutexLocker sl(&s_mutex);
  if (!deformationImpl_) return -1;
  return deformationImpl_->getCursorId();
}
getExtremes()
ToonzExt::Interval StrokeDeformation::getExtremes () const
Retrieve valid extremes for current manipulator/deformator.
{
  QMutexLocker sl(&s_mutex);
  if (!deformationImpl_) return Interval(-1, -1);
  return deformationImpl_->getExtremes();
}
getStatus()
const ContextStatus * StrokeDeformation::getStatus () const
Return the internal status of current deformation.
See also
ContextStatus
{
  QMutexLocker sl(&s_mutex);
  if (deformationImpl_) return deformationImpl_->getImplStatus();
  return 0;
}
getStroke()
const TStroke * StrokeDeformation::getStroke () const
Return the stroke selected from user.
{
  QMutexLocker sl(&s_mutex);
  if (deformationImpl_) return deformationImpl_->getStrokeSelected();
  return 0;
}
getTransformedStroke()
const TStroke * StrokeDeformation::getTransformedStroke () const
Return a reference to the stroke created to be manipulated.
Note
This stroke is different from stroke selected by user.
See also
getStroke
{
  QMutexLocker sl(&s_mutex);
  if (deformationImpl_) return deformationImpl_->getTransformedStroke();
  return 0;
}
reset()
void StrokeDeformation::reset ()
Clear inner status of Deformation.
{
  QMutexLocker sl(&s_mutex);
  state_ = RESETTED;
}
Referenced by PinchTool::onDeactivate(), PinchTool::onImageChanged(), and PinchTool::onLeave().
update()
void StrokeDeformation::update (const TPointD & delta)
Modify stroke.
{
  QMutexLocker sl(&s_mutex);
  assert(deformationImpl_ && "Deformation is null!!!");
  if (!deformationImpl_) {
    state_ = DEACTIVE;
    return;
  }
  if (state_ != ACTIVE && state_ != UPDATING) {
    deformationImpl_->reset();
    state_ = ACTIVE;
    return;
  }
  deformationImpl_->update_impl(delta);
  state_ = UPDATING;
}
References ToonzExt::StrokeDeformationImpl::reset(), and ToonzExt::StrokeDeformationImpl::update_impl().
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/ext/StrokeDeformation.h
E:/opentoonz/toonz/sources/tnzext/StrokeDeformation.cpp