opentoonz: LevelUpdater Class Reference
LevelUpdater Class Reference
#include <levelupdater.h>
Public Member Functions
LevelUpdater (TXshSimpleLevel *sl)
LevelUpdater (const TFilePath &path, TPropertyGroup *lwProperties=0)
TLevelWriterP getLevelWriter ()
TLevelReaderP getLevelReader ()
TLevelP getInputLevel ()
const TImageInfo * getImageInfo ()
Returns the image properties of the updated level, if one already exists.
void open (const TFilePath &src, TPropertyGroup *lwProperties)
void open (TXshSimpleLevel *sl)
bool opened () const
void update (const TFrameId &fid, const TImageP &img)
void close ()
void flush ()
Detailed Description
LevelUpdater is the preferential interface for dealing with conservative levels I/O in Toonz.
The Toonz Image library already provides the basic TLevelWriter interface
that can be used to save image levels on hard disk. This is usually sufficient to satisfy most needs, with a simple enough usage:
    TLevelWriterP lw(
      levelPath,                                          // Attach to the
required level path (creates level if none).
      Tiio::makeWriterProperties(levelPath.getType()));   // NOTE: Level
Properties are not read from an existing level.
    TPropertyGroup* props(lw->getProperties());
    assert(props);                                        // Currently
guaranteed ONLY if specified at lw's construction.
    props->getProperty("Bits Per Pixel")->setValue(L"64(RGBM)");
    lw->getFrameWriter(fid1)->save(img1);                 // Save image img1 at
frame fid1
    lw->getFrameWriter(fid2)->save(img2);                 // ...
Some output types, however, may not support image insertions in the middle of an already existing level, but just at the end <\I> (as is the case for movie formats like avi). In these cases, a newly created temporary file must be used to have both old and new images appended at the right time. Once the appending procedure ends, the temporary gets renamed to the original file. Additional files related to the level must be renamed too, such as the level's palette and content history.
Plus, as noted in the example, the format properties of any existing level at specified path must be manually retrieved.
The LevelUpdater is a wrapper class to both TLevelReader and TLevelWriter employable to deal with these subtelties with a simple, equivalent syntax to the one above:
    LevelUpdater lu(levelPath);                             // Attach to the
required level path (creates level if none).
                                                            // Reads any
existing level format properties.
    TPropertyGroup* props(lu.getLevelWriter()->getProperties());      //
Properties (eventually default ones) are ensured
    assert(props);                                                    // to
exist.
    props->getProperty("Bits Per Pixel")->setValue(L"64(RGBM)");
    lu.update(fid1, img1);                                  // Save image img1
at frame fid1
    lu.update(fid2, img2);                                  // ...
Warning
The LevelUpdater requires that saved images must be ordered by insertion frame <\B>. If necessary, users must have them sorted before supplying them tp the updater.
Constructor & Destructor Documentation
LevelUpdater() [1/3]
LevelUpdater::LevelUpdater ()
    : m_pg(0)
    , m_inputLevel(0)
    , m_currIdx(0)
    , m_imageInfo(0)
    , m_usingTemporaryFile(false)
    , m_opened(false) {}
LevelUpdater() [2/3]
LevelUpdater::LevelUpdater (TXshSimpleLevel * sl)
    : m_pg(0)
    , m_inputLevel(0)
    , m_imageInfo(0)
    , m_currIdx(0)
    , m_opened(false)
    , m_usingTemporaryFile(false) {
  open(sl);
}
LevelUpdater() [3/3]
LevelUpdater::LevelUpdater (const TFilePath & path, TPropertyGroup * lwProperties = 0)
    : m_pg(0)
    , m_inputLevel(0)
    , m_imageInfo(0)
    , m_currIdx(0)
    , m_opened(false)
    , m_usingTemporaryFile(false) {
  open(fp, lwProperties);
}
~LevelUpdater()
LevelUpdater::~LevelUpdater ()
{
  // Please, observe that the try-catch below here is NOT OPTIONAL.
  // IT IS AN ERROR TO THROW INSIDE A DESTRUCTOR. EVER.
  // Doing so damages the stack unwinding process - namely, it interferes
  // with the destruction of OTHER objects going out of scope.
  // C++ does NOT react well to that (ie could terminate() the process).
  try {
    close();
  } catch (...) {
  }
}
Member Function Documentation
close()
void LevelUpdater::close ()
Closes and flushes the level. In case temporary files were used for the level, they replace the originals now. In case the replace procedure failed, the temporaries are (silently, in current implementation) retained on disk.
{
  if (!m_opened) return;
  // Resume open for write
  resume();
  try {
    if (m_usingTemporaryFile) {
      // Add all remaining frames still in m_fids
      addFramesTo((int)m_fids.size());
      // Currently written level is temporary. It must be renamed to its
      // originally intended path,
      // if it's possible to write there. Now, if it's writable, in particular
      // it should be readable,
      // so m_lr should exist.
      // If not... well, the file was corrupt or something. Instead than
      // attempting to delete it,
      // we're begin conservative - this means that no data is lost, but
      // unfortunately temporaries
      // might pile up...
      if (m_lr) {
        TFilePath finalPath(m_lr->getFilePath()), tempPath(m_lw->getFilePath());
        // Release m_lr and m_lw - to be sure that no file is kept open while
        // renaming.
        // NOTE: releasing m_lr and m_lw should not throw anything. As stated
        // before, throwing
        //       in destructors is bad. I'm not sure this is actually guaranteed
        //       in Toonz, however :(
        m_lr = TLevelReaderP(), m_lw = TLevelWriterP();
        // A temp file didn't get created. What happened?  Force failure!
        if (!TFileStatus(tempPath).doesExist())
          throw TSystemException(tempPath, "cant find!");
        // Rename the level
        TSystem::removeFileOrLevel_throw(finalPath);
        TSystem::renameFileOrLevel_throw(finalPath,
                                         tempPath);  // finalPath <- tempPath
        // If present, add known trailing files
        if (finalPath.getType() == "tlv") {
          // Palette file
          TFilePath finalPalette = finalPath.withType("tpl");
          TFilePath tempPalette  = tempPath.withType("tpl");
          if (TFileStatus(finalPalette).doesExist()) {
            if (TFileStatus(tempPalette).doesExist())
              TSystem::deleteFile(finalPalette);
            TSystem::renameFile(finalPalette, tempPalette);
          }
          // History file
          TFilePath finalHistory = finalPath.withType("hst");
          TFilePath tempHistory  = tempPath.withType("hst");
          if (TFileStatus(tempHistory).doesExist()) {
            if (TFileStatus(finalHistory).doesExist())
              TSystem::deleteFile(finalHistory);
            TSystem::renameFile(finalHistory, tempHistory);
          }
        }
      }
      // NOTE: If for some reason m_lr was not present and we were using a
      // temporary file, no
      // renaming takes place. Users could see the __x temporaries and,
      // eventually, rename them manually
      // or see what's wrong with the unwritable file.
    }
    // Reset the updater's status
    reset();
  } catch (...) {
    // Some temporary object could not be renamed. Or some remaining frame could
    // not be added.
    // Hopefully, it was not about closing m_lr or m_lw.
    // However, we still intend to reset the updater's status before rethrowing.
    reset();
    throw;
  }
}
References TFilePath::withType().
flush()
void LevelUpdater::flush ()
Flushes the level currently opened for write, suspending the update procedure. Since a level cannot be both opened for read and write at the same time, users could require to flush all updates and suspend (without closing) an update procedure to read some of the data that has just been written. The update procedure will be resumed automatically at the next update() or close() invocation.
Warning
Not all file formats currently support this. A brief list of currently supporting formats include TLV, MOV and multi-file levels, whereas formats not supporting it include PLI and AVI (due to TLevelWriter not supporting appends to an already existing level).
{
  assert(m_opened);
  if (!m_lw) return;
  // In case the level writer could not be destroyed (bad, should really not
  // throw btw),
  // reset and rethrow
  try {
    m_lw = TLevelWriterP();
  } catch (...) {
    reset();
    throw;
  }
}
getImageInfo()
const TImageInfo * LevelUpdater::getImageInfo () inline
Returns the image properties of the updated level, if one already exists.
{ return m_imageInfo; }
getInputLevel()
TLevelP LevelUpdater::getInputLevel () inline
Returns a description of any already existing level on the attached path (in terms of frames content and palette).
{ return m_inputLevel; }
getLevelReader()
TLevelReaderP LevelUpdater::getLevelReader () inline
{ return m_lr; }
getLevelWriter()
TLevelWriterP LevelUpdater::getLevelWriter () inline
{ return m_lw; }
open() [1/2]
void LevelUpdater::open (const TFilePath & src, TPropertyGroup * lwProperties)
Attaches the updater to the specified path, using and taking ownership <\I> of the supplied write properties. This function may throw in case the specified path has an unrecognized extension, or the file could not be opened for write.
{
  assert(!m_lw);
  // Find out if a corresponding level already exists on disk - in that case,
  // load it
  bool existsLevel = TSystem::doesExistFileOrLevel(fp);
  if (existsLevel)
    buildSourceInfo(fp);  // Could be !m_lr if level could not be read
  // Build Output Properties if needed
  if (pg)
    m_pg = pg->clone();
  else
    buildProperties(fp);  // Throws only if not even the default properties
                          // could be found - ie, bad file type
  try {
    // Decide whether the update procedure requires a temporary file for
    // appending
    m_usingTemporaryFile = existsLevel && !supportsRandomAccess(fp);
    if (m_usingTemporaryFile) {
      // The level requires a temporary to write frames to. Upon closing, the
      // original level
      // is deleted and the temporary takes its place. Note that m_lw takes
      // ownership of the properties group.
      m_lwPath = getNewTemporaryFilePath(fp);
      m_lw     = TLevelWriterP(m_lwPath, m_pg->clone());
      if (m_inputLevel)
        for (TLevel::Iterator it = m_inputLevel->begin();
             it != m_inputLevel->end(); ++it)
          m_fids.push_back(it->first);
    } else {
      m_lr =
          TLevelReaderP();  // Release the reader. This is necessary since the
      m_lw = TLevelWriterP(
          fp, m_pg->clone());  // original file itself will be MODIFIED.
      m_lwPath = fp;
    }
  } catch (...) {
    // In this case, TLevelWriterP(..) failed, that object was never
    // constructed,
    // the assignment m_lw never took place. And m_lw == 0.
    // Reset state and rethrow
    reset();
    throw;
  }
  // In case the writer saves icons inside the output level (TLV case), set the
  // associated icon size now
  TDimension iconSize = Preferences::instance()->getIconSize();
  assert(iconSize.lx > 0 && iconSize.ly > 0);
  m_lw->setIconSize(iconSize);
  m_opened = true;
}
open() [2/2]
void LevelUpdater::open (TXshSimpleLevel * sl)
Attaches the updater to the specified simple level instance. Format properties are the default in case the level is saved anew. If the level requires the alpha channel, evenutal bpp and alpha properties are upgraded accordingly. This function may throw just like its path-based counterpart.
{
  assert(!m_lw);
  assert(sl && sl->getScene());
  m_sl = sl;
  const TFilePath &fp = sl->getScene()->decodeFilePath(sl->getPath());
  // Find out if a corresponding level already exists on disk - in that case,
  // load it
  bool existsLevel = TSystem::doesExistFileOrLevel(fp);
  if (existsLevel)
    buildSourceInfo(fp);  // Could be !m_lr if level could not be read
  // Build Output Properties
  buildProperties(fp);  // May throw if not even the default properties could be
                        // retrieved
  // If there was no level on disk, or the level properties require the alpha
  // channel, enforce the
  // bpp accordingly on m_pg.
  LevelProperties *levelProperties = sl->getProperties();
  assert(levelProperties);
  if (levelProperties->hasAlpha() || !existsLevel) {
    int bpp = levelProperties->hasAlpha()
                  ? std::min(32, levelProperties->getBpp())
                  : levelProperties->getBpp();
    enforceBpp(m_pg, bpp, existsLevel);
  }
  // Should sl->getPalette() be enforced on m_lw too? It was not present in the
  // old code...
  try {
    // Decide whether the update procedure requires a temporary file for
    // appending
    m_usingTemporaryFile = existsLevel && !supportsRandomAccess(fp);
    if (m_usingTemporaryFile) {
      // The level requires a temporary to write frames to. Upon closing, the
      // original level
      // is deleted and the temporary takes its place.
      m_lwPath = getNewTemporaryFilePath(fp);
      m_lw     = TLevelWriterP(m_lwPath, m_pg->clone());
    } else {
      m_lr = TLevelReaderP();                   // Release the reader
      m_lw = TLevelWriterP(fp, m_pg->clone());  // Open for write the usual way
      m_lwPath = fp;
    }
  } catch (...) {
    // Reset state and rethrow
    reset();
    throw;
  }
  // Load the frames directly from sl
  sl->getFids(m_fids);
  // In case the writer saves icons inside the output level (TLV case), set the
  // associated icon size now
  TDimension iconSize = Preferences::instance()->getIconSize();
  assert(iconSize.lx > 0 && iconSize.ly > 0);
  m_lw->setIconSize(iconSize);
  if (sl->getContentHistory())
    m_lw->setContentHistory(m_sl->getContentHistory()->clone());
  m_opened = true;
}
References ToonzScene::decodeFilePath(), LevelProperties::getBpp(), TXshSimpleLevel::getContentHistory(), TXshSimpleLevel::getFids(), TXshSimpleLevel::getPath(), TXshSimpleLevel::getProperties(), TXshLevel::getScene(), and LevelProperties::hasAlpha().
opened()
bool LevelUpdater::opened () const inline
{ return m_opened; }
update()
void LevelUpdater::update (const TFrameId & fid, const TImageP & img)
Stores the supplied image in the level, at the specified frame. Remember that frames must be added with increasing fid ordering.
{
  // Resume open for write
  resume();
  if (!m_usingTemporaryFile) {
    // Plain random access write if supported
    m_lw->getFrameWriter(fid)->save(img);
    return;
  }
  // Otherwise, we must add every frame preceding fid, and *then* add img.
  // NOTE: This requires that the image sequence is already sorted by fid.
  addFramesTo(std::lower_bound(m_fids.begin() + m_currIdx, m_fids.end(), fid) -
              m_fids.begin());
  // Save the passed image. In case it overwrites a frame, erase that from the
  // list too.
  m_lw->getFrameWriter(fid)->save(img);
  if (m_currIdx < int(m_fids.size()) && m_fids[m_currIdx] == fid) ++m_currIdx;
}
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/toonz/levelupdater.h
E:/opentoonz/toonz/sources/toonzlib/levelupdater.cpp