opentoonz: RasterSelection Class Reference
RasterSelection Class Reference final
Selection of TToonzImage and TRasterImage.
#include <rasterselection.h>
Public Member Functions
RasterSelection (const RasterSelection &src)
TSelection * clone () const
Returns the clone of this selection.
void notify ()
Notify to the viewer that the selection is changed.
const TImageP & getCurrentImage () const
const TXshCell & getCurrentImageCell () const
void setCurrentImage (const TImageP &img, const TXshCell &imageCell)
void setStrokes (const std::vector< TStroke > &strokes)
std::vector< TStroke > getStrokes () const
std::vector< TStroke > getOriginalStrokes () const
void setTransformation (const TAffine &affine)
TAffine getTransformation () const
void setStartPosition (const TPoint &position)
TPoint getStartPosition () const
void setFloatingSeletion (const TRasterP &floatingSelection)
TRasterP getFloatingSelection () const
TRasterP getOriginalFloatingSelection () const
void setFrameId (const TFrameId &fid)
TFrameId getFrameId () const
int getTransformationCount () const
void setTransformationCount (int transformationCount)
void setNoAntialiasing (bool value)
bool isPastedSelection () const
TRectD getStrokesBound (std::vector< TStroke > strokes) const
TRectD getSelectionBound () const
TRectD getOriginalSelectionBound () const
TRectD getSelectionBbox () const
void setSelectionBbox (const TRectD &rect)
void selectNone () override
void select (const TRectD &rect)
Take a rect in world coordinates and put it in the selection.
void select (TStroke &stroke)
void selectAll ()
bool isEmpty () const override
void enableCommands () override
bool isFloating () const
void transform (const TAffine &affine)
void makeFloating ()
Build the floating image using m_strokes.
void pasteFloatingSelection ()
Paste the floating image over the current image and empty the selection.
void deleteSelection ()
Delete the floating image.
void copySelection ()
Copy the floating image in the clipboard.
void cutSelection ()
Cut the floating image.
void pasteSelection ()
Create the floating image using clipboard Data.
bool isTransformed ()
bool isEditable ()
Public Member Functions inherited from TSelection
virtual void enableCommands ()
void enableCommand (CommandId cmdId, CommandHandlerInterface *handler)
template<class T >
void enableCommand (T *target, CommandId cmdId, void(T::*method)())
template<class T , typename R >
void enableCommand (T *target, CommandId cmdId, void(T::*method)(R), R value)
void makeCurrent ()
void makeNotCurrent ()
virtual bool isEmpty () const =0
virtual void selectNone ()=0
virtual bool addMenuActions (QMenu *menu)
void addMenuAction (QMenu *menu, CommandId cmdId)
void setView (View *view)
View * getView () const
void notifyView ()
Additional Inherited Members
Static Public Member Functions inherited from TSelection
static TSelection * getCurrent ()
static void setCurrent (TSelection *selection)
Detailed Description
Selection of TToonzImage and TRasterImage.
Constructor & Destructor Documentation
RasterSelection() [1/2]
RasterSelection::RasterSelection ()
    : TSelection()
    , m_currentImage()
    , m_oldPalette(0)
    , m_selectionBbox()
    , m_affine()
    , m_startPosition()
    , m_floatingSelection()
    , m_originalfloatingSelection()
    , m_fid()
    , m_transformationCount(0)
    , m_isPastedSelection(false)
    , m_noAntialiasing(false) {
  m_strokes.clear();
  m_originalStrokes.clear();
}
RasterSelection() [2/2]
RasterSelection::RasterSelection (const RasterSelection & src)
    : TSelection()
    , m_currentImage(src.m_currentImage)
    , m_oldPalette(src.m_oldPalette)
    , m_selectionBbox(src.m_selectionBbox)
    , m_strokes(src.m_strokes)
    , m_originalStrokes(src.m_originalStrokes)
    , m_affine(src.m_affine)
    , m_startPosition(src.m_startPosition)
    , m_fid(src.m_fid)
    , m_transformationCount(src.m_transformationCount)
    , m_isPastedSelection(src.m_isPastedSelection)
    , m_noAntialiasing(src.m_noAntialiasing)
{
  setView(src.getView());
  if (src.isFloating()) {
    m_floatingSelection = src.m_floatingSelection->clone();
    if (src.m_originalfloatingSelection)
      m_originalfloatingSelection = src.m_originalfloatingSelection->clone();
    assert(isFloating());
  }
}
Member Function Documentation
clone()
TSelection * RasterSelection::clone () const
Returns the clone of this selection.
{
  RasterSelection *rs = new RasterSelection(*this);
  return rs;
}
copySelection()
void RasterSelection::copySelection ()
Copy the floating image in the clipboard.
{
  if (isEmpty() || !m_currentImage) return;
  TRasterP ras;
  if (!isFloating())
    ras = getImageFromSelection(m_currentImage, *this);
  else
    ras = m_floatingSelection;
  double dpix, dpiy;
  std::vector<TRectD> rect;
  if (TToonzImageP ti = (TToonzImageP)(m_currentImage)) {
    ToonzImageData *data = new ToonzImageData();
    ti->getDpi(dpix, dpiy);
    data->setData(ras, ti->getPalette(), dpix, dpiy, ti->getSize(), rect,
                  m_strokes, m_originalStrokes, m_affine);
    QApplication::clipboard()->setMimeData(cloneData(data));
  } else if (TRasterImageP ri = (TRasterImageP)(m_currentImage)) {
    FullColorImageData *data = new FullColorImageData();
    ri->getDpi(dpix, dpiy);
    data->setData(ras, ri->getPalette(), dpix, dpiy, ri->getRaster()->getSize(),
                  rect, m_strokes, m_originalStrokes, m_affine);
    QApplication::clipboard()->setMimeData(cloneData(data));
  }
}
Referenced by cutSelection().
cutSelection()
void RasterSelection::cutSelection ()
Cut the floating image.
{
  copySelection();
  deleteSelection();
}
References copySelection(), and deleteSelection().
deleteSelection()
void RasterSelection::deleteSelection ()
Delete the floating image.
{
  if (!m_currentImage) return;
  TTool::Application *app = TTool::getApplication();
  TXshSimpleLevel *level  = app->getCurrentLevel()->getSimpleLevel();
  if (!isEditable()) {
    DVGui::error(
        QObject::tr("The selection cannot be deleted. It is not editable."));
    return;
  }
  // we have to remove all undo transformation and the undo for the makeFloating
  // operation!
  if (isFloating()) {
    assert(m_transformationCount != -1 && m_transformationCount != -2);
    if (m_isPastedSelection)
      TUndoManager::manager()->popUndo(m_transformationCount + 1);
    else
      TUndoManager::manager()->popUndo(m_transformationCount);
  }
  if (!isPastedSelection() && !isEmpty())
    TUndoManager::manager()->add(new UndoDeleteSelection(this, level));
  if (!isFloating())
    deleteSelectionWithoutUndo(m_currentImage, m_strokes);
  else if (m_oldPalette)
    m_currentImage->getPalette()->assign(m_oldPalette.getPointer());
  m_floatingSelection         = TRasterP();
  m_originalfloatingSelection = TRasterP();
  ToolUtils::updateSaveBox();
  selectNone();
  app->getPaletteController()->getCurrentLevelPalette()->notifyPaletteChanged();
  TTool *tool = app->getCurrentTool()->getTool();
  tool->notifyImageChanged(m_fid);
}
References TPalette::assign(), TTool::notifyImageChanged(), TUndoManager::popUndo(), and selectNone().
Referenced by cutSelection().
enableCommands()
void RasterSelection::enableCommands () override virtual
Reimplemented from TSelection.
{
  enableCommand(this, MI_Clear, &RasterSelection::deleteSelection);
  enableCommand(this, MI_Cut, &RasterSelection::cutSelection);
  enableCommand(this, MI_Copy, &RasterSelection::copySelection);
  enableCommand(this, MI_Paste, &RasterSelection::pasteSelection);
  enableCommand(this, MI_SelectAll, &RasterSelection::selectAll);
}
getCurrentImage()
const TImageP & RasterSelection::getCurrentImage () const inline
{ return m_currentImage; }
getCurrentImageCell()
const TXshCell & RasterSelection::getCurrentImageCell () const inline
{ return m_currentImageCell; }
getFloatingSelection()
TRasterP RasterSelection::getFloatingSelection () const inline
{ return m_floatingSelection; }
getFrameId()
TFrameId RasterSelection::getFrameId () const inline
{ return m_fid; }
getOriginalFloatingSelection()
TRasterP RasterSelection::getOriginalFloatingSelection () const inline
{
    return m_originalfloatingSelection;
  }
getOriginalSelectionBound()
TRectD RasterSelection::getOriginalSelectionBound () const
Returns m_originlStrokes bounding box in world coordinates.
{
  if (m_originalStrokes.size() == 0) return TRectD();
  return getStrokesBound(m_originalStrokes);
}
References getStrokesBound().
getOriginalStrokes()
std::vector< TStroke > RasterSelection::getOriginalStrokes () const inline
{ return m_originalStrokes; }
getSelectionBbox()
TRectD RasterSelection::getSelectionBbox () const
Return m_selectionBbox. Can be different from getSelectionBound() after a free deform transformation.
{
  TRectD rect = m_selectionBbox;
  if (isFloating()) rect = m_affine * m_selectionBbox;
  return rect;
}
Referenced by pasteFloatingSelection().
getSelectionBound()
TRectD RasterSelection::getSelectionBound () const
Returns m_strokes bounding box in world coordinates. The bounding box results transformed if the selection is transformed.
{
  if (m_strokes.size() == 0) return TRectD();
  TRectD selectionBox = getStrokesBound(m_strokes);
  if (isFloating()) selectionBox = m_affine * selectionBox;
  return selectionBox;
}
References getStrokesBound().
getStartPosition()
TPoint RasterSelection::getStartPosition () const inline
{ return m_startPosition; }
getStrokes()
std::vector< TStroke > RasterSelection::getStrokes () const inline
{ return m_strokes; }
getStrokesBound()
TRectD RasterSelection::getStrokesBound (std::vector< TStroke > strokes) const
Returns strokes bounding box.
{
  int i;
  TRectD box = TRectD();
  for (i = 0; i < (int)strokes.size(); i++) box += strokes[i].getBBox();
  return box;
}
Referenced by getOriginalSelectionBound(), and getSelectionBound().
getTransformation()
TAffine RasterSelection::getTransformation () const inline
{ return m_affine; }
getTransformationCount()
int RasterSelection::getTransformationCount () const inline
{ return m_transformationCount; }
isEditable()
bool RasterSelection::isEditable ()
{
  TTool::Application *app = TTool::getApplication();
  TXshSimpleLevel *level  = app->getCurrentLevel()->getSimpleLevel();
  TFrameHandle *frame = app->getCurrentFrame();
  bool filmstrip      = frame->isEditingLevel();
  if (level) {
    if (level->isReadOnly()) return false;
    TFrameId frameId = app->getCurrentTool()->getTool()->getCurrentFid();
    if (level->isFrameReadOnly(frameId)) return false;
  }
  if (!filmstrip) {
    int colIndex = app->getCurrentTool()->getTool()->getColumnIndex();
    int rowIndex = frame->getFrame();
    if (app->getCurrentTool()->getTool()->isColumnLocked(colIndex))
      return false;
    TXsheet *xsh      = app->getCurrentXsheet()->getXsheet();
    TStageObject *obj = xsh->getStageObject(TStageObjectId::ColumnId(colIndex));
    // Test for Mesh-deformed levels
    const TStageObjectId &parentId = obj->getParent();
    if (parentId.isColumn() && obj->getParentHandle()[0] != 'H') {
      TXshSimpleLevel *parentSl =
          xsh->getCell(rowIndex, parentId.getIndex()).getSimpleLevel();
      if (parentSl && parentSl->getType() == MESH_XSHLEVEL) return false;
    }
  }
  return true;
}
isEmpty()
bool RasterSelection::isEmpty () const override virtual
Implements TSelection.
{
  return getStrokesBound(m_strokes).isEmpty();
}
isFloating()
bool RasterSelection::isFloating () const
{ return m_floatingSelection; }
isPastedSelection()
bool RasterSelection::isPastedSelection () const inline
{ return m_isPastedSelection; }
isTransformed()
bool RasterSelection::isTransformed ()
{ return !m_affine.isIdentity(); }
makeFloating()
void RasterSelection::makeFloating ()
Build the floating image using m_strokes.
{
  if (isEmpty()) return;
  if (!m_currentImage) return;
  if (!isEditable()) return;
  m_floatingSelection         = getImageFromSelection(m_currentImage, *this);
  m_originalfloatingSelection = m_floatingSelection->clone();
  deleteSelectionWithoutUndo(m_currentImage, m_strokes);
  ToolUtils::updateSaveBox();
  TTool *tool = TTool::getApplication()->getCurrentTool()->getTool();
  tool->notifyImageChanged(m_fid);
}
References TTool::notifyImageChanged().
notify()
void RasterSelection::notify ()
Notify to the viewer that the selection is changed.
{
  RasterSelection *selection = dynamic_cast<RasterSelection *>(
      TTool::getApplication()->getCurrentSelection()->getSelection());
  if (selection) selection->notifyView();
}
Referenced by pasteSelection(), select(), and selectNone().
pasteFloatingSelection()
void RasterSelection::pasteFloatingSelection ()
Paste the floating image over the current image and empty the selection.
{
  if (!isFloating()) return;
  assert(m_transformationCount != -1 && m_transformationCount != -2);
  if (m_isPastedSelection)
    TUndoManager::manager()->popUndo(m_transformationCount + 1);
  else
    TUndoManager::manager()->popUndo(m_transformationCount);
  if (m_transformationCount > 0 || m_isPastedSelection)
    TUndoManager::manager()->add(new UndoPasteFloatingSelection(
        this, m_oldPalette.getPointer(), m_noAntialiasing));
  else if (m_transformationCount == 0)
    TUndoManager::manager()->popUndo(-1, true);
  TRectD wRect = getSelectionBbox();
  pasteFloatingSelectionWithoutUndo(m_currentImage, m_floatingSelection,
                                    m_affine, wRect, m_noAntialiasing);
  ToolUtils::updateSaveBox(m_currentImageCell.getSimpleLevel(),
                           m_currentImageCell.getFrameId());
  setFloatingSeletion(TRasterP());
  selectNone();
  TTool *tool = TTool::getApplication()->getCurrentTool()->getTool();
  tool->notifyImageChanged(m_fid);
}
References TXshCell::getFrameId(), getSelectionBbox(), TXshCell::getSimpleLevel(), TTool::notifyImageChanged(), TUndoManager::popUndo(), and selectNone().
Referenced by pasteSelection(), and selectNone().
pasteSelection()
void RasterSelection::pasteSelection ()
Create the floating image using clipboard Data.
{
  TTool::Application *app = TTool::getApplication();
  TTool *tool             = app->getCurrentTool()->getTool();
  TImageP image           = tool->touchImage();
  if (!image) return;
  if (!isEditable()) {
    DVGui::error(
        QObject::tr("The selection cannot be pasted. It is not editable."));
    return;
  }
  m_currentImage = image;
  m_fid          = tool->getCurrentFid();
  QClipboard *clipboard = QApplication::clipboard();
  const RasterImageData *riData =
      dynamic_cast<const RasterImageData *>(clipboard->mimeData());
  const StrokesData *stData =
      dynamic_cast<const StrokesData *>(clipboard->mimeData());
  if (!riData && !stData) return;
  if (isFloating()) pasteFloatingSelection();
  selectNone();
  m_isPastedSelection = true;
  m_oldPalette        = m_currentImage->getPalette()->clone();
  if (stData) {
    if (TToonzImageP ti = m_currentImage)
      riData = stData->toToonzImageData(ti);
    else {
      TRasterImageP ri = m_currentImage;
      assert(ri);
      double dpix, dpiy;
      ri->getDpi(dpix, dpiy);
      if (dpix == 0 || dpiy == 0) {
        TPointD dpi =
            tool->getXsheet()->getScene()->getCurrentCamera()->getDpi();
        dpix = dpi.x;
        dpiy = dpi.y;
        ri->setDpi(dpix, dpiy);
      }
      riData = stData->toFullColorImageData(ri);
    }
  }
  if (!riData) return;
  pasteSelection(riData);
  app->getPaletteController()->getCurrentLevelPalette()->notifyPaletteChanged();
  notify();
  TUndoManager::manager()->add(new UndoPasteSelection(this));
}
References ToonzScene::getCurrentCamera(), TTool::getCurrentFid(), TCamera::getDpi(), TXsheet::getScene(), TTool::getXsheet(), notify(), pasteFloatingSelection(), pasteSelection(), selectNone(), and TTool::touchImage().
Referenced by pasteSelection().
select() [1/2]
void RasterSelection::select (const TRectD & rect)
Take a rect in world coordinates and put it in the selection.
{
  assert(!!m_currentImage);
  TRectD r  = rect;
  TRect box = getRaster(m_currentImage)->getBounds();
  r *= convertRasterToWorld(box, m_currentImage);
  if (!r.isEmpty()) {
    TStroke stroke = getStrokeByRect(r);
    if ((int)stroke.getControlPointCount() == 0) return;
    m_strokes.push_back(stroke);
    m_originalStrokes.push_back(stroke);
  }
  notify();
}
References TStroke::getControlPointCount(), TRectT< T >::isEmpty(), and notify().
select() [2/2]
void RasterSelection::select (TStroke & stroke)
{
  TRect box                 = getRaster(m_currentImage)->getBounds();
  TRectD rasterBbox         = convertRasterToWorld(box, m_currentImage);
  TStroke intersectedStroke = getIntersectedStroke(stroke, rasterBbox);
  if ((int)intersectedStroke.getControlPointCount() == 0) return;
  m_strokes.push_back(intersectedStroke);
  m_originalStrokes.push_back(intersectedStroke);
  notify();
}
selectAll()
void RasterSelection::selectAll ()
{
  if (!m_currentImage) return;
  selectNone();
  TRectD wRect = convertRasterToWorld(getRaster(m_currentImage)->getBounds(),
                                      m_currentImage);
  select(wRect);
}
selectNone()
void RasterSelection::selectNone () override virtual
Empty the selection. If the selection is floating, the floating image is pasted using the current transformation.
Implements TSelection.
{
  if (isFloating()) {
    pasteFloatingSelection();
    notify();
    return;
  }
  m_selectionBbox = TRectD();
  m_strokes.clear();
  m_originalStrokes.clear();
  m_affine                    = TAffine();
  m_startPosition             = TPoint();
  m_floatingSelection         = TRasterP();
  m_originalfloatingSelection = TRasterP();
  m_transformationCount       = 0;
  m_isPastedSelection         = false;
  m_oldPalette                = 0;
  notify();
}
References notify(), and pasteFloatingSelection().
Referenced by deleteSelection(), pasteFloatingSelection(), and pasteSelection().
setCurrentImage()
void RasterSelection::setCurrentImage (const TImageP & img, const TXshCell & imageCell) inline
{
    m_currentImage = img, m_currentImageCell = imageCell;
  }
setFloatingSeletion()
void RasterSelection::setFloatingSeletion (const TRasterP & floatingSelection) inline
{
    m_floatingSelection = floatingSelection;
  }
setFrameId()
void RasterSelection::setFrameId (const TFrameId & fid) inline
{ m_fid = fid; }
setNoAntialiasing()
void RasterSelection::setNoAntialiasing (bool value) inline
{ m_noAntialiasing = value; }
setSelectionBbox()
void RasterSelection::setSelectionBbox (const TRectD & rect)
{
  m_selectionBbox = rect;
}
setStartPosition()
void RasterSelection::setStartPosition (const TPoint & position) inline
{ m_startPosition = position; }
setStrokes()
void RasterSelection::setStrokes (const std::vector< TStroke > & strokes) inline
{ m_strokes = strokes; }
setTransformation()
void RasterSelection::setTransformation (const TAffine & affine) inline
{ m_affine = affine; }
setTransformationCount()
void RasterSelection::setTransformationCount (int transformationCount) inline
{
    m_transformationCount = transformationCount;
  }
transform()
void RasterSelection::transform (const TAffine & affine)
{
  m_affine = affine * m_affine;
}
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/tools/rasterselection.h
E:/opentoonz/toonz/sources/tnztools/rasterselection.cpp