opentoonz: ImageViewer Class Reference
ImageViewer Class Reference final
The ImageViewer class provides to view an image.
Public Slots
void updateImageViewer ()
void resetView ()
void fitView ()
void showHistogram ()
void swapCompared ()
void onContextAboutToBeDestroyed ()
void onPreferenceChanged (const QString &prefName)
Public Member Functions
ImageViewer (QWidget *parent, FlipBook *flipbook, bool showHistogram)
void setIsColorModel (bool isColorModel)
bool isColorModel ()
void setVisual (const ImagePainter::VisualSettings &settings)
void setImage (TImageP image)
TImageP getImage ()
TAffine getViewAff ()
void setViewAff (TAffine viewAff)
TAffine getImgToWidgetAffine (const TRectD &imgBounds) const
Returns the affine transform from image reference to widget's pixel one.
TAffine getImgToWidgetAffine () const
void setHistogramTitle (QString levelName)
void setHistogramEnable (bool enable)
void hideHistogram ()
void zoomQt (bool forward, bool reset)
void resetZoom ()
void setIsRemakingPreviewFx (bool on)
bool isRemakingPreviewFx ()
void adaptView (const TRect &imgRect, const TRect &viewRect)
void adaptView (const QRect &viewerRect)
void doSwapBuffers ()
void changeSwapBehavior (bool enable)
void invalidateCompHisto ()
void setTimerAndTargetInstant (QElapsedTimer *timer, qint64 target)
Public Member Functions inherited from GLWidgetForHighDpi
GLWidgetForHighDpi (QWidget *parent=nullptr, Qt::WindowFlags f=Qt::WindowFlags())
int width () const
int height () const
QRect rect () const
Protected Member Functions
void contextMenuEvent (QContextMenuEvent *event) override
void initializeGL () override
void resizeGL (int width, int height) override
void paintGL () override
void showEvent (QShowEvent *) override
void hideEvent (QHideEvent *) override
void mouseMoveEvent (QMouseEvent *event) override
void mousePressEvent (QMouseEvent *event) override
void mouseReleaseEvent (QMouseEvent *event) override
void keyPressEvent (QKeyEvent *event) override
void mouseDoubleClickEvent (QMouseEvent *event) override
void wheelEvent (QWheelEvent *) override
void panQt (const QPoint &delta)
void zoomQt (const QPoint &center, double factor)
void dragCompare (const QPoint &dp)
void tabletEvent (QTabletEvent *e) override
void touchEvent (QTouchEvent *e, int type)
void gestureEvent (QGestureEvent *e)
bool event (QEvent *e) override
Detailed Description
The ImageViewer class provides to view an image.
Inherits QOpenGLWidget.
The object allows also to manage pan and zoom event. It's possible to set a color mask TRop::ColorMask to image view.
Constructor & Destructor Documentation
ImageViewer()
ImageViewer::ImageViewer (QWidget * parent, FlipBook * flipbook, bool showHistogram)
    : GLWidgetForHighDpi(parent)
    , m_pressedMousePos(0, 0)
    , m_mouseButton(Qt::NoButton)
    , m_draggingZoomSelection(false)
    , m_image()
    , m_FPS(0)
    , m_viewAff()
    , m_pos(0, 0)
    , m_visualSettings()
    , m_compareSettings()
    , m_isHistogramEnable(showHistogram)
    , m_flipbook(flipbook)
    , m_isColorModel(false)
    , m_histogramPopup(0)
    , m_isRemakingPreviewFx(false)
    , m_rectRGBPick(false)
    , m_firstImage(true)
    , m_timer(nullptr) {
  m_visualSettings.m_sceneProperties =
      TApp::instance()->getCurrentScene()->getScene()->getProperties();
  m_visualSettings.m_drawExternalBG = true;
  setAttribute(Qt::WA_KeyCompression);
  setFocusPolicy(Qt::StrongFocus);
  setMouseTracking(true);
  setAttribute(Qt::WA_AcceptTouchEvents);
  grabGesture(Qt::SwipeGesture);
  grabGesture(Qt::PanGesture);
  grabGesture(Qt::PinchGesture);
  if (m_isHistogramEnable)
    m_histogramPopup = new HistogramPopup(tr("Flipbook Histogram"));
  if (Preferences::instance()->isColorCalibrationEnabled())
    m_lutCalibrator = new LutCalibrator();
  if (Preferences::instance()->is30bitDisplayEnabled())
    setTextureFormat(TGL_TexFmt10);
}
~ImageViewer()
ImageViewer::~ImageViewer ()
{
  // iwsw commented out temporarily
  /*
  if (m_ghibli3DLutUtil)
  {
          m_ghibli3DLutUtil->onEnd();
          delete m_ghibli3DLutUtil;
  }
  */
  if (m_fbo) delete m_fbo;
}
Member Function Documentation
adaptView() [1/2]
void ImageViewer::adaptView (const QRect & geomRect)
Adapts image viewer's affine to display the passed viewer rect at maximized ratio
{
  if (!m_image) return;
  // Retrieve the rect in image reference and call the associated adaptView
  TRect imgBounds(getImageBounds(m_image));
  TRectD imgBoundsD(imgBounds.x0, imgBounds.y0, imgBounds.x1 + 1,
                    imgBounds.y1 + 1);
  TRectD geomRectD(geomRect.left(), geomRect.top(), geomRect.right() + 1,
                   geomRect.bottom() + 1);
  TRectD viewRectD(getImgToWidgetAffine().inv() * geomRectD);
  TRect viewRect(tfloor(viewRectD.x0), tfloor(viewRectD.y0),
                 tceil(viewRectD.x1) - 1, tceil(viewRectD.y1) - 1);
  adaptView(imgBounds, viewRect);
}
References adaptView(), getImgToWidgetAffine(), and TRectT< T >::x0.
adaptView() [2/2]
void ImageViewer::adaptView (const TRect & imgRect, const TRect & viewRect)
Adapts image viewer's affine to display the passed image rect at maximized ratio
{
  QRect viewerRect(rect());
  if (viewerRect.isEmpty()) return;
  double imageScale = std::min(viewerRect.width() / (double)viewRect.getLx(),
                               viewerRect.height() / (double)viewRect.getLy());
  TPointD viewRectCenter((viewRect.x0 + viewRect.x1 + 1) * 0.5,
                         (viewRect.y0 + viewRect.y1 + 1) * 0.5);
  TPointD imgRectCenter((imgRect.x0 + imgRect.x1 + 1) * 0.5,
                        (imgRect.y0 + imgRect.y1 + 1) * 0.5);
  TAffine newViewAff(TScale(imageScale, imageScale) *
                     TTranslation(imgRectCenter - viewRectCenter));
  setViewAff(newViewAff);
}
References TRectT< T >::x0.
Referenced by adaptView(), and mouseReleaseEvent().
changeSwapBehavior()
void ImageViewer::changeSwapBehavior (bool enable)
{
  // do nothing for now as setUpdateBehavior is not available with QGLWidget
  // setUpdateBehavior(enable ? PartialUpdate : NoPartialUpdate);
}
contextMenuEvent()
void ImageViewer::contextMenuEvent (QContextMenuEvent * event) override protected
{
  QAction *action;
  if (m_isColorModel) {
    event->ignore();
    return;
  }
  QMenu *menu = new QMenu(this);
  if (m_flipbook) {
    if (m_flipbook->getPreviewedFx()) {
      if (!(windowState() & Qt::WindowFullScreen)) {
        action = menu->addAction(tr("Clone Preview"));
        action->setShortcut(QKeySequence(
            CommandManager::instance()->getKeyFromId(MI_ClonePreview)));
        connect(action, SIGNAL(triggered()), m_flipbook, SLOT(clonePreview()));
      }
      if (m_flipbook->isFreezed()) {
        action = menu->addAction(tr("Unfreeze Preview"));
        action->setShortcut(QKeySequence(
            CommandManager::instance()->getKeyFromId(MI_FreezePreview)));
        connect(action, SIGNAL(triggered()), m_flipbook,
                SLOT(unfreezePreview()));
      } else {
        action = menu->addAction(tr("Freeze Preview"));
        action->setShortcut(QKeySequence(
            CommandManager::instance()->getKeyFromId(MI_FreezePreview)));
        connect(action, SIGNAL(triggered()), m_flipbook, SLOT(freezePreview()));
      }
      action = menu->addAction(tr("Regenerate Preview"));
      action->setShortcut(QKeySequence(
          CommandManager::instance()->getKeyFromId(MI_RegeneratePreview)));
      connect(action, SIGNAL(triggered()), m_flipbook, SLOT(regenerate()));
      action = menu->addAction(tr("Regenerate Frame Preview"));
      action->setShortcut(QKeySequence(
          CommandManager::instance()->getKeyFromId(MI_RegenerateFramePr)));
      connect(action, SIGNAL(triggered()), m_flipbook, SLOT(regenerateFrame()));
      menu->addSeparator();
    }
    action = menu->addAction(tr("Load / Append Images"));
    connect(action, SIGNAL(triggered()), m_flipbook, SLOT(loadImages()));
    // history of the loaded paths of flipbook
    action = CommandManager::instance()->getAction(MI_LoadRecentImage);
    menu->addAction(action);
    action->setParent(m_flipbook);
    menu->addSeparator();
  }
  QAction *reset = menu->addAction(tr("Reset View"));
  reset->setShortcut(
      QKeySequence(CommandManager::instance()->getKeyFromId(V_ViewReset)));
  connect(reset, SIGNAL(triggered()), SLOT(resetView()));
  QAction *fit = menu->addAction(tr("Fit To Window"));
  fit->setShortcut(
      QKeySequence(CommandManager::instance()->getKeyFromId(V_ZoomFit)));
  connect(fit, SIGNAL(triggered()), SLOT(fitView()));
  if (m_flipbook) {
#ifdef _WIN32
    if (ImageUtils::FullScreenWidget *fsWidget =
            dynamic_cast<ImageUtils::FullScreenWidget *>(parentWidget())) {
      bool isFullScreen = (fsWidget->windowState() & Qt::WindowFullScreen) != 0;
      action = menu->addAction(isFullScreen ? tr("Exit Full Screen Mode")
                                            : tr("Full Screen Mode"));
      action->setShortcut(QKeySequence(
          CommandManager::instance()->getKeyFromId(V_ShowHideFullScreen)));
      connect(action, SIGNAL(triggered()), fsWidget, SLOT(toggleFullScreen()));
    }
#endif
    bool addedSep = false;
    if (m_isHistogramEnable &&
        visibleRegion().contains(event->pos() * getDevPixRatio())) {
      menu->addSeparator();
      addedSep = true;
      action   = menu->addAction(tr("Show Histogram"));
      connect(action, SIGNAL(triggered()), SLOT(showHistogram()));
    }
    if (m_visualSettings.m_doCompare) {
      if (!addedSep) {
        menu->addSeparator();
        addedSep = true;
      }
      action = menu->addAction(tr("Swap Compared Images"));
      connect(action, SIGNAL(triggered()), SLOT(swapCompared()));
    }
    if (m_flipbook->isSavable()) {
      if (!addedSep) menu->addSeparator();
      action = menu->addAction(tr("Save Images"));
      connect(action, SIGNAL(triggered()), m_flipbook, SLOT(saveImages()));
    }
  }
  menu->exec(event->globalPos());
  if (m_flipbook) {
    action = CommandManager::instance()->getAction(MI_LoadRecentImage);
    action->setParent(0);
  }
  delete menu;
  update();
}
doSwapBuffers()
void ImageViewer::doSwapBuffers ()
{ glFlush(); }
dragCompare()
void ImageViewer::dragCompare (const QPoint & dp) protected
{
  if (m_compareSettings.m_dragCompareX)
    m_compareSettings.m_compareX += ((double)dp.x()) / width();
  else if (m_compareSettings.m_dragCompareY)
    m_compareSettings.m_compareY -= ((double)dp.y()) / height();
  m_compareSettings.m_compareX = tcrop(m_compareSettings.m_compareX, 0.0, 1.0);
  m_compareSettings.m_compareY = tcrop(m_compareSettings.m_compareY, 0.0, 1.0);
  update();
}
event()
bool ImageViewer::event (QEvent * e) override protected
{
  /*
  switch (e->type()) {
  case QEvent::TabletPress: {
  QTabletEvent *te = static_cast<QTabletEvent *>(e);
  qDebug() << "[event] TabletPress: pointerType(" << te->pointerType()
  << ") device(" << te->device() << ")";
  } break;
  case QEvent::TabletRelease:
  qDebug() << "[event] TabletRelease";
  break;
  case QEvent::TouchBegin:
  qDebug() << "[event] TouchBegin";
  break;
  case QEvent::TouchEnd:
  qDebug() << "[event] TouchEnd";
  break;
  case QEvent::TouchCancel:
  qDebug() << "[event] TouchCancel";
  break;
  case QEvent::MouseButtonPress:
  qDebug() << "[event] MouseButtonPress";
  break;
  case QEvent::MouseButtonDblClick:
  qDebug() << "[event] MouseButtonDblClick";
  break;
  case QEvent::MouseButtonRelease:
  qDebug() << "[event] MouseButtonRelease";
  break;
  case QEvent::Gesture:
  qDebug() << "[event] Gesture";
  break;
  default:
  break;
  }
  */
  if (e->type() == QEvent::Gesture && CommandManager::instance()
                                          ->getAction(MI_TouchGestureControl)
                                          ->isChecked()) {
    gestureEvent(static_cast<QGestureEvent *>(e));
    return true;
  }
  if ((e->type() == QEvent::TouchBegin || e->type() == QEvent::TouchEnd ||
       e->type() == QEvent::TouchCancel || e->type() == QEvent::TouchUpdate) &&
      CommandManager::instance()
          ->getAction(MI_TouchGestureControl)
          ->isChecked()) {
    touchEvent(static_cast<QTouchEvent *>(e), e->type());
    m_gestureActive = true;
    return true;
  }
  return GLWidgetForHighDpi::event(e);
}
fitView
void ImageViewer::fitView () slot
{
  if (!m_image) return;
  TRect imgBounds(getImageBounds(m_image));
  adaptView(imgBounds, imgBounds);
}
gestureEvent()
void ImageViewer::gestureEvent (QGestureEvent * e) protected
{
  // qDebug() << "[gestureEvent]";
  m_gestureActive = false;
  if (QGesture *swipe = e->gesture(Qt::SwipeGesture)) {
    m_gestureActive = true;
  } else if (QGesture *pan = e->gesture(Qt::PanGesture)) {
    m_gestureActive = true;
  }
  if (QGesture *pinch = e->gesture(Qt::PinchGesture)) {
    QPinchGesture *gesture = static_cast<QPinchGesture *>(pinch);
    QPinchGesture::ChangeFlags changeFlags = gesture->changeFlags();
    QPoint firstCenter                     = gesture->centerPoint().toPoint();
    if (m_touchDevice == QTouchDevice::TouchScreen)
      firstCenter = mapFromGlobal(firstCenter);
    if (gesture->state() == Qt::GestureStarted) {
      m_gestureActive = true;
    } else if (gesture->state() == Qt::GestureFinished) {
      m_gestureActive = false;
      m_zooming       = false;
      m_scaleFactor   = 0.0;
    } else {
      if (changeFlags & QPinchGesture::ScaleFactorChanged) {
        double scaleFactor = gesture->scaleFactor();
        // the scale factor makes for too sensitive scaling
        // divide the change in half
        if (scaleFactor > 1) {
          double decimalValue = scaleFactor - 1;
          decimalValue /= 1.5;
          scaleFactor = 1 + decimalValue;
        } else if (scaleFactor < 1) {
          double decimalValue = 1 - scaleFactor;
          decimalValue /= 1.5;
          scaleFactor = 1 - decimalValue;
        }
        if (!m_zooming) {
          double delta = scaleFactor - 1;
          m_scaleFactor += delta;
          if (m_scaleFactor > .2 || m_scaleFactor < -.2) {
            m_zooming = true;
          }
        }
        if (m_zooming) {
          const QPoint center(
              firstCenter.x() * getDevPixRatio() - width() / 2,
              -firstCenter.y() * getDevPixRatio() + height() / 2);
          zoomQt(center, scaleFactor);
          m_panning = false;
        }
        m_gestureActive = true;
      }
      if (changeFlags & QPinchGesture::CenterPointChanged) {
        QPointF centerDelta = (gesture->centerPoint() * getDevPixRatio()) -
                              (gesture->lastCenterPoint() * getDevPixRatio());
        if (centerDelta.manhattanLength() > 1) {
          // panQt(centerDelta.toPoint());
        }
        m_gestureActive = true;
      }
    }
  }
  e->accept();
}
getImage()
TImageP ImageViewer::getImage () inline
Return current image viewer.
{ return m_image; }
Referenced by ColorModelViewer::pick().
getImgToWidgetAffine() [1/2]
TAffine ImageViewer::getImgToWidgetAffine () const
{
  assert(m_image);
  return getImgToWidgetAffine(getImageBoundsD(m_image));
}
getImgToWidgetAffine() [2/2]
TAffine ImageViewer::getImgToWidgetAffine (const TRectD & imgBounds) const
Returns the affine transform from image reference to widget's pixel one.
{
  TPointD geomCenter((geom.x0 + geom.x1) * 0.5, (geom.y0 + geom.y1) * 0.5);
  QRect widGeom(rect());
  TPointD viewerCenter((widGeom.left() + widGeom.right() + 1) * 0.5,
                       (widGeom.top() + widGeom.bottom() + 1) * 0.5);
  return TAffine(TAffine(1.0, 0.0, 0.0, 0.0, -1.0, height()) *
                 TTranslation(viewerCenter) * m_viewAff *
                 TTranslation(-geomCenter));
}
References getImgToWidgetAffine(), and TRectT< T >::x0.
Referenced by FlipBook::adaptGeometryForFullPreview(), adaptView(), and getImgToWidgetAffine().
getViewAff()
TAffine ImageViewer::getViewAff () inline
Return current viewer matrix transformation.
{ return m_viewAff; }
Referenced by FlipBook::adaptWidGeometry(), and ColorModelViewer::pick().
hideEvent()
void ImageViewer::hideEvent (QHideEvent *) override protected
{
  TSceneHandle *sceneHandle = TApp::instance()->getCurrentScene();
  if (sceneHandle) sceneHandle->disconnect(this);
}
hideHistogram()
void ImageViewer::hideHistogram ()
If histogram popup exist and is open, it is set to default and is hidden.
{
  if (!m_isHistogramEnable) return;
  m_histogramPopup->setImage(TImageP());
  if (m_histogramPopup->isVisible()) {
    m_histogramPopup->hide();
    m_histogramPopup->setTitle(tr("Flipbook Histogram"));
  }
}
initializeGL()
void ImageViewer::initializeGL () override protected
{
  initializeOpenGLFunctions();
  // to be computed once through the software
  if (m_lutCalibrator && !m_lutCalibrator->isInitialized()) {
    m_lutCalibrator->initialize();
    connect(context(), SIGNAL(aboutToBeDestroyed()), this,
            SLOT(onContextAboutToBeDestroyed()));
  }
  // glClearColor(1.0,1.0,1.0,1);
  glClear(GL_COLOR_BUFFER_BIT);
  if (m_firstInitialized)
    m_firstInitialized = false;
  else {
    resizeGL(width(), height());
    update();
  }
}
invalidateCompHisto()
void ImageViewer::invalidateCompHisto ()
{
  if (!m_isHistogramEnable || !m_histogramPopup) return;
  m_histogramPopup->invalidateCompHisto();
}
isColorModel()
bool ImageViewer::isColorModel () inline
{ return m_isColorModel; }
isRemakingPreviewFx()
bool ImageViewer::isRemakingPreviewFx () inline
{ return m_isRemakingPreviewFx; }
keyPressEvent()
void ImageViewer::keyPressEvent (QKeyEvent * event) override protected
{
  if (FlipZoomer(this).exec(event)) return;
  ImageViewerShortcutReceiver(m_flipbook).exec(event);
}
mouseDoubleClickEvent()
void ImageViewer::mouseDoubleClickEvent (QMouseEvent * event) override protected
{
  if (!m_image) return;
  // qDebug() << "[mouseDoubleClickEvent]";
  if (m_gestureActive && !m_stylusUsed) {
    m_gestureActive = false;
    fitView();
    return;
  }
  if (m_visualSettings.m_defineLoadbox && m_flipbook) {
    m_flipbook->setLoadbox(TRect());
    update();
    event->ignore();
  }
}
mouseMoveEvent()
void ImageViewer::mouseMoveEvent (QMouseEvent * event) override protected
If middle button is pressed pan the image. Update current mouse position.
{
  if (!m_image) return;
  if (m_gestureActive && m_touchDevice == QTouchDevice::TouchScreen &&
      !m_stylusUsed) {
    return;
  }
  QPoint curQPos = event->pos() * getDevPixRatio();
  TPoint curPos = TPoint(curQPos.x(), curQPos.y());
  if (m_visualSettings.m_defineLoadbox && m_flipbook) {
    if (m_mouseButton == Qt::LeftButton)
      updateLoadbox(curPos);
    else if (m_mouseButton == Qt::MidButton)
      panQt(curQPos - m_pos);
    else
      updateCursor(curPos);
    update();
    event->ignore();
    m_pos = curQPos;
    return;
  }
  // setting the cursors
  if (!m_isColorModel) {
    // when the histogram window is opened, switch to the RGB picker tool
    if (m_isHistogramEnable && m_histogramPopup->isVisible())
      setToolCursor(this, ToolCursor::PickerRGB);
    else
      setCursor(Qt::ArrowCursor);
  }
  if (m_visualSettings.m_doCompare && m_mouseButton == Qt::NoButton) {
    if (fabs(curPos.x - width() * m_compareSettings.m_compareX) < 20)
      setToolCursor(this, ToolCursor::ScaleHCursor);
    else if (fabs((height() - curPos.y) -
                  height() * m_compareSettings.m_compareY) < 20)
      setToolCursor(this, ToolCursor::ScaleVCursor);
  }
  if (m_compareSettings.m_dragCompareX || m_compareSettings.m_dragCompareY)
    dragCompare(curQPos - m_pos);
  else if (m_mouseButton == Qt::MidButton)
    panQt(curQPos - m_pos);
  m_pos = curQPos;
  // pick the color if the histogram popup is opened
  if (m_isHistogramEnable && m_histogramPopup->isVisible() && !m_isColorModel) {
    // Rect Pick
    if (m_mouseButton == Qt::LeftButton &&
        (event->modifiers() & Qt::ControlModifier)) {
      if (!m_rectRGBPick && !m_visualSettings.m_defineLoadbox &&
          (abs(m_pos.x() - m_pressedMousePos.x) > 10 ||
           abs(m_pos.y() - m_pressedMousePos.y) > 10) &&
          !(m_compareSettings.m_dragCompareX ||
            m_compareSettings.m_dragCompareY) &&
          m_flipbook)
        m_rectRGBPick = true;
      if (m_rectRGBPick) {
        update();
        // do not pick vector image while dragging as a portion of the red
        // rubber band may affect the result
        TImageP img = getPickedImage(m_pos);
        if (img && img->raster()) rectPickColor();
      }
    }
    update();
    pickColor(event);
    return;
  }
  if (m_mouseButton == Qt::LeftButton && !m_isColorModel &&
      (event->modifiers() & Qt::AltModifier)) {
    if (!m_draggingZoomSelection && !m_visualSettings.m_defineLoadbox &&
        (abs(m_pos.x() - m_pressedMousePos.x) > 10 ||
         abs(m_pos.y() - m_pressedMousePos.y) > 10) &&
        !(m_compareSettings.m_dragCompareX ||
          m_compareSettings.m_dragCompareY) &&
        m_flipbook)
      m_draggingZoomSelection = true;
    if (m_draggingZoomSelection) update();
  } else
    m_draggingZoomSelection = false;
  if (m_isColorModel && m_mouseButton == Qt::LeftButton) {
    event->ignore();
  }
}
References ImagePainter::CompareSettings::m_compareX, ImagePainter::CompareSettings::m_compareY, ImagePainter::VisualSettings::m_defineLoadbox, ImagePainter::VisualSettings::m_doCompare, ImagePainter::CompareSettings::m_dragCompareX, ImagePainter::CompareSettings::m_dragCompareY, panQt(), and TImage::raster().
mousePressEvent()
void ImageViewer::mousePressEvent (QMouseEvent * event) override protected
{
  if (!m_image) return;
  // qDebug() << "[mousePressEvent]";
  if (m_gestureActive && m_touchDevice == QTouchDevice::TouchScreen &&
      !m_stylusUsed) {
    return;
  }
  m_pos                   = event->pos() * getDevPixRatio();
  m_pressedMousePos       = TPoint(m_pos.x(), m_pos.y());
  m_mouseButton           = event->button();
  m_draggingZoomSelection = false;
  QPointF winPosMousePos = event->windowPos() * getDevPixRatio() - m_pos;
  m_winPosMousePosOffset = TPointD(winPosMousePos.x(), winPosMousePos.y());
  if (m_mouseButton != Qt::LeftButton) {
    event->ignore();
    return;
  }
  if (m_visualSettings.m_defineLoadbox && m_flipbook)
    m_dragType = getDragType(
        m_pressedMousePos,
        convert(getImgToWidgetAffine() * convert(m_flipbook->getLoadbox())));
  else if (m_visualSettings.m_doCompare) {
    if (fabs(m_pos.x() - width() * m_compareSettings.m_compareX) < 20) {
      m_compareSettings.m_dragCompareX = true;
      m_compareSettings.m_dragCompareY = false;
      m_compareSettings.m_compareY     = ImagePainter::DefaultCompareValue;
      update();
    } else if (fabs((height() - m_pos.y()) -
                    height() * m_compareSettings.m_compareY) < 20) {
      m_compareSettings.m_dragCompareY = true;
      m_compareSettings.m_dragCompareX = false;
      m_compareSettings.m_compareX     = ImagePainter::DefaultCompareValue;
      update();
    } else
      m_compareSettings.m_dragCompareX = m_compareSettings.m_dragCompareY =
          false;
  }
  // pick color and throw it to the style editor
  if (m_isHistogramEnable && m_histogramPopup->isVisible() && !m_isColorModel &&
      !(event->modifiers() & Qt::ControlModifier))  // if ctrl button is
                                                    // pressed, which means
                                                    // rectangular pick
  {
    update();
    pickColor(event, true);
  }
  event->ignore();
}
mouseReleaseEvent()
void ImageViewer::mouseReleaseEvent (QMouseEvent * event) override protected
Reset current mouse position and current mouse button event.
{
  if (!m_image) return;
  if (m_draggingZoomSelection && !m_visualSettings.m_defineLoadbox) {
    m_draggingZoomSelection = false;
    int left, right, top, bottom;
    if (m_pos.x() < m_pressedMousePos.x)
      left = m_pos.x(), right = m_pressedMousePos.x;
    else
      right = m_pos.x(), left = m_pressedMousePos.x;
    if (m_pos.y() < m_pressedMousePos.y)
      top = m_pos.y(), bottom = m_pressedMousePos.y;
    else
      bottom = m_pos.y(), top = m_pressedMousePos.y;
    adaptView(QRect(QPoint(left, top), QPoint(right, bottom)));
  }
  if (m_rectRGBPick) {
    // pick color in the rectangular region
    rectPickColor(true);
    // release the flag
    m_rectRGBPick = false;
    update();
  }
  m_pos                            = QPoint(0, 0);
  m_mouseButton                    = Qt::NoButton;
  m_compareSettings.m_dragCompareX = m_compareSettings.m_dragCompareY = false;
  m_gestureActive = false;
  m_zooming       = false;
  m_panning       = false;
  m_stylusUsed    = false;
  event->ignore();
}
References adaptView(), ImagePainter::VisualSettings::m_defineLoadbox, ImagePainter::CompareSettings::m_dragCompareX, and ImagePainter::CompareSettings::m_dragCompareY.
onContextAboutToBeDestroyed
void ImageViewer::onContextAboutToBeDestroyed () slot
{
  if (!m_lutCalibrator) return;
  makeCurrent();
  m_lutCalibrator->cleanup();
  doneCurrent();
  disconnect(context(), SIGNAL(aboutToBeDestroyed()), this,
             SLOT(onContextAboutToBeDestroyed()));
}
onPreferenceChanged
void ImageViewer::onPreferenceChanged (const QString & prefName) slot
{
  if (prefName == "ColorCalibration") {
    if (Preferences::instance()->isColorCalibrationEnabled()) {
      // if the window is so shriked that the gl widget is empty,
      // showEvent can be called before creating the context.
      if (!context()) return;
      makeCurrent();
      if (!m_lutCalibrator)
        m_lutCalibrator = new LutCalibrator();
      else
        m_lutCalibrator->cleanup();
      m_lutCalibrator->initialize();
      connect(context(), SIGNAL(aboutToBeDestroyed()), this,
              SLOT(onContextAboutToBeDestroyed()));
      if (m_lutCalibrator->isValid() && !m_fbo) {
        if (Preferences::instance()->is30bitDisplayEnabled()) {
          QOpenGLFramebufferObjectFormat format;
          format.setInternalTextureFormat(TGL_TexFmt10);
          m_fbo = new QOpenGLFramebufferObject(width(), height(), format);
        } else  // normally, initialize with GL_RGBA8 format
          m_fbo = new QOpenGLFramebufferObject(width(), height());
      }
      doneCurrent();
    }
    update();
  }
}
paintGL()
void ImageViewer::paintGL () override protected
{
  initializeOpenGLFunctions();
  if (m_lutCalibrator && m_lutCalibrator->isValid()) m_fbo->bind();
  TDimension viewerSize(width(), height());
  TAffine aff = m_viewAff;
  // if (!m_visualSettings.m_defineLoadbox && m_flipbook &&
  // m_flipbook->getLoadbox()!=TRect())
  //  offs =
  //  convert(m_flipbook->getLoadbox().getP00())-TPointD(m_flipbook->getImageSize().lx/2.0,
  //  m_flipbook->getImageSize().ly/2.0);
  TDimension imageSize;
  TRect loadbox;
  if (m_flipbook) {
    QString title =
        (!m_image)
            ? m_flipbook->getTitle() + tr("  ::  Zoom : ") +
                  QString::number(tround(sqrt(m_viewAff.det()) * 100)) + " %"
            : m_flipbook->getLevelZoomTitle() + tr("  ::  Zoom : ") +
                  QString::number(tround(sqrt(m_viewAff.det()) * 100)) + " %";
    m_flipbook->parentWidget()->setWindowTitle(title);
    imageSize = m_flipbook->getImageSize();
    if (m_visualSettings.m_useLoadbox && m_flipbook->getLoadbox() != TRect())
      loadbox = m_flipbook->getLoadbox();
  }
  m_visualSettings.m_sceneProperties =
      TApp::instance()->getCurrentScene()->getScene()->getProperties();
  // enable checks only in the color model
  m_visualSettings.m_useChecks = m_isColorModel;
  ImagePainter::paintImage(m_image, imageSize, viewerSize, aff,
                           m_visualSettings, m_compareSettings, loadbox);
  // when fx parameter is modified with showing the fx preview,
  // a flipbook shows a red border line before the rendered result is shown.
  if (m_isRemakingPreviewFx) {
    glPushMatrix();
    glLoadIdentity();
    glColor3d(1.0, 0.0, 0.0);
    glBegin(GL_LINE_LOOP);
    glVertex2d(5, 5);
    glVertex2d(5, height() - 5);
    glVertex2d(width() - 5, height() - 5);
    glVertex2d(width() - 5, 5);
    glEnd();
    glBegin(GL_LINE_LOOP);
    glVertex2d(10, 10);
    glVertex2d(10, height() - 10);
    glVertex2d(width() - 10, height() - 10);
    glVertex2d(width() - 10, 10);
    glEnd();
    glPopMatrix();
  }
  if (!m_image) {
    if (m_lutCalibrator && m_lutCalibrator->isValid())
      m_lutCalibrator->onEndDraw(m_fbo);
    if (m_timer && m_timer->isValid()) {
      qint64 currentInstant = m_timer->nsecsElapsed();
      while (currentInstant < m_targetInstant) {
        currentInstant = m_timer->nsecsElapsed();
      }
    }
    return;
  }
  if (safeAreaToggle.getStatus() && !m_isColorModel) {
    TRasterImageP rimg = (TRasterImageP)m_image;
    TVectorImageP vimg = (TVectorImageP)m_image;
    TToonzImageP timg  = (TToonzImageP)m_image;
    TRect bbox;
    TPointD centerD;
    TRect bounds;
    if (rimg) {
      centerD = rimg->getRaster()->getCenterD();
      bounds  = rimg->getRaster()->getBounds();
    } else if (timg) {
      centerD = timg->getRaster()->getCenterD();
      bounds  = timg->getRaster()->getBounds();
    }
    if (!vimg) {
      TAffine aff = TTranslation(viewerSize.lx * 0.5, viewerSize.ly * 0.5) *
                    m_viewAff * TTranslation(-centerD);
      TRectD bbox = aff * TRectD(0, 0, bounds.getLx() - 1, bounds.getLy() - 1);
      drawSafeArea(bbox);
    }
  }
  TPoint fromPos, toPos;
  if (m_visualSettings.m_defineLoadbox && m_flipbook) {
    TRect loadbox =
        convert(getImgToWidgetAffine() * convert(m_flipbook->getLoadbox()));
    if (loadbox != TRect()) {
      TPoint p00 = loadbox.getP00();
      TPoint p11 = loadbox.getP11();
      fromPos =
          TPoint(p00.x - width() * 0.5,
                 height() * 0.5 - p00.y);  // m_flipbook->getLoadbox().getP00();
      toPos =
          TPoint(p11.x - width() * 0.5,
                 height() * 0.5 - p11.y);  // m_flipbook->getLoadbox().getP11();
    }
  } else if (m_draggingZoomSelection || m_rectRGBPick) {
    fromPos = TPoint(m_pressedMousePos.x - width() * 0.5,
                     height() * 0.5 - m_pressedMousePos.y);
    toPos   = TPoint(m_pos.x() - width() * 0.5, height() * 0.5 - m_pos.y());
  }
  if (fromPos != TPoint() || toPos != TPoint()) {
    if (m_rectRGBPick) {
      tglColor(TPixel32::Red);
      // TODO: glLineStipple is deprecated in the latest OpenGL. Need to be
      // replaced. (shun_iwasawa 2015/12/25)
      glLineStipple(1, 0x3F33);
      glEnable(GL_LINE_STIPPLE);
      glBegin(GL_LINE_STRIP);
      // do not draw the rect around the mouse cursor
      int margin = (fromPos.y < toPos.y) ? -3 : 3;
      glVertex2i(toPos.x, toPos.y + margin);
      glVertex2i(toPos.x, fromPos.y);
      glVertex2i(fromPos.x, fromPos.y);
      glVertex2i(fromPos.x, toPos.y);
      margin = (fromPos.x < toPos.x) ? -3 : 3;
      glVertex2i(toPos.x + margin, toPos.y);
      glEnd();
      glDisable(GL_LINE_STIPPLE);
    } else {
      tglColor(m_draggingZoomSelection ? TPixel32::Red : TPixel32::Blue);
      glBegin(GL_LINE_STRIP);
      glVertex2i(fromPos.x, fromPos.y);
      glVertex2i(fromPos.x, toPos.y);
      glVertex2i(toPos.x, toPos.y);
      glVertex2i(toPos.x, fromPos.y);
      glVertex2i(fromPos.x, fromPos.y);
      glEnd();
    }
  }
  if (m_lutCalibrator && m_lutCalibrator->isValid())
    m_lutCalibrator->onEndDraw(m_fbo);
  // wait to achieve precise fps
  if (m_timer && m_timer->isValid()) {
    qint64 currentInstant = m_timer->nsecsElapsed();
    while (currentInstant < m_targetInstant) {
      currentInstant = m_timer->nsecsElapsed();
    }
  }
}
panQt()
void ImageViewer::panQt (const QPoint & delta) protected
Add to current transformation matrix a delta translation.
{
  if (delta == QPoint()) return;
  // stop panning when the image is at the edge of window
  QPoint delta_(delta.x(), delta.y());
  TToonzImageP timg  = (TToonzImageP)m_image;
  TRasterImageP rimg = (TRasterImageP)m_image;
  if (timg || rimg) {
    bool isXPlus = delta.x() > 0;
    bool isYPlus = delta.y() > 0;
    TDimension imgSize((timg) ? timg->getSize() : rimg->getRaster()->getSize());
    int subSampling = (timg) ? timg->getSubsampling() : rimg->getSubsampling();
    TPointD cornerPos = TPointD(imgSize.lx * ((isXPlus) ? -1 : 1),
                                imgSize.ly * ((isYPlus) ? 1 : -1)) *
                        (0.5 / (double)subSampling);
    cornerPos = m_viewAff * cornerPos;
    if ((cornerPos.x > 0) == isXPlus) delta_.setX(0);
    if ((cornerPos.y < 0) == isYPlus) delta_.setY(0);
  }
  setViewAff(TTranslation(delta_.x(), -delta_.y()) * m_viewAff);
  update();
}
Referenced by mouseMoveEvent().
resetView
void ImageViewer::resetView () slot
{ zoomQt(false, true); }
resetZoom()
void ImageViewer::resetZoom ()
{
  double oldZoomScale = sqrt(m_viewAff.det());
  setViewAff(TScale(1.0 / oldZoomScale) * m_viewAff);
  update();
}
resizeGL()
void ImageViewer::resizeGL (int width, int height) override protected
{
  w *= getDevPixRatio();
  h *= getDevPixRatio();
  glViewport(0, 0, w, h);
  glMatrixMode(GL_PROJECTION);
  glLoadIdentity();
  double nearPlane   = 100;
  double farPlane    = 2500;
  double centerPlane = 1100;
  glOrtho(0, w, 0, h, -4000, 4000);
  glMatrixMode(GL_MODELVIEW);
  glLoadIdentity();
  glTranslatef(0.375, 0.375, 0.0);
  glTranslated(w * 0.5, h * 0.5, 0);
  // remake fbo with new size
  if (m_lutCalibrator && m_lutCalibrator->isValid()) {
    if (m_fbo) delete m_fbo;
    if (Preferences::instance()->is30bitDisplayEnabled()) {
      QOpenGLFramebufferObjectFormat format;
      format.setInternalTextureFormat(TGL_TexFmt10);
      m_fbo = new QOpenGLFramebufferObject(w, h, format);
    } else  // normally, initialize with GL_RGBA8 format
      m_fbo = new QOpenGLFramebufferObject(w, h);
  }
}
setHistogramEnable()
void ImageViewer::setHistogramEnable (bool enable)
{
  m_isHistogramEnable = enable;
  if (m_isHistogramEnable && !m_histogramPopup)
    m_histogramPopup = new HistogramPopup(tr("Flipbook Histogram"));
}
setHistogramTitle()
void ImageViewer::setHistogramTitle (QString levelName)
If histogram popup exist and is open set its title to "Histogram: level name" if level Name is not empty.
{
  if (m_isHistogramEnable && m_histogramPopup->isVisible()) {
    QString histogramTitle = QString("Histogram  ::  ") + levelName;
    m_histogramPopup->setTitle(histogramTitle);
  }
}
Referenced by FlipBook::setLevel().
setImage()
void ImageViewer::setImage (TImageP image)
Set current image to image and update. If Histogram is visible set its image.
{
  m_image = image;
  if (m_image && m_firstImage) {
    m_firstImage = false;
    fitView();
    // when the viewer size is large enough, limit the zoom ratio to 100% so
    // that the image is shown in actual pixel size without jaggies due to
    // resampling.
    if (fabs(m_viewAff.det()) > 1.0) resetView();
  }
  if (m_isHistogramEnable && m_histogramPopup->isVisible())
    m_histogramPopup->setImage(image);
  // make sure to redraw the frame here.
  // repaint() does NOT immediately redraw the frame for QOpenGLWidget
  update();
  if (!isColorModel()) qApp->processEvents();
}
Referenced by ColorModelViewer::loadCurrentFrame(), FlipBook::onDrawFrame(), and ColorModelViewer::resetImageViewer().
setIsColorModel()
void ImageViewer::setIsColorModel (bool isColorModel) inline
{ m_isColorModel = isColorModel; }
setIsRemakingPreviewFx()
void ImageViewer::setIsRemakingPreviewFx (bool on) inline
{
    m_isRemakingPreviewFx = on;
    update();
  }
setTimerAndTargetInstant()
void ImageViewer::setTimerAndTargetInstant (QElapsedTimer * timer, qint64 target) inline
{
    m_timer         = timer;
    m_targetInstant = target;
  }
setViewAff()
void ImageViewer::setViewAff (TAffine viewAff)
{
  m_viewAff = viewAff;
  update();
  if (m_flipbook && m_flipbook->getPreviewedFx())
    // Update the observable fx region
    m_flipbook->schedulePreviewedFxUpdate();
}
setVisual()
void ImageViewer::setVisual (const ImagePainter::VisualSettings & settings)
{
  if (m_isHistogramEnable && m_histogramPopup &&
      settings.m_doCompare != m_visualSettings.m_doCompare) {
    m_histogramPopup->setShowCompare(settings.m_doCompare);
  }
  m_visualSettings = settings;
  m_visualSettings.m_sceneProperties =
      TApp::instance()->getCurrentScene()->getScene()->getProperties();
  m_visualSettings.m_drawExternalBG = true;
}
showEvent()
void ImageViewer::showEvent (QShowEvent *) override protected
{
  TSceneHandle *sceneHandle = TApp::instance()->getCurrentScene();
  bool ret = connect(sceneHandle, SIGNAL(preferenceChanged(const QString &)),
                     this, SLOT(onPreferenceChanged(const QString &)));
  onPreferenceChanged("ColorCalibration");
  assert(ret);
}
showHistogram
void ImageViewer::showHistogram () slot
{
  if (!m_isHistogramEnable) return;
  if (m_histogramPopup->isVisible())
    m_histogramPopup->raise();
  else {
    m_histogramPopup->setImage(getImage());
    m_histogramPopup->show();
  }
}
swapCompared
void ImageViewer::swapCompared () slot
{
  m_compareSettings.m_swapCompared = !m_compareSettings.m_swapCompared;
  update();
}
tabletEvent()
void ImageViewer::tabletEvent (QTabletEvent * e) override protected
{
  // qDebug() << "[tabletEvent]";
  if (e->type() == QTabletEvent::TabletPress) {
    m_stylusUsed = e->pointerType() ? true : false;
  } else if (e->type() == QTabletEvent::TabletRelease) {
    m_stylusUsed = false;
  }
  e->accept();
}
touchEvent()
void ImageViewer::touchEvent (QTouchEvent * e, int type) protected
{
  // qDebug() << "[touchEvent]";
  if (type == QEvent::TouchBegin) {
    m_touchActive   = true;
    m_firstPanPoint = e->touchPoints().at(0).pos();
    // obtain device type
    m_touchDevice = e->device()->type();
  } else if (m_touchActive) {
    // touchpads must have 2 finger panning for tools and navigation to be
    // functional on other devices, 1 finger panning is preferred
    if ((e->touchPoints().count() == 2 &&
         m_touchDevice == QTouchDevice::TouchPad) ||
        (e->touchPoints().count() == 1 &&
         m_touchDevice == QTouchDevice::TouchScreen)) {
      QTouchEvent::TouchPoint panPoint = e->touchPoints().at(0);
      if (!m_panning) {
        QPointF deltaPoint = panPoint.pos() - m_firstPanPoint;
        // minimize accidental and jerky zooming/rotating during 2 finger
        // panning
        if ((deltaPoint.manhattanLength() > 100) && !m_zooming) {
          m_panning = true;
        }
      }
      if (m_panning) {
        QPoint curPos      = panPoint.pos().toPoint() * getDevPixRatio();
        QPoint lastPos     = panPoint.lastPos().toPoint() * getDevPixRatio();
        QPoint centerDelta = curPos - lastPos;
        panQt(centerDelta);
      }
    }
  }
  if (type == QEvent::TouchEnd || type == QEvent::TouchCancel) {
    m_touchActive = false;
    m_panning     = false;
  }
  e->accept();
}
updateImageViewer
void ImageViewer::updateImageViewer () slot
Update image viewer, reset current matrix transformation, current position and update view.
{
  setViewAff(TAffine());
  m_pos = QPoint(0, 0);
  update();
}
wheelEvent()
void ImageViewer::wheelEvent (QWheelEvent * event) override protected
Apply zoom.
{
  if (!m_image) return;
  if (event->orientation() == Qt::Horizontal) return;
  int delta = 0;
  switch (event->source()) {
  case Qt::MouseEventNotSynthesized: {
    if (event->modifiers() & Qt::AltModifier)
      delta = event->angleDelta().x();
    else
      delta = event->angleDelta().y();
    break;
  }
  case Qt::MouseEventSynthesizedBySystem: {
    QPoint numPixels  = event->pixelDelta();
    QPoint numDegrees = event->angleDelta() / 8;
    if (!numPixels.isNull()) {
      delta = event->pixelDelta().y();
    } else if (!numDegrees.isNull()) {
      QPoint numSteps = numDegrees / 15;
      delta           = numSteps.y();
    }
    break;
  }
  default:  // Qt::MouseEventSynthesizedByQt,
            // Qt::MouseEventSynthesizedByApplication
  {
    std::cout << "not supported event: Qt::MouseEventSynthesizedByQt, "
                 "Qt::MouseEventSynthesizedByApplication"
              << std::endl;
    break;
  }
  }  // end switch
  if (abs(delta) > 0) {
    if ((m_gestureActive == true &&
         m_touchDevice == QTouchDevice::TouchScreen) ||
        m_gestureActive == false) {
      int delta = event->delta() > 0 ? 120 : -120;
      QPoint center(event->pos().x() * getDevPixRatio() - width() / 2,
                    -event->pos().y() * getDevPixRatio() + height() / 2);
      zoomQt(center, exp(0.001 * delta));
    }
  }
  event->accept();
}
zoomQt() [1/2]
void ImageViewer::zoomQt (bool forward, bool reset)
{
  double scale2 = m_viewAff.det();
  if (reset)
    setViewAff(TAffine());
  else if (((scale2 < 100000 || !forward) &&
            (scale2 > 0.001 * 0.05 || forward))) {
    double oldZoomScale = sqrt(scale2);
    double zoomScale =
        reset ? 1 : ImageUtils::getQuantizedZoomFactor(oldZoomScale, forward);
    setViewAff(TScale(zoomScale / oldZoomScale) * m_viewAff);
  }
  update();
}
zoomQt() [2/2]
void ImageViewer::zoomQt (const QPoint & center, double factor) protected
Add to current transformation matrix a center translation matched with a scale of factor factor. Apply a zoom of factor factor with center center.
{
  if (factor == 1.0) return;
  TPointD delta(center.x(), center.y());
  double scale2 = fabs(m_viewAff.det());
  if ((scale2 < 100000 || factor < 1) && (scale2 > 0.001 * 0.05 || factor > 1))
    setViewAff(TTranslation(delta) * TScale(factor) * TTranslation(-delta) *
               m_viewAff);
  update();
}
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/toonz/imageviewer.h
E:/opentoonz/toonz/sources/toonz/flipbook.cpp
E:/opentoonz/toonz/sources/toonz/imageviewer.cpp