opentoonz: SelectionTool Class Reference
SelectionTool Class Reference abstract
Public Member Functions
SelectionTool (int targetType)
ToolType getToolType () const override
TPointD getCenter (int index=0) const
void setCenter (const TPointD &center, int index=0)
int getBBoxsCount () const
DragSelectionTool::FourPoints getBBox (int index=0) const
virtual void setBBox (const DragSelectionTool::FourPoints &points, int index=0)
FreeDeformer * getFreeDeformer (int index=0) const
virtual void setNewFreeDeformer ()=0
void clearDeformers ()
int getSelectedPoint () const
virtual bool isConstantThickness () const
virtual bool isLevelType () const
virtual bool isSelectedFramesType () const
virtual bool isSameStyleType () const
virtual bool isModifiableSelectionType () const
virtual bool isFloating () const
virtual QSet< int > getSelectedStyles () const
void leftButtonDown (const TPointD &pos, const TMouseEvent &) override
void leftButtonDrag (const TPointD &pos, const TMouseEvent &) override=0
void leftButtonUp (const TPointD &pos, const TMouseEvent &) override=0
void mouseMove (const TPointD &pos, const TMouseEvent &e) override
void leftButtonDoubleClick (const TPointD &, const TMouseEvent &e) override=0
bool keyDown (QKeyEvent *) override
int getCursorId () const override
Returns the type of cursor used by the tool.
void draw () override=0
Draws the tool on the viewer.
TSelection * getSelection () override=0
Returns a pointer to the tool selection.
virtual bool isSelectionEmpty ()=0
virtual void computeBBox ()=0
void onActivate () override
Callback invoked whenever the tool activates.
void onDeactivate () override
Callback for tool deactivation, includes tool switch.
void onImageChanged () override=0
Notifies changes in the image in use.
void onSelectionChanged () override
TPropertyGroup * getProperties (int targetType) override
bool onPropertyChanged (std::string propertyName) override
bool isEventAcceptable (QEvent *e) override
virtual bool isSelectionEditable ()
Public Member Functions inherited from TTool
TTool (std::string toolName)
every tool (invoking updateTranslation() for each).
virtual ToolType getToolType () const =0
ToolTargetType getTargetType () const
std::string getName () const
virtual ToolOptionsBox * createOptionsBox ()
void setViewer (Viewer *viewer)
Viewer * getViewer () const
double getPixelSize () const
void invalidate (const TRectD &rect=TRectD())
int pick (const TPointD &p)
bool isPicking () const
virtual void updateTranslation ()
virtual bool preLeftButtonDown ()
virtual void mouseMove (const TPointD &, const TMouseEvent &)
virtual void leftButtonDown (const TPointD &, const TMouseEvent &)
virtual void leftButtonDrag (const TPointD &, const TMouseEvent &)
virtual void leftButtonUp (const TPointD &, const TMouseEvent &)
virtual void leftButtonDoubleClick (const TPointD &, const TMouseEvent &)
virtual void rightButtonDown (const TPointD &, const TMouseEvent &)
virtual bool keyDown (QKeyEvent *)
virtual void onInputText (std::wstring, std::wstring, int, int)
virtual void onSetViewer ()
virtual void onActivate ()
Callback invoked whenever the tool activates.
virtual void onDeactivate ()
Callback for tool deactivation, includes tool switch.
virtual void onImageChanged ()
Notifies changes in the image in use.
virtual void onEnter ()
Callback for the mouse entering the viewer area.
virtual void onLeave ()
Callback for the mouse leaving the viewer area.
virtual void onFrameSwitched ()
virtual void reset ()
virtual void draw ()
Draws the tool on the viewer.
bool isActive () const
Used to know if a tool is active, (used in TextTool only).
void setActive (bool active)
virtual TPropertyGroup * getProperties (int)
virtual bool onPropertyChanged (std::string propertyName)
virtual TSelection * getSelection ()
Returns a pointer to the tool selection.
virtual int getCursorId () const
Returns the type of cursor used by the tool.
virtual bool isEventAcceptable (QEvent *e)
TXsheet * getXsheet () const
Returns a pointer to the actual Xsheet.
int getFrame ()
Returns the actual frame in use.
int getColumnIndex ()
Returns the actual column index.
TStageObjectId getObjectId () const
Returns a pointer to the actual stage object.
void notifyImageChanged ()
void notifyImageChanged (const TFrameId &fid)
images on the level view.
TFrameId getCurrentFid () const
Returns the number of the actual editing frame.
const TAffine & getMatrix () const
void setMatrix (const TAffine &matrix)
TAffine getCurrentColumnMatrix (int frame=-1) const
TAffine getCurrentColumnParentMatrix () const
TAffine getCurrentObjectParentMatrix () const
TAffine getCurrentObjectParentMatrix2 () const
TAffine getColumnMatrix (int index, int frame=-1) const
virtual void updateMatrix ()
virtual void addContextMenuItems (QMenu *menu)
void enable (bool on)
bool isEnabled () const
QString updateEnabled ()
virtual QString updateEnabled (int rowIndex, int columnIndex)
bool isColumnLocked (int columnIndex) const
void resetInputMethod ()
Resets Input Context (IME)
virtual bool isPencilModeActive ()
virtual bool isDragging () const
void setSelectedFrames (const std::set< TFrameId > &selectedFrames)
void tweenSelectedGuideStrokes ()
void tweenGuideStrokeToSelected ()
void flipGuideStrokeDirection (int mode)
Public Member Functions inherited from TSelection::View
virtual void onSelectionChanged ()=0
virtual void enableCommands ()
Public Attributes
DragSelectionTool::DeformValues m_deformValues
Protected Types
enum {
Outside , Inside , DEFORM , ROTATION ,
MOVE_CENTER , SCALE , SCALE_X , SCALE_Y ,
GLOBAL_THICKNESS , ADD_SELECTION
}
enum {
P00 = 0 , P10 = 1 , P11 = 2 , P01 = 3 ,
PM0 = 4 , P1M = 5 , PM1 = 6 , P0M = 7 ,
NONE
}
Protected Member Functions
virtual void updateAction (TPointD pos, const TMouseEvent &e)
virtual void modifySelectionOnClick (TImageP image, const TPointD &pos, const TMouseEvent &e)=0
virtual void doOnActivate ()=0
virtual void doOnDeactivate ()=0
void startFreehand (const TPointD &pos)
void freehandDrag (const TPointD &pos)
Viene aggiunto pos a m_track e disegnato un altro pezzetto del lazzo.
void closeFreehand (const TPointD &pos)
void addPointPolyline (const TPointD &pos)
Viene aggiunto un punto al vettore m_polyline.
void closePolyline (const TPointD &pos)
void updateTranslation () override
void drawPolylineSelection ()
void drawRectSelection (const TImage *image)
void drawFreehandSelection ()
void drawCommandHandle (const TImage *image)
Protected Member Functions inherited from TTool
void bind (int targetType)
virtual void onSelectedFramesChanged ()
virtual QString disableString ()
Returns a custom reason to disable the tool.
Protected Attributes
bool m_firstTime
DragSelectionTool::DragTool * m_dragTool
StrokeGenerator m_track
std::vector< TPointD > m_polyline
TPointD m_mousePosition
TStroke * m_stroke
TPointD m_curPos
TPointD m_firstPos
bool m_selecting
bool m_justSelected
bool m_shiftPressed
enum SelectionTool:: { ... } m_what
enum SelectionTool:: { ... } m_selectedPoint
int m_cursorId
bool m_leftButtonMousePressed
DragSelectionTool::FourPoints m_selectingRect
std::vector< DragSelectionTool::FourPoints > m_bboxs
std::vector< TPointD > m_centers
std::vector< FreeDeformer * > m_freeDeformers
TEnumProperty m_strokeSelectionType
TPropertyGroup m_prop
Protected Attributes inherited from TTool
std::string m_name
The tool's name.
Viewer * m_viewer
Tool's current viewer.
TAffine m_matrix
World-to-window reference change affine.
int m_targetType
The tool's image type target.
bool m_enabled
Whether the tool allows user interaction.
bool m_active
bool m_picking
Additional Inherited Members
Public Types inherited from TTool
enum ToolType {
GenericTool = 1 , ColumnTool = 2 , LevelReadTool = 4 , LevelWriteTool ,
LevelTool = LevelReadTool | LevelWriteTool
}
Tool editing type.
enum ToolTargetType {
NoTarget = 0x0 , VectorImage = 0x1 , ToonzImage = 0x2 , RasterImage = 0x4 ,
MeshImage = 0x8 , Splines = 0x10 , LevelColumns = 0x20 , MeshColumns = 0x40 ,
EmptyTarget = 0x80 , CommonImages = VectorImage | ToonzImage | RasterImage , AllImages = CommonImages | MeshImage , Vectors = VectorImage | Splines ,
CommonLevels = CommonImages | LevelColumns , MeshLevels = MeshImage | MeshColumns , AllTargets = 0xffffffff
}
Object types the tool can operate on.
typedef TApplication Application
Static Public Member Functions inherited from TTool
static TTool * getTool (std::string toolName, ToolTargetType targetType)
static TApplication * getApplication ()
static void setApplication (TApplication *application)
static TXshCell getImageCell ()
Returns the level-frame pair to be edited by the tool.
static TImage * getImage (bool toBeModified, int subsampling=0)
Returns the image to be edited by the tool.
static TImage * touchImage ()
static void updateToolsPropertiesTranslation ()
static const std::set< TFrameId > & getSelectedFrames ()
Static Public Attributes inherited from TTool
static std::vector< CellOps > m_cellsData
static bool m_isLevelCreated = false
static bool m_isFrameCreated = false
static std::vector< TFrameId > m_oldFids
static std::vector< TFrameId > m_newFids
static bool m_isLevelRenumbererd = false
Static Protected Attributes inherited from TTool
static TApplication * m_application = 0
static std::set< TFrameId > m_selectedFrames = std::set<TFrameId>()
Detailed Description
Member Enumeration Documentation
anonymous enum
anonymous enum protected
       {
    Outside,
    Inside,
    DEFORM,
    ROTATION,
    MOVE_CENTER,
    SCALE,
    SCALE_X,
    SCALE_Y,
    GLOBAL_THICKNESS,
    ADD_SELECTION
  } m_what;  // RV
anonymous enum
anonymous enum protected
       {
    P00 = 0,
    P10 = 1,
    P11 = 2,
    P01 = 3,
    PM0 = 4,
    P1M = 5,
    PM1 = 6,
    P0M = 7,
    NONE
  } m_selectedPoint;  // RV
Constructor & Destructor Documentation
SelectionTool()
SelectionTool::SelectionTool (int targetType)
    : TTool("T_Selection")
    , m_firstTime(true)
    , m_dragTool(0)
    , m_what(Outside)
    , m_leftButtonMousePressed(false)
    , m_shiftPressed(false)
    , m_selecting(false)
    , m_mousePosition(TPointD())
    , m_stroke(0)
    , m_justSelected(false)
    , m_strokeSelectionType("Type:")
    , m_deformValues()
    , m_cursorId(ToolCursor::CURSOR_ARROW) {
  bind(targetType);
  m_prop.bind(m_strokeSelectionType);
  m_strokeSelectionType.addValue(RECT_SELECTION);
  m_strokeSelectionType.addValue(FREEHAND_SELECTION);
  m_strokeSelectionType.addValue(POLYLINE_SELECTION);
  m_strokeSelectionType.setId("Type");
}
~SelectionTool()
SelectionTool::~SelectionTool () override
{
  delete m_dragTool;
  if (m_stroke) {
    delete m_stroke;
    m_stroke = 0;
  }
  if (!m_freeDeformers.empty()) clearPointerContainer(m_freeDeformers);
}
Member Function Documentation
addPointPolyline()
void SelectionTool::addPointPolyline (const TPointD & pos) protected
Viene aggiunto un punto al vettore m_polyline.
{
  m_firstPos      = pos;
  m_mousePosition = pos;
  m_polyline.push_back(pos);
}
clearDeformers()
void SelectionTool::clearDeformers ()
{ clearPointerContainer(m_freeDeformers); }
closeFreehand()
void SelectionTool::closeFreehand (const TPointD & pos) protected
Viene chiuso il lazzo (si aggiunge l'ultimo punto ad m_track) e viene creato lo stroke rappresentante il lazzo.
{
  if (m_track.isEmpty()) return;
  double pixelSize = getPixelSize();
  m_track.add(TThickPoint(m_firstPos, 0), pixelSize * pixelSize);
  m_track.filterPoints();
  double error = (30.0 / 11) * pixelSize;
  m_stroke     = m_track.makeStroke(error);
  m_stroke->setStyle(1);
}
References StrokeGenerator::add(), StrokeGenerator::filterPoints(), StrokeGenerator::isEmpty(), StrokeGenerator::makeStroke(), and TStroke::setStyle().
closePolyline()
void SelectionTool::closePolyline (const TPointD & pos) protected
Agginge l'ultimo pos a m_polyline e chiude la spezzata (aggiunge m_polyline.front() alla fine del vettore).
{
  if (m_polyline.size() <= 1) return;
  if (m_polyline.back() != pos) m_polyline.push_back(pos);
  if (m_polyline.back() != m_polyline.front())
    m_polyline.push_back(m_polyline.front());
  std::vector<TThickPoint> strokePoints;
  for (UINT i = 0; i < m_polyline.size() - 1; i++) {
    strokePoints.push_back(TThickPoint(m_polyline[i], 0));
    strokePoints.push_back(
        TThickPoint(0.5 * (m_polyline[i] + m_polyline[i + 1]), 0));
  }
  strokePoints.push_back(TThickPoint(m_polyline.back(), 0));
  m_polyline.clear();
  m_stroke = new TStroke(strokePoints);
  assert(m_stroke->getPoint(0) == m_stroke->getPoint(1));
  invalidate();
}
draw()
void SelectionTool::draw () override pure virtual
Draws the tool on the viewer.
Reimplemented from TTool.
Implemented in RasterSelectionTool, and VectorSelectionTool.
drawCommandHandle()
void SelectionTool::drawCommandHandle (const TImage * image) protected
{
  const TVectorImage *vi = dynamic_cast<const TVectorImage *>(image);
  TPixel32 frameColor(210, 210, 210);
  TPixel32 frameColor2(0, 0, 0);
  FourPoints rect = getBBox();
  drawFourPoints(rect, frameColor, 0xffff, true);
  tglColor(frameColor);
  if (m_dragTool) m_dragTool->draw();
  if (!isSelectionEditable()) return;
  double pixelSize = getPixelSize();
  if (!isLevelType() && !isSelectedFramesType()) {
    TPointD c = getCenter() + TPointD(-pixelSize, +pixelSize);
    tglColor(frameColor);
    tglDrawCircle(c, pixelSize * 5);
    tglDrawSegment(c - TPointD(pixelSize * 15, 0),
                   c + TPointD(pixelSize * 15, 0));
    tglDrawSegment(c - TPointD(0, pixelSize * 15),
                   c + TPointD(0, pixelSize * 15));
    tglColor(frameColor2);
    tglDrawCircle(getCenter(), pixelSize * 5);
    tglDrawSegment(getCenter() - TPointD(pixelSize * 15, 0),
                   getCenter() + TPointD(pixelSize * 15, 0));
    tglDrawSegment(getCenter() - TPointD(0, pixelSize * 15),
                   getCenter() + TPointD(0, pixelSize * 15));
  }
  TPointD bl(rect.getP00().x - pixelSize, rect.getP00().y + pixelSize);
  TPointD tl(rect.getP01().x - pixelSize, rect.getP01().y + pixelSize);
  TPointD br(rect.getP10().x - pixelSize, rect.getP10().y + pixelSize);
  TPointD tr(rect.getP11().x - pixelSize, rect.getP11().y + pixelSize);
  drawSquare(bl, pixelSize * 4, frameColor);
  drawSquare(tl, pixelSize * 4, frameColor);
  drawSquare(br, pixelSize * 4, frameColor);
  drawSquare(tr, pixelSize * 4, frameColor);
  drawSquare(rect.getP00(), pixelSize * 4, frameColor2);
  drawSquare(rect.getP01(), pixelSize * 4, frameColor2);
  drawSquare(rect.getP10(), pixelSize * 4, frameColor2);
  drawSquare(rect.getP11(), pixelSize * 4, frameColor2);
  if (vi && !m_deformValues.m_isSelectionModified) {
    TPointD thickCommandPos =
        rect.getP10() - TPointD(14 * pixelSize, 15 * pixelSize);
    drawRectWhitArrow(thickCommandPos, pixelSize);
  }
  drawSquare(0.5 * (br + tr), pixelSize * 4, frameColor);
  drawSquare(0.5 * (tl + tr), pixelSize * 4, frameColor);
  drawSquare(0.5 * (br + bl), pixelSize * 4, frameColor);
  drawSquare(0.5 * (tl + bl), pixelSize * 4, frameColor);
  drawSquare(0.5 * (rect.getP10() + rect.getP11()), pixelSize * 4, frameColor2);
  drawSquare(0.5 * (rect.getP01() + rect.getP11()), pixelSize * 4, frameColor2);
  drawSquare(0.5 * (rect.getP10() + rect.getP00()), pixelSize * 4, frameColor2);
  drawSquare(0.5 * (rect.getP01() + rect.getP00()), pixelSize * 4, frameColor2);
}
drawFreehandSelection()
void SelectionTool::drawFreehandSelection () protected
{
  if (m_track.isEmpty()) return;
  TPixel color = ToonzCheck::instance()->getChecks() & ToonzCheck::eBlackBg
                     ? TPixel32::White
                     : TPixel32::Black;
  tglColor(color);
  m_track.drawAllFragments();
}
drawPolylineSelection()
void SelectionTool::drawPolylineSelection () protected
{
  if (m_polyline.empty()) return;
  TPixel color = ToonzCheck::instance()->getChecks() & ToonzCheck::eBlackBg
                     ? TPixel32::White
                     : TPixel32::Black;
  tglColor(color);
  tglDrawCircle(m_polyline[0], 2);
  glBegin(GL_LINE_STRIP);
  for (UINT i = 0; i < m_polyline.size(); i++) tglVertex(m_polyline[i]);
  tglVertex(m_mousePosition);
  glEnd();
}
drawRectSelection()
void SelectionTool::drawRectSelection (const TImage * image) protected
{
  const TVectorImage *vi   = dynamic_cast<const TVectorImage *>(image);
  unsigned short stipple   = 0x3F33;
  FourPoints selectingRect = m_selectingRect;
  if (vi && m_curPos.x >= m_firstPos.x) stipple = 0xFF00;
  drawFourPoints(selectingRect, TPixel32::Black, stipple, true);
}
freehandDrag()
void SelectionTool::freehandDrag (const TPointD & pos) protected
Viene aggiunto pos a m_track e disegnato un altro pezzetto del lazzo.
{
  double pixelSize = getPixelSize();
  m_track.add(TThickPoint(pos, 0), pixelSize * pixelSize);
}
References StrokeGenerator::add().
getBBox()
DragSelectionTool::FourPoints SelectionTool::getBBox (int index = 0) const
{
  if (m_bboxs.empty()) return DragSelectionTool::FourPoints();
  assert((int)m_bboxs.size() > index);
  return m_bboxs[index];
}
getBBoxsCount()
int SelectionTool::getBBoxsCount () const
{ return m_bboxs.size(); }
getCenter()
TPointD SelectionTool::getCenter (int index = 0) const
{
  if (m_centers.empty()) return TPointD();
  assert((int)m_centers.size() > index);
  return m_centers[index];
}
getCursorId()
int SelectionTool::getCursorId () const override virtual
Returns the type of cursor used by the tool.
See also
For a list of cursor ids cursor.h
Reimplemented from TTool.
Reimplemented in VectorSelectionTool.
{
  TImageP image    = getImage(false);
  TToonzImageP ti  = (TToonzImageP)image;
  TRasterImageP ri = (TRasterImageP)image;
  TVectorImageP vi = (TVectorImageP)image;
  if (!ti && !vi && !ri) return ToolCursor::StrokeSelectCursor;
  return m_cursorId;
}
getFreeDeformer()
FreeDeformer * SelectionTool::getFreeDeformer (int index = 0) const
{
  if (m_freeDeformers.empty()) return 0;
  return m_freeDeformers[index];
}
getProperties()
TPropertyGroup * SelectionTool::getProperties (int targetType) inline override virtual
Reimplemented from TTool.
{ return &m_prop; }
getSelectedPoint()
int SelectionTool::getSelectedPoint () const inline
{ return m_selectedPoint; }
getSelectedStyles()
virtual QSet< int > SelectionTool::getSelectedStyles () const inline virtual
{ return QSet<int>(); }
getSelection()
TSelection * SelectionTool::getSelection () override pure virtual
Returns a pointer to the tool selection.
Reimplemented from TTool.
Implemented in RasterSelectionTool, and VectorSelectionTool.
getToolType()
ToolType SelectionTool::getToolType () const inline override virtual
Implements TTool.
{ return TTool::LevelWriteTool; }
isConstantThickness()
virtual bool SelectionTool::isConstantThickness () const inline virtual
{ return true; }
isEventAcceptable()
bool SelectionTool::isEventAcceptable (QEvent * e) override virtual
Reimplemented from TTool.
{
  if (!isEnabled()) return false;
  if (isSelectionEmpty()) return false;
  // arrow keys will be used for moving the selected region
  QKeyEvent *keyEvent = static_cast<QKeyEvent *>(e);
  int key             = keyEvent->key();
  return (key == Qt::Key_Up || key == Qt::Key_Down || key == Qt::Key_Left ||
          key == Qt::Key_Right);
}
isFloating()
virtual bool SelectionTool::isFloating () const inline virtual
{ return false; }
isLevelType()
virtual bool SelectionTool::isLevelType () const inline virtual
{ return false; }
isModifiableSelectionType()
virtual bool SelectionTool::isModifiableSelectionType () const inline virtual
{
    return !(isLevelType() || isSelectedFramesType());
  }
isSameStyleType()
virtual bool SelectionTool::isSameStyleType () const inline virtual
{ return false; }
isSelectedFramesType()
virtual bool SelectionTool::isSelectedFramesType () const inline virtual
{ return false; }
isSelectionEditable()
virtual bool SelectionTool::isSelectionEditable () inline virtual
{ return true; }
keyDown()
bool SelectionTool::keyDown (QKeyEvent * event) override virtual
Reimplemented from TTool.
{
  if (isSelectionEmpty()) return false;
  TPointD delta;
  switch (event->key()) {
  case Qt::Key_Up:
    delta.y = 1;
    break;
  case Qt::Key_Down:
    delta.y = -1;
    break;
  case Qt::Key_Left:
    delta.x = -1;
    break;
  case Qt::Key_Right:
    delta.x = 1;
    break;
  default:
    return false;
    break;
  }
  if (event->modifiers() & Qt::ShiftModifier) {
    delta.x *= 10.0;
    delta.y *= 10.0;
  } else if (event->modifiers() & Qt::ControlModifier) {
    delta.x *= 0.1;
    delta.y *= 0.1;
  }
  TImageP image = getImage(true);
  TToonzImageP ti  = (TToonzImageP)image;
  TRasterImageP ri = (TRasterImageP)image;
  TVectorImageP vi = (TVectorImageP)image;
  if (!ti && !vi && !ri) return false;
  std::unique_ptr<DragTool> dragTool(createNewMoveSelectionTool(this));
  TAffine aff = TTranslation(delta);
  dragTool->transform(aff);
  double factor = 1.0 / Stage::inch;
  m_deformValues.m_moveValue += factor * delta;
  dragTool->addTransformUndo();
  TTool::getApplication()->getCurrentTool()->notifyToolChanged();
  invalidate();
  return true;
}
leftButtonDoubleClick()
void SelectionTool::leftButtonDoubleClick (const TPointD & , const TMouseEvent & e) override pure virtual
Reimplemented from TTool.
leftButtonDown()
void SelectionTool::leftButtonDown (const TPointD & pos, const TMouseEvent & e) override virtual
Reimplemented from TTool.
{
  TImageP image = getImage(false);
  if (!image) return;
  if (m_polyline.size() == 0) {
    modifySelectionOnClick(image, pos, e);
    if (m_what == ROTATION) m_dragTool = createNewRotationTool(this);
    if (!e.isShiftPressed() && m_what == Inside)
      m_dragTool = createNewMoveSelectionTool(this);
    else if (m_what == MOVE_CENTER)
      m_dragTool = new MoveCenterTool(this);
    else if (m_what == SCALE)
      m_dragTool = createNewScaleTool(this, ScaleType::GLOBAL);
    else if (m_what == SCALE_X)
      m_dragTool = createNewScaleTool(this, ScaleType::HORIZONTAL);
    else if (m_what == SCALE_Y)
      m_dragTool = createNewScaleTool(this, ScaleType::VERTICAL);
    else if (m_what == DEFORM)
      m_dragTool = createNewFreeDeformTool(this);
    else if (m_what == GLOBAL_THICKNESS)
      m_dragTool = new VectorChangeThicknessTool((VectorSelectionTool *)this);
    if (m_dragTool) m_dragTool->leftButtonDown(pos, e);
  } else
    m_selecting = true;
  if (m_selecting) {
    if (m_stroke) {
      delete m_stroke;
      m_stroke = 0;
    }
    if (m_strokeSelectionType.getValue() == FREEHAND_SELECTION)
      startFreehand(pos);
    if (m_strokeSelectionType.getValue() == POLYLINE_SELECTION)
      addPointPolyline(pos);
    else if (m_polyline.size() != 0)
      m_polyline.clear();
  }
  m_firstPos = m_curPos    = pos;
  m_leftButtonMousePressed = true;
  m_shiftPressed           = e.isShiftPressed();
}
leftButtonDrag()
void SelectionTool::leftButtonDrag (const TPointD & pos, const TMouseEvent &) override pure virtual
Reimplemented from TTool.
leftButtonUp()
void SelectionTool::leftButtonUp (const TPointD & pos, const TMouseEvent &) override pure virtual
Reimplemented from TTool.
mouseMove()
void SelectionTool::mouseMove (const TPointD & pos, const TMouseEvent & e) override virtual
Reimplemented from TTool.
{
  updateAction(pos, e);
  if (m_strokeSelectionType.getValue() == POLYLINE_SELECTION) {
    m_mousePosition = pos;
    invalidate();
  }
}
onActivate()
void SelectionTool::onActivate () override virtual
Callback invoked whenever the tool activates.
Reimplemented from TTool.
Reimplemented in VectorSelectionTool.
{
  if (m_firstTime) {
    m_strokeSelectionType.setValue(::to_wstring(SelectionType.getValue()));
    m_firstTime = false;
  }
  if (isLevelType() || isSelectedFramesType()) return;
  doOnActivate();
}
Referenced by RasterSelectionTool::onActivate(), and VectorSelectionTool::onActivate().
onDeactivate()
void SelectionTool::onDeactivate () override virtual
Callback for tool deactivation, includes tool switch.
Reimplemented from TTool.
Reimplemented in VectorSelectionTool.
{
  if (isLevelType() || isSelectedFramesType()) return;
  doOnDeactivate();
}
Referenced by VectorSelectionTool::onDeactivate().
onImageChanged()
void SelectionTool::onImageChanged () override pure virtual
Notifies changes in the image in use.
Reimplemented from TTool.
Implemented in RasterSelectionTool, and VectorSelectionTool.
onPropertyChanged()
bool SelectionTool::onPropertyChanged (std::string propertyName) override virtual
 Does the tasks associated to changes in \p propertyName and returns \p
true; Does the tasks associated to changes in propertyName and returns true.
Reimplemented from TTool.
Reimplemented in VectorSelectionTool.
{
  if (propertyName == m_strokeSelectionType.getName()) {
    SelectionType = ::to_string(m_strokeSelectionType.getValue());
    return true;
  }
  return false;
}
Referenced by RasterSelectionTool::onPropertyChanged(), and VectorSelectionTool::onPropertyChanged().
onSelectionChanged()
void SelectionTool::onSelectionChanged () override virtual
Implements TSelection::View.
{
  computeBBox();
  invalidate();
  m_polyline.clear();
}
setBBox()
void SelectionTool::setBBox (const DragSelectionTool::FourPoints & points, int index = 0) virtual
{
  if (m_bboxs.empty()) return;
  assert((int)m_bboxs.size() > index);
  m_bboxs[index] = points;
}
setCenter()
void SelectionTool::setCenter (const TPointD & center, int index = 0)
{
  if (m_centers.empty()) return;
  assert((int)m_centers.size() > index);
  m_centers[index] = center;
}
startFreehand()
void SelectionTool::startFreehand (const TPointD & pos) protected
Viene aggiunto pos a m_track e disegnato il primo pezzetto del lazzo. Viene inizializzato m_firstPos
{
  m_track.clear();
  m_firstPos       = pos;
  double pixelSize = getPixelSize();
  m_track.add(TThickPoint(pos, 0), pixelSize * pixelSize);
}
References StrokeGenerator::add(), and StrokeGenerator::clear().
updateAction()
void SelectionTool::updateAction (TPointD pos, const TMouseEvent & e) protected virtual
{
  TImageP image    = getImage(false);
  TToonzImageP ti  = image;
  TRasterImageP ri = image;
  TVectorImageP vi = image;
  m_what     = Outside;
  m_cursorId = ToolCursor::StrokeSelectCursor;
  if (!ti && !vi && !ri) return;
  bool shift = e.isShiftPressed();
  if (shift && !m_leftButtonMousePressed && isModifiableSelectionType()) {
    m_what     = ADD_SELECTION;
    m_cursorId = ToolCursor::SplineEditorCursorAdd;
  } else if (m_leftButtonMousePressed)
    return;
  if (!isSelectionEditable()) return;
  FourPoints bbox = getBBox();
  double pixelSize = getPixelSize();
  if (!bbox.isEmpty()) {
    double maxDist  = 17 * pixelSize;
    double maxDist2 = maxDist * maxDist;
    double p        = (15 * pixelSize);
    m_selectedPoint = NONE;
    if (tdistance2(bbox.getP00(), pos) < maxDist2 + p)
      m_selectedPoint = P00;
    else if (tdistance2(bbox.getP11(), pos) < maxDist2 + p)
      m_selectedPoint = P11;
    else if (tdistance2(bbox.getP01(), pos) < maxDist2 + p)
      m_selectedPoint = P01;
    else if (tdistance2(bbox.getP10(), pos) < maxDist2 + p)
      m_selectedPoint = P10;
    if (tdistance2(bbox.getBottomLeft() + TPointD(-p, -p), pos) < maxDist2) {
      m_what     = ROTATION;
      m_cursorId = ToolCursor::RotBottomLeft;
      return;
    } else if (tdistance2(bbox.getBottomRight() + TPointD(p, -p), pos) <
               maxDist2) {
      m_what     = ROTATION;
      m_cursorId = ToolCursor::RotBottomRight;
      return;
    } else if (tdistance2(bbox.getTopRight() + TPointD(p, p), pos) < maxDist2) {
      m_what     = ROTATION;
      m_cursorId = ToolCursor::RotCursor;
      return;
    } else if (tdistance2(bbox.getTopLeft() + TPointD(-p, p), pos) < maxDist2) {
      m_what     = ROTATION;
      m_cursorId = ToolCursor::RotTopLeft;
      return;
    }
    maxDist  = 5 * pixelSize;
    maxDist2 = maxDist * maxDist;
    if (!isLevelType() && !isSelectedFramesType() &&
        tdistance2(getCenter(), pos) < maxDist2) {
      m_what     = MOVE_CENTER;
      m_cursorId = ToolCursor::PointingHandCursor;
      return;
    }
    if (tdistance2(bbox.getP00(), pos) < maxDist2 ||
        tdistance2(bbox.getP11(), pos) < maxDist2 ||
        tdistance2(bbox.getP01(), pos) < maxDist2 ||
        tdistance2(bbox.getP10(), pos) < maxDist2) {
      if (!e.isCtrlPressed() || isLevelType() || isSelectedFramesType()) {
        m_what = SCALE;
        if (tdistance2(bbox.getTopRight(), pos) < maxDist2 ||
            tdistance2(bbox.getBottomLeft(), pos) < maxDist2)
          m_cursorId = ToolCursor::ScaleCursor;
        else
          m_cursorId = ToolCursor::ScaleInvCursor;
      } else {
        m_cursorId = ToolCursor::DistortCursor;
        m_what     = DEFORM;
      }
      return;
    }
    if (isCloseToSegment(pos, TSegment(bbox.getPoint(0), bbox.getPoint(3)),
                         maxDist))
      m_selectedPoint = P0M;
    else if (isCloseToSegment(pos, TSegment(bbox.getPoint(1), bbox.getPoint(2)),
                              maxDist))
      m_selectedPoint = P1M;
    else if (isCloseToSegment(pos, TSegment(bbox.getPoint(3), bbox.getPoint(2)),
                              maxDist))
      m_selectedPoint = PM1;
    else if (isCloseToSegment(pos, TSegment(bbox.getPoint(0), bbox.getPoint(1)),
                              maxDist))
      m_selectedPoint = PM0;
    if (m_selectedPoint == P0M || m_selectedPoint == P1M) {
      if (!e.isCtrlPressed() || isLevelType() || isSelectedFramesType()) {
        m_cursorId = ToolCursor::ScaleHCursor;
        m_what     = SCALE_X;
      } else {
        m_cursorId = ToolCursor::DistortCursor;
        m_what     = DEFORM;
      }
      return;
    }
    if (m_selectedPoint == PM1 || m_selectedPoint == PM0) {
      if (!e.isCtrlPressed() || isLevelType() || isSelectedFramesType()) {
        m_cursorId = ToolCursor::ScaleVCursor;
        m_what     = SCALE_Y;
      } else {
        m_cursorId = ToolCursor::DistortCursor;
        m_what     = DEFORM;
      }
      return;
    }
    TPointD hpos = bbox.getP10() - TPointD(14 * pixelSize, 15 * pixelSize);
    TRectD rect(hpos - TPointD(14 * pixelSize, 5 * pixelSize),
                hpos + TPointD(14 * pixelSize, 5 * pixelSize));
    if (!m_deformValues.m_isSelectionModified && rect.contains(pos) && vi &&
        !TTool::getApplication()->getCurrentObject()->isSpline()) {
      m_what     = GLOBAL_THICKNESS;
      m_cursorId = ToolCursor::PumpCursor;
      return;
    }
  }
  m_selectedPoint = NONE;
  if ((isLevelType() || isSelectedFramesType()) && !isSameStyleType()) {
    m_what     = Inside;
    m_cursorId = ToolCursor::LevelSelectCursor;
  }
  if (shift) return;
  if (!vi && bbox.contains(pos)) {
    m_what = Inside;
    if (isLevelType() || isSelectedFramesType())
      m_cursorId = ToolCursor::LevelSelectCursor;
    else
      m_cursorId = ToolCursor::MoveCursor;
  }
}
updateTranslation()
void SelectionTool::updateTranslation () override protected virtual
Reimplemented from TTool.
{
  m_strokeSelectionType.setQStringName(tr("Type:"));
  m_strokeSelectionType.setItemUIName(RECT_SELECTION, tr("Rectangular"));
  m_strokeSelectionType.setItemUIName(FREEHAND_SELECTION, tr("Freehand"));
  m_strokeSelectionType.setItemUIName(POLYLINE_SELECTION, tr("Polyline"));
}
Member Data Documentation
m_bboxs
std::vector<DragSelectionTool::FourPoints> SelectionTool::m_bboxs protected
m_centers
std::vector<TPointD> SelectionTool::m_centers protected
m_curPos
TPointD SelectionTool::m_curPos protected
m_cursorId
int SelectionTool::m_cursorId protected
m_deformValues
DragSelectionTool::DeformValues SelectionTool::m_deformValues
m_dragTool
DragSelectionTool::DragTool* SelectionTool::m_dragTool protected
m_firstPos
TPointD SelectionTool::m_firstPos protected
m_firstTime
bool SelectionTool::m_firstTime protected
m_freeDeformers
std::vector<FreeDeformer *> SelectionTool::m_freeDeformers protected
m_justSelected
bool SelectionTool::m_justSelected protected
m_leftButtonMousePressed
bool SelectionTool::m_leftButtonMousePressed protected
m_mousePosition
TPointD SelectionTool::m_mousePosition protected
m_polyline
std::vector<TPointD> SelectionTool::m_polyline protected
m_prop
TPropertyGroup SelectionTool::m_prop protected
m_selecting
bool SelectionTool::m_selecting protected
m_selectingRect
DragSelectionTool::FourPoints SelectionTool::m_selectingRect protected
m_shiftPressed
bool SelectionTool::m_shiftPressed protected
m_stroke
TStroke* SelectionTool::m_stroke protected
m_strokeSelectionType
TEnumProperty SelectionTool::m_strokeSelectionType protected
m_track
StrokeGenerator SelectionTool::m_track protected
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/tnztools/selectiontool.h
E:/opentoonz/toonz/sources/tnztools/selectiontool.cpp