opentoonz: tcg::list< T > Class Template Reference
tcg::list< T > Class Template Reference
Double linked list container class with indexed access to elements.
#include <list.h>
Classes
struct const_iterator
struct iterator
Public Member Functions
list (size_t count, const T &val)
template<typename InIt >
list (InIt begin, InIt end)
template<typename BidIt >
list (BidIt begin, BidIt end, size_t nodesCount)
Constructs from a range of (index, value) pairs.
list (const list &other)
list & operator= (const list &other)
list (list &&other)
list & operator= (list &&other)
size_t insert (size_t idx, TCG_FORWARD_TYPE(T) val)
template<typename Iter >
size_t insert (size_t idx, Iter begin, Iter end)
size_t erase (size_t idx)
size_t erase (size_t begin, size_t end)
void clear ()
void swap (list &other)
void swap (list &a, list &b)
void swap (list &&other)
void swap (list &a, list &&b)
void swap (list &&a, list &b)
void move (size_t afterDst, size_t srcBegin, size_t srcEnd)
void move (iterator afterDst, iterator srcBegin, iterator srcEnd)
iterator insert (iterator it, const T &val)
iterator erase (iterator it)
template<typename Iter >
iterator insert (iterator it, Iter begin, Iter end)
iterator erase (iterator begin, iterator end)
size_t push_front (const T &val)
size_t push_back (const T &val)
void pop_front ()
void pop_back ()
T & front ()
const T & front () const
T & back ()
const T & back () const
iterator begin ()
const_iterator begin () const
iterator last ()
const_iterator last () const
iterator end ()
const_iterator end () const
iterator insert (iterator it, T &&val)
size_t push_front (T &&val)
size_t push_back (T &&val)
Public Member Functions inherited from tcg::list_base< T >
list_base (size_t count, const T &val)
template<typename InIt >
list_base (InIt begin, InIt end)
list_base (const list_base &other)
list_base & operator= (const list_base &other)
list_base (list_base &&other)
list_base & operator= (list_base &&other)
T & operator[] (size_t idx)
const T & operator[] (size_t idx) const
bool isValid (size_t idx) const
size_t size () const
size_t nodesCount () const
void reserve (size_t size)
size_t capacity () const
void clear ()
bool empty () const
void _swap (list_base &a, list_base &b)
void _swap (list_base &a, list_base &&b)
void _swap (list_base &&a, list_base &b)
template<typename ForIt >
list_base (ForIt begin, ForIt end, size_t nodesCount)
Constructs from a range of (index, value) pairs.
Protected Types
typedef list_base< T >::list_node list_node
Protected Types inherited from tcg::list_base< T >
typedef _list_node< T > list_node
Additional Inherited Members
Public Types inherited from tcg::list_base< T >
typedef T value_type
typedef ::size_t size_t
Static Public Attributes inherited from tcg::list_base< T >
static const size_t _neg = -1
Protected Member Functions inherited from tcg::list_base< T >
size_t buyNode (TCG_FORWARD_TYPE(T) val)
void sellNode (size_t idx)
void sellNodes (size_t begin, size_t end)
void move (size_t afterDst, size_t &dstBegin, size_t &dstRBegin, size_t srcBegin, size_t srcEnd, size_t srcRBegin)
Protected Attributes inherited from tcg::list_base< T >
std::vector< list_node > m_vector
size_t m_size
size_t m_clearedHead
Detailed Description
template<typename T>
class tcg::list< T >
Double linked list container class with indexed access to elements.
This class is the result of implementing a double linked list using a dynamic random access sequential container as the underlying pool for the list's nodes.
This is somewhat different than supplying a custom allocator to an existing list implementation, like std::list, since:
No memory model of the underlying container is actually required.
The underlying container provides explicit access to nodes using their associated insertion indexes, so std::list could not be used as-is.
The nodes pool (see list_base) is an internal lazy container that saves released nodes without actually deallocating them (of course, their content is properly destroyed). They are rather stored into an internal stack of released nodes, ready to be reacquired.
Features
Insertion indexes are automatically generated keys with the same access time of the underlying container (typically super-fast O(1)).
Stable indexes and iterators with respect to every operation.
Copying an indexed list preserves the original indexes.
Indexes are process independent - they can be saved on file and restored later (although you probably want to squeeze the list before saving).
Use cases
This class is surprisingly useful for cross-referencing. A graph data structure, for example, can be implemented using a pair of indexed lists for vertexes and edges.
Known issues
The lazy nature of this container class may require squeezing the list's content at strategic places in your code, as noted before. Beware that composite cross-referencing may be hard to track precisely during this particular operation.
Remarks
Current implementation explicitly uses an std::vector class as the underlying random access container. Future improvements will make the container class a template parameter.
See also
Template class tcg::Mesh for a notable use case.
Member Typedef Documentation
list_node
template<typename T > typedef list_base<T>::list_node tcg::list< T >::list_node protected
Constructor & Destructor Documentation
list() [1/6]
template<typename T > tcg::list< T >::list () inline
: m_begin(_neg), m_rbegin(_neg) {}
list() [2/6]
template<typename T > tcg::list< T >::list (size_t count, const T & val) inline
      : list_base<T>(count, val), m_begin(0), m_rbegin(count - 1) {}
list() [3/6]
template<typename T > template<typename InIt > tcg::list< T >::list (InIt begin, InIt end) inline
      : list_base<T>(begin, end)
      , m_begin(list_base<T>::m_size ? 0 : _neg)
      , m_rbegin(list_base<T>::m_size - 1) {}
list() [4/6]
template<typename T > template<typename BidIt > tcg::list< T >::list (BidIt begin, BidIt end, size_t nodesCount) inline
Constructs from a range of (index, value) pairs.
      : list_base<T>(begin, end, nodesCount) {
    if (begin != end) m_begin = (*begin).first, m_rbegin = (*--end).first;
  }
list() [5/6]
template<typename T > tcg::list< T >::list (const list< T > & other) inline
      : list_base<T>(other), m_begin(other.m_begin), m_rbegin(other.m_rbegin) {}
list() [6/6]
template<typename T > tcg::list< T >::list (list< T > && other) inline
      : list_base<T>(std::forward<list_base<T>>(other))
      , m_begin(other.m_begin)
      , m_rbegin(other.m_rbegin) {}
Member Function Documentation
back() [1/2]
template<typename T > T & tcg::list< T >::back () inline
{ return m_vector[m_rbegin].value(); }
back() [2/2]
template<typename T > const T & tcg::list< T >::back () const inline
{ return m_vector[m_rbegin].value(); }
begin() [1/2]
template<typename T > iterator tcg::list< T >::begin () inline
{ return iterator(this, m_begin); }
begin() [2/2]
template<typename T > const_iterator tcg::list< T >::begin () const inline
{ return const_iterator(this, m_begin); }
clear()
template<typename T > void tcg::list< T >::clear () inline
               {
    list_base<T>::clear();
    m_begin = m_rbegin = _neg;
  }
end() [1/2]
template<typename T > iterator tcg::list< T >::end () inline
{ return iterator(this, _neg); }
end() [2/2]
template<typename T > const_iterator tcg::list< T >::end () const inline
{ return const_iterator(this, _neg); }
erase() [1/4]
template<typename T > iterator tcg::list< T >::erase (iterator begin, iterator end) inline
{
    return iterator(this, erase(begin.m_idx, end.m_idx));
  }
erase() [2/4]
template<typename T > iterator tcg::list< T >::erase (iterator it) inline
{ return iterator(this, erase(it.m_idx)); }
erase() [3/4]
template<typename T > size_t tcg::list< T >::erase (size_t begin, size_t end) inline
{
    assert(list_base<T>::isValid(begin));
    if (begin == m_begin) m_begin = end;
    if (end == m_rbegin) m_rbegin = m_vector[begin].m_prev;
    list_base<T>::sellNodes(begin, end);
    return end;
  }
erase() [4/4]
template<typename T > size_t tcg::list< T >::erase (size_t idx) inline
{
    assert(list_base<T>::isValid(idx));
    if (idx == m_begin) m_begin   = m_vector[idx].m_next;
    if (idx == m_rbegin) m_rbegin = m_vector[idx].m_prev;
    size_t result = m_vector[idx].m_next;
    list_base<T>::sellNode(idx);
    return result;
  }
front() [1/2]
template<typename T > T & tcg::list< T >::front () inline
{ return m_vector[m_begin].value(); }
front() [2/2]
template<typename T > const T & tcg::list< T >::front () const inline
{ return m_vector[m_begin].value(); }
insert() [1/5]
template<typename T > iterator tcg::list< T >::insert (iterator it, const T & val) inline
{
    return iterator(this, insert(it.m_idx, val));
  }
insert() [2/5]
template<typename T > template<typename Iter > iterator tcg::list< T >::insert (iterator it, Iter begin, Iter end) inline
{
    return iterator(this, insert(it.m_idx, begin, end));
  }
insert() [3/5]
template<typename T > iterator tcg::list< T >::insert (iterator it, T && val) inline
{
    return iterator(this, insert<T>(it.m_idx, std::forward<T>(val)));
  }
insert() [4/5]
template<typename T > template<typename Iter > size_t tcg::list< T >::insert (size_t idx, Iter begin, Iter end) inline
{
    if (begin == end) return idx;
    assert(idx == _neg || list_base<T>::isValid(idx));
    size_t res = insert(idx, *begin);
    for (++begin; begin != end; ++begin) insert(idx, *begin);
    return res;
  }
insert() [5/5]
template<typename T > size_t tcg::list< T >::insert (size_t idx, TCG_FORWARD_TYPE(T) val) inline
{
    assert(idx == _neg || list_base<T>::isValid(idx));
    size_t nodeIdx  = list_base<T>::buyNode(TCG_FORWARD(T, val));
    list_node &node = m_vector[nodeIdx];
    // Update links
    if (idx != _neg) {
      // node has a valid next
      list_node &next = m_vector[idx];
      node.m_prev                                           = next.m_prev;
      next.m_prev                                           = nodeIdx;
      node.m_next                                           = idx;
      if (node.m_prev != _neg) m_vector[node.m_prev].m_next = nodeIdx;
    } else {
      node.m_next                                     = _neg;
      node.m_prev                                     = m_rbegin;
      if (m_rbegin != _neg) m_vector[m_rbegin].m_next = nodeIdx;
      m_rbegin                                        = nodeIdx;
    }
    if (idx == m_begin) m_begin = nodeIdx;
    return nodeIdx;
  }
last() [1/2]
template<typename T > iterator tcg::list< T >::last () inline
{ return iterator(this, m_rbegin); }
last() [2/2]
template<typename T > const_iterator tcg::list< T >::last () const inline
{ return const_iterator(this, m_rbegin); }
move() [1/2]
template<typename T > void tcg::list< T >::move (iterator afterDst, iterator srcBegin, iterator srcEnd) inline
See also
The equivalent function move(size_t, size_t, size_t). Moves range [srcBegin, srcEnd) right before afterDst.
Parameters
afterDst Iterator right after the destination position.
srcBegin Start of the moved range.
srcEnd End of the moved range.
  {
    assert(afterDst.m_list == this && srcBegin.m_list == this &&
           srcEnd.m_list == this);
    return move(afterDst.m_idx, srcBegin.m_idx, srcEnd.m_idx);
  }
References tcg::list< T >::move().
move() [2/2]
template<typename T > void tcg::list< T >::move (size_t afterDst, size_t srcBegin, size_t srcEnd) inline
This function is tcg::list's counterpart to std::list::splice(). It moves the specified range to a different part of the list, without touching any element elements - just by altering node links.
Note
Unlike std::list::splice(), the list must be the same. Moves range [srcBegin, srcEnd) right before afterDst.
Parameters
afterDst Index right after the destination position.
srcBegin Start index of the moved range.
srcEnd End index of the moved range.
  {
    return move(afterDst, m_begin, m_rbegin, srcBegin, srcEnd, m_rbegin);
  }
References tcg::list< T >::move().
Referenced by tcg::list< T >::move().
operator=() [1/2]
template<typename T > list & tcg::list< T >::operator= (const list< T > & other) inline
Warning
tcg::list has a different copy behavior from other container classes, since it is intended to preserve the source's node indices in the process.
This means that no value-to-value assignment can take place, and thus operator='s behavior is equivalent to first clearing it, and then copy-constructing each value.
    This typically leads to performance penalties with respect to other
container classes that implement value-to-value assignments, like std::vector in case its capacity is not exceeded.
{
    m_begin = other.m_begin, m_rbegin = other.m_rbegin;
    list_base<T>::operator=(other);
    return *this;
  }
operator=() [2/2]
template<typename T > list & tcg::list< T >::operator= (list< T > && other) inline
{
    swap(*this, std::forward<list>(other));
    return *this;
  }
pop_back()
template<typename T > void tcg::list< T >::pop_back () inline
{ erase(m_rbegin); }
pop_front()
template<typename T > void tcg::list< T >::pop_front () inline
{ erase(m_begin); }
push_back() [1/2]
template<typename T > size_t tcg::list< T >::push_back (const T & val) inline
{ return insert(_neg, val); }
push_back() [2/2]
template<typename T > size_t tcg::list< T >::push_back (T && val) inline
{ return insert<T>(_neg, std::forward<T>(val)); }
push_front() [1/2]
template<typename T > size_t tcg::list< T >::push_front (const T & val) inline
{ return insert(m_begin, val); }
push_front() [2/2]
template<typename T > size_t tcg::list< T >::push_front (T && val) inline
{
    return insert<T>(m_begin, std::forward<T>(val));
  }
swap() [1/5]
template<typename T > void tcg::list< T >::swap (list< T > && a, list< T > & b) inline
{ b.swap(std::move(a)); }
swap() [2/5]
template<typename T > void tcg::list< T >::swap (list< T > && other) inline
{
    this->_swap(*this, std::move(other));
    m_begin  = other.m_begin;
    m_rbegin = other.m_rbegin;
  }
swap() [3/5]
template<typename T > void tcg::list< T >::swap (list< T > & a, list< T > && b) inline
{ a.swap(std::move(b)); }
swap() [4/5]
template<typename T > void tcg::list< T >::swap (list< T > & a, list< T > & b) inline
{ a.swap(b); }
swap() [5/5]
template<typename T > void tcg::list< T >::swap (list< T > & other) inline
{
    _swap(*this, other);
    std::swap(m_begin, other.m_begin);
    std::swap(m_rbegin, other.m_rbegin);
  }
The documentation for this class was generated from the following file:
E:/opentoonz/toonz/sources/include/tcg/list.h