opentoonz: TXshSoundLevel Class Reference
TXshSoundLevel Class Reference final
Public Member Functions
TXshSoundLevel (std::wstring name=L"", int startOffset=0, int endOffset=0)
TXshSoundLevel * clone () const
void setScene (ToonzScene *scene) override
TXshSoundLevel * getSoundLevel () override
Overridden from TXshLevel.
void loadSoundTrack ()
void loadSoundTrack (const TFilePath &fileName)
void loadData (TIStream &is) override
Load the level data (i.e. name, path, etc. e.g. from the .tnz file)
void saveData (TOStream &os) override
Save the level data (i.e. name, path, etc. e.g. to the .tnz file)
void load () override
Load the level content from the associated path.
void save () override
Save the level content to the associated path.
void save (const TFilePath &path)
void computeValuesFor (const Orientation *o)
void computeValues ()
void getValueAtPixel (const Orientation *o, int pixel, DoublePair &values) const
void setFrameRate (double fps)
double getFrameRate () const
void setPath (const TFilePath &path)
TFilePath getPath () const override
Return the file path associated with the level.
void setSoundTrack (TSoundTrackP st)
TSoundTrackP getSoundTrack ()
int getFrameSoundCount () const
Pay Attention this is the sound frame !!
int getSamplePerFrame () const
int getFrameCount () const override
void getFids (std::vector< TFrameId > &fids) const override
Public Member Functions inherited from TXshLevel
TXshLevel (ClassCode classCode, std::wstring name)
virtual ~TXshLevel ()
void setName (std::wstring name)
int getType () const
void setType (int type)
change the level type;
ToonzScene * getScene () const
Return the ToonzScene the level belongs to;.
virtual void setScene (ToonzScene *scene)
virtual TXshSimpleLevel * getSimpleLevel ()
Method (to be overridden in subclasses) to downcast to TXshSimpleLevel.
virtual TXshChildLevel * getChildLevel ()
Method (to be overridden in subclasses) to downcast to TXshChildLevel.
virtual TXshZeraryFxLevel * getZeraryFxLevel ()
virtual TXshPaletteLevel * getPaletteLevel ()
Method (to be overridden in subclasses) to downcast to TXshPaletteLevel.
virtual TXshSoundLevel * getSoundLevel ()
Method (to be overridden in subclasses) to downcast to TXshSoundLevel.
virtual TXshSoundTextLevel * getSoundTextLevel ()
std::wstring getName () const
Return level name.
std::wstring getShortName () const
Return level short name.
virtual TFilePath getPath () const
Return the file path associated with the level.
virtual bool isEmpty () const
virtual int getFrameCount () const
virtual void getFids (std::vector< TFrameId > &fids) const
void loadData (TIStream &is) override=0
Load the level data (i.e. name, path, etc. e.g. from the .tnz file)
void saveData (TOStream &os) override=0
Save the level data (i.e. name, path, etc. e.g. to the .tnz file)
virtual void load ()=0
Load the level content from the associated path.
virtual void save ()=0
Save the level content to the associated path.
HookSet * getHookSet () const
virtual void setDirtyFlag (bool on)
Mark the level as "modified".
Public Member Functions inherited from TSmartObject
TSmartObject (ClassCode classCode)
void addRef ()
void release ()
TINT32 getRefCount () const
Public Member Functions inherited from TPersist
virtual void loadData (TIStream &is)=0
virtual void saveData (TOStream &os)=0
std::string getStreamTag () const
virtual const TPersistDeclaration * getDeclaration () const =0
Additional Inherited Members
Public Types inherited from TSmartObject
typedef short ClassCode
Public Types inherited from TPersist
typedef TPersist * CreateProc()
Static Public Member Functions inherited from TSmartObject
static TINT32 getInstanceCount (ClassCode code)
Static Public Member Functions inherited from TPersist
static void declare (CreateProc *)
static TPersist * create (const std::string &name)
Protected Member Functions inherited from TXshLevel
void updateShortName ()
create shortname from the level name
Protected Attributes inherited from TXshLevel
std::wstring m_name
std::wstring m_shortName
int m_type
HookSet * m_hookSet
ToonzScene * m_scene
Detailed Description
Constructor & Destructor Documentation
TXshSoundLevel()
TXshSoundLevel::TXshSoundLevel (std::wstring name = L"", int startOffset = 0, int endOffset = 0)
    : TXshLevel(m_classCode, name)
    , m_soundTrack(0)
    , m_duration(0)
    , m_samplePerFrame(0)
    , m_frameSoundCount(0)
    , m_fps(12)
    , m_path() {}
~TXshSoundLevel()
TXshSoundLevel::~TXshSoundLevel ()
{}
Member Function Documentation
clone()
TXshSoundLevel * TXshSoundLevel::clone () const
{
  TXshSoundLevel *sound = new TXshSoundLevel();
  sound->setSoundTrack(m_soundTrack->clone());
  sound->m_duration        = m_duration;
  sound->m_path            = m_path;
  sound->m_samplePerFrame  = m_samplePerFrame;
  sound->m_frameSoundCount = m_frameSoundCount;
  sound->m_fps             = m_fps;
  return sound;
}
computeValues()
void TXshSoundLevel::computeValues ()
{
  for (auto o : Orientations::all()) computeValuesFor(o);
}
computeValuesFor()
void TXshSoundLevel::computeValuesFor (const Orientation * o)
{
  int frameHeight = o->dimension(PredefinedDimension::FRAME);  // time axis
  int index       = o->dimension(PredefinedDimension::INDEX);
  std::map<int, DoublePair> &values = m_values[index];
  if (frameHeight == 0) frameHeight = 1;
  values.clear();
  if (!m_soundTrack) {
    m_frameSoundCount = 0;
    m_samplePerFrame  = 0;
    return;
  }
  m_samplePerFrame      = m_soundTrack->getSampleRate() / m_fps;
  double samplePerPixel = m_samplePerFrame / frameHeight;
  int sampleCount = m_soundTrack->getSampleCount();
  if (sampleCount <= 0)  // This was if(!sampleCount)  :(
    return;              //
  m_frameSoundCount = tceil(sampleCount / m_samplePerFrame);
  double maxPressure = 0.0;
  double minPressure = 0.0;
  m_soundTrack->getMinMaxPressure(TINT32(0), (TINT32)sampleCount, TSound::LEFT,
                                  minPressure, maxPressure);
  double absMaxPressure = std::max(fabs(minPressure), fabs(maxPressure));
  if (absMaxPressure <= 0) return;
  // Adjusting using a fixed scaleFactor
  int desiredAmplitude = o->dimension(PredefinedDimension::SOUND_AMPLITUDE);
  // results will be in range -desiredAmplitude .. +desiredAmplitude
  double weightA = desiredAmplitude / absMaxPressure;
  long i = 0, j;
  long p = 0;  // se p parte da zero notazione per pixel,
  // se parte da 1 notazione per frame
  while (i < m_frameSoundCount) {
    for (j = 0; j < frameHeight - 1; ++j) {
      double min = 0.0;
      double max = 0.0;
      m_soundTrack->getMinMaxPressure(
          (TINT32)(i * m_samplePerFrame + j * samplePerPixel),
          (TINT32)(i * m_samplePerFrame + (j + 1) * samplePerPixel - 1),
          TSound::MONO, min, max);
      values.insert(std::pair<int, std::pair<double, double>>(
          p + j, std::pair<double, double>(min * weightA, max * weightA)));
    }
    double min = 0.0;
    double max = 0.0;
    m_soundTrack->getMinMaxPressure(
        (TINT32)(i * m_samplePerFrame + j * samplePerPixel),
        (TINT32)((i + 1) * m_samplePerFrame - 1), TSound::MONO, min, max);
    values.insert(std::pair<int, std::pair<double, double>>(
        p + j, std::pair<double, double>(min * weightA, max * weightA)));
    ++i;
    p += frameHeight;
  }
}
getFids()
void TXshSoundLevel::getFids (std::vector< TFrameId > & fids) const override virtual
Reimplemented from TXshLevel.
{
  int i;
  for (i = 0; i < getFrameCount(); i++) fids.push_back(TFrameId(i));
}
getFrameCount()
int TXshSoundLevel::getFrameCount () const override virtual
Reimplemented from TXshLevel.
{
  int frameCount = m_duration * m_fps;
  return (frameCount == 0) ? 1 : frameCount;
}
getFrameRate()
double TXshSoundLevel::getFrameRate () const inline
{ return m_fps; }
getFrameSoundCount()
int TXshSoundLevel::getFrameSoundCount () const inline
Pay Attention this is the sound frame !!
{ return m_frameSoundCount; }
getPath()
TFilePath TXshSoundLevel::getPath () const inline override virtual
Return the file path associated with the level.
Reimplemented from TXshLevel.
{ return m_path; }
getSamplePerFrame()
int TXshSoundLevel::getSamplePerFrame () const inline
{ return m_samplePerFrame; }
getSoundLevel()
TXshSoundLevel * TXshSoundLevel::getSoundLevel () inline override virtual
Overridden from TXshLevel.
Reimplemented from TXshLevel.
{ return this; }
getSoundTrack()
TSoundTrackP TXshSoundLevel::getSoundTrack () inline
{ return m_soundTrack; }
getValueAtPixel()
void TXshSoundLevel::getValueAtPixel (const Orientation * o, int pixel, DoublePair & values) const
{
  int index = o->dimension(PredefinedDimension::INDEX);
  std::map<int, DoublePair>::const_iterator it = m_values[index].find(pixel);
  if (it != m_values[index].end()) values = it->second;
}
load()
void TXshSoundLevel::load () override virtual
Load the level content from the associated path.
Implements TXshLevel.
{ loadSoundTrack(); }
Referenced by ToonzScene::loadLevel().
loadData()
void TXshSoundLevel::loadData (TIStream & is) override virtual
Load the level data (i.e. name, path, etc. e.g. from the .tnz file)
Implements TXshLevel.
{
  is >> m_name;
  setName(m_name);
  std::string tagName;
  bool flag = false;
  int type = UNKNOWN_XSHLEVEL;
  for (;;) {
    if (is.matchTag(tagName)) {
      if (tagName == "path") {
        is >> m_path;
        is.matchEndTag();
      } else if (tagName == "type") {
        std::string v;
        is >> v;
        if (v == "sound") type = SND_XSHLEVEL;
        is.matchEndTag();
      } else
        throw TException("unexpected tag " + tagName);
    } else
      break;
  }
  setType(type);
}
References TIStream::matchEndTag(), TIStream::matchTag(), and TXshLevel::setType().
loadSoundTrack() [1/2]
void TXshSoundLevel::loadSoundTrack ()
{
  assert(getScene());
  TSceneProperties *properties = getScene()->getProperties();
  if (properties) {
    TOutputProperties *outputProperties = properties->getOutputProperties();
    if (outputProperties) m_fps         = outputProperties->getFrameRate();
  }
  TFilePath path = getScene()->decodeFilePath(m_path);
  try {
    loadSoundTrack(path);
  } catch (TException &e) {
    throw TException(e.getMessage());
  }
}
loadSoundTrack() [2/2]
void TXshSoundLevel::loadSoundTrack (const TFilePath & fileName)
{
  try {
    TSoundTrackP st;
    TFilePath path(fileName);
    bool ret = TSoundTrackReader::load(path, st);
    if (ret) {
      m_duration = st->getDuration();
      setName(fileName.getWideName());
      setSoundTrack(st);
    }
  } catch (TException &) {
    return;
  }
}
save() [1/2]
void TXshSoundLevel::save () override virtual
Save the level content to the associated path.
Implements TXshLevel.
{ save(m_path); }
References save().
Referenced by SceneSound::save(), and save().
save() [2/2]
void TXshSoundLevel::save (const TFilePath & path)
{
  TSoundTrackWriter::save(path, m_soundTrack);
}
saveData()
void TXshSoundLevel::saveData (TOStream & os) override virtual
Save the level data (i.e. name, path, etc. e.g. to the .tnz file)
Implements TXshLevel.
{
  os << m_name;
  std::map<std::string, std::string> attr;
  os.child("type") << L"sound";
  os.child("path") << m_path;
}
References TOStream::child().
setFrameRate()
void TXshSoundLevel::setFrameRate (double fps)
Set frame rate to fps.
See also
getSamplePerFrame()
{
  if (m_fps != fps) {
    m_fps = fps;
    computeValues();
  }
}
Referenced by setScene().
setPath()
void TXshSoundLevel::setPath (const TFilePath & path) inline
{ m_path = path; }
setScene()
void TXshSoundLevel::setScene (ToonzScene * scene) override virtual
Set scene to which level belongs to scene.
See also
getScene()
Reimplemented from TXshLevel.
{
  assert(scene);
  TXshLevel::setScene(scene);
  TOutputProperties *properties = scene->getProperties()->getOutputProperties();
  assert(properties);
  setFrameRate(properties->getFrameRate());
}
References TOutputProperties::getFrameRate(), TSceneProperties::getOutputProperties(), ToonzScene::getProperties(), setFrameRate(), and TXshLevel::setScene().
Referenced by ToonzScene::loadLevel().
setSoundTrack()
void TXshSoundLevel::setSoundTrack (TSoundTrackP st) inline
{
    m_soundTrack = st;
    computeValues();
  }
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/toonz/txshsoundlevel.h
E:/opentoonz/toonz/sources/toonzlib/txshsoundlevel.cpp