opentoonz: TImageCombinationFx Class Reference
TImageCombinationFx Class Reference abstract
Public Member Functions
virtual void process (const TRasterP &up, const TRasterP &down, double frame)=0
virtual bool requiresFullRect ()
int dynamicPortGroupsCount () const override
const TFxPortDG * dynamicPortGroup (int g) const override
bool canHandle (const TRenderSettings &info, double frame) override
int getMemoryRequirement (const TRectD &rect, double frame, const TRenderSettings &info) override
bool doGetBBox (double frame, TRectD &bBox, const TRenderSettings &info) override
void doDryCompute (TRectD &rect, double frame, const TRenderSettings &info) override
void doCompute (TTile &tile, double frame, const TRenderSettings &info) override
void compatibilityTranslatePort (int majorVersion, int minorVersion, std::string &portName) override
int getPreferredInputPort () override
Public Member Functions inherited from TBaseRasterFx
std::string getPluginId () const override
Public Member Functions inherited from TRasterFx
virtual bool getBBox (double frame, TRectD &bBox, TPixel32 &bgColor)=0
virtual string getName () const =0
virtual TRect getInvalidRect (const TRect &max)=0
virtual void compute (double frame, const TTile &tile)=0
virtual void allocateAndCompute (double frame, const TDimension size, const TPointD &pos, TTile &tile)
virtual void compute (TTile &tile, double frame, const TRenderSettings &info)
This method supplies the actual fx rendering code.
void allocateAndCompute (TTile &tile, const TPointD &pos, const TDimension &size, TRasterP templateRas, double frame, const TRenderSettings &info)
virtual bool doGetBBox (double frame, TRectD &bBox, const TRenderSettings &info)=0
bool getBBox (double frame, TRectD &bBox, const TRenderSettings &info)
virtual bool isCachable () const
virtual void transform (double frame, int port, const TRectD &rectOnOutput, const TRenderSettings &infoOnOutput, TRectD &rectOnInput, TRenderSettings &infoOnInput)
virtual bool canHandle (const TRenderSettings &info, double frame)=0
virtual TAffine handledAffine (const TRenderSettings &info, double frame)
void enableCache (bool on)
bool isCacheEnabled () const
std::string getAlias (double frame, const TRenderSettings &info) const override
virtual void dryCompute (TRectD &rect, double frame, const TRenderSettings &info)
virtual int getMemoryRequirement (const TRectD &rect, double frame, const TRenderSettings &info)
virtual bool allowUserCacheOnPort (int port)
virtual bool isPlugin () const
Public Member Functions inherited from TFx
virtual std::wstring getName () const
void setName (std::wstring name)
std::wstring getFxId () const
void setFxId (std::wstring id)
TParamContainer * getParams ()
const TParamContainer * getParams () const
void addParamVar (TParamVar *var)
virtual TFx * clone (bool recursive=true) const
TFx * clone (TFx *fx, bool recursive) const
void unlinkParams ()
virtual void linkParams (TFx *src)
TFx * getLinkedFx () const
bool addInputPort (const std::string &name, TFxPort &p)
bool addInputPort (const std::string &name, TFxPort *p, int groupIndex)
bool removeInputPort (const std::string &name)
returns false on duplicate names. Ownership is transferred to the group.
bool renamePort (const std::string &oldName, const std::string &newName)
if not found.
bool connect (const std::string &name, TFx *other)
Equivalent to getInputPort(name)->setFx(other).
bool disconnect (const std::string &name)
Equivalent to getInputPort(name)->setFx(0).
int getInputPortCount () const
TFxPort * getInputPort (int index) const
TFxPort * getInputPort (const std::string &name) const
std::string getInputPortName (int index) const
virtual int dynamicPortGroupsCount () const
virtual const TFxPortDG * dynamicPortGroup (int g) const
bool hasDynamicPortGroups () const
void clearDynamicPortGroup (int g)
bool addOutputConnection (TFxPort *port)
bool removeOutputConnection (TFxPort *port)
virtual bool isZerary () const
virtual int getReferenceColumnIndex () const
virtual TFxPort * getXsheetPort () const
int getOutputConnectionCount () const
TFxPort * getOutputConnection (int i) const
virtual TFxTimeRegion getTimeRegion () const
void setActiveTimeRegion (const TFxTimeRegion &tr)
TFxTimeRegion getActiveTimeRegion () const
virtual bool checkActiveTimeRegion () const
void disconnectAll ()
virtual void getParamUIs (TParamUIConcept *&params, int &length)
std::string getFxType () const
virtual std::string getPluginId () const =0
void onChange (const TParamChange &c) override
void addObserver (TFxObserver *)
void removeObserver (TFxObserver *)
void notify (const TFxChange &change)
void notify (const TFxPortAdded &change)
void notify (const TFxPortRemoved &change)
void notify (const TFxParamAdded &change)
void notify (const TFxParamRemoved &change)
void loadData (TIStream &is) override
void saveData (TOStream &os) override
void loadPreset (TIStream &is)
void savePreset (TOStream &os)
TFxAttributes * getAttributes () const
virtual std::string getAlias (double frame, const TRenderSettings &info) const
virtual void compatibilityTranslatePort (int majorVersion, int minorVersion, std::string &portName)
virtual int getPreferredInputPort ()
virtual void callStartRenderHandler ()
virtual void callEndRenderHandler ()
virtual void callStartRenderFrameHandler (const TRenderSettings *rs, double frame)
virtual void callEndRenderFrameHandler (const TRenderSettings *rs, double frame)
virtual void onObsoleteParamLoaded (const std::string &paramName)
void setFxVersion (int)
int getFxVersion () const
unsigned long getIdentifier () const
void setIdentifier (unsigned long id)
void setNewIdentifier ()
Public Member Functions inherited from TSmartObject
TSmartObject (ClassCode classCode)
void addRef ()
void release ()
TINT32 getRefCount () const
Public Member Functions inherited from TPersist
virtual void loadData (TIStream &is)=0
virtual void saveData (TOStream &os)=0
std::string getStreamTag () const
virtual const TPersistDeclaration * getDeclaration () const =0
virtual void onChange (const TParamChange &)=0
Additional Inherited Members
Public Types inherited from TFx
typedef TFx * CreateProc()
Public Types inherited from TSmartObject
typedef short ClassCode
Public Types inherited from TPersist
typedef TPersist * CreateProc()
Static Public Member Functions inherited from TRasterFx
static TRasterP applyAffine (TTile &tileOut, const TTile &tileIn, const TRenderSettings &info)
static int memorySize (const TRectD &rect, int bpp)
Static Public Member Functions inherited from TFx
static void listFxs (std::vector< TFxInfo > &fxInfos)
static TFxInfo getFxInfo (const std::string &fxIdentifier)
static TFx * create (std::string name)
Static Public Member Functions inherited from TSmartObject
static TINT32 getInstanceCount (ClassCode code)
Static Public Member Functions inherited from TPersist
static void declare (CreateProc *)
static TPersist * create (const std::string &name)
virtual void doCompute (TTile &tile, double frame, const TRenderSettings &settings)=0
virtual void doDryCompute (TRectD &rect, double frame, const TRenderSettings &info)
Detailed Description
Constructor & Destructor Documentation
TImageCombinationFx()
TImageCombinationFx::TImageCombinationFx ()
                                         : m_group("Source", 2) {
  addInputPort("Source1", new TRasterFxPort, 0);
  addInputPort("Source2", new TRasterFxPort, 0);
  setName(L"ImageCombinationFx");
}
~TImageCombinationFx()
virtual TImageCombinationFx::~TImageCombinationFx () inline virtual
{}
Member Function Documentation
canHandle()
bool TImageCombinationFx::canHandle (const TRenderSettings & info, double frame) inline override virtual
Implements TRasterFx.
{
    return true;
  }
compatibilityTranslatePort()
void TImageCombinationFx::compatibilityTranslatePort (int majorVersion, int minorVersion, std::string & portName) override virtual
Compatibility function - used to translate a port name from older Toonz versions into its current form.
Reimplemented from TFx.
{
  if (VersionNumber(major, minor) < VersionNumber(1, 20)) {
    if (portName == "Up")
      portName = "Source1";
    else if (portName == "Down")
      portName = "Source2";
  }
}
doCompute()
void TImageCombinationFx::doCompute (TTile & tile, double frame, const TRenderSettings & info) override virtual
Implements TRasterFx.
{
  int p, pCount = getInputPortCount();
  TRasterFxPort *port = 0;
  // Skip empty ports
  for (p = pCount - 1; p >= 0;
       --p)  // Reverse iteration - bottom ports have high indices
  {
    port = static_cast<TRasterFxPort *>(getInputPort(p));
    if (port && port->getFx()) break;
  }
  // If there is no input, clear and return
  if (p < 0) {
    tile.getRaster()
        ->clear();  // Probably not necessary unless externally invocation
    return;  // deliberately soiled tile - however, should be rare anyway.
  }
  // Calculate the tiles' geometries
  const TRect &tileRect(tile.getRaster()->getBounds());
  const TDimension &tileSize(tileRect.getSize());
  TRectD tileRectD(tile.m_pos, TDimensionD(tileSize.lx, tileSize.ly));
  // Render the first viable port directly on tile
  (*port)->compute(tile, frame,
                   info);  // Should we do it only if the bbox is not empty?
  // Then, render each subsequent port and process() it on top of tile
  bool canRestrict = !requiresFullRect();
  for (--p; p >= 0; --p) {
    port = static_cast<TRasterFxPort *>(getInputPort(p));
    if (!(port && port->getFx()))  // Skip empty ports
      continue;
    // Will allocate a new tile to calculate the input contribution - so, if
    // possible
    // we'll restrict allocation to the input port's bbox
    TRectD computeRect(tileRectD);
    if (canRestrict) {
      TRectD inBBox;
      (*port)->getBBox(frame, inBBox, info);
      computeRect *= inBBox;
      makeRectCoherent(
          computeRect,
          tile.m_pos);  // Make it coherent with tile's pixel geometry
    }
    // Calculate the input port and perform processing
    TDimension computeSize(tround(computeRect.getLx()),
                           tround(computeRect.getLy()));
    if ((computeSize.lx > 0) && (computeSize.ly > 0)) {
      TTile inTile;  // Observe its locality - not incidental
      (*port)->allocateAndCompute(inTile, computeRect.getP00(), computeSize,
                                  tile.getRaster(), frame, info);
      // Invoke process() to deal with the actual fx processing
      TRasterP up(inTile.getRaster()), down(tile.getRaster());
      if (canRestrict) {
        // Extract from tile the part corresponding to inTile
        TRect downRect(convert(computeRect.getP00() - tile.m_pos), computeSize);
        down = down->extract(downRect);
      }
      assert(up->getSize() == down->getSize());
      process(up, down, frame);  // This is the point with the max concentration
                                 // of allocated resources
    }
  }
}
doDryCompute()
void TImageCombinationFx::doDryCompute (TRectD & rect, double frame, const TRenderSettings & info) override virtual
Declares the computation scheme of this fx for rendering optimization purposes. This is an important function of the Toonz rendering API, and should be reimplemented with the necessary care. The Toonz rendering process makes use of this function to enact most of the optimization steps about the fx computation, in particular fx caching. A correct implementation of this method should follow these rules: The invocation of child node computations should be faithfully reproduced. TRasterFx::compute and TRasterFx::allocateAndCompute calls have to be translated to TRasterFx::dryCompute calls. This fx is intended for precomputation stage, so the hard rendering code should be skipped here. By default, this method raises a dryCompute call to each input port in increasing order, using the TRasterFx::transform method to identify the tiles to be passed on input precomputation.
Reimplemented from TRasterFx.
{
  // Mere copy of doCompute(), stripped of the actual computations
  int p, pCount = getInputPortCount();
  TRasterFxPort *port = 0;
  for (p = pCount - 1; p >= 0; --p) {
    port = static_cast<TRasterFxPort *>(getInputPort(p));
    if (port && port->getFx()) break;
  }
  if (p < 0) return;
  (*port)->dryCompute(rect, frame, info);
  bool canRestrict = !requiresFullRect();
  for (--p; p >= 0; --p) {
    port = static_cast<TRasterFxPort *>(getInputPort(p));
    if (!(port && port->getFx())) continue;
    TRectD computeRect(rect);
    if (canRestrict) {
      TRectD inBBox;
      (*port)->getBBox(frame, inBBox, info);
      computeRect *= inBBox;
      makeRectCoherent(computeRect, rect.getP00());
    }
    TDimension computeSize(tround(computeRect.getLx()),
                           tround(computeRect.getLy()));
    if ((computeSize.lx > 0) && (computeSize.ly > 0))
      (*port)->dryCompute(computeRect, frame, info);
  }
}
References requiresFullRect().
doGetBBox()
bool TImageCombinationFx::doGetBBox (double frame, TRectD & bBox, const TRenderSettings & info) override virtual
Implements TRasterFx.
{
  bBox = TRectD();
  int p, pCount = getInputPortCount();
  for (p = 0; p != pCount; ++p) {
    TRasterFxPort *port = static_cast<TRasterFxPort *>(getInputPort(p));
    TRectD inputBBox;
    bool hasInput = (port && port->isConnected())
                        ? (*port)->doGetBBox(frame, inputBBox, info)
                        : false;
    if (hasInput) bBox += inputBBox;
  }
  return (bBox.getLx() >= 0) && (bBox.getLy() >= 0);
}
dynamicPortGroup()
const TFxPortDG * TImageCombinationFx::dynamicPortGroup (int g) const inline override virtual
Reimplemented from TFx.
{
    return (g == 0) ? &m_group : 0;
  }
dynamicPortGroupsCount()
int TImageCombinationFx::dynamicPortGroupsCount () const inline override virtual
Reimplemented from TFx.
{ return 1; }
getMemoryRequirement()
int TImageCombinationFx::getMemoryRequirement (const TRectD & rect, double frame, const TRenderSettings & info) inline override virtual
Specifies the approximate size (in MegaBytes) of the maximum allocation instance that this fx will need to perform in order to render the passed input. This method should be reimplemented in order to make the Toonz rendering process aware of the use of big raster memory chunks, at least. Observe that the passed tile geometry is implicitly already allocated <\i> for the fx output.
The default implementation returns 0, assuming that the passed implicit memory size is passed below in node computation without further allocation of resources. Fxs can reimplement this to -1 to explicitly disable the Toonz's smart memory handling.
Note
The rendering process ensures that the passed render settings are handled by the fx before this function is invoked - do not waste code for it.
See also
TRasterFx::memorySize and TRasterFx::canHandle methods.
Reimplemented from TRasterFx.
{
    // At max the memory of another tile with the same infos may be allocated
    // apart from
    // the externally supplied one.
    return TRasterFx::memorySize(rect, info.m_bpp);
  }
References TRasterFx::memorySize().
getPreferredInputPort()
int TImageCombinationFx::getPreferredInputPort () inline override virtual
Reimplemented from TFx.
{ return 1; }
process()
virtual void TImageCombinationFx::process (const TRasterP & up, const TRasterP & down, double frame) pure virtual
The raster processing function that must be reimplemented to perform the fx
Implemented in OverFx, AddFx, ColorDodgeFx, ColorBurnFx, ScreenFx, SubFx, MultFx, MinFx, MaxFx, LinearBurnFx, OverlayFx, and BlendFx.
requiresFullRect()
virtual bool TImageCombinationFx::requiresFullRect () inline virtual
Whether the 'up' rasters of process() invocations must be allocated to entirely cover the 'down' counterpart. Should be enabled if the process() function affects 'down' pixels when the 'up's are fully transparent.
Reimplemented in ScreenFx, MultFx, MinFx, and BlendFx.
{ return false; }
Referenced by doDryCompute().
The documentation for this class was generated from the following file:
E:/opentoonz/toonz/sources/common/tfx/binaryFx.cpp