opentoonz: Vectorizer Class Reference
Vectorizer Class Reference final
The thread encapsulating a core vectorization process.
#include <vectorizerpopup.h>
Public Slots
void cancel ()
Signals
void frameName (QString)
void frameDone (int)
void partialDone (int, int)
Forwards the VectorizerCore::partialDone(int,int) signal.
void transmitCancel ()
Transmits a user cancel downward to VectorizerCore.
void configurationChanged ()
Public Member Functions
TXshSimpleLevel * getVectorizedLevel () const
void setLevel (const TXshSimpleLevelP &level)
void setParameters (const VectorizerParameters &params)
Stores vectorizer parameters.
void setFids (const std::vector< TFrameId > &fids)
Stores the frame ids to be processed.
bool isCanceled ()
Tells whether vectorization was canceled.
Protected Member Functions
void run () override
Detailed Description
The thread encapsulating a core vectorization process.
The Vectorizer class serves as a medium between Xsheets and the low-level vectorization methods: each frame of the input level is processed by VectorizerCore methods and the output is then stored on free xsheet cells.
      Signals are also excanghed through this class, ensuring basic
communications between the invoker (typically VectorizerPopup) and the VectorizerCore class.
Since vectorization is typically a complex and resource-consuming task, Vectorizer also inherits a QThread in order to avoid system freezes.
See also
The VectorizerPopup, VectorizerConfiguration and VectorizerCore classes.
Constructor & Destructor Documentation
Vectorizer()
Vectorizer::Vectorizer ()
    : m_dialog(new OverwriteDialog)
    , m_isCanceled(false)
    , m_dialogShown(false) {}
~Vectorizer()
Vectorizer::~Vectorizer ()
{
  // DO NOT REMOVE - DESTRUCTS INCOMPLETE TYPES IN THE HEADER FILE
}
Member Function Documentation
cancel
void Vectorizer::cancel () inline slot
{ m_isCanceled = true; }
frameName
void Vectorizer::frameName (QString) signal
Frame name is emitted at beginning of a frame vectorization to be displayed above the progress bar
getVectorizedLevel()
TXshSimpleLevel * Vectorizer::getVectorizedLevel () const inline
{ return m_vLevel.getPointer(); }
isCanceled()
bool Vectorizer::isCanceled () inline
Tells whether vectorization was canceled.
Referenced by VectorizerPopup::apply().
run()
void Vectorizer::run (void) override protected
Remember that each of the above set methods must be called before invoking run().
Starts the vectorization thread (see QThread documentation).
{ doVectorize(); }
setFids()
void Vectorizer::setFids (const std::vector< TFrameId > & fids) inline
Stores the frame ids to be processed.
  {
    m_fids = fids, std::sort(m_fids.begin(), m_fids.end());
  }
Referenced by VectorizerPopup::apply().
setLevel()
void Vectorizer::setLevel (const TXshSimpleLevelP & level)
Stores current level and creates a new vector level.
{
  m_level = level;
  // Creo il livello pli
  TXshSimpleLevel *sl = m_level.getPointer();
  if (!sl) return;
  int rowCount = sl->getFrameCount();
  if (rowCount <= 0 || sl->isEmpty()) return;
  TXshLevel *xl;
  ToonzScene *scene = TApp::instance()->getCurrentScene()->getScene();
  // Build the new level name
  std::wstring levelName = sl->getName() + L"v";
  {
    std::unique_ptr<NameBuilder> nameBuilder(
        NameBuilder::getBuilder(levelName));
    for (;;) {
      levelName = nameBuilder->getNext();
      if (scene->getLevelSet()->getLevel(levelName) == 0) break;
    }
  }
  TFilePath dstPath = sl->getPath().withName(levelName).withType("pli");
  dstPath           = scene->decodeFilePath(dstPath);
  bool overWrite = false;
  if (TSystem::doesExistFileOrLevel(dstPath)) {
    m_dialogShown = true;
    std::wstring name = m_dialog->execute(scene, dstPath, true);
    if (m_dialog->cancelPressed()) return;
    switch (m_dialog->getChoice()) {
    case OverwriteDialog::KEEP_OLD:
      xl = scene->getLevelSet()->getLevel(levelName);
      if (!xl) xl = scene->loadLevel(dstPath);
      m_vLevel = xl->getSimpleLevel();
      return;
    case OverwriteDialog::OVERWRITE:
      overWrite = true;
      break;
    default:
      levelName = name;
      break;
    }
  }
  xl = scene->createNewLevel(PLI_XSHLEVEL, levelName);
  TXshSimpleLevel *vl = xl->getSimpleLevel();
  assert(vl);
  if (overWrite) {
    vl->setPath(scene->codeFilePath(dstPath));
    vl->setName(levelName);
  }
  TPalette *palette = 0;
  if (sl->getType() == TZP_XSHLEVEL) {
    palette = sl->getPalette()->clone();
    replaceMyPaintBrushStyles(palette);
  } else
    palette = new TPalette;
  palette->setPaletteName(vl->getName());
  vl->setPalette(palette);
  m_vLevel = vl;
}
References TPalette::clone(), ToonzScene::codeFilePath(), ToonzScene::createNewLevel(), ToonzScene::decodeFilePath(), TApp::getCurrentScene(), TXshSimpleLevel::getFrameCount(), ToonzScene::getLevelSet(), TXshLevel::getName(), TXshSimpleLevel::getPalette(), TXshSimpleLevel::getPath(), TXshLevel::getSimpleLevel(), TXshLevel::getType(), TApp::instance(), ToonzScene::loadLevel(), TXshSimpleLevel::setPalette(), TFilePath::withName(), and TFilePath::withType().
Referenced by VectorizerPopup::apply().
setParameters()
void Vectorizer::setParameters (const VectorizerParameters & params) inline
Stores vectorizer parameters.
  {
    m_params = params;
  }
Referenced by VectorizerPopup::apply().
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/toonz/vectorizerpopup.h
E:/opentoonz/toonz/sources/toonz/vectorizerpopup.cpp