opentoonz: TStageObjectSpline Class Reference
TStageObjectSpline Class Reference final
The TStageObjectSpline class define stage object motion path.
#include <tstageobjectspline.h>
Public Member Functions
TStageObjectSpline * clone () const
const TStroke * getStroke () const
void setStroke (TStroke *stroke)
TPointD getDagNodePos () const
keeps ownership
void setDagNodePos (const TPointD &pos)
int getId () const
void setId (int id)
std::string getName () const
void setName (const std::string &name)
bool isOpened () const
void setIsOpened (bool value)
void loadData (TIStream &is) override
void saveData (TOStream &os) override
std::string getIconId ()
void addParam (TDoubleParam *param)
void removeParam (TDoubleParam *param)
Public Member Functions inherited from TSmartObject
TSmartObject (ClassCode classCode)
void addRef ()
void release ()
TINT32 getRefCount () const
Public Member Functions inherited from TPersist
virtual void loadData (TIStream &is)=0
virtual void saveData (TOStream &os)=0
std::string getStreamTag () const
virtual const TPersistDeclaration * getDeclaration () const =0
Additional Inherited Members
Public Types inherited from TSmartObject
typedef short ClassCode
Public Types inherited from TPersist
typedef TPersist * CreateProc()
Static Public Member Functions inherited from TSmartObject
static TINT32 getInstanceCount (ClassCode code)
Static Public Member Functions inherited from TPersist
static void declare (CreateProc *)
static TPersist * create (const std::string &name)
Detailed Description
The TStageObjectSpline class define stage object motion path.
Inherits TSmartObject and TPersist.
The motion path is defined by spline build as TStroke getStroke(), and node position getDagNodePos(); spline can be set using setStroke() while node position can be set using setDagNodePos().
It's possible to clone spline using clone().
Constructor & Destructor Documentation
TStageObjectSpline()
TStageObjectSpline::TStageObjectSpline ()
    : TSmartObject(m_classCode)
    , m_stroke(0)
    , m_dagNodePos(TConst::nowhere)
    , m_id(-1)
    , m_idBase(std::to_string(idBaseCode++))
    , m_name("")
    , m_isOpened(false) {
  double d = 30;
  std::vector<TThickPoint> points;
  points.push_back(TPointD(0, 0));
  points.push_back(TPointD(d, 0));
  points.push_back(TPointD(2.0 * d, 0));
  m_stroke = new TStroke(points);
}
~TStageObjectSpline()
TStageObjectSpline::~TStageObjectSpline ()
{
  delete m_stroke;
  for (int i = 0; i < (int)m_posPathParams.size(); i++)
    m_posPathParams[i]->release();
  m_posPathParams.clear();
}
Member Function Documentation
addParam()
void TStageObjectSpline::addParam (TDoubleParam * param)
add the PosPath param if you want to update keyframes values when the stroke changes. addParam() calls param->addRef()
{
  for (int i = 0; i < (int)m_posPathParams.size(); i++)
    if (param == m_posPathParams[i]) return;
  m_posPathParams.push_back(param);
  param->addRef();
}
Referenced by TStageObject::assignParams(), TStageObject::doSetSpline(), and TStageObject::setStatus().
clone()
TStageObjectSpline * TStageObjectSpline::clone () const
{
  TStageObjectSpline *clonedSpline = new TStageObjectSpline();
  clonedSpline->m_id               = m_id;
  clonedSpline->m_name             = m_name;
  clonedSpline->m_stroke           = new TStroke(*m_stroke);
  for (int i = 0; i < (int)m_posPathParams.size(); i++)
    clonedSpline->m_posPathParams.push_back(
        (TDoubleParam *)m_posPathParams[i]->clone());
  return clonedSpline;
}
getDagNodePos()
TPointD TStageObjectSpline::getDagNodePos () const inline
keeps ownership
{ return m_dagNodePos; }
getIconId()
std::string TStageObjectSpline::getIconId ()
{ return "spline" + m_idBase; }
getId()
int TStageObjectSpline::getId () const
{ return m_id; }
getName()
std::string TStageObjectSpline::getName () const
{
  if (m_name == "") return "Path" + std::to_string(m_id + 1);
  return m_name;
}
getStroke()
const TStroke * TStageObjectSpline::getStroke () const
Return spline stroke.
See also
setStroke()
{ return m_stroke; }
Referenced by TColumnDataElement::restoreColumn(), and saveData().
isOpened()
bool TStageObjectSpline::isOpened () const inline
{ return m_isOpened; }
loadData()
void TStageObjectSpline::loadData (TIStream & is) override virtual
 This is a pure virtual function and must be overridden with a method
that implements the object loading from a stream (i.e take the object's features from a formatted data stream). For example the TStageObject class use his implementation to take the values of the parameters that characterizes a stage object as name, coordinates, etc... from a file. is is an input file stream
Implements TPersist.
{
  std::vector<TThickPoint> points;
  VersionNumber tnzVersion = is.getVersion();
  if (tnzVersion < VersionNumber(1, 16)) {
    while (!is.eos()) {
      TThickPoint p;
      is >> p.x >> p.y >> p.thick;
      points.push_back(p);
    }
  } else {
    std::string tagName;
    while (is.matchTag(tagName)) {
      if (tagName == "splineId")
        is >> m_id;
      else if (tagName == "name")
        is >> m_name;
      else if (tagName == "pos")
        is >> m_dagNodePos.x >> m_dagNodePos.y;
      else if (tagName == "isOpened") {
        int v = 0;
        is >> v;
        m_isOpened = (bool)v;
      } else if (tagName == "stroke") {
        int i, n = 0;
        is >> n;
        for (i = 0; i < n; i++) {
          TThickPoint p;
          is >> p.x >> p.y >> p.thick;
          points.push_back(p);
        }
      }
      is.matchEndTag();
    }
  }
  delete m_stroke;
  m_stroke = new TStroke(points);
}
References TIStream::eos(), TIStream::getVersion(), TIStream::matchEndTag(), and TIStream::matchTag().
removeParam()
void TStageObjectSpline::removeParam (TDoubleParam * param)
{
  std::vector<TDoubleParam *>::iterator it =
      std::find(m_posPathParams.begin(), m_posPathParams.end(), param);
  if (it == m_posPathParams.end()) return;
  (*it)->release();
  m_posPathParams.erase(it);
}
saveData()
void TStageObjectSpline::saveData (TOStream & os) override virtual
 This is a pure virtual function and must be overridden with a method
that implements the object saving to a data stream (i.e put the object's features on a formatted data stream). For example the TStageObject class use his implementation to save the values of the parameters that characterizes a stage object as name, coordinates, etc... on a file os is an output file stream.
Implements TPersist.
{
  const TStroke *stroke = getStroke();
  os.child("splineId") << (int)m_id;
  if (!m_name.empty()) os.child("name") << m_name;
  os.child("isOpened") << (int)m_isOpened;
  os.child("pos") << m_dagNodePos.x << m_dagNodePos.y;
  os.openChild("stroke");
  int n = stroke->getControlPointCount();
  os << n;
  for (int i = 0; i < n; i++) {
    TThickPoint p = stroke->getControlPoint(i);
    os << p.x << p.y << p.thick;
  }
  os.closeChild();
}
References TOStream::child(), TOStream::closeChild(), TStroke::getControlPoint(), TStroke::getControlPointCount(), getStroke(), and TOStream::openChild().
setDagNodePos()
void TStageObjectSpline::setDagNodePos (const TPointD & pos) inline
{ m_dagNodePos = pos; }
setId()
void TStageObjectSpline::setId (int id)
{ m_id = id; }
setIsOpened()
void TStageObjectSpline::setIsOpened (bool value) inline
{ m_isOpened = value; }
setName()
void TStageObjectSpline::setName (const std::string & name) inline
{ m_name = name; }
setStroke()
void TStageObjectSpline::setStroke (TStroke * stroke)
Set spline stroke to stroke.
See also
getStroke()
{
  if (stroke != m_stroke) {
    if (!m_posPathParams.empty() && stroke != 0 && m_stroke != 0)
      updatePosPathKeyframes(m_stroke, stroke);
    delete m_stroke;
    m_stroke = stroke;
  }
}
Referenced by TColumnDataElement::restoreColumn().
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/toonz/tstageobjectspline.h
E:/opentoonz/toonz/sources/toonzlib/tstageobjectspline.cpp