opentoonz: TCamera Class Reference
TCamera Class Reference
The TCamera class provides a camera and allows its management.
#include <tcamera.h>
Public Member Functions
TCamera ()
const TDimensionD & getSize () const
void setSize (const TDimensionD &size, bool preserveDpi=false, bool preserveAR=false)
double getAspectRatio () const
const TDimension & getRes () const
void setRes (const TDimension &res)
TPointD getDpi () const
bool isPixelSquared () const
TAffine getStageToCameraRef () const
TAffine getCameraToStageRef () const
TRectD getStageRect () const
void setInterestRect (const TRect &rect)
TRect getInterestRect () const
void setInterestStageRect (const TRectD &rect)
TRectD getInterestStageRect () const
void setXPrevalence (bool value)
bool isXPrevalence ()
void saveData (TOStream &os) const
void loadData (TIStream &is)
Detailed Description
The TCamera class provides a camera and allows its management.
A camera is specified by size, getSize() and resolution, getRes(). It can be changed using the setSize(), setRes() functions.tcamera
The class moreover gives methods to know camera Dpi getDpi(), camera aspect ratio getAspectRatio() and stage rect getStageRect().
Constructor & Destructor Documentation
TCamera()
TCamera::TCamera ()
Constructs TCamera with default value, size (12,9) and resolution (768,576). Constructs TCamera with default value, size (36, 20.25) and resolution (1920,1080).
05/31/16 Constructs TCamera with default value, size (16, 9) and resolution (1920,1080).
08/16/16
    : m_size(16, 9),
      m_res(1920, 1080),
      m_xPrevalence(true) {}
Member Function Documentation
getAspectRatio()
double TCamera::getAspectRatio () const
Return camera aspect ratio.
{ return m_size.lx / m_size.ly; }
Referenced by setSize().
getCameraToStageRef()
TAffine TCamera::getCameraToStageRef () const
Returns the reference change matrix from camera (resolution) reference to stage reference
{
  const double factor = Stage::inch;
  TDimensionD cameraSize = getSize();
  cameraSize.lx *= factor;
  cameraSize.ly *= factor;
  TPointD center(0.5 * cameraSize.lx, 0.5 * cameraSize.ly);
  return TAffine(factor * m_size.lx / (double)m_res.lx, 0, -center.x, 0,
                 factor * m_size.ly / (double)m_res.ly, -center.y);
}
References getSize(), and Stage::inch.
Referenced by getInterestStageRect().
getDpi()
TPointD TCamera::getDpi () const
Return camera Dpi.
{
  TPointD dpi;
  if (m_size.lx > 0 && m_size.ly > 0) {
    dpi.x = m_res.lx / m_size.lx;
    dpi.y = m_res.ly / m_size.ly;
  }
  return dpi;
}
Referenced by SceneViewer::getDpiFactor(), RenderCommand::multimediaRender(), RasterSelection::pasteSelection(), and setSize().
getInterestRect()
TRect TCamera::getInterestRect () const inline
Returns the camera's interest rect.
{ return m_interestRect; }
getInterestStageRect()
TRectD TCamera::getInterestStageRect () const
Returns the interest rect in stage coordinates.
{
  return getCameraToStageRef() * TRectD(m_interestRect.x0, m_interestRect.y0,
                                        m_interestRect.x1 + 1,
                                        m_interestRect.y1 + 1);
}
References getCameraToStageRef(), and TRectT< T >::x0.
getRes()
const TDimension & TCamera::getRes () const inline
Return camera resolution.
See also
setRes()
{ return m_res; }
Referenced by TSceneProperties::cloneCamerasTo(), CleanupSettingsModel::commitChanges(), IoCmd::exportLevel(), SceneViewer::getZoomScaleFittingWithScreen(), RenderCommand::multimediaRender(), ToonzScene::renderFrame(), and FxSettings::setFx().
getSize()
const TDimensionD & TCamera::getSize () const inline
Return camera size.
See also
setSize()
{ return m_size; }
Referenced by CleanupSettingsModel::commitChanges(), getCameraToStageRef(), getStageRect(), and ToonzScene::renderFrame().
getStageRect()
TRectD TCamera::getStageRect () const
Return stage rect.
{
  TDimensionD cameraSize = getSize();
  const double factor    = Stage::inch;
  cameraSize.lx *= factor;
  cameraSize.ly *= factor;
  TRectD rect(cameraSize);
  rect -= 0.5 * (rect.getP00() + rect.getP11());
  return rect;
}
References getSize(), and Stage::inch.
Referenced by EditTool::draw(), and CameraTestTool::draw().
getStageToCameraRef()
TAffine TCamera::getStageToCameraRef () const
Returns the reference change matrix from stage reference to camera (resolution) reference
{
  return TAffine(m_res.lx / (Stage::inch * m_size.lx), 0, 0.5 * m_res.lx, 0,
                 m_res.ly / (Stage::inch * m_size.ly), 0.5 * m_res.ly);
}
References Stage::inch.
Referenced by setInterestStageRect().
isPixelSquared()
bool TCamera::isPixelSquared () const
Return true if "resolution width per size height" is equal to "resolution height per size width".
{
  return areAlmostEqual(m_res.lx * m_size.ly, m_res.ly * m_size.lx);
}
isXPrevalence()
bool TCamera::isXPrevalence () inline
{ return m_xPrevalence; }
loadData()
void TCamera::loadData (TIStream & is)
{
  std::string tagName;
  while (is.matchTag(tagName)) {
    if (tagName == "cameraSize" || tagName == "size")
      is >> m_size.lx >> m_size.ly;
    else if (tagName == "cameraRes" || tagName == "res")
      is >> m_res.lx >> m_res.ly;
    else if (tagName == "cameraXPrevalence") {
      int xPrevalence;
      is >> xPrevalence;
      m_xPrevalence = (bool)xPrevalence;
    } else if (tagName == "interestRect") {
      is >> m_interestRect.x0 >> m_interestRect.y0 >> m_interestRect.x1 >>
          m_interestRect.y1;
    } else
      throw TException("TCamera::loadData. unexpected tag: " + tagName);
    is.matchEndTag();
  }
}
saveData()
void TCamera::saveData (TOStream & os) const
{
  os.child("cameraSize") << m_size.lx << m_size.ly;
  os.child("cameraRes") << m_res.lx << m_res.ly;
  os.child("cameraXPrevalence") << (int)m_xPrevalence;
  os.child("interestRect") << m_interestRect.x0 << m_interestRect.y0
                           << m_interestRect.x1 << m_interestRect.y1;
}
setInterestRect()
void TCamera::setInterestRect (const TRect & rect)
Sets the camera's interest rect. Typically used in preview modes.
{
  // Not using the TRect's common intersection. Unfortunately, in case
  // the rect's coordinates have lx or ly < 0, the intersection returns
  // the default (empty) rect. We want to maintain the coordinates instead.
  // m_interestRect = rect * TRect(m_res);
  m_interestRect.x0 = std::max(rect.x0, 0);
  m_interestRect.y0 = std::max(rect.y0, 0);
  m_interestRect.x1 = std::min(rect.x1, m_res.lx - 1);
  m_interestRect.y1 = std::min(rect.y1, m_res.ly - 1);
}
References TRectT< T >::x0.
Referenced by PreviewSubCameraManager::deleteSubCamera(), and setInterestStageRect().
setInterestStageRect()
void TCamera::setInterestStageRect (const TRectD & rect)
Sets the interest rect from stage coordinates
{
  TRectD cameraInterestRectD(getStageToCameraRef() * rect);
  setInterestRect(TRect(
      tfloor(cameraInterestRectD.x0), tfloor(cameraInterestRectD.y0),
      tceil(cameraInterestRectD.x1) - 1, tceil(cameraInterestRectD.y1) - 1));
}
References getStageToCameraRef(), setInterestRect(), and TRectT< T >::x0.
setRes()
void TCamera::setRes (const TDimension & res)
Set camera resolution to res.
See also
getRes()
{
  assert(res.lx > 0);
  assert(res.ly > 0);
  if (m_res != res) {
    m_res          = res;
    m_interestRect = TRect();
  }
}
Referenced by TSceneProperties::cloneCamerasTo(), and TSceneProperties::loadData().
setSize()
void TCamera::setSize (const TDimensionD & size, bool preserveDpi = false, bool preserveAR = false)
Set camera size to size.
See also
getSize()
{
  double currAR   = getAspectRatio();
  TPointD currDpi = getDpi();
  m_size.lx       = size.lx;
  if (preserveAR)
    m_size.ly = m_size.lx / currAR;  // WARNING! if also preserveDpi==true, the
                                     // AR could lose precision...
  else
    m_size.ly = size.ly;
  if (!preserveDpi) return;
  m_res.lx  = troundp(currDpi.x * m_size.lx);
  m_res.ly  = troundp(currDpi.y * m_size.ly);
  m_size.lx = m_res.lx / currDpi.x;
  if (preserveAR)  //&& currDpi.x==currDpi.y)
  {
    double aux = m_size.lx / currAR - m_res.ly / currDpi.y;
    m_size.ly  = m_size.lx / currAR;
  } else
    m_size.ly = m_res.ly / currDpi.y;
}
References getAspectRatio(), and getDpi().
Referenced by TSceneProperties::loadData().
setXPrevalence()
void TCamera::setXPrevalence (bool value) inline
{ m_xPrevalence = value; }
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/toonz/tcamera.h
E:/opentoonz/toonz/sources/toonzlib/tcamera.cpp