opentoonz: TLevelWriterTzl Class Reference
TLevelWriterTzl Class Reference final
Public Member Functions
TLevelWriterTzl (const TFilePath &path, TPropertyGroup *winfo)
void setPalette (TPalette *palette) override
void setOverwritePaletteFlag (bool overwrite) override
void renumberFids (const std::map< TFrameId, TFrameId > &renumberTable) override
Maps a list of existing level frames to a new list of frames.
void setIconSize (TDimension iconSize) override
TDimension getIconSize () const override
TImageWriterP getFrameWriter (TFrameId fid) override
void save (const TImageP &img)
void save (const TImageP &img, const TFrameId &fid)
void saveIcon (const TImageP &img, const TFrameId &fid)
bool checkIconSize (const TDimension &newSize)
Checks the icons size stored inside an already existing level file, and compares it with the specified newSize.
bool resizeIcons (const TDimension &newSize)
void remove (const TFrameId &fid)
float getFreeSpace ()
bool optimize ()
Public Member Functions inherited from TLevelWriter
TLevelWriter (const TFilePath &path, TPropertyGroup *winfo=0)
void setCreator (const QString &creator)
virtual void setPalette (TPalette *)
virtual void setOverwritePaletteFlag (bool overwrite)
virtual void renumberFids (const std::map< TFrameId, TFrameId > &table)
Maps a list of existing level frames to a new list of frames.
virtual void setIconSize (TDimension)
virtual TDimension getIconSize () const
virtual TImageWriterP getFrameWriter (TFrameId)
TImageWriterP getFrameWriter (int f)
TPropertyGroup * getProperties ()
void save (const TLevelP &level)
virtual void saveSoundTrack (TSoundTrack *st)
virtual void setFrameRate (double fps)
TFilePath getFilePath () const
const TContentHistory * getContentHistory () const
TContentHistory * getContentHistory ()
void setContentHistory (TContentHistory *contentHistory)
Public Member Functions inherited from TSmartObject
TSmartObject (ClassCode classCode)
void addRef ()
void release ()
TINT32 getRefCount () const
Static Public Member Functions
static TLevelWriter * create (const TFilePath &f, TPropertyGroup *winfo)
Static Public Member Functions inherited from TLevelWriter
static void getSupportedFormats (QStringList &names, bool onlyRenderFormats)
static void define (QString extension, TLevelWriterCreateProc *proc, bool isRenderFormat)
Static Public Member Functions inherited from TSmartObject
static TINT32 getInstanceCount (ClassCode code)
Additional Inherited Members
Public Types inherited from TSmartObject
typedef short ClassCode
Protected Attributes inherited from TLevelWriter
TFilePath m_path
double m_frameRate
TPropertyGroup * m_properties
TContentHistory * m_contentHistory
QString m_creator
Detailed Description
Constructor & Destructor Documentation
TLevelWriterTzl()
TLevelWriterTzl::TLevelWriterTzl (const TFilePath & path, TPropertyGroup * winfo)
    : TLevelWriter(path, info)
    , m_headerWritten(false)
    , m_creatorWritten(false)
    , m_chan(0)
    , m_frameCountPos(0)
    , m_frameCount(0)
    , m_palette(0)
    , m_res(0, 0)
    , m_exists(false)
    , m_version(currentVersion())
    , m_updatedIconsSize(false)
    , m_currentIconSize(0, 0)
    , m_iconSize(TDimension(80, 60))
    , m_userIconSize(TDimension(80, 60))
    , m_adjustRatio(false)
    , m_codec(new TRasterCodecLZO("LZO", true))
    , m_overwritePaletteFlag(true) {
  m_path        = path;
  m_palettePath = path.withNoFrame().withType("tpl");
  TFileStatus fs(path);
  m_magic     = (m_version == 14) ? "TLV14B1a" : "TLV15B1a";  // actual version
  erasedFrame = false;
  // version TLV10B1a: first version
  // version TLV11B1a: added frameIds
  // version TLV12B1a: incremental writings
  // version TLV13B1a: added thumbnails
  // version TLV14B1a: add creator string (fixed size = CREATOR_LENGTH char)
  // version TLV15B1a: support multiple suffixes
  if (fs.doesExist()) {
    // if (!fs.isWritable())
    m_chan = fopen(path, "rb+");
    /*--- 誰かが開いている、または権限が無いとき ---*/
    if (!m_chan) {
      throw TSystemException(path, "can't fopen.");
    }
    /*--- TLVファイルのヘッダが正しく読めなかった場合 ---*/
    if (!readHeaderAndOffsets(m_chan, m_frameOffsTable, m_iconOffsTable, m_res,
                              m_version, m_creator, &m_frameCount,
                              &m_offsetTablePos, &m_iconOffsetTablePos, 0)) {
      throw TSystemException(path, "can't readHeaderAndOffsets.");
    } else {
      if (m_version >= 12) buildFreeChunksTable();
      m_headerWritten = true;
      m_exists        = true;
      if (m_version >= 14)
        m_frameCountPos = 8 + CREATOR_LENGTH + 3 * sizeof(TINT32);
      else
        m_frameCountPos = 8 + 3 * sizeof(TINT32);
    }
  }
  if (!m_exists) {
    TFilePath parentDir = path.getParentDir();
    if (!TFileStatus(parentDir).doesExist()) {
      try {
        TSystem::mkDir(parentDir);
      } catch (...) {
        return;
      }
    }
    m_chan = fopen(path, "wb");
    if (!m_chan) return;
    if (!writeVersionAndCreator(m_chan, m_magic, m_creator)) return;
  }
}
~TLevelWriterTzl()
TLevelWriterTzl::~TLevelWriterTzl ()
{
  if (m_version < currentVersion()) {
    if (!convertToLatestVersion()) return;
    assert(m_version == currentVersion());
  }
  delete m_codec;
  TINT32 offsetMapPos     = 0;
  TINT32 iconOffsetMapPos = 0;
  if (!m_chan) return;
  assert(m_frameCount == (int)m_frameOffsTable.size());
  assert(m_frameCount == (int)m_iconOffsTable.size());
  offsetMapPos = (m_exists ? m_offsetTablePos : ftell(m_chan));
  fseek(m_chan, offsetMapPos, SEEK_SET);
  TzlOffsetMap::iterator it = m_frameOffsTable.begin();
  for (; it != m_frameOffsTable.end(); ++it) {
    TFrameId fid      = it->first;
    TINT32 num        = fid.getNumber();
    QByteArray suffix = fid.getLetter().toUtf8();
    TINT32 offs       = it->second.m_offs;
    TINT32 length     = it->second.m_length;
    tfwrite(&num, 1, m_chan);
    if (m_version >= 15) {  // write the suffix length before data
      TINT32 suffixLength = suffix.size();
      tfwrite(&suffixLength, 1, m_chan);
      tfwrite(suffix.constData(), suffixLength, m_chan);
    } else  // write only the first byte
      tfwrite(suffix.constData(), 1, m_chan);
    tfwrite(&offs, 1, m_chan);
    tfwrite(&length, 1, m_chan);
  }
  // Write Icon Offset Table after frameOffsTable
  iconOffsetMapPos =
      ftell(m_chan);  //(m_exists?m_iconOffsetTablePos: ftell(m_chan));
  fseek(m_chan, iconOffsetMapPos, SEEK_SET);
  TzlOffsetMap::iterator iconIt = m_iconOffsTable.begin();
  for (; iconIt != m_iconOffsTable.end(); ++iconIt) {
    TFrameId fid           = iconIt->first;
    TINT32 num             = fid.getNumber();
    QByteArray suffix      = fid.getLetter().toUtf8();
    TINT32 thumbnailOffs   = iconIt->second.m_offs;
    TINT32 thumbnailLength = iconIt->second.m_length;
    tfwrite(&num, 1, m_chan);
    if (m_version >= 15) {  // write the suffix length before data
      TINT32 suffixLength = suffix.size();
      tfwrite(&suffixLength, 1, m_chan);
      tfwrite(suffix.constData(), suffixLength, m_chan);
    } else  // write only the first byte
      tfwrite(suffix.constData(), 1, m_chan);
    tfwrite(&thumbnailOffs, 1, m_chan);
    tfwrite(&thumbnailLength, 1, m_chan);
  }
  fseek(m_chan, m_frameCountPos, SEEK_SET);
  TINT32 frameCount = m_frameCount;
  tfwrite(&frameCount, 1, m_chan);
  tfwrite(&offsetMapPos, 1, m_chan);
  tfwrite(&iconOffsetMapPos, 1, m_chan);
  fclose(m_chan);
  m_chan = 0;
  if (m_palette && m_overwritePaletteFlag &&
      (m_palette->getDirtyFlag() ||
       !TSystem::doesExistFileOrLevel(m_palettePath))) {
    TOStream os(m_palettePath);
    os << m_palette;
    m_palette->release();
  }
  if (m_contentHistory) {
    TFilePath historyFp = m_path.withNoFrame().withType("hst");
    FILE *historyChan   = fopen(historyFp, "w");
    if (historyChan) {
      std::string historyData = m_contentHistory->serialize().toStdString();
      fwrite(&historyData[0], 1, historyData.length(), historyChan);
      fclose(historyChan);
    }
  }
  // Se lo spazio libero (cioè la somma di tutti i buchi che si sono creati tra
  // i frame)
  // è maggiore di una certa soglia oppure è stato rimosso almeno un frame
  // allora ottimizzo il file
  // (in pratica risalvo il file da capo senza buchi).
  if (getFreeSpace() > 0.3 || erasedFrame) optimize();
}
Member Function Documentation
checkIconSize()
bool TLevelWriterTzl::checkIconSize (const TDimension & newSize)
Checks the icons size stored inside an already existing level file, and compares it with the specified newSize.
Returns
Whether the specified newSize matches the icons size in the level file.
{
  assert(m_version >= 13);
  if (!m_exists || m_iconOffsTable.empty() || !m_chan || m_version < 13)
    return false;
  // Read the size of icons in the file
  TINT32 iconLx = 0, iconLy = 0;
  long currentPos =
      ftell(m_chan);  // Backup current reading position in the file
  TzlOffsetMap::iterator it = m_iconOffsTable.begin();
  long offs                 = it->second.m_offs;
  fseek(m_chan, offs, SEEK_SET);
  fread(&iconLx, sizeof(TINT32), 1, m_chan);
  fread(&iconLy, sizeof(TINT32), 1, m_chan);
  fseek(m_chan, currentPos,
        SEEK_SET);  // Reset to the original position in the file
  assert(iconLx > 0 && iconLy > 0);
  if (iconLx <= 0 || iconLy <= 0 || iconLx > m_res.lx || iconLy > m_res.ly)
    return false;
  m_currentIconSize = TDimension(
      iconLx, iconLy);  // This is not performed if the above pre-emptive
                        // bailout kicks in. BTW, m_currentIconSize
                        // is currently UNUSED! Should be cleaned up...
  // Compare newSize against read icon size in the file
  return (m_currentIconSize == newSize);
}
Referenced by setIconSize().
create()
static TLevelWriter * TLevelWriterTzl::create (const TFilePath & f, TPropertyGroup * winfo) inline static
{
    return new TLevelWriterTzl(f, winfo);
  }
getFrameWriter()
TImageWriterP TLevelWriterTzl::getFrameWriter (TFrameId fid) override virtual
Reimplemented from TLevelWriter.
{
  return new TImageWriterTzl(this, fid);
}
getFreeSpace()
float TLevelWriterTzl::getFreeSpace ()
  Da informazioni relativamente allo spazio libero presente su file.
  Ritorna un numero compreso tra 0 e 1: 0 nessuno spazio libero, 1
tutto lo spazio è libero.
{
  if (m_exists && m_version >= 13) {
    TINT32 freeSpace                = 0;
    std::set<TzlChunk>::iterator it = m_freeChunks.begin();
    for (; it != m_freeChunks.end(); ++it) freeSpace += it->m_length;
    TINT32 totalSpace = 0;
    if (m_version == 13)
      totalSpace = m_offsetTablePos - 6 * sizeof(TINT32) - 4 * sizeof(char) -
                   8 * sizeof(char);
    else if (m_version >= 14)
      totalSpace = m_offsetTablePos - 6 * sizeof(TINT32) - 4 * sizeof(char) -
                   8 * sizeof(char) - CREATOR_LENGTH * sizeof(char);
    assert(totalSpace > 0);
    return (float)freeSpace / totalSpace;
  }
  return 0;
}
getIconSize()
TDimension TLevelWriterTzl::getIconSize () const inline override virtual
Reimplemented from TLevelWriter.
{ return m_iconSize; }
optimize()
bool TLevelWriterTzl::optimize ()
Save the file without freeSpace. Salva tutti i frame in maniera continua, senza buchi. Return TRUE if successfully.
{
  TFileStatus fs(m_path);
  assert(fs.doesExist());
  std::string tempName = "~" + m_path.getName() + "tmp&.tlv";
  TFilePath tempPath =
      TSystem::getTempDir() + tempName;  // Path temporaneo del file ottimizzato
  if (TSystem::doesExistFileOrLevel(tempPath)) TSystem::deleteFile(tempPath);
  TLevelWriterP lw(tempPath);
  TLevelReaderP lr(m_path);
  lw->setIconSize(m_userIconSize);
  TLevelP level = lr->loadInfo();
  if (!level || level->getFrameCount() == 0) return false;
  TLevel::Iterator levelIt = level->begin();
  for (; levelIt != level->end(); ++levelIt) {
    TToonzImageP img = lr->getFrameReader(levelIt->first)->load();
    assert(img);
    lw->getFrameWriter(levelIt->first)->save(img);
  }
  lr = TLevelReaderP();
  lw = TLevelWriterP();
  // Se il file tempPath (ottimizzato) è stato creato
  // lo copio sostituendolo ad m_path
  if (TSystem::doesExistFileOrLevel(tempPath)) {
    assert(m_path != tempPath);
    if (TSystem::doesExistFileOrLevel(m_path))
      TSystem::deleteFile(m_path);  // Cancello il file non ottimizzato
    TSystem::copyFile(m_path, tempPath);
    TSystem::deleteFile(tempPath);
  } else
    return false;
  return true;
}
References TFilePath::getName().
remove()
void TLevelWriterTzl::remove (const TFrameId & fid)
{
  TzlOffsetMap::iterator it = m_frameOffsTable.find(fid);
  // se il fid non esiste non faccio nulla
  if (it == m_frameOffsTable.end()) return;
  // aggiungo spazio vuoto
  // m_freeChunks.insert(TzlChunk(it->second.m_offs, it->second.m_length));
  addFreeChunk(it->second.m_offs, it->second.m_length);
  // cancello l'immagine dalla tabella
  m_frameOffsTable.erase(it);
  if (m_iconOffsTable.size() > 0) {
    TzlOffsetMap::iterator iconIt = m_iconOffsTable.find(fid);
    // deve necessariamente esserci anche l'iconcina
    assert(iconIt != m_iconOffsTable.end());
    if (iconIt == m_iconOffsTable.end()) return;
    // aggiungo spazio vuoto
    // m_freeChunks.insert(TzlChunk(iconIt->second.m_offs,
    // iconIt->second.m_length));
    addFreeChunk(iconIt->second.m_offs, iconIt->second.m_length);
    // Cancello la relativa icona
    m_iconOffsTable.erase(iconIt);
    erasedFrame = true;
  }
}
renumberFids()
void TLevelWriterTzl::renumberFids (const std::map< TFrameId, TFrameId > & table) override virtual
Maps a list of existing level frames to a new list of frames.
This function allows an existing level to reorganize (or discard) its disk content. It is typically implemented by TLevelWriters that support random access writing <\I>, which can therefore write new frames on top of an existing level.
This function requires that frames present on disk and in the table be remapped, while frames on disk not in the table be deleted. Eventual frames present in the table but not on disk are ignored.
The default implementation provides renumbering for standard Toonz multi-file level types (levelName.####c.ext), and does nothing if the specified path is not compatible with the multi-file format.
Reimplemented from TLevelWriter.
{
  m_renumberTable = renumberTable;
  if (m_version < 13) return;
  if (m_frameOffsTable.empty() || !m_exists) return;
  // Rimozione dei frame non presenti nella prima colonna di renumberTable
  std::map<TFrameId, TzlChunk> frameOffsTableTemp;
  frameOffsTableTemp        = m_frameOffsTable;
  TzlOffsetMap::iterator it = frameOffsTableTemp.begin();
  while (it != frameOffsTableTemp.end()) {
    TFrameId fid                                     = it->first;
    std::map<TFrameId, TFrameId>::const_iterator it2 = renumberTable.find(fid);
    if (it2 == renumberTable.end()) remove(fid);
    it++;
  }
  std::map<TFrameId, TzlChunk> frameOffsTable, iconOffsTable;
  // Renumber Frame
  std::map<TFrameId, TFrameId>::const_iterator it3 = renumberTable.begin();
  while (it3 != renumberTable.end()) {
    TFrameId fidToRenumber        = it3->first;
    TzlOffsetMap::iterator it     = m_frameOffsTable.find(fidToRenumber);
    TzlOffsetMap::iterator iconIt = m_iconOffsTable.find(fidToRenumber);
    if (it != m_frameOffsTable.end()) frameOffsTable[it3->second] = it->second;
    if (m_iconOffsTable.size() > 0 && iconIt != m_iconOffsTable.end())
      iconOffsTable[it3->second] = iconIt->second;
    it3++;
  }
  m_frameOffsTable.clear();
  m_frameOffsTable = frameOffsTable;
  m_iconOffsTable.clear();
  m_iconOffsTable = iconOffsTable;
  m_frameCount    = m_frameOffsTable.size();
  // buildFreeChunksTable();
}
resizeIcons()
bool TLevelWriterTzl::resizeIcons (const TDimension & newSize)
{
  if (!m_exists) return false;
  if (m_iconOffsTable.empty()) return false;
  if (!m_chan) return false;
  assert(m_version >= 13);
  // faccio una copia di m_path per poi usarla per la resizeIcons()
  fclose(m_chan);
  m_chan = 0;
  TFileStatus fs(m_path);
  assert(fs.doesExist());
  if (!fs.doesExist()) return false;
  std::string tempName = "~" + m_path.getName() + "tmpIcon&.tlv";
  TFilePath tempPath   = TSystem::getTempDir() + tempName;
  if (TSystem::doesExistFileOrLevel(m_path)) {
    assert(m_path != tempPath);
    if (TSystem::doesExistFileOrLevel(tempPath)) TSystem::deleteFile(tempPath);
    TSystem::copyFile(tempPath, m_path);
  } else
    return false;
  m_chan = fopen(m_path, "rb+");
  assert(m_chan);
  assert(TSystem::doesExistFileOrLevel(tempPath));
  if (!TSystem::doesExistFileOrLevel(tempPath)) return false;
  TLevelReaderP lr(tempPath);
  TLevelP level = lr->loadInfo();
  /*
  if(m_currentIconSize.lx>newSize.lx && m_currentIconSize.ly>newSize.ly)
  {
          for(TLevel::Iterator it=level->begin(); it != level->end(); ++it)
          {
                  TImageReaderP ir = lr->getFrameReader(it->first);
                  // carico l'iconcina
            TImageP img = ir->loadIcon();
                  TImageP icon;
                  createIcon(img,icon);
                  saveIcon(icon,it->first);
          }
  }
  else
  {              */
  // leggo tutte le immagini da file e creo le iconcine da da zero
  for (TLevel::Iterator it = level->begin(); it != level->end(); ++it) {
    // carico l'iconcina
    TImageP img = lr->getFrameReader(it->first)->load();
    // creo e salvo
    TImageP icon;
    createIcon(img, icon);
    saveIcon(icon, it->first);
  }
  //}
  lr = TLevelReaderP();
  // delete m_tempPath
  if (TSystem::doesExistFileOrLevel(tempPath)) {
    TSystem::deleteFile(tempPath);
  }
  return true;
}
save() [1/2]
void TLevelWriterTzl::save (const TImageP & img)
{ doSave(img, TFrameId()); }
save() [2/2]
void TLevelWriterTzl::save (const TImageP & img, const TFrameId & fid)
{
  doSave(img, fid);
}
saveIcon()
void TLevelWriterTzl::saveIcon (const TImageP & img, const TFrameId & fid)
{
  // salvo su file come icona
  saveImage(img, fid, true);
}
setIconSize()
void TLevelWriterTzl::setIconSize (TDimension iconSize) override virtual
         Setta le dimensioni dell'iconcina nel file.
         ATTENZIONE: va necessariamente richiamata prima di
renumberFids()!
Reimplemented from TLevelWriter.
{
  assert(iconSize.lx > 0 && iconSize.ly > 0);
  m_iconSize     = TDimension(iconSize.lx, iconSize.ly);
  m_userIconSize = TDimension(
      iconSize.lx, iconSize.ly);  // Used in TLevelWriterTzl::optimize().
                                  // Observe that m_iconSize may change below.
  if (m_version >= 13 && m_exists) {
    // A supported level file already exists at the specified path
    // Check whether icons stored in the file already
    // have the required size
    if (!m_updatedIconsSize)  // m_updatedIconsSize tells whether
      m_updatedIconsSize =
          checkIconSize(m_iconSize);  // icon sizes in the file match m_iconSize
    if (!m_updatedIconsSize) {
      // Icons in the stored file mismatch with the
      // required size. They need to be resized.
      m_updatedIconsSize = resizeIcons(m_iconSize);
      assert(m_updatedIconsSize);
    }
  }
}
References checkIconSize().
setOverwritePaletteFlag()
void TLevelWriterTzl::setOverwritePaletteFlag (bool overwrite) inline override virtual
Reimplemented from TLevelWriter.
{
    m_overwritePaletteFlag = overwrite;
  }
setPalette()
void TLevelWriterTzl::setPalette (TPalette * palette) override virtual
Reimplemented from TLevelWriter.
{
  if (!m_palette) {
    m_palette = palette;
    m_palette->addRef();
  }
}
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/image/tzl/tiio_tzl.h
E:/opentoonz/toonz/sources/image/tzl/tiio_tzl.cpp