opentoonz: TXshLevelColumn Class Reference
TXshLevelColumn Class Reference final
#include <txshlevelcolumn.h>
Public Member Functions
bool isIconVisible ()
void setIconVisible (bool visible)
TXshLevelColumn ()
~TXshLevelColumn ()
TXshColumn::ColumnType getColumnType () const override
bool canSetCell (const TXshCell &cell) const override
TXshLevelColumn * getLevelColumn () override
TXshColumn * clone () const override
void loadData (TIStream &is) override
void saveData (TOStream &os) override
TLevelColumnFx * getLevelColumnFx () const
TFx * getFx () const override
bool setNumbers (int row, int rowCount, const TXshCell cells[])
Public Member Functions inherited from TXshCellColumn
TXshCellColumn ()
~TXshCellColumn ()
TXshCellColumn * getCellColumn () override
virtual bool canSetCell (const TXshCell &cell) const =0
int getRange (int &r0, int &r1) const override
virtual int getRowCount () const
bool isEmpty () const override
bool isCellEmpty (int row) const override
virtual const TXshCell & getCell (int row) const
virtual bool setCell (int row, const TXshCell &cell)
virtual void getCells (int row, int rowCount, TXshCell cells[])
virtual bool setCells (int row, int rowCount, const TXshCell cells[])
virtual void insertEmptyCells (int row, int rowCount=1)
virtual void removeCells (int row, int rowCount=1)
virtual void clearCells (int row, int rowCount=1)
int getMaxFrame () const override
virtual int getFirstRow () const
virtual void checkColumn () const
bool getLevelRange (int row, int &r0, int &r1) const override
void saveCellMarks (TOStream &os)
bool loadCellMarks (std::string tagName, TIStream &is)
void setCellMark (int frame, int id)
int getCellMark (int frame) const
QMap< int, int > getCellMarks () const
void clearCellMarks ()
Public Member Functions inherited from TXshColumn
TXshColumn ()
virtual ColumnType getColumnType () const =0
virtual TXshLevelColumn * getLevelColumn ()
virtual TXshSoundColumn * getSoundColumn ()
virtual TXshSoundTextColumn * getSoundTextColumn ()
virtual TXshCellColumn * getCellColumn ()
virtual TXshPaletteColumn * getPaletteColumn ()
virtual TXshZeraryFxColumn * getZeraryFxColumn ()
virtual TXshMeshColumn * getMeshColumn ()
virtual int getMaxFrame () const =0
virtual TXshColumn * clone () const =0
bool isCamstandVisible () const
void setCamstandVisible (bool on)
UCHAR getOpacity () const
void setOpacity (UCHAR val)
bool isPreviewVisible () const
void setPreviewVisible (bool on)
bool isLocked () const
void lock (bool on)
bool isMask () const
void setIsMask (bool on)
virtual bool isEmpty () const
virtual TRaster32P getIcon ()
virtual bool isCellEmpty (int row) const =0
virtual bool getLevelRange (int row, int &r0, int &r1) const =0
virtual int getRange (int &r0, int &r1) const
virtual void setXsheet (TXsheet *xsheet)
TXsheet * getXsheet () const
virtual TFx * getFx () const
virtual bool isRendered () const
virtual bool isControl () const
int getColorTag () const
void setColorTag (int colorTag)
FilterColor getFilterColorId () const
void setFilterColorId (FilterColor id)
TPixel32 getFilterColor ()
void resetColumnProperties ()
Public Member Functions inherited from TColumnHeader
int getIndex () const
int getPos () const
int getX0 () const
int getX1 () const
void getCoords (int &x0, int &x1) const
int getWidth () const
bool inColumnsSet () const
Public Member Functions inherited from TSmartObject
TSmartObject (ClassCode classCode)
void addRef ()
void release ()
TINT32 getRefCount () const
Public Member Functions inherited from TPersist
virtual void loadData (TIStream &is)=0
virtual void saveData (TOStream &os)=0
std::string getStreamTag () const
virtual const TPersistDeclaration * getDeclaration () const =0
Additional Inherited Members
Public Types inherited from TXshColumn
enum FilterColor {
FilterNone = 0 , FilterRed , FilterGreen , FilterBlue ,
FilterDarkYellow , FilterDarkCyan , FilterDarkMagenta , FilterAmount
}
enum ColumnType {
eLevelType = 0 , eSoundType , eSoundTextType , eZeraryFxType ,
ePaletteType , eMeshType
}
Public Types inherited from TSmartObject
typedef short ClassCode
Public Types inherited from TPersist
typedef TPersist * CreateProc()
Static Public Member Functions inherited from TXshColumn
static ColumnType toColumnType (int levelType)
Returns the column type used to store levels of the specified type.
static TXshColumn * createEmpty (int colType)
Creates an empty TXshColumn of the specified column type.
static QPair< QString, TPixel32 > getFilterInfo (FilterColor key)
static void initColorFilters ()
Static Public Member Functions inherited from TSmartObject
static TINT32 getInstanceCount (ClassCode code)
Static Public Member Functions inherited from TPersist
static void declare (CreateProc *)
static TPersist * create (const std::string &name)
Protected Types inherited from TXshColumn
enum {
eCamstandVisible = 0x1 , ePreviewVisible = 0x2 , eLocked = 0x8 , eMasked = 0x10 ,
eCamstandTransparent43 = 0x20
}
Protected Member Functions inherited from TXshColumn
void setStatusWord (int status)
int getStatusWord () const
Protected Attributes inherited from TXshCellColumn
std::vector< TXshCell > m_cells
int m_first
QMap< int, int > m_cellMarkIds
Protected Attributes inherited from TXshColumn
TRaster32P m_icon
Detailed Description
The TXshLevelColumn class provides a column of levels in xsheet and allows its management.
Inherits TXshCellColumn.
The class defines column of levels getLevelColumn(), more than TXshCellColumn has a pointer to TLevelColumnFx getLevelColumnFx() and a string to identify icon. The string is an icon identification helpful to level icon management, getIcon() updateIcon().
Constructor & Destructor Documentation
TXshLevelColumn()
TXshLevelColumn::TXshLevelColumn ()
Constructs a TXshLevelColumn with default value.
    : m_fx(new TLevelColumnFx())
    //, m_iconId("")
    , m_iconVisible(false) {
  // updateIcon();
  m_fx->addRef();
  m_fx->setColumn(this);
}
Referenced by clone().
~TXshLevelColumn()
TXshLevelColumn::~TXshLevelColumn ()
Destroys the TXshLevelColumn object.
{
  m_fx->setColumn(0);
  m_fx->release();
  m_fx = 0;
}
Member Function Documentation
canSetCell()
bool TXshLevelColumn::canSetCell (const TXshCell & cell) const override virtual
Return true if cell is empty or level of cell isn't a TXshZeraryFxLevel.
Implements TXshCellColumn.
{
  if (cell.isEmpty()) return true;
  TXshSimpleLevel *sl = cell.getSimpleLevel();
  if (sl) return (sl->getType() & LEVELCOLUMN_XSHLEVEL);
  return cell.getChildLevel();
}
References TXshCell::getChildLevel(), TXshCell::getSimpleLevel(), TXshLevel::getType(), and TXshCell::isEmpty().
clone()
TXshColumn * TXshLevelColumn::clone () const override virtual
Clone column and return a pointer to the new TXshColumn cloned.
Implements TXshColumn.
{
  TXshLevelColumn *column = new TXshLevelColumn;
  column->setStatusWord(getStatusWord());
  column->setOpacity(getOpacity());
  column->m_cells = m_cells;
  column->m_first = m_first;
  column->setColorTag(getColorTag());
  column->setFilterColorId(getFilterColorId());
  // column->updateIcon();
  return column;
}
References TXshColumn::getColorTag(), TXshColumn::getOpacity(), TXshColumn::getStatusWord(), and TXshLevelColumn().
getColumnType()
TXshColumn::ColumnType TXshLevelColumn::getColumnType () const override virtual
Implements TXshColumn.
{
  return eLevelType;
}
getFx()
TFx * TXshLevelColumn::getFx () const override virtual
Return TFx.
Reimplemented from TXshColumn.
{ return m_fx; }
getLevelColumn()
TXshLevelColumn * TXshLevelColumn::getLevelColumn () inline override virtual
Return TXshLevelColumn.
Reimplemented from TXshColumn.
{ return this; }
getLevelColumnFx()
TLevelColumnFx * TXshLevelColumn::getLevelColumnFx () const
Return a pointer to TLevelColumnFx m_fx.
{ return m_fx; }
isIconVisible()
bool TXshLevelColumn::isIconVisible () inline
{ return m_iconVisible; }
loadData()
void TXshLevelColumn::loadData (TIStream & is) override virtual
 This is a pure virtual function and must be overridden with a method
that implements the object loading from a stream (i.e take the object's features from a formatted data stream). For example the TStageObject class use his implementation to take the values of the parameters that characterizes a stage object as name, coordinates, etc... from a file. is is an input file stream
Implements TPersist.
{
  std::string tagName;
  while (is.openChild(tagName)) {
    if (tagName == "status") {
      int status;
      is >> status;
      setStatusWord(status);
      if (status & eCamstandTransparent43) {
        setOpacity(128);
        status = status & ~eCamstandTransparent43;
      }
    } else if (tagName == "camerastand_opacity") {
      int opacity;
      is >> opacity;
      setOpacity((UCHAR)opacity);
    } else if (tagName == "filter_color_id") {
      int id;
      is >> id;
      setFilterColorId((TXshColumn::FilterColor)id);
    } else if (tagName == "cells") {
      while (is.openChild(tagName)) {
        if (tagName == "cell") {
          TPersist *p = 0;
          std::string str;
          int row = 1, rowCount = 1, increment = 0;
          TFilePath path;
          is >> row >> rowCount >> p >> str >> increment;
          TFrameId fid = qstringToFrameId(QString::fromStdString(str));
          assert((fid.getLetter().isEmpty() && rowCount >= 0) ||
                 (!fid.getLetter().isEmpty() && rowCount == 1));
          TXshLevel *xshLevel = dynamic_cast<TXshLevel *>(p);
          if (xshLevel) {
            int fidNumber = fid.getNumber();
            for (int i = 0; i < rowCount; i++) {
              TXshCell cell(xshLevel, fid);
              setCell(row++, cell);
              // rowCount>1 => fid has not letter.
              fidNumber += increment;
              fid = TFrameId(fidNumber);
            }
          }
        } else
          throw TException("TXshLevelColumn, unknown tag(2): " + tagName);
        is.closeChild();
      }
    } else if (tagName == "fx") {
      TPersist *p = 0;
      is >> p;
      if (TLevelColumnFx *lcf = dynamic_cast<TLevelColumnFx *>(p)) {
        lcf->addRef();
        if (m_fx) m_fx->release();
        m_fx = lcf;
        lcf->setColumn(this);
      }
    } else if (tagName == "fxnodes")  // per compatibilita' con 1.x e precedenti
    {
      TFxSet fxSet;
      fxSet.loadData(is);
    } else if (loadCellMarks(tagName, is)) {
      // do nothing
    } else
      throw TException("TXshLevelColumn, unknown tag: " + tagName);
    is.closeChild();
  }
}
References TIStream::closeChild(), TIStream::openChild(), TXshCellColumn::setCell(), TXshColumn::setOpacity(), and TXshColumn::setStatusWord().
saveData()
void TXshLevelColumn::saveData (TOStream & os) override virtual
 This is a pure virtual function and must be overridden with a method
that implements the object saving to a data stream (i.e put the object's features on a formatted data stream). For example the TStageObject class use his implementation to save the values of the parameters that characterizes a stage object as name, coordinates, etc... on a file os is an output file stream.
Implements TPersist.
{
  os.child("status") << getStatusWord();
  if (getOpacity() < 255) os.child("camerastand_opacity") << (int)getOpacity();
  if (getFilterColorId() != 0)
    os.child("filter_color_id") << (int)getFilterColorId();
  int r0, r1;
  if (getRange(r0, r1)) {
    os.openChild("cells");
    for (int r = r0; r <= r1; r++) {
      TXshCell cell = getCell(r);
      if (cell.isEmpty()) continue;
      TFrameId fid = cell.m_frameId;
      int n = 1, inc = 0, dr = fid.getNumber();
      // If fid has not letter save more than one cell and its incrementation;
      // otherwise save one cell.
      if (r < r1 && fid.getLetter().isEmpty()) {
        TXshCell cell2 = getCell(r + 1);
        TFrameId fid2  = cell2.m_frameId;
        if (cell2.m_level.getPointer() == cell.m_level.getPointer() &&
            fid2.getLetter().isEmpty()) {
          inc = cell2.m_frameId.getNumber() - dr;
          n++;
          for (;;) {
            if (r + n > r1) break;
            cell2         = getCell(r + n);
            TFrameId fid2 = cell2.m_frameId;
            if (cell2.m_level.getPointer() != cell.m_level.getPointer() ||
                !fid2.getLetter().isEmpty())
              break;
            if (fid2.getNumber() != dr + n * inc) break;
            n++;
          }
        }
      }
      os.child("cell") << r << n << cell.m_level.getPointer() << fid.expand()
                       << inc;
      r += n - 1;
    }
    os.closeChild();
  }
  os.child("fx") << m_fx;
  // cell marks
  saveCellMarks(os);
}
References TOStream::child(), TOStream::closeChild(), TXshCellColumn::getCell(), TXshColumn::getOpacity(), TXshCellColumn::getRange(), TXshColumn::getStatusWord(), TXshCell::isEmpty(), and TOStream::openChild().
setIconVisible()
void TXshLevelColumn::setIconVisible (bool visible) inline
{ m_iconVisible = visible; }
setNumbers()
bool TXshLevelColumn::setNumbers (int row, int rowCount, const TXshCell cells[])
{
  if (m_cells.empty()) return false;
  // Check availability.
  // - if source cells are all empty, do nothing
  // - also, if source or target cells contain NO_FRAME, do nothing
  bool isSrcAllEmpty = true;
  for (int i = 0; i < rowCount; i++) {
    // checking target cells
    int currentTgtIndex = row + i - m_first;
    if (currentTgtIndex < m_cells.size()) {
      TXshCell tgtCell = m_cells[currentTgtIndex];
      if (!tgtCell.isEmpty() && tgtCell.m_frameId == TFrameId::NO_FRAME)
        return false;
    }
    // checking source cells
    TXshCell srcCell = cells[i];
    if (!srcCell.isEmpty()) {
      if (srcCell.m_frameId == TFrameId::NO_FRAME) return false;
      isSrcAllEmpty = false;
    }
  }
  if (isSrcAllEmpty) return false;
  // Find a level to input.
  // If the first target cell is empty, search the upper cells, and lower cells
  // and use a level of firsty-found occupied neighbor cell.
  TXshLevelP currentLevel;
  int tmpIndex = std::min(row - m_first, (int)m_cells.size() - 1);
  // search upper cells
  while (tmpIndex >= 0) {
    TXshCell tmpCell = m_cells[tmpIndex];
    if (!tmpCell.isEmpty() && tmpCell.m_frameId != TFrameId::NO_FRAME) {
      currentLevel = tmpCell.m_level;
      break;
    }
    tmpIndex--;
  }
  // if not found any level in upper cells, then search the lower cells
  if (!currentLevel) {
    tmpIndex = std::max(row - m_first, 0);
    while (tmpIndex < (int)m_cells.size()) {
      TXshCell tmpCell = m_cells[tmpIndex];
      if (!tmpCell.isEmpty() && tmpCell.m_frameId != TFrameId::NO_FRAME) {
        currentLevel = tmpCell.m_level;
        break;
      }
      tmpIndex++;
    }
    // in the case any level for input could not be found
    if (!currentLevel) return false;
  }
  // Resize the cell container
  int ra   = row;
  int rb   = row + rowCount - 1;
  int c_rb = m_first + m_cells.size() - 1;
  if (row > c_rb) {
    int newCellCount = row - m_first + rowCount;
    m_cells.resize(newCellCount);
  } else if (row < m_first) {
    int delta = m_first - row;
    m_cells.insert(m_cells.begin(), delta, TXshCell());
    m_first = row;
  }
  if (rb > c_rb) {
    for (int i = 0; i < rb - c_rb; ++i) m_cells.push_back(TXshCell());
  }
  // Paste numbers.
  for (int i = 0; i < rowCount; i++) {
    int dstIndex     = row - m_first + i;
    TXshCell dstCell = m_cells[dstIndex];
    TXshCell srcCell = cells[i];
    if (srcCell.isEmpty()) {
      m_cells[dstIndex] = TXshCell();
    } else {
      if (!dstCell.isEmpty()) currentLevel = dstCell.m_level;
      m_cells[dstIndex] = TXshCell(currentLevel, srcCell.m_frameId);
    }
  }
  // Update the cell container.
  while (!m_cells.empty() && m_cells.back().isEmpty()) {
    m_cells.pop_back();
  }
  while (!m_cells.empty() && m_cells.front().isEmpty()) {
    m_cells.erase(m_cells.begin());
    m_first++;
  }
  if (m_cells.empty()) {
    m_first = 0;
  }
  return true;
}
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/toonz/txshlevelcolumn.h
E:/opentoonz/toonz/sources/toonzlib/txshlevelcolumn.cpp