opentoonz: DockLayout Class Reference
DockLayout Class Reference final
#include <docklayout.h>
Public Types
typedef std::pair< std::vector< QRect >, QString > State
Public Member Functions
int count (void) const override
void addItem (QLayoutItem *item) override
QSize sizeHint () const override
QSize minimumSize () const override
QSize maximumSize () const override
QLayoutItem * itemAt (int) const override
QWidget * widgetAt (int) const
QLayoutItem * takeAt (int) override
void setGeometry (const QRect &rect) override
NOTE: This method is currently unused by DockLayout implementation...
void update ()
void redistribute ()
void applyTransform (const QTransform &transform)
DockWidget * getMaximized ()
void setMaximized (DockWidget *item, bool state=true)
Region * dockItem (DockWidget *item, Region *r=0, int idx=0)
void dockItem (DockWidget *item, DockPlaceholder *place)
NOTE: Docked items are forcedly shown.
void dockItem (DockWidget *item, DockWidget *target, int regionSide)
bool undockItem (DockWidget *item)
Undocks item and updates geometry.
void calculateDockPlaceholders (DockWidget *item)
Region * rootRegion () const
const std::deque< Region * > & regions () const
Region * region (int i) const
Region * find (DockWidget *item) const
QWidget * containerOf (QPoint point) const
State saveState ()
bool restoreState (const State &state)
Restores the given internal structure of the layout.
void setDecoAllocator (DockDecoAllocator *decoAllocator)
NOTE: DockLayout takes ownership of the allocator.
Detailed Description
DockLayout inherits the abstract QLayout to provide a docking system for widgets.
IMPORTANT NOTE: Observe that the addWidget() method expects only widgets of type DockWidget, so any other widget type added to this kind of Layout will cause a run-time error.
See also
DockWidget and DockSeparator classes.
Member Typedef Documentation
State
typedef std::pair<std::vector<QRect>, QString> DockLayout::State
Constructor & Destructor Documentation
DockLayout()
DockLayout::DockLayout ()
    : m_maximizedDock(0), m_decoAllocator(new DockDecoAllocator()) {}
~DockLayout()
DockLayout::~DockLayout () virtual
{
  // Deleting Regions (separators are Widgets with parent, so they are
  // recursively deleted)
  unsigned int i;
  for (i = 0; i < m_regions.size(); ++i) delete m_regions[i];
  // Deleting dockWidgets
  for (i = 0; i < m_items.size(); ++i) {
    // delete m_items[i]->widget();
    delete m_items[i];
  }
  // Delete deco allocator
  delete m_decoAllocator;
}
Member Function Documentation
addItem()
void DockLayout::addItem (QLayoutItem * item) override
{
  DockWidget *addedItem = dynamic_cast<DockWidget *>(item->widget());
  // Ensure that added item is effectively a DockWidget type;
  assert(addedItem);
  // Check if item is already under layout's control. If so, quit.
  if (find(addedItem)) return;
  // Force reparentation. This is required in order to ensure that all items
  // possess
  // the same geometry() reference. Also store parentLayout for convenience.
  addedItem->m_parentLayout = this;
  addedItem->setParent(parentWidget());
  // Remember that reparenting a widget produces a window flags reset if the new
  // parent is not the current one (see Qt's manual). So, first reassign
  // standard
  // floating flags, then call for custom appearance (which may eventually
  // reassign the flags).
  addedItem->setWindowFlags(Qt::Tool | Qt::FramelessWindowHint);
  addedItem->setFloatingAppearance();
  m_items.push_back(item);
}
applyTransform()
void DockLayout::applyTransform (const QTransform & transform)
{
  unsigned int i;
  for (i = 0; i < m_regions.size(); ++i)
    m_regions[i]->setGeometry(transform.mapRect(m_regions[i]->getGeometry()));
}
calculateDockPlaceholders()
void DockLayout::calculateDockPlaceholders (DockWidget * item)
Calculates possible docking solutions for this dock widget. They are stored into the dock widget. NOTE: Placeholders are here calculated by decreasing importance; in other words, if two rects are part of the layout, and the first contains the second, placeholders of the first are found before those of the second. This fact may be exploited when selecting an appropriate placeholder for docking.
{
  assert(item);
  // If the DockLayout's owner widget is hidden, avoid
  if (!parentWidget()->isVisible()) return;
  if (!m_regions.size()) {
    if (isPossibleInsertion(item, 0, 0)) {
      // Then insert a root placeholder only
      item->m_placeholders.push_back(item->m_decoAllocator->newPlaceBuilt(
          item, 0, 0, DockPlaceholder::root));
      return;
    }
  }
  // For all regions (and for all insertion index), check if
  // insertion may succeed.
  // NOTE: Insertion chance is just the same for all indexes in a given
  // parent region...
  // First check parentRegion=0 (under a new Root - External cases)
  if (isPossibleInsertion(item, 0, 0)) {
    QRect contRect = contentsRect();
    if (m_regions.front()->getOrientation() == Region::horizontal) {
      item->m_placeholders.push_back(item->m_decoAllocator->newPlaceBuilt(
          item, 0, 0, DockPlaceholder::top));
      item->m_placeholders.push_back(item->m_decoAllocator->newPlaceBuilt(
          item, 0, 1, DockPlaceholder::bottom));
    } else {
      item->m_placeholders.push_back(item->m_decoAllocator->newPlaceBuilt(
          item, 0, 0, DockPlaceholder::left));
      item->m_placeholders.push_back(item->m_decoAllocator->newPlaceBuilt(
          item, 0, 1, DockPlaceholder::right));
    }
  }
  unsigned int i;
  for (i = 0; i < m_regions.size(); ++i) {
    Region *r = m_regions[i];
    r->m_placeholders.clear();
    if (isPossibleInsertion(item, r, 0)) {
      unsigned int j;
      QRect cellRect;
      // For all indices, insert a placeholder
      if (r->getOrientation() == Region::horizontal) {
        // Left side
        item->m_placeholders.push_back(item->m_decoAllocator->newPlaceBuilt(
            item, r, 0, DockPlaceholder::left));
        r->m_placeholders.push_back(item->m_placeholders.back());
        // Separators
        for (j = 1; j < r->getChildList().size(); ++j) {
          item->m_placeholders.push_back(item->m_decoAllocator->newPlaceBuilt(
              item, r, j, DockPlaceholder::sepVert));
          r->m_placeholders.push_back(item->m_placeholders.back());
        }
        // Right side
        item->m_placeholders.push_back(item->m_decoAllocator->newPlaceBuilt(
            item, r, j, DockPlaceholder::right));
        r->m_placeholders.push_back(item->m_placeholders.back());
      } else {
        // Top side
        item->m_placeholders.push_back(item->m_decoAllocator->newPlaceBuilt(
            item, r, 0, DockPlaceholder::top));
        r->m_placeholders.push_back(item->m_placeholders.back());
        for (j = 1; j < r->getChildList().size(); ++j) {
          item->m_placeholders.push_back(item->m_decoAllocator->newPlaceBuilt(
              item, r, j, DockPlaceholder::sepHor));
          r->m_placeholders.push_back(item->m_placeholders.back());
        }
        // Bottom side
        item->m_placeholders.push_back(item->m_decoAllocator->newPlaceBuilt(
            item, r, j, DockPlaceholder::bottom));
        r->m_placeholders.push_back(item->m_placeholders.back());
      }
    }
  }
  // Disable all placeholders
  // for(i=0; i<item->m_placeholders.size(); ++i)
  //  item->m_placeholders[i]->setDisabled(true);
}
containerOf()
QWidget * DockLayout::containerOf (QPoint point) const
{
  // Search among regions, from leaf regions to root.
  int i;
  unsigned int j;
  for (i = m_regions.size() - 1; i >= 0; --i) {
    Region *currRegion = m_regions[i];
    DockWidget *item   = currRegion->getItem();
    // First check if item contains it
    if (item && item->geometry().contains(point)) return currRegion->getItem();
    // Then, search among separators
    for (j = 0; j < currRegion->separators().size(); ++j)
      if (currRegion->separator(j)->geometry().contains(point))
        return currRegion->separator(j);
  }
  return 0;
}
count()
int DockLayout::count (void) const override
{ return m_items.size(); }
dockItem() [1/3]
void DockLayout::dockItem (DockWidget * item, DockPlaceholder * place)
NOTE: Docked items are forcedly shown.
Docks input item before position idx of region r. Deals with overall region hierarchy.
{
  place->hide();
  item->hide();
  dockItemPrivate(item, place->m_region, place->m_idx);
  redistribute();
  parentWidget()->repaint();
  item->setWindowFlags(Qt::SubWindow);
  item->show();
}
dockItem() [2/3]
void DockLayout::dockItem (DockWidget * item, DockWidget * target, int regionSide)
Docks input item at side regionside of target dock widget. RegionSide can be Region::left, right, top or bottom.
{
  Region *targetRegion = find(target);
  short var = regionSide >> 2 * (int)targetRegion->getOrientation();
  bool pos  = regionSide & 0xa;
  item->setWindowFlags(Qt::SubWindow);
  item->show();
  if (var & 0x3) {
    // Side is coherent with orientation => Direct insertion at position 0 or 1
    dockItemPrivate(item, targetRegion, pos);
  } else {
    // Side is not coherent - have to find target's index in parent region
    Region *parentRegion = targetRegion->getParent();
    unsigned int idx =
        parentRegion ? parentRegion->find(targetRegion) + pos : pos;
    dockItemPrivate(item, parentRegion, idx);
  }
}
dockItem() [3/3]
Region * DockLayout::dockItem (DockWidget * item, Region * r = 0, int idx = 0)
Docks input item into Region r, at position idx; returns region corresponding to newly inserted item. NOTE: Unlike dockItem(DockWidget*,DockPlaceholder*) and undockItem, this method is supposedly called directly into application code; therefore, no redistribution is done after a single dock - you are supposed to manually call redistribute() after all widgets have been docked.
{
  item->setWindowFlags(Qt::SubWindow);
  item->show();
  return dockItemPrivate(item, r, idx);
}
find()
Region * DockLayout::find (DockWidget * item) const
{
  unsigned int i;
  for (i = 0; i < m_regions.size(); ++i)
    if (m_regions[i]->getItem() == item) return m_regions[i];
  return 0;
}
getMaximized()
DockWidget * DockLayout::getMaximized () inline
{ return m_maximizedDock; }
itemAt()
QLayoutItem * DockLayout::itemAt (int idx) const override
{
  if (idx >= (int)m_items.size()) return 0;
  return m_items[idx];
}
maximumSize()
QSize DockLayout::maximumSize () const override
{
  if (!m_regions.empty()) {
    Region *r = m_regions.front();
    r->calculateExtremalSizes();
    return QSize(r->m_maximumSize[0], r->m_maximumSize[1]);
  }
  return QSize(QWIDGETSIZE_MAX, QWIDGETSIZE_MAX);
}
minimumSize()
QSize DockLayout::minimumSize () const override
{
  if (!m_regions.empty()) {
    Region *r = m_regions.front();
    r->calculateExtremalSizes();
    return QSize(r->m_minimumSize[0], r->m_minimumSize[1]);
  }
  return QSize(0, 0);
}
redistribute()
void DockLayout::redistribute ()
{
  if (!m_regions.empty()) {
    std::vector<QWidget *> widgets;
    // Recompute extremal region sizes
    // NOTA: Sarebbe da fare solo se un certo flag lo richiede; altrimenti tipo
    // per resize events e' inutile...
    // let's force the width of the film strip / style editor not to change
    // check recursively from the root region, if the widgets can be fixed.
    // it avoids all widgets in horizontal alignment to be fixed, or UI becomes
    // glitchy.
    bool fromDocking = false;
    bool widgetsCanBeFixedWidth =
        !m_regions.front()->checkWidgetsToBeFixedWidth(widgets, fromDocking);
    if (!fromDocking && widgetsCanBeFixedWidth) {
      for (QWidget *widget : widgets) widget->setFixedWidth(widget->width());
    }
    m_regions.front()->calculateExtremalSizes();
    int parentWidth  = contentsRect().width();
    int parentHeight = contentsRect().height();
    // Always check main window consistency before effective redistribution. DO
    // NOT ERASE or crashes may occur...
    if (m_regions.front()->getMinimumSize(Region::horizontal) > parentWidth ||
        m_regions.front()->getMinimumSize(Region::vertical) > parentHeight ||
        m_regions.front()->getMaximumSize(Region::horizontal) < parentWidth ||
        m_regions.front()->getMaximumSize(Region::vertical) < parentHeight)
      return;
    // Recompute Layout geometry
    m_regions.front()->setGeometry(contentsRect());
    m_regions.front()->redistribute();
    if (!fromDocking && widgetsCanBeFixedWidth) {
      for (QWidget *widget : widgets) {
        widget->setMaximumSize(QWIDGETSIZE_MAX, QWIDGETSIZE_MAX);
        widget->setMinimumSize(0, 0);
      }
    }
  }
  // Finally, apply Region geometries found
  applyGeometry();
}
region()
Region * DockLayout::region (int i) const inline
{ return m_regions[i]; }
regions()
const std::deque< Region * > & DockLayout::regions () const inline
{ return m_regions; }
restoreState()
bool DockLayout::restoreState (const State & state)
Restores the given internal structure of the layout.
This method is intended to restore the geometry of a set of items that was handled by the layout at the time the state was saved. Input are the geometries of the items involved and the dock hierarchy in form of a string. IMPORTANT NOTE: No check is performed on the item themselves, except for the consistency of their geometrical constraints inside the layout. Furthermore, this method does not ensure the identity of the items involved, assuming that the set of dock widget has ever been left unchanged or completely restored as it were when saved. In particular, their ordering must be preserved.
{
  QStringList vars = state.second.split(" ", QString::SkipEmptyParts);
  if (vars.size() < 1) return 0;
  // Check number of items
  unsigned int count = state.first.size();
  if (m_items.size() != count) return false;  // Items list is not coherent
  // Initialize new Regions hierarchy
  std::deque<Region *> newHierarchy;
  // Load it
  int maximizedItem = vars[0].toInt();
  if (vars.size() > 1) {
    // Scan hierarchy
    Region *r       = 0, *newRegion;
    int orientation = !vars[1].toInt();
    int i;
    for (i = 2; i < vars.size(); ++i) {
      if (vars[i] == "]") {
        // End region and get parent
        r = r->getParent();
      } else {
        // Allocate new Region
        newRegion = new Region(this);
        newHierarchy.push_back(newRegion);
        newRegion->m_orientation = !orientation;
        if (r) r->insertSubRegion(newRegion, r->getChildList().size());
        if (vars[i] == "[") {
          // Current region has children
          r = newRegion;
        } else {
          // newRegion has item
          newRegion->m_item =
              static_cast<DockWidget *>(m_items[vars[i].toInt()]->widget());
        }
      }
    }
    // Check if size constraints are satisfied
    newHierarchy[0]->calculateExtremalSizes();
  }
  unsigned int j;
  for (j = 0; j < newHierarchy.size(); ++j) {
    // Check if their extremal sizes are valid
    Region *r = newHierarchy[j];
    if (r->getMinimumSize(Region::horizontal) >
            r->getMaximumSize(Region::horizontal) ||
        r->getMinimumSize(Region::vertical) >
            r->getMaximumSize(Region::vertical)) {
      // If not, deallocate attempted hierarchy and quit
      for (j = 0; j < newHierarchy.size(); ++j) delete newHierarchy[j];
      return false;
    }
  }
  // Else, deallocate old regions and substitute with new ones
  for (j = 0; j < m_regions.size(); ++j) delete m_regions[j];
  m_regions = newHierarchy;
  // Now re-initialize dock widgets' infos.
  const std::vector<QRect> &geoms = state.first;
  DockWidget *item;
  for (j = 0; j < m_items.size(); ++j) {
    item = static_cast<DockWidget *>(m_items[j]->widget());
    item->setGeometry(geoms[j]);
    item->m_maximized = false;
    item->m_saveIndex = j;
  }
  // Docked widgets are found in hierarchy
  for (j = 0; j < m_regions.size(); ++j)
    if ((item = m_regions[j]->m_item)) {
      item->setWindowFlags(Qt::SubWindow);
      item->setDockedAppearance();
      item->m_floating  = false;
      item->m_saveIndex = -1;
      item->show();
    }
  // Recover available geometry infos
  // QRect availableRect= QApplication::desktop()->availableGeometry();
  int recoverX = 0, recoverY = 0;
  // Deal with floating panels
  for (j = 0; j < m_items.size(); ++j) {
    item = static_cast<DockWidget *>(m_items[j]->widget());
    if (item->m_saveIndex > 0) {
      // Ensure that floating panels are not placed in
      // unavailable positions
      if ((geoms[j] & QApplication::desktop()->availableGeometry(item))
              .isEmpty())
        item->move(recoverX += 50, recoverY += 50);
      // Set floating appearances
      item->setWindowFlags(Qt::Tool | Qt::FramelessWindowHint);
      item->setFloatingAppearance();
      item->m_floating = true;
    }
  }
  // Allocate region separators
  unsigned int k;
  for (j = 0; j < m_regions.size(); ++j) {
    Region *r = m_regions[j];
    for (k = 1; k < r->m_childList.size(); ++k) {
      r->insertSeparator(
          m_decoAllocator->newSeparator(this, r->getOrientation(), r));
    }
  }
  // Calculate regions' geometry starting from leaves (items)
  if (m_regions.size()) m_regions[0]->restoreGeometry();
  // Then, ensure the result is correctly fitting the contents rect
  // redistribute();
  // NOTE: The previous might be tempting to ensure all is right -
  // unfortunately, it may
  // be that the main window's content rect is not yet defined before it is
  // shown the first
  // time (like on MAC), and that is needed to redistribute. Se we force the
  // saved values
  //(assuming they are right)...
  applyGeometry();
  // Finally, set maximized dock widget
  if (maximizedItem != -1) {
    item = static_cast<DockWidget *>(m_items[maximizedItem]->widget());
    // Problema: Puo' essere, in fase di caricamento dati, che la contentsRect
    // del layout
    // venga sballata! (vv. lo ctor di TMainWindow) Allora, evitiamo il
    // controllo fatto
    // in setMazimized, e assumiamo sia per forza corretto...
    // setMaximized(item, true);
    m_maximizedDock   = item;
    item->m_maximized = true;
    item->raise();
    // Hide all other widgets
    QWidget *currWidget;
    for (int i = 0; i < this->count(); ++i)
      if ((currWidget = itemAt(i)->widget()) != item) currWidget->hide();
  }
  return true;
}
References DockDecoAllocator::newSeparator(), DockWidget::setDockedAppearance(), and DockWidget::setFloatingAppearance().
rootRegion()
Region * DockLayout::rootRegion () const inline
{
    return m_regions.size() ? m_regions.front() : 0;
  }
saveState()
DockLayout::State DockLayout::saveState ()
Returns the current State of the layout. A State is a typedef for a pair containing the (normal) geometries of all layout items, and a string indicating their hierarchycal structure.
{
  QString hierarchy;
  // Set save indices so we don't need to find anything
  unsigned int i;
  for (i = 0; i < m_regions.size(); ++i) m_regions[i]->m_saveIndex = i;
  DockWidget *item;
  for (i = 0; i < m_items.size(); ++i) {
    item              = static_cast<DockWidget *>(m_items[i]->widget());
    item->m_saveIndex = i;
  }
  // Write item geometries
  std::vector<QRect> geometries;
  for (i = 0; i < m_items.size(); ++i)
    geometries.push_back(m_items[i]->geometry());
  QTextStream stream(&hierarchy, QIODevice::WriteOnly);
  // Save maximimized Dock index and geometry
  stream << QString::number(m_maximizedDock ? m_maximizedDock->m_saveIndex : -1)
         << " ";
  if (m_maximizedDock) {
    Region *r                                = find(m_maximizedDock);
    geometries[m_maximizedDock->m_saveIndex] = toRect(r->getGeometry());
  }
  // Save regions
  Region *r = rootRegion();
  if (r) {
    stream << QString::number(r->getOrientation()) << " ";
    writeRegion(r, hierarchy);
  }
  return std::pair<std::vector<QRect>, QString>(geometries, hierarchy);
}
setDecoAllocator()
void DockLayout::setDecoAllocator (DockDecoAllocator * decoAllocator)
NOTE: DockLayout takes ownership of the allocator.
Sets current deco allocator to decoAllocator. A default deco allocator is already provided at construction.
{
  // Delete old one
  if (m_decoAllocator) delete m_decoAllocator;
  // Place new one
  m_decoAllocator = decoAllocator;
}
setGeometry()
void DockLayout::setGeometry (const QRect & rect) override
NOTE: This method is currently unused by DockLayout implementation...
{
  // Just pass the info to the widget (it's somehow necessary...)
  QLayout::setGeometry(rect);
}
setMaximized()
void DockLayout::setMaximized (DockWidget * item, bool state = true)
{
  if (item && state != item->m_maximized) {
    if (state) {
      // Maximize
      if (m_maximizedDock) {
        // If maximized already exists, normalize it
        Region *r = find(m_maximizedDock);
        m_maximizedDock->setGeometry(toRect(r->getGeometry()));
        m_maximizedDock->m_maximized = false;
      }
      // Now, attempt requested item maximization
      QSize minimumSize = item->minimumSize();
      QSize maximumSize = item->maximumSize();
      if (contentsRect().width() > minimumSize.width() &&
          contentsRect().height() > minimumSize.height() &&
          contentsRect().width() < maximumSize.width() &&
          contentsRect().height() < maximumSize.height()) {
        // Maximization succeeds
        item->setGeometry(contentsRect());
        item->raise();
        item->m_maximized = true;
        m_maximizedDock   = item;
        // Hide all the other docked widgets (no need to update them. Moreover,
        // doing so
        // could eventually result in painting over the newly maximized widget)
        DockWidget *currWidget;
        for (int i = 0; i < count(); ++i) {
          currWidget = (DockWidget *)itemAt(i)->widget();
          if (currWidget != item && !currWidget->isFloating())
            currWidget->hide();
        }
      }
    } else {
      // Normalize
      Region *r = find(m_maximizedDock);
      if (r) m_maximizedDock->setGeometry(toRect(r->getGeometry()));
      m_maximizedDock->m_maximized = false;
      m_maximizedDock              = 0;
      // Show all other docked widgets
      DockWidget *currWidget;
      for (int i = 0; i < count(); ++i) {
        currWidget = (DockWidget *)itemAt(i)->widget();
        if (currWidget != item && !currWidget->isFloating()) currWidget->show();
      }
    }
  }
}
sizeHint()
QSize DockLayout::sizeHint () const override
{
  QSize s(0, 0);
  int n = m_items.size();
  if (n > 0) s = QSize(100, 70);  // start with a nice default size
  int i = 0;
  while (i < n) {
    QLayoutItem *o = m_items[i];
    s              = s.expandedTo(o->sizeHint());
    ++i;
  }
  return s + n * QSize(spacing(), spacing());
  // return QSize(0,0);
}
takeAt()
QLayoutItem * DockLayout::takeAt (int idx) override
{
  if (idx < 0 || idx >= (int)m_items.size()) return 0;
  QLayoutItem *item = m_items[idx];
  DockWidget *dw    = static_cast<DockWidget *>(item->widget());
  // If docked, undock item
  if (!dw->isFloating()) undockItem(dw);
  // Reset item's parentLayout
  dw->m_parentLayout = 0;
  m_items.erase(m_items.begin() + idx);
  return item;
}
undockItem()
bool DockLayout::undockItem (DockWidget * item)
Undocks item and updates geometry.
NOTE: Window flags are reset to floating appearance (thus hiding the widget). Since the geometry reference changes a geometry() update may be needed - so item's show() is not forced here. You should eventually remember to call it manually after this.
{
  // Find item's region index in m_regions
  Region *itemCarrier = find(item);
  Region *parent = itemCarrier->getParent();
  if (parent) {
    int removalIdx = 0;
    // Find removal index in parent's childList
    unsigned int j;
    for (j = 0; j < parent->getChildList().size(); ++j)
      if (parent->getChildList()[j]->getItem() == item) break;
    if (isPossibleRemoval(item, parent, removalIdx))
      parent->removeItem(item);
    else
      return false;
  }
  // Remove region in regions list
  // m_regions.erase(i);   //Don't - m_regions is cleaned before the end by
  // remove_if
  itemCarrier->setItem(0);
  std::deque<Region *>::iterator j;
  j = std::remove_if(m_regions.begin(), m_regions.end(), isEmptyRegion);
  m_regions.resize(j - m_regions.begin());
  // Update status
  // qDebug("Undock");
  item->setWindowFlags(Qt::Tool | Qt::FramelessWindowHint);
  // NOTA: Usando la flag Qt::Window il focus viene automaticamente riassegnato,
  // con un po' di ritardo.
  // Usando Tool questo non accade. In questo caso, i placeholder devono essere
  // disattivati...
  item->setFloatingAppearance();
  item->m_floating = true;
  // show minimize button in FlipbookPanel
  item->onDock(false);
  setMaximized(item, false);
  redistribute();
  return true;
}
References DockWidget::setFloatingAppearance().
Referenced by TDockWidget::setFloating().
update()
void DockLayout::update () inline
{
  // E' necessario?
  applyGeometry();
}
widgetAt()
QWidget * DockLayout::widgetAt (int idx) const
{ return itemAt(idx)->widget(); }
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/toonzqt/docklayout.h
E:/opentoonz/toonz/sources/toonzqt/docklayout.cpp
E:/opentoonz/toonz/sources/toonzqt/dockwidget.cpp