opentoonz: TRenderer Class Reference
TRenderer Class Reference
#include <trenderer.h>
Classes
struct RenderData
Public Types
enum RenderStatus { IDLE = 0x0 , FIRSTRUN = 0x1 , TESTRUN = 0x2 , COMPUTING = 0x4 }
Public Member Functions
TRenderer (int nThread=1)
TRenderer (TRendererImp *)
TRenderer (const TRenderer &)
void operator= (const TRenderer &)
operator bool () const
void addPort (TRenderPort *port)
void removePort (TRenderPort *port)
unsigned long startRendering (const std::vector< TRenderer::RenderData > *renderDatas)
unsigned long startRendering (double f, const TRenderSettings &info, const TFxPair &actualRoot)
void abortRendering (unsigned long renderId)
void stopRendering (bool waitForCompleteStop=false)
void enablePrecomputing (bool on)
bool isPrecomputingEnabled () const
void setThreadsCount (int nThreads)
unsigned long rendererId ()
Returns the renderer id.
int getRenderStatus (unsigned long renderId) const
bool isAborted (unsigned long renderId) const
void declareRenderStart (unsigned long renderId)
Declares that the render process of passed renderId is about to start.
void declareRenderEnd (unsigned long renderId)
Declares that the render process of passed renderId has ended.
void declareFrameStart (double frame)
Declares that render of passed frame is about to start.
void declareFrameEnd (double frame)
Declares that render of passed has ended.
void install (unsigned long renderId)
Installs the specified render process on the invoking thread.
void uninstall ()
Uninstalls any rendering process active on the invoking thread.
Static Public Member Functions
static TRenderer instance ()
static unsigned long renderId ()
static unsigned long nextRenderId ()
static unsigned long buildRenderId ()
Builds and returns an id for starting a new rendering process.
static void initialize ()
Friends
class TRenderResourceManagerGenerator
Detailed Description
The TRenderer class provides the core operative interface to the Toonz rendering library. The TRenderer's main purpose is that of invoking a render process on a group of separate threads through the startRendering() methods. After this is done, the activated process communicates with any TRenderPort previously set through the addPort() method in order to notify the render status. The rendering process can be interrupted with the stopRendering() method, which makes all rendering threads quit safely at the most appropriate time; the more specific abortRendering() method may be used to terminate a render process id in case more than one process is running.
Technically, this class is an interface to the actual rendering class, which remains in background. This means that users have no necessity of maintaining the TRenderer instance alive as a render process is running. We may, for example, create a TRenderer, set its properties, launch the render, and release the TRenderer instance immediately after as the internal rendering class will continue working on. TRenderers may therefore be copied and assigned freely to refer an already existing internal rendering instance. These are created anew only using the default TRenderer(int) constructor.
On the other hand, TRenderer's lifespan may last longer than that of a single rendering process. This is especially useful when it is known that multiple rendering processes share some common resources (likewise, intermediate cache results), which can be maintained in the same internal TRenderer representation for later use.
Some final notes about methods dealing with Toonz's lower-level API. Direct invocation of rendering functions, such as the TRasterFx::compute() method, is discouraged. Further improvements of the TRenderer's API will eventually make the need for these calls obsolete. However, we've implemented the possibility to rely on TRenderer's management support even in those cases - it can be done by declaring the render process' interesting events through the apposite declare..() < > methods and invoking install() and uninstall() on each rendering thread you'll raise for the process.
Member Enumeration Documentation
RenderStatus
enum TRenderer::RenderStatus
                    {
    IDLE      = 0x0,
    FIRSTRUN  = 0x1,
    TESTRUN   = 0x2,
    COMPUTING = 0x4
  };
Constructor & Destructor Documentation
TRenderer() [1/3]
TRenderer::TRenderer (int nThread = 1)
{
  m_imp = new TRendererImp(nThread);  // Already adds a ref
}
TRenderer() [2/3]
TRenderer::TRenderer (TRendererImp * imp)
                                      : m_imp(imp) {
  if (m_imp) m_imp->addRef();
}
~TRenderer()
TRenderer::~TRenderer ()
                      {
  if (m_imp) m_imp->release();
}
TRenderer() [3/3]
TRenderer::TRenderer (const TRenderer & r)
                                       : m_imp(r.m_imp) {
  if (m_imp) m_imp->addRef();
}
Member Function Documentation
abortRendering()
void TRenderer::abortRendering (unsigned long renderId)
{
  m_imp->abortRendering(renderId);
}
addPort()
void TRenderer::addPort (TRenderPort * port)
{ m_imp->addPort(port); }
buildRenderId()
unsigned long TRenderer::buildRenderId () static
Builds and returns an id for starting a new rendering process.
{
  return TRendererImp::m_renderIdCounter++;
}
References TRendererImp::m_renderIdCounter.
Referenced by SwatchViewer::ContentRender::run().
declareFrameEnd()
void TRenderer::declareFrameEnd (double frame)
Declares that render of passed has ended.
{ m_imp->declareFrameEnd(frame); }
declareFrameStart()
void TRenderer::declareFrameStart (double frame)
Declares that render of passed frame is about to start.
{
  m_imp->declareFrameStart(frame);
}
declareRenderEnd()
void TRenderer::declareRenderEnd (unsigned long renderId)
Declares that the render process of passed renderId has ended.
{
  m_imp->declareRenderEnd(renderId);
}
References renderId().
declareRenderStart()
void TRenderer::declareRenderStart (unsigned long renderId)
Declares that the render process of passed renderId is about to start.
{
  m_imp->declareRenderStart(renderId);
}
References renderId().
enablePrecomputing()
void TRenderer::enablePrecomputing (bool on)
{ m_imp->enablePrecomputing(on); }
getRenderStatus()
int TRenderer::getRenderStatus (unsigned long renderId) const
{
  return m_imp->getRenderStatus(renderId);
}
initialize()
void TRenderer::initialize () static
{ TRendererStartInvoker::instance(); }
install()
void TRenderer::install (unsigned long renderId)
Installs the specified render process on the invoking thread.
{
  m_imp->addRef();
  rendererStorage.setLocalData(new (TRendererImp *)(m_imp));
  renderIdsStorage.setLocalData(new unsigned long(renderId));
}
References renderId().
instance()
TRenderer TRenderer::instance () static
The static method is intended for use inside a rendering thread only. It returns a copy of the eventual TRenderer interface installed on the thread - or an empty TRenderer if none happened to be. It can be set using the install() and uninstall() methods.
{
  TRendererImp **lData = rendererStorage.localData();
  if (lData) return TRenderer(*lData);
  return 0;
}
Referenced by TLevelColumnFx::doDryCompute().
isAborted()
bool TRenderer::isAborted (unsigned long renderId) const
{
  return m_imp->hasToDie(renderId);
}
isPrecomputingEnabled()
bool TRenderer::isPrecomputingEnabled () const
{
  return m_imp->isPrecomputingEnabled();
}
nextRenderId()
unsigned long TRenderer::nextRenderId () static
Returns the renderId that will be used by the next startRendering() call. This method can be used to retrieve the renderId of a rendering instance before it is actually started - provided that no other render instance is launched inbetween.
{
  return TRendererImp::m_renderIdCounter;
}
References TRendererImp::m_renderIdCounter.
Referenced by Previewer::Imp::refreshFrame().
operator bool()
TRenderer::operator bool () const inline
{ return m_imp; }
operator=()
void TRenderer::operator= (const TRenderer & r)
{
  m_imp = r.m_imp;
  if (m_imp) m_imp->addRef();
}
removePort()
void TRenderer::removePort (TRenderPort * port)
{ m_imp->removePort(port); }
rendererId()
unsigned long TRenderer::rendererId ()
Returns the renderer id.
{ return m_imp->m_rendererId; }
renderId()
unsigned long TRenderer::renderId () static
Returns the rendering process id currently running on the invoking thread.
{
  unsigned long *lData = renderIdsStorage.localData();
  return lData ? *lData : -1;
}
Referenced by declareRenderEnd(), declareRenderStart(), TLevelColumnFx::doDryCompute(), install(), and startRendering().
setThreadsCount()
void TRenderer::setThreadsCount (int nThreads)
{
  m_imp->setThreadsCount(nThreads);
}
startRendering() [1/2]
unsigned long TRenderer::startRendering (const std::vector< TRenderer::RenderData > * renderDatas)
Queues a rendering event in the main event loop. NOTE: The passed pointer is owned by the TRenderer after it is submitted for rendering - do not delete it later.
{
  if (renderDatas->empty()) {
    delete renderDatas;
    return -1;
  }
  // Build a new render Id
  unsigned long renderId = m_imp->m_renderIdCounter++;
  TRendererStartInvoker::StartInvokerRenderData srd;
  srd.m_renderId         = renderId;
  srd.m_renderDataVector = renderDatas;
  TRendererStartInvoker::instance()->emitStartRender(m_imp, srd);
  return renderId;
}
References TRendererImp::m_renderIdCounter, and renderId().
Referenced by Previewer::Imp::refreshFrame().
startRendering() [2/2]
unsigned long TRenderer::startRendering (double f, const TRenderSettings & info, const TFxPair & actualRoot)
{
  assert(f >= 0);
  std::vector<RenderData> *rds = new std::vector<RenderData>;
  rds->push_back(RenderData(f, info, actualRoot));
  return startRendering(rds);
}
stopRendering()
void TRenderer::stopRendering (bool waitForCompleteStop = false)
{
  m_imp->stopRendering(waitForCompleteStop);
}
uninstall()
void TRenderer::uninstall ()
Uninstalls any rendering process active on the invoking thread.
{
  rendererStorage.setLocalData(0);
  renderIdsStorage.setLocalData(0);
  m_imp->release();
}
Friends And Related Function Documentation
TRenderResourceManagerGenerator
friend class TRenderResourceManagerGenerator friend
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/trenderer.h
E:/opentoonz/toonz/sources/common/tfx/trenderer.cpp