opentoonz: ColumnLevel Class Reference
ColumnLevel Class Reference
Public Member Functions
ColumnLevel (TXshSoundLevel *soundLevel=0, int startFrame=-1, int startOffset=-1, int endOffset=-1, double fps=-1)
ColumnLevel * clone () const
TXshSoundLevel * getSoundLevel () const
Overridden from TXshLevel.
void setSoundLevel (TXshSoundLevelP level)
void loadData (TIStream &is)
void saveData (TOStream &os)
void setStartOffset (int value)
int getStartOffset () const
void setEndOffset (int value)
int getEndOffset () const
void setOffsets (int startOffset, int endOffset)
void setStartFrame (int frame)
Return the starting frame without offsets.
int getStartFrame () const
int getEndFrame () const
Return the ending frame without offsets.
int getFrameCount () const
Return frame count without offset.
int getVisibleFrameCount () const
Return frame count with offset.
int getVisibleStartFrame () const
Return start frame with offset.
int getVisibleEndFrame () const
Return last frame with offset.
void updateFrameRate (double newFrameRate)
Updates m_startOfset and m_endOffset.
void setFrameRate (double fps)
Detailed Description
Constructor & Destructor Documentation
ColumnLevel()
ColumnLevel::ColumnLevel (TXshSoundLevel * soundLevel = 0, int startFrame = -1, int startOffset = -1, int endOffset = -1, double fps = -1)
    : m_soundLevel(soundLevel)
    , m_startOffset(startOffset)
    , m_endOffset(endOffset)
    , m_startFrame(startFrame)
    , m_fps(fps) {}
~ColumnLevel()
ColumnLevel::~ColumnLevel ()
{}
Member Function Documentation
clone()
ColumnLevel * ColumnLevel::clone () const
{
  ColumnLevel *soundColumnLevel = new ColumnLevel();
  soundColumnLevel->setSoundLevel(getSoundLevel());
  soundColumnLevel->setStartFrame(m_startFrame);
  soundColumnLevel->setStartOffset(m_startOffset);
  soundColumnLevel->setEndOffset(m_endOffset);
  soundColumnLevel->setFrameRate(m_fps);
  return soundColumnLevel;
}
getEndFrame()
int ColumnLevel::getEndFrame () const
Return the ending frame without offsets.
{
  if (!m_soundLevel) return -1;
  return getStartFrame() + getFrameCount() - 1;
}
References getFrameCount().
Referenced by TXshSoundColumn::getLevelRangeWithoutOffset().
getEndOffset()
int ColumnLevel::getEndOffset () const inline
{ return m_endOffset; }
getFrameCount()
int ColumnLevel::getFrameCount () const
Return frame count without offset.
{
  if (!m_soundLevel) return -1;
  return m_soundLevel->getFrameCount();
}
Referenced by getEndFrame(), and getVisibleFrameCount().
getSoundLevel()
TXshSoundLevel * ColumnLevel::getSoundLevel () const inline
Overridden from TXshLevel.
{ return m_soundLevel.getPointer(); }
Referenced by TXshSoundColumn::checkColumn(), TXshSoundColumn::getCell(), TXshSoundColumn::insertEmptyCells(), TXshSoundColumn::isCellEmpty(), and TXshSoundColumn::play().
getStartFrame()
int ColumnLevel::getStartFrame () const inline
{ return m_startFrame; }
getStartOffset()
int ColumnLevel::getStartOffset () const inline
{ return m_startOffset; }
getVisibleEndFrame()
int ColumnLevel::getVisibleEndFrame () const
Return last frame with offset.
{
  if (!m_soundLevel) return -1;
  return getVisibleStartFrame() + getVisibleFrameCount() - 1;
}
References getVisibleFrameCount(), and getVisibleStartFrame().
Referenced by TXshSoundColumn::checkColumn(), TXshSoundColumn::getLevelRange(), TXshSoundColumn::insertEmptyCells(), and TXshSoundColumn::modifyCellRange().
getVisibleFrameCount()
int ColumnLevel::getVisibleFrameCount () const
Return frame count with offset.
{
  if (!m_soundLevel) return -1;
  return getFrameCount() - getStartOffset() - getEndOffset();
}
References getFrameCount().
Referenced by getVisibleEndFrame().
getVisibleStartFrame()
int ColumnLevel::getVisibleStartFrame () const
Return start frame with offset.
{
  if (!m_soundLevel) return -1;
  return getStartFrame() + getStartOffset();
}
Referenced by TXshSoundColumn::checkColumn(), TXshSoundColumn::getLevelRange(), getVisibleEndFrame(), TXshSoundColumn::insertEmptyCells(), and TXshSoundColumn::modifyCellRange().
loadData()
void ColumnLevel::loadData (TIStream & is)
{
  std::string tagName;
  is.openChild(tagName);
  if (tagName == "SoundCells") {
    TPersist *p = 0;
    is >> m_startOffset >> m_endOffset >> m_startFrame >> p;
    TXshSoundLevel *xshLevel = dynamic_cast<TXshSoundLevel *>(p);
    if (xshLevel) m_soundLevel = xshLevel;
  }
  is.closeChild();
}
saveData()
void ColumnLevel::saveData (TOStream & os)
{
  os.child("SoundCells") << getStartOffset() << getEndOffset()
                         << getStartFrame() << m_soundLevel.getPointer();
}
setEndOffset()
void ColumnLevel::setEndOffset (int value)
{
  if (!m_soundLevel) return;
  if (value < 0 || getStartFrame() + getFrameCount() - value <
                       getStartFrame() + getStartOffset() + 1)
    return;
  m_endOffset = value;
}
setFrameRate()
void ColumnLevel::setFrameRate (double fps) inline
{ m_fps = fps; }
setOffsets()
void ColumnLevel::setOffsets (int startOffset, int endOffset)
{
  assert(startOffset > 0 && endOffset > 0);
  if (startOffset < 0 || startOffset > getFrameCount() - endOffset - 1) return;
  m_startOffset = startOffset;
  if (endOffset < 0 || getStartFrame() + getFrameCount() - endOffset <
                           getStartFrame() + getStartOffset() + 1)
    return;
  m_endOffset = endOffset;
}
setSoundLevel()
void ColumnLevel::setSoundLevel (TXshSoundLevelP level) inline
{ m_soundLevel = level; }
setStartFrame()
void ColumnLevel::setStartFrame (int frame) inline
Return the starting frame without offsets.
{ m_startFrame = frame; }
Referenced by TXshSoundColumn::insertEmptyCells().
setStartOffset()
void ColumnLevel::setStartOffset (int value)
{
  if (!m_soundLevel) return;
  if (value < 0 || value > getFrameCount() - getEndOffset() - 1) return;
  m_startOffset = value;
}
updateFrameRate()
void ColumnLevel::updateFrameRate (double newFrameRate)
Updates m_startOfset and m_endOffset.
{
  if (m_fps == newFrameRate) return;
  double fact   = (double)newFrameRate / m_fps;
  m_startFrame  = tround(m_startFrame * fact);
  m_startOffset = tround(m_startOffset * fact);
  m_endOffset   = tround(m_endOffset * fact);
  m_fps         = newFrameRate;
}
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/toonz/txshsoundcolumn.h
E:/opentoonz/toonz/sources/toonzlib/txshsoundcolumn.cpp