opentoonz: StrokeGenerator Class Reference
StrokeGenerator Class Reference
Genera degli stroke.
#include <strokegenerator.h>
Public Member Functions
StrokeGenerator ()
Costruttore.
~StrokeGenerator ()
Distruttore.
void clear ()
Libera le variabili della classe.
bool isEmpty () const
Restituisce true se m_points e' vuoto, false altrimenti.
void add (const TThickPoint &point, double pixelSize2)
Aggiunge un TThickPoint al vettore m_points.
TPointD getFirstPoint ()
void filterPoints ()
Filtra i punti di m_points.
void drawLastFragments ()
Visualizza l'ultimo frammento.
void drawAllFragments ()
Visualizza tutti i frammenti.
void removeMiddlePoints ()
TRectD getModifiedRegion () const
Restituisce il rettangolo che contiene la regione modificata.
TRectD getLastModifiedRegion ()
Restituisce il rettangolo che contiene l'ultima regione modificata.
TStroke * makeStroke (double error, UINT onlyLastPoints=0) const
Genera uno stroke usando TStroke::interpolate.
Detailed Description
Genera degli stroke.
Genera degli stroke sulla base di un vettore di punti, questo vettore e' fatto di punti che vengono inseriti. Consente di visualizzare dei frammenti fatti dai punti che acquisisce.
Constructor & Destructor Documentation
StrokeGenerator()
StrokeGenerator::StrokeGenerator () inline
Costruttore.
: m_paintedPointCount(0) {}
~StrokeGenerator()
StrokeGenerator::~StrokeGenerator () inline
Distruttore.
{}
Member Function Documentation
add()
void StrokeGenerator::add (const TThickPoint & point, double pixelSize2)
Aggiunge un TThickPoint al vettore m_points.
Il punto viene aggiunto se la sua distanza dal punto precedente e' maggiore di 4*pixelSize2
Parameters
point TThickPoint da aggiungere al vettore
pixelSize2 Dimensione pixel
{
  if (m_points.empty()) {
    double x = point.x, y = point.y, d = point.thick + 3;
    m_points.push_back(point);
    TRectD rect(x - d, y - d, x + d, y + d);
    m_modifiedRegion     = rect;
    m_lastPointRect      = rect;
    m_lastModifiedRegion = rect;
    m_p0 = m_p1 = point;
  } else {
    TThickPoint lastPoint = m_points.back();
    if (tdistance2(lastPoint, point) >= 4 * pixelSize2) {
      m_points.push_back(point);
      double d = std::max(point.thick, lastPoint.thick) + 3;
      TRectD rect(TRectD(lastPoint, point).enlarge(d));
      m_modifiedRegion += rect;
      m_lastModifiedRegion += rect;
      m_lastPointRect = rect;
    } else {
      m_points.back().thick = std::max(m_points.back().thick, point.thick);
    }
  }
}
Referenced by RasterTapeTool::closeFreehand(), SelectionTool::closeFreehand(), RasterTapeTool::freehandDrag(), SelectionTool::freehandDrag(), RasterTapeTool::startFreehand(), and SelectionTool::startFreehand().
clear()
void StrokeGenerator::clear ()
Libera le variabili della classe.
{
  m_points.clear();
  m_modifiedRegion = TRectD();
  m_lastPointRect.empty();
  m_lastModifiedRegion.empty();
  m_paintedPointCount = 0;
  m_p0 = m_p1 = TPointD();
}
Referenced by RasterTapeTool::startFreehand(), and SelectionTool::startFreehand().
drawAllFragments()
void StrokeGenerator::drawAllFragments ()
Visualizza tutti i frammenti.
{
  if (m_points.empty()) return;
  int n          = m_points.size();
  int i          = 0;
  const double h = 0.01;
  TThickPoint a = m_points[0];
  if (a.thick >= h) tglDrawDisk(a, a.thick);
  drawFragments(1, n - 1);
  /*
//last fragment
TPointD p0 = c+v;
TPointD p1 = c-v;
glBegin(GL_POLYGON);
tglVertex(m_p0);
tglVertex(m_p1);
tglVertex(p1);
tglVertex(p0);
glEnd();
*/
  a = m_points.back();
  if (a.thick >= h) tglDrawDisk(a, a.thick);
}
Referenced by ControlPointEditorTool::draw(), FullColorEraserTool::draw(), RasterTapeTool::draw(), ToonzVectorBrushTool::draw(), and EraserTool::draw().
drawLastFragments()
void StrokeGenerator::drawLastFragments ()
Visualizza l'ultimo frammento.
{
  if (m_points.empty()) return;
  int n          = m_points.size();
  int i          = m_paintedPointCount;
  const double h = 0.01;
  if (i == 0) {
    TThickPoint a = m_points[0];
    if (a.thick >= h) tglDrawDisk(a, a.thick);
    i++;
  }
  drawFragments(i, n - 1);
  m_paintedPointCount = std::max(0, n - 2);
}
filterPoints()
void StrokeGenerator::filterPoints ()
Filtra i punti di m_points.
Verifica se i primi sei e gli ultimi sei punti successivi hanno una
variazione di thickness elevata. In caso affermativo li cancella.
{
  if (m_points.size() < 10) return;
  //  filtra m_points iniziali: generalmente elevate variazioni di thickness
  //  si hanno tra m_points[0] (al massimo m_points[1]) e i successivi)
  int size1 = m_points.size();
  int kMin  = 0;
  int kMax  = std::min(
      4,
      size1 -
          2);  //  confronta 5 m_points iniziali con i successivi corrispondenti
  int k = kMax;
  for (k = kMax; k >= kMin; --k) {
    TThickPoint currPoint = m_points[k];
    TThickPoint nextPoint = m_points[k + 1];
    double dist           = tdistance(currPoint, nextPoint);
    double deltaThick     = fabs(currPoint.thick - nextPoint.thick);
    if (deltaThick > 0.6 * dist)  //  deltaThick <= dist (condizione
                                  //  approssimata di non-autocontenimento per
                                  //  TTQ)
    {
      vector<TThickPoint>::iterator it1 = m_points.begin();
      vector<TThickPoint>::iterator it2 = it1 + k + 1;
      m_points.erase(it1, it2);  //  cancella da m_points[0] a m_points[k]
      assert((int)m_points.size() == size1 - k - 1);
      break;
    }
  }
  //  filtra m_points finali: generalmente elevate variazioni di thickness
  //  si hanno tra m_points[size - 1] (al massimo m_points[size - 2]) e i
  //  predecessori)
  int size2 = m_points.size();
  kMax      = size2 - 1;
  kMin      = std::max(
      kMax - 4,
      1);  //  confronta 5 m_points finali con i predecessori corrispondenti
  k = kMin;
  for (k = kMin; k <= kMax; ++k) {
    TThickPoint currPoint = m_points[k];
    TThickPoint prevPoint = m_points[k - 1];
    double dist           = tdistance(currPoint, prevPoint);
    double deltaThick     = fabs(currPoint.thick - prevPoint.thick);
    if (deltaThick > 0.6 * dist)  //  deltaThick <= dist (condizione
                                  //  approssimata di non-autocontenimento per
                                  //  TTQ)
    {
      int kTmp = k;
      while (k <= kMax)  //  cancella da m_points[k] a m_points[size2 - 1]
      {
        m_points.pop_back();
        ++k;
      }
      assert((int)m_points.size() == size2 - (kMax - kTmp + 1));
      break;
    }
  }
}
Referenced by RasterTapeTool::closeFreehand(), and SelectionTool::closeFreehand().
getFirstPoint()
TPointD StrokeGenerator::getFirstPoint ()
{ return m_points[0]; }
getLastModifiedRegion()
TRectD StrokeGenerator::getLastModifiedRegion ()
Restituisce il rettangolo che contiene l'ultima regione modificata.
{
  TRectD ret           = m_lastModifiedRegion;
  m_lastModifiedRegion = m_lastPointRect;
  return ret;
}
getModifiedRegion()
TRectD StrokeGenerator::getModifiedRegion () const
Restituisce il rettangolo che contiene la regione modificata.
{ return m_modifiedRegion; }
isEmpty()
bool StrokeGenerator::isEmpty () const
Restituisce true se m_points e' vuoto, false altrimenti.
{ return m_points.empty(); }
Referenced by RasterTapeTool::closeFreehand(), SelectionTool::closeFreehand(), ControlPointEditorTool::draw(), FullColorEraserTool::draw(), RasterTapeTool::draw(), and EraserTool::draw().
makeStroke()
TStroke * StrokeGenerator::makeStroke (double error, UINT onlyLastPoints = 0) const
Genera uno stroke usando TStroke::interpolate.
Se onlyLastPoints e' uguale a 0 genera lo stroke sulla base di m_points.
Se onlyLastPoints e' diverso da zero genera lo stroke sulla base degli ultimi onlyLastPoint elementi di m_points
      \param error          Errore che viene passato a TStroke::interpolate
      \param onlyLastPoints Numero elementi sulla base dei quali creare la
stroke
{
  if (onlyLastPoints == 0 || onlyLastPoints > m_points.size())
    return TStroke::interpolate(m_points, error);
  vector<TThickPoint> lastPoints(onlyLastPoints);
  vector<TThickPoint>::const_iterator first =
      m_points.begin() + (m_points.size() - onlyLastPoints);
  copy(first, m_points.end(), lastPoints.begin());
  return TStroke::interpolate(lastPoints, error);
}
References TStroke::interpolate().
Referenced by RasterTapeTool::closeFreehand(), and SelectionTool::closeFreehand().
removeMiddlePoints()
void StrokeGenerator::removeMiddlePoints ()
{
  int size = m_points.size();
  if (size > 2) {
    m_points.erase(m_points.begin() + 1, m_points.begin() + (size - 1));
  }
}
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/toonz/strokegenerator.h
E:/opentoonz/toonz/sources/toonzlib/strokegenerator.cpp