opentoonz: TThread::Runnable Class Reference
TThread::Runnable Class Reference abstract
#include <tthread.h>
Public Slots
virtual void onStarted (TThread::RunnableP sender)
virtual void onFinished (TThread::RunnableP sender)
The analogous of onStarted() for the finished() signal.
virtual void onException (TThread::RunnableP sender)
The analogous of onStarted() for the exception() signal.
virtual void onCanceled (TThread::RunnableP sender)
The analogous of onStarted() for the canceled() signal.
virtual void onTerminated (TThread::RunnableP sender)
The analogous of onStarted() for the terminated() signal.
Signals
void started (TThread::RunnableP sender)
void finished (TThread::RunnableP sender)
void exception (TThread::RunnableP sender)
void canceled (TThread::RunnableP sender)
void terminated (TThread::RunnableP sender)
Public Member Functions
virtual void run ()=0
The central code of the task that is executed by a worker thread.
virtual int taskLoad ()
virtual int schedulingPriority ()
virtual QThread::Priority runningPriority ()
Public Member Functions inherited from TSmartObject
TSmartObject (ClassCode classCode)
void addRef ()
void release ()
TINT32 getRefCount () const
Friends
class Executor
class ExecutorImp
class Worker
Additional Inherited Members
Public Types inherited from TSmartObject
typedef short ClassCode
Static Public Member Functions inherited from TSmartObject
static TINT32 getInstanceCount (ClassCode code)
Detailed Description
Runnable class is the abstract model for user-defined tasks which can be scheduled for execution into separate application threads.
A user must first implement the run() method to provide a task with the very execution code. Worker threads created internally by the task manager will take ownership of the task and make it run() at the most appropriate time, depending on the task load, insertion time and its scheduling priority.
The scheduling priority of a task can be set by reimplementing the schedulingPriority() method. Tasks whose scheduling priority is higher are always started before compared to the others added by the same executor.
The hosting thread's running priority may also be set reimplementing the runningPriority() method; see QThread class documentation in Qt manual.
A task's load is an important property that should be reimplemented in all resource-consuming tasks. It enables the user to declare the approximate CPU load produced by a task, allowing the task manager to effectively calculate the most appropriate moment to run it.
Warning
All built-in signals about the Runnable class are emitted in a mutex-protected environment in order to make sure that signal emission is consistent with the task status - in other words, so that queued controller-emitted canceled() and terminated() signals are not delivered before started() or after finished() and exception() worker-emitted signals.
Thus, setting up blocking connections or blocking direct slots is not supported and will typically result in deadlocks; furthermore, the same also applies to slot calls to the Executor API, which would have the aforementioned mutex to be locked again.
In case the above blocking strategies are mandatory, the user should add custom signals to be emitted inside the mutex-free run() block, just before or after the actual code to be executed, like this:
void MyTask::run()
{
  try
  {
    emit myStarted(this);
    theRunCode();
    emit myFinished(this);
  }
  catch(...)
  {
    emit myException(this);
    throw;
  }
}
  ..
  MyTask* myTask = new MyTask;
  connect(myTask, SIGNAL(myStarted(TThread::RunnableP)), myTask,
SLOT(onStarted(TThread::RunnableP)),
    Qt::BlockingQueuedConnection)   //theRunCode() waits for onStarted() to
complete
  ..
See also
Executor class.
Constructor & Destructor Documentation
Runnable()
Runnable::Runnable ()
: TSmartObject(m_classCode), m_id(0) {}
~Runnable()
Runnable::~Runnable () virtual
                    {
  if (m_id) m_id->release();  // see Executor::addTask()
}
Member Function Documentation
canceled
void Runnable::canceled (TThread::RunnableP sender) signal
The canceled signal is emitted from the controller thread whenever a task which is currently under the task manager's control is canceled by the user (the signal is emitted from the thread invoking the cancel). Observe that tasks under execution are not stopped by the task manager when they are canceled, but the signal is emitted anyway - helping the user to stop the actual execution of the run() code in advance.
See also
Executor::removeTask and Executor::cancelAll methods.
Referenced by TThread::Executor::cancelAll(), TThread::Executor::removeTask(), and TThread::Executor::shutdown().
exception
void Runnable::exception (TThread::RunnableP sender) signal
The exception signal is emitted from working threads whenever an untrapped exception is found within the run() method.
See also
started and finished signals.
finished
void Runnable::finished (TThread::RunnableP sender) signal
The finished signal is emitted from working threads once the run() code is returned without unmanaged exceptions.
See also
started and exception signals.
onCanceled
void Runnable::onCanceled (TThread::RunnableP sender) virtual slot
The analogous of onStarted() for the canceled() signal.
Reimplemented in SwatchViewer::ContentRender.
{}
onException
void Runnable::onException (TThread::RunnableP sender) virtual slot
The analogous of onStarted() for the exception() signal.
{}
onFinished
void Runnable::onFinished (TThread::RunnableP sender) virtual slot
The analogous of onStarted() for the finished() signal.
Reimplemented in CustomStyleManager::StyleLoaderTask, ImageProcessing, SwatchViewer::ContentRender, VectorizationSwatchTask, and RenderTask.
{}
onStarted
void Runnable::onStarted (TThread::RunnableP sender) virtual slot
Convenience slot for the started() signal - so it's not necessary to declare the task in a header file for moc'ing each time. You must both reimplement and connect it to the started() signal to make it work.
Reimplemented in SwatchViewer::ContentRender, and VectorizationSwatchTask.
{}
onTerminated
void Runnable::onTerminated (TThread::RunnableP sender) virtual slot
The analogous of onStarted() for the terminated() signal.
{}
run()
virtual void TThread::Runnable::run () pure virtual
The central code of the task that is executed by a worker thread.
Implemented in RecordTask, ImageProcessing, TThread::Executor::Imp::Worker, RenderTask, RecordTask, SwatchViewer::ContentRender, TaskRunner, FrameCountTask, VectorizationSwatchTask, DataReader, DataReceiver, ServerInitializer, TaskStarter, Task, CustomStyleManager::StyleLoaderTask, VectorImageIconRenderer, SplineIconRenderer, RasterImageIconRenderer, ToonzImageIconRenderer, MeshImageIconRenderer, XsheetIconRenderer, FileIconRenderer, SceneIconRenderer, and IconRenderer.
runningPriority()
QThread::Priority Runnable::runningPriority () virtual
Returns the QThread::Priority used by worker threads when they adopt the task. The default value returned is QThread::Normal.
Reimplemented in FrameCountTask.
{
  return QThread::NormalPriority;
}
schedulingPriority()
int Runnable::schedulingPriority () virtual
Returns the priority value used to schedule a task for execution. Tasks with higher priority start before tasks with lower priority. The default value returned is 5 (halfway from 0 to 10) - but any value other than (std::numeric_limits<int>::max)() is acceptable.
{ return 5; }
Referenced by TThread::Executor::addTask().
started
void Runnable::started (TThread::RunnableP sender) signal
This signal is emitted from working threads just before the run() code is executed. Observe that the passed smart pointer ensures the survival of the emitting task for the time required by connected slots execution.
Warning
The started(), finished() and exception() signals are emitted in a mutex-protected environment in order to provide the correct sequence of emissions (i.e. so that canceled() and terminated() controller-emitted signals are either delivered after started() and before finished() or exception(), or instead of them).
Thus, setting up blocking connections or direct slots that contain a blocking instruction or even calls to the Executor API (which would definitely try to relock the aforementioned mutex) is dangerous and could result in an application freeze.
In case it's necessary to use blocking features, they should be enforced through custom signals to be invoked manually in the run() method, outside the mutex.
See also
finished and exception signals.
taskLoad()
int Runnable::taskLoad () virtual
Returns the predicted CPU load generated by the task, expressed in percentage of core usage (that is, 100 is intended to fully occupy one processing core). Appropriate task load calibration is an important step to take when implementing a new task; for this purpose, remember some rules to follow:
In every moment, the task manager ensures that the overall sum of the active task's load does not exceed the number of machine's processing cores multiplied by 100. This condition is blocking with respect to the execution of any other task - meaning that when a task is about to be executed the task manager waits until enough CPU resources are available to make it run. In particular, observe that a task's load never has to exceed the total CPU resources - doing so would surely result in a block of your application. The number of available cores can be accessed via the TSystem::getProcessorCount() or QThread::idealThreadCount().
The task load is considered constant for the duration of the task. Changing its value does not affect the task manager in any way once the task has been started.
The default task load is 0, representing a very light task. If the task load is 0 the condition at point 1 always succeeds - so the task is always executed when encountered. Observe that a long succession of 0 task loads leads to the creation of a proportional number of threads simultaneously running to dispatch it; if this is a problem, consider the use of Executor::setMaxActiveTasks() to make only a certain number of tasks being executed at the same time.
Reimplemented in RenderTask, SwatchViewer::ContentRender, and TaskRunner.
{ return 0; }
terminated
void Runnable::terminated (TThread::RunnableP sender) signal
The terminated signal is emitted from the controller thread when the Executor components are shutting down inside a call to Executor::shutdown(). Implementing a slot connected to this signal helps the user in controlling the flow of an Executor-multithreaded application when it is shutting down - for example, it can be imposed that the application must wait for the task to be finished, print logs or similar. This signal is always preceded by a canceled() signal, informing all active tasks that they should begin quitting on their own in a 'soft' way before brute termination may occur.
See also
Executor::shutdown static method and Runnable::canceled signal.
Referenced by TThread::Executor::shutdown().
Friends And Related Function Documentation
Executor
friend class Executor friend
ExecutorImp
friend class ExecutorImp friend
Worker
friend class Worker friend
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/tthread.h
E:/opentoonz/toonz/sources/common/tcore/tthread.cpp