opentoonz: FullColorAreaFiller Class Reference
FullColorAreaFiller Class Reference
Public Member Functions
FullColorAreaFiller (const TRaster32P &ras)
void rectFill (const TRect &rect, const FillParameters &params, bool onlyUnfilled)
Detailed Description
Constructor & Destructor Documentation
FullColorAreaFiller()
FullColorAreaFiller::FullColorAreaFiller (const TRaster32P & ras)
    : m_ras(ras)
    , m_bounds(ras->getBounds())
    , m_pixels(ras->pixels())
    , m_wrap(ras->getWrap())
    , m_color(0) {
  m_ras->lock();
}
~FullColorAreaFiller()
FullColorAreaFiller::~FullColorAreaFiller ()
{ m_ras->unlock(); }
Member Function Documentation
rectFill()
void FullColorAreaFiller::rectFill (const TRect & rect, const FillParameters & params, bool onlyUnfilled)
Fill rect in raster with color.
If fillPaints is false fill only ink in rect; else if fillInks is false fill only paint delimited by ink; else fill ink and paint in rect.
{
  TRect bbox = m_ras->getBounds();
  TRect r    = rect * bbox;
  if (r.isEmpty()) return;
  TRaster32P workRas = m_ras->extract(r);
  TRaster32P copy    = workRas->clone();
  TPixel32 color = params.m_palette->getStyle(params.m_styleId)->getMainColor();
  // Fillo tutto il quadaratino con color
  int x, y;
  for (y = 0; y < workRas->getLy(); y++) {
    TPixel32 *line = workRas->pixels(y);
    for (x = 0; x < workRas->getLx(); x++)
      *(line + x) = overPix(color, workRas->pixels(y)[x]);
  }
  FillParameters paramsApp = params;
  TPixel32 refColor;
  for (y = 0; y < workRas->getLy(); y++) {
    paramsApp.m_p = TPoint(0, y);
    if (y == 0 ||
        refColor != workRas->pixels(paramsApp.m_p.y)[paramsApp.m_p.x]) {
      fill(workRas, copy, paramsApp);
      refColor = workRas->pixels(paramsApp.m_p.y)[paramsApp.m_p.x];
    }
  }
  for (y = 0; y < workRas->getLy(); y++) {
    paramsApp.m_p = TPoint(workRas->getLx() - 1, y);
    if (y == 0 ||
        refColor != workRas->pixels(paramsApp.m_p.y)[paramsApp.m_p.x]) {
      fill(workRas, copy, paramsApp);
      refColor = workRas->pixels(paramsApp.m_p.y)[paramsApp.m_p.x];
    }
  }
  for (x = 0; x < workRas->getLx(); x++) {
    paramsApp.m_p = TPoint(x, 0);
    if (x == 0 ||
        refColor != workRas->pixels(paramsApp.m_p.y)[paramsApp.m_p.x]) {
      fill(workRas, copy, paramsApp);
      refColor = workRas->pixels(paramsApp.m_p.y)[paramsApp.m_p.x];
    }
  }
  for (x = 0; x < workRas->getLx(); x++) {
    paramsApp.m_p = TPoint(x, workRas->getLy() - 1);
    if (x == 0 ||
        refColor != workRas->pixels(paramsApp.m_p.y)[paramsApp.m_p.x]) {
      fill(workRas, copy, paramsApp);
      refColor = workRas->pixels(paramsApp.m_p.y)[paramsApp.m_p.x];
    }
  }
}
References TColorStyle::getMainColor(), TPalette::getStyle(), and TRectT< T >::isEmpty().
Referenced by ImageFiller::build().
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/toonz/fill.h
E:/opentoonz/toonz/sources/toonzlib/fillutil.cpp