opentoonz: SchematicLink Class Reference
SchematicLink Class Reference
#include <schematicnode.h>
Public Member Functions
SchematicLink (QGraphicsItem *parent, QGraphicsScene *scene)
QRectF boundingRect () const override
Reimplements the pure virtual QGraphicsItem::boundingRect() method.
QPainterPath shape () const override
Reimplements the virtual QGraphicsItem::shape() method.
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=0) override
Reimplements the pure virtual QGraphicsItem::paint() method.
void updatePath (const QPointF &startPos, const QPointF &endPos)
void updatePath (SchematicPort *startPort, SchematicPort *endPort)
void updatePath ()
void updateEndPos (const QPointF &endPos)
void setStartPort (SchematicPort *startPort)
Sets the start SchematicPort of the link to startPort.
void setEndPort (SchematicPort *endPort)
Sets the start SchematicPort of the link to startPort.
SchematicPort * getStartPort () const
Returns the start SchematicPort of the link.
SchematicPort * getEndPort () const
Returns the end SchematicPort of the link.
SchematicPort * getOtherPort (const SchematicPort *port) const
SchematicNode * getOtherNode (const SchematicNode *node) const
bool isLineShaped ()
Returns true if the link is line shaped.
void setLineShaped (bool value)
bool isHighlighted ()
void setHighlighted (bool value)
Protected Member Functions
void mousePressEvent (QGraphicsSceneMouseEvent *me) override
void mouseReleaseEvent (QGraphicsSceneMouseEvent *me) override
Detailed Description
 \brief The class provides method to draw links between two SchematicPort
 A link can has a cubic shape or a line shape and is drawing calling the
updatePath() method. The class also provides methods to retrieve the start SchematicPort and the end SchematicPort of the link and a method to remove the link from these two SchematicPort.
See also
SchematicPort, SchematicNode.
Constructor & Destructor Documentation
SchematicLink()
SchematicLink::SchematicLink (QGraphicsItem * parent, QGraphicsScene * scene)
    : QGraphicsItem(parent)
#else
    : QGraphicsItem(parent, scene)
#endif
    , m_startPort(0)
    , m_endPort(0)
    , m_path()
    , m_hitPath()
    , m_lineShaped(false)
    , m_highlighted(false) {
#if QT_VERSION >= 0x050000
  scene->addItem(this);
#endif
  setFlag(QGraphicsItem::ItemIsMovable, false);
  setFlag(QGraphicsItem::ItemIsSelectable, true);
  setFlag(QGraphicsItem::ItemIsFocusable, false);
  setZValue(0.0);
}
~SchematicLink()
SchematicLink::~SchematicLink ()
{ m_startPort = m_endPort = 0; }
Member Function Documentation
boundingRect()
QRectF SchematicLink::boundingRect () const override
Reimplements the pure virtual QGraphicsItem::boundingRect() method.
{
  return m_hitPath.boundingRect().adjusted(-5, -5, 5, 5);
}
getEndPort()
SchematicPort * SchematicLink::getEndPort () const inline
Returns the end SchematicPort of the link.
{ return m_endPort; }
Referenced by SchematicScene::clearAllItems(), SchematicPort::isLinkedTo(), and SchematicPort::updateLinksGeometry().
getOtherNode()
SchematicNode * SchematicLink::getOtherNode (const SchematicNode * node) const
Returns the other SchematicNode linked to the specified node.
Returns 0 if node isn't neither the parent node of the start SchematicPort either the parent node of the end SchematicPort of the link.
{
  if (node == m_startPort->getNode())
    return m_endPort->getNode();
  else if (node == m_endPort->getNode())
    return m_startPort->getNode();
  else
    return 0;
}
getOtherPort()
SchematicPort * SchematicLink::getOtherPort (const SchematicPort * port) const
Returns the other SchematicPort linked to the specified port.
Returns 0 if port isn't neither the start SchematicPort either the end SchematicPort of this link.
{
  if (port == m_startPort)
    return m_endPort;
  else if (port == m_endPort)
    return m_startPort;
  else
    return 0;
}
Referenced by SchematicPort::eraseLink(), and FxSchematicScene::simulateDisconnectSelection().
getStartPort()
SchematicPort * SchematicLink::getStartPort () const inline
Returns the start SchematicPort of the link.
{ return m_startPort; }
Referenced by SchematicScene::clearAllItems(), SchematicPort::isLinkedTo(), paint(), and SchematicPort::updateLinksGeometry().
isHighlighted()
bool SchematicLink::isHighlighted () inline
{ return m_highlighted; }
isLineShaped()
bool SchematicLink::isLineShaped () inline
Returns true if the link is line shaped.
{ return m_lineShaped; }
Referenced by FxSelection::select().
mousePressEvent()
void SchematicLink::mousePressEvent (QGraphicsSceneMouseEvent * me) override protected
{
  QPointF pos              = me->scenePos();
  SchematicPort *startPort = getStartPort();
  SchematicPort *endPort   = getEndPort();
  if (!startPort || !endPort) {
    me->ignore();
    return;
  }
  if (startPort && endPort) {
    QRectF startRect = startPort->boundingRect();
    startRect.moveTopLeft(startPort->scenePos());
    QRectF endRect = endPort->boundingRect();
    endRect.moveTopLeft(endPort->scenePos());
    if (startRect.contains(pos) || endRect.contains(pos)) {
      me->ignore();
      return;
    }
  }
  QMatrix matrix = scene()->views()[0]->matrix();
#if QT_VERSION >= 0x050000
  double scaleFactor = sqrt(matrix.determinant());
#else
  double scaleFactor = sqrt(matrix.det());
#endif
  QPointF startPos = getStartPort()->getLinkEndPoint();
  QPointF endPos   = getEndPort()->getLinkEndPoint();
  QPointF p0((endPos.x() - startPos.x()) * 0.5, 0);
  QPointF p1(p0.x(), endPos.y() - startPos.y());
  QPointF p2(endPos - startPos);
  double sensitivity = 5 / scaleFactor;
  QPointF h(0, sensitivity);
  QPointF p = h;
  if (p2.y() > 0)
    p.setX(p2.x() > 0 ? -sensitivity : sensitivity);
  else
    p.setX(p2.x() > 0 ? sensitivity : -sensitivity);
  QPainterPath path(QPointF(0, 0));
  path.lineTo(h);
  path.cubicTo(p0 + p, p1 + p, p2 + h);
  path.lineTo(p2 - h);
  path.cubicTo(p1 - p, p0 - p, -h);
  path.lineTo(0, 0);
  if (!path.contains(me->scenePos() - scenePos())) {
    me->ignore();
    return;
  }
  if (!isSelected()) {
    if (me->modifiers() != Qt::ControlModifier) scene()->clearSelection();
    if (me->button() == Qt::LeftButton || me->button() == Qt::RightButton)
      setSelected(true);
  } else {
    if (me->modifiers() == Qt::ControlModifier &&
        me->button() == Qt::LeftButton)
      setSelected(false);
  }
}
mouseReleaseEvent()
void SchematicLink::mouseReleaseEvent (QGraphicsSceneMouseEvent * me) override protected
{
  if (me->modifiers() != Qt::ControlModifier && me->button() != Qt::RightButton)
    QGraphicsItem::mouseReleaseEvent(me);
}
paint()
void SchematicLink::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget = 0) override
Reimplements the pure virtual QGraphicsItem::paint() method.
{
  SchematicViewer *viewer;
  FxSchematicScene *fxScene = dynamic_cast<FxSchematicScene *>(scene());
  StageSchematicScene *stageScene =
      dynamic_cast<StageSchematicScene *>(scene());
  if (fxScene) {
    viewer = fxScene->getSchematicViewer();
  } else if (stageScene) {
    viewer = stageScene->getSchematicViewer();
  } else {
    return;
  }
  if (getStartPort() && (getStartPort()->getType() == 100  // eStageSplinePort
                         || getStartPort()->getType() == 202)) {  // eFxLinkPort
    if (isSelected() || isHighlighted())
      painter->setPen(QPen(viewer->getMotionPathSelectedLinkColor()));
    else
      painter->setPen(QColor(viewer->getMotionPathLinkColor()));
  } else if (isSelected() || isHighlighted())
    painter->setPen(QPen(viewer->getSelectedLinkColor()));
  else if (!m_lineShaped)
    painter->setPen(QPen(viewer->getLinkColor()));
  else
    painter->setPen(QPen(QColor(170, 170, 10), 0, Qt::DashLine));
  painter->setRenderHint(QPainter::Antialiasing, true);
  painter->drawPath(m_path);
}
References getStartPort(), and SchematicPort::getType().
setEndPort()
void SchematicLink::setEndPort (SchematicPort * endPort) inline
Sets the start SchematicPort of the link to startPort.
{ m_endPort = endPort; }
Referenced by SchematicPort::makeLink(), and FxSchematicPort::makeLink().
setHighlighted()
void SchematicLink::setHighlighted (bool value) inline
{ m_highlighted = value; }
setLineShaped()
void SchematicLink::setLineShaped (bool value) inline
{ m_lineShaped = value; }
setStartPort()
void SchematicLink::setStartPort (SchematicPort * startPort) inline
Sets the start SchematicPort of the link to startPort.
{ m_startPort = startPort; }
Referenced by SchematicPort::makeLink(), and FxSchematicPort::makeLink().
shape()
QPainterPath SchematicLink::shape () const override
Reimplements the virtual QGraphicsItem::shape() method.
{ return m_hitPath; }
updateEndPos()
void SchematicLink::updateEndPos (const QPointF & endPos)
{
  if (m_startPort) updatePath(m_startPort->getLinkEndPoint(), endPos);
}
updatePath() [1/3]
void SchematicLink::updatePath () inline
{ updatePath(m_startPort, m_endPort); }
updatePath() [2/3]
void SchematicLink::updatePath (const QPointF & startPos, const QPointF & endPos)
Update the link path.
The link is has a cubic shape starting from startPos and ending to endPos. If a link path already exists, the path is updating otherwise a path is created.
{
  prepareGeometryChange();
  setPos(startPos);
  if (!m_lineShaped) {
    QPointF p0((endPos.x() - startPos.x()) * 0.5, 0);
    QPointF p1(p0.x(), endPos.y() - startPos.y());
    QPointF p2(endPos - startPos);
    m_path = QPainterPath(QPointF(0, 0));
    m_path.cubicTo(p0, p1, p2);
    QPointF h(0, 5);
    QPointF p = h;
    if (p2.y() > 0)
      p.setX(p2.x() > 0 ? -5 : 5);
    else
      p.setX(p2.x() > 0 ? 5 : -5);
    m_hitPath = QPainterPath(QPointF(0, 0));
    m_hitPath.lineTo(h);
    m_hitPath.cubicTo(p0 + p, p1 + p, p2 + h);
    m_hitPath.lineTo(p2 - h);
    m_hitPath.cubicTo(p1 - p, p0 - p, -h);
    m_hitPath.lineTo(0, 0);
  } else {
    m_path = QPainterPath(QPointF(0, 0));
    m_path.lineTo(endPos - startPos);
    m_hitPath = QPainterPath(QPointF(0, 0));
    m_hitPath.lineTo(endPos - startPos);
  }
}
References updatePath().
Referenced by SchematicPort::makeLink(), FxSchematicPort::makeLink(), SchematicPort::updateLinksGeometry(), and updatePath().
updatePath() [3/3]
void SchematicLink::updatePath (SchematicPort * startPort, SchematicPort * endPort)
Update the link path.
Call the updatePath(const QPointF &startPos, const QPointF &endPos) method. The start pos and the endPos are taken from the the given startPort and endPort.
{
  updatePath(startPort->getLinkEndPoint(), endPort->getLinkEndPoint());
}
References SchematicPort::getLinkEndPoint(), and updatePath().
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/toonzqt/schematicnode.h
E:/opentoonz/toonz/sources/toonzqt/schematicnode.cpp