opentoonz: TXshSimpleLevel Class Reference
TXshSimpleLevel Class Reference final
The TXshLevel specialization for image levels.
#include <txshsimplelevel.h>
Public Types
enum FrameStatusBit { Normal = 0x0 , Scanned = 0x1 , Cleanupped = 0x2 , CleanupPreview = 0x4 }
Describes a level's frame status.
Public Types inherited from TSmartObject
typedef short ClassCode
Public Types inherited from TPersist
typedef TPersist * CreateProc()
Public Slots
void onPaletteChanged ()
Invoked when some colorstyle has been changed.
Public Member Functions
TXshSimpleLevel (const std::wstring &name=std::wstring())
Constructs a TXshSimpleLevel with a name.
TXshSimpleLevel * getSimpleLevel () override
Reimplemented for TXshLevel.
bool isSubsequence () const
bool is16BitChannelLevel () const
void set16BitChannelLevel (bool value)
bool isReadOnly () const
void setIsReadOnly (bool value)
void updateReadOnly ()
LevelProperties * getProperties () const
< Returns a pointer to the owned level properties.
void clonePropertiesFrom (const TXshSimpleLevel *oldSl)
TPalette * getPalette () const
Returns a pointer to the shared level palette.
void setPalette (TPalette *palette)
Assigns a palette to the level.
TFilePath getPath () const override
Return the file path associated with the level.
void setPath (const TFilePath &path, bool retainCachedImages=false)
TFilePath getScannedPath () const
void setScannedPath (const TFilePath &path)
std::vector< TFrameId > getFids () const
Returns a copy of the level's frame ids.
void getFids (std::vector< TFrameId > &fids) const override
TFrameId getFirstFid () const
TFrameId getLastFid () const
bool isEmpty () const override
Returns whether the level is empty.
bool isFid (const TFrameId &fid) const
Returns whether a given frameId is in the level.
const TFrameId & getFrameId (int index) const
Returns the frame id at specified index.
int getFrameCount () const override
Returns the level's frames count.
TFrameId index2fid (int index) const
int fid2index (const TFrameId &fid) const
an invalid frame otherwise.
int guessIndex (const TFrameId &fid) const
int guessStep () const
void setFrame (const TFrameId &fid, const TImageP &img)
TImageP getFrame (const TFrameId &fid, UCHAR imgManagerParamsMask, int subsampling) const
TImageP getFrame (const TFrameId &fid, bool toBeModified) const
TImageP getFullsampledFrame (const TFrameId &fid, UCHAR imgManagerParamsMask) const
TImageInfo * getFrameInfo (const TFrameId &fid, bool toBeModified)
TImageP getFrameIcon (const TFrameId &fid) const
void loadAllIconsAndPutInCache (bool cacheImagesAsWell)
TRasterImageP getFrameToCleanup (const TFrameId &fid, bool toBeLineProcessed) const
std::string getImageId (const TFrameId &fid, int frameStatus=-1) const
std::string getIconId (const TFrameId &fid, int frameStatus=-1) const
std::string getIconId (const TFrameId &fid, const TDimension &size) const
void eraseFrame (const TFrameId &fid)
void clearFrames ()
void invalidateFrames ()
void invalidateFrame (const TFrameId &fid)
void setEditableRange (unsigned int from, unsigned int to, const std::wstring &userName)
void mergeTemporaryHookFile (unsigned int from, unsigned int to, const TFilePath &hookFile)
void clearEditableRange ()
std::wstring getEditableFileName ()
std::set< TFrameId > getEditableRange ()
Returns the set of editable frames.
int getFrameStatus (const TFrameId &fid) const
void setFrameStatus (const TFrameId &fid, int status)
void makeTlv (const TFilePath &tlvPath)
TImageP createEmptyFrame ()
and assigns the specified level path.
void initializePalette ()
void initializeResolutionAndDpi (const TDimension &dim=TDimension(), double dpi=0)
TDimension getResolution ()
TPointD getImageDpi (const TFrameId &fid=TFrameId::NO_FRAME, int frameStatus=-1)
int getImageSubsampling (const TFrameId &fid) const
TPointD getDpi (const TFrameId &fid=TFrameId::NO_FRAME, int frameStatus=-1)
TRectD getBBox (const TFrameId &fid) const
Returns the bbox for the level's fid, specified in standard inch coordinates (which are different from Toonz's standard world coordinates, by a Stage::inch factor).
void setDirtyFlag (bool on) override
Mark the level as "modified".
bool getDirtyFlag () const
void touchFrame (const TFrameId &fid)
void loadData (TIStream &is) override
Load the level data (i.e. name, path, etc. e.g. from the .tnz file)
void saveData (TOStream &os) override
Save the level data (i.e. name, path, etc. e.g. to the .tnz file)
void load () override
void load (const std::vector< TFrameId > &fIds)
void save () override
Saves the level to disk, with the same path deduction from load()
void save (const TFilePath &fp, const TFilePath &oldFp=TFilePath(), bool overwritePalette=true)
const TContentHistory * getContentHistory () const
note gets the contentHistory. can be 0
TContentHistory * getContentHistory ()
void setContentHistory (TContentHistory *contentHistory)
void setRenumberTable ()
Set elements of m_renumberTable with m_frames.
const std::map< TFrameId, TFrameId > & renumberTable () const
void renumber (const std::vector< TFrameId > &fids)
bool isFrameReadOnly (TFrameId fid)
Public Member Functions inherited from TXshLevel
TXshLevel (ClassCode classCode, std::wstring name)
virtual ~TXshLevel ()
void setName (std::wstring name)
int getType () const
void setType (int type)
change the level type;
ToonzScene * getScene () const
Return the ToonzScene the level belongs to;.
virtual void setScene (ToonzScene *scene)
virtual TXshSimpleLevel * getSimpleLevel ()
Method (to be overridden in subclasses) to downcast to TXshSimpleLevel.
virtual TXshChildLevel * getChildLevel ()
Method (to be overridden in subclasses) to downcast to TXshChildLevel.
virtual TXshZeraryFxLevel * getZeraryFxLevel ()
virtual TXshPaletteLevel * getPaletteLevel ()
Method (to be overridden in subclasses) to downcast to TXshPaletteLevel.
virtual TXshSoundLevel * getSoundLevel ()
Method (to be overridden in subclasses) to downcast to TXshSoundLevel.
virtual TXshSoundTextLevel * getSoundTextLevel ()
std::wstring getName () const
Return level name.
std::wstring getShortName () const
Return level short name.
virtual TFilePath getPath () const
Return the file path associated with the level.
virtual bool isEmpty () const
virtual int getFrameCount () const
virtual void getFids (std::vector< TFrameId > &fids) const
void loadData (TIStream &is) override=0
Load the level data (i.e. name, path, etc. e.g. from the .tnz file)
void saveData (TOStream &os) override=0
Save the level data (i.e. name, path, etc. e.g. to the .tnz file)
virtual void load ()=0
Load the level content from the associated path.
virtual void save ()=0
Save the level content to the associated path.
HookSet * getHookSet () const
virtual void setDirtyFlag (bool on)
Mark the level as "modified".
Public Member Functions inherited from TSmartObject
TSmartObject (ClassCode classCode)
void addRef ()
void release ()
TINT32 getRefCount () const
Public Member Functions inherited from TPersist
virtual void loadData (TIStream &is)=0
virtual void saveData (TOStream &os)=0
std::string getStreamTag () const
virtual const TPersistDeclaration * getDeclaration () const =0
Static Public Member Functions
static void copyFiles (const TFilePath &dst, const TFilePath &src)
Copy files from src to dst.
static void renameFiles (const TFilePath &dst, const TFilePath &src)
Rename files from src to dst.
static void removeFiles (const TFilePath &fp)
Remove files at fp.
static void getFiles (const TFilePath &fp, TFilePathSet &fpset)
Get the auxiliary files list: hooks, tpl, etc.
static TFilePath getHookPath (const TFilePath &levelPath)
static QStringList getHookFiles (const TFilePath &decodedLevelPath)
Returns the list of existing hook files associated to the specified level, sorted by modification date (last modified at front). The list stores local paths<\I> relative to decodedLevelPath.getParentDir().
static TFilePath getExistingHookFile (const TFilePath &decodedLevelPath)
Returns the path of the newest existing hook file associated to the specified decoded level path - or an empty path if none was found.
static void setCompatibilityMasks (int writeMask, int neededMask, int forbiddenMask)
Static Public Member Functions inherited from TSmartObject
static TINT32 getInstanceCount (ClassCode code)
Static Public Member Functions inherited from TPersist
static void declare (CreateProc *)
static TPersist * create (const std::string &name)
Static Public Attributes
static bool m_rasterizePli = false
static bool m_fillFullColorRaster = false
Additional Inherited Members
Protected Member Functions inherited from TXshLevel
void updateShortName ()
create shortname from the level name
Protected Attributes inherited from TXshLevel
std::wstring m_name
std::wstring m_shortName
int m_type
HookSet * m_hookSet
ToonzScene * m_scene
Detailed Description
The TXshLevel specialization for image levels.
Todo:
Substitute m_frames with a sorted vector or a boost flat_set.
Member Enumeration Documentation
FrameStatusBit
enum TXshSimpleLevel::FrameStatusBit
Describes a level's frame status.
Level frames may have special properties depending on the level type they are part of.
See also
TXshSimpleLevel::getFrameStatus() and setFrameStatus() for further details.
Enumerator
Normal
Frame has no special status.
Scanned
A fullcolor frame (only tlv levels).
Cleanupped
A cleanupped frame (only tlv levels).
CleanupPreview
A cleanup preview (only fullcolor levels).
  { Normal         = 0x0,
    Scanned        = 0x1,
    Cleanupped     = 0x2,
    CleanupPreview = 0x4
  };
Constructor & Destructor Documentation
TXshSimpleLevel()
TXshSimpleLevel::TXshSimpleLevel (const std::wstring & name = std::wstring())
Constructs a TXshSimpleLevel with a name.
    : TXshLevel(m_classCode, name)
    , m_properties(new LevelProperties)
    , m_palette(0)
    , m_idBase(std::to_string(idBaseCode++))
    , m_editableRangeUserInfo(L"")
    , m_isSubsequence(false)
    , m_16BitChannelLevel(false)
    , m_isReadOnly(false)
    , m_temporaryHookMerged(false) {}
Referenced by save().
~TXshSimpleLevel()
TXshSimpleLevel::~TXshSimpleLevel ()
{
  clearFrames();
  if (m_palette) m_palette->release();
}
Member Function Documentation
clearEditableRange()
void TXshSimpleLevel::clearEditableRange ()
{
  m_editableRange.clear();
  m_editableRangeUserInfo = L"";
}
clearFrames()
void TXshSimpleLevel::clearFrames ()
{
  ImageManager *im = ImageManager::instance();
  TImageCache *ic  = TImageCache::instance();
  // Unbind frames
  FramesSet::iterator ft, fEnd = m_frames.end();
  for (ft = m_frames.begin(); ft != fEnd; ++ft) {
    im->unbind(getImageId(*ft, Scanned));
    im->unbind(getImageId(*ft, Cleanupped));
    im->unbind(getImageId(*ft, CleanupPreview));
    // remove icon cache as well
    ic->remove(getIconId(*ft, Normal));
    ic->remove(getIconId(*ft, Scanned));
    ic->remove(getIconId(*ft, CleanupPreview));
    if (m_type == PLI_XSHLEVEL) im->unbind(rasterized(getImageId(*ft)));
    if (m_type == OVL_XSHLEVEL || m_type == TZI_XSHLEVEL)
      im->unbind(filled(getImageId(*ft)));
    texture_utils::invalidateTexture(this, *ft);
  }
  // Clear level
  m_frames.clear();
  m_editableRange.clear();
  m_editableRangeUserInfo.clear();
  m_renumberTable.clear();
  m_framesStatus.clear();
}
clonePropertiesFrom()
void TXshSimpleLevel::clonePropertiesFrom (const TXshSimpleLevel * oldSl)
{
  m_properties->setImageDpi(
      oldSl->m_properties
          ->getImageDpi());  // Watch out - may change dpi policy!
  m_properties->setDpi(oldSl->m_properties->getDpi());
  m_properties->setDpiPolicy(oldSl->m_properties->getDpiPolicy());
  m_properties->setImageRes(oldSl->m_properties->getImageRes());
  m_properties->setBpp(oldSl->m_properties->getBpp());
  m_properties->setSubsampling(oldSl->m_properties->getSubsampling());
}
copyFiles()
void TXshSimpleLevel::copyFiles (const TFilePath & dst, const TFilePath & src) static
Copy files from src to dst.
{
  if (dst == src) return;
  TSystem::touchParentDir(dst);
  TSystem::copyFileOrLevel_throw(dst, src);
  if (dst.getType() == "tlv") {
    // Copio la palette del livello
    TFilePath srcPltPath =
        src.getParentDir() + TFilePath(src.getWideName() + L".tpl");
    if (TFileStatus(srcPltPath).doesExist())
      TSystem::copyFile(
          dst.getParentDir() + TFilePath(dst.getWideName() + L".tpl"),
          srcPltPath, true);
  }
  if (dst.getType() == "tzp" || dst.getType() == "tzu") {
    // Copio la palette del livello
    TFilePath srcPltPath =
        src.getParentDir() + TFilePath(src.getWideName() + L".plt");
    if (TFileStatus(srcPltPath).doesExist())
      TSystem::copyFile(
          dst.getParentDir() + TFilePath(dst.getWideName() + L".plt"),
          srcPltPath, true);
  }
  const TFilePath &srcHookFile = TXshSimpleLevel::getExistingHookFile(src);
  if (!srcHookFile.isEmpty()) {
    const TFilePath &dstHookFile = getHookPath(dst);
    TSystem::copyFile(dstHookFile, srcHookFile, true);
  }
  TFilePath files = src.getParentDir() + (src.getName() + "_files");
  if (TFileStatus(files).doesExist() && TFileStatus(files).isDirectory())
    TSystem::copyDir(dst.getParentDir() + (src.getName() + "_files"), files);
}
References getExistingHookFile(), getHookPath(), TFilePath::getName(), TFilePath::getParentDir(), and TFilePath::getType().
Referenced by SceneLevel::save(), and save().
createEmptyFrame()
TImageP TXshSimpleLevel::createEmptyFrame ()
and assigns the specified level path.
{
  // In case this is the first frame to be created in this level (i.e. the level
  // file was missing when loading resources) initialize the level in the same
  // manner as createNewLevel() in order to avoid crash. This can be happened if
  // the level was not saved after creating and being placed in the xsheet.
  if (isEmpty()) {
    if (!getPalette()) initializePalette();
    initializeResolutionAndDpi();
  }
  TImageP result;
  switch (m_type) {
  case PLI_XSHLEVEL:
    result = new TVectorImage;
    break;
  case MESH_XSHLEVEL:
    assert(false);  // Not implemented yet
    break;
  default: {
    // normally the image must have the level->getProperties()->getImageDpi().
    // if this value is missing (for some reason - can this happen, ever?) then
    // we use the getDpi() (that is the current dpi, e.g. cameraDpi or
    // customDpi).
    TPointD dpi = getProperties()->getImageDpi();
    /*--
    tgatlvconvertInsert Paste
    DPI
    --*/
    // if(dpi.x==0.0 || dpi.y==0.0)
    //  dpi = getProperties()->getDpi();
    TDimension res = getProperties()->getImageRes();
    if (m_type == TZP_XSHLEVEL) {
      TRasterCM32P raster(res);
      raster->fill(TPixelCM32());
      TToonzImageP ti(raster, TRect());
      ti->setDpi(dpi.x, dpi.y);
      ti->setSavebox(TRect(0, 0, res.lx - 1, res.ly - 1));
      result = ti;
    } else {
      TRaster32P raster(res);
      raster->fill(TPixel32(0, 0, 0, 0));
      TRasterImageP ri(raster);
      ri->setDpi(dpi.x, dpi.y);
      result = ri;
    }
    break;
  }
  }
  return result;
}
References LevelProperties::getImageDpi(), LevelProperties::getImageRes(), getPalette(), getProperties(), isEmpty(), and TXshLevel::m_type.
Referenced by TTool::touchImage().
eraseFrame()
void TXshSimpleLevel::eraseFrame (const TFrameId & fid)
{
  FramesSet::iterator ft = m_frames.find(fid);
  if (ft == m_frames.end()) return;
  // Erase the corresponding entry in the renumber table
  std::map<TFrameId, TFrameId>::iterator rt, rEnd(m_renumberTable.end());
  for (rt = m_renumberTable.begin(); rt != rEnd; ++rt) {
    if (rt->second == fid) {
      m_renumberTable.erase(rt->first);
      break;
    }
  }
  m_frames.erase(ft);
  getHookSet()->eraseFrame(fid);
  ImageManager *im = ImageManager::instance();
  TImageCache *ic  = TImageCache::instance();
  {
    im->unbind(getImageId(fid, Normal));
    im->unbind(getImageId(fid, Scanned));
    im->unbind(getImageId(fid, CleanupPreview));
    // remove icon cache as well
    ic->remove(getIconId(fid, Normal));
    ic->remove(getIconId(fid, Scanned));
    ic->remove(getIconId(fid, CleanupPreview));
    if (m_type == PLI_XSHLEVEL) im->unbind(rasterized(getImageId(fid)));
    if (m_type == OVL_XSHLEVEL || m_type == TZI_XSHLEVEL)
      im->unbind(filled(getImageId(fid)));
    texture_utils::invalidateTexture(this, fid);
  }
}
fid2index()
int TXshSimpleLevel::fid2index (const TFrameId & fid) const
an invalid frame otherwise.
Returns the frame index corresponding to the specified
{
  FramesSet::const_iterator ft = m_frames.find(fid);
  return (ft != m_frames.end()) ? std::distance(m_frames.begin(), ft)
                                :  // Note: flat_set has random access
             -1;                   // iterators, so this is FAST
}
getBBox()
TRectD TXshSimpleLevel::getBBox (const TFrameId & fid) const
Returns the bbox for the level's fid, specified in standard inch coordinates (which are different from Toonz's standard world coordinates, by a Stage::inch factor).
{
  TRectD bbox;
  double dpiX = Stage::inch, dpiY = dpiX;
  // Get the frame bbox in image coordinates
  switch (getType()) {
  case PLI_XSHLEVEL:
  case MESH_XSHLEVEL: {
    // Load the image and extract its bbox forcibly
    TImageP img = getFrame(fid, false);
    if (!img) return TRectD();
    bbox = img->getBBox();
    if (TMeshImageP mi = img) mi->getDpi(dpiX, dpiY);
    break;
  }
  default: {
    // Raster case: retrieve the image info from the ImageManager
    const std::string &imageId = getImageId(fid);
    const TImageInfo *info =
        ImageManager::instance()->getInfo(imageId, ImageManager::none, 0);
    if (!info) return TRectD();
    bbox = TRectD(TPointD(info->m_x0, info->m_y0),
                  TPointD(info->m_x1, info->m_y1)) -
           0.5 * TPointD(info->m_lx, info->m_ly);
    if (info->m_dpix > 0.0 && info->m_dpiy > 0.0)
      dpiX = info->m_dpix, dpiY = info->m_dpiy;
    break;
  }
  }
  // Get the frame's dpi and traduce the bbox to inch coordinates
  return TScale(1.0 / dpiX, 1.0 / dpiY) * bbox;
}
References TImage::getBBox(), ImageManager::getInfo(), TXshLevel::getType(), and Stage::inch.
Referenced by TXsheet::getBBox().
getContentHistory() [1/2]
TContentHistory * TXshSimpleLevel::getContentHistory () inline
{ return m_contentHistory.get(); }
getContentHistory() [2/2]
const TContentHistory * TXshSimpleLevel::getContentHistory () const inline
note gets the contentHistory. can be 0
{
    return m_contentHistory.get();
  }
Referenced by LevelUpdater::open(), and touchFrame().
getDirtyFlag()
bool TXshSimpleLevel::getDirtyFlag () const
{
  return m_properties->getDirtyFlag();
}
getDpi()
TPointD TXshSimpleLevel::getDpi (const TFrameId & fid = TFrameId::NO_FRAME, int frameStatus = -1)
{
  TPointD dpi;
  if (m_properties->getDpiPolicy() == LevelProperties::DP_ImageDpi)
    dpi = getImageDpi(fid, frameStatus);
  else
    dpi = m_properties->getDpi();
  return dpi;
}
getEditableFileName()
std::wstring TXshSimpleLevel::getEditableFileName ()
{
#ifdef MACOSX
  std::wstring fileName = L"." + m_path.getWideName();
#else
  std::wstring fileName = m_path.getWideName();
#endif
  fileName += L"_" + m_editableRangeUserInfo;
  int from, to;
  getIndexesRangefromFids(this, m_editableRange, from, to);
  if (from == -1 && to == -1) return L"";
  fileName += L"_" + std::to_wstring(from + 1) + L"-" + std::to_wstring(to + 1);
  return fileName;
}
getEditableRange()
std::set< TFrameId > TXshSimpleLevel::getEditableRange ()
Returns the set of editable frames.
{
  return m_editableRange;
}
getExistingHookFile()
TFilePath TXshSimpleLevel::getExistingHookFile (const TFilePath & decodedLevelPath) static
Returns the path of the newest existing hook file associated to the specified decoded level path - or an empty path if none was found.
Note
In case there are more than one hook file (ie files from older Toonz version), the latest file version is used.
{
  static const int pCount              = 3;
  static const QRegExp pattern[pCount] = {
      // Prioritized in this order
      QRegExp(".*\\.\\.?.+\\.xml$"),  // whatever.(.)ext.xml
      QRegExp(".*\\.xml$"),           // whatever.xml
      QRegExp(".*\\.\\.?xml$")        // whatever.(.)xml
  };
  struct locals {
    static inline int getPattern(const QString &fp) {
      for (int p = 0; p != pCount; ++p)
        if (pattern[p].exactMatch(fp)) return p;
      return -1;
    }
  };  // locals
  const QStringList &hookFiles = getHookFiles(decodedLevelPath);
  if (hookFiles.empty()) return TFilePath();
  // Return the hook file with the most recent (smallest) identified
  // regexp pattern
  int fPattern, p = pCount, h = -1;
  int f, fCount = hookFiles.size();
  for (f = 0; f != fCount; ++f) {
    fPattern = locals::getPattern(hookFiles[f]);
    if (fPattern < p) p = fPattern, h = f;
  }
  assert(h >= 0);
  return (h < 0) ? TFilePath()
                 : decodedLevelPath.getParentDir() +
                       TFilePath(hookFiles[h].toStdWString());
}
References getHookFiles(), and TFilePath::getParentDir().
Referenced by copyFiles(), getFiles(), load(), and renameFiles().
getFids() [1/2]
std::vector< TFrameId > TXshSimpleLevel::getFids () const
Returns a copy of the level's frame ids.
Each level frame have a corresponding image retrievable with the getFrame() method and similar.
Remarks
Consider using functions getFrameCount() and getFrameId() to avoid a container copy.
{
  return std::vector<TFrameId>(m_frames.begin(), m_frames.end());
}
Referenced by VectorizerPopup::apply(), ReplaceParentDirectoryPopup::execute(), RGBPickerTool::onImageChanged(), LevelUpdater::open(), renumber(), TTool::touchImage(), and DragSelectionTool::VectorDeformTool::transformWholeLevel().
getFids() [2/2]
void TXshSimpleLevel::getFids (std::vector< TFrameId > & fids) const override virtual
Copies fids() into fids.
Deprecated:
Use
Reimplemented from TXshLevel.
{
  fids.assign(m_frames.begin(), m_frames.end());
}
getFiles()
void TXshSimpleLevel::getFiles (const TFilePath & fp, TFilePathSet & fpset) static
Get the auxiliary files list: hooks, tpl, etc.
{
  if (fp.getType() == "tlv") {
    TFilePath tpl = fp.withType("tpl");
    if (TFileStatus(tpl).doesExist()) fpset.push_back(tpl);
  }
  // Store the hooks file if any (NOTE: there could be more than one hooks
  // file. I'm retaining the behavior I've seen, but was this really intended?
  // Shouldn't we return ALL the hooks files?)
  const TFilePath &hookFile = getExistingHookFile(fp);
  if (!hookFile.isEmpty()) fpset.push_back(hookFile);
  // Needed for TAB Manga & Kids and not used in Toonz
  // TFilePath files = fp.getParentDir() + (fp.getName() + "_files");
  // if(TFileStatus(files).doesExist() && TFileStatus(files).isDirectory())
  //  TSystem::rmDirTree(files);
}
References getExistingHookFile(), TFilePath::getType(), and TFilePath::withType().
Referenced by save().
getFirstFid()
TFrameId TXshSimpleLevel::getFirstFid () const
the return valued variation instead. Returns the first level frame's id; roughly equivalent to index2fid(0).
{
  return !isEmpty() ? *m_frames.begin() : TFrameId(TFrameId::NO_FRAME);
}
References isEmpty().
Referenced by load(), and Filmstrip::updateChooseLevelComboItems().
getFrame() [1/2]
TImageP TXshSimpleLevel::getFrame (const TFrameId & fid, bool toBeModified) const inline
{
    return getFrame(
        fid, toBeModified ? ImageManager::toBeModified : ImageManager::none, 0);
  }
getFrame() [2/2]
TImageP TXshSimpleLevel::getFrame (const TFrameId & fid, UCHAR imgManagerParamsMask, int subsampling) const
{
  assert(m_type != UNKNOWN_XSHLEVEL);
  // If the required frame is not in range, quit
  if (m_frames.count(fid) == 0) return TImageP();
  const std::string &imgId = getImageId(fid);
  ImageLoader::BuildExtData extData(this, fid, subsampling);
  TImageP img = ImageManager::instance()->getImage(imgId, imFlags, &extData);
  if (imFlags & ImageManager::toBeModified) {
    // The image will be modified. Perform any related invalidation.
    texture_utils::invalidateTexture(
        this, fid);  // We must rebuild associated textures
  }
  return img;
}
getFrameCount()
int TXshSimpleLevel::getFrameCount () const inline override virtual
Returns the level's frames count.
Reimplemented from TXshLevel.
Referenced by IoCmd::exportLevel(), FlipBook::Level::getIndexesCount(), texture_utils::invalidateTextures(), setEditableRange(), FlipBook::setLevel(), Vectorizer::setLevel(), and TTool::touchImage().
getFrameIcon()
TImageP TXshSimpleLevel::getFrameIcon (const TFrameId & fid) const
{
  assert(m_type != UNKNOWN_XSHLEVEL);
  if (m_frames.count(fid) == 0) return TImageP();
  // NOTE: Icons caching is DISABLED at this stage. It is now responsibility of
  // ToonzQt's IconGenerator class.
  ImageLoader::BuildExtData extData(this, fid);
  extData.m_subs = 1, extData.m_icon = true;
  const std::string &imgId = getImageId(fid);
  TImageP img              = ImageManager::instance()->getImage(
      imgId, ImageManager::dontPutInCache, &extData);
  TToonzImageP timg = (TToonzImageP)img;
  if (timg && m_palette) timg->setPalette(m_palette);
  return img;
}
getFrameId()
const TFrameId & TXshSimpleLevel::getFrameId (int index) const
Returns the frame id at specified index.
Unlike function index2fid(), getFrameId() asserts beyond current frames count.
{
  return *(m_frames.begin() += index);
}
Referenced by PaletteCmd::eraseStyles(), TXsheet::incrementCells(), and texture_utils::invalidateTextures().
getFrameInfo()
TImageInfo * TXshSimpleLevel::getFrameInfo (const TFrameId & fid, bool toBeModified)
{
  assert(m_type != UNKNOWN_XSHLEVEL);
  // If the required frame is not in range, quit
  if (m_frames.count(fid) == 0) return 0;
  const std::string &imgId = getImageId(fid);
  TImageInfo *info = ImageManager::instance()->getInfo(
      imgId, toBeModified ? ImageManager::toBeModified : ImageManager::none, 0);
  return info;
}
getFrameStatus()
int TXshSimpleLevel::getFrameStatus (const TFrameId & fid) const
{
  std::map<TFrameId, int>::const_iterator it = m_framesStatus.find(fid);
  return (it != m_framesStatus.end()) ? it->second : Normal;
}
getFrameToCleanup()
TRasterImageP TXshSimpleLevel::getFrameToCleanup (const TFrameId & fid, bool toBeLineProcessed) const
{
  assert(m_type != UNKNOWN_XSHLEVEL);
  FramesSet::const_iterator ft = m_frames.find(fid);
  if (ft == m_frames.end()) return TImageP();
  bool flag           = (m_scannedPath != TFilePath());
  std::string imageId = getImageId(fid, flag ? Scanned : 0);
  ImageLoader::BuildExtData extData(this, fid, 1);
  UCHAR imFlags = ImageManager::dontPutInCache;
  // if lines are not processed, obtain the original sampled image
  if (!toBeLineProcessed) imFlags |= ImageManager::is64bitEnabled;
  TRasterImageP img =
      ImageManager::instance()->getImage(imageId, imFlags, &extData);
  if (!img) return img;
  double x_dpi, y_dpi;
  img->getDpi(x_dpi, y_dpi);
  if (!x_dpi && !y_dpi) {
    TPointD dpi = m_properties->getDpi();
    img->setDpi(dpi.x, dpi.y);
  }
  return img;
}
getFullsampledFrame()
TImageP TXshSimpleLevel::getFullsampledFrame (const TFrameId & fid, UCHAR imgManagerParamsMask) const
{
  assert(m_type != UNKNOWN_XSHLEVEL);
  FramesSet::const_iterator it = m_frames.find(fid);
  if (it == m_frames.end()) return TRasterImageP();
  std::string imageId = getImageId(fid);
  ImageLoader::BuildExtData extData(this, fid, 1);
  TImageP img = ImageManager::instance()->getImage(imageId, imFlags, &extData);
  if (imFlags & ImageManager::toBeModified) {
    // The image will be modified. Perform any related invalidation.
    texture_utils::invalidateTexture(
        this, fid);  // We must rebuild associated textures
  }
  return img;
}
getHookFiles()
QStringList TXshSimpleLevel::getHookFiles (const TFilePath & decodedLevelPath) static
Returns the list of existing hook files associated to the specified level, sorted by modification date (last modified at front). The list stores local paths<\I> relative to decodedLevelPath.getParentDir().
Note
A level may have multiple hook files if the hook set was edited with older Toonz versions. Use this function if you need to access all of them. Only the latest file format is considered when loading a level.
{
  const TFilePath &dirPath = decodedLevelPath.getParentDir();
  QDir levelDir(QString::fromStdWString(dirPath.getWideString()));
  QStringList hookFileFilter(
      QString::fromStdWString(  // We have to scan for files of the
          decodedLevelPath.getWideName() +
          L"_hooks*.xml"));   // form  levelName_hooks*.xml  to
                              // retain backward compatibility
  return levelDir.entryList(  //
      hookFileFilter,
      QDir::Files | QDir::NoDotAndDotDot,  // Observe that we cleverly sort by
      QDir::Time);                         // mod date :)
}
References TFilePath::getParentDir().
Referenced by getExistingHookFile(), and removeFiles().
getHookPath()
TFilePath TXshSimpleLevel::getHookPath (const TFilePath & levelPath) static
Translates a level path into the corresponding hook path (no check for the existence of said hook file).
{
  // Translates:  levelName..ext  into  levelName_hooks..ext.xml
  //              levelName.ext   into  levelName_hooks.ext.xml
  // Observe that retaining the original level extension IS IMPORTANT, as it
  // ensures
  // the UNICITY of the association between a level path and its hook path (ie
  // levels  test..png  and  test..tif  have separate hook files).
  return TFilePath(path.withName(path.getName() + "_hooks").getWideString() +
                   L".xml");
}
References TFilePath::getName(), and TFilePath::withName().
Referenced by copyFiles(), renameFiles(), and setEditableRange().
getIconId() [1/2]
std::string TXshSimpleLevel::getIconId (const TFrameId & fid, const TDimension & size) const
{
  return getImageId(fid) + ":" + std::to_string(size.lx) + "x" +
         std::to_string(size.ly);
}
getIconId() [2/2]
std::string TXshSimpleLevel::getIconId (const TFrameId & fid, int frameStatus = -1) const
{
  return "icon:" + getImageId(fid, frameStatus);
}
getImageDpi()
TPointD TXshSimpleLevel::getImageDpi (const TFrameId & fid = TFrameId::NO_FRAME, int frameStatus = -1)
{
  if (isEmpty() || getType() == PLI_XSHLEVEL) return TPointD();
  const TFrameId &theFid =
      (fid == TFrameId::NO_FRAME || !isFid(fid)) ? getFirstFid() : fid;
  const std::string &imageId = getImageId(theFid, frameStatus);
  const TImageInfo *imageInfo =
      ImageManager::instance()->getInfo(imageId, ImageManager::none, 0);
  if (!imageInfo) return TPointD();
  return TPointD(imageInfo->m_dpix, imageInfo->m_dpiy);
}
getImageId()
std::string TXshSimpleLevel::getImageId (const TFrameId & fid, int frameStatus = -1) const
{
  if (frameStatus < 0) frameStatus = getFrameStatus(fid);
  std::string prefix = "L";
  if (frameStatus & CleanupPreview)
    prefix = "P";
  else if ((frameStatus & (Scanned | Cleanupped)) == Scanned)
    prefix = "S";
  std::string imageId = m_idBase + "_" + prefix + fid.expand();
  return imageId;
}
getImageSubsampling()
int TXshSimpleLevel::getImageSubsampling (const TFrameId & fid) const
{
  if (isEmpty() || getType() == PLI_XSHLEVEL) return 1;
  TImageP img = TImageCache::instance()->get(getImageId(fid), false);
  if (!img) return 1;
  if (TRasterImageP ri = img) return ri->getSubsampling();
  if (TToonzImageP ti = img) return ti->getSubsampling();
  return 1;
}
getLastFid()
TFrameId TXshSimpleLevel::getLastFid () const
Returns the last level frame's id; roughly equivalent to index2fid(getFrameCount()-1).
{
  return !isEmpty() ? *m_frames.rbegin() : TFrameId(TFrameId::NO_FRAME);
}
References isEmpty().
getPalette()
TPalette * TXshSimpleLevel::getPalette () const
Returns a pointer to the shared level palette.
{ return m_palette; }
Referenced by ImageLoader::build(), createEmptyFrame(), StudioPaletteTreeViewer::dropEvent(), TXshCell::getPalette(), TImageReaderSvg::load(), load(), StylePickerTool::onImageChanged(), ToonzImageIconRenderer::run(), SceneLevel::save(), save(), SceneLevel::SceneLevel(), and Vectorizer::setLevel().
getPath()
TFilePath TXshSimpleLevel::getPath () const inline override virtual
Return the file path associated with the level.
Reimplemented from TXshLevel.
{ return m_path; }
Referenced by ToonzScene::createNewLevel(), SaveLevelAsPopup::execute(), CleanupSettingsModel::getClnPath(), CleanupSettingsModel::getInputPath(), VectorizerPopup::isLevelToConvert(), ToonzScene::loadTnzFile(), LevelUpdater::open(), SceneLevel::SceneLevel(), and Vectorizer::setLevel().
getProperties()
LevelProperties * TXshSimpleLevel::getProperties () const inline
< Returns a pointer to the owned level properties.
  {
    return m_properties.get();
  }
Referenced by createEmptyFrame(), load(), ToonzScene::loadLevel(), Stage::RasterPainter::onRasterImage(), LevelUpdater::open(), SceneLevel::save(), save(), saveData(), and Filmstrip::updateChooseLevelComboItems().
getResolution()
TDimension TXshSimpleLevel::getResolution ()
{
  if (isEmpty() || getType() == PLI_XSHLEVEL) return TDimension();
  return m_properties->getImageRes();
}
getScannedPath()
TFilePath TXshSimpleLevel::getScannedPath () const inline
{ return m_scannedPath; }
getSimpleLevel()
TXshSimpleLevel * TXshSimpleLevel::getSimpleLevel () inline override virtual
Reimplemented for TXshLevel.
Reimplemented from TXshLevel.
Referenced by VectorizerPopup::apply(), ReplaceParentDirectoryPopup::execute(), TTool::getImageCell(), and Filmstrip::updateChooseLevelComboItems().
guessIndex()
int TXshSimpleLevel::guessIndex (const TFrameId & fid) const
frame id, or -1 if not found.
{
  if (m_frames.empty()) return 0;  // no frames, return 0 (by definition)
  FramesSet::const_iterator ft = m_frames.lower_bound(fid);
  if (ft == m_frames.end()) {
    const TFrameId &maxFid = *m_frames.rbegin();
    assert(fid > maxFid);
    // fid not in the table, but greater than the last one.
    // return a suitable index. (e.g. frames are 1,3,5,7; fid2index(11) should
    // return index=5)
    int step = guessStep();
    int i    = (fid.getNumber() - maxFid.getNumber()) / step;
    return m_frames.size() - 1 + i;
  } else
    return std::distance(m_frames.begin(), ft);
}
References guessStep().
Referenced by StageBuilder::addSimpleLevelFrame(), HookTool::draw(), and ToonzImageIconRenderer::run().
guessStep()
int TXshSimpleLevel::guessStep () const
Analyzes the level's frames table and returns the alleged entries step
ie the distance from each entry to the next.
{
  int frameCount = m_frames.size();
  if (frameCount < 2)
    return 1;  // un livello con zero o un frame ha per def. step=1
  FramesSet::const_iterator ft = m_frames.begin();
  TFrameId firstFid = *ft++, secondFid = *ft++;
  if (!firstFid.getLetter().isEmpty() || !secondFid.getLetter().isEmpty())
    return 1;
  int step = secondFid.getNumber() - firstFid.getNumber();
  if (step == 1) return 1;
  // controllo subito se lo step vale per l'ultimo frame
  // (cerco di limitare il numero di volte in cui devo controllare tutta la
  // lista)
  TFrameId lastFid = *m_frames.rbegin();
  if (!lastFid.getLetter().isEmpty()) return 1;
  if (lastFid.getNumber() != firstFid.getNumber() + step * (frameCount - 1))
    return 1;
  for (int i = 2; ft != m_frames.end(); ++ft, ++i) {
    const TFrameId &fid = *ft;
    if (!fid.getLetter().isEmpty()) return 1;
    if (fid.getNumber() != firstFid.getNumber() + step * i) return 1;
  }
  return step;
}
Referenced by guessIndex(), and index2fid().
index2fid()
TFrameId TXshSimpleLevel::index2fid (int index) const
Function index2fid() attempts guessing frame ids for frame indexes beyond current frames count. See function guessStep() for further details.
Returns a frame id corresponding to the specified frame index, or
{
  if (index < 0) return TFrameId(-2);
  int frameCount = m_frames.size();
  if (frameCount == 0) return TFrameId(1);  // o_o?
  if (index < frameCount) {
    FramesSet::const_iterator ft = m_frames.begin();
    std::advance(ft, index);
    return *ft;
  } else {
    int step        = guessStep();
    TFrameId maxFid = *m_frames.rbegin();
    int d           = step * (index - frameCount + 1);
    return TFrameId(maxFid.getNumber() + d);
  }
}
References guessStep().
Referenced by StageBuilder::addSimpleLevelFrame(), HookTool::draw(), IoCmd::exportLevel(), setEditableRange(), and TTool::touchImage().
initializePalette()
void TXshSimpleLevel::initializePalette ()
{
  assert(getScene());
  int type = getType();
  if (type == TZP_XSHLEVEL || type == PLI_XSHLEVEL) setPalette(new TPalette());
  if (type == OVL_XSHLEVEL)
    setPalette(FullColorPalette::instance()->getPalette(getScene()));
  TPalette *palette = getPalette();
  if (palette && type != OVL_XSHLEVEL) {
    palette->setPaletteName(getName());
    palette->setDirtyFlag(true);
  }
}
initializeResolutionAndDpi()
void TXshSimpleLevel::initializeResolutionAndDpi (const TDimension & dim = TDimension(), double dpi = 0)
{
  assert(getScene());
  if (getProperties()->getImageRes() != TDimension() &&
      getProperties()->getDpi() != TPointD())
    return;
  double dpiY = dpi;
  getProperties()->setDpiPolicy(LevelProperties::DP_ImageDpi);
  if (dim == TDimension()) {
    double w, h;
    Preferences *pref = Preferences::instance();
    if (pref->isNewLevelSizeToCameraSizeEnabled()) {
      TDimensionD camSize = getScene()->getCurrentCamera()->getSize();
      w                   = camSize.lx;
      h                   = camSize.ly;
      getProperties()->setDpiPolicy(LevelProperties::DP_CustomDpi);
      dpi  = getScene()->getCurrentCamera()->getDpi().x;
      dpiY = getScene()->getCurrentCamera()->getDpi().y;
    } else {
      w    = pref->getDefLevelWidth();
      h    = pref->getDefLevelHeight();
      dpi  = pref->getDefLevelDpi();
      dpiY = dpi;
    }
    getProperties()->setImageRes(TDimension(tround(w * dpi), tround(h * dpiY)));
  } else
    getProperties()->setImageRes(dim);
  getProperties()->setImageDpi(TPointD(dpi, dpiY));
  getProperties()->setDpi(dpi);
}
invalidateFrame()
void TXshSimpleLevel::invalidateFrame (const TFrameId & fid)
{
  std::string id = getImageId(fid);
  ImageManager::instance()->invalidate(id);
}
invalidateFrames()
void TXshSimpleLevel::invalidateFrames ()
{
  FramesSet::iterator ft, fEnd = m_frames.end();
  for (ft = m_frames.begin(); ft != fEnd; ++ft)
    ImageManager::instance()->invalidate(getImageId(*ft));
}
is16BitChannelLevel()
bool TXshSimpleLevel::is16BitChannelLevel () const inline
{
    return getType() == OVL_XSHLEVEL && m_16BitChannelLevel;
  }
isEmpty()
bool TXshSimpleLevel::isEmpty () const inline override virtual
Returns whether the level is empty.
Reimplemented from TXshLevel.
Referenced by createEmptyFrame(), IoCmd::exportLevel(), getFirstFid(), getLastFid(), and TTool::touchImage().
isFid()
bool TXshSimpleLevel::isFid (const TFrameId & fid) const
Returns whether a given frameId is in the level.
{
  return m_frames.count(fid);
}
Referenced by RasterImageIconRenderer::run(), ToonzImageIconRenderer::run(), and TTool::touchImage().
isFrameReadOnly()
bool TXshSimpleLevel::isFrameReadOnly (TFrameId fid)
{
  // For Raster and mesh files, check to see if files are marked as read-only at
  // the OS level
  if (getType() == OVL_XSHLEVEL || getType() == TZI_XSHLEVEL ||
      getType() == MESH_XSHLEVEL) {
    if (getProperties()->isStopMotionLevel()) return true;
    TFilePath fullPath   = getScene()->decodeFilePath(m_path);
    std::string fileType = fullPath.getType();
    if (fileType == "psd" || fileType == "gif" || fileType == "mp4" ||
        fileType == "webm")
      return true;
    TFilePath path =
        fullPath.getDots() == ".." ? fullPath.withFrame(fid) : fullPath;
    if (!TSystem::doesExistFileOrLevel(path)) return false;
    TFileStatus fs(path);
    return !fs.isWritable();
  }
  // If Level is marked read only, check for editable frames
  if (m_isReadOnly && !m_editableRange.empty() &&
      m_editableRange.count(fid) != 0)
    return false;
  return m_isReadOnly;
}
isReadOnly()
bool TXshSimpleLevel::isReadOnly () const inline
{ return m_isReadOnly; }
isSubsequence()
bool TXshSimpleLevel::isSubsequence () const inline
{ return m_isSubsequence; }
load() [1/2]
void TXshSimpleLevel::load () override virtual
Loads the level from disk, translating encoded level paths relative to the level's scene path.
Implements TXshLevel.
{
  getProperties()->setCreator("");
  QString creator;
  assert(getScene());
  if (!getScene()) return;
  m_isSubsequence = loadingLevelRange.isEnabled();
  TFilePath checkpath = getScene()->decodeFilePath(m_path);
  std::string type    = checkpath.getType();
  if (m_scannedPath != TFilePath()) {
    getProperties()->setDirtyFlag(
        false);  // Level is now supposedly loaded from disk
    static const int ScannedCleanuppedMask = Scanned | Cleanupped;
    TFilePath path = getScene()->decodeFilePath(m_scannedPath);
    if (TSystem::doesExistFileOrLevel(path)) {
      TLevelReaderP lr(path);
      assert(lr);
      TLevelP level = lr->loadInfo();
      if (!checkCreatorString(creator = lr->getCreator()))
        getProperties()->setIsForbidden(true);
      else
        for (TLevel::Iterator it = level->begin(); it != level->end(); it++) {
          TFrameId fid = it->first;
          if (!loadingLevelRange.match(fid)) continue;
          setFrameStatus(
              fid, (getFrameStatus(fid) & ~ScannedCleanuppedMask) | Scanned);
          setFrame(fid, TImageP());
        }
    }
    path = getScene()->decodeFilePath(m_path);
    if (TSystem::doesExistFileOrLevel(path)) {
      TLevelReaderP lr(path);
      assert(lr);
      TLevelP level = lr->loadInfo();
      if (getType() & FULLCOLOR_TYPE)
        setPalette(FullColorPalette::instance()->getPalette(getScene()));
      else
        setPalette(level->getPalette());
      if (!checkCreatorString(creator = lr->getCreator()))
        getProperties()->setIsForbidden(true);
      else
        for (TLevel::Iterator it = level->begin(); it != level->end(); it++) {
          TFrameId fid = it->first;
          if (!loadingLevelRange.match(fid)) continue;
          setFrameStatus(fid, getFrameStatus(fid) | Cleanupped);
          setFrame(fid, TImageP());
        }
      setContentHistory(
          lr->getContentHistory() ? lr->getContentHistory()->clone() : 0);
    }
  } else {
    // Not a scan + cleanup level
    // Loading PSD files via load level command needs to convert layerID in the
    // file path to layer name here. The conversion is not needed on loading
    // scene as the file path loaded from the scene file is already converted.
    if (m_path.getType() == "psd" && !this->getScene()->isLoading())
      m_path = getLevelPathAndSetNameWithPsdLevelName(this);
    TFilePath path = getScene()->decodeFilePath(m_path);
    getProperties()->setDirtyFlag(
        false);  // Level is now supposedly loaded from disk
    TLevelReaderP lr(path);  // May throw
    assert(lr);
    TLevelP level = lr->loadInfo();
    if (level->getFrameCount() > 0) {
      const TImageInfo *info = lr->getImageInfo(level->begin()->first);
      if (info && info->m_samplePerPixel >= 5) {
        QString msg = QString(
                          "Failed to open %1.\nSamples per pixel is more than "
                          "4. It may contain more than one alpha channel.")
                          .arg(QString::fromStdWString(m_path.getWideString()));
        QMessageBox::warning(0, "Image format not supported", msg);
        return;
      }
      if (info) set16BitChannelLevel(info->m_bitsPerSample == 16);
    }
    if ((getType() & FULLCOLOR_TYPE) && !is16BitChannelLevel())
      setPalette(FullColorPalette::instance()->getPalette(getScene()));
    else
      setPalette(level->getPalette());
    if (!checkCreatorString(creator = lr->getCreator()))
      getProperties()->setIsForbidden(true);
    else
      for (TLevel::Iterator it = level->begin(); it != level->end(); it++) {
        m_renumberTable[it->first] = it->first;  // Voglio che la tabella
                                                 // contenga anche i frame che
                                                 // non vengono caricati
        if (!loadingLevelRange.match(it->first)) continue;
        setFrame(it->first, TImageP());
      }
    setContentHistory(lr->getContentHistory() ? lr->getContentHistory()->clone()
                                              : 0);
  }
  getProperties()->setCreator(creator.toStdString());
  loadingLevelRange.reset();
  if (getType() != PLI_XSHLEVEL) {
    if (m_properties->getImageDpi() == TPointD() && !m_frames.empty()) {
      TDimension imageRes(0, 0);
      TPointD imageDpi;
      const TFrameId &firstFid = getFirstFid();
      std::string imageId      = getImageId(firstFid);
      const TImageInfo *imageInfo =
          ImageManager::instance()->getInfo(imageId, ImageManager::none, 0);
      if (imageInfo) {
        imageRes.lx = imageInfo->m_lx;
        imageRes.ly = imageInfo->m_ly;
        imageDpi.x  = imageInfo->m_dpix;
        imageDpi.y  = imageInfo->m_dpiy;
        m_properties->setImageDpi(imageDpi);
        m_properties->setImageRes(imageRes);
        m_properties->setBpp(imageInfo->m_bitsPerSample *
                             imageInfo->m_samplePerPixel);
      }
    }
    setRenumberTable();
  }
  if (getPalette() && StudioPalette::isEnabled())
    StudioPalette::instance()->updateLinkedColors(getPalette());
  TFilePath refImgName;
  if (m_palette) {
    refImgName           = m_palette->getRefImgPath();
    TFilePath refImgPath = refImgName;
    if (refImgName != TFilePath() && TFileStatus(refImgPath).doesExist()) {
      TLevelReaderP lr(refImgPath);
      if (lr) {
        TLevelP level = lr->loadInfo();
        if (level->getFrameCount() > 0) {
          TImageP img = lr->getFrameReader(level->begin()->first)->load();
          if (img && getPalette()) {
            img->setPalette(0);
            getPalette()->setRefImg(img);
            std::vector<TFrameId> fids = getPalette()->getRefLevelFids();
            // in case the fids are specified by user
            if (fids.size() > 0) {
              // check existence of each fid
              auto itr = fids.begin();
              while (itr != fids.end()) {
                bool found = false;
                for (TLevel::Iterator it = level->begin(); it != level->end();
                     ++it) {
                  if (itr->getNumber() == it->first.getNumber()) {
                    found = true;
                    break;
                  }
                }
                if (!found)  // remove the fid if it does not exist in the level
                  itr = fids.erase(itr);
                else
                  itr++;
              }
            }
            // in case the fids are not specified, or all specified fids are
            // absent
            if (fids.size() == 0) {
              for (TLevel::Iterator it = level->begin(); it != level->end();
                   ++it)
                fids.push_back(it->first);
              getPalette()->setRefLevelFids(fids, false);
            } else if (fids.size() != getPalette()->getRefLevelFids().size())
              getPalette()->setRefLevelFids(fids, true);
          }
        }
      }
    }
  }
  // Load hooks
  HookSet *hookSet = getHookSet();
  hookSet->clearHooks();
  const TFilePath &hookFile =
      TXshSimpleLevel::getExistingHookFile(getScene()->decodeFilePath(m_path));
  if (!hookFile.isEmpty()) {
    TIStream is(hookFile);
    std::string tagName;
    try {
      if (is.matchTag(tagName) && tagName == "hooks") hookSet->loadData(is);
    } catch (...) {
    }
  }
  updateReadOnly();
}
References Cleanupped, HookSet::clearHooks(), ToonzScene::decodeFilePath(), getExistingHookFile(), getFirstFid(), TXshLevel::getHookSet(), ImageManager::getInfo(), getPalette(), getProperties(), TPalette::getRefImgPath(), TPalette::getRefLevelFids(), TXshLevel::getScene(), TFilePath::getType(), TXshLevel::getType(), TImageInfo::m_bitsPerSample, TImageInfo::m_dpix, TImageInfo::m_dpiy, TImageInfo::m_lx, TImageInfo::m_ly, TImageInfo::m_samplePerPixel, TIStream::matchTag(), Scanned, setContentHistory(), LevelProperties::setCreator(), LevelProperties::setDirtyFlag(), LevelProperties::setIsForbidden(), TImage::setPalette(), setPalette(), TPalette::setRefImg(), TPalette::setRefLevelFids(), setRenumberTable(), and StudioPalette::updateLinkedColors().
Referenced by ToonzScene::loadLevel(), and SceneLevel::save().
load() [2/2]
void TXshSimpleLevel::load (const std::vector< TFrameId > & fIds)
{
  getProperties()->setCreator("");
  QString creator;
  assert(getScene());
  getProperties()->setDirtyFlag(false);
  m_isSubsequence = loadingLevelRange.isEnabled();
  // non e' un livello scan+cleanup
  TFilePath path = getScene()->decodeFilePath(m_path);
  TLevelReaderP lr(path);
  assert(lr);
  if (!checkCreatorString(creator = lr->getCreator()))
    getProperties()->setIsForbidden(true);
  else {
    if (fIds.size() != 0) {
      for (int i = 0; i < (int)fIds.size(); i++) {
        m_renumberTable[fIds[i]] = fIds[i];
        if (!loadingLevelRange.match(fIds[i])) continue;
        setFrame(fIds[i], TImageP());
      }
      const TImageInfo *info = lr->getImageInfo(fIds[0]);
      if (info) set16BitChannelLevel(info->m_bitsPerSample == 16);
    } else {
      TLevelP level = lr->loadInfo();
      for (TLevel::Iterator it = level->begin(); it != level->end(); it++) {
        m_renumberTable[it->first] = it->first;
        if (!loadingLevelRange.match(it->first)) continue;
        setFrame(it->first, TImageP());
      }
      const TImageInfo *info = lr->getImageInfo(level->begin()->first);
      if (info) set16BitChannelLevel(info->m_bitsPerSample == 16);
    }
    if ((getType() & FULLCOLOR_TYPE) && !is16BitChannelLevel())
      setPalette(FullColorPalette::instance()->getPalette(getScene()));
  }
  setContentHistory(lr->getContentHistory() ? lr->getContentHistory()->clone()
                                            : 0);
  getProperties()->setCreator(creator.toStdString());
  loadingLevelRange.reset();
  if (getType() != PLI_XSHLEVEL) {
    if (m_properties->getImageDpi() == TPointD() && !m_frames.empty()) {
      TDimension imageRes(0, 0);
      TPointD imageDpi;
      std::string imageId = getImageId(getFirstFid());
      const TImageInfo *imageInfo =
          ImageManager::instance()->getInfo(imageId, ImageManager::none, 0);
      if (imageInfo) {
        imageRes.lx = imageInfo->m_lx;
        imageRes.ly = imageInfo->m_ly;
        imageDpi.x  = imageInfo->m_dpix;
        imageDpi.y  = imageInfo->m_dpiy;
        m_properties->setImageDpi(imageDpi);
        m_properties->setImageRes(imageRes);
      }
    }
    setRenumberTable();
  }
}
loadAllIconsAndPutInCache()
void TXshSimpleLevel::loadAllIconsAndPutInCache (bool cacheImagesAsWell)
{
  if (m_type != TZP_XSHLEVEL) return;
  std::vector<TFrameId> fids;
  getFids(fids);
  std::vector<std::string> iconIds;
  for (int i = 0; i < (int)fids.size(); i++) {
    iconIds.push_back(getIconId(fids[i]));
  }
  ImageManager::instance()->loadAllTlvIconsAndPutInCache(this, fids, iconIds,
                                                         cacheImagesAsWell);
}
loadData()
void TXshSimpleLevel::loadData (TIStream & is) override virtual
Load the level data (i.e. name, path, etc. e.g. from the .tnz file)
Implements TXshLevel.
{
  std::string tagName;
  bool flag = false;
  int type = UNKNOWN_XSHLEVEL;
  for (;;) {
    if (is.matchTag(tagName)) {
      if (tagName == "path") {
        is >> m_path;
        is.matchEndTag();
      } else if (tagName == "scannedPath") {
        is >> m_scannedPath;
        is.matchEndTag();
      } else if (tagName == "info") {
        std::string v;
        double xdpi = 0, ydpi = 0;
        int subsampling                      = 1;
        int doPremultiply                    = 0;
        int whiteTransp                      = 0;
        int antialiasSoftness                = 0;
        int isStopMotionLevel                = 0;
        LevelProperties::DpiPolicy dpiPolicy = LevelProperties::DP_ImageDpi;
        if (is.getTagParam("dpix", v)) xdpi = std::stod(v);
        if (is.getTagParam("dpiy", v)) ydpi = std::stod(v);
        if (xdpi != 0 && ydpi != 0) dpiPolicy = LevelProperties::DP_CustomDpi;
        std::string dpiType = is.getTagAttribute("dpiType");
        if (dpiType == "image") dpiPolicy = LevelProperties::DP_ImageDpi;
        if (is.getTagParam("type", v) && v == "s") type = TZI_XSHLEVEL;
        if (is.getTagParam("subsampling", v)) subsampling = std::stoi(v);
        if (is.getTagParam("premultiply", v)) doPremultiply = std::stoi(v);
        if (is.getTagParam("antialias", v)) antialiasSoftness = std::stoi(v);
        if (is.getTagParam("whiteTransp", v)) whiteTransp = std::stoi(v);
        if (is.getTagParam("isStopMotionLevel", v))
          isStopMotionLevel = std::stoi(v);
        m_properties->setDpiPolicy(dpiPolicy);
        m_properties->setDpi(TPointD(xdpi, ydpi));
        m_properties->setSubsampling(subsampling);
        m_properties->setDoPremultiply(doPremultiply);
        m_properties->setDoAntialias(antialiasSoftness);
        m_properties->setWhiteTransp(whiteTransp);
        m_properties->setIsStopMotion(isStopMotionLevel);
        if (isStopMotionLevel == 1) setIsReadOnly(true);
      } else
        throw TException("unexpected tag " + tagName);
    } else {
      if (flag) break;  // ci puo' essere un solo nome
      flag = true;
      std::wstring token;
      is >> token;
      if (token == L"__empty") {
        // empty = true;
        is >> token;
      }
      if (token == L"_raster")  // obsoleto (Tab2.2)
      {
        double xdpi = 1, ydpi = 1;
        is >> xdpi >> ydpi >> m_name;
        setName(m_name);
        type = OVL_XSHLEVEL;
        m_properties->setDpi(TPointD(xdpi, ydpi));
        setType(type);
        setPath(
            TFilePath("+drawings/") + (getName() + L"." + ::to_wstring("bmp")),
            true);
      } else if (token == L"__raster")  // obsoleto (Tab2.2)
      {
        double xdpi = 1, ydpi = 1;
        std::string extension;
        is >> xdpi >> ydpi >> m_name >> extension;
        setName(m_name);
        type = OVL_XSHLEVEL;
        m_properties->setDpi(TPointD(xdpi, ydpi));
        setType(type);
        setPath(TFilePath("+drawings/") +
                    (getName() + L"." + ::to_wstring(extension)),
                true);
      } else {
        m_name = token;
        setName(m_name);
      }
    }
  }
  if (type == UNKNOWN_XSHLEVEL) {
    std::string ext = m_path.getType();
    if (ext == "pli" || ext == "svg")
      type = PLI_XSHLEVEL;
    else if (ext == "tlv" || ext == "tzu" || ext == "tzp" || ext == "tzl")
      type = TZP_XSHLEVEL;
    else if (ext == "tzi")
      type = TZI_XSHLEVEL;
    else if (ext == "mesh")
      type = MESH_XSHLEVEL;
    else
      type = OVL_XSHLEVEL;
  }
  setType(type);
}
References TXshLevel::getName(), TIStream::getTagAttribute(), TIStream::getTagParam(), TFilePath::getType(), TIStream::matchEndTag(), TIStream::matchTag(), and TXshLevel::setType().
makeTlv()
void TXshSimpleLevel::makeTlv (const TFilePath & tlvPath)
This function will implicitly convert the input path extension to a correctly formatted tlv. Behavior is undefined in case the level is not of fullcolor type.
Deprecated:
Function is obviously an implementation detail of the cleanup process. Should be moved there.
Transforms the level from fullcolor to tlv (colormap),
{
  int ltype = getType();
  if (!(ltype & FULLCOLOR_TYPE)) {
    assert(ltype & FULLCOLOR_TYPE);
    return;
  }
  setType(TZP_XSHLEVEL);
  m_scannedPath = m_path;
  assert(tlvPath.getType() == "tlv");
  m_path = tlvPath;
  FramesSet::const_iterator it;
  for (it = m_frames.begin(); it != m_frames.end(); ++it) {
    TFrameId fid = *it;
    setFrameStatus(fid, Scanned);
    ImageManager::instance()->rebind(getImageId(fid, Scanned),
                                     getImageId(fid, 0));
    ImageManager::instance()->rebind(getIconId(fid, Scanned),
                                     getIconId(fid, 0));
  }
}
References TFilePath::getType(), TXshLevel::getType(), ImageManager::rebind(), Scanned, and TXshLevel::setType().
mergeTemporaryHookFile()
void TXshSimpleLevel::mergeTemporaryHookFile (unsigned int from, unsigned int to, const TFilePath & hookFile)
{
  if (!TFileStatus(hookFile).doesExist()) return;
  HookSet *tempHookSet = new HookSet;
  TIStream is(hookFile);
  std::string tagName;
  try {
    if (is.matchTag(tagName) && tagName == "hooks") tempHookSet->loadData(is);
  } catch (...) {
  }
  HookSet *hookSet  = getHookSet();
  int tempHookCount = tempHookSet->getHookCount();
  if (tempHookCount == 0) {
    for (unsigned int f = from; f <= to; f++) {
      TFrameId fid = index2fid(f);
      hookSet->eraseFrame(fid);
    }
  } else {
    for (int i = 0; i < tempHookCount; i++) {
      Hook *hook    = tempHookSet->getHook(i);
      Hook *newHook = hookSet->touchHook(hook->getId());
      newHook->setTrackerObjectId(hook->getTrackerObjectId());
      newHook->setTrackerRegionHeight(hook->getTrackerRegionHeight());
      newHook->setTrackerRegionWidth(hook->getTrackerRegionWidth());
      for (unsigned int f = from; f <= to; f++) {
        TFrameId fid = index2fid(f);
        newHook->setAPos(fid, hook->getAPos(fid));
        newHook->setBPos(fid, hook->getBPos(fid));
      }
    }
  }
  m_temporaryHookMerged = true;
}
onPaletteChanged
void TXshSimpleLevel::onPaletteChanged () slot
Invoked when some colorstyle has been changed.
{
  FramesSet::iterator ft, fEnd = m_frames.end();
  for (ft = m_frames.begin(); ft != fEnd; ++ft) {
    const TFrameId &fid = *ft;
    if (getType() == PLI_XSHLEVEL) {
      std::string id = rasterized(getImageId(fid));
      ImageManager::instance()->invalidate(id);
    }
    if (getType() & FULLCOLOR_TYPE) {
      std::string id = filled(getImageId(fid));
      ImageManager::instance()->invalidate(id);
    }
    texture_utils::invalidateTexture(this, fid);
  }
}
References TXshLevel::getType(), and ImageManager::invalidate().
removeFiles()
void TXshSimpleLevel::removeFiles (const TFilePath & fp) static
Remove files at fp.
{
  TSystem::moveFileOrLevelToRecycleBin(fp);
  if (fp.getType() == "tlv") {
    TFilePath tpl = fp.withType("tpl");
    if (TFileStatus(tpl).doesExist()) TSystem::moveFileToRecycleBin(tpl);
  }
  // Delete ALL hook files (ie from every Toonz version)
  const QStringList &hookFiles = TXshSimpleLevel::getHookFiles(fp);
  int f, fCount = hookFiles.size();
  for (f = 0; f != fCount; ++f)
    TSystem::moveFileToRecycleBin(TFilePath(hookFiles[f].toStdWString()));
  TFilePath files = fp.getParentDir() + (fp.getName() + "_files");
  if (TFileStatus(files).doesExist() && TFileStatus(files).isDirectory())
    TSystem::rmDirTree(files);
}
References getHookFiles(), TFilePath::getName(), TFilePath::getParentDir(), TFilePath::getType(), and TFilePath::withType().
Referenced by renameFiles().
renameFiles()
void TXshSimpleLevel::renameFiles (const TFilePath & dst, const TFilePath & src) static
Rename files from src to dst.
{
  if (dst == src) return;
  TSystem::touchParentDir(dst);
  if (TSystem::doesExistFileOrLevel(dst)) TXshSimpleLevel::removeFiles(dst);
  TSystem::renameFileOrLevel_throw(dst, src);
  if (dst.getType() == "tlv")
    TSystem::renameFile(dst.withType("tpl"), src.withType("tpl"));
  const TFilePath &srcHookFile = TXshSimpleLevel::getExistingHookFile(src);
  if (!srcHookFile.isEmpty()) {
    const TFilePath &dstHookFile = getHookPath(dst);
    TSystem::renameFile(dstHookFile, srcHookFile);
  }
  TFilePath files = src.getParentDir() + (src.getName() + "_files");
  if (TFileStatus(files).doesExist() && TFileStatus(files).isDirectory())
    TSystem::renameFile(dst.getParentDir() + (dst.getName() + "_files"), files);
}
References getExistingHookFile(), getHookPath(), TFilePath::getName(), TFilePath::getParentDir(), TFilePath::getType(), removeFiles(), and TFilePath::withType().
renumber()
void TXshSimpleLevel::renumber (const std::vector< TFrameId > & fids)
Renumbers the level frames to the specified fids (fids and this->fids() must have the same size).
{
  assert(fids.size() == m_frames.size());
  int n = fids.size();
  int i = 0;
  std::vector<TFrameId> oldFids;
  getFids(oldFids);
  std::map<TFrameId, TFrameId> table;
  std::map<TFrameId, TFrameId> newRenumberTable;
  for (std::vector<TFrameId>::iterator it = oldFids.begin();
       it != oldFids.end(); ++it) {
    TFrameId oldFrameId = *it;
    TFrameId newFrameId = fids[i++];
    table[oldFrameId]   = newFrameId;
    for (auto const &renumber : m_renumberTable) {
      if (renumber.second == oldFrameId) {
        newRenumberTable[renumber.first] = newFrameId;
        break;
      }
    }
  }
  for (auto const &renumber : newRenumberTable) {
    m_renumberTable[renumber.first] = renumber.second;
  }
  m_frames.clear();
  for (i = 0; i < n; ++i) {
    TFrameId fid(fids[i]);
    assert(m_frames.count(fid) == 0);
    m_frames.insert(fid);
  }
  ImageManager *im = ImageManager::instance();
  TImageCache *ic  = TImageCache::instance();
  std::map<TFrameId, TFrameId>::iterator jt;
  {
    for (i = 0, jt = table.begin(); jt != table.end(); ++jt, ++i) {
      std::string Id = getImageId(jt->first);
      ImageLoader::BuildExtData extData(this, jt->first);
      TImageP img = im->getImage(Id, ImageManager::none, &extData);
      ic->add(getIconId(jt->first), img, false);
      im->rebind(Id, "^" + std::to_string(i));
      ic->remap("^icon:" + std::to_string(i), getIconId(jt->first));
    }
    for (i = 0, jt = table.begin(); jt != table.end(); ++jt, ++i) {
      std::string Id = getImageId(jt->second);
      im->rebind("^" + std::to_string(i), Id);
      ic->remap(getIconId(jt->second), "^icon:" + std::to_string(i));
      im->renumber(Id, jt->second);
    }
  }
  if (getType() == PLI_XSHLEVEL) {
    for (i = 0, jt = table.begin(); jt != table.end(); ++jt, ++i) {
      const std::string &id = rasterized(getImageId(jt->first));
      if (im->isBound(id)) im->rebind(id, rasterized("^" + std::to_string(i)));
    }
    for (i = 0, jt = table.begin(); jt != table.end(); ++jt, ++i) {
      const std::string &id = rasterized("^" + std::to_string(i));
      if (im->isBound(id)) im->rebind(id, rasterized(getImageId(jt->second)));
    }
  }
  if (getType() & FULLCOLOR_TYPE) {
    for (i = 0, jt = table.begin(); jt != table.end(); ++jt, ++i) {
      const std::string &id = filled(getImageId(jt->first));
      if (im->isBound(id)) im->rebind(id, filled("^" + std::to_string(i)));
    }
    for (i = 0, jt = table.begin(); jt != table.end(); ++jt, ++i) {
      const std::string &id = filled("^" + std::to_string(i));
      if (im->isBound(id)) im->rebind(id, filled(getImageId(jt->second)));
    }
  }
  m_properties->setDirtyFlag(true);
  if (getHookSet()) getHookSet()->renumber(table);
}
References TImageCache::add(), getFids(), TXshLevel::getHookSet(), ImageManager::getImage(), TXshLevel::getType(), ImageManager::isBound(), ImageManager::rebind(), TImageCache::remap(), and renumber().
Referenced by renumber().
renumberTable()
const std::map< TFrameId, TFrameId > & TXshSimpleLevel::renumberTable () const inline
{
    return m_renumberTable;
  }
save() [1/2]
void TXshSimpleLevel::save () override virtual
Saves the level to disk, with the same path deduction from load()
Implements TXshLevel.
{
  assert(getScene());
  TFilePath path = getScene()->decodeFilePath(m_path);
  TSystem::outputDebug("save() : " + ::to_string(m_path) + " = " +
                       ::to_string(path) + "\n");
  if (getProperties()->getDirtyFlag() == false &&
      getPalette()->getDirtyFlag() == false &&
      TSystem::doesExistFileOrLevel(path))
    return;
  if (!TFileStatus(path.getParentDir()).doesExist()) {
    try {
      TSystem::mkDir(path.getParentDir());
    } catch (...) {
    }
  }
  save(path);
}
References ToonzScene::decodeFilePath(), getPalette(), TFilePath::getParentDir(), getProperties(), TXshLevel::getScene(), and save().
Referenced by SceneLevel::save(), and save().
save() [2/2]
void TXshSimpleLevel::save (const TFilePath & fp, const TFilePath & oldFp = TFilePath(), bool overwritePalette = true)
Save the level in the specified fp. The oldFp is used when the current scene path change...
{
  TFilePath dOldPath =
      (!oldFp.isEmpty()) ? oldFp : getScene()->decodeFilePath(m_path);
  TFilePath dDstPath = getScene()->decodeFilePath(fp);
  if (!TSystem::touchParentDir(dDstPath))
    throw TSystemException(
        dDstPath,
        "The level cannot be saved: failed to access the target folder.");
  // backup
  if (Preferences::instance()->isBackupEnabled() && dOldPath == dDstPath &&
      TSystem::doesExistFileOrLevel(dDstPath) &&
      !getProperties()->isStopMotionLevel())
    saveBackup(dDstPath);
  if (isAreadOnlyLevel(dDstPath)) {
    if (m_editableRange.empty() &&
        !m_temporaryHookMerged)  // file internally locked
      throw TSystemException(
          dDstPath, "The level cannot be saved: it is a read only level.");
    else if (getType() != OVL_XSHLEVEL) {
      // file partially unlocked
      std::wstring fileName = getEditableFileName();
      assert(!fileName.empty());
      TFilePath app = dDstPath.withName(fileName).withType(dDstPath.getType());
      // removes old files
      if (TSystem::doesExistFileOrLevel(app)) TSystem::removeFileOrLevel(app);
      TFilePathSet oldFilePaths;
      getFiles(app, oldFilePaths);
      TFilePathSet::iterator it;
      for (it = oldFilePaths.begin(); it != oldFilePaths.end(); ++it) {
        if (TSystem::doesExistFileOrLevel(*it)) TSystem::removeFileOrLevel(*it);
      }
      // save new files
      TXshSimpleLevel *sl = new TXshSimpleLevel;
      sl->setScene(getScene());
      sl->setPalette(getPalette());
      sl->setPath(getScene()->codeFilePath(app));
      sl->setType(getType());
      sl->setDirtyFlag(getDirtyFlag());
      sl->addRef();  // Needed so levelUpdater doesn't destroy it right away
                     // when its done writing
      std::set<TFrameId>::iterator eft, efEnd = m_editableRange.end();
      for (eft = m_editableRange.begin(); eft != efEnd; ++eft) {
        const TFrameId &fid = *eft;
        sl->setFrame(fid, getFrame(fid, false));
      }
      // Copy hooks
      HookSet *hookSet = sl->getHookSet();
      *hookSet         = *getHookSet();
      FramesSet::iterator ft, fEnd = m_frames.end();
      for (ft = m_frames.begin(); ft != fEnd; ++ft) {
        const TFrameId &fid = *ft;
        if (m_editableRange.find(fid) == m_editableRange.end())
          hookSet->eraseFrame(fid);
      }
      sl->setRenumberTable();
      // Copy mesh level
      sl->save(app);
#ifdef _WIN32
      // hides files
      oldFilePaths.clear();
      if (TSystem::doesExistFileOrLevel(app)) TSystem::hideFileOrLevel(app);
      getFiles(app, oldFilePaths);
      for (it = oldFilePaths.begin(); it != oldFilePaths.end(); ++it) {
        if (TSystem::doesExistFileOrLevel(*it)) TSystem::hideFileOrLevel(*it);
      }
#endif
      return;
    }
  }
  if (dOldPath != dDstPath && m_path != TFilePath()) {
    const TFilePath &dSrcPath = dOldPath;
    try {
      if (TSystem::doesExistFileOrLevel(dSrcPath)) {
        if (TSystem::doesExistFileOrLevel(dDstPath))
          TSystem::removeFileOrLevel(dDstPath);
        copyFiles(dDstPath, dSrcPath);
      }
    } catch (...) {
    }
  }
  // when saving the level palette with global name
  if (overwritePalette && getType() == TZP_XSHLEVEL && getPalette() &&
      getPalette()->getGlobalName() != L"") {
    overwritePalette      = false;
    TFilePath palettePath = dDstPath.withNoFrame().withType("tpl");
    StudioPalette::instance()->save(palettePath, getPalette());
    getPalette()->setDirtyFlag(false);
  }
  saveSimpleLevel(dDstPath, overwritePalette);
}
References copyFiles(), ToonzScene::decodeFilePath(), getFiles(), TXshLevel::getHookSet(), getPalette(), getProperties(), TXshLevel::getScene(), TFilePath::getType(), TXshLevel::getType(), save(), TPalette::setDirtyFlag(), setDirtyFlag(), setPalette(), setRenumberTable(), TXshLevel::setScene(), TXshLevel::setType(), TXshSimpleLevel(), TFilePath::withName(), and TFilePath::withType().
saveData()
void TXshSimpleLevel::saveData (TOStream & os) override virtual
Save the level data (i.e. name, path, etc. e.g. to the .tnz file)
Implements TXshLevel.
{
  os << m_name;
  std::map<std::string, std::string> attr;
  if (getProperties()->getDpiPolicy() == LevelProperties::DP_CustomDpi) {
    TPointD dpi = getProperties()->getDpi();
    if (dpi.x != 0 && dpi.y != 0) {
      attr["dpix"] = std::to_string(dpi.x);
      attr["dpiy"] = std::to_string(dpi.y);
    }
  } else {
    attr["dpiType"] = "image";
  }
  if (getProperties()->getSubsampling() != 1) {
    attr["subsampling"] = std::to_string(getProperties()->getSubsampling());
  }
  if (getProperties()->antialiasSoftness() > 0) {
    attr["antialias"] = std::to_string(getProperties()->antialiasSoftness());
  }
  if (getProperties()->doPremultiply()) {
    attr["premultiply"] = std::to_string(getProperties()->doPremultiply());
  } else if (getProperties()->whiteTransp()) {
    attr["whiteTransp"] = std::to_string(getProperties()->whiteTransp());
  } else if (getProperties()->isStopMotionLevel()) {
    attr["isStopMotionLevel"] =
        std::to_string(getProperties()->isStopMotionLevel());
  }
  if (m_type == TZI_XSHLEVEL) attr["type"] = "s";
  os.openCloseChild("info", attr);
  os.child("path") << m_path;  // fp;
  if (m_scannedPath != TFilePath())
    os.child("scannedPath") << m_scannedPath;  // fp;
}
References TOStream::child(), LevelProperties::getDpi(), getProperties(), TXshLevel::m_type, and TOStream::openCloseChild().
set16BitChannelLevel()
void TXshSimpleLevel::set16BitChannelLevel (bool value) inline
{
    m_16BitChannelLevel = (value && getType() == OVL_XSHLEVEL);
  }
setCompatibilityMasks()
void TXshSimpleLevel::setCompatibilityMasks (int writeMask, int neededMask, int forbiddenMask) static
{
  compatibility.writeMask     = writeMask;
  compatibility.neededMask    = neededMask;
  compatibility.forbiddenMask = forbiddenMask;
}
setContentHistory()
void TXshSimpleLevel::setContentHistory (TContentHistory * contentHistory)
destroys the old contentHistory and replaces it with the new one. Gets ownership
{
  if (contentHistory != m_contentHistory.get())
    m_contentHistory.reset(contentHistory);
}
Referenced by load(), and touchFrame().
setDirtyFlag()
void TXshSimpleLevel::setDirtyFlag (bool on) override virtual
Mark the level as "modified".
Reimplemented from TXshLevel.
{ m_properties->setDirtyFlag(on); }
Referenced by ToonzScene::createNewLevel(), ToonzScene::loadLevel(), TTool::notifyImageChanged(), FillTool::onPropertyChanged(), VectorSelectionTool::onPropertyChanged(), and save().
setEditableRange()
void TXshSimpleLevel::setEditableRange (unsigned int from, unsigned int to, const std::wstring & userName)
Set the range of frame that can be edited and saved. Editable range is contained in m_editableRange.
{
  assert(from <= to && to < (unsigned int)getFrameCount());
  unsigned int i;
  for (i = from; i <= to; i++) m_editableRange.insert(index2fid(i));
  QString hostName        = TSystem::getHostName();
  m_editableRangeUserInfo = userName + L"_" + hostName.toStdWString();
  std::wstring fileName = getEditableFileName();
  TFilePath dstPath     = getScene()->decodeFilePath(m_path);
  dstPath = dstPath.withName(fileName).withType(dstPath.getType());
  // Load temporary level file (for pli and tlv types only)
  if (getType() != OVL_XSHLEVEL && TSystem::doesExistFileOrLevel(dstPath)) {
    TLevelReaderP lr(dstPath);
    TLevelP level = lr->loadInfo();
    setPalette(level->getPalette());
    for (TLevel::Iterator it = level->begin(); it != level->end(); it++) {
      TImageP img = lr->getFrameReader(it->first)->load();
      setFrame(it->first, img);
    }
  }
  // Merge temporary hook file with current hookset
  const TFilePath &hookFile = getHookPath(dstPath);
  mergeTemporaryHookFile(from, to, hookFile);
}
References ToonzScene::decodeFilePath(), getFrameCount(), getHookPath(), TXshLevel::getScene(), TFilePath::getType(), TXshLevel::getType(), index2fid(), setPalette(), TFilePath::withName(), and TFilePath::withType().
setFrame()
void TXshSimpleLevel::setFrame (const TFrameId & fid, const TImageP & img)
{
  assert(m_type != UNKNOWN_XSHLEVEL);
  if (img) img->setPalette(getPalette());
  m_frames.insert(fid);
  TFilePath path = m_path;
  int frameStatus                        = getFrameStatus(fid);
  static const int SCANNED_OR_CLEANUPPED = (Scanned | Cleanupped);
  if ((frameStatus & SCANNED_OR_CLEANUPPED) == Scanned) path = m_scannedPath;
  // Deal with the ImageManger: ensure the identifiers are bound, and the
  // associated image is either modified to img or (if !img) invalidated.
  const std::string &imageId = getImageId(fid);
  if (!ImageManager::instance()->isBound(imageId)) {
    const TFilePath &decodedPath = getScene()->decodeFilePath(path);
    ImageManager::instance()->bind(imageId, new ImageLoader(decodedPath, fid));
  }
  ImageManager::instance()->setImage(imageId, img);  // Invalidates if !img
  if (frameStatus == Normal) {
    // Only a normal frame can have these. Justified since:
    //  PLIs have nothing to share with cleanup stuff
    if (m_type == PLI_XSHLEVEL) {
      const std::string &imageId2 = rasterized(imageId);
      if (!ImageManager::instance()->isBound(imageId2))
        ImageManager::instance()->bind(imageId2, new ImageRasterizer);
      else
        ImageManager::instance()->invalidate(imageId2);
    }
    if (m_type == OVL_XSHLEVEL || m_type == TZI_XSHLEVEL) {
      const std::string &imageId2 = filled(imageId);
      if (!ImageManager::instance()->isBound(imageId2))
        ImageManager::instance()->bind(imageId2, new ImageFiller);
      else
        ImageManager::instance()->invalidate(imageId2);
    }
  }
}
setFrameStatus()
void TXshSimpleLevel::setFrameStatus (const TFrameId & fid, int status)
{
  assert((status & ~(Scanned | Cleanupped | CleanupPreview)) == 0);
  m_framesStatus[fid] = status;
}
setIsReadOnly()
void TXshSimpleLevel::setIsReadOnly (bool value) inline
{ m_isReadOnly = value; }
setPalette()
void TXshSimpleLevel::setPalette (TPalette * palette)
Assigns a palette to the level.
{
  if (m_palette != palette) {
    if (m_palette) m_palette->release();
    m_palette = palette;
    if (m_palette) {
      m_palette->addRef();
      if (!(getType() & FULLCOLOR_TYPE)) m_palette->setPaletteName(getName());
    }
  }
}
References TXshLevel::getName(), TXshLevel::getType(), and TPalette::setPaletteName().
Referenced by load(), save(), setEditableRange(), and Vectorizer::setLevel().
setPath()
void TXshSimpleLevel::setPath (const TFilePath & path, bool retainCachedImages = false)
{
  m_path = fp;
  if (!keepFrames) {
    clearFrames();
    assert(getScene());
    try {
      load();
    } catch (...) {
    }
  }
  if (getType() != PLI_XSHLEVEL) {
    if (!m_frames.empty()) {
      std::string imageId = getImageId(getFirstFid());
      const TImageInfo *imageInfo =
          ImageManager::instance()->getInfo(imageId, ImageManager::none, 0);
      if (imageInfo) {
        TDimension imageRes(0, 0);
        TPointD imageDpi;
        imageRes.lx = imageInfo->m_lx;
        imageRes.ly = imageInfo->m_ly;
        imageDpi.x  = imageInfo->m_dpix;
        imageDpi.y  = imageInfo->m_dpiy;
        m_properties->setImageDpi(imageDpi);
        m_properties->setImageRes(imageRes);
        m_properties->setBpp(imageInfo->m_bitsPerSample *
                             imageInfo->m_samplePerPixel);
      }
    }
  }
}
setRenumberTable()
void TXshSimpleLevel::setRenumberTable ()
Set elements of m_renumberTable with m_frames.
{
  m_renumberTable.clear();
  FramesSet::iterator ft, fEnd = m_frames.end();
  for (ft = m_frames.begin(); ft != fEnd; ++ft) m_renumberTable[*ft] = *ft;
}
Referenced by load(), and save().
setScannedPath()
void TXshSimpleLevel::setScannedPath (const TFilePath & path)
{
  m_scannedPath = fp;
}
touchFrame()
void TXshSimpleLevel::touchFrame (const TFrameId & fid)
Updates content history (invokes setDirtyFlag(true))
Warning
Not what users may expect!
{
  m_properties->setDirtyFlag(true);
  TContentHistory *ch = getContentHistory();
  if (!ch) {
    ch = new TContentHistory(true);
    setContentHistory(ch);
  }
  ch->frameModifiedNow(fid);
  if (getType() == PLI_XSHLEVEL) {
    std::string id = rasterized(getImageId(fid));
    ImageManager::instance()->invalidate(id);
  }
  if (getType() & FULLCOLOR_TYPE) {
    std::string id = filled(getImageId(fid));
    ImageManager::instance()->invalidate(id);
  }
}
References TContentHistory::frameModifiedNow(), getContentHistory(), TXshLevel::getType(), ImageManager::invalidate(), and setContentHistory().
Referenced by TTool::notifyImageChanged().
updateReadOnly()
void TXshSimpleLevel::updateReadOnly ()
{
  TFilePath path = getScene()->decodeFilePath(m_path);
  m_isReadOnly   = isAreadOnlyLevel(path);
}
Member Data Documentation
m_fillFullColorRaster
bool TXshSimpleLevel::m_fillFullColorRaster = false static
m_rasterizePli
bool TXshSimpleLevel::m_rasterizePli = false static
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/toonz/txshsimplelevel.h
E:/opentoonz/toonz/sources/toonzlib/txshsimplelevel.cpp