opentoonz: PreviewFxManager Class Reference
PreviewFxManager Class Reference final
#include <previewfxmanager.h>
Signals
void startedFrame (unsigned long fxId, TRenderPort::RenderData renderData)
void renderedFrame (unsigned long fxId, TRenderPort::RenderData renderData)
void refreshViewRects (unsigned long fxId)
Public Member Functions
FlipBook * showNewPreview (TFxP fx, bool forceFlipbook=false)
void refreshView (TFxP fx)
Updates the fx's preview on the associated flipbooks' current views.
void detach (FlipBook *flipbook)
void freeze (FlipBook *flipbook)
Freezes the specified flipbook.
void unfreeze (FlipBook *flipbook)
void reset (TFxP fx)
void reset (bool detachFlipbooks=true)
Resets the PreviewFxManager together with all internal rendering objects.
void reset (TFxP fx, int frame)
bool isSubCameraActive (TFxP fx)
Static Public Member Functions
static PreviewFxManager * instance ()
Returns the instance of the PreviewFxManager object.
static void suspendRendering (bool suspend)
Protected Slots
void onLevelChanged ()
void onFxChanged ()
void onXsheetChanged ()
void onObjectChanged (bool isDragging)
void onStartedFrame (unsigned long fxId, TRenderPort::RenderData renderData)
void onRenderedFrame (unsigned long fxId, TRenderPort::RenderData renderData)
void onRefreshViewRects (unsigned long id)
Friends
class PreviewFxInstance
Detailed Description
Manages the 'Preview Fx' requests and updates all contextually opened FlipBooks when needed. The class provides the medium between the 'Preview Fx' command and management of both Toonz rendering classes and Flipbooks.
The showNewPreview() method invocation takes place when users activate the 'Preview' command from the right-click menu of fxs in the schematic. It initializes a TRenderer object and starts the render of passed fx over the preview properties range; at the same time, a new Flipbook is opened to visualize the images produced by the render process as frames are finalized.
The refreshView() command is available to update an fx's view upon request (this is typically handled by flipbooks). The manager always renders the area strictly necessary to correctly update all flipbooks' current view; in particular, previously rendered portions of flipbook views are retained, and excluded from further calculations.
Observe that invalidation signals coming from TXshLevelHandle, TFxHandle and TXsheetHandle classes are automatically intercepted to update all FlipBooks created under the manager.
Additional reset() methods are available to clear the manager about a single fx or the whole scene's fxs.
See also
FlipBook, TXshLevelHandle, TFxHandle, TXsheetHandle classes.
Member Function Documentation
detach()
void PreviewFxManager::detach (FlipBook * flipbook)
Detaches the specified flipbook from the manager's control. Optionally, the flipbooks may keep the already previewed images instead of discarding them - however, observe that these images may be cloned from the preview originals, in case some flipbook is still actively previewing the same fx.
{
  // Retrieve its previewed fx
  TFxP fx(flipbook->getPreviewedFx());
  if (!fx) return;
  // Search the flip among attached ones
  QMap<unsigned long, PreviewFxInstance *>::iterator it =
      m_previewInstances.find(fx->getIdentifier());
  if (it == m_previewInstances.end()) return;
  PreviewFxInstance *previewInstance = it.value();
  // Detach the flipbook (does nothing if flipbook is frozen)
  previewInstance->detachFlipbook(flipbook);
  // Eventually, it could be in frozens; detach it from there too
  std::set<FlipBook *> &frozenFlips = previewInstance->m_frozenFlips;
  std::set<FlipBook *>::iterator jt = frozenFlips.find(flipbook);
  if (jt != frozenFlips.end()) {
    flipbook->clearCache();
    delete flipbook->getProgressBarStatus();
    frozenFlips.erase(jt);
  }
  // Finally, delete the preview instance if no flipbook (active or frozen)
  // remain
  if (previewInstance->m_flipbooks.empty() &&
      previewInstance->m_frozenFlips.empty()) {
    delete it.value();
    m_previewInstances.erase(it);
  }
}
freeze()
void PreviewFxManager::freeze (FlipBook * flipbook)
Freezes the specified flipbook.
Observe that detached flipbooks which maintain the previewed images also maintain the internal reference to the previewed fx returned by the FlipBook::getPreviewedFx() method, so the flipbook may be re-attached (ie un-freezed) to the same preview fx.
{
  // Retrieve its previewed fx
  TFxP fx(flipbook->getPreviewedFx());
  if (!fx) return;
  QMap<unsigned long, PreviewFxInstance *>::iterator it =
      m_previewInstances.find(fx->getIdentifier());
  if (it == m_previewInstances.end()) return;
  PreviewFxInstance *previewInstance = it.value();
  // First off, detach the flipbook from the preview instance and
  // insert it among the instance's frozen ones
  previewInstance->detachFlipbook(flipbook);
  previewInstance->m_frozenFlips.insert(flipbook);
  // Then, perform the level copy
  {
    std::string levelName("freezed" + std::to_string(flipbook->getPoolIndex()) +
                          ".noext");
    int i;
    // Clone the preview images
    for (i = previewInstance->m_start; i <= previewInstance->m_end;
         i += previewInstance->m_step) {
      TImageP cachedImage =
          TImageCache::instance()->get(getCacheId(fx, i), false);
      if (cachedImage)
        TImageCache::instance()->add(levelName + std::to_string(i),
                                     cachedImage->cloneImage());
    }
    // Associate a level with the cached images
    TLevelP freezedLevel;
    freezedLevel->setName(levelName);
    for (i = 0; i < previewInstance->m_level->getFrameCount(); ++i)
      freezedLevel->setFrame(TFrameId(i), 0);
    flipbook->setLevel(fx.getPointer(), previewInstance->m_xsheet.getPointer(),
                       freezedLevel.getPointer(), 0,
                       previewInstance->m_start + 1, previewInstance->m_end + 1,
                       previewInstance->m_step, flipbook->getCurrentFrame(),
                       previewInstance->m_snd.getPointer());
    // Also, the associated PB must be cloned
    std::vector<UCHAR> *newPBStatuses = new std::vector<UCHAR>;
    *newPBStatuses                    = previewInstance->m_pbStatus;
    flipbook->setProgressBarStatus(newPBStatuses);
    // Traverse the PB: frames under rendering must be signed as uncompleted
    std::vector<UCHAR>::iterator it;
    for (it = newPBStatuses->begin(); it != newPBStatuses->end(); ++it)
      if (*it == FlipSlider::PBFrameStarted)
        *it = FlipSlider::PBFrameNotStarted;
  }
}
References TImageCache::add(), TImage::cloneImage(), TImageCache::get(), and FlipBook::setLevel().
instance()
PreviewFxManager * PreviewFxManager::instance () static
Returns the instance of the PreviewFxManager object.
{
  static PreviewFxManager _instance;
  return &_instance;
}
isSubCameraActive()
bool PreviewFxManager::isSubCameraActive (TFxP fx)
return true if the preview fx instance for specified fx is with sub-camera activated
{
  if (!fx) return false;
  unsigned long fxId = fx->getIdentifier();
  QMap<unsigned long, PreviewFxInstance *>::iterator it =
      m_previewInstances.find(fxId);
  if (it == m_previewInstances.end()) return false;
  return it.value()->isSubCameraActive();
}
onFxChanged
void PreviewFxManager::onFxChanged () protected slot
{
  // Examinate all RenderInstances for ancestors of current fx
  if (m_previewInstances.size()) {
    TFxP fx = TApp::instance()->getCurrentFx()->getFx();
    QMap<unsigned long, PreviewFxInstance *>::iterator it;
    for (it = m_previewInstances.begin(); it != m_previewInstances.end(); ++it)
    // if(areAncestorAndDescendant(it.value()->m_fx, fx))  //Currently not
    // trespassing sub-xsheet boundaries
    {
      // in case the flipbook is frozen
      if (it.value()->m_flipbooks.empty()) continue;
      it.value()->updateAliases();
      emit refreshViewRects(it.key());
      // it.value()->refreshViewRects();
    }
  }
}
onLevelChanged
void PreviewFxManager::onLevelChanged () protected slot
{
  if (m_previewInstances.size()) {
    // Build the level name as an alias keyword. All cache images associated
    // with an alias containing the level name will be updated.
    TXshLevel *xl = TApp::instance()->getCurrentLevel()->getLevel();
    std::string aliasKeyword;
    TFilePath fp = xl->getPath();
    aliasKeyword = ::to_string(fp.withType(""));
    QMap<unsigned long, PreviewFxInstance *>::iterator it;
    for (it = m_previewInstances.begin(); it != m_previewInstances.end();
         ++it) {
      it.value()->updateAliasKeyword(aliasKeyword);
      emit refreshViewRects(it.key());
      // it.value()->refreshViewRects();
    }
  }
}
onObjectChanged
void PreviewFxManager::onObjectChanged (bool isDragging) protected slot
{
  if (isDragging) return;
  // Update all rendered frames, if necessary
  if (m_previewInstances.size()) {
    QMap<unsigned long, PreviewFxInstance *>::iterator it;
    for (it = m_previewInstances.begin(); it != m_previewInstances.end();
         ++it) {
      // in case the flipbook is frozen
      if (it.value()->m_flipbooks.empty()) continue;
      it.value()->updateFrameRange();
      it.value()->updateFlipbookTitles();
      it.value()->updateAliases();
      emit refreshViewRects(it.key());
      // it.value()->refreshViewRects();
    }
  }
}
onRefreshViewRects
void PreviewFxManager::onRefreshViewRects (unsigned long id) protected slot
This slot is necessary to prevent problems with current implementation of the event-looping PreviewFxInstance::refreshViewRects function.
{
  QMap<unsigned long, PreviewFxInstance *>::iterator it =
      m_previewInstances.find(id);
  if (it != m_previewInstances.end()) it.value()->refreshViewRects();
}
onRenderedFrame
void PreviewFxManager::onRenderedFrame (unsigned long fxId, TRenderPort::RenderData renderData) protected slot
{
  QMap<unsigned long, PreviewFxInstance *>::iterator it =
      m_previewInstances.find(fxId);
  if (it != m_previewInstances.end()) {
    // Invoke the corresponding function. This happens in the MAIN THREAD
    it.value()->doOnRenderRasterCompleted(renderData);
  }
}
onStartedFrame
void PreviewFxManager::onStartedFrame (unsigned long fxId, TRenderPort::RenderData renderData) protected slot
{
  QMap<unsigned long, PreviewFxInstance *>::iterator it =
      m_previewInstances.find(fxId);
  if (it != m_previewInstances.end()) {
    // Invoke the corresponding function. This happens in the MAIN THREAD
    it.value()->doOnRenderRasterStarted(renderData);
  }
}
onXsheetChanged
void PreviewFxManager::onXsheetChanged () protected slot
{
  // Update all rendered frames, if necessary
  if (m_previewInstances.size()) {
    QMap<unsigned long, PreviewFxInstance *>::iterator it;
    for (it = m_previewInstances.begin(); it != m_previewInstances.end();
         ++it) {
      // in case the flipbook is frozen
      if (it.value()->m_flipbooks.empty()) continue;
      it.value()->updateRenderSettings();
      it.value()->updateCamera();
      it.value()->updateFrameRange();
      it.value()->updateFlipbookTitles();
      it.value()->updateAliases();
      emit refreshViewRects(it.key());
      // it.value()->refreshViewRects();
    }
  }
}
refreshView()
void PreviewFxManager::refreshView (TFxP fx)
Updates the fx's preview on the associated flipbooks' current views.
{
  if (!fx) return;
  unsigned long fxId = fx->getIdentifier();
  QMap<unsigned long, PreviewFxInstance *>::iterator it =
      m_previewInstances.find(fxId);
  if (it == m_previewInstances.end()) return;
  it.value()->refreshViewRects();
}
reset() [1/3]
void PreviewFxManager::reset (bool detachFlipbooks = true)
Resets the PreviewFxManager together with all internal rendering objects.
{
  // Hard copy the instances pointers
  QMap<unsigned long, PreviewFxInstance *> previewInstances =
      m_previewInstances;
  QMap<unsigned long, PreviewFxInstance *>::iterator it;
  for (it = previewInstances.begin(); it != previewInstances.end(); ++it) {
    // Just like the above, stopRendering(true) event-LOOPS...
    it.value()->m_renderer.stopRendering(true);
    if (m_previewInstances.find(it.key()) == m_previewInstances.end()) continue;
    if (detachFlipbooks) {
      // Reset all associated flipbooks
      PreviewFxInstance *previewInstance = it.value();
      // Hard copy, since detach manipulates the original
      std::set<FlipBook *> flipbooks = previewInstance->m_flipbooks;
      std::set<FlipBook *>::iterator jt;
      for (jt = flipbooks.begin(); jt != flipbooks.end(); ++jt) {
        // Detach and reset the flipbook
        (*jt)->reset();  // The detachment happens in here
      }
      /*- Frozen
       * FlippreviewInstance
       * -*/
      if (m_previewInstances.find(it.key()) == m_previewInstances.end())
        continue;
      // Same for frozen ones
      if (!previewInstance->m_frozenFlips.empty() &&
          previewInstance->m_frozenFlips.size() < 20) {
        std::set<FlipBook *> frozenFlips = previewInstance->m_frozenFlips;
        for (jt = frozenFlips.begin(); jt != frozenFlips.end(); ++jt) {
          // Detach and reset the flipbook
          (*jt)->reset();  // The detachment happens in here
        }
      }
      // The Preview instance should have been deleted at this point (due to
      // flipbook detachments)
      assert(m_previewInstances.find(it.key()) == m_previewInstances.end());
    } else {
      it.value()->reset();
      it.value()->refreshViewRects();
    }
  }
}
reset() [2/3]
void PreviewFxManager::reset (TFxP fx)
Resets the PreviewFxManager for input fx. All previously rendered previews for it are cleared.
{
  if (!fx) return;
  unsigned long fxId = fx->getIdentifier();
  QMap<unsigned long, PreviewFxInstance *>::iterator it =
      m_previewInstances.find(fxId);
  if (it == m_previewInstances.end()) return;
  it.value()->m_renderer.stopRendering(true);
  // stopRendering(true) LOOPS and may destroy the preview instance. Recheck for
  // its presence
  it = m_previewInstances.find(fxId);
  if (it != m_previewInstances.end()) {
    it.value()->reset();
    it.value()->refreshViewRects();
  }
}
Referenced by showNewPreview().
reset() [3/3]
void PreviewFxManager::reset (TFxP fx, int frame)
Resets the PreviewFxManager for input fx at frame. The previous rendered preview is cleared.
{
  if (!fx) return;
  unsigned long fxId = fx->getIdentifier();
  QMap<unsigned long, PreviewFxInstance *>::iterator it =
      m_previewInstances.find(fxId);
  if (it == m_previewInstances.end()) return;
  if (it.value()->m_start > it.value()->m_end) return;
  it.value()->m_renderer.stopRendering(true);
  // stopRendering(true) LOOPS and may destroy the preview instance. Recheck for
  // its presence
  it = m_previewInstances.find(fxId);
  if (it != m_previewInstances.end()) {
    it.value()->reset(frame);
    it.value()->refreshViewRects();
  }
}
showNewPreview()
FlipBook * PreviewFxManager::showNewPreview (TFxP fx, bool forceFlipbook = false)
Starts a preview instance for passed fx. If explicitly requested, a new flipbook is created to host the preview, otherwise the Preference settings are used. In the former case, the view refresh must be explicitly invoked using the refreshView() command, in order to allow changes of the flipbook's view affine before it. The associated flipbook is returned, in case it has been created.
{
  if (!fx) return 0;
  /*-- fxIdFx --*/
  unsigned long fxId                 = fx->getIdentifier();
  PreviewFxInstance *previewInstance = 0;
  /*-- PreviewFxInstanceFx --*/
  QMap<unsigned long, PreviewFxInstance *>::iterator it =
      m_previewInstances.find(fxId);
  if (it == m_previewInstances.end()) {
    TXsheet *xsh    = TApp::instance()->getCurrentXsheet()->getXsheet();
    previewInstance = new PreviewFxInstance(fx, xsh);
    m_previewInstances.insert(fxId, previewInstance);
  } else {
    previewInstance = it.value();
    /*-- PreviewFxPreview --*/
    if (!forceFlipbook &&
        !Preferences::instance()->previewAlwaysOpenNewFlipEnabled()) {
      // Search the first visible flipbook to be raised. If not found, add a new
      // one.
      /*--
       * FxFlipbookVisiblereset()
       * --*/
      std::set<FlipBook *> &flipbooks = previewInstance->m_flipbooks;
      std::set<FlipBook *>::iterator jt;
      for (jt = flipbooks.begin(); jt != flipbooks.end(); ++jt)
        if ((*jt)->isVisible()) {
          reset(fx);  // Also recalculate the preview
          (*jt)->parentWidget()->raise();
          return 0;
        }
    }
  }
  FlipBook *result = 0;
  /*-- resultFlipbooksetLevel --*/
  previewInstance->addFlipbook(result);
  /*-- Flipbook forceFlipbookfalse --*/
  if (!forceFlipbook) /*-- startRender --*/
    previewInstance->refreshViewRects();
  return result;
}
References TApp::getCurrentXsheet(), TApp::instance(), and reset().
suspendRendering()
void PreviewFxManager::suspendRendering (bool suspend) static
The suspendRendering method allows suspension of the previewer's rendering activity for safety purposes, typically related to the fact that no rendering process should actually be performed as the underlying scene is about to change or being destroyed. Upon suspension, further rendering requests are silently rejected - and currently active ones are canceled and waited until they are no longer active.
{
  suspendedRendering = suspend;
  if (suspend && previewerInstance) {
    QMap<unsigned long, PreviewFxInstance *>::iterator it;
    for (it = previewerInstance->m_previewInstances.begin();
         it != previewerInstance->m_previewInstances.end(); ++it) {
      it.value()->m_renderer.stopRendering(true);
    }
  }
}
unfreeze()
void PreviewFxManager::unfreeze (FlipBook * flipbook)
{
  TFxP fx(flipbook->getPreviewedFx());
  if (!fx) return;
  QMap<unsigned long, PreviewFxInstance *>::iterator it =
      m_previewInstances.find(fx->getIdentifier());
  if (it == m_previewInstances.end()) return;
  PreviewFxInstance *previewInstance = it.value();
  std::set<FlipBook *> &frozenFlips  = previewInstance->m_frozenFlips;
  std::set<FlipBook *>::iterator jt = frozenFlips.find(flipbook);
  if (jt == frozenFlips.end()) return;
  // Re-attach to the preview instance
  {
    frozenFlips.erase(jt);
    // Before attaching, remove any old flipbook level from the cache
    flipbook->clearCache();
    // Also any associated pb status
    delete flipbook->getProgressBarStatus();
    flipbook->setProgressBarStatus(NULL);
    previewInstance->addFlipbook(flipbook);
    // recompute frames, if necessary (call the same process as
    // PreviewFxManager::onXsheetChanged())
    previewInstance->updateRenderSettings();
    previewInstance->updateCamera();
    previewInstance->updateFrameRange();
    previewInstance->updateFlipbookTitles();
    previewInstance->updateAliases();
    previewInstance->refreshViewRects();
  }
}
Friends And Related Function Documentation
PreviewFxInstance
friend class PreviewFxInstance friend
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/toonz/previewfxmanager.h
E:/opentoonz/toonz/sources/toonz/previewfxmanager.cpp