opentoonz: ParamsPageSet Class Reference
ParamsPageSet Class Reference final
ParamsPageSet. Contains a stack of page ParamsPage with relative tab.
#include <fxsettings.h>
Public Member Functions
ParamsPageSet (QWidget *parent=0, Qt::WFlags flags=0)
void setFx (const TFxP &currentFx, const TFxP &actualFx, int frame)
void setScene (ToonzScene *scene)
void setIsCameraViewMode (bool isCameraViewMode)
void updatePage (int frame, bool onlyParam)
void createControls (const TFxP &fx, int index=-1)
ParamsPage * getCurrentParamsPage () const
ParamsPage * getParamsPage (int index) const
int getParamsPageCount () const
ParamsPage * createParamsPage ()
void addParamsPage (ParamsPage *page, const char *name)
QSize getPreferredSize ()
Protected Slots
void setPage (int)
void openHelpFile ()
void openHelpUrl ()
void recomputePreferredSize ()
Protected Member Functions
void createPage (TIStream &is, const TFxP &fx, int index)
Detailed Description
ParamsPageSet. Contains a stack of page ParamsPage with relative tab.
         Inherits \b QWidget.
Constructor & Destructor Documentation
ParamsPageSet()
ParamsPageSet::ParamsPageSet (QWidget * parent = 0, Qt::WFlags flags = 0)
    : QWidget(parent, flags)
    , m_preferredSize(0, 0)
    , m_helpFilePath("")
    , m_helpCommand("") {
  // TabBar
  m_tabBar = new TabBar(this);
  // This widget is used to set the background color of the tabBar
  // using the styleSheet and to draw the two lines on the bottom size.
  m_tabBarContainer = new TabBarContainter(this);
  m_pagesList       = new QStackedWidget(this);
  m_helpButton = new QPushButton(tr(""), this);
  m_helpButton->setIconSize(QSize(20, 20));
  m_helpButton->setIcon(createQIcon("help"));
  m_helpButton->setFixedWidth(28);
  m_helpButton->setToolTip(tr("View help page"));
  m_parent = dynamic_cast<ParamViewer *>(parent);
  m_pageFxIndexTable.clear();
  m_tabBar->setDrawBase(false);
  m_tabBar->setObjectName("FxSettingsTabBar");
  m_helpButton->setFixedHeight(20);
  m_helpButton->setObjectName("FxSettingsHelpButton");
  m_helpButton->setFocusPolicy(Qt::NoFocus);
  //----layout
  QVBoxLayout *mainLayout = new QVBoxLayout();
  mainLayout->setMargin(0);
  mainLayout->setSpacing(0);
  {
    QHBoxLayout *hLayout = new QHBoxLayout();
    hLayout->setMargin(0);
    hLayout->addSpacing(0);
    {
      hLayout->addWidget(m_tabBar);
      hLayout->addStretch(1);
      hLayout->addWidget(m_helpButton);
    }
    m_tabBarContainer->setLayout(hLayout);
    mainLayout->addWidget(m_tabBarContainer);
    mainLayout->addWidget(m_pagesList);
    mainLayout->addWidget(new Separator("", this), 0);
  }
  setLayout(mainLayout);
  connect(m_tabBar, SIGNAL(currentChanged(int)), this, SLOT(setPage(int)));
  m_helpButton->hide();
}
~ParamsPageSet()
ParamsPageSet::~ParamsPageSet ()
{}
Member Function Documentation
addParamsPage()
void ParamsPageSet::addParamsPage (ParamsPage * page, const char * name)
{
  /*-- このFxで最大サイズのページに合わせてダイアログをリサイズ --*/
  QSize pagePreferredSize = page->getPreferredSize();
  m_preferredSize         = m_preferredSize.expandedTo(
      pagePreferredSize + QSize(m_tabBarContainer->height() + 2,
                                2)); /*-- 2は上下左右のマージン --*/
  QScrollArea *pane = new QScrollArea(this);
  pane->setWidgetResizable(true);
  pane->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
  pane->setVerticalScrollBarPolicy(Qt::ScrollBarAsNeeded);
  pane->setWidget(page);
  m_tabBar->addSimpleTab(QString::fromUtf8(name));
  m_pagesList->addWidget(pane);
}
createControls()
void ParamsPageSet::createControls (const TFxP & fx, int index = -1)
Create a page reading xml file relating to fx.
{
  if (TMacroFx *macroFx = dynamic_cast<TMacroFx *>(fx.getPointer())) {
    const std::vector<TFxP> &fxs = macroFx->getFxs();
    for (int i = 0; i < (int)fxs.size(); i++) createControls(fxs[i], i);
    return;
  }
  if (RasterFxPluginHost *plugin =
          dynamic_cast<RasterFxPluginHost *>(fx.getPointer())) {
    plugin->build(this);
    std::string url = plugin->getUrl();
    if (!url.empty()) {
      connect(m_helpButton, SIGNAL(pressed()), this, SLOT(openHelpUrl()));
      m_helpButton->show();
      m_helpUrl = url;
    }
    return;
  }
  TFilePath fp = ToonzFolder::getProfileFolder() + "layouts" + "fxs" +
                 (fx->getFxType() + ".xml");
  TIStream is(fp);
  if (!is) return;
  if (fx->getParams()->getParamCount()) {
    try {
      std::string tagName;
      if (!is.matchTag(tagName) || tagName != "fxlayout")
        throw TException("expected <fxlayout>");
      m_helpFilePath = is.getTagAttribute("help_file");
      if (m_helpFilePath != "") {
        connect(m_helpButton, SIGNAL(pressed()), this, SLOT(openHelpFile()));
        m_helpButton->show();
        /*-- pdfファイルのページ指定など、引数が必要な場合の追加fragmentを取得
         * --*/
        m_helpCommand = is.getTagAttribute("help_command");
      }
      while (!is.matchEndTag()) createPage(is, fx, index);
    } catch (TException const &) {
    }
  }
  // else createEmptyPage();
}
References createControls(), TIStream::getTagAttribute(), TIStream::matchEndTag(), and TIStream::matchTag().
Referenced by createControls().
createPage()
void ParamsPageSet::createPage (TIStream & is, const TFxP & fx, int index) protected
{
  std::string tagName;
  if (!is.matchTag(tagName) || tagName != "page")
    throw TException("expected <page>");
  std::string pageName = is.getTagAttribute("name");
  if (pageName == "") pageName = "page";
  ParamsPage *paramsPage = new ParamsPage(this, m_parent);
  bool isFirstPageOfFx;
  if (index < 0)
    isFirstPageOfFx = (m_pagesList->count() == 0);
  else  // macro fx case
    isFirstPageOfFx = !(m_pageFxIndexTable.values().contains(index));
  paramsPage->setPage(is, fx, isFirstPageOfFx);
  connect(paramsPage, SIGNAL(preferredPageSizeChanged()), this,
          SLOT(recomputePreferredSize()));
  /*-- このFxで最大サイズのページに合わせてダイアログをリサイズ --*/
  QSize pagePreferredSize = paramsPage->getPreferredSize();
  m_preferredSize         = m_preferredSize.expandedTo(
      pagePreferredSize + QSize(m_tabBarContainer->height() + 2,
                                2)); /*-- 2は上下左右のマージン --*/
  QScrollArea *scrollAreaPage = new QScrollArea(this);
  scrollAreaPage->setWidgetResizable(true);
  scrollAreaPage->setHorizontalScrollBarPolicy(Qt::ScrollBarAsNeeded);
  scrollAreaPage->setVerticalScrollBarPolicy(Qt::ScrollBarAsNeeded);
  scrollAreaPage->setWidget(paramsPage);
  QString str;
  m_tabBar->addSimpleTab(str.fromStdString(pageName));
  m_pagesList->addWidget(scrollAreaPage);
  if (index >= 0) m_pageFxIndexTable[paramsPage] = index;
}
createParamsPage()
ParamsPage * ParamsPageSet::createParamsPage ()
{
  return new ParamsPage(this, m_parent);
}
getCurrentParamsPage()
ParamsPage * ParamsPageSet::getCurrentParamsPage () const
{
  QScrollArea *scrollAreaPage =
      dynamic_cast<QScrollArea *>(m_pagesList->currentWidget());
  assert(scrollAreaPage);
  return dynamic_cast<ParamsPage *>(scrollAreaPage->widget());
}
getParamsPage()
ParamsPage * ParamsPageSet::getParamsPage (int index) const
{
  QScrollArea *scrollAreaPage =
      dynamic_cast<QScrollArea *>(m_pagesList->widget(index));
  assert(scrollAreaPage);
  return dynamic_cast<ParamsPage *>(scrollAreaPage->widget());
}
getParamsPageCount()
int ParamsPageSet::getParamsPageCount () const inline
{ return (int)m_pagesList->count(); };
getPreferredSize()
QSize ParamsPageSet::getPreferredSize () inline
{ return m_preferredSize; }
openHelpFile
void ParamsPageSet::openHelpFile () protected slot
{
  if (m_helpFilePath == "") return;
  // if (m_helpCommand != "")
  //    commandString += m_helpCommand + " ";
  // Get UI language as set in "Preferences"
  QString currentLanguage = Preferences::instance()->getCurrentLanguage();
  std::string helpDocLang = currentLanguage.toStdString();
  // Assume associated language subdir exists
  TFilePath helpFp = TEnv::getStuffDir() + "doc" + helpDocLang + m_helpFilePath;
  // Verify subdir exists; if not, default to standard doc dir
  if (!TFileStatus(helpFp).doesExist()) {
    helpFp = TEnv::getStuffDir() + "doc" + m_helpFilePath;
  }
  // commandString +=
  // QString::fromStdWString(helpFp.getWideString()).toStdString();
  // QString command = QString::fromStdString(m_helpFilePath);
  // system(commandString.c_str());
  // QProcess process;
  // process.start(command);
  QDesktopServices::openUrl(
      QUrl::fromLocalFile(QString::fromStdWString(helpFp.getWideString())));
}
openHelpUrl
void ParamsPageSet::openHelpUrl () protected slot
{
  QDesktopServices::openUrl(QUrl(QString(m_helpUrl.c_str())));
}
recomputePreferredSize
void ParamsPageSet::recomputePreferredSize () protected slot
{
  QSize newSize(0, 0);
  for (int i = 0; i < m_pagesList->count(); i++) {
    QScrollArea *area = dynamic_cast<QScrollArea *>(m_pagesList->widget(i));
    if (!area) continue;
    ParamsPage *page = dynamic_cast<ParamsPage *>(area->widget());
    if (!page) continue;
    QSize pagePreferredSize = page->getPreferredSize();
    newSize                 = newSize.expandedTo(pagePreferredSize +
                                 QSize(m_tabBarContainer->height() + 2, 2));
  }
  if (!newSize.isEmpty()) {
    m_preferredSize = newSize;
    // resize the parent FxSettings
    m_parent->notifyPreferredSizeChanged(m_preferredSize + QSize(2, 50));
  }
}
setFx()
void ParamsPageSet::setFx (const TFxP & currentFx, const TFxP & actualFx, int frame)
{
  TMacroFx *currentFxMacro = dynamic_cast<TMacroFx *>(currentFx.getPointer());
  if (currentFxMacro) {
    TMacroFx *actualFxMacro = dynamic_cast<TMacroFx *>(actualFx.getPointer());
    assert(actualFxMacro);
    const std::vector<TFxP> &currentFxMacroFxs = currentFxMacro->getFxs();
    const std::vector<TFxP> &actualFxMacroFxs  = actualFxMacro->getFxs();
    assert(currentFxMacroFxs.size() == actualFxMacroFxs.size());
    for (int i = 0; i < m_pagesList->count(); i++) {
      ParamsPage *page = getParamsPage(i);
      if (!page || !m_pageFxIndexTable.contains(page)) continue;
      int index = m_pageFxIndexTable[page];
      page->setFx(currentFxMacroFxs[index], actualFxMacroFxs[index], frame);
    }
  } else {
    for (int i = 0; i < m_pagesList->count(); i++) {
      ParamsPage *page = getParamsPage(i);
      if (!page) continue;
      page->setFx(currentFx, actualFx, frame);
    }
  }
}
setIsCameraViewMode()
void ParamsPageSet::setIsCameraViewMode (bool isCameraViewMode)
{
  if (!m_pagesList) return;
  int i;
  for (i = 0; i < m_pagesList->count(); i++) {
    ParamsPage *page = getParamsPage(i);
    if (!page) continue;
    page->getFxHistogramRender()->setIsCameraViewMode(isCameraViewMode);
  }
}
setPage
void ParamsPageSet::setPage (int index) protected slot
{
  if (m_tabBar->count() == 0 || m_pagesList->count() == 0) return;
  assert(index >= 0 && index < m_pagesList->count());
  m_pagesList->setCurrentIndex(index);
}
setScene()
void ParamsPageSet::setScene (ToonzScene * scene)
{
  if (!m_pagesList) return;
  int i;
  for (i = 0; i < m_pagesList->count(); i++) {
    ParamsPage *page = getParamsPage(i);
    if (!page) continue;
    page->getFxHistogramRender()->setScene(scene);
  }
}
updatePage()
void ParamsPageSet::updatePage (int frame, bool onlyParam)
{
  if (!m_pagesList) return;
  int i;
  for (i = 0; i < m_pagesList->count(); i++) {
    ParamsPage *page = getParamsPage(i);
    if (!page) continue;
    page->update(frame);
    if (!onlyParam) page->getFxHistogramRender()->invalidateFrame(frame);
  }
}
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/toonzqt/fxsettings.h
E:/opentoonz/toonz/sources/toonzqt/fxsettings.cpp