opentoonz: ToonzScene Class Reference
ToonzScene Class Reference
Public Member Functions
TProject * getProject () const
Returns a pointer to the project holding a scene instance.
void setProject (TProject *)
Associates a scene to a project.
void setScenePath (const TFilePath &p)
Sets the scene's file path.
TFilePath getScenePath () const
Returns the scene's file path.
void setSceneName (std::wstring name)
Sets the scene's name.
std::wstring getSceneName () const
Returns the scene's name.
void setUntitled ()
Marks the scene as explicitly untitled.
bool isUntitled () const
TXsheet * getXsheet () const
Returns a pointer to the scene's current xsheet.
TXsheet * getTopXsheet () const
ChildStack * getChildStack () const
Returns a pointer to the xsheets hierarchy.
TSceneProperties * getProperties () const
< Returns a pointer to the scene's properties.
TLevelSet * getLevelSet () const
Returns a pointer to the scene's Level Set.
void clear ()
Clears the scene.
void save (const TFilePath &path, TXsheet *subxsheet=0)
void loadTnzFile (const TFilePath &path)
void loadNoResources (const TFilePath &path)
void loadResources (bool withProgressDialog=false)
Loads the scene resources.
void load (const TFilePath &path, bool withProgressDialog=false)
TFilePath getImportedLevelPath (const TFilePath path) const
Loads a scene from file.
bool convertLevelIfNeeded (TFilePath &levelPath)
TXshLevel * loadLevel (const TFilePath &actualPath, const LevelOptions *options=0, std::wstring levelName=L"", const std::vector< TFrameId > &fIds=std::vector< TFrameId >())
void renderFrame (const TRaster32P &ras, int row, const TXsheet *xsh=0, bool checkFlags=true) const
void renderFrame (const TRaster32P &ras, int row, const TXsheet *xsh, const TRectD &placedRect, const TAffine &worldToPlacedAff) const
int getFrameCount () const
int loadFrameCount (const TFilePath &fp)
TXshLevel * createNewLevel (int type, std::wstring levelName=L"", const TDimension &dim=TDimension(), double dpi=0, TFilePath fp=TFilePath())
TFilePath codeFilePath (const TFilePath &) const
TFilePath decodeFilePath (const TFilePath &) const
bool isExternPath (const TFilePath &fp) const
TFilePath getDefaultLevelPath (int levelType, std::wstring levelName=L"a") const
TFilePath codeSavePath (TFilePath) const
TFilePath decodeSavePath (TFilePath) const
TCamera * getCurrentCamera ()
TCamera * getCurrentPreviewCamera ()
void getSoundColumns (std::vector< TXshSoundColumn * > &columns)
void updateSoundColumnFrameRate ()
TFilePath getIconPath () const
TFilePath getSavePath () const
TContentHistory * getContentHistory (bool createIfNeeded=false)
gets the contentHistory. possibly creates a new one (if createIfNeeded)
double shiftCameraX (double val)
void setVersionNumber (VersionNumber version)
VersionNumber getVersionNumber ()
bool codeFilePathWithSceneFolder (TFilePath &path) const
bool isLoading ()
void setIsLoading (bool isLoading)
std::wstring getLevelNameWithoutSceneNumber (std::wstring orgName)
Static Public Member Functions
static TFilePath getIconPath (const TFilePath &scenePath)
Detailed Description
Constructor & Destructor Documentation
ToonzScene()
ToonzScene::ToonzScene ()
    : m_contentHistory(0), m_isUntitled(true), m_isLoading(false) {
  m_childStack = new ChildStack(this);
  m_properties = new TSceneProperties();
  m_levelSet   = new TLevelSet();
  m_project    = new TProject();
  m_project->addRef();
}
~ToonzScene()
ToonzScene::~ToonzScene ()
{
  delete m_properties;
  delete m_levelSet;
  delete m_childStack;
  delete m_contentHistory;
  assert(m_project);
  if (m_project) m_project->release();
}
Member Function Documentation
clear()
void ToonzScene::clear ()
Clears the scene.
                       {
  if (isUntitled()) deleteUntitledScene(getScenePath().getParentDir());
  m_childStack->clear();
  m_scenePath                  = TFilePath();
  TSceneProperties *properties = m_properties;
  m_properties                 = new TSceneProperties();
  delete properties;
  m_levelSet->clear();
}
References ChildStack::clear(), getScenePath(), and isUntitled().
Referenced by loadNoResources().
codeFilePath()
TFilePath ToonzScene::codeFilePath (const TFilePath & path) const
Code file path TFilePath.
See also
decodeFilePath()
{
  TFilePath fp(path);
  TProject *project = getProject();
  Preferences::PathAliasPriority priority =
      Preferences::instance()->getPathAliasPriority();
  if (priority == Preferences::SceneFolderAlias &&
      codeFilePathWithSceneFolder(fp)) {
    return fp;
  }
  if (project)
    for (int i = 0; i < project->getFolderCount(); i++) {
      TFilePath folderName("+" + project->getFolderName(i));
      TFilePath folderPath = decodeFilePath(folderName);
      if (folderPath.isAncestorOf(fp)) {
        fp = folderName + (fp - folderPath);
        return fp;
      }
    }
  if (priority == Preferences::ProjectFolderAliases)
    codeFilePathWithSceneFolder(fp);
  return fp;
}
References decodeFilePath(), TProject::getFolderCount(), TProject::getFolderName(), and getProject().
Referenced by ReplaceParentDirectoryPopup::execute(), loadLevel(), OutputSettingsPopup::onPathChanged(), and Vectorizer::setLevel().
codeFilePathWithSceneFolder()
bool ToonzScene::codeFilePathWithSceneFolder (TFilePath & path) const
{
  // if the scene is untitled, then do nothing and return false
  if (isUntitled()) return false;
  TFilePath sceneFolderPath = m_scenePath.getParentDir();
  if (sceneFolderPath.isAncestorOf(path)) {
    path = TFilePath("$scenefolder") + (path - sceneFolderPath);
    return true;
  }
  return false;
}
codeSavePath()
TFilePath ToonzScene::codeSavePath (TFilePath path) const
Code save path. Es. +drawings/seq1/scena1/a.pli -> +drawings/$savepath/a.pli
See also
decodeSavePath()
{
  if (path == TFilePath()) return path;
  TFilePath savePath = getSavePath();
  if (savePath == TFilePath()) return path;  // non dovrebbe succedere mai
  TFilePath filename;
  TFilePath originalPath = path;
  if (savePath.withoutParentDir() != path.withoutParentDir()) {
    TFilePath parentDir = path.getParentDir();
    if (parentDir != TFilePath() && !parentDir.isRoot()) {
      filename = path.withoutParentDir();
      path     = parentDir;
    } else
      return originalPath;
  }
  TFilePath head;
  if (!checkTail(path, savePath, head)) return originalPath;
  if (head.getParentDir() != TFilePath() || head == TFilePath() ||
      head.getWideString()[0] != L'+')
    return originalPath;
  std::string folderName = ::to_string(head.getWideString().substr(1));
  if (!getProject()->getUseScenePath(folderName)) return originalPath;
  return head + savePathString + filename;
}
References TFilePath::getParentDir(), getProject(), getSavePath(), and TFilePath::withoutParentDir().
convertLevelIfNeeded()
bool ToonzScene::convertLevelIfNeeded (TFilePath & levelPath)
If conversion is required, a new level file will be created and levelPath will be substituted with its new path.
Returns
Whether the level doesn't need to be converted or the conversion succeeded.
Checks if the given levelPath is a file path
{
  LevelType ltype = getLevelType(levelPath);
  TFilePath fp    = levelPath;
  if (ltype.m_vectorNotPli) {
    // livello flash o svg
    levelPath = levelPath.withType("pli");
    TLevelWriterP lw(levelPath);
    TLevelReaderP lr(fp);
    if (!lr) return false;
    TLevelP inLevel = lr->loadInfo();
    if (!inLevel || inLevel->getFrameCount() == 0) return false;
    TLevelP outLevel;
    for (TLevel::Iterator it = inLevel->begin(); it != inLevel->end(); ++it) {
      TVectorImageP img = lr->getFrameReader(it->first)->load();
      if (!img) continue;
      lw->getFrameWriter(it->first)->save(img);
    }
  } else if (ltype.m_oldLevelFlag) {
    TLevelP outLevel;
    // livello Toonz 4.6
    levelPath = TFilePath(levelPath.getParentDir().getWideString() + L"\\" +
                          levelPath.getWideName() + L".tlv");
    if (TSystem::doesExistFileOrLevel(levelPath))
      TSystem::removeFileOrLevel(levelPath);
    TFilePath pltPath = TFilePath(levelPath.getParentDir().getWideString() +
                                  L"\\" + levelPath.getWideName() + L".tpl");
    if (TSystem::doesExistFileOrLevel(pltPath))
      TSystem::removeFileOrLevel(pltPath);
    TLevelWriterP lw(levelPath);
    lw->setIconSize(Preferences::instance()->getIconSize());
    TPaletteP palette =
        ToonzImageUtils::loadTzPalette(fp.withType("plt").withNoFrame());
    TLevelReaderP lr(fp);
    if (!lr) return false;
    TLevelP inLevel = lr->loadInfo();
    if (!inLevel || inLevel->getFrameCount() == 0) return false;
    outLevel->setPalette(palette.getPointer());
    try {
      for (TLevel::Iterator it = inLevel->begin(); it != inLevel->end(); ++it) {
        TToonzImageP img = lr->getFrameReader(it->first)->load();
        if (!img) continue;
        img->setPalette(palette.getPointer());
        lw->getFrameWriter(it->first)->save(img);
      }
    } catch (TException &e) {
      // devo buttare il tlv che stavo salvando!
      QString msg = QString::fromStdWString(e.getMessage());
      if (msg == QString("Old 4.1 Palette")) {
        lw = TLevelWriterP();
        if (TSystem::doesExistFileOrLevel(levelPath))
          TSystem::removeFileOrLevel(levelPath);
        throw e;
      }
    }
    lw = TLevelWriterP();  // bisogna liberare prima lw di outLevel,
    // altrimenti la paletta che lw vuole scrivere e' gia' stata
    // loutLeveliberata.
  }
  return true;
}
References TFilePath::getParentDir(), and TFilePath::withType().
Referenced by loadLevel().
createNewLevel()
TXshLevel * ToonzScene::createNewLevel (int type, std::wstring levelName = L"", const TDimension & dim = TDimension(), double dpi = 0, TFilePath fp = TFilePath())
Return a pointer to TXshLevel, a new level.
Create a new level with type defined in txshleveltypes.h and levelName. wstring levelName force an anambiguos name.
{
  TLevelSet *levelSet = getLevelSet();
  if (type == TZI_XSHLEVEL)  // TZI type corresponds to the 'Scan Level'
    type = OVL_XSHLEVEL;     // default option. See Toonz Preferences class.
  if (type == CHILD_XSHLEVEL && levelName == L"") levelName = L"sub";
  // Select a different unique level name in case it already exists (either in
  // scene or on disk)
  {
    const std::unique_ptr<NameBuilder> nameBuilder(
        NameBuilder::getBuilder(levelName));
    for (;;) {
      levelName = nameBuilder->getNext();
      /*-- level --*/
      if (m_levelSet->getLevel(levelName) != 0) continue;
      /*-- LevelSetLevel --*/
      if (type != CHILD_XSHLEVEL && type != PLT_XSHLEVEL) {
        if (fp.isEmpty()) fp = getDefaultLevelPath(type, levelName);
        TFilePath actualFp = decodeFilePath(fp);
        if (TSystem::doesExistFileOrLevel(
                actualFp))  // if(TFileStatus(actualFp).doesExist()) continue;
        {
          fp = TFilePath();
          continue;
        }
        int l, lCount = levelSet->getLevelCount();
        for (l = 0; l != lCount; ++l) {
          TXshLevel *xl = levelSet->getLevel(l);
          if (!xl) continue;
          TXshSimpleLevel *sl = xl->getSimpleLevel();
          if (!sl) continue;
          TFilePath lfp = decodeFilePath(sl->getPath());
          if (actualFp == lfp) break;
        }
        if (l < lCount) {
          /*-- fpLevel --*/
          fp = TFilePath();
          continue;
        }
      }
      break;
    }
  }
  TXshLevel *xl = 0;
  if (type == CHILD_XSHLEVEL) {
    TXshChildLevel *cl = new TXshChildLevel(levelName);
    cl->setScene(this);
    cl->getXsheet()->setScene(this);
    xl = cl;
    // Include the project's default cameras
    const TSceneProperties &props =
        TProjectManager::instance()->getCurrentProject()->getSceneProperties();
    props.cloneCamerasTo(cl->getXsheet()->getStageObjectTree());
  } else if (type == PLT_XSHLEVEL) {
    TXshPaletteLevel *pl = new TXshPaletteLevel(levelName);
    pl->setScene(this);
    xl = pl;
  } else {
    TXshSimpleLevel *sl = new TXshSimpleLevel(levelName);
    sl->setScene(this);
    sl->setType(type);
    sl->setPath(fp);
    sl->setDirtyFlag(true);
    sl->initializePalette();
    sl->initializeResolutionAndDpi();
    xl = sl;
  }
  m_levelSet->insertLevel(xl);
  TNotifier::instance()->notify(TCastChange());
  return xl;
}
References TSceneProperties::cloneCamerasTo(), decodeFilePath(), TProjectManager::getCurrentProject(), getDefaultLevelPath(), getLevelSet(), TXshSimpleLevel::getPath(), TXshLevel::getSimpleLevel(), TXsheet::getStageObjectTree(), TXshChildLevel::getXsheet(), TProjectManager::instance(), TXshSimpleLevel::setDirtyFlag(), TXsheet::setScene(), TXshLevel::setScene(), TXshChildLevel::setScene(), and TXshLevel::setType().
Referenced by ChildStack::createChild(), Vectorizer::setLevel(), and TTool::touchImage().
decodeFilePath()
TFilePath ToonzScene::decodeFilePath (const TFilePath & path) const
Decode file path TFilePath.
See also
codeFilePath()
{
  TProject *project   = getProject();
  bool projectIsEmpty = project->getFolderCount() ? false : true;
  TFilePath fp        = path;
  std::wstring head;
  TFilePath tail;
  path.split(head, tail);
  std::string h;
  std::wstring s;
  if (head != L"") {
    // in case of the project folder aliases
    if (head[0] == L'+') {
      if (TProjectManager::instance()->isTabModeEnabled()) {
        return m_scenePath.getParentDir() +
               (m_scenePath.getWideName() + L"_files") + tail;
      }
      if (TProjectManager::instance()->isTabKidsModeEnabled()) {
        return m_scenePath.getParentDir() + m_scenePath.getWideName() + tail;
      }
      if (projectIsEmpty) {
        TFilePath dir = m_scenePath.getParentDir();
        if (dir.getName() == "scenes")
          return dir.withName(head.substr(1)) + tail;
        else
          return dir + tail;
      }
      if (project) {
        h           = ::to_string(head.substr(1));
        TFilePath f = project->getFolder(h);
        if (f != TFilePath()) s = f.getWideString();
      }
    }
    // in case of the scene folder alias
    else if (head == L"$scenefolder") {
      TFilePath dir = m_scenePath.getParentDir();
      return dir + tail;
    }
  }
  if (s != L"") {
    std::map<std::wstring, std::wstring> table;
    // if the scene is untitled and path expansion depends on the scene
    // (because the expansion contains $ scenename, $ scenepath, or it uses the
    // savepath)
    if (m_isUntitled &&
        (s.find(L"$scene") != std::wstring::npos ||
         project->getUseScenePath(h) ||
         fp.getParentDir().getName() == getScenePath().getName())) {
      TFilePath parentDir = getScenePath().getParentDir();
      fp                  = parentDir + head.substr(1) + tail;
    } else {
      TFilePath scenePath = getScenePath();
      TFilePath scenePathRoot;
      if (project)
        scenePathRoot = project->getFolder(TProject::Scenes);
      else
        scenePathRoot = scenePath.getParentDir();
      if (scenePathRoot != TFilePath() && !scenePathRoot.isAbsolute() &&
          project)
        scenePathRoot = project->getProjectFolder() + scenePathRoot;
      if (TSystem::isUNC(scenePath) && !TSystem::isUNC(scenePathRoot))
        scenePathRoot = TSystem::toUNC(scenePathRoot);
      if (scenePathRoot.isAncestorOf(scenePath))
        scenePath = scenePath - scenePathRoot;
      table[L"$scenepath"] = scenePath.withType("").getWideString();
      table[L"$scenename"] = scenePath.withType("").getWideString();
      std::map<std::wstring, std::wstring>::reverse_iterator it;
      for (it = table.rbegin(); it != table.rend(); ++it) {
        std::wstring keyword = it->first;
        int i                = 0;
        for (;;) {
          int j = s.find(keyword, i);
          if (j == (int)std::wstring::npos) break;
          s.replace(j, keyword.length(), it->second);
          i = j;
        }
      }
      fp = TFilePath(s) + tail;
    }
  }
  if (fp != TFilePath() && !fp.isAbsolute() && project)
    fp = project->getProjectFolder() + fp;
  return fp;
}
References TProject::getFolder(), TProject::getFolderCount(), TFilePath::getName(), TFilePath::getParentDir(), getProject(), TProject::getProjectFolder(), getScenePath(), TProjectManager::instance(), TProject::Scenes, TFilePath::withName(), and TFilePath::withType().
Referenced by codeFilePath(), createNewLevel(), CleanupSettingsModel::getClnPath(), getSavePath(), isExternPath(), TXshPaletteLevel::load(), TXshSimpleLevel::load(), IoCmd::loadResources(), LevelUpdater::open(), ScenePalette::save(), SceneLevel::save(), SceneSound::save(), TXshPaletteLevel::save(), TXshSimpleLevel::save(), save(), SceneLevel::SceneLevel(), TXshSimpleLevel::setEditableRange(), and Vectorizer::setLevel().
decodeSavePath()
TFilePath ToonzScene::decodeSavePath (TFilePath path) const
Decode save path. es. +drawings/$savepath/a.pli -> +drawings/seq1/scena1/a.pli
See also
codeSavePath()
{
  std::wstring s = path.getWideString();
  int i          = s.find(savePathString);
  if (i != (int)std::wstring::npos) {
    TFilePath savePath = getSavePath();
    s.replace(i, savePathString.length(), savePath.getWideString());
    return TFilePath(s);
  }
  // in case of the scene folder alias (start with "$scenefolder")
  else if (s.find(L"$scenefolder") == 0) {
    s.replace(0, 12, m_scenePath.getParentDir().getWideString());
    return TFilePath(s);
  } else
    return path;
}
References TFilePath::getParentDir(), and getSavePath().
getChildStack()
ChildStack * ToonzScene::getChildStack () const inline
Returns a pointer to the xsheets hierarchy.
Referenced by XsheetViewer::changeWindowTitle(), and getSoundColumns().
getContentHistory()
TContentHistory * ToonzScene::getContentHistory (bool createIfNeeded = false)
gets the contentHistory. possibly creates a new one (if createIfNeeded)
{
  if (!m_contentHistory && createIfNeeded)
    m_contentHistory = new TContentHistory(false);
  return m_contentHistory;
}
Referenced by loadTnzFile(), and save().
getCurrentCamera()
TCamera * ToonzScene::getCurrentCamera ()
Return a pointer to current camera TCamera.
{
  return getXsheet()->getStageObjectTree()->getCurrentCamera();
}
References TStageObjectTree::getCurrentCamera(), TXsheet::getStageObjectTree(), and getXsheet().
Referenced by PreviewSubCameraManager::deleteSubCamera(), EditTool::draw(), SceneViewer::getDpiFactor(), SceneViewer::getZoomScaleFittingWithScreen(), loadLevel(), RenderCommand::multimediaRender(), RasterSelection::pasteSelection(), and FxSettings::setFx().
getCurrentPreviewCamera()
TCamera * ToonzScene::getCurrentPreviewCamera ()
{
  return getXsheet()->getStageObjectTree()->getCurrentPreviewCamera();
}
getDefaultLevelPath()
TFilePath ToonzScene::getDefaultLevelPath (int levelType, std::wstring levelName = L"a") const
Return the default TFilePath of a levelType level
{
  TProject *project = getProject();
  assert(project);
  TFilePath levelPath;
  QString scanLevelType;
  switch (levelType) {
  case TZI_XSHLEVEL:
    scanLevelType = Preferences::instance()->getScanLevelType();
    levelPath     = TFilePath(levelName + L".." + scanLevelType.toStdWString());
    break;
  case PLI_XSHLEVEL:
    levelPath = TFilePath(levelName).withType("pli");
    break;
  case TZP_XSHLEVEL:
    levelPath = TFilePath(levelName).withType("tlv");
    break;
  case OVL_XSHLEVEL:
    levelPath = TFilePath(levelName + L"..tif");
    break;
  default:
    levelPath = TFilePath(levelName + L"..png");
  }
  if (!isUntitled() && Preferences::instance()->getPathAliasPriority() ==
                           Preferences::SceneFolderAlias)
    return TFilePath("$scenefolder") + levelPath;
  std::string folderName = getFolderName(levelType);
  if (project->getUseScenePath(folderName))
    return TFilePath("+" + folderName) + getSavePath() + levelPath;
  else
    return TFilePath("+" + folderName) + levelPath;
}
References getProject(), getSavePath(), isUntitled(), and TFilePath::withType().
Referenced by createNewLevel(), and getImportedLevelPath().
getFrameCount()
int ToonzScene::getFrameCount () const
Return scene frame count.
{
  TXsheet *xsh = getXsheet();
  return xsh ? xsh->getFrameCount() : 0;
}
References TXsheet::getFrameCount(), and getXsheet().
Referenced by XsheetViewer::changeWindowTitle(), OnRenderCompleted::onDeliver(), and OutputSettingsPopup::updateField().
getIconPath() [1/2]
TFilePath ToonzScene::getIconPath () const inline
{ return getIconPath(getScenePath()); }
getIconPath() [2/2]
TFilePath ToonzScene::getIconPath (const TFilePath & scenePath) static
Returns the path of the icon related to the scene
{
  return scenePath.getParentDir() + "sceneIcons" +
         (scenePath.getWideName() + L" .png");
}
References getIconPath(), and TFilePath::getParentDir().
Referenced by getIconPath().
getImportedLevelPath()
TFilePath ToonzScene::getImportedLevelPath (const TFilePath path) const
Loads a scene from file.
Returns
The coded path to be used for import. Builds the path to be used during a level import operation.
{
  if (TFileType::getInfo(path) == TFileType::AUDIO_LEVEL)
    return path.withParentDir(TFilePath("+extras"));
  else if (TFileType::getInfo(path) == TFileType::PALETTE_LEVEL)
    return path.withParentDir(TFilePath("+palettes"));
  const LevelType &ltype = getLevelType(path);
  if (ltype.m_ltype == UNKNOWN_XSHLEVEL) return path;
  const std::wstring &levelName = path.getWideName();
  const std::string &dots       = path.getDots();
  TFilePath importedLevelPath =
      getDefaultLevelPath(ltype.m_ltype, levelName).getParentDir() +
      path.getLevelNameW();
  if (dots == "..")
    importedLevelPath = importedLevelPath.withFrame(TFrameId::EMPTY_FRAME);
  if (importedLevelPath.getType() == "tlv")  // Type shouldn't have changed...
    importedLevelPath =
        importedLevelPath.withNoFrame();  // Plus, should be unnecessary...
  return importedLevelPath;
}
References getDefaultLevelPath(), TFilePath::getDots(), TFilePath::getParentDir(), TFilePath::getType(), TFilePath::withFrame(), and TFilePath::withParentDir().
getLevelNameWithoutSceneNumber()
std::wstring ToonzScene::getLevelNameWithoutSceneNumber (std::wstring orgName)
{
  if (!Preferences::instance()->isRemoveSceneNumberFromLoadedLevelNameEnabled())
    return orgName;
  QString orgNameQstr = QString::fromStdWString(orgName);
  // do nothing if the file name has less than 7 letters
  if (orgNameQstr.size() <= 6) return orgName;
  QString sceneName = QString::fromStdWString(getSceneName()).left(5);
  // check if the first 5 letters of the level name is the same as the scene
  // name.
  // note that we must consider following both cases; "c0001_hogehoge.tif" and
  // "c0001A_####.tif"
  if (!orgNameQstr.startsWith(sceneName)) return orgName;
  if (!orgNameQstr.contains("_")) return orgName;
  return orgNameQstr.right(orgNameQstr.size() - orgNameQstr.indexOf("_") - 1)
      .toStdWString();
}
getLevelSet()
TLevelSet * ToonzScene::getLevelSet () const inline
Returns a pointer to the scene's Level Set.
Referenced by createNewLevel(), SaveLevelAsPopup::execute(), IoCmd::loadResources(), XsheetGUI::CellArea::onReplaceByCastedLevel(), Vectorizer::setLevel(), TXshSoundColumn::setXsheet(), and Filmstrip::updateChooseLevelComboItems().
getProject()
TProject * ToonzScene::getProject () const
Returns a pointer to the project holding a scene instance.
The project associated with a scene could be different from the current project.
{ return m_project; }
Referenced by XsheetViewer::changeWindowTitle(), codeFilePath(), codeSavePath(), decodeFilePath(), getDefaultLevelPath(), and TProjectManager::initializeScene().
getProperties()
TSceneProperties * ToonzScene::getProperties () const inline
< Returns a pointer to the scene's properties.
  {
    return m_properties;
  }
Referenced by VectorizerPopup::apply(), StudioPaletteTreeViewer::dropEvent(), IoCmd::exportLevel(), SceneViewer::getDpiFactor(), OutputSettingsPopup::getProperties(), TProjectManager::initializeScene(), loadLevel(), FxBuilder::makePF(), RenderCommand::multimediaRender(), SetScanCropboxTool::onActivate(), OnRenderCompleted::onDeliver(), SetScanCropboxTool::onEnter(), TProjectManager::saveTemplate(), TXshSoundLevel::setScene(), TXshSoundColumn::setXsheet(), and updateSoundColumnFrameRate().
getSavePath()
TFilePath ToonzScene::getSavePath () const
Return save path of scene. If scene is in +scenes/name.tnz return name,
if scene is in +scenes/folder/name.tnz return folder/name
if scene is untitledxxx.tnz return untitledxxx.
{
  std::string sceneName = getScenePath().getName();
  if (isUntitled()) return TFilePath(sceneName);
  TFilePath sceneRoot = decodeFilePath(TFilePath("+" + TProject::Scenes));
  TFilePath scenePath = getScenePath().withType("");
  TFilePath savePath(sceneName);
  if (sceneRoot.isAncestorOf(scenePath)) savePath = scenePath - sceneRoot;
  return savePath;
}
References decodeFilePath(), TFilePath::getName(), getScenePath(), isUntitled(), TProject::Scenes, and TFilePath::withType().
Referenced by codeSavePath(), decodeSavePath(), getDefaultLevelPath(), and SceneResource::updatePath().
getSceneName()
std::wstring ToonzScene::getSceneName () const inline
Returns the scene's name.
  {
    return m_scenePath.getWideName();
  }
Referenced by XsheetViewer::changeWindowTitle().
getScenePath()
TFilePath ToonzScene::getScenePath () const inline
Returns the scene's file path.
Referenced by clear(), decodeFilePath(), getSavePath(), OutputSettingsPopup::onNameChanged(), save(), and OutputSettingsPopup::updateField().
getSoundColumns()
void ToonzScene::getSoundColumns (std::vector< TXshSoundColumn * > & columns)
Insert in vector columns all sound column of scene scene.
{
  ToonzScene *scene = this;
  std::set<TXsheet *> visited, toVisit;
  TXsheet *xsh = scene->getChildStack()->getTopXsheet();
  visited.insert(xsh);
  toVisit.insert(xsh);
  while (!toVisit.empty()) {
    xsh = *toVisit.begin();
    toVisit.erase(xsh);
    for (int i = 0; i < xsh->getColumnCount(); i++) {
      TXshColumn *column = xsh->getColumn(i);
      if (!column) continue;
      if (TXshSoundColumn *sc = column->getSoundColumn())
        columns.push_back(sc);
      else if (TXshCellColumn *cc = column->getCellColumn()) {
        int r0 = 0, r1 = -1;
        cc->getRange(r0, r1);
        if (!cc->isEmpty() && r0 <= r1) {
          for (int r = r0; r <= r1; r++) {
            TXshCell cell = cc->getCell(r);
            if (cell.m_level && cell.m_level->getChildLevel()) {
              TXsheet *subxsh = cell.m_level->getChildLevel()->getXsheet();
              if (visited.find(subxsh) == visited.end()) {
                visited.insert(subxsh);
                toVisit.insert(subxsh);
              }
            }
          }
        }
      }
    }
  }
}
References TXshLevel::getChildLevel(), getChildStack(), TXsheet::getColumn(), TXsheet::getColumnCount(), ChildStack::getTopXsheet(), and TXshChildLevel::getXsheet().
Referenced by updateSoundColumnFrameRate().
getTopXsheet()
TXsheet * ToonzScene::getTopXsheet () const
Returns the topmost xsheet in the scene's xsheet hierarchy.
{
  return m_childStack->getTopXsheet();
}
References ChildStack::getTopXsheet().
Referenced by TProjectManager::initializeScene(), Stage::RasterPainter::onRasterImage(), TTool::touchImage(), and Filmstrip::updateChooseLevelComboItems().
getVersionNumber()
VersionNumber ToonzScene::getVersionNumber () inline
{ return m_versionNumber; }
getXsheet()
TXsheet * ToonzScene::getXsheet () const
Returns a pointer to the scene's current xsheet.
{ return m_childStack->getXsheet(); }
References ChildStack::getXsheet().
Referenced by VectorizerPopup::apply(), getCurrentCamera(), getFrameCount(), loadLevel(), loadNoResources(), loadResources(), IoCmd::loadResources(), loadTnzFile(), OutputSettingsPopup::onCameraChanged(), renderFrame(), TProjectManager::saveTemplate(), and OutputSettingsPopup::updateField().
isExternPath()
bool ToonzScene::isExternPath (const TFilePath & fp) const
Return true if TFilePath fp is not contained in a project folder.
{
  TProject *project = m_project;
  assert(project);
  for (int i = 0; i < project->getFolderCount(); i++) {
    if (project->getFolderName(i) == "scenes") continue;
    TFilePath folderPath =
        decodeFilePath(TFilePath("+" + project->getFolderName(i)));
    if (folderPath.isAncestorOf(fp)) return false;
  }
  return true;
}
References decodeFilePath(), TProject::getFolderCount(), and TProject::getFolderName().
Referenced by IoCmd::loadResourceFolders(), and IoCmd::loadResources().
isLoading()
bool ToonzScene::isLoading () inline
{ return m_isLoading; }
isUntitled()
bool ToonzScene::isUntitled () const
Returns whether the scene path is empty, or the scene is explicitly untitled.
See also
Member function setUntitled().
{
  return m_scenePath == TFilePath() || m_isUntitled;
}
Referenced by clear(), getDefaultLevelPath(), getSavePath(), and save().
load()
void ToonzScene::load (const TFilePath & path, bool withProgressDialog = false)
{
  setIsLoading(true);
  try {
    loadNoResources(path);
    loadResources(withProgressDialog);
  } catch (...) {
    setIsLoading(false);
    throw;
  }
  setIsLoading(false);
}
loadFrameCount()
int ToonzScene::loadFrameCount (const TFilePath & fp)
Returns frame count stored in the scene header. Quicker than load(fp); getFrameCount()
{
  TIStream is(fp);
  if (!is) throw TException(fp.getWideString() + L": Can't open file");
  try {
    // Leggo il primo tag (<tnz/tab>) ed estraggo il framecount (se c'e')
    std::string tagName = "";
    if (!is.matchTag(tagName)) throw TException("Bad file format");
    if (tagName == "tab" || tagName == "tnz") {
      int frameCount;
      if (is.getTagParam("framecount", frameCount))
        return frameCount;
      else
        return 0;
    } else
      throw TException("Bad file format");
  } catch (TException &e) {
    throw TIStreamException(is, e);
  } catch (...) {
    throw TIStreamException(is);
  }
  return 0;
}
References TIStream::getTagParam(), and TIStream::matchTag().
loadLevel()
TXshLevel * ToonzScene::loadLevel (const TFilePath & actualPath, const LevelOptions * options = 0, std::wstring levelName = L"", const std::vector< TFrameId > & fIds = std::vector<TFrameId>())
of an old Toonz level, and converts it if needed.
The loadLevel() function accepts an optional pointer to the LevelOptions to be used by the level. If no option is explicitly specified, a level format match will be looked up in the application preferences; if none is found the default ones will be used.
Returns
A Pointer to the loaded level.
Parameters
options Loads a level from the specified decoded path.
{
  LevelType ltype = getLevelType(actualPath);
  if (ltype.m_ltype == UNKNOWN_XSHLEVEL) return 0;
  TFilePath levelPath = actualPath;
  // Ensure the level name is unique
  if (QString::fromStdWString(levelName).isEmpty()) {
    // if the option is set in the preferences,
    // remove the scene numbers("c####_") from the file name
    levelName = getLevelNameWithoutSceneNumber(levelPath.getWideName());
  }
  NameModifier nm(levelName);
  levelName = nm.getNext();
  while (m_levelSet->hasLevel(levelName)) levelName = nm.getNext();
  // Discriminate sound levels
  if (ltype.m_ltype == SND_XSHLEVEL) {
    TXshSoundLevel *sl = new TXshSoundLevel(levelName);
    sl->setType(ltype.m_ltype);
    sl->setScene(this);
    sl->setPath(codeFilePath(levelPath));
    try {
      sl->load();
    } catch (const std::string &msg)  // Intercepting std::string exceptions
    {
      throw TException(msg);
    }  // from load, and rethrowing... curious!
    m_levelSet->insertLevel(sl);
    return sl;
  } else {
    TXshSimpleLevel *xl = new TXshSimpleLevel(levelName);
    xl->setType(ltype.m_ltype);
    xl->setScene(this);
    if (!convertLevelIfNeeded(levelPath))
      return 0;  // Conversion failed, bail out
    xl->setPath(codeFilePath(levelPath), true);
    try {
      if (fIds.size() != 0 && !ltype.m_oldLevelFlag)
        xl->load(fIds);
      else
        xl->load();
    } catch (const std::string &msg) {
      throw TException(msg);
    }
    if (ltype.m_oldLevelFlag)
      xl->setDirtyFlag(true);  // Not set on old level formats?
    LevelProperties *lp = xl->getProperties();
    assert(lp);
    if (levelOptions)
      lp->options() = *levelOptions;
    else {
      const Preferences &prefs = *Preferences::instance();
      int formatIdx            = prefs.matchLevelFormat(
          levelPath);  // Should I use actualPath here? It's mostly
                                  // irrelevant anyway, it's for old tzp/tzu...
      if (formatIdx >= 0)
        lp->options() = prefs.levelFormat(formatIdx).m_options;
      else {
        // Default subsampling values are assigned from scene properties
        if (xl->getType() == OVL_XSHLEVEL)
          lp->setSubsampling(getProperties()->getFullcolorSubsampling());
        else if (xl->getType() == TZP_XSHLEVEL)
          lp->setSubsampling(getProperties()->getTlvSubsampling());
      }
    }
    if (lp->getDpiPolicy() == LevelProperties::DP_ImageDpi) {
      // We must check whether the image actually has a dpi.
      const TPointD &imageDpi = xl->getImageDpi();
      if (imageDpi == TPointD() ||
          Preferences::instance()->getUnits() == "pixel" ||
          Preferences::instance()->isIgnoreImageDpiEnabled()) {
        // Change to "Custom Dpi" policy and use camera dpi
        TStageObjectId cameraId =
            getXsheet()->getStageObjectTree()->getCurrentCameraId();
        lp->setDpiPolicy(LevelProperties::DP_CustomDpi);
        lp->setDpi(getCurrentCamera()->getDpi());
      } else {
        // Has dpi alright - assign it to custom dpi, too
        lp->setDpi(imageDpi);
      }
    }
    m_levelSet->insertLevel(xl);
    return xl;
  }
  return 0;
}
References codeFilePath(), convertLevelIfNeeded(), getCurrentCamera(), TStageObjectTree::getCurrentCameraId(), LevelProperties::getDpiPolicy(), getProperties(), TXshSimpleLevel::getProperties(), TXsheet::getStageObjectTree(), TXshLevel::getType(), getXsheet(), Preferences::levelFormat(), TXshSimpleLevel::load(), TXshSoundLevel::load(), Preferences::LevelFormat::m_options, Preferences::matchLevelFormat(), LevelProperties::options(), TXshSimpleLevel::setDirtyFlag(), LevelProperties::setDpi(), LevelProperties::setDpiPolicy(), TXshLevel::setScene(), TXshSoundLevel::setScene(), LevelProperties::setSubsampling(), and TXshLevel::setType().
Referenced by Vectorizer::setLevel().
loadNoResources()
void ToonzScene::loadNoResources (const TFilePath & path)
Loads a scene without loading its resources.
{
  clear();
  TProjectManager *pm    = TProjectManager::instance();
  TProjectP sceneProject = pm->loadSceneProject(fp);
  if (!sceneProject) return;
  setProject(sceneProject.getPointer());
  loadTnzFile(fp);
  getXsheet()->updateFrameCount();
}
References clear(), getXsheet(), TProjectManager::instance(), TProjectManager::loadSceneProject(), loadTnzFile(), setProject(), and TXsheet::updateFrameCount().
loadResources()
void ToonzScene::loadResources (bool withProgressDialog = false)
Loads the scene resources.
{
  /*--- m_levelSet->getLevelCount()10---*/
  QProgressDialog *progressDialog = 0;
  if (withProgressDialog && m_levelSet->getLevelCount() >= 10) {
    progressDialog = new QProgressDialog("Loading Scene Resources", "", 0,
                                         m_levelSet->getLevelCount());
    progressDialog->setModal(true);
    progressDialog->setAutoReset(
        true); /*--maximumreset--*/
    progressDialog->setAutoClose(true); /*--reset--*/
    progressDialog->setAttribute(Qt::WA_DeleteOnClose,
                                 true); /*--Delete--*/
    progressDialog->setCancelButton(0);
    progressDialog->setValue(0);
    progressDialog->show();
  }
  int i;
  for (i = 0; i < m_levelSet->getLevelCount(); i++) {
    if (progressDialog) progressDialog->setValue(i + 1);
    TXshLevel *level = m_levelSet->getLevel(i);
    try {
      level->load();
    } catch (...) {
    }
  }
  getXsheet()->updateFrameCount();
}
References getXsheet(), TXshLevel::load(), and TXsheet::updateFrameCount().
loadTnzFile()
void ToonzScene::loadTnzFile (const TFilePath & path)
Loads scene data from file, excluding the associated project and the scene resources.
{
  bool reading22 = false;
  TIStream is(fp);
  if (!is) throw TException(fp.getWideString() + L": Can't open file");
  try {
    std::string tagName = "";
    if (!is.matchTag(tagName)) throw TException("Bad file format");
    if (tagName == "tab" || tagName == "tnz") {
      std::string rootTagName = tagName;
      std::string v           = is.getTagAttribute("version");
      VersionNumber versionNumber(0, 0);
      int k = v.find(".");
      if (k != (int)std::string::npos && 0 < k && k < (int)v.length()) {
        versionNumber.first  = std::stoi(v.substr(0, k));
        versionNumber.second = std::stoi(v.substr(k + 1));
      }
      if (versionNumber == VersionNumber(0, 0))
        throw TException("Bad version number :" + v);
      setVersionNumber(versionNumber);
      is.setVersion(versionNumber);
      while (is.matchTag(tagName)) {
        if (tagName == "generator") {
          std::string program = is.getString();
          // TODO: This obsolete condition should be removed before releasing OT
          // v2.2 !
          reading22 = program.find("2.2") != std::string::npos;
        } else if (tagName == "properties")
          m_properties->loadData(is, false);
        else if (tagName == "palette")  // per compatibilita' beta1
        {
          TPalette *palette = new TPalette;
          is >> *palette;
          delete palette;
        } else if (tagName == "levelSet")
          m_levelSet->loadData(is);
        else if (tagName == "levels") {
          // obsoleto
          if (!reading22) assert(0);
          while (!is.eos()) {
            TPersist *p = 0;
            is >> p;
            TXshLevel *xshLevel = dynamic_cast<TXshLevel *>(p);
            if (xshLevel) {
              xshLevel->setScene(this);
              TXshSimpleLevel *sl = xshLevel->getSimpleLevel();
              if (reading22 && sl && sl->getPath() == TFilePath()) {
                sl->setType(PLI_XSHLEVEL);
                sl->setPath(TFilePath("+drawings/") +
                            (sl->getName() + L".pli"));
              }
              m_levelSet->insertLevel(xshLevel);
            }
          }
        } else if (tagName == "xsheet")
          is >> *getXsheet();
        else if (tagName == "history") {
          std::string historyData, s;
          while (!is.eos()) {
            is >> s;
            historyData += s;
          }
          TContentHistory *history = getContentHistory(true);
          history->deserialize(QString::fromStdString(historyData));
        } else
          throw TException(tagName + " : unexpected tag");
        if (!is.matchEndTag()) throw TException(tagName + " : missing end tag");
      }
      if (!is.matchEndTag())
        throw TException(rootTagName + " : missing end tag");
    } else
      throw TException("Bad file format");
    setScenePath(fp);
    for (int i = 0; i < m_levelSet->getLevelCount(); i++)
      m_levelSet->getLevel(i)->setScene(this);
  } catch (TException &e) {
    throw TIStreamException(is, e);
  } catch (...) {
    throw TIStreamException(is);
  }
  m_properties->cloneCamerasTo(getXsheet()->getStageObjectTree());
  fixBiancoProblem(this, getXsheet());
}
References TSceneProperties::cloneCamerasTo(), TIStream::eos(), getContentHistory(), TXshLevel::getName(), TXshSimpleLevel::getPath(), TXshLevel::getSimpleLevel(), TIStream::getString(), TIStream::getTagAttribute(), getXsheet(), TSceneProperties::loadData(), TIStream::matchEndTag(), TIStream::matchTag(), TXshLevel::setScene(), setScenePath(), TXshLevel::setType(), and TIStream::setVersion().
Referenced by loadNoResources().
renderFrame() [1/2]
void ToonzScene::renderFrame (const TRaster32P & ras, int row, const TXsheet * xsh, const TRectD & placedRect, const TAffine & worldToPlacedAff) const
Performs a camera-stand render of the specified xsheet in the specified placedRect, with known world/placed reference change - and returns the result on top of the specified 32-bit raster.
Performs a camera-stand render of the specified xsheet in the specified placedRect, with known world/placed reference change - and returns the result in a 32-bit raster.
{
  // Build reference change affines
  const TAffine &placedToOglRefAff =
      TScale(ras->getLx() / placedRect.getLx(),
             ras->getLy() / placedRect.getLy()) *
      TTranslation(-0.5 * (placedRect.x0 + placedRect.x1),
                   -0.5 * (placedRect.y0 + placedRect.y1));
  const TAffine &cameraAff =
      xsh->getPlacement(xsh->getStageObjectTree()->getCurrentCameraId(), row);
  const TAffine &worldToOglRefAff =
      placedToOglRefAff * worldToPlacedAff * cameraAff.inv();
  TRect clipRect(ras->getBounds());
// fix for plastic tool applied to subxsheet
#ifdef MACOSX
  QSurfaceFormat format;
  format.setProfile(QSurfaceFormat::CompatibilityProfile);
  std::unique_ptr<QOffscreenSurface> surface(new QOffscreenSurface());
  surface->setFormat(format);
  surface->create();
  glPushAttrib(GL_ALL_ATTRIB_BITS);
  glMatrixMode(GL_MODELVIEW), glPushMatrix();
  glMatrixMode(GL_PROJECTION), glPushMatrix();
#else
  TOfflineGL ogl(ras->getSize());
  currentOfflineGL = &ogl;
  ogl.makeCurrent();
#endif
  {
#ifdef MACOSX
    std::unique_ptr<QOpenGLFramebufferObject> fb(
        new QOpenGLFramebufferObject(ras->getLx(), ras->getLy()));
    fb->bind();
    assert(glGetError() == GL_NO_ERROR);
    glViewport(0, 0, ras->getLx(), ras->getLy());
    glMatrixMode(GL_PROJECTION);
    glLoadIdentity();
    gluOrtho2D(0, ras->getLx(), 0, ras->getLy());
    glMatrixMode(GL_MODELVIEW);
    glLoadIdentity();
#endif
    glTranslated(0.5 * ras->getLx(), 0.5 * ras->getLy(), 0.0);
    glClearColor(0.0f, 0.0f, 0.0f, 0.0f);
    glClear(GL_COLOR_BUFFER_BIT);
    ImagePainter::VisualSettings vs;
    vs.m_plasticVisualSettings.m_drawMeshesWireframe = false;
    Stage::RasterPainter painter(ras->getSize(), worldToOglRefAff, clipRect, vs,
                                 false);
    Stage::visit(painter, const_cast<ToonzScene *>(this),
                 const_cast<TXsheet *>(xsh), row);
    painter.flushRasterImages();
    glFlush();
#ifdef MACOSX
    QImage img =
        fb->toImage().scaled(QSize(ras->getLx(), ras->getLy()),
                             Qt::IgnoreAspectRatio, Qt::SmoothTransformation);
    int wrap      = ras->getLx() * sizeof(TPixel32);
    uchar *srcPix = img.bits();
    uchar *dstPix = ras->getRawData() + wrap * (ras->getLy() - 1);
    for (int y = 0; y < ras->getLy(); y++) {
      memcpy(dstPix, srcPix, wrap);
      dstPix -= wrap;
      srcPix += wrap;
    }
    fb->release();
    assert(glGetError() == GL_NO_ERROR);
#else
    TRop::over(ras, ogl.getRaster());
#endif
  }
#ifdef MACOSX
  glMatrixMode(GL_MODELVIEW), glPopMatrix();
  glMatrixMode(GL_PROJECTION), glPopMatrix();
  glPopAttrib();
#else
  ogl.doneCurrent();
  currentOfflineGL = 0;
#endif
}
References TStageObjectTree::getCurrentCameraId(), TXsheet::getPlacement(), TXsheet::getStageObjectTree(), TAffine::inv(), PlasticVisualSettings::m_drawMeshesWireframe, ImagePainter::VisualSettings::m_plasticVisualSettings, TRop::over(), Stage::visit(), and TRectT< T >::x0.
renderFrame() [2/2]
void ToonzScene::renderFrame (const TRaster32P & ras, int row, const TXsheet * xsh = 0, bool checkFlags = true) const
Performs a camera-stand render of the specified xsheet (or the main one in case none was specified), on its currently selected camera, and returns the result on top of the specified 32-bit raster.
{
  if (xsh == 0) xsh = getXsheet();
  TCamera *camera        = xsh->getStageObjectTree()->getCurrentCamera();
  TDimension cameraRes   = camera->getRes();
  TDimensionD cameraSize = camera->getSize();
  // voglio che la camera sia completamente contenuta dentro raster
  double sx = (double)ras->getLx() / (double)cameraSize.lx;
  double sy = (double)ras->getLy() / (double)cameraSize.ly;
  double sc = (sx < sy) ? sx : sy;
  const TAffine &cameraAff =
      xsh->getPlacement(xsh->getStageObjectTree()->getCurrentCameraId(), row);
  const TAffine &viewAff = TScale(sc / Stage::inch) * cameraAff.inv();
  TRect clipRect(ras->getBounds());
  TOfflineGL ogl(ras->getSize());
  currentOfflineGL = &ogl;
  ogl.makeCurrent();
  {
    glTranslated(0.5 * ras->getLx(), 0.5 * ras->getLy(), 0.0);
    glClearColor(0.0f, 0.0f, 0.0f, 0.0f);
    glClear(GL_COLOR_BUFFER_BIT);
    ImagePainter::VisualSettings vs;
    vs.m_plasticVisualSettings.m_drawMeshesWireframe = false;
    vs.m_forSceneIcon                                = true;
    Stage::RasterPainter painter(ras->getSize(), viewAff, clipRect, vs,
                                 checkFlags);
    Stage::visit(painter, const_cast<ToonzScene *>(this),
                 const_cast<TXsheet *>(xsh), row);
    painter.flushRasterImages();
    glFlush();
    TRop::over(ras, ogl.getRaster());
  }
  ogl.doneCurrent();
  currentOfflineGL = 0;
}
References TStageObjectTree::getCurrentCamera(), TStageObjectTree::getCurrentCameraId(), TXsheet::getPlacement(), TCamera::getRes(), TCamera::getSize(), TXsheet::getStageObjectTree(), getXsheet(), Stage::inch, TAffine::inv(), PlasticVisualSettings::m_drawMeshesWireframe, ImagePainter::VisualSettings::m_plasticVisualSettings, TRop::over(), and Stage::visit().
Referenced by texture_utils::getTextureData().
save()
void ToonzScene::save (const TFilePath & path, TXsheet * subxsheet = 0)
Saves the scene (or a sub-xsheet) at the specified path.
{
  TFilePath oldScenePath = getScenePath();
  TFilePath newScenePath = fp;
  CameraRedirection redir(this, subxsh);
  bool wasUntitled = isUntitled();
  setScenePath(fp);
  TFileStatus fs(newScenePath);
  if (fs.doesExist() && !fs.isWritable())
    throw TSystemException(newScenePath,
                           "The scene cannot be saved: it is a read only "
                           "scene.\n All resources have been saved.");
  TFilePath scenePath = decodeFilePath(fp);
  TFilePath scenePathTemp(scenePath.getWideString() +
                          QString(".tmp").toStdWString());
  if (Preferences::instance()->isBackupEnabled() &&
      oldScenePath == newScenePath && TFileStatus(scenePath).doesExist())
    saveBackup(scenePath);
  if (TFileStatus(scenePathTemp).doesExist())
    TSystem::removeFileOrLevel(scenePathTemp);
  //  TSystem::touchFile(scenePath);
  TSystem::touchFile(scenePathTemp);
  makeSceneIcon(this);
  // TOStream os(scenePath, compressionEnabled);
  //  TOStream os(scenePath, false);
  {
    TOStream os(scenePathTemp, false);
    if (!os.checkStatus())
      throw TException("Could not open temporary save file");
    TXsheet *xsh = subxsh;
    if (xsh == 0) xsh = m_childStack->getTopXsheet();
    std::map<std::string, std::string> attr;
    attr["version"] =
        (QString::number(l_currentVersion.first) +
         "."  // From now on, version numbers in saved files will have
         + QString::number(
               l_currentVersion.second))  // the signature "MAJOR.MINOR", where:
            .toStdString();               //
    attr["framecount"] =
        QString::number(  //    MAJOR = Toonz version number * 10 (eg 7.0 => 70)
            xsh->getFrameCount())
            .toStdString();  //    MINOR = Reset to 0 after each major
                             //    increment,
                             //    and
    //            advancing on its own when fixing bugs.
    os.openChild("tnz", attr);
    os.child("generator") << TEnv::getApplicationFullName();
    os.openChild("properties");
    m_properties->saveData(os);
    os.closeChild();
    if (subxsh) {
      std::set<TXshLevel *> saveSet;
      subxsh->getUsedLevels(saveSet);
      m_levelSet->setSaveSet(saveSet);
    }
    os.openChild("levelSet");
    m_levelSet->saveData(os);
    os.closeChild();
    std::set<TXshLevel *> emptySaveSet;
    m_levelSet->setSaveSet(emptySaveSet);
    os.openChild("xsheet");
    os << *xsh;
    os.closeChild();
    if (getContentHistory()) {
      os.openChild("history");
      QString data = getContentHistory()->serialize();
      int i        = 0, j;
      // non scrivo tutta la std::string di seguito per evitare problemi se
      // diventa
      // troppo lunga. Cerco di spezzarla in modo che sia "bella da leggere" nel
      // tnz
      while ((j = data.indexOf("||", i)) >= i) {
        os << data.mid(i, j - i + 1).toStdWString();
        os.cr();
        i = j + 1;
      }
      os << data.mid(i).toStdWString();
      os.closeChild();
    }
    os.closeChild();
    bool status = os.checkStatus();
    if (!status) throw TException("Could not complete the temporary save");
  }
  if (TFileStatus(scenePathTemp).doesExist())
    TSystem::renameFile(scenePath, scenePathTemp, true);
  if (subxsh) {
    setScenePath(oldScenePath);
    if (wasUntitled) setUntitled();
  } else {
    if (wasUntitled) deleteUntitledScene(oldScenePath.getParentDir());
  }
  // update the last saved version
  setVersionNumber(l_currentVersion);
}
References TOStream::checkStatus(), TOStream::child(), TOStream::closeChild(), TOStream::cr(), decodeFilePath(), getContentHistory(), TXsheet::getFrameCount(), TFilePath::getParentDir(), getScenePath(), ChildStack::getTopXsheet(), TXsheet::getUsedLevels(), isUntitled(), TOStream::openChild(), TContentHistory::serialize(), TLevelSet::setSaveSet(), setScenePath(), and setUntitled().
setIsLoading()
void ToonzScene::setIsLoading (bool isLoading) inline
{ m_isLoading = isLoading; }
setProject()
void ToonzScene::setProject (TProject * project)
Associates a scene to a project.
{
  assert(project);
  if (project != m_project) {
    if (project) project->addRef();
    if (m_project) m_project->release();
    m_project = project;
  }
}
Referenced by loadNoResources().
setSceneName()
void ToonzScene::setSceneName (std::wstring name)
Sets the scene's name.
{
  m_scenePath = m_scenePath.withName(name);
}
References TFilePath::withName().
setScenePath()
void ToonzScene::setScenePath (const TFilePath & p)
Sets the scene's file path.
{
  m_scenePath  = fp;
  m_isUntitled = false;
}
Referenced by loadTnzFile(), and save().
setUntitled()
void ToonzScene::setUntitled ()
Marks the scene as explicitly untitled.
An untitled scene generates unique temporary paths hosting any newly created scene content. Said content is then moved once a proper path is specified by the user.
{
  m_isUntitled               = true;
  const std::string baseName = "untitled";
  TFilePath tempDir          = getUntitledScenesDir();
  if (TFileStatus(tempDir).doesExist() == false) {
    try {
      TSystem::mkDir(tempDir);
    } catch (...) {
    }
  }
  std::string name = baseName;
  if (TFileStatus(tempDir + name).doesExist()) {
    int count = 2;
    do {
      name = baseName + std::to_string(count++);
    } while (TFileStatus(tempDir + name).doesExist());
  }
  TFilePath fp = tempDir + name + (name + ".tnz");
  try {
    TSystem::touchParentDir(fp);
  } catch (...) {
    assert(0);
  }
  m_scenePath = fp;
}
Referenced by TProjectManager::initializeScene(), and save().
setVersionNumber()
void ToonzScene::setVersionNumber (VersionNumber version) inline
{ m_versionNumber = version; }
shiftCameraX()
double ToonzScene::shiftCameraX (double val)
{
  TStageObjectTree *tree = getXsheet()->getStageObjectTree();
  TStageObject *stageObject = tree->getStageObject(tree->getCurrentCameraId());
  TPointD ret               = stageObject->getOffset();
  stageObject->setOffset(TPointD(ret.x + val, ret.y));
  return ret.x;
}
updateSoundColumnFrameRate()
void ToonzScene::updateSoundColumnFrameRate ()
Set output properties frameRate to all sound column of scene.
{
  std::vector<TXshSoundColumn *> soundColumns;
  getSoundColumns(soundColumns);
  TSceneProperties *properties = getProperties();
  if (!properties) return;
  TOutputProperties *outputProperties = properties->getOutputProperties();
  if (!outputProperties) return;
  double frameRate = outputProperties->getFrameRate();
  int i;
  for (i = 0; i < (int)soundColumns.size(); i++)
    soundColumns[i]->updateFrameRate(frameRate);
}
References TOutputProperties::getFrameRate(), TSceneProperties::getOutputProperties(), getProperties(), and getSoundColumns().
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/toonz/toonzscene.h
E:/opentoonz/toonz/sources/toonzlib/toonzscene.cpp