opentoonz: DVGui::IntField Class Reference
DVGui::IntField Class Reference
The IntField class provides to view an object to manage an integer parameter.
#include <intfield.h>
Signals
void valueChanged (bool isDragging)
void valueEditedByHand ()
Public Member Functions
IntField (QWidget *parent=0, bool isMaxRangeLimited=true, bool isRollerHide=true)
void setRange (int minValue, int maxValue)
void getRange (int &minValue, int &maxValue)
void setValue (int value)
int getValue ()
void setValues (int value, int minValue, int maxValue)
void enableSlider (bool enable)
bool sliderIsEnabled ()
void enableRoller (bool enable)
bool rollerIsEnabled ()
void setLineEditBackgroundColor (QColor color)
Protected Slots
void onSliderChanged (int value)
void onSliderReleased ()
void onEditingFinished ()
void onRollerValueChanged (bool isDragging)
Protected Member Functions
void setLinearSlider (bool linear)
Detailed Description
The IntField class provides to view an object to manage an integer parameter.
Inherits QWidget.
The class is composed of an horizontal layout which contains two object,
a vertical layout with a text field IntLineEdit and a roller
an horizontal slider QSlider. This objects are connected, so if you change one the other automatically change. You can set current value getValue(), minimum and max value using setValue(), setRange() or setValues(); by default is value = 0, minimum value = 0 and maximum value = 100.
Maximum height object is fixed to DVGui::WidgetHeight, width depend on parent width.
To know when integer parameter value change class provides a signal, valueChanged(); class emit signal when slider value change or when editing text field is finished and current value is changed. Editing text field finished may occur if focus is lost or enter key is pressed. See SLOT: onSliderChanged(int value), onEditingFinished().
Constructor & Destructor Documentation
IntField()
IntField::IntField (QWidget * parent = 0, bool isMaxRangeLimited = true, bool isRollerHide = true)
    : QWidget(parent)
    , m_lineEdit(0)
    , m_slider(0)
    , m_roller(0)
    , m_isMaxRangeLimited(isMaxRangeLimited)
    , m_isLinearSlider(true) {
  setObjectName("IntField");
  QHBoxLayout *layout = new QHBoxLayout(this);
  layout->setMargin(0);
  layout->setSpacing(5);
  QWidget *field = new QWidget(this);
  field->setMaximumWidth(43);
  QVBoxLayout *vLayout = new QVBoxLayout(field);
  vLayout->setMargin(0);
  vLayout->setSpacing(0);
  m_lineEdit = new DVGui::IntLineEdit(field);
  bool ret   = connect(m_lineEdit, SIGNAL(editingFinished()), this,
                     SLOT(onEditingFinished()));
  vLayout->addWidget(m_lineEdit);
  m_roller = new RollerField(field);
  ret      = ret && connect(m_roller, SIGNAL(valueChanged(bool)), this,
                       SLOT(onRollerValueChanged(bool)));
  vLayout->addWidget(m_roller);
  if (isRollerHide) enableRoller(false);
  layout->addWidget(field);
  m_slider = new QSlider(Qt::Horizontal, this);
  ret      = ret && connect(m_slider, SIGNAL(valueChanged(int)), this,
                       SLOT(onSliderChanged(int)));
  ret      = ret && connect(m_slider, SIGNAL(sliderReleased()), this,
                       SLOT(onSliderReleased()));
  ret = ret && connect(m_lineEdit, SIGNAL(editingFinished()), this,
                       SIGNAL(valueEditedByHand()));
  ret = ret && connect(m_slider, SIGNAL(sliderReleased()), this,
                       SIGNAL(valueEditedByHand()));
  layout->addWidget(m_slider);
  setValues(0, 0, 100);
  setLayout(layout);
  assert(ret);
}
~IntField()
DVGui::IntField::~IntField () inline
{}
Member Function Documentation
enableRoller()
void IntField::enableRoller (bool enable)
If enable is false set roller disable and hide it.
{
  m_roller->setEnabled(enable);
  if (enable)
    m_roller->show();
  else
    m_roller->hide();
}
enableSlider()
void IntField::enableSlider (bool enable)
If enable is false set slider disable and hide it.
{
  m_slider->setEnabled(enable);
  if (enable)
    m_slider->show();
  else
    m_slider->hide();
}
getRange()
void IntField::getRange (int & minValue, int & maxValue)
Set minValue and maxValue to IntField range.
See also
setRange()
{
  double min, max;
  m_roller->getRange(min, max);
  minValue = tround(min);
  maxValue = tround(max);
}
getValue()
int IntField::getValue ()
Return current value.
See also
setValue()
{ return (m_lineEdit->getValue()); }
References DVGui::IntLineEdit::getValue().
onEditingFinished
void IntField::onEditingFinished () protected slot
Set slider and roller value to current value in text field.
This protected slot is called when text editing is finished.
If slider value is different from text field value emit signal valueChanged().
{
  double value = m_lineEdit->getValue();
  // Controllo necessario per evitare che il segnale di cambiamento venga emesso
  // piu' volte.
  if ((pos2value(m_slider->value()) == value && m_slider->isVisible()) ||
      ((int)m_roller->getValue() == value && m_roller->isVisible()))
    return;
  m_slider->setValue(value2pos(value));
  m_roller->setValue((double)value);
  emit valueChanged(false);
}
References DVGui::IntLineEdit::getValue(), and valueChanged().
onRollerValueChanged
void IntField::onRollerValueChanged (bool isDragging) protected slot
Set text field and slider to roller current value.
If slider and text field value are different from roller value emit signal valueChanged().
{
  int value = m_roller->getValue();
  if (value == m_lineEdit->getValue()) {
    assert(pos2value(m_slider->value()) == value || !m_slider->isVisible());
    // Se isDragging e' falso e' giusto che venga emessa la notifica di
    // cambiamento.
    if (!isDragging) emit valueChanged(isDragging);
    return;
  }
  m_slider->setValue(value2pos(value));
  m_lineEdit->setValue(value);
  // Faccio in modo che il cursore sia sulla prima cifra, cosi' se la stringa
  // da visualizzare e' piu' lunga del campo le cifre che vengono troncate sono
  // le ultime e non le prime (dovrebbero essere quelle dopo la virgola).
  m_lineEdit->setCursorPosition(0);
  emit valueChanged(isDragging);
}
References DVGui::IntLineEdit::getValue(), DVGui::IntLineEdit::setValue(), and valueChanged().
onSliderChanged
void IntField::onSliderChanged (int value) protected slot
Set to value the text field. If text field value is different from value emit signal valueChanged().
{
  int value = pos2value(sliderPos);
  // Controllo necessario per evitare che il segnale di cambiamento venga emesso
  // piu' volte.
  if (m_lineEdit->getValue() == value ||
      ((int)m_roller->getValue() == value && m_roller->isVisible()))
    return;
  m_lineEdit->setValue(value);
  m_roller->setValue((double)value);
  // Faccio in modo che il cursore sia sulla prima cifra, cosi' se la stringa
  // da visualizzare e' piu' lunga del campo le cifre che vengono troncate sono
  // le ultime e non le prime (dovrebbero essere quelle dopo la virgola).
  m_lineEdit->setCursorPosition(0);
  emit valueChanged(true);
}
References DVGui::IntLineEdit::getValue(), DVGui::IntLineEdit::setValue(), and valueChanged().
onSliderReleased
void DVGui::IntField::onSliderReleased () inline protected slot
{ emit valueChanged(false); }
rollerIsEnabled()
bool IntField::rollerIsEnabled ()
{ return m_roller->isEnabled(); }
setLinearSlider()
void DVGui::IntField::setLinearSlider (bool linear) inline protected
{ m_isLinearSlider = linear; }
setLineEditBackgroundColor()
void IntField::setLineEditBackgroundColor (QColor color)
{
  m_lineEdit->setLineEditBackgroundColor(color);
}
setRange()
void IntField::setRange (int minValue, int maxValue)
Set to minValue and maxValue slider and text field range.
See also
getRange()
{
  m_lineEdit->setRange(minValue, m_isMaxRangeLimited
                                     ? maxValue
                                     : (std::numeric_limits<int>::max)());
  if (m_isLinearSlider)
    m_slider->setRange(minValue, maxValue);
  else
    m_slider->setRange(minValue * pow(10., NonLinearSliderPrecision),
                       maxValue * pow(10., NonLinearSliderPrecision));
  m_roller->setRange(minValue, maxValue);
}
References DVGui::IntLineEdit::setRange().
Referenced by setValues().
setValue()
void IntField::setValue (int value)
Set to value current value IntField.
See also
getValue()
{
  if (m_lineEdit->getValue() == value) return;
  m_lineEdit->setValue(value);
  m_slider->setSliderPosition(value2pos(value));
  m_roller->setValue((double)value);
}
References DVGui::IntLineEdit::getValue(), and DVGui::IntLineEdit::setValue().
Referenced by setValues().
setValues()
void IntField::setValues (int value, int minValue, int maxValue)
This is provided for convenience. Set to value current value IntField; set to minValue and maxValue slider and text field range.
See also
getValue()
{
  setRange(minValue, maxValue);
  setValue(value);
}
References setRange(), and setValue().
sliderIsEnabled()
bool IntField::sliderIsEnabled ()
{ return m_slider->isEnabled(); }
valueChanged
void DVGui::IntField::valueChanged (bool isDragging) signal
This is a signal emitted when IntField, slider or text field, value change; if slider position change or text field editing is finished.
See also
onEditingFinished() and onSliderChanged(int value).
Referenced by onEditingFinished(), onRollerValueChanged(), and onSliderChanged().
valueEditedByHand
void DVGui::IntField::valueEditedByHand () signal
This signal is emitted only when the user edit the value by hand
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/toonzqt/intfield.h
E:/opentoonz/toonz/sources/toonzqt/intfield.cpp