opentoonz: TOStream Class Reference
TOStream Class Reference
Toonz's XML-like output file parser.
#include <tstream.h>
Classes
class Imp
Public Member Functions
TOStream (const TFilePath &fp, bool compressed=false)
Opens the specified file for write.
~TOStream ()
Closes the file and destroys the stream.
operator bool () const
Returns whether the stream has a valid status.
TOStream & operator<< (int v)
Writes an int to the stream.
TOStream & operator<< (double v)
Writes a double to the stream.
TOStream & operator<< (std::string v)
Writes a string to the stream.
TOStream & operator<< (std::wstring v)
Writes a wstring to the stream.
TOStream & operator<< (const TFilePath &v)
Writes a TFilePath to the stream.
TOStream & operator<< (const TPixel32 &v)
Writes a TPixel32 to the stream.
TOStream & operator<< (const TPixel64 &v)
Writes a TPixel64 to the stream.
TOStream & operator<< (QString v)
Writes a QString to the stream.
TOStream & operator<< (TPersist *v)
deprecated Use operator<<(TPersist&) instead.
TOStream & operator<< (TPersist &v)
TOStream child (std::string tagName)
to the reimplemented TPersist::saveData.
void openChild (std::string tagName)
void openChild (std::string tagName, const std::map< std::string, std::string > &attributes)
Writes a <tagName attribute1="value1" ..>
void openCloseChild (std::string tagName, const std::map< std::string, std::string > &attributes)
to the stream, opening a tag with embedded attributes.
void closeChild ()
void cr ()
Writes carriage return to the stream.
void tab (int dt)
TFilePath getFilePath ()
TFilePath getRepositoryPath ()
bool checkStatus () const
Flushes the stream and checks its validity.
std::string getCurrentTagName ()
Detailed Description
Toonz's XML-like output file parser.
This class is Toonz's standard output parser for simple XML files. It is specifically designed to interact with object types derived from the TPersist base class.
Constructor & Destructor Documentation
TOStream()
TOStream::TOStream (const TFilePath & fp, bool compressed = false)
Opens the specified file for write.
Parameters
fp Output file path
compressed Enables compression of the whole file
Note
Stream construction does not throw . However, the stream status could be invalid. Remember to check the stream validity using operator bool().
Warning
Stream compression has been verified to be unsafe. Please consider it deprecated.
                                                       : m_imp(new Imp) {
  m_imp->m_filepath = fp;
  if (compressed) {
    m_imp->m_os         = &m_imp->m_ostringstream;
    m_imp->m_compressed = true;
    m_imp->m_chanOwner  = false;
  } else {
    std::unique_ptr<Tofstream> os(new Tofstream(fp));
    m_imp->m_os        = os->isOpen() ? os.release() : 0;
    m_imp->m_chanOwner = true;
  }
  m_imp->m_justStarted = true;
}
~TOStream()
TOStream::~TOStream ()
Closes the file and destroys the stream.
                    {
  if (!m_imp) {
    return;
  }
  try {
    if (!m_imp->m_tagStack.empty()) {
      string tagName = m_imp->m_tagStack.back();
      m_imp->m_tagStack.pop_back();
      assert(tagName != "");
      ostream &os = *m_imp->m_os;
      m_imp->m_tab--;
      if (!m_imp->m_justStarted) cr();
      os << "</" << tagName << ">";
      cr();
      m_imp->m_justStarted = true;
    } else {
      if (m_imp->m_compressed) {
        std::string tmp = m_imp->m_ostringstream.str();
        const void *in  = (const void *)tmp.c_str();
        size_t in_len = strlen((char *)in);
        size_t out_len = LZ4F_compressFrameBound(in_len, NULL);
        void *out      = malloc(out_len);
        out_len = LZ4F_compressFrame(out, out_len, in, in_len, NULL);
        if (!LZ4F_isError(out_len)) {
          Tofstream os(m_imp->m_filepath);
          // TNZC <lunghezza dati decompress> <lunghezza dati compresso> <dati
          // compressi>
          os.write("TABc", 4);
          TINT32 v;
          v = 0x0A0B0C0D;
          os.write((char *)&v, sizeof v);
          v = in_len;
          os.write((char *)&v, sizeof v);
          v = out_len;
          os.write((char *)&v, sizeof v);
          os.write((char *)out, out_len);
        }
        free(out);
      }
      if (m_imp->m_chanOwner) delete m_imp->m_os;
    }
  } catch (...) {
  }
}
References cr().
Member Function Documentation
checkStatus()
bool TOStream::checkStatus () const
Flushes the stream and checks its validity.
\detail This function is similar to operator bool(), but flushes the stream before checking the status.
Returns
Whether the stream is in a good state (no fails in writing to).
{
  if (!m_imp->m_os) return false;
  m_imp->m_os->flush();
  return m_imp->m_os->rdstate() == ios_base::goodbit;
}
Referenced by OutputSettingsPopup::onAddPresetButtonPressed(), and ToonzScene::save().
child()
TOStream TOStream::child (std::string tagName)
to the reimplemented TPersist::saveData.
Deprecated:
Use openChild(string) instead
{
  assert(tagName != "");
  m_imp->m_tagStack.push_back(tagName);
  return TOStream(m_imp);
}
Referenced by OutputSettingsPopup::onAddPresetButtonPressed(), ToonzScene::save(), TXshMeshColumn::saveData(), TXshPaletteColumn::saveData(), PlasticSkeletonVertex::saveData(), PlasticSkeleton::saveData(), PlasticSkeletonVertexDeformation::saveData(), PlasticSkeletonDeformation::saveData(), TDoubleParam::saveData(), TExternalProgramFx::saveData(), TFarmTask::saveData(), TFx::saveData(), TStageObjectSpline::saveData(), TXshChildLevel::saveData(), TXshLevelColumn::saveData(), TXshPaletteLevel::saveData(), TXshSimpleLevel::saveData(), TXshSoundLevel::saveData(), TXshSoundTextColumn::saveData(), TXshSoundTextLevel::saveData(), TXshZeraryFxColumn::saveData(), VectorizerParameters::saveData(), TPalette::saveData(), and TStageObjectTree::saveData().
closeChild()
void TOStream::closeChild ()
to the stream, opening a tag with embedded attributes which is immediately closed. Closes current tag, writing </currentTagName> to the stream.
{
  assert(!m_imp->m_tagStack.empty());
  string tagName = m_imp->m_tagStack.back();
  m_imp->m_tagStack.pop_back();
  assert(tagName != "");
  // ostream &os = *m_imp->m_os; //os non e' usato
  m_imp->m_tab--;
  if (!m_imp->m_justStarted) cr();
  *(m_imp->m_os) << "</" << tagName << ">";
  cr();
  m_imp->m_justStarted = true;
}
References cr().
Referenced by OutputSettingsPopup::onAddPresetButtonPressed(), ToonzScene::save(), TProject::save(), TParamSet::saveData(), TXshMeshColumn::saveData(), TXshPaletteColumn::saveData(), PlasticSkeleton::saveData(), PlasticSkeletonDeformation::saveData(), ShaderInterface::ParameterConcept::saveData(), ShaderInterface::Parameter::saveData(), ShaderInterface::ShaderData::saveData(), ShaderInterface::saveData(), TDoubleParam::saveData(), TExternalProgramFx::saveData(), TFarmTask::saveData(), TFarmTaskGroup::saveData(), TFx::saveData(), TMacroFx::saveData(), TTextureMesh::saveData(), TStageObjectSpline::saveData(), TXsheet::saveData(), TXshLevelColumn::saveData(), TXshSoundTextColumn::saveData(), TXshSoundTextLevel::saveData(), TXshZeraryFxColumn::saveData(), VectorizerParameters::saveData(), TPalette::saveData(), TPointParam::saveData(), TPixelParam::saveData(), TRangeParam::saveData(), TSpectrumParam::saveData(), TToneCurveParam::saveData(), BrushData::saveData(), VectorBrushData::saveData(), CtrlFarmTask::saveData(), TStageObjectTree::saveData(), and CleanupSettingsModel::saveSettings().
cr()
void TOStream::cr ()
Writes carriage return to the stream.
Deprecated:
                  {
  *(m_imp->m_os) << endl;
  for (int i = 0; i < m_imp->m_tab; i++) *(m_imp->m_os) << "  ";
  m_imp->m_justStarted = false;
}
Referenced by closeChild(), openCloseChild(), operator<<(), ToonzScene::save(), and ~TOStream().
getCurrentTagName()
std::string TOStream::getCurrentTagName ()
{
  return (m_imp->m_tagStack.empty()) ? "" : m_imp->m_tagStack.back();
}
getFilePath()
TFilePath TOStream::getFilePath ()
Returns the file path of the file associated to this output stream.
{ return m_imp->m_filepath; }
Referenced by ShaderInterface::ShaderData::saveData().
getRepositoryPath()
TFilePath TOStream::getRepositoryPath ()
Deprecated:
{
  TFilePath fp = m_imp->m_filepath;
  return fp.getParentDir() + (fp.getName() + "_files");
}
References TFilePath::getName(), and TFilePath::getParentDir().
openChild()
void TOStream::openChild (std::string tagName)
Writes a <tagName> to the stream, opening a tag.
Referenced by OutputSettingsPopup::onAddPresetButtonPressed(), ToonzScene::save(), TProject::save(), TParamSet::saveData(), TXshMeshColumn::saveData(), TXshPaletteColumn::saveData(), PlasticSkeleton::saveData(), PlasticSkeletonDeformation::saveData(), ShaderInterface::ParameterConcept::saveData(), ShaderInterface::Parameter::saveData(), ShaderInterface::ShaderData::saveData(), ShaderInterface::saveData(), TDoubleParam::saveData(), TExternalProgramFx::saveData(), TFarmTask::saveData(), TFarmTaskGroup::saveData(), TFx::saveData(), TMacroFx::saveData(), TTextureMesh::saveData(), TStageObjectSpline::saveData(), TXsheet::saveData(), TXshLevelColumn::saveData(), TXshSoundTextColumn::saveData(), TXshSoundTextLevel::saveData(), TXshZeraryFxColumn::saveData(), VectorizerParameters::saveData(), TPalette::saveData(), TPointParam::saveData(), TPixelParam::saveData(), TRangeParam::saveData(), TSpectrumParam::saveData(), TToneCurveParam::saveData(), BrushData::saveData(), VectorBrushData::saveData(), CtrlFarmTask::saveData(), TStageObjectTree::saveData(), and CleanupSettingsModel::saveSettings().
openCloseChild()
void TOStream::openCloseChild (std::string tagName, const std::map< std::string, std::string > & attributes)
to the stream, opening a tag with embedded attributes.
Writes a tag <tagName attribute1="value1" ../>
{
  assert(tagName != "");
  // m_imp->m_tagStack.push_back(tagName);
  if (m_imp->m_justStarted == false) cr();
  *(m_imp->m_os) << "<" << tagName;
  for (std::map<std::string, string>::const_iterator it = attributes.begin();
       it != attributes.end(); ++it) {
    *(m_imp->m_os) << " " << it->first << "=\"" << escape(it->second) << "\"";
  }
  *(m_imp->m_os) << "/>";
  // m_imp->m_tab++;
  cr();
  m_imp->m_justStarted = true;
}
References cr().
Referenced by TProject::save(), TExternalProgramFx::saveData(), TMacroFx::saveData(), and TXshSimpleLevel::saveData().
operator bool()
TOStream::operator bool () const
Returns whether the stream has a valid status.
See also
std::basic_ostream::operator void*().
{ return (m_imp->m_os && *m_imp->m_os); }
operator<<() [1/9]
TOStream & TOStream::operator<< (const TFilePath & v)
Writes a TFilePath to the stream.
{
  return operator<<(v.getWideString());
}
References operator<<().
operator<<() [2/9]
TOStream & TOStream::operator<< (const TPixel32 & v)
Writes a TPixel32 to the stream.
{
  ostream &os = *(m_imp->m_os);
  os << (int)v.r << " " << (int)v.g << " " << (int)v.b << " " << (int)v.m
     << " ";
  m_imp->m_justStarted = false;
  return *this;
}
operator<<() [3/9]
TOStream & TOStream::operator<< (const TPixel64 & v)
Writes a TPixel64 to the stream.
{
  ostream &os = *(m_imp->m_os);
  os << (int)v.r << " " << (int)v.g << " " << (int)v.b << " " << (int)v.m
     << " ";
  m_imp->m_justStarted = false;
  return *this;
}
operator<<() [4/9]
TOStream & TOStream::operator<< (double v)
Writes a double to the stream.
{
  if (areAlmostEqual(v, 0))  // con valori molto piccoli (es. 1.4e-310) non
                             // riesce a rileggerli!
    v = 0;
  *(m_imp->m_os) << v << " ";
  m_imp->m_justStarted = false;
  return *this;
}
operator<<() [5/9]
TOStream & TOStream::operator<< (int v)
Writes an int to the stream.
{
  *(m_imp->m_os) << v << " ";
  m_imp->m_justStarted = false;
  return *this;
}
Referenced by operator<<().
operator<<() [6/9]
TOStream & TOStream::operator<< (QString v)
Writes a QString to the stream.
{
  string v = _v.toStdString();
  ostream &os = *(m_imp->m_os);
  int len     = v.length();
  if (len == 0) {
    os << "\"\""
       << " ";
    m_imp->m_justStarted = false;
    return *this;
  }
  int i;
  for (i = 0; i < len; i++)
    if ((!iswalnum(v[i]) && v[i] != '_' && v[i] != '%') ||
        v[i] < 32      // Less than ASCII for SPACE
        || v[i] > 126  // Greater than ASCII for ~
        )
      break;
  if (i == len)
    os << v << " ";
  else {
    os << '"' << escape(v) << '"';
  }
  m_imp->m_justStarted = false;
  return *this;
}
operator<<() [7/9]
TOStream & TOStream::operator<< (std::wstring v)
Writes a wstring to the stream.
{
  return operator<<(::to_string(v));
  /*
ostream &os = *(m_imp->m_os);
int len = v.length();
if(len==0)
{
os << "\"" << "\"" << " ";
m_imp->m_justStarted = false;
return *this;
}
int i;
for(i=0;i<len;i++)
if(!iswalnum(v[i]) && v[i]!=L'_')
break;
if(i==len)
{
os << v;
os << " ";
}
else
{
os.put('"');
for(i=0;i<len;i++)
 if(iswalnum(v[i]))
   os.put((char)v[i]);
 else if(v[i]=='"')
   os << "\\\"";
 else if(v[i]=='\n')
   os << "\\n";
 else if(iswprint(v[i]))
   os << v[i];
 else
   {os.put('\\'); os << (int)v[i];}
os << "\" ";
}
m_imp->m_justStarted = false;
return *this;
*/
}
References operator<<().
operator<<() [8/9]
TOStream & TOStream::operator<< (TPersist & v)
Saves data to the stream according
{
  v.saveData(*this);
  return *this;
}
References TPersist::saveData().
operator<<() [9/9]
TOStream & TOStream::operator<< (TPersist * v)
deprecated Use operator<<(TPersist&) instead.
{
  Imp::PersistTable::iterator it = m_imp->m_table.find(v);
  if (it != m_imp->m_table.end()) {
    *(m_imp->m_os) << "<" << v->getStreamTag() << " id='" << it->second
                   << "'/>";
    m_imp->m_justStarted = false;
  } else {
    int id            = ++m_imp->m_maxId;
    m_imp->m_table[v] = id;
    *(m_imp->m_os) << "<" << v->getStreamTag() << " id='" << id << "'>";
    m_imp->m_tab++;
    cr();
    v->saveData(*this);
    m_imp->m_tab--;
    cr();
    *(m_imp->m_os) << "</" << v->getStreamTag() << ">";
    cr();
  }
  return *this;
}
References cr(), TPersist::getStreamTag(), and TPersist::saveData().
tab()
void TOStream::tab (int dt)
Deprecated:
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/tstream.h
E:/opentoonz/toonz/sources/common/tstream/tstream.cpp