opentoonz: ImageLoader Class Reference
ImageLoader Class Reference final
#include <imagebuilders.h>
Classes
struct BuildExtData
Public Member Functions
ImageLoader (const TFilePath &path, const TFrameId &fid)
bool isImageCompatible (int imFlags, void *extData) override
void buildAllIconsAndPutInCache (TXshSimpleLevel *level, std::vector< TFrameId > fids, std::vector< std::string > iconIds, bool cacheImagesAsWell) override
void setFid (const TFrameId &fid) override
Public Member Functions inherited from ImageBuilder
virtual ImageBuilder * clone ()=0
virtual TImageP build (ImageInfo *info, const TRasterP &ras)=0
bool imageCached ()
bool imageModified ()
virtual bool isImageCompatible (int imFlags, void *extData)
virtual bool areInfosCompatible (int imFlags, void *extData)
Public Member Functions inherited from TSmartObject
TSmartObject (ClassCode classCode)
void addRef ()
void release ()
TINT32 getRefCount () const
Protected Member Functions
bool getInfo (TImageInfo &info, int imFlags, void *extData) override
TImageP build (int imFlags, void *extData) override
void invalidate () override
Clears the builder's cached data.
int buildSubsampling (int imFlags, BuildExtData *data)
virtual TImageP build (int imFlags, void *extData)=0
virtual bool getInfo (TImageInfo &info, int imFlags, void *extData)=0
virtual void buildAllIconsAndPutInCache (TXshSimpleLevel *, std::vector< TFrameId >, std::vector< std::string >, bool)
virtual void setFid (const TFrameId &fid)
virtual void invalidate ()
Clears the builder's cached data.
Additional Inherited Members
Public Types inherited from TSmartObject
typedef short ClassCode
Static Public Member Functions inherited from ImageBuilder
static bool setImageInfo (TImageInfo &info, const TDimension &size)
static bool setImageInfo (TImageInfo &info, TImage *img)
static bool setImageInfo (TImageInfo &info, TImageReader *ir)
Static Public Member Functions inherited from TSmartObject
static TINT32 getInstanceCount (ClassCode code)
Protected Attributes inherited from ImageBuilder
TImageInfo m_info
Currently cached image data - size, bpp, etc.
int m_imFlags
Currently cached image control flags.
Detailed Description
ImageLoader is the specialized ImageBuilder class used to automatically load images from a level file on hard disk.
Refer to ImageLoader::BuildExtData for a description of the allowed options for image loading.
Constructor & Destructor Documentation
ImageLoader()
ImageLoader::ImageLoader (const TFilePath & path, const TFrameId & fid)
    : m_path(path), m_fid(fid), m_subsampling(0), m_64bitCompatible(false) {}
Member Function Documentation
build()
TImageP ImageLoader::build (int imFlags, void * extData) override protected virtual
Builds the image as specified by the supplied control flags and external data.
Implements ImageBuilder.
{
  assert(extData);
  // Extract external data
  BuildExtData *data = static_cast<BuildExtData *>(extData);
  int subsampling = buildSubsampling(imFlags, data);
  try {
    // Initialize level reader
    TLevelReaderP lr(m_path);
    if (!lr) return TImageP();
    // Load info in cases where it's required first
    lr->doReadPalette(false);
    if ((m_path.getType() == "pli") || (m_path.getType() == "svg") ||
        (m_path.getType() == "psd"))
      lr->loadInfo();
    bool isTlvIcon = data->m_icon && m_path.getType() == "tlv";
    // for TLV icons, palettes will be applied in IconGenerator later
    if (!isTlvIcon) lr->doReadPalette(true);  // Allow palette loading
    TImageReaderP ir = lr->getFrameReader(m_fid);
    bool enable64bit = (imFlags & ImageManager::is64bitEnabled);
    ir->enable16BitRead(enable64bit);  // Set 64-bit loading if required
    // Load the image
    TImageP img;
    if (isTlvIcon)
      img = ir->loadIcon();  // TODO: Why just in the tlv case??
    else {
      ir->setShrink(subsampling);
      img = ir->load();
    }
    ir->enable16BitRead(false);
    if (!img) return img;  // There was an error loading the image.
    TPalette *palette = data->m_sl->getPalette();
    if (palette) img->setPalette(palette);
    if (subsampling > 1) {
      // Store the subsampling info in the image
      if (TRasterImageP ri = img)
        ri->setSubsampling(subsampling);
      else if (TToonzImageP ti = img)
        ti->setSubsampling(subsampling);
    }
    // In case the image will be cached, store its subsampling and 64 bit
    // compatibility
    if (!(imFlags & ImageManager::dontPutInCache)) {
      m_subsampling = subsampling;
      m_64bitCompatible =
          data->m_sl->is16BitChannelLevel() ? enable64bit : true;
    }
    return img;
  } catch (...) {
    return TImageP();
  }
}
References TXshSimpleLevel::getPalette(), TFilePath::getType(), ImageLoader::BuildExtData::m_icon, ImageLoader::BuildExtData::m_sl, and TImage::setPalette().
buildAllIconsAndPutInCache()
void ImageLoader::buildAllIconsAndPutInCache (TXshSimpleLevel * level, std::vector< TFrameId > fids, std::vector< std::string > iconIds, bool cacheImagesAsWell) override virtual
Reimplemented from ImageBuilder.
{
  if (m_path.getType() != "tlv") return;
  if (fids.empty() || iconIds.empty()) return;
  /*- fidとアイコンidの数は同じはず -*/
  if ((int)fids.size() != (int)iconIds.size()) return;
  try {
    TLevelReaderP lr(m_path);
    if (!lr) return;
    for (int i = 0; i < (int)fids.size(); i++) {
      lr->doReadPalette(false);
      TImageReaderP ir = lr->getFrameReader(fids[i]);
      lr->doReadPalette(true);
      TImageInfo info;
      TPalette *palette     = level->getPalette();
      std::string fullImgId = level->getImageId(fids[i]);
      /*- 画像データも一緒にキャッシュする場合 -*/
      if (cacheImagesAsWell) {
        ir->enable16BitRead(m_64bitCompatible);
        ir->setShrink(1);
        TImageP fullImg = ir->load();
        if (fullImg) {
          if (palette) fullImg->setPalette(palette);
          TImageCache::instance()->add(fullImgId, fullImg, true);
          setImageInfo(info, fullImg.getPointer());
        }
      }
      /*- アイコンのロード -*/
      TImageP img = ir->loadIcon();
      ir->enable16BitRead(false);
      if (img) {
        if (palette) img->setPalette(palette);
        TImageCache::instance()->add(iconIds[i], img, true);
      }
    }
  } catch (...) {
    return;
  }
}
buildSubsampling()
int ImageLoader::buildSubsampling (int imFlags, BuildExtData * data) inline protected
{
  return (imFlags & ImageManager::toBeModified)
             ? 1
             : (data->m_subs > 0)
                   ? data->m_subs
                   : (m_subsampling > 0)
                         ? m_subsampling
                         : data->m_sl->getProperties()->getSubsampling();
}
getInfo()
bool ImageLoader::getInfo (TImageInfo & info, int imFlags, void * extData) override protected virtual
Returns the image infos as specified by the supplied control flags and external data.
Implements ImageBuilder.
{
  try {
    TLevelReaderP lr(m_path);
    TImageReaderP fr = lr->getFrameReader(m_fid);
    // NOTE: Currently not changing imageInfo's bpp stuff...
    //       Ignoring subsampling too...
    return ImageBuilder::setImageInfo(info, fr.getPointer());
  } catch (TException &e) {
    QString msg = QString::fromStdWString(e.getMessage());
    if (msg == QString("Old 4.1 Palette")) throw;
    return false;
  }
}
invalidate()
void ImageLoader::invalidate () override protected virtual
Clears the builder's cached data.
Reimplemented from ImageBuilder.
{
  ImageBuilder::invalidate();
  m_subsampling     = 0;
  m_64bitCompatible = false;
}
References ImageBuilder::invalidate().
isImageCompatible()
bool ImageLoader::isImageCompatible (int imFlags, void * extData) override virtual
Returns whether any currently cached image is compatible with requested specifications, Returning true prevents ImageBuilder::build() invocations, fetching the cached data instead. The default implementation returns true if m_info has positive m_lx and m_ly.
Reimplemented from ImageBuilder.
{
  assert(extData);
  BuildExtData *data        = static_cast<BuildExtData *>(extData);
  const TXshSimpleLevel *sl = data->m_sl;
  // NOTE: Vector and Mesh dont care about sub sampling rate and bit depth
  // compatibility.
  //       They are property of Raster.
  if (sl->getType() == PLI_XSHLEVEL || sl->getType() == MESH_XSHLEVEL)
    return true;
  int subsampling = buildSubsampling(imFlags, data);
  if (m_subsampling <= 0 || subsampling != m_subsampling) return false;
  if (m_64bitCompatible || !(imFlags & ImageManager::is64bitEnabled)) {
    return true;
  } else {
    return false;
  }
}
References TXshLevel::getType(), and ImageLoader::BuildExtData::m_sl.
setFid()
void ImageLoader::setFid (const TFrameId & fid) override virtual
Reimplemented from ImageBuilder.
{ m_fid = fid; }
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/toonzlib/imagebuilders.h
E:/opentoonz/toonz/sources/toonzlib/imagebuilders.cpp