opentoonz: TIStream Class Reference
TIStream Class Reference
Toonz's XML-like input file parser.
#include <tstream.h>
Classes
class Imp
Public Member Functions
TIStream (const TFilePath &is)
Opens the document at the specified path.
~TIStream ()
Destroys the stream.
operator bool () const
Returns whether the stream has a valid status.
TIStream & operator>> (int &v)
Reads an integer from the stream.
TIStream & operator>> (double &v)
Reads a double from the stream.
TIStream & operator>> (std::string &v)
Reads a string from the stream.
TIStream & operator>> (std::wstring &v)
Reads a wstring from the stream.
TIStream & operator>> (TFilePath &v)
Reads a TFilePath from the stream.
TIStream & operator>> (TPixel32 &v)
Reads a TPixel32 from the stream.
TIStream & operator>> (TPixel64 &v)
Reads a TPixel64 from the stream.
TIStream & operator>> (QString &v)
Reads an integer from the stream.
TIStream & operator>> (TPersist &v)
Reads a TPersist derived object data from the stream.
TIStream & operator>> (TPersist *&v)
std::string getString ()
Returns the stream content as a string, up to the next tag.
bool eos ()
Returns true in case of end of string (a StreamTag::EndTag.
bool matchTag (std::string &tagName)
is encountered or the string is empty).
bool matchEndTag ()
Attempts matching a StreamTag::EndTag.
bool getTagParam (std::string paramName, std::string &value)
Attempts retrieval of the value associated with the specified tag attribute in current tag.
bool getTagParam (std::string paramName, int &value)
bool isBeginEndTag ()
bool openChild (std::string &tagName)
void closeChild ()
bool match (char c) const
std::string getTagAttribute (std::string name) const
TFilePath getFilePath ()
TOStream::openChild(string, const map<std::string, string>&).
TFilePath getRepositoryPath ()
int getLine () const
VersionNumber getVersion () const
void setVersion (const VersionNumber &version)
void skipCurrentTag ()
std::string getCurrentTagName ()
Detailed Description
Toonz's XML-like input file parser.
This class is Toonz's standard input parser for simple XML files. It is specifically designed to interact with object types derived from the TPersist base class.
Constructor & Destructor Documentation
TIStream()
TIStream::TIStream (const TFilePath & is)
Opens the document at the specified path.
Warning
Stream construction may throw on files compressed using TOStream 's compression.
Even if construction does not throw, the stream could still be constructed with an invalid status. Remember to check the stream status using operator bool().
                                      : m_imp(new Imp) {
  m_imp->m_filepath = fp;
  m_imp->m_is       = new Tifstream(fp);
  if (m_imp->m_is->peek() == 'T')  // non comincia con '<' dev'essere compresso
  {
    bool swapForEndianess = false;
    unique_ptr<std::istream> is(m_imp->m_is);
    m_imp->m_is = 0;
    char magicBuffer[4];
    is->read(magicBuffer, 4);
    string magic(magicBuffer, 4);
    size_t in_len, out_len;
    if (magic == "TNZC") {
      // Tab3.0 beta
      is->read((char *)&out_len, sizeof out_len);
      is->read((char *)&in_len, sizeof in_len);
    } else if (magic == "TABc") {
      TINT32 v;
      is->read((char *)&v, sizeof v);
      printf("magic = %08X\n", v);
      if (v == 0x0A0B0C0D)
        swapForEndianess = false;
      else if (v == 0x0D0C0B0A)
        swapForEndianess = true;
      else {
        swapForEndianess = true;
        printf("UH OH!\n");
      }
      is->read((char *)&v, sizeof v);
      out_len = swapForEndianess ? swapTINT32(v) : v;
      is->read((char *)&v, sizeof v);
      in_len = swapForEndianess ? swapTINT32(v) : v;
    } else
      throw TException("Bad magic number");
    if (in_len <= 0 || in_len > 100000000)  // 100M di tnzfile (compresso)
                                            // sembrano proprio esagerati
      throw TException("Corrupted file");
    LZ4F_decompressionContext_t lz4dctx;
    LZ4F_errorCode_t err =
        LZ4F_createDecompressionContext(&lz4dctx, LZ4F_VERSION);
    if (LZ4F_isError(err)) throw TException("Couldn't decompress file");
    char *in = (char *)malloc(in_len);
    is->read((char *)in, in_len);
    m_imp->m_strbuffer.resize(out_len + 1000);  // per prudenza
    char *out = (char *)m_imp->m_strbuffer.c_str();
    size_t check_len = out_len;
    // size_t remaining = LZ4F_decompress(lz4dctx, out, &out_len, in, &in_len,
    // NULL);
    bool ok = lz4decompress(lz4dctx, out, &out_len, in, in_len);
    LZ4F_freeDecompressionContext(lz4dctx);
    free(in);
    if (!ok) throw TException("Couldn't decompress file");
    if (check_len != out_len) throw TException("corrupted file");
    m_imp->m_is = new istringstream(std::string(out, out_len));
  }
  m_imp->m_chanOwner = true;
}
~TIStream()
TIStream::~TIStream ()
Destroys the stream.
                    {
  if (m_imp->m_chanOwner) delete m_imp->m_is;
}
Member Function Documentation
closeChild()
void TIStream::closeChild ()
Deprecated:
Use matchEndTag() instead.
{
  if (!matchEndTag()) {
    string tagName;
    if (!m_imp->m_tagStack.empty()) tagName = m_imp->m_tagStack.back();
    if (tagName != "")
      throw TException("Expected \"" + tagName + "\" end tag");
    else
      throw TException("expected EndTag");
  }
}
References matchEndTag().
Referenced by TImageReaderMesh::load(), TParamSet::loadData(), ShaderInterface::ParameterConcept::loadData(), ShaderInterface::Parameter::loadData(), ShaderInterface::ShaderData::loadData(), ShaderInterface::loadData(), TExternalProgramFx::loadData(), TFx::loadData(), TMacroFx::loadData(), TTextureMesh::loadData(), TXshChildLevel::loadData(), TXsheet::loadData(), TXshLevelColumn::loadData(), TXshMeshColumn::loadData(), TXshPaletteColumn::loadData(), TXshPaletteLevel::loadData(), TXshSoundColumn::loadData(), TXshSoundTextColumn::loadData(), TXshZeraryFxColumn::loadData(), TPalette::loadData(), TPointParam::loadData(), TPixelParam::loadData(), TRangeParam::loadData(), TSpectrumParam::loadData(), TToneCurveParam::loadData(), CtrlFarmTask::loadData(), and TSceneProperties::loadData().
eos()
bool TIStream::eos ()
Returns true in case of end of string (a StreamTag::EndTag.
Deprecated:
                   {
  if (m_imp->matchTag())
    return m_imp->m_currentTag.m_type == StreamTag::EndTag;
  else
    return !(*m_imp->m_is);
}
Referenced by TParamSet::loadData(), TDoubleParam::loadData(), TFarmTask::loadData(), TFarmTaskGroup::loadData(), TFx::loadData(), TMacroFx::loadData(), TStageObjectSpline::loadData(), TXsheet::loadData(), TXshSoundColumn::loadData(), TPalette::loadData(), TPersistSet::loadData(), TSpectrumParam::loadData(), TSceneProperties::loadData(), TStageObjectTree::loadData(), and ToonzScene::loadTnzFile().
getCurrentTagName()
std::string TIStream::getCurrentTagName ()
{ return m_imp->m_tagStack.back(); }
getFilePath()
TFilePath TIStream::getFilePath ()
TOStream::openChild(string, const map<std::string, string>&).
Returns the stream's path (i.e. the opened filename associated to the input stream).
{ return m_imp->m_filepath; }
Referenced by ShaderInterface::ShaderData::loadData().
getLine()
int TIStream::getLine () const
Returns the line number of the stream +1.
Warning
I've not idea why the +1, though.
{ return m_imp->m_line + 1; }
getRepositoryPath()
TFilePath TIStream::getRepositoryPath ()
Deprecated:
{
  TFilePath fp = m_imp->m_filepath;
  return fp.getParentDir() + (fp.getName() + "_files");
}
References TFilePath::getName(), and TFilePath::getParentDir().
getString()
string TIStream::getString ()
Returns the stream content as a string, up to the next tag.
See also
operator>>(TPersist&)
Deprecated:
{
  istream &is = *(m_imp->m_is);
  string v    = "";
  m_imp->skipBlanks();
  char c = is.peek();
  while (c != '<') {
    is.get(c);
    c = is.peek();
    if (!is) throw TException("unexpected EOF");
    v.append(1, c);
  }
  return v;
}
Referenced by ToonzScene::loadTnzFile().
getTagAttribute()
string TIStream::getTagAttribute (std::string name) const
Deprecated:
See also
getTagParam(string, string&),
{
  StreamTag &tag = m_imp->m_currentTag;
  std::map<std::string, string>::const_iterator it =
      tag.m_attributes.find(name);
  if (it == tag.m_attributes.end())
    return "";
  else
    return it->second;
}
Referenced by ParamsPageSet::createControls(), TProject::load(), TDoubleParam::loadData(), TExternalProgramFx::loadData(), TMacroFx::loadData(), TXshSimpleLevel::loadData(), TSceneProperties::loadData(), TStageObjectTree::loadData(), TProjectManager::loadSceneProject(), and ToonzScene::loadTnzFile().
getTagParam() [1/2]
bool TIStream::getTagParam (std::string paramName, int & value)
See also
getTagParam(string, string&)
getTagParam() [2/2]
bool TIStream::getTagParam (std::string paramName, std::string & value)
Attempts retrieval of the value associated with the specified tag attribute in current tag.
Parameters
paramName Tag attribute name.
value Output value of the attribute.
Returns
Whether the tag attribute was found.
Referenced by TXshPaletteLevel::load(), TXshSimpleLevel::loadData(), TPalette::loadData(), and ToonzScene::loadFrameCount().
getVersion()
VersionNumber TIStream::getVersion () const
Returns the currently stored version of the opened document.
See also
setVersion()
{ return m_imp->m_versionNumber; }
Referenced by PlasticSkeletonDeformation::loadData(), TFx::loadData(), TMacroFx::loadData(), TStageObjectSpline::loadData(), TXshSoundColumn::loadData(), and TPalette::loadData().
isBeginEndTag()
bool TIStream::isBeginEndTag ()
Returns whether current tag is of type StreamTag::BeginEndTag.
{
  return m_imp->m_currentTag.m_type == StreamTag::BeginEndTag;
}
match()
bool TIStream::match (char c) const
{
  m_imp->skipBlanks();
  if (m_imp->m_is->peek() != c) return false;
  m_imp->m_is->get(c);
  if (c == '\r') m_imp->m_line++;
  return true;
}
matchEndTag()
bool TIStream::matchEndTag ()
Attempts matching a StreamTag::EndTag.
Returns
Whether an end tag was found.
{
  if (m_imp->m_tagStack.empty()) throw TException("tag stack empty");
  if (!m_imp->matchTag()) return false;
  if (m_imp->m_currentTag.m_type != StreamTag::EndTag) return false;
  if (m_imp->m_currentTag.m_name != m_imp->m_tagStack.back())
    throw TException("end tag mismatch");
  m_imp->m_tagStack.pop_back();
  m_imp->m_currentTag = StreamTag();
  return true;
}
Referenced by closeChild(), ParamsPageSet::createControls(), TXshPaletteLevel::load(), TProject::load(), PlasticSkeletonVertex::loadData(), PlasticSkeleton::loadData(), PlasticSkeletonVertexDeformation::loadData(), PlasticSkeletonDeformation::loadData(), TDoubleParam::loadData(), TFarmTask::loadData(), TFarmTaskGroup::loadData(), TStageObjectSpline::loadData(), TXsheet::loadData(), TXshSimpleLevel::loadData(), TXshSoundLevel::loadData(), TXshSoundTextLevel::loadData(), VectorizerParameters::loadData(), BrushData::loadData(), VectorBrushData::loadData(), TSceneProperties::loadData(), TStageObjectTree::loadData(), TProjectManager::loadSceneProject(), and ToonzScene::loadTnzFile().
matchTag()
bool TIStream::matchTag (std::string & tagName)
is encountered or the string is empty).
Parameters
tagName Output name of a matched tag.
Returns
Whether a tag was found. Attempts matching a tag and returns its name.
{
  if (!m_imp->matchTag()) return false;
  if (m_imp->m_currentTag.m_type == StreamTag::EndTag) return false;
  tagName                    = m_imp->m_currentTag.m_name;
  m_imp->m_currentTag.m_name = "";
  if (m_imp->m_currentTag.m_type != StreamTag::BeginEndTag)
    m_imp->m_tagStack.push_back(tagName);
  return true;
}
Referenced by ParamsPageSet::createControls(), TXshPaletteLevel::load(), TXshSimpleLevel::load(), TProject::load(), PlasticSkeletonVertexDeformation::loadData(), TDoubleParam::loadData(), TExternalProgramFx::loadData(), TFarmTask::loadData(), TFarmTaskGroup::loadData(), TMacroFx::loadData(), TStageObjectSpline::loadData(), TXshChildLevel::loadData(), TXshPaletteLevel::loadData(), TXshSimpleLevel::loadData(), TXshSoundLevel::loadData(), TXshSoundTextLevel::loadData(), TXshZeraryFxColumn::loadData(), VectorizerParameters::loadData(), TPalette::loadData(), BrushData::loadData(), VectorBrushData::loadData(), TSceneProperties::loadData(), TStageObjectTree::loadData(), ToonzScene::loadFrameCount(), TProjectManager::loadSceneProject(), and ToonzScene::loadTnzFile().
openChild()
bool TIStream::openChild (std::string & tagName)
Deprecated:
Use matchTag(string&) instead.
{
  if (!m_imp->matchTag()) return false;
  if (m_imp->m_currentTag.m_type != StreamTag::BeginTag) return false;
  tagName                    = m_imp->m_currentTag.m_name;
  m_imp->m_currentTag.m_name = "";
  m_imp->m_tagStack.push_back(tagName);
  return true;
}
Referenced by TImageReaderMesh::load(), TParamSet::loadData(), PlasticSkeletonVertex::loadData(), PlasticSkeleton::loadData(), PlasticSkeletonDeformation::loadData(), ShaderInterface::ParameterConcept::loadData(), ShaderInterface::Parameter::loadData(), ShaderInterface::ShaderData::loadData(), ShaderInterface::loadData(), TExternalProgramFx::loadData(), TFx::loadData(), TMacroFx::loadData(), TTextureMesh::loadData(), TXsheet::loadData(), TXshLevelColumn::loadData(), TXshMeshColumn::loadData(), TXshPaletteColumn::loadData(), TXshSoundColumn::loadData(), TXshSoundTextColumn::loadData(), TPalette::loadData(), TPointParam::loadData(), TPixelParam::loadData(), TRangeParam::loadData(), TSpectrumParam::loadData(), TToneCurveParam::loadData(), and CtrlFarmTask::loadData().
operator bool()
TIStream::operator bool () const
Returns whether the stream has a valid status.
See also
std::basic_istream::operator void*().
{ return (m_imp->m_is && *m_imp->m_is); }
operator>>() [1/9]
TIStream & TIStream::operator>> (double & v)
Reads a double from the stream.
{
  *(m_imp->m_is) >> v;
  return *this;
}
operator>>() [2/9]
TIStream & TIStream::operator>> (int & v)
Reads an integer from the stream.
{
  *(m_imp->m_is) >> v;
  return *this;
}
Referenced by operator>>().
operator>>() [3/9]
TIStream & TIStream::operator>> (QString & v)
Reads an integer from the stream.
{
  istream &is = *(m_imp->m_is);
  v           = "";
  m_imp->skipBlanks();
  char c;
  is.get(c);
  if (c == '\"') {
    is.get(c);
    while (is && c != '"') {
      if (c == '\\') {
        is.get(c);
        if (!is) throw TException("unexpected EOF");
        if (c == '"')
          v.append('"');
        else if (c == '\\')
          v.append('\\');
        else if (c == '\'')
          v.append('\'');
        else {
          v.append('\\');
          v.append(c);
        }
      } else
        v.append(c);
      is.get(c);
    }
  } else {
    v.append(c);
    while (c = is.peek(), isalnum(c) || c == '_' || c == '&' || c == '#' ||
                              c == ';' || c == '%') {
      is.get(c);
      v.append(c);
    }
  }
  return *this;
}
operator>>() [4/9]
TIStream & TIStream::operator>> (std::wstring & v)
Reads a wstring from the stream.
{
  string s;
  operator>>(s);
  v = ::to_wstring(s);
  return *this;
}
References operator>>().
operator>>() [5/9]
TIStream & TIStream::operator>> (TFilePath & v)
Reads a TFilePath from the stream.
{
  istream &is = *(m_imp->m_is);
  string s;
  char c;
  m_imp->skipBlanks();
  is.get(c);
  if (c == '"') {
    is.get(c);
    bool escapeChar = false;
    // If processing double-quote ("), if it's escaped, keep reading.
    while (is && (c != '"' || escapeChar)) {
      // if(c=='\\')
      //   is.get(c);
      if (c == '\\' && !escapeChar)
        escapeChar = true;
      else
        escapeChar = false;
      s.append(1, c);
      is.get(c);
    }
  } else {
    // il filepath non e' fra virgolette:
    // puo' contenere solo caratteri alfanumerici, % e _
    s.append(1, c);
    while (is) {
      c = is.peek();
      if (!isalnum(c) && c != '%' && c != '_') break;
      is.get(c);
      s.append(1, c);
    }
  }
  v = TFilePath(s);
  return *this;
}
operator>>() [6/9]
TIStream & TIStream::operator>> (TPersist & v)
Reads a TPersist derived object data from the stream.
\detail This function dispatches the loading process to the derived class' reimplementation of the TPersist::loadData() function.
Note
Unlinke operator>>(TPersist*&), this function requires that the passed object is of the correct type to read the current tag.
{
  v.loadData(*this);
  return *this;
}
References TPersist::loadData().
operator>>() [7/9]
TIStream & TIStream::operator>> (TPersist *& v)
Allocates and reads a TPersist derived object data from the stream.
{
  if (!m_imp->matchTag() || m_imp->m_currentTag.m_type == StreamTag::EndTag) {
    throw TException("expected begin tag");
  }
  StreamTag tag       = m_imp->m_currentTag;
  m_imp->m_currentTag = StreamTag();
  string tagName      = tag.m_name;
  std::map<std::string, string>::iterator it;
  int id = -1;
  it     = tag.m_attributes.find("id");
  if (it != tag.m_attributes.end()) id = atoi(it->second.c_str());
  // cout << "tagname = " << tagName << " id = " << id << endl;
  Imp::PersistTable::iterator pit = m_imp->m_table.find(id);
  if (pit == m_imp->m_table.end()) {
    v = TPersistFactory::instance()->create(tagName);
    if (!v) throw TException("unable to create a persistent '" + tagName + "'");
    m_imp->m_table[id] = v;
    if (tag.m_type != StreamTag::BeginTag)
      throw TException("expected begin tag");
    m_imp->m_tagStack.push_back(tag.m_name);
    v->loadData(*this);
    m_imp->matchTag();
    if (!m_imp->m_currentTag || m_imp->m_currentTag.m_type != StreamTag::EndTag)
      throw TException("expected end tag");
    if (m_imp->m_currentTag.m_name != m_imp->m_tagStack.back())
      throw TException("end tag mismatch");
    m_imp->m_tagStack.pop_back();
    m_imp->m_currentTag = StreamTag();
  } else {
    v = pit->second;
    if (tag.m_type != StreamTag::BeginEndTag)
      throw TException("expected begin/end tag");
  }
  return *this;
}
References TPersist::create(), and TPersist::loadData().
operator>>() [8/9]
TIStream & TIStream::operator>> (TPixel32 & v)
Reads a TPixel32 from the stream.
{
  istream &is = *(m_imp->m_is);
  int r, g, b, m;
  is >> r;
  is >> g;
  is >> b;
  is >> m;
  v.r = r;
  v.g = g;
  v.b = b;
  v.m = m;
  return *this;
}
operator>>() [9/9]
TIStream & TIStream::operator>> (TPixel64 & v)
Reads a TPixel64 from the stream.
{
  istream &is = *(m_imp->m_is);
  int r, g, b, m;
  is >> r;
  is >> g;
  is >> b;
  is >> m;
  v.r = r;
  v.g = g;
  v.b = b;
  v.m = m;
  return *this;
}
setVersion()
void TIStream::setVersion (const VersionNumber & version)
Returns the currently stored version of the
{
  m_imp->m_versionNumber = version;
}
Referenced by TProject::load(), and ToonzScene::loadTnzFile().
skipCurrentTag()
void TIStream::skipCurrentTag ()
opened document.
See also
setVersion()
Note
After skipping the tag content, the stream is positioned immediately after the end tag. Silently ignores the content of currently opened tag up to its end.
{ m_imp->skipCurrentTag(); }
Referenced by TImageReaderMesh::load(), PlasticSkeletonVertex::loadData(), PlasticSkeleton::loadData(), PlasticSkeletonVertexDeformation::loadData(), PlasticSkeletonDeformation::loadData(), TFx::loadData(), TTextureMesh::loadData(), TXshMeshColumn::loadData(), VectorizerParameters::loadData(), BrushData::loadData(), and VectorBrushData::loadData().
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/tstream.h
E:/opentoonz/toonz/sources/common/tstream/tstream.cpp