opentoonz: TreeModel::Item Class Reference
TreeModel::Item Class Reference
Public Member Functions
Item * getParent () const
int getChildCount () const
Item * getChild (int row) const
Item * appendChild (Item *child)
virtual void * getInternalPointer () const
see setChildren() below
void setChildren (QList< Item * > &children)
virtual void refresh ()
TreeModel * getModel () const
void setModel (TreeModel *model)
int getRow () const
row is the Item index in the parent. (used by QModelIndex)
void setRow (int row)
int getDepth () const
root_depth == 0; son_depth == parent_depth + 1
bool isOpen () const
void setIsOpen (bool opened)
virtual QVariant data (int role) const
QModelIndex createIndex ()
Detailed Description
Constructor & Destructor Documentation
Item()
TreeModel::Item::Item ()
    : m_model(0), m_parent(0), m_depth(0), m_row(0), m_opened(false) {}
~Item()
TreeModel::Item::~Item () virtual
                     {
  qDeleteAll(m_childItems);
  m_childItems.clear();
  m_model  = 0;
  m_row    = 0;
  m_depth  = 0;
  m_parent = 0;
}
Member Function Documentation
appendChild()
TreeModel::Item * TreeModel::Item::appendChild (TreeModel::Item * child)
{
  assert(child);
  assert(!m_childItems.contains(child));
  updateChild(child, m_childItems.size());
  m_childItems.append(child);
  return child;
}
createIndex()
QModelIndex TreeModel::Item::createIndex ()
{
  return m_parent ? m_model->createIndex(m_row, 0, this) : QModelIndex();
}
data()
QVariant TreeModel::Item::data (int role) const virtual
used by TreeModel::data(); default implementation provides open/close folder icons
Reimplemented in FunctionTreeModel::ChannelGroup, FunctionTreeModel::Channel, FxChannelGroup, and StageObjectChannelGroup.
{
  if (role == Qt::DecorationRole)
    return createQIcon("folder", true);
  else
    return QVariant();
}
Referenced by FunctionTreeModel::ChannelGroup::data(), and FunctionTreeModel::Channel::data().
getChild()
Item * TreeModel::Item::getChild (int row) const inline
{ return m_childItems.value(row); }
getChildCount()
int TreeModel::Item::getChildCount () const inline
{ return m_childItems.count(); }
getDepth()
int TreeModel::Item::getDepth () const inline
root_depth == 0; son_depth == parent_depth + 1
{ return m_depth; }
getInternalPointer()
virtual void * TreeModel::Item::getInternalPointer () const inline virtual
see setChildren() below
Reimplemented in FunctionTreeModel::Channel, FxChannelGroup, StageObjectChannelGroup, and TaskTreeModel::Item.
{ return 0; }
Referenced by TaskTreeModel::setupModelData().
getModel()
TreeModel * TreeModel::Item::getModel () const inline
{ return m_model; }
getParent()
Item * TreeModel::Item::getParent () const inline
{ return m_parent; }
getRow()
int TreeModel::Item::getRow () const inline
row is the Item index in the parent. (used by QModelIndex)
{ return m_row; }
isOpen()
bool TreeModel::Item::isOpen () const inline
{ return m_opened; }
refresh()
virtual void TreeModel::Item::refresh () inline virtual
{}
setChildren()
void TreeModel::Item::setChildren (QList< Item * > & children)
{
  assert(m_model);
  QModelIndex itemIndex = createIndex();
  // save old children and clear 'm_childItems'
  QList<Item *> oldChildren(m_childItems);
  m_childItems.clear();
  int i;
  // for each child to add
  for (i = 0; i < newChildren.size(); i++) {
    Item *newChild           = newChildren.at(i);
    void *newInternalPointer = newChild->getInternalPointer();
    if (newInternalPointer != 0) {
      // search among old children
      int j;
      for (j = 0; j < oldChildren.size(); j++)
        if (oldChildren.at(j)->getInternalPointer() == newInternalPointer)
          break;
      if (j < oldChildren.size()) {
        Item *oldChild = oldChildren.takeAt(j);
        if (oldChild != newChild) {
          // Found! Delete newChild, remove it from 'newChildren' and
          // update consequently the index
          delete newChild;
          newChildren.takeAt(i);
          i--;
          // use the found child instead of the new one.
          newChild = oldChild;
          oldChild->refresh();
        } else {
          // should never happen; (if it happens this is not a big problem)
          assert(0);
        }
      }
    }
    // add the new child to 'm_childItems'
    m_childItems.push_back(newChild);
  }
  // update children model, row, parent, etc.
  updateChildren();
  // postpone item deletion to avoid the (possible) reuse of the
  // same pointer for the newly created items. (Pointers match is
  // used updating persistent indices. see: TreeModel::endRefresh())
  for (i = 0; i < oldChildren.size(); i++) {
    Item *itemToDelete = oldChildren[i];
    if (!m_model->m_itemsToDelete.contains(itemToDelete))
      m_model->m_itemsToDelete.push_back(itemToDelete);
  }
}
setIsOpen()
void TreeModel::Item::setIsOpen (bool opened) inline
{ m_opened = opened; }
setModel()
void TreeModel::Item::setModel (TreeModel * model) inline
{ m_model = model; }
setRow()
void TreeModel::Item::setRow (int row) inline
{ m_row = row; }
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/toonzqt/treemodel.h
E:/opentoonz/toonz/sources/toonzqt/treemodel.cpp