opentoonz: SceneLevel Class Reference
SceneLevel Class Reference final
#include <sceneresources.h>
Public Member Functions
SceneLevel (ToonzScene *scene, TXshSimpleLevel *sl)
void save () override
void updatePath () override
void rollbackPath () override
void accept (ResourceProcessor *processor) override
visitor pattern
bool isDirty () override
QStringList getResourceName () override
Public Member Functions inherited from SceneResource
SceneResource (ToonzScene *scene)
virtual ~SceneResource ()
virtual void save ()=0
virtual void updatePath ()=0
change the resource internal path, according to the scene
virtual void rollbackPath ()=0
change back the resource internal path to its original value
virtual void accept (ResourceProcessor *processor)=0
visitor pattern
void updatePath (TFilePath &fp)
virtual bool isDirty ()=0
virtual QStringList getResourceName ()=0
Additional Inherited Members
Protected Attributes inherited from SceneResource
ToonzScene * m_scene
bool m_untitledScene
TFilePath m_oldSavePath
Detailed Description
The SceneLevel class provides a container for scene level resource and allows its management.
Inherits SceneResource.
The class, more than SceneResources, contains a pointer to a simple level TXshSimpleLevel, two path for old save path, one decoded and one no, two path for old scanned path, one decoded and one no. The class allows to save simple level save() and to update or to restore old path (save and scan) updatePath() rollbackPath().
Constructor & Destructor Documentation
SceneLevel()
SceneLevel::SceneLevel (ToonzScene * scene, TXshSimpleLevel * sl)
Constructs SceneLevel with ToonzScene scene and TXshSimpleLevel sl.
    : SceneResource(scene)
    , m_sl(sl)
    , m_oldPath(sl->getPath())
    , m_oldActualPath(scene->decodeFilePath(sl->getPath()))
    , m_oldScannedPath(sl->getScannedPath())
    , m_oldRefImgPath()
    , m_oldActualRefImgPath() {
  if (m_oldScannedPath != TFilePath())
    m_oldActualScannedPath = m_scene->decodeFilePath(m_oldScannedPath);
  if ((sl->getPath().getType() == "tlv" || sl->getPath().getType() == "pli") &&
      sl->getPalette()) {
    m_oldRefImgPath       = sl->getPalette()->getRefImgPath();
    m_oldActualRefImgPath = m_scene->decodeFilePath(m_oldRefImgPath);
  }
}
References ToonzScene::decodeFilePath(), TXshSimpleLevel::getPalette(), TXshSimpleLevel::getPath(), TPalette::getRefImgPath(), and TFilePath::getType().
Member Function Documentation
accept()
void SceneLevel::accept (ResourceProcessor * processor) inline override virtual
visitor pattern
Implements SceneResource.
{
    processor->process(m_sl);
  }
getResourceName()
QStringList SceneLevel::getResourceName () override virtual
Implements SceneResource.
{
  QStringList ret;
  QString string;
  bool levelIsDirty = false;
  if (m_sl->getProperties()->getDirtyFlag()) {
    string += QString::fromStdString(m_sl->getPath().getLevelName());
    levelIsDirty = true;
  }
  if (m_sl->getPalette() && m_sl->getPalette()->getDirtyFlag()) {
    QString paletteName =
        QString::fromStdWString(m_sl->getPalette()->getPaletteName());
    if (m_sl->getType() & FULLCOLOR_TYPE) {
      if (levelIsDirty) ret << string;
      ret << paletteName + ".tpl";
    } else {
      if (levelIsDirty) string += " and ";
      if (m_sl->getPath().getType() == "pli")
        string += paletteName + ".pli (palette)";
      else
        string += paletteName + ".tpl";
      ret << string;
    }
  } else if (levelIsDirty)
    ret << string;
  return ret;
}
isDirty()
bool SceneLevel::isDirty () override virtual
Implements SceneResource.
{
  if (m_sl->getProperties()->getDirtyFlag() ||
      (m_sl->getPalette() && m_sl->getPalette()->getDirtyFlag()))
    return true;
  else
    return false;
}
rollbackPath()
void SceneLevel::rollbackPath () override virtual
Set simple level path to old path.
Implements SceneResource.
{
  if (!m_untitledScene) return;
  m_sl->setPath(m_oldPath, true);
  m_sl->setScannedPath(m_oldScannedPath);
}
save()
void SceneLevel::save () override virtual
Save simple level in right path.
Implements SceneResource.
                      {
  TFilePath fp = m_oldPath;
  SceneResource::updatePath(fp);
  TFilePath actualFp      = m_scene->decodeFilePath(fp);
  actualFp                = restorePsdPath(actualFp);
  TFilePath oldActualPath = restorePsdPath(m_oldActualPath);
  assert(actualFp.getWideString() == L"" ||
         actualFp.getWideString()[0] != L'+');
  if (actualFp != oldActualPath ||
      !TSystem::doesExistFileOrLevel(oldActualPath) ||
      m_sl->getProperties()->getDirtyFlag() ||
      (m_sl->getPalette() && m_sl->getPalette()->getDirtyFlag())) {
    try {
      TSystem::touchParentDir(actualFp);
      if (actualFp != oldActualPath &&
          TSystem::doesExistFileOrLevel(oldActualPath) &&
          m_sl->getProperties()->getDirtyFlag() == false &&
          (!m_sl->getPalette() ||
           (m_sl->getPalette() &&
            m_sl->getPalette()->getDirtyFlag() == false))) {
        try {
          TXshSimpleLevel::copyFiles(actualFp, oldActualPath);
        } catch (...) {
        }
        // Must NOT KEEP FRAMES, it generate a level frames bind necessary to
        // imageBuilder path refresh.
        m_sl->setPath(fp, false);
      } else {
        try {
          m_sl->save(actualFp, oldActualPath);
        } catch (...) {
          throw;
        }
        if ((actualFp.getType() == "tlv" || actualFp.getType() == "pli") &&
            actualFp != oldActualPath && m_oldRefImgPath != TFilePath()) {
          // Devo preoccuparmi dell'eventuale livello colormodel
          TFilePath actualRefImagPath =
              m_scene->decodeFilePath(m_oldRefImgPath);
          TFilePath actualRefImagPathTpl = actualRefImagPath.withType("tpl");
          TFilePath oldRefImagPathTpl = m_oldActualRefImgPath.withType("tpl");
          TSystem::copyFile(actualRefImagPath, m_oldActualRefImgPath);
          if (actualRefImagPath.getType() == "tlv")
            TSystem::copyFile(actualRefImagPathTpl, oldRefImagPathTpl);
        }
        if (actualFp.getType() == "tif" || actualFp.getType() == "tiff" ||
            actualFp.getType() == "tga" || actualFp.getType() == "tzi") {
          TFilePath clnin = oldActualPath.withNoFrame().withType("cln");
          if (TSystem::doesExistFileOrLevel(clnin))
            TSystem::copyFile(actualFp.withNoFrame().withType("cln"), clnin);
        }
      }
      // Se il livello e' tlv verifico se esiste il corrispondente unpainted ed
      // in caso affermativo lo copio.
      // Questo controllo viene fatto qui e non nella copia o nel salvataggio
      // del livello perche' in generale
      // non si vuole che il livello unpainted venga copiato con il livello.
      if (actualFp.getType() == "tlv") {
        TFilePath oldUnpaintedLevelPath =
            oldActualPath.getParentDir() + "nopaint\\" +
            TFilePath(oldActualPath.getName() + "_np." +
                      oldActualPath.getType());
        TFilePath unpaintedLevelPath =
            actualFp.getParentDir() + "nopaint\\" +
            TFilePath(actualFp.getName() + "_np." + actualFp.getType());
        if (TSystem::doesExistFileOrLevel(oldUnpaintedLevelPath) &&
            !TSystem::doesExistFileOrLevel(unpaintedLevelPath) &&
            TSystem::touchParentDir(unpaintedLevelPath))
          TSystem::copyFile(unpaintedLevelPath, oldUnpaintedLevelPath);
        TFilePath oldUnpaintedPalettePath =
            oldUnpaintedLevelPath.withType("tpl");
        TFilePath unpaintedPalettePath = unpaintedLevelPath.withType("tpl");
        if (TSystem::doesExistFileOrLevel(oldUnpaintedPalettePath) &&
            !TSystem::doesExistFileOrLevel(unpaintedPalettePath) &&
            TSystem::touchParentDir(unpaintedPalettePath))
          TSystem::copyFile(unpaintedPalettePath, oldUnpaintedPalettePath);
      }
    } catch (...) {
    }
  }
  fp = m_oldScannedPath;
  if (fp != TFilePath()) {
    SceneResource::updatePath(fp);
    actualFp = m_scene->decodeFilePath(fp);
    if (actualFp != m_oldActualScannedPath &&
        TSystem::doesExistFileOrLevel(m_oldActualScannedPath)) {
      try {
        TSystem::touchParentDir(actualFp);
        TSystem::copyFileOrLevel_throw(actualFp, m_oldActualScannedPath);
        m_sl->clearFrames();
        m_sl->load();
      } catch (...) {
      }
    }
  }
}
References TXshSimpleLevel::copyFiles(), ToonzScene::decodeFilePath(), TPalette::getDirtyFlag(), LevelProperties::getDirtyFlag(), TFilePath::getName(), TXshSimpleLevel::getPalette(), TFilePath::getParentDir(), TXshSimpleLevel::getProperties(), TFilePath::getType(), TXshSimpleLevel::load(), TXshSimpleLevel::save(), SceneResource::updatePath(), and TFilePath::withType().
updatePath()
void SceneLevel::updatePath () override virtual
Update simple level path.
Implements SceneResource.
{
  if (!m_untitledScene) return;
  TFilePath fp = m_oldPath;
  SceneResource::updatePath(fp);
  m_sl->setPath(fp, true);
  fp = m_oldScannedPath;
  SceneResource::updatePath(fp);
  m_sl->setScannedPath(fp);
}
References SceneResource::updatePath().
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/toonz/sceneresources.h
E:/opentoonz/toonz/sources/toonzlib/sceneresources.cpp