opentoonz: StageObjectsData Class Reference
StageObjectsData Class Reference final
#include <stageobjectsdata.h>
Public Types
enum FxFlags { eDoClone = 0x1 , eResetFxDagPositions }
Public Member Functions
StageObjectsData * clone () const override
bool isEmpty () const
void storeObjects (const std::vector< TStageObjectId > &ids, TXsheet *xsheet, int fxFlags)
void storeColumns (const std::set< int > &columnIndexes, TXsheet *xsheet, int fxFlags)
Overloaded function, stores the specified columns in the supplied xsheet.
void storeFxs (const std::set< TFx * > &fxs, TXsheet *xsheet, int fxFlags)
Stores the specified fxs from the xsheet.
void storeColumnFxs (const std::set< int > &columnIndexes, TXsheet *xsh, int fxFlags)
void storeSplines (const std::list< int > &splineIds, TXsheet *xsh, int fxFlags)
bool checkCircularReferences (TXsheet *xsheet) const
std::vector< TStageObjectId > restoreObjects (std::set< int > &columnIndices, std::list< int > &restoredSplinIds, TXsheet *xsheet, int fxFlags, const TPointD &pos=TConst::nowhere) const
std::vector< TStageObjectId > restoreObjects (std::set< int > &columnIndices, std::list< int > &restoredSplinIds, TXsheet *xsheet, int fxFlags, QMap< TStageObjectId, TStageObjectId > &idTable, QMap< TFx *, TFx * > &fxTable, const TPointD &pos=TConst::nowhere) const
Public Member Functions inherited from DvMimeData
virtual DvMimeData * clone () const =0
virtual void releaseData ()
virtual DvMimeData * clone () const =0
Detailed Description
StageObjectsData is the class used to store multiple schematic stage object's relational data.
Member Enumeration Documentation
FxFlags
enum StageObjectsData::FxFlags
               {
    eDoClone = 0x1,  // Clones sensible stored data
    eResetFxDagPositions =
        0x2  // Accepts default positions for newly created FX objects
  };
Constructor & Destructor Documentation
StageObjectsData()
StageObjectsData::StageObjectsData ()
: DvMimeData() {}
~StageObjectsData()
StageObjectsData::~StageObjectsData ()
{
  int i, elementsCount = m_elements.size();
  for (i = 0; i < elementsCount; ++i) delete m_elements[i];
  for (i = 0; i < m_splines.size(); ++i) delete m_splines[i];
  std::set<TFx *>::iterator it;
  for (it = m_fxs.begin(); it != m_fxs.end(); ++it) {
    TFx *fx = *it;
    if (fx) fx->release();
  }
  for (it = m_terminalFxs.begin(); it != m_terminalFxs.end(); ++it) {
    TFx *fx = *it;
    if (fx) fx->release();
  }
}
Member Function Documentation
checkCircularReferences()
bool StageObjectsData::checkCircularReferences (TXsheet * xsheet) const
Scans the stored column elements to verify if the specified xsheet is a sub-xsheet in of them (thus creating an impossible '\it{circular reference}').
{
  int i, elementsCount = m_elements.size();
  for (i = 0; i < elementsCount; ++i) {
    TColumnDataElement *columnElement =
        dynamic_cast<TColumnDataElement *>(m_elements[i]);
    if (!columnElement) continue;
    if (xsh->checkCircularReferences(columnElement->m_column.getPointer()))
      return true;
  }
  return false;
}
References TXsheet::checkCircularReferences().
clone()
StageObjectsData * StageObjectsData::clone () const override virtual
Clones this object.
Note
Clones stored fxs, columns, etc. too.
Implements DvMimeData.
{
  StageObjectsData *data = new StageObjectsData();
  // Clone each element (the new data gets ownership)
  int i, elementsCount = m_elements.size();
  for (i = 0; i < elementsCount; ++i)
    data->m_elements.append(m_elements[i]->clone());
  // Clone each spline (the new data gets ownership)
  for (i = 0; i < m_splines.size(); ++i)
    data->m_splines.append(m_splines[i]->clone());
  // Same for internal fxs
  std::map<TFx *, TFx *> fxTable;  // And trace the pairings with the originals
  std::set<TFx *>::const_iterator it;
  for (it = m_fxs.begin(); it != m_fxs.end(); ++it) {
    TFx *fxOrig = *it;
    assert(fxOrig);
    assert(fxTable.count(fxOrig) == 0);
    TFx *fx = fxOrig->clone(false);
    fx->getAttributes()->setId(fxOrig->getAttributes()->getId());
    fx->getAttributes()->passiveCacheDataIdx() = -1;
    fx->setName(fxOrig->getName());
    fx->setFxId(fxOrig->getFxId());
    fxTable[fxOrig] = fx;
    fx->addRef();
    data->m_fxs.insert(fx);
  }
  // Same with terminals
  for (it = m_terminalFxs.begin(); it != m_terminalFxs.end(); ++it) {
    TFx *fxOrig = *it;
    assert(fxOrig);
    // If the fx was not already cloned above, do it now
    TFx *fx = searchFx(fxTable, fxOrig);
    if (!fx) {
      fx = fxOrig->clone(false);
      fx->getAttributes()->setId(fxOrig->getAttributes()->getId());
      fx->getAttributes()->passiveCacheDataIdx() = -1;
      fx->setName(fxOrig->getName());
      fx->setFxId(fxOrig->getFxId());
      fxTable[fxOrig] = fx;
    }
    fx->addRef();
    data->m_terminalFxs.insert(fx);
  }
  if (!fxTable.empty())
    updateFxLinks(fxTable);  // Applies the traced map pairings to every fx
                             // descendant of each fx stored in the map.
  // WARNING: m_fxsTable is NOT COPIED / CLONED !!
  return data;
}
isEmpty()
bool StageObjectsData::isEmpty () const inline
{ return m_elements.isEmpty() && m_splines.isEmpty(); }
restoreObjects() [1/2]
std::vector< TStageObjectId > StageObjectsData::restoreObjects (std::set< int > & columnIndices, std::list< int > & restoredSplinIds, TXsheet * xsheet, int fxFlags, const TPointD & pos = TConst::nowhere) const
Restores the stored objects in the supplied xsheet, inserting columns with the specified indices. In case there are more stored columns than specified column indices, the remaining columns are inserted right after the last specified index. Returns the inserted stage object identifiers and updates the columnIndices with all the newly inserted column indices. Additional flags support TXshColumn cloning before insertion.
{
  QMap<TStageObjectId, TStageObjectId> idTable;
  QMap<TFx *, TFx *> fxTable;
  return restoreObjects(columnIndices, restoredSpline, xsh, fxFlags, idTable,
                        fxTable, pos);
}
References restoreObjects().
Referenced by restoreObjects().
restoreObjects() [2/2]
std::vector< TStageObjectId > StageObjectsData::restoreObjects (std::set< int > & columnIndices, std::list< int > & restoredSplinIds, TXsheet * xsheet, int fxFlags, QMap< TStageObjectId, TStageObjectId > & idTable, QMap< TFx *, TFx * > & fxTable, const TPointD & pos = TConst::nowhere) const
{
  bool doClone             = (fxFlags & eDoClone);
  bool resetFxDagPositions = (fxFlags & eResetFxDagPositions);
  // QMap<TStageObjectId, TStageObjectId>
  //    idTable;                     // Trace stored/restored id pairings
  // std::map<TFx *, TFx *> fxTable;  // Same for fxs here
  std::vector<TStageObjectId> restoredIds;
  std::set<int>::iterator idxt = columnIndices.begin();
  int index                    = -1;  // The actual column insertion index
  int i, elementsCount = m_elements.size();
  for (i = 0; i < elementsCount; ++i) {
    TStageObjectDataElement *element = m_elements[i];
    TCameraDataElement *cameraElement =
        dynamic_cast<TCameraDataElement *>(element);
    TColumnDataElement *columnElement =
        dynamic_cast<TColumnDataElement *>(element);
    // Restore the object depending on its specific type
    TStageObjectId restoredId = TStageObjectId::NoneId;
    if (!cameraElement && !columnElement)
      restoredId = element->restoreObject(xsh, pos != TConst::nowhere);
    else if (cameraElement)
      restoredId = cameraElement->restoreCamera(xsh, pos != TConst::nowhere);
    else if (columnElement) {
      // Build the column insertion index
      if (idxt != columnIndices.end())
        index = *idxt++;
      else {
        ++index;
        columnIndices.insert(index);
      }
      // Restore the column element
      restoredId = columnElement->restoreColumn(xsh, index, fxFlags,
                                                pos != TConst::nowhere);
      FxDag *fxDag = xsh->getFxDag();
      TXshColumn *column       = columnElement->m_column.getPointer();
      TXshColumn *pastedColumn = xsh->getColumn(index);
      TFx *fx       = column->getFx();
      TFx *pastedFx = pastedColumn->getFx();
      if (fx && pastedFx) fxTable[fx] = pastedFx;
      // Enforce the correct terminality. Added columns are terminal by default.
      bool terminal = (fx && (m_terminalFxs.count(fx) > 0));
      if (!terminal) fxDag->getTerminalFxs()->removeFx(pastedFx);
      // In case we've cloned a zerary fx column, update the actual fx's data
      if (TXshZeraryFxColumn *zc =
              dynamic_cast<TXshZeraryFxColumn *>(pastedColumn)) {
        TZeraryColumnFx *zfx = zc->getZeraryColumnFx();
        TFx *zeraryFx        = zfx->getZeraryFx();
        if (zeraryFx) {
          if (doClone) {
            // if the fx has not unique name then let  assignUniqueId() set the
            // default name
            if (zeraryFx->getName() == zeraryFx->getFxId())
              zeraryFx->setName(L"");
            fxDag->assignUniqueId(zeraryFx);
          } else
            fxDag->updateFxIdTable(zeraryFx);
          if (TXshZeraryFxColumn *orig_zc =
                  dynamic_cast<TXshZeraryFxColumn *>(column)) {
            if (TFx *origZeraryFx = orig_zc->getZeraryColumnFx()->getZeraryFx())
              fxTable[origZeraryFx] = zeraryFx;
          }
        }
      }
    }
    // Remember stored/restored stage object pairings
    idTable[element->m_params->m_id] = restoredId;
    restoredIds.push_back(restoredId);
  }
  // Apply stage object-parental relationships
  for (i = 0; i < elementsCount; ++i) {
    TStageObjectDataElement *element = m_elements[i];
    TStageObjectId id       = element->m_params->m_id;
    TStageObjectId parentId = element->m_params->m_parentId;
    TStageObjectId pastedId       = idTable[id];
    TStageObjectId pastedParentId = parentId;
    // if the parent object is not restored, redirect to the table
    QMap<TStageObjectId, TStageObjectId>::iterator it = idTable.find(parentId);
    pastedParentId =
        (it == idTable.end()) ? TStageObjectId::TableId : it.value();
    xsh->setStageObjectParent(pastedId, pastedParentId);
    TStageObject *pastedObj = xsh->getStageObject(pastedId);
    // Shouldn't these be done outside ?
    pastedObj->setHandle(element->m_params->m_handle);
    pastedObj->setParentHandle(element->m_params->m_parentHandle);
  }
  // Iterate stored fxs
  std::set<TFx *>::const_iterator fxt, end = m_fxs.end();
  for (fxt = m_fxs.begin(); fxt != end; ++fxt) {
    TFx *fxOrig = *fxt, *fx = fxOrig;
    // Only NOT COLUMN fxs - ie internal fxs
    if (fxTable.find(fxOrig) != fxTable.end()) continue;
    // Internal fxs
    if (doClone) {
      fx = fxOrig->clone(false);
      // if the fx has not unique name then let assignUniqueId() set the default
      // name
      if (fx->getName() == fx->getFxId()) fx->setName(L"");
      fx->getAttributes()->setId(fxOrig->getAttributes()->getId());
      fx->getAttributes()->passiveCacheDataIdx() = -1;
      if (resetFxDagPositions)
        fx->getAttributes()->setDagNodePos(TConst::nowhere);
      xsh->getFxDag()->assignUniqueId(
          fx);  // For now, dragging columns always increment fxid.
                // Could it be more adaptive, avoiding increment
                // if it is not necessary?
    }
    fxTable[fxOrig] = fx;
    // Insert the passed fx in the xsheet
    TOutputFx *outFx = dynamic_cast<TOutputFx *>(fx);
    if (!outFx)
      xsh->getFxDag()->getInternalFxs()->addFx(fx);
    else
      xsh->getFxDag()->addOutputFx(outFx);
    if (m_terminalFxs.count(fxOrig) > 0)
      xsh->getFxDag()->getTerminalFxs()->addFx(fx);
    if (!doClone) {
      // Err.... don't remember. Inquire further? :|
      int fxTypeCount = xsh->getFxDag()->getFxTypeCount(fx);
      int maxFxTypeId = std::max(fxTypeCount, fx->getAttributes()->getId());
      xsh->getFxDag()->updateFxTypeTable(fx, maxFxTypeId);
      xsh->getFxDag()->updateFxIdTable(fx);
    }
    bool isLinked = (fxOrig->getLinkedFx() != fxOrig);
    if (isLinked) {
      if (m_fxs.find(fxOrig->getLinkedFx()) == m_fxs.end())
        fx->linkParams(fxOrig->getLinkedFx());
      else {
        TFx *linkedFx, *oldLinkedFx = fxOrig->getLinkedFx();
        if (doClone) {
          // Clone the linked fx too
          linkedFx = fx->clone(false);
          linkedFx->linkParams(fx);
          // if the fx has not unique name then let assignUniqueId() set the
          // default name
          if (linkedFx->getName() == linkedFx->getFxId())
            linkedFx->setName(L"");
          linkedFx->getAttributes()->setId(
              oldLinkedFx->getAttributes()->getId());
          linkedFx->getAttributes()->passiveCacheDataIdx() = -1;
          if (resetFxDagPositions)
            linkedFx->getAttributes()->setDagNodePos(TConst::nowhere);
          else
            linkedFx->getAttributes()->setDagNodePos(
                oldLinkedFx->getAttributes()->getDagNodePos());
          xsh->getFxDag()->assignUniqueId(linkedFx);
        } else
          linkedFx = oldLinkedFx;
        fxTable[oldLinkedFx] = linkedFx;
        xsh->getFxDag()->getInternalFxs()->addFx(linkedFx);
        if (m_terminalFxs.count(oldLinkedFx) > 0)
          xsh->getFxDag()->getTerminalFxs()->addFx(linkedFx);
        if (!doClone) {
          int fxTypeCount = xsh->getFxDag()->getFxTypeCount(linkedFx);
          int maxFxTypeId =
              std::max(fxTypeCount, linkedFx->getAttributes()->getId());
          xsh->getFxDag()->updateFxTypeTable(linkedFx, maxFxTypeId);
          xsh->getFxDag()->updateFxIdTable(linkedFx);
        }
      }
    }
  }
  // Update the link, like in functions above
  if (!fxTable.empty() && doClone) updateFxLinks(fxTable.toStdMap());
  // Paste any associated spline (not stored im m_splines)
  std::map<TStageObjectSpline *, TStageObjectSpline *> splines;
  for (i = 0; i < (int)restoredIds.size(); ++i) {
    TStageObjectId id = restoredIds[i];
    TStageObject *obj = xsh->getStageObject(id);
    TStageObjectSpline *spline = obj->getSpline();
    if (!spline) continue;
    TStageObjectTree *objTree = xsh->getStageObjectTree();
    if (objTree->containsSpline(
            spline))  // No need to add it if it's already there
      continue;
    std::map<TStageObjectSpline *, TStageObjectSpline *>::iterator it =
        splines.find(spline);
    if (it != splines.end()) {
      // Seems that multiple objects can have the same spline...
      // BTW, shouldn't this case stop at the continue before ?
      obj->setSpline(it->second);
      continue;
    }
    // The spline was not found. Clone and add it to the xsheet
    TStageObjectSpline *newSpline = spline->clone();  // Not checking doClone ?
    objTree->assignUniqueSplineId(newSpline);
    objTree->insertSpline(newSpline);
    obj->setSpline(newSpline);
    splines[spline] = newSpline;
  }
  // paste stored path
  QList<TSplineDataElement *>::const_iterator splinIt;
  for (splinIt = m_splines.begin(); splinIt != m_splines.end(); ++splinIt) {
    TStageObjectTree *objTree    = xsh->getStageObjectTree();
    TSplineDataElement *splineEl = *splinIt;
    TStageObjectSpline *spline   = splineEl->restoreSpline(fxFlags);
    if (doClone) objTree->assignUniqueSplineId(spline);
    objTree->insertSpline(spline);
    restoredSpline.push_back(spline->getId());
  }
  xsh->updateFrameCount();
  if (pos != TConst::nowhere) {
    // Update objects positions depending on the externally supplied pos
    TPointD middlePos;
    int count = 0;
    for (i = 0; i < (int)restoredIds.size(); ++i) {
      TStageObjectId id = restoredIds[i];
      TStageObject *obj = xsh->getStageObject(id);
      TPointD oldPos = obj->getDagNodePos();
      if (oldPos == TConst::nowhere) continue;
      middlePos += oldPos;
      ++count;
    }
    middlePos      = TPointD(middlePos.x / count, middlePos.y / count);
    TPointD offset = pos - middlePos;
    for (i = 0; i < (int)restoredIds.size(); ++i) {
      TStageObjectId id = restoredIds[i];
      TStageObject *obj = xsh->getStageObject(id);
      TPointD oldPos = obj->getDagNodePos();
      if (oldPos == TConst::nowhere) continue;
      obj->setDagNodePos(oldPos + offset);
    }
  }
  // reset grammers for all parameters of pasted stage objects and fxs
  // or they fails to refer to other parameters via expression
  // if they are pasted in different xsheet
  TSyntax::Grammar *grammer = xsh->getStageObjectTree()->getGrammar();
  for (auto id : restoredIds) {
    TStageObject *obj = xsh->getStageObject(id);
    for (int c = 0; c != TStageObject::T_ChannelCount; ++c)
      obj->getParam((TStageObject::Channel)c)->setGrammar(grammer);
    if (const PlasticSkeletonDeformationP &sd =
            obj->getPlasticSkeletonDeformation())
      sd->setGrammar(grammer);
  }
  QMap<TFx *, TFx *>::const_iterator it;
  for (it = fxTable.constBegin(); it != fxTable.constEnd(); ++it) {
    setGrammerToParams(it.value()->getParams(), grammer);
  }
  return restoredIds;
}
storeColumnFxs()
void StageObjectsData::storeColumnFxs (const std::set< int > & columnIndexes, TXsheet * xsh, int fxFlags)
Stores the column fxs \it{and their upstream fxs} associated to the specified column indices, without storing the columns stage objects.
{
  bool doClone             = (fxFlags & eDoClone);
  bool resetFxDagPositions = (fxFlags & eResetFxDagPositions);
  std::set<TFx *> internalFxs;
  xsh->getFxDag()->getInternalFxs()->getFxs(internalFxs);
  // Iterate internal fxs (note: columns NOT included)
  // NOTE: Could this be too heavy ? Shouldn't we travel upstream from given
  // column fxs?
  std::set<TFx *>::iterator it;
  for (it = internalFxs.begin(); it != internalFxs.end(); ++it) {
    TFx *fxOrig = *it, *fx = fxOrig;
    if (m_fxTable.find(fx) != m_fxTable.end())  // If already treated
      continue;
    if (canGenerate(m_originalColumnFxs,
                    fx) != CanGenerate)  // If not completely in the upstream
      continue;
    if (doClone) {
      // Clone the fx if required
      fx = fxOrig->clone(false);
      fx->setName(fxOrig->getName());
      fx->getAttributes()->setId(fxOrig->getAttributes()->getId());
      fx->getAttributes()->passiveCacheDataIdx() = -1;
      if (resetFxDagPositions)
        fx->getAttributes()->setDagNodePos(TConst::nowhere);
    }
    m_fxTable[fxOrig] = fx;
    fx->addRef();
    m_fxs.insert(fx);
    if (isColumnSelectionTerminalFx(fxOrig, xsh->getFxDag()->getTerminalFxs(),
                                    m_originalColumnFxs)) {
      fx->addRef();
      m_terminalFxs.insert(fx);
    }
    if (fxOrig->getLinkedFx() != fxOrig)  // Linked fx
    {
      if (canGenerate(m_originalColumnFxs, fxOrig->getLinkedFx()) !=
          CanGenerate)
        fx->linkParams(fxOrig->getLinkedFx());
      else {
        // Insert the linked fx directly here
        TFx *linkedFx, *oldLinkedFx = fxOrig->getLinkedFx();
        if (doClone) {
          linkedFx = fx->clone(false);  // Not oldLinkedFx->clone() ?
          linkedFx->linkParams(fx);
          linkedFx->setName(oldLinkedFx->getName());
          linkedFx->getAttributes()->setId(
              oldLinkedFx->getAttributes()->getId());
          linkedFx->getAttributes()->passiveCacheDataIdx() = -1;
          if (resetFxDagPositions)
            fx->getAttributes()->setDagNodePos(TConst::nowhere);  // Here too ?
          xsh->getFxDag()->assignUniqueId(linkedFx);
        } else
          linkedFx = oldLinkedFx;
        m_fxTable[oldLinkedFx] = linkedFx;
        linkedFx->addRef();
        m_fxs.insert(linkedFx);
        if (xsh->getFxDag()->getTerminalFxs()->containsFx(
                fx->getLinkedFx()))  // Here too - isATerminal ?
        {
          linkedFx->addRef();
          m_terminalFxs.insert(linkedFx);
        }
      }
    }
  }
  // Like in the functions above, update links
  if (!m_fxTable.empty() && doClone) updateFxLinks(m_fxTable);
}
References TXsheet::getFxDag().
storeColumns()
void StageObjectsData::storeColumns (const std::set< int > & columnIndexes, TXsheet * xsheet, int fxFlags)
Overloaded function, stores the specified columns in the supplied xsheet.
{
  std::vector<TStageObjectId> ids;
  std::set<int>::const_iterator it;
  for (it = columnIndexes.begin(); it != columnIndexes.end(); ++it)
    ids.push_back(TStageObjectId::ColumnId(*it));
  storeObjects(ids, xsh, fxFlags);
}
References storeObjects().
storeFxs()
void StageObjectsData::storeFxs (const std::set< TFx * > & fxs, TXsheet * xsheet, int fxFlags)
Stores the specified fxs from the xsheet.
{
  bool doClone             = (fxFlags & eDoClone);
  bool resetFxDagPositions = (fxFlags & eResetFxDagPositions);
  TFxSet *terminalFxs = xsh->getFxDag()->getTerminalFxs();
  // Traverse specified fxs
  std::set<TFx *>::const_iterator it;
  for (it = fxs.begin(); it != fxs.end(); ++it) {
    TFx *fxOrig = *it, *fx = fxOrig;
    if (doClone) {
      // If required, clone them
      fx = fxOrig->clone(false);
      fx->setName(fxOrig->getName());
      fx->getAttributes()->setId(fxOrig->getAttributes()->getId());
      fx->getAttributes()->passiveCacheDataIdx() = -1;
      if (resetFxDagPositions)
        fx->getAttributes()->setDagNodePos(TConst::nowhere);
    }
    // Store them (and the original/clone pairing even if not cloning)
    m_fxTable[fxOrig] = fx;
    fx->addRef();
    m_fxs.insert(fx);
    // Find out if the fx is a terminal one in the selection. If so, store it
    // there too.
    bool isTerminal = true;
    if (!terminalFxs->containsFx(
            fxOrig))  // If it's terminal in the xsheet, no doubt
    {
      // Otherwise, check terminality with respect to the selection
      int i, outputConnectionsCount = fxOrig->getOutputConnectionCount();
      for (i = 0; i < outputConnectionsCount; ++i) {
        TFx *outputFx = fxOrig->getOutputConnection(i)->getOwnerFx();
        if (outputFx && fxs.count(outputFx) > 0) {
          isTerminal = false;
          break;
        }
      }
    }
    // Well, excluding true TOutputFxs...
    TOutputFx *outFx = dynamic_cast<TOutputFx *>(fx);
    if (isTerminal && !outFx) {
      fx->addRef();
      m_terminalFxs.insert(fx);
    }
  }
  // Updating terminality of the column fxs too!
  // WARNING: This requires that storeObjects() is invoked BEFORE this !
  for (it = m_originalColumnFxs.begin(); it != m_originalColumnFxs.end();
       ++it) {
    TFx *fxOrig = *it;
    bool isTerminal = true;
    if (!terminalFxs->containsFx(fxOrig)) {
      int i, outputConnectionsCount = fxOrig->getOutputConnectionCount();
      for (i = 0; i < outputConnectionsCount; ++i) {
        TFx *outputFx = fxOrig->getOutputConnection(i)->getOwnerFx();
        if (outputFx && fxs.count(outputFx) > 0) {
          isTerminal = false;
          break;
        }
      }
    }
    if (isTerminal) {
      TFx *fx = m_fxTable[fxOrig];
      fx->addRef();
      m_terminalFxs.insert(fx);
    }
  }
  if (!m_fxTable.empty() && doClone)
    updateFxLinks(m_fxTable);  // Apply original/clone pairings
                               // to fx relatives
}
References TXsheet::getFxDag().
storeObjects()
void StageObjectsData::storeObjects (const std::vector< TStageObjectId > & ids, TXsheet * xsheet, int fxFlags)
Stores the xsheet's specified stage objects (be them cameras, columns, pegbars or else). Additional flags support TXshColumn cloning for columns.
{
  assert(
      m_fxTable.empty());  // Should be enforced OUTSIDE. Track implicit uses.
  m_fxTable.clear();       // TO BE REMOVED
  int i, objCount = ids.size();
  // Discriminate sensible stage object types (ie cameras and columns from the
  // rest).
  // Store them in a map, ordered by object index.
  std::map<int, TStageObjectId> cameraIds, columnIds, pegbarIds;
  for (i = 0; i < objCount; ++i) {
    TStageObjectId id = ids[i];
    if (id.isColumn())
      columnIds[id.getIndex()] = id;
    else if (id.isPegbar())
      pegbarIds[id.getIndex()] = id;
    else if (id.isCamera())
      cameraIds[id.getIndex()] = id;
  }
  // Store a suitable object for each
  std::map<int, TStageObjectId>::iterator it;
  for (it = cameraIds.begin(); it != cameraIds.end(); ++it) {
    // Cameras
    TCameraDataElement *cameraElement = new TCameraDataElement();
    cameraElement->storeCamera(it->second, xsh);
    m_elements.append(cameraElement);
  }
  for (it = pegbarIds.begin(); it != pegbarIds.end(); ++it) {
    // Pegbars (includes curves)
    TStageObjectDataElement *objElement = new TStageObjectDataElement();
    objElement->storeObject(it->second, xsh);
    m_elements.append(objElement);
  }
  for (it = columnIds.begin(); it != columnIds.end(); ++it) {
    // Columns
    int colIndex = it->second.getIndex();
    TXshColumn *column = xsh->getColumn(colIndex);
    if (!column) continue;
    TColumnDataElement *columnElement = new TColumnDataElement();
    columnElement->storeColumn(xsh, colIndex, fxFlags);
    m_elements.append(columnElement);
    TXshColumn *copiedColumn = columnElement->m_column.getPointer();
    if (column->getFx() && copiedColumn->getFx()) {
      // Store column fx pairings (even if the originals are not cloned)
      m_fxTable[column->getFx()] = copiedColumn->getFx();
      m_originalColumnFxs.insert(column->getFx());
    }
  }
  // Insert terminal fxs
  for (auto const &e : m_originalColumnFxs) {
    if (isColumnSelectionTerminalFx(e, xsh->getFxDag()->getTerminalFxs(),
                                    m_originalColumnFxs)) {
      TFx *fx = m_fxTable[e];
      fx->addRef();
      m_terminalFxs.insert(fx);
    }
  }
}
References TXsheet::getColumn(), TXsheet::getFxDag(), TCameraDataElement::storeCamera(), TColumnDataElement::storeColumn(), and TStageObjectDataElement::storeObject().
Referenced by storeColumns().
storeSplines()
void StageObjectsData::storeSplines (const std::list< int > & splineIds, TXsheet * xsh, int fxFlags)
Stores the splines identified by the splineIds NOTE: a spline will be stored only if no TStageObject is connected to it, or if no TStageObject connected is stored by this StageObjectsData.
{
  std::list<int>::const_iterator it;
  for (it = splineIds.begin(); it != splineIds.end(); ++it) {
    TStageObjectSpline *spline = xsh->getStageObjectTree()->getSplineById(*it);
    int j;
    bool skipSpline = false;
    for (j = 0; j < m_elements.size(); j++) {
      TStageObjectDataElement *element = m_elements[j];
      if (spline == element->m_params->m_spline) {
        skipSpline = true;
        break;
      }
    }
    if (skipSpline) continue;
    TSplineDataElement *splineElement = new TSplineDataElement();
    splineElement->storeSpline(spline, fxFlags);
    m_splines.append(splineElement);
  }
}
References TStageObjectTree::getSplineById(), TXsheet::getStageObjectTree(), and TStageObjectDataElement::m_params.
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/toonzqt/stageobjectsdata.h
E:/opentoonz/toonz/sources/toonzqt/stageobjectsdata.cpp