opentoonz: PlasticDeformerFx Class Reference
PlasticDeformerFx Class Reference final
#include <plasticdeformerfx.h>
Public Member Functions
TFx * clone (bool recursive=true) const override
bool canHandle (const TRenderSettings &info, double frame) override
std::string getAlias (double frame, const TRenderSettings &info) const override
bool doGetBBox (double frame, TRectD &bbox, const TRenderSettings &info) override
void doCompute (TTile &tile, double frame, const TRenderSettings &info) override
void doDryCompute (TRectD &rect, double frame, const TRenderSettings &info) override
std::string getPluginId () const override
Public Member Functions inherited from TRasterFx
virtual bool getBBox (double frame, TRectD &bBox, TPixel32 &bgColor)=0
virtual string getName () const =0
virtual TRect getInvalidRect (const TRect &max)=0
virtual void compute (double frame, const TTile &tile)=0
virtual void allocateAndCompute (double frame, const TDimension size, const TPointD &pos, TTile &tile)
virtual void compute (TTile &tile, double frame, const TRenderSettings &info)
This method supplies the actual fx rendering code.
void allocateAndCompute (TTile &tile, const TPointD &pos, const TDimension &size, TRasterP templateRas, double frame, const TRenderSettings &info)
virtual bool doGetBBox (double frame, TRectD &bBox, const TRenderSettings &info)=0
bool getBBox (double frame, TRectD &bBox, const TRenderSettings &info)
virtual bool isCachable () const
virtual void transform (double frame, int port, const TRectD &rectOnOutput, const TRenderSettings &infoOnOutput, TRectD &rectOnInput, TRenderSettings &infoOnInput)
virtual bool canHandle (const TRenderSettings &info, double frame)=0
virtual TAffine handledAffine (const TRenderSettings &info, double frame)
void enableCache (bool on)
bool isCacheEnabled () const
std::string getAlias (double frame, const TRenderSettings &info) const override
virtual void dryCompute (TRectD &rect, double frame, const TRenderSettings &info)
virtual int getMemoryRequirement (const TRectD &rect, double frame, const TRenderSettings &info)
virtual bool allowUserCacheOnPort (int port)
virtual bool isPlugin () const
Public Member Functions inherited from TFx
virtual std::wstring getName () const
void setName (std::wstring name)
std::wstring getFxId () const
void setFxId (std::wstring id)
TParamContainer * getParams ()
const TParamContainer * getParams () const
void addParamVar (TParamVar *var)
virtual TFx * clone (bool recursive=true) const
TFx * clone (TFx *fx, bool recursive) const
void unlinkParams ()
virtual void linkParams (TFx *src)
TFx * getLinkedFx () const
bool addInputPort (const std::string &name, TFxPort &p)
bool addInputPort (const std::string &name, TFxPort *p, int groupIndex)
bool removeInputPort (const std::string &name)
returns false on duplicate names. Ownership is transferred to the group.
bool renamePort (const std::string &oldName, const std::string &newName)
if not found.
bool connect (const std::string &name, TFx *other)
Equivalent to getInputPort(name)->setFx(other).
bool disconnect (const std::string &name)
Equivalent to getInputPort(name)->setFx(0).
int getInputPortCount () const
TFxPort * getInputPort (int index) const
TFxPort * getInputPort (const std::string &name) const
std::string getInputPortName (int index) const
virtual int dynamicPortGroupsCount () const
virtual const TFxPortDG * dynamicPortGroup (int g) const
bool hasDynamicPortGroups () const
void clearDynamicPortGroup (int g)
bool addOutputConnection (TFxPort *port)
bool removeOutputConnection (TFxPort *port)
virtual bool isZerary () const
virtual int getReferenceColumnIndex () const
virtual TFxPort * getXsheetPort () const
int getOutputConnectionCount () const
TFxPort * getOutputConnection (int i) const
virtual TFxTimeRegion getTimeRegion () const
void setActiveTimeRegion (const TFxTimeRegion &tr)
TFxTimeRegion getActiveTimeRegion () const
virtual bool checkActiveTimeRegion () const
void disconnectAll ()
virtual void getParamUIs (TParamUIConcept *&params, int &length)
std::string getFxType () const
virtual std::string getPluginId () const =0
void onChange (const TParamChange &c) override
void addObserver (TFxObserver *)
void removeObserver (TFxObserver *)
void notify (const TFxChange &change)
void notify (const TFxPortAdded &change)
void notify (const TFxPortRemoved &change)
void notify (const TFxParamAdded &change)
void notify (const TFxParamRemoved &change)
void loadData (TIStream &is) override
void saveData (TOStream &os) override
void loadPreset (TIStream &is)
void savePreset (TOStream &os)
TFxAttributes * getAttributes () const
virtual std::string getAlias (double frame, const TRenderSettings &info) const
virtual void compatibilityTranslatePort (int majorVersion, int minorVersion, std::string &portName)
virtual int getPreferredInputPort ()
virtual void callStartRenderHandler ()
virtual void callEndRenderHandler ()
virtual void callStartRenderFrameHandler (const TRenderSettings *rs, double frame)
virtual void callEndRenderFrameHandler (const TRenderSettings *rs, double frame)
virtual void onObsoleteParamLoaded (const std::string &paramName)
void setFxVersion (int)
int getFxVersion () const
unsigned long getIdentifier () const
void setIdentifier (unsigned long id)
void setNewIdentifier ()
Public Member Functions inherited from TSmartObject
TSmartObject (ClassCode classCode)
void addRef ()
void release ()
TINT32 getRefCount () const
Public Member Functions inherited from TPersist
virtual void loadData (TIStream &is)=0
virtual void saveData (TOStream &os)=0
std::string getStreamTag () const
virtual const TPersistDeclaration * getDeclaration () const =0
virtual void onChange (const TParamChange &)=0
Public Attributes
TXsheet * m_xsh
The Fx's enclosing Xsheet.
int m_col
The input column index.
TAffine m_texPlacement
Texture to mesh reference transform.
TRasterFxPort m_port
Input port.
Additional Inherited Members
Public Types inherited from TFx
typedef TFx * CreateProc()
Public Types inherited from TSmartObject
typedef short ClassCode
Public Types inherited from TPersist
typedef TPersist * CreateProc()
Static Public Member Functions inherited from TRasterFx
static TRasterP applyAffine (TTile &tileOut, const TTile &tileIn, const TRenderSettings &info)
static int memorySize (const TRectD &rect, int bpp)
Static Public Member Functions inherited from TFx
static void listFxs (std::vector< TFxInfo > &fxInfos)
static TFxInfo getFxInfo (const std::string &fxIdentifier)
static TFx * create (std::string name)
Static Public Member Functions inherited from TSmartObject
static TINT32 getInstanceCount (ClassCode code)
Static Public Member Functions inherited from TPersist
static void declare (CreateProc *)
static TPersist * create (const std::string &name)
virtual void doCompute (TTile &tile, double frame, const TRenderSettings &settings)=0
virtual void doDryCompute (TRectD &rect, double frame, const TRenderSettings &info)
Detailed Description
PlasticDeformerFx is a hidden fx used to inject data about a plastic deformation just above a TLevelColumnFx instance.
Constructor & Destructor Documentation
PlasticDeformerFx()
PlasticDeformerFx::PlasticDeformerFx ()
                                     : TRasterFx() {
  addInputPort("source", m_port);
}
Member Function Documentation
canHandle()
bool PlasticDeformerFx::canHandle (const TRenderSettings & info, double frame) override virtual
Implements TRasterFx.
{
  // Yep. Affines are handled. Well - it's easy, since OpenGL lets you do that
  // directly
  // with a glPushMatrix...
  return true;
}
clone()
TFx * PlasticDeformerFx::clone (bool recursive = true) const override virtual
Reimplemented from TFx.
{
  PlasticDeformerFx *fx =
      dynamic_cast<PlasticDeformerFx *>(TFx::clone(recursive));
  assert(fx);
  fx->m_xsh = m_xsh;
  fx->m_col = m_col;
  return fx;
}
doCompute()
void PlasticDeformerFx::doCompute (TTile & tile, double frame, const TRenderSettings & info) override virtual
Implements TRasterFx.
{
  if (!m_port.isConnected()) {
    tile.getRaster()->clear();
    return;
  }
  int row = (int)frame;
  // Build texture data
  TRenderSettings texInfo(info);
  TAffine worldTexLevelToTexLevelAff;
  if (dynamic_cast<TLevelColumnFx *>(m_port.getFx())) {
    if (!buildTextureDataSl(frame, texInfo, worldTexLevelToTexLevelAff)) return;
  } else
    buildTextureData(frame, texInfo, worldTexLevelToTexLevelAff);
  // Initialize mesh level vars
  const TXshCell &meshCell = m_xsh->getCell(row, m_col);
  TXshSimpleLevel *meshSl = meshCell.getSimpleLevel();
  const TFrameId &meshFid = meshCell.getFrameId();
  if (!meshSl || meshSl->getType() != MESH_XSHLEVEL) return;
  // Retrieve mesh image and deformation
  TStageObject *meshColumnObj =
      m_xsh->getStageObject(TStageObjectId::ColumnId(m_col));
  TMeshImageP mi(meshSl->getFrame(meshFid, false));
  if (!mi) return;
  // Retrieve deformation data
  const PlasticSkeletonDeformationP &sd =
      meshColumnObj->getPlasticSkeletonDeformation();
  assert(sd);
  double sdFrame = meshColumnObj->paramsTime(frame);
  // Build dpi data
  TPointD meshDpi(meshSl->getDpi(meshFid, 0));
  assert(meshDpi.x != 0.0 && meshDpi.y != 0.0);
  // Build reference transforms data
  // Build affines
  const TAffine &imageToTextureAff           = texInfo.m_affine;
  const TAffine &worldTexLevelToWorldMeshAff = m_texPlacement;
  const TAffine &meshToWorldMeshAff =
      TScale(Stage::inch / meshDpi.x, Stage::inch / meshDpi.y);
  const TAffine &meshToTexLevelAff = worldTexLevelToTexLevelAff *
                                     worldTexLevelToWorldMeshAff.inv() *
                                     meshToWorldMeshAff;
  const TAffine &meshToTextureAff = imageToTextureAff * meshToTexLevelAff;
  // Retrieve deformer data
  TScale worldMeshToMeshAff(meshDpi.x / Stage::inch, meshDpi.y / Stage::inch);
  std::unique_ptr<const PlasticDeformerDataGroup> dataGroup(
      PlasticDeformerStorage::instance()->processOnce(
          sdFrame, mi.getPointer(), sd.getPointer(), sd->skeletonId(sdFrame),
          worldMeshToMeshAff));
  // Build texture
  // Build the mesh's bounding box and map it to input reference
  TRectD meshBBox(meshToTextureAff * mi->getBBox());
  // Now, build the tile's geometry
  TRectD texBBox;
  m_port->getBBox(frame, texBBox, texInfo);
  TRectD bbox = texBBox * meshBBox;
  if (bbox.getLx() <= 0.0 || bbox.getLy() <= 0.0) return;
  bbox.x0 = tfloor(bbox.x0);
  bbox.y0 = tfloor(bbox.y0);
  bbox.x1 = tceil(bbox.x1);
  bbox.y1 = tceil(bbox.y1);
  TDimension tileSize(tround(bbox.getLx()), tround(bbox.getLy()));
  // Then, compute the input image
  TTile inTile;
  m_port->allocateAndCompute(inTile, bbox.getP00(), tileSize, TRasterP(), frame,
                             texInfo);
  QOpenGLContext *context;
  // Draw the textured mesh
  {
    // Prepare texture
    TRaster32P tex(inTile.getRaster());
    TRop::depremultiply(tex);  // Textures must be stored depremultiplied.
                               // See docs about the tglDraw() below.
    static TAtomicVar var;
    const std::string &texId = "render_tex " + std::to_string(++var);
    // Prepare an OpenGL context
    context = new QOpenGLContext();
    if (QOpenGLContext::currentContext())
      context->setShareContext(QOpenGLContext::currentContext());
    context->setFormat(QSurfaceFormat::defaultFormat());
    context->create();
    context->makeCurrent(info.m_offScreenSurface.get());
    TDimension d = tile.getRaster()->getSize();
    QOpenGLFramebufferObject fb(d.lx, d.ly);
    fb.bind();
    // Load texture into the context
    TTexturesStorage *ts                = TTexturesStorage::instance();
    const DrawableTextureDataP &texData = ts->loadTexture(texId, tex, bbox);
    // Draw
    glViewport(0, 0, d.lx, d.ly);
    glClearColor(0, 0, 0, 0);
    glClear(GL_COLOR_BUFFER_BIT);
    glMatrixMode(GL_PROJECTION);
    glLoadIdentity();
    gluOrtho2D(0, d.lx, 0, d.ly);
    glMatrixMode(GL_MODELVIEW);
    glLoadIdentity();
    tglMultMatrix(TTranslation(-tile.m_pos) * info.m_affine *
                  meshToWorldMeshAff);
    glEnable(GL_BLEND);
    glEnable(GL_TEXTURE_2D);
    tglDraw(*mi, *texData, meshToTextureAff, *dataGroup);
    // Retrieve drawing and copy to output tile
    QImage img = fb.toImage().scaled(QSize(d.lx, d.ly), Qt::IgnoreAspectRatio,
                                     Qt::SmoothTransformation);
    int wrap   = tile.getRaster()->getLx() * sizeof(TPixel32);
    if (!m_was64bit) {
      uchar *srcPix = img.bits();
      uchar *dstPix = tile.getRaster()->getRawData() + wrap * (d.ly - 1);
      for (int y = 0; y < d.ly; y++) {
        memcpy(dstPix, srcPix, wrap);
        dstPix -= wrap;
        srcPix += wrap;
      }
    } else if (m_was64bit) {
      TRaster64P newRaster(tile.getRaster()->getSize());
      TRaster32P tempRaster(tile.getRaster()->getSize());
      uchar *srcPix = img.bits();
      uchar *dstPix = tempRaster.getPointer()->getRawData() + wrap * (d.ly - 1);
      for (int y = 0; y < d.ly; y++) {
        memcpy(dstPix, srcPix, wrap);
        dstPix -= wrap;
        srcPix += wrap;
      }
      TRop::convert(newRaster, tempRaster);
      int size = tile.getRaster()->getLx() * tile.getRaster()->getLy() *
                 sizeof(TPixel64);
      srcPix = newRaster.getPointer()->getRawData();
      dstPix = tile.getRaster()->getRawData();
      memcpy(dstPix, srcPix, size);
      texInfo.m_bpp = 64;
    }
    fb.release();
    // context->getRaster(tile.getRaster());
    glFlush();
    glFinish();
    // Cleanup
    // No need to disable stuff - the context dies here
    // ts->unloadTexture(texId);                                // Auto-released
    // due to display list destruction
    context->deleteLater();
    // context->doneCurrent();
  }
  assert(glGetError() == GL_NO_ERROR);
}
doDryCompute()
void PlasticDeformerFx::doDryCompute (TRectD & rect, double frame, const TRenderSettings & info) override virtual
Declares the computation scheme of this fx for rendering optimization purposes. This is an important function of the Toonz rendering API, and should be reimplemented with the necessary care. The Toonz rendering process makes use of this function to enact most of the optimization steps about the fx computation, in particular fx caching. A correct implementation of this method should follow these rules: The invocation of child node computations should be faithfully reproduced. TRasterFx::compute and TRasterFx::allocateAndCompute calls have to be translated to TRasterFx::dryCompute calls. This fx is intended for precomputation stage, so the hard rendering code should be skipped here. By default, this method raises a dryCompute call to each input port in increasing order, using the TRasterFx::transform method to identify the tiles to be passed on input precomputation.
Reimplemented from TRasterFx.
{
  if (!m_port.isConnected()) return;
  int row = (int)frame;
  TRenderSettings texInfo(info);
  TAffine worldTexLevelToTexLevelAff;
  if (dynamic_cast<TLevelColumnFx *>(m_port.getFx())) {
    if (!buildTextureDataSl(frame, texInfo, worldTexLevelToTexLevelAff)) return;
  } else
    buildTextureData(frame, texInfo, worldTexLevelToTexLevelAff);
  const TXshCell &meshCell = m_xsh->getCell(row, m_col);
  TXshSimpleLevel *meshSl = meshCell.getSimpleLevel();
  const TFrameId &meshFid = meshCell.getFrameId();
  if (!meshSl || meshSl->getType() == MESH_XSHLEVEL) return;
  TStageObject *meshColumnObj =
      m_xsh->getStageObject(TStageObjectId::ColumnId(m_col));
  TMeshImageP mi(meshSl->getFrame(meshFid, false));
  if (!mi) return;
  const PlasticSkeletonDeformationP &sd =
      meshColumnObj->getPlasticSkeletonDeformation();
  assert(sd);
  TPointD meshDpi(meshSl->getDpi(meshFid, 0));
  assert(meshDpi.x != 0.0 && meshDpi.y != 0.0);
  const TAffine &textureToImageAff        = texInfo.m_affine;
  const TAffine &worldImageToWorldMeshAff = m_texPlacement;
  const TAffine &meshToWorldMeshAff =
      TScale(Stage::inch / meshDpi.x, Stage::inch / meshDpi.y);
  const TAffine &meshToTextureAff =
      textureToImageAff.inv() * worldTexLevelToTexLevelAff *
      worldImageToWorldMeshAff.inv() * meshToWorldMeshAff;
  // Build the mesh's bounding box and map it to input reference
  TRectD meshBBox(meshToTextureAff * mi->getBBox());
  // Now, build the tile's geometry
  TRectD texBBox;
  m_port->getBBox(frame, texBBox, texInfo);
  TRectD bbox = texBBox * meshBBox;
  if (bbox.getLx() <= 0.0 || bbox.getLy() <= 0.0) return;
  bbox.x0 = tfloor(bbox.x0);
  bbox.y0 = tfloor(bbox.y0);
  bbox.x1 = tceil(bbox.x1);
  bbox.y1 = tceil(bbox.y1);
  m_port->dryCompute(bbox, frame, texInfo);
}
References TXsheet::getCell(), TXshCell::getFrameId(), TStageObject::getPlasticSkeletonDeformation(), TXshCell::getSimpleLevel(), TXsheet::getStageObject(), TXshLevel::getType(), Stage::inch, TAffine::inv(), TRenderSettings::m_affine, m_col, m_port, m_texPlacement, m_xsh, and TRectT< T >::x0.
doGetBBox()
bool PlasticDeformerFx::doGetBBox (double frame, TRectD & bbox, const TRenderSettings & info) override virtual
Implements TRasterFx.
{
  if (!m_port.isConnected()) return false;
  // It's hard work to calculate the bounding box of a plastic deformation.
  // Decline.
  bbox = TConsts::infiniteRectD;
  return true;
}
getAlias()
std::string PlasticDeformerFx::getAlias (double frame, const TRenderSettings & info) const override virtual
Reimplemented from TFx.
{
  std::string alias(getFxType());
  alias += "[";
  if (m_port.isConnected()) {
    TRasterFxP ifx = m_port.getFx();
    assert(ifx);
    alias += ifx->getAlias(frame, info);
  }
  TStageObject *meshColumnObj =
      m_xsh->getStageObject(TStageObjectId::ColumnId(m_col));
  const PlasticSkeletonDeformationP &sd =
      meshColumnObj->getPlasticSkeletonDeformation();
  if (sd) alias += ", " + toString(sd, meshColumnObj->paramsTime(frame));
  alias + "]";
  return alias;
}
getPluginId()
std::string PlasticDeformerFx::getPluginId () const inline override virtual
Implements TFx.
{ return std::string(); }
Member Data Documentation
m_col
int PlasticDeformerFx::m_col
The input column index.
Referenced by doDryCompute().
m_port
TRasterFxPort PlasticDeformerFx::m_port
Input port.
Referenced by doDryCompute().
m_texPlacement
TAffine PlasticDeformerFx::m_texPlacement
Texture to mesh reference transform.
Referenced by doDryCompute().
m_xsh
TXsheet* PlasticDeformerFx::m_xsh
The Fx's enclosing Xsheet.
Referenced by doDryCompute().
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/toonz/plasticdeformerfx.h
E:/opentoonz/toonz/sources/toonzlib/plasticdeformerfx.cpp