opentoonz: TStageObject Class Reference
TStageObject Class Reference final
#include <tstageobject.h>
Classes
struct Keyframe
Public Types
enum Status {
XY , PATH = 1 , PATH_AIM = 2 , IK = 3 ,
PATH_UPPK = 5 , PATH_AIM_UPPK = 6 , UPPK_MASK = 4 , STATUS_MASK = 3
}
enum Channel {
T_Angle , T_X , T_Y , T_Z ,
T_SO , T_ScaleX , T_ScaleY , T_Scale ,
T_Path , T_ShearX , T_ShearY , T_ChannelCount
}
Used to describe object parameters.
typedef std::map< int, Keyframe > KeyframeMap
Public Types inherited from TSmartObject
typedef short ClassCode
Public Member Functions
TStageObject (TStageObjectTree *tree, TStageObjectId id)
~TStageObject ()
TStageObjectId getId () const
Retrieves the stage object's id.
void setId (const TStageObjectId &id)
Sets the object's id.
void setName (const std::string &name)
std::string getName () const
bool hasSpecifiedName ()
bool hasSpecifiedName () const
std::string getFullName () const
bool isOpened () const
Returns whether this object is already in use.
void setIsOpened (bool value)
Sets the usage status of the object.
bool isLocked () const
Returns whether the object has been locked (can't move).
void lock (bool on)
Locks the object.
TPinnedRangeSet * getPinnedRangeSet () const
void setParent (const TStageObjectId &parentId)
Sets the object's parent.
TStageObjectId getParent () const
TStageObjectSpline * getSpline () const
Returns the motion path associated to the object.
void setSpline (TStageObjectSpline *spline)
void doSetSpline (TStageObjectSpline *spline)
bool isAncestor (TStageObject *stageObject) const
Returns whether stageObject is ancestor of this.
void setStatus (Status status)
Sets the object's status.
Status getStatus () const
Returns the object's status.
bool isAimEnabled () const
helper functions to manipulate status
bool isPathEnabled () const
bool isUppkEnabled () const
void enableAim (bool enabled)
void enablePath (bool enabled)
void enableUppk (bool enabled)
TPointD getDagNodePos () const
Returns object's position in the schematic view.
void setDagNodePos (const TPointD &p)
const std::string & getHandle () const
const std::string & getParentHandle () const
void setHandle (const std::string &s)
void setParentHandle (const std::string &s)
Sets the name of the pegbar parent handle name.
void setParam (Channel type, double frame, double val)
Sets the channel type to the value val.
double getParam (Channel type, double frame) const
Returns the TStageObject::Channel value associated with the frame.
void setCenter (double frame, const TPointD &center)
Sets the center of the frame to center.
TPointD getCenter (double frame) const
Returns the center of the frame.
TPointD getOffset () const
Returns the offset of the object.
void setOffset (const TPointD &off)
Sets the offset of the object.
void getCenterAndOffset (TPointD &center, TPointD &offset) const
void setCenterAndOffset (const TPointD &center, const TPointD &offset)
bool isKeyframe (int frame) const
Returns true if frame is a keyframe.
bool isFullKeyframe (int frame) const
Returns true if frame is a keyframe for all channels.
bool is52FullKeyframe (int frame) const
Keyframe getKeyframe (int frame) const
void setKeyframeWithoutUndo (int frame, const Keyframe &)
void setKeyframeWithoutUndo (int frame)
void removeKeyframeWithoutUndo (int frame)
bool moveKeyframe (int dst, int src)
bool canMoveKeyframes (std::set< int > &frames, int delta)
bool moveKeyframes (std::set< int > &frames, int delta)
void getKeyframes (KeyframeMap &keyframes) const
bool getKeyframeRange (int &r0, int &r1) const
bool getKeyframeSpan (int row, int &r0, double &ease0, int &r1, double &ease1) const
TAffine getPlacement (double t)
TAffine getParentPlacement (double t) const
double getZ (double frame)
double getSO (double frame)
Returns the object's stacking order at specified frame.
double getGlobalNoScaleZ () const
Returns the absolute depth with no scale factor.
double getNoScaleZ () const
This method returns the original depth of the pegbar.
void setNoScaleZ (double noScaleZ)
PlasticSkeletonDeformationP getPlasticSkeletonDeformation () const
Returns the stored skeleton deformation, if any.
void setPlasticSkeletonDeformation (const PlasticSkeletonDeformationP &sd)
Stores the specified skeleton deformation.
bool hasChildren () const
Returns whether the object has children.
const std::list< TStageObject * > & getChildren () const
bool isCycleEnabled () const
void enableCycle (bool on)
TAffine getLocalPlacement (double frame)
TDoubleParam * getParam (Channel channel) const
Returns the channel's value of the object.
TStageObject * clone ()
TStageObjectParams * getParams () const
Returns a new data-structure filled with the actual data of the object.
void assignParams (const TStageObjectParams *src, bool doParametersClone=true)
Sets the object's values to src values and update the object.
TCamera * getCamera ()
Returns a pointer to the actual camera.
const TCamera * getCamera () const
void detachFromParent ()
void attachChildrenToParent (const TStageObjectId &parentId)
Makes all children of this children of parentId.
void invalidate ()
void loadData (TIStream &is)
void saveData (TOStream &os)
int setGroupId (int value)
void setGroupId (int value, int position)
int getGroupId ()
QStack< int > getGroupIdStack ()
void removeGroupId (int position)
int removeGroupId ()
bool isGrouped ()
bool isContainedInGroup (int groupId)
void setGroupName (const std::wstring &name, int position=-1)
std::wstring getGroupName (bool fromEditor)
QStack< std::wstring > getGroupNameStack ()
int removeGroupName (bool fromEditor)
void removeGroupName (int position=-1)
void removeFromAllGroup ()
void editGroup ()
bool isGroupEditing ()
void closeEditingGroup (int groupId)
int getEditingGroupId ()
std::wstring getEditingGroupName ()
void updateKeyframes ()
Rebuilds the internal keyframes table.
double paramsTime (double t) const
for param values extraction (dealing with repeat/cycling)
Public Member Functions inherited from TSmartObject
TSmartObject (ClassCode classCode)
void addRef ()
void release ()
TINT32 getRefCount () const
Public Member Functions inherited from TParamObserver
virtual void onChange (const TParamChange &)=0
Static Public Member Functions
static bool perspective (TAffine &aff, const TAffine &cameraAff, double cameraZ, const TAffine &objectAff, double objectZ, double objectNoScaleZ)
Static Public Member Functions inherited from TSmartObject
static TINT32 getInstanceCount (ClassCode code)
Detailed Description
TStageObject is the Toonz class representing animatable scene objects like columns, pegbars, tables and cameras (pretty much every object in Toonz's stage schematic).
Description
A TStageObject contains a common set of editable parameters (coordinates, angles and more) that define the object's state along an xsheet timeline. These parameters are in the form of animatable TDoubleParam instances and can be accessed directly through the getParam() method.
A notable responsibility of the TStageObject class is that of building the keyframes data that will be shown in xsheet viewes (the key icons). The object's keyframes are built and cached each time one of its associated parameters is changed.
Furthermore, a TStageObject instance is typically a node in a tree-like hierarchycal structure of class TStageObjectTree which is used to define relative object placement between objects.
Creation
Client code should access TStageObject instances through its TXsheet owner, like:
TStageObjectId objectId = TApp::instance()->getCurrentObject()->getObjectId();
TStageObject* stageObject = TApp::instance()->getCurrentXsheet()
  ->getXsheet()->getStageObject(objectId);
The actual creation of new TStageObject instances is currently a responsibility of the TStageObjectTree class.
Member Typedef Documentation
KeyframeMap
typedef std::map<int, Keyframe> TStageObject::KeyframeMap
Define a map of int and keyframe necessary to know object keyframe; Its purpose is the indexing of the object's keyframes.
Member Enumeration Documentation
Channel
enum TStageObject::Channel
Used to describe object parameters.
Enumerator
T_Angle
Object's angle (rotation)
T_X
Local x coordinate in inches.
T_Y
Local y coordinate in inches.
T_Z
Layer depth.
T_SO
Stacking Order.
T_ScaleX
X-axis scale factor.
T_ScaleY
Y-axis scale factor.
T_Path
point position along the spline, as a percentage of the length of the spline
T_ShearX
Shear along x-axis.
T_ShearY
Shear along y-axis.
               {
    T_Angle,
    T_X,
    T_Y,
    T_Z,
    T_SO,
    T_ScaleX,
    T_ScaleY,
    T_Scale,
    T_Path,
    T_ShearX,
    T_ShearY,
    T_ChannelCount
  };
Status
enum TStageObject::Status
Used to describe the object status - ie how the object can move. The default value is XY.
Enumerator
XY
The object can move freely on a plane.
PATH
The movement take place on a spline.
PATH_AIM
The movement take place on a spline with the orientation of the object defined by the user through TStageObject::T_Angle and the total angle is the sum of the user angle plus the angle formed by the tangent at the curve in the actual point
IK
The object is translated according to inverse kinematics.
PATH_UPPK
PATH + UPPK (Update Pos Path Keyframe, when the spline is changed; see TStageObjectSpline)
PATH_AIM_UPPK
PATH_AIM + UPPK.
UPPK_MASK
(status&UPPK_MASK)!=0 <==> UPPK enabled
STATUS_MASK
(status&STATUS_MASK) => old status
              {
    XY,
    PATH     = 1,
    PATH_AIM = 2,
    IK = 3,
    PATH_UPPK = 5,
    PATH_AIM_UPPK = 6,
    UPPK_MASK     = 4,
    STATUS_MASK   = 3
  };
Constructor & Destructor Documentation
TStageObject()
TStageObject::TStageObject (TStageObjectTree * tree, TStageObjectId id)
Initializes a stage object in his tree with an unique id.
The constructor is called by TStageObjectTree to create a new column in the tree or in general a new node in the tree.
    : m_tree(tree)
    , m_id(id)
    , m_parent(0)
    , m_name("")
    , m_isOpened(false)
    , m_spline(0)
    , m_status(XY)
    , m_x(new TDoubleParam())
    , m_y(new TDoubleParam())
    , m_z(new TDoubleParam())
    , m_so(new TDoubleParam())
    , m_rot(new TDoubleParam())
    , m_scalex(new TDoubleParam(1.0))
    , m_scaley(new TDoubleParam(1.0))
    , m_scale(new TDoubleParam(1.0))
    , m_posPath(new TDoubleParam())
    , m_shearx(new TDoubleParam())
    , m_sheary(new TDoubleParam())
    , m_center()
    , m_offset()
    , m_cycleEnabled(false)
    , m_handle("B")
    , m_parentHandle("B")
    , m_dagNodePos(TConst::nowhere)
    , m_camera(0)
    , m_locked(false)
    , m_noScaleZ(0)
    , m_pinnedRangeSet(0)
    , m_ikflag(0)
    , m_groupSelector(-1) {
  // NOTA: per le unita' di misura controlla anche tooloptions.cpp
  m_x->setName("W_X");
  m_x->setMeasureName("length.x");
  m_x->addObserver(this);
  m_y->setName("W_Y");
  m_y->setMeasureName("length.y");
  m_y->addObserver(this);
  m_z->setName("W_Z");
  m_z->setMeasureName(id.isCamera() ? "zdepth.cam" : "zdepth");
  m_z->addObserver(this);
  m_so->setName("W_SO");
  m_so->addObserver(this);
  m_rot->setName("W_Rotation");
  m_rot->setMeasureName("angle");
  m_rot->addObserver(this);
  m_scalex->setName("W_ScaleH");
  m_scalex->setMeasureName("scale");
  m_scalex->addObserver(this);
  m_scaley->setName("W_ScaleV");
  m_scaley->setMeasureName("scale");
  m_scaley->addObserver(this);
  m_scale->setName("W_Scale");
  m_scale->setMeasureName("scale");
  m_scale->addObserver(this);
  m_shearx->setName("W_ShearH");
  m_shearx->setMeasureName("shear");
  m_shearx->addObserver(this);
  m_sheary->setName("W_ShearV");
  m_sheary->setMeasureName("shear");
  m_sheary->addObserver(this);
  m_posPath->setName("posPath");
  m_posPath->setMeasureName("percentage2");
  m_posPath->addObserver(this);
  m_tree->setGrammar(m_x);
  m_tree->setGrammar(m_y);
  m_tree->setGrammar(m_z);
  m_tree->setGrammar(m_so);
  m_tree->setGrammar(m_rot);
  m_tree->setGrammar(m_scalex);
  m_tree->setGrammar(m_scaley);
  m_tree->setGrammar(m_scale);
  m_tree->setGrammar(m_shearx);
  m_tree->setGrammar(m_sheary);
  m_tree->setGrammar(m_posPath);
  if (id.isCamera()) m_camera = new TCamera();
  m_pinnedRangeSet = new TPinnedRangeSet();
}
~TStageObject()
TStageObject::~TStageObject ()
This is the destructor.
{
  if (m_spline) {
    if (m_posPath) m_spline->removeParam(m_posPath.getPointer());
    m_spline->release();
  }
  if (m_x) m_x->removeObserver(this);
  if (m_y) m_y->removeObserver(this);
  if (m_z) m_z->removeObserver(this);
  if (m_so) m_so->removeObserver(this);
  if (m_rot) m_rot->removeObserver(this);
  if (m_scalex) m_scalex->removeObserver(this);
  if (m_scaley) m_scaley->removeObserver(this);
  if (m_scale) m_scale->removeObserver(this);
  if (m_shearx) m_shearx->removeObserver(this);
  if (m_sheary) m_sheary->removeObserver(this);
  if (m_posPath) m_posPath->removeObserver(this);
  if (m_skeletonDeformation) {
    PlasticDeformerStorage::instance()->releaseDeformationData(
        m_skeletonDeformation.getPointer());
    m_skeletonDeformation->removeObserver(this);
  }
  delete m_camera;
  delete m_pinnedRangeSet;
}
References PlasticDeformerStorage::releaseDeformationData().
Member Function Documentation
assignParams()
void TStageObject::assignParams (const TStageObjectParams * src, bool doParametersClone = true)
Sets the object's values to src values and update the object.
{
  m_name     = src->m_name;
  m_center   = src->m_center;
  m_noScaleZ = src->m_noScaleZ;
  m_offset   = src->m_offset;
  m_status   = src->m_status;
  if (m_spline) m_spline->release();
  m_spline = src->m_spline;
  if (m_spline) m_spline->addRef();
  if (doParametersClone) {
    m_x->copy(src->m_x.getPointer());
    m_y->copy(src->m_y.getPointer());
    m_z->copy(src->m_z.getPointer());
    m_so->copy(src->m_so.getPointer());
    m_rot->copy(src->m_rot.getPointer());
    m_scalex->copy(src->m_scalex.getPointer());
    m_scaley->copy(src->m_scaley.getPointer());
    m_scale->copy(src->m_scale.getPointer());
    m_posPath->copy(src->m_posPath.getPointer());
    m_shearx->copy(src->m_shearx.getPointer());
    m_sheary->copy(src->m_sheary.getPointer());
    if (src->m_skeletonDeformation)
      setPlasticSkeletonDeformation(
          new PlasticSkeletonDeformation(*src->m_skeletonDeformation));
  } else {
    m_x = src->m_x.getPointer();
    m_x->addObserver(this);
    m_y = src->m_y.getPointer();
    m_y->addObserver(this);
    m_z = src->m_z.getPointer();
    m_z->addObserver(this);
    m_so = src->m_so.getPointer();
    m_so->addObserver(this);
    m_rot = src->m_rot.getPointer();
    m_rot->addObserver(this);
    m_scalex = src->m_scalex.getPointer();
    m_scalex->addObserver(this);
    m_scaley = src->m_scaley.getPointer();
    m_scaley->addObserver(this);
    m_scale = src->m_scale.getPointer();
    m_scale->addObserver(this);
    m_posPath = src->m_posPath.getPointer();
    m_posPath->addObserver(this);
    m_shearx = src->m_shearx.getPointer();
    m_shearx->addObserver(this);
    m_sheary = src->m_sheary.getPointer();
    m_sheary->addObserver(this);
    m_skeletonDeformation = src->m_skeletonDeformation;
    if (m_skeletonDeformation) m_skeletonDeformation->addObserver(this);
  }
  m_handle       = src->m_handle;
  m_parentHandle = src->m_parentHandle;
  m_cycleEnabled = src->m_cycleEnabled;
  if (m_pinnedRangeSet) *m_pinnedRangeSet = *src->m_pinnedRangeSet;
  updateKeyframes();
  if (m_spline && isUppkEnabled()) m_spline->addParam(m_posPath.getPointer());
  invalidate();
}
References TStageObjectSpline::addParam(), invalidate(), TStageObjectParams::m_skeletonDeformation, setPlasticSkeletonDeformation(), and updateKeyframes().
Referenced by TCameraDataElement::restoreCamera(), TColumnDataElement::restoreColumn(), and TStageObjectDataElement::restoreObject().
attachChildrenToParent()
void TStageObject::attachChildrenToParent (const TStageObjectId & parentId)
Makes all children of this children of parentId.
{
  while (!m_children.empty()) {
    TStageObject *son = *m_children.begin();
    if (son) son->setParent(parentId);
  }
}
References setParent().
Referenced by TStageObjectTree::removeColumn(), and TStageObjectTree::removeStageObject().
canMoveKeyframes()
bool TStageObject::canMoveKeyframes (std::set< int > & frames, int delta)
{
  if (delta == 0) return false;
  std::set<int>::iterator it;
  for (it = frames.begin(); it != frames.end(); ++it) {
    int f = *it;
    if (!isKeyframe(f)) return false;
    f += delta;
    if (f < 0) return false;
    if (frames.find(f) == frames.end() && isKeyframe(f)) return false;
  }
  return true;
}
clone()
TStageObject * TStageObject::clone ()
Copies the data of the object in a new object with a new id and adds it to the tree.
{
  assert(m_tree);
  TStageObjectId pegId    = getId();
  TStageObjectId newPegId = TStageObjectId::NoneId;
  int newIndex            = pegId.getIndex();
  if (pegId.isCamera()) {
    while ((m_tree->getStageObject(TStageObjectId::CameraId(newIndex), false) !=
            0L) ||
           (pegId.getIndex() == newIndex))
      ++newIndex;
    newPegId = TStageObjectId::CameraId(newIndex);
  } else if (pegId.isColumn()) {
    while ((m_tree->getStageObject(TStageObjectId::ColumnId(newIndex), false) !=
            0L) ||
           (pegId.getIndex() == newIndex))
      ++newIndex;
    newPegId = TStageObjectId::ColumnId(newIndex);
  } else if (pegId.isPegbar()) {
    while ((m_tree->getStageObject(TStageObjectId::PegbarId(newIndex), false) !=
            0L) ||
           (pegId.getIndex() == newIndex))
      ++newIndex;
    newPegId = TStageObjectId::PegbarId(newIndex);
  } else {
    assert(!"Unknown stage object type");
    return 0L;
  }
  assert(newPegId != TStageObjectId::NoneId);
  assert(newIndex >= 0);
  assert(newPegId.getIndex() != pegId.getIndex());
  // aggiunge lo stage object clonato nel stage object tree
  TStageObject *clonedPeg = m_tree->getStageObject(newPegId, true);
  TStageObject *cloned    = clonedPeg;
  assert(cloned);
  assert(cloned->m_tree == m_tree);
  KeyframeMap &keyframes       = lazyData().m_keyframes;
  KeyframeMap &clonedKeyframes = cloned->lazyData().m_keyframes;
  std::map<int, TStageObject::Keyframe>::iterator itKf = keyframes.begin();
  for (; itKf != keyframes.end(); ++itKf) {
    clonedKeyframes.insert(make_pair(itKf->first, itKf->second));
  }
  cloned->m_cycleEnabled    = m_cycleEnabled;
  cloned->lazyData().m_time = lazyData().m_time;
  cloned->m_localPlacement  = m_localPlacement;
  cloned->m_absPlacement    = m_absPlacement;
  cloned->m_status          = m_status;
  cloned->doSetSpline(m_spline);
  cloned->m_x       = static_cast<TDoubleParam *>(m_x->clone());
  cloned->m_y       = static_cast<TDoubleParam *>(m_y->clone());
  cloned->m_z       = static_cast<TDoubleParam *>(m_z->clone());
  cloned->m_so      = static_cast<TDoubleParam *>(m_so->clone());
  cloned->m_rot     = static_cast<TDoubleParam *>(m_rot->clone());
  cloned->m_scalex  = static_cast<TDoubleParam *>(m_scalex->clone());
  cloned->m_scaley  = static_cast<TDoubleParam *>(m_scaley->clone());
  cloned->m_scale   = static_cast<TDoubleParam *>(m_scale->clone());
  cloned->m_posPath = static_cast<TDoubleParam *>(m_posPath->clone());
  cloned->m_shearx  = static_cast<TDoubleParam *>(m_shearx->clone());
  cloned->m_sheary  = static_cast<TDoubleParam *>(m_sheary->clone());
  if (m_skeletonDeformation)
    cloned->m_skeletonDeformation =
        new PlasticSkeletonDeformation(*m_skeletonDeformation);
  cloned->m_noScaleZ   = m_noScaleZ;
  cloned->m_center     = m_center;
  cloned->m_offset     = m_offset;
  cloned->m_name       = m_name;
  cloned->m_dagNodePos = m_dagNodePos;
  return cloned;
}
References doSetSpline(), getId(), TStageObjectTree::getStageObject(), TStageObjectId::isCamera(), TStageObjectId::isColumn(), and TStageObjectId::isPegbar().
closeEditingGroup()
void TStageObject::closeEditingGroup (int groupId)
{
  if (!m_groupId.contains(groupId)) return;
  m_groupSelector = 0;
  while (m_groupId[m_groupSelector] != groupId &&
         m_groupSelector < m_groupId.size())
    m_groupSelector++;
}
detachFromParent()
void TStageObject::detachFromParent ()
Removes this object from the list of children of his actual parent. Doesn't delete this.
{
  if (m_parent) m_parent->m_children.remove(this);
  m_parent = 0;
  invalidate();
}
References invalidate().
Referenced by TStageObjectTree::removeColumn(), and TStageObjectTree::removeStageObject().
doSetSpline()
void TStageObject::doSetSpline (TStageObjectSpline * spline)
As setSpline(), but doesn't notify; actually setSpline() calls doSetSpline() and then notifies
Note
does NOT take spline ownership
{
  TDoubleParam *param = m_posPath.getPointer();
  bool uppkEnabled    = isUppkEnabled();
  if (!spline) {
    if (uppkEnabled && m_spline) m_spline->removeParam(param);
    if (m_spline) m_spline->release();
    m_spline = 0;
    enablePath(false);
  } else {
    if (m_spline != spline) {
      if (m_spline && uppkEnabled) m_spline->removeParam(param);
      if (m_spline) m_spline->release();
      m_spline = spline;
      m_spline->addRef();
      if (m_spline && uppkEnabled) m_spline->addParam(param);
    }
    if (!isPathEnabled()) enablePath(true);
  }
}
References TStageObjectSpline::addParam().
Referenced by clone(), setSpline(), and setStatus().
editGroup()
void TStageObject::editGroup ()
{ m_groupSelector--; }
enableAim()
void TStageObject::enableAim (bool enabled)
{
  setStatus((Status)((m_status & ~STATUS_MASK) | (enabled ? PATH_AIM : PATH)));
}
enableCycle()
void TStageObject::enableCycle (bool on)
Enables cycle of the object, this method is provided to take care of the position of the viewer in the sequence.
See also
isCycleEnabled()
{ m_cycleEnabled = on; }
enablePath()
void TStageObject::enablePath (bool enabled)
{
  if (isPathEnabled() != enabled) setStatus(enabled ? PATH : XY);
}
enableUppk()
void TStageObject::enableUppk (bool enabled)
{
  assert(isPathEnabled());
  setStatus((Status)((m_status & ~UPPK_MASK) | (enabled ? UPPK_MASK : 0)));
}
getCamera() [1/2]
TCamera * TStageObject::getCamera () inline
Returns a pointer to the actual camera.
{ return m_camera; }
Referenced by TSceneProperties::cloneCamerasFrom(), TSceneProperties::cloneCamerasTo(), TStageObjectTree::getCamera(), OutputSettingsPopup::onAddPresetButtonPressed(), TCameraDataElement::restoreCamera(), and TCameraDataElement::storeCamera().
getCamera() [2/2]
const TCamera * TStageObject::getCamera () const inline
{ return m_camera; }
getCenter()
TPointD TStageObject::getCenter (double frame) const
Returns the center of the frame.
{
  return m_center + getHandlePos(m_handle, (int)frame);
}
getCenterAndOffset()
void TStageObject::getCenterAndOffset (TPointD & center, TPointD & offset) const
{
  center = m_center;
  offset = m_offset;
}
getChildren()
const std::list< TStageObject * > & TStageObject::getChildren () const inline
{ return m_children; }
getDagNodePos()
TPointD TStageObject::getDagNodePos () const inline
Returns object's position in the schematic view.
{ return m_dagNodePos; }
Referenced by TCameraDataElement::storeCamera(), TStageObjectDataElement::storeObject(), and StageSchematicScene::updateScene().
getEditingGroupId()
int TStageObject::getEditingGroupId ()
{
  if (!isGrouped() || m_groupSelector + 1 >= m_groupId.size()) return -1;
  return m_groupId[m_groupSelector + 1];
}
getEditingGroupName()
wstring TStageObject::getEditingGroupName ()
{
  if (!isGrouped() || m_groupSelector + 1 >= m_groupName.size()) return L"";
  return m_groupName[m_groupSelector + 1];
}
getFullName()
string TStageObject::getFullName () const
Returns the id's full name, ie the name of the object with its id appended.
{
  string name = getName();
  if (m_id.isColumn()) {
    if (name.find("Col") == 0 && name.length() > 3 &&
        name.find_first_not_of("0123456789", 3) == string::npos)
      return name;
    else
      return name + " (" + std::to_string(m_id.getIndex() + 1) + ")";
  } else
    return name;
}
References TStageObjectId::isColumn().
Referenced by EditTool::draw().
getGlobalNoScaleZ()
double TStageObject::getGlobalNoScaleZ () const
Returns the absolute depth with no scale factor.
{
  return m_parent ? m_parent->getGlobalNoScaleZ() + m_noScaleZ : m_noScaleZ;
}
References getGlobalNoScaleZ().
Referenced by StageBuilder::addCell(), TXsheet::getBBox(), TTool::getColumnMatrix(), and getGlobalNoScaleZ().
getGroupId()
int TStageObject::getGroupId ()
{
  return m_groupId.isEmpty() || m_groupSelector < 0 ||
                 m_groupSelector >= m_groupId.size()
             ? 0
             : m_groupId[m_groupSelector];
}
getGroupIdStack()
QStack< int > TStageObject::getGroupIdStack ()
{ return m_groupId; }
getGroupName()
wstring TStageObject::getGroupName (bool fromEditor)
{
  int groupSelector = fromEditor ? m_groupSelector + 1 : m_groupSelector;
  return m_groupName.isEmpty() || groupSelector < 0 ||
                 groupSelector >= m_groupName.size()
             ? L""
             : m_groupName[groupSelector];
}
getGroupNameStack()
QStack< wstring > TStageObject::getGroupNameStack ()
{ return m_groupName; }
getHandle()
const std::string & TStageObject::getHandle () const inline
Returns string containing pegbar handle name like A,B...Z, or H1,H2...H8.
It refers to the handle of the actual pegbar, ie the offset center of the pegbar. The default value is B that centers the pegbar and corresponds to an hook with index equal to 0. Hooks are column references (0 is the center) in the sheet and are data structures defined in the file hook.h.
H1 has an index equal to 1, H2 => 2 and so on.
See also
setHandle() and getParentHandle()
{ return m_handle; }
Referenced by StageSchematicScene::updateScene().
getId()
TStageObjectId TStageObject::getId () const
Retrieves the stage object's id.
{ return m_id; }
Referenced by clone(), StageObjectChannelGroup::data(), SkeletonTool::draw(), StageSchematicScene::getCurrentNode(), TStageObjectTree::insertStageObject(), StageSchematicNodePort::linkTo(), ColumnPainter::paint(), GroupPainter::paint(), TCameraDataElement::restoreCamera(), TColumnDataElement::restoreColumn(), TStageObjectDataElement::restoreObject(), setParent(), TColumnDataElement::storeColumn(), StageSchematicScene::updateScene(), and ArrowToolOptionsBox::updateStageObjectComboItems().
getKeyframe()
TStageObject::Keyframe TStageObject::getKeyframe (int frame) const
Retrieves from the list of the keyframes a keyframe object (TStageObject::Keyframe) associated with the frame.
{
  const KeyframeMap &keyframes = lazyData().m_keyframes;
  std::map<int, TStageObject::Keyframe>::const_iterator it;
  it = keyframes.find(frame);
  if (it == keyframes.end()) {
    TStageObject::Keyframe k;
    k.m_channels[TStageObject::T_Angle]  = m_rot->getValue(frame);
    k.m_channels[TStageObject::T_X]      = m_x->getValue(frame);
    k.m_channels[TStageObject::T_Y]      = m_y->getValue(frame);
    k.m_channels[TStageObject::T_Z]      = m_z->getValue(frame);
    k.m_channels[TStageObject::T_SO]     = m_so->getValue(frame);
    k.m_channels[TStageObject::T_ScaleX] = m_scalex->getValue(frame);
    k.m_channels[TStageObject::T_ScaleY] = m_scaley->getValue(frame);
    k.m_channels[TStageObject::T_Scale]  = m_scale->getValue(frame);
    k.m_channels[TStageObject::T_Path]   = m_posPath->getValue(frame);
    k.m_channels[TStageObject::T_ShearX] = m_shearx->getValue(frame);
    k.m_channels[TStageObject::T_ShearY] = m_sheary->getValue(frame);
    if (m_skeletonDeformation)
      m_skeletonDeformation->getKeyframeAt(frame, k.m_skeletonKeyframe);
    k.m_isKeyframe = false;
    return k;
  } else
    return it->second;
}
References PlasticSkeletonDeformation::getKeyframeAt(), TStageObject::Keyframe::m_channels, TStageObject::Keyframe::m_isKeyframe, TStageObject::Keyframe::m_skeletonKeyframe, T_Angle, T_Path, T_ScaleX, T_ScaleY, T_ShearX, T_ShearY, T_SO, T_X, T_Y, and T_Z.
Referenced by moveKeyframe().
getKeyframeRange()
bool TStageObject::getKeyframeRange (int & r0, int & r1) const
{
  const KeyframeMap &keyframes = lazyData().m_keyframes;
  if (keyframes.empty()) {
    r0 = 0;
    r1 = -1;
    return false;
  }
  r0 = keyframes.begin()->first;
  r1 = keyframes.rbegin()->first;
  return true;
}
getKeyframes()
void TStageObject::getKeyframes (KeyframeMap & keyframes) const
Gets a range of keyframes
{
  keyframes = lazyData().m_keyframes;
}
getKeyframeSpan()
bool TStageObject::getKeyframeSpan (int row, int & r0, double & ease0, int & r1, double & ease1) const
{
  const KeyframeMap &keyframes = lazyData().m_keyframes;
  KeyframeMap::const_iterator it = keyframes.lower_bound(row);
  if (it == keyframes.end() || it == keyframes.begin() || it->first == row) {
    r0    = 0;
    r1    = -1;
    ease0 = ease1 = 0;
    return false;
  }
  r1    = it->first;
  ease1 = it->second.m_easeIn;
  --it;
  r0    = it->first;
  ease0 = it->second.m_easeOut;
  return true;
}
getLocalPlacement()
TAffine TStageObject::getLocalPlacement (double frame) inline
Gets local placement of the object taking care of translation, rotation, shear and scale of the frame
{
    return computeLocalPlacement(frame);
  }
getName()
string TStageObject::getName () const
{
  if (m_name != "") return m_name;
  if (!m_id.isColumn()) return m_id.toString();
  return "Col" + std::to_string(m_id.getIndex() + 1);
}
getNoScaleZ()
double TStageObject::getNoScaleZ () const
This method returns the original depth of the pegbar.
{ return m_noScaleZ; }
getOffset()
TPointD TStageObject::getOffset () const
Returns the offset of the object.
See also
setOffset().
{ return m_offset; }
getParam() [1/2]
TDoubleParam * TStageObject::getParam (Channel channel) const
Returns the channel's value of the object.
{
  switch (channel) {
  case T_X:
    return m_x.getPointer();
  case T_Y:
    return m_y.getPointer();
  case T_Z:
    return m_z.getPointer();
  case T_SO:
    return m_so.getPointer();
  case T_Angle:
    return m_rot.getPointer();
  case T_Path:
    return m_posPath.getPointer();
  case T_ScaleX:
    return m_scalex.getPointer();
  case T_ScaleY:
    return m_scaley.getPointer();
  case T_Scale:
    return m_scale.getPointer();
  case T_ShearX:
    return m_shearx.getPointer();
  case T_ShearY:
    return m_sheary.getPointer();
  default:
    return 0;
  }
}
References T_Angle, T_Path, T_ScaleX, T_ScaleY, T_ShearX, T_ShearY, T_SO, T_X, T_Y, and T_Z.
getParam() [2/2]
double TStageObject::getParam (Channel type, double frame) const
Returns the TStageObject::Channel value associated with the frame.
{
  switch (type) {
  case T_Angle:
    return m_rot->getValue(frame);
  case T_X:
    return m_x->getValue(frame);
  case T_Y:
    return m_y->getValue(frame);
  case T_Z:
    return m_z->getValue(frame);
  case T_SO:
    return m_so->getValue(frame);
  case T_ScaleX:
    return m_scalex->getValue(frame);
  case T_ScaleY:
    return m_scaley->getValue(frame);
  case T_Scale:
    return m_scale->getValue(frame);
  case T_Path:
    return m_posPath->getValue(frame);
  case T_ShearX:
    return m_shearx->getValue(frame);
  case T_ShearY:
    return m_sheary->getValue(frame);
  default:
    assert(false);
    return 0;
  }
}
References T_Angle, T_Path, T_ScaleX, T_ScaleY, T_ShearX, T_ShearY, T_SO, T_X, T_Y, and T_Z.
Referenced by setStatus().
getParams()
TStageObjectParams * TStageObject::getParams () const
Returns a new data-structure filled with the actual data of the object.
{
  TStageObjectParams *data = new TStageObjectParams();
  data->m_name             = m_name;
  data->m_center           = m_center;
  data->m_noScaleZ         = m_noScaleZ;
  data->m_id       = m_id;
  data->m_parentId = getParent();
  data->m_offset   = m_offset;
  data->m_status   = m_status;
  data->m_x       = m_x;
  data->m_y       = m_y;
  data->m_z       = m_z;
  data->m_so      = m_so;
  data->m_rot     = m_rot;
  data->m_scalex  = m_scalex;
  data->m_scaley  = m_scaley;
  data->m_scale   = m_scale;
  data->m_posPath = m_posPath;
  data->m_shearx  = m_shearx;
  data->m_sheary  = m_sheary;
  data->m_skeletonDeformation = m_skeletonDeformation;
  data->m_cycleEnabled = m_cycleEnabled;
  data->m_spline       = m_spline;
  data->m_handle       = m_handle;
  data->m_parentHandle = m_parentHandle;
  if (m_pinnedRangeSet) data->m_pinnedRangeSet = m_pinnedRangeSet->clone();
  return data;
}
References getParent(), and TStageObjectParams::m_skeletonDeformation.
Referenced by TCameraDataElement::storeCamera(), and TStageObjectDataElement::storeObject().
getParent()
TStageObjectId TStageObject::getParent () const
Returns the id of the object's parent. Use the owner xsheet to access the parent object.
{
  return m_parent ? m_parent->m_id : TStageObjectId();
}
Referenced by StageBuilder::addCell(), StageBuilder::addCellWithOnionSkin(), getParams(), TStageObjectTree::insertStageObject(), TStageObjectTree::removeColumn(), TStageObjectTree::removeStageObject(), and StageSchematicScene::updateScene().
getParentHandle()
const std::string & TStageObject::getParentHandle () const inline
Return string containing pegbar parent handle name. Es.: A,B...Z, or H1,H2...H8.
See also
setParentHandle() and getHandle()
{ return m_parentHandle; }
Referenced by StageBuilder::addCell(), and StageSchematicScene::updateScene().
getParentPlacement()
TAffine TStageObject::getParentPlacement (double t) const
{
  return m_parent ? m_parent->getPlacement(t) : TAffine();
}
getPinnedRangeSet()
TPinnedRangeSet * TStageObject::getPinnedRangeSet () const inline
{ return m_pinnedRangeSet; }
getPlacement()
TAffine TStageObject::getPlacement (double t)
{
  double &time = lazyData().m_time;
  if (time == t) return m_absPlacement;
  if (time != -1) {
    if (!m_parent)
      invalidate();
    else
      findRoot(t)->invalidate();
  }
  double tt = paramsTime(t);
  TAffine place;
  if (m_parent)
    place = m_parent->getPlacement(t) * computeLocalPlacement(tt);
  else
    place = computeLocalPlacement(tt);
  m_absPlacement = place;
  time           = t;
  return place;
}
getPlasticSkeletonDeformation()
PlasticSkeletonDeformationP TStageObject::getPlasticSkeletonDeformation () const
Returns the stored skeleton deformation, if any.
          {
  return m_skeletonDeformation;
}
Referenced by StageBuilder::addCell(), PlasticDeformerFx::doDryCompute(), and PlasticTool::storeDeformation().
getSO()
double TStageObject::getSO (double frame)
Returns the object's stacking order at specified frame.
{
  double tt = paramsTime(t);
  if (m_parent)
    return m_parent->getSO(t) + m_so->getValue(tt);
  else
    return m_so->getValue(tt);
}
References getSO(), and paramsTime().
Referenced by StageBuilder::addFrame(), and getSO().
getSpline()
TStageObjectSpline * TStageObject::getSpline () const
Returns the motion path associated to the object.
{ return m_spline; }
Referenced by TTool::notifyImageChanged(), TColumnDataElement::restoreColumn(), and StageSchematicScene::updateScene().
getStatus()
Status TStageObject::getStatus () const inline
Returns the object's status.
{ return m_status; }
Referenced by Skeleton::isIKEnabled().
getZ()
double TStageObject::getZ (double frame)
Returns the object's depth at specified frame.
See also
Methods getGlobalNoScaleZ() and getNoScaleZ().
{
  double tt = paramsTime(t);
  if (m_parent)
    return m_parent->getZ(t) + m_z->getValue(tt);
  else
    return m_z->getValue(tt);
}
References getZ(), and paramsTime().
Referenced by StageBuilder::addCell(), TXsheet::getBBox(), TTool::getColumnMatrix(), getZ(), and Stage::visit().
hasChildren()
bool TStageObject::hasChildren () const inline
Returns whether the object has children.
{ return !m_children.empty(); }
hasSpecifiedName() [1/2]
bool TStageObject::hasSpecifiedName () inline
{ return m_name != ""; }
hasSpecifiedName() [2/2]
bool TStageObject::hasSpecifiedName () const inline
{ return m_name != ""; }
invalidate()
void TStageObject::invalidate ()
Resets the area position setting internal time of the object and of all his children to -1.
{ invalidate(m_lazyData(tcg::direct_access)); }
References invalidate().
Referenced by assignParams(), detachFromParent(), invalidate(), moveKeyframe(), setCenter(), setHandle(), setNoScaleZ(), setOffset(), setParent(), setParentHandle(), setSpline(), and setStatus().
is52FullKeyframe()
bool TStageObject::is52FullKeyframe (int frame) const
Returns true if frame is a keyframe for all channels with exception of global scale channel.
{
  return m_rot->isKeyframe(frame) && m_x->isKeyframe(frame) &&
         m_y->isKeyframe(frame) && m_z->isKeyframe(frame) &&
         m_posPath->isKeyframe(frame) && m_scalex->isKeyframe(frame) &&
         m_scaley->isKeyframe(frame) && m_shearx->isKeyframe(frame) &&
         m_sheary->isKeyframe(frame);
}
isAimEnabled()
bool TStageObject::isAimEnabled () const inline
helper functions to manipulate status
{
    return (m_status & STATUS_MASK) == PATH_AIM;
  }
isAncestor()
bool TStageObject::isAncestor (TStageObject * stageObject) const
Returns whether stageObject is ancestor of this.
{
  if (!stageObject) return false;
  if (stageObject == (TStageObject *)m_parent)
    return true;
  else if (m_parent == 0)
    return false;
  else
    return m_parent->isAncestor(stageObject);
}
References isAncestor().
Referenced by isAncestor(), and StageSchematicNodePort::linkTo().
isContainedInGroup()
bool TStageObject::isContainedInGroup (int groupId)
{
  return m_groupId.contains(groupId);
}
isCycleEnabled()
bool TStageObject::isCycleEnabled () const
Returns true if the objects cycle is enabled, i.e. if a finite sequence is a cycle.
{ return m_cycleEnabled; }
isFullKeyframe()
bool TStageObject::isFullKeyframe (int frame) const
Returns true if frame is a keyframe for all channels.
{
  return m_rot->isKeyframe(frame) && m_x->isKeyframe(frame) &&
         m_y->isKeyframe(frame) && m_z->isKeyframe(frame) &&
         m_so->isKeyframe(frame) && m_posPath->isKeyframe(frame) &&
         m_scalex->isKeyframe(frame) && m_scaley->isKeyframe(frame) &&
         m_scale->isKeyframe(frame) && m_shearx->isKeyframe(frame) &&
         m_sheary->isKeyframe(frame);
}
isGrouped()
bool TStageObject::isGrouped ()
{ return !m_groupId.isEmpty(); }
isGroupEditing()
bool TStageObject::isGroupEditing ()
{
  return isGrouped() && m_groupSelector == -1;
}
isKeyframe()
bool TStageObject::isKeyframe (int frame) const
Returns true if frame is a keyframe.
See also
TStageObject::Keyframe
{
  const KeyframeMap &keyframes = lazyData().m_keyframes;
  return keyframes.find(frame) != keyframes.end();
}
Referenced by moveKeyframe(), and TCellKeyframeSelection::selectCellsKeyframes().
isLocked()
bool TStageObject::isLocked () const inline
Returns whether the object has been locked (can't move).
{ return m_locked; }
isOpened()
bool TStageObject::isOpened () const inline
Returns whether this object is already in use.
{ return m_isOpened; }
isPathEnabled()
bool TStageObject::isPathEnabled () const inline
{
    return (m_status & STATUS_MASK) == PATH_AIM ||
           (m_status & STATUS_MASK) == PATH;
  }
isUppkEnabled()
bool TStageObject::isUppkEnabled () const inline
{ return (m_status & UPPK_MASK) != 0; }
loadData()
void TStageObject::loadData (TIStream & is)
{
  VersionNumber tnzVersion = is.getVersion();
  string tagName;
  QList<int> groupIds;
  QList<wstring> groupNames;
  KeyframeMap &keyframes = lazyData().m_keyframes;
  while (is.matchTag(tagName)) {
    if (tagName == "parent") {
      string parentIdStr  = is.getTagAttribute("id");
      string handle       = is.getTagAttribute("handle");
      string parentHandle = is.getTagAttribute("parentHandle");
      if (tnzVersion < VersionNumber(1, 15)) {
        handle       = convertTo4InchCenterUnits(handle);
        parentHandle = convertTo4InchCenterUnits(parentHandle);
      }
      if (parentIdStr == "")  // vecchio formato
        is >> parentIdStr;
      else {
      }
      TStageObjectId parentId = toStageObjectId(parentIdStr);
      if (m_id != TStageObjectId::NoneId &&
          parentId != TStageObjectId::NoneId) {
        assert(parentId != m_id);
        setParent(parentId);
      }
      if (handle != "") setHandle(handle);
      if (parentHandle != "") setParentHandle(parentHandle);
    } else if (tagName == "center") {
      is >> m_center.x >> m_center.y >> m_offset.x >> m_offset.y;
      m_offset = -m_offset;
    } else if (tagName == "name")
      is >> m_name;
    else if (tagName == "x")
      is >> *m_x;
    else if (tagName == "y")
      is >> *m_y;
    else if (tagName == "z")
      is >> *m_z;
    else if (tagName == "so")
      is >> *m_so;
    else if (tagName == "rot")
      is >> *m_rot;
    else if (tagName == "sx")
      is >> *m_scalex;
    else if (tagName == "sy")
      is >> *m_scaley;
    else if (tagName == "sc")
      is >> *m_scale;
    else if (tagName == "shx")
      is >> *m_shearx;
    else if (tagName == "shy")
      is >> *m_sheary;
    else if (tagName == "pos")
      is >> *m_posPath;
    else if (tagName == "posCP") {
      TDoubleParam posCP;
      is >> posCP;
    }  // Ghibli 6.2 release. cfr
    else if (tagName == "noScaleZ")
      is >> m_noScaleZ;
    else if (tagName == "isOpened") {
      int v = 0;
      is >> v;
      m_isOpened = (bool)v;
    } else if (tagName == "pinnedStatus") {
      m_pinnedRangeSet->loadData(is);
    } else if (tagName == "status") {
      int v = 0;
      is >> v;
      m_status = (Status)v;
    } else if (tagName == "spline") {
      TStageObjectSpline *spline = m_tree->createSpline();
      is >> *spline;
      m_spline = spline;
      m_spline->addRef();
    } else if (tagName == "splinep") {
      TPersist *p = 0;
      is >> p;
      m_spline = dynamic_cast<TStageObjectSpline *>(p);
      m_tree->insertSpline(m_spline);
      m_spline->addRef();
    } else if (tagName == "cycle") {
      int dummy;
      is >> dummy;
      m_cycleEnabled = true;
    } else if (tagName == "nodePos") {
      TPointD pos;
      is >> pos.x >> pos.y;
      m_dagNodePos = updateDagPosition(pos, tnzVersion);
      // is >> m_dagNodePos.x >> m_dagNodePos.y;
    }
    //***** camera parameters till toonz 6.0 ********
    else if (tagName == "cameraSize") {
      TDimensionD size(0, 0);
      is >> size.lx >> size.ly;
      if (m_camera) m_camera->setSize(size);
    } else if (tagName == "cameraRes") {
      TDimension res(0, 0);
      is >> res.lx >> res.ly;
      if (m_camera) m_camera->setRes(res);
    }
    //***** camera parameters toonz 6.1 ******** november 2009
    else if (tagName == "camera")
      m_camera->loadData(is);
    else if (tagName == "groupIds") {
      int groupId;
      while (!is.eos()) {
        is >> groupId;
        groupIds.push_back(groupId);
      }
    } else if (tagName == "groupNames") {
      wstring groupName;
      while (!is.eos()) {
        is >> groupName;
        groupNames.push_back(groupName);
      }
    } else if (tagName == "plasticSD") {
      PlasticSkeletonDeformation *sd = new PlasticSkeletonDeformation;
      is >> *sd;
      setPlasticSkeletonDeformation(sd);
    } else
      throw TException("TStageObject::loadData. unexpected tag: " + tagName);
    is.matchEndTag();
  }
  if (!groupIds.isEmpty()) {
    assert(groupIds.size() == groupNames.size());
    int i;
    for (i = 0; i < groupIds.size(); i++) {
      setGroupId(groupIds[i]);
      setGroupName(groupNames[i]);
    }
  }
  if (tnzVersion < VersionNumber(1, 13)) {
    updateUnit(m_y.getPointer());
    updateUnit(m_x.getPointer());
  }
  if (tnzVersion < VersionNumber(1, 14)) {
    double factor = 1.0 / Stage::inch;
    m_center      = m_center * factor;
    m_offset      = m_offset * factor;
  }
  if (tnzVersion < VersionNumber(1, 16) && !keyframes.empty()) {
    std::map<int, TStageObject::Keyframe>::iterator itKf = keyframes.begin();
    std::set<int> keyframeIndexSet;
    for (; itKf != keyframes.end(); itKf++)
      if (is52FullKeyframe(itKf->first)) keyframeIndexSet.insert(itKf->first);
    std::set<int>::iterator itKfInd = keyframeIndexSet.begin();
    for (; itKfInd != keyframeIndexSet.end(); itKfInd++)
      setkey(m_scale, *itKfInd);
  }
  // Calling updateKeyframes() here may cause failure to load expressions
  // especially if it refers to a curve which is to be loaded AFTER this
  // function while loading scene process. So I will skip it assuming that
  // updateKeyframes() will be called when it is actually needed.
  // updateKeyframes();
  if (m_spline != 0 && isUppkEnabled())
    m_spline->addParam(m_posPath.getPointer());
  invalidate();
}
lock()
void TStageObject::lock (bool on) inline
Locks the object.
{ m_locked = on; }
moveKeyframe()
bool TStageObject::moveKeyframe (int dst, int src)
Moves Keyframe src to dst. All the Channels associated are copied and the reference to src is deleted. Returns true on success.
{
  assert(dst != src);
  if (isKeyframe(dst) || !isKeyframe(src)) return false;
  setKeyframeWithoutUndo(dst, getKeyframe(src));
  removeKeyframeWithoutUndo(src);
  assert(isKeyframe(dst));
  assert(!isKeyframe(src));
  invalidate();
  return true;
}
References getKeyframe(), invalidate(), and isKeyframe().
moveKeyframes()
bool TStageObject::moveKeyframes (std::set< int > & frames, int delta)
{
  if (!canMoveKeyframes(frames, delta)) return false;
  if (delta < 0) {
    std::set<int>::iterator it;
    for (it = frames.begin(); it != frames.end(); ++it) {
      bool ret = moveKeyframe(*it + delta, *it);
      assert(ret);
    }
  } else {
    std::set<int>::reverse_iterator ti;
    for (ti = frames.rbegin(); ti != frames.rend(); ++ti) {
      bool ret = moveKeyframe(*ti + delta, *ti);
      assert(ret);
    }
  }
  return true;
}
paramsTime()
double TStageObject::paramsTime (double t) const
for param values extraction (dealing with repeat/cycling)
Traduces the xsheet-time into the one suitable
{
  const KeyframeMap &keyframes = lazyData().m_keyframes;
  if (m_cycleEnabled && keyframes.size() > 1) {
    int firstT = keyframes.begin()->first;
    if (t <= firstT) return t;
    int lastT  = keyframes.rbegin()->first;
    int tRange = lastT - firstT + 1;
    assert(tRange > 0);
    int it    = tfloor(t);
    double ft = t - it;
    return firstT + ((it - firstT) % tRange) + ft;
  } else
    return t;
}
Referenced by getSO(), and getZ().
perspective()
bool TStageObject::perspective (TAffine & aff, const TAffine & cameraAff, double cameraZ, const TAffine & objectAff, double objectZ, double objectNoScaleZ) static
Return true if current object is visible, if object position in z-axis is less than 1000; othrwise return false.
Set TAffine aff to current object transformation matrix computed using camera and object transformation matrix, cameraAff, objectAff, and using camera and object position in z-axis, cameraZ, objectZ.
objectZ default value is zero, big value describe the nearest camera object; original distance between table and camera is 1000.
cameraZ default value is zero, negative value suggest that camera is near to the table, camera is in the table for cameraZ = -1000.
{
  TPointD cameraPos(cameraAff.a13, cameraAff.a23);
  TPointD objectPos(objectAff.a13, objectAff.a23);
  const double focus     = 1000;
  const double nearPlane = 1;
  /*--
   * dzfocus(=1000)PegbarZ
   * --*/
  double dz = focus + cameraZ - objectZ;
  if (dz < nearPlane) {
    aff = TAffine();
    return false;
  }
  double noScaleSc = 1 - objectNoScaleZ / focus;
  aff = cameraAff * TScale((focus + cameraZ) / dz) * cameraAff.inv() *
        objectAff * TScale(noScaleSc);
  return true;
}
References TAffine::inv().
Referenced by StageBuilder::addCell(), TXsheet::getBBox(), and TTool::getColumnMatrix().
removeFromAllGroup()
void TStageObject::removeFromAllGroup ()
{
  m_groupId.clear();
  m_groupName.clear();
  m_groupSelector = -1;
}
removeGroupId() [1/2]
int TStageObject::removeGroupId ()
{
  m_groupId.remove(m_groupSelector);
  if (m_groupSelector > -1) m_groupSelector--;
  return m_groupSelector + 1;
}
removeGroupId() [2/2]
void TStageObject::removeGroupId (int position)
{
  if (!isGrouped()) return;
  assert(position >= 0 && position <= m_groupId.size());
  m_groupId.remove(position);
  if (m_groupSelector + 1 >= position && m_groupSelector > -1)
    m_groupSelector--;
}
removeGroupName() [1/2]
int TStageObject::removeGroupName (bool fromEditor)
{
  int groupSelector = fromEditor ? m_groupSelector + 1 : m_groupSelector;
  if (!isGrouped()) return -1;
  assert(groupSelector >= 0 && groupSelector <= m_groupName.size());
  m_groupName.remove(groupSelector);
  return groupSelector;
}
removeGroupName() [2/2]
void TStageObject::removeGroupName (int position = -1)
{
  int groupSelector = position < 0 ? m_groupSelector : position;
  assert(groupSelector >= 0 && groupSelector <= m_groupName.size());
  m_groupName.remove(groupSelector);
}
removeKeyframeWithoutUndo()
void TStageObject::removeKeyframeWithoutUndo (int frame)
{
  KeyframeMap &keyframes = lazyData().m_keyframes;
  double &time           = lazyData().m_time;
  if (!isKeyframe(frame)) return;
  keyframes.erase(frame);
  m_rot->deleteKeyframe(frame);
  m_x->deleteKeyframe(frame);
  m_y->deleteKeyframe(frame);
  m_z->deleteKeyframe(frame);
  m_so->deleteKeyframe(frame);
  m_scalex->deleteKeyframe(frame);
  m_scaley->deleteKeyframe(frame);
  m_scale->deleteKeyframe(frame);
  m_posPath->deleteKeyframe(frame);
  m_shearx->deleteKeyframe(frame);
  m_sheary->deleteKeyframe(frame);
  if (m_skeletonDeformation) m_skeletonDeformation->deleteKeyframe(frame);
  time = -1;
  if ((int)keyframes.size() < 2) m_cycleEnabled = false;
  invalidate();
}
saveData()
void TStageObject::saveData (TOStream & os)
{
  TStageObjectId parentId = getParent();
  std::map<std::string, string> attr;
  attr["id"]           = parentId.toString();
  attr["handle"]       = m_handle;
  attr["parentHandle"] = m_parentHandle;
  os.openChild("parent", attr);
  os.closeChild();
  if (m_name != "") os.child("name") << m_name;
  os.child("isOpened") << (int)m_isOpened;
  if (isGrouped()) {
    os.openChild("groupIds");
    int i;
    for (i = 0; i < m_groupId.size(); i++) os << m_groupId[i];
    os.closeChild();
    os.openChild("groupNames");
    for (i = 0; i < m_groupName.size(); i++) os << m_groupName[i];
    os.closeChild();
  }
  m_pinnedRangeSet->saveData(os);
  os.child("center") << m_center.x << m_center.y << -m_offset.x << -m_offset.y;
  os.child("status") << (int)m_status;
  if (m_noScaleZ != 0) os.child("noScaleZ") << m_noScaleZ;
  if (m_spline) os.child("splinep") << m_spline;
  if (!m_x->isDefault()) os.child("x") << *m_x;
  if (!m_y->isDefault()) os.child("y") << *m_y;
  if (!m_z->isDefault()) os.child("z") << *m_z;
  if (!m_so->isDefault()) os.child("so") << *m_so;
  if (!m_scalex->isDefault()) os.child("sx") << *m_scalex;
  if (!m_scaley->isDefault()) os.child("sy") << *m_scaley;
  if (!m_scale->isDefault()) os.child("sc") << *m_scale;
  if (!m_rot->isDefault()) os.child("rot") << *m_rot;
  if (!m_posPath->isDefault()) os.child("pos") << *m_posPath;
  if (!m_shearx->isDefault()) os.child("shx") << *m_shearx;
  if (!m_sheary->isDefault()) os.child("shy") << *m_sheary;
  if (m_cycleEnabled) os.child("cycle") << 1;
  if (m_skeletonDeformation) os.child("plasticSD") << *m_skeletonDeformation;
  os.child("nodePos") << m_dagNodePos.x << m_dagNodePos.y;
  if (getId().isCamera()) {
    os.openChild("camera");
    m_camera->saveData(os);
    os.closeChild();
    /*TDimensionD size = m_camera->getSize();
TDimension res = m_camera->getRes();
bool isXPrevalence = m_camera->isXPrevalence();
os.child("cameraSize") << size.lx << size.ly;
os.child("cameraRes") << res.lx << res.ly;
os.child("xPrevalence") << (int)isXPrevalence;*/
  }
}
setCenter()
void TStageObject::setCenter (double frame, const TPointD & center)
Sets the center of the frame to center.
{
  TPointD c = center - getHandlePos(m_handle, (int)frame);
  TAffine aff   = computeLocalPlacement(frame);
  TPointD delta = aff * c - aff * m_center;
  m_center      = c;
  m_offset += delta;
  invalidate();
}
References invalidate().
setCenterAndOffset()
void TStageObject::setCenterAndOffset (const TPointD & center, const TPointD & offset)
{
  m_center = center;
  m_offset = offset;
  invalidate();
}
setDagNodePos()
void TStageObject::setDagNodePos (const TPointD & p) inline
Sets the position of the object node object in the widget work area. This function is provided for status saving purpose of the interface that manages the schematic's view.
{ m_dagNodePos = p; }
Referenced by TCameraDataElement::restoreCamera(), TColumnDataElement::restoreColumn(), and TStageObjectDataElement::restoreObject().
setGroupId() [1/2]
int TStageObject::setGroupId (int value)
{
  m_groupSelector++;
  m_groupId.insert(m_groupSelector, value);
  return m_groupSelector;
}
setGroupId() [2/2]
void TStageObject::setGroupId (int value, int position)
{
  assert(position >= 0 && position <= m_groupId.size());
  m_groupId.insert(position, value);
  if (m_groupSelector + 1 >= position) m_groupSelector++;
}
setGroupName()
void TStageObject::setGroupName (const std::wstring & name, int position = -1)
{
  int groupSelector = position < 0 ? m_groupSelector : position;
  assert(groupSelector >= 0 && groupSelector <= m_groupName.size());
  m_groupName.insert(groupSelector, name);
}
setHandle()
void TStageObject::setHandle (const std::string & s)
Sets the name of the pegbar handle name. An empty or an H1,...,H8 string sets the offset to the actual center of the object.
See also
getHandle()
{
  m_handle = s;
  if (!s.empty() && s[0] == 'H') m_offset = m_center = TPointD();
  invalidate();
}
References invalidate().
setId()
void TStageObject::setId (const TStageObjectId & id) inline
Sets the object's id.
{
    if (id != TStageObjectId::NoneId) m_id = id;
  }
setIsOpened()
void TStageObject::setIsOpened (bool value) inline
Sets the usage status of the object.
{ m_isOpened = value; }
Referenced by TColumnDataElement::restoreColumn().
setKeyframeWithoutUndo() [1/2]
void TStageObject::setKeyframeWithoutUndo (int frame)
{
  if (isFullKeyframe(frame)) return;
  setkey(m_x, frame);
  setkey(m_y, frame);
  setkey(m_z, frame);
  setkey(m_so, frame);
  setkey(m_posPath, frame);
  setkey(m_rot, frame);
  setkey(m_scalex, frame);
  setkey(m_scaley, frame);
  setkey(m_scale, frame);
  setkey(m_shearx, frame);
  setkey(m_sheary, frame);
  // Plastic keys are currently not *created* by xsheet commands.
  /*if(m_skeletonDeformation)
{
const PlasticSkeleton* skeleton = m_skeletonDeformation->skeleton();
const tcg::list<PlasticSkeleton::vertex_type>& vertices = skeleton->vertices();
tcg::list<PlasticSkeleton::vertex_type>::const_iterator vt,
vEnd(vertices.end());
for(vt = vertices.begin(); vt != vertices.end(); ++vt)
{
SkVD* vd = m_skeletonDeformation->vertexDeformation(vt->name());
assert(vd);
for(int p=0; p<SkVD::PARAMS_COUNT; ++p)
  setkey(vd->m_params[p], frame);
}
}*/
}
setKeyframeWithoutUndo() [2/2]
void TStageObject::setKeyframeWithoutUndo (int frame, const Keyframe & k)
{
  KeyframeMap &keyframes = lazyData().m_keyframes;
  bool keyWasSet = false;
  keyWasSet = ::setKeyframe(m_rot, k.m_channels[TStageObject::T_Angle], frame,
                            k.m_easeIn, k.m_easeOut) ||
              keyWasSet;
  keyWasSet = ::setKeyframe(m_x, k.m_channels[TStageObject::T_X], frame,
                            k.m_easeIn, k.m_easeOut) ||
              keyWasSet;
  keyWasSet = ::setKeyframe(m_y, k.m_channels[TStageObject::T_Y], frame,
                            k.m_easeIn, k.m_easeOut) ||
              keyWasSet;
  keyWasSet = ::setKeyframe(m_z, k.m_channels[TStageObject::T_Z], frame,
                            k.m_easeIn, k.m_easeOut) ||
              keyWasSet;
  keyWasSet = ::setKeyframe(m_so, k.m_channels[TStageObject::T_SO], frame,
                            k.m_easeIn, k.m_easeOut) ||
              keyWasSet;
  keyWasSet = ::setKeyframe(m_posPath, k.m_channels[TStageObject::T_Path],
                            frame, k.m_easeIn, k.m_easeOut) ||
              keyWasSet;
  keyWasSet = ::setKeyframe(m_scalex, k.m_channels[TStageObject::T_ScaleX],
                            frame, k.m_easeIn, k.m_easeOut) ||
              keyWasSet;
  keyWasSet = ::setKeyframe(m_scaley, k.m_channels[TStageObject::T_ScaleY],
                            frame, k.m_easeIn, k.m_easeOut) ||
              keyWasSet;
  keyWasSet = ::setKeyframe(m_scale, k.m_channels[TStageObject::T_Scale], frame,
                            k.m_easeIn, k.m_easeOut) ||
              keyWasSet;
  keyWasSet = ::setKeyframe(m_shearx, k.m_channels[TStageObject::T_ShearX],
                            frame, k.m_easeIn, k.m_easeOut) ||
              keyWasSet;
  keyWasSet = ::setKeyframe(m_sheary, k.m_channels[TStageObject::T_ShearY],
                            frame, k.m_easeIn, k.m_easeOut) ||
              keyWasSet;
  if (m_skeletonDeformation)
    keyWasSet = m_skeletonDeformation->setKeyframe(k.m_skeletonKeyframe, frame,
                                                   k.m_easeIn, k.m_easeOut) ||
                keyWasSet;
  if (keyWasSet) keyframes[frame] = k;
  invalidate();
}
setName()
void TStageObject::setName (const std::string & name)
{
  m_name = (name == m_id.toString()) ? std::string() : name;
}
setNoScaleZ()
void TStageObject::setNoScaleZ (double noScaleZ)
Returns the depth with no scale factor. Movig along Z axis results in a scale factor on the plane XY. This method sets the original depth of the pegbar.
See also
getGlobalNoScaleZ().
{
  if (m_noScaleZ == noScaleZ) return;
  m_noScaleZ = noScaleZ;
  invalidate();
}
References invalidate().
setOffset()
void TStageObject::setOffset (const TPointD & off)
Sets the offset of the object.
See also
getOffset().
{
  m_offset = off;
  invalidate();
}
References invalidate().
setParam()
void TStageObject::setParam (Channel type, double frame, double val)
Sets the channel type to the value val.
{
  assert(0);
}
setParent()
void TStageObject::setParent (const TStageObjectId & parentId)
Sets the object's parent.
{
  assert(m_tree);
  TStageObject *newParent = 0;
  if (parentId != TStageObjectId::NoneId) {
    newParent = m_tree->getStageObject(parentId);
    assert(newParent);
    // cerco di evitare i cicli
    TStageObject *p = newParent;
    while (p->m_parent) {
      if (p->m_parent->getId() == getId()) return;
      p = p->m_parent;
    }
  } else {
    if (!m_id.isCamera() && !m_id.isTable()) {
      newParent = m_tree->getStageObject(TStageObjectId::TableId);
      assert(newParent);
    }
  }
  if (m_parent) m_parent->m_children.remove(this);
  m_parent = newParent;
  if (m_parent) m_parent->m_children.insert(m_parent->m_children.end(), this);
  invalidate();
#ifndef NDEBUG
  if (m_id.isCamera()) {
  } else if (m_id.isTable()) {
    assert(m_parent == 0);
  } else if (m_id.isColumn()) {
    assert(m_parent &&
           (m_parent->m_id.isTable() || m_parent->m_id.isColumn() ||
            m_parent->m_id.isPegbar() || m_parent->m_id.isCamera()));
  } else if (m_id.isPegbar()) {
    assert(m_parent && (m_parent->m_id.isTable() || m_parent->m_id.isCamera() ||
                        m_parent->m_id.isPegbar()));
  } else {
    assert(0);
  }
#endif
}
References getId(), TStageObjectTree::getStageObject(), invalidate(), TStageObjectId::isCamera(), TStageObjectId::isColumn(), TStageObjectId::isPegbar(), and TStageObjectId::isTable().
Referenced by attachChildrenToParent(), TStageObjectTree::getStageObject(), TStageObjectTree::insertColumn(), and TStageObjectTree::insertStageObject().
setParentHandle()
void TStageObject::setParentHandle (const std::string & s)
Sets the name of the pegbar parent handle name.
{
  m_parentHandle = s;
  invalidate();
}
References invalidate().
setPlasticSkeletonDeformation()
void TStageObject::setPlasticSkeletonDeformation (const PlasticSkeletonDeformationP & sd)
Stores the specified skeleton deformation.
{
  if (m_skeletonDeformation == sd) return;
  if (m_skeletonDeformation) {
    PlasticDeformerStorage::instance()->releaseDeformationData(
        m_skeletonDeformation.getPointer());
    m_skeletonDeformation->setGrammar(0);
    m_skeletonDeformation->removeObserver(this);
  }
  m_skeletonDeformation = sd;
  if (m_skeletonDeformation) {
    m_skeletonDeformation->setGrammar(m_tree->getGrammar());
    m_skeletonDeformation->addObserver(this);
  }
}
References PlasticDeformerStorage::releaseDeformationData().
Referenced by assignParams().
setSpline()
void TStageObject::setSpline (TStageObjectSpline * spline)
Sets the motion path of the object. A null pointer argument make this an object without a path and set the object status to TStageObject::XY, that is it can move on a palne. this gets ownership of spline.
Note
does NOT take spline ownership
{
  doSetSpline(spline);
  TNotifier::instance()->notify(TXsheetChange());
  TNotifier::instance()->notify(TStageChange());
  invalidate();
}
References doSetSpline(), and invalidate().
Referenced by StageSchematicSplinePort::linkTo(), and TColumnDataElement::restoreColumn().
setStatus()
void TStageObject::setStatus (Status status)
Sets the object's status.
{
  if (m_status == status) return;
  bool oldPathEnabled = isPathEnabled();
  bool oldUppkEnabled = isUppkEnabled();
  m_status            = status;
  bool pathEnabled    = isPathEnabled();
  bool uppkEnabled    = isUppkEnabled();
  if (pathEnabled) {
    if (!m_spline)
      doSetSpline(m_tree->createSpline());
    else if (oldUppkEnabled != uppkEnabled) {
      TDoubleParam *param = getParam(T_Path);
      if (uppkEnabled)
        m_spline->addParam(param);
      else
        m_spline->removeParam(param);
    }
  } else {
    doSetSpline(0);
  }
  invalidate();
}
References TStageObjectSpline::addParam(), TStageObjectTree::createSpline(), doSetSpline(), getParam(), invalidate(), and T_Path.
updateKeyframes()
void TStageObject::updateKeyframes ()
Rebuilds the internal keyframes table.
{
  return updateKeyframes(m_lazyData(tcg::direct_access));
}
References updateKeyframes().
Referenced by assignParams(), and updateKeyframes().
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/toonz/tstageobject.h
E:/opentoonz/toonz/sources/toonzlib/tstageobject.cpp