opentoonz: TParamSet Class Reference
TParamSet Class Reference
Public Member Functions
TParamSet (std::string name="")
TParamSet (const TParamSet &src)
void addParam (const TParamP &param, const std::string &name)
void insertParam (const TParamP &param, const std::string &name, int index)
void removeParam (const TParamP &param)
void removeAllParam ()
int getParamCount () const
TParamP getParam (int index) const
std::string getParamName (int index) const
int getParamIdx (const std::string &name) const
void getAnimatableParams (std::vector< TParamP > &params, bool recursive=true)
void addObserver (TParamObserver *observer) override
void removeObserver (TParamObserver *observer) override
void beginParameterChange ()
void endParameterChange ()
void enableDragging (bool on)
void enableNotification (bool on) override
bool isNotificationEnabled () const override
bool isAnimatable () const override
bool isKeyframe (double frame) const override
void deleteKeyframe (double frame) override
void clearKeyframes () override
void assignKeyframe (double frame, const TSmartPointerT< TParam > &src, double srcFrame, bool changedOnly=false) override
void getKeyframes (std::set< double > &frames) const override
int getKeyframeCount () const
double keyframeIndexToFrame (int index) const override
TParam * clone () const override
void copy (TParam *src) override
void loadData (TIStream &) override
void saveData (TOStream &) override
int getNextKeyframe (double frame) const override
int getPrevKeyframe (double frame) const override
bool hasKeyframes () const override
std::string getValueAlias (double frame, int precision) override
Public Member Functions inherited from TParam
TParam (std::string name="", std::string description="", std::string label="")
std::string getName () const
void setName (const std::string &name)
std::string getDescription () const
void setDescription (const std::string &description)
bool hasUILabel () const
void setUILabel (const std::string &l)
std::string getUILabel () const
virtual TParam * clone () const =0
virtual void copy (TParam *src)=0
virtual void addObserver (TParamObserver *)=0
virtual void removeObserver (TParamObserver *)=0
virtual void enableNotification (bool on)
virtual bool isNotificationEnabled () const
virtual std::string getValueAlias (double frame, int precision)=0
virtual bool isAnimatable () const =0
virtual bool isKeyframe (double frame) const =0
virtual void deleteKeyframe (double frame)=0
virtual void clearKeyframes ()=0
virtual void assignKeyframe (double frame, const TSmartPointerT< TParam > &src, double srcFrame, bool changedOnly=false)=0
virtual void getKeyframes (std::set< double > &frames) const
virtual bool hasKeyframes () const
virtual int getNextKeyframe (double frame) const
virtual int getPrevKeyframe (double frame) const
virtual double keyframeIndexToFrame (int index) const
Public Member Functions inherited from TSmartObject
TSmartObject (ClassCode classCode)
void addRef ()
void release ()
TINT32 getRefCount () const
Public Member Functions inherited from TPersist
virtual void loadData (TIStream &is)=0
virtual void saveData (TOStream &os)=0
std::string getStreamTag () const
virtual const TPersistDeclaration * getDeclaration () const =0
Additional Inherited Members
Public Types inherited from TSmartObject
typedef short ClassCode
Public Types inherited from TPersist
typedef TPersist * CreateProc()
Static Public Member Functions inherited from TSmartObject
static TINT32 getInstanceCount (ClassCode code)
Static Public Member Functions inherited from TPersist
static void declare (CreateProc *)
static TPersist * create (const std::string &name)
Detailed Description
Constructor & Destructor Documentation
TParamSet() [1/2]
TParamSet::TParamSet (std::string name = "")
    : TParam(name), m_imp(new TParamSetImp(this)) {}
TParamSet() [2/2]
TParamSet::TParamSet (const TParamSet & src)
    : TParam(src.getName()), m_imp(new TParamSetImp(this)) {}
~TParamSet()
TParamSet::~TParamSet ()
{ delete m_imp; }
Member Function Documentation
addObserver()
void TParamSet::addObserver (TParamObserver *) override virtual
 An observer is a generic class that takes care and manages of canghes
in the parameters. This method must be implemented with a function that add objects to an observer internal list.
Implements TParam.
{
  // TParamSetObserver *obs = dynamic_cast<TParamSetObserver *>(observer);
  // if (obs)
  //  m_imp->m_observers.insert(obs);
  // else
  m_imp->m_paramObservers.insert(observer);
}
addParam()
void TParamSet::addParam (const TParamP & param, const std::string & name)
{
  std::pair<TParam *, std::string> paramToInsert =
      std::make_pair(param.getPointer(), name);
  std::vector<std::pair<TParam *, std::string>>::iterator it =
      std::find(m_imp->m_params.begin(), m_imp->m_params.end(), paramToInsert);
  if (it == m_imp->m_params.end()) {
    param->addRef();
    param->addObserver(m_imp);
    m_imp->m_params.push_back(paramToInsert);
    // TParamSetParamAdded psParamAdded(this, param.getPointer(), name, false);
    if (param->getName().empty()) param->setName(name);
    // m_imp->notify(psParamAdded);
  }
}
assignKeyframe()
void TParamSet::assignKeyframe (double frame, const TSmartPointerT< TParam > & src, double srcFrame, bool changedOnly = false) override virtual
Makes the frame associated to this parameter a keyframe
Implements TParam.
{
  TParamSetP paramSetSrc = src;
  if (!paramSetSrc) return;
  if (getParamCount() != paramSetSrc->getParamCount()) return;
  for (int i = 0; i < getParamCount(); i++)
    getParam(i)->assignKeyframe(frame, paramSetSrc->getParam(i), srcFrame,
                                changedOnly);
}
References TParam::assignKeyframe().
beginParameterChange()
void TParamSet::beginParameterChange ()
{
  //  assert(0);
  // std::set<TParamSetObserver*>::iterator it = m_imp->m_observers.begin();
  // for (;it != m_imp->m_observers.end(); ++it)
  //  (*it)->onBeginChangeBlock(this);
  // assert(!m_imp->m_changeBlock);
  std::vector<TParam *> params;
  /*
MyBackInsertIterator<vector<pair<TParam*, string> > >
myBackInsertIterator(params);
copy(m_imp->m_params.begin(), m_imp->m_params.end(), myIterator);
*/
  std::vector<std::pair<TParam *, std::string>>::iterator it2 =
      m_imp->m_params.begin();
  for (; it2 != m_imp->m_params.end(); ++it2) params.push_back(it2->first);
  // m_imp->m_changeBlock = new ChangeBlock;
};
clearKeyframes()
void TParamSet::clearKeyframes () override virtual
Removes all keyframes from this parameter.
Implements TParam.
{
  for (int i = 0; i < getParamCount(); i++) getParam(i)->clearKeyframes();
}
References TParam::clearKeyframes().
clone()
TParam * TParamSet::clone () const override virtual
 This method must be implemented with a clone function, i.e a function
that make a new copy of the parameter.
Implements TParam.
Reimplemented in TPointParam, TPixelParam, and TRangeParam.
{ return new TParamSet(*this); }
copy()
void TParamSet::copy (TParam * src) override virtual
Performs a copy function of the parameter in an existing object.
Implements TParam.
Reimplemented in TPointParam, TPixelParam, and TRangeParam.
{
  TParamSet *p = dynamic_cast<TParamSet *>(src);
  if (!p) throw TException("invalid source for copy");
  int srcParamCount = p->getParamCount();
  removeAllParam();
  int i;
  for (i = 0; i < srcParamCount; i++) {
    TParamP param = p->getParam(i);
    addParam(param->clone(), param->getName());
  }
}
References TParam::clone(), and TParam::getName().
deleteKeyframe()
void TParamSet::deleteKeyframe (double frame) override virtual
 Removes \e frame from the list of the keyframes associated to this
parameter.
Implements TParam.
{
  for (int i = 0; i < getParamCount(); i++) getParam(i)->deleteKeyframe(frame);
}
References TParam::deleteKeyframe().
enableDragging()
void TParamSet::enableDragging (bool on)
{
  std::vector<std::pair<TParam *, std::string>>::iterator it =
      m_imp->m_params.begin();
  for (; it != m_imp->m_params.end(); ++it) {
    TDoubleParamP dparam(it->first);
    // if (dparam)
    //  dparam->enableDragging(on);
  }
  m_imp->m_draggingEnabled = on;
}
enableNotification()
void TParamSet::enableNotification (bool on) override virtual
 This method is used to sets the status changing notification of the
parameter. i.e the observer must take care of the changes.
Reimplemented from TParam.
{
  //  std::for_each(m_imp->m_params.begin(), m_imp->m_params.end(),
  //  std::bind2nd(DoEnableNotification, on));
  std::vector<std::pair<TParam *, std::string>>::iterator it =
      m_imp->m_params.begin();
  for (; it != m_imp->m_params.end(); ++it) {
    it->first->enableNotification(on);
  }
  m_imp->m_notificationEnabled = on;
}
endParameterChange()
void TParamSet::endParameterChange ()
{
    //  assert(0);
    // assert(m_imp->m_changeBlock);
    /*
TParamSetChange change(this, m_imp->m_changeBlock->m_firstAffectedFrame,
                         m_imp->m_changeBlock->m_lastAffectedFrame,
                         m_imp->m_changeBlock->m_changes, false);
change.m_dragging = m_imp->m_draggingEnabled;
//delete m_imp->m_changeBlock;
//m_imp->m_changeBlock = 0;
//m_imp->notify(change);
//std::set<TParamSetObserver*>::iterator it = m_imp->m_observers.begin();
//for (;it != m_imp->m_observers.end(); ++it)
//  (*it)->onEndChangeBlock(this);
m_imp->notify(change);
*/
};
getAnimatableParams()
void TParamSet::getAnimatableParams (std::vector< TParamP > & params, bool recursive = true)
{
  std::vector<std::pair<TParam *, std::string>>::iterator it =
      m_imp->m_params.begin();
  for (; it != m_imp->m_params.end(); ++it) {
    TParam *param = it->first;
    TDoubleParamP dparam = TParamP(param);
    if (dparam)
      params.push_back(dparam);
    else {
      TParamSetP paramset = TParamP(param);
      if (paramset && recursive)
        paramset->getAnimatableParams(params, recursive);
    }
  }
}
getKeyframeCount()
int TParamSet::getKeyframeCount () const
{
  std::set<double> frames;
  getKeyframes(frames);
  return frames.size();
}
getKeyframes()
void TParamSet::getKeyframes (std::set< double > & frames) const override virtual
 This function must be overridden with a method that returns as a
reference a list of keyframes in the form of a standard list.
Reimplemented from TParam.
{
  for (int i = 0; i < getParamCount(); i++) getParam(i)->getKeyframes(frames);
}
References TParam::getKeyframes().
Referenced by getNextKeyframe(), getPrevKeyframe(), and keyframeIndexToFrame().
getNextKeyframe()
int TParamSet::getNextKeyframe (double frame) const override virtual
 This method must return the index of the keyframe (if any) after the
frame, otherwiswe returns -1.
Reimplemented from TParam.
{
  std::set<double> frames;
  getKeyframes(frames);
  std::set<double>::iterator it = frames.upper_bound(frame);
  if (it == frames.end())
    return -1;
  else
    return std::distance(frames.begin(), it);
}
References getKeyframes().
getParam()
TParamP TParamSet::getParam (int index) const
{
  assert(i >= 0 && i < (int)m_imp->m_params.size());
  return m_imp->m_params[i].first;
}
getParamCount()
int TParamSet::getParamCount () const
{ return m_imp->m_params.size(); }
getParamIdx()
int TParamSet::getParamIdx (const std::string & name) const
{
  int i, paramsCount = m_imp->m_params.size();
  for (i = 0; i < paramsCount; ++i)
    if (m_imp->m_params[i].second == name) break;
  return i;
}
getParamName()
std::string TParamSet::getParamName (int index) const
{
  assert(i >= 0 && i < (int)m_imp->m_params.size());
  return m_imp->m_params[i].second;
}
getPrevKeyframe()
int TParamSet::getPrevKeyframe (double frame) const override virtual
 This method must return the index of the keyframe (if any) before the
frame, otherwiswe returns -1.
Reimplemented from TParam.
{
  std::set<double> frames;
  getKeyframes(frames);
  std::set<double>::iterator it = frames.lower_bound(frame);
  if (it == frames.begin())
    return -1;
  else {
    --it;
    return std::distance(frames.begin(), it);
  }
}
References getKeyframes().
getValueAlias()
std::string TParamSet::getValueAlias (double frame, int precision) override virtual
 This pure virtual method must return a string with the value of the
parameter and the precision needed.
Implements TParam.
{
  std::string alias = "(";
  std::vector<std::pair<TParam *, std::string>>::iterator end =
      m_imp->m_params.begin();
  std::advance(end, m_imp->m_params.size() - 1);
  std::vector<std::pair<TParam *, std::string>>::iterator it =
      m_imp->m_params.begin();
  for (; it != end; ++it)
    alias += it->first->getValueAlias(frame, precision) + ",";
  alias += it->first->getValueAlias(frame, precision);
  alias += ")";
  return alias;
}
hasKeyframes()
bool TParamSet::hasKeyframes () const override virtual
 This method must return true if there are keyframes associated to this
parameter.
Reimplemented from TParam.
{
  for (int i = 0; i < getParamCount(); i++)
    if (getParam(i)->hasKeyframes()) return true;
  return false;
}
References TParam::hasKeyframes().
insertParam()
void TParamSet::insertParam (const TParamP & param, const std::string & name, int index)
{
  std::pair<TParam *, std::string> paramToInsert =
      std::make_pair(param.getPointer(), name);
  std::vector<std::pair<TParam *, std::string>>::iterator it =
      std::find(m_imp->m_params.begin(), m_imp->m_params.end(), paramToInsert);
  if (it == m_imp->m_params.end()) {
    param->addRef();
    param->addObserver(m_imp);
    it = m_imp->m_params.begin();
    int f;
    for (f = 0; f < index; f++) it++;
    m_imp->m_params.insert(it, paramToInsert);
    if (param->getName().empty()) param->setName(name);
  }
}
isAnimatable()
bool TParamSet::isAnimatable () const inline override virtual
Implements TParam.
{ return true; }
isKeyframe()
bool TParamSet::isKeyframe (double frame) const override virtual
It must returns true if the frame is a keyframe.
Implements TParam.
{
  for (int i = 0; i < getParamCount(); i++)
    if (getParam(i)->isKeyframe(frame)) return true;
  return false;
}
References TParam::isKeyframe().
isNotificationEnabled()
bool TParamSet::isNotificationEnabled () const override virtual
 This method must return \e true if the  notification status is
enabled.
Reimplemented from TParam.
{
  return m_imp->m_notificationEnabled;
}
keyframeIndexToFrame()
double TParamSet::keyframeIndexToFrame (int index) const override virtual
 This method must returns a frame given the index \e index. A frame is
a double value representing a frame.
Reimplemented from TParam.
{
  std::set<double> frames;
  getKeyframes(frames);
  assert(0 <= index && index < (int)frames.size());
  std::set<double>::const_iterator it = frames.begin();
  std::advance(it, index);
  return *it;
}
References getKeyframes().
loadData()
void TParamSet::loadData (TIStream & is) override virtual
 This is a pure virtual function and must be overridden with a method
that implements the object loading from a stream (i.e take the object's features from a formatted data stream). For example the TStageObject class use his implementation to take the values of the parameters that characterizes a stage object as name, coordinates, etc... from a file. is is an input file stream
Implements TPersist.
Reimplemented in TPointParam, TPixelParam, and TRangeParam.
{
  std::string tagName;
  is.openChild(tagName);
  while (!is.eos()) {
    std::string paramName;
    is.openChild(paramName);
    TPersist *p = 0;
    is >> p;
    TParam *param = dynamic_cast<TParam *>(p);
    assert(param);
    addParam(param, paramName);
    is.closeChild();
  }
  is.closeChild();
}
References TIStream::closeChild(), TIStream::eos(), and TIStream::openChild().
removeAllParam()
void TParamSet::removeAllParam ()
{
  while (!m_imp->m_params.empty()) {
    std::vector<std::pair<TParam *, std::string>>::iterator it =
        m_imp->m_params.begin();
    TParam *param = it->first;
    param->removeObserver(m_imp);
    param->release();
    m_imp->m_params.erase(it);
  }
}
removeObserver()
void TParamSet::removeObserver (TParamObserver *) override virtual
Removes this from the observer.
See also
addObserver()
Implements TParam.
{
  // TParamSetObserver *obs = dynamic_cast<TParamSetObserver *>(observer);
  // if (obs)
  //  m_imp->m_observers.erase(obs);
  // else
  m_imp->m_paramObservers.erase(observer);
}
removeParam()
void TParamSet::removeParam (const TParamP & param)
{
  std::vector<std::pair<TParam *, std::string>>::iterator it = std::find_if(
      m_imp->m_params.begin(), m_imp->m_params.end(), matchesParam(param));
  if (it != m_imp->m_params.end()) {
    param->removeObserver(m_imp);
    // TParamSetParamRemoved psParamRemoved(this, param.getPointer(),
    // it->second, false);
    // m_imp->notify(psParamRemoved);
    param->release();
    m_imp->m_params.erase(it);
  }
}
saveData()
void TParamSet::saveData (TOStream & os) override virtual
 This is a pure virtual function and must be overridden with a method
that implements the object saving to a data stream (i.e put the object's features on a formatted data stream). For example the TStageObject class use his implementation to save the values of the parameters that characterizes a stage object as name, coordinates, etc... on a file os is an output file stream.
Implements TPersist.
Reimplemented in TPointParam, TPixelParam, and TRangeParam.
{
  os.openChild(getName());
  std::vector<std::pair<TParam *, std::string>>::iterator it =
      m_imp->m_params.begin();
  std::vector<std::pair<TParam *, std::string>>::iterator end =
      m_imp->m_params.end();
  while (it != end) {
    os.openChild(it->second);
    // it->first->saveData(os);
    os << it->first;
    os.closeChild();
    ++it;
  }
  os.closeChild();
}
References TOStream::closeChild(), TParam::getName(), and TOStream::openChild().
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/tparamset.h
E:/opentoonz/toonz/sources/common/tparam/tparamset.cpp