opentoonz: TStrokeParamDeformation Class Reference
TStrokeParamDeformation Class Reference final
#include <tstrokedeformations.h>
Public Member Functions
TStrokeParamDeformation (const TStroke *stroke, double parameterOfNearest, double lengthOfDeformation=100)
TStrokeParamDeformation (const TStroke *stroke, const TPointD &vect, double parameterOfNearest, double lengthOfDeformation=100)
TThickPoint getDisplacement (const TStroke &, double) const override
TThickPoint getDisplacementForControlPoint (const TStroke &stroke, UINT n) const override
TThickPoint getDisplacementForControlPointLen (const TStroke &stroke, double cpLen) const override
double getDelta (const TStroke &, double) const override
double getMaxDiff () const override
virtual TThickPoint getDisplacement (const TStroke &stroke, double w) const =0
virtual TThickPoint getDisplacementForControlPoint (const TStroke &stroke, UINT n) const =0
virtual TThickPoint getDisplacementForControlPointLen (const TStroke &stroke, double cpLen) const =0
virtual double getDelta (const TStroke &stroke, double w) const =0
virtual double getMaxDiff () const =0
Detailed Description
Manage deformation of a stroke using a gaussian potential.
Function is b*exp(-((x-a)^2)/c).
Constructor & Destructor Documentation
TStrokeParamDeformation() [1/2]
TStrokeParamDeformation::TStrokeParamDeformation (const TStroke * stroke, double parameterOfNearest, double lengthOfDeformation = 100)
    : m_pRef(ref), m_startParameter(s), m_lengthOfDeformation(l), m_vect(0) {
  assert(m_lengthOfDeformation >= 0);
  if (isAlmostZero(m_lengthOfDeformation))
    m_lengthOfDeformation = TConsts::epsilon;
}
TStrokeParamDeformation() [2/2]
TStrokeParamDeformation::TStrokeParamDeformation (const TStroke * stroke, const TPointD & vect, double parameterOfNearest, double lengthOfDeformation = 100)
Use this constructor with movePoints.
    : m_pRef(ref)
    , m_startParameter(s)
    , m_lengthOfDeformation(l)
    , m_vect(new TPointD(vect)) {
  assert(m_lengthOfDeformation >= 0);
  if (isAlmostZero(m_lengthOfDeformation))
    m_lengthOfDeformation = TConsts::epsilon;
}
~TStrokeParamDeformation()
TStrokeParamDeformation::~TStrokeParamDeformation () virtual
{ delete m_vect; }
Member Function Documentation
getDelta()
double TStrokeParamDeformation::getDelta (const TStroke & stroke, double w) const override virtual
| d getDisplacement() / dw |
stroke to test
w stroke parameter
\ret | d getDisplacement() / dw |
Implements TStrokeDeformation.
{
  // potenziale exp^(-x^2) limitato tra
  // [-c_maxLengthOfGaussian,c_maxLengthOfGaussian]
  double diff = stroke.getLength(w);
  diff = diff - m_startParameter;
  if (fabs(diff) <= m_lengthOfDeformation) {
    // modulo il vettore spostamento in funzione  del potenziale
    //  il termine (1.0/m_lengthOfDeformation) * 3 scala
    //  il punto in diff su un sistema di coordinate
    //  normalizzato, associato con la curva exp^(-x^2)
    diff *= (1.0 / m_lengthOfDeformation) * c_maxLengthOfGaussian;
    return derivateOfGaussianPotential(diff);
  }
  return 0;
}
References TStroke::getLength().
getDisplacement()
TThickPoint TStrokeParamDeformation::getDisplacement (const TStroke & stroke, double w) const override virtual
return displacement to use with function increaseControlPoints
stroke to test
w stroke parameter
\ret displacement to apply to obtain deformation
See also
increaseControlPoints
Implements TStrokeDeformation.
{
  // potenziale exp^(-x^2) limitato tra
  // [-c_maxLengthOfGaussian,c_maxLengthOfGaussian]
  double diff = stroke.getLength(w);
  diff = diff - m_startParameter;
  if (fabs(diff) <= m_lengthOfDeformation) {
    // modulo il vettore spostamento in funzione  del potenziale
    //  il termine (1.0/m_lengthOfDeformation) * 3 scala
    //  il punto in diff su un sistema di coordinate
    //  normalizzato, associato con la curva exp^(-x^2)
    diff *= (1.0 / m_lengthOfDeformation) * c_maxLengthOfGaussian;
    if (m_vect)
      return gaussianPotential(diff) * TThickPoint(*m_vect, 0);
    else {
      double outVal = gaussianPotential(diff);
      return TThickPoint(outVal, outVal, 0);
    }
  }
  return TThickPoint();
}
References TStroke::getLength().
getDisplacementForControlPoint()
TThickPoint TStrokeParamDeformation::getDisplacementForControlPoint (const TStroke & stroke, UINT n) const override virtual
return displacement to use with function modifyControlPoints
stroke to test
n control point to get
\ret displacement to apply to obtain deformation
See also
modifyControlPoints
Implements TStrokeDeformation.
{
  // potenziale exp^(-x^2) limitato tra
  // [-c_maxLengthOfGaussian,c_maxLengthOfGaussian]
  double diff = stroke.getLengthAtControlPoint(n);
  diff = diff - m_startParameter;
  if (fabs(diff) <= m_lengthOfDeformation) {
    // modulo il vettore spostamento in funzione  del potenziale
    //  il termine (1.0/m_lengthOfDeformation) * 3 scala
    //  il punto in diff su un sistema di coordinate
    //  normalizzato, associato con la curva exp^(-x^2)
    diff *= (1.0 / m_lengthOfDeformation) * c_maxLengthOfGaussian;
    if (m_vect)
      return gaussianPotential(diff) * TThickPoint(*m_vect, 0);
    else {
      double outVal = gaussianPotential(diff);
      return TThickPoint(outVal, outVal, 0);
    }
  }
  return TThickPoint();
}
References TStroke::getLengthAtControlPoint().
getDisplacementForControlPointLen()
TThickPoint TStrokeParamDeformation::getDisplacementForControlPointLen (const TStroke & stroke, double cpLen) const override virtual
Implements TStrokeDeformation.
{
  // potenziale exp^(-x^2) limitato tra
  // [-c_maxLengthOfGaussian,c_maxLengthOfGaussian]
  // double  diff =  stroke.getLengthAtControlPoint(n);
  // double  diff =  cpLen;
  double diff = cpLenDiff;
  if (fabs(diff) <= m_lengthOfDeformation) {
    // modulo il vettore spostamento in funzione  del potenziale
    //  il termine (1.0/m_lengthOfDeformation) * 3 scala
    //  il punto in diff su un sistema di coordinate
    //  normalizzato, associato con la curva exp^(-x^2)
    diff *= (1.0 / m_lengthOfDeformation) * c_maxLengthOfGaussian;
    if (m_vect)
      return gaussianPotential(diff) * TThickPoint(*m_vect, 0);
    else {
      double outVal = gaussianPotential(diff);
      return TThickPoint(outVal, outVal, 0);
    }
  }
  return TThickPoint();
}
getMaxDiff()
double TStrokeParamDeformation::getMaxDiff () const override virtual
Max diff of delta (This value indicates when it's necessary to insert control point) \ret max displacement permitted
Implements TStrokeDeformation.
{ return 0.09; }
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/tstrokedeformations.h
E:/opentoonz/toonz/sources/common/tvrender/tstrokedeformations.cpp