opentoonz: OverwriteDialog Class Reference
OverwriteDialog Class Reference final
#include <overwritepopup.h>
Public Types
enum Resolution {
CANCELED = 0x0 , KEEP_OLD = 0x1 , OVERWRITE = 0x2 , RENAME = 0x4 ,
ALL_RESOLUTIONS = KEEP_OLD | OVERWRITE | RENAME
}
enum Flags { NO_FLAG = 0x0 , APPLY_TO_ALL_FLAG = 0x1 }
Public Types inherited from DVGui::ValidatedChoiceDialog
enum Options { NO_OPTIONS = 0x0 , APPLY_TO_ALL }
Construction options.
enum DefaultResolution { NO_REQUIRED_RESOLUTION , CANCEL = 1 , DEFAULT_RESOLUTIONS_COUNT }
Basic resolutions supported by the dialog.
Public Member Functions
bool cancelPressed () const
Resolution execute (TFilePath &filePath, const ExistsFunc &exists, Resolution acceptedRes=ALL_RESOLUTIONS, Flags flags=NO_FLAG)
Resolution getChoice () const
Returns the resolution type chosen by the user.
std::wstring getSuffix ()
void reset ()
Resets state variables.
std::wstring execute (ToonzScene *scene, const TFilePath &levelPath, bool multiLoad)
Public Member Functions inherited from DVGui::ValidatedChoiceDialog
ValidatedChoiceDialog (QWidget *parent, Options opts=NO_OPTIONS)
int execute (void *obj)
virtual void reset ()
Public Member Functions inherited from DVGui::Dialog
Dialog (QWidget *parent=0, bool hasButton=false, bool hasFixedSize=true, const QString &name=QString())
void beginVLayout ()
void endVLayout ()
void beginHLayout ()
void endHLayout ()
void addWidget (QWidget *widget, bool isRight=true)
void addWidgets (QWidget *firstW, QWidget *secondW)
void addWidget (QString labelName, QWidget *widget)
void addLayout (QLayout *layout, bool isRight=true)
void addWidgetLayout (QWidget *widget, QLayout *layout)
void addLayout (QString labelName, QLayout *layout)
void addLayouts (QLayout *firstL, QLayout *secondL)
void addSpacing (int spacing)
void addSeparator (QString name=QString())
void setAlignment (Qt::Alignment alignment)
void setTopMargin (int margin)
void setTopSpacing (int spacing)
void setLabelWidth (int labelWidth)
int getLabelWidth () const
void setLayoutInsertedSpacing (int spacing)
int getLayoutInsertedSpacing ()
void setButtonBarMargin (int margin)
void setButtonBarSpacing (int spacing)
void addButtonBarWidget (QWidget *widget)
void addButtonBarWidget (QWidget *first, QWidget *second)
void addButtonBarWidget (QWidget *first, QWidget *second, QWidget *third)
void addButtonBarWidget (QWidget *first, QWidget *second, QWidget *third, QWidget *fourth)
void hideEvent (QHideEvent *event) override
void clearButtonBar ()
Protected Slots
void applyToAll ()
void cancel ()
void onButtonClicked (int)
Additional Inherited Members
Signals inherited from DVGui::Dialog
void dialogClosed ()
Public Attributes inherited from DVGui::Dialog
QVBoxLayout * m_topLayout
QFrame * m_mainFrame
QFrame * m_buttonFrame
QHBoxLayout * m_mainHLayout
bool m_isMainHLayout
QVBoxLayout * m_leftVLayout
QVBoxLayout * m_rightVLayout
bool m_isMainVLayout
int m_layoutSpacing
int m_layoutMargin
int m_labelWidth
std::vector< QWidget * > m_buttonBarWidgets
Protected Member Functions inherited from DVGui::ValidatedChoiceDialog
virtual QString acceptResolution (void *obj, int resolution, bool applyToAll)=0
Attempts enforcement of the selected resolution.
virtual void initializeUserInteraction (const void *obj)
bool appliedToAll () const
Returns whether the "Apply To All" button has been hit.
int appliedToAllResolution () const
Protected Member Functions inherited from DVGui::Dialog
void resizeEvent (QResizeEvent *e) override
Protected Attributes inherited from DVGui::ValidatedChoiceDialog
QButtonGroup * m_buttonGroup
Protected Attributes inherited from DVGui::Dialog
QHBoxLayout * m_buttonLayout
QList< QLabel * > m_labelList
Detailed Description
This dialog offers a standard 'overwrite file' resolution Dialog.
Sometimes, the system attempts to write to the file path of an already existing file. This dialog presents a standard interface to let users choose the conflict resolution manually.
There are 3 possible resolution choices:
Overwrite the existing file
Keep the existing file (aborting the write operation)
Rename the file to write adding a suffix
Additionally, the dialog could be \t CANCELED, either by closing it or pressing the "Cancel" button.
Member Enumeration Documentation
Flags
enum OverwriteDialog::Flags
{ NO_FLAG = 0x0, APPLY_TO_ALL_FLAG = 0x1 };
Resolution
enum OverwriteDialog::Resolution
                  {
    CANCELED        = 0x0,
    KEEP_OLD        = 0x1,
    OVERWRITE       = 0x2,
    RENAME          = 0x4,
    ALL_RESOLUTIONS = KEEP_OLD | OVERWRITE | RENAME
  };
Constructor & Destructor Documentation
OverwriteDialog()
OverwriteDialog::OverwriteDialog ()
    : DVGui::Dialog(TApp::instance()->getMainWindow(), true) {
  setModal(true);
  setWindowTitle(tr("Warning!"));
  QButtonGroup *buttonGroup = new QButtonGroup(this);
  buttonGroup->setExclusive(true);
  bool ret = connect(buttonGroup, SIGNAL(buttonClicked(int)), this,
                     SLOT(onButtonClicked(int)));
  beginVLayout();
  m_label = new QLabel(this);
  addWidget(m_label);
  m_keep = new QRadioButton(tr("Keep existing file"), this);
  buttonGroup->addButton(m_keep);
  addWidget(m_keep);
  m_overwrite = new QRadioButton(
      tr("Overwrite the existing file with the new one"), this);
  buttonGroup->addButton(m_overwrite);
  addWidget(m_overwrite);
  m_rename =
      new QRadioButton(tr("Rename the new file adding the suffix"), this);
  buttonGroup->addButton(m_rename);
  m_suffix = new DVGui::LineEdit("_1", this);
  m_suffix->setFixedWidth(25);
  m_suffix->setEnabled(false);
  QHBoxLayout *boxLayout = new QHBoxLayout();
  boxLayout->setMargin(0);
  boxLayout->setSpacing(0);
  boxLayout->addWidget(m_rename);
  boxLayout->addWidget(m_suffix);
  boxLayout->setAlignment(m_rename, Qt::AlignLeft);
  boxLayout->setAlignment(m_suffix, Qt::AlignLeft);
  addLayout(boxLayout);
  endVLayout();
  m_okBtn = new QPushButton(QString(tr("Apply")), this);
  ret     = ret && connect(m_okBtn, SIGNAL(clicked()), this, SLOT(accept()));
  addButtonBarWidget(m_okBtn);
  m_okToAllBtn = new QPushButton(QString(tr("Apply to All")), this);
  ret =
      ret && connect(m_okToAllBtn, SIGNAL(clicked()), this, SLOT(applyToAll()));
  addButtonBarWidget(m_okToAllBtn);
  m_cancelBtn = new QPushButton(QString(tr("Cancel")), this);
  ret = ret && connect(m_cancelBtn, SIGNAL(clicked()), this, SLOT(cancel()));
  addButtonBarWidget(m_cancelBtn);
  assert(ret);
  reset();
  m_keep->setChecked(true);
}
Member Function Documentation
applyToAll
void OverwriteDialog::applyToAll () protected slot
{
  m_applyToAll = true;
  accept();
}
cancel
void OverwriteDialog::cancel () protected slot
{
  m_cancelPressed = true;
  reject();
}
cancelPressed()
bool OverwriteDialog::cancelPressed () const inline
{ return m_cancelPressed; }
execute()
std::wstring OverwriteDialog::execute (ToonzScene * scene, const TFilePath & levelPath, bool multiLoad)
this method has to be called for each filepath to be imported. Only if necessary, it opens a popup. put parameter multiLoad to true only if you are importing more then one level (so that the button 'apply to all' appears in the dialog)
getChoice()
Resolution OverwriteDialog::getChoice () const inline
Returns the resolution type chosen by the user.
{ return m_choice; }
getSuffix()
std::wstring OverwriteDialog::getSuffix ()
Returns the suffix to be added at the base file name when the chosen resolution type is \t KEEP_OLD.
{
  return m_suffix->text().toStdWString();
}
References getSuffix().
Referenced by getSuffix().
onButtonClicked
void OverwriteDialog::onButtonClicked (int) protected slot
{
  m_suffix->setEnabled(m_rename->isChecked());
}
reset()
void OverwriteDialog::reset () virtual
Resets state variables.
Reimplemented from DVGui::ValidatedChoiceDialog.
{
  m_choice        = KEEP_OLD;
  m_applyToAll    = false;
  m_cancelPressed = false;
}
References reset().
Referenced by reset().
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/toonz/overwritepopup.h
E:/opentoonz/toonz/sources/toonz/overwritepopup.cpp