opentoonz: TCameraDataElement Class Reference
TCameraDataElement Class Reference final
Public Member Functions
TCameraDataElement * clone () const override
void storeCamera (const TStageObjectId &selectedObj, TXsheet *xsh)
Stores the specified camera object.
TStageObjectId restoreCamera (TXsheet *xsh, bool copyPosition) const
Restores the stored camera object.
Public Member Functions inherited from TStageObjectDataElement
virtual TStageObjectDataElement * clone () const
void storeObject (const TStageObjectId &objectId, TXsheet *xsh)
TStageObjectId restoreObject (TXsheet *xsh, bool copyPosition) const
Additional Inherited Members
Protected Attributes inherited from TStageObjectDataElement
TStageObjectParams * m_params
Stage object parameters (owned)
TPointD m_dagPos
Stage object position in the viewer.
Detailed Description
Class used to clone a camera stage object's relational data inside the stage schematic.
Constructor & Destructor Documentation
TCameraDataElement()
TCameraDataElement::TCameraDataElement ()
: TStageObjectDataElement() {}
~TCameraDataElement()
TCameraDataElement::~TCameraDataElement ()
{}
Member Function Documentation
clone()
TCameraDataElement * TCameraDataElement::clone () const override virtual
Reimplemented from TStageObjectDataElement.
{
  TCameraDataElement *data = new TCameraDataElement();
  data->m_params = m_params->clone();
  data->m_camera = m_camera;
  data->m_dagPos = m_dagPos;
  return data;
}
restoreCamera()
TStageObjectId TCameraDataElement::restoreCamera (TXsheet * xsh, bool copyPosition) const
Restores the stored camera object.
{
  // Create the new camera object
  TStageObjectTree *tree = xsh->getStageObjectTree();
  // first, try to maintain object id if it is available
  int index = m_params->m_id.getIndex();
  TStageObject *newCamera =
      tree->getStageObject(TStageObjectId::CameraId(index), false);
  if (!newCamera)
    newCamera = tree->getStageObject(TStageObjectId::CameraId(index), true);
  // if the original id is occupied, then use the first unused id
  else {
    // Search the first unused camera id in the xsheet
    index = 0;
    while (tree->getStageObject(TStageObjectId::CameraId(index), false))
      ++index;
    newCamera = tree->getStageObject(TStageObjectId::CameraId(index), true);
  }
  // assign stored data
  newCamera->assignParams(m_params);
  *(newCamera->getCamera()) = m_camera;
  if (copyPosition) newCamera->setDagNodePos(m_dagPos);
  return newCamera->getId();
}
References TStageObject::assignParams(), TStageObject::getCamera(), TStageObject::getId(), TStageObjectTree::getStageObject(), TXsheet::getStageObjectTree(), TStageObjectDataElement::m_dagPos, TStageObjectDataElement::m_params, and TStageObject::setDagNodePos().
storeCamera()
void TCameraDataElement::storeCamera (const TStageObjectId & selectedObj, TXsheet * xsh)
Stores the specified camera object.
{
  TStageObject *obj =
      xsh->getStageObjectTree()->getStageObject(selectedObj, false);
  assert(obj);
  m_params = obj->getParams();
  m_camera = *(obj->getCamera());
  m_dagPos = obj->getDagNodePos();
}
References TStageObject::getCamera(), TStageObject::getDagNodePos(), TStageObject::getParams(), TStageObjectTree::getStageObject(), TXsheet::getStageObjectTree(), TStageObjectDataElement::m_dagPos, and TStageObjectDataElement::m_params.
Referenced by StageObjectsData::storeObjects().
The documentation for this class was generated from the following file:
E:/opentoonz/toonz/sources/toonzqt/stageobjectsdata.cpp