opentoonz: ToonzExt::StraightCornerDeformation Class Reference
ToonzExt::StraightCornerDeformation Class Reference final
Public Member Functions
bool check_ (const ContextStatus *status) override
bool findExtremes_ (const ContextStatus *, Interval &) override
void draw (Designer *) override
double findActionLength () override
Public Member Functions inherited from ToonzExt::StrokeDeformationImpl
ToonzExt::Interval getExtremes ()
const TStroke * getStrokeSelected () const
const TStroke * getCopiedStroke () const
virtual bool activate_impl (const ContextStatus *)
virtual void update_impl (const TPointD &delta)
virtual TStroke * deactivate_impl ()
bool check (const ContextStatus *)
virtual void reset ()
void setPotential (Potential *)
virtual void draw (Designer *)
TStroke * getTransformedStroke ()
ToonzExt::Potential * getPotential ()
TPointD & oldW0 ()
int getShortcutKey () const
int getCursorId () const
void setCursorId (int id)
Static Public Member Functions
static StraightCornerDeformation * instance ()
Static Public Member Functions inherited from ToonzExt::StrokeDeformationImpl
static const ContextStatus *& getImplStatus ()
Additional Inherited Members
virtual bool check_ (const ContextStatus *)=0
virtual bool findExtremes_ (const ContextStatus *, Interval &)=0
virtual double findActionLength ()=0
Static Protected Member Functions inherited from ToonzExt::StrokeDeformationImpl
static TStroke *& getLastSelectedStroke ()
static void setLastSelectedStroke (TStroke *)
static int & getLastSelectedDegree ()
static void setLastSelectedDegree (int degree)
static ToonzExt::Intervals & getSpiresList ()
static ToonzExt::Intervals & getStraightsList ()
Protected Attributes inherited from ToonzExt::StrokeDeformationImpl
TStroke * stroke2manipulate_
ToonzExt::StrokeParametricDeformer * deformer_
int shortcutKey_
double old_w0_
TPointD old_w0_pos_
std::vector< TStroke * > strokes_
Detailed Description
Constructor & Destructor Documentation
~StraightCornerDeformation()
StraightCornerDeformation::~StraightCornerDeformation () virtual
{}
Member Function Documentation
check_()
bool StraightCornerDeformation::check_ (const ContextStatus *) override virtual
Is this the correct deformation?
Implements ToonzExt::StrokeDeformationImpl.
{
  assert(status && "Not status available");
  TStroke *s = status->stroke2change_;
  double w   = status->w_;
  // check extremes in another way.
  if ((!s->isSelfLoop() && areAlmostEqual(w, 0.0)) || areAlmostEqual(w, 1.0)) {
    return isAStraightCorner(s, w, &this->getStraightsList());
  }
  ToonzExt::Interval ret;
  if (ToonzExt::findNearestStraightCorners(status->stroke2change_, status->w_,
                                           ret, &this->getStraightsList()) &&
      isAStraightCorner(s, w, &this->getStraightsList())) {
    if (ret.first > ret.second) {
      assert(s->isSelfLoop());
      if ((ret.first < w && w <= 1.0) || (0.0 <= w && w < ret.second))
        return true;
    } else {
      if (ret.first < w && w < ret.second) return true;
    }
  }
  return false;
}
References ToonzExt::findNearestStraightCorners(), and TStroke::isSelfLoop().
draw()
void StraightCornerDeformation::draw (Designer * designer) override virtual
Apply a designer on current deformation.
Reimplemented from ToonzExt::StrokeDeformationImpl.
{
  StrokeDeformationImpl::draw(0);
  designer->draw(this);
}
References ToonzExt::StrokeDeformationImpl::draw().
findActionLength()
double StraightCornerDeformation::findActionLength () override virtual
Implements ToonzExt::StrokeDeformationImpl.
{
  return stroke2manipulate_->getLength();
}
findExtremes_()
bool StraightCornerDeformation::findExtremes_ (const ContextStatus * , Interval &) override virtual
Retrieve the nearest extremes to point selected.
Implements ToonzExt::StrokeDeformationImpl.
{
  bool found = ToonzExt::findNearestStraightCorners(
      status->stroke2change_, status->w_, ret, &this->getStraightsList());
  // it is not a forced solution
  if ((status->key_event_ != shortcutKey_) && found)
    return found;
  else {
    // it is forced then probably i want to find
    found = ToonzExt::findNearestSpireCorners(
        status->stroke2change_, status->w_, ret, status->cornerSize_,
        &this->getSpiresList());
  }
  return found;
}
References ToonzExt::findNearestSpireCorners(), and ToonzExt::findNearestStraightCorners().
instance()
StraightCornerDeformation * StraightCornerDeformation::instance () static
{
  static StraightCornerDeformation singleton;
  return &singleton;
}
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/ext/StraightCornerDeformation.h
E:/opentoonz/toonz/sources/tnzext/StraightCornerDeformation.cpp