opentoonz: SchematicPort Class Reference
SchematicPort Class Reference abstract
#include <schematicnode.h>
Signals
void isClicked ()
void isReleased (const QPointF &)
void sceneChanged ()
void xsheetChanged ()
Public Member Functions
SchematicPort (QGraphicsItem *parent, SchematicNode *node, int type)
SchematicNode * getNode () const
QRectF boundingRect () const override
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=0) override
void addLink (SchematicLink *link)
Add the link to the links container.
int getLinkCount () const
void removeLink (SchematicLink *link)
void eraseLink (SchematicLink *link)
Removes link from the scene and the m_links list; delete it .
void eraseAllLinks ()
Removes all links from the scene and the m_links list; delete them .
SchematicLink * getLink (int index) const
SchematicNode * getLinkedNode (int index) const
Returns the node linked with the link index.
virtual SchematicLink * makeLink (SchematicPort *port)
Make a link from this port to the given port.
virtual bool linkTo (SchematicPort *port, bool checkOnly=false)=0
QPointF getHook () const
bool isLinkedTo (SchematicPort *port) const
void highLight (bool value)
bool isHighlighted () const
void updateLinksGeometry ()
Updates all links of the ports.
QPointF getLinkEndPoint () const
Returns the scene position of the link end.
int getType () const
void setType (int type)
Set the type of the port.
Protected Member Functions
void mouseMoveEvent (QGraphicsSceneMouseEvent *me) override
void mousePressEvent (QGraphicsSceneMouseEvent *me) override
void mouseReleaseEvent (QGraphicsSceneMouseEvent *me) override
Protected Attributes
Qt::MouseButton m_buttonState
SchematicNode * m_node
QPointF m_hook
bool m_highlighted
QList< SchematicLink * > m_ghostLinks
SchematicPort * m_linkingTo
QList< SchematicLink * > m_links
int m_type
Detailed Description
  \brief The class provides method to draw and andle a SchematicPort.
  A SchematicPort is a child af a SchematicNode and is used to link a
parent node to other nodes. It can be an input port, or better , a port used to accept link coming from other node. A port that isn't an input port cannot accept links but can begin to draw links.
A SchematicPort has got a hook thet is a position where links starts or ends.
A SchematicPort can be linked to an arbitrary number of links. A SchematicPort handles a container of all links to retrieve all linked node; each link is indexed using a progressive number assigned when the link is inserted to the container.
See also
SchematicNode, SchematicLink.
Constructor & Destructor Documentation
SchematicPort()
SchematicPort::SchematicPort (QGraphicsItem * parent, SchematicNode * node, int type)
    : QGraphicsItem(parent)
    , m_node(node)
    , m_buttonState(Qt::NoButton)
    , m_highlighted(false)
    , m_linkingTo(0)
    , m_hook(0, 0)
    , m_type(type) {
#if QT_VERSION >= 0x050000
  setAcceptHoverEvents(false);
#else
  setAcceptsHoverEvents(false);
#endif
  setFlag(QGraphicsItem::ItemIsSelectable, false);
  setFlag(QGraphicsItem::ItemIsFocusable, false);
}
~SchematicPort()
SchematicPort::~SchematicPort ()
{ m_links.clear(); }
Member Function Documentation
addLink()
void SchematicPort::addLink (SchematicLink * link) inline
Add the link to the links container.
{ m_links.push_back(link); }
Referenced by makeLink(), and FxSchematicPort::makeLink().
boundingRect()
QRectF SchematicPort::boundingRect () const inline override
{ return QRectF(0, 0, 1, 1); };
eraseAllLinks()
void SchematicPort::eraseAllLinks ()
Removes all links from the scene and the m_links list; delete them .
{
  while (!m_links.empty()) eraseLink(m_links[0]);
}
References eraseLink().
eraseLink()
void SchematicPort::eraseLink (SchematicLink * link)
Removes link from the scene and the m_links list; delete it .
{
  SchematicPort *otherPort = link->getOtherPort(this);
  if (otherPort) otherPort->removeLink(link);
  removeLink(link);
  if (link->scene()) link->scene()->removeItem(link);
  delete link;
}
References SchematicLink::getOtherPort(), and removeLink().
Referenced by eraseAllLinks().
getHook()
QPointF SchematicPort::getHook () const inline
{ return m_hook; }
getLink()
SchematicLink * SchematicPort::getLink (int index) const inline
Returns the link indexed with index.
Note
A link is indexed with a progressive number when is inserted in the container.
{
    return (index < m_links.size() && index >= 0) ? m_links[index] : 0;
  }
Referenced by FxSchematicScene::simulateDisconnectSelection(), and updateLinksGeometry().
getLinkCount()
int SchematicPort::getLinkCount () const inline
Returns the number of the link contained in the links container or, it is the same, the number of nodes linked to this SchematicPort
{ return m_links.size(); }
Referenced by SchematicNode::getLinkedNodes(), and updateLinksGeometry().
getLinkedNode()
SchematicNode * SchematicPort::getLinkedNode (int index) const inline
Returns the node linked with the link index.
{
    return m_links[index] ? m_links[index]->getOtherNode(m_node) : 0;
  }
Referenced by SchematicNode::getLinkedNodes().
getLinkEndPoint()
QPointF SchematicPort::getLinkEndPoint () const
Returns the scene position of the link end.
{ return scenePos() + m_hook; }
Referenced by updateLinksGeometry(), and SchematicLink::updatePath().
getNode()
SchematicNode * SchematicPort::getNode () const inline
{ return m_node; }
getType()
int SchematicPort::getType () const inline
Returns the type of the port.
See also
eFxSchematicPortType, eStageSchematicPortType
{ return m_type; }
Referenced by FxSchematicPort::linkTo(), StageSchematicNodePort::linkTo(), StageSchematicSplinePort::linkTo(), makeLink(), FxSchematicPort::makeLink(), and SchematicLink::paint().
highLight()
void SchematicPort::highLight (bool value) inline
{ m_highlighted = value; }
isHighlighted()
bool SchematicPort::isHighlighted () const inline
{ return m_highlighted; }
isLinkedTo()
bool SchematicPort::isLinkedTo (SchematicPort * port) const
Returns true if this SchematicPort is linked to port. Otherwise returns false.
{
  if (m_links.size() == 0) return false;
  int i;
  for (i = 0; i < m_links.size(); i++) {
    SchematicLink *link = m_links[i];
    if (((link->getStartPort() == this && link->getEndPort() == port) ||
         (link->getEndPort() == this && link->getStartPort() == port)) &&
        link->isVisible())
      return true;
  }
  return false;
}
References SchematicLink::getEndPort(), and SchematicLink::getStartPort().
Referenced by makeLink(), FxSchematicPort::makeLink(), and StageSchematicScene::updateScene().
linkTo()
virtual bool SchematicPort::linkTo (SchematicPort * port, bool checkOnly = false) pure virtual
Check and make a connection between the data Objects. Returns true if it is possible to have a connection between the data Object represented by this SchematicPort and that represented by port. If check only is false no connections is created!
See also
TFxPort, TStageObject.
Implemented in FxSchematicPort, StageSchematicNodePort, and StageSchematicSplinePort.
makeLink()
SchematicLink * SchematicPort::makeLink (SchematicPort * port) virtual
Make a link from this port to the given port.
Reimplemented in FxSchematicPort.
{
  if (isLinkedTo(port) || !port) return 0;
  SchematicLink *link = new SchematicLink(0, scene());
  if (getType() == 202 && port->getType() == 202) link->setLineShaped(true);
  link->setStartPort(this);
  link->setEndPort(port);
  addLink(link);
  port->addLink(link);
  link->updatePath();
  return link;
}
References addLink(), getType(), isLinkedTo(), SchematicLink::setEndPort(), SchematicLink::setStartPort(), and SchematicLink::updatePath().
Referenced by StageSchematicScene::updateScene().
mouseMoveEvent()
void SchematicPort::mouseMoveEvent (QGraphicsSceneMouseEvent * me) override protected
{
  if (m_buttonState != Qt::LeftButton) return;
  if (m_ghostLinks.isEmpty()) return;
  // Snapping
  SchematicPort *linkingTo = searchPort(me->scenePos());
  if (!linkingTo) {
    for (SchematicLink *ghostLink : m_ghostLinks) {
      ghostLink->updateEndPos(me->scenePos());
      ghostLink->getStartPort()->showSnappedLinks(m_linkingTo);
    }
    if (m_linkingTo) {
      m_linkingTo->highLight(false);
      m_linkingTo->update();
      m_linkingTo = nullptr;
    }
  }
  // if to be connected something
  else if (linkingTo != this) {
    m_linkingTo = linkingTo;
    for (SchematicLink *ghostLink : m_ghostLinks) {
      ghostLink->updatePath(ghostLink->getStartPort(), linkingTo);
      ghostLink->getStartPort()->hideSnappedLinks(m_linkingTo);
    }
  }
  // autopan
  QGraphicsView *viewer = scene()->views()[0];
  viewer->setInteractive(false);
  viewer->ensureVisible(QRectF(me->scenePos(), QSizeF(1, 1)), 5, 5);
  viewer->setInteractive(true);
}
mousePressEvent()
void SchematicPort::mousePressEvent (QGraphicsSceneMouseEvent * me) override protected
{
  if (!isSelected()) {
    if (me->modifiers() != Qt::ControlModifier) scene()->clearSelection();
    if (me->button() == Qt::LeftButton || me->button() == Qt::RightButton)
      getNode()->setSelected(true);
  } else {
    if (me->modifiers() == Qt::ControlModifier &&
        me->button() == Qt::LeftButton)
      getNode()->setSelected(false);
  }
  getNode()->onClicked();
  if (me->button() == Qt::LeftButton && getType() != 202  // eFxLinkPort
      && getType() != 203                                 // eFxGroupedInPort
      && getType() != 204                                 // eFxGroupedOutPort
      && getType() != 103   // eStageSplineGroupPort
      && getType() != 104   // eStageParentGroupPort
      && getType() != 105)  // eStageChildGroupPort
  {
    m_buttonState = Qt::LeftButton;
    QPointF endPos(me->pos());
    // Enable to connect multiple links from all selected nodes
    // only when ( Ctrl + ) dragging from the eStageParentPort.
    if (getType() == 101) {  // eStageParentPort
      QList<QGraphicsItem *> items = scene()->selectedItems();
      if (items.empty()) return;
      for (auto const &item : items) {
        SchematicNode *node = dynamic_cast<SchematicNode *>(item);
        if (node) {
          SchematicPort *parentPort =
              node->getPort(0);  // id 0 is for parent port.
          if (parentPort) {
            SchematicLink *ghostLink = new SchematicLink(0, scene());
            ghostLink->setStartPort(parentPort);
            ghostLink->setZValue(3.0);
            ghostLink->updateEndPos(me->scenePos());
            m_ghostLinks.push_back(ghostLink);
          }
        }
      }
    } else {
      SchematicLink *ghostLink = new SchematicLink(0, scene());
      ghostLink->setStartPort(this);
      ghostLink->setZValue(3.0);
      ghostLink->updateEndPos(me->scenePos());
      m_ghostLinks.push_back(ghostLink);
    }
    emit(isClicked());
  }
}
mouseReleaseEvent()
void SchematicPort::mouseReleaseEvent (QGraphicsSceneMouseEvent * me) override protected
{
  if (me->modifiers() != Qt::ControlModifier && me->button() != Qt::RightButton)
    QGraphicsItem::mouseReleaseEvent(me);
  if (m_buttonState == Qt::LeftButton) emit(isReleased(me->scenePos()));
  // The link is added to the scene only if the user released the left mouse
  // button over
  // a SchematicPort different from SchematicPort of the parent node.
  bool somethingChanged = false;
  if (m_buttonState == Qt::LeftButton && m_linkingTo) {
    TUndoManager::manager()->beginBlock();
    for (SchematicLink *ghostLink : m_ghostLinks) {
      SchematicPort *port = ghostLink->getStartPort();
      if (!port) continue;
      if (!port->isLinkedTo(m_linkingTo) && port->linkTo(m_linkingTo, true)) {
        port->linkTo(m_linkingTo);
        somethingChanged = true;
      } else
        port->showSnappedLinks(m_linkingTo);
    }
    m_buttonState = Qt::NoButton;
    m_linkingTo   = 0;
    TUndoManager::manager()->endBlock();
  }
  if (!m_ghostLinks.isEmpty()) {
    for (SchematicLink *ghostLink : m_ghostLinks)
      scene()->removeItem(ghostLink);
    qDeleteAll(m_ghostLinks.begin(), m_ghostLinks.end());
    m_ghostLinks.clear();
  }
  if (somethingChanged) {
    emit sceneChanged();
    emit xsheetChanged();
  }
}
paint()
void SchematicPort::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget = 0) inline override
                                          {};
removeLink()
void SchematicPort::removeLink (SchematicLink * link)
Removes the link form the links container.
It doesn't remove the link from the scene and it doesn't delete the link!
{ m_links.removeAll(link); }
Referenced by SchematicScene::clearAllItems(), and eraseLink().
setType()
void SchematicPort::setType (int type) inline
Set the type of the port.
{ m_type = type; }
updateLinksGeometry()
void SchematicPort::updateLinksGeometry ()
Updates all links of the ports.
{
  int linkCount = getLinkCount();
  int i;
  for (i = 0; i < linkCount; i++) {
    SchematicLink *link      = getLink(i);
    SchematicPort *startPort = link->getStartPort();
    SchematicPort *endPort   = link->getEndPort();
    if (startPort && endPort) {
      link->updatePath(startPort, endPort);
      link->setPos(startPort->getLinkEndPoint());
    }
  }
}
References SchematicLink::getEndPort(), getLink(), getLinkCount(), getLinkEndPoint(), SchematicLink::getStartPort(), and SchematicLink::updatePath().
Member Data Documentation
m_buttonState
Qt::MouseButton SchematicPort::m_buttonState protected
m_ghostLinks
QList<SchematicLink *> SchematicPort::m_ghostLinks protected
m_highlighted
bool SchematicPort::m_highlighted protected
m_hook
QPointF SchematicPort::m_hook protected
m_linkingTo
SchematicPort* SchematicPort::m_linkingTo protected
m_links
QList<SchematicLink *> SchematicPort::m_links protected
m_node
SchematicNode* SchematicPort::m_node protected
m_type
int SchematicPort::m_type protected
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/toonzqt/schematicnode.h
E:/opentoonz/toonz/sources/toonzqt/schematicnode.cpp