opentoonz: DVGui::DoubleLineEdit Class Reference
DVGui::DoubleLineEdit Class Reference final
The DoubleLineEdit class provides to view an object to manage a double field.
#include <doublefield.h>
Public Member Functions
DoubleLineEdit (QWidget *parent=0, double value=1)
void setValue (double value) override
double getValue () override
void setRange (double minValue, double maxValue) override
void getRange (double &minValue, double &maxValue) override
void setDecimals (int decimals)
int getDecimals () override
Public Member Functions inherited from DVGui::DoubleValueLineEdit
DoubleValueLineEdit (QWidget *parent=0)
virtual void setValue (double value)=0
virtual double getValue ()=0
virtual void setRange (double minValue, double maxValue)=0
virtual void getRange (double &minValue, double &maxValue)=0
virtual int getDecimals ()
Public Member Functions inherited from DVGui::LineEdit
LineEdit (QWidget *parent=0, bool forbiddenSpecialChars=false)
LineEdit (const QString &contents, QWidget *parent=0, bool forbiddenSpecialChars=false)
bool isReturnPressed () const
bool getMouseDragEditing ()
void setMouseDragEditing (bool status)
Additional Inherited Members
Signals inherited from DVGui::DoubleValueLineEdit
void valueChanged ()
Signals inherited from DVGui::LineEdit
void focusIn ()
void returnPressedNow ()
void mouseMoved (QMouseEvent *)
Protected Member Functions inherited from DVGui::DoubleValueLineEdit
void focusOutEvent (QFocusEvent *) override
void mousePressEvent (QMouseEvent *) override
void mouseMoveEvent (QMouseEvent *) override
void mouseReleaseEvent (QMouseEvent *) override
Protected Member Functions inherited from DVGui::LineEdit
void focusInEvent (QFocusEvent *event) override
void keyPressEvent (QKeyEvent *event) override
void mouseMoveEvent (QMouseEvent *) override
Protected Attributes inherited from DVGui::DoubleValueLineEdit
bool m_mouseDragEditing = false
bool m_isTyping = false
Detailed Description
The DoubleLineEdit class provides to view an object to manage a double field.
         Inherits \b LineEdit, set a double validator \b
QDoubleValidator.
         You can pass to constructor current value, getValue(), minimum
and max value field, getRange(), and number of decimals, getDecimals() or you can set this value using setValue(), setRange() and setDecimals().
Constructor & Destructor Documentation
DoubleLineEdit()
DoubleLineEdit::DoubleLineEdit (QWidget * parent = 0, double value = 1)
    : DoubleValueLineEdit(parent) {
  m_validator =
      new QDoubleValidator(-(std::numeric_limits<double>::max)(),
                           (std::numeric_limits<double>::max)(), 5, this);
  setValidator(m_validator);
  setValue(value);
  bool ret = connect(this, SIGNAL(editingFinished()), SIGNAL(valueChanged()));
  assert(ret);
}
~DoubleLineEdit()
DVGui::DoubleLineEdit::~DoubleLineEdit () inline
{}
Member Function Documentation
getDecimals()
int DoubleLineEdit::getDecimals () override virtual
Return length of field value decimal part.
Reimplemented from DVGui::DoubleValueLineEdit.
{ return m_validator->decimals(); }
getRange()
void DoubleLineEdit::getRange (double & minValue, double & maxValue) override virtual
Set minValue an maxValue to current range; to current validator minimum and maximum value.
Implements DVGui::DoubleValueLineEdit.
{
  minValue = m_validator->bottom();
  maxValue = m_validator->top();
}
Referenced by setValue().
getValue()
double DoubleLineEdit::getValue () override virtual
Return a double with field value.
Implements DVGui::DoubleValueLineEdit.
{ return text().toDouble(); }
Referenced by ConvertPopup::apply(), OutputSettingsPopup::onDominantFieldChanged(), OutputSettingsPopup::onGammaFldEditFinished(), and OutputSettingsPopup::onStretchFldEditFinished().
setDecimals()
void DoubleLineEdit::setDecimals (int decimals)
Set length of field value decimal part to decimals.
{
  m_validator->setDecimals(decimals);
}
setRange()
void DoubleLineEdit::setRange (double minValue, double maxValue) override virtual
Set the range of field from minValue to maxValue; set validator value.
Implements DVGui::DoubleValueLineEdit.
{
  m_validator->setRange(minValue, maxValue, m_validator->decimals());
}
setValue()
void DoubleLineEdit::setValue (double value) override virtual
Set text field value to double value value.
Implements DVGui::DoubleValueLineEdit.
{
  double minValue, maxValue;
  getRange(minValue, maxValue);
  if (value < minValue) value = minValue;
  if (value > maxValue) value = maxValue;
  QString str;
  str.setNum(value);
  setText(str);
  // Faccio in modo che il cursore sia sulla prima cifra, cosi' se la stringa
  // da visualizzare e' piu' lunga del campo le cifre che vengono troncate sono
  // le ultime e non le prime (dovrebbero essere quelle dopo la virgola).
  setCursorPosition(0);
}
References getRange().
Referenced by OutputSettingsPopup::onGammaFldEditFinished(), OutputSettingsPopup::onStretchFldEditFinished(), and OutputSettingsPopup::updateField().
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/toonzqt/doublefield.h
E:/opentoonz/toonz/sources/toonzqt/doublefield.cpp