opentoonz: FunctionSheetColumnHeadViewer Class Reference
FunctionSheetColumnHeadViewer Class Reference final
Public Member Functions
FunctionSheetColumnHeadViewer (FunctionSheet *parent)
Public Member Functions inherited from Spreadsheet::ColumnPanel
ColumnPanel (SpreadsheetViewer *viewer)
Public Member Functions inherited from Spreadsheet::GenericPanel
GenericPanel (SpreadsheetViewer *viewer)
SpreadsheetViewer * getViewer () const
virtual DragTool * createDragTool (QMouseEvent *)
Protected Member Functions
void paintEvent (QPaintEvent *) override
void mousePressEvent (QMouseEvent *) override
void mouseMoveEvent (QMouseEvent *) override
void contextMenuEvent (QContextMenuEvent *) override
Protected Member Functions inherited from Spreadsheet::GenericPanel
void paintEvent (QPaintEvent *) override
void mousePressEvent (QMouseEvent *) override
void mouseReleaseEvent (QMouseEvent *) override
void mouseMoveEvent (QMouseEvent *) override
Detailed Description
Constructor & Destructor Documentation
FunctionSheetColumnHeadViewer()
FunctionSheetColumnHeadViewer::FunctionSheetColumnHeadViewer (FunctionSheet * parent)
    : Spreadsheet::ColumnPanel(parent), m_sheet(parent), m_draggingChannel(0) {
  setMouseTracking(true);  // for updating the tooltip
  setFocusPolicy(Qt::NoFocus);
}
Member Function Documentation
contextMenuEvent()
void FunctionSheetColumnHeadViewer::contextMenuEvent (QContextMenuEvent * ce) override protected
{
  // First, select column under cursor
  const QPoint &pos = ce->pos();
  int cursorCol     = getViewer()->xyToPosition(pos).layer();
  if (cursorCol < 0 || cursorCol >= m_sheet->getChannelCount()) return;
  FunctionTreeModel::Channel *channel = m_sheet->getChannel(cursorCol);
  if (!channel) return;
  // Ok, now let's summon a context menu with appropriate options
  FunctionViewer *fv = m_sheet->getViewer();
  if (!fv) {
    assert(fv);
    return;
  }
  const QPoint &globalPos = mapToGlobal(pos);
  if (pos.y() >= cChannelNameY)
    fv->openContextMenu(channel, globalPos);
  else {
    FunctionTreeModel::ChannelGroup *group = channel->getChannelGroup();
    // In this case, commands are different from the tree view. Rather than
    // showing in the tree,
    // channels get ACTIVATED
    QMenu menu;
    QAction showAnimatedOnly(FunctionTreeView::tr("Show Animated Only"), 0);
    QAction showAll(FunctionTreeView::tr("Show All"), 0);
    QAction hideSelected(FunctionTreeView::tr("Hide Selected"), 0);
    menu.addAction(&showAnimatedOnly);
    menu.addAction(&showAll);
    menu.addAction(&hideSelected);
    // execute menu
    QAction *action = menu.exec(globalPos);
    // Process action
    if (action == &showAll) {
      int c, cCount = group->getChildCount();
      for (c = 0; c != cCount; ++c) {
        FunctionTreeModel::Channel *channel =
            dynamic_cast<FunctionTreeModel::Channel *>(group->getChild(c));
        if (channel && !channel->isHidden()) channel->setIsActive(true);
      }
    } else if (action == &showAnimatedOnly) {
      int c, cCount = group->getChildCount();
      for (c = 0; c != cCount; ++c) {
        FunctionTreeModel::Channel *channel =
            dynamic_cast<FunctionTreeModel::Channel *>(group->getChild(c));
        if (channel && !channel->isHidden())
          channel->setIsActive(channel->isAnimated());
      }
    } else if (action == &hideSelected) {
      QRect selectedCells = getViewer()->getSelectedCells();
      // hide the selected columns from the right to the left
      for (int col = selectedCells.right(); col >= selectedCells.left();
           col--) {
        FunctionTreeModel::Channel *chan = m_sheet->getChannel(col);
        if (chan) chan->setIsActive(false);
      }
      // clear cell selection
      getViewer()->selectCells(QRect());
    } else
      return;
    fv->update();
  }
}
mouseMoveEvent()
void FunctionSheetColumnHeadViewer::mouseMoveEvent (QMouseEvent * e) override protected
update tooltips
{
  if ((e->buttons() & Qt::MidButton) && m_draggingChannel &&
      (e->pos() - m_dragStartPosition).manhattanLength() >=
          QApplication::startDragDistance()) {
    QDrag *drag         = new QDrag(this);
    QMimeData *mimeData = new QMimeData;
    mimeData->setText(m_draggingChannel->getExprRefName());
    drag->setMimeData(mimeData);
    static const QPixmap cursorPixmap(":Resources/dragcursor_exp_text.png");
    drag->setDragCursor(cursorPixmap, Qt::MoveAction);
    Qt::DropAction dropAction = drag->exec();
    return;
  }
  // get the column under the cursor
  int col = getViewer()->xyToPosition(e->pos()).layer();
  FunctionTreeModel::Channel *channel = m_sheet->getChannel(col);
  if (!channel) {
    setToolTip(QString(""));
  } else {
    QString tooltip = channel->getExprRefName();
    TXsheet *xsh    = m_sheet->getViewer()->getXsheetHandle()->getXsheet();
    if (xsh->isReferenceManagementIgnored(channel->getParam()))
      tooltip +=
          "\n" + tr("Some key(s) in this parameter loses original reference in "
                    "expression.\nManually changing any keyframe will clear "
                    "the warning.");
    setToolTip(tooltip);
  }
  // modify selected channel by left dragging
  if (m_clickedColumn >= 0 && channel && e->buttons() & Qt::LeftButton) {
    int fromC      = std::min(m_clickedColumn, col);
    int toC        = std::max(m_clickedColumn, col);
    int lastKeyPos = 0;
    for (int c = fromC; c <= toC; c++) {
      FunctionTreeModel::Channel *tmpChan = m_sheet->getChannel(c);
      if (!tmpChan) continue;
      std::set<double> frames;
      tmpChan->getParam()->getKeyframes(frames);
      if (!frames.empty())
        lastKeyPos = std::max(lastKeyPos, (int)*frames.rbegin());
    }
    QRect rect(std::min(m_clickedColumn, col), 0,
               std::abs(col - m_clickedColumn) + 1, lastKeyPos + 1);
    getViewer()->selectCells(rect);
  }
}
References FunctionTreeModel::Channel::getExprRefName(), TDoubleParam::getKeyframes(), and SpreadsheetViewer::xyToPosition().
mousePressEvent()
void FunctionSheetColumnHeadViewer::mousePressEvent (QMouseEvent * e) override protected
{
  QPoint pos                          = e->pos();
  int currentC                        = getViewer()->xyToPosition(pos).layer();
  FunctionTreeModel::Channel *channel = m_sheet->getChannel(currentC);
  if (!channel) {
    m_clickedColumn = -1;
    return;
  }
  if (e->button() == Qt::MidButton) {
    m_draggingChannel   = channel;
    m_dragStartPosition = e->pos();
    return;
  } else
    channel->setIsCurrent(true);
  m_draggingChannel = 0;
  if (e->button() == Qt::LeftButton) {
    int lastKeyPos = 0;
    // if the current selection does not contain the first cell in m_firstColumn
    // then we assume that the selection has been modified and treat shift+click
    // as normal click.
    if (getViewer()->getSelectedCells().contains(m_clickedColumn, 0) &&
        (e->modifiers() & Qt::ShiftModifier)) {
      int fromC = std::min(m_clickedColumn, currentC);
      int toC   = std::max(m_clickedColumn, currentC);
      for (int c = fromC; c <= toC; c++) {
        FunctionTreeModel::Channel *tmpChan = m_sheet->getChannel(c);
        if (!tmpChan) continue;
        std::set<double> frames;
        tmpChan->getParam()->getKeyframes(frames);
        if (!frames.empty())
          lastKeyPos = std::max(lastKeyPos, (int)*frames.rbegin());
      }
    } else {
      // Open folder
      FunctionTreeModel::ChannelGroup *channelGroup =
          channel->getChannelGroup();
      if (!channelGroup->isOpen())
        channelGroup->getModel()->setExpandedItem(channelGroup->createIndex(),
                                                  true);
      // Select all segment
      std::set<double> frames;
      channel->getParam()->getKeyframes(frames);
      if (!frames.empty()) lastKeyPos = (int)*frames.rbegin();
      m_clickedColumn = currentC;
    }
    QRect rect(std::min(m_clickedColumn, currentC), 0,
               std::abs(currentC - m_clickedColumn) + 1, lastKeyPos + 1);
    getViewer()->selectCells(rect);
  }
  // Switch selection before opening the context menu
  // if the clicked column is out of the selection
  else if (e->button() == Qt::RightButton) {
    QRect selectedCell = getViewer()->getSelectedCells();
    if (selectedCell.left() > currentC || selectedCell.right() < currentC) {
      int lastKeyPos = 0;
      std::set<double> frames;
      channel->getParam()->getKeyframes(frames);
      if (!frames.empty()) lastKeyPos = (int)*frames.rbegin();
      getViewer()->selectCells(QRect(currentC, 0, 1, lastKeyPos + 1));
    }
  }
}
paintEvent()
void FunctionSheetColumnHeadViewer::paintEvent (QPaintEvent * e) override protected
{
  QPainter painter(this);
  QRect toBeUpdated = e->rect();
  painter.setClipRect(toBeUpdated);
  // visible columns range
  CellRange visible = getViewer()->xyRectToRange(toBeUpdated);
  int c0            = visible.from().layer();
  int c1            = visible.to().layer();
  if (c0 > c1) return;
  int n = c1 - c0 + 1 + 2;
  FunctionTreeModel::ChannelGroup *currentGroup = 0;
  /*--- Display range + right and left 1 column range ChannelGroup. If there is
   * none, put 0
   * ---*/
  std::vector<FunctionTreeModel::ChannelGroup *> channelGroups(n);
  for (int i = 0; i < n; ++i) {
    channelGroups[i] = 0;
    int c = c0 - 1 + i;
    if (c < 0) continue;
    FunctionTreeModel::Channel *channel = m_sheet->getChannel(c);
    if (!channel) continue;
    channelGroups[i] = channel->getChannelGroup();
    if (!currentGroup && channel->isCurrent()) currentGroup = channelGroups[i];
  }
  int y0 = 0;
  int y1 = 17;  // needs work
  int y3 = 53;
  if (m_sheet->isSmallHeader()) y3 = 34;
  /*--- Fill header with background color ---*/
  for (int c = c0; c <= c1; c++) {
    FunctionTreeModel::Channel *channel = m_sheet->getChannel(c);
    if (!channel) break;
    int x0 = getViewer()->columnToX(c);
    int x1 = getViewer()->columnToX(c + 1) - 1;
    // Column Width
    int width = x1 - x0 + 1;
    painter.fillRect(x0, y0, width, y3 - y0, getViewer()->getBGColor());
  }
  for (int c = c0; c <= c1; ++c) {
    FunctionTreeModel::Channel *channel = m_sheet->getChannel(c);
    if (!channel) {
      if (c != c0) {
        // draw "the end" border
        int x0 = getViewer()->columnToX(c);
        painter.setPen(getViewer()->getColumnHeaderBorderColor());
        painter.drawLine(x0, y0, x0, y3);
      }
      break;
    }
    int i = c - c0 + 1;
    /*---- Channel Column of the current Column and the preceding and following
     * Columns ---*/
    FunctionTreeModel::ChannelGroup *prevGroup = channelGroups[c - c0],
                                    *group     = channelGroups[c - c0 + 1],
                                    *nextGroup = channelGroups[c - c0 + 2];
    /*---- If the group is different from the before and after, flags are set
     * respectively ---*/
    bool firstGroupColumn = prevGroup != group;
    bool lastGroupColumn  = nextGroup != group;
    /*--- The left and right coordinates of the current column ---*/
    int x0 = getViewer()->columnToX(c);
    int x1 = getViewer()->columnToX(c + 1) - 1;
    // Column width
    int width = x1 - x0 + 1;
    QRect selectedRect = m_sheet->getSelectedCells();
    bool isSelected =
        (selectedRect.left() <= c && c <= selectedRect.right()) ? true : false;
    // paint with light color if selected
    if (isSelected)
      painter.fillRect(x0, y1, width, y3 - y1,
                       getViewer()->getCurrentRowBgColor());
    // draw horizonntal lines
    painter.setPen(QPen(getViewer()->getColumnHeaderBorderColor(), 3));
    painter.drawLine(x0, y0, x1, y0);
    painter.setPen(getViewer()->getColumnHeaderBorderColor());
    painter.drawLine(x0, y1, x1, y1);
    // draw vertical bar
    painter.fillRect(x0, y1, 6, y3 - y1,
                     getViewer()->getColumnHeaderBorderColor());
    if (firstGroupColumn)
      painter.fillRect(x0, y0, 6, y1 - y0,
                       getViewer()->getColumnHeaderBorderColor());
    // channel name
    painter.setPen(getViewer()->getTextColor());
    if (channel->isCurrent())
      painter.setPen(m_sheet->getViewer()->getCurrentTextColor());
    QString text = channel->getShortName();
    int d        = 8;
    int flags    = Qt::AlignLeft | Qt::AlignVCenter;
    if (!m_sheet->isSmallHeader()) flags |= Qt::TextWrapAnywhere;
    painter.drawText(x0 + d, y1, width - d, y3 - y1 + 1, flags, text);
    // warning of losing expression reference
    TXsheet *xsh = m_sheet->getViewer()->getXsheetHandle()->getXsheet();
    if (xsh->isReferenceManagementIgnored(channel->getParam())) {
      static QIcon paramIgnoredIcon(":Resources/paramignored_on.svg");
      painter.drawPixmap(QPoint(x0 + 30, y1 + 20),
                         paramIgnoredIcon.pixmap(21, 17));
    }
    // group name
    if (firstGroupColumn) {
      int tmpwidth = (lastGroupColumn) ? width : width * 2;
      painter.setPen(getViewer()->getTextColor());
      if (group == currentGroup)
        painter.setPen(m_sheet->getViewer()->getCurrentTextColor());
      text = group->getShortName();
      painter.drawText(x0 + d, y0, tmpwidth - d, y1 - y0 + 1,
                       Qt::AlignLeft | Qt::AlignVCenter, text);
    }
  }
}
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/toonzqt/functionsheet.h
E:/opentoonz/toonz/sources/toonzqt/functionsheet.cpp