opentoonz: Previewer::Imp Class Reference
Previewer::Imp Class Reference final
Classes
struct FrameInfo
Public Member Functions
Imp (Previewer *owner)
void notifyStarted (int frame)
void notifyCompleted (int frame)
void notifyFailed (int frame)
void notifyUpdate ()
TFxPair buildSceneFx (int frame)
void updateRenderSettings ()
void updateAliases ()
void updateAliasKeyword (const std::string &keyword)
void updateFrameRange ()
void updateProgressBarStatus ()
void updateCamera ()
void updatePreviewRect ()
void refreshFrame (int frame)
Starts rendering the passed frame.
void onRenderRasterStarted (const RenderData &renderData) override
Adds the renderized image to TImageCache; listeners are advised too.
void onRenderRasterCompleted (const RenderData &renderData) override
Adds the renderized image to TImageCache; listeners are advised too.
void onRenderFailure (const RenderData &renderData, TException &e) override
void doOnRenderRasterStarted (const RenderData &renderData)
void doOnRenderRasterCompleted (const RenderData &renderData)
void doOnRenderRasterFailed (const RenderData &renderData)
Adds the renderized image to TImageCache; listeners are advised too.
void remove (int frame)
void remove ()
void saveFrame ()
bool doSaveRenderedFrames (const TFilePath fp)
Public Member Functions inherited from TRenderPort
void setRenderArea (const TRectD &area)
TRectD & getRenderArea ()
Ritorna m_renderArea.
virtual void onRenderRasterStarted (const RenderData &renderData)
virtual void onRenderRasterCompleted (const RenderData &renderData)
virtual void onRenderFailure (const RenderData &renderData, TException &e)
virtual void onRenderFinished (bool isCanceled=false)
Public Attributes
Previewer * m_owner
TThread::Mutex m_mutex
std::set< Previewer::Listener * > m_listeners
std::map< int, FrameInfo > m_frames
std::vector< UCHAR > m_pbStatus
int m_computingFrameCount
TRenderSettings m_renderSettings
std::string m_cachePrefix
TDimension m_cameraRes
TRectD m_renderArea
TPointD m_cameraPos
bool m_subcamera
TRect m_previewRect
TRenderer m_renderer
TLevelWriterP m_lw
int m_currentFrameToSave
Detailed Description
Constructor & Destructor Documentation
Imp()
Previewer::Imp::Imp (Previewer * owner)
    : m_owner(owner)
    , m_cameraRes(0, 0)
    , m_renderer(TSystem::getProcessorCount())
    , m_computingFrameCount(0)
    , m_currentFrameToSave(0)
    , m_subcamera(false)
    , m_lw() {
  // Precomputing (ie predictive cache) is disabled in this case. This is due to
  // current TFxCacheManager's
  // implementation, which can't still handle multiple render processes from the
  // same TRenderer. This should
  // change in the near future...
  m_renderer.enablePrecomputing(false);
  m_renderer.addPort(this);
  updateRenderSettings();
  updateCamera();
  updateFrameRange();
}
~Imp()
Previewer::Imp::~Imp ()
                   {
  m_renderer.removePort(this);
  // for(std::map<int, FrameInfo*>::iterator it=m_frames.begin();
  // it!=m_frames.end(); ++it)
  //  delete it->second; //crash on exit! not a serious leak, Previewer is a
  //  singleton
}
Member Function Documentation
buildSceneFx()
TFxPair Previewer::Imp::buildSceneFx (int frame)
{
  TFxPair fxPair;
  TApp *app         = TApp::instance();
  ToonzScene *scene = app->getCurrentScene()->getScene();
  TXsheet *xsh      = scene->getXsheet();
  if (m_renderSettings.m_stereoscopic) {
    scene->shiftCameraX(-m_renderSettings.m_stereoscopicShift / 2.0);
    fxPair.m_frameA = ::buildSceneFx(
        scene, xsh, frame, TOutputProperties::AllLevels,
        m_renderSettings.m_applyShrinkToViewer ? m_renderSettings.m_shrinkX : 1,
        false);
    scene->shiftCameraX(m_renderSettings.m_stereoscopicShift);
    fxPair.m_frameB = ::buildSceneFx(
        scene, xsh, frame, TOutputProperties::AllLevels,
        m_renderSettings.m_applyShrinkToViewer ? m_renderSettings.m_shrinkX : 1,
        false);
    scene->shiftCameraX(-m_renderSettings.m_stereoscopicShift / 2.0);
  } else
    fxPair.m_frameA = ::buildSceneFx(
        scene, xsh, frame, TOutputProperties::AllLevels,
        m_renderSettings.m_applyShrinkToViewer ? m_renderSettings.m_shrinkX : 1,
        false);
  return fxPair;
}
doOnRenderRasterCompleted()
void Previewer::Imp::doOnRenderRasterCompleted (const RenderData & renderData)
{
  int renderId = renderData.m_renderId;
  int frame    = renderData.m_frames[0];
  if (renderData.m_rasB) {
    assert(m_renderSettings.m_stereoscopic);
    TRop::makeStereoRaster(renderData.m_rasA, renderData.m_rasB);
  }
  TRasterP ras(renderData.m_rasA);
  m_computingFrameCount--;
  // Find the render infos in the Previewer
  std::map<int, FrameInfo>::iterator it = m_frames.find(frame);
  if (it == m_frames.end()) return;
  // Ensure that the render process id is the same
  if (renderId != it->second.m_renderId) return;
  // Store the rendered image in the cache - this is done in the MAIN thread due
  // to the necessity of accessing it->second.m_rectUnderRender for raster
  // extraction.
  std::string str = m_cachePrefix + std::to_string(frame);
  TRasterImageP ri(TImageCache::instance()->get(str, true));
  TRasterP cachedRas(ri ? ri->getRaster() : TRasterP());
  if (!cachedRas || (cachedRas->getSize() != m_cameraRes)) {
    TImageCache::instance()->remove(str);
    // Create the raster at camera resolution
    cachedRas = ras->create(m_cameraRes.lx, m_cameraRes.ly);
    cachedRas->clear();
    ri = TRasterImageP(cachedRas);
  }
  // Finally, copy the rendered raster over the cached one
  TRect rectUnderRender(
      it->second
          .m_rectUnderRender);  // Extract may MODIFY IT! E.g. with shrinks..!
  cachedRas = cachedRas->extract(rectUnderRender);
  if (cachedRas) {
    cachedRas->copy(ras);
    TImageCache::instance()->add(str, ri);
  }
  // Update the FrameInfo
  it->second.m_renderedRegion += toQRect(it->second.m_rectUnderRender);
  it->second.m_rectUnderRender = TRect();
  // Update the progress bar status
  if (frame < m_pbStatus.size())
    m_pbStatus[frame] = FlipSlider::PBFrameFinished;
  // Notify listeners
  notifyCompleted(frame);
}
doOnRenderRasterFailed()
void Previewer::Imp::doOnRenderRasterFailed (const RenderData & renderData)
Adds the renderized image to TImageCache; listeners are advised too.
{
  m_computingFrameCount--;
  int frame = (int)renderData.m_frames[0];
  std::map<int, FrameInfo>::iterator it = m_frames.find(frame);
  if (it == m_frames.end()) return;
  if (renderData.m_renderId != it->second.m_renderId) return;
  it->second.m_renderedRegion  = QRegion();
  it->second.m_rectUnderRender = TRect();
  // Update the progress bar status
  if (frame < m_pbStatus.size())
    m_pbStatus[frame] = FlipSlider::PBFrameNotStarted;
  notifyCompleted(frame);  // Completed!?
}
References TRenderPort::RenderData::m_frames, and TRenderPort::RenderData::m_renderId.
doOnRenderRasterStarted()
void Previewer::Imp::doOnRenderRasterStarted (const RenderData & renderData)
{
  int frame = renderData.m_frames[0];
  m_computingFrameCount++;
  // Update the progress bar status
  if (frame < m_pbStatus.size()) m_pbStatus[frame] = FlipSlider::PBFrameStarted;
  // Notify listeners
  notifyStarted(frame);
}
doSaveRenderedFrames()
bool Previewer::Imp::doSaveRenderedFrames (const TFilePath fp)
{
  ToonzScene *scene = TApp::instance()->getCurrentScene()->getScene();
  TOutputProperties *outputSettings =
      scene->getProperties()->getOutputProperties();
  QStringList formats;
  TLevelWriter::getSupportedFormats(formats, true);
  Tiio::Writer::getSupportedFormats(formats, true);
  std::string ext = fp.getType();
  if (ext == "") {
    ext = outputSettings->getPath().getType();
    fp  = fp.withType(ext);
  }
  if (fp.getName() == "") {
    DVGui::warning(QObject::tr(
        "The file name cannot be empty or contain any of the following "
        "characters:(new line)  \\ / : * ? \"  |"));
    return false;
  }
  if (!formats.contains(QString::fromStdString(ext))) {
    DVGui::warning(QObject::tr("Unsopporter raster format, cannot save"));
    return false;
  }
  if (fp.getWideName() == L"") fp = fp.withName(scene->getSceneName());
  if (TFileType::getInfo(fp) == TFileType::RASTER_IMAGE || ext == "pct" ||
      fp.getType() == "pic" || ext == "pict")  // pct e' un formato"livello" (ha
                                               // i settings di quicktime) ma
                                               // fatto di diversi frames
    fp = fp.withFrame(TFrameId::EMPTY_FRAME);
  fp          = scene->decodeFilePath(fp);
  bool exists = TFileStatus(fp.getParentDir()).doesExist();
  if (!exists) {
    try {
      TFilePath parent = fp.getParentDir();
      TSystem::mkDir(parent);
      DvDirModel::instance()->refreshFolder(parent.getParentDir());
    } catch (TException &e) {
      error(QObject::tr("Cannot create %1 : %2",
                        "Previewer warning %1:path %2:message")
                .arg(toQString(fp.getParentDir()))
                .arg(QString(::to_string(e.getMessage()).c_str())));
      return false;
    } catch (...) {
      error(QObject::tr("Cannot create %1", "Previewer warning %1:path")
                .arg(toQString(fp.getParentDir())));
      return false;
    }
  }
  if (TSystem::doesExistFileOrLevel(fp)) {
    QString question(
        QObject::tr("File %1 already exists.\nDo you want to overwrite it?")
            .arg(toQString(fp)));
    int ret = DVGui::MsgBox(question, QObject::tr("Overwrite"),
                            QObject::tr("Cancel"), 0);
    if (ret == 2) return false;
  }
  try {
    m_lw = TLevelWriterP(fp,
                         outputSettings->getFileFormatProperties(fp.getType()));
  } catch (TImageException &e) {
    error(QString::fromStdString(::to_string(e.getMessage())));
    return false;
  }
  m_lw->setFrameRate(outputSettings->getFrameRate());
  m_currentFrameToSave = 1;
  ProgressBarMessager(
      eBegin,
      TApp::instance()->getCurrentXsheet()->getXsheet()->getFrameCount())
      .sendBlocking();
  QTimer::singleShot(50, m_owner, SLOT(saveFrame()));
  return true;
}
notifyCompleted()
void Previewer::Imp::notifyCompleted (int frame) inline
{
  std::set<Previewer::Listener *>::iterator it;
  for (it = m_listeners.begin(); it != m_listeners.end(); ++it)
    (*it)->onRenderCompleted(frame);
}
notifyFailed()
void Previewer::Imp::notifyFailed (int frame) inline
{
  std::set<Previewer::Listener *>::iterator it;
  for (it = m_listeners.begin(); it != m_listeners.end(); ++it)
    (*it)->onRenderFailed(frame);
}
notifyStarted()
void Previewer::Imp::notifyStarted (int frame) inline
{
  std::set<Previewer::Listener *>::iterator it;
  for (it = m_listeners.begin(); it != m_listeners.end(); ++it)
    (*it)->onRenderStarted(frame);
}
notifyUpdate()
void Previewer::Imp::notifyUpdate () inline
{
  std::set<Previewer::Listener *>::iterator it;
  for (it = m_listeners.begin(); it != m_listeners.end(); ++it)
    (*it)->onPreviewUpdate();
}
onRenderFailure()
void Previewer::Imp::onRenderFailure (const RenderData & renderData, TException & e) override virtual
Removes the associated raster from TImageCache, and listeners are made aware.
Reimplemented from TRenderPort.
{
  m_owner->emitFailedFrame(renderData);
}
onRenderRasterCompleted()
void Previewer::Imp::onRenderRasterCompleted (const RenderData & renderData) override virtual
Adds the renderized image to TImageCache; listeners are advised too.
Reimplemented from TRenderPort.
{
  if (renderData.m_rasB) {
    RenderData _renderData = renderData;
    assert(m_renderSettings.m_stereoscopic);
    TRop::makeStereoRaster(_renderData.m_rasA, _renderData.m_rasB);
    if (_renderData.m_info.m_gamma != 1.0)
      TRop::gammaCorrect(_renderData.m_rasA, _renderData.m_info.m_gamma);
    _renderData.m_rasB = TRasterP();
    m_owner->emitRenderedFrame(_renderData);
    return;
  }
  // If required, correct gamma
  if (renderData.m_info.m_gamma != 1.0)
    TRop::gammaCorrect(renderData.m_rasA, renderData.m_info.m_gamma);
  // Emit the started signal to execute code in the main thread
  m_owner->emitRenderedFrame(renderData);
}
References TRop::gammaCorrect(), TRenderSettings::m_gamma, TRenderPort::RenderData::m_info, TRenderPort::RenderData::m_rasB, and TRenderSettings::m_stereoscopic.
onRenderRasterStarted()
void Previewer::Imp::onRenderRasterStarted (const RenderData & renderData) override virtual
Adds the renderized image to TImageCache; listeners are advised too.
Reimplemented from TRenderPort.
{
  // Emit the started signal to execute code in the main thread
  m_owner->emitStartedFrame(renderData);
}
refreshFrame()
void Previewer::Imp::refreshFrame (int frame)
Starts rendering the passed frame.
{
  if (suspendedRendering) return;
  // Build the region to render
  updatePreviewRect();
  if (m_previewRect.getLx() <= 0 || m_previewRect.getLy() <= 0) return;
  // Retrieve the FrameInfo for passed frame
  std::map<int, FrameInfo>::iterator it = m_frames.find(frame);
  if (it != m_frames.end()) {
    // In case the rect we would render is contained in the frame's rendered
    // region, quit
    if (::contains(it->second.m_renderedRegion, m_previewRect)) return;
    // Then, check the m_previewRect against the frame's m_rectUnderRendering.
    // Ensure that we're not re-launching the very same render.
    if (it->second.m_rectUnderRender == m_previewRect) return;
    // Stop any frame's previously running render process
    m_renderer.abortRendering(it->second.m_renderId);
  } else {
    it = m_frames.insert(std::make_pair(frame, FrameInfo())).first;
    // In case the frame is not in the frame range, we add a temporary
    // supplement
    // to the progress bar.
    if (frame >= (int)m_pbStatus.size()) m_pbStatus.resize(frame + 1);
  }
  // Build the TFxPair to be passed to TRenderer
  TFxPair fxPair = buildSceneFx(frame);
  // Update the RenderInfos associated with frame
  it->second.m_rectUnderRender = m_previewRect;
  it->second.m_alias = fxPair.m_frameA->getAlias(frame, m_renderSettings);
  if (fxPair.m_frameB)
    it->second.m_alias =
        it->second.m_alias + fxPair.m_frameB->getAlias(frame, m_renderSettings);
  // Retrieve the renderId of the rendering instance
  it->second.m_renderId = m_renderer.nextRenderId();
  std::string contextName("P");
  contextName += m_subcamera ? "SC" : "FU";
  contextName += std::to_string(frame);
  TPassiveCacheManager::instance()->setContextName(it->second.m_renderId,
                                                   contextName);
  // Start the render
  m_renderer.startRendering(frame, m_renderSettings, fxPair);
}
References TRenderer::nextRenderId(), and TRenderer::startRendering().
remove() [1/2]
void Previewer::Imp::remove ()
{
  m_renderer.stopRendering(false);
  // Remove all cached images
  std::map<int, FrameInfo>::iterator it;
  for (it = m_frames.begin(); it != m_frames.end(); ++it)
    TImageCache::instance()->remove(m_cachePrefix + std::to_string(it->first));
  m_frames.clear();
}
remove() [2/2]
void Previewer::Imp::remove (int frame)
{
  // Search the frame among rendered ones
  std::map<int, FrameInfo>::iterator it = m_frames.find(frame);
  if (it != m_frames.end()) {
    m_renderer.abortRendering(it->second.m_renderId);
    m_frames.erase(frame);
  }
  // Remove the associated image from cache
  TImageCache::instance()->remove(m_cachePrefix + std::to_string(frame));
}
saveFrame()
void Previewer::Imp::saveFrame ()
{
  static int savedFrames = 0;
  int frameCount =
      TApp::instance()->getCurrentXsheet()->getXsheet()->getFrameCount();
  assert(Pd);
  for (; m_currentFrameToSave <= frameCount; m_currentFrameToSave++) {
    ProgressBarMessager(eIncrement, m_currentFrameToSave).sendBlocking();
    if (!Pd) break;
    // Ensure that current frame actually have to be saved
    int currFrameToSave                   = m_currentFrameToSave - 1;
    std::map<int, FrameInfo>::iterator it = m_frames.find(currFrameToSave);
    if (it == m_frames.end()) continue;
    if (m_pbStatus.size() < currFrameToSave ||
        m_pbStatus[currFrameToSave] != FlipSlider::PBFrameFinished)
      continue;
    TImageP img = TImageCache::instance()->get(
        m_cachePrefix + std::to_string(currFrameToSave), false);
    if (!img) continue;
    // Save the frame
    TImageWriterP writer = m_lw->getFrameWriter(TFrameId(m_currentFrameToSave));
    bool failureOnSaving = false;
    if (!writer) continue;
    writer->save(img);
    savedFrames++;
    m_currentFrameToSave++;
    QTimer::singleShot(50, m_owner, SLOT(saveFrame()));
    return;
  }
  // Output the save result
  QString str =
      QObject::tr("Saved %1 frames out of %2 in %3",
                  "Previewer %1:savedframes %2:framecount %3:filepath")
          .arg(QString(std::to_string(savedFrames).c_str()))
          .arg(QString(std::to_string(frameCount).c_str()))
          .arg(QString(::to_string(m_lw->getFilePath()).c_str()));
  if (!Pd) str = QObject::tr("Canceled! ", "Previewer") + str;
  ProgressBarMessager(eEnd, 0, str).send();
  m_currentFrameToSave = 0;
  m_lw                 = TLevelWriterP();
  savedFrames          = 0;
}
updateAliases()
void Previewer::Imp::updateAliases ()
{
  std::map<int, FrameInfo>::iterator it;
  for (it = m_frames.begin(); it != m_frames.end(); ++it) {
    TFxPair fxPair = buildSceneFx(it->first);
    std::string newAlias =
        fxPair.m_frameA ? fxPair.m_frameA->getAlias(it->first, m_renderSettings)
                        : "";
    newAlias = newAlias + (fxPair.m_frameB ? fxPair.m_frameB->getAlias(
                                                 it->first, m_renderSettings)
                                           : "");
    if (newAlias != it->second.m_alias) {
      // Clear the remaining frame infos
      it->second.m_renderedRegion = QRegion();
    }
  }
}
updateAliasKeyword()
void Previewer::Imp::updateAliasKeyword (const std::string & keyword)
{
  std::map<int, FrameInfo>::iterator it;
  for (it = m_frames.begin(); it != m_frames.end(); ++it) {
    if (it->second.m_alias.find(keyword) != std::string::npos) {
      TFxPair fxPair     = buildSceneFx(it->first);
      it->second.m_alias = fxPair.m_frameA ? fxPair.m_frameA->getAlias(
                                                 it->first, m_renderSettings)
                                           : "";
      it->second.m_alias = it->second.m_alias +
                           (fxPair.m_frameB ? fxPair.m_frameB->getAlias(
                                                  it->first, m_renderSettings)
                                            : "");
      // Clear the remaining frame infos
      it->second.m_renderedRegion = QRegion();
      // No need to release the cached image... eventually, clear it
      TRasterImageP ri = TImageCache::instance()->get(
          m_cachePrefix + std::to_string(it->first), true);
      if (ri) ri->getRaster()->clear();
    }
  }
}
updateCamera()
void Previewer::Imp::updateCamera ()
{
  // Retrieve current camera
  TCamera *currCamera =
      TApp::instance()->getCurrentScene()->getScene()->getCurrentCamera();
  TRect subCameraRect = currCamera->getInterestRect();
  TPointD cameraPos(-0.5 * currCamera->getRes().lx,
                    -0.5 * currCamera->getRes().ly);
  // Update the camera region and camera stage area
  TDimension cameraRes(0, 0);
  TRectD renderArea;
  if (m_subcamera && subCameraRect.getLx() > 0 && subCameraRect.getLy() > 0) {
    cameraRes  = TDimension(subCameraRect.getLx(), subCameraRect.getLy());
    renderArea = TRectD(subCameraRect.x0, subCameraRect.y0,
                        subCameraRect.x1 + 1, subCameraRect.y1 + 1) +
                 cameraPos;
  } else {
    cameraRes  = currCamera->getRes();
    renderArea = TRectD(cameraPos, TDimensionD(cameraRes.lx, cameraRes.ly));
  }
  // Add the shrink to camera res
  cameraRes.lx /= m_renderSettings.m_shrinkX;
  cameraRes.ly /= m_renderSettings.m_shrinkY;
  // Invalidate the old camera size
  if (m_cameraRes != cameraRes || m_renderArea != renderArea) {
    m_cameraRes  = cameraRes;
    m_renderArea = renderArea;
    m_cameraPos  = cameraPos;
    // All previously rendered frames must be erased
    std::map<int, FrameInfo>::iterator it;
    for (it = m_frames.begin(); it != m_frames.end(); ++it)
      TImageCache::instance()->remove(m_cachePrefix +
                                      std::to_string(it->first));
    m_frames.clear();
  }
}
updateFrameRange()
void Previewer::Imp::updateFrameRange ()
{
  // Erase all rendered frames outside the new frame range
  int newFrameCount =
      TApp::instance()->getCurrentScene()->getScene()->getFrameCount();
  std::map<int, FrameInfo>::iterator it,
      jt = m_frames.lower_bound(newFrameCount);
  for (it = jt; it != m_frames.end(); ++it)
    // Release all associated cached images
    TImageCache::instance()->remove(m_cachePrefix + std::to_string(it->first));
  m_frames.erase(jt, m_frames.end());
  // Resize the progress bar status
  int i, oldSize = m_pbStatus.size();
  m_pbStatus.resize(newFrameCount);
  for (i = oldSize; i < newFrameCount; ++i)
    m_pbStatus[i] = FlipSlider::PBFrameNotStarted;
}
updatePreviewRect()
void Previewer::Imp::updatePreviewRect ()
{
  TRectD previewRectD;
  /*--
   * SubCameraPreviewViewer
   * --*/
  if (!m_subcamera)
    previewRectD = m_renderArea;
  else {
    // Retrieve the view rects from each listener. Their union will form the
    // rect to be rendered.
    std::set<Previewer::Listener *>::iterator it;
    for (it = m_listeners.begin(); it != m_listeners.end(); ++it) {
      // Retrieve the listener's viewRect and add it to the preview rect
      previewRectD += (*it)->getPreviewRect();
    }
  }
  previewRectD *= m_renderArea;
  int shrinkX = m_renderSettings.m_shrinkX;
  int shrinkY = m_renderSettings.m_shrinkY;
  // Ensure that rect has the same pixel geometry as the preview camera
  previewRectD -= m_cameraPos;
  previewRectD.x0 = previewRectD.x0 / shrinkX;
  previewRectD.y0 = previewRectD.y0 / shrinkY;
  previewRectD.x1 = previewRectD.x1 / shrinkX;
  previewRectD.y1 = previewRectD.y1 / shrinkY;
  // Now, pass to m_cameraRes-relative coordinates
  TPointD shrinkedRelPos((m_renderArea.x0 - m_cameraPos.x) / shrinkX,
                         (m_renderArea.y0 - m_cameraPos.y) / shrinkY);
  previewRectD -= shrinkedRelPos;
  previewRectD.x0 = tfloor(previewRectD.x0);
  previewRectD.y0 = tfloor(previewRectD.y0);
  previewRectD.x1 = tceil(previewRectD.x1);
  previewRectD.y1 = tceil(previewRectD.y1);
  m_previewRect = TRect(previewRectD.x0, previewRectD.y0, previewRectD.x1 - 1,
                        previewRectD.y1 - 1);
  previewRectD += m_cameraPos + shrinkedRelPos;
  setRenderArea(previewRectD);
}
updateProgressBarStatus()
void Previewer::Imp::updateProgressBarStatus ()
{
  unsigned int i, pbSize = m_pbStatus.size();
  std::map<int, FrameInfo>::iterator it;
  for (i = 0; i < pbSize; ++i) {
    it = m_frames.find(i);
    m_pbStatus[i] =
        (it == m_frames.end())
            ? FlipSlider::PBFrameNotStarted
            : ::contains(it->second.m_renderedRegion, m_previewRect)
                  ? FlipSlider::PBFrameFinished
                  : it->second.m_rectUnderRender.contains(m_previewRect)
                        ? FlipSlider::PBFrameStarted
                        : FlipSlider::PBFrameNotStarted;
  }
}
updateRenderSettings()
void Previewer::Imp::updateRenderSettings ()
{
  ToonzScene *scene = TApp::instance()->getCurrentScene()->getScene();
  TRenderSettings renderSettings =
      scene->getProperties()->getPreviewProperties()->getRenderSettings();
  if (renderSettings.m_applyShrinkToViewer)
    renderSettings.m_shrinkY = renderSettings.m_shrinkX;
  else
    renderSettings.m_shrinkY = renderSettings.m_shrinkX = 1;
  // In case the settings changed, erase all previously cached images
  if (renderSettings != m_renderSettings) {
    m_renderSettings = renderSettings;
    std::map<int, FrameInfo>::iterator it;
    for (it = m_frames.begin(); it != m_frames.end(); ++it)
      TImageCache::instance()->remove(m_cachePrefix +
                                      std::to_string(it->first));
    m_frames.clear();
  }
}
Member Data Documentation
m_cachePrefix
std::string Previewer::Imp::m_cachePrefix
m_cameraPos
TPointD Previewer::Imp::m_cameraPos
m_cameraRes
TDimension Previewer::Imp::m_cameraRes
m_computingFrameCount
int Previewer::Imp::m_computingFrameCount
m_currentFrameToSave
int Previewer::Imp::m_currentFrameToSave
m_frames
std::map<int, FrameInfo> Previewer::Imp::m_frames
m_listeners
std::set<Previewer::Listener *> Previewer::Imp::m_listeners
m_lw
TLevelWriterP Previewer::Imp::m_lw
m_mutex
TThread::Mutex Previewer::Imp::m_mutex
m_owner
Previewer* Previewer::Imp::m_owner
m_pbStatus
std::vector<UCHAR> Previewer::Imp::m_pbStatus
m_previewRect
TRect Previewer::Imp::m_previewRect
m_renderArea
TRectD Previewer::Imp::m_renderArea
m_renderer
TRenderer Previewer::Imp::m_renderer
m_renderSettings
TRenderSettings Previewer::Imp::m_renderSettings
m_subcamera
bool Previewer::Imp::m_subcamera
The documentation for this class was generated from the following file:
E:/opentoonz/toonz/sources/toonz/previewer.cpp