opentoonz: PalettesScanPopup Class Reference
PalettesScanPopup Class Reference final
The PalettesScanPopup class provides a modal dialog to import palette in StudioPalette folder.
Public Member Functions
void setCurrentFolder (TFilePath path)
TFilePath getCurrentFolder ()
Public Member Functions inherited from DVGui::Dialog
Dialog (QWidget *parent=0, bool hasButton=false, bool hasFixedSize=true, const QString &name=QString())
void beginVLayout ()
void endVLayout ()
void beginHLayout ()
void endHLayout ()
void addWidget (QWidget *widget, bool isRight=true)
void addWidgets (QWidget *firstW, QWidget *secondW)
void addWidget (QString labelName, QWidget *widget)
void addLayout (QLayout *layout, bool isRight=true)
void addWidgetLayout (QWidget *widget, QLayout *layout)
void addLayout (QString labelName, QLayout *layout)
void addLayouts (QLayout *firstL, QLayout *secondL)
void addSpacing (int spacing)
void addSeparator (QString name=QString())
void setAlignment (Qt::Alignment alignment)
void setTopMargin (int margin)
void setTopSpacing (int spacing)
void setLabelWidth (int labelWidth)
int getLabelWidth () const
void setLayoutInsertedSpacing (int spacing)
int getLayoutInsertedSpacing ()
void setButtonBarMargin (int margin)
void setButtonBarSpacing (int spacing)
void addButtonBarWidget (QWidget *widget)
void addButtonBarWidget (QWidget *first, QWidget *second)
void addButtonBarWidget (QWidget *first, QWidget *second, QWidget *third)
void addButtonBarWidget (QWidget *first, QWidget *second, QWidget *third, QWidget *fourth)
void hideEvent (QHideEvent *event) override
void clearButtonBar ()
Protected Slots
void onOkBtnClicked ()
Protected Member Functions
void setLabel (const TFilePath &fp)
void timerEvent (QTimerEvent *event) override
void push (const TFilePath &fp)
void push (const TFilePathSet &fs)
void pop ()
bool step ()
void clearStack ()
void onPlt (const TFilePath &fp)
Protected Member Functions inherited from DVGui::Dialog
void resizeEvent (QResizeEvent *e) override
Additional Inherited Members
Signals inherited from DVGui::Dialog
void dialogClosed ()
Public Attributes inherited from DVGui::Dialog
QVBoxLayout * m_topLayout
QFrame * m_mainFrame
QFrame * m_buttonFrame
QHBoxLayout * m_mainHLayout
bool m_isMainHLayout
QVBoxLayout * m_leftVLayout
QVBoxLayout * m_rightVLayout
bool m_isMainVLayout
int m_layoutSpacing
int m_layoutMargin
int m_labelWidth
std::vector< QWidget * > m_buttonBarWidgets
Protected Attributes inherited from DVGui::Dialog
QHBoxLayout * m_buttonLayout
QList< QLabel * > m_labelList
Detailed Description
The PalettesScanPopup class provides a modal dialog to import palette in StudioPalette folder.
Inherits Dialog. This object is composed of three sub-object: a FileField to choose a folder, a label QLabel, generally empty, to show palette folder during them import, and a button bar to start import or cancel command.
The class provides a method, setCurrentFolder(TFilePath path), to set folder wherein import palettes. Protected function allows to manage palette import.
Constructor & Destructor Documentation
PalettesScanPopup()
PalettesScanPopup::PalettesScanPopup ()
    : Dialog(0, true, true, "PalettesScan")
    , m_folderPath(TFilePath())
    , m_timerId(0) {
  setWindowTitle(tr("Search for Palettes"));
  setFixedWidth(250);
  m_field = new DVGui::FileField();
  addWidget(m_field);
  m_label = new QLabel();
  m_label->setFixedWidth(200);
  addWidget(m_label);
  QPushButton *okBtn = new QPushButton(tr("Ok"), this);
  okBtn->setDefault(true);
  QPushButton *cancelBtn = new QPushButton(tr("Cancel"), this);
  connect(okBtn, SIGNAL(clicked()), this, SLOT(onOkBtnClicked()));
  connect(cancelBtn, SIGNAL(clicked()), this, SLOT(reject()));
  addButtonBarWidget(okBtn, cancelBtn);
}
Member Function Documentation
clearStack()
void PalettesScanPopup::clearStack () protected
Resets the content of the directories stack and set label text empty.
{
  for (int i = 0; i < (int)m_stack.size(); i++) delete m_stack[i];
  m_stack.clear();
  m_label->setText(tr(""));
}
Referenced by timerEvent().
getCurrentFolder()
TFilePath PalettesScanPopup::getCurrentFolder ()
Return current folder path.
{ return m_folderPath; }
onOkBtnClicked
void PalettesScanPopup::onOkBtnClicked () protected slot
Start palette import. Add FileField path to directories stack and start a timer.
{
  m_timerId = startTimer(3);
  TFilePathSet fps;
  std::wstring s = m_field->getPath().toStdWString();
  int i = 0, len = s.length();
  while (i < len) {
    while (i < len && (s[i] == ' ' || s[i] == '\t')) i++;
    if (i >= len) break;
    int j = i;
    while (j < len && s[j] != ',') j++;
    int k = j;
    while (k > i && (s[k - 1] == ' ' || s[k - 1] == '\t')) k--;
    std::wstring token = s.substr(i, k - i);
    fps.push_back(TFilePath(token));
    i = j + 1;
  }
  push(fps);
}
References push().
onPlt()
void PalettesScanPopup::onPlt (const TFilePath & fp) protected
Import palette, defined in path fp, in current StudioPalette folder.
{
  TFilePath root(m_field->getPath().toStdString());
  assert(root.isAncestorOf(fp));
  TFilePath q = fp.getParentDir() - root;
  try {
    StudioPalette::instance()->importPalette(m_folderPath + q, fp);
  } catch (TSystemException &se) {
    DVGui::warning(QString::fromStdWString(se.getMessage()));
  } catch (...) {
    DVGui::warning(QString::fromStdWString(fp.getWideString() + L"\n") +
                   tr("Failed to import palette."));
  }
}
References TFilePath::getParentDir().
Referenced by step().
pop()
void PalettesScanPopup::pop () protected
Removes the top item from the stack. If stack is empty return immediately.
{
  if (m_stack.empty()) return;
  Directory *dir = m_stack.back();
  delete dir;
  m_stack.pop_back();
  if (!m_stack.empty()) {
    dir = m_stack.back();
    setLabel(dir->m_path);
  } else
    m_label->setText(tr(""));
}
References setLabel().
Referenced by step().
push() [1/2]
void PalettesScanPopup::push (const TFilePath & fp) protected
Push TFilePath fp to the top of directories stack. Set label text to fp.
{
  setLabel(fp);
  Directory *dir = new Directory();
  m_stack.push_back(dir);
  dir->m_path  = fp;
  dir->m_files = TSystem::readDirectory(fp);
  dir->m_it    = dir->m_files.begin();
}
References setLabel().
Referenced by onOkBtnClicked(), and step().
push() [2/2]
void PalettesScanPopup::push (const TFilePathSet & fs) protected
Push TFilePathSet fs to the top of directories stack. Set label text to "<files>".
{
  m_label->setText(tr("<files>"));
  Directory *dir = new Directory();
  m_stack.push_back(dir);
  dir->m_path  = TFilePath();
  dir->m_files = fs;
  dir->m_it    = dir->m_files.begin();
}
setCurrentFolder()
void PalettesScanPopup::setCurrentFolder (TFilePath path)
Set current folder path to path.
{
  m_folderPath = path;
}
Referenced by StudioPaletteTreeViewer::searchForPalette(), and StudioPaletteTreeViewer::searchForPlt().
setLabel()
void PalettesScanPopup::setLabel (const TFilePath & fp) protected
Set label text to path fp.
{
  QString elideStr =
      elideText(toQString(fp), m_label->font(), m_label->width());
  m_label->setText(elideStr);
}
Referenced by pop(), push(), and step().
step()
bool PalettesScanPopup::step () protected
Return true if directories stack is not empty; otherwise return false.
If stack is not empty check current directory:
if all files are checked recall pop();
if its path is a directory recall push(const TFilePath &fp);
if its path is a file check its extension and recall onPlt(const TFilePath &fp).
{
  if (m_stack.empty()) return false;
  Directory *dir = m_stack.back();
  if (dir->m_it == dir->m_files.end())
    pop();
  else {
    TFilePath fp = *(dir->m_it)++;
    if (TFileStatus(fp).isDirectory())
      push(fp);
    else {
      setLabel(fp);
      std::string ext = fp.getType();
      if (ext == "plt" || ext == "tpl" || ext == "pli") onPlt(fp);
    }
  }
  return true;
}
References TFilePath::getType(), onPlt(), pop(), push(), and setLabel().
Referenced by timerEvent().
timerEvent()
void PalettesScanPopup::timerEvent (QTimerEvent * event) override protected
Proceed in palette import recalling step(); if step() return false stop timer, clear directories stack, and close popup sending accept event.
{
  bool ret = step();
  if (!ret) {
    killTimer(m_timerId);
    clearStack();
    QDialog::accept();
  }
}
References clearStack(), and step().
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/toonzqt/palettesscanpopup.h
E:/opentoonz/toonz/sources/toonzqt/palettesscanpopup.cpp