opentoonz: TCacheResource Class Reference
TCacheResource Class Reference
#include <tcacheresource.h>
Public Types
enum Type { NONE , RGBM32 , RGBM64 , CM32 }
Public Member Functions
const std::string & getName () const
QMutex * getMutex ()
int getRasterType () const
TRasterP buildCompatibleRaster (const TDimension &size)
QRegion getAvailableRegion () const
bool upload (const TPoint &pos, TRasterP ras)
bool upload (const TTile &tile)
QRegion download (const TPoint &pos, TRasterP ras)
QRegion download (TTile &tile)
bool downloadAll (const TPoint &pos, TRasterP ras)
bool downloadAll (TTile &tile)
bool uploadPalette (TPaletteP palette)
void downloadPalette (TPaletteP &palette)
void clear (QRegion region)
bool canUpload (const TTile &tile) const
bool canDownloadSome (const TTile &tile) const
bool canDownloadAll (const TTile &tile) const
bool canUpload (int rasType) const
bool canDownloadSome (const TRect &rect) const
bool canDownloadAll (const TRect &rect) const
void addRef2 (const TRect &rect)
void release2 (const TRect &rect)
void addLock ()
void releaseLock ()
int size () const
Returns the current size, in MB, of the cache resource.
void enableBackup ()
void invalidate ()
void save (const TFilePath &fp)
Friends
class TCacheResourcePool
class THDCacheResourcePool
class TCacheResourceP
Detailed Description
The TCacheResource class models generic tile objects suitable for caching in render processes.
Whereas common TTile instances can be used to represent images bounded on a specific rect of the plane, the caching procedures in a render process require certain generalizations of the tile model that are fulfilled by the TCacheResource class:
A cache resource has a textual description of its content that we'll call 'name'. It is the associative key used to retrieve a resource among all the others stored in the cache. <
> The spatial domain of a cache resource is the entire plane, meaning that access methods are not bound to work on a specific rect. This is necessary since the image data accessed on non-consecutive renders could cover sparse regions of the plane. <
> For simplicity, the pixel geometry of a cache is coherent to the plane origin - that is, pixel corners always have integer coordinates. <
> Filled resources have a raster type < >, specifying the type of rasters that are currently storing. It is forbidden to upload rasters to resources when their raster type differs. Empty resources are compatible to all possible raster types. <
> Cache resources provide reference counters to either the entire resource and each piece of its internal memory model, in order to perform automatic release of unnecessary data. <
> The resource provides an accessible resume of its currently filled areas, in the form of a QRegion. <
>
In order to use or retrieve a cache resource, users must instantiate a smart pointer reference to the resource, providing its name. Please refer to the TCacheResourceP documentation for this topic.
See also
TRaster, TTile classes.
Member Enumeration Documentation
Type
enum TCacheResource::Type
{ NONE, RGBM32, RGBM64, CM32 };
Member Function Documentation
addLock()
void TCacheResource::addLock ()
{
  // DIAGNOSTICS_NUMBEREDSTR(prefix + QString::number((UINT) this) + " | Stack |
  // ",
  //"crStack", "addLock");
  ++m_locksCount;
}
addRef2()
void TCacheResource::addRef2 (const TRect & rect)
{
  // DIAGNOSTICS_NUMBEREDSTRSET(prefix + QString::number((UINT) this) + " |
  // Stack | ",
  //"crStack", "addRef", ::traduce(rect));
  // Add a reference to all cells intersecting the passed one
  TPoint initialPos(getCellPos(rect.getP00()));
  TPoint pos;
  for (pos.x = initialPos.x; pos.x <= rect.x1; pos.x += latticeStep)
    for (pos.y = initialPos.y; pos.y <= rect.y1; pos.y += latticeStep) {
      PointLess cellIndex(getCellIndex(pos));
      CellData &cellData    = m_cellDatas[cellIndex];
      cellData.m_referenced = true;
      cellData.m_refsCount++;
    }
}
buildCompatibleRaster()
TRasterP TCacheResource::buildCompatibleRaster (const TDimension & size)
{
  TRasterP result;
  if (m_tileType == RGBM32)
    result = TRaster32P(size);
  else if (m_tileType == RGBM64)
    result = TRaster64P(size);
  else if (m_tileType == CM32)
    result = TRasterCM32P(size);
  return result;
}
canDownloadAll() [1/2]
bool TCacheResource::canDownloadAll (const TRect & rect) const
{
  return contains(m_region, rect);
}
canDownloadAll() [2/2]
bool TCacheResource::canDownloadAll (const TTile & tile) const
Returns true if the passed tile is compatible, and it can be downloaded entirely.
{
  return checkTile(tile) && contains(m_region, getTileRect(tile));
}
canDownloadSome() [1/2]
bool TCacheResource::canDownloadSome (const TRect & rect) const
{
  return m_region.intersects(toQRect(rect));
}
canDownloadSome() [2/2]
bool TCacheResource::canDownloadSome (const TTile & tile) const
Returns true if the passed tile is compatible with the complex, and some part of it is downloadable.
{
  return checkTile(tile) && m_region.intersects(toQRect(getTileRect(tile)));
}
canUpload() [1/2]
bool TCacheResource::canUpload (const TTile & tile) const
{
  int tileType;
  return checkTile(tile) && checkRasterType(tile.getRaster(), tileType);
}
canUpload() [2/2]
bool TCacheResource::canUpload (int rasType) const inline
{
    return m_tileType == NONE || m_tileType == rasType;
  }
clear()
void TCacheResource::clear (QRegion region)
Clears the complex on the specified region. Please observe that the actually cleared region consists of all lattice cells intersecting the passed region, therefore resulting in a cleared region typically larger than passed one, up to the lattice granularity.
{
  if (!m_region.intersects(region)) return;
  // Get the region bbox
  TRect bbox(toTRect(region.boundingRect()));
  // For all cells intersecting the bbox
  TPoint initialPos(getCellPos(bbox.getP00()));
  TPoint pos;
  for (pos.x = initialPos.x; pos.x <= bbox.x1; pos.x += latticeStep)
    for (pos.y = initialPos.y; pos.y <= bbox.y1; pos.y += latticeStep) {
      QRect cellQRect(
          toQRect(TRect(pos, TDimension(latticeStep, latticeStep))));
      if (region.intersects(cellQRect) && m_region.intersects(cellQRect)) {
        // Release the associated cell from cache and clear the cell from the
        // content region.
        TImageCache::instance()->remove(getCellCacheId(pos));
        m_region -= cellQRect;
        --m_cellsCount;
        // DIAGNOSTICS_GLOADD("crCellsCnt", -1);
        // Release the cell from m_cellDatas
        m_cellDatas[getCellIndex(pos)].m_modified = true;
      }
    }
  if (m_region.isEmpty()) {
    m_tileType   = NONE;
    m_locksCount = 0;
  }
}
References clear(), and TImageCache::remove().
Referenced by clear().
download() [1/2]
QRegion TCacheResource::download (const TPoint & pos, TRasterP ras)
Fills the passed tile with the data contained in the complex, returning the copied region. The same restriction of the upload() method applies here.
{
  int tileType;
  if (!checkRasterType(ras, tileType)) return QRegion();
  // Build the tile's rect
  TRect tileRect(ras->getBounds() + pos);
  if (!m_region.intersects(toQRect(tileRect))) return QRegion();
  // For all cells intersecting the tile's rect, copy all those intersecting the
  // complex's content region.
  TPoint initialPos(getCellPos(tileRect.getP00()));
  TPoint currPos;
  for (currPos.x = initialPos.x; currPos.x <= tileRect.x1;
       currPos.x += latticeStep)
    for (currPos.y = initialPos.y; currPos.y <= tileRect.y1;
         currPos.y += latticeStep) {
      TRect cellRect(currPos, TDimension(latticeStep, latticeStep));
      TRect overlapRect(tileRect * cellRect);
      assert(!overlapRect.isEmpty());
      QRect overlapQRect(toQRect(overlapRect));
      if (m_region.intersects(overlapQRect)) {
        // Extract the associated rasters and perform the copy to the input
        // tile.
        std::pair<TRasterP, CellData *> cellInfos(touch(getCellIndex(currPos)));
        TRasterP cellRas(cellInfos.first);
        TRect temp(overlapRect - currPos);
        TRasterP overlappingCellRas(cellRas->extract(temp));
        temp = TRect(overlapRect - tileRect.getP00());
        TRasterP overlappingTileRas(ras->extract(temp));
        TRop::copy(overlappingTileRas, overlappingCellRas);
      }
    }
  return m_region.intersected(QRegion(toQRect(tileRect)));
}
References TRop::copy(), and TRectT< T >::isEmpty().
download() [2/2]
QRegion TCacheResource::download (TTile & tile)
{
  if (!checkTile(tile)) return QRegion();
  return download(TPoint(tile.m_pos.x, tile.m_pos.y), tile.getRaster());
}
downloadAll() [1/2]
bool TCacheResource::downloadAll (const TPoint & pos, TRasterP ras)
{
  int tileType;
  if (!checkRasterType(ras, tileType)) return false;
  // Build the tile's rect
  TRect tileRect(ras->getBounds() + pos);
  if (!contains(m_region, tileRect)) return false;
  // DIAGNOSTICS_NUMBEREDSTRSET(prefix + QString::number((UINT) this) + " |
  // Stack | ",
  //"crStack", "downloadAll", ::traduce(TRect(pos, ras->getSize())));
  // For all cells intersecting the tile's rect, copy all those intersecting the
  // complex's content region.
  TPoint initialPos(getCellPos(tileRect.getP00()));
  TPoint currPos;
  for (currPos.x = initialPos.x; currPos.x <= tileRect.x1;
       currPos.x += latticeStep)
    for (currPos.y = initialPos.y; currPos.y <= tileRect.y1;
         currPos.y += latticeStep) {
      TRect cellRect(currPos, TDimension(latticeStep, latticeStep));
      TRect overlapRect(tileRect * cellRect);
      assert(!overlapRect.isEmpty());
      QRect overlapQRect(toQRect(overlapRect));
      if (m_region.intersects(overlapQRect)) {
        // Extract the associated rasters and perform the copy to the input
        // tile.
        std::pair<TRasterP, CellData *> cellInfos(touch(getCellIndex(currPos)));
        TRasterP cellRas(cellInfos.first);
        TRect temp(overlapRect - currPos);
        TRasterP overlappingCellRas(cellRas->extract(temp));
        temp = TRect(overlapRect - tileRect.getP00());
        TRasterP overlappingTileRas(ras->extract(temp));
        TRop::copy(overlappingTileRas, overlappingCellRas);
      }
    }
  return true;
}
downloadAll() [2/2]
bool TCacheResource::downloadAll (TTile & tile)
{
  if (!checkTile(tile)) return false;
  return downloadAll(TPoint(tile.m_pos.x, tile.m_pos.y), tile.getRaster());
}
downloadPalette()
void TCacheResource::downloadPalette (TPaletteP & palette)
{
  palette = m_palette;
}
enableBackup()
void TCacheResource::enableBackup ()
{
  if (m_backEnabled) return;
  TCacheResourcePool::instance()->startBacking(this);
}
getAvailableRegion()
QRegion TCacheResource::getAvailableRegion () const inline
Returns the current region currently available in the complex, with respect to the complex's origin.
{ return m_region; }
getMutex()
QMutex * TCacheResource::getMutex () inline
{ return &m_mutex; }
getName()
const std::string & TCacheResource::getName () const inline
{ return m_pos->first; }
getRasterType()
int TCacheResource::getRasterType () const inline
Returns the type of raster currently present in the tile complex. Only images providing a raster representation coherent with the complex's one may be exchanged with it.
{ return m_tileType; }
invalidate()
void TCacheResource::invalidate ()
{ m_invalidated = true; }
release2()
void TCacheResource::release2 (const TRect & rect)
{
  // DIAGNOSTICS_NUMBEREDSTRSET(prefix + QString::number((UINT) this) + " |
  // Stack | ",
  //"crStack", "release", ::traduce(rect));
  if (m_locksCount > 0) return;
  std::map<PointLess, CellData>::iterator it;
  for (it = m_cellDatas.begin(); it != m_cellDatas.end();) {
    if (!it->second.m_referenced) {
      ++it;
      continue;
    }
    TPoint cellPos(getCellPos(it->first));
    TRect cellRect(cellPos, TDimension(latticeStep, latticeStep));
    if (isEmpty(cellRect * rect)) {
      ++it;
      continue;
    }
    QRect cellQRect(toQRect(cellRect));
    if (--it->second.m_refsCount <= 0) {
      releaseCell(cellQRect, it->first, it->second.m_modified);
      std::map<PointLess, CellData>::iterator jt = it++;
      m_cellDatas.erase(jt);
    } else
      ++it;
  }
}
releaseLock()
void TCacheResource::releaseLock ()
{
  // DIAGNOSTICS_NUMBEREDSTR(prefix + QString::number((UINT) this) + " | Stack |
  // ",
  //"crStack", "releaseLock");
  m_locksCount = std::max(m_locksCount - 1, 0);
  if (m_locksCount > 0) return;
  // Check for released cells
  std::map<PointLess, CellData>::iterator it;
  for (it = m_cellDatas.begin(); it != m_cellDatas.end();)
    if (it->second.m_referenced) {
      TPoint cellPos(getCellPos(it->first));
      QRect cellQRect(cellPos.x, cellPos.y, latticeStep, latticeStep);
      releaseCell(cellQRect, it->first, it->second.m_modified);
      std::map<PointLess, CellData>::iterator jt = it++;
      m_cellDatas.erase(jt);
    } else
      ++it;
}
save()
void TCacheResource::save (const TFilePath & fp)
{
  assert(!fp.isEmpty());
  std::map<PointLess, CellData>::iterator it;
  for (it = m_cellDatas.begin(); it != m_cellDatas.end(); ++it) {
    TRasterP cellRas = getRaster(TImageCache::instance()->get(
        getCellCacheId(it->first.x, it->first.y), false));
    assert(m_tileType != NONE);
    TFilePath cellFp(fp + TFilePath(getCellName(it->first.x, it->first.y)));
    if (m_tileType == CM32)
      ::saveCompressed(cellFp, cellRas);
    else
      TImageWriter::save(cellFp.withType(".tif"), cellRas);
  }
}
size()
int TCacheResource::size () const
Returns the current size, in MB, of the cache resource.
{
  // NOTE: It's better to store the size incrementally. This complies
  // with the possibility of specifying a bbox to fit the stored cells to...
  return m_tileType == NONE ? 0
                            : m_tileType == RGBM64 ? (m_cellsCount << 11)
                                                   : (m_cellsCount << 10);
}
upload() [1/2]
bool TCacheResource::upload (const TPoint & pos, TRasterP ras)
Copies the passed tile in the tile complex. The passed tile must possess integer geometry (ie tile.m_pos must have integer coordinates), otherwise this function is a no-op.
{
  int tileType;
  if (!checkRasterType(ras, tileType)) return false;
  if (m_tileType == NONE) m_tileType = tileType;
  // For all cells of the lattice which intersect the tile, upload the content
  // in the
  // complex
  TRect tileRect(ras->getBounds() + pos);
  TPoint initialPos(getCellPos(tileRect.getP00()));
  // DIAGNOSTICS_NUMBEREDSTRSET(prefix + QString::number((UINT) this) + " |
  // Stack | ",
  //"crStack", "upload", ::traduce(TRect(pos, ras->getSize())));
  TPoint currPos;
  for (currPos.x = initialPos.x; currPos.x <= tileRect.x1;
       currPos.x += latticeStep)
    for (currPos.y = initialPos.y; currPos.y <= tileRect.y1;
         currPos.y += latticeStep) {
      // Copy tile's content into the cell's raster.
      TRect cellRect(currPos, TDimension(latticeStep, latticeStep));
      TRect overlapRect(tileRect * cellRect);
      assert(!overlapRect.isEmpty());
      PointLess cellIndex(getCellIndex(currPos));
      std::pair<TRasterP, CellData *> cellInfos(touch(cellIndex));
      TRasterP cellRas(cellInfos.first);
      TRect temp(overlapRect - currPos);
      TRasterP overlappingCellRas(cellRas->extract(temp));
      temp = TRect(overlapRect - tileRect.getP00());
      TRasterP overlappingTileRas(ras->extract(temp));
      assert(overlappingCellRas->getBounds() ==
             overlappingTileRas->getBounds());
      TRop::copy(overlappingCellRas, overlappingTileRas);
      cellInfos.second->m_modified = true;
    }
  // Update the complex's content region
  m_region += toQRect(tileRect);
  return true;
}
References TRop::copy(), and TRectT< T >::isEmpty().
upload() [2/2]
bool TCacheResource::upload (const TTile & tile)
{
  if (!checkTile(tile)) return false;
  return upload(TPoint(tile.m_pos.x, tile.m_pos.y), tile.getRaster());
}
uploadPalette()
bool TCacheResource::uploadPalette (TPaletteP palette)
{
  if (m_tileType == NONE) m_tileType = CM32;
  if (m_tileType != CM32) {
    assert(!"The resource already holds a non-colormap content!");
    return false;
  }
  m_palette = palette;
  return true;
}
Friends And Related Function Documentation
TCacheResourceP
friend class TCacheResourceP friend
TCacheResourcePool
friend class TCacheResourcePool friend
THDCacheResourcePool
friend class THDCacheResourcePool friend
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/tcacheresource.h
E:/opentoonz/toonz/sources/common/tfx/tcacheresource.cpp