opentoonz: SchematicNode Class Reference
SchematicNode Class Reference abstract
The class provides methods to draw and handle a node item in the SchematicScene.
#include "../include/toonzqt/schematicnode.h"
Signals
void sceneChanged ()
void xsheetChanged ()
void nodeChangedSize ()
Public Member Functions
SchematicNode (SchematicScene *scene)
QRectF boundingRect () const override
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=0) override
SchematicPort * addPort (int portId, SchematicPort *port)
void erasePort (int portId)
SchematicPort * getPort (int portId) const
QList< SchematicNode * > getLinkedNodes (int portId) const
virtual void setSchematicNodePos (const QPointF &pos) const =0
virtual void setPosition (const QPointF &newPos)=0
void updateLinksGeometry ()
virtual void onClicked ()
Protected Member Functions
void mouseMoveEvent (QGraphicsSceneMouseEvent *me) override
void mousePressEvent (QGraphicsSceneMouseEvent *me) override
void mouseReleaseEvent (QGraphicsSceneMouseEvent *me) override
Protected Attributes
SchematicScene * m_scene
qreal m_width
qreal m_height
Qt::MouseButton m_buttonState
QMap< int, SchematicPort * > m_ports
Detailed Description
The class provides methods to draw and handle a node item in the SchematicScene.
Constructor & Destructor Documentation
SchematicNode()
SchematicNode::SchematicNode (SchematicScene * scene)
    : QGraphicsItem(0)
#else
    : QGraphicsItem(0, scene)
#endif
    , m_scene(scene)
    , m_width(0)
    , m_height(0)
    , m_buttonState(Qt::NoButton) {
#if QT_VERSION >= 0x050000
  scene->addItem(this);
#endif
  setFlag(QGraphicsItem::ItemIsMovable, false);
  setFlag(QGraphicsItem::ItemIsSelectable, true);
  setFlag(QGraphicsItem::ItemIsFocusable, false);
  setZValue(1.0);
}
~SchematicNode()
SchematicNode::~SchematicNode ()
{}
Member Function Documentation
addPort()
SchematicPort * SchematicNode::addPort (int portId, SchematicPort * port)
{
  QMap<int, SchematicPort *>::iterator it;
  it = m_ports.find(portId);
  if (it != m_ports.end() && m_ports[portId] != port) {
    SchematicPort *oldPort = m_ports[portId];
    m_ports.erase(it);
    scene()->removeItem(oldPort);
    delete oldPort;
  }
  m_ports[portId] = port;
  return port;
}
boundingRect()
QRectF SchematicNode::boundingRect () const override
Reimplements the pure virtual QGraphicsItem::boundingRect() method.
{ return QRectF(0, 0, 1, 1); }
Referenced by SchematicScene::getPlacedNode(), and SchematicScene::isAnEmptyZone().
erasePort()
void SchematicNode::erasePort (int portId)
Erase the pair (portId, SchematicPort*port) from the mapping
{
  QMap<int, SchematicPort *>::iterator it = m_ports.find(portId);
  if (it != m_ports.end()) {
    delete it.value();
    m_ports.erase(it);
  }
}
getLinkedNodes()
QList< SchematicNode * > SchematicNode::getLinkedNodes (int portId) const
Returns a list of all node connected by links to a SchematicPort identified by portId.
{
  QList<SchematicNode *> list;
  SchematicPort *port = getPort(portId);
  if (port) {
    int linkCount = port->getLinkCount();
    int i;
    for (i = 0; i < linkCount; i++) list.push_back(port->getLinkedNode(i));
  }
  return list;
}
References SchematicPort::getLinkCount(), SchematicPort::getLinkedNode(), and getPort().
getPort()
SchematicPort * SchematicNode::getPort (int portId) const
Returns a pointer to the SchematicPort mapped from portId.
Returns 0 if portId doesn't map no SchematicPort.
{
  QMap<int, SchematicPort *>::const_iterator it = m_ports.find(portId);
  if (it != m_ports.end()) return it.value();
  return 0;
}
Referenced by getLinkedNodes(), and StageSchematicScene::updateScene().
mouseMoveEvent()
void SchematicNode::mouseMoveEvent (QGraphicsSceneMouseEvent * me) override protected
Reimplements the QGraphicsItem::mouseMoveEvent() method.
{
  QList<QGraphicsItem *> items = scene()->selectedItems();
  if (items.empty()) return;
  QPointF delta         = me->scenePos() - me->lastScenePos();
  QGraphicsView *viewer = scene()->views()[0];
  for (auto const &item : items) {
    SchematicNode *node = dynamic_cast<SchematicNode *>(item);
    if (node) {
      node->setPosition(node->scenePos() + delta);
      node->setSchematicNodePos(node->scenePos());
      node->updateLinksGeometry();
    }
  }
  viewer->setInteractive(false);
  viewer->ensureVisible(QRectF(me->scenePos(), QSizeF(1, 1)), 5, 5);
  viewer->setInteractive(true);
}
mousePressEvent()
void SchematicNode::mousePressEvent (QGraphicsSceneMouseEvent * me) override protected
{
  if (!isSelected()) {
    if (me->modifiers() != Qt::ControlModifier) scene()->clearSelection();
    if (me->button() == Qt::LeftButton || me->button() == Qt::RightButton)
      setSelected(true);
  } else {
    if (me->modifiers() == Qt::ControlModifier &&
        me->button() == Qt::LeftButton)
      setSelected(false);
  }
  onClicked();
}
mouseReleaseEvent()
void SchematicNode::mouseReleaseEvent (QGraphicsSceneMouseEvent * me) override protected
{
  if (me->modifiers() != Qt::ControlModifier && me->button() != Qt::RightButton)
    QGraphicsItem::mouseReleaseEvent(me);
}
onClicked()
virtual void SchematicNode::onClicked () inline virtual
{};
paint()
void SchematicNode::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget = 0) override
Reimplements the pure virtual QGraphicsItem::paint() method.
{
  SchematicViewer *viewer;
  FxSchematicScene *fxScene = dynamic_cast<FxSchematicScene *>(scene());
  StageSchematicScene *stageScene =
      dynamic_cast<StageSchematicScene *>(scene());
  if (fxScene) {
    viewer = fxScene->getSchematicViewer();
  } else if (stageScene) {
    viewer = stageScene->getSchematicViewer();
  } else {
    return;
  }
  QPen pen;
  if (isSelected()) {
    painter->setBrush(QColor(0, 0, 0, 0));
    pen.setColor(QColor(viewer->getSelectedBorderColor()));
    pen.setWidth(4.0);
    pen.setJoinStyle(Qt::RoundJoin);
    painter->setPen(pen);
    painter->drawRect(-2, -2, m_width + 4, m_height + 4);
  }
  pen.setColor(QColor(0, 0, 0, 255));
  pen.setWidth(0);
  painter->setPen(pen);
}
updateLinksGeometry()
void SchematicNode::updateLinksGeometry ()
{
  QMap<int, SchematicPort *>::iterator it;
  for (it = m_ports.begin(); it != m_ports.end(); ++it)
    it.value()->updateLinksGeometry();
}
Member Data Documentation
m_buttonState
Qt::MouseButton SchematicNode::m_buttonState protected
m_height
qreal SchematicNode::m_height protected
m_ports
QMap<int, SchematicPort *> SchematicNode::m_ports protected
m_scene
SchematicScene* SchematicNode::m_scene protected
m_width
qreal SchematicNode::m_width protected
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/toonzqt/schematicnode.h
E:/opentoonz/toonz/sources/toonzqt/schematicnode.cpp