opentoonz: TColorStyle Class Reference
TColorStyle Class Reference abstract
Abstract class representing a color style in a Toonz palette.
#include <tcolorstyles.h>
Classes
struct bool_tag
class Declaration
Helper class to declare color styles.
struct double_tag
struct int_tag
struct PickedPosition
struct TFilePath_tag
Public Types
enum ParamType {
BOOL , INT , ENUM , DOUBLE ,
FILEPATH
}
Public Types inherited from TSmartObject
typedef short ClassCode
Public Member Functions
TColorStyle (const TColorStyle &other)
Copies another style except its icon.
virtual TColorStyle * clone () const =0
Polymorphic clone of the style.
virtual TColorStyle & copy (const TColorStyle &other)
bool operator== (const TColorStyle &cs) const
bool operator!= (const TColorStyle &cs)
virtual TStrokeProp * makeStrokeProp (const TStroke *stroke)=0
virtual TRegionProp * makeRegionProp (const TRegion *region)=0
used to draw the style on the specified stroke object.
virtual bool isRasterStyle () const
used to draw the style on the specified region object.
virtual TRasterStyleFx * getRasterStyleFx ()
virtual bool isRegionStyle () const =0
Returns whether the style applies on regions.
virtual bool isStrokeStyle () const =0
Returns whether the style applies on strokes.
void setName (std::wstring name)
Sets the style's user-defined name.
std::wstring getName () const
Returns the style's user-defined name.
void setGlobalName (std::wstring name)
Sets the global name of the style.
std::wstring getGlobalName () const
Returns the global name of the style.
void setOriginalName (std::wstring name)
If the style is originally copied from studio palette, set this.
std::wstring getOriginalName () const
Returns the original name of the style.
void setIsEditedFlag (bool edited)
bool getIsEditedFlag () const
style is edited from the original one.
void assignNames (const TColorStyle *src)
Copies the style names from src.
unsigned int getFlags () const
Sets color attributes.
void setFlags (unsigned int flags)
Returns color attributes.
void setPickedPosition (const TPoint &pos, const int index=0)
void setPickedPosition (const PickedPosition &pos)
PickedPosition getPickedPosition () const
virtual bool hasMainColor () const
Returns whether the style has a reference main color.
virtual TPixel32 getMainColor () const
Returns the style's main color, or black if none.
virtual void setMainColor (const TPixel32 &color)
Sets the main color, if it has one.
virtual int getColorParamCount () const
Returns the number of colors (if any) of the style.
virtual TPixel32 getColorParamValue (int index) const
Returns the value of the color of index index.
virtual void setColorParamValue (int index, const TPixel32 &color)
Sets the index-th color value.
virtual TPixel32 getAverageColor () const
Returns a color representing the average of all the style's colors.
virtual int getParamCount () const
virtual ParamType getParamType (int paramIdx) const
Returns the type of the specified parameter.
virtual bool hasParamDefault (int index) const
Value of parameter can be reset to default.
virtual void setParamDefault (int index)
Reset value of parameter to default.
virtual bool isParamDefault (int index) const
Check if current value of parameter equals to default.
virtual void setParamValue (int index, bool value)
Assigns a value to the specified bool parameter.
virtual bool getParamValue (bool_tag, int index) const
Retrieves the specified bool parameter value.
virtual void setParamValue (int index, int value)
Assigns a value to the specified int parameter.
virtual int getParamValue (int_tag, int index) const
Retrieves the specified int parameter value.
virtual void getParamRange (int index, int &min, int &max) const
Retrieves the specified int parameter range.
virtual void getParamRange (int pIndex, QStringList &stringItems) const
virtual void setParamValue (int index, double value)
extension value in text form.
virtual double getParamValue (double_tag, int index) const
Retrieves the specified double parameter value.
virtual void getParamRange (int index, double &min, double &max) const
Retrieves the specified double parameter range.
virtual void setParamValue (int index, const TFilePath &fp)
Assigns a value to the specified TFilePath parameter.
virtual TFilePath getParamValue (TFilePath_tag, int index) const
Retrieves the specified TFilePath parameter value.
void assignBlend (const TColorStyle &a, const TColorStyle &b, double t)
virtual QString getDescription () const =0
Return a brief description of the style.
virtual QString getParamNames (int index) const
Return the string that identifies the index-th parameter.
virtual int getTagId () const =0
Returns an unique number representing the style.
virtual void getObsoleteTagIds (std::vector< int > &) const
void save (TOutputStreamInterface &) const
void invalidateIcon ()
Sets a flag that defines the style's icon validity.
virtual const TRaster32P & getIcon (const TDimension &d)
Returns an image representing the style.
bool isEnabled () const
Returns whether the style can be used.
void enable (bool on)
Sets the style's enabled status.
int getVersionNumber () const
Returns the version number of the style.
Public Member Functions inherited from TSmartObject
TSmartObject (ClassCode classCode)
void addRef ()
void release ()
TINT32 getRefCount () const
Static Public Member Functions
static TColorStyle * load (TInputStreamInterface &)
static TColorStyle * create (int tagId)
Creates a new style with identifier equal to tagId.
static void declare (TColorStyle *style)
Puts the style in the table of actual styles.
static void getAllTags (std::vector< int > &tags)
Static Public Member Functions inherited from TSmartObject
static TINT32 getInstanceCount (ClassCode code)
Static Public Attributes
static int m_currentFrame = 0
Protected Member Functions
virtual void makeIcon (const TDimension &d)
virtual void loadData (TInputStreamInterface &)=0
virtual void saveData (TOutputStreamInterface &) const =0
virtual void loadData (int, TInputStreamInterface &)
void updateVersionNumber ()
TColorStyle & operator= (const TColorStyle &other)
Copies another style except its icon.
Protected Attributes
TRaster32P m_icon
Icon shown on TPalette viewers.
bool m_validIcon
Icon's validity status.
Detailed Description
Abstract class representing a color style in a Toonz palette.
Member Enumeration Documentation
ParamType
enum TColorStyle::ParamType
Enumerator
BOOL
Boolean parameter type.
INT
Integer parameter type.
ENUM
Enum parameter type (maps to integer values).
DOUBLE
Double parameter type (getParamType() default).
FILEPATH
TFilePath parameter type.
                 {
    BOOL,
    INT,
    ENUM,
    DOUBLE,
    FILEPATH
  };
Constructor & Destructor Documentation
TColorStyle() [1/2]
TColorStyle::TColorStyle ()
    : m_name(L"color")
    , m_globalName(L"")
    , m_originalName(L"")
    , m_versionNumber(0)
    , m_flags(0)
    , m_enabled(true)
    , m_icon(0)
    , m_validIcon(false)
    , m_isEditedFromOriginal(false)
    , m_pickedPosition() {}
TColorStyle() [2/2]
TColorStyle::TColorStyle (const TColorStyle & other)
Copies another style except its icon.
    : m_name(other.m_name)
    , m_globalName(other.m_globalName)
    , m_originalName(other.m_originalName)
    , m_versionNumber(other.m_versionNumber)
    , m_flags(other.m_flags)
    , m_enabled(other.m_enabled)
    , m_validIcon(false)
    , m_isEditedFromOriginal(other.m_isEditedFromOriginal)
    , m_pickedPosition(other.m_pickedPosition) {}
~TColorStyle()
TColorStyle::~TColorStyle () virtual
{}
Member Function Documentation
assignBlend()
void TColorStyle::assignBlend (const TColorStyle & a, const TColorStyle & b, double t)
\detail This function is provided to animate a palette style. Given two keyframe styles a and b, it calculates their linear interpolation at parameter t and assigns the result to this style instance.
Parameters
a Style value at parameter t = 0.
b Style value at parameter t = 1.
t Interpolation parameter. Assigns the linear interpolation between the supplied styles.
{
  // Blend colors
  {
    int col, colCount = getColorParamCount();
    assert(a.getColorParamCount() == colCount &&
           b.getColorParamCount() == colCount);
    for (col = 0; col != colCount; ++col)
      setColorParamValue(
          col, blend(a.getColorParamValue(col), b.getColorParamValue(col), t));
  }
  // Blend parameters
  {
    int par, parCount = getParamCount();
    assert(a.getParamCount() == parCount && b.getParamCount() == parCount);
    for (par = 0; par != parCount; ++par) {
      switch (getParamType(par)) {
      case DOUBLE:
        setParamValue(par, (1 - t) * a.getParamValue(double_tag(), par) +
                               t * b.getParamValue(double_tag(), par));
        break;
      default:
        break;
      }
    }
  }
  invalidateIcon();
}
References DOUBLE, getColorParamCount(), getColorParamValue(), getParamCount(), getParamType(), getParamValue(), invalidateIcon(), setColorParamValue(), and setParamValue().
Referenced by TPalette::setFrame().
assignNames()
void TColorStyle::assignNames (const TColorStyle * src)
Copies the style names from src.
{
  m_name                 = src->getName();
  m_globalName           = src->getGlobalName();
  m_originalName         = src->getOriginalName();
  m_isEditedFromOriginal = src->getIsEditedFlag();
}
References getGlobalName(), getIsEditedFlag(), getName(), and getOriginalName().
Referenced by TAirbrushRasterStyle::clone(), and TVectorBrushStyle::clone().
clone()
virtual TColorStyle * TColorStyle::clone () const pure virtual
Polymorphic clone of the style.
Implemented in TAirbrushRasterStyle, TBlendRasterStyle, TNoColorRasterStyle, MovingSolidColor, ShadowStyle, ShadowStyle2, TRubberFillStyle, TPointShadowFillStyle, TDottedFillStyle, TCheckedFillStyle, ArtisticSolidColor, TChalkFillStyle, TChessFillStyle, TStripeFillStyle, TLinGradFillStyle, TRadGradFillStyle, TCircleStripeFillStyle, TMosaicFillStyle, TPatchFillStyle, TFurStrokeStyle, TChainStrokeStyle, TSprayStrokeStyle, TGraphicPenStrokeStyle, TDottedLineStrokeStyle, TRopeStrokeStyle, TCrystallizeStrokeStyle, TBraidStrokeStyle, TSketchStrokeStyle, TBubbleStrokeStyle, TTissueStrokeStyle, TBiColorStrokeStyle, TNormal2StrokeStyle, TChalkStrokeStyle2, TBlendStrokeStyle2, TTwirlStrokeStyle, TSawToothStrokeStyle, TMultiLineStrokeStyle2, TZigzagStrokeStyle, TSinStrokeStyle, TFriezeStrokeStyle2, TDualColorStrokeStyle2, TLongBlendStrokeStyle2, TMatrioskaStrokeStyle, TColorCleanupStyle, TBlackCleanupStyle, TTextureStyle, TMyPaintBrushStyle, TSolidColorStyle, TCenterLineStrokeStyle, TRasterImagePatternStrokeStyle, TVectorImagePatternStrokeStyle, and TVectorBrushStyle.
Referenced by TPalette::assign(), TStyleSelection::getBackOriginalStyle(), TPalette::loadData(), TPalette::merge(), StyleEditor::setEditedStyleToStyle(), TPalette::setKeyframe(), StyleEditor::setOldStyleToStyle(), DVGui::StyleSample::setStyle(), and StudioPalette::updateLinkedColors().
copy()
virtual TColorStyle & TColorStyle::copy (const TColorStyle & other) inline virtual
Parameters
other Polymorphic copy of the style.
  {
    assignBlend(other, other, 0.0);
    return *this;
  }
Referenced by TPalette::setFrame().
create()
TColorStyle * TColorStyle::create (int tagId) static
Creates a new style with identifier equal to tagId.
implementation of loadData().
{
  bool isObsolete = false;
  return ColorStyleList::instance()->create(tagId, isObsolete);
}
References create().
Referenced by create(), and load().
declare()
void TColorStyle::declare (TColorStyle * style) static
Puts the style in the table of actual styles.
{
  ColorStyleList::instance()->declare(style);
}
enable()
void TColorStyle::enable (bool on) inline
Sets the style's enabled status.
getAllTags()
void TColorStyle::getAllTags (std::vector< int > & tags) static
{
  ColorStyleList::instance()->getAllTags(tags);
}
getAverageColor()
virtual TPixel32 TColorStyle::getAverageColor () const inline virtual
Returns a color representing the average of all the style's colors.
Reimplemented in TAirbrushRasterStyle, and TTextureStyle.
Referenced by TRop::convertRaster50to46(), ToonzRasterBrushTool::onEnter(), and ToonzVectorBrushTool::onEnter().
getColorParamCount()
virtual int TColorStyle::getColorParamCount () const inline virtual
Returns the number of colors (if any) of the style.
\detail For example a bubble styles has two colors. By default it returns 1 if the style has only a main color else returns 0 if the style has no color.
Reimplemented in TAirbrushRasterStyle, TNoColorRasterStyle, ShadowStyle, ShadowStyle2, TPointShadowFillStyle, TDottedFillStyle, TCheckedFillStyle, TChalkFillStyle, TChessFillStyle, TStripeFillStyle, TLinGradFillStyle, TRadGradFillStyle, TCircleStripeFillStyle, TMosaicFillStyle, TPatchFillStyle, TBraidStrokeStyle, TBubbleStrokeStyle, TBiColorStrokeStyle, TMultiLineStrokeStyle2, TDualColorStrokeStyle2, TLongBlendStrokeStyle2, TMatrioskaStrokeStyle, TCleanupStyle, TTextureStyle, and TVectorBrushStyle.
Referenced by assignBlend().
getColorParamValue()
virtual TPixel32 TColorStyle::getColorParamValue (int index) const inline virtual
Returns the value of the color of index index.
\detail Returns the main color by default.
Reimplemented in TAirbrushRasterStyle, TNoColorRasterStyle, ShadowStyle, ShadowStyle2, TPointShadowFillStyle, TDottedFillStyle, TCheckedFillStyle, TChalkFillStyle, TChessFillStyle, TStripeFillStyle, TLinGradFillStyle, TRadGradFillStyle, TCircleStripeFillStyle, TMosaicFillStyle, TPatchFillStyle, TBraidStrokeStyle, TBubbleStrokeStyle, TBiColorStrokeStyle, TMultiLineStrokeStyle2, TDualColorStrokeStyle2, TLongBlendStrokeStyle2, TMatrioskaStrokeStyle, TCleanupStyle, TTextureStyle, and TVectorBrushStyle.
Referenced by assignBlend(), and DVGui::StyleSample::setStyle().
getDescription()
virtual QString TColorStyle::getDescription () const pure virtual
Return a brief description of the style.
\detail For example for a stroke style we have "Constant", "Chain", "Rope", "Tulle", etc...
Implemented in TAirbrushRasterStyle, TBlendRasterStyle, TNoColorRasterStyle, MovingSolidColor, ShadowStyle, ShadowStyle2, TRubberFillStyle, TPointShadowFillStyle, TDottedFillStyle, TCheckedFillStyle, ArtisticSolidColor, TChalkFillStyle, TChessFillStyle, TStripeFillStyle, TLinGradFillStyle, TRadGradFillStyle, TCircleStripeFillStyle, TMosaicFillStyle, TPatchFillStyle, TFurStrokeStyle, TChainStrokeStyle, TSprayStrokeStyle, TGraphicPenStrokeStyle, TDottedLineStrokeStyle, TRopeStrokeStyle, TCrystallizeStrokeStyle, TBraidStrokeStyle, TSketchStrokeStyle, TBubbleStrokeStyle, TTissueStrokeStyle, TBiColorStrokeStyle, TNormal2StrokeStyle, TChalkStrokeStyle2, TBlendStrokeStyle2, TTwirlStrokeStyle, TSawToothStrokeStyle, TMultiLineStrokeStyle2, TZigzagStrokeStyle, TSinStrokeStyle, TFriezeStrokeStyle2, TDualColorStrokeStyle2, TLongBlendStrokeStyle2, TMatrioskaStrokeStyle, TColorCleanupStyle, TBlackCleanupStyle, TTextureStyle, TMyPaintBrushStyle, TSolidColorStyle, TCenterLineStrokeStyle, TRasterImagePatternStrokeStyle, TVectorImagePatternStrokeStyle, and TVectorBrushStyle.
getFlags()
unsigned int TColorStyle::getFlags () const inline
Sets color attributes.
See also
tcolorflags.h
Referenced by TVectorBrushStyle::clone(), PaletteViewerGUI::PageViewer::drawColorName(), and PaletteViewerGUI::PageViewer::paintEvent().
getGlobalName()
std::wstring TColorStyle::getGlobalName () const inline
Returns the global name of the style.
Referenced by TPalette::assign(), assignNames(), PaletteViewerGUI::PageViewer::drawToggleLink(), TStyleSelection::getBackOriginalStyle(), TStyleSelection::hasLinkedStyle(), TPalette::merge(), TStyleSelection::removeLink(), save(), StyleEditor::setStyle(), and StudioPalette::updateLinkedColors().
getIcon()
const TRaster32P & TColorStyle::getIcon (const TDimension & d) virtual
Returns an image representing the style.
{
  checkErrorsByGL;
  if (!m_validIcon || !m_icon || m_icon->getSize() != d) {
    checkErrorsByGL;
    makeIcon(d);
    checkErrorsByGL;
    m_validIcon = true;
  }
  checkErrorsByGL;
  if (!m_icon) {
    checkErrorsByGL;
    TRaster32P icon(d);
    checkErrorsByGL;
    icon->fill(TPixel32::Black);
    checkErrorsByGL;
    int lx = icon->getLx();
    checkErrorsByGL;
    int ly = icon->getLy();
    checkErrorsByGL;
    for (int y = 0; y < ly; y++) {
      checkErrorsByGL;
      int x = ((lx - 1 - 10) * y / ly);
      checkErrorsByGL;
      icon->extractT(x, y, x + 5, y)->fill(TPixel32::Red);
      checkErrorsByGL;
    }
    checkErrorsByGL;
    m_icon = icon;
    checkErrorsByGL;
  }
  return m_icon;
}
References m_icon, and m_validIcon.
Referenced by PaletteViewerGUI::PageViewer::drawColorChip(), PaletteViewerGUI::PageViewer::paintEvent(), and DVGui::StyleSample::setStyle().
getIsEditedFlag()
bool TColorStyle::getIsEditedFlag () const inline
style is edited from the original one.
Returns whether the style is edited from the original from studio palette
Referenced by assignNames(), and PaletteViewerGUI::PageViewer::paintEvent().
getMainColor()
virtual TPixel32 TColorStyle::getMainColor () const inline virtual
Returns the style's main color, or black if none.
Reimplemented in TAirbrushRasterStyle, TFurStrokeStyle, TChainStrokeStyle, TSprayStrokeStyle, TGraphicPenStrokeStyle, TDottedLineStrokeStyle, TRopeStrokeStyle, TCrystallizeStrokeStyle, TBraidStrokeStyle, TSketchStrokeStyle, TBubbleStrokeStyle, TTissueStrokeStyle, TBiColorStrokeStyle, TNormal2StrokeStyle, TChalkStrokeStyle2, TBlendStrokeStyle2, TTwirlStrokeStyle, TSawToothStrokeStyle, TMultiLineStrokeStyle2, TZigzagStrokeStyle, TSinStrokeStyle, TFriezeStrokeStyle2, TDualColorStrokeStyle2, TLongBlendStrokeStyle2, TTextureStyle, TMyPaintBrushStyle, TSolidColorStyle, TCenterLineStrokeStyle, TRasterImagePatternStrokeStyle, TVectorImagePatternStrokeStyle, and TVectorBrushStyle.
Referenced by PaletteViewerGUI::PageViewer::drawColorChip(), PaletteViewerGUI::PageViewer::drawColorName(), PaletteViewerGUI::PageViewer::drawToggleLink(), TVectorBrushStyle::getColorParamValue(), TVectorBrushStyle::getMainColor(), PaletteViewerGUI::PageViewer::paintEvent(), FullColorAreaFiller::rectFill(), and DVGui::StyleSample::setStyle().
getName()
std::wstring TColorStyle::getName () const inline
Returns the style's user-defined name.
Referenced by TPalette::assign(), assignNames(), PaletteViewerGUI::PageViewer::drawColorName(), PaletteViewerGUI::PageViewer::event(), TStyleSelection::getBackOriginalStyle(), TPalette::merge(), PaletteViewerGUI::PageViewer::mouseDoubleClickEvent(), PaletteViewerGUI::PageViewer::paintEvent(), save(), and StudioPalette::updateLinkedColors().
getObsoleteTagIds()
virtual void TColorStyle::getObsoleteTagIds (std::vector< int > &) const inline virtual
{};
getOriginalName()
std::wstring TColorStyle::getOriginalName () const inline
Returns the original name of the style.
Referenced by TPalette::assign(), assignNames(), TPalette::merge(), PaletteViewerGUI::PageViewer::paintEvent(), TStyleSelection::removeLink(), and save().
getParamCount()
virtual int TColorStyle::getParamCount () const inline virtual
\detail For example: a the general cleanup style has two parameters, brightness and contrast and a black cleanup style has in addition a black and white threshold, therefore 4 parameters. Returns the number of parameters necessary to describe the style.
Reimplemented in TAirbrushRasterStyle, MovingSolidColor, ShadowStyle, ShadowStyle2, TRubberFillStyle, TPointShadowFillStyle, TDottedFillStyle, TCheckedFillStyle, ArtisticSolidColor, TChalkFillStyle, TChessFillStyle, TStripeFillStyle, TLinGradFillStyle, TRadGradFillStyle, TCircleStripeFillStyle, TMosaicFillStyle, TPatchFillStyle, TFurStrokeStyle, TSprayStrokeStyle, TGraphicPenStrokeStyle, TDottedLineStrokeStyle, TRopeStrokeStyle, TCrystallizeStrokeStyle, TBraidStrokeStyle, TSketchStrokeStyle, TTissueStrokeStyle, TNormal2StrokeStyle, TChalkStrokeStyle2, TBlendStrokeStyle2, TTwirlStrokeStyle, TSawToothStrokeStyle, TMultiLineStrokeStyle2, TZigzagStrokeStyle, TSinStrokeStyle, TFriezeStrokeStyle2, TDualColorStrokeStyle2, TLongBlendStrokeStyle2, TMatrioskaStrokeStyle, TCleanupStyle, TColorCleanupStyle, TBlackCleanupStyle, TTextureStyle, TMyPaintBrushStyle, TCenterLineStrokeStyle, TRasterImagePatternStrokeStyle, and TVectorImagePatternStrokeStyle.
Referenced by assignBlend().
getParamNames()
QString TColorStyle::getParamNames (int index) const virtual
Return the string that identifies the index-th parameter.
Reimplemented in TAirbrushRasterStyle, MovingSolidColor, ShadowStyle, ShadowStyle2, TRubberFillStyle, TPointShadowFillStyle, TDottedFillStyle, TCheckedFillStyle, ArtisticSolidColor, TChalkFillStyle, TChessFillStyle, TStripeFillStyle, TLinGradFillStyle, TRadGradFillStyle, TCircleStripeFillStyle, TMosaicFillStyle, TPatchFillStyle, TFurStrokeStyle, TSprayStrokeStyle, TGraphicPenStrokeStyle, TDottedLineStrokeStyle, TRopeStrokeStyle, TCrystallizeStrokeStyle, TBraidStrokeStyle, TSketchStrokeStyle, TTissueStrokeStyle, TNormal2StrokeStyle, TChalkStrokeStyle2, TBlendStrokeStyle2, TTwirlStrokeStyle, TSawToothStrokeStyle, TMultiLineStrokeStyle2, TZigzagStrokeStyle, TSinStrokeStyle, TFriezeStrokeStyle2, TDualColorStrokeStyle2, TLongBlendStrokeStyle2, TMatrioskaStrokeStyle, TCleanupStyle, TColorCleanupStyle, TBlackCleanupStyle, TTextureStyle, TMyPaintBrushStyle, TCenterLineStrokeStyle, TRasterImagePatternStrokeStyle, and TVectorImagePatternStrokeStyle.
{
  assert(false);
  return QString("");
}
getParamRange() [1/3]
virtual void TColorStyle::getParamRange (int index, double & min, double & max) const inline virtual
Retrieves the specified double parameter range.
Reimplemented in TAirbrushRasterStyle, MovingSolidColor, ShadowStyle, ShadowStyle2, TRubberFillStyle, TPointShadowFillStyle, TDottedFillStyle, TCheckedFillStyle, ArtisticSolidColor, TChalkFillStyle, TChessFillStyle, TStripeFillStyle, TLinGradFillStyle, TRadGradFillStyle, TCircleStripeFillStyle, TMosaicFillStyle, TPatchFillStyle, TFurStrokeStyle, TSprayStrokeStyle, TGraphicPenStrokeStyle, TDottedLineStrokeStyle, TRopeStrokeStyle, TCrystallizeStrokeStyle, TBraidStrokeStyle, TSketchStrokeStyle, TTissueStrokeStyle, TNormal2StrokeStyle, TChalkStrokeStyle2, TBlendStrokeStyle2, TTwirlStrokeStyle, TSawToothStrokeStyle, TMultiLineStrokeStyle2, TZigzagStrokeStyle, TSinStrokeStyle, TFriezeStrokeStyle2, TDualColorStrokeStyle2, TLongBlendStrokeStyle2, TMatrioskaStrokeStyle, TCleanupStyle, TColorCleanupStyle, TBlackCleanupStyle, TTextureStyle, TMyPaintBrushStyle, TCenterLineStrokeStyle, TRasterImagePatternStrokeStyle, and TVectorImagePatternStrokeStyle.
getParamRange() [2/3]
virtual void TColorStyle::getParamRange (int index, int & min, int & max) const inline virtual
Retrieves the specified int parameter range.
getParamRange() [3/3]
virtual void TColorStyle::getParamRange (int pIndex, QStringList & stringItems) const inline virtual
Returns a description of each supported enum or file
Reimplemented in TTextureStyle.
getParamType()
virtual ParamType TColorStyle::getParamType (int paramIdx) const inline virtual
Returns the type of the specified parameter.
Reimplemented in TAirbrushRasterStyle, MovingSolidColor, ShadowStyle, ShadowStyle2, TRubberFillStyle, TPointShadowFillStyle, TDottedFillStyle, TCheckedFillStyle, ArtisticSolidColor, TChalkFillStyle, TChessFillStyle, TStripeFillStyle, TLinGradFillStyle, TRadGradFillStyle, TCircleStripeFillStyle, TMosaicFillStyle, TPatchFillStyle, TFurStrokeStyle, TSprayStrokeStyle, TGraphicPenStrokeStyle, TDottedLineStrokeStyle, TRopeStrokeStyle, TCrystallizeStrokeStyle, TBraidStrokeStyle, TSketchStrokeStyle, TTissueStrokeStyle, TNormal2StrokeStyle, TChalkStrokeStyle2, TBlendStrokeStyle2, TTwirlStrokeStyle, TSawToothStrokeStyle, TMultiLineStrokeStyle2, TZigzagStrokeStyle, TSinStrokeStyle, TFriezeStrokeStyle2, TDualColorStrokeStyle2, TLongBlendStrokeStyle2, TMatrioskaStrokeStyle, TTextureStyle, TMyPaintBrushStyle, TCenterLineStrokeStyle, TRasterImagePatternStrokeStyle, and TVectorImagePatternStrokeStyle.
Referenced by assignBlend().
getParamValue() [1/4]
virtual bool TColorStyle::getParamValue (bool_tag , int index) const inline virtual
Retrieves the specified bool parameter value.
Reimplemented in TTextureStyle.
Referenced by assignBlend().
getParamValue() [2/4]
virtual double TColorStyle::getParamValue (double_tag , int index) const inline virtual
Retrieves the specified double parameter value.
Reimplemented in TMyPaintBrushStyle, TAirbrushRasterStyle, MovingSolidColor, ShadowStyle, ShadowStyle2, TRubberFillStyle, TPointShadowFillStyle, TDottedFillStyle, TCheckedFillStyle, ArtisticSolidColor, TChalkFillStyle, TChessFillStyle, TStripeFillStyle, TLinGradFillStyle, TRadGradFillStyle, TCircleStripeFillStyle, TMosaicFillStyle, TPatchFillStyle, TFurStrokeStyle, TSprayStrokeStyle, TGraphicPenStrokeStyle, TDottedLineStrokeStyle, TRopeStrokeStyle, TCrystallizeStrokeStyle, TBraidStrokeStyle, TSketchStrokeStyle, TTissueStrokeStyle, TNormal2StrokeStyle, TChalkStrokeStyle2, TBlendStrokeStyle2, TTwirlStrokeStyle, TSawToothStrokeStyle, TMultiLineStrokeStyle2, TZigzagStrokeStyle, TSinStrokeStyle, TFriezeStrokeStyle2, TDualColorStrokeStyle2, TLongBlendStrokeStyle2, TMatrioskaStrokeStyle, TCleanupStyle, TColorCleanupStyle, TBlackCleanupStyle, TTextureStyle, TCenterLineStrokeStyle, TRasterImagePatternStrokeStyle, and TVectorImagePatternStrokeStyle.
getParamValue() [3/4]
virtual int TColorStyle::getParamValue (int_tag , int index) const inline virtual
Retrieves the specified int parameter value.
Reimplemented in TTextureStyle.
getParamValue() [4/4]
virtual TFilePath TColorStyle::getParamValue (TFilePath_tag , int index) const inline virtual
Retrieves the specified TFilePath parameter value.
Reimplemented in TTextureStyle.
getPickedPosition()
PickedPosition TColorStyle::getPickedPosition () const inline
{ return m_pickedPosition; }
getRasterStyleFx()
virtual TRasterStyleFx * TColorStyle::getRasterStyleFx () inline virtual
If the style contains raster effects it must return it, else returns 0.
Reimplemented in TAirbrushRasterStyle, TNoColorRasterStyle, and TTextureStyle.
Referenced by ToonzRasterBrushTool::onEnter(), and ToonzVectorBrushTool::onEnter().
getTagId()
virtual int TColorStyle::getTagId () const pure virtual
Returns an unique number representing the style.
Implemented in TAirbrushRasterStyle, TBlendRasterStyle, TNoColorRasterStyle, MovingSolidColor, ShadowStyle, ShadowStyle2, TRubberFillStyle, TPointShadowFillStyle, TDottedFillStyle, TCheckedFillStyle, ArtisticSolidColor, TChalkFillStyle, TChessFillStyle, TStripeFillStyle, TLinGradFillStyle, TRadGradFillStyle, TCircleStripeFillStyle, TMosaicFillStyle, TPatchFillStyle, TFurStrokeStyle, TChainStrokeStyle, TSprayStrokeStyle, TGraphicPenStrokeStyle, TDottedLineStrokeStyle, TRopeStrokeStyle, TCrystallizeStrokeStyle, TBraidStrokeStyle, TSketchStrokeStyle, TBubbleStrokeStyle, TTissueStrokeStyle, TBiColorStrokeStyle, TNormal2StrokeStyle, TChalkStrokeStyle2, TBlendStrokeStyle2, TTwirlStrokeStyle, TSawToothStrokeStyle, TMultiLineStrokeStyle2, TZigzagStrokeStyle, TSinStrokeStyle, TFriezeStrokeStyle2, TDualColorStrokeStyle2, TLongBlendStrokeStyle2, TMatrioskaStrokeStyle, TColorCleanupStyle, TBlackCleanupStyle, TTextureStyle, TMyPaintBrushStyle, TSolidColorStyle, TCenterLineStrokeStyle, TRasterImagePatternStrokeStyle, TVectorImagePatternStrokeStyle, and TVectorBrushStyle.
Referenced by PaletteViewerGUI::PageViewer::drawColorChip(), PaletteViewerGUI::PageViewer::paintEvent(), save(), and DVGui::StyleSample::setStyle().
getVersionNumber()
int TColorStyle::getVersionNumber () const inline
Returns the version number of the style.
Referenced by OutlineRegionProp::draw().
hasMainColor()
virtual bool TColorStyle::hasMainColor () const inline virtual
Returns whether the style has a reference main color.
\detail Raster or vector pattern image styles, for example, return false.
Reimplemented in TAirbrushRasterStyle, TFurStrokeStyle, TChainStrokeStyle, TSprayStrokeStyle, TGraphicPenStrokeStyle, TDottedLineStrokeStyle, TRopeStrokeStyle, TCrystallizeStrokeStyle, TBraidStrokeStyle, TSketchStrokeStyle, TBubbleStrokeStyle, TTissueStrokeStyle, TBiColorStrokeStyle, TNormal2StrokeStyle, TChalkStrokeStyle2, TBlendStrokeStyle2, TTwirlStrokeStyle, TSawToothStrokeStyle, TMultiLineStrokeStyle2, TZigzagStrokeStyle, TSinStrokeStyle, TFriezeStrokeStyle2, TDualColorStrokeStyle2, TLongBlendStrokeStyle2, TTextureStyle, TMyPaintBrushStyle, TSolidColorStyle, TCenterLineStrokeStyle, TRasterImagePatternStrokeStyle, TVectorImagePatternStrokeStyle, and TVectorBrushStyle.
hasParamDefault()
virtual bool TColorStyle::hasParamDefault (int index) const inline virtual
Value of parameter can be reset to default.
Reimplemented in TMyPaintBrushStyle.
invalidateIcon()
void TColorStyle::invalidateIcon () inline
Sets a flag that defines the style's icon validity.
\detail It is used when updates must be done after changes or creation of new styles.
Referenced by assignBlend().
isEnabled()
bool TColorStyle::isEnabled () const inline
Returns whether the style can be used.
isParamDefault()
virtual bool TColorStyle::isParamDefault (int index) const inline virtual
Check if current value of parameter equals to default.
Reimplemented in TMyPaintBrushStyle.
isRasterStyle()
virtual bool TColorStyle::isRasterStyle () const inline virtual
used to draw the style on the specified region object.
Returns whether the style is of the raster kind.
Reimplemented in TAirbrushRasterStyle, TNoColorRasterStyle, and TTextureStyle.
isRegionStyle()
virtual bool TColorStyle::isRegionStyle () const pure virtual
Returns whether the style applies on regions.
Implemented in TAirbrushRasterStyle, TNoColorRasterStyle, MovingSolidColor, ShadowStyle, ShadowStyle2, TRubberFillStyle, TPointShadowFillStyle, TDottedFillStyle, TCheckedFillStyle, ArtisticSolidColor, TChalkFillStyle, TChessFillStyle, TStripeFillStyle, TLinGradFillStyle, TRadGradFillStyle, TCircleStripeFillStyle, TMosaicFillStyle, TPatchFillStyle, TOptimizedStrokeStyleT< T >, TOptimizedStrokeStyleT< PointsAndDoubles >, TOptimizedStrokeStyleT< Points >, TOptimizedStrokeStyleT< Doubles >, TOptimizedStrokeStyleT< DrawmodePointsMatrix >, TOptimizedStrokeStyleT< BlendAndPoints >, TOptimizedStrokeStyleT< PointMatrix >, TBiColorStrokeStyle, TNormal2StrokeStyle, TSawToothStrokeStyle, TDualColorStrokeStyle2, TLongBlendStrokeStyle2, TMatrioskaStrokeStyle, TMyPaintBrushStyle, TSimpleStrokeStyle, TOutlineStyle, TRasterImagePatternStrokeStyle, TVectorImagePatternStrokeStyle, and TVectorBrushStyle.
isStrokeStyle()
virtual bool TColorStyle::isStrokeStyle () const pure virtual
Returns whether the style applies on strokes.
Implemented in TAirbrushRasterStyle, TNoColorRasterStyle, MovingSolidColor, ShadowStyle, ShadowStyle2, TRubberFillStyle, TPointShadowFillStyle, TDottedFillStyle, TCheckedFillStyle, ArtisticSolidColor, TChalkFillStyle, TChessFillStyle, TStripeFillStyle, TLinGradFillStyle, TRadGradFillStyle, TCircleStripeFillStyle, TMosaicFillStyle, TPatchFillStyle, TOptimizedStrokeStyleT< T >, TOptimizedStrokeStyleT< PointsAndDoubles >, TOptimizedStrokeStyleT< Points >, TOptimizedStrokeStyleT< Doubles >, TOptimizedStrokeStyleT< DrawmodePointsMatrix >, TOptimizedStrokeStyleT< BlendAndPoints >, TOptimizedStrokeStyleT< PointMatrix >, TBiColorStrokeStyle, TNormal2StrokeStyle, TSawToothStrokeStyle, TDualColorStrokeStyle2, TLongBlendStrokeStyle2, TMatrioskaStrokeStyle, TMyPaintBrushStyle, TSimpleStrokeStyle, TOutlineStyle, TRasterImagePatternStrokeStyle, TVectorImagePatternStrokeStyle, and TVectorBrushStyle.
Referenced by ToonzRasterBrushTool::onEnter(), and ToonzVectorBrushTool::onEnter().
load()
TColorStyle * TColorStyle::load (TInputStreamInterface & is) static
passing it also the name and the tagId of the style. Loads the style from disk. Calls the local
{
  std::string name;
  std::wstring gname;
  std::wstring origName;
  bool isEdited = false;
  is >> name;
  unsigned int flags = 0;
  if (name.length() == 2 && name[0] == '_' && '0' <= name[1] &&
      name[1] <= '9') {
    flags = QString::fromStdString(name.substr(1)).toUInt();
    is >> name;
  }
  if (name.length() > 0 && name[0] == '|') {
    gname = ::to_wstring(name.substr(1));
    is >> name;
    // If the style is copied from studio palette, original name is here
    if (name.length() > 0 && name[0] == '@') {
      // if there are two "@"s, then activate the edited flag
      if (name[1] == '@') {
        isEdited = true;
        origName = ::to_wstring(name.substr(2));
      } else {
        origName = ::to_wstring(name.substr(1));
      }
      is >> name;
    }
  }
  int id = 0;
  if (!name.empty() && '0' <= name[0] && name[0] <= '9') {
    id   = std::stoi(name);
    name = "color";
  } else {
    if (!name.empty() && name[0] == '_') name.erase(name.begin());
    is >> id;
  }
  bool isObsolete    = false;
  TColorStyle *style = ColorStyleList::instance()->create(id, isObsolete);
  assert(style);
  style->setFlags(flags);
  if (isObsolete)
    style->loadData(id, is);
  else
    style->loadData(is);
  style->setName(::to_wstring(name));
  style->setGlobalName(gname);
  style->setOriginalName(origName);
  style->setIsEditedFlag(isEdited);
  return style;
}
References create(), setFlags(), setGlobalName(), setName(), and setOriginalName().
Referenced by TPalette::loadData().
loadData()
virtual void TColorStyle::loadData (int , TInputStreamInterface &) inline protected virtual
Deprecated:
Backward compatibility
Reimplemented in TAirbrushRasterStyle, TNoColorRasterStyle, TChalkFillStyle, TBraidStrokeStyle, TBubbleStrokeStyle, TBiColorStrokeStyle, TNormal2StrokeStyle, TChalkStrokeStyle2, TBlendStrokeStyle2, TMultiLineStrokeStyle2, TFriezeStrokeStyle2, TRasterImagePatternStrokeStyle, and TVectorImagePatternStrokeStyle.
makeIcon()
void TColorStyle::makeIcon (const TDimension & d) protected virtual
{
  checkErrorsByGL;
  TColorStyle *style = this->clone();
  checkErrorsByGL;
  TPaletteP tmpPalette = new TPalette();
  checkErrorsByGL;
  int id = tmpPalette->addStyle(style);
  checkErrorsByGL;
  int contextLx = pow(2.0, tceil(log((double)d.lx) / log(2.0)));
  int contextLy = pow(2.0, tceil(log((double)d.ly) / log(2.0)));
  TDimension dim(contextLx, contextLy);
  TOfflineGL *glContext = TOfflineGL::getStock(dim);
  checkErrorsByGL;
  glContext->clear(TPixel32::White);
  checkErrorsByGL;
  TVectorImageP img = new TVectorImage;
  checkErrorsByGL;
  img->setPalette(tmpPalette.getPointer());
  checkErrorsByGL;
  std::vector<TThickPoint> points(3);
  if (isRegionStyle() && !isStrokeStyle()) {
    points[0]        = TThickPoint(-55, -50, 1);
    points[1]        = TThickPoint(0, -60, 1);
    points[2]        = TThickPoint(55, -50, 1);
    TStroke *stroke1 = new TStroke(points);
    img->addStroke(stroke1);
    points[0]        = TThickPoint(50, -55, 1);
    points[1]        = TThickPoint(60, 0, 1);
    points[2]        = TThickPoint(50, 55, 1);
    TStroke *stroke2 = new TStroke(points);
    img->addStroke(stroke2);
    points[0]        = TThickPoint(55, 50, 1);
    points[1]        = TThickPoint(0, 60, 1);
    points[2]        = TThickPoint(-55, 50, 1);
    TStroke *stroke3 = new TStroke(points);
    img->addStroke(stroke3);
    points[0]        = TThickPoint(-50, 55, 1);
    points[1]        = TThickPoint(-60, 0, 1);
    points[2]        = TThickPoint(-50, -55, 1);
    TStroke *stroke4 = new TStroke(points);
    img->addStroke(stroke4);
    img->fill(TPointD(0, 0), id);
  } else if (isStrokeStyle() && !isRegionStyle()) {
    double rasX05 = d.lx * 0.5;
    double rasY05 = d.ly * 0.5;
    points[0]        = TThickPoint(-rasX05, -rasY05, 7);
    points[1]        = TThickPoint(0, -rasY05, 9);
    points[2]        = TThickPoint(rasX05, rasY05, 12);
    TStroke *stroke1 = new TStroke(points);
    stroke1->setStyle(id);
    img->addStroke(stroke1);
    points.clear();
  } else if (!isRasterStyle()) {
    assert(isStrokeStyle() && isRegionStyle());
    points[0]        = TThickPoint(-60, -30, 0.5);
    points[1]        = TThickPoint(0, -30, 0.5);
    points[2]        = TThickPoint(60, -30, 0.5);
    TStroke *stroke1 = new TStroke(points);
    stroke1->setStyle(id);
    img->addStroke(stroke1);
    points[0]        = TThickPoint(60, -30, 0.5);
    points[1]        = TThickPoint(60, 0, 0.5);
    points[2]        = TThickPoint(60, 30, 0.5);
    TStroke *stroke2 = new TStroke(points);
    stroke2->setStyle(id);
    img->addStroke(stroke2);
    points[0]        = TThickPoint(60, 30, 0.5);
    points[1]        = TThickPoint(0, 30, 0.5);
    points[2]        = TThickPoint(-60, 30, 0.5);
    TStroke *stroke3 = new TStroke(points);
    stroke3->setStyle(id);
    img->addStroke(stroke3);
    points[0]        = TThickPoint(-60, 30, 0.5);
    points[1]        = TThickPoint(-60, 0, 0.5);
    points[2]        = TThickPoint(-60, -30, 0.5);
    TStroke *stroke4 = new TStroke(points);
    stroke4->setStyle(id);
    img->addStroke(stroke4);
    img->fill(TPointD(0, 0), id);
  }
  TRectD bbox = img->getBBox();
  checkErrorsByGL;
  bbox = bbox.enlarge(TDimensionD(-10, -10));
  checkErrorsByGL;
  double scx  = 0.9 * d.lx / bbox.getLx();
  double scy  = 0.9 * d.ly / bbox.getLy();
  double sc   = std::min(scx, scy);
  double dx   = (d.lx - bbox.getLx() * sc) * 0.5;
  double dy   = (d.ly - bbox.getLy() * sc) * 0.5;
  TAffine aff = TScale(sc) * TTranslation(-bbox.getP00() + TPointD(dx, dy));
  checkErrorsByGL;
  if (isRegionStyle() && !isStrokeStyle()) aff = aff * TTranslation(-10, -10);
  checkErrorsByGL;
  const TVectorRenderData rd(aff, TRect(), tmpPalette.getPointer(), 0, true);
  checkErrorsByGL;
  glContext->draw(img, rd);
  checkErrorsByGL;
  TRect rect(d);
  if (!m_icon || m_icon->getSize() != d) {
    checkErrorsByGL;
    m_icon = glContext->getRaster()->extract(rect)->clone();
  } else {
    checkErrorsByGL;
    m_icon->copy(glContext->getRaster()->extract(rect));
  }
}
makeRegionProp()
virtual TRegionProp * TColorStyle::makeRegionProp (const TRegion * region) pure virtual
used to draw the style on the specified stroke object.
Allocates a new derived TRegionProp instance
Implemented in TMyPaintBrushStyle, TSimpleStrokeStyle, TRasterImagePatternStrokeStyle, TVectorImagePatternStrokeStyle, TAirbrushRasterStyle, TNoColorRasterStyle, TOptimizedStrokeStyleT< T >, TOptimizedStrokeStyleT< PointsAndDoubles >, TOptimizedStrokeStyleT< Points >, TOptimizedStrokeStyleT< Doubles >, TOptimizedStrokeStyleT< DrawmodePointsMatrix >, TOptimizedStrokeStyleT< BlendAndPoints >, TOptimizedStrokeStyleT< PointMatrix >, TOutlineStyle, and TVectorBrushStyle.
makeStrokeProp()
virtual TStrokeProp * TColorStyle::makeStrokeProp (const TStroke * stroke) pure virtual
Allocates a new derived TStrokeProp instance
Implemented in TMyPaintBrushStyle, TAirbrushRasterStyle, TNoColorRasterStyle, TOptimizedStrokeStyleT< T >, TOptimizedStrokeStyleT< PointsAndDoubles >, TOptimizedStrokeStyleT< Points >, TOptimizedStrokeStyleT< Doubles >, TOptimizedStrokeStyleT< DrawmodePointsMatrix >, TOptimizedStrokeStyleT< BlendAndPoints >, TOptimizedStrokeStyleT< PointMatrix >, TMatrioskaStrokeStyle, TSimpleStrokeStyle, TOutlineStyle, TRasterImagePatternStrokeStyle, TVectorImagePatternStrokeStyle, and TVectorBrushStyle.
operator!=()
bool TColorStyle::operator!= (const TColorStyle & cs) inline
{ return !operator==(cs); }
operator=()
TColorStyle & TColorStyle::operator= (const TColorStyle & other) protected
Copies another style except its icon.
{
  m_name                 = other.m_name;
  m_globalName           = other.m_globalName;
  m_originalName         = other.m_originalName;
  m_versionNumber        = other.m_versionNumber;
  m_flags                = other.m_flags;
  m_enabled              = other.m_enabled;
  m_validIcon            = false;
  m_isEditedFromOriginal = other.m_isEditedFromOriginal;
  m_pickedPosition       = other.m_pickedPosition;
  return *this;
}
References m_validIcon.
operator==()
bool TColorStyle::operator== (const TColorStyle & cs) const
{
  if (getTagId() != cs.getTagId()) return false;
  if (getMainColor() != cs.getMainColor()) return false;
  int paramCount = getParamCount();
  if (paramCount != cs.getParamCount()) return false;
  int colorParamCount = getColorParamCount();
  if (colorParamCount != cs.getColorParamCount()) return false;
  if (m_name != cs.getName()) return false;
  if (m_originalName != cs.getOriginalName()) return false;
  if (m_globalName != cs.getGlobalName()) return false;
  if (m_isEditedFromOriginal != cs.getIsEditedFlag()) return false;
  if (m_pickedPosition != cs.getPickedPosition()) return false;
  if (m_flags != cs.getFlags()) return false;
  for (int p = 0; p < colorParamCount; ++p)
    if (getColorParamValue(p) != cs.getColorParamValue(p)) return false;
  for (int p = 0; p < paramCount; ++p) {
    switch (getParamType(p)) {
    case BOOL:
      if (getParamValue(bool_tag(), p) != cs.getParamValue(bool_tag(), p))
        return false;
      break;
    case INT:
    case ENUM:
      if (getParamValue(int_tag(), p) != cs.getParamValue(int_tag(), p))
        return false;
      break;
    case DOUBLE:
      if (getParamValue(double_tag(), p) != cs.getParamValue(double_tag(), p))
        return false;
      break;
    case FILEPATH:
      if (getParamValue(TFilePath_tag(), p) !=
          cs.getParamValue(TFilePath_tag(), p))
        return false;
      break;
    default:
      assert(false);
    }
  }
  return true;
}
save()
void TColorStyle::save (TOutputStreamInterface & os) const
Deprecated:
Calls the local implementation of saveData()
{
  std::wstring name = getName();
  bool numberedName =
      !name.empty() && (('0' <= name[0] && name[0] <= '9') || name[0] == '_');
  if (m_flags > 0 || (name.length() == 1 && numberedName))
    os << ("_" + QString::number(m_flags)).toStdString();
  std::wstring gname    = getGlobalName();
  std::wstring origName = getOriginalName();
  if (gname != L"") {
    os << ::to_string(L"|" + gname);
    // save the original name from studio palette
    if (origName != L"") {
      // write two "@"s if the edited flag is ON
      os << ::to_string(((m_isEditedFromOriginal) ? L"@@" : L"@") + origName);
    }
  }
  if (numberedName) name.insert(0, L"_");
  os << ::to_string(name) << getTagId();
  saveData(os);
}
References getGlobalName(), getName(), getOriginalName(), and getTagId().
Referenced by TPalette::saveData().
setColorParamValue()
virtual void TColorStyle::setColorParamValue (int index, const TPixel32 & color) inline virtual
Sets the index-th color value.
Reimplemented in TAirbrushRasterStyle, TNoColorRasterStyle, ShadowStyle, ShadowStyle2, TPointShadowFillStyle, TDottedFillStyle, TCheckedFillStyle, TChalkFillStyle, TChessFillStyle, TStripeFillStyle, TLinGradFillStyle, TRadGradFillStyle, TCircleStripeFillStyle, TMosaicFillStyle, TPatchFillStyle, TBraidStrokeStyle, TBubbleStrokeStyle, TBiColorStrokeStyle, TMultiLineStrokeStyle2, TDualColorStrokeStyle2, TLongBlendStrokeStyle2, TMatrioskaStrokeStyle, TCleanupStyle, TTextureStyle, and TVectorBrushStyle.
Referenced by assignBlend().
setFlags()
void TColorStyle::setFlags (unsigned int flags) inline
Returns color attributes.
Referenced by TVectorBrushStyle::clone(), and load().
setGlobalName()
void TColorStyle::setGlobalName (std::wstring name) inline
Sets the global name of the style.
\detail The global name contains information about palette id.
Referenced by TPalette::assign(), TStyleSelection::getBackOriginalStyle(), load(), TPalette::merge(), TStyleSelection::removeLink(), and StudioPalette::updateLinkedColors().
setIsEditedFlag()
void TColorStyle::setIsEditedFlag (bool edited) inline
{
    m_isEditedFromOriginal = edited;
  }  //<! If the style is copied from studio palette, This flag will be set when
setMainColor()
virtual void TColorStyle::setMainColor (const TPixel32 & color) inline virtual
Sets the main color, if it has one.
Reimplemented in TRasterImagePatternStrokeStyle, TVectorImagePatternStrokeStyle, TAirbrushRasterStyle, TFurStrokeStyle, TChainStrokeStyle, TSprayStrokeStyle, TGraphicPenStrokeStyle, TDottedLineStrokeStyle, TRopeStrokeStyle, TCrystallizeStrokeStyle, TBraidStrokeStyle, TSketchStrokeStyle, TBubbleStrokeStyle, TTissueStrokeStyle, TBiColorStrokeStyle, TNormal2StrokeStyle, TChalkStrokeStyle2, TBlendStrokeStyle2, TTwirlStrokeStyle, TSawToothStrokeStyle, TMultiLineStrokeStyle2, TZigzagStrokeStyle, TSinStrokeStyle, TFriezeStrokeStyle2, TDualColorStrokeStyle2, TCleanupStyle, TTextureStyle, TMyPaintBrushStyle, TSolidColorStyle, TCenterLineStrokeStyle, TVectorBrushStyle, and TLongBlendStrokeStyle2.
Referenced by TPalette::loadData(), TVectorBrushStyle::setColorParamValue(), and TVectorBrushStyle::setMainColor().
setName()
void TColorStyle::setName (std::wstring name) inline
Sets the style's user-defined name.
Referenced by TPalette::assign(), TStyleSelection::getBackOriginalStyle(), load(), TPalette::merge(), and StudioPalette::updateLinkedColors().
setOriginalName()
void TColorStyle::setOriginalName (std::wstring name) inline
If the style is originally copied from studio palette, set this.
Referenced by TPalette::assign(), TStyleSelection::getBackOriginalStyle(), load(), TPalette::merge(), TStyleSelection::removeLink(), and StudioPalette::updateLinkedColors().
setParamDefault()
virtual void TColorStyle::setParamDefault (int index) inline virtual
Reset value of parameter to default.
Reimplemented in TMyPaintBrushStyle.
setParamValue() [1/4]
virtual void TColorStyle::setParamValue (int index, bool value) inline virtual
Assigns a value to the specified bool parameter.
Reimplemented in TTextureStyle.
Referenced by assignBlend().
setParamValue() [2/4]
virtual void TColorStyle::setParamValue (int index, const TFilePath & fp) inline virtual
Assigns a value to the specified TFilePath parameter.
Reimplemented in TTextureStyle.
setParamValue() [3/4]
virtual void TColorStyle::setParamValue (int index, double value) inline virtual
extension value in text form.
Assigns a value to the specified double parameter.
Reimplemented in TAirbrushRasterStyle, MovingSolidColor, ShadowStyle, ShadowStyle2, TRubberFillStyle, TPointShadowFillStyle, TDottedFillStyle, TCheckedFillStyle, ArtisticSolidColor, TChalkFillStyle, TChessFillStyle, TStripeFillStyle, TLinGradFillStyle, TRadGradFillStyle, TCircleStripeFillStyle, TMosaicFillStyle, TPatchFillStyle, TFurStrokeStyle, TSprayStrokeStyle, TGraphicPenStrokeStyle, TDottedLineStrokeStyle, TRopeStrokeStyle, TCrystallizeStrokeStyle, TBraidStrokeStyle, TSketchStrokeStyle, TTissueStrokeStyle, TNormal2StrokeStyle, TChalkStrokeStyle2, TBlendStrokeStyle2, TTwirlStrokeStyle, TSawToothStrokeStyle, TMultiLineStrokeStyle2, TZigzagStrokeStyle, TSinStrokeStyle, TFriezeStrokeStyle2, TDualColorStrokeStyle2, TLongBlendStrokeStyle2, TMatrioskaStrokeStyle, TCleanupStyle, TColorCleanupStyle, TBlackCleanupStyle, TTextureStyle, TMyPaintBrushStyle, TCenterLineStrokeStyle, TRasterImagePatternStrokeStyle, and TVectorImagePatternStrokeStyle.
setParamValue() [4/4]
virtual void TColorStyle::setParamValue (int index, int value) inline virtual
Assigns a value to the specified int parameter.
Reimplemented in TTextureStyle.
setPickedPosition() [1/2]
void TColorStyle::setPickedPosition (const PickedPosition & pos) inline
{ m_pickedPosition = pos; }
setPickedPosition() [2/2]
void TColorStyle::setPickedPosition (const TPoint & pos, const int index = 0) inline
{
    m_pickedPosition.pos   = pos;
    m_pickedPosition.frame = index;
  }
updateVersionNumber()
void TColorStyle::updateVersionNumber () protected
{ ++m_versionNumber; }
Member Data Documentation
m_currentFrame
int TColorStyle::m_currentFrame = 0 static
Time instant in the palette's timeline.
Deprecated:
Should be done better
m_icon
TRaster32P TColorStyle::m_icon protected
Icon shown on TPalette viewers.
Referenced by getIcon().
m_validIcon
bool TColorStyle::m_validIcon protected
Icon's validity status.
Referenced by getIcon(), and operator=().
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/tcolorstyles.h
E:/opentoonz/toonz/sources/common/tvrender/tcolorstyles.cpp