opentoonz: ToonzExt::StrokeParametricDeformer Class Reference
ToonzExt::StrokeParametricDeformer Class Reference final
This class implements new deformer.
#include <StrokeParametricDeformer.h>
Public Member Functions
StrokeParametricDeformer (double actionLength, double startParameter, TStroke *s, Potential *)
void setMouseMove (double vx, double vy)
Set mouse movement from last valid position.
TThickPoint getDisplacement (const TStroke &stroke, double w) const override
Return displacement to use with function increaseControlPoints.
TThickPoint getDisplacementForControlPoint (const TStroke &stroke, UINT n) const override
Return displacement to use with function modifyControlPoints.
TThickPoint getDisplacementForControlPointLen (const TStroke &stroke, double cpLen) const override
double getDelta (const TStroke &stroke, double w) const override
This method compute the delta (gradient) referred to stroke in at parameter w.
double getMaxDiff () const override
Max diff of delta (This value indicates when it's necessary to insert control point)
const Potential * getPotential () const
void setDiff (double diff)
Change sensitivity of deformer (just for debug).
void getRange (double &from, double &to)
Retrieve the parameters range where is applied deformation.
virtual TThickPoint getDisplacement (const TStroke &stroke, double w) const =0
virtual TThickPoint getDisplacementForControlPoint (const TStroke &stroke, UINT n) const =0
virtual TThickPoint getDisplacementForControlPointLen (const TStroke &stroke, double cpLen) const =0
virtual double getDelta (const TStroke &stroke, double w) const =0
virtual double getMaxDiff () const =0
Detailed Description
This class implements new deformer.
New stroke deformer doesn't change last point of stroke.
Constructor & Destructor Documentation
StrokeParametricDeformer()
ToonzExt::StrokeParametricDeformer::StrokeParametricDeformer (double actionLength, double startParameter, TStroke * s, Potential * pot)
    : startParameter_(startParameter)
    , actionLength_(actionLength)
    , vx_(1.0)
    , vy_(1.0)
    , pot_(0) {
  diff_ = 0.001;
  try {
    ref_copy_ = new TStroke(*s);
  } catch (std::bad_alloc &) {
    throw std::invalid_argument("Not possible to have a copy of stroke!!!");
  }
  assert(0.0 <= startParameter_ && startParameter_ <= 1.0);
  // double
  //  max_length = s->getLength();
  //  if( actionLength == -1 )
  //  {
  //    assert(false && "Rispristina la vecchia gestione");
  //    actionLength_ = 2.0 * max_length;
  //  }
  //  else
  //  {
  assert(0.0 <= actionLength_);
  // && actionLength_ <= max_length );
  if (0.0 > actionLength_) actionLength_ = 0.0;
  // else if ( actionLength_ > max_length )
  //  actionLength_ = max_length;
  //}
  pot_ = pot;
  if (!pot_)
    throw std::invalid_argument("Not Possible to have a ref of Potential!!!");
  pot_->setParameters(ref_copy_, startParameter_, actionLength_);
  assert(pot_);
  startLength_ = startParameter_;
}
~StrokeParametricDeformer()
ToonzExt::StrokeParametricDeformer::~StrokeParametricDeformer ()
{
  delete pot_;
  delete ref_copy_;
}
Member Function Documentation
getDelta()
double ToonzExt::StrokeParametricDeformer::getDelta (const TStroke & stroke, double w) const override virtual
This method compute the delta (gradient) referred to stroke in at parameter w.
This value is the result of .
Note
Sometimes this value can be approximated.
Parameters
stroke Stroke to test
w Stroke parameter
Returns
the gradient in w
Implements TStrokeDeformation.
{
#if 0
  double  w0 = w;
  if(w0 == 1.0)
    return norm( stroke.getSpeed(1.0));
  double tmp = stroke.getLength(w0);
  tmp+=1.0;
  double w1 = stroke.getParameterAtLength(tmp);
  /*
  double  w1 = w + 0.01;
  if(w1>1.0)
  {
    w0 = 1.0 - 0.01;
    w1 = 1.0;
  }
  */
  const double  dx = 1.0; //stroke.getLength(w0,w1);
  TThickPoint pnt = this->getDisplacement(stroke,w1) -
                    this->getDisplacement(stroke,w0);
  double  dy =  sqrt( sq(pnt.x) + sq(pnt.y) + sq(pnt.thick) );
  assert(dx!=0.0);
  return dy/dx;
  /*
  // the increaser is wrong than this value need to be the deformation
  //  value
  // is norm
  TThickPoint pnt = this->getDisplacement(stroke,
                                          w);
  return sqrt( sq(pnt.x) + sq(pnt.y) + sq(pnt.thick) );
  //return pot_->gradient(w);
  */
#endif
  return this->getDisplacement(stroke, w).y;
}
References TStroke::getLength(), TStroke::getParameterAtLength(), and TStroke::getSpeed().
getDisplacement()
TThickPoint ToonzExt::StrokeParametricDeformer::getDisplacement (const TStroke & stroke, double w) const override virtual
Return displacement to use with function increaseControlPoints.
Parameters
stroke to test
w stroke parameter
Returns
displacement to apply to obtain deformation
See also
increaseControlPoints
Implements TStrokeDeformation.
{
  // conversion in absolute system for shape deformation
  double val = pot_->value(w);
  assert(val >= 0);
  // amplify movement
  return TThickPoint(vx_ * val, vy_ * val, 0.0);
}
getDisplacementForControlPoint()
TThickPoint ToonzExt::StrokeParametricDeformer::getDisplacementForControlPoint (const TStroke & stroke, UINT n) const override virtual
Return displacement to use with function modifyControlPoints.
Parameters
stroke to test
n control point to get
Returns
displacement to apply to obtain deformation
See also
modifyControlPoints
Implements TStrokeDeformation.
{
  double w = stroke.getParameterAtControlPoint(n);
  return this->getDisplacement(stroke, w);
}
References TStroke::getParameterAtControlPoint().
getDisplacementForControlPointLen()
TThickPoint ToonzExt::StrokeParametricDeformer::getDisplacementForControlPointLen (const TStroke & stroke, double cpLen) const override virtual
Implements TStrokeDeformation.
{
  return this->getDisplacement(stroke, cpLen);
}
getMaxDiff()
double ToonzExt::StrokeParametricDeformer::getMaxDiff () const override virtual
Max diff of delta (This value indicates when it's necessary to insert control point)
Returns
max displacement permitted
Implements TStrokeDeformation.
{ return diff_; }
getPotential()
const Potential * ToonzExt::StrokeParametricDeformer::getPotential () const inline
{ return pot_; }
getRange()
void ToonzExt::StrokeParametricDeformer::getRange (double & from, double & to)
Retrieve the parameters range where is applied deformation.
{
  double x     = ref_copy_->getLength(startParameter_);
  double delta = x - actionLength_ * 0.5;
  if (delta > 0)
    from = ref_copy_->getParameterAtLength(delta);
  else
    from = 0.0;
  delta = x + actionLength_ * 0.5;
  if (delta < ref_copy_->getLength())
    to = ref_copy_->getParameterAtLength(delta);
  else
    to = 1.0;
}
setDiff()
void ToonzExt::StrokeParametricDeformer::setDiff (double diff) inline
Change sensitivity of deformer (just for debug).
{ diff_ = diff; }
Referenced by ToonzExt::StrokeDeformationImpl::activate_impl().
setMouseMove()
void ToonzExt::StrokeParametricDeformer::setMouseMove (double vx, double vy)
Set mouse movement from last valid position.
Parameters
vx horyzontal
vy vertical
{
  vx_ = vx;
  vy_ = vy;
}
Referenced by ToonzExt::StrokeDeformationImpl::update_impl().
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/ext/StrokeParametricDeformer.h
E:/opentoonz/toonz/sources/tnzext/StrokeParametricDeformer.cpp