opentoonz: PinchTool Class Reference
PinchTool Class Reference
Public Member Functions
ToolType getToolType () const override
void setShowSelector (bool show)
void onEnter () override
Callback for the mouse entering the viewer area.
void onLeave () override
Callback for the mouse leaving the viewer area.
void updateTranslation () override
void draw () override
Draws the tool on the viewer.
void leftButtonDown (const TPointD &pos, const TMouseEvent &) override
void leftButtonDrag (const TPointD &pos, const TMouseEvent &e) override
void leftButtonUp (const TPointD &pos, const TMouseEvent &e) override
void invalidateCursorArea ()
void mouseMove (const TPointD &pos, const TMouseEvent &e) override
bool moveCursor (const TPointD &pos)
bool keyDown (QKeyEvent *) override
void onActivate () override
Callback invoked whenever the tool activates.
void onDeactivate () override
Callback for tool deactivation, includes tool switch.
void update (const TGlobalChange &)
void onImageChanged () override
Notifies changes in the image in use.
int getCursorId () const override
Returns the type of cursor used by the tool.
TPropertyGroup * getProperties (int targetType) override
Public Member Functions inherited from TTool
TTool (std::string toolName)
every tool (invoking updateTranslation() for each).
virtual ToolType getToolType () const =0
ToolTargetType getTargetType () const
std::string getName () const
virtual ToolOptionsBox * createOptionsBox ()
void setViewer (Viewer *viewer)
Viewer * getViewer () const
double getPixelSize () const
void invalidate (const TRectD &rect=TRectD())
int pick (const TPointD &p)
bool isPicking () const
virtual void updateTranslation ()
virtual bool preLeftButtonDown ()
virtual void mouseMove (const TPointD &, const TMouseEvent &)
virtual void leftButtonDown (const TPointD &, const TMouseEvent &)
virtual void leftButtonDrag (const TPointD &, const TMouseEvent &)
virtual void leftButtonUp (const TPointD &, const TMouseEvent &)
virtual void leftButtonDoubleClick (const TPointD &, const TMouseEvent &)
virtual void rightButtonDown (const TPointD &, const TMouseEvent &)
virtual bool keyDown (QKeyEvent *)
virtual void onInputText (std::wstring, std::wstring, int, int)
virtual void onSetViewer ()
virtual void onActivate ()
Callback invoked whenever the tool activates.
virtual void onDeactivate ()
Callback for tool deactivation, includes tool switch.
virtual void onImageChanged ()
Notifies changes in the image in use.
virtual void onEnter ()
Callback for the mouse entering the viewer area.
virtual void onLeave ()
Callback for the mouse leaving the viewer area.
virtual void onFrameSwitched ()
virtual void reset ()
virtual void draw ()
Draws the tool on the viewer.
bool isActive () const
Used to know if a tool is active, (used in TextTool only).
void setActive (bool active)
virtual TPropertyGroup * getProperties (int)
virtual bool onPropertyChanged (std::string propertyName)
virtual TSelection * getSelection ()
Returns a pointer to the tool selection.
virtual int getCursorId () const
Returns the type of cursor used by the tool.
virtual bool isEventAcceptable (QEvent *e)
TXsheet * getXsheet () const
Returns a pointer to the actual Xsheet.
int getFrame ()
Returns the actual frame in use.
int getColumnIndex ()
Returns the actual column index.
TStageObjectId getObjectId () const
Returns a pointer to the actual stage object.
void notifyImageChanged ()
void notifyImageChanged (const TFrameId &fid)
images on the level view.
TFrameId getCurrentFid () const
Returns the number of the actual editing frame.
const TAffine & getMatrix () const
void setMatrix (const TAffine &matrix)
TAffine getCurrentColumnMatrix (int frame=-1) const
TAffine getCurrentColumnParentMatrix () const
TAffine getCurrentObjectParentMatrix () const
TAffine getCurrentObjectParentMatrix2 () const
TAffine getColumnMatrix (int index, int frame=-1) const
virtual void updateMatrix ()
virtual void addContextMenuItems (QMenu *menu)
void enable (bool on)
bool isEnabled () const
QString updateEnabled ()
virtual QString updateEnabled (int rowIndex, int columnIndex)
bool isColumnLocked (int columnIndex) const
void resetInputMethod ()
Resets Input Context (IME)
virtual bool isPencilModeActive ()
virtual bool isDragging () const
void setSelectedFrames (const std::set< TFrameId > &selectedFrames)
void tweenSelectedGuideStrokes ()
void tweenGuideStrokeToSelected ()
void flipGuideStrokeDirection (int mode)
Additional Inherited Members
Public Types inherited from TTool
enum ToolType {
GenericTool = 1 , ColumnTool = 2 , LevelReadTool = 4 , LevelWriteTool ,
LevelTool = LevelReadTool | LevelWriteTool
}
Tool editing type.
enum ToolTargetType {
NoTarget = 0x0 , VectorImage = 0x1 , ToonzImage = 0x2 , RasterImage = 0x4 ,
MeshImage = 0x8 , Splines = 0x10 , LevelColumns = 0x20 , MeshColumns = 0x40 ,
EmptyTarget = 0x80 , CommonImages = VectorImage | ToonzImage | RasterImage , AllImages = CommonImages | MeshImage , Vectors = VectorImage | Splines ,
CommonLevels = CommonImages | LevelColumns , MeshLevels = MeshImage | MeshColumns , AllTargets = 0xffffffff
}
Object types the tool can operate on.
typedef TApplication Application
Static Public Member Functions inherited from TTool
static TTool * getTool (std::string toolName, ToolTargetType targetType)
static TApplication * getApplication ()
static void setApplication (TApplication *application)
static TXshCell getImageCell ()
Returns the level-frame pair to be edited by the tool.
static TImage * getImage (bool toBeModified, int subsampling=0)
Returns the image to be edited by the tool.
static TImage * touchImage ()
static void updateToolsPropertiesTranslation ()
static const std::set< TFrameId > & getSelectedFrames ()
Static Public Attributes inherited from TTool
static std::vector< CellOps > m_cellsData
static bool m_isLevelCreated = false
static bool m_isFrameCreated = false
static std::vector< TFrameId > m_oldFids
static std::vector< TFrameId > m_newFids
static bool m_isLevelRenumbererd = false
Protected Member Functions inherited from TTool
void bind (int targetType)
virtual void onSelectedFramesChanged ()
virtual QString disableString ()
Returns a custom reason to disable the tool.
Protected Attributes inherited from TTool
std::string m_name
The tool's name.
Viewer * m_viewer
Tool's current viewer.
TAffine m_matrix
World-to-window reference change affine.
int m_targetType
The tool's image type target.
bool m_enabled
Whether the tool allows user interaction.
bool m_active
bool m_picking
Static Protected Attributes inherited from TTool
static TApplication * m_application = 0
static std::set< TFrameId > m_selectedFrames = std::set<TFrameId>()
Detailed Description
Constructor & Destructor Documentation
PinchTool()
PinchTool::PinchTool ()
    : TTool("T_Pinch")
    , m_active(false)
    , m_cursorEnabled(false)
    , m_draw(false)
    , m_undo(0)
    , m_showSelector(true)
    , m_toolRange("Size:", 1.0, 10000.0, 500.0)  // W_ToolOptions_PinchTool
    , m_toolCornerSize("Corner:", 1.0, 180.0,
                       160.0)          // W_ToolOptions_PinchCorner
    , m_autoOrManual("Manual", false)  // W_ToolOptions_PinchManual
    , m_deformation(new ToonzExt::StrokeDeformation)
    , m_selector(500, 10, 1000) {
  bind(TTool::Vectors);
  m_toolRange.setNonLinearSlider();
  m_prop.bind(m_toolCornerSize);
  m_prop.bind(m_autoOrManual);
  m_prop.bind(m_toolRange);
  CornerDeformation::instance()->setCursorId(ToolCursor::PinchWaveCursor);
  SmoothDeformation::instance()->setCursorId(ToolCursor::PinchCursor);
  StraightCornerDeformation::instance()->setCursorId(
      ToolCursor::PinchAngleCursor);
  assert(m_deformation && "Can not create a deformation CATASTROFIC!!!");
  TMouseEvent dummy;
  updateInterfaceStatus(dummy);
  m_autoOrManual.setId("Manual");
}
~PinchTool()
PinchTool::~PinchTool () virtual
                      {
  delete m_deformation;
  m_deformation = 0;
}
Member Function Documentation
draw()
void PinchTool::draw () override virtual
Draws the tool on the viewer.
Reimplemented from TTool.
                     {
  GLMatrixGuard guard;
  TVectorImageP img(getImage(true));
  if (!img ||
      img->getStrokeCount() ==
          0)  // Controllo che il numero degli stroke nell'immagine sia != 0
    return;
  if (!m_draw) return;
  ContextStatus *status = &m_status;
  if (!status) return;
  StrokeDeformation *deformation = m_deformation;
  OverallDesigner designer((int)m_curr.x, (int)m_curr.y);
  // m_active == true means that a button down is done (drag)
  if (!m_active) {
    if (m_cursorEnabled) {
      glColor3d(1, 0, 1);
      if (m_cursor.thick > 0) tglDrawCircle(m_cursor, m_cursor.thick);
      tglDrawCircle(m_cursor, m_cursor.thick + 4 * status->pixelSize_);
    }
  }
  // internal deformer can be changed during draw
  if (!m_selector.isSelected()) deformation->draw(&designer);
  m_selector.draw(&designer);
  CHECK_ERRORS_BY_GL;
}
References TTool::getImage().
getCursorId()
int PinchTool::getCursorId () const inline override virtual
Returns the type of cursor used by the tool.
See also
For a list of cursor ids cursor.h
Reimplemented from TTool.
{ return updateCursor(); }
getProperties()
TPropertyGroup * PinchTool::getProperties (int targetType) inline override virtual
Reimplemented from TTool.
{ return &m_prop; }
getToolType()
ToolType PinchTool::getToolType () const inline override virtual
Implements TTool.
{ return TTool::LevelWriteTool; }
invalidateCursorArea()
void PinchTool::invalidateCursorArea ()
{
  double r = m_cursor.thick + 6;
  TPointD d(r, r);
  invalidate(TRectD(m_cursor - d, m_cursor + d));
}
keyDown()
bool PinchTool::keyDown (QKeyEvent * event) override virtual
Reimplemented from TTool.
{
  if (!m_active) m_deformation->reset();
#if 0
  char c = (char)key;
  if(c == 'p' ||
     c == 'P' )
  {
    TVectorImageP vimage(getImage());
    if(!vimage)
      return false;
    char  fileName[] = {"c:\\toonz_input.sdd"};
    ofstream  out_file(fileName);
    if(!out_file)
    {
      cerr<<"Error on opening: "<<fileName<<endl;
      return false;
    }
    out_file<<"# VImage info\n";
    out_file<<"# Number of stroke:\n";
    const int max_number_of_strokes = vimage->getStrokeCount();
    out_file<<max_number_of_strokes<<endl;
    int number_of_strokes = 0;
    const int cp_for_row=3;
    while( number_of_strokes<max_number_of_strokes)
    {
      TStroke* ref = vimage->getStroke(number_of_strokes);
      out_file<<endl;
      out_file<<"# Number of control points for stroke:\n";
      const int max_number_of_cp = ref->getControlPointCount();
      out_file<<max_number_of_cp <<endl;
      out_file<<"# Control Points:\n";
      int number_of_cp=0;
      while( number_of_cp<max_number_of_cp )
      {
        out_file<<ref->getControlPoint(number_of_cp)<<" ";
        if(!((number_of_cp+1)%cp_for_row)) // add a new line after ten points
          out_file<<endl;
        number_of_cp++;
      }
      out_file<<endl;
      number_of_strokes++;
    }
  }
#endif
  return false;
}
leftButtonDown()
void PinchTool::leftButtonDown (const TPointD & pos, const TMouseEvent & event) override virtual
Reimplemented from TTool.
{
  if (getViewer() && getViewer()->getGuidedStrokePickerMode()) {
    getViewer()->doPickGuideStroke(pos);
    return;
  }
  m_curr = m_down = pos;
  if (!m_active && !m_selector.isSelected()) {
    m_active = false;
    assert(m_undo == 0);
    StrokeDeformation *deformation = m_deformation;
    TVectorImageP vi = TImageP(getImage(true));
    if (!vi) return;
    m_active = true;
    ContextStatus *status = &m_status;
    // reset status
    status->init();
    double w, dist2;
    // find nearest stroke
    if (vi->getNearestStroke(m_down, w, m_n, dist2, true)) {
      TStroke *stroke = vi->getStroke(m_n);
      assert(stroke && "Not valid stroke found!!!");
      if (!stroke) return;
      updateStrokeStatus(stroke, w);
      // set parameters from sliders
      updateInterfaceStatus(event);
      deformation->activate(status);
      // stroke can be changed (replaced by another) during deformation activate
      if (TTool::getApplication()->getCurrentObject()->isSpline())
        m_undo = new ToolUtils::UndoPath(
            getXsheet()->getStageObject(getObjectId())->getSpline());
      else {
        TXshSimpleLevel *sl =
            TTool::getApplication()->getCurrentLevel()->getSimpleLevel();
        assert(sl);
        TFrameId id = getCurrentFid();
        m_undo      = new UndoModifyStrokeAndPaint(sl, id, m_n);
      }
    }
  }
  m_selector.mouseDown(m_curr);
  m_prev = m_curr;
  invalidate();
}
leftButtonDrag()
void PinchTool::leftButtonDrag (const TPointD & pos, const TMouseEvent & e) override virtual
Reimplemented from TTool.
{
  m_curr = pos;
  if (m_selector.isSelected()) {
    m_selector.mouseDrag(m_curr);
    TDoubleProperty::Range prop_range = m_toolRange.getRange();
    double val_in_range               = m_selector.getLength();
    // set value in range
    val_in_range =
        std::max(std::min(val_in_range, prop_range.second), prop_range.first);
    try {
      m_toolRange.setValue(val_in_range);
      TTool::getApplication()->getCurrentTool()->notifyToolChanged();
    } catch (TDoubleProperty::RangeError &) {
      m_toolRange.setValue((prop_range.first + prop_range.second) * 0.5);
      TTool::getApplication()->getCurrentTool()->notifyToolChanged();
    }
    m_selector.setLength(m_toolRange.getValue());
  } else {
    TVectorImageP vi(getImage(true));
    ContextStatus *status = &m_status;
    if (!vi || !status->stroke2change_ || !m_active) return;
    QMutexLocker lock(vi->getMutex());
    // assert( status->stroke2change_->getLength() >= 0.0 );
    StrokeDeformation *deformation = m_deformation;
    TPointD delta = m_curr - m_prev;
    deformation->update(delta);
  }
  m_prev = m_curr;
  // moveCursor(pos);
  invalidate();
}
leftButtonUp()
void PinchTool::leftButtonUp (const TPointD & pos, const TMouseEvent & e) override virtual
Reimplemented from TTool.
{
  if (!m_active || m_selector.isSelected()) return;
  m_active = false;
  TVectorImageP vi(getImage(true));
  ContextStatus *status = &m_status;
  if (!vi || !status->stroke2change_) {
    delete m_undo;
    m_undo = 0;
    return;
  }
  // if mouse position is unchanged doesn't modify current stroke
  if (areAlmostEqual(m_down, pos, PickRadius * status->pixelSize_)) {
    assert(m_undo);
    delete m_undo;
    m_undo = 0;
// to avoid red line tool on stroke
#ifdef _WIN32
    invalidate(
        status->stroke2change_->getBBox().enlarge(status->pixelSize_ * 13));
#else
    invalidate();
#endif
    m_deformation->deactivate();
    status->stroke2change_ = 0;
    return;
  }
  QMutexLocker lock(vi->getMutex());
  TStroke *deactivateStroke          = m_deformation->deactivate();
  deactivateStroke->outlineOptions() = status->stroke2change_->outlineOptions();
  replaceStroke(status->stroke2change_, deactivateStroke, m_n, vi);
  status->stroke2change_ = 0;
  vi->notifyChangedStrokes(m_n);
#ifdef _DEBUG
  vi->checkIntersections();
#endif
  invalidate();
#ifdef _DEBUG
  vi->checkIntersections();
#endif
  moveCursor(pos);
  notifyImageChanged();
  assert(m_undo);
  TUndoManager::manager()->add(m_undo);
  m_undo = 0;
}
mouseMove()
void PinchTool::mouseMove (const TPointD & pos, const TMouseEvent & e) override virtual
Reimplemented from TTool.
{
  if (m_active) return;
  if (!m_draw) m_draw = true;
  ContextStatus *status = &m_status;
  m_curr                = pos;
  const int pixelRange = 3;
  if (std::abs(m_lastMouseEvent.m_pos.x - event.m_pos.x) < pixelRange &&
      std::abs(m_lastMouseEvent.m_pos.y - event.m_pos.y) < pixelRange &&
      m_lastMouseEvent.getModifiersMask() == event.getModifiersMask())
    return;
  m_lastMouseEvent = event;
  double w         = 0;
  TStroke *stroke  = getClosestStroke(pos, w);
  if (stroke) {
    // set parameters from sliders
    updateInterfaceStatus(event);
    // update information about current stroke
    updateStrokeStatus(stroke, w);
    // retrieve the current m_deformation and
    // prepare to design and modify
    if (m_deformation) m_deformation->check(status);
    m_selector.setStroke(stroke);
    m_selector.mouseMove(m_curr);
  } else {
    m_status.stroke2change_ = 0;
    m_selector.setStroke(0);
    return;
  }
  m_prev          = m_curr;
  m_cursorEnabled = moveCursor(pos);
  if (m_cursorEnabled) invalidate();
  //  TNotifier::instance()->notify(TToolChange());
}
moveCursor()
bool PinchTool::moveCursor (const TPointD & pos)
{
  double w        = 0.0;
  TStroke *stroke = getClosestStroke(pos, w);
  if (!stroke) return false;
  m_cursor = stroke->getThickPoint(w);
  return true;
}
onActivate()
void PinchTool::onActivate () override virtual
Callback invoked whenever the tool activates.
Reimplemented from TTool.
{
  //  getApplication()->editImageOrSpline();
  //  TNotifier::instance()->attach(this);
  // per sicurezza
  m_status.stroke2change_ = 0;
  m_selector.setStroke(0);
}
onDeactivate()
void PinchTool::onDeactivate () override virtual
Callback for tool deactivation, includes tool switch.
Reimplemented from TTool.
{
  m_draw = false;
  delete m_undo;
  m_undo   = 0;
  m_active = false;
  m_deformation->reset();
  //  TNotifier::instance()->detach(this);
}
References ToonzExt::StrokeDeformation::reset().
onEnter()
void PinchTool::onEnter () override virtual
Callback for the mouse entering the viewer area.
Reimplemented from TTool.
{
  m_draw = true;
  // per sicurezza
  // m_status.stroke2change_ = 0;
  // m_selector.setStroke(0);
}
onImageChanged()
void PinchTool::onImageChanged () override virtual
Notifies changes in the image in use.
Reimplemented from TTool.
{
  m_status.stroke2change_ = 0;
  m_deformation->reset();
  // m_active may be true if the frame switched while dragging
  if (m_active) {
    m_deformation->deactivate();
    m_active = false;
    if (m_undo) {
      delete m_undo;
      m_undo = 0;
    }
  }
  double w        = 0;
  TStroke *stroke = getClosestStroke(m_lastMouseEvent.m_pos, w);
  if (stroke) {
    // set parameters from sliders
    updateInterfaceStatus(m_lastMouseEvent);
    // update information about current stroke
    updateStrokeStatus(stroke, w);
  }
  m_selector.setStroke(stroke);
  invalidate();
}
References ToonzExt::StrokeDeformation::deactivate(), TTool::invalidate(), TMouseEvent::m_pos, and ToonzExt::StrokeDeformation::reset().
onLeave()
void PinchTool::onLeave () override virtual
Callback for the mouse leaving the viewer area.
Reimplemented from TTool.
{
  if (!m_active) m_draw = false;
  m_status.stroke2change_ = 0;
  // Abbiamo dovuto commentarlo perche' stranamente
  // l'onLeave viene chiamata anche quando viene premuto il tasto del mouse
  // per iniziare a fare drag utilizzando il Selector
  // setStroke al suo interno resetta lo status del Selector (lo mette a NONE)
  //  m_selector.setStroke(0);
  m_deformation->reset();
}
References ToonzExt::StrokeDeformation::reset().
setShowSelector()
void PinchTool::setShowSelector (bool show) inline
{ m_showSelector = show; }
update()
void PinchTool::update (const TGlobalChange &)
{
  m_cursor = TConsts::natp;
  m_selector.setStroke(0);
  m_selector.setVisibility(m_autoOrManual.getValue() && m_showSelector);
  if (m_deformation) delete m_deformation->deactivate();
  // per sicurezza
  m_status.stroke2change_ = 0;
}
updateTranslation()
void PinchTool::updateTranslation () override virtual
Reimplemented from TTool.
{
  m_toolRange.setQStringName(tr("Size:"));
  m_toolCornerSize.setQStringName(tr("Corner:"));
  m_autoOrManual.setQStringName(tr("Manual"));
}
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/tools/pinchtool.h
E:/opentoonz/toonz/sources/tnztools/pinchtool.cpp