opentoonz: ToonzExt::StrokeDeformationImpl Class Reference
ToonzExt::StrokeDeformationImpl Class Reference abstract
Public Member Functions
ToonzExt::Interval getExtremes ()
const TStroke * getStrokeSelected () const
const TStroke * getCopiedStroke () const
virtual bool activate_impl (const ContextStatus *)
virtual void update_impl (const TPointD &delta)
virtual TStroke * deactivate_impl ()
bool check (const ContextStatus *)
virtual void reset ()
void setPotential (Potential *)
virtual void draw (Designer *)
TStroke * getTransformedStroke ()
ToonzExt::Potential * getPotential ()
TPointD & oldW0 ()
int getShortcutKey () const
int getCursorId () const
void setCursorId (int id)
Static Public Member Functions
static const ContextStatus *& getImplStatus ()
Protected Member Functions
virtual bool check_ (const ContextStatus *)=0
virtual bool findExtremes_ (const ContextStatus *, Interval &)=0
virtual double findActionLength ()=0
Static Protected Member Functions
static TStroke *& getLastSelectedStroke ()
static void setLastSelectedStroke (TStroke *)
static int & getLastSelectedDegree ()
static void setLastSelectedDegree (int degree)
static ToonzExt::Intervals & getSpiresList ()
static ToonzExt::Intervals & getStraightsList ()
Protected Attributes
TStroke * stroke2manipulate_
ToonzExt::StrokeParametricDeformer * deformer_
int shortcutKey_
double old_w0_
TPointD old_w0_pos_
std::vector< TStroke * > strokes_
Detailed Description
Constructor & Destructor Documentation
StrokeDeformationImpl()
StrokeDeformationImpl::StrokeDeformationImpl () protected
{
  shortcutKey_ = ContextStatus::NONE;
  cursorId_    = -1;
  this->reset();
}
~StrokeDeformationImpl()
StrokeDeformationImpl::~StrokeDeformationImpl () virtual
{
  clearPointerContainer(strokes_);
  delete potential_;
  potential_ = 0;
  delete deformer_;
  deformer_ = 0;
  delete copyOfLastSelectedStroke_;
  copyOfLastSelectedStroke_ = 0;
}
Member Function Documentation
activate_impl()
bool StrokeDeformationImpl::activate_impl (const ContextStatus * status) virtual
Wrapper for activate.
{
  assert(status && "Not status available");
  if (!status || !this->init(status)) return false;
  double w = status->w_;
  ToonzExt::Interval extremes = this->getExtremes();
  TStroke *stroke2transform;
  if (!this->computeStroke2Transform(status, stroke2transform, w, extremes))
    return false;
  // to avoid strange behaviour in limit's value
  if (areAlmostEqual(extremes.first, w)) w = extremes.first;
  if (areAlmostEqual(extremes.second, w)) w = extremes.second;
  assert(extremes.first <= w && w <= extremes.second);
  if (extremes.first > w || w > extremes.second) {
    return false;
  }
  std::vector<double> splitParameter;
  splitParameter.push_back(extremes.first);
  splitParameter.push_back(extremes.second);
  assert(strokes_.empty());
  if (!strokes_.empty()) clearPointerContainer(strokes_);
  splitStroke(*stroke2transform, splitParameter, strokes_);
  assert(strokes_.size() == 3);
  // I don't know how to manage properly this case
  if (strokes_.size() != 3) {
    clearPointerContainer(strokes_);
    return false;
  }
  // stroke to change
  stroke2manipulate_ = strokes_[1];
  assert(stroke2manipulate_ && " Not valid reference to stroke to move!!!");
  if (!stroke2manipulate_) return false;
  // remove empty stroke
  {
    TStroke *tmp_stroke = strokes_[2];
    if (isAlmostZero(tmp_stroke->getLength())) {
      std::vector<TStroke *>::iterator it = strokes_.begin();
      std::advance(it, 2);
      strokes_.erase(it);
      delete tmp_stroke;
    }
    tmp_stroke = strokes_[0];
    if (isAlmostZero(tmp_stroke->getLength())) {
      strokes_.erase(strokes_.begin());
      delete tmp_stroke;
    }
    // little movement of control points to have not empty
    //  length
    if (isAlmostZero(stroke2manipulate_->getLength())) {
      int count = stroke2manipulate_->getControlPointCount() - 1;
      assert(count > 0);
      TThickPoint pnt0  = stroke2manipulate_->getControlPoint(0),
                  pntn  = stroke2manipulate_->getControlPoint(count),
                  delta = TThickPoint(2.0 * TConsts::epsilon,
                                      -2.0 * TConsts::epsilon, 0.0);
      stroke2manipulate_->setControlPoint(0, pnt0 - delta);
      stroke2manipulate_->setControlPoint(count, pntn + delta);
    }
  }
  // simple check for empty chunk
  int cp_count = stroke2manipulate_->getChunkCount();
  const TThickQuadratic *tq;
  bool haveEmpty = false;
  while (--cp_count >= 0) {
    tq = stroke2manipulate_->getChunk(cp_count);
    //    assert( tq->getLength() != 0.0 );
    if (tq->getLength() == 0.0) haveEmpty = true;
  }
  if (haveEmpty) {
    const double reductionFactor =
        computeReductionFactor(getImplStatus()->pixelSize_, 1.0);
    stroke2manipulate_->reduceControlPoints(reductionFactor);
  }
  TPointD pntOnStroke = stroke2transform->getPoint(w);
  // parameter need to be recomputed to match
  // with new stroke
  w = stroke2manipulate_->getW(pntOnStroke);
  //  prevStyle_ = stroke2transform->getStyle();
  //  set a style for error
  //  stroke2manipulate_->setStyle( 4 );
  // in this deformer all stroke need to be moved
  double lengthOfAction = this->findActionLength();
  bool exception = false;
  try {
    // create a new stroke deformer
    delete deformer_;
    deformer_ = new StrokeParametricDeformer(
        lengthOfAction, w, stroke2manipulate_, potential_->clone());
  } catch (std::invalid_argument &) {
    exception = true;
    assert(!"Invalid argument");
  } catch (...) {
    exception = true;
  }
  assert(deformer_ && "Deformer is not available");
  if (exception) {
    deformer_ = 0;
    return false;
  }
  assert(getImplStatus() != 0 && "ContextStatus is null???");
  if (!getImplStatus()) {
    delete deformer_;
    this->reset();
    return false;
  }
  // change the threshold value of increser,
  //  if value is greater than diff add control points
  deformer_->setDiff(getImplStatus()->deformerSensitivity_);
  // just to be sure to have a control point where
  // stroke is selected
  stroke2manipulate_->insertControlPoints(w);
  //  two different case:
  //  (1) point at w=0 is not in stroke to transform
  //  (2) point at w=0 is in stroke to transform
  //  in case (2) it is mandatory to retrieve the
  //  parameter where stroke2transform is equal to
  //  w=0 and store it.
  //  old_w0_pos_ will be used in deactivate method
  if (old_w0_pos_ != TConsts::napd) {
    double w    = stroke2manipulate_->getW(old_w0_pos_);
    TPointD pnt = stroke2manipulate_->getPoint(w);
    if (tdistance2(pnt, old_w0_pos_) < sq(TConsts::epsilon)) {
      // the this position can be modifyed during drag
      old_w0_ = w;
    } else
      old_w0_ = -1;
  }
  bool test = increaseControlPoints(*stroke2manipulate_, *deformer_,
                                    getImplStatus()->pixelSize_);
  /*
// New Increaser behaviour
deformer_->setMouseMove(0,100);
extremes_ = Toonz::increase_cp (stroke2manipulate_,
deformer_);
//*/
  if (!test) return false;
  stroke2manipulate_->disableComputeOfCaches();
  return true;
}
References ToonzExt::Potential::clone(), TStroke::disableComputeOfCaches(), TStroke::getChunk(), TStroke::getChunkCount(), TStroke::getControlPoint(), TStroke::getControlPointCount(), TQuadratic::getLength(), TStroke::getLength(), TStroke::getPoint(), TStroke::getW(), TStroke::insertControlPoints(), TStroke::reduceControlPoints(), reset(), TStroke::setControlPoint(), and ToonzExt::StrokeParametricDeformer::setDiff().
Referenced by ToonzExt::StrokeDeformation::activate().
check()
bool StrokeDeformationImpl::check (const ContextStatus * status)
{
  if (!status || !this->init(status)) return false;
  return this->check_(status);
}
check_()
virtual bool ToonzExt::StrokeDeformationImpl::check_ (const ContextStatus *) protected pure virtual
Is this the correct deformation?
Implemented in ToonzExt::CornerDeformation, ToonzExt::SmoothDeformation, and ToonzExt::StraightCornerDeformation.
deactivate_impl()
TStroke * StrokeDeformationImpl::deactivate_impl () virtual
Reduce control points and change stroke.
{
  if (!stroke2manipulate_ || !getImplStatus()) {
    this->reset();
    return 0;
  }
  // retrieve the point
  if (old_w0_ != -1) old_w0_pos_ = stroke2manipulate_->getPoint(old_w0_);
  const double reductionFactor =
      computeReductionFactor(getImplStatus()->pixelSize_, 3.0);
  // stroke2manipulate_->enableComputeOfCaches ();
  // stroke2manipulate_->reduceControlPoints (reductionFactor);
  const int size = stroke2manipulate_->getControlPointCount();
  std::vector<TThickPoint> pnt(size);
  for (int i = 0; i < size; ++i)
    pnt[i]   = stroke2manipulate_->getControlPoint(i);
  std::vector<TStroke *>::iterator it =
      std::find(strokes_.begin(), strokes_.end(), stroke2manipulate_);
  assert(it != strokes_.end());
  int pos            = std::distance(strokes_.begin(), it);
  stroke2manipulate_ = 0;
  delete strokes_[pos];
  TStroke *tmpStroke = new TStroke(pnt);
  assert((tmpStroke != 0) && "Not valid stroke!");
  strokes_[pos] = tmpStroke;
  strokes_[pos]->reduceControlPoints(reductionFactor);
  // strokes_[pos] = TStroke::interpolate(pnt,
  //                                   reductionFactor,
  //                                   false);
  TStroke *ref = Toonz::merge(strokes_);
  ToonzExt::cloneStrokeStatus(getImplStatus()->stroke2change_, ref);
  if (old_w0_pos_ != TConsts::napd) {
    // restore (if necessary) the initial position of
    // a stroke
    TStroke *rotated = rotateControlPointAtPoint(ref, old_w0_pos_);
    if (rotated) {
      delete ref;
      ref = rotated;
      if (getImplStatus())
        ToonzExt::cloneStrokeStatus(getImplStatus()->stroke2change_, ref);
      else {
        delete ref;
        ref = 0;
      }
    }
  }
  this->reset();
  return ref;
}
References ToonzExt::cloneStrokeStatus(), TStroke::getControlPoint(), TStroke::getControlPointCount(), TStroke::getPoint(), and reset().
Referenced by ToonzExt::StrokeDeformation::deactivate().
draw()
void StrokeDeformationImpl::draw (Designer * designer) virtual
Apply a designer on current deformation.
Reimplemented in ToonzExt::CornerDeformation, ToonzExt::SmoothDeformation, and ToonzExt::StraightCornerDeformation.
{}
Referenced by ToonzExt::StrokeDeformation::draw(), ToonzExt::CornerDeformation::draw(), ToonzExt::SmoothDeformation::draw(), and ToonzExt::StraightCornerDeformation::draw().
findExtremes_()
virtual bool ToonzExt::StrokeDeformationImpl::findExtremes_ (const ContextStatus * , Interval &) protected pure virtual
Retrieve the nearest extremes to point selected.
Implemented in ToonzExt::CornerDeformation, ToonzExt::SmoothDeformation, and ToonzExt::StraightCornerDeformation.
getCopiedStroke()
const TStroke * ToonzExt::StrokeDeformationImpl::getCopiedStroke () const inline
{ return this->getStrokeSelected(); }
getCursorId()
int ToonzExt::StrokeDeformationImpl::getCursorId () const inline
{ return cursorId_; }
getExtremes()
ToonzExt::Interval StrokeDeformationImpl::getExtremes ()
{
  ToonzExt::Interval extremes = ToonzExt::Interval(-1.0, -1.0);
  if (!getImplStatus()) return extremes;
  // if it is manual
  if (getImplStatus()->isManual_ == true) {
    findExtremesFromActionLength(getImplStatus()->lengthOfAction_,
                                 getImplStatus()->stroke2change_,
                                 getImplStatus()->w_, extremes);
  } else {
    // if there are some special key down all will be managed in deformation
    this->findExtremes_(getImplStatus(), extremes);
  }
  return extremes;
}
getImplStatus()
const ContextStatus *& StrokeDeformationImpl::getImplStatus () static
{
  // if multi threading this datas need to be serialized
  // a ref to status
  static const ContextStatus *contextStatus_instance;
  return contextStatus_instance;
}
getLastSelectedDegree()
int & StrokeDeformationImpl::getLastSelectedDegree () static protected
{
  static int lastSelectedDegree_instance;
  return lastSelectedDegree_instance;
}
getLastSelectedStroke()
TStroke *& StrokeDeformationImpl::getLastSelectedStroke () static protected
{
  static TStroke *lastSelectedStroke_instance;
  return lastSelectedStroke_instance;
}
getPotential()
ToonzExt::Potential * StrokeDeformationImpl::getPotential ()
{
  return this->potential_;
}
getShortcutKey()
int ToonzExt::StrokeDeformationImpl::getShortcutKey () const inline
{ return shortcutKey_; }
getSpiresList()
ToonzExt::Intervals & StrokeDeformationImpl::getSpiresList () static protected
{
  static ToonzExt::Intervals listOfSpire_instance;
  return listOfSpire_instance;
}
getStraightsList()
ToonzExt::Intervals & StrokeDeformationImpl::getStraightsList () static protected
{
  static ToonzExt::Intervals listOfStraight_instance;
  return listOfStraight_instance;
}
getStrokeSelected()
const TStroke * ToonzExt::StrokeDeformationImpl::getStrokeSelected () const inline
{
    if (getImplStatus()) return this->getImplStatus()->stroke2change_;
    return 0;
  }
getTransformedStroke()
TStroke * StrokeDeformationImpl::getTransformedStroke ()
{
  return this->stroke2manipulate_;
}
oldW0()
TPointD & StrokeDeformationImpl::oldW0 ()
{ return old_w0_pos_; }
reset()
void StrokeDeformationImpl::reset () virtual
Restore last good status.
{
  old_w0_     = -1;
  old_w0_pos_ = TConsts::napd;
  deformer_       = 0;
  getImplStatus() = 0;
  this->setLastSelectedDegree(-1);
  this->setLastSelectedStroke(0);
  this->getSpiresList().clear();
  this->getStraightsList().clear();
  stroke2manipulate_ = 0;
  clearPointerContainer(strokes_);  // stroke2move is deleted here (it
                                    // is in vector)
}
Referenced by ToonzExt::StrokeDeformation::activate(), activate_impl(), ToonzExt::StrokeDeformation::deactivate(), deactivate_impl(), and ToonzExt::StrokeDeformation::update().
setCursorId()
void ToonzExt::StrokeDeformationImpl::setCursorId (int id) inline
{ cursorId_ = id; }
setLastSelectedDegree()
void StrokeDeformationImpl::setLastSelectedDegree (int degree) static protected
{
  getLastSelectedDegree() = degree;
}
setLastSelectedStroke()
void StrokeDeformationImpl::setLastSelectedStroke (TStroke * stroke) static protected
{
  TStroke *&lastSelStroke = getLastSelectedStroke();
  lastSelStroke           = stroke;
  if (lastSelStroke) {
    delete copyOfLastSelectedStroke_;
    copyOfLastSelectedStroke_ = new TStroke(*lastSelStroke);
  }
}
setPotential()
void StrokeDeformationImpl::setPotential (Potential * potential)
{
  assert(potential);
  potential_ = potential;
}
update_impl()
void StrokeDeformationImpl::update_impl (const TPointD & delta) virtual
Modify stroke.
{
  assert(stroke2manipulate_ && deformer_ &&
         "Stroke and Deformer are available");
  if (!stroke2manipulate_ || !deformer_) return;
  // update delta in deformer
  deformer_->setMouseMove(delta.x, delta.y);
  modifyControlPoints(*stroke2manipulate_, *deformer_);
}
References ToonzExt::StrokeParametricDeformer::setMouseMove().
Referenced by ToonzExt::StrokeDeformation::update().
Member Data Documentation
deformer_
ToonzExt::StrokeParametricDeformer* ToonzExt::StrokeDeformationImpl::deformer_ protected
old_w0_
double ToonzExt::StrokeDeformationImpl::old_w0_ protected
old_w0_pos_
TPointD ToonzExt::StrokeDeformationImpl::old_w0_pos_ protected
shortcutKey_
int ToonzExt::StrokeDeformationImpl::shortcutKey_ protected
stroke2manipulate_
TStroke* ToonzExt::StrokeDeformationImpl::stroke2manipulate_ protected
strokes_
std::vector<TStroke *> ToonzExt::StrokeDeformationImpl::strokes_ protected
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/ext/StrokeDeformationImpl.h
E:/opentoonz/toonz/sources/tnzext/StrokeDeformationImpl.cpp