opentoonz: ShaderInterface::ShaderData Class Reference
ShaderInterface::ShaderData Class Reference final
Public Member Functions
bool isValid () const
Public Member Functions inherited from TPersist
virtual void loadData (TIStream &is)=0
virtual void saveData (TOStream &os)=0
std::string getStreamTag () const
virtual const TPersistDeclaration * getDeclaration () const =0
Public Attributes
QString m_name
A name associated to the shader action.
TFilePath m_path
The shader program's file path.
QOpenGLShader::ShaderType m_type
The shader type.
Protected Member Functions
void saveData (TOStream &os) override
void loadData (TIStream &is) override
Additional Inherited Members
Public Types inherited from TPersist
typedef TPersist * CreateProc()
Static Public Member Functions inherited from TPersist
static void declare (CreateProc *)
static TPersist * create (const std::string &name)
Detailed Description
Member Function Documentation
isValid()
bool ShaderInterface::ShaderData::isValid () const inline
{ return !m_path.isEmpty(); }
loadData()
void ShaderInterface::ShaderData::loadData (TIStream & is) override protected virtual
 This is a pure virtual function and must be overridden with a method
that implements the object loading from a stream (i.e take the object's features from a formatted data stream). For example the TStageObject class use his implementation to take the values of the parameters that characterizes a stage object as name, coordinates, etc... from a file. is is an input file stream
Implements TPersist.
{
  struct locals {
    inline static TFilePath getAbsolutePath(const TFilePath &file,
                                            const TFilePath &relTo) {
      QDir relToDir(
          QString::fromStdWString(relTo.getParentDir().getWideString()));
      QString absFileStr(relToDir.absoluteFilePath(
          QString::fromStdWString(file.getWideString())));
      return TFilePath(absFileStr.toStdWString());
    }
  };
  std::string tagName;
  while (is.openChild(tagName)) {
    if (tagName == l_names[NAME])
      is >> m_name, is.closeChild();
    else if (tagName == l_names[PROGRAM_FILE]) {
      is >> m_path;
      m_path = locals::getAbsolutePath(m_path, is.getFilePath());
      is.closeChild();
    } else
      ::skipTag(is, tagName);
  }
}
References TIStream::closeChild(), TIStream::getFilePath(), TFilePath::getParentDir(), and TIStream::openChild().
saveData()
void ShaderInterface::ShaderData::saveData (TOStream & os) override protected virtual
 This is a pure virtual function and must be overridden with a method
that implements the object saving to a data stream (i.e put the object's features on a formatted data stream). For example the TStageObject class use his implementation to save the values of the parameters that characterizes a stage object as name, coordinates, etc... on a file os is an output file stream.
Implements TPersist.
{
  struct locals {
    inline static TFilePath getRelativePath(const TFilePath &file,
                                            const TFilePath &relTo) {
      QDir relToDir(
          QString::fromStdWString(relTo.getParentDir().getWideString()));
      QString relFileStr(relToDir.relativeFilePath(
          QString::fromStdWString(file.getWideString())));
      return TFilePath(relFileStr.toStdWString());
    }
  };
  os.openChild(l_names[NAME]);
  os << m_name;
  os.closeChild();
  os.openChild(l_names[PROGRAM_FILE]);
  os << locals::getRelativePath(m_path, os.getFilePath());
  os.closeChild();
}
References TOStream::closeChild(), TOStream::getFilePath(), TFilePath::getParentDir(), m_name, m_path, and TOStream::openChild().
Member Data Documentation
m_name
QString ShaderInterface::ShaderData::m_name
A name associated to the shader action.
Referenced by saveData().
m_path
TFilePath ShaderInterface::ShaderData::m_path
The shader program's file path.
Referenced by ShaderInterface::makeProgram(), and saveData().
m_type
QOpenGLShader::ShaderType ShaderInterface::ShaderData::m_type
The shader type.
Referenced by ShaderInterface::loadData(), and ShaderInterface::makeProgram().
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/stdfx/shaderinterface.h
E:/opentoonz/toonz/sources/stdfx/shaderinterface.cpp