opentoonz: FrameNavigator Class Reference
FrameNavigator Class Reference final
The FrameNavigator is a simple toolbar widget showing a numerical representation of an integer timeline.
#include <framenavigator.h>
Public Slots
void setFrame (int frame, bool notifyFrameHandler)
void prevFrame ()
Move to previous frame.
void nextFrame ()
Move to next frame.
Signals
void frameSwitched ()
Public Member Functions
FrameNavigator (QWidget *parent=0)
int getFrame () const
void setFrameHandle (TFrameHandle *)
bool anyWidgetHasFocus ()
Protected Slots
void onEditingFinished ()
void onFrameSwitched ()
Protected Member Functions
void showEvent (QShowEvent *) override
void hideEvent (QHideEvent *) override
void updateFrame (int frame)
Detailed Description
The FrameNavigator is a simple toolbar widget showing a numerical representation of an integer timeline.
A FrameNavigator is a TFrameHandle viewer composed of a line edit widget showing the current frame number, and a pair of directional arrow buttons that move to adjacent frames.
Remarks
The text field actually visualizes the internal integer m_frame +1 (e.g. when m_frame is 0 then 1 is visualized).
Constructor & Destructor Documentation
FrameNavigator()
FrameNavigator::FrameNavigator (QWidget * parent = 0)
    : QToolBar(parent), m_frame(0), m_lineEdit(0), m_frameHandle(0) {
  setMaximumWidth(130);
  setIconSize(QSize(20, 20));
  setObjectName("WidePaddingToolBar");
  QAction *prevButton =
      new QAction(createQIcon("frameprev"), tr("Previous Frame"), this);
  connect(prevButton, SIGNAL(triggered()), this, SLOT(prevFrame()));
  addAction(prevButton);
  m_lineEdit = new DVGui::IntLineEdit(this);
  m_lineEdit->setFixedHeight(19);
  bool ret = connect(m_lineEdit, SIGNAL(editingFinished()), this,
                     SLOT(onEditingFinished()));
  addWidget(m_lineEdit);
  QAction *nextButton =
      new QAction(createQIcon("framenext"), tr("Next Frame"), this);
  ret =
      ret && connect(nextButton, SIGNAL(triggered()), this, SLOT(nextFrame()));
  addAction(nextButton);
  assert(ret);
}
~FrameNavigator()
FrameNavigator::~FrameNavigator () inline
{}
Member Function Documentation
anyWidgetHasFocus()
bool FrameNavigator::anyWidgetHasFocus ()
Remarks
Detaches from any previously attached frame handle.
{
  return hasFocus() || m_lineEdit->hasFocus() || m_lineEdit->hasFocus();
}
getFrame()
int FrameNavigator::getFrame () const inline
{ return m_frame; }
hideEvent()
void FrameNavigator::hideEvent (QHideEvent *) override protected
{
  if (m_frameHandle)
    disconnect(m_frameHandle, SIGNAL(frameSwitched()), this,
               SLOT(onFrameSwitched()));
}
nextFrame
void FrameNavigator::nextFrame () inline slot
Move to next frame.
onEditingFinished
void FrameNavigator::onEditingFinished () protected slot
Copies the value in the frame's line edit widget to the internal current frame value. Slot invoked whenever current frame's text editing is finished.
{
  setFrame(m_lineEdit->getValue() - 1, true);
}
References DVGui::IntLineEdit::getValue(), and setFrame().
onFrameSwitched
void FrameNavigator::onFrameSwitched () protected slot
{
  if (m_frameHandle) updateFrame(m_frameHandle->getFrame());
}
prevFrame
void FrameNavigator::prevFrame () inline slot
Move to previous frame.
setFrame
void FrameNavigator::setFrame (int frame, bool notifyFrameHandler) slot
Sets the navigator's current frame.
Deprecated:
Remove the bool.
{
  if (m_frame == frame) return;
  updateFrame(frame);
  if (m_frameHandle && notifyFrameHandler) m_frameHandle->setFrame(frame);
  if (notifyFrameHandler) emit frameSwitched();
}
References updateFrame().
Referenced by onEditingFinished().
setFrameHandle()
void FrameNavigator::setFrameHandle (TFrameHandle * fh)
Attaches the navigator to the specified frameHandle.
{
  if (fh == m_frameHandle) return;
  if (isVisible() && m_frameHandle)
    disconnect(m_frameHandle, SIGNAL(frameSwitched()), this,
               SLOT(onFrameSwitched()));
  m_frameHandle = fh;
  if (m_frameHandle) {
    if (isVisible())
      connect(m_frameHandle, SIGNAL(frameSwitched()), this,
              SLOT(onFrameSwitched()));
    updateFrame(m_frameHandle->getFrame());
  }
}
References updateFrame().
showEvent()
void FrameNavigator::showEvent (QShowEvent *) override protected
{
  onFrameSwitched();
  if (m_frameHandle)
    connect(m_frameHandle, SIGNAL(frameSwitched()), this,
            SLOT(onFrameSwitched()));
}
updateFrame()
void FrameNavigator::updateFrame (int frame) protected
Changes frame without emitting any signal and notifying the frameHandle.
{
  m_frame = frame;
  m_lineEdit->setValue(m_frame + 1);
}
References DVGui::IntLineEdit::setValue().
Referenced by setFrame(), and setFrameHandle().
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/toonzqt/framenavigator.h
E:/opentoonz/toonz/sources/toonzqt/framenavigator.cpp