opentoonz: StageSchematicNodePort Class Reference
StageSchematicNodePort Class Reference final
Public Member Functions
StageSchematicNodePort (StageSchematicNodeDock *parent, int type)
QRectF boundingRect () const override
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=0) override
void setHandle (const QString &value)
QString getHandle ()
bool linkTo (SchematicPort *port, bool checkOnly=false) override
Public Member Functions inherited from SchematicPort
SchematicPort (QGraphicsItem *parent, SchematicNode *node, int type)
SchematicNode * getNode () const
QRectF boundingRect () const override
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=0) override
void addLink (SchematicLink *link)
Add the link to the links container.
int getLinkCount () const
void removeLink (SchematicLink *link)
void eraseLink (SchematicLink *link)
Removes link from the scene and the m_links list; delete it .
void eraseAllLinks ()
Removes all links from the scene and the m_links list; delete them .
SchematicLink * getLink (int index) const
SchematicNode * getLinkedNode (int index) const
Returns the node linked with the link index.
virtual SchematicLink * makeLink (SchematicPort *port)
Make a link from this port to the given port.
virtual bool linkTo (SchematicPort *port, bool checkOnly=false)=0
QPointF getHook () const
bool isLinkedTo (SchematicPort *port) const
void highLight (bool value)
bool isHighlighted () const
void updateLinksGeometry ()
Updates all links of the ports.
QPointF getLinkEndPoint () const
Returns the scene position of the link end.
int getType () const
void setType (int type)
Set the type of the port.
Additional Inherited Members
Signals inherited from SchematicPort
void isClicked ()
void isReleased (const QPointF &)
void sceneChanged ()
void xsheetChanged ()
Protected Member Functions inherited from SchematicPort
void mouseMoveEvent (QGraphicsSceneMouseEvent *me) override
void mousePressEvent (QGraphicsSceneMouseEvent *me) override
void mouseReleaseEvent (QGraphicsSceneMouseEvent *me) override
Protected Attributes inherited from SchematicPort
Qt::MouseButton m_buttonState
SchematicNode * m_node
QPointF m_hook
bool m_highlighted
QList< SchematicLink * > m_ghostLinks
SchematicPort * m_linkingTo
QList< SchematicLink * > m_links
int m_type
Detailed Description
Constructor & Destructor Documentation
StageSchematicNodePort()
StageSchematicNodePort::StageSchematicNodePort (StageSchematicNodeDock * parent, int type)
    : SchematicPort(parent, parent->getNode(), type), m_handle("") {
  QRectF rect = boundingRect();
  if (parent->isParentPort())
    m_hook = QPointF(rect.left(), (rect.top() + rect.bottom()) * 0.5);
  else
    m_hook = QPointF(rect.right(), (rect.top() + rect.bottom()) * 0.5);
}
~StageSchematicNodePort()
StageSchematicNodePort::~StageSchematicNodePort ()
{}
Member Function Documentation
boundingRect()
QRectF StageSchematicNodePort::boundingRect () const override
{
  return QRectF(0, 0, 18, 18);
}
getHandle()
QString StageSchematicNodePort::getHandle () inline
{ return m_handle; }
linkTo()
bool StageSchematicNodePort::linkTo (SchematicPort * port, bool checkOnly = false) override virtual
Check and make a connection between the data Objects. Returns true if it is possible to have a connection between the data Object represented by this SchematicPort and that represented by port. If check only is false no connections is created!
See also
TFxPort, TStageObject.
Implements SchematicPort.
{
  StageSchematicScene *stageScene =
      dynamic_cast<StageSchematicScene *>(scene());
  if (!port) return false;
  StageSchematicNode *srcNode = dynamic_cast<StageSchematicNode *>(getNode());
  if (this == port && !srcNode->getStageObject()->isGrouped()) {
    if (!checkOnly)
      TStageObjectCmd::setParent(srcNode->getStageObject()->getId(),
                                 TStageObjectId::NoneId, "",
                                 stageScene->getXsheetHandle());
    return true;
  }
  StageSchematicNode *dstNode =
      dynamic_cast<StageSchematicNode *>(port->getNode());
  if (!dstNode) return false;
  if (srcNode == dstNode) return false;
  TStageObject *pegbar = 0, *parentPegbar = 0;
  SchematicPort *childPort, *parentPort;
  if (getType() == eStageParentPort && port->getType() == eStageChildPort) {
    pegbar       = srcNode->getStageObject();
    parentPegbar = dstNode->getStageObject();
    childPort    = this;
    parentPort   = port;
  } else if (getType() == eStageChildPort &&
             port->getType() == eStageParentPort) {
    pegbar       = dstNode->getStageObject();
    parentPegbar = srcNode->getStageObject();
    childPort    = port;
    parentPort   = this;
  } else
    return false;
  if (pegbar->getId().isTable()) return false;
  if (pegbar->getId().isPegbar() && !parentPegbar->getId().isTable() &&
      !parentPegbar->getId().isPegbar() && !parentPegbar->getId().isCamera())
    return false;
  if (parentPegbar == pegbar || parentPegbar->isAncestor(pegbar)) return false;
  if (parentPegbar->isGrouped() || pegbar->isGrouped()) return false;
  if (checkOnly) return true;
  StageSchematicNodePort *dstPort =
      dynamic_cast<StageSchematicNodePort *>(parentPort);
  if (!dstPort) return false;
  TStageObjectCmd::setParent(pegbar->getId(), parentPegbar->getId(),
                             dstPort->getHandle().toStdString(),
                             stageScene->getXsheetHandle());
  return true;
}
References TStageObject::getId(), SchematicPort::getType(), TStageObject::isAncestor(), TStageObjectId::isPegbar(), and TStageObjectId::isTable().
paint()
void StageSchematicNodePort::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget = 0) override
{
  // StageSchematicNode *node = dynamic_cast<StageSchematicNode *>(getNode());
  StageSchematicScene *scene =
      dynamic_cast<StageSchematicScene *>(this->scene());
  if (scene && scene->isShowLetterOnPortFlagEnabled()) {
    painter->setBrush(QColor(255, 255, 255, 255));
    painter->setPen(QColor(180, 180, 180, 255));
    painter->drawRect(boundingRect());
    if (m_type == 103 || m_type == 104 || m_type == 105) return;
    painter->setPen(QColor(0, 0, 0, 255));
    QFont font("Verdana", 8);
    painter->setFont(font);
    QTextOption textOption(Qt::AlignCenter);
    QString text = m_handle;
    if (text.size() > 1 && text.at(0) == 'H') text.remove("H");
    painter->drawText(boundingRect(), text, textOption);
  } else {
    QRect imgRect(2, 2, 14, 14);
    QRect sourceRect = scene->views()[0]->matrix().mapRect(imgRect);
    QPixmap pixmap;
    if (getType() == eStageParentPort || getType() == eStageParentGroupPort) {
      if (isHighlighted())
        pixmap = QIcon(":Resources/port_blue_highlight.svg")
                     .pixmap(sourceRect.size());
      else
        pixmap = QIcon(":Resources/port_blue.svg").pixmap(sourceRect.size());
    } else {
      if (isHighlighted())
        pixmap = QIcon(":Resources/port_red_highlight.svg")
                     .pixmap(sourceRect.size());
      else
        pixmap = QIcon(":Resources/port_red.svg").pixmap(sourceRect.size());
    }
    sourceRect = QRect(0, 0, sourceRect.width() * getDevPixRatio(),
                       sourceRect.height() * getDevPixRatio());
    painter->drawPixmap(imgRect, pixmap, sourceRect);
  }
}
setHandle()
void StageSchematicNodePort::setHandle (const QString & value) inline
{ m_handle = value; }
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/toonzqt/stageschematicnode.h
E:/opentoonz/toonz/sources/toonzqt/stageschematicnode.cpp