opentoonz: TXshCell Class Reference
TXshCell Class Reference
#include <txshcell.h>
Public Member Functions
TXshCell ()
TXshCell (const TXshLevelP &level, const TFrameId &frameId)
~TXshCell ()
bool operator== (const TXshCell &c) const
bool operator!= (const TXshCell &c) const
bool isEmpty () const
TImageP getImage (bool toBeModified, int subsampling=0) const
TXshSimpleLevel * getSimpleLevel () const
TXshSoundLevel * getSoundLevel () const
TXshSoundTextLevel * getSoundTextLevel () const
TXshZeraryFxLevel * getZeraryFxLevel () const
TXshPaletteLevel * getPaletteLevel () const
TXshChildLevel * getChildLevel () const
TFrameId getFrameId () const
TPalette * getPalette () const
Public Attributes
TXshLevelP m_level
TFrameId m_frameId
Detailed Description
The TXshCell class provides a cell of xsheet, this structure contains a level frame.
TXshCell is composed by a pointer to level TXshLevelP and a TFrameId that identifies right frame in level.
The class provides functions that return the cell element. The getImage() function return image associated to cell. The getSimpleLevel() function return simple level TXshSimpleLevel to which cell belongs. The getFrameId() function return TFrameId frame identification of cell. It's possible to know if cell is empty through isEmpty().
Constructor & Destructor Documentation
TXshCell() [1/2]
TXshCell::TXshCell () inline
Constructs TXshCell with default value.
: m_level(), m_frameId() {}
TXshCell() [2/2]
TXshCell::TXshCell (const TXshLevelP & level, const TFrameId & frameId) inline
Constructs a TXshCell with simple level level, and a frame identification frameId
      : m_level(level), m_frameId(frameId) {}
~TXshCell()
TXshCell::~TXshCell () inline
Destroys the TLevelSet object.
{}
Member Function Documentation
getChildLevel()
TXshChildLevel * TXshCell::getChildLevel () const
Return the TXshChildLevel to which cell belongs.
{
  return m_level ? m_level->getChildLevel() : 0;
}
References TXshLevel::getChildLevel().
Referenced by TXshLevelColumn::canSetCell(), TXsheet::getBBox(), and Stage::Player::texture().
getFrameId()
TFrameId TXshCell::getFrameId () const inline
Returns the TFrameId correspondent to cell.
{ return m_frameId; }
Referenced by VectorizerPopup::apply(), TXshSoundColumn::assignLevels(), PlasticDeformerFx::doDryCompute(), HookTool::draw(), TXsheet::getBBox(), TTool::getCurrentFid(), TXsheet::incrementCells(), RasterSelection::pasteFloatingSelection(), TXshZeraryFxColumn::setCell(), Stage::Player::texture(), and TTool::touchImage().
getImage()
TImageP TXshCell::getImage (bool toBeModified, int subsampling = 0) const
Returns the TImageP in the current cell.
If bool toBeModified is true the image can be modified.
{
  if (TXshSimpleLevel *sl = getSimpleLevel())
    return sl->getFrame(m_frameId, toBeModified ? ImageManager::toBeModified
                                                : ImageManager::none,
                        subsampling);
  return TImageP();
}
References getSimpleLevel().
Referenced by TTool::getImage(), and TTool::touchImage().
getPalette()
TPalette * TXshCell::getPalette () const
Returns the TPalette associated with current cell, if any.
{
  TXshSimpleLevel *sl = getSimpleLevel();
  if (sl)
    return sl->getPalette();
  else
    return 0;
}
References TXshSimpleLevel::getPalette(), and getSimpleLevel().
getPaletteLevel()
TXshPaletteLevel * TXshCell::getPaletteLevel () const
Return the TXshPaletteLevel to which cell belongs.
{
  return m_level ? m_level->getPaletteLevel() : 0;
}
References TXshLevel::getPaletteLevel().
getSimpleLevel()
TXshSimpleLevel * TXshCell::getSimpleLevel () const
Returns the TXshSimpleLevel to which cell belongs.
{
  return m_level ? m_level->getSimpleLevel() : 0;
}
References TXshLevel::getSimpleLevel().
Referenced by StageBuilder::addCellWithOnionSkin(), VectorizerPopup::apply(), TXshLevelColumn::canSetCell(), PlasticDeformerFx::doDryCompute(), ExportLevelPopup::execute(), TXsheet::getBBox(), TApp::getCurrentImageType(), getImage(), getPalette(), TXsheet::incrementCells(), TTool::notifyImageChanged(), RasterSelection::pasteFloatingSelection(), and TTool::touchImage().
getSoundLevel()
TXshSoundLevel * TXshCell::getSoundLevel () const
Return the TXshSoundLevel to which cell belongs.
{
  return m_level ? m_level->getSoundLevel() : 0;
}
References TXshLevel::getSoundLevel().
Referenced by XsheetViewer::areSoundCellsSelected().
getSoundTextLevel()
TXshSoundTextLevel * TXshCell::getSoundTextLevel () const
Return the TXshSoundTextLevel to which cell belongs.
{
  return m_level ? m_level->getSoundTextLevel() : 0;
}
References TXshLevel::getSoundTextLevel().
getZeraryFxLevel()
TXshZeraryFxLevel * TXshCell::getZeraryFxLevel () const
Return the TXshZeraryFxLevel to which cell belongs.
{
  return m_level ? m_level->getZeraryFxLevel() : 0;
}
References TXshLevel::getZeraryFxLevel().
isEmpty()
bool TXshCell::isEmpty () const inline
Returns true if level is equal to zero.
{ return !m_level; }
Referenced by StageBuilder::addCellWithOnionSkin(), VectorizerPopup::apply(), XsheetViewer::areSoundCellsSelected(), TXshSoundColumn::assignLevels(), TXshLevelColumn::canSetCell(), TXshZeraryFxColumn::canSetCell(), TXsheet::checkCircularReferences(), TXsheet::decreaseStepCells(), TLevelColumnFx::doDryCompute(), SaveLevelAsPopup::execute(), ReplaceParentDirectoryPopup::execute(), TXsheet::getBBox(), TTool::getCurrentFid(), TApp::getCurrentImageType(), TTool::getImage(), TXshCellColumn::getLevelRange(), TXsheet::getUsedLevels(), TXsheet::increaseStepCells(), TXshCellColumn::isCellEmpty(), FxBuilder::makePF(), TXshMeshColumn::saveData(), TXshPaletteColumn::saveData(), TXshLevelColumn::saveData(), TXshSoundTextColumn::saveData(), TXshZeraryFxColumn::saveData(), TXshCellColumn::setCell(), TXshZeraryFxColumn::setCell(), TTool::touchImage(), and Toolbar::updateToolbar().
operator!=()
bool TXshCell::operator!= (const TXshCell & c) const inline
Returns true if cell c and this cell have different simple level or different frameId; otherwise returns false.
{
    return (m_level.getPointer() != c.m_level.getPointer() ||
            m_frameId != c.m_frameId);
  }
operator==()
bool TXshCell::operator== (const TXshCell & c) const inline
Returns true if cell c and this cell have the same simple level and the same frameId; otherwise returns false.
{
    return (m_level.getPointer() == c.m_level.getPointer() &&
            m_frameId == c.m_frameId);
  }
Member Data Documentation
m_frameId
TFrameId TXshCell::m_frameId
m_level
TXshLevelP TXshCell::m_level
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/toonz/txshcell.h
E:/opentoonz/toonz/sources/toonzlib/txshcell.cpp