opentoonz: TParam Class Reference
TParam Class Reference abstract
#include <tparam.h>
Public Member Functions
TParam (std::string name="", std::string description="", std::string label="")
std::string getName () const
void setName (const std::string &name)
std::string getDescription () const
void setDescription (const std::string &description)
bool hasUILabel () const
void setUILabel (const std::string &l)
std::string getUILabel () const
virtual TParam * clone () const =0
virtual void copy (TParam *src)=0
virtual void addObserver (TParamObserver *)=0
virtual void removeObserver (TParamObserver *)=0
virtual void enableNotification (bool on)
virtual bool isNotificationEnabled () const
virtual std::string getValueAlias (double frame, int precision)=0
virtual bool isAnimatable () const =0
virtual bool isKeyframe (double frame) const =0
virtual void deleteKeyframe (double frame)=0
virtual void clearKeyframes ()=0
virtual void assignKeyframe (double frame, const TSmartPointerT< TParam > &src, double srcFrame, bool changedOnly=false)=0
virtual void getKeyframes (std::set< double > &frames) const
virtual bool hasKeyframes () const
virtual int getNextKeyframe (double frame) const
virtual int getPrevKeyframe (double frame) const
virtual double keyframeIndexToFrame (int index) const
Public Member Functions inherited from TSmartObject
TSmartObject (ClassCode classCode)
void addRef ()
void release ()
TINT32 getRefCount () const
Public Member Functions inherited from TPersist
virtual void loadData (TIStream &is)=0
virtual void saveData (TOStream &os)=0
std::string getStreamTag () const
virtual const TPersistDeclaration * getDeclaration () const =0
Additional Inherited Members
Public Types inherited from TSmartObject
typedef short ClassCode
Public Types inherited from TPersist
typedef TPersist * CreateProc()
Static Public Member Functions inherited from TSmartObject
static TINT32 getInstanceCount (ClassCode code)
Static Public Member Functions inherited from TPersist
static void declare (CreateProc *)
static TPersist * create (const std::string &name)
Detailed Description
This class is an abstract class and is a generic interface to the features of an object.
It is used to access to the parameters of an object, with the purpose to store and retrieve the key features.
Constructor & Destructor Documentation
TParam()
TParam::TParam (std::string name = "", std::string description = "", std::string label = "") inline
The constructor store the name of the parameter and initialize his interface with I/O through the class TPersist.
      : TSmartObject(m_classCode)
      , TPersist()
      , m_name(name)
      , m_description(description)
      , m_label(label) {}
~TParam()
virtual TParam::~TParam () inline virtual
{}
Member Function Documentation
addObserver()
virtual void TParam::addObserver (TParamObserver *) pure virtual
 An observer is a generic class that takes care and manages of canghes
in the parameters. This method must be implemented with a function that add objects to an observer internal list.
Implemented in TSpectrumParam, TToneCurveParam, TDoubleParam, TNotAnimatableParam< T >, TNotAnimatableParam< bool >, TNotAnimatableParam< int >, TNotAnimatableParam< TFilePath >, TNotAnimatableParam< std::wstring >, TNotAnimatableParam< double >, and TParamSet.
assignKeyframe()
virtual void TParam::assignKeyframe (double frame, const TSmartPointerT< TParam > & src, double srcFrame, bool changedOnly = false) pure virtual
Makes the frame associated to this parameter a keyframe
Implemented in TDoubleParam, TParamSet, TSpectrumParam, TToneCurveParam, TNotAnimatableParam< T >, TNotAnimatableParam< bool >, TNotAnimatableParam< int >, TNotAnimatableParam< TFilePath >, TNotAnimatableParam< std::wstring >, and TNotAnimatableParam< double >.
Referenced by TParamSet::assignKeyframe().
clearKeyframes()
virtual void TParam::clearKeyframes () pure virtual
Removes all keyframes from this parameter.
Implemented in TDoubleParam, TNotAnimatableParam< T >, TNotAnimatableParam< bool >, TNotAnimatableParam< int >, TNotAnimatableParam< TFilePath >, TNotAnimatableParam< std::wstring >, TNotAnimatableParam< double >, TParamSet, TSpectrumParam, and TToneCurveParam.
Referenced by TParamSet::clearKeyframes().
clone()
virtual TParam * TParam::clone () const pure virtual
 This method must be implemented with a clone function, i.e a function
that make a new copy of the parameter.
Implemented in TDoubleStepParam, TDoubleParam, TIntParam, TBoolParam, TFilePathParam, TStringParam, TEnumParam, TNADoubleParam, TFontParam, TParamSet, TPointParam, TPixelParam, TRangeParam, TSpectrumParam, and TToneCurveParam.
Referenced by TParamSet::copy().
copy()
virtual void TParam::copy (TParam * src) pure virtual
Performs a copy function of the parameter in an existing object.
Implemented in TDoubleParam, TNotAnimatableParam< T >, TNotAnimatableParam< bool >, TNotAnimatableParam< int >, TNotAnimatableParam< TFilePath >, TNotAnimatableParam< std::wstring >, TNotAnimatableParam< double >, TEnumParam, TParamSet, TPointParam, TPixelParam, TRangeParam, TSpectrumParam, and TToneCurveParam.
deleteKeyframe()
virtual void TParam::deleteKeyframe (double frame) pure virtual
 Removes \e frame from the list of the keyframes associated to this
parameter.
Implemented in TDoubleParam, TParamSet, TSpectrumParam, TToneCurveParam, TNotAnimatableParam< T >, TNotAnimatableParam< bool >, TNotAnimatableParam< int >, TNotAnimatableParam< TFilePath >, TNotAnimatableParam< std::wstring >, and TNotAnimatableParam< double >.
Referenced by TParamSet::deleteKeyframe().
enableNotification()
virtual void TParam::enableNotification (bool on) inline virtual
 This method is used to sets the status changing notification of the
parameter. i.e the observer must take care of the changes.
Reimplemented in TParamSet, and TSpectrumParam.
{}
getDescription()
std::string TParam::getDescription () const inline
Return the description.
{ return m_description; }
getKeyframes()
virtual void TParam::getKeyframes (std::set< double > & frames) const inline virtual
 This function must be overridden with a method that returns as a
reference a list of keyframes in the form of a standard list.
Reimplemented in TNotAnimatableParam< T >, TNotAnimatableParam< bool >, TNotAnimatableParam< int >, TNotAnimatableParam< TFilePath >, TNotAnimatableParam< std::wstring >, TNotAnimatableParam< double >, TDoubleParam, TParamSet, TSpectrumParam, and TToneCurveParam.
{}
Referenced by TParamSet::getKeyframes().
getName()
std::string TParam::getName () const inline
Returns the name of the parameter.
{ return m_name; };
Referenced by TDoubleParam::copy(), TNotAnimatableParam< T >::copy(), TEnumParam::copy(), TParamSet::copy(), TPointParam::copy(), TPixelParam::copy(), TRangeParam::copy(), TSpectrumParam::copy(), TToneCurveParam::copy(), TFx::loadData(), and TParamSet::saveData().
getNextKeyframe()
virtual int TParam::getNextKeyframe (double frame) const inline virtual
 This method must return the index of the keyframe (if any) after the
frame, otherwiswe returns -1.
Reimplemented in TDoubleParam, TParamSet, TSpectrumParam, TToneCurveParam, TNotAnimatableParam< T >, TNotAnimatableParam< bool >, TNotAnimatableParam< int >, TNotAnimatableParam< TFilePath >, TNotAnimatableParam< std::wstring >, and TNotAnimatableParam< double >.
{ return -1; }
getPrevKeyframe()
virtual int TParam::getPrevKeyframe (double frame) const inline virtual
 This method must return the index of the keyframe (if any) before the
frame, otherwiswe returns -1.
Reimplemented in TDoubleParam, TParamSet, TSpectrumParam, TToneCurveParam, TNotAnimatableParam< T >, TNotAnimatableParam< bool >, TNotAnimatableParam< int >, TNotAnimatableParam< TFilePath >, TNotAnimatableParam< std::wstring >, and TNotAnimatableParam< double >.
{ return -1; }
getUILabel()
std::string TParam::getUILabel () const inline
{ return m_label; };
getValueAlias()
virtual std::string TParam::getValueAlias (double frame, int precision) pure virtual
 This pure virtual method must return a string with the value of the
parameter and the precision needed.
Implemented in TDoubleParam, TParamSet, TSpectrumParam, TToneCurveParam, TNotAnimatableParam< T >, TNotAnimatableParam< bool >, TNotAnimatableParam< int >, TNotAnimatableParam< TFilePath >, TNotAnimatableParam< std::wstring >, and TNotAnimatableParam< double >.
hasKeyframes()
virtual bool TParam::hasKeyframes () const inline virtual
 This method must return true if there are keyframes associated to this
parameter.
Reimplemented in TDoubleParam, TNotAnimatableParam< T >, TNotAnimatableParam< bool >, TNotAnimatableParam< int >, TNotAnimatableParam< TFilePath >, TNotAnimatableParam< std::wstring >, TNotAnimatableParam< double >, TParamSet, TSpectrumParam, and TToneCurveParam.
{ return false; }
Referenced by FxChannelGroup::data(), and TParamSet::hasKeyframes().
hasUILabel()
bool TParam::hasUILabel () const inline
{ return m_label != "" ? true : false; }
isKeyframe()
virtual bool TParam::isKeyframe (double frame) const pure virtual
It must returns true if the frame is a keyframe.
Implemented in TDoubleParam, TParamSet, TSpectrumParam, TToneCurveParam, TNotAnimatableParam< T >, TNotAnimatableParam< bool >, TNotAnimatableParam< int >, TNotAnimatableParam< TFilePath >, TNotAnimatableParam< std::wstring >, and TNotAnimatableParam< double >.
Referenced by TParamSet::isKeyframe().
isNotificationEnabled()
virtual bool TParam::isNotificationEnabled () const inline virtual
 This method must return \e true if the  notification status is
enabled.
Reimplemented in TParamSet, and TSpectrumParam.
{ return true; }
keyframeIndexToFrame()
virtual double TParam::keyframeIndexToFrame (int index) const inline virtual
 This method must returns a frame given the index \e index. A frame is
a double value representing a frame.
Reimplemented in TDoubleParam, TParamSet, TSpectrumParam, and TToneCurveParam.
{ return 0.0; }
removeObserver()
virtual void TParam::removeObserver (TParamObserver *) pure virtual
Removes this from the observer.
See also
addObserver()
Implemented in TSpectrumParam, TToneCurveParam, TDoubleParam, TNotAnimatableParam< T >, TNotAnimatableParam< bool >, TNotAnimatableParam< int >, TNotAnimatableParam< TFilePath >, TNotAnimatableParam< std::wstring >, TNotAnimatableParam< double >, and TParamSet.
setDescription()
void TParam::setDescription (const std::string & description) inline
Set the description.
{
    m_description = description;
  }
setName()
void TParam::setName (const std::string & name) inline
This method sets the name of the parameter to name.
{ m_name = name; };
Referenced by TDoubleParam::copy(), TNotAnimatableParam< T >::copy(), TEnumParam::copy(), TPointParam::copy(), TPixelParam::copy(), TRangeParam::copy(), TSpectrumParam::copy(), and TToneCurveParam::copy().
setUILabel()
void TParam::setUILabel (const std::string & l) inline
{ m_label = l; };
The documentation for this class was generated from the following file:
E:/opentoonz/toonz/sources/include/tparam.h