opentoonz: TImageCache Class Reference
TImageCache Class Reference
#include <timagecache.h>
Classes
class Imp
Public Member Functions
std::string getUniqueId ()
void setEnabled (bool enable)
bool isEnabled ()
Returns true or false whether the cache is active or not.
void setRootDir (const TFilePath &fp)
void add (const std::string &id, const TImageP &img, bool overwrite=true)
void remove (const std::string &id)
Removes from the image cache the image associated to passed id.
void remap (const std::string &dstId, const std::string &srcId)
Rebinds the association between a previously cached image and its id.
void remapIcons (const std::string &dstId, const std::string &srcId)
void clear (bool deleteFolder=false)
void clearSceneImages ()
bool isCached (const std::string &id) const
bool getSubsampling (const std::string &id, int &subs) const
Returns the subsampling level of the image under the specified id.
TImageP get (const std::string &id, bool toBeModified) const
UINT getMemUsage () const
Returns the RAM memory size (KB) occupied by the image cache.
UINT getDiskUsage () const
UINT getUncompressedMemUsage (const std::string &id) const
UINT getMemUsage (const std::string &id) const
Returns the RAM memory size (KB) of the image associated to passed id.
UINT getDiskUsage (const std::string &id) const
void dump (std::ostream &os) const
UCHAR * compressAndMalloc (TUINT32 requestedSize)
void outputMap (UINT chunkRequested, std::string filename)
bool hasBeenModified (const std::string &id, bool reset) const
void add (const QString &id, const TImageP &img, bool overwrite=true)
void remove (const QString &id)
TImageP get (const QString &id, bool toBeModified) const
void compress (const std::string &id)
Static Public Member Functions
static TImageCache * instance ()
Detailed Description
The Image Cache is the global container used throughout Toonz to store images that need to be retrieved at later times.
TImageCache is Toonz's low-level manager singleton that deals with image storage.
The main task of TImageCache is that of acting as an associative container that maps a name (of std::string type) into an image smart pointer. Many-to-one relationships where multiple names map to the same image are supported. Thus, users can add() an image and get() it later, until comes the time to remove() it.
An important reason to use TImageCache instead of direct storage of TImageP or TRasterP instances is that it takes care of verifying memory shortages in the process' virtual address space, and in case either compresses or ships to disk unreferenced images with last-access precedence.
Warning
Memory-hungry tasks should always use TImageCache to store images, since it prevents abuses of system memory. This is especially true on 32-bit OSes.
Member Function Documentation
add() [1/2]
void TImageCache::add (const QString & id, const TImageP & img, bool overwrite = true)
{
  if (!isEnabled()) return;
  m_imp->add(id.toStdString(), img, overwrite);
}
add() [2/2]
void TImageCache::add (const std::string & id, const TImageP & img, bool overwrite = true)
Adds the passed image to the cache, under the specified id. The optional overwrite parameter may be specified in case an image with the same id has already been cached.
{
  if (!isEnabled()) return;
  m_imp->add(id, img, overwrite);
}
References isEnabled().
Referenced by TRop::convertRaster50to46(), PreviewFxManager::freeze(), ImageManager::getImage(), CSTPic< P >::initPic(), TXshSimpleLevel::renumber(), MovieRenderer::Imp::saveFrame(), ImageManager::setImage(), and TCachedImage::setImage().
clear()
void TImageCache::clear (bool deleteFolder = false)
Clears the image cache. After calling this method, every image in the cache is released - and optionally the cache swap folder is deleted.
{
  TThread::MutexLocker sl(&m_imp->m_mutex);
  m_imp->m_uncompressedItems.clear();
  m_imp->m_itemHistory.clear();
  m_imp->m_compressedItems.clear();
  m_imp->m_duplicatedItems.clear();
  m_imp->m_itemsByImagePointer.clear();
  if (deleteFolder && m_imp->m_rootDir != TFilePath())
    TSystem::rmDirTree(m_imp->m_rootDir);
}
clearSceneImages()
void TImageCache::clearSceneImages ()
Clears the image cache of all images which belong to current scene. This spares images (typically file browser icons) which are scene-independent.
{NOTE:} Scene-independent images are simply assumed to have the "$:" id prefix.
{
  TThread::MutexLocker sl(&m_imp->m_mutex);
  // note the ';' - which follows ':' in the ascii table
  m_imp->m_uncompressedItems.erase(
      m_imp->m_uncompressedItems.begin(),
      m_imp->m_uncompressedItems.lower_bound("$:"));
  m_imp->m_uncompressedItems.erase(m_imp->m_uncompressedItems.lower_bound("$;"),
                                   m_imp->m_uncompressedItems.end());
  m_imp->m_compressedItems.erase(m_imp->m_compressedItems.begin(),
                                 m_imp->m_compressedItems.lower_bound("$:"));
  m_imp->m_compressedItems.erase(m_imp->m_compressedItems.lower_bound("$;"),
                                 m_imp->m_compressedItems.end());
  m_imp->m_duplicatedItems.erase(m_imp->m_duplicatedItems.begin(),
                                 m_imp->m_duplicatedItems.lower_bound("$:"));
  m_imp->m_duplicatedItems.erase(m_imp->m_duplicatedItems.lower_bound("$;"),
                                 m_imp->m_duplicatedItems.end());
  // Clear maps whose id is on the second of map pairs.
  std::map<TUINT32, std::string>::iterator it;
  for (it = m_imp->m_itemHistory.begin(); it != m_imp->m_itemHistory.end();) {
    if (it->second.size() >= 2 && it->second[0] == '$' && it->second[1] == ':')
      ++it;
    else {
      std::map<TUINT32, std::string>::iterator app = it;
      app++;
      m_imp->m_itemHistory.erase(it);
      it = app;
    }
  }
  std::map<void *, std::string>::iterator jt;
  for (jt = m_imp->m_itemsByImagePointer.begin();
       jt != m_imp->m_itemsByImagePointer.end();) {
    if (jt->second.size() >= 2 && jt->second[0] == '$' && jt->second[1] == ':')
      ++jt;
    else {
      std::map<void *, std::string>::iterator app = jt;
      app++;
      m_imp->m_itemsByImagePointer.erase(jt);
      jt = app;
    }
  }
}
Referenced by ImageManager::clear().
compress()
void TImageCache::compress (const std::string & id)
{ m_imp->doCompress(id); }
compressAndMalloc()
UCHAR * TImageCache::compressAndMalloc (TUINT32 requestedSize)
{
  return m_imp->compressAndMalloc(requestedSize);
}
dump()
void TImageCache::dump (std::ostream & os) const
{
  os << "mem: " << getMemUsage() << std::endl;
  std::map<std::string, CacheItemP>::iterator it =
      m_imp->m_uncompressedItems.begin();
  for (; it != m_imp->m_uncompressedItems.end(); ++it) {
    os << it->first << std::endl;
  }
}
get() [1/2]
TImageP TImageCache::get (const QString & id, bool toBeModified) const
{
  return get(id.toStdString(), toBeModified);
}
get() [2/2]
TImageP TImageCache::get (const std::string & id, bool toBeModified) const
Retrieves the image associated to input id. Returns an empty pointer if no image was found.
{
  return m_imp->get(id, toBeModified);
}
Referenced by SetScanCropboxTool::draw(), PreviewFxManager::freeze(), ImageManager::getImage(), Previewer::getRaster(), TCachedImage::image(), and CSTPic< P >::lock().
getDiskUsage() [1/2]
UINT TImageCache::getDiskUsage () const
Returns the swap files size (KB) currently allocated by the image cache.
{NOTE:} This function is not implemented yet!
{ return 0; }
getDiskUsage() [2/2]
UINT TImageCache::getDiskUsage (const std::string & id) const
{ return 0; }
getMemUsage() [1/2]
UINT TImageCache::getMemUsage () const
Returns the RAM memory size (KB) occupied by the image cache.
{
  TThread::MutexLocker sl(&m_imp->m_mutex);
  int ret = std::accumulate(m_imp->m_uncompressedItems.begin(),
                            m_imp->m_uncompressedItems.end(), 0,
                            AccumulateMemUsage());
  return ret + std::accumulate(m_imp->m_compressedItems.begin(),
                               m_imp->m_compressedItems.end(), 0,
                               AccumulateMemUsage());
}
getMemUsage() [2/2]
UINT TImageCache::getMemUsage (const std::string & id) const
Returns the RAM memory size (KB) of the image associated to passed id.
{
  std::map<std::string, CacheItemP>::iterator it =
      m_imp->m_uncompressedItems.find(id);
  if (it != m_imp->m_uncompressedItems.end()) return it->second->getSize();
  it = m_imp->m_compressedItems.find(id);
  if (it != m_imp->m_compressedItems.end()) return it->second->getSize();
  return 0;
}
getSubsampling()
bool TImageCache::getSubsampling (const std::string & id, int & subs) const
Returns the subsampling level of the image under the specified id.
{
  TThread::MutexLocker sl(&m_imp->m_mutex);
  std::map<std::string, std::string>::iterator it1;
  if ((it1 = m_imp->m_duplicatedItems.find(id)) !=
      m_imp->m_duplicatedItems.end()) {
    assert(m_imp->m_duplicatedItems.find(it1->second) ==
           m_imp->m_duplicatedItems.end());
    return getSubsampling(it1->second, subs);
  }
  std::map<std::string, CacheItemP>::iterator it =
      m_imp->m_uncompressedItems.find(id);
  if (it != m_imp->m_uncompressedItems.end()) {
    UncompressedOnMemoryCacheItemP uncompressed = it->second;
    assert(uncompressed);
#ifndef TNZCORE_LIGHT
    if (TToonzImageP ti = uncompressed->getImage()) {
      subs = ti->getSubsampling();
      return true;
    }
    else
#endif
        if (TRasterImageP ri = uncompressed->getImage()) {
      subs = ri->getSubsampling();
      return true;
    } else
      return false;
  }
  std::map<std::string, CacheItemP>::iterator itc =
      m_imp->m_compressedItems.find(id);
  if (itc == m_imp->m_compressedItems.end()) return false;
  CacheItemP cacheItem = itc->second;
  assert(cacheItem->m_imageInfo);
  if (RasterImageInfo *rimageInfo =
          dynamic_cast<RasterImageInfo *>(cacheItem->m_imageInfo)) {
    subs = rimageInfo->m_subs;
    return true;
  }
#ifndef TNZCORE_LIGHT
  else if (ToonzImageInfo *timageInfo =
               dynamic_cast<ToonzImageInfo *>(cacheItem->m_imageInfo)) {
    subs = timageInfo->m_subs;
    return true;
  }
#endif
  else
    return false;
}
References getSubsampling().
Referenced by getSubsampling().
getUncompressedMemUsage()
UINT TImageCache::getUncompressedMemUsage (const std::string & id) const
Returns the uncompressed image size (in KB) of the image associated with passd id, or 0 if none was found.
{
  std::map<std::string, CacheItemP>::iterator it =
      m_imp->m_uncompressedItems.find(id);
  if (it != m_imp->m_uncompressedItems.end()) return it->second->getSize();
  it = m_imp->m_compressedItems.find(id);
  if (it != m_imp->m_compressedItems.end()) return it->second->getSize();
  return 0;
}
getUniqueId()
std::string TImageCache::getUniqueId (void)
{
  static TAtomicVar count;
  std::stringstream ss;
  ss << ++count;
  return "IMAGECACHEUNIQUEID" + ss.str();
}
hasBeenModified()
bool TImageCache::hasBeenModified (const std::string & id, bool reset) const
{
  TThread::MutexLocker sl(&m_imp->m_mutex);
  std::map<std::string, std::string>::iterator it;
  if ((it = m_imp->m_duplicatedItems.find(id)) !=
      m_imp->m_duplicatedItems.end()) {
    assert(m_imp->m_duplicatedItems.find(it->second) ==
           m_imp->m_duplicatedItems.end());
    return hasBeenModified(it->second, reset);
  }
  TImageP img;
  std::map<std::string, CacheItemP>::iterator itu =
      m_imp->m_uncompressedItems.find(id);
  if (itu != m_imp->m_uncompressedItems.end()) {
    if (reset && itu->second->m_modified) {
      itu->second->m_modified = false;
      return true;
    } else
      return itu->second->m_modified;
  }
  return true;  // not present in cache==modified (for particle purposes...)
}
instance()
TImageCache * TImageCache::instance () static
{
  if (CacheInstance == 0) CacheInstance = new TImageCache();
  return CacheInstance;
  /*
if (!ImageCache::m_instance)
{
ImageCache::m_instance = new ImageCache;
ImageCache::m_destroyer.m_imageCache = ImageCache::m_instance;
}
return ImageCache::m_instance;
  */
}
isCached()
bool TImageCache::isCached (const std::string & id) const
Returns true or false whether an image under the passed id is found in the cache.
{
  TThread::MutexLocker sl(&m_imp->m_mutex);
  return (m_imp->m_uncompressedItems.find(id) !=
              m_imp->m_uncompressedItems.end() ||
          m_imp->m_compressedItems.find(id) != m_imp->m_compressedItems.end() ||
          m_imp->m_duplicatedItems.find(id) != m_imp->m_duplicatedItems.end());
}
isEnabled()
bool TImageCache::isEnabled ()
Returns true or false whether the cache is active or not.
{
#ifndef TNZCORE_LIGHT
  QThreadStorage<bool *> &storage = m_imp->m_isEnabled;
  if (!storage.hasLocalData()) return true;
  return *(storage.localData());
#else
  return m_isEnabled;
#endif
}
Referenced by add(), ImageManager::getImage(), and setEnabled().
outputMap()
void TImageCache::outputMap (UINT chunkRequested, std::string filename)
{
  m_imp->outputMap(chunkRequested, filename);
}
remap()
void TImageCache::remap (const std::string & dstId, const std::string & srcId)
Rebinds the association between a previously cached image and its id.
{
  m_imp->remap(dstId, srcId);
}
Referenced by ImageManager::rebind(), and TXshSimpleLevel::renumber().
remapIcons()
void TImageCache::remapIcons (const std::string & dstId, const std::string & srcId)
{
  std::map<std::string, CacheItemP>::iterator it;
  std::map<std::string, std::string> table;
  std::string prefix = srcId + ":";
  int j              = (int)prefix.length();
  for (it = m_imp->m_uncompressedItems.begin();
       it != m_imp->m_uncompressedItems.end(); ++it) {
    std::string id                      = it->first;
    if (id.find(prefix) == 0) table[id] = dstId + ":" + id.substr(j);
  }
  for (std::map<std::string, std::string>::iterator it2 = table.begin();
       it2 != table.end(); ++it2) {
    remap(it2->second, it2->first);
  }
}
remove() [1/2]
void TImageCache::remove (const QString & id)
{ m_imp->remove(id.toStdString()); }
remove() [2/2]
void TImageCache::remove (const std::string & id)
Removes from the image cache the image associated to passed id.
{ m_imp->remove(id); }
Referenced by ImageManager::bind(), TCacheResource::clear(), ImageManager::invalidate(), OnRenderCompleted::onDeliver(), TRop::releaseRaster46(), PreviewFxInstance::reset(), ImageManager::unbind(), and TXshChildLevel::~TXshChildLevel().
setEnabled()
void TImageCache::setEnabled (bool enable)
Enables or disables the image cache on current thread. When the cache is disabled, images can't be added to the cache.
{
#ifndef TNZCORE_LIGHT
  QThreadStorage<bool *> &storage = m_imp->m_isEnabled;
  if (storage.hasLocalData() && *(storage.localData()) == isEnabled) return;
  if (!storage.hasLocalData())
    storage.setLocalData(new bool(isEnabled));
  else
    *(storage.localData()) = isEnabled;
#else
  m_imp->m_isEnabled = isEnabled;
#endif
}
References isEnabled().
setRootDir()
void TImageCache::setRootDir (const TFilePath & fp)
Sets the hard disk swap directory. It is set by default in the \it{stuff\cache} folder.
{
  if (m_imp->m_rootDir != TFilePath()) return;
  m_imp->m_rootDir =
      cacheDir + TFilePath(std::to_string(TSystem::getProcessId()));
#ifndef TNZCORE_LIGHT
  TFileStatus fs1(m_imp->m_rootDir);
  if (!fs1.doesExist()) TSystem::mkDir(m_imp->m_rootDir);
#endif
}
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/timagecache.h
E:/opentoonz/toonz/sources/common/tcache/timagecache.cpp