opentoonz: DockPlaceholder Class Reference
DockPlaceholder Class Reference
#include <docklayout.h>
Public Types
enum {
left = 0 , right = 1 , top = 2 , bottom = 3 ,
sepHor = 4 , sepVert = 5 , root = 6
}
Public Member Functions
DockPlaceholder (DockWidget *owner, Region *r, int idx, int attributes=0)
DockSeparator * getSeparator () const
Returns DockSeparator on which docking takes place (if any)
DockWidget * getDockWidget () const
Returns dockWidget owner.
Region * getParentRegion () const
Returns Region owner.
int getInsertionIdx () const
Returns insertion index into parent region.
int getAttribute () const
void setAttribute (int attribute)
QRect parentGeometry () const
virtual void buildGeometry ()
Assigns the geometry of this placeholder.
bool isRoot () const
DockPlaceholder * parentPlaceholder ()
NOTE: If no grandParent exists this is the root, which is then returned.
DockPlaceholder * greatestPlaceholder ()
Returns greatest placeholder which contains this one.
DockPlaceholder * childPlaceholder (QPoint p)
DockPlaceholder * smallestPlaceholder (QPoint p)
Friends
class DockLayout
Detailed Description
A dock placeholder contains the necessary information about a possible docking solution.
Dock placeholders are top-level widgets used by a DockLayout to draw docking solutions for a dragged DockWidget. They are actually generated when dragging of a DockWidget begins: if it belongs to a parent DockLayout, docking possibilities are calculated and stored into the layout. Placeholders selection and activation depend on the dragged dock window and therefore are of its own responsibility. You may, however, inherit this class to provide custom placeholders; in this case, a DockDecoAllocator class reimplementing allocation of placeholders must be assigned to the owner dock widget.
See also
DockLayout and DockWidget classes
Member Enumeration Documentation
anonymous enum
anonymous enum
       {
    left    = 0,
    right   = 1,
    top     = 2,
    bottom  = 3,
    sepHor  = 4,
    sepVert = 5,
    root    = 6
  };
Constructor & Destructor Documentation
DockPlaceholder()
DockPlaceholder::DockPlaceholder (DockWidget * owner, Region * r, int idx, int attributes = 0)
    : QWidget(owner)
    , m_owner(owner)
    , m_separator(0)
    , m_region(r)
    , m_idx(idx)
    , m_attributes(attributes) {
  setWindowFlags(Qt::Tool | Qt::WindowStaysOnTopHint | Qt::FramelessWindowHint);
  // Set separators
  if (r && idx && idx < (int)r->getChildList().size()) {
    m_separator = r->separators()[idx - 1];
  }
}
~DockPlaceholder()
virtual DockPlaceholder::~DockPlaceholder () inline virtual
{}
Member Function Documentation
buildGeometry()
void DockPlaceholder::buildGeometry () inline virtual
Assigns the geometry of this placeholder.
Once a placeholder is created, in response to a user window drag, dock placeholders are calculated. After a placeholder is created, its geometry is built according to this function. It is possible to reimplement it in order to build custom placeholder styles.
Reimplemented in TDockPlaceholder.
{
  QRect relativeToMainRect;
  if (m_separator)
    relativeToMainRect = m_separator->geometry();
  else {
    QRect parentRect   = parentGeometry();
    DockLayout *layout = m_owner->parentLayout();
    QRect mainRect     = layout->contentsRect();
    int sepWidth       = layout->spacing();
    int margin = 6;  // layout->margin();   //Purtroppo questa info e' assegnata
                     // prima delle Room...
    if (isRoot()) {
      // Set the whole contents rect
      relativeToMainRect = parentRect;
      // Set a square at middle of parent geometry
      // QPoint center= parentRect.center();
      // relativeToMainRect= QRect(center - QPoint(50,50), center +
      // QPoint(50,50));
    } else if (getParentRegion() == 0 ||
               getParentRegion() == layout->rootRegion()) {
      // Outer insertion case
      switch (getAttribute()) {
        int leftBound, upperBound;
      case left:
        leftBound = parentRect.left() - margin;
        relativeToMainRect =
            QRect(leftBound, parentRect.top(), margin, parentRect.height());
        break;
      case right:
        leftBound = parentRect.right() + 1;
        relativeToMainRect =
            QRect(leftBound, parentRect.top(), margin, parentRect.height());
        break;
      case top:
        upperBound = parentRect.top() - margin;
        relativeToMainRect =
            QRect(parentRect.left(), upperBound, parentRect.width(), margin);
        break;
      default:
        upperBound = parentRect.bottom() + 1;
        relativeToMainRect =
            QRect(parentRect.left(), upperBound, parentRect.width(), margin);
        break;
      }
    } else
      switch (getAttribute()) {
        int leftBound, upperBound;
      case left:
        leftBound = parentRect.left();
        relativeToMainRect =
            QRect(leftBound, parentRect.top(), sepWidth, parentRect.height());
        break;
      case right:
        leftBound = parentRect.right() - sepWidth + 1;
        relativeToMainRect =
            QRect(leftBound, parentRect.top(), sepWidth, parentRect.height());
        break;
      case top:
        upperBound = parentRect.top();
        relativeToMainRect =
            QRect(parentRect.left(), upperBound, parentRect.width(), sepWidth);
        break;
      default:
        upperBound = parentRect.bottom() - sepWidth + 1;
        relativeToMainRect =
            QRect(parentRect.left(), upperBound, parentRect.width(), sepWidth);
        break;
      }
  }
  QPoint topLeft =
      m_owner->parentWidget()->mapToGlobal(relativeToMainRect.topLeft());
  QPoint bottomRight =
      m_owner->parentWidget()->mapToGlobal(relativeToMainRect.bottomRight());
  setGeometry(QRect(topLeft, bottomRight));
}
References getParentRegion(), and isRoot().
Referenced by TDockPlaceholder::buildGeometry().
childPlaceholder()
DockPlaceholder * DockPlaceholder::childPlaceholder (QPoint p)
The opposite of parentPlaceholder() - but a point belonging to the child region to be selected is requested as univoque key among all children.
{
  // Ensure this is not a root placeholder
  if (m_attributes == root) return this;
  // Define children list and ensure it is not void.
  Region *r;
  unsigned int i;
  bool lastExtremity;
  if (m_region) {
    if (!m_region->getChildList().size()) return this;
    // Search the subregion containing p
    for (i = 0; i < m_region->getChildList().size(); ++i)
      if (m_region->childRegion(i)->getGeometry().contains(p)) break;
    if (i == m_region->getChildList().size())
      return this;  // No subregion found...
    lastExtremity = (m_idx > (int)i);
    // Ensure it has subRegions.
    r = m_region->childRegion(i);
    if (!r->getChildList().size()) return this;
  } else {
    r             = m_owner->parentLayout()->rootRegion();
    lastExtremity = m_attributes % 2;
  }
  // Now, take the 'grandson' region as above.
  for (i = 0; i < r->getChildList().size(); ++i)
    if (r->childRegion(i)->getGeometry().contains(p)) break;
  if (i == r->getChildList().size()) return this;  // No subregion found...
  r = r->childRegion(i);
  // Finally, return child placeholder found.
  return r->placeholders().size()
             ? lastExtremity ? r->placeholders().back()
                             : r->placeholders().front()
             : this;
}
Referenced by smallestPlaceholder(), and DockWidget::wheelEvent().
getAttribute()
int DockPlaceholder::getAttribute () const inline
{ return m_attributes; }
getDockWidget()
DockWidget * DockPlaceholder::getDockWidget () const inline
Returns dockWidget owner.
{ return m_owner; }
getInsertionIdx()
int DockPlaceholder::getInsertionIdx () const inline
Returns insertion index into parent region.
{ return m_idx; }
getParentRegion()
Region * DockPlaceholder::getParentRegion () const inline
Returns Region owner.
{ return m_region; }
Referenced by buildGeometry().
getSeparator()
DockSeparator * DockPlaceholder::getSeparator () const inline
Returns DockSeparator on which docking takes place (if any)
{
  return m_separator;
}
greatestPlaceholder()
DockPlaceholder * DockPlaceholder::greatestPlaceholder () inline
Returns greatest placeholder which contains this one.
{
  DockPlaceholder *old = this, *current = parentPlaceholder();
  while (current != old) {
    old     = current;
    current = old->parentPlaceholder();
  }
  return current;
}
References parentPlaceholder().
isRoot()
bool DockPlaceholder::isRoot () const inline
A root placeholder is passed only if no item is currently docked (special case)
{ return m_attributes == root; }
Referenced by buildGeometry(), TDockPlaceholder::buildGeometry(), and parentPlaceholder().
parentGeometry()
QRect DockPlaceholder::parentGeometry () const inline
{
  return m_region ? toRect(m_region->getGeometry())
                  : m_owner->parentLayout()->contentsRect();
}
parentPlaceholder()
DockPlaceholder * DockPlaceholder::parentPlaceholder ()
NOTE: If no grandParent exists this is the root, which is then returned.
Find the 'parent' of this placeholder (same side/orientation, on grandParent region)
{
  // Placeholders covering a whole separator or roots have no parent (return
  // itself)
  if (m_attributes == sepHor || m_attributes == sepVert || isRoot())
    return this;
  // Now, check if owner Region has a parent.
  Region *grandParent;
  if (!m_region || !m_region->getParent()) return this;
  if ((grandParent = m_region->getParent()->getParent())) {
    // Good, we finally have to search in grandParent's region our direct
    // parent.
    unsigned int idx = grandParent->find(m_region->getParent());
    // Since placeholders are built ordered, just use the found idx.
    if (m_attributes == left || m_attributes == top)
      return grandParent->placeholders().size() ? grandParent->placeholder(idx)
                                                : this;
    else
      return grandParent->placeholders().size()
                 ? grandParent->placeholder(idx + 1)
                 : this;
  } else {
    // GrandParent would be a new root. Then, take the first two possible
    // placeholders
    // of the entire dockWidget.
    if (m_owner->m_placeholders.size()) {
      DockPlaceholder *result = m_owner->m_placeholders[m_attributes % 2];
      if (!result->m_region) return result;
    }
    return this;
  }
}
References isRoot().
Referenced by greatestPlaceholder(), and DockWidget::wheelEvent().
setAttribute()
void DockPlaceholder::setAttribute (int attribute) inline
{ m_attributes = attribute; }
smallestPlaceholder()
DockPlaceholder * DockPlaceholder::smallestPlaceholder (QPoint p) inline
Returns smallest placeholder contained by this one - a point belonging to the child region to be selected is requested as univoque key among all children.
{
  DockPlaceholder *old = this, *current = childPlaceholder(p);
  while (current != old) {
    old     = current;
    current = old->childPlaceholder(p);
  }
  return current;
}
References childPlaceholder().
Friends And Related Function Documentation
DockLayout
friend class DockLayout friend
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/toonzqt/docklayout.h
E:/opentoonz/toonz/sources/toonzqt/dockwidget.cpp