opentoonz: DragSelectionTool::Scale Class Reference
DragSelectionTool::Scale Class Reference
Public Member Functions
Scale (DeformTool *deformTool, ScaleType type)
TPointD getIntersectionPoint (const TPointD &point0, const TPointD &point1, const TPointD &point2, const TPointD &point3, const TPointD &p) const
FourPoints bboxScale (int index, const FourPoints &oldBbox, const TPointD &pos)
TPointD computeScaleValue (int movedIndex, const FourPoints newBbox)
TPointD getScaledPoint (int index, const FourPoints &oldBbox, const TPointD scaleValue, const TPointD center)
TPointD getNewCenter (int index, const FourPoints bbox, const TPointD scaleValue)
FourPoints bboxScaleInCenter (int index, const FourPoints &oldBbox, const TPointD newPos, TPointD &scaleValue, const TPointD center, bool recomputeScaleValue)
void leftButtonDown (const TPointD &pos, const TMouseEvent &e)
void leftButtonDrag (const TPointD &pos, const TMouseEvent &e)
void leftButtonUp ()
std::vector< FourPoints > getStartBboxs () const
TPointD getStartCenter () const
bool scaleInCenter () const
Public Attributes
ScaleType m_type
Detailed Description
Constructor & Destructor Documentation
Scale()
DragSelectionTool::Scale::Scale (DeformTool * deformTool, ScaleType type)
    : m_deformTool(deformTool)
    , m_startCenter(deformTool->getTool()->getCenter())
    , m_type(type)
    , m_isShiftPressed(false)
    , m_isAltPressed(false)
    , m_scaleInCenter(true) {
  int i;
  for (i = 0; i < (int)m_deformTool->getTool()->getBBoxsCount(); i++)
    m_startBboxs.push_back(m_deformTool->getTool()->getBBox(i));
}
Member Function Documentation
bboxScale()
DragSelectionTool::FourPoints DragSelectionTool::Scale::bboxScale (int index, const FourPoints & oldBbox, const TPointD & pos)
Scale index point of bbox in pos and return scaled bbox.
{
  FourPoints bbox = oldBbox;
  TPointD p       = oldBbox.getPoint(index);
  int nextIndex   = m_deformTool->getNextVertexIndex(index);
  TPointD nextP   = oldBbox.getPoint(nextIndex);
  int nextIndex2  = m_deformTool->getNextVertexIndex(nextIndex);
  TPointD next2P  = oldBbox.getPoint(nextIndex2);
  TPointD newP    = getIntersectionPoint(next2P, nextP, nextP, p, pos);
  bbox.setPoint(nextIndex, newP);
  int beforeIndex  = m_deformTool->getBeforeVertexIndex(index);
  TPointD beforeP  = oldBbox.getPoint(beforeIndex);
  int before2Index = m_deformTool->getBeforeVertexIndex(beforeIndex);
  TPointD before2P = oldBbox.getPoint(before2Index);
  newP             = getIntersectionPoint(before2P, beforeP, beforeP, p, pos);
  bbox.setPoint(beforeIndex, newP);
  if (index < 4) bbox.setPoint(index, pos);
  return bbox;
}
References DragSelectionTool::FourPoints::getPoint(), and DragSelectionTool::FourPoints::setPoint().
bboxScaleInCenter()
FourPoints DragSelectionTool::Scale::bboxScaleInCenter (int index, const FourPoints & oldBbox, const TPointD newPos, TPointD & scaleValue, const TPointD center, bool recomputeScaleValue)
Scale bbox index point in pos and if m_scaleInCenter is true scale in center bbox symmetric point; compute scaleValue.
{
  TPointD oldp = oldBbox.getPoint(index);
  if (areAlmostEqual(oldp.x, newPos.x, 1e-2) &&
      areAlmostEqual(oldp.y, newPos.y, 1e-2))
    return oldBbox;
  FourPoints bbox = bboxScale(index, oldBbox, newPos);
  if (recomputeScaleValue) scaleValue = computeScaleValue(index, bbox);
  if (!m_scaleInCenter) return bbox;
  int symmetricIndex = m_deformTool->getSymmetricPointIndex(index);
  // Gestisco il caso particolare in cui uno dei fattori di scalatura e' -100% e
  // center e' al centro della bbox
  if (bbox.getPoint(index) == oldBbox.getPoint(symmetricIndex)) {
    bbox.setPoint(symmetricIndex, oldBbox.getPoint(index));
    bbox.setPoint(m_deformTool->getNextPointIndex(symmetricIndex),
                  oldBbox.getPoint(m_deformTool->getBeforePointIndex(index)));
    bbox.setPoint(m_deformTool->getBeforePointIndex(symmetricIndex),
                  oldBbox.getPoint(m_deformTool->getNextPointIndex(index)));
  } else
    bbox =
        bboxScale(symmetricIndex, bbox,
                  getScaledPoint(symmetricIndex, oldBbox, scaleValue, center));
  return bbox;
}
References DragSelectionTool::FourPoints::getPoint(), and DragSelectionTool::FourPoints::setPoint().
Referenced by DragSelectionTool::RasterScaleTool::transform().
computeScaleValue()
TPointD DragSelectionTool::Scale::computeScaleValue (int movedIndex, const FourPoints newBbox)
Compute new scale value take care of new position of movedIndex point in bbox.
{
  TPointD p = m_startBboxs[0].getPoint(movedIndex);
  if (movedIndex < 4) {
    int beforeIndex = m_deformTool->getBeforePointIndex(movedIndex);
    int nextIndex   = m_deformTool->getNextPointIndex(movedIndex);
    FourPoints bbox = bboxScale(nextIndex, newBbox, p);
    TPointD scale1  = computeScaleValue(beforeIndex, bbox);
    bbox            = bboxScale(beforeIndex, newBbox, p);
    TPointD scale2  = computeScaleValue(nextIndex, bbox);
    if (movedIndex % 2 == 0)
      return TPointD(scale1.x, scale2.y);
    else
      return TPointD(scale2.x, scale1.y);
  }
  int symmetricIndex = m_deformTool->getSymmetricPointIndex(movedIndex);
  TPointD s          = m_startBboxs[0].getPoint(symmetricIndex);
  TPointD center     = m_scaleInCenter ? m_startCenter : s;
  TPointD nearP =
      m_startBboxs[0].getPoint(m_deformTool->getBeforePointIndex(movedIndex));
  TPointD pc   = getIntersectionPoint(nearP, p, p, s, center);
  TPointD newp = newBbox.getPoint(movedIndex);
  TPointD news = newBbox.getPoint(symmetricIndex);
  TPointD newNearP =
      newBbox.getPoint(m_deformTool->getBeforePointIndex(movedIndex));
  TPointD newpc = getIntersectionPoint(newNearP, newp, newp, news, center);
  double newD             = tdistance2(newpc, center);
  double oldD             = tdistance2(pc, center);
  double f                = sqrt(newD / oldD) - 1;
  TPointD startScaleValue = m_deformTool->getStartScaleValue();
  if (movedIndex % 2 == 1) {
    double sign = (pc.x < center.x && newpc.x < center.x) ||
                          (pc.x > center.x && newpc.x > center.x)
                      ? 1
                      : -1;
    double x =
        startScaleValue.x == 0 ? f : startScaleValue.x + startScaleValue.x * f;
    return TPointD(sign * x, startScaleValue.y);
  } else {
    double sign = (pc.y < center.y && newpc.y < center.y) ||
                          (pc.y > center.y && newpc.y > center.y)
                      ? 1
                      : -1;
    double y =
        startScaleValue.y == 0 ? f : startScaleValue.y + startScaleValue.y * f;
    return TPointD(startScaleValue.x, sign * y);
  }
}
References DragSelectionTool::FourPoints::getPoint().
getIntersectionPoint()
TPointD DragSelectionTool::Scale::getIntersectionPoint (const TPointD & point0, const TPointD & point1, const TPointD & point2, const TPointD & point3, const TPointD & p) const
Return intersection between straight line in point0, point1 and straight line for p parallel to straight line in point2, point3.
{
  // Parametri della retta passante per point0, point1
  double d1x = point0.x - point1.x;
  double m1  = d1x == 0 ? 0 : (point0.y - point1.y) / d1x;
  double q1  = point1.y - m1 * point1.x;
  // Parametri della retta passante per p parallela alla retta passante per
  // point1, point2
  double d2x = point2.x - point3.x;
  double m2  = d2x == 0 ? 0 : (point2.y - point3.y) / d2x;
  double q2  = p.y - m2 * p.x;
  // Calcolo l'intersezione tra le due rette
  double x, y, m, q;
  if (d1x == 0) {
    x = point0.x;
    m = m2;
    q = q2;
  } else if (d2x == 0) {
    x = p.x;
    m = m1;
    q = q1;
  } else {
    assert(m1 != m2);
    x = (q1 - q2) / (m2 - m1);
    m = m1;
    q = q1;
  }
  y = m * x + q;
  return TPointD(x, y);
}
getNewCenter()
TPointD DragSelectionTool::Scale::getNewCenter (int index, const FourPoints bbox, const TPointD scaleValue)
Compute new center after scale of bbox index point.
{
  int xIndex, yIndex;
  if (index < 4) {
    xIndex = m_deformTool->getBeforePointIndex(index);
    yIndex = m_deformTool->getNextPointIndex(index);
  } else {
    xIndex =
        m_deformTool->getNextPointIndex(m_deformTool->getNextPointIndex(index));
    yIndex = index;
  }
  if (index % 2 == 1) std::swap(xIndex, yIndex);
  FourPoints xBbox = bboxScale(xIndex, bbox, m_startCenter);
  TPointD xCenter  = getScaledPoint(
      xIndex, xBbox, scaleValue,
      xBbox.getPoint(m_deformTool->getSymmetricPointIndex(xIndex)));
  FourPoints yBbox = bboxScale(yIndex, bbox, m_startCenter);
  TPointD yCenter  = getScaledPoint(
      yIndex, yBbox, scaleValue,
      yBbox.getPoint(m_deformTool->getSymmetricPointIndex(yIndex)));
  TPointD in = getIntersectionPoint(bbox.getP00(), bbox.getP10(), bbox.getP10(),
                                    bbox.getP11(), xCenter);
  return getIntersectionPoint(in, xCenter, bbox.getP00(), bbox.getP10(),
                              yCenter);
}
References DragSelectionTool::FourPoints::getPoint().
Referenced by DragSelectionTool::RasterScaleTool::transform().
getScaledPoint()
TPointD DragSelectionTool::Scale::getScaledPoint (int index, const FourPoints & oldBbox, const TPointD scaleValue, const TPointD center)
Return index point scaled in center of scaleValue.
{
  TPointD p          = oldBbox.getPoint(index);
  int symmetricIndex = m_deformTool->getSymmetricPointIndex(index);
  TPointD s          = oldBbox.getPoint(symmetricIndex);
  if (index < 4) {
    int beforeIndex = m_deformTool->getBeforePointIndex(index);
    int nextIndex   = m_deformTool->getNextPointIndex(index);
    TPointD newbp   = getScaledPoint(beforeIndex, oldBbox, scaleValue, center);
    TPointD newnp   = getScaledPoint(nextIndex, oldBbox, scaleValue, center);
    TPointD bp = oldBbox.getPoint(m_deformTool->getBeforePointIndex(index));
    TPointD np = oldBbox.getPoint(m_deformTool->getNextPointIndex(index));
    TPointD in = getIntersectionPoint(np, p, bp, p, newbp);
    return getIntersectionPoint(newbp, in, np, p, newnp);
  }
  TPointD nearP = oldBbox.getPoint(m_deformTool->getBeforePointIndex(index));
  TPointD nearS =
      oldBbox.getPoint(m_deformTool->getBeforePointIndex(symmetricIndex));
  TPointD pc = getIntersectionPoint(nearP, p, p, s, center);
  TPointD sc = getIntersectionPoint(nearS, s, p, s, center);
  if (center == pc) return pc;
  TPointD v       = normalize(center - pc);
  double currentD = tdistance(sc, pc);
  double startD   = (index % 2 == 1)
                      ? currentD / m_deformTool->getStartScaleValue().x
                      : currentD / m_deformTool->getStartScaleValue().y;
  double factor = (index % 2 == 1) ? scaleValue.x : scaleValue.y;
  double d = (currentD - startD * factor) * tdistance(center, pc) / currentD;
  return TPointD(pc.x + d * v.x, pc.y + d * v.y);
}
References DragSelectionTool::FourPoints::getPoint().
getStartBboxs()
std::vector< FourPoints > DragSelectionTool::Scale::getStartBboxs () const inline
{ return m_startBboxs; }
getStartCenter()
TPointD DragSelectionTool::Scale::getStartCenter () const inline
{ return m_startCenter; }
leftButtonDown()
void DragSelectionTool::Scale::leftButtonDown (const TPointD & pos, const TMouseEvent & e)
{
  m_isShiftPressed = e.isShiftPressed();
  m_isAltPressed   = e.isAltPressed();
}
leftButtonDrag()
void DragSelectionTool::Scale::leftButtonDrag (const TPointD & pos, const TMouseEvent & e)
{
  SelectionTool *tool = m_deformTool->getTool();
  bool isBboxReset    = false;
  if (m_isShiftPressed != e.isShiftPressed() ||
      m_isAltPressed != e.isAltPressed()) {
    m_deformTool->applyTransform(m_startBboxs[0]);
    tool->setBBox(m_startBboxs[0]);
    tool->setCenter(m_startCenter);
    isBboxReset      = true;
    m_isShiftPressed = e.isShiftPressed();
    m_isAltPressed   = e.isAltPressed();
  }
  TPointD newPos    = pos;
  int selectedIndex = tool->getSelectedPoint();
  if (m_isShiftPressed && m_type == ScaleType::GLOBAL) {
    TPointD point = tool->getBBox().getPoint(selectedIndex);
    TPointD delta;
    if (!isBboxReset)
      delta = pos - m_deformTool->getCurPos();
    else
      delta = pos - m_deformTool->getStartPos();
    int symmetricIndex = m_deformTool->getSymmetricPointIndex(selectedIndex);
    TPointD symmetricPoint = tool->getBBox().getPoint(symmetricIndex);
    TPointD v              = normalize(point - symmetricPoint);
    delta                  = v * (v * delta);
    newPos                 = point + delta;
  }
  m_scaleInCenter = m_isAltPressed;
  double pixelSize = tool->getPixelSize();
  bool isFastDragging =
      tdistance2(pos, m_deformTool->getCurPos()) > 9.0 * pixelSize * pixelSize;
  m_deformTool->setCurPos(pos);
  TPointD scaleValue =
      m_deformTool->transform(selectedIndex, newPos, isFastDragging);
  tool->m_deformValues.m_scaleValue = scaleValue;
  TTool::getApplication()->getCurrentTool()->notifyToolChanged();
}
leftButtonUp()
void DragSelectionTool::Scale::leftButtonUp ()
{
  SelectionTool *tool = m_deformTool->getTool();
  TPointD newPos      = m_deformTool->getCurPos();
  int selectedIndex   = tool->getSelectedPoint();
  if (m_isShiftPressed && m_type == ScaleType::GLOBAL) {
    newPos = tool->getBBox().getPoint(selectedIndex);
  }
  m_deformTool->transform(selectedIndex, newPos);
  TTool::getApplication()->getCurrentTool()->notifyToolChanged();
}
scaleInCenter()
bool DragSelectionTool::Scale::scaleInCenter () const inline
{ return m_scaleInCenter; }
Member Data Documentation
m_type
ScaleType DragSelectionTool::Scale::m_type
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/tnztools/selectiontool.h
E:/opentoonz/toonz/sources/tnztools/selectiontool.cpp