opentoonz: TNotAnimatableParam< T > Class Template Reference
TNotAnimatableParam< T > Class Template Reference
Public Member Functions
TNotAnimatableParam (T def=T())
TNotAnimatableParam (const TNotAnimatableParam &src)
T getValue () const
T getDefaultValue () const
void setValue (T v, bool undoing=false)
void setDefaultValue (T value)
void copy (TParam *src) override
void reset (bool undoing=false)
void addObserver (TParamObserver *observer) override
void removeObserver (TParamObserver *observer) override
bool isAnimatable () const override
bool isKeyframe (double) const override
void deleteKeyframe (double) override
void clearKeyframes () override
void assignKeyframe (double, const TSmartPointerT< TParam > &, double, bool) override
std::string getValueAlias (double, int) override
bool hasKeyframes () const override
void getKeyframes (std::set< double > &) const override
int getNextKeyframe (double) const override
int getPrevKeyframe (double) const override
Public Member Functions inherited from TParam
TParam (std::string name="", std::string description="", std::string label="")
std::string getName () const
void setName (const std::string &name)
std::string getDescription () const
void setDescription (const std::string &description)
bool hasUILabel () const
void setUILabel (const std::string &l)
std::string getUILabel () const
virtual TParam * clone () const =0
virtual void copy (TParam *src)=0
virtual void addObserver (TParamObserver *)=0
virtual void removeObserver (TParamObserver *)=0
virtual void enableNotification (bool on)
virtual bool isNotificationEnabled () const
virtual std::string getValueAlias (double frame, int precision)=0
virtual bool isAnimatable () const =0
virtual bool isKeyframe (double frame) const =0
virtual void deleteKeyframe (double frame)=0
virtual void clearKeyframes ()=0
virtual void assignKeyframe (double frame, const TSmartPointerT< TParam > &src, double srcFrame, bool changedOnly=false)=0
virtual void getKeyframes (std::set< double > &frames) const
virtual bool hasKeyframes () const
virtual int getNextKeyframe (double frame) const
virtual int getPrevKeyframe (double frame) const
virtual double keyframeIndexToFrame (int index) const
Public Member Functions inherited from TSmartObject
TSmartObject (ClassCode classCode)
void addRef ()
void release ()
TINT32 getRefCount () const
Public Member Functions inherited from TPersist
virtual void loadData (TIStream &is)=0
virtual void saveData (TOStream &os)=0
std::string getStreamTag () const
virtual const TPersistDeclaration * getDeclaration () const =0
Protected Attributes
std::set< TNotAnimatableParamObserver< T > * > m_observers
std::set< TParamObserver * > m_paramObservers
Additional Inherited Members
Public Types inherited from TSmartObject
typedef short ClassCode
Public Types inherited from TPersist
typedef TPersist * CreateProc()
Static Public Member Functions inherited from TSmartObject
static TINT32 getInstanceCount (ClassCode code)
Static Public Member Functions inherited from TPersist
static void declare (CreateProc *)
static TPersist * create (const std::string &name)
Detailed Description
template<class T>
class TNotAnimatableParam< T >
Constructor & Destructor Documentation
TNotAnimatableParam() [1/2]
template<class T > TNotAnimatableParam< T >::TNotAnimatableParam (T def = T()) inline
      : TParam(), m_defaultValue(def), m_value(def){};
TNotAnimatableParam() [2/2]
template<class T > TNotAnimatableParam< T >::TNotAnimatableParam (const TNotAnimatableParam< T > & src) inline
      : TParam(src.getName())
      , m_defaultValue(src.getDefaultValue())
      , m_value(src.getValue()){};
~TNotAnimatableParam()
template<class T > TNotAnimatableParam< T >::~TNotAnimatableParam () inline
{};
Member Function Documentation
addObserver()
template<class T > void TNotAnimatableParam< T >::addObserver (TParamObserver *) inline override virtual
 An observer is a generic class that takes care and manages of canghes
in the parameters. This method must be implemented with a function that add objects to an observer internal list.
Implements TParam.
{
    TNotAnimatableParamObserver<T> *obs =
        dynamic_cast<TNotAnimatableParamObserver<T> *>(observer);
    if (obs)
      m_observers.insert(obs);
    else
      m_paramObservers.insert(observer);
  }
assignKeyframe()
template<class T > void TNotAnimatableParam< T >::assignKeyframe (double frame, const TSmartPointerT< TParam > & src, double srcFrame, bool changedOnly) inline override virtual
Makes the frame associated to this parameter a keyframe
Implements TParam.
                                     {}
clearKeyframes()
template<class T > void TNotAnimatableParam< T >::clearKeyframes () inline override virtual
Removes all keyframes from this parameter.
Implements TParam.
{}
copy()
template<class T > void TNotAnimatableParam< T >::copy (TParam * src) inline override virtual
Performs a copy function of the parameter in an existing object.
Implements TParam.
{
    TNotAnimatableParam<T> *p = dynamic_cast<TNotAnimatableParam<T> *>(src);
    if (!p) throw TException("invalid source for copy");
    setName(src->getName());
    m_defaultValue = p->m_defaultValue;
    m_value        = p->m_value;
  }
References TParam::getName(), and TParam::setName().
Referenced by TEnumParam::copy().
deleteKeyframe()
template<class T > void TNotAnimatableParam< T >::deleteKeyframe (double frame) inline override virtual
 Removes \e frame from the list of the keyframes associated to this
parameter.
Implements TParam.
{}
getDefaultValue()
template<class T > T TNotAnimatableParam< T >::getDefaultValue () const inline
{ return m_defaultValue; }
getKeyframes()
template<class T > void TNotAnimatableParam< T >::getKeyframes (std::set< double > & frames) const inline override virtual
 This function must be overridden with a method that returns as a
reference a list of keyframes in the form of a standard list.
Reimplemented from TParam.
{};
getNextKeyframe()
template<class T > int TNotAnimatableParam< T >::getNextKeyframe (double frame) const inline override virtual
 This method must return the index of the keyframe (if any) after the
frame, otherwiswe returns -1.
Reimplemented from TParam.
{ return -1; };
getPrevKeyframe()
template<class T > int TNotAnimatableParam< T >::getPrevKeyframe (double frame) const inline override virtual
 This method must return the index of the keyframe (if any) before the
frame, otherwiswe returns -1.
Reimplemented from TParam.
{ return -1; };
getValue()
template<class T > T TNotAnimatableParam< T >::getValue () const inline
{ return m_value; }
getValueAlias()
template<class T > std::string TNotAnimatableParam< T >::getValueAlias (double frame, int precision) inline override virtual
 This pure virtual method must return a string with the value of the
parameter and the precision needed.
Implements TParam.
{
    using namespace std;
    return to_string(getValue());
  }
hasKeyframes()
template<class T > bool TNotAnimatableParam< T >::hasKeyframes () const inline override virtual
 This method must return true if there are keyframes associated to this
parameter.
Reimplemented from TParam.
{ return 0; };
isAnimatable()
template<class T > bool TNotAnimatableParam< T >::isAnimatable () const inline override virtual
Implements TParam.
{ return false; }
isKeyframe()
template<class T > bool TNotAnimatableParam< T >::isKeyframe (double frame) const inline override virtual
It must returns true if the frame is a keyframe.
Implements TParam.
{ return false; }
removeObserver()
template<class T > void TNotAnimatableParam< T >::removeObserver (TParamObserver *) inline override virtual
Removes this from the observer.
See also
addObserver()
Implements TParam.
{
    TNotAnimatableParamObserver<T> *obs =
        dynamic_cast<TNotAnimatableParamObserver<T> *>(observer);
    if (obs)
      m_observers.erase(obs);
    else
      m_paramObservers.erase(observer);
  }
reset()
template<class T > void TNotAnimatableParam< T >::reset (bool undoing = false) inline
{ setValue(m_defaultValue, undoing); }
setDefaultValue()
template<class T > void TNotAnimatableParam< T >::setDefaultValue (T value) inline
{ m_defaultValue = value; }
setValue()
template<class T > void TNotAnimatableParam< T >::setValue (T v, bool undoing = false) inline
{
    if (m_value == v) return;
    TNotAnimatableParamChange<T> change(this, m_value, v, undoing);
    m_value = v;
    for (typename std::set<TNotAnimatableParamObserver<T> *>::iterator obsIt =
             m_observers.begin();
         obsIt != m_observers.end(); ++obsIt)
      (*obsIt)->onChange(change);
    for (std::set<TParamObserver *>::iterator parObsIt =
             m_paramObservers.begin();
         parObsIt != m_paramObservers.end(); ++parObsIt)
      (*parObsIt)->onChange(change);
  }
Member Data Documentation
m_observers
template<class T > std::set<TNotAnimatableParamObserver<T> *> TNotAnimatableParam< T >::m_observers protected
m_paramObservers
template<class T > std::set<TParamObserver *> TNotAnimatableParam< T >::m_paramObservers protected
The documentation for this class was generated from the following file:
E:/opentoonz/toonz/sources/include/tnotanimatableparam.h