opentoonz: DVGui::SpectrumBar Class Reference
DVGui::SpectrumBar Class Reference final
The SpectrumBar class provides a bar to display a spectrum.
Public Slots
void setCurrentPos (int pos, bool isDragging)
void setCurrentColor (const TPixel32 &color)
void addKeyAt (int pos)
Signals
void currentPosChanged (bool isDragging)
void currentKeyChanged ()
void currentKeyAdded (int)
void currentKeyRemoved (int)
Public Member Functions
SpectrumBar (QWidget *parent=0, TPixel32 color=TPixel32(0, 0, 0, 255))
int getCurrentKeyIndex ()
void setCurrentKeyIndex (int index)
int getCurrentPos ()
TPixel32 getCurrentColor ()
TSpectrum & getSpectrum ()
void setSpectrum (TSpectrum &spectrum)
Protected Member Functions
double posToSpectrumValue (int pos)
int spectrumValueToPos (double spectrumValue)
void paintEvent (QPaintEvent *e) override
void mousePressEvent (QMouseEvent *e) override
void mouseMoveEvent (QMouseEvent *e) override
void mouseReleaseEvent (QMouseEvent *e) override
int getMaxPosKeyIndex ()
int getMinPosKeyIndex ()
int getNearPosKeyIndex (int pos)
Detailed Description
The SpectrumBar class provides a bar to display a spectrum.
         Inherits \b QWidget.
         The object allows to manage a spectrum, permit you to insert,
move and remove key.
You can set spectrum default color in constructor, or set color of current key, getCurrentColor(), using setCurrentColor(). It's possible to change current key, getCurrentKeyIndex(), through its index, setCurrentKeyIndex(). You can also set current key position, getCurrentPos(), using setCurrentPos() or add a new key in a specific position, addKeyAt().
Constructor & Destructor Documentation
SpectrumBar()
SpectrumBar::SpectrumBar (QWidget * parent = 0, TPixel32 color = TPixel32(0, 0, 0, 255))
    : QWidget(parent)
    , m_x0(10)
    , m_currentKeyIndex(0)
    , m_spectrum(color, color)
    , m_chessBg(":Resources/backg.png") {
  setMinimumWidth(200);
  setFixedHeight(WidgetHeight);
}
~SpectrumBar()
SpectrumBar::~SpectrumBar ()
{}
Member Function Documentation
addKeyAt
void SpectrumBar::addKeyAt (int x) slot
Add a new key to spectrum. Key position is computed x using posToSpectrumValue() and color come from position.
{
  TPixel32 color = m_spectrum.getValue(posToSpectrumValue(x));
  TSpectrum::ColorKey key(posToSpectrumValue(x), color);
  m_spectrum.addKey(key);
  int newIndex = m_spectrum.getKeyCount() - 1;
  setCurrentKeyIndex(newIndex);
  emit currentKeyAdded(newIndex);
}
References posToSpectrumValue(), and setCurrentKeyIndex().
Referenced by mouseMoveEvent(), and mousePressEvent().
currentKeyChanged
void DVGui::SpectrumBar::currentKeyChanged () signal
The signal is emitted when current key index change.
Referenced by setCurrentKeyIndex().
currentPosChanged
void DVGui::SpectrumBar::currentPosChanged (bool isDragging) signal
The signal is emitted when current key position change.
Referenced by setCurrentPos().
getCurrentColor()
TPixel32 SpectrumBar::getCurrentColor ()
Return current key color.
{
  if (m_currentKeyIndex == -1)  // C'e' sicuramente una key perche' lo spectrum
                                // e' strutturato in modo da non avere mai size
                                // nulla.
    return m_spectrum.getKey(getMaxPosKeyIndex()).second;
  return m_spectrum.getKey(m_currentKeyIndex).second;
}
References getMaxPosKeyIndex().
Referenced by DVGui::SpectrumField::onCurrentKeyChanged().
getCurrentKeyIndex()
int DVGui::SpectrumBar::getCurrentKeyIndex () inline
{ return m_currentKeyIndex; }
getCurrentPos()
int SpectrumBar::getCurrentPos ()
Return current key position.
{
  if (m_currentKeyIndex == -1) return -1;
  return spectrumValueToPos(m_spectrum.getKey(m_currentKeyIndex).first);
}
References spectrumValueToPos().
Referenced by DVGui::SpectrumField::paintEvent().
getMaxPosKeyIndex()
int SpectrumBar::getMaxPosKeyIndex () protected
Return index of key with maximum position.
{
  int spectrumSize = m_spectrum.getKeyCount();
  if (!spectrumSize) return -1;
  int maxPosIndex = 0;
  int maxPos      = spectrumValueToPos(m_spectrum.getKey(0).first);
  int i;
  for (i = 0; i < spectrumSize; i++) {
    int newPos = spectrumValueToPos(m_spectrum.getKey(i).first);
    if (maxPos < newPos) {
      maxPos      = newPos;
      maxPosIndex = i;
    }
  }
  return maxPosIndex;
}
References spectrumValueToPos().
Referenced by getCurrentColor(), and mousePressEvent().
getMinPosKeyIndex()
int SpectrumBar::getMinPosKeyIndex () protected
Return index of key with minimum position.
{
  int spectrumSize = m_spectrum.getKeyCount();
  if (!spectrumSize) return -1;
  int minPosIndex = 0;
  int minPos      = spectrumValueToPos(m_spectrum.getKey(0).first);
  int i;
  for (i = 0; i < spectrumSize; i++) {
    int newPos = spectrumValueToPos(m_spectrum.getKey(i).first);
    if (minPos > newPos) {
      minPos      = newPos;
      minPosIndex = i;
    }
  }
  return minPosIndex;
}
References spectrumValueToPos().
Referenced by mousePressEvent().
getNearPosKeyIndex()
int SpectrumBar::getNearPosKeyIndex (int pos) protected
Return index of key "near" pos. "near" mean with a dinstace less than a constant size. If there aren't key near pos return -1.
{
  int i;
  int gap = 20;
  for (i = 0; i < m_spectrum.getKeyCount(); i++)
    if (areAlmostEqual(double(pos),
                       double(spectrumValueToPos(m_spectrum.getKey(i).first)),
                       gap))
      return i;
  return -1;
}
References spectrumValueToPos().
Referenced by mousePressEvent().
getSpectrum()
TSpectrum & DVGui::SpectrumBar::getSpectrum () inline
{ return m_spectrum; }
mouseMoveEvent()
void SpectrumBar::mouseMoveEvent (QMouseEvent * e) override protected
Manage mouse move event. If y position value greater than widget height erase current key; otherwise move current key position.
{
  QPoint pos = e->pos();
  int x      = pos.x();
  int y      = pos.y();
  if (x < m_x0 || x > width() - m_x0 - 1) return;
  // Se il valore della y e' maggiore dell'altezza widget, cioe' va fuori dal
  // widget
  // elimino la key corrente
  if (y > height()) {
    if (m_currentKeyIndex == -1 || m_spectrum.getKeyCount() == 1) return;
    m_spectrum.removeKey(m_currentKeyIndex);
    int keyIndex = m_currentKeyIndex;
    setCurrentKeyIndex(-1);
    emit currentKeyRemoved(keyIndex);
    return;
  }
  // Se il valore della y e' interno al widget
  // Se l'indice della key corrente e' -1 avevo eliminato un key; ora devo
  // riaggiungerla.
  if (m_currentKeyIndex == -1) addKeyAt(x);
  // Setto la nuova posizione x alla chiave corrente
  setCurrentPos(x, true);
}
References addKeyAt(), setCurrentKeyIndex(), and setCurrentPos().
mousePressEvent()
void SpectrumBar::mousePressEvent (QMouseEvent * e) override protected
Manage mouse press event. Search existing key near click position, if there is set it as current key; otherwise add a new key in click position.
{
  QPoint pos = e->pos();
  int x      = pos.x();
  // Verifico se esiste una key vicino alla posizione in cui ho cliccato
  int index        = -1;
  int spectrumSize = m_spectrum.getKeyCount();
  if (x < m_x0)
    index = getMinPosKeyIndex();
  else if (x > width() - m_x0)
    index = getMaxPosKeyIndex();
  else
    index = getNearPosKeyIndex(x);
  // Se x e' vicino a una key esistente setto questa come corrente
  if (index != -1)
    setCurrentKeyIndex(index);
  else  // Altrimenti aggiungo una nuova key
    addKeyAt(x);
}
References addKeyAt(), getMaxPosKeyIndex(), getMinPosKeyIndex(), getNearPosKeyIndex(), and setCurrentKeyIndex().
mouseReleaseEvent()
void SpectrumBar::mouseReleaseEvent (QMouseEvent * e) override protected
{
  if (m_currentKeyIndex == -1) return;
  QPoint pos = e->pos();
  int x      = pos.x();
  int y      = pos.y();
  if (x < m_x0 || x > width() - m_x0 - 1) return;
  if (y > height()) return;
  setCurrentPos(x, false);
}
paintEvent()
void SpectrumBar::paintEvent (QPaintEvent * e) override protected
Paint widget object:
a linear gradient computed with spectrum value;
arrows for each spectrum key.
{
  QPainter p(this);
  int h          = height() - 1;
  int y1         = height() / 2;
  int x1         = width() - m_x0;
  QRectF rectBar = QRectF(m_x0, 0, x1 - m_x0 + 1, y1);
  // Build the linear gradient
  QLinearGradient linearGrad(QPointF(m_x0, h), QPointF(x1, h));
  int spectrumSize = m_spectrum.getKeyCount();
  int i;
  for (i = 0; i < spectrumSize; i++) {
    TSpectrum::ColorKey key = m_spectrum.getKey(i);
    // Linear Gradient
    TPixel32 pix         = key.second;
    double spectrumValue = key.first;
    linearGrad.setColorAt(spectrumValue, QColor(pix.r, pix.g, pix.b, pix.m));
    // Frecce delle key
    int pos = spectrumValueToPos(spectrumValue);
    int f   = 4;
    drawArrow(p, QPointF(pos - f, y1 + f), QPointF(pos, y1),
              QPointF(pos + f, y1 + f), true,
              (m_currentKeyIndex == i) ? Qt::black : Qt::white);
  }
  p.setPen(Qt::NoPen);
  // Draw chess bg
  QBrush bg;
  bg.setTexture(m_chessBg);
  p.setBrush(bg);
  p.drawRect(rectBar);
  // Draw the gradient
  p.setBrush(linearGrad);
  p.drawRect(rectBar);
}
References spectrumValueToPos().
posToSpectrumValue()
double SpectrumBar::posToSpectrumValue (int pos) protected
Return spectrum value from widget position pos.
{
  return (double)(pos - m_x0) / (double)(width() - 2 * m_x0 - 1);
}
Referenced by addKeyAt(), and setCurrentPos().
setCurrentColor
void SpectrumBar::setCurrentColor (const TPixel32 & color) slot
Set current key color to color. Update spectrum bar.
{
  if (m_currentKeyIndex == -1) return;
  TSpectrum::ColorKey key = m_spectrum.getKey(m_currentKeyIndex);
  TPixel32 oldColor       = key.second;
  if (oldColor == color) return;
  key.second = color;
  m_spectrum.setKey(m_currentKeyIndex, key);
  update();
}
Referenced by DVGui::SpectrumField::onColorChanged().
setCurrentKeyIndex()
void SpectrumBar::setCurrentKeyIndex (int index)
Set current key index to index. Update spectrum bar and emit a signal to notify current key changed currentKeyChanged().
{
  if (m_currentKeyIndex == index) return;
  m_currentKeyIndex = index;
  update();
  emit currentKeyChanged();
}
References currentKeyChanged().
Referenced by addKeyAt(), mouseMoveEvent(), and mousePressEvent().
setCurrentPos
void SpectrumBar::setCurrentPos (int pos, bool isDragging) slot
Set current key position to pos. Update spectrum bar and emit a signal to notify current key changed currentKeyChanged().
{
  TSpectrum::ColorKey key = m_spectrum.getKey(m_currentKeyIndex);
  key.first               = posToSpectrumValue(pos);
  m_spectrum.setKey(m_currentKeyIndex, key);
  update();
  emit currentPosChanged(isDragging);
}
References currentPosChanged(), and posToSpectrumValue().
Referenced by mouseMoveEvent().
setSpectrum()
void DVGui::SpectrumBar::setSpectrum (TSpectrum & spectrum) inline
{
    m_spectrum = spectrum;
    /*-- UndoSpectrumIndex
     * --*/
    if (m_currentKeyIndex >= m_spectrum.getKeyCount())
      setCurrentKeyIndex(getMaxPosKeyIndex());
    update();
  }
spectrumValueToPos()
int SpectrumBar::spectrumValueToPos (double spectrumValue) protected
Return widget position from spectrum value spectrumValue.
{
  return m_x0 + int(0.5 + spectrumValue * (width() - 2 * m_x0));
}
Referenced by getCurrentPos(), getMaxPosKeyIndex(), getMinPosKeyIndex(), getNearPosKeyIndex(), and paintEvent().
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/toonzqt/spectrumfield.h
E:/opentoonz/toonz/sources/toonzqt/spectrumfield.cpp