opentoonz: HookTool Class Reference
HookTool Class Reference final
Public Member Functions
ToolType getToolType () const override
HookSet * getHookSet () const
void updateTranslation () override
void draw () override
Draws the tool on the viewer.
void leftButtonDown (const TPointD &pos, const TMouseEvent &e) override
void leftButtonDrag (const TPointD &pos, const TMouseEvent &e) override
void leftButtonUp (const TPointD &pos, const TMouseEvent &) override
void mouseMove (const TPointD &pos, const TMouseEvent &e) override
void onActivate () override
Callback invoked whenever the tool activates.
void onDeactivate () override
Callback for tool deactivation, includes tool switch.
void onEnter () override
Callback for the mouse entering the viewer area.
void onImageChanged () override
Notifies changes in the image in use.
TPropertyGroup * getProperties (int targetType) override
int getCursorId () const override
Returns the type of cursor used by the tool.
void onSelectionChanged ()
bool select (const TSelection *)
bool pick (int &hookId, int &side, const TPointD &pos)
bool snap (TPointD &pos, double &range2)
bool isSnappedActive () const
bool isEditingScene () const
int getPivotIndex ()
void drawHooks (HookSet *hookSet, const TFrameId &fid, bool isOnion)
void updateMatrix () override
Public Member Functions inherited from TTool
TTool (std::string toolName)
every tool (invoking updateTranslation() for each).
virtual ToolType getToolType () const =0
ToolTargetType getTargetType () const
std::string getName () const
virtual ToolOptionsBox * createOptionsBox ()
void setViewer (Viewer *viewer)
Viewer * getViewer () const
double getPixelSize () const
void invalidate (const TRectD &rect=TRectD())
int pick (const TPointD &p)
bool isPicking () const
virtual void updateTranslation ()
virtual bool preLeftButtonDown ()
virtual void mouseMove (const TPointD &, const TMouseEvent &)
virtual void leftButtonDown (const TPointD &, const TMouseEvent &)
virtual void leftButtonDrag (const TPointD &, const TMouseEvent &)
virtual void leftButtonUp (const TPointD &, const TMouseEvent &)
virtual void leftButtonDoubleClick (const TPointD &, const TMouseEvent &)
virtual void rightButtonDown (const TPointD &, const TMouseEvent &)
virtual bool keyDown (QKeyEvent *)
virtual void onInputText (std::wstring, std::wstring, int, int)
virtual void onSetViewer ()
virtual void onActivate ()
Callback invoked whenever the tool activates.
virtual void onDeactivate ()
Callback for tool deactivation, includes tool switch.
virtual void onImageChanged ()
Notifies changes in the image in use.
virtual void onEnter ()
Callback for the mouse entering the viewer area.
virtual void onLeave ()
Callback for the mouse leaving the viewer area.
virtual void onFrameSwitched ()
virtual void reset ()
virtual void draw ()
Draws the tool on the viewer.
bool isActive () const
Used to know if a tool is active, (used in TextTool only).
void setActive (bool active)
virtual TPropertyGroup * getProperties (int)
virtual bool onPropertyChanged (std::string propertyName)
virtual TSelection * getSelection ()
Returns a pointer to the tool selection.
virtual int getCursorId () const
Returns the type of cursor used by the tool.
virtual bool isEventAcceptable (QEvent *e)
TXsheet * getXsheet () const
Returns a pointer to the actual Xsheet.
int getFrame ()
Returns the actual frame in use.
int getColumnIndex ()
Returns the actual column index.
TStageObjectId getObjectId () const
Returns a pointer to the actual stage object.
void notifyImageChanged ()
void notifyImageChanged (const TFrameId &fid)
images on the level view.
TFrameId getCurrentFid () const
Returns the number of the actual editing frame.
const TAffine & getMatrix () const
void setMatrix (const TAffine &matrix)
TAffine getCurrentColumnMatrix (int frame=-1) const
TAffine getCurrentColumnParentMatrix () const
TAffine getCurrentObjectParentMatrix () const
TAffine getCurrentObjectParentMatrix2 () const
TAffine getColumnMatrix (int index, int frame=-1) const
virtual void updateMatrix ()
virtual void addContextMenuItems (QMenu *menu)
void enable (bool on)
bool isEnabled () const
QString updateEnabled ()
virtual QString updateEnabled (int rowIndex, int columnIndex)
bool isColumnLocked (int columnIndex) const
void resetInputMethod ()
Resets Input Context (IME)
virtual bool isPencilModeActive ()
virtual bool isDragging () const
void setSelectedFrames (const std::set< TFrameId > &selectedFrames)
void tweenSelectedGuideStrokes ()
void tweenGuideStrokeToSelected ()
void flipGuideStrokeDirection (int mode)
Additional Inherited Members
Public Types inherited from TTool
enum ToolType {
GenericTool = 1 , ColumnTool = 2 , LevelReadTool = 4 , LevelWriteTool ,
LevelTool = LevelReadTool | LevelWriteTool
}
Tool editing type.
enum ToolTargetType {
NoTarget = 0x0 , VectorImage = 0x1 , ToonzImage = 0x2 , RasterImage = 0x4 ,
MeshImage = 0x8 , Splines = 0x10 , LevelColumns = 0x20 , MeshColumns = 0x40 ,
EmptyTarget = 0x80 , CommonImages = VectorImage | ToonzImage | RasterImage , AllImages = CommonImages | MeshImage , Vectors = VectorImage | Splines ,
CommonLevels = CommonImages | LevelColumns , MeshLevels = MeshImage | MeshColumns , AllTargets = 0xffffffff
}
Object types the tool can operate on.
typedef TApplication Application
Static Public Member Functions inherited from TTool
static TTool * getTool (std::string toolName, ToolTargetType targetType)
static TApplication * getApplication ()
static void setApplication (TApplication *application)
static TXshCell getImageCell ()
Returns the level-frame pair to be edited by the tool.
static TImage * getImage (bool toBeModified, int subsampling=0)
Returns the image to be edited by the tool.
static TImage * touchImage ()
static void updateToolsPropertiesTranslation ()
static const std::set< TFrameId > & getSelectedFrames ()
Static Public Attributes inherited from TTool
static std::vector< CellOps > m_cellsData
static bool m_isLevelCreated = false
static bool m_isFrameCreated = false
static std::vector< TFrameId > m_oldFids
static std::vector< TFrameId > m_newFids
static bool m_isLevelRenumbererd = false
Protected Member Functions inherited from TTool
void bind (int targetType)
virtual void onSelectedFramesChanged ()
virtual QString disableString ()
Returns a custom reason to disable the tool.
Protected Attributes inherited from TTool
std::string m_name
The tool's name.
Viewer * m_viewer
Tool's current viewer.
TAffine m_matrix
World-to-window reference change affine.
int m_targetType
The tool's image type target.
bool m_enabled
Whether the tool allows user interaction.
bool m_active
bool m_picking
Static Protected Attributes inherited from TTool
static TApplication * m_application = 0
static std::set< TFrameId > m_selectedFrames = std::set<TFrameId>()
Detailed Description
Constructor & Destructor Documentation
HookTool()
HookTool::HookTool ()
    : TTool("T_Hook")
    , m_hookId(-1)
    , m_hookSide(0)
    , m_deselectArmed(false)
    , m_undo(0)
    , m_snappedActive("Snap", true)  // W_ToolOptions_Snapped
    , m_snappedPos()
    , m_snappedReason("")
    , m_shapeBBox()
    , m_snapped(false)
    , m_hookSetChanged(false)
    , m_buttonDown(false)
    , m_pivotOffset() {
  bind(TTool::CommonLevels);
  m_prop.bind(m_snappedActive);
  m_snappedActive.setId("Snap");
}
Member Function Documentation
draw()
void HookTool::draw () override virtual
Draws the tool on the viewer.
Reimplemented from TTool.
                    {
  // ToolUtils::drawRect(TRectD(10,10,110,110), TPixel32(255,200,200), 0xFFF0);
  // draw the current image bounding box
  const double v200 = 200.0 / 255.0;
  TImageP image     = getImage(false);
  if (!image) return;
  TToonzImageP ti  = image;
  TVectorImageP vi = image;
  if (ti) {
    TRectD bbox =
        ToonzImageUtils::convertRasterToWorld(convert(ti->getBBox()), ti);
    ToolUtils::drawRect(bbox * ti->getSubsampling(), TPixel32(200, 200, 200),
                        0x5555);
  }
  if (vi) {
    TRectD bbox = vi->getBBox();
    ToolUtils::drawRect(bbox, TPixel32(200, 200, 200), 0x5555);
  }
  // draw hooks
  HookSet *hookSet = getHookSet();
  if (!hookSet) return;
  TTool::Application *app = TTool::getApplication();
  TFrameHandle *fh        = app->getCurrentFrame();
  TFrameId fid            = getCurrentFid();
  TXshSimpleLevel *level  = 0;
  OnionSkinMask osm = app->getCurrentOnionSkin()->getOnionSkinMask();
  std::vector<int> os;
  if (isEditingScene())
    osm.getAll(getFrame(), os);
  else {
    level = app->getCurrentLevel()->getSimpleLevel();
    assert(level);
    osm.getAll(level->guessIndex(fid), os);
  }
  int i;
  if (osm.isEnabled())
    for (i = 0; i < (int)os.size(); i++) {
      if (isEditingScene()) {
        const TXshCell &cell = getXsheet()->getCell(
            os[i], app->getCurrentColumn()->getColumnIndex());
        drawHooks(hookSet, cell.getFrameId(), true);
      } else {
        const TFrameId &fid2 = level->index2fid(os[i]);
        drawHooks(hookSet, fid2, true);
      }
    }
  drawHooks(hookSet, fid, false);
  // TXshCell cell = xsh->getCell(row, i);
  // draw other level hooks
  if (isSnappedActive() && isEditingScene()) {
    for (i = 0; i < (int)m_otherHooks.size(); i++) {
      drawHook(m_otherHooks[i].m_hookPos, OtherLevelHook, false);
    }
  }
  // draw hooks balloons
  std::vector<TRectD> balloons;  // this is used to avoid balloons overlapping
  int pivotIndex = getPivotIndex();
  for (i = 0; i < hookSet->getHookCount(); i++) {
    Hook *hook = hookSet->getHook(i);
    if (!hook || hook->isEmpty()) continue;
    assert(hook);
    TPointD p0  = hook->getAPos(fid);
    TPointD p1  = hook->getBPos(fid);
    bool linked = p0 == p1;
    if (i == pivotIndex) {
      p0 += m_pivotOffset;
      p1 += m_pivotOffset;
    }
    TPixel32 balloonColor(200, 220, 205, 200);
    TPoint balloonOffset(20, 20);
    std::string hookName = std::to_string(i + 1);
    drawBalloon(p0, hookName, balloonColor, balloonOffset, getPixelSize(),
                false, &balloons);
    if (!linked)
      drawBalloon(p1, hookName, balloonColor, balloonOffset, getPixelSize(),
                  false, &balloons);
  }
  // draw snapped hook balloon
  if (m_snappedReason != "") {
    TPointD pos = m_snappedPos;
    TRectD bbox = m_shapeBBox;
    if (bbox.getLx() > 0 && bbox.getLy() > 0) {
      glColor3d(v200, v200, v200);
      glEnable(GL_LINE_STIPPLE);
      glLineStipple(5, 0xAAAA);
      tglDrawRect(bbox);
      glDisable(GL_LINE_STIPPLE);
      glBegin(GL_LINES);
      glVertex2d(pos.x, bbox.y0);
      glVertex2d(pos.x, bbox.y1);
      glVertex2d(bbox.x0, pos.y);
      glVertex2d(bbox.x1, pos.y);
      glEnd();
      glDisable(GL_LINE_STIPPLE);
    }
    drawBalloon(pos, m_snappedReason, TPixel32(200, 250, 180, 200),
                TPoint(20, 20), getPixelSize(), false, &balloons);
  }
}
References OnionSkinMask::getAll(), TXsheet::getCell(), TTool::getCurrentFid(), TTool::getFrame(), TXshCell::getFrameId(), TTool::getImage(), TTool::getXsheet(), TXshSimpleLevel::guessIndex(), TXshSimpleLevel::index2fid(), and TRectT< T >::x0.
drawHooks()
void HookTool::drawHooks (HookSet * hookSet, const TFrameId & fid, bool isOnion)
{
  int pivotIndex = getPivotIndex();
  int i;
  for (i = 0; i < hookSet->getHookCount(); i++) {
    Hook *hook = hookSet->getHook(i);
    if (!hook || hook->isEmpty()) continue;
    assert(hook);
    TPointD p0 = hook->getAPos(fid);
    TPointD p1 = hook->getBPos(fid);
    if (pivotIndex == i) {
      // translating the pivot doesn't change its actual position, but just the
      // m_pivotOffset
      // the actual pivot position is changed in the mouseUp event
      p0 += m_pivotOffset;
      p1 += m_pivotOffset;
    }
    bool linked = p0 == p1;
    drawHook(p0, linked ? NormalHook : PassHookA, m_selection.isSelected(i, 1),
             isOnion);
    if (!linked) drawHook(p1, PassHookB, m_selection.isSelected(i, 2), isOnion);
  }
}
getCursorId()
int HookTool::getCursorId () const inline override virtual
Returns the type of cursor used by the tool.
See also
For a list of cursor ids cursor.h
Reimplemented from TTool.
{ return ToolCursor::MoveCursor; }
getHookSet()
HookSet * HookTool::getHookSet () const
{
  TXshLevel *xl = TTool::getApplication()->getCurrentLevel()->getLevel();
  if (!xl) return 0;
  return xl->getHookSet();
}
getPivotIndex()
int HookTool::getPivotIndex () inline
                      {
    if (!isEditingScene())
      return -1;  // a pivot can be defined only when editing a scene
    std::string handle =
        getXsheet()->getStageObject(getObjectId())->getHandle();
    if (handle.find("H") != 0) return -1;
    return std::stoi(handle.substr(1)) - 1;
  }
getProperties()
TPropertyGroup * HookTool::getProperties (int targetType) inline override virtual
Reimplemented from TTool.
{ return &m_prop; }
getToolType()
ToolType HookTool::getToolType () const inline override virtual
Implements TTool.
{ return TTool::LevelReadTool; }
isEditingScene()
bool HookTool::isEditingScene () const inline
{
    return getApplication()->getCurrentFrame()->isEditingScene();
  }
isSnappedActive()
bool HookTool::isSnappedActive () const inline
{ return m_snappedActive.getValue(); }
leftButtonDown()
void HookTool::leftButtonDown (const TPointD & pos, const TMouseEvent & e) override virtual
Reimplemented from TTool.
{
  TTool::Application *app = TTool::getApplication();
  if (!app) return;
  m_buttonDown = true;
  m_snapped    = false;
  TXshLevel *xl                          = app->getCurrentLevel()->getLevel();
  if (xl && xl->getSimpleLevel()) m_undo = new HookUndo(xl->getSimpleLevel());
  m_selection.setLevel(xl);
  m_firstPos = m_lastPos = pos;
  m_hookId = -1, m_hookSide = 0;
  m_deselectArmed = false;
  if (pick(m_hookId, m_hookSide, pos)) {
    if (m_hookSide == 3)  // ho cliccato su un cerchio-croce
    {
      if (e.isAltPressed())  // con l'alt voglio dividere
      {
        m_selection.selectNone();
        m_selection.select(m_hookId, 2);
      } else if (e.isCtrlPressed()) {
        // se sono tutti e due selezionati li deseleziono
        if (m_selection.isSelected(m_hookId, 1) &&
            m_selection.isSelected(m_hookId, 2)) {
          m_selection.unselect(m_hookId, 1);
          m_selection.unselect(m_hookId, 2);
        } else  // altrimenti li seleziono tutti e due
        {
          m_selection.select(m_hookId, 1);
          m_selection.select(m_hookId, 2);
        }
      } else {
        // senza control ne' shift ne' alt: se ho cliccato su un hook non
        // selezionato
        // deseleziono tutti gli altri e lo seleziono, altrimenti lascio tutto
        // com'e' e al buttonup se non c'e' stato movimento deseleziono gli
        // altri
        if (m_selection.isSelected(m_hookId, 1) ||
            m_selection.isSelected(m_hookId, 2))
          m_deselectArmed = true;
        else {
          m_selection.selectNone();
          m_selection.select(m_hookId, 1);
          m_selection.select(m_hookId, 2);
        }
      }
    } else  // ho cliccato o su un cerchio o su una croce
    {
      if (e.isCtrlPressed())
        m_selection.invertSelection(m_hookId, m_hookSide);
      else {
        m_selection.selectNone();
        m_selection.select(m_hookId, m_hookSide);
      }
    }
  } else {
    // non ho cliccato su nulla: con ctrl non faccio nulla, senza creo un nuovo
    // hook
    if (!e.isCtrlPressed()) {
      m_selection.selectNone();
      TFrameId fid     = getCurrentFid();
      HookSet *hookSet = getHookSet();
      if (hookSet && xl->getSimpleLevel() &&
          !xl->getSimpleLevel()->isReadOnly()) {
        Hook *hook       = hookSet->addHook();
        m_hookSetChanged = true;
        if (hook) {
          TPointD ppos(pos);
          if (m_snappedReason != "") {
            m_snapped = true;
            ppos      = m_snappedPos;
          }
          m_snappedReason = "";
          hook->setAPos(fid, ppos);
          ppos = hook->getAPos(fid);
          m_selection.select(hook->getId(), 1);
          m_selection.select(hook->getId(), 2);
        }
      }
    }
  }
  m_pivotOffset = TPointD();
  m_selection.makeCurrent();
  invalidate();
}
leftButtonDrag()
void HookTool::leftButtonDrag (const TPointD & pos, const TMouseEvent & e) override virtual
Reimplemented from TTool.
{
  TTool::Application *app = TTool::getApplication();
  if (!app) return;
  if (m_snapped) return;
  TFrameId fid = getCurrentFid();
  // cerco di capire se sto muovendo un unico hook "unito"
  TPointD hookPos;
  HookSet *hookSet = getHookSet();
  if (!hookSet) return;
  bool draggingPivot = false;
  int pivotIndex     = getPivotIndex();
  int i, count = 0;
  for (i = 0; i < hookSet->getHookCount(); i++) {
    Hook *hook = hookSet->getHook(i);
    if (!hook || hook->isEmpty()) continue;
    TPointD aPos = hook->getAPos(fid);
    TPointD bPos = hook->getBPos(fid);
    if (m_selection.isSelected(i, 1) && m_selection.isSelected(i, 2) &&
        aPos == bPos) {
      count++;
      hookPos = aPos;
    } else if (m_selection.isSelected(i, 1) || m_selection.isSelected(i, 2)) {
      count = 0;
      break;
    }
    if (i == pivotIndex && m_selection.isSelected(i, 1)) draggingPivot = true;
  }
  TPointD pos(pp);
  TPointD delta = pos - m_lastPos;
  if (e.isShiftPressed()) {
    // se e' pigiato lo shift non snappa e si muove solo in
    // orizzontale/verticale
    TPointD d = pos - m_firstPos;
    if (d.x * d.x > d.y * d.y)
      pos.y = m_firstPos.y;
    else
      pos.x = m_firstPos.x;
    delta   = pos - m_lastPos;
  } else if (count == 1 && isSnappedActive() && !draggingPivot) {
    // snappa
    TPointD oldHookPos = hookPos;
    hookPos += pos - m_lastPos;
    double range2 = getPixelSize() * 20;
    range2 *= range2;
    m_snappedReason = "";
    m_shapeBBox     = TRectD();
    if (snap(hookPos, range2)) {
      delta = hookPos - oldHookPos;
      pos   = delta + m_lastPos;
    }
  } else if (count > 1 && isSnappedActive() && !draggingPivot) {
    TPointD oldHookPos = hookPos;
    // delta = pos - m_lastPos;
    TPointD snappedDelta = delta;
    double range2        = getPixelSize() * 20;
    range2 *= range2;
    m_snappedReason = "";
    m_shapeBBox     = TRectD();
    for (i = 0; i < hookSet->getHookCount(); i++) {
      Hook *hook = hookSet->getHook(i);
      if (hook && !hook->isEmpty()) {
        if (m_selection.isSelected(i, 1)) {
          TPointD p0 = hook->getAPos(fid);
          TPointD p1 = p0 + delta;
          if (snap(p1, range2)) snappedDelta = p1 - p0;
        }
        if (m_selection.isSelected(i, 1)) {
          TPointD p0 = hook->getBPos(fid);
          TPointD p1 = p0 + delta;
          if (snap(p1, range2)) snappedDelta = p1 - p0;
        }
      }
    }
    pos   = m_lastPos + snappedDelta;
    delta = snappedDelta;
  }
  m_lastPos = pos;
  TXsheet *xsh = getXsheet();
  //  std::string handle =
  //  getXsheet()->getStageObject(TStageObjectId::ColumnId())->getHandle();
  // actual movement
  for (i = 0; i < hookSet->getHookCount(); i++) {
    Hook *hook = hookSet->getHook(i);
    if (!hook || hook->isEmpty()) continue;
    TPointD aPos   = hook->getAPos(fid);
    TPointD bPos   = hook->getBPos(fid);
    bool aSelected = m_selection.isSelected(i, 1);
    bool bSelected = m_selection.isSelected(i, 2);
    if (pivotIndex == i) {
      if (aSelected) {
        m_pivotOffset += delta;
        if (!bSelected) hook->setBPos(fid, bPos - delta);
      } else if (bSelected)
        hook->setBPos(fid, bPos + delta);
    } else {
      if (aSelected) hook->setAPos(fid, aPos + delta);
      if (bSelected) hook->setBPos(fid, bPos + delta);
    }
    m_hookSetChanged = true;
  }
  getXsheet()->getStageObjectTree()->invalidateAll();
  invalidate();
}
leftButtonUp()
void HookTool::leftButtonUp (const TPointD & pos, const TMouseEvent &) override virtual
Reimplemented from TTool.
{
  TTool::Application *app = TTool::getApplication();
  if (!app) return;
  // note: apparently sometimes (when the user triple-clicks) we receive this
  // event twice
  if (!m_buttonDown) return;
  m_buttonDown = false;
  // if I've moved the pivot hook I have to perform the actual movement in the
  // mouse up event
  int pivotIndex = getPivotIndex();
  if (m_selection.isSelected(pivotIndex, 1) && m_pivotOffset != TPointD()) {
    HookSet *hookSet = getHookSet();
    if (hookSet) {
      Hook *hook = hookSet->getHook(pivotIndex);
      if (hook && !hook->isEmpty()) {
        TFrameId fid = getCurrentFid();
        TPointD aPos = hook->getAPos(fid);
        TPointD bPos = hook->getBPos(fid);
        hook->setAPos(fid, aPos + m_pivotOffset);
        hook->setBPos(fid, bPos + m_pivotOffset);
        getXsheet()->getStageObjectTree()->invalidateAll();
        updateMatrix();
      }
    }
  }
  m_snapped = false;
  // m_selection.selectNone();
  TXshLevel *xl = app->getCurrentLevel()->getLevel();
  if (!xl || !xl->getSimpleLevel()) return;
  xl->getSimpleLevel()->getProperties()->setDirtyFlag(true);
  TPointD delta = m_lastPos - m_firstPos;
  if (m_deselectArmed && norm2(delta) < 10) {
    m_selection.selectNone();
    m_selection.unselect(m_hookId, 1);
    m_selection.unselect(m_hookId, 2);
  }
  m_deselectArmed = false;
  if (m_undo && m_hookSetChanged)
    TUndoManager::manager()->add(m_undo);
  else {
    delete m_undo;
    m_undo = 0;
  }
  m_hookSetChanged = false;
  m_pivotOffset    = TPointD();
}
mouseMove()
void HookTool::mouseMove (const TPointD & pos, const TMouseEvent & e) override virtual
Reimplemented from TTool.
{
  std::string oldReason = m_snappedReason;
  TPointD oldPos        = m_snappedPos;
  m_snappedPos    = TPointD();
  m_snappedReason = "";
  m_shapeBBox     = TRectD();
  m_otherHooks.clear();
  getOtherHooks(m_otherHooks);
  int hookId, side;
  if (pick(hookId, side, pos)) {
    if (oldReason != "") invalidate();
    return;
  }
  if (isSnappedActive()) {
    double range2 = getPixelSize() * 20.0;
    range2 *= range2;
    TPointD snappedPos = pos;
    snap(snappedPos, range2);
  }
  if (m_snappedReason != oldReason || m_snappedPos != oldPos) invalidate();
}
onActivate()
void HookTool::onActivate () override virtual
Callback invoked whenever the tool activates.
Reimplemented from TTool.
{
  // TODO: getApplication()->editImageOrSpline();
  m_otherHooks.clear();
  getOtherHooks(m_otherHooks);
  m_selection.makeCurrent();
}
onDeactivate()
void HookTool::onDeactivate () override virtual
Callback for tool deactivation, includes tool switch.
Reimplemented from TTool.
{
  m_selection.selectNone();
  TSelection::setCurrent(0);
}
onEnter()
void HookTool::onEnter () override virtual
Callback for the mouse entering the viewer area.
Reimplemented from TTool.
{ m_selection.makeCurrent(); }
onImageChanged()
void HookTool::onImageChanged () inline override virtual
Notifies changes in the image in use.
Reimplemented from TTool.
{
    m_selection.selectNone();
    m_hookId = -1;
    m_otherHooks.clear();
    getOtherHooks(m_otherHooks);
    invalidate();
  }
References TTool::invalidate().
onSelectionChanged()
void HookTool::onSelectionChanged () inline
{ invalidate(); }
pick()
bool HookTool::pick (int & hookId, int & side, const TPointD & pos)
{
  HookSet *hookSet = getHookSet();
  if (!hookSet) return false;
  TFrameId fid    = getCurrentFid();
  double minDist2 = 1e8;
  for (int i = 0; i < hookSet->getHookCount(); i++) {
    Hook *hook = hookSet->getHook(i);
    if (!hook || hook->isEmpty()) continue;
    TPointD aPos = hook->getAPos(fid);
    TPointD bPos = hook->getBPos(fid);
    bool linked  = aPos == bPos;
    if (linked) {
      double dist2 = tdistance2(pos, aPos);
      if (dist2 < minDist2) {
        minDist2 = dist2;
        hookId   = hook->getId();
        side     = 3;
      }
    } else {
      double aDist2 = tdistance2(pos, aPos);
      double bDist2 = tdistance2(pos, bPos);
      double dist2  = aDist2;
      int s         = 1;
      if (bDist2 < dist2) {
        dist2 = bDist2;
        s     = 2;
      }
      if (dist2 < minDist2) {
        minDist2 = dist2;
        hookId   = hook->getId();
        side     = s;
      }
    }
  }
  double pixelSize = getPixelSize();
  return minDist2 < 100 * pixelSize * pixelSize;
}
select()
bool HookTool::select (const TSelection *) inline
{ return false; }
snap()
bool HookTool::snap (TPointD & pos, double & range2)
{
  bool ret               = false;
  TPointD snappedPos     = pos;
  TVectorImageP vi       = TImageP(getImage(false));
  TStroke *selectedShape = 0;
  TRectD selectedShapeBBox;
  double selectedShapeBBoxArea = 0;
  int i, n;
  n = vi ? (int)vi->getStrokeCount() : 0;
  for (i = 0; i < n; i++) {
    TStroke *stroke = vi->getStroke(i);
    if (!stroke->isSelfLoop()) continue;
    TRectD bbox          = stroke->getBBox();
    TPointD strokeCenter = 0.5 * (bbox.getP00() + bbox.getP11());
    if (bbox.contains(pos)) {
      double dist2 = norm2(pos - strokeCenter);
      if (dist2 < range2) {
        double bboxArea = bbox.getLx() * bbox.getLy();
        if (selectedShape == 0 || selectedShapeBBoxArea > bboxArea) {
          range2                = dist2;
          selectedShape         = stroke;
          selectedShapeBBox     = bbox;
          selectedShapeBBoxArea = bboxArea;
        }
      }
    }
  }
  if (selectedShape) {
    m_shapeBBox = selectedShapeBBox;
    snappedPos =
        0.5 * (selectedShapeBBox.getP00() + selectedShapeBBox.getP11());
    m_snappedPos    = snappedPos;
    m_snappedReason = "shape center";
    ret             = true;
  }
  int k = -1;
  if (isEditingScene()) {
    for (i = 0; i < (int)m_otherHooks.size(); i++) {
      double dist2 = norm2(pos - m_otherHooks[i].m_hookPos);
      if (dist2 < range2) {
        range2 = dist2;
        k      = i;
      }
    }
  }
  if (k >= 0) {
    m_shapeBBox     = TRectD();
    snappedPos      = m_otherHooks[k].m_hookPos;
    m_snappedPos    = snappedPos;
    m_snappedReason = "Col" +
                      std::to_string(m_otherHooks[k].m_columnIndex + 1) + "/" +
                      std::to_string(m_otherHooks[k].m_hookIndex + 1);
    ret = true;
  }
  pos = snappedPos;
  return ret;
}
updateMatrix()
void HookTool::updateMatrix () inline override virtual
Updates the current matrix transformation with the actual column matrix transformation.
See also
getCurrentColumnMatrix().
Reimplemented from TTool.
{
    TTool::updateMatrix();
    m_otherHooks.clear();
    getOtherHooks(m_otherHooks);
  }
References TTool::updateMatrix().
updateTranslation()
void HookTool::updateTranslation () override virtual
Reimplemented from TTool.
{
  m_snappedActive.setQStringName(tr("Snap"));
}
The documentation for this class was generated from the following file:
E:/opentoonz/toonz/sources/tnztools/hooktool.cpp