opentoonz: LoadLevelPopup Class Reference
LoadLevelPopup Class Reference final
Public Member Functions
bool execute () override
void initFolder () override
Public Member Functions inherited from FileBrowserPopup
FileBrowserPopup (const QString &windowTitle, Options options=STANDARD, QString applyButtonTxt="", QWidget *customWidget=0)
void setOkText (const QString &text)
void setFilterTypes (const QStringList &typesList)
void removeFilterType (const QString &type)
void addFilterType (const QString &type)
void setFileMode (bool isDirectoryOnly)
void setFolder (const TFilePath &folderPath)
void setFilename (const TFilePath &filename)
virtual void initFolder ()
FileBrowserPopup (TWidget *parent)
FileBrowserPopup (TWidget *parent, const vector< string > &fileTypes)
void configureNotify (const TDimension &d)
TDimension getPreferredSize () const
void draw ()
void setCurrentDir (const TFilePath &dirPath)
void setFilter (const vector< string > &fileTypes)
void setOkAction (TGenericFileBrowserPopupAction *action)
void popup (const TPoint &p)
Public Member Functions inherited from TPopup
TPopup (TWidget *parent, std::string name, bool hasCaption=true, bool isResizable=true, bool isTopMost=false)
virtual void openPopup ()
virtual void openPopup (const TPoint &pos)
virtual void openPopup (const TDimension &size)
virtual void closePopup ()
virtual void setGeometry (const TRect &rect)
bool onNcPaint (bool is_active, const TDimension &window_size, const TRect &caption_rect)
virtual bool onClose ()
virtual void onOpen ()
bool isOpen ()
bool isMenu () const
bool hasCaption () const
bool isResizable () const
bool isTopMost () const
void setCaption (const std::string &name)
void setCaption (const std::wstring &name)
std::wstring getCaption () const
virtual TDimension getPreferredSize () const
virtual TDimension getMinimumSize () const
virtual TDimension getMaximumSize () const
Public Member Functions inherited from TWidget
TWidget (TWidget *parent=0, std::string name="unnamed")
const TRect & getGeometry () const
TPoint getPosition () const
virtual TPoint getHotSpot () const
TDimension getSize () const
TRect getBounds () const
int getLx () const
int getLy () const
void setPlacement (const TRect &rect)
void setGeometry (int x0, int y0, int x1, int y1)
virtual void setGeometry (const TRect &rect)
void setGeometry (const TPoint &pos, const TDimension &size)
void setSize (int w, int h)
void setSize (const TDimension &size)
void setPosition (int x, int y)
void setPosition (const TPoint &pt)
bool contains (int x, int y) const
bool contains (const TPoint &p) const
TPoint getScreenPosition () const
TWidget * getParent () const
std::string getName () const
virtual void setParent (TWidget *p)
virtual void addSon (TWidget *son)
virtual void removeSon (TWidget *son)
int getSonCount () const
TWidget * getSon (int i) const
std::wstring getLongHelp () const
std::wstring getShortHelp () const
void setHelp (std::string shortHelp, std::string longHelp)
void setHelp (std::wstring shortHelp, std::wstring longHelp)
virtual std::string getContextHelpReference (const TPoint &)
void setContextHelpReference (std::string s)
virtual std::wstring getTooltipString (const TPoint &)
bool isHidden () const
bool isMapped () const
void enable ()
void disable ()
bool isEnabled () const
void show ()
void hide ()
virtual void map ()
virtual void unmap ()
virtual void doModal ()
virtual void undock ()
virtual void dock (TWidget *parent)
virtual TWidget * findSubWidget (const TPoint &pt)
virtual void repaint ()
void sendRepaint ()
void sendRepaint (const TRect &)
virtual void paste ()
virtual void startDragAndDrop (std::string stringToDrop)
CursorIndex getCurrentCursor ()
void changeCursor (CursorIndex new_cur)
TWidgetImp * getImp ()
void startTimer (TINT32 period)
void stopTimer ()
virtual void getSelection ()
virtual void onFocusChange (bool on)
virtual bool getFocus ()
virtual void circulateFocus ()
virtual void copyRegion (const TPoint &dst, const TPoint &src, const TDimension &size)
void flush ()
virtual void draw ()
virtual void invalidate ()
virtual void invalidate (const TRect &rect)
void getClipRect (TRect &rect)
virtual void clear ()
virtual void drawText (const TPoint &p, std::string text)
virtual void drawText (const TPoint &p, std::wstring text)
virtual void drawText (const TRect &r, std::string text, Alignment alignment=CENTER)
virtual void drawText (const TRect &r, std::wstring text, Alignment alignment=CENTER)
virtual void drawMultiLineText (const TRect &r, std::string text)
virtual void drawMultiLineText (const TRect &r, std::wstring text)
virtual TDimension getTextSize (std::string text)
virtual TDimension getTextSize (std::wstring text)
virtual TDimension getTextSize (std::string text, std::string font, int fontSize)
virtual TDimension getTextSize (std::wstring text, std::string font, int fontSize)
void drawPoint (int x, int y)
virtual void drawLine (const TPoint &p0, const TPoint &p1)
void drawLine (int x0, int y0, int x1, int y1)
virtual void drawVLine (const TPoint &p0, int length)
virtual void drawHLine (const TPoint &p0, int length)
virtual void drawDottedLine (const TPoint &p0, const TPoint &p1)
void drawDottedLine (int x0, int y0, int x1, int y1)
virtual void drawRect (const TRect &)
virtual void fillRect (const TRect &)
virtual void drawRect (int x0, int y0, int x1, int y1)
virtual void fillRect (int x0, int y0, int x1, int y1)
virtual void draw3DRect (const TRect &, bool pressed=false, int border=1)
virtual void fill3DRect (const TRect &, bool pressed=false, int border=1)
virtual void drawDottedRect (const TRect &)
virtual void drawDottedRect (int x0, int y0, int x1, int y1)
virtual void fillPolygon (const TGuiColor &fillColor, const TGuiColor &borderColor, const TPoint points[], int pointCount)
virtual void clear (const TRect &)
virtual void drawImage (int index, const TPoint &)
virtual void setColor (const TGuiColor &, int shade=0)
virtual void setBackgroundColor (const TGuiColor &)
TGuiColor getBackgroundColor () const
TGuiColor getForegroundColor () const
virtual void rectwrite (const TRaster32P &, const TPoint &)
virtual void setFontSize (int size)
virtual void setFont (std::string name, int size=0, int orientation=0)
virtual void enter (const TPoint &)
virtual void leave (const TPoint &)
virtual void mouseMove (const TMouseEvent &)
virtual void leftButtonDown (const TMouseEvent &)
virtual void leftButtonDrag (const TMouseEvent &)
virtual void leftButtonUp (const TMouseEvent &)
virtual void rightButtonDown (const TMouseEvent &)
virtual void rightButtonDrag (const TMouseEvent &)
virtual void rightButtonUp (const TMouseEvent &)
virtual void middleButtonDown (const TMouseEvent &)
virtual void middleButtonDrag (const TMouseEvent &)
virtual void middleButtonUp (const TMouseEvent &)
virtual void leftButtonDoubleClick (const TMouseEvent &)
virtual void middleButtonDoubleClick (const TMouseEvent &)
virtual void rightButtonDoubleClick (const TMouseEvent &)
virtual void mouseWheel (const TMouseEvent &, int wheel)
virtual void keyDown (int, TUINT32, const TPoint &)
virtual void configureNotify (const TDimension &)
virtual void onPaste (std::string)
virtual void onDrop (std::string)
virtual std::string getToolTip ()
virtual void onTimer (int)
virtual void onChildrenChanged ()
virtual bool onNcPaint (bool is_active, const TDimension &window_size, const TRect &caption_rect)
virtual FocusHandling getFocusHandling () const
virtual void maximize (TWidget *)
virtual bool isMaximized (TWidget *)
void enableDropTarget (TDragDropListener *dragDropListener)
TDragDropListener * getDragDropListener () const
TPoint getAbsolutePosition () const
TPoint getMouseRelativePosition () const
bool isMenuRelated () const
Protected Slots
void onFilePathsSelected (const std::set< TFilePath > &paths, const std::list< std::vector< TFrameId > > &fIds) override
void onFrameSwitched ()
void onSubsequentFrameChanged ()
void updatePosTo ()
void onNameSetEditted (void)
void onSelectionChanged (TSelection *selection)
void onFilePathDoubleClicked (const TFilePath &path) override
void onPreferenceChanged (const QString &)
void onDpiPolicyActivated ()
void onDoPremultiplyClicked ()
void onWhiteTranspClicked ()
Protected Slots inherited from FileBrowserPopup
void onFilePathClicked (const TFilePath &)
virtual void onFilePathsSelected (const std::set< TFilePath > &paths, const std::list< std::vector< TFrameId > > &fIds)
virtual void onFilePathDoubleClicked (const TFilePath &)
Protected Member Functions
void showEvent (QShowEvent *) override
void hideEvent (QHideEvent *) override
Protected Member Functions inherited from FileBrowserPopup
TFilePath getCurrentPath ()
std::set< TFilePath > & getCurrentPathSet ()
std::vector< TFrameId > getCurrentFIds ()
std::list< std::vector< TFrameId > > & getCurrentFIdsSet ()
virtual bool execute ()=0
virtual bool executeApply ()
void showEvent (QShowEvent *) override
void hideEvent (QHideEvent *) override
Protected Member Functions inherited from TPopup
virtual void create ()
Protected Member Functions inherited from TWidget
virtual void create ()
virtual void setDecoration ()
virtual void destroyImp ()
void createSons ()
Additional Inherited Members
Public Types inherited from FileBrowserPopup
enum Options {
STANDARD = 0x0 , CUSTOM_LAYOUT = 0x1 , MULTISELECTION = 0x2 , WITH_APPLY_BUTTON = 0x4 ,
FOR_SAVING = 0x8
}
Various options used to customize the popup's behavior.
Public Types inherited from TWidget
enum Alignment { BEGIN , CENTER , END }
enum FocusHandling { IGNORE_FOCUS , STOP_FOCUS , LISTEN_TO_FOCUS }
typedef unsigned int CursorIndex
Public Slots inherited from FileBrowserPopup
void onOkPressed ()
void onApplyPressed ()
Signals inherited from FileBrowserPopup
void filePathClicked (const TFilePath &)
Static Public Member Functions inherited from FileBrowserPopup
static void setModalBrowserToParent (QWidget *widget)
Static Public Member Functions inherited from TWidget
static void setFocusOwner (TWidget *w)
static TWidget * getFocusOwner ()
static void placeInteractively (TRect &)
static void yield ()
static void setMode (int mode)
static TPoint getMouseAbsolutePosition ()
static void processAllPendingMessages ()
static void processAllPendingMessages2 ()
static TDimension getScreenSize ()
static void getScreenPlacement (std::vector< TRectI > &)
Static Public Attributes inherited from TWidget
static const TGuiColor White
static const TGuiColor Black
Protected Attributes inherited from FileBrowserPopup
std::set< TFilePath > m_selectedPaths
Paths in the active selection.
TFilePath m_currentProjectPath
std::list< std::vector< TFrameId > > m_currentFIdsSet
FileBrowser * m_browser
QLabel * m_nameFieldLabel
DVGui::LineEdit * m_nameField
QPushButton * m_okButton
QPushButton * m_cancelButton
bool m_isDirectoryOnly
bool m_multiSelectionEnabled
bool m_forSaving
QSize m_dialogSize
QWidget * m_customWidget
Protected Attributes inherited from TPopup
bool m_isOpen
bool m_isMenu
bool m_hasCaption
bool m_isResizable
bool m_isTopMost
std::wstring m_caption
Protected Attributes inherited from TWidget
TRect m_placement
int m_xoff
int m_yoff
bool m_mapped
bool m_hidden
bool m_childrenChanged
TWidget * m_parent
TWidget * m_sonKeeper
std::string m_name
std::string m_contextHelpReference
std::wstring m_shortHelp
std::wstring m_longHelp
int m_cursorIdx
TWidgetList * m_sons
TWidgetImp * m_imp
TGuiColor m_backgroundColor
TGuiColor m_foregroundColor
bool m_popupMode
bool m_menuMode
bool m_fixedSize
bool m_fullColor
bool m_openGL
bool m_enabled
bool m_menuRelated
TDragDropListener * m_dragDropListener
std::string m_fontName
int m_fontSize
int m_fontOrientation
Static Protected Attributes inherited from TWidget
static TWidget * m_selectionOwner
static TWidget * m_focusOwner
Detailed Description
Constructor & Destructor Documentation
LoadLevelPopup()
LoadLevelPopup::LoadLevelPopup ()
    : FileBrowserPopup(tr("Load Level"),
                       Options(MULTISELECTION | WITH_APPLY_BUTTON), "",
                       new QWidget(0)) {
  setModal(false);
  setOkText(tr("Load"));
  QWidget *optionWidget = (QWidget *)m_customWidget;
  // choose tlv caching behavior
  QLabel *cacheBehaviorLabel = new QLabel(tr("TLV Caching Behavior"), this);
  m_loadTlvBehaviorComboBox  = new QComboBox(this);
  //----Load Subsequence Level
  QPushButton *showSubsequenceButton = createShowButton(this);
  QLabel *subsequenceLabel = new QLabel(tr("Load Subsequence Level"), this);
  m_subsequenceFrame       = new QFrame(this);
  m_fromFrame              = new FrameNumberLineEdit(this, TFrameId(1));
  m_toFrame                = new FrameNumberLineEdit(this, TFrameId(1));
  //----Arrangement in Xsheet
  m_arrLvlPropWidget                 = new QWidget(this);
  QPushButton *showArrangementButton = createShowButton(this);
  QLabel *arrangementLabel =
      new QLabel(tr("Level Settings & Arrangement in Xsheet"), this);
  m_arrangementFrame = new QFrame(this);
  m_xFrom            = new FrameNumberLineEdit(this, TFrameId(1));
  m_xTo              = new FrameNumberLineEdit(this, TFrameId(1));
  m_stepCombo        = new QComboBox(this);
  m_incCombo         = new QComboBox(this);
  m_posFrom          = new DVGui::IntLineEdit(this, 1, 1);
  m_posTo            = new DVGui::IntLineEdit(this, 1, 1);
  //----Level Properties
  m_levelPropertiesFrame = new QFrame(this);
  m_levelName            = new DVGui::LineEdit(this);
  m_dpiWidget            = new QWidget(this);
  m_dpiPolicy            = new QComboBox(this);
  m_dpi                  = new DVGui::DoubleLineEdit(this);
  m_subsampling          = new DVGui::IntLineEdit(this, 1, 1);
  m_antialias            = new DVGui::IntLineEdit(this, 10, 0, 100);
  m_premultiply          = new DVGui::CheckBox(tr("Premultiply"), this);
  m_whiteTransp = new DVGui::CheckBox(tr("White As Transparent"), this);
  m_notExistLabel = new QLabel(tr("(FILE DOES NOT EXIST)"));
  //----
  m_loadTlvBehaviorComboBox->addItem(tr("On Demand"),
                                     IoCmd::LoadResourceArguments::ON_DEMAND);
  m_loadTlvBehaviorComboBox->addItem(tr("All Icons"),
                                     IoCmd::LoadResourceArguments::ALL_ICONS);
  m_loadTlvBehaviorComboBox->addItem(
      tr("All Icons & Images"),
      IoCmd::LoadResourceArguments::ALL_ICONS_AND_IMAGES);
  // use the default value set in the preference
  m_loadTlvBehaviorComboBox->setCurrentIndex(
      m_loadTlvBehaviorComboBox->findData(
          Preferences::instance()->getInitialLoadTlvCachingBehavior()));
  cacheBehaviorLabel->setObjectName("TitleTxtLabel");
  //----Load Subsequence Level
  m_subsequenceFrame->setObjectName("LoadLevelFrame");
  subsequenceLabel->setObjectName("TitleTxtLabel");
  m_subsequenceFrame->hide();
  m_fromFrame->setMaximumWidth(50);
  m_toFrame->setMaximumWidth(50);
  //----Arrangement in Xsheet
  m_arrangementFrame->setObjectName("LoadLevelFrame");
  m_levelPropertiesFrame->setObjectName("LoadLevelFrame");
  arrangementLabel->setObjectName("TitleTxtLabel");
  m_arrLvlPropWidget->hide();
  QStringList sList;
  sList << QString("Auto") << QString("1") << QString("2") << QString("3")
        << QString("4") << QString("5") << QString("6") << QString("7")
        << QString("8");
  m_stepCombo->addItems(sList);
  m_incCombo->addItems(sList);
  //----Level Properties
  m_dpiPolicy->addItem(QObject::tr("Image DPI"), LevelOptions::DP_ImageDpi);
  m_dpiPolicy->addItem(QObject::tr("Custom DPI"), LevelOptions::DP_CustomDpi);
  m_dpi->setRange(1, (std::numeric_limits<double>::max)());
  m_dpi->setFixedWidth(54);
  // initialize with the default value
  LevelOptions options;
  setLevelProperties(options);
  //"FILE DOES NOT EXIST" label
  m_notExistLabel->setObjectName("FileDoesNotExistLabel");
  m_notExistLabel->hide();
  //----layout
  auto createVBoxLayout = [](int margin, int spacing) {
    QVBoxLayout *layout = new QVBoxLayout();
    layout->setMargin(margin);
    layout->setSpacing(spacing);
    return layout;
  };
  auto createHBoxLayout = [](int margin, int spacing) {
    QHBoxLayout *layout = new QHBoxLayout();
    layout->setMargin(margin);
    layout->setSpacing(spacing);
    return layout;
  };
  QVBoxLayout *mainLayout = createVBoxLayout(5, 3);
  {
    QHBoxLayout *cacheLay = createHBoxLayout(0, 5);
    {
      cacheLay->addStretch(1);
      cacheLay->addWidget(cacheBehaviorLabel, 0);
      cacheLay->addWidget(m_loadTlvBehaviorComboBox, 0);
    }
    mainLayout->addLayout(cacheLay, 0);
    //----Load Subsequence Level
    QHBoxLayout *subsequenceHeadLay = createHBoxLayout(0, 5);
    {
      QFontMetrics metrics(font());
      subsequenceHeadLay->addSpacing(metrics.width("File name:") + 3);
      subsequenceHeadLay->addWidget(m_notExistLabel, 0);
      subsequenceHeadLay->addStretch(1);
      subsequenceHeadLay->addWidget(subsequenceLabel, 0);
      subsequenceHeadLay->addWidget(showSubsequenceButton, 0);
    }
    mainLayout->addLayout(subsequenceHeadLay, 0);
    QHBoxLayout *subsequenceLay = createHBoxLayout(5, 5);
    {
      subsequenceLay->addWidget(new QLabel(tr("From:"), this), 0);
      subsequenceLay->addWidget(m_fromFrame, 0);
      subsequenceLay->addWidget(new QLabel(tr(" To:"), this), 0);
      subsequenceLay->addWidget(m_toFrame, 0);
    }
    m_subsequenceFrame->setLayout(subsequenceLay);
    mainLayout->addWidget(m_subsequenceFrame, 0,
                          Qt::AlignRight | Qt::AlignVCenter);
    //----Arrangement in Xsheet
    QHBoxLayout *arrangementHeadLay = createHBoxLayout(0, 3);
    {
      arrangementHeadLay->addWidget(arrangementLabel, 1,
                                    Qt::AlignRight | Qt::AlignVCenter);
      arrangementHeadLay->addWidget(showArrangementButton, 0);
    }
    mainLayout->addLayout(arrangementHeadLay);
    QHBoxLayout *bottomLay = createHBoxLayout(0, 10);
    {
      QGridLayout *levelLay = new QGridLayout();
      levelLay->setMargin(5);
      levelLay->setSpacing(5);
      {
        levelLay->addWidget(new QLabel(tr("Level Name:"), this), 0, 0,
                            Qt::AlignRight | Qt::AlignVCenter);
        levelLay->addWidget(m_levelName, 0, 1);
        QHBoxLayout *dpiLay = createHBoxLayout(0, 5);
        {
          dpiLay->addSpacing(10);
          dpiLay->addWidget(new QLabel(tr("DPI:"), this), 0,
                            Qt::AlignRight | Qt::AlignVCenter);
          dpiLay->addWidget(m_dpiPolicy, 0);
          dpiLay->addWidget(m_dpi, 1);
        }
        m_dpiWidget->setLayout(dpiLay);
        levelLay->addWidget(m_dpiWidget, 0, 2, 1, 3);
        levelLay->addWidget(m_premultiply, 1, 0, 1, 2);
        levelLay->addWidget(m_whiteTransp, 2, 0, 1, 2);
        // levelLay->addWidget(m_doAntialias, 1, 3, 1, 2);
        levelLay->addWidget(new QLabel(tr("Antialias Softness:"), this), 1, 2,
                            1, 2, Qt::AlignRight | Qt::AlignVCenter);
        levelLay->addWidget(m_antialias, 1, 4);
        levelLay->addWidget(new QLabel(tr("Subsampling:"), this), 2, 2, 1, 2,
                            Qt::AlignRight | Qt::AlignVCenter);
        levelLay->addWidget(m_subsampling, 2, 4);
      }
      levelLay->setColumnStretch(1, 1);
      levelLay->setColumnStretch(4, 1);
      m_levelPropertiesFrame->setLayout(levelLay);
      bottomLay->addWidget(m_levelPropertiesFrame, 0);
      QGridLayout *arrLay = new QGridLayout();
      arrLay->setMargin(5);
      arrLay->setSpacing(5);
      {
        arrLay->addWidget(new QLabel(tr("From:"), this), 0, 0,
                          Qt::AlignRight | Qt::AlignVCenter);
        arrLay->addWidget(m_xFrom, 0, 1);
        arrLay->addWidget(new QLabel(tr(" To:"), this), 0, 2,
                          Qt::AlignRight | Qt::AlignVCenter);
        arrLay->addWidget(m_xTo, 0, 3);
        arrLay->addWidget(new QLabel(tr(" Step:"), this), 1, 0,
                          Qt::AlignRight | Qt::AlignVCenter);
        arrLay->addWidget(m_stepCombo, 1, 1);
        arrLay->addWidget(new QLabel(tr(" Inc:"), this), 1, 2,
                          Qt::AlignRight | Qt::AlignVCenter);
        arrLay->addWidget(m_incCombo, 1, 3);
        arrLay->addWidget(new QLabel(tr(" Frames:"), this), 2, 0,
                          Qt::AlignRight | Qt::AlignVCenter);
        arrLay->addWidget(m_posFrom, 2, 1);
        arrLay->addWidget(new QLabel(tr("::"), this), 2, 2, Qt::AlignCenter);
        arrLay->addWidget(m_posTo, 2, 3);
      }
      arrLay->setColumnStretch(1, 1);
      arrLay->setColumnStretch(3, 1);
      m_arrangementFrame->setLayout(arrLay);
      bottomLay->addWidget(m_arrangementFrame, 0);
    }
    m_arrLvlPropWidget->setLayout(bottomLay);
    mainLayout->addWidget(m_arrLvlPropWidget, 0,
                          Qt::AlignRight | Qt::AlignVCenter);
  }
  optionWidget->setLayout(mainLayout);
  //----signal-slot connections
  //----Load Subsequence Level
  connect(showSubsequenceButton, SIGNAL(toggled(bool)), m_subsequenceFrame,
          SLOT(setVisible(bool)));
  connect(m_fromFrame, SIGNAL(editingFinished()),
          SLOT(onSubsequentFrameChanged()));
  connect(m_toFrame, SIGNAL(editingFinished()),
          SLOT(onSubsequentFrameChanged()));
  //----Arrangement in Xsheet
  connect(showArrangementButton, SIGNAL(toggled(bool)), m_arrLvlPropWidget,
          SLOT(setVisible(bool)));
  connect(m_xFrom, SIGNAL(editingFinished()), SLOT(updatePosTo()));
  connect(m_xTo, SIGNAL(editingFinished()), SLOT(updatePosTo()));
  connect(m_posFrom, SIGNAL(editingFinished()), SLOT(updatePosTo()));
  connect(m_stepCombo, SIGNAL(currentIndexChanged(int)), SLOT(updatePosTo()));
  connect(m_incCombo, SIGNAL(currentIndexChanged(int)), SLOT(updatePosTo()));
  connect(m_nameField, SIGNAL(editingFinished()), this,
          SLOT(onNameSetEditted()));
  connect(m_browser, SIGNAL(treeFolderChanged(const TFilePath &)), this,
          SLOT(onNameSetEditted()));
  connect(m_browser, SIGNAL(filePathDoubleClicked(const TFilePath &)), this,
          SLOT(onFilePathDoubleClicked(const TFilePath &)));
  //----Level Properties
  connect(m_dpiPolicy, SIGNAL(activated(int)), this,
          SLOT(onDpiPolicyActivated()));
  connect(m_premultiply, SIGNAL(clicked(bool)), this,
          SLOT(onDoPremultiplyClicked()));
  connect(m_whiteTransp, SIGNAL(clicked(bool)), this,
          SLOT(onWhiteTranspClicked()));
}
Member Function Documentation
execute()
bool LoadLevelPopup::execute () override virtual
Performs some action on m_paths and returns whether the action was successful (accepted) - in which case the popup closes.
Implements FileBrowserPopup.
{
  if (m_selectedPaths.size() == 1) {
    const TFilePath &fp = *m_selectedPaths.begin();
    //---- SubSequent load
    // if loading the "missing" level
    if (m_notExistLabel->isVisible()) {
      TFrameId firstLoadingFId = m_fromFrame->getValue();
      TFrameId lastLoadingFId  = m_toFrame->getValue();
      setLoadingLevelRange(firstLoadingFId, lastLoadingFId);
    } else if (m_subsequenceFrame->isEnabled() &&
               m_subsequenceFrame->isVisible()) {
      std::vector<TFrameId> fIds = getCurrentFIds();
      TFrameId firstFrame;
      TFrameId lastFrame;
      // if the level is sequential and there is a reusable list of TFrameId
      if (fIds.size() != 0) {
        firstFrame = fIds[0];
        lastFrame  = fIds[fIds.size() - 1];
      }
      // another case such as loading tlv
      else {
        try {
          TLevelReaderP lr(fp);
          TLevelP level;
          if (lr) level = lr->loadInfo();
          if (!level.getPointer()) return false;
          firstFrame = level->begin()->first;
          lastFrame  = (--level->end())->first;
          lr         = TLevelReaderP();
        } catch (...) {
          return false;
        }
      }
      TFrameId firstLoadingFId = m_fromFrame->getValue();
      TFrameId lastLoadingFId  = m_toFrame->getValue();
      if (firstFrame != firstLoadingFId || lastFrame != lastLoadingFId)
        setLoadingLevelRange(firstLoadingFId, lastLoadingFId);
    }
    IoCmd::LoadResourceArguments args(fp);
    args.row0 = m_posFrom->text().toInt() - 1;
    args.frameCount = m_posTo->text().toInt() - m_posFrom->text().toInt() + 1;
    if ((int)getCurrentFIdsSet().size() != 0)
      args.frameIdsSet.push_back(*getCurrentFIdsSet().begin());
    else if (m_notExistLabel->isVisible()) {
      TFrameId firstLoadingFId = m_fromFrame->getValue();
      TFrameId lastLoadingFId  = m_toFrame->getValue();
      // putting the Fids in order to avoid LoadInfo later
      std::vector<TFrameId> tmp_fids;
      int i = firstLoadingFId.getNumber();
      if (!firstLoadingFId.getLetter().isEmpty()) {
        tmp_fids.push_back(firstLoadingFId);
        i++;
      }
      for (; i <= lastLoadingFId.getNumber(); i++) {
        tmp_fids.push_back(TFrameId(i));
      }
      if (!lastLoadingFId.getLetter().isEmpty())
        tmp_fids.push_back(lastLoadingFId);
      args.frameIdsSet.push_back(tmp_fids);
    }
    TFrameId xFrom = m_xFrom->getValue();
    if (!xFrom.isEmptyFrame()) args.xFrom = xFrom;
    TFrameId xTo = m_xTo->getValue();
    if (!xTo.isEmptyFrame()) args.xTo = xTo;
    args.levelName             = m_levelName->text().toStdWString();
    args.step                  = m_stepCombo->currentIndex();
    args.inc                   = m_incCombo->currentIndex();
    args.doesFileActuallyExist = !m_notExistLabel->isVisible();
    args.cachingBehavior       = IoCmd::LoadResourceArguments::CacheTlvBehavior(
        m_loadTlvBehaviorComboBox->currentData().toInt());
    if (m_arrLvlPropWidget->isVisible() &&
        m_levelPropertiesFrame->isEnabled()) {
      for (IoCmd::LoadResourceArguments::ResourceData &rd :
           args.resourceDatas) {
        rd.m_options = LevelOptions();
        getLevelProperties(*rd.m_options);
      }
    }
    return 0 < IoCmd::loadResources(args, true, 0);
  } else {
    std::set<TFilePath>::const_iterator it;
    IoCmd::LoadResourceArguments args;
    args.row0 = m_posFrom->text().toInt() - 1;
    for (it = m_selectedPaths.begin(); it != m_selectedPaths.end(); ++it)
      args.resourceDatas.push_back(*it);
    std::list<std::vector<TFrameId>> fIdsSet = getCurrentFIdsSet();
    if (fIdsSet.size() > 0) {
      std::list<std::vector<TFrameId>>::const_iterator fIdIt;
      for (fIdIt = fIdsSet.begin(); fIdIt != fIdsSet.end(); ++fIdIt)
        args.frameIdsSet.insert(args.frameIdsSet.begin(), *fIdIt);
    }
    args.cachingBehavior = IoCmd::LoadResourceArguments::CacheTlvBehavior(
        m_loadTlvBehaviorComboBox->currentData().toInt());
    if (m_arrLvlPropWidget->isVisible() &&
        m_levelPropertiesFrame->isEnabled()) {
      for (IoCmd::LoadResourceArguments::ResourceData &rd :
           args.resourceDatas) {
        rd.m_options = LevelOptions();
        getLevelProperties(*rd.m_options);
      }
    }
    return 0 < IoCmd::loadResources(args, true, 0);
  }
}
References FrameNumberLineEdit::getValue(), IoCmd::loadResources(), IoCmd::LoadResourceArguments::ResourceData::m_options, FileBrowserPopup::m_selectedPaths, IoCmd::LoadResourceArguments::resourceDatas, and IoCmd::LoadResourceArguments::row0.
hideEvent()
void LoadLevelPopup::hideEvent (QHideEvent * e) override protected
{
  FileBrowserPopup::hideEvent(e);
  TFrameHandle *fh = TApp::instance()->getCurrentFrame();
  disconnect(fh, SIGNAL(frameSwitched()), this, SLOT(onFrameSwitched()));
  disconnect(fh, SIGNAL(frameTypeChanged()), this, SLOT(onFrameSwitched()));
  TSelectionHandle *sh = TApp::instance()->getCurrentSelection();
  disconnect(sh, SIGNAL(selectionChanged(TSelection *)), this,
             SLOT(onSelectionChanged(TSelection *)));
  disconnect(TApp::instance()->getCurrentScene(),
             SIGNAL(preferenceChanged(const QString &)), this,
             SLOT(onPreferenceChanged(const QString &)));
}
initFolder()
void LoadLevelPopup::initFolder () override virtual
Reimplemented from FileBrowserPopup.
{
  TFilePath fp;
  TProject *project =
      TProjectManager::instance()->getCurrentProject().getPointer();
  ToonzScene *scene = TApp::instance()->getCurrentScene()->getScene();
  if (scene) fp = scene->decodeFilePath(project->getProjectFolder());
  setFolder(fp);
  onFilePathsSelected(getCurrentPathSet(), getCurrentFIdsSet());
}
onDoPremultiplyClicked
void LoadLevelPopup::onDoPremultiplyClicked () protected slot
{
  if (m_whiteTransp->isChecked()) m_whiteTransp->setChecked(false);
}
onDpiPolicyActivated
void LoadLevelPopup::onDpiPolicyActivated () protected slot
{
  m_dpi->setEnabled(m_dpiPolicy->currentData().toInt() ==
                    LevelOptions::DP_CustomDpi);
}
onFilePathDoubleClicked
void LoadLevelPopup::onFilePathDoubleClicked (const TFilePath & path) override protected slot
{
  Q_UNUSED(path);
  onOkPressed();
}
onFilePathsSelected
void LoadLevelPopup::onFilePathsSelected (const std::set< TFilePath > & paths, const std::list< std::vector< TFrameId > > & fIds) override protected slot
{
  m_notExistLabel->hide();
  FileBrowserPopup::onFilePathsSelected(paths, fIds);
  updateBottomGUI();
}
onFrameSwitched
void LoadLevelPopup::onFrameSwitched () protected slot
{
  TFrameHandle *fh = TApp::instance()->getCurrentFrame();
  if (fh->isEditingLevel())
    m_posFrom->setText("1");
  else
    m_posFrom->setText(QString::number(fh->getFrame() + 1));
  updatePosTo();
}
onNameSetEditted
void LoadLevelPopup::onNameSetEditted (void) protected slot
{
  getCurrentPathSet().clear();
  getCurrentFIdsSet().clear();
  // if nothing input
  if (m_nameField->text() == "") {
    m_notExistLabel->hide();
    updateBottomGUI();
  }
  // if the path exists
  else {
    TFilePath path =
        m_browser->getFolder() + TFilePath(m_nameField->text().toStdString());
    getCurrentPathSet().insert(path);
    if (TSystem::doesExistFileOrLevel(path)) {
      m_notExistLabel->hide();
      updateBottomGUI();
    } else {
      m_notExistLabel->show();
      m_fromFrame->setValue(TFrameId(1));
      m_toFrame->setValue(TFrameId(1));
      m_subsequenceFrame->setEnabled(true);
      m_xFrom->setValue(TFrameId(1));
      m_xTo->setValue(TFrameId(1));
      m_levelName->setText(QString::fromStdString(path.getName()));
      m_arrangementFrame->setEnabled(true);
      m_levelName->setEnabled(true);
      m_levelPropertiesFrame->setEnabled(true);
      updatePosTo();
    }
  }
  update();
}
onPreferenceChanged
void LoadLevelPopup::onPreferenceChanged (const QString & propertyName) protected slot
{
  if (!propertyName.isEmpty() && propertyName != "pixelsOnly") return;
  bool pixelsMode = Preferences::instance()->getBoolValue(pixelsOnly);
  m_dpiWidget->setHidden(pixelsMode);
  if (pixelsMode) {
    m_dpiPolicy->setCurrentIndex(
        m_dpiPolicy->findData(LevelOptions::DP_ImageDpi));
    m_dpi->setValue(Stage::standardDpi);
    m_dpi->setEnabled(false);
  }
}
onSelectionChanged
void LoadLevelPopup::onSelectionChanged (TSelection * selection) protected slot
if the x-sheet cells are selected, load levels at the upper-left corner of the selection
{
  TCellSelection *cellSelection = dynamic_cast<TCellSelection *>(selection);
  if (!cellSelection) return;
  int r0, r1, c0, c1;
  cellSelection->getSelectedCells(r0, c0, r1, c1);
  m_posFrom->setText(QString::number(r0 + 1));
  updatePosTo();
}
onSubsequentFrameChanged
void LoadLevelPopup::onSubsequentFrameChanged () protected slot
if the from / to values in the subsequent box, update m_xFrom and m_xTo
{
  m_xFrom->setValue(m_fromFrame->getValue());
  m_xTo->setValue(m_toFrame->getValue());
  updatePosTo();
}
References FrameNumberLineEdit::getValue(), and FrameNumberLineEdit::setValue().
onWhiteTranspClicked
void LoadLevelPopup::onWhiteTranspClicked () protected slot
{
  if (m_premultiply->isChecked()) m_premultiply->setChecked(false);
}
showEvent()
void LoadLevelPopup::showEvent (QShowEvent * e) override protected
{
  m_nameField->clear();
  FileBrowserPopup::showEvent(e);
  bool ret         = true;
  TFrameHandle *fh = TApp::instance()->getCurrentFrame();
  ret              = ret &&
        connect(fh, SIGNAL(frameSwitched()), this, SLOT(onFrameSwitched()));
  ret = ret &&
        connect(fh, SIGNAL(frameTypeChanged()), this, SLOT(onFrameSwitched()));
  TSelectionHandle *sh = TApp::instance()->getCurrentSelection();
  ret = ret && connect(sh, SIGNAL(selectionChanged(TSelection *)), this,
                       SLOT(onSelectionChanged(TSelection *)));
  ret = ret && connect(TApp::instance()->getCurrentScene(),
                       SIGNAL(preferenceChanged(const QString &)), this,
                       SLOT(onPreferenceChanged(const QString &)));
  assert(ret);
  onFrameSwitched();
  onSelectionChanged(sh->getSelection());
  onPreferenceChanged("");
  onNameSetEditted();  // clear currentPathSet
}
updatePosTo
void LoadLevelPopup::updatePosTo () protected slot
{
  // calculate how many frames to be occupied in the xsheet
  TFilePath fp = getCurrentPath();
  if (QString::fromStdString(fp.getType()) == "tpl") {
    m_posTo->setText(m_posFrom->text());
    return;
  }
  TFrameId xFrom = m_xFrom->getValue();
  TFrameId xTo   = m_xTo->getValue();
  int frameLength;
  bool isScene = (QString::fromStdString(fp.getType()) == "tnz");
  if (isScene) {  // scene does not consider frame suffixes
    xFrom = TFrameId(xFrom.getNumber());
    xTo   = TFrameId(xTo.getNumber());
  }
  auto frameLengthBetweenFIds = [&]() {
    if (xFrom > xTo) return 0;
    int ret = xTo.getNumber() - xFrom.getNumber() + 1;
    if (!xTo.getLetter().isEmpty()) ret++;
    return ret;
  };
  //--- if loading the "missing" level
  if (m_notExistLabel->isVisible()) {
    int inc = m_incCombo->currentIndex();
    if (inc == 0)  // Inc = Auto
    {
      frameLength =
          frameLengthBetweenFIds() * ((m_stepCombo->currentIndex() == 0)
                                          ? 1
                                          : m_stepCombo->currentIndex());
    } else  // Inc =! Auto
    {
      int loopAmount;
      loopAmount  = tceil((double)(frameLengthBetweenFIds()) / (double)inc);
      frameLength = loopAmount * ((m_stepCombo->currentIndex() == 0)
                                      ? inc
                                      : m_stepCombo->currentIndex());
    }
  }
  //-- if loading the existing level
  else if (m_incCombo->currentIndex() == 0)  // Inc = Auto
  {
    if (isScene) {
      frameLength = frameLengthBetweenFIds();
    } else {
      std::vector<TFrameId> fIds = getCurrentFIds();
      //--- If loading the level with sequential files, reuse the list of
      // TFrameId
      if (fIds.size() != 0) {
        if (m_stepCombo->currentIndex() == 0)  // Step = Auto
        {
          frameLength = 0;
          std::vector<TFrameId>::iterator it;
          for (it = fIds.begin(); it != fIds.end(); it++) {
            if (xFrom <= *it && *it <= xTo)
              frameLength++;
            else if (xTo < *it)
              break;
          }
        } else  // Step != Auto
        {
          std::vector<TFrameId>::iterator it;
          int loopAmount = 0;
          for (it = fIds.begin(); it != fIds.end(); it++) {
            if (xFrom <= *it && *it <= xTo) loopAmount++;
          }
          frameLength = loopAmount * m_stepCombo->currentIndex();
        }
      }
      // loading another type of level such as tlv
      else {
        if (fp.isEmpty()) return;
        try {
          TLevelReaderP lr(fp);
          TLevelP level;
          if (lr) level = lr->loadInfo();
          if (!level.getPointer()) return;
          if (m_stepCombo->currentIndex() == 0)  // Step = Auto
          {
            frameLength = 0;
            TLevel::Iterator it;
            for (it = level->begin(); it != level->end(); it++) {
              if (xFrom <= it->first && it->first <= xTo)
                frameLength++;
              else if (xTo < it->first)
                break;
            }
          } else  // Step != Auto
          {
            TLevel::Iterator it;
            int loopAmount = 0;
            for (it = level->begin(); it != level->end(); it++) {
              if (xFrom <= it->first && it->first <= xTo) loopAmount++;
            }
            frameLength = loopAmount * m_stepCombo->currentIndex();
          }
        } catch (...) {
          return;
        }
      }
    }
  }
  // Inc != Auto
  else {
    int inc = m_incCombo->currentIndex();
    int loopAmount;
    loopAmount  = tceil((double)(frameLengthBetweenFIds()) / (double)inc);
    frameLength = loopAmount * ((m_stepCombo->currentIndex() == 0)
                                    ? inc
                                    : m_stepCombo->currentIndex());
  }
  m_posTo->setText(
      QString::number(m_posFrom->text().toInt() + frameLength - 1));
}
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/toonz/filebrowserpopup.h
E:/opentoonz/toonz/sources/toonz/filebrowserpopup.cpp