opentoonz: FxSchematicScene Class Reference
FxSchematicScene Class Reference final
Signals
void showPreview (TFxP)
void cacheFx (TFxP)
void doCollapse (const QList< TFxP > &)
void doExplodeChild (const QList< TFxP > &)
void editObject ()
Public Member Functions
FxSchematicScene (QWidget *parent)
void updateScene () override
QGraphicsItem * getCurrentNode () override
void reorderScene () override
TXsheet * getXsheet ()
void setApplication (TApplication *app)
TApplication * getApplication () const
TXsheetHandle * getXsheetHandle () const
TFxHandle * getFxHandle () const
TFrameHandle * getFrameHandle () const
TColumnHandle * getColumnHandle () const
TFx * getCurrentFx ()
QMenu * getInsertFxMenu ()
QMenu * getAddFxMenu ()
QMenu * getReplaceFxMenu ()
QAction * getAgainAction (int commands)
FxSelection * getFxSelection () const
void simulateDisconnectSelection (bool disconnect)
void updateNestedGroupEditors (FxSchematicNode *node, const QPointF &newPos)
void closeInnerMacroEditor (int groupId)
void resizeNodes (bool maximizedNode)
void initCursorScenePos ()
void selectNodes (QList< TFxP > &fxs)
void toggleNormalIconView ()
bool isNormalIconView ()
SchematicViewer * getSchematicViewer ()
Public Member Functions inherited from SchematicScene
SchematicScene (QWidget *parent)
void clearAllItems ()
virtual QGraphicsItem * getCurrentNode ()
virtual void reorderScene ()=0
virtual void updateScene ()=0
Protected Slots
void onSelectionSwitched (TSelection *oldSel, TSelection *newSel) override
void onSelectionChanged ()
void onDisconnectFromXSheet ()
void onConnectToXSheet ()
void onDeleteFx ()
void onDuplicateFx ()
void onUnlinkFx ()
void onMacroFx ()
void onExplodeMacroFx ()
void onOpenMacroFx ()
void onSavePresetFx ()
void onRemoveOutput ()
void onActivateOutput ()
void onPreview ()
void onCacheFx ()
void onUncacheFx ()
void onCollapse (const QList< TFxP > &)
void onXsheetChanged ()
void onSceneChanged ()
void onSwitchCurrentFx (TFx *)
void onCurrentFxSwitched ()
void onCurrentColumnChanged (int)
void onFxNodeDoubleClicked ()
void onInsertPaste ()
void onAddPaste ()
void onReplacePaste ()
void onAltModifierChanged (bool)
void onEditGroup ()
void onIconifyNodesToggled (bool iconified)
void onNodeChangedSize ()
Protected Slots inherited from SchematicScene
virtual void onSelectionSwitched (TSelection *, TSelection *)
Protected Member Functions
void contextMenuEvent (QGraphicsSceneContextMenuEvent *cme) override
void mousePressEvent (QGraphicsSceneMouseEvent *me) override
void mouseMoveEvent (QGraphicsSceneMouseEvent *me) override
void mouseReleaseEvent (QGraphicsSceneMouseEvent *me) override
bool event (QEvent *e) override
Protected Member Functions inherited from SchematicScene
bool isAnEmptyZone (const QRectF &rect)
Returns true if no nodes intersects rect.
QVector< SchematicNode * > getPlacedNode (SchematicNode *node)
void showEvent (QShowEvent *se)
void hideEvent (QHideEvent *se)
Additional Inherited Members
Protected Types inherited from SchematicScene
enum GridDimension { eLarge , eSmall }
Protected Attributes inherited from SchematicScene
QList< SchematicLink * > m_highlightedLinks
Detailed Description
Constructor & Destructor Documentation
FxSchematicScene()
FxSchematicScene::FxSchematicScene (QWidget * parent)
    : SchematicScene(parent)
    , m_firstPoint(sceneRect().center())
    , m_xshHandle(0)
    , m_fxHandle(0)
    , m_addFxContextMenu()
    , m_disconnectionLinks()
    , m_connectionLinks()
    , m_isConnected(false)
    , m_linkUnlinkSimulation(false)
    , m_altPressed(false)
    , m_lastPos(0, 0)
    , m_currentFxNode(0)
    , m_gridDimension(eSmall)
    , m_isNormalIconView(!IconifyFxSchematicNodes)
    , m_viewer() {
  m_viewer = (SchematicViewer *)parent;
  m_selection = new FxSelection();
  m_selection->setFxSchematicScene(this);
  connect(m_selection, SIGNAL(doCollapse(const QList<TFxP> &)), this,
          SLOT(onCollapse(const QList<TFxP> &)));
  connect(m_selection, SIGNAL(doExplodeChild(const QList<TFxP> &)), this,
          SIGNAL(doExplodeChild(const QList<TFxP> &)));
  connect(this, SIGNAL(selectionChanged()), this, SLOT(onSelectionChanged()));
  m_addFxContextMenu.setSelection(m_selection);
  m_highlightedLinks.clear();
}
~FxSchematicScene()
FxSchematicScene::~FxSchematicScene ()
{
  if (m_selection) delete m_selection;
}
Member Function Documentation
closeInnerMacroEditor()
void FxSchematicScene::closeInnerMacroEditor (int groupId)
{
  assert(m_groupEditorTable.contains(groupId));
  QMap<TMacroFx *, FxSchematicMacroEditor *>::iterator it;
  for (it = m_macroEditorTable.begin(); it != m_macroEditorTable.end(); it++) {
    TMacroFx *macro = it.key();
    assert(macro);
    if (macro->getAttributes()->isContainedInGroup(groupId)) {
      macro->editMacro(false);
      macro->getAttributes()->closeEditingGroup(groupId);
    }
  }
}
contextMenuEvent()
void FxSchematicScene::contextMenuEvent (QGraphicsSceneContextMenuEvent * cme) override protected
{
  QPointF scenePos                = cme->scenePos();
  QList<QGraphicsItem *> itemList = items(scenePos);
  if (!itemList.isEmpty()) {
    SchematicScene::contextMenuEvent(cme);
    return;
  }
  QMenu menu(views()[0]);
  if (cme->modifiers() & Qt::ControlModifier) {
    menu.addAction(m_addFxContextMenu.getAgainCommand(AddFxContextMenu::Add));
    if (!menu.actions().isEmpty()) {
      menu.exec(cme->screenPos());
      return;
    }
  }
  QAction *addOutputFx =
      CommandManager::instance()->getAction("MI_NewOutputFx");
  QAction *copy  = CommandManager::instance()->getAction("MI_Copy");
  QAction *cut   = CommandManager::instance()->getAction("MI_Cut");
  QAction *paste = CommandManager::instance()->getAction("MI_Paste");
  m_addFxContextMenu.setCurrentCursorScenePos(cme->scenePos());
  menu.addMenu(m_addFxContextMenu.getAddMenu());
  if (addOutputFx) menu.addAction(addOutputFx);
  // Close sub xsheet and move to parent sheet
  ToonzScene *scene      = getXsheet()->getScene();
  ChildStack *childStack = scene->getChildStack();
  if (childStack && childStack->getAncestorCount() > 0) {
    menu.addSeparator();
    menu.addAction(CommandManager::instance()->getAction("MI_CloseChild"));
  }
  menu.addSeparator();
  menu.addAction(copy);
  menu.addAction(cut);
  menu.addAction(paste);
  m_selection->setPastePosition(TPointD(scenePos.x(), scenePos.y()));
  menu.exec(cme->screenPos());
  m_selection->setPastePosition(TConst::nowhere);
}
event()
bool FxSchematicScene::event (QEvent * e) override protected
{
  bool ret        = SchematicScene::event(e);
  bool altPressed = QApplication::keyboardModifiers() == Qt::AltModifier;
  if (m_altPressed != altPressed) {
    // When Alt key is pressed, put the link lines on top of other items
    // in order to enable to pick them up with itemAt() function.
    double z                          = (altPressed) ? 5.0 : 0.0;
    QList<QGraphicsItem *> sceneItems = items();
    for (int i = 0; i < sceneItems.size(); i++) {
      SchematicLink *link = dynamic_cast<SchematicLink *>(sceneItems.at(i));
      if (link) link->setZValue(z);
    }
    if (m_linkUnlinkSimulation) onAltModifierChanged(altPressed);
    m_altPressed = altPressed;
  }
  return ret;
}
getAddFxMenu()
QMenu * FxSchematicScene::getAddFxMenu () inline
{ return m_addFxContextMenu.getAddMenu(); }
getAgainAction()
QAction * FxSchematicScene::getAgainAction (int commands) inline
{
    return m_addFxContextMenu.getAgainCommand(commands);
  }
getApplication()
TApplication * FxSchematicScene::getApplication () const inline
{ return m_app; }
getColumnHandle()
TColumnHandle * FxSchematicScene::getColumnHandle () const inline
{ return m_columnHandle; }
getCurrentFx()
TFx * FxSchematicScene::getCurrentFx ()
{ return m_fxHandle->getFx(); }
getCurrentNode()
QGraphicsItem * FxSchematicScene::getCurrentNode () override virtual
Reimplemented from SchematicScene.
{
  QList<QGraphicsItem *> allItems = items();
  for (auto const item : allItems) {
    FxSchematicNode *node = dynamic_cast<FxSchematicNode *>(item);
    if (node && node->getFx() == m_fxHandle->getFx()) return node;
  }
  return 0;
}
getFrameHandle()
TFrameHandle * FxSchematicScene::getFrameHandle () const inline
{ return m_frameHandle; }
getFxHandle()
TFxHandle * FxSchematicScene::getFxHandle () const inline
{ return m_fxHandle; }
getFxSelection()
FxSelection * FxSchematicScene::getFxSelection () const inline
{ return m_selection; }
getInsertFxMenu()
QMenu * FxSchematicScene::getInsertFxMenu () inline
{ return m_addFxContextMenu.getInsertMenu(); }
getReplaceFxMenu()
QMenu * FxSchematicScene::getReplaceFxMenu () inline
{ return m_addFxContextMenu.getReplaceMenu(); }
getSchematicViewer()
SchematicViewer * FxSchematicScene::getSchematicViewer () inline
{ return m_viewer; }
getXsheet()
TXsheet * FxSchematicScene::getXsheet ()
{ return m_xshHandle->getXsheet(); }
getXsheetHandle()
TXsheetHandle * FxSchematicScene::getXsheetHandle () const inline
{ return m_xshHandle; }
initCursorScenePos()
void FxSchematicScene::initCursorScenePos () inline
{
    m_addFxContextMenu.setCurrentCursorScenePos(QPointF(0, 0));
  }
isNormalIconView()
bool FxSchematicScene::isNormalIconView () inline
{ return m_isNormalIconView; }
mouseMoveEvent()
void FxSchematicScene::mouseMoveEvent (QGraphicsSceneMouseEvent * me) override protected
{
  SchematicScene::mouseMoveEvent(me);
  m_lastPos = me->scenePos();
  bool leftButton = (QApplication::mouseButtons() == Qt::LeftButton);
  bool altButton  = (QApplication::keyboardModifiers() == Qt::AltModifier);
  if (leftButton && m_isConnected && altButton) {
    m_linkUnlinkSimulation = true;
    simulateDisconnectSelection(true);
    m_connectionLinks.showBridgeLinks();
#if QT_VERSION >= 0x050000
    SchematicLink *link =
        dynamic_cast<SchematicLink *>(itemAt(m_lastPos, QTransform()));
#else
    SchematicLink *link = dynamic_cast<SchematicLink *>(itemAt(m_lastPos));
#endif
    if (link && (link->getEndPort() && link->getStartPort())) {
      TFxCommand::Link fxLink = m_selection->getBoundingFxs(link);
      if (fxLink == TFxCommand::Link()) return;
      TFx *inputFx  = fxLink.m_inputFx.getPointer();
      TFx *outputFx = fxLink.m_outputFx.getPointer();
      TFxSet *internalFxs = getXsheet()->getFxDag()->getInternalFxs();
      if (!internalFxs->containsFx(inputFx) &&
          !dynamic_cast<TColumnFx *>(inputFx) &&
          !dynamic_cast<TXsheetFx *>(inputFx) &&
          !dynamic_cast<TOutputFx *>(inputFx))
        return;
      if (!internalFxs->containsFx(outputFx) &&
          !dynamic_cast<TColumnFx *>(outputFx) &&
          !dynamic_cast<TXsheetFx *>(outputFx) &&
          !dynamic_cast<TOutputFx *>(outputFx))
        return;
    }
    m_connectionLinks.hideBridgeLinks();
    simulateInsertSelection(link, altButton && !!link);
  }
}
mousePressEvent()
void FxSchematicScene::mousePressEvent (QGraphicsSceneMouseEvent * me) override protected
{
  QList<QGraphicsItem *> items = selectedItems();
#if QT_VERSION >= 0x050000
  QGraphicsItem *item = itemAt(me->scenePos(), QTransform());
#else
  QGraphicsItem *item = itemAt(me->scenePos());
#endif
  FxSchematicPort *port = dynamic_cast<FxSchematicPort *>(item);
  FxSchematicLink *link = dynamic_cast<FxSchematicLink *>(item);
  SchematicScene::mousePressEvent(me);
  onSelectionChanged();
  if (me->button() == Qt::MidButton) {
    int i;
    for (i = 0; i < items.size(); i++) items[i]->setSelected(true);
  }
  /*
  m_selection may not be updated here, so I use QGraphicsScene::selectedItems()
  instead of m_selection->isEmpty() to check whether any node is selected or
  not.
  */
  if (selectedItems().isEmpty()) {
    if (me->button() != Qt::MidButton && !item) m_fxHandle->setFx(0, false);
    return;
  }
  m_isConnected = false;
  if (!canDisconnectSelection(m_selection)) return;
  m_selectionOldPos.clear();
  QList<TFxP> selectedFxs = m_selection->getFxs();
  int i;
  for (i = 0; i < selectedFxs.size(); i++) {
    TFxP selectedFx = selectedFxs[i];
    TPointD pos     = selectedFx->getAttributes()->getDagNodePos();
    m_selectionOldPos.append(QPair<TFxP, TPointD>(selectedFx, pos));
  }
  FxsData fxsData;
  fxsData.setFxs(m_selection->getFxs(), m_selection->getLinks(),
                 m_selection->getColumnIndexes(), m_xshHandle->getXsheet());
  // m_isConnected indicates that the all selected nodes are connected
  if (fxsData.isConnected() && me->button() == Qt::LeftButton && !port && !link)
    m_isConnected = true;
}
mouseReleaseEvent()
void FxSchematicScene::mouseReleaseEvent (QGraphicsSceneMouseEvent * me) override protected
{
  SchematicScene::mouseReleaseEvent(me);
  m_linkUnlinkSimulation = false;
  if ((m_disconnectionLinks.size() == 0) && (m_connectionLinks.size() == 0))
    return;
  TUndoManager::manager()->beginBlock();
  bool altButton = QApplication::keyboardModifiers() == Qt::AltModifier;
  if (altButton && m_isConnected) {
    if (m_connectionLinks.size() > 0) {
      const QList<SchematicLink *> &bridgeLinks =
          m_connectionLinks.getBridgeLinks();
      assert(bridgeLinks.size() <= 1);
      SchematicLink *link = bridgeLinks[0];
      if (link) {
        FxSchematicNode *outputNode =
            dynamic_cast<FxSchematicNode *>(link->getEndPort()->getNode());
        FxSchematicNode *inputNode =
            dynamic_cast<FxSchematicNode *>(link->getStartPort()->getNode());
        if (inputNode && outputNode) {
          SchematicPort *port = link->getStartPort();
          if (port->getType() == 200 || port->getType() == 204)
            port = link->getOtherPort(port);
          int i;
          for (i = 0; i < outputNode->getInputPortCount(); i++)
            if (port == outputNode->getInputPort(i)) break;
          TFxCommand::Link fxLink;
          fxLink.m_outputFx = outputNode->getFx();
          fxLink.m_inputFx  = inputNode->getFx();
          if (!outputNode->isA(eXSheetFx)) fxLink.m_index = i;
          TFxCommand::connectFxs(fxLink, m_selection->getFxs().toStdList(),
                                 m_xshHandle, m_selectionOldPos);
        }
      }
    } else if (m_disconnectionLinks.size() > 0) {
      QList<TFxP> fxs = m_selection->getFxs();
      TFxCommand::disconnectFxs(fxs.toStdList(), m_xshHandle,
                                m_selectionOldPos);
      m_selectionOldPos.clear();
    }
  }
  TUndoManager::manager()->endBlock();
  m_isConnected = false;
}
onActivateOutput
void FxSchematicScene::onActivateOutput () protected slot
{
  TFxCommand::makeOutputFxCurrent(m_fxHandle->getFx(), m_xshHandle);
}
onAddPaste
void FxSchematicScene::onAddPaste () protected slot
{
  if (!m_selection->addPasteSelection())
    DVGui::error(
        tr("Cannot Paste Add a selection of unconnected FX nodes.\nSelect FX "
           "nodes and related links before copying or cutting the selection "
           "you want to paste."));
}
onAltModifierChanged
void FxSchematicScene::onAltModifierChanged (bool altPressed) protected slot
{
  if (altPressed) {
    if (m_disconnectionLinks.size() == 0 && m_linkUnlinkSimulation)
      simulateDisconnectSelection(altPressed);
    if (m_connectionLinks.size() == 0 && m_linkUnlinkSimulation) {
#if QT_VERSION >= 0x050000
      SchematicLink *link =
          dynamic_cast<SchematicLink *>(itemAt(m_lastPos, QTransform()));
#else
      SchematicLink *link = dynamic_cast<SchematicLink *>(itemAt(m_lastPos));
#endif
      if (link && (!link->getEndPort() || !link->getStartPort())) return;
      simulateInsertSelection(link, altPressed && !!link);
    }
  } else {
    if (m_disconnectionLinks.size() > 0 && m_linkUnlinkSimulation)
      simulateDisconnectSelection(altPressed);
    if (m_connectionLinks.size() > 0 && m_linkUnlinkSimulation) {
      m_connectionLinks.showBridgeLinks();
      simulateInsertSelection(0, false);
    }
  }
}
onCacheFx
void FxSchematicScene::onCacheFx () protected slot
{ setEnableCache(true); }
onCollapse
void FxSchematicScene::onCollapse (const QList< TFxP > & fxs) protected slot
{
  emit doCollapse(fxs);
}
onConnectToXSheet
void FxSchematicScene::onConnectToXSheet () protected slot
{
  std::list<TFxP, std::allocator<TFxP>> list =
      m_selection->getFxs().toStdList();
  TFxCommand::connectNodesToXsheet(list, m_xshHandle);
}
onCurrentColumnChanged
void FxSchematicScene::onCurrentColumnChanged (int index) protected slot
{
  m_app->getCurrentColumn()->setColumnIndex(index);
  m_app->getCurrentObject()->setObjectId(TStageObjectId::ColumnId(index));
}
onCurrentFxSwitched
void FxSchematicScene::onCurrentFxSwitched () protected slot
{
  if (m_currentFxNode) m_currentFxNode->setIsCurrentFxLinked(false, 0);
  if (m_table.contains(m_fxHandle->getFx())) {
    m_currentFxNode = m_table[m_fxHandle->getFx()];
    m_currentFxNode->setIsCurrentFxLinked(true, 0);
  } else
    m_currentFxNode = 0;
}
onDeleteFx
void FxSchematicScene::onDeleteFx () protected slot
{
  std::list<TFxP, std::allocator<TFxP>> fxList =
      m_selection->getFxs().toStdList();
  std::list<TFxCommand::Link> linkList = m_selection->getLinks().toStdList();
  std::list<int> columnIndexList = m_selection->getColumnIndexes().toStdList();
  TFxCommand::deleteSelection(fxList, linkList, columnIndexList, m_xshHandle,
                              m_fxHandle);
}
onDisconnectFromXSheet
void FxSchematicScene::onDisconnectFromXSheet () protected slot
{
  std::list<TFxP, std::allocator<TFxP>> list =
      m_selection->getFxs().toStdList();
  TFxCommand::disconnectNodesFromXsheet(list, m_xshHandle);
}
onDuplicateFx
void FxSchematicScene::onDuplicateFx () protected slot
{
  QList<TFxP> fxs = m_selection->getFxs();
  if (fxs.empty()) return;
  TUndoManager::manager()->beginBlock();
  int i, size = fxs.size();
  for (i = 0; i != size; ++i)
    TFxCommand::duplicateFx(fxs[i].getPointer(), m_xshHandle, m_fxHandle);
  TUndoManager::manager()->endBlock();
}
onEditGroup
void FxSchematicScene::onEditGroup () protected slot
{
  if (m_selection->isEmpty()) return;
  QList<TFxP> fxs = m_selection->getFxs();
  int i;
  for (i = 0; i < fxs.size(); i++) {
    if (fxs[i]->getAttributes()->isGrouped() &&
        !fxs[i]->getAttributes()->isGroupEditing()) {
      fxs[i]->getAttributes()->editGroup();
      TMacroFx *macro = dynamic_cast<TMacroFx *>(fxs[i].getPointer());
      if (macro) {
        std::vector<TFxP> macroFxs = macro->getFxs();
        int j;
        for (j = 0; j < (int)macroFxs.size(); j++)
          macroFxs[j]->getAttributes()->editGroup();
      }
    }
  }
  updateScene();
}
onExplodeMacroFx
void FxSchematicScene::onExplodeMacroFx () protected slot
{
  if (TMacroFx *macroFx = dynamic_cast<TMacroFx *>(m_fxHandle->getFx()))
    TFxCommand::explodeMacroFx(macroFx, m_app);
}
onFxNodeDoubleClicked
void FxSchematicScene::onFxNodeDoubleClicked () protected slot
{
  // emitting fxSettingsShouldBeSwitched
  m_fxHandle->onFxNodeDoubleClicked();
}
onIconifyNodesToggled
void FxSchematicScene::onIconifyNodesToggled (bool iconified) protected slot
{
  m_isNormalIconView      = !iconified;
  IconifyFxSchematicNodes = (iconified) ? 1 : 0;
  updateScene();
}
onInsertPaste
void FxSchematicScene::onInsertPaste () protected slot
{
  if (!m_selection->insertPasteSelection())
    DVGui::error(
        tr("Cannot Paste Insert a selection of unconnected FX nodes.\nSelect "
           "FX nodes and related links before copying or cutting the selection "
           "you want to paste."));
}
onMacroFx
void FxSchematicScene::onMacroFx () protected slot
{
  TFxCommand::makeMacroFx(m_selection->getFxs().toVector().toStdVector(),
                          m_app);
}
onNodeChangedSize
void FxSchematicScene::onNodeChangedSize () protected slot
{
  if (resizingNodes) return;
  updateScene();
}
onOpenMacroFx
void FxSchematicScene::onOpenMacroFx () protected slot
{
  if (TMacroFx *macroFx = dynamic_cast<TMacroFx *>(m_fxHandle->getFx())) {
    macroFx->editMacro(true);
    updateScene();
  }
}
onPreview
void FxSchematicScene::onPreview () protected slot
{ emit showPreview(m_fxHandle->getFx()); }
onRemoveOutput
void FxSchematicScene::onRemoveOutput () protected slot
{
  TFxCommand::removeOutputFx(m_fxHandle->getFx(), m_xshHandle, m_fxHandle);
}
onReplacePaste
void FxSchematicScene::onReplacePaste () protected slot
{
  if (!m_selection->replacePasteSelection())
    DVGui::error(
        tr("Cannot Paste Replace a selection of unconnected FX nodes.\nSelect "
           "FX nodes and related links before copying or cutting the selection "
           "you want to paste."));
}
onSavePresetFx
void FxSchematicScene::onSavePresetFx () protected slot
{
  CommandManager::instance()->getAction("MI_SavePreset")->trigger();
}
onSceneChanged
void FxSchematicScene::onSceneChanged () protected slot
{
  m_app->getCurrentScene()->notifySceneChanged();
}
onSelectionChanged
void FxSchematicScene::onSelectionChanged () protected slot
{
  m_selection->selectNone();
  int i, size = m_highlightedLinks.size();
  for (i = 0; i < size; i++) {
    SchematicLink *link = m_highlightedLinks[i];
    link->setHighlighted(false);
    link->update();
  }
  m_highlightedLinks.clear();
  QList<QGraphicsItem *> slcItems = selectedItems();
  QList<QGraphicsItem *>::iterator it;
  for (it = slcItems.begin(); it != slcItems.end(); it++) {
    FxSchematicNode *node = dynamic_cast<FxSchematicNode *>(*it);
    if (node) {
      if (!node->isA(eGroupedFx)) {
        if (node->isA(eXSheetFx)) continue;
        m_selection->select(node->getFx());
        if (node->isA(eColumnFx)) {
          FxSchematicColumnNode *columnNode =
              dynamic_cast<FxSchematicColumnNode *>(node);
          if (columnNode)
            m_selection->select(columnNode->getColumnIndex());
          else {
            FxSchematicPaletteNode *paletteNode =
                dynamic_cast<FxSchematicPaletteNode *>(node);
            if (paletteNode) m_selection->select(paletteNode->getColumnIndex());
          }
        }
      } else {
        FxGroupNode *groupNode = dynamic_cast<FxGroupNode *>(node);
        assert(groupNode);
        QList<TFxP> fxs = groupNode->getGroupedFxs();
        for (i = 0; i < fxs.size(); i++) {
          m_selection->select(fxs[i].getPointer());
          TLevelColumnFx *colFx =
              dynamic_cast<TLevelColumnFx *>(fxs[i].getPointer());
          if (colFx) {
            if (TXshLevelColumn *column = colFx->getColumn()) {
              int colIndex = column->getIndex();
              m_selection->select(colIndex);
            }
          }
        }
      }
      highlightLinks(node, true);
    }
    SchematicLink *link = dynamic_cast<SchematicLink *>(*it);
    if (link) m_selection->select(link);
  }
  m_selection->makeCurrent();
  TSelectionHandle *selHandle = TSelectionHandle::getCurrent();
  selHandle->notifySelectionChanged();
}
onSelectionSwitched
void FxSchematicScene::onSelectionSwitched (TSelection * oldSel, TSelection * newSel) override protected slot
{
  if (m_selection == oldSel && m_selection != newSel) clearSelection();
}
onSwitchCurrentFx
void FxSchematicScene::onSwitchCurrentFx (TFx * fx) protected slot
{
  if (m_fxHandle->getFx() == fx) return;
  if (fx) {
    // Forbid update of the swatch upon column switch. This could generate
    // a further useless render...
    SwatchViewer::suspendRendering(true, false);
    int columnIndex = fx->getReferenceColumnIndex();
    if (columnIndex >= 0) {
      m_columnHandle->setColumnIndex(columnIndex);
      m_app->getCurrentObject()->setObjectId(
          TStageObjectId::ColumnId(columnIndex));
    }
    SwatchViewer::suspendRendering(false);
    m_fxHandle->setFx(fx, false);  // Setting the fx updates the swatch
    emit editObject();
  } else {
    m_fxHandle->setFx(0, false);
  }
}
onUncacheFx
void FxSchematicScene::onUncacheFx () protected slot
{ setEnableCache(false); }
onUnlinkFx
void FxSchematicScene::onUnlinkFx () protected slot
{
  QList<TFxP> fxs = m_selection->getFxs();
  if (fxs.empty()) return;
  TUndoManager::manager()->beginBlock();
  int i, size = fxs.size();
  for (i = 0; i != size; ++i)
    TFxCommand::unlinkFx(fxs[i].getPointer(), m_fxHandle, m_xshHandle);
  TUndoManager::manager()->endBlock();
}
onXsheetChanged
void FxSchematicScene::onXsheetChanged () protected slot
{ m_xshHandle->notifyXsheetChanged(); }
reorderScene()
void FxSchematicScene::reorderScene () override virtual
Implements SchematicScene.
{
  int step = m_gridDimension == eLarge ? 100 : 50;
  m_placedFxs.clear();
  QPointF sceneCenter = sceneRect().center();
  double minY         = sceneCenter.y();
  double maxX         = sceneCenter.x();
  double y            = minY;
  double x            = maxX;
  TXsheet *xsh = m_xshHandle->getXsheet();
  int i        = 0;
  FxDag *fxDag  = xsh->getFxDag();
  TFxSet *fxSet = fxDag->getInternalFxs();
  //  Let's reset every position to nowhere first
  fxDag->getXsheetFx()->getAttributes()->setDagNodePos(TConst::nowhere);
  for (i = 0; i < fxDag->getOutputFxCount(); i++) {
    TOutputFx *fx = fxDag->getOutputFx(i);
    if (!fx) continue;
    fx->getAttributes()->setDagNodePos(TConst::nowhere);
  }
  for (i = 0; i < xsh->getColumnCount(); i++) {
    TXshColumn *column = xsh->getColumn(i);
    TFx *fx            = column->getFx();
    if (!fx) continue;
    fx->getAttributes()->setDagNodePos(TConst::nowhere);
  }
  for (i = 0; i < fxSet->getFxCount(); i++) {
    TFx *fx = fxSet->getFx(i);
    fx->getAttributes()->setDagNodePos(TConst::nowhere);
    TMacroFx *macro = dynamic_cast<TMacroFx *>(fx);
    if (macro && macro->isEditing()) {
      std::vector<TFxP> fxs = macro->getFxs();
      int j;
      for (j = 0; j < (int)fxs.size(); j++) {
        fxs[j]->getAttributes()->setDagNodePos(TConst::nowhere);
      }
    }
  }
  // Let's start placing them now
  for (i = 0; i < xsh->getColumnCount(); i++) {
    TXshColumn *column = xsh->getColumn(i);
    TFx *fx            = column->getFx();
    if (column->isEmpty() || !fx) continue;
    TZeraryColumnFx *zfx = dynamic_cast<TZeraryColumnFx *>(fx);
    if (zfx && (zfx->getZeraryFx()->getInputPortCount() > 0)) {
      TFxPort *port = zfx->getZeraryFx()->getInputPort(0);
      if (port && port->getFx()) continue;
    }
    if (zfx && m_placedFxs.contains(zfx->getZeraryFx())) continue;
    x = sceneCenter.x();
    placeNodeAndParents(fx, x, maxX, minY);
    y -= step;
    minY = std::min(y, minY);
  }
  // remove retrolink
  for (i = 0; i < xsh->getColumnCount(); i++) {
    TXshColumn *column = xsh->getColumn(i);
    TFx *fx            = column->getFx();
    if (column->isEmpty() || !fx) continue;
    TZeraryColumnFx *zfx = dynamic_cast<TZeraryColumnFx *>(fx);
    if (zfx && m_placedFxs.contains(zfx->getZeraryFx())) continue;
    if (zfx && (zfx->getZeraryFx()->getInputPortCount() > 0)) {
      TFxPort *port = zfx->getZeraryFx()->getInputPort(0);
      if (port && port->getFx()) continue;
    }
    for (int j = 0; j < fx->getOutputConnectionCount(); j++) {
      TFx *outFx = fx->getOutputConnection(j)->getOwnerFx();
      removeRetroLinks(outFx, maxX);
    }
  }
  double middleY = (sceneCenter.y() + minY + step) * 0.5;
  placeNodeAndParents(xsh->getFxDag()->getXsheetFx(), maxX, maxX, middleY);
  y -= step;
  minY = std::min(y, minY);
  for (i = 0; i < fxSet->getFxCount(); i++) {
    TFx *fx = fxSet->getFx(i);
    if (m_placedFxs.contains(fx)) continue;
    placeNodeAndParents(fx, (sceneCenter.x() + 120), maxX, minY);
    y -= step;
    minY = std::min(y, minY);
  }
  updateScene();
}
resizeNodes()
void FxSchematicScene::resizeNodes (bool maximizedNode)
{
  resizingNodes = true;
  // resize nodes
  m_gridDimension = maximizedNode ? eLarge : eSmall;
  m_xshHandle->getXsheet()->getFxDag()->setDagGridDimension(m_gridDimension);
  QMap<TFx *, FxSchematicNode *>::iterator it1;
  for (it1 = m_table.begin(); it1 != m_table.end(); it1++) {
    if (!it1.value()) continue;
    it1.value()->resize(maximizedNode);
    TFx *fx = it1.value()->getFx();
    updatePositionOnResize(fx, maximizedNode);
  }
  QMap<int, FxGroupNode *>::iterator it2;
  for (it2 = m_groupedTable.begin(); it2 != m_groupedTable.end(); it2++) {
    if (!it2.value()) continue;
    it2.value()->resize(maximizedNode);
    QList<TFxP> groupedFxs = it2.value()->getGroupedFxs();
    for (int i = 0; i < groupedFxs.size(); i++)
      updatePositionOnResize(groupedFxs[i].getPointer(), maximizedNode);
  }
  QMap<TMacroFx *, FxSchematicMacroEditor *>::iterator it3;
  for (it3 = m_macroEditorTable.begin(); it3 != m_macroEditorTable.end();
       it3++) {
    if (!it3.value()) continue;
    it3.value()->resizeNodes(maximizedNode);
  }
  updateScene();
  resizingNodes = false;
}
selectNodes()
void FxSchematicScene::selectNodes (QList< TFxP > & fxs)
in order to select nods after pasting the copied fx nodes from FxSelection
{
  clearSelection();
  for (int i = 0; i < (int)fxs.size(); i++) {
    TFx *tempFx = fxs[i].getPointer();
    QMap<TFx *, FxSchematicNode *>::iterator it;
    it = m_table.find(tempFx);
    if (it == m_table.end()) continue;
    it.value()->setSelected(true);
  }
  update();
}
Referenced by FxSelection::pasteSelection().
setApplication()
void FxSchematicScene::setApplication (TApplication * app)
{
  m_app = app;
  m_xshHandle    = app->getCurrentXsheet();
  m_fxHandle     = app->getCurrentFx();
  m_frameHandle  = app->getCurrentFrame();
  m_columnHandle = app->getCurrentColumn();
  if (m_fxHandle)
    connect(m_fxHandle, SIGNAL(fxSwitched()), this,
            SLOT(onCurrentFxSwitched()));
  m_addFxContextMenu.setApplication(app);
  m_selection->setXsheetHandle(m_xshHandle);
  m_selection->setFxHandle(m_fxHandle);
}
simulateDisconnectSelection()
void FxSchematicScene::simulateDisconnectSelection (bool disconnect)
Disconnects or connects selected item from the rest of the graph. Selection must be a connected subgraph. If disconnect is true, the selection is disconnected; connected otherwise.
{
  if (disconnect) {
    if (m_selection->isEmpty()) return;
    QList<TFxP> selectedFxs = m_selection->getFxs();
    if (selectedFxs.isEmpty()) return;
    QMap<TFx *, bool> visitedFxs;
    int i;
    for (i = 0; i < selectedFxs.size(); i++)
      visitedFxs[selectedFxs[i].getPointer()] = false;
    TFx *inputFx = 0, *outputFx = 0;
    findBoundariesFxs(inputFx, outputFx, visitedFxs);
    FxSchematicNode *inputNode  = m_table[inputFx];
    FxSchematicNode *outputNode = m_table[outputFx];
    assert(inputNode && outputNode);
    FxSchematicPort *inputPort = 0, *outputPort = 0;
    SchematicPort *otherInputPort = 0;
    QList<SchematicPort *> otherOutputPorts;
    if (inputNode->getInputPortCount() > 0) {
      inputPort = inputNode->getInputPort(0);
      if (inputPort) {
        SchematicLink *inputLink = inputPort->getLink(0);
        if (inputLink && !m_connectionLinks.isAnInputLink(inputLink)) {
          if (!m_disconnectionLinks.isAnInputLink(inputLink))
            m_disconnectionLinks.addInputLink(inputLink);
          otherInputPort = inputLink->getOtherPort(inputPort);
        }
      }
    }
    outputPort = outputNode->getOutputPort();
    if (outputPort) {
      for (i = 0; i < outputPort->getLinkCount(); i++) {
        SchematicLink *outputLink = outputPort->getLink(i);
        if (outputLink && !m_connectionLinks.isAnOutputLink(outputLink)) {
          if (!m_disconnectionLinks.isAnOutputLink(outputLink))
            m_disconnectionLinks.addOutputLink(outputLink);
          otherOutputPorts.push_back(outputLink->getOtherPort(outputPort));
        }
      }
    }
    m_disconnectionLinks.hideInputLinks();
    m_disconnectionLinks.hideOutputLinks();
    if (otherInputPort) {
      for (i = 0; i < otherOutputPorts.size(); i++)
        m_disconnectionLinks.addBridgeLink(
            otherOutputPorts[i]->makeLink(otherInputPort));
    }
  } else {
    m_disconnectionLinks.showInputLinks();
    m_disconnectionLinks.showOutputLinks();
    m_disconnectionLinks.removeInputLinks();
    m_disconnectionLinks.removeOutputLinks();
    m_disconnectionLinks.removeBridgeLinks(true);
  }
}
References SchematicPort::getLink(), SchematicLink::getOtherPort(), and FxSelection::isEmpty().
toggleNormalIconView()
void FxSchematicScene::toggleNormalIconView () inline
{ m_isNormalIconView = !m_isNormalIconView; }
updateNestedGroupEditors()
void FxSchematicScene::updateNestedGroupEditors (FxSchematicNode * node, const QPointF & newPos)
Updates all Group Editors containing fx. Each fx is only in one group, but each group can contains other groups. All nested Groups must be updated.
{
  if (!node) return;
  QStack<int> groupIdStack = node->getFx()->getAttributes()->getGroupIdStack();
  int i;
  QRectF rect;
  for (i = 0; i < groupIdStack.size(); i++) {
    if (m_groupEditorTable.contains(groupIdStack[i])) {
      QRectF app = m_groupEditorTable[groupIdStack[i]]->sceneBoundingRect();
      if (rect.isEmpty())
        rect = app;
      else
#if QT_VERSION >= 0x050000
        rect = rect.united(app);
#else
        rect = rect.unite(app);
#endif
    }
  }
  QMap<TMacroFx *, FxSchematicMacroEditor *>::iterator it;
  for (it = m_macroEditorTable.begin(); it != m_macroEditorTable.end(); it++) {
    if (it.value()->contains(node)) {
      QRectF app = it.value()->sceneBoundingRect();
      if (rect.isEmpty())
        rect = app;
      else
#if QT_VERSION >= 0x050000
        rect = rect.united(app);
#else
        rect = rect.unite(app);
#endif
    }
  }
  node->setPos(newPos);
  for (i = 0; i < groupIdStack.size(); i++) {
    if (!m_groupEditorTable.contains(groupIdStack[i])) continue;
#if QT_VERSION >= 0x050000
    rect =
        rect.united(m_groupEditorTable[groupIdStack[i]]->sceneBoundingRect());
#else
    rect = rect.unite(m_groupEditorTable[groupIdStack[i]]->sceneBoundingRect());
#endif
    QRectF app = m_groupEditorTable[groupIdStack[i]]->boundingSceneRect();
    if (m_groupEditorTable[groupIdStack[i]]->scenePos() != app.topLeft())
      m_groupEditorTable[groupIdStack[i]]->setPos(app.topLeft());
  }
  for (it = m_macroEditorTable.begin(); it != m_macroEditorTable.end(); it++) {
    FxSchematicMacroEditor *editor = it.value();
    if (editor->contains(node)) {
      QRectF app = editor->sceneBoundingRect();
#if QT_VERSION >= 0x050000
      rect = rect.united(app);
#else
      rect = rect.unite(app);
#endif
      app = editor->boundingSceneRect();
      if (editor->scenePos() != app.topLeft()) editor->setPos(app.topLeft());
    }
  }
  update(rect);
}
updateScene()
void FxSchematicScene::updateScene () override virtual
Implements SchematicScene.
{
  if (updatingScene) return;
  updatingScene = true;
  if (!views().empty()) m_disconnectionLinks.clearAll();
  m_connectionLinks.clearAll();
  m_selectionOldPos.clear();
  clearSelection();
  clearAllItems();
  m_table.clear();
  m_groupedTable.clear();
  m_groupEditorTable.clear();
  m_macroEditorTable.clear();
  m_currentFxNode = 0;
  // GroupId->Fx
  QMap<int, QList<TFxP>> groupedFxs;
  QMap<int, QList<SchematicNode *>> editedGroup;
  QMap<TMacroFx *, QList<SchematicNode *>> editedMacro;
  TXsheet *xsh    = m_xshHandle->getXsheet();
  m_gridDimension = xsh->getFxDag()->getDagGridDimension();
  TFxSet *fxSet   = xsh->getFxDag()->getInternalFxs();
  int i;
  FxDag *fxDag = xsh->getFxDag();
  // Add XSheetFX node
  addFxSchematicNode(fxDag->getXsheetFx());
  // Add outputFx nodes
  int k;
  for (k = 0; k < fxDag->getOutputFxCount(); k++) {
    TOutputFx *fx = fxDag->getOutputFx(k);
    if (fx->getAttributes()->isGrouped() &&
        !fx->getAttributes()->isGroupEditing()) {
      groupedFxs[fx->getAttributes()->getGroupId()].push_back(fx);
      continue;
    }
    SchematicNode *node = addFxSchematicNode(fx);
    if (fx->getAttributes()->isGrouped())
      editedGroup[fx->getAttributes()->getEditingGroupId()].append(node);
  }
  // Add columnFx and zeraryFx nodes
  for (i = 0; i < xsh->getColumnCount(); i++) {
    TXshColumn *column = xsh->getColumn(i);
    TFx *fx            = 0;
    if (TXshLevelColumn *lc = column->getLevelColumn())
      fx = lc->getLevelColumnFx();
    else if (TXshPaletteColumn *pc = dynamic_cast<TXshPaletteColumn *>(column))
      fx = pc->getPaletteColumnFx();
    else if (TXshZeraryFxColumn *zc =
                 dynamic_cast<TXshZeraryFxColumn *>(column))
      fx = zc->getZeraryColumnFx();
    if (!fx) continue;
    if (fx->getAttributes()->isGrouped() &&
        !fx->getAttributes()->isGroupEditing()) {
      groupedFxs[fx->getAttributes()->getGroupId()].push_back(fx);
      continue;
    }
    if (column->isEmpty() && fx && fx->getOutputConnectionCount() == 0)
      continue;
    SchematicNode *node = addFxSchematicNode(fx);
    if (fx->getAttributes()->isGrouped())
      editedGroup[fx->getAttributes()->getEditingGroupId()].append(node);
  }
  // Add normalFx
  QList<TFx *> fxsToBePlaced;
  for (i = 0; i < fxSet->getFxCount(); i++) {
    TFx *fx         = fxSet->getFx(i);
    TMacroFx *macro = dynamic_cast<TMacroFx *>(fx);
    if (fx->getAttributes()->isGrouped() &&
        !fx->getAttributes()->isGroupEditing()) {
      groupedFxs[fx->getAttributes()->getGroupId()].push_back(fx);
      continue;
    } else if (macro && macro->isEditing()) {
      std::vector<TFxP> fxs = macro->getFxs();
      int j;
      for (j = 0; j < (int)fxs.size(); j++) {
        SchematicNode *node = addFxSchematicNode(fxs[j].getPointer());
        editedMacro[macro].append(node);
        if (fxs[j]->getAttributes()->isGrouped() &&
            macro->getAttributes()->isGroupEditing())
          editedGroup[fx->getAttributes()->getEditingGroupId()].append(node);
      }
      continue;
    }
    fxsToBePlaced.append(fx);
  }
  // sorting fxs so that fxs with specified positions are placed first
  qSort(fxsToBePlaced.begin(), fxsToBePlaced.end(), nodePosDefined);
  for (auto fx : fxsToBePlaced) {
    SchematicNode *node = addFxSchematicNode(fx);
    if (fx->getAttributes()->isGrouped())
      editedGroup[fx->getAttributes()->getEditingGroupId()].append(node);
    TMacroFx *macro = dynamic_cast<TMacroFx *>(fx);
    // If adding an unedited macro and nodes are not yet set, let's position the
    // internal nodes now
    if (macro) {
      double minY           = macro->getAttributes()->getDagNodePos().y;
      double maxX           = macro->getAttributes()->getDagNodePos().x;
      double y              = minY;
      double x              = maxX;
      std::vector<TFxP> fxs = macro->getFxs();
      for (int j = 0; j < (int)fxs.size(); j++) {
        TFx *macroFx = fxs[j].getPointer();
        if (macroFx && !m_placedFxs.contains(macroFx)) {
          placeNodeAndParents(macroFx, x, maxX, minY);
          y -= (m_gridDimension == eLarge ? 100 : 50);
          minY = std::min(y, minY);
        }
      }
    }
  }
  // grouped node
  QMap<int, QList<TFxP>>::const_iterator it;
  for (it = groupedFxs.begin(); it != groupedFxs.end(); it++) {
    FxSchematicNode *node = addGroupedFxSchematicNode(it.key(), it.value());
    TFx *fx               = node->getFx();
    assert(fx);
    int editingGroupId = fx->getAttributes()->getEditingGroupId();
    if (editingGroupId != -1) editedGroup[editingGroupId].append(node);
  }
  keepSubgroup(editedGroup);
  updateEditedGroups(editedGroup);
  updateEditedMacros(editedMacro);
  updateLink();
  m_nodesToPlace.clear();
  updatingScene = false;
}
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/toonzqt/fxschematicscene.h
E:/opentoonz/toonz/sources/toonzqt/fxschematicscene.cpp