opentoonz: TStageObjectDataElement Class Reference
TStageObjectDataElement Class Reference
Public Member Functions
virtual TStageObjectDataElement * clone () const
void storeObject (const TStageObjectId &objectId, TXsheet *xsh)
TStageObjectId restoreObject (TXsheet *xsh, bool copyPosition) const
Protected Attributes
TStageObjectParams * m_params
Stage object parameters (owned)
TPointD m_dagPos
Stage object position in the viewer.
Friends
class StageObjectsData
Detailed Description
Base class used to clone a stage object's relational data inside the stage schematic.
Constructor & Destructor Documentation
TStageObjectDataElement()
TStageObjectDataElement::TStageObjectDataElement ()
    : m_params(0), m_dagPos(TConst::nowhere) {}
~TStageObjectDataElement()
TStageObjectDataElement::~TStageObjectDataElement () virtual
{ delete m_params; }
Member Function Documentation
clone()
TStageObjectDataElement * TStageObjectDataElement::clone () const virtual
Reimplemented in TColumnDataElement.
{
  TStageObjectDataElement *data = new TStageObjectDataElement();
  data->m_params = m_params->clone();
  data->m_dagPos = m_dagPos;
  return data;
}
restoreObject()
TStageObjectId TStageObjectDataElement::restoreObject (TXsheet * xsh, bool copyPosition) const
Restores the object data in the xsheet (TStageObjectDataElement -> TXsheet) and returns the associated new stage object identifier.
{
  // Create the new object to be inserted
  TStageObjectTree *tree = xsh->getStageObjectTree();
  // first, try to maintain object id if it is available
  int index = m_params->m_id.getIndex();
  TStageObject *newObj =
      tree->getStageObject(TStageObjectId::PegbarId(index), false);
  if (!newObj)
    newObj = tree->getStageObject(TStageObjectId::PegbarId(index), true);
  // if the original id is occupied, then use the first unused id
  else {
    index = 0;
    // Search the first unused common (pegbar) id
    while (tree->getStageObject(TStageObjectId::PegbarId(index), false))
      ++index;
    newObj = tree->getStageObject(TStageObjectId::PegbarId(index), true);
  }
  // object-parental relationships will be restored in the function
  // restoreObjects() so we do not set the parent here.
  // newObj->setParent(m_params->m_parentId);
  newObj->assignParams(m_params);
  // If specified, copy the stored position in the viewer
  if (copyPosition) newObj->setDagNodePos(m_dagPos);
  return newObj->getId();
}
References TStageObject::assignParams(), TStageObject::getId(), TStageObjectTree::getStageObject(), TXsheet::getStageObjectTree(), m_dagPos, m_params, and TStageObject::setDagNodePos().
storeObject()
void TStageObjectDataElement::storeObject (const TStageObjectId & objectId, TXsheet * xsh)
Stores the object data strictly regarding the object being part of the schematic stage view (TStageObjectDataElement <- TStageObjectId).
{
  // Search the object in the xsheet (false = don't create a new one)
  TStageObject *obj = xsh->getStageObjectTree()->getStageObject(objId, false);
  assert(obj);
  m_params = obj->getParams();
  m_dagPos = obj->getDagNodePos();
}
References TStageObject::getDagNodePos(), TStageObject::getParams(), TStageObjectTree::getStageObject(), TXsheet::getStageObjectTree(), m_dagPos, and m_params.
Referenced by TColumnDataElement::storeColumn(), and StageObjectsData::storeObjects().
Friends And Related Function Documentation
StageObjectsData
friend class StageObjectsData friend
Member Data Documentation
m_dagPos
TPointD TStageObjectDataElement::m_dagPos protected
Stage object position in the viewer.
Referenced by TColumnDataElement::clone(), TCameraDataElement::restoreCamera(), TColumnDataElement::restoreColumn(), restoreObject(), TCameraDataElement::storeCamera(), and storeObject().
m_params
TStageObjectParams* TStageObjectDataElement::m_params protected
Stage object parameters (owned)
Referenced by TColumnDataElement::clone(), TCameraDataElement::restoreCamera(), TColumnDataElement::restoreColumn(), restoreObject(), TCameraDataElement::storeCamera(), storeObject(), and StageObjectsData::storeSplines().
The documentation for this class was generated from the following file:
E:/opentoonz/toonz/sources/toonzqt/stageobjectsdata.cpp