opentoonz: TSegment Class Reference
TSegment Class Reference
#include <tcurves.h>
Public Member Functions
TSegment (const TPointD &p0, const TPointD &p1)
p0,p1 are the two control points
TSegment (double x0, double y0, double x1, double y1)
TSegment (const TSegment &src)
TPointD getPoint (double t) const
Return the point of segment at parameter t.
TPointD getSpeed (double=0) const
Return speed of segment.
TPointD getP0 () const
Return first control point P0.
TPointD getP1 () const
Return second control point P1.
void setP0 (const TPointD &p)
Set the value of first control point P0 to p.
void setP1 (const TPointD &p)
Set the value of second control point P1 to p.
bool operator== (const TSegment &c) const
bool operator!= (const TSegment &c) const
TRectD getBBox () const
Return rect that contains the segment.
double getLength () const
Return the length of segment.
bool isPoint (double err2=TConsts::epsilon) const
Return true if segment is a point.
Protected Attributes
TPointD m_c0
TPointD m_c1
Detailed Description
TSegment Class to manage a segment
Constructor & Destructor Documentation
TSegment() [1/4]
TSegment::TSegment () inline
: m_c0(), m_c1(){};
TSegment() [2/4]
TSegment::TSegment (const TPointD & p0, const TPointD & p1) inline
p0,p1 are the two control points
: m_c0(p0), m_c1(p1 - p0) {}
TSegment() [3/4]
TSegment::TSegment (double x0, double y0, double x1, double y1) inline
      : m_c0(x0, y0), m_c1(x1 - x0, y1 - y0) {}
TSegment() [4/4]
TSegment::TSegment (const TSegment & src) inline
: m_c0(src.m_c0), m_c1(src.m_c1) {}
Member Function Documentation
getBBox()
TRectD TSegment::getBBox () const inline
Return rect that contains the segment.
{ return TRectD(getP0(), getP1()); }
getLength()
double TSegment::getLength () const inline
Return the length of segment.
{ return norm(m_c1); }
getP0()
TPointD TSegment::getP0 () const inline
Return first control point P0.
{ return m_c0; }
Referenced by TAffine::operator*().
getP1()
TPointD TSegment::getP1 () const inline
Return second control point P1.
{ return m_c0 + m_c1; }
Referenced by TAffine::operator*().
getPoint()
TPointD TSegment::getPoint (double t) const inline
Return the point of segment at parameter t.
{ return m_c0 + t * m_c1; };
getSpeed()
TPointD TSegment::getSpeed (double = 0) const inline
Return speed of segment.
{ return m_c1; };
Referenced by TStroke::getSpeed(), and TStroke::getSpeedTwoValues().
isPoint()
bool TSegment::isPoint (double err2 = TConsts::epsilon) const inline
Return true if segment is a point.
{
    return norm2(m_c1) < err2;
  }
operator!=()
bool TSegment::operator!= (const TSegment & c) const inline
{ return !operator==(c); };
operator==()
bool TSegment::operator== (const TSegment & c) const inline
{
    return m_c0 == c.m_c0 && m_c1 == c.m_c1;
  };
setP0()
void TSegment::setP0 (const TPointD & p) inline
Set the value of first control point P0 to p.
{
    m_c1 += m_c0 - p;
    m_c0 = p;
  }
setP1()
void TSegment::setP1 (const TPointD & p) inline
Set the value of second control point P1 to p.
{ m_c1 = p - m_c0; }
Member Data Documentation
m_c0
TPointD TSegment::m_c0 protected
m_c1
TPointD TSegment::m_c1 protected
The documentation for this class was generated from the following file:
E:/opentoonz/toonz/sources/include/tcurves.h