opentoonz: TImageReaderMesh Class Reference
TImageReaderMesh Class Reference final
Public Member Functions
TImageReaderMesh (const TFilePath &fp, const TFrameId &frameId)
const TImageInfo * getImageInfo () const override
TImageP load () override
Public Member Functions inherited from TImageReader
TImageReader (const TFilePath &path)
virtual const TImageInfo * getImageInfo () const
TFilePath getFilePath () const
TPropertyGroup * getProperties ()
void setProperties (const TPropertyGroup *)
virtual TImageP load ()
void load (const TRasterP &ras, const TPoint &pos=TPoint(0, 0), int shrinkX=1, int shrinkY=1)
virtual TImageP loadIcon ()
void doReadGraytones (bool readThem)
void enable16BitRead (bool is64bitEnabled)
int getShrink () const
void setShrink (int shrink)
void setRegion (TRect rect)
TRect getRegion () const
void getTzpPaletteColorNames (std::map< int, std::pair< std::string, std::string > > &pltColorNames)
Public Member Functions inherited from TSmartObject
TSmartObject (ClassCode classCode)
void addRef ()
void release ()
TINT32 getRefCount () const
Additional Inherited Members
Public Types inherited from TSmartObject
typedef short ClassCode
Static Public Member Functions inherited from TImageReader
static void setSafeModeReadingForTzl (bool activated)
static bool load (const TFilePath &, TRasterP &)
static bool load (const TFilePath &, TImageP &)
static void getSupportedFormats (QStringList &names)
static void define (QString extension, TImageReaderCreateProc *proc)
Static Public Member Functions inherited from TSmartObject
static TINT32 getInstanceCount (ClassCode code)
Protected Member Functions inherited from TImageReader
void open ()
void close ()
bool isOpen () const
Protected Attributes inherited from TImageReader
TFilePath m_path
FILE * m_file
Tiio::Reader * m_reader
Tiio::VectorReader * m_vectorReader
bool m_readGreytones
bool m_is64BitEnabled
int m_shrink
TRect m_region
Static Protected Attributes inherited from TImageReader
static bool m_safeMode = false
Detailed Description
Constructor & Destructor Documentation
TImageReaderMesh()
TImageReaderMesh::TImageReaderMesh (const TFilePath & fp, const TFrameId & frameId)
    : TImageReader(fp), m_fid(frameId) {}
~TImageReaderMesh()
TImageReaderMesh::~TImageReaderMesh () inline
{}
Member Function Documentation
getImageInfo()
const TImageInfo * TImageReaderMesh::getImageInfo () const override virtual
Reimplemented from TImageReader.
{
  if (!m_info.m_valid) {
    // Load info from file
    TFilePath imagePath(this->m_path.withFrame(m_fid));
    TIStream is(imagePath);
    readHeader(is);
  }
  return &m_info;
}
load()
TImageP TImageReaderMesh::load () override virtual
Load Image from disk. If set region then loads only image's region. If set shrink then loads image (or region, if set) with shrink.
Note: if the region, or part of it, is not contained in the image then returns only the intersection between the image and region. If the intersection is void returns TImageP();
Reimplemented from TImageReader.
{
  TMeshImageP mi(new TMeshImage);
  TFilePath imagePath(this->m_path.withFrame(m_fid));
  TIStream is(imagePath);
  readHeader(is);
  mi->setDpi(m_info.m_dpix, m_info.m_dpiy);
  // Meshes
  std::vector<TTextureMeshP> &meshes = mi->meshes();
  std::string tagName;
  while (is.openChild(tagName)) {
    if (tagName == "mesh") {
      meshes.push_back(new TTextureMesh);
      is >> *meshes.back();
      is.closeChild();
    } else
      is.skipCurrentTag();
  }
  return mi;
}
References TIStream::closeChild(), TImageInfo::m_dpix, TImageInfo::m_dpiy, TIStream::openChild(), TIStream::skipCurrentTag(), and TFilePath::withFrame().
The documentation for this class was generated from the following file:
E:/opentoonz/toonz/sources/image/mesh/tiio_mesh.cpp