opentoonz: TRasterFx Class Reference
TRasterFx Class Reference abstract
TRasterFx is the base class for any renderable Toonz Fx.
#include <trasterfx.h>
Classes
class TRasterFxImp
Public Member Functions
virtual bool getBBox (double frame, TRectD &bBox, TPixel32 &bgColor)=0
virtual string getName () const =0
virtual TRect getInvalidRect (const TRect &max)=0
virtual void compute (double frame, const TTile &tile)=0
virtual void allocateAndCompute (double frame, const TDimension size, const TPointD &pos, TTile &tile)
virtual void compute (TTile &tile, double frame, const TRenderSettings &info)
This method supplies the actual fx rendering code.
void allocateAndCompute (TTile &tile, const TPointD &pos, const TDimension &size, TRasterP templateRas, double frame, const TRenderSettings &info)
virtual bool doGetBBox (double frame, TRectD &bBox, const TRenderSettings &info)=0
bool getBBox (double frame, TRectD &bBox, const TRenderSettings &info)
virtual bool isCachable () const
virtual void transform (double frame, int port, const TRectD &rectOnOutput, const TRenderSettings &infoOnOutput, TRectD &rectOnInput, TRenderSettings &infoOnInput)
virtual bool canHandle (const TRenderSettings &info, double frame)=0
virtual TAffine handledAffine (const TRenderSettings &info, double frame)
void enableCache (bool on)
bool isCacheEnabled () const
std::string getAlias (double frame, const TRenderSettings &info) const override
virtual void dryCompute (TRectD &rect, double frame, const TRenderSettings &info)
virtual int getMemoryRequirement (const TRectD &rect, double frame, const TRenderSettings &info)
virtual bool allowUserCacheOnPort (int port)
virtual bool isPlugin () const
Public Member Functions inherited from TFx
virtual std::wstring getName () const
void setName (std::wstring name)
std::wstring getFxId () const
void setFxId (std::wstring id)
TParamContainer * getParams ()
const TParamContainer * getParams () const
void addParamVar (TParamVar *var)
virtual TFx * clone (bool recursive=true) const
TFx * clone (TFx *fx, bool recursive) const
void unlinkParams ()
virtual void linkParams (TFx *src)
TFx * getLinkedFx () const
bool addInputPort (const std::string &name, TFxPort &p)
bool addInputPort (const std::string &name, TFxPort *p, int groupIndex)
bool removeInputPort (const std::string &name)
returns false on duplicate names. Ownership is transferred to the group.
bool renamePort (const std::string &oldName, const std::string &newName)
if not found.
bool connect (const std::string &name, TFx *other)
Equivalent to getInputPort(name)->setFx(other).
bool disconnect (const std::string &name)
Equivalent to getInputPort(name)->setFx(0).
int getInputPortCount () const
TFxPort * getInputPort (int index) const
TFxPort * getInputPort (const std::string &name) const
std::string getInputPortName (int index) const
virtual int dynamicPortGroupsCount () const
virtual const TFxPortDG * dynamicPortGroup (int g) const
bool hasDynamicPortGroups () const
void clearDynamicPortGroup (int g)
bool addOutputConnection (TFxPort *port)
bool removeOutputConnection (TFxPort *port)
virtual bool isZerary () const
virtual int getReferenceColumnIndex () const
virtual TFxPort * getXsheetPort () const
int getOutputConnectionCount () const
TFxPort * getOutputConnection (int i) const
virtual TFxTimeRegion getTimeRegion () const
void setActiveTimeRegion (const TFxTimeRegion &tr)
TFxTimeRegion getActiveTimeRegion () const
virtual bool checkActiveTimeRegion () const
void disconnectAll ()
virtual void getParamUIs (TParamUIConcept *&params, int &length)
std::string getFxType () const
virtual std::string getPluginId () const =0
void onChange (const TParamChange &c) override
void addObserver (TFxObserver *)
void removeObserver (TFxObserver *)
void notify (const TFxChange &change)
void notify (const TFxPortAdded &change)
void notify (const TFxPortRemoved &change)
void notify (const TFxParamAdded &change)
void notify (const TFxParamRemoved &change)
void loadData (TIStream &is) override
void saveData (TOStream &os) override
void loadPreset (TIStream &is)
void savePreset (TOStream &os)
TFxAttributes * getAttributes () const
virtual std::string getAlias (double frame, const TRenderSettings &info) const
virtual void compatibilityTranslatePort (int majorVersion, int minorVersion, std::string &portName)
virtual int getPreferredInputPort ()
virtual void callStartRenderHandler ()
virtual void callEndRenderHandler ()
virtual void callStartRenderFrameHandler (const TRenderSettings *rs, double frame)
virtual void callEndRenderFrameHandler (const TRenderSettings *rs, double frame)
virtual void onObsoleteParamLoaded (const std::string &paramName)
void setFxVersion (int)
int getFxVersion () const
unsigned long getIdentifier () const
void setIdentifier (unsigned long id)
void setNewIdentifier ()
Public Member Functions inherited from TSmartObject
TSmartObject (ClassCode classCode)
void addRef ()
void release ()
TINT32 getRefCount () const
Public Member Functions inherited from TPersist
virtual void loadData (TIStream &is)=0
virtual void saveData (TOStream &os)=0
std::string getStreamTag () const
virtual const TPersistDeclaration * getDeclaration () const =0
virtual void onChange (const TParamChange &)=0
Static Public Member Functions
static TRasterP applyAffine (TTile &tileOut, const TTile &tileIn, const TRenderSettings &info)
static int memorySize (const TRectD &rect, int bpp)
Static Public Member Functions inherited from TFx
static void listFxs (std::vector< TFxInfo > &fxInfos)
static TFxInfo getFxInfo (const std::string &fxIdentifier)
static TFx * create (std::string name)
Static Public Member Functions inherited from TSmartObject
static TINT32 getInstanceCount (ClassCode code)
Static Public Member Functions inherited from TPersist
static void declare (CreateProc *)
static TPersist * create (const std::string &name)
Protected Member Functions
virtual void doCompute (TTile &tile, double frame, const TRenderSettings &settings)=0
virtual void doDryCompute (TRectD &rect, double frame, const TRenderSettings &info)
Friends
class FxResourceBuilder
Additional Inherited Members
Public Types inherited from TFx
typedef TFx * CreateProc()
Public Types inherited from TSmartObject
typedef short ClassCode
Public Types inherited from TPersist
typedef TPersist * CreateProc()
Detailed Description
TRasterFx is the base class for any renderable Toonz Fx.
A standard Toonz Fx is roughly composed of 2 parts: one providing the necessary interface for access by a GUI interface (covered by the TFx class, which this class inherits), the other for the actual computation of the fx - which is the focus of the TRasterFx interface.
So, the essential part of this class lies in the compute() and doCompute() methods that are invoked to perform an fx computation. The former method is the publicly accessed one, while the latter is the one that fx writers must reimplement to supply their rendering code.
The allocateAndCompute() method can be used to automatically allocate the tile to be rendered right before invoking compute().
The dryCompute() / doDryCompute() methods are required by Toonz to perform predictive caching in order to minimize needless recomputations of the same fx. Fx writers must reimplement doDryCompute() to mimic the behaviour of doCompute() in terms of compute() invocations for children fx nodes. Those compute() invocations must be replaced with dryCompute().
The getBBox() / doGetBBox() methods are used to obtain the geometry of the maximal output that an fx can produce with similar inputs to compute(). Again, doCompute() is the method to reimplement by subclasses. Observe that, unlike doCompute() and doDryCompute(), in this case the affine supplied with the render settings must be ignored (see the method itself for further details).
The canHandle() / handledAffine() methods are used by the compute() function to separate the part of an affine that the doCompute() can apply to the result on its own from the rest (which is automatically applied on the fx result using TRasterFx::applyAffine()). Note that every Toonz fx should be able to handle at least the scale part of an affine (applying TRasterFx::applyAffine() on image enlargements typically hampers image quality).
Further methods whose reimplementation depends on the fx itself are getAlias(), which must return a string uniquely descripting a rendered object, and getMemoryRequirement() to declare the amount of memory that will be used by the fx.
Constructor & Destructor Documentation
TRasterFx()
TRasterFx::TRasterFx () inline
{};
~TRasterFx()
TRasterFx::~TRasterFx () inline virtual
{};
Member Function Documentation
allocateAndCompute()
void TRasterFx::allocateAndCompute (TTile & tile, const TPointD & pos, const TDimension & size, TRasterP templateRas, double frame, const TRenderSettings & info)
This is an overloaded member function that deals with the allocation of an input tile before invoking the TRasterFx::compute method on it.
{
  if (templateRas) {
    TRaster32P ras32(templateRas);
    TRaster64P ras64(templateRas);
    templateRas = 0;  // Release the reference to templateRas before allocation
    TRasterP tileRas;
    if (ras32)
      tileRas = TRaster32P(size.lx, size.ly);
    else if (ras64)
      tileRas = TRaster64P(size.lx, size.ly);
    else {
      assert(false);
      return;
    }
    tile.setRaster(tileRas);
  } else {
    if (info.m_bpp == 32) {
      TRaster32P tileRas(size.lx, size.ly);
      tile.setRaster(tileRas);
    } else if (info.m_bpp == 64) {
      TRaster64P tileRas(size.lx, size.ly);
      tile.setRaster(tileRas);
    } else
      assert(false);
  }
  tile.m_pos = pos;
  compute(tile, frame, info);
}
allowUserCacheOnPort()
virtual bool TRasterFx::allowUserCacheOnPort (int port) inline virtual
{ return true; }
applyAffine()
TRasterP TRasterFx::applyAffine (TTile & tileOut, const TTile & tileIn, const TRenderSettings & info) static
{
  TAffine aff = info.m_affine;
  TRasterP src_ras = tileIn.getRaster();
  TRasterP dst_ras = tileOut.getRaster();
  if (aff.isTranslation()) {
    // Check the tile origins' fractionary displacement
    TPointD diff(tileOut.m_pos - tileIn.m_pos - TPointD(aff.a13, aff.a23));
    double fracX = diff.x - tfloor(diff.x);
    double fracY = diff.y - tfloor(diff.y);
    if ((fracX < 0.01 || fracX > 0.99) && (fracY < 0.01 || fracY > 0.99)) {
      // Just copy part of tileIn into tileOut
      TRect geomIn(src_ras->getBounds());
      TRect geomOut(dst_ras->getBounds());
      TPoint diffI(convert(diff));
      geomIn -= diffI;
      geomOut += diffI;
      geomIn *= dst_ras->getBounds();
      geomOut *= src_ras->getBounds();
      if (geomIn.isEmpty()) return dst_ras;
      TRasterP rasIn(src_ras->extract(geomOut));
      TRasterP rasOut(dst_ras->extract(geomIn));
      TRop::copy(rasOut, rasIn);
      return dst_ras;
    }
  }
  TRectD rectIn  = myConvert(src_ras->getBounds()) + tileIn.m_pos;
  TRectD rectOut = myConvert(dst_ras->getBounds()) + tileOut.m_pos;
  TRectD rectInAfter = aff * myConvert(src_ras->getBounds());
  TAffine rasterAff  = TTranslation((aff * rectIn).getP00() - rectOut.getP00() -
                                   rectInAfter.getP00()) *
                      aff;
  TRop::ResampleFilterType qual;
  switch (info.m_quality) {
  case TRenderSettings::StandardResampleQuality:
    qual = TRop::Triangle;
    break;
  case TRenderSettings::ImprovedResampleQuality:
    qual = TRop::Hann2;
    break;
  case TRenderSettings::HighResampleQuality:
    qual = TRop::Hamming3;
    break;
  case TRenderSettings::Triangle_FilterResampleQuality:
    qual = TRop::Triangle;
    break;
  case TRenderSettings::Mitchell_FilterResampleQuality:
    qual = TRop::Mitchell;
    break;
  case TRenderSettings::Cubic5_FilterResampleQuality:
    qual = TRop::Cubic5;
    break;
  case TRenderSettings::Cubic75_FilterResampleQuality:
    qual = TRop::Cubic75;
    break;
  case TRenderSettings::Cubic1_FilterResampleQuality:
    qual = TRop::Cubic1;
    break;
  case TRenderSettings::Hann2_FilterResampleQuality:
    qual = TRop::Hann2;
    break;
  case TRenderSettings::Hann3_FilterResampleQuality:
    qual = TRop::Hann3;
    break;
  case TRenderSettings::Hamming2_FilterResampleQuality:
    qual = TRop::Hamming2;
    break;
  case TRenderSettings::Hamming3_FilterResampleQuality:
    qual = TRop::Hamming3;
    break;
  case TRenderSettings::Lanczos2_FilterResampleQuality:
    qual = TRop::Lanczos2;
    break;
  case TRenderSettings::Lanczos3_FilterResampleQuality:
    qual = TRop::Lanczos3;
    break;
  case TRenderSettings::Gauss_FilterResampleQuality:
    qual = TRop::Gauss;
    break;
  case TRenderSettings::ClosestPixel_FilterResampleQuality:
    qual = TRop::ClosestPixel;
    break;
  case TRenderSettings::Bilinear_FilterResampleQuality:
    qual = TRop::Bilinear;
    break;
  default:
    assert(false);
  }
  TRop::resample(dst_ras, src_ras, rasterAff, qual);
  return dst_ras;
}
compute()
void TRasterFx::compute (TTile & tile, double frame, const TRenderSettings & info) virtual
This method supplies the actual fx rendering code.
{
  // If the render was aborted, avoid everything
  // if(TRenderer::instance().isAborted(TRenderer::renderId()))
  //  throw TException("Render canceled");
  if (checkActiveTimeRegion() && !getActiveTimeRegion().contains(frame)) return;
  if (!getAttributes()->isEnabled() || !m_rasFxImp->isEnabled()) {
    if (getInputPortCount() == 0) return;
    TFxPort *port = getInputPort(0);
    // la porta 0 non deve essere una porta di controllo
    assert(port->isaControlPort() == false);
    if (port->isConnected()) {
      TRasterFxP(port->getFx())->compute(tile, frame, info);
      return;
    }
    return;
  }
  // If the input tile has a fractionary position, it is passed to the
  // rendersettings' accumulated affine. At the same time, the integer part of
  // such affine is transferred to the tile.
  TPoint intTilePos(tfloor(tile.m_pos.x), tfloor(tile.m_pos.y));
  TPointD fracTilePos(tile.m_pos.x - intTilePos.x, tile.m_pos.y - intTilePos.y);
  TPointD fracInfoTranslation(info.m_affine.a13 - fracTilePos.x,
                              info.m_affine.a23 - fracTilePos.y);
  TPoint intInfoTranslation(tfloor(fracInfoTranslation.x),
                            tfloor(fracInfoTranslation.y));
  TPointD newTilePos(intTilePos.x - intInfoTranslation.x,
                     intTilePos.y - intInfoTranslation.y);
  /*--  --*/
  if (tile.m_pos != newTilePos) {
    /*-- RenderSettingsaffine --*/
    TRenderSettings newInfo(info);
    newInfo.m_affine.a13 = fracInfoTranslation.x - intInfoTranslation.x;
    newInfo.m_affine.a23 = fracInfoTranslation.y - intInfoTranslation.y;
    /*--  --*/
    TPointD oldPos(tile.m_pos);
    tile.m_pos = newTilePos;
    compute(tile, frame, newInfo);
    tile.m_pos = oldPos;
    return;
  }
  bool canHandleAffine =
      canHandle(info, frame) || (handledAffine(info, frame) == info.m_affine);
  if (!info.m_affine.isIdentity() && !canHandleAffine) {
    TrFx *transformerFx = new TrFx;
    TFxP locker(transformerFx);
    transformerFx->setFx(this);
    transformerFx->compute(tile, frame, info);
    return;
  }
  // Retrieve tile's geometry
  TRectD tilePlacement = myConvert(tile.getRaster()->getBounds()) + tile.m_pos;
  // Build the fx result alias (in other words, its name)
  std::string alias = getAlias(frame, info) + "[" + ::traduce(info.m_affine) +
                      "][" + std::to_string(info.m_bpp) +
                      "]";  // To be moved below
  TRectD bbox;
  getBBox(frame, bbox, info);
  enlargeToI(bbox);
  TRectD interestingRect(tilePlacement * bbox);
  if (myIsEmpty(interestingRect)) return;
  // Extract the interesting tile from requested one
  TTile interestingTile;
  interestingTile.m_pos = interestingRect.getP00();
  TRect interestingRectI(myConvert(interestingRect - tilePlacement.getP00()));
  interestingTile.setRaster(tile.getRaster()->extract(interestingRectI));
#ifdef DIAGNOSTICS
  // 1. Push fx name on call stack
  QString fxName = QString::fromStdString(getDeclaration()->getId());
  DIAGNOSTICS_PUSH("FName", fxName);
  DIAGNOSTICS_THRSET("FComputeTime", 0);
  TStopWatch sw;
  sw.start();
#endif
  // Invoke the fx-specific computation process
  FxResourceBuilder rBuilder(alias, this, info, frame);
  rBuilder.build(interestingTile);
#ifdef DIAGNOSTICS
  sw.stop();
  QString countsStr("#ftimes.txt | 4. " + fxName + " | 4. Calls count");
  QString fxStr("fcum_4. " + fxName);
  long computeTime      = DIAGNOSTICS_THRGET("FComputeTime");
  long fxTime           = sw.getTotalTime();
  long fxCumulativeTime = DIAGNOSTICS_GLOGET(fxStr);
  long count            = DIAGNOSTICS_GET(countsStr);
  // 2. Add this time to fx time, and subtract it from parent time
  DIAGNOSTICS_GLOADD(fxStr, computeTime);
  DIAGNOSTICS_ADD(countsStr, 1);
  DIAGNOSTICS_SET("#ftimes.txt | 4. " + fxName + " | 3. Mean time",
                  (fxCumulativeTime + computeTime) / (count + 1));
  DIAGNOSTICS_POP("FName", 1);
  QString parentFxName = DIAGNOSTICS_STACKGET("FName");
  if (!parentFxName.isEmpty())
    DIAGNOSTICS_GLOADD("fcum_4. " + parentFxName, -fxTime);
  DIAGNOSTICS_GLOADD("fcum_03. Cached Fxs Retrieval", fxTime - computeTime);
#endif
#ifdef WRITEIMAGES
  static int iCount = 0;
  QString qPath("C:\\butta\\image_" +
                QString::number(++iCount).rightJustified(3, '0') + ".tif");
  TImageWriter::save(TFilePath(qPath.toStdWString()), tile.getRaster());
  if (iCount >= 35) int aa = 1;
#endif
  /*
return;
tryCanceled:
//if(TRenderer::instance().isAborted(TRenderer::renderId()))
//  throw TException("Render canceled");
;
*/
}
References TPersist::getDeclaration(), TStopWatch::getTotalTime(), TRenderSettings::m_affine, and TStopWatch::start().
doDryCompute()
void TRasterFx::doDryCompute (TRectD & rect, double frame, const TRenderSettings & info) protected virtual
Declares the computation scheme of this fx for rendering optimization purposes. This is an important function of the Toonz rendering API, and should be reimplemented with the necessary care. The Toonz rendering process makes use of this function to enact most of the optimization steps about the fx computation, in particular fx caching. A correct implementation of this method should follow these rules: The invocation of child node computations should be faithfully reproduced. TRasterFx::compute and TRasterFx::allocateAndCompute calls have to be translated to TRasterFx::dryCompute calls. This fx is intended for precomputation stage, so the hard rendering code should be skipped here. By default, this method raises a dryCompute call to each input port in increasing order, using the TRasterFx::transform method to identify the tiles to be passed on input precomputation.
Reimplemented in TImageCombinationFx, InFx, OutFx, AtopFx, TMacroFx, PlasticDeformerFx, TLevelColumnFx, BacklitFx, BodyHighLightFx, CornerPinFx, DespeckleFx, ExternalPaletteFx, GlowFx, Iwa_TiledParticlesFx, LinearWaveFx, LocalBlurFx, PaletteFilterFx, ParticlesFx, RandomWaveFx, BaseRaylitFx, RippleFx, TextureFx, WarpFx, TrFx, TimeShuffleFx, ArtContourFx, ErodeDilateFx, FreeDistortBaseFx, KaleidoFx, MosaicFx, ShaderFx, and TBlendForeBackRasterFx.
{
  int inputPortCount = getInputPortCount();
  for (int i = 0; i < inputPortCount; ++i) {
    TFxPort *port = getInputPort(i);
    if (port->isConnected()) {
      TRectD rectOnInput;
      TRenderSettings infoOnInput;
      TRasterFxP fx = port->getFx();
      transform(frame, i, rect, info, rectOnInput, infoOnInput);
      if (!myIsEmpty(rectOnInput))
        fx->dryCompute(rectOnInput, frame, infoOnInput);
    }
  }
}
dryCompute()
void TRasterFx::dryCompute (TRectD & rect, double frame, const TRenderSettings & info) virtual
{
  if (checkActiveTimeRegion() && !getActiveTimeRegion().contains(frame)) return;
  if (!getAttributes()->isEnabled() || !m_rasFxImp->isEnabled()) {
    if (getInputPortCount() == 0) return;
    TFxPort *port = getInputPort(getPreferredInputPort());
    if (port->isConnected())
      TRasterFxP(port->getFx())->dryCompute(rect, frame, info);
    return;
  }
  // If the input tile has a fractionary position, it is passed to the
  // rendersettings' accumulated affine.
  TPoint intTilePos(tfloor(rect.x0), tfloor(rect.y0));
  TPointD fracTilePos(rect.x0 - intTilePos.x, rect.y0 - intTilePos.y);
  TPointD fracInfoTranslation(info.m_affine.a13 - fracTilePos.x,
                              info.m_affine.a23 - fracTilePos.y);
  TPoint intInfoTranslation(tfloor(fracInfoTranslation.x),
                            tfloor(fracInfoTranslation.y));
  TPointD newTilePos(intTilePos.x - intInfoTranslation.x,
                     intTilePos.y - intInfoTranslation.y);
  if (rect.getP00() != newTilePos) {
    TRenderSettings newInfo(info);
    newInfo.m_affine.a13 = fracInfoTranslation.x - intInfoTranslation.x;
    newInfo.m_affine.a23 = fracInfoTranslation.y - intInfoTranslation.y;
    TRectD newRect(newTilePos, rect.getSize());
    dryCompute(newRect, frame, newInfo);
    return;
  }
  // If the fx can't handle the whole affine passed with the TRenderSettings,
  // the part
  // of it that the fx can't handle is retained and applied by an affine
  // transformer fx (TrFx)
  // after the node has been computed.
  bool canHandleAffine =
      canHandle(info, frame) || (handledAffine(info, frame) == info.m_affine);
  if (!info.m_affine.isIdentity() && !canHandleAffine) {
    TrFx *transformerFx = new TrFx;
    TFxP locker(transformerFx);
    transformerFx->setFx(this);
    transformerFx->dryCompute(rect, frame, info);
    return;
  }
  std::string alias = getAlias(frame, info) + "[" + ::traduce(info.m_affine) +
                      "][" + std::to_string(info.m_bpp) + "]";
  int renderStatus =
      TRenderer::instance().getRenderStatus(TRenderer::renderId());
  TFxCacheManager *cacheManager = TFxCacheManager::instance();
  if (renderStatus == TRenderer::FIRSTRUN) {
    TRectD bbox;
    // ret = getBBox... puo' darsi che l'enlarge del trFx (o naturale del bbox)
    // faccia
    // diventare TRectD() non vuoto!!
    getBBox(frame, bbox, info);
    enlargeToI(bbox);
    TRectD interestingRect(rect * bbox);
    if (myIsEmpty(interestingRect)) return;
    // Declare the tile to the tiles manager
    ResourceBuilder::declareResource(alias, this, interestingRect, frame, info);
    doDryCompute(interestingRect, frame, info);
  } else {
    TRectD bbox;
    getBBox(frame, bbox, info);
    enlargeToI(bbox);
    TRectD interestingRect(rect * bbox);
    if (myIsEmpty(interestingRect)) return;
    // Invoke the fx-specific simulation process
    FxResourceBuilder rBuilder(alias, this, info, frame);
    rBuilder.simBuild(interestingRect);
  }
}
enableCache()
void TRasterFx::enableCache (bool on)
{ m_rasFxImp->enableCache(on); }
getAlias()
std::string TRasterFx::getAlias (double frame, const TRenderSettings & info) const override virtual
Reimplemented from TFx.
{
  std::string alias = getFxType();
  alias += "[";
  // alias degli effetti connessi alle porte di input separati da virgole
  // una porta non connessa da luogo a un alias vuoto (stringa vuota)
  int i;
  for (i = 0; i < getInputPortCount(); i++) {
    TFxPort *port = getInputPort(i);
    if (port->isConnected()) {
      TRasterFxP ifx = port->getFx();
      assert(ifx);
      alias += ifx->getAlias(frame, info);
    }
    alias += ",";
  }
  // alias dei valori dei parametri dell'effetto al frame dato
  for (i = 0; i < getParams()->getParamCount(); i++) {
    TParam *param = getParams()->getParam(i);
    alias += param->getName() + "=" + param->getValueAlias(frame, 3);
  }
  alias += "]";
  return alias;
}
getBBox()
bool TRasterFx::getBBox (double frame, TRectD & bBox, const TRenderSettings & info)
{
  bool ret = doGetBBox(frame, bBox, info);
  bBox     = info.m_affine * bBox;
  enlargeToI(bBox);
  return ret;
}
getMemoryRequirement()
int TRasterFx::getMemoryRequirement (const TRectD & rect, double frame, const TRenderSettings & info) virtual
Specifies the approximate size (in MegaBytes) of the maximum allocation instance that this fx will need to perform in order to render the passed input. This method should be reimplemented in order to make the Toonz rendering process aware of the use of big raster memory chunks, at least. Observe that the passed tile geometry is implicitly already allocated <\i> for the fx output.
The default implementation returns 0, assuming that the passed implicit memory size is passed below in node computation without further allocation of resources. Fxs can reimplement this to -1 to explicitly disable the Toonz's smart memory handling.
Note
The rendering process ensures that the passed render settings are handled by the fx before this function is invoked - do not waste code for it.
See also
TRasterFx::memorySize and TRasterFx::canHandle methods.
Reimplemented in BacklitFx, TImageCombinationFx, InFx, OutFx, AtopFx, TLevelColumnFx, BacklitFx, BlurFx, BodyHighLightFx, ColorEmbossFx, CornerPinFx, EmbossFx, ErodeDilateFx, FreeDistortBaseFx, GlowFx, ino_blur, ino_fog, ino_maxmin, ino_median, ino_median_filter, ino_motion_blur, ino_motion_wind, ino_radial_blur, ino_spin_blur, ino_warp_hv, Iwa_TileFx, KaleidoFx, LinearWaveFx, LocalBlurFx, LocalTransparencyFx, MosaicFx, DirectionalBlurBaseFx, NothingFx, PerlinNoiseFx, RadialBlurFx, RandomWaveFx, BaseRaylitFx, RippleFx, SpinBlurFx, TextureFx, TileFx, WarpFx, TrFx, RasterFxPluginHost, and TBlendForeBackRasterFx.
{
  return 0;
}
getName()
virtual string TRasterFx::getName () const pure virtual
Reimplemented from TFx.
handledAffine()
TAffine TRasterFx::handledAffine (const TRenderSettings & info, double frame) virtual
{
  return (info.m_affine.a11 == info.m_affine.a22 && info.m_affine.a12 == 0 &&
          info.m_affine.a21 == 0 && info.m_affine.a13 == 0 &&
          info.m_affine.a23 == 0)
             ? info.m_affine
             : TScale(norm2(info.m_affine));
}
isCachable()
virtual bool TRasterFx::isCachable () const inline virtual
{ return true; }
isCacheEnabled()
bool TRasterFx::isCacheEnabled () const
{ return m_rasFxImp->m_cacheEnabled; }
isPlugin()
virtual bool TRasterFx::isPlugin () const inline virtual
{ return false; };
memorySize()
int TRasterFx::memorySize (const TRectD & rect, int bpp) static
Returns the size (MB) of a tile with passed specs. It can be used to supply the TRasterFx::getMemoryRequirement info. If rect is empty, returns 0.
{
  if (rect.x1 <= rect.x0 || rect.y1 <= rect.y0) return 0;
  return (unsigned long)(rect.getLx() + 1) * (unsigned long)(rect.getLy() + 1) *
             (bpp >> 3) >>
         20;
}
References TRectT< T >::x0.
Referenced by BacklitFx::getMemoryRequirement(), TImageCombinationFx::getMemoryRequirement(), InFx::getMemoryRequirement(), OutFx::getMemoryRequirement(), AtopFx::getMemoryRequirement(), BlurFx::getMemoryRequirement(), BodyHighLightFx::getMemoryRequirement(), ColorEmbossFx::getMemoryRequirement(), CornerPinFx::getMemoryRequirement(), EmbossFx::getMemoryRequirement(), ErodeDilateFx::getMemoryRequirement(), FreeDistortBaseFx::getMemoryRequirement(), GlowFx::getMemoryRequirement(), ino_blur::getMemoryRequirement(), ino_fog::getMemoryRequirement(), ino_maxmin::getMemoryRequirement(), ino_median::getMemoryRequirement(), ino_median_filter::getMemoryRequirement(), ino_motion_blur::getMemoryRequirement(), ino_motion_wind::getMemoryRequirement(), ino_radial_blur::getMemoryRequirement(), ino_spin_blur::getMemoryRequirement(), ino_warp_hv::getMemoryRequirement(), Iwa_TileFx::getMemoryRequirement(), KaleidoFx::getMemoryRequirement(), LinearWaveFx::getMemoryRequirement(), LocalBlurFx::getMemoryRequirement(), LocalTransparencyFx::getMemoryRequirement(), MosaicFx::getMemoryRequirement(), DirectionalBlurBaseFx::getMemoryRequirement(), PerlinNoiseFx::getMemoryRequirement(), RadialBlurFx::getMemoryRequirement(), RandomWaveFx::getMemoryRequirement(), BaseRaylitFx::getMemoryRequirement(), RippleFx::getMemoryRequirement(), SpinBlurFx::getMemoryRequirement(), TextureFx::getMemoryRequirement(), TileFx::getMemoryRequirement(), WarpFx::getMemoryRequirement(), TrFx::getMemoryRequirement(), and TBlendForeBackRasterFx::getMemoryRequirement().
transform()
void TRasterFx::transform (double frame, int port, const TRectD & rectOnOutput, const TRenderSettings & infoOnOutput, TRectD & rectOnInput, TRenderSettings & infoOnInput) virtual
{
  rectOnInput = rectOnOutput;
  infoOnInput = infoOnOutput;
}
Friends And Related Function Documentation
FxResourceBuilder
friend class FxResourceBuilder friend
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/tfxdef.h
E:/opentoonz/toonz/sources/include/trasterfx.h
E:/opentoonz/toonz/sources/tnzbase/trasterfx.cpp