opentoonz: PlasticSkeletonDeformation Class Reference
PlasticSkeletonDeformation Class Reference final
#include <plasticskeletondeformation.h>
Classes
class Imp
Public Types
typedef tcg::any_it< int, int, void * >::bidirectional skelId_iterator
typedef tcg::any_it< std::pair< constQString *, SkVD * >, std::pair< constQString *, SkVD * >, void * >::bidirectional vd_iterator
typedef tcg::any_it< std::pair< int, int >, std::pair< int, int >, void * >::bidirectional vx_iterator
Public Types inherited from TSmartObject
typedef short ClassCode
Public Types inherited from TPersist
typedef TPersist * CreateProc()
Public Member Functions
PlasticSkeletonDeformation ()
Constructs an empty deformation.
PlasticSkeletonDeformation (const PlasticSkeletonDeformation &other)
Constructs a deformation cloning other's skeletons.
PlasticSkeletonDeformation & operator= (const PlasticSkeletonDeformation &other)
bool empty () const
int skeletonsCount () const
void attach (int skeletonId, PlasticSkeleton *skeleton)
void detach (int skeletonId)
Releases the skeleton associated to specified skeletonId.
PlasticSkeletonP skeleton (int skeletonId) const
int skeletonId (PlasticSkeleton *skeleton) const
void skeletonIds (skelId_iterator &begin, skelId_iterator &end) const
Returns the ordered range containing the skeleton ids.
TDoubleParamP skeletonIdsParam () const
Returns the skeleton id by frame animatable parameter.
PlasticSkeletonP skeleton (double frame) const
Returns the active skeleton by xsheet frame.
int skeletonId (double frame) const
Returns the active skeleton id by xsheet frame.
int vertexDeformationsCount () const
SkVD * vertexDeformation (const QString &vertexName) const
SkVD * vertexDeformation (int skelId, int v) const
void vertexDeformations (vd_iterator &begin, vd_iterator &end) const
Returns the ordered range of vertex deformations.
void vdSkeletonVertices (const QString &vertexName, vx_iterator &begin, vx_iterator &end) const
int hookNumber (const QString &name) const
int hookNumber (int skelId, int v) const
QString vertexName (int hookNumber) const
int vertexIndex (int hookNumber, int skelId) const
void addObserver (TParamObserver *observer)
void removeObserver (TParamObserver *observer)
void setGrammar (TSyntax::Grammar *grammar)
void getKeyframeAt (double frame, SkDKey &keysMap) const
void setKeyframe (double frame)
bool setKeyframe (const SkDKey &keyframe)
bool setKeyframe (const SkDKey &keyframe, double frame, double easeIn=-1.0, double easeOut=-1.0)
bool isKeyframe (double frame) const
bool isFullKeyframe (double frame) const
void deleteKeyframe (double frame)
void storeDeformedSkeleton (int skeletonId, double frame, PlasticSkeleton &skeleton) const
void updatePosition (const PlasticSkeleton &originalSkeleton, PlasticSkeleton &deformedSkeleton, double frame, int v, const TPointD &pos)
void updateAngle (const PlasticSkeleton &originalSkeleton, PlasticSkeleton &deformedSkeleton, double frame, int v, const TPointD &pos)
Public Member Functions inherited from TSmartObject
TSmartObject (ClassCode classCode)
void addRef ()
void release ()
TINT32 getRefCount () const
Public Member Functions inherited from TPersist
virtual void loadData (TIStream &is)=0
virtual void saveData (TOStream &os)=0
std::string getStreamTag () const
virtual const TPersistDeclaration * getDeclaration () const =0
Protected Member Functions
void saveData (TOStream &os) override
void loadData (TIStream &is) override
Friends
class PlasticSkeleton
Additional Inherited Members
Static Public Member Functions inherited from TSmartObject
static TINT32 getInstanceCount (ClassCode code)
Static Public Member Functions inherited from TPersist
static void declare (CreateProc *)
static TPersist * create (const std::string &name)
Detailed Description
PlasticSkeletonDeformation models the deformation of a group of PlasticSkeleton instances.
Description
A PlasticSkeleton instance is typically used to act as a deformable object - in other words, it defines the 'original' form of a hierarchy of vertices that can be manipulated interactively to obtain a 'deformed' configuration.
PlasticSkeletonDeformation represents a deformation of PlasticSkeleton objects, therefore acting primarily as a collection of PlasticSkeletonVertexDeformation instances - one per skeleton vertex. The collection is an associative container mapping a vertex name <\I> to its deformation; using names as keys is a useful abstraction that allows vertex deformations data (eg keyframes) to be copied to skeleton deformations whose skeletons have a different internal configuration (ie vertex indices and such).
Each vertex deformation also stores a unique hook number <\I> that can be used during xsheet animation to link stage objects to a skeleton vertex.
The Skeletons group
The PlasticSkeletonDeformation implementation has been extended to work on multiple skeletons for one class instance. This class stores a map associating skeleton indices to the skeleton instances, that can be used to select a skeleton to be deformed with the deformation's data.
Vertices in different skeleton instances share the same animation if their name is the same.
This class provides an animatable parameter that is intended to choose the active skeleton along an xsheet timeline. It is retrievable through the skeletonIdsParam() method.
Notable implementation details
In current implementation, a PlasticSkeletonDeformation keeps shared ownership of the skeletons it is attached to. It is therefore intended to be a container of said skeletons.
Member Typedef Documentation
skelId_iterator
typedef tcg::any_it<int,int,void*>::bidirectional PlasticSkeletonDeformation::skelId_iterator
vd_iterator
typedef tcg::any_it<std::pair<constQString*,SkVD*>,std::pair<constQString*,SkVD*>,void*>::bidirectional PlasticSkeletonDeformation::vd_iterator
vx_iterator
typedef tcg::any_it<std::pair<int,int>,std::pair<int,int>,void*>::bidirectional PlasticSkeletonDeformation::vx_iterator
Constructor & Destructor Documentation
PlasticSkeletonDeformation() [1/2]
PlasticSkeletonDeformation::PlasticSkeletonDeformation ()
Constructs an empty deformation.
    : m_imp(new Imp(this)) {}
PlasticSkeletonDeformation() [2/2]
PlasticSkeletonDeformation::PlasticSkeletonDeformation (const PlasticSkeletonDeformation & other)
Constructs a deformation cloning other's skeletons.
    : TSmartObject(m_classCode), m_imp(new Imp(this, *other.m_imp)) {
  // Register deformation
  SkeletonSet::iterator st, sEnd(m_imp->m_skeletons.end());
  for (st = m_imp->m_skeletons.begin(); st != sEnd; ++st)
    st->get_right()->addListener(this);
}
~PlasticSkeletonDeformation()
PlasticSkeletonDeformation::~PlasticSkeletonDeformation ()
{
  // Unregister deformation
  SkeletonSet::iterator st, sEnd(m_imp->m_skeletons.end());
  for (st = m_imp->m_skeletons.begin(); st != sEnd; ++st)
    st->get_right()->removeListener(this);
}
Member Function Documentation
addObserver()
void PlasticSkeletonDeformation::addObserver (TParamObserver * observer)
{
  m_imp->m_observers.insert(observer);
}
attach()
void PlasticSkeletonDeformation::attach (int skeletonId, PlasticSkeleton * skeleton)
Acquires shared ownership <\I> of the specified skeleton, under given skeletonId
{
  m_imp->attach(skeletonId, skeleton);
  skeleton->addListener(this);
}
Referenced by loadData().
deleteKeyframe()
void PlasticSkeletonDeformation::deleteKeyframe (double frame)
{
  m_imp->m_skelIdsParam->deleteKeyframe(frame);
  SkVDSet::iterator dt, dEnd(m_imp->m_vds.end());
  for (dt = m_imp->m_vds.begin(); dt != dEnd; ++dt)
    dt->m_vd.deleteKeyframe(frame);
}
detach()
void PlasticSkeletonDeformation::detach (int skeletonId)
Releases the skeleton associated to specified skeletonId.
{
  SkeletonSet::left_map::iterator st(m_imp->m_skeletons.left.find(skeletonId));
  if (st != m_imp->m_skeletons.left.end()) {
    st->second->removeListener(this);
    m_imp->detach(skeletonId);
  }
}
empty()
bool PlasticSkeletonDeformation::empty () const
{
  return m_imp->m_skeletons.empty();
}
getKeyframeAt()
void PlasticSkeletonDeformation::getKeyframeAt (double frame, SkDKey & keysMap) const
Note
keysMap returned by argument to avoid map copies in case move semantics is not available
{
  keyframe.m_skelIdKeyframe = m_imp->m_skelIdsParam->getKeyframeAt(frame);
  keyframe.m_vertexKeyframes.clear();
  SkVDSet::const_iterator dt, dEnd(m_imp->m_vds.end());
  for (dt = m_imp->m_vds.begin(); dt != dEnd; ++dt)
    keyframe.m_vertexKeyframes.insert(
        std::make_pair(dt->m_name, dt->m_vd.getKeyframe(frame)));
}
References PlasticSkeletonDeformationKeyframe::m_skelIdKeyframe, and PlasticSkeletonDeformationKeyframe::m_vertexKeyframes.
Referenced by TStageObject::getKeyframe().
hookNumber() [1/2]
int PlasticSkeletonDeformation::hookNumber (const QString & name) const
{
  SkVDSet::const_iterator nt(m_imp->m_vds.find(name));
  return (nt == m_imp->m_vds.end()) ? -1 : nt->m_hookNumber;
}
hookNumber() [2/2]
int PlasticSkeletonDeformation::hookNumber (int skelId, int v) const
{
  const QString &name = skeleton(skelId)->vertex(v).name();
  return hookNumber(name);
}
isFullKeyframe()
bool PlasticSkeletonDeformation::isFullKeyframe (double frame) const
{
  if (!m_imp->m_skelIdsParam->isKeyframe(frame)) return false;
  SkVDSet::const_iterator dt, dEnd(m_imp->m_vds.end());
  for (dt = m_imp->m_vds.begin(); dt != dEnd; ++dt)
    if (!dt->m_vd.isFullKeyframe(frame)) return false;
  return true;
}
isKeyframe()
bool PlasticSkeletonDeformation::isKeyframe (double frame) const
{
  if (m_imp->m_skelIdsParam->isKeyframe(frame)) return true;
  SkVDSet::const_iterator dt, dEnd(m_imp->m_vds.end());
  for (dt = m_imp->m_vds.begin(); dt != dEnd; ++dt)
    if (dt->m_vd.isKeyframe(frame)) return true;
  return false;
}
loadData()
void PlasticSkeletonDeformation::loadData (TIStream & is) override protected virtual
 This is a pure virtual function and must be overridden with a method
that implements the object loading from a stream (i.e take the object's features from a formatted data stream). For example the TStageObject class use his implementation to take the values of the parameters that characterizes a stage object as name, coordinates, etc... from a file. is is an input file stream
Implements TPersist.
{
  if (is.getVersion() < VersionNumber(1, 21)) {
    loadData_prerelease(is);
    return;
  }
  int skeletonId;
  PlasticSkeleton *skeleton;
  std::string tagName;
  while (is.openChild(tagName)) {
    if (tagName == "VertexDeforms") {
      VDKey vKey;
      while (is.openChild(tagName)) {
        if (tagName == "Name")
          is >> vKey.m_name, is.matchEndTag();
        else if (tagName == "Hook")
          is >> vKey.m_hookNumber, is.matchEndTag();
        else if (tagName == "VD") {
          m_imp->touchParams(vKey.m_vd);
          is >> vKey.m_vd, is.matchEndTag();
          m_imp->m_vds.insert(vKey);
          vKey = VDKey();
        } else
          is.skipCurrentTag();
      }
      is.matchEndTag();
    } else if (tagName == "SkelIdsParam")
      is >> *m_imp->m_skelIdsParam, is.matchEndTag();
    else if (tagName == "Skeletons") {
      while (is.openChild(tagName)) {
        if (tagName == "SkelId")
          is >> skeletonId, is.matchEndTag();
        else if (tagName == "Skeleton") {
          skeleton = new PlasticSkeleton;
          is >> *skeleton, is.matchEndTag();
          attach(skeletonId, skeleton);
          skeletonId = 0, skeleton = 0;
        } else
          is.skipCurrentTag();
      }
      is.matchEndTag();
    } else
      is.skipCurrentTag();
  }
}
References attach(), TIStream::getVersion(), TIStream::matchEndTag(), TIStream::openChild(), and TIStream::skipCurrentTag().
operator=()
PlasticSkeletonDeformation & PlasticSkeletonDeformation::operator= (const PlasticSkeletonDeformation & other)
{
  // The meaning of operator= is DIFFERENT from that implemented in the copy
  // constructor.
  // Skeletons are NOT cloned.
  *m_imp = *other.m_imp;
  return *this;
}
removeObserver()
void PlasticSkeletonDeformation::removeObserver (TParamObserver * observer)
{
  m_imp->m_observers.erase(observer);
}
saveData()
void PlasticSkeletonDeformation::saveData (TOStream & os) override protected virtual
 This is a pure virtual function and must be overridden with a method
that implements the object saving to a data stream (i.e put the object's features on a formatted data stream). For example the TStageObject class use his implementation to save the values of the parameters that characterizes a stage object as name, coordinates, etc... on a file os is an output file stream.
Implements TPersist.
{
  // Save skeleton vertex deformations
  os.openChild("VertexDeforms");  // These are saved *before* skeletons
  {                               // ON PURPOSE - in loadData(), we'll
    SkVDSet::iterator vdt,
        vdEnd(m_imp->m_vds.end());  // attach() skeletons to a completely
    for (vdt = m_imp->m_vds.begin(); vdt != vdEnd;
         ++vdt)  // rebuilt set of vertex deformations.
    {
      os.child("Name") << vdt->m_name;
      os.child("Hook") << vdt->m_hookNumber;
      os.child("VD") << vdt->m_vd;
    }
  }
  os.closeChild();
  // Save skeleton ids param
  os.child("SkelIdsParam") << *m_imp->m_skelIdsParam;
  // Save skeletons
  os.openChild("Skeletons");
  {
    SkeletonSet::iterator st, sEnd(m_imp->m_skeletons.end());
    for (st = m_imp->m_skeletons.begin(); st != sEnd; ++st) {
      os.child("SkelId") << st->get_left();
      os.child("Skeleton") << *st->get_right();
    }
  }
  os.closeChild();
}
References TOStream::child(), TOStream::closeChild(), and TOStream::openChild().
setGrammar()
void PlasticSkeletonDeformation::setGrammar (TSyntax::Grammar * grammar)
{
  SkVDSet::iterator vdt, vdEnd(m_imp->m_vds.end());
  for (vdt = m_imp->m_vds.begin(); vdt != vdEnd; ++vdt) {
    SkVD &vd = vdt->m_vd;
    for (int c = 0; c != SkVD::PARAMS_COUNT; ++c)
      vd.m_params[c]->setGrammar(grammar);
  }
  m_imp->m_skelIdsParam->setGrammar(grammar);
  m_imp->m_grammar = grammar;
}
setKeyframe() [1/3]
bool PlasticSkeletonDeformation::setKeyframe (const SkDKey & keyframe)
{
  bool keyWasSet = false;
  if (keyframe.m_skelIdKeyframe.m_isKeyframe) {
    m_imp->m_skelIdsParam->setKeyframe(keyframe.m_skelIdKeyframe);
    keyWasSet = true;
  }
  const std::map<QString, SkVD::Keyframe> &vdKeys = keyframe.m_vertexKeyframes;
  // Iterate the keyframe's vertex deformations
  std::map<QString, SkVD::Keyframe>::const_iterator kt, kEnd(vdKeys.end());
  for (kt = vdKeys.begin(); kt != vdKeys.end(); ++kt) {
    // Search for a corresponding vertex deformation among stored ones
    SkVDSet::iterator vdt = m_imp->m_vds.find(kt->first);
    if (vdt != m_imp->m_vds.end()) {
      // Set the corresponding keyframe
      keyWasSet = vdt->m_vd.setKeyframe(kt->second) || keyWasSet;
    }
  }
  return keyWasSet;
}
setKeyframe() [2/3]
bool PlasticSkeletonDeformation::setKeyframe (const SkDKey & keyframe, double frame, double easeIn = -1.0, double easeOut = -1.0)
{
  bool keyWasSet = false;
  if (keyframe.m_skelIdKeyframe.m_isKeyframe) {
    TDoubleKeyframe kf(keyframe.m_skelIdKeyframe);
    kf.m_frame = frame;
    m_imp->m_skelIdsParam->setKeyframe(kf);
    keyWasSet = true;
  }
  const std::map<QString, SkVD::Keyframe> &vdKeys = keyframe.m_vertexKeyframes;
  // Iterate the keyframe's vertex deformations
  std::map<QString, SkVD::Keyframe>::const_iterator kt, kEnd(vdKeys.end());
  for (kt = vdKeys.begin(); kt != vdKeys.end(); ++kt) {
    // Search for a corresponding vertex deformation among stored ones
    SkVDSet::iterator vdt = m_imp->m_vds.find(kt->first);
    if (vdt != m_imp->m_vds.end()) {
      // Set the corresponding keyframe
      keyWasSet = vdt->m_vd.setKeyframe(kt->second, frame, easeIn, easeOut) ||
                  keyWasSet;
    }
  }
  return keyWasSet;
}
setKeyframe() [3/3]
void PlasticSkeletonDeformation::setKeyframe (double frame)
{
  m_imp->m_skelIdsParam->setKeyframe(frame);
  SkVDSet::iterator dt, dEnd(m_imp->m_vds.end());
  for (dt = m_imp->m_vds.begin(); dt != dEnd; ++dt) dt->m_vd.setKeyframe(frame);
}
skeleton() [1/2]
PlasticSkeletonP PlasticSkeletonDeformation::skeleton (double frame) const
Returns the active skeleton by xsheet frame.
{
  return skeleton(skeletonId(frame));
}
skeleton() [2/2]
PlasticSkeletonP PlasticSkeletonDeformation::skeleton (int skeletonId) const
{
  SkeletonSet::left_map::const_iterator st =
      m_imp->m_skeletons.left.find(skeletonId);
  return (st == m_imp->m_skeletons.left.end()) ? PlasticSkeletonP()
                                               : st->second;
}
skeletonId() [1/2]
int PlasticSkeletonDeformation::skeletonId (double frame) const
Returns the active skeleton id by xsheet frame.
{
  return m_imp->m_skelIdsParam->getValue(frame);
}
skeletonId() [2/2]
int PlasticSkeletonDeformation::skeletonId (PlasticSkeleton * skeleton) const
{
  SkeletonSet::right_map::const_iterator st =
      m_imp->m_skeletons.right.find(skeleton);
  return (st == m_imp->m_skeletons.right.end())
             ? -(std::numeric_limits<int>::max)()
             : st->second;
}
skeletonIds()
void PlasticSkeletonDeformation::skeletonIds (skelId_iterator & begin, skelId_iterator & end) const
Returns the ordered range containing the skeleton ids.
{
  auto const f = [](const SkeletonSet::left_map::value_type &val) {
    return val.first;
  };
  begin = boost::make_transform_iterator(m_imp->m_skeletons.left.begin(), f);
  end   = boost::make_transform_iterator(m_imp->m_skeletons.left.end(), f);
}
skeletonIdsParam()
TDoubleParamP PlasticSkeletonDeformation::skeletonIdsParam () const
Returns the skeleton id by frame animatable parameter.
{
  return m_imp->m_skelIdsParam;
}
skeletonsCount()
int PlasticSkeletonDeformation::skeletonsCount () const
{
  return m_imp->m_skeletons.size();
}
storeDeformedSkeleton()
void PlasticSkeletonDeformation::storeDeformedSkeleton (int skeletonId, double frame, PlasticSkeleton & skeleton) const
{
  // Copy the un-deformed skeleton to the output one
  const PlasticSkeletonP &origSkel = this->skeleton(skelId);
  skeleton                         = origSkel ? *origSkel : PlasticSkeleton();
  // Update the skeleton to the specified frame
  if (!skeleton.vertices().empty())
    m_imp->updateBranchPositions(*origSkel, skeleton, frame,
                                 skeleton.vertices().begin().m_idx);
}
updateAngle()
void PlasticSkeletonDeformation::updateAngle (const PlasticSkeleton & originalSkeleton, PlasticSkeleton & deformedSkeleton, double frame, int v, const TPointD & pos)
{
  const PlasticSkeletonVertex &vx = deformedSkeleton.vertex(v);
  int vParent                     = vx.parent();
  const TPointD &vParentPos = deformedSkeleton.vertex(vParent).P();
  // No need to access the grandParent, we're making the diff against the old vx
  // position
  SkVD &vd = m_imp->m_vds.find(vx.name())->m_vd;
  double aDelta = tcg::point_ops::angle(vx.P() - vParentPos, pos - vParentPos) *
                  M_180_PI,
         a = tcrop(vd.m_params[SkVD::ANGLE]->getValue(frame) + aDelta,
                   vx.m_minAngle, vx.m_maxAngle);
  vd.m_params[SkVD::ANGLE]->setValue(frame, a);
  m_imp->updateBranchPositions(originalSkeleton, deformedSkeleton, frame, v);
}
updatePosition()
void PlasticSkeletonDeformation::updatePosition (const PlasticSkeleton & originalSkeleton, PlasticSkeleton & deformedSkeleton, double frame, int v, const TPointD & pos)
{
  const PlasticSkeletonVertex &vx = deformedSkeleton.vertex(v);
  int vParent                     = vx.parent();
  const TPointD &vParentPos = deformedSkeleton.vertex(vParent).P();
  const TPointD &vPos       = deformedSkeleton.vertex(v).P();
  SkVD &vd = m_imp->m_vds.find(vx.name())->m_vd;
  // NOTE: The following aDelta calculation should be done as a true difference
  // - this is still ok and spares
  // access to v's grandParent...
  double aDelta = tcg::point_ops::angle(vPos - vParentPos, pos - vParentPos) *
                  M_180_PI,
         dDelta = tcg::point_ops::dist(vParentPos, pos) -
                  tcg::point_ops::dist(vParentPos, vPos),
         a = tcrop(vd.m_params[SkVD::ANGLE]->getValue(frame) + aDelta,
                   vx.m_minAngle, vx.m_maxAngle),
         d = vd.m_params[SkVD::DISTANCE]->getValue(frame) + dDelta;
  vd.m_params[SkVD::ANGLE]->setValue(frame, a);
  vd.m_params[SkVD::DISTANCE]->setValue(frame, d);
  m_imp->updateBranchPositions(originalSkeleton, deformedSkeleton, frame, v);
}
vdSkeletonVertices()
void PlasticSkeletonDeformation::vdSkeletonVertices (const QString & vertexName, vx_iterator & begin, vx_iterator & end) const
Returns the ordered range of skeleton vertices (at max one per skeleton id) associated to a vertex name
{
  auto const f = [](const std::map<int, int>::value_type &val) {
    return std::make_pair(val.first, val.second);
  };
  SkVDSet::const_iterator nt(m_imp->m_vds.find(vertexName));
  if (nt == m_imp->m_vds.end()) {
    begin = vx_iterator();
    end   = vx_iterator();
  } else {
    begin = boost::make_transform_iterator(nt->m_vIndices.begin(), f);
    end   = boost::make_transform_iterator(nt->m_vIndices.end(), f);
  }
}
Referenced by PlasticTool::onPropertyChanged().
vertexDeformation() [1/2]
SkVD * PlasticSkeletonDeformation::vertexDeformation (const QString & vertexName) const
Returns the vertex deformation associated to given vertex name. The returned pointer is owned by the deformation - it must not be deleted <\I>
{
  SkVDSet::const_iterator vdt = m_imp->m_vds.find(vxName);
  return (vdt == m_imp->m_vds.end()) ? (SkVD *)0 : &vdt->m_vd;
}
vertexDeformation() [2/2]
SkVD * PlasticSkeletonDeformation::vertexDeformation (int skelId, int v) const
{
  const QString &name = skeleton(skelId)->vertex(v).name();
  return vertexDeformation(name);
}
vertexDeformations()
void PlasticSkeletonDeformation::vertexDeformations (vd_iterator & begin, vd_iterator & end) const
Returns the ordered range of vertex deformations.
{
  auto const f = [](const VDKey &vdKey) {
    return std::make_pair(&vdKey.m_name, &vdKey.m_vd);
  };
  begin = boost::make_transform_iterator(m_imp->m_vds.begin(), f);
  end   = boost::make_transform_iterator(m_imp->m_vds.end(), f);
}
vertexDeformationsCount()
int PlasticSkeletonDeformation::vertexDeformationsCount () const
{
  return m_imp->m_vds.size();
}
vertexIndex()
int PlasticSkeletonDeformation::vertexIndex (int hookNumber, int skelId) const
{
  const SkVDByHookNumber &vds = m_imp->m_vds.get<int>();
  SkVDByHookNumber::const_iterator ht(vds.find(hookNumber));
  if (ht == vds.end()) return -1;
  std::map<int, int>::const_iterator st(ht->m_vIndices.find(skelId));
  return (st == ht->m_vIndices.end()) ? -1 : st->second;
}
vertexName()
QString PlasticSkeletonDeformation::vertexName (int hookNumber) const
{
  const SkVDByHookNumber &vds = m_imp->m_vds.get<int>();
  SkVDByHookNumber::const_iterator ht(vds.find(hookNumber));
  return (ht == vds.end()) ? QString() : ht->m_name;
}
Friends And Related Function Documentation
PlasticSkeleton
friend class PlasticSkeleton friend
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/ext/plasticskeletondeformation.h
E:/opentoonz/toonz/sources/tnzext/plasticskeletondeformation.cpp