opentoonz: Toolbar Class Reference
Toolbar Class Reference final
Public Member Functions
Toolbar (QWidget *parent, bool isVertical=true)
Protected Slots
void onToolChanged ()
void onPreferenceChanged (const QString &prefName)
void setIsExpanded (bool expand)
void updateToolbar ()
Protected Member Functions
bool addAction (QAction *act)
void showEvent (QShowEvent *e) override
void hideEvent (QHideEvent *e) override
Detailed Description
Constructor & Destructor Documentation
Toolbar()
Toolbar::Toolbar (QWidget * parent, bool isVertical = true)
    : QToolBar(parent), m_isExpanded(ShowAllToolsToggle != 0) {
  // Fondamentale per lo style sheet
  setObjectName("toolBar");
  setMovable(false);
  if (isVertical)
    setOrientation(Qt::Vertical);
  else
    setOrientation(Qt::Horizontal);
  setIconSize(QSize(20, 20));
  setToolButtonStyle(Qt::ToolButtonIconOnly);
  m_expandButton = new QToolButton(this);
  m_expandButton->setObjectName("expandButton");
  m_expandButton->setCheckable(true);
  m_expandButton->setChecked(m_isExpanded);
  m_expandButton->setArrowType((isVertical) ? Qt::DownArrow : Qt::RightArrow);
  m_expandAction = addWidget(m_expandButton);
  connect(m_expandButton, SIGNAL(toggled(bool)), this,
          SLOT(setIsExpanded(bool)));
  updateToolbar();
}
~Toolbar()
Toolbar::~Toolbar ()
{}
Member Function Documentation
addAction()
bool Toolbar::addAction (QAction * act) protected
{
  if (!act) return false;
  QToolBar::addAction(act);
  return true;
}
hideEvent()
void Toolbar::hideEvent (QHideEvent * e) override protected
{
  disconnect(TApp::instance()->getCurrentLevel(), 0, this, 0);
  disconnect(TApp::instance()->getCurrentTool(), SIGNAL(toolSwitched()), this,
             SLOT(onToolChanged()));
  disconnect(TApp::instance()->getCurrentColumn(),
             SIGNAL(columnIndexSwitched()), this, SLOT(updateToolbar()));
  disconnect(TApp::instance()->getCurrentFrame(), SIGNAL(frameSwitched()), this,
             SLOT(updateToolbar()));
  disconnect(TApp::instance()->getCurrentFrame(), SIGNAL(frameTypeChanged()),
             this, SLOT(updateToolbar()));
  disconnect(TApp::instance()->getCurrentXsheet(), SIGNAL(xsheetChanged()),
             this, SLOT(updateToolbar()));
  disconnect(TApp::instance()->getCurrentScene(),
             SIGNAL(preferenceChanged(const QString &)), this,
             SLOT(onPreferenceChanged(const QString &)));
}
onPreferenceChanged
void Toolbar::onPreferenceChanged (const QString & prefName) protected slot
{
  if (prefName == "ToolbarDisplay" || prefName.isEmpty()) updateToolbar();
}
onToolChanged
void Toolbar::onToolChanged () protected slot
{
  ToolHandle *toolHandle = TApp::instance()->getCurrentTool();
  TTool *tool            = toolHandle->getTool();
  std::string toolName   = tool->getName();
  QAction *act = CommandManager::instance()->getAction(toolName.c_str());
  if (!act || act->isChecked()) return;
  act->setChecked(true);
}
setIsExpanded
void Toolbar::setIsExpanded (bool expand) protected slot
{
  m_isExpanded       = expand;
  ShowAllToolsToggle = (expand) ? 1 : 0;
  updateToolbar();
}
showEvent()
void Toolbar::showEvent (QShowEvent * e) override protected
{
  TColumnHandle *columnHandle = TApp::instance()->getCurrentColumn();
  connect(columnHandle, SIGNAL(columnIndexSwitched()), this,
          SLOT(updateToolbar()));
  TFrameHandle *frameHandle = TApp::instance()->getCurrentFrame();
  connect(frameHandle, SIGNAL(frameSwitched()), this, SLOT(updateToolbar()));
  connect(frameHandle, SIGNAL(frameTypeChanged()), this, SLOT(updateToolbar()));
  TXsheetHandle *xsheetHandle = TApp::instance()->getCurrentXsheet();
  connect(xsheetHandle, SIGNAL(xsheetChanged()), this, SLOT(updateToolbar()));
  connect(TApp::instance()->getCurrentTool(), SIGNAL(toolSwitched()),
          SLOT(onToolChanged()));
  TXshLevelHandle *levelHandle = TApp::instance()->getCurrentLevel();
  connect(levelHandle, SIGNAL(xshLevelSwitched(TXshLevel *)), this,
          SLOT(updateToolbar()));
  connect(TApp::instance()->getCurrentScene(),
          SIGNAL(preferenceChanged(const QString &)), this,
          SLOT(onPreferenceChanged(const QString &)));
}
updateToolbar
void Toolbar::updateToolbar () protected slot
Layout the tool buttons according to the state of the expandButton
{
  TApp *app                 = TApp::instance();
  TFrameHandle *frameHandle = app->getCurrentFrame();
  if (frameHandle->isPlaying()) return;
  TXshLevelHandle *currlevel = app->getCurrentLevel();
  TXshLevel *level           = currlevel ? currlevel->getLevel() : 0;
  int levelType              = level ? level->getType() : NO_XSHLEVEL;
  TColumnHandle *colHandle = app->getCurrentColumn();
  int colIndex             = colHandle->getColumnIndex();
  int rowIndex = frameHandle->getFrameIndex();
  if (Preferences::instance()->isAutoCreateEnabled() &&
      Preferences::instance()->isAnimationSheetEnabled()) {
    // If in an empty cell, find most recent level
    if (levelType == NO_XSHLEVEL) {
      TXsheetHandle *xshHandle = app->getCurrentXsheet();
      TXsheet *xsh             = xshHandle->getXsheet();
      if (colIndex >= 0 && !xsh->isColumnEmpty(colIndex)) {
        int r0, r1;
        xsh->getCellRange(colIndex, r0, r1);
        if (0 <= r0 && r0 <= r1) {
          // level type depends on previous occupied cell
          for (int r = std::min(r1, rowIndex); r >= r0; r--) {
            TXshCell cell = xsh->getCell(r, colIndex);
            if (cell.isEmpty()) continue;
            levelType = cell.m_level->getType();
            rowIndex  = r;
            break;
          }
          if (levelType == NO_XSHLEVEL) {
            TXshCell cell = xsh->getCell(r0, colIndex);
            levelType     = cell.m_level->getType();
            rowIndex      = r0;
          }
        }
      }
    }
  }
  m_toolbarLevel = levelType;
  TTool::ToolTargetType targetType = TTool::NoTarget;
  switch (m_toolbarLevel) {
  case OVL_XSHLEVEL:
    targetType = TTool::RasterImage;
    break;
  case TZP_XSHLEVEL:
    targetType = TTool::ToonzImage;
    break;
  case PLI_XSHLEVEL:
  default:
    targetType = TTool::VectorImage;
    break;
  case MESH_XSHLEVEL:
    targetType = TTool::MeshImage;
    break;
  }
  // Hide action for now
  for (int idx = 0; buttonLayout[idx].toolName; idx++) {
    if (buttonLayout[idx].action) removeAction(buttonLayout[idx].action);
  }
  removeAction(m_expandAction);
  int levelBasedDisplay = Preferences::instance()->getLevelBasedToolsDisplay();
  bool actionEnabled     = false;
  ToolHandle *toolHandle = TApp::instance()->getCurrentTool();
  for (int idx = 0; buttonLayout[idx].toolName; idx++) {
    TTool *tool = TTool::getTool(buttonLayout[idx].toolName, targetType);
    if (tool) tool->updateEnabled(rowIndex, colIndex);
    bool isSeparator = !strncmp(buttonLayout[idx].toolName, "Separator", 9);
    bool enable =
        !levelBasedDisplay ? true : (!tool ? actionEnabled : tool->isEnabled());
    // Plastic tool should always be available so you can create a mesh
    if (!enable && !strncmp(buttonLayout[idx].toolName, T_Plastic, 9) &&
        (m_toolbarLevel & LEVELCOLUMN_XSHLEVEL))
      enable = true;
    if (!m_isExpanded && buttonLayout[idx].collapsible) continue;
    if (!buttonLayout[idx].action) {
      if (isSeparator)
        buttonLayout[idx].action = addSeparator();
      else
        buttonLayout[idx].action =
            CommandManager::instance()->getAction(buttonLayout[idx].toolName);
    }
    if (levelBasedDisplay != 2)
      buttonLayout[idx].action->setEnabled(enable);
    else if (!enable)
      continue;
    actionEnabled = addAction(buttonLayout[idx].action) || actionEnabled;
    if (isSeparator) actionEnabled = false;
  }
  addAction(m_expandAction);
  if (m_isExpanded) {
    m_expandButton->setArrowType(
        (orientation() == Qt::Vertical) ? Qt::UpArrow : Qt::LeftArrow);
    m_expandButton->setToolTip(tr("Collapse toolbar"));
  } else {
    m_expandButton->setArrowType(
        (orientation() == Qt::Vertical) ? Qt::DownArrow : Qt::RightArrow);
    m_expandButton->setToolTip(tr("Expand toolbar"));
  }
  update();
}
References TXsheet::getCell(), TXsheet::getCellRange(), TApp::getCurrentColumn(), TApp::getCurrentFrame(), TApp::getCurrentLevel(), TApp::getCurrentTool(), TApp::getCurrentXsheet(), TXshLevel::getType(), TApp::instance(), TXsheet::isColumnEmpty(), TXshCell::isEmpty(), TTool::MeshImage, TTool::RasterImage, TTool::ToonzImage, TTool::updateEnabled(), and TTool::VectorImage.
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/toonz/toolbar.h
E:/opentoonz/toonz/sources/toonz/toolbar.cpp