opentoonz: FunctionTreeModel::Channel Class Reference
FunctionTreeModel::Channel Class Reference final
The model item representing a channel (i.e. a real-valued function).
#include <functiontreeviewer.h>
Public Member Functions
Channel (FunctionTreeModel *model, TDoubleParam *param, std::string paramNamePrefix="", std::wstring fxId=L"")
TDoubleParam * getParam () const
void setParam (const TParamP &param) override
QString getShortName () const
QString getLongName () const
QString getExprRefName () const
ChannelGroup * getChannelGroup () const
void setChannelGroup (ChannelGroup *group)
QVariant data (int role) const override
bool isActive () const override
void setIsActive (bool active)
bool isAnimated () const override
bool isIgnored () const override
bool isCurrent () const
void setIsCurrent (bool current)
bool isHidden () const
void onChange (const TParamChange &) override
void * getInternalPointer () const override
see setChildren() below
Public Member Functions inherited from FunctionTreeModel::ParamWrapper
ParamWrapper (const TParamP &param, const std::wstring &fxId)
const std::wstring & getFxId () const
TParamP getParam () const
virtual void setParam (const TParamP &param)
virtual bool isActive () const =0
virtual bool isAnimated () const =0
virtual bool isIgnored () const =0
Public Member Functions inherited from TreeModel::Item
Item * getParent () const
int getChildCount () const
Item * getChild (int row) const
Item * appendChild (Item *child)
virtual void * getInternalPointer () const
see setChildren() below
void setChildren (QList< Item * > &children)
virtual void refresh ()
TreeModel * getModel () const
void setModel (TreeModel *model)
int getRow () const
row is the Item index in the parent. (used by QModelIndex)
void setRow (int row)
int getDepth () const
root_depth == 0; son_depth == parent_depth + 1
bool isOpen () const
void setIsOpen (bool opened)
virtual QVariant data (int role) const
QModelIndex createIndex ()
virtual void onChange (const TParamChange &)=0
Additional Inherited Members
Protected Attributes inherited from FunctionTreeModel::ParamWrapper
TParamP m_param
The wrapped parameter.
std::wstring m_fxId
Fx identifier for m_param's owner, if any.
Detailed Description
The model item representing a channel (i.e. a real-valued function).
Constructor & Destructor Documentation
Channel()
FunctionTreeModel::Channel::Channel (FunctionTreeModel * model, TDoubleParam * param, std::string paramNamePrefix = "", std::wstring fxId = L"")
    : ParamWrapper(param, fxId)
    , m_model(model)
    , m_group(0)
    , m_isActive(false)
    , m_paramNamePref(paramNamePref) {}
~Channel()
FunctionTreeModel::Channel::~Channel ()
{
  m_model->onChannelDestroyed(this);
  if (m_isActive) getParam()->removeObserver(this);
}
Member Function Documentation
data()
QVariant FunctionTreeModel::Channel::data (int role) const override virtual
used by TreeModel::data(); default implementation provides open/close folder icons
Reimplemented from TreeModel::Item.
{
  if (role == Qt::DecorationRole) {
    static QIcon paramAnimOn(":Resources/paramanim_on.svg");
    static QIcon paramAnimOff(":Resources/paramanim_off.svg");
    static QIcon paramOn(":Resources/param_on.svg");
    static QIcon paramOff(":Resources/param_off.svg");
    static QIcon paramIgnoredOn(":Resources/paramignored_on.svg");
    static QIcon paramIgnoredOff(":Resources/paramignored_off.svg");
    if (isIgnored()) return isActive() ? paramIgnoredOn : paramIgnoredOff;
    return m_param->hasKeyframes() ? isActive() ? paramAnimOn : paramAnimOff
                                   : isActive() ? paramOn : paramOff;
  } else if (role == Qt::DisplayRole) {
    if (m_param->hasUILabel()) {
      return QString::fromStdString(m_param->getUILabel());
    }
    std::string name            = m_paramNamePref + m_param->getName();
    std::wstring translatedName = TStringTable::translate(name);
    if (m_fxId.size() > 0)
      return QString::fromStdWString(translatedName + L" (" + m_fxId + L")");
    return QString::fromStdWString(translatedName);
  } else if (role == Qt::ForegroundRole) {
    // 130221 iwasawa
    FunctionTreeView *view = dynamic_cast<FunctionTreeView *>(m_model->m_view);
    if (!view)
#if QT_VERSION >= 0x050000
      return QColor(Qt::black);
#else
      return Qt::black;
#endif
    return (isCurrent()) ? view->getViewer()->getCurrentTextColor()
                         : view->getTextColor();
  } else if (role == Qt::ToolTipRole) {
    if (m_param->hasKeyframes()) {
      TDoubleParam *dp = dynamic_cast<TDoubleParam *>(m_param.getPointer());
      FunctionTreeView *view =
          dynamic_cast<FunctionTreeView *>(m_model->m_view);
      if (dp && view &&
          view->getXsheetHandle()->getXsheet()->isReferenceManagementIgnored(
              dp))
        return tr(
            "Some key(s) in this parameter loses original reference in "
            "expression.\nManually changing any keyframe will clear the "
            "warning.");
    }
    return TreeModel::Item::data(role);
  } else
    return TreeModel::Item::data(role);
}
References TreeModel::Item::data().
getChannelGroup()
ChannelGroup * FunctionTreeModel::Channel::getChannelGroup () const inline
{ return m_group; }
getExprRefName()
QString FunctionTreeModel::Channel::getExprRefName () const
in order to show the expression name in the tooltip
{
  QString tmpName;
  if (m_param->hasUILabel())
    tmpName = QString::fromStdString(m_param->getUILabel());
  else
    tmpName = QString::fromStdWString(
        TStringTable::translate(m_paramNamePref + m_param->getName()));
  /*--- stage
   * objectパラメータの場合、TableにあわせてtmpNameを代表的なExpression名にする---*/
  StageObjectChannelGroup *stageGroup =
      dynamic_cast<StageObjectChannelGroup *>(m_group);
  if (stageGroup) {
    if (tmpName == "Y")
      tmpName = "y";
    else if (tmpName == "X")
      tmpName = "x";
    else if (tmpName == "Z")
      tmpName = "z";
    else if (tmpName == "Rotation")
      tmpName = "rot";
    else if (tmpName == "Scale H")
      tmpName = "sx";
    else if (tmpName == "Scale V")
      tmpName = "sy";
    else if (tmpName == "Shear H")
      tmpName = "shx";
    else if (tmpName == "Shear V")
      tmpName = "shy";
    else if (tmpName == "posPath")
      tmpName = "path";
    else if (tmpName == "Scale")
      tmpName = "sc";
    else
      tmpName = tmpName.toLower();
    return stageGroup->getIdName() + QString(".") + tmpName;
  }
  // expression for fx parameters
  // see txsheetexpr.cpp for generation of actual tokens
  tmpName.remove(QChar(' '), Qt::CaseInsensitive);
  tmpName.remove(QChar('/'));
  tmpName.remove(QChar('-'));
  tmpName = tmpName.toLower();
  FunctionTreeModel::ChannelGroup *parentGroup =
      dynamic_cast<FunctionTreeModel::ChannelGroup *>(getParent());
  if (parentGroup) {
    return QString("fx.") + parentGroup->getIdName() + QString(".") + tmpName;
  } else
    return "";
}
Referenced by FunctionSheet::getSelectedParamName(), and FunctionSheetColumnHeadViewer::mouseMoveEvent().
getInternalPointer()
void * FunctionTreeModel::Channel::getInternalPointer () const override virtual
see setChildren() below
Reimplemented from TreeModel::Item.
{
  return this->m_param.getPointer();
}
getLongName()
QString FunctionTreeModel::Channel::getLongName () const
{
  QString name = getShortName();
  if (getChannelGroup()) name = getChannelGroup()->getLongName() + " " + name;
  return name;
}
getParam()
TDoubleParam * FunctionTreeModel::Channel::getParam () const inline
{
      return (TDoubleParam *)m_param.getPointer();
    }
getShortName()
QString FunctionTreeModel::Channel::getShortName () const
{
  if (m_param->hasUILabel()) {
    return QString::fromStdString(m_param->getUILabel());
  }
  std::string name            = m_paramNamePref + m_param->getName();
  std::wstring translatedName = TStringTable::translate(name);
  return QString::fromStdWString(translatedName);
}
isActive()
bool FunctionTreeModel::Channel::isActive () const inline override virtual
Implements FunctionTreeModel::Item.
{ return m_isActive; }
isAnimated()
bool FunctionTreeModel::Channel::isAnimated () const override virtual
Implements FunctionTreeModel::Item.
{
  return m_param->hasKeyframes();
}
isCurrent()
bool FunctionTreeModel::Channel::isCurrent () const
{
  return m_model->m_currentChannel == this;
}
isHidden()
bool FunctionTreeModel::Channel::isHidden () const
{
  return getChannelGroup()->getShowFilter() ==
             ChannelGroup::ShowAnimatedChannels &&
         !getParam()->hasKeyframes();
}
isIgnored()
bool FunctionTreeModel::Channel::isIgnored () const override virtual
Implements FunctionTreeModel::Item.
{
  if (!isAnimated()) return false;
  TDoubleParam *dp = dynamic_cast<TDoubleParam *>(m_param.getPointer());
  if (!dp) return false;
  FunctionTreeView *view = dynamic_cast<FunctionTreeView *>(m_model->m_view);
  if (!view) return false;
  return view->getXsheetHandle()->getXsheet()->isReferenceManagementIgnored(dp);
}
onChange()
void FunctionTreeModel::Channel::onChange (const TParamChange & ch) override virtual
Implements TParamObserver.
{
  m_model->onChange(ch);
}
setChannelGroup()
void FunctionTreeModel::Channel::setChannelGroup (ChannelGroup * group) inline
{ m_group = group; }
setIsActive()
void FunctionTreeModel::Channel::setIsActive (bool active)
{
  if (active == m_isActive) return;
  m_isActive = active;
  m_model->refreshActiveChannels();
  if (m_isActive) {
    getParam()->addObserver(this);
    /*--- これが最初にVisibleにしたChannelの場合 ---*/
    if (!m_model->m_currentChannel) {
      setIsCurrent(true);
      m_model->emitCurveSelected(getParam());
    }
  } else {
    getParam()->removeObserver(this);
    if (isCurrent()) {
      setIsCurrent(false);
      m_model->emitCurveSelected(0);
    }
  }
  m_model->emitDataChanged(this);
}
setIsCurrent()
void FunctionTreeModel::Channel::setIsCurrent (bool current)
{
  Channel *oldCurrent = m_model->m_currentChannel;
  if (current) {
    // this channel must become the current
    if (oldCurrent == this) return;  // already it is: nothing to do
    m_model->m_currentChannel = this;
    // change the current fx if the FxChannelGroup is clicked
    FxChannelGroup *fxGroup = dynamic_cast<FxChannelGroup *>(m_group);
    if (fxGroup && m_model->getFxHandle()) {
      m_model->getFxHandle()->setFx(fxGroup->getFx());
    }
    // or, change the current object if the stageObjectChannelGroup is clicked
    else {
      StageObjectChannelGroup *stageObjectGroup =
          dynamic_cast<StageObjectChannelGroup *>(m_group);
      if (stageObjectGroup && m_model->getObjectHandle()) {
        m_model->getObjectHandle()->setObjectId(
            stageObjectGroup->getStageObject()->getId());
      }
    }
    // the current channel must be active
    if (!m_isActive) {
      m_isActive = true;
      m_model->refreshActiveChannels();
      getParam()->addObserver(this);
    }
    // refresh the old current (if !=0) and the new one
    if (oldCurrent) m_model->emitDataChanged(oldCurrent);
    m_model->emitDataChanged(this);
    m_model->emitCurveSelected(getParam());
    // scroll the column to ensure visible the current channel
    m_model->emitCurrentChannelChanged(this);
  } else {
    // this channel is not the current anymore
    if (oldCurrent != this) return;  // it was not: nothing to do
    m_model->m_currentChannel = 0;
    // refresh the channel
    m_model->emitDataChanged(this);
  }
}
setParam()
void FunctionTreeModel::Channel::setParam (const TParamP & param) override virtual
Reimplemented from FunctionTreeModel::ParamWrapper.
{
  if (param.getPointer() == m_param.getPointer()) return;
  TParamP oldParam = m_param;
  m_param          = param;
  if (m_isActive) {
    oldParam->removeObserver(this);
    param->addObserver(this);
  }
}
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/toonzqt/functiontreeviewer.h
E:/opentoonz/toonz/sources/toonzqt/functiontreeviewer.cpp