opentoonz: ShaderInterface::Parameter Class Reference
ShaderInterface::Parameter Class Reference final
Public Member Functions
Parameter (ParameterType type, const QString &name)
Public Member Functions inherited from TPersist
virtual void loadData (TIStream &is)=0
virtual void saveData (TOStream &os)=0
std::string getStreamTag () const
virtual const TPersistDeclaration * getDeclaration () const =0
Public Attributes
ParameterType m_type
QString m_name
ParameterValue m_default
ParameterValue m_range [2]
ParameterConcept m_concept
Protected Member Functions
void saveData (TOStream &os) override
void loadData (TIStream &is) override
Additional Inherited Members
Public Types inherited from TPersist
typedef TPersist * CreateProc()
Static Public Member Functions inherited from TPersist
static void declare (CreateProc *)
static TPersist * create (const std::string &name)
Detailed Description
Constructor & Destructor Documentation
Parameter() [1/2]
ShaderInterface::Parameter::Parameter () inline
: m_type(PARAMETER_UNKNOWN) {}
Parameter() [2/2]
ShaderInterface::Parameter::Parameter (ParameterType type, const QString & name) inline
        : m_type(type), m_name(name) {}
Member Function Documentation
loadData()
void ShaderInterface::Parameter::loadData (TIStream & is) override protected virtual
 This is a pure virtual function and must be overridden with a method
that implements the object loading from a stream (i.e take the object's features from a formatted data stream). For example the TStageObject class use his implementation to take the values of the parameters that characterizes a stage object as name, coordinates, etc... from a file. is is an input file stream
Implements TPersist.
{
  // Load type and name
  QString typeName;
  is >> typeName >> m_name;
  m_type = ShaderInterface::ParameterType(
      std::find_if(l_typeNames, l_typeNames + TYPESCOUNT,
                   ::CaselessCompare(typeName)) -
      l_typeNames);
  if (m_type == TYPESCOUNT)
    throw TException(L"Unrecognized parameter type '" +
                     typeName.toStdWString() + L"'");
  // Load range
  std::string tagName;
  // Initialize default values
  m_concept = ParameterConcept();
  switch (m_type) {
  case BOOL:
    m_default.m_bool = false;
    break;
  case FLOAT:
    m_default.m_float  = 0.0;
    m_range[0].m_float = -(std::numeric_limits<GLfloat>::max)();
    m_range[1].m_float = (std::numeric_limits<GLfloat>::max)();
    break;
  case VEC2:
    m_default.m_vec2[0] = m_default.m_vec2[1] = 0.0;
    m_range[0].m_vec2[0]                      = m_range[0].m_vec2[1] =
        -(std::numeric_limits<GLfloat>::max)();
    m_range[1].m_vec2[0] = m_range[1].m_vec2[1] =
        (std::numeric_limits<GLfloat>::max)();
    break;
  case VEC3:
    m_default.m_vec3[0] = m_default.m_vec3[1] = m_default.m_vec3[1] = 0.0;
    m_range[0].m_vec3[0] = m_range[0].m_vec3[1] = m_range[0].m_vec3[2] =
        -(std::numeric_limits<GLfloat>::max)();
    m_range[1].m_vec3[0] = m_range[1].m_vec3[1] = m_range[1].m_vec3[2] =
        (std::numeric_limits<GLfloat>::max)();
    break;
  case VEC4:
    m_default.m_vec4[0] = m_default.m_vec4[1] = m_default.m_vec4[1] =
        m_default.m_vec4[1]                   = 0.0;
    m_range[0].m_vec4[0] = m_range[0].m_vec4[1] = m_range[0].m_vec4[2] =
        m_range[0].m_vec4[3] = -(std::numeric_limits<GLfloat>::max)();
    m_range[1].m_vec4[0] = m_range[1].m_vec4[1] = m_range[1].m_vec4[2] =
        m_range[1].m_vec4[3] = (std::numeric_limits<GLfloat>::max)();
    break;
  case INT:
    m_default.m_int  = 0;
    m_range[0].m_int = -(std::numeric_limits<GLint>::max)();
    m_range[1].m_int = (std::numeric_limits<GLint>::max)();
    break;
  case IVEC2:
    m_default.m_ivec2[0] = m_default.m_ivec2[1] = 0;
    m_range[0].m_ivec2[0]                       = m_range[0].m_ivec2[1] =
        -(std::numeric_limits<GLint>::max)();
    m_range[1].m_ivec2[0] = m_range[1].m_ivec2[1] =
        (std::numeric_limits<GLint>::max)();
    break;
  case IVEC3:
    m_default.m_ivec3[0] = m_default.m_ivec3[1] = m_default.m_ivec3[1] = 0;
    m_range[0].m_ivec3[0] = m_range[0].m_ivec3[1] = m_range[0].m_ivec3[2] =
        -(std::numeric_limits<GLint>::max)();
    m_range[1].m_ivec3[0] = m_range[1].m_ivec3[1] = m_range[1].m_ivec3[2] =
        (std::numeric_limits<GLint>::max)();
    break;
  case IVEC4:
    m_default.m_ivec4[0] = m_default.m_ivec4[1] = m_default.m_ivec4[1] =
        m_default.m_ivec4[1]                    = 0;
    m_range[0].m_ivec4[0] = m_range[0].m_ivec4[1] = m_range[0].m_ivec4[2] =
        m_range[0].m_ivec4[3] = -(std::numeric_limits<GLint>::max)();
    m_range[1].m_ivec4[0] = m_range[1].m_ivec4[1] = m_range[1].m_ivec4[2] =
        m_range[1].m_ivec4[3] = (std::numeric_limits<GLint>::max)();
    break;
  case RGBA:
    m_default.m_rgba[0] = m_default.m_rgba[1] = m_default.m_rgba[2] =
        m_default.m_rgba[3]                   = 255;
    break;
  case RGB:
    m_default.m_rgb[0] = m_default.m_rgb[1] = m_default.m_rgb[2] = 255;
    break;
  default:
    break;
  }
  // Attempt loading range from file
  while (is.openChild(tagName)) {
    if (tagName == l_names[CONCEPT])
      is >> m_concept, is.closeChild();
    else if (tagName == l_names[DEFAULT_]) {
      switch (m_type) {
      case BOOL: {
        int val;
        is >> val, m_default.m_bool = val;
        break;
      }
      case FLOAT: {
        double val;
        is >> val, m_default.m_float = val;
        break;
      }
      case VEC2: {
        double val;
        is >> val, m_default.m_vec2[0] = val;
        is >> val, m_default.m_vec2[1] = val;
        break;
      }
      case VEC3: {
        double val;
        is >> val, m_default.m_vec3[0] = val;
        is >> val, m_default.m_vec3[1] = val;
        is >> val, m_default.m_vec3[2] = val;
        break;
      }
      case VEC4: {
        double val;
        is >> val, m_default.m_vec4[0] = val;
        is >> val, m_default.m_vec4[1] = val;
        is >> val, m_default.m_vec4[2] = val;
        is >> val, m_default.m_vec4[3] = val;
        break;
      }
      case INT:
        is >> m_default.m_int;
        break;
      case IVEC2:
        is >> m_default.m_ivec2[0] >> m_default.m_ivec2[1];
        break;
      case IVEC3:
        is >> m_default.m_ivec3[0] >> m_default.m_ivec3[1] >>
            m_default.m_ivec3[2];
        break;
      case IVEC4:
        is >> m_default.m_ivec4[0] >> m_default.m_ivec4[1] >>
            m_default.m_ivec4[2] >> m_default.m_ivec4[3];
        break;
      case RGBA: {
        int val;
        is >> val, m_default.m_rgba[0] = val;
        is >> val, m_default.m_rgba[1] = val;
        is >> val, m_default.m_rgba[2] = val;
        is >> val, m_default.m_rgba[3] = val;
        break;
      }
      case RGB: {
        int val;
        is >> val, m_default.m_rgb[0] = val;
        is >> val, m_default.m_rgb[1] = val;
        is >> val, m_default.m_rgb[2] = val;
        break;
      }
      default:
        break;
      }
      is.closeChild();
    } else if (tagName == l_names[RANGE]) {
      switch (m_type) {
      case FLOAT: {
        double val;
        is >> val, m_range[0].m_float = val;
        is >> val, m_range[1].m_float = val;
        break;
      }
      case VEC2: {
        double val;
        is >> val, m_range[0].m_vec2[0] = val;
        is >> val, m_range[1].m_vec2[0] = val;
        is >> val, m_range[0].m_vec2[1] = val;
        is >> val, m_range[1].m_vec2[1] = val;
        break;
      }
      case VEC3: {
        double val;
        is >> val, m_range[0].m_vec3[0] = val;
        is >> val, m_range[1].m_vec3[0] = val;
        is >> val, m_range[0].m_vec3[1] = val;
        is >> val, m_range[1].m_vec3[1] = val;
        is >> val, m_range[0].m_vec3[2] = val;
        is >> val, m_range[1].m_vec3[2] = val;
        break;
      }
      case VEC4: {
        double val;
        is >> val, m_range[0].m_vec4[0] = val;
        is >> val, m_range[1].m_vec4[0] = val;
        is >> val, m_range[0].m_vec4[1] = val;
        is >> val, m_range[1].m_vec4[1] = val;
        is >> val, m_range[0].m_vec4[2] = val;
        is >> val, m_range[1].m_vec4[2] = val;
        is >> val, m_range[0].m_vec4[3] = val;
        is >> val, m_range[1].m_vec4[3] = val;
        break;
      }
      case INT:
        is >> m_range[0].m_int >> m_range[1].m_int;
        break;
      case IVEC2:
        is >> m_range[0].m_ivec2[0] >> m_range[1].m_ivec2[0] >>
            m_range[0].m_ivec2[1] >> m_range[1].m_ivec2[1];
        break;
      case IVEC3:
        is >> m_range[0].m_ivec3[0] >> m_range[1].m_ivec3[0] >>
            m_range[0].m_ivec3[1] >> m_range[1].m_ivec3[1] >>
            m_range[0].m_ivec3[2] >> m_range[1].m_ivec3[2];
        break;
      case IVEC4:
        is >> m_range[0].m_ivec4[0] >> m_range[1].m_ivec4[0] >>
            m_range[0].m_ivec4[1] >> m_range[1].m_ivec4[1] >>
            m_range[0].m_ivec4[2] >> m_range[1].m_ivec4[2] >>
            m_range[0].m_ivec4[3] >> m_range[1].m_ivec4[3];
        break;
      default:
        break;
      }
      is.closeChild();
    } else
      ::skipTag(is, tagName);
  }
  // Post-process loaded data
  if (m_concept.m_label.isEmpty()) m_concept.m_label = m_name;
}
References TIStream::closeChild(), and TIStream::openChild().
saveData()
void ShaderInterface::Parameter::saveData (TOStream & os) override protected virtual
 This is a pure virtual function and must be overridden with a method
that implements the object saving to a data stream (i.e put the object's features on a formatted data stream). For example the TStageObject class use his implementation to save the values of the parameters that characterizes a stage object as name, coordinates, etc... on a file os is an output file stream.
Implements TPersist.
{
  os << l_typeNames[m_type] << m_name;
  os.openChild(l_names[CONCEPT]);
  os << m_concept;
  os.closeChild();
  os.openChild(l_names[DEFAULT_]);
  switch (m_type) {
  case BOOL:
    os << (int)m_default.m_bool;
    break;
  case FLOAT:
    os << (double)m_default.m_float;
    break;
  case VEC2:
    os << (double)m_default.m_vec2[0] << (double)m_default.m_vec2[1];
    break;
  case VEC3:
    os << (double)m_default.m_vec3[0] << (double)m_default.m_vec3[1]
       << (double)m_default.m_vec3[2];
    break;
  case VEC4:
    os << (double)m_default.m_vec4[0] << (double)m_default.m_vec4[1]
       << (double)m_default.m_vec4[2] << (double)m_default.m_vec4[3];
    break;
  case INT:
    os << m_default.m_int;
    break;
  case IVEC2:
    os << m_default.m_ivec2[0] << m_default.m_ivec2[1];
    break;
  case IVEC3:
    os << m_default.m_ivec3[0] << m_default.m_ivec3[1] << m_default.m_ivec3[2];
    break;
  case IVEC4:
    os << m_default.m_ivec4[0] << m_default.m_ivec4[1] << m_default.m_ivec4[2]
       << m_default.m_ivec4[3];
    break;
  case RGBA:
    os << (int)m_default.m_rgba[0] << (int)m_default.m_rgba[1]
       << (int)m_default.m_rgba[2] << (int)m_default.m_rgba[3];
    break;
  case RGB:
    os << (int)m_default.m_rgb[0] << (int)m_default.m_rgb[1]
       << (int)m_default.m_rgb[2];
    break;
  default:
    break;
  }
  os.closeChild();
  os.openChild(l_names[RANGE]);
  switch (m_type) {
  case FLOAT:
    os << (double)m_range[0].m_float << (double)m_range[1].m_float;
    break;
  case VEC2:
    os << (double)m_range[0].m_vec2[0] << (double)m_range[1].m_vec2[0]
       << (double)m_range[0].m_vec2[1] << (double)m_range[1].m_vec2[1];
    break;
  case VEC3:
    os << (double)m_range[0].m_vec3[0] << (double)m_range[1].m_vec3[0]
       << (double)m_range[0].m_vec3[1] << (double)m_range[1].m_vec3[1]
       << (double)m_range[0].m_vec3[2] << (double)m_range[1].m_vec3[2];
    break;
  case VEC4:
    os << (double)m_range[0].m_vec4[0] << (double)m_range[1].m_vec4[0]
       << (double)m_range[0].m_vec4[1] << (double)m_range[1].m_vec4[1]
       << (double)m_range[0].m_vec4[2] << (double)m_range[1].m_vec4[2]
       << (double)m_range[0].m_vec4[3] << (double)m_range[1].m_vec4[3];
    break;
  case INT:
    os << m_range[0].m_int << m_range[1].m_int;
    break;
  case IVEC2:
    os << m_range[0].m_ivec2[0] << m_range[1].m_ivec2[0]
       << m_range[0].m_ivec2[1] << m_range[1].m_ivec2[1];
    break;
  case IVEC3:
    os << m_range[0].m_ivec3[0] << m_range[1].m_ivec3[0]
       << m_range[0].m_ivec3[1] << m_range[1].m_ivec3[1]
       << m_range[0].m_ivec3[2] << m_range[1].m_ivec3[2];
    break;
  case IVEC4:
    os << m_range[0].m_ivec4[0] << m_range[1].m_ivec4[0]
       << m_range[0].m_ivec4[1] << m_range[1].m_ivec4[1]
       << m_range[0].m_ivec4[2] << m_range[1].m_ivec4[2]
       << m_range[0].m_ivec4[3] << m_range[1].m_ivec4[3];
    break;
  default:
    break;
  }
  os.closeChild();
}
References TOStream::closeChild(), and TOStream::openChild().
Member Data Documentation
m_concept
ParameterConcept ShaderInterface::Parameter::m_concept
m_default
ParameterValue ShaderInterface::Parameter::m_default
m_name
QString ShaderInterface::Parameter::m_name
m_range
ParameterValue ShaderInterface::Parameter::m_range[2]
m_type
ParameterType ShaderInterface::Parameter::m_type
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/stdfx/shaderinterface.h
E:/opentoonz/toonz/sources/stdfx/shaderinterface.cpp