opentoonz: TPalette::Page Class Reference
TPalette::Page Class Reference
A palette page is a restricted view of a palette instance.
#include <tpalette.h>
Public Member Functions
Page (std::wstring name)
std::wstring getName () const
Returns the name of the page.
void setName (std::wstring name)
Sets the name of the page.
TPalette * getPalette () const
Returns a pointer to the palette that contains this page.
int getIndex () const
Returns the page index in the palette.
int getStyleCount () const
Returns the number of the styles contained in the page.
int getStyleId (int indexInPage) const
TColorStyle * getStyle (int indexInPage) const
found.
int addStyle (int styleId)
int addStyle (TColorStyle *style)
int addStyle (TPixel32 color)
void insertStyle (int indexInPage, int styleId)
to this page.
void insertStyle (int indexInPage, TColorStyle *style)
void insertStyle (int indexInPage, TPixel32 color)
void removeStyle (int indexInPage)
int search (int styleId) const
int search (TColorStyle *style) const
Friends
class TPalette
Detailed Description
A palette page is a restricted view of a palette instance.
Constructor & Destructor Documentation
Page()
TPalette::Page::Page (std::wstring name)
    : m_name(name), m_index(-1), m_palette(0) {}
Member Function Documentation
addStyle() [1/3]
int TPalette::Page::addStyle (int styleId)
style in the page, or 0 if not found.
Returns
The insertion index in the page, or -1 on failure Adds the specified style Id to the page (at the back of the page).
{
  assert(m_palette);
  if (styleId < 0 || styleId >= m_palette->getStyleCount()) return -1;
  if (m_palette->m_styles[styleId].first != 0) return -1;
  m_palette->m_styles[styleId].first = this;
  int indexInPage                    = int(m_styleIds.size());
  m_styleIds.push_back(styleId);
  return indexInPage;
}
Referenced by TPalette::assign(), TPalette::loadData(), and TPalette::merge().
addStyle() [2/3]
int TPalette::Page::addStyle (TColorStyle * style)
Warning
The supplied style must have been allocated with new.
Style ownership is surrendered to the palette.
Returns
The insertion index in the page, or -1 on failure. In case of failure, the supplied style is deleted. Adds the specified style to the palette, and assigns it
{
  assert(m_palette);
  int stylesCount = int(m_palette->m_styles.size());
  int styleId;
  for (styleId = 0; styleId < stylesCount; styleId++)
    if (m_palette->m_styles[styleId].first == 0) break;
  if (styleId >= stylesCount - 1) return addStyle(m_palette->addStyle(style));
  m_palette->setStyle(styleId, style);
  return addStyle(styleId);
}
References TPalette::addStyle().
addStyle() [3/3]
int TPalette::Page::addStyle (TPixel32 color)
to this page.
Returns
The insertion index in the page, or -1 on failure Add a solid color style to the palette, and assigns it
{
  return addStyle(new TSolidColorStyle(color));
}
References TPalette::addStyle().
getIndex()
int TPalette::Page::getIndex () const inline
Returns the page index in the palette.
Referenced by PaletteViewerGUI::PageViewer::contextMenuEvent(), PaletteViewerGUI::PageViewer::dragEnterEvent(), PaletteViewerGUI::PageViewer::drop(), TPalette::getPage(), TPalette::getStyleShortcut(), PaletteViewerGUI::PageViewer::mousePressEvent(), TPalette::movePage(), PaletteViewerGUI::PageViewer::paintEvent(), PaletteViewerGUI::PageViewer::select(), and PaletteViewerGUI::PageViewer::startDragDrop().
getName()
std::wstring TPalette::Page::getName () const inline
Returns the name of the page.
Referenced by TPalette::assign(), TPalette::merge(), TPalette::saveData(), and PaletteViewer::updateTabBar().
getPalette()
TPalette * TPalette::Page::getPalette () const inline
Returns a pointer to the palette that contains this page.
Referenced by PaletteViewerGUI::PageViewer::contextMenuEvent(), PaletteViewerGUI::PageViewer::createDropPage(), PaletteViewerGUI::PaletteTabBar::dragMoveEvent(), PaletteViewerGUI::PageViewer::drawColorName(), PaletteViewerGUI::PageViewer::drop(), PaletteViewerGUI::PageViewer::event(), PaletteViewerGUI::PageViewer::mouseDoubleClickEvent(), PaletteViewerGUI::PaletteTabBar::mouseDoubleClickEvent(), PaletteViewerGUI::PageViewer::mouseMoveEvent(), PaletteViewerGUI::PaletteTabBar::mouseMoveEvent(), PaletteViewerGUI::PageViewer::mousePressEvent(), PaletteViewerGUI::PageViewer::onFrameChanged(), PaletteViewerGUI::PageViewer::paintEvent(), PaletteViewerGUI::PageViewer::select(), PaletteViewerGUI::PageViewer::startDragDrop(), and PaletteViewerGUI::PageViewer::updateCommandLocks().
getStyle()
TColorStyle * TPalette::Page::getStyle (int indexInPage) const
found.
Returns the index-th
{
  assert(m_palette);
  if (0 <= index && index < getStyleCount())
    return m_palette->getStyle(m_styleIds[index]);
  else
    return 0;
}
References TPalette::getStyle(), and getStyleCount().
Referenced by PaletteViewerGUI::PageViewer::drop(), PaletteViewerGUI::PageViewer::event(), TStyleSelection::getBackOriginalStyle(), TStyleSelection::hasLinkedStyle(), PaletteViewerGUI::PageViewer::mouseDoubleClickEvent(), PaletteViewerGUI::PageViewer::paintEvent(), and TStyleSelection::removeLink().
getStyleCount()
int TPalette::Page::getStyleCount () const inline
Returns the number of the styles contained in the page.
Referenced by TPalette::assign(), PaletteViewer::deletePage(), PaletteViewerGUI::PageViewer::dragEnterEvent(), PaletteViewerGUI::PageViewer::dragMoveEvent(), PaletteViewerGUI::PageViewer::drop(), TPalette::erasePage(), PaletteViewerGUI::PageViewer::event(), PaletteViewerGUI::PageViewer::getChipCount(), getStyle(), TPalette::merge(), TPalette::saveData(), and PaletteViewerGUI::PageViewer::select().
getStyleId()
int TPalette::Page::getStyleId (int indexInPage) const
Returns the index-th style id in the page, or -1 if not
{
  assert(m_palette);
  if (0 <= index && index < getStyleCount())
    return m_styleIds[index];
  else
    return -1;
}
References TPalette::getStyleCount().
Referenced by TPalette::assign(), PaletteViewer::contextMenuEvent(), PaletteViewer::deletePage(), PaletteViewerGUI::PageViewer::dragMoveEvent(), PaletteViewerGUI::PageViewer::drop(), TPalette::erasePage(), PaletteViewerGUI::PageViewer::event(), TStyleSelection::getBackOriginalStyle(), TPalette::getShortcutValue(), TPalette::merge(), PaletteViewerGUI::PageViewer::mousePressEvent(), PaletteViewerGUI::PageViewer::paintEvent(), TPalette::saveData(), and PaletteViewerGUI::PageViewer::select().
insertStyle() [1/3]
void TPalette::Page::insertStyle (int indexInPage, int styleId)
to this page.
Inserts the supplied style id at the
{
  assert(m_palette);
  if (styleId < 0 || styleId >= m_palette->getStyleCount()) return;
  if (m_palette->m_styles[styleId].first != 0) return;
  m_palette->m_styles[styleId].first = this;
  if (indexInPage < 0)
    indexInPage = 0;
  else if (indexInPage > getStyleCount())
    indexInPage = getStyleCount();
  m_styleIds.insert(m_styleIds.begin() + indexInPage, styleId);
}
References TPalette::getStyleCount().
insertStyle() [2/3]
void TPalette::Page::insertStyle (int indexInPage, TColorStyle * style)
specified position in the page.
See also
The specifics of addStyle(TColorStyle*) apply here. Inserts the
{
  assert(m_palette);
  int styleId = m_palette->addStyle(style);
  if (styleId >= 0) insertStyle(indexInPage, styleId);
}
insertStyle() [3/3]
void TPalette::Page::insertStyle (int indexInPage, TPixel32 color)
supplied style in the palette, and assigns its id at the specified position in the page. Inserts a solid color style in the
{
  assert(m_palette);
  int styleId = m_palette->addStyle(color);
  if (styleId >= 0) insertStyle(indexInPage, styleId);
}
removeStyle()
void TPalette::Page::removeStyle (int indexInPage)
palette, and assigns its id at the specified position in the page. Removes the style at the specified position from this page.
{
  if (indexInPage < 0 || indexInPage >= getStyleCount()) return;
  assert(m_palette);
  int styleId = getStyleId(indexInPage);
  assert(0 <= styleId && styleId < m_palette->getStyleCount());
  assert(m_palette->m_styles[styleId].first == this);
  m_palette->m_styles[styleId].first = 0;
  m_styleIds.erase(m_styleIds.begin() + indexInPage);
}
References TPalette::getStyleCount().
search() [1/2]
int TPalette::Page::search (int styleId) const
Returns the page position of the specified style id, or -1 if it cannot be found on the page.
{
  std::vector<int>::const_iterator it =
      std::find(m_styleIds.begin(), m_styleIds.end(), styleId);
  if (it == m_styleIds.end())
    return -1;
  else
    return it - m_styleIds.begin();
}
Referenced by TPalette::getStyleShortcut(), and PaletteViewer::onColorStyleSwitched().
search() [2/2]
int TPalette::Page::search (TColorStyle * style) const
Returns the page position of the specified style, or -1 if it cannot be found on the page.
{
  assert(style);
  assert(m_palette);
  for (int i = 0; i < getStyleCount(); i++)
    if (m_palette->getStyle(m_styleIds[i]) == style) return i;
  return -1;
}
References TPalette::getStyleCount().
setName()
void TPalette::Page::setName (std::wstring name) inline
Sets the name of the page.
Friends And Related Function Documentation
TPalette
friend class TPalette friend
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/tpalette.h
E:/opentoonz/toonz/sources/common/tvrender/tpalette.cpp