opentoonz: TTool::Viewer Class Reference
TTool::Viewer Class Reference abstract
The TTool::Viewer class is the abstract base class that provides an interface for TTool viewer widgets (it is required that such widgets support OpenGL).
#include <tool.h>
Public Member Functions
const ImagePainter::VisualSettings & visualSettings () const
ImagePainter::VisualSettings & visualSettings ()
virtual double getPixelSize () const =0
virtual void invalidateAll ()=0
virtual void GLInvalidateAll ()=0
virtual void GLInvalidateRect (const TRectD &rect)=0
virtual void invalidateToolStatus ()=0
virtual TAffine getViewMatrix () const
virtual int posToColumnIndex (const TPointD &p, double distance, bool includeInvisible=true) const =0
virtual void posToColumnIndexes (const TPointD &p, std::vector< int > &indexes, double distance, bool includeInvisible=true) const =0
virtual int posToRow (const TPointD &p, double distance, bool includeInvisible=true, bool currentColumnOnly=false) const =0
virtual TPointD worldToPos (const TPointD &worldPos) const =0
return pos in pixel, bottom-left origin
virtual int pick (const TPointD &point)=0
virtual TPointD winToWorld (const TPointD &winPos) const =0
virtual void pan (const TPointD &delta)=0
virtual void zoom (const TPointD &center, double scaleFactor)=0
virtual void rotate (const TPointD &center, double angle)=0
virtual void rotate3D (double dPhi, double dTheta)=0
virtual bool is3DView () const =0
virtual bool getIsFlippedX () const =0
virtual bool getIsFlippedY () const =0
virtual double projectToZ (const TPointD &delta)=0
virtual TPointD getDpiScale () const =0
virtual int getVGuideCount ()=0
virtual int getHGuideCount ()=0
virtual double getHGuide (int index)=0
virtual double getVGuide (int index)=0
virtual void resetInputMethod ()=0
virtual void setFocus ()=0
virtual TRectD getGeometry () const =0
virtual void bindFBO ()
virtual void releaseFBO ()
int getGuidedStrokePickerMode ()
void setGuidedStrokePickerMode (int mode)
int getGuidedStrokePickerCursor ()
int getGuidedFrontStroke ()
void setGuidedFrontStroke (int strokeIdx)
int getGuidedBackStroke ()
void setGuidedBackStroke (int strokeIdx)
void getGuidedFrameIdx (int *backIdx, int *frontIdx)
void doPickGuideStroke (const TPointD &pos)
Protected Attributes
ImagePainter::VisualSettings m_visualSettings
Settings used by the Viewer to draw scene contents.
int guidedStrokePickMode = 0
int m_guidedFrontStroke = -1
int m_guidedBackStroke = -1
Detailed Description
The TTool::Viewer class is the abstract base class that provides an interface for TTool viewer widgets (it is required that such widgets support OpenGL).
Constructor & Destructor Documentation
Viewer()
TTool::Viewer::Viewer () inline
{}
~Viewer()
virtual TTool::Viewer::~Viewer () inline virtual
{}
Member Function Documentation
bindFBO()
virtual void TTool::Viewer::bindFBO () inline virtual
{}
doPickGuideStroke()
void TTool::Viewer::doPickGuideStroke (const TPointD & pos)
{
  int pickerMode = getGuidedStrokePickerMode();
  if (!pickerMode) return;
  if (pickerMode >= -2 && pickerMode <= 2) setGuidedStrokePickerMode(0);
  int osBack  = -1;
  int osFront = -1;
  int os      = -1;
  getGuidedFrameIdx(&osBack, &osFront);
  if (pickerMode < 0)  // Previous Frame
    os = osBack;
  else if (pickerMode > 0)  // Next Frame
    os = osFront;
  TFrameId fid;
  TFrameHandle *currentFrame = getApplication()->getCurrentFrame();
  TXshSimpleLevel *sl =
      getApplication()->getCurrentLevel()->getLevel()->getSimpleLevel();
  if (!sl) return;
  if (currentFrame->isEditingScene()) {
    TXsheet *xsh = getApplication()->getCurrentXsheet()->getXsheet();
    int col      = getApplication()->getCurrentColumn()->getColumnIndex();
    if (xsh && col >= 0) {
      TXshCell cell = xsh->getCell(os, col);
      if (!cell.isEmpty()) fid = cell.getFrameId();
    }
  } else
    fid = sl->getFrameId(os);
  if (fid.isEmptyFrame()) return;
  TVectorImageP fvi = sl->getFrame(fid, false);
  if (!fvi) return;
  UINT index;
  double t, dist2 = 0;
  double pixelSize = getPixelSize();
  TAffine aff      = getViewMatrix();
  double maxDist   = 5 * pixelSize;
  double maxDist2  = maxDist * maxDist;
  double checkDist = maxDist2 * 4;
  TStroke *strokeRef;
  if (fvi->getNearestStroke(pos, t, index, dist2)) {
    strokeRef          = fvi->getStroke(index);
    TThickPoint cursor = strokeRef->getThickPoint(t);
    double len         = cursor.thick * pixelSize * sqrt(aff.det());
    checkDist          = std::max(checkDist, (len * len));
  }
  if (dist2 >= checkDist)
    index = -1;
  else {
    if (pickerMode < 0)  // Previous Frame
      setGuidedBackStroke(index);
    else if (pickerMode > 0)  // Next Frame
      setGuidedFrontStroke(index);
  }
  if (pickerMode <= -2) {
    if (index != -1) setGuidedStrokePickerMode(pickerMode * -1);
  } else if (pickerMode >= 2) {
    if (pickerMode >= 3 && index != -1) {
      TTool *tool = TTool::getTool(T_Brush, TTool::ToolTargetType::VectorImage);
      ToonzVectorBrushTool *vbTool = (ToonzVectorBrushTool *)tool;
      if (vbTool) {
        vbTool->setViewer(this);
        vbTool->doGuidedAutoInbetween(fid, fvi, strokeRef, false, false, false,
                                      false);
      }
      setGuidedStrokePickerMode(pickerMode * -1);
    }
  }
}
getGeometry()
virtual TRectD TTool::Viewer::getGeometry () const pure virtual
Implemented in SceneViewer.
getGuidedBackStroke()
int TTool::Viewer::getGuidedBackStroke () inline
{ return m_guidedBackStroke; }
getGuidedFrameIdx()
void TTool::Viewer::getGuidedFrameIdx (int * backIdx, int * frontIdx)
{
  if (!Preferences::instance()->isGuidedDrawingEnabled()) return;
  OnionSkinMask osMask =
      m_application->getCurrentOnionSkin()->getOnionSkinMask();
  if (!osMask.isEnabled() || osMask.isEmpty()) return;
  TFrameHandle *currentFrame = getApplication()->getCurrentFrame();
  int cidx     = currentFrame->getFrameIndex();
  int mosBack  = 0;
  int mosFront = 0;
  int mosCount = osMask.getMosCount();
  int fosBack  = -1;
  int fosFront = -1;
  int fosCount = osMask.getFosCount();
  // Find onion-skinned drawing that is being used for guided auto inbetween
  if (Preferences::instance()->getGuidedDrawingType() == 1) {
    // Get closest moving unionskin
    for (int i = 0; i < mosCount; i++) {
      int cmos = osMask.getMos(i);
      if (cmos == 0) continue;  // skip current
      if (cmos < 0 && (!mosBack || cmos > mosBack)) mosBack = cmos;
      if (cmos > 0 && (!mosFront || cmos < mosFront)) mosFront = cmos;
    }
    if (mosBack) *backIdx = mosBack + cidx;
    if (mosFront) *frontIdx = mosFront + cidx;
    // Get closest fixed onionskin
    for (int i = 0; i < fosCount; i++) {
      int cfos = osMask.getFos(i);
      if (cfos == cidx) continue;  // skip current
      if (cfos < cidx && (fosBack == -1 || cfos > fosBack)) fosBack = cfos;
      if (cfos > cidx && (fosFront == -1 || cfos < fosFront)) fosFront = cfos;
    }
    if (*backIdx == -1)
      *backIdx = fosBack;
    else if (fosBack != -1)
      *backIdx = std::max(*backIdx, fosBack);
    if (*frontIdx == -1)
      *frontIdx = fosFront;
    else if (fosFront != -1)
      *frontIdx = std::min(*frontIdx, fosFront);
  } else if (Preferences::instance()->getGuidedDrawingType() ==
             2) {  // Furthest drawing
                   // Get moving unionskin
    for (int i = 0; i < mosCount; i++) {
      int cmos = osMask.getMos(i);
      if (cmos == 0) continue;  // skip current
      if (cmos < 0 && (!mosBack || cmos < mosBack)) mosBack = cmos;
      if (cmos > 0 && (!mosFront || cmos > mosFront)) mosFront = cmos;
    }
    if (mosBack) *backIdx = mosBack + cidx;
    if (mosFront) *frontIdx = mosFront + cidx;
    // Get fixed onionskin
    for (int i = 0; i < fosCount; i++) {
      int cfos = osMask.getFos(i);
      if (cfos == cidx) continue;  // skip current
      if (cfos < cidx && (fosBack == -1 || cfos < fosBack)) fosBack = cfos;
      if (cfos > cidx && (fosFront == -1 || cfos > fosFront)) fosFront = cfos;
    }
    if (*backIdx == -1)
      *backIdx = fosBack;
    else if (fosBack != -1)
      *backIdx = std::min(*backIdx, fosBack);
    if (*frontIdx == -1)
      *frontIdx = fosFront;
    else if (fosFront != -1)
      *frontIdx = std::max(*frontIdx, fosFront);
  }
}
getGuidedFrontStroke()
int TTool::Viewer::getGuidedFrontStroke () inline
{ return m_guidedFrontStroke; }
getGuidedStrokePickerCursor()
int TTool::Viewer::getGuidedStrokePickerCursor () inline
{
    if (guidedStrokePickMode < 0)
      return ToolCursor::PickPrevCursor;
    else if (guidedStrokePickMode > 0)
      return ToolCursor::PickNextCursor;
    else
      return ToolCursor::PointingHandCursor;
  }
getGuidedStrokePickerMode()
int TTool::Viewer::getGuidedStrokePickerMode () inline
{ return guidedStrokePickMode; }
getPixelSize()
virtual double TTool::Viewer::getPixelSize () const pure virtual
Returns the length of a pixel in current OpenGL coordinates
Implemented in SceneViewer.
getViewMatrix()
virtual TAffine TTool::Viewer::getViewMatrix () const inline virtual
Gets the viewer's current view affine (ie the transform from starting to current world view <\I>)
Reimplemented in SceneViewer.
Referenced by RotateTool::draw().
GLInvalidateAll()
virtual void TTool::Viewer::GLInvalidateAll () pure virtual
Redraws the entire viewer, bypassing Qt's event system
Implemented in SceneViewer.
Referenced by TTool::invalidate().
GLInvalidateRect()
virtual void TTool::Viewer::GLInvalidateRect (const TRectD & rect) pure virtual
Same as GLInvalidateAll(),
Implemented in SceneViewer.
Referenced by TTool::invalidate().
invalidateAll()
virtual void TTool::Viewer::invalidateAll () pure virtual
Redraws the entire viewer, passing through Qt's event system
Implemented in SceneViewer.
Referenced by PlasticTool::onChange().
invalidateToolStatus()
virtual void TTool::Viewer::invalidateToolStatus () pure virtual
for a specific clipping rect Forces the viewer to update the perceived status of tools
Implemented in SceneViewer.
pick()
virtual int TTool::Viewer::pick (const TPointD & point) pure virtual
return the OpenGL nameId of the object intersecting point p (window coordinate, pixels, bottom-left origin)
Implemented in SceneViewer.
Referenced by TTool::pick().
posToColumnIndex()
virtual int TTool::Viewer::posToColumnIndex (const TPointD & p, double distance, bool includeInvisible = true) const pure virtual
return the column index of the drawing intersecting point p (window coordinate, pixels, bottom-left origin)
Implemented in SceneViewer.
posToRow()
virtual int TTool::Viewer::posToRow (const TPointD & p, double distance, bool includeInvisible = true, bool currentColumnOnly = false) const pure virtual
return the row of the drawing intersecting point p (used with onionskins) (window coordinate, pixels, bottom-left origin)
Implemented in SceneViewer.
releaseFBO()
virtual void TTool::Viewer::releaseFBO () inline virtual
{}
setGuidedBackStroke()
void TTool::Viewer::setGuidedBackStroke (int strokeIdx) inline
{
    m_guidedBackStroke = strokeIdx;
    invalidateAll();
  }
setGuidedFrontStroke()
void TTool::Viewer::setGuidedFrontStroke (int strokeIdx) inline
{
    m_guidedFrontStroke = strokeIdx;
    invalidateAll();
  }
setGuidedStrokePickerMode()
void TTool::Viewer::setGuidedStrokePickerMode (int mode) inline
{ guidedStrokePickMode = mode; }
visualSettings() [1/2]
ImagePainter::VisualSettings & TTool::Viewer::visualSettings () inline
{ return m_visualSettings; }
visualSettings() [2/2]
const ImagePainter::VisualSettings & TTool::Viewer::visualSettings () const inline
{
    return m_visualSettings;
  }
worldToPos()
virtual TPointD TTool::Viewer::worldToPos (const TPointD & worldPos) const pure virtual
return pos in pixel, bottom-left origin
Implemented in SceneViewer.
Member Data Documentation
guidedStrokePickMode
int TTool::Viewer::guidedStrokePickMode = 0 protected
m_guidedBackStroke
int TTool::Viewer::m_guidedBackStroke = -1 protected
m_guidedFrontStroke
int TTool::Viewer::m_guidedFrontStroke = -1 protected
m_visualSettings
ImagePainter::VisualSettings TTool::Viewer::m_visualSettings protected
Settings used by the Viewer to draw scene contents.
Referenced by SceneViewer::posToRow().
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/tools/tool.h
E:/opentoonz/toonz/sources/tnztools/tool.cpp