opentoonz: SchematicScene Class Reference
SchematicScene Class Reference abstract
Public Member Functions
SchematicScene (QWidget *parent)
void clearAllItems ()
virtual QGraphicsItem * getCurrentNode ()
virtual void reorderScene ()=0
virtual void updateScene ()=0
Protected Types
enum GridDimension { eLarge , eSmall }
Protected Slots
virtual void onSelectionSwitched (TSelection *, TSelection *)
Protected Member Functions
bool isAnEmptyZone (const QRectF &rect)
Returns true if no nodes intersects rect.
QVector< SchematicNode * > getPlacedNode (SchematicNode *node)
void showEvent (QShowEvent *se)
void hideEvent (QHideEvent *se)
Protected Attributes
QList< SchematicLink * > m_highlightedLinks
Detailed Description
Member Enumeration Documentation
GridDimension
enum SchematicScene::GridDimension protected
{ eLarge, eSmall };
Constructor & Destructor Documentation
SchematicScene()
SchematicScene::SchematicScene (QWidget * parent)
                                              : QGraphicsScene(parent) {
  setSceneRect(0, 0, 50000, 50000);
  setItemIndexMethod(NoIndex);
}
~SchematicScene()
SchematicScene::~SchematicScene ()
{ clearAllItems(); }
Member Function Documentation
clearAllItems()
void SchematicScene::clearAllItems ()
Removes and then deletes all item in the scene.
{
  clearSelection();
  m_highlightedLinks.clear();
  QList<SchematicWindowEditor *> editors;
  QList<SchematicNode *> nodes;
  QList<SchematicLink *> links;
  int i;
  QList<QGraphicsItem *> sceneItems = items();
  int size                          = sceneItems.size();
  // create nodes and links list
  for (i = 0; i < size; i++) {
    QGraphicsItem *item           = sceneItems.at(i);
    SchematicWindowEditor *editor = dynamic_cast<SchematicWindowEditor *>(item);
    SchematicNode *node           = dynamic_cast<SchematicNode *>(item);
    SchematicLink *link           = dynamic_cast<SchematicLink *>(item);
    if (editor) editors.append(editor);
    if (node) nodes.append(node);
    if (link) links.append(link);
  }
  while (links.size() > 0) {
    SchematicLink *link = links.back();
    removeItem(link);
    links.removeLast();
    SchematicPort *startPort = link->getStartPort();
    SchematicPort *endPort   = link->getEndPort();
    if (startPort) startPort->removeLink(link);
    if (endPort) endPort->removeLink(link);
    delete link;
  }
  while (editors.size() > 0) {
    SchematicWindowEditor *editor = editors.back();
    removeItem(editor);
    editors.removeLast();
    delete editor;
  }
  while (nodes.size() > 0) {
    SchematicNode *node = nodes.back();
    removeItem(node);
    nodes.removeLast();
    delete node;
  }
  assert(items().size() == 0);
}
References SchematicLink::getEndPort(), SchematicLink::getStartPort(), and SchematicPort::removeLink().
Referenced by StageSchematicScene::updateScene().
getCurrentNode()
virtual QGraphicsItem * SchematicScene::getCurrentNode () inline virtual
Reimplemented in StageSchematicScene.
{ return 0; }
getPlacedNode()
QVector< SchematicNode * > SchematicScene::getPlacedNode (SchematicNode * node) protected
Returns a vector containing all nodes which had their bounding rects contained in node bounding rect enlarged of 10.
{
  QRectF rect = node->boundingRect().translated(node->scenePos());
  QList<QGraphicsItem *> allItems = items();
  QVector<SchematicNode *> nodes;
  for (auto const item : allItems) {
    SchematicNode *placedNode = dynamic_cast<SchematicNode *>(item);
    if (!placedNode || placedNode == node) continue;
    QRectF nodeRect =
        placedNode->boundingRect().translated(placedNode->scenePos());
    QRectF enlargedRect = rect.adjusted(-10, -10, 10, 10);
    if (enlargedRect.contains(nodeRect)) nodes.push_back(placedNode);
  }
  return nodes;
}
References SchematicNode::boundingRect().
hideEvent()
void SchematicScene::hideEvent (QHideEvent * se) protected
{
  TSelectionHandle *selHandle = TSelectionHandle::getCurrent();
  disconnect(selHandle, SIGNAL(selectionSwitched(TSelection *, TSelection *)),
             this, SLOT(onSelectionSwitched(TSelection *, TSelection *)));
}
isAnEmptyZone()
bool SchematicScene::isAnEmptyZone (const QRectF & rect) protected
Returns true if no nodes intersects rect.
check if any item exists in the rect
{
  QList<QGraphicsItem *> allItems = items();
  for (auto const level : allItems) {
    SchematicNode *node = dynamic_cast<SchematicNode *>(level);
    if (!node) continue;
    FxSchematicNode *fxNode = dynamic_cast<FxSchematicNode *>(node);
    if (fxNode && fxNode->isA(eXSheetFx)) continue;
    if (node->boundingRect().translated(node->scenePos()).intersects(rect))
      return false;
  }
  return true;
}
References SchematicNode::boundingRect().
onSelectionSwitched
virtual void SchematicScene::onSelectionSwitched (TSelection * , TSelection *) inline protected virtual slot
{}
reorderScene()
virtual void SchematicScene::reorderScene () pure virtual
Implemented in StageSchematicScene.
showEvent()
void SchematicScene::showEvent (QShowEvent * se) protected
{
  TSelectionHandle *selHandle = TSelectionHandle::getCurrent();
  connect(selHandle, SIGNAL(selectionSwitched(TSelection *, TSelection *)),
          this, SLOT(onSelectionSwitched(TSelection *, TSelection *)));
  clearSelection();
}
updateScene()
virtual void SchematicScene::updateScene () pure virtual
Implemented in StageSchematicScene.
Member Data Documentation
m_highlightedLinks
QList<SchematicLink *> SchematicScene::m_highlightedLinks protected
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/toonzqt/schematicviewer.h
E:/opentoonz/toonz/sources/toonzqt/schematicviewer.cpp