opentoonz: RasterSelectionTool Class Reference
RasterSelectionTool Class Reference final
Public Member Functions
RasterSelectionTool (int targetType)
void setBBox (const DragSelectionTool::FourPoints &points, int index=0) override
void setNewFreeDeformer () override
VectorFreeDeformer * getSelectionFreeDeformer () const
bool isFloating () const override
void leftButtonDown (const TPointD &pos, const TMouseEvent &) override
void mouseMove (const TPointD &pos, const TMouseEvent &e) override
void leftButtonDrag (const TPointD &pos, const TMouseEvent &) override
void leftButtonUp (const TPointD &pos, const TMouseEvent &) override
void leftButtonDoubleClick (const TPointD &, const TMouseEvent &e) override
void draw () override
Draws the tool on the viewer.
TSelection * getSelection () override
Returns a pointer to the tool selection.
bool isSelectionEmpty () override
void computeBBox () override
void doOnActivate () override
void doOnDeactivate () override
void onImageChanged () override
Notifies changes in the image in use.
void transformFloatingSelection (const TAffine &affine, const TPointD &center, const DragSelectionTool::FourPoints &points)
void increaseTransformationCount ()
void decreaseTransformationCount ()
void onActivate () override
Callback invoked whenever the tool activates.
TBoolProperty * getModifySaveboxProperty ()
bool onPropertyChanged (std::string propertyName) override
bool getNoAntialiasingValue ()
bool isSelectionEditable () override
Public Member Functions inherited from SelectionTool
SelectionTool (int targetType)
ToolType getToolType () const override
TPointD getCenter (int index=0) const
void setCenter (const TPointD &center, int index=0)
int getBBoxsCount () const
DragSelectionTool::FourPoints getBBox (int index=0) const
virtual void setBBox (const DragSelectionTool::FourPoints &points, int index=0)
FreeDeformer * getFreeDeformer (int index=0) const
virtual void setNewFreeDeformer ()=0
void clearDeformers ()
int getSelectedPoint () const
virtual bool isConstantThickness () const
virtual bool isLevelType () const
virtual bool isSelectedFramesType () const
virtual bool isSameStyleType () const
virtual bool isModifiableSelectionType () const
virtual bool isFloating () const
virtual QSet< int > getSelectedStyles () const
void leftButtonDown (const TPointD &pos, const TMouseEvent &) override
void leftButtonDrag (const TPointD &pos, const TMouseEvent &) override=0
void leftButtonUp (const TPointD &pos, const TMouseEvent &) override=0
void mouseMove (const TPointD &pos, const TMouseEvent &e) override
void leftButtonDoubleClick (const TPointD &, const TMouseEvent &e) override=0
bool keyDown (QKeyEvent *) override
int getCursorId () const override
Returns the type of cursor used by the tool.
void draw () override=0
Draws the tool on the viewer.
TSelection * getSelection () override=0
Returns a pointer to the tool selection.
virtual bool isSelectionEmpty ()=0
virtual void computeBBox ()=0
void onActivate () override
Callback invoked whenever the tool activates.
void onDeactivate () override
Callback for tool deactivation, includes tool switch.
void onImageChanged () override=0
Notifies changes in the image in use.
void onSelectionChanged () override
TPropertyGroup * getProperties (int targetType) override
bool onPropertyChanged (std::string propertyName) override
bool isEventAcceptable (QEvent *e) override
virtual bool isSelectionEditable ()
Public Member Functions inherited from TTool
TTool (std::string toolName)
every tool (invoking updateTranslation() for each).
virtual ToolType getToolType () const =0
ToolTargetType getTargetType () const
std::string getName () const
virtual ToolOptionsBox * createOptionsBox ()
void setViewer (Viewer *viewer)
Viewer * getViewer () const
double getPixelSize () const
void invalidate (const TRectD &rect=TRectD())
int pick (const TPointD &p)
bool isPicking () const
virtual void updateTranslation ()
virtual bool preLeftButtonDown ()
virtual void mouseMove (const TPointD &, const TMouseEvent &)
virtual void leftButtonDown (const TPointD &, const TMouseEvent &)
virtual void leftButtonDrag (const TPointD &, const TMouseEvent &)
virtual void leftButtonUp (const TPointD &, const TMouseEvent &)
virtual void leftButtonDoubleClick (const TPointD &, const TMouseEvent &)
virtual void rightButtonDown (const TPointD &, const TMouseEvent &)
virtual bool keyDown (QKeyEvent *)
virtual void onInputText (std::wstring, std::wstring, int, int)
virtual void onSetViewer ()
virtual void onActivate ()
Callback invoked whenever the tool activates.
virtual void onDeactivate ()
Callback for tool deactivation, includes tool switch.
virtual void onImageChanged ()
Notifies changes in the image in use.
virtual void onEnter ()
Callback for the mouse entering the viewer area.
virtual void onLeave ()
Callback for the mouse leaving the viewer area.
virtual void onFrameSwitched ()
virtual void reset ()
virtual void draw ()
Draws the tool on the viewer.
bool isActive () const
Used to know if a tool is active, (used in TextTool only).
void setActive (bool active)
virtual TPropertyGroup * getProperties (int)
virtual bool onPropertyChanged (std::string propertyName)
virtual TSelection * getSelection ()
Returns a pointer to the tool selection.
virtual int getCursorId () const
Returns the type of cursor used by the tool.
virtual bool isEventAcceptable (QEvent *e)
TXsheet * getXsheet () const
Returns a pointer to the actual Xsheet.
int getFrame ()
Returns the actual frame in use.
int getColumnIndex ()
Returns the actual column index.
TStageObjectId getObjectId () const
Returns a pointer to the actual stage object.
void notifyImageChanged ()
void notifyImageChanged (const TFrameId &fid)
images on the level view.
TFrameId getCurrentFid () const
Returns the number of the actual editing frame.
const TAffine & getMatrix () const
void setMatrix (const TAffine &matrix)
TAffine getCurrentColumnMatrix (int frame=-1) const
TAffine getCurrentColumnParentMatrix () const
TAffine getCurrentObjectParentMatrix () const
TAffine getCurrentObjectParentMatrix2 () const
TAffine getColumnMatrix (int index, int frame=-1) const
virtual void updateMatrix ()
virtual void addContextMenuItems (QMenu *menu)
void enable (bool on)
bool isEnabled () const
QString updateEnabled ()
virtual QString updateEnabled (int rowIndex, int columnIndex)
bool isColumnLocked (int columnIndex) const
void resetInputMethod ()
Resets Input Context (IME)
virtual bool isPencilModeActive ()
virtual bool isDragging () const
void setSelectedFrames (const std::set< TFrameId > &selectedFrames)
void tweenSelectedGuideStrokes ()
void tweenGuideStrokeToSelected ()
void flipGuideStrokeDirection (int mode)
Public Member Functions inherited from TSelection::View
virtual void onSelectionChanged ()=0
virtual void enableCommands ()
Protected Member Functions
void updateTranslation () override
Protected Member Functions inherited from SelectionTool
virtual void updateAction (TPointD pos, const TMouseEvent &e)
virtual void modifySelectionOnClick (TImageP image, const TPointD &pos, const TMouseEvent &e)=0
virtual void doOnActivate ()=0
virtual void doOnDeactivate ()=0
void startFreehand (const TPointD &pos)
void freehandDrag (const TPointD &pos)
Viene aggiunto pos a m_track e disegnato un altro pezzetto del lazzo.
void closeFreehand (const TPointD &pos)
void addPointPolyline (const TPointD &pos)
Viene aggiunto un punto al vettore m_polyline.
void closePolyline (const TPointD &pos)
void updateTranslation () override
void drawPolylineSelection ()
void drawRectSelection (const TImage *image)
void drawFreehandSelection ()
void drawCommandHandle (const TImage *image)
Protected Member Functions inherited from TTool
void bind (int targetType)
virtual void onSelectedFramesChanged ()
virtual QString disableString ()
Returns a custom reason to disable the tool.
Additional Inherited Members
Public Types inherited from TTool
enum ToolType {
GenericTool = 1 , ColumnTool = 2 , LevelReadTool = 4 , LevelWriteTool ,
LevelTool = LevelReadTool | LevelWriteTool
}
Tool editing type.
enum ToolTargetType {
NoTarget = 0x0 , VectorImage = 0x1 , ToonzImage = 0x2 , RasterImage = 0x4 ,
MeshImage = 0x8 , Splines = 0x10 , LevelColumns = 0x20 , MeshColumns = 0x40 ,
EmptyTarget = 0x80 , CommonImages = VectorImage | ToonzImage | RasterImage , AllImages = CommonImages | MeshImage , Vectors = VectorImage | Splines ,
CommonLevels = CommonImages | LevelColumns , MeshLevels = MeshImage | MeshColumns , AllTargets = 0xffffffff
}
Object types the tool can operate on.
typedef TApplication Application
Static Public Member Functions inherited from TTool
static TTool * getTool (std::string toolName, ToolTargetType targetType)
static TApplication * getApplication ()
static void setApplication (TApplication *application)
static TXshCell getImageCell ()
Returns the level-frame pair to be edited by the tool.
static TImage * getImage (bool toBeModified, int subsampling=0)
Returns the image to be edited by the tool.
static TImage * touchImage ()
static void updateToolsPropertiesTranslation ()
static const std::set< TFrameId > & getSelectedFrames ()
Public Attributes inherited from SelectionTool
DragSelectionTool::DeformValues m_deformValues
Static Public Attributes inherited from TTool
static std::vector< CellOps > m_cellsData
static bool m_isLevelCreated = false
static bool m_isFrameCreated = false
static std::vector< TFrameId > m_oldFids
static std::vector< TFrameId > m_newFids
static bool m_isLevelRenumbererd = false
Protected Types inherited from SelectionTool
enum {
Outside , Inside , DEFORM , ROTATION ,
MOVE_CENTER , SCALE , SCALE_X , SCALE_Y ,
GLOBAL_THICKNESS , ADD_SELECTION
}
enum {
P00 = 0 , P10 = 1 , P11 = 2 , P01 = 3 ,
PM0 = 4 , P1M = 5 , PM1 = 6 , P0M = 7 ,
NONE
}
Protected Attributes inherited from SelectionTool
bool m_firstTime
DragSelectionTool::DragTool * m_dragTool
StrokeGenerator m_track
std::vector< TPointD > m_polyline
TPointD m_mousePosition
TStroke * m_stroke
TPointD m_curPos
TPointD m_firstPos
bool m_selecting
bool m_justSelected
bool m_shiftPressed
enum SelectionTool:: { ... } m_what
enum SelectionTool:: { ... } m_selectedPoint
int m_cursorId
bool m_leftButtonMousePressed
DragSelectionTool::FourPoints m_selectingRect
std::vector< DragSelectionTool::FourPoints > m_bboxs
std::vector< TPointD > m_centers
std::vector< FreeDeformer * > m_freeDeformers
TEnumProperty m_strokeSelectionType
TPropertyGroup m_prop
Protected Attributes inherited from TTool
std::string m_name
The tool's name.
Viewer * m_viewer
Tool's current viewer.
TAffine m_matrix
World-to-window reference change affine.
int m_targetType
The tool's image type target.
bool m_enabled
Whether the tool allows user interaction.
bool m_active
bool m_picking
Static Protected Attributes inherited from TTool
static TApplication * m_application = 0
static std::set< TFrameId > m_selectedFrames = std::set<TFrameId>()
Detailed Description
Constructor & Destructor Documentation
RasterSelectionTool()
RasterSelectionTool::RasterSelectionTool (int targetType)
    : SelectionTool(targetType)
    , m_transformationCount(0)
    , m_selectionFreeDeformer(0)
    , m_noAntialiasing("No Antialiasing", false)
    , m_modifySavebox("Modify Savebox", false)
    , m_setSaveboxTool(0) {
  m_prop.bind(m_noAntialiasing);
  m_rasterSelection.setView(this);
  if (m_targetType & ToonzImage) {
    m_setSaveboxTool = new SetSaveboxTool(this);
    m_modifySavebox.setId("ModifySavebox");
  }
}
Member Function Documentation
computeBBox()
void RasterSelectionTool::computeBBox () override virtual
Implements SelectionTool.
{
  TImageP image    = getImage(false);
  TToonzImageP ti  = (TToonzImageP)image;
  TRasterImageP ri = (TRasterImageP)image;
  if (!ti && !ri) return;
  m_deformValues.reset();
  m_bboxs.clear();
  m_centers.clear();
  {
    std::vector<TStroke> strokes = m_rasterSelection.getStrokes();
    TRectD strokesRect           = m_rasterSelection.getStrokesBound(strokes);
    DragSelectionTool::FourPoints p;
    p = strokesRect;
    p = p * m_rasterSelection.getTransformation();
    m_bboxs.push_back(p);
    m_centers.push_back((p.getP00() + p.getP11()) * 0.5);
    m_rasterSelection.setSelectionBbox(strokesRect);
  }
  if (!m_freeDeformers.empty()) clearPointerContainer(m_freeDeformers);
  if (m_selectionFreeDeformer) {
    delete m_selectionFreeDeformer;
    m_selectionFreeDeformer = 0;
  }
  TTool::getApplication()->getCurrentTool()->notifyToolChanged();
}
decreaseTransformationCount()
void RasterSelectionTool::decreaseTransformationCount ()
{
  m_transformationCount--;
  m_rasterSelection.setTransformationCount(m_transformationCount);
  if (m_rasterSelection.getTransformationCount() == 0)
    m_rasterSelection.pasteFloatingSelection();
}
doOnActivate()
void RasterSelectionTool::doOnActivate () override virtual
Implements SelectionTool.
{
  const TXshCell &imageCell = TTool::getImageCell();
  TImageP image =
      imageCell.getImage(false, 1);  // => See the onImageChanged() warning !
  TToonzImageP ti  = (TToonzImageP)image;
  TRasterImageP ri = (TRasterImageP)image;
  if (!ti && !ri) return;
  m_rasterSelection.makeCurrent();
  m_rasterSelection.setCurrentImage(image, imageCell);
  m_rasterSelection.selectNone();
  m_noAntialiasing.setValue(NoAntialiasing);
  m_rasterSelection.setNoAntialiasing(m_noAntialiasing.getValue());
  TTool::getApplication()
      ->getCurrentTool()
      ->notifyToolChanged();  // Refreshes toolbar values
}
doOnDeactivate()
void RasterSelectionTool::doOnDeactivate () override virtual
Implements SelectionTool.
{
  TTool::getApplication()->getCurrentSelection()->setSelection(0);
  m_rasterSelection.setCurrentImage(0, TXshCell());
  m_rasterSelection.selectNone();
}
draw()
void RasterSelectionTool::draw () override virtual
Draws the tool on the viewer.
Implements SelectionTool.
{
  TImageP image    = getImage(false);
  TToonzImageP ti  = (TToonzImageP)image;
  TRasterImageP ri = (TRasterImageP)image;
  if (!ti && !ri) return;
  if (m_setSaveboxTool && m_modifySavebox.getValue()) {
    m_setSaveboxTool->draw();
    return;
  }
  glPushMatrix();
  /*--  --*/
  drawFloatingSelection();
  if (m_strokeSelectionType.getValue() == POLYLINE_SELECTION &&
      !m_rasterSelection.isFloating())
    drawPolylineSelection();
  else if (m_strokeSelectionType.getValue() == FREEHAND_SELECTION &&
           !m_rasterSelection.isFloating())
    drawFreehandSelection();
  if (m_rasterSelection.isEmpty()) m_bboxs.clear();
  /*--  --*/
  if (getBBoxsCount() > 0) drawCommandHandle(image.getPointer());
  /*--  --*/
  if (m_selecting && !m_selectingRect.isEmpty())
    drawRectSelection(image.getPointer());
  /*--  --*/
  /*
if(ti)
{
   TRectD saveBox = ToonzImageUtils::convertRasterToWorld(ti->getSavebox(), ti);
drawRect(saveBox.enlarge(0.5)*ti->getSubsampling(), TPixel32::Black, 0x5555,
true);
}
*/
  glPopMatrix();
}
References TRectT< T >::isEmpty().
getModifySaveboxProperty()
TBoolProperty * RasterSelectionTool::getModifySaveboxProperty () inline
{
    if (m_targetType & ToonzImage) return &m_modifySavebox;
    return 0;
  }
getNoAntialiasingValue()
bool RasterSelectionTool::getNoAntialiasingValue () inline
{ return m_noAntialiasing.getValue(); }
getSelection()
TSelection * RasterSelectionTool::getSelection () override virtual
Returns a pointer to the tool selection.
Implements SelectionTool.
{ return &m_rasterSelection; }
getSelectionFreeDeformer()
VectorFreeDeformer * RasterSelectionTool::getSelectionFreeDeformer () const
{
  return m_selectionFreeDeformer;
}
increaseTransformationCount()
void RasterSelectionTool::increaseTransformationCount ()
{
  if (m_rasterSelection.getTransformationCount() != m_transformationCount)
    m_transformationCount = 0;
  m_transformationCount++;
  m_rasterSelection.setTransformationCount(m_transformationCount);
}
isFloating()
bool RasterSelectionTool::isFloating () const override virtual
Reimplemented from SelectionTool.
{
  return m_rasterSelection.isFloating();
}
isSelectionEditable()
bool RasterSelectionTool::isSelectionEditable () inline override virtual
Reimplemented from SelectionTool.
{ return m_rasterSelection.isEditable(); }
isSelectionEmpty()
bool RasterSelectionTool::isSelectionEmpty () override virtual
Implements SelectionTool.
{
  TImageP image    = getImage(false);
  TToonzImageP ti  = (TToonzImageP)image;
  TRasterImageP ri = (TRasterImageP)image;
  if (!ti && !ri) return true;
  return m_rasterSelection.isEmpty();
}
leftButtonDoubleClick()
void RasterSelectionTool::leftButtonDoubleClick (const TPointD & pos, const TMouseEvent & e) override virtual
Implements SelectionTool.
{
  TImageP image    = getImage(true);
  TToonzImageP ti  = (TToonzImageP)image;
  TRasterImageP ri = (TRasterImageP)image;
  if (!ti && !ri) return;
  if (m_strokeSelectionType.getValue() == POLYLINE_SELECTION &&
      !m_polyline.empty()) {
    closePolyline(pos);
    if (m_stroke) {
      m_rasterSelection.select(*m_stroke);
      m_rasterSelection.setFrameId(getCurrentFid());
      m_rasterSelection.makeCurrent();
    }
    m_selecting = false;
    return;
  }
  TTool::getApplication()
      ->getCurrentTool()
      ->notifyToolChanged();  // Refreshes toolbar values
}
leftButtonDown()
void RasterSelectionTool::leftButtonDown (const TPointD & pos, const TMouseEvent & e) override virtual
Reimplemented from TTool.
{
  if (m_setSaveboxTool && m_modifySavebox.getValue()) {
    m_setSaveboxTool->leftButtonDown(pos);
    return;
  }
  SelectionTool::leftButtonDown(pos, e);
}
leftButtonDrag()
void RasterSelectionTool::leftButtonDrag (const TPointD & pos, const TMouseEvent & e) override virtual
Implements SelectionTool.
{
  if (m_setSaveboxTool && m_modifySavebox.getValue()) {
    m_setSaveboxTool->leftButtonDrag(pos);
    invalidate();
    return;
  }
  double pixelSize = getPixelSize();
  if (m_dragTool) {
    // Even in Windows version deformation is processed at interval of 20msec.
    // (See SceneViewer::tabletEvent)
    if (e.isHighFrequent()) return;
    if (!m_rasterSelection.isEditable()) return;
    m_dragTool->leftButtonDrag(pos, e);
    invalidate();
    return;
  }
  TImageP image    = getImage(true);
  TToonzImageP ti  = (TToonzImageP)image;
  TRasterImageP ri = (TRasterImageP)image;
  if (!ti && !ri) return;
  if (m_selecting) {
    if (m_strokeSelectionType.getValue() == RECT_SELECTION) {
      TDimension imageSize;
      if (ti)
        imageSize = ti->getSize();
      else if (ri)
        imageSize = ri->getRaster()->getSize();
      TPointD p(imageSize.lx % 2 ? 0.5 : 0.0, imageSize.ly % 2 ? 0.5 : 0.0);
      TRectD rectD(tround(std::min(m_firstPos.x, pos.x) - p.x) + p.x,
                   tround(std::min(m_firstPos.y, pos.y) - p.y) + p.y,
                   tround(std::max(m_firstPos.x, pos.x) - p.x) + p.x,
                   tround(std::max(m_firstPos.y, pos.y) - p.y) + p.y);
      m_selectingRect = rectD;
      m_bboxs.clear();
      TTool::getApplication()
          ->getCurrentTool()
          ->notifyToolChanged();  // Refreshes toolbar values
      invalidate();
    } else if (m_strokeSelectionType.getValue() == FREEHAND_SELECTION) {
      freehandDrag(pos);
      invalidate();
    }
    return;
  }
  TTool::Application *app = TTool::getApplication();
  if (!app || m_justSelected || !m_selecting ||
      tdistance2(pos, m_curPos) < 9.0 * pixelSize * pixelSize)
    return;
  m_curPos = pos;
  if (m_strokeSelectionType.getValue() == FREEHAND_SELECTION) {
    freehandDrag(pos);
    invalidate();
  } else if (m_strokeSelectionType.getValue() == RECT_SELECTION) {
    bool selectOverlappingStroke = (m_firstPos.x > pos.x);
    TRectD rect(m_firstPos, pos);
    m_selectingRect = rect;
    TTool::getApplication()
        ->getCurrentTool()
        ->notifyToolChanged();  // Refreshes toolbar values
    invalidate();
  }
}
leftButtonUp()
void RasterSelectionTool::leftButtonUp (const TPointD & pos, const TMouseEvent & e) override virtual
Implements SelectionTool.
{
  if (m_setSaveboxTool && m_modifySavebox.getValue()) {
    m_setSaveboxTool->leftButtonUp(pos);
    invalidate();
    return;
  }
  m_leftButtonMousePressed = false;
  m_shiftPressed           = false;
  if (m_dragTool) {
    if (!m_rasterSelection.isEditable()) {
      delete m_dragTool;
      m_dragTool = 0;
      return;
    }
    m_dragTool->leftButtonUp(pos, e);
    delete m_dragTool;
    m_dragTool = 0;
    invalidate();
    notifyImageChanged();
    return;
  }
  if (!m_selecting) return;
  // Se stavo modificando la selezione la completo
  TImageP image    = getImage(true);
  TToonzImageP ti  = (TToonzImageP)image;
  TRasterImageP ri = (TRasterImageP)image;
  if (ti || ri) {
    if (m_strokeSelectionType.getValue() == RECT_SELECTION) {
      m_bboxs.push_back(m_selectingRect);
      m_rasterSelection.select(
          TRectD(m_selectingRect.getP00(), m_selectingRect.getP11()));
      m_rasterSelection.setFrameId(getCurrentFid());
      m_selectingRect.empty();
    } else if (m_strokeSelectionType.getValue() == FREEHAND_SELECTION) {
      closeFreehand(pos);
      if (m_stroke->getControlPointCount() > 5) {
        m_rasterSelection.select(*m_stroke);
        m_rasterSelection.setFrameId(getCurrentFid());
        m_rasterSelection.makeCurrent();
      }
      m_track.clear();
    }
  }
  m_selecting    = false;
  m_justSelected = false;
  invalidate();
}
mouseMove()
void RasterSelectionTool::mouseMove (const TPointD & pos, const TMouseEvent & e) override virtual
Reimplemented from TTool.
{
  if (m_setSaveboxTool && m_modifySavebox.getValue()) {
    if (!m_leftButtonMousePressed)
      m_cursorId = m_setSaveboxTool->getCursorId(pos);
    return;
  }
  SelectionTool::mouseMove(pos, e);
}
onActivate()
void RasterSelectionTool::onActivate () override virtual
Callback invoked whenever the tool activates.
Reimplemented from TTool.
{
  if (m_firstTime) {
    if (m_targetType & ToonzImage)
      m_modifySavebox.setValue(ModifySavebox ? 1 : 0);
  }
  SelectionTool::onActivate();
}
References SelectionTool::onActivate().
onImageChanged()
void RasterSelectionTool::onImageChanged () override virtual
Notifies changes in the image in use.
Implements SelectionTool.
{
  // ATTENTION: using getImage(false, 1) *works* here, but it's trickier than
  // you could
  // expect. It works because:
  // 1. Invoking getImage(true) after getImage(false, 1) will return the same
  // image
  // 2. The cached fullsampled image may be in the 'not modified' ImageManager
  // state.
  //    Users could then alter the required image level subsampling - but doing
  //    so will
  //    immediately redirect here through 'onXshLevelChanged()' (thus resetting
  //    the subs back to 1).
  TImageP image    = getImage(false, 1);
  TToonzImageP ti  = image;
  TRasterImageP ri = image;
  if ((!ti && !ri) || image != m_rasterSelection.getCurrentImage())
    m_rasterSelection.selectNone();
  TTool::getApplication()
      ->getCurrentTool()
      ->notifyToolChanged();  // Refreshes toolbar values
}
References ToolHandle::notifyToolChanged().
onPropertyChanged()
bool RasterSelectionTool::onPropertyChanged (std::string propertyName) override virtual
 Does the tasks associated to changes in \p propertyName and returns \p
true; Does the tasks associated to changes in propertyName and returns true.
Reimplemented from TTool.
{
  if (!m_rasterSelection.isEditable()) return false;
  if (SelectionTool::onPropertyChanged(propertyName)) return true;
  if (m_targetType & ToonzImage) {
    ModifySavebox = (int)(m_modifySavebox.getValue());
    invalidate();
  }
  if (propertyName == m_noAntialiasing.getName()) {
    NoAntialiasing = m_noAntialiasing.getValue() ? 1 : 0;
    m_rasterSelection.setNoAntialiasing(m_noAntialiasing.getValue());
  }
  return true;
}
References SelectionTool::onPropertyChanged().
setBBox()
void RasterSelectionTool::setBBox (const DragSelectionTool::FourPoints & points, int index = 0) override virtual
Reimplemented from SelectionTool.
{
  if (m_bboxs.empty()) return;
  assert((int)m_bboxs.size() > index);
  m_bboxs[index]                  = points;
  TAffine aff                     = m_rasterSelection.getTransformation();
  DragSelectionTool::FourPoints p = points * aff.inv();
  m_rasterSelection.setSelectionBbox(p.getBox());
}
setNewFreeDeformer()
void RasterSelectionTool::setNewFreeDeformer () override virtual
Implements SelectionTool.
{
  if (!m_freeDeformers.empty() || isSelectionEmpty()) return;
  TImageP image = (TImageP)getImage(true);
  TToonzImageP ti  = (TToonzImageP)image;
  TRasterImageP ri = (TRasterImageP)image;
  if (!ti && !ri) return;
  if (!m_rasterSelection.isEditable()) return;
  if (!isFloating()) m_rasterSelection.makeFloating();
  m_freeDeformers.push_back(
      new RasterFreeDeformer(m_rasterSelection.getFloatingSelection()));
  std::vector<TStroke> strokes = m_rasterSelection.getOriginalStrokes();
  if (!strokes.empty()) {
    TVectorImage *vi = new TVectorImage();
    std::set<int> indices;
    // Devo deformare anche gli strokes della selezione!!!
    int i;
    for (i = 0; i < (int)strokes.size(); i++) {
      vi->addStroke(new TStroke(strokes[i]));
      indices.insert(i);
    }
    m_selectionFreeDeformer = new VectorFreeDeformer(vi, indices);
    m_selectionFreeDeformer->setPreserveThickness(true);
  }
}
transformFloatingSelection()
void RasterSelectionTool::transformFloatingSelection (const TAffine & affine, const TPointD & center, const DragSelectionTool::FourPoints & points)
{
  m_rasterSelection.setTransformation(affine);
  if (isFloating()) {
    setBBox(points);
    setCenter(center);
  }
  invalidate();
}
updateTranslation()
void RasterSelectionTool::updateTranslation () override protected virtual
Reimplemented from TTool.
{
  if (m_targetType & ToonzImage)
    m_modifySavebox.setQStringName(tr("Modify Savebox"));
  m_noAntialiasing.setQStringName(tr("No Antialiasing"));
  SelectionTool::updateTranslation();
}
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/tnztools/rasterselectiontool.h
E:/opentoonz/toonz/sources/tnztools/rasterselectiontool.cpp