opentoonz: ShaderInterface::ParameterConcept Class Reference
ShaderInterface::ParameterConcept Class Reference final
Public Member Functions
ParameterConcept (ParameterConceptType type, const QString &label)
bool isUI () const
Public Member Functions inherited from TPersist
virtual void loadData (TIStream &is)=0
virtual void saveData (TOStream &os)=0
std::string getStreamTag () const
virtual const TPersistDeclaration * getDeclaration () const =0
Public Attributes
ParameterConceptType m_type
The concept type (typically composite)
QString m_label
Name to be shown for ui concepts.
std::vector< QString > m_parameterNames
The involved parameters (by name)
Protected Member Functions
void saveData (TOStream &os) override
void loadData (TIStream &is) override
Additional Inherited Members
Public Types inherited from TPersist
typedef TPersist * CreateProc()
Static Public Member Functions inherited from TPersist
static void declare (CreateProc *)
static TPersist * create (const std::string &name)
Detailed Description
Constructor & Destructor Documentation
ParameterConcept() [1/2]
ShaderInterface::ParameterConcept::ParameterConcept () inline
: m_type(CONCEPT_NONE) {}
ParameterConcept() [2/2]
ShaderInterface::ParameterConcept::ParameterConcept (ParameterConceptType type, const QString & label) inline
        : m_type(type), m_label(label) {}
Member Function Documentation
isUI()
bool ShaderInterface::ParameterConcept::isUI () const inline
                      {
      return m_type >= UI_CONCEPTS && m_type < CONCEPTSCOUNT;
    }
loadData()
void ShaderInterface::ParameterConcept::loadData (TIStream & is) override protected virtual
 This is a pure virtual function and must be overridden with a method
that implements the object loading from a stream (i.e take the object's features from a formatted data stream). For example the TStageObject class use his implementation to take the values of the parameters that characterizes a stage object as name, coordinates, etc... from a file. is is an input file stream
Implements TPersist.
{
  // Read the concept type
  QString conceptName;
  is >> conceptName;
  m_type = ParameterConceptType(std::find_if(l_conceptNames,
                                             l_conceptNames + CONCEPTSCOUNT,
                                             ::CaselessCompare(conceptName)) -
                                l_conceptNames);
  if (m_type == CONCEPTSCOUNT) {
    m_type = CONCEPT_NONE;
    ::dumpError(
        is, L"Unrecognized concept type '" + conceptName.toStdWString() + L"'");
  }
  // Read any associated parameter names
  std::string tagName;
  while (is.openChild(tagName)) {
    if (tagName == l_names[PARAMETER]) {
      QString name;
      is >> name;
      m_parameterNames.push_back(name);
      is.closeChild();
    } else if (tagName == l_names[NAME])
      is >> m_label, is.closeChild();
    else
      ::skipTag(is, tagName);
  }
}
References TIStream::closeChild(), and TIStream::openChild().
saveData()
void ShaderInterface::ParameterConcept::saveData (TOStream & os) override protected virtual
 This is a pure virtual function and must be overridden with a method
that implements the object saving to a data stream (i.e put the object's features on a formatted data stream). For example the TStageObject class use his implementation to save the values of the parameters that characterizes a stage object as name, coordinates, etc... on a file os is an output file stream.
Implements TPersist.
{
  os << l_conceptNames[m_type];
  if (!m_label.isEmpty()) {
    os.openChild(l_names[NAME]);
    os << m_label;
    os.closeChild();
  }
  int n, nCount = int(m_parameterNames.size());
  for (n = 0; n != nCount; ++n) {
    os.openChild(l_names[PARAMETER]);
    os << m_parameterNames[n];
    os.closeChild();
  }
}
References TOStream::closeChild(), and TOStream::openChild().
Member Data Documentation
m_label
QString ShaderInterface::ParameterConcept::m_label
Name to be shown for ui concepts.
m_parameterNames
std::vector<QString> ShaderInterface::ParameterConcept::m_parameterNames
The involved parameters (by name)
m_type
ParameterConceptType ShaderInterface::ParameterConcept::m_type
The concept type (typically composite)
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/stdfx/shaderinterface.h
E:/opentoonz/toonz/sources/stdfx/shaderinterface.cpp