opentoonz: MeshTexturizer Class Reference
MeshTexturizer Class Reference
The MeshTexturizer class acts as a management wrapper to OpenGL texturing capabilities, in particular concerning texture virtualization.
#include <meshtexturizer.h>
Classes
class Imp
struct TextureData
The MeshTexturizer-owned data about a texture.
Public Types
enum PremultMode { NONPREMULTIPLIED , PREMULTIPLIED }
Premultiplication specifier for texture binding.
Public Member Functions
int bindTexture (const TRaster32P &ras, const TRectD &geometry, PremultMode premultiplyMode=NONPREMULTIPLIED)
TextureData * getTextureData (int textureId)
void rebindTexture (int textureId, const TRaster32P &ras, const TRectD &geometry, PremultMode premultiplyMode=NONPREMULTIPLIED)
void unbindTexture (int textureId)
id to a new image.
Detailed Description
The MeshTexturizer class acts as a management wrapper to OpenGL texturing capabilities, in particular concerning texture virtualization.
The first step in OpenGL texturing requires copying a texture into the video ram (VRAM). Now, OpenGL documentation specifies that, although there is no limit to the number of allowed textures, there are limits to the size of said textures, which can be tested by asking OpenGL whether it can accommodate specific texture requests or not.
Technically, the MeshTexturizer class acts as a virtualization manager that can be used to allow texturization with arbitrary texture sizes. The manager accepts raster images that are cut up into tiles and bound to VRAM.
Please, observe that the number of texture objects is typically not an issue, as OpenGL is able to swap texture objects between RAM and VRAM, depending on which textures have been used most frequently. In other words, since MeshTexturizer ensures the granularity required by OpenGL, textures can be used until the process runs out of memory - of course, swapping can be a source of slowdowns, though.
Remarks
Subdivision into tiles is designed to work for both premultiplied and non-premultiplied textures.
MeshTexturizer instances are thread-safe.
Member Enumeration Documentation
PremultMode
enum MeshTexturizer::PremultMode
Premultiplication specifier for texture binding.
Enumerator
NONPREMULTIPLIED
Texture is not premultiplied.
PREMULTIPLIED
Texture is premultiplied.
  { NONPREMULTIPLIED,
    PREMULTIPLIED,
  };
Constructor & Destructor Documentation
MeshTexturizer()
MeshTexturizer::MeshTexturizer ()
: m_imp(new Imp) {}
~MeshTexturizer()
MeshTexturizer::~MeshTexturizer ()
{}
Member Function Documentation
bindTexture()
int MeshTexturizer::bindTexture (const TRaster32P & ras, const TRectD & geometry, PremultMode premultiplyMode = NONPREMULTIPLIED)
The bindTexture() function is used to specify a 32-bit fullcolor raster as a texture to be used for mesh rendering. The supplied geometry rect defines its position with respect to compiled meshes.
Remarks
The premultiplication specifier is used to tell the texturizer how to add a proper transparent border surrounding texture tiles. This border is essential to draw transparent pixels beyond a texture tile's content.
Returns
The internal id used to reference to the input raster.
Parameters
geometry Moves a copy of the supplied raster image to VRAM,
{
  QWriteLocker locker(&m_imp->m_lock);
  // Backup the state of some specific OpenGL variables that will be changed
  // throughout the code
  int row_length, alignment;
  glGetIntegerv(GL_UNPACK_ROW_LENGTH, &row_length);
  glGetIntegerv(GL_UNPACK_ALIGNMENT, &alignment);
  // Initialize a new texture data
  int dataIdx =
      m_imp->m_textureDatas.push_back(std::make_shared<TextureData>(geom));
  // Textures must have 2-power sizes. So, let's start with the smallest 2 power
  // >= ras's sizes.
  int textureLx =
      tcg::numeric_ops::GE_2Power((unsigned int)ras->getLx() + TOTAL_BORDER_2);
  int textureLy =
      tcg::numeric_ops::GE_2Power((unsigned int)ras->getLy() + TOTAL_BORDER_2);
  // We'll assume a strict granularity max of 2048 x 2048 textures, if it is
  // possible.
  textureLx = std::min(textureLx, getMaxTextureTileSize());
  textureLy = std::min(textureLy, getMaxTextureTileSize());
  // Allocate a suitable texture raster. The texture will include a transparent
  // 1-pix border
  // that is needed to perform texture mapping with GL_CLAMP transparent
  // wrapping
  TRaster32P tex(textureLx, textureLy);
  // Now, let's tile the specified raster. We'll start from the lower-left
  // corner in case
  // the raster can be completely included in just one tile
  int lx = ras->getLx(), ly = ras->getLy();
  int tileLx = textureLx - TOTAL_BORDER_2,
      tileLy = textureLy - TOTAL_BORDER_2;  // Texture size without border
  int xEntireCells = (lx - 1) / tileLx,
      yEntireCells =
          (ly - 1) /
          tileLy;  // +1 so in case l == tileL, we get the remainder case
  int lastTexLx = tcg::numeric_ops::GE_2Power(
      (unsigned int)(lx - xEntireCells * tileLx + TOTAL_BORDER_2));
  int lastTexLy = tcg::numeric_ops::GE_2Power(
      (unsigned int)(ly - yEntireCells * tileLy + TOTAL_BORDER_2));
  int lastTileLx = lastTexLx - TOTAL_BORDER_2,
      lastTileLy = lastTexLy - TOTAL_BORDER_2;
  bool premultiplied = (premultiplyMode == PREMULTIPLIED);
  int i, j;
  for (i = 0; i < yEntireCells; ++i) {
    for (j = 0; j < xEntireCells; ++j)
      // Perform a (possibly subdividing) allocation of the specified tile
      m_imp->allocateTextures(dataIdx, ras, tex, j * tileLx, i * tileLy, tileLx,
                              tileLy, premultiplied);
    m_imp->allocateTextures(dataIdx, ras, tex, j * tileLx, i * tileLy,
                            lastTileLx, tileLy, premultiplied);
  }
  for (j = 0; j < xEntireCells; ++j)
    m_imp->allocateTextures(dataIdx, ras, tex, j * tileLx, i * tileLy, tileLx,
                            lastTileLy, premultiplied);
  m_imp->allocateTextures(dataIdx, ras, tex, j * tileLx, i * tileLy, lastTileLx,
                          lastTileLy, premultiplied);
  // Restore OpenGL variables
  glPixelStorei(GL_UNPACK_ROW_LENGTH, row_length);
  glPixelStorei(GL_UNPACK_ALIGNMENT, alignment);
  return dataIdx;
}
References tcg::numeric_ops::GE_2Power(), and PREMULTIPLIED.
Referenced by TTexturesStorage::loadTexture(), and rebindTexture().
getTextureData()
MeshTexturizer::TextureData * MeshTexturizer::getTextureData (int textureId)
and assigns an identification number to it.
Parameters
ras Texture to be copied to VRAM.
geometry The texture's geometry in the world - with respect to compiled meshes.
premultiplyMode Specified whether ras is to be intended premultiplied or not.
Warning
The pointer returned by getTextureData() is owned by this class - it must not be deleted. Retrieves the texture data built from a previously
{
  QReadLocker locker(&m_imp->m_lock);
  return m_imp->getTextureData(textureId);
}
Referenced by TTexturesStorage::loadTexture().
rebindTexture()
void MeshTexturizer::rebindTexture (int textureId, const TRaster32P & ras, const TRectD & geometry, PremultMode premultiplyMode = NONPREMULTIPLIED)
bound texture image.
Parameters
textureId Identifier of the texture to be retrieved
Returns
See summary.
The texture identifier specified to rebindTexture() is retained, and the effect is that of an unbindTexture() - bindTexture() combo.
Note
Pre-compiled mesh data against the old texture can be retained if the newly supplied texture size and geometry are the same as the old one.
Parameters
geometry Rebinds the image bound to the specified texture
{
  QWriteLocker locker(&m_imp->m_lock);
  unbindTexture(texId);
  int newTexId = bindTexture(ras, geom, premultiplyMode);
  assert(texId == newTexId);
}
References bindTexture(), and unbindTexture().
unbindTexture()
void MeshTexturizer::unbindTexture (int textureId)
id to a new image.
Deletes the texture associated to the passed id.
Parameters
textureId
{
  QWriteLocker locker(&m_imp->m_lock);
  m_imp->m_textureDatas.erase(texId);
}
Referenced by rebindTexture().
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/ext/meshtexturizer.h
E:/opentoonz/toonz/sources/tnzext/meshtexturizer.cpp