opentoonz: DVGui::StyleSample Class Reference
DVGui::StyleSample Class Reference final
The StyleSample class provides to view a square color.
Signals
void clicked ()
Public Member Functions
StyleSample (QWidget *parent, int sizeX, int sizeY)
void enableClick (bool on)
void setStyle (TColorStyle &style, int colorParameterIndex)
TColorStyle * getStyle () const
void setColor (const TPixel32 &color)
void setChessboardColors (const TPixel32 &col1, const TPixel32 &col2)
void setIsEditing (bool isEditing)
bool isEditing () const
void setEnable (bool drawEnable)
bool isEnable () const
void setCloneStyle (bool enable)
void setSystemChessboard (bool enable)
Protected Member Functions
void paintEvent (QPaintEvent *event) override
void mousePressEvent (QMouseEvent *) override
void mouseDoubleClickEvent (QMouseEvent *event) override
Detailed Description
The StyleSample class provides to view a square color.
Inherits QWidget.
By default square color is set to TPixel32(235,235,235,255), you can set other color using setColor(); you can also define current color with a style TColorStyle, getStyle(), using setStyle(). You can pass to constructor square size.
StyleSample permit to manage click event, it's possile to enable this feature setting enableClick(bool on) to true. If it is enable when click in square class emit the signal clicked(const TColorStyle &style).
Constructor & Destructor Documentation
StyleSample()
StyleSample::StyleSample (QWidget * parent, int sizeX, int sizeY)
    : m_samplePixmap(sizeX, sizeY, QImage::Format_ARGB32)
    , m_bgRas(sizeX, sizeY)
    , m_style(0)
    , m_clickEnabled(false)
    , m_chessColor1(0, 0, 0)
    , m_chessColor2(255, 255, 255)
    , m_sysChessboard(false)
    , m_stretch(true)
    , m_isEditing(false) {
  setMinimumSize(sizeX, sizeY);
  setColor(TPixel32::Transparent);
  TRop::checkBoard(m_bgRas, m_chessColor1, m_chessColor2,
                   TDimensionD(sizeX / 8, sizeX / 8), TPointD(0, 0));
  setEnable(true);
}
~StyleSample()
StyleSample::~StyleSample ()
{
  if (m_style) delete m_style;
  m_style = 0;
}
Member Function Documentation
clicked
void DVGui::StyleSample::clicked () signal
This signal is emitted when click event is enable and a style is set.
Referenced by mousePressEvent().
enableClick()
void DVGui::StyleSample::enableClick (bool on) inline
Set click event enable if is true, disable otherwise. If true setStyle store current style and buttonPress emit signal clicked(const TColorStyle &style).
{ m_clickEnabled = on; }
getStyle()
TColorStyle * StyleSample::getStyle () const
Return current StyleSample TColorStyle style.
{ return m_style; }
isEditing()
bool DVGui::StyleSample::isEditing () const inline
{ return m_isEditing; }
isEnable()
bool DVGui::StyleSample::isEnable () const inline
{ return m_drawEnable; }
mouseDoubleClickEvent()
void StyleSample::mouseDoubleClickEvent (QMouseEvent * event) override protected
{ event->ignore(); }
mousePressEvent()
void StyleSample::mousePressEvent (QMouseEvent * event) override protected
If exist current style and event click is enable emit signal clicked(const TColorStyle &style).
{
  if (m_clickEnabled)
    emit clicked();
  else
    event->ignore();
}
References clicked().
paintEvent()
void StyleSample::paintEvent (QPaintEvent * event) override protected
Paint square color.
{
  if (!isEnable()) return;
  QPainter painter(this);
  if (m_sysChessboard) {
    painter.drawTiledPixmap(rect(),
                            DVGui::CommonChessboard::instance()->getPixmap());
  } else {
    QImage img(m_bgRas->getRawData(), m_bgRas->getLx(), m_bgRas->getLy(),
               QImage::Format_ARGB32);
    painter.drawImage(0, 0, img.scaled(size()));
  }
  if (m_stretch) {
    painter.drawImage(0, 0, m_samplePixmap.scaled(size()));
  } else {
    // put the icon on the left
    int x = 0;
    // int x = (width() - m_samplePixmap.width()) / 2;
    int y = (height() - m_samplePixmap.height()) / 2;
    painter.fillRect(rect(), m_currentColor);
    painter.drawImage(x, y, m_samplePixmap);
  }
  if (m_isEditing) {
    // QRect rect(0,0,m_bgRas->getLx(),m_bgRas->getLy());
    painter.setPen(Qt::white);
    painter.drawRect(rect().adjusted(0, 0, -1, -1));
    painter.drawRect(rect().adjusted(2, 2, -3, -3));
    painter.setPen(QColor(180, 210, 255));
    painter.drawRect(rect().adjusted(1, 1, -2, -2));
  }
}
setChessboardColors()
void StyleSample::setChessboardColors (const TPixel32 & col1, const TPixel32 & col2)
{
  m_chessColor1 = col1;
  m_chessColor2 = col2;
  TRop::checkBoard(m_bgRas, m_chessColor1, m_chessColor2,
                   TDimensionD(m_bgRas->getLx() / 8, m_bgRas->getLy() / 8),
                   TPointD(0, 0));
  update();
}
setCloneStyle()
void DVGui::StyleSample::setCloneStyle (bool enable) inline
{ m_cloneStyle = enable; }
setColor()
void StyleSample::setColor (const TPixel32 & pixel)
Update current square colore to TPixel32 color. Useful for efficiency if click event is disable.
{
  QColor color(pixel.r, pixel.g, pixel.b, pixel.m);
  if (LutManager::instance()->isValid()) LutManager::instance()->convert(color);
  m_samplePixmap.fill(color.rgba());
  update();
}
Referenced by DVGui::ColorField::onAlphaChannelChanged(), DVGui::ColorField::onBlueChannelChanged(), DVGui::ColorField::onGreenChannelChanged(), DVGui::ColorField::onRedChannelChanged(), DVGui::ColorField::setAlphaActive(), and setStyle().
setEnable()
void DVGui::StyleSample::setEnable (bool drawEnable) inline
{ m_drawEnable = drawEnable; }
setIsEditing()
void DVGui::StyleSample::setIsEditing (bool isEditing) inline
{
    m_isEditing = isEditing;
    update();
  }
setStyle()
void StyleSample::setStyle (TColorStyle & style, int colorParameterIndex)
Update current square colore and, if click event is enable set current StyleSample TColorStyle style to style.
{
  // Store current color
  TPixel32 color = style.getColorParamValue(colorParameterIndex);
  m_currentColor = QColor(color.r, color.g, color.b, color.m);
  if (LutManager::instance()->isValid())
    LutManager::instance()->convert(m_currentColor);
  /*-- TSolidColorStyleの場合のみ、単色塗りつぶし --*/
  if (style.getTagId() == 3) {
    setColor(style.getMainColor());
    m_stretch = true;
  } else {
    TDimension iconDim(width(), height());
    // obtain square icon for the TMyPaintBrushStyle
    // so that the checkerboard color will become consistent with solido style
    // when the main color is semi-transparent.
    if (style.getTagId() == 4001) {
      int d   = std::min(width(), height());
      iconDim = TDimension(d, d);
    }
    TRaster32P icon = style.getIcon(iconDim);
    // TRaster32P icon =
    //  style.getIcon(qsize2Dimension(m_samplePixmap.rect().size()));
    m_samplePixmap = rasterToQImage(icon, false);  // modified in 6.2
    m_stretch      = false;
    update();
  }
  if (m_cloneStyle) {
    if (m_style) delete m_style;  // avoid memory leak
    m_style = style.clone();
  }
}
References TColorStyle::clone(), TColorStyle::getColorParamValue(), TColorStyle::getIcon(), TColorStyle::getMainColor(), TColorStyle::getTagId(), and setColor().
setSystemChessboard()
void DVGui::StyleSample::setSystemChessboard (bool enable) inline
{ m_sysChessboard = enable; }
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/toonzqt/colorfield.h
E:/opentoonz/toonz/sources/toonzqt/colorfield.cpp