opentoonz: TImageReaderSvg Class Reference
TImageReaderSvg Class Reference final
Public Member Functions
TImageReaderSvg (const TFilePath &path, TLevelP &level)
TImageP load () override
Public Member Functions inherited from TImageReader
TImageReader (const TFilePath &path)
virtual const TImageInfo * getImageInfo () const
TFilePath getFilePath () const
TPropertyGroup * getProperties ()
void setProperties (const TPropertyGroup *)
virtual TImageP load ()
void load (const TRasterP &ras, const TPoint &pos=TPoint(0, 0), int shrinkX=1, int shrinkY=1)
virtual TImageP loadIcon ()
void doReadGraytones (bool readThem)
void enable16BitRead (bool is64bitEnabled)
int getShrink () const
void setShrink (int shrink)
void setRegion (TRect rect)
TRect getRegion () const
void getTzpPaletteColorNames (std::map< int, std::pair< std::string, std::string > > &pltColorNames)
Public Member Functions inherited from TSmartObject
TSmartObject (ClassCode classCode)
void addRef ()
void release ()
TINT32 getRefCount () const
Additional Inherited Members
Public Types inherited from TSmartObject
typedef short ClassCode
Static Public Member Functions inherited from TImageReader
static void setSafeModeReadingForTzl (bool activated)
static bool load (const TFilePath &, TRasterP &)
static bool load (const TFilePath &, TImageP &)
static void getSupportedFormats (QStringList &names)
static void define (QString extension, TImageReaderCreateProc *proc)
Static Public Member Functions inherited from TSmartObject
static TINT32 getInstanceCount (ClassCode code)
Protected Member Functions inherited from TImageReader
void open ()
void close ()
bool isOpen () const
Protected Attributes inherited from TImageReader
TFilePath m_path
FILE * m_file
Tiio::Reader * m_reader
Tiio::VectorReader * m_vectorReader
bool m_readGreytones
bool m_is64BitEnabled
int m_shrink
TRect m_region
Static Protected Attributes inherited from TImageReader
static bool m_safeMode = false
Detailed Description
Constructor & Destructor Documentation
TImageReaderSvg()
TImageReaderSvg::TImageReaderSvg (const TFilePath & path, TLevelP & level) inline
      : TImageReader(path), m_level(level) {}
Member Function Documentation
load()
TImageP TImageReaderSvg::load () override virtual
Load Image from disk. If set region then loads only image's region. If set shrink then loads image (or region, if set) with shrink.
Note: if the region, or part of it, is not contained in the image then returns only the intersection between the image and region. If the intersection is void returns TImageP();
Reimplemented from TImageReader.
{
  NSVGimage *svgImg =
      nsvgParseFromFile(m_path.getQString().toStdString().c_str());
  if (!svgImg) return TImageP();
  TPalette *plt = m_level->getPalette();
  assert(plt);
  TVectorImage *vimage = new TVectorImage();
  vimage->setPalette(plt);
  for (NSVGshape *shape = svgImg->shapes; shape; shape = shape->next) {
    int inkIndex, paintIndex;
    NSVGpath *path = shape->paths;
    if (!path) continue;
    // TVectorImageP vapp = new TVectorImage();
    // TPalette* appPlt = new TPalette();
    // vapp->setPalette(appPlt);
    TPixel color(shape->fillColor & 0xFF, (shape->fillColor >> 8) & 0xFF,
                 shape->fillColor >> 16);
    if (!shape->hasFill) {
      assert(color == TPixel::Black);
      shape->hasFill = true;
    }
    if (shape->hasStroke) inkIndex = findColor(plt, shape->strokeColor);
    if (shape->hasFill) paintIndex = findColor(plt, shape->fillColor);
    // vapp->setPalette(plt.getPointer());
    int startStrokeIndex = vimage->getStrokeCount();
    for (; path; path = path->next) {
      TStroke *s = buildStroke(path, shape->hasStroke ? shape->strokeWidth : 0);
      if (!s) continue;
      s->setStyle(shape->hasStroke ? inkIndex : 0);
      vimage->addStroke(s);
    }
    if (startStrokeIndex == vimage->getStrokeCount()) continue;
    vimage->group(startStrokeIndex,
                  vimage->getStrokeCount() - startStrokeIndex);
    if (shape->hasFill) {
      vimage->enterGroup(startStrokeIndex);
      vimage->selectFill(TRectD(-9999999, -9999999, 9999999, 9999999), 0,
                         paintIndex, true, true, false);
      vimage->exitGroup();
    }
    /* vapp->findRegions();
if (paintIndex!=-1)
for (int i=0; i<(int)vapp->getRegionCount(); i++)
vapp->getRegion(i)->setStyle(paintIndex);
std::vector<int> indexes(vapp->getStrokeCount());
for (int i=0; i<(int)vapp->getStrokeCount() ;i++)
indexes[i] = vimage->getStrokeCount()+i;
vimage->insertImage(vapp, indexes);*/
    // delete appPlt;
  }
  nsvgDelete(svgImg);
  // if (m_level)
  // m_level->setPalette(plt);
  return TImageP(vimage);
}
References TVectorImage::addStroke(), TXshSimpleLevel::getPalette(), TVectorImage::getStrokeCount(), TVectorImage::group(), TVectorImage::selectFill(), TImage::setPalette(), and TStroke::setStyle().
The documentation for this class was generated from the following file:
E:/opentoonz/toonz/sources/image/svg/tiio_svg.cpp