opentoonz: StageSchematicScene Class Reference
StageSchematicScene Class Reference final
#include <stageschematicscene.h>
Signals
void editObject ()
void doCollapse (QList< TStageObjectId >)
void doExplodeChild (QList< TStageObjectId >)
Public Member Functions
StageSchematicScene (QWidget *parent)
void updateScene () override
Clear all item an regenerate the Stage Schematic graph.
QGraphicsItem * getCurrentNode () override
Reurns the current node.
void reorderScene () override
Replace all nodes in the scene.
TXsheet * getXsheet ()
TXsheetHandle * getXsheetHandle ()
void setXsheetHandle (TXsheetHandle *xshHandle)
void setObjectHandle (TObjectHandle *objHandle)
void setColumnHandle (TColumnHandle *colHandle)
void setFxHandle (TFxHandle *fxHandle)
void setSceneHandle (TSceneHandle *sceneHandle)
void setFrameHandle (TFrameHandle *frameHandle)
TStageObjectId getCurrentObject ()
TFrameHandle * getFrameHandle ()
TColumnHandle * getColumnHandle ()
void updateNestedGroupEditors (StageSchematicNode *node, const QPointF &newPos)
void resizeNodes (bool maximizedNode)
bool isShowLetterOnPortFlagEnabled ()
SchematicViewer * getSchematicViewer ()
StageObjectSelection * getStageSelection () const
Public Member Functions inherited from SchematicScene
SchematicScene (QWidget *parent)
void clearAllItems ()
virtual QGraphicsItem * getCurrentNode ()
virtual void reorderScene ()=0
virtual void updateScene ()=0
Protected Slots
void onSelectionSwitched (TSelection *oldSel, TSelection *newSel) override
void onPegbarAdded ()
void onSplineAdded ()
void onCameraAdded ()
void onResetCenter ()
void onCameraActivate ()
void onRemoveSpline ()
void onSaveSpline ()
void onLoadSpline ()
void onPathToggled (int state)
void onCpToggled (bool toggled)
void onXsheetChanged ()
void onSceneChanged ()
void onCurrentObjectChanged (const TStageObjectId &, bool)
void onCurrentColumnChanged (int)
void onSelectionChanged ()
void onCollapse (QList< TStageObjectId >)
void onEditGroup ()
void onNodeChangedSize ()
void onSwitchPortModeToggled (bool withLetter)
Protected Slots inherited from SchematicScene
virtual void onSelectionSwitched (TSelection *, TSelection *)
Protected Member Functions
void contextMenuEvent (QGraphicsSceneContextMenuEvent *cme) override
void mousePressEvent (QGraphicsSceneMouseEvent *me) override
Protected Member Functions inherited from SchematicScene
bool isAnEmptyZone (const QRectF &rect)
Returns true if no nodes intersects rect.
QVector< SchematicNode * > getPlacedNode (SchematicNode *node)
void showEvent (QShowEvent *se)
void hideEvent (QHideEvent *se)
Additional Inherited Members
Protected Types inherited from SchematicScene
enum GridDimension { eLarge , eSmall }
Protected Attributes inherited from SchematicScene
QList< SchematicLink * > m_highlightedLinks
Detailed Description
It is the implementation of the SchematicScene representig the QGraphicsScene for the Stage Schematic. All StageSchematicNode, StageSchematicSplineNode and link are pleced and handled in this scene. The scene maintains two mapping: one for StageSchematicNode and one for StageSchematicSplineNode. These mapping can be used to retrieve nodes and spline.
To regenearte the scene use the updateScene().
To oreder nodes in the scene use the reorderScene().
Constructor & Destructor Documentation
StageSchematicScene()
StageSchematicScene::StageSchematicScene (QWidget * parent)
    : SchematicScene(parent)
    , m_nextNodePos(0, 0)
    , m_xshHandle(0)
    , m_objHandle(0)
    , m_colHandle(0)
    , m_sceneHandle(0)
    , m_frameHandle(0)
    , m_gridDimension(eSmall)
    , m_showLetterOnPortFlag(ShowLetterOnOutputPortOfStageNode != 0)
    , m_viewer() {
  m_viewer = (SchematicViewer *)parent;
  QPointF sceneCenter = sceneRect().center();
  m_firstPos          = TPointD(sceneCenter.x(), sceneCenter.y());
  m_selection = new StageObjectSelection();
  connect(m_selection, SIGNAL(doCollapse(QList<TStageObjectId>)), this,
          SLOT(onCollapse(QList<TStageObjectId>)));
  connect(m_selection, SIGNAL(doExplodeChild(QList<TStageObjectId>)), this,
          SIGNAL(doExplodeChild(QList<TStageObjectId>)));
  connect(this, SIGNAL(selectionChanged()), this, SLOT(onSelectionChanged()));
  m_highlightedLinks.clear();
}
~StageSchematicScene()
StageSchematicScene::~StageSchematicScene ()
{}
Member Function Documentation
contextMenuEvent()
void StageSchematicScene::contextMenuEvent (QGraphicsSceneContextMenuEvent * cme) override protected
{
  QPointF scenePos                = cme->scenePos();
  QList<QGraphicsItem *> itemList = items(scenePos);
  if (!itemList.isEmpty()) {
    SchematicScene::contextMenuEvent(cme);
    return;
  }
  QMenu menu(views()[0]);
  // AddPegbar
  QAction *addPegbar = new QAction(tr("&New Pegbar"), &menu);
  connect(addPegbar, SIGNAL(triggered()), this, SLOT(onPegbarAdded()));
  // AddSpline
  QAction *addSpline = new QAction(tr("&New Motion Path"), &menu);
  connect(addSpline, SIGNAL(triggered()), this, SLOT(onSplineAdded()));
  // AddCamera
  QAction *addCamera = new QAction(tr("&New Camera"), &menu);
  connect(addCamera, SIGNAL(triggered()), this, SLOT(onCameraAdded()));
  QAction *paste = CommandManager::instance()->getAction("MI_Paste");
  // this is to place the node at the clicked position
  addPegbar->setData(cme->scenePos());
  addSpline->setData(cme->scenePos());
  addCamera->setData(cme->scenePos());
  menu.addAction(addPegbar);
  menu.addAction(addCamera);
  menu.addAction(addSpline);
  // Close sub xsheet and move to parent sheet
  ToonzScene *scene      = m_sceneHandle->getScene();
  ChildStack *childStack = scene->getChildStack();
  if (childStack && childStack->getAncestorCount() > 0) {
    menu.addSeparator();
    menu.addAction(CommandManager::instance()->getAction("MI_CloseChild"));
  }
  menu.addSeparator();
  menu.addAction(paste);
  m_selection->setPastePosition(TPointD(scenePos.x(), scenePos.y()));
  menu.exec(cme->screenPos());
}
getColumnHandle()
TColumnHandle * StageSchematicScene::getColumnHandle () inline
{ return m_colHandle; }
getCurrentNode()
QGraphicsItem * StageSchematicScene::getCurrentNode () override virtual
Reurns the current node.
Reimplemented from SchematicScene.
{
  QList<QGraphicsItem *> allItems = items();
  for (auto const item : allItems) {
    StageSchematicNode *node = dynamic_cast<StageSchematicNode *>(item);
    if (node && node->getStageObject()->getId() == m_objHandle->getObjectId())
      return node;
  }
  return 0;
}
References TStageObject::getId().
getCurrentObject()
TStageObjectId StageSchematicScene::getCurrentObject ()
{
  return m_objHandle->getObjectId();
}
getFrameHandle()
TFrameHandle * StageSchematicScene::getFrameHandle () inline
{ return m_frameHandle; }
getSchematicViewer()
SchematicViewer * StageSchematicScene::getSchematicViewer () inline
{ return m_viewer; }
getStageSelection()
StageObjectSelection * StageSchematicScene::getStageSelection () const inline
{ return m_selection; }
getXsheet()
TXsheet * StageSchematicScene::getXsheet ()
{ return m_xshHandle->getXsheet(); }
getXsheetHandle()
TXsheetHandle * StageSchematicScene::getXsheetHandle () inline
{ return m_xshHandle; }
isShowLetterOnPortFlagEnabled()
bool StageSchematicScene::isShowLetterOnPortFlagEnabled () inline
{ return m_showLetterOnPortFlag; }
mousePressEvent()
void StageSchematicScene::mousePressEvent (QGraphicsSceneMouseEvent * me) override protected
{
  QList<QGraphicsItem *> items = selectedItems();
  SchematicScene::mousePressEvent(me);
  if (me->button() == Qt::MidButton) {
    int i;
    for (i = 0; i < items.size(); i++) items[i]->setSelected(true);
  }
}
onCameraActivate
void StageSchematicScene::onCameraActivate () protected slot
{
  TStageObjectCmd::setAsActiveCamera(m_xshHandle, m_objHandle);
}
onCameraAdded
void StageSchematicScene::onCameraAdded () protected slot
{
  // if this command called from the context menu, place the node at the
  // cllicked position
  // clickedPos will be null(0,0) if it called from the toolbar
  QPointF clickedPos = qobject_cast<QAction *>(sender())->data().toPointF();
  TStageObjectCmd::addNewCamera(m_xshHandle, m_objHandle, clickedPos);
}
onCollapse
void StageSchematicScene::onCollapse (QList< TStageObjectId > objects) protected slot
{
  emit doCollapse(objects);
}
onCpToggled
void StageSchematicScene::onCpToggled (bool toggled) protected slot
{
  TStageObjectId objId = m_objHandle->getObjectId();
  TStageObject *obj    = m_xshHandle->getXsheet()->getStageObject(objId);
  TStageObjectCmd::enableSplineUppk(obj, toggled, m_xshHandle);
  update();
}
onCurrentColumnChanged
void StageSchematicScene::onCurrentColumnChanged (int index) protected slot
{
  m_colHandle->setColumnIndex(index);
}
onCurrentObjectChanged
void StageSchematicScene::onCurrentObjectChanged (const TStageObjectId & id, bool isSpline) protected slot
{
  // revert the pre-selected node to normal text color
  QMap<TStageObjectId, StageSchematicNode *>::iterator it;
  it = m_nodeTable.find(getCurrentObject());
  if (it != m_nodeTable.end()) {
    it.value()->update();
  }
  m_objHandle->setObjectId(id);
  if (m_frameHandle->isEditingLevel()) return;
  m_objHandle->setIsSpline(isSpline);
}
onEditGroup
void StageSchematicScene::onEditGroup () protected slot
{
  if (m_selection->isEmpty()) return;
  TStageObjectTree *pegTree  = m_xshHandle->getXsheet()->getStageObjectTree();
  QList<TStageObjectId> objs = m_selection->getObjects();
  int i;
  for (i = 0; i < objs.size(); i++) {
    TStageObject *obj = pegTree->getStageObject(objs[i], false);
    if (obj && obj->isGrouped() && !obj->isGroupEditing()) obj->editGroup();
  }
  updateScene();
}
onLoadSpline
void StageSchematicScene::onLoadSpline () protected slot
{
  TFilePath projectFolder =
      m_sceneHandle->getScene()->getProject()->getProjectFolder();
  QString fileNameStr = QFileDialog::getOpenFileName(
      this->views()[0], QObject::tr("Load Motion Path"),
      QString::fromStdWString(projectFolder.getWideString()),
      QObject::tr("Motion Path files (*.mpath)"));
  if (fileNameStr == "") return;
  TFilePath fp(fileNameStr.toStdWString());
  if (fp.getType() == "") fp = fp.withType("mpath");
  try {
    if (!TFileStatus(fp).doesExist()) {
      QString msg;
      msg = "Motion path " + toQString(fp) + " doesn't exists.";
      DVGui::info(msg);
      return;
    }
    assert(m_objHandle->isSpline());
    // ObjectID of the parent node to which the spline is connected
    TStageObjectId id = m_objHandle->getObjectId();
    TXsheet *xsh      = m_xshHandle->getXsheet();
    TStageObjectSpline *spline =
        xsh->getStageObjectTree()->getStageObject(id, false)->getSpline();
    if (!spline) return;
    TIStream is(fp);
    if (is) {
      spline->loadData(is);
      m_objHandle->setSplineObject(spline);
      m_objHandle->commitSplineChanges();
      IconGenerator::instance()->invalidate(spline);
    }
  } catch (...) {
    DVGui::warning(QObject::tr("It is not possible to load the motion path."));
  }
}
onNodeChangedSize
void StageSchematicScene::onNodeChangedSize () protected slot
{
  if (resizingNodes) return;
  updateScene();
}
onPathToggled
void StageSchematicScene::onPathToggled (int state) protected slot
{
  TStageObjectId objId = m_objHandle->getObjectId();
  TStageObject *obj    = m_xshHandle->getXsheet()->getStageObject(objId);
  TStageObjectCmd::enableSplineAim(obj, state, m_xshHandle);
  onSceneChanged();
  update();
}
onPegbarAdded
void StageSchematicScene::onPegbarAdded () protected slot
{
  // if this command called from the context menu, place the node at the
  // cllicked position
  // clickedPos will be null(0,0) if it called from the toolbar
  QPointF clickedPos = qobject_cast<QAction *>(sender())->data().toPointF();
  TStageObjectCmd::addNewPegbar(m_xshHandle, m_objHandle, clickedPos);
}
onRemoveSpline
void StageSchematicScene::onRemoveSpline () protected slot
{ m_selection->deleteSelection(); }
onResetCenter
void StageSchematicScene::onResetCenter () protected slot
{
  TStageObjectId id = m_objHandle->getObjectId();
  TStageObjectCmd::resetCenterAndOffset(id, m_xshHandle);
}
onSaveSpline
void StageSchematicScene::onSaveSpline () protected slot
{
  TFilePath projectFolder =
      m_sceneHandle->getScene()->getProject()->getProjectFolder();
  QString fileNameStr = QFileDialog::getSaveFileName(
      this->views()[0], QObject::tr("Save Motion Path"),
      QString::fromStdWString(projectFolder.getWideString()),
      QObject::tr("Motion Path files (*.mpath)"));
  if (fileNameStr == "") return;
  TFilePath fp(fileNameStr.toStdWString());
  if (fp.getType() == "") fp = fp.withType("mpath");
  try {
    assert(m_objHandle->isSpline());
    TStageObjectId id        = m_objHandle->getObjectId();
    TXsheet *xsh             = m_xshHandle->getXsheet();
    TStageObject *currentObj = xsh->getStageObjectTree()->getStageObject(id);
    if (currentObj == 0) throw "no currentObj";
    TStageObjectSpline *spline = currentObj->getSpline();
    if (spline == 0) throw "no spline";
    TOStream os(fp);
    // Only points are saved
    const TStroke *stroke = spline->getStroke();
    int n                 = stroke ? stroke->getControlPointCount() : 0;
    for (int i = 0; i < n; i++) {
      TThickPoint p = stroke->getControlPoint(i);
      os << p.x << p.y << p.thick;
    }
  } catch (...) {
    DVGui::warning(QObject::tr("It is not possible to save the motion path."));
  }
}
onSceneChanged
void StageSchematicScene::onSceneChanged () protected slot
{
  m_sceneHandle->notifySceneChanged();
}
onSelectionChanged
void StageSchematicScene::onSelectionChanged () protected slot
{
  m_selection->selectNone();
  int i, size = m_highlightedLinks.size();
  for (i = 0; i < size; i++) {
    SchematicLink *link = m_highlightedLinks[i];
    link->setHighlighted(false);
    link->update();
  }
  m_highlightedLinks.clear();
  QList<QGraphicsItem *> slcItems = selectedItems();
  QList<QGraphicsItem *>::iterator it;
  for (it = slcItems.begin(); it != slcItems.end(); it++) {
    StageSchematicGroupNode *groupNode =
        dynamic_cast<StageSchematicGroupNode *>(*it);
    StageSchematicNode *node = dynamic_cast<StageSchematicNode *>(*it);
    if (groupNode) {
      QList<TStageObject *> objs = groupNode->getGroupedObjects();
      for (i = 0; i < objs.size(); i++) m_selection->select(objs[i]->getId());
      highlightLinks(groupNode, true);
    } else if (node) {
      m_selection->select(node->getStageObject()->getId());
      highlightLinks(node, true);
    }
    StageSchematicSplineNode *spline =
        dynamic_cast<StageSchematicSplineNode *>(*it);
    if (spline) {
      m_selection->select(spline->getSpline()->getId());
      StageSchematicSplinePort *port = spline->getParentPort();
      if (port) {
        int i, linkCount = port->getLinkCount();
        for (i = 0; i < linkCount; i++) {
          SchematicLink *link = port->getLink(i);
          link->setHighlighted(true);
          m_highlightedLinks.push_back(link);
        }
      }
    }
    SchematicLink *link = dynamic_cast<SchematicLink *>(*it);
    if (link) m_selection->select(link);
  }
  if (!m_selection->isEmpty()) m_selection->makeCurrent();
}
onSelectionSwitched
void StageSchematicScene::onSelectionSwitched (TSelection * oldSel, TSelection * newSel) override protected slot
{
  if (m_selection == oldSel && m_selection != newSel) clearSelection();
}
onSplineAdded
void StageSchematicScene::onSplineAdded () protected slot
{
  // if this command called from the context menu, place the node at the
  // cllicked position
  // clickedPos will be null(0,0) if it called from the toolbar
  QPointF clickedPos = qobject_cast<QAction *>(sender())->data().toPointF();
  TStageObjectCmd::addNewSpline(m_xshHandle, m_objHandle, m_colHandle,
                                clickedPos);
}
onSwitchPortModeToggled
void StageSchematicScene::onSwitchPortModeToggled (bool withLetter) protected slot
{
  m_showLetterOnPortFlag            = withLetter;
  ShowLetterOnOutputPortOfStageNode = (withLetter) ? 1 : 0;
  updateScene();
}
onXsheetChanged
void StageSchematicScene::onXsheetChanged () protected slot
{
  m_xshHandle->notifyXsheetChanged();
}
reorderScene()
void StageSchematicScene::reorderScene () override virtual
Replace all nodes in the scene.
Implements SchematicScene.
{ placeNodes(); }
resizeNodes()
void StageSchematicScene::resizeNodes (bool maximizedNode)
{
  resizingNodes             = true;
  m_gridDimension           = maximizedNode ? eLarge : eSmall;
  TStageObjectTree *pegTree = m_xshHandle->getXsheet()->getStageObjectTree();
  pegTree->setDagGridDimension(m_gridDimension);
  int i, objCount = pegTree->getStageObjectCount();
  for (i = 0; i < objCount; i++) {
    TStageObject *obj = pegTree->getStageObject(i);
    if (obj && obj->getId().isColumn()) {
      if (!m_nodeTable.contains(obj->getId())) continue;
      StageSchematicColumnNode *node =
          dynamic_cast<StageSchematicColumnNode *>(m_nodeTable[obj->getId()]);
      assert(node);
      node->resize(maximizedNode);
    }
    if (obj && !obj->getId().isCamera())
      updatePositionOnResize(obj, maximizedNode);
  }
  int splineCount = pegTree->getSplineCount();
  for (i = 0; i < splineCount; i++) {
    TStageObjectSpline *spl = pegTree->getSpline(i);
    if (spl) {
      if (!m_splineTable.contains(spl)) continue;
      StageSchematicSplineNode *node =
          dynamic_cast<StageSchematicSplineNode *>(m_splineTable[spl]);
      assert(node);
      node->resize(maximizedNode);
      updateSplinePositionOnResize(spl, maximizedNode);
    }
  }
  QMap<int, StageSchematicGroupNode *>::iterator it;
  for (it = m_GroupTable.begin(); it != m_GroupTable.end(); it++) {
    it.value()->resize(maximizedNode);
    QList<TStageObject *> groupedObjs = it.value()->getGroupedObjects();
    for (int i = 0; i < groupedObjs.size(); i++)
      updatePositionOnResize(groupedObjs[i], maximizedNode);
  }
  QMap<int, StageSchematicGroupEditor *>::iterator it2;
  for (it2 = m_groupEditorTable.begin(); it2 != m_groupEditorTable.end(); it2++)
    it2.value()->resizeNodes(maximizedNode);
  updateScene();
  resizingNodes = false;
}
setColumnHandle()
void StageSchematicScene::setColumnHandle (TColumnHandle * colHandle)
{
  m_colHandle = colHandle;
  m_selection->setColumnHandle(colHandle);
}
setFrameHandle()
void StageSchematicScene::setFrameHandle (TFrameHandle * frameHandle) inline
{
    m_frameHandle = frameHandle;
  }
setFxHandle()
void StageSchematicScene::setFxHandle (TFxHandle * fxHandle)
{
  m_selection->setFxHandle(fxHandle);
}
setObjectHandle()
void StageSchematicScene::setObjectHandle (TObjectHandle * objHandle)
{
  m_objHandle = objHandle;
  m_selection->setObjectHandle(objHandle);
}
setSceneHandle()
void StageSchematicScene::setSceneHandle (TSceneHandle * sceneHandle) inline
{
    m_sceneHandle = sceneHandle;
  }
setXsheetHandle()
void StageSchematicScene::setXsheetHandle (TXsheetHandle * xshHandle)
{
  m_xshHandle = xshHandle;
  m_selection->setXsheetHandle(xshHandle);
}
updateNestedGroupEditors()
void StageSchematicScene::updateNestedGroupEditors (StageSchematicNode * node, const QPointF & newPos)
{
  if (!node) return;
  QStack<int> groupIdStack = node->getStageObject()->getGroupIdStack();
  if (groupIdStack.isEmpty()) return;
  int i;
  QRectF rect;
  for (i = 0; i < groupIdStack.size(); i++) {
    if (m_groupEditorTable.contains(groupIdStack[i])) {
      QRectF app = m_groupEditorTable[groupIdStack[i]]->sceneBoundingRect();
      if (rect.isEmpty())
        rect = app;
      else
#if QT_VERSION >= 0x050000
        rect = rect.united(app);
#else
        rect = rect.unite(app);
#endif
    }
  }
  node->setPos(newPos);
  for (i = 0; i < groupIdStack.size(); i++) {
    if (!m_groupEditorTable.contains(groupIdStack[i])) continue;
#if QT_VERSION >= 0x050000
    rect =
        rect.united(m_groupEditorTable[groupIdStack[i]]->sceneBoundingRect());
#else
    rect = rect.unite(m_groupEditorTable[groupIdStack[i]]->sceneBoundingRect());
#endif
    QRectF app = m_groupEditorTable[groupIdStack[i]]->boundingSceneRect();
    if (m_groupEditorTable[groupIdStack[i]]->scenePos() != app.topLeft())
      m_groupEditorTable[groupIdStack[i]]->setPos(app.topLeft());
  }
  update(rect);
}
updateScene()
void StageSchematicScene::updateScene () override virtual
Clear all item an regenerate the Stage Schematic graph.
note: not every stage object is represented in the scene (e.g. empty columns are not)
Implements SchematicScene.
{
  if (updatingScene) return;
  updatingScene = true;
  clearAllItems();
  QPointF firstPos = sceneRect().center();
  m_nextNodePos    = TPointD(firstPos.x(), firstPos.y());
  TStageObjectTree *pegTree = m_xshHandle->getXsheet()->getStageObjectTree();
  m_nodeTable.clear();
  m_GroupTable.clear();
  m_groupEditorTable.clear();
  m_gridDimension = pegTree->getDagGridDimension();
  QMap<int, QList<TStageObject *>> groupedObj;
  QMap<int, QList<SchematicNode *>> editedGroup;
  // in order to draw the position-specified nodes first
  QList<int> modifiedNodeIds;
  for (int i = 0; i < pegTree->getStageObjectCount(); i++) {
    TStageObject *pegbar = pegTree->getStageObject(i);
    if (pegbar->getDagNodePos() == TConst::nowhere)
      modifiedNodeIds.push_back(i);
    else
      modifiedNodeIds.push_front(i);
  }
  for (int i = 0; i < modifiedNodeIds.size(); i++) {
    TStageObject *pegbar = pegTree->getStageObject(modifiedNodeIds.at(i));
    if (pegbar->isGrouped() && !pegbar->isGroupEditing()) {
      groupedObj[pegbar->getGroupId()].push_back(pegbar);
      continue;
    }
    StageSchematicNode *node = addStageSchematicNode(pegbar);
    if (node != 0) {
      m_nodeTable[pegbar->getId()] = node;
      if (pegbar->isGrouped())
        editedGroup[pegbar->getEditingGroupId()].append(node);
    }
  }
  // Motion Path
  m_splineTable.clear();
  for (int i = 0; i < pegTree->getSplineCount(); i++) {
    TStageObjectSpline *spline     = pegTree->getSpline(i);
    StageSchematicSplineNode *node = addSchematicSplineNode(spline);
    if (node != 0) {
      m_splineTable[spline] = node;
      connect(node, SIGNAL(currentObjectChanged(const TStageObjectId &, bool)),
              this, SLOT(onCurrentObjectChanged(const TStageObjectId &, bool)));
    }
  }
  QMap<int, QList<TStageObject *>>::iterator it;
  for (it = groupedObj.begin(); it != groupedObj.end(); it++) {
    StageSchematicGroupNode *node = addStageGroupNode(it.value());
    m_GroupTable[it.key()]        = node;
    int editingGroupId            = node->getStageObject()->getEditingGroupId();
    if (editingGroupId != -1) editedGroup[editingGroupId].append(node);
  }
  keepSubgroup(editedGroup);
  updateEditedGroups(editedGroup);
  // update stage links
  for (int i = 0; i < pegTree->getStageObjectCount(); i++)
  {
    TStageObject *pegbar    = pegTree->getStageObject(i);
    TStageObjectId parentId = pegbar->getParent();
    // update link; find StageSchematicNode representing pegbar
    QMap<TStageObjectId, StageSchematicNode *>::iterator it;
    if (!pegbar->isGrouped() || pegbar->isGroupEditing()) {
      it = m_nodeTable.find(pegbar->getId());
      if (it == m_nodeTable.end()) continue;
      StageSchematicNode *node = it.value();
      // get pegbar parent
      if (parentId != TStageObjectId::NoneId) {
        // find StageSchematicNode representing parentId
        it = m_nodeTable.find(parentId);
        if (it != m_nodeTable.end())  // at least we avoid crash
        {
          StageSchematicNode *parentNode = it.value();
          if (parentNode) {
            StageSchematicNodePort *port1 = parentNode->makeChildPort(
                QString::fromStdString(pegbar->getParentHandle()));
            StageSchematicNodePort *port2 = node->makeParentPort(
                QString::fromStdString(pegbar->getHandle()));
            port2->makeLink(port1);
          }
        }
        TStageObject *parent = pegTree->getStageObject(parentId, false);
        if (parent && parent->isGrouped()) {
          int groupId = parent->getGroupId();
          if (m_GroupTable.contains(groupId)) {
            StageSchematicGroupNode *groupeNode = m_GroupTable[groupId];
            StageSchematicNodePort *port1       = groupeNode->getChildPort(0);
            StageSchematicNodePort *port2       = node->makeParentPort(
                QString::fromStdString(pegbar->getHandle()));
            port2->makeLink(port1);
          }
        }
      }
      // link to motion path
      TStageObjectSpline *spline = pegbar->getSpline();
      if (spline) {
        QMap<TStageObjectSpline *, StageSchematicSplineNode *>::iterator
            splineIt;
        splineIt = m_splineTable.find(spline);
        if (splineIt != m_splineTable.end()) {
          SchematicPort *port1 = splineIt.value()->getPort(-1);
          SchematicPort *port2 = node->getPort(-1);
          port2->makeLink(port1);
        }
      }
    } else {
      int groupId                         = pegbar->getGroupId();
      StageSchematicGroupNode *groupeNode = m_GroupTable[groupId];
      TStageObject *parent = pegTree->getStageObject(parentId, false);
      if (parent && (!parent->isGrouped() || parent->isGroupEditing())) {
        it = m_nodeTable.find(parentId);
        if (it == m_nodeTable.end()) continue;
        StageSchematicNode *parentNode = it.value();
        if (parentNode) {
          StageSchematicNodePort *port1 = parentNode->makeChildPort(
              QString::fromStdString(pegbar->getParentHandle()));
          StageSchematicNodePort *port2 = groupeNode->getParentPort();
          port2->makeLink(port1);
        }
      }
      if (parent && parent->isGrouped()) {
        int parentGroupId = parent->getGroupId();
        if (m_GroupTable.contains(parentGroupId)) {
          StageSchematicGroupNode *groupeParentNode =
              m_GroupTable[parentGroupId];
          StageSchematicNodePort *port1 = groupeParentNode->getChildPort(0);
          StageSchematicNodePort *port2 = groupeNode->getParentPort();
          if (!port1->isLinkedTo(port2) && groupeParentNode != groupeNode)
            port2->makeLink(port1);
        }
      }
      TStageObjectSpline *spline = pegbar->getSpline();
      if (spline) {
        QMap<TStageObjectSpline *, StageSchematicSplineNode *>::iterator
            splineIt;
        splineIt = m_splineTable.find(spline);
        if (splineIt != m_splineTable.end()) {
          SchematicPort *port1 = splineIt.value()->getPort(-1);
          SchematicPort *port2 = groupeNode->getPort(-1);
          port2->makeLink(port1);
        }
      }
    }
  }
  m_nodesToPlace.clear();
  updatingScene = false;
}
References SchematicScene::clearAllItems(), TStageObject::getDagNodePos(), TStageObject::getHandle(), TStageObject::getId(), TStageObject::getParent(), TStageObject::getParentHandle(), SchematicNode::getPort(), TStageObject::getSpline(), TStageObjectTree::getSpline(), TStageObjectTree::getSplineCount(), TStageObjectTree::getStageObject(), TStageObjectTree::getStageObjectCount(), TXsheet::getStageObjectTree(), SchematicPort::isLinkedTo(), and SchematicPort::makeLink().
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/toonzqt/stageschematicscene.h
E:/opentoonz/toonz/sources/toonzqt/stageschematicscene.cpp