opentoonz: TCleanupStyle Class Reference
TCleanupStyle Class Reference
Public Member Functions
TCleanupStyle (const TPixel32 &color=TPixel32::Black)
TCleanupStyle (const TCleanupStyle &)
void setMainColor (const TPixel32 &color) override
Sets the main color, if it has one.
int getColorParamCount () const override
Returns the number of colors (if any) of the style.
TPixel32 getColorParamValue (int index) const override
Returns the value of the color of index index.
void setColorParamValue (int index, const TPixel32 &color) override
Sets the index-th color value.
int getParamCount () const override
QString getParamNames (int index) const override
Return the string that identifies the index-th parameter.
void getParamRange (int index, double &min, double &max) const override
Retrieves the specified double parameter range.
double getParamValue (TColorStyle::double_tag, int index) const override
Retrieves the specified double parameter value.
void setParamValue (int index, double value) override
extension value in text form.
double getBrightness () const
double getContrast () const
void setBrightness (double b)
void setContrast (double c)
void enableContrast (bool value)
bool isContrastEnabled () const
bool canUpdate () const
void setCanUpdate (bool state)
void makeIcon (const TDimension &size) override
Public Member Functions inherited from TSolidColorStyle
TSolidColorStyle (const TPixel32 &color=TPixel32::Black)
TSolidColorStyle (const TSolidColorStyle &)
TColorStyle * clone () const override
Polymorphic clone of the style.
QString getDescription () const override
Return a brief description of the style.
bool hasMainColor () const override
Returns whether the style has a reference main color.
TPixel32 getMainColor () const override
Returns the style's main color, or black if none.
void setMainColor (const TPixel32 &color) override
Sets the main color, if it has one.
void drawRegion (const TColorFunction *cf, const bool antiAliasing, TRegionOutline &outline) const override
void drawStroke (const TColorFunction *cf, TStrokeOutline *outline, const TStroke *s) const override
int getTagId () const override
Returns an unique number representing the style.
Public Member Functions inherited from TOutlineStyle
TOutlineStyle (const TOutlineStyle &)
RegionOutlineModifier * getRegionOutlineModifier () const
void setRegionOutlineModifier (RegionOutlineModifier *modifier)
bool isRegionStyle () const override
Returns whether the style applies on regions.
bool isStrokeStyle () const override
Returns whether the style applies on strokes.
virtual void computeOutline (const TStroke *stroke, TStrokeOutline &outline, TOutlineUtil::OutlineParameter param) const
TStrokeProp * makeStrokeProp (const TStroke *stroke) override
TRegionProp * makeRegionProp (const TRegion *region) override
used to draw the style on the specified stroke object.
virtual void drawRegion (const TColorFunction *cf, const bool antiAliasing, TRegionOutline &outline) const =0
virtual void drawStroke (const TColorFunction *cf, TStrokeOutline *outline, const TStroke *stroke) const =0
Public Member Functions inherited from TColorStyle
TColorStyle (const TColorStyle &other)
Copies another style except its icon.
virtual TColorStyle * clone () const =0
Polymorphic clone of the style.
virtual TColorStyle & copy (const TColorStyle &other)
bool operator== (const TColorStyle &cs) const
bool operator!= (const TColorStyle &cs)
virtual TStrokeProp * makeStrokeProp (const TStroke *stroke)=0
virtual TRegionProp * makeRegionProp (const TRegion *region)=0
used to draw the style on the specified stroke object.
virtual bool isRasterStyle () const
used to draw the style on the specified region object.
virtual TRasterStyleFx * getRasterStyleFx ()
virtual bool isRegionStyle () const =0
Returns whether the style applies on regions.
virtual bool isStrokeStyle () const =0
Returns whether the style applies on strokes.
void setName (std::wstring name)
Sets the style's user-defined name.
std::wstring getName () const
Returns the style's user-defined name.
void setGlobalName (std::wstring name)
Sets the global name of the style.
std::wstring getGlobalName () const
Returns the global name of the style.
void setOriginalName (std::wstring name)
If the style is originally copied from studio palette, set this.
std::wstring getOriginalName () const
Returns the original name of the style.
void setIsEditedFlag (bool edited)
bool getIsEditedFlag () const
style is edited from the original one.
void assignNames (const TColorStyle *src)
Copies the style names from src.
unsigned int getFlags () const
Sets color attributes.
void setFlags (unsigned int flags)
Returns color attributes.
void setPickedPosition (const TPoint &pos, const int index=0)
void setPickedPosition (const PickedPosition &pos)
PickedPosition getPickedPosition () const
virtual bool hasMainColor () const
Returns whether the style has a reference main color.
virtual TPixel32 getMainColor () const
Returns the style's main color, or black if none.
virtual void setMainColor (const TPixel32 &color)
Sets the main color, if it has one.
virtual int getColorParamCount () const
Returns the number of colors (if any) of the style.
virtual TPixel32 getColorParamValue (int index) const
Returns the value of the color of index index.
virtual void setColorParamValue (int index, const TPixel32 &color)
Sets the index-th color value.
virtual TPixel32 getAverageColor () const
Returns a color representing the average of all the style's colors.
virtual int getParamCount () const
virtual ParamType getParamType (int paramIdx) const
Returns the type of the specified parameter.
virtual bool hasParamDefault (int index) const
Value of parameter can be reset to default.
virtual void setParamDefault (int index)
Reset value of parameter to default.
virtual bool isParamDefault (int index) const
Check if current value of parameter equals to default.
virtual void setParamValue (int index, bool value)
Assigns a value to the specified bool parameter.
virtual bool getParamValue (bool_tag, int index) const
Retrieves the specified bool parameter value.
virtual void setParamValue (int index, int value)
Assigns a value to the specified int parameter.
virtual int getParamValue (int_tag, int index) const
Retrieves the specified int parameter value.
virtual void getParamRange (int index, int &min, int &max) const
Retrieves the specified int parameter range.
virtual void getParamRange (int pIndex, QStringList &stringItems) const
virtual void setParamValue (int index, double value)
extension value in text form.
virtual double getParamValue (double_tag, int index) const
Retrieves the specified double parameter value.
virtual void getParamRange (int index, double &min, double &max) const
Retrieves the specified double parameter range.
virtual void setParamValue (int index, const TFilePath &fp)
Assigns a value to the specified TFilePath parameter.
virtual TFilePath getParamValue (TFilePath_tag, int index) const
Retrieves the specified TFilePath parameter value.
void assignBlend (const TColorStyle &a, const TColorStyle &b, double t)
virtual QString getDescription () const =0
Return a brief description of the style.
virtual QString getParamNames (int index) const
Return the string that identifies the index-th parameter.
virtual int getTagId () const =0
Returns an unique number representing the style.
virtual void getObsoleteTagIds (std::vector< int > &) const
void save (TOutputStreamInterface &) const
void invalidateIcon ()
Sets a flag that defines the style's icon validity.
virtual const TRaster32P & getIcon (const TDimension &d)
Returns an image representing the style.
bool isEnabled () const
Returns whether the style can be used.
void enable (bool on)
Sets the style's enabled status.
int getVersionNumber () const
Returns the version number of the style.
Public Member Functions inherited from TSmartObject
TSmartObject (ClassCode classCode)
void addRef ()
void release ()
TINT32 getRefCount () const
Protected Member Functions
void loadData (TInputStreamInterface &) override
void saveData (TOutputStreamInterface &) const override
Protected Member Functions inherited from TSolidColorStyle
void makeIcon (const TDimension &d) override
void loadData (TInputStreamInterface &) override
void saveData (TOutputStreamInterface &) const override
Protected Member Functions inherited from TOutlineStyle
TOutlineStyle & operator= (const TOutlineStyle &)
Protected Member Functions inherited from TColorStyle
virtual void makeIcon (const TDimension &d)
virtual void loadData (TInputStreamInterface &)=0
virtual void saveData (TOutputStreamInterface &) const =0
virtual void loadData (int, TInputStreamInterface &)
void updateVersionNumber ()
TColorStyle & operator= (const TColorStyle &other)
Copies another style except its icon.
Additional Inherited Members
Public Types inherited from TColorStyle
enum ParamType {
BOOL , INT , ENUM , DOUBLE ,
FILEPATH
}
Public Types inherited from TSmartObject
typedef short ClassCode
Static Public Member Functions inherited from TColorStyle
static TColorStyle * load (TInputStreamInterface &)
static TColorStyle * create (int tagId)
Creates a new style with identifier equal to tagId.
static void declare (TColorStyle *style)
Puts the style in the table of actual styles.
static void getAllTags (std::vector< int > &tags)
Static Public Member Functions inherited from TSmartObject
static TINT32 getInstanceCount (ClassCode code)
Static Public Attributes inherited from TColorStyle
static int m_currentFrame = 0
Protected Attributes inherited from TOutlineStyle
RegionOutlineModifier * m_regionOutlineModifier
Protected Attributes inherited from TColorStyle
TRaster32P m_icon
Icon shown on TPalette viewers.
bool m_validIcon
Icon's validity status.
Detailed Description
Constructor & Destructor Documentation
TCleanupStyle() [1/2]
TCleanupStyle::TCleanupStyle (const TPixel32 & color = TPixel32::Black)
    : TSolidColorStyle(color)
    , m_outColor(color)
    , m_brightness(0)
    , m_contrast(50)
    , m_canUpdate(true) {}
TCleanupStyle() [2/2]
TCleanupStyle::TCleanupStyle (const TCleanupStyle & src)
    : TSolidColorStyle(src)
    , m_outColor(src.m_outColor)
    , m_brightness(src.m_brightness)
    , m_contrast(src.m_contrast)
    , m_contrastEnable(true)
    , m_canUpdate(src.m_canUpdate) {
  setName(src.getName());
}
~TCleanupStyle()
TCleanupStyle::~TCleanupStyle ()
{}
Member Function Documentation
canUpdate()
bool TCleanupStyle::canUpdate () const inline
{ return m_canUpdate; }
enableContrast()
void TCleanupStyle::enableContrast (bool value)
{ m_contrastEnable = value; }
getBrightness()
double TCleanupStyle::getBrightness () const inline
{ return m_brightness; }
getColorParamCount()
int TCleanupStyle::getColorParamCount () const override virtual
Returns the number of colors (if any) of the style.
\detail For example a bubble styles has two colors. By default it returns 1 if the style has only a main color else returns 0 if the style has no color.
Reimplemented from TColorStyle.
{ return 2; }
getColorParamValue()
TPixel32 TCleanupStyle::getColorParamValue (int index) const override virtual
Returns the value of the color of index index.
\detail Returns the main color by default.
Reimplemented from TColorStyle.
{
  return (index == 0) ? getMainColor() : m_outColor;
}
References TSolidColorStyle::getMainColor().
getContrast()
double TCleanupStyle::getContrast () const inline
{ return m_contrastEnable ? m_contrast : 100; }
getParamCount()
int TCleanupStyle::getParamCount () const inline override virtual
\detail For example: a the general cleanup style has two parameters, brightness and contrast and a black cleanup style has in addition a black and white threshold, therefore 4 parameters. Returns the number of parameters necessary to describe the style.
Reimplemented from TColorStyle.
Reimplemented in TColorCleanupStyle, and TBlackCleanupStyle.
{ return 2; }
getParamNames()
QString TCleanupStyle::getParamNames (int index) const override virtual
Return the string that identifies the index-th parameter.
Reimplemented from TColorStyle.
Reimplemented in TColorCleanupStyle, and TBlackCleanupStyle.
{
  switch (index) {
  case 0:
    return QObject::tr("Brightness");
  case 1:
    return QObject::tr("Contrast");
  default:
    return QString("");
  }
}
Referenced by TColorCleanupStyle::getParamNames(), and TBlackCleanupStyle::getParamNames().
getParamRange()
void TCleanupStyle::getParamRange (int index, double & min, double & max) const override virtual
Retrieves the specified double parameter range.
Reimplemented from TColorStyle.
Reimplemented in TColorCleanupStyle, and TBlackCleanupStyle.
{
  if (index == 0) {
    min = -100;
    max = 100;
  } else {
    min = 0;
    max = 100;
  }
}
Referenced by TColorCleanupStyle::getParamRange(), and TBlackCleanupStyle::getParamRange().
getParamValue()
double TCleanupStyle::getParamValue (TColorStyle::double_tag , int index) const override virtual
Retrieves the specified double parameter value.
Reimplemented from TColorStyle.
Reimplemented in TColorCleanupStyle, and TBlackCleanupStyle.
{
  switch (index) {
  case 0:
    return getBrightness();
  case 1:
    return getContrast();
  default:
    return 0.0;
  }
}
Referenced by TColorCleanupStyle::getParamValue(), and TBlackCleanupStyle::getParamValue().
isContrastEnabled()
bool TCleanupStyle::isContrastEnabled () const
{ return m_contrastEnable; }
loadData()
void TCleanupStyle::loadData (TInputStreamInterface & is) override protected virtual
Implements TColorStyle.
{
  TSolidColorStyle::loadData(is);
  VersionNumber version(is.versionNumber());
  if (version.first == 1 && version.second == 18) {
    // Toonz 6.3 ML had removed the output color option
    TPixel32 dummy;
    is >> dummy >> m_brightness >> m_contrast;
    m_outColor = getMainColor();
  } else
    is >> m_outColor >> m_brightness >> m_contrast;
}
makeIcon()
void TCleanupStyle::makeIcon (const TDimension & size) override virtual
Reimplemented from TColorStyle.
{
  // Build an icon with mainColor on the top half, and
  // getColorParamValue(1) on the bottom.
  if (!m_icon || m_icon->getSize() != size) {
    TRaster32P ras(size);
    m_icon = ras;
  }
  TPixel32 topCol(getMainColor()), botCol(getColorParamValue(1));
  int ly_2 = size.ly / 2;
  TRaster32P botRas(m_icon->extract(0, 0, size.lx, ly_2));
  TRaster32P topRas(m_icon->extract(0, ly_2 + 1, size.lx, size.ly));
  makeIcon(botRas, botCol);
  makeIcon(topRas, topCol);
}
saveData()
void TCleanupStyle::saveData (TOutputStreamInterface & os) const override protected virtual
Implements TColorStyle.
{
  TSolidColorStyle::saveData(os);
  os << m_outColor << m_brightness << m_contrast;
}
setBrightness()
void TCleanupStyle::setBrightness (double b)
{ m_brightness = b; }
setCanUpdate()
void TCleanupStyle::setCanUpdate (bool state)
{ m_canUpdate = state; }
setColorParamValue()
void TCleanupStyle::setColorParamValue (int index, const TPixel32 & color) override virtual
Sets the index-th color value.
Reimplemented from TColorStyle.
{
  if (index == 0)
    setMainColor(color);
  else
    m_outColor = color;
}
References setMainColor().
setContrast()
void TCleanupStyle::setContrast (double c)
{ m_contrast = c; }
setMainColor()
void TCleanupStyle::setMainColor (const TPixel32 & color) override virtual
Sets the main color, if it has one.
Reimplemented from TColorStyle.
{
  if (getMainColor() == m_outColor) m_outColor = color;
  TSolidColorStyle::setMainColor(color);
}
References TSolidColorStyle::getMainColor(), and TSolidColorStyle::setMainColor().
Referenced by setColorParamValue().
setParamValue()
void TCleanupStyle::setParamValue (int index, double value) override virtual
extension value in text form.
Assigns a value to the specified double parameter.
Reimplemented from TColorStyle.
Reimplemented in TColorCleanupStyle, and TBlackCleanupStyle.
{
  switch (index) {
  case 0:
    setBrightness(value);
    break;
  case 1:
    setContrast(value);
    break;
  }
}
Referenced by TColorCleanupStyle::setParamValue(), and TBlackCleanupStyle::setParamValue().
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/toonz/cleanupcolorstyles.h
E:/opentoonz/toonz/sources/toonzlib/cleanupcolorstyles.cpp