opentoonz: TXshCellColumn Class Reference
TXshCellColumn Class Reference abstract
#include <txshcolumn.h>
Public Member Functions
TXshCellColumn ()
~TXshCellColumn ()
TXshCellColumn * getCellColumn () override
virtual bool canSetCell (const TXshCell &cell) const =0
int getRange (int &r0, int &r1) const override
virtual int getRowCount () const
bool isEmpty () const override
bool isCellEmpty (int row) const override
virtual const TXshCell & getCell (int row) const
virtual bool setCell (int row, const TXshCell &cell)
virtual void getCells (int row, int rowCount, TXshCell cells[])
virtual bool setCells (int row, int rowCount, const TXshCell cells[])
virtual void insertEmptyCells (int row, int rowCount=1)
virtual void removeCells (int row, int rowCount=1)
virtual void clearCells (int row, int rowCount=1)
int getMaxFrame () const override
virtual int getFirstRow () const
virtual void checkColumn () const
bool getLevelRange (int row, int &r0, int &r1) const override
void saveCellMarks (TOStream &os)
bool loadCellMarks (std::string tagName, TIStream &is)
void setCellMark (int frame, int id)
int getCellMark (int frame) const
QMap< int, int > getCellMarks () const
void clearCellMarks ()
Public Member Functions inherited from TXshColumn
TXshColumn ()
virtual ColumnType getColumnType () const =0
virtual TXshLevelColumn * getLevelColumn ()
virtual TXshSoundColumn * getSoundColumn ()
virtual TXshSoundTextColumn * getSoundTextColumn ()
virtual TXshCellColumn * getCellColumn ()
virtual TXshPaletteColumn * getPaletteColumn ()
virtual TXshZeraryFxColumn * getZeraryFxColumn ()
virtual TXshMeshColumn * getMeshColumn ()
virtual int getMaxFrame () const =0
virtual TXshColumn * clone () const =0
bool isCamstandVisible () const
void setCamstandVisible (bool on)
UCHAR getOpacity () const
void setOpacity (UCHAR val)
bool isPreviewVisible () const
void setPreviewVisible (bool on)
bool isLocked () const
void lock (bool on)
bool isMask () const
void setIsMask (bool on)
virtual bool isEmpty () const
virtual TRaster32P getIcon ()
virtual bool isCellEmpty (int row) const =0
virtual bool getLevelRange (int row, int &r0, int &r1) const =0
virtual int getRange (int &r0, int &r1) const
virtual void setXsheet (TXsheet *xsheet)
TXsheet * getXsheet () const
virtual TFx * getFx () const
virtual bool isRendered () const
virtual bool isControl () const
int getColorTag () const
void setColorTag (int colorTag)
FilterColor getFilterColorId () const
void setFilterColorId (FilterColor id)
TPixel32 getFilterColor ()
void resetColumnProperties ()
Public Member Functions inherited from TColumnHeader
int getIndex () const
int getPos () const
int getX0 () const
int getX1 () const
void getCoords (int &x0, int &x1) const
int getWidth () const
bool inColumnsSet () const
Public Member Functions inherited from TSmartObject
TSmartObject (ClassCode classCode)
void addRef ()
void release ()
TINT32 getRefCount () const
Public Member Functions inherited from TPersist
virtual void loadData (TIStream &is)=0
virtual void saveData (TOStream &os)=0
std::string getStreamTag () const
virtual const TPersistDeclaration * getDeclaration () const =0
Protected Attributes
std::vector< TXshCell > m_cells
int m_first
QMap< int, int > m_cellMarkIds
Protected Attributes inherited from TXshColumn
TRaster32P m_icon
Additional Inherited Members
Public Types inherited from TXshColumn
enum FilterColor {
FilterNone = 0 , FilterRed , FilterGreen , FilterBlue ,
FilterDarkYellow , FilterDarkCyan , FilterDarkMagenta , FilterAmount
}
enum ColumnType {
eLevelType = 0 , eSoundType , eSoundTextType , eZeraryFxType ,
ePaletteType , eMeshType
}
Public Types inherited from TSmartObject
typedef short ClassCode
Public Types inherited from TPersist
typedef TPersist * CreateProc()
Static Public Member Functions inherited from TXshColumn
static ColumnType toColumnType (int levelType)
Returns the column type used to store levels of the specified type.
static TXshColumn * createEmpty (int colType)
Creates an empty TXshColumn of the specified column type.
static QPair< QString, TPixel32 > getFilterInfo (FilterColor key)
static void initColorFilters ()
Static Public Member Functions inherited from TSmartObject
static TINT32 getInstanceCount (ClassCode code)
Static Public Member Functions inherited from TPersist
static void declare (CreateProc *)
static TPersist * create (const std::string &name)
Protected Types inherited from TXshColumn
enum {
eCamstandVisible = 0x1 , ePreviewVisible = 0x2 , eLocked = 0x8 , eMasked = 0x10 ,
eCamstandTransparent43 = 0x20
}
Protected Member Functions inherited from TXshColumn
void setStatusWord (int status)
int getStatusWord () const
Detailed Description
The TXshCellColumn class is the base class of column cell managers in xsheet.
Inherits TXshColumn.
This is an abstract base class inherited by the concrete classes TXshLevelColumn and TXshZeraryFxColumn.
The class defines column by cells getCellColumn(). TXshCellColumn is an object composed of a TXshCell vector and of an integer to memorize first not empty cell.
Class allows to manage cells in a column. It's possible to know if cell is empty isCellEmpty(), if column is empty isEmpty(), to know column range getRange(), row count getRowCount(), last and first not empty frame getMaxFrame(), getFirstRow(). Specally class allows to change cells, getCells(), setCells(), or individually cell, getCell(), setCell(); allows to insert insertEmptyCells(), remove removeCells(), clear clearCells() and move moveCells() cells in a column of xsheet.
Constructor & Destructor Documentation
TXshCellColumn()
TXshCellColumn::TXshCellColumn ()
Constructs a TXshCellColumn with default value.
: m_first(0) {}
~TXshCellColumn()
TXshCellColumn::~TXshCellColumn ()
Destroys the TXshCellColumn object.
{ m_cells.clear(); }
Member Function Documentation
canSetCell()
virtual bool TXshCellColumn::canSetCell (const TXshCell & cell) const pure virtual
Implemented in TXshLevelColumn, and TXshZeraryFxColumn.
checkColumn()
void TXshCellColumn::checkColumn () const virtual
Reimplemented in TXshSoundColumn.
{
  assert(m_first >= 0);
  int r0, r1;
  int range = getRange(r0, r1);
  assert(range >= 0);
  assert(range == (int)m_cells.size());
  assert(getRowCount() >= 0);
  TXshCell firstCell = getCell(m_first);
  TXshCell lastCell  = getCell(r1);
  if (range == 0)
    assert(firstCell.isEmpty() && lastCell.isEmpty());
  else {
    assert(firstCell.isEmpty() == 0);
    assert(lastCell.isEmpty() == 0);
    int maxFrame = getMaxFrame();
    assert(maxFrame == r1);
    assert(getCell(maxFrame).isEmpty() == 0);
  }
}
clearCellMarks()
void TXshCellColumn::clearCellMarks ()
{ m_cellMarkIds.clear(); }
clearCells()
void TXshCellColumn::clearCells (int row, int rowCount = 1) virtual
Clear rowCount cells from line row, without shift.
Reimplemented in TXshSoundColumn.
{
  if (rowCount <= 0) return;
  if (m_cells.empty()) return;  // se la colonna e' vuota
  // le celle da cancellare sono [ra, rb]
  int ra = row;
  int rb = row + rowCount - 1;
  assert(ra <= rb);
  int cellCount = m_cells.size();
  // le celle non vuote sono [c_ra, c_rb]
  int c_ra = m_first;
  int c_rb = m_first + cellCount - 1;
  assert(c_ra <= c_rb);
  // se e' sotto o sopra le celle occupate non devo far nulla
  if (rb < c_ra || ra > c_rb) return;
  // restringo l'area da cancellare in modo che comprenda solo celle non vuote
  if (ra < c_ra) ra = c_ra;
  if (rb > c_rb) rb = c_rb;
  // devo "sbiancare" n celle
  int n = rb - ra + 1;
  assert(n >= 0);
  if (n == cellCount)  // ho cancellato tutto
  {
    m_cells.clear();
    m_first = 0;
  } else {
    assert(ra - c_ra < (int)m_cells.size());
    assert(ra - c_ra + n <= (int)m_cells.size());
    // std::fill_n(&m_cells[ra-c_ra],n, TXshCell());
    int i;
    for (i = 0; i < n; i++) m_cells[ra - c_ra + i] = TXshCell();
    // verifico la presenza di celle bianche alla fine
    while (!m_cells.empty() && m_cells.back().isEmpty()) {
      m_cells.pop_back();
    }
    if (m_cells.empty()) {
      m_first = 0;
    } else {
      // verifico la presenza di celle bianche all'inizio
      while (!m_cells.empty() && m_cells.front().isEmpty()) {
        m_cells.erase(m_cells.begin());
        m_first++;
      }
    }
  }
  // updateIcon();
}
Referenced by TXsheet::clearCells().
getCell()
const TXshCell & TXshCellColumn::getCell (int row) const virtual
Return cell in row.
See also
getCells and setCell()
Reimplemented in TXshSoundColumn.
{
  static TXshCell emptyCell;
  if (row < 0 || row < m_first || row >= m_first + (int)m_cells.size())
    return emptyCell;
  return m_cells[row - m_first];
}
Referenced by TXsheet::checkCircularReferences(), TLevelColumnFx::doDryCompute(), getLevelRange(), TXsheet::getUsedLevels(), isCellEmpty(), FxBuilder::makePF(), TXshMeshColumn::saveData(), TXshPaletteColumn::saveData(), TXshLevelColumn::saveData(), TXshSoundTextColumn::saveData(), TXshZeraryFxColumn::saveData(), and LevelSettingsPopup::updateLevelSettings().
getCellColumn()
TXshCellColumn * TXshCellColumn::getCellColumn () inline override virtual
Return TXshCellColumn.
Reimplemented from TXshColumn.
{ return this; }
getCellMark()
int TXshCellColumn::getCellMark (int frame) const
{
  return m_cellMarkIds.value(frame, -1);
}
getCellMarks()
QMap< int, int > TXshCellColumn::getCellMarks () const
{ return m_cellMarkIds; }
getCells()
void TXshCellColumn::getCells (int row, int rowCount, TXshCell cells[]) virtual
Set cells[] from row to row + rowCount to column cells.
See also
getCell and setCells()
Reimplemented in TXshSoundColumn.
{
  const TXshCell emptyCell;
  int first = m_first;
  int i;
  int cellCount = m_cells.size();
  if (row < 0 || row + rowCount - 1 < first || row >= first + cellCount) {
    for (i = 0; i < rowCount; i++) cells[i] = emptyCell;
    return;
  }
  int dst, src, n, delta;
  n     = rowCount;
  delta = m_first - row;
  if (delta < 0) {  // le celle cominciano PRIMA della zona da leggere
    dst = 0;
    src = -delta;
  } else {  // le celle cominciano DOPO della zona da leggere
    dst = delta;
    src = 0;
    n -= delta;
  }
  if (n + src > cellCount) n = cellCount - src;
  TXshCell *dstCell    = cells;
  TXshCell *endDstCell = dstCell + dst;
  while (dstCell < endDstCell) *dstCell++ = emptyCell;
  endDstCell += n;
  while (dstCell < endDstCell) *dstCell++ = m_cells[src++];
  endDstCell = cells + rowCount;
  while (dstCell < endDstCell) *dstCell++ = emptyCell;
}
getFirstRow()
int TXshCellColumn::getFirstRow () const virtual
Return first not empty row.
Reimplemented in TXshSoundColumn.
{ return m_first; }
getLevelRange()
bool TXshCellColumn::getLevelRange (int row, int & r0, int & r1) const override virtual
Return true if cell in row is not empty. Set r0 and r1 to first and last row with not empty cell of same level.
Implements TXshColumn.
Reimplemented in TXshSoundColumn.
{
  r0 = r1       = row;
  TXshCell cell = getCell(row);
  if (cell.isEmpty()) return false;
  while (r0 > 0 &&
         getCell(r0 - 1).m_level.getPointer() == cell.m_level.getPointer())
    r0--;
  while (getCell(r1 + 1).m_level.getPointer() == cell.m_level.getPointer())
    r1++;
  return true;
}
References getCell(), and TXshCell::isEmpty().
getMaxFrame()
int TXshCellColumn::getMaxFrame () const override virtual
Return last row with not empty cell.
Implements TXshColumn.
Reimplemented in TXshSoundColumn.
{
  int r0, r1;
  getRange(r0, r1);
  return r1;
}
References getRange().
Referenced by TXsheet::clearCells(), and TXsheet::removeCells().
getRange()
int TXshCellColumn::getRange (int & r0, int & r1) const override virtual
Return not empty cell range. Set r0 and r1 to first and last row with not empty cell.
See also
isEmpty() and getRowCount()
Reimplemented from TXshColumn.
Reimplemented in TXshSoundColumn.
{
  int cellCount = m_cells.size();
  r0            = m_first;
  r1            = r0 + cellCount - 1;
  int i;
  for (i = 0; i < cellCount && m_cells[i].isEmpty(); i++) {
  }
  if (i >= cellCount) {
    r0 = 0;
    r1 = -1;
    return 0;
  }
  r0 = m_first + i;
  for (i = cellCount - 1; i >= 0 && m_cells[i].isEmpty(); i--) {
  }
  r1 = m_first + i;
  return r1 - r0 + 1;
}
Referenced by TXsheet::checkCircularReferences(), TXsheet::getCellRange(), getMaxFrame(), TXsheet::getUsedLevels(), TXshZeraryFxColumn::loadData(), FxBuilder::makePF(), TXshMeshColumn::saveData(), TXshPaletteColumn::saveData(), TXshLevelColumn::saveData(), TXshSoundTextColumn::saveData(), TXshZeraryFxColumn::saveData(), and LevelSettingsPopup::updateLevelSettings().
getRowCount()
int TXshCellColumn::getRowCount () const virtual
Return row count.
See also
isEmpty() and getRange()
Reimplemented in TXshSoundColumn.
{
  int i = m_cells.size();
  for (; i > 0 && m_cells[i - 1].isEmpty(); i--) {
  }
  if (i == 0)
    return 0;
  else
    return m_first + i;
}
Referenced by FxsData::setFxs().
insertEmptyCells()
void TXshCellColumn::insertEmptyCells (int row, int rowCount = 1) virtual
Insert rowCount empty cells from line row.
Reimplemented in TXshSoundColumn.
{
  if (m_cells.empty())
    return;  // se la colonna e' vuota non devo inserire
             // celle
  if (row >= m_first + (int)m_cells.size()) return;  // dopo:non inserisco nulla
  if (row <= m_first)                                // prima
  {
    m_first += rowCount;
  } else  // in mezzo
  {
    int delta                          = row - m_first;
    std::vector<TXshCell>::iterator it = m_cells.begin();
    std::advance(it, delta);
    m_cells.insert(it, rowCount, TXshCell());
  }
}
isCellEmpty()
bool TXshCellColumn::isCellEmpty (int row) const override virtual
Return true if cell in row is empty.
See also
isEmpty()
Implements TXshColumn.
Reimplemented in TXshSoundColumn.
{
  return getCell(row).isEmpty();
}
References getCell(), and TXshCell::isEmpty().
isEmpty()
bool TXshCellColumn::isEmpty () const inline override virtual
Return true if row count is null.
See also
isCellEmpty(), getRowCount(), getRange()
Reimplemented from TXshColumn.
{ return getRowCount() == 0; }
Referenced by FxBuilder::makePF(), TXshZeraryFxColumn::saveData(), TXshZeraryFxColumn::setCell(), and TXshZeraryFxColumn::setCells().
loadCellMarks()
bool TXshCellColumn::loadCellMarks (std::string tagName, TIStream & is)
{
  if (tagName != "cellMarks") return false;
  m_cellMarkIds.clear();
  while (is.openChild(tagName)) {
    if (tagName == "cellMark") {
      int id;
      QString frameStr;
      if (is.getTagParam("id", id)) {
        is >> frameStr;
#if (QT_VERSION >= QT_VERSION_CHECK(5, 14, 0))
        QStringList frameStrList = frameStr.split(" ", Qt::SkipEmptyParts);
#else
        QStringList frameStrList = frameStr.split(" ", QString::SkipEmptyParts);
#endif
        for (auto fStr : frameStrList) m_cellMarkIds.insert(fStr.toInt(), id);
      }
    }
    is.closeChild();
  }
  return true;
}
removeCells()
void TXshCellColumn::removeCells (int row, int rowCount = 1) virtual
Remove rowCount cells from line row, with shift.
Reimplemented in TXshSoundColumn.
{
  if (rowCount <= 0) return;
  if (m_cells.empty()) return;  // se la colonna e' vuota
  int cellCount = m_cells.size();
  if (row >= m_first + cellCount) return;  // sono "sotto" l'ultima cella
  if (row < m_first) {
    if (row + rowCount <= m_first)  //"sono sopra la prima cella"
    {                               // aggiorno solo m_first
      m_first -= rowCount;
      return;
    }
    rowCount += row - m_first;
    m_first = row;
  }
  assert(row >= m_first);
  // le celle sotto m_first+cellCount sono gia' vuote
  if (rowCount > m_first + cellCount - row)
    rowCount = m_first + cellCount - row;
  if (rowCount <= 0) return;
  if (row == m_first) {
    // cancello all'inizio
    assert(rowCount <= cellCount);
    std::vector<TXshCell>::iterator it  = m_cells.begin();
    std::vector<TXshCell>::iterator it2 = m_cells.begin();
    std::advance(it2, rowCount);
    m_cells.erase(it, it2);
    // verifico la presenza di celle bianche all'inizio
    while (!m_cells.empty() && m_cells.front().isEmpty()) {
      m_cells.erase(m_cells.begin());
      m_first++;
    }
  } else {
    // cancello dopo l'inizio
    int d                               = row - m_first;
    std::vector<TXshCell>::iterator it  = m_cells.begin();
    std::vector<TXshCell>::iterator it2 = m_cells.begin();
    std::advance(it, d);
    std::advance(it2, d + rowCount);
    m_cells.erase(it, it2);
    if (row + rowCount == m_first + cellCount) {
      // verifico la presenza di celle bianche alla fine
      while (!m_cells.empty() && m_cells.back().isEmpty()) {
        m_cells.pop_back();
      }
    }
  }
  if (m_cells.empty()) {
    m_first = 0;
  }
  // updateIcon();
}
Referenced by TXshZeraryFxColumn::loadData(), and TXsheet::removeCells().
saveCellMarks()
void TXshCellColumn::saveCellMarks (TOStream & os)
{
  if (m_cellMarkIds.isEmpty()) return;
  // gather frame numbers with the same id
  QMap<int, QString> idStrMap;
  QMap<int, int>::const_iterator i = m_cellMarkIds.constBegin();
  while (i != m_cellMarkIds.constEnd()) {
    if (!idStrMap.contains(i.value()))
      idStrMap.insert(i.value(), QString::number(i.key()));
    else
      idStrMap[i.value()] += " " + QString::number(i.key());
    ++i;
  }
  os.openChild("cellMarks");
  QMap<int, QString>::const_iterator j = idStrMap.constBegin();
  while (j != idStrMap.constEnd()) {
    std::map<std::string, std::string> attr;
    attr["id"] = std::to_string(j.key());
    os.openChild("cellMark", attr);
    os << j.value();
    os.closeChild();
    ++j;
  }
  os.closeChild();
}
setCell()
bool TXshCellColumn::setCell (int row, const TXshCell & cell) virtual
Set cell in row to TXshCell cell.
See also
setCells() and getCell(); return false if cannot set cells.
Reimplemented in TXshSoundColumn, and TXshZeraryFxColumn.
{
  if (!canSetCell(cell)) return false;
  assert(row >= 0);
#ifndef NDEBUG
  checkColumn();
#endif
  if (m_cells.empty())  // se la colonna e' vuota
  {
    if (!cell.isEmpty()) {
      m_cells.push_back(cell);
      m_first = row;
      // updateIcon();
    }
    return true;
  }
  int oldCellCount = m_cells.size();
  assert(oldCellCount > 0);
  int lastRow = m_first + oldCellCount - 1;
  if (row < m_first)  // prima
  {
    if (cell.isEmpty()) return false;  // non faccio nulla
    int delta = m_first - row;
    assert(delta > 0);
    m_cells.insert(m_cells.begin(), delta - 1, TXshCell());  // celle vuote
    m_cells.insert(m_cells.begin(),
                   cell);  // devo settare la prima comp. del vettore
    m_first = row;         // row 'e la nuova firstrow
// updateIcon();
#ifndef NDEBUG
    checkColumn();
#endif
    return true;
  } else if (row > lastRow)  // dopo
  {
    if (cell.isEmpty()) return false;  // non faccio nulla
    int count = row - lastRow - 1;
    // se necessario, inserisco celle vuote
    for (int i = 0; i < count; ++i) m_cells.push_back(TXshCell());
    m_cells.push_back(cell);
#ifndef NDEBUG
    checkColumn();
#endif
    return true;
  }
  //"[r0,r1]"
  int index = row - m_first;
  assert(0 <= index && index < (int)m_cells.size());
  m_cells[index] = cell;
  // if(index == 0) updateIcon();
  if (cell.isEmpty()) {
    if (row == lastRow) {
      // verifico la presenza di celle bianche alla fine
      while (!m_cells.empty() && m_cells.back().isEmpty()) m_cells.pop_back();
    } else if (row == m_first) {
      // verifico la presenza di celle bianche all'inizio
      while (!m_cells.empty() && m_cells.front().isEmpty()) {
        m_cells.erase(m_cells.begin());
        m_first++;
      }
    }
    if (m_cells.empty()) m_first = 0;
  }
  checkColumn();
  return true;
}
References TXshCell::isEmpty().
Referenced by TXshLevelColumn::loadData(), TXshMeshColumn::loadData(), TXshPaletteColumn::loadData(), TXshSoundTextColumn::loadData(), and TXshZeraryFxColumn::setCell().
setCellMark()
void TXshCellColumn::setCellMark (int frame, int id)
{
  if (id < 0)
    m_cellMarkIds.remove(frame);
  else
    m_cellMarkIds.insert(frame, id);
}
setCells()
bool TXshCellColumn::setCells (int row, int rowCount, const TXshCell cells[]) virtual
Set column cells from row to row + rowCount to cells[].
See also
setCell() and getCell(); return false if cannot set cells[].
Reimplemented in TXshSoundColumn, and TXshZeraryFxColumn.
{
  assert(row >= 0);
  int i;
  for (i = 0; i < rowCount; i++)
    if (!canSetCell(cells[i])) return false;
  int oldCellCount = m_cells.size();
  // le celle da settare sono [ra, rb]
  int ra = row;
  int rb = row + rowCount - 1;
  assert(ra <= rb);
  // le celle non vuote sono [c_ra, c_rb]
  int c_rb = m_first + oldCellCount - 1;
  if (row > c_rb)  // sono oltre l'ultima riga
  {
    if (oldCellCount == 0) m_first = row;  // row 'e la nuova firstrow
    int newCellCount = row - m_first + rowCount;
    m_cells.resize(newCellCount);
  } else if (row < m_first) {
    int delta = m_first - row;
    m_cells.insert(m_cells.begin(), delta, TXshCell());
    m_first = row;  // row e' la nuova firstrow
  }
  if (rb > c_rb) {
    for (int i = 0; i < rb - c_rb; ++i) m_cells.push_back(TXshCell());
  }
  int index = row - m_first;
  assert(0 <= index && index < (int)m_cells.size());
  for (int i = 0; i < rowCount; i++) m_cells[index + i] = cells[i];
  // verifico la presenza di celle bianche alla fine
  while (!m_cells.empty() && m_cells.back().isEmpty()) {
    m_cells.pop_back();
  }
  // verifico la presenza di celle bianche all'inizio
  while (!m_cells.empty() && m_cells.front().isEmpty()) {
    m_cells.erase(m_cells.begin());
    m_first++;
  }
  if (m_cells.empty()) {
    m_first = 0;
  }
  // updateIcon();
  return true;
}
Referenced by TXshZeraryFxColumn::setCells().
Member Data Documentation
m_cellMarkIds
QMap<int, int> TXshCellColumn::m_cellMarkIds protected
m_cells
std::vector<TXshCell> TXshCellColumn::m_cells protected
m_first
int TXshCellColumn::m_first protected
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/toonz/txshcolumn.h
E:/opentoonz/toonz/sources/toonzlib/txshcolumn.cpp