opentoonz: TRaster Class Reference
TRaster Class Reference abstract
#include <traster.h>
Public Member Functions
int getLx () const
int getLy () const
TDimension getSize () const
int getWrap () const
Returns the length of a row in pixel.
TPointD getCenterD () const
TPoint getCenter () const
TRect getBounds () const
int getPixelSize () const
int getRowSize () const
void lock ()
void unlock ()
void beginRemapping ()
void endRemapping ()
const UCHAR * getRawData () const
Returns a pointer to the image buffer.
UCHAR * getRawData ()
const UCHAR * getRawData (int x, int y) const
Returns a pointer to the image buffer positioned in the (x,y) coords.
UCHAR * getRawData (int x, int y)
bool isEmpty () const
TRasterP getParent ()
virtual TRasterP clone () const =0
virtual TRasterP extract (TRect &rect)=0
virtual TRasterP create () const =0
virtual TRasterP create (int lx, int ly) const =0
virtual TRasterP extract (int x0, int y0, int x1, int y1)
void copy (const TRasterP &src, const TPoint &offset=TPoint())
void xMirror ()
void yMirror ()
void rotate180 ()
void rotate90 ()
void clear ()
void clearOutside (const TRect &rect)
Public Member Functions inherited from TSmartObject
TSmartObject (ClassCode classCode)
void addRef ()
void release ()
TINT32 getRefCount () const
Protected Member Functions
TRaster (int lx, int ly, int pixelSize)
TRaster (int lx, int ly, int pixelSize, int wrap, UCHAR *buffer, TRaster *parent, bool bufferOwner=false)
void fillRawData (const UCHAR *pixel)
void fillRawDataOutside (const TRect &rect, const UCHAR *pixel)
Protected Attributes
int m_pixelSize
int m_lx
int m_ly
int m_wrap
int m_lockCount
TRaster * m_parent
UCHAR * m_buffer
bool m_bufferOwner
Friends
class TBigMemoryManager
Additional Inherited Members
Public Types inherited from TSmartObject
typedef short ClassCode
Static Public Member Functions inherited from TSmartObject
static TINT32 getInstanceCount (ClassCode code)
Detailed Description
This class stores bitmap images.
Constructor & Destructor Documentation
TRaster() [1/2]
TRaster::TRaster (int lx, int ly, int pixelSize) protected
    : TSmartObject(m_classCode)
    , m_pixelSize(pixelSize)
    , m_lx(lx)
    , m_ly(ly)
    , m_wrap(lx)
    , m_parent(0)
    , m_bufferOwner(true)
    , m_buffer(0)
    , m_lockCount(0)
#ifdef _DEBUG
    , m_cashed(false)
#endif
{
  // try
  {
    assert(pixelSize > 0);
    assert(lx > 0 && ly > 0);
    TBigMemoryManager::instance()->putRaster(this);
    // m_buffer = new UCHAR[lx*ly*pixelSize];
    if (!m_buffer) {
#ifdef _WIN32
      static bool firstTime = true;
      if (firstTime) {
        firstTime          = false;
        unsigned long size = pixelSize * lx * ly;
        TImageCache::instance()->outputMap(size, "C:\\runout");
        (*TBigMemoryManager::instance()->m_runOutCallback)(size);
      }
#endif
      return;
    }
    // TBigMemoryManager::instance()->checkConsistency();
    // m_totalMemory += ((lx*ly*pixelSize)>>10);
  }
  /* catch(...)
{
TImageCache::instance()->putAllOnDisk();
m_buffer = BigMemoryManager.getMemoryChunk(lx*ly*pixelSize, this);
//m_buffer = new UCHAR[lx*ly*pixelSize];
m_totalMemory += ((lx*ly*pixelSize)>>10);
#ifdef _WIN32
MessageBox(NULL, "Run out of contiguous physical memory: please save all and
restart toonz!", "Warning", MB_OK);
#endif
}*/
}
TRaster() [2/2]
TRaster::TRaster (int lx, int ly, int pixelSize, int wrap, UCHAR * buffer, TRaster * parent, bool bufferOwner = false) protected
    : TSmartObject(m_classCode)
    , m_pixelSize(pixelSize)
    , m_lx(lx)
    , m_ly(ly)
    , m_wrap(wrap)
    , m_buffer(buffer)
    , m_bufferOwner(bufferOwner)
    , m_lockCount(0)
#ifdef _DEBUG
    , m_cashed(false)
#endif
{
  if (parent) {
    assert(bufferOwner == false);
    while (parent->m_parent) parent = parent->m_parent;
    parent->addRef();
  }
#ifdef _DEBUG
  else if (bufferOwner)
    TBigMemoryManager::instance()->m_totRasterMemInKb +=
        ((m_lx * m_ly * m_pixelSize) >> 10);
#endif
  m_parent = parent;
  assert(pixelSize > 0);
  assert(lx > 0 && ly > 0);
  assert(wrap >= lx);
  assert(m_buffer);
  // if (parent)
  TBigMemoryManager::instance()->putRaster(this);
  //  TBigMemoryManager::instance()->checkConsistency();
}
~TRaster()
TRaster::~TRaster () virtual
                  {
  bool parent = false;
#ifdef _DEBUG
// TBigMemoryManager::instance()->checkConsistency();
#endif
  // bool ret =
  TBigMemoryManager::instance()->releaseRaster(this);
#ifdef _DEBUG
// TBigMemoryManager::instance()->checkConsistency();
#endif
  if (m_parent) {
    assert(!m_bufferOwner);
    m_parent->release();
    m_parent = 0;
    parent   = true;
  }
  // if(m_buffer && m_bufferOwner)
  //  {
  // delete [] m_buffer;
  // m_totalMemory += -((m_lx*m_ly*m_pixelSize)>>10);
  // assert(m_totalMemory>=0);
  //  }
  //  UCHAR* aux = m_buffer;
  m_buffer = 0;
#ifdef _DEBUG
// TBigMemoryManager::instance()->checkConsistency();
#endif
}
Member Function Documentation
beginRemapping()
void TRaster::beginRemapping ()
{ m_mutex.lock(); }
clear()
void TRaster::clear ()
                    {
  TRasterCM32 *ras = dynamic_cast<TRasterCM32 *>(this);
  if (ras) {
    // ras->fill(TPixelCM32(0,BackgroundStyle,TPixelCM32::getMaxTone()));
    ras->fill(TPixelCM32());
  } else {
    const int rowSize = getRowSize();
    lock();
    if (m_wrap == m_lx) {
      int bufferSize = rowSize * m_ly;
      memset(getRawData(), 0, bufferSize);
    } else
      for (int y = m_ly - 1; y >= 0; y--) {
        UCHAR *buffer = getRawData(0, y);
        memset(buffer, 0, rowSize);
      }
    unlock();
  }
}
clearOutside()
void TRaster::clearOutside (const TRect & rect)
{
  if (m_lx == 0 || m_ly == 0) return;
  TRect r = rect * getBounds();
  if (r.isEmpty()) return;
  if (r.y0 > 0)  // fascia "inferiore"
  {
    TRect bounds(0, 0, m_lx - 1, r.y0 - 1);
    extract(bounds)->clear();
  }
  if (rect.y1 < m_ly - 1)  // fascia "superiore"
  {
    TRect bounds(0, r.y1 + 1, m_lx - 1, m_ly - 1);
    extract(bounds)->clear();
  }
  if (rect.x0 > 0)  // zona "a sinistra"
  {
    TRect bounds(0, r.y0, r.x0 - 1, r.y1);
    extract(bounds)->clear();
  }
  if (rect.x1 < m_lx - 1)  // zona "a destra"
  {
    TRect bounds(r.x1 + 1, r.y0, m_lx - 1, r.y1);
    extract(bounds)->clear();
  }
}
copy()
void TRaster::copy (const TRasterP & src, const TPoint & offset = TPoint())
Copies the content of the source raster in the current raster.
{
  assert(m_pixelSize == src0->getPixelSize());
  TRect rect = getBounds() * (src0->getBounds() + offset);
  if (rect.isEmpty()) return;
  TRasterP dst = extract(rect);
  TRect r(rect);
  r -= offset;
  // TRasterP src = src0->extract(rect - offset);
  TRasterP src = src0->extract(r);
  assert(dst->getSize() == src->getSize());
  dst->lock();
  src0->lock();
  if (dst->getLx() == dst->getWrap() && src->getLx() == src->getWrap()) {
    int size = rect.getLx() * rect.getLy() * m_pixelSize;
    ::memcpy(dst->getRawData(), src->getRawData(), size);
  } else {
    int rowSize         = dst->getLx() * m_pixelSize;
    int srcWrapSize     = src->getWrap() * m_pixelSize;
    int dstWrapSize     = dst->getWrap() * m_pixelSize;
    const UCHAR *srcRow = src->getRawData();
    UCHAR *dstRow       = dst->getRawData();
    UCHAR *maxDstRow    = dstRow + dstWrapSize * dst->getLy();
    while (dstRow < maxDstRow) {
      ::memcpy(dstRow, srcRow, rowSize);
      dstRow += dstWrapSize;
      srcRow += srcWrapSize;
    }
  }
  dst->unlock();
  src0->unlock();
}
References getRawData(), getWrap(), and TRectT< T >::isEmpty().
Referenced by TRop::copy().
endRemapping()
void TRaster::endRemapping ()
{ m_mutex.unlock(); }
extract()
TRasterP TRaster::extract (int x0, int y0, int x1, int y1) inline virtual
Reimplemented in TRasterT< T >, TRasterT< TPixelGR8 >, TRasterT< TPixelCM32 >, TRasterT< TPixel32 >, TRasterT< DataPixel >, TRasterT< pixel_type >, TRasterT< GRAY >, and TRasterT< PIXEL >.
{
  TRect rect(x0, y0, x1, y1);
  return extract(rect);
}
fillRawData()
void TRaster::fillRawData (const UCHAR * pixel) protected
{
  if (m_lx == 0 || m_ly == 0) return;
  // N.B. uso la convenzione stl per end()
  const int wrapSize = m_wrap * m_pixelSize;
  const int rowSize  = m_lx * m_pixelSize;
  UCHAR *buf1        = m_parent ? m_parent->m_buffer : m_buffer;
  lock();
  unsigned char *firstPixel = getRawData();
  const unsigned char *lastPixel =
      firstPixel + wrapSize * (m_ly - 1) + m_pixelSize * (m_lx - 1);
  // riempio la prima riga
  unsigned char *pixel          = firstPixel;
  const unsigned char *endpixel = firstPixel + rowSize;
  while (pixel < endpixel) {
    assert(firstPixel <= pixel && pixel <= lastPixel);
    ::memcpy(pixel, color, m_pixelSize);
    pixel += m_pixelSize;
  }
  // riempio le altre
  pixel += wrapSize - rowSize;
  const unsigned char *endrow = pixel + wrapSize * (m_ly - 1);
  while (pixel < endrow) {
    assert(firstPixel <= pixel && pixel + rowSize - m_pixelSize <= lastPixel);
    ::memcpy(pixel, firstPixel, rowSize);
    pixel += wrapSize;
  }
  UCHAR *buf2 = m_parent ? m_parent->m_buffer : m_buffer;
  unlock();
}
fillRawDataOutside()
void TRaster::fillRawDataOutside (const TRect & rect, const UCHAR * pixel) protected
{
  if (m_lx == 0 || m_ly == 0) return;
  TRect r = rect * getBounds();
  if (r.isEmpty()) return;
  if (r.y0 > 0)  // fascia "inferiore"
  {
    TRect bounds(0, 0, m_lx - 1, r.y0 - 1);
    extract(bounds)->fillRawData(pixel);
  }
  if (rect.y1 < m_ly - 1)  // fascia "superiore"
  {
    TRect bounds(0, r.y1 + 1, m_lx - 1, m_ly - 1);
    extract(bounds)->fillRawData(pixel);
  }
  if (rect.x0 > 0)  // zona "a sinistra"
  {
    TRect bounds(0, r.y0, r.x0 - 1, r.y1);
    extract(bounds)->fillRawData(pixel);
  }
  if (rect.x1 < m_lx - 1)  // zona "a destra"
  {
    TRect bounds(r.x1 + 1, r.y0, m_lx - 1, r.y1);
    extract(bounds)->fillRawData(pixel);
  }
}
getBounds()
TRect TRaster::getBounds () const inline
{ return TRect(0, 0, m_lx - 1, m_ly - 1); };
getCenter()
TPoint TRaster::getCenter () const inline
{ return TPoint(m_lx / 2, m_ly / 2); };
getCenterD()
TPointD TRaster::getCenterD () const inline
{ return TPointD(0.5 * m_lx, 0.5 * m_ly); };
getLx()
int TRaster::getLx () const inline
{ return m_lx; };
getLy()
int TRaster::getLy () const inline
{ return m_ly; };
getParent()
TRasterP TRaster::getParent () inline
{ return m_parent; }
getPixelSize()
int TRaster::getPixelSize () const inline
{ return m_pixelSize; };
getRawData() [1/4]
UCHAR * TRaster::getRawData () inline
{ return m_buffer; };
getRawData() [2/4]
const UCHAR * TRaster::getRawData () const inline
Returns a pointer to the image buffer.
{ return m_buffer; };
Referenced by TRop::convertRaster50to46(), copy(), ShadingContext::draw(), ShadingContext::loadTexture(), TRop::lockRaster(), TCleanupper::process(), and RasterPool::releaseRaster().
getRawData() [3/4]
UCHAR * TRaster::getRawData (int x, int y) inline
{
    assert(0 <= x && x < m_lx && 0 <= y && y < m_ly);
    return m_buffer + (y * m_wrap + x) * m_pixelSize;
  };
getRawData() [4/4]
const UCHAR * TRaster::getRawData (int x, int y) const inline
Returns a pointer to the image buffer positioned in the (x,y) coords.
{
    assert(0 <= x && x < m_lx && 0 <= y && y < m_ly);
    return m_buffer + (y * m_wrap + x) * m_pixelSize;
  };
getRowSize()
int TRaster::getRowSize () const inline
{ return m_pixelSize * m_lx; };
getSize()
TDimension TRaster::getSize () const inline
{ return TDimension(m_lx, m_ly); };
getWrap()
int TRaster::getWrap () const inline
Returns the length of a row in pixel.
{ return m_wrap; };  // lunghezza di una riga in pixel
Referenced by TRop::convertRaster50to46(), copy(), ShadingContext::draw(), ShadingContext::loadTexture(), and TCleanupper::process().
isEmpty()
bool TRaster::isEmpty () const inline
{ return getSize() == TDimension(); };
lock()
void TRaster::lock () inline
              {
    if (!TBigMemoryManager::instance()->isActive()) return;
    TThread::MutexLocker sl(&m_mutex);
    if (m_parent)
      m_parent->lock();
    else
      ++m_lockCount;
  }
rotate180()
void TRaster::rotate180 ()
{
  // const int rowSize = m_lx * m_pixelSize;
  const int wrapSize = m_wrap * m_pixelSize;
  std::unique_ptr<UCHAR[]> auxBuf(new UCHAR[m_pixelSize]);
  lock();
  UCHAR *buff1 = getRawData();
  UCHAR *buff2 = buff1 + wrapSize * (m_ly - 1) + m_pixelSize * (m_lx - 1);
  if (m_wrap == m_lx) {
    while (buff1 < buff2) {
      ::memcpy(auxBuf.get(), buff1, m_pixelSize);
      ::memcpy(buff1, buff2, m_pixelSize);
      ::memcpy(buff2, auxBuf.get(), m_pixelSize);
      buff1 += m_pixelSize;
      buff2 -= m_pixelSize;
    }
  } else {
    for (int y = 0; y < m_ly / 2; y++) {
      UCHAR *a = buff1, *b = buff2;
      for (int x = 0; x < m_lx; x++) {
        ::memcpy(auxBuf.get(), a, m_pixelSize);
        ::memcpy(a, b, m_pixelSize);
        ::memcpy(b, auxBuf.get(), m_pixelSize);
        a += m_pixelSize;
        b -= m_pixelSize;
      }
      buff1 += wrapSize;
      buff2 -= wrapSize;
    }
  }
  unlock();
}
rotate90()
void TRaster::rotate90 ()
                       {
  /*
  UCHAR *auxBuf= new UCHAR[m_pixelSize];
for(int y=m_ly;y>0;y--)
{
  UCHAR *a = getRawData() + wrapSize * (y-1) + m_pixelSize * (m_lx-1);
for (int x=m_lx-1;x>=0;x--)
  {
    UCHAR *b = a - (m_ly-1)*m_pixelSize *(m_lx-x);
    ::memcpy(auxBuf,  a,   m_pixelSize);
    ::memcpy(a,       b,   m_pixelSize);
    ::memcpy(b,    auxBuf, m_pixelSize);
    a-=m_pixelSize;
  }
}
*/
}
unlock()
void TRaster::unlock () inline
                {
    if (!TBigMemoryManager::instance()->isActive()) return;
    TThread::MutexLocker sl(&m_mutex);
    if (m_parent)
      m_parent->unlock();
    else {
      assert(m_lockCount > 0);
      --m_lockCount;
    }
  }
xMirror()
void TRaster::xMirror ()
                      {
  const int wrapSize        = m_wrap * m_pixelSize;
  const int lastPixelOffset = (m_lx - 1) * m_pixelSize;
  std::unique_ptr<UCHAR[]> auxBuf(new UCHAR[m_pixelSize]);
  lock();
  UCHAR *row = getRawData();
  for (int i = 0; i < m_ly; i++) {
    UCHAR *a = row, *b = row + lastPixelOffset;
    while (a < b) {
      ::memcpy(auxBuf.get(), a, m_pixelSize);
      ::memcpy(a, b, m_pixelSize);
      ::memcpy(b, auxBuf.get(), m_pixelSize);
      a += m_pixelSize;
      b -= m_pixelSize;
    }
    row += wrapSize;
  }
  unlock();
}
yMirror()
void TRaster::yMirror ()
                      {
  const int rowSize  = m_lx * m_pixelSize;
  const int wrapSize = m_wrap * m_pixelSize;
  std::unique_ptr<UCHAR[]> auxBuf(new UCHAR[rowSize]);
  lock();
  UCHAR *buff1 = getRawData();
  UCHAR *buff2 = getRawData(0, (m_ly - 1));
  while (buff1 < buff2) {
    ::memcpy(auxBuf.get(), buff1, rowSize);
    ::memcpy(buff1, buff2, rowSize);
    ::memcpy(buff2, auxBuf.get(), rowSize);
    buff1 += wrapSize;
    buff2 -= wrapSize;
  }
  unlock();
}
Friends And Related Function Documentation
TBigMemoryManager
friend class TBigMemoryManager friend
Member Data Documentation
m_buffer
UCHAR* TRaster::m_buffer protected
m_bufferOwner
bool TRaster::m_bufferOwner protected
m_lockCount
int TRaster::m_lockCount protected
m_lx
int TRaster::m_lx protected
m_ly
int TRaster::m_ly protected
m_parent
TRaster* TRaster::m_parent protected
m_pixelSize
int TRaster::m_pixelSize protected
m_wrap
int TRaster::m_wrap protected
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/traster.h
E:/opentoonz/toonz/sources/common/traster/traster.cpp