opentoonz: TLevelColumnFx Class Reference
TLevelColumnFx Class Reference
Public Member Functions
TFx * clone (bool recursive=true) const override
TPalette * getPalette (int frame) const
TFilePath getPalettePath (int frame) const
void setColumn (TXshLevelColumn *column)
TXshLevelColumn * getColumn () const
std::wstring getColumnName () const override
std::wstring getColumnId () const override
int getColumnIndex () const override
TXshColumn * getXshColumn () const override
bool isCachable () const override
bool canHandle (const TRenderSettings &info, double frame) override
TAffine handledAffine (const TRenderSettings &info, double frame) override
TAffine getDpiAff (int frame)
TFxTimeRegion getTimeRegion () const override
bool doGetBBox (double frame, TRectD &bBox, const TRenderSettings &info) override
std::string getAlias (double frame, const TRenderSettings &info) const override
int getMemoryRequirement (const TRectD &rect, double frame, const TRenderSettings &info) override
void doDryCompute (TRectD &rect, double frame, const TRenderSettings &info) override
void doCompute (TTile &tile, double frame, const TRenderSettings &info) override
void saveData (TOStream &os) override
void loadData (TIStream &is) override
const TPersistDeclaration * getDeclaration () const override
std::string getPluginId () const override
Public Member Functions inherited from TColumnFx
virtual int getColumnIndex () const =0
virtual std::wstring getColumnName () const =0
virtual std::wstring getColumnId () const =0
virtual TXshColumn * getXshColumn () const =0
int getReferenceColumnIndex () const override
Public Member Functions inherited from TRasterFx
virtual bool getBBox (double frame, TRectD &bBox, TPixel32 &bgColor)=0
virtual string getName () const =0
virtual TRect getInvalidRect (const TRect &max)=0
virtual void compute (double frame, const TTile &tile)=0
virtual void allocateAndCompute (double frame, const TDimension size, const TPointD &pos, TTile &tile)
virtual void compute (TTile &tile, double frame, const TRenderSettings &info)
This method supplies the actual fx rendering code.
void allocateAndCompute (TTile &tile, const TPointD &pos, const TDimension &size, TRasterP templateRas, double frame, const TRenderSettings &info)
virtual bool doGetBBox (double frame, TRectD &bBox, const TRenderSettings &info)=0
bool getBBox (double frame, TRectD &bBox, const TRenderSettings &info)
virtual bool isCachable () const
virtual void transform (double frame, int port, const TRectD &rectOnOutput, const TRenderSettings &infoOnOutput, TRectD &rectOnInput, TRenderSettings &infoOnInput)
virtual bool canHandle (const TRenderSettings &info, double frame)=0
virtual TAffine handledAffine (const TRenderSettings &info, double frame)
void enableCache (bool on)
bool isCacheEnabled () const
std::string getAlias (double frame, const TRenderSettings &info) const override
virtual void dryCompute (TRectD &rect, double frame, const TRenderSettings &info)
virtual int getMemoryRequirement (const TRectD &rect, double frame, const TRenderSettings &info)
virtual bool allowUserCacheOnPort (int port)
virtual bool isPlugin () const
Public Member Functions inherited from TFx
virtual std::wstring getName () const
void setName (std::wstring name)
std::wstring getFxId () const
void setFxId (std::wstring id)
TParamContainer * getParams ()
const TParamContainer * getParams () const
void addParamVar (TParamVar *var)
virtual TFx * clone (bool recursive=true) const
TFx * clone (TFx *fx, bool recursive) const
void unlinkParams ()
virtual void linkParams (TFx *src)
TFx * getLinkedFx () const
bool addInputPort (const std::string &name, TFxPort &p)
bool addInputPort (const std::string &name, TFxPort *p, int groupIndex)
bool removeInputPort (const std::string &name)
returns false on duplicate names. Ownership is transferred to the group.
bool renamePort (const std::string &oldName, const std::string &newName)
if not found.
bool connect (const std::string &name, TFx *other)
Equivalent to getInputPort(name)->setFx(other).
bool disconnect (const std::string &name)
Equivalent to getInputPort(name)->setFx(0).
int getInputPortCount () const
TFxPort * getInputPort (int index) const
TFxPort * getInputPort (const std::string &name) const
std::string getInputPortName (int index) const
virtual int dynamicPortGroupsCount () const
virtual const TFxPortDG * dynamicPortGroup (int g) const
bool hasDynamicPortGroups () const
void clearDynamicPortGroup (int g)
bool addOutputConnection (TFxPort *port)
bool removeOutputConnection (TFxPort *port)
virtual bool isZerary () const
virtual int getReferenceColumnIndex () const
virtual TFxPort * getXsheetPort () const
int getOutputConnectionCount () const
TFxPort * getOutputConnection (int i) const
virtual TFxTimeRegion getTimeRegion () const
void setActiveTimeRegion (const TFxTimeRegion &tr)
TFxTimeRegion getActiveTimeRegion () const
virtual bool checkActiveTimeRegion () const
void disconnectAll ()
virtual void getParamUIs (TParamUIConcept *&params, int &length)
std::string getFxType () const
virtual std::string getPluginId () const =0
void onChange (const TParamChange &c) override
void addObserver (TFxObserver *)
void removeObserver (TFxObserver *)
void notify (const TFxChange &change)
void notify (const TFxPortAdded &change)
void notify (const TFxPortRemoved &change)
void notify (const TFxParamAdded &change)
void notify (const TFxParamRemoved &change)
void loadData (TIStream &is) override
void saveData (TOStream &os) override
void loadPreset (TIStream &is)
void savePreset (TOStream &os)
TFxAttributes * getAttributes () const
virtual std::string getAlias (double frame, const TRenderSettings &info) const
virtual void compatibilityTranslatePort (int majorVersion, int minorVersion, std::string &portName)
virtual int getPreferredInputPort ()
virtual void callStartRenderHandler ()
virtual void callEndRenderHandler ()
virtual void callStartRenderFrameHandler (const TRenderSettings *rs, double frame)
virtual void callEndRenderFrameHandler (const TRenderSettings *rs, double frame)
virtual void onObsoleteParamLoaded (const std::string &paramName)
void setFxVersion (int)
int getFxVersion () const
unsigned long getIdentifier () const
void setIdentifier (unsigned long id)
void setNewIdentifier ()
Public Member Functions inherited from TSmartObject
TSmartObject (ClassCode classCode)
void addRef ()
void release ()
TINT32 getRefCount () const
Public Member Functions inherited from TPersist
virtual void loadData (TIStream &is)=0
virtual void saveData (TOStream &os)=0
std::string getStreamTag () const
virtual const TPersistDeclaration * getDeclaration () const =0
virtual void onChange (const TParamChange &)=0
Additional Inherited Members
Public Types inherited from TFx
typedef TFx * CreateProc()
Public Types inherited from TSmartObject
typedef short ClassCode
Public Types inherited from TPersist
typedef TPersist * CreateProc()
Static Public Member Functions inherited from TRasterFx
static TRasterP applyAffine (TTile &tileOut, const TTile &tileIn, const TRenderSettings &info)
static int memorySize (const TRectD &rect, int bpp)
Static Public Member Functions inherited from TFx
static void listFxs (std::vector< TFxInfo > &fxInfos)
static TFxInfo getFxInfo (const std::string &fxIdentifier)
static TFx * create (std::string name)
Static Public Member Functions inherited from TSmartObject
static TINT32 getInstanceCount (ClassCode code)
Static Public Member Functions inherited from TPersist
static void declare (CreateProc *)
static TPersist * create (const std::string &name)
virtual void doCompute (TTile &tile, double frame, const TRenderSettings &settings)=0
virtual void doDryCompute (TRectD &rect, double frame, const TRenderSettings &info)
Detailed Description
Constructor & Destructor Documentation
TLevelColumnFx()
TLevelColumnFx::TLevelColumnFx ()
    : m_levelColumn(0), m_isCachable(true), m_mutex(), m_offlineContext(0) {
  setName(L"LevelColumn");
}
~TLevelColumnFx()
TLevelColumnFx::~TLevelColumnFx ()
{
  if (m_offlineContext) delete m_offlineContext;
}
Member Function Documentation
canHandle()
bool TLevelColumnFx::canHandle (const TRenderSettings & info, double frame) override virtual
Implements TRasterFx.
{
  // NOTE 1: Currently, it is necessary that level columns return FALSE for
  // raster levels - just a quick way to tell the cache functions that they
  // have to be cached.
  if (!m_levelColumn) return true;
  TXshCell cell = m_levelColumn->getCell(m_levelColumn->getFirstRow());
  if (cell.isEmpty()) return true;
  TXshSimpleLevel *sl = cell.m_level->getSimpleLevel();
  if (!sl) return true;
  return (sl->getType() == PLI_XSHLEVEL &&
          !vectorMustApplyCmappedFx(info.m_data));
}
clone()
TFx * TLevelColumnFx::clone (bool recursive = true) const override virtual
Reimplemented from TFx.
{
  TLevelColumnFx *clonedFx =
      dynamic_cast<TLevelColumnFx *>(TFx::clone(recursive));
  assert(clonedFx);
  clonedFx->m_levelColumn = m_levelColumn;
  clonedFx->m_isCachable  = m_isCachable;
  return clonedFx;
}
doCompute()
void TLevelColumnFx::doCompute (TTile & tile, double frame, const TRenderSettings & info) override virtual
Implements TRasterFx.
{
  if (!m_levelColumn) return;
  // Ensure that a corresponding cell and level exists
  int row       = (int)frame;
  TXshCell cell = m_levelColumn->getCell(row);
  if (cell.isEmpty()) return;
  TXshSimpleLevel *sl = cell.m_level->getSimpleLevel();
  if (!sl) return;
  TFrameId fid = cell.m_frameId;
  TImageP img;
  TImageInfo imageInfo;
  // Now, fetch the image
  if (sl->getType() != PLI_XSHLEVEL) {
    // Raster case
    LevelFxBuilder builder(getAlias(frame, TRenderSettings()) + "_image", frame,
                           info, sl, fid);
    getImageInfo(imageInfo, sl, fid);
    TRectD imgRect(0, 0, imageInfo.m_lx, imageInfo.m_ly);
    builder.setRasBounds(TRect(0, 0, imageInfo.m_lx - 1, imageInfo.m_ly - 1));
    builder.build(imgRect);
    img = builder.getImage();
  } else {
    // Vector case (loading is immediate)
    if (!img) {
      img = sl->getFullsampledFrame(
          fid, ((info.m_bpp == 64) ? ImageManager::is64bitEnabled : 0) |
                   ImageManager::dontPutInCache);
    }
  }
  // Extract the required geometry
  TRect tileBounds(tile.getRaster()->getBounds());
  TRectD tileRectD = TRectD(tileBounds.x0, tileBounds.y0, tileBounds.x1 + 1,
                            tileBounds.y1 + 1) +
                     tile.m_pos;
  // To be sure, if there is no image, return.
  if (!img) return;
  TRectD bBox = img->getBBox();
  // Discriminate image type
  if (TVectorImageP vectorImage = img) {
    // Vector case
    if (vectorMustApplyCmappedFx(info.m_data)) {
      // Deal separately
      applyTzpFxsOnVector(vectorImage, tile, frame, info);
    } else {
      QMutexLocker m(&m_mutex);
      bBox = info.m_affine * vectorImage->getBBox();
      TDimension size(tile.getRaster()->getSize());
      TAffine aff = TTranslation(-tile.m_pos.x, -tile.m_pos.y) *
                    TScale(1.0 / info.m_shrinkX, 1.0 / info.m_shrinkY) *
                    info.m_affine;
      applyCmappedFx(vectorImage, info.m_data, (int)frame);
      TPalette *vpalette = vectorImage->getPalette();
      assert(vpalette);
      m_isCachable = !vpalette->isAnimated();
      int oldFrame = vpalette->getFrame();
      TVectorRenderData rd(TVectorRenderData::ProductionSettings(), aff,
                           TRect(size), vpalette);
      if (!m_offlineContext || m_offlineContext->getLx() < size.lx ||
          m_offlineContext->getLy() < size.ly) {
        if (m_offlineContext) delete m_offlineContext;
        m_offlineContext = new TOfflineGL(size);
      }
      m_offlineContext->makeCurrent();
      m_offlineContext->clear(TPixel32(0, 0, 0, 0));
      // If level has animated palette, it is necessary to lock palette's color
      // against
      // concurrents TPalette::setFrame.
      if (!m_isCachable) vpalette->mutex()->lock();
      vpalette->setFrame((int)frame);
      m_offlineContext->draw(vectorImage, rd, true);
      vpalette->setFrame(oldFrame);
      if (!m_isCachable) vpalette->mutex()->unlock();
      m_offlineContext->getRaster(tile.getRaster());
      m_offlineContext->doneCurrent();
    }
  } else {
    // Raster case
    TRasterP ras;
    TAffine aff;
    TRasterImageP ri = img;
    TToonzImageP ti  = img;
    img              = 0;
    if (ri) {
      // Fullcolor case
      ras = ri->getRaster();
      ri  = 0;
      TRaster32P ras32(ras);
      TRaster64P ras64(ras);
      // Ensure that ras is either a 32 or 64 fullcolor.
      // Otherwise, we have to convert it.
      if (!ras32 && !ras64) {
        TRasterP tileRas(tile.getRaster());
        TRaster32P tileRas32(tileRas);
        TRaster64P tileRas64(tileRas);
        if (tileRas32) {
          ras32 = TRaster32P(ras->getLx(), ras->getLy());
          TRop::convert(ras32, ras);
          ras = ras32;
        } else if (tileRas64) {
          ras64 = TRaster64P(ras->getLx(), ras->getLy());
          TRop::convert(ras64, ras);
          ras = ras64;
        } else
          assert(0);
      }
      TXsheet *xsh  = m_levelColumn->getLevelColumn()->getXsheet();
      TXsheet *txsh = sl->getScene()->getTopXsheet();
      LevelProperties *levelProp = sl->getProperties();
      if (Preferences::instance()->isIgnoreAlphaonColumn1Enabled() &&
          m_levelColumn->getIndex() == 0 &&
          isSubsheetChainOnColumn0(txsh, xsh, frame)) {
        TRasterP appRas(ras->clone());
        setMaxMatte(appRas);
        ras = appRas;
      }
      if (levelProp->doPremultiply()) {
        TRasterP appRas = ras->clone();
        TRop::premultiply(appRas);
        ras = appRas;
      }
      if (levelProp->whiteTransp()) {
        TRasterP appRas(ras->clone());
        TRop::whiteTransp(appRas);
        ras = appRas;
      }
      if (levelProp->antialiasSoftness() > 0) {
        TRasterP appRas = ras->create(ras->getLx(), ras->getLy());
        TRop::antialias(ras, appRas, 10, levelProp->antialiasSoftness());
        ras = appRas;
      }
      if (TXshSimpleLevel::m_fillFullColorRaster) {
        TRasterP appRas(ras->clone());
        FullColorAreaFiller filler(appRas);
        TPaletteP palette = new TPalette();
        int styleId       = palette->getPage(0)->addStyle(TPixel32::White);
        FillParameters params;
        params.m_palette      = palette.getPointer();
        params.m_styleId      = styleId;
        params.m_minFillDepth = 0;
        params.m_maxFillDepth = 15;
        filler.rectFill(appRas->getBounds(), params, false);
        ras = appRas;
      }
    } else if (ti) {
      // Colormap case
      // Use the imageInfo's dpi
      ti->setDpi(imageInfo.m_dpix, imageInfo.m_dpiy);
      TImageP newImg = applyTzpFxs(ti, frame, info);
      ri = newImg;
      ti = newImg;
      if (ri)
        ras = ri->getRaster();
      else
        ras = ti->getRaster();
      if (sl->getProperties()->antialiasSoftness() > 0) {
        // convert colormap raster to fullcolor raster before applying antialias
        if (ti) {
          TRaster32P convRas(ras->getSize());
          TRop::convert(convRas, ras, ti->getPalette(), TRect(), false, true);
          ras = convRas;
        }
        TRasterP appRas = ras->create(ras->getLx(), ras->getLy());
        TRop::antialias(ras, appRas, 10,
                        sl->getProperties()->antialiasSoftness());
        ras = appRas;
      }
      ri = 0;
    }
    if (ras) {
      double lx_2 = ras->getLx() / 2.0;
      double ly_2 = ras->getLy() / 2.0;
      TRenderSettings infoAux(info);
      assert(info.m_affine.isTranslation());
      infoAux.m_data.clear();
      // Place the output rect in the image's reference
      tileRectD += TPointD(lx_2 - info.m_affine.a13, ly_2 - info.m_affine.a23);
      // Then, retrieve loaded image's interesting region
      TRectD inTileRectD;
      if (ti) {
        TRect saveBox(ti->getSavebox());
        inTileRectD =
            TRectD(saveBox.x0, saveBox.y0, saveBox.x1 + 1, saveBox.y1 + 1);
      } else {
        TRect rasBounds(ras->getBounds());
        inTileRectD = TRectD(rasBounds.x0, rasBounds.y0, rasBounds.x1 + 1,
                             rasBounds.y1 + 1);
      }
      // And intersect the two
      inTileRectD *= tileRectD;
      // Should the intersection be void, return
      if (inTileRectD.x0 >= inTileRectD.x1 || inTileRectD.y0 >= inTileRectD.y1)
        return;
      // Output that intersection in the requested tile
      TRect inTileRect(tround(inTileRectD.x0), tround(inTileRectD.y0),
                       tround(inTileRectD.x1) - 1, tround(inTileRectD.y1) - 1);
      TTile inTile(ras->extract(inTileRect),
                   inTileRectD.getP00() + TPointD(-lx_2, -ly_2));
      // Observe that inTile is in the standard reference, ie image's minus the
      // center coordinates
      if ((TRasterCM32P)ras) {
        // In the colormapped case, we have to convert the cmap to fullcolor
        TPalette *palette = ti->getPalette();
        if (!m_isCachable) palette->mutex()->lock();
        int prevFrame = palette->getFrame();
        palette->setFrame((int)frame);
        TTile auxtile(TRaster32P(inTile.getRaster()->getSize()), inTile.m_pos);
        TRop::convert(auxtile, inTile, palette, false, true);
        palette->setFrame(prevFrame);
        if (!m_isCachable) palette->mutex()->unlock();
        inTile.setRaster(auxtile.getRaster());
      }
      TRasterFx::applyAffine(tile, inTile, infoAux);
    }
  }
}
doDryCompute()
void TLevelColumnFx::doDryCompute (TRectD & rect, double frame, const TRenderSettings & info) override virtual
Declares the computation scheme of this fx for rendering optimization purposes. This is an important function of the Toonz rendering API, and should be reimplemented with the necessary care. The Toonz rendering process makes use of this function to enact most of the optimization steps about the fx computation, in particular fx caching. A correct implementation of this method should follow these rules: The invocation of child node computations should be faithfully reproduced. TRasterFx::compute and TRasterFx::allocateAndCompute calls have to be translated to TRasterFx::dryCompute calls. This fx is intended for precomputation stage, so the hard rendering code should be skipped here. By default, this method raises a dryCompute call to each input port in increasing order, using the TRasterFx::transform method to identify the tiles to be passed on input precomputation.
Reimplemented from TRasterFx.
{
  if (!m_levelColumn) return;
  int row       = (int)frame;
  TXshCell cell = m_levelColumn->getCell(row);
  if (cell.isEmpty()) return;
  TXshSimpleLevel *sl = cell.m_level->getSimpleLevel();
  if (!sl) return;
  // In case this is a vector level, the image is renderized quickly and
  // directly at the
  // correct resolution. Caching is disabled in such case, at the moment.
  if (sl->getType() == PLI_XSHLEVEL) return;
  int renderStatus =
      TRenderer::instance().getRenderStatus(TRenderer::renderId());
  std::string alias = getAlias(frame, TRenderSettings()) + "_image";
  TImageInfo imageInfo;
  getImageInfo(imageInfo, sl, cell.m_frameId);
  TRectD imgRect(0, 0, imageInfo.m_lx, imageInfo.m_ly);
  if (renderStatus == TRenderer::FIRSTRUN) {
    ResourceBuilder::declareResource(alias, 0, imgRect, frame, info, false);
  } else {
    LevelFxBuilder builder(alias, frame, info, sl, cell.m_frameId);
    builder.setRasBounds(TRect(0, 0, imageInfo.m_lx - 1, imageInfo.m_ly - 1));
    builder.simBuild(imgRect);
  }
}
References TXshCellColumn::getCell(), TXshLevel::getSimpleLevel(), TXshLevel::getType(), TRenderer::instance(), TXshCell::isEmpty(), TImageInfo::m_lx, TImageInfo::m_ly, and TRenderer::renderId().
doGetBBox()
bool TLevelColumnFx::doGetBBox (double frame, TRectD & bBox, const TRenderSettings & info) override virtual
Implements TRasterFx.
{
  // Usual preliminaries (make sure a level/cell exists, etc...)
  if (!m_levelColumn) return false;
  int row              = (int)frame;
  const TXshCell &cell = m_levelColumn->getCell(row);
  if (cell.isEmpty()) return false;
  TXshLevelP xshl = cell.m_level;
  if (!xshl) return false;
  TXshSimpleLevel *sl = xshl->getSimpleLevel();
  if (!sl) return false;
  double dpi = 1.0;
  // Discriminate for level type
  int type = xshl->getType();
  if (type != PLI_XSHLEVEL) {
    TImageInfo imageInfo;
    getImageInfo(imageInfo, sl, cell.m_frameId);
    double cx = 0.5 * imageInfo.m_lx;
    double cy = 0.5 * imageInfo.m_ly;
    if (info.m_getFullSizeBBox) {
      bBox = TRectD(-cx, -cy, cx, cy);
    } else {
      TRect imageSavebox(imageInfo.m_x0, imageInfo.m_y0, imageInfo.m_x1,
                         imageInfo.m_y1);
      double x0 = (imageSavebox.x0 - cx);
      double y0 = (imageSavebox.y0 - cy);
      double x1 = x0 + imageSavebox.getLx();
      double y1 = y0 + imageSavebox.getLy();
      bBox      = TRectD(x0, y0, x1, y1);
    }
    dpi = imageInfo.m_dpix / Stage::inch;
  } else {
    TImageP img = m_levelColumn->getCell(row).getImage(false);
    if (!img) return false;
    bBox = img->getBBox();
  }
  // Add the enlargement of the bbox due to Tzp render data
  if (info.m_data.size()) {
    TRectD imageBBox(bBox);
    for (unsigned int i = 0; i < info.m_data.size(); ++i) {
      TRectD enlargedImageBBox = info.m_data[i]->getBBoxEnlargement(imageBBox);
      double enlargement       = enlargedImageBBox.x1 - imageBBox.x1;
      bBox += imageBBox.enlarge(enlargement * dpi);
    }
  }
  return true;
}
getAlias()
std::string TLevelColumnFx::getAlias (double frame, const TRenderSettings & info) const override virtual
Reimplemented from TFx.
{
  if (!m_levelColumn || m_levelColumn->getCell((int)frame).isEmpty())
    return std::string();
  const TXshCell &cell = m_levelColumn->getCell((int)frame);
  TFilePath fp;
  TXshSimpleLevel *sl = cell.getSimpleLevel();
  if (!sl) {
    // Try with the sub-xsheet case
    TXshChildLevel *childLevel = cell.m_level->getChildLevel();
    if (childLevel) return ::getAlias(childLevel->getXsheet(), frame, info);
    return std::string();
  }
  TFilePath path = sl->getPath();
  if (!cell.m_frameId.isNoFrame())
    fp = path.withFrame(cell.m_frameId);
  else
    fp = path;
  std::string rdata;
  std::vector<TRasterFxRenderDataP>::const_iterator it = info.m_data.begin();
  for (; it != info.m_data.end(); ++it) {
    TRasterFxRenderDataP data = *it;
    if (data) rdata += data->toString();
  }
  if (sl->getType() == PLI_XSHLEVEL || sl->getType() == TZP_XSHLEVEL) {
    TPalette *palette = cell.getPalette();
    if (palette && palette->isAnimated())
      rdata += "animatedPlt" + std::to_string(frame);
  }
  if (Preferences::instance()->isIgnoreAlphaonColumn1Enabled()) {
    TXsheet *xsh  = m_levelColumn->getLevelColumn()->getXsheet();
    TXsheet *txsh = sl->getScene()->getTopXsheet();
    if (m_levelColumn->getIndex() == 0 &&
        isSubsheetChainOnColumn0(txsh, xsh, frame))
      rdata += "column_0";
  }
  return getFxType() + "[" + ::to_string(fp.getWideString()) + "," + rdata +
         "]";
}
getColumn()
TXshLevelColumn * TLevelColumnFx::getColumn () const inline
{ return m_levelColumn; }
getColumnId()
std::wstring TLevelColumnFx::getColumnId () const override virtual
Implements TColumnFx.
{
  if (!m_levelColumn) return L"Col?";
  return L"Col" + std::to_wstring(m_levelColumn->getIndex() + 1);
}
getColumnIndex()
int TLevelColumnFx::getColumnIndex () const override virtual
Implements TColumnFx.
{
  return m_levelColumn ? m_levelColumn->getIndex() : -1;
}
getColumnName()
std::wstring TLevelColumnFx::getColumnName () const override virtual
Implements TColumnFx.
{
  if (!m_levelColumn) return L"";
  int idx = getColumnIndex();
  return ::to_wstring(m_levelColumn->getXsheet()
                          ->getStageObject(TStageObjectId::ColumnId(idx))
                          ->getName());
}
getDeclaration()
const TPersistDeclaration * TLevelColumnFx::getDeclaration () const override virtual
      This pure virtual method is used to define a global pointer to the
object. This method is overridden with the macro PERSIST_DECLARATION(T).
For example:
class DVAPI TStageObjectTree final : public TPersist {
PERSIST_DECLARATION(TStageObjectTree)
public:
...
Implements TPersist.
{
  return &columnFxInfo;
}
getDpiAff()
TAffine TLevelColumnFx::getDpiAff (int frame)
{
  if (!m_levelColumn) return TAffine();
  TXshCell cell = m_levelColumn->getCell(frame);
  if (cell.isEmpty()) return TAffine();
  TXshSimpleLevel *sl = cell.m_level->getSimpleLevel();
  TFrameId fid        = cell.m_frameId;
  if (sl) return ::getDpiAffine(sl, cell.m_frameId, true);
  return TAffine();
}
getMemoryRequirement()
int TLevelColumnFx::getMemoryRequirement (const TRectD & rect, double frame, const TRenderSettings & info) override virtual
Specifies the approximate size (in MegaBytes) of the maximum allocation instance that this fx will need to perform in order to render the passed input. This method should be reimplemented in order to make the Toonz rendering process aware of the use of big raster memory chunks, at least. Observe that the passed tile geometry is implicitly already allocated <\i> for the fx output.
The default implementation returns 0, assuming that the passed implicit memory size is passed below in node computation without further allocation of resources. Fxs can reimplement this to -1 to explicitly disable the Toonz's smart memory handling.
Note
The rendering process ensures that the passed render settings are handled by the fx before this function is invoked - do not waste code for it.
See also
TRasterFx::memorySize and TRasterFx::canHandle methods.
Reimplemented from TRasterFx.
{
  // Sandor fxs are currently considered *VERY* inefficient upon tile
  // subdivision
  if (mustApplySandorFx(info.m_data)) {
    return -1;
  }
  return 0;
}
getPalette()
TPalette * TLevelColumnFx::getPalette (int frame) const
{
  if (!m_levelColumn) return 0;
  TXshCell cell = m_levelColumn->getCell(frame);
  if (cell.isEmpty()) return 0;
  TXshSimpleLevel *sl = cell.m_level->getSimpleLevel();
  if (!sl) return 0;
  return sl->getPalette();
}
getPalettePath()
TFilePath TLevelColumnFx::getPalettePath (int frame) const
{
  if (!m_levelColumn) return TFilePath();
  TXshCell cell = m_levelColumn->getCell(frame);
  if (cell.isEmpty()) return TFilePath();
  TXshSimpleLevel *sl = cell.m_level->getSimpleLevel();
  if (!sl) return TFilePath();
  if (sl->getType() == TZP_XSHLEVEL)
    return sl->getScene()->decodeFilePath(
        sl->getPath().withNoFrame().withType("tpl"));
  if (sl->getType() == PLI_XSHLEVEL)
    return sl->getScene()->decodeFilePath(sl->getPath());
  return TFilePath();
}
getPluginId()
std::string TLevelColumnFx::getPluginId () const override virtual
Implements TFx.
{ return "Toonz_"; }
getTimeRegion()
TFxTimeRegion TLevelColumnFx::getTimeRegion () const override virtual
Reimplemented from TFx.
{
  if (!m_levelColumn) return TFxTimeRegion();
  int first = m_levelColumn->getFirstRow();
  int last  = m_levelColumn->getRowCount();
  return TFxTimeRegion(first, last);
}
getXshColumn()
TXshColumn * TLevelColumnFx::getXshColumn () const override virtual
Implements TColumnFx.
{ return m_levelColumn; }
handledAffine()
TAffine TLevelColumnFx::handledAffine (const TRenderSettings & info, double frame) override virtual
Reimplemented from TRasterFx.
{
  if (!m_levelColumn) return TAffine();
  TXshCell cell = m_levelColumn->getCell(m_levelColumn->getFirstRow());
  if (cell.isEmpty()) return TAffine();
  TXshSimpleLevel *sl = cell.m_level->getSimpleLevel();
  if (!sl) return TAffine();
  if (sl->getType() == PLI_XSHLEVEL)
    return vectorMustApplyCmappedFx(info.m_data)
               ? TRasterFx::handledAffine(info, frame)
               : info.m_affine;
  // Accept any translation consistent with the image's pixels geometry
  TImageInfo imageInfo;
  getImageInfo(imageInfo, sl, cell.m_frameId);
  TPointD pixelsOrigin(-0.5 * imageInfo.m_lx, -0.5 * imageInfo.m_ly);
  const TAffine &aff = info.m_affine;
  if (aff.a11 != 1.0 || aff.a22 != 1.0 || aff.a12 != 0.0 || aff.a21 != 0.0)
    return TTranslation(-pixelsOrigin);
  // This is a translation, ok. Just ensure it is consistent.
  TAffine consistentAff(aff);
  consistentAff.a13 -= pixelsOrigin.x, consistentAff.a23 -= pixelsOrigin.y;
  consistentAff.a13 = tfloor(consistentAff.a13),
  consistentAff.a23 = tfloor(consistentAff.a23);
  consistentAff.a13 += pixelsOrigin.x, consistentAff.a23 += pixelsOrigin.y;
  return consistentAff;
}
isCachable()
bool TLevelColumnFx::isCachable () const inline override virtual
Reimplemented from TRasterFx.
{ return m_isCachable; }
loadData()
void TLevelColumnFx::loadData (TIStream & is) override virtual
 This is a pure virtual function and must be overridden with a method
that implements the object loading from a stream (i.e take the object's features from a formatted data stream). For example the TStageObject class use his implementation to take the values of the parameters that characterizes a stage object as name, coordinates, etc... from a file. is is an input file stream
Reimplemented from TFx.
{
  // The internal numeric identifier is set here but not in constructors.
  // This is *intended* as fx cloning needs to retain the original id
  // through the fxs tree deployment procedure happening just before a
  // render process (see scenefx.cpp).
  TFx::loadData(is);
  setNewIdentifier();
}
References TFx::loadData().
saveData()
void TLevelColumnFx::saveData (TOStream & os) override virtual
 This is a pure virtual function and must be overridden with a method
that implements the object saving to a data stream (i.e put the object's features on a formatted data stream). For example the TStageObject class use his implementation to save the values of the parameters that characterizes a stage object as name, coordinates, etc... on a file os is an output file stream.
Reimplemented from TFx.
{
  assert(m_levelColumn);
  TFx::saveData(os);
}
References TFx::saveData().
setColumn()
void TLevelColumnFx::setColumn (TXshLevelColumn * column)
{
  m_levelColumn = column;
}
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/toonz/tcolumnfx.h
E:/opentoonz/toonz/sources/toonzlib/tcolumnfx.cpp