opentoonz: FxSchematicNode Class Reference
FxSchematicNode Class Reference
Signals
void switchCurrentFx (TFx *fx)
void currentColumnChanged (int index)
void fxNodeDoubleClicked ()
Signals inherited from SchematicNode
void sceneChanged ()
void xsheetChanged ()
void nodeChangedSize ()
Public Member Functions
FxSchematicNode (FxSchematicScene *parent, TFx *fx, qreal width, qreal height, eFxType type)
void setWidth (const qreal &width)
void setHeight (const qreal &height)
void setSchematicNodePos (const QPointF &pos) const override
TFx * getFx () const
bool isA (eFxType type)
int getInputPortCount ()
int getInputDockId (FxSchematicDock *dock)
FxSchematicPort * getInputPort (int i)
FxSchematicPort * getOutputPort ()
FxSchematicPort * getLinkPort ()
bool isNameEditing ()
void onClicked () override
bool isCurrentFxLinked (SchematicNode *comingNode)
void setIsCurrentFxLinked (bool value, FxSchematicNode *comingNode)
void setPosition (const QPointF &newPos) override
void updatePortsPosition ()
virtual bool isOpened ()
virtual bool isEnabled () const
virtual bool isCached () const
virtual void resize (bool maximizeNode)
void toggleNormalIconView ()
bool isNormalIconView ()
Public Member Functions inherited from SchematicNode
SchematicNode (SchematicScene *scene)
QRectF boundingRect () const override
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=0) override
SchematicPort * addPort (int portId, SchematicPort *port)
void erasePort (int portId)
SchematicPort * getPort (int portId) const
QList< SchematicNode * > getLinkedNodes (int portId) const
virtual void setSchematicNodePos (const QPointF &pos) const =0
virtual void setPosition (const QPointF &newPos)=0
void updateLinksGeometry ()
virtual void onClicked ()
Protected Types
enum eDropActionMode { eShift , eNone }
Protected Member Functions
virtual void checkDynamicInputPortSize () const
void addDynamicInputPort (int groupIndex) const
Adds a dynamic group port to the associated fx.
bool removeDynamicInputPort (const std::string &name) const
void shiftLinks () const
Moves the port group links to the front ports.
void updateOutputDockToolTips (const QString &name)
Protected Member Functions inherited from SchematicNode
void mouseMoveEvent (QGraphicsSceneMouseEvent *me) override
void mousePressEvent (QGraphicsSceneMouseEvent *me) override
void mouseReleaseEvent (QGraphicsSceneMouseEvent *me) override
Protected Attributes
QString m_name
Node's name (displayed on top, editable)
TFxP m_fx
The node's associated fx (could be a wrapper to the actual fx)
TFxP m_actualFx
The actual node's associated fx.
FxSchematicNode * m_linkedNode
QList< FxSchematicDock * > m_inDocks
FxSchematicDock * m_outDock
FxSchematicDock * m_linkDock
SchematicName * m_nameItem
eFxType m_type
bool m_isCurrentFxLinked
bool m_isNormalIconView
Protected Attributes inherited from SchematicNode
SchematicScene * m_scene
qreal m_width
qreal m_height
Qt::MouseButton m_buttonState
QMap< int, SchematicPort * > m_ports
Detailed Description
Member Enumeration Documentation
eDropActionMode
enum FxSchematicNode::eDropActionMode protected
{ eShift, eNone };
Constructor & Destructor Documentation
FxSchematicNode()
FxSchematicNode::FxSchematicNode (FxSchematicScene * parent, TFx * fx, qreal width, qreal height, eFxType type)
    : SchematicNode(scene)
    , m_fx(fx)
    , m_type(type)
    , m_isCurrentFxLinked(false)
    , m_isNormalIconView(scene->isNormalIconView()) {
  if (m_type == eGroupedFx)
    m_actualFx = 0;
  else {
    // m_fx could be the zerary wrapper to the actual (user-coded) fx - find and
    // store it.
    TZeraryColumnFx *zfx = dynamic_cast<TZeraryColumnFx *>(m_fx.getPointer());
    m_actualFx           = zfx ? zfx->getZeraryFx() : m_fx;
  }
  setWidth(width);
  setHeight(height);
}
Member Function Documentation
addDynamicInputPort()
void FxSchematicNode::addDynamicInputPort (int groupIndex) const protected
Adds a dynamic group port to the associated fx.
{
  assert(m_actualFx);
  assert(groupIdx < m_actualFx->dynamicPortGroupsCount());
  TFxPort *port = new TRasterFxPort;
  // Add the port with a suitable port name
  const TFxPortDG *group = m_actualFx->dynamicPortGroup(groupIdx);
  for (int n =
           group->ports().size() + 1;  // +1 since ports start from <prefix>1
       !m_actualFx->addInputPort(
           group->portsPrefix() + QString::number(n).toStdString(), port,
           groupIdx);
       ++n)
    ;
}
References TFx::addInputPort(), and m_actualFx.
Referenced by checkDynamicInputPortSize().
checkDynamicInputPortSize()
void FxSchematicNode::checkDynamicInputPortSize () const protected virtual
If the fx has dynamic port groups, ensures that each group always has at least one unlinked port that users can attach to, while keeping the number of unlinked ports to the minimum allowed by the group's specifics.
{
  assert(m_actualFx);
  if (!m_actualFx->hasDynamicPortGroups()) return;
  // Shift holes in each dynamic port group links toward the end of the group
  shiftLinks();
  // Treat each dynamic port group independently
  int g, gCount = m_actualFx->dynamicPortGroupsCount();
  for (g = 0; g != gCount; ++g) {
    const TFxPortDG *group = m_actualFx->dynamicPortGroup(g);
    int gSize              = group->ports().size();
    int minPortsCount = group->minPortsCount();
    if (gSize < minPortsCount) {
      // Add empty ports up to the group's minimal required quota
      for (; gSize != minPortsCount; ++gSize) addDynamicInputPort(g);
    }
    // Must remove all unlinked ports beyond the minimal - however, we'll be
    // iterating
    // on the ports container, so it's easier if we avoid removing WHILE
    // iterating
    // So, fill in a list of all the fx's unlinked ports first
    QList<std::string> unlinkedPorts;
    int p, portCount = m_actualFx->getInputPortCount();
    for (p = 0; p != portCount; ++p) {
      TFxPort *port = m_actualFx->getInputPort(p);
      assert(port);
      if ((port->getGroupIndex() == g) && !port->isConnected())
        unlinkedPorts.append(m_actualFx->getInputPortName(p));
    }
    // Remove excess empty ports save for 1 (needed to let the user insert new
    // links)
    if (unlinkedPorts.empty())
      addDynamicInputPort(g);
    else {
      while (unlinkedPorts.size() > 1 &&
             m_actualFx->getInputPortCount() > minPortsCount) {
        removeDynamicInputPort(unlinkedPorts.last());
        unlinkedPorts.pop_back();
      }
    }
  }
}
References addDynamicInputPort(), m_actualFx, removeDynamicInputPort(), and shiftLinks().
getFx()
TFx * FxSchematicNode::getFx () const inline
{ return m_fx.getPointer(); }
getInputDockId()
int FxSchematicNode::getInputDockId (FxSchematicDock * dock)
{
  return m_inDocks.indexOf(dock);
}
getInputPort()
FxSchematicPort * FxSchematicNode::getInputPort (int i) inline
{
    return m_inDocks[i] ? m_inDocks[i]->getPort() : 0;
  }
getInputPortCount()
int FxSchematicNode::getInputPortCount () inline
{ return m_inDocks.size(); }
getLinkPort()
FxSchematicPort * FxSchematicNode::getLinkPort () inline
{
    return m_linkDock ? m_linkDock->getPort() : 0;
  }
getOutputPort()
FxSchematicPort * FxSchematicNode::getOutputPort () inline
{
    return m_outDock ? m_outDock->getPort() : 0;
  }
isA()
bool FxSchematicNode::isA (eFxType type) inline
{ return m_type == type; }
isCached()
bool FxSchematicNode::isCached () const virtual
{
  return TPassiveCacheManager::instance()->cacheEnabled(m_fx.getPointer());
}
isCurrentFxLinked()
bool FxSchematicNode::isCurrentFxLinked (SchematicNode * comingNode) inline
{
    return m_isCurrentFxLinked;
  }
isEnabled()
bool FxSchematicNode::isEnabled () const virtual
{
  TZeraryColumnFx *zcFx = dynamic_cast<TZeraryColumnFx *>(m_fx.getPointer());
  return zcFx ? zcFx->getColumn()->isPreviewVisible()
              : m_fx->getAttributes()->isEnabled();
}
isNameEditing()
bool FxSchematicNode::isNameEditing () inline
{ return m_nameItem->isVisible(); }
isNormalIconView()
bool FxSchematicNode::isNormalIconView () inline
{ return m_isNormalIconView; }
isOpened()
virtual bool FxSchematicNode::isOpened () inline virtual
{ return true; }
onClicked()
void FxSchematicNode::onClicked () override virtual
Reimplemented from SchematicNode.
{
  emit switchCurrentFx(m_fx.getPointer());
  if (TColumnFx *cfx = dynamic_cast<TColumnFx *>(m_fx.getPointer())) {
    int columnIndex = cfx->getColumnIndex();
    if (columnIndex >= 0) emit currentColumnChanged(columnIndex);
  }
}
removeDynamicInputPort()
bool FxSchematicNode::removeDynamicInputPort (const std::string & name) const protected
Removes the port with specified name from the associated fx. Returns false (ie operation refused) if the specified port does not exists, is connected, or is not in a dynamic port group.
{
  assert(m_actualFx);
  TFxPort *port = m_actualFx->getInputPort(
      name);  // Must retrieve the port to access its infos
  if (!port || port->getFx() || port->getGroupIndex() < 0) {
    assert(port && !port->isConnected() && port->getGroupIndex() >= 0);
    return false;
  }
  m_actualFx->removeInputPort(name);
  // delete port;                                                // TFxPortDG
  // owns it - so it would be wrong
  return true;
}
References m_actualFx, and TFx::removeInputPort().
Referenced by checkDynamicInputPortSize().
resize()
virtual void FxSchematicNode::resize (bool maximizeNode) inline virtual
{}
setHeight()
void FxSchematicNode::setHeight (const qreal & height) inline
{ m_height = height; }
setIsCurrentFxLinked()
void FxSchematicNode::setIsCurrentFxLinked (bool value, FxSchematicNode * comingNode)
{
  m_isCurrentFxLinked = value;
  update();
  if (!m_linkDock) return;
  int i;
  for (i = 0; i < m_linkDock->getPort()->getLinkCount(); i++) {
    SchematicNode *node = m_linkDock->getPort()->getLinkedNode(i);
    if (!node || node == comingNode) continue;
    FxSchematicNode *fxNode = dynamic_cast<FxSchematicNode *>(node);
    assert(fxNode);
    fxNode->setIsCurrentFxLinked(value, this);
  }
}
setPosition()
void FxSchematicNode::setPosition (const QPointF & newPos) override virtual
Implements SchematicNode.
{
  FxSchematicScene *fxScene = dynamic_cast<FxSchematicScene *>(scene());
  assert(fxScene);
  fxScene->updateNestedGroupEditors(this, newPos);
}
setSchematicNodePos()
void FxSchematicNode::setSchematicNodePos (const QPointF & pos) const override virtual
Implements SchematicNode.
{
  TPointD p(pos.x(), pos.y());
  if (!m_fx->getAttributes()->isGrouped() ||
      m_fx->getAttributes()->isGroupEditing()) {
    TPointD oldFxPos = m_fx->getAttributes()->getDagNodePos();
    m_fx->getAttributes()->setDagNodePos(p);
    TMacroFx *macro = dynamic_cast<TMacroFx *>(m_fx.getPointer());
    if (macro) {
      TPointD delta =
          p - (oldFxPos != TConst::nowhere ? oldFxPos : TPointD(0, 0));
      std::vector<TFxP> fxs = macro->getFxs();
      int i;
      for (i = 0; i < (int)fxs.size(); i++) {
        TPointD oldPos = fxs[i]->getAttributes()->getDagNodePos();
        if (oldPos != TConst::nowhere)
          fxs[i]->getAttributes()->setDagNodePos(oldPos + delta);
      }
    }
  } else {
    const FxGroupNode *groupNode = dynamic_cast<const FxGroupNode *>(this);
    assert(groupNode);
    groupNode->updateFxsDagPosition(p);
  }
}
setWidth()
void FxSchematicNode::setWidth (const qreal & width) inline
{ m_width = width; }
shiftLinks()
void FxSchematicNode::shiftLinks () const protected
Moves the port group links to the front ports.
{
  struct locals {
    // Advances p along the ports array, stopping at the first port in the group
    // with the specified
    // connection state. Returns whether the port index is in the ports array
    // range.
    static inline bool moveToNext(const TFxPortDG &group, bool connected,
                                  int &p) {
      int pCount = group.ports().size();
      while (p < pCount && (group.ports()[p]->isConnected() != connected)) ++p;
      return (p < pCount);
    }
  };  // locals
  assert(m_actualFx);
  // Treat each dynamic port group individually
  int g, gCount = m_actualFx->dynamicPortGroupsCount();
  for (g = 0; g != gCount; ++g) {
    const TFxPortDG *group = m_actualFx->dynamicPortGroup(g);
    // Traverse fx ports, moving all the group links to the front
    // First, couple empty and not-empty ports manually
    int e = 0;
    locals::moveToNext(*group, false, e);  // manual advance
    int ne = e + 1;
    if (locals::moveToNext(*group, true, ne))  // manual advance
    {
      do {
        // Swap links between the empty and not-empty ports
        TFxPort *ePort  = group->ports()[e];
        TFxPort *nePort = group->ports()[ne];
        ePort->setFx(nePort->getFx());
        nePort->setFx(0);
        ++e, ++ne;
        // Then, advance coupled from there
      } while (locals::moveToNext(*group, false, e) &&
               locals::moveToNext(*group, true, ne));
    }
  }
}
References m_actualFx.
Referenced by checkDynamicInputPortSize().
toggleNormalIconView()
void FxSchematicNode::toggleNormalIconView () inline
{ m_isNormalIconView = !m_isNormalIconView; }
updateOutputDockToolTips()
void FxSchematicNode::updateOutputDockToolTips (const QString & name) protected
{
  FxSchematicPort *outPort = getOutputPort();
  int i;
  for (i = 0; i < outPort->getLinkCount(); i++) {
    SchematicLink *link = outPort->getLink(i);
    if (!link) continue;
    SchematicPort *linkedPort = link->getOtherPort(outPort);
    assert(linkedPort);
    FxSchematicPort *linkedFxPort = dynamic_cast<FxSchematicPort *>(linkedPort);
    FxSchematicDock *linkedFxDock = linkedFxPort->getDock();
    linkedFxDock->setToolTip(name);
  }
}
updatePortsPosition()
void FxSchematicNode::updatePortsPosition ()
{
  struct locals {
    struct PositionAssigner {
      double m_lastYPos;
      bool isLarge;
      inline void assign(FxSchematicDock *dock) {
        dock->setPos(0, m_lastYPos);
        if (isLarge)
          m_lastYPos += dock->boundingRect().height();
        else
          m_lastYPos += dock->boundingRect().height() + 4;  // 4 is margin
      }
    };
  };  // locals
  locals::PositionAssigner positioner;
  if (m_isNormalIconView) {
    positioner.m_lastYPos = m_height;
    positioner.isLarge    = true;
  } else {
    positioner.m_lastYPos = 0;
    positioner.isLarge    = false;
  }
  if (!(m_actualFx && m_actualFx->hasDynamicPortGroups())) {
    // 'Fake' or common schematic fx nodes can just list the prepared m_inDocks
    // container incrementally
    for (int i = 0; i != m_inDocks.size(); ++i) positioner.assign(m_inDocks[i]);
  } else {
    // Otherwise, port groups must be treated
    assert(m_inDocks.size() == m_actualFx->getInputPortCount());
    int incrementalGroupIndex = -1;  // We'll assume that groups are encountered
    // incrementally (requires not ill-formed fxs).
    int p, pCount = m_actualFx->getInputPortCount();
    for (p = 0; p != pCount; ++p) {
      int g = m_actualFx->getInputPort(p)->getGroupIndex();
      if (g < 0)
        positioner.assign(
            m_inDocks[p]);  // The port is in no group - just add it
      else if (g > incrementalGroupIndex) {
        // Position the whole group
        incrementalGroupIndex = g;
        for (int gp = p; gp != pCount; ++gp)
          if (m_actualFx->getInputPort(gp)->getGroupIndex() == g)
            positioner.assign(m_inDocks[gp]);
      }
    }
  }
}
Member Data Documentation
m_actualFx
TFxP FxSchematicNode::m_actualFx protected
The actual node's associated fx.
Referenced by addDynamicInputPort(), checkDynamicInputPortSize(), removeDynamicInputPort(), and shiftLinks().
m_fx
TFxP FxSchematicNode::m_fx protected
The node's associated fx (could be a wrapper to the actual fx)
m_inDocks
QList<FxSchematicDock *> FxSchematicNode::m_inDocks protected
m_isCurrentFxLinked
bool FxSchematicNode::m_isCurrentFxLinked protected
m_isNormalIconView
bool FxSchematicNode::m_isNormalIconView protected
m_linkDock
FxSchematicDock* FxSchematicNode::m_linkDock protected
m_linkedNode
FxSchematicNode* FxSchematicNode::m_linkedNode protected
m_name
QString FxSchematicNode::m_name protected
Node's name (displayed on top, editable)
m_nameItem
SchematicName* FxSchematicNode::m_nameItem protected
m_outDock
FxSchematicDock* FxSchematicNode::m_outDock protected
m_type
eFxType FxSchematicNode::m_type protected
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/toonzqt/fxschematicnode.h
E:/opentoonz/toonz/sources/toonzqt/fxschematicnode.cpp