opentoonz: OnRenderCompleted Class Reference
OnRenderCompleted Class Reference final
Public Member Functions
OnRenderCompleted (const TFilePath &fp, bool error)
TThread::Message * clone () const override
void onDeliver () override
Public Member Functions inherited from TThread::Message
virtual Message * clone () const =0
virtual void onDeliver ()=0
void send ()
void sendBlocking ()
Detailed Description
Constructor & Destructor Documentation
OnRenderCompleted()
OnRenderCompleted::OnRenderCompleted (const TFilePath & fp, bool error) inline
      : m_fp(fp), m_error(error) {}
Member Function Documentation
clone()
TThread::Message * OnRenderCompleted::clone () const inline override virtual
Implements TThread::Message.
{
    return new OnRenderCompleted(*this);
  }
onDeliver()
void OnRenderCompleted::onDeliver () inline override virtual
quite ugly I know....
Implements TThread::Message.
{
    if (m_error) {
      m_error = false;
      DVGui::error(
          QObject::tr("There was an error saving frames for the %1 level.")
              .arg(QString::fromStdWString(
                  m_fp.withoutParentDir().getWideString())));
    }
    bool isPreview = (m_fp.getType() == "noext");
    TImageCache::instance()->remove(::to_string(m_fp.getWideString() + L".0"));
    TNotifier::instance()->notify(TSceneNameChange());
    if (Preferences::instance()->isGeneratedMovieViewEnabled()) {
      if (!isPreview && (Preferences::instance()->isDefaultViewerEnabled()) &&
          (m_fp.getType() == "mov" || m_fp.getType() == "avi" ||
           m_fp.getType() == "3gp" || m_fp.getType() == "mp4" ||
           m_fp.getType() == "gif" || m_fp.getType() == "webm")) {
        QString name = QString::fromStdString(m_fp.getName());
        int index;
        if ((index = name.indexOf("#RENDERID")) != -1)
          m_fp = m_fp.withName(name.left(index).toStdWString());
        if (!TSystem::showDocument(m_fp)) {
          QString msg(QObject::tr("It is not possible to display the file %1: "
                                  "no player associated with its format")
                          .arg(QString::fromStdWString(
                              m_fp.withoutParentDir().getWideString())));
          DVGui::warning(msg);
        }
      }
      else {
        int r0, r1, step;
        TApp *app         = TApp::instance();
        ToonzScene *scene = app->getCurrentScene()->getScene();
        TOutputProperties &outputSettings =
            isPreview ? *scene->getProperties()->getPreviewProperties()
                      : *scene->getProperties()->getOutputProperties();
        outputSettings.getRange(r0, r1, step);
        const TRenderSettings rs    = outputSettings.getRenderSettings();
        if (r0 == 0 && r1 == -1) r0 = 0, r1 = scene->getFrameCount() - 1;
        double timeStretchFactor =
            isPreview
                ? 1.0
                : (double)outputSettings.getRenderSettings().m_timeStretchTo /
                      outputSettings.getRenderSettings().m_timeStretchFrom;
        r0 = tfloor(r0 * timeStretchFactor);
        r1 = tceil((r1 + 1) * timeStretchFactor) - 1;
        TXsheet::SoundProperties *prop = new TXsheet::SoundProperties();
        prop->m_frameRate              = outputSettings.getFrameRate();
        TSoundTrack *snd =
            app->getCurrentXsheet()->getXsheet()->makeSound(prop);
        // keeps ffmpeg files from being previewed until import is fixed
        if (m_fp.getType() != "mp4" && m_fp.getType() != "webm" &&
            m_fp.getType() != "gif" && m_fp.getType() != "spritesheet") {
          if (outputSettings.getRenderSettings().m_stereoscopic) {
            assert(!isPreview);
            ::viewFile(m_fp.withName(m_fp.getName() + "_l"), r0 + 1, r1 + 1,
                       step, isPreview ? rs.m_shrinkX : 1, snd, 0, false, true);
            ::viewFile(m_fp.withName(m_fp.getName() + "_r"), r0 + 1, r1 + 1,
                       step, isPreview ? rs.m_shrinkX : 1, snd, 0, false, true);
          } else
            ::viewFile(m_fp, r0 + 1, r1 + 1, step, isPreview ? rs.m_shrinkX : 1,
                       snd, 0, false, true);
        }
      }
    }
  }
References TApp::getCurrentScene(), TApp::getCurrentXsheet(), ToonzScene::getFrameCount(), TOutputProperties::getFrameRate(), TSceneProperties::getOutputProperties(), TSceneProperties::getPreviewProperties(), ToonzScene::getProperties(), TOutputProperties::getRange(), TOutputProperties::getRenderSettings(), TApp::instance(), TRenderSettings::m_shrinkX, TRenderSettings::m_stereoscopic, TRenderSettings::m_timeStretchFrom, TRenderSettings::m_timeStretchTo, and TImageCache::remove().
The documentation for this class was generated from the following file:
E:/opentoonz/toonz/sources/toonz/rendercommand.cpp