opentoonz: FunctionTreeModel::ChannelGroup Class Reference
FunctionTreeModel::ChannelGroup Class Reference
The model item representing a channels group.
#include <functiontreeviewer.h>
Public Types
enum ShowFilter { ShowAllChannels , ShowAnimatedChannels }
Public Member Functions
ChannelGroup (const QString &name="")
bool isActive () const override
bool isAnimated () const override
bool isIgnored () const override
virtual QString getShortName () const
virtual QString getLongName () const
virtual QString getIdName () const
void setShowFilter (ShowFilter showFilter)
ShowFilter getShowFilter () const
void applyShowFilter ()
QVariant data (int role) const override
void setChildrenAllActive (bool active)
void displayAnimatedChannels ()
virtual bool isActive () const =0
virtual bool isAnimated () const =0
virtual bool isIgnored () const =0
Public Member Functions inherited from TreeModel::Item
Item * getParent () const
int getChildCount () const
Item * getChild (int row) const
Item * appendChild (Item *child)
virtual void * getInternalPointer () const
see setChildren() below
void setChildren (QList< Item * > &children)
virtual void refresh ()
TreeModel * getModel () const
void setModel (TreeModel *model)
int getRow () const
row is the Item index in the parent. (used by QModelIndex)
void setRow (int row)
int getDepth () const
root_depth == 0; son_depth == parent_depth + 1
bool isOpen () const
void setIsOpen (bool opened)
virtual QVariant data (int role) const
QModelIndex createIndex ()
Detailed Description
The model item representing a channels group.
Member Enumeration Documentation
ShowFilter
enum FunctionTreeModel::ChannelGroup::ShowFilter
{ ShowAllChannels, ShowAnimatedChannels };
Constructor & Destructor Documentation
ChannelGroup()
FunctionTreeModel::ChannelGroup::ChannelGroup (const QString & name = "")
    : m_name(name), m_showFilter(ShowAllChannels) {}
~ChannelGroup()
FunctionTreeModel::ChannelGroup::~ChannelGroup ()
{}
Member Function Documentation
applyShowFilter()
void FunctionTreeModel::ChannelGroup::applyShowFilter ()
Todo:
This is not recursive - I guess it should be...?
{
  int i, itemCount = getChildCount();
  for (i = 0; i < itemCount; i++) {
    FunctionTreeModel::Channel *channel =
        dynamic_cast<FunctionTreeModel::Channel *>(getChild(i));
    /*--- ChannelGroupの内部も同じフィルタで更新する ---*/
    if (!channel) {
      FunctionTreeModel::ChannelGroup *channelGroup =
          dynamic_cast<FunctionTreeModel::ChannelGroup *>(getChild(i));
      if (!channelGroup) continue;
      channelGroup->setShowFilter(m_showFilter);
      continue;
    }
    bool showItem = (m_showFilter == ShowAllChannels) ||
                    channel->getParam()->hasKeyframes();
    QModelIndex modelIndex = createIndex();
    getModel()->setRowHidden(i, modelIndex, !showItem);
    if (!showItem) channel->setIsActive(false);
  }
}
References TDoubleParam::hasKeyframes().
data()
QVariant FunctionTreeModel::ChannelGroup::data (int role) const override virtual
used by TreeModel::data(); default implementation provides open/close folder icons
Reimplemented from TreeModel::Item.
Reimplemented in FxChannelGroup, and StageObjectChannelGroup.
{
  if (role == Qt::DisplayRole)
    return getLongName();
  else if (role == Qt::DecorationRole) {
    bool animated = isAnimated();
    bool active   = isActive();
    bool ignored  = (animated) ? isIgnored() : false;
    if (active) {
      static QIcon folderAnimOpen(createQIcon("folder_anim_on", true));
      static QIcon folderAnimClose(createQIcon("folder_anim", true));
      static QIcon folderOpen(createQIcon("folder_on", true));
      static QIcon folderClose(createQIcon("folder", true));
      static QIcon ignoredOn(":Resources/paramignored_on.svg");
      return animated ? (isOpen() ? folderAnimOpen
                                  : (ignored ? ignoredOn : folderAnimClose))
                      : (isOpen() ? folderOpen : folderClose);
    } else {
      static QIcon folderAnimOpen(createQIcon("folder_anim_inactive_on", true));
      static QIcon folderAnimClose(createQIcon("folder_anim_inactive", true));
      static QIcon folderOpen(createQIcon("folder_inactive_on", true));
      static QIcon folderClose(createQIcon("folder_inactive", true));
      static QIcon ignoredOff(":Resources/paramignored_off.svg");
      return animated ? (isOpen() ? folderAnimOpen
                                  : (ignored ? ignoredOff : folderAnimClose))
                      : (isOpen() ? folderOpen : folderClose);
    }
  } else
    return Item::data(role);
}
References TreeModel::Item::data().
Referenced by StageObjectChannelGroup::data().
displayAnimatedChannels()
void FunctionTreeModel::ChannelGroup::displayAnimatedChannels ()
show all the animated channels when the scene switched
{
  int itemCount = getChildCount();
  int i;
  for (i = 0; i < itemCount; i++) {
    FunctionTreeModel::Channel *channel =
        dynamic_cast<FunctionTreeModel::Channel *>(getChild(i));
    if (!channel) {
      FunctionTreeModel::ChannelGroup *channelGroup =
          dynamic_cast<FunctionTreeModel::ChannelGroup *>(getChild(i));
      if (!channelGroup) continue;
      channelGroup->displayAnimatedChannels();
      continue;
    }
    channel->setIsActive(channel->getParam()->hasKeyframes());
  }
}
References displayAnimatedChannels(), and TDoubleParam::hasKeyframes().
Referenced by displayAnimatedChannels(), and FunctionTreeView::displayAnimatedChannels().
getIdName()
QString FunctionTreeModel::ChannelGroup::getIdName () const virtual
{
  QString tmpName = QString(m_name);
  tmpName.remove(QChar(' '), Qt::CaseInsensitive);
  tmpName = tmpName.toLower();
  FunctionTreeModel::ChannelGroup *parentGroup =
      dynamic_cast<FunctionTreeModel::ChannelGroup *>(getParent());
  if (parentGroup) {
    return parentGroup->getIdName() + QString(".") + tmpName;
  }
  return tmpName;
}
getLongName()
virtual QString FunctionTreeModel::ChannelGroup::getLongName () const inline virtual
{ return m_name; }
getShortName()
virtual QString FunctionTreeModel::ChannelGroup::getShortName () const inline virtual
{ return m_name; }
getShowFilter()
ShowFilter FunctionTreeModel::ChannelGroup::getShowFilter () const inline
{ return m_showFilter; }
isActive()
bool FunctionTreeModel::ChannelGroup::isActive () const override virtual
Implements FunctionTreeModel::Item.
{
  // Analyze children. If one is active, this is active too.
  int c, childCount = getChildCount();
  for (c = 0; c != childCount; ++c)
    if (static_cast<Item *>(getChild(c))->isActive()) return true;
  return false;
}
isAnimated()
bool FunctionTreeModel::ChannelGroup::isAnimated () const override virtual
Implements FunctionTreeModel::Item.
{
  // Same for the animated feature, this is animate if any of its children is.
  int c, childCount = getChildCount();
  for (c = 0; c != childCount; ++c)
    if (static_cast<Item *>(getChild(c))->isAnimated()) return true;
  return false;
}
isIgnored()
bool FunctionTreeModel::ChannelGroup::isIgnored () const override virtual
Implements FunctionTreeModel::Item.
{
  // Same for the ignored ones, show warning icon if any of its children is.
  int c, childCount = getChildCount();
  for (c = 0; c != childCount; ++c)
    if (static_cast<Item *>(getChild(c))->isIgnored()) return true;
  return false;
}
setChildrenAllActive()
void FunctionTreeModel::ChannelGroup::setChildrenAllActive (bool active)
{
  for (int i = 0; i < getChildCount(); i++) {
    // for Channel
    FunctionTreeModel::Channel *channel =
        dynamic_cast<FunctionTreeModel::Channel *>(getChild(i));
    if (channel) {
      channel->setIsActive(active);
      continue;
    }
    // for ChannelGroup
    else {
      FunctionTreeModel::ChannelGroup *channelGroup =
          dynamic_cast<FunctionTreeModel::ChannelGroup *>(getChild(i));
      if (channelGroup) {
        channelGroup->setChildrenAllActive(active);
        continue;
      }
    }
  }
}
setShowFilter()
void FunctionTreeModel::ChannelGroup::setShowFilter (ShowFilter showFilter)
{
  m_showFilter = showFilter;
  applyShowFilter();
}
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/toonzqt/functiontreeviewer.h
E:/opentoonz/toonz/sources/toonzqt/functiontreeviewer.cpp