opentoonz: FxBuilder Class Reference
FxBuilder Class Reference abstract
Public Member Functions
virtual TFx * create ()=0
FxBuilder (ToonzScene *scene, TXsheet *xsh, double frame, int whichLevels, bool isPreview=false, bool expandXSheet=true)
TFxP buildFx ()
TFxP buildFx (const TFxP &root, BSFX_Transforms_Enum transforms)
PlacedFx makePF (TLevelColumnFx *fx)
Creates and returns a PlacedFx for a TLevelColumnFx.
PlacedFx makePF (TPaletteColumnFx *fx)
PlacedFx makePF (TZeraryColumnFx *fx)
PlacedFx makePF (TXsheetFx *fx)
PlacedFx makePFfromUnaryFx (TFx *fx)
PlacedFx makePFfromGenericFx (TFx *fx)
PlacedFx makePF (TFx *fx)
TFxP getFxWithColumnMovements (const PlacedFx &pf)
bool addPlasticDeformerFx (PlacedFx &pf)
Public Attributes
ToonzScene * m_scene
TXsheet * m_xsh
TAffine m_cameraAff
double m_cameraZ
double m_frame
int m_whichLevels
bool m_isPreview
bool m_expandXSheet
int m_particleDescendentCount
QMap< std::wstring, QPair< TFxP, bool > > m_globalControlledFx
Detailed Description
Constructor & Destructor Documentation
~FxBuilder()
virtual FxBuilder::~FxBuilder () inline virtual
{}
FxBuilder()
FxBuilder::FxBuilder (ToonzScene * scene, TXsheet * xsh, double frame, int whichLevels, bool isPreview = false, bool expandXSheet = true)
    : m_scene(scene)
    , m_xsh(xsh)
    , m_frame(frame)
    , m_whichLevels(whichLevels)
    , m_isPreview(isPreview)
    , m_expandXSheet(expandXSheet)
    , m_particleDescendentCount(0) {
  TStageObjectId cameraId;
  if (m_isPreview)
    cameraId = m_xsh->getStageObjectTree()->getCurrentPreviewCameraId();
  else
    cameraId = m_xsh->getStageObjectTree()->getCurrentCameraId();
  TStageObject *camera = m_xsh->getStageObject(cameraId);
  m_cameraAff          = camera->getPlacement(m_frame);
  m_cameraZ            = camera->getZ(m_frame);
}
Member Function Documentation
addPlasticDeformerFx()
bool FxBuilder::addPlasticDeformerFx (PlacedFx & pf)
{
  TStageObject *obj =
      m_xsh->getStageObject(TStageObjectId::ColumnId(pf.m_columnIndex));
  TStageObjectId parentId(obj->getParent());
  if (parentId.isColumn() && obj->getParentHandle()[0] != 'H') {
    const SkDP &sd =
        m_xsh->getStageObject(parentId)->getPlasticSkeletonDeformation();
    const TXshCell &parentCell = m_xsh->getCell(m_frame, parentId.getIndex());
    TXshSimpleLevel *parentSl  = parentCell.getSimpleLevel();
    if (sd && parentSl && (parentSl->getType() == MESH_XSHLEVEL)) {
      // Plastic Deformer case - add the corresponding fx,
      // absorb the dpi and local column placement affines
      PlasticDeformerFx *plasticFx = new PlasticDeformerFx;
      plasticFx->m_xsh             = m_xsh;
      plasticFx->m_col             = parentId.getIndex();
      plasticFx->m_texPlacement    = obj->getLocalPlacement(m_frame);
      if (!plasticFx->connect("source", pf.m_fx.getPointer()))
        assert(!"Could not connect ports!");
      pf.m_fx  = plasticFx;
      pf.m_aff = pf.m_aff * plasticFx->m_texPlacement.inv();
      return true;
    }
  }
  return false;
}
buildFx() [1/2]
TFxP FxBuilder::buildFx ()
{
  TFx *outputFx = m_xsh->getFxDag()->getOutputFx(0);
  if (!outputFx || outputFx->getInputPortCount() != 1 ||
      outputFx->getInputPort(0)->getFx() == 0)
    return TFxP();
  outputFx->setName(L"OutputFx");
  assert(m_particleDescendentCount == 0);
  PlacedFx pf = makePF(outputFx->getInputPort(0)->getFx());
  assert(m_particleDescendentCount == 0);
  TAffine cameraFullAff = m_cameraAff * TScale((1000 + m_cameraZ) / 1000);
  return TFxUtil::makeAffine(pf.makeFx(), cameraFullAff.inv());
}
buildFx() [2/2]
TFxP FxBuilder::buildFx (const TFxP & root, BSFX_Transforms_Enum transforms)
{
  assert(m_particleDescendentCount == 0);
  PlacedFx pf = makePF(root.getPointer());
  assert(m_particleDescendentCount == 0);
  TFxP fx = (transforms & BSFX_COLUMN_TR) ? pf.makeFx() : pf.m_fx;
  if (transforms & BSFX_CAMERA_TR) {
    TAffine cameraFullAff = m_cameraAff * TScale((1000 + m_cameraZ) / 1000);
    fx                    = TFxUtil::makeAffine(fx, cameraFullAff.inv());
  }
  return fx;
}
getFxWithColumnMovements()
TFxP FxBuilder::getFxWithColumnMovements (const PlacedFx & pf)
{
  TFxP fx = pf.m_fx;
  if (!fx) return fx;
  if (pf.m_columnIndex == -1) return pf.m_fx;
  TStageObjectId id    = TStageObjectId::ColumnId(pf.m_columnIndex);
  TStageObject *pegbar = m_xsh->getStageObject(id);
  AffineFx *affFx = new AffineFx(m_xsh, pegbar);
  affFx->getInputPort(0)->setFx(fx.getPointer());
  return affFx;
}
makePF() [1/5]
PlacedFx FxBuilder::makePF (TFx * fx)
{
  if (!fx) return PlacedFx();
  if (TLevelColumnFx *lcfx = dynamic_cast<TLevelColumnFx *>(fx))
    return makePF(lcfx);
  else if (TPaletteColumnFx *pcfx = dynamic_cast<TPaletteColumnFx *>(fx))
    return makePF(pcfx);
  else if (TZeraryColumnFx *zcfx = dynamic_cast<TZeraryColumnFx *>(fx))
    return makePF(zcfx);
  else if (TXsheetFx *xsfx = dynamic_cast<TXsheetFx *>(fx))
    return makePF(xsfx);
  else if (fx->getInputPortCount() == 1)
    return makePFfromUnaryFx(fx);
  else
    return makePFfromGenericFx(fx);
}
makePF() [2/5]
PlacedFx FxBuilder::makePF (TLevelColumnFx * fx)
Creates and returns a PlacedFx for a TLevelColumnFx.
{
  assert(m_scene);
  assert(lcfx);
  assert(lcfx->getColumn());
  if (!lcfx || !lcfx->getColumn() || lcfx->getColumn()->isEmpty())
    return PlacedFx();
  if (!lcfx->getColumn()->isPreviewVisible())  // This is the 'eye' icon
                                               // property in the column header
                                               // interface
    return PlacedFx();  // that disables rendering of this particular column
  // Retrieve the corresponding xsheet cell to build up
  /*--  --*/
  TXshCell cell  = lcfx->getColumn()->getCell(tfloor(m_frame));
  int levelFrame = cell.m_frameId.getNumber() - 1;
  /*--  ParticlesFx  --*/
  // -> even if the cell is empty, pass the affine infotmation of the column to
  // the subsequent nodes
  // if (m_particleDescendentCount == 0 && cell.isEmpty()) return PlacedFx();
  if (m_whichLevels == TOutputProperties::AnimatedOnly) {
    // In case only 'animated levels' are selected to be rendered, exclude all
    // 'backgrounds' - that is,
    // fullcolor levels...
    // Still, I wonder if this is still used in Toonz. I don't remember seeing
    // it anywhere :\ ?
    TXshLevel *xl = cell.m_level.getPointer();
    // if the cell is empty, use a level of the first occupied cell instead.
    if (!xl) {
      int r0, r1;
      if (lcfx->getColumn()->getRange(r0, r1) > 0)
        xl = lcfx->getColumn()->getCell(r0).m_level.getPointer();
    }
    /*-- ParticleFxTexture --*/
    if (m_particleDescendentCount == 0) {
      if (!xl ||
          (xl->getType() != PLI_XSHLEVEL && xl->getType() != TZP_XSHLEVEL &&
           xl->getType() != CHILD_XSHLEVEL))
        return PlacedFx();
    }
    /*-- ParticleFxTexture --*/
    else {
      if (xl && xl->getType() != PLI_XSHLEVEL &&
          xl->getType() != TZP_XSHLEVEL && xl->getType() != CHILD_XSHLEVEL)
        return PlacedFx();
    }
  }
  // Build a PlacedFx for the column - start with the standard version for
  // common (image) levels
  PlacedFx pf;
  pf.m_columnIndex = lcfx->getColumn()->getIndex();
  // Build column placement
  bool columnVisible =
      getColumnPlacement(pf, m_xsh, m_frame, pf.m_columnIndex, m_isPreview);
  // if the cell is empty, only inherits its placement
  if ((m_particleDescendentCount == 0 && cell.isEmpty())) return pf;
  pf.m_fx = lcfx;
  /*-- subXsheetBuildFx --*/
  if (!cell.isEmpty() && cell.m_level->getChildLevel()) {
    // Treat the sub-xsheet case - build the sub-render-tree and reassign stuff
    // to pf
    TXsheet *xsh = cell.m_level->getChildLevel()->getXsheet();
    // Build the sub-render-tree
    FxBuilder builder(m_scene, xsh, levelFrame, m_whichLevels, m_isPreview);
    // Then, add the TimeShuffleFx
    pf.m_fx = timeShuffle(builder.buildFx(), levelFrame, lcfx->getTimeRegion(),
                          lcfx->getColumn());
    pf.m_fx->setIdentifier(lcfx->getIdentifier());
    pf.m_fx->getAttributes()->passiveCacheDataIdx() =
        lcfx->getAttributes()->passiveCacheDataIdx();
    // If the level should sustain a Plastic deformation, add the corresponding
    // fx
    addPlasticDeformerFx(pf);
  }
  if (columnVisible) {
    // Column is visible, alright
    TXshSimpleLevel *sl = cell.isEmpty() ? 0 : cell.m_level->getSimpleLevel();
    if (sl) {
      // If the level should sustain a Plastic deformation, add the
      // corresponding fx
      if (!addPlasticDeformerFx(pf)) {
        // Common (image) level case - add an NaAffineFx to compensate for the
        // image's dpi
        TAffine dpiAff = ::getDpiAffine(
            sl, cell.m_frameId, true);  // true stands for 'force full-sampling'
        pf.m_fx = TFxUtil::makeAffine(pf.m_fx, dpiAff);
        if (pf.m_fx) pf.m_fx->setName(L"LevelColumn AffineFx");
      }
    } else {
      // Okay, weird code ensues. This is what happens on non-common image
      // cases, which should be:
      //  1. Sub-Xsheet cases - and it really shouldn't
      //  2. Empty cell cases - with m_particles_blabla > 0; and again I don't
      //  get why on earth this should happen...
      // Please, note that (1) is a bug, although it happens when inserting a
      // common level and a sub-xsh
      // level in the same column...
      // when a cell not exists, there is no way to keep the dpi of the image!
      // in this case it is kept the dpi of the first cell not empty in the
      // column!
      /*--
       * Dpi
       * --*/
      TXshLevelColumn *column = lcfx->getColumn();
      int r0, r1;
      if (column->getRange(r0, r1) > 0)
        sl = column->getCell(r0).m_level->getSimpleLevel();
      if (sl) {
        TAffine dpiAff =
            ::getDpiAffine(sl, column->getCell(r0).m_frameId, true);
        pf.m_fx = TFxUtil::makeAffine(pf.m_fx, dpiAff);
      }
    }
    // Apply column's color filter and semi-transparency for rendering
    TXshLevelColumn *column = lcfx->getColumn();
    if (m_scene->getProperties()->isColumnColorFilterOnRenderEnabled() &&
        (column->getFilterColorId() != TXshColumn::FilterNone ||
         (column->isCamstandVisible() && column->getOpacity() != 255))) {
      TPixel32 colorScale = column->getFilterColor();
      colorScale.m        = column->getOpacity();
      pf.m_fx             = TFxUtil::makeColumnColorFilter(pf.m_fx, colorScale);
    }
    return pf;
  } else
    return PlacedFx();
}
References TXshCellColumn::getCell(), TXshLevel::getChildLevel(), ToonzScene::getProperties(), TXshCellColumn::getRange(), TXshLevel::getSimpleLevel(), TXshLevel::getType(), TXshChildLevel::getXsheet(), TXshCell::isEmpty(), TXshCellColumn::isEmpty(), TXshColumn::isPreviewVisible(), PlacedFx::m_columnIndex, and PlacedFx::m_fx.
makePF() [3/5]
PlacedFx FxBuilder::makePF (TPaletteColumnFx * fx)
{
  assert(pcfx);
  assert(pcfx->getColumn());
  if (!pcfx->getColumn()->isPreviewVisible()) return PlacedFx();
  TXshCell cell = pcfx->getColumn()->getCell(tfloor(m_frame));
  if (cell.isEmpty()) return PlacedFx();
  PlacedFx pf;
  pf.m_columnIndex = pcfx->getColumn()->getIndex();
  pf.m_fx          = pcfx;
  return pf;
}
makePF() [4/5]
PlacedFx FxBuilder::makePF (TXsheetFx * fx)
{
  if (!m_expandXSheet)  // Xsheet expansion is typically blocked for render-tree
                        // building of post-xsheet fxs only.
  {
    PlacedFx ret(fx);
    ret.m_isPostXsheetNode = true;
    return ret;
  }
  // Expand the render-tree from terminal fxs
  TFxSet *fxs = m_xsh->getFxDag()->getTerminalFxs();
  int m       = fxs->getFxCount();
  if (m == 0) {
    PlacedFx ret;
    ret.m_isPostXsheetNode = true;
    return ret;
  }
  std::vector<PlacedFx> pfs(m);
  int i;
  for (i = 0; i < m; i++) {
    // Expand each terminal fx
    TFx *fx = fxs->getFx(i);
    assert(fx);
    pfs[i] = makePF(fx);  // Builds the sub-render-trees here
  }
  /*--
   * XsheetPlacedFxOver
   * --*/
  std::sort(pfs.begin(),
            pfs.end());  // Sort each terminal depending on Z/SO/Column index
  // Compose them in a cascade of overs (or affines 'leftXsheetPort' cases)
  TFxP currentFx =
      pfs[0].makeFx();  // Adds an NaAffineFx if pf.m_aff is not the identity
  for (i = 1; i < m; i++) {
    TFxP fx = pfs[i].makeFx();  // See above
    if (pfs[i].m_leftXsheetPort) {
      // LeftXsheetPort cases happen for those fxs like Add, Multiply, etc that
      // declare an xsheet-like input port.
      // That is, all terminal fxs below ours are attached COMPOSED to enter the
      // fx's leftXsheet input port.
      TFxP inputFx = currentFx;
      inputFx      = TFxUtil::makeAffine(inputFx, pfs[i].m_aff.inv());
      pfs[i].m_leftXsheetPort->setFx(inputFx.getPointer());
      currentFx = fx;
    } else {
      if (Preferences::instance()
              ->isShowRasterImagesDarkenBlendedInViewerEnabled())
        currentFx = TFxUtil::makeDarken(currentFx, fx);
      else
        currentFx = TFxUtil::makeOver(currentFx, fx);  // Common over case
    }
  }
  PlacedFx ret(currentFx);
  ret.m_isPostXsheetNode = true;
  return ret;
}
makePF() [5/5]
PlacedFx FxBuilder::makePF (TZeraryColumnFx * fx)
{
  assert(zcfx);
  assert(zcfx->getColumn());
  if (!zcfx->getColumn()->isPreviewVisible())  // ...
    return PlacedFx();
  if (!zcfx->getAttributes()->isEnabled())  // ...
    return PlacedFx();
  TFx *fx = zcfx->getZeraryFx();
  if (!fx || !fx->getAttributes()->isEnabled())  // ... Perhaps these shouldn't
                                                 // be tested altogether? Only 1
                                                 // truly works !
    return PlacedFx();
  TXshCell cell = zcfx->getColumn()->getCell(tfloor(m_frame));
  // Build
  PlacedFx pf;
  pf.m_columnIndex = zcfx->getColumn()->getIndex();
  // Add the column placement NaAffineFx
  if (!getColumnPlacement(pf, m_xsh, m_frame, pf.m_columnIndex, m_isPreview))
    return PlacedFx();
  // if the cell is empty, only inherits its placement
  if (cell.isEmpty()) return pf;
  // set m_fx only when the current cell is not empty
  pf.m_fx =
      fx->clone(false);  // Detach the fx with a clone. Why? It's typically done
                         // to build fx connections in the render-tree freely.
                         // Here, it's used just for particles, I guess...
  // Deal with input sub-trees
  for (int i = 0; i < fx->getInputPortCount(); ++i) {
    // Note that only particles should end up here, currently
    if (TFxP inputFx = fx->getInputPort(i)->getFx()) {
      PlacedFx inputPF;
      // if the effect is a particle fx, it is necessary to consider also empty
      // cells
      // this causes a connection with the effect and a level also with empty
      // cells.
      if (fx->getFxType() == "STD_particlesFx" ||
          fx->getFxType() == "STD_iwa_TiledParticlesFx" ||
          fx->getFxType() == "STD_tiledParticlesFx") {
        m_particleDescendentCount++;
        inputPF = makePF(inputFx.getPointer());
        m_particleDescendentCount--;
      } else
        inputPF = makePF(inputFx.getPointer());
      inputFx = getFxWithColumnMovements(inputPF);
      if (!inputFx) continue;
      inputFx = TFxUtil::makeAffine(inputFx, pf.m_aff.inv());
      if (!pf.m_fx->connect(pf.m_fx->getInputPortName(i), inputFx.getPointer()))
        assert(!"Could not connect ports!");
    }
  }
  if (pf.m_fx->getFxType() == "STD_iwa_TextFx") {
    TextAwareBaseFx *textFx =
        dynamic_cast<TextAwareBaseFx *>(pf.m_fx.getPointer());
    if (textFx && textFx->getSourceType() != TextAwareBaseFx::INPUT_TEXT) {
      int noteColumnIndex = textFx->getNoteColumnIndex();
      bool getNeighbor =
          (textFx->getSourceType() == TextAwareBaseFx::NEARBY_COLUMN);
      textFx->setNoteLevelStr(getNoteText(m_xsh, m_frame, pf.m_columnIndex,
                                          noteColumnIndex, getNeighbor));
    }
  }
  return pf;
}
makePFfromGenericFx()
PlacedFx FxBuilder::makePFfromGenericFx (TFx * fx)
{
  assert(!dynamic_cast<TLevelColumnFx *>(fx));
  assert(!dynamic_cast<TZeraryColumnFx *>(fx));
  PlacedFx pf;
  if (!fx->getAttributes()->isEnabled()) {
    if (fx->getInputPortCount() == 0) return PlacedFx();
    TFxP inputFx = fx->getInputPort(fx->getPreferredInputPort())->getFx();
    if (inputFx) return makePF(inputFx.getPointer());
    return pf;
  }
  // global controllable fx
  if (fx->getAttributes()->hasGlobalControl()) {
    if (!m_globalControlledFx.contains(fx->getFxId())) {
      GlobalControllableFx *gcFx = dynamic_cast<GlobalControllableFx *>(fx);
      double val                 = gcFx->getGrobalControlValue(m_frame);
      if (val < 1.0) {
        TFxP inputFx = fx->getInputPort(fx->getPreferredInputPort())->getFx();
        if (!inputFx) return pf;
        // insert cross dissolve fx and mix with the input fx
        TFxP blendFx = TFx::create("blendFx");
        blendFx->connect("Source1", fx);
        blendFx->connect("Source2", inputFx.getPointer());
        m_globalControlledFx.insert(fx->getFxId(), {blendFx, true});
        // set the global intensity value to the cross dissolve fx
        dynamic_cast<TDoubleParam *>(blendFx->getParams()->getParam("value"))
            ->setDefaultValue(val * 100.0);
        return makePF(blendFx.getPointer());
      }
    } else if (m_globalControlledFx.value(fx->getFxId()).second)
      m_globalControlledFx[fx->getFxId()].second = false;
    else {
      m_globalControlledFx[fx->getFxId()].second = true;
      return makePF(
          m_globalControlledFx.value(fx->getFxId()).first.getPointer());
    }
  }
  // Multi-input fxs are always cloned - since at least one of its input ports
  // will have an NaAffineFx
  // injected just before its actual input fx.
  pf.m_fx = fx->clone(false);
  bool firstInput = true;
  int m = fx->getInputPortCount();
  for (int i = 0; i < m; ++i) {
    if (TFxP inputFx = fx->getInputPort(i)->getFx()) {
      PlacedFx inputPF = makePF(inputFx.getPointer());
      inputFx          = inputPF.m_fx;
      // check the column index instead of inputFx
      // so that the firstly-found input column always inherits
      // its placement even if the current cell is empty.
      if (inputPF.m_columnIndex < 0 && !inputPF.m_isPostXsheetNode) continue;
      if (firstInput) {
        firstInput = false;
        // The first found input PlacedFx carries its placement infos up
        pf.m_aff              = inputPF.m_aff;
        pf.m_columnIndex      = inputPF.m_columnIndex;
        pf.m_z                = inputPF.m_z;
        pf.m_so               = inputPF.m_so;
        pf.m_isPostXsheetNode = inputPF.m_isPostXsheetNode;
        /*-- BinaryFx --*/
        if (pf.m_fx->getAttributes()->isSpeedAware()) {
          MotionAwareBaseFx *mabfx =
              dynamic_cast<MotionAwareBaseFx *>(pf.m_fx.getPointer());
          if (mabfx) {
            double shutterStart = mabfx->getShutterStart()->getValue(m_frame);
            double shutterEnd   = mabfx->getShutterEnd()->getValue(m_frame);
            int traceResolution = mabfx->getTraceResolution()->getValue();
            /*-- NoneId --*/
            MotionObjectType type   = mabfx->getMotionObjectType();
            int index               = mabfx->getMotionObjectIndex()->getValue();
            TStageObjectId objectId = getMotionObjectId(type, index);
            pf.m_fx->getAttributes()->setMotionPoints(getColumnMotionPoints(
                m_xsh, m_frame, pf.m_columnIndex, objectId, m_isPreview,
                shutterStart, shutterEnd, traceResolution));
          }
        }
        if (!inputFx) continue;
      } else if (!inputFx)
        continue;
      else {
        // The follow-ups traduce their PlacedFx::m_aff into an NaAffineFx,
        // instead
        inputFx = getFxWithColumnMovements(inputPF);
        inputFx = TFxUtil::makeAffine(inputFx, pf.m_aff.inv());
      }
      if (!pf.m_fx->connect(pf.m_fx->getInputPortName(i), inputFx.getPointer()))
        assert(!"Could not connect ports!");
    }
  }
  // The xsheet-like input port is activated and brought upwards whenever it is
  // both
  // specified by the fx, and there is no input fx attached to it.
  if (pf.m_fx->getXsheetPort() && pf.m_fx->getXsheetPort()->getFx() == 0)
    pf.m_leftXsheetPort = pf.m_fx->getXsheetPort();
  return pf;
}
makePFfromUnaryFx()
PlacedFx FxBuilder::makePFfromUnaryFx (TFx * fx)
{
  assert(!dynamic_cast<TLevelColumnFx *>(fx));
  assert(!dynamic_cast<TZeraryColumnFx *>(fx));
  assert(fx->getInputPortCount() == 1);
  TFx *inputFx = fx->getInputPort(0)->getFx();
  if (!inputFx) return PlacedFx();
  // global controllable fx
  if (fx->getAttributes()->hasGlobalControl()) {
    if (!m_globalControlledFx.contains(fx->getFxId())) {
      GlobalControllableFx *gcFx = dynamic_cast<GlobalControllableFx *>(fx);
      double val                 = gcFx->getGrobalControlValue(m_frame);
      if (val < 1.0) {
        // insert cross dissolve fx and mix with the input fx
        TFxP blendFx = TFx::create("blendFx");
        blendFx->connect("Source1", fx);
        blendFx->connect("Source2", inputFx);
        // set the global intensity value to the cross dissolve fx
        dynamic_cast<TDoubleParam *>(blendFx->getParams()->getParam("value"))
            ->setDefaultValue(val * 100.0);
        m_globalControlledFx.insert(fx->getFxId(), {blendFx, true});
        return makePF(blendFx.getPointer());
      }
    } else if (m_globalControlledFx.value(fx->getFxId()).second)
      m_globalControlledFx[fx->getFxId()].second = false;
    else {
      m_globalControlledFx[fx->getFxId()].second = true;
      return makePF(
          m_globalControlledFx.value(fx->getFxId()).first.getPointer());
    }
  }
  PlacedFx pf = makePF(inputFx);  // Build sub-render-tree
  if (pf.m_columnIndex < 0 && !pf.m_isPostXsheetNode) return PlacedFx();
  // inherit the column placement even if the current cell is empty
  if (!pf.m_fx) return pf;
  if (fx->getAttributes()->isEnabled()) {
    // Fx is enabled, so insert it in the render-tree
    // Clone this fx necessary
    if (pf.m_fx.getPointer() != inputFx ||  // As in an earlier makePF, clone
                                            // whenever input connections have
                                            // changed
        fx->getAttributes()->isSpeedAware() ||  // In the 'speedAware' case,
                                                // we'll alter the fx's
                                                // attributes (see below)
        dynamic_cast<TMacroFx *>(fx))  // As for macros... I'm not sure. Not
                                       // even who wrote this *understood*
    // why - it just solved a bug  X( . Investigate!
    {
      fx = fx->clone(false);
      if (!fx->connect(fx->getInputPortName(0), pf.m_fx.getPointer()))
        assert(!"Could not connect ports!");
    }
    pf.m_fx = fx;
    if (fx->getAttributes()->isSpeedAware()) {
      /*--  --*/
      MotionAwareBaseFx *mabfx = dynamic_cast<MotionAwareBaseFx *>(fx);
      if (mabfx) {
        double shutterStart = mabfx->getShutterStart()->getValue(m_frame);
        double shutterEnd   = mabfx->getShutterEnd()->getValue(m_frame);
        int traceResolution = mabfx->getTraceResolution()->getValue();
        /*-- NoneId --*/
        MotionObjectType type   = mabfx->getMotionObjectType();
        int index               = mabfx->getMotionObjectIndex()->getValue();
        TStageObjectId objectId = getMotionObjectId(type, index);
        fx->getAttributes()->setMotionPoints(getColumnMotionPoints(
            m_xsh, m_frame, pf.m_columnIndex, objectId, m_isPreview,
            shutterStart, shutterEnd, traceResolution));
      } else {
        TPointD speed =
            getColumnSpeed(m_xsh, m_frame, pf.m_columnIndex, m_isPreview);
        fx->getAttributes()->setSpeed(speed);
      }
    }
  }
  return pf;
}
Member Data Documentation
m_cameraAff
TAffine FxBuilder::m_cameraAff
m_cameraZ
double FxBuilder::m_cameraZ
m_expandXSheet
bool FxBuilder::m_expandXSheet
m_frame
double FxBuilder::m_frame
m_globalControlledFx
QMap<std::wstring, QPair<TFxP, bool> > FxBuilder::m_globalControlledFx
m_isPreview
bool FxBuilder::m_isPreview
m_particleDescendentCount
int FxBuilder::m_particleDescendentCount
m_scene
ToonzScene* FxBuilder::m_scene
m_whichLevels
int FxBuilder::m_whichLevels
m_xsh
TXsheet* FxBuilder::m_xsh
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/tw/fxbrowser.h
E:/opentoonz/toonz/sources/toonzlib/scenefx.cpp