opentoonz: PlasticSkeleton Class Reference
PlasticSkeleton Class Reference final
Classes
class Imp
Public Types
typedef tcg::Mesh< PlasticSkeletonVertex, tcg::Edge, tcg::FaceN< 3 > > mesh_type
Public Types inherited from TSmartObject
typedef short ClassCode
Public Types inherited from tcg::Mesh< PlasticSkeletonVertex, tcg::Edge, tcg::FaceN< 3 > >
typedef PlasticSkeletonVertex vertex_type
typedef tcg::Edge edge_type
typedef tcg::FaceN< 3 > face_type
typedef list< PlasticSkeletonVertex > vertices_container
typedef list< tcg::Edge > edges_container
typedef list< tcg::FaceN< 3 > > faces_container
Public Types inherited from TPersist
typedef TPersist * CreateProc()
Public Member Functions
PlasticSkeleton (const PlasticSkeleton &other)
PlasticSkeleton & operator= (const PlasticSkeleton &other)
int parentVertex (int v)
void moveVertex (int v, const TPointD &pos)
int addVertex (const PlasticSkeletonVertex &vx, int parent)
associated deformers
int insertVertex (const PlasticSkeletonVertex &vx, int e)
int insertVertex (const PlasticSkeletonVertex &vx, int parent, const std::vector< int > &children)
it is useful as inverse of vertex removal.
void removeVertex (int v)
Removes a vertex, reattaching all its children to parent.
void clear ()
void squeeze ()
bool setVertexName (int v, const QString &name)
void saveData (TOStream &os) override
void loadData (TIStream &is) override
int closestVertex (const TPointD &pos, double *distance=0) const
int closestEdge (const TPointD &pos, double *distance=0) const
std::vector< PlasticHandle > verticesToHandles () const
PlasticSkeleton (PlasticSkeleton &&other)
PlasticSkeleton & operator= (PlasticSkeleton &&other)
Public Member Functions inherited from TSmartObject
TSmartObject (ClassCode classCode)
void addRef ()
void release ()
TINT32 getRefCount () const
Public Member Functions inherited from tcg::Mesh< PlasticSkeletonVertex, tcg::Edge, tcg::FaceN< 3 > >
bool empty () const
void clear ()
int verticesCount () const
int edgesCount () const
int facesCount () const
const vertices_container & vertices () const
vertices_container & vertices ()
const edges_container & edges () const
edges_container & edges ()
const faces_container & faces () const
faces_container & faces ()
int addVertex (const PlasticSkeletonVertex &v)
int addEdge (const tcg::Edge &e)
int addFace (const tcg::FaceN< 3 > &f)
void removeVertex (int v)
void removeEdge (int e)
void removeFace (int f)
const PlasticSkeletonVertex & vertex (int v) const
PlasticSkeletonVertex & vertex (int v)
const tcg::Edge & edge (int e) const
tcg::Edge & edge (int e)
const tcg::FaceN< 3 > & face (int f) const
tcg::FaceN< 3 > & face (int f)
const PlasticSkeletonVertex & edgeVertex (int e, int i) const
PlasticSkeletonVertex & edgeVertex (int e, int i)
Returns the i-th vertex in the edge of index e.
const tcg::FaceN< 3 > & edgeFace (int e, int i) const
tcg::FaceN< 3 > & edgeFace (int e, int i)
Returns the i-th face in the edge of index e.
const PlasticSkeletonVertex & otherEdgeVertex (int e, int v) const
PlasticSkeletonVertex & otherEdgeVertex (int e, int v)
Retrieves the vertex adjacent to e whose index is not v.
const tcg::FaceN< 3 > & otherEdgeFace (int e, int f) const
tcg::FaceN< 3 > & otherEdgeFace (int e, int f)
Retrieves the face adjacent to e whose index is not f.
int edgeInciding (int v1, int v2, int n=0) const
Returns the edge index of the.
void squeeze ()
Eliminates unused list nodes in the representation of vertices, edges and faces.
Public Member Functions inherited from TPersist
virtual void loadData (TIStream &is)=0
virtual void saveData (TOStream &os)=0
std::string getStreamTag () const
virtual const TPersistDeclaration * getDeclaration () const =0
Friends
class PlasticSkeletonDeformation
Additional Inherited Members
Static Public Member Functions inherited from TSmartObject
static TINT32 getInstanceCount (ClassCode code)
Static Public Member Functions inherited from TPersist
static void declare (CreateProc *)
static TPersist * create (const std::string &name)
Protected Attributes inherited from tcg::Mesh< PlasticSkeletonVertex, tcg::Edge, tcg::FaceN< 3 > >
vertices_container m_vertices
edges_container m_edges
faces_container m_faces
Detailed Description
Member Typedef Documentation
mesh_type
typedef tcg::Mesh<PlasticSkeletonVertex, tcg::Edge, tcg::FaceN<3> > PlasticSkeleton::mesh_type
Constructor & Destructor Documentation
PlasticSkeleton() [1/3]
PlasticSkeleton::PlasticSkeleton ()
: m_imp(new Imp) {}
PlasticSkeleton() [2/3]
PlasticSkeleton::PlasticSkeleton (const PlasticSkeleton & other)
    : mesh_type(other), m_imp(new Imp(*other.m_imp)) {}
~PlasticSkeleton()
PlasticSkeleton::~PlasticSkeleton ()
{}
PlasticSkeleton() [3/3]
PlasticSkeleton::PlasticSkeleton (PlasticSkeleton && other)
    : mesh_type(std::forward<mesh_type>(other))
    , m_imp(new Imp(std::move(*other.m_imp))) {}
Member Function Documentation
addVertex()
int PlasticSkeleton::addVertex (const PlasticSkeletonVertex & vx, int parent)
associated deformers
Adds a vertex to the skeleton
{
  // Add the vertex
  int v = mesh_type::addVertex(vx);
  // Retrieve a vertex index
  PlasticSkeletonVertex &vx_ = vertex(v);
  vx_.m_number = m_imp->m_numbersPool.acquire();
  // Assign a name to the vertex in case none was given
  QString name(vx.name());
  if (name.isEmpty())
    name = (v == 0) ? QString("Root")
                    : "Vertex " +
                          QString::number(vx_.m_number).rightJustified(3, '_');
  // Ensure the name is unique
  while (!setVertexName(v, name)) name += "_";
  if (parent >= 0) {
    // Link it to the parent
    mesh_type::addEdge(
        edge_type(parent, v));  // Observe that parent is always v0
    vx_.m_parent = parent;
    assert(parent != v);
  }
  // Notify deformations
  std::set<PlasticSkeletonDeformation *>::iterator dt,
      dEnd(m_imp->m_deformations.end());
  for (dt = m_imp->m_deformations.begin(); dt != dEnd; ++dt)
    (*dt)->addVertex(this, v);
  return v;
}
Referenced by insertVertex().
clear()
void PlasticSkeleton::clear ()
{
  mesh_type::clear();
  m_imp->m_numbersPool.clear();
  // Notify deformations
  std::set<PlasticSkeletonDeformation *>::iterator dt,
      dEnd(m_imp->m_deformations.end());
  for (dt = m_imp->m_deformations.begin(); dt != dEnd; ++dt) (*dt)->clear(this);
}
closestEdge()
int PlasticSkeleton::closestEdge (const TPointD & pos, double * distance = 0) const
{
  // Traverse edges
  double d, minDist = (std::numeric_limits<double>::max)();
  int e = -1;
  tcg::list<edge_type>::const_iterator et, eEnd(m_edges.end());
  for (et = m_edges.begin(); et != eEnd; ++et) {
    const TPointD &vp0 = vertex(et->vertex(0)).P(),
                  &vp1 = vertex(et->vertex(1)).P();
    d                        = tcg::point_ops::segDist(vp0, vp1, pos);
    if (d < minDist) minDist = d, e = int(et.m_idx);
  }
  if (dist && e >= 0) *dist = minDist;
  return e;
}
closestVertex()
int PlasticSkeleton::closestVertex (const TPointD & pos, double * distance = 0) const
{
  // Traverse vertices
  double d2, minDist2 = (std::numeric_limits<double>::max)();
  int v = -1;
  tcg::list<vertex_type>::const_iterator vt, vEnd(m_vertices.end());
  for (vt = m_vertices.begin(); vt != vEnd; ++vt) {
    d2                          = tcg::point_ops::dist2(pos, vt->P());
    if (d2 < minDist2) minDist2 = d2, v = int(vt.m_idx);
  }
  if (dist && v >= 0) *dist = sqrt(minDist2);
  return v;
}
insertVertex() [1/2]
int PlasticSkeleton::insertVertex (const PlasticSkeletonVertex & vx, int e)
Inserts a vertex splitting an existing edge
Note
Inserted Vertex will connect to parent first
{
  const edge_type &ed = edge(e);
  return insertVertex(vx, ed.vertex(0), std::vector<int>(1, ed.vertex(1)));
}
References insertVertex().
Referenced by insertVertex().
insertVertex() [2/2]
int PlasticSkeleton::insertVertex (const PlasticSkeletonVertex & vx, int parent, const std::vector< int > & children)
it is useful as inverse of vertex removal.
Parameters
parent Generalization of vertex addition/insertion,
{
  assert(parent >= 0);
  if (children.empty()) return addVertex(vx, parent);
  // Add the vertex
  int v = mesh_type::addVertex(vx);
  // Retrieve a vertex index
  PlasticSkeletonVertex &vx_ = vertex(v);
  vx_.m_number = m_imp->m_numbersPool.acquire();
  // Assign a name to the vertex in case none was given
  QString name(vx.name());
  if (name.isEmpty())
    name = "Vertex " + QString::number(vx_.m_number).rightJustified(3, '_');
  // Ensure the name is unique
  while (!setVertexName(v, name)) name += "_";
  // Link it to the parent
  {
    PlasticSkeletonVertex &vx_ = vertex(v);
    mesh_type::addEdge(
        edge_type(parent, v));  // Observe that parent is always v0
    vx_.m_parent = parent;
    assert(parent != v);
  }
  // Link it to children
  int c, cCount = int(children.size());
  for (c = 0; c != cCount; ++c) {
    int vChild                     = children[c];
    PlasticSkeletonVertex &vxChild = vertex(vChild);
    assert(vxChild.parent() == parent);
    // Remove the edge and substitute it with a new one
    int e = edgeInciding(parent, vChild);
    mesh_type::removeEdge(e);
    mesh_type::addEdge(edge_type(v, vChild));
    vxChild.m_parent = v;
    assert(v != vChild);
  }
  // Notify deformations
  std::set<PlasticSkeletonDeformation *>::iterator dt,
      dEnd(m_imp->m_deformations.end());
  for (dt = m_imp->m_deformations.begin(); dt != dEnd; ++dt)
    (*dt)->insertVertex(this, v);
  return v;
}
References addVertex(), tcg::Mesh< PlasticSkeletonVertex, tcg::Edge, tcg::FaceN< 3 > >::edgeInciding(), and tcg::Mesh< PlasticSkeletonVertex, tcg::Edge, tcg::FaceN< 3 > >::removeEdge().
loadData()
void PlasticSkeleton::loadData (TIStream & is) override virtual
 This is a pure virtual function and must be overridden with a method
that implements the object loading from a stream (i.e take the object's features from a formatted data stream). For example the TStageObject class use his implementation to take the values of the parameters that characterizes a stage object as name, coordinates, etc... from a file. is is an input file stream
Implements TPersist.
{
  // Ensure the skeleton is clean
  clear();
  // Load vertices
  std::string str;
  int i, size;
  while (is.openChild(str)) {
    if (str == "V") {
      is >> size;
      std::vector<int> acquiredVertexNumbers;
      acquiredVertexNumbers.reserve(size);
      m_vertices.reserve(size);
      for (i = 0; i < size; ++i) {
        if (is.openChild(str) && (str == "Vertex")) {
          vertex_type vx;
          is >> vx;
          int idx = mesh_type::addVertex(vx);
          if (vx.m_number < 0) vertex(idx).m_number = vx.m_number = idx + 1;
          acquiredVertexNumbers.push_back(vx.m_number);
          is.matchEndTag();
        } else
          assert(false), is.skipCurrentTag();
      }
      m_imp->m_numbersPool = tcg::indices_pool<int>(
          acquiredVertexNumbers.begin(), acquiredVertexNumbers.end());
      is.matchEndTag();
    } else if (str == "E") {
      is >> size;
      m_edges.reserve(size);
      int v0, v1;
      for (i = 0; i < size; ++i) {
        is >> v0 >> v1;
        addEdge(edge_type(v0, v1));
        vertex(v1).m_parent = v0;
      }
      is.matchEndTag();
    } else
      assert(false), is.skipCurrentTag();
  }
}
References TIStream::matchEndTag(), TIStream::openChild(), and TIStream::skipCurrentTag().
moveVertex()
void PlasticSkeleton::moveVertex (int v, const TPointD & pos)
Moves a vertex to the specified position, informing
{
  mesh_type::vertex(v).P() = pos;  // Apply new position
}
operator=() [1/2]
PlasticSkeleton & PlasticSkeleton::operator= (const PlasticSkeleton & other)
{
  assert(m_imp->m_deformations.empty());
  mesh_type::operator=(other);
  *m_imp             = *other.m_imp;
  return *this;
}
operator=() [2/2]
PlasticSkeleton & PlasticSkeleton::operator= (PlasticSkeleton && other)
{
  assert(m_imp->m_deformations.empty());
  mesh_type::operator=(std::forward<mesh_type>(other));
  *m_imp             = std::move(*other.m_imp);
  return *this;
}
parentVertex()
int PlasticSkeleton::parentVertex (int v) inline
{ return vertex(v).m_parent; }
removeVertex()
void PlasticSkeleton::removeVertex (int v)
Removes a vertex, reattaching all its children to parent.
{
  int vNumber;
  {
    // Reparent all of v's children to its parent's children, first. This is
    // needed
    // to ensure that deformations update vertex deformations correctly.
    PlasticSkeletonVertex vx(
        vertex(v));  // Note the COPY - not referencing. It's best since
    // we'll be iterating and erasing vx's edges at the same time
    int parent = vx.m_parent;
    if (parent < 0) {
      // Root case - clear the whole skeleton
      clear();  // Should ensure that the next inserted vertex has index 0
      return;
    }
    // Add edges from parent to vx's children
    vertex_type::edges_iterator et, eEnd = vx.edgesEnd();
    for (et = vx.edgesBegin(); et != eEnd; ++et) {
      int vChild = edge(*et).vertex(1);
      if (vChild == v) continue;
      mesh_type::removeEdge(*et);
      mesh_type::addEdge(edge_type(parent, vChild));
      vertex(vChild).m_parent = parent;
      assert(vChild != parent);
    }
    vNumber = vx.m_number;
  }
  // Notify deformations BEFORE removing the vertex, so the vertex deformations
  // are still accessible.
  std::set<PlasticSkeletonDeformation *>::iterator dt,
      dEnd(m_imp->m_deformations.end());
  for (dt = m_imp->m_deformations.begin(); dt != dEnd; ++dt)
    (*dt)->deleteVertex(this, v);
  // Then, erase v. This already ensures that edges connected with v are
  // destroyed.
  mesh_type::removeVertex(v);
  m_imp->m_numbersPool.release(vNumber);
}
References tcg::Mesh< PlasticSkeletonVertex, tcg::Edge, tcg::FaceN< 3 > >::removeEdge(), and tcg::Mesh< PlasticSkeletonVertex, tcg::Edge, tcg::FaceN< 3 > >::removeVertex().
saveData()
void PlasticSkeleton::saveData (TOStream & os) override virtual
 This is a pure virtual function and must be overridden with a method
that implements the object saving to a data stream (i.e put the object's features on a formatted data stream). For example the TStageObject class use his implementation to save the values of the parameters that characterizes a stage object as name, coordinates, etc... on a file os is an output file stream.
Implements TPersist.
{
  // NOTE: Primitives saved by INDEX iteration is NOT COINCIDENTAL - since
  // the lists' internal linking could have been altered to mismatch the
  // natural indexing referred to by primitives' data.
  if (m_vertices.size() != m_vertices.nodesCount() ||
      m_edges.size() != m_edges.nodesCount()) {
    // Ensure that there are no holes in the representation
    PlasticSkeleton skel(*this);
    skel.squeeze();
    skel.saveData(os);
    return;
  }
  // Save vertices
  os.openChild("V");
  {
    int vCount = int(m_vertices.size());
    os << vCount;
    for (int v = 0; v != vCount; ++v) os.child("Vertex") << m_vertices[v];
  }
  os.closeChild();
  // Save edges
  os.openChild("E");
  {
    int eCount = int(m_edges.size());
    os << eCount;
    for (int e = 0; e != eCount; ++e) {
      PlasticSkeleton::edge_type &ed = m_edges[e];
      os << ed.vertex(0) << ed.vertex(1);
    }
  }
  os.closeChild();
}
References TOStream::child(), TOStream::closeChild(), TOStream::openChild(), and saveData().
Referenced by saveData().
setVertexName()
bool PlasticSkeleton::setVertexName (int v, const QString & name)
{
  assert(!newName.isEmpty());
  if (m_vertices[v].m_name == newName) return true;
  // Traverse the vertices list - if the same name already exists, return false
  tcg::list<vertex_type>::iterator vt, vEnd(m_vertices.end());
  for (vt = m_vertices.begin(); vt != vEnd; ++vt)
    if (vt.m_idx != v &&
        vt->m_name == newName)  // v should be skipped in the check
      return false;
  // Notify deformations before changing the name
  std::set<PlasticSkeletonDeformation *>::iterator dt,
      dEnd(m_imp->m_deformations.end());
  for (dt = m_imp->m_deformations.begin(); dt != dEnd; ++dt)
    (*dt)->vertexNameChange(this, v, newName);
  m_vertices[v].m_name = newName;
  return true;
}
squeeze()
void PlasticSkeleton::squeeze ()
{
  // Squeeze associated deformations first
  int v, e;
  // Update indices
  tcg::list<vertex_type>::iterator vt, vEnd(m_vertices.end());
  for (v = 0, vt = m_vertices.begin(); vt != vEnd; ++vt, ++v) vt->setIndex(v);
  tcg::list<edge_type>::iterator et, eEnd(m_edges.end());
  for (e = 0, et = m_edges.begin(); et != eEnd; ++et, ++e) et->setIndex(e);
  // Update stored indices
  for (et = m_edges.begin(); et != eEnd; ++et) {
    edge_type &ed = *et;
    ed.setVertex(0, vertex(ed.vertex(0)).getIndex());
    ed.setVertex(1, vertex(ed.vertex(1)).getIndex());
  }
  for (vt = m_vertices.begin(); vt != vEnd; ++vt) {
    vertex_type &vx = *vt;
    if (vt->m_parent >= 0) vt->m_parent = vertex(vt->m_parent).getIndex();
    vertex_type::edges_iterator vet, veEnd(vx.edgesEnd());
    for (vet = vx.edgesBegin(); vet != veEnd; ++vet)
      *vet = edge(*vet).getIndex();
  }
  // Finally, rebuild the actual containers
  if (!m_edges.empty()) {
    tcg::list<edge_type> temp(m_edges.begin(), m_edges.end());
    std::swap(m_edges, temp);
  }
  if (!m_vertices.empty()) {
    tcg::list<vertex_type> temp(m_vertices.begin(), m_vertices.end());
    std::swap(m_vertices, temp);
  }
}
verticesToHandles()
std::vector< PlasticHandle > PlasticSkeleton::verticesToHandles () const
{
  std::vector<PlasticHandle> v;
  for (auto const &e : m_vertices) {
    v.push_back(e);
  }
  return v;
}
Friends And Related Function Documentation
PlasticSkeletonDeformation
friend class PlasticSkeletonDeformation friend
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/ext/plasticskeleton.h
E:/opentoonz/toonz/sources/tnzext/plasticskeleton.cpp