opentoonz: TSolidColorStyle Class Reference
TSolidColorStyle Class Reference
Public Member Functions
TSolidColorStyle (const TPixel32 &color=TPixel32::Black)
TSolidColorStyle (const TSolidColorStyle &)
TColorStyle * clone () const override
Polymorphic clone of the style.
QString getDescription () const override
Return a brief description of the style.
bool hasMainColor () const override
Returns whether the style has a reference main color.
TPixel32 getMainColor () const override
Returns the style's main color, or black if none.
void setMainColor (const TPixel32 &color) override
Sets the main color, if it has one.
void drawRegion (const TColorFunction *cf, const bool antiAliasing, TRegionOutline &outline) const override
void drawStroke (const TColorFunction *cf, TStrokeOutline *outline, const TStroke *s) const override
int getTagId () const override
Returns an unique number representing the style.
Public Member Functions inherited from TOutlineStyle
TOutlineStyle (const TOutlineStyle &)
RegionOutlineModifier * getRegionOutlineModifier () const
void setRegionOutlineModifier (RegionOutlineModifier *modifier)
bool isRegionStyle () const override
Returns whether the style applies on regions.
bool isStrokeStyle () const override
Returns whether the style applies on strokes.
virtual void computeOutline (const TStroke *stroke, TStrokeOutline &outline, TOutlineUtil::OutlineParameter param) const
TStrokeProp * makeStrokeProp (const TStroke *stroke) override
TRegionProp * makeRegionProp (const TRegion *region) override
used to draw the style on the specified stroke object.
virtual void drawRegion (const TColorFunction *cf, const bool antiAliasing, TRegionOutline &outline) const =0
virtual void drawStroke (const TColorFunction *cf, TStrokeOutline *outline, const TStroke *stroke) const =0
Public Member Functions inherited from TColorStyle
TColorStyle (const TColorStyle &other)
Copies another style except its icon.
virtual TColorStyle * clone () const =0
Polymorphic clone of the style.
virtual TColorStyle & copy (const TColorStyle &other)
bool operator== (const TColorStyle &cs) const
bool operator!= (const TColorStyle &cs)
virtual TStrokeProp * makeStrokeProp (const TStroke *stroke)=0
virtual TRegionProp * makeRegionProp (const TRegion *region)=0
used to draw the style on the specified stroke object.
virtual bool isRasterStyle () const
used to draw the style on the specified region object.
virtual TRasterStyleFx * getRasterStyleFx ()
virtual bool isRegionStyle () const =0
Returns whether the style applies on regions.
virtual bool isStrokeStyle () const =0
Returns whether the style applies on strokes.
void setName (std::wstring name)
Sets the style's user-defined name.
std::wstring getName () const
Returns the style's user-defined name.
void setGlobalName (std::wstring name)
Sets the global name of the style.
std::wstring getGlobalName () const
Returns the global name of the style.
void setOriginalName (std::wstring name)
If the style is originally copied from studio palette, set this.
std::wstring getOriginalName () const
Returns the original name of the style.
void setIsEditedFlag (bool edited)
bool getIsEditedFlag () const
style is edited from the original one.
void assignNames (const TColorStyle *src)
Copies the style names from src.
unsigned int getFlags () const
Sets color attributes.
void setFlags (unsigned int flags)
Returns color attributes.
void setPickedPosition (const TPoint &pos, const int index=0)
void setPickedPosition (const PickedPosition &pos)
PickedPosition getPickedPosition () const
virtual bool hasMainColor () const
Returns whether the style has a reference main color.
virtual TPixel32 getMainColor () const
Returns the style's main color, or black if none.
virtual void setMainColor (const TPixel32 &color)
Sets the main color, if it has one.
virtual int getColorParamCount () const
Returns the number of colors (if any) of the style.
virtual TPixel32 getColorParamValue (int index) const
Returns the value of the color of index index.
virtual void setColorParamValue (int index, const TPixel32 &color)
Sets the index-th color value.
virtual TPixel32 getAverageColor () const
Returns a color representing the average of all the style's colors.
virtual int getParamCount () const
virtual ParamType getParamType (int paramIdx) const
Returns the type of the specified parameter.
virtual bool hasParamDefault (int index) const
Value of parameter can be reset to default.
virtual void setParamDefault (int index)
Reset value of parameter to default.
virtual bool isParamDefault (int index) const
Check if current value of parameter equals to default.
virtual void setParamValue (int index, bool value)
Assigns a value to the specified bool parameter.
virtual bool getParamValue (bool_tag, int index) const
Retrieves the specified bool parameter value.
virtual void setParamValue (int index, int value)
Assigns a value to the specified int parameter.
virtual int getParamValue (int_tag, int index) const
Retrieves the specified int parameter value.
virtual void getParamRange (int index, int &min, int &max) const
Retrieves the specified int parameter range.
virtual void getParamRange (int pIndex, QStringList &stringItems) const
virtual void setParamValue (int index, double value)
extension value in text form.
virtual double getParamValue (double_tag, int index) const
Retrieves the specified double parameter value.
virtual void getParamRange (int index, double &min, double &max) const
Retrieves the specified double parameter range.
virtual void setParamValue (int index, const TFilePath &fp)
Assigns a value to the specified TFilePath parameter.
virtual TFilePath getParamValue (TFilePath_tag, int index) const
Retrieves the specified TFilePath parameter value.
void assignBlend (const TColorStyle &a, const TColorStyle &b, double t)
virtual QString getDescription () const =0
Return a brief description of the style.
virtual QString getParamNames (int index) const
Return the string that identifies the index-th parameter.
virtual int getTagId () const =0
Returns an unique number representing the style.
virtual void getObsoleteTagIds (std::vector< int > &) const
void save (TOutputStreamInterface &) const
void invalidateIcon ()
Sets a flag that defines the style's icon validity.
virtual const TRaster32P & getIcon (const TDimension &d)
Returns an image representing the style.
bool isEnabled () const
Returns whether the style can be used.
void enable (bool on)
Sets the style's enabled status.
int getVersionNumber () const
Returns the version number of the style.
Public Member Functions inherited from TSmartObject
TSmartObject (ClassCode classCode)
void addRef ()
void release ()
TINT32 getRefCount () const
Protected Member Functions
void makeIcon (const TDimension &d) override
void loadData (TInputStreamInterface &) override
void saveData (TOutputStreamInterface &) const override
Protected Member Functions inherited from TOutlineStyle
TOutlineStyle & operator= (const TOutlineStyle &)
Protected Member Functions inherited from TColorStyle
virtual void makeIcon (const TDimension &d)
virtual void loadData (TInputStreamInterface &)=0
virtual void saveData (TOutputStreamInterface &) const =0
virtual void loadData (int, TInputStreamInterface &)
void updateVersionNumber ()
TColorStyle & operator= (const TColorStyle &other)
Copies another style except its icon.
Additional Inherited Members
Public Types inherited from TColorStyle
enum ParamType {
BOOL , INT , ENUM , DOUBLE ,
FILEPATH
}
Public Types inherited from TSmartObject
typedef short ClassCode
Static Public Member Functions inherited from TColorStyle
static TColorStyle * load (TInputStreamInterface &)
static TColorStyle * create (int tagId)
Creates a new style with identifier equal to tagId.
static void declare (TColorStyle *style)
Puts the style in the table of actual styles.
static void getAllTags (std::vector< int > &tags)
Static Public Member Functions inherited from TSmartObject
static TINT32 getInstanceCount (ClassCode code)
Static Public Attributes inherited from TColorStyle
static int m_currentFrame = 0
Protected Attributes inherited from TOutlineStyle
RegionOutlineModifier * m_regionOutlineModifier
Protected Attributes inherited from TColorStyle
TRaster32P m_icon
Icon shown on TPalette viewers.
bool m_validIcon
Icon's validity status.
Detailed Description
Constructor & Destructor Documentation
TSolidColorStyle() [1/2]
TSolidColorStyle::TSolidColorStyle (const TPixel32 & color = TPixel32::Black)
    : m_color(color), m_tessellator(new TglTessellator) {}
TSolidColorStyle() [2/2]
TSolidColorStyle::TSolidColorStyle (const TSolidColorStyle & other)
    : TOutlineStyle(other)
    , m_color(other.m_color)
    , m_tessellator(new TglTessellator) {}
~TSolidColorStyle()
TSolidColorStyle::~TSolidColorStyle ()
{ delete m_tessellator; }
Member Function Documentation
clone()
TColorStyle * TSolidColorStyle::clone () const override virtual
Polymorphic clone of the style.
Implements TColorStyle.
{
  return new TSolidColorStyle(*this);
}
drawRegion()
void TSolidColorStyle::drawRegion (const TColorFunction * cf, const bool antiAliasing, TRegionOutline & outline) const override virtual
Implements TOutlineStyle.
{
  m_tessellator->tessellate(cf, antiAliasing, boundary, m_color);
}
drawStroke()
void TSolidColorStyle::drawStroke (const TColorFunction * cf, TStrokeOutline * outline, const TStroke * s) const override virtual
Implements TOutlineStyle.
{
  struct locals {
    static inline void fillOutlinedStroke(const std::vector<TOutlinePoint> &v) {
      static const int stride = sizeof(TOutlinePoint);
      glEnableClientState(GL_VERTEX_ARRAY);
      glVertexPointer(2, GL_DOUBLE, stride, &v[0]);
      glDrawArrays(QUAD_PRIMITIVE, 0, v.size());
      glDisableClientState(GL_VERTEX_ARRAY);
    }
  };  // locals
  TPixel32 color = m_color;
  if (cf) color = (*cf)(color);
  if (color.m == 0) return;
  tglColor(color);
  const std::vector<TOutlinePoint> &v = outline->getArray();
  if (v.empty()) return;
  if (true)  // color.m != 254) // !dummyStyle)
  {
    if (color.m < 255) {
      TStencilControl *stencil = TStencilControl::instance();
      /*
// invertendo l'ordine tra disegno interno e contorno, l'antialiasing
// peggiora un po'. Piu che altro, il mangiucchiamento che faceva su alcune
macchine,
// ma solo in drawOnScreen, ora lo fa anche quando si renderizza offline
stencil->beginMask(TStencilControl::DRAW_ON_SCREEN_ONLY_ONCE);
// center line
fillOutlinedStroke(v);
// outline with antialiasing
drawAntialiasedOutline(v);
stencil->endMask();
*/
      stencil->beginMask(TStencilControl::DRAW_ON_SCREEN_ONLY_ONCE);
      locals::fillOutlinedStroke(v);
      stencil->endMask();
      stencil->enableMask(TStencilControl::SHOW_OUTSIDE);
      drawAntialiasedOutline(v, stroke);
      stencil->disableMask();
    } else {
      // outline with antialiasing
      drawAntialiasedOutline(v, stroke);
      // center line
      locals::fillOutlinedStroke(v);
    }
  } else {
    int i = 0;
    for (i = 0; i < stroke->getControlPointCount(); i++) {
      TThickPoint p = stroke->getControlPoint(i);
      if (i % 2) {
        tglColor(TPixel32(255, 0, 0));
        tglDrawCircle(p, p.thick);
      } else {
        tglColor(TPixel32(255, 200, 200));
        tglDrawDisk(p, p.thick);
        tglColor(TPixel32(0, 255, 0));
        tglDrawCircle(p, p.thick);
      }
      tglColor(TPixel32(127, 127, 127));
      tglDrawDisk(p, 0.3);
    }
    tglColor(TPixel32(127, 127, 127));
    glBegin(GL_LINE_STRIP);
    for (i = 0; i < stroke->getControlPointCount(); i++)
      tglVertex(stroke->getControlPoint(i));
    glEnd();
    tglColor(TPixel32(0, 0, 0));
    drawAntialiasedOutline(v, stroke);
  }
}
getDescription()
QString TSolidColorStyle::getDescription () const override virtual
Return a brief description of the style.
\detail For example for a stroke style we have "Constant", "Chain", "Rope", "Tulle", etc...
Implements TColorStyle.
{ return "SolidColorStyle"; }
getMainColor()
TPixel32 TSolidColorStyle::getMainColor () const inline override virtual
Returns the style's main color, or black if none.
Reimplemented from TColorStyle.
{ return m_color; }
Referenced by TPalette::getClosestStyle(), ShadowStyle::getColorParamValue(), ShadowStyle2::getColorParamValue(), TPointShadowFillStyle::getColorParamValue(), TDottedFillStyle::getColorParamValue(), TCheckedFillStyle::getColorParamValue(), TChalkFillStyle::getColorParamValue(), TChessFillStyle::getColorParamValue(), TStripeFillStyle::getColorParamValue(), TLinGradFillStyle::getColorParamValue(), TRadGradFillStyle::getColorParamValue(), TCircleStripeFillStyle::getColorParamValue(), TMosaicFillStyle::getColorParamValue(), TPatchFillStyle::getColorParamValue(), TMatrioskaStrokeStyle::getColorParamValue(), TCleanupStyle::getColorParamValue(), and TCleanupStyle::setMainColor().
getTagId()
int TSolidColorStyle::getTagId () const override virtual
Returns an unique number representing the style.
Implements TColorStyle.
{ return 3; }
hasMainColor()
bool TSolidColorStyle::hasMainColor () const inline override virtual
Returns whether the style has a reference main color.
\detail Raster or vector pattern image styles, for example, return false.
Reimplemented from TColorStyle.
{ return true; }
loadData()
void TSolidColorStyle::loadData (TInputStreamInterface & is) override protected virtual
Implements TColorStyle.
{
  TPixel32 color;
  is >> color;
  m_color = color;
}
makeIcon()
void TSolidColorStyle::makeIcon (const TDimension & d) override protected virtual
Reimplemented from TColorStyle.
{
  /*-- TSolidColorStyle, TColorCleanupStyle, TBlackCleanupStyle --*/
  if (getTagId() != 3 && getTagId() != 2001 &&
      getTagId() !=
          2002)  // e' un'istanza di una classe derivata da TSolidColorStyle
  {
    TColorStyle::makeIcon(size);
  } else {
    if (!m_icon || m_icon->getSize() != size) {
      TRaster32P ras(size);
      m_icon = ras;
    }
    TPixel32 col = m_color;
    if (col.m == 255)
      m_icon->fill(col);
    else {
      TRaster32P fg(size);
      fg->fill(premultiply(col));
      TRop::checkBoard(m_icon, TPixel32::Black, TPixel32::White,
                       TDimensionD(6, 6), TPointD());
      TRop::over(m_icon, fg);
    }
  }
}
saveData()
void TSolidColorStyle::saveData (TOutputStreamInterface & os) const override protected virtual
Implements TColorStyle.
{
  os << m_color;
}
setMainColor()
void TSolidColorStyle::setMainColor (const TPixel32 & color) inline override virtual
Sets the main color, if it has one.
Reimplemented from TColorStyle.
{ m_color = color; }
Referenced by ShadowStyle::setColorParamValue(), ShadowStyle2::setColorParamValue(), TPointShadowFillStyle::setColorParamValue(), TDottedFillStyle::setColorParamValue(), TCheckedFillStyle::setColorParamValue(), TChalkFillStyle::setColorParamValue(), TChessFillStyle::setColorParamValue(), TStripeFillStyle::setColorParamValue(), TLinGradFillStyle::setColorParamValue(), TRadGradFillStyle::setColorParamValue(), TCircleStripeFillStyle::setColorParamValue(), TMosaicFillStyle::setColorParamValue(), TPatchFillStyle::setColorParamValue(), TMatrioskaStrokeStyle::setColorParamValue(), and TCleanupStyle::setMainColor().
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/tsimplecolorstyles.h
E:/opentoonz/toonz/sources/common/tvrender/tsimplecolorstyles.cpp