opentoonz: FrameNumberLineEdit Class Reference
FrameNumberLineEdit Class Reference
Public Member Functions
FrameNumberLineEdit (QWidget *parent=0, TFrameId fId=TFrameId(1), bool acceptLetter=true)
void setValue (TFrameId fId)
TFrameId getValue ()
void onProjectSwitched () override
void onProjectChanged () override
FrameNumberLineEdit (QWidget *parent=0, TFrameId fId=TFrameId(1), bool acceptLetter=true)
void setValue (TFrameId fId)
TFrameId getValue ()
void onProjectSwitched () override
void onProjectChanged () override
Public Member Functions inherited from DVGui::LineEdit
LineEdit (QWidget *parent=0, bool forbiddenSpecialChars=false)
LineEdit (const QString &contents, QWidget *parent=0, bool forbiddenSpecialChars=false)
bool isReturnPressed () const
bool getMouseDragEditing ()
void setMouseDragEditing (bool status)
virtual void onProjectSwitched ()=0
virtual void onProjectChanged ()=0
Protected Member Functions
void focusInEvent (QFocusEvent *) override
void focusOutEvent (QFocusEvent *) override
void showEvent (QShowEvent *event) override
void focusInEvent (QFocusEvent *) override
void focusOutEvent (QFocusEvent *) override
void showEvent (QShowEvent *event) override
Protected Member Functions inherited from DVGui::LineEdit
void focusInEvent (QFocusEvent *event) override
void keyPressEvent (QKeyEvent *event) override
void mouseMoveEvent (QMouseEvent *) override
Additional Inherited Members
Signals inherited from DVGui::LineEdit
void focusIn ()
void returnPressedNow ()
void mouseMoved (QMouseEvent *)
Detailed Description
Constructor & Destructor Documentation
FrameNumberLineEdit()
FrameNumberLineEdit::FrameNumberLineEdit (QWidget * parent = 0, TFrameId fId = TFrameId(1), bool acceptLetter = true)
    : LineEdit(parent) {
  if (acceptLetter) {
    QString regExpStr   = QString("^%1$").arg(TFilePath::fidRegExpStr());
    m_regexpValidator   = new QRegExpValidator(QRegExp(regExpStr), this);
    TProjectManager* pm = TProjectManager::instance();
    pm->addListener(this);
  } else
    m_regexpValidator = new QRegExpValidator(QRegExp("^\\d{1,4}$"), this);
  m_regexpValidator_alt =
      new QRegExpValidator(QRegExp("^\\d{1,3}[A-Ia-i]?$"), this);
  updateValidator();
  updateSize();
  setValue(fId);
}
~FrameNumberLineEdit() [1/2]
FrameNumberLineEdit::~FrameNumberLineEdit () inline
{}
~FrameNumberLineEdit() [2/2]
FrameNumberLineEdit::~FrameNumberLineEdit () inline
{}
Member Function Documentation
focusInEvent() [1/2]
void FrameNumberLineEdit::focusInEvent (QFocusEvent * e) override protected
If focus is lost and current text value is out of range emit signal editingFinished.
{
  m_textOnFocusIn = text();
}
focusInEvent() [2/2]
void FrameNumberLineEdit::focusInEvent (QFocusEvent *) override protected
If focus is lost and current text value is out of range emit signal editingFinished.
focusOutEvent()
void FrameNumberLineEdit::focusOutEvent (QFocusEvent * e) override protected
{
  // if the field is empty, then revert the last input
  if (text().isEmpty()) setText(m_textOnFocusIn);
  LineEdit::focusOutEvent(e);
}
getValue() [1/2]
TFrameId FrameNumberLineEdit::getValue ()
Return an integer with text field value.
{
  if (Preferences::instance()->isShowFrameNumberWithLettersEnabled()) {
    QString str = text();
    int f;
    // if no letters added
    if (str.at(str.size() - 1).isDigit())
      f = str.toInt() * 10;
    else {
      f = str.left(str.size() - 1).toInt() * 10 +
          letterToNum(str.at(str.size() - 1));
    }
    return TFrameId(f);
  } else {
    QString regExpStr = QString("^%1$").arg(TFilePath::fidRegExpStr());
    QRegExp rx(regExpStr);
    int pos = rx.indexIn(text());
    if (pos < 0) return TFrameId();
    if (rx.cap(2).isEmpty())
      return TFrameId(rx.cap(1).toInt());
    else
      return TFrameId(rx.cap(1).toInt(), rx.cap(2));
  }
}
Referenced by LoadLevelPopup::execute(), and LoadLevelPopup::onSubsequentFrameChanged().
getValue() [2/2]
TFrameId FrameNumberLineEdit::getValue ()
Return an integer with text field value.
onProjectChanged() [1/2]
void FrameNumberLineEdit::onProjectChanged () override virtual
Implements TProjectManager::Listener.
{ onProjectSwitched(); }
onProjectChanged() [2/2]
void FrameNumberLineEdit::onProjectChanged () override virtual
Implements TProjectManager::Listener.
onProjectSwitched() [1/2]
void FrameNumberLineEdit::onProjectSwitched () override virtual
Implements TProjectManager::Listener.
{
  QRegExpValidator* oldValidator = m_regexpValidator;
  QString regExpStr = QString("^%1$").arg(TFilePath::fidRegExpStr());
  m_regexpValidator = new QRegExpValidator(QRegExp(regExpStr), this);
  updateValidator();
  if (oldValidator) delete oldValidator;
  updateSize();
}
onProjectSwitched() [2/2]
void FrameNumberLineEdit::onProjectSwitched () override virtual
Implements TProjectManager::Listener.
setValue() [1/2]
void FrameNumberLineEdit::setValue (TFrameId fId)
Set text in field to value.
{
  QString str;
  if (Preferences::instance()->isShowFrameNumberWithLettersEnabled()) {
    if (!fId.getLetter().isEmpty()) {
      // need some warning?
    }
    str = convertToFrameWithLetter(fId.getNumber(), 3);
  } else {
    str = QString::fromStdString(fId.expand());
  }
  setText(str);
  setCursorPosition(0);
}
Referenced by LoadLevelPopup::onSubsequentFrameChanged().
setValue() [2/2]
void FrameNumberLineEdit::setValue (TFrameId fId)
Set text in field to value.
showEvent() [1/2]
void FrameNumberLineEdit::showEvent (QShowEvent * event) inline override protected
{ updateValidator(); }
showEvent() [2/2]
void FrameNumberLineEdit::showEvent (QShowEvent * event) inline override protected
{ updateValidator(); }
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/toonz/penciltestpopup.h
E:/opentoonz/toonz/sources/toonz/penciltestpopup_qt.h
E:/opentoonz/toonz/sources/toonz/penciltestpopup.cpp
E:/opentoonz/toonz/sources/toonz/penciltestpopup_qt.cpp