opentoonz: ExportScenePopup Class Reference
ExportScenePopup Class Reference final
Public Member Functions
ExportScenePopup (std::vector< TFilePath > scenes)
void setScenes (std::vector< TFilePath > scenes)
Public Member Functions inherited from DVGui::Dialog
Dialog (QWidget *parent=0, bool hasButton=false, bool hasFixedSize=true, const QString &name=QString())
void beginVLayout ()
void endVLayout ()
void beginHLayout ()
void endHLayout ()
void addWidget (QWidget *widget, bool isRight=true)
void addWidgets (QWidget *firstW, QWidget *secondW)
void addWidget (QString labelName, QWidget *widget)
void addLayout (QLayout *layout, bool isRight=true)
void addWidgetLayout (QWidget *widget, QLayout *layout)
void addLayout (QString labelName, QLayout *layout)
void addLayouts (QLayout *firstL, QLayout *secondL)
void addSpacing (int spacing)
void addSeparator (QString name=QString())
void setAlignment (Qt::Alignment alignment)
void setTopMargin (int margin)
void setTopSpacing (int spacing)
void setLabelWidth (int labelWidth)
int getLabelWidth () const
void setLayoutInsertedSpacing (int spacing)
int getLayoutInsertedSpacing ()
void setButtonBarMargin (int margin)
void setButtonBarSpacing (int spacing)
void addButtonBarWidget (QWidget *widget)
void addButtonBarWidget (QWidget *first, QWidget *second)
void addButtonBarWidget (QWidget *first, QWidget *second, QWidget *third)
void addButtonBarWidget (QWidget *first, QWidget *second, QWidget *third, QWidget *fourth)
void hideEvent (QHideEvent *event) override
void clearButtonBar ()
Protected Slots
void switchMode (int id)
void onProjectTreeViweFocusIn ()
void onProjectNameFocusIn ()
void onExport ()
Protected Member Functions
TFilePath createNewProject ()
Create new project and return new project path.
Protected Member Functions inherited from DVGui::Dialog
void resizeEvent (QResizeEvent *e) override
Additional Inherited Members
Signals inherited from DVGui::Dialog
void dialogClosed ()
Public Attributes inherited from DVGui::Dialog
QVBoxLayout * m_topLayout
QFrame * m_mainFrame
QFrame * m_buttonFrame
QHBoxLayout * m_mainHLayout
bool m_isMainHLayout
QVBoxLayout * m_leftVLayout
QVBoxLayout * m_rightVLayout
bool m_isMainVLayout
int m_layoutSpacing
int m_layoutMargin
int m_labelWidth
std::vector< QWidget * > m_buttonBarWidgets
Protected Attributes inherited from DVGui::Dialog
QHBoxLayout * m_buttonLayout
QList< QLabel * > m_labelList
Detailed Description
Constructor & Destructor Documentation
ExportScenePopup()
ExportScenePopup::ExportScenePopup (std::vector< TFilePath > scenes)
    : Dialog(TApp::instance()->getMainWindow(), true, false, "ExportScene")
    , m_scenes(scenes)
    , m_createNewProject(false) {
  setWindowTitle(tr("Export Scene"));
  bool ret = true;
  QVBoxLayout *layout = new QVBoxLayout(this);
  //  m_command = new QLabel(this);
  //  layout->addWidget(m_command);
  QButtonGroup *group = new QButtonGroup(this);
  group->setExclusive(true);
  // Choose Project
  QWidget *chooseProjectWidget     = new QWidget(this);
  QVBoxLayout *chooseProjectLayout = new QVBoxLayout(chooseProjectWidget);
  m_chooseProjectButton =
      new QRadioButton(tr("Choose Existing Project"), chooseProjectWidget);
  group->addButton(m_chooseProjectButton, 0);
  m_chooseProjectButton->setChecked(true);
  chooseProjectLayout->addWidget(m_chooseProjectButton);
  m_projectTreeView = new ExportSceneTreeView(chooseProjectWidget);
  m_projectTreeView->setMinimumWidth(400);
  ret = ret && connect(m_projectTreeView, SIGNAL(focusIn()), this,
                       SLOT(onProjectTreeViweFocusIn()));
  chooseProjectLayout->addWidget(m_projectTreeView);
  chooseProjectWidget->setLayout(chooseProjectLayout);
  layout->addWidget(chooseProjectWidget, 5);
  // New Project
  QWidget *newProjectWidget     = new QWidget(this);
  QGridLayout *newProjectLayout = new QGridLayout(newProjectWidget);
  m_newProjectButton =
      new QRadioButton(tr("New Project"), newProjectWidget);
  group->addButton(m_newProjectButton, 1);
  newProjectLayout->addWidget(m_newProjectButton, 0, 0, 1, 2, Qt::AlignLeft);
  m_newProjectNameLabel = new QLabel(tr("Name:"), newProjectWidget);
  newProjectLayout->addWidget(m_newProjectNameLabel, 1, 0, 1, 1,
                              Qt::AlignRight);
  m_newProjectName = new LineEdit(newProjectWidget);
  ret              = ret && connect(m_newProjectName, SIGNAL(focusIn()), this,
                       SLOT(onProjectNameFocusIn()));
  newProjectLayout->setColumnStretch(1, 5);
  newProjectLayout->addWidget(m_newProjectName, 1, 1, 1, 1, Qt::AlignLeft);
    m_pathFieldLabel = new QLabel(tr("Create In:"), this);
  QString defaultProjectLocation =
      Preferences::instance()->getDefaultProjectPath();
  m_projectLocationFld =
      new DVGui::FileField(this, getStdDocumentsPath().getQString());
  ret = ret && connect(m_projectLocationFld->getField(), SIGNAL(focusIn()),
                       this, SLOT(onProjectNameFocusIn()));
  if (TSystem::doesExistFileOrLevel(TFilePath(defaultProjectLocation))) {
    m_projectLocationFld->setPath(defaultProjectLocation);
  }
  newProjectLayout->addWidget(m_pathFieldLabel, 2, 0,
                              Qt::AlignRight | Qt::AlignVCenter);
  newProjectLayout->addWidget(m_projectLocationFld, 2, 1);
  newProjectWidget->setLayout(chooseProjectLayout);
  layout->addWidget(newProjectWidget);
  ret = ret &&
        connect(group, SIGNAL(buttonClicked(int)), this, SLOT(switchMode(int)));
  addLayout(layout, false);
  QPushButton *okBtn = new QPushButton(tr("Export"), this);
  okBtn->setDefault(true);
  QPushButton *cancelBtn = new QPushButton(tr("Cancel"), this);
  connect(okBtn, SIGNAL(clicked()), this, SLOT(onExport()));
  connect(cancelBtn, SIGNAL(clicked()), this, SLOT(reject()));
  addButtonBarWidget(okBtn, cancelBtn);
  switchMode(0);
  //  updateCommandLabel();
  assert(ret);
}
Member Function Documentation
createNewProject()
TFilePath ExportScenePopup::createNewProject () protected
Create new project and return new project path.
{
  TProjectManager *pm = TProjectManager::instance();
  TFilePath projectName(m_newProjectName->text().toStdWString());
  if (projectName == TFilePath()) {
    DVGui::warning(
        tr("The project name cannot be empty or contain any of the following "
           "characters:(new line)   \\ / : * ? \"  |"));
    return TFilePath();
  }
  if (projectName.isAbsolute()) {
    // bad project name
    DVGui::warning(
        tr("The project name cannot be empty or contain any of the following "
           "characters:(new line)   \\ / : * ? \"  |"));
    return TFilePath();
  }
  if (pm->getProjectPathByName(projectName) != TFilePath()) {
    // project already exists
    DVGui::warning(tr("The project name you specified is already used."));
    return TFilePath();
  }
  TFilePath newLocation   = TFilePath(m_projectLocationFld->getPath());
  TFilePath projectFolder = newLocation + projectName;
  TFilePath projectPath   = pm->projectFolderToProjectPath(projectFolder);
  if (TSystem::doesExistFileOrLevel(projectPath)) {
    error(tr("Project '%1' already exists").arg(m_newProjectName->text()));
    return TFilePath();
  }
  TProject *project = new TProject();rToProjectPath(projectFolder);
  TProject *project       = new TProject();
  TProjectP currentProject = pm->getCurrentProject();
  assert(currentProject);
  int i;
  for (i = 0; i < (int)currentProject->getFolderCount(); i++)
    project->setFolder(currentProject->getFolderName(i),
                       currentProject->getFolder(i));
  project->save(projectPath);
  DvDirModel::instance()->refreshFolder(currentProjectRoot);
  return projectPath;
}
References TProjectManager::getCurrentProject(), TProjectManager::getProjectPathByName(), TProjectManager::instance(), TProjectManager::projectFolderToProjectPath(), and TProject::save().
onExport
void ExportScenePopup::onExport () protected slot
{
  QApplication::setOverrideCursor(Qt::WaitCursor);
  TProjectManager *pm      = TProjectManager::instance();
  TFilePath oldProjectPath = pm->getCurrentProjectPath();
  TFilePath projectPath;
  if (!m_createNewProject) {
    DvDirModelFileFolderNode *node =
        (DvDirModelFileFolderNode *)m_projectTreeView->getCurrentNode();
    if (!node || !pm->isProject(node->getPath())) {
      QApplication::restoreOverrideCursor();
      DVGui::warning(tr("The folder you selected is not a project."));
      return;
    }
    projectPath = pm->projectFolderToProjectPath(node->getPath());
    assert(projectPath != TFilePath());
  } else  // Create project
  {
    projectPath = createNewProject();
    if (projectPath == TFilePath()) {
      QApplication::restoreOverrideCursor();
      return;
    }
  }
  pm->setCurrentProjectPath(projectPath);
  std::vector<TFilePath> newScenes;
  int i;
  for (i = 0; i < m_scenes.size(); i++) {
    TFilePath newScenePath = importScene(m_scenes[i]);
    if (newScenePath == TFilePath()) continue;
    newScenes.push_back(newScenePath);
  }
  pm->setCurrentProjectPath(oldProjectPath);
  if (newScenes.empty()) {
    QApplication::restoreOverrideCursor();
    DVGui::warning(tr("There was an error exporting the scene."));
    return;
  }
  for (i = 0; i < newScenes.size(); i++) collectAssets(newScenes[i]);
  QApplication::restoreOverrideCursor();
  accept();
}
onProjectNameFocusIn
void ExportScenePopup::onProjectNameFocusIn () protected slot
{
  m_newProjectButton->setChecked(true);
  switchMode(1);
}
onProjectTreeViweFocusIn
void ExportScenePopup::onProjectTreeViweFocusIn () protected slot
{
  m_chooseProjectButton->setChecked(true);
  switchMode(0);
}
setScenes()
void ExportScenePopup::setScenes (std::vector< TFilePath > scenes) inline
{
    m_scenes = scenes;
    //    updateCommandLabel();
  }
switchMode
void ExportScenePopup::switchMode (int id) protected slot
{
  if (id == 0)  // choose Existing Project
  {
    m_createNewProject = false;
    // m_projectTreeView->setEnabled(true);
  } else  // create new project
  {
    assert(id == 1);
    m_createNewProject = true;
    // m_projectTreeView->setEnabled(false);
  }
}
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/toonz/exportscenepopup.h
E:/opentoonz/toonz/sources/toonz/exportscenepopup.cpp