opentoonz: VectorizerCore Class Reference
VectorizerCore Class Reference final
#include <tcenterlinevectorizer.h>
Signals
void partialDone (int, int)
Partial progress par1 of overall par2 is notified.
Public Member Functions
TVectorImageP vectorize (const TImageP &image, const VectorizerConfiguration &c, TPalette *palette)
bool isCanceled ()
Returns true if vectorization was aborted at user's request.
void setOverallPartials (int total)
void emitPartialDone (void)
Protected Slots
void onCancel ()
Detailed Description
Contains specific vectorization methods and deals with partial progress notifications (using Qt signals).
VectorizerCore class is the lowest layer of a vectorization process, it provides vectorization of a single input raster image by calling the vectorize method.
It can also deal notifications about its progress status, and is receptive to user cancels.
See also
VectorizerPopup, Vectorizer, VectorizerConfiguration classes.
Constructor & Destructor Documentation
VectorizerCore()
VectorizerCore::VectorizerCore () inline
: m_currPartial(0), m_isCanceled(false) {}
~VectorizerCore()
VectorizerCore::~VectorizerCore () inline
{}
Member Function Documentation
emitPartialDone()
void VectorizerCore::emitPartialDone (void)
(Internal use only) Emits partial progress signal and updates partial progresses internal count.
{
  emit partialDone(m_currPartial++, m_totalPartials);
}
References partialDone().
isCanceled()
bool VectorizerCore::isCanceled () inline
Returns true if vectorization was aborted at user's request.
{ return m_isCanceled; }
onCancel
void VectorizerCore::onCancel () inline protected slot
Receives a user cancel signal and attempts an early exit from vectorization process.
{ m_isCanceled = true; }
setOverallPartials()
void VectorizerCore::setOverallPartials (int total) inline
(Internal use only) Sets the maximum number of partial notifications.
{ m_totalPartials = total; }
vectorize()
TVectorImageP VectorizerCore::vectorize (const TImageP & image, const VectorizerConfiguration & c, TPalette * palette)
Calls the appropriate technique to convert image to vectors depending on c. Also provides post-processing operations such as regions computing and painting (using colors found in palette). Returns the TVectorImageP converted image.
{
  TVectorImageP vi;
  if (c.m_outline)
    vi = newOutlineVectorize(
        img, static_cast<const NewOutlineConfiguration &>(c), plt);
  else {
    TImageP img2(img);
    vi = centerlineVectorize(
        img2, static_cast<const CenterlineConfiguration &>(c), plt);
    if (vi) {
      for (int i = 0; i < (int)vi->getStrokeCount(); ++i) {
        TStroke *stroke = vi->getStroke(i);
        for (int j = 0; j < stroke->getControlPointCount(); ++j) {
          TThickPoint p = stroke->getControlPoint(j);
          p             = TThickPoint(c.m_affine * p, c.m_thickScale * p.thick);
          stroke->setControlPoint(j, p);
        }
      }
      applyFillColors(vi, img2, plt, c);
    }
  }
  // align boundary strokes direction
  if (c.m_alignBoundaryStrokesDirection) {
    alignBoundariesDirection(vi);
    vi->validateRegions(false);
    vi->findRegions();
    if (c.m_leaveUnpainted) removeFillColors(vi);
  }
  return vi;
}
References TStroke::getControlPoint(), TStroke::getControlPointCount(), VectorizerConfiguration::m_affine, VectorizerConfiguration::m_leaveUnpainted, VectorizerConfiguration::m_outline, VectorizerConfiguration::m_thickScale, and TStroke::setControlPoint().
Referenced by VectorizationSwatchTask::run().
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/toonz/tcenterlinevectorizer.h
E:/opentoonz/toonz/sources/toonzlib/tcenterlinevectorizer.cpp
E:/opentoonz/toonz/sources/toonzlib/tnewoutlinevectorize.cpp
E:/opentoonz/toonz/sources/toonzlib/toutlinevectorizer.cpp