opentoonz: TSoundOutputDevice Class Reference
TSoundOutputDevice Class Reference
#include <tsound.h>
Public Member Functions
TSoundTrackFormat getPreferredFormat (TUINT32 sampleRate, int channelCount, int bitPerSample)
Returns the best format supported near the given parameters.
TSoundTrackFormat getPreferredFormat (const TSoundTrackFormat &)
Returns the best format supported near the given format.
bool isFormatSupported (const TSoundTrackFormat &)
bool supportsVolume ()
double getVolume ()
Returns the current value of the volume [0,1].
bool setVolume (double value)
Set the value of volume , between [0,1].
void prepareVolume (double volume)
bool open (const TSoundTrackP &st)
Open the device according to the features of soundtrack.
void play (const TSoundTrackP &st, TINT32 s0, TINT32 s1, bool loop=false, bool scrubbing=false)
Playback of the sndtrack in the request sample range.
bool close ()
Close in the right mode the device.
void play (const TSoundTrackP &st, double t0, double t1, bool loop=false, bool scrubbing=false)
void stop ()
Stop the playback of one or more soundtracks.
bool isPlaying () const
Returns if the device is busy with a playback.
bool isLooping ()
Returns if the status of player is in looping.
void setLooping (bool loop)
Permits to change the looping status of player.
void attach (TSoundOutputDeviceListener *listener)
void detach (TSoundOutputDeviceListener *listener)
Static Public Member Functions
static bool installed ()
Detailed Description
The class TSoundOutputDevice permits the playback of a sound track
Constructor & Destructor Documentation
TSoundOutputDevice()
TSoundOutputDevice::TSoundOutputDevice ()
: m_imp(new TSoundOutputDeviceImp()) {}
~TSoundOutputDevice()
TSoundOutputDevice::~TSoundOutputDevice ()
{
  close();
  WaitForSingleObject(m_imp->m_closeDevice, INFINITE);
  CloseHandle(m_imp->m_closeDevice);
}
Member Function Documentation
attach()
void TSoundOutputDevice::attach (TSoundOutputDeviceListener * listener)
{
  m_imp->m_listeners.insert(listener);
}
close()
bool TSoundOutputDevice::close ()
Close in the right mode the device.
{ return m_imp->doCloseDevice(); }
detach()
void TSoundOutputDevice::detach (TSoundOutputDeviceListener * listener)
{
  m_imp->m_listeners.erase(listener);
}
getPreferredFormat() [1/2]
TSoundTrackFormat TSoundOutputDevice::getPreferredFormat (const TSoundTrackFormat & format)
Returns the best format supported near the given format.
{
  try {
    return getPreferredFormat(format.m_sampleRate, format.m_channelCount,
                              format.m_bitPerSample);
  } catch (TSoundDeviceException &e) {
    throw TSoundDeviceException(TSoundDeviceException::UnsupportedFormat,
                                e.getMessage());
  }
}
References getPreferredFormat().
getPreferredFormat() [2/2]
TSoundTrackFormat TSoundOutputDevice::getPreferredFormat (TUINT32 sampleRate, int channelCount, int bitPerSample)
Returns the best format supported near the given parameters.
{
  TSoundTrackFormat fmt;
  // avvvicinarsi al sample rate => dovrebbe esser OK avendo selezionato i piu'
  // vicini
  std::set<int>::iterator it = m_imp->m_supportedRate.lower_bound(sampleRate);
  if (it == m_imp->m_supportedRate.end()) {
    it = std::max_element(m_imp->m_supportedRate.begin(),
                          m_imp->m_supportedRate.end());
    if (it != m_imp->m_supportedRate.end())
      sampleRate = *(m_imp->m_supportedRate.rbegin());
    else
      throw TSoundDeviceException(TSoundDeviceException::UnsupportedFormat,
                                  "There isn't a supported format");
  } else
    sampleRate = *it;
  if (bitPerSample <= 8)
    bitPerSample = 8;
  else if ((bitPerSample > 8 && bitPerSample < 16) || bitPerSample >= 16)
    bitPerSample = 16;
  if (bitPerSample >= 16)
    fmt.m_signedSample = true;
  else
    fmt.m_signedSample = false;
  // switch mono/stereo
  if (channelCount <= 1)
    channelCount = 1;
  else
    channelCount = 2;
  fmt.m_bitPerSample = bitPerSample;
  fmt.m_channelCount = channelCount;
  fmt.m_sampleRate   = sampleRate;
  return fmt;
}
Referenced by getPreferredFormat(), and play().
getVolume()
double TSoundOutputDevice::getVolume ()
Returns the current value of the volume [0,1].
{
  return m_imp->getVolume();
}
installed()
bool TSoundOutputDevice::installed () static
Returns true if on the machine there is an audio card installed correctly
{
  int ndev = waveOutGetNumDevs();
  if (ndev <= 0) return false;
  return true;
}
Referenced by TXshSoundColumn::play().
isLooping()
bool TSoundOutputDevice::isLooping ()
Returns if the status of player is in looping.
{
  TThread::MutexLocker sl(&m_imp->m_mutex);
  return m_imp->m_looped;
}
isPlaying()
bool TSoundOutputDevice::isPlaying () const
Returns if the device is busy with a playback.
{ return m_imp->m_isPlaying; }
Referenced by TXshSoundColumn::setVolume().
open()
bool TSoundOutputDevice::open (const TSoundTrackP & st)
Open the device according to the features of soundtrack.
{
  return m_imp->doOpenDevice(st->getFormat());
}
References TSoundTrack::getFormat().
play() [1/2]
void TSoundOutputDevice::play (const TSoundTrackP & st, double t0, double t1, bool loop = false, bool scrubbing = false) inline
Playback of the sndtrack in the request time range. The loop argument permits to set the looping status of player The scrubbing permits to an application to set the mode for the interaction between sound and mouse
{
    play(st, st->secondsToSamples(t0), st->secondsToSamples(t1), loop,
         scrubbing);
  }
References TSoundTrack::secondsToSamples().
play() [2/2]
void TSoundOutputDevice::play (const TSoundTrackP & st, TINT32 s0, TINT32 s1, bool loop = false, bool scrubbing = false)
Playback of the sndtrack in the request sample range.
{
  assert((scrubbing && !loop) || !scrubbing);
  if (!st->getSampleCount()) return;
  TSoundTrackFormat format;
  TSoundTrackP subTrack;
  {
    TThread::MutexLocker sl(&m_imp->m_mutex);
    if (m_imp->m_looped)
      throw TSoundDeviceException(
          TSoundDeviceException::Busy,
          "Unable to queue another playback when the sound player is looping");
    format = st->getFormat();
    try {
      TSoundTrackFormat fmt = getPreferredFormat(format);
      if (fmt != format) {
        throw TSoundDeviceException(TSoundDeviceException::UnsupportedFormat,
                                    "Unsupported Format");
      }
    } catch (TSoundDeviceException &e) {
      throw TSoundDeviceException(TSoundDeviceException::UnsupportedFormat,
                                  e.getMessage());
    }
    assert(s1 >= s0);
    subTrack           = st->extract(s0, s1);
    m_imp->m_looped    = loop;
    m_imp->m_scrubbing = scrubbing;
  }
  if (!m_imp->m_wout) m_imp->doOpenDevice(format);
  m_imp->m_whdrQueue->put(subTrack);
}
References TSoundTrack::extract(), TSoundTrack::getFormat(), and getPreferredFormat().
Referenced by TXshSoundColumn::play().
prepareVolume()
void TSoundOutputDevice::prepareVolume (double volume)
{
    m_imp->prepareVolume(volume);
}
setLooping()
void TSoundOutputDevice::setLooping (bool loop)
Permits to change the looping status of player.
{
  TThread::MutexLocker sl(&m_imp->m_mutex);
  m_imp->m_looped = loop;
}
setVolume()
bool TSoundOutputDevice::setVolume (double value)
Set the value of volume , between [0,1].
{
  m_imp->setVolume(volume);
  return true;
}
Referenced by TXshSoundColumn::setVolume().
stop()
void TSoundOutputDevice::stop ()
Stop the playback of one or more soundtracks.
{
  if ((m_imp->m_wout) && m_imp->m_isPlaying) {
    MMRESULT ret = waveOutReset(m_imp->m_wout);
    if (ret != MMSYSERR_NOERROR) return;
    TThread::MutexLocker sl(&m_imp->m_mutex);
    m_imp->m_looped    = false;
    m_imp->m_stopped   = true;
    m_imp->m_isPlaying = false;
    m_imp->m_whdrQueue->clear();
  }
}
supportsVolume()
bool TSoundOutputDevice::supportsVolume ()
Returns true if is possible to change volume setting on current input interface
{ return true; }
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/tsound.h
E:/opentoonz/toonz/sources/common/tsound/tsound_nt.cpp
E:/opentoonz/toonz/sources/common/tsound/tsound_qt.cpp