opentoonz: DVGui::ValidatedChoiceDialog Class Reference
DVGui::ValidatedChoiceDialog Class Reference abstract
Base class for validated multi-choice user dialogs.
#include <validatedchoicedialog.h>
Public Types
enum Options { NO_OPTIONS = 0x0 , APPLY_TO_ALL }
Construction options.
enum DefaultResolution { NO_REQUIRED_RESOLUTION , CANCEL = 1 , DEFAULT_RESOLUTIONS_COUNT }
Basic resolutions supported by the dialog.
Public Member Functions
ValidatedChoiceDialog (QWidget *parent, Options opts=NO_OPTIONS)
int execute (void *obj)
virtual void reset ()
Public Member Functions inherited from DVGui::Dialog
Dialog (QWidget *parent=0, bool hasButton=false, bool hasFixedSize=true, const QString &name=QString())
void beginVLayout ()
void endVLayout ()
void beginHLayout ()
void endHLayout ()
void addWidget (QWidget *widget, bool isRight=true)
void addWidgets (QWidget *firstW, QWidget *secondW)
void addWidget (QString labelName, QWidget *widget)
void addLayout (QLayout *layout, bool isRight=true)
void addWidgetLayout (QWidget *widget, QLayout *layout)
void addLayout (QString labelName, QLayout *layout)
void addLayouts (QLayout *firstL, QLayout *secondL)
void addSpacing (int spacing)
void addSeparator (QString name=QString())
void setAlignment (Qt::Alignment alignment)
void setTopMargin (int margin)
void setTopSpacing (int spacing)
void setLabelWidth (int labelWidth)
int getLabelWidth () const
void setLayoutInsertedSpacing (int spacing)
int getLayoutInsertedSpacing ()
void setButtonBarMargin (int margin)
void setButtonBarSpacing (int spacing)
void addButtonBarWidget (QWidget *widget)
void addButtonBarWidget (QWidget *first, QWidget *second)
void addButtonBarWidget (QWidget *first, QWidget *second, QWidget *third)
void addButtonBarWidget (QWidget *first, QWidget *second, QWidget *third, QWidget *fourth)
void hideEvent (QHideEvent *event) override
void clearButtonBar ()
Protected Member Functions
virtual QString acceptResolution (void *obj, int resolution, bool applyToAll)=0
Attempts enforcement of the selected resolution.
virtual void initializeUserInteraction (const void *obj)
bool appliedToAll () const
Returns whether the "Apply To All" button has been hit.
int appliedToAllResolution () const
Protected Member Functions inherited from DVGui::Dialog
void resizeEvent (QResizeEvent *e) override
Protected Attributes
QButtonGroup * m_buttonGroup
Protected Attributes inherited from DVGui::Dialog
QHBoxLayout * m_buttonLayout
QList< QLabel * > m_labelList
Additional Inherited Members
Signals inherited from DVGui::Dialog
void dialogClosed ()
Public Attributes inherited from DVGui::Dialog
QVBoxLayout * m_topLayout
QFrame * m_mainFrame
QFrame * m_buttonFrame
QHBoxLayout * m_mainHLayout
bool m_isMainHLayout
QVBoxLayout * m_leftVLayout
QVBoxLayout * m_rightVLayout
bool m_isMainVLayout
int m_layoutSpacing
int m_layoutMargin
int m_labelWidth
std::vector< QWidget * > m_buttonBarWidgets
Detailed Description
Base class for validated multi-choice user dialogs.
Warning
For correct usage, observe the guidelines described in the ValidatedChoiceDialog() constructor.
Member Enumeration Documentation
DefaultResolution
enum DVGui::ValidatedChoiceDialog::DefaultResolution
Basic resolutions supported by the dialog.
Enumerator
NO_REQUIRED_RESOLUTION
An object supplied for validation turns out to be valid, no need for any resolution.
CANCEL
Resolution selection was canceled. Stop processing.
  { NO_REQUIRED_RESOLUTION =
        0,
    CANCEL = 1,
    DEFAULT_RESOLUTIONS_COUNT };
Options
enum DVGui::ValidatedChoiceDialog::Options
Construction options.
Enumerator
NO_OPTIONS
No special options.
APPLY_TO_ALL
Has the "Apply to All" button. An applied to all resolution persists as the default without-prompt resolution until the next call to reset().
  { NO_OPTIONS = 0x0,
    APPLY_TO_ALL =
        0x1
  };
Constructor & Destructor Documentation
ValidatedChoiceDialog()
DVGui::ValidatedChoiceDialog::ValidatedChoiceDialog (QWidget * parent, Options opts = NO_OPTIONS)
Warning
Due to compatibility with DVGui::Dialog's interface, this class reserves invocation of Dialog::beginVLayout() during class construction - however, Dialog::endVLayout() invocation is responsibility of derived classes after resolution choices have been manually added to the layout.
Users are required to respect the default resolution ids when adding buttons into m_buttonGroup. See the DefaultResolution enum for a list of all default resolutions. Constructs the dialog with no default
    : Dialog(parent, true, false) {
  setModal(true);
  m_buttonGroup = new QButtonGroup(this);
  m_buttonGroup->setExclusive(true);
  bool ret = true;
  QPushButton *okBtn = new QPushButton(QString(tr("Apply")), this);
  ret                = ret && connect(okBtn, SIGNAL(clicked()), SLOT(accept()));
  addButtonBarWidget(okBtn);
  QPushButton *okToAllBtn = new QPushButton(QString(tr("Apply to All")), this);
  ret = ret && connect(okToAllBtn, SIGNAL(clicked()), SLOT(onApplyToAll()));
  addButtonBarWidget(okToAllBtn);
  QPushButton *cancelBtn = new QPushButton(QString(tr("Cancel")), this);
  ret = ret && connect(cancelBtn, SIGNAL(clicked()), SLOT(reject()));
  addButtonBarWidget(cancelBtn);
  assert(ret);
  reset();
  // Start layout
  beginVLayout();
  m_label = new QLabel(this);
  addWidget(m_label);
  // enbVLayout() must be invoked by derived classes
}
References DVGui::Dialog::addButtonBarWidget(), DVGui::Dialog::addWidget(), DVGui::Dialog::beginVLayout(), m_buttonGroup, and reset().
Member Function Documentation
acceptResolution()
virtual QString DVGui::ValidatedChoiceDialog::acceptResolution (void * obj, int resolution, bool applyToAll) protected pure virtual
Attempts enforcement of the selected resolution.
Resolution NO_REQUIRED_RESOLUTION is always tested before other proposed resolutions.
Returns
An error message upon failure.
Parameters
obj The type-erased object to be resolved. May be modified.
resolution The button id associated to the selected resolution.
applyToAll Whether user selected the resolution for all successive prompts.
appliedToAll()
bool DVGui::ValidatedChoiceDialog::appliedToAll () const inline protected
Returns whether the "Apply To All" button has been hit.
appliedToAllResolution()
int DVGui::ValidatedChoiceDialog::appliedToAllResolution () const inline protected
Returns the resolution associated to the "Apply To All" button.
execute()
int DVGui::ValidatedChoiceDialog::execute (void * obj)
resolutions.
Parameters
parent Parent top-level widget.
Opts Construction options.
obj The object to resolve.
Returns
The accepted resolution. Prompts the dialog asking for user input, until a valid resolution for the specified object is selected or the action is canceled.
{
  struct Resol {
    int m_res;
    bool m_all;
    Resol(int res, bool all) : m_res(res), m_all(all) {}
  };
  Resol curResolution(NO_REQUIRED_RESOLUTION, false),
      newResolution(m_appliedToAll ? m_appliedToAllRes : NO_REQUIRED_RESOLUTION,
                    m_appliedToAll);
  bool initialize = true;
  // Loop until a resolution gets accepted
  do {
    QString err =
        acceptResolution(obj, curResolution.m_res, curResolution.m_all);
    if (err.isEmpty()) break;
    if (newResolution.m_res == NO_REQUIRED_RESOLUTION) {
      // No new resolution selected - prompt for user interaction
      m_label->setText(err);
      m_applyToAll = false;
      if (initialize) initializeUserInteraction(obj), initialize = false;
      if (exec() == QDialog::Rejected) {
        curResolution.m_res = CANCEL;
        break;
      }
      newResolution = Resol(m_buttonGroup->checkedId(), m_applyToAll);
      assert(newResolution.m_res >= DEFAULT_RESOLUTIONS_COUNT);
    }
    // Substitute resolution and retry
    curResolution = newResolution,
    newResolution = Resol(NO_REQUIRED_RESOLUTION, false);
  } while (true);
  return curResolution.m_res;
}
initializeUserInteraction()
virtual void DVGui::ValidatedChoiceDialog::initializeUserInteraction (const void * obj) inline protected virtual
This function can be used to initialize the widget as soon as user interaction is required. Use showEvent() in case the initialization is needed at every interaction time. Invoked at max once per execute(), immediately before the dialog is shown.
reset()
void DVGui::ValidatedChoiceDialog::reset () virtual
Clears accepted resolutions - should be used together with option APPLY_TO_ALL.
Reimplemented in OverwriteDialog, and CleanupPopup::OverwriteDialog.
{
  m_appliedToAllRes = NO_REQUIRED_RESOLUTION;
  m_appliedToAll    = false;
}
Referenced by ValidatedChoiceDialog().
Member Data Documentation
m_buttonGroup
QButtonGroup* DVGui::ValidatedChoiceDialog::m_buttonGroup protected
Group of abstract buttons representing all available resolutions.
Referenced by ValidatedChoiceDialog().
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/toonzqt/validatedchoicedialog.h
E:/opentoonz/toonz/sources/toonzqt/validatedchoicedialog.cpp