opentoonz: TRandom Class Reference
TRandom Class Reference
#include <trandom.h>
Public Member Functions
TRandom (UINT seed=0)
void reset ()
void setSeed (UINT seed)
UINT getUInt (UINT end=c_maxuint)
int getInt (int begin, int end)
float getFloat ()
float getFloat (float end)
float getFloat (float begin, float end)
bool getBool ()
double getDouble ()
Detailed Description
Generates a pseudorandom sequence
Constructor & Destructor Documentation
TRandom()
TRandom::TRandom (UINT seed = 0)
                           : seed(_seed) {
  if (RandomFloatType == TRandom::RANDOM_FLOAT_TYPE_NONE) setRandomFloatType();
  reset();
}
~TRandom()
TRandom::~TRandom ()
{}
Member Function Documentation
getBool()
bool TRandom::getBool ()
returns a random bool value
                      {
  UINT u = getNextUINT();
  return u & 1;
}
getDouble()
double TRandom::getDouble ()
returns a double number in the range [0, 1[
{
  return getFloat();
#ifdef DA_RIVEDERE_O_PROPRIO_IMPLEMENTARE
  UINT low     = getNextUINT();
  UINT high    = getNextUINT();
  double value = 0;
  void *ptr  = &value;
  UINT *retL = (UINT *)ptr;
  UINT *retH = retL + 1;
/*
// questa parte e' stata commentata perche' su tutte le piattaforme il tipo
//di float e' RANDOM_FLOAT_TYPE_1ma su irix c'e' bisogno di eseguire le
//istruzioni sotto RANDOM_FLOAT_TYPE_2
switch (RandomFloatType)
  {
  case RANDOM_FLOAT_TYPE_1:
                             *retH = high;
                             *retH &= 0x00efffff;
                             *retH |= 0x3f000000;
                             *retL = low ;
// vecchi commenti
//                             *retH = high;
//                             *retL = (low >> 5) & 0x007fffff | 0x3ff00000;
                             return value;
                             break;
   case RANDOM_FLOAT_TYPE_2: *retH = low;
                             *retL = (high >> 5) & 0x007fffff | 0x3ff00000;
                             break;
                             return value-1.0;
  default: assert (0);
  }
return -1;
*/
#ifndef __sgi
  *retH = high;
  *retH &= 0x007fffff;
  *retH |= 0x3ff00000;
  *retL = low;
  return value - 1.0;
#else
  *retH = low;
  *retL = (high >> 5) & 0x007fffff | 0x3ff00000;
  return value - 1.0;
#endif
#endif
}
References getFloat().
getFloat() [1/3]
float TRandom::getFloat ()
returns a float number in the range [0, 1[
{
  UINT u = getNextUINT();
  switch (RandomFloatType) {
  case RANDOM_FLOAT_TYPE_1:
    u = ((u >> 5) & 0x007fffff) | 0x3f800000;
    break;
  case RANDOM_FLOAT_TYPE_2:
    u = (u & 0xffff7f00) | 0x0000803f;
    break;
  default:
    assert(0);
    u = 0;
    break;
  }
  return (*(float *)&u) - 1.0F;
}
Referenced by getDouble(), and getFloat().
getFloat() [2/3]
float TRandom::getFloat (float begin, float end)
returns a float number in the range [begin, end[
{
  assert(end >= begin);
  return (getFloat() * (end - begin)) + begin;
}
References getFloat().
getFloat() [3/3]
float TRandom::getFloat (float end)
returns a float number in the range [0, end[
{
  return getFloat() * end;
}
References getFloat().
getInt()
int TRandom::getInt (int begin, int end)
returns an integer number in the range [begin, end[
{
  assert(end >= begin);
  int limit = end - begin;
  if (limit == 0)  // end == begin
    return begin;
  UINT u = getNextUINT();
  return u % limit + begin;
}
getUInt()
UINT TRandom::getUInt (UINT end = c_maxuint)
returns an unsigned integer number in the range [0, end[
{
  if (end == 0) return 0;
  UINT u = getNextUINT();
  if (end == c_maxuint) return u;
  return u % end;
}
reset()
void TRandom::reset ()
resets the pseudorandom engine to the first number of the sequence
                    {
  UINT uj, uk;
  int i, ii, k;
  assert(sizeof(UINT) == 32 / 8);
  uj      = 161803398 - seed;
  ran[55] = uj;
  uk      = 1;
  for (i = 1; i <= 54; i++) {
    ii      = (21 * i) % 55;
    ran[ii] = uk;
    uk      = uj - uk;
    uj      = ran[ii];
  }
  for (k = 1; k <= 4; k++)
    for (i = 1; i <= 55; i++) ran[i] -= ran[1 + (i + 30) % 55];
  idx1     = 55;
  idx2     = 31;
}
Referenced by setSeed().
setSeed()
void TRandom::setSeed (UINT seed)
set a new seed for the pseudorandom engine and reset the sequence
{
  seed = s;
  reset();
}
References reset().
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/trandom.h
E:/opentoonz/toonz/sources/common/tcore/trandom.cpp