opentoonz: PaletteViewerGUI::PaletteTabBar Class Reference
PaletteViewerGUI::PaletteTabBar Class Reference final
The PaletteTabBar class provides a bar with tab to show and manage palette page.
Public Slots
void updateTabName ()
Signals
void tabTextChanged (int index)
void movePage (int srcIndex, int dstIndex)
Public Member Functions
PaletteTabBar (QWidget *parent, bool hasPageCommand)
void setPageViewer (PageViewer *pageViewer)
Protected Member Functions
void mousePressEvent (QMouseEvent *event) override
void mouseMoveEvent (QMouseEvent *event) override
void mouseDoubleClickEvent (QMouseEvent *event) override
void dragEnterEvent (QDragEnterEvent *event) override
void dragMoveEvent (QDragMoveEvent *event) override
void dropEvent (QDropEvent *event) override
Detailed Description
The PaletteTabBar class provides a bar with tab to show and manage palette page.
Inherits QTabBar. This object allows to move a tab with mouseMoveEvent, rename a tab in doubleClickevent and create a new tab in drag and drop.
Constructor & Destructor Documentation
PaletteTabBar()
PaletteTabBar::PaletteTabBar (QWidget * parent, bool hasPageCommand)
    : QTabBar(parent)
    , m_renameTextField(new LineEdit(this))
    , m_renameTabIndex(-1)
    , m_pageViewer(0)
    , m_hasPageCommand(hasPageCommand) {
  setObjectName("PaletteTabBar");
  setDrawBase(false);
  m_renameTextField->hide();
  connect(m_renameTextField, SIGNAL(editingFinished()), this,
          SLOT(updateTabName()));
  if (m_hasPageCommand) setAcceptDrops(true);
}
Member Function Documentation
dragEnterEvent()
void PaletteTabBar::dragEnterEvent (QDragEnterEvent * event) override protected
If event data is a paletteData accept drag event; otherwise return.
{
  if (!m_hasPageCommand) return;
  const PaletteData *paletteData =
      dynamic_cast<const PaletteData *>(event->mimeData());
  if (!paletteData) return;
  if ((m_pageViewer->getViewType() == CLEANUP_PALETTE &&
       !paletteData->getPalette()->isCleanupPalette()) ||
      (m_pageViewer->getViewType() == LEVEL_PALETTE &&
       paletteData->getPalette()->isCleanupPalette())) {
    event->ignore();
    return;
  }
  event->acceptProposedAction();
}
References PaletteViewerGUI::CLEANUP_PALETTE, TPalette::isCleanupPalette(), and PaletteViewerGUI::LEVEL_PALETTE.
dragMoveEvent()
void PaletteTabBar::dragMoveEvent (QDragMoveEvent * event) override protected
If tab in event position exist set it as current, otherwise create a new tab recalling PageViewer::createDropPage().
{
  if (!m_hasPageCommand) return;
  const PaletteData *paletteData =
      dynamic_cast<const PaletteData *>(event->mimeData());
  if (!paletteData) return;
  if (paletteData->getPalette() == m_pageViewer->getPage()->getPalette() &&
      paletteData->hasOnlyPalette())
    return;
  int tabIndex = tabAt(event->pos());
  if (0 <= tabIndex && tabIndex < count())
    setCurrentIndex(tabIndex);
  else
    m_pageViewer->createDropPage();
  event->acceptProposedAction();
}
References PaletteViewerGUI::PageViewer::createDropPage(), PaletteViewerGUI::PageViewer::getPage(), and TPalette::Page::getPalette().
dropEvent()
void PaletteTabBar::dropEvent (QDropEvent * event) override protected
Recall PageViewer::drop().
{
  if (!m_hasPageCommand) return;
  if (!dynamic_cast<const PaletteData *>(event->mimeData())) return;
  m_pageViewer->drop(-1, event->mimeData());
  event->acceptProposedAction();
}
References PaletteViewerGUI::PageViewer::drop().
mouseDoubleClickEvent()
void PaletteTabBar::mouseDoubleClickEvent (QMouseEvent * event) override protected
Set a text field with focus in event position to edit tab name.
{
  if (!m_hasPageCommand) return;
  if (m_pageViewer->getPage()->getPalette()->isLocked()) return;
  int index = tabAt(event->pos());
  if (index < 0) return;
  m_renameTabIndex = index;
  LineEdit *fld    = m_renameTextField;
  fld->setText(tabText(index));
  fld->setGeometry(tabRect(index));
  fld->setAlignment(Qt::AlignCenter);
  fld->show();
  fld->selectAll();
  fld->setFocus(Qt::OtherFocusReason);
}
References PaletteViewerGUI::PageViewer::getPage(), TPalette::Page::getPalette(), and TPalette::isLocked().
mouseMoveEvent()
void PaletteTabBar::mouseMoveEvent (QMouseEvent * event) override protected
If left button is pressed and a tab is selected emit signal movePage. In any case recall QTabBar::mousePressEvent().
{
  if (event->buttons() == Qt::LeftButton &&
      event->modifiers() == Qt::ControlModifier &&
      !m_pageViewer->getPage()->getPalette()->isLocked()) {
    int srcIndex = currentIndex();
    int dstIndex = tabAt(event->pos());
    if (dstIndex >= 0 && dstIndex < count() && dstIndex != srcIndex) {
      QRect rect = tabRect(srcIndex);
      int x      = event->pos().x();
      if (x < rect.left() || x > rect.right()) {
        emit movePage(srcIndex, dstIndex);
      }
    }
  }
  QTabBar::mouseMoveEvent(event);
}
References PaletteViewerGUI::PageViewer::getPage(), TPalette::Page::getPalette(), TPalette::isLocked(), and movePage().
mousePressEvent()
void PaletteTabBar::mousePressEvent (QMouseEvent * event) override protected
Hide rename text field and recall QTabBar::mousePressEvent().
{
  m_renameTextField->hide();
  QTabBar::mousePressEvent(event);
  m_pageViewer->getSelection()->select(currentIndex());
  m_pageViewer->getSelection()->makeCurrent();
}
movePage
void PaletteTabBar::movePage (int srcIndex, int dstIndex) signal
This signal is emitted to notify tab position change.
Referenced by mouseMoveEvent().
setPageViewer()
void PaletteTabBar::setPageViewer (PageViewer * pageViewer) inline
Set current tab bar page to pageViewer.
{ m_pageViewer = pageViewer; }
tabTextChanged
void PaletteTabBar::tabTextChanged (int index) signal
This signal is emitted when tab associated text change.
Referenced by updateTabName().
updateTabName
void PaletteTabBar::updateTabName () slot
If current rename tab index is a valid index, set tab text to rename text field text; hide the rename text field and emit tabTextChanged() signal.
{
  int index = m_renameTabIndex;
  if (index < 0) return;
  m_renameTabIndex = -1;
  if (m_renameTextField->text() != "")
    setTabText(index, m_renameTextField->text());
  m_renameTextField->hide();
  emit tabTextChanged(index);
}
References tabTextChanged().
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/toonzqt/paletteviewergui.h
E:/opentoonz/toonz/sources/toonzqt/paletteviewergui.cpp