opentoonz: TXshSoundTextLevel Class Reference
TXshSoundTextLevel Class Reference final
The TXshSoundTextLevel.
#include <txshsoundtextlevel.h>
Public Member Functions
TXshSoundTextLevel (std::wstring name=L"")
TXshSoundTextLevel * clone () const
TXshSoundTextLevel * getSoundTextLevel () override
Overridden from TXshLevel.
void setFrameText (int frameIndex, QString)
QString getFrameText (int frameIndex) const
void loadData (TIStream &is) override
Load the level data (i.e. name, path, etc. e.g. from the .tnz file)
void saveData (TOStream &os) override
Save the level data (i.e. name, path, etc. e.g. to the .tnz file)
void load () override
Load the level content from the associated path.
void save () override
Save the level content to the associated path.
Public Member Functions inherited from TXshLevel
TXshLevel (ClassCode classCode, std::wstring name)
virtual ~TXshLevel ()
void setName (std::wstring name)
int getType () const
void setType (int type)
change the level type;
ToonzScene * getScene () const
Return the ToonzScene the level belongs to;.
virtual void setScene (ToonzScene *scene)
virtual TXshSimpleLevel * getSimpleLevel ()
Method (to be overridden in subclasses) to downcast to TXshSimpleLevel.
virtual TXshChildLevel * getChildLevel ()
Method (to be overridden in subclasses) to downcast to TXshChildLevel.
virtual TXshZeraryFxLevel * getZeraryFxLevel ()
virtual TXshPaletteLevel * getPaletteLevel ()
Method (to be overridden in subclasses) to downcast to TXshPaletteLevel.
virtual TXshSoundLevel * getSoundLevel ()
Method (to be overridden in subclasses) to downcast to TXshSoundLevel.
virtual TXshSoundTextLevel * getSoundTextLevel ()
std::wstring getName () const
Return level name.
std::wstring getShortName () const
Return level short name.
virtual TFilePath getPath () const
Return the file path associated with the level.
virtual bool isEmpty () const
virtual int getFrameCount () const
virtual void getFids (std::vector< TFrameId > &fids) const
void loadData (TIStream &is) override=0
Load the level data (i.e. name, path, etc. e.g. from the .tnz file)
void saveData (TOStream &os) override=0
Save the level data (i.e. name, path, etc. e.g. to the .tnz file)
virtual void load ()=0
Load the level content from the associated path.
virtual void save ()=0
Save the level content to the associated path.
HookSet * getHookSet () const
virtual void setDirtyFlag (bool on)
Mark the level as "modified".
Public Member Functions inherited from TSmartObject
TSmartObject (ClassCode classCode)
void addRef ()
void release ()
TINT32 getRefCount () const
Public Member Functions inherited from TPersist
virtual void loadData (TIStream &is)=0
virtual void saveData (TOStream &os)=0
std::string getStreamTag () const
virtual const TPersistDeclaration * getDeclaration () const =0
Additional Inherited Members
Public Types inherited from TSmartObject
typedef short ClassCode
Public Types inherited from TPersist
typedef TPersist * CreateProc()
Static Public Member Functions inherited from TSmartObject
static TINT32 getInstanceCount (ClassCode code)
Static Public Member Functions inherited from TPersist
static void declare (CreateProc *)
static TPersist * create (const std::string &name)
Protected Member Functions inherited from TXshLevel
void updateShortName ()
create shortname from the level name
Protected Attributes inherited from TXshLevel
std::wstring m_name
std::wstring m_shortName
int m_type
HookSet * m_hookSet
ToonzScene * m_scene
Detailed Description
The TXshSoundTextLevel.
Constructor & Destructor Documentation
TXshSoundTextLevel()
TXshSoundTextLevel::TXshSoundTextLevel (std::wstring name = L"")
    : TXshLevel(m_classCode, name), m_framesText() {}
~TXshSoundTextLevel()
TXshSoundTextLevel::~TXshSoundTextLevel ()
{}
Member Function Documentation
clone()
TXshSoundTextLevel * TXshSoundTextLevel::clone () const
{
  TXshSoundTextLevel *sound = new TXshSoundTextLevel(m_name);
  return sound;
}
getFrameText()
QString TXshSoundTextLevel::getFrameText (int frameIndex) const
{
  if (frameIndex >= m_framesText.size()) return QString();
  return m_framesText[frameIndex];
}
getSoundTextLevel()
TXshSoundTextLevel * TXshSoundTextLevel::getSoundTextLevel () inline override virtual
Overridden from TXshLevel.
Reimplemented from TXshLevel.
{ return this; }
load()
void TXshSoundTextLevel::load () inline override virtual
Load the level content from the associated path.
Implements TXshLevel.
{};
loadData()
void TXshSoundTextLevel::loadData (TIStream & is) override virtual
Load the level data (i.e. name, path, etc. e.g. from the .tnz file)
Implements TXshLevel.
{
  is >> m_name;
  setName(m_name);
  std::string tagName;
  int type = UNKNOWN_XSHLEVEL;
  while (is.matchTag(tagName)) {
    if (tagName == "type") {
      std::string v;
      is >> v;
      if (v == "textSound") type = SND_TXT_XSHLEVEL;
      is.matchEndTag();
    } else if (tagName == "frame") {
      std::wstring text;
      is >> text;
      m_framesText.push_back(QString::fromStdWString(text));
      is.matchEndTag();
    } else
      throw TException("unexpected tag " + tagName);
  }
  setType(type);
}
References TIStream::matchEndTag(), TIStream::matchTag(), and TXshLevel::setType().
save()
void TXshSoundTextLevel::save () inline override virtual
Save the level content to the associated path.
Implements TXshLevel.
{};
saveData()
void TXshSoundTextLevel::saveData (TOStream & os) override virtual
Save the level data (i.e. name, path, etc. e.g. to the .tnz file)
Implements TXshLevel.
{
  os << m_name;
  int i;
  for (i = 0; i < m_framesText.size(); i++) {
    os.openChild("frame");
    os << m_framesText[i];
    os.closeChild();
  }
  os.child("type") << L"textSound";
}
References TOStream::child(), TOStream::closeChild(), and TOStream::openChild().
setFrameText()
void TXshSoundTextLevel::setFrameText (int frameIndex, QString text)
{
  while (frameIndex >= m_framesText.size()) {
    m_framesText.append(QString(" "));
  }
  m_framesText.replace(frameIndex, text);
}
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/toonz/txshsoundtextlevel.h
E:/opentoonz/toonz/sources/toonzlib/txshsoundtextlevel.cpp