opentoonz: DVGui::IntPairField Class Reference
DVGui::IntPairField Class Reference
The IntPairField class provides to view an object to manage a pair of int parameter.
#include <intpairfield.h>
Signals
void valuesChanged (bool isDragging)
Public Member Functions
IntPairField (QWidget *parent=0, bool isMaxRangeLimited=true)
void setValues (const std::pair< int, int > &values)
std::pair< int, int > getValues () const
void setLeftText (const QString &text)
void setRightText (const QString &text)
void setLabelsEnabled (bool enable)
void setRange (int minValue, int maxValue)
void getRange (int &minValue, int &maxValue)
QPixmap getHandleLeftPixmap () const
void setHandleLeftPixmap (const QPixmap &pixmap)
QPixmap getHandleRightPixmap () const
void setHandleRightPixmap (const QPixmap &pixmap)
QPixmap getHandleLeftGrayPixmap () const
void setHandleLeftGrayPixmap (const QPixmap &pixmap)
QPixmap getHandleRightGrayPixmap () const
void setHandleRightGrayPixmap (const QPixmap &pixmap)
void setLightLineColor (const QColor &color)
QColor getLightLineColor () const
void setDarkLineColor (const QColor &color)
QColor getDarkLineColor () const
void setMiddleLineColor (const QColor &color)
QColor getMiddleLineColor () const
void setLightLineEdgeColor (const QColor &color)
QColor getLightLineEdgeColor () const
Protected Slots
void onLeftEditingFinished ()
void onRightEditingFinished ()
Protected Member Functions
int pos2value (int x) const
int value2pos (int v) const
void setValue (int v)
void paintEvent (QPaintEvent *) override
void mousePressEvent (QMouseEvent *event) override
void mouseMoveEvent (QMouseEvent *event) override
void mouseReleaseEvent (QMouseEvent *event) override
void setLinearSlider (bool linear)
Properties
QPixmap HandleLeftPixmap
QPixmap HandleRightPixmap
QPixmap HandleLeftGrayPixmap
QPixmap HandleRightGrayPixmap
QColor LightLineColor
QColor DarkLineColor
QColor MiddleLineColor
QColor LightLineEdgeColor
Detailed Description
The IntPairField class provides to view an object to manage a pair of int parameter.
Inherits QWidget.
The object is composed of an horizontal layout QHBoxLayout which contains two pair [label, text field] and a slider with two grab, one for each int value to manage. [label, text field] are a QLabel and a IntLineEdit. Objects are inserted in the following order: a label and respective text field, the slider and the other pair [lebel,text field]. Object size width is not fixed, while height is equal to DVGui::WidgetHeight, 20; labels width depend from its text length, text fields has fixed size, while slider width change in according with widget size.
Objects contained in this widget are connected, so if you change one value the other automatically change, if it is necessary. You can set current value, getValues(), minimum and max value, getRange(), using setValues(), setRange().
         To know when one of two int parameter value change class
provides a signal, valuesChanged(); class emit signal when a grab slider position change or when editing text field, left or right is finished and current value is changed. Editing text field finished may occur if focus is lost or enter key is pressed. See SLOT: onLeftEditingFinished() and onRightEditingFinished().
Example:
                     IntPairField* intPairFieldExample = new
IntPairField(this);
                     intPairFieldExample->setLeftText(tr("Left Value:"));
                     intPairFieldExample->setRightText(tr("Right Value:"));
                     intPairFieldExample->setRange(0,10);
                     intPairFieldExample->setValues(std::make_pair(3,8));
Result:
Constructor & Destructor Documentation
IntPairField()
IntPairField::IntPairField (QWidget * parent = 0, bool isMaxRangeLimited = true)
    : QWidget(parent)
    , m_values(0, 0)
    , m_minValue(0)
    , m_maxValue(100)
    , m_grabOffset(0)
    , m_grabIndex(-1)
    , m_leftMargin(52)
    , m_rightMargin(52)
    , m_isMaxRangeLimited(isMaxRangeLimited)
    , m_isLinear(true) {
  setObjectName("IntPairField");
  setFixedHeight(WidgetHeight);
  m_leftLabel    = new QLabel("", this);
  m_leftLineEdit = new DVGui::IntLineEdit(this);
  m_rightLabel    = new QLabel("", this);
  m_rightLineEdit = new DVGui::IntLineEdit(this);
  m_leftLineEdit->setFixedWidth(40);
  m_rightLineEdit->setFixedWidth(40);
  //----layout
  QHBoxLayout *m_mainLayout = new QHBoxLayout;
  m_mainLayout->setMargin(0);
  m_mainLayout->setSpacing(5);
  {
    m_mainLayout->addWidget(m_leftLabel, 1);
    m_mainLayout->addWidget(m_leftLineEdit, 1, Qt::AlignLeft);
    m_mainLayout->addSpacing(35);
    m_mainLayout->addStretch(100);
    m_mainLayout->addWidget(m_rightLabel, 1);
    m_mainLayout->addWidget(m_rightLineEdit, 1, Qt::AlignRight);
  }
  setLayout(m_mainLayout);
  //---signal-slot connections
  bool ret = connect(m_leftLineEdit, SIGNAL(editingFinished()),
                     SLOT(onLeftEditingFinished()));
  ret      = ret && connect(m_rightLineEdit, SIGNAL(editingFinished()),
                       SLOT(onRightEditingFinished()));
  assert(ret);
}
~IntPairField()
DVGui::IntPairField::~IntPairField () inline
{}
Member Function Documentation
getDarkLineColor()
QColor DVGui::IntPairField::getDarkLineColor () const inline
{ return m_darkLineColor; }
getHandleLeftGrayPixmap()
QPixmap DVGui::IntPairField::getHandleLeftGrayPixmap () const inline
{ return m_handleLeftGrayPixmap; }
getHandleLeftPixmap()
QPixmap DVGui::IntPairField::getHandleLeftPixmap () const inline
{ return m_handleLeftPixmap; }
getHandleRightGrayPixmap()
QPixmap DVGui::IntPairField::getHandleRightGrayPixmap () const inline
{ return m_handleRightGrayPixmap; }
getHandleRightPixmap()
QPixmap DVGui::IntPairField::getHandleRightPixmap () const inline
{ return m_handleRightPixmap; }
getLightLineColor()
QColor DVGui::IntPairField::getLightLineColor () const inline
{ return m_lightLineColor; }
getLightLineEdgeColor()
QColor DVGui::IntPairField::getLightLineEdgeColor () const inline
{ return m_lightLineEdgeColor; }
getMiddleLineColor()
QColor DVGui::IntPairField::getMiddleLineColor () const inline
{ return m_middleLineColor; }
getRange()
void IntPairField::getRange (int & minValue, int & maxValue)
Set minValue and maxValue to IntPairField range.
{
  minValue = m_minValue;
  maxValue = m_maxValue;
}
getValues()
std::pair< int, int > DVGui::IntPairField::getValues () const inline
Return a pair containing current values.
{ return m_values; }
mouseMoveEvent()
void IntPairField::mouseMoveEvent (QMouseEvent * event) override protected
{
  if (event->buttons()) {
    std::pair<int, int> oldValues = m_values;
    int x                         = event->pos().x() + m_grabOffset;
    setValue(pos2value(x));
    if (oldValues == m_values) return;
    emit valuesChanged(true);
    update();
  }
}
mousePressEvent()
void IntPairField::mousePressEvent (QMouseEvent * event) override protected
{
  if (event->button() == Qt::LeftButton) {
    int x = event->pos().x();
    int cur0, cur1;
    if (m_values.first > m_maxValue)
      cur0 = value2pos(m_maxValue) - 5;
    else
      cur0 = value2pos(m_values.first);
    if (m_values.second > m_maxValue)
      cur1 = value2pos(m_maxValue);
    else
      cur1 = value2pos(m_values.second);
    int d0 = abs(cur0 - x);
    int d1 = abs(cur1 - x);
    int d, cur;
    if (d0 < d1 || (d0 == d1 && x < cur0)) {
      d           = d0;
      cur         = cur0;
      m_grabIndex = 0;
    } else {
      d           = d1;
      cur         = cur1;
      m_grabIndex = 1;
    }
    if (d < 6)
      m_grabOffset = cur - x;
    else {
      m_grabOffset = 0;
      setValue(pos2value(x));
      emit valuesChanged(true);
      update();
    }
  }
}
mouseReleaseEvent()
void IntPairField::mouseReleaseEvent (QMouseEvent * event) override protected
{
  m_grabOffset = 0;
  m_grabIndex  = 0;
  emit valuesChanged(false);
}
onLeftEditingFinished
void IntPairField::onLeftEditingFinished () protected slot
Set current left value to value in left text field; if necessary, if left value is greater than right, change also current right value.
This protected slot is called when text editing is finished.
Emit valuesChanged().
If current left value is equal to left text field value, return and do nothing.
{
  int value = m_leftLineEdit->getValue();
  if (value == m_values.first) return;
  if (!m_isMaxRangeLimited && value < m_minValue)
    value = m_minValue;
  else if (m_isMaxRangeLimited)
    value = tcrop(value, m_minValue, m_maxValue);
  m_values.first = value;
  if (m_values.first > m_values.second) {
    m_values.second = m_values.first;
    m_rightLineEdit->setValue(m_values.second);
  }
  emit valuesChanged(false);
  update();
}
References DVGui::IntLineEdit::getValue(), DVGui::IntLineEdit::setValue(), and valuesChanged().
onRightEditingFinished
void IntPairField::onRightEditingFinished () protected slot
Set current right value to value in right text field; if necessary, if right value is lower than left, change also current left value.
This protected slot is called when text editing is finished.
Emit valuesChanged().
If current right value is equal to right text field value return and do nothing.
{
  int value = m_rightLineEdit->getValue();
  if (value == m_values.second) return;
  if (m_isMaxRangeLimited) value = tcrop(value, m_minValue, m_maxValue);
  m_values.second = value;
  if (m_values.second < m_values.first) {
    m_values.first = m_values.second;
    m_leftLineEdit->setValue(m_values.first);
  }
  emit valuesChanged(false);
  update();
}
References DVGui::IntLineEdit::getValue(), DVGui::IntLineEdit::setValue(), and valuesChanged().
paintEvent()
void IntPairField::paintEvent (QPaintEvent *) override protected
{
  QPainter p(this);
  p.setBrush(Qt::NoBrush);
  int x0 = value2pos(m_minValue);
  int x1 = value2pos(m_maxValue);
  int y  = height() / 2;
  p.setPen(QPen(getDarkLineColor(), 4));
  p.drawLine(x0 - 1, y, x1, y);
  p.setPen(Qt::black);
  int y1 = height() - 1;
  int x;
  x                = value2pos(m_values.first);
  QRect sliderRect = QRect(x0, -5, x1 - x0 + 1, 10);
  if (sliderRect.contains(QPoint(x, 0)))
    p.drawPixmap(x - m_handleLeftPixmap.width() + 1, 2, m_handleLeftPixmap);
  else
    p.drawPixmap(sliderRect.right() - m_handleLeftPixmap.width() + 1, 2,
                 m_handleLeftGrayPixmap);
  x = value2pos(m_values.second);
  if (sliderRect.contains(QPoint(x, 0)))
    p.drawPixmap(x, 2, m_handleRightPixmap);
  else
    p.drawPixmap(sliderRect.right(), 2, m_handleRightGrayPixmap);
}
pos2value()
int IntPairField::pos2value (int x) const protected
Return value corresponding x position.
{
  int xMin = m_leftMargin, xMax = width() - m_rightMargin - 1;
  if (m_isLinear)
    return m_minValue + (m_maxValue - m_minValue) * (x - xMin) / (xMax - xMin);
  // nonlinear slider case
  double posRatio = (double)(x - xMin) / (double)(xMax - xMin);
  double t;
  if (posRatio <= 0.5)
    t = 0.04 * posRatio;
  else if (posRatio <= 0.75)
    t = -0.02 + 0.08 * posRatio;
  else if (posRatio <= 0.9)
    t = -0.26 + 0.4 * posRatio;
  else
    t = -8.0 + 9.0 * posRatio;
  return m_minValue + (int)((double)(m_maxValue - m_minValue) * t);
}
setDarkLineColor()
void DVGui::IntPairField::setDarkLineColor (const QColor & color) inline
{ m_darkLineColor = color; }
setHandleLeftGrayPixmap()
void DVGui::IntPairField::setHandleLeftGrayPixmap (const QPixmap & pixmap) inline
{
    m_handleLeftGrayPixmap = pixmap;
  }
setHandleLeftPixmap()
void DVGui::IntPairField::setHandleLeftPixmap (const QPixmap & pixmap) inline
{
    m_handleLeftPixmap = pixmap;
  }
setHandleRightGrayPixmap()
void DVGui::IntPairField::setHandleRightGrayPixmap (const QPixmap & pixmap) inline
{
    m_handleRightGrayPixmap = pixmap;
  }
setHandleRightPixmap()
void DVGui::IntPairField::setHandleRightPixmap (const QPixmap & pixmap) inline
{
    m_handleRightPixmap = pixmap;
  }
setLabelsEnabled()
void IntPairField::setLabelsEnabled (bool enable)
{
  if (!enable) {
    m_rightLabel->hide();
    m_leftLabel->hide();
  } else {
    m_rightLabel->show();
    m_leftLabel->show();
  }
}
setLeftText()
void IntPairField::setLeftText (const QString & text)
Set left label string to QString text. Recompute left margin adding label width.
{
  QPoint pos       = m_leftLabel->pos();
  QString oldText  = m_leftLabel->text();
  int oldLabelSize = fontMetrics().width(oldText);
  int newLabelSize = fontMetrics().width(text);
  int labelSize    = newLabelSize - oldLabelSize;
  m_leftMargin += labelSize + MARGIN_OFFSET;
  m_leftLabel->setText(text);
  update();
}
setLightLineColor()
void DVGui::IntPairField::setLightLineColor (const QColor & color) inline
{ m_lightLineColor = color; }
setLightLineEdgeColor()
void DVGui::IntPairField::setLightLineEdgeColor (const QColor & color) inline
{
    m_lightLineEdgeColor = color;
  }
setLinearSlider()
void DVGui::IntPairField::setLinearSlider (bool linear) inline protected
{ m_isLinear = linear; }
setMiddleLineColor()
void DVGui::IntPairField::setMiddleLineColor (const QColor & color) inline
{ m_middleLineColor = color; }
setRange()
void IntPairField::setRange (int minValue, int maxValue)
Set range of IntPairField to minValue, maxValue.
{
  m_minValue = minValue;
  m_maxValue = maxValue;
  if (!m_isMaxRangeLimited) maxValue = (std::numeric_limits<int>::max)();
  m_leftLineEdit->setRange(minValue, maxValue);
  m_rightLineEdit->setRange(minValue, maxValue);
  update();
}
References DVGui::IntLineEdit::setRange().
setRightText()
void IntPairField::setRightText (const QString & text)
Set right label string to QString text. Recompute right margin adding label width.
{
  QString oldText  = m_rightLabel->text();
  int oldLabelSize = fontMetrics().width(oldText);
  int newLabelSize = fontMetrics().width(text);
  int labelSize    = newLabelSize - oldLabelSize;
  m_rightMargin += labelSize + MARGIN_OFFSET;
  m_rightLabel->setText(text);
  update();
}
setValue()
void IntPairField::setValue (int v) protected
Set current value to value. Set left or right value, or both, to value depending on current slider grab edited and value.
{
  value = tcrop(value, m_minValue, m_maxValue);
  value = tround(value * 100) * 0.01;
  if (m_grabIndex == 0)  // Left grab
  {
    m_values.first = value;
    m_leftLineEdit->setValue(m_values.first);
    if (value > m_values.second) {
      m_values.second = value;
      m_rightLineEdit->setValue(m_values.second);
    }
  } else  // Right grab
  {
    m_values.second = value;
    m_rightLineEdit->setValue(m_values.second);
    if (value < m_values.first) {
      m_values.first = value;
      m_leftLineEdit->setValue(m_values.first);
    }
  }
}
References DVGui::IntLineEdit::setValue().
setValues()
void IntPairField::setValues (const std::pair< int, int > & values)
Set current values to values.
{
  assert(values.first <= values.second);
  m_values.first = tcrop(values.first, m_minValue, m_maxValue);
  m_leftLineEdit->setValue(m_values.first);
  m_values.second = values.second;
  if (m_isMaxRangeLimited)
    m_values.second = tcrop(values.second, m_values.first, m_maxValue);
  m_rightLineEdit->setValue(m_values.second);
  update();
}
References DVGui::IntLineEdit::setValue().
value2pos()
int IntPairField::value2pos (int v) const protected
Return x position corresponding value.
{
  int xMin = m_leftMargin, xMax = width() - m_rightMargin - 1;
  if (m_isLinear)
    return xMin +
           ((xMax - xMin) * (v - m_minValue)) / (m_maxValue - m_minValue);
  // nonlinear slider case
  double valueRatio =
      (double)(v - m_minValue) / (double)(m_maxValue - m_minValue);
  double t;
  if (valueRatio <= 0.02)
    t = valueRatio / 0.04;
  else if (valueRatio <= 0.04)
    t = (valueRatio + 0.02) / 0.08;
  else if (valueRatio <= 0.1)
    t = (valueRatio + 0.26) / 0.4;
  else
    t = (valueRatio + 8.0) / 9.0;
  return xMin + (int)(t * (double)(xMax - xMin));
}
valuesChanged
void DVGui::IntPairField::valuesChanged (bool isDragging) signal
This signal is emitted when change one of two IntField value; if one slider grab position change or if one text field editing is finished.
Referenced by onLeftEditingFinished(), and onRightEditingFinished().
Property Documentation
DarkLineColor
QColor DVGui::IntPairField::DarkLineColor read write
HandleLeftGrayPixmap
QPixmap DVGui::IntPairField::HandleLeftGrayPixmap read
HandleLeftPixmap
QPixmap DVGui::IntPairField::HandleLeftPixmap read
HandleRightGrayPixmap
QPixmap DVGui::IntPairField::HandleRightGrayPixmap read
HandleRightPixmap
QPixmap DVGui::IntPairField::HandleRightPixmap read
LightLineColor
QColor DVGui::IntPairField::LightLineColor read write
LightLineEdgeColor
QColor DVGui::IntPairField::LightLineEdgeColor read
MiddleLineColor
QColor DVGui::IntPairField::MiddleLineColor read write
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/toonzqt/intpairfield.h
E:/opentoonz/toonz/sources/toonzqt/intpairfield.cpp