opentoonz: DVGui::SpectrumField Class Reference
DVGui::SpectrumField Class Reference final
The SpectrumField class provides an object to display and manage a spectrum.
Signals
void keyColorChanged (bool)
void keyPositionChanged (bool)
void keyAdded (int)
void keyRemoved (int)
Public Member Functions
SpectrumField (QWidget *parent=0, TPixel32 color=TPixel32(0, 0, 0, 255))
TSpectrum & getSpectrum ()
void setSpectrum (TSpectrum &spectrum)
int getCurrentKeyIndex ()
void setCurrentKeyIndex (int index)
Protected Slots
void onCurrentPosChanged (bool isDragging)
void onCurrentKeyChanged ()
void onColorChanged (const TPixel32 &color, bool isDragging)
Protected Member Functions
void paintEvent (QPaintEvent *e) override
Detailed Description
The SpectrumField class provides an object to display and manage a spectrum.
         Inherits \b QWidget.
         The object is composed of a vertical layout \b QVBoxLayout which
contains a spectrum bar SpectrumBar and a color field ColorField. Using color field it's possible to set spectrum current key color.
Example: Spectrum Field.
Constructor & Destructor Documentation
SpectrumField()
SpectrumField::SpectrumField (QWidget * parent = 0, TPixel32 color = TPixel32(0, 0, 0, 255))
    : QWidget(parent), m_margin(0), m_spacing(4) {
  setFixedHeight(60);
  QVBoxLayout *layout = new QVBoxLayout();
  layout->setMargin(m_margin);
  layout->setSpacing(m_spacing);
  m_spectrumbar = new SpectrumBar(this, color);
  connect(m_spectrumbar, SIGNAL(currentPosChanged(bool)),
          SLOT(onCurrentPosChanged(bool)));
  connect(m_spectrumbar, SIGNAL(currentKeyChanged()),
          SLOT(onCurrentKeyChanged()));
  connect(m_spectrumbar, SIGNAL(currentKeyAdded(int)), SIGNAL(keyAdded(int)));
  connect(m_spectrumbar, SIGNAL(currentKeyRemoved(int)),
          SIGNAL(keyRemoved(int)));
  layout->addWidget(m_spectrumbar);
  m_colorField = new ColorField(this, true, color, 36);
  connect(m_colorField, SIGNAL(colorChanged(const TPixel32 &, bool)), this,
          SLOT(onColorChanged(const TPixel32 &, bool)));
  layout->addWidget(m_colorField, 0, Qt::AlignLeft);
  setLayout(layout);
}
~SpectrumField()
SpectrumField::~SpectrumField ()
{}
Member Function Documentation
getCurrentKeyIndex()
int DVGui::SpectrumField::getCurrentKeyIndex () inline
{ return m_spectrumbar->getCurrentKeyIndex(); }
getSpectrum()
TSpectrum & DVGui::SpectrumField::getSpectrum () inline
{ return m_spectrumbar->getSpectrum(); }
onColorChanged
void SpectrumField::onColorChanged (const TPixel32 & color, bool isDragging) protected slot
Set spectrum current key color to color and emit keyColorChanged().
{
  m_spectrumbar->setCurrentColor(color);
  emit keyColorChanged(isDragging);
}
References DVGui::SpectrumBar::setCurrentColor().
onCurrentKeyChanged
void SpectrumField::onCurrentKeyChanged () protected slot
Set color field to spectrum current key color and update.
{
  if (m_spectrumbar->getCurrentKeyIndex() != -1)
    m_colorField->setColor(m_spectrumbar->getCurrentColor());
  update();
}
References DVGui::SpectrumBar::getCurrentColor().
onCurrentPosChanged
void SpectrumField::onCurrentPosChanged (bool isDragging) protected slot
Update all widget and emit keyPositionChanged() signal.
{
  if (m_spectrumbar->getCurrentKeyIndex() == -1) return;
  update();
  emit keyPositionChanged(isDragging);
}
paintEvent()
void SpectrumField::paintEvent (QPaintEvent * e) override protected
Paint an arrow to connect current spectrum key and square color field.
{
  int curPos = m_spectrumbar->getCurrentPos();
  if (curPos == -1) return;
  QPainter p(this);
  int x0 = 18 + m_margin;
  int y0 = 2 * m_margin + WidgetHeight + m_spacing;
  int y  = m_margin + m_spacing +
          (WidgetHeight * 0.5 -
           4);  // 4 e' l'altezza della freccia nella spectrum bar
  int y1 = y0 - y * 0.5 + 1;
  int y2 = y0 - y;
  curPos += m_margin;
  p.setPen(Qt::black);
  p.drawLine(x0, y0, x0, y1);
  p.drawLine(x0, y1, curPos, y1);
  p.drawLine(curPos, y1, curPos, y2);
}
References DVGui::SpectrumBar::getCurrentPos().
setCurrentKeyIndex()
void DVGui::SpectrumField::setCurrentKeyIndex (int index) inline
{
    m_spectrumbar->setCurrentKeyIndex(index);
    m_colorField->setColor(m_spectrumbar->getCurrentColor());
  }
setSpectrum()
void DVGui::SpectrumField::setSpectrum (TSpectrum & spectrum) inline
{
    m_spectrumbar->setSpectrum(spectrum);
    m_colorField->setColor(m_spectrumbar->getCurrentColor());
  }
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/toonzqt/spectrumfield.h
E:/opentoonz/toonz/sources/toonzqt/spectrumfield.cpp