opentoonz: CameraTestCheck Class Reference
CameraTestCheck Class Reference
The CameraTestCheck class allows visualization in "CameraTest" mode, from cleanup menu.
Public Member Functions
void setToggle (QAction *toggle)
bool isEnabled () const
void setIsEnabled (bool on)
Static Public Member Functions
static CameraTestCheck * instance ()
Detailed Description
The CameraTestCheck class allows visualization in "CameraTest" mode, from cleanup menu.
Member Function Documentation
instance()
CameraTestCheck * CameraTestCheck::instance () static
Return current CameraTestCheck instance.
{
  static CameraTestCheck _instance;
  return &_instance;
}
Referenced by StageBuilder::addFrame(), SceneViewer::getDpiFactor(), and SceneViewer::getZoomScaleFittingWithScreen().
isEnabled()
bool CameraTestCheck::isEnabled () const
{
  return m_toggle ? m_toggle->isChecked() : false;
}
setIsEnabled()
void CameraTestCheck::setIsEnabled (bool on)
{
  if (!m_toggle) return;
  if (m_toggle->isChecked() != on)
    m_toggle->trigger();  // Please, note that this is different than using
                          // setEnabled(bool)
}
setToggle()
void CameraTestCheck::setToggle (QAction * toggle)
{ m_toggle = toggle; }
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/toonz/stage2.h
E:/opentoonz/toonz/sources/toonzlib/stage2.cpp