opentoonz: FillTool Class Reference
FillTool Class Reference final
Public Slots
void onFrameSwitched () override
Public Member Functions
FillTool (int targetType)
ToolType getToolType () const override
void updateTranslation () override
TPropertyGroup * getProperties (int targetType) override
FillParameters getFillParameters () const
void leftButtonDown (const TPointD &pos, const TMouseEvent &e) override
void leftButtonDrag (const TPointD &pos, const TMouseEvent &e) override
void leftButtonUp (const TPointD &pos, const TMouseEvent &e) override
void mouseMove (const TPointD &pos, const TMouseEvent &e) override
void leftButtonDoubleClick (const TPointD &pos, const TMouseEvent &e) override
void resetMulti ()
bool onPropertyChanged (std::string propertyName) override
void onImageChanged () override
Notifies changes in the image in use.
void draw () override
Draws the tool on the viewer.
int pick (const TImageP &image, const TPointD &pos, const int frame=-1)
int pickOnionColor (const TPointD &pos)
void onEnter () override
Callback for the mouse entering the viewer area.
void onActivate () override
Callback invoked whenever the tool activates.
void onDeactivate () override
Callback for tool deactivation, includes tool switch.
int getCursorId () const override
Returns the type of cursor used by the tool.
int getColorClass () const
Public Member Functions inherited from TTool
TTool (std::string toolName)
every tool (invoking updateTranslation() for each).
virtual ToolType getToolType () const =0
ToolTargetType getTargetType () const
std::string getName () const
virtual ToolOptionsBox * createOptionsBox ()
void setViewer (Viewer *viewer)
Viewer * getViewer () const
double getPixelSize () const
void invalidate (const TRectD &rect=TRectD())
int pick (const TPointD &p)
bool isPicking () const
virtual void updateTranslation ()
virtual bool preLeftButtonDown ()
virtual void mouseMove (const TPointD &, const TMouseEvent &)
virtual void leftButtonDown (const TPointD &, const TMouseEvent &)
virtual void leftButtonDrag (const TPointD &, const TMouseEvent &)
virtual void leftButtonUp (const TPointD &, const TMouseEvent &)
virtual void leftButtonDoubleClick (const TPointD &, const TMouseEvent &)
virtual void rightButtonDown (const TPointD &, const TMouseEvent &)
virtual bool keyDown (QKeyEvent *)
virtual void onInputText (std::wstring, std::wstring, int, int)
virtual void onSetViewer ()
virtual void onActivate ()
Callback invoked whenever the tool activates.
virtual void onDeactivate ()
Callback for tool deactivation, includes tool switch.
virtual void onImageChanged ()
Notifies changes in the image in use.
virtual void onEnter ()
Callback for the mouse entering the viewer area.
virtual void onLeave ()
Callback for the mouse leaving the viewer area.
virtual void onFrameSwitched ()
virtual void reset ()
virtual void draw ()
Draws the tool on the viewer.
bool isActive () const
Used to know if a tool is active, (used in TextTool only).
void setActive (bool active)
virtual TPropertyGroup * getProperties (int)
virtual bool onPropertyChanged (std::string propertyName)
virtual TSelection * getSelection ()
Returns a pointer to the tool selection.
virtual int getCursorId () const
Returns the type of cursor used by the tool.
virtual bool isEventAcceptable (QEvent *e)
TXsheet * getXsheet () const
Returns a pointer to the actual Xsheet.
int getFrame ()
Returns the actual frame in use.
int getColumnIndex ()
Returns the actual column index.
TStageObjectId getObjectId () const
Returns a pointer to the actual stage object.
void notifyImageChanged ()
void notifyImageChanged (const TFrameId &fid)
images on the level view.
TFrameId getCurrentFid () const
Returns the number of the actual editing frame.
const TAffine & getMatrix () const
void setMatrix (const TAffine &matrix)
TAffine getCurrentColumnMatrix (int frame=-1) const
TAffine getCurrentColumnParentMatrix () const
TAffine getCurrentObjectParentMatrix () const
TAffine getCurrentObjectParentMatrix2 () const
TAffine getColumnMatrix (int index, int frame=-1) const
virtual void updateMatrix ()
virtual void addContextMenuItems (QMenu *menu)
void enable (bool on)
bool isEnabled () const
QString updateEnabled ()
virtual QString updateEnabled (int rowIndex, int columnIndex)
bool isColumnLocked (int columnIndex) const
void resetInputMethod ()
Resets Input Context (IME)
virtual bool isPencilModeActive ()
virtual bool isDragging () const
void setSelectedFrames (const std::set< TFrameId > &selectedFrames)
void tweenSelectedGuideStrokes ()
void tweenGuideStrokeToSelected ()
void flipGuideStrokeDirection (int mode)
Additional Inherited Members
Public Types inherited from TTool
enum ToolType {
GenericTool = 1 , ColumnTool = 2 , LevelReadTool = 4 , LevelWriteTool ,
LevelTool = LevelReadTool | LevelWriteTool
}
Tool editing type.
enum ToolTargetType {
NoTarget = 0x0 , VectorImage = 0x1 , ToonzImage = 0x2 , RasterImage = 0x4 ,
MeshImage = 0x8 , Splines = 0x10 , LevelColumns = 0x20 , MeshColumns = 0x40 ,
EmptyTarget = 0x80 , CommonImages = VectorImage | ToonzImage | RasterImage , AllImages = CommonImages | MeshImage , Vectors = VectorImage | Splines ,
CommonLevels = CommonImages | LevelColumns , MeshLevels = MeshImage | MeshColumns , AllTargets = 0xffffffff
}
Object types the tool can operate on.
typedef TApplication Application
Static Public Member Functions inherited from TTool
static TTool * getTool (std::string toolName, ToolTargetType targetType)
static TApplication * getApplication ()
static void setApplication (TApplication *application)
static TXshCell getImageCell ()
Returns the level-frame pair to be edited by the tool.
static TImage * getImage (bool toBeModified, int subsampling=0)
Returns the image to be edited by the tool.
static TImage * touchImage ()
static void updateToolsPropertiesTranslation ()
static const std::set< TFrameId > & getSelectedFrames ()
Static Public Attributes inherited from TTool
static std::vector< CellOps > m_cellsData
static bool m_isLevelCreated = false
static bool m_isFrameCreated = false
static std::vector< TFrameId > m_oldFids
static std::vector< TFrameId > m_newFids
static bool m_isLevelRenumbererd = false
Protected Member Functions inherited from TTool
void bind (int targetType)
virtual void onSelectedFramesChanged ()
virtual QString disableString ()
Returns a custom reason to disable the tool.
Protected Attributes inherited from TTool
std::string m_name
The tool's name.
Viewer * m_viewer
Tool's current viewer.
TAffine m_matrix
World-to-window reference change affine.
int m_targetType
The tool's image type target.
bool m_enabled
Whether the tool allows user interaction.
bool m_active
bool m_picking
Static Protected Attributes inherited from TTool
static TApplication * m_application = 0
static std::set< TFrameId > m_selectedFrames = std::set<TFrameId>()
Detailed Description
Constructor & Destructor Documentation
FillTool()
FillTool::FillTool (int targetType)
    : TTool("T_Fill")
    , m_frameRange("Frame Range", false)  // W_ToolOptions_FrameRange
    , m_fillType("Type:")
    , m_selective("Selective", false)
    , m_colorType("Mode:")
    , m_onion("Onion Skin", false)
    , m_fillDepth("Fill Depth", 0, 15, 0, 15)
    , m_segment("Segment", false)
    , m_onionStyleId(0)
    , m_currCell(-1, -1)
    , m_maxGapDistance("Maximum Gap", 0.01, 10.0, 1.15)
    , m_firstTime(true)
    , m_autopaintLines("Autopaint Lines", true) {
  m_rectFill           = new AreaFillTool(this);
  m_normalLineFillTool = new NormalLineFillTool(this);
  bind(targetType);
  m_prop.bind(m_fillType);
  m_fillType.addValue(NORMALFILL);
  m_fillType.addValue(RECTFILL);
  m_fillType.addValue(FREEHANDFILL);
  m_fillType.addValue(POLYLINEFILL);
  m_prop.bind(m_colorType);
  m_colorType.addValue(LINES);
  m_colorType.addValue(AREAS);
  m_colorType.addValue(ALL);
  m_prop.bind(m_selective);
  if (targetType == TTool::ToonzImage) {
    m_prop.bind(m_fillDepth);
    m_prop.bind(m_segment);
  }
  m_prop.bind(m_onion);
  m_prop.bind(m_frameRange);
  if (targetType == TTool::VectorImage) {
    m_prop.bind(m_maxGapDistance);
    m_maxGapDistance.setId("MaxGapDistance");
  }
  if (targetType == TTool::ToonzImage) m_prop.bind(m_autopaintLines);
  m_selective.setId("Selective");
  m_onion.setId("OnionSkin");
  m_frameRange.setId("FrameRange");
  m_segment.setId("SegmentInk");
  m_fillType.setId("Type");
  m_colorType.setId("Mode");
  m_autopaintLines.setId("AutopaintLines");
}
Member Function Documentation
draw()
void FillTool::draw () override virtual
Draws the tool on the viewer.
Reimplemented from TTool.
                    {
  if (Preferences::instance()->getFillOnlySavebox()) {
    TToonzImageP ti = (TToonzImageP)getImage(false);
    if (ti) {
      TRectD bbox =
          ToonzImageUtils::convertRasterToWorld(convert(ti->getBBox()), ti);
      drawRect(bbox.enlarge(0.5) * ti->getSubsampling(), TPixel32::Black,
               0x5555, true);
    }
  }
  if (m_fillType.getValue() != NORMALFILL) {
    m_rectFill->draw();
    return;
  }
  if (m_frameRange.getValue() && m_firstClick) {
    tglColor(TPixel::Red);
    drawCross(m_firstPoint, 6);
  } else if (!m_frameRange.getValue() &&
             getFillParameters().m_fillType == LINES &&
             m_targetType == TTool::ToonzImage)
    m_normalLineFillTool->draw();
}
References TTool::getImage(), TTool::m_targetType, and TTool::ToonzImage.
getColorClass()
int FillTool::getColorClass () const inline
{ return 2; }
getCursorId()
int FillTool::getCursorId () const override virtual
Returns the type of cursor used by the tool.
See also
For a list of cursor ids cursor.h
Reimplemented from TTool.
{
  int ret;
  if (m_colorType.getValue() == LINES)
    ret = ToolCursor::FillCursorL;
  else {
    ret = ToolCursor::FillCursor;
    if (m_colorType.getValue() == AREAS) ret = ret | ToolCursor::Ex_Area;
    if (!m_autopaintLines.getValue())
      ret = ret | ToolCursor::Ex_Fill_NoAutopaint;
  }
  if (m_fillType.getValue() == FREEHANDFILL)
    ret = ret | ToolCursor::Ex_FreeHand;
  else if (m_fillType.getValue() == POLYLINEFILL)
    ret = ret | ToolCursor::Ex_PolyLine;
  else if (m_fillType.getValue() == RECTFILL)
    ret = ret | ToolCursor::Ex_Rectangle;
  if (ToonzCheck::instance()->getChecks() & ToonzCheck::eBlackBg)
    ret = ret | ToolCursor::Ex_Negate;
  return ret;
}
References ToonzCheck::eBlackBg.
getFillParameters()
FillParameters FillTool::getFillParameters () const
{
  FillParameters params;
  int styleId      = TTool::getApplication()->getCurrentLevelStyleIndex();
  params.m_styleId = styleId;
  /*---colorTypefillType---*/
  params.m_fillType     = m_colorType.getValue();
  params.m_emptyOnly    = m_selective.getValue();
  params.m_segment      = m_segment.getValue();
  params.m_minFillDepth = (int)m_fillDepth.getValue().first;
  params.m_maxFillDepth = (int)m_fillDepth.getValue().second;
  return params;
}
getProperties()
TPropertyGroup * FillTool::getProperties (int targetType) inline override virtual
Reimplemented from TTool.
{ return &m_prop; }
getToolType()
ToolType FillTool::getToolType () const inline override virtual
Implements TTool.
{ return TTool::LevelWriteTool; }
leftButtonDoubleClick()
void FillTool::leftButtonDoubleClick (const TPointD & pos, const TMouseEvent & e) override virtual
Reimplemented from TTool.
{
  if (m_fillType.getValue() != NORMALFILL) {
    m_rectFill->leftButtonDoubleClick(pos, e);
    return;
  }
}
leftButtonDown()
void FillTool::leftButtonDown (const TPointD & pos, const TMouseEvent & e) override virtual
Reimplemented from TTool.
{
  TTool::Application *app = TTool::getApplication();
  if (!app) return;
  m_clickPoint = pos;
  if (m_fillType.getValue() != NORMALFILL) {
    m_rectFill->leftButtonDown(pos, e, getImage(true));
    return;
  }
  /*--NormalFill--*/
  FillParameters params = getFillParameters();
  if (m_onion.getValue()) {
    m_onionStyleId = pickOnionColor(pos);
    if (m_onionStyleId > 0) app->setCurrentLevelStyleIndex(m_onionStyleId);
  } else if (m_frameRange.getValue()) {
    if (!m_firstClick) {
      // PRIMO CLICK
      // if (app->getCurrentFrame()->isEditingScene())
      m_currCell = std::pair<int, int>(getColumnIndex(), getFrame());
      m_firstClick   = true;
      m_firstPoint   = pos;
      m_firstFrameId = m_veryFirstFrameId = getCurrentFid();
      // gmt. NON BISOGNA DISEGNARE DENTRO LE CALLBACKS!!!!
      // drawCross(m_firstPoint, 6);
      invalidate();
    } else {
      // When using tablet on windows, the mouse press event may be called AFTER
      // tablet release. It causes unwanted another "first click" just after
      // frame-range-filling. Calling processEvents() here to make sure to
      // consume the mouse press event in advance.
      qApp->processEvents();
      // SECONDO CLICK
      TFrameId fid = getCurrentFid();
      MultiFiller filler(m_firstPoint, pos, params,
                         m_autopaintLines.getValue());
      filler.processSequence(m_level.getPointer(), m_firstFrameId, fid);
      if (e.isShiftPressed()) {
        m_firstPoint   = pos;
        m_firstFrameId = getCurrentFid();
      } else {
        m_firstClick = false;
        if (app->getCurrentFrame()->isEditingScene()) {
          app->getCurrentColumn()->setColumnIndex(m_currCell.first);
          app->getCurrentFrame()->setFrame(m_currCell.second);
        } else
          app->getCurrentFrame()->setFid(m_veryFirstFrameId);
      }
      TTool *t = app->getCurrentTool()->getTool();
      if (t) t->notifyImageChanged();
    }
  } else {
    if (params.m_fillType == LINES && m_targetType == TTool::ToonzImage)
      m_normalLineFillTool->leftButtonDown(pos, e);
    else {
      TXshLevel *xl = app->getCurrentLevel()->getLevel();
      m_level       = xl ? xl->getSimpleLevel() : 0;
      doFill(getImage(true), pos, params, e.isShiftPressed(),
             m_level.getPointer(), getCurrentFid(),
             m_autopaintLines.getValue());
      invalidate();
    }
  }
}
leftButtonDrag()
void FillTool::leftButtonDrag (const TPointD & pos, const TMouseEvent & e) override virtual
Reimplemented from TTool.
{
  if ((m_fillType.getValue() != NORMALFILL && !m_onion.getValue()) ||
      (m_colorType.getValue() == AREAS && m_onion.getValue()))
    m_rectFill->leftButtonDrag(pos, e);
  else if (!m_onion.getValue() && !m_frameRange.getValue()) {
    FillParameters params = getFillParameters();
    if (params.m_fillType == LINES && m_targetType == TTool::ToonzImage) {
      m_normalLineFillTool->leftButtonDrag(pos, e);
      return;
    }
    if (m_clickPoint == pos) return;
    TImageP img = getImage(true);
    int styleId = params.m_styleId;
    if (TVectorImageP vi = img) {
      TRegion *r = vi->getRegion(pos);
      if (r && r->getStyle() == styleId) return;
    } else if (TToonzImageP ti = img) {
      TRasterCM32P ras = ti->getRaster();
      if (!ras) return;
      TPointD center = ras->getCenterD();
      TPoint ipos    = convert(pos + center);
      if (!ras->getBounds().contains(ipos)) return;
      TPixelCM32 pix = ras->pixels(ipos.y)[ipos.x];
      if (pix.getPaint() == styleId) {
        invalidate();
        return;
      }
      TSystem::outputDebug("ok. pix=" + std::to_string(pix.getTone()) + "," +
                           std::to_string(pix.getPaint()) + "\n");
    } else
      return;
    doFill(img, pos, params, e.isShiftPressed(), m_level.getPointer(),
           getCurrentFid(), m_autopaintLines.getValue());
    invalidate();
  }
}
leftButtonUp()
void FillTool::leftButtonUp (const TPointD & pos, const TMouseEvent & e) override virtual
Reimplemented from TTool.
{
  if (m_onion.getValue()) {
    if (m_fillType.getValue() != NORMALFILL && m_colorType.getValue() == AREAS)
      m_rectFill->leftButtonUp(pos, e);
    else if (m_onionStyleId > 0) {
      FillParameters tmp = getFillParameters();
      doFill(getImage(true), pos, tmp, e.isShiftPressed(), m_level.getPointer(),
             getCurrentFid(), m_autopaintLines.getValue());
      invalidate();
    }
  } else if (m_fillType.getValue() != NORMALFILL) {
    m_rectFill->leftButtonUp(pos, e);
    return;
  }
  if (!m_frameRange.getValue()) {
    TFrameId fid = getCurrentFid();
    // notifyImageChanged();
    if (getFillParameters().m_fillType == LINES &&
        m_targetType == TTool::ToonzImage) {
      FillParameters params = getFillParameters();
      m_normalLineFillTool->leftButtonUp(pos, e, getImage(true), params);
      return;
    }
  }
}
mouseMove()
void FillTool::mouseMove (const TPointD & pos, const TMouseEvent & e) override virtual
Reimplemented from TTool.
{
  if (m_fillType.getValue() != NORMALFILL) m_rectFill->mouseMove(pos, e);
}
onActivate()
void FillTool::onActivate () override virtual
Callback invoked whenever the tool activates.
Reimplemented from TTool.
{
  // OnionSkinMask osMask = getApplication()->getOnionSkinMask(false);
  /*
  for (int i=0; i<osMask.getMosCount(); i++)
  boh = osMask.getMos(i);
  for (i=0; i<osMask.getFosCount(); i++)
  boh = osMask.getFos(i);
  */
  if (m_firstTime) {
    m_fillDepth.setValue(
        TDoublePairProperty::Value(MinFillDepth, MaxFillDepth));
    m_fillType.setValue(::to_wstring(FillType.getValue()));
    m_colorType.setValue(::to_wstring(FillColorType.getValue()));
    //      m_onlyEmpty.setValue(FillSelective ? 1 :0);
    m_onion.setValue(FillOnion ? 1 : 0);
    m_segment.setValue(FillSegment ? 1 : 0);
    m_frameRange.setValue(FillRange ? 1 : 0);
    m_firstTime = false;
    if (m_fillType.getValue() != NORMALFILL) {
      AreaFillTool::Type type;
      if (m_fillType.getValue() == RECTFILL)
        type = AreaFillTool::RECT;
      else if (m_fillType.getValue() == FREEHANDFILL)
        type = AreaFillTool::FREEHAND;
      else if (m_fillType.getValue() == POLYLINEFILL)
        type = AreaFillTool::POLYLINE;
      else
        assert(false);
      m_rectFill->onPropertyChanged(
          m_frameRange.getValue(), m_selective.getValue(), m_onion.getValue(),
          type, m_colorType.getValue(), m_autopaintLines.getValue());
    }
  }
  if (m_fillType.getValue() != NORMALFILL) {
    m_rectFill->onActivate();
    return;
  }
  if (FillColorType.getValue() == "Lines") m_normalLineFillTool->init();
  resetMulti();
  //  getApplication()->editImage();
  TVectorImageP vi = TImageP(getImage(false));
  if (!vi) return;
  vi->findRegions();
  if (m_targetType == TTool::VectorImage) {
    if (m_level) {
      TImageP img = getImage(true);
      if (TVectorImageP vi = img) {
        double tolerance = vi->getAutocloseTolerance();
        if (tolerance < 9.9) tolerance += 0.000001;
        m_maxGapDistance.setValue(tolerance);
      }
    }
  }
  bool ret = true;
  ret      = ret && connect(TTool::m_application->getCurrentFrame(),
                       SIGNAL(frameSwitched()), this, SLOT(onFrameSwitched()));
  ret      = ret && connect(TTool::m_application->getCurrentScene(),
                       SIGNAL(sceneSwitched()), this, SLOT(onFrameSwitched()));
  ret      = ret &&
        connect(TTool::m_application->getCurrentColumn(),
                SIGNAL(columnIndexSwitched()), this, SLOT(onFrameSwitched()));
  assert(ret);
}
References TTool::getImage(), TTool::m_targetType, and TTool::VectorImage.
onDeactivate()
void FillTool::onDeactivate () override virtual
Callback for tool deactivation, includes tool switch.
Reimplemented from TTool.
{
  disconnect(TTool::m_application->getCurrentFrame(), SIGNAL(frameSwitched()),
             this, SLOT(onFrameSwitched()));
  disconnect(TTool::m_application->getCurrentScene(), SIGNAL(sceneSwitched()),
             this, SLOT(onFrameSwitched()));
  disconnect(TTool::m_application->getCurrentColumn(),
             SIGNAL(columnIndexSwitched()), this, SLOT(onFrameSwitched()));
}
onEnter()
void FillTool::onEnter () override virtual
Callback for the mouse entering the viewer area.
Reimplemented from TTool.
                       {
  // resetMulti();
  // getApplication()->editImage();
}
onFrameSwitched
void FillTool::onFrameSwitched () override slot
{
  m_frameSwitched = true;
  if (TVectorImageP vi = getImage(true)) {
    if (m_maxGapDistance.getValue() != vi->getAutocloseTolerance()) {
      m_maxGapDistance.setValue(vi->getAutocloseTolerance());
      getApplication()->getCurrentTool()->notifyToolChanged();
    }
  }
  m_frameSwitched           = false;
  m_changedGapOriginalValue = -1.0;
}
onImageChanged()
void FillTool::onImageChanged () override virtual
Notifies changes in the image in use.
Reimplemented from TTool.
{
  if (m_fillType.getValue() != NORMALFILL) {
    m_rectFill->onImageChanged();
    return;
  }
  if (TVectorImageP vi = getImage(true)) {
    m_frameSwitched = true;
    if (m_maxGapDistance.getValue() != vi->getAutocloseTolerance()) {
      m_maxGapDistance.setValue(vi->getAutocloseTolerance());
      getApplication()->getCurrentTool()->notifyToolChanged();
    }
    m_frameSwitched = false;
  }
  if (!m_level) resetMulti();
}
References TTool::getImage(), and ToolHandle::notifyToolChanged().
onPropertyChanged()
bool FillTool::onPropertyChanged (std::string propertyName) override virtual
 Does the tasks associated to changes in \p propertyName and returns \p
true; Does the tasks associated to changes in propertyName and returns true.
Reimplemented from TTool.
{
  /*--- m_rectFill->onPropertyChanged
                  fillType, frameRange, selective,
     colorType---*/
  bool rectPropChangedflag = false;
  // Areas, Lines etc.
  if (propertyName == m_colorType.getName()) {
    FillColorType       = ::to_string(m_colorType.getValue());
    rectPropChangedflag = true;
    /*--- ColorModelCursorSIGNAL ---*/
    TTool::getApplication()->getCurrentTool()->notifyToolChanged();
    /*--- FillLine ---*/
    if (FillColorType.getValue() == "Lines") m_normalLineFillTool->init();
  }
  // Rect, Polyline etc.
  else if (propertyName == m_fillType.getName()) {
    if (m_fillType.getValue() != NORMALFILL) {
      FillOnion   = (int)(m_onion.getValue());
      FillSegment = (int)(m_segment.getValue());
    }
    FillType            = ::to_string(m_fillType.getValue());
    rectPropChangedflag = true;
  }
  // Onion Skin
  else if (propertyName == m_onion.getName()) {
    if (m_onion.getValue()) FillType = ::to_string(m_fillType.getValue());
    FillOnion = (int)(m_onion.getValue());
  }
  // Frame Range
  else if (propertyName == m_frameRange.getName()) {
    FillRange = (int)(m_frameRange.getValue());
    resetMulti();
    rectPropChangedflag = true;
  }
  // Selective
  else if (propertyName == m_selective.getName()) {
    rectPropChangedflag = true;
  }
  // Fill Depth
  else if (propertyName == m_fillDepth.getName()) {
    MinFillDepth = (int)m_fillDepth.getValue().first;
    MaxFillDepth = (int)m_fillDepth.getValue().second;
  }
  // Segment
  else if (propertyName == m_segment.getName()) {
    if (m_segment.getValue()) FillType = ::to_string(m_fillType.getValue());
    FillSegment = (int)(m_segment.getValue());
  }
  // Autopaint
  else if (propertyName == m_autopaintLines.getName()) {
    rectPropChangedflag = true;
  }
  else if (!m_frameSwitched &&
           (propertyName == m_maxGapDistance.getName() ||
            propertyName == m_maxGapDistance.getName() + "withUndo")) {
    TXshLevel *xl = TTool::getApplication()->getCurrentLevel()->getLevel();
    m_level       = xl ? xl->getSimpleLevel() : 0;
    if (TVectorImageP vi = getImage(true)) {
      if (m_changedGapOriginalValue == -1.0) {
        ImageUtils::getFillingInformationInArea(vi, m_oldFillInformation,
                                                vi->getBBox());
        m_changedGapOriginalValue = vi->getAutocloseTolerance();
      }
      TFrameId fid = getCurrentFid();
      vi->setAutocloseTolerance(m_maxGapDistance.getValue());
      int count = vi->getStrokeCount();
      std::vector<int> v(count);
      int i;
      for (i = 0; i < (int)count; i++) v[i] = i;
      vi->notifyChangedStrokes(v, std::vector<TStroke *>(), false);
      if (m_level) {
        m_level->setDirtyFlag(true);
        TTool::getApplication()->getCurrentLevel()->notifyLevelChange();
        if (propertyName == m_maxGapDistance.getName() + "withUndo" &&
            m_changedGapOriginalValue != -1.0) {
          TUndoManager::manager()->add(new VectorGapSizeChangeUndo(
              m_changedGapOriginalValue, m_maxGapDistance.getValue(),
              m_level.getPointer(), fid, vi, m_oldFillInformation));
          m_changedGapOriginalValue = -1.0;
          m_oldFillInformation.clear();
          TTool::Application *app = TTool::getApplication();
          app->getCurrentXsheet()->notifyXsheetChanged();
          notifyImageChanged();
        }
      }
    }
  }
  /*--- fillType, frameRange, selective, colorType ---*/
  if (rectPropChangedflag && m_fillType.getValue() != NORMALFILL) {
    AreaFillTool::Type type;
    if (m_fillType.getValue() == RECTFILL)
      type = AreaFillTool::RECT;
    else if (m_fillType.getValue() == FREEHANDFILL)
      type = AreaFillTool::FREEHAND;
    else if (m_fillType.getValue() == POLYLINEFILL)
      type = AreaFillTool::POLYLINE;
    else
      assert(false);
    m_rectFill->onPropertyChanged(
        m_frameRange.getValue(), m_selective.getValue(), m_onion.getValue(),
        type, m_colorType.getValue(), m_autopaintLines.getValue());
  }
  return true;
}
References TTool::getCurrentFid(), TTool::getImage(), TXshLevel::getSimpleLevel(), TTool::notifyImageChanged(), ToolHandle::notifyToolChanged(), and TXshSimpleLevel::setDirtyFlag().
pick()
int FillTool::pick (const TImageP & image, const TPointD & pos, const int frame = -1)
{
  TToonzImageP ti  = image;
  TVectorImageP vi = image;
  if (!ti && !vi) return 0;
  StylePicker picker(image);
  double scale2 = 1.0;
  if (vi) {
    TAffine aff = getViewer()->getViewMatrix() * getCurrentColumnMatrix(frame);
    scale2      = aff.det();
  }
  TPointD pickPos = pos;
  // in case that the column is animated in scene-editing mode
  if (frame > 0) {
    TPointD dpiScale = getViewer()->getDpiScale();
    pickPos.x *= dpiScale.x;
    pickPos.y *= dpiScale.y;
    TPointD worldPos = getCurrentColumnMatrix() * pickPos;
    pickPos          = getCurrentColumnMatrix(frame).inv() * worldPos;
    pickPos.x /= dpiScale.x;
    pickPos.y /= dpiScale.y;
  }
  // thin stroke can be picked with 10 pixel range
  return picker.pickStyleId(pickPos, 10.0, scale2);
}
pickOnionColor()
int FillTool::pickOnionColor (const TPointD & pos)
{
  TTool::Application *app = TTool::getApplication();
  if (!app) return 0;
  bool filmStripEditing = !app->getCurrentObject()->isSpline();
  OnionSkinMask osMask  = app->getCurrentOnionSkin()->getOnionSkinMask();
  TFrameId fid = getCurrentFid();
  TXshSimpleLevel *sl = m_level.getPointer();
  if (!sl) return 0;
  std::vector<int> rows;
  // level editing case
  if (app->getCurrentFrame()->isEditingLevel()) {
    osMask.getAll(sl->guessIndex(fid), rows);
    int i, j;
    for (i = 0; i < (int)rows.size(); i++)
      if (sl->index2fid(rows[i]) > fid) break;
    int onionStyleId = 0;
    for (j = i - 1; j >= 0; j--) {
      TFrameId onionFid = sl->index2fid(rows[j]);
      if (onionFid != fid &&
          ((onionStyleId =
                pick(m_level->getFrame(onionFid, ImageManager::none, 1), pos)) >
           0))  // subsampling must be 1, otherwise onionfill does  not work
        break;
    }
    if (onionStyleId == 0)
      for (j = i; j < (int)rows.size(); j++) {
        TFrameId onionFid = sl->index2fid(rows[j]);
        if (onionFid != fid &&
            ((onionStyleId = pick(
                  m_level->getFrame(onionFid, ImageManager::none, 1), pos)) >
             0))  // subsampling must be 1, otherwise onionfill does  not work
          break;
      }
    return onionStyleId;
  } else {  // scene editing case
    TXsheet *xsh = app->getCurrentXsheet()->getXsheet();
    int colId    = app->getCurrentColumn()->getColumnIndex();
    int row      = app->getCurrentFrame()->getFrame();
    osMask.getAll(row, rows);
    std::vector<int>::iterator it = rows.begin();
    while (it != rows.end() && *it < row) it++;
    std::sort(rows.begin(), it, descending);
    int onionStyleId = 0;
    for (int i = 0; i < (int)rows.size(); i++) {
      if (rows[i] == row) continue;
      TXshCell cell = xsh->getCell(rows[i], colId);
      TXshLevel *xl = cell.m_level.getPointer();
      if (!xl || xl->getSimpleLevel() != sl) continue;
      TFrameId onionFid = cell.getFrameId();
      onionStyleId = pick(m_level->getFrame(onionFid, ImageManager::none, 1),
                          pos, rows[i]);
      if (onionStyleId > 0) break;
    }
    return onionStyleId;
  }
}
resetMulti()
void FillTool::resetMulti ()
{
  m_firstClick   = false;
  m_firstFrameId = -1;
  m_firstPoint   = TPointD();
  TXshLevel *xl  = TTool::getApplication()->getCurrentLevel()->getLevel();
  m_level        = xl ? xl->getSimpleLevel() : 0;
}
updateTranslation()
void FillTool::updateTranslation () override virtual
Reimplemented from TTool.
{
  m_frameRange.setQStringName(tr("Frame Range"));
  m_fillType.setQStringName(tr("Type:"));
  m_fillType.setItemUIName(NORMALFILL, tr("Normal"));
  m_fillType.setItemUIName(RECTFILL, tr("Rectangular"));
  m_fillType.setItemUIName(FREEHANDFILL, tr("Freehand"));
  m_fillType.setItemUIName(POLYLINEFILL, tr("Polyline"));
  m_selective.setQStringName(tr("Selective"));
  m_colorType.setQStringName(tr("Mode:"));
  m_colorType.setItemUIName(LINES, tr("Lines"));
  m_colorType.setItemUIName(AREAS, tr("Areas"));
  m_colorType.setItemUIName(ALL, tr("Lines & Areas"));
  m_onion.setQStringName(tr("Onion Skin"));
  m_fillDepth.setQStringName(tr("Fill Depth"));
  m_segment.setQStringName(tr("Segment"));
  m_maxGapDistance.setQStringName(tr("Maximum Gap"));
  m_autopaintLines.setQStringName(tr("Autopaint Lines"));
}
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/tnztools/filltool.h
E:/opentoonz/toonz/sources/tnztools/filltool.cpp