opentoonz: DragSelectionTool::VectorDeformTool Class Reference
DragSelectionTool::VectorDeformTool Class Reference
Classes
struct VFDScopedBlock
Public Member Functions
VectorDeformTool (VectorSelectionTool *tool)
void applyTransform (FourPoints bbox, bool onFastDragging=false) override
void addTransformUndo () override
void transformWholeLevel ()
bool isFlip ()
Public Member Functions inherited from DragSelectionTool::DeformTool
DeformTool (SelectionTool *tool)
virtual void applyTransform (FourPoints bbox, bool onFastDragging=false)=0
virtual void applyTransform (TAffine aff)
void addTransformUndo () override=0
int getSymmetricPointIndex (int index) const
int getBeforePointIndex (int index) const
int getNextPointIndex (int index) const
int getBeforeVertexIndex (int index) const
int getNextVertexIndex (int index) const
TPointD getStartPos () const
void setStartPos (const TPointD &pos)
TPointD getCurPos () const
void setCurPos (const TPointD &pos)
bool isDragging () const
TPointD getStartScaleValue () const
void leftButtonDown (const TPointD &pos, const TMouseEvent &e) override
void leftButtonDrag (const TPointD &pos, const TMouseEvent &e) override=0
void leftButtonUp (const TPointD &pos, const TMouseEvent &e) override
void draw () override=0
Public Member Functions inherited from DragSelectionTool::DragTool
DragTool (SelectionTool *tool)
SelectionTool * getTool () const
virtual void transform (TAffine aff, double angle)
virtual void transform (TAffine aff)
virtual TPointD transform (int index, TPointD newPos, bool onFastDragging=false)
virtual void addTransformUndo ()
virtual void leftButtonDown (const TPointD &pos, const TMouseEvent &)=0
virtual void leftButtonDrag (const TPointD &pos, const TMouseEvent &)=0
virtual void leftButtonUp (const TPointD &pos, const TMouseEvent &)=0
virtual void draw ()=0
Protected Member Functions
void leftButtonDrag (const TPointD &pos, const TMouseEvent &e) override
void leftButtonUp (const TPointD &pos, const TMouseEvent &e) override
void draw () override
Protected Attributes
std::unique_ptr< UndoChangeStrokes > m_undo
Protected Attributes inherited from DragSelectionTool::DeformTool
TPointD m_curPos
bool m_isDragging
TPointD m_startScaleValue
TPointD m_startPos
Protected Attributes inherited from DragSelectionTool::DragTool
SelectionTool * m_tool
Detailed Description
Constructor & Destructor Documentation
VectorDeformTool()
DragSelectionTool::VectorDeformTool::VectorDeformTool (VectorSelectionTool * tool)
    : DeformTool(tool), m_undo() {
  if (!TTool::getApplication()->getCurrentObject()->isSpline()) {
    m_undo.reset(new UndoChangeStrokes(
        TTool::getApplication()->getCurrentLevel()->getSimpleLevel(),
        tool->getCurrentFid(), tool, tool->strokeSelection()));
  }
}
~VectorDeformTool()
DragSelectionTool::VectorDeformTool::~VectorDeformTool ()
{
  // DO NOT REMOVE - DESTRUCTS TYPES INCOMPLETE IN THE HEADER
}
Member Function Documentation
addTransformUndo()
void DragSelectionTool::VectorDeformTool::addTransformUndo () override virtual
Implements DragSelectionTool::DeformTool.
{
  if (TTool::getApplication()->getCurrentObject()->isSpline())
    TUndoManager::manager()->add(
        new UndoPath(getTool()
                         ->getXsheet()
                         ->getStageObject(getTool()->getObjectId())
                         ->getSpline()));
  else if (m_undo) {
    m_undo->registerStrokes();
    TUndoManager::manager()->add(m_undo.release());
  }
}
applyTransform()
void DragSelectionTool::VectorDeformTool::applyTransform (FourPoints bbox, bool onFastDragging = false) override virtual
Implements DragSelectionTool::DeformTool.
{
  SelectionTool *tool = getTool();
  std::unique_ptr<VFDScopedBlock> localVfdScopedBlock;
  if (!m_vfdScopedBlock) {
    std::unique_ptr<VFDScopedBlock> &vfdScopedBlock =
        m_isDragging ? m_vfdScopedBlock : localVfdScopedBlock;
    vfdScopedBlock.reset(new VFDScopedBlock(tool));
  }
  VectorFreeDeformer *freeDeformer =
      static_cast<VectorFreeDeformer *>(tool->getFreeDeformer());
  const bool stayedTheSame = bbox.getP00() == freeDeformer->getPoint(0) &&
                             bbox.getP10() == freeDeformer->getPoint(1) &&
                             bbox.getP11() == freeDeformer->getPoint(2) &&
                             bbox.getP01() == freeDeformer->getPoint(3);
  freeDeformer->setPoints(bbox.getP00(), bbox.getP10(), bbox.getP11(),
                          bbox.getP01());
  freeDeformer->setComputeRegion(!m_isDragging);
  freeDeformer->setPreserveThickness(tool->isConstantThickness());
  freeDeformer->setFlip(isFlip());
  if (!TTool::getApplication()->getCurrentObject()->isSpline() && m_undo)
    m_undo->setFlip(isFlip());
  freeDeformer->deformImage();
  tool->invalidate();
  if (!m_isDragging) tool->notifyImageChanged();
  if (!stayedTheSame) tool->m_deformValues.m_isSelectionModified = true;
  if (!m_isDragging && (tool->isLevelType() || tool->isSelectedFramesType()))
    transformWholeLevel();
}
draw()
void DragSelectionTool::VectorDeformTool::draw () inline override protected virtual
Implements DragSelectionTool::DeformTool.
{}
isFlip()
bool DragSelectionTool::VectorDeformTool::isFlip ()
{
  TPointD scaleValue = getTool()->m_deformValues.m_scaleValue;
  return m_startScaleValue.x * scaleValue.x < 0 ||
         m_startScaleValue.y * scaleValue.y < 0;
}
leftButtonDrag()
void DragSelectionTool::VectorDeformTool::leftButtonDrag (const TPointD & pos, const TMouseEvent & e) inline override protected virtual
Implements DragSelectionTool::DeformTool.
{}
leftButtonUp()
void DragSelectionTool::VectorDeformTool::leftButtonUp (const TPointD & pos, const TMouseEvent & e) override protected virtual
Reimplemented from DragSelectionTool::DeformTool.
{
  std::unique_ptr<VFDScopedBlock> vfdScopedBlock(std::move(m_vfdScopedBlock));
  SelectionTool *tool = getTool();
  VectorFreeDeformer *deformer =
      dynamic_cast<VectorFreeDeformer *>(tool->getFreeDeformer());
  if (!deformer) return;
  deformer->setComputeRegion(true);
  deformer->setFlip(isFlip());
  deformer->deformRegions();
  if (!tool->isLevelType() && !tool->isSelectedFramesType())
    addTransformUndo();
  else
    transformWholeLevel();
  m_isDragging = false;
  tool->notifyImageChanged();
  VectorSelectionTool *selectionTool =
      dynamic_cast<VectorSelectionTool *>(m_tool);
  selectionTool->setResetCenter(true);
}
transformWholeLevel()
void DragSelectionTool::VectorDeformTool::transformWholeLevel ()
Transform whole level and add undo.
{
  VectorSelectionTool *tool = dynamic_cast<VectorSelectionTool *>(m_tool);
  assert(tool);
  assert(!tool->levelSelection().isEmpty());
  TXshSimpleLevel *level =
      TTool::getApplication()->getCurrentLevel()->getSimpleLevel();
  std::vector<TFrameId> fids;
  level->getFids(fids);
  // Remove unwanted fids
  fids.erase(std::remove_if(
                 fids.begin(), fids.end(),
                 boost::bind(::currentOrNotSelected, boost::cref(*tool), _1)),
             fids.end());
  TUndoManager::manager()->beginBlock();
  {
    addTransformUndo();  // For current frame
    int f, fCount = int(fids.size());
    for (f = 0; f != fCount; ++f) {
      const TFrameId &fid = fids[f];
      int t               = f + 1;  // Current frame's data is always at index 0
                                    // The others are thus shifted by 1
      // Skip nonselected frames
      if (tool->getCurrentFid() == fid ||
          (tool->isSelectedFramesType() &&
           tool->getSelectedFrames().count(fid) == 0))
        continue;
      TVectorImageP vi = level->getFrame(fid, true);
      if (!vi) continue;
      std::unique_ptr<UndoChangeStrokes> undo(
          new UndoChangeStrokes(level, fid, tool, tool->levelSelection()));
      std::set<int> strokesIndices;
      for (int s = 0; s < (int)vi->getStrokeCount(); ++s)
        strokesIndices.insert(s);
      FourPoints bbox = tool->getBBox(t);
      VectorFreeDeformer *freeDeformer =
          static_cast<VectorFreeDeformer *>(tool->getFreeDeformer(t));
      freeDeformer->setPoints(bbox.getPoint(0), bbox.getPoint(1),
                              bbox.getPoint(2), bbox.getPoint(3));
      freeDeformer->setComputeRegion(true);
      freeDeformer->setPreserveThickness(tool->isConstantThickness());
      freeDeformer->setFlip(isFlip());
      freeDeformer->deformImage();
      undo->registerStrokes();
      TUndoManager::manager()->add(undo.release());
    }
  }
  TUndoManager::manager()->endBlock();
  // Finally, notify changed frames
  std::for_each(fids.begin(), fids.end(),
                boost::bind(  // NOTE: current frame is not here - it should be,
                    &TTool::notifyImageChanged, m_tool,
                    _1));  //       but it's currently unnecessary, in fact...
  // notifyImageChanged(fid) must be invoked OUTSIDE of the loop - since it
  // seems to imply notifyImageChanged()
  // on CURRENT image - which seems wrong, but it's too low-level and I'm not
  // changing it.
  // This reasonably leads to computeBBox(), but bboxes are taken as INPUT to
  // this transformation...            >:(
}
References TTool::getCurrentFid(), TXshSimpleLevel::getFids(), DragSelectionTool::FourPoints::getPoint(), LevelSelection::isEmpty(), TTool::notifyImageChanged(), and VectorFreeDeformer::setPoints().
Member Data Documentation
m_undo
std::unique_ptr<UndoChangeStrokes> DragSelectionTool::VectorDeformTool::m_undo protected
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/tnztools/vectorselectiontool.h
E:/opentoonz/toonz/sources/tnztools/vectorselectiontool.cpp