opentoonz: ControlPointEditorStroke Class Reference
ControlPointEditorStroke Class Reference
Public Types
enum PointType {
CONTROL_POINT , SPEED_IN , SPEED_OUT , SEGMENT ,
NONE
}
Public Member Functions
ControlPointEditorStroke * clone () const
bool setStroke (const TVectorImageP &vi, int strokeIndex)
TStroke * getStroke () const
void setStrokeIndex (int strokeIndex)
int getStrokeIndex () const
int getControlPointCount () const
TThickPoint getControlPoint (int index) const
int getIndexPointInStroke (int index) const
TThickPoint getSpeedInPoint (int index) const
TThickPoint getSpeedOutPoint (int index) const
bool isCusp (int index) const
Return true if index point is a cusp.
void setCusp (int index, bool isCusp, bool setSpeedIn)
Set m_isCusp of index point to isCusp.
bool isSpeedInLinear (int index) const
bool isSpeedOutLinear (int index) const
void setLinearSpeedIn (int index, bool linear=true, bool updatePoints=true)
void setLinearSpeedOut (int index, bool linear=true, bool updatePoints=true)
bool setLinear (int index, bool isLinear, bool updatePoints=true)
bool setControlPointsLinear (std::set< int > points, bool isLinear)
void moveControlPoint (int index, const TPointD &delta)
int addControlPoint (const TPointD &pos)
void deleteControlPoint (int index)
void moveSpeed (int index, const TPointD &delta, bool isIn, double minDistance)
void moveSegment (int beforeIndex, int nextIndex, const TPointD &delta, const TPointD &pos)
PointType getPointTypeAt (const TPointD &pos, double &distance2, int &index) const
bool isSelfLoop () const
Detailed Description
Member Enumeration Documentation
PointType
enum ControlPointEditorStroke::PointType
{ CONTROL_POINT, SPEED_IN, SPEED_OUT, SEGMENT, NONE };
Constructor & Destructor Documentation
ControlPointEditorStroke()
ControlPointEditorStroke::ControlPointEditorStroke () inline
: m_vi() {}
~ControlPointEditorStroke()
ControlPointEditorStroke::~ControlPointEditorStroke () inline
{ m_controlPoints.clear(); }
Member Function Documentation
addControlPoint()
int ControlPointEditorStroke::addControlPoint (const TPointD & pos)
Add a ControlPoint in point. Return added ControlPoint index.
{
  TStroke *stroke = getStroke();
  if (!stroke) return -1;
  double d = 0.01;
  int indexAtPos;
  int cpCount = stroke->getControlPointCount();
  if (cpCount <= 3)  // e' un unico chunk e in questo caso rappresenta un punto
  {
    getPointTypeAt(pos, d, indexAtPos);
    return indexAtPos;
  }
  double w       = stroke->getW(pos);
  int pointIndex = stroke->getControlPointIndexAfterParameter(w);
  int i, index;
  for (i = 0; i < getControlPointCount(); i++) {
    // Cerco il ControlPoint corrispondente all'indice pointIndex. OSS.:
    // Effettuo il
    // controllo da zero a getControlPointCount()-1 per gestire il caso del
    // selfLoop
    if (pointIndex == m_controlPoints[i].m_pointIndex + 1 ||
        pointIndex == m_controlPoints[i].m_pointIndex + 2 ||
        pointIndex == m_controlPoints[i].m_pointIndex + 3 ||
        pointIndex == m_controlPoints[i].m_pointIndex + 4)
      index = i;
  }
  ControlPoint precCp = m_controlPoints[index];
  assert(precCp.m_pointIndex >= 0);
  std::vector<TThickPoint> points;
  for (i = 0; i < cpCount; i++) {
    if (i != precCp.m_pointIndex + 1 && i != precCp.m_pointIndex + 2 &&
        i != precCp.m_pointIndex + 3)
      points.push_back(stroke->getControlPoint(i));
    if (i == precCp.m_pointIndex + 2) {
      bool isBeforePointLinear = isSpeedOutLinear(index);
      int nextIndex =
          (isSelfLoop() && index == m_controlPoints.size() - 1) ? 0 : index + 1;
      bool isNextPointLinear =
          nextIndex < (int)m_controlPoints.size() && isSpeedInLinear(nextIndex);
      TThickPoint a0 = stroke->getControlPoint(precCp.m_pointIndex);
      TThickPoint a1 = stroke->getControlPoint(precCp.m_pointIndex + 1);
      TThickPoint a2 = stroke->getControlPoint(precCp.m_pointIndex + 2);
      TThickPoint a3 = stroke->getControlPoint(precCp.m_pointIndex + 3);
      TThickPoint a4 = stroke->getControlPoint(precCp.m_pointIndex + 4);
      double dist2   = tdistance2(pos, TPointD(a2));
      TThickPoint d0, d1, d2, d3, d4, d5, d6;
      if (isBeforePointLinear && isNextPointLinear) {
        // Se sono entrambi i punti lineari  inserisco un punto lineare
        d0 = a1;
        d3 = stroke->getThickPoint(w);
        d6 = a3;
        d2 = computeLinearPoint(d0, d3, 0.01, true);   // SpeedIn
        d4 = computeLinearPoint(d3, d6, 0.01, false);  // SpeedOut
        d1 = 0.5 * (d0 + d2);
        d5 = 0.5 * (d4 + d6);
      } else if (dist2 < 32) {
        // Sono molto vicino al punto che non viene visualizzato
        TThickPoint b0 = 0.5 * (a0 + a1);
        TThickPoint b1 = 0.5 * (a2 + a1);
        TThickPoint c0 = 0.5 * (b0 + b1);
        TThickPoint b2 = 0.5 * (a2 + a3);
        TThickPoint b3 = 0.5 * (a3 + a4);
        TThickPoint c1 = 0.5 * (b2 + b3);
        d0             = b0;
        d1             = c0;
        d2             = b1;
        d3             = a2;
        d4             = b2;
        d5             = c1;
        d6             = b3;
      } else {
        bool isInFirstChunk = true;
        if (pointIndex > precCp.m_pointIndex + 2) {
          // nel caso in cui sono nel secondo chunk scambio i punti
          a0 = a4;
          std::swap(a1, a3);
          isInFirstChunk = false;
        }
        double w0 = (isSelfLoop() && precCp.m_pointIndex + 4 == cpCount - 1 &&
                     !isInFirstChunk)
                        ? 1
                        : stroke->getW(a0);
        double w1 = stroke->getW(a2);
        double t  = (w - w0) / (w1 - w0);
        TThickPoint p  = stroke->getThickPoint(w);
        TThickPoint b0 = TThickPoint((1 - t) * a0 + t * a1,
                                     (1 - t) * a0.thick + t * a1.thick);
        TThickPoint b1 = TThickPoint((1 - t) * a1 + t * a2,
                                     (1 - t) * a1.thick + t * a2.thick);
        TThickPoint c0 =
            TThickPoint(0.5 * a0 + 0.5 * b0, (1 - t) * a0.thick + t * b0.thick);
        TThickPoint c1 =
            TThickPoint(0.5 * b0 + 0.5 * p, (1 - t) * b0.thick + t * p.thick);
        TThickPoint c2 =
            TThickPoint(0.5 * c0 + 0.5 * c1, (1 - t) * c0.thick + t * c1.thick);
        d0 = (isInFirstChunk) ? c0 : a3;
        d1 = (isInFirstChunk) ? c2 : a2;
        d2 = (isInFirstChunk) ? c1 : b1;
        d3 = p;
        d4 = (isInFirstChunk) ? b1 : c1;
        d5 = (isInFirstChunk) ? a2 : c2;
        d6 = (isInFirstChunk) ? a3 : c0;
      }
      if (isBeforePointLinear && !isNextPointLinear)
        d1 = computeLinearPoint(d0, d2, 0.01, false);
      else if (isNextPointLinear && !isBeforePointLinear)
        d5 = computeLinearPoint(d4, d6, 0.01, true);
      points.push_back(d0);
      points.push_back(d1);
      points.push_back(d2);
      points.push_back(d3);
      points.push_back(d4);
      points.push_back(d5);
      points.push_back(d6);
    }
  }
  stroke->reshape(&points[0], points.size());
  resetControlPoints();
  getPointTypeAt(pos, d, indexAtPos);
  return indexAtPos;
}
References TStroke::getControlPoint(), TStroke::getControlPointCount(), getPointTypeAt(), TStroke::getThickPoint(), TStroke::getW(), and TStroke::reshape().
clone()
ControlPointEditorStroke * ControlPointEditorStroke::clone () const
{
  ControlPointEditorStroke *controlPointEditorStroke =
      new ControlPointEditorStroke();
  controlPointEditorStroke->setStroke(m_vi->clone(), m_strokeIndex);
  return controlPointEditorStroke;
}
deleteControlPoint()
void ControlPointEditorStroke::deleteControlPoint (int index)
{
  TStroke *stroke = getStroke();
  if (!stroke) return;
  assert(stroke && 0 <= index && index < (int)getControlPointCount());
  // E' un unico chunk e in questo caso rappresenta un punto
  if (stroke->getControlPointCount() <= 3 ||
      (isSelfLoop() && stroke->getControlPointCount() <= 5)) {
    m_controlPoints.clear();
    m_vi->deleteStroke(m_strokeIndex);
    return;
  }
  QList<int> newPointsIndex;
  int i;
  for (i = 0; i < (int)getControlPointCount() - 1; i++)
    newPointsIndex.push_back(m_controlPoints[i].m_pointIndex);
  m_controlPoints.removeAt(index);
  updatePoints();
  // Aggiorno gli indici dei punti nella stroke
  assert((int)newPointsIndex.size() == (int)getControlPointCount());
  for (i = 0; i < (int)getControlPointCount(); i++)
    m_controlPoints[i].m_pointIndex = newPointsIndex.at(i);
  int prev = prevIndex(index);
  if (prev >= 0 && isSpeedOutLinear(prev)) {
    setLinearSpeedOut(prev);
    updateDependentPoint(prev);
  }
  if (index < (int)m_controlPoints.size() && isSpeedInLinear(index)) {
    setLinearSpeedIn(index);
    updateDependentPoint(index);
  }
}
getControlPoint()
TThickPoint ControlPointEditorStroke::getControlPoint (int index) const
{
  TStroke *stroke = getStroke();
  assert(stroke && 0 <= index && index < (int)m_controlPoints.size());
  return stroke->getControlPoint(m_controlPoints[index].m_pointIndex);
}
getControlPointCount()
int ControlPointEditorStroke::getControlPointCount () const inline
{ return m_controlPoints.size(); }
getIndexPointInStroke()
int ControlPointEditorStroke::getIndexPointInStroke (int index) const
From index point in ControlPointEditorStroke to index point in TStroke.
{
  return m_controlPoints[index].m_pointIndex;
}
getPointTypeAt()
ControlPointEditorStroke::PointType ControlPointEditorStroke::getPointTypeAt (const TPointD & pos, double & distance2, int & index) const
Return NONE if pos is far from stroke.
{
  TStroke *stroke = getStroke();
  if (!stroke) return NONE;
  double w              = stroke->getW(pos);
  TPointD p             = stroke->getPoint(w);
  double strokeDistance = tdistance2(p, pos);
  int precPointIndex     = -1;
  double minPrecDistance = 0;
  double minDistance2    = distance2;
  index                  = -1;
  PointType type         = NONE;
  int cpCount            = m_controlPoints.size();
  int i;
  for (i = 0; i < cpCount; i++) {
    ControlPoint cPoint = m_controlPoints[i];
    TPointD point       = stroke->getControlPoint(cPoint.m_pointIndex);
    double cpDistance2  = tdistance2(pos, point);
    double distanceIn2  = !isSpeedInLinear(i)
                             ? tdistance2(pos, point - cPoint.m_speedIn)
                             : cpDistance2 + 1;
    double distanceOut2 = !isSpeedOutLinear(i)
                              ? tdistance2(pos, point + cPoint.m_speedOut)
                              : cpDistance2 + 1;
    if (i == 0 && !isSelfLoop())
      distanceIn2 = std::max(cpDistance2, distanceOut2) + 1;
    if (i == cpCount - 1 && !isSelfLoop())
      distanceOut2 = std::max(cpDistance2, distanceIn2) + 1;
    if (cpDistance2 < distanceIn2 && cpDistance2 < distanceOut2 &&
        (cpDistance2 < minDistance2 || index < 0)) {
      minDistance2 = cpDistance2;
      index        = i;
      type         = CONTROL_POINT;
    } else if (distanceIn2 < cpDistance2 && distanceIn2 < distanceOut2 &&
               (distanceIn2 < minDistance2 || index < 0)) {
      minDistance2 = distanceIn2;
      index        = i;
      type         = SPEED_IN;
    } else if (distanceOut2 < cpDistance2 && distanceOut2 < distanceIn2 &&
               (distanceOut2 < minDistance2 || index < 0)) {
      minDistance2 = distanceOut2;
      index        = i;
      type         = SPEED_OUT;
    }
    double cpw =
        stroke->getParameterAtControlPoint(m_controlPoints[i].m_pointIndex);
    if (w <= cpw) continue;
    double precDistance = w - cpw;
    if (precPointIndex < 0 || precDistance < minPrecDistance) {
      precPointIndex  = i;
      minPrecDistance = precDistance;
    }
  }
  if (minDistance2 < distance2)
    distance2 = minDistance2;
  else if (strokeDistance > distance2) {
    distance2 = strokeDistance;
    index     = -1;
    type      = NONE;
  } else {
    distance2 = minPrecDistance;
    index     = precPointIndex;
    type      = SEGMENT;
  }
  return type;
}
References TStroke::getControlPoint(), TStroke::getParameterAtControlPoint(), TStroke::getPoint(), and TStroke::getW().
Referenced by addControlPoint().
getSpeedInPoint()
TThickPoint ControlPointEditorStroke::getSpeedInPoint (int index) const
{
  TStroke *stroke = getStroke();
  assert(stroke && 0 <= index && index < (int)m_controlPoints.size());
  ControlPoint cp = m_controlPoints[index];
  return stroke->getControlPoint(cp.m_pointIndex) - cp.m_speedIn;
}
getSpeedOutPoint()
TThickPoint ControlPointEditorStroke::getSpeedOutPoint (int index) const
{
  TStroke *stroke = getStroke();
  assert(stroke && 0 <= index && index < (int)m_controlPoints.size());
  ControlPoint cp = m_controlPoints[index];
  return stroke->getControlPoint(cp.m_pointIndex) + cp.m_speedOut;
}
getStroke()
TStroke * ControlPointEditorStroke::getStroke () const inline
{
    return m_vi ? m_vi->getStroke(m_strokeIndex) : 0;
  }
getStrokeIndex()
int ControlPointEditorStroke::getStrokeIndex () const inline
{ return m_strokeIndex; }
isCusp()
bool ControlPointEditorStroke::isCusp (int index) const
Return true if index point is a cusp.
{
  TStroke *stroke = getStroke();
  assert(stroke && 0 <= index && index < (int)getControlPointCount());
  return m_controlPoints[index].m_isCusp;
}
Referenced by moveSegment(), and setCusp().
isSelfLoop()
bool ControlPointEditorStroke::isSelfLoop () const inline
{
    TStroke *stroke = getStroke();
    return stroke && stroke->isSelfLoop();
  }
isSpeedInLinear()
bool ControlPointEditorStroke::isSpeedInLinear (int index) const
{
  assert(index < (int)m_controlPoints.size());
  return (fabs(m_controlPoints[index].m_speedIn.x) <= 0.02) &&
         (fabs(m_controlPoints[index].m_speedIn.y) <= 0.02);
}
isSpeedOutLinear()
bool ControlPointEditorStroke::isSpeedOutLinear (int index) const
{
  assert(index < (int)m_controlPoints.size());
  return (fabs(m_controlPoints[index].m_speedOut.x) <= 0.02) &&
         (fabs(m_controlPoints[index].m_speedOut.y) <= 0.02);
}
moveControlPoint()
void ControlPointEditorStroke::moveControlPoint (int index, const TPointD & delta)
Move index ControlPoint of delta.
{
  TStroke *stroke = getStroke();
  if (!stroke) return;
  assert(stroke && 0 <= index && index < (int)getControlPointCount());
  moveSingleControlPoint(index, delta);
  updateDependentPoint(index);
}
moveSegment()
void ControlPointEditorStroke::moveSegment (int beforeIndex, int nextIndex, const TPointD & delta, const TPointD & pos)
Move segment between beforeIndex and nextIndex of delta.
{
  TStroke *stroke = getStroke();
  if (!stroke) return;
  int cpCount = getControlPointCount();
  // Verifiche per il caso in cui lo stroke e' selfLoop
  if (isSelfLoop() && beforeIndex == 0 && nextIndex == cpCount - 1)
    std::swap(beforeIndex, nextIndex);
  int beforePointIndex = m_controlPoints[beforeIndex].m_pointIndex;
  int nextPointIndex   = (isSelfLoop() && nextIndex == 0)
                           ? stroke->getControlPointCount() - 1
                           : m_controlPoints[nextIndex].m_pointIndex;
  double w  = stroke->getW(pos);
  double w0 = stroke->getParameterAtControlPoint(beforePointIndex);
  double w4 = stroke->getParameterAtControlPoint(nextPointIndex);
  if (w0 > w) return;
  assert(w0 <= w && w <= w4);
  double t = 1;
  double s = 1;
  if (isSpeedOutLinear(beforeIndex)) {
    m_controlPoints[beforeIndex].m_speedOut =
        (stroke->getControlPoint(nextPointIndex) -
         stroke->getControlPoint(beforePointIndex)) *
        0.3;
    if (!isSpeedInLinear(beforeIndex))
      m_controlPoints[beforeIndex].m_isCusp = true;
  } else if (!isSpeedOutLinear(beforeIndex) && !isSpeedInLinear(beforeIndex) &&
             !isCusp(beforeIndex)) {
    t = 1 - fabs(w - w0) / fabs(w4 - w0);
    moveSingleControlPoint(beforeIndex, t * delta);
    t = 1 - t;
  }
  if (isSpeedInLinear(nextIndex)) {
    m_controlPoints[nextIndex].m_speedIn =
        (stroke->getControlPoint(nextPointIndex) -
         stroke->getControlPoint(beforePointIndex)) *
        0.3;
    if (!isSpeedOutLinear(nextIndex))
      m_controlPoints[nextIndex].m_isCusp = true;
  } else if (!isSpeedInLinear(nextIndex) && !isSpeedOutLinear(nextIndex) &&
             !isCusp(nextIndex)) {
    s = 1 - fabs(w4 - w) / fabs(w4 - w0);
    moveSingleControlPoint(nextIndex, s * delta);
    s = 1 - s;
  }
  moveSpeedOut(beforeIndex, delta * s, 0);
  // updateDependentPoint(beforeIndex);
  moveSpeedIn(nextIndex, delta * t, 0);
  // updateDependentPoint(nextIndex);
  updatePoints();
}
References TStroke::getControlPoint(), TStroke::getControlPointCount(), TStroke::getParameterAtControlPoint(), TStroke::getW(), and isCusp().
moveSpeed()
void ControlPointEditorStroke::moveSpeed (int index, const TPointD & delta, bool isIn, double minDistance)
Move speed in index of delta.
{
  if (!isIn)
    moveSpeedOut(index, delta, minDistance);
  else
    moveSpeedIn(index, delta, minDistance);
  updateDependentPoint(index);
}
Referenced by setCusp().
setControlPointsLinear()
bool ControlPointEditorStroke::setControlPointsLinear (std::set< int > points, bool isLinear)
{
  std::set<int>::iterator it;
  bool isChanged = false;
  for (it = points.begin(); it != points.end(); it++)
    isChanged = setLinear(*it, isLinear, false) || isChanged;
  for (it = points.begin(); it != points.end(); it++) updateDependentPoint(*it);
  return isChanged;
}
setCusp()
void ControlPointEditorStroke::setCusp (int index, bool isCusp, bool setSpeedIn)
Set m_isCusp of index point to isCusp.
If isCusp == false check setSpeedIn and modify speed.
{
  m_controlPoints[index].m_isCusp = isCusp;
  if (isCusp == true) return;
  moveSpeed(index, TPointD(0.0, 0.0), setSpeedIn, 0.0);
}
References isCusp(), and moveSpeed().
setLinear()
bool ControlPointEditorStroke::setLinear (int index, bool isLinear, bool updatePoints = true)
If isLinear==true set to "0" the speedIn and speedOut value of index point; otherwise set to default value. Return true if speedIn or speedOut is modified. If updatePoints is true update dependent point after.
{
  bool movePrec = (!isSelfLoop()) ? index > 0 : true;
  bool moveNext = (!isSelfLoop()) ? (index < getControlPointCount() - 1) : true;
  if (isLinear != isSpeedInLinear(index))
    setLinearSpeedIn(index, isLinear, updatePoints);
  else
    movePrec = false;
  if (isLinear != isSpeedOutLinear(index))
    setLinearSpeedOut(index, isLinear, updatePoints);
  else
    moveNext = false;
  bool ret = moveNext || movePrec;
  if (ret) m_controlPoints[index].m_isCusp = true;
  return ret;
}
setLinearSpeedIn()
void ControlPointEditorStroke::setLinearSpeedIn (int index, bool linear = true, bool updatePoints = true)
{
  TStroke *stroke = getStroke();
  if (!stroke || m_controlPoints.size() == 1) return;
  int pointIndex = m_controlPoints[index].m_pointIndex;
  if (pointIndex == 0) {
    if (isSelfLoop())
      pointIndex = stroke->getControlPointCount() - 1;
    else
      return;
  }
  int precIndex =
      (index == 0 && isSelfLoop()) ? m_controlPoints.size() - 1 : index - 1;
  TThickPoint point     = stroke->getControlPoint(pointIndex);
  TThickPoint precPoint = (pointIndex > 2)
                              ? stroke->getControlPoint(pointIndex - 3)
                              : TThickPoint();
  if (linear) {
    TThickPoint p(point - precPoint);
    double n = norm(p);
    TThickPoint speedIn =
        (n != 0.0) ? (0.01 / n) * p : TThickPoint(0.001, 0.001, 0.0);
    m_controlPoints[index].m_speedIn = speedIn;
  } else {
    TThickPoint newPrec2             = (precPoint + point) * 0.5;
    TThickPoint speedIn              = (point - newPrec2) * 0.5;
    m_controlPoints[index].m_speedIn = speedIn;
  }
  if (updatePoints) updateDependentPoint(index);
}
setLinearSpeedOut()
void ControlPointEditorStroke::setLinearSpeedOut (int index, bool linear = true, bool updatePoints = true)
{
  TStroke *stroke = getStroke();
  if (!stroke || m_controlPoints.size() == 1) return;
  int cpCount    = stroke->getControlPointCount();
  int pointIndex = m_controlPoints[index].m_pointIndex;
  if (pointIndex == cpCount - 1) {
    if (isSelfLoop())
      pointIndex = 0;
    else
      return;
  }
  int nextIndex =
      (index == m_controlPoints.size() - 1 && isSelfLoop()) ? 0 : index + 1;
  TThickPoint point     = stroke->getControlPoint(pointIndex);
  TThickPoint nextPoint = (pointIndex < cpCount - 3)
                              ? stroke->getControlPoint(pointIndex + 3)
                              : TThickPoint();
  if (linear) {
    TThickPoint p(nextPoint - point);
    double n = norm(p);
    TThickPoint speedOut =
        (n != 0.0) ? (0.01 / n) * p : TThickPoint(0.001, 0.001, 0.0);
    m_controlPoints[index].m_speedOut = speedOut;
  } else {
    TThickPoint newNext2              = (nextPoint + point) * 0.5;
    TThickPoint speedOut              = (newNext2 - point) * 0.5;
    m_controlPoints[index].m_speedOut = speedOut;
  }
  if (updatePoints) updateDependentPoint(index);
}
setStroke()
bool ControlPointEditorStroke::setStroke (const TVectorImageP & vi, int strokeIndex)
Modify stroke: between two linear or cusp point must be a pair chunk number. PAY ATTENTION: Can add control point in the stroke.
{
  bool ret = true;
  if (m_strokeIndex == strokeIndex && m_vi == vi) ret = false;
  m_strokeIndex = strokeIndex;
  m_vi          = vi;
  if (!vi || strokeIndex == -1) {
    m_controlPoints.clear();
    return true;
  }
  TStroke *stroke              = getStroke();
  const TThickQuadratic *chunk = stroke->getChunk(0);
  if (stroke->getControlPointCount() == 3 && chunk->getP0() == chunk->getP1() &&
      chunk->getP0() == chunk->getP2()) {
    resetControlPoints();
    return ret;
  }
  adjustChunkParity();
  resetControlPoints();
  return ret;
}
References TStroke::getChunk(), TStroke::getControlPointCount(), TQuadratic::getP0(), TQuadratic::getP1(), and TQuadratic::getP2().
Referenced by ControlPointEditorTool::draw(), ControlPointEditorTool::onActivate(), and ControlPointEditorTool::onImageChanged().
setStrokeIndex()
void ControlPointEditorStroke::setStrokeIndex (int strokeIndex) inline
{ m_strokeIndex = strokeIndex; }
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/tnztools/controlpointselection.h
E:/opentoonz/toonz/sources/tnztools/controlpointselection.cpp