opentoonz: TThickPoint Class Reference
TThickPoint Class Reference final
#include <tgeometry.h>
Public Member Functions
TThickPoint (double _x, double _y, double _thick=0)
TThickPoint (const TPointD &_p, double _thick=0)
TThickPoint (const T3DPointD &_p)
TThickPoint (const TThickPoint &_p)
TThickPoint & operator= (const TThickPoint &a)
TThickPoint & operator+= (const TThickPoint &a)
TThickPoint & operator-= (const TThickPoint &a)
TThickPoint operator+ (const TThickPoint &a) const
TThickPoint operator- (const TThickPoint &a) const
TThickPoint operator- () const
bool operator== (const TThickPoint &p) const
bool operator!= (const TThickPoint &p) const
Public Member Functions inherited from TPointT< double >
TPointT (double _x, double _y)
TPointT (const TPointT &point)
TPointT & operator= (const TPointT &a)
TPointT & operator+= (const TPointT &a)
TPointT & operator-= (const TPointT &a)
TPointT operator+ (const TPointT &a) const
TPointT operator- (const TPointT &a) const
TPointT operator- () const
bool operator!= (const TPointT &p) const
Public Attributes
double thick
Public Attributes inherited from TPointT< double >
double x
double y
Related Functions
(Note that these are not member functions.)
double tdistance2 (const TThickPoint &p1, const TThickPoint &p2)
double tdistance (const TThickPoint &p1, const TThickPoint &p2)
Related Functions inherited from TPointT< double >
TPointT< double > rotate90 (const TPointT< double > &p)
TPointT< double > rotate270 (const TPointT< double > &p)
double operator* (const TPointT< double > &a, const TPointT< double > &b)
TPoint operator* (int a, const TPoint &p)
TPoint operator* (const TPoint &p, int a)
TPointD operator* (double a, const TPointD &p)
TPointD operator* (const TPointD &p, double a)
T3DPointT< double > operator* (const T3DPointT< double > &p, double a)
int norm2 (const TPointI &p)
double norm2 (const TPointD &p)
double norm2 (const T3DPointT< double > &p)
double norm (const TPointD &p)
TPointD normalize (const TPointD &p)
TPointD convert (const TPoint &p)
TPoint convert (const TPointD &p)
double tdistance2 (const TPointD &p1, const TPointD &p2)
double tdistance (const TPointD &p1, const TPointD &p2)
double cross (const TPointD &a, const TPointD &b)
TRectD boundingBox (const TPointD &p0, const TPointD &p1)
TRectD boundingBox (const TPointD &p0, const TPointD &p1, const TPointD &p2)
TRectD boundingBox (const TPointD &p0, const TPointD &p1, const TPointD &p2, const TPointD &p3)
Detailed Description
TThickPoint describe a thick point. , TThickCubic
Constructor & Destructor Documentation
TThickPoint() [1/5]
TThickPoint::TThickPoint () inline
: TPointD(), thick(0) {}
TThickPoint() [2/5]
TThickPoint::TThickPoint (double _x, double _y, double _thick = 0) inline
      : TPointD(_x, _y), thick(_thick) {}
TThickPoint() [3/5]
TThickPoint::TThickPoint (const TPointD & _p, double _thick = 0) inline
      : TPointD(_p.x, _p.y), thick(_thick) {}
TThickPoint() [4/5]
TThickPoint::TThickPoint (const T3DPointD & _p) inline
: TPointD(_p.x, _p.y), thick(_p.z) {}
TThickPoint() [5/5]
TThickPoint::TThickPoint (const TThickPoint & _p) inline
: TPointD(_p.x, _p.y), thick(_p.thick) {}
Member Function Documentation
operator!=()
bool TThickPoint::operator!= (const TThickPoint & p) const inline
{
    return x != p.x || y != p.y || thick != p.thick;
  }
operator+()
TThickPoint TThickPoint::operator+ (const TThickPoint & a) const inline
{
    return TThickPoint(x + a.x, y + a.y, thick + a.thick);
  }
operator+=()
TThickPoint & TThickPoint::operator+= (const TThickPoint & a) inline
{
    x += a.x;
    y += a.y;
    thick += a.thick;
    return *this;
  }
operator-() [1/2]
TThickPoint TThickPoint::operator- () const inline
{ return TThickPoint(-x, -y, -thick); }
operator-() [2/2]
TThickPoint TThickPoint::operator- (const TThickPoint & a) const inline
{
    return TThickPoint(x - a.x, y - a.y, thick - a.thick);
  }
operator-=()
TThickPoint & TThickPoint::operator-= (const TThickPoint & a) inline
{
    x -= a.x;
    y -= a.y;
    thick -= a.thick;
    return *this;
  }
operator=()
TThickPoint & TThickPoint::operator= (const TThickPoint & a) inline
{
    x     = a.x;
    y     = a.y;
    thick = a.thick;
    return *this;
  }
operator==()
bool TThickPoint::operator== (const TThickPoint & p) const inline
{
    return x == p.x && y == p.y && thick == p.thick;
  }
Friends And Related Function Documentation
tdistance()
double tdistance (const TThickPoint & p1, const TThickPoint & p2) related
This helper function returns the distance between two thick points (only x and y are used)
{
  return norm(convert(p2 - p1));
}
References TPointT< T >::convert(), and TPointT< T >::norm().
tdistance2()
double tdistance2 (const TThickPoint & p1, const TThickPoint & p2) related
This helper function returns the square of the distance between two thick points (only x and y are used)
{
  return norm2(convert(p2 - p1));
}
References TPointT< T >::convert(), and TPointT< T >::norm2().
Member Data Documentation
thick
double TThickPoint::thick
The documentation for this class was generated from the following file:
E:/opentoonz/toonz/sources/include/tgeometry.h