opentoonz: DVGui::ColorField Class Reference
DVGui::ColorField Class Reference final
The ColorField class is used to view an object to manage a color.
Classes
class ColorFieldEditorController
Signals
void editingChanged (const TPixel32 &, bool isEditing)
void colorChanged (const TPixel32 &, bool isDragging)
Public Member Functions
ColorField (QWidget *parent=0, bool isAlphaActive=true, TPixel32 color=TPixel32(0, 0, 0, 255), int squareSize=40, bool useStyleEditor=true, int sliderWidth=-1)
void setColor (const TPixel32 &color)
TPixel32 getColor () const
void setChessboardColors (const TPixel32 &col1, const TPixel32 &col2)
void notifyColorChanged (const TPixel32 &color, bool isDragging)
void setEditingChangeNotified (bool notify)
void setIsEditing (bool isEditing)
bool isEditing () const
void hideChannelsFields (bool hide)
void setAlphaActive (bool active)
Static Public Member Functions
static void setEditorController (ColorFieldEditorController *editorController)
static ColorFieldEditorController * getEditorController ()
Static Public Attributes
static ColorFieldEditorController * m_editorController = 0
Protected Slots
void onRedChannelChanged (int value, bool isDragging)
void onGreenChannelChanged (int value, bool isDragging)
void onBlueChannelChanged (int value, bool isDragging)
void onAlphaChannelChanged (int value, bool isDragging)
void onPasteColor ()
void onCopyColor ()
Protected Member Functions
void updateChannels ()
void mousePressEvent (QMouseEvent *event) override
void mouseDoubleClickEvent (QMouseEvent *event) override
void hideEvent (QHideEvent *) override
void contextMenuEvent (QContextMenuEvent *event) override
Detailed Description
The ColorField class is used to view an object to manage a color.
         Inherits \b QWidget.
         The object is composed of a horizontal layout \b QHBoxLayout
which contains a StyleSample, and three or four ChannelField, it depend if transparency is count, to manage color channel. You can pass to constructor current color value, getColor(), or set it calling setColor(). You can also pass to constructor a boolean to know if manage transparency channel or not, and an integer for StyleSample size.
         To know when color value change class provides a signal,
colorChanged(const TPixel32 &); class emit signal when one ChannelField value change. See SLOT: onRedChannelChanged(int value), onGreenChannelChanged(int value), onBlueChannelChanged(int value) and onAlphaChannelChanged(int value) to know when signal is emitted.
Example: initialize a ColorField with transparency channel.
                     ColorField* colorFld = new
ColorField(0,true,TPixel32(0,0,255,255),50);
Result:
Constructor & Destructor Documentation
ColorField()
ColorField::ColorField (QWidget * parent = 0, bool isAlphaActive = true, TPixel32 color = TPixel32(0, 0, 0, 255), int squareSize = 40, bool useStyleEditor = true, int sliderWidth = -1)
    : QWidget(parent)
    , m_color(color)
    , m_notifyEditingChange(true)
    , m_useStyleEditor(useStyleEditor) {
  setMaximumHeight(squareSize);
  QHBoxLayout *layout = new QHBoxLayout(this);
  layout->setMargin(0);
  layout->setSpacing(5);
  layout->setSizeConstraint(QLayout::SetFixedSize);
  int h = WidgetHeight;
  m_colorSample = new StyleSample(this, squareSize, squareSize);
  m_colorSample->setColor(m_color);
  m_redChannel =
      new ChannelField(this, tr("R:"), m_color.r, 255, false, 13, sliderWidth);
  connect(m_redChannel, SIGNAL(valueChanged(int, bool)),
          SLOT(onRedChannelChanged(int, bool)));
  m_greenChannel =
      new ChannelField(this, tr("G:"), m_color.g, 255, false, 13, sliderWidth);
  connect(m_greenChannel, SIGNAL(valueChanged(int, bool)),
          SLOT(onGreenChannelChanged(int, bool)));
  m_blueChannel =
      new ChannelField(this, tr("B:"), m_color.b, 255, false, 13, sliderWidth);
  connect(m_blueChannel, SIGNAL(valueChanged(int, bool)),
          SLOT(onBlueChannelChanged(int, bool)));
  m_alphaChannel =
      new ChannelField(this, tr("A:"), m_color.m, 255, false, 13, sliderWidth);
  connect(m_alphaChannel, SIGNAL(valueChanged(int, bool)),
          SLOT(onAlphaChannelChanged(int, bool)));
  layout->addWidget(m_colorSample);
  layout->addWidget(m_redChannel);
  layout->addWidget(m_greenChannel);
  layout->addWidget(m_blueChannel);
  layout->addWidget(m_alphaChannel);
  if (!isAlphaActive) m_alphaChannel->hide();
  setLayout(layout);
}
~ColorField()
DVGui::ColorField::~ColorField () inline
{}
Member Function Documentation
colorChanged
void DVGui::ColorField::colorChanged (const TPixel32 & , bool isDragging) signal
This signal is emitted when a channel value of current color change.
Referenced by onAlphaChannelChanged(), onBlueChannelChanged(), onGreenChannelChanged(), onRedChannelChanged(), and setAlphaActive().
contextMenuEvent()
void ColorField::contextMenuEvent (QContextMenuEvent * event) override protected
{
  bool hasColor = QApplication::clipboard()->mimeData()->hasColor();
  const StyleData *data =
      dynamic_cast<const StyleData *>(QApplication::clipboard()->mimeData());
  QMenu menu(this);
  if (hasColor) {  // pasting QColor
    QColor color = qvariant_cast<QColor>(
        QApplication::clipboard()->mimeData()->colorData());
    QAction *action = new QAction(tr("Paste Color"), this);
    action->setIcon(QIcon(getIconPm(color)));
    action->setData(color);
    connect(action, SIGNAL(triggered()), this, SLOT(onPasteColor()));
    menu.addAction(action);
    menu.addSeparator();
  } else if (data && data->getStyleCount() > 0) {  // pasting styles colors
    // show 10 styles in maximum
    int styleCount = std::min(10, data->getStyleCount());
    for (int i = 0; i < styleCount; i++) {
      QString styleName = QString::fromStdWString(data->getStyle(i)->getName());
      TPixel32 color    = data->getStyle(i)->getMainColor();
      QColor _color(color.r, color.g, color.b, color.m);
      QAction *action =
          new QAction(tr("Paste Color of %1").arg(styleName), this);
      action->setIcon(QIcon(getIconPm(_color)));
      action->setData(_color);
      connect(action, SIGNAL(triggered()), this, SLOT(onPasteColor()));
      menu.addAction(action);
    }
    menu.addSeparator();
  }
  QAction *copyAction = new QAction(tr("Copy Color"), this);
  connect(copyAction, SIGNAL(triggered()), this, SLOT(onCopyColor()));
  menu.addAction(copyAction);
  menu.exec(event->globalPos());
  event->accept();
}
getColor()
TPixel32 DVGui::ColorField::getColor () const inline
Return ColorField current color.
{ return m_color; }
Referenced by ConvertPopup::apply().
getEditorController()
ColorField::ColorFieldEditorController * ColorField::getEditorController () static
{
  return m_editorController;
}
hideChannelsFields()
void ColorField::hideChannelsFields (bool hide)
Set all ChannelField channel value to ColorField current color.
{
  if (hide) {
    m_redChannel->hide();
    m_greenChannel->hide();
    m_blueChannel->hide();
    m_alphaChannel->hide();
    disconnect(m_redChannel, SIGNAL(valueChanged(int, bool)), this,
               SLOT(onRedChannelChanged(int, bool)));
    disconnect(m_greenChannel, SIGNAL(valueChanged(int, bool)), this,
               SLOT(onGreenChannelChanged(int, bool)));
    disconnect(m_blueChannel, SIGNAL(valueChanged(int, bool)), this,
               SLOT(onBlueChannelChanged(int, bool)));
    disconnect(m_alphaChannel, SIGNAL(valueChanged(int, bool)), this,
               SLOT(onAlphaChannelChanged(int, bool)));
  } else {
    m_redChannel->show();
    m_greenChannel->show();
    m_blueChannel->show();
    m_alphaChannel->show();
    ;
    connect(m_redChannel, SIGNAL(valueChanged(int, bool)),
            SLOT(onRedChannelChanged(int, bool)));
    connect(m_greenChannel, SIGNAL(valueChanged(int, bool)),
            SLOT(onGreenChannelChanged(int, bool)));
    connect(m_blueChannel, SIGNAL(valueChanged(int, bool)),
            SLOT(onBlueChannelChanged(int, bool)));
    connect(m_alphaChannel, SIGNAL(valueChanged(int, bool)),
            SLOT(onAlphaChannelChanged(int, bool)));
  }
}
References onAlphaChannelChanged(), onBlueChannelChanged(), onGreenChannelChanged(), and onRedChannelChanged().
hideEvent()
void ColorField::hideEvent (QHideEvent *) override protected
{
  if (!m_useStyleEditor || !getEditorController()) return;
  getEditorController()->hide();
}
isEditing()
bool DVGui::ColorField::isEditing () const inline
{
    assert(m_colorSample);
    return m_colorSample->isEditing();
  }
mouseDoubleClickEvent()
void ColorField::mouseDoubleClickEvent (QMouseEvent * event) override protected
{
  QPoint p = event->pos();
  if (!m_colorSample->visibleRegion().contains(p)) return;
  if (!m_useStyleEditor || !getEditorController()) return;
  CommandManager::instance()->execute("MI_OpenStyleControl");
  getEditorController()->edit(this);
}
mousePressEvent()
void ColorField::mousePressEvent (QMouseEvent * event) override protected
{
  if (event->button() != Qt::LeftButton) return;
  QPoint p = event->pos();
  if (!m_colorSample->visibleRegion().contains(p)) return;
  if (!m_useStyleEditor || !getEditorController()) return;
  getEditorController()->edit(this);
}
notifyColorChanged()
void DVGui::ColorField::notifyColorChanged (const TPixel32 & color, bool isDragging) inline
{
    emit colorChanged(color, isDragging);
  }
onAlphaChannelChanged
void ColorField::onAlphaChannelChanged (int value, bool isDragging) protected slot
If current alpha channel value of color is different from value set it, change StyleSample color and emit signal colorChanged(const TPixel32 &).
{
  if (m_color.m == value) {
    if (!isDragging) emit colorChanged(m_color, isDragging);
    return;
  }
  m_color = TPixel32(m_color.r, m_color.g, m_color.b, value);
  m_colorSample->setColor(m_color);
  emit colorChanged(m_color, isDragging);
}
References colorChanged(), and DVGui::StyleSample::setColor().
Referenced by hideChannelsFields(), and setAlphaActive().
onBlueChannelChanged
void ColorField::onBlueChannelChanged (int value, bool isDragging) protected slot
If current blue channel value of color is different from value set it, change StyleSample color and emit signal colorChanged(const TPixel32 &).
{
  if (m_color.b == value) {
    if (!isDragging) emit colorChanged(m_color, isDragging);
    return;
  }
  m_color = TPixel32(m_color.r, m_color.g, value, m_color.m);
  m_colorSample->setColor(m_color);
  emit colorChanged(m_color, isDragging);
}
References colorChanged(), and DVGui::StyleSample::setColor().
Referenced by hideChannelsFields().
onCopyColor
void ColorField::onCopyColor () protected slot
{
  QColor color(m_color.r, m_color.g, m_color.b, m_color.m);
  QMimeData *data = new QMimeData();
  data->setColorData(color);
  QApplication::clipboard()->setMimeData(data);
}
onGreenChannelChanged
void ColorField::onGreenChannelChanged (int value, bool isDragging) protected slot
If current green channel value of color is different from value set it, change StyleSample color and emit signal colorChanged(const TPixel32 &).
{
  if (m_color.g == value) {
    if (!isDragging) emit colorChanged(m_color, isDragging);
    return;
  }
  m_color = TPixel32(m_color.r, value, m_color.b, m_color.m);
  m_colorSample->setColor(m_color);
  emit colorChanged(m_color, isDragging);
}
References colorChanged(), and DVGui::StyleSample::setColor().
Referenced by hideChannelsFields().
onPasteColor
void ColorField::onPasteColor () protected slot
{
  QColor color = qobject_cast<QAction *>(sender())->data().value<QColor>();
  m_color = TPixel32(color.red(), color.green(), color.blue(), color.alpha());
  if (!m_alphaChannel->isVisible()) m_color.m = 255;
  m_colorSample->setColor(m_color);
  updateChannels();
  emit colorChanged(m_color, false);
}
onRedChannelChanged
void ColorField::onRedChannelChanged (int value, bool isDragging) protected slot
If current red channel value of color is different from value set it, change StyleSample color and emit signal colorChanged(const TPixel32 &).
{
  if (m_color.r == value) {
    if (!isDragging) emit colorChanged(m_color, isDragging);
    return;
  }
  m_color = TPixel32(value, m_color.g, m_color.b, m_color.m);
  m_colorSample->setColor(m_color);
  emit colorChanged(m_color, isDragging);
}
References colorChanged(), and DVGui::StyleSample::setColor().
Referenced by hideChannelsFields().
setAlphaActive()
void ColorField::setAlphaActive (bool active)
Set ColorField current color to color. Update channel value of ChannelField and StyleSample color.
{
  if (active && !m_alphaChannel->isVisible()) {
    m_alphaChannel->show();
    connect(m_alphaChannel, SIGNAL(valueChanged(int, bool)),
            SLOT(onAlphaChannelChanged(int, bool)));
    assert(m_color.m == 255);
    m_alphaChannel->setChannel(0);
    m_color.m = 0;
    m_colorSample->setColor(m_color);
    emit colorChanged(m_color, false);
  } else if (!active && m_alphaChannel->isVisible()) {
    m_alphaChannel->hide();
    disconnect(m_alphaChannel, SIGNAL(valueChanged(int, bool)), this,
               SLOT(onAlphaChannelChanged(int, bool)));
    if (m_color.m != 255) {
      m_alphaChannel->setChannel(255);
      m_color.m = 255;
      m_colorSample->setColor(m_color);
      emit colorChanged(m_color, false);
    }
  }
}
References colorChanged(), onAlphaChannelChanged(), DVGui::ChannelField::setChannel(), and DVGui::StyleSample::setColor().
setChessboardColors()
void ColorField::setChessboardColors (const TPixel32 & col1, const TPixel32 & col2)
{
  m_colorSample->setChessboardColors(col1, col2);
}
setColor()
void ColorField::setColor (const TPixel32 & color)
{
  if (m_color == color) return;
  m_color = color;
  updateChannels();
  m_colorSample->setColor(m_color);
}
setEditingChangeNotified()
void DVGui::ColorField::setEditingChangeNotified (bool notify) inline
{ m_notifyEditingChange = notify; }
setEditorController()
void ColorField::setEditorController (ColorFieldEditorController * editorController) static
{
  m_editorController = editorController;
}
setIsEditing()
void DVGui::ColorField::setIsEditing (bool isEditing) inline
{
    assert(m_colorSample);
    m_colorSample->setIsEditing(isEditing);
    if (m_notifyEditingChange) emit editingChanged(getColor(), isEditing);
  }
updateChannels()
void ColorField::updateChannels () protected
Set all ChannelField channel value to ColorField current color.
{
  m_redChannel->setChannel(m_color.r);
  m_greenChannel->setChannel(m_color.g);
  m_blueChannel->setChannel(m_color.b);
  m_alphaChannel->setChannel(m_color.m);
}
References DVGui::ChannelField::setChannel().
Member Data Documentation
m_editorController
ColorField::ColorFieldEditorController * ColorField::m_editorController = 0 static
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/toonzqt/colorfield.h
E:/opentoonz/toonz/sources/toonzqt/colorfield.cpp