opentoonz: TXshColumn Class Reference
TXshColumn Class Reference abstract
The TXshColumn class is the base class of column managers in xsheet.
#include <txshcolumn.h>
Public Types
enum FilterColor {
FilterNone = 0 , FilterRed , FilterGreen , FilterBlue ,
FilterDarkYellow , FilterDarkCyan , FilterDarkMagenta , FilterAmount
}
enum ColumnType {
eLevelType = 0 , eSoundType , eSoundTextType , eZeraryFxType ,
ePaletteType , eMeshType
}
Public Types inherited from TSmartObject
typedef short ClassCode
Public Types inherited from TPersist
typedef TPersist * CreateProc()
Public Member Functions
TXshColumn ()
virtual ColumnType getColumnType () const =0
virtual TXshLevelColumn * getLevelColumn ()
virtual TXshSoundColumn * getSoundColumn ()
virtual TXshSoundTextColumn * getSoundTextColumn ()
virtual TXshCellColumn * getCellColumn ()
virtual TXshPaletteColumn * getPaletteColumn ()
virtual TXshZeraryFxColumn * getZeraryFxColumn ()
virtual TXshMeshColumn * getMeshColumn ()
virtual int getMaxFrame () const =0
virtual TXshColumn * clone () const =0
bool isCamstandVisible () const
void setCamstandVisible (bool on)
UCHAR getOpacity () const
void setOpacity (UCHAR val)
bool isPreviewVisible () const
void setPreviewVisible (bool on)
bool isLocked () const
void lock (bool on)
bool isMask () const
void setIsMask (bool on)
virtual bool isEmpty () const
virtual TRaster32P getIcon ()
virtual bool isCellEmpty (int row) const =0
virtual bool getLevelRange (int row, int &r0, int &r1) const =0
virtual int getRange (int &r0, int &r1) const
virtual void setXsheet (TXsheet *xsheet)
TXsheet * getXsheet () const
virtual TFx * getFx () const
virtual bool isRendered () const
virtual bool isControl () const
int getColorTag () const
void setColorTag (int colorTag)
FilterColor getFilterColorId () const
void setFilterColorId (FilterColor id)
TPixel32 getFilterColor ()
void resetColumnProperties ()
Public Member Functions inherited from TColumnHeader
int getIndex () const
int getPos () const
int getX0 () const
int getX1 () const
void getCoords (int &x0, int &x1) const
int getWidth () const
bool inColumnsSet () const
Public Member Functions inherited from TSmartObject
TSmartObject (ClassCode classCode)
void addRef ()
void release ()
TINT32 getRefCount () const
Public Member Functions inherited from TPersist
virtual void loadData (TIStream &is)=0
virtual void saveData (TOStream &os)=0
std::string getStreamTag () const
virtual const TPersistDeclaration * getDeclaration () const =0
Static Public Member Functions
static ColumnType toColumnType (int levelType)
Returns the column type used to store levels of the specified type.
static TXshColumn * createEmpty (int colType)
Creates an empty TXshColumn of the specified column type.
static QPair< QString, TPixel32 > getFilterInfo (FilterColor key)
static void initColorFilters ()
Static Public Member Functions inherited from TSmartObject
static TINT32 getInstanceCount (ClassCode code)
Static Public Member Functions inherited from TPersist
static void declare (CreateProc *)
static TPersist * create (const std::string &name)
Protected Types
enum {
eCamstandVisible = 0x1 , ePreviewVisible = 0x2 , eLocked = 0x8 , eMasked = 0x10 ,
eCamstandTransparent43 = 0x20
}
Protected Member Functions
void setStatusWord (int status)
int getStatusWord () const
Protected Attributes
TRaster32P m_icon
Detailed Description
The TXshColumn class is the base class of column managers in xsheet.
Inherits TColumnHeader and TPersist.
This is an abstract base class inherited by the concrete classes TXshCellColumn, TXshSoundColumn and TXshPaletteColumn.
The class contains all features about a generic xsheet column and gives all methods to access to these information.
The createEmpty() static method creates an new empty column.
The getXsheet() function return xsheet to which column belongs, xsheet can be changed using the setXsheet().
The getIcon() function return column icon.
TXshColumn allows to manage generic column status getStatusWord() and setStatusWord. Particularly it's possible to know if column is a mask isMask(), is lock isLocked(), or if it's view is in modality preview or camera stand, isCamstandVisible() and isPreviewVisible(). It's besides possible ot change this settings using setMask(), lock(), setCamstandVisible() and setPreviewVisible().
Member Enumeration Documentation
anonymous enum
anonymous enum protected
       {
    eCamstandVisible       = 0x1,
    ePreviewVisible        = 0x2,
    eLocked                = 0x8,
    eMasked                = 0x10,
    eCamstandTransparent43 = 0x20  // obsoleto, solo per retrocompatibilita'
  };
ColumnType
enum TXshColumn::ColumnType
                  {
    eLevelType = 0,
    eSoundType,
    eSoundTextType,
    eZeraryFxType,
    ePaletteType,
    eMeshType
  };
FilterColor
enum TXshColumn::FilterColor
                   {
    FilterNone = 0,
    FilterRed,
    FilterGreen,
    FilterBlue,
    FilterDarkYellow,
    FilterDarkCyan,
    FilterDarkMagenta,
    FilterAmount
  };
Constructor & Destructor Documentation
TXshColumn()
TXshColumn::TXshColumn () inline
Constructs a TXshColumn with default value.
      : m_status(0)
      , m_xsheet(0)
      , m_colorTag(0)
      , m_opacity(255)
      , m_filterColorId(FilterNone) {}
Member Function Documentation
clone()
virtual TXshColumn * TXshColumn::clone () const pure virtual
Implemented in TXshLevelColumn, and TXshZeraryFxColumn.
createEmpty()
TXshColumn * TXshColumn::createEmpty (int colType) static
Creates an empty TXshColumn of the specified column type.
{
  switch (type) {
  case eSoundType:
    return new TXshSoundColumn;
  case eZeraryFxType:
    return new TXshZeraryFxColumn(0);
  case ePaletteType:
    return new TXshPaletteColumn;
  case eSoundTextType:
    return new TXshSoundTextColumn;
  case eMeshType:
    return new TXshMeshColumn;
  }
  assert(type == eLevelType);
  return new TXshLevelColumn;
}
Referenced by TXsheet::insertColumn().
getCellColumn()
virtual TXshCellColumn * TXshColumn::getCellColumn () inline virtual
Reimplemented in TXshCellColumn.
{ return 0; }
getColorTag()
int TXshColumn::getColorTag () const inline
Return column color tag.
See also
setColorTag()
{ return m_colorTag; }  // Usato solo in tabkids
Referenced by TXshLevelColumn::clone().
getFilterColor()
TPixel32 TXshColumn::getFilterColor ()
{
  return TXshColumn::getFilterInfo(m_filterColorId).second;
}
getFilterColorId()
FilterColor TXshColumn::getFilterColorId () const inline
{ return m_filterColorId; }
getFilterInfo()
QPair< QString, TPixel32 > TXshColumn::getFilterInfo (TXshColumn::FilterColor key) static
{
  TXshColumn::initColorFilters();
  if (!filterColors.contains(key))
    return QPair<QString, TPixel32>(QObject::tr("None"), TPixel::Black);
  return filterColors.value(key);
}
getFx()
virtual TFx * TXshColumn::getFx () const inline virtual
Reimplemented in TXshLevelColumn, and TXshZeraryFxColumn.
{ return 0; }
getIcon()
virtual TRaster32P TXshColumn::getIcon () inline virtual
Return m_icon.
{ return m_icon; }
getLevelColumn()
virtual TXshLevelColumn * TXshColumn::getLevelColumn () inline virtual
Reimplemented in TXshLevelColumn.
{ return 0; }
getLevelRange()
virtual bool TXshColumn::getLevelRange (int row, int & r0, int & r1) const pure virtual
If r0=r1=row return false.
Implemented in TXshCellColumn, and TXshSoundColumn.
getMaxFrame()
virtual int TXshColumn::getMaxFrame () const pure virtual
Implemented in TXshCellColumn, and TXshSoundColumn.
getMeshColumn()
virtual TXshMeshColumn * TXshColumn::getMeshColumn () inline virtual
{ return 0; }
getOpacity()
UCHAR TXshColumn::getOpacity () const inline
Return true if camera stand is transparent.notice: this value is not relevant if camerastandVisible is off.
See also
setCamstandTransparent()
{ return m_opacity; }
Referenced by StageBuilder::addCell(), TXshLevelColumn::clone(), TXshMeshColumn::saveData(), and TXshLevelColumn::saveData().
getPaletteColumn()
virtual TXshPaletteColumn * TXshColumn::getPaletteColumn () inline virtual
{ return 0; }
getRange()
virtual int TXshColumn::getRange (int & r0, int & r1) const inline virtual
Reimplemented in TXshCellColumn, and TXshSoundColumn.
{
    r0 = 0;
    r1 = -1;
    return 0;
  }
getSoundColumn()
virtual TXshSoundColumn * TXshColumn::getSoundColumn () inline virtual
{ return 0; }
getSoundTextColumn()
virtual TXshSoundTextColumn * TXshColumn::getSoundTextColumn () inline virtual
{ return 0; }
getStatusWord()
int TXshColumn::getStatusWord () const inline protected
Return m_status.
See also
setStatusWord()
{ return m_status; };
Referenced by TXshLevelColumn::clone(), TXshMeshColumn::saveData(), TXshLevelColumn::saveData(), TXshSoundColumn::saveData(), and TXshZeraryFxColumn::saveData().
getXsheet()
TXsheet * TXshColumn::getXsheet () const inline
Return m_xsheet.
See also
setXsheet()
{ return m_xsheet; }
Referenced by isControl(), isRendered(), and TXshSoundColumn::modifyCellRange().
getZeraryFxColumn()
virtual TXshZeraryFxColumn * TXshColumn::getZeraryFxColumn () inline virtual
{ return 0; }
initColorFilters()
void TXshColumn::initColorFilters () static
{
  static bool _firstTime = true;
  if (!_firstTime) return;
  filterColors[TXshColumn::FilterNone] =
      QPair<QString, TPixel32>(QObject::tr("None"), TPixel::Black);
  filterColors[TXshColumn::FilterRed] =
      QPair<QString, TPixel32>(QObject::tr("Red"), TPixel::Red);
  filterColors[TXshColumn::FilterGreen] =
      QPair<QString, TPixel32>(QObject::tr("Green"), TPixel::Green);
  filterColors[TXshColumn::FilterBlue] =
      QPair<QString, TPixel32>(QObject::tr("Blue"), TPixel::Blue);
  filterColors[TXshColumn::FilterDarkYellow] =
      QPair<QString, TPixel32>(QObject::tr("DarkYellow"), TPixel(128, 128, 0));
  filterColors[TXshColumn::FilterDarkCyan] =
      QPair<QString, TPixel32>(QObject::tr("DarkCyan"), TPixel(0, 128, 128));
  filterColors[TXshColumn::FilterDarkMagenta] =
      QPair<QString, TPixel32>(QObject::tr("DarkMagenta"), TPixel(128, 0, 128));
  _firstTime = false;
}
isCamstandVisible()
bool TXshColumn::isCamstandVisible () const
Return true if camera stand is visible.
See also
setCamstandVisible()
{
  return (m_status & eCamstandVisible) == 0;
}
isCellEmpty()
virtual bool TXshColumn::isCellEmpty (int row) const pure virtual
Implemented in TXshCellColumn, and TXshSoundColumn.
isControl()
bool TXshColumn::isControl () const virtual
Return true if column is control.
{
  if (!getXsheet() || !getFx()) return false;
  return getXsheet()->getFxDag()->isControl(getFx());
  /*
TFx *fx = getFx();
if(!fx) return false;
if(!getXsheet()) return false;
if(getXsheet()->getFxDag()->getTerminalFxs()->containsFx(getFx())) return false;
for(int i=0;i<fx->getOutputConnectionCount();i++)
{
TFxPort *port = fx->getOutputConnection(i);
if(port->getOwnerFx()->getInputPort(0) != port)
return true;
}
return false;
*/
}
References TXsheet::getFxDag(), and getXsheet().
isEmpty()
virtual bool TXshColumn::isEmpty () const inline virtual
Reimplemented in TXshCellColumn.
{ return true; }
isLocked()
bool TXshColumn::isLocked () const
Return true if column is locked.
See also
lock()
{ return (m_status & eLocked) != 0; }
isMask()
bool TXshColumn::isMask () const
Return true if column is a mask.
See also
setMask()
{ return (m_status & eMasked) != 0; }
isPreviewVisible()
bool TXshColumn::isPreviewVisible () const
Return true if preview is visible.
See also
setPreviewVisible()
{
  return (m_status & ePreviewVisible) == 0;
}
Referenced by isRendered(), and FxBuilder::makePF().
isRendered()
bool TXshColumn::isRendered () const virtual
Return true if column affects the final render
{
  //  if (!getXsheet() || !getFx()) return false;
  //  if (!isPreviewVisible()) return false;
  if (!getXsheet() || !isPreviewVisible()) return false;
  if (getColumnType() == eSoundType) return true;
  if (!getFx()) return false;
  return getXsheet()->getFxDag()->isRendered(getFx());
}
References TXsheet::getFxDag(), getXsheet(), and isPreviewVisible().
lock()
void TXshColumn::lock (bool on)
Set column status look to on.
See also
isLocked()
{
  const int mask = eLocked;
  if (on)
    m_status |= mask;
  else
    m_status &= ~mask;
}
resetColumnProperties()
void TXshColumn::resetColumnProperties ()
{
  setStatusWord(0);
  setOpacity(255);
  setColorTag(0);
  setFilterColorId(FilterNone);
}
setCamstandVisible()
void TXshColumn::setCamstandVisible (bool on)
Set column status camera stand visibility to on.
See also
isCamstandVisible()
{
  const int mask = eCamstandVisible;
  if (on)
    m_status &= ~mask;
  else
    m_status |= mask;
}
setColorTag()
void TXshColumn::setColorTag (int colorTag) inline
Set column color tag to colorTag.
See also
getColorTag()
{
    m_colorTag = colorTag;
  }  // Usato solo in tabkids
setFilterColorId()
void TXshColumn::setFilterColorId (FilterColor id) inline
{ m_filterColorId = id; }
setIsMask()
void TXshColumn::setIsMask (bool on)
Set column status mask to on.
See also
isMask()
{
  const int mask = eMasked;
  if (on)
    m_status |= mask;
  else
    m_status &= ~mask;
}
setOpacity()
void TXshColumn::setOpacity (UCHAR val) inline
Set column status camera stand transparent to on. notice: this value is not relevant if camerastandVisible is off.
See also
isCamstandTransparent()
{ m_opacity = val; }
Referenced by StageBuilder::addCell(), TXshLevelColumn::loadData(), and TXshMeshColumn::loadData().
setPreviewVisible()
void TXshColumn::setPreviewVisible (bool on)
Set column status preview to on.
See also
isPreviewVisible()
{
  const int mask = ePreviewVisible;
  if (on)
    m_status &= ~mask;
  else
    m_status |= mask;
}
setStatusWord()
void TXshColumn::setStatusWord (int status) protected
Set m_status to status.
See also
getStatusWord()
{ m_status = status; }
Referenced by TXshLevelColumn::loadData(), TXshMeshColumn::loadData(), TXshSoundColumn::loadData(), and TXshZeraryFxColumn::loadData().
setXsheet()
virtual void TXshColumn::setXsheet (TXsheet * xsheet) inline virtual
Set m_xsheet to xsheet.
See also
getXsheet()
Reimplemented in TXshSoundColumn.
{ m_xsheet = xsheet; }
Referenced by IoCmd::exposeComment(), TXshChildLevel::setScene(), and TXshSoundColumn::setXsheet().
toColumnType()
TXshColumn::ColumnType TXshColumn::toColumnType (int levelType) static
Returns the column type used to store levels of the specified type.
{
  ColumnType colType = TXshColumn::eLevelType;
  if (levelType & LEVELCOLUMN_XSHLEVEL)
    colType = TXshColumn::eLevelType;
  else if (levelType == ZERARYFX_XSHLEVEL)
    colType = TXshColumn::eZeraryFxType;
  else if (levelType == PLT_XSHLEVEL)
    colType = TXshColumn::ePaletteType;
  else if (levelType == SND_XSHLEVEL)
    colType = TXshColumn::eSoundType;
  else if (levelType == SND_TXT_XSHLEVEL)
    colType = TXshColumn::eSoundTextType;
  else if (levelType == MESH_XSHLEVEL)
    colType = TXshColumn::eMeshType;
  else
    assert(!"Unknown level type!");
  return colType;
}
Member Data Documentation
m_icon
TRaster32P TXshColumn::m_icon protected
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/toonz/txshcolumn.h
E:/opentoonz/toonz/sources/toonzlib/txshcolumn.cpp