opentoonz: TRangeParam Class Reference
TRangeParam Class Reference final
Public Member Functions
TRangeParam (const DoublePair &range=DoublePair(0, 0))
TRangeParam (const TRangeParam &src)
TParam * clone () const override
void copy (TParam *src) override
DoublePair getDefaultValue () const
DoublePair getValue (double frame) const
bool setValue (double frame, const DoublePair &v)
void setDefaultValue (const DoublePair &v)
void loadData (TIStream &is) override
void saveData (TOStream &os) override
int getKeyframeCount () const
TDoubleParamP & getMin ()
TDoubleParamP & getMax ()
Public Member Functions inherited from TParamSet
TParamSet (std::string name="")
TParamSet (const TParamSet &src)
void addParam (const TParamP &param, const std::string &name)
void insertParam (const TParamP &param, const std::string &name, int index)
void removeParam (const TParamP &param)
void removeAllParam ()
int getParamCount () const
TParamP getParam (int index) const
std::string getParamName (int index) const
int getParamIdx (const std::string &name) const
void getAnimatableParams (std::vector< TParamP > &params, bool recursive=true)
void addObserver (TParamObserver *observer) override
void removeObserver (TParamObserver *observer) override
void beginParameterChange ()
void endParameterChange ()
void enableDragging (bool on)
void enableNotification (bool on) override
bool isNotificationEnabled () const override
bool isAnimatable () const override
bool isKeyframe (double frame) const override
void deleteKeyframe (double frame) override
void clearKeyframes () override
void assignKeyframe (double frame, const TSmartPointerT< TParam > &src, double srcFrame, bool changedOnly=false) override
void getKeyframes (std::set< double > &frames) const override
int getKeyframeCount () const
double keyframeIndexToFrame (int index) const override
TParam * clone () const override
void copy (TParam *src) override
void loadData (TIStream &) override
void saveData (TOStream &) override
int getNextKeyframe (double frame) const override
int getPrevKeyframe (double frame) const override
bool hasKeyframes () const override
std::string getValueAlias (double frame, int precision) override
Public Member Functions inherited from TParam
TParam (std::string name="", std::string description="", std::string label="")
std::string getName () const
void setName (const std::string &name)
std::string getDescription () const
void setDescription (const std::string &description)
bool hasUILabel () const
void setUILabel (const std::string &l)
std::string getUILabel () const
virtual TParam * clone () const =0
virtual void copy (TParam *src)=0
virtual void addObserver (TParamObserver *)=0
virtual void removeObserver (TParamObserver *)=0
virtual void enableNotification (bool on)
virtual bool isNotificationEnabled () const
virtual std::string getValueAlias (double frame, int precision)=0
virtual bool isAnimatable () const =0
virtual bool isKeyframe (double frame) const =0
virtual void deleteKeyframe (double frame)=0
virtual void clearKeyframes ()=0
virtual void assignKeyframe (double frame, const TSmartPointerT< TParam > &src, double srcFrame, bool changedOnly=false)=0
virtual void getKeyframes (std::set< double > &frames) const
virtual bool hasKeyframes () const
virtual int getNextKeyframe (double frame) const
virtual int getPrevKeyframe (double frame) const
virtual double keyframeIndexToFrame (int index) const
Public Member Functions inherited from TSmartObject
TSmartObject (ClassCode classCode)
void addRef ()
void release ()
TINT32 getRefCount () const
Public Member Functions inherited from TPersist
virtual void loadData (TIStream &is)=0
virtual void saveData (TOStream &os)=0
std::string getStreamTag () const
virtual const TPersistDeclaration * getDeclaration () const =0
Additional Inherited Members
Public Types inherited from TSmartObject
typedef short ClassCode
Public Types inherited from TPersist
typedef TPersist * CreateProc()
Static Public Member Functions inherited from TSmartObject
static TINT32 getInstanceCount (ClassCode code)
Static Public Member Functions inherited from TPersist
static void declare (CreateProc *)
static TPersist * create (const std::string &name)
Detailed Description
Constructor & Destructor Documentation
TRangeParam() [1/2]
TRangeParam::TRangeParam (const DoublePair & range = DoublePair(0, 0))
                                            : m_data(new TRangeParamImp(v)) {
  addParam(m_data->m_min, "min");
  addParam(m_data->m_max, "max");
}
TRangeParam() [2/2]
TRangeParam::TRangeParam (const TRangeParam & src)
    : TParamSet(src.getName()), m_data(new TRangeParamImp(*src.m_data)) {
  addParam(m_data->m_min, "min");
  addParam(m_data->m_max, "max");
}
~TRangeParam()
TRangeParam::~TRangeParam ()
{ delete m_data; }
Member Function Documentation
clone()
TParam * TRangeParam::clone () const inline override virtual
 This method must be implemented with a clone function, i.e a function
that make a new copy of the parameter.
Reimplemented from TParamSet.
{ return new TRangeParam(*this); }
copy()
void TRangeParam::copy (TParam * src) override virtual
Performs a copy function of the parameter in an existing object.
Reimplemented from TParamSet.
{
  TRangeParam *p = dynamic_cast<TRangeParam *>(src);
  if (!p) throw TException("invalid source for copy");
  setName(src->getName());
  m_data->m_min->copy(p->m_data->m_min.getPointer());
  m_data->m_max->copy(p->m_data->m_max.getPointer());
}
References TParam::getName(), and TParam::setName().
getDefaultValue()
DoublePair TRangeParam::getDefaultValue () const
{
  return DoublePair(m_data->m_min->getDefaultValue(),
                    m_data->m_max->getDefaultValue());
}
getMax()
TDoubleParamP & TRangeParam::getMax ()
{ return m_data->m_max; }
getMin()
TDoubleParamP & TRangeParam::getMin ()
{ return m_data->m_min; }
getValue()
DoublePair TRangeParam::getValue (double frame) const
{
  return DoublePair(m_data->m_min->getValue(frame),
                    m_data->m_max->getValue(frame));
}
loadData()
void TRangeParam::loadData (TIStream & is) override virtual
 This is a pure virtual function and must be overridden with a method
that implements the object loading from a stream (i.e take the object's features from a formatted data stream). For example the TStageObject class use his implementation to take the values of the parameters that characterizes a stage object as name, coordinates, etc... from a file. is is an input file stream
Reimplemented from TParamSet.
{
  std::string childName;
  while (is.openChild(childName)) {
    if (childName == "min")
      m_data->m_min->loadData(is);
    else if (childName == "max")
      m_data->m_max->loadData(is);
    else
      throw TException("unknown tag");
    is.closeChild();
  }
}
References TIStream::closeChild(), and TIStream::openChild().
saveData()
void TRangeParam::saveData (TOStream & os) override virtual
 This is a pure virtual function and must be overridden with a method
that implements the object saving to a data stream (i.e put the object's features on a formatted data stream). For example the TStageObject class use his implementation to save the values of the parameters that characterizes a stage object as name, coordinates, etc... on a file os is an output file stream.
Reimplemented from TParamSet.
{
  os.openChild("min");
  m_data->m_min->saveData(os);
  os.closeChild();
  os.openChild("max");
  m_data->m_max->saveData(os);
  os.closeChild();
}
References TOStream::closeChild(), and TOStream::openChild().
setDefaultValue()
void TRangeParam::setDefaultValue (const DoublePair & v)
{
  m_data->m_min->setDefaultValue(v.first);
  m_data->m_max->setDefaultValue(v.second);
}
setValue()
bool TRangeParam::setValue (double frame, const DoublePair & v)
{
  beginParameterChange();
  m_data->m_min->setValue(frame, v.first);
  m_data->m_max->setValue(frame, v.second);
  endParameterChange();
  return true;
}
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/tparamset.h
E:/opentoonz/toonz/sources/common/tparam/trangeparam.cpp