opentoonz: TRectT< T > Class Template Reference
TRectT< T > Class Template Reference
Specifies the corners of a rectangle.
#include <tgeometry.h>
Public Member Functions
TRectT ()
TRectT (T _x0, T _y0, T _x1, T _y1)
TRectT (const TRectT &rect)
TRectT (const TPointT< T > &p0, const TPointT< T > &p1)
TRectT (const TPointT< T > &bottomLeft, const TDimensionT< T > &d)
TRectT (const TDimensionT< T > &d)
void empty ()
bool isEmpty () const
T getLx () const
T getLy () const
TDimensionT< T > getSize () const
TPointT< T > getP00 () const
TPointT< T > getP10 () const
TPointT< T > getP01 () const
TPointT< T > getP11 () const
TRectT< T > operator+ (const TRectT< T > &rect) const
TRectT< T > & operator+= (const TRectT< T > &rect)
TRectT< T > & operator*= (const TRectT< T > &rect)
TRectT< T > operator* (const TRectT< T > &rect) const
Returns the intersection of two existing rectangles.
TRectT< T > & operator+= (const TPointT< T > &p)
TRectT< T > & operator-= (const TPointT< T > &p)
TRectT< T > operator+ (const TPointT< T > &p) const
TRectT< T > operator- (const TPointT< T > &p) const
bool operator== (const TRectT< T > &r) const
bool operator!= (const TRectT< T > &r) const
bool contains (const TPointT< T > &p) const
bool contains (const TRectT< T > &b) const
bool overlaps (const TRectT< T > &b) const
TRectT< T > enlarge (T dx, T dy) const
TRectT< T > enlarge (T d) const
TRectT< T > enlarge (TDimensionT< T > d) const
Public Attributes
T x0
T y0
T x1
T y1
Related Functions
(Note that these are not member functions.)
TRect convert (const TRectD &r)
TRectD convert (const TRect &r)
Detailed Description
template<class T>
class TRectT< T >
Specifies the corners of a rectangle.
x0 specifies the x-coordinate of the bottom-left corner of a rectangle. y0 specifies the y-coordinate of the bottom-left corner of a rectangle. x1 specifies the x-coordinate of the upper-right corner of a rectangle. y1 specifies the y-coordinate of the upper-right corner of a rectangle.
Constructor & Destructor Documentation
TRectT() [1/4]
template<class T > TRectT< T >::TRectT ()
makes an empty rect
TRectT() [2/4]
template<class T > TRectT< T >::TRectT (T _x0, T _y0, T _x1, T _y1) inline
: x0(_x0), y0(_y0), x1(_x1), y1(_y1){};
TRectT() [3/4]
template<class T > TRectT< T >::TRectT (const TRectT< T > & rect) inline
      : x0(rect.x0), y0(rect.y0), x1(rect.x1), y1(rect.y1){};
TRectT() [4/4]
template<class T > TRectT< T >::TRectT (const TPointT< T > & p0, const TPointT< T > & p1) inline
      : x0(std::min((T)p0.x, (T)p1.x)),
        y0(std::min((T)p0.y, (T)p1.y)),
        x1(std::max((T)p0.x, (T)p1.x)),
        y1(std::max((T)p0.y, (T)p1.y)){};
Member Function Documentation
contains() [1/2]
template<class T > bool TRectT< T >::contains (const TPointT< T > & p) const inline
{
    return x0 <= p.x && p.x <= x1 && y0 <= p.y && p.y <= y1;
  };
contains() [2/2]
template<class T > bool TRectT< T >::contains (const TRectT< T > & b) const inline
{
    return x0 <= b.x0 && x1 >= b.x1 && y0 <= b.y0 && y1 >= b.y1;
  };
enlarge() [1/3]
template<class T > TRectT< T > TRectT< T >::enlarge (T d) const inline
{ return enlarge(d, d); };
enlarge() [2/3]
template<class T > TRectT< T > TRectT< T >::enlarge (T dx, T dy) const inline
{
    if (isEmpty()) return *this;
    return TRectT<T>(x0 - dx, y0 - dy, x1 + dx, y1 + dy);
  };
enlarge() [3/3]
template<class T > TRectT< T > TRectT< T >::enlarge (TDimensionT< T > d) const inline
{ return enlarge(d.lx, d.ly); };
getP00()
template<class T > TPointT< T > TRectT< T >::getP00 () const inline
{ return TPointT<T>(x0, y0); };
getP01()
template<class T > TPointT< T > TRectT< T >::getP01 () const inline
{ return TPointT<T>(x0, y1); };
getP10()
template<class T > TPointT< T > TRectT< T >::getP10 () const inline
{ return TPointT<T>(x1, y0); };
getP11()
template<class T > TPointT< T > TRectT< T >::getP11 () const inline
{ return TPointT<T>(x1, y1); };
getSize()
template<class T > TDimensionT< T > TRectT< T >::getSize () const inline
{ return TDimensionT<T>(getLx(), getLy()); };
isEmpty()
template<class T > bool TRectT< T >::isEmpty () const
TRectD is empty if and only if (x0>x1 || y0>y1) || (x0==y1 && y0==y1); TRectI is empty if x0>x1 || y0>y1
Referenced by TRaster::copy(), TRop::copy(), LocalBlurFx::doDryCompute(), TCacheResource::download(), RasterSelectionTool::draw(), VectorSelectionTool::draw(), VectorTapeTool::draw(), ToonzRasterBrushTool::finishRasterBrush(), RadialBlurFx::getMemoryRequirement(), BaseRaylitFx::getMemoryRequirement(), SpinBlurFx::getMemoryRequirement(), SceneViewer::GLInvalidateRect(), TTool::invalidate(), TImageReaderTzl::load(), FullColorEraserTool::onImageChanged(), RasterTapeTool::onImageChanged(), EraserTool::onImageChanged(), Stage::RasterPainter::onRasterImage(), Stage::RasterPainter::onToonzImage(), TRectT< T >::operator*(), TRectT< T >::operator+(), TRop::over(), FullColorAreaFiller::rectFill(), TVectorImage::render(), RasterSelection::select(), and TCacheResource::upload().
operator!=()
template<class T > bool TRectT< T >::operator!= (const TRectT< T > & r) const inline
{
    return x0 != r.x0 || y0 != r.y0 || x1 != r.x1 || y1 != r.y1;
  };
operator*()
template<class T > TRectT< T > TRectT< T >::operator* (const TRectT< T > & rect) const inline
Returns the intersection of two existing rectangles.
                                                   {  // intersezione
    if (isEmpty() || rect.isEmpty())
      return TRectT<T>();
    else if (rect.x1 < x0 || x1 < rect.x0 || rect.y1 < y0 || y1 < rect.y0)
      return TRectT<T>();
    else
      return TRectT<T>(std::max((T)x0, (T)rect.x0), std::max((T)y0, (T)rect.y0),
                       std::min((T)x1, (T)rect.x1),
                       std::min((T)y1, (T)rect.y1));
  };
References TRectT< T >::isEmpty(), and TRectT< T >::x0.
operator*=()
template<class T > TRectT< T > & TRectT< T >::operator*= (const TRectT< T > & rect) inline
                                               {  // intersezione
    return *this = *this * rect;
  };
operator+() [1/2]
template<class T > TRectT< T > TRectT< T >::operator+ (const TPointT< T > & p) const inline
{
    TRectT<T> ris(*this);
    return ris += p;
  };
operator+() [2/2]
template<class T > TRectT< T > TRectT< T >::operator+ (const TRectT< T > & rect) const inline
Returns the union of two source rectangles. The union is the smallest rectangle that contains both source rectangles.
                                                   {  // unione
    if (isEmpty())
      return rect;
    else if (rect.isEmpty())
      return *this;
    else
      return TRectT<T>(std::min((T)x0, (T)rect.x0),
                       std::min((T)y0, (T)rect.y0),
                       std::max((T)x1, (T)rect.x1),
                       std::max((T)y1, (T)rect.y1));
  };
References TRectT< T >::isEmpty(), and TRectT< T >::x0.
operator+=() [1/2]
template<class T > TRectT< T > & TRectT< T >::operator+= (const TPointT< T > & p) inline
                                             {  // shift
    x0 += p.x;
    y0 += p.y;
    x1 += p.x;
    y1 += p.y;
    return *this;
  };
operator+=() [2/2]
template<class T > TRectT< T > & TRectT< T >::operator+= (const TRectT< T > & rect) inline
                                               {  // unione
    return *this = *this + rect;
  };
operator-()
template<class T > TRectT< T > TRectT< T >::operator- (const TPointT< T > & p) const inline
{
    TRectT<T> ris(*this);
    return ris -= p;
  };
operator-=()
template<class T > TRectT< T > & TRectT< T >::operator-= (const TPointT< T > & p) inline
{
    x0 -= p.x;
    y0 -= p.y;
    x1 -= p.x;
    y1 -= p.y;
    return *this;
  };
operator==()
template<class T > bool TRectT< T >::operator== (const TRectT< T > & r) const inline
{
    return x0 == r.x0 && y0 == r.y0 && x1 == r.x1 && y1 == r.y1;
  };
overlaps()
template<class T > bool TRectT< T >::overlaps (const TRectT< T > & b) const inline
{
    return x0 <= b.x1 && x1 >= b.x0 && y0 <= b.y1 && y1 >= b.y0;
  };
Friends And Related Function Documentation
convert() [1/2]
template<class T > TRectD convert (const TRect & r) related
Convert a TRect into a TRectD
{ return TRectD(r.x0, r.y0, r.x1, r.y1); }
References TRectT< T >::x0.
convert() [2/2]
template<class T > TRect convert (const TRectD & r) related
Convert a TRectD into a TRect
{
  return TRect((int)(r.x0 + 0.5), (int)(r.y0 + 0.5), (int)(r.x1 + 0.5),
               (int)(r.y1 + 0.5));
}
References TRectT< T >::x0.
Member Data Documentation
x0
template<class T > T TRectT< T >::x0
if x0>x1 || y0>y1 then rect is empty if x0==y1 && y0==y1 and rect is a TRectD then rect is empty
Referenced by FlipBook::adaptGeometryForFullPreview(), ImageViewer::adaptView(), FlipBook::adaptWidGeometry(), TVectorImage::addStroke(), ImageRasterizer::build(), TRectT< T >::convert(), PlasticDeformerFx::doDryCompute(), BacklitFx::doDryCompute(), BodyHighLightFx::doDryCompute(), WarpFx::doDryCompute(), MosaicFx::doDryCompute(), HookTool::draw(), PumpTool::draw(), CameraTestTool::draw(), SetScanCropboxTool::draw(), ThumbnailViewer::drawBackground(), ThumbnailViewer::drawItem(), SceneViewer::drawOverlay(), Stage::RasterPainter::drawRasterImages(), RadialBlurFx::enlarge(), SpinBlurFx::enlarge(), TQuadratic::getBBox(), TXsheet::getBBox(), ImageViewer::getImgToWidgetAffine(), TCamera::getInterestStageRect(), MosaicFx::getMemoryRequirement(), BilinearDistorter::invMap(), PerspectiveDistorter::invMap(), TRasterFx::memorySize(), Stage::Picker::onImage(), TRectT< T >::operator*(), TRectT< T >::operator+(), TRop::over(), AreaFiller::rectFill(), ToonzScene::renderFrame(), CustomStyleManager::StyleLoaderTask::run(), TCamera::setInterestRect(), TCamera::setInterestStageRect(), and TFxCacheManager::Imp::subdivideIntoSmallerTiles().
x1
template<class T > T TRectT< T >::x1
y0
template<class T > T TRectT< T >::y0
y1
template<class T > T TRectT< T >::y1
The documentation for this class was generated from the following file:
E:/opentoonz/toonz/sources/include/tgeometry.h