opentoonz: ToonzVectorBrushTool Class Reference
ToonzVectorBrushTool Class Reference final
Public Member Functions
ToonzVectorBrushTool (std::string name, int targetType)
ToolType getToolType () const override
ToolOptionsBox * createOptionsBox () override
void updateTranslation () override
void onActivate () override
Callback invoked whenever the tool activates.
void onDeactivate () override
Callback for tool deactivation, includes tool switch.
bool preLeftButtonDown () override
void leftButtonDown (const TPointD &pos, const TMouseEvent &e) override
void leftButtonDrag (const TPointD &pos, const TMouseEvent &e) override
void leftButtonUp (const TPointD &pos, const TMouseEvent &e) override
void mouseMove (const TPointD &pos, const TMouseEvent &e) override
bool keyDown (QKeyEvent *event) override
void draw () override
Draws the tool on the viewer.
void onEnter () override
Callback for the mouse entering the viewer area.
void onLeave () override
Callback for the mouse leaving the viewer area.
int getCursorId () const override
Returns the type of cursor used by the tool.
TPropertyGroup * getProperties (int targetType) override
bool onPropertyChanged (std::string propertyName) override
void resetFrameRange ()
void initPresets ()
void loadPreset ()
void addPreset (QString name)
void removePreset ()
void loadLastBrush ()
bool isPencilModeActive () override
void addTrackPoint (const TThickPoint &point, double pixelSize2)
void flushTrackPoint ()
bool doFrameRangeStrokes (TFrameId firstFrameId, TStroke *firstStroke, TFrameId lastFrameId, TStroke *lastStroke, int interpolationType, bool breakAngles, bool autoGroup=false, bool autoFill=false, bool drawFirstStroke=true, bool drawLastStroke=true, bool withUndo=true)
void checkGuideSnapping (bool beforeMousePress, bool invertCheck)
void checkStrokeSnapping (bool beforeMousePress, bool invertCheck)
bool doGuidedAutoInbetween (TFrameId cFid, const TVectorImageP &cvi, TStroke *cStroke, bool breakAngles, bool autoGroup=false, bool autoFill=false, bool drawStroke=true)
Public Member Functions inherited from TTool
TTool (std::string toolName)
every tool (invoking updateTranslation() for each).
virtual ToolType getToolType () const =0
ToolTargetType getTargetType () const
std::string getName () const
virtual ToolOptionsBox * createOptionsBox ()
void setViewer (Viewer *viewer)
Viewer * getViewer () const
double getPixelSize () const
void invalidate (const TRectD &rect=TRectD())
int pick (const TPointD &p)
bool isPicking () const
virtual void updateTranslation ()
virtual bool preLeftButtonDown ()
virtual void mouseMove (const TPointD &, const TMouseEvent &)
virtual void leftButtonDown (const TPointD &, const TMouseEvent &)
virtual void leftButtonDrag (const TPointD &, const TMouseEvent &)
virtual void leftButtonUp (const TPointD &, const TMouseEvent &)
virtual void leftButtonDoubleClick (const TPointD &, const TMouseEvent &)
virtual void rightButtonDown (const TPointD &, const TMouseEvent &)
virtual bool keyDown (QKeyEvent *)
virtual void onInputText (std::wstring, std::wstring, int, int)
virtual void onSetViewer ()
virtual void onActivate ()
Callback invoked whenever the tool activates.
virtual void onDeactivate ()
Callback for tool deactivation, includes tool switch.
virtual void onImageChanged ()
Notifies changes in the image in use.
virtual void onEnter ()
Callback for the mouse entering the viewer area.
virtual void onLeave ()
Callback for the mouse leaving the viewer area.
virtual void onFrameSwitched ()
virtual void reset ()
virtual void draw ()
Draws the tool on the viewer.
bool isActive () const
Used to know if a tool is active, (used in TextTool only).
void setActive (bool active)
virtual TPropertyGroup * getProperties (int)
virtual bool onPropertyChanged (std::string propertyName)
virtual TSelection * getSelection ()
Returns a pointer to the tool selection.
virtual int getCursorId () const
Returns the type of cursor used by the tool.
virtual bool isEventAcceptable (QEvent *e)
TXsheet * getXsheet () const
Returns a pointer to the actual Xsheet.
int getFrame ()
Returns the actual frame in use.
int getColumnIndex ()
Returns the actual column index.
TStageObjectId getObjectId () const
Returns a pointer to the actual stage object.
void notifyImageChanged ()
void notifyImageChanged (const TFrameId &fid)
images on the level view.
TFrameId getCurrentFid () const
Returns the number of the actual editing frame.
const TAffine & getMatrix () const
void setMatrix (const TAffine &matrix)
TAffine getCurrentColumnMatrix (int frame=-1) const
TAffine getCurrentColumnParentMatrix () const
TAffine getCurrentObjectParentMatrix () const
TAffine getCurrentObjectParentMatrix2 () const
TAffine getColumnMatrix (int index, int frame=-1) const
virtual void updateMatrix ()
virtual void addContextMenuItems (QMenu *menu)
void enable (bool on)
bool isEnabled () const
QString updateEnabled ()
virtual QString updateEnabled (int rowIndex, int columnIndex)
bool isColumnLocked (int columnIndex) const
void resetInputMethod ()
Resets Input Context (IME)
virtual bool isPencilModeActive ()
virtual bool isDragging () const
void setSelectedFrames (const std::set< TFrameId > &selectedFrames)
void tweenSelectedGuideStrokes ()
void tweenGuideStrokeToSelected ()
void flipGuideStrokeDirection (int mode)
Protected Attributes
TPropertyGroup m_prop [2]
TDoublePairProperty m_thickness
TDoubleProperty m_accuracy
TDoubleProperty m_smooth
TEnumProperty m_preset
TBoolProperty m_breakAngles
TBoolProperty m_pressure
TBoolProperty m_snap
TEnumProperty m_frameRange
TEnumProperty m_snapSensitivity
TEnumProperty m_capStyle
TEnumProperty m_joinStyle
TIntProperty m_miterJoinLimit
StrokeGenerator m_track
StrokeGenerator m_rangeTrack
RasterStrokeGenerator * m_rasterTrack
TStroke * m_firstStroke
TTileSetCM32 * m_tileSet
TTileSaverCM32 * m_tileSaver
TFrameId m_firstFrameId
TFrameId m_veryFirstFrameId
TPixel32 m_currentColor
int m_styleId
double m_minThick
double m_maxThick
int m_strokeIndex1
int m_strokeIndex2
int m_col
int m_firstFrame
int m_veryFirstFrame
int m_veryFirstCol
int m_targetType
double m_w1
double m_w2
double m_pixelSize
double m_currThickness
double m_minDistance2
bool m_foundFirstSnap = false
bool m_foundLastSnap = false
bool m_dragDraw = true
bool m_altPressed = false
bool m_snapSelf = false
TRectD m_modifiedRegion
TPointD m_dpiScale
TPointD m_mousePos
Current mouse position, in world coordinates.
TPointD m_brushPos
World position the brush will be painted at.
TPointD m_firstSnapPoint
TPointD m_lastSnapPoint
BluredBrush * m_bluredBrush
QRadialGradient m_brushPad
TRasterCM32P m_backupRas
TRaster32P m_workRas
std::vector< TThickPoint > m_points
TRect m_strokeRect
TRect m_lastRect
SmoothStroke m_smoothStroke
VectorBrushPresetManager m_presetsManager
Manager for presets of this tool instance.
bool m_active
bool m_enabled
bool m_isPrompting
bool m_firstTime
bool m_isPath
bool m_presetsLoaded
bool m_firstFrameRange
TFrameId m_workingFrameId
TPointD m_lastDragPos
Position where mouse was last dragged.
TMouseEvent m_lastDragEvent
Previous mouse-drag event.
bool m_propertyUpdating = false
Protected Attributes inherited from TTool
std::string m_name
The tool's name.
Viewer * m_viewer
Tool's current viewer.
TAffine m_matrix
World-to-window reference change affine.
int m_targetType
The tool's image type target.
bool m_enabled
Whether the tool allows user interaction.
bool m_active
bool m_picking
Additional Inherited Members
Public Types inherited from TTool
enum ToolType {
GenericTool = 1 , ColumnTool = 2 , LevelReadTool = 4 , LevelWriteTool ,
LevelTool = LevelReadTool | LevelWriteTool
}
Tool editing type.
enum ToolTargetType {
NoTarget = 0x0 , VectorImage = 0x1 , ToonzImage = 0x2 , RasterImage = 0x4 ,
MeshImage = 0x8 , Splines = 0x10 , LevelColumns = 0x20 , MeshColumns = 0x40 ,
EmptyTarget = 0x80 , CommonImages = VectorImage | ToonzImage | RasterImage , AllImages = CommonImages | MeshImage , Vectors = VectorImage | Splines ,
CommonLevels = CommonImages | LevelColumns , MeshLevels = MeshImage | MeshColumns , AllTargets = 0xffffffff
}
Object types the tool can operate on.
typedef TApplication Application
Static Public Member Functions inherited from TTool
static TTool * getTool (std::string toolName, ToolTargetType targetType)
static TApplication * getApplication ()
static void setApplication (TApplication *application)
static TXshCell getImageCell ()
Returns the level-frame pair to be edited by the tool.
static TImage * getImage (bool toBeModified, int subsampling=0)
Returns the image to be edited by the tool.
static TImage * touchImage ()
static void updateToolsPropertiesTranslation ()
static const std::set< TFrameId > & getSelectedFrames ()
Static Public Attributes inherited from TTool
static std::vector< CellOps > m_cellsData
static bool m_isLevelCreated = false
static bool m_isFrameCreated = false
static std::vector< TFrameId > m_oldFids
static std::vector< TFrameId > m_newFids
static bool m_isLevelRenumbererd = false
Protected Member Functions inherited from TTool
void bind (int targetType)
virtual void onSelectedFramesChanged ()
virtual QString disableString ()
Returns a custom reason to disable the tool.
Static Protected Attributes inherited from TTool
static TApplication * m_application = 0
static std::set< TFrameId > m_selectedFrames = std::set<TFrameId>()
Detailed Description
Constructor & Destructor Documentation
ToonzVectorBrushTool()
ToonzVectorBrushTool::ToonzVectorBrushTool (std::string name, int targetType)
    : TTool(name)
    , m_thickness("Size", 0, 1000, 0, 5)
    , m_accuracy("Accuracy:", 1, 100, 20)
    , m_smooth("Smooth:", 0, 50, 0)
    , m_preset("Preset:")
    , m_breakAngles("Break", true)
    , m_pressure("Pressure", true)
    , m_capStyle("Cap")
    , m_joinStyle("Join")
    , m_miterJoinLimit("Miter:", 0, 100, 4)
    , m_rasterTrack(0)
    , m_styleId(0)
    , m_modifiedRegion()
    , m_bluredBrush(0)
    , m_active(false)
    , m_enabled(false)
    , m_isPrompting(false)
    , m_firstTime(true)
    , m_firstFrameRange(true)
    , m_presetsLoaded(false)
    , m_frameRange("Range:")
    , m_snap("Snap", false)
    , m_snapSensitivity("Sensitivity:")
    , m_targetType(targetType)
    , m_workingFrameId(TFrameId()) {
  bind(targetType);
  m_thickness.setNonLinearSlider();
  m_prop[0].bind(m_thickness);
  m_prop[0].bind(m_accuracy);
  m_prop[0].bind(m_smooth);
  m_prop[0].bind(m_breakAngles);
  m_prop[0].bind(m_pressure);
  m_prop[0].bind(m_frameRange);
  m_frameRange.addValue(L"Off");
  m_frameRange.addValue(LINEAR_WSTR);
  m_frameRange.addValue(EASEIN_WSTR);
  m_frameRange.addValue(EASEOUT_WSTR);
  m_frameRange.addValue(EASEINOUT_WSTR);
  m_prop[0].bind(m_snap);
  m_prop[0].bind(m_snapSensitivity);
  m_snapSensitivity.addValue(LOW_WSTR);
  m_snapSensitivity.addValue(MEDIUM_WSTR);
  m_snapSensitivity.addValue(HIGH_WSTR);
  m_prop[0].bind(m_preset);
  m_preset.addValue(CUSTOM_WSTR);
  m_prop[1].bind(m_capStyle);
  m_capStyle.addValue(BUTT_WSTR, QString::fromStdWString(BUTT_WSTR));
  m_capStyle.addValue(ROUNDC_WSTR, QString::fromStdWString(ROUNDC_WSTR));
  m_capStyle.addValue(PROJECTING_WSTR,
                      QString::fromStdWString(PROJECTING_WSTR));
  m_prop[1].bind(m_joinStyle);
  m_joinStyle.addValue(MITER_WSTR, QString::fromStdWString(MITER_WSTR));
  m_joinStyle.addValue(ROUNDJ_WSTR, QString::fromStdWString(ROUNDJ_WSTR));
  m_joinStyle.addValue(BEVEL_WSTR, QString::fromStdWString(BEVEL_WSTR));
  m_prop[1].bind(m_miterJoinLimit);
  m_breakAngles.setId("BreakSharpAngles");
  m_frameRange.setId("FrameRange");
  m_snap.setId("Snap");
  m_snapSensitivity.setId("SnapSensitivity");
  m_preset.setId("BrushPreset");
  m_pressure.setId("PressureSensitivity");
  m_capStyle.setId("Cap");
  m_joinStyle.setId("Join");
  m_miterJoinLimit.setId("Miter");
}
Member Function Documentation
addPreset()
void ToonzVectorBrushTool::addPreset (QString name)
{
  // Build the preset
  VectorBrushData preset(name.toStdWString());
  preset.m_min = m_thickness.getValue().first;
  preset.m_max = m_thickness.getValue().second;
  preset.m_acc         = m_accuracy.getValue();
  preset.m_smooth      = m_smooth.getValue();
  preset.m_breakAngles = m_breakAngles.getValue();
  preset.m_pressure    = m_pressure.getValue();
  preset.m_cap         = m_capStyle.getIndex();
  preset.m_join        = m_joinStyle.getIndex();
  preset.m_miter       = m_miterJoinLimit.getValue();
  // Pass the preset to the manager
  m_presetsManager.addPreset(preset);
  // Reinitialize the associated preset enum
  initPresets();
  // Set the value to the specified one
  m_preset.setValue(preset.m_name);
  V_VectorBrushPreset = m_preset.getValueAsString();
}
addTrackPoint()
void ToonzVectorBrushTool::addTrackPoint (const TThickPoint & point, double pixelSize2)
{
  m_smoothStroke.addPoint(point);
  std::vector<TThickPoint> pts;
  m_smoothStroke.getSmoothPoints(pts);
  for (size_t i = 0; i < pts.size(); ++i) {
    m_track.add(pts[i], pixelSize2);
  }
}
checkGuideSnapping()
void ToonzVectorBrushTool::checkGuideSnapping (bool beforeMousePress, bool invertCheck)
{
  if (Preferences::instance()->getVectorSnappingTarget() == 0) return;
  bool foundSnap;
  TPointD snapPoint;
  beforeMousePress ? foundSnap = m_foundFirstSnap : foundSnap = m_foundLastSnap;
  beforeMousePress ? snapPoint = m_firstSnapPoint : snapPoint = m_lastSnapPoint;
  bool checkSnap = m_snap.getValue();
  if (invertCheck) checkSnap = !checkSnap;
  if (checkSnap) {
    // check guide snapping
    int vGuideCount = 0, hGuideCount = 0;
    double guideDistance  = sqrt(m_minDistance2);
    TTool::Viewer *viewer = getViewer();
    if (viewer) {
      vGuideCount = viewer->getVGuideCount();
      hGuideCount = viewer->getHGuideCount();
    }
    double distanceToVGuide = -1.0, distanceToHGuide = -1.0;
    double vGuide, hGuide;
    bool useGuides = false;
    if (vGuideCount) {
      for (int j = 0; j < vGuideCount; j++) {
        double guide        = viewer->getVGuide(j);
        double tempDistance = std::abs(guide - m_mousePos.y);
        if (tempDistance < guideDistance &&
            (distanceToVGuide < 0 || tempDistance < distanceToVGuide)) {
          distanceToVGuide = tempDistance;
          vGuide           = guide;
          useGuides        = true;
        }
      }
    }
    if (hGuideCount) {
      for (int j = 0; j < hGuideCount; j++) {
        double guide        = viewer->getHGuide(j);
        double tempDistance = std::abs(guide - m_mousePos.x);
        if (tempDistance < guideDistance &&
            (distanceToHGuide < 0 || tempDistance < distanceToHGuide)) {
          distanceToHGuide = tempDistance;
          hGuide           = guide;
          useGuides        = true;
        }
      }
    }
    if (useGuides && foundSnap) {
      double currYDistance = std::abs(snapPoint.y - m_mousePos.y);
      double currXDistance = std::abs(snapPoint.x - m_mousePos.x);
      double hypotenuse =
          sqrt(pow(currYDistance, 2.0) + pow(currXDistance, 2.0));
      if ((distanceToVGuide >= 0 && distanceToVGuide < hypotenuse) ||
          (distanceToHGuide >= 0 && distanceToHGuide < hypotenuse)) {
        useGuides  = true;
        m_snapSelf = false;
      } else
        useGuides = false;
    }
    if (useGuides) {
      assert(distanceToHGuide >= 0 || distanceToVGuide >= 0);
      if (distanceToHGuide < 0 ||
          (distanceToVGuide <= distanceToHGuide && distanceToVGuide >= 0)) {
        snapPoint.y = vGuide;
        snapPoint.x = m_mousePos.x;
      } else {
        snapPoint.y = m_mousePos.y;
        snapPoint.x = hGuide;
      }
      beforeMousePress ? m_foundFirstSnap = true : m_foundLastSnap = true;
      beforeMousePress ? m_firstSnapPoint                          = snapPoint
                       : m_lastSnapPoint                           = snapPoint;
    }
  }
}
checkStrokeSnapping()
void ToonzVectorBrushTool::checkStrokeSnapping (bool beforeMousePress, bool invertCheck)
{
  if (Preferences::instance()->getVectorSnappingTarget() == 1) return;
  TVectorImageP vi(getImage(false));
  bool checkSnap = m_snap.getValue();
  if (invertCheck) checkSnap = !checkSnap;
  m_dragDraw = true;
  if (vi && checkSnap) {
    double minDistance2 = m_minDistance2;
    if (beforeMousePress)
      m_strokeIndex1 = -1;
    else
      m_strokeIndex2 = -1;
    int i, strokeNumber = vi->getStrokeCount();
    TStroke *stroke;
    double distance2, outW;
    bool snapFound = false;
    TThickPoint point1;
    for (i = 0; i < strokeNumber; i++) {
      stroke = vi->getStroke(i);
      if (stroke->getNearestW(m_mousePos, outW, distance2) &&
          distance2 < minDistance2) {
        minDistance2                      = distance2;
        beforeMousePress ? m_strokeIndex1 = i : m_strokeIndex2 = i;
        if (areAlmostEqual(outW, 0.0, 1e-3))
          beforeMousePress ? m_w1 = 0.0 : m_w2 = 0.0;
        else if (areAlmostEqual(outW, 1.0, 1e-3))
          beforeMousePress ? m_w1 = 1.0 : m_w2 = 1.0;
        else
          beforeMousePress ? m_w1 = outW : m_w2 = outW;
        beforeMousePress ? point1 = stroke->getPoint(m_w1)
                         : point1 = stroke->getPoint(m_w2);
        snapFound                 = true;
      }
    }
    // compare to first point of current stroke
    if (beforeMousePress && snapFound) {
      m_firstSnapPoint = TPointD(point1.x, point1.y);
      m_foundFirstSnap = true;
    } else if (!beforeMousePress) {
      if (!snapFound) {
        TPointD tempPoint        = m_track.getFirstPoint();
        double distanceFromStart = tdistance2(m_mousePos, tempPoint);
        if (distanceFromStart < m_minDistance2) {
          point1     = tempPoint;
          distance2  = distanceFromStart;
          snapFound  = true;
          m_snapSelf = true;
        }
      }
      if (snapFound) {
        m_lastSnapPoint = TPointD(point1.x, point1.y);
        m_foundLastSnap = true;
        if (distance2 < 2.0) m_dragDraw = false;
      }
    }
  }
}
createOptionsBox()
ToolOptionsBox * ToonzVectorBrushTool::createOptionsBox () override virtual
The default returns a generic box containing the options for property group 0).
See also
See tooloptions.h for more details. Factory function returning a newly created GUI options box to be displayed for the tool
Reimplemented from TTool.
{
  TPaletteHandle *currPalette =
      TTool::getApplication()->getPaletteController()->getCurrentLevelPalette();
  ToolHandle *currTool = TTool::getApplication()->getCurrentTool();
  return new BrushToolOptionsBox(0, this, currPalette, currTool);
}
doFrameRangeStrokes()
bool ToonzVectorBrushTool::doFrameRangeStrokes (TFrameId firstFrameId, TStroke * firstStroke, TFrameId lastFrameId, TStroke * lastStroke, int interpolationType, bool breakAngles, bool autoGroup = false, bool autoFill = false, bool drawFirstStroke = true, bool drawLastStroke = true, bool withUndo = true)
                   {
  TXshSimpleLevel *sl =
      TTool::getApplication()->getCurrentLevel()->getLevel()->getSimpleLevel();
  TStroke *first           = new TStroke();
  TStroke *last            = new TStroke();
  TVectorImageP firstImage = new TVectorImage();
  TVectorImageP lastImage  = new TVectorImage();
  *first       = *firstStroke;
  *last        = *lastStroke;
  bool swapped = false;
  if (firstFrameId > lastFrameId) {
    std::swap(firstFrameId, lastFrameId);
    *first  = *lastStroke;
    *last   = *firstStroke;
    swapped = true;
  }
  firstImage->addStroke(first, false);
  lastImage->addStroke(last, false);
  assert(firstFrameId <= lastFrameId);
  std::vector<TFrameId> allFids;
  sl->getFids(allFids);
  std::vector<TFrameId>::iterator i0 = allFids.begin();
  while (i0 != allFids.end() && *i0 < firstFrameId) i0++;
  if (i0 == allFids.end()) return false;
  std::vector<TFrameId>::iterator i1 = i0;
  while (i1 != allFids.end() && *i1 <= lastFrameId) i1++;
  assert(i0 < i1);
  std::vector<TFrameId> fids(i0, i1);
  int m = fids.size();
  assert(m > 0);
  if (withUndo) TUndoManager::manager()->beginBlock();
  int row = getApplication()->getCurrentFrame()->isEditingScene()
                ? getApplication()->getCurrentFrame()->getFrameIndex()
                : -1;
  TFrameId cFid = getApplication()->getCurrentFrame()->getFid();
  for (int i = 0; i < m; ++i) {
    TFrameId fid = fids[i];
    assert(firstFrameId <= fid && fid <= lastFrameId);
    // This is an attempt to divide the tween evenly
    double t = m > 1 ? (double)i / (double)(m - 1) : 0.5;
    double s = t;
    switch (interpolationType) {
    case 1:  // LINEAR_WSTR
      break;
    case 2:  // EASEIN_WSTR
      s = t * (2 - t);
      break;  // s'(1) = 0
    case 3:   // EASEOUT_WSTR
      s = t * t;
      break;  // s'(0) = 0
    case 4:   // EASEINOUT_WSTR:
      s = t * t * (3 - 2 * t);
      break;  // s'(0) = s'(1) = 0
    }
    TTool::Application *app = TTool::getApplication();
    if (app) app->getCurrentFrame()->setFid(fid);
    TVectorImageP img = sl->getFrame(fid, true);
    if (t == 0) {
      if (!swapped && !drawFirstStroke) {
      } else
        addStrokeToImage(getApplication(), img, firstImage->getStroke(0),
                         breakAngles, autoGroup, autoFill, m_isFrameCreated,
                         m_isLevelCreated, sl, fid);
    } else if (t == 1) {
      if (swapped && !drawFirstStroke) {
      } else if (drawLastStroke)
        addStrokeToImage(getApplication(), img, lastImage->getStroke(0),
                         breakAngles, autoGroup, autoFill, m_isFrameCreated,
                         m_isLevelCreated, sl, fid);
    } else {
      assert(firstImage->getStrokeCount() == 1);
      assert(lastImage->getStrokeCount() == 1);
      TVectorImageP vi = TInbetween(firstImage, lastImage).tween(s);
      assert(vi->getStrokeCount() == 1);
      addStrokeToImage(getApplication(), img, vi->getStroke(0), breakAngles,
                       autoGroup, autoFill, m_isFrameCreated, m_isLevelCreated,
                       sl, fid);
    }
  }
  if (row != -1)
    getApplication()->getCurrentFrame()->setFrame(row);
  else
    getApplication()->getCurrentFrame()->setFid(cFid);
  if (withUndo) TUndoManager::manager()->endBlock();
  notifyImageChanged();
  return true;
}
doGuidedAutoInbetween()
bool ToonzVectorBrushTool::doGuidedAutoInbetween (TFrameId cFid, const TVectorImageP & cvi, TStroke * cStroke, bool breakAngles, bool autoGroup = false, bool autoFill = false, bool drawStroke = true)
{
  TApplication *app = TTool::getApplication();
  if (cFid.isEmptyFrame() || cFid.isNoFrame() || !cvi || !cStroke) return false;
  TXshSimpleLevel *sl = app->getCurrentLevel()->getLevel()->getSimpleLevel();
  if (!sl) return false;
  int osBack  = -1;
  int osFront = -1;
  getViewer()->getGuidedFrameIdx(&osBack, &osFront);
  TFrameHandle *currentFrame = getApplication()->getCurrentFrame();
  bool resultBack            = false;
  bool resultFront           = false;
  TFrameId oFid;
  int cStrokeIdx = cvi->getStrokeCount();
  if (!drawStroke) cStrokeIdx--;
  TUndoManager::manager()->beginBlock();
  if (osBack != -1) {
    if (currentFrame->isEditingScene()) {
      TXsheet *xsh = app->getCurrentXsheet()->getXsheet();
      int col      = app->getCurrentColumn()->getColumnIndex();
      if (xsh && col >= 0) {
        TXshCell cell = xsh->getCell(osBack, col);
        if (!cell.isEmpty()) oFid = cell.getFrameId();
      }
    } else
      oFid = sl->getFrameId(osBack);
    TVectorImageP fvi = sl->getFrame(oFid, false);
    int fStrokeCount  = fvi ? fvi->getStrokeCount() : 0;
    int strokeIdx = getViewer()->getGuidedBackStroke() != -1
                        ? getViewer()->getGuidedBackStroke()
                        : cStrokeIdx;
    if (!oFid.isEmptyFrame() && oFid != cFid && fvi && fStrokeCount &&
        strokeIdx < fStrokeCount) {
      TStroke *fStroke = fvi->getStroke(strokeIdx);
      bool frameCreated = m_isFrameCreated;
      m_isFrameCreated  = false;
      touchImage();
      resultBack        = doFrameRangeStrokes(
          oFid, fStroke, cFid, cStroke,
          Preferences::instance()->getGuidedInterpolation(), breakAngles,
          autoGroup, autoFill, false, drawStroke, false);
      m_isFrameCreated = frameCreated;
    }
  }
  if (osFront != -1) {
    bool drawFirstStroke = (osBack != -1 && resultBack) ? false : true;
    if (currentFrame->isEditingScene()) {
      TXsheet *xsh = app->getCurrentXsheet()->getXsheet();
      int col      = app->getCurrentColumn()->getColumnIndex();
      if (xsh && col >= 0) {
        TXshCell cell = xsh->getCell(osFront, col);
        if (!cell.isEmpty()) oFid = cell.getFrameId();
      }
    } else
      oFid = sl->getFrameId(osFront);
    TVectorImageP fvi = sl->getFrame(oFid, false);
    int fStrokeCount  = fvi ? fvi->getStrokeCount() : 0;
    int strokeIdx = getViewer()->getGuidedFrontStroke() != -1
                        ? getViewer()->getGuidedFrontStroke()
                        : cStrokeIdx;
    if (!oFid.isEmptyFrame() && oFid != cFid && fvi && fStrokeCount &&
        strokeIdx < fStrokeCount) {
      TStroke *fStroke = fvi->getStroke(strokeIdx);
      bool frameCreated = m_isFrameCreated;
      m_isFrameCreated  = false;
      touchImage();
      resultFront       = doFrameRangeStrokes(
          cFid, cStroke, oFid, fStroke,
          Preferences::instance()->getGuidedInterpolation(), breakAngles,
          autoGroup, autoFill, drawFirstStroke, false, false);
      m_isFrameCreated = frameCreated;
    }
  }
  TUndoManager::manager()->endBlock();
  return resultBack || resultFront;
}
draw()
void ToonzVectorBrushTool::draw () override virtual
Draws the tool on the viewer.
Reimplemented from TTool.
{
  /*----*/
  if (m_minThick == 0 && m_maxThick == 0 &&
      !Preferences::instance()->getShow0ThickLines())
    return;
  TImageP img = getImage(false, 1);
  // Draw track
  tglColor(m_isPrompting ? TPixel32::Green : m_currentColor);
  m_track.drawAllFragments();
  // snapping
  TVectorImageP vi = img;
  if (m_snap.getValue() != m_altPressed) {
    m_pixelSize  = getPixelSize();
    double thick = 6.0 * m_pixelSize;
    if (m_foundFirstSnap) {
      tglColor(TPixelD(0.1, 0.9, 0.1));
      tglDrawCircle(m_firstSnapPoint, thick);
    }
    TThickPoint point2;
    if (m_foundLastSnap) {
      tglColor(TPixelD(0.1, 0.9, 0.1));
      tglDrawCircle(m_lastSnapPoint, thick);
    }
  }
  // frame range
  if (m_firstStroke) {
    glColor3d(1.0, 0.0, 0.0);
    m_rangeTrack.drawAllFragments();
    glColor3d(0.0, 0.6, 0.0);
    TPointD firstPoint        = m_rangeTrack.getFirstPoint();
    TPointD topLeftCorner     = TPointD(firstPoint.x - 5, firstPoint.y - 5);
    TPointD topRightCorner    = TPointD(firstPoint.x + 5, firstPoint.y - 5);
    TPointD bottomLeftCorner  = TPointD(firstPoint.x - 5, firstPoint.y + 5);
    TPointD bottomRightCorner = TPointD(firstPoint.x + 5, firstPoint.y + 5);
    tglDrawSegment(topLeftCorner, bottomRightCorner);
    tglDrawSegment(topRightCorner, bottomLeftCorner);
  }
  if (getApplication()->getCurrentObject()->isSpline()) return;
  // If toggled off, don't draw brush outline
  if (!Preferences::instance()->isCursorOutlineEnabled()) return;
  // Don't draw brush outline if picking guiding stroke
  if (getViewer()->getGuidedStrokePickerMode()) return;
  // Draw the brush outline - change color when the Ink / Paint check is
  // activated
  if ((ToonzCheck::instance()->getChecks() & ToonzCheck::eInk) ||
      (ToonzCheck::instance()->getChecks() & ToonzCheck::ePaint) ||
      (ToonzCheck::instance()->getChecks() & ToonzCheck::eInk1))
    glColor3d(0.5, 0.8, 0.8);
  // normally draw in red
  else
    glColor3d(1.0, 0.0, 0.0);
  tglDrawCircle(m_brushPos, 0.5 * m_minThick);
  tglDrawCircle(m_brushPos, 0.5 * m_maxThick);
}
References StrokeGenerator::drawAllFragments(), ToonzCheck::eInk, ToonzCheck::eInk1, ToonzCheck::ePaint, TTool::getImage(), m_brushPos, and m_isPrompting.
flushTrackPoint()
void ToonzVectorBrushTool::flushTrackPoint ()
{
  m_smoothStroke.endStroke();
  std::vector<TThickPoint> pts;
  m_smoothStroke.getSmoothPoints(pts);
  double pixelSize2 = getPixelSize() * getPixelSize();
  for (size_t i = 0; i < pts.size(); ++i) {
    m_track.add(pts[i], pixelSize2);
  }
}
getCursorId()
int ToonzVectorBrushTool::getCursorId () const inline override virtual
Returns the type of cursor used by the tool.
See also
For a list of cursor ids cursor.h
Reimplemented from TTool.
{
    if (m_viewer && m_viewer->getGuidedStrokePickerMode())
      return m_viewer->getGuidedStrokePickerCursor();
    return ToolCursor::PenCursor;
  }
References TTool::m_viewer.
getProperties()
TPropertyGroup * ToonzVectorBrushTool::getProperties (int targetType) override virtual
Reimplemented from TTool.
{
  if (!m_presetsLoaded) initPresets();
  return &m_prop[idx];
}
getToolType()
ToolType ToonzVectorBrushTool::getToolType () const inline override virtual
Implements TTool.
{ return TTool::LevelWriteTool; }
initPresets()
void ToonzVectorBrushTool::initPresets ()
{
  if (!m_presetsLoaded) {
    // If necessary, load the presets from file
    m_presetsLoaded = true;
    m_presetsManager.load(TEnv::getConfigDir() + "brush_vector.txt");
  }
  // Rebuild the presets property entries
  const std::set<VectorBrushData> &presets = m_presetsManager.presets();
  m_preset.deleteAllValues();
  m_preset.addValue(CUSTOM_WSTR);
  m_preset.setItemUIName(CUSTOM_WSTR, tr("<custom>"));
  std::set<VectorBrushData>::const_iterator it, end = presets.end();
  for (it = presets.begin(); it != end; ++it) m_preset.addValue(it->m_name);
}
isPencilModeActive()
bool ToonzVectorBrushTool::isPencilModeActive () override virtual
BrushPaintBrushEraserToolPencilModeTrue
Reimplemented from TTool.
{ return false; }
keyDown()
bool ToonzVectorBrushTool::keyDown (QKeyEvent * event) override virtual
Reimplemented from TTool.
{
  if (event->key() == Qt::Key_Escape) {
    resetFrameRange();
  }
  return false;
}
leftButtonDown()
void ToonzVectorBrushTool::leftButtonDown (const TPointD & pos, const TMouseEvent & e) override virtual
Reimplemented from TTool.
{
  TTool::Application *app = TTool::getApplication();
  if (!app) return;
  if (getViewer() && getViewer()->getGuidedStrokePickerMode()) {
    getViewer()->doPickGuideStroke(pos);
    return;
  }
  int col   = app->getCurrentColumn()->getColumnIndex();
  m_isPath  = app->getCurrentObject()->isSpline();
  m_enabled = col >= 0 || m_isPath || app->getCurrentFrame()->isEditingLevel();
  // todo: gestire autoenable
  if (!m_enabled) return;
  if (!m_isPath) {
    m_currentColor = TPixel32::Black;
    m_active       = !!getImage(true);
    if (!m_active) {
      m_active = !!touchImage();
    }
    if (!m_active) return;
    if (m_active) {
      // nel caso che il colore corrente sia un cleanup/studiopalette color
      // oppure il colore di un colorfield
      m_styleId       = app->getCurrentLevelStyleIndex();
      TColorStyle *cs = app->getCurrentLevelStyle();
      if (cs) {
        TRasterStyleFx *rfx = cs ? cs->getRasterStyleFx() : 0;
        m_active =
            cs != 0 && (cs->isStrokeStyle() || (rfx && rfx->isInkStyle()));
        m_currentColor   = cs->getAverageColor();
        m_currentColor.m = 255;
      } else {
        m_styleId      = 1;
        m_currentColor = TPixel32::Black;
      }
    }
  } else {
    m_currentColor = TPixel32::Red;
    m_active       = true;
  }
  // assert(0<=m_styleId && m_styleId<2);
  m_track.clear();
  double thickness = (m_pressure.getValue() || m_isPath)
                         ? computeThickness(e.m_pressure, m_thickness, m_isPath)
                         : m_thickness.getValue().second * 0.5;
  /*--- Max ---*/
  if (m_pressure.getValue() && e.m_pressure == 1.0)
    thickness = m_thickness.getValue().first * 0.5;
  m_currThickness = thickness;
  m_smoothStroke.beginStroke(m_smooth.getValue());
  if (m_foundFirstSnap) {
    addTrackPoint(TThickPoint(m_firstSnapPoint, thickness),
                  getPixelSize() * getPixelSize());
  } else
    addTrackPoint(TThickPoint(pos, thickness), getPixelSize() * getPixelSize());
  TRectD invalidateRect = m_track.getLastModifiedRegion();
  invalidate(invalidateRect.enlarge(2));
  // updating m_brushPos is needed to refresh viewer properly
  m_brushPos = m_mousePos = pos;
}
leftButtonDrag()
void ToonzVectorBrushTool::leftButtonDrag (const TPointD & pos, const TMouseEvent & e) override virtual
Reimplemented from TTool.
{
  if (!m_enabled || !m_active) {
    m_brushPos = m_mousePos = pos;
    return;
  }
  m_lastDragPos   = pos;
  m_lastDragEvent = e;
  double thickness = (m_pressure.getValue() || m_isPath)
                         ? computeThickness(e.m_pressure, m_thickness, m_isPath)
                         : m_thickness.getValue().second * 0.5;
  TRectD invalidateRect;
  TPointD halfThick(m_maxThick * 0.5, m_maxThick * 0.5);
  TPointD snapThick(6.0 * m_pixelSize, 6.0 * m_pixelSize);
  // In order to clear the previous brush tip
  invalidateRect += TRectD(m_brushPos - halfThick, m_brushPos + halfThick);
  // In order to clear the previous snap indicator
  if (m_foundLastSnap)
    invalidateRect +=
        TRectD(m_lastSnapPoint - snapThick, m_lastSnapPoint + snapThick);
  m_currThickness = thickness;
  m_mousePos       = pos;
  m_lastSnapPoint  = pos;
  m_foundLastSnap  = false;
  m_foundFirstSnap = false;
  m_snapSelf       = false;
  m_altPressed     = e.isAltPressed() && !e.isCtrlPressed();
  checkStrokeSnapping(false, m_altPressed);
  checkGuideSnapping(false, m_altPressed);
  m_brushPos = m_lastSnapPoint;
  if (m_foundLastSnap)
    invalidateRect +=
        TRectD(m_lastSnapPoint - snapThick, m_lastSnapPoint + snapThick);
  if (e.isShiftPressed()) {
    m_smoothStroke.clearPoints();
    m_track.add(TThickPoint(m_brushPos, thickness),
                getPixelSize() * getPixelSize());
    m_track.removeMiddlePoints();
    invalidateRect += m_track.getModifiedRegion();
  } else if (m_dragDraw) {
    addTrackPoint(TThickPoint(pos, thickness), getPixelSize() * getPixelSize());
    invalidateRect += m_track.getLastModifiedRegion();
  }
  // In order to draw the current brush tip
  invalidateRect += TRectD(m_brushPos - halfThick, m_brushPos + halfThick);
  if (!invalidateRect.isEmpty()) {
    // for motion path, call the invalidate function directly to ignore dpi of
    // the current level
    if (m_isPath)
      m_viewer->GLInvalidateRect(invalidateRect.enlarge(2));
    else
      invalidate(invalidateRect.enlarge(2));
  }
}
leftButtonUp()
void ToonzVectorBrushTool::leftButtonUp (const TPointD & pos, const TMouseEvent & e) override virtual
Reimplemented from TTool.
{
  bool isValid = m_enabled && m_active;
  m_enabled    = false;
  if (!isValid) {
    // in case the current frame is moved to empty cell while dragging
    if (!m_track.isEmpty()) {
      m_track.clear();
      invalidate();
    }
    return;
  }
  if (m_isPath) {
    double error = 20.0 * getPixelSize();
    TStroke *stroke;
    if (e.isShiftPressed()) {
      m_track.removeMiddlePoints();
      stroke = m_track.makeStroke(0);
    } else {
      flushTrackPoint();
      stroke = m_track.makeStroke(error);
    }
    int points = stroke->getControlPointCount();
    TVectorImageP vi = getImage(true);
    struct Cleanup {
      ToonzVectorBrushTool *m_this;
      ~Cleanup() { m_this->m_track.clear(), m_this->invalidate(); }
    } cleanup = {this};
    if (!isJustCreatedSpline(vi.getPointer())) {
      m_isPrompting = true;
      QString question("Are you sure you want to replace the motion path?");
      int ret =
          DVGui::MsgBox(question, QObject::tr("Yes"), QObject::tr("No"), 0);
      m_isPrompting = false;
      if (ret == 2 || ret == 0) return;
    }
    QMutexLocker lock(vi->getMutex());
    TUndo *undo =
        new UndoPath(getXsheet()->getStageObject(getObjectId())->getSpline());
    while (vi->getStrokeCount() > 0) vi->deleteStroke(0);
    vi->addStroke(stroke, false);
    notifyImageChanged();
    TUndoManager::manager()->add(undo);
    return;
  }
  TVectorImageP vi = getImage(true);
  if (m_track.isEmpty()) {
    m_styleId = 0;
    m_track.clear();
    return;
  }
  if (vi && (m_snap.getValue() != m_altPressed) && m_foundLastSnap) {
    addTrackPoint(TThickPoint(m_lastSnapPoint, m_currThickness),
                  getPixelSize() * getPixelSize());
  }
  m_strokeIndex1   = -1;
  m_strokeIndex2   = -1;
  m_w1             = -1;
  m_w2             = -2;
  m_foundFirstSnap = false;
  m_foundLastSnap  = false;
  m_track.filterPoints();
  double error = 30.0 / (1 + 0.5 * m_accuracy.getValue());
  error *= getPixelSize();
  TStroke *stroke;
  if (e.isShiftPressed()) {
    m_track.removeMiddlePoints();
    stroke = m_track.makeStroke(0);
  } else {
    flushTrackPoint();
    stroke = m_track.makeStroke(error);
  }
  stroke->setStyle(m_styleId);
  {
    TStroke::OutlineOptions &options = stroke->outlineOptions();
    options.m_capStyle               = m_capStyle.getIndex();
    options.m_joinStyle              = m_joinStyle.getIndex();
    options.m_miterUpper             = m_miterJoinLimit.getValue();
  }
  m_styleId = 0;
  QMutexLocker lock(vi->getMutex());
  if (stroke->getControlPointCount() == 3 &&
      stroke->getControlPoint(0) !=
          stroke->getControlPoint(2))  // gli stroke con solo 1 chunk vengono
                                       // fatti dal tape tool...e devono venir
                                       // riconosciuti come speciali di
                                       // autoclose proprio dal fatto che
                                       // hanno 1 solo chunk.
    stroke->insertControlPoints(0.5);
  if (m_frameRange.getIndex()) {
    if (m_firstFrameId == -1) {
      m_firstStroke                   = new TStroke(*stroke);
      m_firstFrameId                  = getFrameId();
      TTool::Application *application = TTool::getApplication();
      if (application) {
        m_col        = application->getCurrentColumn()->getColumnIndex();
        m_firstFrame = application->getCurrentFrame()->getFrame();
      }
      m_rangeTrack = m_track;
      if (m_firstFrameRange) {
        m_veryFirstCol     = m_col;
        m_veryFirstFrame   = m_firstFrame;
        m_veryFirstFrameId = m_firstFrameId;
      }
    } else if (m_firstFrameId == getFrameId()) {
      if (m_firstStroke) {
        delete m_firstStroke;
        m_firstStroke = 0;
      }
      m_firstStroke = new TStroke(*stroke);
      m_rangeTrack  = m_track;
    } else {
      TFrameId currentId = getFrameId();
      int curCol = 0, curFrame = 0;
      TTool::Application *application = TTool::getApplication();
      if (application) {
        curCol   = application->getCurrentColumn()->getColumnIndex();
        curFrame = application->getCurrentFrame()->getFrame();
      }
      bool success = doFrameRangeStrokes(
          m_firstFrameId, m_firstStroke, getFrameId(), stroke,
          m_frameRange.getIndex(), m_breakAngles.getValue(), false, false,
          m_firstFrameRange);
      if (e.isCtrlPressed()) {
        if (application) {
          if (m_firstFrameId > currentId) {
            if (application->getCurrentFrame()->isEditingScene()) {
              application->getCurrentColumn()->setColumnIndex(curCol);
              application->getCurrentFrame()->setFrame(curFrame);
            } else
              application->getCurrentFrame()->setFid(currentId);
          }
        }
        resetFrameRange();
        m_firstStroke     = new TStroke(*stroke);
        m_rangeTrack      = m_track;
        m_firstFrameId    = currentId;
        m_firstFrameRange = false;
      }
      if (application && !e.isCtrlPressed()) {
        if (application->getCurrentFrame()->isEditingScene()) {
          application->getCurrentColumn()->setColumnIndex(m_veryFirstCol);
          application->getCurrentFrame()->setFrame(m_veryFirstFrame);
        } else
          application->getCurrentFrame()->setFid(m_veryFirstFrameId);
      }
      if (!e.isCtrlPressed()) {
        resetFrameRange();
      }
    }
    invalidate();
  } else {
    if (m_snapSelf) {
      stroke->setSelfLoop(true);
      m_snapSelf = false;
    }
    addStrokeToImage(getApplication(), vi, stroke, m_breakAngles.getValue(),
                     false, false, m_isFrameCreated, m_isLevelCreated);
    TRectD bbox = stroke->getBBox().enlarge(2) + m_track.getModifiedRegion();
    invalidate();  // should use bbox?
    if ((Preferences::instance()->getGuidedDrawingType() == 1 ||
         Preferences::instance()->getGuidedDrawingType() == 2) &&
        Preferences::instance()->getGuidedAutoInbetween()) {
      int fidx     = getApplication()->getCurrentFrame()->getFrameIndex();
      TFrameId fId = getFrameId();
      doGuidedAutoInbetween(fId, vi, stroke, m_breakAngles.getValue(), false,
                            false, false);
      if (getApplication()->getCurrentFrame()->isEditingScene())
        getApplication()->getCurrentFrame()->setFrame(fidx);
      else
        getApplication()->getCurrentFrame()->setFid(fId);
    }
  }
  assert(stroke);
  m_track.clear();
  m_altPressed = false;
}
loadLastBrush()
void ToonzVectorBrushTool::loadLastBrush ()
{
  // Properties tracked with preset
  m_thickness.setValue(
      TDoublePairProperty::Value(V_VectorBrushMinSize, V_VectorBrushMaxSize));
  m_capStyle.setIndex(V_VectorCapStyle);
  m_joinStyle.setIndex(V_VectorJoinStyle);
  m_miterJoinLimit.setValue(V_VectorMiterValue);
  m_breakAngles.setValue(V_BrushBreakSharpAngles ? 1 : 0);
  m_accuracy.setValue(V_BrushAccuracy);
  m_pressure.setValue(V_BrushPressureSensitivity ? 1 : 0);
  m_smooth.setValue(V_BrushSmooth);
  // Properties not tracked with preset
  m_frameRange.setIndex(V_VectorBrushFrameRange);
  m_snap.setValue(V_VectorBrushSnap);
  m_snapSensitivity.setIndex(V_VectorBrushSnapSensitivity);
  // Recalculate based on prior values
  m_minThick = m_thickness.getValue().first;
  m_maxThick = m_thickness.getValue().second;
  switch (V_VectorBrushSnapSensitivity) {
  case 0:
    m_minDistance2 = SNAPPING_LOW;
    break;
  case 1:
    m_minDistance2 = SNAPPING_MEDIUM;
    break;
  case 2:
    m_minDistance2 = SNAPPING_HIGH;
    break;
  }
}
loadPreset()
void ToonzVectorBrushTool::loadPreset ()
{
  const std::set<VectorBrushData> &presets = m_presetsManager.presets();
  std::set<VectorBrushData>::const_iterator it;
  it = presets.find(VectorBrushData(m_preset.getValue()));
  if (it == presets.end()) return;
  const VectorBrushData &preset = *it;
  try  // Don't bother with RangeErrors
  {
    m_thickness.setValue(
        TDoublePairProperty::Value(preset.m_min, preset.m_max));
    m_accuracy.setValue(preset.m_acc, true);
    m_smooth.setValue(preset.m_smooth, true);
    m_breakAngles.setValue(preset.m_breakAngles);
    m_pressure.setValue(preset.m_pressure);
    m_capStyle.setIndex(preset.m_cap);
    m_joinStyle.setIndex(preset.m_join);
    m_miterJoinLimit.setValue(preset.m_miter);
    // Recalculate based on updated presets
    m_minThick = m_thickness.getValue().first;
    m_maxThick = m_thickness.getValue().second;
  } catch (...) {
  }
}
mouseMove()
void ToonzVectorBrushTool::mouseMove (const TPointD & pos, const TMouseEvent & e) override virtual
Reimplemented from TTool.
{
  qApp->processEvents(QEventLoop::ExcludeUserInputEvents);
  struct Locals {
    ToonzVectorBrushTool *m_this;
    void setValue(TDoublePairProperty &prop,
                  const TDoublePairProperty::Value &value) {
      prop.setValue(value);
      m_this->onPropertyChanged(prop.getName());
      TTool::getApplication()->getCurrentTool()->notifyToolChanged();
    }
    void addMinMax(TDoublePairProperty &prop, double add) {
      if (add == 0.0) return;
      const TDoublePairProperty::Range &range = prop.getRange();
      TDoublePairProperty::Value value = prop.getValue();
      value.first  = tcrop(value.first + add, range.first, range.second);
      value.second = tcrop(value.second + add, range.first, range.second);
      setValue(prop, value);
    }
    void addMinMaxSeparate(TDoublePairProperty &prop, double min, double max) {
      if (min == 0.0 && max == 0.0) return;
      const TDoublePairProperty::Range &range = prop.getRange();
      TDoublePairProperty::Value value = prop.getValue();
      value.first += min;
      value.second += max;
      if (value.first > value.second) value.first = value.second;
      value.first  = tcrop(value.first, range.first, range.second);
      value.second = tcrop(value.second, range.first, range.second);
      setValue(prop, value);
    }
  } locals = {this};
  TPointD halfThick(m_maxThick * 0.5, m_maxThick * 0.5);
  TRectD invalidateRect(m_brushPos - halfThick, m_brushPos + halfThick);
  if (e.isCtrlPressed() && e.isAltPressed() && !e.isShiftPressed() &&
      Preferences::instance()->useCtrlAltToResizeBrushEnabled()) {
    // Resize the brush if CTRL+ALT is pressed and the preference is enabled.
    const TPointD &diff = pos - m_mousePos;
    double max          = diff.x / 2;
    double min          = diff.y / 2;
    locals.addMinMaxSeparate(m_thickness, min, max);
    double radius = m_thickness.getValue().second * 0.5;
    invalidateRect += TRectD(m_brushPos - TPointD(radius, radius),
                             m_brushPos + TPointD(radius, radius));
  } else {
    m_mousePos = pos;
    m_brushPos = pos;
    TPointD snapThick(6.0 * m_pixelSize, 6.0 * m_pixelSize);
    // In order to clear the previous snap indicator
    if (m_foundFirstSnap)
      invalidateRect +=
          TRectD(m_firstSnapPoint - snapThick, m_firstSnapPoint + snapThick);
    m_firstSnapPoint = pos;
    m_foundFirstSnap = false;
    m_altPressed     = e.isAltPressed() && !e.isCtrlPressed();
    checkStrokeSnapping(true, m_altPressed);
    checkGuideSnapping(true, m_altPressed);
    m_brushPos = m_firstSnapPoint;
    // In order to draw the snap indicator
    if (m_foundFirstSnap)
      invalidateRect +=
          TRectD(m_firstSnapPoint - snapThick, m_firstSnapPoint + snapThick);
    invalidateRect += TRectD(pos - halfThick, pos + halfThick);
  }
  invalidate(invalidateRect.enlarge(2));
  if (m_minThick == 0 && m_maxThick == 0) {
    m_minThick = m_thickness.getValue().first;
    m_maxThick = m_thickness.getValue().second;
  }
}
onActivate()
void ToonzVectorBrushTool::onActivate () override virtual
Callback invoked whenever the tool activates.
Reimplemented from TTool.
{
  if (m_firstTime) {
    m_firstTime = false;
    std::wstring wpreset =
        QString::fromStdString(V_VectorBrushPreset.getValue()).toStdWString();
    if (wpreset != CUSTOM_WSTR) {
      initPresets();
      if (!m_preset.isValue(wpreset)) wpreset = CUSTOM_WSTR;
      m_preset.setValue(wpreset);
      V_VectorBrushPreset = m_preset.getValueAsString();
      loadPreset();
    } else
      loadLastBrush();
  }
  resetFrameRange();
  // TODO:app->editImageOrSpline();
}
onDeactivate()
void ToonzVectorBrushTool::onDeactivate () override virtual
Callback for tool deactivation, includes tool switch.
Reimplemented from TTool.
{
  /*---
   * onDeactivateMouseRelease
   * ---*/
  // End current stroke.
  if (m_active && m_enabled) {
    leftButtonUp(m_lastDragPos, m_lastDragEvent);
  }
  if (m_tileSaver && !m_isPath) {
    m_enabled = false;
  }
  m_workRas   = TRaster32P();
  m_backupRas = TRasterCM32P();
  resetFrameRange();
}
References m_lastDragEvent, and m_lastDragPos.
onEnter()
void ToonzVectorBrushTool::onEnter () override virtual
Callback for the mouse entering the viewer area.
Reimplemented from TTool.
{
  TImageP img = getImage(false);
  m_minThick = m_thickness.getValue().first;
  m_maxThick = m_thickness.getValue().second;
  Application *app = getApplication();
  m_styleId       = app->getCurrentLevelStyleIndex();
  TColorStyle *cs = app->getCurrentLevelStyle();
  if (cs) {
    TRasterStyleFx *rfx = cs->getRasterStyleFx();
    m_active            = cs->isStrokeStyle() || (rfx && rfx->isInkStyle());
    m_currentColor      = cs->getAverageColor();
    m_currentColor.m    = 255;
  } else {
    m_currentColor = TPixel32::Black;
  }
  m_active = img;
}
References TColorStyle::getAverageColor(), TTool::getImage(), TColorStyle::getRasterStyleFx(), and TColorStyle::isStrokeStyle().
onLeave()
void ToonzVectorBrushTool::onLeave () override virtual
Callback for the mouse leaving the viewer area.
Reimplemented from TTool.
{
  m_minThick = 0;
  m_maxThick = 0;
}
onPropertyChanged()
bool ToonzVectorBrushTool::onPropertyChanged (std::string propertyName) override virtual
 Does the tasks associated to changes in \p propertyName and returns \p
true; Does the tasks associated to changes in propertyName and returns true.
Reimplemented from TTool.
{
  if (m_propertyUpdating) return true;
  // Set the following to true whenever a different piece of interface must
  // be refreshed - done once at the end.
  bool notifyTool = false;
  if (propertyName == m_preset.getName()) {
    if (m_preset.getValue() != CUSTOM_WSTR)
      loadPreset();
    else  // Chose <custom>, go back to last saved brush settings
      loadLastBrush();
    V_VectorBrushPreset = m_preset.getValueAsString();
    m_propertyUpdating  = true;
    getApplication()->getCurrentTool()->notifyToolChanged();
    m_propertyUpdating = false;
    return true;
  }
  // Switch to <custom> only if it's a preset property change
  if (m_preset.getValue() != CUSTOM_WSTR &&
      (propertyName == m_thickness.getName() ||
       propertyName == m_accuracy.getName() ||
       propertyName == m_smooth.getName() ||
       propertyName == m_breakAngles.getName() ||
       propertyName == m_pressure.getName() ||
       propertyName == m_capStyle.getName() ||
       propertyName == m_joinStyle.getName() ||
       propertyName == m_miterJoinLimit.getName())) {
    m_preset.setValue(CUSTOM_WSTR);
    V_VectorBrushPreset = m_preset.getValueAsString();
    notifyTool          = true;
  }
  // Properties tracked with preset. Update only on <custom>
  if (m_preset.getValue() == CUSTOM_WSTR) {
    V_VectorBrushMinSize       = m_thickness.getValue().first;
    V_VectorBrushMaxSize       = m_thickness.getValue().second;
    V_BrushAccuracy            = m_accuracy.getValue();
    V_BrushSmooth              = m_smooth.getValue();
    V_BrushBreakSharpAngles    = m_breakAngles.getValue();
    V_BrushPressureSensitivity = m_pressure.getValue();
    V_VectorCapStyle           = m_capStyle.getIndex();
    V_VectorJoinStyle          = m_joinStyle.getIndex();
    V_VectorMiterValue         = m_miterJoinLimit.getValue();
  }
  // Properties not tracked with preset
  int frameIndex               = m_frameRange.getIndex();
  V_VectorBrushFrameRange      = frameIndex;
  V_VectorBrushSnap            = m_snap.getValue();
  int snapSensitivityIndex     = m_snapSensitivity.getIndex();
  V_VectorBrushSnapSensitivity = snapSensitivityIndex;
  // Recalculate/reset based on changed settings
  m_minThick = m_thickness.getValue().first;
  m_maxThick = m_thickness.getValue().second;
  if (frameIndex == 0) resetFrameRange();
  switch (snapSensitivityIndex) {
  case 0:
    m_minDistance2 = SNAPPING_LOW;
    break;
  case 1:
    m_minDistance2 = SNAPPING_MEDIUM;
    break;
  case 2:
    m_minDistance2 = SNAPPING_HIGH;
    break;
  }
  if (propertyName == m_joinStyle.getName()) notifyTool = true;
  if (notifyTool) {
    m_propertyUpdating = true;
    getApplication()->getCurrentTool()->notifyToolChanged();
    m_propertyUpdating = false;
  }
  return true;
}
References ToolHandle::notifyToolChanged().
preLeftButtonDown()
bool ToonzVectorBrushTool::preLeftButtonDown () override virtual
This method is called before leftButtonDown() and can be used e.g. to create the image if needed. return true if the method execution can have changed the current tool
Reimplemented from TTool.
{
  if (getViewer() && getViewer()->getGuidedStrokePickerMode()) return false;
  touchImage();
  if (m_isFrameCreated) {
    // When the xsheet frame is selected, whole viewer will be updated from
    // SceneViewer::onXsheetChanged() on adding a new frame.
    // We need to take care of a case when the level frame is selected.
    if (m_application->getCurrentFrame()->isEditingLevel()) invalidate();
  }
  return true;
}
References TTool::invalidate(), TTool::m_isFrameCreated, and TTool::touchImage().
removePreset()
void ToonzVectorBrushTool::removePreset ()
{
  std::wstring name(m_preset.getValue());
  if (name == CUSTOM_WSTR) return;
  m_presetsManager.removePreset(name);
  initPresets();
  // No parameter change, and set the preset value to custom
  m_preset.setValue(CUSTOM_WSTR);
  V_VectorBrushPreset = m_preset.getValueAsString();
}
resetFrameRange()
void ToonzVectorBrushTool::resetFrameRange ()
{
  m_rangeTrack.clear();
  m_firstFrameId = -1;
  if (m_firstStroke) {
    delete m_firstStroke;
    m_firstStroke = 0;
  }
  m_firstFrameRange = true;
}
updateTranslation()
void ToonzVectorBrushTool::updateTranslation () override virtual
Reimplemented from TTool.
{
  m_thickness.setQStringName(tr("Size"));
  m_accuracy.setQStringName(tr("Accuracy:"));
  m_smooth.setQStringName(tr("Smooth:"));
  m_preset.setQStringName(tr("Preset:"));
  m_preset.setItemUIName(CUSTOM_WSTR, tr("<custom>"));
  m_breakAngles.setQStringName(tr("Break"));
  m_pressure.setQStringName(tr("Pressure"));
  m_capStyle.setQStringName(tr("Cap"));
  m_joinStyle.setQStringName(tr("Join"));
  m_miterJoinLimit.setQStringName(tr("Miter:"));
  m_frameRange.setQStringName(tr("Range:"));
  m_snap.setQStringName(tr("Snap"));
  m_snapSensitivity.setQStringName("");
  m_frameRange.setItemUIName(L"Off", tr("Off"));
  m_frameRange.setItemUIName(LINEAR_WSTR, tr("Linear"));
  m_frameRange.setItemUIName(EASEIN_WSTR, tr("In"));
  m_frameRange.setItemUIName(EASEOUT_WSTR, tr("Out"));
  m_frameRange.setItemUIName(EASEINOUT_WSTR, tr("In&Out"));
  m_snapSensitivity.setItemUIName(LOW_WSTR, tr("Low"));
  m_snapSensitivity.setItemUIName(MEDIUM_WSTR, tr("Med"));
  m_snapSensitivity.setItemUIName(HIGH_WSTR, tr("High"));
  m_capStyle.setItemUIName(BUTT_WSTR, tr("Butt cap"));
  m_capStyle.setItemUIName(ROUNDC_WSTR, tr("Round cap"));
  m_capStyle.setItemUIName(PROJECTING_WSTR, tr("Projecting cap"));
  m_joinStyle.setItemUIName(MITER_WSTR, tr("Miter join"));
  m_joinStyle.setItemUIName(ROUNDJ_WSTR, tr("Round join"));
  m_joinStyle.setItemUIName(BEVEL_WSTR, tr("Bevel join"));
}
Member Data Documentation
m_accuracy
TDoubleProperty ToonzVectorBrushTool::m_accuracy protected
m_active
bool ToonzVectorBrushTool::m_active protected
m_altPressed
bool ToonzVectorBrushTool::m_altPressed = false protected
m_backupRas
TRasterCM32P ToonzVectorBrushTool::m_backupRas protected
m_bluredBrush
BluredBrush* ToonzVectorBrushTool::m_bluredBrush protected
m_breakAngles
TBoolProperty ToonzVectorBrushTool::m_breakAngles protected
m_brushPad
QRadialGradient ToonzVectorBrushTool::m_brushPad protected
m_brushPos
TPointD ToonzVectorBrushTool::m_brushPos protected
World position the brush will be painted at.
Referenced by draw().
m_capStyle
TEnumProperty ToonzVectorBrushTool::m_capStyle protected
m_col
int ToonzVectorBrushTool::m_col protected
m_currentColor
TPixel32 ToonzVectorBrushTool::m_currentColor protected
m_currThickness
double ToonzVectorBrushTool::m_currThickness protected
m_dpiScale
TPointD ToonzVectorBrushTool::m_dpiScale protected
m_dragDraw
bool ToonzVectorBrushTool::m_dragDraw = true protected
m_enabled
bool ToonzVectorBrushTool::m_enabled protected
m_firstFrame
int ToonzVectorBrushTool::m_firstFrame protected
m_firstFrameId
TFrameId ToonzVectorBrushTool::m_firstFrameId protected
m_firstFrameRange
bool ToonzVectorBrushTool::m_firstFrameRange protected
m_firstSnapPoint
TPointD ToonzVectorBrushTool::m_firstSnapPoint protected
m_firstStroke
TStroke* ToonzVectorBrushTool::m_firstStroke protected
m_firstTime
bool ToonzVectorBrushTool::m_firstTime protected
m_foundFirstSnap
bool ToonzVectorBrushTool::m_foundFirstSnap = false protected
m_foundLastSnap
bool ToonzVectorBrushTool::m_foundLastSnap = false protected
m_frameRange
TEnumProperty ToonzVectorBrushTool::m_frameRange protected
m_isPath
bool ToonzVectorBrushTool::m_isPath protected
m_isPrompting
bool ToonzVectorBrushTool::m_isPrompting protected
Whether the tool is prompting for spline substitution.
Referenced by draw().
m_joinStyle
TEnumProperty ToonzVectorBrushTool::m_joinStyle protected
m_lastDragEvent
TMouseEvent ToonzVectorBrushTool::m_lastDragEvent protected
Previous mouse-drag event.
Referenced by onDeactivate().
m_lastDragPos
TPointD ToonzVectorBrushTool::m_lastDragPos protected
Position where mouse was last dragged.
Referenced by onDeactivate().
m_lastRect
TRect ToonzVectorBrushTool::m_lastRect protected
m_lastSnapPoint
TPointD ToonzVectorBrushTool::m_lastSnapPoint protected
m_maxThick
double ToonzVectorBrushTool::m_maxThick protected
m_minDistance2
double ToonzVectorBrushTool::m_minDistance2 protected
m_minThick
double ToonzVectorBrushTool::m_minThick protected
m_miterJoinLimit
TIntProperty ToonzVectorBrushTool::m_miterJoinLimit protected
m_modifiedRegion
TRectD ToonzVectorBrushTool::m_modifiedRegion protected
m_mousePos
TPointD ToonzVectorBrushTool::m_mousePos protected
Current mouse position, in world coordinates.
m_pixelSize
double ToonzVectorBrushTool::m_pixelSize protected
m_points
std::vector<TThickPoint> ToonzVectorBrushTool::m_points protected
m_preset
TEnumProperty ToonzVectorBrushTool::m_preset protected
m_presetsLoaded
bool ToonzVectorBrushTool::m_presetsLoaded protected
m_presetsManager
VectorBrushPresetManager ToonzVectorBrushTool::m_presetsManager protected
Manager for presets of this tool instance.
m_pressure
TBoolProperty ToonzVectorBrushTool::m_pressure protected
m_prop
TPropertyGroup ToonzVectorBrushTool::m_prop[2] protected
m_propertyUpdating
bool ToonzVectorBrushTool::m_propertyUpdating = false protected
m_rangeTrack
StrokeGenerator ToonzVectorBrushTool::m_rangeTrack protected
m_rasterTrack
RasterStrokeGenerator* ToonzVectorBrushTool::m_rasterTrack protected
m_smooth
TDoubleProperty ToonzVectorBrushTool::m_smooth protected
m_smoothStroke
SmoothStroke ToonzVectorBrushTool::m_smoothStroke protected
m_snap
TBoolProperty ToonzVectorBrushTool::m_snap protected
m_snapSelf
bool ToonzVectorBrushTool::m_snapSelf = false protected
m_snapSensitivity
TEnumProperty ToonzVectorBrushTool::m_snapSensitivity protected
m_strokeIndex1
int ToonzVectorBrushTool::m_strokeIndex1 protected
m_strokeIndex2
int ToonzVectorBrushTool::m_strokeIndex2 protected
m_strokeRect
TRect ToonzVectorBrushTool::m_strokeRect protected
m_styleId
int ToonzVectorBrushTool::m_styleId protected
m_targetType
int ToonzVectorBrushTool::m_targetType protected
m_thickness
TDoublePairProperty ToonzVectorBrushTool::m_thickness protected
m_tileSaver
TTileSaverCM32* ToonzVectorBrushTool::m_tileSaver protected
m_tileSet
TTileSetCM32* ToonzVectorBrushTool::m_tileSet protected
m_track
StrokeGenerator ToonzVectorBrushTool::m_track protected
m_veryFirstCol
int ToonzVectorBrushTool::m_veryFirstCol protected
m_veryFirstFrame
int ToonzVectorBrushTool::m_veryFirstFrame protected
m_veryFirstFrameId
TFrameId ToonzVectorBrushTool::m_veryFirstFrameId protected
m_w1
double ToonzVectorBrushTool::m_w1 protected
m_w2
double ToonzVectorBrushTool::m_w2 protected
m_workingFrameId
TFrameId ToonzVectorBrushTool::m_workingFrameId protected
m_workRas
TRaster32P ToonzVectorBrushTool::m_workRas protected
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/tnztools/toonzvectorbrushtool.h
E:/opentoonz/toonz/sources/tnztools/toonzvectorbrushtool.cpp