opentoonz: ToonzRasterBrushTool Class Reference
ToonzRasterBrushTool Class Reference final
Public Member Functions
ToonzRasterBrushTool (std::string name, int targetType)
ToolType getToolType () const override
ToolOptionsBox * createOptionsBox () override
void updateTranslation () override
void onActivate () override
Callback invoked whenever the tool activates.
void onDeactivate () override
Callback for tool deactivation, includes tool switch.
bool preLeftButtonDown () override
void leftButtonDown (const TPointD &pos, const TMouseEvent &e) override
void leftButtonDrag (const TPointD &pos, const TMouseEvent &e) override
void leftButtonUp (const TPointD &pos, const TMouseEvent &e) override
void mouseMove (const TPointD &pos, const TMouseEvent &e) override
void draw () override
Draws the tool on the viewer.
void onEnter () override
Callback for the mouse entering the viewer area.
void onLeave () override
Callback for the mouse leaving the viewer area.
int getCursorId () const override
Returns the type of cursor used by the tool.
TPropertyGroup * getProperties (int targetType) override
bool onPropertyChanged (std::string propertyName) override
void onImageChanged () override
Notifies changes in the image in use.
void setWorkAndBackupImages ()
void updateWorkAndBackupRasters (const TRect &rect)
void initPresets ()
void loadPreset ()
void addPreset (QString name)
void removePreset ()
void loadLastBrush ()
void finishRasterBrush (const TPointD &pos, double pressureVal)
bool isPencilModeActive () override
void onColorStyleChanged ()
bool askRead (const TRect &rect) override
bool askWrite (const TRect &rect) override
bool isMyPaintStyleSelected ()
Public Member Functions inherited from TTool
TTool (std::string toolName)
every tool (invoking updateTranslation() for each).
virtual ToolType getToolType () const =0
ToolTargetType getTargetType () const
std::string getName () const
virtual ToolOptionsBox * createOptionsBox ()
void setViewer (Viewer *viewer)
Viewer * getViewer () const
double getPixelSize () const
void invalidate (const TRectD &rect=TRectD())
int pick (const TPointD &p)
bool isPicking () const
virtual void updateTranslation ()
virtual bool preLeftButtonDown ()
virtual void mouseMove (const TPointD &, const TMouseEvent &)
virtual void leftButtonDown (const TPointD &, const TMouseEvent &)
virtual void leftButtonDrag (const TPointD &, const TMouseEvent &)
virtual void leftButtonUp (const TPointD &, const TMouseEvent &)
virtual void leftButtonDoubleClick (const TPointD &, const TMouseEvent &)
virtual void rightButtonDown (const TPointD &, const TMouseEvent &)
virtual bool keyDown (QKeyEvent *)
virtual void onInputText (std::wstring, std::wstring, int, int)
virtual void onSetViewer ()
virtual void onActivate ()
Callback invoked whenever the tool activates.
virtual void onDeactivate ()
Callback for tool deactivation, includes tool switch.
virtual void onImageChanged ()
Notifies changes in the image in use.
virtual void onEnter ()
Callback for the mouse entering the viewer area.
virtual void onLeave ()
Callback for the mouse leaving the viewer area.
virtual void onFrameSwitched ()
virtual void reset ()
virtual void draw ()
Draws the tool on the viewer.
bool isActive () const
Used to know if a tool is active, (used in TextTool only).
void setActive (bool active)
virtual TPropertyGroup * getProperties (int)
virtual bool onPropertyChanged (std::string propertyName)
virtual TSelection * getSelection ()
Returns a pointer to the tool selection.
virtual int getCursorId () const
Returns the type of cursor used by the tool.
virtual bool isEventAcceptable (QEvent *e)
TXsheet * getXsheet () const
Returns a pointer to the actual Xsheet.
int getFrame ()
Returns the actual frame in use.
int getColumnIndex ()
Returns the actual column index.
TStageObjectId getObjectId () const
Returns a pointer to the actual stage object.
void notifyImageChanged ()
void notifyImageChanged (const TFrameId &fid)
images on the level view.
TFrameId getCurrentFid () const
Returns the number of the actual editing frame.
const TAffine & getMatrix () const
void setMatrix (const TAffine &matrix)
TAffine getCurrentColumnMatrix (int frame=-1) const
TAffine getCurrentColumnParentMatrix () const
TAffine getCurrentObjectParentMatrix () const
TAffine getCurrentObjectParentMatrix2 () const
TAffine getColumnMatrix (int index, int frame=-1) const
virtual void updateMatrix ()
virtual void addContextMenuItems (QMenu *menu)
void enable (bool on)
bool isEnabled () const
QString updateEnabled ()
virtual QString updateEnabled (int rowIndex, int columnIndex)
bool isColumnLocked (int columnIndex) const
void resetInputMethod ()
Resets Input Context (IME)
virtual bool isPencilModeActive ()
virtual bool isDragging () const
void setSelectedFrames (const std::set< TFrameId > &selectedFrames)
void tweenSelectedGuideStrokes ()
void tweenGuideStrokeToSelected ()
void flipGuideStrokeDirection (int mode)
virtual bool askRead (const TRect &rect)
virtual bool askWrite (const TRect &rect)
Protected Member Functions
TPointD getCenteredCursorPos (const TPointD &originalCursorPos)
Protected Member Functions inherited from TTool
void bind (int targetType)
virtual void onSelectedFramesChanged ()
virtual QString disableString ()
Returns a custom reason to disable the tool.
Static Protected Member Functions
static void drawLine (const TPointD &point, const TPointD &centre, bool horizontal, bool isDecimal)
static void drawEmptyCircle (TPointD point, int thick, bool isLxEven, bool isLyEven, bool isPencil)
Protected Attributes
TPropertyGroup m_prop [2]
TDoublePairProperty m_rasThickness
TDoubleProperty m_smooth
TDoubleProperty m_hardness
TEnumProperty m_preset
TEnumProperty m_drawOrder
TBoolProperty m_pencil
TBoolProperty m_pressure
TDoubleProperty m_modifierSize
TBoolProperty m_modifierLockAlpha
RasterStrokeGenerator * m_rasterTrack
TTileSetCM32 * m_tileSet
TTileSaverCM32 * m_tileSaver
TPixel32 m_currentColor
int m_styleId
double m_minThick
double m_maxThick
int m_targetType
TPointD m_dpiScale
TPointD m_mousePos
Current mouse position, in world coordinates.
TPointD m_brushPos
World position the brush will be painted at.
BluredBrush * m_bluredBrush
QRadialGradient m_brushPad
TRasterCM32P m_backupRas
TRaster32P m_workRas
std::vector< TThickPoint > m_points
TRect m_strokeRect
TRect m_lastRect
TRect m_strokeSegmentRect
SmoothStroke m_smoothStroke
BrushPresetManager m_presetsManager
Manager for presets of this tool instance.
bool m_active
bool m_enabled
bool m_isPrompting
bool m_firstTime
bool m_presetsLoaded
TFrameId m_workingFrameId
ToonzRasterBrushToolNotifier * m_notifier
bool m_isMyPaintStyleSelected = false
MyPaintToonzBrush * m_toonz_brush = 0
QElapsedTimer m_brushTimer
int m_minCursorThick
int m_maxCursorThick
bool m_propertyUpdating = false
Protected Attributes inherited from TTool
std::string m_name
The tool's name.
Viewer * m_viewer
Tool's current viewer.
TAffine m_matrix
World-to-window reference change affine.
int m_targetType
The tool's image type target.
bool m_enabled
Whether the tool allows user interaction.
bool m_active
bool m_picking
Additional Inherited Members
Public Types inherited from TTool
enum ToolType {
GenericTool = 1 , ColumnTool = 2 , LevelReadTool = 4 , LevelWriteTool ,
LevelTool = LevelReadTool | LevelWriteTool
}
Tool editing type.
enum ToolTargetType {
NoTarget = 0x0 , VectorImage = 0x1 , ToonzImage = 0x2 , RasterImage = 0x4 ,
MeshImage = 0x8 , Splines = 0x10 , LevelColumns = 0x20 , MeshColumns = 0x40 ,
EmptyTarget = 0x80 , CommonImages = VectorImage | ToonzImage | RasterImage , AllImages = CommonImages | MeshImage , Vectors = VectorImage | Splines ,
CommonLevels = CommonImages | LevelColumns , MeshLevels = MeshImage | MeshColumns , AllTargets = 0xffffffff
}
Object types the tool can operate on.
typedef TApplication Application
Static Public Member Functions inherited from TTool
static TTool * getTool (std::string toolName, ToolTargetType targetType)
static TApplication * getApplication ()
static void setApplication (TApplication *application)
static TXshCell getImageCell ()
Returns the level-frame pair to be edited by the tool.
static TImage * getImage (bool toBeModified, int subsampling=0)
Returns the image to be edited by the tool.
static TImage * touchImage ()
static void updateToolsPropertiesTranslation ()
static const std::set< TFrameId > & getSelectedFrames ()
Static Public Attributes inherited from TTool
static std::vector< CellOps > m_cellsData
static bool m_isLevelCreated = false
static bool m_isFrameCreated = false
static std::vector< TFrameId > m_oldFids
static std::vector< TFrameId > m_newFids
static bool m_isLevelRenumbererd = false
Static Protected Attributes inherited from TTool
static TApplication * m_application = 0
static std::set< TFrameId > m_selectedFrames = std::set<TFrameId>()
Detailed Description
Constructor & Destructor Documentation
ToonzRasterBrushTool()
ToonzRasterBrushTool::ToonzRasterBrushTool (std::string name, int targetType)
    : TTool(name)
    , m_rasThickness("Size", 1, 1000, 1, 5)
    , m_smooth("Smooth:", 0, 50, 0)
    , m_hardness("Hardness:", 0, 100, 100)
    , m_preset("Preset:")
    , m_drawOrder("Draw Order:")
    , m_pencil("Pencil", false)
    , m_pressure("Pressure", true)
    , m_modifierSize("ModifierSize", -3, 3, 0, true)
    , m_rasterTrack(0)
    , m_styleId(0)
    , m_bluredBrush(0)
    , m_active(false)
    , m_enabled(false)
    , m_isPrompting(false)
    , m_firstTime(true)
    , m_presetsLoaded(false)
    , m_targetType(targetType)
    , m_workingFrameId(TFrameId())
    , m_notifier(0)
    , m_modifierLockAlpha("Lock Alpha", false) {
  bind(targetType);
  m_rasThickness.setNonLinearSlider();
  m_prop[0].bind(m_rasThickness);
  m_prop[0].bind(m_hardness);
  m_prop[0].bind(m_smooth);
  m_prop[0].bind(m_drawOrder);
  m_prop[0].bind(m_modifierSize);
  m_prop[0].bind(m_modifierLockAlpha);
  m_prop[0].bind(m_pencil);
  m_pencil.setId("PencilMode");
  m_drawOrder.addValue(L"Over All");
  m_drawOrder.addValue(L"Under All");
  m_drawOrder.addValue(L"Palette Order");
  m_drawOrder.setId("DrawOrder");
  m_prop[0].bind(m_pressure);
  m_prop[0].bind(m_preset);
  m_preset.setId("BrushPreset");
  m_preset.addValue(CUSTOM_WSTR);
  m_pressure.setId("PressureSensitivity");
  m_modifierLockAlpha.setId("LockAlpha");
}
Member Function Documentation
addPreset()
void ToonzRasterBrushTool::addPreset (QString name)
{
  // Build the preset
  BrushData preset(name.toStdWString());
  preset.m_min = m_rasThickness.getValue().first;
  preset.m_max = m_rasThickness.getValue().second;
  preset.m_smooth            = m_smooth.getValue();
  preset.m_hardness          = m_hardness.getValue();
  preset.m_drawOrder         = m_drawOrder.getIndex();
  preset.m_pencil            = m_pencil.getValue();
  preset.m_pressure          = m_pressure.getValue();
  preset.m_modifierSize      = m_modifierSize.getValue();
  preset.m_modifierLockAlpha = m_modifierLockAlpha.getValue();
  // Pass the preset to the manager
  m_presetsManager.addPreset(preset);
  // Reinitialize the associated preset enum
  initPresets();
  // Set the value to the specified one
  m_preset.setValue(preset.m_name);
  RasterBrushPreset = m_preset.getValueAsString();
}
askRead()
bool ToonzRasterBrushTool::askRead (const TRect & rect) override virtual
Reimplemented from RasterController.
{ return askWrite(rect); }
askWrite()
bool ToonzRasterBrushTool::askWrite (const TRect & rect) override virtual
Reimplemented from RasterController.
{
  if (rect.isEmpty()) return true;
  m_strokeRect += rect;
  m_strokeSegmentRect += rect;
  updateWorkAndBackupRasters(rect);
  m_tileSaver->save(rect);
  return true;
}
createOptionsBox()
ToolOptionsBox * ToonzRasterBrushTool::createOptionsBox () override virtual
The default returns a generic box containing the options for property group 0).
See also
See tooloptions.h for more details. Factory function returning a newly created GUI options box to be displayed for the tool
Reimplemented from TTool.
{
  TPaletteHandle *currPalette =
      TTool::getApplication()->getPaletteController()->getCurrentLevelPalette();
  ToolHandle *currTool = TTool::getApplication()->getCurrentTool();
  return new BrushToolOptionsBox(0, this, currPalette, currTool);
}
draw()
void ToonzRasterBrushTool::draw () override virtual
Draws the tool on the viewer.
Reimplemented from TTool.
{
  /*----*/
  if (m_minThick == 0 && m_maxThick == 0 &&
      !Preferences::instance()->getShow0ThickLines())
    return;
  TImageP img = getImage(false, 1);
  if (getApplication()->getCurrentObject()->isSpline()) return;
  // If toggled off, don't draw brush outline
  if (!Preferences::instance()->isCursorOutlineEnabled()) return;
  // Draw the brush outline - change color when the Ink / Paint check is
  // activated
  if ((ToonzCheck::instance()->getChecks() & ToonzCheck::eInk) ||
      (ToonzCheck::instance()->getChecks() & ToonzCheck::ePaint) ||
      (ToonzCheck::instance()->getChecks() & ToonzCheck::eInk1))
    glColor3d(0.5, 0.8, 0.8);
  // normally draw in red
  else
    glColor3d(1.0, 0.0, 0.0);
  if (m_isMyPaintStyleSelected) {
    tglDrawCircle(m_brushPos, (m_minCursorThick + 1) * 0.5);
    tglDrawCircle(m_brushPos, (m_maxCursorThick + 1) * 0.5);
    return;
  }
  if (TToonzImageP ti = img) {
    TRasterP ras = ti->getRaster();
    int lx       = ras->getLx();
    int ly       = ras->getLy();
    drawEmptyCircle(m_brushPos, tround(m_minThick), lx % 2 == 0, ly % 2 == 0,
                    m_pencil.getValue());
    drawEmptyCircle(m_brushPos, tround(m_maxThick), lx % 2 == 0, ly % 2 == 0,
                    m_pencil.getValue());
  } else {
    drawEmptyCircle(m_brushPos, tround(m_minThick), true, true,
                    m_pencil.getValue());
    drawEmptyCircle(m_brushPos, tround(m_maxThick), true, true,
                    m_pencil.getValue());
  }
}
References ToonzCheck::eInk, ToonzCheck::eInk1, ToonzCheck::ePaint, TTool::getImage(), and m_brushPos.
drawEmptyCircle()
void ToonzRasterBrushTool::drawEmptyCircle (TPointD point, int thick, bool isLxEven, bool isLyEven, bool isPencil) static protected
{
  if (isLxEven) pos.x += 0.5;
  if (isLyEven) pos.y += 0.5;
  if (!isPencil)
    tglDrawCircle(pos, (thick + 1) * 0.5);
  else {
    int x = 0, y = tround((thick * 0.5) - 0.5);
    int d           = 3 - 2 * (int)(thick * 0.5);
    bool horizontal = true, isDecimal = thick % 2 != 0;
    drawLine(TPointD(x, y), pos, horizontal, isDecimal);
    while (y > x) {
      if (d < 0) {
        d          = d + 4 * x + 6;
        horizontal = true;
      } else {
        d          = d + 4 * (x - y) + 10;
        horizontal = false;
        y--;
      }
      x++;
      drawLine(TPointD(x, y), pos, horizontal, isDecimal);
    }
  }
}
drawLine()
void ToonzRasterBrushTool::drawLine (const TPointD & point, const TPointD & centre, bool horizontal, bool isDecimal) static protected
{
  if (!isDecimal) {
    if (horizontal) {
      tglDrawSegment(TPointD(point.x - 1.5, point.y + 0.5) + centre,
                     TPointD(point.x - 0.5, point.y + 0.5) + centre);
      tglDrawSegment(TPointD(point.y - 0.5, -point.x + 1.5) + centre,
                     TPointD(point.y - 0.5, -point.x + 0.5) + centre);
      tglDrawSegment(TPointD(-point.x + 0.5, -point.y + 0.5) + centre,
                     TPointD(-point.x - 0.5, -point.y + 0.5) + centre);
      tglDrawSegment(TPointD(-point.y - 0.5, point.x - 0.5) + centre,
                     TPointD(-point.y - 0.5, point.x + 0.5) + centre);
      tglDrawSegment(TPointD(point.y - 0.5, point.x + 0.5) + centre,
                     TPointD(point.y - 0.5, point.x - 0.5) + centre);
      tglDrawSegment(TPointD(point.x - 0.5, -point.y + 0.5) + centre,
                     TPointD(point.x - 1.5, -point.y + 0.5) + centre);
      tglDrawSegment(TPointD(-point.y - 0.5, -point.x + 0.5) + centre,
                     TPointD(-point.y - 0.5, -point.x + 1.5) + centre);
      tglDrawSegment(TPointD(-point.x - 0.5, point.y + 0.5) + centre,
                     TPointD(-point.x + 0.5, point.y + 0.5) + centre);
    } else {
      tglDrawSegment(TPointD(point.x - 1.5, point.y + 1.5) + centre,
                     TPointD(point.x - 1.5, point.y + 0.5) + centre);
      tglDrawSegment(TPointD(point.x - 1.5, point.y + 0.5) + centre,
                     TPointD(point.x - 0.5, point.y + 0.5) + centre);
      tglDrawSegment(TPointD(point.y + 0.5, -point.x + 1.5) + centre,
                     TPointD(point.y - 0.5, -point.x + 1.5) + centre);
      tglDrawSegment(TPointD(point.y - 0.5, -point.x + 1.5) + centre,
                     TPointD(point.y - 0.5, -point.x + 0.5) + centre);
      tglDrawSegment(TPointD(-point.x + 0.5, -point.y - 0.5) + centre,
                     TPointD(-point.x + 0.5, -point.y + 0.5) + centre);
      tglDrawSegment(TPointD(-point.x + 0.5, -point.y + 0.5) + centre,
                     TPointD(-point.x - 0.5, -point.y + 0.5) + centre);
      tglDrawSegment(TPointD(-point.y - 1.5, point.x - 0.5) + centre,
                     TPointD(-point.y - 0.5, point.x - 0.5) + centre);
      tglDrawSegment(TPointD(-point.y - 0.5, point.x - 0.5) + centre,
                     TPointD(-point.y - 0.5, point.x + 0.5) + centre);
      tglDrawSegment(TPointD(point.y + 0.5, point.x - 0.5) + centre,
                     TPointD(point.y - 0.5, point.x - 0.5) + centre);
      tglDrawSegment(TPointD(point.y - 0.5, point.x - 0.5) + centre,
                     TPointD(point.y - 0.5, point.x + 0.5) + centre);
      tglDrawSegment(TPointD(point.x - 1.5, -point.y - 0.5) + centre,
                     TPointD(point.x - 1.5, -point.y + 0.5) + centre);
      tglDrawSegment(TPointD(point.x - 1.5, -point.y + 0.5) + centre,
                     TPointD(point.x - 0.5, -point.y + 0.5) + centre);
      tglDrawSegment(TPointD(-point.y - 1.5, -point.x + 1.5) + centre,
                     TPointD(-point.y - 0.5, -point.x + 1.5) + centre);
      tglDrawSegment(TPointD(-point.y - 0.5, -point.x + 1.5) + centre,
                     TPointD(-point.y - 0.5, -point.x + 0.5) + centre);
      tglDrawSegment(TPointD(-point.x + 0.5, point.y + 1.5) + centre,
                     TPointD(-point.x + 0.5, point.y + 0.5) + centre);
      tglDrawSegment(TPointD(-point.x + 0.5, point.y + 0.5) + centre,
                     TPointD(-point.x - 0.5, point.y + 0.5) + centre);
    }
  } else {
    if (horizontal) {
      tglDrawSegment(TPointD(point.x - 0.5, point.y + 0.5) + centre,
                     TPointD(point.x + 0.5, point.y + 0.5) + centre);
      tglDrawSegment(TPointD(point.y + 0.5, point.x - 0.5) + centre,
                     TPointD(point.y + 0.5, point.x + 0.5) + centre);
      tglDrawSegment(TPointD(point.y + 0.5, -point.x + 0.5) + centre,
                     TPointD(point.y + 0.5, -point.x - 0.5) + centre);
      tglDrawSegment(TPointD(point.x + 0.5, -point.y - 0.5) + centre,
                     TPointD(point.x - 0.5, -point.y - 0.5) + centre);
      tglDrawSegment(TPointD(-point.x - 0.5, -point.y - 0.5) + centre,
                     TPointD(-point.x + 0.5, -point.y - 0.5) + centre);
      tglDrawSegment(TPointD(-point.y - 0.5, -point.x + 0.5) + centre,
                     TPointD(-point.y - 0.5, -point.x - 0.5) + centre);
      tglDrawSegment(TPointD(-point.y - 0.5, point.x - 0.5) + centre,
                     TPointD(-point.y - 0.5, point.x + 0.5) + centre);
      tglDrawSegment(TPointD(-point.x + 0.5, point.y + 0.5) + centre,
                     TPointD(-point.x - 0.5, point.y + 0.5) + centre);
    } else {
      tglDrawSegment(TPointD(point.x - 0.5, point.y + 1.5) + centre,
                     TPointD(point.x - 0.5, point.y + 0.5) + centre);
      tglDrawSegment(TPointD(point.x - 0.5, point.y + 0.5) + centre,
                     TPointD(point.x + 0.5, point.y + 0.5) + centre);
      tglDrawSegment(TPointD(point.y + 1.5, point.x - 0.5) + centre,
                     TPointD(point.y + 0.5, point.x - 0.5) + centre);
      tglDrawSegment(TPointD(point.y + 0.5, point.x - 0.5) + centre,
                     TPointD(point.y + 0.5, point.x + 0.5) + centre);
      tglDrawSegment(TPointD(point.y + 1.5, -point.x + 0.5) + centre,
                     TPointD(point.y + 0.5, -point.x + 0.5) + centre);
      tglDrawSegment(TPointD(point.y + 0.5, -point.x + 0.5) + centre,
                     TPointD(point.y + 0.5, -point.x - 0.5) + centre);
      tglDrawSegment(TPointD(point.x - 0.5, -point.y - 1.5) + centre,
                     TPointD(point.x - 0.5, -point.y - 0.5) + centre);
      tglDrawSegment(TPointD(point.x - 0.5, -point.y - 0.5) + centre,
                     TPointD(point.x + 0.5, -point.y - 0.5) + centre);
      tglDrawSegment(TPointD(-point.x + 0.5, -point.y - 1.5) + centre,
                     TPointD(-point.x + 0.5, -point.y - 0.5) + centre);
      tglDrawSegment(TPointD(-point.x + 0.5, -point.y - 0.5) + centre,
                     TPointD(-point.x - 0.5, -point.y - 0.5) + centre);
      tglDrawSegment(TPointD(-point.y - 1.5, -point.x + 0.5) + centre,
                     TPointD(-point.y - 0.5, -point.x + 0.5) + centre);
      tglDrawSegment(TPointD(-point.y - 0.5, -point.x + 0.5) + centre,
                     TPointD(-point.y - 0.5, -point.x - 0.5) + centre);
      tglDrawSegment(TPointD(-point.y - 1.5, point.x - 0.5) + centre,
                     TPointD(-point.y - 0.5, point.x - 0.5) + centre);
      tglDrawSegment(TPointD(-point.y - 0.5, point.x - 0.5) + centre,
                     TPointD(-point.y - 0.5, point.x + 0.5) + centre);
      tglDrawSegment(TPointD(-point.x + 0.5, point.y + 1.5) + centre,
                     TPointD(-point.x + 0.5, point.y + 0.5) + centre);
      tglDrawSegment(TPointD(-point.x + 0.5, point.y + 0.5) + centre,
                     TPointD(-point.x - 0.5, point.y + 0.5) + centre);
    }
  }
}
finishRasterBrush()
void ToonzRasterBrushTool::finishRasterBrush (const TPointD & pos, double pressureVal)
onDeactivateMouseRelease
{
  TToonzImageP ti = TImageP(getImage(true));
  if (!ti) return;
  TPointD rasCenter         = ti->getRaster()->getCenterD();
  TTool::Application *app   = TTool::getApplication();
  TXshLevel *level          = app->getCurrentLevel()->getLevel();
  TXshSimpleLevelP simLevel = level->getSimpleLevel();
  /*--
   * FidUndo
   * --*/
  TFrameId frameId =
      m_workingFrameId.isEmptyFrame() ? getCurrentFid() : m_workingFrameId;
  if (m_isMyPaintStyleSelected) {
    TRasterCM32P ras = ti->getRaster();
    TPointD point(pos + rasCenter);
    double pressure = m_pressure.getValue() ? pressureVal : 0.5;
    m_strokeSegmentRect.empty();
    m_toonz_brush->strokeTo(point, pressure, restartBrushTimer());
    m_toonz_brush->endStroke();
    TRect updateRect = m_strokeSegmentRect * ras->getBounds();
    if (!updateRect.isEmpty()) {
      // ras->extract(updateRect)->copy(m_workRaster->extract(updateRect));
      m_toonz_brush->updateDrawing(ras, m_backupRas, m_strokeSegmentRect,
                                   m_styleId, m_modifierLockAlpha.getValue());
    }
    TPointD thickOffset(m_maxCursorThick * 0.5,
                        m_maxCursorThick * 0.5);  // TODO
    TRectD invalidateRect = convert(m_strokeSegmentRect) - rasCenter;
    invalidateRect += TRectD(pos - thickOffset, pos + thickOffset);
    invalidate(invalidateRect.enlarge(2.0));
    if (m_toonz_brush) {
      delete m_toonz_brush;
      m_toonz_brush = 0;
    }
    m_lastRect.empty();
    m_workRas->unlock();
    if (m_tileSet->getTileCount() > 0) {
      TRasterCM32P subras = ras->extract(m_strokeRect)->clone();
      TUndoManager::manager()->add(new MyPaintBrushUndo(
          m_tileSet, simLevel.getPointer(), frameId, m_isFrameCreated,
          m_isLevelCreated, subras, m_strokeRect.getP00()));
    }
  } else if (m_rasterTrack &&
             (m_hardness.getValue() == 100 || m_pencil.getValue())) {
    double thickness = m_pressure.getValue()
                           ? computeThickness(pressureVal, m_rasThickness)
                           : m_rasThickness.getValue().second;
    /*--- Max ---*/
    if (m_pressure.getValue() && pressureVal == 1.0)
      thickness = m_rasThickness.getValue().first;
    /*-- PencilHardness=100 1 --*/
    if (!m_pencil.getValue()) thickness -= 1.0;
    TRectD invalidateRect;
    TThickPoint thickPoint(pos + rasCenter, thickness);
    std::vector<TThickPoint> pts;
    if (m_smooth.getValue() == 0) {
      pts.push_back(thickPoint);
    } else {
      m_smoothStroke.addPoint(thickPoint);
      m_smoothStroke.endStroke();
      m_smoothStroke.getSmoothPoints(pts);
    }
    for (size_t i = 0; i < pts.size(); ++i) {
      const TThickPoint &thickPoint = pts[i];
      m_rasterTrack->add(thickPoint);
      m_tileSaver->save(m_rasterTrack->getLastRect());
      m_rasterTrack->generateLastPieceOfStroke(m_pencil.getValue(), true);
      std::vector<TThickPoint> brushPoints = m_rasterTrack->getPointsSequence();
      int m                                = (int)brushPoints.size();
      std::vector<TThickPoint> points;
      if (m == 3) {
        points.push_back(brushPoints[0]);
        points.push_back(brushPoints[1]);
      } else {
        points.push_back(brushPoints[m - 4]);
        points.push_back(brushPoints[m - 3]);
        points.push_back(brushPoints[m - 2]);
      }
      int maxThickness = m_rasThickness.getValue().second;
      invalidateRect += ToolUtils::getBounds(points, maxThickness) - rasCenter;
    }
    invalidate(invalidateRect.enlarge(2));
    if (m_tileSet->getTileCount() > 0) {
      TUndoManager::manager()->add(new RasterBrushUndo(
          m_tileSet, m_rasterTrack->getPointsSequence(),
          m_rasterTrack->getStyleId(), m_rasterTrack->isSelective(),
          simLevel.getPointer(), frameId, m_pencil.getValue(), m_isFrameCreated,
          m_isLevelCreated, m_rasterTrack->isPaletteOrder(),
          m_rasterTrack->isAlphaLocked()));
    }
    delete m_rasterTrack;
    m_rasterTrack = 0;
  } else {
    double maxThickness = m_rasThickness.getValue().second;
    double thickness    = (m_pressure.getValue())
                           ? computeThickness(pressureVal, m_rasThickness)
                           : maxThickness;
    TPointD rasCenter = ti->getRaster()->getCenterD();
    TRectD invalidateRect;
    TThickPoint thickPoint(pos + rasCenter, thickness);
    std::vector<TThickPoint> pts;
    if (m_smooth.getValue() == 0) {
      pts.push_back(thickPoint);
    } else {
      m_smoothStroke.addPoint(thickPoint);
      m_smoothStroke.endStroke();
      m_smoothStroke.getSmoothPoints(pts);
    }
    // we need to skip the for-loop here if pts.size() == 0 or else
    // (pts.size() - 1) becomes ULLONG_MAX since size_t is unsigned
    if (pts.size() > 0) {
      for (size_t i = 0; i < pts.size() - 1; ++i) {
        TThickPoint old = m_points.back();
        const TThickPoint &point = pts[i];
        TThickPoint mid((old + point) * 0.5, (point.thick + old.thick) * 0.5);
        m_points.push_back(mid);
        m_points.push_back(point);
        TRect bbox;
        int m = (int)m_points.size();
        std::vector<TThickPoint> points;
        if (m == 3) {
          // ho appena cominciato. devo disegnare un segmento
          TThickPoint pa = m_points.front();
          points.push_back(pa);
          points.push_back(mid);
          bbox = m_bluredBrush->getBoundFromPoints(points);
          updateWorkAndBackupRasters(bbox + m_lastRect);
          m_tileSaver->save(bbox);
          m_bluredBrush->addArc(pa, (mid + pa) * 0.5, mid, 1, 1);
          m_lastRect += bbox;
        } else {
          points.push_back(m_points[m - 4]);
          points.push_back(old);
          points.push_back(mid);
          bbox = m_bluredBrush->getBoundFromPoints(points);
          updateWorkAndBackupRasters(bbox + m_lastRect);
          m_tileSaver->save(bbox);
          m_bluredBrush->addArc(m_points[m - 4], old, mid, 1, 1);
          m_lastRect += bbox;
        }
        invalidateRect +=
            ToolUtils::getBounds(points, maxThickness) - rasCenter;
        m_bluredBrush->updateDrawing(ti->getRaster(), m_backupRas, bbox,
                                     m_styleId, m_drawOrder.getIndex(),
                                     m_modifierLockAlpha.getValue());
        m_strokeRect += bbox;
      }
      TThickPoint point = pts.back();
      m_points.push_back(point);
      int m = m_points.size();
      std::vector<TThickPoint> points;
      points.push_back(m_points[m - 3]);
      points.push_back(m_points[m - 2]);
      points.push_back(m_points[m - 1]);
      TRect bbox = m_bluredBrush->getBoundFromPoints(points);
      updateWorkAndBackupRasters(bbox);
      m_tileSaver->save(bbox);
      m_bluredBrush->addArc(points[0], points[1], points[2], 1, 1);
      m_bluredBrush->updateDrawing(ti->getRaster(), m_backupRas, bbox,
                                   m_styleId, m_drawOrder.getIndex(),
                                   m_modifierLockAlpha.getValue());
      invalidateRect += ToolUtils::getBounds(points, maxThickness) - rasCenter;
      m_lastRect += bbox;
      m_strokeRect += bbox;
    }
    if (!invalidateRect.isEmpty()) invalidate(invalidateRect.enlarge(2));
    m_lastRect.empty();
    delete m_bluredBrush;
    m_bluredBrush = 0;
    if (m_tileSet->getTileCount() > 0) {
      TUndoManager::manager()->add(new RasterBluredBrushUndo(
          m_tileSet, m_points, m_styleId, (DrawOrder)m_drawOrder.getIndex(),
          m_modifierLockAlpha.getValue(), simLevel.getPointer(), frameId,
          m_rasThickness.getValue().second, m_hardness.getValue() * 0.01,
          m_isFrameCreated, m_isLevelCreated));
    }
  }
  delete m_tileSaver;
  m_tileSaver = 0;
  /*-- FId
  Fid--*/
  notifyImageChanged(frameId);
  m_strokeRect.empty();
  ToolUtils::updateSaveBox();
  /*--  --*/
  m_workingFrameId = TFrameId();
}
References TTool::getCurrentFid(), TTool::getImage(), TXshLevel::getSimpleLevel(), TTool::invalidate(), TRectT< T >::isEmpty(), TTool::m_isFrameCreated, TTool::m_isLevelCreated, and TTool::notifyImageChanged().
Referenced by onDeactivate().
getCenteredCursorPos()
TPointD ToonzRasterBrushTool::getCenteredCursorPos (const TPointD & originalCursorPos) protected
{
  if (m_isMyPaintStyleSelected) return originalCursorPos;
  TXshLevelHandle *levelHandle = m_application->getCurrentLevel();
  TXshSimpleLevel *level = levelHandle ? levelHandle->getSimpleLevel() : 0;
  TDimension resolution =
      level ? level->getProperties()->getImageRes() : TDimension(0, 0);
  bool xEven = (resolution.lx % 2 == 0);
  bool yEven = (resolution.ly % 2 == 0);
  TPointD centeredCursorPos = originalCursorPos;
  if (xEven) centeredCursorPos.x -= 0.5;
  if (yEven) centeredCursorPos.y -= 0.5;
  return centeredCursorPos;
}
getCursorId()
int ToonzRasterBrushTool::getCursorId () const inline override virtual
Returns the type of cursor used by the tool.
See also
For a list of cursor ids cursor.h
Reimplemented from TTool.
{ return ToolCursor::PenCursor; }
getProperties()
TPropertyGroup * ToonzRasterBrushTool::getProperties (int targetType) override virtual
Reimplemented from TTool.
{
  if (!m_presetsLoaded) initPresets();
  return &m_prop[idx];
}
getToolType()
ToolType ToonzRasterBrushTool::getToolType () const inline override virtual
Implements TTool.
{ return TTool::LevelWriteTool; }
initPresets()
void ToonzRasterBrushTool::initPresets ()
{
  if (!m_presetsLoaded) {
    // If necessary, load the presets from file
    m_presetsLoaded = true;
    m_presetsManager.load(TEnv::getConfigDir() + "brush_toonzraster.txt");
  }
  // Rebuild the presets property entries
  const std::set<BrushData> &presets = m_presetsManager.presets();
  m_preset.deleteAllValues();
  m_preset.addValue(CUSTOM_WSTR);
  m_preset.setItemUIName(CUSTOM_WSTR, tr("<custom>"));
  std::set<BrushData>::const_iterator it, end = presets.end();
  for (it = presets.begin(); it != end; ++it) m_preset.addValue(it->m_name);
}
isMyPaintStyleSelected()
bool ToonzRasterBrushTool::isMyPaintStyleSelected () inline
{ return m_isMyPaintStyleSelected; }
isPencilModeActive()
bool ToonzRasterBrushTool::isPencilModeActive () override virtual
BrushPaintBrushEraserToolPencilModeTrue
Reimplemented from TTool.
{
  return getTargetType() == TTool::ToonzImage && m_pencil.getValue();
}
References TTool::ToonzImage.
leftButtonDown()
void ToonzRasterBrushTool::leftButtonDown (const TPointD & pos, const TMouseEvent & e) override virtual
Reimplemented from TTool.
{
  TTool::Application *app = TTool::getApplication();
  if (!app) return;
  int col   = app->getCurrentColumn()->getColumnIndex();
  m_enabled = col >= 0 || app->getCurrentFrame()->isEditingLevel();
  // todo: gestire autoenable
  if (!m_enabled) return;
  TPointD centeredPos = getCenteredCursorPos(pos);
  m_currentColor = TPixel32::Black;
  m_active       = !!getImage(true);
  if (!m_active) {
    m_active = !!touchImage();
  }
  if (!m_active) return;
  if (m_active) {
    // nel caso che il colore corrente sia un cleanup/studiopalette color
    // oppure il colore di un colorfield
    m_styleId       = app->getCurrentLevelStyleIndex();
    TColorStyle *cs = app->getCurrentLevelStyle();
    if (cs) {
      TRasterStyleFx *rfx = cs ? cs->getRasterStyleFx() : 0;
      m_active = cs != 0 && (cs->isStrokeStyle() || (rfx && rfx->isInkStyle()));
      m_currentColor   = cs->getAverageColor();
      m_currentColor.m = 255;
    } else {
      m_styleId      = 1;
      m_currentColor = TPixel32::Black;
    }
  }
  // assert(0<=m_styleId && m_styleId<2);
  TImageP img = getImage(true);
  TToonzImageP ri(img);
  TRasterCM32P ras = ri->getRaster();
  if (ras) {
    TPointD rasCenter = ras->getCenterD();
    m_tileSet         = new TTileSetCM32(ras->getSize());
    m_tileSaver       = new TTileSaverCM32(ras, m_tileSet);
    double maxThick   = m_rasThickness.getValue().second;
    double thickness  = (m_pressure.getValue())
                           ? computeThickness(e.m_pressure, m_rasThickness) * 2
                           : maxThick;
    /*--- Max
     * ---*/
    if (m_pressure.getValue() && e.m_pressure == 1.0)
      thickness = m_rasThickness.getValue().first;
    TPointD halfThick(maxThick * 0.5, maxThick * 0.5);
    TRectD invalidateRect(centeredPos - halfThick, centeredPos + halfThick);
    TPointD dpi;
    ri->getDpi(dpi.x, dpi.y);
    TRectD previousTipRect(m_brushPos - halfThick, m_brushPos + halfThick);
    if (dpi.x > Stage::inch || dpi.y > Stage::inch)
      previousTipRect *= dpi.x / Stage::inch;
    invalidateRect += previousTipRect;
    // if the drawOrder mode = "Palette Order",
    // get styleId list which is above the current style in the palette
    DrawOrder drawOrder = (DrawOrder)m_drawOrder.getIndex();
    QSet<int> aboveStyleIds;
    if (drawOrder == PaletteOrder) {
      getAboveStyleIdSet(m_styleId, ri->getPalette(), aboveStyleIds);
    }
    // mypaint brush case
    if (m_isMyPaintStyleSelected) {
      TPointD point(centeredPos + rasCenter);
      double pressure =
          m_pressure.getValue() && e.isTablet() ? e.m_pressure : 0.5;
      updateCurrentStyle();
      if (!(m_workRas && m_backupRas)) setWorkAndBackupImages();
      m_workRas->lock();
      mypaint::Brush mypaintBrush;
      TMyPaintBrushStyle *mypaintStyle =
          dynamic_cast<TMyPaintBrushStyle *>(app->getCurrentLevelStyle());
      {  // applyToonzBrushSettings
        mypaintBrush.fromBrush(mypaintStyle->getBrush());
        double modifierSize = m_modifierSize.getValue() * log(2.0);
        float baseSize =
            mypaintBrush.getBaseValue(MYPAINT_BRUSH_SETTING_RADIUS_LOGARITHMIC);
        mypaintBrush.setBaseValue(MYPAINT_BRUSH_SETTING_RADIUS_LOGARITHMIC,
                                  baseSize + modifierSize);
      }
      m_toonz_brush = new MyPaintToonzBrush(m_workRas, *this, mypaintBrush);
      m_strokeRect.empty();
      m_strokeSegmentRect.empty();
      m_toonz_brush->beginStroke();
      m_toonz_brush->strokeTo(point, pressure, restartBrushTimer());
      TRect updateRect = m_strokeSegmentRect * ras->getBounds();
      if (!updateRect.isEmpty()) {
        // ras->extract(updateRect)->copy(m_workRas->extract(updateRect));
        m_toonz_brush->updateDrawing(ri->getRaster(), m_backupRas, m_strokeRect,
                                     m_styleId, m_modifierLockAlpha.getValue());
      }
      m_lastRect = m_strokeRect;
      TPointD thickOffset(m_maxCursorThick * 0.5, m_maxCursorThick * 0.5);
      invalidateRect = convert(m_strokeSegmentRect) - rasCenter;
      invalidateRect +=
          TRectD(centeredPos - thickOffset, centeredPos + thickOffset);
      invalidateRect +=
          TRectD(m_brushPos - thickOffset, m_brushPos + thickOffset);
    } else if (m_hardness.getValue() == 100 || m_pencil.getValue()) {
      /*-- PencilHardness=100 1
       * --*/
      if (!m_pencil.getValue()) thickness -= 1.0;
      TThickPoint thickPoint(centeredPos + convert(ras->getCenter()),
                             thickness);
      m_rasterTrack = new RasterStrokeGenerator(
          ras, BRUSH, NONE, m_styleId, thickPoint, drawOrder != OverAll, 0,
          m_modifierLockAlpha.getValue(), !m_pencil.getValue(),
          drawOrder == PaletteOrder);
      if (drawOrder == PaletteOrder)
        m_rasterTrack->setAboveStyleIds(aboveStyleIds);
      m_tileSaver->save(m_rasterTrack->getLastRect());
      m_rasterTrack->generateLastPieceOfStroke(m_pencil.getValue());
      std::vector<TThickPoint> pts;
      if (m_smooth.getValue() == 0) {
        pts.push_back(thickPoint);
      } else {
        m_smoothStroke.beginStroke(m_smooth.getValue());
        m_smoothStroke.addPoint(thickPoint);
        m_smoothStroke.getSmoothPoints(pts);
      }
    } else {
      m_points.clear();
      TThickPoint point(centeredPos + rasCenter, thickness);
      m_points.push_back(point);
      m_bluredBrush = new BluredBrush(m_workRas, maxThick, m_brushPad, false);
      if (drawOrder == PaletteOrder)
        m_bluredBrush->setAboveStyleIds(aboveStyleIds);
      m_strokeRect = m_bluredBrush->getBoundFromPoints(m_points);
      updateWorkAndBackupRasters(m_strokeRect);
      m_tileSaver->save(m_strokeRect);
      m_bluredBrush->addPoint(point, 1);
      m_bluredBrush->updateDrawing(ri->getRaster(), m_backupRas, m_strokeRect,
                                   m_styleId, drawOrder,
                                   m_modifierLockAlpha.getValue());
      m_lastRect = m_strokeRect;
      std::vector<TThickPoint> pts;
      if (m_smooth.getValue() == 0) {
        pts.push_back(point);
      } else {
        m_smoothStroke.beginStroke(m_smooth.getValue());
        m_smoothStroke.addPoint(point);
        m_smoothStroke.getSmoothPoints(pts);
      }
    }
    /*-- Fid --*/
    m_workingFrameId = getFrameId();
    invalidate(invalidateRect.enlarge(2));
  }
  // updating m_brushPos is needed to refresh viewer properly
  m_mousePos = pos;
  m_brushPos = getCenteredCursorPos(pos);
}
leftButtonDrag()
void ToonzRasterBrushTool::leftButtonDrag (const TPointD & pos, const TMouseEvent & e) override virtual
Reimplemented from TTool.
{
  if (!m_enabled || !m_active) {
    m_mousePos = pos;
    m_brushPos = getCenteredCursorPos(pos);
    return;
  }
  TPointD centeredPos = getCenteredCursorPos(pos);
  TToonzImageP ti   = TImageP(getImage(true));
  TPointD rasCenter = ti->getRaster()->getCenterD();
  int maxThickness  = m_rasThickness.getValue().second;
  double thickness  = (m_pressure.getValue())
                         ? computeThickness(e.m_pressure, m_rasThickness) * 2
                         : maxThickness;
  TRectD invalidateRect;
  if (m_isMyPaintStyleSelected) {
    TRasterP ras = ti->getRaster();
    TPointD point(centeredPos + rasCenter);
    double pressure =
        m_pressure.getValue() && e.isTablet() ? e.m_pressure : 0.5;
    m_strokeSegmentRect.empty();
    m_toonz_brush->strokeTo(point, pressure, restartBrushTimer());
    TRect updateRect = m_strokeSegmentRect * ras->getBounds();
    if (!updateRect.isEmpty()) {
      // ras->extract(updateRect)->copy(m_workRaster->extract(updateRect));
      m_toonz_brush->updateDrawing(ras, m_backupRas, m_strokeSegmentRect,
                                   m_styleId, m_modifierLockAlpha.getValue());
    }
    m_lastRect = m_strokeRect;
    TPointD thickOffset(m_maxCursorThick * 0.5, m_maxCursorThick * 0.5);
    invalidateRect = convert(m_strokeSegmentRect) - rasCenter;
    invalidateRect +=
        TRectD(centeredPos - thickOffset, centeredPos + thickOffset);
    invalidateRect +=
        TRectD(m_brushPos - thickOffset, m_brushPos + thickOffset);
  } else if (m_rasterTrack &&
             (m_hardness.getValue() == 100 || m_pencil.getValue())) {
    /*-- PencilHardness=100 1
     * --*/
    if (!m_pencil.getValue()) thickness -= 1.0;
    TThickPoint thickPoint(centeredPos + rasCenter, thickness);
    std::vector<TThickPoint> pts;
    if (m_smooth.getValue() == 0) {
      pts.push_back(thickPoint);
    } else {
      m_smoothStroke.addPoint(thickPoint);
      m_smoothStroke.getSmoothPoints(pts);
    }
    for (size_t i = 0; i < pts.size(); ++i) {
      const TThickPoint &thickPoint = pts[i];
      m_rasterTrack->add(thickPoint);
      m_tileSaver->save(m_rasterTrack->getLastRect());
      m_rasterTrack->generateLastPieceOfStroke(m_pencil.getValue());
      std::vector<TThickPoint> brushPoints = m_rasterTrack->getPointsSequence();
      int m                                = (int)brushPoints.size();
      std::vector<TThickPoint> points;
      if (m == 3) {
        points.push_back(brushPoints[0]);
        points.push_back(brushPoints[1]);
      } else {
        points.push_back(brushPoints[m - 4]);
        points.push_back(brushPoints[m - 3]);
        points.push_back(brushPoints[m - 2]);
      }
      invalidateRect += ToolUtils::getBounds(points, maxThickness) - rasCenter;
    }
  } else {
    // antialiased brush
    assert(m_workRas.getPointer() && m_backupRas.getPointer());
    TThickPoint thickPoint(centeredPos + rasCenter, thickness);
    std::vector<TThickPoint> pts;
    if (m_smooth.getValue() == 0) {
      pts.push_back(thickPoint);
    } else {
      m_smoothStroke.addPoint(thickPoint);
      m_smoothStroke.getSmoothPoints(pts);
    }
    for (size_t i = 0; i < pts.size(); ++i) {
      TThickPoint old = m_points.back();
      const TThickPoint &point = pts[i];
      TThickPoint mid((old + point) * 0.5, (point.thick + old.thick) * 0.5);
      m_points.push_back(mid);
      m_points.push_back(point);
      TRect bbox;
      int m = (int)m_points.size();
      std::vector<TThickPoint> points;
      if (m == 3) {
        // ho appena cominciato. devo disegnare un segmento
        TThickPoint pa = m_points.front();
        points.push_back(pa);
        points.push_back(mid);
        bbox = m_bluredBrush->getBoundFromPoints(points);
        updateWorkAndBackupRasters(bbox + m_lastRect);
        m_tileSaver->save(bbox);
        m_bluredBrush->addArc(pa, (mid + pa) * 0.5, mid, 1, 1);
        m_lastRect += bbox;
      } else {
        points.push_back(m_points[m - 4]);
        points.push_back(old);
        points.push_back(mid);
        bbox = m_bluredBrush->getBoundFromPoints(points);
        updateWorkAndBackupRasters(bbox + m_lastRect);
        m_tileSaver->save(bbox);
        m_bluredBrush->addArc(m_points[m - 4], old, mid, 1, 1);
        m_lastRect += bbox;
      }
      invalidateRect += ToolUtils::getBounds(points, maxThickness) - rasCenter;
      m_bluredBrush->updateDrawing(ti->getRaster(), m_backupRas, bbox,
                                   m_styleId, m_drawOrder.getIndex(),
                                   m_modifierLockAlpha.getValue());
      m_strokeRect += bbox;
    }
  }
  // clear & draw brush tip when drawing smooth stroke
  if (m_smooth.getValue() != 0) {
    TPointD halfThick(m_maxThick * 0.5, m_maxThick * 0.5);
    invalidateRect += TRectD(m_brushPos - halfThick, m_brushPos + halfThick);
    invalidateRect += TRectD(centeredPos - halfThick, centeredPos + halfThick);
  }
  m_mousePos = pos;
  m_brushPos = getCenteredCursorPos(pos);
  invalidate(invalidateRect.enlarge(2));
}
leftButtonUp()
void ToonzRasterBrushTool::leftButtonUp (const TPointD & pos, const TMouseEvent & e) override virtual
Reimplemented from TTool.
{
  bool isValid = m_enabled && m_active;
  m_enabled    = false;
  m_active     = false;
  if (!isValid) {
    return;
  }
  TPointD centeredPos = getCenteredCursorPos(pos);
  double pressure = m_pressure.getValue() && e.isTablet() ? e.m_pressure : 0.5;
  finishRasterBrush(centeredPos, pressure);
  int tc = ToonzCheck::instance()->getChecks();
  if (tc & ToonzCheck::eGap || tc & ToonzCheck::eAutoclose) invalidate();
}
loadLastBrush()
void ToonzRasterBrushTool::loadLastBrush ()
{
  m_rasThickness.setValue(
      TDoublePairProperty::Value(RasterBrushMinSize, RasterBrushMaxSize));
  m_drawOrder.setIndex(BrushDrawOrder);
  m_pencil.setValue(RasterBrushPencilMode ? 1 : 0);
  m_hardness.setValue(RasterBrushHardness);
  m_pressure.setValue(BrushPressureSensitivity ? 1 : 0);
  m_smooth.setValue(BrushSmooth);
  m_modifierSize.setValue(RasterBrushModifierSize);
  m_modifierLockAlpha.setValue(BrushLockAlpha ? 1 : 0);
  // Recalculate based on prior values
  m_minThick = m_rasThickness.getValue().first;
  m_maxThick = m_rasThickness.getValue().second;
  setWorkAndBackupImages();
  m_brushPad = getBrushPad(m_rasThickness.getValue().second,
                           m_hardness.getValue() * 0.01);
}
loadPreset()
void ToonzRasterBrushTool::loadPreset ()
{
  const std::set<BrushData> &presets = m_presetsManager.presets();
  std::set<BrushData>::const_iterator it;
  it = presets.find(BrushData(m_preset.getValue()));
  if (it == presets.end()) return;
  const BrushData &preset = *it;
  try  // Don't bother with RangeErrors
  {
    m_rasThickness.setValue(
        TDoublePairProperty::Value(std::max(preset.m_min, 1.0), preset.m_max));
    m_hardness.setValue(preset.m_hardness, true);
    m_smooth.setValue(preset.m_smooth, true);
    m_drawOrder.setIndex(preset.m_drawOrder);
    m_pencil.setValue(preset.m_pencil);
    m_pressure.setValue(preset.m_pressure);
    m_modifierSize.setValue(preset.m_modifierSize);
    m_modifierLockAlpha.setValue(preset.m_modifierLockAlpha);
    // Recalculate based on updated presets
    m_minThick = m_rasThickness.getValue().first;
    m_maxThick = m_rasThickness.getValue().second;
    setWorkAndBackupImages();
    m_brushPad = ToolUtils::getBrushPad(preset.m_max, preset.m_hardness * 0.01);
  } catch (...) {
  }
}
mouseMove()
void ToonzRasterBrushTool::mouseMove (const TPointD & pos, const TMouseEvent & e) override virtual
Reimplemented from TTool.
{
  qApp->processEvents(QEventLoop::ExcludeUserInputEvents);
  struct Locals {
    ToonzRasterBrushTool *m_this;
    void setValue(TDoublePairProperty &prop,
                  const TDoublePairProperty::Value &value) {
      prop.setValue(value);
      m_this->onPropertyChanged(prop.getName());
      TTool::getApplication()->getCurrentTool()->notifyToolChanged();
    }
    void addMinMax(TDoublePairProperty &prop, double add) {
      if (add == 0.0) return;
      const TDoublePairProperty::Range &range = prop.getRange();
      TDoublePairProperty::Value value = prop.getValue();
      value.first  = tcrop(value.first + add, range.first, range.second);
      value.second = tcrop(value.second + add, range.first, range.second);
      setValue(prop, value);
    }
    void addMinMaxSeparate(TDoublePairProperty &prop, double min, double max) {
      if (min == 0.0 && max == 0.0) return;
      const TDoublePairProperty::Range &range = prop.getRange();
      TDoublePairProperty::Value value = prop.getValue();
      value.first += min;
      value.second += max;
      if (value.first > value.second) value.first = value.second;
      value.first  = tcrop(value.first, range.first, range.second);
      value.second = tcrop(value.second, range.first, range.second);
      setValue(prop, value);
    }
  } locals = {this};
  // if (e.isAltPressed() && !e.isCtrlPressed()) {
  // const TPointD &diff = pos - m_mousePos;
  // double add = (fabs(diff.x) > fabs(diff.y)) ? diff.x : diff.y;
  // locals.addMinMax(
  //  TToonzImageP(getImage(false, 1)) ? m_rasThickness : m_thickness, add);
  //} else
  double thickness =
      (m_isMyPaintStyleSelected) ? (double)(m_maxCursorThick + 1) : m_maxThick;
  TPointD halfThick(thickness * 0.5, thickness * 0.5);
  TRectD invalidateRect(m_brushPos - halfThick, m_brushPos + halfThick);
  if (e.isCtrlPressed() && e.isAltPressed() && !e.isShiftPressed() &&
      Preferences::instance()->useCtrlAltToResizeBrushEnabled()) {
    // Resize the brush if CTRL+ALT is pressed and the preference is enabled.
    const TPointD &diff = pos - m_mousePos;
    double max          = diff.x / 2;
    double min          = diff.y / 2;
    locals.addMinMaxSeparate(m_rasThickness, min, max);
    double radius = m_rasThickness.getValue().second * 0.5;
    invalidateRect += TRectD(m_brushPos - TPointD(radius, radius),
                             m_brushPos + TPointD(radius, radius));
  } else {
    m_mousePos = pos;
    m_brushPos = getCenteredCursorPos(pos);
    invalidateRect += TRectD(pos - halfThick, pos + halfThick);
  }
  invalidate(invalidateRect.enlarge(2));
  if (m_minThick == 0 && m_maxThick == 0) {
    m_minThick = m_rasThickness.getValue().first;
    m_maxThick = m_rasThickness.getValue().second;
  }
}
onActivate()
void ToonzRasterBrushTool::onActivate () override virtual
Callback invoked whenever the tool activates.
Reimplemented from TTool.
{
  if (!m_notifier) m_notifier = new ToonzRasterBrushToolNotifier(this);
  if (m_firstTime) {
    m_firstTime = false;
    std::wstring wpreset =
        QString::fromStdString(RasterBrushPreset.getValue()).toStdWString();
    if (wpreset != CUSTOM_WSTR) {
      initPresets();
      if (!m_preset.isValue(wpreset)) wpreset = CUSTOM_WSTR;
      m_preset.setValue(wpreset);
      RasterBrushPreset = m_preset.getValueAsString();
      loadPreset();
    } else
      loadLastBrush();
  }
  m_brushPad = ToolUtils::getBrushPad(m_rasThickness.getValue().second,
                                      m_hardness.getValue() * 0.01);
  setWorkAndBackupImages();
  m_brushTimer.start();
  // TODO:app->editImageOrSpline();
}
onColorStyleChanged()
void ToonzRasterBrushTool::onColorStyleChanged ()
{
  // in case the style switched while drawing
  if (m_tileSaver) {
    bool isValid = m_enabled && m_active;
    m_enabled    = false;
    if (isValid) {
      finishRasterBrush(m_mousePos, 1);
    }
  }
  TTool::Application *app = getApplication();
  TMyPaintBrushStyle *mpbs =
      dynamic_cast<TMyPaintBrushStyle *>(app->getCurrentLevelStyle());
  m_isMyPaintStyleSelected = (mpbs) ? true : false;
  setWorkAndBackupImages();
  getApplication()->getCurrentTool()->notifyToolChanged();
}
onDeactivate()
void ToonzRasterBrushTool::onDeactivate () override virtual
Callback for tool deactivation, includes tool switch.
Reimplemented from TTool.
{
  /*---
   * onDeactivateMouseRelease
   * ---*/
  if (m_tileSaver) {
    bool isValid = m_enabled && m_active;
    m_enabled    = false;
    m_active     = false;
    if (isValid) {
      finishRasterBrush(m_mousePos,
                        1); /*-- 1 --*/
    }
  }
  m_workRas   = TRaster32P();
  m_backupRas = TRasterCM32P();
}
References finishRasterBrush(), and m_mousePos.
onEnter()
void ToonzRasterBrushTool::onEnter () override virtual
Callback for the mouse entering the viewer area.
Reimplemented from TTool.
{
  TImageP img = getImage(false);
  m_minThick = m_rasThickness.getValue().first;
  m_maxThick = m_rasThickness.getValue().second;
  updateCurrentStyle();
  Application *app = getApplication();
  m_styleId       = app->getCurrentLevelStyleIndex();
  TColorStyle *cs = app->getCurrentLevelStyle();
  if (cs) {
    TRasterStyleFx *rfx = cs->getRasterStyleFx();
    m_active            = cs->isStrokeStyle() || (rfx && rfx->isInkStyle());
    m_currentColor      = cs->getAverageColor();
    m_currentColor.m    = 255;
  } else {
    m_currentColor = TPixel32::Black;
  }
  m_active = img;
}
References TColorStyle::getAverageColor(), TTool::getImage(), TColorStyle::getRasterStyleFx(), and TColorStyle::isStrokeStyle().
onImageChanged()
void ToonzRasterBrushTool::onImageChanged () override virtual
Notifies changes in the image in use.
Reimplemented from TTool.
{
  if (!isEnabled()) return;
  setWorkAndBackupImages();
}
onLeave()
void ToonzRasterBrushTool::onLeave () override virtual
Callback for the mouse leaving the viewer area.
Reimplemented from TTool.
{
  m_minThick       = 0;
  m_maxThick       = 0;
  m_minCursorThick = 0;
  m_maxCursorThick = 0;
}
onPropertyChanged()
bool ToonzRasterBrushTool::onPropertyChanged (std::string propertyName) override virtual
 Does the tasks associated to changes in \p propertyName and returns \p
true; Does the tasks associated to changes in propertyName and returns true.
Reimplemented from TTool.
{
  if (m_propertyUpdating) return true;
  if (propertyName == m_preset.getName()) {
    if (m_preset.getValue() != CUSTOM_WSTR)
      loadPreset();
    else  // Chose <custom>, go back to last saved brush settings
      loadLastBrush();
    RasterBrushPreset  = m_preset.getValueAsString();
    m_propertyUpdating = true;
    getApplication()->getCurrentTool()->notifyToolChanged();
    m_propertyUpdating = false;
    return true;
  }
  RasterBrushMinSize       = m_rasThickness.getValue().first;
  RasterBrushMaxSize       = m_rasThickness.getValue().second;
  BrushSmooth              = m_smooth.getValue();
  BrushDrawOrder           = m_drawOrder.getIndex();
  RasterBrushPencilMode    = m_pencil.getValue();
  BrushPressureSensitivity = m_pressure.getValue();
  RasterBrushHardness      = m_hardness.getValue();
  RasterBrushModifierSize  = m_modifierSize.getValue();
  BrushLockAlpha           = m_modifierLockAlpha.getValue();
  // Recalculate/reset based on changed settings
  if (propertyName == m_rasThickness.getName()) {
    m_minThick = m_rasThickness.getValue().first;
    m_maxThick = m_rasThickness.getValue().second;
  }
  if (propertyName == m_hardness.getName()) setWorkAndBackupImages();
  if (propertyName == m_hardness.getName() ||
      propertyName == m_rasThickness.getName()) {
    m_brushPad = getBrushPad(m_rasThickness.getValue().second,
                             m_hardness.getValue() * 0.01);
    TRectD rect(m_mousePos - TPointD(m_maxThick + 2, m_maxThick + 2),
                m_mousePos + TPointD(m_maxThick + 2, m_maxThick + 2));
    invalidate(rect);
  }
  if (m_preset.getValue() != CUSTOM_WSTR) {
    m_preset.setValue(CUSTOM_WSTR);
    RasterBrushPreset  = m_preset.getValueAsString();
    m_propertyUpdating = true;
    getApplication()->getCurrentTool()->notifyToolChanged();
    m_propertyUpdating = false;
  }
  return true;
}
References TTool::invalidate(), m_mousePos, and ToolHandle::notifyToolChanged().
preLeftButtonDown()
bool ToonzRasterBrushTool::preLeftButtonDown () override virtual
This method is called before leftButtonDown() and can be used e.g. to create the image if needed. return true if the method execution can have changed the current tool
Reimplemented from TTool.
{
  touchImage();
  if (m_isFrameCreated) {
    setWorkAndBackupImages();
    // When the xsheet frame is selected, whole viewer will be updated from
    // SceneViewer::onXsheetChanged() on adding a new frame.
    // We need to take care of a case when the level frame is selected.
    if (m_application->getCurrentFrame()->isEditingLevel()) invalidate();
  }
  return true;
}
References TTool::invalidate(), TTool::m_isFrameCreated, and TTool::touchImage().
removePreset()
void ToonzRasterBrushTool::removePreset ()
{
  std::wstring name(m_preset.getValue());
  if (name == CUSTOM_WSTR) return;
  m_presetsManager.removePreset(name);
  initPresets();
  // No parameter change, and set the preset value to custom
  m_preset.setValue(CUSTOM_WSTR);
  RasterBrushPreset = m_preset.getValueAsString();
}
setWorkAndBackupImages()
void ToonzRasterBrushTool::setWorkAndBackupImages ()
{
  TToonzImageP ti = (TToonzImageP)getImage(false, 1);
  if (!ti) return;
  TRasterP ras   = ti->getRaster();
  TDimension dim = ras->getSize();
  double hardness = m_hardness.getValue() * 0.01;
  if (!m_isMyPaintStyleSelected && hardness == 1.0 &&
      ras->getPixelSize() == 4) {
    m_workRas   = TRaster32P();
    m_backupRas = TRasterCM32P();
  } else {
    if (!m_workRas || m_workRas->getLx() > dim.lx ||
        m_workRas->getLy() > dim.ly)
      m_workRas = TRaster32P(dim);
    if (!m_backupRas || m_backupRas->getLx() > dim.lx ||
        m_backupRas->getLy() > dim.ly)
      m_backupRas = TRasterCM32P(dim);
    m_strokeRect.empty();
    m_lastRect.empty();
  }
}
updateTranslation()
void ToonzRasterBrushTool::updateTranslation () override virtual
Reimplemented from TTool.
{
  m_rasThickness.setQStringName(tr("Size"));
  m_hardness.setQStringName(tr("Hardness:"));
  m_smooth.setQStringName(tr("Smooth:"));
  m_drawOrder.setQStringName(tr("Draw Order:"));
  m_drawOrder.setItemUIName(L"Over All", tr("Over All"));
  m_drawOrder.setItemUIName(L"Under All", tr("Under All"));
  m_drawOrder.setItemUIName(L"Palette Order", tr("Palette Order"));
  m_modifierSize.setQStringName(tr("Size"));
  // m_filled.setQStringName(tr("Filled"));
  m_preset.setQStringName(tr("Preset:"));
  m_preset.setItemUIName(CUSTOM_WSTR, tr("<custom>"));
  m_pencil.setQStringName(tr("Pencil"));
  m_pressure.setQStringName(tr("Pressure"));
  m_modifierLockAlpha.setQStringName(tr("Lock Alpha"));
}
updateWorkAndBackupRasters()
void ToonzRasterBrushTool::updateWorkAndBackupRasters (const TRect & rect)
{
  TToonzImageP ti = TImageP(getImage(false, 1));
  if (!ti) return;
  TRasterCM32P ras = ti->getRaster();
  if (m_isMyPaintStyleSelected) {
    const int denominator = 8;
    TRect enlargedRect    = rect + m_lastRect;
    int dx                = (enlargedRect.getLx() - 1) / denominator + 1;
    int dy                = (enlargedRect.getLy() - 1) / denominator + 1;
    if (m_lastRect.isEmpty()) {
      enlargedRect.x0 -= dx;
      enlargedRect.y0 -= dy;
      enlargedRect.x1 += dx;
      enlargedRect.y1 += dy;
      TRect _rect = enlargedRect * ras->getBounds();
      if (_rect.isEmpty()) return;
      m_workRas->extract(_rect)->copy(ras->extract(_rect));
      m_backupRas->extract(_rect)->copy(ras->extract(_rect));
    } else {
      if (enlargedRect.x0 < m_lastRect.x0) enlargedRect.x0 -= dx;
      if (enlargedRect.y0 < m_lastRect.y0) enlargedRect.y0 -= dy;
      if (enlargedRect.x1 > m_lastRect.x1) enlargedRect.x1 += dx;
      if (enlargedRect.y1 > m_lastRect.y1) enlargedRect.y1 += dy;
      TRect _rect = enlargedRect * ras->getBounds();
      if (_rect.isEmpty()) return;
      TRect _lastRect    = m_lastRect * ras->getBounds();
      QList<TRect> rects = ToolUtils::splitRect(_rect, _lastRect);
      for (int i = 0; i < rects.size(); i++) {
        m_workRas->extract(rects[i])->copy(ras->extract(rects[i]));
        m_backupRas->extract(rects[i])->copy(ras->extract(rects[i]));
      }
    }
    m_lastRect = enlargedRect;
    return;
  }
  TRect _rect     = rect * ras->getBounds();
  TRect _lastRect = m_lastRect * ras->getBounds();
  if (_rect.isEmpty()) return;
  if (m_lastRect.isEmpty()) {
    m_workRas->extract(_rect)->clear();
    m_backupRas->extract(_rect)->copy(ras->extract(_rect));
    return;
  }
  QList<TRect> rects = ToolUtils::splitRect(_rect, _lastRect);
  for (int i = 0; i < rects.size(); i++) {
    m_workRas->extract(rects[i])->clear();
    m_backupRas->extract(rects[i])->copy(ras->extract(rects[i]));
  }
}
Member Data Documentation
m_active
bool ToonzRasterBrushTool::m_active protected
m_backupRas
TRasterCM32P ToonzRasterBrushTool::m_backupRas protected
m_bluredBrush
BluredBrush* ToonzRasterBrushTool::m_bluredBrush protected
m_brushPad
QRadialGradient ToonzRasterBrushTool::m_brushPad protected
m_brushPos
TPointD ToonzRasterBrushTool::m_brushPos protected
World position the brush will be painted at.
Referenced by draw().
m_brushTimer
QElapsedTimer ToonzRasterBrushTool::m_brushTimer protected
m_currentColor
TPixel32 ToonzRasterBrushTool::m_currentColor protected
m_dpiScale
TPointD ToonzRasterBrushTool::m_dpiScale protected
m_drawOrder
TEnumProperty ToonzRasterBrushTool::m_drawOrder protected
m_enabled
bool ToonzRasterBrushTool::m_enabled protected
m_firstTime
bool ToonzRasterBrushTool::m_firstTime protected
m_hardness
TDoubleProperty ToonzRasterBrushTool::m_hardness protected
m_isMyPaintStyleSelected
bool ToonzRasterBrushTool::m_isMyPaintStyleSelected = false protected
m_isPrompting
bool ToonzRasterBrushTool::m_isPrompting protected
Whether the tool is prompting for spline substitution.
m_lastRect
TRect ToonzRasterBrushTool::m_lastRect protected
m_maxCursorThick
int ToonzRasterBrushTool::m_maxCursorThick protected
m_maxThick
double ToonzRasterBrushTool::m_maxThick protected
m_minCursorThick
int ToonzRasterBrushTool::m_minCursorThick protected
m_minThick
double ToonzRasterBrushTool::m_minThick protected
m_modifierLockAlpha
TBoolProperty ToonzRasterBrushTool::m_modifierLockAlpha protected
m_modifierSize
TDoubleProperty ToonzRasterBrushTool::m_modifierSize protected
m_mousePos
TPointD ToonzRasterBrushTool::m_mousePos protected
Current mouse position, in world coordinates.
Referenced by onDeactivate(), and onPropertyChanged().
m_notifier
ToonzRasterBrushToolNotifier* ToonzRasterBrushTool::m_notifier protected
m_pencil
TBoolProperty ToonzRasterBrushTool::m_pencil protected
m_points
std::vector<TThickPoint> ToonzRasterBrushTool::m_points protected
m_preset
TEnumProperty ToonzRasterBrushTool::m_preset protected
m_presetsLoaded
bool ToonzRasterBrushTool::m_presetsLoaded protected
m_presetsManager
BrushPresetManager ToonzRasterBrushTool::m_presetsManager protected
Manager for presets of this tool instance.
m_pressure
TBoolProperty ToonzRasterBrushTool::m_pressure protected
m_prop
TPropertyGroup ToonzRasterBrushTool::m_prop[2] protected
m_propertyUpdating
bool ToonzRasterBrushTool::m_propertyUpdating = false protected
m_rasterTrack
RasterStrokeGenerator* ToonzRasterBrushTool::m_rasterTrack protected
m_rasThickness
TDoublePairProperty ToonzRasterBrushTool::m_rasThickness protected
m_smooth
TDoubleProperty ToonzRasterBrushTool::m_smooth protected
m_smoothStroke
SmoothStroke ToonzRasterBrushTool::m_smoothStroke protected
m_strokeRect
TRect ToonzRasterBrushTool::m_strokeRect protected
m_strokeSegmentRect
TRect ToonzRasterBrushTool::m_strokeSegmentRect protected
m_styleId
int ToonzRasterBrushTool::m_styleId protected
m_targetType
int ToonzRasterBrushTool::m_targetType protected
m_tileSaver
TTileSaverCM32* ToonzRasterBrushTool::m_tileSaver protected
m_tileSet
TTileSetCM32* ToonzRasterBrushTool::m_tileSet protected
m_toonz_brush
MyPaintToonzBrush* ToonzRasterBrushTool::m_toonz_brush = 0 protected
m_workingFrameId
TFrameId ToonzRasterBrushTool::m_workingFrameId protected
m_workRas
TRaster32P ToonzRasterBrushTool::m_workRas protected
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/tnztools/toonzrasterbrushtool.h
E:/opentoonz/toonz/sources/tnztools/toonzrasterbrushtool.cpp