opentoonz: TMacroFx Class Reference
TMacroFx Class Reference final
Public Member Functions
TFx * clone (bool recursive=true) const override
bool doGetBBox (double frame, TRectD &bBox, const TRenderSettings &info) override
void doDryCompute (TRectD &rect, double frame, const TRenderSettings &info) override
void doCompute (TTile &tile, double frame, const TRenderSettings &ri) override
TFxTimeRegion getTimeRegion () const override
std::string getPluginId () const override
void setRoot (TFx *root)
TFx * getRoot () const
TFx * getFxById (const std::wstring &id) const
const std::vector< TFxP > & getFxs () const
std::string getMacroFxType () const
bool canHandle (const TRenderSettings &info, double frame) override
std::string getAlias (double frame, const TRenderSettings &info) const override
void loadData (TIStream &is) override
void saveData (TOStream &os) override
bool isEditing ()
void editMacro (bool edit)
void compatibilityTranslatePort (int majorVersion, int minorVersion, std::string &portName) override
void linkParams (TFx *src) override
bool isLoading ()
void setWaitingLinkFx (TMacroFx *linkFx)
Public Member Functions inherited from TRasterFx
virtual bool getBBox (double frame, TRectD &bBox, TPixel32 &bgColor)=0
virtual string getName () const =0
virtual TRect getInvalidRect (const TRect &max)=0
virtual void compute (double frame, const TTile &tile)=0
virtual void allocateAndCompute (double frame, const TDimension size, const TPointD &pos, TTile &tile)
virtual void compute (TTile &tile, double frame, const TRenderSettings &info)
This method supplies the actual fx rendering code.
void allocateAndCompute (TTile &tile, const TPointD &pos, const TDimension &size, TRasterP templateRas, double frame, const TRenderSettings &info)
virtual bool doGetBBox (double frame, TRectD &bBox, const TRenderSettings &info)=0
bool getBBox (double frame, TRectD &bBox, const TRenderSettings &info)
virtual bool isCachable () const
virtual void transform (double frame, int port, const TRectD &rectOnOutput, const TRenderSettings &infoOnOutput, TRectD &rectOnInput, TRenderSettings &infoOnInput)
virtual bool canHandle (const TRenderSettings &info, double frame)=0
virtual TAffine handledAffine (const TRenderSettings &info, double frame)
void enableCache (bool on)
bool isCacheEnabled () const
std::string getAlias (double frame, const TRenderSettings &info) const override
virtual void dryCompute (TRectD &rect, double frame, const TRenderSettings &info)
virtual int getMemoryRequirement (const TRectD &rect, double frame, const TRenderSettings &info)
virtual bool allowUserCacheOnPort (int port)
virtual bool isPlugin () const
Public Member Functions inherited from TFx
virtual std::wstring getName () const
void setName (std::wstring name)
std::wstring getFxId () const
void setFxId (std::wstring id)
TParamContainer * getParams ()
const TParamContainer * getParams () const
void addParamVar (TParamVar *var)
virtual TFx * clone (bool recursive=true) const
TFx * clone (TFx *fx, bool recursive) const
void unlinkParams ()
virtual void linkParams (TFx *src)
TFx * getLinkedFx () const
bool addInputPort (const std::string &name, TFxPort &p)
bool addInputPort (const std::string &name, TFxPort *p, int groupIndex)
bool removeInputPort (const std::string &name)
returns false on duplicate names. Ownership is transferred to the group.
bool renamePort (const std::string &oldName, const std::string &newName)
if not found.
bool connect (const std::string &name, TFx *other)
Equivalent to getInputPort(name)->setFx(other).
bool disconnect (const std::string &name)
Equivalent to getInputPort(name)->setFx(0).
int getInputPortCount () const
TFxPort * getInputPort (int index) const
TFxPort * getInputPort (const std::string &name) const
std::string getInputPortName (int index) const
virtual int dynamicPortGroupsCount () const
virtual const TFxPortDG * dynamicPortGroup (int g) const
bool hasDynamicPortGroups () const
void clearDynamicPortGroup (int g)
bool addOutputConnection (TFxPort *port)
bool removeOutputConnection (TFxPort *port)
virtual bool isZerary () const
virtual int getReferenceColumnIndex () const
virtual TFxPort * getXsheetPort () const
int getOutputConnectionCount () const
TFxPort * getOutputConnection (int i) const
virtual TFxTimeRegion getTimeRegion () const
void setActiveTimeRegion (const TFxTimeRegion &tr)
TFxTimeRegion getActiveTimeRegion () const
virtual bool checkActiveTimeRegion () const
void disconnectAll ()
virtual void getParamUIs (TParamUIConcept *&params, int &length)
std::string getFxType () const
virtual std::string getPluginId () const =0
void onChange (const TParamChange &c) override
void addObserver (TFxObserver *)
void removeObserver (TFxObserver *)
void notify (const TFxChange &change)
void notify (const TFxPortAdded &change)
void notify (const TFxPortRemoved &change)
void notify (const TFxParamAdded &change)
void notify (const TFxParamRemoved &change)
void loadData (TIStream &is) override
void saveData (TOStream &os) override
void loadPreset (TIStream &is)
void savePreset (TOStream &os)
TFxAttributes * getAttributes () const
virtual std::string getAlias (double frame, const TRenderSettings &info) const
virtual void compatibilityTranslatePort (int majorVersion, int minorVersion, std::string &portName)
virtual int getPreferredInputPort ()
virtual void callStartRenderHandler ()
virtual void callEndRenderHandler ()
virtual void callStartRenderFrameHandler (const TRenderSettings *rs, double frame)
virtual void callEndRenderFrameHandler (const TRenderSettings *rs, double frame)
virtual void onObsoleteParamLoaded (const std::string &paramName)
void setFxVersion (int)
int getFxVersion () const
unsigned long getIdentifier () const
void setIdentifier (unsigned long id)
void setNewIdentifier ()
Public Member Functions inherited from TSmartObject
TSmartObject (ClassCode classCode)
void addRef ()
void release ()
TINT32 getRefCount () const
Public Member Functions inherited from TPersist
virtual void loadData (TIStream &is)=0
virtual void saveData (TOStream &os)=0
std::string getStreamTag () const
virtual const TPersistDeclaration * getDeclaration () const =0
virtual void onChange (const TParamChange &)=0
Static Public Member Functions
static bool analyze (const std::vector< TFxP > &fxs, TFxP &root, std::vector< TFxP > &roots, std::vector< TFxP > &leafs)
static bool analyze (const std::vector< TFxP > &fxs)
static TMacroFx * create (const std::vector< TFxP > &fxs)
Static Public Member Functions inherited from TRasterFx
static TRasterP applyAffine (TTile &tileOut, const TTile &tileIn, const TRenderSettings &info)
static int memorySize (const TRectD &rect, int bpp)
Static Public Member Functions inherited from TFx
static void listFxs (std::vector< TFxInfo > &fxInfos)
static TFxInfo getFxInfo (const std::string &fxIdentifier)
static TFx * create (std::string name)
Static Public Member Functions inherited from TSmartObject
static TINT32 getInstanceCount (ClassCode code)
Static Public Member Functions inherited from TPersist
static void declare (CreateProc *)
static TPersist * create (const std::string &name)
Additional Inherited Members
Public Types inherited from TFx
typedef TFx * CreateProc()
Public Types inherited from TSmartObject
typedef short ClassCode
Public Types inherited from TPersist
typedef TPersist * CreateProc()
virtual void doCompute (TTile &tile, double frame, const TRenderSettings &settings)=0
virtual void doDryCompute (TRectD &rect, double frame, const TRenderSettings &info)
Detailed Description
Constructor & Destructor Documentation
TMacroFx()
TMacroFx::TMacroFx ()
: m_isEditing(false) {}
~TMacroFx()
TMacroFx::~TMacroFx ()
{}
Member Function Documentation
analyze() [1/2]
bool TMacroFx::analyze (const std::vector< TFxP > & fxs) static
{
  TFxP root = 0;
  std::vector<TFxP> leafs;
  std::vector<TFxP> roots;
  return analyze(fxs, root, roots, leafs);
}
analyze() [2/2]
bool TMacroFx::analyze (const std::vector< TFxP > & fxs, TFxP & root, std::vector< TFxP > & roots, std::vector< TFxP > & leafs) static
{
  if (fxs.size() == 1)
    return false;
  else {
    leafs.clear();
    roots.clear();
    std::vector<TFxP>::const_iterator it = fxs.begin();
    for (; it != fxs.end(); ++it) {
      TFxP fx                      = *it;
      int inputInternalConnection  = 0;
      int inputExternalConnection  = 0;
      int outputInternalConnection = 0;
      int outputExternalConnection = 0;
      int i;
      // calcola se ci sono connessioni in input dall'esterno
      // verso l'interno e/o internamente a orderedFxs
      int inputPortCount = fx->getInputPortCount();
      for (i = 0; i < inputPortCount; ++i) {
        TFxPort *inputPort = fx->getInputPort(i);
        TFx *inputPortFx   = inputPort->getFx();
        if (inputPortFx) {
          if (std::find_if(fxs.begin(), fxs.end(), MatchesFx(inputPortFx)) !=
              fxs.end())
            ++inputInternalConnection;
          else
            ++inputExternalConnection;
        }
      }
      // calcola se ci sono connessioni in output dall'interno
      // verso l'esterno e/o internamente a orderedFxs
      int outputPortCount = fx->getOutputConnectionCount();
      for (i = 0; i < outputPortCount; ++i) {
        TFxPort *outputPort = fx->getOutputConnection(i);
        TFx *outputFx       = outputPort->getOwnerFx();
        if (outputFx) {
          if (std::find_if(fxs.begin(), fxs.end(), MatchesFx(outputFx)) !=
              fxs.end())
            ++outputInternalConnection;
          else
            ++outputExternalConnection;
        }
      }
      // se fx e' una radice
      if ((outputExternalConnection > 0) ||
          (outputExternalConnection == 0 && outputInternalConnection == 0)) {
        root = fx;
        roots.push_back(fx);
      }
      // se fx e' una foglia
      if (inputExternalConnection > 0 || fx->getInputPortCount() == 0 ||
          (inputExternalConnection == 0 &&
           inputInternalConnection < fx->getInputPortCount())) {
        leafs.push_back(fx);
      }
    }
    if (roots.size() != 1)
      return false;
    else {
      if (leafs.size() == 0) return false;
    }
    return true;
  }
}
canHandle()
bool TMacroFx::canHandle (const TRenderSettings & info, double frame) override virtual
Implements TRasterFx.
{
  return m_root->canHandle(info, frame);
}
clone()
TFx * TMacroFx::clone (bool recursive = true) const override virtual
Reimplemented from TFx.
{
  int n = m_fxs.size();
  std::vector<TFxP> clones(n);
  std::map<TFx *, int> table;
  std::map<TFx *, int>::iterator it;
  int i, rootIndex = -1;
  // nodi
  for (i = 0; i < n; ++i) {
    TFx *fx = m_fxs[i].getPointer();
    assert(fx);
    clones[i] = fx->clone(false);
    assert(table.count(fx) == 0);
    table[fx] = i;
    if (fx == m_root.getPointer()) rootIndex = i;
    TFx *linkedFx = fx->getLinkedFx();
    if (linkedFx && table.find(linkedFx) != table.end())
      clones[i]->linkParams(clones[table[linkedFx]].getPointer());
  }
  assert(rootIndex >= 0);
  // connessioni
  for (i = 0; i < n; i++) {
    TFx *fx = m_fxs[i].getPointer();
    for (int j = 0; j < fx->getInputPortCount(); j++) {
      TFxPort *port = fx->getInputPort(j);
      TFx *inputFx  = port->getFx();
      if (!inputFx) continue;
      it = table.find(inputFx);
      if (it == table.end()) {
        // il j-esimo input di fx e' esterno alla macro
        if (recursive)
          clones[i]->connect(fx->getInputPortName(j), inputFx->clone(true));
      } else {
        // il j-esimo input di fx e' interno alla macro
        clones[i]->connect(fx->getInputPortName(j),
                           clones[it->second].getPointer());
      }
    }
  }
  // TFx *rootClone =
  //  const_cast<TMacroFx*>(this)->
  //  clone(m_root.getPointer(), recursive, visited, clones);
  TMacroFx *clone = TMacroFx::create(clones);
  clone->setName(getName());
  clone->setFxId(getFxId());
  // Copy the index of the passive cache manager.
  clone->getAttributes()->passiveCacheDataIdx() =
      getAttributes()->passiveCacheDataIdx();
  assert(clone->getRoot() == clones[rootIndex].getPointer());
  return clone;
}
compatibilityTranslatePort()
void TMacroFx::compatibilityTranslatePort (int majorVersion, int minorVersion, std::string & portName) override virtual
Compatibility function - used to translate a port name from older Toonz versions into its current form.
Reimplemented from TFx.
{
  // Reroute translation to the actual fx associated to the port
  const std::string &fxId =
      portName.substr(portName.find_last_of('_') + 1, std::string::npos);
  if (TFx *fx = getFxById(::to_wstring(fxId))) {
    size_t opnEnd = portName.find_first_of('_');
    std::string originalPortName = portName.substr(0, opnEnd);
    fx->compatibilityTranslatePort(major, minor, originalPortName);
    portName.replace(0, opnEnd, originalPortName);
  }
  // Seems that at a certain point, the port name got extended...
  if (VersionNumber(major, minor) == VersionNumber(1, 16)) {
    for (int i = 0; i < getInputPortCount(); ++i) {
      const std::string &name = getInputPortName(i);
      if (name.find(portName) != std::string::npos) {
        portName = name;
        break;
      }
    }
  }
}
References TFx::compatibilityTranslatePort(), and getFxById().
Referenced by loadData().
create()
TMacroFx * TMacroFx::create (const std::vector< TFxP > & fxs) static
{
  std::vector<TFxP> leafs;
  std::vector<TFxP> roots;
  TFxP root = 0;
  std::vector<TFxP> orederedFxs = sortFxs(fxs);
  // verifica che gli effetti selezionati siano idonei ad essere raccolti
  // in una macro. Ci deve essere un solo nodo terminale
  // (roots.size()==1, roots[0] == root) e uno o piu' nodi di ingresso
  // (assert leafs.size()>0)
  if (!analyze(orederedFxs, root, roots, leafs)) return 0;
  // -----------------------------
  TMacroFx *macroFx = new TMacroFx;
  // tutti i nodi vengono spostati (e non copiati) nella macro stessa
  std::vector<TFxP>::const_iterator it = orederedFxs.begin();
  for (; it != orederedFxs.end(); ++it) macroFx->m_fxs.push_back(*it);
  // i nodi di ingresso vengono messi in collegamento con le
  // porte di ingresso della macro
  for (int i = 0; i < (int)leafs.size(); i++) {
    TFxP fx   = leafs[i];
    int k     = 0;
    int count = fx->getInputPortCount();
    for (; k < count; k++) {
      TFxPort *port        = fx->getInputPort(k);
      std::string portName = fx->getInputPortName(k);
      std::string fxId     = ::to_string(fx->getFxId());
      portName +=
          "_" + std::to_string(macroFx->getInputPortCount()) + "_" + fxId;
      TFx *portFx = port->getFx();
      if (portFx) {
        // se la porta k-esima del nodo di ingresso i-esimo e' collegata
        // ad un effetto, la porta viene inserita solo se l'effetto non fa
        // gia' parte della macro
        if (std::find_if(orederedFxs.begin(), orederedFxs.end(),
                         MatchesFx(portFx)) == orederedFxs.end())
          macroFx->addInputPort(portName, *port);
      } else
        macroFx->addInputPort(portName, *port);
    }
  }
  // le porte di uscita di root diventano le porte di uscita della macro
  int count = root->getOutputConnectionCount();
  int k     = count - 1;
  for (; k >= 0; --k) {
    TFxPort *port = root->getOutputConnection(k);
    port->setFx(macroFx);
  }
  macroFx->setRoot(root.getPointer());
  // tutti i parametri delle funzioni figlie diventano parametri della macro
  collectParams(macroFx);
  return macroFx;
}
doCompute()
void TMacroFx::doCompute (TTile & tile, double frame, const TRenderSettings & ri) override virtual
Implements TRasterFx.
{
  assert(m_root);
  m_root->compute(tile, frame, ri);
}
doDryCompute()
void TMacroFx::doDryCompute (TRectD & rect, double frame, const TRenderSettings & info) override virtual
Declares the computation scheme of this fx for rendering optimization purposes. This is an important function of the Toonz rendering API, and should be reimplemented with the necessary care. The Toonz rendering process makes use of this function to enact most of the optimization steps about the fx computation, in particular fx caching. A correct implementation of this method should follow these rules: The invocation of child node computations should be faithfully reproduced. TRasterFx::compute and TRasterFx::allocateAndCompute calls have to be translated to TRasterFx::dryCompute calls. This fx is intended for precomputation stage, so the hard rendering code should be skipped here. By default, this method raises a dryCompute call to each input port in increasing order, using the TRasterFx::transform method to identify the tiles to be passed on input precomputation.
Reimplemented from TRasterFx.
{
  assert(m_root);
  m_root->dryCompute(rect, frame, info);
}
doGetBBox()
bool TMacroFx::doGetBBox (double frame, TRectD & bBox, const TRenderSettings & info) override virtual
Implements TRasterFx.
{
  return m_root->doGetBBox(frame, bBox, info);
}
editMacro()
void TMacroFx::editMacro (bool edit) inline
{ m_isEditing = edit; }
getAlias()
std::string TMacroFx::getAlias (double frame, const TRenderSettings & info) const override virtual
Reimplemented from TFx.
{
  std::string alias = getFxType();
  alias += "[";
  // alias degli effetti connessi alle porte di input separati da virgole
  // una porta non connessa da luogo a un alias vuoto (stringa vuota)
  int i;
  for (i = 0; i < getInputPortCount(); i++) {
    TFxPort *port = getInputPort(i);
    if (port->isConnected()) {
      TRasterFxP ifx = port->getFx();
      assert(ifx);
      alias += ifx->getAlias(frame, info);
    }
    alias += ",";
  }
  // alias dei valori dei parametri dell'effetto al frame dato
  for (int j = 0; j < (int)m_fxs.size(); j++) {
    alias += (j == 0) ? "(" : ",(";
    for (i = 0; i < m_fxs[j]->getParams()->getParamCount(); i++) {
      if (i > 0) alias += ",";
      TParam *param = m_fxs[j]->getParams()->getParam(i);
      alias += param->getName() + "=" + param->getValueAlias(frame, 2);
    }
    alias += ")";
  }
  alias += "]";
  return alias;
}
getFxById()
TFx * TMacroFx::getFxById (const std::wstring & id) const
Returns the Fx identified by id. Returns 0 if the macro does not contains an Fx with fxId equals ti id.
{
  int i;
  for (i = 0; i < (int)m_fxs.size(); i++) {
    TFx *fx = m_fxs[i].getPointer();
    if (fx->getFxId() == id) return fx;
  }
  return 0;
}
Referenced by compatibilityTranslatePort().
getFxs()
const std::vector< TFxP > & TMacroFx::getFxs () const
{ return m_fxs; }
getMacroFxType()
std::string TMacroFx::getMacroFxType () const
{
  std::string name = getFxType() + "(";
  for (int i = 0; i < (int)m_fxs.size(); i++) {
    if (i > 0) name += ",";
    if (TMacroFx *childMacro = dynamic_cast<TMacroFx *>(m_fxs[i].getPointer()))
      name += childMacro->getMacroFxType();
    else
      name += m_fxs[i]->getFxType();
  }
  return name + ")";
}
getPluginId()
std::string TMacroFx::getPluginId () const override virtual
Implements TFx.
{ return "Base"; }
getRoot()
TFx * TMacroFx::getRoot () const
{ return m_root.getPointer(); }
getTimeRegion()
TFxTimeRegion TMacroFx::getTimeRegion () const override virtual
Reimplemented from TFx.
{
  return m_root->getTimeRegion();
}
isEditing()
bool TMacroFx::isEditing () inline
{ return m_isEditing; }
isLoading()
bool TMacroFx::isLoading () inline
{ return m_isLoading; }
linkParams()
void TMacroFx::linkParams (TFx * src) override virtual
Reimplemented from TFx.
{
  // in case the src fx is not yet loaded
  // (i.e. we are in loading the src fx tree),
  // wait linking the parameters until loading src is completed
  TMacroFx *srcMacroFx = dynamic_cast<TMacroFx *>(src);
  if (srcMacroFx && srcMacroFx->isLoading()) {
    srcMacroFx->setWaitingLinkFx(this);
    return;
  }
  TFx::linkParams(src);
}
loadData()
void TMacroFx::loadData (TIStream & is) override virtual
 This is a pure virtual function and must be overridden with a method
that implements the object loading from a stream (i.e take the object's features from a formatted data stream). For example the TStageObject class use his implementation to take the values of the parameters that characterizes a stage object as name, coordinates, etc... from a file. is is an input file stream
Reimplemented from TFx.
{
  VersionNumber tnzVersion = is.getVersion();
  std::string tagName;
  while (is.openChild(tagName)) {
    if (tagName == "root") {
      // set the flag here in order to prevent the leaf macro fx in the tree
      // to try to link this fx before finish loading
      m_isLoading = true;
      TPersist *p = 0;
      is >> p;
      m_root = dynamic_cast<TFx *>(p);
      // release the flag
      m_isLoading = false;
    } else if (tagName == "nodes") {
      while (!is.eos()) {
        TPersist *p = 0;
        is >> p;
        // NOTE: In current implementation p is sharedly owned by is - it's
        // automatically
        //       released upon stream destruction if the below assignment fails
        if (TFx *fx = dynamic_cast<TFx *>(p)) {
          m_fxs.push_back(fx);
        }
      }
      // collecting params just after loading nodes since they may need on
      // loading "super" tag in case it is linked with another macro fx
      collectParams(this);
      // link parameters if there is a waiting fx for linking with this
      if (m_waitingLinkFx) {
        m_waitingLinkFx->linkParams(this);
        m_waitingLinkFx = nullptr;
      }
    } else if (tagName == "ports") {
      int i = 0;
      while (is.matchTag(tagName)) {
        if (tagName == "port") {
          std::string name = is.getTagAttribute("name");
          if (tnzVersion < VersionNumber(1, 16) && name != "") {
            TRasterFxPort *port = new TRasterFxPort();
            addInputPort(name, *port);
          } else {
            name = is.getTagAttribute("name_inFx");
            if (tnzVersion < VersionNumber(1, 17) &&
                tnzVersion != VersionNumber(0, 0))
              name.insert(name.find("_"), "_" + std::to_string(i));
            compatibilityTranslatePort(tnzVersion.first, tnzVersion.second,
                                       name);
            std::string inPortName = name;
            inPortName.erase(inPortName.find("_"), inPortName.size() - 1);
            std::string inFxId = name;
            inFxId.erase(0, inFxId.find_last_of("_") + 1);
            for (int i = 0; i < (int)m_fxs.size(); i++) {
              std::wstring fxId = m_fxs[i]->getFxId();
              if (fxId == ::to_wstring(inFxId)) {
                if (TFxPort *port = m_fxs[i]->getInputPort(inPortName))
                  addInputPort(name, *port);
              }
            }
          }
          i++;
        } else
          throw TException("unexpected tag " + tagName);
      }
    } else if (tagName == "super") {
      TRasterFx::loadData(is);
    } else
      throw TException("unexpected tag " + tagName);
    is.closeChild();
  }
}
References TFx::addInputPort(), TIStream::closeChild(), compatibilityTranslatePort(), TIStream::eos(), TIStream::getTagAttribute(), TIStream::getVersion(), TFx::loadData(), TIStream::matchTag(), and TIStream::openChild().
saveData()
void TMacroFx::saveData (TOStream & os) override virtual
 This is a pure virtual function and must be overridden with a method
that implements the object saving to a data stream (i.e put the object's features on a formatted data stream). For example the TStageObject class use his implementation to save the values of the parameters that characterizes a stage object as name, coordinates, etc... on a file os is an output file stream.
Reimplemented from TFx.
{
  int i;
  os.openChild("root");
  TPersist *p = m_root.getPointer();
  os << p;
  os.closeChild();
  os.openChild("nodes");
  for (i = 0; i < (int)m_fxs.size(); i++) {
    TFxP fx     = m_fxs[i];
    TPersist *p = fx.getPointer();
    os << p;
  }
  os.closeChild();
  os.openChild("ports");
  for (i = 0; i < getInputPortCount(); i++) {
    std::string portName = getInputPortName(i);
    std::map<std::string, std::string> attr;
    attr["name_inFx"] = portName;
    os.openCloseChild("port", attr);
  }
  os.closeChild();
  os.openChild("super");
  TRasterFx::saveData(os);
  os.closeChild();
}
References TOStream::closeChild(), TOStream::openChild(), TOStream::openCloseChild(), and TFx::saveData().
setRoot()
void TMacroFx::setRoot (TFx * root)
{
  m_root = root;
  // TFx::m_imp->m_outputPort = root->m_imp->m_outputPort;
}
setWaitingLinkFx()
void TMacroFx::setWaitingLinkFx (TMacroFx * linkFx) inline
{ m_waitingLinkFx = linkFx; }
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/tmacrofx.h
E:/opentoonz/toonz/sources/common/tfx/tmacrofx.cpp