opentoonz: DVGui::DoubleValueField Class Reference
DVGui::DoubleValueField Class Reference
The DoubleValueField class provides to view an object to manage a generic double parameter, with two cipher after decimal point.
#include <doublefield.h>
Signals
void valueChanged (bool)
void valueEditedByHand ()
Public Member Functions
DoubleValueField (QWidget *parent, DoubleValueLineEdit *lineEdit)
void getRange (double &minValue, double &maxValue)
void setRange (double minValue=0, double maxValue=0)
void setValue (double value)
double getValue ()
void setValues (double value, double minValue=0, double maxValue=0)
void enableSlider (bool enable)
bool isSliderEnabled ()
void enableRoller (bool enable)
bool isRollerEnabled ()
Protected Slots
void onSliderChanged (int value)
void onSliderReleased ()
void onLineEditValueChanged ()
void onRollerValueChanged (bool isDragging)
Protected Member Functions
void setLinearSlider (bool linear)
Protected Attributes
RollerField * m_roller
DoubleValueLineEdit * m_lineEdit
QSlider * m_slider
QWidget * m_spaceWidget
Detailed Description
The DoubleValueField class provides to view an object to manage a generic double parameter, with two cipher after decimal point.
            Inherits \b QWidget.
            The class is composed of an horizontal layout which contains two
object,
a vertical layout with a text field PrimaryDoubleLineEdit and a roller
an horizontal slider QSlider. This objects are connected, so if you change one the other automatically change. It's possible to set current value getValue(), minimum and max value, getRange(), using setValue(), setRange() or setValues(); by default value = 0, minimum value = -100.0 and maximum value = 100.0.
Maximum height object is fixed to DVGui::WidgetHeight, while width depend on parent width.
To know when double parameter value change class provides a signal, valueChanged(); class emit signal when slider value change or when editing text field is finished and current value is changed. Editing text field finished may occur if focus is lost or enter key is pressed. See SLOT: onSliderChanged(int value), onEditingFinished().
Constructor & Destructor Documentation
DoubleValueField()
DoubleValueField::DoubleValueField (QWidget * parent, DoubleValueLineEdit * lineEdit)
    : QWidget(parent)
    , m_lineEdit(lineEdit)
    , m_slider(0)
    , m_roller(0)
    , m_isLinearSlider(true) {
  assert(m_lineEdit);
  QWidget *field = new QWidget(this);
  m_roller       = new RollerField(field);
  m_slider       = new QSlider(Qt::Horizontal, this);
  field->setMaximumWidth(100);
  //---layout
  QHBoxLayout *layout = new QHBoxLayout(this);
  layout->setMargin(0);
  layout->setSpacing(5);
  {
    QVBoxLayout *vLayout = new QVBoxLayout(field);
    vLayout->setMargin(0);
    vLayout->setSpacing(0);
    {
      vLayout->addWidget(m_lineEdit);
      vLayout->addWidget(m_roller);
    }
    layout->addWidget(field);
    layout->addWidget(m_slider);
  }
  setLayout(layout);
  //----signal/slot connections
  bool ret = true;
  ret      = ret && connect(m_lineEdit, SIGNAL(valueChanged()),
                       SLOT(onLineEditValueChanged()));
  ret      = ret && connect(m_roller, SIGNAL(valueChanged(bool)),
                       SLOT(onRollerValueChanged(bool)));
  ret      = ret && connect(m_slider, SIGNAL(valueChanged(int)),
                       SLOT(onSliderChanged(int)));
  ret      = ret &&
        connect(m_slider, SIGNAL(sliderReleased()), SLOT(onSliderReleased()));
  ret = ret && connect(m_lineEdit, SIGNAL(editingFinished()), this,
                       SIGNAL(valueEditedByHand()));
  ret = ret && connect(m_slider, SIGNAL(sliderReleased()), this,
                       SIGNAL(valueEditedByHand()));
  assert(ret);
  m_spaceWidget = new QWidget();
  m_spaceWidget->setSizePolicy(QSizePolicy::Expanding, QSizePolicy::Minimum);
  layout->addWidget(m_spaceWidget, 1, Qt::AlignLeft);
  setRange(-100.0, 100.0);
}
~DoubleValueField()
DVGui::DoubleValueField::~DoubleValueField () inline
{}
Member Function Documentation
enableRoller()
void DoubleValueField::enableRoller (bool enable)
If enable is false set roller disable and hide it.
{
  m_roller->setEnabled(enable);
  if (enable)
    m_roller->show();
  else
    m_roller->hide();
}
enableSlider()
void DoubleValueField::enableSlider (bool enable)
If enable is false set slider disable and hide it.
{
  m_slider->setEnabled(enable);
  m_spaceWidget->setEnabled(!enable);
  if (enable) {
    m_slider->show();
    m_spaceWidget->hide();
  } else {
    m_slider->hide();
    m_spaceWidget->show();
  }
}
getRange()
void DoubleValueField::getRange (double & minValue, double & maxValue)
{
  m_lineEdit->getRange(minValue, maxValue);
}
getValue()
double DoubleValueField::getValue ()
{ return (m_lineEdit->getValue()); }
isRollerEnabled()
bool DoubleValueField::isRollerEnabled ()
{ return m_roller->isEnabled(); }
isSliderEnabled()
bool DoubleValueField::isSliderEnabled ()
{ return m_slider->isEnabled(); }
onLineEditValueChanged
void DoubleValueField::onLineEditValueChanged () protected slot
Set slider and roller value to current value in text field. This protected slot is called when text editing is finished. If slider value is different from text field value emit signal valueChanged().
{
  double value = m_lineEdit->getValue();
  int dicimal  = m_lineEdit->getDecimals();
  // Control necessary to prevent the change signal from being emitted more than
  // once.
  if ((pos2value(m_slider->value()) == value && m_slider->isVisible()) ||
      (m_roller->getValue() == value && m_roller->isVisible()))
    return;
  m_slider->setValue(value2pos(value));
  m_roller->setValue(value);
  emit valueChanged(false);
}
References valueChanged().
onRollerValueChanged
void DoubleValueField::onRollerValueChanged (bool isDragging) protected slot
Set text field and slider to roller current value.
If slider and text field value are different from roller value emit signal valueChanged().
{
  double value = m_roller->getValue();
  if (value == m_lineEdit->getValue()) {
    assert(pos2value(m_slider->value()) == value || !m_slider->isVisible());
    // Se isDragging e' falso e' giusto che venga emessa la notifica di
    // cambiamento.
    if (!isDragging) emit valueChanged(isDragging);
    return;
  }
  m_slider->setValue(value2pos(value));
  m_lineEdit->setValue(value);
  // Faccio in modo che il cursore sia sulla prima cifra, cosi' se la stringa
  // da visualizzare e' piu' lunga del campo le cifre che vengono troncate sono
  // le ultime e non le prime (dovrebbero essere quelle dopo la virgola).
  m_lineEdit->setCursorPosition(0);
  emit valueChanged(isDragging);
}
References valueChanged().
onSliderChanged
void DoubleValueField::onSliderChanged (int value) protected slot
Set to value the text field and roller. If text field value is different from value emit signal valueChanged(int value).
{
  double val = pos2value(sliderPos);
  // Controllo necessario per evitare che il segnale di cambiamento venga emesso
  // piu' volte.
  if (m_lineEdit->getValue() == val ||
      (m_roller->getValue() == val && m_roller->isVisible()))
    return;
  m_lineEdit->setValue(val);
  m_roller->setValue(val);
  // Faccio in modo che il cursore sia sulla prima cifra, cosi' se la stringa
  // da visualizzare e' piu' lunga del campo le cifre che vengono troncate sono
  // le ultime e non le prime (dovrebbero essere quelle dopo la virgola).
  m_lineEdit->setCursorPosition(0);
  emit valueChanged(true);
}
References valueChanged().
onSliderReleased
void DVGui::DoubleValueField::onSliderReleased () inline protected slot
{ emit valueChanged(false); }
setLinearSlider()
void DVGui::DoubleValueField::setLinearSlider (bool linear) inline protected
{ m_isLinearSlider = linear; }
setRange()
void DoubleValueField::setRange (double minValue = 0, double maxValue = 0)
{
  m_lineEdit->setRange(minValue, maxValue);
  m_roller->setRange(minValue, maxValue);
  int dicimal   = m_lineEdit->getDecimals();
  int sliderMax = (int)round(maxValue * pow(10., dicimal));
  int sliderMin = (int)round(minValue * pow(10., dicimal));
  m_slider->setRange(sliderMin, sliderMax);
  enableSlider(maxValue - minValue < 10000);
}
setValue()
void DoubleValueField::setValue (double value)
{
  if (m_lineEdit->getValue() == value) return;
  m_lineEdit->setValue(value);
  m_roller->setValue(value);
  m_slider->setValue(value2pos(value));
  // forzo il repaint... non sempre si aggiorna e l'update non sembra risolvere
  // il ptroblema!!!
  m_slider->repaint();
}
setValues()
void DoubleValueField::setValues (double value, double minValue = 0, double maxValue = 0)
This is provided for convenience. Set to value current value DoubleField; set to minValue and maxValue slider and text field range.
See also
getValue()
{
  setRange(minValue, maxValue);
  setValue(value);
}
valueChanged
void DVGui::DoubleValueField::valueChanged (bool) signal
This signal is emitted when DoubleFiel, slider, roller or text field, value change; if slider position change or text field editing is finished.
See also
onEditingFinished() and onSliderChanged(int value).
Referenced by onLineEditValueChanged(), onRollerValueChanged(), and onSliderChanged().
valueEditedByHand
void DVGui::DoubleValueField::valueEditedByHand () signal
This signal is emitted only when users edited the value by hand
Member Data Documentation
m_lineEdit
DoubleValueLineEdit* DVGui::DoubleValueField::m_lineEdit protected
m_roller
RollerField* DVGui::DoubleValueField::m_roller protected
m_slider
QSlider* DVGui::DoubleValueField::m_slider protected
m_spaceWidget
QWidget* DVGui::DoubleValueField::m_spaceWidget protected
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/toonzqt/doublefield.h
E:/opentoonz/toonz/sources/toonzqt/doublefield.cpp