opentoonz: TThread::Executor Class Reference
TThread::Executor Class Reference
#include <tthread.h>
Classes
class Imp
Public Member Functions
void addTask (RunnableP task)
void removeTask (RunnableP task)
void cancelAll ()
void setMaxActiveTasks (int count)
void setMaxActiveLoad (int load)
int maxActiveTasks () const
int maxActiveLoad () const
void setDedicatedThreads (bool dedicated, bool persistent=true)
Specifies the use of dedicated threads for the Executor's task group.
Static Public Member Functions
static void init ()
static void shutdown ()
Friends
class ExecutorImp
Detailed Description
Executor class provides an effective way for planning the execution of user-defined tasks that require separate working threads.
When an application needs to perform a resource-consuming task, it is often a good idea to dedicate a separate thread for it, especially in GUI applications; however, doing so eventually raises the problem of managing such intensive tasks in a way that constantly ensures the correct use of the machine resources - so that in any given time the CPU usage is maximal, but not overloaded. Additional requests by the user may arise, including preferenced ordering among tasks, the necessity of salvaging some CPU resources or threads for incoming tasks, and so on.
The TThread namespace API contains two main classes, Runnable and Executor, which provide a way for implementing consistent threading strategies.
In order to use the Executor class it is first necessary to install the thread manager into application code by calling the static method init() appropriately.
Executors are then used to submit - or eventually remove - tasks for execution into a separate working thread, by means of the addTask(), removeTask() and cancelAll() methods. Each Executor's visibility is always limited to the tasks that it submits - so calling removeTask() or cancelAll() only affects the tasks previously added by that same Executor - which easily reflects the idea of an Executor representing a group of tasks.
Basic control over the execution strategy for the group of tasks submitted by an Executor can be acquired using the setMaxActiveTasks() and setMaxActiveLoad() methods, both granting the possibility to bound the execution of tasks to custom maximum conditions. For example, use setMaxActiveTasks(1) to force the execution of 1 task only at a time, or setMaxActiveLoad(100) to set a single CPU core available for the group.
See also
Runnable class documentation.
Constructor & Destructor Documentation
Executor()
Executor::Executor ()
: m_id(new ExecutorId) { m_id->addRef(); }
~Executor()
TThread::Executor::~Executor ()
{ m_id->release(); }
Member Function Documentation
addTask()
void TThread::Executor::addTask (RunnableP task)
Submits a task for execution. The task is executed according to its task load, insertion time and scheduling priority.
{
  {
    if (task->m_id)  // Must be done outside transition lock, since eventually
      task->m_id->release();  // invoked ~ExecutorId will lock it
    // Updating tasks and workers list - lock against state transitions
    QMutexLocker transitionLocker(&globalImp->m_transitionMutex);
    task->m_id = m_id;
    m_id->addRef();
    globalImp->insertTask(task->schedulingPriority(), task);
  }
  // If addTask is called in the main thread, the emit works directly -
  // so it is necessary to unlock the mutex *before* emitting the refresh.
  globalImpSlots->emitRefreshAssignments();
}
References TThread::Runnable::schedulingPriority().
cancelAll()
void Executor::cancelAll ()
Clears the task manager of all tasks added by this Executor and emits the Runnable::canceled signal for each of them. The same specifications described in the removeTask method apply here.
See also
Runnable::canceled signal and the removeTask method.
{
  // Updating tasks list - lock against state transitions
  QMutexLocker transitionLocker(&globalImp->m_transitionMutex);
  // Clear the tasks chronologically. So, first check currently working
  // tasks.
  std::set<Worker *>::iterator it;
  for (it = globalImp->m_workers.begin(); it != globalImp->m_workers.end();
       ++it) {
    RunnableP task = (*it)->m_task;
    if (task && task->m_id == m_id) Q_EMIT task->canceled(task);
  }
  // Finally, clear the global tasks list from all tasks inserted by this
  // executor
  // NOTE: An easier way here?
  QMutableMapIterator<int, RunnableP> jt(globalImp->m_tasks);
  while (jt.hasNext()) {
    jt.next();
    if (jt.value()->m_id == m_id) {
      RunnableP task = jt.value();
      Q_EMIT task->canceled(task);
      jt.remove();
    }
  }
}
References TThread::Runnable::canceled().
init()
void Executor::init () static
This static method declares the use of the Executor's task manager into the application code. Be sure to use it according to the following rules:
Only QCoreApplications or QApplications may use Executors.
This method must be invoked in a thread which performs constant Qt event processing - like the main loop of interactive GUI applications.
No task processing is allowed after event processing stops.
                    {
  // If no global ExecutorImp exists, allocate it now. You may not move this
  // to a static declaration, since ExecutorImpSlots's connections must be
  // made once the QCoreApplication has been constructed.
  if (!globalImp) {
    globalImp      = new ExecutorImp;
    globalImpSlots = new ExecutorImpSlots;
  }
  qRegisterMetaType<TThread::RunnableP>("TThread::RunnableP");
}
maxActiveLoad()
int Executor::maxActiveLoad () const
{
  QMutexLocker transitionLocker(&globalImp->m_transitionMutex);
  return m_id->m_maxActiveLoad;
}
maxActiveTasks()
int Executor::maxActiveTasks () const
{
  QMutexLocker transitionLocker(&globalImp->m_transitionMutex);
  return m_id->m_maxActiveTasks;
}
removeTask()
void Executor::removeTask (RunnableP task)
Removes the given task from scheduled execution and emits its Runnable::canceled signal. Tasks already under execution are not stopped by this method - although the canceled signal is still emitted. It has no effect if the task is not currently under the task manager's control.
See also
Runnable::canceled signal and the cancelAll method.
{
  // If the task does not belong to this Executor, quit.
  if (task->m_id != m_id) return;
  // Updating tasks list - lock against state transitions
  QMutexLocker transitionLocker(&globalImp->m_transitionMutex);
  // Then, look in the global queue - if it is found, emiminate the task and
  // send the canceled signal.
  if (globalImp->m_tasks.remove(task->m_schedulingPriority, task)) {
    Q_EMIT task->canceled(task);
    return;
  }
  // Finally, the task may be running - look in workers.
  std::set<Worker *> &workers = globalImp->m_workers;
  std::set<Worker *>::iterator it;
  for (it = workers.begin(); it != workers.end(); ++it)
    if (task && (*it)->m_task == task) Q_EMIT task->canceled(task);
  // No need to refresh - tasks were eventually decremented...
}
References TThread::Runnable::canceled().
setDedicatedThreads()
void Executor::setDedicatedThreads (bool dedicated, bool persistent = true)
Specifies the use of dedicated threads for the Executor's task group.
By default a worker thread attempts adoption of Runnable tasks without regard to the Executor that performed the submission. This helps in stabilizing the number of threads that are created and destroyed by the task manager - but may be a problem in some cases. Using this method the user can explicitly tell the Executor to seize the ownership of worker threads assigned to its tasks, so that they will not try adoption of external tasks but instead remain focused on Executor's tasks only. An optional persistent parameter may be passed, which specifies if dedicated threads should remain sleeping or should rather die when no processable tasks from the Executor are found. This method is especially helpful in two occasions:
The Executor's tasks use thread-specific data such as QThreadStorages, which may be recycled among different tasks.
The Executor receives tasks at a frequent rate, but mostly ends each one before another one is submitted - resulting in a continuous thread turnover.
{
  QMutexLocker transitionLocker(&globalImp->m_transitionMutex);
  m_id->m_dedicatedThreads  = dedicated;
  m_id->m_persistentThreads = persistent;
  m_id->refreshDedicatedList();
}
setMaxActiveLoad()
void Executor::setMaxActiveLoad (int maxActiveLoad)
Declares a maximum overall task load for the tasks added by this Executor. NOTE: The same remark for setMaxActiveTasks() holds here.
{
  QMutexLocker transitionLocker(&globalImp->m_transitionMutex);
  m_id->m_maxActiveLoad = maxActiveLoad;
}
setMaxActiveTasks()
void Executor::setMaxActiveTasks (int maxActiveTasks)
Declares that only a certain number of tasks added by this Executor may be processed simultaneously. The default is 1 - meaning that tasks added to the executor are completely serialized. A negative task number disables any form of task serialization. NOTE: Currently, tasks that do not satisfy this condition avoid blocking execution of tasks not added by the same Executor - even if they were scheduled for later execution.
{
  QMutexLocker transitionLocker(&globalImp->m_transitionMutex);
  if (maxActiveTasks <= 0)
    m_id->m_maxActiveTasks = (std::numeric_limits<int>::max)();
  else
    m_id->m_maxActiveTasks = maxActiveTasks;
}
shutdown()
void Executor::shutdown () static
This static method, which must be invoked in the controller thread, declares termination of all Executor-based components, forcing the execution of tasks submitted by any Executor to quit as soon as possible in a safe way. When the shutdown method is invoked, the task manager first emits a canceled() signal for all the tasks that were submitted to it, independently from the Executor that performed the submission; then, tasks that are still active once all the cancellation signals were delivered further receive a terminated() signal informing them that they must provide code termination (or at least remain silent in a safe state until the application quits). NOTE: Observe that this method does not explicitly wait for all the tasks to terminate - this depends on the code connected to the terminated() signal and is under the user's responsibility (see the remarks specified in started() signal description); if this is the intent and the terminated slot is invoked in the controller thread, you should remember to implement a local event loop in it (so that event processing is still performed) and wait there until the first finished() or catched() slot make it quit.
{
  {
    // Updating tasks list - lock against state transitions
    QMutexLocker transitionLocker(&globalImp->m_transitionMutex);
    shutdownVar = true;
    // Cancel all tasks  - first the active ones
    std::set<Worker *>::iterator it;
    for (it = globalImp->m_workers.begin(); it != globalImp->m_workers.end();
         ++it) {
      RunnableP task = (*it)->m_task;
      if (task) Q_EMIT task->canceled(task);
    }
    // Finally, deal with the global queue tasks
    QMutableMapIterator<int, RunnableP> jt(globalImp->m_tasks);
    while (jt.hasNext()) {
      jt.next();
      RunnableP task = jt.value();
      Q_EMIT task->canceled(task);
      jt.remove();
    }
    // Now, send the terminate() signal to all active tasks
    for (it = globalImp->m_workers.begin(); it != globalImp->m_workers.end();
         ++it) {
      RunnableP task = (*it)->m_task;
      if (task) Q_EMIT task->terminated(task);
    }
  }
  // Just placing a convenience processEvents() to make sure that queued slots
  // invoked by the
  // signals above are effectively invoked in this method - without having to
  // return to an event loop.
  QCoreApplication::processEvents();
}
References TThread::Runnable::canceled(), and TThread::Runnable::terminated().
Friends And Related Function Documentation
ExecutorImp
friend class ExecutorImp friend
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/tthread.h
E:/opentoonz/toonz/sources/common/tcore/tthread.cpp
E:/opentoonz/toonz/sources/toonzfarm/tnzcore_stuff/tthread.cpp