opentoonz: DVGui::ChannelField Class Reference
DVGui::ChannelField Class Reference final
The ChannelField class is used to view an object to manage a color value, red, green, blue or transparency channel.
Signals
void valueChanged (int value, bool isDragging)
Public Member Functions
ChannelField (QWidget *parent=0, const QString &string="", int value=0, int maxValue=255, bool horizontal=false, int labelWidth=13, int sliderWidth=-1)
void setChannel (int value)
int getChannel ()
Protected Slots
void onSliderChanged (int value)
void onSliderReleased ()
void onEditChanged (const QString &str)
void onEditFinished ()
Detailed Description
The ChannelField class is used to view an object to manage a color value, red, green, blue or transparency channel.
         Inherits \b QWidget.
         The object is composed of grid layout \b QGridLayout which
contains a label in first row, first column, to identify channel, a text field IntLineEdit in first row, second column, and a slider in second row, second column. Texf field and slider are connected, so if you change one the other automatically change. You can set current value getChannel(), using setChannel(). This two object is used to manage channel value, them range is fixed to [0,255]. This object size is fixed, [50, 2*DVGui::WidgetHeight].
To know when channel parameter value change class provides a signal, valueChanged(int value); class emit signal when slider value change or when text field is editing, see SLOT: onSliderChanged(int value) and onEditChanged(const QString &str) to know when signal is emitted.
Constructor & Destructor Documentation
ChannelField()
ChannelField::ChannelField (QWidget * parent = 0, const QString & string = "", int value = 0, int maxValue = 255, bool horizontal = false, int labelWidth = 13, int sliderWidth = -1)
    : QWidget(parent), m_maxValue(maxValue) {
  assert(maxValue > 0);
  assert(0 <= value && value <= m_maxValue);
  QLabel *channelName = new QLabel(string, this);
  m_channelEdit       = new DVGui::IntLineEdit(this, value, 0, maxValue);
  m_channelSlider     = new QSlider(Qt::Horizontal, this);
  m_channelSlider->setFocusPolicy(Qt::NoFocus);
  channelName->setAlignment(Qt::AlignRight | Qt::AlignVCenter);
  channelName->setFixedWidth(labelWidth);
  m_channelSlider->setRange(0, maxValue);
  m_channelSlider->setValue(value);
  if (sliderWidth > 0) m_channelSlider->setFixedWidth(sliderWidth);
  //----layout
  QGridLayout *mainLayout = new QGridLayout(this);
  mainLayout->setMargin(0);
  mainLayout->setSpacing(3);
  {
    mainLayout->addWidget(channelName, 0, 0);
    mainLayout->addWidget(m_channelEdit, 0, 1);
    mainLayout->addWidget(m_channelSlider, horizontal ? 0 : 1,
                          horizontal ? 2 : 1);
  }
  mainLayout->setColumnStretch(0, 0);
  mainLayout->setColumnStretch(1, 1);
  mainLayout->setRowStretch(2, 1);
  setLayout(mainLayout);
  //----singnal-slot connections
  bool ret = connect(m_channelEdit, SIGNAL(textChanged(const QString &)),
                     SLOT(onEditChanged(const QString &)));
  ret      = ret && connect(m_channelEdit, SIGNAL(editingFinished()),
                       SLOT(onEditFinished()));
  ret      = ret && connect(m_channelSlider, SIGNAL(valueChanged(int)),
                       SLOT(onSliderChanged(int)));
  ret      = ret && connect(m_channelSlider, SIGNAL(sliderReleased()),
                       SLOT(onSliderReleased()));
  assert(ret);
}
~ChannelField()
DVGui::ChannelField::~ChannelField () inline
{}
Member Function Documentation
getChannel()
int ChannelField::getChannel ()
Return current channel value.
See also
setChannel()
{
  int value = m_channelEdit->getValue();
  assert(m_channelSlider->value() == value);
  return value;
}
References DVGui::IntLineEdit::getValue().
Referenced by setChannel().
onEditChanged
void ChannelField::onEditChanged (const QString & str) protected slot
Set slider value to new string str value. Verify if value is lower than 255 or greater than 0, range, otherwise set current value to 255 or 0. If slider value is different from value in str emit signal valueChanged(int value).
{
  int value = str.toInt();
  if (value < 0) value = 0;
  if (value > m_maxValue) value = m_maxValue;
  assert(0 <= value && value <= m_maxValue);
  if (str.toInt() != value) m_channelEdit->setValue(value);
  if (m_channelSlider->value() == value) return;
  m_channelSlider->setValue(value);
  emit valueChanged(value, true);
}
References DVGui::IntLineEdit::setValue(), and valueChanged().
onEditFinished
void ChannelField::onEditFinished () protected slot
{
  emit valueChanged(m_channelEdit->getValue(), false);
}
onSliderChanged
void ChannelField::onSliderChanged (int value) protected slot
Set text field value to value. If text field value is different from value emit signal valueChanged(int value).
{
  assert(0 <= value && value <= m_maxValue);
  if (m_channelEdit->getValue() == value) return;
  m_channelEdit->setText(QString(std::to_string(value).c_str()));
  emit valueChanged(value, true);
}
References DVGui::IntLineEdit::getValue(), and valueChanged().
onSliderReleased
void ChannelField::onSliderReleased () protected slot
{
  emit valueChanged(m_channelSlider->value(), false);
}
setChannel()
void ChannelField::setChannel (int value)
Set current value to value.
See also
getChannel()
{
  if (getChannel() == value) return;
  assert(0 <= value && value <= m_maxValue);
  m_channelSlider->setValue(value);
  m_channelEdit->setValue(value);
}
References getChannel(), and DVGui::IntLineEdit::setValue().
Referenced by DVGui::ColorField::setAlphaActive(), and DVGui::ColorField::updateChannels().
valueChanged
void DVGui::ChannelField::valueChanged (int value, bool isDragging) signal
This signal is emitted when ChannelField, slider or text field, value change; if slider position change or text field is editing.
See also
onEditChanged(const QString &str) and onSliderChanged(int value).
Referenced by onEditChanged(), and onSliderChanged().
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/toonzqt/colorfield.h
E:/opentoonz/toonz/sources/toonzqt/colorfield.cpp