opentoonz: TColumnDataElement Class Reference
TColumnDataElement Class Reference final
Public Types
enum FxFlags { eDoClone = 0x1 , eResetFxDagPositions = 0x2 }
Public Member Functions
TColumnDataElement * clone () const override
void storeColumn (TXsheet *xsheet, int index, int fxFlags)
TStageObjectId restoreColumn (TXsheet *xsh, int index, int fxFlags, bool copyPosition) const
Public Member Functions inherited from TStageObjectDataElement
virtual TStageObjectDataElement * clone () const
void storeObject (const TStageObjectId &objectId, TXsheet *xsh)
TStageObjectId restoreObject (TXsheet *xsh, bool copyPosition) const
Friends
class StageObjectsData
Additional Inherited Members
Protected Attributes inherited from TStageObjectDataElement
TStageObjectParams * m_params
Stage object parameters (owned)
TPointD m_dagPos
Stage object position in the viewer.
Detailed Description
Class used to clone a column stage object's relational data inside the stage schematic.
Member Enumeration Documentation
FxFlags
enum TColumnDataElement::FxFlags
{ eDoClone = 0x1, eResetFxDagPositions = 0x2 };
Constructor & Destructor Documentation
TColumnDataElement()
TColumnDataElement::TColumnDataElement ()
    : TStageObjectDataElement(), m_column(0) {}
~TColumnDataElement()
TColumnDataElement::~TColumnDataElement ()
{}
Member Function Documentation
clone()
TColumnDataElement * TColumnDataElement::clone () const override virtual
Clones the stord data.
Warning
Clones the stored TXshColumnP, too.
Reimplemented from TStageObjectDataElement.
{
  TColumnDataElement *element = new TColumnDataElement();
  element->m_params = m_params->clone();
  element->m_dagPos = m_dagPos;
  element->m_column = m_column;
  if (element->m_column) element->m_column = element->m_column->clone();
  return element;
}
References TStageObjectDataElement::m_dagPos, and TStageObjectDataElement::m_params.
restoreColumn()
TStageObjectId TColumnDataElement::restoreColumn (TXsheet * xsh, int index, int fxFlags, bool copyPosition) const
Inserts the stored column in the supplied xsheet with the specified column index, returning the new associated stage object id. Supported additional flags include performing a clone of the associated TXshColumnP rather than restoring the stored column directly.
{
  bool doClone             = (fxFlags & eDoClone);
  bool resetFxDagPositions = (fxFlags & eResetFxDagPositions);
  TXshColumn *column = m_column.getPointer();
  // The xsheet 'changes' if a new column is inserted. If it was already there,
  // no.
  bool xsheetChange = false;
  if (column && column->getXsheet() && column->getXsheet() != xsh)
    xsheetChange = true;
  // Insert a column at the specified index. If a column was stored, insert that
  // one.
  TPointD dagPos = TConst::nowhere;
  if (column) {
    if (column->getFx())
      dagPos = column->getFx()->getAttributes()->getDagNodePos();
    if (doClone) column = column->clone();
    xsh->insertColumn(index, column);
  } else
    xsh->insertColumn(index);  // Create a new one otherwise
  if (!resetFxDagPositions && dagPos != TConst::nowhere) {
    // Don't accept the default position (fx object)
    TXshColumn *restoredColumn = xsh->getColumn(index);
    restoredColumn->getFx()->getAttributes()->setDagNodePos(dagPos);
  }
  // Retrieve the newly inserted column stage object
  TStageObject *obj = xsh->getStageObject(TStageObjectId::ColumnId(index));
  assert(obj);
  obj->assignParams(m_params, doClone);  // Assign the stored params
  if (copyPosition) obj->setDagNodePos(m_dagPos);
  // Clone the associated curve if any
  if (xsheetChange && obj->getSpline()) {
    TStageObjectSpline *srcSpl = obj->getSpline();
    TStageObjectSpline *dstSpl = xsh->getStageObjectTree()->createSpline();
    dstSpl->addRef();
    dstSpl->setStroke(new TStroke(*srcSpl->getStroke()));
    obj->setSpline(dstSpl);
  }
  int gridType = xsh->getStageObjectTree()->getDagGridDimension();
  obj->setIsOpened(gridType ==
                   0);  // gridType is 0 if the node is opened, 1 if closed
                        // see StageSchematicScene::GridDimension
                        // TODO: Should be made PUBLIC!!
  xsh->updateFrameCount();
  return obj->getId();
}
References TStageObject::assignParams(), TStageObjectTree::createSpline(), TXsheet::getColumn(), TStageObject::getId(), TStageObject::getSpline(), TXsheet::getStageObject(), TXsheet::getStageObjectTree(), TStageObjectSpline::getStroke(), TXsheet::insertColumn(), TStageObjectDataElement::m_dagPos, TStageObjectDataElement::m_params, TStageObject::setDagNodePos(), TStageObject::setIsOpened(), TStageObject::setSpline(), TStageObjectSpline::setStroke(), and TXsheet::updateFrameCount().
storeColumn()
void TColumnDataElement::storeColumn (TXsheet * xsheet, int index, int fxFlags)
Stores the stage object and column data of the specified column index in the supplied xsheet. Specifically, the TXshColumnP associated with the desired column index is stored. Supported additional flags include performing a clone of the associated TXshColumnP rather than storing the original.
{
  if (index < 0) return;
  bool doClone             = (fxFlags & eDoClone);
  bool resetFxDagPositions = (fxFlags & eResetFxDagPositions);
  // Fetch the specified column (if none, return)
  TStageObject *obj = xsh->getStageObject(TStageObjectId::ColumnId(index));
  assert(obj);
  TXshColumn *column = xsh->getColumn(index);
  if (!column) return;
  TFx *fx = column->getFx();
  TPointD dagPos;
  if (fx) dagPos = fx->getAttributes()->getDagNodePos();
  if (doClone)
    column = column->clone();  // Zerary fxs clone the associated fx (drawn
                               // levels do not)
  if (fx && !resetFxDagPositions)
    column->getFx()->getAttributes()->setDagNodePos(dagPos);
  m_column = column;
  storeObject(obj->getId(), xsh);
}
References TXsheet::getColumn(), TStageObject::getId(), TXsheet::getStageObject(), and TStageObjectDataElement::storeObject().
Referenced by StageObjectsData::storeObjects().
Friends And Related Function Documentation
StageObjectsData
friend class StageObjectsData friend
The documentation for this class was generated from the following file:
E:/opentoonz/toonz/sources/toonzqt/stageobjectsdata.cpp