opentoonz: TFilePath Class Reference
TFilePath Class Reference
#include <tfilepath.h>
Public Member Functions
TFilePath (const char *path="")
TFilePath (const std::string &path)
TFilePath (const std::wstring &path)
TFilePath (const QString &path)
TFilePath (const TFilePath &fp)
TFilePath & operator= (const TFilePath &fp)
bool operator== (const TFilePath &fp) const
bool operator!= (const TFilePath &fp) const
bool operator< (const TFilePath &fp) const
const std::wstring getWideString () const
QString getQString () const
std::string getDots () const
std::string getDottedType () const
std::string getUndottedType () const
std::string getType () const
std::string getName () const
std::wstring getWideName () const
std::string getLevelName () const
std::wstring getLevelNameW () const
TFilePath getParentDir () const
TFrameId getFrame () const
bool isFfmpegType () const
bool isLevelName () const
bool isAbsolute () const
bool isRoot () const
bool isEmpty () const
TFilePath withType (const std::string &type) const
TFilePath withName (const std::string &name) const
TFilePath withName (const std::wstring &name) const
TFilePath withParentDir (const TFilePath &dir) const
TFilePath withoutParentDir () const
TFilePath withFrame (const TFrameId &frame, TFrameId::FrameFormat format=TFrameId::USE_CURRENT_FORMAT) const
TFilePath withFrame (int f) const
TFilePath withFrame (int f, char letter) const
TFilePath withFrame () const
TFilePath withNoFrame () const
TFilePath operator+ (const TFilePath &fp) const
TFilePath & operator+= (const TFilePath &fp)
TFilePath operator+ (const std::string &s) const
TFilePath & operator+= (const std::string &s)
TFilePath & operator+= (const std::wstring &s)
TFilePath operator+ (const std::wstring &s) const
bool isAncestorOf (const TFilePath &) const
TFilePath operator- (const TFilePath &fp) const
bool match (const TFilePath &fp) const
void split (std::wstring &head, TFilePath &tail) const
TFilePathInfo analyzePath () const
Static Public Member Functions
static void setUnderscoreFormatAllowed (bool state)
static bool setFilePathProperties (bool useStandard, bool acceptNonAlphaSuffix, int letterCountForSuffix)
static bool useStandard ()
static QString fidRegExpStr ()
Detailed Description
The class TFilePath defines a file path.Its constructor creates a string according to the platform and to certain rules.For more information see the constructor.
Constructor & Destructor Documentation
TFilePath() [1/5]
TFilePath::TFilePath (const char * path = "") explicit
This constructor creates a string removing redundances ('//', './',etc.) and final slashes, correcting (redressing) the "twisted" slashes. Note that if the current directory is ".", it becomes "". If the path is "<alpha>:" a slash will be added
{ setPath(::to_wstring(path)); }
Referenced by getParentDir(), withFrame(), withName(), withParentDir(), and withType().
TFilePath() [2/5]
TFilePath::TFilePath (const std::string & path) explicit
{ setPath(::to_wstring(path)); }
TFilePath() [3/5]
TFilePath::TFilePath (const std::wstring & path) explicit
{ setPath(path); }
TFilePath() [4/5]
TFilePath::TFilePath (const QString & path) explicit
{ setPath(path.toStdWString()); }
~TFilePath()
TFilePath::~TFilePath () inline
{}
TFilePath() [5/5]
TFilePath::TFilePath (const TFilePath & fp) inline
: m_path(fp.m_path) {}
Member Function Documentation
analyzePath()
TFilePath::TFilePathInfo TFilePath::analyzePath () const
{
  assert(!TFilePath::m_useStandard);
  TFilePath::TFilePathInfo info;
  int i            = getLastSlash(m_path);
  std::wstring str = m_path.substr(i + 1);
  if (i >= 0) info.parentDir = QString::fromStdWString(m_path.substr(0, i + 1));
  QString fileName = QString::fromStdWString(str);
  // Level Name : letters other than  \/:,;*?"<>|
  const QString levelNameRegExp("([^\\\\/:,;*?\"<>|]+)");
  // Sep Char : period or underscore
  const QString sepCharRegExp("([\\._])");
  // Frame Number and Suffix
  QString fIdRegExp = TFilePath::fidRegExpStr();
  // Extension：letters other than "._" or  \/:,;*?"<>|  or " "(space)
  const QString extensionRegExp("([^\\._ \\\\/:,;*?\"<>|]+)");
  // ignore frame numbers on non-sequential (i.e. movie) extension case :
  // hoge_0001.mp4
  // QRegExp rx_mf("^" + levelNameRegExp + "\\." + extensionRegExp + "$");
  // if (rx_mf.indexIn(levelName) != -1) {
  //  QString ext = rx_mf.cap(2);
  //  if (!checkForSeqNum(ext)) {
  //    info.levelName = rx_mf.cap(1);
  //    info.sepChar = QChar();
  //    info.fId = TFrameId(TFrameId::NO_FRAME, 0, 0); //NO_PADで初期化する
  //    info.extension = ext;
  //    return info;
  //  }
  //}
  // hogehoge.0001a.jpg
  // empty frame case : hogehoge..jpg
  QRegExp rx("^" + levelNameRegExp + sepCharRegExp + "(?:" + fIdRegExp + ")?" +
             "\\." + extensionRegExp + "$");
  if (rx.indexIn(fileName) != -1) {
    assert(rx.captureCount() == 5);
    info.levelName = rx.cap(1);
    info.sepChar   = rx.cap(2)[0];
    info.extension = rx.cap(5);
    // ignore frame numbers on non-sequential (i.e. movie) extension case :
    // hoge_0001.mp4
    if (!checkForSeqNum(info.extension)) {
      info.levelName = rx.cap(1) + rx.cap(2);
      if (!rx.cap(3).isEmpty()) info.levelName += rx.cap(3);
      if (!rx.cap(4).isEmpty()) info.levelName += rx.cap(4);
      info.sepChar = QChar();
      info.fId = TFrameId(TFrameId::NO_FRAME, 0, 0);  // initialize with NO_PAD
    } else {
      QString numberStr = rx.cap(3);
      if (numberStr.isEmpty())  // empty frame case : hogehoge..jpg
        info.fId =
            TFrameId(TFrameId::EMPTY_FRAME, 0, 4, info.sepChar.toLatin1());
      else {
        int number  = numberStr.toInt();
        int padding = 0;
        if (numberStr[0] == "0")  // with padding
          padding = numberStr.count();
        QString suffix;
        if (!rx.cap(4).isEmpty()) suffix = rx.cap(4);
        info.fId = TFrameId(number, suffix, padding, info.sepChar.toLatin1());
      }
    }
    return info;
  }
  // QRegExp rx_ef("^" + levelNameRegExp + sepCharRegExp + "\\." +
  // extensionRegExp + "$"); if (rx_ef.indexIn(levelName) != -1) {
  //  info.levelName = rx_ef.cap(1);
  //  info.sepChar = rx_ef.cap(2)[0];
  //  info.fId = TFrameId(TFrameId::EMPTY_FRAME, 0, 4, info.sepChar.toLatin1());
  //  info.extension = rx_ef.cap(3);
  //  return info;
  //}
  // no frame case : hogehoge.jpg
  // no level name case : .jpg
  QRegExp rx_nf("^(?:" + levelNameRegExp + ")?\\." + extensionRegExp + "$");
  if (rx_nf.indexIn(fileName) != -1) {
    if (!rx_nf.cap(1).isEmpty()) info.levelName = rx_nf.cap(1);
    info.sepChar = QChar();
    info.fId = TFrameId(TFrameId::NO_FRAME, 0, 0);  // initialize with NO_PAD
    info.extension = rx_nf.cap(2);
    return info;
  }
  // no periods
  info.levelName = fileName;
  info.sepChar   = QChar();
  info.fId = TFrameId(TFrameId::NO_FRAME, 0, 0);  // initialize with NO_PAD
  info.extension = QString();
  return info;
}
fidRegExpStr()
QString TFilePath::fidRegExpStr () static
{
  if (m_useStandard) return QString("(\\d+)([a-zA-Z]?)");
  QString suffixLetter = (m_acceptNonAlphabetSuffix)
                             ? "[^\\._ \\\\/:,;*?\"<>|0123456789]"
                             : "[a-zA-Z]";
  QString countLetter = (m_letterCountForSuffix == 0)
                            ? "{0,}"
                            : (QString("{0,%1}").arg(m_letterCountForSuffix));
  return QString("(\\d+)(%1%2)").arg(suffixLetter).arg(countLetter);
  // const QString fIdRegExp("(\\d+)([a-zA-Z]?)");
}
getDots()
string TFilePath::getDots () const
Returns: a. "" if there is no filename extension b. "." if there is a filename extension but no frame c.".." if there are both filename extension and frame
{
  if (!TFilePath::m_useStandard) {
    TFilePathInfo info = analyzePath();
    if (info.extension.isEmpty()) return "";
    if (info.sepChar.isNull()) return ".";
    // return ".." regardless of sepChar type (either "_" or ".")
    return "..";
  }
  //-----
  QString type = QString::fromStdString(getType()).toLower();
  if (isFfmpegType()) return ".";
  int i            = getLastSlash(m_path);
  std::wstring str = m_path.substr(i + 1);
  // potrei anche avere a.b.c.d dove d e' l'estensione
  i = str.rfind(L".");
  if (i == (int)std::wstring::npos || str == L"..") return "";
  int j = str.substr(0, i).rfind(L".");
  if (j == (int)std::wstring::npos && m_underscoreFormatAllowed)
    j = str.substr(0, i).rfind(L"_");
  if (j != (int)std::wstring::npos)
    return (j == i - 1 || (checkForSeqNum(type) && isNumbers(str, j, i))) ? ".."
                                                                          : ".";
  else
    return ".";
}
References getType().
Referenced by ToonzScene::getImportedLevelPath(), TLevelWriter::renumberFids(), FlipBook::setLevel(), and withFrame().
getDottedType()
string TFilePath::getDottedType () const
Returns the filename extension, including leading period (.). Returns "" if there is no filename extension.
{
  if (!TFilePath::m_useStandard) {
    QString ext = analyzePath().extension;
    if (ext.isEmpty()) return "";
    return "." + ext.toLower().toStdString();
  }
  int i            = getLastSlash(m_path);
  std::wstring str = m_path.substr(i + 1);
  i                = str.rfind(L".");
  if (i == (int)std::wstring::npos) return "";
  return toLower(::to_string(str.substr(i)));
}
Referenced by StudioPaletteTreeViewer::dropEvent(), TSceneProperties::onInitialize(), and StudioPaletteTreeViewer::onItemChanged().
getFrame()
TFrameId TFilePath::getFrame () const
{
  if (!TFilePath::m_useStandard) {
    return analyzePath().fId;
  }
  //-----
  int i            = getLastSlash(m_path);  // cerco l'ultimo slash
  std::wstring str = m_path.substr(i + 1);  // str e' il path senza parentdir
  QString type     = QString::fromStdString(getType()).toLower();
  i                = str.rfind(L'.');
  if (i == (int)std::wstring::npos || str == L"." || str == L"..")
    return TFrameId(TFrameId::NO_FRAME);
  int j;
  j = str.substr(0, i).rfind(L'.');
  if (j == (int)std::wstring::npos && m_underscoreFormatAllowed)
    j = str.substr(0, i).rfind(L'_');
  if (j == (int)std::wstring::npos) return TFrameId(TFrameId::NO_FRAME);
  if (i == j + 1) return TFrameId(TFrameId::EMPTY_FRAME);
  // 間が数字でない場合（ファイル名にまぎれた"_" や "."がある場合）を除外する
  if (!checkForSeqNum(type) || !isNumbers(str, j, i))
    return TFrameId(TFrameId::NO_FRAME);
  int k, number = 0, digits = 0;
  for (k = j + 1; k < i && iswdigit(str[k]); k++) {
    digits++;
    number = number * 10 + str[k] - L'0';
  }
  char letter = '\0';
  if (iswalpha(str[k])) letter = str[k++] + ('a' - L'a');
  //  if (number == 0 || k < i)  // || letter!='\0')
  //    throw TMalformedFrameException(
  //        *this,
  //        str + L": " + QObject::tr("Malformed frame name").toStdWString());
  int padding = 0;
  if (str[j + 1] == '0') padding = digits;
  return TFrameId(number, letter, padding, str[j]);
}
getLevelName()
string TFilePath::getLevelName () const
Returns the filename (with extension, escluding in case the frame number). ex.: TFilePath("/pippo/pluto.0001.gif").getLevelName() == "pluto..gif"
{
  return ::to_string(getLevelNameW());
}
Referenced by ThumbnailViewer::drawItem().
getLevelNameW()
std::wstring TFilePath::getLevelNameW () const
{
  if (!TFilePath::m_useStandard) {
    TFilePathInfo info = analyzePath();
    if (info.extension.isEmpty()) return info.levelName.toStdWString();
    QString name = info.levelName;
    if (!info.sepChar.isNull()) name += info.sepChar;
    name += "." + info.extension;
    return name.toStdWString();
  }
  //-----
  int i            = getLastSlash(m_path);  // cerco l'ultimo slash
  std::wstring str = m_path.substr(i + 1);  // str e' m_path senza directory
  QString type     = QString::fromStdString(getType()).toLower();
  if (isFfmpegType()) return str;
  int j = str.rfind(L".");                       // str[j..] = ".type"
  if (j == (int)std::wstring::npos) return str;  // no frame; no type
  i = str.substr(0, j).rfind(L'.');
  if (i == (int)std::wstring::npos && m_underscoreFormatAllowed)
    i = str.substr(0, j).rfind(L'_');
  if (j == i || j - i == 1)  // prova.tif o prova..tif
    return str;
  if (!checkForSeqNum(type) || !isNumbers(str, i, j) ||
      i == (int)std::wstring::npos)
    return str;
  // prova.0001.tif
  return str.erase(i + 1, j - i - 1);
}
getName()
string TFilePath::getName () const
Returns the base filename (no extension, no dots, no slash)
{
  return ::to_string(getWideName());
}
Referenced by TXshSimpleLevel::copyFiles(), StudioPaletteTreeViewer::createItem(), StudioPaletteTreeViewer::createRootItem(), ToonzScene::decodeFilePath(), StudioPaletteTreeViewer::dropEvent(), ExportLevelPopup::execute(), SaveSceneAsPopup::execute(), SaveLevelAsPopup::execute(), SavePaletteAsPopup::execute(), IoCmd::exportLevel(), TProject::getFolderIndexFromPath(), TXshSimpleLevel::getHookPath(), TIStream::getRepositoryPath(), TOStream::getRepositoryPath(), ToonzScene::getSavePath(), IoCmd::loadResources(), OutputSettingsPopup::onAddPresetButtonPressed(), StudioPaletteTreeViewer::onItemChanged(), OutputSettingsPopup::onNameChanged(), TLevelWriterTzl::optimize(), TXshSimpleLevel::removeFiles(), TXshSimpleLevel::renameFiles(), SceneLevel::save(), and OutputSettingsPopup::updateField().
getParentDir()
TFilePath TFilePath::getParentDir () const
Returns the parent directory escluding the eventual final slash.
{
  int i = getLastSlash(m_path);  // cerco l'ultimo slash
  if (i < 0) {
    if (m_path.length() >= 2 &&
        (('a' <= m_path[0] && m_path[0] <= 'z') ||
         ('A' <= m_path[0] && m_path[0] <= 'Z')) &&
        m_path[1] == ':')
      return TFilePath(m_path.substr(0, 2));
    else
      return TFilePath("");
  } else if (i == 0)
    return TFilePath("/");
  else
    return TFilePath(m_path.substr(0, i));
}
References TFilePath().
Referenced by ToonzScene::codeSavePath(), ToonzScene::convertLevelIfNeeded(), TXshSimpleLevel::copyFiles(), StudioPaletteCmd::createPalette(), ToonzScene::decodeFilePath(), ToonzScene::decodeSavePath(), StudioPaletteTreeViewer::dropEvent(), SaveLevelAsPopup::execute(), ReplaceLevelPopup::execute(), SavePaletteAsPopup::execute(), IoCmd::exportLevel(), TProjectManager::getCurrentProjectPath(), TXshSimpleLevel::getExistingHookFile(), TProject::getFolderIndexFromPath(), TXshSimpleLevel::getHookFiles(), ToonzScene::getIconPath(), ToonzScene::getImportedLevelPath(), TProject::getProjectFolder(), TIStream::getRepositoryPath(), TOStream::getRepositoryPath(), TProjectManager::getSandboxProjectFolder(), TProject::load(), ShaderInterface::ShaderData::loadData(), ShaderInterface::loadData(), IoCmd::loadResources(), TProjectManager::loadSceneProject(), StudioPaletteTreeViewer::onItemChanged(), PalettesScanPopup::onPlt(), TProjectManager::projectPathToProjectName(), TXshSimpleLevel::removeFiles(), TXshSimpleLevel::renameFiles(), TLevelWriter::renumberFids(), SceneLevel::save(), TXshSimpleLevel::save(), ToonzScene::save(), TProject::save(), ShaderInterface::ShaderData::saveData(), ShaderInterface::saveData(), and OutputSettingsPopup::updateField().
getQString()
QString TFilePath::getQString () const
{
  return QString::fromStdWString(getWideString());
}
getType()
std::string TFilePath::getType () const inline
It is equal to getUndottedType(): Returns the filename extension, excluding leading period (.). Returns "" if there is no filename extension.
{
    return getUndottedType();
  }  // ritorna l'estensione SENZA PUNTO
Referenced by ImageLoader::build(), TXshSimpleLevel::copyFiles(), PaletteViewer::dragEnterEvent(), StudioPaletteTreeViewer::dragEnterEvent(), ColorModelViewer::dragEnterEvent(), StudioPaletteTreeViewer::dragMoveEvent(), ThumbnailViewer::drawItem(), PaletteViewer::dropEvent(), StudioPaletteTreeViewer::dropEvent(), LoadTaskListPopup::execute(), LoadTaskPopup::execute(), SaveCurvePopup::execute(), LoadCurvePopup::execute(), ExportCurvePopup::execute(), GenericSaveFilePopup::execute(), LoadScenePopup::execute(), LoadSubScenePopup::execute(), SaveLevelAsPopup::execute(), SavePaletteAsPopup::execute(), IoCmd::exportLevel(), getDots(), TXshSimpleLevel::getFiles(), ToonzScene::getImportedLevelPath(), TProject::isAProjectPath(), VectorizerPopup::isLevelToConvert(), TXshSimpleLevel::load(), TXshSimpleLevel::loadData(), IoCmd::loadResources(), TXshSimpleLevel::makeTlv(), RenderCommand::multimediaRender(), OutputSettingsPopup::onFormatChanged(), StudioPaletteTreeViewer::onItemSelectionChanged(), OutputSettingsPopup::openSettingsPopup(), TXshSimpleLevel::removeFiles(), TXshSimpleLevel::renameFiles(), TLevelWriter::renumberFids(), FileIconRenderer::run(), SceneLevel::save(), TXshSimpleLevel::save(), SceneLevel::SceneLevel(), TXshSimpleLevel::setEditableRange(), FlipBook::setLevel(), StudioPaletteTreeViewer::startDragDrop(), PalettesScanPopup::step(), OutputSettingsPopup::updateField(), withFrame(), and withName().
getUndottedType()
string TFilePath::getUndottedType () const
Returns the filename extension, escluding leading period (.). Returns "" if there is no filename extension.
{
  if (!TFilePath::m_useStandard) {
    QString ext = analyzePath().extension;
    if (ext.isEmpty())
      return "";
    else
      return ext.toLower().toStdString();
  }
  //-----
  size_t i         = getLastSlash(m_path);
  std::wstring str = m_path.substr(i + 1);
  i                = str.rfind(L".");
  if (i == std::wstring::npos || i == str.length() - 1) return "";
  return toLower(::to_string(str.substr(i + 1)));
}
Referenced by TSceneProperties::loadData().
getWideName()
std::wstring TFilePath::getWideName () const
{
  if (!TFilePath::m_useStandard) {
    return analyzePath().levelName.toStdWString();
  }
  //-----
  QString type     = QString::fromStdString(getType()).toLower();
  int i            = getLastSlash(m_path);  // cerco l'ultimo slash
  std::wstring str = m_path.substr(i + 1);
  i                = str.rfind(L".");
  if (i == (int)std::wstring::npos) return str;
  int j = str.substr(0, i).rfind(L".");
  if (j != (int)std::wstring::npos) {
    if (checkForSeqNum(type) && isNumbers(str, j, i)) i = j;
  } else if (m_underscoreFormatAllowed) {
    j = str.substr(0, i).rfind(L"_");
    if (j != (int)std::wstring::npos && checkForSeqNum(type) &&
        isNumbers(str, j, i))
      i = j;
  }
  return str.substr(0, i);
}
getWideString()
const std::wstring TFilePath::getWideString () const
{
  return m_path;
  /*
std::wstring s;
int n = m_path.size();
for(int i=0;i<n; i++)
{
char c = m_path[i];
if(c!='&') s.append(1, (unsigned short)c);
else
 {
  i++;
  if(m_path[i] == '#')
    {
     unsigned short w = 0;
     i++;
     while(i<n)
       {
        c = m_path[i];
        if('0'<=c && c<='9')
          w = w*10 + c - '0';
        else if('a' <=c && c<='f')
          w = w*10 + c - 'a' + 10;
        else if('A' <=c && c<='F')
          w = w*10 + c - 'A' + 10;
        else
          break;
        i++;
       }
     s.append(1, w);
    }
 }
}
return s;
*/
}
isAbsolute()
bool TFilePath::isAbsolute () const
{
  return ((m_path.length() >= 1 && m_path[0] == slash) ||
          (m_path.length() >= 2 && iswalpha(m_path[0]) && m_path[1] == ':'));
}
isAncestorOf()
bool TFilePath::isAncestorOf (const TFilePath & possibleDescendent) const
{
  size_t len = m_path.length();
  if (len == 0) {
    // il punto e' antenato di tutti i path non assoluti
    return !possibleDescendent.isAbsolute();
  }
  // un path e' antenato di se stesso
  if (m_path == possibleDescendent.m_path) return true;
  int possibleDescendentLen = possibleDescendent.m_path.length();
  // altrimenti l'antenato deve essere piu' corto
  if ((int)len >= possibleDescendentLen) return false;
  // e deve coincidere con la prima parte del discendente
  if (toLower(m_path) != toLower(possibleDescendent.m_path.substr(0, len)))
    return false;
  // se l'antenato non finisce con slash ci deve essere uno slash nel
  // discendente, subito dopo
  if (m_path[len - 1] != wslash && possibleDescendent.m_path[len] != wslash)
    return false;
  return true;
}
isEmpty()
bool TFilePath::isEmpty () const inline
{ return m_path == L""; }
isFfmpegType()
bool TFilePath::isFfmpegType () const
{
  QString type = QString::fromStdString(getType()).toLower();
  if (type == "gif" || type == "mp4" || type == "webm")
    return true;
  else
    return false;
}
isLevelName()
bool TFilePath::isLevelName () const
{
  if (!TFilePath::m_useStandard) {
    return analyzePath().fId.getNumber() == TFrameId::EMPTY_FRAME;
  }
  //-----
  QString type = QString::fromStdString(getType()).toLower();
  if (isFfmpegType() || !checkForSeqNum(type)) return false;
  try {
    return getFrame() == TFrameId(TFrameId::EMPTY_FRAME);
  }
  catch (...) {
    return false;
  }
}
isRoot()
bool TFilePath::isRoot () const
{
  return ((m_path.length() == 1 && m_path[0] == slash) ||
          (m_path.length() == 3 && iswalpha(m_path[0]) && m_path[1] == ':' &&
           m_path[2] == slash) ||
          ((m_path.length() > 2 && m_path[0] == slash && m_path[1] == slash) &&
           (std::string::npos == m_path.find(slash, 2) ||
            m_path.find(slash, 2) == (m_path.size() - 1))));
}
match()
bool TFilePath::match (const TFilePath & fp) const
{
  if (!TFilePath::m_useStandard) {
    if (getParentDir() != fp.getParentDir()) return false;
    TFilePathInfo info     = analyzePath();
    TFilePathInfo info_ext = fp.analyzePath();
    return (info.levelName == info_ext.levelName && info.fId == info_ext.fId &&
            info.extension == info_ext.extension);
  }
  return getParentDir() == fp.getParentDir() && getName() == fp.getName() &&
         getFrame() == fp.getFrame() && getType() == fp.getType();
}
operator!=()
bool TFilePath::operator!= (const TFilePath & fp) const inline
{
    return !(m_path == fp.m_path);
  }
operator+() [1/3]
TFilePath TFilePath::operator+ (const std::string & s) const inline
{
    return operator+(TFilePath(s));
  }
operator+() [2/3]
TFilePath TFilePath::operator+ (const std::wstring & s) const inline
{
    TFilePath res(*this);
    return res += s;
  }
operator+() [3/3]
TFilePath TFilePath::operator+ (const TFilePath & fp) const
{
  TFilePath ret(*this);
  ret += fp;
  return ret;
}
operator+=() [1/3]
TFilePath & TFilePath::operator+= (const std::string & s) inline
{
    return operator+=(TFilePath(s));
  }
operator+=() [2/3]
TFilePath & TFilePath::operator+= (const std::wstring & s)
{
  if (s.empty()) return *this;
  // if(m_path.length()!=1 || m_path[0] != slash)
  //  m_path += slash;
  if (m_path.length() > 0 && !isSlash(m_path[m_path.length() - 1]))
    m_path.append(1, wslash);
  m_path += s;
  return *this;
}
operator+=() [3/3]
TFilePath & TFilePath::operator+= (const TFilePath & fp)
{
  assert(!fp.isAbsolute());
  if (fp.isEmpty())
    return *this;
  else if (isEmpty()) {
    *this = fp;
    return *this;
  } else if (m_path.length() != 1 || m_path[0] != slash) {
    assert(!m_path.empty());
    if (!isSlash(m_path[m_path.length() - 1])) m_path.append(1, wslash);
    m_path += fp.m_path;
    return *this;
  } else {
    *this = TFilePath(m_path + fp.m_path);
    return *this;
  }
}
operator-()
TFilePath TFilePath::operator- (const TFilePath & fp) const
{
  if (toLower(m_path) == toLower(fp.m_path)) return TFilePath("");
  if (!fp.isAncestorOf(*this)) return *this;
  int len = fp.m_path.length();
  if (len == 0 || fp.m_path[len - 1] != wslash) len++;
  return TFilePath(m_path.substr(len));
}
operator<()
bool TFilePath::operator< (const TFilePath & fp) const
{
  std::wstring iName = m_path;
  std::wstring jName = fp.m_path;
  int i1 = 0, j1 = 0;
  int i2 = m_path.find(L"\\");
  int j2 = fp.m_path.find(L"\\");
  if (i2 == j2 && j2 == -1)
#ifdef _WIN32
    return _wcsicmp(m_path.c_str(), fp.m_path.c_str()) < 0;
#else
    return m_path < fp.m_path;
#endif
  if (!i2) {
    ++i1;
    i2 = m_path.find(L"\\", i1);
  }
  if (!j2) {
    ++j1;
    j2 = fp.m_path.find(L"\\", j1);
  }
  while (i2 != -1 || j2 != -1) {
    iName = (i2 != -1) ? m_path.substr(i1, i2 - i1) : m_path;
    jName = (j2 != -1) ? fp.m_path.substr(j1, j2 - j1) : fp.m_path;
// se le due parti di path, conpresi tra slash sono uguali
// itero il processo di confronto altrimenti ritorno
#ifdef _WIN32
    char differ;
    differ = _wcsicmp(iName.c_str(), jName.c_str());
    if (differ != 0) return differ < 0 ? true : false;
#else
    if (TFilePath(iName) != TFilePath(jName))
      return TFilePath(iName) < TFilePath(jName);
#endif
    i1 = (i2 != -1) ? i2 + 1 : m_path.size();
    j1 = (j2 != -1) ? j2 + 1 : fp.m_path.size();
    i2 = m_path.find(L"\\", i1);
    j2 = fp.m_path.find(L"\\", j1);
  }
  iName = m_path.substr(i1, m_path.size() - i1);
  jName = fp.m_path.substr(j1, fp.m_path.size() - j1);
#ifdef _WIN32
  return _wcsicmp(iName.c_str(), jName.c_str()) < 0;
#else
  return TFilePath(iName) < TFilePath(jName);
#endif
}
operator=()
TFilePath & TFilePath::operator= (const TFilePath & fp) inline
{
    m_path = fp.m_path;
    return *this;
  }
operator==()
bool TFilePath::operator== (const TFilePath & fp) const
{
#ifdef _WIN32
  return _wcsicmp(m_path.c_str(), fp.m_path.c_str()) == 0;
#else
  return m_path == fp.m_path;
#endif
}
setFilePathProperties()
static bool TFilePath::setFilePathProperties (bool useStandard, bool acceptNonAlphaSuffix, int letterCountForSuffix) inline static
{
    if (m_useStandard == useStandard &&
        m_acceptNonAlphabetSuffix == acceptNonAlphaSuffix &&
        m_letterCountForSuffix == letterCountForSuffix)
      return false;
    m_useStandard             = useStandard;
    m_acceptNonAlphabetSuffix = acceptNonAlphaSuffix;
    m_letterCountForSuffix    = letterCountForSuffix;
    return true;
  }
setUnderscoreFormatAllowed()
static void TFilePath::setUnderscoreFormatAllowed (bool state) inline static
this static method allows correct reading of levels in the form pippo_0001.tif (represented always as pippo..tif)
{
    m_underscoreFormatAllowed = state;
  }
Referenced by ConvertPopup::apply().
split()
void TFilePath::split (std::wstring & head, TFilePath & tail) const
{
  TFilePath ancestor = getParentDir();
  if (ancestor == TFilePath()) {
    head = getWideString();
    tail = TFilePath();
    return;
  }
  for (;;) {
    if (ancestor.isRoot()) break;
    TFilePath p = ancestor.getParentDir();
    if (p == TFilePath()) break;
    ancestor = p;
  }
  head = ancestor.getWideString();
  tail = *this - ancestor;
}
useStandard()
static bool TFilePath::useStandard () inline static
{ return m_useStandard; }
withFrame() [1/4]
TFilePath TFilePath::withFrame () const inline
{
    return withFrame(TFrameId(TFrameId::EMPTY_FRAME));
  }
withFrame() [2/4]
TFilePath TFilePath::withFrame (const TFrameId & frame, TFrameId::FrameFormat format = TFrameId::USE_CURRENT_FORMAT) const
Return a TFilePath with frame "frame".
{
  if (!TFilePath::m_useStandard) {
    TFilePathInfo info = analyzePath();
    // Override format input because it may be wrong.
    if (checkForSeqNum(info.extension)) format = frame.getCurrentFormat();
    // override format if the original fid is available
    else if (info.fId.getNumber() != TFrameId::NO_FRAME)
      format = info.fId.getCurrentFormat();
    if (info.extension.isEmpty()) {
      if (frame.isEmptyFrame() || frame.isNoFrame()) return *this;
      return TFilePath(m_path + L"." + ::to_wstring(frame.expand(format)));
    }
    if (frame.isNoFrame()) {
      return TFilePath(info.parentDir + info.levelName + "." + info.extension);
    }
    QString sepChar = (info.sepChar.isNull()) ? "." : QString(info.sepChar);
    return TFilePath(info.parentDir + info.levelName + sepChar +
                     QString::fromStdString(frame.expand(format)) + "." +
                     info.extension);
  }
  //-----------------
  const std::wstring dot = L".", dotDot = L"..";
  int i            = getLastSlash(m_path);  // cerco l'ultimo slash
  std::wstring str = m_path.substr(i + 1);  // str e' il path senza parentdir
  QString type     = QString::fromStdString(getType()).toLower();
  assert(str != dot && str != dotDot);
  int j          = str.rfind(L'.');
  const char *ch = ".";
  // Override format input because it may be wrong.
  if (!isFfmpegType() && checkForSeqNum(type))
    format = frame.getCurrentFormat();
  if (m_underscoreFormatAllowed && (format == TFrameId::UNDERSCORE_FOUR_ZEROS ||
                                    format == TFrameId::UNDERSCORE_NO_PAD ||
                                    format == TFrameId::UNDERSCORE_CUSTOM_PAD))
    ch = "_";
  // no extension case
  if (j == (int)std::wstring::npos) {
    if (frame.isEmptyFrame() || frame.isNoFrame())
      return *this;
    else
      return TFilePath(m_path + ::to_wstring(ch + frame.expand(format)));
  }
  int k = str.substr(0, j).rfind(L'.');
  bool hasValidFrameNum = false;
  if (!isFfmpegType() && checkForSeqNum(type) && isNumbers(str, k, j))
    hasValidFrameNum = true;
  std::string frameString;
  if (frame.isNoFrame())
    frameString = "";
  else if (!frame.isEmptyFrame() && getDots() != "." && !hasValidFrameNum) {
    if (k != (int)std::wstring::npos) {
      std::wstring wstr = str.substr(k, j - k);
      std::string str2(wstr.begin(), wstr.end());
      frameString = str2;
    } else
      frameString = "";
  } else
    frameString = ch + frame.expand(format);
  if (k != (int)std::wstring::npos)
    return TFilePath(m_path.substr(0, k + i + 1) + ::to_wstring(frameString) +
                     str.substr(j));
  else if (m_underscoreFormatAllowed) {
    k = str.substr(0, j).rfind(L'_');
    if (k != (int)std::wstring::npos &&
        (k == j - 1 ||
         (checkForSeqNum(type) &&
          isNumbers(str, k,
                    j))))  //-- "_." の並びか、"_[数字]."の並びのとき --
      return TFilePath(m_path.substr(0, k + i + 1) +
                       ((frame.isNoFrame())
                            ? L""
                            : ::to_wstring("_" + frame.expand(format))) +
                       str.substr(j));
  }
  return TFilePath(m_path.substr(0, j + i + 1) + ::to_wstring(frameString) +
                   str.substr(j));
}
References getDots(), getType(), TFilePath(), and withFrame().
Referenced by ExportLevelPopup::execute(), IoCmd::exportLevel(), ToonzScene::getImportedLevelPath(), TImageReaderMesh::load(), ColorModelViewer::loadCurrentFrame(), Previewer::onImageChange(), FlipBook::setLevel(), and withFrame().
withFrame() [3/4]
TFilePath TFilePath::withFrame (int f) const inline
Return a TFilePath with a frame identified by an integer number "f".
{ return withFrame(TFrameId(f)); }
References withFrame().
Referenced by withFrame().
withFrame() [4/4]
TFilePath TFilePath::withFrame (int f, char letter) const inline
Return a TFilePath with a frame identified by an integer and by a character
{
    return withFrame(TFrameId(f, letter));
  }
withName() [1/2]
TFilePath TFilePath::withName (const std::string & name) const
Return a TFilePath with filename "name".
{
  return withName(::to_wstring(name));
}
References withName().
Referenced by ToonzScene::decodeFilePath(), ExportLevelPopup::execute(), TXshSimpleLevel::getHookPath(), OutputSettingsPopup::onNameChanged(), TXshSimpleLevel::save(), TXshSimpleLevel::setEditableRange(), Vectorizer::setLevel(), ToonzScene::setSceneName(), and withName().
withName() [2/2]
TFilePath TFilePath::withName (const std::wstring & name) const
Return a TFilePath with filename "name". Unicode
{
  if (!TFilePath::m_useStandard) {
    TFilePathInfo info = analyzePath();
    QString ret = info.parentDir + QString::fromStdWString(name);
    if (info.fId.getNumber() != TFrameId::NO_FRAME) {
      QString sepChar = (info.sepChar.isNull()) ? "." : QString(info.sepChar);
      ret += sepChar + QString::fromStdString(
                           info.fId.expand(info.fId.getCurrentFormat()));
    }
    if (!info.extension.isEmpty()) ret += "." + info.extension;
    return TFilePath(ret);
  }
  int i            = getLastSlash(m_path);  // cerco l'ultimo slash
  std::wstring str = m_path.substr(i + 1);  // str e' il path senza parentdir
  QString type     = QString::fromStdString(getType()).toLower();
  int j;
  j = str.rfind(L'.');
  if (j == (int)std::wstring::npos) {
    if (m_underscoreFormatAllowed) {
      j = str.rfind(L'_');
      if (j != (int)std::wstring::npos)
        return TFilePath(m_path.substr(0, i + 1) + name + str.substr(j));
    }
    return TFilePath(m_path.substr(0, i + 1) + name);
  }
  int k;
  k = str.substr(0, j).rfind(L".");
  if (k == (int)std::wstring::npos && m_underscoreFormatAllowed)
    k = str.substr(0, j).rfind(L"_");
  if (k == (int)(std::wstring::npos))
    k = j;
  else if (k != j - 1 && (!checkForSeqNum(type) || !isNumbers(str, k, j)))
    k = j;
  return TFilePath(m_path.substr(0, i + 1) + name + str.substr(k));
}
References getType(), and TFilePath().
withNoFrame()
TFilePath TFilePath::withNoFrame () const inline
{
    return withFrame(TFrameId(TFrameId::NO_FRAME));
  }  // pippo.tif
withoutParentDir()
TFilePath TFilePath::withoutParentDir () const inline
Return a TFilePath without parent directory
{ return withParentDir(TFilePath()); }
Referenced by ToonzScene::codeSavePath(), ColorModelViewer::loadCurrentFrame(), TProjectManager::projectPathToProjectName(), and FlipBook::setLevel().
withParentDir()
TFilePath TFilePath::withParentDir (const TFilePath & dir) const
Return a TFilePath with parent directory "dir".
{
  int i = getLastSlash(m_path);  // cerco l'ultimo slash
  return dir + TFilePath(m_path.substr(i + 1));
}
References TFilePath().
Referenced by ReplaceParentDirectoryPopup::execute(), ToonzScene::getImportedLevelPath(), IoCmd::loadResources(), and OutputSettingsPopup::onPathChanged().
withType()
TFilePath TFilePath::withType (const std::string & type) const
Return a TFilePath with extension type. type is a string that indicate the filename extension(ex:. bmp or .bmp)
{
  assert(type.length() < 2 || type.substr(0, 2) != "..");
  int i            = getLastSlash(m_path);  // cerco l'ultimo slash
  std::wstring str = m_path.substr(i + 1);  // str e' il path senza parentdir
  int j            = str.rfind(L'.');
  if (j == (int)std::wstring::npos || str == L"..")
  // il path originale non ha tipo
  {
    if (type == "")
      return *this;
    else if (type[0] == '.')
      return TFilePath(m_path + ::to_wstring(type));
    else
      return TFilePath(m_path + ::to_wstring("." + type));
  } else
  // il path originale ha gia' il tipo
  {
    if (type == "")
      return TFilePath(m_path.substr(0, i + j + 1));
    else if (type[0] == '.')
      return TFilePath(m_path.substr(0, i + j + 1) + ::to_wstring(type));
    else
      return TFilePath(m_path.substr(0, i + j + 2) + ::to_wstring(type));
  }
}
References TFilePath().
Referenced by LevelUpdater::close(), ToonzScene::convertLevelIfNeeded(), ToonzScene::decodeFilePath(), SaveTaskListPopup::execute(), SaveCurvePopup::execute(), LoadCurvePopup::execute(), ExportCurvePopup::execute(), ExportLevelPopup::execute(), SaveLevelAsPopup::execute(), IoCmd::exportLevel(), CleanupSettingsModel::getClnPath(), ToonzScene::getDefaultLevelPath(), TXshSimpleLevel::getFiles(), ToonzScene::getSavePath(), TSceneProperties::loadData(), OutputSettingsPopup::onFormatChanged(), TXshSimpleLevel::removeFiles(), TXshSimpleLevel::renameFiles(), SceneLevel::save(), TXshSimpleLevel::save(), TXshSimpleLevel::setEditableRange(), and Vectorizer::setLevel().
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/tfilepath.h
E:/opentoonz/toonz/sources/common/tsystem/tfilepath.cpp
E:/opentoonz/toonz/sources/toonzfarm/tnzcore_stuff/tfilepath.cpp