opentoonz: TRasterImage Class Reference
TRasterImage Class Reference final
An image containing a raster.
#include <trasterimage.h>
Public Member Functions
TRasterImage (const TRasterP &raster)
TImage::Type getType () const override
Return the image type.
std::string getName () const
Return the name of the image.
void setName (std::string name)
Set the name of the image.
void getDpi (double &dpix, double &dpiy) const
Get the dpi image.
void setDpi (double dpix, double dpiy)
Set the dpi image.
int getSubsampling () const
void setSubsampling (int s)
TRect getSavebox () const
Return the save box of the image.
void setSavebox (const TRect &rect)
Set the save box of the image.
TRectD getBBox () const override
Return the bbox of the image.
TPoint getOffset () const
Return raster image offset m_offset.
void setOffset (const TPoint &offset)
Set raster image offset m_offset.
TImage * cloneImage () const override
Return raster hPos m_hPos.
const TRasterP & getRaster () const
Return TRasterP.
TRasterP & getRaster ()
Return TRasterP.
TRasterP raster () const override
void setRaster (const TRasterP &raster)
Set the TRasterP raster.
const TRasterP & getIconRaster () const
Return a TRasterP contained the icon of the image m_iconRaster.
TRasterP & getIconRaster ()
Return a TRasterP contained the icon of the image m_iconRaster.
void setIconRaster (const TRasterP &raster)
Set a TRasterP contained the icon of the image m_iconRaster.
bool isEmpty () const
Return true if the raster is empty.
bool isScanBW () const
Return true if the raster comes from BW Scan.
void setScanBWFlag (bool isScanBW)
bool isOpaque () const
Return true if the raster is opaque.
void setOpaqueFlag (bool isOpaque)
void makeIcon (const TRaster32P &raster)
Make the icon of the raster.
Public Member Functions inherited from TImage
TImage ()
virtual Type getType () const =0
virtual TRectD getBBox () const =0
virtual TImage * cloneImage () const =0
virtual TRasterP raster () const
TPalette * getPalette () const
virtual void setPalette (TPalette *palette)
Public Member Functions inherited from TSmartObject
TSmartObject (ClassCode classCode)
void addRef ()
void release ()
TINT32 getRefCount () const
Additional Inherited Members
Public Types inherited from TImage
enum Type {
NONE = 0 , RASTER = 1 , VECTOR = 2 , TOONZ_RASTER = 3 ,
MESH = 4
}
Public Types inherited from TSmartObject
typedef short ClassCode
Static Public Member Functions inherited from TSmartObject
static TINT32 getInstanceCount (ClassCode code)
Detailed Description
An image containing a raster.
Some examples:
Constructor & Destructor Documentation
TRasterImage() [1/2]
TRasterImage::TRasterImage ()
    : m_mainRaster()
    , m_patchRaster()
    , m_iconRaster()
    , m_dpix(0)
    , m_dpiy(0)
    , m_name("")
    , m_savebox()
    //, m_hPos(0.0)
    , m_isOpaque(false)
    , m_isScanBW(false)
    , m_offset(0, 0)
    , m_subsampling(1) {}
TRasterImage() [2/2]
TRasterImage::TRasterImage (const TRasterP & raster)
    : m_mainRaster(ras)
    , m_patchRaster()
    , m_iconRaster()
    , m_dpix(0)
    , m_dpiy(0)
    , m_name("")
    , m_savebox(0, 0, ras->getLx() - 1, ras->getLy() - 1)
    //, m_hPos(0.0)
    , m_isOpaque(false)
    , m_isScanBW(false)
    , m_offset(0, 0)
    , m_subsampling(1) {}
~TRasterImage()
TRasterImage::~TRasterImage ()
{}
Member Function Documentation
cloneImage()
TImage * TRasterImage::cloneImage () const override virtual
Return raster hPos m_hPos.
Set raster hPos m_hPos Return a clone of image
Implements TImage.
{ return new TRasterImage(*this); }
getBBox()
TRectD TRasterImage::getBBox () const inline override virtual
Return the bbox of the image.
Implements TImage.
{ return convert(m_savebox); }
getDpi()
void TRasterImage::getDpi (double & dpix, double & dpiy) const inline
Get the dpi image.
{
    dpix = m_dpix;
    dpiy = m_dpiy;
  }
getIconRaster() [1/2]
TRasterP & TRasterImage::getIconRaster () inline
Return a TRasterP contained the icon of the image m_iconRaster.
{ return m_iconRaster; }
getIconRaster() [2/2]
const TRasterP & TRasterImage::getIconRaster () const inline
Return a TRasterP contained the icon of the image m_iconRaster.
{ return m_iconRaster; }
getName()
std::string TRasterImage::getName () const inline
Return the name of the image.
{ return m_name; }
getOffset()
TPoint TRasterImage::getOffset () const inline
Return raster image offset m_offset.
{ return m_offset; }
Referenced by Stage::RasterPainter::onRasterImage().
getRaster() [1/2]
TRasterP & TRasterImage::getRaster () inline
Return TRasterP.
{ return m_mainRaster; }
getRaster() [2/2]
const TRasterP & TRasterImage::getRaster () const inline
Return TRasterP.
{ return m_mainRaster; }
Referenced by Stage::RasterPainter::onRasterImage().
getSavebox()
TRect TRasterImage::getSavebox () const inline
Return the save box of the image.
{ return m_savebox; }
Referenced by Stage::RasterPainter::onRasterImage().
getSubsampling()
int TRasterImage::getSubsampling () const inline
{ return m_subsampling; }
getType()
TImage::Type TRasterImage::getType () const inline override virtual
Return the image type.
Implements TImage.
{ return TImage::RASTER; }
References TImage::RASTER.
isEmpty()
bool TRasterImage::isEmpty () const inline
Return true if the raster is empty.
{ return !m_mainRaster; }
isOpaque()
bool TRasterImage::isOpaque () const inline
Return true if the raster is opaque.
{ return m_isOpaque; }
isScanBW()
bool TRasterImage::isScanBW () const inline
Return true if the raster comes from BW Scan.
{ return m_isScanBW; }
makeIcon()
void TRasterImage::makeIcon (const TRaster32P & raster)
Make the icon of the raster.
{
#ifndef TNZCORE_LIGHT
  assert(dstRas && dstRas->getLx() > 0 && dstRas->getLy() > 0);
  TRasterP &srcRas = m_mainRaster;
  if (!srcRas || srcRas->getLx() <= 0 || srcRas->getLy() <= 0) {
    dstRas->clear();
    return;
  }
  double dpix = m_dpix, dpiy = m_dpiy;
  if (dpix == 0) dpix = 1;
  if (dpiy == 0) dpiy = 1;
  double sx   = (double)dstRas->getLx() * dpix / (double)srcRas->getLx();
  double sy   = (double)dstRas->getLy() * dpiy / (double)srcRas->getLy();
  double sc   = std::max(sx, sy);
  TAffine aff = TScale(sc / dpix, sc / dpiy)
                    .place(srcRas->getCenterD(), dstRas->getCenterD());
  TRop::resample(dstRas, srcRas, aff);
#endif
}
References TAffine::place(), and TRop::resample().
raster()
TRasterP TRasterImage::raster () const inline override virtual
 Returns a pointer to the palette associated to this image. A palette
is a limited set of colors, identified by indexes and composed by a combination of primitive colors, i.e. RGB color.
Reimplemented from TImage.
{ return m_mainRaster; }
Referenced by setRaster().
setDpi()
void TRasterImage::setDpi (double dpix, double dpiy) inline
Set the dpi image.
{
    m_dpix = dpix;
    m_dpiy = dpiy;
  }
setIconRaster()
void TRasterImage::setIconRaster (const TRasterP & raster) inline
Set a TRasterP contained the icon of the image m_iconRaster.
{ m_iconRaster = raster; }
References TImage::raster().
setName()
void TRasterImage::setName (std::string name) inline
Set the name of the image.
{ m_name = name; }
setOffset()
void TRasterImage::setOffset (const TPoint & offset) inline
Set raster image offset m_offset.
{ m_offset = offset; }
setOpaqueFlag()
void TRasterImage::setOpaqueFlag (bool isOpaque) inline
{ m_isOpaque = isOpaque; }
setRaster()
void TRasterImage::setRaster (const TRasterP & raster)
Set the TRasterP raster.
{
  m_mainRaster = raster;
  m_savebox    = TRect(0, 0, raster->getLx() - 1, raster->getLy() - 1);
}
References raster().
setSavebox()
void TRasterImage::setSavebox (const TRect & rect) inline
Set the save box of the image.
{ m_savebox = rect; }
setScanBWFlag()
void TRasterImage::setScanBWFlag (bool isScanBW) inline
{ m_isScanBW = isScanBW; }
setSubsampling()
void TRasterImage::setSubsampling (int s)
{ m_subsampling = s; }
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/trasterimage.h
E:/opentoonz/toonz/sources/common/trasterimage/trasterimage.cpp