opentoonz: FxSchematicPort Class Reference
FxSchematicPort Class Reference final
Public Member Functions
FxSchematicPort (FxSchematicDock *parent, int type)
QRectF boundingRect () const override
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=0) override
bool linkTo (SchematicPort *port, bool checkOnly=false) override
FxSchematicDock * getDock () const
SchematicLink * makeLink (SchematicPort *port) override
Make a link from this port to the given port.
void setIsPassThrough ()
Public Member Functions inherited from SchematicPort
SchematicPort (QGraphicsItem *parent, SchematicNode *node, int type)
SchematicNode * getNode () const
QRectF boundingRect () const override
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=0) override
void addLink (SchematicLink *link)
Add the link to the links container.
int getLinkCount () const
void removeLink (SchematicLink *link)
void eraseLink (SchematicLink *link)
Removes link from the scene and the m_links list; delete it .
void eraseAllLinks ()
Removes all links from the scene and the m_links list; delete them .
SchematicLink * getLink (int index) const
SchematicNode * getLinkedNode (int index) const
Returns the node linked with the link index.
virtual SchematicLink * makeLink (SchematicPort *port)
Make a link from this port to the given port.
virtual bool linkTo (SchematicPort *port, bool checkOnly=false)=0
QPointF getHook () const
bool isLinkedTo (SchematicPort *port) const
void highLight (bool value)
bool isHighlighted () const
void updateLinksGeometry ()
Updates all links of the ports.
QPointF getLinkEndPoint () const
Returns the scene position of the link end.
int getType () const
void setType (int type)
Set the type of the port.
Protected Member Functions
void contextMenuEvent (QGraphicsSceneContextMenuEvent *cme) override
void mouseMoveEvent (QGraphicsSceneMouseEvent *me) override
void mouseReleaseEvent (QGraphicsSceneMouseEvent *me) override
TFx * getOwnerFx () const
Protected Member Functions inherited from SchematicPort
void mouseMoveEvent (QGraphicsSceneMouseEvent *me) override
void mousePressEvent (QGraphicsSceneMouseEvent *me) override
void mouseReleaseEvent (QGraphicsSceneMouseEvent *me) override
Additional Inherited Members
Signals inherited from SchematicPort
void isClicked ()
void isReleased (const QPointF &)
void sceneChanged ()
void xsheetChanged ()
Protected Attributes inherited from SchematicPort
Qt::MouseButton m_buttonState
SchematicNode * m_node
QPointF m_hook
bool m_highlighted
QList< SchematicLink * > m_ghostLinks
SchematicPort * m_linkingTo
QList< SchematicLink * > m_links
int m_type
Detailed Description
Constructor & Destructor Documentation
FxSchematicPort()
FxSchematicPort::FxSchematicPort (FxSchematicDock * parent, int type)
    : SchematicPort(parent, parent->getNode(), type)
    , m_currentTargetPort(0)
    , m_isPassThrough(false) {
  QRectF rect = boundingRect();
  if (getType() == eFxInputPort || getType() == eFxGroupedInPort)
    m_hook = QPointF(rect.left(), (rect.top() + rect.bottom()) * 0.5);
  else if (getType() == eFxOutputPort || getType() == eFxGroupedOutPort)
    m_hook = QPointF(rect.right(), (rect.top() + rect.bottom()) * 0.5);
  else  // link port
    m_hook = QPointF(rect.right(), (rect.top() + rect.bottom()) * 0.5);
  m_ownerFx              = getOwnerFx();
  TZeraryColumnFx *colFx = dynamic_cast<TZeraryColumnFx *>(m_ownerFx);
  if (colFx) m_ownerFx = colFx->getZeraryFx();
}
~FxSchematicPort()
FxSchematicPort::~FxSchematicPort ()
{}
Member Function Documentation
boundingRect()
QRectF FxSchematicPort::boundingRect () const override
{
  if (m_isPassThrough) return QRectF(0, 0, 15, 15);
  // large scaled
  if (getDock()->getNode()->isNormalIconView()) {
    switch (getType()) {
    case eFxInputPort:
    case eFxGroupedInPort:
      return QRectF(0, 0, 14, 14);
      break;
    case eFxOutputPort:
    case eFxGroupedOutPort:
      return QRectF(0, 0, 18, 18);
      break;
    case eFxLinkPort:  // LinkPort
    default:
      return QRectF(0, 0, 18, 7);
    }
  }
  // small scaled
  else {
    switch (getType()) {
    case eFxInputPort: {
      FxSchematicNode *node = getDock()->getNode();
      float nodeHeight =
          node->boundingRect().height() - 10.0f;  // 10.0 is margin
      TFx *fx = 0;
      FxSchematicZeraryNode *zeraryNode =
          dynamic_cast<FxSchematicZeraryNode *>(node);
      if (zeraryNode) {
        TZeraryColumnFx *zcfx =
            dynamic_cast<TZeraryColumnFx *>(zeraryNode->getFx());
        fx = zcfx->getZeraryFx();
      } else {
        fx = node->getFx();
      }
      if (fx && fx->getInputPortCount()) {
        // ex. particles fx etc. For fxs of which amount of ports may change
        if (fx->hasDynamicPortGroups())
          nodeHeight =
              (nodeHeight - (float)(2 * (fx->getInputPortCount() - 1))) /
              (float)fx->getInputPortCount();
        else
          nodeHeight =
              (nodeHeight - (float)(4 * (fx->getInputPortCount() - 1))) /
              (float)fx->getInputPortCount();
      }
      return QRectF(0, 0, 10, nodeHeight);
    } break;
    case eFxGroupedInPort:
    case eFxOutputPort:
    case eFxGroupedOutPort: {
      FxSchematicNode *node = getDock()->getNode();
      float nodeHeight =
          node->boundingRect().height() - 10.0f;  // 10.0 is margin
      return QRectF(0, 0, 10, nodeHeight);
    } break;
    case eFxLinkPort:  // LinkPort
    default:
      return QRectF(0, 0, 10, 5);
      break;
    }
  }
  return QRectF();
}
contextMenuEvent()
void FxSchematicPort::contextMenuEvent (QGraphicsSceneContextMenuEvent * cme) override protected
{
  FxSchematicScene *fxScene = dynamic_cast<FxSchematicScene *>(scene());
  QMenu menu(fxScene->views()[0]);
  TFx *fx = getDock()->getNode()->getFx();
  bool enableInsertAction =
      fxScene->getXsheet()->getFxDag()->getInternalFxs()->containsFx(fx) &&
      (!fx->getAttributes()->isGrouped() ||
       fx->getAttributes()->isGroupEditing());
  if ((getType() == eFxOutputPort || getType() == eFxGroupedOutPort) &&
      enableInsertAction) {
    fxScene->initCursorScenePos();
    if (cme->modifiers() & Qt::ControlModifier) {
      menu.addAction(fxScene->getAgainAction(AddFxContextMenu::Add));
      if (!menu.actions().isEmpty()) {
        menu.exec(cme->screenPos());
        return;
      }
    }
    QAction *disconnectFromXSheet =
        new QAction(tr("&Disconnect from Xsheet"), &menu);
    connect(disconnectFromXSheet, SIGNAL(triggered()), fxScene,
            SLOT(onDisconnectFromXSheet()));
    QAction *connectToXSheet = new QAction(tr("&Connect to Xsheet"), &menu);
    connect(connectToXSheet, SIGNAL(triggered()), fxScene,
            SLOT(onConnectToXSheet()));
    QAction *fxEditorPopup =
        CommandManager::instance()->getAction(MI_FxParamEditor);
    menu.addMenu(fxScene->getAddFxMenu());
    menu.addAction(fxEditorPopup);
    if (fxScene->getXsheet()->getFxDag()->getTerminalFxs()->containsFx(
            getDock()->getNode()->getFx()))
      menu.addAction(disconnectFromXSheet);
    else
      menu.addAction(connectToXSheet);
  }
  menu.exec(cme->screenPos());
}
getDock()
FxSchematicDock * FxSchematicPort::getDock () const
{
  return dynamic_cast<FxSchematicDock *>(parentItem());
}
getOwnerFx()
TFx * FxSchematicPort::getOwnerFx () const protected
{
  FxSchematicNode *node = dynamic_cast<FxSchematicNode *>(this->getNode());
  if (!node) return 0;
  return node->getFx();
}
linkTo()
bool FxSchematicPort::linkTo (SchematicPort * port, bool checkOnly = false) override virtual
Check and make a connection between the data Objects. Returns true if it is possible to have a connection between the data Object represented by this SchematicPort and that represented by port. If check only is false no connections is created!
See also
TFxPort, TStageObject.
Implements SchematicPort.
{
  if (port == this) return false;
  FxSchematicNode *dstNode = dynamic_cast<FxSchematicNode *>(port->getNode());
  FxSchematicNode *srcNode = dynamic_cast<FxSchematicNode *>(getNode());
  if (dstNode == srcNode) return false;
  TFx *inputFx = 0, *fx = 0;
  int portIndex = 0;
  if (getType() == eFxInputPort && port->getType() == eFxOutputPort) {
    inputFx   = dstNode->getFx();
    fx        = srcNode->getFx();
    portIndex = srcNode->getInputDockId(this->getDock());
  } else if (getType() == eFxOutputPort && port->getType() == eFxInputPort) {
    inputFx   = srcNode->getFx();
    fx        = dstNode->getFx();
    portIndex = dstNode->getInputDockId(
        (dynamic_cast<FxSchematicPort *>(port))->getDock());
  } else
    return false;
  if (inputFx->getAttributes()->isGrouped() &&
      fx->getAttributes()->isGrouped() &&
      inputFx->getAttributes()->getEditingGroupId() !=
          fx->getAttributes()->getEditingGroupId())
    return false;
  FxSchematicScene *fxScene = dynamic_cast<FxSchematicScene *>(scene());
  if (!fxScene) return false;
  FxDag *fxDag = fxScene->getXsheet()->getFxDag();
  if (fxDag->checkLoop(inputFx, fx)) return false;
  if (!checkOnly) linkEffects(inputFx, fx, portIndex);
  return true;
}
References FxDag::checkLoop(), TXsheet::getFxDag(), and SchematicPort::getType().
makeLink()
SchematicLink * FxSchematicPort::makeLink (SchematicPort * port) override virtual
Make a link from this port to the given port.
Reimplemented from SchematicPort.
{
  if (isLinkedTo(port) || !port) return 0;
  FxSchematicLink *link = new FxSchematicLink(0, scene());
  if (getType() == eFxLinkPort && port->getType() == eFxLinkPort)
    link->setLineShaped(true);
  link->setStartPort(this);
  link->setEndPort(port);
  addLink(link);
  port->addLink(link);
  link->updatePath();
  return link;
}
References SchematicPort::addLink(), SchematicPort::getType(), SchematicPort::isLinkedTo(), SchematicLink::setEndPort(), SchematicLink::setStartPort(), and SchematicLink::updatePath().
mouseMoveEvent()
void FxSchematicPort::mouseMoveEvent (QGraphicsSceneMouseEvent * me) override protected
{
  SchematicPort::mouseMoveEvent(me);
  if (!m_ghostLinks.isEmpty() && !m_ghostLinks[0]->isVisible())
    m_ghostLinks[0]->show();
  bool cntr = me->modifiers() == Qt::ControlModifier;
  if (m_currentTargetPort) {
    m_currentTargetPort->resetSnappedLinksOnDynamicPortFx();
    m_currentTargetPort = 0;
  }
  if (!m_linkingTo) return;
  FxSchematicPort *targetPort = dynamic_cast<FxSchematicPort *>(m_linkingTo);
  assert(targetPort);
  m_currentTargetPort    = targetPort;
  TFx *targetFx          = targetPort->getOwnerFx();
  TZeraryColumnFx *colFx = dynamic_cast<TZeraryColumnFx *>(targetFx);
  if (colFx) targetFx = colFx->getZeraryFx();
  if (targetPort->getType() != eFxInputPort ||
      !targetFx->hasDynamicPortGroups() || targetPort == this)
    return;
  FxSchematicNode *node =
      dynamic_cast<FxSchematicNode *>(targetPort->getNode());
  int id                = node->getInputDockId(targetPort->getDock());
  TFxPort *targetFxPort = targetFx->getInputPort(id);
  int groupId           = targetFxPort->getGroupIndex();
  if (groupId < 0) return;
  std::vector<TFxPort *> groupedPorts =
      targetFx->dynamicPortGroup(groupId)->ports();
  int portId = getIndex(targetFxPort, groupedPorts);
  if (portId == -1) return;
  if (targetFx != m_ownerFx && cntr && getType() == eFxOutputPort)
    targetPort->handleSnappedLinksOnDynamicPortFx(groupedPorts, portId);
  else if (targetFx == m_ownerFx && getType() == eFxInputPort) {
    if (!m_ghostLinks.isEmpty()) {
      for (SchematicLink *ghostLink : m_ghostLinks)
        scene()->removeItem(ghostLink);
      qDeleteAll(m_ghostLinks.begin(), m_ghostLinks.end());
      m_ghostLinks.clear();
    }
    FxSchematicNode *thisNode = dynamic_cast<FxSchematicNode *>(getNode());
    int thisId                = thisNode->getInputDockId(getDock());
    TFxPort *thisFxPort       = targetFx->getInputPort(thisId);
    int thisGroupId           = thisFxPort->getGroupIndex();
    if (thisGroupId != groupId) return;
    int thisPortId = getIndex(thisFxPort, groupedPorts);
    if (thisPortId == -1) return;
    targetPort->handleSnappedLinksOnDynamicPortFx(groupedPorts, portId,
                                                  thisPortId);
    SchematicLink *link = getLink(0);
    assert(link);
    SchematicLink *ghostLink = targetPort->makeLink(link->getOtherPort(this));
    if (ghostLink) {
      targetPort->m_ghostLinks.append(ghostLink);
    }
  }
}
mouseReleaseEvent()
void FxSchematicPort::mouseReleaseEvent (QGraphicsSceneMouseEvent * me) override protected
{
  if (m_currentTargetPort)
    m_currentTargetPort->resetSnappedLinksOnDynamicPortFx();
  m_currentTargetPort = 0;
  FxSchematicPort *targetPort =
      dynamic_cast<FxSchematicPort *>(searchPort(me->scenePos()));
  if (!targetPort)  // not over a port: do nothing
  {
    SchematicPort::mouseReleaseEvent(me);
    return;
  }
  TFx *targetOwnerFx     = targetPort->getOwnerFx();
  TZeraryColumnFx *colFx = dynamic_cast<TZeraryColumnFx *>(targetOwnerFx);
  if (colFx) targetOwnerFx = colFx->getZeraryFx();
  // if the target fx has no dynamic port or has dynamic ports but the target
  // port is not an input port: do nothing!
  if (!targetOwnerFx || !targetOwnerFx->hasDynamicPortGroups() ||
      targetPort->getType() != eFxInputPort) {
    SchematicPort::mouseReleaseEvent(me);
    return;
  }
  FxSchematicNode *targetNode =
      dynamic_cast<FxSchematicNode *>(targetPort->getNode());
  int targetFxId        = targetNode->getInputDockId(targetPort->getDock());
  TFxPort *targetFxPort = targetOwnerFx->getInputPort(targetFxId);
  int targetGroupId     = targetFxPort->getGroupIndex();
  if (targetGroupId < 0) {
    SchematicPort::mouseReleaseEvent(me);
    return;
  }
  std::vector<TFxPort *> groupedPorts =
      targetOwnerFx->dynamicPortGroup(targetGroupId)->ports();
  int groupedPortCount = groupedPorts.size();
  if (targetOwnerFx != m_ownerFx && me->modifiers() == Qt::ControlModifier &&
      linkTo(targetPort, true)) {
    // trying to link different fxs inserting the new link and shifting the
    // others
    int targetIndex = getIndex(targetFxPort, groupedPorts);
    if (targetIndex == -1) {
      SchematicPort::mouseReleaseEvent(me);
      return;
    }
    int i;
    TUndoManager::manager()->beginBlock();
    for (i = groupedPortCount - 1; i > targetIndex; i--) {
      TFxPort *currentPort   = groupedPorts[i];
      TFxPort *precedentPort = groupedPorts[i - 1];
      int currentPortIndex   = getInputPortIndex(currentPort, targetOwnerFx);
      linkEffects(precedentPort->getFx(), colFx ? colFx : targetOwnerFx,
                  currentPortIndex);
    }
    linkTo(targetPort);
    TUndoManager::manager()->endBlock();
    emit sceneChanged();
    emit xsheetChanged();
  } else if (targetOwnerFx == m_ownerFx && m_type == eFxInputPort &&
             getLink(0) && targetPort != this) {
    // reordering of links in input of the same fxs
    /*FxSchematicNode* linkedNode =
dynamic_cast<FxSchematicNode*>(getLinkedNode(0));
assert(linkedNode);
TFx* linkedFx = linkedNode->getFx();
assert(linkedFx);*/
    int thisFxId        = targetNode->getInputDockId(getDock());
    TFxPort *thisFxPort = m_ownerFx->getInputPort(thisFxId);
    TFx *linkedFx       = thisFxPort->getFx();
    int targetIndex = getIndex(targetFxPort, groupedPorts);
    int thisIndex   = getIndex(thisFxPort, groupedPorts);
    if (targetIndex != -1 && thisIndex != -1 && thisIndex != targetIndex) {
      TUndoManager::manager()->beginBlock();
      // linkEffects(0,colFx ? colFx : m_ownerFx,thisFxId);
      if (thisIndex > targetIndex) {
        int i;
        for (i = thisIndex; i > targetIndex; i--) {
          TFxPort *currentPort   = groupedPorts[i];
          TFxPort *precedentPort = groupedPorts[i - 1];
          int currentId          = getInputPortIndex(currentPort, m_ownerFx);
          linkEffects(precedentPort->getFx(), colFx ? colFx : m_ownerFx,
                      currentId);
        }
      } else {
        int i;
        for (i = thisIndex; i < targetIndex; i++) {
          TFxPort *currentPort = groupedPorts[i];
          TFxPort *nextPort    = groupedPorts[i + 1];
          int currentId        = getInputPortIndex(currentPort, m_ownerFx);
          linkEffects(nextPort->getFx(), colFx ? colFx : m_ownerFx, currentId);
        }
      }
      linkEffects(linkedFx, colFx ? colFx : m_ownerFx, targetFxId);
      TUndoManager::manager()->endBlock();
      emit sceneChanged();
      emit xsheetChanged();
    } else
      SchematicPort::mouseReleaseEvent(me);
  } else
    SchematicPort::mouseReleaseEvent(me);
}
paint()
void FxSchematicPort::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget = 0) override
{
  if (m_isPassThrough && getLinkCount() > 0) return;
  // large scaled
  if (getDock()->getNode()->isNormalIconView()) {
    switch (getType()) {
    case eFxInputPort:
    case eFxGroupedInPort: {
      QRect sourceRect =
          scene()->views()[0]->matrix().mapRect(boundingRect()).toRect();
      static QIcon fxPortRedIcon(":Resources/fxport_red.svg");
      static QIcon fxPortPassThroughRedIcon(":Resources/fxport_pt_red.svg");
      QPixmap redPm = (m_isPassThrough)
                          ? fxPortPassThroughRedIcon.pixmap(sourceRect.size())
                          : fxPortRedIcon.pixmap(sourceRect.size());
      sourceRect = QRect(0, 0, sourceRect.width() * getDevPixRatio(),
                         sourceRect.height() * getDevPixRatio());
      painter->drawPixmap(boundingRect(), redPm, sourceRect);
    } break;
    case eFxOutputPort:
    case eFxGroupedOutPort: {
      QRect sourceRect =
          scene()->views()[0]->matrix().mapRect(boundingRect()).toRect();
      static QIcon fxPortBlueIcon(":Resources/fxport_blue.svg");
      QPixmap bluePm = fxPortBlueIcon.pixmap(sourceRect.size());
      sourceRect     = QRect(0, 0, sourceRect.width() * getDevPixRatio(),
                         sourceRect.height() * getDevPixRatio());
      painter->drawPixmap(boundingRect(), bluePm, sourceRect);
      FxSchematicDock *parentDock =
          dynamic_cast<FxSchematicDock *>(parentItem());
      if (parentDock) {
        FxSchematicNode *parentFxNode =
            dynamic_cast<FxSchematicNode *>(parentDock->parentItem());
        if (parentFxNode) {
          bool isCached = parentFxNode->isCached();
          if (isCached) {
            QPixmap cachePm = QPixmap(":Resources/cachefx.png");
            painter->drawPixmap(QRectF(0, 0, 18, 36), cachePm,
                                QRectF(0, 0, 50, 100));
          }
        }
      }
    } break;
    case eFxLinkPort:  // LinkPort
    default: {         //
      QRect sourceRect =
          scene()->views()[0]->matrix().mapRect(boundingRect()).toRect();
      QPixmap linkPm =
          QIcon(":Resources/schematic_link.svg").pixmap(sourceRect.size());
      sourceRect = QRect(0, 0, sourceRect.width() * getDevPixRatio(),
                         sourceRect.height() * getDevPixRatio());
      painter->drawPixmap(boundingRect(), linkPm, sourceRect);
    } break;
    }
  }
  // small scaled
  else {
    painter->setPen(Qt::NoPen);
    switch (getType()) {
    case eFxInputPort:
    case eFxGroupedInPort: {
      painter->setBrush(QColor(223, 100, 100, 255));
    } break;
    case eFxOutputPort:
    case eFxGroupedOutPort: {
      painter->setBrush(QColor(100, 100, 223, 255));
    } break;
    case eFxLinkPort:  // LinkPort
    {
      QRect sourceRect =
          scene()->views()[0]->matrix().mapRect(boundingRect()).toRect();
      QPixmap linkPm = QIcon(":Resources/schematic_link_small.svg")
                           .pixmap(sourceRect.size());
      sourceRect = QRect(0, 0, sourceRect.width() * getDevPixRatio(),
                         sourceRect.height() * getDevPixRatio());
      painter->drawPixmap(boundingRect(), linkPm, sourceRect);
    } break;
    }
    painter->drawRect(boundingRect());
  }
}
setIsPassThrough()
void FxSchematicPort::setIsPassThrough ()
{
  m_isPassThrough = true;
  // recompute the hook position
  QRectF rect = boundingRect();
  if (getType() == eFxInputPort)
    m_hook = QPointF(rect.right(), (rect.top() + rect.bottom()) * 0.5);
  else if (getType() == eFxOutputPort)
    m_hook = QPointF(rect.left(), (rect.top() + rect.bottom()) * 0.5);
}
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/toonzqt/fxschematicnode.h
E:/opentoonz/toonz/sources/toonzqt/fxschematicnode.cpp