opentoonz: ImageUtils::ShortcutZoomer Class Reference
ImageUtils::ShortcutZoomer Class Reference abstract
The ShortcutZoomer abstract base class is used by viewer widget to access shortcut-related commands.
#include <imageutils.h>
Public Member Functions
ShortcutZoomer (QWidget *viewerWidget)
Constructs on the specified viewer widget.
QWidget * getWidget ()
Returns the processed viewer widget.
bool exec (QKeyEvent *event)
Protected Member Functions
virtual bool zoom (bool zoomin, bool resetView)=0
Handler for zoom commands. Required.
virtual bool fit ()
Handler for 'fit to image' commands.
virtual bool setActualPixelSize ()
Handler for 'use actual pixel size' commands.
virtual bool setFlipX ()
Handler for 'flip viewer vertically' commands.
virtual bool setFlipY ()
Handler for 'flip viewer horizontally' commands.
virtual bool resetZoom ()
Handler for 'reset zoom' commands.
virtual bool resetRotation ()
Handler for 'reset rotation' commands.
virtual bool resetPosition ()
Handler for 'reset position' commands.
virtual bool toggleFullScreen (bool quit=false)
Handler for 'toggle fullscreen' commands.
Detailed Description
The ShortcutZoomer abstract base class is used by viewer widget to access shortcut-related commands.
This class is a wrapper for shortcuts established by the CommandManager interface.
Subclass it defining the required view commands, then implement a keyPressEvent() event handler in the viewer widget you want:
void MyViewer::keyPressEvent(QKeyEvent* ke)
{
  if(ViewerZoomer(this).exec(event))
    return;
  return MyViewerBase::keyPressEvent(ke);
}
Warning
Use the FullScreenWidget class to wrap a viewer class that needs to go fullscreen.
Constructor & Destructor Documentation
ShortcutZoomer()
ImageUtils::ShortcutZoomer::ShortcutZoomer (QWidget * viewerWidget)
Constructs on the specified viewer widget.
    : m_widget(zoomingWidget) {}
Member Function Documentation
exec()
bool ImageUtils::ShortcutZoomer::exec (QKeyEvent * event)
Processes a key event for shortcuts related to viewer commands.
Returns
Whether a shortcut was recognized.
{
  int zoomInKey, zoomOutKey, viewResetKey, zoomFitKey, showHideFullScreenKey,
      actualPixelSize, flipX, flipY, zoomReset, rotateReset, positionReset;
  getViewerShortcuts(zoomInKey, zoomOutKey, viewResetKey, zoomFitKey,
                     showHideFullScreenKey, actualPixelSize, flipX, flipY,
                     zoomReset, rotateReset, positionReset);
  int key = event->key();
  if (key == Qt::Key_Control || key == Qt::Key_Shift || key == Qt::Key_Alt)
    return false;
  key = key | event->modifiers() &
                  (~0xf0000000);  // Ignore if the key is a numpad key
  return (key == showHideFullScreenKey)
             ? toggleFullScreen()
             : (key == Qt::Key_Escape)
                   ? toggleFullScreen(true)
                   : (key == actualPixelSize)
                         ? setActualPixelSize()
                         : (key == zoomFitKey)
                               ? fit()
                               : (key == zoomInKey || key == zoomOutKey ||
                                  key == viewResetKey)
                                     ? zoom(key == zoomInKey,
                                            key == viewResetKey)
                                     : (key == flipX)
                                           ? setFlipX()
                                           : (key == flipY)
                                                 ? setFlipY()
                                                 : (key == zoomReset)
                                                       ? resetZoom()
                                                       : (key == rotateReset)
                                                             ? resetRotation()
                                                             : (key ==
                                                                positionReset)
                                                                   ? resetPosition()
                                                                   : false;
  ;
}
References fit(), resetPosition(), resetRotation(), resetZoom(), setActualPixelSize(), setFlipX(), setFlipY(), toggleFullScreen(), and zoom().
fit()
virtual bool ImageUtils::ShortcutZoomer::fit () inline protected virtual
Handler for 'fit to image' commands.
Reimplemented in ViewerZoomer.
Referenced by exec().
getWidget()
QWidget * ImageUtils::ShortcutZoomer::getWidget () inline
Returns the processed viewer widget.
resetPosition()
virtual bool ImageUtils::ShortcutZoomer::resetPosition () inline protected virtual
Handler for 'reset position' commands.
Reimplemented in ViewerZoomer.
Referenced by exec().
resetRotation()
virtual bool ImageUtils::ShortcutZoomer::resetRotation () inline protected virtual
Handler for 'reset rotation' commands.
Reimplemented in ViewerZoomer.
Referenced by exec().
resetZoom()
virtual bool ImageUtils::ShortcutZoomer::resetZoom () inline protected virtual
Handler for 'reset zoom' commands.
Reimplemented in ViewerZoomer.
Referenced by exec().
setActualPixelSize()
virtual bool ImageUtils::ShortcutZoomer::setActualPixelSize () inline protected virtual
Handler for 'use actual pixel size' commands.
Reimplemented in ViewerZoomer.
Referenced by exec().
setFlipX()
virtual bool ImageUtils::ShortcutZoomer::setFlipX () inline protected virtual
Handler for 'flip viewer vertically' commands.
Reimplemented in ViewerZoomer.
Referenced by exec().
setFlipY()
virtual bool ImageUtils::ShortcutZoomer::setFlipY () inline protected virtual
Handler for 'flip viewer horizontally' commands.
Reimplemented in ViewerZoomer.
Referenced by exec().
toggleFullScreen()
virtual bool ImageUtils::ShortcutZoomer::toggleFullScreen (bool quit = false) inline protected virtual
Handler for 'toggle fullscreen' commands.
Reimplemented in ViewerZoomer.
  {
    return false;
  }
Referenced by exec().
zoom()
virtual bool ImageUtils::ShortcutZoomer::zoom (bool zoomin, bool resetView) protected pure virtual
Handler for zoom commands. Required.
Implemented in ViewerZoomer.
Referenced by exec().
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/toonzqt/imageutils.h
E:/opentoonz/toonz/sources/toonzqt/imageutils.cpp