opentoonz: TStrokeBenderDeformation Class Reference
TStrokeBenderDeformation Class Reference final
#include <tstrokedeformations.h>
Public Types
enum VERSUS { INNER = 0 , OUTER }
Public Member Functions
TStrokeBenderDeformation (const TStroke *stroke, double parameterOfNearest, double lengthOfDeformation=50)
TStrokeBenderDeformation (const TStroke *stroke, const TPointD &centerOfRot, double angle, double parameterOfNearest, int innerOrOuter=INNER, double lengthOfDeformation=50)
TThickPoint getDisplacement (const TStroke &, double s) const override
TThickPoint getDisplacementForControlPoint (const TStroke &, UINT n) const override
TThickPoint getDisplacementForControlPointLen (const TStroke &stroke, double cpLen) const override
double getDelta (const TStroke &, double) const override
double getMaxDiff () const override
virtual TThickPoint getDisplacement (const TStroke &stroke, double w) const =0
virtual TThickPoint getDisplacementForControlPoint (const TStroke &stroke, UINT n) const =0
virtual TThickPoint getDisplacementForControlPointLen (const TStroke &stroke, double cpLen) const =0
virtual double getDelta (const TStroke &stroke, double w) const =0
virtual double getMaxDiff () const =0
Detailed Description
Manage the bending of a stroke.
Member Enumeration Documentation
VERSUS
enum TStrokeBenderDeformation::VERSUS
{ INNER = 0, OUTER };
Constructor & Destructor Documentation
TStrokeBenderDeformation() [1/2]
TStrokeBenderDeformation::TStrokeBenderDeformation (const TStroke * stroke, double parameterOfNearest, double lengthOfDeformation = 50)
Use this constructor with increasePoints.
Parameters
stroke a reference to a stroke
parameterOfNearest
lengthOfDeformation
    : m_pRef(ref)
    , m_startLength(s)
    , m_lengthOfDeformation(l)
    , m_vect(0)
    , m_versus(INNER) {
  assert(m_lengthOfDeformation >= 0);
  if (isAlmostZero(m_lengthOfDeformation))
    m_lengthOfDeformation = TConsts::epsilon;
}
TStrokeBenderDeformation() [2/2]
TStrokeBenderDeformation::TStrokeBenderDeformation (const TStroke * stroke, const TPointD & centerOfRot, double angle, double parameterOfNearest, int innerOrOuter = INNER, double lengthOfDeformation = 50)
Use this constructor with movePoints.
    : m_pRef(ref)
    , m_startLength(s)
    , m_lengthOfDeformation(l)
    , m_vect(new TPointD(vect))
    , m_versus(innerOrOuter)
    , m_angle(angle) {
  assert(m_lengthOfDeformation >= 0);
  if (isAlmostZero(m_lengthOfDeformation))
    m_lengthOfDeformation = TConsts::epsilon;
}
~TStrokeBenderDeformation()
TStrokeBenderDeformation::~TStrokeBenderDeformation () virtual
{ delete m_vect; }
Member Function Documentation
getDelta()
double TStrokeBenderDeformation::getDelta (const TStroke & stroke, double w) const override virtual
| d getDisplacement() / dw |
stroke to test
w stroke parameter
\ret | d getDisplacement() / dw |
Implements TStrokeDeformation.
{
  double totalLength = s.getLength();
  if (totalLength != 0) {
    double val = s.getLength(w) / totalLength * (M_PI * 10.0);
    return sin(val);
  }
  return 0;
}
References TStroke::getLength().
getDisplacement()
TThickPoint TStrokeBenderDeformation::getDisplacement (const TStroke & stroke, double w) const override virtual
return displacement to use with function increaseControlPoints
stroke to test
w stroke parameter
\ret displacement to apply to obtain deformation
See also
increaseControlPoints
Implements TStrokeDeformation.
{
  // potenziale exp^(-x^2) limitato tra
  // [-c_maxLengthOfGaussian,c_maxLengthOfGaussian]
  double strokeLengthAtParameter = s.getLength(w);
  double diff                    = strokeLengthAtParameter - m_startLength;
  if (m_vect) {
    double outVal = 0.0;
    if (fabs(diff) <= m_lengthOfDeformation) {
      if (m_versus == INNER) {
        diff *= (1.0 / m_lengthOfDeformation) * c_maxLengthOfGaussian;
        outVal = gaussianPotential(diff);
      } else if (m_versus == OUTER) {
        double valForGaussian = -c_maxLengthOfGaussian +
                                2 * c_maxLengthOfGaussian /
                                    m_lengthOfDeformation *
                                    strokeLengthAtParameter;
        outVal = 1.0 - gaussianPotential(valForGaussian);
      }
    }
    TPointD cp = convert(s.getControlPointAtParameter(w));
    TPointD p  = cp;
    TRotation rot(*m_vect, outVal * rad2degree(m_angle));
    p = rot * p;
    return TThickPoint(p - cp, 0.0);
  }
  return TThickPoint();
}
References TStroke::getControlPointAtParameter(), and TStroke::getLength().
getDisplacementForControlPoint()
TThickPoint TStrokeBenderDeformation::getDisplacementForControlPoint (const TStroke & stroke, UINT n) const override virtual
return displacement to use with function modifyControlPoints
stroke to test
n control point to get
\ret displacement to apply to obtain deformation
See also
modifyControlPoints
Implements TStrokeDeformation.
{
  // potenziale exp^(-x^2) limitato tra
  // [-c_maxLengthOfGaussian,c_maxLengthOfGaussian]
  double strokeLengthAtParameter = s.getLengthAtControlPoint(n);
  double diff                    = strokeLengthAtParameter - m_startLength;
  if (m_vect) {
    double outVal = 0;
    if (fabs(diff) <= m_lengthOfDeformation && m_versus == INNER) {
      diff *= (1.0 / m_lengthOfDeformation) * c_maxLengthOfGaussian;
      outVal = gaussianPotential(diff);
    } else if (m_versus == OUTER) {
      double valForGaussian = -c_maxLengthOfGaussian +
                              2 * c_maxLengthOfGaussian /
                                  m_lengthOfDeformation *
                                  strokeLengthAtParameter;
      outVal = 1.0 - gaussianPotential(valForGaussian);
    }
    TPointD cp = convert(s.getControlPoint(n));
    TPointD p  = cp;
    TRotation rot(*m_vect, outVal * rad2degree(m_angle));
    p = rot * p;
    return TThickPoint(p - cp, 0.0);
  }
  return TThickPoint();
}
References TStroke::getControlPoint(), and TStroke::getLengthAtControlPoint().
getDisplacementForControlPointLen()
TThickPoint TStrokeBenderDeformation::getDisplacementForControlPointLen (const TStroke & stroke, double cpLen) const override virtual
Implements TStrokeDeformation.
{
  assert(0);
  return TThickPoint();
}
getMaxDiff()
double TStrokeBenderDeformation::getMaxDiff () const override virtual
Max diff of delta (This value indicates when it's necessary to insert control point) \ret max displacement permitted
Implements TStrokeDeformation.
{
  //  return  0.09; OK per gaussiana
  return 0.4;
}
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/tstrokedeformations.h
E:/opentoonz/toonz/sources/common/tvrender/tstrokedeformations.cpp