opentoonz: StudioPaletteTreeViewer Class Reference
StudioPaletteTreeViewer Class Reference final
The StudioPaletteTreeViewer class provides an object to view and manage palettes files.
#include <studiopaletteviewer.h>
Public Slots
void addNewPalette ()
void addNewFolder ()
void deleteItems ()
void searchForPalette ()
void loadInCurrentPalette ()
void loadInCurrentPaletteAndAdaptLevel ()
void replaceCurrentPalette ()
void mergeToCurrentPalette ()
void convertToStudioPalette ()
void addNewPlt ()
void addNewFolder ()
void deleteItem ()
void searchForPlt ()
void loadInCurrentCleanupPlt ()
void replaceCurrentCleanupPlt ()
void loadInCurrentPlt ()
void replaceCurrentPlt ()
void mergeToCurrentPlt ()
Public Member Functions
StudioPaletteTreeViewer (QWidget *parent, TPaletteHandle *studioPaletteHandle, TPaletteHandle *levelPaletteHandle, TXsheetHandle *xsheetHandle, TXshLevelHandle *currentLevelHandle)
void setLevelPaletteHandle (TPaletteHandle *paletteHandle)
TPaletteHandle * getLevelPaletteHandle () const
void setCurrentLevelHandle (TXshLevelHandle *currentLevelHandle)
TXshLevelHandle * getCurrentLevelHandle () const
void setStdPaletteHandle (TPaletteHandle *stdPaletteHandle)
TPaletteHandle * getStdPaletteHandle () const
void onStudioPaletteTreeChange () override
void onStudioPaletteMove (const TFilePath &dstPath, const TFilePath &srcPath) override
void onStudioPaletteChange (const TFilePath &palette) override
void onProjectSwitched () override
void onProjectChanged () override
TFilePath getCurrentItemPath ()
StudioPaletteTreeViewer (QWidget *parent=0, TPaletteHandle *studioPaletteHandle=0, TPaletteHandle *levelPaletteHandle=0)
void setLevelPaletteHandle (TPaletteHandle *paletteHandle)
TPaletteHandle * getLevelPaletteHandle () const
void setStdPaletteHandle (TPaletteHandle *stdPltHandle)
TPaletteHandle * getStdPaletteHandle () const
void setSceneHandle (TSceneHandle *sceneHandle)
TSceneHandle * getSceneHandle () const
void setLevelHandle (TXshLevelHandle *levelHandle)
TXshLevelHandle * getLevelHandle () const
void onStudioPaletteTreeChange ()
void onStudioPaletteMove (const TFilePath &dstPath, const TFilePath &srcPath)
void onStudioPaletteChange (const TFilePath &palette)
virtual void onStudioPaletteTreeChange ()
virtual void onStudioPaletteMove (const TFilePath &dstPath, const TFilePath &srcPath)
virtual void onStudioPaletteChange (const TFilePath &palette)
virtual void onProjectSwitched ()=0
virtual void onProjectChanged ()=0
Protected Slots
void refresh ()
void refreshItem (QTreeWidgetItem *)
void resetProjectPaletteFolder ()
void onItemClicked (QTreeWidgetItem *item, int column)
void onItemChanged (QTreeWidgetItem *item, int column)
void onCurrentItemChanged (QTreeWidgetItem *current, QTreeWidgetItem *previous)
void onTreeItemExpanded (QTreeWidgetItem *)
void onRefreshTreeShortcutTriggered ()
void refresh ()
void refreshItem (QTreeWidgetItem *)
void onItemChanged (QTreeWidgetItem *item, int column)
void onItemExpanded (QTreeWidgetItem *item)
void onItemCollapsed (QTreeWidgetItem *item)
void onItemSelectionChanged ()
Protected Member Functions
void deleteItem (QTreeWidgetItem *item)
QTreeWidgetItem * createRootItem (const TFilePath path)
bool isRootItem (QTreeWidgetItem *item)
QTreeWidgetItem * createItem (const TFilePath path)
TFilePath getItemPath (QTreeWidgetItem *)
TFilePath getCurrentFolderPath ()
QTreeWidgetItem * getItem (const TFilePath path)
QTreeWidgetItem * getFolderItem (QTreeWidgetItem *parent, const TFilePath path)
void resetDropItem ()
void paintEvent (QPaintEvent *event) override
void contextMenuEvent (QContextMenuEvent *event) override
void createMenuAction (QMenu &menu, const char *id, QString name, const char *slot)
void mousePressEvent (QMouseEvent *event) override
void mouseMoveEvent (QMouseEvent *event) override
void mouseReleaseEvent (QMouseEvent *event) override
void startDragDrop ()
void dragEnterEvent (QDragEnterEvent *event) override
void dragMoveEvent (QDragMoveEvent *event) override
void dropEvent (QDropEvent *event) override
void dragLeaveEvent (QDragLeaveEvent *event) override
QTreeWidgetItem * createRootItem (const TFilePath path, const QPixmap pix)
bool isRootItem (QTreeWidgetItem *item)
QTreeWidgetItem * createItem (const TFilePath path)
TFilePath getFolderPath (QTreeWidgetItem *)
TFilePath getCurrentFolderPath ()
QTreeWidgetItem * getItem (const TFilePath path)
QTreeWidgetItem * getFolderItem (QTreeWidgetItem *parent, const TFilePath path)
void paintEvent (QPaintEvent *event)
void contextMenuEvent (QContextMenuEvent *event)
void createMenuAction (QMenu &menu, QString name, const char *slot)
void mouseMoveEvent (QMouseEvent *event)
void startDragDrop ()
void dragEnterEvent (QDragEnterEvent *event)
void dragMoveEvent (QDragMoveEvent *event)
void dropEvent (QDropEvent *event)
void dragLeaveEvent (QDragLeaveEvent *event)
void hideEvent (QHideEvent *event)
void showEvent (QShowEvent *event)
Detailed Description
The StudioPaletteTreeViewer class provides an object to view and manage palettes files.
The StudioPaletteTreeViewer class provides an object to view and manage palettes files.
Inherits QTreeWidget, StudioPalette::Listener and ProjectManager::Listener.
         This object provides interface for class \b StudioPalette.
         StudioPaletteTreeViewer is a \b QTreeWidget with three root item
related to level palette folder and current project palette folder, the three root folder of StudioPalette.
Inherits QTreeWidget and StudioPalette::Listener.
This object provides interface for class StudioPalette. StudioPaletteTreeViewer is a QTreeWidget with three root item related to level palette folder, cleanup palette folder and current project palette folder, the three root folder of StudioPalette.
Constructor & Destructor Documentation
StudioPaletteTreeViewer() [1/2]
StudioPaletteTreeViewer::StudioPaletteTreeViewer (QWidget * parent, TPaletteHandle * studioPaletteHandle, TPaletteHandle * levelPaletteHandle, TXsheetHandle * xsheetHandle, TXshLevelHandle * currentLevelHandle)
    : QTreeWidget(parent)
    , m_dropItem(0)
    , m_studioPaletteHandle(studioPaletteHandle)
    , m_levelPaletteHandle(levelPaletteHandle)
    , m_currentLevelHandle(currentLevelHandle)
    , m_xsheetHandle(xsheetHandle)
    , m_folderIcon(QIcon())
    , m_levelPaletteIcon(QIcon())
    , m_studioPaletteIcon(QIcon())
    , m_startPos() {
  setIndentation(14);
  setAlternatingRowColors(true);
  header()->close();
  setUniformRowHeights(true);
  setIconSize(QSize(21, 18));
  QList<QTreeWidgetItem *> paletteItems;
  QString levelPaletteIcon = QString(":Resources/palette.svg");
  m_levelPaletteIcon.addPixmap(levelPaletteIcon, QIcon::Normal, QIcon::On);
  QString studioPaletteIcon = QString(":Resources/studiopalette.svg");
  m_studioPaletteIcon.addPixmap(studioPaletteIcon, QIcon::Normal, QIcon::On);
  StudioPalette *studioPalette = StudioPalette::instance();
  TFilePath levelPalettePath = studioPalette->getLevelPalettesRoot();
  paletteItems.append(createRootItem(levelPalettePath));
  TFilePath projectPalettePath = studioPalette->getProjectPalettesRoot();
  if (TSystem::doesExistFileOrLevel(projectPalettePath))
    paletteItems.append(createRootItem(projectPalettePath));
  insertTopLevelItems(0, paletteItems);
  bool ret = connect(this, SIGNAL(itemChanged(QTreeWidgetItem *, int)),
                     SLOT(onItemChanged(QTreeWidgetItem *, int)));
  ret      = ret && connect(this, SIGNAL(itemClicked(QTreeWidgetItem *, int)),
                       SLOT(onItemClicked(QTreeWidgetItem *, int)));
  ret =
      ret &&
      connect(this,
              SIGNAL(currentItemChanged(QTreeWidgetItem *, QTreeWidgetItem *)),
              SLOT(onCurrentItemChanged(QTreeWidgetItem *, QTreeWidgetItem *)));
  ret = ret && connect(this, SIGNAL(itemClicked(QTreeWidgetItem *, int)), this,
                       SLOT(onTreeItemExpanded(QTreeWidgetItem *)));
  // refresh tree with shortcut key
  QAction *refreshAct = CommandManager::instance()->getAction(MI_RefreshTree);
  ret                 = ret && connect(refreshAct, SIGNAL(triggered()), this,
                       SLOT(onRefreshTreeShortcutTriggered()));
  addAction(refreshAct);
  m_palettesScanPopup = new PalettesScanPopup();
  setAcceptDrops(true);
  // Per la selezione multipla
  setSelectionMode(QAbstractItemView::ExtendedSelection);
  StudioPalette::instance()->addListener(this);
  TProjectManager::instance()->addListener(this);
  refresh();
  assert(ret);
}
~StudioPaletteTreeViewer()
StudioPaletteTreeViewer::~StudioPaletteTreeViewer ()
{}
StudioPaletteTreeViewer() [2/2]
StudioPaletteTreeViewer::StudioPaletteTreeViewer (QWidget * parent = 0, TPaletteHandle * studioPaletteHandle = 0, TPaletteHandle * levelPaletteHandle = 0)
    : QTreeWidget(parent)
    , m_dropItem(0)
    , m_stdPltHandle(studioPaletteHandle)
    , m_levelPltHandle(levelPaletteHandle)
    , m_sceneHandle(0)
    , m_levelHandle(0) {
  header()->close();
  setIconSize(QSize(20, 20));
  // Da sistemare le icone dei tre folder principali
  static QPixmap PaletteIconPxmp(":Resources/icon.png");
  QList<QTreeWidgetItem *> paletteItems;
  StudioPalette *studioPlt = StudioPalette::instance();
  // static QPixmap PaletteLevelIconPxmp(":Resources/studio_plt_toonz.png");
  TFilePath levelPltPath = studioPlt->getLevelPalettesRoot();
  paletteItems.append(createRootItem(levelPltPath, PaletteIconPxmp));
  // static QPixmap PaletteCleanupIconPxmp(":Resources/studio_plt_cleanup.png");
  TFilePath cleanupPltPath = studioPlt->getCleanupPalettesRoot();
  paletteItems.append(createRootItem(cleanupPltPath, PaletteIconPxmp));
  // DAFARE
  // Oss.: se il folder non c'e' non fa nulla, non si aprono neanche i menu' da
  // tasto destro!
  // static QPixmap PaletteProjectIconPxmp(":Resources/studio_plt_project.png");
  TFilePath projectPltPath = TFilePath(
      "C:\\Toonz 6.0 stuff\\projects\\Project Palettes");  // studioPlt->getProjectPalettesRoot();
                                                           // Per ora lo fisso
  paletteItems.append(createRootItem(projectPltPath, PaletteIconPxmp));
  insertTopLevelItems(0, paletteItems);
  connect(this, SIGNAL(itemChanged(QTreeWidgetItem *, int)), this,
          SLOT(onItemChanged(QTreeWidgetItem *, int)));
  connect(this, SIGNAL(itemExpanded(QTreeWidgetItem *)), this,
          SLOT(onItemExpanded(QTreeWidgetItem *)));
  connect(this, SIGNAL(itemCollapsed(QTreeWidgetItem *)), this,
          SLOT(onItemCollapsed(QTreeWidgetItem *)));
  connect(this, SIGNAL(itemSelectionChanged()), this,
          SLOT(onItemSelectionChanged()));
  m_palettesScanPopup = new PalettesScanPopup();
  setAcceptDrops(true);
}
Member Function Documentation
addNewFolder
void StudioPaletteTreeViewer::addNewFolder () slot
Create a new StudioPalette folder in current item path.
{
  if (!currentItem()) {
    error("Error: No folder selected.");
    return;
  }
  TFilePath newPath;
  try {
    newPath = StudioPaletteCmd::addFolder(getCurrentFolderPath());
  } catch (TException &e) {
    error("Can't create palette folder: " +
          QString(toString(e.getMessage()).c_str()));
  } catch (...) {
    error("Can't create palette folder");
  }
  setCurrentItem(getItem(newPath));
}
References StudioPaletteCmd::addFolder(), getCurrentFolderPath(), and getItem().
addNewPalette
void StudioPaletteTreeViewer::addNewPalette () slot
Create a new StudioPalette palette in current item path.
{
  if (!currentItem()) {
    error("Error: No folder selected.");
    return;
  }
  TFilePath newPath;
  try {
    newPath = StudioPaletteCmd::createPalette(getCurrentFolderPath(), "", 0);
  } catch (TException &e) {
    error("Can't create palette: " +
          QString(::to_string(e.getMessage()).c_str()));
  } catch (...) {
    error("Can't create palette");
  }
  refreshItem(currentItem());
  setCurrentItem(getItem(newPath));
}
References StudioPaletteCmd::createPalette(), getCurrentFolderPath(), getItem(), and refreshItem().
addNewPlt
void StudioPaletteTreeViewer::addNewPlt () slot
Create a new StudioPalette palette in current item path.
{
  if (!currentItem()) {
    error("Error: No folder selected.");
    return;
  }
  TFilePath newPath;
  try {
    newPath = StudioPaletteCmd::createPalette(getCurrentFolderPath(), "", 0);
  } catch (TException &e) {
    error("Can't create palette: " + QString(toString(e.getMessage()).c_str()));
  } catch (...) {
    error("Can't create palette");
  }
  setCurrentItem(getItem(newPath));
}
References StudioPaletteCmd::createPalette(), getCurrentFolderPath(), and getItem().
contextMenuEvent()
void StudioPaletteTreeViewer::contextMenuEvent (QContextMenuEvent * event) override protected
Open a context menu considering current item data role Qt::UserRole.
{
  TFilePath path = getCurrentFolderPath();
  StudioPalette *studioPlt = StudioPalette::instance();
  // Verify if click position is in a row containing an item.
  QRect rect = visualItemRect(currentItem());
  if (!QRect(0, rect.y(), width(), rect.height()).contains(event->pos()))
    return;
  bool isLevelFolder =
      (studioPlt->isFolder(path) && !studioPlt->isCleanupFolder(path));
  QMenu menu(this);
  if (isLevelFolder) {
    createMenuAction(menu, tr("New Palette"), "addNewPlt()");
    createMenuAction(menu, tr("New Folder"), "addNewFolder()");
  } else if (studioPlt->isCleanupFolder(path)) {
    createMenuAction(menu, tr("New Cleanup Palette"), "addNewPlt()");
    createMenuAction(menu, tr("New Folder"), "addNewFolder()");
  }
  if (studioPlt->isFolder(path) && studioPlt->getLevelPalettesRoot() != path &&
      studioPlt->getCleanupPalettesRoot() != path &&
      TFilePath("C:\\Toonz 6.0 stuff\\projects\\Project Palettes") !=
          path)  // DAFARE studioPlt->getProjectPalettesRoot(); Per ora lo
                 // fisso)
  {
    menu.addSeparator();
    createMenuAction(menu, tr("Delete Folder"), "deleteItem()");
  } else if (studioPlt->isPalette(path)) {
    if (studioPlt->isCleanupPalette(path)) {
      createMenuAction(menu, tr("Load into Current Cleaunp Palette"),
                       "loadInCurrentCleanupPlt()");
      createMenuAction(menu, tr("Replace with Current Cleaunp Palette"),
                       "replaceCurrentCleanupPlt()");
      menu.addSeparator();
    } else if (m_stdPltHandle->getPalette()) {
      createMenuAction(menu, tr("Load into Current Palette"),
                       "loadInCurrentPlt()");
      createMenuAction(menu, tr("Merge to Current Palette"),
                       "mergeToCurrentPlt()");
      createMenuAction(menu, tr("Replace with Current Palette"),
                       "replaceCurrentPlt()");
      menu.addSeparator();
    }
    createMenuAction(menu, tr("Delete Palette"), "deleteItem()");
    menu.addSeparator();
    menu.addAction(
        CommandManager::instance()->getAction("MI_LoadColorModelInStdPlt"));
  }
  if (isLevelFolder) {
    menu.addSeparator();
    createMenuAction(menu, tr("Search for Palettes"), "searchForPlt()");
  }
  menu.exec(event->globalPos());
}
References createMenuAction(), and getCurrentFolderPath().
convertToStudioPalette
void StudioPaletteTreeViewer::convertToStudioPalette () slot
Convert level palette to studio palette.
{
  TFilePath path               = getItemPath(currentItem());
  StudioPalette *studioPalette = StudioPalette::instance();
  if (studioPalette->isPalette(path)) {
    TPalette *palette = studioPalette->getPalette(path);
    if (!palette) {
      error("Can't touch palette");
      return;
    }
    if (m_currentPalette->getPaletteName() != palette->getPaletteName()) {
      error("Can't touch palette");
      return;
    }
    QString question =
        tr("Convert %1 to Studio Palette and Overwrite. \nAre you sure ?")
            .arg(QString::fromStdWString(path.getWideString()));
    int ret = DVGui::MsgBox(question, tr("Convert"), tr("Cancel"));
    if (ret == 0 || ret == 2) return;
    // apply global name
    time_t ltime;
    time(&ltime);
    wstring gname = std::to_wstring(ltime) + L"_" + std::to_wstring(rand());
    m_currentPalette->setGlobalName(gname);
    studioPalette->setStylesGlobalNames(m_currentPalette.getPointer());
    studioPalette->save(path, m_currentPalette.getPointer());
    m_currentPalette->setDirtyFlag(false);
    currentItem()->setIcon(0, m_studioPaletteIcon);
  } else
    error("Can't find palette");
}
References getItemPath(), TPalette::getPaletteName(), TPalette::setDirtyFlag(), and TPalette::setGlobalName().
createItem()
QTreeWidgetItem * StudioPaletteTreeViewer::createItem (const TFilePath path) protected
Create a new item related to path path.
{
  static QPixmap PaletteIconPxmp(":Resources/icon.png");
  static QPixmap FolderIconPxmp(":Resources/newfolder_over.png");
  StudioPalette *studioPlt = StudioPalette::instance();
  QString itemName = QString(path.getName().c_str());
  QTreeWidgetItem *item =
      new QTreeWidgetItem((QTreeWidget *)0, QStringList(itemName));
  if (studioPlt->isPalette(path))
    item->setIcon(0, PaletteIconPxmp);
  else if (studioPlt->isFolder(path))
    item->setIcon(0, FolderIconPxmp);
  item->setData(1, Qt::UserRole, toQString(path));
  item->setFlags(item->flags() | Qt::ItemIsEditable);
  return item;
}
References TFilePath::getName().
Referenced by refreshItem().
createMenuAction() [1/2]
void StudioPaletteTreeViewer::createMenuAction (QMenu & menu, const char * id, QString name, const char * slot) protected
Add an action to menu menu; the action has text name and its triggered() signal is connetted with slot.
{
  QAction *act = menu.addAction(name);
  string slotName(slot);
  slotName = string("1") + slotName;
  connect(act, SIGNAL(triggered()), slotName.c_str());
}
Referenced by contextMenuEvent().
createMenuAction() [2/2]
void StudioPaletteTreeViewer::createMenuAction (QMenu & menu, QString name, const char * slot) protected
Add an action to menu menu; the action has text name and its triggered() signal is connetted with slot.
{
  QAction *act = menu.addAction(name);
  string slotName(slot);
  slotName = string("1") + slotName;
  connect(act, SIGNAL(triggered()), slotName.c_str());
}
createRootItem() [1/2]
QTreeWidgetItem * StudioPaletteTreeViewer::createRootItem (const TFilePath path) protected
Create and refresh root item: Studio Palette and Cleanup Palette.
{
  QString rootName = QString::fromStdWString(path.getWideName());
  if (rootName != "Global Palettes") rootName = "Project Palettes";
  QTreeWidgetItem *rootItem =
      new QTreeWidgetItem((QTreeWidget *)0, QStringList(rootName));
  rootItem->setIcon(0, createQIcon("folder", true));
  rootItem->setData(1, Qt::UserRole, toQString(path));
  refreshItem(rootItem);
  return rootItem;
}
References refreshItem().
Referenced by resetProjectPaletteFolder().
createRootItem() [2/2]
QTreeWidgetItem * StudioPaletteTreeViewer::createRootItem (const TFilePath path, const QPixmap pix) protected
Create root item related to path path.
{
  QString rootName = QString(path.getName().c_str());
  QTreeWidgetItem *rootItem =
      new QTreeWidgetItem((QTreeWidget *)0, QStringList(rootName));
  rootItem->setIcon(0, pix);
  rootItem->setData(1, Qt::UserRole, toQString(path));
  refreshItem(rootItem);
  return rootItem;
}
References TFilePath::getName(), and refreshItem().
deleteItem [1/2]
void StudioPaletteTreeViewer::deleteItem () slot
Delete current item path from StudioPalette. If item is a not empty folder send a question to know if must delete item or not.
{
  if (!currentItem()) {
    error("Nothing to delete");
    return;
  }
  QTreeWidgetItem *parent = currentItem()->parent();
  if (!parent) return;
  if (currentItem()->childCount() > 0) {
    QString question;
    question = tr("This folder is not empty. Delete anyway?");
    int ret  = MsgBox(0, question, QObject::tr("Yes"), QObject::tr("No"));
    if (ret == 0 || ret == 2) return;
  }
  TFilePath path           = getCurrentFolderPath();
  StudioPalette *studioPlt = StudioPalette::instance();
  if (studioPlt->isFolder(path)) {
    try {
      StudioPaletteCmd::deleteFolder(path);
    } catch (TException &e) {
      error("Can't delete palette: " +
            QString(toString(e.getMessage()).c_str()));
    } catch (...) {
      error("Can't delete palette");
    }
  } else {
    assert(studioPlt->isPalette(path));
    try {
      StudioPaletteCmd::deletePalette(path);
    } catch (TException &e) {
      error("Can't delete palette: " +
            QString(toString(e.getMessage()).c_str()));
    } catch (...) {
      error("Can't delete palette");
    }
  }
}
References StudioPaletteCmd::deleteFolder(), StudioPaletteCmd::deletePalette(), and getCurrentFolderPath().
Referenced by deleteItems().
deleteItem() [2/2]
void StudioPaletteTreeViewer::deleteItem (QTreeWidgetItem * item) protected
Delete item path from StudioPalette. If item is a not empty folder send a question to know if must delete item or not.
{
  QTreeWidgetItem *parent = item->parent();
  if (!parent) return;
  if (item->childCount() > 0) {
    QString question;
    question = tr("This folder is not empty. Delete anyway?");
    int ret  = DVGui::MsgBox(question, tr("Delete"), tr("Cancel"));
    if (ret == 0 || ret == 2) return;
  }
  TFilePath path               = getItemPath(item);
  StudioPalette *studioPalette = StudioPalette::instance();
  if (studioPalette->isFolder(path)) {
    try {
      StudioPaletteCmd::deleteFolder(path);
    } catch (TException &e) {
      error("Can't delete folder: " +
            QString(::to_string(e.getMessage()).c_str()));
    } catch (...) {
      error("Can't delete folder");
    }
  } else {
    assert(studioPalette->isPalette(path));
    try {
      StudioPaletteCmd::deletePalette(path);
    } catch (TException &e) {
      error("Can't delete palette: " +
            QString(::to_string(e.getMessage()).c_str()));
    } catch (...) {
      error("Can't delete palette");
    }
  }
  refreshItem(parent);
}
References StudioPaletteCmd::deleteFolder(), StudioPaletteCmd::deletePalette(), getItemPath(), and refreshItem().
deleteItems
void StudioPaletteTreeViewer::deleteItems () slot
Delete all item selected recalling deleteItem().
{
  QList<QTreeWidgetItem *> items = selectedItems();
  int count                      = items.size();
  if (count == 0) {
    error("Nothing to delete");
    return;
  }
  int i;
  TUndoManager::manager()->beginBlock();
  for (i = 0; i < count; i++) deleteItem(items[i]);
  TUndoManager::manager()->endBlock();
}
References deleteItem().
dragEnterEvent()
void StudioPaletteTreeViewer::dragEnterEvent (QDragEnterEvent * event) override protected
Verify drag enter data, if it has an url and it's path is a palette or data is a PaletteData accept drag event.
{
  const QMimeData *mimeData      = event->mimeData();
  const PaletteData *paletteData = dynamic_cast<const PaletteData *>(mimeData);
  if (mimeData->hasUrls()) {
    if (mimeData->urls().size() != 1) return;
    QUrl url = mimeData->urls()[0];
    TFilePath path(url.toLocalFile().toStdWString());
    if (path.isEmpty() || (path.getType() != "tpl" && path.getType() != "pli" &&
                           path.getType() != "tlv" && path.getType() != "tnz"))
      return;
    event->acceptProposedAction();
  } else if (paletteData && !paletteData->hasStyleIndeces())
    event->acceptProposedAction();
  viewport()->update();
}
References TFilePath::getType().
dragLeaveEvent()
void StudioPaletteTreeViewer::dragLeaveEvent (QDragLeaveEvent * event) override protected
Set dropItem to 0 and update the tree.
{
  m_dropItem = 0;
  update();
}
dragMoveEvent()
void StudioPaletteTreeViewer::dragMoveEvent (QDragMoveEvent * event) override protected
Find item folder nearest to current position.
{
  QTreeWidgetItem *item = itemAt(event->pos());
  TFilePath newPath     = getFolderPath(item);
  if (newPath.getType() == "tpl") {
    m_dropItem = 0;
    event->ignore();
  } else {
    m_dropItem = item;
    event->acceptProposedAction();
  }
  viewport()->update();
}
References getFolderPath(), and TFilePath::getType().
dropEvent()
void StudioPaletteTreeViewer::dropEvent (QDropEvent * event) override protected
Execute drop event. If dropped palette is in studio palette folder move palette, otherwise copy palette in current folder.
{
  TFilePath path;
  const QMimeData *mimeData = event->mimeData();
  if (!mimeData->hasUrls()) return;
  if (mimeData->urls().size() != 1) return;
  QUrl url = mimeData->urls()[0];
  path     = TFilePath(url.toLocalFile().toStdWString());
  event->setDropAction(Qt::CopyAction);
  event->accept();
  TFilePath newPath = getFolderPath(m_dropItem);
  StudioPalette *studioPlt = StudioPalette::instance();
  if (path == newPath || path.getParentDir() == newPath) return;
  if (isInStudioPalette(path)) {
    newPath += TFilePath(path.getName() + path.getDottedType());
    try {
      StudioPaletteCmd::movePalette(newPath, path);
    } catch (TException &e) {
      error("Can't rename palette: " +
            QString(toString(e.getMessage()).c_str()));
    } catch (...) {
      error("Can't rename palette");
    }
  } else {
    TPalette *palette = studioPlt->getPalette(path);
    // Se non trova palette sto importando: - la palette del livello corrente o
    // - la cleanupPalette!
    if (!palette) {
      if (path.getType() == "pli" || path.getType() == "tlv") {
        TXshLevel *level = m_levelHandle->getLevel();
        assert(level && level->getSimpleLevel());
        palette = level->getSimpleLevel()->getPalette();
        path    = level->getPath();
      } else if (path.getType() == "tnz") {
        palette =
            m_sceneHandle->getScene()->getProperties()->getCleanupPalette();
        path = TFilePath();
      }
    }
    try {
      StudioPaletteCmd::createPalette(newPath, path.getName(), palette);
    } catch (TException &e) {
      error("Can't create palette: " +
            QString(toString(e.getMessage()).c_str()));
    } catch (...) {
      error("Can't create palette");
    }
  }
  m_dropItem = 0;
}
References StudioPaletteCmd::createPalette(), TFilePath::getDottedType(), getFolderPath(), TFilePath::getName(), TXshSimpleLevel::getPalette(), TFilePath::getParentDir(), TXshLevel::getPath(), ToonzScene::getProperties(), TXshLevel::getSimpleLevel(), TFilePath::getType(), and StudioPaletteCmd::movePalette().
getCurrentFolderPath()
TFilePath StudioPaletteTreeViewer::getCurrentFolderPath () protected
Return current item path.
{
  return getFolderPath(currentItem());
}
References getFolderPath().
Referenced by addNewFolder(), addNewPalette(), addNewPlt(), contextMenuEvent(), deleteItem(), loadInCurrentCleanupPlt(), loadInCurrentPlt(), mergeToCurrentPlt(), onCurrentItemChanged(), onItemChanged(), onItemSelectionChanged(), replaceCurrentCleanupPlt(), replaceCurrentPlt(), searchForPalette(), searchForPlt(), and startDragDrop().
getCurrentItemPath()
TFilePath StudioPaletteTreeViewer::getCurrentItemPath () inline
{ return getItemPath(currentItem()); }
getCurrentLevelHandle()
TXshLevelHandle * StudioPaletteTreeViewer::getCurrentLevelHandle () const inline
{
    return m_currentLevelHandle;
  }
getFolderItem()
QTreeWidgetItem * StudioPaletteTreeViewer::getFolderItem (QTreeWidgetItem * parent, const TFilePath path) protected
Return item child of parent identified by path; if it doesn't exist return 0.
{
  int childrenCount = parent->childCount();
  int i;
  for (i = 0; i < childrenCount; i++) {
    QTreeWidgetItem *item = parent->child(i);
    if (getFolderPath(item) == path)
      return item;
    else {
      item = getFolderItem(item, path);
      if (item) return item;
    }
  }
  return 0;
}
References getFolderItem(), and getFolderPath().
Referenced by getFolderItem(), and getItem().
getFolderPath()
TFilePath StudioPaletteTreeViewer::getFolderPath (QTreeWidgetItem * item) protected
Return path related to item item if item exist, otherwise return an empty path TFilePath.
{
  TFilePath path =
      (item) ? TFilePath(item->data(1, Qt::UserRole).toString().toStdWString())
             : TFilePath();
  return path;
}
Referenced by dragMoveEvent(), dropEvent(), getCurrentFolderPath(), getFolderItem(), isRootItem(), and refreshItem().
getItem()
QTreeWidgetItem * StudioPaletteTreeViewer::getItem (const TFilePath path) protected
Return item identified by path; if it doesn't exist return 0.
{
  QList<QTreeWidgetItem *> oldItems =
      findItems(QString(""), Qt::MatchContains, 0);
  if (oldItems.isEmpty()) return 0;
  int i;
  for (i = 0; i < (int)oldItems.size(); i++) {
    TFilePath oldItemPath(
        oldItems[i]->data(1, Qt::UserRole).toString().toStdWString());
    if (oldItemPath == path)
      return oldItems[i];
    else {
      QTreeWidgetItem *item = getFolderItem(oldItems[i], path);
      if (item) return item;
    }
  }
  return 0;
}
References getFolderItem().
Referenced by addNewFolder(), addNewPalette(), addNewPlt(), onCurrentItemChanged(), onItemChanged(), onItemSelectionChanged(), and refresh().
getItemPath()
TFilePath StudioPaletteTreeViewer::getItemPath (QTreeWidgetItem * item) protected
Return path related to item item if item exist, otherwise return an empty path TFilePath.
{
  TFilePath path =
      (item) ? TFilePath(item->data(1, Qt::UserRole).toString().toStdWString())
             : TFilePath();
  return path;
}
Referenced by convertToStudioPalette(), deleteItem(), loadInCurrentPalette(), mergeToCurrentPalette(), onCurrentItemChanged(), replaceCurrentPalette(), and resetProjectPaletteFolder().
getLevelHandle()
TXshLevelHandle * StudioPaletteTreeViewer::getLevelHandle () const inline
{ return m_levelHandle; }
getLevelPaletteHandle() [1/2]
TPaletteHandle * StudioPaletteTreeViewer::getLevelPaletteHandle () const inline
{ return m_levelPaletteHandle; }
getLevelPaletteHandle() [2/2]
TPaletteHandle * StudioPaletteTreeViewer::getLevelPaletteHandle () const inline
{ return m_levelPltHandle; }
getSceneHandle()
TSceneHandle * StudioPaletteTreeViewer::getSceneHandle () const inline
{ return m_sceneHandle; }
getStdPaletteHandle() [1/2]
TPaletteHandle * StudioPaletteTreeViewer::getStdPaletteHandle () const inline
{ return m_studioPaletteHandle; }
getStdPaletteHandle() [2/2]
TPaletteHandle * StudioPaletteTreeViewer::getStdPaletteHandle () const inline
{ return m_stdPltHandle; }
hideEvent()
void StudioPaletteTreeViewer::hideEvent (QHideEvent * event) protected
Receive widget hide events. Remove this listener from StudioPalette.
{
  StudioPalette::instance()->removeListener(this);
}
isRootItem()
bool StudioPaletteTreeViewer::isRootItem (QTreeWidgetItem * item) protected
Return true if item match with Studio Palette or Cleanup Palette folder.
Return true if item is a root item; false otherwise.
{
  assert(item);
  TFilePath path = getFolderPath(item);
  // DAFARE
  // Oss.: se il folder non c'e' non fa nulla, non si aprono neanche i menu' da
  // tasto destro!
  // static QPixmap PaletteProjectIconPxmp(":Resources/studio_plt_project.png");
  TFilePath projectPltPath = TFilePath(
      "C:\\Toonz 6.0 stuff\\projects\\Project Palettes");  // studioPlt->getProjectPalettesRoot();
                                                           // Per ora lo fisso
  StudioPalette *stdPalette = StudioPalette::instance();
  if (path == stdPalette->getCleanupPalettesRoot() ||
      path == stdPalette->getLevelPalettesRoot() || path == projectPltPath)
    return true;
  return false;
}
References getFolderPath().
Referenced by onItemCollapsed(), and onItemExpanded().
loadInCurrentCleanupPlt
void StudioPaletteTreeViewer::loadInCurrentCleanupPlt () slot
Recall StudioPaletteCmd::loadIntoCleanupPalette.
{
  StudioPaletteCmd::loadIntoCleanupPalette(m_levelPltHandle, m_sceneHandle,
                                           getCurrentFolderPath());
}
References getCurrentFolderPath().
loadInCurrentPalette
void StudioPaletteTreeViewer::loadInCurrentPalette () slot
Recall StudioPaletteCmd::loadIntoCurrentPalette.
{
  QList<QTreeWidgetItem *> items = selectedItems();
  int count                      = items.size();
  if (count == 0) return;
  TPalette *palette = m_levelPaletteHandle->getPalette();
  if (!palette) return;
  if (palette->isLocked()) {
    DVGui::warning("Palette is Locked!");
    return;
  }
  TPalette *newPalette =
      StudioPalette::instance()->getPalette(getItemPath(items[0]), false);
  if (!newPalette) return;
  if (m_xsheetHandle) {
    int ret = DVGui::eraseStylesInDemand(palette, m_xsheetHandle, newPalette);
    if (ret == 0) return;
  }
  StudioPaletteCmd::loadIntoCurrentPalette(m_levelPaletteHandle, newPalette);
  m_currentLevelHandle->notifyLevelChange();
  TXshLevel *level = m_currentLevelHandle->getLevel();
  if (level) {
    std::vector<TFrameId> fids;
    level->getFids(fids);
    invalidateIcons(level, fids);
  }
  int i;
  for (i = 1; i < count; i++) {
    TFilePath path = getItemPath(items[i]);
    StudioPaletteCmd::mergeIntoCurrentPalette(m_levelPaletteHandle, path);
  }
  // in order to update the title bar of palette viewer
  m_levelPaletteHandle->getPalette()->setDirtyFlag(true);
  m_levelPaletteHandle->notifyPaletteChanged();
}
References getItemPath(), and TPalette::setDirtyFlag().
loadInCurrentPaletteAndAdaptLevel
void StudioPaletteTreeViewer::loadInCurrentPaletteAndAdaptLevel () slot
{
  QList<QTreeWidgetItem *> items = selectedItems();
  assert(items.size() == 1);
  TPalette *palette = m_levelPaletteHandle->getPalette();
  if (!palette) return;
  // prevent crash when the command is applied to the palette level
  if (!m_currentLevelHandle->getSimpleLevel()) return;
  TPalette *newPalette =
      StudioPalette::instance()->getPalette(getItemPath(items[0]), true);
  if (!newPalette) return;
  AdjustPaletteDialog apd;
  if (apd.exec() != QDialog::Accepted) return;
  /* awful patch: since in StudioPaletteCmd(defined in toonzlib) I cannot use
the invalidateIcons(defined in toonzqt)
i do invalidate icons from here using a "fake TUndo", named InvalidateIconsUndo.
And, since I need to refresh icons at the end of the processing, i have to put
that fake undo twice, one before and one after.
this way , when the user do either an undo or a redo operation, I am ensured
that the last operation is the icon refresh...
*/
  TUndoManager::manager()->beginBlock();
  TUndoManager::manager()->add(new InvalidateIconsUndo(m_currentLevelHandle));
  StudioPaletteCmd::loadIntoCurrentPalette(m_levelPaletteHandle, newPalette,
                                           m_currentLevelHandle,
                                           apd.getTolerance());
  TUndoManager::manager()->add(new InvalidateIconsUndo(m_currentLevelHandle));
  TUndoManager::manager()->endBlock();
  InvalidateIconsUndo(m_currentLevelHandle).undo();
}
loadInCurrentPlt
void StudioPaletteTreeViewer::loadInCurrentPlt () slot
Recall StudioPaletteCmd::loadIntoCurrentPalette.
{
  StudioPaletteCmd::loadIntoCurrentPalette(m_levelPltHandle, m_sceneHandle,
                                           getCurrentFolderPath());
}
References getCurrentFolderPath().
mergeToCurrentPalette
void StudioPaletteTreeViewer::mergeToCurrentPalette () slot
Recall StudioPaletteCmd::mergeIntoCurrentPalette.
{
  QList<QTreeWidgetItem *> items = selectedItems();
  int count                      = items.size();
  if (count == 0) return;
  TUndoManager::manager()->beginBlock();
  int i;
  for (i = 0; i < count; i++)
    StudioPaletteCmd::mergeIntoCurrentPalette(m_levelPaletteHandle,
                                              getItemPath(items[i]));
  TUndoManager::manager()->endBlock();
}
References getItemPath().
mergeToCurrentPlt
void StudioPaletteTreeViewer::mergeToCurrentPlt () slot
Recall StudioPaletteCmd::mergeIntoCurrentPalette.
{
  StudioPaletteCmd::mergeIntoCurrentPalette(m_levelPltHandle, m_sceneHandle,
                                            getCurrentFolderPath());
}
References getCurrentFolderPath().
mouseMoveEvent()
void StudioPaletteTreeViewer::mouseMoveEvent (QMouseEvent * event) override protected
If button left is pressed start drag and drop.
{
  // If left button is not pressed return; is not drag event.
  if (!(event->buttons() & Qt::LeftButton)) return;
  startDragDrop();
}
References startDragDrop().
mousePressEvent()
void StudioPaletteTreeViewer::mousePressEvent (QMouseEvent * event) override protected
If button left is pressed start drag and drop.
{
  QTreeWidget::mousePressEvent(event);
  // If left button is not pressed return
  if (event->button() == Qt::LeftButton) m_startPos = event->pos();
}
mouseReleaseEvent()
void StudioPaletteTreeViewer::mouseReleaseEvent (QMouseEvent * event) override protected
{
  QTreeWidget::mouseReleaseEvent(event);
  if (event->button() == Qt::LeftButton) m_startPos = QPoint();
}
onCurrentItemChanged
void StudioPaletteTreeViewer::onCurrentItemChanged (QTreeWidgetItem * current, QTreeWidgetItem * previous) protected slot
Called when the current palette is switched
{
  TFilePath oldPath = getItemPath(previous);
  TFilePath newPath = getCurrentFolderPath();
  if (!m_studioPaletteHandle) return;
  if (m_currentPalette.getPointer() && m_currentPalette->getDirtyFlag()) {
    TFilePath oldPath = StudioPalette::instance()->getPalettePath(
        m_currentPalette->getGlobalName());
    if (oldPath == newPath) return;
    wstring gname = m_currentPalette->getGlobalName();
    QString question =
        tr("The current palette %1\nin the studio palette has been modified. "
           "Do you want to "
           "save your changes?")
            .arg(QString::fromStdWString(oldPath.getWideString()));
    int ret =
        DVGui::MsgBox(question, tr("Save"), tr("Discard"), tr("Cancel"), 0);
    if (ret == 3) {
      setCurrentItem(getItem(oldPath));
      return;
    }
    if (ret == 1) {
      try {
        // If the palette is level palette (i.e. NOT stdio palette), just
        // overwrite it
        if (gname.empty())
          StudioPalette::instance()->save(oldPath,
                                          m_currentPalette.getPointer());
        else
          StudioPalette::instance()->setPalette(
              oldPath, m_currentPalette.getPointer(), false);
      } catch (TSystemException se) {
        DVGui::warning(QString::fromStdWString(se.getMessage()));
        setCurrentItem(previous);
        return;
      } catch (...) {
        DVGui::warning(
            QString::fromStdWString(oldPath.getWideString() + L"\n") +
            tr("Failed to save palette."));
        setCurrentItem(previous);
        return;
      }
    }
    m_currentPalette->setDirtyFlag(false);
  }
  // load palette here
  m_currentPalette = StudioPalette::instance()->getPalette(newPath, false);
  m_studioPaletteHandle->setPalette(m_currentPalette.getPointer());
  m_studioPaletteHandle->notifyPaletteSwitched();
  StudioPaletteCmd::updateAllLinkedStyles(m_levelPaletteHandle, m_xsheetHandle);
}
References getCurrentFolderPath(), TPalette::getDirtyFlag(), TPalette::getGlobalName(), getItem(), getItemPath(), and TPalette::setDirtyFlag().
Referenced by replaceCurrentPalette().
onItemChanged
void StudioPaletteTreeViewer::onItemChanged (QTreeWidgetItem * item, int column) protected slot
If item item name change update path name in StudioPalette.
If item item name changed update name item related path name in StudioPalette.
{
  if (item != currentItem()) return;
  string name       = item->text(column).toStdString();
  TFilePath oldPath = getCurrentFolderPath();
  if (oldPath.isEmpty() || name.empty() || oldPath.getName() == name) return;
  TFilePath newPath(oldPath.getParentDir() +
                    TFilePath(name + oldPath.getDottedType()));
  try {
    StudioPaletteCmd::movePalette(newPath, oldPath);
  } catch (TException &e) {
    error("Can't rename palette: " + QString(toString(e.getMessage()).c_str()));
  } catch (...) {
    error("Can't rename palette");
  }
  setCurrentItem(getItem(newPath));
}
References getCurrentFolderPath(), TFilePath::getDottedType(), getItem(), TFilePath::getName(), TFilePath::getParentDir(), and StudioPaletteCmd::movePalette().
onItemClicked
void StudioPaletteTreeViewer::onItemClicked (QTreeWidgetItem * item, int column) protected slot
{
  if (currentItem() && m_studioPaletteHandle && m_currentPalette.getPointer()) {
    // if(m_studioPaletteHandle->getPalette() != m_currentPalette.getPointer())
    {
      m_studioPaletteHandle->setPalette(m_currentPalette.getPointer());
      m_studioPaletteHandle->notifyPaletteSwitched();
      StudioPaletteCmd::updateAllLinkedStyles(m_levelPaletteHandle,
                                              m_xsheetHandle);
    }
  }
}
onItemCollapsed
void StudioPaletteTreeViewer::onItemCollapsed (QTreeWidgetItem * item) protected slot
If item item is collapsed change item icon.
{
  if (!item || isRootItem(item)) return;
  static QPixmap FolderIconPxmp(":Resources/newfolder_over.png");
  item->setIcon(0, FolderIconPxmp);
}
References isRootItem().
onItemExpanded
void StudioPaletteTreeViewer::onItemExpanded (QTreeWidgetItem * item) protected slot
If item item is expanded change item icon.
{
  if (!item || isRootItem(item)) return;
  static QPixmap FolderIconExpandedPxmp(":Resources/folder_open.png");
  item->setIcon(0, FolderIconExpandedPxmp);
}
References isRootItem().
onItemSelectionChanged
void StudioPaletteTreeViewer::onItemSelectionChanged () protected slot
If current item is a palette set current studioPalette to it.
{
  TFilePath path = getCurrentFolderPath();
  if (!m_stdPltHandle || path.getType() != "tpl") return;
  if (m_stdPltHandle->getPalette() &&
      m_stdPltHandle->getPalette()->getDirtyFlag()) {
    QString question;
    question =
        "Current Studio Palette has been modified.\n"
        "Do you want to save your changes?";
    int ret = MsgBox(0, question, QObject::tr("Save"),
                     QObject::tr("Don't Save"), QObject::tr("Cancel"), 0);
    TPaletteP oldPalette = m_stdPltHandle->getPalette();
    TFilePath oldPath =
        StudioPalette::instance()->getPalettePath(oldPalette->getGlobalName());
    if (ret == 3) {
      setCurrentItem(getItem(oldPath));
      return;
    }
    if (ret == 1)
      StudioPalette::instance()->save(oldPath, oldPalette.getPointer());
    oldPalette->setDirtyFlag(false);
  }
  m_stdPltHandle->setPalette(StudioPalette::instance()->getPalette(path, true));
  m_stdPltHandle->notifyPaletteSwitched();
}
References getCurrentFolderPath(), TPalette::getDirtyFlag(), TPalette::getGlobalName(), getItem(), TFilePath::getType(), and TPalette::setDirtyFlag().
onProjectChanged()
void StudioPaletteTreeViewer::onProjectChanged () inline override virtual
Overridden from TProjectManager::Listener.
Implements TProjectManager::Listener.
{ resetProjectPaletteFolder(); }
onProjectSwitched()
void StudioPaletteTreeViewer::onProjectSwitched () inline override virtual
Overridden from TProjectManager::Listener.
Implements TProjectManager::Listener.
{ resetProjectPaletteFolder(); }
onRefreshTreeShortcutTriggered
void StudioPaletteTreeViewer::onRefreshTreeShortcutTriggered () protected slot
Refresh tree only when this widget has focus
{
  if (hasFocus()) refresh();
}
References refresh().
onStudioPaletteChange() [1/2]
void StudioPaletteTreeViewer::onStudioPaletteChange (const TFilePath & palette) inline virtual
Reimplemented from StudioPalette::Listener.
{ refresh(); }
onStudioPaletteChange() [2/2]
void StudioPaletteTreeViewer::onStudioPaletteChange (const TFilePath & palette) inline override virtual
Overridden from StudioPalette::Listener.
Reimplemented from StudioPalette::Listener.
{ refresh(); }
onStudioPaletteMove() [1/2]
void StudioPaletteTreeViewer::onStudioPaletteMove (const TFilePath & dstPath, const TFilePath & srcPath) inline virtual
Reimplemented from StudioPalette::Listener.
{
    refresh();
  }
onStudioPaletteMove() [2/2]
void StudioPaletteTreeViewer::onStudioPaletteMove (const TFilePath & dstPath, const TFilePath & srcPath) inline override virtual
Overridden from StudioPalette::Listener.
Reimplemented from StudioPalette::Listener.
{
    refresh();
  }
onStudioPaletteTreeChange() [1/2]
void StudioPaletteTreeViewer::onStudioPaletteTreeChange () inline virtual
Reimplemented from StudioPalette::Listener.
{ refresh(); }
onStudioPaletteTreeChange() [2/2]
void StudioPaletteTreeViewer::onStudioPaletteTreeChange () inline override virtual
Overridden from StudioPalette::Listener.
Reimplemented from StudioPalette::Listener.
{ refresh(); }
onTreeItemExpanded
void StudioPaletteTreeViewer::onTreeItemExpanded (QTreeWidgetItem * item) protected slot
When expand a tree, prepare the child items of it
{
  if (!item) return;
  // if this item was not yet opened, then get the children of this item
  if (!m_openedItems.contains(item)) refreshItem(item);
  // expand the item
  item->setExpanded(!item->isExpanded());
}
References refreshItem().
paintEvent()
void StudioPaletteTreeViewer::paintEvent (QPaintEvent * event) override protected
{
  QTreeWidget::paintEvent(event);
  QPainter p(viewport());
  if (m_dropItem) {
    QRect rect = visualItemRect(m_dropItem).adjusted(0, 0, -5, 0);
    p.setPen(Qt::red);
    p.drawRect(rect);
  }
}
refresh
void StudioPaletteTreeViewer::refresh () protected slot
Refresh all item of three root item in tree and preserve current item.
{
  StudioPalette *studioPlt = StudioPalette::instance();
  TFilePath levelPltPath = studioPlt->getLevelPalettesRoot();
  refreshItem(getItem(levelPltPath));
  TFilePath cleanupPltPath = studioPlt->getCleanupPalettesRoot();
  refreshItem(getItem(cleanupPltPath));
  // DAFARE
  TFilePath projectPltPath = TFilePath(
      "C:\\Toonz 6.0 stuff\\projects\\Project Palettes");  // studioPlt->getProjectPalettesRoot();
                                                           // Per ora lo fisso
  refreshItem(getItem(projectPltPath));
}
References getItem(), and refreshItem().
Referenced by onRefreshTreeShortcutTriggered(), searchForPalette(), searchForPlt(), and showEvent().
refreshItem
void StudioPaletteTreeViewer::refreshItem (QTreeWidgetItem * item) protected slot
Refresh item item and its children; take path concerning item and compare StudioPalette folder in path with folder in item. If are not equal add or remove child to current item. Recall itself for each item child.
Update the content of item
{
  TFilePath folderPath = getFolderPath(item);
  assert(folderPath != TFilePath());
  std::vector<TFilePath> childrenPath;
  StudioPalette::instance()->getChildren(childrenPath, folderPath);
  int currentChildCount = item->childCount();
  std::vector<QTreeWidgetItem *> currentChildren;
  int i;
  for (i = 0; i < currentChildCount; i++)
    currentChildren.push_back(item->child(i));
  int childrenPathCount = childrenPath.size();
  int itemIndex         = 0;
  int pathIndex         = 0;
  while (itemIndex < currentChildCount || pathIndex < childrenPathCount) {
    TFilePath path =
        (pathIndex < childrenPathCount) ? childrenPath[pathIndex] : TFilePath();
    QTreeWidgetItem *currentItem =
        (itemIndex < currentChildCount) ? currentChildren[itemIndex] : 0;
    TFilePath currentItemPath = getFolderPath(currentItem);
    if (path == currentItemPath) {
      itemIndex++;
      pathIndex++;
      refreshItem(currentItem);
    } else if ((!path.isEmpty() && path < currentItemPath) ||
               currentItemPath.isEmpty()) {
      currentItem = createItem(path);
      item->insertChild(pathIndex, currentItem);
      refreshItem(currentItem);
      pathIndex++;
    } else {
      assert(currentItemPath < path || path.isEmpty());
      assert(currentItem);
      item->removeChild(currentItem);
      itemIndex++;
    }
  }
}
References createItem(), getFolderPath(), and refreshItem().
Referenced by addNewPalette(), createRootItem(), deleteItem(), onTreeItemExpanded(), refresh(), and refreshItem().
replaceCurrentCleanupPlt
void StudioPaletteTreeViewer::replaceCurrentCleanupPlt () slot
Recall StudioPaletteCmd::replaceWithCleanupPalette.
{
  StudioPaletteCmd::replaceWithCleanupPalette(
      m_levelPltHandle, m_stdPltHandle, m_sceneHandle, getCurrentFolderPath());
}
References getCurrentFolderPath().
replaceCurrentPalette
void StudioPaletteTreeViewer::replaceCurrentPalette () slot
Recall StudioPaletteCmd::replaceWithCurrentPalette.
{
  QList<QTreeWidgetItem *> items = selectedItems();
  int count                      = items.size();
  if (count == 0) return;
  // exec confirmation dialog
  TPalette *current = m_levelPaletteHandle->getPalette();
  if (!current) return;
  QString label;
  if (count != 1)  // replacing to multiple palettes
    label = tr("Replacing all selected palettes with the palette \"%1\". \nAre "
               "you sure ?")
                .arg(QString::fromStdWString(current->getPaletteName()));
  else {
    TPalette *dstPalette =
        StudioPalette::instance()->getPalette(getItemPath(items[0]));
    if (!dstPalette) return;
    label = tr("Replacing the palette \"%1\" with the palette \"%2\". \nAre "
               "you sure ?")
                .arg(QString::fromStdWString(dstPalette->getPaletteName()))
                .arg(QString::fromStdWString(current->getPaletteName()));
  }
  int ret = DVGui::MsgBox(label, tr("Replace"), tr("Cancel"), 1);
  if (ret == 0 || ret == 2) return;
  TUndoManager::manager()->beginBlock();
  int i;
  for (i = 0; i < count; i++)
    StudioPaletteCmd::replaceWithCurrentPalette(
        m_levelPaletteHandle, m_studioPaletteHandle, getItemPath(items[i]));
  TUndoManager::manager()->endBlock();
  if (m_currentPalette) m_currentPalette->setDirtyFlag(false);
  // in order to update display
  onCurrentItemChanged(currentItem(), currentItem());
}
References getItemPath(), TPalette::getPaletteName(), onCurrentItemChanged(), and TPalette::setDirtyFlag().
replaceCurrentPlt
void StudioPaletteTreeViewer::replaceCurrentPlt () slot
Recall StudioPaletteCmd::replaceWithCurrentPalette.
{
  StudioPaletteCmd::replaceWithCurrentPalette(
      m_levelPltHandle, m_stdPltHandle, m_sceneHandle, getCurrentFolderPath());
}
References getCurrentFolderPath().
resetDropItem()
void StudioPaletteTreeViewer::resetDropItem () protected
{
  if (!m_dropItem) return;
  m_dropItem = 0;
}
resetProjectPaletteFolder
void StudioPaletteTreeViewer::resetProjectPaletteFolder () protected slot
Delete old project palette item and create the new one.
{
  int projectPaletteIndex = 1;
  TFilePath projectPalettePath =
      StudioPalette::instance()->getProjectPalettesRoot();
  // Prendo l'item del project palette.
  QTreeWidgetItem *projectPaletteItem = topLevelItem(projectPaletteIndex);
  if (projectPaletteItem) {
    // Se il path dell'item e' uguale a quello del project palette corrente
    // ritorno.
    if (getItemPath(projectPaletteItem) == projectPalettePath) return;
    // Altrimenti lo rimuovo.
    removeItemWidget(projectPaletteItem, 0);
    delete projectPaletteItem;
    // clear the item list in order to search the folder from scratch
    m_openedItems.clear();
    // Toonz Palette is not changed, so resurrect the ToonzPaletteRoot
    m_openedItems.insert(topLevelItem(0));
  }
  if (!TSystem::doesExistFileOrLevel(projectPalettePath)) return;
  // Creo il nuovo item con il nuovo project folder e lo inserisco nell'albero.
  // Items in the ProjectPaletteRoot are refreshed here. Stored in openedItems
  // as well.
  QTreeWidgetItem *newProjectPaletteItem = createRootItem(projectPalettePath);
  insertTopLevelItem(projectPaletteIndex, newProjectPaletteItem);
  setCurrentItem(0);
}
References createRootItem(), and getItemPath().
searchForPalette
void StudioPaletteTreeViewer::searchForPalette () slot
Open a PalettesScanPopup.
{
  m_palettesScanPopup->setCurrentFolder(getCurrentFolderPath());
  int ret = m_palettesScanPopup->exec();
  if (ret == QDialog::Accepted) refresh();
}
References getCurrentFolderPath(), refresh(), and PalettesScanPopup::setCurrentFolder().
searchForPlt
void StudioPaletteTreeViewer::searchForPlt () slot
Open a PalettesScanPopup.
{
  m_palettesScanPopup->setCurrentFolder(getCurrentFolderPath());
  int ret = m_palettesScanPopup->exec();
  if (ret == QDialog::Accepted) refresh();
}
References getCurrentFolderPath(), refresh(), and PalettesScanPopup::setCurrentFolder().
setCurrentLevelHandle()
void StudioPaletteTreeViewer::setCurrentLevelHandle (TXshLevelHandle * currentLevelHandle)
{
  m_currentLevelHandle = currentLevelHandle;
}
setLevelHandle()
void StudioPaletteTreeViewer::setLevelHandle (TXshLevelHandle * levelHandle)
{
  m_levelHandle = levelHandle;
}
setLevelPaletteHandle()
void StudioPaletteTreeViewer::setLevelPaletteHandle (TPaletteHandle * paletteHandle)
{
  m_levelPltHandle = paletteHandle;
}
setSceneHandle()
void StudioPaletteTreeViewer::setSceneHandle (TSceneHandle * sceneHandle)
{
  m_sceneHandle = sceneHandle;
}
setStdPaletteHandle()
void StudioPaletteTreeViewer::setStdPaletteHandle (TPaletteHandle * stdPaletteHandle)
{
  m_stdPltHandle = stdPltHandle;
}
showEvent()
void StudioPaletteTreeViewer::showEvent (QShowEvent * event) protected
Receive widget show events. Add this listener to StudioPalette and refresh tree.
{
  StudioPalette::instance()->addListener(this);
  refresh();
}
References refresh().
startDragDrop()
void StudioPaletteTreeViewer::startDragDrop () protected
If path related to current item exist and is a palette execute drag.
{
  TFilePath path = getCurrentFolderPath();
  if (!path.isEmpty() && (path.getType() == "tpl" || path.getType() == "pli" ||
                          path.getType() == "tlv" || path.getType() == "tnz")) {
    QDrag *drag         = new QDrag(this);
    QMimeData *mimeData = new QMimeData;
    QList<QUrl> urls;
    urls.append(pathToUrl(path));
    mimeData->setUrls(urls);
    drag->setMimeData(mimeData);
    Qt::DropAction dropAction = drag->exec(Qt::CopyAction | Qt::MoveAction);
  }
  viewport()->update();
}
References getCurrentFolderPath(), and TFilePath::getType().
Referenced by mouseMoveEvent().
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/toonzqt/studiopaletteviewer.h
E:/opentoonz/toonz/sources/toonz/studiopaletteviewer.h
E:/opentoonz/toonz/sources/toonz/studiopaletteviewer.cpp
E:/opentoonz/toonz/sources/toonzqt/studiopaletteviewer.cpp