opentoonz: TXshSoundTextColumn Class Reference
TXshSoundTextColumn Class Reference final
#include <txshsoundtextcolumn.h>
Public Member Functions
TXshColumn::ColumnType getColumnType () const override
TXshSoundTextColumn * getSoundTextColumn () override
void createSoundTextLevel (int row, QList< QString > textList)
bool canSetCell (const TXshCell &cell) const override
TXshColumn * clone () const override
void loadData (TIStream &is) override
void saveData (TOStream &os) override
Public Member Functions inherited from TXshCellColumn
TXshCellColumn ()
~TXshCellColumn ()
TXshCellColumn * getCellColumn () override
virtual bool canSetCell (const TXshCell &cell) const =0
int getRange (int &r0, int &r1) const override
virtual int getRowCount () const
bool isEmpty () const override
bool isCellEmpty (int row) const override
virtual const TXshCell & getCell (int row) const
virtual bool setCell (int row, const TXshCell &cell)
virtual void getCells (int row, int rowCount, TXshCell cells[])
virtual bool setCells (int row, int rowCount, const TXshCell cells[])
virtual void insertEmptyCells (int row, int rowCount=1)
virtual void removeCells (int row, int rowCount=1)
virtual void clearCells (int row, int rowCount=1)
int getMaxFrame () const override
virtual int getFirstRow () const
virtual void checkColumn () const
bool getLevelRange (int row, int &r0, int &r1) const override
void saveCellMarks (TOStream &os)
bool loadCellMarks (std::string tagName, TIStream &is)
void setCellMark (int frame, int id)
int getCellMark (int frame) const
QMap< int, int > getCellMarks () const
void clearCellMarks ()
Public Member Functions inherited from TXshColumn
TXshColumn ()
virtual ColumnType getColumnType () const =0
virtual TXshLevelColumn * getLevelColumn ()
virtual TXshSoundColumn * getSoundColumn ()
virtual TXshSoundTextColumn * getSoundTextColumn ()
virtual TXshCellColumn * getCellColumn ()
virtual TXshPaletteColumn * getPaletteColumn ()
virtual TXshZeraryFxColumn * getZeraryFxColumn ()
virtual TXshMeshColumn * getMeshColumn ()
virtual int getMaxFrame () const =0
virtual TXshColumn * clone () const =0
bool isCamstandVisible () const
void setCamstandVisible (bool on)
UCHAR getOpacity () const
void setOpacity (UCHAR val)
bool isPreviewVisible () const
void setPreviewVisible (bool on)
bool isLocked () const
void lock (bool on)
bool isMask () const
void setIsMask (bool on)
virtual bool isEmpty () const
virtual TRaster32P getIcon ()
virtual bool isCellEmpty (int row) const =0
virtual bool getLevelRange (int row, int &r0, int &r1) const =0
virtual int getRange (int &r0, int &r1) const
virtual void setXsheet (TXsheet *xsheet)
TXsheet * getXsheet () const
virtual TFx * getFx () const
virtual bool isRendered () const
virtual bool isControl () const
int getColorTag () const
void setColorTag (int colorTag)
FilterColor getFilterColorId () const
void setFilterColorId (FilterColor id)
TPixel32 getFilterColor ()
void resetColumnProperties ()
Public Member Functions inherited from TColumnHeader
int getIndex () const
int getPos () const
int getX0 () const
int getX1 () const
void getCoords (int &x0, int &x1) const
int getWidth () const
bool inColumnsSet () const
Public Member Functions inherited from TSmartObject
TSmartObject (ClassCode classCode)
void addRef ()
void release ()
TINT32 getRefCount () const
Public Member Functions inherited from TPersist
virtual void loadData (TIStream &is)=0
virtual void saveData (TOStream &os)=0
std::string getStreamTag () const
virtual const TPersistDeclaration * getDeclaration () const =0
Additional Inherited Members
Public Types inherited from TXshColumn
enum FilterColor {
FilterNone = 0 , FilterRed , FilterGreen , FilterBlue ,
FilterDarkYellow , FilterDarkCyan , FilterDarkMagenta , FilterAmount
}
enum ColumnType {
eLevelType = 0 , eSoundType , eSoundTextType , eZeraryFxType ,
ePaletteType , eMeshType
}
Public Types inherited from TSmartObject
typedef short ClassCode
Public Types inherited from TPersist
typedef TPersist * CreateProc()
Static Public Member Functions inherited from TXshColumn
static ColumnType toColumnType (int levelType)
Returns the column type used to store levels of the specified type.
static TXshColumn * createEmpty (int colType)
Creates an empty TXshColumn of the specified column type.
static QPair< QString, TPixel32 > getFilterInfo (FilterColor key)
static void initColorFilters ()
Static Public Member Functions inherited from TSmartObject
static TINT32 getInstanceCount (ClassCode code)
Static Public Member Functions inherited from TPersist
static void declare (CreateProc *)
static TPersist * create (const std::string &name)
Protected Types inherited from TXshColumn
enum {
eCamstandVisible = 0x1 , ePreviewVisible = 0x2 , eLocked = 0x8 , eMasked = 0x10 ,
eCamstandTransparent43 = 0x20
}
Protected Member Functions inherited from TXshColumn
void setStatusWord (int status)
int getStatusWord () const
Protected Attributes inherited from TXshCellColumn
std::vector< TXshCell > m_cells
int m_first
QMap< int, int > m_cellMarkIds
Protected Attributes inherited from TXshColumn
TRaster32P m_icon
Detailed Description
The TXshSoundTextColumn class provides a sound column in xsheet and allows its management through cell concept.
Inherits TXshCellColumn.
Constructor & Destructor Documentation
TXshSoundTextColumn()
TXshSoundTextColumn::TXshSoundTextColumn ()
{}
~TXshSoundTextColumn()
TXshSoundTextColumn::~TXshSoundTextColumn ()
{}
Member Function Documentation
canSetCell()
bool TXshSoundTextColumn::canSetCell (const TXshCell & cell) const override virtual
Implements TXshCellColumn.
{
  return cell.isEmpty() || cell.m_level->getSoundTextLevel() != 0;
}
clone()
TXshColumn * TXshSoundTextColumn::clone () const override virtual
Implements TXshColumn.
{
  TXshSoundTextColumn *column = new TXshSoundTextColumn();
  column->setXsheet(getXsheet());
  column->setStatusWord(getStatusWord());
  column->m_cells = m_cells;
  column->m_first = m_first;
  return column;
}
createSoundTextLevel()
void TXshSoundTextColumn::createSoundTextLevel (int row, QList< QString > textList)
{
  TXshSoundTextLevel *level = new TXshSoundTextLevel();
  level->setType(SND_TXT_XSHLEVEL);
  TXshCell cell;
  for (int i = 0; i < textList.size(); i++, row++) {
    QString str     = textList.at(i);
    QString precStr = (i > 0) ? level->getFrameText(i - 1) : QString();
    if (str == QString("<none>")) {
      if (i > 0) {
        setCell(row, cell);
        continue;
      } else
        str = QString();
    }
    level->setFrameText(i, str);
    TFrameId fid(i + 1);
    cell = TXshCell(level, fid);
    setCell(row, cell);
  }
}
getColumnType()
TXshColumn::ColumnType TXshSoundTextColumn::getColumnType () const override virtual
Implements TXshColumn.
{
  return eSoundTextType;
}
getSoundTextColumn()
TXshSoundTextColumn * TXshSoundTextColumn::getSoundTextColumn () inline override virtual
Reimplemented from TXshColumn.
{ return this; }
loadData()
void TXshSoundTextColumn::loadData (TIStream & is) override virtual
 This is a pure virtual function and must be overridden with a method
that implements the object loading from a stream (i.e take the object's features from a formatted data stream). For example the TStageObject class use his implementation to take the values of the parameters that characterizes a stage object as name, coordinates, etc... from a file. is is an input file stream
Implements TPersist.
{
  std::string tagName;
  while (is.openChild(tagName)) {
    if (tagName == "cells") {
      while (is.openChild(tagName)) {
        if (tagName == "cell") {
          TPersist *p             = 0;
          std::string rowRangeStr = "1";
          int fidNumber           = 1;
          TFilePath path;
          is >> rowRangeStr >> fidNumber >> p;
          TXshLevel *xshLevel = dynamic_cast<TXshLevel *>(p);
          TXshCell cell(xshLevel, TFrameId(fidNumber));
          QString _rowRangeStr = QString::fromStdString(rowRangeStr);
          QStringList rows     = _rowRangeStr.split('-');
          if (rows.size() == 1)
            setCell(rows[0].toInt(), cell);
          else if (rows.size() == 2) {
            for (int r = rows[0].toInt(); r <= rows[1].toInt(); r++)
              setCell(r, cell);
          }
        } else
          throw TException("TXshLevelColumn, unknown tag(2): " + tagName);
        is.closeChild();
      }
    } else if (loadCellMarks(tagName, is)) {
      // do nothing
    } else
      throw TException("TXshLevelColumn, unknown tag: " + tagName);
    is.closeChild();
  }
}
References TIStream::closeChild(), TIStream::openChild(), and TXshCellColumn::setCell().
saveData()
void TXshSoundTextColumn::saveData (TOStream & os) override virtual
 This is a pure virtual function and must be overridden with a method
that implements the object saving to a data stream (i.e put the object's features on a formatted data stream). For example the TStageObject class use his implementation to save the values of the parameters that characterizes a stage object as name, coordinates, etc... on a file os is an output file stream.
Implements TPersist.
{
  int r0, r1;
  if (getRange(r0, r1)) {
    os.openChild("cells");
    TXshCell prevCell;
    int fromR = r0;
    for (int r = r0; r <= r1; r++) {
      TXshCell cell = getCell(r);
      if (cell != prevCell) {
        if (!prevCell.isEmpty()) {
          int toR      = r - 1;
          TFrameId fid = prevCell.m_frameId;
          if (fromR == toR)
            os.child("cell")
                << toR << fid.getNumber() << prevCell.m_level.getPointer();
          else {
            QString rangeStr = QString("%1-%2").arg(fromR).arg(toR);
            os.child("cell") << rangeStr.toStdString() << fid.getNumber()
                             << prevCell.m_level.getPointer();
          }
        }
        prevCell = cell;
        fromR    = r;
      }
      assert(cell == prevCell);
      if (r == r1) {
        if (!cell.isEmpty()) {
          int toR      = r;
          TFrameId fid = cell.m_frameId;
          if (fromR == toR)
            os.child("cell")
                << toR << fid.getNumber() << cell.m_level.getPointer();
          else {
            QString rangeStr = QString("%1-%2").arg(fromR).arg(toR);
            os.child("cell") << rangeStr.toStdString() << fid.getNumber()
                             << cell.m_level.getPointer();
          }
        }
      }
    }
    os.closeChild();
  }
  // cell marks
  saveCellMarks(os);
}
References TOStream::child(), TOStream::closeChild(), TXshCellColumn::getCell(), TXshCellColumn::getRange(), TXshCell::isEmpty(), and TOStream::openChild().
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/toonz/txshsoundtextcolumn.h
E:/opentoonz/toonz/sources/toonzlib/txshsoundtextcolumn.cpp