opentoonz: FlipBookPool Class Reference
FlipBookPool Class Reference
The FlipBookPool class is used to store used flipbook viewers.
Public Member Functions
void load (const TFilePath &historyPath)
Loads the pool from input history.
void save () const
Saves the content of this flipbook pool.
FlipBook * pop ()
void push (FlipBook *flipbook)
Static Public Member Functions
static FlipBookPool * instance ()
Detailed Description
The FlipBookPool class is used to store used flipbook viewers.
Flipbooks are generally intended as temporary but friendly floating widgets, that gets displayed when a rendered scene or image needs to be shown. Since a user may require that the geometry of a flipbook is to be remembered between rendering tasks - perhaps even between different Toonz sessions - flipbooks are always stored for later use in a FlipBookPool class.
This class implements the basical features to pop a flipbook from the pool or push a used one; plus, it provides the save and load functions for persistent storage between Toonz sessions.
See also
FlipBook class.
Constructor & Destructor Documentation
FlipBookPool()
FlipBookPool::FlipBookPool ()
                           : m_overallFlipCount(0) {
  qRegisterMetaType<ImagePainter::VisualSettings>(
      "ImagePainter::VisualSettings");
}
~FlipBookPool()
FlipBookPool::~FlipBookPool ()
{}
Member Function Documentation
instance()
FlipBookPool * FlipBookPool::instance () static
{
  static FlipBookPool poolInstance;
  return &poolInstance;
}
load()
void FlipBookPool::load (const TFilePath & historyPath)
Loads the pool from input history.
{
  QSettings history(toQString(historyPath), QSettings::IniFormat);
  m_historyPath = historyPath;
  m_pool.clear();
  m_geometryPool.clear();
  m_overallFlipCount = history.value("count").toInt();
  history.beginGroup("flipbooks");
  QStringList flipBooks(history.childGroups());
  QStringList::iterator it;
  for (it = flipBooks.begin(); it != flipBooks.end(); ++it) {
    history.beginGroup(*it);
    // Retrieve flipbook geometry
    QVariant geom = history.value("geometry");
    // Insert geometry
    m_geometryPool.insert(pair<int, QRect>(it->toInt(), geom.toRect()));
    history.endGroup();
  }
  history.endGroup();
}
pop()
FlipBook * FlipBookPool::pop ()
Extracts the first unused flipbook from the flipbook pool. If all known flipbooks are shown, allocates a new flipbook with the first unused flipbook geometry in a geometry pool. Again, if all recorded geometry are used by some existing flipbook, a default geometry is used.
{
  FlipBook *flipbook;
  TPanel *panel;
  TMainWindow *currentRoom = TApp::instance()->getCurrentRoom();
  if (m_pool.empty()) {
    panel = TPanelFactory::createPanel(currentRoom, "FlipBook");
    panel->setFloating(true);
    flipbook = static_cast<FlipBook *>(panel->widget());
    // Set geometry
    static int x = 0, y = 0;
    if (m_geometryPool.empty()) {
      panel->setGeometry(x += 50, y += 50, 400, 300);
      flipbook->setPoolIndex(m_overallFlipCount);
      m_overallFlipCount++;
    } else {
      flipbook->setPoolIndex(m_geometryPool.begin()->first);
      QRect geometry(m_geometryPool.begin()->second);
      panel->setGeometry(geometry);
      if ((geometry & QApplication::desktop()->availableGeometry(panel))
              .isEmpty())
        panel->move(x += 50, y += 50);
      m_geometryPool.erase(m_geometryPool.begin());
    }
  } else {
    flipbook = m_pool.begin()->second;
    panel    = (TPanel *)flipbook->parent();
    m_pool.erase(m_pool.begin());
  }
  // The panel need to be added to currentRoom's layout control.
  currentRoom->addDockWidget(panel);
  panel->raise();
  panel->show();
  return flipbook;
}
References TMainWindow::addDockWidget(), TApp::getCurrentRoom(), TApp::instance(), and TDockWidget::setFloating().
push()
void FlipBookPool::push (FlipBook * flipbook)
{
  m_pool.insert(pair<int, FlipBook *>(flipbook->getPoolIndex(), flipbook));
}
save()
void FlipBookPool::save () const
Saves the content of this flipbook pool.
{
  QSettings history(toQString(m_historyPath), QSettings::IniFormat);
  history.clear();
  history.setValue("count", m_overallFlipCount);
  history.beginGroup("flipbooks");
  std::map<int, FlipBook *>::const_iterator it;
  for (it = m_pool.begin(); it != m_pool.end(); ++it) {
    history.beginGroup(QString::number(it->first));
    TPanel *panel = static_cast<TPanel *>(it->second->parent());
    history.setValue("geometry", panel->geometry());
    history.endGroup();
  }
  std::map<int, QRect>::const_iterator jt;
  for (jt = m_geometryPool.begin(); jt != m_geometryPool.end(); ++jt) {
    history.beginGroup(QString::number(jt->first));
    history.setValue("geometry", jt->second);
    history.endGroup();
  }
  history.endGroup();
}
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/toonz/flipbook.h
E:/opentoonz/toonz/sources/toonz/flipbook.cpp