opentoonz: Previewer Class Reference
Previewer Class Reference final
Classes
class Imp
class Listener
Public Slots
void saveFrame ()
void saveRenderedFrames ()
void update ()
Refreshes all scene frames.
void updateView ()
Limited version of update(), just refreshes the view area.
void onLevelChanged ()
void onFxChanged ()
void onXsheetChanged ()
void onObjectChanged ()
Signals
void activedChanged ()
void startedFrame (TRenderPort::RenderData renderData)
void renderedFrame (TRenderPort::RenderData renderData)
void failedFrame (TRenderPort::RenderData renderData)
Public Member Functions
void addListener (Listener *)
void removeListener (Listener *)
TRasterP getRaster (int frame, bool renderIfNeeded=true) const
bool isFrameReady (int frame) const
Verifica se frame e' nella cache, cioe' se il frame e' disponibile.
bool doSaveRenderedFrames (TFilePath fp)
bool isActive () const
bool isBusy () const
void onChange (const TFxChange &change) override
void onImageChange (TXshLevel *xl, const TFrameId &fid)
void onLevelChange (TXshLevel *xl)
void clear (int frame)
void clear ()
std::vector< UCHAR > & getProgressBarStatus () const
Public Member Functions inherited from TFxObserver
virtual void onChange (const TFxChange &change)=0
virtual void onChange (const TFxPortAdded &change)
virtual void onChange (const TFxPortRemoved &change)
virtual void onChange (const TFxParamAdded &change)
virtual void onChange (const TFxParamRemoved &change)
virtual void onChange (const TFxParamsUnlinked &change)
Static Public Member Functions
static Previewer * instance (bool subcameraPreview=false)
Ritorna l'istanza del Previewer.
static void clearAll ()
static void suspendRendering (bool suspend)
Protected Slots
void onStartedFrame (TRenderPort::RenderData renderData)
void onRenderedFrame (TRenderPort::RenderData renderData)
void onFailedFrame (TRenderPort::RenderData renderData)
Friends
class Imp
Detailed Description
The Previewer class is a singleton which deals with Preview renders of isolated frames. The main purpose of this class, as of Toonz 6.x, is that of managing preview requests coming from Toonz's Scene Viewers; however, it is designed to support requests from a generic Previewer::Listener class. The Previewer is a singleton, meaning that it centralizes requests from many possible listeners in a single collection of previewed frames.
The most important method of the class is getRaster(), which attempts retrieval of a certain frame and, if the frame was not calculated yet, makes the Previewer build it.
The update() slot is provided to refresh the cached information about the entire collection of currently stored frames. Updated frames are recalculated only upon a new getRaster(), in case the previously stored information no more match the current frame description.
The clear() methods make the Previewer erase all stored information about one or all frames, so that the following getRaster() will forcibly recalculate the requested frame.
Member Function Documentation
addListener()
void Previewer::addListener (Listener * listener)
{
  m_imp->m_listeners.insert(listener);
  connect(&listener->m_refreshTimer, SIGNAL(timeout()), this,
          SLOT(updateView()));
}
clear() [1/2]
void Previewer::clear (void)
                      {
  m_imp->remove();
  m_imp->updateAliases();
  m_imp->updateFrameRange();
  m_imp->updateRenderSettings();
  m_imp->updateCamera();
  m_imp->updatePreviewRect();
  m_imp->updateProgressBarStatus();
}
clear() [2/2]
void Previewer::clear (int frame)
{
  m_imp->remove(frame);
  m_imp->updateProgressBarStatus();
}
clearAll()
void Previewer::clearAll () static
{
  Previewer::instance(false)->clear();
  Previewer::instance(true)->clear();
}
doSaveRenderedFrames()
bool Previewer::doSaveRenderedFrames (TFilePath fp)
{
  return m_imp->doSaveRenderedFrames(fp);
}
getProgressBarStatus()
std::vector< UCHAR > & Previewer::getProgressBarStatus () const
{
  return m_imp->m_pbStatus;
}
getRaster()
TRasterP Previewer::getRaster (int frame, bool renderIfNeeded = true) const
Restituisce un puntatore al raster randerizzato se il frame e' disponibile, altrimenti comincia a calcolarlo
{
  if (frame < 0) return TRasterP();
  std::map<int, Imp::FrameInfo>::iterator it = m_imp->m_frames.find(frame);
  if (it != m_imp->m_frames.end()) {
    if (frame < m_imp->m_pbStatus.size()) {
      if (m_imp->m_pbStatus[frame] == FlipSlider::PBFrameFinished ||
          !renderIfNeeded) {
        std::string str = m_imp->m_cachePrefix + std::to_string(frame);
        TRasterImageP rimg =
            (TRasterImageP)TImageCache::instance()->get(str, false);
        if (rimg) {
          TRasterP ras = rimg->getRaster();
          assert((TRaster32P)ras || (TRaster64P)ras);
          return ras;
        } else
          // Weird case - the frame was declared rendered, but no raster is
          // available...
          return TRasterP();
      } else {
        // Calculate the frame if it was not yet started
        if (m_imp->m_pbStatus[frame] == FlipSlider::PBFrameNotStarted)
          m_imp->refreshFrame(frame);
      }
    }
    // Retrieve the cached image, if any
    std::string str = m_imp->m_cachePrefix + std::to_string(frame);
    TRasterImageP rimg =
        (TRasterImageP)TImageCache::instance()->get(str, false);
    if (rimg) {
      TRasterP ras = rimg->getRaster();
      assert((TRaster32P)ras || (TRaster64P)ras);
      return ras;
    } else
      return TRasterP();
  } else {
    // Just schedule the frame for calculation, and return a void raster ptr
    if (renderIfNeeded) m_imp->refreshFrame(frame);
    return TRasterP();
  }
}
References TImageCache::get().
instance()
Previewer * Previewer::instance (bool subcameraPreview = false) static
Ritorna l'istanza del Previewer.
{
  static Previewer _instance(false);
  static Previewer _instanceSC(true);
  return subcameraPreview ? &_instanceSC : &_instance;
}
Referenced by PreviewSubCameraManager::deleteSubCamera().
isActive()
bool Previewer::isActive () const
{ return !m_imp->m_listeners.empty(); }
isBusy()
bool Previewer::isBusy () const
{
  return !m_imp->m_listeners.empty() && m_imp->m_computingFrameCount > 0;
}
isFrameReady()
bool Previewer::isFrameReady (int frame) const
Verifica se frame e' nella cache, cioe' se il frame e' disponibile.
{
  if (frame < 0 || frame >= (int)m_imp->m_pbStatus.size()) return false;
  return m_imp->m_pbStatus[frame] == FlipSlider::PBFrameFinished;
}
onChange()
void Previewer::onChange (const TFxChange & change) override virtual
Implements TFxObserver.
{ onObjectChanged(); }
onFailedFrame
void Previewer::onFailedFrame (TRenderPort::RenderData renderData) protected slot
{
  m_imp->doOnRenderRasterFailed(renderData);
}
onFxChanged
void Previewer::onFxChanged () slot
{
  m_imp->updateAliases();
  m_imp->updateProgressBarStatus();
  m_imp->notifyUpdate();
}
onImageChange()
void Previewer::onImageChange (TXshLevel * xl, const TFrameId & fid)
Richiama IMP::invalidateFrames(string aliasKeyframe) per aggiornare il frame fid.
{
  TFilePath fp             = xl->getPath().withFrame(fid);
  std::string levelKeyword = ::to_string(fp);
  // Inform the cache managers of level invalidation
  if (!m_imp->m_subcamera)
    TPassiveCacheManager::instance()->invalidateLevel(levelKeyword);
  m_imp->updateAliasKeyword(levelKeyword);
}
References TXshLevel::getPath(), and TFilePath::withFrame().
onLevelChange()
void Previewer::onLevelChange (TXshLevel * xl)
{
  TFilePath fp             = xl->getPath();
  std::string levelKeyword = ::to_string(fp);
  // Inform the cache managers of level invalidation
  if (!m_imp->m_subcamera)
    TPassiveCacheManager::instance()->invalidateLevel(levelKeyword);
  m_imp->updateAliasKeyword(levelKeyword);
  m_imp->updateProgressBarStatus();
  m_imp->notifyUpdate();
}
onLevelChanged
void Previewer::onLevelChanged () slot
{
  TXshLevel *xl = TApp::instance()->getCurrentLevel()->getLevel();
  if (!xl) return;
  std::string levelKeyword;
  TFilePath fp = xl->getPath();
  levelKeyword = ::to_string(fp.withType(""));
  // Inform the cache managers of level invalidation
  if (!m_imp->m_subcamera)
    TPassiveCacheManager::instance()->invalidateLevel(levelKeyword);
  m_imp->updateAliasKeyword(levelKeyword);
  m_imp->updateProgressBarStatus();
  // Seems that the scene viewer does not update in this case...
  m_imp->notifyUpdate();
}
onObjectChanged
void Previewer::onObjectChanged () slot
{
  m_imp->updateAliases();
  m_imp->updateProgressBarStatus();
  m_imp->notifyUpdate();
}
onRenderedFrame
void Previewer::onRenderedFrame (TRenderPort::RenderData renderData) protected slot
{
  m_imp->doOnRenderRasterCompleted(renderData);
}
onStartedFrame
void Previewer::onStartedFrame (TRenderPort::RenderData renderData) protected slot
{
  // Invoke the corresponding function. This happens in the MAIN THREAD
  m_imp->doOnRenderRasterStarted(renderData);
}
onXsheetChanged
void Previewer::onXsheetChanged () slot
{
  m_imp->updateRenderSettings();
  m_imp->updateCamera();
  m_imp->updateFrameRange();
  m_imp->updateAliases();
  m_imp->updateProgressBarStatus();
  m_imp->notifyUpdate();
}
removeListener()
void Previewer::removeListener (Listener * listener)
{
  m_imp->m_listeners.erase(listener);
  disconnect(&listener->m_refreshTimer, SIGNAL(timeout()), this,
             SLOT(updateView()));
  if (m_imp->m_listeners.empty()) {
    m_imp->m_renderer.stopRendering(false);
    // Release all used context names
    std::string prefix("P");
    TPassiveCacheManager::instance()->releaseContextNamesWithPrefix(
        prefix + (m_imp->m_subcamera ? "SC" : "FU"));
  }
}
saveFrame
void Previewer::saveFrame () slot
{ m_imp->saveFrame(); }
saveRenderedFrames
void Previewer::saveRenderedFrames () slot
{
  if (TApp::instance()->getCurrentXsheet()->getXsheet()->getFrameCount() == 0) {
    info(QObject::tr("No frame to save!"));
    return;
  }
  if (m_imp->m_currentFrameToSave != 0) {
    info(QObject::tr("Already saving!"));
    return;
  }
  static SavePreviewedPopup *savePopup = 0;
  if (!savePopup) savePopup = new SavePreviewedPopup;
  savePopup->setPreview(this);
  TFilePath outpath = TApp::instance()
                          ->getCurrentScene()
                          ->getScene()
                          ->getProperties()
                          ->getOutputProperties()
                          ->getPath();
  savePopup->setFolder(outpath.getParentDir());
  TFilePath name = outpath.withoutParentDir();
  savePopup->setFilename(
      name.getName() == ""
          ? name.withName(
                TApp::instance()->getCurrentScene()->getScene()->getSceneName())
          : name);
  savePopup->show();
  savePopup->raise();
  savePopup->activateWindow();
}
suspendRendering()
void Previewer::suspendRendering (bool suspend) static
The suspendRendering method allows suspension of the previewer's rendering activity for safety purposes, typically related to the fact that no rendering process should actually be performed as the underlying scene is about to change or being destroyed. Upon suspension, further rendering requests are silently rejected - and currently active ones are canceled and waited until they are no longer active. NOTE: This method is currently static declared, since the Previewer must be be instanced only after a consistent scene has been initialized. This method is allowed to bypass such limitation.
{
  suspendedRendering = suspend;
  if (suspend && previewerInstance)
    previewerInstance->m_imp->m_renderer.stopRendering(true);
  if (suspend && previewerInstanceSC)
    previewerInstanceSC->m_imp->m_renderer.stopRendering(true);
}
update
void Previewer::update () slot
Refreshes all scene frames.
                       {
  if (m_imp->m_listeners.empty()) return;
  m_imp->updateAliases();
  m_imp->updateFrameRange();
  m_imp->updateRenderSettings();
  m_imp->updateCamera();
  m_imp->updatePreviewRect();
  m_imp->updateProgressBarStatus();
  m_imp->notifyUpdate();
}
updateView
void Previewer::updateView () slot
Limited version of update(), just refreshes the view area.
{
  if (m_imp->m_listeners.empty()) return;
  m_imp->updateFrameRange();
  m_imp->updateRenderSettings();
  m_imp->updateCamera();
  m_imp->updatePreviewRect();
  m_imp->updateProgressBarStatus();
  m_imp->notifyUpdate();
}
Referenced by PreviewSubCameraManager::deleteSubCamera().
Friends And Related Function Documentation
Imp
friend class Imp friend
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/toonz/previewer.h
E:/opentoonz/toonz/sources/toonz/previewer.cpp