opentoonz: TProject Class Reference
TProject Class Reference final
Define and handle a toonz project.
#include <tproject.h>
Public Member Functions
TFilePath getName () const
TFilePath getProjectPath () const
TFilePath getProjectFolder () const
void setFolder (std::string name, TFilePath path)
void setFolder (std::string name)
int getFolderCount () const
Returns the number of the folders contained in the project folder.
std::string getFolderName (int index) const
Returns the name of the folder indexed with index.
int getFolderIndex (std::string folderName) const
bool isConstantFolder (int index) const
TFilePath getFolder (int index) const
TFilePath getFolder (std::string name, bool absolute=false) const
TFilePath getScenesPath () const
TFilePath decode (TFilePath fp) const
bool isCurrent () const
void setSceneProperties (const TSceneProperties &sprop)
const TSceneProperties & getSceneProperties () const
FilePathProperties * getFilePathProperties () const
void setUseScenePath (std::string folderName, bool on)
bool getUseScenePath (std::string folderName) const
int getFolderIndexFromPath (const TFilePath &fp)
std::wstring getFolderNameFromPath (const TFilePath &fp)
bool save (const TFilePath &projectPath)
bool save ()
void load (const TFilePath &projectPath)
Public Member Functions inherited from TSmartObject
TSmartObject (ClassCode classCode)
void addRef ()
void release ()
TINT32 getRefCount () const
Static Public Member Functions
static bool isAProjectPath (const TFilePath &fp)
Static Public Member Functions inherited from TSmartObject
static TINT32 getInstanceCount (ClassCode code)
Static Public Attributes
static const std::string Inputs = "inputs"
static const std::string Drawings = "drawings"
static const std::string Scenes = "scenes"
static const std::string Extras = "extras"
static const std::string Outputs = "outputs"
static const std::string Scripts = "scripts"
static const std::string Palettes = "palettes"
static const TFilePath SandboxProjectName
Default project name.
Additional Inherited Members
Public Types inherited from TSmartObject
typedef short ClassCode
Detailed Description
Define and handle a toonz project.
A toonz project is identified by a project name that matches a folder with the same name in the project root.
The project folder can contains saveral other folders. By default, five folders are created: Inputs, Drawings, Scenes, Extras and Outputs. Each of this folders can be renamed using the setFolder(string name, TFilePath path) method. Usually, the name parameter is chosen from inputs, drawings, scenes, extras and outputs; the path parameter contains the folder that can have a different name from them. All association between names and folder are kept in a mapping.
A folder of a project can be constant or scene dependent. A constant folder is used by every scene created in the project to save or load data. A scene dependent folder is used only by the scene from which the folder depends. A scene dependent folder contains the string "$scene" in its path.
 \code
 e.g.
 Scene path: "...\\prodA\\episode1\\scenes\\sceneA.tzn"
 Drawings scene dependent folder:
"...\\prodA\\episode1\\$scene\\drawings" Drawings folder path: "...\\prodA\\episode1\\SceneA\\drawings"
By default, from the toonz installation, exist always a toonz project called "sandbox".
See also
TProjectManager, TSceneProperties.
Constructor & Destructor Documentation
TProject()
TProject::TProject ()
    : m_name()
    , m_path()
    , m_sprop(new TSceneProperties())
    , m_fpProp(new FilePathProperties()) {}
~TProject()
TProject::~TProject ()
                    {
  delete m_sprop;
  delete m_fpProp;
}
Member Function Documentation
decode()
TFilePath TProject::decode (TFilePath fp) const
Returns the absolute path of fp. If fp contains "$project", replaces it with the name of the project.
Note
the returned path can contain "$scene"
{
  for (;;) {
    wstring fpstr = fp.getWideString();
    int j         = fpstr.find(L"$project");
    if (j == (int)wstring::npos) break;
    fpstr.replace(j, 8, getName().getWideString());
    fp = TFilePath(fpstr);
  }
  return makeAbsolute(getProjectFolder(), fp);
}
References getName(), and getProjectFolder().
Referenced by getFolderIndexFromPath(), and save().
getFilePathProperties()
FilePathProperties * TProject::getFilePathProperties () const inline
{ return m_fpProp; }
getFolder()
TFilePath TProject::getFolder (int index) const
Returns the path of the folder indexed with index.
Returns TFilePath() if there isn't a folder indexed with index.
Note
The returned path could be a relative path.
{
  if (0 <= index && index < (int)m_folderNames.size())
    return getFolder(m_folderNames[index]);
  else
    return TFilePath();
}
References getFolder().
Referenced by ToonzScene::decodeFilePath(), getFolder(), getFolderIndexFromPath(), getFolderNameFromPath(), getScenesPath(), isConstantFolder(), and save().
getFolderCount()
int TProject::getFolderCount () const
Returns the number of the folders contained in the project folder.
{ return m_folders.size(); }
Referenced by ToonzScene::codeFilePath(), ToonzScene::decodeFilePath(), getFolderIndexFromPath(), ToonzScene::isExternPath(), and save().
getFolderIndex()
int TProject::getFolderIndex (std::string folderName) const
Returns the index of the folder named with folderName.
If a folder named with folderName doesn't exist, return -1.
{
  std::vector<std::string>::const_iterator it;
  it = std::find(m_folderNames.begin(), m_folderNames.end(), name);
  if (it == m_folderNames.end()) return -1;
  return std::distance(it, m_folderNames.begin());
}
getFolderIndexFromPath()
int TProject::getFolderIndexFromPath (const TFilePath & folderDir)
Returns the index of the folder specified in the path folderDir. Returns -1 if folderDir isn't a folder of the project.
{
  TFilePath scenePath          = decode(getFolder(Scenes));
  bool sceneDependentScenePath = false;
  if (scenePath.getName().find("$scene") != string::npos) {
    scenePath               = scenePath.getParentDir();
    sceneDependentScenePath = true;
  }
  int folderIndex;
  for (folderIndex = 0; folderIndex < getFolderCount(); folderIndex++)
    if (isConstantFolder(folderIndex)) {
      TFilePath fp = decode(getFolder(folderIndex));
      if (fp == folderDir) return folderIndex;
    } else {
      TFilePath fp = decode(getFolder(folderIndex));
      wstring a    = fp.getWideString();
      wstring b    = folderDir.getWideString();
      int alen     = a.length();
      int blen     = b.length();
      int i        = a.find(L"$scene");
      assert(i != (int)wstring::npos);
      if (i == (int)wstring::npos) continue;
      int j = i + 1;
      while (j < alen && isalnum(a[j])) j++;
      // a.substr(i,j-i) == "$scenexxxx"
      int k = j + blen - alen;
      if (!(0 <= i && i < k && k <= blen)) continue;
      assert(i < blen);
      if (i > 0 && a.substr(0, i) != b.substr(0, i)) continue;
      if (k < blen && (j >= alen || a.substr(j) != b.substr(k))) continue;
      wstring v = b.substr(i, k - i);
      TFilePath scene(v + L".tnz");
      if (sceneDependentScenePath)
        scene = scenePath + scene.getWideName() + scene;
      else
        scene = scenePath + scene;
      if (TFileStatus(scene).doesExist()) return folderIndex;
    }
  return -1;
}
References decode(), getFolder(), getFolderCount(), TFilePath::getName(), TFilePath::getParentDir(), isConstantFolder(), and Scenes.
Referenced by getFolderNameFromPath().
getFolderName()
string TProject::getFolderName (int index) const
Returns the name of the folder indexed with index.
{
  if (0 <= index && index < (int)m_folderNames.size())
    return m_folderNames[index];
  else
    return "";
}
Referenced by ToonzScene::codeFilePath(), getFolderNameFromPath(), ToonzScene::isExternPath(), and save().
getFolderNameFromPath()
wstring TProject::getFolderNameFromPath (const TFilePath & folderDir)
Returns the folder's name of the specified TFilePath folderDir.
Returns the empty string if folderDir isn't a folder of the project.
{
  int index = getFolderIndexFromPath(folderDir);
  if (index < 0) return L"";
  if (getFolder(index).isAbsolute())
    return ::to_wstring("+" + getFolderName(index));
  else
    return folderDir.getWideName();
}
References getFolder(), getFolderIndexFromPath(), and getFolderName().
getName()
TFilePath TProject::getName () const inline
Returns the name of the project.
e.g. "prodA\\episode1"
{ return m_name; }
Referenced by decode().
getProjectFolder()
TFilePath TProject::getProjectFolder () const inline
Returns the project folder path. It is an absolute path.
e.g. "prodA\\episode1" -> "...\\prodA\\episode1\\"
{ return m_path.getParentDir(); }
References TFilePath::getParentDir().
Referenced by decode(), ToonzScene::decodeFilePath(), and getScenesPath().
getProjectPath()
TFilePath TProject::getProjectPath () const inline
Returns the path of the project. It is an absolute path.
e.g. "prodA\\episode1" -> "...\\prodA\\episode1\\episode1_prj.xml"
{ return m_path; }
Referenced by isCurrent().
getSceneProperties()
const TSceneProperties & TProject::getSceneProperties () const inline
Returns the scene properties of the project.
See also
TSceneProperties
{ return *m_sprop; }
Referenced by TProjectManager::initializeScene(), and save().
getScenesPath()
TFilePath TProject::getScenesPath () const
Returns the path of the Scene folder.
The Scene folder contains all the saved scene. The returned path is an absolute path.
{
  TFilePath scenes = getFolder(Scenes);
  return makeAbsolute(getProjectFolder(), scenes);
}
References getFolder(), getProjectFolder(), and Scenes.
getUseScenePath()
bool TProject::getUseScenePath (std::string folderName) const
{
  std::map<std::string, bool>::const_iterator it;
  it = m_useScenePathFlags.find(folderName);
  return it != m_useScenePathFlags.end() ? it->second : false;
}
isAProjectPath()
bool TProject::isAProjectPath (const TFilePath & fp) static
Returns true if the specified path is a project path.
A project path must be absolute, must be an xml file and must have the name of the parent root with either one of the version-dependent suffixes "_prj*".
     e.g. "C:\\Toonz 5.2 stuff\\projects\\prodA\\episode1\\episode1_prj.xml"
is a project path.
{
  if (fp.isAbsolute() && fp.getType() == "xml") {
    const std::wstring &fpName = fp.getWideName();
    for (int i = 0; i < prjSuffixCount; ++i)
      if (fpName.find(prjSuffix[i]) != std::wstring::npos) return true;
  }
  return false;
}
References TFilePath::getType().
Referenced by TProjectManager::getCurrentProject(), TProjectManager::getCurrentProjectPath(), TProjectManager::getProjectPathByName(), load(), TProjectManager::loadSceneProject(), TProjectManager::projectNameToProjectPath(), save(), and TProjectManager::setCurrentProjectPath().
isConstantFolder()
bool TProject::isConstantFolder (int index) const
Returns true if the folder indexed with index isn't scene dependent.
A scene dependent folder is a folder containing "$scene" in its path.
{
  TFilePath fp = getFolder(index);
  return fp.getWideString().find(L"$scene") == wstring::npos;
}
References getFolder().
Referenced by getFolderIndexFromPath(), and save().
isCurrent()
bool TProject::isCurrent () const
Returns true if this project is the current project. Uses TProjectManager.
See also
TProjectManager
{
  TFilePath currentProjectPath =
      TProjectManager::instance()->getCurrentProjectPath();
  if (getProjectPath() == currentProjectPath)
    return true;
  else
    return getLatestVersionProjectPath(currentProjectPath) ==
           getLatestVersionProjectPath(getProjectPath());
}
References TProjectManager::getCurrentProjectPath(), getProjectPath(), and TProjectManager::instance().
load()
void TProject::load (const TFilePath & projectPath)
Loads the project specified in projectPath.
projectPath must be an absolute path.
{
  assert(isAProjectPath(projectPath));
  TFilePath latestProjectPath = getLatestVersionProjectPath(projectPath);
  TFilePath inputProjectPath  = searchProjectPath(projectPath.getParentDir());
  TProjectManager *pm = TProjectManager::instance();
  m_name              = pm->projectPathToProjectName(latestProjectPath);
  m_path              = latestProjectPath;
  m_folderNames.clear();
  m_folders.clear();
  m_useScenePathFlags.clear();
  delete m_sprop;
  m_sprop = new TSceneProperties();
  // Read the project
  TIStream is(inputProjectPath);
  if (!is) return;
  string tagName;
  if (!is.matchTag(tagName) || tagName != "project") return;
  while (is.matchTag(tagName)) {
    if (tagName == "folders") {
      while (is.matchTag(tagName)) {
        if (tagName == "folder") {
          string name = is.getTagAttribute("name");
          TFilePath path(is.getTagAttribute("path"));
          setFolder(name, path);
          string useScenePath = is.getTagAttribute("useScenePath");
          setUseScenePath(name, useScenePath == "yes");
        } else
          throw TException("expected <folder>");
      }
      is.matchEndTag();
    } else if (tagName == "version") {
      int major, minor;
      is >> major >> minor;
      is.setVersion(VersionNumber(major, minor));
      is.matchEndTag();
    } else if (tagName == "sceneProperties") {
      TSceneProperties sprop;
      try {
        sprop.loadData(is, true);
      } catch (...) {
      }
      setSceneProperties(sprop);
      is.matchEndTag();
    } else if (tagName == "filePathProperties") {
      m_fpProp->loadData(is);
      is.matchEndTag();
    }
  }
}
References TFilePath::getParentDir(), TIStream::getTagAttribute(), TProjectManager::instance(), isAProjectPath(), TSceneProperties::loadData(), TIStream::matchEndTag(), TIStream::matchTag(), TProjectManager::projectPathToProjectName(), setSceneProperties(), and TIStream::setVersion().
Referenced by TProjectManager::initializeScene(), and TProjectManager::loadSceneProject().
save() [1/2]
bool TProject::save ()
Saves the project. Is equivalent to save(getProjectPath()). The project is saved as a xml file.
Uses TProjectManager and TOStream.
Note
Exceptions can be thrown.
See also
TProjectManager and TOStream.
{ return save(m_path); }
References save().
Referenced by save().
save() [2/2]
bool TProject::save (const TFilePath & projectPath)
Saves the project in the specified path. The TfilePath fp must be an absolute path. The project is saved as a xml file.
Uses TProjectManager and TOStream.
Note
Exceptions can be thrown.
See also
TProjectManager and TOStream.
{
  assert(isAProjectPath(projectPath));
  TProjectManager *pm     = TProjectManager::instance();
  m_name                  = pm->projectPathToProjectName(projectPath);
  m_path                  = getLatestVersionProjectPath(projectPath);
  TFilePath projectFolder = projectPath.getParentDir();
  if (!TFileStatus(projectFolder).doesExist()) {
    try {
      TSystem::mkDir(projectFolder);
    } catch (...) {
      return false;
    }
  }
  TFilePath sceneFolder    = decode(getFolder(TProject::Scenes));
  TFilePath scenesDescPath = sceneFolder + "scenes.xml";
  TFileStatus fs(projectPath);
  if (fs.doesExist() && !fs.isWritable()) {
    throw TSystemException(
        projectPath,
        "Cannot save the project settings. The file is read-only.");
    return false;
  }
  TFileStatus fs2(scenesDescPath);
  if (fs2.doesExist() && !fs2.isWritable()) {
    throw TSystemException(
        projectPath,
        "Cannot save the project settings. The scenes file is read-only.");
    return false;
  }
  TOStream os(m_path);
  os.openChild("project");
  os.openChild("version");
  os << 70 << 1;    // Standard version signature:
  os.closeChild();  //   <Major Toonz version number * 10>.<Major version
                    //   advancement>
  os.openChild("folders");
  int i = 0;
  for (i = 0; i < getFolderCount(); i++) {
    TFilePath folderRelativePath = getFolder(i);
    if (folderRelativePath == TFilePath()) continue;
    std::map<std::string, string> attr;
    string folderName = getFolderName(i);
    attr["name"]      = folderName;
    attr["path"]      = ::to_string(folderRelativePath);  // escape()
    if (getUseScenePath(folderName)) attr["useScenePath"] = "yes";
    os.openCloseChild("folder", attr);
  }
  os.closeChild();
  os.openChild("sceneProperties");
  getSceneProperties().saveData(os);
  os.closeChild();
  if (!getFilePathProperties()->isDefault()) {
    os.openChild("filePathProperties");
    getFilePathProperties()->saveData(os);
    os.closeChild();
  }
  os.closeChild();
  // crea (se necessario) le directory relative ai vari folder
  for (i = 0; i < getFolderCount(); i++)
    if (isConstantFolder(i)) {
      TFilePath fp = getFolder(i);
      if (fp == TFilePath()) continue;
      fp = decode(fp);
      // if(!fp.isAbsolute()) fp = projectFolder + fp;
      if (!TFileStatus(fp).doesExist()) {
        try {
          TSystem::mkDir(fp);
        } catch (...) {
        }
      }
    }
  /*-- +scenes Project Folderscenes.xml --*/
  std::vector<std::string> foldernames;
  pm->getFolderNames(foldernames);
  for (int f = 0; f < foldernames.size(); f++) {
    TFilePath folderpath = decode(getFolder(foldernames.at(f)));
    if (folderpath.isEmpty() || !isConstantFolder(f)) continue;
    TFilePath xmlPath = folderpath + "scenes.xml";
    TFileStatus xmlfs(xmlPath);
    if (xmlfs.doesExist() && !xmlfs.isWritable()) continue;
    TFilePath relativeProjectFolder =
        makeRelative(folderpath, m_path.getParentDir());
    TOStream os2(xmlPath);
    std::map<std::string, string> attr;
    attr["type"] = "projectFolder";
    os2.openChild("parentProject", attr);
    os2 << relativeProjectFolder;
    os2.closeChild();
  }
  // The project has been successfully saved. In case there are other
  // project files from older Toonz project versions, those files are
  // renamed so that older Toonz versions can no longer 'see' it.
  if (!isFolderUnderVersionControl(projectFolder))
    hideOlderProjectFiles(projectFolder);
  return true;
}
References TOStream::closeChild(), decode(), getFolder(), getFolderCount(), getFolderName(), TProjectManager::getFolderNames(), TFilePath::getParentDir(), getSceneProperties(), TProjectManager::instance(), isAProjectPath(), isConstantFolder(), TOStream::openChild(), TOStream::openCloseChild(), TProjectManager::projectPathToProjectName(), and Scenes.
Referenced by ExportScenePopup::createNewProject().
setSceneProperties()
void TProject::setSceneProperties (const TSceneProperties & sprop)
Set the scene properties sprop to the project.
See also
TSceneProperties
{
  m_sprop->assign(&sprop);
}
References TSceneProperties::assign().
Referenced by load().
setUseScenePath()
void TProject::setUseScenePath (std::string folderName, bool on)
{
  m_useScenePathFlags[folderName] = on;
}
Member Data Documentation
Drawings
const std::string TProject::Drawings = "drawings" static
Default drawings folder: is used to save all tlv and pli levels.
Referenced by TProjectManager::getFolderNames().
Extras
const std::string TProject::Extras = "extras" static
Default extras folder: is used to save all imported images and levels not pli or tlv.
Referenced by TProjectManager::getFolderNames().
Inputs
const std::string TProject::Inputs = "inputs" static
Default inputs folder: is used to save all scanned immage.
Referenced by TProjectManager::getFolderNames().
Outputs
const std::string TProject::Outputs = "outputs" static
Default outputs folder: is used to save all rendered scenes.
Referenced by TProjectManager::getFolderNames().
Palettes
const std::string TProject::Palettes = "palettes" static
Default palettes folder: is used for color design ()
SandboxProjectName
const TFilePath TProject::SandboxProjectName static
Default project name.
Referenced by TProjectManager::getCurrentProjectPath(), TProjectManager::getProjectPathByName(), TProjectManager::getSandboxProjectPath(), and TProjectManager::projectNameToProjectPath().
Scenes
const std::string TProject::Scenes = "scenes" static
Default scenes folder: is used to save all scenes.
Referenced by ToonzScene::decodeFilePath(), getFolderIndexFromPath(), TProjectManager::getFolderNames(), ToonzScene::getSavePath(), getScenesPath(), and save().
Scripts
const std::string TProject::Scripts = "scripts" static
Default scripts folder: is used to save all the script.
Referenced by TProjectManager::getFolderNames().
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/toonz/tproject.h
E:/opentoonz/toonz/sources/toonzlib/tproject.cpp