opentoonz: TStyleSelection Class Reference
TStyleSelection Class Reference final
Public Member Functions
TStyleSelection (TStyleSelection *styleSelection)
void select (int pageIndex)
void select (int pageIndex, int styleIndexInPage, bool on)
bool isSelected (int pageIndex, int styleIndexInPage) const
bool isPageSelected (int pageIndex) const
bool canHandleStyles ()
void selectNone () override
bool isEmpty () const override
int getStyleCount () const
TPaletteHandle * getPaletteHandle () const
void setPaletteHandle (TPaletteHandle *paletteHandle)
TPalette * getPalette () const
int getPageIndex () const
const std::set< int > & getIndicesInPage () const
void getIndices (std::set< int > &indices) const
void setXsheetHandle (TXsheetHandle *xsheetHandle)
TXsheetHandle * getXsheetHandle () const
void setLevelHandle (TXshLevelHandle *levelHandle)
void cutStyles ()
void copyStyles ()
void pasteStyles ()
void pasteStylesValues (bool pasteName, bool pasteColor=true)
void pasteStylesValue ()
void pasteStylesColor ()
void pasteStylesName ()
void deleteStyles ()
void eraseUnusedStyle ()
void blendStyles ()
void toggleLink ()
void eraseToggleLink ()
void enableCommands () override
void toggleKeyframe (int frame)
void removeLink ()
void getBackOriginalStyle ()
bool hasLinkedStyle ()
TStyleSelection (TStyleSelection *styleSelection)
void select (const TPaletteP &palette, int pageIndex)
void select (const TPaletteP &palette, int pageIndex, int styleIndexInPage, bool on)
bool isSelected (const TPaletteP &palette, int pageIndex, int styleIndexInPage) const
bool isPageSelected (const TPaletteP &palette, int pageIndex) const
void selectNone ()
bool isEmpty () const
int getStyleCount () const
const TPaletteP & getPalette () const
int getPageIndex () const
const std::set< int > & getIndicesInPage () const
void cutStyles ()
void copyStyles ()
void pasteStyles ()
void pasteStylesValue ()
void deleteStyles ()
void blendStyles ()
void toggleLink ()
void enableCommands ()
QByteArray toByteArray () const
Public Member Functions inherited from TSelection
virtual void enableCommands ()
void enableCommand (CommandId cmdId, CommandHandlerInterface *handler)
template<class T >
void enableCommand (T *target, CommandId cmdId, void(T::*method)())
template<class T , typename R >
void enableCommand (T *target, CommandId cmdId, void(T::*method)(R), R value)
void makeCurrent ()
void makeNotCurrent ()
virtual bool isEmpty () const =0
virtual void selectNone ()=0
virtual bool addMenuActions (QMenu *menu)
void addMenuAction (QMenu *menu, CommandId cmdId)
void setView (View *view)
View * getView () const
void notifyView ()
Static Public Member Functions
static QByteArray toByteArray (int pageIndex, const std::set< int > &indicesInPage, const QString paletteGlobalName)
static void fromByteArray (QByteArray &byteArray, int &pageIndex, std::set< int > &indicesInPage, QString &paletteGlobalName)
static const char * getMimeType ()
Static Public Member Functions inherited from TSelection
static TSelection * getCurrent ()
static void setCurrent (TSelection *selection)
Detailed Description
Constructor & Destructor Documentation
TStyleSelection() [1/3]
TStyleSelection::TStyleSelection ()
: m_palette(0), m_pageIndex(-1) {}
TStyleSelection() [2/3]
TStyleSelection::TStyleSelection (TStyleSelection * styleSelection) inline
      : m_paletteHandle(styleSelection->getPaletteHandle())
      , m_pageIndex(styleSelection->getPageIndex())
      , m_styleIndicesInPage(styleSelection->getIndicesInPage()) {}
~TStyleSelection()
TStyleSelection::~TStyleSelection ()
{}
TStyleSelection() [3/3]
TStyleSelection::TStyleSelection (TStyleSelection * styleSelection) inline
      : m_palette(styleSelection->getPalette())
      , m_pageIndex(styleSelection->getPageIndex())
      , m_styleIndicesInPage(styleSelection->getIndicesInPage()) {}
Member Function Documentation
blendStyles()
void TStyleSelection::blendStyles ()
{
  if (!m_palette || m_pageIndex < 0) return;
  int n = m_styleIndicesInPage.size();
  if (n < 2) return;
  TPalette::Page *page = m_palette->getPage(m_pageIndex);
  assert(page);
  std::vector<TColorStyle *> styles;
  std::vector<std::pair<int, TColorStyle *>> oldStyles;
  for (std::set<int>::iterator it = m_styleIndicesInPage.begin();
       it != m_styleIndicesInPage.end(); ++it) {
    TColorStyle *cs = page->getStyle(*it);
    assert(cs);
    styles.push_back(cs);
    oldStyles.push_back(std::pair<int, TColorStyle *>(*it, cs->clone()));
  }
  assert(styles.size() >= 2);
  TPixel32 c0 = styles.front()->getMainColor();
  TPixel32 c1 = styles.back()->getMainColor();
  bool areAllStyleLincked = true;
  int i;
  for (i = 1; i < n - 1; i++) {
    QString gname = QString::fromStdWString(styles[i]->getGlobalName());
    if (!gname.isEmpty() && gname[0] != L'-') continue;
    areAllStyleLincked = false;
    styles[i]->setMainColor(blend(c0, c1, (double)i / (double)(n - 1)));
    styles[i]->invalidateIcon();
  }
  if (areAllStyleLincked) return;
  TApp::instance()->getCurrentPalette()->notifyColorStyleChanged();
  UndoBlendColor *undo =
      new UndoBlendColor(m_palette, m_pageIndex, oldStyles, c0, c1);
  TUndoManager::manager()->add(undo);
}
canHandleStyles()
bool TStyleSelection::canHandleStyles ()
{
  TPalette *palette = getPalette();
  if (!palette) return false;
  TPalette::Page *page = palette->getPage(m_pageIndex);
  if (!page) return false;
  if ((isSelected(m_pageIndex, 0) && page->getStyleId(0) == 0) ||
      (isSelected(m_pageIndex, 1) && page->getStyleId(1) == 1))
    return false;
  return true;
}
copyStyles()
void TStyleSelection::copyStyles ()
{
  if (isEmpty()) return;
  QClipboard *clipboard = QApplication::clipboard();
  QMimeData *oldData    = cloneData(clipboard->mimeData());
  copyStylesWithoutUndo(m_palette, m_pageIndex, &m_styleIndicesInPage);
  QMimeData *newData = cloneData(clipboard->mimeData());
  TUndoManager::manager()->add(new CopyStylesUndo(oldData, newData));
}
cutStyles()
void TStyleSelection::cutStyles ()
{
  if (isEmpty()) return;
  QClipboard *clipboard      = QApplication::clipboard();
  QMimeData *oldData         = cloneData(clipboard->mimeData());
  TStyleSelection *selection = new TStyleSelection(this);
  if (m_pageIndex == 0 &&
      (isSelected(m_palette, 0, 0) || isSelected(m_palette, 0, 1))) {
    MsgBox(CRITICAL, "Can't delete colors #0 and #1");
    return;
  }
  cutStylesWithoutUndo(m_palette, m_pageIndex, &m_styleIndicesInPage);
  TUndoManager::manager()->add(new CutStylesUndo(selection, oldData));
}
deleteStyles()
void TStyleSelection::deleteStyles ()
{
  if (!m_palette || m_pageIndex < 0) return;
  if (m_pageIndex == 0 &&
      (isSelected(m_palette, 0, 0) || isSelected(m_palette, 0, 1))) {
    MsgBox(CRITICAL, "Can't delete colors #0 and #1");
    return;
  }
  StyleData *data = new StyleData();
  std::set<int>::iterator it;
  TPalette::Page *page = m_palette->getPage(m_pageIndex);
  for (it = m_styleIndicesInPage.begin(); it != m_styleIndicesInPage.end();
       ++it) {
    int j       = *it;
    int styleId = page->getStyleId(j);
    if (styleId < 0) continue;
    TColorStyle *style = page->getStyle(j)->clone();
    data->addStyle(styleId, style);
  }
  TStyleSelection *selection = new TStyleSelection(this);
  deleteStylesWithoutUndo(m_palette, m_pageIndex, &m_styleIndicesInPage);
  TUndoManager::manager()->add(new DeleteStylesUndo(selection, data));
}
enableCommands() [1/2]
void TStyleSelection::enableCommands () virtual
Reimplemented from TSelection.
enableCommands() [2/2]
void TStyleSelection::enableCommands () override virtual
Reimplemented from TSelection.
{
  enableCommand(this, MI_Cut, &TStyleSelection::cutStyles);
  enableCommand(this, MI_Copy, &TStyleSelection::copyStyles);
  enableCommand(this, MI_Paste, &TStyleSelection::pasteStyles);
  enableCommand(this, MI_PasteValues, &TStyleSelection::pasteStylesValue);
  enableCommand(this, MI_Clear, &TStyleSelection::deleteStyles);
  enableCommand(this, MI_BlendColors, &TStyleSelection::blendStyles);
}
eraseToggleLink()
void TStyleSelection::eraseToggleLink ()
{
  TPalette *palette = getPalette();
  if (!palette || m_pageIndex < 0) return;
  if (isEmpty() || palette->isLocked()) return;
  int n = m_styleIndicesInPage.size();
  if (n <= 0) return;
  bool currentStyleIsInSelection = false;
  TPalette::Page *page = palette->getPage(m_pageIndex);
  assert(page);
  std::vector<std::pair<int, std::wstring>> oldColorStylesLinked;
  std::vector<std::pair<int, std::wstring>> newColorStylesLinked;
  UndoLinkToStudioPalette *undo =
      new UndoLinkToStudioPalette(m_paletteHandle, m_pageIndex);
  for (std::set<int>::iterator it = m_styleIndicesInPage.begin();
       it != m_styleIndicesInPage.end(); ++it) {
    int index       = *it;
    TColorStyle *cs = page->getStyle(index);
    assert(cs);
    TColorStyle *oldCs = cs->clone();
    std::wstring name  = cs->getGlobalName();
    if (name != L"" && (name[0] == L'-' || name[0] == L'+'))
      cs->setGlobalName(L"");
    undo->setColorStyle(index, oldCs, L"");
    if (*it ==
        palette->getPage(m_pageIndex)->search(m_paletteHandle->getStyleIndex()))
      currentStyleIsInSelection = true;
  }
  m_paletteHandle->notifyColorStyleChanged(false);
  if (currentStyleIsInSelection) m_paletteHandle->notifyColorStyleSwitched();
  palette->setDirtyFlag(true);
  TUndoManager::manager()->add(undo);
}
eraseUnusedStyle()
void TStyleSelection::eraseUnusedStyle ()
{
  std::set<TXshSimpleLevel *> levels;
  int row, column, i, j;
  TPalette *palette = m_paletteHandle->getPalette();
  findPaletteLevels(levels, row, column, palette, m_xsheetHandle->getXsheet());
  // Verifico quali stili sono usati e quali no
  std::map<int, bool> usedStyleIds;
  int pageCount = palette->getPageCount();
  for (auto const level : levels) {
    std::vector<TFrameId> fids;
    level->getFids(fids);
    int m, i, j;
    for (m = 0; m < (int)fids.size(); m++) {
      TImageP image = level->getFrame(fids[m], false);
      if (!image) continue;
      for (i = 0; i < pageCount; i++) {
        TPalette::Page *page = palette->getPage(i);
        assert(page);
        for (j = 0; j < page->getStyleCount(); j++) {
          int styleId = page->getStyleId(j);
          if (m != 0 && usedStyleIds[styleId]) continue;
          if (i == 0 &&
              (j == 0 || j == 1))  // Il primo stile della prima pagina non deve
                                   // essere mai cancellato
          {
            usedStyleIds[styleId] = true;
            continue;
          }
          usedStyleIds[styleId] = isStyleUsed(image, styleId);
        }
      }
    }
  }
  // check if there are styles to be erased
  QMap<int, std::set<int>> styleIndicesInPageMap;
  QString indicesStr;
  int count = 0;
  // Butto gli stili non usati
  for (i = 0; i < pageCount; i++) {
    // Variabili usate per l'undo
    std::set<int> styleIndicesInPage;
    TPalette::Page *page = palette->getPage(i);
    assert(page);
    for (j = 0; j < page->getStyleCount(); j++) {
      int styleId = page->getStyleId(j);
      if (usedStyleIds[styleId]) continue;
      styleIndicesInPage.insert(j);
      if (count < 10) indicesStr.append(QString::number(styleId) + ", ");
      count++;
    }
    if (!styleIndicesInPage.empty())
      styleIndicesInPageMap.insert(i, styleIndicesInPage);
  }
  if (styleIndicesInPageMap.isEmpty()) {
    DVGui::error(QObject::tr("There are no unused styles."));
    return;
  }
  if (count <= 10)
    indicesStr.chop(2);
  else
    indicesStr.append(
        QObject::tr("and %1 more styles.").arg(QString::number(count - 10)));
  // open confirmation popup
  QString question =
      QObject::tr(
          "Erasing unused styles with following indices. Are you sure?\n\n%1")
          .arg(indicesStr);
  int ret =
      DVGui::MsgBox(question, QObject::tr("Erase"), QObject::tr("Cancel"), 0);
  if (ret == 2 || ret == 0) return;
  TUndoManager::manager()->beginBlock();
  QMap<int, std::set<int>>::const_iterator styleMapItr =
      styleIndicesInPageMap.constBegin();
  while (styleMapItr != styleIndicesInPageMap.constEnd()) {
    int pageIndex                    = styleMapItr.key();
    std::set<int> styleIndicesInPage = styleMapItr.value();
    StyleData *data                  = new StyleData();
    TPalette::Page *page             = palette->getPage(pageIndex);
    for (auto indexInPage : styleIndicesInPage) {
      int styleId = page->getStyleId(indexInPage);
      data->addStyle(styleId, page->getStyle(indexInPage)->clone());
    }
    // Cancello gli stili
    std::set<int>::reverse_iterator it;
    for (it = styleIndicesInPage.rbegin(); it != styleIndicesInPage.rend();
         ++it)
      page->removeStyle(*it);
    // Undo
    DeleteStylesUndo *undo = new DeleteStylesUndo(this, data);
    undo->setPageIndex(pageIndex);
    undo->setStyleIndicesInPage(styleIndicesInPage);
    TUndoManager::manager()->add(undo);
    ++styleMapItr;
  }
  TUndoManager::manager()->endBlock();
  m_paletteHandle->setStyleIndex(1);
}
fromByteArray()
void TStyleSelection::fromByteArray (QByteArray & byteArray, int & pageIndex, std::set< int > & indicesInPage, QString & paletteGlobalName) static
{
  QBuffer dataBuffer(&byteArray);
  dataBuffer.open(QIODevice::ReadOnly);
  QDataStream in(&dataBuffer);
  int i, count = 0;
  in >> pageIndex >> count >> paletteGlobalName;
  for (i = 0; i < count; i++) {
    int indexInPage;
    in >> indexInPage;
    indicesInPage.insert(indexInPage);
  }
}
getBackOriginalStyle()
void TStyleSelection::getBackOriginalStyle ()
get the color from the linked style of the studio palette
{
  TPalette *palette = getPalette();
  if (!palette || m_pageIndex < 0) return;
  if (isEmpty() || palette->isLocked()) return;  // 110804 iwasawa
  int n = m_styleIndicesInPage.size();
  if (n <= 0) return;
  TPalette::Page *page = palette->getPage(m_pageIndex);
  assert(page);
  bool somethingChanged = false;
  std::map<std::wstring, TPaletteP> table;
  TUndo *undo = new getBackOriginalStyleUndo(this);
  // for each selected style
  for (std::set<int>::iterator it = m_styleIndicesInPage.begin();
       it != m_styleIndicesInPage.end(); ++it) {
    TColorStyle *cs = page->getStyle(*it);
    assert(cs);
    std::wstring gname = cs->getGlobalName();
    // if the style has no link
    if (gname == L"") continue;
    // Find the palette from the table
    int k = gname.find_first_of(L'-', 1);
    if (k == (int)std::wstring::npos) continue;
    std::wstring paletteId = gname.substr(1, k - 1);
    std::map<std::wstring, TPaletteP>::iterator palIt;
    palIt = table.find(paletteId);
    TPalette *spPalette = 0;
    // If not found in the table, then search for a new studio palette.
    if (palIt == table.end()) {
      spPalette = StudioPalette::instance()->getPalette(paletteId);
      if (!spPalette) continue;
      table[paletteId] = spPalette;
      assert(spPalette->getRefCount() == 1);
    } else
      spPalette = palIt->second.getPointer();
    // j is StyleID
    int j = std::stoi(gname.substr(k + 1));
    if (spPalette && 0 <= j && j < spPalette->getStyleCount()) {
      TColorStyle *spStyle = spPalette->getStyle(j);
      assert(spStyle);
      // edit flag is also copied here
      spStyle = spStyle->clone();
      spStyle->setGlobalName(gname);
      // get the original name from the studio palette
      spStyle->setOriginalName(spStyle->getName());
      // do not change the style name
      spStyle->setName(cs->getName());
      palette->setStyle(page->getStyleId(*it), spStyle);
      somethingChanged = true;
    }
  }
  if (somethingChanged) {
    palette->setDirtyFlag(true);
    TUndoManager::manager()->add(undo);
    m_paletteHandle->notifyColorStyleChanged(false);
    m_paletteHandle->notifyColorStyleSwitched();
  } else
    delete undo;
}
References TColorStyle::clone(), TColorStyle::getGlobalName(), TColorStyle::getName(), TPalette::Page::getStyle(), TPalette::getStyle(), TPalette::Page::getStyleId(), TColorStyle::setGlobalName(), TColorStyle::setName(), and TColorStyle::setOriginalName().
getIndicesInPage() [1/2]
const std::set< int > & TStyleSelection::getIndicesInPage () const inline
{ return m_styleIndicesInPage; }
getIndicesInPage() [2/2]
const std::set< int > & TStyleSelection::getIndicesInPage () const inline
{ return m_styleIndicesInPage; }
getMimeType()
const char * TStyleSelection::getMimeType () static
{
  return "application/vnd.toonz.style";
}
getPageIndex() [1/2]
int TStyleSelection::getPageIndex () const inline
{ return m_pageIndex; }
getPageIndex() [2/2]
int TStyleSelection::getPageIndex () const inline
{ return m_pageIndex; }
getPalette() [1/2]
TPalette * TStyleSelection::getPalette () const inline
{ return m_paletteHandle->getPalette(); }
getPalette() [2/2]
const TPaletteP & TStyleSelection::getPalette () const inline
{ return m_palette; }
getPaletteHandle()
TPaletteHandle * TStyleSelection::getPaletteHandle () const inline
{ return m_paletteHandle; }
getStyleCount()
int TStyleSelection::getStyleCount () const
{
  return m_styleIndicesInPage.size();
}
getXsheetHandle()
TXsheetHandle * TStyleSelection::getXsheetHandle () const inline
{ return m_xsheetHandle; }
hasLinkedStyle()
bool TStyleSelection::hasLinkedStyle ()
return true if there is at least one linked style in the selection
{
  TPalette *palette = getPalette();
  if (!palette || m_pageIndex < 0 || isEmpty()) return false;
  if (m_styleIndicesInPage.size() <= 0) return false;
  TPalette::Page *page = palette->getPage(m_pageIndex);
  assert(page);
  // for each selected style
  for (std::set<int>::iterator it = m_styleIndicesInPage.begin();
       it != m_styleIndicesInPage.end(); ++it) {
    TColorStyle *cs    = page->getStyle(*it);
    std::wstring gname = cs->getGlobalName();
    // if the style has link, return true
    if (gname != L"" && (gname[0] == L'-' || gname[0] == L'+')) return true;
  }
  return false;
}
References TColorStyle::getGlobalName(), and TPalette::Page::getStyle().
Referenced by PaletteViewerGUI::PageViewer::contextMenuEvent().
isEmpty() [1/2]
bool TStyleSelection::isEmpty () const virtual
Implements TSelection.
isEmpty() [2/2]
bool TStyleSelection::isEmpty () const override virtual
Implements TSelection.
{
  return m_pageIndex < 0 && m_styleIndicesInPage.empty();
}
isPageSelected() [1/2]
bool TStyleSelection::isPageSelected (const TPaletteP & palette, int pageIndex) const
{
  return m_palette.getPointer() == palette.getPointer() &&
         m_pageIndex == pageIndex;
}
isPageSelected() [2/2]
bool TStyleSelection::isPageSelected (int pageIndex) const
{
  return m_pageIndex == pageIndex;
}
isSelected() [1/2]
bool TStyleSelection::isSelected (const TPaletteP & palette, int pageIndex, int styleIndexInPage) const
{
  return m_palette.getPointer() == palette.getPointer() &&
         m_pageIndex == pageIndex &&
         m_styleIndicesInPage.find(id) != m_styleIndicesInPage.end();
}
isSelected() [2/2]
bool TStyleSelection::isSelected (int pageIndex, int styleIndexInPage) const
{
  return m_pageIndex == pageIndex &&
         m_styleIndicesInPage.find(id) != m_styleIndicesInPage.end();
}
pasteStyles()
void TStyleSelection::pasteStyles ()
{
  // se non c'e' palette o pagina corrente esco
  if (!m_palette || m_pageIndex < 0) return;
  if (m_pageIndex == 0 && !m_styleIndicesInPage.empty() &&
      *m_styleIndicesInPage.begin() < 2) {
    MsgBox(CRITICAL, "Can't paste styles there");
    return;
  }
  pasteStylesWithoutUndo(m_palette, m_pageIndex, &m_styleIndicesInPage);
  TUndoManager::manager()->add(new PasteStylesUndo(new TStyleSelection(this)));
}
pasteStylesColor()
void TStyleSelection::pasteStylesColor ()
{ pasteStylesValues(false, true); }
pasteStylesName()
void TStyleSelection::pasteStylesName ()
{ pasteStylesValues(true, false); }
pasteStylesValue()
void TStyleSelection::pasteStylesValue ()
{
  if (!m_palette || m_pageIndex < 0) return;
  if (m_pageIndex == 0 && isSelected(m_palette, 0, 0)) {
    MsgBox(CRITICAL, "Can't modify color #0");
    return;
  }
  TPalette::Page *page = m_palette->getPage(m_pageIndex);
  assert(page);
  const StyleData *data =
      dynamic_cast<const StyleData *>(QApplication::clipboard()->mimeData());
  if (!data) return;
  int i                 = 0;
  UndoPasteValues *undo = new UndoPasteValues(m_palette);
  std::set<int>::iterator it;
  for (it = m_styleIndicesInPage.begin();
       it != m_styleIndicesInPage.end() && i < data->getStyleCount();
       ++it, i++) {
    int styleId = page->getStyleId(*it);
    undo->addItem(styleId, m_palette->getStyle(styleId), data->getStyle(i));
    m_palette->setStyle(styleId, data->getStyle(i)->clone());
  }
  TUndoManager::manager()->add(undo);
  TPaletteHandle *ph = TApp::instance()->getCurrentPalette();
  ph->notifyColorStyleChanged();
  ph->updateColor();
}
pasteStylesValues()
void TStyleSelection::pasteStylesValues (bool pasteName, bool pasteColor = true)
{
  TPalette *palette = getPalette();
  if (!palette || m_pageIndex < 0) return;
  if (palette->isLocked()) return;
  TPalette::Page *page = palette->getPage(m_pageIndex);
  if (!page) return;
  if (isSelected(m_pageIndex, 0) && page->getStyleId(0) == 0) {
    error(QObject::tr("Can't modify color #0"));
    return;
  }
  const StyleData *data =
      dynamic_cast<const StyleData *>(QApplication::clipboard()->mimeData());
  if (!data) return;
  int dataStyleCount = data->getStyleCount();
  if (dataStyleCount > (int)m_styleIndicesInPage.size()) {
    QString question = QObject::tr(
        "There are more cut/copied styles than selected. Paste anyway (adding "
        "styles)?");
    int ret =
        DVGui::MsgBox(question, QObject::tr("Paste"), QObject::tr("Cancel"), 0);
    if (ret == 2 || ret == 0) return;
  }
  int i                 = 0;
  UndoPasteValues *undo = new UndoPasteValues(this, pasteName, pasteColor);
  std::set<int>::iterator it;
  int indexInPage = 0;
  for (it = m_styleIndicesInPage.begin();
       it != m_styleIndicesInPage.end() && i < data->getStyleCount();
       ++it, i++) {
    if (page->getStyleCount() < i) break;
    indexInPage = *it;
    int styleId = page->getStyleId(indexInPage);
    undo->addItem(indexInPage, palette->getStyle(styleId), data->getStyle(i));
    TColorStyle *colorStyle = page->getStyle(indexInPage);
    std::wstring styleName  = colorStyle->getName();
    unsigned int flags      = colorStyle->getFlags();
    if (pasteColor) {
      // first, check out the types of copied and pasted styles
      StyleType srcType, dstType;
      // copied (source)
      if (data->getStyle(i)->getGlobalName() == L"")
        srcType = NORMALSTYLE;
      else if (data->getStyle(i)->getOriginalName() == L"")
        srcType = STUDIOSTYLE;
      else
        srcType = LINKEDSTYLE;
      // pasted (destination)
      TColorStyle *dstStyle        = page->getStyle(indexInPage);
      std::wstring dstGlobalName   = dstStyle->getGlobalName();
      std::wstring dstOriginalName = dstStyle->getOriginalName();
      if (dstGlobalName == L"")
        dstType = NORMALSTYLE;
      else if (dstOriginalName == L"")
        dstType = STUDIOSTYLE;
      else
        dstType = LINKEDSTYLE;
      // For cleanup styles, do not duplicate the cleanup information. Just
      // paste color information.
      TCleanupStyle *cleanupStyle =
          dynamic_cast<TCleanupStyle *>(data->getStyle(i));
      if (cleanupStyle && !palette->isCleanupPalette())
        palette->setStyle(styleId, cleanupStyle->getMainColor());
      else
        palette->setStyle(styleId, data->getStyle(i)->clone());
      // Process the global and original names according to the pasted style
      TColorStyle *pastedStyle = getPalette()->getStyle(styleId);
      // If paste color and name are both ON, then paste the link information.
      if (pasteName) {
        if (srcType == NORMALSTYLE) {
          if (dstType == NORMALSTYLE) {
          }  // 1. From normal to normal. Do nothing.
          else if (dstType == STUDIOSTYLE)  // 2. From normal to studio. Restore
                                            // the global name
            pastedStyle->setGlobalName(dstGlobalName);
          else  // dstType == LINKEDSTYLE       //3. From normal to
                // linked. Restore both the global and the original name.
                // Activate the edited flag.
          {
            pastedStyle->setGlobalName(dstGlobalName);
            pastedStyle->setOriginalName(dstOriginalName);
            pastedStyle->setIsEditedFlag(true);
          }
        } else if (srcType == STUDIOSTYLE) {
          if (dstType ==
              NORMALSTYLE)  // 4. From studio to normal. Set the studio
                            // style's name to the original name.
            pastedStyle->setOriginalName(data->getStyle(i)->getName());
          else if (dstType == STUDIOSTYLE)  // 5. From studio to studio. Restore
                                            // the global name.
            pastedStyle->setGlobalName(dstGlobalName);
          else  // dstType == LINKEDSTYLE       //6. From studio to
                // linked. Set the studio style's name to the original name, and
                // set the edited flag to off.
          {
            pastedStyle->setOriginalName(data->getStyle(i)->getName());
            pastedStyle->setIsEditedFlag(false);
          }
        } else  // srcType == LINKEDSTYLE
        {
          if (dstType == NORMALSTYLE) {
          }  // 7. From linked to normal. Do nothing.
          else if (dstType == STUDIOSTYLE)  // 8. From linked to studio. Restore
                                            // the global name. Delete the
                                            // original name. Set the edited
                                            // flag to off.
          {
            pastedStyle->setGlobalName(dstGlobalName);
            pastedStyle->setOriginalName(L"");
            pastedStyle->setIsEditedFlag(false);
          } else  // dstType == LINKEDSTYLE     //9. From linked to
                  // linked.
                  // Do nothing (bring all information from the original).
          {
          }
        }
      }
      // If paste color is ON and paste name is OFF, then revert the link
      // information (i.e. "paste color" will paste color info only).
      else {  // !pasteName
        pastedStyle->setGlobalName(dstGlobalName);
        pastedStyle->setOriginalName(dstOriginalName);
        pastedStyle->setIsEditedFlag(dstType == LINKEDSTYLE);
        // put back the name
        page->getStyle(indexInPage)->setName(styleName);
        page->getStyle(indexInPage)->setFlags(flags);
      }
    }
    // when "paste name"
    if (pasteName)
      page->getStyle(indexInPage)->setName(data->getStyle(i)->getName());
  }
  // If the styles of the data are more than those selected, make a paste of the
  // styles that remain, inserting the new styles after indexInPage
  if (i < dataStyleCount) {
    StyleData *newData = new StyleData();
    int j;
    for (j = i; j < dataStyleCount; j++)
      newData->addStyle(data->getStyleIndex(j), data->getStyle(j)->clone());
    std::set<int> styleIndicesInPage;
    pasteStylesDataWithoutUndo(m_paletteHandle->getPalette(), m_paletteHandle,
                               newData, indexInPage + 1, m_pageIndex,
                               &styleIndicesInPage);
    undo->addItemToInsert(styleIndicesInPage);
    std::set<int>::iterator styleIt;
    for (styleIt = styleIndicesInPage.begin();
         styleIt != styleIndicesInPage.end(); ++styleIt)
      m_styleIndicesInPage.insert(*styleIt);
    delete newData;
  }
  TUndoManager::manager()->add(undo);
  // clear cache(invalidate) of the level
  if (m_levelHandle && m_levelHandle->getSimpleLevel() &&
      !m_levelHandle->getSimpleLevel()->getProperties()->getDirtyFlag())
    m_levelHandle->getSimpleLevel()->invalidateFrames();
  m_paletteHandle->notifyColorStyleChanged(false);
  m_paletteHandle->notifyColorStyleSwitched();
  // this is to redraw the style editor with colorStyleSwitched() signal
  m_paletteHandle->setStyleIndex(m_paletteHandle->getStyleIndex());
  palette->setDirtyFlag(true);
}
removeLink()
void TStyleSelection::removeLink ()
remove link from studio palette. Delete the global and the original names. return true if something changed
{
  TPalette *palette = getPalette();
  if (!palette || m_pageIndex < 0) return;
  int n = m_styleIndicesInPage.size();
  if (n <= 0) return;
  TPalette::Page *page = palette->getPage(m_pageIndex);
  assert(page);
  bool somethingChanged = false;
  UndoRemoveLink *undo = new UndoRemoveLink(m_paletteHandle, m_pageIndex);
  for (std::set<int>::iterator it = m_styleIndicesInPage.begin();
       it != m_styleIndicesInPage.end(); ++it) {
    TColorStyle *cs = page->getStyle(*it);
    assert(cs);
    if (cs->getGlobalName() != L"" || cs->getOriginalName() != L"") {
      undo->setColorStyle(*it, cs);
      cs->setGlobalName(L"");
      cs->setOriginalName(L"");
      cs->setIsEditedFlag(false);
      somethingChanged = true;
    }
  }
  if (somethingChanged) {
    m_paletteHandle->notifyColorStyleChanged(false);
    TUndoManager::manager()->add(undo);
  } else
    delete undo;
}
References TColorStyle::getGlobalName(), TColorStyle::getOriginalName(), TPalette::Page::getStyle(), TColorStyle::setGlobalName(), and TColorStyle::setOriginalName().
select() [1/4]
void TStyleSelection::select (const TPaletteP & palette, int pageIndex)
{
  m_palette   = palette;
  m_pageIndex = pageIndex;
  m_styleIndicesInPage.clear();
}
select() [2/4]
void TStyleSelection::select (const TPaletteP & palette, int pageIndex, int styleIndexInPage, bool on)
{
  if (on) {
    if (m_palette.getPointer() != palette.getPointer() ||
        pageIndex != m_pageIndex)
      m_styleIndicesInPage.clear();
    m_palette   = palette;
    m_pageIndex = pageIndex;
    m_styleIndicesInPage.insert(styleIndexInPage);
  } else if (m_palette.getPointer() == palette.getPointer() &&
             pageIndex == m_pageIndex)
    m_styleIndicesInPage.erase(styleIndexInPage);
}
select() [3/4]
void TStyleSelection::select (int pageIndex)
{
  m_pageIndex = pageIndex;
  m_styleIndicesInPage.clear();
}
select() [4/4]
void TStyleSelection::select (int pageIndex, int styleIndexInPage, bool on)
{
  if (on) {
    if (pageIndex != m_pageIndex) m_styleIndicesInPage.clear();
    m_pageIndex = pageIndex;
    m_styleIndicesInPage.insert(styleIndexInPage);
  } else if (pageIndex == m_pageIndex)
    m_styleIndicesInPage.erase(styleIndexInPage);
}
selectNone() [1/2]
void TStyleSelection::selectNone () virtual
Implements TSelection.
selectNone() [2/2]
void TStyleSelection::selectNone () override virtual
Implements TSelection.
{
  m_palette   = 0;
  m_pageIndex = -1;
  m_styleIndicesInPage.clear();
  notifyView();
}
setLevelHandle()
void TStyleSelection::setLevelHandle (TXshLevelHandle * levelHandle) inline
{
    m_levelHandle = levelHandle;
  }
setPaletteHandle()
void TStyleSelection::setPaletteHandle (TPaletteHandle * paletteHandle) inline
{
    m_paletteHandle = paletteHandle;
  }
setXsheetHandle()
void TStyleSelection::setXsheetHandle (TXsheetHandle * xsheetHandle) inline
{
    m_xsheetHandle = xsheetHandle;
  }
toByteArray() [1/2]
QByteArray TStyleSelection::toByteArray () const
{
  QString globalName =
      QString::fromStdWString(m_palette->getGlobalName().c_str());
  return toByteArray(m_pageIndex, m_styleIndicesInPage, globalName);
}
toByteArray() [2/2]
QByteArray TStyleSelection::toByteArray (int pageIndex, const std::set< int > & indicesInPage, const QString paletteGlobalName) static
{
  QByteArray data;
  QBuffer dataBuffer(&data);
  dataBuffer.open(QIODevice::WriteOnly);
  QDataStream out(&dataBuffer);
  out << (int)pageIndex << (int)indicesInPage.size() << paletteGlobalName;
  std::set<int>::const_iterator it;
  for (it = indicesInPage.begin(); it != indicesInPage.end(); ++it)
    out << (int)*it;
  return data;
}
toggleKeyframe()
void TStyleSelection::toggleKeyframe (int frame)
{
  TPalette *palette = getPalette();
  if (!palette || m_pageIndex < 0) return;
  int n                = m_styleIndicesInPage.size();
  TPalette::Page *page = palette->getPage(m_pageIndex);
  assert(page);
  for (std::set<int>::iterator it = m_styleIndicesInPage.begin();
       it != m_styleIndicesInPage.end(); ++it) {
    int styleId = page->getStyleId(*it);
    palette->setKeyframe(styleId, frame);
  }
}
toggleLink()
void TStyleSelection::toggleLink ()
{
  if (!m_palette || m_pageIndex < 0) return;
  int n = m_styleIndicesInPage.size();
  if (n <= 0) return;
  bool somethingHasBeenLinked = false;
  bool currentStyleIsInSelection = false;
  TApp *app                      = TApp::instance();
  TPaletteHandle *ph             = app->getCurrentPalette();
  TPalette::Page *page = m_palette->getPage(m_pageIndex);
  assert(page);
  for (std::set<int>::iterator it = m_styleIndicesInPage.begin();
       it != m_styleIndicesInPage.end(); ++it) {
    TColorStyle *cs = page->getStyle(*it);
    assert(cs);
    wstring name = cs->getGlobalName();
    if (name != L"" && (name[0] == L'-' || name[0] == L'+')) {
      name[0] = name[0] == L'-' ? L'+' : L'-';
      cs->setGlobalName(name);
      if (name[0] == L'+') somethingHasBeenLinked = true;
    }
    if (*it == m_palette->getPage(m_pageIndex)->search(ph->getStyleIndex()))
      currentStyleIsInSelection = true;
  }
  if (somethingHasBeenLinked)
    StudioPalette::instance()->updateLinkedColors(m_palette.getPointer());
  ph->notifyPaletteChanged();
  if (currentStyleIsInSelection) ph->notifyColorStyleSwitched();
  // DA FARE: e' giusto mettere la nofica del dirty flag a current scene
  // o e' meglio farlo al livello corrente!?
  app->getCurrentScene()->setDirtyFlag(true);
  //  extern void setPaletteDirtyFlag();
  //  setPaletteDirtyFlag();
}
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/toonzqt/styleselection.h
E:/opentoonz/toonz/sources/toonz/styleselection.h
E:/opentoonz/toonz/sources/toonz/styleselection.cpp
E:/opentoonz/toonz/sources/toonzqt/styleselection.cpp