opentoonz: TPointT< T > Class Template Reference
TPointT< T > Class Template Reference
#include <tgeometry.h>
Public Member Functions
TPointT (T _x, T _y)
TPointT (const TPointT &point)
TPointT & operator= (const TPointT &a)
TPointT & operator+= (const TPointT &a)
TPointT & operator-= (const TPointT &a)
TPointT operator+ (const TPointT &a) const
TPointT operator- (const TPointT &a) const
TPointT operator- () const
bool operator!= (const TPointT &p) const
Public Attributes
T x
T y
Related Functions
(Note that these are not member functions.)
template<class T >
TPointT< T > rotate90 (const TPointT< T > &p)
template<class T >
TPointT< T > rotate270 (const TPointT< T > &p)
template<class T >
T operator* (const TPointT< T > &a, const TPointT< T > &b)
TPoint operator* (int a, const TPoint &p)
TPoint operator* (const TPoint &p, int a)
TPointD operator* (double a, const TPointD &p)
TPointD operator* (const TPointD &p, double a)
int norm2 (const TPointI &p)
double norm2 (const TPointD &p)
double norm (const TPointD &p)
TPointD normalize (const TPointD &p)
TPointD convert (const TPoint &p)
TPoint convert (const TPointD &p)
double tdistance2 (const TPointD &p1, const TPointD &p2)
double tdistance (const TPointD &p1, const TPointD &p2)
double cross (const TPointD &a, const TPointD &b)
template<class T >
T3DPointT< T > operator* (const T3DPointT< T > &p, T a)
template<class T >
T norm2 (const T3DPointT< T > &p)
TRectD boundingBox (const TPointD &p0, const TPointD &p1)
TRectD boundingBox (const TPointD &p0, const TPointD &p1, const TPointD &p2)
TRectD boundingBox (const TPointD &p0, const TPointD &p1, const TPointD &p2, const TPointD &p3)
Detailed Description
template<class T>
class TPointT< T >
The template class TPointT defines the x- and y-coordinates of a point.
Constructor & Destructor Documentation
TPointT() [1/3]
template<class T > TPointT< T >::TPointT () inline
: x(0), y(0){};
TPointT() [2/3]
template<class T > TPointT< T >::TPointT (T _x, T _y) inline
: x(_x), y(_y){};
TPointT() [3/3]
template<class T > TPointT< T >::TPointT (const TPointT< T > & point) inline
: x(point.x), y(point.y){};
Member Function Documentation
operator!=()
template<class T > bool TPointT< T >::operator!= (const TPointT< T > & p) const inline
{ return x != p.x || y != p.y; }
operator+()
template<class T > TPointT TPointT< T >::operator+ (const TPointT< T > & a) const inline
{
    return TPointT(x + a.x, y + a.y);
  };
operator+=()
template<class T > TPointT & TPointT< T >::operator+= (const TPointT< T > & a) inline
{
    x += a.x;
    y += a.y;
    return *this;
  };
operator-() [1/2]
template<class T > TPointT TPointT< T >::operator- () const inline
{ return TPointT(-x, -y); };
operator-() [2/2]
template<class T > TPointT TPointT< T >::operator- (const TPointT< T > & a) const inline
{
    return TPointT(x - a.x, y - a.y);
  };
operator-=()
template<class T > TPointT & TPointT< T >::operator-= (const TPointT< T > & a) inline
{
    x -= a.x;
    y -= a.y;
    return *this;
  };
operator=()
template<class T > TPointT & TPointT< T >::operator= (const TPointT< T > & a) inline
{
    x = a.x;
    y = a.y;
    return *this;
  };
Friends And Related Function Documentation
boundingBox() [1/3]
template<class T > TRectD boundingBox (const TPointD & p0, const TPointD & p1) related
{
  return TRectD(std::min(p0.x, p1.x), std::min(p0.y, p1.y),  // bottom left
                std::max(p0.x, p1.x), std::max(p0.y, p1.y));  // top right
}
boundingBox() [2/3]
template<class T > TRectD boundingBox (const TPointD & p0, const TPointD & p1, const TPointD & p2) related
{
  return TRectD(std::min({p0.x, p1.x, p2.x}), std::min({p0.y, p1.y, p2.y}),
                std::max({p0.x, p1.x, p2.x}), std::max({p0.y, p1.y, p2.y}));
}
boundingBox() [3/3]
template<class T > TRectD boundingBox (const TPointD & p0, const TPointD & p1, const TPointD & p2, const TPointD & p3) related
{
  return TRectD(
      std::min({p0.x, p1.x, p2.x, p3.x}), std::min({p0.y, p1.y, p2.y, p3.y}),
      std::max({p0.x, p1.x, p2.x, p3.x}), std::max({p0.y, p1.y, p2.y, p3.y}));
}
convert() [1/2]
template<class T > TPointD convert (const TPoint & p) related
This helper function converts a TPoint (TPointT<int>) into a TPointD
{ return TPointD(p.x, p.y); }
Referenced by texture_utils::getTextureData(), TThickPoint::tdistance(), and TThickPoint::tdistance2().
convert() [2/2]
template<class T > TPoint convert (const TPointD & p) related
This helper function converts a TPointD (TPointT<double>) into a TPoint
{
  return TPoint(tround(p.x), tround(p.y));
}
cross()
template<class T > double cross (const TPointD & a, const TPointD & b) related
the cross product
{
  return a.x * b.y - a.y * b.x;
}
norm()
template<class T > double norm (const TPointD & p) related
This helper function returns the absolute value of the specified point
{ return std::sqrt(norm2(p)); }
References TPointT< T >::norm2().
Referenced by TPointT< T >::normalize(), TPointT< T >::tdistance(), and TThickPoint::tdistance().
norm2() [1/3]
template<class T > T norm2 (const T3DPointT< T > & p) related
This helper function returns the square of the absolute value of the specified point (a TPointI)
{
  return p.x * p.x + p.y * p.y + p.z * p.z;
}
norm2() [2/3]
template<class T > double norm2 (const TPointD & p) related
This helper function returns the square of the absolute value of the specified point (a TPointD)
{ return p.x * p.x + p.y * p.y; }
norm2() [3/3]
template<class T > int norm2 (const TPointI & p) related
This helper function returns the square of the absolute value of the specified point (a TPointI)
{ return p.x * p.x + p.y * p.y; }
Referenced by TPointT< T >::norm(), TPointT< T >::tdistance2(), and TThickPoint::tdistance2().
normalize()
template<class T > TPointD normalize (const TPointD & p) related
This helper function returns the normalized version of the specified point
{
  double n = norm(p);
  assert(n != 0.0);
  return (1.0 / n) * p;
}
References TPointT< T >::norm().
operator*() [1/6]
template<class T > T3DPointT< T > operator* (const T3DPointT< T > & p, T a) related
{
  return T3DPointT<T>(a * p.x, a * p.y, a * p.z);
}
operator*() [2/6]
template<class T > TPoint operator* (const TPoint & p, int a) related
{
  return TPoint(a * p.x, a * p.y);
}
operator*() [3/6]
template<class T > TPointD operator* (const TPointD & p, double a) related
{
  return TPointD(a * p.x, a * p.y);
}
operator*() [4/6]
template<class T > T operator* (const TPointT< T > & a, const TPointT< T > & b) related
{
  return a.x * b.x + a.y * b.y;
}
operator*() [5/6]
template<class T > TPointD operator* (double a, const TPointD & p) related
{
  return TPointD(a * p.x, a * p.y);
}
operator*() [6/6]
template<class T > TPoint operator* (int a, const TPoint & p) related
{
  return TPoint(a * p.x, a * p.y);
}
rotate270()
template<class T > TPointT< T > rotate270 (const TPointT< T > & p) related
Rotate a point 270 degrees (clockwise).
Parameters
p a point.
Returns
the rotated point
See also
rotate90
{
  return TPointT<T>(p.y, -p.x);
}
rotate90()
template<class T > TPointT< T > rotate90 (const TPointT< T > & p) related
Rotate a point 90 degrees (counterclockwise).
Parameters
p a point.
Returns
the rotated point
See also
rotate270
{
  return TPointT<T>(-p.y, p.x);
}
tdistance()
template<class T > double tdistance (const TPointD & p1, const TPointD & p2) related
This helper function returns the distance between two points
{
  return norm(p2 - p1);
}
References TPointT< T >::norm().
tdistance2()
template<class T > double tdistance2 (const TPointD & p1, const TPointD & p2) related
This helper function returns the square of the distance between two points
{
  return norm2(p2 - p1);
}
References TPointT< T >::norm2().
Member Data Documentation
x
template<class T > T TPointT< T >::x
y
template<class T > T TPointT< T >::y
The documentation for this class was generated from the following file:
E:/opentoonz/toonz/sources/include/tgeometry.h