opentoonz: SceneResource Class Reference
SceneResource Class Reference abstract
The SceneResource class is the base class of scene resource.
#include <sceneresources.h>
Public Member Functions
SceneResource (ToonzScene *scene)
virtual ~SceneResource ()
virtual void save ()=0
virtual void updatePath ()=0
change the resource internal path, according to the scene
virtual void rollbackPath ()=0
change back the resource internal path to its original value
virtual void accept (ResourceProcessor *processor)=0
visitor pattern
void updatePath (TFilePath &fp)
virtual bool isDirty ()=0
virtual QStringList getResourceName ()=0
Protected Attributes
ToonzScene * m_scene
bool m_untitledScene
TFilePath m_oldSavePath
Detailed Description
The SceneResource class is the base class of scene resource.
The class contains a pointer to scene, a boolean to know if scene is untiltled and a path to know old save path.
Constructor & Destructor Documentation
SceneResource()
SceneResource::SceneResource (ToonzScene * scene)
Constructs SceneResource with default value and scene.
    : m_scene(scene)
    , m_untitledScene(scene->isUntitled())
    , m_oldSavePath(scene->getSavePath()) {}
~SceneResource()
SceneResource::~SceneResource () virtual
Destroys the SceneResource object.
{}
Member Function Documentation
accept()
virtual void SceneResource::accept (ResourceProcessor * processor) pure virtual
visitor pattern
Implemented in ScenePalette, SceneLevel, and SceneSound.
rollbackPath()
virtual void SceneResource::rollbackPath () pure virtual
change back the resource internal path to its original value
Implemented in ScenePalette, SceneLevel, and SceneSound.
save()
virtual void SceneResource::save () pure virtual
save the resource to the disk using the updated path. Note: it calls SceneResource::updatePath(fp) before
Implemented in ScenePalette, SceneLevel, and SceneSound.
updatePath() [1/2]
virtual void SceneResource::updatePath () pure virtual
change the resource internal path, according to the scene
Implemented in ScenePalette, SceneLevel, and SceneSound.
Referenced by ScenePalette::save(), SceneLevel::save(), SceneSound::save(), ScenePalette::updatePath(), SceneLevel::updatePath(), and SceneSound::updatePath().
updatePath() [2/2]
void SceneResource::updatePath (TFilePath & fp)
If scene is untitled update save path.
{
  if (m_untitledScene)
    changeSavePath(fp, m_oldSavePath, m_scene->getSavePath());
}
References ToonzScene::getSavePath().
Member Data Documentation
m_oldSavePath
TFilePath SceneResource::m_oldSavePath protected
m_scene
ToonzScene* SceneResource::m_scene protected
m_untitledScene
bool SceneResource::m_untitledScene protected
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/toonz/sceneresources.h
E:/opentoonz/toonz/sources/toonzlib/sceneresources.cpp