opentoonz: PaintBrushTool Class Reference
PaintBrushTool Class Reference final
Public Member Functions
ToolType getToolType () const override
void draw () override
Draws the tool on the viewer.
void update (TToonzImageP ti, TRectD area)
void updateTranslation () override
void leftButtonDown (const TPointD &pos, const TMouseEvent &e) override
void leftButtonDrag (const TPointD &pos, const TMouseEvent &e) override
void leftButtonUp (const TPointD &pos, const TMouseEvent &) override
void mouseMove (const TPointD &pos, const TMouseEvent &e) override
void onEnter () override
Callback for the mouse entering the viewer area.
void onLeave () override
Callback for the mouse leaving the viewer area.
void onActivate () override
Callback invoked whenever the tool activates.
void onDeactivate () override
Callback for tool deactivation, includes tool switch.
bool onPropertyChanged (std::string propertyName) override
TPropertyGroup * getProperties (int targetType) override
int getCursorId () const override
Returns the type of cursor used by the tool.
TPointD getCenteredCursorPos (const TPointD &originalCursorPos)
void fixMousePos (TPointD pos, bool precise=false)
int getColorClass () const
void finishBrush ()
bool isPencilModeActive () override
Public Member Functions inherited from TTool
TTool (std::string toolName)
every tool (invoking updateTranslation() for each).
virtual ToolType getToolType () const =0
ToolTargetType getTargetType () const
std::string getName () const
virtual ToolOptionsBox * createOptionsBox ()
void setViewer (Viewer *viewer)
Viewer * getViewer () const
double getPixelSize () const
void invalidate (const TRectD &rect=TRectD())
int pick (const TPointD &p)
bool isPicking () const
virtual void updateTranslation ()
virtual bool preLeftButtonDown ()
virtual void mouseMove (const TPointD &, const TMouseEvent &)
virtual void leftButtonDown (const TPointD &, const TMouseEvent &)
virtual void leftButtonDrag (const TPointD &, const TMouseEvent &)
virtual void leftButtonUp (const TPointD &, const TMouseEvent &)
virtual void leftButtonDoubleClick (const TPointD &, const TMouseEvent &)
virtual void rightButtonDown (const TPointD &, const TMouseEvent &)
virtual bool keyDown (QKeyEvent *)
virtual void onInputText (std::wstring, std::wstring, int, int)
virtual void onSetViewer ()
virtual void onActivate ()
Callback invoked whenever the tool activates.
virtual void onDeactivate ()
Callback for tool deactivation, includes tool switch.
virtual void onImageChanged ()
Notifies changes in the image in use.
virtual void onEnter ()
Callback for the mouse entering the viewer area.
virtual void onLeave ()
Callback for the mouse leaving the viewer area.
virtual void onFrameSwitched ()
virtual void reset ()
virtual void draw ()
Draws the tool on the viewer.
bool isActive () const
Used to know if a tool is active, (used in TextTool only).
void setActive (bool active)
virtual TPropertyGroup * getProperties (int)
virtual bool onPropertyChanged (std::string propertyName)
virtual TSelection * getSelection ()
Returns a pointer to the tool selection.
virtual int getCursorId () const
Returns the type of cursor used by the tool.
virtual bool isEventAcceptable (QEvent *e)
TXsheet * getXsheet () const
Returns a pointer to the actual Xsheet.
int getFrame ()
Returns the actual frame in use.
int getColumnIndex ()
Returns the actual column index.
TStageObjectId getObjectId () const
Returns a pointer to the actual stage object.
void notifyImageChanged ()
void notifyImageChanged (const TFrameId &fid)
images on the level view.
TFrameId getCurrentFid () const
Returns the number of the actual editing frame.
const TAffine & getMatrix () const
void setMatrix (const TAffine &matrix)
TAffine getCurrentColumnMatrix (int frame=-1) const
TAffine getCurrentColumnParentMatrix () const
TAffine getCurrentObjectParentMatrix () const
TAffine getCurrentObjectParentMatrix2 () const
TAffine getColumnMatrix (int index, int frame=-1) const
virtual void updateMatrix ()
virtual void addContextMenuItems (QMenu *menu)
void enable (bool on)
bool isEnabled () const
QString updateEnabled ()
virtual QString updateEnabled (int rowIndex, int columnIndex)
bool isColumnLocked (int columnIndex) const
void resetInputMethod ()
Resets Input Context (IME)
virtual bool isPencilModeActive ()
virtual bool isDragging () const
void setSelectedFrames (const std::set< TFrameId > &selectedFrames)
void tweenSelectedGuideStrokes ()
void tweenGuideStrokeToSelected ()
void flipGuideStrokeDirection (int mode)
Additional Inherited Members
Public Types inherited from TTool
enum ToolType {
GenericTool = 1 , ColumnTool = 2 , LevelReadTool = 4 , LevelWriteTool ,
LevelTool = LevelReadTool | LevelWriteTool
}
Tool editing type.
enum ToolTargetType {
NoTarget = 0x0 , VectorImage = 0x1 , ToonzImage = 0x2 , RasterImage = 0x4 ,
MeshImage = 0x8 , Splines = 0x10 , LevelColumns = 0x20 , MeshColumns = 0x40 ,
EmptyTarget = 0x80 , CommonImages = VectorImage | ToonzImage | RasterImage , AllImages = CommonImages | MeshImage , Vectors = VectorImage | Splines ,
CommonLevels = CommonImages | LevelColumns , MeshLevels = MeshImage | MeshColumns , AllTargets = 0xffffffff
}
Object types the tool can operate on.
typedef TApplication Application
Static Public Member Functions inherited from TTool
static TTool * getTool (std::string toolName, ToolTargetType targetType)
static TApplication * getApplication ()
static void setApplication (TApplication *application)
static TXshCell getImageCell ()
Returns the level-frame pair to be edited by the tool.
static TImage * getImage (bool toBeModified, int subsampling=0)
Returns the image to be edited by the tool.
static TImage * touchImage ()
static void updateToolsPropertiesTranslation ()
static const std::set< TFrameId > & getSelectedFrames ()
Static Public Attributes inherited from TTool
static std::vector< CellOps > m_cellsData
static bool m_isLevelCreated = false
static bool m_isFrameCreated = false
static std::vector< TFrameId > m_oldFids
static std::vector< TFrameId > m_newFids
static bool m_isLevelRenumbererd = false
Protected Member Functions inherited from TTool
void bind (int targetType)
virtual void onSelectedFramesChanged ()
virtual QString disableString ()
Returns a custom reason to disable the tool.
Protected Attributes inherited from TTool
std::string m_name
The tool's name.
Viewer * m_viewer
Tool's current viewer.
TAffine m_matrix
World-to-window reference change affine.
int m_targetType
The tool's image type target.
bool m_enabled
Whether the tool allows user interaction.
bool m_active
bool m_picking
Static Protected Attributes inherited from TTool
static TApplication * m_application = 0
static std::set< TFrameId > m_selectedFrames = std::set<TFrameId>()
Detailed Description
Constructor & Destructor Documentation
PaintBrushTool()
PaintBrushTool::PaintBrushTool ()
    : TTool("T_PaintBrush")
    , m_rasterTrack(0)
    , m_pointSize(-1)
    , m_selecting(false)
    , m_tileSaver(0)
    , m_cursor(ToolCursor::EraserCursor)
    // sostituire i nomi con quelli del current, tipo W_ToolOptions...
    , m_toolSize("Size:", 1, 1000, 10, false)  // W_ToolOptions_BrushToolSize
    , m_colorType("Mode:")                     // W_ToolOptions_InkOrPaint
    , m_onlyEmptyAreas("Selective", false)     // W_ToolOptions_Selective
    , m_firstTime(true)
    , m_workingFrameId(TFrameId())
    , m_modifierLockAlpha("Lock Alpha", false) {
  m_toolSize.setNonLinearSlider();
  m_colorType.addValue(LINES);
  m_colorType.addValue(AREAS);
  m_colorType.addValue(ALL);
  bind(TTool::ToonzImage);
  m_prop.bind(m_toolSize);
  m_prop.bind(m_colorType);
  m_prop.bind(m_onlyEmptyAreas);
  m_prop.bind(m_modifierLockAlpha);
  m_onlyEmptyAreas.setId("Selective");
  m_colorType.setId("Mode");
  m_modifierLockAlpha.setId("LockAlpha");
}
Member Function Documentation
draw()
void PaintBrushTool::draw () override virtual
Draws the tool on the viewer.
Reimplemented from TTool.
{
  /*-- MouseLeaveBrushTip --*/
  if (m_pointSize == -1) return;
  // If toggled off, don't draw brush outline
  if (!Preferences::instance()->isCursorOutlineEnabled()) return;
  TToonzImageP ti = (TToonzImageP)getImage(false);
  if (!ti) return;
  TRasterP ras = ti->getRaster();
  int lx       = ras->getLx();
  int ly       = ras->getLy();
  if ((ToonzCheck::instance()->getChecks() & ToonzCheck::eInk) ||
      (ToonzCheck::instance()->getChecks() & ToonzCheck::ePaint) ||
      (ToonzCheck::instance()->getChecks() & ToonzCheck::eInk1))
    glColor3d(0.5, 0.8, 0.8);
  else
    glColor3d(1.0, 0.0, 0.0);
  drawEmptyCircle(m_toolSize.getValue(), m_mousePos, true, lx % 2 == 0,
                  ly % 2 == 0);
}
References ToonzCheck::eInk, ToonzCheck::eInk1, ToonzCheck::ePaint, and TTool::getImage().
finishBrush()
void PaintBrushTool::finishBrush ()
onDeactivateMouseRelease
{
  if (TToonzImageP ti = (TToonzImageP)getImage(true)) {
    if (m_rasterTrack) {
      int thickness = m_toolSize.getValue();
      m_rasterTrack->add(TThickPoint(
          m_mousePos + convert(ti->getRaster()->getCenter()), thickness));
      m_tileSaver->save(m_rasterTrack->getLastRect());
      m_rasterTrack->generateLastPieceOfStroke(true, true);
      TTool::Application *app   = TTool::getApplication();
      TXshLevel *level          = app->getCurrentLevel()->getLevel();
      TXshSimpleLevelP simLevel = level->getSimpleLevel();
      /*-- FidUndo
       * --*/
      TFrameId frameId =
          m_workingFrameId.isEmptyFrame() ? getCurrentFid() : m_workingFrameId;
      TUndoManager::manager()->add(new BrushUndo(
          m_tileSaver->getTileSet(), m_rasterTrack->getPointsSequence(),
          m_colorTypeBrush, m_rasterTrack->getStyleId(),
          m_rasterTrack->isSelective(), simLevel.getPointer(), frameId,
          m_rasterTrack->isAlphaLocked()));
      ToolUtils::updateSaveBox();
      /*--- FId
              Fid---*/
      notifyImageChanged(frameId);
      invalidate();
      delete m_rasterTrack;
      m_rasterTrack = 0;
      delete m_tileSaver;
      /*---  ---*/
      m_workingFrameId = TFrameId();
    }
    ToolUtils::updateSaveBox();
  }
  m_selecting = false;
}
References TTool::getCurrentFid(), TTool::getImage(), TXshLevel::getSimpleLevel(), TTool::invalidate(), and TTool::notifyImageChanged().
Referenced by onDeactivate().
fixMousePos()
void PaintBrushTool::fixMousePos (TPointD pos, bool precise = false)
{
  m_mousePos = getCenteredCursorPos(pos);
  if (precise) {
    TPointD pp(tround(m_mousePos.x), tround(m_mousePos.y));
    m_mousePos = pp;
  }
}
getCenteredCursorPos()
TPointD PaintBrushTool::getCenteredCursorPos (const TPointD & originalCursorPos)
{
  TXshLevelHandle *levelHandle = m_application->getCurrentLevel();
  TXshSimpleLevel *level = levelHandle ? levelHandle->getSimpleLevel() : 0;
  TDimension resolution =
      level ? level->getProperties()->getImageRes() : TDimension(0, 0);
  bool xEven = (resolution.lx % 2 == 0);
  bool yEven = (resolution.ly % 2 == 0);
  TPointD centeredCursorPos = originalCursorPos;
  if (xEven) centeredCursorPos.x -= 0.5;
  if (yEven) centeredCursorPos.y -= 0.5;
  return centeredCursorPos;
}
getColorClass()
int PaintBrushTool::getColorClass () const inline
{ return 2; }
getCursorId()
int PaintBrushTool::getCursorId () const inline override virtual
Returns the type of cursor used by the tool.
See also
For a list of cursor ids cursor.h
Reimplemented from TTool.
{ return m_cursor; }
getProperties()
TPropertyGroup * PaintBrushTool::getProperties (int targetType) inline override virtual
Reimplemented from TTool.
{ return &m_prop; }
getToolType()
ToolType PaintBrushTool::getToolType () const inline override virtual
Implements TTool.
{ return TTool::LevelWriteTool; }
isPencilModeActive()
bool PaintBrushTool::isPencilModeActive () inline override virtual
Reimplemented from TTool.
{ return true; }
leftButtonDown()
void PaintBrushTool::leftButtonDown (const TPointD & pos, const TMouseEvent & e) override virtual
Reimplemented from TTool.
{
  fixMousePos(pos);
  m_selecting = true;
  TImageP image(getImage(true));
  if (m_colorType.getValue() == LINES) m_colorTypeBrush = INK;
  if (m_colorType.getValue() == AREAS) m_colorTypeBrush = PAINT;
  if (m_colorType.getValue() == ALL) m_colorTypeBrush   = INKNPAINT;
  if (TToonzImageP ti = image) {
    TRasterCM32P ras = ti->getRaster();
    if (ras) {
      int thickness = m_toolSize.getValue();
      int styleId   = TTool::getApplication()->getCurrentLevelStyleIndex();
      TTileSetCM32 *tileSet = new TTileSetCM32(ras->getSize());
      m_tileSaver           = new TTileSaverCM32(ras, tileSet);
      m_rasterTrack         = new RasterStrokeGenerator(
          ras, PAINTBRUSH, m_colorTypeBrush, styleId,
          TThickPoint(m_mousePos + convert(ras->getCenter()), thickness),
          m_onlyEmptyAreas.getValue(), 0, m_modifierLockAlpha.getValue(),
          false);
      /*-- Fid --*/
      m_workingFrameId = getFrameId();
      m_tileSaver->save(m_rasterTrack->getLastRect());
      m_rasterTrack->generateLastPieceOfStroke(true);
      invalidate();
    }
  }
}
leftButtonDrag()
void PaintBrushTool::leftButtonDrag (const TPointD & pos, const TMouseEvent & e) override virtual
Reimplemented from TTool.
{
  if (!m_selecting) return;
  fixMousePos(pos);
  if (TToonzImageP ri = TImageP(getImage(true))) {
    /*---
            leftButtonDragm_rasterTrack
---*/
    if (m_rasterTrack) {
      int thickness = m_toolSize.getValue();
      m_rasterTrack->add(TThickPoint(
          m_mousePos + convert(ri->getRaster()->getCenter()), thickness));
      m_tileSaver->save(m_rasterTrack->getLastRect());
      TRect modifiedBbox = m_rasterTrack->generateLastPieceOfStroke(true);
      invalidate();
    }
  }
}
leftButtonUp()
void PaintBrushTool::leftButtonUp (const TPointD & pos, const TMouseEvent &) override virtual
Reimplemented from TTool.
{
  if (!m_selecting) return;
  fixMousePos(pos);
  finishBrush();
}
mouseMove()
void PaintBrushTool::mouseMove (const TPointD & pos, const TMouseEvent & e) override virtual
Reimplemented from TTool.
{
  fixMousePos(pos, true);
  invalidate();
}
onActivate()
void PaintBrushTool::onActivate () override virtual
Callback invoked whenever the tool activates.
Reimplemented from TTool.
{ onEnter(); }
References onEnter().
onDeactivate()
void PaintBrushTool::onDeactivate () override virtual
Callback for tool deactivation, includes tool switch.
Reimplemented from TTool.
{
  /*--(m_selecting=true)---*/
  if (m_selecting) finishBrush();
}
References finishBrush().
onEnter()
void PaintBrushTool::onEnter () override virtual
Callback for the mouse entering the viewer area.
Reimplemented from TTool.
{
  if (m_firstTime) {
    m_onlyEmptyAreas.setValue(PaintBrushSelective ? 1 : 0);
    m_colorType.setValue(::to_wstring(PaintBrushColorType.getValue()));
    m_toolSize.setValue(PaintBrushSize);
    m_modifierLockAlpha.setValue(PaintBrushModifierLockAlpha ? 1 : 0);
    m_firstTime = false;
  }
  double x = m_toolSize.getValue();
  double minRange = 1;
  double maxRange = 100;
  double minSize = 0.01;
  double maxSize = 100;
  m_pointSize =
      (x - minRange) / (maxRange - minRange) * (maxSize - minSize) + minSize;
  if ((TToonzImageP)getImage(false))
    m_cursor = ToolCursor::PenCursor;
  else
    m_cursor = ToolCursor::CURSOR_NO;
}
References TTool::getImage().
Referenced by onActivate().
onLeave()
void PaintBrushTool::onLeave () override virtual
Callback for the mouse leaving the viewer area.
Reimplemented from TTool.
{ m_pointSize = -1; }
onPropertyChanged()
bool PaintBrushTool::onPropertyChanged (std::string propertyName) override virtual
 Does the tasks associated to changes in \p propertyName and returns \p
true; Does the tasks associated to changes in propertyName and returns true.
Reimplemented from TTool.
{
  /*-- Size ---*/
  if (propertyName == m_toolSize.getName()) {
    PaintBrushSize = m_toolSize.getValue();
    double x       = m_toolSize.getValue();
    double minRange = 1;
    double maxRange = 100;
    double minSize = 0.01;
    double maxSize = 100;
    m_pointSize =
        (x - minRange) / (maxRange - minRange) * (maxSize - minSize) + minSize;
    invalidate();
  }
  // Selective
  else if (propertyName == m_onlyEmptyAreas.getName()) {
    PaintBrushSelective = (int)(m_onlyEmptyAreas.getValue());
    if (m_onlyEmptyAreas.getValue() && m_modifierLockAlpha.getValue())
      m_modifierLockAlpha.setValue(false);
  }
  // Areas, Lines etc.
  else if (propertyName == m_colorType.getName()) {
    PaintBrushColorType = ::to_string(m_colorType.getValue());
    /*--- ColorModelCursorSIGNAL ---*/
    TTool::getApplication()->getCurrentTool()->notifyToolChanged();
  }
  // Lock Alpha
  else if (propertyName == m_modifierLockAlpha.getName()) {
    PaintBrushModifierLockAlpha = (int)(m_modifierLockAlpha.getValue());
    if (m_modifierLockAlpha.getValue() && m_onlyEmptyAreas.getValue())
      m_onlyEmptyAreas.setValue(false);
  }
  return true;
}
References TTool::invalidate(), and ToolHandle::notifyToolChanged().
updateTranslation()
void PaintBrushTool::updateTranslation () override virtual
Reimplemented from TTool.
{
  m_toolSize.setQStringName(tr("Size:"));
  m_colorType.setQStringName(tr("Mode:"));
  m_colorType.setItemUIName(LINES, tr("Lines"));
  m_colorType.setItemUIName(AREAS, tr("Areas"));
  m_colorType.setItemUIName(ALL, tr("Lines & Areas"));
  m_onlyEmptyAreas.setQStringName(tr("Selective", NULL));
  m_modifierLockAlpha.setQStringName(tr("Lock Alpha"));
}
The documentation for this class was generated from the following file:
E:/opentoonz/toonz/sources/tnztools/paintbrushtool.cpp