opentoonz: ToonzImageIconRenderer Class Reference
ToonzImageIconRenderer Class Reference final
Public Member Functions
ToonzImageIconRenderer (const std::string &id, const TDimension &iconSize, TXshSimpleLevelP sl, const TFrameId &fid, const IconGenerator::Settings &settings)
void run () override
The central code of the task that is executed by a worker thread.
void setIcon_TnzImg (const TRasterCM32P &timgp)
TRasterCM32P getIcon_TnzImg () const
Public Member Functions inherited from IconRenderer
IconRenderer (const std::string &id, const TDimension &iconSize)
void run () override=0
The central code of the task that is executed by a worker thread.
void setIcon (const TRaster32P &icon)
TRaster32P getIcon () const
TDimension getIconSize ()
const std::string & getId () const
bool & hasStarted ()
bool & wasTerminated ()
Public Member Functions inherited from TThread::Runnable
virtual void run ()=0
The central code of the task that is executed by a worker thread.
virtual int taskLoad ()
virtual int schedulingPriority ()
virtual QThread::Priority runningPriority ()
Public Member Functions inherited from TSmartObject
TSmartObject (ClassCode classCode)
void addRef ()
void release ()
TINT32 getRefCount () const
Additional Inherited Members
Public Types inherited from TSmartObject
typedef short ClassCode
Public Slots inherited from TThread::Runnable
virtual void onStarted (TThread::RunnableP sender)
virtual void onFinished (TThread::RunnableP sender)
The analogous of onStarted() for the finished() signal.
virtual void onException (TThread::RunnableP sender)
The analogous of onStarted() for the exception() signal.
virtual void onCanceled (TThread::RunnableP sender)
The analogous of onStarted() for the canceled() signal.
virtual void onTerminated (TThread::RunnableP sender)
The analogous of onStarted() for the terminated() signal.
Signals inherited from TThread::Runnable
void started (TThread::RunnableP sender)
void finished (TThread::RunnableP sender)
void exception (TThread::RunnableP sender)
void canceled (TThread::RunnableP sender)
void terminated (TThread::RunnableP sender)
Static Public Member Functions inherited from TSmartObject
static TINT32 getInstanceCount (ClassCode code)
Detailed Description
Constructor & Destructor Documentation
ToonzImageIconRenderer()
ToonzImageIconRenderer::ToonzImageIconRenderer (const std::string & id, const TDimension & iconSize, TXshSimpleLevelP sl, const TFrameId & fid, const IconGenerator::Settings & settings) inline
      : IconRenderer(id, iconSize)
      , m_sl(sl)
      , m_fid(fid)
      , m_settings(settings)
      , m_tnzImgIcon(0) {}
Member Function Documentation
getIcon_TnzImg()
TRasterCM32P ToonzImageIconRenderer::getIcon_TnzImg () const inline
{ return m_tnzImgIcon; }
run()
void ToonzImageIconRenderer::run () override virtual
The central code of the task that is executed by a worker thread.
Implements IconRenderer.
{
  if (!m_sl->isFid(m_fid)) return;
  TImageP image = m_sl->getFrameIcon(m_fid);
  if (!image) return;
  TRasterImageP rimage(image);
  if (rimage) {
    TRaster32P icon(convertToIcon(rimage, getIconSize()));
    if (icon) setIcon(icon);
    return;
  }
  TToonzImageP timage = (TToonzImageP)image;
  TDimension iconSize(getIconSize());
  if (!timage) {
    TRaster32P p(iconSize.lx, iconSize.ly);
    p->fill(TPixelRGBM32::Yellow);
    setIcon(p);
    return;
  }
  TRasterCM32P rasCM32 = timage->getRaster();
  if (!rasCM32.getPointer()) return;
  int lx     = rasCM32->getSize().lx;
  int ly     = rasCM32->getSize().ly;
  int iconLx = iconSize.lx, iconLy = iconSize.ly;
  TRaster32P icon(iconSize);
  icon->fill(m_settings.m_blackBgCheck ? TPixel::Black : TPixel::White);
  if (lx != iconLx && ly != iconLy) {
    // The icons stored in the tlv file don't have the required size.
    // Fetch the original and iconize it.
    image = m_sl->getFrame(m_fid, ImageManager::dontPutInCache,
                           0);  // 0 uses the level properties' subsampling
    if (!image) return;
    timage = (TToonzImageP)image;
    if (!timage) {
      TRaster32P p(iconSize.lx, iconSize.ly);
      p->fill(TPixelRGBM32::Yellow);
      setIcon(p);
      return;
    }
    rasCM32 = timage->getRaster();
    if (!rasCM32.getPointer()) return;
    TRasterCM32P auxCM32(icon->getSize());
    auxCM32->clear();
    TRop::makeIcon(auxCM32, rasCM32);
    rasCM32 = auxCM32;
  }
  if (!m_sl->getPalette()) return;
  TPaletteP plt = m_sl->getPalette()->clone();
  if (!plt) return;
  int frame = m_sl->guessIndex(m_fid);
  plt->setFrame(frame);
  setIcon_TnzImg(rasCM32);
}
References TPalette::clone(), TXshSimpleLevel::getPalette(), TXshSimpleLevel::guessIndex(), TXshSimpleLevel::isFid(), and TPalette::setFrame().
setIcon_TnzImg()
void ToonzImageIconRenderer::setIcon_TnzImg (const TRasterCM32P & timgp) inline
{ m_tnzImgIcon = timgp; }
The documentation for this class was generated from the following file:
E:/opentoonz/toonz/sources/toonzqt/icongenerator.cpp