opentoonz: StageBuilder Class Reference
StageBuilder Class Reference
Classes
struct SubXSheet
Public Types
enum ShiftTraceGhostId { NO_GHOST , FIRST_GHOST , SECOND_GHOST , TRACED }
Public Member Functions
void addCell (PlayerSet &players, ToonzScene *scene, TXsheet *xsh, int row, int col, int level, int subSheetColIndex=-1)
void addCellWithOnionSkin (PlayerSet &players, ToonzScene *scene, TXsheet *xsh, int row, int col, int level, int subSheetColIndex=-1)
void addFrame (PlayerSet &players, ToonzScene *scene, TXsheet *xsh, int row, int level, bool includeUnvisible, bool checkPreviewVisibility, int subSheetColIndex=-1)
void addSimpleLevelFrame (PlayerSet &players, TXshSimpleLevel *level, const TFrameId &fid)
void visit (PlayerSet &players, Visitor &visitor, bool isPlaying=false)
Public Attributes
PlayerSet m_players
std::vector< PlayerSet * > m_maskPool
std::vector< ZPlacement > m_placementStack
ZPlacement m_cameraPlacement
std::vector< SubXSheet > m_subXSheetStack
std::vector< int > m_masks
int m_onionSkinDistance
double m_fade
ShiftTraceGhostId m_shiftTraceGhostId
bool m_camera3d
OnionSkinMask m_onionSkinMask
int m_currentColumnIndex
int m_ancestorColumnIndex
int m_currentXsheetLevel
int m_xsheetLevel
TFrameId m_currentFrameId
int m_isGuidedDrawingEnabled
int m_guidedFrontStroke = -1
int m_guidedBackStroke = -1
std::vector< TXshColumn * > m_ancestors
const ImagePainter::VisualSettings * m_vs
Detailed Description
The StageBuilder class finds and provides data for frame visualization.
The class contains a PlayerSet, a vector of player, of all necessary information.
Member Enumeration Documentation
ShiftTraceGhostId
enum StageBuilder::ShiftTraceGhostId
{ NO_GHOST, FIRST_GHOST, SECOND_GHOST, TRACED };
Constructor & Destructor Documentation
StageBuilder()
StageBuilder::StageBuilder ()
    : m_onionSkinDistance(c_noOnionSkin)
    , m_camera3d(false)
    , m_currentColumnIndex(-1)
    , m_ancestorColumnIndex(-1)
    , m_fade(0)
    , m_shiftTraceGhostId(NO_GHOST)
    , m_currentXsheetLevel(0)
    , m_xsheetLevel(0) {
  m_placementStack.push_back(ZPlacement());
}
~StageBuilder()
StageBuilder::~StageBuilder () virtual
{ clearPointerContainer(m_maskPool); }
Member Function Documentation
addCell()
void StageBuilder::addCell (PlayerSet & players, ToonzScene * scene, TXsheet * xsh, int row, int col, int level, int subSheetColIndex = -1)
Add in players vector information about specify cell.
Analyze cell in row row and column col of xsheet xsh. If level containing this cell is a simple level, TXshSimpleLevel, create a Pleyer object with information of the cell. Else if level is a child level, TXshChildLevel, recall addFrame().
{
  // Local functions
  struct locals {
    static inline bool isMeshDeformed(TXsheet *xsh, TStageObject *obj,
                                      const ImagePainter::VisualSettings *vs) {
      const TStageObjectId &parentId = obj->getParent();
      if (parentId.isColumn() && obj->getParentHandle()[0] != 'H') {
        TStageObject *parentObj = xsh->getStageObject(parentId);
        if (!parentObj->getPlasticSkeletonDeformation()) return false;
        TXshColumn *parentCol = xsh->getColumn(parentId.getIndex());
        return (parentCol->getColumnType() == TXshColumn::eMeshType) &&
               (parentCol != vs->m_plasticVisualSettings.m_showOriginalColumn);
      }
      return false;
    }
    //-----------------------------------------------------------------------------
    static inline bool applyPlasticDeform(
        TXshColumn *col, const ImagePainter::VisualSettings *vs) {
      const PlasticVisualSettings &pvs = vs->m_plasticVisualSettings;
      return pvs.m_applyPlasticDeformation && (col != pvs.m_showOriginalColumn);
    }
  };  // locals
  TXshColumnP column = xsh->getColumn(col);
  assert(column);
  TStageObject *pegbar = xsh->getStageObject(TStageObjectId::ColumnId(col));
  // Build affine placements
  TAffine columnAff     = pegbar->getPlacement(row);
  double columnZ        = pegbar->getZ(row);
  double columnNoScaleZ = pegbar->getGlobalNoScaleZ();
  TXshCell cell = xsh->getCell(row, col);
  TXshLevel *xl = cell.m_level.getPointer();
#if defined(x64)
  // check the previous row for a stop motion layer
  if (!xl) {
    if (!m_liveViewImage) return;
    cell = xsh->getCell(row - 1, col);
    xl   = cell.m_level.getPointer();
    if (!xl) {
      return;
    } else {
      xl                  = cell.m_level.getPointer();
      TXshSimpleLevel *sl = xl->getSimpleLevel();
      if (sl && sl == m_liveViewPlayer.m_sl) {
        row -= 1;
      } else
        return;
    }
  }
#else
  if (!xl) return;
#endif
  ZPlacement cameraPlacement;
  if (m_subXSheetStack.empty())
    cameraPlacement = m_cameraPlacement;
  else
    cameraPlacement = m_subXSheetStack.back().m_camera;
  TAffine columnZaff;
  bool columnBehindCamera = TStageObject::perspective(
      columnZaff, cameraPlacement.m_aff, cameraPlacement.m_z, columnAff,
      columnZ, columnNoScaleZ);
  if (!columnBehindCamera) return;
  TXshSimpleLevel *sl = xl->getSimpleLevel();
  bool storePlayer =
      sl || (xl->getChildLevel() &&
             locals::applyPlasticDeform(column.getPointer(), m_vs) &&
             locals::isMeshDeformed(xsh, pegbar, m_vs));
  if (storePlayer) {
    // Build and store a player
    Player player;
    player.m_sl                     = sl;
    player.m_fid                    = cell.m_frameId;
    player.m_xsh                    = xsh;
    player.m_column                 = col;
    player.m_frame                  = row;
    player.m_currentFrameId         = m_currentFrameId;
    player.m_isGuidedDrawingEnabled = m_isGuidedDrawingEnabled;
    player.m_guidedFrontStroke      = m_guidedFrontStroke;
    player.m_guidedBackStroke       = m_guidedBackStroke;
    player.m_dpiAff = sl ? getDpiAffine(sl, cell.m_frameId) : TAffine();
    player.m_onionSkinDistance = m_onionSkinDistance;
    // when visiting the subxsheet, valuate the subxsheet column index
    bool isCurrent = (subSheetColIndex >= 0)
                         ? (subSheetColIndex == m_currentColumnIndex)
                         : (col == m_currentColumnIndex);
    player.m_isCurrentColumn     = isCurrent;
    player.m_ancestorColumnIndex = m_ancestorColumnIndex;
    player.m_masks               = m_masks;
    player.m_opacity             = column->getOpacity();
    player.m_filterColor         = column->getFilterColor();
    if (m_subXSheetStack.empty()) {
      player.m_z         = columnZ;
      player.m_placement = m_camera3d ? columnAff : columnZaff;
    } else {
      const SubXSheet &parent = m_subXSheetStack.back();
      player.m_z = parent.m_z;
      player.m_placement =
          (m_camera3d ? parent.m_aff : parent.m_zaff) * columnZaff;
    }
    if (m_shiftTraceGhostId != NO_GHOST) {
      // if F1, F2 or F3 key is pressed, then draw only the corresponding ghost
      int flipKey = m_onionSkinMask.getGhostFlipKey();
      if (Qt::Key_F1 <= flipKey && flipKey <= Qt::Key_F3) {
        if (m_shiftTraceGhostId == TRACED && flipKey == Qt::Key_F2) {
          players.push_back(player);
        } else if (m_shiftTraceGhostId == FIRST_GHOST &&
                   flipKey == Qt::Key_F1) {
          player.m_placement =
              m_onionSkinMask.getShiftTraceGhostAff(0) * player.m_placement;
          players.push_back(player);
        } else if (m_shiftTraceGhostId == SECOND_GHOST &&
                   flipKey == Qt::Key_F3) {
          player.m_placement =
              m_onionSkinMask.getShiftTraceGhostAff(1) * player.m_placement;
          players.push_back(player);
        }
        return;
      }
      else {
        int opacity         = player.m_opacity;
        player.m_bingoOrder = 10;
        if (m_onionSkinMask.getShiftTraceStatus() !=
            OnionSkinMask::ENABLED_WITHOUT_GHOST_MOVEMENTS) {
          if (m_shiftTraceGhostId == FIRST_GHOST) {
            player.m_opacity = 30;
            players.push_back(player);
            player.m_opacity           = opacity;
            player.m_onionSkinDistance = -1;
            player.m_placement =
                m_onionSkinMask.getShiftTraceGhostAff(0) * player.m_placement;
          } else if (m_shiftTraceGhostId == SECOND_GHOST) {
            player.m_opacity = 30;
            players.push_back(player);
            player.m_opacity           = opacity;
            player.m_onionSkinDistance = 1;
            player.m_placement =
                m_onionSkinMask.getShiftTraceGhostAff(1) * player.m_placement;
          }
        }
      }
    }
    players.push_back(player);
  } else if (TXshChildLevel *cl = xl->getChildLevel()) {
    int childRow         = cell.m_frameId.getNumber() - 1;
    TXsheet *childXsheet = cl->getXsheet();
    TStageObjectId childCameraId =
        childXsheet->getStageObjectTree()->getCurrentCameraId();
    TStageObject *childCamera = childXsheet->getStageObject(childCameraId);
    TAffine childCameraAff    = childCamera->getPlacement(childRow);
    double childCameraZ       = childCamera->getZ(childRow);
    std::vector<UCHAR> originalOpacity(childXsheet->getColumnCount());
    for (int c = 0; c < childXsheet->getColumnCount(); c++) {
      originalOpacity[c] = childXsheet->getColumn(c)->getOpacity();
      childXsheet->getColumn(c)->setOpacity(column->getOpacity());
    }
    SubXSheet subXSheet;
    subXSheet.m_camera = ZPlacement(childCameraAff, childCameraZ);
    subXSheet.m_z      = columnZ;
    TAffine childCameraZaff =
        childCameraAff *
        TScale((1000 + childCameraZ) / 1000);  // TODO: put in some lib
    TAffine invChildCameraZaff = childCameraZaff.inv();
    subXSheet.m_aff  = columnAff * invChildCameraZaff;
    subXSheet.m_zaff = columnZaff * invChildCameraZaff;
    if (!m_subXSheetStack.empty()) {
      const SubXSheet &parentXSheet = m_subXSheetStack.back();
      subXSheet.m_z =
          m_subXSheetStack.front().m_z;  // Top-level xsheet cell's z
      subXSheet.m_aff  = parentXSheet.m_aff * subXSheet.m_aff;
      subXSheet.m_zaff = parentXSheet.m_zaff * subXSheet.m_zaff;
    }
    m_subXSheetStack.push_back(subXSheet);
    ++m_currentXsheetLevel;
    // inherit the column index when visiting grandchild (sub-sub) sheet
    int subCol = (subSheetColIndex >= 0) ? subSheetColIndex : col;
    addFrame(players, scene, childXsheet, childRow, level + 1, false, false,
             subCol);
    --m_currentXsheetLevel;
    m_subXSheetStack.pop_back();
    for (int c = 0; c < childXsheet->getColumnCount(); c++)
      childXsheet->getColumn(c)->setOpacity(originalOpacity[c]);
  }
}
References addFrame(), TXsheet::getCell(), TXshLevel::getChildLevel(), TXsheet::getColumn(), TXsheet::getColumnCount(), TStageObjectTree::getCurrentCameraId(), TStageObject::getGlobalNoScaleZ(), TXshColumn::getOpacity(), TStageObject::getParent(), TStageObject::getParentHandle(), TStageObject::getPlasticSkeletonDeformation(), TXshLevel::getSimpleLevel(), TXsheet::getStageObject(), TXsheet::getStageObjectTree(), TStageObject::getZ(), TAffine::inv(), TStageObjectId::isColumn(), Stage::Player::m_ancestorColumnIndex, PlasticVisualSettings::m_applyPlasticDeformation, Stage::Player::m_bingoOrder, Stage::Player::m_column, Stage::Player::m_dpiAff, Stage::Player::m_fid, Stage::Player::m_frame, Stage::Player::m_isCurrentColumn, Stage::Player::m_onionSkinDistance, Stage::Player::m_opacity, Stage::Player::m_placement, ImagePainter::VisualSettings::m_plasticVisualSettings, PlasticVisualSettings::m_showOriginalColumn, Stage::Player::m_sl, Stage::Player::m_xsh, Stage::Player::m_z, TStageObject::perspective(), and TXshColumn::setOpacity().
Referenced by addCellWithOnionSkin().
addCellWithOnionSkin()
void StageBuilder::addCellWithOnionSkin (PlayerSet & players, ToonzScene * scene, TXsheet * xsh, int row, int col, int level, int subSheetColIndex = -1)
Verify if onion-skin is active and recall addCell().
Compute the distance between each cell with active onion-skin and current cell and recall addCell(). If onion-skin is not active recall addCell() with argument current cell.
{
  struct locals {
    static inline bool hasOnionSkinnedMeshParent(StageBuilder *sb, TXsheet *xsh,
                                                 int col) {
      const TStageObjectId &parentId =
          xsh->getStageObject(TStageObjectId::ColumnId(col))->getParent();
      return parentId.isColumn() &&
             (parentId.getIndex() == sb->m_currentColumnIndex);
    }
    //-----------------------------------------------------------------------------
    static inline bool doStandardOnionSkin(StageBuilder *sb, TXsheet *xsh,
                                           int level, int col) {
      const OnionSkinMask &osm = sb->m_onionSkinMask;
      return level == sb->m_xsheetLevel && osm.isEnabled() && !osm.isEmpty() &&
             (osm.isWholeScene() || col == sb->m_currentColumnIndex ||
              locals::hasOnionSkinnedMeshParent(sb, xsh, col));
    }
  };  // locals
  if (m_onionSkinMask.isShiftTraceEnabled()) {
    // when visiting the subxsheet, valuate the subxsheet column index
    bool isCurrent = (subSheetColIndex >= 0)
                         ? (subSheetColIndex == m_currentColumnIndex)
                         : (col == m_currentColumnIndex);
    if (isCurrent) {
      TXshCell cell = xsh->getCell(row, col);
      // First Ghost
      int r;
      r = row + m_onionSkinMask.getShiftTraceGhostFrameOffset(0);
      if (r >= 0 && xsh->getCell(r, col) != cell &&
          (cell.getSimpleLevel() == 0 ||
           xsh->getCell(r, col).getSimpleLevel() == cell.getSimpleLevel())) {
        m_shiftTraceGhostId = FIRST_GHOST;
        addCell(players, scene, xsh, r, col, level, subSheetColIndex);
      }
      r = row + m_onionSkinMask.getShiftTraceGhostFrameOffset(1);
      if (r >= 0 && xsh->getCell(r, col) != cell &&
          (cell.getSimpleLevel() == 0 ||
           xsh->getCell(r, col).getSimpleLevel() == cell.getSimpleLevel())) {
        m_shiftTraceGhostId = SECOND_GHOST;
        addCell(players, scene, xsh, r, col, level, subSheetColIndex);
      }
      // draw current working frame
      if (!cell.isEmpty()) {
        m_shiftTraceGhostId = TRACED;
        addCell(players, scene, xsh, row, col, level, subSheetColIndex);
        m_shiftTraceGhostId = NO_GHOST;
      }
    }
    // flip non-current columns as well
    else {
      int flipKey = m_onionSkinMask.getGhostFlipKey();
      if (flipKey == Qt::Key_F1) {
        int r = row + m_onionSkinMask.getShiftTraceGhostFrameOffset(0);
        addCell(players, scene, xsh, r, col, level, subSheetColIndex);
      } else if (flipKey == Qt::Key_F3) {
        int r = row + m_onionSkinMask.getShiftTraceGhostFrameOffset(1);
        addCell(players, scene, xsh, r, col, level, subSheetColIndex);
      } else
        addCell(players, scene, xsh, row, col, level, subSheetColIndex);
    }
  } else if (locals::doStandardOnionSkin(this, xsh, level, col)) {
    std::vector<int> rows;
    m_onionSkinMask.getAll(row, rows);
    std::vector<int>::iterator it = rows.begin();
    while (it != rows.end() && *it < row) it++;
    std::sort(rows.begin(), it, descending);
    int frontPos = 0, backPos = 0;
    for (int i = 0; i < (int)rows.size(); i++) {
      if (rows[i] == row) continue;
#ifdef NUOVO_ONION
      m_onionSkinDistance = rows[i] - row;
#else
      if (!Preferences::instance()->isAnimationSheetEnabled() ||
          !alreadyAdded(xsh, row, i, rows, col)) {
        m_onionSkinDistance = (rows[i] - row) < 0 ? --backPos : ++frontPos;
        addCell(players, scene, xsh, rows[i], col, level, subSheetColIndex);
      }
#endif
    }
    m_onionSkinDistance = 0;
    addCell(players, scene, xsh, row, col, level, subSheetColIndex);
    m_onionSkinDistance = c_noOnionSkin;
  } else
    addCell(players, scene, xsh, row, col, level, subSheetColIndex);
}
References addCell(), OnionSkinMask::getAll(), TXsheet::getCell(), TStageObject::getParent(), TXshCell::getSimpleLevel(), TXsheet::getStageObject(), TStageObjectId::isColumn(), and TXshCell::isEmpty().
Referenced by addFrame().
addFrame()
void StageBuilder::addFrame (PlayerSet & players, ToonzScene * scene, TXsheet * xsh, int row, int level, bool includeUnvisible, bool checkPreviewVisibility, int subSheetColIndex = -1)
Recall addCellWithOnionSkin() for each cell of row row.
{
  int columnCount        = xsh->getColumnCount();
  unsigned int maskCount = m_masks.size();
  std::vector<std::pair<double, int>> shuffle;
  for (int c = 0; c < columnCount; c++) {
    TXshColumnP column = xsh->getColumn(c);
    assert(column);
    TStageObject *pegbar = xsh->getStageObject(TStageObjectId::ColumnId(c));
    double columnSO      = pegbar->getSO(row);
    shuffle.push_back(std::make_pair(columnSO, c));
  }
  std::stable_sort(shuffle.begin(), shuffle.end(), StackingOrder());
  for (int i = 0; i < columnCount; i++) {
    int c = shuffle[i].second;
    if (CameraTestCheck::instance()->isEnabled() && c != m_currentColumnIndex)
      continue;
    if (level == 0) {
      // m_isCurrentColumn = (c == m_currentColumnIndex);
      m_ancestorColumnIndex = c;
    }
    TXshColumn *column = xsh->getColumn(c);
    bool isMask        = false;
    if (column && !column->isEmpty() && !column->getSoundColumn()) {
      if (!column->isPreviewVisible() && checkPreviewVisibility) continue;
      if (column->isCamstandVisible() ||
          includeUnvisible)  // se l'"occhietto" non e' chiuso
      {
        if (column->isMask())  // se e' una maschera (usate solo in tab pro)
        {
          isMask = true;
          std::vector<int> saveMasks;
          saveMasks.swap(m_masks);
          int maskIndex   = m_maskPool.size();
          PlayerSet *mask = new PlayerSet();
          m_maskPool.push_back(mask);
          addCellWithOnionSkin(*mask, scene, xsh, row, c, level);
          std::stable_sort(mask->begin(), mask->end(), PlayerLt());
          saveMasks.swap(m_masks);
          m_masks.push_back(maskIndex);
        } else
          addCellWithOnionSkin(players, scene, xsh, row, c, level,
                               subSheetColIndex);
      }
    }
    if (!isMask) {
      while (m_masks.size() > maskCount) m_masks.pop_back();
    }
  }
  if (level == 0) std::stable_sort(players.begin(), players.end(), PlayerLt());
}
References addCellWithOnionSkin(), TXsheet::getColumn(), TXsheet::getColumnCount(), TStageObject::getSO(), TXsheet::getStageObject(), and CameraTestCheck::instance().
Referenced by addCell(), and Stage::visit().
addSimpleLevelFrame()
void StageBuilder::addSimpleLevelFrame (PlayerSet & players, TXshSimpleLevel * level, const TFrameId & fid)
Add in players vector information about level cell with TFrameId fid.
Compute information for all cell with active onion-skin, if onion-skin is not active compute information only for current cell.
{
  auto addGhost = [&](int ghostIndex, int ghostRow, bool fullOpac = false) {
    const TFrameId &ghostFid = level->index2fid(ghostRow);
    Player player;
    player.m_sl                     = level;
    player.m_frame                  = level->guessIndex(ghostFid);
    player.m_fid                    = ghostFid;
    player.m_isCurrentColumn        = true;
    player.m_isCurrentXsheetLevel   = true;
    player.m_isEditingLevel         = true;
    player.m_currentFrameId         = m_currentFrameId;
    player.m_isGuidedDrawingEnabled = m_isGuidedDrawingEnabled;
    player.m_guidedFrontStroke      = m_guidedFrontStroke;
    player.m_guidedBackStroke       = m_guidedBackStroke;
    player.m_isVisibleinOSM         = ghostRow >= 0;
    player.m_onionSkinDistance      = m_onionSkinDistance;
    player.m_dpiAff                 = getDpiAffine(level, ghostFid);
    player.m_ancestorColumnIndex    = -1;
    if (fullOpac) {
      player.m_placement = m_onionSkinMask.getShiftTraceGhostAff(ghostIndex) *
                           player.m_placement;
      players.push_back(player);
      return;
    }
    int opacity         = player.m_opacity;
    player.m_bingoOrder = 10;
    if (m_onionSkinMask.getShiftTraceStatus() !=
        OnionSkinMask::ENABLED_WITHOUT_GHOST_MOVEMENTS) {
      player.m_opacity = 30;
      players.push_back(player);
      player.m_opacity           = opacity;
      player.m_onionSkinDistance = (ghostIndex == 0) ? -1 : 1;
      player.m_placement = m_onionSkinMask.getShiftTraceGhostAff(ghostIndex) *
                           player.m_placement;
    }
    players.push_back(player);
  };
  int index = -1;
  int row = level->guessIndex(fid);
  // Shift & Trace
  if (m_onionSkinMask.isShiftTraceEnabled()) {
    int previousOffset = m_onionSkinMask.getShiftTraceGhostFrameOffset(0);
    int forwardOffset  = m_onionSkinMask.getShiftTraceGhostFrameOffset(1);
    // If F1, F2 or F3 key is pressed, then only
    // display the corresponding ghost
    int flipKey = m_onionSkinMask.getGhostFlipKey();
    if (Qt::Key_F1 <= flipKey && flipKey <= Qt::Key_F3) {
      if (flipKey == Qt::Key_F1 && previousOffset != 0) {
        addGhost(0, row + previousOffset, true);
        return;
      } else if (flipKey == Qt::Key_F3 && forwardOffset != 0) {
        addGhost(1, row + forwardOffset, true);
        return;
      }
    }
    else {
      // draw the first ghost
      if (previousOffset != 0) addGhost(0, row + previousOffset);
      if (forwardOffset != 0) addGhost(1, row + forwardOffset);
    }
  }
  // Onion Skin
  else if (!m_onionSkinMask.isEmpty() && m_onionSkinMask.isEnabled()) {
    std::vector<int> rows;
    m_onionSkinMask.getAll(row, rows);
    std::vector<int>::iterator it = rows.begin();
    while (it != rows.end() && *it < row) ++it;
    std::sort(rows.begin(), it, descending);
    m_onionSkinDistance = 0;
    int frontPos = 0, backPos = 0;
    for (int i = 0; i < (int)rows.size(); i++) {
      const TFrameId &fid2 = level->index2fid(rows[i]);
      if (fid2 == fid) continue;
      players.push_back(Player());
      Player &player                  = players.back();
      player.m_sl                     = level;
      player.m_frame                  = level->guessIndex(fid);
      player.m_fid                    = fid2;
      player.m_isCurrentColumn        = true;
      player.m_isCurrentXsheetLevel   = true;
      player.m_isEditingLevel         = true;
      player.m_currentFrameId         = m_currentFrameId;
      player.m_isGuidedDrawingEnabled = m_isGuidedDrawingEnabled;
      player.m_guidedFrontStroke      = m_guidedFrontStroke;
      player.m_guidedBackStroke       = m_guidedBackStroke;
      player.m_isVisibleinOSM         = rows[i] >= 0;
#ifdef NUOVO_ONION
      player.m_onionSkinDistance = rows[i] - row;
#else
      player.m_onionSkinDistance = rows[i] - row < 0 ? --backPos : ++frontPos;
#endif
      player.m_dpiAff = getDpiAffine(level, fid2);
    }
  }
  players.push_back(Player());
  Player &player = players.back();
  player.m_sl    = level;
  player.m_frame = level->guessIndex(fid);
  player.m_fid   = fid;
  if (!m_onionSkinMask.isEmpty() && m_onionSkinMask.isEnabled())
    player.m_onionSkinDistance = 0;
  player.m_isCurrentColumn      = true;
  player.m_isCurrentXsheetLevel = true;
  player.m_isEditingLevel       = true;
  player.m_ancestorColumnIndex  = -1;
  player.m_dpiAff               = getDpiAffine(level, fid);
}
References OnionSkinMask::getAll(), TXshSimpleLevel::guessIndex(), TXshSimpleLevel::index2fid(), Stage::Player::m_ancestorColumnIndex, Stage::Player::m_bingoOrder, Stage::Player::m_dpiAff, Stage::Player::m_fid, Stage::Player::m_frame, Stage::Player::m_isCurrentColumn, Stage::Player::m_isCurrentXsheetLevel, Stage::Player::m_onionSkinDistance, Stage::Player::m_opacity, Stage::Player::m_placement, and Stage::Player::m_sl.
Referenced by Stage::visit().
visit()
void StageBuilder::visit (PlayerSet & players, Visitor & visitor, bool isPlaying = false)
Recall visitor.onImage(player) for each player contained in players vector.
{
  std::vector<int> masks;
  int m                = players.size();
  int h                = 0;
  bool stopMotionShown = false;
  for (; h < m; h++) {
    Player &player = players[h];
    unsigned int i = 0;
    // vale solo per TAB pro
    for (; i < masks.size() && i < player.m_masks.size(); i++)
      if (masks[i] != player.m_masks[i]) break;
    // vale solo per TAB pro
    if (i < masks.size() || i < player.m_masks.size()) {
      while (i < masks.size()) {
        masks.pop_back();
        visitor.disableMask();
      }
      while (i < player.m_masks.size()) {
        int maskIndex = player.m_masks[i];
        visitor.beginMask();
        visit(*m_maskPool[maskIndex], visitor, isPlaying);
        visitor.endMask();
        masks.push_back(maskIndex);
        visitor.enableMask();
        i++;
      }
    }
    player.m_isPlaying = isPlaying;
#if defined(x64)
    if (m_liveViewImage && player.m_sl == m_liveViewPlayer.m_sl) {
      if (m_lineupImage) {
        m_lineupPlayer.m_sl = NULL;
        visitor.onRasterImage(m_lineupImage.getPointer(), m_lineupPlayer);
        stopMotionShown = true;
      }
      if (m_liveViewImage) {
        m_liveViewPlayer.m_sl = NULL;
        visitor.onRasterImage(m_liveViewImage.getPointer(), m_liveViewPlayer);
        stopMotionShown = true;
      }
    } else {
      visitor.onImage(player);
    }
  }
  if (!stopMotionShown && (m_liveViewImage || m_lineupImage)) {
    if (m_lineupImage) {
      m_lineupPlayer.m_sl = NULL;
      visitor.onRasterImage(m_lineupImage.getPointer(), m_lineupPlayer);
    }
    if (m_liveViewImage) {
      m_liveViewPlayer.m_sl = NULL;
      visitor.onRasterImage(m_liveViewImage.getPointer(), m_liveViewPlayer);
    }
#else
    visitor.onImage(player);
#endif
  }
  // vale solo per TAB pro
  for (h = 0; h < (int)masks.size(); h++) visitor.disableMask();
}
References Stage::Player::m_isPlaying, Stage::Player::m_sl, Stage::Visitor::onImage(), and visit().
Referenced by visit(), and Stage::visit().
Member Data Documentation
m_ancestorColumnIndex
int StageBuilder::m_ancestorColumnIndex
m_ancestors
std::vector<TXshColumn *> StageBuilder::m_ancestors
m_camera3d
bool StageBuilder::m_camera3d
m_cameraPlacement
ZPlacement StageBuilder::m_cameraPlacement
m_currentColumnIndex
int StageBuilder::m_currentColumnIndex
m_currentFrameId
TFrameId StageBuilder::m_currentFrameId
m_currentXsheetLevel
int StageBuilder::m_currentXsheetLevel
m_fade
double StageBuilder::m_fade
m_guidedBackStroke
int StageBuilder::m_guidedBackStroke = -1
m_guidedFrontStroke
int StageBuilder::m_guidedFrontStroke = -1
m_isGuidedDrawingEnabled
int StageBuilder::m_isGuidedDrawingEnabled
m_maskPool
std::vector<PlayerSet *> StageBuilder::m_maskPool
m_masks
std::vector<int> StageBuilder::m_masks
m_onionSkinDistance
int StageBuilder::m_onionSkinDistance
m_onionSkinMask
OnionSkinMask StageBuilder::m_onionSkinMask
m_placementStack
std::vector<ZPlacement> StageBuilder::m_placementStack
m_players
PlayerSet StageBuilder::m_players
m_shiftTraceGhostId
ShiftTraceGhostId StageBuilder::m_shiftTraceGhostId
m_subXSheetStack
std::vector<SubXSheet> StageBuilder::m_subXSheetStack
m_vs
const ImagePainter::VisualSettings* StageBuilder::m_vs
m_xsheetLevel
int StageBuilder::m_xsheetLevel
The documentation for this class was generated from the following file:
E:/opentoonz/toonz/sources/toonzlib/stage.cpp