opentoonz: TStopWatch Class Reference
TStopWatch Class Reference
Public Member Functions
TStopWatch (std::string name="")
void reset ()
void start (bool resetFlag=false)
void stop ()
TUINT32 getTotalTime ()
TUINT32 getUserTime ()
TUINT32 getSystemTime ()
const std::string & getName ()
void setName (std::string name)
operator std::string ()
void print (std::ostream &out)
void print ()
Static Public Member Functions
static TStopWatch & global (int index)
static void printGlobals (std::ostream &out)
static void printGlobals ()
Detailed Description
Constructor & Destructor Documentation
TStopWatch()
TStopWatch::TStopWatch (std::string name = "")
    : m_name(name), m_active(false), m_isRunning(false) {
  if (timerToUse == TTUUnknown) determineTimer();
  m_start = 0;
#ifdef _WIN32
  m_startUser.dwHighDateTime = m_startUser.dwLowDateTime = 0;
  m_startSystem.dwHighDateTime = m_startSystem.dwLowDateTime = 0;
#else
  m_startUser               = 0;
  m_startSystem             = 0;
#endif  //_WIN32
  m_tm       = 0;
  m_tmUser   = 0;
  m_tmSystem = 0;
}
~TStopWatch()
TStopWatch::~TStopWatch ()
{ m_active = false; }
Member Function Documentation
getName()
const std::string & TStopWatch::getName () inline
{ return m_name; };
getSystemTime()
TUINT32 TStopWatch::getSystemTime ()
Returns the amount of time that the process has spent executing operating system code. see getTotalTime()
{
  TM_TOTAL tm;
  TM_USER user;
  TM_SYSTEM system;
  getElapsedTime(tm, user, system);
#ifdef _WIN32
  return (TINT32)(system / 10000);
#else
  return (TINT32)(system * 1000) / STW_TICKS_PER_SECOND;
#endif  //_WIN32
}
getTotalTime()
TUINT32 TStopWatch::getTotalTime ()
Returns the number of milliseconds that have elapsed in all the start()-stop() intervals since the stopWatch was reset up to the getTotalTime() call. The method can be called during a start()-stop() interval
{
  TM_TOTAL tm;
  TM_USER user;
  TM_SYSTEM system;
  getElapsedTime(tm, user, system);
#ifdef _WIN32
  return tm;
#else
  return (TINT32)(tm * 1000) / STW_TICKS_PER_SECOND;
#endif  //_WIN32
}
Referenced by TRasterFx::compute().
getUserTime()
TUINT32 TStopWatch::getUserTime ()
Returns the amount of time that the process has spent executing application code. see getTotalTime()
{
  TM_TOTAL tm;
  TM_USER user;
  TM_SYSTEM system;
  getElapsedTime(tm, user, system);
#ifdef _WIN32
  return (TINT32)(user / 10000);
#else
  return (TINT32)(user * 1000) / STW_TICKS_PER_SECOND;
#endif  //_WIN32
}
global()
static TStopWatch & TStopWatch::global (int index) inline static
TStopWatch::global(index) is a global array of 10 stop watches.
{
    assert(0 <= index && index < 10);
    return StopWatch[index];
  };
Referenced by RenderTask::run().
operator std::string()
TStopWatch::operator std::string ()
Returns a string containing the recorded times.
print() [1/2]
void TStopWatch::print ()
{ print(cout); }
print() [2/2]
void TStopWatch::print (std::ostream & out)
Print (to cout) the name and the relative total,user and system times of the stop watch. see getTotalTime()
printGlobals() [1/2]
void TStopWatch::printGlobals () static
{ printGlobals(cout); }
printGlobals() [2/2]
static void TStopWatch::printGlobals (std::ostream & out) static
Allows you to print the name and the relative total, user and system times of all the active stop watches.
reset()
void TStopWatch::reset ()
                       {
  m_tm       = 0;
  m_tmUser   = 0;
  m_tmSystem = 0;
  setStartToCurrentTime();
}
setName()
void TStopWatch::setName (std::string name) inline
{ m_name = name; };
start()
void TStopWatch::start (bool resetFlag = false)
Start the stop watch. If reset=true the stop watch is firstly reset.
{
  if (resetFlag) reset();
  if (m_isRunning) return;
  m_active    = true;
  m_isRunning = true;
  setStartToCurrentTime();
}
Referenced by TRasterFx::compute(), and RenderTask::run().
stop()
void TStopWatch::stop ()
                      {
  if (!m_isRunning) return;
  m_isRunning = false;
#ifdef _WIN32
  if (timerToUse == TTUTickCount)
    checkTime(m_start, m_startUser, m_startSystem, m_tm, m_tmUser, m_tmSystem);
  else
    hrCheckTime(m_hrStart, m_startUser, m_startSystem, m_tm, m_tmUser,
                m_tmSystem);
#else
  checkTime(m_start, m_startUser, m_startSystem, m_tm, m_tmUser, m_tmSystem);
#endif
}
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/tstopwatch.h
E:/opentoonz/toonz/sources/common/tcore/tstopwatch.cpp