opentoonz: TPersist Class Reference
TPersist Class Reference abstract
#include <tpersist.h>
Public Types
typedef TPersist * CreateProc()
Public Member Functions
virtual void loadData (TIStream &is)=0
virtual void saveData (TOStream &os)=0
std::string getStreamTag () const
virtual const TPersistDeclaration * getDeclaration () const =0
Static Public Member Functions
static void declare (CreateProc *)
static TPersist * create (const std::string &name)
Detailed Description
This is an abstract class for load and save data from and to the file system (i.e files on the disk)
Member Typedef Documentation
CreateProc
typedef TPersist * TPersist::CreateProc()
Constructor & Destructor Documentation
~TPersist()
virtual TPersist::~TPersist () inline virtual
{};
Member Function Documentation
create()
TPersist * TPersist::create (const std::string & name) static
If the object identified by name doesn't exist, this method creates it through TPersistDeclarationT class template.
See also
getDeclaration()
{
  return TPersistFactory::instance()->create(name);
}
References create().
Referenced by create(), TStageObjectTree::getStageObject(), and TIStream::operator>>().
getDeclaration()
virtual const TPersistDeclaration * TPersist::getDeclaration () const pure virtual
      This pure virtual method is used to define a global pointer to the
object. This method is overridden with the macro PERSIST_DECLARATION(T).
For example:
class DVAPI TStageObjectTree final : public TPersist {
PERSIST_DECLARATION(TStageObjectTree)
public:
...
Implemented in TFarmTask, TFarmTaskGroup, TLevelColumnFx, TPaletteColumnFx, TZeraryColumnFx, TXsheetFx, TOutputFx, CtrlFarmTask, and RasterFxPluginHost.
Referenced by TRasterFx::compute(), and getStreamTag().
getStreamTag()
std::string TPersist::getStreamTag () const inline
 Returns the string identifier of the object. For example a TXsheet
object is identified by "xsheet", a TStageObjectTree is identified by PegbarTree.
{
  return getDeclaration()->getId();
}
References getDeclaration().
Referenced by TOStream::operator<<().
loadData()
virtual void TPersist::loadData (TIStream & is) pure virtual
 This is a pure virtual function and must be overridden with a method
that implements the object loading from a stream (i.e take the object's features from a formatted data stream). For example the TStageObject class use his implementation to take the values of the parameters that characterizes a stage object as name, coordinates, etc... from a file. is is an input file stream
Implemented in TParamSet, PlasticSkeletonVertex, PlasticSkeleton, PlasticSkeletonVertexDeformation, PlasticSkeletonDeformation, ShaderInterface::ParameterConcept, ShaderInterface::Parameter, ShaderInterface::ShaderData, ShaderInterface, TDoubleParam, TExternalProgramFx, TFarmTask, TFarmTaskGroup, TFx, TMacroFx, TTextureMesh, TIntParam, TBoolParam, TFilePathParam, TStringParam, TEnumParam, TNADoubleParam, TFontParam, TLevelColumnFx, TZeraryColumnFx, TStageObjectSpline, TStageObjectTree, TXshChildLevel, TXsheet, TXshLevelColumn, TXshMeshColumn, TXshPaletteColumn, TXshPaletteLevel, TXshSimpleLevel, TXshSoundColumn, TXshSoundLevel, TXshSoundTextColumn, TXshSoundTextLevel, TXshZeraryFxColumn, TXshZeraryFxLevel, VectorizerParameters, TPalette, TPointParam, TPixelParam, TRangeParam, TPersistSet, TSpectrumParam, TToneCurveParam, BrushData, VectorBrushData, CtrlFarmTask, and TXshLevel.
Referenced by TFx::loadData(), and TIStream::operator>>().
saveData()
virtual void TPersist::saveData (TOStream & os) pure virtual
 This is a pure virtual function and must be overridden with a method
that implements the object saving to a data stream (i.e put the object's features on a formatted data stream). For example the TStageObject class use his implementation to save the values of the parameters that characterizes a stage object as name, coordinates, etc... on a file os is an output file stream.
Implemented in TParamSet, TXshMeshColumn, TXshPaletteColumn, PlasticSkeletonVertex, PlasticSkeleton, PlasticSkeletonVertexDeformation, PlasticSkeletonDeformation, ShaderInterface::ParameterConcept, ShaderInterface::Parameter, ShaderInterface::ShaderData, ShaderInterface, TDoubleParam, TExternalProgramFx, TFarmTask, TFarmTaskGroup, TFx, TMacroFx, TTextureMesh, TIntParam, TBoolParam, TFilePathParam, TStringParam, TEnumParam, TNADoubleParam, TFontParam, TLevelColumnFx, TZeraryColumnFx, TStageObjectSpline, TStageObjectTree, TXshChildLevel, TXsheet, TXshLevelColumn, TXshPaletteLevel, TXshSimpleLevel, TXshSoundColumn, TXshSoundLevel, TXshSoundTextColumn, TXshSoundTextLevel, TXshZeraryFxColumn, TXshZeraryFxLevel, VectorizerParameters, TPalette, TPointParam, TPixelParam, TRangeParam, TPersistSet, TSpectrumParam, TToneCurveParam, BrushData, VectorBrushData, CtrlFarmTask, and TXshLevel.
Referenced by TOStream::operator<<(), and TFx::saveData().
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/tpersist.h
E:/opentoonz/toonz/sources/common/tstream/tstream.cpp