opentoonz: TPropertyGroup Class Reference
TPropertyGroup Class Reference
Classes
class PropertyNotFoundError
Public Types
typedef std::vector< std::pair< TProperty *, bool > > PropertyVector
typedef std::map< std::string, TProperty * > PropertyTable
Public Member Functions
virtual TPropertyGroup * clone () const
void add (TProperty *p)
get ownership
void bind (TProperty &p)
don't get ownership
TProperty * getProperty (std::string name)
returns 0 if the property doesn't exist
TProperty * getProperty (int i)
void setProperties (TPropertyGroup *g)
void accept (TProperty::Visitor &v)
int getPropertyCount () const
void loadData (TIStream &is)
void saveData (TOStream &os) const
void clear ()
virtual void updateTranslation ()
void assignUINames (TPropertyGroup *refPg)
Detailed Description
Member Typedef Documentation
PropertyTable
typedef std::map<std::string, TProperty *> TPropertyGroup::PropertyTable
PropertyVector
typedef std::vector<std::pair<TProperty *, bool> > TPropertyGroup::PropertyVector
Constructor & Destructor Documentation
TPropertyGroup()
TPropertyGroup::TPropertyGroup ()
{}
~TPropertyGroup()
TPropertyGroup::~TPropertyGroup () virtual
{
  for (PropertyVector::iterator it = m_properties.begin();
       it != m_properties.end(); ++it)
    if (it->second) delete it->first;
}
Member Function Documentation
accept()
void TPropertyGroup::accept (TProperty::Visitor & v)
{
  for (PropertyVector::const_iterator i = m_properties.begin();
       i != m_properties.end(); ++i)
    i->first->accept(v);
}
add()
void TPropertyGroup::add (TProperty * p)
get ownership
{
  std::string name = p->getName();
  assert(m_table.find(name) == m_table.end());
  m_properties.push_back(std::make_pair(p, true));
  m_table[name] = p;
}
assignUINames()
void TPropertyGroup::assignUINames (TPropertyGroup * refPg)
{
  for (PropertyVector::const_iterator i = m_properties.begin();
       i != m_properties.end(); ++i) {
    TProperty *refP = refPg->getProperty(i->first->getName());
    if (refP) i->first->assignUIName(refP);
  }
}
bind()
void TPropertyGroup::bind (TProperty & p)
don't get ownership
{
  std::string name = p.getName();
  assert(m_table.find(name) == m_table.end());
  m_properties.push_back(std::make_pair(&p, false));
  m_table[name] = &p;
}
clear()
void TPropertyGroup::clear ()
{
  m_properties.clear();
  m_table.clear();
}
clone()
TPropertyGroup * TPropertyGroup::clone () const virtual
{
  TPropertyGroup *g = new TPropertyGroup();
  for (PropertyVector::const_iterator i = m_properties.begin();
       i != m_properties.end(); ++i)
    g->add(i->first->clone());
  return g;
}
getProperty() [1/2]
TProperty * TPropertyGroup::getProperty (int i) inline
{
    return (i >= (int)m_properties.size()) ? 0 : m_properties[i].first;
  }
getProperty() [2/2]
TProperty * TPropertyGroup::getProperty (std::string name)
returns 0 if the property doesn't exist
{
  PropertyTable::iterator i = m_table.find(name);
  if (i == m_table.end())
    return 0;
  else
    return i->second;
}
Referenced by TSceneProperties::loadData(), RenderCommand::multimediaRender(), and ToolOptionParamRelayField::onValueChanged().
getPropertyCount()
int TPropertyGroup::getPropertyCount () const inline
{ return (int)m_properties.size(); }
loadData()
void TPropertyGroup::loadData (TIStream & is)
{
  for (PropertyVector::iterator it = m_properties.begin();
       it != m_properties.end(); ++it)
    if (it->second) delete it->first;
  m_properties.clear();
  m_table.clear();
  std::string tagName;
  while (is.matchTag(tagName)) {
    if (tagName == "property") {
      std::string name   = is.getTagAttribute("name");
      std::string type   = is.getTagAttribute("type");
      std::string svalue = is.getTagAttribute("value");
      if (name == "") throw TException("missing property name");
      if (type == "") throw TException("missing property type");
      if (type != "string" && svalue == "")
        throw TException("missing property value");
      if (type == "double") {
        double min = std::stod(is.getTagAttribute("min"));
        double max = std::stod(is.getTagAttribute("max"));
        add(new TDoubleProperty(name, min, max, std::stod(svalue)));
      }
      if (type == "pair") {
        double min = std::stod(is.getTagAttribute("min"));
        double max = std::stod(is.getTagAttribute("max"));
        TDoublePairProperty::Value v(0, 0);
        int i = svalue.find(' ');
        if (i != (int)std::string::npos) {
          v.first  = std::stod(svalue.substr(0, i));
          v.second = std::stod(svalue.substr(i + 1));
        }
        add(new TDoublePairProperty(name, min, max, v.first, v.second));
      } else if (type == "int") {
        int min = std::stoi(is.getTagAttribute("min"));
        int max = std::stoi(is.getTagAttribute("max"));
        add(new TIntProperty(name, min, max, std::stoi(svalue)));
      } else if (type == "bool") {
        if (svalue != "true" && svalue != "false")
          throw TException("bad boolean property value");
        add(new TBoolProperty(name, svalue == "true" ? true : false));
      } else if (type == "string") {
        add(new TStringProperty(name, ::to_wstring(svalue)));
      } else if (type == "enum") {
        TEnumProperty *p = new TEnumProperty(name);
        if (is.isBeginEndTag())
          p->addValue(::to_wstring(svalue));
        else {
          while (is.matchTag(tagName)) {
            if (tagName == "item") {
              std::string item = is.getTagAttribute("value");
              p->addValue(::to_wstring(item));
            } else
              throw TException("expected range property <item>");
          }
          is.closeChild();
        }
        p->setValue(::to_wstring(svalue));
        add(p);
      } else
        throw TException("unrecognized property type : " + type);
    } else
      throw TException("expected <property>");
    // is.closeChild();
  }
}
saveData()
void TPropertyGroup::saveData (TOStream & os) const
{
  PropertyWriter writer(os);
  const_cast<TPropertyGroup *>(this)->accept(writer);
}
setProperties()
void TPropertyGroup::setProperties (TPropertyGroup * g)
{
  for (PropertyVector::const_iterator i = g->m_properties.begin();
       i != g->m_properties.end(); ++i) {
    TProperty *src = i->first;
    TProperty *dst = getProperty(src->getName());
    if (dst) {
      Setter setter(src);
      TProperty::Visitor *visitor = &setter;
      dst->accept(*visitor);
    }
  }
}
updateTranslation()
virtual void TPropertyGroup::updateTranslation () inline virtual
{};
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/tproperty.h
E:/opentoonz/toonz/sources/common/tproperty.cpp