opentoonz: TStroke Struct Reference
TStroke Struct Reference final
#include <tstroke.h>
Classes
struct Imp
Public Types
enum CapStyle { BUTT_CAP = 0 , ROUND_CAP , PROJECTING_CAP }
enum JoinStyle { MITER_JOIN = 0 , ROUND_JOIN , BEVEL_JOIN }
typedef BYTE TStrokeFlag
Public Types inherited from TSmartObject
typedef short ClassCode
Public Member Functions
TStroke (const TStroke &stroke)
to be erased
TStroke & operator= (const TStroke &other)
to be erased
TStroke ()
Constructor.
TStroke (const std::vector< TThickPoint > &)
Build a stroke from an array of ThickPoint.
TStroke (const std::vector< TPointD > &v)
Build a stroke from an array of TPointD.
void invalidate ()
bool getNearestChunk (const TPointD &p, double &outT, int &chunkIndex, double &distance2, bool checkBBox=true) const
computes outlines (only if it's needed). call it before drawing.
bool getNearestW (const TPointD &p, double &outW, double &distance2, bool checkBBox=true) const
int getNearChunks (const TThickPoint &p, std::vector< TThickPoint > &pointsOnStroke, bool checkBBox=true) const
int getChunkCount () const
int getControlPointCount () const
Return number of control points in a stroke.
void getControlPoints (std::vector< TThickPoint > &v) const
TThickPoint getControlPoint (int n) const
TThickPoint getControlPointAtParameter (double w) const
int getControlPointIndexAfterParameter (double w) const
void setControlPoint (int n, const TThickPoint &pos)
void setControlPoint (int n, const TPointD &pos)
void reshape (const TThickPoint pos[], int count)
Reshape stroke.
const TThickQuadratic * getChunk (int index) const
TRectD getBBox (double w0=0.0, double w1=1.0) const
Return the bbox of the stroke.
void computeBBox ()
TRectD getCenterlineBBox () const
Return the bbox of the stroke without thickness.
double getLength (int chunk, double t) const
Returns the length of the stroke at passed chunk-param.
double getLength (double w0, double w1) const
Return length of a stroke.
double getLength (double w1=1.0) const
Return length of a stroke.
double getApproximateLength (double w0, double w1, double error) const
Return approximate length of a stroke.
void insertControlPointsAtLength (double s)
void insertControlPoints (double w)
void reduceControlPoints (double maxError)
Reduce the number of control point according to maxError parameter.
void reduceControlPoints (double maxError, std::vector< int > corners)
TThickPoint getThickPoint (double w) const
TPointD getPoint (double w) const
TThickPoint getThickPointAtLength (double s) const
TPointD getPointAtLength (double s) const
double getParameterAtLength (double s) const
double getParameterAtControlPoint (int n) const
double getLengthAtControlPoint (int) const
Return the stroke leght at passed control point.
void disableComputeOfCaches ()
Freeze parameter of a stroke in last valid status.
void enableComputeOfCaches ()
double getW (const TPointD &) const
Return parameter w at point position.
double getW (int chunkIndex, double t) const
TPointD getSpeed (double w, bool outSpeed=false) const
Get speed at parameter w.
bool getSpeedTwoValues (double w, TPointD &speed0, TPointD &speed1) const
Returns true if speed1!=speed0, so it is an edge in w.
TPointD getSpeedAtLength (double s) const
Get speed at length s.
void split (double w, TStroke &f, TStroke &s) const
void swap (TStroke &ref)
Swap the contents of two strokes.
void swapGeometry (TStroke &ref)
Swapd the geometrical data of two strokes.
void transform (const TAffine &aff, bool doChangeThickness=false)
Transform a stroke using an affine.
int getStyle () const
void setStyle (int styleId)
TStrokeProp * getProp () const
Return a TStrokeProp.
void setProp (TStrokeProp *prop)
Set TSrokePrope of a stroke.
void print (std::ostream &os=std::cout) const
Only for debug.
TStroke & changeDirection ()
change tangent versus in the stroke
void setFlag (TStrokeFlag flag, bool status)
Set TStrokeFlag of the stroke.
bool getFlag (TStrokeFlag flag) const
Return TStrokeFlag of the stroke.
bool getChunkAndT (double w, int &chunk, double &t) const
bool getChunkAndTAtLength (double s, int &chunk, double &t) const
TThickPoint getCentroid () const
void setSelfLoop (bool loop=true)
Set a loop stroke.
bool isSelfLoop () const
Return true if the stroke is looped.
bool isCenterLine () const
Return true if all control points have negative thickness.
int getId () const
void setId (int id)
double getAverageThickness () const
Return the average value of stroke thickness.
double getMaxThickness ()
void setAverageThickness (double thickness)
Set the average value of stroke thickness to thickness.
bool operator== (const TStroke &s) const
bool operator!= (const TStroke &s) const
OutlineOptions & outlineOptions ()
const OutlineOptions & outlineOptions () const
OutlineOptions ()
OutlineOptions (UCHAR capStyle, UCHAR JoinStyle, double lower, double upper)
Public Member Functions inherited from TSmartObject
TSmartObject (ClassCode classCode)
void addRef ()
void release ()
TINT32 getRefCount () const
Static Public Member Functions
static TStroke * interpolate (const std::vector< TThickPoint > &points, double error, bool findCorners=true)
Get a stroke from a TThickPoint vector.
static TStroke * create (const std::vector< TThickQuadratic * > &curves)
Get a stroke from a TThickQuadratic vector.
Static Public Member Functions inherited from TSmartObject
static TINT32 getInstanceCount (ClassCode code)
Public Attributes
UCHAR m_capStyle
UCHAR m_joinStyle
double m_miterLower
double m_miterUpper
Static Public Attributes
static const TStrokeFlag c_selected_flag = 0x1
static const TStrokeFlag c_changed_region_flag = 0x2
static const TStrokeFlag c_dirty_flag = 0x4
Detailed Description
This is the new release of TStroke (Version 4). It's possible to use style to set brush, texture, pattern, TStroke now are smart pointer.
Contains complementary stroke parameters used in the process of transforming the raw (centerline) stroke data in its drawable (outline) form.
Member Typedef Documentation
TStrokeFlag
typedef BYTE TStroke::TStrokeFlag
Member Enumeration Documentation
CapStyle
enum TStroke::CapStyle
{ BUTT_CAP = 0, ROUND_CAP, PROJECTING_CAP };
JoinStyle
enum TStroke::JoinStyle
{ MITER_JOIN = 0, ROUND_JOIN, BEVEL_JOIN };
Constructor & Destructor Documentation
TStroke() [1/4]
TStroke::TStroke (const TStroke & stroke)
to be erased
    : TSmartObject(m_classCode), m_imp(new TStroke::Imp()) {
  m_imp->m_bBox           = other.getBBox();
  m_imp->m_isValidLength  = other.m_imp->m_isValidLength;
  m_imp->m_isOutlineValid = other.m_imp->m_isOutlineValid;
  m_imp->m_areDisabledComputeOfCaches =
      other.m_imp->m_areDisabledComputeOfCaches;
  m_imp->m_flag           = other.m_imp->m_flag;
  m_imp->m_outlineOptions = other.m_imp->m_outlineOptions;
  // Are they sure as regards exceptions ?
  m_imp->m_centerLineArray.resize(other.m_imp->m_centerLineArray.size());
  int i;
  for (i = 0; i < (int)other.m_imp->m_centerLineArray.size(); i++)
    m_imp->m_centerLineArray[i] =
        new TThickQuadratic(*other.m_imp->m_centerLineArray[i]);
  // copy(  other.m_imp->m_centerLineArray.begin(),
  //   other.m_imp->m_centerLineArray.end(),
  //   TThickQuadraticArrayInsertIterator(m_imp->m_centerLineArray));
  copy(other.m_imp->m_partialLengthArray.begin(),
       other.m_imp->m_partialLengthArray.end(),
       back_inserter<DoubleArray>(m_imp->m_partialLengthArray));
  copy(other.m_imp->m_parameterValueAtControlPoint.begin(),
       other.m_imp->m_parameterValueAtControlPoint.end(),
       back_inserter<DoubleArray>(m_imp->m_parameterValueAtControlPoint));
  m_imp->m_styleId = other.m_imp->m_styleId;
  m_imp->m_prop =
      0;  // other.m_imp->m_prop ? other.m_imp->m_prop->clone(this) : 0;
  m_imp->m_selfLoop                = other.m_imp->m_selfLoop;
  m_imp->m_negativeThicknessPoints = other.m_imp->m_negativeThicknessPoints;
}
References getBBox().
TStroke() [2/4]
TStroke::TStroke ()
Constructor.
                 : TSmartObject(m_classCode) {
  vector<TThickPoint> p(3);
  p[0] = TThickPoint(0, 0, 0);
  p[1] = p[0];
  p[2] = p[1];
  m_imp.reset(new TStroke::Imp(p));
  /*
// da fissare deve trovarsi prima della init
m_imp->m_centerLineArray.push_back (new TThickQuadratic);
*/
}
Referenced by create(), and split().
TStroke() [3/4]
TStroke::TStroke (const std::vector< TThickPoint > & v)
Build a stroke from an array of ThickPoint.
TStroke constructor build a stroke from an array of control points. If chunks are n control points are 2*n+1.
Note
Common control points between two chunks are supposed not replicated.
    : TSmartObject(m_classCode), m_imp(new TStroke::Imp(v)) {}
TStroke() [4/4]
TStroke::TStroke (const std::vector< TPointD > & v)
Build a stroke from an array of TPointD.
TStroke constructor build a stroke from an array of control points. If chunks are n control points are 2*n+1.
Note
Common control points between two chunks are supposed not replicated, and thickness is equal 0.
    : TSmartObject(m_classCode), m_imp(new TStroke::Imp(v)) {}
~TStroke()
TStroke::~TStroke ()
{}
Member Function Documentation
changeDirection()
TStroke & TStroke::changeDirection ()
change tangent versus in the stroke
change tangent versus in a stroke
Note
Change versus of all thickquadratric and change its position in list
{
  UINT chunkCount = getChunkCount();
  UINT to         = tfloor(chunkCount * 0.5);
  UINT i;
  if (chunkCount & 1) changeTQDirection(m_imp->m_centerLineArray[to]);
  --chunkCount;
  for (i = 0; i < to; ++i) {
    changeTQDirection(m_imp->m_centerLineArray[i]);
    changeTQDirection(m_imp->m_centerLineArray[chunkCount - i]);
    TThickQuadratic *q1         = m_imp->m_centerLineArray[i];
    m_imp->m_centerLineArray[i] = m_imp->m_centerLineArray[chunkCount - i];
    m_imp->m_centerLineArray[chunkCount - i] = q1;
  }
  invalidate();
  return *this;
}
References getChunkCount(), and invalidate().
computeBBox()
void TStroke::computeBBox ()
{
  m_imp->m_bBox = TOutlineUtil::computeBBox(*this);
  m_imp->m_flag &= ~c_dirty_flag;
}
create()
TStroke * TStroke::create (const std::vector< TThickQuadratic * > & curves) static
Get a stroke from a TThickQuadratic vector.
Restituisce uno stroke da un vettore di TThickQuadratic.
Take from curves the control points used to create the stroke
Estrae dalle curve i punti di controllo e crea con questi un nuovo stroke
{
  if (curves.empty()) return 0;
  // make a vector of control points
  vector<TThickPoint> ctrlPnts;
  extractStrokeControlPoints(curves, ctrlPnts);
  TStroke *stroke = new TStroke(ctrlPnts);
  stroke->invalidate();
  return stroke;
}
References invalidate(), and TStroke().
Referenced by split().
disableComputeOfCaches()
void TStroke::disableComputeOfCaches ()
Freeze parameter of a stroke in last valid status.
{
  m_imp->m_areDisabledComputeOfCaches = true;
}
Referenced by ToonzExt::StrokeDeformationImpl::activate_impl().
enableComputeOfCaches()
void TStroke::enableComputeOfCaches ()
{
  m_imp->m_areDisabledComputeOfCaches = false;
}
getApproximateLength()
double TStroke::getApproximateLength (double w0, double w1, double error) const
Return approximate length of a stroke.
{
  m_imp->computeCacheVector();
  assert((int)m_imp->m_partialLengthArray.size() == getControlPointCount());
  if (w0 == w1) return 0.0;
  w0 = min(max(0.0, w0), 1.0);
  w1 = min(max(0.0, w1), 1.0);
  if (w0 > w1) std::swap(w0, w1);
  // vede se la lunghezza e' individuabile nella cache
  if (0.0 == w0) {
    vector<double>::iterator first;
    // trova l'iteratore alla prima posizione che risulta maggiore di w
    first = std::upper_bound(m_imp->m_parameterValueAtControlPoint.begin(),
                             m_imp->m_parameterValueAtControlPoint.end(),
                             w1 - TConsts::epsilon);
    if (first != m_imp->m_parameterValueAtControlPoint.end() &&
        *first < w1 + TConsts::epsilon) {
      int offset =
          distance(m_imp->m_parameterValueAtControlPoint.begin(), first);
      return m_imp->m_partialLengthArray[offset];
    }
  }
  int firstChunk, secondChunk;
  double firstT, secondT;
  // calcolo i chunk interessati ed i valori del parametro t
  bool val1 = m_imp->retrieveChunkAndItsParamameter(w0, firstChunk, firstT);
  assert(val1);
  bool val2 = m_imp->retrieveChunkAndItsParamameter(w1, secondChunk, secondT);
  assert(val2);
  if (firstChunk == secondChunk)
    return getChunk(firstChunk)->getApproximateLength(firstT, secondT, error);
  double totalLength = 0;
  totalLength += getChunk(firstChunk)->getApproximateLength(firstT, 1, error);
  // lunghezza dei pezzi intermedi
  for (int i = firstChunk + 1; i != secondChunk; i++)
    totalLength += getChunk(i)->getApproximateLength(0.0, 1.0, error);
  totalLength +=
      getChunk(secondChunk)->getApproximateLength(0.0, secondT, error);
  return totalLength;
}
References getChunk(), and getControlPointCount().
getAverageThickness()
double TStroke::getAverageThickness () const
Return the average value of stroke thickness.
{
  return m_imp->m_averageThickness;
}
Referenced by ToonzExt::cloneStrokeStatus().
getBBox()
TRectD TStroke::getBBox (double w0 = 0.0, double w1 = 1.0) const
Return the bbox of the stroke.
{
  if (w0 > w1) std::swap(w0, w1);
  if (w0 != 0.0 || w1 != 1.0) return m_imp->computeSubBBox(w0, w1);
  if (m_imp->m_flag & c_dirty_flag) ((TStroke *)this)->computeBBox();
  return m_imp->m_bBox;
}
Referenced by TVectorImage::addStroke(), TInbetween::Imp::computeTransformation(), PumpTool::draw(), and TStroke().
getCenterlineBBox()
TRectD TStroke::getCenterlineBBox () const
Return the bbox of the stroke without thickness.
{
  return m_imp->computeCenterlineBBox();
}
getCentroid()
TThickPoint TStroke::getCentroid () const
{
  double totalLen = getLength();
  if (totalLen == 0) return getControlPoint(0);
  double step           = totalLen * 0.1;
  double len            = 0;
  if (step > 10.0) step = 10.0;
  int count             = 0;
  TThickPoint point;
  for (; len <= totalLen; len += step) {
    count++;
    point += getThickPointAtLength(len);
  }
  return point * (1.0 / (double)count);
}
getChunk()
const TThickQuadratic * TStroke::getChunk (int index) const
Return chunk at position index If index is not valid return NULL
Note
it is used mainly for drawing
{
  return m_imp->getChunk(index);
}
Referenced by ToonzExt::StrokeDeformationImpl::activate_impl(), TStroke::Imp::computeCacheVector(), TInbetween::Imp::computeTransformation(), PumpTool::draw(), getApproximateLength(), getControlPoint(), getLength(), getSpeed(), getSpeedTwoValues(), getThickPoint(), getThickPointAtLength(), insertControlPoints(), insertControlPointsAtLength(), print(), TStroke::Imp::retrieveChunkAndItsParamameterAtLength(), and ControlPointEditorStroke::setStroke().
getChunkAndT()
bool TStroke::getChunkAndT (double w, int & chunk, double & t) const
Gets the chunk and its parameter at stroke parameter w; returns true if a chunk was found.
{
  return m_imp->retrieveChunkAndItsParamameter(w, chunk, t);
}
Referenced by PumpTool::draw().
getChunkAndTAtLength()
bool TStroke::getChunkAndTAtLength (double s, int & chunk, double & t) const
Gets the chunk and its parameter at stroke length s; returns true if a chunk was found.
{
  return m_imp->retrieveChunkAndItsParamameterAtLength(s, chunk, t);
}
getChunkCount()
int TStroke::getChunkCount () const
Returns
number of chunks in the stroke
{ return m_imp->getChunkCount(); }
Referenced by ToonzExt::StrokeDeformationImpl::activate_impl(), changeDirection(), TStroke::Imp::computeCacheVector(), TStroke::Imp::computeParameterInControlPoint(), TInbetween::Imp::computeTransformation(), PumpTool::draw(), getControlPoint(), getParameterAtLength(), getSpeed(), getSpeedTwoValues(), getW(), insertControlPoints(), print(), reduceControlPoints(), TStroke::Imp::retrieveChunkAndItsParamameterAtLength(), setControlPoint(), and split().
getControlPoint()
TThickPoint TStroke::getControlPoint (int n) const
Return the n-th control point
Note
n is clamped to [0,ControlPointCount-1] interval
n index of desired control point
{
  if (n <= 0) return m_imp->m_centerLineArray.front()->getThickP0();
  if (n >= getControlPointCount())
    return m_imp->m_centerLineArray.back()->getThickP2();
  // calcolo l'offset del chunk risolvendo l'equazione
  //  2 * chunkNumber + 1 = n
  //  chunkNumber = tceil((n - 1) / 2)
  int chunkNumber = tceil((n - 1) * 0.5);
  assert(chunkNumber <= getChunkCount());
  int pointOffset = n - chunkNumber * 2;
  if (chunkNumber == getChunkCount())  // e' l'ultimo punto della stroke
    return getChunk(chunkNumber - 1)->getThickP2();
  switch (pointOffset) {
  case 0:
    return getChunk(chunkNumber)->getThickP0();
  case 1:
    return getChunk(chunkNumber)->getThickP1();
  case 2:
    return getChunk(chunkNumber)->getThickP2();
  }
  assert("Not yet finished" && false);
  return getControlPoint(0);
}
References getChunk(), getChunkCount(), getControlPoint(), getControlPointCount(), TThickQuadratic::getThickP0(), TThickQuadratic::getThickP1(), and TThickQuadratic::getThickP2().
Referenced by ToonzExt::StrokeDeformationImpl::activate_impl(), ControlPointEditorStroke::addControlPoint(), TInbetween::Imp::computeTransformation(), ToonzExt::StrokeDeformationImpl::deactivate_impl(), getControlPoint(), getControlPointAtParameter(), TStrokeBenderDeformation::getDisplacementForControlPoint(), TStrokePointDeformation::getDisplacementForControlPoint(), ControlPointEditorStroke::getPointTypeAt(), getThickPoint(), getThickPointAtLength(), interpolate(), ControlPointEditorStroke::moveSegment(), ToonzExt::rotateControlPoint(), TStageObjectSpline::saveData(), setControlPoint(), setSelfLoop(), split(), and VectorizerCore::vectorize().
getControlPointAtParameter()
TThickPoint TStroke::getControlPointAtParameter (double w) const
Return control point nearest of parameter w.
Note
w is clamped to [0,1] interval
{
  if (w <= 0) return m_imp->m_centerLineArray.front()->getThickP0();
  if (w >= 1.0) return m_imp->m_centerLineArray.back()->getThickP2();
  vector<double>::iterator it_begin =
                               m_imp->m_parameterValueAtControlPoint.begin(),
                           first,
                           it_end = m_imp->m_parameterValueAtControlPoint.end();
  // find iterator at position greater or equal to w
  first = std::lower_bound(it_begin, it_end, w);
  assert(first != it_end);
  // now is possible to get control point
  // if( areAlmostEqual(*first, w, 0.1) )
  //  return  getControlPoint( distance(it_begin, first) );
  if (first == it_begin)
    return getControlPoint(0);
  else if ((*first - w) <= w - *(first - 1))
    return getControlPoint(distance(it_begin, first));
  else
    return getControlPoint(distance(it_begin, first - 1));
}
References getControlPoint().
Referenced by TStrokePointDeformation::getDelta(), TStrokeBenderDeformation::getDisplacement(), TStrokeTwirlDeformation::getDisplacement(), TStrokePointDeformation::getDisplacement(), and ToonzExt::rotateControlPoint().
getControlPointCount()
int TStroke::getControlPointCount () const
Return number of control points in a stroke.
Return number of control points in a stroke
Note
the control point in common between adjacent chunks is counted only once. e.g.: A n-chunk TStroke has n*2+1 CP
{
  return m_imp->getControlPointCount();
}
Referenced by ToonzExt::StrokeDeformationImpl::activate_impl(), ControlPointEditorStroke::addControlPoint(), TStroke::Imp::computeCacheVector(), TStroke::Imp::computeParameterInControlPoint(), TInbetween::Imp::computeTransformation(), ToonzExt::StrokeDeformationImpl::deactivate_impl(), getApproximateLength(), getControlPoint(), getLength(), getLengthAtControlPoint(), getParameterAtControlPoint(), getThickPoint(), getThickPointAtLength(), interpolate(), isCenterLine(), ControlPointEditorStroke::moveSegment(), ToonzExt::rotateControlPoint(), TStageObjectSpline::saveData(), RasterSelection::select(), setControlPoint(), setSelfLoop(), ControlPointEditorStroke::setStroke(), split(), transform(), and VectorizerCore::vectorize().
getControlPointIndexAfterParameter()
int TStroke::getControlPointIndexAfterParameter (double w) const
{
  const vector<double>::const_iterator
      begin = m_imp->m_parameterValueAtControlPoint.begin(),
      end   = m_imp->m_parameterValueAtControlPoint.end();
  vector<double>::const_iterator it = std::upper_bound(begin, end, w);
  if (it == end)
    return getControlPointCount();
  else
    return std::distance(begin, it);
}
getControlPoints()
void TStroke::getControlPoints (std::vector< TThickPoint > & v) const
{
  assert(v.empty());
  v.resize(m_imp->m_centerLineArray.size() * 2 + 1);
  v[0] = m_imp->m_centerLineArray[0]->getThickP0();
  for (UINT i = 0; i < m_imp->m_centerLineArray.size(); i++) {
    TThickQuadratic *q = m_imp->m_centerLineArray[i];
    v[2 * i + 1]       = q->getThickP1();
    v[2 * i + 2]       = q->getThickP2();
  }
}
getFlag()
bool TStroke::getFlag (TStrokeFlag flag) const
Return TStrokeFlag of the stroke.
{
  return (m_imp->m_flag & flag) != 0;
}
Referenced by TVectorImage::splitSelected().
getId()
int TStroke::getId () const
{ return m_imp->m_id; }
getLength() [1/3]
double TStroke::getLength (double w0, double w1) const
Return length of a stroke.
{
  if (w0 == w1) return 0.0;
  // If necessary, swap values
  w0 = min(max(0.0, w0), 1.0);
  w1 = min(max(0.0, w1), 1.0);
  if (w0 > w1) std::swap(w0, w1);
  // Retrieve s1
  int chunk;
  double t;
  bool ok = !m_imp->retrieveChunkAndItsParamameter(w1, chunk, t);
  assert(ok);
  double s1 = getLength(chunk, t);
  if (w0 == 0.0) return s1;
  // Retrieve s0
  ok = !m_imp->retrieveChunkAndItsParamameter(w0, chunk, t);
  assert(ok);
  return s1 - getLength(chunk, t);
}
References getLength().
getLength() [2/3]
double TStroke::getLength (double w1 = 1.0) const inline
Return length of a stroke.
{ return getLength(0.0, w1); }
References getLength().
Referenced by getLength().
getLength() [3/3]
double TStroke::getLength (int chunk, double t) const
Returns the length of the stroke at passed chunk-param.
{
  // Compute length caches
  m_imp->computeCacheVector();
  assert((int)m_imp->m_partialLengthArray.size() == getControlPointCount());
  if (t == 1.0) ++chunk, t = 0.0;
  double s = m_imp->m_partialLengthArray[chunk << 1];
  if (t > 0.0) s += getChunk(chunk)->getLength(t);
  return s;
}
References getChunk(), getControlPointCount(), and TQuadratic::getLength().
Referenced by ToonzExt::StrokeDeformationImpl::activate_impl(), TInbetween::Imp::computeTransformation(), PumpTool::draw(), TStrokeParamDeformation::getDelta(), TStrokeThicknessDeformation::getDelta(), TStrokeBenderDeformation::getDelta(), ToonzExt::StrokeParametricDeformer::getDelta(), TStrokeBenderDeformation::getDisplacement(), TStrokeParamDeformation::getDisplacement(), TStrokeThicknessDeformation::getDisplacement(), getLength(), getParameterAtLength(), getThickPointAtLength(), insertControlPointsAtLength(), ToonzExt::rotateControlPoint(), ToonzExt::NotSymmetricExpPotential::setParameters_(), ToonzExt::LinearPotential::setParameters_(), ToonzExt::NotSymmetricBezierPotential::setParameters_(), and ToonzExt::SquarePotential::setParameters_().
getLengthAtControlPoint()
double TStroke::getLengthAtControlPoint (int n) const
Return the stroke leght at passed control point.
{
  m_imp->computeCacheVector();
  if (n >= getControlPointCount()) return m_imp->m_partialLengthArray.back();
  if (n <= 0) return m_imp->m_partialLengthArray.front();
  return m_imp->m_partialLengthArray[n];
}
References getControlPointCount().
Referenced by TStrokeBenderDeformation::getDisplacementForControlPoint(), TStrokeParamDeformation::getDisplacementForControlPoint(), and TStrokeThicknessDeformation::getDisplacementForControlPoint().
getMaxThickness()
double TStroke::getMaxThickness ()
{
  if (m_imp->m_maxThickness == -1) m_imp->computeMaxThickness();
  return m_imp->m_maxThickness;
}
getNearChunks()
int TStroke::getNearChunks (const TThickPoint & p, std::vector< TThickPoint > & pointsOnStroke, bool checkBBox = true) const
\finds all points on stroke which are "enough" close to point p. return the number of such points.
{
  int currIndex    = -100;
  double currDist2 = 100000;
  for (UINT i = 0; i < m_imp->m_centerLineArray.size(); i++) {
    TThickQuadratic *q = m_imp->m_centerLineArray[i];
    if (checkBBox && !q->getBBox().enlarge(30).contains(p)) continue;
    double t       = q->getT(p);
    TThickPoint p1 = q->getThickPoint(t);
    double dist2   = tdistance2(p1, p);
    if (dist2 < (p1.thick + p.thick + 5) * (p1.thick + p.thick + 5)) {
      if (!pointsOnStroke.empty() &&
          areAlmostEqual(p1, pointsOnStroke.back(), 1e-3))
        continue;
      if (currIndex == i - 1) {
        if (dist2 < currDist2)
          pointsOnStroke.pop_back();
        else
          continue;
      }
      currIndex = i;
      currDist2 = dist2;
      pointsOnStroke.push_back(p1);
    }
  }
  return pointsOnStroke.size();  // dist2 < (numeric_limits<double>::max)();
}
References TQuadratic::getT(), and TThickQuadratic::getThickPoint().
getNearestChunk()
bool TStroke::getNearestChunk (const TPointD & p, double & outT, int & chunkIndex, double & distance2, bool checkBBox = true) const
computes outlines (only if it's needed). call it before drawing.
Returns
false if the bbox doesn't contain the point
p is input point to test
outT is parameter of minimum
chunkIndex is chunk of stroke where is minimum
distance2 is square distance of minimum
checkBBox (default true) is a flag to check or not in bounding box
{
  dist2 = (numeric_limits<double>::max)();
  for (UINT i = 0; i < m_imp->m_centerLineArray.size(); i++) {
    if (checkBBox &&
        !m_imp->m_centerLineArray[i]->getBBox().enlarge(30).contains(p))
      continue;
    double t    = (m_imp->m_centerLineArray)[i]->getT(p);
    double dist = tdistance2((m_imp->m_centerLineArray)[i]->getPoint(t), p);
    if (dist < dist2) {
      dist2      = dist;
      chunkIndex = i;
      outT       = t;
    }
  }
  return dist2 < (numeric_limits<double>::max)();
}
Referenced by getW().
getNearestW()
bool TStroke::getNearestW (const TPointD & p, double & outW, double & distance2, bool checkBBox = true) const
{
  double outT;
  int chunkIndex;
  bool ret      = getNearestChunk(p, outT, chunkIndex, dist2, checkBBox);
  if (ret) outW = getW(chunkIndex, outT);
  return ret;
}
getParameterAtControlPoint()
double TStroke::getParameterAtControlPoint (int n) const
Return parameter for a control point
Note
if control point is not on curve return middle value between two adjacent control point
{
  double out = -1;
  if (0 <= n && n < getControlPointCount()) out = m_imp->getW(n);
  /* FAB
assert(0.0 <= out &&
    out <= 1.0 );
*/
  if (0.0 > out) return 0.0;
  if (out > 1.0) return 1.0;
  return out;
}
References getControlPointCount().
Referenced by ToonzExt::StrokeParametricDeformer::getDisplacementForControlPoint(), getParameterAtLength(), ControlPointEditorStroke::getPointTypeAt(), and ControlPointEditorStroke::moveSegment().
getParameterAtLength()
double TStroke::getParameterAtLength (double s) const
Return parameter in (based on arc length)
{
  if (s <= 0)
    return 0;
  else if (s >= getLength())
    return 1;
  int chunk;
  double t;
  if (!m_imp->retrieveChunkAndItsParamameterAtLength(s, chunk, t)) {
    DoublePair p = m_imp->retrieveParametersFromChunk(chunk);
    return proportion(p.second, t, 1.0, p.first);
  } else if (chunk < (int)getChunkCount() && t == -1)
    return getParameterAtControlPoint(2 * chunk);
  return 1.0;
}
References getChunkCount(), getLength(), and getParameterAtControlPoint().
Referenced by PumpTool::draw(), ToonzExt::StrokeParametricDeformer::getDelta(), getSpeedAtLength(), and ToonzExt::rotateControlPoint().
getPoint()
TPointD TStroke::getPoint (double w) const inline
same that getThickPoint but return a TPointD
{ return convert(getThickPoint(w)); }
Referenced by ToonzExt::StrokeDeformationImpl::activate_impl(), ToonzExt::CornerDeformation::check_(), ToonzExt::StrokeDeformationImpl::deactivate_impl(), PumpTool::draw(), VectorTapeTool::draw(), ControlPointEditorStroke::getPointTypeAt(), and EraserTool::leftButtonDoubleClick().
getPointAtLength()
TPointD TStroke::getPointAtLength (double s) const inline
same that getThickPointAtLength but return a TPointD
{
    return convert(getThickPointAtLength(s));
  }
getProp()
TStrokeProp * TStroke::getProp () const
Return a TStrokeProp.
{
#if !defined(DISEGNO_OUTLINE)
  if (!m_imp->m_styleId) return 0;
#endif
  /*
TColorStyle * style = palette->getStyle(m_imp->m_styleId);
if(!style->isStrokeStyle() || style->isEnabled() == false)
return 0;
if(!m_imp->m_prop || style != m_imp->m_prop->getColorStyle())
{
delete m_imp->m_prop;
m_imp->m_prop = style->makeStrokeProp(this);
}
*/
  return m_imp->m_prop;
}
getSpeed()
TPointD TStroke::getSpeed (double w, bool outSpeed = false) const
Get speed at parameter w.
{
  assert(!m_imp->m_centerLineArray.empty());
  if (w < 0) return m_imp->m_centerLineArray.front()->getSpeed(0.0);
  if (w > 1.0) return m_imp->m_centerLineArray.back()->getSpeed(1.0);
  int chunk;
  double t;
  bool error = m_imp->retrieveChunkAndItsParamameter(w, chunk, t);
  if (t == 1 && outSpeed && chunk < getChunkCount() - 1) {
    chunk++;
    t = 0;
  }
  assert(!error);
  if (error) return m_imp->m_centerLineArray.front()->getSpeed(0.0);
  TPointD speed = getChunk(chunk)->getSpeed(t);
  if (speed == TPointD())  // la quadratica e' degenere!!!
  {
    while (speed == TPointD()) {
      speed = getChunk(chunk--)->getSpeed(1.0);
      if (chunk <= 0) break;
    }
    chunk = 0;
    while (speed == TPointD()) {
      speed = getChunk(chunk++)->getSpeed(0.0);
      if (chunk >= getChunkCount() - 1) break;
    }
    if (speed == TPointD()) {
      if (getChunkCount() == 1) {
        const TThickQuadratic *q = getChunk(0);
        if (q->getP0() == q->getP1() && q->getP1() != q->getP2())
          return TSegment(q->getP1(), q->getP2()).getSpeed(t);
        else if (q->getP1() == q->getP2() && q->getP0() != q->getP1())
          return TSegment(q->getP0(), q->getP1()).getSpeed(t);
        else
          assert(speed != TPointD());
      } else
        assert(speed != TPointD());
    }
  }
  return speed;
}
References getChunk(), getChunkCount(), TQuadratic::getP0(), TQuadratic::getP1(), TQuadratic::getP2(), TQuadratic::getSpeed(), and TSegment::getSpeed().
Referenced by ToonzExt::StrokeParametricDeformer::getDelta(), getSpeedAtLength(), and getSpeedTwoValues().
getSpeedAtLength()
TPointD TStroke::getSpeedAtLength (double s) const
Get speed at length s.
{
  double t = getParameterAtLength(s);
  return getSpeed(t);
}
References getParameterAtLength(), and getSpeed().
getSpeedTwoValues()
bool TStroke::getSpeedTwoValues (double w, TPointD & speed0, TPointD & speed1) const
Returns true if speed1!=speed0, so it is an edge in w.
{
  bool ret = false;
  assert(!m_imp->m_centerLineArray.empty());
  if (w < 0) {
    speed0 = m_imp->m_centerLineArray.front()->getSpeed(0.0);
    return ret;
  }
  if (w > 1.0) {
    speed0 = m_imp->m_centerLineArray.back()->getSpeed(1.0);
    return ret;
  }
  int chunk;
  double t;
  bool error = m_imp->retrieveChunkAndItsParamameter(w, chunk, t);
  assert(!error);
  if (error) {
    speed0 = m_imp->m_centerLineArray.front()->getSpeed(0.0);
    speed1 = -speed0;
    return ret;
  }
  speed0 = getChunk(chunk)->getSpeed(t);
  speed1 = -speed0;
  if (areAlmostEqual(t, 0.0, 1e-9) && chunk > 0 &&
      (speed1 = -getChunk(chunk - 1)->getSpeed(1.0)) != -speed0)
    ret = true;
  else if (areAlmostEqual(t, 1.0, 1e-9) && chunk < getChunkCount() - 1 &&
           (speed1 = -getChunk(chunk + 1)->getSpeed(0.0)) != -speed0) {
    TPointD aux = -speed0;
    speed0      = -speed1;
    speed1      = aux;
    ret         = true;
  }
  if (speed0 == TPointD())  // la quadratica e' degenere!!!
  {
    while (speed0 == TPointD()) {
      speed0 = getChunk(chunk--)->getSpeed(1.0);
      if (chunk <= 0) break;
    }
    chunk = 0;
    while (speed0 == TPointD()) {
      speed0 = getChunk(chunk++)->getSpeed(0.0);
      if (chunk >= getChunkCount() - 1) break;
    }
    if (speed0 == TPointD()) {
      if (getChunkCount() == 1) {
        const TThickQuadratic *q = getChunk(0);
        if (q->getP0() == q->getP1() && q->getP1() != q->getP2())
          speed0 = TSegment(q->getP1(), q->getP2()).getSpeed(t);
        else if (q->getP1() == q->getP2() && q->getP0() != q->getP1())
          speed0 = TSegment(q->getP0(), q->getP1()).getSpeed(t);
        else
          assert(speed0 != TPointD());
      } else
        assert(speed0 != TPointD());
    }
  }
  return ret;
}
References getChunk(), getChunkCount(), TQuadratic::getP0(), TQuadratic::getP1(), TQuadratic::getP2(), TQuadratic::getSpeed(), getSpeed(), and TSegment::getSpeed().
getStyle()
int TStroke::getStyle () const
Returns
Style
{ return m_imp->m_styleId; }
Referenced by ToonzExt::cloneStrokeStatus(), TVectorImage::eraseStyleIds(), TVectorImage::getUsedStyles(), StylePicker::pickStyleId(), TVectorImage::reassignStyles(), and split().
getThickPoint()
TThickPoint TStroke::getThickPoint (double w) const
Return a thickpoint at w (parameter (0<=w<=1))
Note
w is 0 at begin of the stroke and is 1.0 at the end. Parameter value for a chunk is stored in the vector m_parameterValueAtChunk. Every change (subdivision of a stroke, resample, insertion of a control point) computes a new value for parameter.
{
  assert(!m_imp->m_centerLineArray.empty());
  if (w < 0) return getControlPoint(0);
  if (w > 1.0) return getControlPoint(getControlPointCount() - 1);
  int chunk = 0;
  double t  = 0;
  bool error = m_imp->retrieveChunkAndItsParamameter(w, chunk, t);
  assert(!error);
  if (error) return getControlPoint(0);
  return getChunk(chunk)->getThickPoint(t);
}
References getChunk(), getControlPoint(), getControlPointCount(), and TThickQuadratic::getThickPoint().
Referenced by ControlPointEditorStroke::addControlPoint(), TVectorImage::fillStrokes(), TStrokePointDeformation::getDelta(), TStrokePointDeformation::getDisplacement(), TVectorImage::getNearestStroke(), Stage::Picker::onImage(), and StylePicker::pickStyleId().
getThickPointAtLength()
TThickPoint TStroke::getThickPointAtLength (double s) const
Return a thickpoint at s (length of arc)
{
  assert(!m_imp->m_centerLineArray.empty());
  if (s <= 0) return getControlPoint(0);
  if (s >= getLength()) return getControlPoint(getControlPointCount() - 1);
  int chunk;
  double tOfDivision;
  bool error =
      m_imp->retrieveChunkAndItsParamameterAtLength(s, chunk, tOfDivision);
  if (error)
    error =
        m_imp->retrieveChunkAndItsParamameterAtLength(s, chunk, tOfDivision);
  assert(!error);
  if (error) return getControlPoint(0);
  return getChunk(chunk)->getThickPoint(tOfDivision);
}
References getChunk(), getControlPoint(), getControlPointCount(), getLength(), and TThickQuadratic::getThickPoint().
getW() [1/2]
double TStroke::getW (const TPointD & p) const
Return parameter w at point position.
{
  int chunkIndex;
  double tOfchunk, distance2 = (numeric_limits<double>::max)();
  // cerca il chunk piu' vicino senza testare la BBox
  getNearestChunk(p, tOfchunk, chunkIndex, distance2, false);
  assert(0 <= chunkIndex && chunkIndex <= getChunkCount());
  DoublePair parRange = m_imp->retrieveParametersFromChunk(chunkIndex);
  double t = proportion(parRange.second, tOfchunk, 1.0, parRange.first);
  assert(0 <= t && t <= 1.0);
  return t;
}
References getChunkCount(), and getNearestChunk().
Referenced by ToonzExt::StrokeDeformationImpl::activate_impl(), ControlPointEditorStroke::addControlPoint(), TVectorImage::getNearestStroke(), ControlPointEditorStroke::getPointTypeAt(), ControlPointEditorStroke::moveSegment(), and TStroke::Imp::retrieveChunkAndItsParamameterAtLength().
getW() [2/2]
double TStroke::getW (int chunkIndex, double t) const
{
  DoublePair parRange = m_imp->retrieveParametersFromChunk(chunkIndex);
  double w = proportion(parRange.second, t, 1.0, parRange.first);
  assert(0 <= w && w <= 1.0);
  return w;
}
insertControlPoints()
void TStroke::insertControlPoints (double w)
Add a control point (in fact delete one and add three) without changing the stroke shape. w is the position of the new CP along parameter. (0<w<1)
Note
if a control point already exists near w, then the stroke remains unchanged
{
  if (0.0 > w || w > 1.0) return;
  int chunk;
  double tOfDivision = -1;
  if (m_imp->retrieveChunkAndItsParamameter(w, chunk, tOfDivision)) return;
  if (isAlmostZero(tOfDivision) || areAlmostEqual(tOfDivision, 1)) return;
  assert(0 <= chunk && chunk < getChunkCount());
  assert(0 <= tOfDivision && tOfDivision <= 1.0);
  // calcolo i due "cionchi"
  TThickQuadratic *tqfirst  = new TThickQuadratic,
                  *tqsecond = new TThickQuadratic;
  getChunk(chunk)->split(tOfDivision, *tqfirst, *tqsecond);
  m_imp->updateParameterValue(w, chunk, tqfirst, tqsecond);
  // recupero la posizione nella lista delle curve
  QuadStrokeChunkArray::iterator it = m_imp->m_centerLineArray.begin();
  // elimino la curva vecchia
  advance(it, chunk);
  delete *it;
  it = m_imp->m_centerLineArray.erase(it);
  // ed aggiungo le nuove
  it = m_imp->m_centerLineArray.insert(it, tqsecond);
  m_imp->m_centerLineArray.insert(it, tqfirst);
  invalidate();
  m_imp->computeCacheVector();
  m_imp->m_negativeThicknessPoints = 0;
  for (UINT j = 0; j < m_imp->m_centerLineArray.size(); j++) {
    if (m_imp->m_centerLineArray[j]->getThickP0().thick <= 0)
      m_imp->m_negativeThicknessPoints++;
    if (m_imp->m_centerLineArray[j]->getThickP1().thick <= 0)
      m_imp->m_negativeThicknessPoints++;
  }
  if (!m_imp->m_centerLineArray.empty() &&
      m_imp->m_centerLineArray.back()->getThickP2().thick <= 0)
    m_imp->m_negativeThicknessPoints++;
}
References getChunk(), getChunkCount(), and invalidate().
Referenced by ToonzExt::StrokeDeformationImpl::activate_impl(), and split().
insertControlPointsAtLength()
void TStroke::insertControlPointsAtLength (double s)
Add a control point (in fact delete one and add three) without changing the stroke shape. s is the position of the new CP along the stroke itself. (0<s<strokeLength)
Note
if a control point already exists near s, then the stroke remains unchanged
N.B. Questa funzione e' piu' lenta rispetto alla insertCP perche' ricerca la posizione di s con un algoritmo di bisezione.
{
  if (0 > s || s > getLength()) return;
  int chunk;
  double t;
  // cerca il cionco ed il parametro alla lunghezza s
  if (!m_imp->retrieveChunkAndItsParamameterAtLength(s, chunk, t)) {
    if (isAlmostZero(t) || areAlmostEqual(t, 1)) return;
    // calcolo i due "cionchi"
    TThickQuadratic *tqfirst  = new TThickQuadratic,
                    *tqsecond = new TThickQuadratic;
    getChunk(chunk)->split(t, *tqfirst, *tqsecond);
    double parameterInStroke;
    if (0 == chunk)
      parameterInStroke = m_imp->getW(2) * t;
    else
      parameterInStroke =
          t * m_imp->getW((chunk + 1) * 2) + (1 - t) * m_imp->getW(chunk * 2);
    m_imp->updateParameterValue(parameterInStroke, chunk, tqfirst, tqsecond);
    // recupero la posizione nella lista delle curve
    QuadStrokeChunkArray::iterator it = m_imp->m_centerLineArray.begin();
    // elimino la curva vecchia
    advance(it, chunk);
    delete *it;
    it = m_imp->m_centerLineArray.erase(it);
    // ed aggiungo le nuove
    it = m_imp->m_centerLineArray.insert(it, tqsecond);
    it = m_imp->m_centerLineArray.insert(it, tqfirst);
  }
  /* FAB
#ifdef  _DEBUG
{
const int
size = m_imp->m_parameterValueAtControlPoint.size();
double
prev = m_imp->m_parameterValueAtControlPoint[0];
for(int i = 1;
   i < size;
   ++i )
{
assert(prev <= m_imp->m_parameterValueAtControlPoint[i]);
prev = m_imp->m_parameterValueAtControlPoint[i];
}
}
#endif
//*/
  invalidate();
}
References getChunk(), getLength(), and invalidate().
Referenced by ToonzExt::rotateControlPoint().
interpolate()
TStroke * TStroke::interpolate (const std::vector< TThickPoint > & points, double error, bool findCorners = true) static
Get a stroke from a TThickPoint vector.
Restituisce uno stroke da un vettore di TThickPoint.
Create a T3DPointD vector froma a TThickPoint vector. The T3DPointD vector is used to find a TCubicStroke; than find the quadratic stroke.
Trasforma un vettore di TThickPoint in un vettore di T3DPointD che usa per trovare un TCubicStroke, cioe' uno stroke cubico. Da questo trova lo stroke quadratico.
{
  vector<T3DPointD> pointsArray3D;
  convert(points, pointsArray3D);
  TCubicStroke cubicStroke(pointsArray3D, error, findCorners);
  numSaved = 0;
  //  TStroke *stroke = computeQuadStroke(cubicStroke,error);
  TStroke *stroke = computeQuadStroke(cubicStroke);
#ifdef _DEBUG
  UINT cpIndex = 0;
  TThickPoint p;
  for (; cpIndex != (UINT)stroke->getControlPointCount(); cpIndex++) {
    p = stroke->getControlPoint(cpIndex);
    assert(std::isfinite(p.x));
    assert(std::isfinite(p.y));
    assert(std::isfinite(p.thick));
  }
#endif
  removeNullQuadratic(stroke);
  stroke->invalidate();
  return stroke;
}
References getControlPoint(), getControlPointCount(), and invalidate().
Referenced by StrokeGenerator::makeStroke().
invalidate()
void TStroke::invalidate ()
mark invalid the length and the outline. The next computeOutlines() will update them
{
  m_imp->m_maxThickness   = -1;
  m_imp->m_isOutlineValid = false;
  m_imp->m_isValidLength  = false;
  m_imp->m_flag           = m_imp->m_flag | c_dirty_flag;
  if (m_imp->m_prop) m_imp->m_prop->notifyStrokeChange();
}
Referenced by changeDirection(), ToonzExt::cloneStrokeStatus(), create(), insertControlPoints(), insertControlPointsAtLength(), interpolate(), VectorSelectionTool::onPropertyChanged(), reshape(), setControlPoint(), and transform().
isCenterLine()
bool TStroke::isCenterLine () const
Return true if all control points have negative thickness.
{
  assert(m_imp->m_negativeThicknessPoints <= getControlPointCount());
  return m_imp->m_negativeThicknessPoints == getControlPointCount();
}
References getControlPointCount().
isSelfLoop()
bool TStroke::isSelfLoop () const
Return true if the stroke is looped.
{ return m_imp->m_selfLoop; }
Referenced by ToonzExt::StraightCornerDeformation::check_(), ToonzExt::cloneStrokeStatus(), PumpTool::draw(), and ToonzExt::rotateControlPoint().
operator!=()
bool TStroke::operator!= (const TStroke & s) const inline
{ return !operator==(s); }
operator=()
TStroke & TStroke::operator= (const TStroke & other)
to be erased
{
  TStroke temp(other);
  swap(temp);
  return *this;
}
References swap().
operator==()
bool TStroke::operator== (const TStroke & s) const
{
  if (getChunkCount() != s.getChunkCount()) return false;
  int i;
  for (i = 0; i < getChunkCount(); i++) {
    const TThickQuadratic *chanck  = getChunk(i);
    const TThickQuadratic *sChanck = s.getChunk(i);
    if (chanck->getThickP0() != sChanck->getThickP0() ||
        chanck->getThickP1() != sChanck->getThickP1() ||
        chanck->getThickP2() != sChanck->getThickP2())
      return false;
  }
  return true;
}
outlineOptions() [1/2]
TStroke::OutlineOptions & TStroke::outlineOptions ()
{
  return m_imp->m_outlineOptions;
}
outlineOptions() [2/2]
const TStroke::OutlineOptions & TStroke::outlineOptions () const
{
  return m_imp->m_outlineOptions;
}
print()
void TStroke::print (std::ostream & os = std::cout) const
Only for debug.
{
  // m_imp->print(os);
  const TThickQuadratic *q;
  os << "Punti di controllo\n";
  for (int i = 0; i < getChunkCount(); ++i) {
    os << "quad #" << i << ":" << endl;
    q = getChunk(i);
    os << "    P0:" << q->getThickP0().x << ", " << q->getThickP0().y << ", "
       << q->getThickP0().thick << endl;
    os << "    P1:" << q->getThickP1().x << ", " << q->getThickP1().y << ", "
       << q->getThickP1().thick << endl;
    assert(i == getChunkCount() - 1 ||
           (getChunk(i)->getThickP2() == getChunk(i + 1)->getThickP0()));
  }
  q = getChunk(getChunkCount() - 1);
  os << "    P2:" << q->getThickP2().x << ", " << q->getThickP2().y << ", "
     << q->getThickP2().thick << endl;
}
References getChunk(), getChunkCount(), TThickQuadratic::getThickP0(), TThickQuadratic::getThickP1(), and TThickQuadratic::getThickP2().
reduceControlPoints() [1/2]
void TStroke::reduceControlPoints (double maxError)
Reduce the number of control point according to maxError parameter.
{
  vector<int> corners;
  corners.push_back(0);
  detectCorners(this, 10, corners);
  corners.push_back(getChunkCount());
  reduceControlPoints(error, corners);
}
References getChunkCount(), and reduceControlPoints().
Referenced by ToonzExt::StrokeDeformationImpl::activate_impl(), and reduceControlPoints().
reduceControlPoints() [2/2]
void TStroke::reduceControlPoints (double maxError, std::vector< int > corners)
Reduce the number of control point according to maxError parameter. The vector corners contain the corner of the stroke.
reshape()
void TStroke::reshape (const TThickPoint pos[], int count)
Reshape stroke.
Ridisegna lo stroke.
{
  // count deve essere dispari e maggiore o uguale a tre
  assert(count >= 3);
  assert(count & 1);
  QuadStrokeChunkArray &chunkArray = m_imp->m_centerLineArray;
  clearPointerContainer(chunkArray);
  m_imp->m_negativeThicknessPoints = 0;
  for (int i = 0; i < count - 1; i += 2) {
    chunkArray.push_back(new TThickQuadratic(pos[i], pos[i + 1], pos[i + 2]));
    if (pos[i].thick <= 0) m_imp->m_negativeThicknessPoints++;
    if (pos[i + 1].thick <= 0) m_imp->m_negativeThicknessPoints++;
  }
  if (pos[count - 1].thick <= 0) m_imp->m_negativeThicknessPoints++;
  invalidate();
  // m_imp->computeBBox();
  m_imp->computeParameterInControlPoint();
}
References invalidate().
Referenced by ControlPointEditorStroke::addControlPoint().
setAverageThickness()
void TStroke::setAverageThickness (double thickness)
Set the average value of stroke thickness to thickness.
{
  m_imp->m_averageThickness = thickness;
}
Referenced by ToonzExt::cloneStrokeStatus().
setControlPoint() [1/2]
void TStroke::setControlPoint (int n, const TPointD & pos) inline
Set the position of n-th control point. If "n" is not a valid position no points are changed If the CP is shared between two chunks, then both chunks are modified The first method doesn't change the point thickness
{
    setControlPoint(n, TThickPoint(pos, getControlPoint(n).thick));
  }
setControlPoint() [2/2]
void TStroke::setControlPoint (int n, const TThickPoint & pos)
Set the position of n-th control point. If "n" is not a valid position no points are changed If the CP is shared between two chunks, then both chunks are modified The first method doesn't change the point thickness
{
  assert(n >= 0);
  assert(n < getControlPointCount());
  if (n < 0 || n >= getControlPointCount()) return;
  invalidate();
  QuadStrokeChunkArray &chunkArray = m_imp->m_centerLineArray;
  if (getControlPoint(n).thick <= 0 && pos.thick > 0)
    m_imp->m_negativeThicknessPoints--;
  else if (getControlPoint(n).thick > 0 && pos.thick <= 0)
    m_imp->m_negativeThicknessPoints++;
  if (n == 0) {
    chunkArray[0]->setThickP0(pos);
    // m_imp->computeBBox();
    return;
  }
  int chunkNumber = tceil((n - 1) * 0.5);
  assert(chunkNumber <= getChunkCount());
  int pointOffset = n - chunkNumber * 2;
  if (chunkNumber == getChunkCount())  // e' l'ultimo punto della stroke
  {
    chunkArray[chunkNumber - 1]->setThickP2(pos);
    // m_imp->computeBBox();
    return;
  }
  if (0 == pointOffset) {
    chunkArray[chunkNumber]->setThickP0(pos);
    if (chunkNumber >= 1) {
      chunkNumber--;
      chunkArray[chunkNumber]->setThickP2(pos);
    }
  } else if (1 == pointOffset)
    chunkArray[chunkNumber]->setThickP1(pos);
  else if (2 == pointOffset) {
    chunkArray[chunkNumber]->setThickP2(pos);
    if (chunkNumber < getChunkCount() - 1) {
      chunkNumber++;
      chunkArray[chunkNumber]->setThickP0(pos);
    }
  }
  // m_imp->computeBBox();
}
References getChunkCount(), getControlPoint(), getControlPointCount(), and invalidate().
Referenced by ToonzExt::StrokeDeformationImpl::activate_impl(), setSelfLoop(), and VectorizerCore::vectorize().
setFlag()
void TStroke::setFlag (TStrokeFlag flag, bool status)
Set TStrokeFlag of the stroke.
{
  if (status)
    m_imp->m_flag |= flag;
  else
    m_imp->m_flag &= ~flag;
}
setId()
void TStroke::setId (int id)
{ m_imp->m_id = id; }
setProp()
void TStroke::setProp (TStrokeProp * prop)
Set TSrokePrope of a stroke.
{
  assert(prop);
  delete m_imp->m_prop;
  m_imp->m_prop = prop;
}
setSelfLoop()
void TStroke::setSelfLoop (bool loop = true)
Set a loop stroke.
{
  if (loop) {
    // assert that a self loop is a stroke where first and last control points
    // are the same
    const int cpCount = this->getControlPointCount();
    TThickPoint p, p0 = this->getControlPoint(0),
                   pn = this->getControlPoint(cpCount - 1);
    p = (p0 + pn) * 0.5;
    this->setControlPoint(0, p);
    this->setControlPoint(cpCount - 1, p);
  }
  m_imp->m_selfLoop = loop;
}
References getControlPoint(), getControlPointCount(), and setControlPoint().
Referenced by ToonzExt::cloneStrokeStatus(), and ToonzExt::rotateControlPoint().
setStyle()
void TStroke::setStyle (int styleId)
Set a style
Note
If the same style exists, it is replaced by new
TStroke becomes the owner of TStrokeStyle
{
  m_imp->m_styleId = styleId;
  /*
if (!colorStyle || (colorStyle && colorStyle->isStrokeStyle()))
{
m_imp->m_colorStyle = colorStyle;
delete m_imp->m_prop;
m_imp->m_prop = 0;
}
*/
}
Referenced by ToonzExt::cloneStrokeStatus(), RasterTapeTool::closeFreehand(), SelectionTool::closeFreehand(), TImageReaderSvg::load(), PumpTool::onDeactivate(), TVectorImage::reassignStyles(), and split().
split()
void TStroke::split (double w, TStroke & f, TStroke & s) const
Split a stroke at parameter t
Note
Chunk of null length are removed.
{
  int chunk;
  double t;
  f.m_imp->m_maxThickness = -1;
  s.m_imp->m_maxThickness = -1;
  if (!m_imp->retrieveChunkAndItsParamameter(w, chunk, t)) {
    assert(0 <= chunk && chunk < getChunkCount());
    assert(0 <= w && w <= 1.0);
    assert(0 <= t && t <= 1.0);
    QuadStrokeChunkArray &chunkArray = m_imp->m_centerLineArray;
    // build two temporary quadratic
    TThickQuadratic *tq1 = new TThickQuadratic, *tq2 = new TThickQuadratic;
    // make split
    chunkArray[chunk]->split(t, *tq1, *tq2);
    // a temporary vector of ThickQuadratic
    QuadStrokeChunkArray vTQ;
    // copy all chunk of stroke in a vTQ
    int i;
    for (i = 0; i < chunk; ++i) vTQ.push_back(chunkArray[i]);
    // not insert null length chunk (unless vTQ is empty....)
    if (tq1->getLength() != 0.0 || w == 0.0 || vTQ.empty()) vTQ.push_back(tq1);
    // build a temp and swap
    TStroke *ts1  = TStroke::create(vTQ);
    if (!ts1) ts1 = new TStroke;
    ts1->swapGeometry(f);
    // clear vector (chunks are now under TStroke control)
    vTQ.clear();
    // idem...
    if (tq2->getLength() != 0.0 || w == 1.0 || getChunkCount() == 0)
      vTQ.push_back(tq2);
    for (i = chunk + 1; i < getChunkCount(); ++i) vTQ.push_back(chunkArray[i]);
    TStroke *ts2  = TStroke::create(vTQ);
    if (!ts2) ts2 = new TStroke;
    ts2->swapGeometry(s);
    // Copy style infos
    f.setStyle(getStyle());
    s.setStyle(getStyle());
    f.outlineOptions() = s.outlineOptions() = outlineOptions();
    delete ts2;
    delete ts1;
    // delete temporary quadratic
    delete tq1;
    delete tq2;
    if (f.getControlPointCount() == 3 &&
        f.getControlPoint(0) !=
            f.getControlPoint(2))  // gli stroke con solo 1 chunk vengono fatti
                                   // dal tape tool...e devono venir
                                   // riconosciuti come speciali di autoclose
                                   // proprio dal fatto che hanno 1 solo chunk.
      f.insertControlPoints(0.5);
    if (s.getControlPointCount() == 3 &&
        s.getControlPoint(0) !=
            s.getControlPoint(2))  // gli stroke con solo 1 chunk vengono fatti
                                   // dal tape tool...e devono venir
                                   // riconosciuti come speciali di autoclose
                                   // proprio dal fatto che hanno 1 solo chunk.
      s.insertControlPoints(0.5);
  }
}
References create(), getChunkCount(), getControlPoint(), getControlPointCount(), TQuadratic::getLength(), getStyle(), insertControlPoints(), setStyle(), swapGeometry(), and TStroke().
swap()
void TStroke::swap (TStroke & ref)
Swap the contents of two strokes.
{
  std::swap(m_imp, ref.m_imp);
  // Stroke props need to update their stroke owners
  if (m_imp->m_prop) m_imp->m_prop->setStroke(this);
  if (ref.m_imp->m_prop) ref.m_imp->m_prop->setStroke(&ref);
  // The id is retained. This is coherent as the stroke id is supposedly
  // not an exchangeable info.
  std::swap(m_imp->m_id, ref.m_imp->m_id);
}
Referenced by operator=().
swapGeometry()
void TStroke::swapGeometry (TStroke & ref)
Swapd the geometrical data of two strokes.
{ m_imp->swapGeometry(*ref.m_imp); }
Referenced by split().
transform()
void TStroke::transform (const TAffine & aff, bool doChangeThickness = false)
Transform a stroke using an affine.
{
  for (UINT i = 0; i < m_imp->m_centerLineArray.size(); ++i) {
    TThickQuadratic &ref = *m_imp->m_centerLineArray[i];
    ref                  = transformQuad(aff, ref, doChangeThickness);
    if (doChangeThickness) {
      double det                                     = aff.det();
      if (det == 0) m_imp->m_negativeThicknessPoints = getControlPointCount();
      if (m_imp->m_maxThickness != -1) m_imp->m_maxThickness *= sqrt(fabs(det));
      // else if(det<0)
      //  m_imp->m_negativeThicknessPoints=getControlPointCount()-m_imp->m_negativeThicknessPoints;
    }
  }
  invalidate();
}
References getControlPointCount(), and invalidate().
Referenced by RasterTapeTool::checkSegments(), and AreaFiller::strokeFill().
Member Data Documentation
c_changed_region_flag
const BYTE TStroke::c_changed_region_flag = 0x2 static
c_dirty_flag
const BYTE TStroke::c_dirty_flag = 0x4 static
c_selected_flag
const BYTE TStroke::c_selected_flag = 0x1 static
m_capStyle
UCHAR TStroke::m_capStyle
m_joinStyle
UCHAR TStroke::m_joinStyle
m_miterLower
double TStroke::m_miterLower
m_miterUpper
double TStroke::m_miterUpper
The documentation for this struct was generated from the following files:
E:/opentoonz/toonz/sources/include/tstroke.h
E:/opentoonz/toonz/sources/common/tvectorimage/tstroke.cpp