opentoonz: ColorModelViewer Class Reference
ColorModelViewer Class Reference final
The ColorModelViewer class is a flip book used to manage color model.
Signals
void refImageNotFound ()
Signals inherited from FlipBook
void closeFlipBook (FlipBook *)
void unfreezed (FlipBook *)
void imageLoaded (QString &)
Public Member Functions
ColorModelViewer (QWidget *parent=0)
Public Member Functions inherited from FlipBook
FlipBook (QWidget *parent=0, QString viewerTitle=QString(), std::vector< int > flipConsoleButtonMask={FlipConsole::eFilledRaster, FlipConsole::eDefineSubCamera, FlipConsole::eLocator, FlipConsole::eZoomIn, FlipConsole::eZoomOut, FlipConsole::eFlipHorizontal, FlipConsole::eFlipVertical, FlipConsole::eResetView}, UCHAR flags=0, bool isColorModel=false)
void setLevel (const TFilePath &path, TPalette *palette=0, int from=-1, int to=-1, int step=1, int shrink=1, TSoundTrack *snd=0, bool append=false, bool isToonzOutput=false)
void setLevel (TFx *previewedFx, TXsheet *xsh, TLevel *level, TPalette *palette=0, int from=-1, int to=-1, int step=1, int currentFrame=1, TSoundTrack *snd=0)
void setLevel (TXshSimpleLevel *xl)
void onPlayCompleted () override
bool doSaveImages (TFilePath fp)
int getCurrentFrame ()
QString getLevelZoomTitle () const
void setTitle (const QString &title)
QString getTitle () const
void showFrame (int frame)
TFx * getPreviewedFx () const
TXsheet * getPreviewXsheet () const
bool isFreezed () const
TRectD getPreviewedImageGeometry () const
void schedulePreviewedFxUpdate ()
bool canAppend ()
bool isSavable () const
void setPoolIndex (int poolIndex)
int getPoolIndex () const
void setIsRemakingPreviewFx (bool on)
void addFreezeButtonToTitleBar ()
void setProgressBarStatus (const std::vector< UCHAR > *pbStatus)
const std::vector< UCHAR > * getProgressBarStatus () const
void adaptGeometry (const TRect &interestingImgRect, const TRect &imgRect)
void adaptGeometryForFullPreview (const TRect &imgRect)
void adaptGeometryToCurrentSize ()
void zoomAndAdaptGeometry (bool forward)
void reset ()
void onDrawFrame (int frame, const ImagePainter::VisualSettings &vs, QElapsedTimer *timer, qint64 targetInstant) override
void minimize (bool doMinimize)
ImageViewer * getImageViewer ()
TRect getLoadbox () const
void setLoadbox (const TRect &box)
TDimension getImageSize () const
void swapBuffers () override
void changeSwapBehavior (bool enable) override
virtual void onPlayCompleted ()=0
virtual void onDrawFrame (int frame, const ImagePainter::VisualSettings &settings, QElapsedTimer *timer=nullptr, qint64 targetInstant=0)=0
virtual void swapBuffers ()
virtual void changeSwapBehavior (bool enable)
Protected Slots
void showCurrentImage ()
void loadCurrentFrame ()
void removeColorModel ()
void onRefImageNotFound ()
void updateViewer ()
void changePickType ()
void repickFromColorModel ()
Protected Slots inherited from FlipBook
void onDoubleClick (QMouseEvent *me)
void onButtonPressed (FlipConsole::EGadget button)
void onCloseButtonPressed ()
void saveImage ()
void freeze (bool on)
Protected Member Functions
void dragEnterEvent (QDragEnterEvent *event) override
void dropEvent (QDropEvent *event) override
void loadImage (const TFilePath &fp)
void resetImageViewer ()
void contextMenuEvent (QContextMenuEvent *event) override
void mousePressEvent (QMouseEvent *) override
void mouseMoveEvent (QMouseEvent *) override
void pick (const QPoint &p)
void hideEvent (QHideEvent *e) override
void showEvent (QShowEvent *e) override
void reloadCurrentFrame ()
Protected Member Functions inherited from FlipBook
void clearCache ()
void adaptWidGeometry (const TRect &interestWidRect, const TRect &imgWidRect, bool keepPosition)
Adapts panel geometry to that of passed rect.
void dragEnterEvent (QDragEnterEvent *e) override
void dropEvent (QDropEvent *e) override
void playAudioFrame (int frame)
TImageP getCurrentImage (int frame)
void showEvent (QShowEvent *e) override
void hideEvent (QHideEvent *e) override
void focusInEvent (QFocusEvent *e) override
void resizeEvent (QResizeEvent *e) override
void enterEvent (QEvent *e) override
Additional Inherited Members
Public Types inherited from FlipBook
enum Flags { eDontKeepFilesOpened = 0x1 }
Public Slots inherited from FlipBook
void saveImages ()
void loadImages ()
void performFxUpdate ()
void regenerate ()
void regenerateFrame ()
void clonePreview ()
void freezePreview ()
void unfreezePreview ()
Protected Attributes inherited from FlipBook
int m_poolIndex
QString m_viewerTitle
QString m_title
QString m_title1
ImageViewer * m_imageViewer
FlipConsole * m_flipConsole
int m_shrink
int m_framesCount
TRect m_loadbox
TDimension m_dim
std::map< std::string, TRect > m_loadboxes
std::vector< Level > m_levels
std::vector< QString > m_levelNames
TPalette * m_palette
bool m_playSound
std::vector< std::string > m_addedInCache
TSoundOutputDevice * m_player
TSoundTrack * m_snd
TLevelWriterP m_lw
TLevelReaderP m_lr
TXshSimpleLevel * m_xl
int m_currentFrameToSave
SaveImagesPopup * m_savePopup
LoadImagesPopup * m_loadPopup
bool m_isPreviewFx
TFxP m_previewedFx
TXsheetP m_previewXsh
QTimer m_previewUpdateTimer
bool m_freezed
UCHAR m_flags
TPanelTitleBarButton * m_freezeButton
Detailed Description
The ColorModelViewer class is a flip book used to manage color model.
         Inherits \b FlipBook.
         This object show the reference image linked to current level
palette.
Constructor & Destructor Documentation
ColorModelViewer()
ColorModelViewer::ColorModelViewer (QWidget * parent = 0)
    : FlipBook(parent, QString(tr("Color Model")),
               std::vector<int>(
                   {FlipConsole::eRed,          FlipConsole::eGreen,
                    FlipConsole::eBlue,         FlipConsole::eMatte,
                    FlipConsole::eGRed,         FlipConsole::eGGreen,
                    FlipConsole::eGBlue,        FlipConsole::eRate,
                    FlipConsole::eSound,        FlipConsole::eSaveImg,
                    FlipConsole::eHisto,        FlipConsole::eCompare,
                    FlipConsole::eCustomize,    FlipConsole::eSave,
                    FlipConsole::eFilledRaster, FlipConsole::eDefineLoadBox,
                    FlipConsole::eUseLoadBox,   FlipConsole::eDefineSubCamera,
                    FlipConsole::eLocator,      FlipConsole::eZoomIn,
                    FlipConsole::eZoomOut,      FlipConsole::eFlipHorizontal,
                    FlipConsole::eFlipVertical, FlipConsole::eResetView}),
               eDontKeepFilesOpened, true)
    , m_mode(0)
    , m_currentRefImgPath(TFilePath()) {
  setObjectName("colormodel");
  setToolCursor(m_imageViewer, ToolCursor::PickerCursor);
  // Do not call the special procedure for flipbook closures...
  disconnect(parentWidget(), SIGNAL(closeButtonPressed()), this,
             SLOT(onCloseButtonPressed()));
  bool ret = connect(this, SIGNAL(refImageNotFound()), this,
                     SLOT(onRefImageNotFound()), Qt::QueuedConnection);
  assert(ret);
  m_imageViewer->setMouseTracking(true);
}
~ColorModelViewer()
ColorModelViewer::~ColorModelViewer ()
{}
Member Function Documentation
changePickType
void ColorModelViewer::changePickType () protected slot
{
  TTool *tool = TApp::instance()->getCurrentTool()->getTool();
  if (tool->getName() == T_StylePicker) {
    StylePickerTool *stylePickerTool = dynamic_cast<StylePickerTool *>(tool);
    if (stylePickerTool->isOrganizePaletteActive()) {
      setToolCursor(m_imageViewer, ToolCursor::PickerCursorOrganize);
      return;
    }
  }
  TPropertyGroup *propGroup = tool->getProperties(0);
  /*- Property -*/
  if (!propGroup) {
    m_mode = 2;
    setToolCursor(m_imageViewer, ToolCursor::PickerCursor);
    return;
  }
  /*- Mode: 0 -*/
  TProperty *modeProp = propGroup->getProperty("Mode:");
  if (!modeProp) {
    m_mode = 2;
    setToolCursor(m_imageViewer, ToolCursor::PickerCursor);
    return;
  }
  else {
    std::string var = modeProp->getValueAsString();
    if (var == LINES) {
      m_mode = 1;
      setToolCursor(m_imageViewer, ToolCursor::PickerCursorLine);
    } else if (var == AREAS) {
      m_mode = 0;
      setToolCursor(m_imageViewer, ToolCursor::PickerCursorArea);
    } else  // Line & Areas
    {
      m_mode = 2;
      setToolCursor(m_imageViewer, ToolCursor::PickerCursor);
    }
  }
}
contextMenuEvent()
void ColorModelViewer::contextMenuEvent (QContextMenuEvent * event) override protected
Create and open the Right-click menu color model viewer.
{
  /*-- LevelMenu --*/
  TApp *app     = TApp::instance();
  TXshLevel *xl = app->getCurrentLevel()->getLevel();
  if (!xl) return;
  TXshSimpleLevel *sl = xl->getSimpleLevel();
  if (!sl) return;
  TPalette *currentPalette =
      app->getPaletteController()->getCurrentLevelPalette()->getPalette();
  if (!currentPalette) return;
  QMenu menu(this);
  menu.addAction(CommandManager::instance()->getAction(MI_LoadColorModel));
  QAction *loadCurrentFrame =
      new QAction(QString(tr("Use Current Frame")), this);
  connect(loadCurrentFrame, SIGNAL(triggered()), SLOT(loadCurrentFrame()));
  menu.addAction(loadCurrentFrame);
  if (!m_imageViewer->getImage()) {
    menu.exec(event->globalPos());
    return;
  }
  QAction *removeColorModel =
      new QAction(QString(tr("Remove Color Model")), this);
  connect(removeColorModel, SIGNAL(triggered()), SLOT(removeColorModel()));
  menu.addAction(removeColorModel);
  /* If there is at least one style with "picked pos" parameter, then enable
   * repick command */
  TRasterImageP ri = m_imageViewer->getImage();
  if (ri && currentPalette->hasPickedPosStyle()) {
    menu.addSeparator();
    QAction *repickFromColorModelAct = new QAction(
        QString(tr("Update Colors by Using Picked Positions")), this);
    connect(repickFromColorModelAct, SIGNAL(triggered()),
            SLOT(repickFromColorModel()));
    menu.addAction(repickFromColorModelAct);
  }
  menu.addSeparator();
  QString shortcut = QString::fromStdString(
      CommandManager::instance()->getShortcutFromId(V_ViewReset));
  QAction *reset = menu.addAction(tr("Reset View") + "\t " + shortcut);
  connect(reset, SIGNAL(triggered()), m_imageViewer, SLOT(resetView()));
  shortcut = QString::fromStdString(
      CommandManager::instance()->getShortcutFromId(V_ZoomFit));
  QAction *fit = menu.addAction(tr("Fit to Window") + "\t" + shortcut);
  connect(fit, SIGNAL(triggered()), m_imageViewer, SLOT(fitView()));
  menu.exec(event->globalPos());
}
References TApp::getCurrentLevel(), TXshLevel::getSimpleLevel(), and TApp::instance().
dragEnterEvent()
void ColorModelViewer::dragEnterEvent (QDragEnterEvent * event) override protected
Accept event if current palette is not empty, event data has urls and each urls type are different from "src" and "tpl" .
{
  TPalette *palette = getPaletteHandle()->getPalette();
  if (!palette) return;
  const QMimeData *mimeData = event->mimeData();
  if (!acceptResourceDrop(mimeData->urls())) return;
  for (const QUrl &url : mimeData->urls()) {
    TFilePath fp(url.toLocalFile().toStdWString());
    std::string type = fp.getType();
    if (type == "scr" || type == "tpl") return;
  }
  // Force CopyAction
  event->setDropAction(Qt::CopyAction);
  // For files, don't accept original proposed action in case it's a move
  event->accept();
}
References TFilePath::getType().
dropEvent()
void ColorModelViewer::dropEvent (QDropEvent * event) override protected
If event data has urls, convert each urls in path and set view and current palette reference image (recall loadImage() and setLevel()).
{
  const QMimeData *mimeData = event->mimeData();
  if (mimeData->hasUrls()) {
    for (const QUrl &url : mimeData->urls()) {
      TFilePath fp(url.toLocalFile().toStdWString());
      loadImage(fp);
      setLevel(fp);
    }
    // Force CopyAction
    event->setDropAction(Qt::CopyAction);
    // For files, don't accept original proposed action in case it's a move
    event->accept();
  }
}
References loadImage(), and FlipBook::setLevel().
hideEvent()
void ColorModelViewer::hideEvent (QHideEvent * e) override protected
{
  TPaletteHandle *paletteHandle = getPaletteHandle();
  TXshLevelHandle *levelHandle  = TApp::instance()->getCurrentLevel();
  ToolHandle *toolHandle        = TApp::instance()->getCurrentTool();
  disconnect(paletteHandle, SIGNAL(paletteSwitched()), this,
             SLOT(showCurrentImage()));
  disconnect(paletteHandle, SIGNAL(paletteChanged()), this,
             SLOT(showCurrentImage()));
  disconnect(paletteHandle, SIGNAL(colorStyleChanged(bool)), this,
             SLOT(showCurrentImage()));
  disconnect(toolHandle, SIGNAL(toolSwitched()), this, SLOT(changePickType()));
  disconnect(toolHandle, SIGNAL(toolChanged()), this, SLOT(changePickType()));
  disconnect(levelHandle, SIGNAL(xshLevelViewChanged()), this,
             SLOT(updateViewer()));
}
loadCurrentFrame
void ColorModelViewer::loadCurrentFrame () protected slot
Clone current image and set it in viewer.
{
  TApp *app     = TApp::instance();
  TXshLevel *xl = app->getCurrentLevel()->getLevel();
  if (!xl) return;
  TXshSimpleLevel *sl = xl->getSimpleLevel();
  if (!sl) return;
  /*- FId -*/
  TFrameId fid;
  if (app->getCurrentFrame()->isEditingLevel())
    fid = app->getCurrentFrame()->getFid();
  else if (app->getCurrentFrame()->isEditingScene()) {
    int columnIndex = app->getCurrentColumn()->getColumnIndex();
    TXsheet *xsh    = app->getCurrentXsheet()->getXsheet();
    if (!xsh) return;
    TXshColumn *column = xsh->getColumn(columnIndex);
    if (!column) return;
    int frame = app->getCurrentFrame()->getFrame();
    fid       = column->getCellColumn()->getCell(frame).getFrameId();
  }
  TImageP img = sl->getFrame(fid, true);
  TPalette *currentPalette =
      app->getPaletteController()->getCurrentLevelPalette()->getPalette();
  if (!img || !currentPalette) return;
  TImageP refImg = img->cloneImage();
  currentPalette->setRefImg(TImageP());
  /*--onPaletteSwitchedRefImagePathUpdate--*/
  currentPalette->setRefImgPath(xl->getPath());
  std::vector<TFrameId> fids;
  fids.push_back(fid);
  currentPalette->setRefLevelFids(fids, false);
  m_currentRefImgPath = xl->getPath();
  m_levels.clear();
  m_levelNames.clear();
  m_framesCount = 1;
  m_palette     = 0;
  m_lr          = TLevelReaderP();
  m_dim         = TDimension(0, 0);
  m_loadbox     = TRect();
  m_loadboxes.clear();
  m_flipConsole->enableProgressBar(false);
  m_flipConsole->setProgressBarStatus(0);
  m_flipConsole->setFrameRange(1, 1, 1);
  m_title1 = m_viewerTitle +
             " :: " + m_currentRefImgPath.withoutParentDir().withFrame(fid);
  m_title = "  ::  <Use Current Frame>";
  m_imageViewer->setImage(refImg);
}
References TImage::cloneImage(), TXsheet::getColumn(), TApp::getCurrentColumn(), TApp::getCurrentFrame(), TApp::getCurrentLevel(), TApp::getCurrentXsheet(), TXshLevel::getPath(), TXshLevel::getSimpleLevel(), TApp::instance(), ImageViewer::setImage(), TPalette::setRefImg(), TPalette::setRefImgPath(), TPalette::setRefLevelFids(), TFilePath::withFrame(), and TFilePath::withoutParentDir().
loadImage()
void ColorModelViewer::loadImage (const TFilePath & fp) protected
Set current palette reference image to fp recall: PaletteCmd::loadReferenceImage().
{
  if (fp.isEmpty()) return;
  TPaletteHandle *paletteHandle = getPaletteHandle();
  TPalette *palette             = paletteHandle->getPalette();
  if (!palette || palette->isCleanupPalette()) {
    DVGui::error(QObject::tr("Cannot load Color Model in current palette."));
    return;
  }
  PaletteCmd::ColorModelLoadingConfiguration config;
  // if the palette is locked, replace the color model's palette with the
  // destination
  if (palette->isLocked()) {
    // do nothing as config will use behavior = ReplaceColorModelPlt by default
    // config.behavior = PaletteCmd::ReplaceColorModelPlt;
  } else {
    std::set<TFilePath> fpSet;
    fpSet.insert(fp);
    ColorModelBehaviorPopup popup(fpSet, 0);
    int ret = popup.exec();
    if (ret == QDialog::Rejected) return;
    popup.getLoadingConfiguration(config);
  }
  ToonzScene *scene = TApp::instance()->getCurrentScene()->getScene();
  int isLoaded =
      PaletteCmd::loadReferenceImage(paletteHandle, config, fp, scene);
  if (0 != isLoaded) {
    std::cout << "loadReferenceImage Failed for some reason." << std::endl;
    return;
  }
  // no changes in the icon with replace (Keep the destination palette) option
  if (config.behavior != PaletteCmd::ReplaceColorModelPlt) {
    TXshLevel *level = TApp::instance()->getCurrentLevel()->getLevel();
    if (!level) return;
    std::vector<TFrameId> fids;
    level->getFids(fids);
    invalidateIcons(level, fids);
  }
}
References TApp::getCurrentLevel(), TApp::getCurrentScene(), and TApp::instance().
Referenced by dropEvent().
mouseMoveEvent()
void ColorModelViewer::mouseMoveEvent (QMouseEvent * event) override protected
If left button is moved recall pick() in event pos.
{
  if (event->buttons() & Qt::LeftButton) pick(event->pos() * getDevPixRatio());
}
References pick().
mousePressEvent()
void ColorModelViewer::mousePressEvent (QMouseEvent * event) override protected
If left button is pressed recall pick() in event pos.
{
  if (event->button() == Qt::LeftButton) pick(event->pos() * getDevPixRatio());
}
References pick().
onRefImageNotFound
void ColorModelViewer::onRefImageNotFound () protected slot
{
  DVGui::info(
      tr("It is not possible to retrieve the color model set for the current "
         "level."));
}
pick()
void ColorModelViewer::pick (const QPoint & p) protected
Pick color from image and set it as current style.
{
  TImageP img = m_imageViewer->getImage();
  if (!img) return;
  TPaletteHandle *ph =
      TApp::instance()->getPaletteController()->getCurrentLevelPalette();
  TPalette *currentPalette = ph->getPalette();
  if (!currentPalette) return;
  /*- Pick -*/
  if (!m_imageViewer->rect().contains(p)) return;
  StylePicker picker(img, currentPalette);
  QPoint viewP = m_imageViewer->mapFrom(this, p);
  TPointD pos  = m_imageViewer->getViewAff().inv() *
                TPointD(viewP.x() - m_imageViewer->width() / 2,
                        -viewP.y() + m_imageViewer->height() / 2);
  double scale2 = m_imageViewer->getViewAff().det();
  /*---
          ToolPick
          0=Area, 1=Line, 2=Line&Areas(default)
  ---*/
  int styleIndex =
      picker.pickStyleId(pos + TPointD(-0.5, -0.5), 1, scale2, m_mode);
  if (styleIndex < 0) return;
  /*-- pickLineStyle0 /
   * PurePaint Style --*/
  if (m_mode == 1) {
    if (styleIndex == 0) return;
    TToonzImageP ti = img;
    if (ti && picker.pickTone(pos) == 255) return;
  }
  /*- Palettereturn -*/
  TPalette::Page *page = currentPalette->getStylePage(styleIndex);
  if (!page) return;
  /*-- Style --*/
  TSelection *selection =
      TApp::instance()->getCurrentSelection()->getSelection();
  if (selection) {
    TStyleSelection *styleSelection =
        dynamic_cast<TStyleSelection *>(selection);
    if (styleSelection) styleSelection->selectNone();
  }
  /*
    if the Style Picker tool is current and "organize palette" is activated,
    then move the picked style to the first page of the palette.
  */
  TTool *tool = TApp::instance()->getCurrentTool()->getTool();
  if (tool->getName() == "T_StylePicker") {
    StylePickerTool *spTool = dynamic_cast<StylePickerTool *>(tool);
    if (spTool && spTool->isOrganizePaletteActive()) {
      TPoint point = picker.getRasterPoint(pos);
      int frame    = m_flipConsole->getCurrentFrame() - 1;
      PaletteCmd::organizePaletteStyle(
          ph, styleIndex, TColorStyle::PickedPosition(point, frame));
    }
  }
  ph->setStyleIndex(styleIndex);
}
References TApp::getCurrentSelection(), TApp::getCurrentTool(), ImageViewer::getImage(), StylePicker::getRasterPoint(), TPalette::getStylePage(), ImageViewer::getViewAff(), TApp::instance(), TAffine::inv(), and StylePicker::pickStyleId().
Referenced by mouseMoveEvent(), and mousePressEvent().
reloadCurrentFrame()
void ColorModelViewer::reloadCurrentFrame () protected
{
  TApp *app     = TApp::instance();
  TXshLevel *xl = app->getCurrentLevel()->getLevel();
  if (!xl) return;
  TXshSimpleLevel *sl = xl->getSimpleLevel();
  if (!sl) return;
  TPalette *currentPalette =
      app->getPaletteController()->getCurrentLevelPalette()->getPalette();
  if (!currentPalette) return;
  std::vector<TFrameId> fids = currentPalette->getRefLevelFids();
  /*- CurrentFrame1Frame -*/
  if (fids.size() != 1) return;
  TImageP img = sl->getFrame(fids[0], true);
  if (!img) return;
  TImageP refImg = img->cloneImage();
  currentPalette->setRefImg(TImageP());
  currentPalette->setRefImgPath(xl->getPath());
  /*- currentRefImgPath -*/
  m_currentRefImgPath = xl->getPath();
  m_levels.clear();
  m_levelNames.clear();
  m_framesCount = 1;
  m_palette     = 0;
  m_lr          = TLevelReaderP();
  m_dim         = TDimension(0, 0);
  m_loadbox     = TRect();
  m_loadboxes.clear();
  m_flipConsole->enableProgressBar(false);
  m_flipConsole->setProgressBarStatus(0);
  m_flipConsole->setFrameRange(1, 1, 1);
  m_title1 = m_viewerTitle +
             " :: " + m_currentRefImgPath.withoutParentDir().withFrame(fids[0]);
  m_title = "  ::  <Use Current Frame>";
  m_imageViewer->setImage(refImg);
}
removeColorModel
void ColorModelViewer::removeColorModel () protected slot
Remove reference image from current palette using PaletteCmd::removeReferenceImage() and reset image viewer.
{
  PaletteCmd::removeReferenceImage(getPaletteHandle());
  resetImageViewer();
  m_currentRefImgPath = TFilePath();
}
References resetImageViewer().
repickFromColorModel
void ColorModelViewer::repickFromColorModel () protected slot
{
  TImageP img = m_imageViewer->getImage();
  if (!img) return;
  TPaletteHandle *ph =
      TApp::instance()->getPaletteController()->getCurrentLevelPalette();
  PaletteCmd::pickColorByUsingPickedPosition(
      ph, img, m_flipConsole->getCurrentFrame() - 1);
}
resetImageViewer()
void ColorModelViewer::resetImageViewer () inline protected
Set current level to TLevelP() and image to "0".
{
    clearCache();
    m_levels.clear();
    m_title = "";
    m_imageViewer->setImage(getCurrentImage(0));
    m_currentRefImgPath = TFilePath();
    m_palette           = 0;
  }
References ImageViewer::setImage().
Referenced by removeColorModel().
showCurrentImage
void ColorModelViewer::showCurrentImage () protected slot
{
  TPalette *palette = getPaletteHandle()->getPalette();
  if (!palette) {
    resetImageViewer();
    return;
  }
  TApp *app     = TApp::instance();
  TXshLevel *xl = app->getCurrentLevel()->getLevel();
  if (!xl) {
    resetImageViewer();
    return;
  }
  /*-- UseCurrentFramepalette --*/
  if (palette->getRefImgPath() == xl->getPath()) {
    TXshSimpleLevel *sl = xl->getSimpleLevel();
    if (!sl) {
      resetImageViewer();
      return;
    }
    /*- TFrameId -*/
    if (m_currentRefImgPath == xl->getPath()) {
      TImageP refImg = m_imageViewer->getImage();
      if (!refImg) {
        resetImageViewer();
        return;
      }
      TImageP refImg_clone = refImg->cloneImage();
      refImg_clone->setPalette(palette);
      m_imageViewer->setImage(refImg_clone);
      return;
    }
    /*- UseCurrentFrameLevelLevel -*/
    else {
      reloadCurrentFrame();
      return;
    }
  }
  /*- ColorModel -*/
  resetImageViewer();
  ToonzScene *scene = TApp::instance()->getCurrentScene()->getScene();
  TFilePath fp      = scene->decodeFilePath(palette->getRefImgPath());
  if (TSystem::doesExistFileOrLevel(fp)) {
    setLevel(fp, palette);
  } else if (!fp.isEmpty())
    emit refImageNotFound();
}
showEvent()
void ColorModelViewer::showEvent (QShowEvent * e) override protected
{
  TPaletteHandle *paletteHandle = getPaletteHandle();
  TXshLevelHandle *levelHandle  = TApp::instance()->getCurrentLevel();
  ToolHandle *toolHandle        = TApp::instance()->getCurrentTool();
  bool ret = connect(paletteHandle, SIGNAL(paletteSwitched()), this,
                     SLOT(showCurrentImage()));
  ret      = ret && connect(paletteHandle, SIGNAL(paletteChanged()), this,
                       SLOT(showCurrentImage()));
  ret = ret && connect(paletteHandle, SIGNAL(colorStyleChanged(bool)), this,
                       SLOT(showCurrentImage()));
  /*- TypePick -*/
  ret = ret && connect(toolHandle, SIGNAL(toolSwitched()), this,
                       SLOT(changePickType()));
  ret = ret && connect(toolHandle, SIGNAL(toolChanged()), this,
                       SLOT(changePickType()));
  ret = ret && connect(levelHandle, SIGNAL(xshLevelViewChanged()), this,
                       SLOT(updateViewer()));
  assert(ret);
  changePickType();
  showCurrentImage();
}
updateViewer
void ColorModelViewer::updateViewer () protected slot
If current palette level exists reset image viewer and set current viewer to reference image path level.
{ getImageViewer()->repaint(); }
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/toonz/colormodelviewer.h
E:/opentoonz/toonz/sources/toonz/colormodelviewer.cpp