opentoonz: tipc::Stream Class Reference
tipc::Stream Class Reference final
#include <tipc.h>
Public Member Functions
Stream (QLocalSocket *socket)
QLocalSocket * socket ()
int readSize ()
bool messageReady ()
bool readData (char *data, qint64 dataSize, int msecs=-1)
bool readMessage (Message &msg, int msecs=-1)
bool readDataNB (char *data, qint64 dataSize, int msecs=-1, QEventLoop::ProcessEventsFlag flag=QEventLoop::AllEvents)
bool readMessageNB (Message &msg, int msecs=-1, QEventLoop::ProcessEventsFlag flag=QEventLoop::AllEvents)
bool flush (int msecs=-1)
Detailed Description
A tipc::Stream is a specialized QDataStream designed to work with a tipc-based QLocalSocket instance.
Constructor & Destructor Documentation
Stream()
tipc::Stream::Stream (QLocalSocket * socket) inline
: QDataStream(socket), m_socket(socket) {}
Member Function Documentation
flush()
bool tipc::Stream::flush (int msecs = -1)
Flushes all data written to the stream. This function waits until all data written on the stream has been successfully delivered in output. Returns true if the operation was successful, false if it timed out or an error occurred.
{
  tipc_debug(qDebug("tipc:flush entry"));
  while (m_socket->bytesToWrite() > 0) {
    tipc_debug(qDebug() << "bytes to write:" << m_socket->bytesToWrite());
    bool ok = m_socket->flush();
    tipc_debug(qDebug() << "flush success:" << ok
                        << "bytes to write:" << m_socket->bytesToWrite());
    if (m_socket->bytesToWrite() > 0 && !m_socket->waitForBytesWritten(msecs))
      return false;
  }
  tipc_debug(qDebug() << "tipc:flush exit - bytes to write:"
                      << m_socket->bytesToWrite());
  return (m_socket->bytesToWrite() == 0);
}
Referenced by tipc::readMessage(), and tipc::readShMemBuffer().
messageReady()
bool tipc::Stream::messageReady ()
{
  TINT32 msgSize;
  return (msgSize = readSize()) >= 0 && m_socket->bytesAvailable() >= msgSize;
}
readData()
bool tipc::Stream::readData (char * data, qint64 dataSize, int msecs = -1)
{
  tipc_debug(qDebug("tipc::Stream::readData entry"));
  qint64 r, dataRead = 0;
  char *currData = data;
  while (dataRead < dataSize) {
    if ((m_socket->bytesAvailable() == 0) &&
        !m_socket->waitForReadyRead(msecs)) {
      tipc_debug(
          qDebug("tipc::Stream::readData exit (unexpected loss of data)"));
      return false;
    }
    // Read the supplied data
    currData += r = m_socket->read(currData, dataSize - dataRead);
    dataRead += r;
  }
  tipc_debug(qDebug("tipc::Stream::readData exit"));
  return true;
}
readDataNB()
bool tipc::Stream::readDataNB (char * data, qint64 dataSize, int msecs = -1, QEventLoop::ProcessEventsFlag flag = QEventLoop::AllEvents)
{
  tipc_debug(qDebug("tipc::Stream::readDataNB entry"));
  qint64 r, dataRead = 0;
  char *currData = data;
  QEventLoop loop;
  QObject::connect(m_socket, SIGNAL(readyRead()), &loop, SLOT(quit()));
  QObject::connect(m_socket, SIGNAL(error(QLocalSocket::LocalSocketError)),
                   &loop, SLOT(quit()));
  if (msecs >= 0) QTimer::singleShot(msecs, &loop, SLOT(quit()));
  while (dataRead < dataSize) {
    if (m_socket->bytesAvailable() == 0) {
      loop.exec(flag);
      if (m_socket->bytesAvailable() == 0) {
        tipc_debug(
            qDebug("tipc::Stream::readDataNB exit (unexpected loss of data)"));
        return false;
      }
    }
    // Read the supplied data
    currData += r = m_socket->read(currData, dataSize - dataRead);
    dataRead += r;
  }
  tipc_debug(qDebug("tipc::Stream::readDataNB exit"));
  return true;
}
readMessage()
bool tipc::Stream::readMessage (Message & msg, int msecs = -1)
Reads the message and returns its header. This function reads a complete message from the socket, waiting until it is completely available. The function accepts an inactivity timeout which can be supplied to drop the operation after msecs milliseconds no data has been received.
{
  TINT32 msgSize = 0;
  if (!readData((char *)&msgSize, sizeof(TINT32), msecs)) return false;
  msg.ba().resize(msgSize);
  if (!readData(msg.ba().data(), msgSize, msecs)) return false;
  return true;
}
Referenced by tipc::readMessage().
readMessageNB()
bool tipc::Stream::readMessageNB (Message & msg, int msecs = -1, QEventLoop::ProcessEventsFlag flag = QEventLoop::AllEvents)
The non-blocking equivalent to readMessage(), this function performs event processing in a local event loop until all message data has been received.
{
  TINT32 msgSize = 0;
  if (!readDataNB((char *)&msgSize, sizeof(TINT32), msecs, flag)) return false;
  msg.ba().resize(msgSize);
  if (!readDataNB(msg.ba().data(), msgSize, msecs, flag)) return false;
  return true;
}
Referenced by tipc::readMessageNB().
readSize()
int tipc::Stream::readSize ()
{
  if (m_socket->bytesAvailable() < sizeof(TINT32)) return -1;
  TINT32 msgSize = -1;
  m_socket->peek((char *)&msgSize, sizeof(TINT32));
  return msgSize;
}
socket()
QLocalSocket * tipc::Stream::socket () inline
{ return m_socket; }
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/tipc.h
E:/opentoonz/toonz/sources/common/tipc/tipc.cpp