opentoonz: TXshLevel Class Reference
TXshLevel Class Reference abstract
The TXshLevel class is the base class of level managers in xsheet.
#include <txshlevel.h>
Public Member Functions
TXshLevel (ClassCode classCode, std::wstring name)
virtual ~TXshLevel ()
void setName (std::wstring name)
int getType () const
void setType (int type)
change the level type;
ToonzScene * getScene () const
Return the ToonzScene the level belongs to;.
virtual void setScene (ToonzScene *scene)
virtual TXshSimpleLevel * getSimpleLevel ()
Method (to be overridden in subclasses) to downcast to TXshSimpleLevel.
virtual TXshChildLevel * getChildLevel ()
Method (to be overridden in subclasses) to downcast to TXshChildLevel.
virtual TXshZeraryFxLevel * getZeraryFxLevel ()
virtual TXshPaletteLevel * getPaletteLevel ()
Method (to be overridden in subclasses) to downcast to TXshPaletteLevel.
virtual TXshSoundLevel * getSoundLevel ()
Method (to be overridden in subclasses) to downcast to TXshSoundLevel.
virtual TXshSoundTextLevel * getSoundTextLevel ()
std::wstring getName () const
Return level name.
std::wstring getShortName () const
Return level short name.
virtual TFilePath getPath () const
Return the file path associated with the level.
virtual bool isEmpty () const
virtual int getFrameCount () const
virtual void getFids (std::vector< TFrameId > &fids) const
void loadData (TIStream &is) override=0
Load the level data (i.e. name, path, etc. e.g. from the .tnz file)
void saveData (TOStream &os) override=0
Save the level data (i.e. name, path, etc. e.g. to the .tnz file)
virtual void load ()=0
Load the level content from the associated path.
virtual void save ()=0
Save the level content to the associated path.
HookSet * getHookSet () const
virtual void setDirtyFlag (bool on)
Mark the level as "modified".
Public Member Functions inherited from TSmartObject
TSmartObject (ClassCode classCode)
void addRef ()
void release ()
TINT32 getRefCount () const
Public Member Functions inherited from TPersist
virtual void loadData (TIStream &is)=0
virtual void saveData (TOStream &os)=0
std::string getStreamTag () const
virtual const TPersistDeclaration * getDeclaration () const =0
Protected Member Functions
void updateShortName ()
create shortname from the level name
Protected Attributes
std::wstring m_name
std::wstring m_shortName
int m_type
HookSet * m_hookSet
ToonzScene * m_scene
Additional Inherited Members
Public Types inherited from TSmartObject
typedef short ClassCode
Public Types inherited from TPersist
typedef TPersist * CreateProc()
Static Public Member Functions inherited from TSmartObject
static TINT32 getInstanceCount (ClassCode code)
Static Public Member Functions inherited from TPersist
static void declare (CreateProc *)
static TPersist * create (const std::string &name)
Detailed Description
The TXshLevel class is the base class of level managers in xsheet.
Inherits TSmartObject and TPersist.
This is an abstract base class inherited by the concrete classes TXshChildLevel, TXshSimpleLevel and TXshZeraryFxLevel.
The class contains all features about a generic level and gives all methods to access to these information.
It's possible ot know level name, getName(), or identify level types getType(), defined in txshleveltypes.h, and change it, setType(). The class provides function to know scene to which level belongs, getScene(), and function to change scene setScene().
Constructor & Destructor Documentation
TXshLevel()
TXshLevel::TXshLevel (ClassCode classCode, std::wstring name)
Constructs a TXshLevel with TXshLevel name name
    : TSmartObject(code)
    , m_name(name)
    , m_type(UNKNOWN_XSHLEVEL)
    , m_hookSet(new HookSet())
    , m_scene(0) {
  updateShortName();
}
References updateShortName().
~TXshLevel()
TXshLevel::~TXshLevel () virtual
Destroys the TXshLevel object.
{ delete m_hookSet; }
Member Function Documentation
getChildLevel()
virtual TXshChildLevel * TXshLevel::getChildLevel () inline virtual
Method (to be overridden in subclasses) to downcast to TXshChildLevel.
Reimplemented in TXshChildLevel.
{ return 0; }
Referenced by StageBuilder::addCell(), TXsheet::checkCircularReferences(), ChildStack::createChild(), TXshCell::getChildLevel(), ToonzScene::getSoundColumns(), TXsheet::getUsedLevels(), FxBuilder::makePF(), and ChildStack::openChild().
getFids()
virtual void TXshLevel::getFids (std::vector< TFrameId > & fids) const inline virtual
Reimplemented in TXshChildLevel, and TXshSimpleLevel.
{}
getFrameCount()
virtual int TXshLevel::getFrameCount () const inline virtual
Reimplemented in TXshChildLevel, TXshPaletteLevel, and TXshSimpleLevel.
{ return 0; }
getHookSet()
HookSet * TXshLevel::getHookSet () const inline
Return HookSet.
{ return m_hookSet; }
Referenced by TXshSimpleLevel::load(), TXshSimpleLevel::renumber(), and TXshSimpleLevel::save().
getName()
std::wstring TXshLevel::getName () const inline
Return level name.
See also
getShortName()
{ return m_name; }
Referenced by VectorizerPopup::apply(), XsheetViewer::changeWindowTitle(), ExportLevelPopup::execute(), TXshSimpleLevel::loadData(), ToonzScene::loadTnzFile(), TXshChildLevel::saveData(), TXshPaletteLevel::saveData(), Vectorizer::setLevel(), TXshSimpleLevel::setPalette(), and Filmstrip::updateChooseLevelComboItems().
getPaletteLevel()
virtual TXshPaletteLevel * TXshLevel::getPaletteLevel () inline virtual
Method (to be overridden in subclasses) to downcast to TXshPaletteLevel.
Reimplemented in TXshPaletteLevel.
{ return 0; }
Referenced by TXshCell::getPaletteLevel(), and StylePickerTool::onImageChanged().
getPath()
virtual TFilePath TXshLevel::getPath () const inline virtual
Return the file path associated with the level.
Reimplemented in TXshPaletteLevel, TXshSimpleLevel, and TXshSoundLevel.
{ return TFilePath(); }
Referenced by StudioPaletteTreeViewer::dropEvent(), ColorModelViewer::loadCurrentFrame(), and Previewer::onImageChange().
getScene()
ToonzScene * TXshLevel::getScene () const inline
Return the ToonzScene the level belongs to;.
See also
setScene()
{ return m_scene; }
Referenced by TXshPaletteLevel::load(), TXshSimpleLevel::load(), Stage::RasterPainter::onRasterImage(), LevelUpdater::open(), TXshPaletteLevel::save(), TXshSimpleLevel::save(), and TXshSimpleLevel::setEditableRange().
getShortName()
std::wstring TXshLevel::getShortName () const inline
Return level short name.
See also
getName()
{ return m_shortName; }
getSimpleLevel()
virtual TXshSimpleLevel * TXshLevel::getSimpleLevel () inline virtual
Method (to be overridden in subclasses) to downcast to TXshSimpleLevel.
Reimplemented in TXshSimpleLevel.
{ return 0; }
Referenced by StageBuilder::addCell(), ColorModelViewer::contextMenuEvent(), ToonzScene::createNewLevel(), TLevelColumnFx::doDryCompute(), StudioPaletteTreeViewer::dropEvent(), ReplaceParentDirectoryPopup::execute(), FingerTool::finishBrush(), PaintBrushTool::finishBrush(), ToonzRasterBrushTool::finishRasterBrush(), TXshCell::getSimpleLevel(), ColorModelViewer::loadCurrentFrame(), IoCmd::loadResources(), ToonzScene::loadTnzFile(), FxBuilder::makePF(), TTool::notifyImageChanged(), StylePickerTool::onImageChanged(), EraserTool::onImageChanged(), SceneViewer::onLevelSwitched(), FillTool::onPropertyChanged(), Vectorizer::setLevel(), and TTool::touchImage().
getSoundLevel()
virtual TXshSoundLevel * TXshLevel::getSoundLevel () inline virtual
Method (to be overridden in subclasses) to downcast to TXshSoundLevel.
Reimplemented in TXshSoundLevel.
{ return 0; }
Referenced by TXshSoundColumn::assignLevels(), and TXshCell::getSoundLevel().
getSoundTextLevel()
virtual TXshSoundTextLevel * TXshLevel::getSoundTextLevel () inline virtual
Method (to be overridden in subclasses) to downcast to TXshSoundTextLevel
Reimplemented in TXshSoundTextLevel.
{ return 0; }
Referenced by TXshCell::getSoundTextLevel().
getType()
int TXshLevel::getType () const inline
return the level type (types are defined in txshleveltypes.h);
See also
setType()
{ return m_type; }
Referenced by TXshLevelColumn::canSetCell(), PlasticDeformerFx::doDryCompute(), TLevelColumnFx::doDryCompute(), PaletteCmd::eraseStyles(), SaveLevelAsPopup::execute(), IoCmd::exportLevel(), TXshSimpleLevel::getBBox(), TXsheet::getBBox(), TApp::getCurrentImageType(), SceneViewer::getDpiFactor(), SceneViewer::getZoomScaleFittingWithScreen(), Stage::Player::image(), ImageLoader::isImageCompatible(), TXshSimpleLevel::load(), ToonzScene::loadLevel(), IoCmd::loadResources(), FxBuilder::makePF(), TXshSimpleLevel::makeTlv(), StylePickerTool::onImageChanged(), TXshSimpleLevel::onPaletteChanged(), TXshSimpleLevel::renumber(), TXshSimpleLevel::save(), TXsheet::setCells(), TXshSimpleLevel::setEditableRange(), Vectorizer::setLevel(), TXshSimpleLevel::setPalette(), TXshSimpleLevel::touchFrame(), and Toolbar::updateToolbar().
getZeraryFxLevel()
virtual TXshZeraryFxLevel * TXshLevel::getZeraryFxLevel () inline virtual
Method (to be overridden in subclasses) to downcast to TXshZeraryFxLevel
Reimplemented in TXshZeraryFxLevel.
{ return 0; }
Referenced by TXshZeraryFxColumn::canSetCell(), TXshCell::getZeraryFxLevel(), and TXshZeraryFxColumn::setCell().
isEmpty()
virtual bool TXshLevel::isEmpty () const inline virtual
Reimplemented in TXshSimpleLevel.
{ return true; }
load()
virtual void TXshLevel::load () pure virtual
Load the level content from the associated path.
Implemented in TXshChildLevel, TXshPaletteLevel, TXshSimpleLevel, TXshSoundLevel, TXshSoundTextLevel, and TXshZeraryFxLevel.
Referenced by ToonzScene::loadResources().
loadData()
void TXshLevel::loadData (TIStream & is) override pure virtual
Load the level data (i.e. name, path, etc. e.g. from the .tnz file)
Implements TPersist.
Implemented in TXshChildLevel, TXshPaletteLevel, TXshSimpleLevel, TXshSoundLevel, TXshSoundTextLevel, and TXshZeraryFxLevel.
save()
virtual void TXshLevel::save () pure virtual
Save the level content to the associated path.
Implemented in TXshChildLevel, TXshPaletteLevel, TXshSimpleLevel, TXshSoundLevel, TXshSoundTextLevel, and TXshZeraryFxLevel.
saveData()
void TXshLevel::saveData (TOStream & os) override pure virtual
Save the level data (i.e. name, path, etc. e.g. to the .tnz file)
Implements TPersist.
Implemented in TXshChildLevel, TXshPaletteLevel, TXshSimpleLevel, TXshSoundLevel, TXshSoundTextLevel, and TXshZeraryFxLevel.
setDirtyFlag()
virtual void TXshLevel::setDirtyFlag (bool on) inline virtual
Mark the level as "modified".
Reimplemented in TXshSimpleLevel.
{}
setName()
void TXshLevel::setName (std::wstring name)
{
  m_name = name;
  updateShortName();
}
setScene()
void TXshLevel::setScene (ToonzScene * scene) virtual
Set scene to which level belongs to scene.
See also
getScene()
Reimplemented in TXshChildLevel, and TXshSoundLevel.
{ m_scene = scene; }
Referenced by ToonzScene::createNewLevel(), ToonzScene::loadLevel(), ToonzScene::loadTnzFile(), TXshSimpleLevel::save(), TXshChildLevel::setScene(), and TXshSoundLevel::setScene().
setType()
void TXshLevel::setType (int type) inline
change the level type;
See also
getType()
{ m_type = type; }
Referenced by ToonzScene::createNewLevel(), TXshSimpleLevel::loadData(), TXshSoundLevel::loadData(), TXshSoundTextLevel::loadData(), ToonzScene::loadLevel(), ToonzScene::loadTnzFile(), TXshSimpleLevel::makeTlv(), and TXshSimpleLevel::save().
updateShortName()
void TXshLevel::updateShortName () protected
create shortname from the level name
{
  if (m_name.size() < 5)
    m_shortName = m_name;
  else
    m_shortName = m_name.substr(0, 4) + L"~";
}
Referenced by TXshLevel().
Member Data Documentation
m_hookSet
HookSet* TXshLevel::m_hookSet protected
m_name
std::wstring TXshLevel::m_name protected
m_scene
ToonzScene* TXshLevel::m_scene protected
m_shortName
std::wstring TXshLevel::m_shortName protected
m_type
int TXshLevel::m_type protected
Identify level types defined in txshleveltypes.h
Referenced by TXshSimpleLevel::createEmptyFrame(), and TXshSimpleLevel::saveData().
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/toonz/txshlevel.h
E:/opentoonz/toonz/sources/toonzlib/txshlevel.cpp