opentoonz: DockWidget Class Reference
DockWidget Class Reference
Dockable widgets are widget containers handled by DockLayout class.
#include <docklayout.h>
Public Types
enum { leftMargin = 0x1 , rightMargin = 0x2 , topMargin = 0x4 , bottomMargin = 0x8 }
Public Member Functions
void maximizeDock ()
bool getCanFixWidth ()
void setCanFixWidth (bool fixed)
DockWidget (QWidget *parent=0, Qt::WindowFlags flags=Qt::Tool)
DockLayout * parentLayout () const
bool isFloating () const
bool wasFloating () const
void clearWasFloating ()
bool isMaximized () const
QWidget * hoveredWidget (QMouseEvent *me)
DockPlaceholder * placeAdjacentTo (DockWidget *dockWidget, int boundary)
DockPlaceholder * placeOfSeparator (DockSeparator *)
Returns placeholder associated with input separator.
const std::vector< DockPlaceholder * > & placeholders () const
virtual QSize getDockedMinimumSize ()
virtual QSize getDockedMaximumSize ()
virtual void setFloatingAppearance ()
virtual void setDockedAppearance ()
virtual bool isDragGrip (QPoint p)
Shows dock widget in docked mode.
virtual int isResizeGrip (QPoint)
virtual void selectDockPlaceholder (QMouseEvent *me)
void clearDockPlaceholders ()
void setDecoAllocator (DockDecoAllocator *decoAllocator)
NOTE: DockWidget takes ownership of the allocator.
virtual void onDock (bool docked)
Protected Member Functions
void wheelEvent (QWheelEvent *we) override
Switch in selected dock placeholder's hierarchy.
void mouseDoubleClickEvent (QMouseEvent *me) override
virtual void windowTitleEvent (QEvent *)
Protected Attributes
bool m_floating
bool m_wasFloating
bool m_dragging
bool m_undocking
bool m_resizing
int m_marginType
bool m_maximized
bool m_canFixWidth = false
std::vector< DockPlaceholder * > m_placeholders
DockPlaceholder * m_selectedPlace
Friends
class DockLayout
class DockPlaceholder
Detailed Description
Dockable widgets are widget containers handled by DockLayout class.
DockLayouts accept only dock widgets of this class; so if you want to place a given widget under this kind of layout, a DockWidget shell for it must be allocated first. The following class implements base dock widgets, with native floating decorations and no docked title bar. It is encouraged to reimplement all the essential functions for custom aspect and behaviour.
See also
DockLayout and DockPlaceholder classes.
Member Enumeration Documentation
anonymous enum
anonymous enum
       {
    leftMargin   = 0x1,
    rightMargin  = 0x2,
    topMargin    = 0x4,
    bottomMargin = 0x8
  };
Constructor & Destructor Documentation
DockWidget()
DockWidget::DockWidget (QWidget * parent = 0, Qt::WindowFlags flags = Qt::Tool)
Constructs a dock Widget; every newly constructed dock widget is floating (i.e. not docked into the layout).
    : QFrame(parent, flags)
    , m_dragging(false)
    , m_resizing(false)
    , m_floating(true)
    , m_undocking(false)
    , m_parentLayout(0)
    , m_selectedPlace(0)
    , m_maximized(0) {
  // Don't let this widget inherit the parent's background color
  // setAutoFillBackground(true);
  // setBackgroundRole(QPalette::Background);
  // setAttribute(Qt::WA_DeleteOnClose);   //Since Toonz just hides panels...
  setAttribute(Qt::WA_Hover);
  // Set default minimum and maximum sizes.
  setMinimumSize(QSize(50, 50));
  setMaximumSize(QSize(10000, 10000));
  m_decoAllocator = new DockDecoAllocator;
  // Make sure the desktop is initialized and known
  desktop = qApp->desktop();
}
~DockWidget()
DockWidget::~DockWidget () virtual
{
  // Since close button lies on the title bar, make sure mouse is released if
  // that is pressed.
  if (QWidget::mouseGrabber() == this) releaseMouse();
  clearDockPlaceholders();
  // Delete deco allocator
  delete m_decoAllocator;
}
Member Function Documentation
clearDockPlaceholders()
void DockWidget::clearDockPlaceholders ()
Clears dock placeholders for this dockwidget. This is automatically called at drag ends.
{
  unsigned int i;
  for (i = 0; i < m_placeholders.size(); ++i) delete m_placeholders[i];
  m_placeholders.clear();
}
clearWasFloating()
void DockWidget::clearWasFloating () inline
{ m_wasFloating = false; }
getCanFixWidth()
bool DockWidget::getCanFixWidth () inline
{ return m_canFixWidth; }
getDockedMaximumSize()
virtual QSize DockWidget::getDockedMaximumSize () inline virtual
Returns the maximum size of the dock widget when docked. This function should be reimlemented whenever minimum size changes between floating and docked appearance.
{ return maximumSize(); }
getDockedMinimumSize()
virtual QSize DockWidget::getDockedMinimumSize () inline virtual
Returns the minimum size of the dock widget when docked. This function should be reimlemented whenever minimum size changes between floating and docked appearance.
{ return minimumSize(); }
hoveredWidget()
QWidget * DockWidget::hoveredWidget (QMouseEvent * me)
Returns widget (separator or docked widget) containing input \point, or 0 if none. Convenience function combining parentLayout() and containerOf(point). NOTE: Observe that, in any case, the use of QEnterEvents is discouraged for this purpose: remember that we forcedly remain within its boundaries when dragging a dock widget; instead, we are rather interested about entering the dock widgets below.
{
  if (!m_parentLayout) return 0;
  QPoint point = parentWidget()->mapFromGlobal(me->globalPos());
  return m_parentLayout->containerOf(point);
}
isDragGrip()
bool DockWidget::isDragGrip (QPoint p) virtual
Shows dock widget in docked mode.
Returns true or false whether input QPoint is inside the dragging grip for this DockWidget, or not. Typically (and by default), true is returned whenever p lies inside the widget's title bar when floating; however, you are free to place the drag grip anywhere reimplementing this method in custom dockwidgets.
{
  if (isFloating()) {
    QRect frame        = frameGeometry();
    QRect conts        = geometry();
    int margin         = conts.left() - frame.left();
    int titleBarHeight = conts.top() - frame.top();
    QRect titleArea(QPoint(0, margin - titleBarHeight),
                    QPoint(width() - 1, -1));
    return titleArea.contains(p);
  }
  return 0;
}
Referenced by mouseDoubleClickEvent().
isFloating()
bool DockWidget::isFloating () const inline
{ return m_floating; }
isMaximized()
bool DockWidget::isMaximized () const inline
{ return m_maximized; }
isResizeGrip()
virtual int DockWidget::isResizeGrip (QPoint) inline virtual
{
    return 0;  // Native deco widgets handle margins and resizes on their own
  }
maximizeDock()
void DockWidget::maximizeDock ()
{
  if (!m_floating) {
    parentLayout()->setMaximized(this, !m_maximized);
  }
}
mouseDoubleClickEvent()
void DockWidget::mouseDoubleClickEvent (QMouseEvent * me) override protected
DockWidgets respond to title bar double clicks maximizing the widget in layout's contents rect.
{
  if (!m_floating && isDragGrip(me->pos())) {
    parentLayout()->setMaximized(this, !m_maximized);
  }
}
References isDragGrip().
onDock()
virtual void DockWidget::onDock (bool docked) inline virtual
{}
parentLayout()
DockLayout * DockWidget::parentLayout () const inline
{ return m_parentLayout; }
placeAdjacentTo()
DockPlaceholder * DockWidget::placeAdjacentTo (DockWidget * dockWidget, int boundary)
Returns adjacent placeholders to hovered widget. If hovered is a separator, just return associated placeholder.
{
  Region *r = parentLayout()->find(dockWidget);
  if (((boundary == DockPlaceholder::left ||
        boundary == DockPlaceholder::right) &&
       r->getOrientation() == Region::horizontal) ||
      ((boundary == DockPlaceholder::top ||
        boundary == DockPlaceholder::bottom) &&
       r->getOrientation() == Region::vertical)) {
    // Placeholder is coherent with region orientation
    return r->placeholders().size() ? r->placeholder(boundary % 2) : 0;
  } else {
    // Search in parent region
    Region *parent = r->getParent();
    if (parent) {
      unsigned int i = parent->find(r);
      return parent->placeholders().size()
                 ? parent->placeholder(i + (boundary % 2))
                 : 0;
    } else {
      // No parent region - dockWidget is the only widget of the whole layout;
      // Then check the first 2 elements of placeholders vector.
      if (!m_placeholders[boundary % 2]->getParentRegion()) {
        return m_placeholders.size() ? m_placeholders[boundary % 2] : 0;
      }
    }
  }
  return 0;
}
placeholders()
const std::vector< DockPlaceholder * > & DockWidget::placeholders () const inline
{
    return m_placeholders;
  }
placeOfSeparator()
DockPlaceholder * DockWidget::placeOfSeparator (DockSeparator * sep)
Returns placeholder associated with input separator.
{
  Region *r = sep->getParentRegion();
  int idx   = sep->getIndex();
  return r->placeholders().size() ? r->placeholder(idx + 1) : 0;
}
selectDockPlaceholder()
void DockWidget::selectDockPlaceholder (QMouseEvent * me) virtual
Processes an input mouse event to select the active placeholder among the possible ones for this dock widget. The selected placeholder is also evidenced with respect to the other (or these are kept hidden) according to the body of this function.
{
  // const int inf= 1000000;
  DockPlaceholder *selected = 0;
  // Search placeholders cotaining muose position
  unsigned int i;
  for (i = 0; i < m_placeholders.size(); ++i) {
    if (m_placeholders[i]->geometry().contains(me->globalPos())) {
      selected = m_placeholders[i];
    }
  }
  // In order to avoid flickering
  if (m_selectedPlace != selected) {
    if (m_selectedPlace) m_selectedPlace->hide();
    if (selected) selected->show();
  }
  m_selectedPlace = selected;
}
setCanFixWidth()
void DockWidget::setCanFixWidth (bool fixed) inline
{ m_canFixWidth = fixed; }
setDecoAllocator()
void DockWidget::setDecoAllocator (DockDecoAllocator * decoAllocator)
NOTE: DockWidget takes ownership of the allocator.
Sets current deco allocator to decoAllocator. A default deco allocator is already provided at construction.
{
  // Delete old one
  if (m_decoAllocator) delete m_decoAllocator;
  // Place a copy of new one
  m_decoAllocator = decoAllocator;
}
Referenced by TDockWidget::TDockWidget().
setDockedAppearance()
virtual void DockWidget::setDockedAppearance () inline virtual
This function is called in order to show the dock widget in its docked status. No show() or update() is needed in its body. It can be reimplemented to build custom-styled dock widgets.
{}
Referenced by DockLayout::restoreState().
setFloatingAppearance()
virtual void DockWidget::setFloatingAppearance () inline virtual
This function is called in order to show the dock widget in its floating status. No show() or update() is needed in its body. It can be reimplemented to build custom-styled dock widgets.
{ setWindowFlags(Qt::Tool); }
Referenced by DockLayout::restoreState(), and DockLayout::undockItem().
wasFloating()
bool DockWidget::wasFloating () const inline
{ return m_wasFloating; }
wheelEvent()
void DockWidget::wheelEvent (QWheelEvent * we) override protected
Switch in selected dock placeholder's hierarchy.
{
  if (m_dragging) {
    if (m_selectedPlace) {
      DockPlaceholder *newSelected =
          (we->delta() > 0)
              ? m_selectedPlace->parentPlaceholder()
              : m_selectedPlace->childPlaceholder(
                    parentWidget()->mapFromGlobal(we->globalPos()));
      if (newSelected != m_selectedPlace) {
        m_selectedPlace->hide();
        newSelected->show();
        m_selectedPlace = newSelected;
      }
    }
  }
}
References DockPlaceholder::childPlaceholder(), and DockPlaceholder::parentPlaceholder().
windowTitleEvent()
virtual void DockWidget::windowTitleEvent (QEvent *) inline protected virtual
{}
Friends And Related Function Documentation
DockLayout
friend class DockLayout friend
DockPlaceholder
friend class DockPlaceholder friend
Member Data Documentation
m_canFixWidth
bool DockWidget::m_canFixWidth = false protected
m_dragging
bool DockWidget::m_dragging protected
m_floating
bool DockWidget::m_floating protected
m_marginType
int DockWidget::m_marginType protected
m_maximized
bool DockWidget::m_maximized protected
m_placeholders
std::vector<DockPlaceholder *> DockWidget::m_placeholders protected
m_resizing
bool DockWidget::m_resizing protected
m_selectedPlace
DockPlaceholder* DockWidget::m_selectedPlace protected
m_undocking
bool DockWidget::m_undocking protected
m_wasFloating
bool DockWidget::m_wasFloating protected
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/toonzqt/docklayout.h
E:/opentoonz/toonz/sources/toonzqt/docklayout.cpp
E:/opentoonz/toonz/sources/toonzqt/dockwidget.cpp