opentoonz: TXshChildLevel Class Reference
TXshChildLevel Class Reference final
#include <txshchildlevel.h>
Public Member Functions
TXshChildLevel (std::wstring name=L"")
~TXshChildLevel ()
TXshChildLevel * getChildLevel () override
TXsheet * getXsheet ()
void setXsheet (TXsheet *xsheet)
void loadData (TIStream &is) override
Load the level data (i.e. name, path, etc. e.g. from the .tnz file)
void saveData (TOStream &os) override
Save the level data (i.e. name, path, etc. e.g. to the .tnz file)
void load () override
Load the level content from the associated path.
void save () override
Save the level content to the associated path.
void setScene (ToonzScene *scene) override
int getFrameCount () const override
void getFids (std::vector< TFrameId > &fids) const override
Public Member Functions inherited from TXshLevel
TXshLevel (ClassCode classCode, std::wstring name)
virtual ~TXshLevel ()
void setName (std::wstring name)
int getType () const
void setType (int type)
change the level type;
ToonzScene * getScene () const
Return the ToonzScene the level belongs to;.
virtual void setScene (ToonzScene *scene)
virtual TXshSimpleLevel * getSimpleLevel ()
Method (to be overridden in subclasses) to downcast to TXshSimpleLevel.
virtual TXshChildLevel * getChildLevel ()
Method (to be overridden in subclasses) to downcast to TXshChildLevel.
virtual TXshZeraryFxLevel * getZeraryFxLevel ()
virtual TXshPaletteLevel * getPaletteLevel ()
Method (to be overridden in subclasses) to downcast to TXshPaletteLevel.
virtual TXshSoundLevel * getSoundLevel ()
Method (to be overridden in subclasses) to downcast to TXshSoundLevel.
virtual TXshSoundTextLevel * getSoundTextLevel ()
std::wstring getName () const
Return level name.
std::wstring getShortName () const
Return level short name.
virtual TFilePath getPath () const
Return the file path associated with the level.
virtual bool isEmpty () const
virtual int getFrameCount () const
virtual void getFids (std::vector< TFrameId > &fids) const
void loadData (TIStream &is) override=0
Load the level data (i.e. name, path, etc. e.g. from the .tnz file)
void saveData (TOStream &os) override=0
Save the level data (i.e. name, path, etc. e.g. to the .tnz file)
virtual void load ()=0
Load the level content from the associated path.
virtual void save ()=0
Save the level content to the associated path.
HookSet * getHookSet () const
virtual void setDirtyFlag (bool on)
Mark the level as "modified".
Public Member Functions inherited from TSmartObject
TSmartObject (ClassCode classCode)
void addRef ()
void release ()
TINT32 getRefCount () const
Public Member Functions inherited from TPersist
virtual void loadData (TIStream &is)=0
virtual void saveData (TOStream &os)=0
std::string getStreamTag () const
virtual const TPersistDeclaration * getDeclaration () const =0
Additional Inherited Members
Public Types inherited from TSmartObject
typedef short ClassCode
Public Types inherited from TPersist
typedef TPersist * CreateProc()
Static Public Member Functions inherited from TSmartObject
static TINT32 getInstanceCount (ClassCode code)
Static Public Member Functions inherited from TPersist
static void declare (CreateProc *)
static TPersist * create (const std::string &name)
Protected Member Functions inherited from TXshLevel
void updateShortName ()
create shortname from the level name
Protected Attributes inherited from TXshLevel
std::wstring m_name
std::wstring m_shortName
int m_type
HookSet * m_hookSet
ToonzScene * m_scene
Detailed Description
The TXshChildLevel class provides a child level of xsheet and allows its management.
Inherits TXshLevel.
A child level getChildLevel() is a xsheet reduced to level. The class allows to edit xsheet getXsheet(), change xsheet setXsheet() and change scene xsheet setScene(). It's possibile change level name setName() and know how many frame are in level getFrameCount().
The class provides methods to control child level icon, makeIcon(), getIcon() and invalidateIcon().
Constructor & Destructor Documentation
TXshChildLevel()
TXshChildLevel::TXshChildLevel (std::wstring name = L"")
Constructs a TXshChildLevel with TXshLevel name name
    : TXshLevel(m_classCode, name), m_xsheet(new TXsheet()), m_iconId() {
  m_xsheet->addRef();
  m_type = CHILD_XSHLEVEL;
}
~TXshChildLevel()
TXshChildLevel::~TXshChildLevel ()
Destroys the TXshChildLevel object.
{
  m_xsheet->release();
  if (m_iconId != "") {
    ImageManager::instance()->bind(m_iconId, 0);
    TImageCache::instance()->remove(m_iconId);
  }
}
References ImageManager::bind(), and TImageCache::remove().
Member Function Documentation
getChildLevel()
TXshChildLevel * TXshChildLevel::getChildLevel () inline override virtual
Return the TXshChildLevel child level.
Reimplemented from TXshLevel.
{ return this; }
getFids()
void TXshChildLevel::getFids (std::vector< TFrameId > & fids) const override virtual
Set the vector fids to the frameId of level.
Reimplemented from TXshLevel.
{
  int i;
  for (i = 1; i <= getFrameCount(); i++) fids.push_back(TFrameId(i));
}
References getFrameCount().
getFrameCount()
int TXshChildLevel::getFrameCount () const override virtual
Return the frame count.
Reimplemented from TXshLevel.
{
  if (m_xsheet)
    return m_xsheet->getFrameCount();
  else
    return 0;
}
References TXsheet::getFrameCount().
Referenced by getFids().
getXsheet()
TXsheet * TXshChildLevel::getXsheet () inline
Return the level TXsheet.
See also
setXsheet()
{ return m_xsheet; }
Referenced by TXsheet::checkCircularReferences(), ToonzScene::createNewLevel(), ToonzScene::getSoundColumns(), TXsheet::getUsedLevels(), FxBuilder::makePF(), ChildStack::openChild(), and Stage::Player::texture().
load()
void TXshChildLevel::load () inline override virtual
Load the level content from the associated path.
Implements TXshLevel.
{}
loadData()
void TXshChildLevel::loadData (TIStream & is) override virtual
Load the level data (i.e. name, path, etc. e.g. from the .tnz file)
Implements TXshLevel.
{
  if (m_xsheet) m_xsheet->release();
  m_xsheet = 0;
  is >> m_xsheet;
  m_xsheet->addRef();
  std::string tagName;
  if (is.matchTag(tagName)) {
    if (tagName == "name") {
      std::wstring name;
      is >> name;
      setName(name);
    }
    is.closeChild();
  }
}
References TIStream::closeChild(), and TIStream::matchTag().
save()
void TXshChildLevel::save () inline override virtual
Save the level content to the associated path.
Implements TXshLevel.
{}
saveData()
void TXshChildLevel::saveData (TOStream & os) override virtual
Save the level data (i.e. name, path, etc. e.g. to the .tnz file)
Implements TXshLevel.
{
  os << m_xsheet;
  os.child("name") << getName();
}
References TOStream::child(), and TXshLevel::getName().
setScene()
void TXshChildLevel::setScene (ToonzScene * scene) override virtual
Override. Set level scene to scene.
Reimplemented from TXshLevel.
{
  TXshLevel::setScene(scene);
  assert(m_xsheet);
  if (!m_xsheet) return;
  m_xsheet->setScene(scene);
  int i, columnCount = m_xsheet->getColumnCount();
  for (i = 0; i < columnCount; i++)
    if (m_xsheet->getColumn(i)) m_xsheet->getColumn(i)->setXsheet(m_xsheet);
}
References TXsheet::getColumn(), TXsheet::getColumnCount(), TXsheet::setScene(), TXshLevel::setScene(), and TXshColumn::setXsheet().
Referenced by ToonzScene::createNewLevel().
setXsheet()
void TXshChildLevel::setXsheet (TXsheet * xsheet)
Set the level TXsheet to xsheet.
See also
getXsheet()
{
  xsheet->addRef();
  m_xsheet->release();
  m_xsheet = xsheet;
}
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/toonz/txshchildlevel.h
E:/opentoonz/toonz/sources/toonzlib/txshchildlevel.cpp