opentoonz: TTexturesStorage Class Reference
TTexturesStorage Class Reference
TTexturesStorage is the class responsible for the storage of textures associated with mesh rendering.
#include <ttexturesstorage.h>
Public Member Functions
DrawableTextureDataP loadTexture (const std::string &textureId, const TRaster32P &ras, const TRectD &geometry)
Stores the specified raster to a group of OpenGL textures, returning a reference pointer ensuring the texture survival during its lifetime.
void unloadTexture (const std::string &textureId)
Releases the texture associated with the specified texture id.
DrawableTextureDataP getTextureData (const std::string &textureId)
Returns the texture data associated to the specified string identifier.
Static Public Member Functions
static TTexturesStorage * instance ()
Detailed Description
TTexturesStorage is the class responsible for the storage of textures associated with mesh rendering.
This class deals with textures storage and meshes compilation for drawing purposes. An OpenGL texture is typically split into several tiles before being rendered. A texturized mesh is then compiled against a texture in order to decide which mesh faces must be rendered with a given texture tile.
The TTextureStorage class uses a QCache to store texture objects up to a maximum memory size, plus all the already compiled mesh objects against the stored textures. Whenever a texture loading procedure would exceed the maximum textures size, the least accessed stored textures are automatically removed from the storage to make space for the newly assigned one.
Textures can be stored only if the OpenGL context they are loaded on has a valid known display lists proxy submitted in the TGLDisplayListsManager. In case the OpenGL context does not have a proxy, the loaded texture is a temporary, and will be deleted as soon as the returned TexturObject is destroyed (so, make sure the associated context is still current at that point).
Note
TTexturesStorage is thread-safe.
See also
The TGLDisplayListsManager class.
Member Function Documentation
getTextureData()
DrawableTextureDataP TTexturesStorage::getTextureData (const std::string & textureId)
Returns the texture data associated to the specified string identifier.
{
  // Get current display lists space
  TGlContext currentContext = tglGetCurrentContext();
  int dlSpaceId =
      TGLDisplayListsManager::instance()->displayListsSpaceId(currentContext);
  // If there is no known associated display lists space, the texture cannot be
  // stored.
  if (dlSpaceId < 0) return DrawableTextureDataP();
  QMutexLocker locker(&l_mutex);
  // Search the texture object
  QString texString(::textureString(dlSpaceId, textureId));
  if (!l_objects.contains(texString)) return DrawableTextureDataP();
  return *l_objects.object(texString);
}
References TGLDisplayListsManager::displayListsSpaceId().
instance()
TTexturesStorage * TTexturesStorage::instance () static
{
  static TTexturesStorage theInstance;
  return &theInstance;
}
loadTexture()
DrawableTextureDataP TTexturesStorage::loadTexture (const std::string & textureId, const TRaster32P & ras, const TRectD & geometry)
Stores the specified raster to a group of OpenGL textures, returning a reference pointer ensuring the texture survival during its lifetime.
Warning
This class may keep a copy of the specified texture only for a limited amount of time, if the current context has an associated display lists space proxy. Users must always be ready to reload the texture in case it was not found.
{
  // Try to retrieve the proxy associated to current OpenGL context
  TGlContext currentContext = tglGetCurrentContext();
  int dlSpaceId =
      TGLDisplayListsManager::instance()->displayListsSpaceId(currentContext);
  QString texString(::textureString(dlSpaceId, textureId));
  // Deal with containers
  QMutexLocker locker(&l_mutex);
  // If necessary, allocate a textures container
  std::map<int, TexturesContainer *>::iterator it =
      l_texturesContainers.find(dlSpaceId);
  if (it == l_texturesContainers.end())
    it = l_texturesContainers
             .insert(std::make_pair(dlSpaceId, new TexturesContainer))
             .first;
  MeshTexturizer &texturizer = it->second->m_texturizer;
  DrawableTextureDataP dataPtr = std::make_shared<DrawableTextureData>();
  DrawableTextureData *data    = dataPtr.get();
  data->m_dlSpaceId   = dlSpaceId;
  data->m_texId       = texturizer.bindTexture(ras, geometry);
  data->m_objIdx      = it->second->m_keys.push_back(texString);
  data->m_textureData = texturizer.getTextureData(data->m_texId);
  l_objects.insert(texString, new DrawableTextureDataP(dataPtr),
                   (ras->getLx() * ras->getLy() * ras->getPixelSize()) >> 10);
  if (dlSpaceId < 0) {
    // obj is a temporary. It was pushed in the cache to make space for it -
    // however, it must not be
    // stored. Remove it now.
    l_objects.remove(texString);
  }
  return dataPtr;
}
References MeshTexturizer::bindTexture(), TGLDisplayListsManager::displayListsSpaceId(), MeshTexturizer::getTextureData(), and DrawableTextureData::m_textureData.
Referenced by texture_utils::getTextureData().
unloadTexture()
void TTexturesStorage::unloadTexture (const std::string & textureId)
Releases the texture associated with the specified texture id.
{
  QMutexLocker locker(&l_mutex);
  // Remove the specified texture from ALL the display lists spaces
  std::map<int, TexturesContainer *>::iterator it,
      iEnd(l_texturesContainers.end());
  for (it = l_texturesContainers.begin(); it != iEnd; ++it)
    l_objects.remove(::textureString(it->first, textureId));
}
Referenced by texture_utils::invalidateTexture().
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/ext/ttexturesstorage.h
E:/opentoonz/toonz/sources/tnzext/ttexturesstorage.cpp