opentoonz: ToonzExt::CornerDeformation Class Reference
ToonzExt::CornerDeformation Class Reference final
Public Member Functions
bool check_ (const ContextStatus *status) override
bool findExtremes_ (const ContextStatus *, Interval &) override
double findActionLength () override
void draw (Designer *) override
Public Member Functions inherited from ToonzExt::StrokeDeformationImpl
ToonzExt::Interval getExtremes ()
const TStroke * getStrokeSelected () const
const TStroke * getCopiedStroke () const
virtual bool activate_impl (const ContextStatus *)
virtual void update_impl (const TPointD &delta)
virtual TStroke * deactivate_impl ()
bool check (const ContextStatus *)
virtual void reset ()
void setPotential (Potential *)
virtual void draw (Designer *)
TStroke * getTransformedStroke ()
ToonzExt::Potential * getPotential ()
TPointD & oldW0 ()
int getShortcutKey () const
int getCursorId () const
void setCursorId (int id)
Static Public Member Functions
static CornerDeformation * instance ()
Static Public Member Functions inherited from ToonzExt::StrokeDeformationImpl
static const ContextStatus *& getImplStatus ()
Additional Inherited Members
virtual bool check_ (const ContextStatus *)=0
virtual bool findExtremes_ (const ContextStatus *, Interval &)=0
virtual double findActionLength ()=0
Static Protected Member Functions inherited from ToonzExt::StrokeDeformationImpl
static TStroke *& getLastSelectedStroke ()
static void setLastSelectedStroke (TStroke *)
static int & getLastSelectedDegree ()
static void setLastSelectedDegree (int degree)
static ToonzExt::Intervals & getSpiresList ()
static ToonzExt::Intervals & getStraightsList ()
Protected Attributes inherited from ToonzExt::StrokeDeformationImpl
TStroke * stroke2manipulate_
ToonzExt::StrokeParametricDeformer * deformer_
int shortcutKey_
double old_w0_
TPointD old_w0_pos_
std::vector< TStroke * > strokes_
Detailed Description
Constructor & Destructor Documentation
~CornerDeformation()
CornerDeformation::~CornerDeformation () virtual
{}
Member Function Documentation
check_()
bool CornerDeformation::check_ (const ContextStatus *) override virtual
Is this the correct deformation?
Implements ToonzExt::StrokeDeformationImpl.
{
  assert(status && "Not status available");
  TStroke *s = status->stroke2change_;
  double w   = status->w_;
  if (isASpireCorner(s, w, status->cornerSize_, &this->getSpiresList()))
    return true;
#ifdef USE_TOLERANCE_IN_SELECTION
  // analyse if the selected distance is close to an extreme if an
  //  extreme is almost an extreme prefer to select extreme
  const TPointD pressed = status->stroke2change_->getPoint(status->w_);
  double pixelTolerance2 = sq(5 * status->pixelSize_);
  // array of corners
  std::vector<double> corners;
  // also if an straight extreme was not found prefer smooth
  if (cornersDetector(status->stroke2change_, status->cornerSize_, corners)) {
    while (!corners.empty()) {
      TPointD actual = status->stroke2change_->getPoint(corners.back());
      if (tdistance2(actual, pressed) < pixelTolerance2) {
        // status->w_ = corners.back();
        // out = CornerDeformation::instance();
        // break;
        this->w_ = corners.back();
        return true;
      }
      corners.pop_back();
    }
  }
#endif
  return false;
}
References ToonzExt::cornersDetector(), and TStroke::getPoint().
draw()
void CornerDeformation::draw (Designer * designer) override virtual
Apply a designer on current deformation.
Reimplemented from ToonzExt::StrokeDeformationImpl.
{
  StrokeDeformationImpl::draw(0);
  designer->draw(this);
}
References ToonzExt::StrokeDeformationImpl::draw().
findActionLength()
double CornerDeformation::findActionLength () override virtual
Implements ToonzExt::StrokeDeformationImpl.
{
  // just to limit action until parameters are not computed
  //  return  lengthOfAction_ < stroke2transform_->getLength() ?
  //          lengthOfAction_ : stroke2transform_->getLength();
  // return -1;//
  return stroke2manipulate_->getLength();
}
findExtremes_()
bool CornerDeformation::findExtremes_ (const ContextStatus * , Interval &) override virtual
Retrieve the nearest extremes to point selected.
Implements ToonzExt::StrokeDeformationImpl.
{
  return ToonzExt::findNearestSpireCorners(status->stroke2change_, status->w_,
                                           ret, status->cornerSize_,
                                           &this->getSpiresList());
}
References ToonzExt::findNearestSpireCorners().
instance()
CornerDeformation * CornerDeformation::instance () static
{
  static CornerDeformation singleton;
  return &singleton;
}
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/ext/CornerDeformation.h
E:/opentoonz/toonz/sources/tnzext/CornerDeformation.cpp