opentoonz: CustomStyleManager::StyleLoaderTask Class Reference
CustomStyleManager::StyleLoaderTask Class Reference final
Public Member Functions
StyleLoaderTask (CustomStyleManager *manager, const TFilePath &fp)
void run () override
The central code of the task that is executed by a worker thread.
void onFinished (TThread::RunnableP sender) override
The analogous of onStarted() for the finished() signal.
Public Member Functions inherited from TThread::Runnable
virtual void run ()=0
The central code of the task that is executed by a worker thread.
virtual int taskLoad ()
virtual int schedulingPriority ()
virtual QThread::Priority runningPriority ()
Public Member Functions inherited from TSmartObject
TSmartObject (ClassCode classCode)
void addRef ()
void release ()
TINT32 getRefCount () const
Additional Inherited Members
Public Types inherited from TSmartObject
typedef short ClassCode
Public Slots inherited from TThread::Runnable
virtual void onStarted (TThread::RunnableP sender)
virtual void onFinished (TThread::RunnableP sender)
The analogous of onStarted() for the finished() signal.
virtual void onException (TThread::RunnableP sender)
The analogous of onStarted() for the exception() signal.
virtual void onCanceled (TThread::RunnableP sender)
The analogous of onStarted() for the canceled() signal.
virtual void onTerminated (TThread::RunnableP sender)
The analogous of onStarted() for the terminated() signal.
Signals inherited from TThread::Runnable
void started (TThread::RunnableP sender)
void finished (TThread::RunnableP sender)
void exception (TThread::RunnableP sender)
void canceled (TThread::RunnableP sender)
void terminated (TThread::RunnableP sender)
Static Public Member Functions inherited from TSmartObject
static TINT32 getInstanceCount (ClassCode code)
Detailed Description
Constructor & Destructor Documentation
StyleLoaderTask()
CustomStyleManager::StyleLoaderTask::StyleLoaderTask (CustomStyleManager * manager, const TFilePath & fp)
    : m_manager(manager), m_fp(fp) {
  connect(this, SIGNAL(finished(TThread::RunnableP)), this,
          SLOT(onFinished(TThread::RunnableP)));
  if (QThread::currentThread() == qGuiApp->thread()) {
    m_offScreenSurface.reset(new QOffscreenSurface());
    m_offScreenSurface->setFormat(QSurfaceFormat::defaultFormat());
    m_offScreenSurface->create();
  }
}
Member Function Documentation
onFinished()
void CustomStyleManager::StyleLoaderTask::onFinished (TThread::RunnableP sender) override virtual
The analogous of onStarted() for the finished() signal.
Reimplemented from TThread::Runnable.
{
  // On the main thread...
  if (m_data.m_image)  // Everything went ok
  {
    m_manager->m_patterns.push_back(m_data);
    emit m_manager->patternAdded();
  }
}
run()
void CustomStyleManager::StyleLoaderTask::run () override virtual
The central code of the task that is executed by a worker thread.
Implements TThread::Runnable.
{
  try {
    // Fetch the level
    TLevelReaderP lr(m_fp);
    TLevelP level = lr->loadInfo();
    if (!level || level->getFrameCount() == 0) return;
    // Fetch the image of the first frame in the level
    TLevel::Iterator frameIt = level->begin();
    if (frameIt == level->end()) return;
    TImageP img = lr->getFrameReader(frameIt->first)->load();
    // Process the image
    const QSize &qChipSize = m_manager->getChipSize();
    TDimension chipSize(qChipSize.width(), qChipSize.height());
    TVectorImageP vimg = img;
    TRasterImageP rimg = img;
    TRaster32P ras;
    QImage *image = nullptr;
    if (vimg) {
      assert(level->getPalette());
      TPalette *vPalette = level->getPalette();
      assert(vPalette);
      vimg->setPalette(vPalette);
#ifdef LINUX
      TOfflineGL *glContext = 0;
      glContext             = TOfflineGL::getStock(chipSize);
      glContext->clear(TPixel32::White);
#else
      QOpenGLContext *glContext = new QOpenGLContext();
      if (QOpenGLContext::currentContext())
        glContext->setShareContext(QOpenGLContext::currentContext());
      glContext->setFormat(QSurfaceFormat::defaultFormat());
      glContext->create();
      glContext->makeCurrent(m_offScreenSurface.get());
      // attaching stencil buffer here as some styles use it
      QOpenGLFramebufferObject fb(
          chipSize.lx, chipSize.ly,
          QOpenGLFramebufferObject::CombinedDepthStencil);
      fb.bind();
      // Draw
      glViewport(0, 0, chipSize.lx, chipSize.ly);
      glClearColor(1.0, 1.0, 1.0, 1.0);  // clear with white color
      glClear(GL_COLOR_BUFFER_BIT);
      glMatrixMode(GL_PROJECTION);
      glLoadIdentity();
      gluOrtho2D(0, chipSize.lx, 0, chipSize.ly);
      glMatrixMode(GL_MODELVIEW);
      glLoadIdentity();
#endif
      TRectD bbox = img->getBBox();
      double scx  = 0.8 * chipSize.lx / bbox.getLx();
      double scy  = 0.8 * chipSize.ly / bbox.getLy();
      double sc   = std::min(scx, scy);
      double dx   = 0.5 * chipSize.lx;
      double dy   = 0.5 * chipSize.ly;
      TAffine aff =
          TTranslation(dx, dy) * TScale(sc) *
          TTranslation(-0.5 * (bbox.x0 + bbox.x1), -0.5 * (bbox.y0 + bbox.y1));
      TVectorRenderData rd(aff, chipSize, vPalette, 0, true);
#ifdef LINUX
      glContext->draw(img, rd);
      // No need to clone! The received raster already is a copy of the
      // context's buffer
      ras = glContext->getRaster();  //->clone();
#else
      tglDraw(rd, vimg.getPointer());
      image = new QImage(fb.toImage().scaled(QSize(chipSize.lx, chipSize.ly),
                                             Qt::IgnoreAspectRatio,
                                             Qt::SmoothTransformation));
      fb.release();
      glContext->deleteLater();
#endif
    } else if (rimg) {
      TDimension size = rimg->getRaster()->getSize();
      if (size == chipSize)
        ras = rimg->getRaster()->clone();  // Yep, this may be necessary
      else {
        TRaster32P rout(chipSize);
        TRop::resample(rout, rimg->getRaster(),
                       TScale((double)chipSize.lx / size.lx,
                              (double)chipSize.ly / size.ly));
        TRop::addBackground(rout, TPixel::White);
        ras = rout;
      }
#ifndef LINUX
      image = new QImage(chipSize.lx, chipSize.ly, QImage::Format_RGB32);
      convertRaster32ToImage(ras, image);
#endif
    } else
      assert(!"unsupported type for custom styles!");
#ifdef LINUX
    image = new QImage(chipSize.lx, chipSize.ly, QImage::Format_RGB32);
    convertRaster32ToImage(ras, image);
#endif
    m_data.m_patternName = m_fp.getName();
    m_data.m_isVector    = (m_fp.getType() == "pli" || m_fp.getType() == "svg");
    m_data.m_image       = image;
  } catch (...) {
  }
}
References TRop::addBackground(), TImage::getBBox(), TRop::resample(), and TRectT< T >::x0.
The documentation for this class was generated from the following file:
E:/opentoonz/toonz/sources/toonzlib/stylemanager.cpp