opentoonz: TSpectrumParam Class Reference
TSpectrumParam Class Reference final
Public Member Functions
TSpectrumParam (std::vector< TSpectrum::ColorKey > const &keys)
TSpectrumParam (const TSpectrumParam &)
TParam * clone () const override
void copy (TParam *src) override
void addObserver (TParamObserver *) override
void removeObserver (TParamObserver *) override
TSpectrum getValue (double frame) const
TSpectrum64 getValue64 (double frame) const
void setValue (double frame, const TSpectrum &value, bool undoing=false)
void setDefaultValue (const TSpectrum &value)
int getKeyCount () const
TDoubleParamP getPosition (int index) const
TPixelParamP getColor (int index) const
void setValue (double frame, int index, double s, const TPixel32 &color, bool undoing=false)
void insertKey (int index, double s, const TPixel32 &color)
void addKey (double s, const TPixel32 &color)
void removeKey (int index)
bool isAnimatable () const override
bool isKeyframe (double frame) const override
void deleteKeyframe (double frame) override
void clearKeyframes () override
void assignKeyframe (double frame, const TSmartPointerT< TParam > &src, double srcFrame, bool changedOnly=false) override
void loadData (TIStream &is) override
void saveData (TOStream &os) override
void enableDragging (bool on)
void enableNotification (bool on) override
bool isNotificationEnabled () const override
void enableMatte (bool on)
bool isMatteEnabled () const
std::string getValueAlias (double frame, int precision) override
bool hasKeyframes () const override
void getKeyframes (std::set< double > &frames) const override
int getNextKeyframe (double frame) const override
int getPrevKeyframe (double frame) const override
double keyframeIndexToFrame (int index) const override
Public Member Functions inherited from TParam
TParam (std::string name="", std::string description="", std::string label="")
std::string getName () const
void setName (const std::string &name)
std::string getDescription () const
void setDescription (const std::string &description)
bool hasUILabel () const
void setUILabel (const std::string &l)
std::string getUILabel () const
virtual TParam * clone () const =0
virtual void copy (TParam *src)=0
virtual void addObserver (TParamObserver *)=0
virtual void removeObserver (TParamObserver *)=0
virtual void enableNotification (bool on)
virtual bool isNotificationEnabled () const
virtual std::string getValueAlias (double frame, int precision)=0
virtual bool isAnimatable () const =0
virtual bool isKeyframe (double frame) const =0
virtual void deleteKeyframe (double frame)=0
virtual void clearKeyframes ()=0
virtual void assignKeyframe (double frame, const TSmartPointerT< TParam > &src, double srcFrame, bool changedOnly=false)=0
virtual void getKeyframes (std::set< double > &frames) const
virtual bool hasKeyframes () const
virtual int getNextKeyframe (double frame) const
virtual int getPrevKeyframe (double frame) const
virtual double keyframeIndexToFrame (int index) const
Public Member Functions inherited from TSmartObject
TSmartObject (ClassCode classCode)
void addRef ()
void release ()
TINT32 getRefCount () const
Public Member Functions inherited from TPersist
virtual void loadData (TIStream &is)=0
virtual void saveData (TOStream &os)=0
std::string getStreamTag () const
virtual const TPersistDeclaration * getDeclaration () const =0
Additional Inherited Members
Public Types inherited from TSmartObject
typedef short ClassCode
Public Types inherited from TPersist
typedef TPersist * CreateProc()
Static Public Member Functions inherited from TSmartObject
static TINT32 getInstanceCount (ClassCode code)
Static Public Member Functions inherited from TPersist
static void declare (CreateProc *)
static TPersist * create (const std::string &name)
Detailed Description
Constructor & Destructor Documentation
TSpectrumParam() [1/3]
TSpectrumParam::TSpectrumParam ()
    : m_imp(new TSpectrumParamImp(this))  // brutto...
{
  ColorKeyParam ck1(TDoubleParamP(0.0), TPixelParamP(TPixel32::Black));
  ColorKeyParam ck2(TDoubleParamP(1.0), TPixelParamP(TPixel32::White));
  m_imp->addKey(ck1);
  m_imp->addKey(ck2);
}
TSpectrumParam() [2/3]
TSpectrumParam::TSpectrumParam (std::vector< TSpectrum::ColorKey > const & keys)
    : m_imp(new TSpectrumParamImp(this)) {
  for (auto const &key : keys) {
    double v     = key.first;
    TPixel32 pix = key.second;
    TDoubleParamP dp(v);
    TPixelParamP pp(pix);
    pp->enableMatte(m_imp->m_isMatteEnabled);
    ColorKeyParam ck(dp, pp);
    m_imp->addKey(ck);
  }
}
TSpectrumParam() [3/3]
TSpectrumParam::TSpectrumParam (const TSpectrumParam & src)
    : TParam(src.getName()), m_imp(new TSpectrumParamImp(*src.m_imp)) {}
~TSpectrumParam()
TSpectrumParam::~TSpectrumParam ()
{}
Member Function Documentation
addKey()
void TSpectrumParam::addKey (double s, const TPixel32 & color)
{
  /*
assert(m_imp);
insertKey(m_imp->getKeyCount(), s,color);
*/
  int index = m_imp->getKeyCount();
  assert(m_imp);
  int keyCount = m_imp->getKeyCount();
  if (index < 0)
    index = 0;
  else if (index >= keyCount)
    index = keyCount;
  TDoubleParamP dp(s);
  TPixelParamP pp(color);
  pp->enableMatte(m_imp->m_isMatteEnabled);
  ColorKeyParam ck(dp, pp);
  m_imp->insertKey(index, ck);
}
addObserver()
void TSpectrumParam::addObserver (TParamObserver *) override virtual
 An observer is a generic class that takes care and manages of canghes
in the parameters. This method must be implemented with a function that add objects to an observer internal list.
Implements TParam.
{
  m_imp->m_observers.insert(obs);
}
assignKeyframe()
void TSpectrumParam::assignKeyframe (double frame, const TSmartPointerT< TParam > & src, double srcFrame, bool changedOnly = false) override virtual
Makes the frame associated to this parameter a keyframe
Implements TParam.
{
  TSpectrumParamP spectrum = src;
  if (!spectrum) return;
  int keyCount = m_imp->getKeyCount();
  if (keyCount != spectrum->m_imp->getKeyCount()) return;
  for (int i = 0; i < keyCount; i++) {
    ColorKeyParam dstKey = m_imp->getKey(i);
    ColorKeyParam srcKey = spectrum->m_imp->getKey(i);
    dstKey.first->setValue(frame, srcKey.first->getValue(srcFrame));
    dstKey.second->setValue(frame, srcKey.second->getValue(srcFrame));
  }
}
clearKeyframes()
void TSpectrumParam::clearKeyframes () override virtual
Removes all keyframes from this parameter.
Implements TParam.
{
  assert(m_imp);
  int k, keyCount = m_imp->getKeyCount();
  for (k = 0; k < keyCount; ++k) {
    const ColorKeyParam &key = m_imp->getKey(k);
    key.first->clearKeyframes();
    key.second->clearKeyframes();
  }
  m_imp->notify(TParamChange(this, TParamChange::m_minFrame,
                             TParamChange::m_maxFrame, true,
                             m_imp->m_draggingEnabled, false));
}
clone()
TParam * TSpectrumParam::clone () const inline override virtual
 This method must be implemented with a clone function, i.e a function
that make a new copy of the parameter.
Implements TParam.
{ return new TSpectrumParam(*this); }
copy()
void TSpectrumParam::copy (TParam * src) override virtual
Performs a copy function of the parameter in an existing object.
Implements TParam.
{
  TSpectrumParam *p = dynamic_cast<TSpectrumParam *>(src);
  if (!p) throw TException("invalid source for copy");
  setName(src->getName());
  m_imp->copy(*(p->m_imp));
}
References TParam::getName(), and TParam::setName().
deleteKeyframe()
void TSpectrumParam::deleteKeyframe (double frame) override virtual
 Removes \e frame from the list of the keyframes associated to this
parameter.
Implements TParam.
{
  int keyCount = m_imp->getKeyCount();
  for (int i = 0; i < keyCount; i++) {
    ColorKeyParam currentKey = m_imp->getKey(i);
    currentKey.first->deleteKeyframe(frame);
    currentKey.second->deleteKeyframe(frame);
  }
}
enableDragging()
void TSpectrumParam::enableDragging (bool on)
{ m_imp->m_draggingEnabled = on; }
enableMatte()
void TSpectrumParam::enableMatte (bool on)
{ m_imp->m_isMatteEnabled = on; }
enableNotification()
void TSpectrumParam::enableNotification (bool on) override virtual
 This method is used to sets the status changing notification of the
parameter. i.e the observer must take care of the changes.
Reimplemented from TParam.
{
  m_imp->m_notificationEnabled = on;
}
getColor()
TPixelParamP TSpectrumParam::getColor (int index) const
{
  assert(index <= m_imp->getKeyCount());
  return m_imp->getKey(index).second;
}
getKeyCount()
int TSpectrumParam::getKeyCount () const
{
  assert(m_imp);
  return m_imp->getKeyCount();
}
getKeyframes()
void TSpectrumParam::getKeyframes (std::set< double > & frames) const override virtual
 This function must be overridden with a method that returns as a
reference a list of keyframes in the form of a standard list.
Reimplemented from TParam.
{
  int keyCount = m_imp->getKeyCount();
  for (int i = 0; i < keyCount; i++) {
    ColorKeyParam currentKey = m_imp->getKey(i);
    currentKey.first->getKeyframes(frames);
    currentKey.second->getKeyframes(frames);
  }
}
Referenced by getNextKeyframe(), getPrevKeyframe(), and keyframeIndexToFrame().
getNextKeyframe()
int TSpectrumParam::getNextKeyframe (double frame) const override virtual
 This method must return the index of the keyframe (if any) after the
frame, otherwiswe returns -1.
Reimplemented from TParam.
{
  std::set<double> frames;
  getKeyframes(frames);
  std::set<double>::iterator it = frames.upper_bound(frame);
  if (it == frames.end())
    return -1;
  else
    return std::distance(frames.begin(), it);
}
References getKeyframes().
getPosition()
TDoubleParamP TSpectrumParam::getPosition (int index) const
{
  assert(index <= m_imp->getKeyCount());
  return m_imp->getKey(index).first;
}
getPrevKeyframe()
int TSpectrumParam::getPrevKeyframe (double frame) const override virtual
 This method must return the index of the keyframe (if any) before the
frame, otherwiswe returns -1.
Reimplemented from TParam.
{
  std::set<double> frames;
  getKeyframes(frames);
  std::set<double>::iterator it = frames.lower_bound(frame);
  if (it == frames.begin())
    return -1;
  else {
    --it;
    return std::distance(frames.begin(), it);
  }
}
References getKeyframes().
getValue()
TSpectrum TSpectrumParam::getValue (double frame) const
{
  assert(m_imp);
  std::vector<TSpectrum::ColorKey> keys;
  int keyCount = m_imp->getKeyCount();
  for (int i = 0; i < keyCount; i++) {
    ColorKeyParam paramKey = m_imp->getKey(i);
    TSpectrum::ColorKey key(paramKey.first->getValue(frame),
                            paramKey.second->getValue(frame));
    keys.push_back(key);
  }
  return TSpectrum(keys.size(), &keys[0]);
}
getValue64()
TSpectrum64 TSpectrumParam::getValue64 (double frame) const
{
  assert(m_imp);
  std::vector<TSpectrum64::ColorKey> keys;
  int keyCount = m_imp->getKeyCount();
  for (int i = 0; i < keyCount; i++) {
    ColorKeyParam paramKey = m_imp->getKey(i);
    TSpectrum64::ColorKey key(paramKey.first->getValue(frame),
                              toPixel64(paramKey.second->getValue(frame)));
    keys.push_back(key);
  }
  return TSpectrum64(keys.size(), &keys[0]);
}
getValueAlias()
std::string TSpectrumParam::getValueAlias (double frame, int precision) override virtual
 This pure virtual method must return a string with the value of the
parameter and the precision needed.
Implements TParam.
{
  std::vector<TSpectrum::ColorKey> keys;
  int keyCount = m_imp->getKeyCount();
  for (int i = 0; i < keyCount; i++) {
    ColorKeyParam paramKey = m_imp->getKey(i);
    TSpectrum::ColorKey key(paramKey.first->getValue(frame),
                            paramKey.second->getValue(frame));
    keys.push_back(key);
  }
  std::string alias = "(";
  if (!keys.empty()) {
    std::vector<TSpectrum::ColorKey>::iterator it  = keys.begin();
    std::vector<TSpectrum::ColorKey>::iterator end = keys.begin();
    std::advance(end, keys.size() - 1);
    for (; it != end; ++it) {
      alias += toString(*it, precision);
      alias += ",";
    }
    alias += toString(*it, precision);
  }
  alias += ")";
  return alias;
}
hasKeyframes()
bool TSpectrumParam::hasKeyframes () const override virtual
 This method must return true if there are keyframes associated to this
parameter.
Reimplemented from TParam.
{
  int keyCount = m_imp->getKeyCount();
  for (int i = 0; i < keyCount; i++) {
    ColorKeyParam currentKey = m_imp->getKey(i);
    if (currentKey.first->hasKeyframes() || currentKey.second->hasKeyframes())
      return true;
  }
  return false;
}
insertKey()
void TSpectrumParam::insertKey (int index, double s, const TPixel32 & color)
{
  assert(m_imp);
  int keyCount = m_imp->getKeyCount();
  if (index < 0)
    index = 0;
  else if (index >= keyCount)
    index = keyCount;
  TDoubleParamP dp(s);
  TPixelParamP pp(color);
  pp->enableMatte(m_imp->m_isMatteEnabled);
  ColorKeyParam ck(dp, pp);
  m_imp->insertKey(index, ck);
}
isAnimatable()
bool TSpectrumParam::isAnimatable () const inline override virtual
Implements TParam.
{ return true; }
isKeyframe()
bool TSpectrumParam::isKeyframe (double frame) const override virtual
It must returns true if the frame is a keyframe.
Implements TParam.
{
  int keyCount = m_imp->getKeyCount();
  for (int i = 0; i < keyCount; i++) {
    ColorKeyParam currentKey = m_imp->getKey(i);
    if (currentKey.first->isKeyframe(frame)) return true;
    if (currentKey.second->isKeyframe(frame)) return true;
  }
  return false;
}
isMatteEnabled()
bool TSpectrumParam::isMatteEnabled () const
{ return m_imp->m_isMatteEnabled; }
isNotificationEnabled()
bool TSpectrumParam::isNotificationEnabled () const override virtual
 This method must return \e true if the  notification status is
enabled.
Reimplemented from TParam.
{
  return m_imp->m_notificationEnabled;
}
keyframeIndexToFrame()
double TSpectrumParam::keyframeIndexToFrame (int index) const override virtual
 This method must returns a frame given the index \e index. A frame is
a double value representing a frame.
Reimplemented from TParam.
{
  std::set<double> frames;
  getKeyframes(frames);
  assert(0 <= index && index < (int)frames.size());
  std::set<double>::const_iterator it = frames.begin();
  std::advance(it, index);
  return *it;
}
References getKeyframes().
loadData()
void TSpectrumParam::loadData (TIStream & is) override virtual
 This is a pure virtual function and must be overridden with a method
that implements the object loading from a stream (i.e take the object's features from a formatted data stream). For example the TStageObject class use his implementation to take the values of the parameters that characterizes a stage object as name, coordinates, etc... from a file. is is an input file stream
Implements TPersist.
{
  assert(m_imp);
  m_imp->clearKeys();
  std::string tagName;
  is.openChild(tagName);
  assert(tagName == "spectrum");
  while (!is.eos()) {
    TDoubleParamP pos(0.0);
    TPixelParamP color(TPixel32::Black);
    is.openChild(tagName);
    pos->loadData(is);
    is.closeChild();
    is.openChild(tagName);
    color->loadData(is);
    is.closeChild();
    ColorKeyParam ck(pos, color);
    m_imp->addKey(ck);
  }
  is.closeChild();
}
References TIStream::closeChild(), TIStream::eos(), and TIStream::openChild().
removeKey()
void TSpectrumParam::removeKey (int index)
{
  assert(m_imp);
  int keyCount = m_imp->getKeyCount();
  if (index < 0 || index >= keyCount)
    throw TException("TSpectrumParam::removeKey. Index out of range");
  m_imp->eraseKey(index);
}
removeObserver()
void TSpectrumParam::removeObserver (TParamObserver *) override virtual
Removes this from the observer.
See also
addObserver()
Implements TParam.
{
  m_imp->m_observers.erase(obs);
}
saveData()
void TSpectrumParam::saveData (TOStream & os) override virtual
 This is a pure virtual function and must be overridden with a method
that implements the object saving to a data stream (i.e put the object's features on a formatted data stream). For example the TStageObject class use his implementation to save the values of the parameters that characterizes a stage object as name, coordinates, etc... on a file os is an output file stream.
Implements TPersist.
{
  assert(m_imp);
  int keyCount = m_imp->getKeyCount();
  os.openChild("spectrum");
  for (int i = 0; i < keyCount; i++) {
    ColorKeyParam key = m_imp->getKey(i);
    os.openChild("s_value");
    key.first->saveData(os);
    os.closeChild();
    os.openChild("col_value");
    key.second->saveData(os);
    os.closeChild();
  }
  os.closeChild();
}
References TOStream::closeChild(), and TOStream::openChild().
setDefaultValue()
void TSpectrumParam::setDefaultValue (const TSpectrum & value)
{
  assert(value.getKeyCount() == getKeyCount());
  for (int i = 0; i < getKeyCount(); i++) {
    ColorKeyParam dstKeyParam = m_imp->getKey(i);
    TSpectrum::Key srcKey     = value.getKey(i);
    dstKeyParam.first->setDefaultValue(srcKey.first);
    dstKeyParam.second->setDefaultValue(srcKey.second);
  }
}
setValue() [1/2]
void TSpectrumParam::setValue (double frame, const TSpectrum & value, bool undoing = false)
{
  assert(getKeyCount() == spectrum.getKeyCount());
  int keyCount = getKeyCount();
  for (int i = 0; i < keyCount; i++) {
    TSpectrum::Key key = spectrum.getKey(i);
    setValue(frame, i, key.first, key.second, undoing);
  }
}
setValue() [2/2]
void TSpectrumParam::setValue (double frame, int index, double s, const TPixel32 & color, bool undoing = false)
{
  assert(m_imp);
  int keyCount = m_imp->getKeyCount();
  if (index < 0 || index >= keyCount)
    throw TException("TSpectrumParam::setValue. Index out of range");
  ColorKeyParam key = m_imp->getKey(index);
  //  beginParameterChange();
  key.first->setValue(frame, s);
  key.second->setValue(frame, color);
  //  endParameterChange();
  m_imp->notify(TParamChange(this, TParamChange::m_minFrame,
                             TParamChange::m_maxFrame, true,
                             m_imp->m_draggingEnabled, false));
}
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/tspectrumparam.h
E:/opentoonz/toonz/sources/common/tparam/tspectrumparam.cpp