opentoonz: FullColorEraserTool Class Reference
FullColorEraserTool Class Reference final
Public Member Functions
FullColorEraserTool (std::string name)
ToolType getToolType () const override
void updateTranslation () override
void onActivate () override
Callback invoked whenever the tool activates.
void onDeactivate () override
Callback for tool deactivation, includes tool switch.
void leftButtonDown (const TPointD &pos, const TMouseEvent &e) override
void leftButtonDrag (const TPointD &pos, const TMouseEvent &e) override
void leftButtonUp (const TPointD &pos, const TMouseEvent &e) override
void leftButtonDoubleClick (const TPointD &pos, const TMouseEvent &e) override
void mouseMove (const TPointD &pos, const TMouseEvent &e) override
void draw () override
Draws the tool on the viewer.
int getCursorId () const override
Returns the type of cursor used by the tool.
TPropertyGroup * getProperties (int targetType) override
bool onPropertyChanged (std::string propertyName) override
void onImageChanged () override
Notifies changes in the image in use.
void onEnter () override
Callback for the mouse entering the viewer area.
void update (const TRasterImageP &ri, TRectD selArea, const TXshSimpleLevelP &level, bool multi=false, const TFrameId &frameId=-1)
void multiUpdate (const TRectD firstRect, const TRectD lastRect)
void multiAreaEraser (TFrameId &firstFid, TFrameId &lastFid, TStroke *firstStroke, TStroke *lastStroke)
void doMultiEraser (const TImageP &img, double t, const TFrameId &fid, const TVectorImageP &firstImage, const TVectorImageP &lastImage)
void resetMulti ()
Public Member Functions inherited from TTool
TTool (std::string toolName)
every tool (invoking updateTranslation() for each).
virtual ToolType getToolType () const =0
ToolTargetType getTargetType () const
std::string getName () const
virtual ToolOptionsBox * createOptionsBox ()
void setViewer (Viewer *viewer)
Viewer * getViewer () const
double getPixelSize () const
void invalidate (const TRectD &rect=TRectD())
int pick (const TPointD &p)
bool isPicking () const
virtual void updateTranslation ()
virtual bool preLeftButtonDown ()
virtual void mouseMove (const TPointD &, const TMouseEvent &)
virtual void leftButtonDown (const TPointD &, const TMouseEvent &)
virtual void leftButtonDrag (const TPointD &, const TMouseEvent &)
virtual void leftButtonUp (const TPointD &, const TMouseEvent &)
virtual void leftButtonDoubleClick (const TPointD &, const TMouseEvent &)
virtual void rightButtonDown (const TPointD &, const TMouseEvent &)
virtual bool keyDown (QKeyEvent *)
virtual void onInputText (std::wstring, std::wstring, int, int)
virtual void onSetViewer ()
virtual void onActivate ()
Callback invoked whenever the tool activates.
virtual void onDeactivate ()
Callback for tool deactivation, includes tool switch.
virtual void onImageChanged ()
Notifies changes in the image in use.
virtual void onEnter ()
Callback for the mouse entering the viewer area.
virtual void onLeave ()
Callback for the mouse leaving the viewer area.
virtual void onFrameSwitched ()
virtual void reset ()
virtual void draw ()
Draws the tool on the viewer.
bool isActive () const
Used to know if a tool is active, (used in TextTool only).
void setActive (bool active)
virtual TPropertyGroup * getProperties (int)
virtual bool onPropertyChanged (std::string propertyName)
virtual TSelection * getSelection ()
Returns a pointer to the tool selection.
virtual int getCursorId () const
Returns the type of cursor used by the tool.
virtual bool isEventAcceptable (QEvent *e)
TXsheet * getXsheet () const
Returns a pointer to the actual Xsheet.
int getFrame ()
Returns the actual frame in use.
int getColumnIndex ()
Returns the actual column index.
TStageObjectId getObjectId () const
Returns a pointer to the actual stage object.
void notifyImageChanged ()
void notifyImageChanged (const TFrameId &fid)
images on the level view.
TFrameId getCurrentFid () const
Returns the number of the actual editing frame.
const TAffine & getMatrix () const
void setMatrix (const TAffine &matrix)
TAffine getCurrentColumnMatrix (int frame=-1) const
TAffine getCurrentColumnParentMatrix () const
TAffine getCurrentObjectParentMatrix () const
TAffine getCurrentObjectParentMatrix2 () const
TAffine getColumnMatrix (int index, int frame=-1) const
virtual void updateMatrix ()
virtual void addContextMenuItems (QMenu *menu)
void enable (bool on)
bool isEnabled () const
QString updateEnabled ()
virtual QString updateEnabled (int rowIndex, int columnIndex)
bool isColumnLocked (int columnIndex) const
void resetInputMethod ()
Resets Input Context (IME)
virtual bool isPencilModeActive ()
virtual bool isDragging () const
void setSelectedFrames (const std::set< TFrameId > &selectedFrames)
void tweenSelectedGuideStrokes ()
void tweenGuideStrokeToSelected ()
void flipGuideStrokeDirection (int mode)
Additional Inherited Members
Public Types inherited from TTool
enum ToolType {
GenericTool = 1 , ColumnTool = 2 , LevelReadTool = 4 , LevelWriteTool ,
LevelTool = LevelReadTool | LevelWriteTool
}
Tool editing type.
enum ToolTargetType {
NoTarget = 0x0 , VectorImage = 0x1 , ToonzImage = 0x2 , RasterImage = 0x4 ,
MeshImage = 0x8 , Splines = 0x10 , LevelColumns = 0x20 , MeshColumns = 0x40 ,
EmptyTarget = 0x80 , CommonImages = VectorImage | ToonzImage | RasterImage , AllImages = CommonImages | MeshImage , Vectors = VectorImage | Splines ,
CommonLevels = CommonImages | LevelColumns , MeshLevels = MeshImage | MeshColumns , AllTargets = 0xffffffff
}
Object types the tool can operate on.
typedef TApplication Application
Static Public Member Functions inherited from TTool
static TTool * getTool (std::string toolName, ToolTargetType targetType)
static TApplication * getApplication ()
static void setApplication (TApplication *application)
static TXshCell getImageCell ()
Returns the level-frame pair to be edited by the tool.
static TImage * getImage (bool toBeModified, int subsampling=0)
Returns the image to be edited by the tool.
static TImage * touchImage ()
static void updateToolsPropertiesTranslation ()
static const std::set< TFrameId > & getSelectedFrames ()
Static Public Attributes inherited from TTool
static std::vector< CellOps > m_cellsData
static bool m_isLevelCreated = false
static bool m_isFrameCreated = false
static std::vector< TFrameId > m_oldFids
static std::vector< TFrameId > m_newFids
static bool m_isLevelRenumbererd = false
Protected Member Functions inherited from TTool
void bind (int targetType)
virtual void onSelectedFramesChanged ()
virtual QString disableString ()
Returns a custom reason to disable the tool.
Protected Attributes inherited from TTool
std::string m_name
The tool's name.
Viewer * m_viewer
Tool's current viewer.
TAffine m_matrix
World-to-window reference change affine.
int m_targetType
The tool's image type target.
bool m_enabled
Whether the tool allows user interaction.
bool m_active
bool m_picking
Static Protected Attributes inherited from TTool
static TApplication * m_application = 0
static std::set< TFrameId > m_selectedFrames = std::set<TFrameId>()
Detailed Description
Constructor & Destructor Documentation
FullColorEraserTool()
FullColorEraserTool::FullColorEraserTool (std::string name)
    : TTool(name)
    , m_size("Size:", 1, 1000, 5, false)
    , m_opacity("Opacity:", 0, 100, 100)
    , m_hardness("Hardness:", 0, 100, 100)
    , m_eraseType("Type:")
    , m_invertOption("Invert", false)
    , m_multi("Frame Range", false)
    , m_currCell(-1, -1)
    , m_brush(0)
    , m_tileSet(0)
    , m_tileSaver(0)
    , m_thick(0.5)
    , m_firstTime(true)
    , m_selecting(false)
    , m_firstFrameSelected(false)
    , m_isXsheetCell(false) {
  bind(TTool::RasterImage);
  m_size.setNonLinearSlider();
  m_prop.bind(m_size);
  m_prop.bind(m_hardness);
  m_prop.bind(m_opacity);
  m_prop.bind(m_eraseType);
  m_prop.bind(m_invertOption);
  m_prop.bind(m_multi);
  m_eraseType.addValue(NORMALERASE);
  m_eraseType.addValue(RECTERASE);
  m_eraseType.addValue(FREEHANDERASE);
  m_eraseType.addValue(POLYLINEERASE);
  m_eraseType.setId("Type");
  m_invertOption.setId("Invert");
  m_multi.setId("FrameRange");
}
~FullColorEraserTool()
FullColorEraserTool::~FullColorEraserTool ()
{ delete m_firstStroke; }
Member Function Documentation
doMultiEraser()
void FullColorEraserTool::doMultiEraser (const TImageP & img, double t, const TFrameId & fid, const TVectorImageP & firstImage, const TVectorImageP & lastImage)
{
  int styleId = TTool::getApplication()->getCurrentLevelStyleIndex();
  if (t == 0)
    eraseStroke(img, firstImage->getStroke(0), m_eraseType.getValue(),
                m_invertOption.getValue(), /*m_multi.getValue(),*/ m_level,
                fid);
  else if (t == 1)
    eraseStroke(img, lastImage->getStroke(0), m_eraseType.getValue(),
                m_invertOption.getValue(), /*m_multi.getValue(),*/ m_level,
                fid);
  else {
    assert(firstImage->getStrokeCount() == 1);
    assert(lastImage->getStrokeCount() == 1);
    TVectorImageP vi = TInbetween(firstImage, lastImage).tween(t);
    assert(vi->getStrokeCount() == 1);
    eraseStroke(img, vi->getStroke(0), m_eraseType.getValue(),
                m_invertOption.getValue(), /*m_multi.getValue(),*/ m_level,
                fid);
  }
}
draw()
void FullColorEraserTool::draw () override virtual
Draws the tool on the viewer.
Reimplemented from TTool.
{
  double pixelSize2 = getPixelSize() * getPixelSize();
  m_thick           = sqrt(pixelSize2) / 2.0;
  TRasterImageP img = (TRasterImageP)getImage(false);
  if (!img) return;
  if (m_eraseType.getValue() == NORMALERASE) {
    // If toggled off, don't draw brush outline
    if (!Preferences::instance()->isCursorOutlineEnabled()) return;
    glColor3d(1.0, 0.0, 0.0);
    tglDrawCircle(m_brushPos, (m_size.getValue() + 1) * 0.5);
  } else if (m_eraseType.getValue() == RECTERASE) {
    TPixel color = ToonzCheck::instance()->getChecks() & ToonzCheck::eBlackBg
                       ? TPixel32::White
                       : TPixel32::Black;
    if (m_multi.getValue() && m_firstFrameSelected)
      drawRect(m_firstRect, color, 0x3F33, true);
    if (m_selecting || (m_multi.getValue() && !m_firstFrameSelected))
      drawRect(m_selectingRect, color, 0x3F33, true);
  }
  if ((m_eraseType.getValue() == FREEHANDERASE ||
       m_eraseType.getValue() == POLYLINEERASE) &&
      m_multi.getValue()) {
    TPixel color = ToonzCheck::instance()->getChecks() & ToonzCheck::eBlackBg
                       ? TPixel32::White
                       : TPixel32::Black;
    tglColor(color);
    if (m_firstStroke) drawStrokeCenterline(*m_firstStroke, 1);
  }
  if (m_eraseType.getValue() == POLYLINEERASE && !m_polyline.empty()) {
    TPixel color = ToonzCheck::instance()->getChecks() & ToonzCheck::eBlackBg
                       ? TPixel32::White
                       : TPixel32::Black;
    tglColor(color);
    tglDrawCircle(m_polyline[0], 2 * m_thick);
    glBegin(GL_LINE_STRIP);
    for (UINT i = 0; i < m_polyline.size(); i++) tglVertex(m_polyline[i]);
    tglVertex(m_mousePos);
    glEnd();
  } else if (m_eraseType.getValue() == FREEHANDERASE && !m_track.isEmpty()) {
    TPixel color = ToonzCheck::instance()->getChecks() & ToonzCheck::eBlackBg
                       ? TPixel32::White
                       : TPixel32::Black;
    tglColor(color);
    m_track.drawAllFragments();
  }
}
References StrokeGenerator::drawAllFragments(), ToonzCheck::eBlackBg, TTool::getImage(), and StrokeGenerator::isEmpty().
getCursorId()
int FullColorEraserTool::getCursorId () const inline override virtual
Returns the type of cursor used by the tool.
See also
For a list of cursor ids cursor.h
Reimplemented from TTool.
{ return ToolCursor::PenCursor; }
getProperties()
TPropertyGroup * FullColorEraserTool::getProperties (int targetType) inline override virtual
Reimplemented from TTool.
{ return &m_prop; }
getToolType()
ToolType FullColorEraserTool::getToolType () const inline override virtual
Implements TTool.
{ return TTool::LevelWriteTool; }
leftButtonDoubleClick()
void FullColorEraserTool::leftButtonDoubleClick (const TPointD & pos, const TMouseEvent & e) override virtual
Reimplemented from TTool.
{
  TRasterImageP ri(getImage(true));
  if (!ri) return;
  TStroke *stroke;
  TTool::Application *app = TTool::getApplication();
  if (m_polyline.size() <= 1) {
    resetMulti();
    return;
  }
  if (m_polyline.back() != pos) m_polyline.push_back(pos);
  if (m_polyline.back() != m_polyline.front())
    m_polyline.push_back(m_polyline.front());
  std::vector<TThickPoint> strokePoints;
  for (UINT i = 0; i < m_polyline.size() - 1; i++) {
    strokePoints.push_back(TThickPoint(m_polyline[i], 1));
    strokePoints.push_back(
        TThickPoint(0.5 * (m_polyline[i] + m_polyline[i + 1]), 1));
  }
  strokePoints.push_back(TThickPoint(m_polyline.back(), 1));
  m_polyline.clear();
  stroke = new TStroke(strokePoints);
  assert(stroke->getPoint(0) == stroke->getPoint(1));
  if (m_multi.getValue())  // stroke multi
  {
    if (m_firstFrameSelected) {
      TFrameId tmp = getFrameId();
      if (m_firstStroke && stroke)
        multiAreaEraser(m_firstFrameId, tmp, m_firstStroke, stroke);
      if (e.isShiftPressed()) {
        TRectD invalidateRect = m_firstStroke->getBBox();
        delete m_firstStroke;
        m_firstStroke = 0;
        invalidate(invalidateRect.enlarge(2));
        m_firstStroke  = stroke;
        invalidateRect = m_firstStroke->getBBox();
        invalidate(invalidateRect.enlarge(2));
        m_firstFrameId = getFrameId();
      } else {
        if (m_isXsheetCell) {
          app->getCurrentColumn()->setColumnIndex(m_currCell.first);
          app->getCurrentFrame()->setFrame(m_currCell.second);
        } else
          app->getCurrentFrame()->setFid(m_veryFirstFrameId);
        resetMulti();
        delete stroke;
      }
    } else  // primo frame
    {
      m_firstStroke  = stroke;
      m_isXsheetCell = app->getCurrentFrame()->isEditingScene();
      m_currCell     = std::pair<int, int>(getColumnIndex(), getFrame());
      invalidate(m_firstStroke->getBBox().enlarge(2));
    }
  } else {
    if (!getImage(true)) return;
    TXshLevel *level          = app->getCurrentLevel()->getLevel();
    TXshSimpleLevelP simLevel = level->getSimpleLevel();
    TFrameId frameId          = getFrameId();
    eraseStroke(ri, stroke, m_eraseType.getValue(), m_invertOption.getValue(),
                /*m_multi.getValue(),*/ m_level, frameId);
    notifyImageChanged();
    if (m_invertOption.getValue())
      invalidate();
    else
      invalidate(stroke->getBBox().enlarge(2));
  }
}
leftButtonDown()
void FullColorEraserTool::leftButtonDown (const TPointD & pos, const TMouseEvent & e) override virtual
Reimplemented from TTool.
{
  m_brushPos = m_mousePos = pos;
  m_mouseEvent            = e;
  m_mousePressed          = true;
  TRasterImageP ri        = (TRasterImageP)getImage(true);
  if (!ri) return;
  TRectD invalidateRect;
  TRasterP ras = ri->getRaster();
  if (m_eraseType.getValue() == NORMALERASE) {
    TDimension dim  = ras->getSize();
    double opacity  = m_opacity.getValue() * 0.01;
    double hardness = m_hardness.getValue() * 0.01;
    m_workRaster    = TRaster32P(dim);
    m_workRaster->clear();
    m_backUpRas = ras->clone();
    int maxThick      = m_size.getValue();
    TPointD rasCenter = ras->getCenterD();
    TThickPoint point(pos + rasCenter, maxThick);
    TPointD halfThick(maxThick * 0.5, maxThick * 0.5);
    invalidateRect = TRectD(pos - halfThick, pos + halfThick);
    m_points.clear();
    m_points.push_back(point);
    m_tileSet   = new TTileSetFullColor(ras->getSize());
    m_tileSaver = new TTileSaverFullColor(ras, m_tileSet);
    m_brush =
        new BluredBrush(m_workRaster, m_size.getValue(), m_brushPad, false);
    TRect bbox = m_brush->getBoundFromPoints(m_points);
    m_tileSaver->save(bbox);
    m_brush->addPoint(point, 1);
    m_brush->eraseDrawing(ras, m_backUpRas, bbox, opacity);
  } else if (m_eraseType.getValue() == RECTERASE) {
    if (m_multi.getValue() && m_firstRect.isEmpty()) {
      invalidateRect = m_selectingRect;
      m_selectingRect.empty();
      invalidate(invalidateRect.enlarge(2));
    }
    m_selecting        = true;
    m_selectingRect.x0 = pos.x;
    m_selectingRect.y0 = pos.y;
    m_selectingRect.x1 = pos.x + 1;
    m_selectingRect.y1 = pos.y + 1;
    invalidateRect     = m_selectingRect;
  } else if (m_eraseType.getValue() == FREEHANDERASE ||
             m_eraseType.getValue() == POLYLINEERASE) {
    if (m_multi.getValue() && m_firstStroke && !m_firstFrameSelected) {
      invalidateRect = m_firstStroke->getBBox();
      delete m_firstStroke;
      m_firstStroke = 0;
      invalidate(invalidateRect.enlarge(2));
    }
    m_track.clear();
    m_firstPos        = pos;
    double pixelSize2 = getPixelSize() * getPixelSize();
    m_track.add(TThickPoint(pos, m_thick), pixelSize2);
    if (m_eraseType.getValue() == POLYLINEERASE) {
      if (m_polyline.empty() || m_polyline.back() != pos)
        m_polyline.push_back(pos);
    }
    int maxThick = 2 * m_thick;
    TPointD halfThick(maxThick * 0.5, maxThick * 0.5);
    invalidateRect = TRectD(pos - halfThick, pos + halfThick);
  }
  invalidate(invalidateRect.enlarge(2));
}
leftButtonDrag()
void FullColorEraserTool::leftButtonDrag (const TPointD & pos, const TMouseEvent & e) override virtual
Reimplemented from TTool.
{
  if (!m_mousePressed) return;
  m_brushPos = m_mousePos = pos;
  m_mouseEvent            = e;
  double pixelSize2       = getPixelSize() * getPixelSize();
  TRasterImageP ri = (TRasterImageP)getImage(true);
  if (!ri) return;
  if (m_eraseType.getValue() == NORMALERASE) {
    double thickness  = m_size.getValue();
    TDimension size   = m_workRaster->getSize();
    TPointD rasCenter = ri->getRaster()->getCenterD();
    TThickPoint point(pos + rasCenter, thickness);
    TThickPoint old = m_points.back();
    if (norm2(point - old) < 4) return;
    TThickPoint mid((old + point) * 0.5, (point.thick + old.thick) * 0.5);
    m_points.push_back(mid);
    m_points.push_back(point);
    int m          = m_points.size();
    double opacity = m_opacity.getValue() * 0.01;
    TThickPoint pa = m_points.front();
    std::vector<TThickPoint> points;
    points.push_back(pa);
    points.push_back(mid);
    TRect bbox;
    TRectD invalidateRect;
    if (m == 3) {
      TThickPoint pa = m_points.front();
      std::vector<TThickPoint> points;
      points.push_back(pa);
      points.push_back(mid);
      invalidateRect = ToolUtils::getBounds(points, thickness);
      bbox           = m_brush->getBoundFromPoints(points);
      m_tileSaver->save(bbox);
      m_brush->addArc(pa, (mid + pa) * 0.5, mid, 1, 1);
    } else {
      std::vector<TThickPoint> points;
      points.push_back(m_points[m - 4]);
      points.push_back(old);
      points.push_back(mid);
      invalidateRect = ToolUtils::getBounds(points, thickness);
      bbox           = m_brush->getBoundFromPoints(points);
      m_tileSaver->save(bbox);
      m_brush->addArc(m_points[m - 4], old, mid, 1, 1);
    }
    m_brush->eraseDrawing(ri->getRaster(), m_backUpRas, bbox, opacity);
    invalidate(invalidateRect.enlarge(2) - rasCenter);
  }
  if (m_eraseType.getValue() == RECTERASE) {
    assert(m_selecting);
    TRectD oldRect = m_selectingRect;
    if (oldRect.x0 > oldRect.x1) std::swap(oldRect.x1, oldRect.x0);
    if (oldRect.y0 > oldRect.y1) std::swap(oldRect.y1, oldRect.y0);
    m_selectingRect.x1 = pos.x;
    m_selectingRect.y1 = pos.y;
    TRectD invalidateRect(m_selectingRect);
    if (invalidateRect.x0 > invalidateRect.x1)
      std::swap(invalidateRect.x1, invalidateRect.x0);
    if (invalidateRect.y0 > invalidateRect.y1)
      std::swap(invalidateRect.y1, invalidateRect.y0);
    invalidateRect += oldRect;
    invalidate(invalidateRect.enlarge(2));
  }
  if (m_eraseType.getValue() == FREEHANDERASE) {
    m_track.add(TThickPoint(pos, m_thick), pixelSize2);
    invalidate(m_track.getModifiedRegion());
  }
}
leftButtonUp()
void FullColorEraserTool::leftButtonUp (const TPointD & pos, const TMouseEvent & e) override virtual
Reimplemented from TTool.
{
  m_brushPos = m_mousePos = pos;
  TRasterImageP ri        = (TRasterImageP)getImage(true);
  if (!ri) return;
  if (m_eraseType.getValue() == NORMALERASE) {
    if (m_points.size() != 1) {
      TPointD rasCenter = ri->getRaster()->getCenterD();
      TThickPoint point(pos + rasCenter, m_size.getValue());
      m_points.push_back(point);
      int m = m_points.size();
      std::vector<TThickPoint> points;
      points.push_back(m_points[m - 3]);
      points.push_back(m_points[m - 2]);
      points.push_back(m_points[m - 1]);
      TRect bbox = m_brush->getBoundFromPoints(points);
      m_tileSaver->save(bbox);
      m_brush->addArc(points[0], points[1], points[2], 1, 1);
      double opacity = m_opacity.getValue() * 0.01;
      m_brush->eraseDrawing(ri->getRaster(), m_backUpRas, bbox, opacity);
      TRectD invalidateRect = ToolUtils::getBounds(points, m_size.getValue());
      invalidate(invalidateRect.enlarge(2) - rasCenter);
    }
    if (m_brush) {
      delete m_brush;
      m_brush = 0;
    }
    m_workRaster->unlock();
    double opacity  = m_opacity.getValue() * 0.01;
    double hardness = m_hardness.getValue() * 0.01;
    m_workRaster = TRaster32P();
    m_backUpRas  = TRaster32P();
    delete m_tileSaver;
    TTool::Application *app   = TTool::getApplication();
    TXshLevel *level          = app->getCurrentLevel()->getLevel();
    TXshSimpleLevelP simLevel = level->getSimpleLevel();
    TFrameId frameId          = getCurrentFid();
    TUndoManager::manager()->add(new FullColorEraserUndo(
        m_tileSet, m_points, simLevel.getPointer(), frameId, m_size.getValue(),
        m_hardness.getValue() * 0.01, opacity));
    notifyImageChanged();
  } else if (m_eraseType.getValue() == RECTERASE) {
    if (m_selectingRect.x0 > m_selectingRect.x1)
      std::swap(m_selectingRect.x1, m_selectingRect.x0);
    if (m_selectingRect.y0 > m_selectingRect.y1)
      std::swap(m_selectingRect.y1, m_selectingRect.y0);
    if (m_multi.getValue()) {
      TTool::Application *app = TTool::getApplication();
      if (m_firstFrameSelected) {
        multiUpdate(m_firstRect, m_selectingRect);
        notifyImageChanged();
        if (e.isShiftPressed()) {
          m_firstRect    = m_selectingRect;
          m_firstFrameId = getFrameId();
          invalidate();
        } else {
          if (m_isXsheetCell) {
            app->getCurrentColumn()->setColumnIndex(m_currCell.first);
            app->getCurrentFrame()->setFrame(m_currCell.second);
          } else
            app->getCurrentFrame()->setFid(m_veryFirstFrameId);
          resetMulti();
        }
      } else {
        m_isXsheetCell = app->getCurrentFrame()->isEditingScene();
        m_currCell     = std::pair<int, int>(getColumnIndex(), getFrame());
      }
    } else {
      TTool::Application *app   = TTool::getApplication();
      TXshLevel *level          = app->getCurrentLevel()->getLevel();
      TXshSimpleLevelP simLevel = level->getSimpleLevel();
      TFrameId frameId          = getCurrentFid();
      if (m_invertOption.getValue()) {
        TUndoManager::manager()->beginBlock();
        TRect rect =
            TRasterImageUtils::convertWorldToRaster(m_selectingRect, ri);
        rect *= ri->getSavebox();
        TDimension dim = ri->getRaster()->getSize();
        TRectD rect01 =
            TRectD(TPointD(0., 0.), TPointD((double)rect.x0, (double)dim.ly));
        if (rect01.getLx() > 0 && rect01.getLy() > 0) {
          rect01 = TRasterImageUtils::convertRasterToWorld(convert(rect01), ri);
          update(ri, rect01, simLevel, false, frameId);
        }
        TRectD rect02 = TRectD(convert(rect.getP01()),
                               TPointD((double)rect.x1, (double)dim.ly));
        if (rect02.getLx() > 0 && rect02.getLy() > 0) {
          rect02 = TRasterImageUtils::convertRasterToWorld(convert(rect02), ri);
          update(ri, rect02, simLevel, false, frameId);
        }
        TRectD rect03 =
            TRectD(TPointD((double)rect.x0, 0.), convert(rect.getP10()));
        if (rect03.getLx() > 0 && rect03.getLy() > 0) {
          rect03 = TRasterImageUtils::convertRasterToWorld(convert(rect03), ri);
          update(ri, rect03, simLevel, false, frameId);
        }
        TRectD rect04 = TRectD(TPointD((double)rect.x1, 0.),
                               TPointD((double)dim.lx, (double)dim.ly));
        if (rect04.getLx() > 0 && rect04.getLy() > 0) {
          rect04 = TRasterImageUtils::convertRasterToWorld(convert(rect04), ri);
          update(ri, rect04, simLevel, false, frameId);
        }
        TUndoManager::manager()->endBlock();
        invalidate();
      } else {
        update(ri, m_selectingRect, simLevel, false, frameId);
        invalidate(m_selectingRect.enlarge(2));
      }
      m_selectingRect.empty();
      TTool::getApplication()->getCurrentXsheet()->notifyXsheetChanged();
      m_selecting = false;
      notifyImageChanged();
    }
  } else if (m_eraseType.getValue() == FREEHANDERASE) {
    if (m_track.isEmpty()) return;
    double pixelSize2 = getPixelSize() * getPixelSize();
    m_track.add(TThickPoint(pos, m_thick), pixelSize2);
    m_track.add(TThickPoint(m_firstPos, m_thick), pixelSize2);
    m_track.filterPoints();
    double error    = (30.0 / 11) * sqrt(pixelSize2);
    TStroke *stroke = m_track.makeStroke(error);
    stroke->setStyle(1);
    m_track.clear();
    TTool::Application *app = TTool::getApplication();
    if (m_multi.getValue())  // stroke multi
    {
      if (m_firstFrameSelected) {
        TFrameId tmp = getCurrentFid();
        if (m_firstStroke && stroke)
          multiAreaEraser(m_firstFrameId, tmp, m_firstStroke, stroke);
        notifyImageChanged();
        if (e.isShiftPressed()) {
          TRectD invalidateRect = m_firstStroke->getBBox();
          delete m_firstStroke;
          m_firstStroke = 0;
          invalidate(invalidateRect.enlarge(2));
          m_firstStroke  = stroke;
          invalidateRect = m_firstStroke->getBBox();
          invalidate(invalidateRect.enlarge(2));
          m_firstFrameId = getFrameId();
        } else {
          if (m_isXsheetCell) {
            app->getCurrentColumn()->setColumnIndex(m_currCell.first);
            app->getCurrentFrame()->setFrame(m_currCell.second);
          } else
            app->getCurrentFrame()->setFid(m_veryFirstFrameId);
          resetMulti();
          delete stroke;
        }
      } else  // primo frame
      {
        m_firstStroke  = stroke;
        m_isXsheetCell = app->getCurrentFrame()->isEditingScene();
        m_currCell     = std::pair<int, int>(getColumnIndex(), getFrame());
        invalidate(m_firstStroke->getBBox().enlarge(2));
      }
    } else  // stroke non multi
    {
      if (!getImage(true)) return;
      TFrameId frameId = getCurrentFid();
      eraseStroke(ri, stroke, m_eraseType.getValue(), m_invertOption.getValue(),
                  /*m_multi.getValue(),*/ m_level, frameId);
      notifyImageChanged();
      if (m_invertOption.getValue())
        invalidate();
      else
        invalidate(stroke->getBBox().enlarge(2));
    }
  }
  m_mousePressed = false;
}
mouseMove()
void FullColorEraserTool::mouseMove (const TPointD & pos, const TMouseEvent & e) override virtual
Reimplemented from TTool.
{
  struct Locals {
    FullColorEraserTool *m_this;
    void setValue(TIntProperty &prop, int value) {
      prop.setValue(value);
      m_this->onPropertyChanged(prop.getName());
      TTool::getApplication()->getCurrentTool()->notifyToolChanged();
    }
    void addValue(TIntProperty &prop, double add) {
      const TIntProperty::Range &range = prop.getRange();
      setValue(prop,
               tcrop<double>(prop.getValue() + add, range.first, range.second));
    }
  } locals = {this};
  switch (e.getModifiersMask()) {
  case TMouseEvent::ALT_KEY: {
    // User wants to alter the maximum brush size
    const TPointD &diff = pos - m_mousePos;
    double add          = (fabs(diff.x) > fabs(diff.y)) ? diff.x : diff.y;
    locals.addValue(m_size, add);
    break;
  }
  default:
    m_brushPos = pos;
    break;
  }
  m_mousePos = pos;
  invalidate();
}
multiAreaEraser()
void FullColorEraserTool::multiAreaEraser (TFrameId & firstFid, TFrameId & lastFid, TStroke * firstStroke, TStroke * lastStroke)
{
  TStroke *first           = new TStroke();
  TStroke *last            = new TStroke();
  *first                   = *firstStroke;
  *last                    = *lastStroke;
  TVectorImageP firstImage = new TVectorImage();
  TVectorImageP lastImage  = new TVectorImage();
  firstImage->addStroke(first);
  lastImage->addStroke(last);
  bool backward = false;
  if (firstFid > lastFid) {
    std::swap(firstFid, lastFid);
    backward = true;
  }
  assert(firstFid <= lastFid);
  std::vector<TFrameId> allFids;
  m_level->getFids(allFids);
  std::vector<TFrameId>::iterator i0 = allFids.begin();
  while (i0 != allFids.end() && *i0 < firstFid) i0++;
  if (i0 == allFids.end()) return;
  std::vector<TFrameId>::iterator i1 = i0;
  while (i1 != allFids.end() && *i1 <= lastFid) i1++;
  assert(i0 < i1);
  std::vector<TFrameId> fids(i0, i1);
  int m = fids.size();
  assert(m > 0);
  TUndoManager::manager()->beginBlock();
  for (int i = 0; i < m; ++i) {
    TFrameId fid = fids[i];
    assert(firstFid <= fid && fid <= lastFid);
    TImageP img = m_level->getFrame(fid, true);
    double t    = m > 1 ? (double)i / (double)(m - 1) : 0.5;
    doMultiEraser(img, backward ? 1 - t : t, fid, firstImage, lastImage);
    m_level->getProperties()->setDirtyFlag(true);
    notifyImageChanged(fid);
  }
  TUndoManager::manager()->endBlock();
}
multiUpdate()
void FullColorEraserTool::multiUpdate (const TRectD firstRect, const TRectD lastRect)
{
  bool backward     = false;
  TFrameId firstFid = m_firstFrameId;
  TFrameId lastFid  = getCurrentFid();
  if (firstFid > lastFid) {
    std::swap(firstFid, lastFid);
    backward = true;
  }
  assert(firstFid <= lastFid);
  std::vector<TFrameId> allFids;
  m_level->getFids(allFids);
  std::vector<TFrameId>::iterator i0 = allFids.begin();
  while (i0 != allFids.end() && *i0 < firstFid) i0++;
  if (i0 == allFids.end()) return;
  std::vector<TFrameId>::iterator i1 = i0;
  while (i1 != allFids.end() && *i1 <= lastFid) i1++;
  assert(i0 < i1);
  std::vector<TFrameId> fids(i0, i1);
  int m = fids.size();
  assert(m > 0);
  TUndoManager::manager()->beginBlock();
  for (int i = 0; i < m; ++i) {
    TFrameId fid = fids[i];
    assert(firstFid <= fid && fid <= lastFid);
    TRasterImageP ri = m_level->getFrame(fid, true);
    assert(ri);
    double t    = m > 1 ? (double)i / (double)(m - 1) : 0.5;
    TRectD rect = interpolateRect(firstRect, lastRect, backward ? 1 - t : t);
    if (m_invertOption.getValue()) {
      TRectD rect01 =
          TRectD(TPointD(-100000., -100000.), TPointD(rect.x0, 100000.));
      update(ri, rect01, m_level, true, fid);
      TRectD rect02 = TRectD(rect.getP01(), TPointD(rect.x1, 100000.));
      update(ri, rect02, m_level, true, fid);
      TRectD rect03 = TRectD(TPointD(rect.x0, -100000.), rect.getP10());
      update(ri, rect03, m_level, true, fid);
      TRectD rect04 =
          TRectD(TPointD(rect.x1, -100000.), TPointD(100000., 100000.));
      update(ri, rect04, m_level, true, fid);
    } else
      update(ri, rect, m_level, true, fid);
    m_level->getProperties()->setDirtyFlag(true);
    notifyImageChanged(fid);
  }
  TUndoManager::manager()->endBlock();
}
onActivate()
void FullColorEraserTool::onActivate () override virtual
Callback invoked whenever the tool activates.
Reimplemented from TTool.
{
  if (m_firstTime) {
    m_firstTime = false;
    m_size.setValue(FullcolorEraseSize);
    m_opacity.setValue(FullcolorEraserOpacity);
    m_hardness.setValue(FullcolorEraseHardness);
    m_eraseType.setValue(::to_wstring(FullcolorEraserType.getValue()));
    m_invertOption.setValue((bool)FullcolorEraserInvert);
    m_multi.setValue((bool)FullcolorEraserRange);
    m_firstTime = false;
  }
  m_brushPad = getBrushPad(m_size.getValue(), m_hardness.getValue() * 0.01);
  // setting m_level in resetMulti() will take care when the tool is switched
  // via shortcut ( i.e. the case skipping onEnter() )
  resetMulti();
  // clear previous polyline when the tool is activated
  m_polyline.clear();
}
onDeactivate()
void FullColorEraserTool::onDeactivate () override virtual
Callback for tool deactivation, includes tool switch.
Reimplemented from TTool.
{
  if (m_mousePressed) leftButtonUp(m_mousePos, m_mouseEvent);
}
onEnter()
void FullColorEraserTool::onEnter () override virtual
Callback for the mouse entering the viewer area.
Reimplemented from TTool.
{
  TRasterImageP ti(getImage(false));
  if (!ti) return;
  TTool::Application *app = TTool::getApplication();
  m_level                 = app->getCurrentLevel()->getLevel()
                ? app->getCurrentLevel()->getSimpleLevel()
                : 0;
}
References TTool::getImage().
onImageChanged()
void FullColorEraserTool::onImageChanged () override virtual
Notifies changes in the image in use.
Reimplemented from TTool.
{
  if (!m_multi.getValue()) return;
  TTool::Application *app = TTool::getApplication();
  TXshSimpleLevel *xshl   = 0;
  if (app->getCurrentLevel()->getLevel())
    xshl = app->getCurrentLevel()->getSimpleLevel();
  if (!xshl || m_level.getPointer() != xshl ||
      (m_selectingRect.isEmpty() && !m_firstStroke))
    resetMulti();
  else if (m_firstFrameId == getCurrentFid())
    m_firstFrameSelected = false;  // nel caso sono passato allo stato 1 e torno
                                   // all'immagine iniziale, torno allo stato
                                   // iniziale
  else {                           // cambio stato.
    m_firstFrameSelected = true;
    if (m_eraseType.getValue() != FREEHANDERASE &&
        m_eraseType.getValue() != POLYLINEERASE) {
      assert(!m_selectingRect.isEmpty());
      m_firstRect = m_selectingRect;
    }
  }
}
References TTool::getCurrentFid(), and TRectT< T >::isEmpty().
onPropertyChanged()
bool FullColorEraserTool::onPropertyChanged (std::string propertyName) override virtual
 Does the tasks associated to changes in \p propertyName and returns \p
true; Does the tasks associated to changes in propertyName and returns true.
Reimplemented from TTool.
{
  FullcolorEraseSize     = m_size.getValue();
  FullcolorEraseHardness = m_hardness.getValue();
  FullcolorEraserOpacity = m_opacity.getValue();
  FullcolorEraserType    = ::to_string(m_eraseType.getValue());
  FullcolorEraserInvert  = (int)m_invertOption.getValue();
  FullcolorEraserRange   = (int)m_multi.getValue();
  if (propertyName == "Hardness:" || propertyName == "Size:") {
    m_brushPad = getBrushPad(m_size.getValue(), m_hardness.getValue() * 0.01);
    TRectD rect(
        m_brushPos - TPointD(FullcolorEraseSize + 2, FullcolorEraseSize + 2),
        m_brushPos + TPointD(FullcolorEraseSize + 2, FullcolorEraseSize + 2));
    invalidate(rect);
  }
  return true;
}
References TTool::invalidate().
resetMulti()
void FullColorEraserTool::resetMulti ()
{
  m_isXsheetCell       = false;
  m_firstFrameSelected = false;
  m_firstRect.empty();
  m_selectingRect.empty();
  TTool::Application *app = TTool::getApplication();
  m_level                 = app->getCurrentLevel()->getLevel()
                ? app->getCurrentLevel()->getSimpleLevel()
                : 0;
  m_firstFrameId = m_veryFirstFrameId = getCurrentFid();
  if (m_firstStroke) {
    delete m_firstStroke;
    m_firstStroke = 0;
  }
}
update()
void FullColorEraserTool::update (const TRasterImageP & ri, TRectD selArea, const TXshSimpleLevelP & level, bool multi = false, const TFrameId & frameId = -1)
{
  if (m_selectingRect.x0 > m_selectingRect.x1) {
    selArea.x1 = m_selectingRect.x0;
    selArea.x0 = m_selectingRect.x1;
  }
  if (m_selectingRect.y0 > m_selectingRect.y1) {
    selArea.y1 = m_selectingRect.y0;
    selArea.y0 = m_selectingRect.y1;
  }
  if (selArea.getLx() < 1 || selArea.getLy() < 1) return;
  TRasterP raster            = ri->getRaster();
  TTileSetFullColor *tileSet = new TTileSetFullColor(raster->getSize());
  tileSet->add(raster, TRasterImageUtils::convertWorldToRaster(selArea, ri));
  TUndo *undo;
  undo       = new RectFullColorUndo(tileSet, selArea, TStroke(),
                               m_eraseType.getValue(), level.getPointer(),
                               m_invertOption.getValue(), frameId);
  TRect rect = TRasterImageUtils::eraseRect(ri, selArea);
  TUndoManager::manager()->add(undo);
}
updateTranslation()
void FullColorEraserTool::updateTranslation () override virtual
Reimplemented from TTool.
{
  m_size.setQStringName(tr("Size:"));
  m_opacity.setQStringName(tr("Opacity:"));
  m_hardness.setQStringName(tr("Hardness:"));
  m_eraseType.setQStringName(tr("Type:"));
  m_eraseType.setItemUIName(NORMALERASE, tr("Normal"));
  m_eraseType.setItemUIName(RECTERASE, tr("Rectangular"));
  m_eraseType.setItemUIName(FREEHANDERASE, tr("Freehand"));
  m_eraseType.setItemUIName(POLYLINEERASE, tr("Polyline"));
  m_invertOption.setQStringName(tr("Invert"));
  m_multi.setQStringName(tr("Frame Range"));
}
The documentation for this class was generated from the following file:
E:/opentoonz/toonz/sources/tnztools/fullcolorerasertool.cpp