opentoonz: TRegion Class Reference
TRegion Class Reference
Classes
class Imp
Public Member Functions
TRectD getBBox () const
bool contains (const TPointD &p) const
bool contains (const TRegion &r) const
bool contains (const TStroke &s, bool mayIntersect=false) const
bool contains (const TEdge &e) const
TRegion * findRegion (const TRegion &r) const
returns the region equivalent to r, 0 if does not exists.
TRegion * getSubregion (UINT index) const
UINT getSubregionCount () const
void deleteSubregion (UINT index)
void addSubregion (TRegion *region)
TEdge * getEdge (UINT index) const
TEdge * getLastEdge () const
UINT getEdgeCount () const
void addEdge (TEdge *e, bool minimizeEdges)
TEdge * popFrontEdge ()
TEdge * popBackEdge ()
void moveSubregionsTo (TRegion *r)
int fill (const TPointD &p, int styleId)
bool selectFill (const TRectD &selectArea, int styleId)
TRegion * getRegion (const TPointD &p)
returns the smallest subregions (including this) containing p
int getStyle () const
void setStyle (int styleId)
void autoFill (int styleId, bool oddLevel)
bool isSubRegionOf (const TRegion &r) const
bool getInternalPoint (TPointD &p)
TRegionProp * getProp ()
void setProp (TRegionProp *prop)
TRegionId getId ()
void invalidateProp ()
void invalidateBBox ()
void print ()
void computeScanlineIntersections (double y, std::vector< double > &intersections) const
int scanlineIntersectionsBefore (double x, double y, bool horiz) const
int leftScanlineIntersections (double x, double y) const
Detailed Description
Constructor & Destructor Documentation
TRegion()
TRegion::TRegion ()
                 : m_imp(new TRegion::Imp()) {
  // m_imp->m_fillStyle->setRegion(this);
}
~TRegion()
TRegion::~TRegion ()
{}
Member Function Documentation
addEdge()
void TRegion::addEdge (TEdge * e, bool minimizeEdges)
{
  if (minimizeEdges &&
      e->m_s->getMaxThickness() > 0.0 &&  // outline strokes ignore this
      !m_imp->m_edge.empty() && m_imp->m_edge.back()->m_index == e->m_index &&
      areAlmostEqual(m_imp->m_edge.back()->m_w1, e->m_w0, 1e-5))
    m_imp->m_edge.back()->m_w1 = e->m_w1;
  else
    m_imp->m_edge.push_back(e);
  m_imp->m_isValidBBox = false;
  // if (e->m_s->isSelfLoop())
  //  assert(m_imp->m_edge.size()==1);
}
addSubregion()
void TRegion::addSubregion (TRegion * region)
{ m_imp->addSubregion(region); }
computeScanlineIntersections()
void TRegion::computeScanlineIntersections (double y, std::vector< double > & intersections) const
{
  m_imp->computeScanlineIntersections(y, intersections);
}
contains() [1/4]
bool TRegion::contains (const TEdge & e) const
{
  for (UINT i = 0; i < m_imp->m_edge.size(); i++)
    if (*m_imp->m_edge[i] == e) return true;
  return false;
}
contains() [2/4]
bool TRegion::contains (const TPointD & p) const
{ return m_imp->contains(p); }
contains() [3/4]
bool TRegion::contains (const TRegion & r) const
{
  return m_imp->contains(*r.m_imp);
}
contains() [4/4]
bool TRegion::contains (const TStroke & s, bool mayIntersect = false) const
{
  return m_imp->contains(s, mayIntersect);
}
deleteSubregion()
void TRegion::deleteSubregion (UINT index)
{
  assert(m_imp->m_includedRegionArray[index]->getSubregionCount() == 0);
  // delete m_imp->m_includedRegionArray[index];
  m_imp->m_includedRegionArray.erase(m_imp->m_includedRegionArray.begin() +
                                     index);
}
fill()
int TRegion::fill (const TPointD & p, int styleId)
{
  UINT i;
  for (i = 0; i < m_imp->m_includedRegionArray.size(); i++)
    if (m_imp->m_includedRegionArray[i]->contains(p))
      return m_imp->m_includedRegionArray[i]->fill(p, styleId);
  int ret = getStyle();
  setStyle(styleId);
  return ret;
}
findRegion()
TRegion * TRegion::findRegion (const TRegion & r) const
returns the region equivalent to r, 0 if does not exists.
{
  if (areAlmostEqual(r.getBBox(), getBBox(), 1e-3)) return (TRegion *)this;
  if (!getBBox().contains(r.getBBox())) return 0;
  TRegion *ret;
  for (UINT i = 0; i < m_imp->m_includedRegionArray.size(); i++)
    if ((ret = m_imp->m_includedRegionArray[i]->findRegion(r)) != 0) return ret;
  return 0;
}
Referenced by TVectorImage::findRegion().
getBBox()
TRectD TRegion::getBBox () const
{ return m_imp->getBBox(); }
getEdge()
TEdge * TRegion::getEdge (UINT index) const
{ return m_imp->m_edge[index]; }
getEdgeCount()
UINT TRegion::getEdgeCount () const
{ return m_imp->m_edge.size(); }
getId()
TRegionId TRegion::getId ()
{
  assert(getEdgeCount() > 0);
  TEdge *edge;
  for (UINT i = 0; i < m_imp->m_edge.size(); i++)
    if (m_imp->m_edge[i]->m_index >= 0) {
      edge = m_imp->m_edge[i];
      return TRegionId(edge->m_s->getId(),
                       (float)((edge->m_w0 + edge->m_w1) * 0.5),
                       edge->m_w0 < edge->m_w1);
    }
  edge = m_imp->m_edge[0];
  return TRegionId(edge->m_s->getId(), (float)((edge->m_w0 + edge->m_w1) * 0.5),
                   edge->m_w0 < edge->m_w1);
}
getInternalPoint()
bool TRegion::getInternalPoint (TPointD & p)
{
  return m_imp->getInternalPoint(p, getBBox().x0, getBBox().x1,
                                 0.5 * (getBBox().y0 + getBBox().y1));
}
getLastEdge()
TEdge * TRegion::getLastEdge () const
{
  if (m_imp->m_edge.empty()) return 0;
  return m_imp->m_edge.back();
}
getProp()
TRegionProp * TRegion::getProp ()
{
  // if(m_working)  buttato m_working
  return m_imp->m_prop;
  /*
int styleId = getStyle();
if(!styleId) return 0;
TColorStyle * style = palette->getStyle(styleId);
if (!style->isRegionStyle() || style->isEnabled() == false)
return 0;
if(!m_imp->m_prop || style != m_imp->m_prop->getColorStyle())
{
delete m_imp->m_prop;
m_imp->m_prop = style->makeRegionProp(this);
}
return m_imp->m_prop;
*/
}
getRegion()
TRegion * TRegion::getRegion (const TPointD & p)
returns the smallest subregions (including this) containing p
{
  for (UINT i = 0; i < m_imp->m_includedRegionArray.size(); i++)
    if (m_imp->m_includedRegionArray[i]->contains(p))
      return m_imp->m_includedRegionArray[i]->getRegion(p);
  return this;
}
Referenced by Stage::Picker::onImage(), and StylePicker::pickStyleId().
getStyle()
int TRegion::getStyle () const
{
  int ret = 0;
  UINT i = 0, j, n = getEdgeCount();
  for (; i < n; i++) {
    int styleId = getEdge(i)->getStyle();
    if (styleId != 0 && ret == 0) {
      // assert(styleId<100);
      ret = styleId;
      if (i > 0)
        for (j = 0; j < i; j++) getEdge(i)->setStyle(ret);
    } else if (styleId != ret)
      getEdge(i)->setStyle(ret);
  }
  return ret;
}
getSubregion()
TRegion * TRegion::getSubregion (UINT index) const
{
  return m_imp->m_includedRegionArray[index];
}
getSubregionCount()
UINT TRegion::getSubregionCount () const
{
  return m_imp->m_includedRegionArray.size();
}
invalidateBBox()
void TRegion::invalidateBBox ()
{
  m_imp->invalidateBBox();
  for (UINT i = 0; i < m_imp->m_includedRegionArray.size(); i++)
    m_imp->m_includedRegionArray[i]->invalidateBBox();
}
invalidateProp()
void TRegion::invalidateProp ()
{
  if (m_imp->m_prop) m_imp->m_prop->notifyRegionChange();
}
isSubRegionOf()
bool TRegion::isSubRegionOf (const TRegion & r) const
{
  return m_imp->isSubRegionOf(*r.m_imp);
}
leftScanlineIntersections()
int TRegion::leftScanlineIntersections (double x, double y) const inline
{
    return scanlineIntersectionsBefore(x, y, true);
  }
moveSubregionsTo()
void TRegion::moveSubregionsTo (TRegion * r)
{
  while (m_imp->m_includedRegionArray.size()) {
    r->m_imp->m_includedRegionArray.push_back(
        m_imp->m_includedRegionArray.back());
    m_imp->m_includedRegionArray.pop_back();
  }
}
popBackEdge()
TEdge * TRegion::popBackEdge ()
{
  TEdge *ret;
  if (m_imp->m_edge.empty()) return 0;
  ret = m_imp->m_edge.back();
  m_imp->m_edge.pop_back();
  return ret;
}
popFrontEdge()
TEdge * TRegion::popFrontEdge ()
{
  TEdge *ret;
  if (m_imp->m_edge.empty()) return 0;
  ret = m_imp->m_edge.front();
  m_imp->m_edge.erase(m_imp->m_edge.begin());
  return ret;
}
print()
void TRegion::print ()
                    {
  std::cout << "\nNum edges: " << getEdgeCount() << std::endl;
  for (UINT i = 0; i < getEdgeCount(); i++) {
    std::cout << "\nEdge #" << i;
    std::cout << ":P0(" << getEdge(i)->m_s->getChunk(0)->getP0().x << ","
              << getEdge(i)->m_s->getChunk(0)->getP0().y << ")";
    std::cout << ":P2("
              << getEdge(i)
                     ->m_s->getChunk(getEdge(i)->m_s->getChunkCount() - 1)
                     ->getP2()
                     .x
              << ","
              << getEdge(i)
                     ->m_s->getChunk(getEdge(i)->m_s->getChunkCount() - 1)
                     ->getP2()
                     .y
              << ")";
    std::cout << std::endl;
  }
  if (m_imp->m_includedRegionArray.size()) {
    std::cout << "***** questa regione contiene:" << std::endl;
    for (UINT i = 0; i < m_imp->m_includedRegionArray.size(); i++)
      m_imp->m_includedRegionArray[i]->print();
    std::cout << "***** fine" << std::endl;
  }
}
scanlineIntersectionsBefore()
int TRegion::scanlineIntersectionsBefore (double x, double y, bool horiz) const
{
  static double TPointD::*const dir[2] = {&TPointD::x, &TPointD::y};
  return m_imp->leftScanlineIntersections(TPointD(x, y), dir[!horizontal],
                                          dir[horizontal]);
}
selectFill()
bool TRegion::selectFill (const TRectD & selectArea, int styleId)
{
  bool hitSomeRegions = false;
  if (selArea.contains(getBBox())) {
    hitSomeRegions = true;
    setStyle(styleId);
  }
  int regNum = m_imp->m_includedRegionArray.size();
  for (int i = 0; i < regNum; i++)
    hitSomeRegions |=
        m_imp->m_includedRegionArray[i]->selectFill(selArea, styleId);
  return hitSomeRegions;
}
setProp()
void TRegion::setProp (TRegionProp * prop)
{
  assert(prop);
  delete m_imp->m_prop;
  m_imp->m_prop = prop;
}
setStyle()
void TRegion::setStyle (int styleId)
{
  for (UINT i = 0; i < getEdgeCount(); i++) getEdge(i)->setStyle(colorStyle);
  /*
if (!colorStyle || (colorStyle && colorStyle->isFillStyle()))
{
for (UINT i=0; i<getEdgeCount(); i++)
getEdge(i)->setColorStyle(colorStyle);
delete m_imp->m_prop;
m_imp->m_prop = 0;
}
*/
}
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/tregion.h
E:/opentoonz/toonz/sources/common/tvectorimage/tregion.cpp