opentoonz: TOutputProperties Class Reference
TOutputProperties Class Reference
#include <toutputproperties.h>
Public Types
enum { AllLevels , SelectedOnly , AnimatedOnly }
enum MaxTileSizeValues { LargeVal = 50 , MediumVal = 10 , SmallVal = 2 }
Public Member Functions
TOutputProperties ()
~TOutputProperties ()
TOutputProperties (const TOutputProperties &src)
TOutputProperties & operator= (const TOutputProperties &src)
TFilePath getPath () const
void setPath (const TFilePath &fp)
void setWhichLevels (int state)
int getWhichLevels () const
int getOffset () const
void setOffset (int off)
bool getRange (int &r0, int &r1, int &step) const
void setRange (int r0, int r1, int step)
void setFrameRate (double)
double getFrameRate () const
const TRenderSettings & getRenderSettings () const
void setRenderSettings (const TRenderSettings &renderSettings)
TPropertyGroup * getFileFormatProperties (std::string ext)
void getFileFormatPropertiesExtensions (std::vector< std::string > &v) const
void setMultimediaRendering (int mode)
Sets the rendering behaviour to 'Multimedia'.
int getMultimediaRendering () const
void setMaxTileSizeIndex (int idx)
int getMaxTileSizeIndex () const
void setThreadIndex (int idx)
int getThreadIndex () const
bool isSubcameraPreview () const
void setSubcameraPreview (bool enabled)
BoardSettings * getBoardSettings () const
Detailed Description
The TOutputProperties class provides a container for output properties and gives all methods to access to these information.
The class contains all features necessaries to compute output and provides a collection of functions that return the various feature, and enable manipulation of these.
A path getPath() is used to manipulate output name and directory, path can be changed using the setPath().
The getRange() function tells whether is set a range in output, if it's so provides first frame, last frame, and step; this element can be changed using setRange().
The getFrameRate() function return output frame rate, it can be set by setFrameRate().
The getWhichLevels() function return a value is used to characterize which levels are in output:
If value is TOutputProperties::AllLevels all levels are computed in output.
If value is TOutputProperties::SelectedOnly only selectecd levels are computed in output.
If value is TOutputProperties::AnimatedOnly only animated levels are computed in output.
It can be set by setWhichLevels().
The getFileFormatProperties(string ext) function return file of format ext properties TPropertyGroup. It's possibile set different format and have appropriate properties.
The getRenderSettings() function return render settings TRenderSettings, it can be change using setRenderSettings().
Member Enumeration Documentation
anonymous enum
anonymous enum
This enum type is used to characterize which levels are in output. Can set in output to all levels, only selectecd levels or only animated levels.
See also
getWhichLevels(), setWhichLevels()
{ AllLevels, SelectedOnly, AnimatedOnly };
MaxTileSizeValues
enum TOutputProperties::MaxTileSizeValues
{ LargeVal = 50, MediumVal = 10, SmallVal = 2 };
Constructor & Destructor Documentation
TOutputProperties() [1/2]
TOutputProperties::TOutputProperties ()
Constructs TOutputProperties with default value.
    : m_path(TFilePath("+outputs") + ".tif")
    , m_renderSettings()
    , m_frameRate(24)
    , m_from(0)
    , m_to(-1)
    , m_offset(0)
    , m_step(1)
    , m_whichLevels(false)
    , m_multimediaRendering(0)
    , m_maxTileSizeIndex(0)
    , m_threadIndex(2)
    , m_subcameraPreview(false)
    , m_boardSettings(new BoardSettings()) {
  m_renderSettings = new TRenderSettings();
}
~TOutputProperties()
TOutputProperties::~TOutputProperties ()
Destroys the TOutputProperties object.
{
  delete m_renderSettings;
  std::for_each(m_formatProperties.begin(), m_formatProperties.end(),
                ::deleteValue);
}
TOutputProperties() [2/2]
TOutputProperties::TOutputProperties (const TOutputProperties & src)
Constructs a TOutputProperties object that is a copy of the TOutputProperties object src.
See also
operator=()
    : m_path(src.m_path)
    , m_formatProperties(src.m_formatProperties)
    , m_renderSettings(new TRenderSettings(*src.m_renderSettings))
    , m_frameRate(src.m_frameRate)
    , m_from(src.m_from)
    , m_to(src.m_to)
    , m_whichLevels(src.m_whichLevels)
    , m_offset(src.m_offset)
    , m_step(src.m_step)
    , m_multimediaRendering(src.m_multimediaRendering)
    , m_maxTileSizeIndex(src.m_maxTileSizeIndex)
    , m_threadIndex(src.m_threadIndex)
    , m_subcameraPreview(src.m_subcameraPreview)
    , m_boardSettings(new BoardSettings(*src.m_boardSettings)) {
  std::map<std::string, TPropertyGroup *>::iterator ft,
      fEnd = m_formatProperties.end();
  for (ft = m_formatProperties.begin(); ft != fEnd; ++ft) {
    if (ft->second) ft->second = ft->second->clone();
  }
}
Member Function Documentation
getBoardSettings()
BoardSettings * TOutputProperties::getBoardSettings () const inline
{ return m_boardSettings; }
getFileFormatProperties()
TPropertyGroup * TOutputProperties::getFileFormatProperties (std::string ext)
Return TPropertyGroup, file format ext (Extension) properties. If extension there isn't is created.
{
  std::map<std::string, TPropertyGroup *>::const_iterator it;
  it = m_formatProperties.find(ext);
  if (it == m_formatProperties.end()) {
    TPropertyGroup *ret     = Tiio::makeWriterProperties(ext);
    m_formatProperties[ext] = ret;
    return ret;
  } else {
    // Try to merge settings instead of overriding them
    TPropertyGroup *ret = Tiio::makeWriterProperties(ext);
    ret->setProperties(it->second);
    m_formatProperties[ext] = ret;
    return ret;
  }
}
Referenced by IoCmd::exportLevel(), TSceneProperties::loadData(), RenderCommand::multimediaRender(), OutputSettingsPopup::onAddPresetButtonPressed(), and OutputSettingsPopup::openSettingsPopup().
getFileFormatPropertiesExtensions()
void TOutputProperties::getFileFormatPropertiesExtensions (std::vector< std::string > & v) const
Insert in v all extension in format properties of output settings.
{
  v.reserve(m_formatProperties.size());
  std::map<std::string, TPropertyGroup *>::const_iterator it;
  for (it = m_formatProperties.begin(); it != m_formatProperties.end(); ++it)
    v.push_back(it->first);
}
Referenced by OutputSettingsPopup::onAddPresetButtonPressed().
getFrameRate()
double TOutputProperties::getFrameRate () const inline
Return output frame rate.
See also
setFrameRate()
{ return m_frameRate; }
Referenced by TSceneProperties::loadData(), OnRenderCompleted::onDeliver(), TXshSoundLevel::setScene(), TXshSoundColumn::setXsheet(), OutputSettingsPopup::updateField(), and ToonzScene::updateSoundColumnFrameRate().
getMaxTileSizeIndex()
int TOutputProperties::getMaxTileSizeIndex () const inline
{ return m_maxTileSizeIndex; }
getMultimediaRendering()
int TOutputProperties::getMultimediaRendering () const inline
{ return m_multimediaRendering; }
getOffset()
int TOutputProperties::getOffset () const inline
Return output offset.
{ return m_offset; }
getPath()
TFilePath TOutputProperties::getPath () const
Return output path, name and directory where output file will be save.
See also
setPath()
{ return m_path; }
Referenced by OutputSettingsPopup::onFormatChanged(), TSceneProperties::onInitialize(), OutputSettingsPopup::onNameChanged(), OutputSettingsPopup::onPathChanged(), OutputSettingsPopup::openSettingsPopup(), and OutputSettingsPopup::updateField().
getRange()
bool TOutputProperties::getRange (int & r0, int & r1, int & step) const
Return true if frame start <= than frame end. Set step to output step, r0 to first frame, r1 to last frame.
See also
setRange()
{
  step = m_step;
  if (m_from > m_to) {
    r0 = 0;
    r1 = -1;
    return false;
  } else {
    r0 = m_from;
    r1 = m_to;
    return true;
  }
}
Referenced by TSceneProperties::loadData(), OnRenderCompleted::onDeliver(), and OutputSettingsPopup::updateField().
getRenderSettings()
const TRenderSettings & TOutputProperties::getRenderSettings () const inline
Return const TRenderSettings.
See also
setRenderSettings()
{ return *m_renderSettings; }
Referenced by RenderCommand::multimediaRender(), OutputSettingsPopup::onChannelWidthChanged(), OnRenderCompleted::onDeliver(), OutputSettingsPopup::onDominantFieldChanged(), OutputSettingsPopup::onGammaFldEditFinished(), OutputSettingsPopup::onResampleChanged(), OutputSettingsPopup::onStretchFldEditFinished(), and OutputSettingsPopup::updateField().
getThreadIndex()
int TOutputProperties::getThreadIndex () const inline
{ return m_threadIndex; }
getWhichLevels()
int TOutputProperties::getWhichLevels () const inline
Return which levels are in output.
See also
setWhichLevels()
{ return m_whichLevels; }
isSubcameraPreview()
bool TOutputProperties::isSubcameraPreview () const inline
{ return m_subcameraPreview; }
operator=()
TOutputProperties & TOutputProperties::operator= (const TOutputProperties & src)
Assign the src object to this TOutputProperties object.
{
  m_path        = src.m_path;
  m_from        = src.m_from;
  m_to          = src.m_to;
  m_frameRate   = src.m_frameRate;
  m_whichLevels = src.m_whichLevels;
  m_offset      = src.m_offset;
  m_step        = src.m_step;
  m_multimediaRendering = src.m_multimediaRendering;
  m_maxTileSizeIndex    = src.m_maxTileSizeIndex;
  m_threadIndex         = src.m_threadIndex;
  m_subcameraPreview    = src.m_subcameraPreview;
  delete m_renderSettings;
  m_renderSettings = new TRenderSettings(*src.m_renderSettings);
  std::for_each(m_formatProperties.begin(), m_formatProperties.end(),
                ::deleteValue);
  std::map<std::string, TPropertyGroup *>::const_iterator sft,
      sfEnd = src.m_formatProperties.end();
  for (sft = src.m_formatProperties.begin(); sft != sfEnd; ++sft)
    m_formatProperties[sft->first] = sft->second->clone();
  delete m_boardSettings;
  m_boardSettings = new BoardSettings(*src.m_boardSettings);
  return *this;
}
setFrameRate()
void TOutputProperties::setFrameRate (double fps)
Set output frame rate.
See also
getFrameRate()
{ m_frameRate = fps; }
Referenced by TSceneProperties::loadData().
setMaxTileSizeIndex()
void TOutputProperties::setMaxTileSizeIndex (int idx) inline
Sets the granularity of raster allocations for rendering processes. The specified value refers to an index associated with const values, spanning from 0 (no bound, ie giant rasters are allowed) to 3 (highly restrictive, only small rasters are allocated). The value should be high for complex scenes.
{ m_maxTileSizeIndex = idx; }
Referenced by TSceneProperties::loadData().
setMultimediaRendering()
void TOutputProperties::setMultimediaRendering (int mode) inline
Sets the rendering behaviour to 'Multimedia'.
{ m_multimediaRendering = mode; }
Referenced by TSceneProperties::loadData().
setOffset()
void TOutputProperties::setOffset (int off)
Set output offset to off.
{ m_offset = off; }
Referenced by TSceneProperties::loadData().
setPath()
void TOutputProperties::setPath (const TFilePath & fp)
Set output path to fp.
See also
getPath()
{ m_path = fp; }
Referenced by TSceneProperties::loadData(), OutputSettingsPopup::onFormatChanged(), TSceneProperties::onInitialize(), OutputSettingsPopup::onNameChanged(), and OutputSettingsPopup::onPathChanged().
setRange()
void TOutputProperties::setRange (int r0, int r1, int step)
Set first frame to r0, last frame to r1, step to step.
See also
getRange()
{
  assert(0 <= r0 && r0 <= r1 || r0 == 0 && r1 == -1);
  m_from = r0;
  m_to   = r1;
  m_step = step;
}
Referenced by TSceneProperties::loadData().
setRenderSettings()
void TOutputProperties::setRenderSettings (const TRenderSettings & renderSettings)
Set render settings to renderSettings.
See also
getRenderSettings()
{
  assert(renderSettings.m_bpp == 32 || renderSettings.m_bpp == 64);
  assert(renderSettings.m_gamma > 0);
  assert(renderSettings.m_quality == TRenderSettings::StandardResampleQuality ||
         renderSettings.m_quality == TRenderSettings::ImprovedResampleQuality ||
         renderSettings.m_quality == TRenderSettings::HighResampleQuality ||
         renderSettings.m_quality ==
             TRenderSettings::Triangle_FilterResampleQuality ||
         renderSettings.m_quality ==
             TRenderSettings::Mitchell_FilterResampleQuality ||
         renderSettings.m_quality ==
             TRenderSettings::Cubic5_FilterResampleQuality ||
         renderSettings.m_quality ==
             TRenderSettings::Cubic75_FilterResampleQuality ||
         renderSettings.m_quality ==
             TRenderSettings::Cubic1_FilterResampleQuality ||
         renderSettings.m_quality ==
             TRenderSettings::Hann2_FilterResampleQuality ||
         renderSettings.m_quality ==
             TRenderSettings::Hann3_FilterResampleQuality ||
         renderSettings.m_quality ==
             TRenderSettings::Hamming2_FilterResampleQuality ||
         renderSettings.m_quality ==
             TRenderSettings::Hamming3_FilterResampleQuality ||
         renderSettings.m_quality ==
             TRenderSettings::Lanczos2_FilterResampleQuality ||
         renderSettings.m_quality ==
             TRenderSettings::Lanczos3_FilterResampleQuality ||
         renderSettings.m_quality ==
             TRenderSettings::Gauss_FilterResampleQuality ||
         renderSettings.m_quality ==
             TRenderSettings::ClosestPixel_FilterResampleQuality ||
         renderSettings.m_quality ==
             TRenderSettings::Bilinear_FilterResampleQuality);
  *m_renderSettings = renderSettings;
}
References TRenderSettings::HighResampleQuality, TRenderSettings::ImprovedResampleQuality, TRenderSettings::m_bpp, TRenderSettings::m_gamma, TRenderSettings::m_quality, and TRenderSettings::StandardResampleQuality.
Referenced by TSceneProperties::loadData(), OutputSettingsPopup::onChannelWidthChanged(), OutputSettingsPopup::onDominantFieldChanged(), OutputSettingsPopup::onGammaFldEditFinished(), OutputSettingsPopup::onResampleChanged(), and OutputSettingsPopup::onStretchFldEditFinished().
setSubcameraPreview()
void TOutputProperties::setSubcameraPreview (bool enabled) inline
{ m_subcameraPreview = enabled; }
setThreadIndex()
void TOutputProperties::setThreadIndex (int idx) inline
Sets index for a combo selection of threads running for rendering processes. Possible values are: 0 (1 thread, safe mode), 1 (half), 2 (max - number of machine's CPU).
{ m_threadIndex = idx; }
Referenced by TSceneProperties::loadData().
setWhichLevels()
void TOutputProperties::setWhichLevels (int state) inline
Set which levels are in output to state. State can be:
TOutputProperties::AllLevels.
TOutputProperties::SelectedOnly.
TOutputProperties::AnimatedOnly.
See also
getWhichLevels()
{ m_whichLevels = state; }
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/toutputproperties.h
E:/opentoonz/toonz/sources/toonzlib/outputproperties.cpp