opentoonz: Stage::Picker Class Reference
Stage::Picker Class Reference final
Public Member Functions
Picker (const TAffine &viewAff, const TPointD &p, const ImagePainter::VisualSettings &vs, int devPixRatio=1)
void setMinimumDistance (double d)
void onImage (const Stage::Player &data) override
The visitation function.
void onRasterImage (TRasterImage *ri, const Stage::Player &data) override
void beginMask () override
void endMask () override
void enableMask () override
void disableMask () override
int getColumnIndex () const
void getColumnIndexes (std::vector< int > &indexes) const
int getRow () const
void setCurrentColumnIndex (int index)
Public Member Functions inherited from Stage::Visitor
Visitor (const ImagePainter::VisualSettings &vs)
virtual void onImage (const Player &player)=0
The visitation function.
virtual void onRasterImage (TRasterImage *ri, const Stage::Player &data)=0
virtual void enableMask ()=0
virtual void disableMask ()=0
virtual void beginMask ()=0
virtual void endMask ()=0
Additional Inherited Members
Public Attributes inherited from Stage::Visitor
const ImagePainter::VisualSettings & m_vs
Generic painting visual options.
Detailed Description
Constructor & Destructor Documentation
Picker()
Picker::Picker (const TAffine & viewAff, const TPointD & p, const ImagePainter::VisualSettings & vs, int devPixRatio = 1)
    : Visitor(vs)
    , m_viewAff(viewAff)
    , m_point(point)
    , m_columnIndexes()
    , m_minDist2(25.0)
    , m_devPixRatio(devPixRatio) {}
Member Function Documentation
beginMask()
void Picker::beginMask () override virtual
Implements Stage::Visitor.
{}
disableMask()
void Picker::disableMask () override virtual
Implements Stage::Visitor.
{}
enableMask()
void Picker::enableMask () override virtual
Implements Stage::Visitor.
{}
endMask()
void Picker::endMask () override virtual
Implements Stage::Visitor.
{}
getColumnIndex()
int Picker::getColumnIndex () const
{
  if (m_columnIndexes.empty())
    return -1;
  else
    return m_columnIndexes.back();
}
getColumnIndexes()
void Picker::getColumnIndexes (std::vector< int > & indexes) const
{
  indexes = m_columnIndexes;
}
getRow()
int Picker::getRow () const
{
  if (m_rows.empty())
    return -1;
  else
    return m_rows.back();
}
onImage()
void Picker::onImage (const Stage::Player & player) override virtual
The visitation function.
Implements Stage::Visitor.
{
  // if m_currentColumnIndex is other than the default value (-1),
  // then pick only the current column.
  if (m_currentColumnIndex != -1 &&
      m_currentColumnIndex != player.m_ancestorColumnIndex)
    return;
  bool picked   = false;
  TAffine aff   = m_viewAff * player.m_placement;
  TPointD point = aff.inv() * m_point;
  const TImageP &img = player.image();
  if (TVectorImageP vi = img) {
    double w         = 0;
    UINT strokeIndex = 0;
    double dist2     = 0;
    TRegion *r       = vi->getRegion(point);
    int styleId      = 0;
    if (r) styleId = r->getStyle();
    if (styleId != 0)
      picked = true;
    else if (vi->getNearestStroke(point, w, strokeIndex, dist2)) {
      dist2 *= aff.det();
      TStroke *stroke        = vi->getStroke(strokeIndex);
      TThickPoint thickPoint = stroke->getThickPoint(w);
      double len2            = thickPoint.thick * thickPoint.thick * aff.det();
      double checkDist       = std::max(m_minDist2, len2);
      if (dist2 < checkDist) picked = true;
    }
  } else if (TRasterImageP ri = img) {
    TRaster32P ras = ri->getRaster();
    if (!ras) return;
    ras->lock();
    TPointD pp = player.m_dpiAff.inv() * point + ras->getCenterD();
    TPoint p(tround(pp.x), tround(pp.y));
    if (!ras->getBounds().contains(p)) return;
    TPixel32 *pix = ras->pixels(p.y);
    if (pix[p.x].m != 0) picked = true;
    TAffine aff2 = (aff * player.m_dpiAff).inv();
    TPointD pa(p.x, p.y);
    TPointD dx = aff2 * (m_point + TPointD(3, 0)) - aff2 * m_point;
    TPointD dy = aff2 * (m_point + TPointD(0, 3)) - aff2 * m_point;
    double rx  = dx.x * dx.x + dx.y * dx.y;
    double ry  = dy.x * dy.x + dy.y * dy.y;
    int radius = tround(sqrt(rx > ry ? rx : ry));
    TRect rect = TRect(p.x - radius, p.y - radius, p.x + radius, p.y + radius) *
                 ras->getBounds();
    for (int y = rect.y0; !picked && y <= rect.y1; y++) {
      pix = ras->pixels(y);
      for (int x = rect.x0; !picked && x <= rect.x1; x++)
        if (pix[x].m != 0) picked = true;
    }
    ras->unlock();
  } else if (TToonzImageP ti = img) {
    TRasterCM32P ras = ti->getRaster();
    if (!ras) return;
    ras->lock();
    TPointD pp = player.m_dpiAff.inv() * point + ras->getCenterD();
    TPoint p(tround(pp.x), tround(pp.y));
    if (!ras->getBounds().contains(p)) return;
    TPixelCM32 *pix = ras->pixels(p.y) + p.x;
    if (!pix->isPurePaint() || pix->getPaint() != 0) picked = true;
    ras->unlock();
  }
  if (picked) {
    int columnIndex = player.m_ancestorColumnIndex;
    if (m_columnIndexes.empty() || m_columnIndexes.back() != columnIndex)
      m_columnIndexes.push_back(columnIndex);
    int row = player.m_frame;
    if (m_rows.empty() || m_rows.back() != row) m_rows.push_back(row);
  }
}
References TRegion::getRegion(), TStroke::getThickPoint(), Stage::Player::image(), TAffine::inv(), Stage::Player::m_ancestorColumnIndex, Stage::Player::m_dpiAff, Stage::Player::m_frame, Stage::Player::m_placement, and TRectT< T >::x0.
onRasterImage()
void Stage::Picker::onRasterImage (TRasterImage * ri, const Stage::Player & data) inline override virtual
Implements Stage::Visitor.
{};
setCurrentColumnIndex()
void Stage::Picker::setCurrentColumnIndex (int index) inline
{ m_currentColumnIndex = index; }
setMinimumDistance()
void Picker::setMinimumDistance (double d)
{
  m_minDist2 = (double)(m_devPixRatio * m_devPixRatio) * d * d;
}
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/toonz/stagevisitor.h
E:/opentoonz/toonz/sources/toonzlib/stagevisitor.cpp