opentoonz: CtrlFarmTask Class Reference
CtrlFarmTask Class Reference final
Public Member Functions
CtrlFarmTask (const QString &id, const QString &name, const QString &cmdline, const QString &user, const QString &host, int stepCount, int priority)
CtrlFarmTask (const CtrlFarmTask &rhs)
void loadData (TIStream &is) override
void saveData (TOStream &os) override
const TPersistDeclaration * getDeclaration () const override
Public Member Functions inherited from TFarmTask
TFarmTask (const QString &name="")
TFarmTask (const QString &id, const QString &name, const QString &cmdline, const QString &user, const QString &host, int stepCount, int priority)
TFarmTask (const QString &id, const QString &name, bool composerTask, const QString &user, const QString &host, int stepCount, int priority, const TFilePath &taskFilePath, const TFilePath &outputPath, int from, int to, int step, int shrink, int multimedia, int chunksize, int threadsIndex, int maxTileSizeIndex, OverwriteBehavior overwrite, bool onlyvisible)
TFarmTask (const TFarmTask &)
TFarmTask & operator= (const TFarmTask &)
bool operator== (const TFarmTask &task)
bool operator!= (const TFarmTask &task)
virtual int getTaskCount () const
virtual TFarmTask * getTask (int index)
QString getCommandLine (bool isFarmTask=false) const
void parseCommandLine (QString commandLine)
void loadData (TIStream &is) override
void saveData (TOStream &os) override
const TPersistDeclaration * getDeclaration () const override
Public Member Functions inherited from TPersist
virtual void loadData (TIStream &is)=0
virtual void saveData (TOStream &os)=0
std::string getStreamTag () const
virtual const TPersistDeclaration * getDeclaration () const =0
Public Attributes
QString m_serverId
vector< QString > m_subTasks
bool m_toBeDeleted
int m_failureCount
vector< QString > m_failedOnServers
Public Attributes inherited from TFarmTask
Id m_id
Internal task identifier.
Id m_parentId
Task id of the parent task (if any)
bool m_isComposerTask
QString m_name
User-readable name.
TFilePath m_taskFilePath
Path of the input file affected by the task.
TFilePath m_outputPath
Path of the task's output file.
QString m_callerMachineName
Name of the... caller (submitter?) machine.
int m_priority
Priority value used for scheduling order.
QString m_user
User who submitted the task.
QString m_hostName
Machine on which the task was submitted.
TaskState m_status
The task's status (completed, work in progress... etc)
QString m_server
Server node (name) the task was supplied to.
QDateTime m_submissionDate
QDateTime m_startDate
QDateTime m_completionDate
int m_successfullSteps
int m_failedSteps
int m_stepCount
int m_from
int m_to
int m_step
int m_shrink
Range data.
int m_chunkSize
Sub-tasks size.
int m_multimedia
int m_threadsIndex
int m_maxTileSizeIndex
OverwriteBehavior m_overwrite
bool m_onlyVisible
TFarmPlatform m_platform
Dependencies * m_dependencies
Additional Inherited Members
Public Types inherited from TFarmTask
typedef QString Id
Public Types inherited from TPersist
typedef TPersist * CreateProc()
Static Public Member Functions inherited from TPersist
static void declare (CreateProc *)
static TPersist * create (const std::string &name)
Detailed Description
Constructor & Destructor Documentation
CtrlFarmTask() [1/3]
CtrlFarmTask::CtrlFarmTask () inline
: m_toBeDeleted(false), m_failureCount(0) {}
CtrlFarmTask() [2/3]
CtrlFarmTask::CtrlFarmTask (const QString & id, const QString & name, const QString & cmdline, const QString & user, const QString & host, int stepCount, int priority) inline
      : TFarmTask(id, name, cmdline, user, host, stepCount, priority)
      , m_toBeDeleted(false)
      , m_failureCount(0) {
    m_id     = id;
    m_status = Waiting;
  }
CtrlFarmTask() [3/3]
CtrlFarmTask::CtrlFarmTask (const CtrlFarmTask & rhs) inline
                                        : TFarmTask(rhs) {
    m_serverId    = rhs.m_serverId;
    m_subTasks    = rhs.m_subTasks;
    m_toBeDeleted = rhs.m_toBeDeleted;
  }
Member Function Documentation
getDeclaration()
const TPersistDeclaration * CtrlFarmTask::getDeclaration () const override virtual
      This pure virtual method is used to define a global pointer to the
object. This method is overridden with the macro PERSIST_DECLARATION(T).
For example:
class DVAPI TStageObjectTree final : public TPersist {
PERSIST_DECLARATION(TStageObjectTree)
public:
...
Reimplemented from TFarmTask.
{
  return &Declaration;
}
loadData()
void CtrlFarmTask::loadData (TIStream & is) override virtual
 This is a pure virtual function and must be overridden with a method
that implements the object loading from a stream (i.e take the object's features from a formatted data stream). For example the TStageObject class use his implementation to take the values of the parameters that characterizes a stage object as name, coordinates, etc... from a file. is is an input file stream
Reimplemented from TFarmTask.
{
  is >> m_name;
  QString cmdline;
  is >> cmdline;
  parseCommandLine(cmdline);
  is >> m_priority;
  is >> m_user;
  is >> m_hostName;
  is >> m_id;
  is >> m_parentId;
  int status;
  is >> status;
  m_status = (TaskState)status;
  is >> m_server;
  QString dateStr;
  is >> dateStr;
  m_submissionDate = QDateTime::fromString(dateStr);
  is >> dateStr;
  m_startDate = QDateTime::fromString(dateStr);
  is >> dateStr;
  m_completionDate = QDateTime::fromString(dateStr);
  is >> m_successfullSteps;
  is >> m_failedSteps;
  is >> m_stepCount;
  is >> m_serverId;
  string tagName;
  while (is.openChild(tagName)) {
    if (tagName == "platform") {
      int plat;
      is >> plat;
      switch (plat) {
      case NoPlatform:
        m_platform = NoPlatform;
        break;
      case Windows:
        m_platform = Windows;
        break;
      case Irix:
        m_platform = Irix;
        break;
      case Linux:
        m_platform = Linux;
        break;
      }
    } else if (tagName == "dependencies") {
      int depCount = 0;
      is >> depCount;
      if (depCount > 0) m_dependencies = new Dependencies();
      while (depCount > 0) {
        TFarmTask::Id id;
        is >> id;
        m_dependencies->add(id);
        depCount--;
      }
    }
    is.closeChild();
  }
}
References TIStream::closeChild(), TFarmTask::m_hostName, TFarmTask::m_id, TFarmTask::m_name, TFarmTask::m_parentId, TFarmTask::m_priority, TFarmTask::m_server, TFarmTask::m_status, TFarmTask::m_user, and TIStream::openChild().
saveData()
void CtrlFarmTask::saveData (TOStream & os) override virtual
 This is a pure virtual function and must be overridden with a method
that implements the object saving to a data stream (i.e put the object's features on a formatted data stream). For example the TStageObject class use his implementation to save the values of the parameters that characterizes a stage object as name, coordinates, etc... on a file os is an output file stream.
Reimplemented from TFarmTask.
{
  os << m_name;
  os << getCommandLine();
  os << m_priority;
  os << m_user;
  os << m_hostName;
  os << m_id;
  os << m_parentId;
  os << (int)m_status;
  os << m_server;
  os << m_submissionDate.toString();
  os << m_startDate.toString();
  os << m_completionDate.toString();
  os << m_successfullSteps;
  os << m_failedSteps;
  os << m_stepCount;
  os << m_serverId;
  os.openChild("platform");
  os << m_platform;
  os.closeChild();
  os.openChild("dependencies");
  if (m_dependencies) {
    int depCount = m_dependencies->getTaskCount();
    os << depCount;
    int i = 0;
    while (i < depCount) {
      TFarmTask::Id id = m_dependencies->getTaskId(i++);
      os << id;
    }
  } else
    os << 0;
  os.closeChild();
}
References TOStream::closeChild(), TFarmTask::m_hostName, TFarmTask::m_id, TFarmTask::m_name, TFarmTask::m_parentId, TFarmTask::m_priority, TFarmTask::m_server, TFarmTask::m_status, TFarmTask::m_user, and TOStream::openChild().
Member Data Documentation
m_failedOnServers
vector<QString> CtrlFarmTask::m_failedOnServers
m_failureCount
int CtrlFarmTask::m_failureCount
m_serverId
QString CtrlFarmTask::m_serverId
m_subTasks
vector<QString> CtrlFarmTask::m_subTasks
m_toBeDeleted
bool CtrlFarmTask::m_toBeDeleted
The documentation for this class was generated from the following file:
E:/opentoonz/toonz/sources/toonzfarm/tfarmcontroller/tfarmcontroller.cpp