opentoonz: DVGui::IntLineEdit Class Reference
DVGui::IntLineEdit Class Reference
The IntLineEdit class provides an object to manage an integer line edit.
#include <intfield.h>
Public Member Functions
IntLineEdit (QWidget *parent=0, int value=1, int minValue=(-(std::numeric_limits< int >::max)()), int maxValue=((std::numeric_limits< int >::max)()), int showedDigits=0)
void setValue (int value)
int getValue ()
void setRange (int minValue, int maxValue)
void setBottomRange (int minValue)
void setTopRange (int maxValue)
void getRange (int &minValue, int &maxValue)
void setLineEditBackgroundColor (QColor color)
Public Member Functions inherited from DVGui::LineEdit
LineEdit (QWidget *parent=0, bool forbiddenSpecialChars=false)
LineEdit (const QString &contents, QWidget *parent=0, bool forbiddenSpecialChars=false)
bool isReturnPressed () const
bool getMouseDragEditing ()
void setMouseDragEditing (bool status)
Protected Member Functions
void focusOutEvent (QFocusEvent *) override
void mousePressEvent (QMouseEvent *) override
void mouseMoveEvent (QMouseEvent *) override
void mouseReleaseEvent (QMouseEvent *) override
Protected Member Functions inherited from DVGui::LineEdit
void focusInEvent (QFocusEvent *event) override
void keyPressEvent (QKeyEvent *event) override
void mouseMoveEvent (QMouseEvent *) override
Additional Inherited Members
Signals inherited from DVGui::LineEdit
void focusIn ()
void returnPressedNow ()
void mouseMoved (QMouseEvent *)
Detailed Description
The IntLineEdit class provides an object to manage an integer line edit.
         Inherits \b LineEdit, set an integer validator \b QIntValidator.
         You can pass to constructor current value, minimum and max value
field or set this value using setValue(), setRange() .
Constructor & Destructor Documentation
IntLineEdit()
IntLineEdit::IntLineEdit (QWidget * parent = 0, int value = 1, int minValue = (-(std::numeric_limits<int>::max)()), int maxValue = ((std::numeric_limits<int>::max)()), int showedDigits = 0)
    : LineEdit(parent), m_showedDigits(showedDigits) {
  setFixedWidth(54);
  m_validator = new QIntValidator(this);
  setValue(value);
  setRange(minValue, maxValue);
  setValidator(m_validator);
}
~IntLineEdit()
DVGui::IntLineEdit::~IntLineEdit () inline
{}
Member Function Documentation
focusOutEvent()
void IntLineEdit::focusOutEvent (QFocusEvent * e) override protected
If focus is lost and current text value is out of range emit signal editingFinished.
{
  int value = getValue();
  int minValue, maxValue;
  getRange(minValue, maxValue);
  if (e->lostFocus()) setValue(value);
  QLineEdit::focusOutEvent(e);
  m_isTyping = false;
}
References getRange(), getValue(), and setValue().
getRange()
void IntLineEdit::getRange (int & minValue, int & maxValue)
Set minValue an maxValue to current range; to current validator minimum and maximum value.
{
  minValue = m_validator->bottom();
  maxValue = m_validator->top();
}
Referenced by focusOutEvent(), and setValue().
getValue()
int IntLineEdit::getValue ()
Return an integer with text field value.
{ return text().toInt(); }
Referenced by focusOutEvent(), DVGui::ChannelField::getChannel(), DVGui::IntField::getValue(), FrameNavigator::onEditingFinished(), DVGui::IntField::onEditingFinished(), DVGui::IntPairField::onLeftEditingFinished(), DVGui::IntPairField::onRightEditingFinished(), DVGui::IntField::onRollerValueChanged(), DVGui::ChannelField::onSliderChanged(), DVGui::IntField::onSliderChanged(), and DVGui::IntField::setValue().
mouseMoveEvent()
void IntLineEdit::mouseMoveEvent (QMouseEvent * e) override protected
{
  if (e->buttons() == Qt::MiddleButton) {
    setValue(getValue() + ((e->x() - m_xMouse) / 2));
    m_xMouse = e->x();
  } else
    QLineEdit::mouseMoveEvent(e);
}
mousePressEvent()
void IntLineEdit::mousePressEvent (QMouseEvent * e) override protected
{
  if (e->buttons() == Qt::MiddleButton) {
    m_xMouse           = e->x();
    m_mouseDragEditing = true;
  } else {
    QLineEdit::mousePressEvent(e);
    if (!m_isTyping) {  // only the first click will select all
      selectAll();
      m_isTyping = true;
    }
  }
}
mouseReleaseEvent()
void IntLineEdit::mouseReleaseEvent (QMouseEvent * e) override protected
{
  if ((e->buttons() == Qt::NoButton && m_mouseDragEditing)) {
    m_mouseDragEditing = false;
    clearFocus();
  } else
    QLineEdit::mouseReleaseEvent(e);
}
setBottomRange()
void IntLineEdit::setBottomRange (int minValue)
Set to minValue minimum range value.
See also
setRange()
{
  m_validator->setBottom(minValue);
}
setLineEditBackgroundColor()
void IntLineEdit::setLineEditBackgroundColor (QColor color)
{
  // Set text color based on luminescence of bg color
  int value           = 0;
  double luminescence = ((0.299 * color.red()) + (0.587 * color.green()) +
                         (0.114 * color.blue())) /
                        255;
  if (luminescence > 0.5)
    value = 0;  // black
  else
    value = 255;  // white
  QString sheet =
      QString("background-color: rgba(") + QString::number(color.red()) +
      QString(",") + QString::number(color.green()) + QString(",") +
      QString::number(color.blue()) + QString(",") +
      QString::number(color.alpha()) +
      QString(");" +
              QString("color: rgb(" + QString::number(value) + QString(",") +
                      QString::number(value) + QString(",") +
                      QString::number(value) + QString(");")));
  setStyleSheet(sheet);
}
setRange()
void IntLineEdit::setRange (int minValue, int maxValue)
Set the range of field from minValue to maxValue; set validator value.
{
  m_validator->setRange(minValue, maxValue);
}
Referenced by DVGui::IntField::setRange(), and DVGui::IntPairField::setRange().
setTopRange()
void IntLineEdit::setTopRange (int maxValue)
Set to maxValue maximum range value.
See also
getRange()
{ m_validator->setTop(maxValue); }
setValue()
void IntLineEdit::setValue (int value)
Set text in field to value.
{
  int minValue, maxValue;
  getRange(minValue, maxValue);
  if (value < minValue) value = minValue;
  if (value > maxValue) value = maxValue;
  QString str;
  str.setNum(value);
  if (m_showedDigits > 0) {
    while (str.length() < m_showedDigits) str.push_front("0");
    while (str.length() > m_showedDigits) str.remove(0, 1);
  }
  setText(str);
  // Faccio in modo che il cursore sia sulla prima cifra, cosi' se la stringa da
  // visualizzare
  // e' piu' lunga del campo le cifre che vengono troncate sono le ultime e non
  // le prime.
  setCursorPosition(0);
}
References getRange().
Referenced by focusOutEvent(), DVGui::ChannelField::onEditChanged(), DVGui::IntPairField::onLeftEditingFinished(), DVGui::IntPairField::onRightEditingFinished(), DVGui::IntField::onRollerValueChanged(), DVGui::IntField::onSliderChanged(), DVGui::ChannelField::setChannel(), DVGui::IntPairField::setValue(), DVGui::IntField::setValue(), DVGui::IntPairField::setValues(), OutputSettingsPopup::updateField(), FrameNavigator::updateFrame(), and LevelSettingsPopup::updateLevelSettings().
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/toonzqt/intfield.h
E:/opentoonz/toonz/sources/toonzqt/intfield.cpp