opentoonz: TXshPaletteLevel Class Reference
TXshPaletteLevel Class Reference final
The TXshPaletteLevel class represents a palette uncoupled from a level.
#include <txshpalettelevel.h>
Public Member Functions
TXshPaletteLevel (std::wstring name=L"")
~TXshPaletteLevel ()
TXshPaletteLevel * getPaletteLevel () override
TPalette * getPalette () const
void setPalette (TPalette *palette)
TFilePath getPath () const override
void setPath (const TFilePath &path)
int getFrameCount () const override
void loadData (TIStream &is) override
Load the level data (i.e. name, path, etc. e.g. from the .tnz file)
void saveData (TOStream &os) override
Save the level data (i.e. name, path, etc. e.g. to the .tnz file)
void load () override
Load the level content from the associated path.
void save () override
Save the level content to the associated path.
void save (const TFilePath &fp)
const TContentHistory * getContentHistory () const
note gets the contentHistory. can be 0
TContentHistory * getContentHistory ()
void setContentHistory (TContentHistory *contentHistory)
Public Member Functions inherited from TXshLevel
TXshLevel (ClassCode classCode, std::wstring name)
virtual ~TXshLevel ()
void setName (std::wstring name)
int getType () const
void setType (int type)
change the level type;
ToonzScene * getScene () const
Return the ToonzScene the level belongs to;.
virtual void setScene (ToonzScene *scene)
virtual TXshSimpleLevel * getSimpleLevel ()
Method (to be overridden in subclasses) to downcast to TXshSimpleLevel.
virtual TXshChildLevel * getChildLevel ()
Method (to be overridden in subclasses) to downcast to TXshChildLevel.
virtual TXshZeraryFxLevel * getZeraryFxLevel ()
virtual TXshPaletteLevel * getPaletteLevel ()
Method (to be overridden in subclasses) to downcast to TXshPaletteLevel.
virtual TXshSoundLevel * getSoundLevel ()
Method (to be overridden in subclasses) to downcast to TXshSoundLevel.
virtual TXshSoundTextLevel * getSoundTextLevel ()
std::wstring getName () const
Return level name.
std::wstring getShortName () const
Return level short name.
virtual TFilePath getPath () const
Return the file path associated with the level.
virtual bool isEmpty () const
virtual int getFrameCount () const
virtual void getFids (std::vector< TFrameId > &fids) const
void loadData (TIStream &is) override=0
Load the level data (i.e. name, path, etc. e.g. from the .tnz file)
void saveData (TOStream &os) override=0
Save the level data (i.e. name, path, etc. e.g. to the .tnz file)
virtual void load ()=0
Load the level content from the associated path.
virtual void save ()=0
Save the level content to the associated path.
HookSet * getHookSet () const
virtual void setDirtyFlag (bool on)
Mark the level as "modified".
Public Member Functions inherited from TSmartObject
TSmartObject (ClassCode classCode)
void addRef ()
void release ()
TINT32 getRefCount () const
Public Member Functions inherited from TPersist
virtual void loadData (TIStream &is)=0
virtual void saveData (TOStream &os)=0
std::string getStreamTag () const
virtual const TPersistDeclaration * getDeclaration () const =0
Additional Inherited Members
Public Types inherited from TSmartObject
typedef short ClassCode
Public Types inherited from TPersist
typedef TPersist * CreateProc()
Static Public Member Functions inherited from TSmartObject
static TINT32 getInstanceCount (ClassCode code)
Static Public Member Functions inherited from TPersist
static void declare (CreateProc *)
static TPersist * create (const std::string &name)
Protected Member Functions inherited from TXshLevel
void updateShortName ()
create shortname from the level name
Protected Attributes inherited from TXshLevel
std::wstring m_name
std::wstring m_shortName
int m_type
HookSet * m_hookSet
ToonzScene * m_scene
Detailed Description
The TXshPaletteLevel class represents a palette uncoupled from a level.
Inherits TXshLevel.
A palette can be loaded in the xsheet and subsequently can be used as "external palette". The number of frames of the palette-level depends on the palette animation.
Constructor & Destructor Documentation
TXshPaletteLevel()
TXshPaletteLevel::TXshPaletteLevel (std::wstring name = L"")
Constructs a TXshPaletteLevel with name
    : TXshLevel(m_classCode, name), m_palette(0) {
  m_type = PLT_XSHLEVEL;
}
~TXshPaletteLevel()
TXshPaletteLevel::~TXshPaletteLevel ()
Destroys the TXshPaletteLevel object.
{}
Member Function Documentation
getContentHistory() [1/2]
TContentHistory * TXshPaletteLevel::getContentHistory () inline
{ return m_contentHistory; }
getContentHistory() [2/2]
const TContentHistory * TXshPaletteLevel::getContentHistory () const inline
note gets the contentHistory. can be 0
{ return m_contentHistory; }
getFrameCount()
int TXshPaletteLevel::getFrameCount () const override virtual
Returns the frame count. It depends on the palette animation: for a not-animated palette getFrameCount() == 1
Reimplemented from TXshLevel.
{ return 0; }
getPalette()
TPalette * TXshPaletteLevel::getPalette () const
Return the TPalette
See also
setPalette()
{ return m_palette; }
Referenced by StylePickerTool::onImageChanged().
getPaletteLevel()
TXshPaletteLevel * TXshPaletteLevel::getPaletteLevel () inline override virtual
Return the TXshPaletteLevel level (overridden from TXshLevel)
Reimplemented from TXshLevel.
{ return this; }
getPath()
TFilePath TXshPaletteLevel::getPath () const inline override virtual
Return level path.
See also
setPath()
Reimplemented from TXshLevel.
{ return m_path; }
load()
void TXshPaletteLevel::load () override virtual
Load the level content from the associated path.
Implements TXshLevel.
{
  TFilePath path = getScene()->decodeFilePath(m_path);
  if (TSystem::doesExistFileOrLevel(path)) {
    TFileStatus fs(path);
    TPersist *p = 0;
    TIStream is(path);
    TPalette *palette = nullptr;
    if (is && fs.doesExist()) {
      std::string tagName;
      if (is.matchTag(tagName) && tagName == "palette") {
        std::string gname;
        is.getTagParam("name", gname);
        palette = new TPalette();
        palette->loadData(is);
        palette->setGlobalName(::to_wstring(gname));
        is.matchEndTag();
        palette->setPaletteName(path.getWideName());
        setPalette(palette);
      }
    }
    assert(m_palette);
  }
}
References ToonzScene::decodeFilePath(), TXshLevel::getScene(), TIStream::getTagParam(), TIStream::matchEndTag(), TIStream::matchTag(), and setPalette().
loadData()
void TXshPaletteLevel::loadData (TIStream & is) override virtual
Load the level data (i.e. name, path, etc. e.g. from the .tnz file)
Implements TXshLevel.
{
  std::string tagName;
  while (is.matchTag(tagName)) {
    if (tagName == "name") {
      std::wstring name;
      is >> name;
      setName(name);
    } else if (tagName == "path") {
      is >> m_path;
    } else {
      throw TException("TXshPaletteLevel, unknown tag: " + tagName);
    }
    is.closeChild();
  }
}
References TIStream::closeChild(), and TIStream::matchTag().
save()
void TXshPaletteLevel::save () override virtual
Save the level content to the associated path.
Implements TXshLevel.
{
  TFilePath path = getScene()->decodeFilePath(m_path);
  if (TSystem::doesExistFileOrLevel(path) && m_palette) {
    TFileStatus fs(path);
    if (!fs.isWritable()) {
      throw TSystemException(
          path, "The palette cannot be saved: it is a read only palette.");
    }
    TOStream os(path);
    os << m_palette;
  }
}
References ToonzScene::decodeFilePath(), and TXshLevel::getScene().
Referenced by ScenePalette::save().
saveData()
void TXshPaletteLevel::saveData (TOStream & os) override virtual
Save the level data (i.e. name, path, etc. e.g. to the .tnz file)
Implements TXshLevel.
{
  os.child("path") << m_path;
  os.child("name") << getName();
}
References TOStream::child(), and TXshLevel::getName().
setContentHistory()
void TXshPaletteLevel::setContentHistory (TContentHistory * contentHistory)
destroys the old contentHistory and replaces it with the new one. Gets ownership
setPalette()
void TXshPaletteLevel::setPalette (TPalette * palette)
Set the level palette to palette.
See also
getPalette()
{
  if (m_palette != palette) {
    if (m_palette) m_palette->release();
    m_palette = palette;
    if (m_palette) m_palette->addRef();
  }
}
Referenced by load().
setPath()
void TXshPaletteLevel::setPath (const TFilePath & path)
Set level path.
See also
getPath()
{ m_path = path; }
Referenced by ScenePalette::rollbackPath(), and ScenePalette::updatePath().
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/toonz/txshpalettelevel.h
E:/opentoonz/toonz/sources/toonzlib/txshpalettelevel.cpp