opentoonz: ShaderInterface Class Reference
ShaderInterface Class Reference final
#include <shaderinterface.h>
Classes
class Parameter
class ParameterConcept
union ParameterValue
class ShaderData
Public Types
enum ParameterConceptType {
CONCEPT_NONE , PERCENT , LENGTH , ANGLE ,
POINT , RADIUS_UI , WIDTH_UI , ANGLE_UI ,
POINT_UI , XY_UI , VECTOR_UI , POLAR_UI ,
SIZE_UI , QUAD_UI , RECT_UI , COMPASS_UI ,
COMPASS_SPIN_UI , CONCEPTSCOUNT , UI_CONCEPTS = RADIUS_UI
}
enum ParameterType {
PARAMETER_UNKNOWN , BOOL , FLOAT , VEC2 ,
VEC3 , VEC4 , INT , IVEC2 ,
IVEC3 , IVEC4 , RGBA , RGB ,
TYPESCOUNT
}
enum HandledWorldTransformsType { HWT_UNKNOWN , ANY , ISOTROPIC , HWTCOUNT }
Public Types inherited from TPersist
typedef TPersist * CreateProc()
Public Member Functions
bool isValid () const
const std::vector< Parameter > & parameters () const
const std::vector< QString > & inputPorts () const
const ShaderData & mainShader () const
const ShaderData & inputPortsShader () const
const ShaderData & bboxShader () const
HandledWorldTransformsType hwtType () const
std::pair< QOpenGLShaderProgram *, QDateTime > makeProgram (const ShaderData &sd, int varyingsCount=0, const GLchar **varyingNames=0) const
Public Member Functions inherited from TPersist
virtual void loadData (TIStream &is)=0
virtual void saveData (TOStream &os)=0
std::string getStreamTag () const
virtual const TPersistDeclaration * getDeclaration () const =0
Protected Member Functions
void clear ()
void saveData (TOStream &os) override
void loadData (TIStream &is) override
Additional Inherited Members
Static Public Member Functions inherited from TPersist
static void declare (CreateProc *)
static TPersist * create (const std::string &name)
Detailed Description
A ShaderInterface represents interface data to a GLSL shader program.
Rationale
OpenGL shaders are supplied as text to be compiled at run-time by a GLSL compiler. In our case, the specified text is assumed to be stored in one or more files on hard-disk.
However, in order for an executable to correctly interface a GLSL shader program, further interface data must be supplied in some form.
Interface data include the path of the GLSL shader program file and parameters to be bound by the executable before the shader is run.
Usage
A ShaderInterface is loaded from an xml file. Since an interface could be loaded incorrectly, remember to check the isValid() method to ensure that the loading process succeeds.
A loaded ShaderInterface allows access to shader parameters and acts as a factory object to compiled QGLShaderProgram instances.
Member Enumeration Documentation
HandledWorldTransformsType
enum ShaderInterface::HandledWorldTransformsType
{ HWT_UNKNOWN, ANY, ISOTROPIC, HWTCOUNT };
ParameterConceptType
enum ShaderInterface::ParameterConceptType
{
    CONCEPT_NONE,
    PERCENT,
    LENGTH,
    ANGLE,
    POINT,
    RADIUS_UI,
    WIDTH_UI,
    ANGLE_UI,
    POINT_UI,
    XY_UI,
    VECTOR_UI,
    POLAR_UI,
    SIZE_UI,
    QUAD_UI,
    RECT_UI,
    COMPASS_UI,
    COMPASS_SPIN_UI,
    CONCEPTSCOUNT,
    UI_CONCEPTS = RADIUS_UI
  };
ParameterType
enum ShaderInterface::ParameterType
                     {
    PARAMETER_UNKNOWN,
    BOOL,
    FLOAT,
    VEC2,
    VEC3,
    VEC4,
    INT,
    IVEC2,
    IVEC3,
    IVEC4,
    RGBA,
    RGB,
    TYPESCOUNT
  };
Constructor & Destructor Documentation
ShaderInterface()
ShaderInterface::ShaderInterface ()
: m_hwt(ANY) {}
Member Function Documentation
bboxShader()
const ShaderInterface::ShaderData & ShaderInterface::bboxShader () const
{
  return m_bboxShader;
}
clear()
void ShaderInterface::clear () protected
{
  m_mainShader = m_portsShader = ShaderData();
  m_parameters.clear();
}
hwtType()
ShaderInterface::HandledWorldTransformsType ShaderInterface::hwtType () const
{
  return m_hwt;
}
inputPorts()
const std::vector< QString > & ShaderInterface::inputPorts () const
{
  return m_ports;
}
inputPortsShader()
const ShaderInterface::ShaderData & ShaderInterface::inputPortsShader () const
{
  return m_portsShader;
}
isValid()
bool ShaderInterface::isValid () const
{ return m_mainShader.isValid(); }
loadData()
void ShaderInterface::loadData (TIStream & is) override protected virtual
 This is a pure virtual function and must be overridden with a method
that implements the object loading from a stream (i.e take the object's features from a formatted data stream). For example the TStageObject class use his implementation to take the values of the parameters that characterizes a stage object as name, coordinates, etc... from a file. is is an input file stream
Implements TPersist.
{
  struct locals {
    inline static TFilePath getAbsolutePath(const TFilePath &file,
                                            const TFilePath &relTo) {
      QDir relToDir(
          QString::fromStdWString(relTo.getParentDir().getWideString()));
      QString absFileStr(relToDir.absoluteFilePath(
          QString::fromStdWString(file.getWideString())));
      return TFilePath(absFileStr.toStdWString());
    }
    static bool nameMatch(const QString &name, const Parameter &param) {
      return (name == param.m_name);
    }
  };
  std::string tagName;
  try {
    while (is.openChild(tagName)) {
      if (tagName == l_names[MAIN_PROGRAM]) {
        is >> m_mainShader;
        m_mainShader.m_type = QOpenGLShader::Fragment;
        is.closeChild();
      } else if (tagName == l_names[INPUT_PORTS]) {
        while (is.openChild(tagName)) {
          if (tagName == l_names[INPUT_PORT]) {
            QString portName;
            is >> portName;
            m_ports.push_back(portName);
            is.closeChild();
          } else if (tagName == l_names[PORTS_PROGRAM]) {
            is >> m_portsShader;
            m_portsShader.m_type = QOpenGLShader::Vertex;
            is.closeChild();
          } else
            ::skipTag(is, tagName);
        }
        is.closeChild();
      } else if (tagName == l_names[BBOX_PROGRAM]) {
        is >> m_bboxShader;
        m_bboxShader.m_type = QOpenGLShader::Vertex;
        is.closeChild();
      } else if (tagName == l_names[HANDLED_WORLD_TRANSFORMS]) {
        QString hwtName;
        is >> hwtName;
        m_hwt = HandledWorldTransformsType(
            std::find_if(l_hwtNames, l_hwtNames + HWTCOUNT,
                         ::CaselessCompare(hwtName)) -
            l_hwtNames);
        if (m_hwt == HWTCOUNT) {
          m_hwt = HWT_UNKNOWN;
          ::dumpError(is, L"Unrecognized HandledWorldTransforms type '" +
                              hwtName.toStdWString() + L"'");
        }
        is.closeChild();
      } else if (tagName == l_names[PARAMETERS]) {
        while (is.openChild(tagName)) {
          if (tagName == l_names[PARAMETER]) {
            Parameter param;
            is >> param;
            m_parameters.push_back(param);
            is.closeChild();
          } else
            ::skipTag(is, tagName);
        }
        is.closeChild();
      } else if (tagName == l_names[CONCEPT]) {
        ParameterConcept concept;
        is >> concept;
        m_parConcepts.push_back(concept);
        is.closeChild();
      } else
        ::skipTag(is, tagName);
    };
  } catch (const TException &e) {
    ::dumpError(is, e.getMessage());
    clear();
  } catch (...) {
    ::dumpError(is);
    clear();
  }
}
References TIStream::closeChild(), TFilePath::getParentDir(), ShaderInterface::ShaderData::m_type, and TIStream::openChild().
mainShader()
const ShaderInterface::ShaderData & ShaderInterface::mainShader () const
{
  return m_mainShader;
}
makeProgram()
std::pair< QOpenGLShaderProgram *, QDateTime > ShaderInterface::makeProgram (const ShaderData & sd, int varyingsCount = 0, const GLchar ** varyingNames = 0) const
Returns a compiled shader program against current OpenGL context, and the last modified date of the associated shader file.
{
  CompiledShader result;
  if (!isValid()) return result;
  result.first = new QOpenGLShaderProgram;
  ::loadShader(sd.m_type, sd.m_path, result);
  if (varyingsCount > 0)
    glTransformFeedbackVaryings(result.first->programId(), varyingsCount,
                                varyingNames, GL_INTERLEAVED_ATTRIBS);
  // NOTE: Since we'll be drawing a single vertex, GL_INTERLEAVED_ATTRIBS is
  // less restrictive than GL_SEPARATE_ATTRIBS.
  result.first->link();
  return result;
}
References ShaderInterface::ShaderData::m_path, and ShaderInterface::ShaderData::m_type.
parameters()
const std::vector< ShaderInterface::Parameter > & ShaderInterface::parameters () const
          {
  return m_parameters;
}
saveData()
void ShaderInterface::saveData (TOStream & os) override protected virtual
 This is a pure virtual function and must be overridden with a method
that implements the object saving to a data stream (i.e put the object's features on a formatted data stream). For example the TStageObject class use his implementation to save the values of the parameters that characterizes a stage object as name, coordinates, etc... on a file os is an output file stream.
Implements TPersist.
{
  struct locals {
    inline static TFilePath getRelativePath(const TFilePath &file,
                                            const TFilePath &relTo) {
      QDir relToDir(
          QString::fromStdWString(relTo.getParentDir().getWideString()));
      QString relFileStr(relToDir.relativeFilePath(
          QString::fromStdWString(file.getWideString())));
      return TFilePath(relFileStr.toStdWString());
    }
  };
  assert(isValid());
  if (isValid()) {
    os.openChild(l_names[MAIN_PROGRAM]);
    os << m_mainShader;
    os.closeChild();
    os.openChild(l_names[INPUT_PORTS]);
    {
      int i, iCount = int(m_ports.size());
      for (i = 0; i != iCount; ++i) {
        os.openChild(l_names[INPUT_PORT]);
        os << m_ports[i];
        os.closeChild();
      }
      if (m_portsShader.isValid()) {
        os.openChild(l_names[PORTS_PROGRAM]);
        os << m_portsShader;
        os.closeChild();
      }
    }
    os.closeChild();
    if (m_bboxShader.isValid()) {
      os.openChild(l_names[BBOX_PROGRAM]);
      os << m_bboxShader;
      os.closeChild();
    }
    if (m_hwt != ANY) {
      os.openChild(l_names[HANDLED_WORLD_TRANSFORMS]);
      os << l_names[m_hwt];
      os.closeChild();
    }
    os.openChild(l_names[PARAMETERS]);
    {
      int p, pCount = int(m_parameters.size());
      for (p = 0; p != pCount; ++p) {
        os.openChild(l_names[PARAMETER]);
        os << m_parameters[p];
        os.closeChild();
      }
    }
    os.closeChild();
  }
}
References TOStream::closeChild(), TFilePath::getParentDir(), and TOStream::openChild().
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/stdfx/shaderinterface.h
E:/opentoonz/toonz/sources/stdfx/shaderinterface.cpp