opentoonz: StylePickerTool Class Reference
StylePickerTool Class Reference final
Public Member Functions
TPropertyGroup * getProperties (int targetType) override
ToolType getToolType () const override
void draw () override
Draws the tool on the viewer.
void leftButtonDown (const TPointD &pos, const TMouseEvent &e) override
void leftButtonDrag (const TPointD &pos, const TMouseEvent &e) override
void pick (const TPointD &pos, const TMouseEvent &e, bool isDragging=true)
void mouseMove (const TPointD &pos, const TMouseEvent &e) override
int getCursorId () const override
Returns the type of cursor used by the tool.
bool onPropertyChanged (std::string propertyName) override
bool isOrganizePaletteActive ()
void onImageChanged () override
Notifies changes in the image in use.
void updateTranslation () override
Public Member Functions inherited from TTool
TTool (std::string toolName)
every tool (invoking updateTranslation() for each).
virtual ToolType getToolType () const =0
ToolTargetType getTargetType () const
std::string getName () const
virtual ToolOptionsBox * createOptionsBox ()
void setViewer (Viewer *viewer)
Viewer * getViewer () const
double getPixelSize () const
void invalidate (const TRectD &rect=TRectD())
int pick (const TPointD &p)
bool isPicking () const
virtual void updateTranslation ()
virtual bool preLeftButtonDown ()
virtual void mouseMove (const TPointD &, const TMouseEvent &)
virtual void leftButtonDown (const TPointD &, const TMouseEvent &)
virtual void leftButtonDrag (const TPointD &, const TMouseEvent &)
virtual void leftButtonUp (const TPointD &, const TMouseEvent &)
virtual void leftButtonDoubleClick (const TPointD &, const TMouseEvent &)
virtual void rightButtonDown (const TPointD &, const TMouseEvent &)
virtual bool keyDown (QKeyEvent *)
virtual void onInputText (std::wstring, std::wstring, int, int)
virtual void onSetViewer ()
virtual void onActivate ()
Callback invoked whenever the tool activates.
virtual void onDeactivate ()
Callback for tool deactivation, includes tool switch.
virtual void onImageChanged ()
Notifies changes in the image in use.
virtual void onEnter ()
Callback for the mouse entering the viewer area.
virtual void onLeave ()
Callback for the mouse leaving the viewer area.
virtual void onFrameSwitched ()
virtual void reset ()
virtual void draw ()
Draws the tool on the viewer.
bool isActive () const
Used to know if a tool is active, (used in TextTool only).
void setActive (bool active)
virtual TPropertyGroup * getProperties (int)
virtual bool onPropertyChanged (std::string propertyName)
virtual TSelection * getSelection ()
Returns a pointer to the tool selection.
virtual int getCursorId () const
Returns the type of cursor used by the tool.
virtual bool isEventAcceptable (QEvent *e)
TXsheet * getXsheet () const
Returns a pointer to the actual Xsheet.
int getFrame ()
Returns the actual frame in use.
int getColumnIndex ()
Returns the actual column index.
TStageObjectId getObjectId () const
Returns a pointer to the actual stage object.
void notifyImageChanged ()
void notifyImageChanged (const TFrameId &fid)
images on the level view.
TFrameId getCurrentFid () const
Returns the number of the actual editing frame.
const TAffine & getMatrix () const
void setMatrix (const TAffine &matrix)
TAffine getCurrentColumnMatrix (int frame=-1) const
TAffine getCurrentColumnParentMatrix () const
TAffine getCurrentObjectParentMatrix () const
TAffine getCurrentObjectParentMatrix2 () const
TAffine getColumnMatrix (int index, int frame=-1) const
virtual void updateMatrix ()
virtual void addContextMenuItems (QMenu *menu)
void enable (bool on)
bool isEnabled () const
QString updateEnabled ()
virtual QString updateEnabled (int rowIndex, int columnIndex)
bool isColumnLocked (int columnIndex) const
void resetInputMethod ()
Resets Input Context (IME)
virtual bool isPencilModeActive ()
virtual bool isDragging () const
void setSelectedFrames (const std::set< TFrameId > &selectedFrames)
void tweenSelectedGuideStrokes ()
void tweenGuideStrokeToSelected ()
void flipGuideStrokeDirection (int mode)
Additional Inherited Members
Public Types inherited from TTool
enum ToolType {
GenericTool = 1 , ColumnTool = 2 , LevelReadTool = 4 , LevelWriteTool ,
LevelTool = LevelReadTool | LevelWriteTool
}
Tool editing type.
enum ToolTargetType {
NoTarget = 0x0 , VectorImage = 0x1 , ToonzImage = 0x2 , RasterImage = 0x4 ,
MeshImage = 0x8 , Splines = 0x10 , LevelColumns = 0x20 , MeshColumns = 0x40 ,
EmptyTarget = 0x80 , CommonImages = VectorImage | ToonzImage | RasterImage , AllImages = CommonImages | MeshImage , Vectors = VectorImage | Splines ,
CommonLevels = CommonImages | LevelColumns , MeshLevels = MeshImage | MeshColumns , AllTargets = 0xffffffff
}
Object types the tool can operate on.
typedef TApplication Application
Static Public Member Functions inherited from TTool
static TTool * getTool (std::string toolName, ToolTargetType targetType)
static TApplication * getApplication ()
static void setApplication (TApplication *application)
static TXshCell getImageCell ()
Returns the level-frame pair to be edited by the tool.
static TImage * getImage (bool toBeModified, int subsampling=0)
Returns the image to be edited by the tool.
static TImage * touchImage ()
static void updateToolsPropertiesTranslation ()
static const std::set< TFrameId > & getSelectedFrames ()
Static Public Attributes inherited from TTool
static std::vector< CellOps > m_cellsData
static bool m_isLevelCreated = false
static bool m_isFrameCreated = false
static std::vector< TFrameId > m_oldFids
static std::vector< TFrameId > m_newFids
static bool m_isLevelRenumbererd = false
Protected Member Functions inherited from TTool
void bind (int targetType)
virtual void onSelectedFramesChanged ()
virtual QString disableString ()
Returns a custom reason to disable the tool.
Protected Attributes inherited from TTool
std::string m_name
The tool's name.
Viewer * m_viewer
Tool's current viewer.
TAffine m_matrix
World-to-window reference change affine.
int m_targetType
The tool's image type target.
bool m_enabled
Whether the tool allows user interaction.
bool m_active
bool m_picking
Static Protected Attributes inherited from TTool
static TApplication * m_application = 0
static std::set< TFrameId > m_selectedFrames = std::set<TFrameId>()
Detailed Description
Constructor & Destructor Documentation
StylePickerTool()
StylePickerTool::StylePickerTool ()
    : TTool("T_StylePicker")
    , m_currentStyleId(0)
    , m_colorType("Mode:")
    , m_passivePick("Passive Pick", false)
    , m_organizePalette("Organize Palette", false)
    , m_paletteToBeOrganized(NULL) {
  m_prop.bind(m_colorType);
  m_colorType.addValue(AREAS);
  m_colorType.addValue(LINES);
  m_colorType.addValue(ALL);
  m_colorType.setId("Mode");
  bind(TTool::CommonLevels);
  m_prop.bind(m_passivePick);
  m_passivePick.setId("PassivePick");
  m_prop.bind(m_organizePalette);
  m_organizePalette.setId("OrganizePalette");
}
Member Function Documentation
draw()
void StylePickerTool::draw () inline override virtual
Draws the tool on the viewer.
Reimplemented from TTool.
{}
getCursorId()
int StylePickerTool::getCursorId () const override virtual
Returns the type of cursor used by the tool.
See also
For a list of cursor ids cursor.h
Reimplemented from TTool.
{
  int ret;
  if (!Preferences::instance()->isMultiLayerStylePickerEnabled()) {
    TImageP img      = getImage(false);
    TVectorImageP vi = img;
    TToonzImageP ti  = img;
    if (!vi && !ti) return ToolCursor::CURSOR_NO;
  }
  /* in case the "organize palette" option is active */
  if (m_organizePalette.getValue())
    ret = ToolCursor::PickerCursorOrganize;
  else if (m_colorType.getValue() == LINES)
    ret = ToolCursor::PickerCursorLine;
  else if (m_colorType.getValue() == AREAS)
    ret = ToolCursor::PickerCursorArea;
  else  // line&areas
    ret = ToolCursor::PickerCursor;
  if (ToonzCheck::instance()->getChecks() & ToonzCheck::eBlackBg)
    ret = ret | ToolCursor::Ex_Negate;
  return ret;
}
References ToonzCheck::eBlackBg, and TTool::getImage().
getProperties()
TPropertyGroup * StylePickerTool::getProperties (int targetType) inline override virtual
Reimplemented from TTool.
{ return &m_prop; }
getToolType()
ToolType StylePickerTool::getToolType () const inline override virtual
Implements TTool.
{ return TTool::LevelReadTool; }
isOrganizePaletteActive()
bool StylePickerTool::isOrganizePaletteActive () inline
{ return m_organizePalette.getValue(); }
leftButtonDown()
void StylePickerTool::leftButtonDown (const TPointD & pos, const TMouseEvent & e) override virtual
Reimplemented from TTool.
{
  m_oldStyleId = m_currentStyleId =
      getApplication()->getCurrentLevelStyleIndex();
  pick(pos, e, false);
}
leftButtonDrag()
void StylePickerTool::leftButtonDrag (const TPointD & pos, const TMouseEvent & e) override virtual
Reimplemented from TTool.
{
  pick(pos, e);
}
mouseMove()
void StylePickerTool::mouseMove (const TPointD & pos, const TMouseEvent & e) override virtual
Reimplemented from TTool.
{
  if (!m_passivePick.getValue()) return;
  /*--- PassiveStyle ---*/
  PaletteController *controller =
      TTool::getApplication()->getPaletteController();
  TImageP image    = getImage(false);
  TToonzImageP ti  = image;
  TVectorImageP vi = image;
  TXshSimpleLevel *level =
      getApplication()->getCurrentLevel()->getSimpleLevel();
  if ((!ti && !vi) || !level || !m_viewer->getGeometry().contains(pos)) {
    controller->notifyStylePassivePicked(-1, -1, -1);
    return;
  }
  TAffine aff     = getViewer()->getViewMatrix() * getCurrentColumnMatrix();
  double scale2   = aff.det();
  int subsampling = level->getImageSubsampling(getCurrentFid());
  StylePicker picker(image);
  TPointD pickPos(TScale(1.0 / subsampling) * pos + TPointD(-0.5, -0.5));
  int inkStyleId   = picker.pickStyleId(pickPos, 10.0, scale2, 1);
  int paintStyleId = picker.pickStyleId(pickPos, 10.0, scale2, 0);
  int tone         = picker.pickTone(pickPos);
  controller->notifyStylePassivePicked(inkStyleId, paintStyleId, tone);
}
onImageChanged()
void StylePickerTool::onImageChanged () override virtual
Notifies changes in the image in use.
Reimplemented from TTool.
{
  std::cout << "StylePickerTool::onImageChanged" << std::endl;
  if (!m_organizePalette.getValue() || !m_paletteToBeOrganized) return;
  TXshLevel *level = getApplication()->getCurrentLevel()->getLevel();
  if (!level) {
    m_organizePalette.setValue(false);
    getApplication()->getCurrentTool()->notifyToolChanged();
    return;
  }
  TPalette *pal = NULL;
  if (level->getType() == PLT_XSHLEVEL)
    pal = level->getPaletteLevel()->getPalette();
  else if (level->getSimpleLevel()) {
    pal = level->getSimpleLevel()->getPalette();
  }
  if (!pal || pal != m_paletteToBeOrganized) {
    m_organizePalette.setValue(false);
    getApplication()->getCurrentTool()->notifyToolChanged();
    return;
  }
}
References TXshPaletteLevel::getPalette(), TXshSimpleLevel::getPalette(), TXshLevel::getPaletteLevel(), TXshLevel::getSimpleLevel(), TXshLevel::getType(), and ToolHandle::notifyToolChanged().
onPropertyChanged()
bool StylePickerTool::onPropertyChanged (std::string propertyName) override virtual
 Does the tasks associated to changes in \p propertyName and returns \p
true; Does the tasks associated to changes in propertyName and returns true.
Reimplemented from TTool.
{
  if (propertyName == m_organizePalette.getName()) {
    if (m_organizePalette.getValue()) {
      if (!startOrganizePalette()) {
        m_organizePalette.setValue(false);
        getApplication()->getCurrentTool()->notifyToolChanged();
        return false;
      }
    } else {
      std::cout << "End Organize Palette" << std::endl;
      m_paletteToBeOrganized = NULL;
    }
  }
  return true;
}
References ToolHandle::notifyToolChanged().
pick()
void StylePickerTool::pick (const TPointD & pos, const TMouseEvent & e, bool isDragging = true)
{
  // Area = 0, Line = 1, All = 2
  int modeValue = m_colorType.getIndex();
  //------------------------------------
  // MultiLayerStylePicker
  /*---
                  PickStyleId = 0
                  Preference  MultiLayerStylePicker
                  Scene
                  Transparent
                   Level
  ---*/
  if (Preferences::instance()->isMultiLayerStylePickerEnabled() &&
      getApplication()->getCurrentFrame()->isEditingScene()) {
    double pickRange = 10.0;
    int superPickedColumnId =
        getViewer()->posToColumnIndex(e.m_pos, pickRange, false);
    if (superPickedColumnId >= 0 /*-- Column --*/
        && getApplication()->getCurrentColumn()->getColumnIndex() !=
               superPickedColumnId) /*-- Current Column --*/
    {
      /*-- ColumnPick --*/
      int currentFrame = getApplication()->getCurrentFrame()->getFrame();
      TXshCell pickedCell =
          getApplication()->getCurrentXsheet()->getXsheet()->getCell(
              currentFrame, superPickedColumnId);
      TImageP pickedImage           = pickedCell.getImage(false).getPointer();
      TToonzImageP picked_ti        = pickedImage;
      TVectorImageP picked_vi       = pickedImage;
      TXshSimpleLevel *picked_level = pickedCell.getSimpleLevel();
      if ((picked_ti || picked_vi) && picked_level) {
        TPointD tmpMousePosition = getColumnMatrix(superPickedColumnId).inv() *
                                   getViewer()->winToWorld(e.m_pos);
        TPointD tmpDpiScale = getCurrentDpiScale(picked_level, getCurrentFid());
        tmpMousePosition.x /= tmpDpiScale.x;
        tmpMousePosition.y /= tmpDpiScale.y;
        TAffine aff =
            getViewer()->getViewMatrix() * getColumnMatrix(superPickedColumnId);
        double scale2 = aff.det();
        StylePicker superPicker(pickedImage);
        int picked_subsampling =
            picked_level->getImageSubsampling(pickedCell.getFrameId());
        int superPicked_StyleId = superPicker.pickStyleId(
            TScale(1.0 / picked_subsampling) * tmpMousePosition +
                TPointD(-0.5, -0.5),
            pickRange, scale2, modeValue);
        /*-- StyleTransparent --*/
        if (superPicked_StyleId > 0) {
          /*-- Level --*/
          getApplication()->getCurrentLevel()->setLevel(picked_level);
          /*-- Column --*/
          getApplication()->getCurrentColumn()->setColumnIndex(
              superPickedColumnId);
          /*--  --*/
          if (getApplication()->getCurrentSelection()->getSelection())
            getApplication()
                ->getCurrentSelection()
                ->getSelection()
                ->selectNone();
          /*-- StyleId --*/
          getApplication()->setCurrentLevelStyleIndex(superPicked_StyleId,
                                                      !isDragging);
          return;
        }
      }
    }
  }
  /*-- MultiLayerStylePicker  --*/
  //------------------------------------
  TImageP image    = getImage(false);
  TToonzImageP ti  = image;
  TVectorImageP vi = image;
  TXshSimpleLevel *level =
      getApplication()->getCurrentLevel()->getSimpleLevel();
  if ((!ti && !vi) || !level) return;
  /*-- pick --*/
  if (!m_viewer->getGeometry().contains(pos)) return;
  TAffine aff     = getViewer()->getViewMatrix() * getCurrentColumnMatrix();
  double scale2   = aff.det();
  int subsampling = level->getImageSubsampling(getCurrentFid());
  StylePicker picker(image);
  int styleId =
      picker.pickStyleId(TScale(1.0 / subsampling) * pos + TPointD(-0.5, -0.5),
                         10.0, scale2, modeValue);
  if (styleId < 0) return;
  if (modeValue == 1)  // LINES
  {
    /*-- pickLineStyle0Style
     * --*/
    if (styleId == 0) return;
    /*--
     * pickLinePurePaintStyle
     * --*/
    if (ti && picker.pickTone(TScale(1.0 / subsampling) * pos +
                              TPointD(-0.5, -0.5)) == 255)
      return;
  }
  /*--- Style ---*/
  TSelection *selection =
      TTool::getApplication()->getCurrentSelection()->getSelection();
  if (selection) {
    TStyleSelection *styleSelection =
        dynamic_cast<TStyleSelection *>(selection);
    if (styleSelection) styleSelection->selectNone();
  }
  // When clicking and switching between studio palette and level palette, the
  // signal broadcastColorStyleSwitched is not emitted if the picked style is
  // previously selected one.
  // Therefore here I set the "forceEmit" flag to true in order to emit the
  // signal whenever the picking with mouse press.
  getApplication()->setCurrentLevelStyleIndex(styleId, !isDragging);
}
updateTranslation()
void StylePickerTool::updateTranslation () override virtual
Reimplemented from TTool.
{
  m_colorType.setQStringName(tr("Mode:"));
  m_colorType.setItemUIName(LINES, tr("Lines"));
  m_colorType.setItemUIName(AREAS, tr("Areas"));
  m_colorType.setItemUIName(ALL, tr("Lines & Areas"));
  m_passivePick.setQStringName(tr("Passive Pick"));
  m_organizePalette.setQStringName(tr("Organize Palette"));
}
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/tnztools/stylepickertool.h
E:/opentoonz/toonz/sources/tnztools/stylepickertool.cpp