opentoonz: TContentHistory Class Reference
TContentHistory Class Reference
#include <tcontenthistory.h>
Public Member Functions
TContentHistory (bool isLevel)
set isLevel=true if you want to keep track of single-frames modifications
TContentHistory * clone () const
void deserialize (const QString &history)
const QString serialize () const
the returned string is only for visualitation and serialization
void fixCurrentHistory ()
void frameModifiedNow (const TFrameId &id)
do not call this 2 methods if isLevel==false! (assertion fails)
void frameRangeModifiedNow (const TFrameId &fromId, const TFrameId &toId)
void modifiedNow ()
do not call this method if isLevel==true! (assertion fails)
Detailed Description
this class keeps tracks of modification times on contents, as well as user and machine info; typically used for levels and scene files (or whatever you like...)
Constructor & Destructor Documentation
TContentHistory()
TContentHistory::TContentHistory (bool isLevel)
set isLevel=true if you want to keep track of single-frames modifications
    : m_isLevel(isLevel), m_frozenHistory() {}
~TContentHistory()
TContentHistory::~TContentHistory ()
{}
Member Function Documentation
clone()
TContentHistory * TContentHistory::clone () const
{
  TContentHistory *history = new TContentHistory(m_isLevel);
  history->deserialize(serialize());
  return history;
}
deserialize()
void TContentHistory::deserialize (const QString & history)
history can come only from a deserialization WARNING! any preexistent history will be erased by calling this method
{
  m_frozenHistory = currentHistory;
}
fixCurrentHistory()
void TContentHistory::fixCurrentHistory ()
after calling this method, following history info added will not "merge" with the history until now
{
  m_frozenHistory = serialize();
  m_records.clear();
}
References serialize().
frameModifiedNow()
void TContentHistory::frameModifiedNow (const TFrameId & id) inline
do not call this 2 methods if isLevel==false! (assertion fails)
{ frameRangeModifiedNow(id, id); }
Referenced by TXshSimpleLevel::touchFrame().
frameRangeModifiedNow()
void TContentHistory::frameRangeModifiedNow (const TFrameId & fromId, const TFrameId & toId)
{
  assert(m_isLevel);
  QDateTime date = QDateTime::currentDateTime();
  QDateTime dateNoSecs(date.date(), date.time().addSecs(-date.time().second()));
  assert(dateNoSecs.secsTo(date) == date.time().second());
  int i;
  m_records[fromId] = dateNoSecs;
  if (fromId == toId) return;
  for (i = fromId.getNumber() + 1; i <= toId.getNumber() - 1; i++)
    m_records[TFrameId(i)] = dateNoSecs;
  m_records[toId] = dateNoSecs;
}
modifiedNow()
void TContentHistory::modifiedNow ()
do not call this method if isLevel==true! (assertion fails)
{
  assert(!m_isLevel);
  QDateTime date = QDateTime::currentDateTime();
  QDateTime dateNoSecs(date.date(), date.time().addSecs(-date.time().second()));
  assert(dateNoSecs.secsTo(date) == date.time().second());
  m_records[0] = dateNoSecs;
}
serialize()
const QString TContentHistory::serialize () const
the returned string is only for visualitation and serialization
{
  const QString currentHistory = currentToString();
  if (m_frozenHistory != "")
    return m_frozenHistory + currentHistory;
  else if (currentHistory != "") {
    if (m_isLevel)
      return "| #    DATE:       Time:   MACHINE:    USER:          FRAMES "
             "MODIFIED:     |" +
             currentHistory;
    else
      return "| #    DATE:       Time:   MACHINE:    USER:           |" +
             currentHistory;
  } else
    return "";
}
Referenced by fixCurrentHistory(), and ToonzScene::save().
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/tcontenthistory.h
E:/opentoonz/toonz/sources/common/tcontenthistory.cpp