opentoonz: TSoundTrackT< T > Class Template Reference
TSoundTrackT< T > Class Template Reference final
Public Types
typedef T SampleType
Public Types inherited from TSmartObject
typedef short ClassCode
Public Member Functions
TSoundTrackT (TUINT32 sampleRate, int channelCount, TINT32 sampleCount)
TSoundTrackT (TUINT32 sampleRate, int channelCount, TINT32 sampleCount, T *buffer, TSoundTrackT< T > *parent)
bool isSampleSigned () const override
Returns true if the samples of the soundtrack are signed, false otherwise.
const T * samples () const
Returns the const samples array.
T * samples ()
Returns the samples array.
TSoundTrackP clone () const override
Returns a soundtrack whom is a clone of the object.
TSoundTrackP extract (TINT32 s0, TINT32 s1) override
Extract the subtrack in the samples range [s0,s1] given in samples.
TSoundTrackP clone (TSound::Channel chan) const override
void copy (const TSoundTrackP &src, TINT32 dst_s0) override
Copies from sample dst_s0 of object the samples of the soundtrack src.
TSoundTrackP apply (TSoundTransform *transform) override
double getPressure (TINT32 s, TSound::Channel chan) const override
Returns the pressure of the sample s about the channel chan.
void getMinMaxPressure (TINT32 s0, TINT32 s1, TSound::Channel chan, double &min, double &max) const override
double getMaxPressure (TINT32 s0, TINT32 s1, TSound::Channel chan) const override
double getMinPressure (TINT32 s0, TINT32 s1, TSound::Channel chan) const override
void copyChannel (const TSoundTrackT< T > &src, TINT32 src_s0, TINT32 src_s1, TSound::Channel srcChan, TINT32 dst_s0, TSound::Channel dstChan)
void blank (TINT32 s0, TINT32 s1) override
Makes blank the samples in the given sample range.
void blankChannel (TINT32 s0, TINT32 s1, TSound::Channel chan)
Makes blank the samples in the given sample range and channel.
Public Member Functions inherited from TSoundTrack
TINT32 secondsToSamples (double sec) const
Converts from seconds to samples according to the soundtrack sample rate.
double samplesToSeconds (TINT32 smp) const
Converts from samples to seconds according to the soundtrack sample rate.
TUINT32 getSampleRate () const
int getSampleSize () const
int getChannelCount () const
int getBitPerSample () const
TINT32 getSampleCount () const
double getDuration () const
Returns the duration of the soundtrack in seconds.
virtual bool isSampleSigned () const =0
Returns true if the samples of the soundtrack are signed, false otherwise.
TSoundTrackFormat getFormat () const
Returns the soundtrack format.
const UCHAR * getRawData () const
Returns a pointer to the samples buffer.
void setSampleRate (TUINT32 sampleRate)
virtual TSoundTrackP clone () const =0
Clones the soundtrack.
virtual TSoundTrackP clone (TSound::Channel chan) const =0
Returns a soundtrack that contains just the cloned channel.
virtual TSoundTrackP extract (TINT32 s0, TINT32 s1)=0
Returns a subtrack for the range [s0, s1], s0 and s1 are samples.
TSoundTrackP extract (double t0, double t1)
Returns a subtrack for the range [t0, t1], t0 and t1 are seconds.
virtual void copy (const TSoundTrackP &src, TINT32 dst_s0)=0
void copy (const TSoundTrackP &src, double dst_t0)
virtual void blank (TINT32 s0, TINT32 s1)=0
Blanks the soundtrack in the given range.
void blank (double t0, double t1)
virtual TSoundTrackP apply (TSoundTransform *)=0
virtual double getPressure (TINT32 sample, TSound::Channel chan) const =0
double getPressure (double second, TSound::Channel chan) const
Returns the soundtrack pressure value for the given time and channel.
virtual void getMinMaxPressure (TINT32 s0, TINT32 s1, TSound::Channel chan, double &min, double &max) const =0
void getMinMaxPressure (double t0, double t1, TSound::Channel chan, double &min, double &max) const
void getMinMaxPressure (TSound::Channel chan, double &min, double &max) const
Returns the soundtrack pressure min and max values for the given channel.
virtual double getMaxPressure (TINT32 s0, TINT32 s1, TSound::Channel chan) const =0
double getMaxPressure (double t0, double t1, TSound::Channel chan) const
double getMaxPressure (TSound::Channel chan) const
Returns the soundtrack pressure max value for the given channel.
virtual double getMinPressure (TINT32 s0, TINT32 s1, TSound::Channel chan) const =0
double getMinPressure (double t0, double t1, TSound::Channel chan) const
double getMinPressure (TSound::Channel chan) const
Returns the soundtrack pressure min value for the given channel.
Public Member Functions inherited from TSmartObject
TSmartObject (ClassCode classCode)
void addRef ()
void release ()
TINT32 getRefCount () const
Additional Inherited Members
Static Public Member Functions inherited from TSoundTrack
static TSoundTrackP create (TUINT32 sampleRate, int bitPerSample, int channelCount, TINT32 sampleCount, bool signedSample=true)
static TSoundTrackP create (TUINT32 sampleRate, int bitPerSample, int channelCount, TINT32 sampleCount, void *buffer, bool signedSample=true)
static TSoundTrackP create (const TSoundTrackFormat &format, TINT32 sampleCount)
static TSoundTrackP create (const TSoundTrackFormat &format, TINT32 sampleCount, void *buffer)
Static Public Member Functions inherited from TSmartObject
static TINT32 getInstanceCount (ClassCode code)
Protected Member Functions inherited from TSoundTrack
TSoundTrack (TUINT32 sampleRate, int bitPerSample, int channelCount, int sampleSize, TINT32 sampleCount, bool isSampleSigned)
TSoundTrack (TUINT32 sampleRate, int bitPerSample, int channelCount, int sampleSize, TINT32 sampleCount, UCHAR *buffer, TSoundTrack *parent)
Protected Attributes inherited from TSoundTrack
TUINT32 m_sampleRate
int m_sampleSize
int m_bitPerSample
TINT32 m_sampleCount
int m_channelCount
TSoundTrack * m_parent
UCHAR * m_buffer
bool m_bufferOwner
Detailed Description
template<class T>
class TSoundTrackT< T >
Member Typedef Documentation
SampleType
template<class T > typedef T TSoundTrackT< T >::SampleType
Constructor & Destructor Documentation
TSoundTrackT() [1/2]
template<class T > TSoundTrackT< T >::TSoundTrackT (TUINT32 sampleRate, int channelCount, TINT32 sampleCount) inline
      : TSoundTrack(sampleRate, T::getBitPerSample(), channelCount, sizeof(T),
                    sampleCount, T::isSampleSigned()) {}
TSoundTrackT() [2/2]
template<class T > TSoundTrackT< T >::TSoundTrackT (TUINT32 sampleRate, int channelCount, TINT32 sampleCount, T * buffer, TSoundTrackT< T > * parent) inline
      : TSoundTrack(sampleRate, T::getBitPerSample(), channelCount, sizeof(T),
                    sampleCount, reinterpret_cast<UCHAR *>(buffer), parent) {}
~TSoundTrackT()
template<class T > TSoundTrackT< T >::~TSoundTrackT () inline
{};
Member Function Documentation
apply()
template<class T > TSoundTrackP TSoundTrackT< T >::apply (TSoundTransform * transform) override virtual
Applies a transformation (echo, reverb, ect) to the object and returns the transformed soundtrack
Implements TSoundTrack.
{
  assert(transform);
  return transform->compute(*this);
}
blank()
template<class T > void TSoundTrackT< T >::blank (TINT32 s0, TINT32 s1) inline override virtual
Makes blank the samples in the given sample range.
Implements TSoundTrack.
{
    TINT32 ss0, ss1;
    // se i valori sono nel range ed uguali => voglio pulire
    // un solo campione
    if (s1 == s0 && s1 >= 0 && s1 < getSampleCount())
      ss0 = ss1 = s1;
    else {
      assert(s1 >= s0);
      ss0 = tcrop<TINT32>(s0, (TINT32)0, (TINT32)(getSampleCount() - 1));
      ss1 = tcrop<TINT32>(s1, (TINT32)0, (TINT32)(getSampleCount() - 1));
      assert(ss1 >= ss0);
      // esco perche' non ha senso pulire indiscriminatamente
      // il primo o l'ultimo campione
      if (ss1 == ss0) return;
    }
    T *sample = samples() + ss0;
    assert(sample);
    T blankSample;
    const T *endSample                   = sample + (ss1 - ss0 + 1);
    while (sample < endSample) *sample++ = blankSample;
  }
blankChannel()
template<class T > void TSoundTrackT< T >::blankChannel (TINT32 s0, TINT32 s1, TSound::Channel chan) inline
Makes blank the samples in the given sample range and channel.
{
    if (s0 > s1) return;
    // ....
    assert(false);
  }
clone() [1/2]
template<class T > TSoundTrackP TSoundTrackT< T >::clone () const inline override virtual
Returns a soundtrack whom is a clone of the object.
Implements TSoundTrack.
{
    TSoundTrackP dst = TSoundTrack::create(getFormat(), m_sampleCount);
    TSoundTrackP src(const_cast<TSoundTrack *>((const TSoundTrack *)this));
    dst->copy(src, (TINT32)0);
    return dst;
  }
References TSoundTrack::copy(), TSoundTrack::create(), and TSoundTrack::getFormat().
clone() [2/2]
template<class T > TSoundTrackP TSoundTrackT< T >::clone (TSound::Channel chan) const inline override virtual
Returns a soundtrack whom is a clone of the object for the specified channel. A clone means that it's an object who lives independently from the other from which it's created. It has no reference to the object.
Implements TSoundTrack.
{
    if (getChannelCount() == 1)
      return clone();
    else {
      typedef typename T::ChannelSampleType TCST;
      TSoundTrackT<TCST> *dst =
          new TSoundTrackT<TCST>(m_sampleRate, 1, getSampleCount());
      const T *sample    = samples();
      const T *endSample = sample + getSampleCount();
      TCST *dstSample = dst->samples();
      while (sample < endSample) {
        *dstSample++ = sample->getValue(chan);
        sample++;
      }
      return dst;
    }
  }
References TSoundTrack::clone(), and TSoundTrackT< T >::samples().
copy()
template<class T > void TSoundTrackT< T >::copy (const TSoundTrackP & src, TINT32 dst_s0) inline override virtual
Copies from sample dst_s0 of object the samples of the soundtrack src.
Implements TSoundTrack.
{
    TSoundTrackT<T> *srcT = dynamic_cast<TSoundTrackT<T> *>(src.getPointer());
    if (!srcT)
      throw(
          TException("Unable to copy from a track whose format is different"));
    T *srcSample    = srcT->samples();
    T *srcEndSample = srcT->samples() + srcT->getSampleCount();
    T *dstEndSample = samples() + getSampleCount();
    TINT32 ss0 = tcrop<TINT32>(dst_s0, (TINT32)0, getSampleCount() - (TINT32)1);
    T *dstSample = samples() + ss0;
    while (srcSample < srcEndSample && dstSample < dstEndSample)
      *dstSample++ = *srcSample++;
  }
References TSoundTrackT< T >::samples().
copyChannel()
template<class T > void TSoundTrackT< T >::copyChannel (const TSoundTrackT< T > & src, TINT32 src_s0, TINT32 src_s1, TSound::Channel srcChan, TINT32 dst_s0, TSound::Channel dstChan) inline
Copies the samples in the given sample range and channel inside the dstChan channel from sample dst_s0
{
    TINT32 ss0, ss1;
    // se i valori sono nel range ed uguali => voglio copiare il
    // canale di un solo campione
    if (src_s1 == src_s0 && src_s1 >= 0 && src_s1 < src.getSampleCount())
      ss0 = ss1 = src_s1;
    else {
      assert(src_s1 >= src_s0);
      ss0 = tcrop(src_s0, (TINT32)0, (TINT32)(src.getSampleCount() - 1));
      ss1 = tcrop(src_s1, (TINT32)0, (TINT32)(src.getSampleCount() - 1));
      assert(ss1 >= ss0);
      // esco perche' non ha senso copiare indiscriminatamente il primo
      // o l'ultimo campione della sorgente
      if (ss1 == ss0) return;
    }
    assert(dst_s0 >= 0L && dst_s0 < getSampleCount());
    const T *srcSample = src.samples() + ss0;
    const T *srcEndSample =
        srcSample +
        std::min((TINT32)(ss1 - ss0 + 1), (TINT32)(getSampleCount() - dst_s0));
    T *dstSample = samples() + dst_s0;
    for (; srcSample < srcEndSample; srcSample++, dstSample++)
      dstSample->setValue(srcChan, srcSample->getValue(dstChan));
  }
References TSoundTrackT< T >::samples().
extract()
template<class T > TSoundTrackP TSoundTrackT< T >::extract (TINT32 s0, TINT32 s1) inline override virtual
Extract the subtrack in the samples range [s0,s1] given in samples.
Implements TSoundTrack.
{
    if (!m_buffer || s0 > s1) return TSoundTrackP();
    // addRef();
    TINT32 ss0, ss1;
    ss0 = tcrop<TINT32>(s0, (TINT32)0, getSampleCount() - 1);
    ss1 = tcrop<TINT32>(s1, (TINT32)0, getSampleCount() - 1);
    return TSoundTrackP(new TSoundTrackT<T>(
        getSampleRate(), getChannelCount(), ss1 - ss0 + 1,
        (T *)(m_buffer + (long)(ss0 * getSampleSize())), this));
  }
getMaxPressure()
template<class T > double TSoundTrackT< T >::getMaxPressure (TINT32 s0, TINT32 s1, TSound::Channel chan) const inline override virtual
Returns the soundtrack pressure max value in the given sample range and channel
Implements TSoundTrack.
{
    TINT32 sampleCount = getSampleCount();
    if (sampleCount <= 0) {
      return -1;
    }
    assert(s1 >= s0);
    TINT32 ss0, ss1;
    ss0 = tcrop<TINT32>(s0, (TINT32)0, sampleCount - (TINT32)1);
    ss1 = tcrop<TINT32>(s1, (TINT32)0, sampleCount - (TINT32)1);
    assert(ss1 >= ss0);
    if (s0 == s1) return (getPressure(s0, chan));
    const T *sample = samples() + ss0;
    assert(sample);
    double maxPressure = sample->getPressure(chan);
    const T *endSample = sample + (ss1 - ss0 + 1);
    ++sample;
    while (sample < endSample) {
      if (maxPressure < sample->getPressure(chan))
        maxPressure = sample->getPressure(chan);
      ++sample;
    }
    return ((double)maxPressure);
  }
References TSoundTrack::getPressure().
getMinMaxPressure()
template<class T > void TSoundTrackT< T >::getMinMaxPressure (TINT32 s0, TINT32 s1, TSound::Channel chan, double & min, double & max) const inline override virtual
Returns the soundtrack pressure max and min values in the given sample range and channel
Implements TSoundTrack.
{
    TINT32 sampleCount = getSampleCount();
    if (sampleCount <= 0) {
      min = 0;
      max = -1;
      return;
    }
    assert(s1 >= s0);
    TINT32 ss0, ss1;
    ss0 = tcrop<TINT32>(s0, (TINT32)0, sampleCount - (TINT32)1);
    ss1 = tcrop<TINT32>(s1, (TINT32)0, sampleCount - (TINT32)1);
    assert(ss1 >= ss0);
    if (s0 == s1) {
      min = max = getPressure(s0, chan);
      return;
    }
    const T *sample = samples() + ss0;
    assert(sample);
    min = max = sample->getPressure(chan);
    const T *endSample = sample + (ss1 - ss0 + 1);
    ++sample;
    while (sample < endSample) {
      double value = sample->getPressure(chan);
      if (max < value) max = value;
      if (min > value) min = value;
      ++sample;
    }
  }
References TSoundTrack::getPressure().
getMinPressure()
template<class T > double TSoundTrackT< T >::getMinPressure (TINT32 s0, TINT32 s1, TSound::Channel chan) const inline override virtual
Returns the soundtrack pressure min value in the given sample range and channel
Implements TSoundTrack.
{
    TINT32 sampleCount = getSampleCount();
    if (sampleCount <= 0) {
      return 0;
    }
    assert(s1 >= s0);
    TINT32 ss0, ss1;
    ss0 = tcrop<TINT32>(s0, (TINT32)0, (TINT32)(getSampleCount() - (TINT32)1));
    ss1 = tcrop<TINT32>(s1, (TINT32)0, (TINT32)(getSampleCount() - (TINT32)1));
    assert(ss1 >= ss0);
    if (s0 == s1) return (getPressure(s0, chan));
    const T *sample = samples() + ss0;
    assert(sample);
    double minPressure = sample->getPressure(chan);
    const T *endSample = sample + (ss1 - ss0 + 1);
    ++sample;
    while (sample < endSample) {
      if (minPressure > sample->getPressure(chan))
        minPressure = sample->getPressure(chan);
      ++sample;
    }
    return ((double)minPressure);
  }
References TSoundTrack::getPressure().
getPressure()
template<class T > double TSoundTrackT< T >::getPressure (TINT32 s, TSound::Channel chan) const inline override virtual
Returns the pressure of the sample s about the channel chan.
Implements TSoundTrack.
{
    assert(s >= 0 && s < getSampleCount());
    assert(m_buffer);
    const T *sample = samples() + s;
    assert(sample);
    return sample->getPressure(chan);
  }
isSampleSigned()
template<class T > bool TSoundTrackT< T >::isSampleSigned () const inline override virtual
Returns true if the samples of the soundtrack are signed, false otherwise.
Implements TSoundTrack.
{ return T::isSampleSigned(); }
samples() [1/2]
template<class T > T * TSoundTrackT< T >::samples () inline
Returns the samples array.
{ return reinterpret_cast<T *>(m_buffer); }
samples() [2/2]
template<class T > const T * TSoundTrackT< T >::samples () const inline
Returns the const samples array.
{ return reinterpret_cast<T *>(m_buffer); }
Referenced by TSoundTrackT< T >::clone(), TSoundTrackT< T >::copy(), and TSoundTrackT< T >::copyChannel().
The documentation for this class was generated from the following file:
E:/opentoonz/toonz/sources/include/tsound_t.h