opentoonz: OutputSettingsPopup Class Reference
OutputSettingsPopup Class Reference
The OutputSettingsPopup class provides a output settings dialog.
Public Member Functions
OutputSettingsPopup (bool isPreview=false)
Public Member Functions inherited from DVGui::Dialog
Dialog (QWidget *parent=0, bool hasButton=false, bool hasFixedSize=true, const QString &name=QString())
void beginVLayout ()
void endVLayout ()
void beginHLayout ()
void endHLayout ()
void addWidget (QWidget *widget, bool isRight=true)
void addWidgets (QWidget *firstW, QWidget *secondW)
void addWidget (QString labelName, QWidget *widget)
void addLayout (QLayout *layout, bool isRight=true)
void addWidgetLayout (QWidget *widget, QLayout *layout)
void addLayout (QString labelName, QLayout *layout)
void addLayouts (QLayout *firstL, QLayout *secondL)
void addSpacing (int spacing)
void addSeparator (QString name=QString())
void setAlignment (Qt::Alignment alignment)
void setTopMargin (int margin)
void setTopSpacing (int spacing)
void setLabelWidth (int labelWidth)
int getLabelWidth () const
void setLayoutInsertedSpacing (int spacing)
int getLayoutInsertedSpacing ()
void setButtonBarMargin (int margin)
void setButtonBarSpacing (int spacing)
void addButtonBarWidget (QWidget *widget)
void addButtonBarWidget (QWidget *first, QWidget *second)
void addButtonBarWidget (QWidget *first, QWidget *second, QWidget *third)
void addButtonBarWidget (QWidget *first, QWidget *second, QWidget *third, QWidget *fourth)
void hideEvent (QHideEvent *event) override
void clearButtonBar ()
Protected Slots
void updateField ()
void onPathChanged ()
void onNameChanged ()
void onFormatChanged (const QString &str)
void openSettingsPopup ()
void onCameraChanged (const QString &str)
void onFrameFldEditFinished ()
void onResampleChanged (int type)
void onChannelWidthChanged (int type)
void onGammaFldEditFinished ()
void onDominantFieldChanged (int type)
void onStretchFldEditFinished ()
void onApplyShrinkChecked (int state)
void onSubcameraChecked (int state)
void onMultimediaChanged (int mode)
void onThreadsComboChanged (int type)
void onRasterGranularityChanged (int type)
void onStereoChecked (int)
void onStereoChanged ()
void onRenderClicked ()
void onAddPresetButtonPressed ()
void onRemovePresetButtonPressed ()
void onPresetSelected (const QString &)
void onCameraSettingsChanged ()
void onFrameRateEditingFinished ()
void onAddBoardChecked (int state)
void onBoardSettingsBtnClicked ()
void onCategoryActivated (QListWidgetItem *)
Protected Member Functions
ToonzScene * getCurrentScene () const
TOutputProperties * getProperties () const
void showEvent (QShowEvent *) override
void hideEvent (QHideEvent *) override
bool eventFilter (QObject *, QEvent *) override
Protected Member Functions inherited from DVGui::Dialog
void resizeEvent (QResizeEvent *e) override
Additional Inherited Members
Signals inherited from DVGui::Dialog
void dialogClosed ()
Public Attributes inherited from DVGui::Dialog
QVBoxLayout * m_topLayout
QFrame * m_mainFrame
QFrame * m_buttonFrame
QHBoxLayout * m_mainHLayout
bool m_isMainHLayout
QVBoxLayout * m_leftVLayout
QVBoxLayout * m_rightVLayout
bool m_isMainVLayout
int m_layoutSpacing
int m_layoutMargin
int m_labelWidth
std::vector< QWidget * > m_buttonBarWidgets
Protected Attributes inherited from DVGui::Dialog
QHBoxLayout * m_buttonLayout
QList< QLabel * > m_labelList
Detailed Description
The OutputSettingsPopup class provides a output settings dialog.
         Inherits \b Dialog.
         This class allows to set output properties of current scene.
         It's composed of a list of field to set this preperties:
         a \b DVGui::FileField to set output directory, a LineEdit for
output name, a QComboBox to choose format, a button near QComboBox that open a popup to change format chosen settings, other QComboBox to choose camera, resample balance, channel width and dominant field and other number field to set values for frame and time stretch.
Constructor & Destructor Documentation
OutputSettingsPopup()
OutputSettingsPopup::OutputSettingsPopup (bool isPreview = false)
    : Dialog(TApp::instance()->getMainWindow(), false, isPreview,
             isPreview ? "PreviewSettings" : "OutputSettings")
    , m_subcameraChk(nullptr)
    , m_applyShrinkChk(nullptr)
    , m_outputCameraOm(nullptr)
    , m_isPreviewSettings(isPreview)
    , m_allowMT(Preferences::instance()->getFfmpegMultiThread())
    , m_presetCombo(nullptr) {
  setWindowTitle(isPreview ? tr("Preview Settings") : tr("Output Settings"));
  if (!isPreview) setObjectName("OutputSettingsPopup");
  // create panel
  QFrame *panel = createPanel(isPreview);
  // preview settings
  if (isPreview) {
    m_topLayout->setMargin(5);
    m_topLayout->addWidget(panel, 0);
    return;
  }
  // outputsettings with category list & scrollable panel
  QPushButton *addPresetButton    = new QPushButton(tr("Add"), this);
  QPushButton *removePresetButton = new QPushButton(tr("Remove"), this);
  m_presetCombo                   = new QComboBox(this);
  addPresetButton->setObjectName("PushButton_NoPadding");
  removePresetButton->setObjectName("PushButton_NoPadding");
  QString tooltip =
      tr("Save current output settings.\nThe parameters to be saved are:\n- "
         "Camera settings\n- Project folder to be saved in\n- File format\n- "
         "File options\n- Resample Balance\n- Channel width");
  addPresetButton->setToolTip(tooltip);
  /*-- プリセットフォルダを調べ、コンボボックスにアイテムを格納する --*/
  updatePresetComboItems();
  QListWidget *categoryList = new QListWidget(this);
  QStringList categories;
  categories << tr("Camera") << tr("File") << tr("More");
  categoryList->addItems(categories);
  categoryList->setFixedWidth(100);
  categoryList->setCurrentRow(0);
  m_scrollArea = new QScrollArea(this);
  m_scrollArea->setWidgetResizable(true);
  m_scrollArea->setWidget(panel);
  QPushButton *renderButton = new QPushButton(tr("Render"), this);
  renderButton->setIcon(createQIcon("render"));
  renderButton->setIconSize(QSize(20, 20));
  renderButton->setFixedWidth(200);
  m_topLayout->setMargin(5);
  {
    QHBoxLayout *presetLay = new QHBoxLayout();
    presetLay->setMargin(0);
    presetLay->setSpacing(5);
    {
      presetLay->addStretch(1);
      presetLay->addWidget(new QLabel(tr("Presets:"), this), 1,
                           Qt::AlignRight | Qt::AlignVCenter);
      presetLay->addWidget(m_presetCombo, 1);
      presetLay->addWidget(addPresetButton, 0);
      presetLay->addWidget(removePresetButton, 0);
    }
    m_topLayout->addLayout(presetLay, 0);
    QHBoxLayout *middleLay = new QHBoxLayout();
    middleLay->setMargin(0);
    middleLay->setSpacing(5);
    {
      middleLay->addWidget(categoryList, 0);
      middleLay->addWidget(m_scrollArea, 1);
    }
    m_topLayout->addLayout(middleLay, 1);
    m_topLayout->addSpacing(5);
    m_topLayout->addWidget(renderButton, 0, Qt::AlignCenter);
  }
  bool ret = true;
  ret      = ret &&
        connect(renderButton, SIGNAL(pressed()), this, SLOT(onRenderClicked()));
  ret = ret && connect(addPresetButton, SIGNAL(pressed()), this,
                       SLOT(onAddPresetButtonPressed()));
  ret = ret && connect(removePresetButton, SIGNAL(pressed()), this,
                       SLOT(onRemovePresetButtonPressed()));
  ret = ret && connect(m_presetCombo, SIGNAL(activated(const QString &)), this,
                       SLOT(onPresetSelected(const QString &)));
  ret = ret && connect(categoryList, SIGNAL(itemClicked(QListWidgetItem *)),
                       this, SLOT(onCategoryActivated(QListWidgetItem *)));
  assert(ret);
}
Member Function Documentation
eventFilter()
bool OutputSettingsPopup::eventFilter (QObject * obj, QEvent * e) override protected
{
  if (e->type() == QEvent::Wheel) {
    QComboBox *combo = qobject_cast<QComboBox *>(obj);
    if (combo && !combo->hasFocus()) return true;
  }
  return QObject::eventFilter(obj, e);
}
getCurrentScene()
ToonzScene * OutputSettingsPopup::getCurrentScene () const protected
Return current ToonzScene scene.
{
  ToonzScene *scene = TApp::instance()->getCurrentScene()->getScene();
  return scene;
}
References TApp::getCurrentScene(), and TApp::instance().
Referenced by getProperties(), onCameraChanged(), onChannelWidthChanged(), onDominantFieldChanged(), onGammaFldEditFinished(), onNameChanged(), onPathChanged(), onResampleChanged(), onStretchFldEditFinished(), and updateField().
getProperties()
TOutputProperties * OutputSettingsPopup::getProperties () const protected
Return current scene output properties TOutputProperties, if current scene is not empty.
{
  ToonzScene *scene = getCurrentScene();
  if (!scene) return 0;
  return m_isPreviewSettings ? scene->getProperties()->getPreviewProperties()
                             : scene->getProperties()->getOutputProperties();
}
References getCurrentScene(), TSceneProperties::getOutputProperties(), TSceneProperties::getPreviewProperties(), and ToonzScene::getProperties().
Referenced by onAddPresetButtonPressed(), onChannelWidthChanged(), onDominantFieldChanged(), onFormatChanged(), onGammaFldEditFinished(), onNameChanged(), onPathChanged(), onResampleChanged(), onStretchFldEditFinished(), openSettingsPopup(), and updateField().
hideEvent()
void OutputSettingsPopup::hideEvent (QHideEvent * e) override protected
{
  TSceneHandle *sceneHandle   = TApp::instance()->getCurrentScene();
  TXsheetHandle *xsheetHandle = TApp::instance()->getCurrentXsheet();
  bool ret = disconnect(sceneHandle, SIGNAL(sceneChanged()), this,
                        SLOT(updateField()));
  ret      = ret && disconnect(sceneHandle, SIGNAL(sceneSwitched()), this,
                          SLOT(updateField()));
  ret = ret && disconnect(xsheetHandle, SIGNAL(xsheetChanged()), this,
                          SLOT(updateField()));
  assert(ret);
  Dialog::hideEvent(e);
}
onAddBoardChecked
void OutputSettingsPopup::onAddBoardChecked (int state) protected slot
{
  BoardSettings *boardSettings = getProperties()->getBoardSettings();
  boardSettings->setActive(state == Qt::Checked);
  m_boardSettingsBtn->setEnabled(state == Qt::Checked);
}
onAddPresetButtonPressed
void OutputSettingsPopup::onAddPresetButtonPressed () protected slot
OutputSettingsのPreset登録
{
  //*-- プリセット名を取得 --*/
  bool ok;
  QString qs = DVGui::getText(
      tr("Add preset"), tr("Enter the name for the output settings preset."),
      "", &ok);
  if (!ok || qs.isEmpty()) return;
  if (!qs.endsWith(".txt")) qs.append(".txt");
  TFilePath fp = TEnv::getConfigDir() + "outputpresets";
  if (!TFileStatus(fp).doesExist()) TSystem::mkDir(fp);
  fp = fp + qs.toStdString();
  /*-- すでに存在する場合、上書きを確認 --*/
  if (TFileStatus(fp).doesExist()) {
    int ret = QMessageBox::question(
        this, tr("Add output settings preset"),
        QString("The file %1 does already exist.\nDo you want to overwrite it?")
            .arg(qs),
        QMessageBox::Save | QMessageBox::Cancel, QMessageBox::Save);
    if (ret == QMessageBox::Cancel) return;
  }
  TSystem::touchFile(fp);
  TOStream os(fp, false);
  if (!os.checkStatus()) return;
  os.openChild("outputsettingspreset");
  /*-- カメラ設定 --*/
  os.openChild("camera");
  TXsheet *xsheet         = TApp::instance()->getCurrentXsheet()->getXsheet();
  TStageObjectId cameraId = xsheet->getStageObjectTree()->getCurrentCameraId();
  TCamera *camera         = xsheet->getStageObject(cameraId)->getCamera();
  camera->saveData(os);
  os.closeChild();
  /*--  Saveinのプロジェクトフォルダ部分 --*/
  QString saveInPath = m_saveInFileFld->getPath();
  if (saveInPath.startsWith("+")) {
    QString projectFolderName = (saveInPath.contains("\\"))
                                    ? saveInPath.left(saveInPath.indexOf("\\"))
                                    : saveInPath;
    os.child("savein_projectfolder") << projectFolderName.toStdString();
  }
  /*-- ファイル形式 --*/
  QString format = m_fileFormat->currentText();
  os.child("format") << format.toStdString();
  TOutputProperties *prop = getProperties();
  /*-- ファイルオプション --*/
  os.openChild("formatsProperties");
  std::vector<std::string> fileExtensions;
  prop->getFileFormatPropertiesExtensions(fileExtensions);
  for (int i = 0; i < (int)fileExtensions.size(); i++) {
    std::string ext    = fileExtensions[i];
    TPropertyGroup *pg = prop->getFileFormatProperties(ext);
    assert(pg);
    std::map<std::string, std::string> attr;
    attr["ext"] = ext;
    os.openChild("formatProperties", attr);
    pg->saveData(os);
    os.closeChild();
  }
  os.closeChild();
  // Resample Balance
  QString resq =
      resampleInfoMap[(ResampleOption)m_resampleBalanceOm->currentIndex()]
          .idString;
  os.child("resquality") << resq.toStdString();
  // Channel Width
  QString chanw = m_channelWidthOm->currentData().toString();
  os.child("bpp") << chanw.toStdString();
  // 140503 iwasawa Frame Rate (Scene Settings)
  os.child("frameRate") << m_frameRateFld->text().toStdString();
  // 140325 iwasawa stretch FPS
  os.child("stretchFrom") << m_stretchFromFld->text().toStdString();
  os.child("stretchTo") << m_stretchToFld->text().toStdString();
  // 140325 iwasawa gamma
  os.child("gamma") << m_gammaFld->text().toStdString();
  os.closeChild();  // outputsettingspreset
  m_presetCombo->blockSignals(true);
  updatePresetComboItems();
  m_presetCombo->setCurrentIndex(
      m_presetCombo->findText(QString::fromStdString(fp.getName())));
  m_presetCombo->blockSignals(false);
}
References TOStream::checkStatus(), TOStream::child(), TOStream::closeChild(), TStageObject::getCamera(), TStageObjectTree::getCurrentCameraId(), TApp::getCurrentXsheet(), TOutputProperties::getFileFormatProperties(), TOutputProperties::getFileFormatPropertiesExtensions(), TFilePath::getName(), getProperties(), TXsheet::getStageObject(), TXsheet::getStageObjectTree(), TApp::instance(), and TOStream::openChild().
onApplyShrinkChecked
void OutputSettingsPopup::onApplyShrinkChecked (int state) protected slot
{
  TRenderSettings rs       = getProperties()->getRenderSettings();
  rs.m_applyShrinkToViewer = (state == Qt::Checked);
  getProperties()->setRenderSettings(rs);
}
onBoardSettingsBtnClicked
void OutputSettingsPopup::onBoardSettingsBtnClicked () protected slot
{
  std::cout << "board settings button clicked" << std::endl;
  BoardSettingsPopup popup(this);
  popup.exec();
}
onCameraChanged
void OutputSettingsPopup::onCameraChanged (const QString & str) protected slot
Set current scene output camera to camera set in popup field.
{
  ToonzScene *scene = getCurrentScene();
  if (!scene) return;
  TStageObjectTree *tree = scene->getXsheet()->getStageObjectTree();
  int cameraCount        = tree->getCameraCount();
  /*-- 注：CameraCountはDeleteされたCameraは入らないがIndexは欠番になる。
          ので、CameraCountとIndexの最大値は必ずしも一致しない
  --*/
  int tmpCameraId = 0;
  int i;
  for (i = 0; i < cameraCount;) {
    if (!tree->getStageObject(TStageObjectId::CameraId(tmpCameraId), false)) {
      tmpCameraId++;
      continue;
    }
    std::string name =
        tree->getStageObject(TStageObjectId::CameraId(tmpCameraId))->getName();
    if (name == str.toStdString()) break;
    tmpCameraId++;
    i++;
  }
  if (i >= cameraCount) return;
  TApp *app                      = TApp::instance();
  TStageObjectId cameraId        = TStageObjectId::CameraId(i);
  TStageObjectId currentCameraId = m_isPreviewSettings
                                       ? tree->getCurrentPreviewCameraId()
                                       : tree->getCurrentCameraId();
  if (currentCameraId != cameraId) {
    TXsheetHandle *xsheetHandle = app->getCurrentXsheet();
    disconnect(xsheetHandle, SIGNAL(xsheetChanged()), this,
               SLOT(updateField()));
    if (m_isPreviewSettings)
      tree->setCurrentPreviewCameraId(cameraId);
    else
      tree->setCurrentCameraId(cameraId);
    app->getCurrentScene()->setDirtyFlag(true);
    xsheetHandle->notifyXsheetChanged();
    connect(xsheetHandle, SIGNAL(xsheetChanged()), this, SLOT(updateField()));
  }
  if (m_presetCombo) m_presetCombo->setCurrentIndex(0);
}
References TStageObjectTree::getCameraCount(), TStageObjectTree::getCurrentCameraId(), getCurrentScene(), TApp::getCurrentScene(), TApp::getCurrentXsheet(), TStageObjectTree::getStageObject(), TXsheet::getStageObjectTree(), ToonzScene::getXsheet(), TApp::instance(), TStageObjectTree::setCurrentCameraId(), and updateField().
onCameraSettingsChanged
void OutputSettingsPopup::onCameraSettingsChanged () protected slot
{
  if (m_presetCombo) m_presetCombo->setCurrentIndex(0);
}
onCategoryActivated
void OutputSettingsPopup::onCategoryActivated (QListWidgetItem * item) protected slot
{
  AnimatedLabel *label;
  QFrame *frame;
  if (item->text() == tr("Camera")) {
    label = m_cameraLabel;
    frame = m_cameraBox;
  } else if (item->text() == tr("File")) {
    label = m_fileLabel;
    frame = m_fileBox;
  } else if (item->text() == tr("More")) {
    label = m_moreLabel;
    frame = m_moreBox;
  } else
    return;
  m_scrollArea->ensureWidgetVisible(frame);
  QPropertyAnimation *a = new QPropertyAnimation(label, "color");
  a->setDuration(1000);
  a->setStartValue(QColor(255, 255, 0, 128));
  a->setEndValue(QColor(255, 255, 0, 0));
  a->setEasingCurve(QEasingCurve::OutBack);
  a->start(QPropertyAnimation::DeleteWhenStopped);
}
onChannelWidthChanged
void OutputSettingsPopup::onChannelWidthChanged (int type) protected slot
Set current scene output channel width to value identified by type index in popup QComboBox.
{
  if (!getCurrentScene()) return;
  TOutputProperties *prop = getProperties();
  TRenderSettings rs      = prop->getRenderSettings();
  if (type == c_8bit)
    rs.m_bpp = 32;
  else
    rs.m_bpp = 64;
  prop->setRenderSettings(rs);
  TApp::instance()->getCurrentScene()->setDirtyFlag(true);
  if (m_presetCombo) m_presetCombo->setCurrentIndex(0);
}
References getCurrentScene(), TApp::getCurrentScene(), getProperties(), TOutputProperties::getRenderSettings(), TApp::instance(), TRenderSettings::m_bpp, and TOutputProperties::setRenderSettings().
onDominantFieldChanged
void OutputSettingsPopup::onDominantFieldChanged (int type) protected slot
Set current scene output dominant field to value identified by type index in popup QComboBox. If time stretch velue from-to are different and dominant field is different from none show a message error.
{
  if (!getCurrentScene()) return;
  TOutputProperties *prop = getProperties();
  TRenderSettings rs      = prop->getRenderSettings();
  if (type != c_none &&
      m_stretchFromFld->getValue() != m_stretchToFld->getValue()) {
    DVGui::error("Can't apply field rendering in a time stretched scene");
    rs.m_fieldPrevalence = TRenderSettings::NoField;
    m_dominantFieldOm->setCurrentIndex(c_none);
  } else if (type == c_odd)
    rs.m_fieldPrevalence = TRenderSettings::OddField;
  else if (type == c_even)
    rs.m_fieldPrevalence = TRenderSettings::EvenField;
  else
    rs.m_fieldPrevalence = TRenderSettings::NoField;
  m_doStereoscopy->setEnabled(rs.m_fieldPrevalence == TRenderSettings::NoField);
  m_stereoShift->setEnabled(rs.m_fieldPrevalence == TRenderSettings::NoField);
  prop->setRenderSettings(rs);
  TApp::instance()->getCurrentScene()->setDirtyFlag(true);
}
References TRenderSettings::EvenField, getCurrentScene(), TApp::getCurrentScene(), getProperties(), TOutputProperties::getRenderSettings(), DVGui::DoubleLineEdit::getValue(), TApp::instance(), TRenderSettings::m_fieldPrevalence, TRenderSettings::NoField, TRenderSettings::OddField, and TOutputProperties::setRenderSettings().
onFormatChanged
void OutputSettingsPopup::onFormatChanged (const QString & str) protected slot
Set current scene output format to new format set in popup field.
{
  auto isMultiRenderInvalid = [](std::string ext, bool allowMT) -> bool {
    return (!allowMT && (ext == "mp4" || ext == "gif" || ext == "webm")) ||
           ext == "spritesheet";
  };
  TOutputProperties *prop    = getProperties();
  bool wasMultiRenderInvalid =
      isMultiRenderInvalid(prop->getPath().getType(), m_allowMT);
  TFilePath fp = prop->getPath().withType(str.toStdString());
  prop->setPath(fp);
  TApp::instance()->getCurrentScene()->setDirtyFlag(true);
  m_allowMT = Preferences::instance()->getFfmpegMultiThread();
  if (m_presetCombo) m_presetCombo->setCurrentIndex(0);
  if (isMultiRenderInvalid(str.toStdString(), m_allowMT)) {
    m_threadsComboOm->setDisabled(true);
    m_threadsComboOm->setCurrentIndex(0);
  } else {
    m_threadsComboOm->setDisabled(false);
    if (wasMultiRenderInvalid) m_threadsComboOm->setCurrentIndex(2);
  }
  // clapperboard is only available with movie formats
  if (isMovieType(str.toStdString())) {
    m_addBoard->setEnabled(true);
    m_boardSettingsBtn->setEnabled(m_addBoard->isChecked());
  } else {
    m_addBoard->setEnabled(false);
    m_boardSettingsBtn->setEnabled(false);
  }
}
References TApp::getCurrentScene(), TOutputProperties::getPath(), getProperties(), TFilePath::getType(), TApp::instance(), TOutputProperties::setPath(), and TFilePath::withType().
Referenced by updateField().
onFrameFldEditFinished
void OutputSettingsPopup::onFrameFldEditFinished () protected slot
{
  ToonzScene *scene = getCurrentScene();
  if (!scene) return;
  TOutputProperties *prop = getProperties();
  int maxR0  = std::max(0, scene->getFrameCount() - 1);
  int r0     = (int)m_startFld->getValue() - 1;
  int r1     = (int)m_endFld->getValue() - 1;
  int step   = (int)m_stepFld->getValue();
  int shrink = (int)m_shrinkFld->getValue();
  bool error = false;
  if (r0 < 0) {
    error = true;
    r0    = 0;
  }
  if (r0 > maxR0) {
    error = true;
    r0    = maxR0;
  }
  if (r1 < r0) {
    error = true;
    r1    = r0;
  }
  if (r1 > maxR0) {
    error = true;
    r1    = maxR0;
  }
  if (error) {
    m_startFld->setValue(r0 + 1);
    m_endFld->setValue(r1 + 1);
  }
  if (step < 1) {
    step = 1;
    m_stepFld->setValue(step);
  }
  if (shrink < 1) {
    shrink = 1;
    m_shrinkFld->setValue(shrink);
  }
  if (r0 == 0 && r1 == maxR0) {
    r0 = 0;
    r1 = -1;
  }
  prop->setRange(r0, r1, step);
  TRenderSettings rs = prop->getRenderSettings();
  rs.m_shrinkX = rs.m_shrinkY = shrink;
  rs.m_applyShrinkToViewer =
      m_applyShrinkChk ? m_applyShrinkChk->checkState() == Qt::Checked : false;
  prop->setRenderSettings(rs);
  TApp::instance()->getCurrentScene()->setDirtyFlag(true);
}
onFrameRateEditingFinished
void OutputSettingsPopup::onFrameRateEditingFinished () protected slot
{
  double frameRate         = getProperties()->getFrameRate();
  double frameRateFldValue = m_frameRateFld->getValue();
  if (frameRate == frameRateFldValue) return;
  getProperties()->setFrameRate(frameRateFldValue);
  TApp::instance()->getCurrentScene()->getScene()->updateSoundColumnFrameRate();
  TApp::instance()->getCurrentScene()->notifySceneChanged();
  TApp::instance()->getCurrentXsheet()->getXsheet()->updateFrameCount();
  TApp::instance()->getCurrentXsheet()->notifyXsheetChanged();
}
onGammaFldEditFinished
void OutputSettingsPopup::onGammaFldEditFinished () protected slot
Set current scene output gamma value to current value in popup gamma field.
{
  if (!getCurrentScene()) return;
  TOutputProperties *prop = getProperties();
  double gamma = m_gammaFld->getValue();
  m_gammaFld->setCursorPosition(0);
  if (gamma <= 0) {
    gamma = 0.001;
    m_gammaFld->setValue(gamma);
  }
  TRenderSettings rs = prop->getRenderSettings();
  rs.m_gamma         = gamma;
  prop->setRenderSettings(rs);
  TApp::instance()->getCurrentScene()->setDirtyFlag(true);
}
References getCurrentScene(), TApp::getCurrentScene(), getProperties(), TOutputProperties::getRenderSettings(), DVGui::DoubleLineEdit::getValue(), TApp::instance(), TRenderSettings::m_gamma, TOutputProperties::setRenderSettings(), and DVGui::DoubleLineEdit::setValue().
onMultimediaChanged
void OutputSettingsPopup::onMultimediaChanged (int mode) protected slot
{
  if (!getCurrentScene()) return;
  TOutputProperties *prop = getProperties();
  prop->setMultimediaRendering(state);
  TApp::instance()->getCurrentScene()->setDirtyFlag(true);
}
onNameChanged
void OutputSettingsPopup::onNameChanged () protected slot
Set current scene output name to new name modified in popup field.
{
  ToonzScene *scene = getCurrentScene();
  if (!scene) return;
  QString name = m_fileNameFld->text();
  if (!isValidFileName(name)) {
    DVGui::error(
        "A filename cannot be empty or contain any of the following "
        "characters:\n \\ / : * ? \" < > |");
    TOutputProperties *prop = getProperties();
    TFilePath fp            = prop->getPath();
    QString name            = QString::fromStdString(fp.getName());
    if (name.isEmpty())
      name = QString::fromStdString(scene->getScenePath().getName());
    m_fileNameFld->setText(name);
    return;
  }
  if (isReservedFileName_message(name)) {
    TOutputProperties *prop = getProperties();
    TFilePath fp            = prop->getPath();
    QString name            = QString::fromStdString(fp.getName());
    if (name.isEmpty())
      name = QString::fromStdString(scene->getScenePath().getName());
    m_fileNameFld->setText(name);
    return;
  }
  std::wstring wname = name.toStdWString();
  {
    // It could be possible that users add an extension to the level name.
    // This is not supported, and the extension must be removed.
    // Observe that leaving wname as is WOULD be a bug (see Bugzilla #6578).
    const std::wstring &actualWName = TFilePath(wname).getWideName();
    if (wname != actualWName) {
      wname = actualWName;
      m_fileNameFld->setText(QString::fromStdWString(wname));
    }
  }
  // In case the output level name is reverted back to the scene name, we assume
  // that
  // a "Save Scene As..." command should move the value to the *new* scene name
  if (wname == scene->getScenePath().getWideName())
    wname = std::wstring();  // An empty name is redirected to the scene name
  // directly by the render procedure, let's use this!
  TOutputProperties *prop = getProperties();
  TFilePath fp            = prop->getPath();
  if (fp.getWideName() == wname) return;  // Already had the right name
  fp = fp.withName(wname);
  prop->setPath(fp);
  TApp::instance()->getCurrentScene()->setDirtyFlag(true);
  if (m_presetCombo) m_presetCombo->setCurrentIndex(0);
}
References getCurrentScene(), TApp::getCurrentScene(), TFilePath::getName(), TOutputProperties::getPath(), getProperties(), ToonzScene::getScenePath(), TApp::instance(), TOutputProperties::setPath(), and TFilePath::withName().
onPathChanged
void OutputSettingsPopup::onPathChanged () protected slot
Set current scene output path to new path modified in popup field.
{
  if (!getCurrentScene()) return;
  QString text = m_saveInFileFld->getPath();
  TFilePath newFp(text.toStdWString());
  newFp = TApp::instance()->getCurrentScene()->getScene()->codeFilePath(newFp);
  m_saveInFileFld->setPath(QString::fromStdWString(newFp.getWideString()));
  TOutputProperties *prop = getProperties();
  TFilePath fp            = prop->getPath();
  if (fp == newFp) return;
  fp = fp.withParentDir(newFp);
  prop->setPath(fp);
  TApp::instance()->getCurrentScene()->setDirtyFlag(true);
  if (m_presetCombo) m_presetCombo->setCurrentIndex(0);
}
References ToonzScene::codeFilePath(), getCurrentScene(), TApp::getCurrentScene(), TOutputProperties::getPath(), getProperties(), TApp::instance(), TOutputProperties::setPath(), and TFilePath::withParentDir().
onPresetSelected
void OutputSettingsPopup::onPresetSelected (const QString & str) protected slot
{
  /*-- "<custom>"を選択したら何もせずreturn --*/
  if (m_presetCombo->currentIndex() == 0) return;
  TFilePath fp = TEnv::getConfigDir() + "outputpresets" +
                 QString("%1.txt").arg(str).toStdString();
  if (!TFileStatus(fp).doesExist()) {
    QMessageBox::warning(this, tr("Warning"),
                         QString("The preset file %1.txt not found").arg(str),
                         QMessageBox::Ok, QMessageBox::Ok);
    return;
  }
  TIStream is(fp);
  if (!is) {
    QMessageBox::warning(
        this, tr("Warning"),
        QString("Failed to open the preset file %1.txt").arg(str),
        QMessageBox::Ok, QMessageBox::Ok);
    return;
  }
  std::string tagName = "";
  if (!is.matchTag(tagName) || tagName != "outputsettingspreset") {
    QMessageBox::warning(this, tr("Warning"),
                         QString("Bad file format: %1.txt").arg(str),
                         QMessageBox::Ok, QMessageBox::Ok);
    return;
  }
  TOutputProperties *prop = getProperties();
  TRenderSettings rs      = prop->getRenderSettings();
  while (is.matchTag(tagName)) {
    // Camera
    if (tagName == "camera") {
      TXsheet *xsheet = TApp::instance()->getCurrentXsheet()->getXsheet();
      TStageObjectId cameraId =
          xsheet->getStageObjectTree()->getCurrentCameraId();
      TCamera *camera = xsheet->getStageObject(cameraId)->getCamera();
      camera->loadData(is);
    }  // if "camera"
    /*-- Saveinのプロジェクトフォルダ部分 --*/
    else if (tagName == "savein_projectfolder") {
      std::string projectFolderName;
      is >> projectFolderName;
      QString newProjectFolder = QString::fromStdString(projectFolderName);
      QString fp = QString::fromStdWString(prop->getPath().getWideString());
      /*-- 出力パスがプロジェクトフォルダで始まっている場合は、差し替える --*/
      if (!newProjectFolder.isEmpty() && fp.startsWith("+")) {
        if (fp.indexOf("\\") >= 0)
          fp = QString("%1\\%2")
                   .arg(newProjectFolder)
                   .arg(fp.right(fp.size() - fp.indexOf("\\") - 1));
        else
          fp = newProjectFolder;
        prop->setPath(TFilePath(fp.toStdWString()));
      }
    }
    // File format
    else if (tagName == "format") {
      std::string formatName;
      is >> formatName;
      TFilePath fp = prop->getPath().withType(formatName);
      prop->setPath(fp);
    }
    // File options
    else if (tagName == "formatsProperties") {
      while (is.matchTag(tagName)) {
        if (tagName == "formatProperties") {
          std::string ext    = is.getTagAttribute("ext");
          TPropertyGroup *pg = prop->getFileFormatProperties(ext);
          if (ext == "avi") {
            TPropertyGroup appProperties;
            appProperties.loadData(is);
            if (pg->getPropertyCount() != 1 ||
                appProperties.getPropertyCount() != 1) {
              is.closeChild();
              continue;
            }
            TEnumProperty *enumProp =
                dynamic_cast<TEnumProperty *>(pg->getProperty(0));
            TEnumProperty *enumAppProp =
                dynamic_cast<TEnumProperty *>(appProperties.getProperty(0));
            assert(enumAppProp && enumProp);
            if (enumAppProp && enumProp) {
              try {
                enumProp->setValue(enumAppProp->getValue());
              } catch (TProperty::RangeError &) {
              }
            } else
              throw TException();
          } else
            pg->loadData(is);
          is.closeChild();
        } else
          throw TException("unexpected tag: " + tagName);
      }  // end while
    }
    // Resample Balance
    else if (tagName == "resquality") {
      std::string resq;
      is >> resq;
      // first, search in the combobox item data.
      int index = m_resampleBalanceOm->findData(QString::fromStdString(resq));
      // second, search in the combobox ui text (which may be translated).
      // the second search is kept in order to keep backward compatibility.
      if (index < 0)
        index = m_resampleBalanceOm->findText(QString::fromStdString(resq));
      if (index >= 0) {
        m_resampleBalanceOm->setCurrentIndex(index);
        rs.m_quality = resampleInfoMap[(ResampleOption)index].quality;
      }
    }
    // Channel Width
    else if (tagName == "bpp") {
      std::string chanw;
      is >> chanw;
      // first, search in the combobox item data.
      int index = m_channelWidthOm->findData(QString::fromStdString(chanw));
      // second, search in the combobox ui text (which may be translated).
      // the second search is kept in order to keep backward compatibility.
      if (index < 0)
        index = m_channelWidthOm->findText(QString::fromStdString(chanw));
      if (index >= 0) {
        m_channelWidthOm->setCurrentIndex(index);
        if (index == c_8bit)
          rs.m_bpp = 32;
        else
          rs.m_bpp = 64;
      }
    }
    // Frame Rate (Scene Settings)
    else if (tagName == "frameRate") {
      std::string strFps;
      is >> strFps;
      prop->setFrameRate(QString::fromStdString(strFps).toDouble());
    }
    // stretch FPS
    else if (tagName == "stretchFrom") {
      std::string strFrm;
      is >> strFrm;
      rs.m_timeStretchFrom = QString::fromStdString(strFrm).toDouble();
    } else if (tagName == "stretchTo") {
      std::string strTo;
      is >> strTo;
      rs.m_timeStretchTo = QString::fromStdString(strTo).toDouble();
    }
    // gamma
    else if (tagName == "gamma") {
      std::string gamma;
      is >> gamma;
      rs.m_gamma = QString::fromStdString(gamma).toDouble();
    }
    is.closeChild();
  }
  /*-- renderSettingsを戻す --*/
  prop->setRenderSettings(rs);
  TApp::instance()->getCurrentScene()->notifySceneChanged();
  m_presetCombo->blockSignals(true);
  m_presetCombo->setCurrentIndex(m_presetCombo->findText(str));
  m_presetCombo->blockSignals(false);
}
onRasterGranularityChanged
void OutputSettingsPopup::onRasterGranularityChanged (int type) protected slot
{
  if (!getCurrentScene()) return;
  TOutputProperties *prop = getProperties();
  prop->setMaxTileSizeIndex(type);
  TApp::instance()->getCurrentScene()->setDirtyFlag(true);
}
onRemovePresetButtonPressed
void OutputSettingsPopup::onRemovePresetButtonPressed () protected slot
OutputSettingsのPreset削除
{
  int index = m_presetCombo->currentIndex();
  if (index <= 0) return;
  int ret = QMessageBox::question(this, tr("Remove preset"),
                                  QString("Deleting \"%1\".\nAre you sure?")
                                      .arg(m_presetCombo->currentText()),
                                  QMessageBox::Ok | QMessageBox::Cancel,
                                  QMessageBox::Ok);
  if (ret == QMessageBox::Cancel) return;
  TFilePath fp =
      TEnv::getConfigDir() + "outputpresets" +
      QString("%1.txt").arg(m_presetCombo->currentText()).toStdString();
  if (TFileStatus(fp).doesExist()) TSystem::deleteFile(fp);
  m_presetCombo->blockSignals(true);
  m_presetCombo->removeItem(index);
  m_presetCombo->setCurrentIndex(0);
  m_presetCombo->blockSignals(false);
}
onRenderClicked
void OutputSettingsPopup::onRenderClicked () protected slot
{
  CommandManager::instance()->execute("MI_Render");
}
onResampleChanged
void OutputSettingsPopup::onResampleChanged (int type) protected slot
Set current scene output resample balance to balance identified by type index in popup QComboBox.
{
  if (!getCurrentScene()) return;
  TOutputProperties *prop = getProperties();
  TRenderSettings rs      = prop->getRenderSettings();
  rs.m_quality = resampleInfoMap[(ResampleOption)type].quality;
  prop->setRenderSettings(rs);
  TApp::instance()->getCurrentScene()->setDirtyFlag(true);
  if (m_presetCombo) m_presetCombo->setCurrentIndex(0);
}
References getCurrentScene(), TApp::getCurrentScene(), getProperties(), TOutputProperties::getRenderSettings(), TApp::instance(), TRenderSettings::m_quality, and TOutputProperties::setRenderSettings().
onStereoChanged
void OutputSettingsPopup::onStereoChanged () protected slot
{
  TOutputProperties *prop = getProperties();
  TRenderSettings rs      = prop->getRenderSettings();
  rs.m_stereoscopic       = m_doStereoscopy->isChecked();
  rs.m_stereoscopicShift  = m_stereoShift->getValue();
  prop->setRenderSettings(rs);
}
onStereoChecked
void OutputSettingsPopup::onStereoChecked (int) protected slot
Set current scene output frame values: start frame, end frame, step and shrink, to current field values.
{
  m_stereoShift->setEnabled(m_doStereoscopy->isChecked());
  if (m_dominantFieldOm)
    m_dominantFieldOm->setEnabled(!m_doStereoscopy->isChecked());
  onStereoChanged();
}
onStretchFldEditFinished
void OutputSettingsPopup::onStretchFldEditFinished () protected slot
If dominant field is different from none set time stretch field values to current scene output time stretch values; otherwise set current scene output time stretch values to current field values.
{
  if (!getCurrentScene()) return;
  TOutputProperties *prop = getProperties();
  TRenderSettings rs      = prop->getRenderSettings();
  if (m_dominantFieldOm->currentIndex() != c_none) {
    DVGui::error("Can't stretch time in a field rendered scene\n");
    m_stretchFromFld->setValue(rs.m_timeStretchFrom);
    m_stretchToFld->setValue(rs.m_timeStretchTo);
  } else {
    rs.m_timeStretchFrom = m_stretchFromFld->getValue();
    rs.m_timeStretchTo   = m_stretchToFld->getValue();
    prop->setRenderSettings(rs);
  }
  TApp::instance()->getCurrentScene()->setDirtyFlag(true);
}
References getCurrentScene(), TApp::getCurrentScene(), getProperties(), TOutputProperties::getRenderSettings(), DVGui::DoubleLineEdit::getValue(), TApp::instance(), TRenderSettings::m_timeStretchFrom, TRenderSettings::m_timeStretchTo, TOutputProperties::setRenderSettings(), and DVGui::DoubleLineEdit::setValue().
onSubcameraChecked
void OutputSettingsPopup::onSubcameraChecked (int state) protected slot
{
  getProperties()->setSubcameraPreview(state == Qt::Checked);
}
onThreadsComboChanged
void OutputSettingsPopup::onThreadsComboChanged (int type) protected slot
{
  if (!getCurrentScene()) return;
  TOutputProperties *prop = getProperties();
  prop->setThreadIndex(type);
  TApp::instance()->getCurrentScene()->setDirtyFlag(true);
}
openSettingsPopup
void OutputSettingsPopup::openSettingsPopup () protected slot
Open a popup output format settings popup to set current output format settings.
{
  TOutputProperties *prop = getProperties();
  std::string ext         = prop->getPath().getType();
  openFormatSettingsPopup(this, ext, prop->getFileFormatProperties(ext));
  if (m_presetCombo) m_presetCombo->setCurrentIndex(0);
}
References TOutputProperties::getFileFormatProperties(), TOutputProperties::getPath(), getProperties(), and TFilePath::getType().
showEvent()
void OutputSettingsPopup::showEvent (QShowEvent *) override protected
{
  TSceneHandle *sceneHandle   = TApp::instance()->getCurrentScene();
  TXsheetHandle *xsheetHandle = TApp::instance()->getCurrentXsheet();
  bool ret =
      connect(sceneHandle, SIGNAL(sceneChanged()), this, SLOT(updateField()));
  ret = ret && connect(sceneHandle, SIGNAL(sceneSwitched()), this,
                       SLOT(updateField()));
  ret = ret && connect(xsheetHandle, SIGNAL(xsheetChanged()), this,
                       SLOT(updateField()));
  updateField();
  assert(ret);
}
updateField
void OutputSettingsPopup::updateField () protected slot
Update all field value take care current scene output properties.
{
  ToonzScene *scene       = getCurrentScene();
  TOutputProperties *prop = getProperties();
  if (!prop) {
    if (!m_isPreviewSettings) {
      m_saveInFileFld->setPath(QString());
      m_fileNameFld->setText(QString());
      m_fileFormat->setCurrentIndex(0);
      m_gammaFld->setText(QString());
      m_dominantFieldOm->setCurrentIndex(c_none);
      m_frameRateFld->setText(QString());
      m_stretchFromFld->setText(QString());
      m_stretchToFld->setText(QString());
      m_multimediaOm->setCurrentIndex(0);
    }
    if (m_outputCameraOm) m_outputCameraOm->setCurrentIndex(0);
    m_startFld->setText(QString());
    m_endFld->setText(QString());
    m_stepFld->setText(QString());
    m_shrinkFld->setText(QString());
    if (m_applyShrinkChk) m_applyShrinkChk->setCheckState(Qt::Unchecked);
    m_resampleBalanceOm->setCurrentIndex(c_standard);
    m_channelWidthOm->setCurrentIndex(c_8bit);
    m_threadsComboOm->setCurrentIndex(0);
    m_rasterGranularityOm->setCurrentIndex(0);
    if (m_subcameraChk) m_subcameraChk->setCheckState(Qt::Unchecked);
    return;
  }
  TRenderSettings renderSettings = prop->getRenderSettings();
  if (!m_isPreviewSettings) {
    TFilePath path = prop->getPath();
    QString name   = QString::fromStdWString(path.getWideName());
    if (name.isEmpty())
      name = QString::fromStdString(scene->getScenePath().getName());
    m_saveInFileFld->setPath(toQString(path.getParentDir()));
    m_fileNameFld->setText(name);
    // RenderController::instance()->setMovieExt(path.getType());
    m_fileFormat->setCurrentIndex(
        m_fileFormat->findText(QString::fromStdString(path.getType())));
    m_multimediaOm->setCurrentIndex(prop->getMultimediaRendering());
  }
  // Refresh format if allow-multithread was toggled
  if (m_allowMT != Preferences::instance()->getFfmpegMultiThread()) {
    onFormatChanged(m_fileFormat->currentText());
  }
  // camera
  if (m_outputCameraOm) {
    m_outputCameraOm->blockSignals(true);
    m_outputCameraOm->clear();
  }
  TStageObjectTree *tree  = scene->getXsheet()->getStageObjectTree();
  int cameraCount         = tree->getCameraCount();
  TStageObjectId cameraId = m_isPreviewSettings
                                ? tree->getCurrentPreviewCameraId()
                                : tree->getCurrentCameraId();
  QStringList cameras;
  int tmpCameraId = 0;
  int index       = 0;
  int i;
  for (i = 0; i < cameraCount;) {
    /*-- Deleteされたカメラの場合tmpCameraIdだけIncrementする --*/
    if (!tree->getStageObject(TStageObjectId::CameraId(tmpCameraId), false)) {
      tmpCameraId++;
      continue;
    }
    std::string name =
        tree->getStageObject(TStageObjectId::CameraId(tmpCameraId))->getName();
    cameras.append(QString::fromStdString(name));
    if (name == tree->getStageObject(cameraId)->getName()) index = i;
    i++;
    tmpCameraId++;
  }
  if (m_outputCameraOm) {
    m_outputCameraOm->addItems(cameras);
    m_outputCameraOm->blockSignals(false);
    m_outputCameraOm->setCurrentIndex(index);
  }
  if (m_subcameraChk)
    m_subcameraChk->setCheckState(prop->isSubcameraPreview() ? Qt::Checked
                                                             : Qt::Unchecked);
  // start,end,step
  int r0 = 0, r1 = -1, step;
  prop->getRange(r0, r1, step);
  if (r0 > r1) {
    r0 = 0;
    r1 = scene->getFrameCount() - 1;
    if (r1 < 0) r1 = 0;
  }
  m_startFld->setValue(r0 + 1);
  m_endFld->setValue(r1 + 1);
  m_stepFld->setValue(step);
  m_shrinkFld->setValue(renderSettings.m_shrinkX);
  if (m_applyShrinkChk)
    m_applyShrinkChk->setCheckState(
        renderSettings.m_applyShrinkToViewer ? Qt::Checked : Qt::Unchecked);
  // resample
  m_resampleBalanceOm->setCurrentIndex(
      (int)quality2index(renderSettings.m_quality));
  // channel width
  switch (renderSettings.m_bpp) {
  case 64:
    m_channelWidthOm->setCurrentIndex(c_16bit);
    break;
  default:
    m_channelWidthOm->setCurrentIndex(c_8bit);
    break;
  }
  // Threads
  m_threadsComboOm->setCurrentIndex(prop->getThreadIndex());
  // Raster granularity
  m_rasterGranularityOm->setCurrentIndex(prop->getMaxTileSizeIndex());
  if (m_isPreviewSettings) return;
  m_doStereoscopy->setChecked(renderSettings.m_stereoscopic);
  m_stereoShift->setValue(renderSettings.m_stereoscopicShift);
  m_stereoShift->setEnabled(renderSettings.m_stereoscopic);
  // gamma
  m_gammaFld->setValue(renderSettings.m_gamma);
  // dominant field
  switch (renderSettings.m_fieldPrevalence) {
  case TRenderSettings::OddField:
    m_dominantFieldOm->setCurrentIndex(c_odd);
    break;
  case TRenderSettings::EvenField:
    m_dominantFieldOm->setCurrentIndex(c_even);
    break;
  case TRenderSettings::NoField:
  default:
    m_dominantFieldOm->setCurrentIndex(c_none);
  }
  m_dominantFieldOm->setEnabled(!renderSettings.m_stereoscopic);
  // time stretch
  m_stretchFromFld->setValue(renderSettings.m_timeStretchFrom);
  m_stretchToFld->setValue(renderSettings.m_timeStretchTo);
  m_frameRateFld->setValue(prop->getFrameRate());
  // clapperboard
  BoardSettings *boardSettings = prop->getBoardSettings();
  m_addBoard->setChecked(boardSettings->isActive());
  // clapperboard is only available with movie formats
  if (isMovieType(m_fileFormat->currentText().toStdString())) {
    m_addBoard->setEnabled(true);
    m_boardSettingsBtn->setEnabled(m_addBoard->isChecked());
  } else {
    m_addBoard->setEnabled(false);
    m_boardSettingsBtn->setEnabled(false);
  }
}
References TRenderSettings::EvenField, TStageObjectTree::getCameraCount(), TStageObjectTree::getCurrentCameraId(), getCurrentScene(), ToonzScene::getFrameCount(), TOutputProperties::getFrameRate(), TFilePath::getName(), TFilePath::getParentDir(), TOutputProperties::getPath(), getProperties(), TOutputProperties::getRange(), TOutputProperties::getRenderSettings(), ToonzScene::getScenePath(), TStageObjectTree::getStageObject(), TXsheet::getStageObjectTree(), TFilePath::getType(), ToonzScene::getXsheet(), TRenderSettings::m_applyShrinkToViewer, TRenderSettings::m_bpp, TRenderSettings::m_fieldPrevalence, TRenderSettings::m_gamma, TRenderSettings::m_quality, TRenderSettings::m_shrinkX, TRenderSettings::m_stereoscopic, TRenderSettings::m_stereoscopicShift, TRenderSettings::m_timeStretchFrom, TRenderSettings::m_timeStretchTo, TRenderSettings::NoField, TRenderSettings::OddField, onFormatChanged(), DVGui::DoubleLineEdit::setValue(), and DVGui::IntLineEdit::setValue().
Referenced by onCameraChanged().
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/toonz/outputsettingspopup.h
E:/opentoonz/toonz/sources/toonz/outputsettingspopup.cpp