opentoonz: VectorizationSwatchTask Class Reference
VectorizationSwatchTask Class Reference final
Signals
void myStarted (TThread::RunnableP task)
Signals inherited from TThread::Runnable
void started (TThread::RunnableP sender)
void finished (TThread::RunnableP sender)
void exception (TThread::RunnableP sender)
void canceled (TThread::RunnableP sender)
void terminated (TThread::RunnableP sender)
Public Member Functions
VectorizationSwatchTask (int row, int col, TPaletteP substitutePalette=TPaletteP())
void run () override
The central code of the task that is executed by a worker thread.
void onStarted (TThread::RunnableP task) override
void onFinished (TThread::RunnableP task) override
The analogous of onStarted() for the finished() signal.
Public Member Functions inherited from TThread::Runnable
virtual void run ()=0
The central code of the task that is executed by a worker thread.
virtual int taskLoad ()
virtual int schedulingPriority ()
virtual QThread::Priority runningPriority ()
Public Member Functions inherited from TSmartObject
TSmartObject (ClassCode classCode)
void addRef ()
void release ()
TINT32 getRefCount () const
Additional Inherited Members
Public Types inherited from TSmartObject
typedef short ClassCode
Public Slots inherited from TThread::Runnable
virtual void onStarted (TThread::RunnableP sender)
virtual void onFinished (TThread::RunnableP sender)
The analogous of onStarted() for the finished() signal.
virtual void onException (TThread::RunnableP sender)
The analogous of onStarted() for the exception() signal.
virtual void onCanceled (TThread::RunnableP sender)
The analogous of onStarted() for the canceled() signal.
virtual void onTerminated (TThread::RunnableP sender)
The analogous of onStarted() for the terminated() signal.
Static Public Member Functions inherited from TSmartObject
static TINT32 getInstanceCount (ClassCode code)
Detailed Description
Constructor & Destructor Documentation
VectorizationSwatchTask()
VectorizationSwatchTask::VectorizationSwatchTask (int row, int col, TPaletteP substitutePalette = TPaletteP())
    : m_row(row), m_col(col), m_substitutePalette(substitutePalette) {
  // Establish connections to default slots; the started one must be blocking,
  // so that run() awaits until it has been performed.
  connect(this, SIGNAL(myStarted(TThread::RunnableP)),
          SLOT(onStarted(TThread::RunnableP)), Qt::BlockingQueuedConnection);
  connect(this, SIGNAL(finished(TThread::RunnableP)),
          SLOT(onFinished(TThread::RunnableP)));
}
Member Function Documentation
onFinished()
void VectorizationSwatchTask::onFinished (TThread::RunnableP sender) override virtual
The analogous of onStarted() for the finished() signal.
Reimplemented from TThread::Runnable.
{
  if (m_image) {
    VectorizationBuilder *builder = VectorizationBuilder::instance();
    if (builder->m_row == m_row && builder->m_col == m_col) {
      builder->m_done = true;
      builder->notifyDone(m_image);
    }
  }
}
onStarted()
void VectorizationSwatchTask::onStarted (TThread::RunnableP sender) override virtual
Convenience slot for the started() signal - so it's not necessary to declare the task in a header file for moc'ing each time. You must both reimplement and connect it to the started() signal to make it work.
Reimplemented from TThread::Runnable.
{
  VectorizationBuilder *builder = VectorizationBuilder::instance();
  if (builder->m_done || builder->m_row != m_row || builder->m_col != m_col)
    return;
  // Retrieve the image to be vectorized
  m_image = getXsheetImage(m_row, m_col);
  // Build the vectorization configuration
  m_config = getCurrentVectorizerConfiguration(m_row, m_col);
}
run()
void VectorizationSwatchTask::run () override virtual
The central code of the task that is executed by a worker thread.
Implements TThread::Runnable.
{
  emit myStarted(this);
  if (!m_image || !m_config.get()) return;
  // The task must be performed - retrieve and prepare configuration data
  ToonzScene *scene = TApp::instance()->getCurrentScene()->getScene();
  VectorizerConfiguration *c = m_config.get();
  // Build additional configuration data
  TPaletteP palette;
  TPointD center, dpi;
  if (TToonzImageP ti = m_image) {
    palette = (m_substitutePalette) ? m_substitutePalette : ti->getPalette();
    center  = ti->getRaster()->getCenterD();
    ti->getDpi(dpi.x, dpi.y);
  } else if (TRasterImageP ri = m_image) {
    palette = new TPalette;
    center  = ri->getRaster()->getCenterD();
    ri->getDpi(dpi.x, dpi.y);
  }
  // In case the image has no dpi, use the standard dpi (same one the
  // PlaneViewer will show
  // the raster image with)
  if (dpi.x == 0.0 || dpi.y == 0.0) dpi.x = dpi.y = Stage::inch;
  // The vectorized image must feel the same visualization transform as m_image.
  // We're transforming the image itself, rather than having it transformed at
  // every paint event.
  // NOTE: It would be best if the transform was the same found from the
  // VectorizerPopup...
  // Unfortunately, this would mean accessing the level's dpi value, thus having
  // to rewrite quite
  // some code around here...
  c->m_affine =
      TScale(Stage::inch / dpi.x, Stage::inch / dpi.y) * TTranslation(-center);
  c->m_thickScale = Stage::inch / dpi.x;
  // Vectorize the image
  VectorizerCore vectorizer;
  TVectorImageP vi = vectorizer.vectorize(m_image, *c, palette.getPointer());
  vi->setPalette(palette.getPointer());
  m_image = vi;
}
References TApp::getCurrentScene(), Stage::inch, TApp::instance(), VectorizerConfiguration::m_affine, VectorizerConfiguration::m_thickScale, and VectorizerCore::vectorize().
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/toonz/vectorizerswatch.h
E:/opentoonz/toonz/sources/toonz/vectorizerswatch.cpp