opentoonz: TPalette Class Reference
TPalette Class Reference final
The class representing a Toonz palette object.
#include <tpalette.h>
Classes
class Page
A palette page is a restricted view of a palette instance.
Public Member Functions
TPalette * clone () const
Allocates a new copy of this palette instance.
std::wstring getGlobalName () const
Returns the name of the palette object.
void setGlobalName (std::wstring name)
Assigns the name of the palette.
void setDirtyFlag (bool dirtyFlag)
bool getDirtyFlag ()
TColorStyle * getStyle (int styleId) const
int getStyleCount () const
Returns the number of the color styles in the palette.
int getStyleInPagesCount () const
Returns the number of styles contained in palette pages.
int getFirstUnpagedStyle () const
int addStyle (TColorStyle *style)
int addStyle (const TPixelRGBM32 &color)
void setStyle (int styleId, TColorStyle *style)
Replaces the style with the specified style id.
void setStyle (int styleId, const TPixelRGBM32 &color)
int getPageCount () const
specified style id.
Page * getPage (int pageIndex)
const Page * getPage (int pageIndex) const
Const version of getPage(int).
Page * addPage (std::wstring name)
Creates a new page with the specified name.
void erasePage (int index)
Deletes the index-th page.
void movePage (Page *page, int dstPageIndex)
Page * getStylePage (int styleId) const
Returns the page containing the specified styleId.
int getClosestStyle (const TPixelRGBM32 &color) const
void loadData (TIStream &is) override
I/O palette save function.
void saveData (TOStream &os) override
I/O palette load function.
int getVersion () const
Returns the palette's version number.
void setVersion (int v)
Sets the palette's version number.
void setRefLevelFids (const std::vector< TFrameId > fids, bool specified)
std::vector< TFrameId > getRefLevelFids ()
void assign (const TPalette *src, bool isFromStudioPalette=false)
void merge (const TPalette *src, bool isFromStudioPalette=false)
void setAskOverwriteFlag (bool askOverwriteFlag)
bool getAskOverwriteFlag ()
Returns the ask-overwrite flag.
void setIsCleanupPalette (bool on)
Sets the palette's identity as a cleanup palette.
bool isCleanupPalette () const
Returns whether this is a cleanup palette.
const TImageP & getRefImg () const
void setRefImg (const TImageP &img)
const TFilePath getRefImgPath () const
built or modified using this palette.
void setRefImgPath (const TFilePath &fp)
Sets the path filename of the reference image.
bool isAnimated () const
int getFrame () const
Returns the index of the current frame.
void setFrame (int frame)
Sets the index of the current frame.
bool isKeyframe (int styleId, int frame) const
int getKeyframeCount (int styleId) const
Returns the keyframes count in styleId's animation.
int getKeyframe (int styleId, int index) const
void setKeyframe (int styleId, int frame)
void clearKeyframe (int styleId, int frame)
animation.
int getShortcutValue (int key) const
animation.
int getStyleShortcut (int styleId) const
void setShortcutValue (int key, int styleId)
Associates the specified key to a styleId.
void setPaletteName (std::wstring name)
Sets the name of the palette.
std::wstring getPaletteName () const
Returns the name of the palette.
QMutex * mutex ()
Returns the palette's mutex.
bool isLocked () const
Returns whether the palette is locked.
void setIsLocked (bool lock)
bool hasPickedPosStyle ()
void nextShortcutScope (bool invert)
void setCurrentStyleId (int id)
int getCurrentStyleId () const
bool getFxRects (const TRect &rect, TRect &rectIn, TRect &rectOut)
Public Member Functions inherited from TPersist
virtual void loadData (TIStream &is)=0
virtual void saveData (TOStream &os)=0
std::string getStreamTag () const
virtual const TPersistDeclaration * getDeclaration () const =0
Public Member Functions inherited from TSmartObject
TSmartObject (ClassCode classCode)
void addRef ()
void release ()
TINT32 getRefCount () const
Static Public Member Functions
static void setRootDir (const TFilePath &fp)
static TFilePath getRootDir ()
fp/textures.
Static Public Member Functions inherited from TPersist
static void declare (CreateProc *)
static TPersist * create (const std::string &name)
Static Public Member Functions inherited from TSmartObject
static TINT32 getInstanceCount (ClassCode code)
Friends
class Page
Additional Inherited Members
Public Types inherited from TPersist
typedef TPersist * CreateProc()
Public Types inherited from TSmartObject
typedef short ClassCode
Detailed Description
The class representing a Toonz palette object.
Rationale
A palette is a collection of color styles that adds a level of indirection on color selections when drawing certain graphical objects.
Palette-based objects store style identifiers into an associated palette object, rather than the colors directly. When a color needs to be accessed, the palette objects is queried for a style id, and the associated style is returned.
A TColorStyle instance generalizes the notion of color, providing the ability to reduce a style instance to a color, and specialized drawing functions for vector graphics objects.
Reserved colors
A palette object has two fixed reserved styles - which cannot be removed - at indexes 0 and \p1. Index 0 is reserved for the transparent color. Index 1 is reserved for the ink color, initialized by default to black.
Syntax
A palette is supposedly created on the heap, to the point that, in current implementation, copy and assignment are forbidden. This behavior is somewhat inconsistent since a palette is currently clonable and assignable with the appropriate functions. Normalization to common C++ syntax should be enforced ASAP.
See also
The TColorStyle class.
Constructor & Destructor Documentation
TPalette()
TPalette::TPalette ()
    : m_version(0)
    , m_isCleanupPalette(false)
    , m_currentFrame(-1)
    , m_dirtyFlag(false)
    , m_mutex(QMutex::Recursive)
    , m_isLocked(false)
    , m_askOverwriteFlag(false)
    , m_shortcutScopeIndex(0)
    , m_currentStyleId(1) {
  QString tempName(QObject::tr("colors"));
  std::wstring pageName = tempName.toStdWString();
  Page *page            = addPage(pageName);
  page->addStyle(TPixel32(255, 255, 255, 0));
  page->addStyle(TPixel32(0, 0, 0, 255));
  getStyle(0)->setName(L"color_0");
  getStyle(1)->setName(L"color_1");
  for (int i = 0; i < 10; i++) m_shortcuts['0' + i] = i;
}
~TPalette()
TPalette::~TPalette ()
                    {
  std::set<TColorStyle *> table;
  int i = 0;
  for (i = 0; i < getStyleCount(); i++) {
    assert(table.find(getStyle(i)) == table.end());
    table.insert(getStyle(i));
  }
  clearPointerContainer(m_pages);
}
Member Function Documentation
addPage()
TPalette::Page * TPalette::addPage (std::wstring name)
Creates a new page with the specified name.
Returns
A pointer to the newly created page.
{
  Page *page      = new Page(name);
  page->m_index   = getPageCount();
  page->m_palette = this;
  m_pages.push_back(page);
  return page;
}
References getPageCount().
Referenced by assign(), loadData(), and merge().
addStyle() [1/2]
int TPalette::addStyle (const TPixelRGBM32 & color)
Adds a solid color style to the palette (but in no page).
addStyle() [2/2]
int TPalette::addStyle (TColorStyle * style)
 \remark   Style ownserhip is \a surrendered to the palette
 \return   The styleId associated to the inserted style, or \a -1 on
failure. Adds the specified style to the palette (but in no page).
Adding style with new styleId. Even if there are deleted styles in the palette, the new style will be appended to the end of the list.
{
  // limit the number of cleanup style to 7
  if (isCleanupPalette() && getStyleInPagesCount() >= 8) return -1;
  int styleId = int(m_styles.size());
  if (styleId < 4096) {
    // checking if the style is overlapped
    int i = 0;
    for (i = 0; i < styleId; i++)
      if (getStyle(i) == style) break;
    if (i == styleId) {
      m_styles.push_back(std::make_pair((Page *)0, style));
      return styleId;
    }
  }
  delete style;
  return -1;
}
References getStyle(), getStyleInPagesCount(), and isCleanupPalette().
Referenced by TPalette::Page::addStyle(), assign(), loadData(), and merge().
assign()
void TPalette::assign (const TPalette * src, bool isFromStudioPalette = false)
Deprecated:
Should be substituted by operator=(const TPalette&).
Copies src's page, color styles an animation table
if the palette is copied from studio palette, this function will modify the original names.
{
  if (src == this) return;
  int i;
  m_isCleanupPalette = src->isCleanupPalette();
  // for(i=0;i<getStyleCount();i++) delete getStyle(i);
  m_styles.clear();
  clearPointerContainer(m_pages);
  for (i = 0; i < src->getStyleCount(); i++) {
    TColorStyle *srcStyle = src->getStyle(i);
    TColorStyle *dstStyle = srcStyle->clone();
    dstStyle->setName(
        srcStyle->getName());  // per un baco del TColorStyle::clone()
    dstStyle->setGlobalName(
        srcStyle->getGlobalName());  // per un baco del TColorStyle::clone()
    // if the style is copied from studio palette, put its name to the original
    // name.
    // check if the style has the global name (i.e. it comes from studio
    // palette)
    if (isFromStudioPalette && srcStyle->getGlobalName() != L"") {
      // If the original style has no original name (i.e. if the style is copied
      // from the studio palette)
      if (srcStyle->getOriginalName() == L"") {
        // put the original style name to the "original name" of the pasted
        // style.
        dstStyle->setOriginalName(srcStyle->getName());
      }
    }
    int j = addStyle(dstStyle);
    assert(i == j);
  }
  for (i = 0; i < src->getPageCount(); i++) {
    const Page *srcPage = src->getPage(i);
    Page *dstPage       = addPage(srcPage->getName());
    for (int j = 0; j < srcPage->getStyleCount(); j++)
      dstPage->addStyle(srcPage->getStyleId(j));
  }
  m_refImg     = !!src->m_refImg ? src->m_refImg->cloneImage() : TImageP();
  m_refImgPath = src->m_refImgPath;
  StyleAnimationTable::iterator it;
  StyleAnimation::iterator j;
  for (it = m_styleAnimationTable.begin(); it != m_styleAnimationTable.end();
       ++it) {
    // for(j = it->second.begin(); j != it->second.end(); ++j)
    //   delete j->second;
    it->second.clear();
  }
  m_styleAnimationTable.clear();
  StyleAnimationTable::const_iterator cit;
  for (cit = src->m_styleAnimationTable.begin();
       cit != src->m_styleAnimationTable.end(); ++cit) {
    StyleAnimation animation = cit->second;
    for (j = animation.begin(); j != animation.end(); j++)
      j->second = j->second->clone();
    m_styleAnimationTable[cit->first] = cit->second;
  }
  m_globalName         = src->getGlobalName();
  m_shortcuts          = src->m_shortcuts;
  m_currentFrame       = src->m_currentFrame;
  m_shortcutScopeIndex = src->m_shortcutScopeIndex;
  // setDirtyFlag(true);
}
References addPage(), TPalette::Page::addStyle(), addStyle(), TColorStyle::clone(), TImage::cloneImage(), TColorStyle::getGlobalName(), getGlobalName(), TColorStyle::getName(), TPalette::Page::getName(), TColorStyle::getOriginalName(), getPage(), getPageCount(), getStyle(), TPalette::Page::getStyleCount(), getStyleCount(), TPalette::Page::getStyleId(), isCleanupPalette(), TColorStyle::setGlobalName(), TColorStyle::setName(), and TColorStyle::setOriginalName().
Referenced by RasterSelection::deleteSelection().
clearKeyframe()
void TPalette::clearKeyframe (int styleId, int frame)
animation.
Deletes the keyframe at the specified frame of styleId's
{
  assert(0 <= styleId && styleId < getStyleCount());
  assert(0 <= frame);
  StyleAnimationTable::iterator it = m_styleAnimationTable.find(styleId);
  if (it == m_styleAnimationTable.end()) return;
  StyleAnimation &animation  = it->second;
  StyleAnimation::iterator j = animation.find(frame);
  if (j == animation.end()) return;
  // j->second->release();
  animation.erase(j);
  if (animation.empty()) {
    m_styleAnimationTable.erase(styleId);
  }
}
References getStyleCount().
clone()
TPalette * TPalette::clone () const
Allocates a new copy of this palette instance.
{
  TPalette *palette = new TPalette;
  palette->assign(this);
  return palette;
}
Referenced by ToonzImageIconRenderer::run(), and Vectorizer::setLevel().
erasePage()
void TPalette::erasePage (int index)
Deletes the index-th page.
{
  Page *page = getPage(index);
  if (!page) return;
  m_pages.erase(m_pages.begin() + index);
  int i;
  for (i = 0; i < getPageCount(); i++) m_pages[i]->m_index = i;
  for (i = 0; i < page->getStyleCount(); i++)
    m_styles[page->getStyleId(i)].first = 0;
  page->m_palette = 0;
  delete page;
}
References getPage(), getPageCount(), TPalette::Page::getStyleCount(), and TPalette::Page::getStyleId().
getAskOverwriteFlag()
bool TPalette::getAskOverwriteFlag () inline
Returns the ask-overwrite flag.
getClosestStyle()
int TPalette::getClosestStyle (const TPixelRGBM32 & color) const
Note
The distance between colors is calculated with the usual sphrical norm between RGBA color components.
Returns
The style id of the nearest style, or -1 if none was found. Returns the index of the style whose main color is nearest to the requested one.
{
  struct locals {
    static inline int getDistance2(const TPixel32 &a, const TPixel32 &b) {
      return (a.r - b.r) * (a.r - b.r) + (a.g - b.g) * (a.g - b.g) +
             (a.b - b.b) * (a.b - b.b) + (a.m - b.m) * (a.m - b.m);
    }
  };  // locals
  if (color == TPixel32::Transparent) return 0;
  int bestIndex    = -1;
  int bestDistance = 255 * 255 * 4 + 1;
  for (int i = 1; i < (int)m_styles.size(); i++) {
    // if(i==FirstUserStyle+2) continue;
    TSolidColorStyle *scs =
        dynamic_cast<TSolidColorStyle *>(m_styles[i].second.getPointer());
    if (scs) {
      int d = locals::getDistance2(scs->getMainColor(), color);
      if (d < bestDistance) {
        bestIndex    = i;
        bestDistance = d;
      }
    }
  }
  return bestIndex;
}
References TSolidColorStyle::getMainColor().
getCurrentStyleId()
int TPalette::getCurrentStyleId () const inline
{ return m_currentStyleId; }
getDirtyFlag()
bool TPalette::getDirtyFlag () inline
Returns whether the palette changed with respect to the last saved state.
Referenced by StudioPaletteTreeViewer::onCurrentItemChanged(), StudioPaletteTreeViewer::onItemSelectionChanged(), and SceneLevel::save().
getFirstUnpagedStyle()
int TPalette::getFirstUnpagedStyle () const
Returns the styleId of the first style not in a page (-1 if none).
{
  for (int i = 0; i < getStyleCount(); i++)
    if (m_styles[i].first == 0) return i;
  return -1;
}
References getStyleCount().
getFrame()
int TPalette::getFrame () const
Returns the index of the current frame.
{ return m_currentFrame; }
Referenced by Stage::RasterPainter::onVectorImage().
getFxRects()
bool TPalette::getFxRects (const TRect & rect, TRect & rectIn, TRect & rectOut)
Deprecated:
Used only once throughout Toonz, should be verified.
{
  int i;
  bool ret = false;
  int borderIn, borderOut, fullBorderIn = 0, fullBorderOut = 0;
  for (i = 0; i < (int)m_styles.size(); i++)
    if (m_styles[i].second->isRasterStyle()) {
      m_styles[i].second->getRasterStyleFx()->getEnlargement(borderIn,
                                                             borderOut);
      fullBorderIn  = std::max(fullBorderIn, borderIn);
      fullBorderOut = std::max(fullBorderOut, borderOut);
      ret           = true;
    }
  rectIn  = rect.enlarge(fullBorderIn);
  rectOut = rect.enlarge(fullBorderOut);
  return ret;
}
getGlobalName()
std::wstring TPalette::getGlobalName () const inline
Returns the name of the palette object.
Referenced by assign(), StudioPaletteTreeViewer::onCurrentItemChanged(), and StudioPaletteTreeViewer::onItemSelectionChanged().
getKeyframe()
int TPalette::getKeyframe (int styleId, int index) const
Returns the index-th frame in styleId's animation, or -1 if it couldn't be found.
{
  StyleAnimationTable::const_iterator it = m_styleAnimationTable.find(styleId);
  if (it == m_styleAnimationTable.end()) return -1;
  const StyleAnimation &animation = it->second;
  if (index < 0 || index >= (int)animation.size()) return -1;
  StyleAnimation::const_iterator j = animation.begin();
  std::advance(j, index);
  return j->first;
}
getKeyframeCount()
int TPalette::getKeyframeCount (int styleId) const
Returns the keyframes count in styleId's animation.
keyframe in styleId's animation
{
  StyleAnimationTable::const_iterator it = m_styleAnimationTable.find(styleId);
  if (it == m_styleAnimationTable.end()) return 0;
  return int(it->second.size());
}
getPage() [1/2]
TPalette::Page * TPalette::getPage (int pageIndex)
Returns the index-th palette page, or 0 if no such page was found.
{
  if (0 <= pageIndex && pageIndex < getPageCount()) {
    Page *page = m_pages[pageIndex];
    assert(page->getIndex() == pageIndex);
    assert(page->m_palette == this);
    return page;
  } else
    return 0;
}
References TPalette::Page::getIndex(), and getPageCount().
Referenced by assign(), PaletteViewer::contextMenuEvent(), PaletteViewerGUI::PageViewer::drop(), erasePage(), getShortcutValue(), merge(), and saveData().
getPage() [2/2]
const TPalette::Page * TPalette::getPage (int pageIndex) const
Const version of getPage(int).
{
  if (0 <= pageIndex && pageIndex < getPageCount()) {
    Page *page = m_pages[pageIndex];
    assert(page->getIndex() == pageIndex);
    assert(page->m_palette == this);
    return page;
  } else
    return 0;
}
References TPalette::Page::getIndex(), and getPageCount().
getPageCount()
int TPalette::getPageCount () const
specified style id.
Returns the pages count.
{ return int(m_pages.size()); }
Referenced by PaletteViewer::addNewPage(), addPage(), assign(), PaletteViewer::dropEvent(), erasePage(), getPage(), merge(), TVectorImage::mergeImage(), movePage(), and saveData().
getPaletteName()
std::wstring TPalette::getPaletteName () const inline
Returns the name of the palette.
Referenced by StudioPaletteTreeViewer::convertToStudioPalette(), merge(), and StudioPaletteTreeViewer::replaceCurrentPalette().
getRefImg()
const TImageP & TPalette::getRefImg () const inline
Returns an image that represents the frame image associated to this palette.
getRefImgPath()
const TFilePath TPalette::getRefImgPath () const inline
built or modified using this palette.
Returns the file path of the reference image.
Referenced by PaletteViewer::dropEvent(), TXshSimpleLevel::load(), and SceneLevel::SceneLevel().
getRefLevelFids()
std::vector< TFrameId > TPalette::getRefLevelFids ()
fids to this palette. When specified == true fids were specified by user on loading. Returns the list of frames associated to this palette.
{ return m_refLevelFids; }
Referenced by TXshSimpleLevel::load().
getShortcutValue()
int TPalette::getShortcutValue (int key) const
animation.
Note
Key is an integer between 0 and 9 included. Returns the style id shortcut associated to key, or -1 if it couldn't be found.
{
  assert(Qt::Key_0 <= key && key <= Qt::Key_9);
  int shortcutIndex = (key == Qt::Key_0) ? 9 : key - Qt::Key_1;
  int indexInPage   = m_shortcutScopeIndex * 10 + shortcutIndex;
  // shortcut is available only in the first page
  return getPage(0)->getStyleId(indexInPage);
}
References getPage(), and TPalette::Page::getStyleId().
Referenced by saveData().
getStyle()
TColorStyle * TPalette::getStyle (int styleId) const
Returns a pointer to the color style with the specified id, or 0 if said id is not stored in the palette.
{
  if (0 <= index && index < getStyleCount())
    return m_styles[index].second.getPointer();
  else {
    static TSolidColorStyle *ss = new TSolidColorStyle(TPixel32::Red);
    ss->addRef();
    return ss;
  }
}
References getStyleCount().
Referenced by addStyle(), assign(), TRop::convertRaster50to46(), TStyleSelection::getBackOriginalStyle(), TVectorImage::getBBox(), TVectorBrushStyle::getColorParamValue(), TVectorBrushStyle::getMainColor(), TPalette::Page::getStyle(), loadData(), merge(), FullColorAreaFiller::rectFill(), TVectorBrushStyle::setColorParamValue(), setFrame(), setKeyframe(), TVectorBrushStyle::setMainColor(), setStyle(), and StudioPalette::updateLinkedColors().
getStyleCount()
int TPalette::getStyleCount () const inline
Returns the number of the color styles in the palette.
Referenced by assign(), clearKeyframe(), TRop::convertRaster50to46(), getFirstUnpagedStyle(), getStyle(), TPalette::Page::getStyleId(), getStyleInPagesCount(), getStylePage(), getStyleShortcut(), TPalette::Page::insertStyle(), merge(), TPalette::Page::removeStyle(), saveData(), TPalette::Page::search(), setFrame(), setKeyframe(), setShortcutValue(), and setStyle().
getStyleInPagesCount()
int TPalette::getStyleInPagesCount () const
Returns the number of styles contained in palette pages.
{
  int styleInPagesCount = 0;
  for (int i = 0; i < getStyleCount(); i++)
    if (m_styles[i].first != 0) styleInPagesCount++;
  return styleInPagesCount;
}
References getStyleCount().
Referenced by addStyle().
getStylePage()
TPalette::Page * TPalette::getStylePage (int styleId) const
Returns the page containing the specified styleId.
{
  if (0 <= styleId && styleId < getStyleCount())
    return m_styles[styleId].first;
  else
    return 0;
}
References getStyleCount().
Referenced by getStyleShortcut(), and ColorModelViewer::pick().
getStyleShortcut()
int TPalette::getStyleShortcut (int styleId) const
Returns the shortcut associated to styleId, or or -1 if it couldn't be found.
{
  assert(0 <= styleId && styleId < getStyleCount());
  Page *page = getStylePage(styleId);
  // shortcut is available only in the first page
  if (!page || page->getIndex() != 0) return -1;
  int indexInPage   = page->search(styleId);
  int shortcutIndex = indexInPage - m_shortcutScopeIndex * 10;
  if (shortcutIndex < 0 || shortcutIndex > 9) return -1;
  return (shortcutIndex == 9) ? Qt::Key_0 : Qt::Key_1 + shortcutIndex;
}
References TPalette::Page::getIndex(), getStyleCount(), getStylePage(), and TPalette::Page::search().
Referenced by PaletteViewerGUI::PageViewer::event().
getVersion()
int TPalette::getVersion () const inline
Returns the palette's version number.
hasPickedPosStyle()
bool TPalette::hasPickedPosStyle ()
{
  for (int i = 0; i < getStyleCount(); ++i) {
    TColorStyleP style = m_styles[i].second;
    if (style->getPickedPosition().pos != TPoint()) return true;
  }
  return false;
}
isAnimated()
bool TPalette::isAnimated () const
Returns whether this palette is animated (styles change through time).
{ return !m_styleAnimationTable.empty(); }
Referenced by saveData().
isCleanupPalette()
bool TPalette::isCleanupPalette () const inline
Returns whether this is a cleanup palette.
Referenced by addStyle(), assign(), PaletteViewerGUI::PageViewer::dragEnterEvent(), and PaletteViewerGUI::PaletteTabBar::dragEnterEvent().
isKeyframe()
bool TPalette::isKeyframe (int styleId, int frame) const
Returns whether the specified frame is a
{
  StyleAnimationTable::const_iterator it = m_styleAnimationTable.find(styleId);
  if (it == m_styleAnimationTable.end()) return false;
  return it->second.count(frame) > 0;
}
isLocked()
bool TPalette::isLocked () const inline
Returns whether the palette is locked.
Referenced by PaletteViewerGUI::PageViewer::contextMenuEvent(), PaletteViewerGUI::PageViewer::mouseDoubleClickEvent(), PaletteViewerGUI::PaletteTabBar::mouseDoubleClickEvent(), PaletteViewerGUI::PageViewer::mouseMoveEvent(), PaletteViewerGUI::PaletteTabBar::mouseMoveEvent(), PaletteViewerGUI::PageViewer::mousePressEvent(), PaletteViewerGUI::PageViewer::paintEvent(), saveData(), and PaletteViewerGUI::PageViewer::updateCommandLocks().
loadData()
void TPalette::loadData (TIStream & is) override virtual
I/O palette save function.
Implements TPersist.
{
  m_styles.clear();
  clearPointerContainer(m_pages);
  VersionNumber version = is.getVersion();
  std::string tagName;
  while (is.openChild(tagName)) {
    if (tagName == "version") {
      is >> version.first >> version.second;
      if (version > VersionNumber(71, 0))
        throw TException("palette, unsupported version number");
    } else if (tagName == "styles") {
      while (!is.eos())  // I think while(is.openChild(tagName))
      {                  // would be better. However, I don't trust
        if (!is.openChild(tagName) ||
            tagName !=
                "style")  // TIStream's implementation very much. Keeping it
          throw TException(
              "palette, expected tag <style>");  // like this for now.
        {
          StyleReader r(is, version);
          TColorStyle *cs = TColorStyle::load(r);
          std::string pickedPosStr;
          if (is.getTagParam("pickedpos", pickedPosStr))
            cs->setPickedPosition(stringToPoint(pickedPosStr));
          addStyle(cs);
        }
        is.closeChild();
      }
    } else if (tagName == "stylepages") {
      while (!is.eos()) {
        if (!is.openChild(tagName) || tagName != "page")
          throw TException("palette, expected tag <stylepage>");
        {
          std::wstring pageName;
          if (!is.openChild(tagName) || tagName != "name")
            throw TException("palette, expected tag <name>");
          { is >> pageName; }
          is.closeChild();
          Page *page = addPage(pageName);
          if (!is.openChild(tagName) || tagName != "indices")
            throw TException("palette, expected tag <indices>");
          {
            while (!is.eos()) {
              int index;
              is >> index;
              page->addStyle(index);
            }
          }
          is.closeChild();
        }
        is.closeChild();
      }
    } else if (tagName == "refImgPath") {
      std::string fidsStr;
      if (is.getTagParam("fids", fidsStr)) {
        m_areRefLevelFidsSpecified = true;
        m_refLevelFids             = strToFids(fidsStr);
      } else {
        m_areRefLevelFidsSpecified = false;
        m_refLevelFids.clear();
      }
      is >> m_refImgPath;
    } else if (tagName == "animation") {
      while (!is.eos()) {
        if (!is.openChild(tagName) || tagName != "style")
          throw TException("palette, expected tag <style>");
        {
          int styleId = 0;
          if (!is.getTagParam("id", styleId))
            throw TException("palette, missing id attribute in tag <style>");
          StyleAnimation animation;
          TColorStyle *style = getStyle(styleId);
          assert(style);
          while (is.matchTag(tagName)) {
            TColorStyle *cs = 0;
            int frame       = 0;
            if (tagName == "keycolor") {
              if (!is.getTagParam("frame", frame))
                throw TException(
                    "palette, missing frame attribute in tag <keycolor>");
              TPixel32 color;
              is >> color;
              cs = style->clone();
              cs->setMainColor(color);
            } else if (tagName == "keyframe") {
              if (!is.getTagParam("frame", frame))
                throw TException(
                    "palette, missing frame attribute in tag <keyframe>");
              StyleReader r(is, version);
              cs = TColorStyle::load(r);
            } else
              throw TException("palette, expected <keyframe> tag");
            animation[frame] = cs;
            is.closeChild();
          }
          m_styleAnimationTable[styleId] = animation;
        }
        is.closeChild();
      }
    } else if (tagName == "stylepages") {
      int key = '0';
      while (!is.eos()) {
        int styleId = 0;
        is >> styleId;
        if (key <= '9') setShortcutValue(key, styleId);
      }
    } else if (tagName == "shortcuts") {
      for (int i = 0; i < 10; ++i) {
        int v;
        is >> v;
        setShortcutValue('0' + i, v);
      }
    } else if (tagName == "lock") {
      int lockValue;
      is >> lockValue;
      m_isLocked = (bool)lockValue;
    } else
      throw TException("palette, unknown tag: " + tagName);
    is.closeChild();
  }
}
References addPage(), TPalette::Page::addStyle(), addStyle(), TColorStyle::clone(), TIStream::closeChild(), TIStream::eos(), getStyle(), TIStream::getTagParam(), TIStream::getVersion(), TColorStyle::load(), TIStream::matchTag(), TIStream::openChild(), TColorStyle::setMainColor(), and setShortcutValue().
Referenced by TSceneProperties::loadData().
merge()
void TPalette::merge (const TPalette * src, bool isFromStudioPalette = false)
to the corresponding features of the palette. if the palette is copied from studio palette, this function will modify the original names. Adds src's styles and pages to the palette.
if the palette is merged from studio palette, this function will modify the original names.
{
  std::map<int, int> table;
  int i;
  for (i = 1; i < src->getStyleCount(); i++) {
    TColorStyle *srcStyle = src->getStyle(i);
    TColorStyle *dstStyle = srcStyle->clone();
    dstStyle->setName(srcStyle->getName());
    dstStyle->setGlobalName(srcStyle->getGlobalName());
    // if the style is copied from studio palette, put its name to the original
    // name.
    // check if the style has the global name (i.e. it comes from studio
    // palette)
    if (isFromStudioPalette && srcStyle->getGlobalName() != L"") {
      // If the original style has no original name (i.e. if the style is copied
      // from the studio palette)
      if (srcStyle->getOriginalName() == L"") {
        // put the original style name to the "original name" of the pasted
        // style.
        dstStyle->setOriginalName(srcStyle->getName());
      }
    }
    int j    = addStyle(dstStyle);
    table[i] = j;
  }
  int pageCount = src->getPageCount();
  for (i = 0; i < pageCount; i++) {
    const Page *srcPage   = src->getPage(i);
    std::wstring pageName = srcPage->getName();
    if (pageName == L"colors" && src->getPaletteName() != L"")
      pageName = src->getPaletteName();
    Page *dstPage = addPage(pageName);  //;
    for (int j = 0; j < srcPage->getStyleCount(); j++) {
      int styleId = srcPage->getStyleId(j);
      if (styleId == 0) continue;
      assert(table.find(styleId) != table.end());
      dstPage->addStyle(table[styleId]);
    }
    assert(dstPage->m_palette == this);
  }
}
References addPage(), TPalette::Page::addStyle(), addStyle(), TColorStyle::clone(), TColorStyle::getGlobalName(), TColorStyle::getName(), TPalette::Page::getName(), TColorStyle::getOriginalName(), getPage(), getPageCount(), getPaletteName(), getStyle(), TPalette::Page::getStyleCount(), getStyleCount(), TPalette::Page::getStyleId(), TColorStyle::setGlobalName(), TColorStyle::setName(), and TColorStyle::setOriginalName().
movePage()
void TPalette::movePage (Page * page, int dstPageIndex)
Moves the specified page to a different page index.
{
  assert(page);
  assert(page->m_palette == this);
  dstPageIndex = tcrop(dstPageIndex, 0, getPageCount() - 1);
  if (dstPageIndex == page->getIndex()) return;
  m_pages.erase(m_pages.begin() + page->getIndex());
  m_pages.insert(m_pages.begin() + dstPageIndex, page);
  for (int i = 0; i < getPageCount(); i++) m_pages[i]->m_index = i;
  assert(page->getIndex() == dstPageIndex);
}
References TPalette::Page::getIndex(), and getPageCount().
mutex()
QMutex * TPalette::mutex () inline
Returns the palette's mutex.
nextShortcutScope()
void TPalette::nextShortcutScope (bool invert)
{
  if (invert) {
    if (m_shortcutScopeIndex > 0)
      m_shortcutScopeIndex -= 1;
    else
      m_shortcutScopeIndex = getPage(0)->getStyleCount() / 10;
  } else {
    if ((m_shortcutScopeIndex + 1) * 10 < getPage(0)->getStyleCount())
      m_shortcutScopeIndex += 1;
    else
      m_shortcutScopeIndex = 0;
  }
}
saveData()
void TPalette::saveData (TOStream & os) override virtual
I/O palette load function.
Implements TPersist.
{
  os.child("version") << 71 << 0;  // Inserting the version tag at this level.
  // This is necessary to support the tpl format
  if (m_refImgPath !=
      TFilePath()) {  // since it performs *untagged* stream output
    if (m_areRefLevelFidsSpecified) {
      std::map<std::string, std::string> attr;
      attr["fids"] = fidsToString(m_refLevelFids);
      os.openChild("refImgPath", attr);
    } else
      os.openChild("refImgPath");
    os << m_refImgPath;  // (the palette is streamed directly).
    os.closeChild();
  }
  os.openChild("styles");
  {
    for (int i = 0; i < getStyleCount(); ++i) {
      TColorStyleP style = m_styles[i].second;
      if (style->getPickedPosition().pos == TPoint())
        os.openChild("style");
      else {
        std::map<std::string, std::string> attr;
        attr["pickedpos"] = pointToString(style->getPickedPosition());
        os.openChild("style", attr);
      }
      {
        StyleWriter w(os, i);
        style->save(w);
      }
      os.closeChild();
    }
  }
  os.closeChild();
  os.openChild("stylepages");
  {
    for (int i = 0; i < getPageCount(); ++i) {
      Page *page = getPage(i);
      os.openChild("page");
      {
        os.child("name") << page->getName();
        os.openChild("indices");
        {
          int m = page->getStyleCount();
          for (int j = 0; j < m; ++j) os << page->getStyleId(j);
        }
        os.closeChild();
      }
      os.closeChild();
    }
  }
  os.closeChild();
  if (isAnimated()) {
    os.openChild("animation");
    {
      StyleAnimationTable::iterator sat, saEnd = m_styleAnimationTable.end();
      for (sat = m_styleAnimationTable.begin(); sat != saEnd; ++sat) {
        int styleId               = sat->first;
        StyleAnimation &animation = sat->second;
        std::map<std::string, std::string> attributes;
        attributes["id"] = std::to_string(styleId);
        os.openChild("style", attributes);
        {
          StyleAnimation::iterator kt, kEnd = animation.end();
          for (kt = animation.begin(); kt != kEnd; ++kt) {
            int frame = kt->first;
            TColorStyle *cs = kt->second.getPointer();
            assert(cs);
            attributes.clear();
            attributes["frame"] = std::to_string(frame);
            /*os.openChild("keycolor", attributes);                       // Up
            to Toonz 7.0, animations saved os << cs->getMainColor(); // the main
            color only os.closeChild();*/  //
            os.openChild("keyframe", attributes);
            {
              StyleWriter w(os, sat->first);
              kt->second->save(w);
            }
            os.closeChild();
          }
        }
        os.closeChild();
      }
    }
    os.closeChild();
  }
  // salvo gli shortcuts solo se sono non standard
  int i;
  for (i = 0; i < 10; ++i)
    if (getShortcutValue('0' + i) != i) break;
  if (i < 10) {
    os.openChild("shortcuts");
    {
      for (i = 0; i < 10; i++) os << getShortcutValue('0' + i);
    }
    os.closeChild();
  }
  if (isLocked()) {
    os.openChild("lock");
    os << 1;
    os.closeChild();
  }
}
References TOStream::child(), TOStream::closeChild(), TPalette::Page::getName(), getPage(), getPageCount(), getShortcutValue(), TPalette::Page::getStyleCount(), getStyleCount(), TPalette::Page::getStyleId(), isAnimated(), isLocked(), TOStream::openChild(), and TColorStyle::save().
setAskOverwriteFlag()
void TPalette::setAskOverwriteFlag (bool askOverwriteFlag) inline
if the palette is merged from studio palette, this function will modify the original names.
< Sets the ask-overwrite flag.
{
    m_askOverwriteFlag = askOverwriteFlag;
  }
setCurrentStyleId()
void TPalette::setCurrentStyleId (int id) inline
{ m_currentStyleId = id; }
setDirtyFlag()
void TPalette::setDirtyFlag (bool dirtyFlag) inline
Parameters
dirtyFlag Declares the palette changed with respect to the last saved state.
  {
    m_dirtyFlag = dirtyFlag;
    // synchronize with the dirty flag
    m_askOverwriteFlag = dirtyFlag;
  }
Referenced by StudioPaletteTreeViewer::convertToStudioPalette(), StudioPaletteTreeViewer::loadInCurrentPalette(), StudioPaletteTreeViewer::onCurrentItemChanged(), StudioPaletteTreeViewer::onItemSelectionChanged(), StudioPaletteTreeViewer::replaceCurrentPalette(), TXshSimpleLevel::save(), and PaletteViewer::setIsLocked().
setFrame()
void TPalette::setFrame (int frame)
Sets the index of the current frame.
{
  QMutexLocker muLock(&m_mutex);
  if (m_currentFrame == frame) return;
  m_currentFrame = frame;
  StyleAnimationTable::iterator sat, saEnd = m_styleAnimationTable.end();
  for (sat = m_styleAnimationTable.begin(); sat != saEnd; ++sat) {
    StyleAnimation &animation = sat->second;
    assert(!animation.empty());
    // Retrieve the associated style to interpolate
    int styleId = sat->first;
    assert(0 <= styleId && styleId < getStyleCount());
    TColorStyle *cs = getStyle(styleId);
    assert(cs);
    // Build the keyframes interval containing frame
    StyleAnimation::iterator j0, j1;
    j1 = animation.lower_bound(
        frame);  // j1 is the first element:  j1->first >= frame
    if (j1 == animation.begin())
      cs->copy(*j1->second);
    else {
      j0 = j1, --j0;
      assert(j0->first <= frame);
      if (j1 == animation.end())
        cs->copy(*j0->second);
      else {
        assert(frame <= j1->first);
        cs->assignBlend(*j0->second, *j1->second,
                        (frame - j0->first) / double(j1->first - j0->first));
      }
    }
  }
}
References TColorStyle::assignBlend(), TColorStyle::copy(), getStyle(), and getStyleCount().
Referenced by Stage::RasterPainter::onVectorImage(), and ToonzImageIconRenderer::run().
setGlobalName()
void TPalette::setGlobalName (std::wstring name) inline
Assigns the name of the palette.
Referenced by StudioPaletteTreeViewer::convertToStudioPalette().
setIsCleanupPalette()
void TPalette::setIsCleanupPalette (bool on)
Sets the palette's identity as a cleanup palette.
{ m_isCleanupPalette = on; }
setIsLocked()
void TPalette::setIsLocked (bool lock) inline
Parameters
lock Sets lock/unlock to the palette.
  {
    m_isLocked = lock;
  }
Referenced by PaletteViewer::setIsLocked().
setKeyframe()
void TPalette::setKeyframe (int styleId, int frame)
Sets a keyframe at the specified frame of styleId's
{
  assert(styleId >= 0 && styleId < getStyleCount());
  assert(frame >= 0);
  StyleAnimationTable::iterator sat = m_styleAnimationTable.find(styleId);
  if (sat == m_styleAnimationTable.end())
    sat =
        m_styleAnimationTable.insert(std::make_pair(styleId, StyleAnimation()))
            .first;
  assert(sat != m_styleAnimationTable.end());
  StyleAnimation &animation = sat->second;
  animation[frame]          = getStyle(styleId)->clone();
}
References TColorStyle::clone(), getStyle(), and getStyleCount().
setPaletteName()
void TPalette::setPaletteName (std::wstring name) inline
Sets the name of the palette.
Referenced by TXshSimpleLevel::setPalette().
setRefImg()
void TPalette::setRefImg (const TImageP & img)
Associates an image to this palette, that is an image in the frame
{
  m_refImg = img;
  if (img) {
    assert(img->getPalette() == 0);
  }
}
Referenced by TXshSimpleLevel::load(), and ColorModelViewer::loadCurrentFrame().
setRefImgPath()
void TPalette::setRefImgPath (const TFilePath & fp)
Sets the path filename of the reference image.
{
  m_refImgPath = refImgPath;
}
Referenced by PaletteViewer::dropEvent(), and ColorModelViewer::loadCurrentFrame().
setRefLevelFids()
void TPalette::setRefLevelFids (const std::vector< TFrameId > fids, bool specified)
Associates the list of frames
{
  m_refLevelFids             = fids;
  m_areRefLevelFidsSpecified = specified;
}
Referenced by TXshSimpleLevel::load(), and ColorModelViewer::loadCurrentFrame().
setRootDir()
void TPalette::setRootDir (const TFilePath & fp) static
It must be specified to save textures in
{
  StyleWriter::setRootDir(fp);
  StyleReader::setRootDir(fp);
}
setShortcutValue()
void TPalette::setShortcutValue (int key, int styleId)
Associates the specified key to a styleId.
{
  assert('0' <= key && key <= '9');
  assert(styleId == -1 || 0 <= styleId && styleId < getStyleCount());
  if (styleId == -1)
    m_shortcuts.erase(key);
  else {
    std::map<int, int>::iterator it;
    for (it = m_shortcuts.begin(); it != m_shortcuts.end(); ++it)
      if (it->second == styleId) {
        m_shortcuts.erase(it);
        break;
      }
    m_shortcuts[key] = styleId;
  }
}
References getStyleCount().
Referenced by loadData().
setStyle() [1/2]
void TPalette::setStyle (int styleId, const TPixelRGBM32 & color)
Replaces the style with the
{
  setStyle(styleId, new TSolidColorStyle(color));
}
References setStyle().
setStyle() [2/2]
void TPalette::setStyle (int styleId, TColorStyle * style)
Replaces the style with the specified style id.
Remarks
Style ownserhip is surrendered to the palette.
Any existing style's animation will be discarded.
{
  std::unique_ptr<TColorStyle> styleOwner(style);
  int styleCount = getStyleCount();
  if (0 <= styleId && styleId < styleCount) {
    // Find out if the supplied style is already in the palette
    // with a different style id. In that case, bail out as a noop.
    for (int i = 0; i < styleCount; ++i)
      if (style == getStyle(i)) return;
    // Substitution can take place
    if (typeid(*m_styles[styleId].second.getPointer()) != typeid(*style))
      m_styleAnimationTable.erase(styleId);
    m_styles[styleId].second = styleOwner.release();
  }
}
References getStyle(), and getStyleCount().
Referenced by setStyle().
setVersion()
void TPalette::setVersion (int v) inline
Sets the palette's version number.
Friends And Related Function Documentation
Page
friend class Page friend
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/tpalette.h
E:/opentoonz/toonz/sources/common/tvrender/tpalette.cpp