opentoonz: ChildStack Class Reference
ChildStack Class Reference
The ChildStack class provides a stack of xsheet and allows its management.
#include <childstack.h>
Classes
class Node
The Node class is a container of element necessary to define a sub-xsheet.
Public Member Functions
ChildStack (ToonzScene *scene)
~ChildStack ()
void clear ()
bool openChild (int row, int col)
bool closeChild (int &row, int &col)
TXshChildLevel * createChild (int row, int col)
int getAncestorCount () const
TXsheet * getTopXsheet () const
TXsheet * getXsheet () const
void setXsheet (TXsheet *xsheet)
std::pair< TXsheet *, int > getAncestor (int row) const
bool getAncestorAffine (TAffine &aff, int row) const
Detailed Description
The ChildStack class provides a stack of xsheet and allows its management.
The class has a vector of ChildStack::Node, a pointer to current TXsheet getXsheet(), and a pointer to current ToonzScene m_scene. The ChildStack::Node vector is as a subxsheet vector.
Through this class you can create, open openChild(), close closeChild() or clear clear() a sub-xsheet.
The class provides a collection of functions that return set of subxsheet properties, getAncestor(), getAncestorCount(), getAncestorAffine(), getTopXsheet().
Constructor & Destructor Documentation
ChildStack()
ChildStack::ChildStack (ToonzScene * scene)
Constructs a ChildStack with default value and current scene.
    : m_scene(scene), m_xsheet(new TXsheet()) {
  m_xsheet->setScene(m_scene);
  m_xsheet->addRef();
}
References TXsheet::setScene().
~ChildStack()
ChildStack::~ChildStack ()
Destroys the ChildStack object.
{
  m_xsheet->release();
  clearPointerContainer(m_stack);
}
Member Function Documentation
clear()
void ChildStack::clear ()
Clear child stack.
                       {
  m_xsheet->clearAll();
  m_xsheet->setScene(m_scene);
  clearPointerContainer(m_stack);
}
References TXsheet::clearAll(), and TXsheet::setScene().
Referenced by ToonzScene::clear().
closeChild()
bool ChildStack::closeChild (int & row, int & col)
Close current xsheet if is a sub-xsheet. Return false if stack is empty. Set row, col to sub-xsheet row and column.
{
  if (m_stack.empty()) return false;
  TXsheet *childXsh = m_xsheet;
  childXsh
      ->updateFrameCount();  // non dovrebbe essere necessario, ma non si sa mai
  int childFrameCount = childXsh->getFrameCount();
  Node *node = m_stack.back();
  m_stack.pop_back();
  TXsheet *parentXsh = node->m_xsheet;
  TXshChildLevelP cl = node->m_cl;
  row                = node->m_row;
  col                = node->m_col;
  bool justCreated   = node->m_justCreated;
  delete node;
  m_xsheet = parentXsh;
  m_xsheet->updateFrameCount();
  // if(cl) cl->invalidateIcon();
  TXsheet *xsh = m_xsheet;
  if (justCreated) {
    assert(xsh->getCell(row, col).m_level.getPointer() == cl.getPointer());
    if (childFrameCount > 1) {
      xsh->insertCells(row + 1, col, childFrameCount - 1);
      for (int i = 1; i < childFrameCount; i++)
        xsh->setCell(row + i, col, TXshCell(cl.getPointer(), TFrameId(1 + i)));
    }
  }
  return true;
}
References TXsheet::getCell(), TXsheet::getFrameCount(), TXsheet::insertCells(), and TXsheet::updateFrameCount().
createChild()
TXshChildLevel * ChildStack::createChild (int row, int col)
Create a sub-xsheet in cell row, col and returns the new child level.
Column col must be empty, The current xsheet remains unchanged
{
  TXshLevel *xl = m_scene->createNewLevel(CHILD_XSHLEVEL);
  m_xsheet->setCell(row, col, TXshCell(xl, TFrameId(1)));
  TXshCell cell = m_xsheet->getCell(row, col);
  return cell.m_level->getChildLevel();
}
References ToonzScene::createNewLevel(), TXsheet::getCell(), and TXshLevel::getChildLevel().
getAncestor()
std::pair< TXsheet *, int > ChildStack::getAncestor (int row) const
Return the ancestor and respective frame that contains row.
Useful by edit in place. Oss.: row of current xsheet.
{
  TXsheet *xsh = m_xsheet;
  int i        = m_stack.size() - 1;
  while (i >= 0) {
    std::map<int, int>::const_iterator it = m_stack[i]->m_rowTable.find(row);
    if (it == m_stack[i]->m_rowTable.end()) break;
    row = it->second;
    xsh = m_stack[i]->m_xsheet;
    i--;
  }
  return std::make_pair(xsh, row);
}
getAncestorAffine()
bool ChildStack::getAncestorAffine (TAffine & aff, int row) const
Set aff to ancestor affine in row. Return true if all ancestors are visible in row.
{
  aff   = TAffine();
  int i = m_stack.size() - 1;
  while (i >= 0) {
    std::map<int, int>::const_iterator it = m_stack[i]->m_rowTable.find(row);
    if (it == m_stack[i]->m_rowTable.end()) break;
    row        = it->second;
    Node *node = m_stack[i];
    TAffine aff2;
    if (!getColumnPlacement(aff2, node->m_xsheet, row, node->m_col, false))
      return false;
    aff = aff2 * aff;
    i--;
  }
  return true;
}
getAncestorCount()
int ChildStack::getAncestorCount () const
Return ancestor number, size of ChildStack::Node vector.
{ return m_stack.size(); }
getTopXsheet()
TXsheet * ChildStack::getTopXsheet () const
Return a pointer to top xsheet of stack, if stack is empty to current xsheet.
{
  return m_stack.empty() ? m_xsheet : m_stack.front()->m_xsheet;
}
Referenced by ToonzScene::getSoundColumns(), ToonzScene::getTopXsheet(), and ToonzScene::save().
getXsheet()
TXsheet * ChildStack::getXsheet () const inline
Return a pointer to current xsheet.
{ return m_xsheet; }
Referenced by ToonzScene::getXsheet().
openChild()
bool ChildStack::openChild (int row, int col)
Open a sub-xsheet in cell row, col. Return true if it's possible.
If cell row, col is empty create a new sub-xheet empty and return true, if cell contains a sub-xsheet set this as current xsheet and return true, if cell contains another element return false.
{
  TXshChildLevel *childLevel = 0;
  TXshCell cell              = m_xsheet->getCell(row, col);
  if (!cell.m_level) {
    return false;
  } else
    childLevel = cell.m_level->getChildLevel();
  if (!childLevel) return false;
  TXsheet *childXsheet = childLevel->getXsheet();
  Node *node           = new Node();
  node->m_row          = row;
  node->m_col          = col;
  node->m_xsheet       = m_xsheet;
  node->m_cl           = childLevel;
  node->m_justCreated  = !cell.m_level;
  int r0 = 0, r1 = -1;
  m_xsheet->getCellRange(col, r0, r1);
  for (int r = r0; r <= r1; r++) {
    TXshCell cell = m_xsheet->getCell(r, col);
    if (cell.m_level.getPointer() == childLevel) {
      int d = cell.m_frameId.getNumber() - 1;
      std::map<int, int>::iterator it = node->m_rowTable.find(d);
      if (it == node->m_rowTable.end()) node->m_rowTable[d] = r;
    }
  }
  m_stack.push_back(node);
  m_xsheet = childXsheet;
  return true;
}
References TXsheet::getCell(), TXsheet::getCellRange(), TXshLevel::getChildLevel(), and TXshChildLevel::getXsheet().
setXsheet()
void ChildStack::setXsheet (TXsheet * xsheet) inline
{ m_xsheet = xsheet; }
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/toonz/childstack.h
E:/opentoonz/toonz/sources/toonzlib/childstack.cpp