opentoonz: TThickQuadratic Class Reference
TThickQuadratic Class Reference final
#include <tcurves.h>
Public Member Functions
TThickQuadratic (const TPointD &p0, double thickP0, const TPointD &p1, double thickP1, const TPointD &p2, double thickP2)
thickP0, thickP1, thickP2 are thickness of quadratic control points
TThickQuadratic (const TThickPoint &p0, const TThickPoint &p1, const TThickPoint &p2)
TThickQuadratic (const TThickQuadratic &thickQuadratic)
TThickQuadratic (const TQuadratic &quadratic)
void setThickP0 (const TThickPoint &p)
Set the value of first control point P0 to TThickPoint p.
void setThickP1 (const TThickPoint &p)
Set the value of second control point P1 to TThickPoint p.
void setThickP2 (const TThickPoint &p)
Set the value of third control point P2 to TThickPoint p.
TThickPoint getThickPoint (double t) const
Return the TThickPoint of quadratic at parameter t.
TThickPoint getThickP0 () const
Return first control point P0.
TThickPoint getThickP1 () const
Return second control point P1.
TThickPoint getThickP2 () const
Return third control point P2.
void split (double t, TThickQuadratic &first, TThickQuadratic &second) const
TRectD getBBox () const
Public Member Functions inherited from TQuadratic
TQuadratic (const TPointD &p0, const TPointD &p1, const TPointD &p2)
p0,p1,p2 are the three control points
TQuadratic (const TQuadratic &src)
TQuadratic & operator= (const TQuadratic &src)
TPointD getPoint (double t) const
Return the point of quadratic at parameter t.
double getX (double t) const
double getY (double t) const
TPointD getSpeed (double t) const
Return speed of quadratic at parameter t.
double getSpeedY (double t) const
Return the y value of quadratic speed at parameter t.
TPointD getAcceleration (double=0) const
Return acceleration of quadratic.
double getCurvature (double t) const
Return curvature of quadratic at parameter t.
TPointD getP0 () const
Return first control point P0.
TPointD getP1 () const
Return second control point P1.
TPointD getP2 () const
Return third control point P2.
void setP0 (const TPointD &p)
Set the value of first control point P0 to p.
void setP1 (const TPointD &p)
Set the value of second control point P1 to p.
void setP2 (const TPointD &p)
Set the value of third control point P2 to p.
bool operator== (const TQuadratic &c) const
bool operator!= (const TQuadratic &c) const
double getT (const TPointD &p) const
Return a parameter that correspond to the point p in the quadratic.
int getX (double y, double &x0, double &x1) const
int getY (double x, double &y0, double &y1) const
void split (double t, TQuadratic &first, TQuadratic &second) const
TRectD getBBox () const
Return rect that contains the quadratic.
double getLength (double t0, double t1) const
double getLength (double t1=1) const
double getApproximateLength (double t0, double t1, double error) const
void reverse ()
Protected Attributes
double m_thickP0
double m_thickP1
double m_thickP2
Protected Attributes inherited from TQuadratic
TPointD m_p0
TPointD m_p1
TPointD m_p2
Detailed Description
Class TThickQuadratic: manage a curve with thick !relates TQuadratic
Constructor & Destructor Documentation
TThickQuadratic() [1/5]
TThickQuadratic::TThickQuadratic ()
    : TQuadratic(), m_thickP0(0), m_thickP1(0), m_thickP2(0) {}
TThickQuadratic() [2/5]
TThickQuadratic::TThickQuadratic (const TPointD & p0, double thickP0, const TPointD & p1, double thickP1, const TPointD & p2, double thickP2)
thickP0, thickP1, thickP2 are thickness of quadratic control points
    : TQuadratic(p0, p1, p2)
    , m_thickP0(thickP0)
    , m_thickP1(thickP1)
    , m_thickP2(thickP2) {}
TThickQuadratic() [3/5]
TThickQuadratic::TThickQuadratic (const TThickPoint & p0, const TThickPoint & p1, const TThickPoint & p2)
    : TQuadratic(TPointD(p0.x, p0.y), TPointD(p1.x, p1.y), TPointD(p2.x, p2.y))
    , m_thickP0(p0.thick)
    , m_thickP1(p1.thick)
    , m_thickP2(p2.thick) {}
TThickQuadratic() [4/5]
TThickQuadratic::TThickQuadratic (const TThickQuadratic & thickQuadratic)
    : TQuadratic(thickQuadratic)
    , m_thickP0(thickQuadratic.m_thickP0)
    , m_thickP1(thickQuadratic.m_thickP1)
    , m_thickP2(thickQuadratic.m_thickP2) {}
TThickQuadratic() [5/5]
TThickQuadratic::TThickQuadratic (const TQuadratic & quadratic)
    : TQuadratic(q), m_thickP0(0.0), m_thickP1(0.0), m_thickP2(0.0) {}
Member Function Documentation
getBBox()
TRectD TThickQuadratic::getBBox () const
{
  TRectD bBox = TQuadratic::getBBox();
  double maxRadius = std::max({m_thickP0, m_thickP1, m_thickP2});
  if (maxRadius > 0) {
    //  bBox.enlarge(maxRadius) si comporta male nel caso bBox.isEmpty()
    bBox.x0 -= maxRadius;
    bBox.y0 -= maxRadius;
    bBox.x1 += maxRadius;
    bBox.y1 += maxRadius;
  }
  return bBox;
}
getThickP0()
TThickPoint TThickQuadratic::getThickP0 () const inline
Return first control point P0.
{ return TThickPoint(m_p0, m_thickP0); }
Referenced by TStroke::getControlPoint(), and TStroke::print().
getThickP1()
TThickPoint TThickQuadratic::getThickP1 () const inline
Return second control point P1.
{ return TThickPoint(m_p1, m_thickP1); }
Referenced by TStroke::getControlPoint(), and TStroke::print().
getThickP2()
TThickPoint TThickQuadratic::getThickP2 () const inline
Return third control point P2.
{ return TThickPoint(m_p2, m_thickP2); }
Referenced by TStroke::getControlPoint(), and TStroke::print().
getThickPoint()
TThickPoint TThickQuadratic::getThickPoint (double t) const
Return the TThickPoint of quadratic at parameter t.
{
  double s = 1 - t;
  return TThickPoint(
      m_p0 * s * s + 2 * t * s * m_p1 + t * t * m_p2,
      m_thickP0 * s * s + 2 * t * s * m_thickP1 + t * t * m_thickP2);
}
Referenced by TStroke::getNearChunks(), TStroke::getThickPoint(), and TStroke::getThickPointAtLength().
setThickP0()
void TThickQuadratic::setThickP0 (const TThickPoint & p)
Set the value of first control point P0 to TThickPoint p.
{
  m_p0      = p;
  m_thickP0 = p.thick;
}
setThickP1()
void TThickQuadratic::setThickP1 (const TThickPoint & p)
Set the value of second control point P1 to TThickPoint p.
{
  m_p1      = p;
  m_thickP1 = p.thick;
}
setThickP2()
void TThickQuadratic::setThickP2 (const TThickPoint & p)
Set the value of third control point P2 to TThickPoint p.
{
  m_p2      = p;
  m_thickP2 = p.thick;
}
split()
void TThickQuadratic::split (double t, TThickQuadratic & first, TThickQuadratic & second) const
{
  double dt;
  TPointD p;
  dt = 1.0 - t;
  // control points
  left.m_p0  = m_p0;
  right.m_p2 = m_p2;
  left.m_p1  = dt * m_p0 + t * m_p1;
  right.m_p1 = dt * m_p1 + t * m_p2;
  p          = dt * left.m_p1 + t * right.m_p1;
  left.m_p2 = right.m_p0 = p;
  // thick points
  left.m_thickP0  = m_thickP0;
  right.m_thickP2 = m_thickP2;
  left.m_thickP1  = dt * m_thickP0 + t * m_thickP1;
  right.m_thickP1 = dt * m_thickP1 + t * m_thickP2;
  // store thickness of intermediary point
  p.x = dt * left.m_thickP1 + t * right.m_thickP1;
  left.m_thickP2 = right.m_thickP0 = p.x;
}
Member Data Documentation
m_thickP0
double TThickQuadratic::m_thickP0 protected
m_thickP1
double TThickQuadratic::m_thickP1 protected
m_thickP2
double TThickQuadratic::m_thickP2 protected
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/tcurves.h
E:/opentoonz/toonz/sources/common/tgeometry/tcurves.cpp