opentoonz: DragSelectionTool::FourPoints Class Reference
DragSelectionTool::FourPoints Class Reference
Public Member Functions
FourPoints (TPointD p00, TPointD p01, TPointD p10, TPointD p11)
void setP00 (TPointD p)
void setP01 (TPointD p)
void setP10 (TPointD p)
void setP11 (TPointD p)
TPointD getP00 () const
TPointD getP01 () const
TPointD getP10 () const
TPointD getP11 () const
FourPoints orderedPoints () const
TPointD getBottomLeft () const
TPointD getBottomRight () const
TPointD getTopRight () const
TPointD getTopLeft () const
TPointD getPoint (int index) const
void setPoint (int index, const TPointD &p)
FourPoints enlarge (double d)
bool isEmpty ()
void empty ()
bool contains (TPointD p)
TRectD getBox () const
FourPoints & operator= (const TRectD &r)
bool operator== (const FourPoints &p) const
FourPoints operator* (const TAffine &aff) const
Detailed Description
Constructor & Destructor Documentation
FourPoints() [1/2]
DragSelectionTool::FourPoints::FourPoints (TPointD p00, TPointD p01, TPointD p10, TPointD p11) inline
      : m_p00(p00), m_p01(p01), m_p10(p10), m_p11(p11) {}
FourPoints() [2/2]
DragSelectionTool::FourPoints::FourPoints () inline
      : m_p00(TPointD())
      , m_p01(TPointD())
      , m_p10(TPointD())
      , m_p11(TPointD()) {}
Member Function Documentation
contains()
bool FourPoints::contains (TPointD p)
{
  double maxDistance =
      std::max(tdistance2(getP00(), getP11()), tdistance2(getP10(), getP01()));
  TPointD outP = p + maxDistance * TPointD(1, 1);
  TSegment segment(outP, p);
  std::vector<DoublePair> d;
  int inters = intersect(TSegment(getP00(), getP10()), segment, d);
  inters += intersect(TSegment(getP10(), getP11()), segment, d);
  inters += intersect(TSegment(getP11(), getP01()), segment, d);
  inters += intersect(TSegment(getP01(), getP00()), segment, d);
  return inters % 2 == 1;
}
empty()
void FourPoints::empty ()
{
  m_p00 = TPointD();
  m_p01 = TPointD();
  m_p10 = TPointD();
  m_p11 = TPointD();
}
enlarge()
FourPoints FourPoints::enlarge (double d)
{
  TPointD v   = normalize(getP10() - getP00());
  TPointD p00 = getP00() - d * v;
  TPointD p10 = getP10() + d * v;
  v           = normalize(getP11() - getP10());
  p10         = p10 - d * v;
  TPointD p11 = getP11() + d * v;
  v           = normalize(getP01() - getP11());
  p11         = p11 - d * v;
  TPointD p01 = getP01() + d * v;
  v           = normalize(getP00() - getP01());
  p01         = p01 - d * v;
  p00         = p00 + d * v;
  return FourPoints(p00, p01, p10, p11);
}
getBottomLeft()
TPointD DragSelectionTool::FourPoints::getBottomLeft () const inline
{ return orderedPoints().getP00(); }
getBottomRight()
TPointD DragSelectionTool::FourPoints::getBottomRight () const inline
{ return orderedPoints().getP10(); }
getBox()
TRectD FourPoints::getBox () const
{
  double x0 = std::min({getP00().x, getP10().x, getP01().x, getP11().x});
  double y0 = std::min({getP00().y, getP10().y, getP01().y, getP11().y});
  double x1 = std::max({getP00().x, getP10().x, getP01().x, getP11().x});
  double y1 = std::max({getP00().y, getP10().y, getP01().y, getP11().y});
  return TRectD(TPointD(x0, y0), TPointD(x1, y1));
}
getP00()
TPointD DragSelectionTool::FourPoints::getP00 () const inline
{ return m_p00; }
getP01()
TPointD DragSelectionTool::FourPoints::getP01 () const inline
{ return m_p01; }
getP10()
TPointD DragSelectionTool::FourPoints::getP10 () const inline
{ return m_p10; }
getP11()
TPointD DragSelectionTool::FourPoints::getP11 () const inline
{ return m_p11; }
getPoint()
TPointD FourPoints::getPoint (int index) const
Point = index: P00 = 0; P10 = 1; P11 = 2; P01 = 3; P0M = 4; P1M = 5; PM1 = 6; P0M = 7.
{
  if (index == 0)
    return m_p00;
  else if (index == 1)
    return m_p10;
  else if (index == 2)
    return m_p11;
  else if (index == 3)
    return m_p01;
  else if (index == 4)
    return (m_p00 + m_p10) * 0.5;
  else if (index == 5)
    return (m_p10 + m_p11) * 0.5;
  else if (index == 6)
    return (m_p11 + m_p01) * 0.5;
  else if (index == 7)
    return (m_p01 + m_p00) * 0.5;
  return TPointD();
}
Referenced by DragSelectionTool::Scale::bboxScale(), DragSelectionTool::Scale::bboxScaleInCenter(), DragSelectionTool::Scale::computeScaleValue(), DragSelectionTool::Scale::getNewCenter(), DragSelectionTool::Scale::getScaledPoint(), DragSelectionTool::VectorScaleTool::transform(), and DragSelectionTool::VectorDeformTool::transformWholeLevel().
getTopLeft()
TPointD DragSelectionTool::FourPoints::getTopLeft () const inline
{ return orderedPoints().getP01(); }
getTopRight()
TPointD DragSelectionTool::FourPoints::getTopRight () const inline
{ return orderedPoints().getP11(); }
isEmpty()
bool FourPoints::isEmpty ()
{
  return ((getP00().x == getP01().x && getP01().x == getP10().x &&
           getP10().x == getP11().x) ||
          (getP00().y == getP01().y && getP01().y == getP10().y &&
           getP10().y == getP11().y));
}
operator*()
FourPoints FourPoints::operator* (const TAffine & aff) const
{
  FourPoints p;
  p.setP00(aff * getP00());
  p.setP10(aff * getP10());
  p.setP11(aff * getP11());
  p.setP01(aff * getP01());
  return p;
}
operator=()
FourPoints & FourPoints::operator= (const TRectD & r)
{
  setP00(r.getP00());
  setP01(r.getP01());
  setP10(r.getP10());
  setP11(r.getP11());
  return *this;
}
operator==()
bool FourPoints::operator== (const FourPoints & p) const
{
  return getP00() == p.getP00() && getP01() == p.getP01() &&
         getP10() == p.getP10() && getP11() == p.getP11();
}
orderedPoints()
FourPoints FourPoints::orderedPoints () const
Order four point from BottomLeft to TopRight.
{
  FourPoints newPoints;
  int i;
  std::vector<TPointD> allPoints;
  allPoints.push_back(m_p00);
  allPoints.push_back(m_p01);
  allPoints.push_back(m_p10);
  allPoints.push_back(m_p11);
  int minXindex1 = tminPoint(allPoints, true);
  std::vector<TPointD> points;
  for (i = 0; i < 4; i++)
    if (i != minXindex1) points.push_back(allPoints[i]);
  int minXindex2 = tminPoint(points, true);
  int index = tminPoint(allPoints[minXindex1], points[minXindex2], false);
  TPointD newPoint1 = allPoints[minXindex1];
  TPointD newPoint2 = points[minXindex2];
  if (index == 1) std::swap(newPoint1, newPoint2);
  newPoints.setP00(newPoint1);
  newPoints.setP01(newPoint2);
  std::vector<TPointD> points2;
  for (i = 0; i < 3; i++)
    if (i != minXindex2) points2.push_back(points[i]);
  index = tminPoint(points2, false);
  newPoints.setP10(points2[index]);
  newPoints.setP11(points2[(index == 0) ? 1 : 0]);
  return newPoints;
}
setP00()
void DragSelectionTool::FourPoints::setP00 (TPointD p) inline
{ m_p00 = p; }
setP01()
void DragSelectionTool::FourPoints::setP01 (TPointD p) inline
{ m_p01 = p; }
setP10()
void DragSelectionTool::FourPoints::setP10 (TPointD p) inline
{ m_p10 = p; }
setP11()
void DragSelectionTool::FourPoints::setP11 (TPointD p) inline
{ m_p11 = p; }
setPoint()
void FourPoints::setPoint (int index, const TPointD & p)
Point = index: P00 = 0; P10 = 1; P11 = 2; P01 = 3.
{
  if (index == 0)
    m_p00 = p;
  else if (index == 1)
    m_p10 = p;
  else if (index == 2)
    m_p11 = p;
  else if (index == 3)
    m_p01 = p;
}
Referenced by DragSelectionTool::Scale::bboxScale(), and DragSelectionTool::Scale::bboxScaleInCenter().
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/tnztools/selectiontool.h
E:/opentoonz/toonz/sources/tnztools/selectiontool.cpp