opentoonz: GeometricTool Class Reference
GeometricTool Class Reference final
Public Member Functions
GeometricTool (int targetType)
ToolType getToolType () const override
void updateTranslation () override
void addPrimitive (Primitive *p)
void changeType (std::wstring name)
bool preLeftButtonDown () override
void leftButtonDown (const TPointD &p, const TMouseEvent &e) override
void leftButtonDrag (const TPointD &p, const TMouseEvent &e) override
void leftButtonUp (const TPointD &p, const TMouseEvent &e) override
void leftButtonDoubleClick (const TPointD &p, const TMouseEvent &e) override
bool keyDown (QKeyEvent *event) override
void onImageChanged () override
Notifies changes in the image in use.
void rightButtonDown (const TPointD &p, const TMouseEvent &e) override
void mouseMove (const TPointD &p, const TMouseEvent &e) override
void onActivate () override
Callback invoked whenever the tool activates.
void onDeactivate () override
Callback for tool deactivation, includes tool switch.
void onEnter () override
Callback for the mouse entering the viewer area.
void draw () override
Draws the tool on the viewer.
int getCursorId () const override
Returns the type of cursor used by the tool.
int getColorClass () const
TPropertyGroup * getProperties (int idx) override
bool onPropertyChanged (std::string propertyName) override
void addStroke ()
Public Member Functions inherited from TTool
TTool (std::string toolName)
every tool (invoking updateTranslation() for each).
virtual ToolType getToolType () const =0
ToolTargetType getTargetType () const
std::string getName () const
virtual ToolOptionsBox * createOptionsBox ()
void setViewer (Viewer *viewer)
Viewer * getViewer () const
double getPixelSize () const
void invalidate (const TRectD &rect=TRectD())
int pick (const TPointD &p)
bool isPicking () const
virtual void updateTranslation ()
virtual bool preLeftButtonDown ()
virtual void mouseMove (const TPointD &, const TMouseEvent &)
virtual void leftButtonDown (const TPointD &, const TMouseEvent &)
virtual void leftButtonDrag (const TPointD &, const TMouseEvent &)
virtual void leftButtonUp (const TPointD &, const TMouseEvent &)
virtual void leftButtonDoubleClick (const TPointD &, const TMouseEvent &)
virtual void rightButtonDown (const TPointD &, const TMouseEvent &)
virtual bool keyDown (QKeyEvent *)
virtual void onInputText (std::wstring, std::wstring, int, int)
virtual void onSetViewer ()
virtual void onActivate ()
Callback invoked whenever the tool activates.
virtual void onDeactivate ()
Callback for tool deactivation, includes tool switch.
virtual void onImageChanged ()
Notifies changes in the image in use.
virtual void onEnter ()
Callback for the mouse entering the viewer area.
virtual void onLeave ()
Callback for the mouse leaving the viewer area.
virtual void onFrameSwitched ()
virtual void reset ()
virtual void draw ()
Draws the tool on the viewer.
bool isActive () const
Used to know if a tool is active, (used in TextTool only).
void setActive (bool active)
virtual TPropertyGroup * getProperties (int)
virtual bool onPropertyChanged (std::string propertyName)
virtual TSelection * getSelection ()
Returns a pointer to the tool selection.
virtual int getCursorId () const
Returns the type of cursor used by the tool.
virtual bool isEventAcceptable (QEvent *e)
TXsheet * getXsheet () const
Returns a pointer to the actual Xsheet.
int getFrame ()
Returns the actual frame in use.
int getColumnIndex ()
Returns the actual column index.
TStageObjectId getObjectId () const
Returns a pointer to the actual stage object.
void notifyImageChanged ()
void notifyImageChanged (const TFrameId &fid)
images on the level view.
TFrameId getCurrentFid () const
Returns the number of the actual editing frame.
const TAffine & getMatrix () const
void setMatrix (const TAffine &matrix)
TAffine getCurrentColumnMatrix (int frame=-1) const
TAffine getCurrentColumnParentMatrix () const
TAffine getCurrentObjectParentMatrix () const
TAffine getCurrentObjectParentMatrix2 () const
TAffine getColumnMatrix (int index, int frame=-1) const
virtual void updateMatrix ()
virtual void addContextMenuItems (QMenu *menu)
void enable (bool on)
bool isEnabled () const
QString updateEnabled ()
virtual QString updateEnabled (int rowIndex, int columnIndex)
bool isColumnLocked (int columnIndex) const
void resetInputMethod ()
Resets Input Context (IME)
virtual bool isPencilModeActive ()
virtual bool isDragging () const
void setSelectedFrames (const std::set< TFrameId > &selectedFrames)
void tweenSelectedGuideStrokes ()
void tweenGuideStrokeToSelected ()
void flipGuideStrokeDirection (int mode)
Protected Attributes
Primitive * m_primitive
std::map< std::wstring, Primitive * > m_primitiveTable
PrimitiveParam m_param
std::wstring m_typeCode
bool m_active
bool m_firstTime
bool m_isRotatingOrMoving
bool m_wasCtrlPressed
TStroke * m_rotatedStroke
TPointD m_originalCursorPos
TPointD m_currentCursorPos
TPixel32 m_color
double m_lastRotateAngle
TPointD m_rotateCenter
TPointD m_lastMoveStrokePos
Protected Attributes inherited from TTool
std::string m_name
The tool's name.
Viewer * m_viewer
Tool's current viewer.
TAffine m_matrix
World-to-window reference change affine.
int m_targetType
The tool's image type target.
bool m_enabled
Whether the tool allows user interaction.
bool m_active
bool m_picking
Additional Inherited Members
Public Types inherited from TTool
enum ToolType {
GenericTool = 1 , ColumnTool = 2 , LevelReadTool = 4 , LevelWriteTool ,
LevelTool = LevelReadTool | LevelWriteTool
}
Tool editing type.
enum ToolTargetType {
NoTarget = 0x0 , VectorImage = 0x1 , ToonzImage = 0x2 , RasterImage = 0x4 ,
MeshImage = 0x8 , Splines = 0x10 , LevelColumns = 0x20 , MeshColumns = 0x40 ,
EmptyTarget = 0x80 , CommonImages = VectorImage | ToonzImage | RasterImage , AllImages = CommonImages | MeshImage , Vectors = VectorImage | Splines ,
CommonLevels = CommonImages | LevelColumns , MeshLevels = MeshImage | MeshColumns , AllTargets = 0xffffffff
}
Object types the tool can operate on.
typedef TApplication Application
Static Public Member Functions inherited from TTool
static TTool * getTool (std::string toolName, ToolTargetType targetType)
static TApplication * getApplication ()
static void setApplication (TApplication *application)
static TXshCell getImageCell ()
Returns the level-frame pair to be edited by the tool.
static TImage * getImage (bool toBeModified, int subsampling=0)
Returns the image to be edited by the tool.
static TImage * touchImage ()
static void updateToolsPropertiesTranslation ()
static const std::set< TFrameId > & getSelectedFrames ()
Static Public Attributes inherited from TTool
static std::vector< CellOps > m_cellsData
static bool m_isLevelCreated = false
static bool m_isFrameCreated = false
static std::vector< TFrameId > m_oldFids
static std::vector< TFrameId > m_newFids
static bool m_isLevelRenumbererd = false
Protected Member Functions inherited from TTool
void bind (int targetType)
virtual void onSelectedFramesChanged ()
virtual QString disableString ()
Returns a custom reason to disable the tool.
Static Protected Attributes inherited from TTool
static TApplication * m_application = 0
static std::set< TFrameId > m_selectedFrames = std::set<TFrameId>()
Detailed Description
Constructor & Destructor Documentation
GeometricTool()
GeometricTool::GeometricTool (int targetType) inline
      : TTool("T_Geometric")
      , m_primitive(0)
      , m_param(targetType)
      , m_active(false)
      , m_isRotatingOrMoving(false)
      , m_rotatedStroke(0)
      , m_firstTime(true) {
    bind(targetType);
    if ((targetType & TTool::RasterImage) || (targetType & TTool::ToonzImage)) {
      addPrimitive(new RectanglePrimitive(&m_param, this, true));
      addPrimitive(new CirclePrimitive(&m_param, this, true));
      addPrimitive(new EllipsePrimitive(&m_param, this, true));
      addPrimitive(new LinePrimitive(&m_param, this, true));
      addPrimitive(new MultiLinePrimitive(&m_param, this, true));
      addPrimitive(new ArcPrimitive(&m_param, this, true));
      addPrimitive(new MultiArcPrimitive(&m_param, this, true));
      addPrimitive(new PolygonPrimitive(&m_param, this, true));
    } else  // targetType == 1
    {
      // vector
      addPrimitive(m_primitive = new RectanglePrimitive(&m_param, this, false));
      addPrimitive(new CirclePrimitive(&m_param, this, false));
      addPrimitive(new EllipsePrimitive(&m_param, this, false));
      addPrimitive(new LinePrimitive(&m_param, this, false));
      addPrimitive(new MultiLinePrimitive(&m_param, this, false));
      addPrimitive(new ArcPrimitive(&m_param, this, false));
      addPrimitive(new MultiArcPrimitive(&m_param, this, false));
      addPrimitive(new PolygonPrimitive(&m_param, this, false));
    }
  }
~GeometricTool()
GeometricTool::~GeometricTool () inline
                   {
    delete m_rotatedStroke;
    std::map<std::wstring, Primitive *>::iterator it;
    for (it = m_primitiveTable.begin(); it != m_primitiveTable.end(); ++it)
      delete it->second;
  }
Member Function Documentation
addPrimitive()
void GeometricTool::addPrimitive (Primitive * p) inline
{
    // TODO: aggiungere il controllo per evitare nomi ripetuti
    std::wstring name = ::to_wstring(p->getName());
    // wstring name = TStringTable::translate(p->getName());
    m_primitiveTable[name] = p;
    m_param.m_type.addValue(name);
  }
addStroke()
void GeometricTool::addStroke () inline
                   {
    if (!m_primitive) return;
    TStroke *stroke = 0;
    if (!m_isRotatingOrMoving) {
      stroke = m_primitive->makeStroke();
      if (!stroke) return;
      if (m_param.m_rotate.getValue()) {
        m_isRotatingOrMoving = true;
        m_rotatedStroke      = stroke;
        TRectD bbox          = stroke->getBBox();
        m_rotateCenter       = 0.5 * (bbox.getP11() + bbox.getP00());
        m_originalCursorPos  = m_currentCursorPos;
        m_lastRotateAngle    = 0;
        m_lastMoveStrokePos  = TPointD(0, 0);
        m_wasCtrlPressed     = false;
        const TTool::Application *app = TTool::getApplication();
        if (!app) {
          m_color = TPixel32::Red;
          return;
        }
        const TColorStyle *style = app->getCurrentLevelStyle();
        if (!style) {
          m_color = TPixel32::Red;
          return;
        }
        m_color = style->getAverageColor();
        return;
      }
    } else {
      stroke               = m_rotatedStroke;
      m_isRotatingOrMoving = false;
      m_rotatedStroke      = 0;
    }
    TStroke::OutlineOptions &options = stroke->outlineOptions();
    options.m_capStyle               = m_param.m_capStyle.getIndex();
    options.m_joinStyle              = m_param.m_joinStyle.getIndex();
    options.m_miterUpper             = m_param.m_miterJoinLimit.getValue();
    TImage *image = getImage(true);
    TToonzImageP ti(image);
    TVectorImageP vi(image);
    TRasterImageP ri(image);
    TXshSimpleLevel *sl =
        TTool::getApplication()->getCurrentLevel()->getSimpleLevel();
    TFrameId id = getCurrentFid();
    /*-- ToonzImage --*/
    if (ti) {
      int styleId    = TTool::getApplication()->getCurrentLevelStyleIndex();
      bool selective = m_param.m_selective.getValue();
      bool filled = false;
      stroke->setStyle(styleId);
      double hardness = m_param.m_hardness.getValue() * 0.01;
      TRect savebox;
      if (hardness == 1 || m_param.m_pencil.getValue()) {
        TUndoManager::manager()->add(new UndoRasterPencil(
            sl, id, stroke, selective, filled, !m_param.m_pencil.getValue(),
            m_isFrameCreated, m_isLevelCreated, m_primitive->getName()));
        savebox = ToonzImageUtils::addInkStroke(ti, stroke, styleId, selective,
                                                filled, TConsts::infiniteRectD,
                                                !m_param.m_pencil.getValue());
      } else {
        int thickness = m_param.m_rasterToolSize.getValue();
        TUndoManager::manager()->add(new CMBluredPrimitiveUndo(
            sl, id, stroke, thickness, hardness, selective, false,
            m_isFrameCreated, m_isLevelCreated, m_primitive->getName()));
        savebox = drawBluredBrush(ti, stroke, thickness, hardness, selective);
      }
      ToolUtils::updateSaveBox();
      delete stroke;
    }
    /*-- VectorImage --*/
    else if (vi) {
      if (TTool::getApplication()->getCurrentObject()->isSpline()) {
        if (!ToolUtils::isJustCreatedSpline(vi.getPointer())) {
          m_primitive->setIsPrompting(true);
          QString question("Are you sure you want to replace the motion path?");
          int ret =
              DVGui::MsgBox(question, QObject::tr("Yes"), QObject::tr("No"), 0);
          m_primitive->setIsPrompting(false);
          if (ret == 2 || ret == 0) return;
        }
        QMutexLocker lock(vi->getMutex());
        TUndo *undo = new UndoPath(
            getXsheet()->getStageObject(getObjectId())->getSpline());
        while (vi->getStrokeCount() > 0) vi->deleteStroke(0);
        vi->addStroke(stroke, false);
        TUndoManager::manager()->add(undo);
      } else {
        int styleId = TTool::getApplication()->getCurrentLevelStyleIndex();
        if (styleId >= 0) stroke->setStyle(styleId);
        QMutexLocker lock(vi->getMutex());
        std::vector<TFilledRegionInf> *fillInformation =
            new std::vector<TFilledRegionInf>;
        ImageUtils::getFillingInformationOverlappingArea(vi, *fillInformation,
                                                         stroke->getBBox());
        vi->addStroke(stroke);
        TUndoManager::manager()->add(new UndoPencil(
            vi->getStroke(vi->getStrokeCount() - 1), fillInformation, sl, id,
            m_isFrameCreated, m_isLevelCreated, m_param.m_autogroup.getValue(),
            m_param.m_autofill.getValue()));
        if ((Preferences::instance()->getGuidedDrawingType() == 1 ||
             Preferences::instance()->getGuidedDrawingType() == 2) &&
            Preferences::instance()->getGuidedAutoInbetween()) {
          TTool *tool =
              TTool::getTool(T_Brush, TTool::ToolTargetType::VectorImage);
          ToonzVectorBrushTool *vbTool = (ToonzVectorBrushTool *)tool;
          if (vbTool) {
            vbTool->setViewer(m_viewer);
            vbTool->doGuidedAutoInbetween(id, vi, stroke, false,
                                          m_param.m_autogroup.getValue(),
                                          m_param.m_autofill.getValue(), false);
          }
        }
      }
      if (m_param.m_autogroup.getValue() && stroke->isSelfLoop()) {
        int index = vi->getStrokeCount() - 1;
        vi->group(index, 1);
        if (m_param.m_autofill.getValue()) {
          // to avoid filling other strokes, I enter into the new stroke group
          int currentGroup = vi->exitGroup();
          vi->enterGroup(index);
          vi->selectFill(stroke->getBBox().enlarge(1, 1), 0, stroke->getStyle(),
                         false, true, false);
          if (currentGroup != -1)
            vi->enterGroup(currentGroup);
          else
            vi->exitGroup();
        }
      }
    }
    /*-- RasterImage --*/
    else if (ri) {
      int styleId = TTool::getApplication()->getCurrentLevelStyleIndex();
      stroke->setStyle(styleId);
      double opacity  = m_param.m_opacity.getValue() * 0.01;
      double hardness = m_param.m_hardness.getValue() * 0.01;
      TRect savebox;
      if (hardness == 1) {
        TUndoManager::manager()->add(new UndoFullColorPencil(
            sl, id, stroke, opacity, true, m_isFrameCreated, m_isLevelCreated));
        savebox = TRasterImageUtils::addStroke(ri, stroke, TRectD(), opacity);
      } else {
        int thickness = m_param.m_rasterToolSize.getValue();
        TUndoManager::manager()->add(new FullColorBluredPrimitiveUndo(
            sl, id, stroke, thickness, hardness, opacity, true,
            m_isFrameCreated, m_isLevelCreated));
        savebox = drawBluredBrush(ri, stroke, thickness, hardness, opacity);
      }
      ToolUtils::updateSaveBox();
      delete stroke;
    }
    notifyImageChanged();
    m_active = false;
  }
changeType()
void GeometricTool::changeType (std::wstring name) inline
{
    std::map<std::wstring, Primitive *>::iterator it =
        m_primitiveTable.find(name);
    if (it != m_primitiveTable.end()) {
      if (m_primitive) m_primitive->onDeactivate();
      m_primitive = it->second;
    }
  }
draw()
void GeometricTool::draw () inline override virtual
Draws the tool on the viewer.
Reimplemented from TTool.
                       {
    if (m_isRotatingOrMoving) {
      tglColor(m_color);
      drawStrokeCenterline(*m_rotatedStroke, sqrt(tglGetPixelSize2()));
      return;
    }
    if (m_primitive) m_primitive->draw();
  }
getColorClass()
int GeometricTool::getColorClass () const inline
{ return 1; }
getCursorId()
int GeometricTool::getCursorId () const inline override virtual
Returns the type of cursor used by the tool.
See also
For a list of cursor ids cursor.h
Reimplemented from TTool.
{
    if (m_viewer && m_viewer->getGuidedStrokePickerMode())
      return m_viewer->getGuidedStrokePickerCursor();
    return ToolCursor::PenCursor;
  }
References TTool::m_viewer.
getProperties()
TPropertyGroup * GeometricTool::getProperties (int idx) inline override virtual
Reimplemented from TTool.
{
    return &m_param.m_prop[idx];
  }
getToolType()
ToolType GeometricTool::getToolType () const inline override virtual
Implements TTool.
{ return TTool::LevelWriteTool; }
keyDown()
bool GeometricTool::keyDown (QKeyEvent * event) inline override virtual
Reimplemented from TTool.
{
    return m_primitive->keyDown(event);
  }
leftButtonDoubleClick()
void GeometricTool::leftButtonDoubleClick (const TPointD & p, const TMouseEvent & e) inline override virtual
Reimplemented from TTool.
{
    if (!m_active) return;
    if (m_primitive) m_primitive->leftButtonDoubleClick(p, e);
    invalidate();
  }
leftButtonDown()
void GeometricTool::leftButtonDown (const TPointD & p, const TMouseEvent & e) inline override virtual
Reimplemented from TTool.
{
    if (getViewer() && getViewer()->getGuidedStrokePickerMode()) {
      getViewer()->doPickGuideStroke(p);
      return;
    }
    if (m_isRotatingOrMoving) {
      addStroke();
      return;
    }
    if (m_primitive) m_primitive->leftButtonDown(p, e);
    invalidate();
  }
leftButtonDrag()
void GeometricTool::leftButtonDrag (const TPointD & p, const TMouseEvent & e) inline override virtual
Reimplemented from TTool.
{
    if (!m_active) return;
    if (m_primitive) m_primitive->leftButtonDrag(p, e);
    invalidate();
  }
leftButtonUp()
void GeometricTool::leftButtonUp (const TPointD & p, const TMouseEvent & e) inline override virtual
Reimplemented from TTool.
{
    if (!m_active) return;
    if (m_primitive) m_primitive->leftButtonUp(p, e);
    invalidate();
  }
mouseMove()
void GeometricTool::mouseMove (const TPointD & p, const TMouseEvent & e) inline override virtual
Reimplemented from TTool.
{
    m_currentCursorPos = p;
    if (m_isRotatingOrMoving) {
      // move
      if (e.isCtrlPressed()) {
        // if ctrl wasn't pressed, it means the user has switched from
        // rotation to move. Thus, re-initiate move-relevant variables
        if (!m_wasCtrlPressed) {
          m_wasCtrlPressed = true;
          m_originalCursorPos = m_currentCursorPos;
          m_lastMoveStrokePos = TPointD(0, 0);
        }
        // move the stroke to the original location
        double x = -m_lastMoveStrokePos.x;
        double y = -m_lastMoveStrokePos.y;
        m_rotatedStroke->transform(TTranslation(x, y));
        // move the stroke according to current mouse position
        double dx           = m_currentCursorPos.x - m_originalCursorPos.x;
        double dy           = m_currentCursorPos.y - m_originalCursorPos.y;
        m_lastMoveStrokePos = TPointD(dx, dy);
        m_rotatedStroke->transform(TTranslation(dx, dy));
        invalidate();
        return;
      }
      // if ctrl was pressed, it means the user has switched from
      // move to rotation. Thus, re-initiate rotation-relevant variables
      if (m_wasCtrlPressed) {
        m_wasCtrlPressed = false;
        m_lastRotateAngle   = 0;
        m_originalCursorPos = m_currentCursorPos;
        TRectD bbox         = m_rotatedStroke->getBBox();
        m_rotateCenter      = 0.5 * (bbox.getP11() + bbox.getP00());
      }
      // rotate
      // first, rotate the stroke back to original
      m_rotatedStroke->transform(TRotation(m_rotateCenter, -m_lastRotateAngle));
      // then, rotate it according to mouse position
      // this formula is from: https://stackoverflow.com/a/31334882
      TPointD center = m_rotateCenter;
      TPointD org    = m_originalCursorPos;
      TPointD cur    = m_currentCursorPos;
      double angle1  = atan2(cur.y - center.y, cur.x - center.x);
      double angle2  = atan2(org.y - center.y, org.x - center.x);
      double angle   = (angle1 - angle2) * 180 / 3.14;
      if (e.isShiftPressed()) {
        angle = ((int)angle / 45) * 45;
      }
      m_rotatedStroke->transform(TRotation(m_rotateCenter, angle));
      m_lastRotateAngle = angle;
      invalidate();
      return;
    }
    if (m_primitive) m_primitive->mouseMove(p, e);
  }
onActivate()
void GeometricTool::onActivate () inline override virtual
Callback invoked whenever the tool activates.
Reimplemented from TTool.
{
    if (m_firstTime) {
      m_param.m_toolSize.setValue(GeometricSize);
      m_param.m_rasterToolSize.setValue(GeometricRasterSize);
      m_param.m_opacity.setValue(GeometricOpacity);
      m_param.m_hardness.setValue(GeometricBrushHardness);
      m_param.m_selective.setValue(GeometricSelective ? 1 : 0);
      m_param.m_rotate.setValue(GeometricRotate ? 1 : 0);
      m_param.m_autogroup.setValue(GeometricGroupIt ? 1 : 0);
      m_param.m_smooth.setValue(GeometricSmooth ? 1 : 0);
      m_param.m_autofill.setValue(GeometricAutofill ? 1 : 0);
      std::wstring typeCode = ::to_wstring(GeometricType.getValue());
      m_param.m_type.setValue(typeCode);
      GeometricType = ::to_string(typeCode);
      m_typeCode    = typeCode;
      changeType(typeCode);
      m_param.m_edgeCount.setValue(GeometricEdgeCount);
      m_param.m_pencil.setValue(GeometricPencil ? 1 : 0);
      m_param.m_capStyle.setIndex(GeometricCapStyle);
      m_param.m_joinStyle.setIndex(GeometricJoinStyle);
      m_param.m_miterJoinLimit.setValue(GeometricMiterValue);
      m_firstTime = false;
      m_param.m_snap.setValue(GeometricSnap);
      if (m_targetType & TTool::Vectors) {
        m_param.m_snapSensitivity.setIndex(GeometricSnapSensitivity);
        switch (GeometricSnapSensitivity) {
        case 0:
          m_param.m_minDistance2 = SNAPPING_LOW;
          break;
        case 1:
          m_param.m_minDistance2 = SNAPPING_MEDIUM;
          break;
        case 2:
          m_param.m_minDistance2 = SNAPPING_HIGH;
          break;
        }
      }
    }
    m_primitive->resetSnap();
    /*--
       onEnter
            LineTool --*/
    m_active = (getImage(false) != 0 ||
                Preferences::instance()->isAutoCreateEnabled());
    if (m_primitive) m_primitive->onActivate();
  }
References TTool::getImage(), and TTool::m_targetType.
onDeactivate()
void GeometricTool::onDeactivate () inline override virtual
Callback for tool deactivation, includes tool switch.
Reimplemented from TTool.
{
    if (m_primitive) m_primitive->onDeactivate();
    m_isRotatingOrMoving = false;
    delete m_rotatedStroke;
    m_rotatedStroke = 0;
  }
onEnter()
void GeometricTool::onEnter () inline override virtual
Callback for the mouse entering the viewer area.
Reimplemented from TTool.
{
    m_active = getImage(false) != 0;
    if (m_active && m_primitive) m_primitive->onEnter();
  }
References TTool::getImage().
onImageChanged()
void GeometricTool::onImageChanged () inline override virtual
Notifies changes in the image in use.
Reimplemented from TTool.
{
    if (m_primitive) m_primitive->onImageChanged();
    m_isRotatingOrMoving = false;
    delete m_rotatedStroke;
    m_rotatedStroke = 0;
    invalidate();
  }
References TTool::invalidate().
onPropertyChanged()
bool GeometricTool::onPropertyChanged (std::string propertyName) inline override virtual
 Does the tasks associated to changes in \p propertyName and returns \p
true; Does the tasks associated to changes in propertyName and returns true.
Reimplemented from TTool.
{
    /*---   Property
            m_toolSizem_rasterToolSizeName(="Size:")
             ---*/
    if (propertyName == m_param.m_toolSize.getName()) {
      TImageP img = getImage(false);
      TToonzImageP ri(img); /*--  --*/
      if (ri)
        GeometricRasterSize = m_param.m_rasterToolSize.getValue();
      else
        GeometricSize = m_param.m_toolSize.getValue();
    } else if (propertyName == m_param.m_type.getName()) {
      std::wstring typeCode = m_param.m_type.getValue();
      GeometricType         = ::to_string(typeCode);
      if (typeCode != m_typeCode) {
        m_typeCode = typeCode;
        changeType(typeCode);
      }
    } else if (propertyName == m_param.m_edgeCount.getName())
      GeometricEdgeCount = m_param.m_edgeCount.getValue();
    else if (propertyName == m_param.m_rotate.getName())
      GeometricRotate = m_param.m_rotate.getValue();
    else if (propertyName == m_param.m_autogroup.getName()) {
      if (!m_param.m_autogroup.getValue()) {
        m_param.m_autofill.setValue(false);
        // this is ugly: it's needed to refresh the GUI of the toolbar after
        // having set to false the autofill...
        TTool::getApplication()->getCurrentTool()->setTool(
            "");  // necessary, otherwise next setTool is ignored...
        TTool::getApplication()->getCurrentTool()->setTool(
            QString::fromStdString(getName()));
      }
      GeometricGroupIt = m_param.m_autogroup.getValue();
    } else if (propertyName == m_param.m_autofill.getName()) {
      if (m_param.m_autofill.getValue()) {
        m_param.m_autogroup.setValue(true);
        // this is ugly: it's needed to refresh the GUI of the toolbar after
        // having set to false the autofill...
        TTool::getApplication()->getCurrentTool()->setTool(
            "");  // necessary, otherwise next setTool is ignored...
        TTool::getApplication()->getCurrentTool()->setTool(
            QString::fromStdString(getName()));
      }
      GeometricGroupIt = m_param.m_autofill.getValue();
    } else if (propertyName == m_param.m_smooth.getName()) {
      GeometricSmooth = m_param.m_smooth.getValue();
    } else if (propertyName == m_param.m_selective.getName())
      GeometricSelective = m_param.m_selective.getValue();
    else if (propertyName == m_param.m_pencil.getName())
      GeometricPencil = m_param.m_pencil.getValue();
    else if (propertyName == m_param.m_hardness.getName())
      GeometricBrushHardness = m_param.m_hardness.getValue();
    else if (propertyName == m_param.m_opacity.getName())
      GeometricOpacity = m_param.m_opacity.getValue();
    else if (propertyName == m_param.m_capStyle.getName())
      GeometricCapStyle = m_param.m_capStyle.getIndex();
    else if (propertyName == m_param.m_joinStyle.getName())
      GeometricJoinStyle = m_param.m_joinStyle.getIndex();
    else if (propertyName == m_param.m_miterJoinLimit.getName())
      GeometricMiterValue = m_param.m_miterJoinLimit.getValue();
    else if (propertyName == m_param.m_snap.getName())
      GeometricSnap = m_param.m_snap.getValue();
    else if (propertyName == m_param.m_snapSensitivity.getName()) {
      GeometricSnapSensitivity = m_param.m_snapSensitivity.getIndex();
      switch (GeometricSnapSensitivity) {
      case 0:
        m_param.m_minDistance2 = SNAPPING_LOW;
        break;
      case 1:
        m_param.m_minDistance2 = SNAPPING_MEDIUM;
        break;
      case 2:
        m_param.m_minDistance2 = SNAPPING_HIGH;
        break;
      }
    }
    return false;
  }
References TTool::getImage().
preLeftButtonDown()
bool GeometricTool::preLeftButtonDown () inline override virtual
This method is called before leftButtonDown() and can be used e.g. to create the image if needed. return true if the method execution can have changed the current tool
Reimplemented from TTool.
{
    if (getViewer() && getViewer()->getGuidedStrokePickerMode()) return false;
    if (getApplication()->getCurrentObject()->isSpline()) return true;
    // in the halfway through the drawing of Polyline / MultiArc primitive, OT
    // should not call touchImage or the m_frameCreated / m_levelCreated flags
    // will be reset.
    if (m_primitive && !m_primitive->canTouchImageOnPreLeftClick()) return true;
    // NEEDS to be done even if(m_active), due
    // to the HORRIBLE m_frameCreated / m_levelCreated
    // mechanism. touchImage() is the ONLY function
    // resetting them to false...                       >_<
    m_active = !!touchImage();
    return true;
  }
References TTool::touchImage().
rightButtonDown()
void GeometricTool::rightButtonDown (const TPointD & p, const TMouseEvent & e) inline override virtual
Reimplemented from TTool.
{
    if (m_primitive) m_primitive->rightButtonDown(p, e);
    invalidate();
  }
updateTranslation()
void GeometricTool::updateTranslation () inline override virtual
Reimplemented from TTool.
{ m_param.updateTranslation(); }
Member Data Documentation
m_active
bool GeometricTool::m_active protected
m_color
TPixel32 GeometricTool::m_color protected
m_currentCursorPos
TPointD GeometricTool::m_currentCursorPos protected
m_firstTime
bool GeometricTool::m_firstTime protected
m_isRotatingOrMoving
bool GeometricTool::m_isRotatingOrMoving protected
m_lastMoveStrokePos
TPointD GeometricTool::m_lastMoveStrokePos protected
m_lastRotateAngle
double GeometricTool::m_lastRotateAngle protected
m_originalCursorPos
TPointD GeometricTool::m_originalCursorPos protected
m_param
PrimitiveParam GeometricTool::m_param protected
m_primitive
Primitive* GeometricTool::m_primitive protected
m_primitiveTable
std::map<std::wstring, Primitive *> GeometricTool::m_primitiveTable protected
m_rotateCenter
TPointD GeometricTool::m_rotateCenter protected
m_rotatedStroke
TStroke* GeometricTool::m_rotatedStroke protected
m_typeCode
std::wstring GeometricTool::m_typeCode protected
m_wasCtrlPressed
bool GeometricTool::m_wasCtrlPressed protected
The documentation for this class was generated from the following file:
E:/opentoonz/toonz/sources/tnztools/geometrictool.cpp