opentoonz: TCubic Class Reference
TCubic Class Reference
#include <tcurves.h>
Public Member Functions
TCubic (const TPointD &p0, const TPointD &p1, const TPointD &p2, const TPointD &p3)
p0,p1,p2,p3 are the four control points
TCubic (const TCubic &src)
TCubic & operator= (const TCubic &src)
TPointD getP0 () const
Return first control point P0.
TPointD getP1 () const
Return second control point P1.
TPointD getP2 () const
Return third control point P2.
TPointD getP3 () const
Return fourth control point P3.
void setP0 (const TPointD &p0)
Set the value of first control point P0 to p.
void setP1 (const TPointD &p1)
Set the value of second control point P1 to p.
void setP2 (const TPointD &p2)
Set the value of third control point P2 to p.
void setP3 (const TPointD &p3)
Set the value of fourth control point P3 to p.
bool operator== (const TCubic &c) const
bool operator!= (const TCubic &c) const
TRectD getBBox () const
Return rect that contains the cubic.
TPointD getPoint (double t) const
Return the point of cubic at parameter t.
TPointD getSpeed (double t) const
Return speed of cubic at parameter t.
TPointD getAcceleration (double t) const
Return acceleration of cubic at parameter t.
double getLength (double t0, double t1) const
double getLength (double t1=1.0) const
void split (double t, TCubic &first, TCubic &second) const
Protected Attributes
TPointD m_p0
TPointD m_p1
TPointD m_p2
TPointD m_p3
Detailed Description
TCubic class to manage a cubic
Constructor & Destructor Documentation
TCubic() [1/3]
TCubic::TCubic () inline
: m_p0(), m_p1(), m_p2(), m_p3() {}
TCubic() [2/3]
TCubic::TCubic (const TPointD & p0, const TPointD & p1, const TPointD & p2, const TPointD & p3) inline
p0,p1,p2,p3 are the four control points
      : m_p0(p0), m_p1(p1), m_p2(p2), m_p3(p3) {}
TCubic() [3/3]
TCubic::TCubic (const TCubic & src) inline
      : m_p0(src.m_p0), m_p1(src.m_p1), m_p2(src.m_p2), m_p3(src.m_p3) {}
Member Function Documentation
getAcceleration()
TPointD TCubic::getAcceleration (double t) const inline
Return acceleration of cubic at parameter t.
{
    return 6.0 *
           ((m_p2 - 2 * m_p1 + m_p0) * (1 - t) + (m_p3 - 2 * m_p2 + m_p1) * t);
  };
getBBox()
TRectD TCubic::getBBox () const inline
Return rect that contains the cubic.
{
    return TRectD(std::min({m_p0.x, m_p1.x, m_p2.x, m_p3.x}),
                  std::min({m_p0.y, m_p1.y, m_p2.y, m_p3.y}),
                  std::max({m_p0.x, m_p1.x, m_p2.x, m_p3.x}),
                  std::max({m_p0.y, m_p1.y, m_p2.y, m_p3.y}));
  };
getLength() [1/2]
double TCubic::getLength (double t0, double t1) const
Return length of an arc between parameters t0 t1. N.B. Length returned is always positive.
Note
t0 and t1 are clamped to [0,1] interval
if t0>=t1 returns 0
{ return -1; }
getLength() [2/2]
double TCubic::getLength (double t1 = 1.0) const inline
{ return getLength(0.0, t1); }
getP0()
TPointD TCubic::getP0 () const inline
Return first control point P0.
{ return m_p0; }
Referenced by TAffine::operator*().
getP1()
TPointD TCubic::getP1 () const inline
Return second control point P1.
{ return m_p1; }
Referenced by TAffine::operator*().
getP2()
TPointD TCubic::getP2 () const inline
Return third control point P2.
{ return m_p2; }
Referenced by TAffine::operator*().
getP3()
TPointD TCubic::getP3 () const inline
Return fourth control point P3.
{ return m_p3; }
Referenced by TAffine::operator*().
getPoint()
TPointD TCubic::getPoint (double t) const
Return the point of cubic at parameter t.
{
  double s = 1 - t;
  return m_p0 * s * s * s + 3 * t * s * (s * m_p1 + t * m_p2) +
         t * t * t * m_p3;
}
getSpeed()
TPointD TCubic::getSpeed (double t) const
Return speed of cubic at parameter t.
{
  double s = 1 - t;
  return 3.0 * ((m_p1 - m_p0) * s * s + 2 * (m_p2 - m_p0) * s * t +
                (m_p3 - m_p2) * t * t);
}
operator!=()
bool TCubic::operator!= (const TCubic & c) const inline
{ return !operator==(c); }
operator=()
TCubic & TCubic::operator= (const TCubic & src) inline
{
    m_p0 = src.m_p0;
    m_p1 = src.m_p1;
    m_p2 = src.m_p2;
    m_p3 = src.m_p3;
    return *this;
  }
operator==()
bool TCubic::operator== (const TCubic & c) const inline
{
    return m_p0 == c.m_p0 && m_p1 == c.m_p1 && m_p2 == c.m_p2 && m_p3 == c.m_p3;
  }
setP0()
void TCubic::setP0 (const TPointD & p0) inline
Set the value of first control point P0 to p.
{ m_p0 = p0; }
Referenced by TAffine::operator*().
setP1()
void TCubic::setP1 (const TPointD & p1) inline
Set the value of second control point P1 to p.
{ m_p1 = p1; }
Referenced by TAffine::operator*().
setP2()
void TCubic::setP2 (const TPointD & p2) inline
Set the value of third control point P2 to p.
{ m_p2 = p2; }
Referenced by TAffine::operator*().
setP3()
void TCubic::setP3 (const TPointD & p3) inline
Set the value of fourth control point P3 to p.
{ m_p3 = p3; }
Referenced by TAffine::operator*().
split()
void TCubic::split (double t, TCubic & first, TCubic & second) const
N.B. if t==0 o t==1 return a quadratic with all points equal
{
  double s = 1.0 - t;
  TPointD H = s * m_p1 + t * m_p2;
  first.m_p0 = m_p0;
  first.m_p1 = s * m_p0 + t * m_p1;
  first.m_p2 = s * first.m_p1 + t * H;
  second.m_p3 = m_p3;
  second.m_p2 = s * m_p2 + t * m_p3;
  second.m_p1 = s * H + t * second.m_p2;
  first.m_p3  = s * first.m_p2 + t * second.m_p1;
  second.m_p0 = first.m_p3;
}
Member Data Documentation
m_p0
TPointD TCubic::m_p0 protected
m_p1
TPointD TCubic::m_p1 protected
m_p2
TPointD TCubic::m_p2 protected
m_p3
TPointD TCubic::m_p3 protected
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/tcurves.h
E:/opentoonz/toonz/sources/common/tgeometry/tcurves.cpp