opentoonz: TTool Class Reference
TTool Class Reference abstract
TTool is the abstract base class defining the interface for Toonz tools - the ones accessible from the Toolbar panel that users can activate to edit the scene contents interactively.
#include <tool.h>
Classes
struct CellOps
class Viewer
The TTool::Viewer class is the abstract base class that provides an interface for TTool viewer widgets (it is required that such widgets support OpenGL).
Public Types
enum ToolType {
GenericTool = 1 , ColumnTool = 2 , LevelReadTool = 4 , LevelWriteTool ,
LevelTool = LevelReadTool | LevelWriteTool
}
Tool editing type.
enum ToolTargetType {
NoTarget = 0x0 , VectorImage = 0x1 , ToonzImage = 0x2 , RasterImage = 0x4 ,
MeshImage = 0x8 , Splines = 0x10 , LevelColumns = 0x20 , MeshColumns = 0x40 ,
EmptyTarget = 0x80 , CommonImages = VectorImage | ToonzImage | RasterImage , AllImages = CommonImages | MeshImage , Vectors = VectorImage | Splines ,
CommonLevels = CommonImages | LevelColumns , MeshLevels = MeshImage | MeshColumns , AllTargets = 0xffffffff
}
Object types the tool can operate on.
typedef TApplication Application
Public Member Functions
TTool (std::string toolName)
every tool (invoking updateTranslation() for each).
virtual ToolType getToolType () const =0
ToolTargetType getTargetType () const
std::string getName () const
virtual ToolOptionsBox * createOptionsBox ()
void setViewer (Viewer *viewer)
Viewer * getViewer () const
double getPixelSize () const
void invalidate (const TRectD &rect=TRectD())
int pick (const TPointD &p)
bool isPicking () const
virtual void updateTranslation ()
virtual bool preLeftButtonDown ()
virtual void mouseMove (const TPointD &, const TMouseEvent &)
virtual void leftButtonDown (const TPointD &, const TMouseEvent &)
virtual void leftButtonDrag (const TPointD &, const TMouseEvent &)
virtual void leftButtonUp (const TPointD &, const TMouseEvent &)
virtual void leftButtonDoubleClick (const TPointD &, const TMouseEvent &)
virtual void rightButtonDown (const TPointD &, const TMouseEvent &)
virtual bool keyDown (QKeyEvent *)
virtual void onInputText (std::wstring, std::wstring, int, int)
virtual void onSetViewer ()
virtual void onActivate ()
Callback invoked whenever the tool activates.
virtual void onDeactivate ()
Callback for tool deactivation, includes tool switch.
virtual void onImageChanged ()
Notifies changes in the image in use.
virtual void onEnter ()
Callback for the mouse entering the viewer area.
virtual void onLeave ()
Callback for the mouse leaving the viewer area.
virtual void onFrameSwitched ()
virtual void reset ()
virtual void draw ()
Draws the tool on the viewer.
bool isActive () const
Used to know if a tool is active, (used in TextTool only).
void setActive (bool active)
virtual TPropertyGroup * getProperties (int)
virtual bool onPropertyChanged (std::string propertyName)
virtual TSelection * getSelection ()
Returns a pointer to the tool selection.
virtual int getCursorId () const
Returns the type of cursor used by the tool.
virtual bool isEventAcceptable (QEvent *e)
TXsheet * getXsheet () const
Returns a pointer to the actual Xsheet.
int getFrame ()
Returns the actual frame in use.
int getColumnIndex ()
Returns the actual column index.
TStageObjectId getObjectId () const
Returns a pointer to the actual stage object.
void notifyImageChanged ()
void notifyImageChanged (const TFrameId &fid)
images on the level view.
TFrameId getCurrentFid () const
Returns the number of the actual editing frame.
const TAffine & getMatrix () const
void setMatrix (const TAffine &matrix)
TAffine getCurrentColumnMatrix (int frame=-1) const
TAffine getCurrentColumnParentMatrix () const
TAffine getCurrentObjectParentMatrix () const
TAffine getCurrentObjectParentMatrix2 () const
TAffine getColumnMatrix (int index, int frame=-1) const
virtual void updateMatrix ()
virtual void addContextMenuItems (QMenu *menu)
void enable (bool on)
bool isEnabled () const
QString updateEnabled ()
virtual QString updateEnabled (int rowIndex, int columnIndex)
bool isColumnLocked (int columnIndex) const
void resetInputMethod ()
Resets Input Context (IME)
virtual bool isPencilModeActive ()
virtual bool isDragging () const
void setSelectedFrames (const std::set< TFrameId > &selectedFrames)
void tweenSelectedGuideStrokes ()
void tweenGuideStrokeToSelected ()
void flipGuideStrokeDirection (int mode)
Static Public Member Functions
static TTool * getTool (std::string toolName, ToolTargetType targetType)
static TApplication * getApplication ()
static void setApplication (TApplication *application)
static TXshCell getImageCell ()
Returns the level-frame pair to be edited by the tool.
static TImage * getImage (bool toBeModified, int subsampling=0)
Returns the image to be edited by the tool.
static TImage * touchImage ()
static void updateToolsPropertiesTranslation ()
static const std::set< TFrameId > & getSelectedFrames ()
Static Public Attributes
static std::vector< CellOps > m_cellsData
static bool m_isLevelCreated = false
static bool m_isFrameCreated = false
static std::vector< TFrameId > m_oldFids
static std::vector< TFrameId > m_newFids
static bool m_isLevelRenumbererd = false
Protected Member Functions
void bind (int targetType)
virtual void onSelectedFramesChanged ()
virtual QString disableString ()
Returns a custom reason to disable the tool.
Protected Attributes
std::string m_name
The tool's name.
Viewer * m_viewer
Tool's current viewer.
TAffine m_matrix
World-to-window reference change affine.
int m_targetType
The tool's image type target.
bool m_enabled
Whether the tool allows user interaction.
bool m_active
bool m_picking
Static Protected Attributes
static TApplication * m_application = 0
static std::set< TFrameId > m_selectedFrames = std::set<TFrameId>()
Detailed Description
TTool is the abstract base class defining the interface for Toonz tools - the ones accessible from the Toolbar panel that users can activate to edit the scene contents interactively.
Toonz implements a number of interactive tools, like the Brush Tool, Fill Tool, Zoom Tool and others. They all inherit from this class, which provides the necessary interface and framework to implement a generic interactive tool in Toonz.
        A Toonz Tool should re-implement the following key functionalities:
The abstract getToolType() method, which classifies the tool, and eventually getTargetType()
The draw() method, used to draw the tool on screen
The mouse-related methods, to grant user interaction
The getProperties() and onPropertyChanged() methods, to define and track a tool's TProperty members
The addContextMenuItems() method, to insert actions in right-click menus
Tool classification
Toonz enforces a strict classification of its tools that is used to enable or disable them in the appropriate contexts:
Generic Tools: the tool is always enabled, since it does not need to access specific scene contents. Hidden tools typically prefer to select this type since they should handle disablements silently.
Column Tools: the tool is used to alter or define the placement of a column's content. It is disabled in Filmstrip view mode, since that's a strictly level-related view.
LevelRead Tools: the tool is used to read a level's images data. It is therefore enabled on all view modes. The tool is disabled in camera stand or 3D view modes if the level's host column has sustained a placement which makes it impossible to access image data (as is the case with Plastic-deformed columns).
LevelWrite Tools: the tool is used to write a level's images data. It is disabled in all contexts where a LevelRead Tool would be disabled. It is also disabled in case the current level is of a type unsupported for write, or the level is read-only on disk.
Furthermore, tools define a bitwise combination of Target Types, which are the category of level types it can work on (including every image type and the motion path type). The Target Type is used only associated with LevelRead and LevelWrite tool types.
There are a number of additional generic rules that define whenever a tool is disabled:
Every tool is disabled when a viewer is in playback.
Every non-Generic tool is disabled on level/columns that do not host a placeable image type (eg sound or magpie data).
Every non-Generic tool is disabled when working on columns/levels that have been hidden.
Every non-Generic tool is disabled when working on columns that have been locked (the lock icon on a column header).
Drawing
Tools use OpenGL to draw in their currently associated Viewer instance, which can be retrieved through the getViewer() accessor function. The viewer is assigned to the tool just before it invokes the tool's draw() function - use the onSetViewer() virtual method to access viewer data before the viewer starts drawing (observe the tool is typically drawn as an overlay, on top of other stuff).
Just before draw() is invoked by the viewer, the GL_MODELVIEW matrix is automatically pushed by the viewer with the tool-to-window affine returned by getMatrix() (multiplied by the viewer's view affine). Use glGetDoublev() to retrieve the effective tool-to-window reference change affine, and in case reimplement updateMatrix() to specify the affine returned by getMatrix().
The default implementation for updateMatrix() sets the tool reference to current object's world one.
Tool Properties
A tool's properties must be implemented by defining one or more TPropertyGroup containers, and adding them the TProperty specializations corresponding to the required parameters.
Every TProperty instance in group 0 is automatically added to the Tool Options panel in Toonz's GUI. Further groups or special toolbar options must be currently hard-coded elsewhere. Tool Options panel construction will probably be redirected to the tool in future Toonz versions.
Context Menu Items
The addContextMenuItems() is used to insert context menu actions before the standard actions provided by the tool viewer. Remember to insert separators to isolate commands of different type (such as view, editing, etc).
Member Typedef Documentation
Application
typedef TApplication TTool::Application
Member Enumeration Documentation
ToolTargetType
enum TTool::ToolTargetType
Object types the tool can operate on.
Enumerator
VectorImage
Will work on vector images.
ToonzImage
Will work on colormap (tlv) images.
RasterImage
Will work on fullcolor images.
MeshImage
Will work on mesh images.
Splines
Will work on motion paths.
LevelColumns
Will work on level columns.
MeshColumns
Will work on mesh columns.
EmptyTarget
Will work on empty cells/columns.
  { NoTarget    = 0x0,
    VectorImage = 0x1,
    ToonzImage  = 0x2,
    RasterImage = 0x4,
    MeshImage   = 0x8,
    Splines     = 0x10,
    LevelColumns = 0x20,
    MeshColumns  = 0x40,
    EmptyTarget = 0x80,
    CommonImages = VectorImage | ToonzImage | RasterImage,
    AllImages    = CommonImages | MeshImage,
    Vectors      = VectorImage | Splines,
    CommonLevels = CommonImages | LevelColumns,
    MeshLevels   = MeshImage | MeshColumns,
    AllTargets = 0xffffffff,
  };
ToolType
enum TTool::ToolType
Tool editing type.
Enumerator
GenericTool
Tool will not deal with specific scene content.
ColumnTool
Tool deals with placement of column objects.
LevelReadTool
Tool reads a level's image data.
LevelWriteTool
Tool writes a level's image data (implies LevelReadTool).
  { GenericTool   = 1,
    ColumnTool    = 2,
    LevelReadTool = 4,
    LevelWriteTool =
        8,
    // Convenience testing flags - getToolType() should not return these
    LevelTool = LevelReadTool | LevelWriteTool };
Constructor & Destructor Documentation
TTool()
TTool::TTool (std::string toolName)
every tool (invoking updateTranslation() for each).
    : m_name(name)
    , m_viewer(0)
    , m_targetType(NoTarget)
    , m_enabled(true)
    , m_active(false)
    , m_picking(false) {}
~TTool()
virtual TTool::~TTool () inline virtual
{}
Member Function Documentation
addContextMenuItems()
virtual void TTool::addContextMenuItems (QMenu * menu) inline virtual
Add a context menu to the actual tool, as for example pressing right mouse button with the stroke selection tool.
Reimplemented in ControlPointEditorTool, PlasticTool, SkeletonTool, and VectorSelectionTool.
{}
bind()
void TTool::bind (int targetType) protected
{
  m_targetType = targetType;
  if (!toolTable) toolTable = new ToolTable();
  if (!toolNames) toolNames = new std::set<std::string>();
  std::string name = getName();
  if (toolNames->count(name) == 0) {
    toolNames->insert(name);
    // Initialize with the dummy tool
    toolTable->insert(
        std::make_pair(std::make_pair(name, ToonzImage), &theDummyTool));
    toolTable->insert(
        std::make_pair(std::make_pair(name, VectorImage), &theDummyTool));
    toolTable->insert(
        std::make_pair(std::make_pair(name, RasterImage), &theDummyTool));
    toolTable->insert(
        std::make_pair(std::make_pair(name, MeshImage), &theDummyTool));
    ToolSelector *toolSelector = new ToolSelector(name);
    CommandManager::instance()->setHandler(
        name.c_str(), new CommandHandlerHelper<ToolSelector>(
                          toolSelector, &ToolSelector::selectTool));
  }
  if (targetType & ToonzImage)
    (*toolTable)[std::make_pair(name, ToonzImage)] = this;
  if (targetType & VectorImage)
    (*toolTable)[std::make_pair(name, VectorImage)] = this;
  if (targetType & RasterImage)
    (*toolTable)[std::make_pair(name, RasterImage)] = this;
  if (targetType & MeshImage)
    (*toolTable)[std::make_pair(name, MeshImage)] = this;
}
createOptionsBox()
ToolOptionsBox * TTool::createOptionsBox () virtual
The default returns a generic box containing the options for property group 0).
See also
See tooloptions.h for more details. Factory function returning a newly created GUI options box to be displayed for the tool
Reimplemented in FullColorBrushTool, PlasticTool, ToonzRasterBrushTool, and ToonzVectorBrushTool.
{
  TPaletteHandle *currPalette =
      m_application->getPaletteController()->getCurrentLevelPalette();
  ToolHandle *currTool = m_application->getCurrentTool();
  return new GenericToolOptionsBox(0, this, currPalette, 0, currTool);
}
disableString()
virtual QString TTool::disableString () inline protected virtual
Returns a custom reason to disable the tool.
draw()
virtual void TTool::draw () inline virtual
Draws the tool on the viewer.
Reimplemented in PinchTool, ControlPointEditorTool, EditTool, FillTool, FingerTool, FullColorBrushTool, FullColorEraserTool, GeometricTool, HookTool, MagnetTool, PaintBrushTool, PlasticTool, PumpTool, RasterSelectionTool, RasterTapeTool, RGBPickerTool, RulerTool, ShiftTraceTool, SkeletonTool, StylePickerTool, ToonzRasterBrushTool, ToonzVectorBrushTool, TrackerTool, TypeTool, EraserTool, VectorSelectionTool, VectorTapeTool, RotateTool, CameraTestTool, SetScanCropboxTool, and SelectionTool.
Referenced by SceneViewer::drawOverlay().
enable()
void TTool::enable (bool on) inline
{ m_enabled = on; }
flipGuideStrokeDirection()
void TTool::flipGuideStrokeDirection (int mode)
{
  if (!mode) return;
  TXshSimpleLevel *sl =
      m_application->getCurrentLevel()->getLevel()->getSimpleLevel();
  if (!sl) return;
  int osBack  = -1;
  int osFront = -1;
  int os      = -1;
  int strokeIdx;
  getViewer()->getGuidedFrameIdx(&osBack, &osFront);
  if (mode < 0) {  // Previous Frame
    os        = osBack;
    strokeIdx = getViewer()->getGuidedBackStroke();
  } else if (mode > 0) {  // Next Frame
    os        = osFront;
    strokeIdx = getViewer()->getGuidedFrontStroke();
  }
  if (os < 0) return;
  TFrameHandle *currentFrame = getApplication()->getCurrentFrame();
  int row                    = currentFrame->getFrameIndex();
  TFrameId cFid              = getCurrentFid();
  if (cFid.isEmptyFrame()) return;
  TVectorImageP cvi = sl->getFrame(cFid, false);
  if (!cvi) return;
  int cStrokeCount = cvi->getStrokeCount();
  TFrameId fid;
  if (currentFrame->isEditingScene()) {
    TXsheet *xsh = getApplication()->getCurrentXsheet()->getXsheet();
    int col      = getApplication()->getCurrentColumn()->getColumnIndex();
    if (xsh && col >= 0) {
      TXshCell cell = xsh->getCell(os, col);
      if (!cell.isEmpty()) fid = cell.getFrameId();
    }
  } else
    fid = sl->getFrameId(os);
  if (fid.isEmptyFrame()) return;
  TVectorImageP vi = sl->getFrame(fid, false);
  if (!vi) return;
  int strokeCount = vi->getStrokeCount();
  if (!strokeCount) return;
  if (strokeIdx == -1) strokeIdx = cStrokeCount;
  if (strokeIdx >= strokeCount) return;
  TStroke *stroke = vi->getStroke(strokeIdx);
  if (!stroke) return;
  stroke->changeDirection();
  sl->setDirtyFlag(true);
  getViewer()->invalidateAll();
  m_application->getCurrentLevel()->notifyLevelChange();
}
getApplication()
TTool::Application * TTool::getApplication () static
{
  if (m_application == 0)
    assert(!"you MUST call the TTool::setApplication function in the main of the program!");
  return m_application;
}
getColumnIndex()
int TTool::getColumnIndex ()
Returns the actual column index.
{
  if (!m_application) return 0;
  return m_application->getCurrentColumn()->getColumnIndex();
}
Referenced by SkeletonTool::addContextMenuItems(), and EditTool::onActivate().
getColumnMatrix()
TAffine TTool::getColumnMatrix (int index, int frame = -1) const
    Returns the matrix transformation of the stage object with column
index equal to index and frame as the current frame. if frame = -1 then it uses the current frame
See also
TXsheet::getPlacement.
{
  if (!m_application) return TAffine();
  TFrameHandle *fh = m_application->getCurrentFrame();
  if (fh->isEditingLevel()) return TAffine();
  if (frame < 0) frame = fh->getFrame();
  TXsheet *xsh = m_application->getCurrentXsheet()->getXsheet();
  TStageObjectId columnObjId =
      (columnIndex >= 0)
          ? TStageObjectId::ColumnId(columnIndex)
          : TStageObjectId::CameraId(xsh->getCameraColumnIndex());
  TAffine columnPlacement = xsh->getPlacement(columnObjId, frame);
  double columnZ          = xsh->getZ(columnObjId, frame);
  TStageObjectId cameraId = xsh->getStageObjectTree()->getCurrentCameraId();
  TStageObject *camera    = xsh->getStageObject(cameraId);
  TAffine cameraPlacement = camera->getPlacement(frame);
  double cameraZ          = camera->getZ(frame);
  TStageObject *object = xsh->getStageObject(columnObjId);
  TAffine placement;
  TStageObject::perspective(placement, cameraPlacement, cameraZ,
                            columnPlacement, columnZ,
                            object->getGlobalNoScaleZ());
  return placement;
}
References TStageObjectTree::getCurrentCameraId(), TStageObject::getGlobalNoScaleZ(), TXsheet::getPlacement(), TXsheet::getStageObject(), TXsheet::getStageObjectTree(), TXsheet::getZ(), TStageObject::getZ(), and TStageObject::perspective().
Referenced by getCurrentColumnMatrix().
getCurrentColumnMatrix()
TAffine TTool::getCurrentColumnMatrix (int frame = -1) const
Returns the current column matrix transformation. if frame = -1 then it uses the current frame
See also
TXsheet::getPlacement.
{
  return getColumnMatrix(m_application->getCurrentColumn()->getColumnIndex(),
                         frame);
}
References getColumnMatrix().
Referenced by invalidate(), and updateMatrix().
getCurrentColumnParentMatrix()
TAffine TTool::getCurrentColumnParentMatrix () const
Returns the current matrix transformation of the current stage object parent.
{
  if (!m_application) return TAffine();
  TFrameHandle *fh = m_application->getCurrentFrame();
  if (fh->isEditingLevel()) return TAffine();
  int frame       = fh->getFrame();
  int columnIndex = m_application->getCurrentColumn()->getColumnIndex();
  TXsheet *xsh    = m_application->getCurrentXsheet()->getXsheet();
  TStageObjectId parentId =
      xsh->getStageObjectParent(TStageObjectId::ColumnId(columnIndex));
  return xsh->getPlacement(parentId, frame);
}
References TXsheet::getPlacement(), and TXsheet::getStageObjectParent().
getCurrentFid()
TFrameId TTool::getCurrentFid () const
Returns the number of the actual editing frame.
frame fid; used to update images on the level view.
It can depend on the actual frame and the actual cell or on the current fid (editing level). In editing scene if the current cell is empty the method returns TFrameId::NO_FRAME.
{
  if (!m_application) return TFrameId();
  TFrameHandle *fh = m_application->getCurrentFrame();
  if (fh->isEditingLevel()) return fh->getFid();
  int row = m_application->getCurrentFrame()->getFrame();
  int col = m_application->getCurrentColumn()->getColumnIndex();
  TXshCell cell =
      m_application->getCurrentXsheet()->getXsheet()->getCell(row, col);
  if (cell.isEmpty()) return TFrameId::NO_FRAME;
  return cell.getFrameId();
}
References TXsheet::getCell(), TXshCell::getFrameId(), and TXshCell::isEmpty().
Referenced by HookTool::draw(), TrackerTool::draw(), FingerTool::finishBrush(), PaintBrushTool::finishBrush(), ToonzRasterBrushTool::finishRasterBrush(), invalidate(), FullColorEraserTool::onImageChanged(), EraserTool::onImageChanged(), SceneViewer::onLevelSwitched(), FillTool::onPropertyChanged(), TrackerTool::onPropertyChanged(), RasterSelection::pasteSelection(), and DragSelectionTool::VectorDeformTool::transformWholeLevel().
getCurrentObjectParentMatrix()
TAffine TTool::getCurrentObjectParentMatrix () const
{
  if (!m_application) return TAffine();
  TXsheet *xsh = m_application->getCurrentXsheet()->getXsheet();
  int frame    = m_application->getCurrentFrame()->getFrame();
  TStageObjectId currentObjectId =
      m_application->getCurrentObject()->getObjectId();
  if (currentObjectId == TStageObjectId::NoneId) return TAffine();
  TStageObjectId parentId = xsh->getStageObjectParent(currentObjectId);
  if (parentId == TStageObjectId::NoneId)
    return TAffine();
  else
    return xsh->getPlacement(parentId, frame);
}
getCurrentObjectParentMatrix2()
TAffine TTool::getCurrentObjectParentMatrix2 () const
{
  TTool::Application *app = m_application;
  TFrameHandle *fh        = app->getCurrentFrame();
  if (fh->isEditingLevel()) return TAffine();
  int frame               = fh->getFrame();
  TXsheet *xsh            = app->getCurrentXsheet()->getXsheet();
  TStageObjectId id       = app->getCurrentObject()->getObjectId();
  double objZ             = xsh->getZ(id, frame);
  TStageObjectId parentId = xsh->getStageObjectParent(id);
  if (parentId == TStageObjectId::NoneId) return TAffine();
  id                   = parentId;
  TAffine objPlacement = xsh->getPlacement(id, frame);
  TStageObjectId cameraId = xsh->getStageObjectTree()->getCurrentCameraId();
  TStageObject *camera    = xsh->getStageObject(cameraId);
  TAffine cameraPlacement = camera->getPlacement(frame);
  double cameraZ          = camera->getZ(frame);
  TAffine placement;
  TStageObject::perspective(placement, cameraPlacement, cameraZ, objPlacement,
                            objZ, 0);
  return placement;
}
getCursorId()
virtual int TTool::getCursorId () const inline virtual
Returns the type of cursor used by the tool.
See also
For a list of cursor ids cursor.h
Reimplemented in PinchTool, ControlPointEditorTool, EditTool, FillTool, FingerTool, FullColorBrushTool, FullColorEraserTool, FullColorFillTool, GeometricTool, HookTool, MagnetTool, PaintBrushTool, PlasticTool, PumpTool, RasterTapeTool, RGBPickerTool, RulerTool, SelectionTool, ShiftTraceTool, SkeletonTool, StylePickerTool, ToonzRasterBrushTool, ToonzVectorBrushTool, TrackerTool, TypeTool, EraserTool, VectorSelectionTool, VectorTapeTool, RotateTool, CameraTestTool, and SetScanCropboxTool.
Referenced by SceneViewer::invalidateToolStatus(), and SceneViewer::onToolChanged().
getFrame()
int TTool::getFrame ()
Returns the actual frame in use.
                    {
  if (!m_application) return 0;
  return m_application->getCurrentFrame()->getFrame();
}
Referenced by EditTool::draw(), and HookTool::draw().
getImage()
TImage * TTool::getImage (bool toBeModified, int subsampling = 0) static
Returns the image to be edited by the tool.
The image returned by getImage() is either the one associated to getImageCell(), or the vector image corresponding to currently edited spline path.
{
  assert(m_application);
  if (m_application->getCurrentFrame()->isPlaying())
    toBeModified =
        false;  // In playback mode, you are not going to modify images
                // Probably useless - tools are disabled when playing...
  const TXshCell &cell = getImageCell();
  if (cell.isEmpty()) {
    TObjectHandle *currentObject = m_application->getCurrentObject();
    return currentObject->isSpline() ? currentObject->getSplineImage()
                                     : (TImage *)0;
  } else
    return cell.getImage(toBeModified, subsampling).getPointer();
}
References TXshCell::getImage(), getImageCell(), and TXshCell::isEmpty().
Referenced by PinchTool::draw(), ControlPointEditorTool::draw(), FillTool::draw(), FingerTool::draw(), FullColorBrushTool::draw(), FullColorEraserTool::draw(), HookTool::draw(), MagnetTool::draw(), PaintBrushTool::draw(), PumpTool::draw(), ToonzRasterBrushTool::draw(), ToonzVectorBrushTool::draw(), TypeTool::draw(), EraserTool::draw(), VectorTapeTool::draw(), FingerTool::finishBrush(), PaintBrushTool::finishBrush(), ToonzRasterBrushTool::finishRasterBrush(), StylePickerTool::getCursorId(), EraserTool::leftButtonDoubleClick(), FillTool::onActivate(), GeometricTool::onActivate(), PumpTool::onDeactivate(), EraserTool::onDeactivate(), ControlPointEditorTool::onEnter(), FingerTool::onEnter(), FullColorEraserTool::onEnter(), GeometricTool::onEnter(), MagnetTool::onEnter(), PaintBrushTool::onEnter(), PumpTool::onEnter(), ToonzRasterBrushTool::onEnter(), ToonzVectorBrushTool::onEnter(), ControlPointEditorTool::onImageChanged(), FillTool::onImageChanged(), FillTool::onPropertyChanged(), and GeometricTool::onPropertyChanged().
getImageCell()
TXshCell TTool::getImageCell () static
Returns the level-frame pair to be edited by the tool.
Warning
In case there is no level currently selected, or the object to be edited is a spline path, the xsheet cell returned by getImageCell() is empty.
{
  assert(m_application);
  TXshCell result;
  TFrameHandle *currentFrame    = m_application->getCurrentFrame();
  TXshLevelHandle *currentLevel = m_application->getCurrentLevel();
  if (currentFrame->isEditingLevel()) {
    if (TXshLevel *xl = currentLevel->getLevel()) {
      if (TXshSimpleLevel *sl = xl->getSimpleLevel()) {
        result.m_level   = xl;
        result.m_frameId = currentFrame->getFid();
      }
    }
  } else {
    if (TXsheet *xsh = m_application->getCurrentXsheet()->getXsheet()) {
      if (!m_application->getCurrentObject()->isSpline()) {
        int row = currentFrame->getFrame();
        int col = m_application->getCurrentColumn()->getColumnIndex();
        result = xsh->getCell(row, col);
      }
    }
  }
  return result;
}
References TXshSimpleLevel::getSimpleLevel().
Referenced by getImage().
getMatrix()
const TAffine & TTool::getMatrix () const inline
{ return m_matrix; }
getName()
std::string TTool::getName () const inline
{ return m_name; }
getObjectId()
TStageObjectId TTool::getObjectId () const
Returns a pointer to the actual stage object.
{
  if (!m_application) return TStageObjectId();
  return m_application->getCurrentObject()->getObjectId();
}
Referenced by EditTool::draw(), and EditTool::onActivate().
getPixelSize()
double TTool::getPixelSize () const
{
  return m_viewer ? m_viewer->getPixelSize() : 1.0;
}
getProperties()
virtual TPropertyGroup * TTool::getProperties (int) inline virtual
{ return 0; }
getSelectedFrames()
static const std::set< TFrameId > & TTool::getSelectedFrames () inline static
{
    return m_selectedFrames;
  }
getSelection()
virtual TSelection * TTool::getSelection () inline virtual
Returns a pointer to the tool selection.
Reimplemented in RasterSelectionTool, VectorSelectionTool, and SelectionTool.
getTargetType()
ToolTargetType TTool::getTargetType () const inline
{ return (ToolTargetType)m_targetType; }
getTool()
TTool * TTool::getTool (std::string toolName, ToolTargetType targetType) static
{
  if (!toolTable) return 0;
  ToolTable::iterator it =
      toolTable->find(std::make_pair(toolName, targetType));
  if (it == toolTable->end()) return 0;
  return it->second;
}
getViewer()
Viewer * TTool::getViewer () const inline
{ return m_viewer; }
getXsheet()
TXsheet * TTool::getXsheet () const
Returns a pointer to the actual Xsheet.
{
  if (!m_application) return 0;
  return m_application->getCurrentXsheet()->getXsheet();
}
Referenced by EditTool::draw(), HookTool::draw(), SkeletonTool::draw(), and RasterSelection::pasteSelection().
invalidate()
void TTool::invalidate (const TRectD & rect = TRectD())
Causes the refreshing of the rect portion of the viewer. If rect is empty all viewer is refreshed. rect must be in image coordinate.
{
  if (m_viewer) {
    if (rect.isEmpty())
      m_viewer->GLInvalidateAll();
    else {
      TPointD dpiScale(1, 1);
      TXshSimpleLevel *sl =
          getApplication()->getCurrentLevel()->getSimpleLevel();
      if (sl) dpiScale = getCurrentDpiScale(sl, getCurrentFid());
      m_viewer->GLInvalidateRect(getCurrentColumnMatrix() *
                                 TScale(dpiScale.x, dpiScale.y) * rect);
    }
  }
}
References getCurrentColumnMatrix(), getCurrentFid(), TTool::Viewer::GLInvalidateAll(), TTool::Viewer::GLInvalidateRect(), TRectT< T >::isEmpty(), and m_viewer.
Referenced by RasterTapeTool::closePolyline(), FingerTool::finishBrush(), PaintBrushTool::finishBrush(), ToonzRasterBrushTool::finishRasterBrush(), EraserTool::leftButtonDoubleClick(), PumpTool::onDeactivate(), PinchTool::onImageChanged(), GeometricTool::onImageChanged(), HookTool::onImageChanged(), SkeletonTool::onImageChanged(), FingerTool::onPropertyChanged(), FullColorEraserTool::onPropertyChanged(), MagnetTool::onPropertyChanged(), PaintBrushTool::onPropertyChanged(), SkeletonTool::onPropertyChanged(), ToonzRasterBrushTool::onPropertyChanged(), TrackerTool::onPropertyChanged(), EraserTool::onPropertyChanged(), FullColorBrushTool::preLeftButtonDown(), ToonzRasterBrushTool::preLeftButtonDown(), and ToonzVectorBrushTool::preLeftButtonDown().
isActive()
bool TTool::isActive () const inline
Used to know if a tool is active, (used in TextTool only).
isColumnLocked()
bool TTool::isColumnLocked (int columnIndex) const
{
  if (columnIndex < 0) return false;
  TXsheet *xsh       = getXsheet();
  TXshColumn *column = xsh->getColumn(columnIndex);
  if (!column) return false;
  return column->isLocked();
}
isDragging()
virtual bool TTool::isDragging () const inline virtual
{ return false; };
isEnabled()
bool TTool::isEnabled () const inline
{ return m_enabled; }
isEventAcceptable()
virtual bool TTool::isEventAcceptable (QEvent * e) inline virtual
{ return false; }
isPencilModeActive()
virtual bool TTool::isPencilModeActive () inline virtual
Reimplemented in ToonzRasterBrushTool, and ToonzVectorBrushTool.
{ return false; }
isPicking()
bool TTool::isPicking () const inline
{ return m_picking; }
keyDown()
virtual bool TTool::keyDown (QKeyEvent *) inline virtual
{ return false; }
leftButtonDoubleClick()
virtual void TTool::leftButtonDoubleClick (const TPointD & , const TMouseEvent &) inline virtual
Reimplemented in EraserTool.
{}
leftButtonDown()
virtual void TTool::leftButtonDown (const TPointD & , const TMouseEvent &) inline virtual
{}
leftButtonDrag()
virtual void TTool::leftButtonDrag (const TPointD & , const TMouseEvent &) inline virtual
{}
leftButtonUp()
virtual void TTool::leftButtonUp (const TPointD & , const TMouseEvent &) inline virtual
{}
mouseMove()
virtual void TTool::mouseMove (const TPointD & , const TMouseEvent &) inline virtual
{}
notifyImageChanged() [1/2]
void TTool::notifyImageChanged ()
Notifies changes on the actual image; used to update
Notify change of current image: update icon and notify level change. If current object is a spline commit spline changed. If current mode is EditingLevel touch current frame.
{
  onImageChanged();
  if (!m_application) return;
  m_application->getCurrentScene()->setDirtyFlag(true);
  if (m_application->getCurrentFrame()->isEditingLevel()) {
    TXshLevel *xl = m_application->getCurrentLevel()->getLevel();
    if (!xl) return;
    TXshSimpleLevel *sl = xl->getSimpleLevel();
    if (!sl) return;
    TFrameId fid = m_application->getCurrentFrame()->getFid();
    sl->touchFrame(fid);
    // sl->setDirtyFlag(true);
    IconGenerator::instance()->invalidate(sl, fid);
    IconGenerator::instance()->invalidateSceneIcon();
  } else {
    TXsheet *xsh = m_application->getCurrentXsheet()->getXsheet();
    if (!xsh) return;
    TObjectHandle *currentObject = m_application->getCurrentObject();
    if (currentObject->isSpline()) {
      m_application->getCurrentObject()->commitSplineChanges();
      TStageObject *pegbar = xsh->getStageObject(currentObject->getObjectId());
      IconGenerator::instance()->invalidate(pegbar->getSpline());
    } else {
      int row = m_application->getCurrentFrame()->getFrame();
      int col = m_application->getCurrentColumn()->getColumnIndex();
      if (col < 0) return;
      TXshCell cell       = xsh->getCell(row, col);
      TXshSimpleLevel *sl = cell.getSimpleLevel();
      if (sl) {
        IconGenerator::instance()->invalidate(sl, cell.m_frameId);
        sl->touchFrame(cell.m_frameId);
        IconGenerator::instance()->invalidateSceneIcon();
      }
    }
  }
  m_application->getCurrentLevel()->notifyLevelChange();
}
References TXsheet::getCell(), TXshLevel::getSimpleLevel(), TXshCell::getSimpleLevel(), TStageObject::getSpline(), TXsheet::getStageObject(), onImageChanged(), and TXshSimpleLevel::touchFrame().
Referenced by RasterSelection::deleteSelection(), FingerTool::finishBrush(), PaintBrushTool::finishBrush(), ToonzRasterBrushTool::finishRasterBrush(), EraserTool::leftButtonDoubleClick(), RasterSelection::makeFloating(), FillTool::onPropertyChanged(), RasterTapeTool::onPropertyChanged(), VectorTapeTool::onPropertyChanged(), RasterSelection::pasteFloatingSelection(), and DragSelectionTool::VectorDeformTool::transformWholeLevel().
notifyImageChanged() [2/2]
void TTool::notifyImageChanged (const TFrameId & fid)
images on the level view.
Notifies changes on the
Notify change of image in fid: update icon and notify level change.
{
  onImageChanged();
  if (!m_application) return;
  m_application->getCurrentScene()->setDirtyFlag(true);
  if (m_application->getCurrentFrame()->isEditingLevel()) {
    TXshLevel *xl = m_application->getCurrentLevel()->getLevel();
    if (!xl) return;
    TXshSimpleLevel *sl = xl->getSimpleLevel();
    if (!sl) return;
    sl->setDirtyFlag(true);
    IconGenerator::instance()->invalidate(sl, fid);
    IconGenerator::instance()->invalidateSceneIcon();
  } else {
    int row = m_application->getCurrentFrame()->getFrame();
    int col = m_application->getCurrentColumn()->getColumnIndex();
    if (col < 0) return;
    TXsheet *xsh = m_application->getCurrentXsheet()->getXsheet();
    if (!xsh) return;
    TXshCell cell       = xsh->getCell(row, col);
    TXshSimpleLevel *sl = cell.getSimpleLevel();
    if (sl) {
      IconGenerator::instance()->invalidate(sl, fid);
      IconGenerator::instance()->invalidateSceneIcon();
      sl->setDirtyFlag(true);
    }
  }
  m_application->getCurrentLevel()->notifyLevelChange();
}
References TXsheet::getCell(), TXshLevel::getSimpleLevel(), TXshCell::getSimpleLevel(), onImageChanged(), and TXshSimpleLevel::setDirtyFlag().
onActivate()
virtual void TTool::onActivate () inline virtual
Callback invoked whenever the tool activates.
Reimplemented in PinchTool, ControlPointEditorTool, EditTool, FillTool, FingerTool, FullColorBrushTool, FullColorEraserTool, FullColorFillTool, GeometricTool, HookTool, MagnetTool, PaintBrushTool, PlasticTool, RasterSelectionTool, RasterTapeTool, RGBPickerTool, RulerTool, SelectionTool, ShiftTraceTool, SkeletonTool, ToonzRasterBrushTool, ToonzVectorBrushTool, TrackerTool, TypeTool, EraserTool, VectorSelectionTool, VectorTapeTool, and SetScanCropboxTool.
onDeactivate()
virtual void TTool::onDeactivate () inline virtual
Callback for tool deactivation, includes tool switch.
Reimplemented in PinchTool, ControlPointEditorTool, EditTool, FillTool, FingerTool, FullColorBrushTool, FullColorEraserTool, GeometricTool, HookTool, PaintBrushTool, PlasticTool, PumpTool, RasterTapeTool, SelectionTool, ShiftTraceTool, SkeletonTool, ToonzRasterBrushTool, ToonzVectorBrushTool, TrackerTool, TypeTool, EraserTool, and VectorSelectionTool.
onEnter()
virtual void TTool::onEnter () inline virtual
Callback for the mouse entering the viewer area.
Reimplemented in PinchTool, ControlPointEditorTool, FillTool, FingerTool, FullColorBrushTool, FullColorEraserTool, GeometricTool, HookTool, MagnetTool, PaintBrushTool, PlasticTool, PumpTool, RasterTapeTool, SkeletonTool, ToonzRasterBrushTool, ToonzVectorBrushTool, TrackerTool, EraserTool, VectorTapeTool, and SetScanCropboxTool.
onFrameSwitched()
virtual void TTool::onFrameSwitched () inline virtual
{}
onImageChanged()
virtual void TTool::onImageChanged () inline virtual
Notifies changes in the image in use.
Reimplemented in PinchTool, ControlPointEditorTool, FillTool, FullColorBrushTool, FullColorEraserTool, GeometricTool, HookTool, RasterSelectionTool, RasterTapeTool, RGBPickerTool, RulerTool, SkeletonTool, StylePickerTool, ToonzRasterBrushTool, TrackerTool, TypeTool, EraserTool, VectorSelectionTool, and SelectionTool.
Referenced by SceneViewer::drawOverlay(), and notifyImageChanged().
onInputText()
virtual void TTool::onInputText (std::wstring , std::wstring , int , int) inline virtual
{};
onLeave()
virtual void TTool::onLeave () inline virtual
Callback for the mouse leaving the viewer area.
Reimplemented in PinchTool, ControlPointEditorTool, FingerTool, FullColorBrushTool, PaintBrushTool, PlasticTool, PumpTool, ShiftTraceTool, ToonzRasterBrushTool, ToonzVectorBrushTool, TrackerTool, EraserTool, and VectorTapeTool.
onPropertyChanged()
virtual bool TTool::onPropertyChanged (std::string propertyName) inline virtual
 Does the tasks associated to changes in \p propertyName and returns \p
true; Does the tasks associated to changes in propertyName and returns true.
Reimplemented in ControlPointEditorTool, EditTool, FillTool, FingerTool, FullColorBrushTool, FullColorEraserTool, FullColorFillTool, GeometricTool, MagnetTool, PaintBrushTool, PlasticTool, RasterSelectionTool, RasterTapeTool, RGBPickerTool, SelectionTool, SkeletonTool, StylePickerTool, ToonzRasterBrushTool, ToonzVectorBrushTool, TrackerTool, TypeTool, EraserTool, VectorSelectionTool, and VectorTapeTool.
onSelectedFramesChanged()
virtual void TTool::onSelectedFramesChanged () inline protected virtual
{}
onSetViewer()
virtual void TTool::onSetViewer () inline virtual
{}
pick()
int TTool::pick (const TPointD & p)
Picks a region of the scene, using an OpenGL projection matrix to restrict drawing to a small regionaround p of the viewport. Returns -1 if no object's view has been changed.
{
  if (!m_viewer) return 0;
  m_picking = true;
  int ret   = m_viewer->pick(p);
  m_picking = false;
  return ret;
}
References m_viewer, and TTool::Viewer::pick().
preLeftButtonDown()
virtual bool TTool::preLeftButtonDown () inline virtual
This method is called before leftButtonDown() and can be used e.g. to create the image if needed. return true if the method execution can have changed the current tool
Reimplemented in FullColorBrushTool, GeometricTool, ToonzRasterBrushTool, ToonzVectorBrushTool, and TypeTool.
{ return false; }
reset()
virtual void TTool::reset () inline virtual
{}
resetInputMethod()
void TTool::resetInputMethod ()
Resets Input Context (IME)
{
  if (m_viewer) m_viewer->resetInputMethod();
}
References m_viewer.
Referenced by TypeTool::onDeactivate().
rightButtonDown()
virtual void TTool::rightButtonDown (const TPointD & , const TMouseEvent &) inline virtual
{}
setActive()
void TTool::setActive (bool active) inline
{ m_active = active; }
setApplication()
static void TTool::setApplication (TApplication * application) inline static
{
    m_application = application;
  }
setMatrix()
void TTool::setMatrix (const TAffine & matrix) inline
{ m_matrix = matrix; }
setSelectedFrames()
void TTool::setSelectedFrames (const std::set< TFrameId > & selectedFrames)
{
  m_selectedFrames = selectedFrames;
  onSelectedFramesChanged();
}
setViewer()
void TTool::setViewer (Viewer * viewer) inline
{
    m_viewer = viewer;
    onSetViewer();
  }
touchImage()
TImage * TTool::touchImage () static
Returns a pointer to the actual image - the one of the frame that has been selected.
{
  if (!m_application) return 0;
  m_cellsData.clear();
  m_oldFids.clear();
  m_newFids.clear();
  m_isLevelCreated     = false;
  m_isFrameCreated     = false;
  m_isLevelRenumbererd = false;
  Preferences *pref    = Preferences::instance();
  bool isAutoCreateEnabled        = pref->isAutoCreateEnabled();
  bool animationSheetEnabled      = pref->isAnimationSheetEnabled();
  bool isAutoStretchEnabled       = pref->isAutoStretchEnabled();
  bool isAutoRenumberEnabled      = pref->isAutorenumberEnabled();
  bool isCreateInHoldCellsEnabled = pref->isCreationInHoldCellsEnabled();
  TFrameHandle *currentFrame    = m_application->getCurrentFrame();
  TXshLevelHandle *currentLevel = m_application->getCurrentLevel();
  if (currentFrame->isEditingLevel()) {
    // Editing level
    // no level => return 0
    TXshLevel *xl = currentLevel->getLevel();
    if (!xl) return 0;
    TXshSimpleLevel *sl = xl->getSimpleLevel();
    if (!sl || sl->isEmpty()) return 0;
    TFrameId fid = currentFrame->getFid();
    TImageP img  = sl->getFrame(fid, true);
    if (!img) {
      // no drawing found
      if (sl->isSubsequence() || sl->isReadOnly() || !isAutoCreateEnabled)
        return 0;
      // create a new drawing
      img = sl->createEmptyFrame();
      sl->setFrame(fid, img);
      currentLevel->notifyLevelChange();
      m_isFrameCreated = true;
    }
    return img.getPointer();
  }
  //- - - - editing xsheet case starts here - - - -
  if (m_application->getCurrentObject()->isSpline()) return 0;
  TSceneHandle *currentScene = m_application->getCurrentScene();
  ToonzScene *scene          = currentScene->getScene();
  int row                    = currentFrame->getFrame();
  int col = m_application->getCurrentColumn()->getColumnIndex();
  if (col < 0) return 0;
  TXsheetHandle *currentXsheet = m_application->getCurrentXsheet();
  TXsheet *xsh                 = currentXsheet->getXsheet();
  if (!xsh) return 0;
  TXshCell cell       = xsh->getCell(row, col);
  TXshSimpleLevel *sl = cell.getSimpleLevel();
  if (sl) {
    // current cell is not empty
    if (isCreateInHoldCellsEnabled && row > 0 &&
        xsh->getCell(row - 1, col) == xsh->getCell(row, col)) {
      // CreateInHoldCells is enabled and the current cell is a "hold".
      // We must create a new drawing.
      // measure the hold length (starting from the current row) : r0-r1
      int r0 = row, r1 = row;
      if (isAutoStretchEnabled)
        while (xsh->getCell(r1 + 1, col) == cell) r1++;
      // find the proper frameid (possibly addisng suffix, in order to avoid a
      // fid already used)
      // find the proper frameid
      TFrameId fid;
      TXshCellColumn *column = xsh->getColumn(col)->getCellColumn();
      if (isAutoRenumberEnabled && column) {
        TFrameId maxFid;
        if (animationSheetEnabled) {
          fid    = TFrameId(row + 1);
          maxFid = TFrameId(row);
        } else {
          int r_begin, r_end;
          column->getRange(r_begin, r_end);
          fid = getDesiredFId(column, r_begin, sl, row, maxFid);
        }
        // renumber fids
        sl->getFids(m_oldFids);
        m_isLevelRenumbererd = ToolUtils::renumberForInsertFId(
            sl, fid, maxFid, scene->getTopXsheet());
        if (m_isLevelRenumbererd) sl->getFids(m_newFids);
      } else
        fid = (animationSheetEnabled) ? getNewFrameId(sl, row)
                                      : sl->index2fid(sl->getFrameCount());
      // create the new drawing
      TImageP img      = sl->createEmptyFrame();
      m_isFrameCreated = true;
      // insert the drawing in the level
      sl->setFrame(fid, img);
      // update the cell
      cell = TXshCell(sl, fid);
      // update the xsheet (change the current cell and possibly all the
      // following "hold")
      for (int r = r0; r <= r1; r++) xsh->setCell(r, col, cell);
      // notify
      currentXsheet->notifyXsheetChanged();
      currentScene->notifyCastChange();
      currentLevel->notifyLevelChange();
      m_cellsData.push_back({r0, r1, CellOps::ExistingToNew});
    }
    // if the level does not contain a frame in the current cell
    // (i.e. drawing on the cell with red numbers)
    else if (!sl->isFid(cell.getFrameId())) {
      // no drawing found
      if (sl->isSubsequence() || sl->isReadOnly() || !isAutoCreateEnabled)
        return 0;
      // create a new drawing
      TImageP img = sl->createEmptyFrame();
      sl->setFrame(cell.getFrameId(), img);
      currentXsheet->notifyXsheetChanged();
      currentLevel->notifyLevelChange();
      m_isFrameCreated = true;
      return img.getPointer();
    }
    // we've found the image. return it.
    return cell.getImage(true).getPointer();
  }
  // current cell is empty.
  if (!isAutoCreateEnabled) return 0;
  // get the column range
  int r0, r1;
  xsh->getCellRange(col, r0, r1);
  // in case the column is not empty
  if (r0 <= r1) {
    // We must create a new drawing in the column level and possibly add "holds"
    // find the last not-empty cell before the current one (a) and the first
    // after (b)
    int a = row - 1, b = row + 1;
    while (a >= r0 && xsh->getCell(a, col).isEmpty()) a--;
    while (b <= r1 && xsh->getCell(b, col).isEmpty()) b++;
    // find the level we must attach to
    if (a >= r0) {
      // there is a not-empty cell before the current one
      sl = xsh->getCell(a, col).getSimpleLevel();
    } else if (b <= r1) {
      sl = xsh->getCell(b, col).getSimpleLevel();
    }
    if (sl && !sl->isSubsequence() && !sl->isReadOnly()) {
      // note: sl should be always !=0 (the column is not empty)
      // if - for some reason - it is == 0 or it is not editable,
      // then we skip to empty-column behaviour
      // create the drawing
      // find the proper frameid
      TFrameId fid;
      TXshCellColumn *column = xsh->getColumn(col)->getCellColumn();
      if (isAutoRenumberEnabled && column) {
        TFrameId maxFid(row);
        fid = (animationSheetEnabled)
                  ? TFrameId(row + 1)
                  : getDesiredFId(column, r0, sl, row, maxFid);
        sl->getFids(m_oldFids);
        m_isLevelRenumbererd = ToolUtils::renumberForInsertFId(
            sl, fid, maxFid, scene->getTopXsheet());
        if (m_isLevelRenumbererd) sl->getFids(m_newFids);
      } else
        fid = (animationSheetEnabled) ? getNewFrameId(sl, row)
                                      : sl->index2fid(sl->getFrameCount());
      // create the new drawing
      TImageP img      = sl->createEmptyFrame();
      m_isFrameCreated = true;
      // insert the drawing in the level
      sl->setFrame(fid, img);
      // update the cell
      cell = TXshCell(sl, fid);
      xsh->setCell(row, col, cell);
      // create holds
      if (!isAutoStretchEnabled) {
        m_cellsData.push_back({row, row, CellOps::BlankToNew});
      } else {
        if (a >= r0) {
          // create a hold before : [a+1, row-1]
          TXshCell aCell = xsh->getCell(a, col);
          for (int i = a + 1; i < row; i++) xsh->setCell(i, col, aCell);
          m_cellsData.push_back({a + 1, row - 1, CellOps::BlankToExisting});
          if (b <= r1 && xsh->getCell(b, col).getSimpleLevel() == sl) {
            // create also a hold after
            for (int i = row + 1; i < b; i++) xsh->setCell(i, col, cell);
            m_cellsData.push_back({row, b - 1, CellOps::BlankToNew});
          } else {
            m_cellsData.push_back({row, row, CellOps::BlankToNew});
          }
        } else if (b <= r1) {
          // create a hold after
          for (int i = row + 1; i < b; i++) xsh->setCell(i, col, cell);
          m_cellsData.push_back({row, b - 1, CellOps::BlankToNew});
        }
      }
      // notify & return
      currentXsheet->notifyXsheetChanged();
      currentScene->notifyCastChange();
      currentLevel->notifyLevelChange();
      return cell.getImage(true).getPointer();
    }
  }
  // - - - - empty column case starts here - - - -
  // autoCreate is enabled: we must create a new level
  int levelType    = pref->getDefLevelType();
  TXshLevel *xl    = scene->createNewLevel(levelType);
  sl               = xl->getSimpleLevel();
  m_isLevelCreated = true;
  // create the drawing
  TFrameId fid = animationSheetEnabled ? getNewFrameId(sl, row) : TFrameId(1);
  TImageP img  = sl->createEmptyFrame();
  m_isFrameCreated = true;
  sl->setFrame(fid, img);
  cell = TXshCell(sl, fid);
  xsh->setCell(row, col, cell);
  m_cellsData.push_back({row, row, CellOps::BlankToNew});  // vuoto => nuovo
  currentXsheet->notifyXsheetChanged();
  currentScene->notifyCastChange();
  currentLevel->notifyLevelChange();
  return img.getPointer();
}
References TXshSimpleLevel::createEmptyFrame(), ToonzScene::createNewLevel(), TXsheet::getCell(), TXsheet::getCellRange(), TXsheet::getColumn(), TXshSimpleLevel::getFids(), TXshSimpleLevel::getFrameCount(), TXshCell::getFrameId(), TXshCell::getImage(), TXshLevel::getSimpleLevel(), TXshCell::getSimpleLevel(), ToonzScene::getTopXsheet(), TXshSimpleLevel::index2fid(), TXshCell::isEmpty(), TXshSimpleLevel::isEmpty(), TXshSimpleLevel::isFid(), m_cellsData, m_isFrameCreated, and m_isLevelCreated.
Referenced by RasterSelection::pasteSelection(), FullColorBrushTool::preLeftButtonDown(), GeometricTool::preLeftButtonDown(), ToonzRasterBrushTool::preLeftButtonDown(), ToonzVectorBrushTool::preLeftButtonDown(), and TypeTool::preLeftButtonDown().
tweenGuideStrokeToSelected()
void TTool::tweenGuideStrokeToSelected ()
{
  if (!getViewer() || !m_application) return;
  TXshSimpleLevel *sl =
      m_application->getCurrentLevel()->getLevel()->getSimpleLevel();
  if (!sl) return;
  int backIdx = -1, frontIdx = -1;
  getViewer()->getGuidedFrameIdx(&backIdx, &frontIdx);
  TFrameHandle *currentFrame = getApplication()->getCurrentFrame();
  int row                    = currentFrame->getFrameIndex();
  TFrameId bFid, cFid, fFid;
  TVectorImageP bvi, cvi, fvi;
  cFid = getCurrentFid();
  if (cFid.isEmptyFrame()) return;
  cvi = sl->getFrame(cFid, false);
  if (!cvi) return;
  int cStrokeCount = cvi->getStrokeCount();
  if (!cStrokeCount) return;
  StrokeSelection *strokeSelection =
      dynamic_cast<StrokeSelection *>(getSelection());
  if (!strokeSelection || strokeSelection->isEmpty()) return;
  const std::set<int> &selectedStrokeIdxs = strokeSelection->getSelection();
  const std::set<int>::iterator it        = selectedStrokeIdxs.begin();
  int cStrokeIdx                          = *it;
  TStroke *cStroke = cvi->getStroke(cStrokeIdx);
  if (!cStroke) return;
  if (backIdx != -1) {
    if (currentFrame->isEditingScene()) {
      TXsheet *xsh = m_application->getCurrentXsheet()->getXsheet();
      int col      = m_application->getCurrentColumn()->getColumnIndex();
      if (xsh && col >= 0) {
        TXshCell cell = xsh->getCell(backIdx, col);
        if (!cell.isEmpty()) bFid = cell.getFrameId();
      }
    } else
      bFid = sl->getFrameId(backIdx);
    if (!bFid.isEmptyFrame()) bvi = sl->getFrame(bFid, false);
  }
  if (frontIdx != -1) {
    if (currentFrame->isEditingScene()) {
      TXsheet *xsh = m_application->getCurrentXsheet()->getXsheet();
      int col      = m_application->getCurrentColumn()->getColumnIndex();
      if (xsh && col >= 0) {
        TXshCell cell = xsh->getCell(frontIdx, col);
        if (!cell.isEmpty()) fFid = cell.getFrameId();
      }
    } else
      fFid = sl->getFrameId(frontIdx);
    if (!fFid.isEmptyFrame()) fvi = sl->getFrame(fFid, false);
  }
  if (!bvi && !fvi) return;
  int bStrokeCount = bvi ? bvi->getStrokeCount() : 0;
  int fStrokeCount = fvi ? fvi->getStrokeCount() : 0;
  if (!bStrokeCount && !fStrokeCount) return;
  int bStrokeIdx = getViewer()->getGuidedBackStroke() != -1
                       ? getViewer()->getGuidedBackStroke()
                       : cStrokeCount;
  int fStrokeIdx = getViewer()->getGuidedFrontStroke() != -1
                       ? getViewer()->getGuidedFrontStroke()
                       : cStrokeCount;
  if ((bStrokeCount && bStrokeIdx >= bStrokeCount) ||
      (fStrokeCount && fStrokeIdx >= fStrokeCount))
    return;
  TStroke *bStroke = bvi ? bvi->getStroke(bStrokeIdx) : 0;
  TStroke *fStroke = fvi ? fvi->getStroke(fStrokeIdx) : 0;
  if (!bStroke && !fStroke) return;
  TTool *tool = TTool::getTool(T_Brush, TTool::ToolTargetType::VectorImage);
  ToonzVectorBrushTool *vbTool = (ToonzVectorBrushTool *)tool;
  if (vbTool) {
    m_isFrameCreated = false;
    m_isLevelCreated = false;
    vbTool->touchImage();
    vbTool->setViewer(m_viewer);
    TUndoManager::manager()->beginBlock();
    if (bStroke)
      vbTool->doFrameRangeStrokes(
          bFid, bStroke, cFid, cStroke,
          Preferences::instance()->getGuidedInterpolation(), false, false,
          false, false, false, false);
    if (fStroke)
      vbTool->doFrameRangeStrokes(
          cFid, cStroke, fFid, fStroke,
          Preferences::instance()->getGuidedInterpolation(), false, false,
          false, false, false, false);
    TUndoManager::manager()->endBlock();
  }
}
tweenSelectedGuideStrokes()
void TTool::tweenSelectedGuideStrokes ()
{
  if (!getViewer() || !m_application) return;
  TXshSimpleLevel *sl =
      m_application->getCurrentLevel()->getLevel()->getSimpleLevel();
  if (!sl) return;
  int backIdx = -1, frontIdx = -1;
  getViewer()->getGuidedFrameIdx(&backIdx, &frontIdx);
  if (backIdx == -1 || frontIdx == -1) return;
  TFrameHandle *currentFrame = getApplication()->getCurrentFrame();
  int row                    = currentFrame->getFrameIndex();
  TFrameId bFid, cFid, fFid;
  cFid = getCurrentFid();
  if (cFid.isEmptyFrame()) return;
  TVectorImageP cvi = sl->getFrame(cFid, false);
  if (!cvi) return;
  int cStrokeCount = cvi->getStrokeCount();
  if (currentFrame->isEditingScene()) {
    TXsheet *xsh = m_application->getCurrentXsheet()->getXsheet();
    int col      = m_application->getCurrentColumn()->getColumnIndex();
    if (xsh && col >= 0) {
      TXshCell cell = xsh->getCell(backIdx, col);
      if (!cell.isEmpty()) bFid = cell.getFrameId();
      cell = xsh->getCell(frontIdx, col);
      if (!cell.isEmpty()) fFid = cell.getFrameId();
    }
  } else {
    bFid = sl->getFrameId(backIdx);
    fFid = sl->getFrameId(frontIdx);
  }
  if (bFid.isEmptyFrame() || fFid.isEmptyFrame()) return;
  TVectorImageP bvi = sl->getFrame(bFid, false);
  TVectorImageP fvi = sl->getFrame(fFid, false);
  if (!bvi || !fvi) return;
  int bStrokeCount = bvi->getStrokeCount();
  int fStrokeCount = fvi->getStrokeCount();
  if (!bStrokeCount || !fStrokeCount) return;
  int bStrokeIdx = getViewer()->getGuidedBackStroke() != -1
                       ? getViewer()->getGuidedBackStroke()
                       : cStrokeCount;
  int fStrokeIdx = getViewer()->getGuidedFrontStroke() != -1
                       ? getViewer()->getGuidedFrontStroke()
                       : cStrokeCount;
  if (bStrokeIdx >= bStrokeCount || fStrokeIdx >= fStrokeCount) return;
  TStroke *bStroke = bvi->getStroke(bStrokeIdx);
  TStroke *fStroke = fvi->getStroke(fStrokeIdx);
  if (!bStroke || !fStroke) return;
  TTool *tool = TTool::getTool(T_Brush, TTool::ToolTargetType::VectorImage);
  ToonzVectorBrushTool *vbTool = (ToonzVectorBrushTool *)tool;
  if (vbTool) {
    m_isFrameCreated = false;
    m_isLevelCreated = false;
    vbTool->touchImage();
    vbTool->setViewer(m_viewer);
    vbTool->doFrameRangeStrokes(
        bFid, bStroke, fFid, fStroke,
        Preferences::instance()->getGuidedInterpolation(), false, false, false,
        false, false, true);
  }
}
updateEnabled() [1/2]
QString TTool::updateEnabled ()
Sets the tool's enability and returns a reason in case the tool was disabled.
{
  int rowIndex    = m_application->getCurrentFrame()->getFrame();
  int columnIndex = m_application->getCurrentColumn()->getColumnIndex();
  return updateEnabled(rowIndex, columnIndex);
}
References updateEnabled().
Referenced by SceneViewer::invalidateToolStatus(), updateEnabled(), and Toolbar::updateToolbar().
updateEnabled() [2/2]
QString TTool::updateEnabled (int rowIndex, int columnIndex) virtual
{
  // Disable every tool during playback
  if (m_application->getCurrentFrame()->isPlaying())
    return (enable(false), QString());
  // Release Generic tools at once
  int toolType   = getToolType();
  int targetType = getTargetType();
  if (toolType == TTool::GenericTool) return (enable(true), QString());
  // Retrieve vars and view modes
  TXsheet *xsh = m_application->getCurrentXsheet()->getXsheet();
  TXshColumn *column = (columnIndex >= 0) ? xsh->getColumn(columnIndex) : 0;
  TXshLevel *xl       = m_application->getCurrentLevel()->getLevel();
  TXshSimpleLevel *sl = xl ? xl->getSimpleLevel() : 0;
  int levelType       = sl ? sl->getType() : NO_XSHLEVEL;
  // If not in Level editor, let's use our current cell from the xsheet to
  // find the nearest level before it
  if (levelType == NO_XSHLEVEL &&
      !m_application->getCurrentFrame()->isEditingLevel()) {
    if (!column || (column && !column->getSoundColumn())) {
      TXshCell cell = xsh->getCell(rowIndex, columnIndex);
      xl            = cell.isEmpty() ? 0 : (TXshLevel *)(&cell.m_level);
      sl            = cell.isEmpty() ? 0 : cell.getSimpleLevel();
      levelType     = cell.isEmpty() ? NO_XSHLEVEL : cell.m_level->getType();
    }
  }
  if (Preferences::instance()->isAutoCreateEnabled()) {
    // If not in Level editor, let's use our current cell from the xsheet to
    // find the nearest level before it
    if (levelType == NO_XSHLEVEL &&
        !m_application->getCurrentFrame()->isEditingLevel()) {
      if (!column || (column && !column->getSoundColumn())) {
        int r0, r1;
        xsh->getCellRange(columnIndex, r0, r1);
        for (int r = std::min(r1, rowIndex); r > r0; r--) {
          TXshCell cell = xsh->getCell(r, columnIndex);
          if (cell.isEmpty()) continue;
          xl        = (TXshLevel *)(&cell.m_level);
          sl        = cell.getSimpleLevel();
          levelType = cell.m_level->getType();
          break;
        }
      }
    }
    // If the current tool does not match the current type, check for
    // a version of the same tool that does
    {
      TTool *tool = this;
      if ((levelType == PLI_XSHLEVEL) && !(targetType & VectorImage))
        tool = TTool::getTool(m_name, VectorImage);
      else if ((levelType == TZP_XSHLEVEL) && !(targetType & ToonzImage))
        tool = TTool::getTool(m_name, ToonzImage);
      else if ((levelType == OVL_XSHLEVEL) && !(targetType & RasterImage))
        tool = TTool::getTool(m_name, RasterImage);
      else if ((levelType == MESH_XSHLEVEL) && !(targetType & MeshImage))
        tool = TTool::getTool(m_name, MeshImage);
      if (tool && tool != this && tool->getTargetType() != TTool::NoTarget)
        return tool->updateEnabled();
    }
  }
  bool spline = m_application->getCurrentObject()->isSpline();
  bool filmstrip = m_application->getCurrentFrame()->isEditingLevel();
  /*-- MultiLayerStylePickerON --*/
  if (m_name == T_StylePicker &&
      Preferences::instance()->isMultiLayerStylePickerEnabled())
    return (enable(true), QString());
  // Check against camera column
  if (!filmstrip && columnIndex < 0 && (targetType & TTool::EmptyTarget) &&
      (m_name == T_Type || m_name == T_Geometric || m_name == T_Brush))
    return (enable(false), QString());
  bool isZeraryCol =
      column ? (column->getZeraryFxColumn() ? true : false) : false;
  bool isPaletteCol =
      column ? (column->getPaletteColumn() ? true : false) : false;
  bool isMeshCol = column ? (column->getMeshColumn() ? true : false) : false;
  // Check against splines
  if (spline && (toolType & TTool::LevelTool)) {
    return (targetType & Splines)
               ? (enable(true), QString())
               : (enable(false), QObject::tr("The current tool cannot be "
                                             "used to edit a motion path."));
  }
  // Check against unplaced columns (not in filmstrip mode)
  if (column && !filmstrip) {
    if (column->isLocked() && m_name != T_Selection)
      return (enable(false), QObject::tr("The current column is locked."));
    else if (!column->isCamstandVisible())
      return (enable(false), QObject::tr("The current column is hidden."));
    else if (column->getSoundColumn())
      return (enable(false),
              QObject::tr("It is not possible to edit the audio column."));
    else if (column->getSoundTextColumn())
      return (
          enable(false),
          QObject::tr(
              "Note columns can only be edited in the xsheet or timeline."));
    if (toolType == TTool::ColumnTool) {
      // Check column target
      if (column->getLevelColumn() && !(targetType & LevelColumns))
        return (
            enable(false),
            QObject::tr("The current tool cannot be used on a Level column."));
      if (column->getMeshColumn() && !(targetType & MeshColumns))
        return (
            enable(false),
            QObject::tr("The current tool cannot be used on a Mesh column."));
    }
  }
  // Check column tools
  if (toolType == TTool::ColumnTool) {
    if (filmstrip)
      return (
          enable(false),
          QObject::tr("The current tool cannot be used in Level Strip mode."));
    if ((!column || column->isEmpty()) && !(targetType & TTool::EmptyTarget))
      return (enable(false), QString());
  }
  // Check LevelRead & LevelWrite tools
  if (toolType & TTool::LevelTool) {
    // Check against empty levels
    if (!xl)
      return ((targetType & EmptyTarget) && !isZeraryCol && !isPaletteCol &&
              !isMeshCol)
                 ? (enable(true), QString())
                 : (enable(false), QString());
    // Check against simple-level-edness
    if (!sl)
      return (enable(false),
              QObject::tr("The current level is not editable."));  // Does it
                                                                   // happen at
                                                                   // all btw?
    // Check against level types
    {
      if ((levelType == PLI_XSHLEVEL) && !(targetType & VectorImage))
        return (
            enable(false),
            QObject::tr("The current tool cannot be used on a Vector Level."));
      if ((levelType == TZP_XSHLEVEL) && !(targetType & ToonzImage))
        return (
            enable(false),
            QObject::tr("The current tool cannot be used on a Toonz Level."));
      if ((levelType == OVL_XSHLEVEL) && !(targetType & RasterImage))
        return (
            enable(false),
            QObject::tr("The current tool cannot be used on a Raster Level."));
      if ((levelType == MESH_XSHLEVEL) && !(targetType & MeshImage))
        return (
            enable(false),
            QObject::tr("The current tool cannot be used on a Mesh Level."));
    }
    // Check against impossibly traceable movements on the column
    if ((levelType & LEVELCOLUMN_XSHLEVEL) && !filmstrip && columnIndex >= 0) {
      TStageObject *obj =
          xsh->getStageObject(TStageObjectId::ColumnId(columnIndex));
      // Test for Mesh-deformed levels
      const TStageObjectId &parentId = obj->getParent();
      if (parentId.isColumn() && obj->getParentHandle()[0] != 'H') {
        TXshSimpleLevel *parentSl =
            xsh->getCell(rowIndex, parentId.getIndex()).getSimpleLevel();
        if (parentSl && parentSl->getType() == MESH_XSHLEVEL &&
            m_name != T_Selection)
          return (
              enable(false),
              QObject::tr(
                  "The current tool cannot be used on a mesh-deformed level"));
      }
    }
    // Check TTool::ImageType tools
    if (toolType == TTool::LevelWriteTool && m_name != T_Selection) {
      // Check level against read-only status
      if (sl->isFrameReadOnly(getCurrentFid()))
        return (enable(false),
                QObject::tr(
                    "The current frame is locked: any editing is forbidden."));
      // Check level type write support
      if (sl->getPath().getType() ==
              "psd" ||  // We don't have the API to write psd files
          sl->getPath().getType() == "gif" ||
          sl->getPath().getType() == "mp4" ||
          sl->getPath().getType() == "webm" ||
          sl->is16BitChannelLevel() ||  // Inherited by previous
                                        // implementation.
                                        // Could be fixed?
          sl->getProperties()->getBpp() ==
              1)  // Black & White images. Again, could be fixed?
        return (enable(false),
                QObject::tr("The current level is not editable."));
    }
  }
  return (enable(true), QString());
}
updateMatrix()
void TTool::updateMatrix () virtual
Updates the current matrix transformation with the actual column matrix transformation.
See also
getCurrentColumnMatrix().
Reimplemented in EditTool, HookTool, SkeletonTool, and RotateTool.
{
  assert(m_application);
  if (m_application->getCurrentObject()->isSpline())
    setMatrix(getCurrentObjectParentMatrix2());
  else
    setMatrix(getCurrentColumnMatrix());
}
References getCurrentColumnMatrix().
Referenced by SceneViewer::invalidateToolStatus(), and HookTool::updateMatrix().
updateToolsPropertiesTranslation()
void TTool::updateToolsPropertiesTranslation () static
This function is necessary since tools are created before the main application (TAB or Toonz) starts, and hence tr() calls have no effect (the translation is not yet installed - to install one you need at least an instance of QApplication / QCoreApplication).
Deprecated:
This so much stinks of a bug turned into design choice...
Updates translation of the bound properties of
{
  ToolTable::iterator tt, tEnd(toolTable->end());
  for (tt = toolTable->begin(); tt != tEnd; ++tt)
    tt->second->updateTranslation();
}
updateTranslation()
virtual void TTool::updateTranslation () inline virtual
{};
Member Data Documentation
m_active
bool TTool::m_active protected
m_application
TTool::Application * TTool::m_application = 0 static protected
m_cellsData
std::vector< TTool::CellOps > TTool::m_cellsData static
Deprecated:
brutto brutto. fix quick & dirty del baco #6213 (undo
Referenced by touchImage().
m_enabled
bool TTool::m_enabled protected
Whether the tool allows user interaction.
m_isFrameCreated
bool TTool::m_isFrameCreated = false static
Deprecated:
Shouldn't expose global static variables.
Referenced by ToonzRasterBrushTool::finishRasterBrush(), FullColorBrushTool::preLeftButtonDown(), ToonzRasterBrushTool::preLeftButtonDown(), ToonzVectorBrushTool::preLeftButtonDown(), and touchImage().
m_isLevelCreated
bool TTool::m_isLevelCreated = false static
con animation sheet) spiegazioni in tool.cpp
Deprecated:
Shouldn't expose global static variables.
Referenced by ToonzRasterBrushTool::finishRasterBrush(), and touchImage().
m_isLevelRenumbererd
bool TTool::m_isLevelRenumbererd = false static
m_matrix
TAffine TTool::m_matrix protected
World-to-window reference change affine.
m_name
std::string TTool::m_name protected
The tool's name.
m_newFids
std::vector< TFrameId > TTool::m_newFids static
m_oldFids
std::vector< TFrameId > TTool::m_oldFids static
m_picking
bool TTool::m_picking protected
m_selectedFrames
std::set< TFrameId > TTool::m_selectedFrames = std::set<TFrameId>() static protected
m_targetType
int TTool::m_targetType protected
The tool's image type target.
Referenced by FillTool::draw(), FillTool::onActivate(), and GeometricTool::onActivate().
m_viewer
Viewer* TTool::m_viewer protected
Tool's current viewer.
Referenced by RotateTool::draw(), ControlPointEditorTool::getCursorId(), GeometricTool::getCursorId(), MagnetTool::getCursorId(), PumpTool::getCursorId(), ToonzVectorBrushTool::getCursorId(), TypeTool::getCursorId(), VectorSelectionTool::getCursorId(), invalidate(), pick(), and resetInputMethod().
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/tools/tool.h
E:/opentoonz/toonz/sources/tnztools/tool.cpp