opentoonz: TQuadratic Class Reference
TQuadratic Class Reference
#include <tcurves.h>
Public Member Functions
TQuadratic (const TPointD &p0, const TPointD &p1, const TPointD &p2)
p0,p1,p2 are the three control points
TQuadratic (const TQuadratic &src)
TQuadratic & operator= (const TQuadratic &src)
TPointD getPoint (double t) const
Return the point of quadratic at parameter t.
double getX (double t) const
double getY (double t) const
TPointD getSpeed (double t) const
Return speed of quadratic at parameter t.
double getSpeedY (double t) const
Return the y value of quadratic speed at parameter t.
TPointD getAcceleration (double=0) const
Return acceleration of quadratic.
double getCurvature (double t) const
Return curvature of quadratic at parameter t.
TPointD getP0 () const
Return first control point P0.
TPointD getP1 () const
Return second control point P1.
TPointD getP2 () const
Return third control point P2.
void setP0 (const TPointD &p)
Set the value of first control point P0 to p.
void setP1 (const TPointD &p)
Set the value of second control point P1 to p.
void setP2 (const TPointD &p)
Set the value of third control point P2 to p.
bool operator== (const TQuadratic &c) const
bool operator!= (const TQuadratic &c) const
double getT (const TPointD &p) const
Return a parameter that correspond to the point p in the quadratic.
int getX (double y, double &x0, double &x1) const
int getY (double x, double &y0, double &y1) const
void split (double t, TQuadratic &first, TQuadratic &second) const
TRectD getBBox () const
Return rect that contains the quadratic.
double getLength (double t0, double t1) const
double getLength (double t1=1) const
double getApproximateLength (double t0, double t1, double error) const
void reverse ()
Protected Attributes
TPointD m_p0
TPointD m_p1
TPointD m_p2
Detailed Description
TQuadratic class to manage a quadratic
Constructor & Destructor Documentation
TQuadratic() [1/3]
TQuadratic::TQuadratic () inline
: m_p0(), m_p1(), m_p2() {}
TQuadratic() [2/3]
TQuadratic::TQuadratic (const TPointD & p0, const TPointD & p1, const TPointD & p2) inline
p0,p1,p2 are the three control points
      : m_p0(p0), m_p1(p1), m_p2(p2) {}
TQuadratic() [3/3]
TQuadratic::TQuadratic (const TQuadratic & src) inline
      : m_p0(src.m_p0), m_p1(src.m_p1), m_p2(src.m_p2) {}
Member Function Documentation
getAcceleration()
TPointD TQuadratic::getAcceleration (double = 0) const inline
Return acceleration of quadratic.
{
    return 2.0 * (m_p0 + m_p2 - 2.0 * m_p1);
  }
getApproximateLength()
double TQuadratic::getApproximateLength (double t0, double t1, double error) const
{
  if (t0 == t1) return 0;
  t0 = min(max(0.0, t0), 1.0);
  t1 = min(max(0.0, t1), 1.0);
  if (t0 > t1) std::swap(t0, t1);
  TQuadratic q;
  if (t0 == 0.0 && t1 == 1.0)
    q = *this;
  else {
    TQuadratic q1;
    split(t0, q, q1);
    assert(t0 != 1.0);
    double newPar = (t1 - t0) / (1.0 - t0);
    q1.split(newPar, q, q1);
  }
  double step = computeStep(q, error);
  double length = 0.0;
  TPointD p1 = q.getP0();
  TPointD p2;
  for (double t = step; t < 1.0; t += step) {
    p2 = q.getPoint(t);
    length += tdistance(p1, p2);
    p1 = p2;
  }
  length += tdistance(p1, q.getP2());
  return length;
}
getBBox()
TRectD TQuadratic::getBBox () const
Return rect that contains the quadratic.
{
  TRectD bBox;
  if (m_p0.x < m_p2.x)
    bBox.x0 = m_p0.x, bBox.x1 = m_p2.x;
  else
    bBox.x0 = m_p2.x, bBox.x1 = m_p0.x;
  if (m_p0.y < m_p2.y)
    bBox.y0 = m_p0.y, bBox.y1 = m_p2.y;
  else
    bBox.y0 = m_p2.y, bBox.y1 = m_p0.y;
  TPointD denom = 2 * m_p1 - m_p0 - m_p2;
  if (denom.x != 0) {
    double tx = (m_p1.x - m_p0.x) / denom.x;
    if (tx >= 0 && tx <= 1) {
      double x = getPoint(tx).x;
      if (x < bBox.x0)
        bBox.x0 = x;
      else if (x > bBox.x1)
        bBox.x1 = x;
    }
  }
  if (denom.y != 0) {
    double ty = (m_p1.y - m_p0.y) / denom.y;
    if (ty >= 0 && ty <= 1) {
      double y = getPoint(ty).y;
      if (y < bBox.y0)
        bBox.y0 = y;
      else if (y > bBox.y1)
        bBox.y1 = y;
    }
  }
  return bBox;
}
References getPoint(), and TRectT< T >::x0.
getCurvature()
double TQuadratic::getCurvature (double t) const
Return curvature of quadratic at parameter t.
Calcolo della curvatura per una Quadratica. Vedi Farin pag.176 per la spiegazione della formula usata.
{
  assert(0 <= t && t <= 1.0);
  TQuadratic q1, q2;
  split(t, q1, q2);
  double signum = 1.0;
  if (areAlmostEqual(t, 1.0)) {
    signum *= -1.0;
    std::swap(q1, q2);
    std::swap(q2.m_p0, q2.m_p2);
  }
  TPointD v_1_0(q2.m_p1 - q2.m_p0);
  double a = norm2(v_1_0);
  if (isAlmostZero(a)) return (std::numeric_limits<double>::max)();
  a = 1.0 / sqrt(a);
  double b = cross(v_1_0 * a, q2.m_p2 - q2.m_p0);
  return 0.5 * signum * b / a;
}
References split().
getLength() [1/2]
double TQuadratic::getLength (double t0, double t1) const
Return length of an arc between parameters t0 t1. N.B. Length returned is always positive.
Note
t0 and t1 are clamped to [0,1] interval
if t0>=t1 returns 0
{
  TQuadraticLengthEvaluator lengthEval(*this);
  t0 = min(max(0.0, t0), 1.0);  // backward compatibility
  t1 = min(max(0.0, t1), 1.0);  // backward compatibility
  if (t0 > t1) std::swap(t0, t1);
  if (t0 > 0.0) return lengthEval.getLengthAt(t1) - lengthEval.getLengthAt(t0);
  return lengthEval.getLengthAt(t1);
}
Referenced by ToonzExt::StrokeDeformationImpl::activate_impl(), TStroke::getLength(), and TStroke::split().
getLength() [2/2]
double TQuadratic::getLength (double t1 = 1) const inline
{ return getLength(0, t1); }
getP0()
TPointD TQuadratic::getP0 () const inline
Return first control point P0.
{ return m_p0; }
Referenced by TInbetween::Imp::computeTransformation(), TStroke::getSpeed(), TStroke::getSpeedTwoValues(), TAffine::operator*(), and ControlPointEditorStroke::setStroke().
getP1()
TPointD TQuadratic::getP1 () const inline
Return second control point P1.
{ return m_p1; }
Referenced by TStroke::getSpeed(), TStroke::getSpeedTwoValues(), TAffine::operator*(), ControlPointEditorStroke::setStroke(), and TStroke::Imp::updateParameterValue().
getP2()
TPointD TQuadratic::getP2 () const inline
Return third control point P2.
{ return m_p2; }
Referenced by TStroke::getSpeed(), TStroke::getSpeedTwoValues(), TAffine::operator*(), and ControlPointEditorStroke::setStroke().
getPoint()
TPointD TQuadratic::getPoint (double t) const
Return the point of quadratic at parameter t.
{
  double s = 1 - t;
  return m_p0 * s * s + 2 * t * s * m_p1 + t * t * m_p2;
}
Referenced by PumpTool::draw(), getBBox(), and getT().
getSpeed()
TPointD TQuadratic::getSpeed (double t) const inline
Return speed of quadratic at parameter t.
{
    return 2 * ((t - 1) * m_p0 + (1.0 - 2.0 * t) * m_p1 + t * m_p2);
  }
Referenced by TStroke::getSpeed(), and TStroke::getSpeedTwoValues().
getSpeedY()
double TQuadratic::getSpeedY (double t) const inline
Return the y value of quadratic speed at parameter t.
{
    return 2 * ((t - 1) * m_p0.y + (1.0 - 2.0 * t) * m_p1.y + t * m_p2.y);
  }
getT()
double TQuadratic::getT (const TPointD & p) const
Return a parameter that correspond to the point p in the quadratic.
{
  // risolvo l'equazione  min|| b(t) - p ||
  // esprimo b in forma di polinomio  ed ottengo
  //
  //    ||  2                ||
  // min || a t + b t + c - p ||
  //    ||                   ||
  //
  // il tutto si riconduce a cercare le radici
  //  di un'equazione del tipo
  //    2  3          2               2
  // 2a t  + 3abt  + t(2av + b ) + bv
  // dove v e' pari a c - p
  vector<TPointD> bez(3), poly(3);
  bez[0] = m_p0;
  bez[1] = m_p1;
  bez[2] = m_p2;
  bezier2poly(bez, poly);
  TPointD v = poly[0] - p;
  vector<double> toSolve(4);
  vector<double> sol;
  toSolve[3] = 2.0 * norm2(poly[2]);
  toSolve[2] = 3.0 * (poly[2].x * poly[1].x + poly[2].y * poly[1].y);
  toSolve[1] = 2.0 * (poly[2].x * v.x + poly[2].y * v.y) + norm2(poly[1]);
  toSolve[0] = (poly[1].x * v.x + poly[1].y * v.y);
  int nSol = rootFinding(toSolve, sol);
  if (-1 == nSol)  // infinite soluzioni
    return 0;
  int minParameter = -1;
  double minDist   = (std::numeric_limits<double>::max)();
  for (int i = 0; i < nSol; ++i) {
    if (sol[i] < 0.0)
      sol[i] = 0.0;
    else if (sol[i] > 1.0)
      sol[i] = 1.0;
    double tmpDist = tdistance2(p, getPoint(sol[i]));
    if (tmpDist < minDist) {
      minDist      = tmpDist;
      minParameter = i;
    }
  }
  if (minParameter != -1) return sol[minParameter];
  return tdistance2(m_p0, p) < tdistance2(m_p2, p) ? 0 : 1;
}
References getPoint().
Referenced by TStroke::getNearChunks(), and TStroke::Imp::updateParameterValue().
getX() [1/2]
double TQuadratic::getX (double t) const
{
  double s = 1 - t;
  return m_p0.x * s * s + 2 * t * s * m_p1.x + t * t * m_p2.x;
}
getX() [2/2]
int TQuadratic::getX (double y, double & x0, double & x1) const
{
  int ret = 0;
  double t;
  if (y > getBBox().y1 || y < getBBox().y0) return 0;
  double a      = getP0().y - 2 * getP1().y + getP2().y;
  double half_b = getP1().y - getP0().y;
  double c      = getP0().y - y;
  if (a == 0)  // segment
  {
    if (half_b == 0)  // horizontal segment, or point
    {
      if (c == 0) {
        x0 = getP0().x;
        x1 = getP2().x;
        return 2;
      } else
        return 0;
    } else {
      t = -c / (2 * half_b);
      if (t >= 0 && t <= 1) {
        x0 = getPoint(t).x;
        return 1;
      }
    }
  }
  double discr = half_b * half_b - a * c;
  if (discr < 0) return 0;
  double coeff  = 1.0 / a;
  double coeff1 = -half_b * coeff;
  if (discr == 0) {
    t = coeff1;
    if (t >= 0 && t <= 1) {
      ret = 2;
      x0 = x1 = getPoint(t).x;
    }
  } else {
    discr = sqrt(discr) * coeff;
    t     = coeff1 + discr;
    if (t >= 0 && t <= 1) {
      ret++;
      x0 = getPoint(t).x;
    }
    t = coeff1 - discr;
    if (t >= 0 && t <= 1) {
      ret++;
      if (ret == 2)
        x1 = getPoint(t).x;
      else
        x0 = getPoint(t).x;
    }
  }
  return ret;
}
getY() [1/2]
double TQuadratic::getY (double t) const
{
  double s = 1 - t;
  return m_p0.y * s * s + 2 * t * s * m_p1.y + t * t * m_p2.y;
}
getY() [2/2]
int TQuadratic::getY (double x, double & y0, double & y1) const
{
  TQuadratic temp(*this);
  swap(temp.m_p0.x, temp.m_p0.y);
  swap(temp.m_p1.x, temp.m_p1.y);
  swap(temp.m_p2.x, temp.m_p2.y);
  return temp.getX(y, y0, y1);
}
operator!=()
bool TQuadratic::operator!= (const TQuadratic & c) const inline
{ return !operator==(c); }
operator=()
TQuadratic & TQuadratic::operator= (const TQuadratic & src) inline
{
    m_p0 = src.m_p0;
    m_p1 = src.m_p1;
    m_p2 = src.m_p2;
    return *this;
  }
operator==()
bool TQuadratic::operator== (const TQuadratic & c) const inline
{
    return m_p0 == c.m_p0 && m_p1 == c.m_p1 && m_p2 == c.m_p2;
  }
reverse()
void TQuadratic::reverse () inline
                 {
    TPointD app;
    app  = m_p0;
    m_p0 = m_p2;
    m_p2 = app;
  }
setP0()
void TQuadratic::setP0 (const TPointD & p) inline
Set the value of first control point P0 to p.
{ m_p0 = p; }
Referenced by TAffine::operator*().
setP1()
void TQuadratic::setP1 (const TPointD & p) inline
Set the value of second control point P1 to p.
{ m_p1 = p; }
Referenced by TAffine::operator*().
setP2()
void TQuadratic::setP2 (const TPointD & p) inline
Set the value of third control point P2 to p.
{ m_p2 = p; }
Referenced by TAffine::operator*().
split()
void TQuadratic::split (double t, TQuadratic & first, TQuadratic & second) const
N.B. if t==0 o t==1 return a quadratic with all points equal
{
  double dt;
  TPointD p;
  dt = 1.0 - t;
  left.m_p0  = m_p0;
  right.m_p2 = m_p2;
  left.m_p1  = dt * m_p0 + t * m_p1;
  right.m_p1 = dt * m_p1 + t * m_p2;
  p          = dt * left.m_p1 + t * right.m_p1;
  left.m_p2 = right.m_p0 = p;
}
Referenced by getCurvature().
Member Data Documentation
m_p0
TPointD TQuadratic::m_p0 protected
m_p1
TPointD TQuadratic::m_p1 protected
m_p2
TPointD TQuadratic::m_p2 protected
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/tcurves.h
E:/opentoonz/toonz/sources/common/tgeometry/tcurves.cpp