opentoonz: FxsData Class Reference
FxsData Class Reference final
Public Member Functions
FxsData * clone () const override
void setFxs (const QList< TFxP > &selectedFxs, const QList< Link > &selectedLinks, const QList< int > &columnIndexes, TXsheet *xsh)
Set the FxsData. FxsData<-QList<TFxP>
void getFxs (QList< TFxP > &selectedFxs, QMap< TFx *, int > &zeraryFxColumnSize, QList< TXshColumnP > &columns) const
Get the FxsData. FxsData->QList<TFxP>
bool isConnected () const
Return true if copied fxs makes a connected graph.
Public Member Functions inherited from DvMimeData
virtual DvMimeData * clone () const =0
virtual void releaseData ()
virtual DvMimeData * clone () const =0
Detailed Description
Constructor & Destructor Documentation
FxsData()
FxsData::FxsData ()
: m_connected(false) {}
Member Function Documentation
clone()
FxsData * FxsData::clone () const override virtual
Implements DvMimeData.
{
  FxsData *data = new FxsData;
  getFxs(data->m_fxs, data->m_zeraryFxColumnSize, data->m_columns);
  return data;
}
getFxs()
void FxsData::getFxs (QList< TFxP > & selectedFxs, QMap< TFx *, int > & zeraryFxColumnSize, QList< TXshColumnP > & columns) const
Get the FxsData. FxsData->QList<TFxP>
{
  QMap<TFx *, TFx *> clonedFxs;
  for (int i = 0; i < m_fxs.size(); i++) {
    TFx *clonedFx = m_fxs[i]->clone(false);
    TPointD pos   = m_fxs[i]->getAttributes()->getDagNodePos();
    clonedFx->getAttributes()->setDagNodePos(pos);
    clonedFx->getAttributes()->removeFromAllGroup();
    fxs.append(clonedFx);
    if (m_fxs[i]->isZerary())
      zeraryFxColumnSize[clonedFx] =
          m_zeraryFxColumnSize[m_fxs[i].getPointer()];
    clonedFxs[m_fxs[i].getPointer()] = clonedFx;
    TFx *linkedFx = m_fxs[i]->getLinkedFx();
    if (linkedFx && clonedFxs.contains(linkedFx))
      clonedFx->linkParams(clonedFxs[linkedFx]);
  }
  QList<TXshColumnP>::const_iterator it;
  for (it = m_columns.begin(); it != m_columns.end(); it++) {
    TXshColumn *col    = it->getPointer();
    TXshColumn *newCol = col->clone();
    newCol->getFx()->getAttributes()->setDagNodePos(
        col->getFx()->getAttributes()->getDagNodePos());
    columns.append(newCol);
    clonedFxs[col->getFx()] = newCol->getFx();
  }
  linkFxs(clonedFxs);
}
Referenced by FxSelection::addPasteSelection(), FxSelection::insertPasteSelection(), FxSelection::pasteSelection(), and FxSelection::replacePasteSelection().
isConnected()
bool FxsData::isConnected () const inline
Return true if copied fxs makes a connected graph.
{ return m_connected; }
Referenced by FxSelection::addPasteSelection(), FxSelection::insertPasteSelection(), and FxSelection::replacePasteSelection().
setFxs()
void FxsData::setFxs (const QList< TFxP > & selectedFxs, const QList< Link > & selectedLinks, const QList< int > & columnIndexes, TXsheet * xsh)
Set the FxsData. FxsData<-QList<TFxP>
{
  // fx->clonedFx
  QMap<TFx *, TFx *> clonedFxs;
  for (int i = 0; i < selectedFxs.size(); i++) {
    TFx *fx = selectedFxs[i].getPointer();
    if (!canCopyFx(fx)) continue;
    TZeraryColumnFx *zerayFx = dynamic_cast<TZeraryColumnFx *>(fx);
    if (zerayFx) fx          = zerayFx->getZeraryFx();
    TFx *clonedFx            = fx->clone(false);
    TPointD pos;
    if (zerayFx)
      pos = zerayFx->getAttributes()->getDagNodePos();
    else
      pos = fx->getAttributes()->getDagNodePos();
    clonedFx->getAttributes()->setDagNodePos(pos);
    m_fxs.append(clonedFx);
    if (zerayFx)
      m_zeraryFxColumnSize[clonedFx] = zerayFx->getColumn()->getRowCount();
    m_visitedFxs[clonedFx]           = false;
    clonedFxs[fx]                    = clonedFx;
    TFx *linkedFx = fx->getLinkedFx();
    if (linkedFx && clonedFxs.contains(linkedFx))
      clonedFx->linkParams(clonedFxs[linkedFx]);
  }
  QList<int>::const_iterator it;
  for (it = columnIndexes.begin(); it != columnIndexes.end(); it++) {
    TXshColumn *col    = xsh->getColumn(*it);
    TXshColumn *newCol = col->clone();
    newCol->getFx()->getAttributes()->setDagNodePos(
        col->getFx()->getAttributes()->getDagNodePos());
    m_columns.append(newCol);
    clonedFxs[col->getFx()] = newCol->getFx();
  }
  linkFxs(clonedFxs, selectedLinks);
  checkConnectivity();
}
References TXsheet::getColumn(), and TXshCellColumn::getRowCount().
Referenced by FxSelection::copySelection().
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/toonzqt/fxdata.h
E:/opentoonz/toonz/sources/toonzqt/fxdata.cpp