opentoonz: TAffine Class Reference
TAffine Class Reference
This is the base class for the affine transformations.
#include <tgeometry.h>
Public Member Functions
TAffine ()
TAffine (double p11, double p12, double p13, double p21, double p22, double p23)
TAffine (const TAffine &a)
TAffine & operator= (const TAffine &a)
TAffine operator* (const TAffine &b) const
TAffine operator*= (const TAffine &b)
TAffine inv () const
double det () const
bool operator== (const TAffine &a) const
bool operator!= (const TAffine &a) const
bool isIdentity (double err=1.e-8) const
bool isTranslation (double err=1.e-8) const
bool isIsotropic (double err=1.e-8) const
TPointD operator* (const TPointD &p) const
TRectD operator* (const TRectD &rect) const
TAffine place (double u, double v, double x, double y) const
TAffine place (const TPointD &pIn, const TPointD &pOut) const
Public Attributes
double a11
double a12
double a13
double a21
double a22
double a23
Related Functions
(Note that these are not member functions.)
TSegment operator* (const TAffine &aff, const TSegment &seg)
, TSegment
TQuadratic operator* (const TAffine &aff, const TQuadratic &curve)
, TQuadratic
TCubic operator* (const TAffine &aff, const TCubic &curve)
, TCubic
Detailed Description
This is the base class for the affine transformations.
This class performs basic manipulations of affine transformations. An affine transformation is a linear transformation followed by a translation.
[a11, a12, a13] [a21, a22, a23]
a13 and a23 represent translation (moving sideways or up and down) the other 4 handle rotation, scale and shear
Constructor & Destructor Documentation
TAffine() [1/3]
TAffine::TAffine () inline
 By default the object is initialized with a null matrix and a null
translation vector.
: a11(1.0), a12(0.0), a13(0.0), a21(0.0), a22(1.0), a23(0.0){};
Referenced by inv(), operator*(), and place().
TAffine() [2/3]
TAffine::TAffine (double p11, double p12, double p13, double p21, double p22, double p23) inline
 Initializes the internal matrix and vector of translation with the
user values.
      : a11(p11), a12(p12), a13(p13), a21(p21), a22(p22), a23(p23){};
TAffine() [3/3]
TAffine::TAffine (const TAffine & a) inline
Copy constructor.
      : a11(a.a11)
      , a12(a.a12)
      , a13(a.a13)
      , a21(a.a21)
      , a22(a.a22)
      , a23(a.a23){};
Member Function Documentation
det()
double TAffine::det () const
{ return a11 * a22 - a12 * a21; }
inv()
TAffine TAffine::inv () const
Returns the inverse tansformation as:
{
  if (a12 == 0.0 && a21 == 0.0) {
    double inv_a11 =
        (a11 == 0.0 ? std::numeric_limits<double>::max() / (1 << 16)
                    : 1.0 / a11);
    double inv_a22 =
        (a22 == 0.0 ? std::numeric_limits<double>::max() / (1 << 16)
                    : 1.0 / a22);
    return TAffine(inv_a11, 0, -a13 * inv_a11, 0, inv_a22, -a23 * inv_a22);
  } else if (a11 == 0.0 && a22 == 0.0) {
    assert(a12 != 0.0);
    assert(a21 != 0.0);
    double inv_a21 =
        (a21 == 0.0 ? std::numeric_limits<double>::max() / (1 << 16)
                    : 1.0 / a21);
    double inv_a12 =
        (a12 == 0.0 ? std::numeric_limits<double>::max() / (1 << 16)
                    : 1.0 / a12);
    return TAffine(0, inv_a21, -a23 * inv_a21, inv_a12, 0, -a13 * inv_a12);
  } else {
    double d = 1. / det();
    return TAffine(a22 * d, -a12 * d, (a12 * a23 - a22 * a13) * d, -a21 * d,
                   a11 * d, (a21 * a13 - a11 * a23) * d);
  }
}
References TAffine().
Referenced by StageBuilder::addCell(), TInbetween::Imp::computeTransformation(), PlasticDeformerFx::doDryCompute(), EditTool::draw(), SkeletonTool::draw(), RotateTool::draw(), SceneViewer::getGeometry(), texture_utils::getTextureData(), SceneViewer::getViewMatrix(), Stage::Picker::onImage(), TStageObject::perspective(), ColorModelViewer::pick(), TCleanupper::process(), and ToonzScene::renderFrame().
isIdentity()
bool TAffine::isIdentity (double err = 1.e-8) const
Returns true if the transformation is an identity, i.e in the error limit err leaves the vectors unchanged.
{
  return ((a11 - 1.0) * (a11 - 1.0) + (a22 - 1.0) * (a22 - 1.0) + a12 * a12 +
          a13 * a13 + a21 * a21 + a23 * a23) < err;
}
Referenced by TRop::over(), and ShiftTraceToolOptionBox::updateStatus().
isIsotropic()
bool TAffine::isIsotropic (double err = 1.e-8) const
 Returns \e true if in the error limits the matrix \f$\bf{A}\f$ is of
the form:
.
{
  return areAlmostEqual(a11, a22, err) && areAlmostEqual(a12, -a21, err);
}
isTranslation()
bool TAffine::isTranslation (double err = 1.e-8) const
 Returns \e true if in the error limits \e err \f$\bf{A}\f$ is the
identity matrix.
{
  return ((a11 - 1.0) * (a11 - 1.0) + (a22 - 1.0) * (a22 - 1.0) + a12 * a12 +
          a21 * a21) < err;
}
operator!=()
bool TAffine::operator!= (const TAffine & a) const
Returns true if at least one element is different.
{
  return a11 != a.a11 || a12 != a.a12 || a13 != a.a13 || a21 != a.a21 ||
         a22 != a.a22 || a23 != a.a23;
}
operator*() [1/3]
TAffine TAffine::operator* (const TAffine & b) const
Matrix multiplication.
{
  return TAffine(a11 * b.a11 + a12 * b.a21, a11 * b.a12 + a12 * b.a22,
                 a11 * b.a13 + a12 * b.a23 + a13,
                 a21 * b.a11 + a22 * b.a21, a21 * b.a12 + a22 * b.a22,
                 a21 * b.a13 + a22 * b.a23 + a23);
}
References TAffine().
operator*() [2/3]
TPointD TAffine::operator* (const TPointD & p) const
Returns the transformed point.
{
  return TPointD(p.x * a11 + p.y * a12 + a13, p.x * a21 + p.y * a22 + a23);
}
operator*() [3/3]
TRectD TAffine::operator* (const TRectD & rect) const
Returns the transformed box of the bounding box.
{
  if (rect != TConsts::infiniteRectD) {
    TPointD p1 = *this * rect.getP00(), p2 = *this * rect.getP01(),
            p3 = *this * rect.getP10(), p4 = *this * rect.getP11();
    return TRectD(
        std::min({p1.x, p2.x, p3.x, p4.x}), std::min({p1.y, p2.y, p3.y, p4.y}),
        std::max({p1.x, p2.x, p3.x, p4.x}), std::max({p1.y, p2.y, p3.y, p4.y}));
  } else
    return TConsts::infiniteRectD;
}
operator*=()
TAffine TAffine::operator*= (const TAffine & b)
{ return *this = *this * b; }
operator=()
TAffine & TAffine::operator= (const TAffine & a)
Assignment operator.
{
  a11 = a.a11;
  a12 = a.a12;
  a13 = a.a13;
  a21 = a.a21;
  a22 = a.a22;
  a23 = a.a23;
  return *this;
}
operator==()
bool TAffine::operator== (const TAffine & a) const
Returns true if all elements are equals.
{
  return a11 == a.a11 && a12 == a.a12 && a13 == a.a13 && a21 == a.a21 &&
         a22 == a.a22 && a23 == a.a23;
}
place() [1/2]
TAffine TAffine::place (const TPointD & pIn, const TPointD & pOut) const
See above.
{
  return TAffine(a11, a12, pOut.x - (a11 * pIn.x + a12 * pIn.y), a21, a22,
                 pOut.y - (a21 * pIn.x + a22 * pIn.y));
}
References TAffine().
place() [2/2]
TAffine TAffine::place (double u, double v, double x, double y) const
    Returns a translated matrix that change the vector (u,v) in (x,y).
It returns a matrix of the form:
{
  return TAffine(a11, a12, x - (a11 * u + a12 * v), a21, a22,
                 y - (a21 * u + a22 * v));
}
References TAffine().
Referenced by TRasterImage::makeIcon().
Friends And Related Function Documentation
operator*() [1/3]
TCubic operator* (const TAffine & aff, const TCubic & curve) related
, TCubic
{
  TCubic out;
  out.setP0(aff * curve.getP0());
  out.setP1(aff * curve.getP1());
  out.setP2(aff * curve.getP2());
  out.setP3(aff * curve.getP3());
  return out;
}
References TCubic::getP0(), TCubic::getP1(), TCubic::getP2(), TCubic::getP3(), TCubic::setP0(), TCubic::setP1(), TCubic::setP2(), and TCubic::setP3().
operator*() [2/3]
TQuadratic operator* (const TAffine & aff, const TQuadratic & curve) related
, TQuadratic
{
  TQuadratic quad;
  quad.setP0(aff * curve.getP0());
  quad.setP1(aff * curve.getP1());
  quad.setP2(aff * curve.getP2());
  return quad;
}
References TQuadratic::getP0(), TQuadratic::getP1(), TQuadratic::getP2(), TQuadratic::setP0(), TQuadratic::setP1(), and TQuadratic::setP2().
operator*() [3/3]
TSegment operator* (const TAffine & aff, const TSegment & seg) related
, TSegment
{
  return TSegment(aff * seg.getP0(), aff * seg.getP1());
}
References TSegment::getP0(), and TSegment::getP1().
Member Data Documentation
a11
double TAffine::a11
a12
double TAffine::a12
a13
double TAffine::a13
a21
double TAffine::a21
a22
double TAffine::a22
a23
double TAffine::a23
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/tgeometry.h
E:/opentoonz/toonz/sources/common/tgeometry/tgeometry.cpp
E:/opentoonz/toonz/sources/include/tcurves.h