opentoonz: TStrokePointDeformation Class Reference
TStrokePointDeformation Class Reference final
#include <tstrokedeformations.h>
Classes
struct Imp
Public Member Functions
TStrokePointDeformation (const TPointD &center=TPointD(), double radius=40.0)
TStrokePointDeformation (const TPointD &vect, const TPointD &center=TPointD(), double radius=40.0)
TThickPoint getDisplacement (const TStroke &stroke, double s) const override
TThickPoint getDisplacementForControlPoint (const TStroke &s, UINT n) const override
TThickPoint getDisplacementForControlPointLen (const TStroke &stroke, double cpLen) const override
double getDelta (const TStroke &stroke, double w) const override
double getMaxDiff () const override
virtual TThickPoint getDisplacement (const TStroke &stroke, double w) const =0
virtual TThickPoint getDisplacementForControlPoint (const TStroke &stroke, UINT n) const =0
virtual TThickPoint getDisplacementForControlPointLen (const TStroke &stroke, double cpLen) const =0
virtual double getDelta (const TStroke &stroke, double w) const =0
virtual double getMaxDiff () const =0
Protected Attributes
std::unique_ptr< Imp > m_imp
Detailed Description
Manage the manipulation of a stroke using the metaball.
Every tools have a constructor like:
const TStroke *pStroke const TPointD &vect ... list of parameter.
Constructor & Destructor Documentation
TStrokePointDeformation() [1/2]
TStrokePointDeformation::TStrokePointDeformation (const TPointD & center = TPointD(), double radius = 40.0)
Use this constructor with increasePoints.
    : m_imp(new Imp(center, radius)) {}
TStrokePointDeformation() [2/2]
TStrokePointDeformation::TStrokePointDeformation (const TPointD & vect, const TPointD & center = TPointD(), double radius = 40.0)
Use this constructor with modifyControlPoints.
    : m_imp(new Imp(vect, center, radius)) {}
~TStrokePointDeformation()
TStrokePointDeformation::~TStrokePointDeformation () virtual
{}
Member Function Documentation
getDelta()
double TStrokePointDeformation::getDelta (const TStroke & stroke, double w) const override virtual
| d getDisplacement() / dw |
stroke to test
w stroke parameter
\ret | d getDisplacement() / dw |
Implements TStrokeDeformation.
{
  // reference to a thickpoint
  TThickPoint thickPnt = m_imp->m_vect ? stroke.getControlPointAtParameter(w)
                                       : stroke.getThickPoint(w);
  assert(thickPnt != TConsts::natp);
  TPointD pntOfStroke = convert(thickPnt);
  double d = tdistance(pntOfStroke, m_imp->m_circleCenter);
  return m_imp->m_potential->gradient(d);
}
References TStroke::getControlPointAtParameter(), and TStroke::getThickPoint().
getDisplacement()
TThickPoint TStrokePointDeformation::getDisplacement (const TStroke & stroke, double w) const override virtual
return displacement to use with function increaseControlPoints
stroke to test
w stroke parameter
\ret displacement to apply to obtain deformation
See also
increaseControlPoints
Implements TStrokeDeformation.
{
  // riferimento ad un punto ciccione della stroke
  TThickPoint thickPnt = m_imp->m_vect ? stroke.getControlPointAtParameter(w)
                                       : stroke.getThickPoint(w);
  assert(thickPnt != TConsts::natp);
  TPointD pntOfStroke(convert(thickPnt));
  double d = tdistance(pntOfStroke, m_imp->m_circleCenter);
  if (m_imp->m_vect)
    return m_imp->m_potential->value(d) * TThickPoint(*m_imp->m_vect, 0);
  else {
    double outVal = m_imp->m_potential->value(d);
    return TThickPoint(outVal, outVal, 0);
  }
}
References TStroke::getControlPointAtParameter(), and TStroke::getThickPoint().
getDisplacementForControlPoint()
TThickPoint TStrokePointDeformation::getDisplacementForControlPoint (const TStroke & stroke, UINT n) const override virtual
return displacement to use with function modifyControlPoints
stroke to test
n control point to get
\ret displacement to apply to obtain deformation
See also
modifyControlPoints
Implements TStrokeDeformation.
{
  // riferimento ad un punto ciccione della stroke
  TPointD pntOfStroke(convert(stroke.getControlPoint(n)));
  double d = tdistance(pntOfStroke, m_imp->m_circleCenter);
  if (m_imp->m_vect)
    return m_imp->m_potential->value(d) * TThickPoint(*m_imp->m_vect, 0);
  else {
    double outVal = m_imp->m_potential->value(d);
    return TThickPoint(outVal, outVal, 0);
  }
}
References TStroke::getControlPoint().
getDisplacementForControlPointLen()
TThickPoint TStrokePointDeformation::getDisplacementForControlPointLen (const TStroke & stroke, double cpLen) const override virtual
Implements TStrokeDeformation.
{
  assert(0);
  return TThickPoint();
}
getMaxDiff()
double TStrokePointDeformation::getMaxDiff () const override virtual
Max diff of delta (This value indicates when it's necessary to insert control point) \ret max displacement permitted
Implements TStrokeDeformation.
{ return 0.005; }
Member Data Documentation
m_imp
std::unique_ptr<Imp> TStrokePointDeformation::m_imp protected
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/tstrokedeformations.h
E:/opentoonz/toonz/sources/common/tvrender/tstrokedeformations.cpp