opentoonz: TStageObjectId Class Reference
TStageObjectId Class Reference
#include <tstageobjectid.h>
Public Member Functions
bool operator!= (const TStageObjectId &p) const
bool operator== (const TStageObjectId &p) const
bool operator< (const TStageObjectId &p) const
bool operator> (const TStageObjectId &p) const
bool operator<= (const TStageObjectId &p) const
bool operator>= (const TStageObjectId &p) const
std::string toString () const
int getIndex () const
bool isCamera () const
bool isTable () const
bool isPegbar () const
bool isColumn () const
bool isSpline () const
Code getCode () const
void setCode (Code id)
Static Public Member Functions
static const TStageObjectId CameraId (int index)
static const TStageObjectId PegbarId (int index)
static const TStageObjectId ColumnId (int index)
static const TStageObjectId SplineId (int index)
Static Public Attributes
static const TStageObjectId NoneId
static const TStageObjectId TableId
Detailed Description
The class TStageObjectId permits the specialization of a generic stage object.
The possible type of a stage object are: table TableId, camera CameraId, pegbar PegbarId, column ColumnId and spline SplineId; the class allows to know object type: isCamera(), isTable(), isPegbar(), isColumn() and isSpline().
For each specialization you give to each stage object a sequential number. The class provides methods to get sequential number getIndex() and objectId name toString(). It's possible to compare different stage object using defined operator, operator==(), operator!=(), operator<(), operator<=(), operator>() and operator>=().
Constructor & Destructor Documentation
TStageObjectId()
TStageObjectId::TStageObjectId ()
: m_id(NONE << StageObjectTypeShift) {}
~TStageObjectId()
TStageObjectId::~TStageObjectId ()
{}
Member Function Documentation
CameraId()
const TStageObjectId TStageObjectId::CameraId (int index) static
{
  assert(0 <= index && index <= StageObjectMaxIndex);
  return TStageObjectId(CAMERA << StageObjectTypeShift | index);
}
ColumnId()
const TStageObjectId TStageObjectId::ColumnId (int index) static
{
  assert(0 <= index && index <= StageObjectMaxIndex);
  return TStageObjectId(COLUMN << StageObjectTypeShift | index);
}
getCode()
Code TStageObjectId::getCode () const inline
{ return m_id; }
getIndex()
int TStageObjectId::getIndex () const
{ return m_id & StageObjectIndexMask; }
isCamera()
bool TStageObjectId::isCamera () const
Return true if this TStageObjectId is CameraId; otherwise return false.
See also
isTable(), isPegbar(), isColumn() and isSpline().
{
  return m_id >> StageObjectTypeShift == CAMERA;
}
Referenced by TStageObject::clone(), EditTool::draw(), TStageObjectTree::getCamera(), and TStageObject::setParent().
isColumn()
bool TStageObjectId::isColumn () const
Return true if this TStageObjectId is column; otherwise return false.
See also
isCamera(), isTable(), isPegbar() and isSpline()
{
  return m_id >> StageObjectTypeShift == COLUMN;
}
Referenced by StageBuilder::addCell(), StageBuilder::addCellWithOnionSkin(), TStageObject::clone(), EditTool::draw(), SkeletonTool::draw(), TStageObject::getFullName(), TStageObjectTree::saveData(), and TStageObject::setParent().
isPegbar()
bool TStageObjectId::isPegbar () const
Return true if this TStageObjectId is pegbar; otherwise return false.
See also
isCamera(), isTable(), isColumn() and isSpline()
{
  return m_id >> StageObjectTypeShift == PEGBAR;
}
Referenced by TStageObject::clone(), EditTool::draw(), StageSchematicNodePort::linkTo(), and TStageObject::setParent().
isSpline()
bool TStageObjectId::isSpline () const
Return true if this TStageObjectId is spline; otherwise return false.
See also
isCamera(), isTable(), isPegbar() and isColumn()
isTable()
bool TStageObjectId::isTable () const
Return true if this TStageObjectId is table; otherwise return false.
See also
isCamera(), isPegbar(), isColumn() and isSpline()
{
  return m_id >> StageObjectTypeShift == TABLE;
}
Referenced by EditTool::draw(), StageSchematicNodePort::linkTo(), and TStageObject::setParent().
operator!=()
bool TStageObjectId::operator!= (const TStageObjectId & p) const inline
Return true if this TStageObjectId and the given p have different identification; otherwise return false.
{
    return m_id != p.m_id;
  }
operator<()
bool TStageObjectId::operator< (const TStageObjectId & p) const inline
Return true if this TStageObjectId identification is smaller than p identification; otherwise return false.
{ return m_id < p.m_id; }
operator<=()
bool TStageObjectId::operator<= (const TStageObjectId & p) const inline
Return true if this TStageObjectId identification is equal or smaller than p identification; otherwise return false.
{
    return m_id <= p.m_id;
  }
operator==()
bool TStageObjectId::operator== (const TStageObjectId & p) const inline
Return true if this TStageObjectId and the given p have the same identification; otherwise return false.
{
    return m_id == p.m_id;
  }
operator>()
bool TStageObjectId::operator> (const TStageObjectId & p) const inline
Return true if this TStageObjectId identification is greater than p identification; otherwise return false.
{ return m_id > p.m_id; }
operator>=()
bool TStageObjectId::operator>= (const TStageObjectId & p) const inline
Return true if this TStageObjectId identification is equal or greater than p identification; otherwise return false.
{
    return m_id >= p.m_id;
  }
PegbarId()
const TStageObjectId TStageObjectId::PegbarId (int index) static
{
  assert(0 <= index && index <= StageObjectMaxIndex);
  return TStageObjectId(PEGBAR << StageObjectTypeShift | index);
}
setCode()
void TStageObjectId::setCode (Code id) inline
{ m_id = id; }
toString()
string TStageObjectId::toString () const
Return std::string with this TStageObjectId short name.
{
  int index = m_id & StageObjectIndexMask;
  string shortName;
  switch (m_id >> StageObjectTypeShift) {
  case NONE:
    shortName = "None";
    break;
  case CAMERA:
    shortName = "Camera" + std::to_string(index + 1);
    break;
  case TABLE:
    shortName = "Table";
    break;
  case PEGBAR:
    shortName = "Peg" + std::to_string(index + 1);
    break;
  case COLUMN:
    shortName = "Col" + std::to_string(index + 1);
    break;
  default:
    shortName = "BadPegbar";
  }
  return shortName;
}
Referenced by TStageObjectTree::saveData().
Member Data Documentation
NoneId
const TStageObjectId TStageObjectId::NoneId static
TableId
const TStageObjectId TStageObjectId::TableId static
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/toonz/tstageobjectid.h
E:/opentoonz/toonz/sources/toonzlib/tstageobject.cpp