opentoonz: TXshSoundColumn Class Reference
TXshSoundColumn Class Reference final
#include <txshsoundcolumn.h>
Public Member Functions
TXshColumn::ColumnType getColumnType () const override
TXshSoundColumn * getSoundColumn () override
bool canSetCell (const TXshCell &cell) const override
TXshColumn * clone () const override
void assignLevels (const TXshSoundColumn *src)
void loadData (TIStream &is) override
void saveData (TOStream &os) override
int getRange (int &r0, int &r1) const override
int getRowCount () const override
int getMaxFrame () const override
int getFirstRow () const override
const TXshCell & getCell (int row) const override
TXshCell getSoundCell (int row)
void getCells (int row, int rowCount, TXshCell cells[]) override
bool setCell (int row, const TXshCell &cell) override
bool setCells (int row, int rowCount, const TXshCell cells[]) override
void insertEmptyCells (int row, int rowCount) override
void clearCells (int row, int rowCount) override
void removeCells (int row, int rowCount) override
void updateCells (int row, int rowCount)
int modifyCellRange (int row, int delta, bool modifyStartValue)
bool isCellEmpty (int row) const override
bool getLevelRange (int row, int &r0, int &r1) const override
bool getLevelRangeWithoutOffset (int row, int &r0, int &r1) const
void checkColumn () const override
void setXsheet (TXsheet *xsheet) override
void setFrameRate (double fps)
void updateFrameRate (double fps)
void setVolume (double value)
From 0.0 to 1.0.
double getVolume () const
TSoundTrackP getCurrentPlaySoundTruck ()
void play (TSoundTrackP soundtrack, int s0, int s1, bool loop)
s0 and s1 are samples
void play (ColumnLevel *ss, int currentFrame)
void play (int currentFrame=0)
void stop ()
bool isPlaying () const
void scrub (int fromFrame, int toFrame)
TSoundTrackP getOverallSoundTrack (int fromFrame=-1, int toFram=-1, double fps=-1, TSoundTrackFormat format=TSoundTrackFormat())
TSoundTrackP mixingTogether (const std::vector< TXshSoundColumn * > &vect, int fromFrame=-1, int toFram=-1, double fps=-1)
Public Member Functions inherited from TXshCellColumn
TXshCellColumn ()
~TXshCellColumn ()
TXshCellColumn * getCellColumn () override
virtual bool canSetCell (const TXshCell &cell) const =0
int getRange (int &r0, int &r1) const override
virtual int getRowCount () const
bool isEmpty () const override
bool isCellEmpty (int row) const override
virtual const TXshCell & getCell (int row) const
virtual bool setCell (int row, const TXshCell &cell)
virtual void getCells (int row, int rowCount, TXshCell cells[])
virtual bool setCells (int row, int rowCount, const TXshCell cells[])
virtual void insertEmptyCells (int row, int rowCount=1)
virtual void removeCells (int row, int rowCount=1)
virtual void clearCells (int row, int rowCount=1)
int getMaxFrame () const override
virtual int getFirstRow () const
virtual void checkColumn () const
bool getLevelRange (int row, int &r0, int &r1) const override
void saveCellMarks (TOStream &os)
bool loadCellMarks (std::string tagName, TIStream &is)
void setCellMark (int frame, int id)
int getCellMark (int frame) const
QMap< int, int > getCellMarks () const
void clearCellMarks ()
Public Member Functions inherited from TXshColumn
TXshColumn ()
virtual ColumnType getColumnType () const =0
virtual TXshLevelColumn * getLevelColumn ()
virtual TXshSoundColumn * getSoundColumn ()
virtual TXshSoundTextColumn * getSoundTextColumn ()
virtual TXshCellColumn * getCellColumn ()
virtual TXshPaletteColumn * getPaletteColumn ()
virtual TXshZeraryFxColumn * getZeraryFxColumn ()
virtual TXshMeshColumn * getMeshColumn ()
virtual int getMaxFrame () const =0
virtual TXshColumn * clone () const =0
bool isCamstandVisible () const
void setCamstandVisible (bool on)
UCHAR getOpacity () const
void setOpacity (UCHAR val)
bool isPreviewVisible () const
void setPreviewVisible (bool on)
bool isLocked () const
void lock (bool on)
bool isMask () const
void setIsMask (bool on)
virtual bool isEmpty () const
virtual TRaster32P getIcon ()
virtual bool isCellEmpty (int row) const =0
virtual bool getLevelRange (int row, int &r0, int &r1) const =0
virtual int getRange (int &r0, int &r1) const
virtual void setXsheet (TXsheet *xsheet)
TXsheet * getXsheet () const
virtual TFx * getFx () const
virtual bool isRendered () const
virtual bool isControl () const
int getColorTag () const
void setColorTag (int colorTag)
FilterColor getFilterColorId () const
void setFilterColorId (FilterColor id)
TPixel32 getFilterColor ()
void resetColumnProperties ()
Public Member Functions inherited from TColumnHeader
int getIndex () const
int getPos () const
int getX0 () const
int getX1 () const
void getCoords (int &x0, int &x1) const
int getWidth () const
bool inColumnsSet () const
Public Member Functions inherited from TSmartObject
TSmartObject (ClassCode classCode)
void addRef ()
void release ()
TINT32 getRefCount () const
Public Member Functions inherited from TPersist
virtual void loadData (TIStream &is)=0
virtual void saveData (TOStream &os)=0
std::string getStreamTag () const
virtual const TPersistDeclaration * getDeclaration () const =0
Protected Slots
void onTimerOut ()
Protected Member Functions
bool setCell (int row, const TXshCell &cell, bool updateSequence)
void removeCells (int row, int rowCount, bool shift)
void setCellInEmptyFrame (int row, const TXshCell &cell)
void insertColumnLevel (ColumnLevel *columnLevel, int index=-1)
void removeColumnLevel (ColumnLevel *columnLevel)
ColumnLevel * getColumnLevelByFrame (int frame) const
ColumnLevel * getColumnLevel (int index)
int getColumnLevelIndex (ColumnLevel *ss) const
void clear ()
Protected Member Functions inherited from TXshColumn
void setStatusWord (int status)
int getStatusWord () const
Additional Inherited Members
Public Types inherited from TXshColumn
enum FilterColor {
FilterNone = 0 , FilterRed , FilterGreen , FilterBlue ,
FilterDarkYellow , FilterDarkCyan , FilterDarkMagenta , FilterAmount
}
enum ColumnType {
eLevelType = 0 , eSoundType , eSoundTextType , eZeraryFxType ,
ePaletteType , eMeshType
}
Public Types inherited from TSmartObject
typedef short ClassCode
Public Types inherited from TPersist
typedef TPersist * CreateProc()
Static Public Member Functions inherited from TXshColumn
static ColumnType toColumnType (int levelType)
Returns the column type used to store levels of the specified type.
static TXshColumn * createEmpty (int colType)
Creates an empty TXshColumn of the specified column type.
static QPair< QString, TPixel32 > getFilterInfo (FilterColor key)
static void initColorFilters ()
Static Public Member Functions inherited from TSmartObject
static TINT32 getInstanceCount (ClassCode code)
Static Public Member Functions inherited from TPersist
static void declare (CreateProc *)
static TPersist * create (const std::string &name)
Protected Types inherited from TXshColumn
enum {
eCamstandVisible = 0x1 , ePreviewVisible = 0x2 , eLocked = 0x8 , eMasked = 0x10 ,
eCamstandTransparent43 = 0x20
}
Protected Attributes inherited from TXshCellColumn
std::vector< TXshCell > m_cells
int m_first
QMap< int, int > m_cellMarkIds
Protected Attributes inherited from TXshColumn
TRaster32P m_icon
Detailed Description
The TXshSoundColumn class provides a sound column in xsheet and allows its management through cell concept.
Inherits TXshCellColumn.
Constructor & Destructor Documentation
TXshSoundColumn()
TXshSoundColumn::TXshSoundColumn ()
    : m_player(0)
    , m_volume(0.4)
    , m_currentPlaySoundTrack(0)
    , m_isOldVersion(false) {
  m_timer.setInterval(500);
  m_timer.setSingleShot(true);
  m_timer.stop();
  connect(&m_timer, SIGNAL(timeout()), this, SLOT(onTimerOut()));
}
~TXshSoundColumn()
TXshSoundColumn::~TXshSoundColumn ()
{
  clear();
  if (m_timer.isActive()) {
    m_timer.stop();
    stop();
  }
}
Member Function Documentation
assignLevels()
void TXshSoundColumn::assignLevels (const TXshSoundColumn * src)
Clear column and set src level.
{
  // Svuoto la lista dei livelli
  clear();
  int r;
  for (r = src->getFirstRow(); r <= src->getMaxFrame(); r++) {
    int r0, r1;
    if (!src->getLevelRange(r, r0, r1)) continue;
    TXshCell cell = src->getCell(r);
    if (cell.isEmpty()) continue;
    TXshSoundLevel *soundLevel = cell.m_level->getSoundLevel();
    assert(!!soundLevel);
    int startOffset = cell.getFrameId().getNumber();
    int startFrame  = r - startOffset;
    int endOffset   = startFrame + soundLevel->getFrameCount() - r1 - 1;
    ColumnLevel *l =
        new ColumnLevel(soundLevel, startFrame, startOffset, endOffset);
    insertColumnLevel(l);
    r = r1;
  }
}
References getCell(), getFirstRow(), TXshCell::getFrameId(), getLevelRange(), getMaxFrame(), TXshLevel::getSoundLevel(), insertColumnLevel(), and TXshCell::isEmpty().
canSetCell()
bool TXshSoundColumn::canSetCell (const TXshCell & cell) const override virtual
Implements TXshCellColumn.
{
  return cell.isEmpty() || cell.m_level->getSoundLevel() != 0;
}
checkColumn()
void TXshSoundColumn::checkColumn () const override virtual
Only debug.
Reimplemented from TXshCellColumn.
{
#ifndef NDEBUG
  int size = m_levels.size();
  int i;
  for (i = 0; i < size; i++) {
    ColumnLevel *level = m_levels.at(i);
    assert(level);
    assert(level->getSoundLevel());
    int start1 = level->getVisibleStartFrame();
    int end1   = level->getVisibleEndFrame();
    assert(start1 <= end1);
    if (i < size - 1) {
      ColumnLevel *nextLevel = m_levels.at(i + 1);
      assert(nextLevel);
      assert(nextLevel->getSoundLevel());
      int start2 = nextLevel->getVisibleStartFrame();
      int end2   = nextLevel->getVisibleEndFrame();
      assert(start2 <= end2);
      assert(end1 < start2);
    }
  }
#endif
}
References ColumnLevel::getSoundLevel(), ColumnLevel::getVisibleEndFrame(), and ColumnLevel::getVisibleStartFrame().
Referenced by getCells(), insertEmptyCells(), and modifyCellRange().
clear()
void TXshSoundColumn::clear () protected
{
  int sequenceCount = m_levels.size();
  for (int i = 0; i < sequenceCount; i++) {
    ColumnLevel *s = m_levels[i];
    delete s;
  }
  m_levels.clear();
}
clearCells()
void TXshSoundColumn::clearCells (int row, int rowCount) override virtual
Clear rowCount cells from line row, without shift.
Reimplemented from TXshCellColumn.
{
  if (rowCount <= 0) return;
  if (m_levels.isEmpty())
    return;  // se la colonna e' vuota non devo "sbiancare" celle
  removeCells(row, rowCount, false);
}
References removeCells().
clone()
TXshColumn * TXshSoundColumn::clone () const override virtual
Implements TXshColumn.
{
  TXshSoundColumn *column = new TXshSoundColumn();
  column->setVolume(m_volume);
  column->setXsheet(getXsheet());
  int i;
  for (i = 0; i < m_levels.size(); i++)
    column->insertColumnLevel(m_levels.at(i)->clone(), i);
  return column;
}
getCell()
const TXshCell & TXshSoundColumn::getCell (int row) const override virtual
Return cell in row.
See also
getCells and setCell()
Reimplemented from TXshCellColumn.
{
  static TXshCell emptyCell;
  ColumnLevel *l = getColumnLevelByFrame(row);
  if (row < 0 || row < getFirstRow() || row > getMaxFrame()) {
    if (l) emptyCell.m_level = l->getSoundLevel();
    return emptyCell;
  }
  if (!l) return emptyCell;
  TXshSoundLevel *soundLevel = l->getSoundLevel();
  TXshCell *cell = new TXshCell(soundLevel, TFrameId(row - l->getStartFrame()));
  // The new cell adds a reference to the TXshSoundLevel;
  // since the cells of the TXshSoundColumn are not persistent structures
  // but are dynamic structures (they are recreated every time) I have to take
  // care of making the release otherwise the TXshSoundLevel is never thrown
  // away.
  soundLevel->release();
  return *cell;
}
References getFirstRow(), getMaxFrame(), and ColumnLevel::getSoundLevel().
Referenced by assignLevels(), getCells(), and updateCells().
getCells()
void TXshSoundColumn::getCells (int row, int rowCount, TXshCell cells[]) override virtual
Set cells[] from row to row + rowCount to column cells.
See also
getCell and setCells()
Reimplemented from TXshCellColumn.
{
  // le celle da settare sono [ra, rb]
  int ra = row;
  int rb = row + rowCount - 1;
  assert(ra <= rb);
  TXshCell *dstCell = cells;
  int r;
  for (r = ra; r <= rb; r++) *cells++ = getCell(r);
  checkColumn();
}
References checkColumn(), and getCell().
getColumnLevel()
ColumnLevel * TXshSoundColumn::getColumnLevel (int index) protected
{
  if (index < 0 || index >= m_levels.count()) return 0;
  return m_levels.at(index);
}
getColumnLevelByFrame()
ColumnLevel * TXshSoundColumn::getColumnLevelByFrame (int frame) const protected
{
  int levelCount = m_levels.size();
  for (int i = 0; i < levelCount; i++) {
    ColumnLevel *l             = m_levels.at(i);
    TXshSoundLevel *soundLevel = l->getSoundLevel();
    int startFrame             = l->getStartFrame() + l->getStartOffset();
    int frameCount =
        soundLevel->getFrameCount() - l->getStartOffset() - l->getEndOffset();
    if (startFrame <= frame && startFrame + frameCount > frame) return l;
  }
  return 0;
}
getColumnLevelIndex()
int TXshSoundColumn::getColumnLevelIndex (ColumnLevel * ss) const protected
{
  return m_levels.indexOf(columnLevel);
}
getColumnType()
TXshColumn::ColumnType TXshSoundColumn::getColumnType () const override virtual
Implements TXshColumn.
{
  return eSoundType;
}
getCurrentPlaySoundTruck()
TSoundTrackP TXshSoundColumn::getCurrentPlaySoundTruck () inline
{ return m_currentPlaySoundTrack; }
getFirstRow()
int TXshSoundColumn::getFirstRow () const override virtual
Return min row not empty.
Reimplemented from TXshCellColumn.
{
  if (m_levels.size() == 0) return -1;
  return m_levels.at(0)->getVisibleStartFrame();
}
Referenced by assignLevels(), getCell(), getRange(), and getRowCount().
getLevelRange()
bool TXshSoundColumn::getLevelRange (int row, int & r0, int & r1) const override virtual
r0 : min row not empty of level in row, r1 : max row not empty of level in row. Return true if level range is not empty.
Reimplemented from TXshCellColumn.
{
  ColumnLevel *l = getColumnLevelByFrame(row);
  if (!l) {
    r0 = r1 = row;
    return false;
  }
  r0 = l->getVisibleStartFrame();
  r1 = l->getVisibleEndFrame();
  return true;
}
References ColumnLevel::getVisibleEndFrame(), and ColumnLevel::getVisibleStartFrame().
Referenced by assignLevels().
getLevelRangeWithoutOffset()
bool TXshSoundColumn::getLevelRangeWithoutOffset (int row, int & r0, int & r1) const
r0 : min possible (without offset) row of level in row, r1 : max possible (without offset) row of level in row. Return true if level range is not empty.
{
  ColumnLevel *l = getColumnLevelByFrame(row);
  if (!l) {
    r0 = r1 = row;
    return false;
  }
  r0 = l->getStartFrame();
  r1 = l->getEndFrame();
  return true;
}
References ColumnLevel::getEndFrame().
getMaxFrame()
int TXshSoundColumn::getMaxFrame () const override virtual
Return max row not empty.
Reimplemented from TXshCellColumn.
{
  int levelsCount = m_levels.size();
  if (levelsCount == 0) return -1;
  return m_levels.at(levelsCount - 1)->getVisibleEndFrame();
}
Referenced by assignLevels(), getCell(), getRange(), and getRowCount().
getOverallSoundTrack()
TSoundTrackP TXshSoundColumn::getOverallSoundTrack (int fromFrame = -1, int toFram = -1, double fps = -1, TSoundTrackFormat format = TSoundTrackFormat())
{
  int levelsCount = m_levels.size();
  if (levelsCount == 0) return 0;
  if (fps == -1) fps = m_levels[0]->getSoundLevel()->getFrameRate();
  if (fromFrame == -1) fromFrame = getFirstRow();
  if (toFrame == -1) toFrame = getMaxFrame();
  if (format.m_sampleRate == 0) {
    // Find the best format inside the soundsequences
    int sampleRate    = 0;
    int bitsPerSample = 8;
    int channels      = 1;
    for (int i = 0; i < levelsCount; i++) {
      TXshSoundLevel *soundLevel = m_levels.at(i)->getSoundLevel();
      TSoundTrackP soundTrack    = soundLevel->getSoundTrack();
      if (soundTrack.getPointer() == 0) continue;
      TSoundTrackFormat f = soundTrack->getFormat();
      if ((int)f.m_sampleRate > sampleRate) {
        format.m_sampleRate   = f.m_sampleRate;
        sampleRate            = f.m_sampleRate;
        format.m_channelCount = f.m_channelCount;
        channels              = f.m_channelCount;
        format.m_signedSample = f.m_signedSample;
        format.m_bitPerSample = f.m_bitPerSample;
        bitsPerSample         = f.m_bitPerSample;
      }
      if (f.m_channelCount > channels) {
        format.m_channelCount = f.m_channelCount;
        channels              = f.m_channelCount;
      }
      if (f.m_bitPerSample > bitsPerSample) {
        format.m_bitPerSample = f.m_bitPerSample;
        bitsPerSample         = f.m_bitPerSample;
      }
    }
  }
  // If there is no soundSequence I use a default format
  if (levelsCount == 0 || format.m_sampleRate == 0) {
    format.m_sampleRate   = 44100;
    format.m_bitPerSample = 16;
    format.m_channelCount = 1;
    format.m_signedSample = true;
  }
#ifdef _WIN32
  if (format.m_sampleRate > 44100) format.m_sampleRate = 44100;
#else
  QAudioDeviceInfo info(QAudioDeviceInfo::defaultOutputDevice());
  if (info.deviceName().length() == 0)
    throw TSoundDeviceException(TSoundDeviceException::NoDevice,
                                "No device found, check QAudio backends");
  QList<int> ssrs = info.supportedSampleRates();
  if (!ssrs.contains(format.m_sampleRate)) format.m_sampleRate = 44100;
  QAudioFormat qFormat;
  qFormat.setSampleRate(format.m_sampleRate);
  qFormat.setSampleType(format.m_signedSample ? QAudioFormat::SignedInt
                                              : QAudioFormat::UnSignedInt);
  qFormat.setSampleSize(format.m_bitPerSample);
  qFormat.setCodec("audio/pcm");
  qFormat.setChannelCount(format.m_channelCount);
  qFormat.setByteOrder(QAudioFormat::LittleEndian);
  if (!info.isFormatSupported((qFormat))) {
    qFormat = info.nearestFormat(qFormat);
    format.m_bitPerSample = qFormat.sampleSize();
    format.m_channelCount = qFormat.channelCount();
    format.m_sampleRate = qFormat.sampleRate();
    if (qFormat.sampleType() == QAudioFormat::SignedInt)
      format.m_signedSample = true;
    else
      format.m_signedSample = false;
  }
#endif
  // Create the soundTrack
  double samplePerFrame = format.m_sampleRate / fps;
  // In seconds
  double duration = double(toFrame - fromFrame) / fps;
  // Seconds to Sample  (it is more accurate than using sampleCount
  double dsamp = duration * format.m_sampleRate;
  TINT32 lsamp = (TINT32)dsamp;
  if ((double)lsamp < dsamp - TConsts::epsilon) lsamp++;
  TSoundTrackP overallSoundTrack;
  try {
    overallSoundTrack = TSoundTrack::create(format, lsamp);
  } catch (TSoundDeviceException &) {
  }
  // Blank the whole track
  overallSoundTrack->blank(0, lsamp);
  if (levelsCount == 0) return overallSoundTrack;
  for (int i = 0; i < levelsCount; i++) {
    ColumnLevel *l             = m_levels.at(i);
    TXshSoundLevel *soundLevel = l->getSoundLevel();
    // Check if the soundtrack is inside the frame Range.
    int levelStartFrame = l->getStartFrame() + l->getStartOffset();
    int levelEndFrame   = levelStartFrame + soundLevel->getFrameCount() -
                        l->getStartOffset() - l->getEndOffset();
    // If the soundSequence is completely before fromFrame I will skip it
    if ((levelStartFrame < fromFrame && levelEndFrame < fromFrame)) continue;
    // If the soundSequence is after toFrame I don't check the others (that
    // comes later..)
    if ((levelStartFrame > toFrame && levelEndFrame > toFrame)) break;
    // Extract the right soundTrack (using the offsets)
    // (pay attention to convert it before)
    TSoundTrackP s = soundLevel->getSoundTrack();
    if (!s) continue;
    TSoundTrackP soundTrack = TSop::convert(s, format);
    int s0delta = 0;
    if (fromFrame > levelStartFrame) s0delta = fromFrame - levelStartFrame;
    int s0 = (l->getStartOffset() + s0delta) * samplePerFrame;
    int s1delta = 0;
    if (toFrame < levelEndFrame) s1delta = levelEndFrame - toFrame;
    int s1 = (soundLevel->getFrameCount() - l->getEndOffset() - s1delta) *
             samplePerFrame;
    if (s1 > 0 && s1 >= s0) {
      soundTrack = soundTrack->extract(s0, s1);
      // Copy the sound track
      overallSoundTrack->copy(
          soundTrack,
          int((levelStartFrame - fromFrame) *
              samplePerFrame));  // The int cast is IMPORTANT, since
    }                            // there are 2 overloads (int & double)
  }                              // with DIFFERENT SCALES. We mean the
                                 // SAMPLES-BASED one.
  return overallSoundTrack;
}
getRange()
int TXshSoundColumn::getRange (int & r0, int & r1) const override virtual
r0 : min row not empty, r1 : max row not empty. Return row count.
Reimplemented from TXshCellColumn.
{
  r0 = getFirstRow();
  r1 = getMaxFrame();
  return r1 - r0 + 1;
}
References getFirstRow(), and getMaxFrame().
getRowCount()
int TXshSoundColumn::getRowCount () const override virtual
Last not empty row - first not empty row.
Reimplemented from TXshCellColumn.
{
  return getMaxFrame() - getFirstRow();
}
References getFirstRow(), and getMaxFrame().
getSoundCell()
TXshCell TXshSoundColumn::getSoundCell (int row)
{
  static TXshCell emptyCell;
  ColumnLevel *l = getColumnLevelByFrame(row);
  if (row < 0 || row < getFirstRow() || row > getMaxFrame()) {
    if (l) emptyCell.m_level = l->getSoundLevel();
    return emptyCell;
  }
  if (!l) return emptyCell;
  TXshSoundLevel *soundLevel = l->getSoundLevel();
  TXshCell cell(soundLevel, TFrameId(row - l->getStartFrame()));
  return cell;
}
getSoundColumn()
TXshSoundColumn * TXshSoundColumn::getSoundColumn () inline override virtual
Reimplemented from TXshColumn.
{ return this; }
getVolume()
double TXshSoundColumn::getVolume () const
{ return m_volume; }
insertColumnLevel()
void TXshSoundColumn::insertColumnLevel (ColumnLevel * columnLevel, int index = -1) protected
If index == -1 insert soundColumnLevel at last and than order soundColumnLevel by startFrame.
{
  if (index == -1) index = m_levels.size();
  m_levels.insert(index, columnLevel);
  std::sort(m_levels.begin(), m_levels.end(), lessThan);
}
Referenced by assignLevels(), insertEmptyCells(), and loadData().
insertEmptyCells()
void TXshSoundColumn::insertEmptyCells (int row, int rowCount) override virtual
Insert rowCount empty cells from line row.
Reimplemented from TXshCellColumn.
{
  if (m_levels.isEmpty())
    return;  // se la colonna e' vuota non devo inserire celle
  int ra = row;
  int rb = row + rowCount - 1;
  assert(ra <= rb);
  // Se il livello nella riga ra inizia prima devo "spezzarlo"
  ColumnLevel *l = getColumnLevelByFrame(ra);
  if (l && l->getVisibleStartFrame() < ra) {
    int oldOffset = l->getEndOffset();
    l->setEndOffset(oldOffset + l->getVisibleEndFrame() - ra + 1);
    insertColumnLevel(new ColumnLevel(l->getSoundLevel(), l->getStartFrame(),
                                      row - l->getStartFrame(), oldOffset));
  }
  // Sposto il first frame di tutti i livelli successivi ad ra.
  int i;
  for (i = m_levels.count() - 1; i >= 0; i--) {
    ColumnLevel *cl = m_levels.at(i);
    if (cl->getVisibleStartFrame() < ra) continue;
    cl->setStartFrame(cl->getStartFrame() + rowCount);
  }
  checkColumn();
}
References checkColumn(), ColumnLevel::getSoundLevel(), ColumnLevel::getVisibleEndFrame(), ColumnLevel::getVisibleStartFrame(), insertColumnLevel(), and ColumnLevel::setStartFrame().
isCellEmpty()
bool TXshSoundColumn::isCellEmpty (int row) const override virtual
Return true if cell in row is empty.
See also
isEmpty()
Reimplemented from TXshCellColumn.
{
  if (m_levels.empty()) return true;
  ColumnLevel *l = getColumnLevelByFrame(row);
  if (!l || !l->getSoundLevel()) return true;
  return false;
}
References ColumnLevel::getSoundLevel().
isPlaying()
bool TXshSoundColumn::isPlaying () const
{
  return m_player && m_player->isPlaying();
}
loadData()
void TXshSoundColumn::loadData (TIStream & is) override virtual
 This is a pure virtual function and must be overridden with a method
that implements the object loading from a stream (i.e take the object's features from a formatted data stream). For example the TStageObject class use his implementation to take the values of the parameters that characterizes a stage object as name, coordinates, etc... from a file. is is an input file stream
Implements TPersist.
{
  VersionNumber tnzVersion = is.getVersion();
  if (tnzVersion < VersionNumber(1, 17)) {
    TFilePath path;
    is >> path;
    m_isOldVersion = true;
    int offset     = 0;
    is >> offset;
    is >> m_volume;
    if (!is.eos()) {
      int status;
      is >> status;
      setStatusWord(status);
    }
    TXshSoundLevelP level = new TXshSoundLevel(path.getWideName());
    level->setPath(path);
    ColumnLevel *l = new ColumnLevel(level.getPointer(), offset, 0, 0);
    insertColumnLevel(l);
    return;
  }
  is >> m_volume;
  int levelCount = 0;
  is >> levelCount;
  int i;
  for (i = 0; i < levelCount; i++) {
    ColumnLevel *sl = new ColumnLevel();
    sl->loadData(is);
    insertColumnLevel(sl, i);
  }
  if (!is.eos()) {
    int status;
    is >> status;
    setStatusWord(status);
  }
  std::string tagName;
  while (is.openChild(tagName)) {
    if (!loadCellMarks(tagName, is))
      throw TException("TXshLevelColumn, unknown tag: " + tagName);
    is.closeChild();
  }
}
References TIStream::closeChild(), TIStream::eos(), TIStream::getVersion(), insertColumnLevel(), TIStream::openChild(), and TXshColumn::setStatusWord().
mixingTogether()
TSoundTrackP TXshSoundColumn::mixingTogether (const std::vector< TXshSoundColumn * > & vect, int fromFrame = -1, int toFram = -1, double fps = -1)
                {
  int offset       = 0xffff;
  long sampleCount = 0;
  std::vector<TSoundTrackP> tracks;
  TSoundTrackP mix;
  int size = vect.size(), i = 0;
  ColumnLevel *l = vect[0]->getColumnLevel(0);
  if (!l)        // May happen if the sound level is not
    return mix;  // correctly loaded from disk
  TXshSoundLevel *soundLevel = l->getSoundLevel();
  assert(soundLevel);
  if (fps == -1) fps = soundLevel->getFrameRate();
  if (fromFrame == -1) fromFrame = 0;
  if (toFrame == -1) toFrame = getXsheet()->getFrameCount();
  if (!soundLevel->getSoundTrack()) return mix;
  TSoundTrackFormat format = soundLevel->getSoundTrack()->getFormat();
  TXshSoundColumn *c = 0;
  int j;
  for (j = 0; j < size; ++j) {
    TXshSoundColumn *oldC = c;
    c                     = vect[j];
    if (j == 0) {
      mix = c->getOverallSoundTrack(fromFrame, toFrame, fps, format);
      TSoundTrackP mixedTrack =
          TSoundTrack::create(mix->getFormat(), mix->getSampleCount());
      mix = TSop::mix(mixedTrack, mix, 1.0, c->getVolume());
      continue;
    }
    assert(oldC);
    if (c->getVolume() == 0 || c->isEmpty()) {
      c = oldC;
      continue;
    }
    mix =
        TSop::mix(mix, c->getOverallSoundTrack(fromFrame, toFrame, fps, format),
                  1.0, c->getVolume());
  }
  // Per ora perche mov vuole solo 16 bit
  TSoundTrackFormat fmt = mix->getFormat();
  if (fmt.m_bitPerSample != 16) fmt.m_bitPerSample = 16;
  mix = TSop::convert(mix, fmt);
  return mix;
}
modifyCellRange()
int TXshSoundColumn::modifyCellRange (int row, int delta, bool modifyStartValue)
Modify range of level sound in row. Return new range value of the level in row. N.B. Row must be the first or last cell of a sound level.
{
  ColumnLevel *l = getColumnLevelByFrame(row);
  if (!l) return -1;
  int startVisibleFrame = l->getVisibleStartFrame();
  int endVisibleFrame   = l->getVisibleEndFrame();
  // Non dovrebbe mai accadere, metto un controllo di sicurezza.
  if (startVisibleFrame != row && endVisibleFrame != row) return -1;
  int r0 = delta > 0 ? row : row + delta;
  int r1 = delta > 0 ? row + delta : row;
  int r;
  for (r = r0; r <= r1; r++) {
    ColumnLevel *oldL = getColumnLevelByFrame(r);
    if (!oldL || oldL == l) continue;
    int visibleStartFrame = oldL->getVisibleStartFrame();
    int visibleEndFrame   = oldL->getVisibleEndFrame();
    if (visibleStartFrame >= r0 && visibleEndFrame <= r1)
      removeColumnLevel(oldL);
    if (visibleStartFrame <= r0)
      oldL->setEndOffset(oldL->getEndOffset() + visibleEndFrame - r0 + 1);
    if (visibleEndFrame >= r1)
      oldL->setStartOffset(oldL->getStartOffset() + r1 - visibleStartFrame + 1);
    r = visibleEndFrame;
  }
  if (modifyStartValue) {
    // Evito che vada oltre il limite infieriore
    if (endVisibleFrame < startVisibleFrame + delta)
      delta = endVisibleFrame - startVisibleFrame;
    int newStartOffset = l->getStartOffset() + delta;
    // Evito che vada oltre il limite superiore
    if (newStartOffset < 0) newStartOffset = 0;
    l->setStartOffset(newStartOffset);
    checkColumn();
    getXsheet()->updateFrameCount();
    return l->getVisibleStartFrame();
  }
  // Evito che vada oltre il limite superiore
  if (startVisibleFrame > endVisibleFrame + delta)
    delta = startVisibleFrame - endVisibleFrame;
  // Evito che vada oltre il limite inferiore
  int newEndOffset = l->getEndOffset() - delta;
  if (newEndOffset < 0) newEndOffset = 0;
  l->setEndOffset(newEndOffset);
  checkColumn();
  getXsheet()->updateFrameCount();
  return l->getVisibleEndFrame();
}
References checkColumn(), ColumnLevel::getVisibleEndFrame(), ColumnLevel::getVisibleStartFrame(), TXshColumn::getXsheet(), and TXsheet::updateFrameCount().
onTimerOut
void TXshSoundColumn::onTimerOut () protected slot
{
#ifdef _WIN32
  if (m_player && m_player->isAllQueuedItemsPlayed()) stop();
#endif
}
play() [1/3]
void TXshSoundColumn::play (ColumnLevel * ss, int currentFrame)
Play the whole soundSequence, currentFrame it is used to compute an offset when the user play a single level and hence the audio behind..
{
  assert(columnLevel);
  TXshSoundLevel *soundLevel = columnLevel->getSoundLevel();
  int offset                 = 0;
  int startFrame             = currentFrame - columnLevel->getStartFrame();
  int endFrame = soundLevel->getFrameCount() - columnLevel->getEndOffset();
  int spf      = soundLevel->getSamplePerFrame();
  int s0       = startFrame * spf;
  int s1       = endFrame * spf;
  if (!soundLevel->getSoundTrack()) return;
  play(soundLevel->getSoundTrack(), s0, s1, false);
}
References ColumnLevel::getSoundLevel(), and play().
play() [2/3]
void TXshSoundColumn::play (int currentFrame = 0)
{
  try {
    TSoundTrackP soundTrack = getOverallSoundTrack(currentFrame);
    if (!soundTrack) return;
    int spf        = m_levels.at(0)->getSoundLevel()->getSamplePerFrame();
    int startFrame = (currentFrame - getFirstRow());
    int s0 = startFrame * spf;
    int s1 = getMaxFrame() * spf;
    play(soundTrack, s0, s1, false);
  } catch (TSoundDeviceException &e) {
    if (e.getType() == TSoundDeviceException::NoDevice) {
      std::cout << ::to_string(e.getMessage()) << std::endl;
    } else {
      throw TSoundDeviceException(e.getType(), e.getMessage());
    }
  }
}
play() [3/3]
void TXshSoundColumn::play (TSoundTrackP soundtrack, int s0, int s1, bool loop)
s0 and s1 are samples
{
  if (!TSoundOutputDevice::installed()) return;
  if (!m_player) m_player = new TSoundOutputDevice();
  if (m_player) {
    try {
#ifndef _WIN32
      m_player->prepareVolume(m_volume);
      TSoundTrackP mixedTrack = soundtrack;
#else
      TSoundTrackP mixedTrack = TSoundTrack::create(
          soundtrack->getFormat(), soundtrack->getSampleCount());
      mixedTrack = TSop::mix(mixedTrack, soundtrack, 1.0, m_volume);
#endif
      m_player->play(mixedTrack, s0, s1, loop);
      m_currentPlaySoundTrack = mixedTrack;
#ifdef _WIN32
      m_timer.start();
#endif
    } catch (TSoundDeviceException &) {
    }
  }
}
References TSoundTrack::create(), TSoundTrack::getFormat(), TSoundOutputDevice::installed(), TSop::mix(), and TSoundOutputDevice::play().
Referenced by play().
removeCells() [1/2]
void TXshSoundColumn::removeCells (int row, int rowCount) override virtual
Remove rowCount cells from line row, with shift.
Reimplemented from TXshCellColumn.
{
  removeCells(row, rowCount, true);
}
References removeCells().
Referenced by clearCells(), and removeCells().
removeCells() [2/2]
void TXshSoundColumn::removeCells (int row, int rowCount, bool shift) protected
{
  // le celle da cancellare sono [ra, rb]
  int ra = row;
  int rb = row + rowCount - 1;
  assert(ra <= rb);
  int i;
  for (i = m_levels.size() - 1; i >= 0; i--) {
    ColumnLevel *l = m_levels.at(i);
    if (!l) continue;  // Non dovrebbe accadere!
    int visibleStartFrame = l->getVisibleStartFrame();
    int visibleEndFrame   = l->getVisibleEndFrame();
    // Fuori dal range da tagliare.
    if (visibleStartFrame > rb || visibleEndFrame < ra) continue;
    int newEndOffset   = l->getEndFrame() - ra + 1;
    int newStartOffset = rb - l->getStartFrame() + 1;
    // Il livello contiene il range da cancellare: devo "spezzare" il livello in
    // due.
    if (visibleStartFrame < ra && visibleEndFrame > rb) {
      int oldEndOffset = l->getEndOffset();
      l->setEndOffset(newEndOffset);
      insertColumnLevel(new ColumnLevel(l->getSoundLevel(), l->getStartFrame(),
                                        newStartOffset, oldEndOffset));
      continue;
    }
    if (visibleStartFrame < ra) l->setEndOffset(newEndOffset);
    if (visibleEndFrame > rb) l->setStartOffset(newStartOffset);
    // Il livello e' contenuto nel range da cancellare: lo rimuovo.
    if (visibleStartFrame >= ra && visibleEndFrame <= rb) removeColumnLevel(l);
  }
  if (shift) {
    for (i = m_levels.size() - 1; i >= 0; i--) {
      ColumnLevel *l = m_levels.at(i);
      if (!l) continue;  // Non dovrebbe accadere!
      int visibleStartFrame = l->getVisibleStartFrame();
      int visibleEndFrame   = l->getVisibleEndFrame();
      if (visibleStartFrame > ra)
        l->setStartFrame(l->getStartFrame() - rowCount);
    }
    // Devo controllare se il livello precedente il taglio e quello successivo
    // sono in sequenza
    ColumnLevel *beforeL = getColumnLevelByFrame(ra - 1);
    ColumnLevel *nextL   = getColumnLevelByFrame(ra);
    if (beforeL && nextL &&
        beforeL->getSoundLevel() == nextL->getSoundLevel() &&
        beforeL->getStartFrame() == nextL->getStartFrame()) {
      beforeL->setEndOffset(nextL->getEndOffset());
      removeColumnLevel(nextL);
    }
  }
  checkColumn();
}
removeColumnLevel()
void TXshSoundColumn::removeColumnLevel (ColumnLevel * columnLevel) protected
{
  if (!columnLevel) return;
  int index = m_levels.indexOf(columnLevel);
  if (index == -1) return;
  m_levels.removeAt(index);
  delete columnLevel;
}
saveData()
void TXshSoundColumn::saveData (TOStream & os) override virtual
 This is a pure virtual function and must be overridden with a method
that implements the object saving to a data stream (i.e put the object's features on a formatted data stream). For example the TStageObject class use his implementation to save the values of the parameters that characterizes a stage object as name, coordinates, etc... on a file os is an output file stream.
Implements TPersist.
{
  os << m_volume;
  int levelsCount = m_levels.size();
  os << levelsCount;
  if (levelsCount == 0) return;
  int i;
  for (i = 0; i < levelsCount; i++) m_levels.at(i)->saveData(os);
  os << getStatusWord();
  // cell marks
  saveCellMarks(os);
}
References TXshColumn::getStatusWord().
scrub()
void TXshSoundColumn::scrub (int fromFrame, int toFrame)
{
  if (!isCamstandVisible()) return;
  try {
    TSoundTrackP soundTrack = getOverallSoundTrack(fromFrame, toFrame + 1);
    if (!soundTrack) return;
    play(soundTrack, 0, soundTrack->getSampleCount(), false);
  } catch (TSoundDeviceException &e) {
    if (e.getType() == TSoundDeviceException::NoDevice) {
      std::cout << ::to_string(e.getMessage()) << std::endl;
    } else {
      throw TSoundDeviceException(e.getType(), e.getMessage());
    }
  }
}
setCell() [1/2]
bool TXshSoundColumn::setCell (int row, const TXshCell & cell) override virtual
Set cell in row to TXshCell cell.
See also
setCells() and getCell(); return false if cannot set cells.
Reimplemented from TXshCellColumn.
{
  return setCell(row, cell, false);
}
References setCell().
Referenced by setCell(), setCells(), and updateCells().
setCell() [2/2]
bool TXshSoundColumn::setCell (int row, const TXshCell & cell, bool updateSequence) protected
{
  if (!canSetCell(cell)) return false;
  assert(row >= 0);
  ColumnLevel *lBefore = getColumnLevelByFrame(row - 1);
  ColumnLevel *l       = getColumnLevelByFrame(row);
  ColumnLevel *lNext   = getColumnLevelByFrame(row + 1);
  // Se non devo fare un update della sequenzialita' e la cella e' uguale a
  // quella gia' esistente ritorno.
  if (!updateSequence && l && l->getSoundLevel() == cell.getSoundLevel() &&
      row - l->getStartFrame() == cell.getFrameId().getNumber())
    return false;
  bool isBeforeLevelInSequence =
      (lBefore && lBefore->getSoundLevel() == cell.getSoundLevel() &&
       row - lBefore->getStartFrame() == cell.getFrameId().getNumber());
  bool isNextLevelInSequence =
      (lNext && lNext->getSoundLevel() == cell.getSoundLevel() &&
       row - lNext->getStartFrame() == cell.getFrameId().getNumber());
  // Modifico solo l'endOffset del BeforeLevel
  if (isBeforeLevelInSequence) {
    int oldEndOffset = lBefore->getEndOffset();
    int endOffset    = (lBefore->getVisibleEndFrame() != row) ? oldEndOffset - 1
                                                           : oldEndOffset;
    if (isNextLevelInSequence) {
      endOffset = lNext->getEndOffset();
      // Se precedente e successivo sono diversi elimino il successivo (caso in
      // cui inserisci un frame in successione su una cella vuota)
      if (lNext != lBefore) removeColumnLevel(lNext);
    }
    if (l && l != lBefore) {
      if (l->getVisibleFrameCount() == 1)
        removeColumnLevel(l);
      else
        l->setStartOffset(l->getStartOffset() + 1);
    }
    lBefore->setEndOffset(endOffset);
    checkColumn();
    return true;
  }
  // Modifico solo lo startOffset del NextLevel
  if (isNextLevelInSequence) {
    int oldStartOffset = lNext->getStartOffset();
    int startOffset    = (lNext->getVisibleStartFrame() != row)
                          ? oldStartOffset - 1
                          : oldStartOffset;
    if (l && l != lNext) {
      if (l->getVisibleFrameCount() == 1)
        removeColumnLevel(l);
      else
        l->setEndOffset(l->getEndOffset() + 1);
    }
    lNext->setStartOffset(startOffset);
    checkColumn();
    return true;
  }
  // I Frame non sono in successione quindi devo inserire la cella in frame un
  // vuoto:
  clearCells(row, 1);
  setCellInEmptyFrame(row, cell);
  checkColumn();
  return true;
}
setCellInEmptyFrame()
void TXshSoundColumn::setCellInEmptyFrame (int row, const TXshCell & cell) protected
{
  if (cell.isEmpty()) return;
  TXshSoundLevel *soundLevel = cell.getSoundLevel();
  if (!soundLevel) return;
  int startOffset = cell.getFrameId().getNumber();
  int startFrame  = row - startOffset;
  int endOffset   = startFrame + soundLevel->getFrameCount() - 1 - row;
  insertColumnLevel(
      new ColumnLevel(soundLevel, startFrame, startOffset, endOffset));
}
setCells()
bool TXshSoundColumn::setCells (int row, int rowCount, const TXshCell cells[]) override virtual
Return false if cannot set cells.
Reimplemented from TXshCellColumn.
{
  assert(row >= 0);
  // le celle da settare sono [ra, rb]
  int ra = row;
  int rb = row + rowCount - 1;
  assert(ra <= rb);
  bool ret = false;
  int r;
  for (r = ra; r <= rb; r++) {
    bool isOneCellSet = setCell(r, cells[r - ra]);
    if (isOneCellSet) ret = isOneCellSet;
  }
  return ret;
}
References setCell().
setFrameRate()
void TXshSoundColumn::setFrameRate (double fps)
{
  if (m_levels.empty()) return;
  int i;
  for (i = 0; i < m_levels.size(); i++) {
    ColumnLevel *column        = m_levels.at(i);
    TXshSoundLevel *soundLevel = column->getSoundLevel();
    if (soundLevel->getFrameRate() != fps) soundLevel->setFrameRate(fps);
    column->setFrameRate(fps);
  }
}
setVolume()
void TXshSoundColumn::setVolume (double value)
From 0.0 to 1.0.
{
  m_volume = tcrop<double>(value, 0.0, 1.0);
  if (m_player && m_player->isPlaying())
#ifndef _WIN32
    m_player->setVolume(m_volume);
#else
    stop();
#endif
}
References TSoundOutputDevice::isPlaying(), and TSoundOutputDevice::setVolume().
setXsheet()
void TXshSoundColumn::setXsheet (TXsheet * xsheet) override virtual
Set m_xsheet to xsheet.
See also
getXsheet()
Reimplemented from TXshColumn.
{
  TXshColumn::setXsheet(xsheet);
  ToonzScene *scene = xsheet->getScene();
  if (!scene || m_levels.empty()) return;
  if (m_isOldVersion) {
    assert(m_levels.size() == 1);
    scene->getLevelSet()->insertLevel(m_levels.at(0)->getSoundLevel());
    m_isOldVersion = false;
  }
  TOutputProperties *properties = scene->getProperties()->getOutputProperties();
  setFrameRate(properties->getFrameRate());
}
References TOutputProperties::getFrameRate(), ToonzScene::getLevelSet(), TSceneProperties::getOutputProperties(), ToonzScene::getProperties(), TXsheet::getScene(), and TXshColumn::setXsheet().
stop()
void TXshSoundColumn::stop ()
{
  if (m_player) {
    m_player->stop();
    m_player->close();
    m_player                = 0;
    m_currentPlaySoundTrack = TSoundTrackP();
  }
}
updateCells()
void TXshSoundColumn::updateCells (int row, int rowCount)
Check if frames from row to row+rowCount are in sequence and collapse level if it is true.
{
  int r;
  for (r = row; r < row + rowCount; r++) {
    TXshCell cell = getCell(r);
    setCell(row, cell, true);
  }
}
References getCell(), and setCell().
updateFrameRate()
void TXshSoundColumn::updateFrameRate (double fps)
{
  if (m_levels.empty()) return;
  int i;
  for (i = 0; i < m_levels.size(); i++) {
    ColumnLevel *column        = m_levels.at(i);
    TXshSoundLevel *soundLevel = column->getSoundLevel();
    double oldFps              = soundLevel->getFrameRate();
    if (oldFps != fps) soundLevel->setFrameRate(fps);
    column->updateFrameRate(fps);
  }
}
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/toonz/txshsoundcolumn.h
E:/opentoonz/toonz/sources/toonzlib/txshsoundcolumn.cpp