opentoonz: OnionSkinMask Class Reference
OnionSkinMask Class Reference
#include <onionskinmask.h>
Public Types
enum ShiftTraceStatus { DISABLED , EDITING_GHOST , ENABLED , ENABLED_WITHOUT_GHOST_MOVEMENTS }
Public Member Functions
void clear ()
void getAll (int currentRow, std::vector< int > &output) const
Fills in the output vector with the absolute frames to be onion-skinned.
int getMosCount () const
Returns the Mobile OS frames count.
int getFosCount () const
Returns the Fixed OS frames count.
int getMos (int index) const
int getFos (int index) const
void setMos (int drow, bool on)
void setFos (int row, bool on)
Sets a Fixed OS frame to the specified xsheet row.
bool isMos (int drow) const
bool isFos (int row) const
bool getMosRange (int &drow0, int &drow1) const
bool isEmpty () const
bool isEnabled () const
void enable (bool on)
bool isWholeScene () const
void setIsWholeScene (bool wholeScene)
ShiftTraceStatus getShiftTraceStatus () const
void setShiftTraceStatus (ShiftTraceStatus status)
bool isShiftTraceEnabled () const
const TAffine getShiftTraceGhostAff (int index) const
void setShiftTraceGhostAff (int index, const TAffine &aff)
const TPointD getShiftTraceGhostCenter (int index) const
void setShiftTraceGhostCenter (int index, const TPointD &center)
const int getShiftTraceGhostFrameOffset (int index)
void setShiftTraceGhostFrameOffset (int index, int offset)
const int getGhostFlipKey ()
void appendGhostFlipKey (int key)
void removeGhostFlipKey (int key)
void clearGhostFlipKey ()
Static Public Member Functions
static double getOnionSkinFade (int distance)
Detailed Description
OnionSkinMask is the class encapsulating onion skin data in Toonz.
Member Enumeration Documentation
ShiftTraceStatus
enum OnionSkinMask::ShiftTraceStatus
{
    DISABLED,
    EDITING_GHOST,
    ENABLED,
    ENABLED_WITHOUT_GHOST_MOVEMENTS
  };
Constructor & Destructor Documentation
OnionSkinMask()
OnionSkinMask::OnionSkinMask () inline
: m_enabled(false), m_wholeScene(false) {}
Member Function Documentation
appendGhostFlipKey()
void OnionSkinMask::appendGhostFlipKey (int key) inline
{
    m_ghostFlipKeys.removeAll(key);
    m_ghostFlipKeys.append(key);
  }
clear()
void OnionSkinMask::clear ()
{
  m_fos.clear();
  m_mos.clear();
  m_shiftTraceStatus = DISABLED;
  m_ghostAff[0]    = TAffine();
  m_ghostAff[1]    = TAffine();
  m_ghostCenter[0] = TPointD();
  m_ghostCenter[1] = TPointD();
  m_ghostFrame[0]  = 0;
  m_ghostFrame[1]  = 0;
}
clearGhostFlipKey()
void OnionSkinMask::clearGhostFlipKey () inline
{ m_ghostFlipKeys.clear(); }
enable()
void OnionSkinMask::enable (bool on) inline
{ m_enabled = on; }
getAll()
void OnionSkinMask::getAll (int currentRow, std::vector< int > & output) const
Fills in the output vector with the absolute frames to be onion-skinned.
{
  output.clear();
  output.reserve(m_fos.size() + m_mos.size());
  std::vector<int>::const_iterator fosIt, fosEnd(m_fos.end());
  std::vector<int>::const_iterator mosIt, mosEnd(m_mos.end());
  for (fosIt = m_fos.begin(), mosIt = m_mos.begin();
       fosIt != fosEnd && mosIt != mosEnd;) {
    int fos = *fosIt, mos = *mosIt + currentRow;
    if (fos < mos) {
      if (fos != currentRow) output.push_back(fos);
      ++fosIt;
    } else {
      if (mos != currentRow) output.push_back(mos);
      ++mosIt;
    }
  }
  for (; fosIt != fosEnd; ++fosIt)
    if (*fosIt != currentRow) output.push_back(*fosIt);
  for (; mosIt != mosEnd; ++mosIt) {
    int mos = *mosIt + currentRow;
    if (mos != currentRow) output.push_back(mos);
  }
}
Referenced by StageBuilder::addCellWithOnionSkin(), StageBuilder::addSimpleLevelFrame(), and HookTool::draw().
getFos()
int OnionSkinMask::getFos (int index) const inline
{
    assert(0 <= index && index < (int)m_fos.size());
    return m_fos[index];
  }
getFosCount()
int OnionSkinMask::getFosCount () const inline
Returns the Fixed OS frames count.
getGhostFlipKey()
const int OnionSkinMask::getGhostFlipKey () inline
{
    return (m_ghostFlipKeys.isEmpty()) ? 0 : m_ghostFlipKeys.last();
  }
getMos()
int OnionSkinMask::getMos (int index) const inline
{
    assert(0 <= index && index < (int)m_mos.size());
    return m_mos[index];
  }
getMosCount()
int OnionSkinMask::getMosCount () const inline
Returns the Mobile OS frames count.
getMosRange()
bool OnionSkinMask::getMosRange (int & drow0, int & drow1) const
{
  if (m_mos.empty()) {
    drow0 = 0, drow1 = -1;
    return false;
  } else {
    drow0 = m_mos.front(), drow1 = m_mos.back();
    return true;
  }
}
getOnionSkinFade()
double OnionSkinMask::getOnionSkinFade (int distance) static
Returns the fade (transparency) value, in the [0.0, 1.0] range, corresponding to the specified distance from current frame. In case distance == 0, the returned value is 0.9, ie almost opaque, since underlying onion-skinned drawings must be visible.
{
  if (rowsDistance == 0) return 0.9;
  double fade =
      MINFADE +
      abs(rowsDistance) *
          getIncrement(Preferences::instance()->getOnionPaperThickness());
  return tcrop(fade, MINFADE, MAXFADE);
}
Referenced by Stage::RasterPainter::onRasterImage(), Stage::RasterPainter::onToonzImage(), and Stage::RasterPainter::onVectorImage().
getShiftTraceGhostAff()
const TAffine OnionSkinMask::getShiftTraceGhostAff (int index) const inline
{
    return m_ghostAff[index];
  }
getShiftTraceGhostCenter()
const TPointD OnionSkinMask::getShiftTraceGhostCenter (int index) const inline
{
    return m_ghostCenter[index];
  }
getShiftTraceGhostFrameOffset()
const int OnionSkinMask::getShiftTraceGhostFrameOffset (int index) inline
{
    return m_ghostFrame[index];
  }
getShiftTraceStatus()
ShiftTraceStatus OnionSkinMask::getShiftTraceStatus () const inline
{ return m_shiftTraceStatus; }
isEmpty()
bool OnionSkinMask::isEmpty () const inline
{ return m_mos.empty() && m_fos.empty(); }
isEnabled()
bool OnionSkinMask::isEnabled () const inline
{ return m_enabled; }
isFos()
bool OnionSkinMask::isFos (int row) const
{
  return std::binary_search(m_fos.begin(), m_fos.end(), row);
}
isMos()
bool OnionSkinMask::isMos (int drow) const
{
  return std::binary_search(m_mos.begin(), m_mos.end(), drow);
}
isShiftTraceEnabled()
bool OnionSkinMask::isShiftTraceEnabled () const inline
{ return m_shiftTraceStatus != DISABLED; }
isWholeScene()
bool OnionSkinMask::isWholeScene () const inline
{ return m_wholeScene; }
removeGhostFlipKey()
void OnionSkinMask::removeGhostFlipKey (int key) inline
{ m_ghostFlipKeys.removeAll(key); }
setFos()
void OnionSkinMask::setFos (int row, bool on)
Sets a Fixed OS frame to the specified xsheet row.
{
  typedef std::vector<int>::iterator Iter;
  std::pair<Iter, Iter> r = std::equal_range(m_fos.begin(), m_fos.end(), row);
  if (on) {
    if (r.first == r.second) m_fos.insert(r.first, row);
  } else {
    if (r.first != r.second) m_fos.erase(r.first, r.second);
  }
}
setIsWholeScene()
void OnionSkinMask::setIsWholeScene (bool wholeScene) inline
{ m_wholeScene = wholeScene; }
setMos()
void OnionSkinMask::setMos (int drow, bool on)
Sets a Mobile OS frame shifted by drow around current xsheet frame
{
  assert(drow != 0);
  typedef std::vector<int>::iterator Iter;
  std::pair<Iter, Iter> r = std::equal_range(m_mos.begin(), m_mos.end(), drow);
  if (on) {
    if (r.first == r.second) m_mos.insert(r.first, drow);
  } else {
    if (r.first != r.second) m_mos.erase(r.first, r.second);
  }
}
setShiftTraceGhostAff()
void OnionSkinMask::setShiftTraceGhostAff (int index, const TAffine & aff)
{
  assert(0 <= index && index < 2);
  m_ghostAff[index] = aff;
}
setShiftTraceGhostCenter()
void OnionSkinMask::setShiftTraceGhostCenter (int index, const TPointD & center)
{
  assert(0 <= index && index < 2);
  m_ghostCenter[index] = center;
}
setShiftTraceGhostFrameOffset()
void OnionSkinMask::setShiftTraceGhostFrameOffset (int index, int offset) inline
{
    m_ghostFrame[index] = offset;
  }
setShiftTraceStatus()
void OnionSkinMask::setShiftTraceStatus (ShiftTraceStatus status) inline
{
    m_shiftTraceStatus = status;
  }
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/toonz/onionskinmask.h
E:/opentoonz/toonz/sources/toonzlib/onionskinmask.cpp