opentoonz: PlasticDeformerStorage Class Reference
PlasticDeformerStorage Class Reference
PlasticDeformerStorage is the global storage class for plastic deformers.
#include <plasticdeformerstorage.h>
Classes
class Imp
Public Types
enum DataType {
NONE = 0x0 , HANDLES = 0x1 , SO = 0x4 , MESH = 0x8 ,
ALL = HANDLES | SO | MESH
}
Public Member Functions
const PlasticDeformerDataGroup * process (double frame, const TMeshImage *meshImage, const PlasticSkeletonDeformation *deformation, int skeletonId, const TAffine &deformationToMeshAffine, DataType dataType=ALL)
void invalidateMeshImage (const TMeshImage *meshImage, int recompiledDataType=NONE)
void invalidateSkeleton (const PlasticSkeletonDeformation *deformation, int skeletonId, int recompiledDataType=NONE)
void invalidateDeformation (const PlasticSkeletonDeformation *deformation, int recompiledDataType=NONE)
void releaseMeshData (const TMeshImage *meshImage)
Releases all deformers associated to the specified mesh image.
void releaseSkeletonData (const PlasticSkeletonDeformation *deformation, int skeletonId)
Releases all deformers associated to the specified skeletal deformation.
void releaseDeformationData (const PlasticSkeletonDeformation *deformation)
Releases all deformers associated to the specified skeletal deformation.
void clear ()
Static Public Member Functions
static PlasticDeformerStorage * instance ()
static const PlasticDeformerDataGroup * processOnce (double frame, const TMeshImage *meshImage, const PlasticSkeletonDeformation *deformation, int skeletonId, const TAffine &deformationToMeshAffine, DataType dataType=ALL)
Performs the specified deformation once, without caching data.
Detailed Description
PlasticDeformerStorage is the global storage class for plastic deformers.
PlasticDeformer models a mesh-deformer object that can be used together with texturing to create an interactive image-deformation technique. Direct use of PlasticDeformer instances is discouraged, as they can be considered as technical low-level interfaces to the deformation job.
Rationale
The crucial reason behind the existence of this class lies in the necessity to cache PlasticDeformer instances to achieve real-time speed in the processing of part of its algorithms.
In this context, caching is all about storing intermediate data so that they are recalculated only when strictly necessary. In PlasticDeformer's case, we can see 3 chained processing stages that need to be calculated before the final result is produced:
Initialization: <\B> A mesh is acquired
Compilation: <\B> The deformation's source domain data is acquired
Deformation: <\B> The deformation's destination domain data is acquired
Each step requires that the previous one has been computed. Obviously when, say, only the deformation's destination data change, there is no need to process the first 2 steps - their cached data remains valid.
Interface
This class provides the preferential high-level interface to plastic deformers.
The storage caches data about every requested deform specification, that is kept until an explicit release command is issued. A data request is issued with a call to the process() method, which accepts specification of a subset of deform-related data to be returned, skipping unnecessary computations.
The storage requires explicit content invalidation to know that is must recalculate subsequent requests. Invalidation is specific to changes in a PlasticSkeletonDeformation instance, and can be restrained to the destination (deformed) domain, or require more expensive invalidation.
Deformations and Data requests
Cached data is uniquely associated with pairs of meshImage and deformed skeletons, meaning that the same meshImage can be deformed by multiple skeletons, and viceversa.
A deformer data request needs an affine transform in input, which is intended to map the skeleton deformation on top of the mesh (in mesh coordinates). The storage does not <\I> store a PlasticDeformer instance for each different affine supplied, but rather invalidates the old data in case it changes.
The mesh vertex coordinates resulting from a deformation will be stored in the resulting PlasticDeformerData::m_output member of each entry of the output array, one for each mesh of the input meshImage. The returned coordinates are intended in the mesh reference.
Lifetime and Ownership
This class does not claim ownerhip <\B> of neither the mesh nor the deformation that are specified in a deformer request - and lifetime tracking <\I> of the objects involved in plastic deforming is a burden of callers.
This class requires that the destruction of either a mesh or a deformation be signaled by a call to the appropriate release method in order to enforce the associated deformers destruction.
Warning
No call to the appropriate release method when either a mesh or a deformation which has requested a deformer is destroyed will result in a leak.
Member Enumeration Documentation
DataType
enum PlasticDeformerStorage::DataType
                {
    NONE    = 0x0,
    HANDLES = 0x1,  // Handles data
    SO      = 0x4,  // Stacking Order data
    MESH    = 0x8,  // The deformed Mesh
    ALL = HANDLES | SO | MESH
  };
Constructor & Destructor Documentation
PlasticDeformerStorage()
PlasticDeformerStorage::PlasticDeformerStorage ()
: m_imp(new Imp) {}
~PlasticDeformerStorage()
PlasticDeformerStorage::~PlasticDeformerStorage ()
{}
Member Function Documentation
clear()
void PlasticDeformerStorage::clear ()
Releases all deformers, effectively returning the storage to its empty state.
{
  QMutexLocker locker(&m_imp->m_mutex);
  m_imp->m_deformers.clear();
}
instance()
PlasticDeformerStorage * PlasticDeformerStorage::instance () static
{
  static PlasticDeformerStorage theInstance;
  return &theInstance;
}
invalidateDeformation()
void PlasticDeformerStorage::invalidateDeformation (const PlasticSkeletonDeformation * deformation, int recompiledDataType = NONE)
Similarly to invalidateSkeleton(), for everything attached to the specified deformation.
{
  QMutexLocker locker(&m_imp->m_mutex);
  DeformersByDeformedSkeleton &deformers =
      m_imp->m_deformers.get<DeformedSkeleton>();
  DeformedSkeleton dsBegin(deformation, -(std::numeric_limits<int>::max)()),
      dsEnd(deformation, (std::numeric_limits<int>::max)());
  DeformersByDeformedSkeleton::iterator dBegin(deformers.lower_bound(dsBegin));
  DeformersByDeformedSkeleton::iterator dEnd(deformers.upper_bound(dsEnd));
  if (dBegin == dEnd) return;
  for (DeformersByDeformedSkeleton::iterator dt = dBegin; dt != dEnd; ++dt) {
    dt->m_dataGroup->m_outputFrame =
        (std::numeric_limits<double>::max)();  // Schedule for redeformation
    if (recompiledData)
      dt->m_dataGroup->m_compiled &=
          ~recompiledData;  // Schedule for recompilation, too
  }
}
invalidateMeshImage()
void PlasticDeformerStorage::invalidateMeshImage (const TMeshImage * meshImage, int recompiledDataType = NONE)
Similarly to invalidateSkeleton(), for every deformer attached to the specified mesh.
{
  QMutexLocker locker(&m_imp->m_mutex);
  DeformersByMeshImage &deformers = m_imp->m_deformers.get<TMeshImage>();
  DeformersByMeshImage::iterator dBegin(deformers.lower_bound(meshImage));
  if (dBegin == deformers.end()) return;
  DeformersByMeshImage::iterator dt, dEnd(deformers.upper_bound(meshImage));
  for (dt = dBegin; dt != dEnd; ++dt) {
    dt->m_dataGroup->m_outputFrame =
        (std::numeric_limits<double>::max)();  // Schedule for redeformation
    if (recompiledData)
      dt->m_dataGroup->m_compiled &=
          ~recompiledData;  // Schedule for recompilation, too
  }
}
invalidateSkeleton()
void PlasticDeformerStorage::invalidateSkeleton (const PlasticSkeletonDeformation * deformation, int skeletonId, int recompiledDataType = NONE)
Schedules all stored deformers associated to the specified deformation for either re-deformation (stage 3 invalidation) or re-compilation (stage 2 invalidation).
Recompilation should be selected whenever the deformation has sustained source domain changes, such as a vertex addition or removal, or when the source skeletal configuration has changed.
Note
Recompilation is typically a slower process than the mere deformers update. Select it explicitly only when it truly needs to be done.
{
  QMutexLocker locker(&m_imp->m_mutex);
  DeformedSkeleton ds(deformation, skelId);
  DeformersByDeformedSkeleton &deformers =
      m_imp->m_deformers.get<DeformedSkeleton>();
  DeformersByDeformedSkeleton::iterator dBegin(deformers.lower_bound(ds));
  if (dBegin == deformers.end()) return;
  DeformersByDeformedSkeleton::iterator dt, dEnd(deformers.upper_bound(ds));
  for (dt = dBegin; dt != dEnd; ++dt) {
    dt->m_dataGroup->m_outputFrame =
        (std::numeric_limits<double>::max)();  // Schedule for redeformation
    if (recompiledData)
      dt->m_dataGroup->m_compiled &=
          ~recompiledData;  // Schedule for recompilation, too
  }
}
Referenced by PlasticTool::onPropertyChanged().
process()
const PlasticDeformerDataGroup * PlasticDeformerStorage::process (double frame, const TMeshImage * meshImage, const PlasticSkeletonDeformation * deformation, int skeletonId, const TAffine & deformationToMeshAffine, DataType dataType = ALL)
This function processes the specified meshImage-deformation pair, returning a DataGroup with the required data.
Note
This function caches all required data, so that subsequent requests about the same triplet can be sped up considerably in case of cache match.
{
  QMutexLocker locker(&m_imp->m_mutex);
  PlasticDeformerDataGroup *group =
      deformerData(meshImage, deformation, skelId);
  // On-the-fly checks for data invalidation
  if (group->m_skeletonAffine != skeletonAffine) {
    group->m_upToDate       = NONE;
    group->m_compiled       = NONE;
    group->m_skeletonAffine = skeletonAffine;
  }
  if (group->m_outputFrame != frame) {
    group->m_upToDate    = NONE;
    group->m_outputFrame = frame;
  }
  bool doMesh    = (dataType & MESH);
  bool doSO      = (dataType & SO) || doMesh;
  bool doHandles = (bool)dataType;
  // Process data
  if (doHandles)
    processHandles(group, frame, meshImage, deformation, skelId,
                   skeletonAffine);
  if (doSO)
    processSO(group, frame, meshImage, deformation, skelId, skeletonAffine);
  if (doMesh)
    processMesh(group, frame, meshImage, deformation, skelId, skeletonAffine);
  return group;
}
processOnce()
const PlasticDeformerDataGroup * PlasticDeformerStorage::processOnce (double frame, const TMeshImage * meshImage, const PlasticSkeletonDeformation * deformation, int skeletonId, const TAffine & deformationToMeshAffine, DataType dataType = ALL) static
Performs the specified deformation once, without caching data.
This method allows the user to perform a single-shot Platic deformation, without dealing with caching issues.
Note
Since caching is disabled, this method is comparably slower than its cached counterpart, in case the same deformation is repeatedly invoked. It is meant to be used only in absence of user interaction.
Warning
The returned pointer is owned by the caller, and must be manually deleted when no longer needed.
{
  PlasticDeformerDataGroup *group = new PlasticDeformerDataGroup;
  initializeDeformersData(group, meshImage);
  bool doMesh    = (dataType & MESH);
  bool doSO      = (dataType & SO) || doMesh;
  bool doHandles = (bool)dataType;
  // Process data
  if (doHandles)
    processHandles(group, frame, meshImage, deformation, skelId,
                   skeletonAffine);
  if (doSO)
    processSO(group, frame, meshImage, deformation, skelId, skeletonAffine);
  if (doMesh)
    processMesh(group, frame, meshImage, deformation, skelId, skeletonAffine);
  return group;
}
releaseDeformationData()
void PlasticDeformerStorage::releaseDeformationData (const PlasticSkeletonDeformation * deformation)
Releases all deformers associated to the specified skeletal deformation.
{
  QMutexLocker locker(&m_imp->m_mutex);
  DeformersByDeformedSkeleton &deformers =
      m_imp->m_deformers.get<DeformedSkeleton>();
  DeformedSkeleton dsBegin(deformation, -(std::numeric_limits<int>::max)()),
      dsEnd(deformation, (std::numeric_limits<int>::max)());
  DeformersByDeformedSkeleton::iterator dBegin(deformers.lower_bound(dsBegin));
  DeformersByDeformedSkeleton::iterator dEnd(deformers.upper_bound(dsEnd));
  if (dBegin == dEnd) return;
  deformers.erase(dBegin, dEnd);
}
Referenced by TStageObject::setPlasticSkeletonDeformation(), and TStageObject::~TStageObject().
releaseMeshData()
void PlasticDeformerStorage::releaseMeshData (const TMeshImage * meshImage)
Releases all deformers associated to the specified mesh image.
{
  QMutexLocker locker(&m_imp->m_mutex);
  DeformersByMeshImage &deformers = m_imp->m_deformers.get<TMeshImage>();
  DeformersByMeshImage::iterator dBegin(deformers.lower_bound(meshImage));
  if (dBegin == deformers.end()) return;
  deformers.erase(dBegin, deformers.upper_bound(meshImage));
}
releaseSkeletonData()
void PlasticDeformerStorage::releaseSkeletonData (const PlasticSkeletonDeformation * deformation, int skeletonId)
Releases all deformers associated to the specified skeletal deformation.
{
  QMutexLocker locker(&m_imp->m_mutex);
  DeformedSkeleton ds(deformation, skelId);
  DeformersByDeformedSkeleton &deformers =
      m_imp->m_deformers.get<DeformedSkeleton>();
  DeformersByDeformedSkeleton::iterator dBegin(deformers.lower_bound(ds));
  if (dBegin == deformers.end()) return;
  deformers.erase(dBegin, deformers.upper_bound(ds));
}
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/ext/plasticdeformerstorage.h
E:/opentoonz/toonz/sources/tnzext/plasticdeformerstorage.cpp