opentoonz: TFarmTaskGroup Class Reference
TFarmTaskGroup Class Reference final
Classes
class Imp
Public Member Functions
TFarmTaskGroup (const QString &id, const QString &name, const QString &user, const QString &host, int stepCount, int priority, const TFilePath &taskFilePath, const TFilePath &outputPath, int from, int to, int step, int shrink, int multimedia, int chunksize, int threadsIndex, int maxTileSizeIndex)
TFarmTaskGroup (const QString &id, const QString &name, const QString &user, const QString &host, int stepCount, int priority, const TFilePath &taskFilePath, OverwriteBehavior overwrite, bool onlyvisible)
TFarmTaskGroup (const QString &id, const QString &name, const QString &cmdline, const QString &user, const QString &host, int stepCount, int priority)
TFarmTaskGroup (const TFarmTaskGroup &src)
void addTask (TFarmTask *task)
void removeTask (TFarmTask *task)
int getTaskCount () const override
TFarmTask * getTask (int index) override
bool changeChunkSize (int chunksize)
void loadData (TIStream &is) override
void saveData (TOStream &os) override
const TPersistDeclaration * getDeclaration () const override
Public Member Functions inherited from TFarmTask
TFarmTask (const QString &name="")
TFarmTask (const QString &id, const QString &name, const QString &cmdline, const QString &user, const QString &host, int stepCount, int priority)
TFarmTask (const QString &id, const QString &name, bool composerTask, const QString &user, const QString &host, int stepCount, int priority, const TFilePath &taskFilePath, const TFilePath &outputPath, int from, int to, int step, int shrink, int multimedia, int chunksize, int threadsIndex, int maxTileSizeIndex, OverwriteBehavior overwrite, bool onlyvisible)
TFarmTask (const TFarmTask &)
TFarmTask & operator= (const TFarmTask &)
bool operator== (const TFarmTask &task)
bool operator!= (const TFarmTask &task)
virtual int getTaskCount () const
virtual TFarmTask * getTask (int index)
QString getCommandLine (bool isFarmTask=false) const
void parseCommandLine (QString commandLine)
void loadData (TIStream &is) override
void saveData (TOStream &os) override
const TPersistDeclaration * getDeclaration () const override
Public Member Functions inherited from TPersist
virtual void loadData (TIStream &is)=0
virtual void saveData (TOStream &os)=0
std::string getStreamTag () const
virtual const TPersistDeclaration * getDeclaration () const =0
Additional Inherited Members
Public Types inherited from TFarmTask
typedef QString Id
Public Types inherited from TPersist
typedef TPersist * CreateProc()
Static Public Member Functions inherited from TPersist
static void declare (CreateProc *)
static TPersist * create (const std::string &name)
Public Attributes inherited from TFarmTask
Id m_id
Internal task identifier.
Id m_parentId
Task id of the parent task (if any)
bool m_isComposerTask
QString m_name
User-readable name.
TFilePath m_taskFilePath
Path of the input file affected by the task.
TFilePath m_outputPath
Path of the task's output file.
QString m_callerMachineName
Name of the... caller (submitter?) machine.
int m_priority
Priority value used for scheduling order.
QString m_user
User who submitted the task.
QString m_hostName
Machine on which the task was submitted.
TaskState m_status
The task's status (completed, work in progress... etc)
QString m_server
Server node (name) the task was supplied to.
QDateTime m_submissionDate
QDateTime m_startDate
QDateTime m_completionDate
int m_successfullSteps
int m_failedSteps
int m_stepCount
int m_from
int m_to
int m_step
int m_shrink
Range data.
int m_chunkSize
Sub-tasks size.
int m_multimedia
int m_threadsIndex
int m_maxTileSizeIndex
OverwriteBehavior m_overwrite
bool m_onlyVisible
TFarmPlatform m_platform
Dependencies * m_dependencies
Detailed Description
Constructor & Destructor Documentation
TFarmTaskGroup() [1/5]
TFarmTaskGroup::TFarmTaskGroup ()
: m_imp(new Imp()) {}
TFarmTaskGroup() [2/5]
TFarmTaskGroup::TFarmTaskGroup (const QString & id, const QString & name, const QString & user, const QString & host, int stepCount, int priority, const TFilePath & taskFilePath, const TFilePath & outputPath, int from, int to, int step, int shrink, int multimedia, int chunksize, int threadsIndex, int maxTileSizeIndex)
    : TFarmTask(id, name, true, user, host, stepCount, priority, taskFilePath,
                outputPath, from, to, step, shrink, multimedia, chunksize,
                threadsIndex, maxTileSizeIndex, Overwrite_Off, false)
    , m_imp(new Imp()) {
  int subCount = 0;
  if (chunksize > 0) subCount = tceil((to - from + 1) / (double)chunksize);
  int ra = from;
  if (subCount > 1) {
    for (int i = 1; i <= subCount; ++i) {
      int rb = std::min(ra + chunksize - 1, to);
      try {
        QString subName =
            name + " " + toString(ra, 2, '0') + "-" + toString(rb, 2, '0');
        stepCount = rb - ra + 1;
        TFarmTask *subTask =
            new TFarmTask(id + "." + toString(i, 2, '0'), subName, true, user,
                          host, stepCount, priority, taskFilePath, outputPath,
                          ra, rb, step, shrink, multimedia, chunksize,
                          threadsIndex, maxTileSizeIndex, Overwrite_Off, false);
        subTask->m_parentId = id;
        addTask(subTask);
      } catch (TException &) {
        // TMessage::error(toString(e.getMessage()));
      }
      ra = rb + 1;
    }
  }
}
TFarmTaskGroup() [3/5]
TFarmTaskGroup::TFarmTaskGroup (const QString & id, const QString & name, const QString & user, const QString & host, int stepCount, int priority, const TFilePath & taskFilePath, OverwriteBehavior overwrite, bool onlyvisible)
    : TFarmTask(id, name, false, user, host, stepCount, priority, taskFilePath,
                TFilePath(), 0, 0, 0, 0, 0, 0, 0, 0, overwrite, onlyvisible)
    , m_imp(new Imp()) {}
TFarmTaskGroup() [4/5]
TFarmTaskGroup::TFarmTaskGroup (const QString & id, const QString & name, const QString & cmdline, const QString & user, const QString & host, int stepCount, int priority)
    : TFarmTask(id, name, cmdline, user, host, stepCount, priority)
    , m_imp(new Imp()) {}
TFarmTaskGroup() [5/5]
TFarmTaskGroup::TFarmTaskGroup (const TFarmTaskGroup & src)
    : TFarmTask(src), m_imp(new TFarmTaskGroup::Imp()) {
  int count = src.getTaskCount();
  for (int i = 0; i < count; ++i) {
    TFarmTaskGroup &ssrc = const_cast<TFarmTaskGroup &>(src);
    addTask(new TFarmTask(*ssrc.getTask(i)));
  }
}
~TFarmTaskGroup()
TFarmTaskGroup::~TFarmTaskGroup ()
{}
Member Function Documentation
addTask()
void TFarmTaskGroup::addTask (TFarmTask * task)
{
  m_imp->m_tasks.push_back(task);
}
changeChunkSize()
bool TFarmTaskGroup::changeChunkSize (int chunksize)
{
  m_chunkSize  = chunksize;
  int subCount = tceil((m_to - m_from + 1) / (double)m_chunkSize);
  if (subCount > 1) {
    int ra = m_from;
    for (int i = 1; i <= subCount; ++i) {
      int rb = std::min(ra + m_chunkSize - 1, m_to);
      try {
        QString subName =
            m_name + " " + toString(ra, 2, '0') + "-" + toString(rb, 2, '0');
        TFarmTask *subTask = new TFarmTask(
            m_id + "." + toString(i, 2, '0'), subName, true, m_user, m_hostName,
            rb - ra + 1, m_priority, m_taskFilePath, m_outputPath, ra, rb,
            m_step, m_shrink, m_multimedia, m_chunkSize, m_threadsIndex,
            m_maxTileSizeIndex, Overwrite_Off, false);
        subTask->m_parentId = m_id;
        addTask(subTask);
      } catch (TException &) {
        // TMessage::error(toString(e.getMessage()));
      }
      ra = rb + 1;
    }
  }
  return true;
}
getDeclaration()
const TPersistDeclaration * TFarmTaskGroup::getDeclaration () const override virtual
      This pure virtual method is used to define a global pointer to the
object. This method is overridden with the macro PERSIST_DECLARATION(T).
For example:
class DVAPI TStageObjectTree final : public TPersist {
PERSIST_DECLARATION(TStageObjectTree)
public:
...
Reimplemented from TFarmTask.
{
  return &FarmTaskGroupDeclaration;
}
getTask()
TFarmTask * TFarmTaskGroup::getTask (int index) override virtual
Reimplemented from TFarmTask.
{
  std::vector<TFarmTask *>::iterator it = m_imp->m_tasks.begin();
  std::advance(it, index);
  return it != m_imp->m_tasks.end() ? *it : 0;
}
getTaskCount()
int TFarmTaskGroup::getTaskCount () const override virtual
Reimplemented from TFarmTask.
{ return m_imp->m_tasks.size(); }
loadData()
void TFarmTaskGroup::loadData (TIStream & is) override virtual
 This is a pure virtual function and must be overridden with a method
that implements the object loading from a stream (i.e take the object's features from a formatted data stream). For example the TStageObject class use his implementation to take the values of the parameters that characterizes a stage object as name, coordinates, etc... from a file. is is an input file stream
Reimplemented from TFarmTask.
{
  std::string tagName;
  while (is.matchTag(tagName)) {
    if (tagName == "info") {
      TFarmTask::loadData(is);
    } else if (tagName == "tasks") {
      while (!is.eos()) {
        TPersist *p = 0;
        is >> p;
        TFarmTask *task = dynamic_cast<TFarmTask *>(p);
        if (task) addTask(task);
      }
    } else {
      throw TException(tagName + " : unexpected tag");
    }
    if (!is.matchEndTag()) throw TException(tagName + " : missing end tag");
  }
}
References TIStream::eos(), TFarmTask::loadData(), TIStream::matchEndTag(), and TIStream::matchTag().
removeTask()
void TFarmTaskGroup::removeTask (TFarmTask * task)
{
  std::vector<TFarmTask *>::iterator it =
      std::find(m_imp->m_tasks.begin(), m_imp->m_tasks.end(), task);
  if (it != m_imp->m_tasks.end()) m_imp->m_tasks.erase(it);
}
saveData()
void TFarmTaskGroup::saveData (TOStream & os) override virtual
 This is a pure virtual function and must be overridden with a method
that implements the object saving to a data stream (i.e put the object's features on a formatted data stream). For example the TStageObject class use his implementation to save the values of the parameters that characterizes a stage object as name, coordinates, etc... on a file os is an output file stream.
Reimplemented from TFarmTask.
{
  os.openChild("info");
  TFarmTask::saveData(os);
  os.closeChild();
  os.openChild("tasks");
  std::vector<TFarmTask *>::iterator it = m_imp->m_tasks.begin();
  for (; it != m_imp->m_tasks.end(); ++it) os << *it;
  os.closeChild();
}
References TOStream::closeChild(), TOStream::openChild(), and TFarmTask::saveData().
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/tfarmtask.h
E:/opentoonz/toonz/sources/toonzfarm/tfarm/tfarmtask.cpp