opentoonz: TInbetween::Imp Class Reference
TInbetween::Imp Class Reference
Classes
struct StrokeTransform
Public Member Functions
void computeTransformation ()
void transferColor (const TVectorImageP &destination) const
TVectorImageP tween (double t) const
Imp (const TVectorImageP firstImage, const TVectorImageP lastImage)
Public Attributes
TVectorImageP m_firstImage
TVectorImageP m_lastImage
std::vector< StrokeTransform > m_transformation
Detailed Description
Constructor & Destructor Documentation
Imp()
TInbetween::Imp::Imp (const TVectorImageP firstImage, const TVectorImageP lastImage) inline
      : m_firstImage(firstImage), m_lastImage(lastImage) {
    computeTransformation();
  }
Member Function Documentation
computeTransformation()
void TInbetween::Imp::computeTransformation ()
compute centre of Rotation and Scaling
{
  const UINT samplingPointNumber = 10;
  const UINT bboxSamplingWeight  = samplingPointNumber / 2;
  StrokeTransform transform;
  double cs, sn, totalLen1, totalLen2, constK, constQ, constB, constD, constA;
  UINT cpCount1, cpCount2;
  TPointD stroke1Centroid, stroke2Centroid, stroke1Begin, stroke2Begin,
      stroke1End, stroke2End, versor1, versor2;
  std::vector<TPointD> samplingPoint1(samplingPointNumber),
      samplingPoint2(samplingPointNumber);
  TStroke *stroke1, *stroke2;
  std::vector<double> ratioSampling, weights, subStrokeXScaling,
      subStrokeYScaling;
  UINT strokeCount1 = m_firstImage->getStrokeCount();
  UINT strokeCount2 = m_lastImage->getStrokeCount();
  if (strokeCount1 > strokeCount2) strokeCount1 = strokeCount2;
  m_transformation.clear();
  m_transformation.reserve(strokeCount1);
  const int maxSubSetNum = (strokeCount1) ? 1000 / strokeCount1 : 1;
  UINT j, p;
  for (UINT i = 0; i < strokeCount1; i++) {
    stroke1 = m_firstImage->getStroke(i);
    stroke2 = m_lastImage->getStroke(i);
    // check if the strokes are equal
    cpCount1 = stroke1->getControlPointCount();
    cpCount2 = stroke2->getControlPointCount();
    transform.m_firstStrokeCornerIndexes.clear();
    transform.m_secondStrokeCornerIndexes.clear();
    transform.m_translate              = TPointD();
    transform.m_rotationAndScaleCenter = TPointD();
    transform.m_scaleX                 = 0;
    transform.m_scaleY                 = 0;
    transform.m_rotation               = 0;
    bool isEqual = true;
    if (cpCount1 == cpCount2) {
      for (j = 0; j < cpCount1 && isEqual; j++) {
        isEqual = (stroke1->getControlPoint(j) == stroke2->getControlPoint(j));
      }
    } else
      isEqual = false;
    if (isEqual) {
      transform.m_type = StrokeTransform::EQUAL;
    } else {
      totalLen1 = stroke1->getLength();
      totalLen2 = stroke2->getLength();
      if (totalLen1 == 0 || totalLen2 == 0) {
        if (totalLen1 == 0 && totalLen2 == 0) {
          transform.m_type = StrokeTransform::POINT;
        } else {
          transform.m_inverse = TAffine();
          transform.m_firstStrokeCornerIndexes.resize(2);
          transform.m_firstStrokeCornerIndexes[0] = 0;
          transform.m_firstStrokeCornerIndexes[1] = stroke1->getChunkCount();
          transform.m_secondStrokeCornerIndexes.resize(2);
          transform.m_secondStrokeCornerIndexes[0] = 0;
          transform.m_secondStrokeCornerIndexes[1] = stroke2->getChunkCount();
        }
      } else {
        const double startMinAngle = 30.0;
        std::vector<std::pair<int, double>> angles1, angles2;
        transform.m_type = StrokeTransform::GENERAL;
        double minAngle, maxAngle;
        int minAngle1, maxAngle1, minAngle2, maxAngle2;
        angles1.clear();
        angles2.clear();
        //        TDebugMessage::getStream()<<j<<" stroke1 corner detection";
        //        TDebugMessage::flush();
        detectCorners(stroke1, startMinAngle, angles1, minAngle, maxAngle);
        minAngle1 = (int)minAngle;
        maxAngle1 = (int)maxAngle;
        //        TDebugMessage::getStream()<<j<<" stroke2 corner detection";
        //        TDebugMessage::flush();
        detectCorners(stroke2, startMinAngle, angles2, minAngle, maxAngle);
        minAngle2 = (int)minAngle;
        maxAngle2 = (int)maxAngle;
        if (angles1.empty()) angles2.clear();
        if (angles2.empty()) angles1.clear();
        /*
debugStream.open("c:\\temp\\inbetween.txt", ios_base::out);
debugStream <<"num angoli 1: "<< angles1.size() << endl;
debugStream <<"num angoli 2: "<< angles2.size() << endl;
*/
        double bestValue = (std::numeric_limits<double>::max)();
        if (angles1.size() != angles2.size()) {
          bestValue = (std::numeric_limits<double>::max)();
          //--------------------------------------------------------------------------
          if (isTooComplex(angles1.size(), angles2.size(), maxSubSetNum)) {
            // debugStream <<"is too complex" << endl;
            int firstAngle =
                (int)((angles1.size() < angles2.size()) ? minAngle2
                                                        : minAngle1);
            int lastAngle =
                (int)((angles1.size() < angles2.size()) ? maxAngle1
                                                        : maxAngle2);
            int bestAngle = (int)startMinAngle;
            if ((int)(angles1.size() + angles2.size()) <
                lastAngle - firstAngle + 1) {
              double tempAngle;
              std::vector<double> sortedAngles1, sortedAngles2;
              sortedAngles1.reserve(angles1.size());
              sortedAngles2.reserve(angles2.size());
              for (j = 0; j < angles1.size(); j++) {
                tempAngle = angles1[j].second;
                if (tempAngle >= firstAngle && tempAngle <= lastAngle)
                  sortedAngles1.push_back(tempAngle);
              }
              for (j = 0; j < angles2.size(); j++) {
                tempAngle = angles2[j].second;
                if (tempAngle >= firstAngle && tempAngle <= lastAngle)
                  sortedAngles2.push_back(tempAngle);
              }
              std::vector<double> sortedAngles(sortedAngles1.size() +
                                               sortedAngles2.size());
              std::sort(sortedAngles1.begin(), sortedAngles1.end());
              std::sort(sortedAngles2.begin(), sortedAngles2.end());
              std::merge(sortedAngles1.begin(), sortedAngles1.end(),
                         sortedAngles2.begin(), sortedAngles2.end(),
                         sortedAngles.begin());
              for (j = 0; j < sortedAngles.size(); j++) {
                int numAng1 = angleNumber(angles1, sortedAngles[j]);
                int numAng2 = angleNumber(angles2, sortedAngles[j]);
                double val  = (numAng1 == numAng2)
                                 ? 0
                                 : fabs((float)(numAng1 - numAng2)) /
                                       (numAng1 + numAng2);
                if (val < bestValue) {
                  bestValue = val;
                  bestAngle = (int)(sortedAngles[j]);
                  if (bestValue == 0 ||
                      !isTooComplex(numAng1, numAng2, maxSubSetNum))
                    break;
                }
              }
            } else  //-----------------------------------------------------
            {
              for (int angle = firstAngle; angle <= lastAngle; angle++) {
                int numAng1 = angleNumber(angles1, angle);
                int numAng2 = angleNumber(angles2, angle);
                double val  = (numAng1 == numAng2)
                                 ? 0
                                 : fabs((float)(numAng1 - numAng2)) /
                                       (numAng1 + numAng2);
                if (val < bestValue) {
                  bestValue = val;
                  bestAngle = angle;
                  if (bestValue == 0 ||
                      !isTooComplex(numAng1, numAng2, maxSubSetNum))
                    break;
                }
              }
            }
            eraseSmallAngles(angles1, bestAngle);
            eraseSmallAngles(angles2, bestAngle);
            /*
debugStream <<"bestAngle: "<< bestAngle << endl;
debugStream <<"num angoli 1: "<< angles1.size() << endl;
debugStream <<"num angoli 2: "<< angles2.size() << endl;
*/
          }
          //--------------------------------------------------------------------------
          bestValue = (std::numeric_limits<double>::max)();
          if (angles1.size() == angles2.size()) {
            transform.m_firstStrokeCornerIndexes.push_back(0);
            for (j = 0; j < angles1.size(); j++)
              transform.m_firstStrokeCornerIndexes.push_back(angles1[j].first);
            transform.m_firstStrokeCornerIndexes.push_back(
                stroke1->getChunkCount());
            transform.m_secondStrokeCornerIndexes.push_back(0);
            for (j = 0; j < angles2.size(); j++)
              transform.m_secondStrokeCornerIndexes.push_back(angles2[j].first);
            transform.m_secondStrokeCornerIndexes.push_back(
                stroke2->getChunkCount());
          } else {
            if (isTooComplex(angles1.size(), angles2.size(), maxSubSetNum)) {
              if (angles1.size() > angles2.size()) {
                transform.m_firstStrokeCornerIndexes.resize(angles2.size());
                trivialSolution(stroke1, stroke2, angles1, angles2,
                                transform.m_firstStrokeCornerIndexes);
                transform.m_firstStrokeCornerIndexes.insert(
                    transform.m_firstStrokeCornerIndexes.begin(), 0);
                transform.m_firstStrokeCornerIndexes.push_back(
                    stroke1->getChunkCount());
                transform.m_secondStrokeCornerIndexes.push_back(0);
                for (j = 0; j < angles2.size(); j++)
                  transform.m_secondStrokeCornerIndexes.push_back(
                      angles2[j].first);
                transform.m_secondStrokeCornerIndexes.push_back(
                    stroke2->getChunkCount());
              } else {
                transform.m_firstStrokeCornerIndexes.push_back(0);
                for (j = 0; j < angles1.size(); j++)
                  transform.m_firstStrokeCornerIndexes.push_back(
                      angles1[j].first);
                transform.m_firstStrokeCornerIndexes.push_back(
                    stroke1->getChunkCount());
                transform.m_secondStrokeCornerIndexes.resize(angles1.size());
                trivialSolution(stroke2, stroke1, angles2, angles1,
                                transform.m_secondStrokeCornerIndexes);
                transform.m_secondStrokeCornerIndexes.insert(
                    transform.m_secondStrokeCornerIndexes.begin(), 0);
                transform.m_secondStrokeCornerIndexes.push_back(
                    stroke2->getChunkCount());
              }
            } else {
              if (angles1.size() > angles2.size()) {
                transform.m_firstStrokeCornerIndexes.resize(angles2.size());
                findBestSolution(stroke1, stroke2, angles1, angles2, bestValue,
                                 transform.m_firstStrokeCornerIndexes);
                transform.m_firstStrokeCornerIndexes.insert(
                    transform.m_firstStrokeCornerIndexes.begin(), 0);
                transform.m_firstStrokeCornerIndexes.push_back(
                    stroke1->getChunkCount());
                transform.m_secondStrokeCornerIndexes.push_back(0);
                for (j = 0; j < angles2.size(); j++)
                  transform.m_secondStrokeCornerIndexes.push_back(
                      angles2[j].first);
                transform.m_secondStrokeCornerIndexes.push_back(
                    stroke2->getChunkCount());
              } else {
                transform.m_firstStrokeCornerIndexes.push_back(0);
                for (j = 0; j < angles1.size(); j++)
                  transform.m_firstStrokeCornerIndexes.push_back(
                      angles1[j].first);
                transform.m_firstStrokeCornerIndexes.push_back(
                    stroke1->getChunkCount());
                transform.m_secondStrokeCornerIndexes.resize(angles1.size());
                findBestSolution(stroke2, stroke1, angles2, angles1, bestValue,
                                 transform.m_secondStrokeCornerIndexes);
                transform.m_secondStrokeCornerIndexes.insert(
                    transform.m_secondStrokeCornerIndexes.begin(), 0);
                transform.m_secondStrokeCornerIndexes.push_back(
                    stroke2->getChunkCount());
              }
            }
          }
        } else {
          transform.m_firstStrokeCornerIndexes.push_back(0);
          for (j = 0; j < angles1.size(); j++)
            transform.m_firstStrokeCornerIndexes.push_back(angles1[j].first);
          transform.m_firstStrokeCornerIndexes.push_back(
              stroke1->getChunkCount());
          transform.m_secondStrokeCornerIndexes.push_back(0);
          for (j = 0; j < angles2.size(); j++)
            transform.m_secondStrokeCornerIndexes.push_back(angles2[j].first);
          transform.m_secondStrokeCornerIndexes.push_back(
              stroke2->getChunkCount());
        }
        UINT cornerSize = transform.m_firstStrokeCornerIndexes.size();
        assert(cornerSize == transform.m_secondStrokeCornerIndexes.size());
        assert(cornerSize >= 2);
        double totalRadRotation = 0;
        TStroke *subStroke1 = 0;
        TStroke *subStroke2 = 0;
        stroke1Centroid = stroke1->getCentroid();
        stroke2Centroid = stroke2->getCentroid();
#ifdef _DEBUG
        assert(transform.m_firstStrokeCornerIndexes[0] == 0);
        assert(transform.m_secondStrokeCornerIndexes[0] == 0);
        assert(transform.m_firstStrokeCornerIndexes[cornerSize - 1] ==
               stroke1->getChunkCount());
        assert(transform.m_secondStrokeCornerIndexes[cornerSize - 1] ==
               stroke2->getChunkCount());
        for (j = 0; j < cornerSize - 1; j++) {
          assert(transform.m_firstStrokeCornerIndexes[j] <
                 transform.m_firstStrokeCornerIndexes[j + 1]);
          assert(transform.m_secondStrokeCornerIndexes[j] <
                 transform.m_secondStrokeCornerIndexes[j + 1]);
          assert(transform.m_firstStrokeCornerIndexes[j] <
                 stroke1->getChunkCount());
          assert(transform.m_secondStrokeCornerIndexes[j] <
                 stroke2->getChunkCount());
        }
#endif
        for (j = 0; j < cornerSize - 1; j++) {
          subStroke1 = extract(stroke1, transform.m_firstStrokeCornerIndexes[j],
                               transform.m_firstStrokeCornerIndexes[j + 1] - 1);
          sample(subStroke1, samplingPointNumber, samplingPoint1);
          subStroke2 =
              extract(stroke2, transform.m_secondStrokeCornerIndexes[j],
                      transform.m_secondStrokeCornerIndexes[j + 1] - 1);
          sample(subStroke2, samplingPointNumber, samplingPoint2);
          ratioSampling.clear();
          ratioSampling.reserve(samplingPointNumber);
          weights.clear();
          weights.reserve(samplingPointNumber);
          TPointD pOld, pNew;
          // double totalW=0;
          for (p = 0; p < samplingPointNumber; p++) {
            pOld = samplingPoint1[p];
            pNew = samplingPoint2[p];
            if (pOld == stroke1Centroid) continue;
            if (pNew == stroke2Centroid) continue;
            versor1 = normalize(pOld - stroke1Centroid);
            versor2 = normalize(pNew - stroke2Centroid);
            weights.push_back(tdistance(pOld, stroke1Centroid) +
                              tdistance(pNew, stroke2Centroid));
            cs       = versor1 * versor2;
            sn       = cross(versor1, versor2);
            double v = atan2(sn, cs);
            ratioSampling.push_back(v);
          }
          delete subStroke1;
          delete subStroke2;
          subStroke1 = 0;
          subStroke2 = 0;
          double radRotation = weightedAverage(ratioSampling, weights);
          totalRadRotation += radRotation;
        }
        totalRadRotation /= (cornerSize - 1);
        transform.m_rotation = totalRadRotation * M_180_PI;
        if (isAlmostZero(transform.m_rotation, 2)) {
          transform.m_rotation = 0.0;
          totalRadRotation     = 0.0;
        }
#ifdef _DEBUG
//        TDebugMessage::getStream()<<"rotation "<< transform.m_rotation;
//        TDebugMessage::flush();
#endif
        if (transform.m_rotation == 0.0) {
          subStrokeXScaling.clear();
          subStrokeXScaling.reserve(cornerSize - 1);
          subStrokeYScaling.clear();
          subStrokeYScaling.reserve(cornerSize - 1);
          for (j = 0; j < cornerSize - 1; j++) {
            subStroke1 =
                extract(stroke1, transform.m_firstStrokeCornerIndexes[j],
                        transform.m_firstStrokeCornerIndexes[j + 1] - 1);
            sample(subStroke1, samplingPointNumber, samplingPoint1);
            subStroke2 =
                extract(stroke2, transform.m_secondStrokeCornerIndexes[j],
                        transform.m_secondStrokeCornerIndexes[j + 1] - 1);
            sample(subStroke2, samplingPointNumber, samplingPoint2);
            ratioSampling.clear();
            ratioSampling.reserve(samplingPointNumber + bboxSamplingWeight);
            double appX, appY;
            TPointD appPoint;
            double bboxXMin, bboxYMin, bboxXMax, bboxYMax;
            bboxXMin = bboxYMin = (std::numeric_limits<double>::max)();
            bboxXMax = bboxYMax = -(std::numeric_limits<double>::max)();
            int h;
            for (h = 0; h < subStroke1->getControlPointCount(); ++h) {
              appPoint = subStroke1->getControlPoint(h);
              if (appPoint.x < bboxXMin) bboxXMin = appPoint.x;
              if (appPoint.x > bboxXMax) bboxXMax = appPoint.x;
              if (appPoint.y < bboxYMin) bboxYMin = appPoint.y;
              if (appPoint.y > bboxYMax) bboxYMax = appPoint.y;
            }
            appX = bboxXMax - bboxXMin;
            appY = bboxYMax - bboxYMin;
            if (appX) {
              bboxXMin = (std::numeric_limits<double>::max)();
              bboxXMax = -(std::numeric_limits<double>::max)();
              for (h = 0; h < subStroke2->getControlPointCount(); ++h) {
                appPoint = subStroke2->getControlPoint(h);
                if (appPoint.x < bboxXMin) bboxXMin = appPoint.x;
                if (appPoint.x > bboxXMax) bboxXMax = appPoint.x;
              }
              appX = (isAlmostZero(appX, 1e-01)) ? -1
                                                 : (bboxXMax - bboxXMin) / appX;
              for (UINT tms = 0; tms < bboxSamplingWeight && appX >= 0; tms++)
                ratioSampling.push_back(appX);
              for (p = 0; p < samplingPointNumber; p++) {
                appX = fabs(samplingPoint1[p].x - stroke1Centroid.x);
                if (appX)
                  ratioSampling.push_back(
                      fabs(samplingPoint2[p].x - stroke2Centroid.x) / appX);
              }
              if (!ratioSampling.empty()) {
                subStrokeXScaling.push_back(average(ratioSampling));
              }
            }
            ratioSampling.clear();
            ratioSampling.reserve(samplingPointNumber + bboxSamplingWeight);
            if (appY) {
              bboxYMin = (std::numeric_limits<double>::max)();
              bboxYMax = -(std::numeric_limits<double>::max)();
              for (h = 0; h < subStroke2->getControlPointCount(); ++h) {
                appPoint = subStroke2->getControlPoint(h);
                if (appPoint.y < bboxYMin) bboxYMin = appPoint.y;
                if (appPoint.y > bboxYMax) bboxYMax = appPoint.y;
              }
              appY = (isAlmostZero(appY, 1e-01)) ? -1
                                                 : (bboxYMax - bboxYMin) / appY;
              for (UINT tms = 0; tms < bboxSamplingWeight && appY >= 0; tms++)
                ratioSampling.push_back(appY);
              for (p = 0; p < samplingPointNumber; p++) {
                appY = fabs(samplingPoint1[p].y - stroke1Centroid.y);
                if (appY)
                  ratioSampling.push_back(
                      fabs(samplingPoint2[p].y - stroke2Centroid.y) / appY);
              }
              if (!ratioSampling.empty()) {
                subStrokeYScaling.push_back(average(ratioSampling));
              }
            }
            delete subStroke1;
            delete subStroke2;
            subStroke1 = 0;
            subStroke2 = 0;
          }
          if (subStrokeXScaling.empty()) {
            transform.m_scaleX = 1.0;
          } else {
            transform.m_scaleX = average(subStrokeXScaling);
            if (isAlmostZero(transform.m_scaleX - 1.0))
              transform.m_scaleX = 1.0;
          }
          if (subStrokeYScaling.empty()) {
            transform.m_scaleY = 1.0;
          } else {
            transform.m_scaleY = average(subStrokeYScaling);
            if (isAlmostZero(transform.m_scaleY - 1.0))
              transform.m_scaleY = 1.0;
          }
          /*
#ifdef _DEBUG
TDebugMessage::getStream()<<"x scale "<< transform.m_scaleX ;
TDebugMessage::flush();
TDebugMessage::getStream()<<"y scale "<< transform.m_scaleY ;
TDebugMessage::flush();
#endif
*/
        } else {
          subStrokeXScaling.clear();
          subStrokeXScaling.reserve(cornerSize - 1);
          for (j = 0; j < cornerSize - 1; j++) {
            subStroke1 =
                extract(stroke1, transform.m_firstStrokeCornerIndexes[j],
                        transform.m_firstStrokeCornerIndexes[j + 1] - 1);
            sample(subStroke1, samplingPointNumber, samplingPoint1);
            subStroke2 =
                extract(stroke2, transform.m_secondStrokeCornerIndexes[j],
                        transform.m_secondStrokeCornerIndexes[j + 1] - 1);
            sample(subStroke2, samplingPointNumber, samplingPoint2);
            ratioSampling.clear();
            ratioSampling.reserve(samplingPointNumber + bboxSamplingWeight);
            TRectD bbox1 = subStroke1->getBBox();
            double app   = tdistance2(bbox1.getP00(), bbox1.getP11());
            if (app) {
              TRectD bbox2 =
                  TRotation(transform.m_rotation).inv() * subStroke2->getBBox();
              app = sqrt(tdistance2(bbox2.getP00(), bbox2.getP11()) / app);
              for (UINT tms = 0; tms < bboxSamplingWeight; tms++)
                ratioSampling.push_back(app);
              double app;
              for (p = 0; p < samplingPointNumber; p++) {
                app = tdistance(samplingPoint1[p], stroke1Centroid);
                if (app) {
                  ratioSampling.push_back(
                      tdistance(samplingPoint2[p], stroke2Centroid) / app);
                }
              }
            }
            if (!ratioSampling.empty()) {
              subStrokeXScaling.push_back(average(ratioSampling));
            }
            delete subStroke1;
            delete subStroke2;
            subStroke1 = 0;
            subStroke2 = 0;
          }
          if (subStrokeXScaling.empty()) {
            transform.m_scaleX = transform.m_scaleY = 1.0;
          } else {
            transform.m_scaleX = transform.m_scaleY =
                average(subStrokeXScaling);
            if (isAlmostZero(transform.m_scaleX - 1.0, 0.00001))
              transform.m_scaleX = transform.m_scaleY = 1.0;
          }
          /*
#ifdef _DEBUG
TDebugMessage::getStream()<<"scale "<< transform.m_scaleX ;
TDebugMessage::flush();
#endif
*/
        }
        std::vector<TPointD> vpOld(cornerSize), vpNew(cornerSize);
        TPointD pOld, pNew;
        for (j = 0; j < cornerSize - 1; j++) {
          vpOld[j] = stroke1->getChunk(transform.m_firstStrokeCornerIndexes[j])
                         ->getP0();
          vpNew[j] = stroke2->getChunk(transform.m_secondStrokeCornerIndexes[j])
                         ->getP0();
        }
        vpOld[j] = stroke1->getControlPoint(stroke1->getControlPointCount());
        vpNew[j] = stroke2->getControlPoint(stroke2->getControlPointCount());
        if (transform.m_rotation == 0.0) {
          if (transform.m_scaleX == 1.0 && transform.m_scaleY == 1.0) {
            transform.m_translate = stroke2Centroid - stroke1Centroid;
            transform.m_rotationAndScaleCenter = TPointD();
          } else {
            if (transform.m_scaleX == 1.0) {
              transform.m_rotationAndScaleCenter.x = 0;
              transform.m_translate.x              = 0;
              for (j = 0; j < cornerSize; j++) {
                transform.m_translate.x += vpNew[j].x - vpOld[j].x;
              }
              transform.m_translate.x = transform.m_translate.x / cornerSize;
            } else {
              transform.m_rotationAndScaleCenter.x = 0;
              for (j = 0; j < cornerSize; j++) {
                pOld = vpOld[j];
                pNew = vpNew[j];
                transform.m_rotationAndScaleCenter.x +=
                    (transform.m_scaleX * pOld.x - pNew.x) /
                    (transform.m_scaleX - 1.0);
              }
              transform.m_rotationAndScaleCenter.x =
                  transform.m_rotationAndScaleCenter.x / cornerSize;
              transform.m_translate.x = 0;
            }
            if (transform.m_scaleY == 1.0) {
              transform.m_rotationAndScaleCenter.y = 0;
              transform.m_translate.y              = 0;
              for (j = 0; j < cornerSize; j++) {
                transform.m_translate.y += vpNew[j].y - vpOld[j].y;
              }
              transform.m_translate.y = transform.m_translate.y / cornerSize;
            } else {
              transform.m_rotationAndScaleCenter.y = 0;
              for (j = 0; j < cornerSize; j++) {
                pOld = vpOld[j];
                pNew = vpNew[j];
                transform.m_rotationAndScaleCenter.y +=
                    (transform.m_scaleY * pOld.y - pNew.y) /
                    (transform.m_scaleY - 1.0);
              }
              transform.m_rotationAndScaleCenter.y =
                  transform.m_rotationAndScaleCenter.y / cornerSize;
              transform.m_translate.y = 0;
            }
          }
        } else {
          assert(transform.m_scaleX == transform.m_scaleY);
          cs = transform.m_scaleX * cos(totalRadRotation);
          sn = transform.m_scaleX * sin(totalRadRotation);
          // scelgo punti da usare come vincolo, per ottenere la translazione,
          // dato un centro di rotazione
          // dato il punto pOld e pNew si calcola analiticamnete il punto di
          // rotazione e scala
          // che minimizza la traslazione aggiuntiva e la traslazione stessa
          for (j = 0; j < cornerSize; j++) {
            pOld   = vpOld[j];
            pNew   = vpNew[j];
            constK = pNew.x - cs * pOld.x + sn * pOld.y;
            constQ = pNew.y - sn * pOld.x - cs * pOld.y;
            constB = 2 * (constK * (cs - 1.) + sn * constQ);
            constD = 2 * (constQ * (cs - 1.) - sn * constK);
            constA = transform.m_scaleX * transform.m_scaleX + 1 - 2 * cs;
            assert(constA > 0);
            constA = 1.0 / (2 * constA);
            transform.m_rotationAndScaleCenter.x += -constB * constA;
            transform.m_rotationAndScaleCenter.y += -constD * constA;
          }
          transform.m_rotationAndScaleCenter =
              transform.m_rotationAndScaleCenter * (1.0 / (double)cornerSize);
          transform.m_translate.x =
              (cs - 1.0) * transform.m_rotationAndScaleCenter.x -
              sn * transform.m_rotationAndScaleCenter.y + constK;
          transform.m_translate.y =
              sn * transform.m_rotationAndScaleCenter.x +
              (cs - 1.0) * transform.m_rotationAndScaleCenter.y + constQ;
        }
        transform.m_inverse = (TTranslation(transform.m_translate) *
                               TScale(transform.m_rotationAndScaleCenter,
                                      transform.m_scaleX, transform.m_scaleY) *
                               TRotation(transform.m_rotationAndScaleCenter,
                                         transform.m_rotation))
                                  .inv();
        // debugStream.close();
      }  // end if !isPoint
    }  // end if !isEqual
    m_transformation.push_back(transform);
  }  // end for each stroke
}
References TStroke::getBBox(), TStroke::getChunk(), TStroke::getChunkCount(), TStroke::getControlPoint(), TStroke::getControlPointCount(), TStroke::getLength(), TQuadratic::getP0(), and TAffine::inv().
transferColor()
void TInbetween::Imp::transferColor (const TVectorImageP & destination) const
{
  const TVectorImageP &original = m_firstImage;
  destination->setPalette(original->getPalette());
  destination->findRegions();
  if (destination->getRegionCount()) {
    UINT strokeCount1 = original->getStrokeCount();
    UINT strokeCount2 = destination->getStrokeCount();
    if (strokeCount1 > strokeCount2) strokeCount1 = strokeCount2;
    for (UINT i = 0; i < strokeCount1; i++) {
      TVectorImage::transferStrokeColors(original, i, destination, i);
    }
  }
}
tween()
TVectorImageP TInbetween::Imp::tween (double t) const
{
  const double step             = 5.0;
  const double interpolateError = 1.0;
  TVectorImageP vi = new TVectorImage;
  UINT strokeCount1 = m_firstImage->getStrokeCount();
  UINT strokeCount2 = m_lastImage->getStrokeCount();
  vi->setPalette(m_firstImage->getPalette());
  if (strokeCount1 > strokeCount2) strokeCount1 = strokeCount2;
  assert(m_transformation.size() == strokeCount1);
  double totalLen1, totalLen2, len1, len2, step1, step2;
  std::vector<TThickPoint> points;
  TStroke *stroke1, *stroke2, *subStroke1, *subStroke2, *stroke;
  TAffine mt, invMatrix;
  TThickPoint point2, finalPoint;
  UINT i, j, cp, cpSize;
  for (i = 0; i < strokeCount1; i++) {
    stroke1 = m_firstImage->getStroke(i);
    stroke2 = m_lastImage->getStroke(i);
    if (m_transformation[i].m_type == StrokeTransform::EQUAL) {
      stroke = new TStroke(*stroke1);
    } else {
      points.clear();
      totalLen1 = stroke1->getLength();
      totalLen2 = stroke2->getLength();
      ;
      if (stroke1->getControlPointCount() == stroke2->getControlPointCount() &&
          stroke1->isSelfLoop() && stroke2->isSelfLoop()) {
        for (int i = 0; i < stroke1->getControlPointCount(); i++) {
          TThickPoint p0 = stroke1->getControlPoint(i);
          TThickPoint p1 = stroke2->getControlPoint(i);
          points.push_back(p0 * (1 - t) + p1 * t);
        }
        stroke = new TStroke(points);
      } else if (m_transformation[i].m_type == StrokeTransform::POINT) {
        TThickPoint pOld = stroke1->getThickPointAtLength(0.5 * totalLen1);
        TThickPoint pNew = stroke2->getThickPointAtLength(0.5 * totalLen2);
        points.push_back(pOld * (1 - t) + pNew * t);
        points.push_back(points[0]);
        points.push_back(points[0]);
        stroke = new TStroke(points);
      } else {
        mt = (m_transformation[i].m_inverse.isIdentity())
                 ? TAffine()
                 : TTranslation(m_transformation[i].m_translate * t) *
                       TScale(m_transformation[i].m_rotationAndScaleCenter,
                              (1 - t) + t * m_transformation[i].m_scaleX,
                              (1 - t) + t * m_transformation[i].m_scaleY) *
                       TRotation(m_transformation[i].m_rotationAndScaleCenter,
                                 m_transformation[i].m_rotation * t);
        UINT cornerSize = m_transformation[i].m_firstStrokeCornerIndexes.size();
        assert(cornerSize ==
               m_transformation[i].m_secondStrokeCornerIndexes.size());
        if (cornerSize > m_transformation[i].m_secondStrokeCornerIndexes.size())
          cornerSize = m_transformation[i].m_secondStrokeCornerIndexes.size();
        assert(cornerSize >= 2);
        std::vector<TThickPoint> controlPoints;
        // if not m_transformation[i].m_findCorners => detect corner return
        // different size =>cornerSize==2
        // assert(!m_transformation[i].m_findCorners || cornerSize==2);
        for (j = 0; j < cornerSize - 1; j++) {
          points.clear();
          subStroke1 = extract(
              stroke1, m_transformation[i].m_firstStrokeCornerIndexes[j],
              m_transformation[i].m_firstStrokeCornerIndexes[j + 1] - 1);
          subStroke2 = extract(
              stroke2, m_transformation[i].m_secondStrokeCornerIndexes[j],
              m_transformation[i].m_secondStrokeCornerIndexes[j + 1] - 1);
          totalLen1 = subStroke1->getLength();
          totalLen2 = subStroke2->getLength();
          if (totalLen1 > totalLen2) {
            step1 = step;
            step2 = (totalLen2 / totalLen1) * step;
          } else {
            step1 = (totalLen1 / totalLen2) * step;
            step2 = step;
          }
          len1 = 0;
          len2 = 0;
          while (len1 <= totalLen1 && len2 <= totalLen2) {
            point2 = subStroke2->getThickPointAtLength(len2);
            point2 = TThickPoint(m_transformation[i].m_inverse *
                                     subStroke2->getThickPointAtLength(len2),
                                 point2.thick);
            finalPoint =
                subStroke1->getThickPointAtLength(len1) * (1 - t) + t * point2;
            points.push_back(TThickPoint(mt * (finalPoint), finalPoint.thick));
            len1 += step1;
            len2 += step2;
          }
          point2     = subStroke2->getThickPointAtLength(totalLen2);
          point2     = TThickPoint(m_transformation[i].m_inverse *
                                   subStroke2->getThickPointAtLength(totalLen2),
                               point2.thick);
          finalPoint = subStroke1->getThickPointAtLength(totalLen1) * (1 - t) +
                       t * point2;
          points.push_back(TThickPoint(mt * (finalPoint), finalPoint.thick));
          stroke = TStroke::interpolate(points, interpolateError, false
                                        /*m_transformation[i].m_findCorners*/);
          if (j == 0)
            controlPoints.push_back(stroke->getControlPoint(0));
          else
            controlPoints.back() =
                (controlPoints.back() + stroke->getControlPoint(0)) * 0.5;
          cpSize = stroke->getControlPointCount();
          for (cp = 1; cp < cpSize; cp++) {
            controlPoints.push_back(stroke->getControlPoint(cp));
          }
          delete subStroke1;
          delete subStroke2;
          delete stroke;
          subStroke1 = 0;
          subStroke2 = 0;
          stroke     = 0;
        }
        stroke = new TStroke(controlPoints);
      }
    }
    if (stroke1->isSelfLoop() && stroke2->isSelfLoop()) stroke->setSelfLoop();
    stroke->setStyle(stroke1->getStyle());
    stroke->outlineOptions() = stroke1->outlineOptions();
    VIStroke *vs =
        new VIStroke(stroke, m_firstImage->getVIStroke(i)->m_groupId);
    vi->m_imp->m_strokes.push_back(vs);
  }  // end for each stroke
  if (m_firstImage->isComputedRegionAlmostOnce()) transferColor(vi);
  return vi;
}
Member Data Documentation
m_firstImage
TVectorImageP TInbetween::Imp::m_firstImage
m_lastImage
TVectorImageP TInbetween::Imp::m_lastImage
m_transformation
std::vector<StrokeTransform> TInbetween::Imp::m_transformation
The documentation for this class was generated from the following file:
E:/opentoonz/toonz/sources/common/tvrender/tinbetween.cpp