opentoonz: ToolHandle Class Reference
ToolHandle Class Reference final
Public Slots
void onImageChanged (TImage::Type type)
void updateMatrix ()
Signals
void toolComboBoxListChanged (std::string)
void toolSwitched ()
void toolChanged ()
void toolEditingFinished ()
void toolCursorTypeChanged ()
Public Member Functions
TTool * getTool () const
void setTool (TTool *tool)
void setTool (QString name)
void setTargetType (int targetType)
void storeTool ()
void restoreTool ()
void setPseudoTool (QString name)
void unsetPseudoTool ()
void setToolBusy (bool value)
bool isToolBusy ()
void notifyToolChanged ()
void notifyToolCursorTypeChanged ()
void notifyToolComboBoxListChanged (std::string id)
Detailed Description
Constructor & Destructor Documentation
ToolHandle()
ToolHandle::ToolHandle ()
    : m_tool(0)
    , m_toolName("")
    , m_toolTargetType(TTool::NoTarget)
    , m_storedToolName("")
    , m_toolIsBusy(false) {}
~ToolHandle()
ToolHandle::~ToolHandle ()
{}
Member Function Documentation
getTool()
TTool * ToolHandle::getTool () const
{ return m_tool; }
isToolBusy()
bool ToolHandle::isToolBusy () inline
{ return m_toolIsBusy; }
notifyToolChanged()
void ToolHandle::notifyToolChanged () inline
Notify tool parameters change (out of toolOption bar).
{ emit toolChanged(); }
Referenced by FillTool::onImageChanged(), RasterSelectionTool::onImageChanged(), StylePickerTool::onImageChanged(), FillTool::onPropertyChanged(), FullColorBrushTool::onPropertyChanged(), PaintBrushTool::onPropertyChanged(), StylePickerTool::onPropertyChanged(), ToonzRasterBrushTool::onPropertyChanged(), and ToonzVectorBrushTool::onPropertyChanged().
notifyToolComboBoxListChanged()
void ToolHandle::notifyToolComboBoxListChanged (std::string id) inline
{
    emit toolComboBoxListChanged(id);
  }
notifyToolCursorTypeChanged()
void ToolHandle::notifyToolCursorTypeChanged () inline
{ emit toolCursorTypeChanged(); }
onImageChanged
void ToolHandle::onImageChanged (TImage::Type type) slot
{
  TTool::ToolTargetType targetType = TTool::NoTarget;
  switch (imageType) {
  case TImage::RASTER:
    targetType = TTool::RasterImage;
    break;
  case TImage::TOONZ_RASTER:
    targetType = TTool::ToonzImage;
    break;
  case TImage::VECTOR:
  default:
    targetType = TTool::VectorImage;
    break;
  case TImage::MESH:
    targetType = TTool::MeshImage;
    break;
  }
  if (targetType != m_toolTargetType) {
    m_toolTargetType = targetType;
    setTool(m_toolName);
  }
  if (m_tool) {
    m_tool->updateMatrix();
    m_tool->onImageChanged();
  }
}
restoreTool()
void ToolHandle::restoreTool ()
{
  // qDebug() << m_storedToolTime.elapsed();
  if (m_storedToolName != m_toolName && m_storedToolName != "" &&
      m_storedToolTime.elapsed() >
          Preferences::instance()->getTempToolSwitchTimer()) {
    setTool(m_storedToolName);
  }
}
setPseudoTool()
void ToolHandle::setPseudoTool (QString name)
{
  QString oldToolName = m_oldToolName;
  setTool(name);
  m_oldToolName = oldToolName;
}
setTool()
void ToolHandle::setTool (QString name)
{
  m_oldToolName = m_toolName = name;
  TTool *tool = TTool::getTool(m_toolName.toStdString(),
                               (TTool::ToolTargetType)m_toolTargetType);
  if (tool == m_tool) return;
  if (m_tool) m_tool->onDeactivate();
  // Camera test uses the automatically activated CameraTestTool
  if (name != "T_CameraTest" && CameraTestCheck::instance()->isEnabled())
    CameraTestCheck::instance()->setIsEnabled(false);
  m_tool = tool;
  if (name != T_Hand && CleanupPreviewCheck::instance()->isEnabled()) {
    // When using a tool, you have to exit from cleanup preview mode
    QAction *act = CommandManager::instance()->getAction("MI_CleanupPreview");
    if (act) CommandManager::instance()->execute(act);
  }
  if (m_tool)  // Should always enter
  {
    m_tool->onActivate();
    emit toolSwitched();
  }
}
setToolBusy()
void ToolHandle::setToolBusy (bool value)
{
  m_toolIsBusy = value;
  if (!m_toolIsBusy) emit toolEditingFinished();
}
storeTool()
void ToolHandle::storeTool ()
{
  m_storedToolName = m_toolName;
  m_storedToolTime.start();
}
unsetPseudoTool()
void ToolHandle::unsetPseudoTool ()
{
  if (m_toolName != m_oldToolName) setTool(m_oldToolName);
}
updateMatrix
void ToolHandle::updateMatrix () slot
{
  if (m_tool) m_tool->updateMatrix();
}
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/tools/toolhandle.h
E:/opentoonz/toonz/sources/tnztools/toolhandle.cpp