opentoonz: TApp Class Reference
TApp Class Reference final
This is the instance of the main application.
#include <tapp.h>
Signals
void tabletLeft ()
void activeViewerChanged ()
Public Member Functions
TSceneHandle * getCurrentScene () const override
TXsheetHandle * getCurrentXsheet () const override
TFrameHandle * getCurrentFrame () const override
TColumnHandle * getCurrentColumn () const override
TXshLevelHandle * getCurrentLevel () const override
ToolHandle * getCurrentTool () const override
TObjectHandle * getCurrentObject () const override
TSelectionHandle * getCurrentSelection () const override
TOnionSkinMaskHandle * getCurrentOnionSkin () const override
TFxHandle * getCurrentFx () const override
PaletteController * getPaletteController () const override
TPaletteHandle * getCurrentPalette () const override
TColorStyle * getCurrentLevelStyle () const override
int getCurrentLevelStyleIndex () const override
void setCurrentLevelStyleIndex (int index, bool forceUpdate=false) override
void setMainWindow (QMainWindow *mainWindow)
QMainWindow * getMainWindow () const
TMainWindow * getCurrentRoom () const
int getCurrentImageType ()
void init ()
QString getCurrentRoomName () const
void setActiveViewer (SceneViewer *viewer)
SceneViewer * getActiveViewer () const
bool isApplicationStarting ()
bool isPenCloseToTablet () const
void writeSettings ()
void setCurrentXsheetViewer (XsheetViewer *viewer)
XsheetViewer * getCurrentXsheetViewer () const
virtual TFrameHandle * getCurrentFrame () const =0
virtual TXshLevelHandle * getCurrentLevel () const =0
virtual TXsheetHandle * getCurrentXsheet () const =0
virtual TObjectHandle * getCurrentObject () const =0
virtual TColumnHandle * getCurrentColumn () const =0
virtual TSceneHandle * getCurrentScene () const =0
virtual ToolHandle * getCurrentTool () const =0
virtual TSelectionHandle * getCurrentSelection () const =0
virtual TOnionSkinMaskHandle * getCurrentOnionSkin () const =0
virtual TPaletteHandle * getCurrentPalette () const =0
virtual TFxHandle * getCurrentFx () const =0
virtual PaletteController * getPaletteController () const =0
virtual TColorStyle * getCurrentLevelStyle () const =0
virtual int getCurrentLevelStyleIndex () const =0
virtual void setCurrentLevelStyleIndex (int index, bool forceUpdate=false)=0
Static Public Member Functions
static TApp * instance ()
Protected Slots
void onXsheetChanged ()
void onSceneSwitched ()
void onXsheetSwitched ()
void onXsheetSoundChanged ()
void onFrameSwitched ()
void onFxSwitched ()
void onColumnIndexSwitched ()
void onXshLevelSwitched (TXshLevel *)
void onXshLevelChanged ()
void onObjectSwitched ()
void onSplineChanged ()
void onSceneChanged ()
void onImageChanged ()
void onPaletteChanged ()
void onLevelColorStyleChanged ()
void onLevelColorStyleSwitched ()
void autosave ()
void onToolEditingFinished ()
void onStartAutoSave ()
void onStopAutoSave ()
Protected Member Functions
bool eventFilter (QObject *obj, QEvent *event) override
Detailed Description
This is the instance of the main application.
This class is a singleton and is used to initialize the main application window. It defines the basic signals used in the application, as the status changing of the scene and connects them to the basic handlers.
It is also used to retrieve a pointer to the current state of the application, as the pointer to the main window, a pointer to the current scene or a pointer to the current selection, etc...
For example to get the pointer to the main window in any part of the code one has to write:
    \code
// A pointer to the main windows is
QMainWindow * mainwindow = TApp::instance()->getMainWindow();
// To get the current object id
TStageObjectId currentObjectId = TApp::instance()->getCurrentObject()->getObjectId();
            \endcode
            This class is used to take care of changes on the state of the
application and to notify through event handling to the rest of the code.
Constructor & Destructor Documentation
~TApp()
TApp::~TApp ()
{}
Member Function Documentation
autosave
void TApp::autosave () protected slot
                    {
  ToonzScene *scene = getCurrentScene()->getScene();
  if (!getCurrentScene()->getDirtyFlag()) return;
  if (getCurrentTool()->isToolBusy()) {
    m_autosaveSuspended = true;
    return;
  } else
    m_autosaveSuspended = false;
  DVGui::ProgressDialog pb(
      "Autosaving scene..." + toQString(scene->getScenePath()), 0, 0, 1);
  pb.show();
  Preferences *pref = Preferences::instance();
  if (pref->isAutosaveSceneEnabled() && pref->isAutosaveOtherFilesEnabled()) {
    IoCmd::saveAll(IoCmd::AUTO_SAVE);
  } else if (pref->isAutosaveSceneEnabled()) {
    IoCmd::saveScene(IoCmd::AUTO_SAVE);
  } else if (pref->isAutosaveOtherFilesEnabled()) {
    IoCmd::saveNonSceneFiles();
  }
  pb.setValue(1);
}
eventFilter()
bool TApp::eventFilter (QObject * obj, QEvent * event) override protected
{
  if (e->type() == QEvent::TabletEnterProximity) {
    m_isPenCloseToTablet = true;
  } else if (e->type() == QEvent::TabletLeaveProximity) {
    // if the user is painting very quickly with the pen, a number of events
    // could be still in the queue
    // the must be processed as tabled events (not mouse events)
    if (m_isPenCloseToTablet) qApp->processEvents();
    m_isPenCloseToTablet = false;
    emit tabletLeft();
  }
  return false;  // I want just peek at the event. It must be processed anyway.
}
getActiveViewer()
SceneViewer * TApp::getActiveViewer () const inline
{ return m_activeViewer; }
getCurrentColumn()
TColumnHandle * TApp::getCurrentColumn () const inline override virtual
Returns a pointer to the current column.
Implements TApplication.
{ return m_currentColumn; }
Referenced by SaveLevelAsPopup::execute(), getCurrentImageType(), ColorModelViewer::loadCurrentFrame(), IoCmd::loadResources(), SceneViewer::posToRow(), and Toolbar::updateToolbar().
getCurrentFrame()
TFrameHandle * TApp::getCurrentFrame () const inline override virtual
Returns a pointer to the current frame.
Implements TApplication.
{ return m_currentFrame; }
Referenced by XsheetViewer::changeWindowTitle(), SceneViewer::drawOverlay(), getCurrentImageType(), SceneViewer::getSceneMatrix(), SceneViewer::getViewMatrix(), ColorModelViewer::loadCurrentFrame(), IoCmd::loadResources(), Filmstrip::onChooseLevelComboChanged(), SceneViewer::posToRow(), ComboViewerPanel::showEvent(), ComboViewerPanel::updateFrameRange(), and Toolbar::updateToolbar().
getCurrentFx()
TFxHandle * TApp::getCurrentFx () const inline override virtual
Returns a pointer to the current effect.
Implements TApplication.
{ return m_currentFx; }
getCurrentImageType()
int TApp::getCurrentImageType ()
 Returns the current image type that can be a raster or a vector image.
See also
TImage::Type.
{
  /*-- 現在のセルの種類に関係無く、Splineを選択中はベクタを編集できるようにする
   * --*/
  if (getCurrentObject()->isSpline()) return TImage::VECTOR;
  TXshSimpleLevel *sl = 0;
  if (getCurrentFrame()->isEditingScene()) {
    int row = getCurrentFrame()->getFrame();
    int col = getCurrentColumn()->getColumnIndex();
    if (col < 0) {
      int levelType = Preferences::instance()->getDefLevelType();
      return (levelType == PLI_XSHLEVEL)
                 ? TImage::VECTOR
                 :  // RASTER image type includes both TZI_XSHLEVEL
                 (levelType == TZP_XSHLEVEL)
                     ? TImage::TOONZ_RASTER
                     : TImage::RASTER;  // and OVL_XSHLEVEL level types
    }
    TXsheet *xsh = getCurrentXsheet()->getXsheet();
    if (xsh->getColumn(col) && xsh->getColumn(col)->getSoundColumn())
      return TImage::VECTOR;
    TXshCell cell = xsh->getCell(row, col);
    if (cell.isEmpty()) {
      int r0, r1;
      xsh->getCellRange(col, r0, r1);
      if (0 <= r0 && r0 <= r1) {
        /*-- Columnに格納されている一番上のLevelのTypeに合わせる--*/
        cell = xsh->getCell(r0, col);
      } else /*-- Columnが空の場合 --*/
      {
        int levelType = Preferences::instance()->getDefLevelType();
        return (levelType == PLI_XSHLEVEL)
                   ? TImage::VECTOR
                   : (levelType == TZP_XSHLEVEL) ? TImage::TOONZ_RASTER
                                                 : TImage::RASTER;
      }
    }
    sl = cell.getSimpleLevel();
  } else if (getCurrentFrame()->isEditingLevel())
    sl = getCurrentLevel()->getSimpleLevel();
  if (sl) {
    switch (sl->getType()) {
    case TZP_XSHLEVEL:
      return TImage::TOONZ_RASTER;
    case OVL_XSHLEVEL:
      return TImage::RASTER;
    case PLI_XSHLEVEL:
    default:
      return TImage::VECTOR;
    case MESH_XSHLEVEL:
      return TImage::MESH;
    }
  }
  return TImage::VECTOR;
}
References TXsheet::getCell(), TXsheet::getCellRange(), TXsheet::getColumn(), getCurrentColumn(), getCurrentFrame(), getCurrentLevel(), getCurrentObject(), getCurrentXsheet(), TXshCell::getSimpleLevel(), TXshLevel::getType(), TXshCell::isEmpty(), TImage::MESH, TImage::RASTER, TImage::TOONZ_RASTER, and TImage::VECTOR.
getCurrentLevel()
TXshLevelHandle * TApp::getCurrentLevel () const inline override virtual
Returns a pointer to the current level.
Implements TApplication.
{ return m_currentLevel; }
Referenced by XsheetViewer::changeWindowTitle(), ColorModelViewer::contextMenuEvent(), SceneViewer::drawOverlay(), SaveLevelAsPopup::execute(), LoadColorModelPopup::execute(), ReplaceParentDirectoryPopup::execute(), IoCmd::exportLevel(), getCurrentImageType(), SceneViewer::getDpiFactor(), SceneViewer::getZoomScaleFittingWithScreen(), ColorModelViewer::loadCurrentFrame(), ColorModelViewer::loadImage(), Filmstrip::onChooseLevelComboChanged(), SceneViewer::onLevelSwitched(), Filmstrip::onLevelSwitched(), SceneViewer::posToRow(), ComboViewerPanel::showEvent(), LevelSettingsPopup::updateLevelSettings(), and Toolbar::updateToolbar().
getCurrentLevelStyle()
TColorStyle * TApp::getCurrentLevelStyle () const override virtual
Implements TApplication.
{
  return m_paletteController->getCurrentLevelPalette()->getStyle();
}
getCurrentLevelStyleIndex()
int TApp::getCurrentLevelStyleIndex () const override virtual
Implements TApplication.
{
  return m_paletteController->getCurrentLevelPalette()->getStyleIndex();
}
getCurrentObject()
TObjectHandle * TApp::getCurrentObject () const inline override virtual
Returns a pointer to the current object in use.
Implements TApplication.
{ return m_currentObject; }
Referenced by SceneViewer::drawOverlay(), getCurrentImageType(), SceneViewer::getGeometry(), and ComboViewerPanel::showEvent().
getCurrentOnionSkin()
TOnionSkinMaskHandle * TApp::getCurrentOnionSkin () const inline override virtual
Returns a pointer to the current layer's mask.
Implements TApplication.
{
    return m_currentOnionSkinMask;
  }
Referenced by SceneViewer::posToRow().
getCurrentPalette()
TPaletteHandle * TApp::getCurrentPalette () const override virtual
Sets a pointer to the main window..
Implements TApplication.
{
  return m_paletteController->getCurrentPalette();
}
getCurrentRoom()
TMainWindow * TApp::getCurrentRoom () const
 Returns a pointer to the current room. The current room is the window
environment in use, i.e. the drawing tab, the animation tab, the pltedit tab etc...
{
  MainWindow *mainWindow = dynamic_cast<MainWindow *>(getMainWindow());
  if (mainWindow)
    return mainWindow->getCurrentRoom();
  else
    return 0;
}
References getMainWindow().
Referenced by FlipBookPool::pop().
getCurrentRoomName()
QString TApp::getCurrentRoomName () const
{
  Room *currentRoom = dynamic_cast<Room *>(getCurrentRoom());
  if (!currentRoom) return QString();
  return currentRoom->getName();
}
getCurrentScene()
TSceneHandle * TApp::getCurrentScene () const inline override virtual
Returns a pointer to the current scene.
Implements TApplication.
{ return m_currentScene; }
Referenced by VectorizerPopup::apply(), XsheetViewer::changeWindowTitle(), PreviewSubCameraManager::deleteSubCamera(), SaveLevelAsPopup::execute(), ReplaceLevelPopup::execute(), LoadColorModelPopup::execute(), ReplaceParentDirectoryPopup::execute(), IoCmd::exportLevel(), CleanupSettingsModel::getClnPath(), OutputSettingsPopup::getCurrentScene(), SceneViewer::getDpiFactor(), CleanupSettingsModel::getOutputPath(), SceneViewer::getZoomScaleFittingWithScreen(), ColorModelViewer::loadImage(), IoCmd::loadResourceFolders(), IoCmd::loadResources(), RenderCommand::multimediaRender(), OutputSettingsPopup::onCameraChanged(), OutputSettingsPopup::onChannelWidthChanged(), OnRenderCompleted::onDeliver(), OutputSettingsPopup::onDominantFieldChanged(), OutputSettingsPopup::onFormatChanged(), OutputSettingsPopup::onGammaFldEditFinished(), OutputSettingsPopup::onNameChanged(), OutputSettingsPopup::onPathChanged(), XsheetGUI::CellArea::onReplaceByCastedLevel(), OutputSettingsPopup::onResampleChanged(), OutputSettingsPopup::onStretchFldEditFinished(), SceneViewer::posToRow(), VectorizationSwatchTask::run(), Vectorizer::setLevel(), ComboViewerPanel::showEvent(), and Filmstrip::updateChooseLevelComboItems().
getCurrentSelection()
TSelectionHandle * TApp::getCurrentSelection () const inline override virtual
Returns a pointer to the current selection.
Implements TApplication.
{
    return m_currentSelection;
  }
Referenced by XsheetViewer::changeWindowTitle(), ExportLevelPopup::execute(), Filmstrip::onChooseLevelComboChanged(), ColorModelViewer::pick(), and LevelSettingsPopup::updateLevelSettings().
getCurrentTool()
ToolHandle * TApp::getCurrentTool () const inline override virtual
Returns a pointer to the current tool used.
Implements TApplication.
{ return m_currentTool; }
Referenced by SceneViewer::drawOverlay(), SceneViewer::getGeometry(), SceneViewer::GLInvalidateRect(), SceneViewer::invalidateToolStatus(), SceneViewer::onLevelSwitched(), SceneViewer::onToolChanged(), ColorModelViewer::pick(), ComboViewerPanel::showEvent(), and Toolbar::updateToolbar().
getCurrentXsheet()
TXsheetHandle * TApp::getCurrentXsheet () const inline override virtual
Returns a pointer to the current Xsheet.
Implements TApplication.
{ return m_currentXsheet; }
Referenced by VectorizerPopup::apply(), ExportLevelPopup::execute(), SaveLevelAsPopup::execute(), ReplaceLevelPopup::execute(), ReplaceParentDirectoryPopup::execute(), IoCmd::exposeComment(), getCurrentImageType(), SceneViewer::getViewMatrix(), ColorModelViewer::loadCurrentFrame(), IoCmd::loadResources(), OutputSettingsPopup::onAddPresetButtonPressed(), OutputSettingsPopup::onCameraChanged(), OnRenderCompleted::onDeliver(), XsheetGUI::CellArea::onReplaceByCastedLevel(), SceneViewer::posToRow(), ComboViewerPanel::showEvent(), PreviewFxManager::showNewPreview(), LevelSettingsPopup::updateLevelSettings(), and Toolbar::updateToolbar().
getCurrentXsheetViewer()
XsheetViewer * TApp::getCurrentXsheetViewer () const inline
{ return m_xsheetViewer; }
getMainWindow()
QMainWindow * TApp::getMainWindow () const inline
Returns a pointer to the main window.
{ return m_mainWindow; }
Referenced by getCurrentRoom().
getPaletteController()
PaletteController * TApp::getPaletteController () const inline override virtual
Implements TApplication.
{
    return m_paletteController;
  }
init()
void TApp::init ()
 Initializes the main window application. It is called in the main
function after the environment initialization.
                {
  m_isStarting = true;
  IoCmd::newScene();
  m_currentColumn->setColumnIndex(0);
  m_currentFrame->setFrame(0);
  m_isStarting = false;
}
instance()
TApp * TApp::instance () static
A static pointer to the main application.
                     {
  static TApp _instance;
  return &_instance;
}
Referenced by VectorizerPopup::apply(), XsheetViewer::changeWindowTitle(), ColorModelViewer::contextMenuEvent(), PreviewSubCameraManager::deleteSubCamera(), SceneViewer::drawOverlay(), ExportLevelPopup::execute(), SaveLevelAsPopup::execute(), ReplaceLevelPopup::execute(), SavePaletteAsPopup::execute(), LoadColorModelPopup::execute(), ReplaceParentDirectoryPopup::execute(), IoCmd::exportLevel(), IoCmd::exposeComment(), CleanupSettingsModel::getClnPath(), OutputSettingsPopup::getCurrentScene(), SceneViewer::getDpiFactor(), SceneViewer::getGeometry(), CleanupSettingsModel::getOutputPath(), SceneViewer::getSceneMatrix(), SceneViewer::getViewMatrix(), SceneViewer::getZoomScaleFittingWithScreen(), SceneViewer::GLInvalidateRect(), SceneViewer::invalidateToolStatus(), ColorModelViewer::loadCurrentFrame(), ColorModelViewer::loadImage(), IoCmd::loadResourceFolders(), IoCmd::loadResources(), RenderCommand::multimediaRender(), OutputSettingsPopup::onAddPresetButtonPressed(), OutputSettingsPopup::onCameraChanged(), OutputSettingsPopup::onChannelWidthChanged(), Filmstrip::onChooseLevelComboChanged(), OnRenderCompleted::onDeliver(), OutputSettingsPopup::onDominantFieldChanged(), OutputSettingsPopup::onFormatChanged(), ComboViewerPanel::onFrameTypeChanged(), OutputSettingsPopup::onGammaFldEditFinished(), SceneViewer::onLevelSwitched(), Filmstrip::onLevelSwitched(), OutputSettingsPopup::onNameChanged(), OutputSettingsPopup::onPathChanged(), XsheetGUI::CellArea::onReplaceByCastedLevel(), OutputSettingsPopup::onResampleChanged(), OutputSettingsPopup::onStretchFldEditFinished(), SceneViewer::onToolChanged(), ColorModelViewer::pick(), FlipBookPool::pop(), SceneViewer::posToRow(), CleanupSettingsModel::restoreGlobalSettings(), VectorizationSwatchTask::run(), Vectorizer::setLevel(), ComboViewerPanel::showEvent(), PreviewFxManager::showNewPreview(), Filmstrip::updateChooseLevelComboItems(), ComboViewerPanel::updateFrameRange(), LevelSettingsPopup::updateLevelSettings(), and Toolbar::updateToolbar().
isApplicationStarting()
bool TApp::isApplicationStarting () inline
{ return m_isStarting; }
isPenCloseToTablet()
bool TApp::isPenCloseToTablet () const inline
{ return m_isPenCloseToTablet; }
onColumnIndexSwitched
void TApp::onColumnIndexSwitched () protected slot
{
  // update xsheetlevel
  updateXshLevel();
  // update current object
  int columnIndex = m_currentColumn->getColumnIndex();
  if (columnIndex >= 0)
    m_currentObject->setObjectId(TStageObjectId::ColumnId(columnIndex));
  else {
    TXsheet *xsh = getCurrentXsheet()->getXsheet();
    m_currentObject->setObjectId(
        TStageObjectId::CameraId(xsh->getCameraColumnIndex()));
  }
}
onFrameSwitched
void TApp::onFrameSwitched () protected slot
{
  updateXshLevel();
  int row = m_currentFrame->getFrameIndex();
  TCellSelection *sel =
      dynamic_cast<TCellSelection *>(TSelection::getCurrent());
  if (sel && !sel->isRowSelected(row) &&
      !Preferences::instance()->isUseArrowKeyToShiftCellSelectionEnabled()) {
    sel->selectNone();
  }
}
onFxSwitched
void TApp::onFxSwitched () protected slot
{
  //  if(m_currentFx->getFx() != 0)
  //    m_currentTool->setTool(T_Edit);
}
onImageChanged
void TApp::onImageChanged () protected slot
{
  m_currentTool->onImageChanged((TImage::Type)getCurrentImageType());
}
onLevelColorStyleChanged
void TApp::onLevelColorStyleChanged () protected slot
{
  onPaletteChanged();
  TXshLevel *level = m_currentLevel->getLevel();
  if (!level) return;
  TPalette *palette            = getCurrentPalette()->getPalette();
  TXshSimpleLevel *simpleLevel = level->getSimpleLevel();
  if (simpleLevel && simpleLevel->getPalette() == palette) {
    notifyPaletteChanged(simpleLevel);
  } else {
    TLevelSet *levelSet = getCurrentScene()->getScene()->getLevelSet();
    for (int i = 0; i < levelSet->getLevelCount(); i++) {
      if (levelSet->getLevel(i)) {
        simpleLevel = levelSet->getLevel(i)->getSimpleLevel();
        if (simpleLevel && simpleLevel->getPalette() == palette) {
          notifyPaletteChanged(simpleLevel);
        }
      }
    }
  }
}
onLevelColorStyleSwitched
void TApp::onLevelColorStyleSwitched () protected slot
{
  TXshLevel *sl = m_currentLevel->getLevel();
  if (!sl || (sl->getType() != TZP_XSHLEVEL && sl->getType() != PLI_XSHLEVEL))
    return;
  TPaletteHandle *ph = m_paletteController->getCurrentLevelPalette();
  assert(ph);
  if (ToonzCheck::instance()->setColorIndex(ph->getStyleIndex())) {
    ToonzCheck *tc = ToonzCheck::instance();
    int mask       = tc->getChecks();
    if (mask & ToonzCheck::eInk || mask & ToonzCheck::ePaint) {
      IconGenerator::Settings s;
      s.m_blackBgCheck      = mask & ToonzCheck::eBlackBg;
      s.m_transparencyCheck = mask & ToonzCheck::eTransparency;
      s.m_inksOnly          = mask & ToonzCheck::eInksOnly;
      s.m_inkIndex   = mask & ToonzCheck::eInk ? tc->getColorIndex() : -1;
      s.m_paintIndex = mask & ToonzCheck::ePaint ? tc->getColorIndex() : -1;
      IconGenerator::instance()->setSettings(s);
      if (sl->getType() == PLI_XSHLEVEL) {
        std::vector<TFrameId> fids;
        sl->getFids(fids);
        for (int i = 0; i < (int)fids.size(); i++)
          IconGenerator::instance()->invalidate(sl, fids[i]);
      }
      m_currentLevel->notifyLevelViewChange();
    }
    /*-- 表示オプションが切り替わっただけなので、DirtyFlagを立てない --*/
    m_currentScene->notifySceneChanged(false);
  }
}
onObjectSwitched
void TApp::onObjectSwitched () protected slot
{
  if (m_currentObject->isSpline()) {
    TXsheet *xsh = m_currentXsheet->getXsheet();
    TStageObject *currentObject =
        xsh->getStageObject(m_currentObject->getObjectId());
    TStageObjectSpline *ps = currentObject->getSpline();
    m_currentObject->setSplineObject(ps);
  } else
    m_currentObject->setSplineObject(0);
  onImageChanged();
}
onPaletteChanged
void TApp::onPaletteChanged () protected slot
{ m_currentScene->setDirtyFlag(true); }
onSceneChanged
void TApp::onSceneChanged () protected slot
{
  updateCurrentFrame();
  m_currentTool->updateMatrix();
}
onSceneSwitched
void TApp::onSceneSwitched () protected slot
{
  // update XSheet
  m_currentXsheet->setXsheet(m_currentScene->getScene()->getXsheet());
  TPalette *palette = m_currentScene->getScene()
                          ->getProperties()
                          ->getCleanupParameters()
                          ->m_cleanupPalette.getPointer();
  m_paletteController->getCurrentCleanupPalette()->setPalette(palette, -1);
  m_paletteController->editLevelPalette();
  // reset current frame
  m_currentFrame->setFrame(0);
  // clear current onionSkinMask
  m_currentOnionSkinMask->clear();
  // update currentFrames
  updateCurrentFrame();
  // update current tool
  m_currentTool->onImageChanged((TImage::Type)getCurrentImageType());
}
onSplineChanged
void TApp::onSplineChanged () protected slot
{
  if (m_currentObject->isSpline()) {
    TXsheet *xsh = m_currentXsheet->getXsheet();
    TStageObject *currentObject =
        xsh->getStageObject(m_currentObject->getObjectId());
    currentObject->setOffset(
        currentObject->getOffset());  // invalidate currentObject
  }
}
onStartAutoSave
void TApp::onStartAutoSave () protected slot
{
  assert(Preferences::instance()->isAutosaveEnabled());
  m_autosaveTimer->start(Preferences::instance()->getAutosavePeriod() * 1000 *
                         60);
}
onStopAutoSave
void TApp::onStopAutoSave () protected slot
{
  // assert(!Preferences::instance()->isAutosaveEnabled());
  m_autosaveTimer->stop();
}
onToolEditingFinished
void TApp::onToolEditingFinished () protected slot
{
  if (!Preferences::instance()->isAutosaveEnabled() || !m_autosaveSuspended)
    return;
  autosave();
}
onXsheetChanged
void TApp::onXsheetChanged () protected slot
{
  updateXshLevel();
  updateCurrentFrame();
  // update current tool
  m_currentTool->onImageChanged((TImage::Type)getCurrentImageType());
}
onXsheetSoundChanged
void TApp::onXsheetSoundChanged () protected slot
{
  m_currentXsheet->getXsheet()->invalidateSound();
}
onXsheetSwitched
void TApp::onXsheetSwitched () protected slot
{
  // update current object
  int columnIndex = m_currentColumn->getColumnIndex();
  if (columnIndex >= 0)
    m_currentObject->setObjectId(TStageObjectId::ColumnId(columnIndex));
  // update xsheetlevel
  updateXshLevel();
  // no Fx is set to current.
  m_currentFx->setFx(0);
}
onXshLevelChanged
void TApp::onXshLevelChanged () protected slot
{
  TXshLevel *level = m_currentLevel->getLevel();
  std::vector<TFrameId> fids;
  if (level != 0) level->getFids(fids);
  m_currentFrame->setFrameIds(fids);
  // update current tool
  m_currentTool->onImageChanged((TImage::Type)getCurrentImageType());
}
onXshLevelSwitched
void TApp::onXshLevelSwitched (TXshLevel *) protected slot
{
  TXshLevel *level = m_currentLevel->getLevel();
  if (level) {
    TXshSimpleLevel *simpleLevel = level->getSimpleLevel();
    // Devo aggiornare la paletta corrente
    if (simpleLevel) {
      m_paletteController->getCurrentLevelPalette()->setPalette(
          simpleLevel->getPalette());
      // Se il nuovo livello selezionato e' un ovl,
      // la paletta corrente e' una cleanup palette
      //  => setto come handle corrente quello della paletta di cleanup.
      TPalette *currentPalette =
          m_paletteController->getCurrentPalette()->getPalette();
      if (simpleLevel->getType() == OVL_XSHLEVEL && currentPalette &&
          currentPalette->isCleanupPalette())
        m_paletteController->editCleanupPalette();
      return;
    }
    TXshPaletteLevel *paletteLevel = level->getPaletteLevel();
    if (paletteLevel) {
      m_paletteController->getCurrentLevelPalette()->setPalette(
          paletteLevel->getPalette());
      return;
    }
  }
  m_paletteController->getCurrentLevelPalette()->setPalette(0);
}
setActiveViewer()
void TApp::setActiveViewer (SceneViewer * viewer) inline
{
    if (m_activeViewer == viewer) return;
    m_activeViewer = viewer;
    emit activeViewerChanged();
  }
setCurrentLevelStyleIndex()
void TApp::setCurrentLevelStyleIndex (int index, bool forceUpdate = false) override virtual
Implements TApplication.
{
  m_paletteController->getCurrentLevelPalette()->setStyleIndex(index,
                                                               forceUpdate);
}
setCurrentXsheetViewer()
void TApp::setCurrentXsheetViewer (XsheetViewer * viewer) inline
{ m_xsheetViewer = viewer; }
setMainWindow()
void TApp::setMainWindow (QMainWindow * mainWindow) inline
{ m_mainWindow = mainWindow; }
writeSettings()
void TApp::writeSettings ()
{
  MainWindow *mainWindow = dynamic_cast<MainWindow *>(getMainWindow());
  if (mainWindow) mainWindow->refreshWriteSettings();
}
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/toonz/tapp.h
E:/opentoonz/toonz/sources/toonz/tapp.cpp