opentoonz: TCleanupper Class Reference
TCleanupper Class Reference
Public Member Functions
void setParameters (CleanupParameters *parameters)
const CleanupParameters * getParameters () const
TPalette * createToonzPaletteFromCleanupPalette ()
bool getResampleValues (const TRasterImageP &image, TAffine &aff, double &blur, TDimension &outDim, TPointD &outDpi, bool isCameraTest, bool &isSameDpi)
TRasterP processColors (const TRasterP &r)
CleanupPreprocessedImage * process (TRasterImageP &image, bool first_image, TRasterImageP &onlyResampledImage, bool isCameraTest=false, bool returnResampled=false, bool onlyForSwatch=false, TAffine *aff=0, TRasterP templateForResampled=0)
void finalize (const TRaster32P &dst, CleanupPreprocessedImage *src)
TToonzImageP finalize (CleanupPreprocessedImage *src, bool isCleanupper=false)
TRasterImageP autocenterOnly (const TRasterImageP &image, bool isCameraTest, bool &autocentered)
TPointD getSourceDpi () const
void setSourceDpi (const TPointD &dpi)
Static Public Member Functions
static TCleanupper * instance ()
Detailed Description
Member Function Documentation
autocenterOnly()
TRasterImageP TCleanupper::autocenterOnly (const TRasterImageP & image, bool isCameraTest, bool & autocentered)
{
  double xDpi, yDpi;
  // double inlx, inly, zoom_factor, max_blur;
  double skew = 0, angle = 0,
         dist = 0 /*lq_nozoom, lp_nozoom,, cx, cy, scalex, scaley*/;
  double cxin, cyin, cpout, cqout;
  int rasterIsSavebox = true;
  TAffine aff, preAff, inv;
  int rasterLx, finalLx, rasterLy, finalLy;
  rasterLx = finalLx = image->getRaster()->getLx();
  rasterLy = finalLy = image->getRaster()->getLy();
  TRect saveBox = image->getSavebox();
  if ((saveBox == TRect()) &&
      ((saveBox.getLx() > 0 && saveBox.getLx() < rasterLx) ||
       (saveBox.getLy() > 0 && saveBox.getLy() < rasterLy)))
    rasterIsSavebox = false;
  int rotate = m_parameters->m_rotate;
  image->getDpi(xDpi, yDpi);
  if (!xDpi)  // using 65.0 as default DPI
    xDpi = (yDpi ? yDpi : 65);
  if (!yDpi) yDpi = (xDpi ? xDpi : 65);
  if (rasterIsSavebox) {
    cxin = -saveBox.getP00().x + (saveBox.getLx() - 1) / 2.0;
    cyin = -saveBox.getP00().y + (saveBox.getLy() - 1) / 2.0;
  } else {
    cxin = (rasterLx - 1) / 2.0;
    cyin = (rasterLy - 1) / 2.0;
  }
  cpout = (rasterLx - 1) / 2.0;
  cqout = (rasterLy - 1) / 2.0;
  if (m_parameters->m_autocenterType != AUTOCENTER_NONE)
    autocentered = doAutocenter(angle, skew, cxin, cyin, cqout, cpout, xDpi,
                                yDpi, rasterIsSavebox, saveBox, image, 1.0);
  else
    autocentered = true;
  if (m_parameters->m_autocenterType == AUTOCENTER_CTR && skew) {
    aff.a11 = cos(skew * M_PI_180);
    aff.a21 = sin(skew * M_PI_180);
  }
  aff = aff * TRotation(angle);
  aff = aff.place(cxin, cyin, cpout, cqout);
  if (rotate != 0 && rotate != 180) std::swap(finalLx, finalLy);
  TPointD pin  = TPointD((rasterLx - 1) / 2.0, (rasterLy - 1) / 2.0);
  TPointD pout = TPointD((finalLx - 1) / 2.0, (finalLy - 1) / 2.0);
  if (rotate != 0) aff = TRotation(-(double)rotate).place(pin, pout) * aff;
  if (m_parameters->m_flipx || m_parameters->m_flipy)
    aff = TScale(m_parameters->m_flipx ? -1 : 1, m_parameters->m_flipy ? -1 : 1)
              .place(pout, pout) *
          aff;
  if (!isCameraTest)
    aff = TTranslation(m_parameters->m_offx * xDpi / 2,
                       m_parameters->m_offy * yDpi / 2) *
          aff;
  TRasterP tmpRas;
  TPoint dp;
  if (isCameraTest)  // in cameratest, I don't want to crop the image to be
                     // shown.
  // so, I resample without cropping, and I compute the offset needed to have it
  // autocentered.
  // That offset is stored in the RasterImage(setOffset below) and then used
  // when displaying the image in camerastand (in method
  // RasterPainter::onRasterImage)
  {
    // TPointD srcActualCenter = aff.inv()*TPointD(finalLx/2.0, finalLy/2.0);//
    // the autocenter position in the source image
    // TPointD srcCenter = imageToResample->getRaster()->getCenterD();*/
    TPointD dstActualCenter = TPointD(finalLx / 2.0, finalLy / 2.0);
    TPointD dstCenter       = aff * image->getRaster()->getCenterD();
    dp = convert(
        dstCenter -
        dstActualCenter);  // the amount to be offset in the destination image.
    TRect r = convert(aff * convert(image->getRaster()->getBounds()));
    aff     = (TTranslation(convert(-r.getP00())) * aff);
    // aff = aff.place(srcActualCenter, dstActualCenter);
    tmpRas = image->getRaster()->create(r.getLx(), r.getLy());
  } else
    tmpRas = image->getRaster()->create(finalLx, finalLy);
  TRop::resample(tmpRas, image->getRaster(), aff);
  // TImageWriter::save(TFilePath("C:\\temp\\incleanup.tif"), imageToResample);
  // TImageWriter::save(TFilePath("C:\\temp\\outcleanup.tif"), tmp_ras);
  TRasterImageP final(tmpRas);
  final->setOffset(dp);
  final->setDpi(xDpi, yDpi);
  // final->sethPos(finalHPos);
  return final;
}
createToonzPaletteFromCleanupPalette()
TPalette * TCleanupper::createToonzPaletteFromCleanupPalette ()
{
  TPalette *cleanupPalette = m_parameters->m_cleanupPalette.getPointer();
  return createToonzPalette(cleanupPalette, 1);
}
finalize() [1/2]
TToonzImageP TCleanupper::finalize (CleanupPreprocessedImage * src, bool isCleanupper = false)
{
  if (src->m_wasFromGR8)
    return doPostProcessingGR8(src);
  else
    return doPostProcessingColor(src->getImg(), isCleanupper);
}
finalize() [2/2]
void TCleanupper::finalize (const TRaster32P & dst, CleanupPreprocessedImage * src)
{
  if (!outRas) return;
  if (srcImg->m_wasFromGR8)
    doPostProcessingGR8(outRas, srcImg);
  else
    doPostProcessingColor(outRas, srcImg);
}
getParameters()
const CleanupParameters * TCleanupper::getParameters () const inline
{ return m_parameters; }
getResampleValues()
bool TCleanupper::getResampleValues (const TRasterImageP & image, TAffine & aff, double & blur, TDimension & outDim, TPointD & outDpi, bool isCameraTest, bool & isSameDpi)
{
  double outlp, outlq;
  double scalex, scaley;
  double cxin, cyin, cpout, cqout;
  double max_blur;
  TPointD dpi;
  // Locking the input image to be cleanupped
  image->getRaster()->lock();
  // Retrieve image infos
  int rasterLx = image->getRaster()->getLx();
  int rasterLy = image->getRaster()->getLy();
  /*---入力画像サイズとSaveBoxのサイズが一致しているか？の判定---*/
  TRect saveBox          = image->getSavebox();
  bool raster_is_savebox = true;
  if (saveBox == TRect() &&
      ((saveBox.getLx() > 0 && saveBox.getLx() < rasterLx) ||
       (saveBox.getLy() > 0 && saveBox.getLy() < rasterLy)))
    raster_is_savebox = false;
  // Use the same source dpi throughout the level
  dpi = getSourceDpi();
  if (dpi == TPointD())
    dpi.x = dpi.y = 65.0;  // using 65.0 as default DPI //??????WHY
  else if (!dpi.x)
    dpi.x = dpi.y;
  else if (!dpi.y)
    dpi.y = dpi.x;
  // Retrieve some cleanup parameters
  int rotate = m_parameters->m_rotate;
  // Build scaling/dpi data
  {
    m_parameters->getOutputImageInfo(outDim, outDpi.x, outDpi.y);
    // input -> output scale factor
    scalex = outDpi.x / dpi.x;
    scaley = outDpi.y / dpi.y;
    outlp = outDim.lx;
    outlq = outDim.ly;
  }
  /*---
   * 拡大／縮小をしていない場合（DPIが変わらない場合）、NearestNeighborでリサンプリングする。---*/
  isSameDpi = areAlmostEqual(outDpi.x, dpi.x, 0.1) &&
              areAlmostEqual(outDpi.y, dpi.y, 0.1);
  // Retrieve input center
  if (raster_is_savebox) {
    cxin = -saveBox.getP00().x + (saveBox.getLx() - 1) / 2.0;
    cyin = -saveBox.getP00().y + (saveBox.getLy() - 1) / 2.0;
  } else {
    cxin = (rasterLx - 1) / 2.0;
    cyin = (rasterLy - 1) / 2.0;
  }
  // Retrieve output center
  cpout = (outlp - 1) / 2.0;
  cqout = (outlq - 1) / 2.0;
  // Perform autocenter if any is found
  double angle = 0.0;
  double skew  = 0.0;
  TAffine pre_aff;
  image->getRaster()->lock();
  bool autocentered =
      doAutocenter(angle, skew, cxin, cyin, cqout, cpout, dpi.x, dpi.y,
                   raster_is_savebox, saveBox, image, scalex);
  image->getRaster()->unlock();
  // Build the image transform as deduced by the autocenter
  if (m_parameters->m_autocenterType == AUTOCENTER_CTR && skew) {
    pre_aff.a11 = cos(skew * M_PI_180);
    pre_aff.a21 = sin(skew * M_PI_180);
  }
  aff = (TScale(scalex, scaley) * pre_aff) * TRotation(angle);
  aff = aff.place(cxin, cyin, cpout, cqout);
  // Apply eventual additional user-defined transforms
  TPointD pout = TPointD((outlp - 1) / 2.0, (outlq - 1) / 2.0);
  if (m_parameters->m_rotate != 0)
    aff = TRotation(-(double)m_parameters->m_rotate).place(pout, pout) * aff;
  if (m_parameters->m_flipx || m_parameters->m_flipy)
    aff = TScale(m_parameters->m_flipx ? -1 : 1, m_parameters->m_flipy ? -1 : 1)
              .place(pout, pout) *
          aff;
  if (!isCameraTest)
    aff = TTranslation(m_parameters->m_offx * outDpi.x / 2,
                       m_parameters->m_offy * outDpi.y / 2) *
          aff;
  max_blur = 20.0 * sqrt(fabs(scalex /*** * oversample_factor ***/));
  blur     = pow(max_blur, (100 - m_parameters->m_sharpness) / (100 - 1));
  return autocentered;
}
getSourceDpi()
TPointD TCleanupper::getSourceDpi () const inline
{ return m_sourceDpi; }
instance()
TCleanupper * TCleanupper::instance () static
{
  static TCleanupper theCleanupper;
  return &theCleanupper;
}
process()
CleanupPreprocessedImage * TCleanupper::process (TRasterImageP & image, bool first_image, TRasterImageP & onlyResampledImage, bool isCameraTest = false, bool returnResampled = false, bool onlyForSwatch = false, TAffine * aff = 0, TRasterP templateForResampled = 0)
The main cleanup method.
Warning
The input image reference is internally released at the most appropriate time, to unlock a possibly useful memory block.
{
  TAffine aff;
  double blur;
  TDimension outDim(0, 0);
  TPointD outDpi;
  bool isSameDpi    = false;
  bool autocentered = getResampleValues(image, aff, blur, outDim, outDpi,
                                        isCameraTest, isSameDpi);
  if (m_parameters->m_autocenterType != AUTOCENTER_NONE && !autocentered)
    DVGui::warning(
        QObject::tr("The autocentering failed on the current drawing."));
  bool fromGr8 = (bool)TRasterGR8P(image->getRaster());
  bool toGr8   = (m_parameters->m_lineProcessingMode == lpGrey);
  // If necessary, perform auto-adjust
  if (!isCameraTest && m_parameters->m_lineProcessingMode != lpNone && toGr8 &&
      m_parameters->m_autoAdjustMode != AUTO_ADJ_NONE && !onlyForSwatch) {
    static int ref_cum[256];
    UCHAR lut[256];
    int cum[256];
    double x0_src_f, y0_src_f, x1_src_f, y1_src_f;
    int x0_src, y0_src, x1_src, y1_src;
    // cleanup_message("Autoadjusting... \n");
    TAffine inv = aff.inv();
    x0_src_f = affMV1(inv, 0, 0);
    y0_src_f = affMV2(inv, 0, 0);
    x1_src_f = affMV1(inv, outDim.lx - 1, outDim.ly - 1);
    y1_src_f = affMV2(inv, outDim.lx - 1, outDim.ly - 1);
    x0_src = tround(x0_src_f);
    y0_src = tround(y0_src_f);
    x1_src = tround(x1_src_f);
    y1_src = tround(y1_src_f);
    set_autoadjust_window(x0_src, y0_src, x1_src, y1_src);
    if (!TRasterGR8P(image->getRaster())) {
      // Auto-adjusting a 32-bit image. This means that a white background must
      // be introduced first.
      TRaster32P ras32(image->getRaster()->clone());
      TRop::addBackground(ras32, TPixel32::White);
      image = TRasterImageP(ras32);  // old image is released here
      ras32 = TRaster32P();
      TRasterGR8P rgr(image->getRaster()->getSize());
      TRop::copy(rgr, image->getRaster());
      // This is now legit. It was NOT before the clone, since the original
      // could be cached.
      image->setRaster(rgr);
    }
    switch (m_parameters->m_autoAdjustMode) {
    case AUTO_ADJ_HISTOGRAM:
      if (first_image) {
        build_gr_cum(image, ref_cum);
      } else {
        build_gr_cum(image, cum);
        build_gr_lut(ref_cum, cum, lut);
        apply_lut(image, lut);
      }
      break;
    case AUTO_ADJ_HISTO_L:
      histo_l_algo(image, first_image);
      break;
    case AUTO_ADJ_BLACK_EQ:
      black_eq_algo(image);
      break;
    case AUTO_ADJ_NONE:
    default:
      assert(false);
      break;
    }
  }
  fromGr8 = (bool)TRasterGR8P(
      image->getRaster());  // may have changed type due to auto-adjust
  assert(returnResampled ||
         !onlyForSwatch);  // if onlyForSwatch, then returnResampled
  // Allocate output colormap raster
  TRasterCM32P finalRas;
  if (!onlyForSwatch) {
    finalRas = TRasterCM32P(outDim);
    if (!finalRas) {
      TImageCache::instance()->outputMap(outDim.lx * outDim.ly * 4,
                                         "C:\\cachelog");
      assert(!"failed finalRas allocation!");
      return 0;
    }
  }
  // In case the input raster was a greymap, we cannot reutilize finalRas's
  // buffer to transform the final
  // fullcolor pixels to colormap pixels directly (1 32-bit pixel would hold 4
  // 8-bit pixels) - therefore,
  // a secondary greymap is allocated.
  // NOTE: This should be considered obsolete? By using TRop::resample(
  // <TRaster32P& instance> , ...) we
  // should get the same effect!!
  TRasterP tmp_ras;
  if (returnResampled || (fromGr8 && toGr8)) {
    if (templateForResampled)
      tmp_ras = templateForResampled->create(outDim.lx, outDim.ly);
    else if (fromGr8 && toGr8)
      tmp_ras = TRasterGR8P(outDim);
    else
      tmp_ras = TRaster32P(outDim);
    if (!tmp_ras) {
      TImageCache::instance()->outputMap(outDim.lx * outDim.ly * 4,
                                         "C:\\cachelog");
      assert(!"failed tmp_ras allocation!");
      return 0;
    }
  } else
    // if finalRas is allocated, and the intermediate raster has to be 32-bit,
    // we can perform pixel
    // conversion directly on the same output buffer
    tmp_ras = TRaster32P(outDim.lx, outDim.ly, outDim.lx,
                         (TPixel32 *)finalRas->getRawData());
  TRop::ResampleFilterType flt_type;
  if (isSameDpi)
    flt_type = TRop::ClosestPixel;  // NearestNeighbor
  else if (isCameraTest)
    flt_type = TRop::Triangle;
  else
    flt_type = TRop::Hann2;
  TRop::resample(tmp_ras, image->getRaster(), aff, flt_type, blur);
  if ((TRaster32P)tmp_ras && !templateForResampled)
    // Add white background to deal with semitransparent pixels
    TRop::addBackground(tmp_ras, TPixel32::White);
  if (resampleAff) *resampleAff = aff;
  image->getRaster()->unlock();
  image = TRasterImageP();
  if (returnResampled) {
    onlyResampledImage = TRasterImageP(tmp_ras);
    onlyResampledImage->setDpi(outDpi.x, outDpi.y);
  }
  if (onlyForSwatch) return 0;
  assert(finalRas);
  // Copy current cleanup palette to parameters' colors
  m_parameters->m_colors.update(m_parameters->m_cleanupPalette.getPointer(),
                                m_parameters->m_noAntialias);
  if (toGr8) {
    // No (color) processing. Not even thresholding. This just means that all
    // the important
    // stuff here is made in the brightness/contrast stage...
    // NOTE: Most of the color processing should be DISABLED in this case!!
    tmp_ras->lock();
    finalRas->lock();
    assert(tmp_ras->getSize() == finalRas->getSize());
    assert(tmp_ras->getLx() == tmp_ras->getWrap());
    assert(finalRas->getLx() == finalRas->getWrap());
    int pixCount = outDim.lx * outDim.ly;
    if (fromGr8) {
      UCHAR *rowin    = tmp_ras->getRawData();
      TUINT32 *rowout = reinterpret_cast<TUINT32 *>(finalRas->getRawData());
      for (int i = 0; i < pixCount; i++)
        *rowout++ = *rowin++;  // Direct copy for now... :(
    } else {
      TPixel32 *rowin = reinterpret_cast<TPixel32 *>(tmp_ras->getRawData());
      TUINT32 *rowout = reinterpret_cast<TUINT32 *>(finalRas->getRawData());
      for (int i = 0; i < pixCount; i++)
        *rowout++ = TPixelGR8::from(*rowin++).value;
    }
    tmp_ras->unlock();
    finalRas->unlock();
  } else {
    // WARNING: finalRas and tmp_ras may share the SAME buffer!
    assert(TRaster32P(tmp_ras));
    preprocessColors(finalRas, tmp_ras, m_parameters->m_colors);
  }
  TToonzImageP final;
  final = TToonzImageP(finalRas, finalRas->getBounds());
  final->setDpi(outDpi.x, outDpi.y);
  CleanupPreprocessedImage *cpi =
      new CleanupPreprocessedImage(m_parameters, final, toGr8);
  cpi->m_autocentered = autocentered;
  cpi->m_appliedAff   = aff;
  return cpi;
}
References TRop::addBackground(), TRop::ClosestPixel, TRop::copy(), TPixelGR8::from(), TRaster::getRawData(), TRaster::getWrap(), TRop::Hann2, TAffine::inv(), TRop::resample(), and TRop::Triangle.
processColors()
TRasterP TCleanupper::processColors (const TRasterP & r)
{
  if (m_parameters->m_lineProcessingMode == lpNone) return rin;
  TRasterCM32P rcm = TRasterCM32P(rin->getSize());
  if (!rcm) {
    assert(!"failed finalRas allocation!");
    return TRasterCM32P();
  }
  // Copy current cleanup palette to parameters' colors
  m_parameters->m_colors.update(m_parameters->m_cleanupPalette.getPointer(),
                                m_parameters->m_noAntialias);
  bool toGr8 = (m_parameters->m_lineProcessingMode == lpGrey);
  if (toGr8) {
    // No (color) processing. Not even thresholding. This just means that all
    // the important
    // stuff here is made in the brightness/contrast stage...
    // NOTE: Most of the color processing should be DISABLED in this case!!
    // finalRas->clear();
    rin->lock();
    rcm->lock();
    if (TRasterGR8P(rin)) {
      UCHAR *rowin    = rin->getRawData();
      TUINT32 *rowout = reinterpret_cast<TUINT32 *>(rcm->getRawData());
      for (int i = 0; i < rin->getLy(); i++) {
        for (int j = 0; j < rin->getLx(); j++)
          *rowout++ = *rowin++;  // Direct copy for now... :(
        rowin += rin->getWrap() - rin->getLx();
        rowout += rcm->getWrap() - rcm->getLx();
      }
    } else {
      TPixel32 *rowin = reinterpret_cast<TPixel32 *>(rin->getRawData());
      TUINT32 *rowout = reinterpret_cast<TUINT32 *>(rcm->getRawData());
      for (int i = 0; i < rin->getLy(); i++) {
        for (int j = 0; j < rin->getLx(); j++)
          *rowout++ = TPixelGR8::from(*rowin++).value;
        rowin += rin->getWrap() - rin->getLx();
        rowout += rcm->getWrap() - rcm->getLx();
      }
    }
    rin->unlock();
    rcm->unlock();
  } else {
    assert(TRaster32P(rin));
    preprocessColors(rcm, rin, m_parameters->m_colors);
  }
  // outImg->setDpi(outDpi.x, outDpi.y);
  CleanupPreprocessedImage cpi(m_parameters,
                               TToonzImageP(rcm, rcm->getBounds()), toGr8);
  cpi.m_autocentered = true;
  TRaster32P rout = TRaster32P(rin->getSize());
  finalize(rout, &cpi);
  return rout;
}
setParameters()
void TCleanupper::setParameters (CleanupParameters * parameters)
{
  m_parameters = parameters;
}
setSourceDpi()
void TCleanupper::setSourceDpi (const TPointD & dpi) inline
{ m_sourceDpi = dpi; }
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/toonz/tcleanupper.h
E:/opentoonz/toonz/sources/toonzlib/tcleanupper.cpp