opentoonz: TProjectManager Class Reference
TProjectManager Class Reference
Manages all toonz projects. The class provides all needed method to retrieve projects paths, names and folders.
#include <tproject.h>
Classes
class Listener
Public Member Functions
void notifyProjectChanged ()
TFilePath getCurrentProjectPath ()
void setCurrentProjectPath (const TFilePath &fp)
TProjectP getCurrentProject ()
void initializeScene (ToonzScene *scene)
void saveTemplate (ToonzScene *scene)
void addProjectsRoot (const TFilePath &fp)
void addSVNProjectsRoot (const TFilePath &fp)
TFilePath getCurrentProjectRoot ()
TFilePath projectPathToProjectName (const TFilePath &projectPath)
TFilePath projectNameToProjectPath (const TFilePath &projectName)
TFilePath projectFolderToProjectPath (const TFilePath &projectFolder)
TFilePath getProjectPathByName (const TFilePath &projectName)
TFilePath getProjectPathByProjectFolder (const TFilePath &projectFolder)
TProjectP loadSceneProject (const TFilePath &scenePath)
void getFolderNames (std::vector< std::string > &names)
void addListener (Listener *listener)
void removeListener (Listener *listener)
TProjectP createStandardProject ()
void createSandboxIfNeeded ()
bool isTabKidsModeEnabled () const
void enableTabKidsMode (bool tabKidsMode)
bool isTabModeEnabled () const
void enableTabMode (bool tabMode)
TFilePath getSandboxProjectFolder ()
Return the absolute path of the standard folder "sandbox".
TFilePath getSandboxProjectPath ()
Return the absolute path of the standard project "sandbox_prj6.xml" file.
void getProjectRoots (std::vector< TFilePath > &projectRoots) const
bool isProject (const TFilePath &projectFolder)
Static Public Member Functions
static TProjectManager * instance ()
Detailed Description
Manages all toonz projects. The class provides all needed method to retrieve projects paths, names and folders.
It is possible to handle more than one project root. The class maintains a container this purpose. All the projects roots must be set by hand in the windows registry. By default, only one project root is created when toonz is installed.
The project root container can be updated using addProjectsRoot(const TFilePath &root), addDefaultProjectsRoot() methods.
 The class maintains also information about the current project. The
class provides all needed method to retrieve the current project path, name and folder.
See also
TProject
Constructor & Destructor Documentation
~TProjectManager()
TProjectManager::~TProjectManager ()
{}
Member Function Documentation
addListener()
void TProjectManager::addListener (Listener * listener)
Adds listener to the listeners container.
{
  m_listeners.insert(listener);
}
addProjectsRoot()
void TProjectManager::addProjectsRoot (const TFilePath & root)
Adds the specified folder fp in the projecs roots container.
If fp is already contained in the container, the method does nothing.
Note
fp must be a folder and not a file path.
{
  // assert(TFileStatus(root).isDirectory());
  if (std::find(m_projectsRoots.begin(), m_projectsRoots.end(), root) ==
      m_projectsRoots.end())
    m_projectsRoots.push_back(root);
}
addSVNProjectsRoot()
void TProjectManager::addSVNProjectsRoot (const TFilePath & root)
Adds the specified folder fp in the version control projecs roots container.
If fp is already contained in the container, the method does nothing.
Note
fp must be a folder and not a file path.
{
  assert(TFileStatus(root).isDirectory());
  if (std::find(m_svnProjectsRoots.begin(), m_svnProjectsRoots.end(), root) ==
      m_svnProjectsRoots.end())
    m_svnProjectsRoots.push_back(root);
}
createSandboxIfNeeded()
void TProjectManager::createSandboxIfNeeded ()
Creates the standard project folder "sandbox" if it doesn't exist.
{
  TFilePath path = getSandboxProjectPath();
  if (!TFileStatus(path).doesExist()) {
    TProjectP project = createStandardProject();
    try {
      project->save(path);
    } catch (...) {
    }
  }
}
References createStandardProject(), and getSandboxProjectPath().
createStandardProject()
TProjectP TProjectManager::createStandardProject ()
Create a standard project.
A standard project is a project containing the standard named and constant folder.
See also
TProject.
{
  TProject *project = new TProject();
  // set default folders (+drawings, ecc.)
  std::vector<std::string> names;
  getFolderNames(names);
  std::vector<std::string>::iterator it;
  for (it = names.begin(); it != names.end(); ++it) project->setFolder(*it);
  return project;
}
References getFolderNames().
Referenced by createSandboxIfNeeded().
enableTabKidsMode()
void TProjectManager::enableTabKidsMode (bool tabKidsMode) inline
{ m_tabKidsMode = tabKidsMode; }
enableTabMode()
void TProjectManager::enableTabMode (bool tabMode) inline
Set the tab mode to the passed tabMode.
Note
the tab mode is used for Tab Application
{ m_tabMode = tabMode; }
getCurrentProject()
TProjectP TProjectManager::getCurrentProject ()
Returns the current TProject.
If a current TProject() doesn't exist, load the project in the the current project path.
{
  if (currentProject.getPointer() == 0) {
    TFilePath fp = getCurrentProjectPath();
    assert(TProject::isAProjectPath(fp));
    currentProject = new TProject();
    currentProject->load(fp);
    // update TFilePath condition on loading the current project
    FilePathProperties *fpProp = currentProject->getFilePathProperties();
    TFilePath::setFilePathProperties(fpProp->useStandard(),
                                     fpProp->acceptNonAlphabetSuffix(),
                                     fpProp->letterCountForSuffix());
  }
  return currentProject;
}
References getCurrentProjectPath(), and TProject::isAProjectPath().
Referenced by ToonzScene::createNewLevel(), ExportScenePopup::createNewProject(), and saveTemplate().
getCurrentProjectPath()
TFilePath TProjectManager::getCurrentProjectPath ()
Returns the current project path.
The project path, usually, is set in key registry. If a current project path isn't set, TProject::SandboxProjectName is set as current project.
{
  TFilePath fp(currentProjectPath);
  if (fp == TFilePath())
    fp = projectNameToProjectPath(TProject::SandboxProjectName);
  if (!TProject::isAProjectPath(fp)) {
    // in Toonz 5.1 e precedenti era un project name
    if (!fp.isAbsolute()) fp = getProjectPathByName(fp);
  }
  fp = searchProjectPath(fp.getParentDir());
  if (!TFileStatus(fp).doesExist())
    fp = projectNameToProjectPath(TProject::SandboxProjectName);
  fp       = getLatestVersionProjectPath(fp);
  string s = ::to_string(fp);
  if (s != (string)currentProjectPath) currentProjectPath = s;
  return fp;
}
References TFilePath::getParentDir(), getProjectPathByName(), TProject::isAProjectPath(), projectNameToProjectPath(), and TProject::SandboxProjectName.
Referenced by getCurrentProject(), getCurrentProjectRoot(), initializeScene(), and TProject::isCurrent().
getCurrentProjectRoot()
TFilePath TProjectManager::getCurrentProjectRoot ()
returns the project root of the current project (if this fails, then returns the first project root)
{
  TFilePath currentProjectPath = getCurrentProjectPath();
  int i;
  for (i = 0; i < (int)m_projectsRoots.size(); i++)
    if (m_projectsRoots[i].isAncestorOf(currentProjectPath))
      return m_projectsRoots[i];
  for (i = 0; i < (int)m_svnProjectsRoots.size(); i++)
    if (m_svnProjectsRoots[i].isAncestorOf(currentProjectPath))
      return m_svnProjectsRoots[i];
  if (m_projectsRoots.empty())
    addDefaultProjectsRoot();  // shouldn't be necessary
  return m_projectsRoots[0];
}
References getCurrentProjectPath().
getFolderNames()
void TProjectManager::getFolderNames (std::vector< std::string > & names)
Gets all project folder names and put them in the passed vector names.
Note
All previous data contained in names are lost.
{
  names.clear();
  TFilePath fp = ToonzFolder::getProfileFolder() + "project_folders.txt";
  try {
    Tifstream is(fp);
    if (is)
      for (;;) {
        char buffer[1024];
        is.getline(buffer, sizeof(buffer));
        if (is.eof()) break;
        char *s = buffer;
        while (*s == ' ' || *s == '\t') s++;  // skips blanks
        char *t = s;
        while (*t && *t != '\r' && *t != '\n') t++;  // reads up to end of line
        while (t > s && (t[-1] == ' ' || t[-1] == '\t'))
          t--;  // remove trailing blanks
        t[0] = '\0';
        if (s[0]) names.push_back(string(s));
      }
  } catch (...) {
  }
  const std::string stdNames[] = {TProject::Inputs,  TProject::Drawings,
                                  TProject::Scenes,  TProject::Extras,
                                  TProject::Outputs, TProject::Scripts};
  for (auto const &name : stdNames) {
    // se il nome non e' gia' stato inserito lo aggiungo
    if (std::find(names.begin(), names.end(), name) == names.end())
      names.push_back(name);
  }
}
References TProject::Drawings, TProject::Extras, TProject::Inputs, TProject::Outputs, TProject::Scenes, and TProject::Scripts.
Referenced by createStandardProject(), and TProject::save().
getProjectPathByName()
TFilePath TProjectManager::getProjectPathByName (const TFilePath & projectName)
Returns the absolute path of the specified projectName only if the project already exist.
Returns TFilePath() if a project with the specified projectName doesn't exist.
Note
projectName must be a relative path.
{
  assert(!TProject::isAProjectPath(projectName));
  assert(!projectName.isAbsolute());
  // TFilePath relativeProjectPath = projectName + (projectName.getName() +
  // projectPathSuffix);
  if (m_projectsRoots.empty()) addDefaultProjectsRoot();
  if (projectName == TProject::SandboxProjectName)
    return searchProjectPath(TEnv::getStuffDir() + projectName);
  int i, n = (int)m_projectsRoots.size();
  for (i = 0; i < n; i++) {
    TFilePath projectPath = searchProjectPath(m_projectsRoots[i] + projectName);
    assert(TProject::isAProjectPath(projectPath));
    if (TFileStatus(projectPath).doesExist()) return projectPath;
  }
  for (i = 0; i < (int)m_svnProjectsRoots.size(); i++) {
    TFilePath projectPath =
        searchProjectPath(m_svnProjectsRoots[i] + projectName);
    assert(TProject::isAProjectPath(projectPath));
    if (TFileStatus(projectPath).doesExist()) return projectPath;
  }
  return TFilePath();
}
References TProject::isAProjectPath(), and TProject::SandboxProjectName.
Referenced by ExportScenePopup::createNewProject(), getCurrentProjectPath(), getSandboxProjectPath(), and loadSceneProject().
getProjectPathByProjectFolder()
TFilePath TProjectManager::getProjectPathByProjectFolder (const TFilePath & projectFolder)
{
  assert(projectFolder.isAbsolute());
  TFilePath projectPath = searchProjectPath(projectFolder);
  return projectPathToProjectName(projectPath);
}
getProjectRoots()
void TProjectManager::getProjectRoots (std::vector< TFilePath > & projectRoots) const inline
{
    projectRoots = m_projectsRoots;
  }
getSandboxProjectFolder()
TFilePath TProjectManager::getSandboxProjectFolder ()
Return the absolute path of the standard folder "sandbox".
{
  return getSandboxProjectPath().getParentDir();
}
References TFilePath::getParentDir(), and getSandboxProjectPath().
getSandboxProjectPath()
TFilePath TProjectManager::getSandboxProjectPath ()
Return the absolute path of the standard project "sandbox_prj6.xml" file.
{
  return getProjectPathByName(TProject::SandboxProjectName);
}
References getProjectPathByName(), and TProject::SandboxProjectName.
Referenced by createSandboxIfNeeded(), getSandboxProjectFolder(), and loadSceneProject().
initializeScene()
void TProjectManager::initializeScene (ToonzScene * scene)
Initializes the specified scene using the TSceneProperties of the current project.
See also
TSceneProperties
{
  TProject *project       = scene->getProject();
  TSceneProperties *sprop = scene->getProperties();
  TFilePath currentProjectPath = getCurrentProjectPath();
  project->load(currentProjectPath);
  sprop->assign(&project->getSceneProperties());
  CleanupParameters::GlobalParameters.assign(
      project->getSceneProperties().getCleanupParameters());
  // scene->setProject(this);
  scene->setUntitled();
  sprop->cloneCamerasTo(scene->getTopXsheet()->getStageObjectTree());
  sprop->onInitialize();
  // scene->save(scene->getScenePath());
}
References TSceneProperties::assign(), TSceneProperties::cloneCamerasTo(), TSceneProperties::getCleanupParameters(), getCurrentProjectPath(), ToonzScene::getProject(), ToonzScene::getProperties(), TProject::getSceneProperties(), TXsheet::getStageObjectTree(), ToonzScene::getTopXsheet(), TProject::load(), TSceneProperties::onInitialize(), and ToonzScene::setUntitled().
instance()
TProjectManager * TProjectManager::instance () static
Returns the instance to the TProjectManager.
If an instance doesn't exist, creates one.
{
  static TProjectManager _instance;
  return &_instance;
}
Referenced by ToonzScene::createNewLevel(), ExportScenePopup::createNewProject(), ToonzScene::decodeFilePath(), TProject::isCurrent(), TProject::load(), ToonzScene::loadNoResources(), and TProject::save().
isProject()
bool TProjectManager::isProject (const TFilePath & projectFolder)
{
  TFilePath projectPath = projectFolderToProjectPath(projectFolder);
  return TFileStatus(projectPath).doesExist();
}
isTabKidsModeEnabled()
bool TProjectManager::isTabKidsModeEnabled () const inline
{ return m_tabKidsMode; }
isTabModeEnabled()
bool TProjectManager::isTabModeEnabled () const inline
Returns the tab mode.
Note
the tab mode is used for Tab Application
{ return m_tabMode; }
loadSceneProject()
TProjectP TProjectManager::loadSceneProject (const TFilePath & scenePath)
Returns the TProjectP in which the specified scenePath is saved.
Returns 0 if scenePath isn't a valid scene, or isn't saved in a valid folder of a project root.
Note
scenePath must be an absolute path.
Creates a new TProject. The caller gets ownership.
{
  // cerca il file scenes.xml nella stessa directory della scena
  // oppure in una
  // directory superiore
  TFilePath folder = scenePath.getParentDir();
  TFilePath sceneDesc;
  bool found = true;
  for (;;) {
    sceneDesc = folder + "scenes.xml";
    if (TFileStatus(sceneDesc).doesExist()) break;
    if (folder.isRoot()) {
      found = false;
      break;
    }
    folder = folder.getParentDir();
  }
  // legge il path (o il nome) del progetto
  TFilePath projectPath;
  if (found) {
    try {
      TIStream is(sceneDesc);
      string tagName;
      is.matchTag(tagName);
      string type = is.getTagAttribute("type");
      TFilePath projectFolderPath;
      is >> projectFolderPath;
      if (type == "") {
        projectFolderPath = TFilePath("..");
      }
      is.matchEndTag();
      projectPath = makeAbsolute(folder, projectFolderPath);
      TFilePath path = getProjectFile(projectPath);
      projectPath = path;
    } catch (...) {
    }
    if (projectPath == TFilePath()) return 0;
  } else
    projectPath = getSandboxProjectPath();
  if (!TProject::isAProjectPath(projectPath)) {
    // in Toonz 5.1 e precedenti era un project name
    if (!projectPath.isAbsolute())
      projectPath = getProjectPathByName(projectPath);
    else
      return 0;
  }
  if (!TFileStatus(projectPath).doesExist()) return 0;
  TProject *project = new TProject();
  project->load(projectPath);
  return project;
}
References TFilePath::getParentDir(), getProjectPathByName(), getSandboxProjectPath(), TIStream::getTagAttribute(), TProject::isAProjectPath(), TProject::load(), TIStream::matchEndTag(), and TIStream::matchTag().
Referenced by ToonzScene::loadNoResources().
notifyProjectChanged()
void TProjectManager::notifyProjectChanged ()
{
  for (std::set<Listener *>::iterator i = m_listeners.begin();
       i != m_listeners.end(); ++i)
    (*i)->onProjectChanged();
}
projectFolderToProjectPath()
TFilePath TProjectManager::projectFolderToProjectPath (const TFilePath & projectFolder)
Returns the absolute path of the project file respect to the specified projectFolder.
Note
projectName must be an absolute path.
{
  assert(projectFolder.isAbsolute());
  return searchProjectPath(projectFolder);
}
Referenced by ExportScenePopup::createNewProject().
projectNameToProjectPath()
TFilePath TProjectManager::projectNameToProjectPath (const TFilePath & projectName)
Returns an absolute path of the specified projectName.
Note
The returned project path is always computed used the first project root in the container.
{
  assert(!TProject::isAProjectPath(projectName));
  assert(!projectName.isAbsolute());
  if (m_projectsRoots.empty()) addDefaultProjectsRoot();
  if (projectName == TProject::SandboxProjectName)
    return searchProjectPath(TEnv::getStuffDir() + projectName);
  return searchProjectPath(m_projectsRoots[0] + projectName);
}
References TProject::isAProjectPath(), and TProject::SandboxProjectName.
Referenced by getCurrentProjectPath().
projectPathToProjectName()
TFilePath TProjectManager::projectPathToProjectName (const TFilePath & projectPath)
Returns the name of the specified projectPath.
Note
projectPath must be an absolute path.
{
  assert(projectPath.isAbsolute());
  TFilePath projectFolder = projectPath.getParentDir();
  if (m_projectsRoots.empty()) addDefaultProjectsRoot();
  std::wstring fpName = projectPath.getWideName();
  for (int i = 0; i < prjSuffixCount; ++i) {
    //    std::wstring::size_type const i = fpName.find(prjSuffix[i]);
    if (fpName.find(prjSuffix[i]) != std::wstring::npos)
      return TFilePath(fpName.substr(0, fpName.find(prjSuffix[i])));
  }
  int i;
  for (i = 0; i < (int)m_projectsRoots.size(); i++) {
    if (m_projectsRoots[i].isAncestorOf(projectFolder))
      return projectFolder - m_projectsRoots[i];
  }
  for (i = 0; i < (int)m_svnProjectsRoots.size(); i++) {
    if (m_svnProjectsRoots[i].isAncestorOf(projectFolder))
      return projectFolder - m_svnProjectsRoots[i];
  }
  // non dovrei mai arrivare qui: il progetto non sta sotto un project root
  return projectFolder.withoutParentDir();
}
References TFilePath::getParentDir(), and TFilePath::withoutParentDir().
Referenced by TProject::load(), and TProject::save().
removeListener()
void TProjectManager::removeListener (Listener * listener)
Removes listener from the listeners container.
{
  m_listeners.erase(listener);
}
saveTemplate()
void TProjectManager::saveTemplate (ToonzScene * scene)
Saves the TSceneProperties of the specified scene in the current project.
{
  TSceneProperties props;
  props.assign(scene->getProperties());
  props.cloneCamerasFrom(scene->getXsheet()->getStageObjectTree());
  // camera capture's "save in" path is saved in env, not in the project
  props.setCameraCaptureSaveInPath(TFilePath());
  TProjectP currentProject = getCurrentProject();
  currentProject->setSceneProperties(props);
  currentProject->save();
}
References TSceneProperties::assign(), TSceneProperties::cloneCamerasFrom(), getCurrentProject(), ToonzScene::getProperties(), TXsheet::getStageObjectTree(), and ToonzScene::getXsheet().
setCurrentProjectPath()
void TProjectManager::setCurrentProjectPath (const TFilePath & fp)
Set the the path fp as current project path.
fp must be an absolute path.
{
  assert(TProject::isAProjectPath(fp));
  currentProjectPath = ::to_string(fp.getWideString());
  currentProject     = TProjectP();
  notifyListeners();
}
References TProject::isAProjectPath().
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/toonz/tproject.h
E:/opentoonz/toonz/sources/toonzlib/tproject.cpp