opentoonz: PreviewSubCameraManager Class Reference
PreviewSubCameraManager Class Reference final
Public Types
enum EditPreviewDrag {
NODRAG = 0x0 , OUTER_LEFT = 0x1 , INNER_LEFT = 0x2 , OUTER_RIGHT = 0x4 ,
INNER_RIGHT = 0x8 , OUTER_TOP = 0x10 , INNER_TOP = 0x20 , OUTER_BOTTOM = 0x40 ,
INNER_BOTTOM = 0x80 , OUTER = OUTER_LEFT | OUTER_RIGHT | OUTER_TOP | OUTER_BOTTOM , INNER = INNER_LEFT | INNER_RIGHT | INNER_TOP | INNER_BOTTOM , DRAG_LEFT = OUTER_LEFT | INNER ,
DRAG_RIGHT = OUTER_RIGHT | INNER , DRAG_TOP = OUTER_TOP | INNER , DRAG_BOTTOM = OUTER_BOTTOM | INNER
}
Public Member Functions
UCHAR getDragType () const
void setDragType (UCHAR dragType)
TRect getEditingCameraInterestRect () const
void setEditingCameraInterestRect (const TRect &rect)
TRectD getEditingCameraInterestStageRect () const
bool mousePressEvent (SceneViewer *viewer, const TMouseEvent &event)
bool mouseMoveEvent (SceneViewer *viewer, const TMouseEvent &event)
bool mouseReleaseEvent (SceneViewer *viewer)
void deleteSubCamera (SceneViewer *viewer)
Public Member Functions inherited from SceneViewerInteractiveGadget
virtual int getPriority () const
virtual bool mousePressEvent (SceneViewer *viewer, QMouseEvent *me)
virtual bool mouseMoveEvent (SceneViewer *viewer, QMouseEvent *me)
virtual bool mouseReleaseEvent (SceneViewer *viewer, QMouseEvent *me)
virtual void draw (SceneViewer *viewer, QPaintEvent *pe)
Static Public Member Functions
static PreviewSubCameraManager * instance ()
Detailed Description
Member Enumeration Documentation
EditPreviewDrag
enum PreviewSubCameraManager::EditPreviewDrag
                       {
    NODRAG       = 0x0,
    OUTER_LEFT   = 0x1,
    INNER_LEFT   = 0x2,
    OUTER_RIGHT  = 0x4,
    INNER_RIGHT  = 0x8,
    OUTER_TOP    = 0x10,
    INNER_TOP    = 0x20,
    OUTER_BOTTOM = 0x40,
    INNER_BOTTOM = 0x80,
    OUTER        = OUTER_LEFT | OUTER_RIGHT | OUTER_TOP | OUTER_BOTTOM,
    INNER        = INNER_LEFT | INNER_RIGHT | INNER_TOP | INNER_BOTTOM,
    DRAG_LEFT    = OUTER_LEFT | INNER,
    DRAG_RIGHT   = OUTER_RIGHT | INNER,
    DRAG_TOP     = OUTER_TOP | INNER,
    DRAG_BOTTOM  = OUTER_BOTTOM | INNER
  };
Constructor & Destructor Documentation
PreviewSubCameraManager()
PreviewSubCameraManager::PreviewSubCameraManager ()
    : m_mousePressed(false), m_dragType(NODRAG), m_clickAndDrag(false) {}
~PreviewSubCameraManager()
PreviewSubCameraManager::~PreviewSubCameraManager ()
{}
Member Function Documentation
deleteSubCamera()
void PreviewSubCameraManager::deleteSubCamera (SceneViewer * viewer)
Delete sub camera frame. Executed from context menu of the viewer.
{
  TCamera *camera =
      TApp::instance()->getCurrentScene()->getScene()->getCurrentCamera();
  camera->setInterestRect(TRect());
  Previewer::instance(true)->updateView();
  // Refresh viewer
  viewer->update();
}
References ToonzScene::getCurrentCamera(), TApp::getCurrentScene(), TApp::instance(), Previewer::instance(), TCamera::setInterestRect(), and Previewer::updateView().
Referenced by SceneViewer::doDeleteSubCamera().
getDragType()
UCHAR PreviewSubCameraManager::getDragType () const inline
{ return m_dragType; }
getEditingCameraInterestRect()
TRect PreviewSubCameraManager::getEditingCameraInterestRect () const
{
  if (m_mousePressed)
    return m_editingInterestRect;
  else {
    // Return the actual current camera's interest rect
    TCamera *currCamera =
        TApp::instance()->getCurrentScene()->getScene()->getCurrentCamera();
    return currCamera->getInterestRect();
  }
}
getEditingCameraInterestStageRect()
TRectD PreviewSubCameraManager::getEditingCameraInterestStageRect () const
{
  TCamera *currCamera =
      TApp::instance()->getCurrentScene()->getScene()->getCurrentCamera();
  if (m_mousePressed)
    // Build the stage rect associated with m_editingInterestRect
    return currCamera->getCameraToStageRef() *
           TRectD(m_editingInterestRect.x0, m_editingInterestRect.y0,
                  m_editingInterestRect.x1 + 1, m_editingInterestRect.y1 + 1);
  else
    // Return the actual current camera's stage interest rect
    return currCamera->getInterestStageRect();
}
instance()
PreviewSubCameraManager * PreviewSubCameraManager::instance () static
{
  static PreviewSubCameraManager theInstance;
  return &theInstance;
}
mouseMoveEvent()
bool PreviewSubCameraManager::mouseMoveEvent (SceneViewer * viewer, const TMouseEvent & event)
{
  if (viewer->is3DView()) return true;
  QPointF curPos(event.mousePos() * getDevPixRatio());
  if (event.buttons() == Qt::LeftButton) {
    if (!bitwiseContains(m_dragType, INNER)) {
      if (std::abs(curPos.x() - m_mousePressPos.x()) > 10 ||
          std::abs(curPos.y() - m_mousePressPos.y()) > 10)
        m_clickAndDrag = true;
    }
    if (m_clickAndDrag == true) {
      // Write the temporary preview subcamera to current camera
      TPointD worldMousePressPos(viewer->winToWorld(m_mousePressPos));
      TPointD worldCurPos(viewer->winToWorld(curPos));
      TApp *app = TApp::instance();
      TAffine cameraAffInv(
          app->getCurrentXsheet()
              ->getXsheet()
              ->getCameraAff(app->getCurrentFrame()->getFrame())
              .inv());
      worldMousePressPos = cameraAffInv * worldMousePressPos;
      worldCurPos        = cameraAffInv * worldCurPos;
      TRectD worldPreviewSubCameraRect(
          std::min(worldMousePressPos.x, worldCurPos.x),
          std::min(worldMousePressPos.y, worldCurPos.y),
          std::max(worldMousePressPos.x, worldCurPos.x),
          std::max(worldMousePressPos.y, worldCurPos.y));
      TCamera *camera = app->getCurrentScene()->getScene()->getCurrentCamera();
      // camera->setInterestStageRect(worldPreviewSubCameraRect);
      TRectD previewSubCameraD(camera->getStageToCameraRef() *
                               worldPreviewSubCameraRect);
      m_editingInterestRect =
          TRect(previewSubCameraD.x0, previewSubCameraD.y0,
                previewSubCameraD.x1 - 1, previewSubCameraD.y1 - 1) *
          TRect(camera->getRes());
      viewer->update();
    } else {
      TPoint dragDistance = getSubCameraDragDistance(viewer, curPos);
      // Adjust the camera subrect
      TCamera *camera =
          TApp::instance()->getCurrentScene()->getScene()->getCurrentCamera();
      TRect subRect(camera->getInterestRect());
      if (bitwiseExclude(m_dragType, OUTER))
        subRect += dragDistance;
      else {
        if (bitwiseContains(m_dragType, DRAG_LEFT))
          subRect.x0 = subRect.x0 + dragDistance.x;
        else if (bitwiseContains(m_dragType, DRAG_RIGHT))
          subRect.x1 = subRect.x1 + dragDistance.x;
        if (bitwiseContains(m_dragType, DRAG_BOTTOM))
          subRect.y0 = subRect.y0 + dragDistance.y;
        else if (bitwiseContains(m_dragType, DRAG_TOP))
          subRect.y1 = subRect.y1 + dragDistance.y;
      }
      m_editingInterestRect = subRect * TRect(camera->getRes());
      viewer->update();
    }
  } else {
    UCHAR dragEnum = getSubCameraDragEnum(viewer, curPos);
    if (dragEnum == NODRAG)
      viewer->setCursor(Qt::ArrowCursor);
    else if (bitwiseExclude(dragEnum, OUTER))
      viewer->setCursor(Qt::SizeAllCursor);
    else
      switch (dragEnum) {
      case DRAG_LEFT:
      case DRAG_RIGHT:
        viewer->setCursor(Qt::SizeHorCursor);
        break;
      case DRAG_TOP:
      case DRAG_BOTTOM:
        viewer->setCursor(Qt::SizeVerCursor);
        break;
      case DRAG_LEFT | DRAG_TOP:
      case DRAG_RIGHT | DRAG_BOTTOM:
        viewer->setCursor(Qt::SizeFDiagCursor);
        break;
      case DRAG_LEFT | DRAG_BOTTOM:
      case DRAG_RIGHT | DRAG_TOP:
        viewer->setCursor(Qt::SizeBDiagCursor);
        break;
      default:
        viewer->setCursor(Qt::ArrowCursor);
        break;
      }
  }
  // In case, perform the pan
  return event.buttons() == Qt::MidButton;
}
mousePressEvent()
bool PreviewSubCameraManager::mousePressEvent (SceneViewer * viewer, const TMouseEvent & event)
{
  if (viewer->is3DView()) return true;
  m_mousePressed  = true;
  m_mousePressPos = event.mousePos() * getDevPixRatio();
  m_dragType      = getSubCameraDragEnum(viewer, m_mousePressPos);
  if (bitwiseExclude(m_dragType, OUTER))
    m_cameraMousePressPos = winToCamera(viewer, m_mousePressPos);
  return false;
}
mouseReleaseEvent()
bool PreviewSubCameraManager::mouseReleaseEvent (SceneViewer * viewer)
{
  if (viewer->is3DView()) return true;
  m_mousePressed = false;
  m_dragType     = NODRAG;
  m_clickAndDrag = false;
  TCamera *camera =
      TApp::instance()->getCurrentScene()->getScene()->getCurrentCamera();
  camera->setInterestRect(m_editingInterestRect);
  // Request a previewer update. Observe that whereas this previewer may not be
  // in preview mode,
  // another visible one may.
  Previewer::instance(true)->updateView();
  // Refresh viewer
  viewer->update();
  return false;
}
setDragType()
void PreviewSubCameraManager::setDragType (UCHAR dragType) inline
{ m_dragType = dragType; }
setEditingCameraInterestRect()
void PreviewSubCameraManager::setEditingCameraInterestRect (const TRect & rect) inline
{
    m_editingInterestRect = rect;
  }
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/toonz/subcameramanager.h
E:/opentoonz/toonz/sources/toonz/subcameramanager.cpp