opentoonz: TStrokeThicknessDeformation Class Reference
TStrokeThicknessDeformation Class Reference final
#include <tstrokedeformations.h>
Public Member Functions
TStrokeThicknessDeformation (const TStroke *stroke, double parameterOfNearest, double lengthOfDeformation=100)
TStrokeThicknessDeformation (const TStroke *stroke, const TPointD &vect, double parameterOfNearest, double lengthOfDeformation=100, double versus=1.0)
TThickPoint getDisplacement (const TStroke &, double) const override
TThickPoint getDisplacementForControlPoint (const TStroke &stroke, UINT n) const override
TThickPoint getDisplacementForControlPointLen (const TStroke &stroke, double cpLen) const override
double getDelta (const TStroke &, double) const override
double getMaxDiff () const override
virtual TThickPoint getDisplacement (const TStroke &stroke, double w) const =0
virtual TThickPoint getDisplacementForControlPoint (const TStroke &stroke, UINT n) const =0
virtual TThickPoint getDisplacementForControlPointLen (const TStroke &stroke, double cpLen) const =0
virtual double getDelta (const TStroke &stroke, double w) const =0
virtual double getMaxDiff () const =0
Detailed Description
Manage the deformation of thick in a stroke.
Constructor & Destructor Documentation
TStrokeThicknessDeformation() [1/2]
TStrokeThicknessDeformation::TStrokeThicknessDeformation (const TStroke * stroke, double parameterOfNearest, double lengthOfDeformation = 100)
    : m_lengthOfDeformation(l), m_startParameter(s), m_vect(0), m_pRef(ref) {
  assert(m_lengthOfDeformation >= 0);
  if (isAlmostZero(m_lengthOfDeformation))
    m_lengthOfDeformation = TConsts::epsilon;
}
TStrokeThicknessDeformation() [2/2]
TStrokeThicknessDeformation::TStrokeThicknessDeformation (const TStroke * stroke, const TPointD & vect, double parameterOfNearest, double lengthOfDeformation = 100, double versus = 1.0)
Use this constructor with movePoints.
    : m_lengthOfDeformation(l)
    , m_startParameter(s)
    , m_versus(versus)
    , m_vect(new TPointD(vect))
    , m_pRef(ref) {
  assert(m_lengthOfDeformation >= 0);
  if (isAlmostZero(m_lengthOfDeformation))
    m_lengthOfDeformation = TConsts::epsilon;
}
~TStrokeThicknessDeformation()
TStrokeThicknessDeformation::~TStrokeThicknessDeformation () virtual
{ delete m_vect; }
Member Function Documentation
getDelta()
double TStrokeThicknessDeformation::getDelta (const TStroke & stroke, double w) const override virtual
| d getDisplacement() / dw |
stroke to test
w stroke parameter
\ret | d getDisplacement() / dw |
Implements TStrokeDeformation.
{
  // potenziale exp^(-x^2) limitato tra
  // [-c_maxLengthOfGaussian,c_maxLengthOfGaussian]
  double diff = stroke.getLength(w);
  diff = diff - m_startParameter;
  if (fabs(diff) <= m_lengthOfDeformation) {
    // modulo il vettore spostamento in funzione  del potenziale
    //  il termine (1.0/m_lengthOfDeformation) * 3 scala
    //  il punto in diff su un sistema di coordinate
    //  normalizzato, associato con la curva exp^(-x^2)
    diff *= (1.0 / m_lengthOfDeformation) * c_maxLengthOfGaussian;
    return derivateOfGaussianPotential(diff);
  }
  return 0;
}
References TStroke::getLength().
getDisplacement()
TThickPoint TStrokeThicknessDeformation::getDisplacement (const TStroke & stroke, double w) const override virtual
return displacement to use with function increaseControlPoints
stroke to test
w stroke parameter
\ret displacement to apply to obtain deformation
See also
increaseControlPoints
Implements TStrokeDeformation.
{
  // potenziale exp^(-x^2) limitato tra
  // [-c_maxLengthOfGaussian,c_maxLengthOfGaussian]
  double diff = stroke.getLength(w);
  diff = diff - m_startParameter;
  if (fabs(diff) <= m_lengthOfDeformation) {
    // modulo il vettore spostamento in funzione  del potenziale
    //  il termine (1.0/m_lengthOfDeformation) * 3 scala
    //  il punto in diff su un sistema di coordinate
    //  normalizzato, associato con la curva exp^(-x^2)
    diff *= (1.0 / m_lengthOfDeformation) * c_maxLengthOfGaussian;
    if (m_vect)
      return gaussianPotential(diff) * TThickPoint(*m_vect, 0);
    else {
      double outVal = gaussianPotential(diff);
      return TThickPoint(0, 0, outVal);
    }
  }
  return TThickPoint();
}
References TStroke::getLength().
getDisplacementForControlPoint()
TThickPoint TStrokeThicknessDeformation::getDisplacementForControlPoint (const TStroke & stroke, UINT n) const override virtual
return displacement to use with function modifyControlPoints
stroke to test
n control point to get
\ret displacement to apply to obtain deformation
See also
modifyControlPoints
Implements TStrokeDeformation.
{
  // potenziale exp^(-x^2) limitato tra
  // [-c_maxLengthOfGaussian,c_maxLengthOfGaussian]
  double diff = stroke.getLengthAtControlPoint(n);
  diff = diff - m_startParameter;
  if (fabs(diff) <= m_lengthOfDeformation) {
    // modulo il vettore spostamento in funzione  del potenziale
    //  il termine (1.0/m_lengthOfDeformation) * 3 scala
    //  il punto in diff su un sistema di coordinate
    //  normalizzato, associato con la curva exp^(-x^2)
    diff *= (1.0 / m_lengthOfDeformation) * c_maxLengthOfGaussian;
    TThickPoint delta;
    if (m_vect) {
      // tsign(m_vect->y) * 0.1
      delta =
          TThickPoint(0, 0, m_versus * norm(*m_vect) * gaussianPotential(diff));
    } else {
      double outVal = gaussianPotential(diff);
      delta         = TThickPoint(0, 0, outVal);
    }
    // TThickPoint cp = stroke.getControlPoint(n);
    // if(cp.thick + delta.thick<0.001) delta.thick = 0.001-cp.thick;
    return delta;
  }
  return TThickPoint();
}
References TStroke::getLengthAtControlPoint().
getDisplacementForControlPointLen()
TThickPoint TStrokeThicknessDeformation::getDisplacementForControlPointLen (const TStroke & stroke, double cpLen) const override virtual
Implements TStrokeDeformation.
{
  if (fabs(diff) <= m_lengthOfDeformation) {
    // modulo il vettore spostamento in funzione  del potenziale
    //  il termine (1.0/m_lengthOfDeformation) * 3 scala
    //  il punto in diff su un sistema di coordinate
    //  normalizzato, associato con la curva exp^(-x^2)
    diff *= (1.0 / m_lengthOfDeformation) * c_maxLengthOfGaussian;
    TThickPoint delta;
    if (m_vect) {
      // tsign(m_vect->y) * 0.1
      delta =
          TThickPoint(0, 0, m_versus * norm(*m_vect) * gaussianPotential(diff));
    } else {
      double outVal = gaussianPotential(diff);
      delta         = TThickPoint(0, 0, outVal);
    }
    // TThickPoint cp = stroke.getControlPoint(n);
    // if(cp.thick + delta.thick<0.001) delta.thick = 0.001-cp.thick;
    return delta;
  }
  return TThickPoint();
}
getMaxDiff()
double TStrokeThicknessDeformation::getMaxDiff () const override virtual
Max diff of delta (This value indicates when it's necessary to insert control point) \ret max displacement permitted
Implements TStrokeDeformation.
{ return 0.09; }
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/tstrokedeformations.h
E:/opentoonz/toonz/sources/common/tvrender/tstrokedeformations.cpp