opentoonz: TDockWidget Class Reference
TDockWidget Class Reference
#include <tdockwindows.h>
Public Types
enum Orientation { horizontal = 0 , vertical = 1 }
Public Types inherited from DockWidget
enum { leftMargin = 0x1 , rightMargin = 0x2 , topMargin = 0x4 , bottomMargin = 0x8 }
Public Member Functions
TDockWidget (const QString &title, QWidget *parent=0, Qt::WindowFlags flags=0)
TDockWidget (QWidget *parent=0, Qt::WindowFlags flags=0)
void setTitleBarWidget (QWidget *titlebar)
QWidget * titleBarWidget () const
void setFloatingMargin (int margin)
int getFloatingMargin () const
void setWidget (QWidget *widget)
QWidget * widget () const
void setFloating (bool status=true)
void setMaximized (bool status=true)
Maximizes this TDockWidget, if docked.
void setOrientation (bool direction=vertical)
bool getOrientation () const
Public Member Functions inherited from DockWidget
void maximizeDock ()
bool getCanFixWidth ()
void setCanFixWidth (bool fixed)
DockWidget (QWidget *parent=0, Qt::WindowFlags flags=Qt::Tool)
DockLayout * parentLayout () const
bool isFloating () const
bool wasFloating () const
void clearWasFloating ()
bool isMaximized () const
QWidget * hoveredWidget (QMouseEvent *me)
DockPlaceholder * placeAdjacentTo (DockWidget *dockWidget, int boundary)
DockPlaceholder * placeOfSeparator (DockSeparator *)
Returns placeholder associated with input separator.
const std::vector< DockPlaceholder * > & placeholders () const
virtual QSize getDockedMinimumSize ()
virtual QSize getDockedMaximumSize ()
virtual void setFloatingAppearance ()
virtual void setDockedAppearance ()
virtual bool isDragGrip (QPoint p)
Shows dock widget in docked mode.
virtual int isResizeGrip (QPoint)
virtual void selectDockPlaceholder (QMouseEvent *me)
void clearDockPlaceholders ()
void setDecoAllocator (DockDecoAllocator *decoAllocator)
NOTE: DockWidget takes ownership of the allocator.
virtual void onDock (bool docked)
Additional Inherited Members
Protected Member Functions inherited from DockWidget
void wheelEvent (QWheelEvent *we) override
Switch in selected dock placeholder's hierarchy.
void mouseDoubleClickEvent (QMouseEvent *me) override
virtual void windowTitleEvent (QEvent *)
Protected Attributes inherited from DockWidget
bool m_floating
bool m_wasFloating
bool m_dragging
bool m_undocking
bool m_resizing
int m_marginType
bool m_maximized
bool m_canFixWidth = false
std::vector< DockPlaceholder * > m_placeholders
DockPlaceholder * m_selectedPlace
Detailed Description
TDockWidget class is a convenience QDockWidget-like interface to DockWidget class. It provides an internal base layout including a titlebar and a content widget.
See also
TMainWindow class.
Member Enumeration Documentation
Orientation
enum TDockWidget::Orientation
{ horizontal = 0, vertical = 1 };
Constructor & Destructor Documentation
TDockWidget() [1/2]
TDockWidget::TDockWidget (const QString & title, QWidget * parent = 0, Qt::WindowFlags flags = 0)
    : DockWidget(parent, flags), m_widget(0), m_titlebar(0), m_margin(5) {
  setWindowTitle(title);
  QBoxLayout *layout = new QBoxLayout(QBoxLayout::TopToBottom);
  layout->setSpacing(0);
  setLayout(layout);
}
TDockWidget() [2/2]
TDockWidget::TDockWidget (QWidget * parent = 0, Qt::WindowFlags flags = 0)
Constructs a TDockWidget with given parent and window flags. If parent is a TMainWindow, then the constructed dock widget is assigned to it (addDockWidget'd). TDockWidgets are always floating at construction.
    : DockWidget(parent, flags), m_widget(0), m_titlebar(0), m_margin(5) {
  setAutoFillBackground(false);
  // setFrameStyle(QFrame::StyledPanel);
  QBoxLayout *layout = new QBoxLayout(QBoxLayout::TopToBottom);
  layout->setSpacing(0);
  setLayout(layout);
  // Check if parent is a TMainWindow class
  TMainWindow *parentMain = qobject_cast<TMainWindow *>(parent);
  if (parentMain) parentMain->addDockWidget(this);
  setDecoAllocator(new TDockDecoAllocator);
}
References TMainWindow::addDockWidget(), and DockWidget::setDecoAllocator().
~TDockWidget()
TDockWidget::~TDockWidget () inline
{}
Member Function Documentation
getFloatingMargin()
int TDockWidget::getFloatingMargin () const inline
{ return m_margin; }
getOrientation()
bool TDockWidget::getOrientation () const
{
  QBoxLayout *boxLayout = static_cast<QBoxLayout *>(layout());
  return (boxLayout->direction() == QBoxLayout::TopToBottom) ? vertical
                                                             : horizontal;
}
setFloating()
void TDockWidget::setFloating (bool status = true)
Currently working only for status = true. If you need to dock a TDockWidget, you must specify a dock location by either choosing a placeholder or identifying the Region and insertion index, and then running 'parentLayout()->dockItem(..)'.
{
  if (status) {
    setWindowFlags(Qt::Tool | Qt::FramelessWindowHint);
    if (!m_floating) parentLayout()->undockItem(this);
  }
}
References DockLayout::undockItem().
Referenced by FlipBookPool::pop().
setFloatingMargin()
void TDockWidget::setFloatingMargin (int margin) inline
{ m_margin = margin; }
setMaximized()
void TDockWidget::setMaximized (bool status = true)
Maximizes this TDockWidget, if docked.
{
  parentLayout()->setMaximized(this, status);
}
setOrientation()
void TDockWidget::setOrientation (bool direction = vertical)
Specifies the orientation of the dock widget. It can be either vertical (default) or horizontal, meaning that the titlebar is laid respectively at the top or left side of content widget. Directly speaking, it is equivalent to setting the Qt's QDockWidget::DockWidgetVerticalTitleBar feature.
{
  QBoxLayout *boxLayout = static_cast<QBoxLayout *>(layout());
  QBoxLayout::Direction boxDirection;
  if (direction == vertical) {
    boxLayout->setAlignment(m_titlebar, Qt::AlignTop);
    boxDirection = QBoxLayout::TopToBottom;
  } else {
    boxLayout->setAlignment(m_titlebar, Qt::AlignLeft);
    boxDirection = QBoxLayout::LeftToRight;
  }
  boxLayout->setDirection(boxDirection);
}
setTitleBarWidget()
void TDockWidget::setTitleBarWidget (QWidget * titlebar)
{
  if (titlebar) {
    QBoxLayout *boxLayout = static_cast<QBoxLayout *>(layout());
    if (m_titlebar && m_titlebar != titlebar)
      boxLayout->removeWidget(m_titlebar);
    boxLayout->insertWidget(0, titlebar);
    // Set top/left-aligned
    boxLayout->setAlignment(
        titlebar, getOrientation() == vertical ? Qt::AlignTop : Qt::AlignLeft);
    m_titlebar = titlebar;
    if (m_floating) setFloatingAppearance();
  }
}
setWidget()
void TDockWidget::setWidget (QWidget * widget)
{
  if (widget) {
    QBoxLayout *boxLayout = static_cast<QBoxLayout *>(layout());
    if (m_widget && m_widget != widget) boxLayout->removeWidget(m_widget);
    boxLayout->insertWidget(1, widget);
    widget->setSizePolicy(QSizePolicy::Expanding, QSizePolicy::Expanding);
    m_widget = widget;
  }
}
titleBarWidget()
QWidget * TDockWidget::titleBarWidget () const inline
{ return m_titlebar; }
widget()
QWidget * TDockWidget::widget () const inline
{ return m_widget; }
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/toonzqt/tdockwindows.h
E:/opentoonz/toonz/sources/toonzqt/tdockwindows.cpp