opentoonz: SceneViewer Class Reference
SceneViewer Class Reference final
Public Types
enum ReferenceMode { NORMAL_REFERENCE = 1 , CAMERA3D_REFERENCE = 2 , CAMERA_REFERENCE = 3 , LEVEL_MODE = 128 }
enum ViewMode { SCENE_VIEWMODE = 0 , LEVEL_VIEWMODE = 1 }
enum PreviewMode { NO_PREVIEW = 0 , FULL_PREVIEW = 1 , SUBCAMERA_PREVIEW = 2 }
Public Slots
void resetSceneViewer ()
void resetZoom ()
void resetRotation ()
void resetPosition ()
void setActualPixelSize ()
void flipX ()
void flipY ()
void zoomIn ()
void zoomOut ()
void onXsheetChanged ()
void onObjectSwitched ()
void onToolChanged ()
void onToolSwitched ()
void onSceneChanged ()
void onLevelChanged ()
void onLevelSwitched ()
void onFrameSwitched ()
void onOnionSkinMaskChanged ()
void setReferenceMode (int referenceMode)
void enablePreview (int previewMode)
void freeze (bool on)
void onButtonPressed (FlipConsole::EGadget button)
void fitToCamera ()
void fitToCameraOutline ()
void swapCompared ()
void regeneratePreviewFrame ()
void regeneratePreview ()
void doDeleteSubCamera ()
void resetTabletStatus ()
void releaseBusyOnTabletMove ()
void onContextAboutToBeDestroyed ()
void onPreferenceChanged (const QString &prefName)
Signals
void onZoomChanged ()
void onFlipHChanged (bool)
void onFlipVChanged (bool)
void freezeStateChanged (bool)
void previewStatusChanged ()
void refreshNavi ()
void previewToggled ()
void aboutToBeDestroyed ()
Public Member Functions
SceneViewer (ImageUtils::FullScreenWidget *parent)
double getPixelSize () const override
TRectD getPreviewRect () const override
void onRenderStarted (int frame) override
void onRenderCompleted (int frame) override
void onPreviewUpdate () override
bool isPreviewEnabled () const
int getPreviewMode () const
void setVisual (const ImagePainter::VisualSettings &settings)
TRect getActualClipRect (const TAffine &aff)
TAffine getViewMatrix () const override
TAffine getSceneMatrix () const
void setViewMatrix (const TAffine &aff, int viewMode)
int getFPS ()
void setRulers (Ruler *v, Ruler *h)
bool is3DView () const override
TDimension getViewportSize () const
void invalidateAll () override
void GLInvalidateAll () override
void GLInvalidateRect (const TRectD &rect) override
void invalidateToolStatus () override
TPointD getPan3D () const
double getZoomScale3D () const
double projectToZ (const TPointD &delta) override
TPointD getDpiScale () const override
void zoomQt (bool forward, bool reset)
TAffine getNormalZoomScale ()
bool canSwapCompared () const
bool isEditPreviewSubcamera () const
bool getIsFlippedX () const override
bool getIsFlippedY () const override
void setEditPreviewSubcamera (bool enabled)
void navigatorPan (const QPoint &delta)
double getDpiFactor ()
double getZoomScaleFittingWithScreen ()
TRectD getGeometry () const override
void setFocus (Qt::FocusReason reason)
void setIsLocator ()
void setIsStyleShortcutSwitchable ()
int getVGuideCount () override
int getHGuideCount () override
double getVGuide (int index) override
double getHGuide (int index) override
void bindFBO () override
void releaseFBO () override
void setTimerAndTargetInstant (QElapsedTimer *timer, qint64 target)
TPointD winToWorld (const QPointF &pos) const
TPointD winToWorld (const TPointD &winPos) const override
TPointD worldToPos (const TPointD &worldPos) const override
return pos in pixel, bottom-left origin
Public Member Functions inherited from GLWidgetForHighDpi
GLWidgetForHighDpi (QWidget *parent=nullptr, Qt::WindowFlags f=Qt::WindowFlags())
int width () const
int height () const
QRect rect () const
Public Member Functions inherited from TTool::Viewer
const ImagePainter::VisualSettings & visualSettings () const
ImagePainter::VisualSettings & visualSettings ()
virtual double getPixelSize () const =0
virtual void invalidateAll ()=0
virtual void GLInvalidateAll ()=0
virtual void GLInvalidateRect (const TRectD &rect)=0
virtual void invalidateToolStatus ()=0
virtual TAffine getViewMatrix () const
virtual int posToColumnIndex (const TPointD &p, double distance, bool includeInvisible=true) const =0
virtual void posToColumnIndexes (const TPointD &p, std::vector< int > &indexes, double distance, bool includeInvisible=true) const =0
virtual int posToRow (const TPointD &p, double distance, bool includeInvisible=true, bool currentColumnOnly=false) const =0
virtual TPointD worldToPos (const TPointD &worldPos) const =0
return pos in pixel, bottom-left origin
virtual int pick (const TPointD &point)=0
virtual TPointD winToWorld (const TPointD &winPos) const =0
virtual void pan (const TPointD &delta)=0
virtual void zoom (const TPointD &center, double scaleFactor)=0
virtual void rotate (const TPointD &center, double angle)=0
virtual void rotate3D (double dPhi, double dTheta)=0
virtual bool is3DView () const =0
virtual bool getIsFlippedX () const =0
virtual bool getIsFlippedY () const =0
virtual double projectToZ (const TPointD &delta)=0
virtual TPointD getDpiScale () const =0
virtual int getVGuideCount ()=0
virtual int getHGuideCount ()=0
virtual double getHGuide (int index)=0
virtual double getVGuide (int index)=0
virtual void resetInputMethod ()=0
virtual void setFocus ()=0
virtual TRectD getGeometry () const =0
virtual void bindFBO ()
virtual void releaseFBO ()
int getGuidedStrokePickerMode ()
void setGuidedStrokePickerMode (int mode)
int getGuidedStrokePickerCursor ()
int getGuidedFrontStroke ()
void setGuidedFrontStroke (int strokeIdx)
int getGuidedBackStroke ()
void setGuidedBackStroke (int strokeIdx)
void getGuidedFrameIdx (int *backIdx, int *frontIdx)
void doPickGuideStroke (const TPointD &pos)
Public Member Functions inherited from Previewer::Listener
void requestTimedRefresh ()
virtual TRectD getPreviewRect () const =0
virtual void onRenderStarted (int frame)
virtual void onRenderCompleted (int frame)
virtual void onRenderFailed (int frame)
virtual void onPreviewUpdate ()
Protected Member Functions
void drawBuildVars ()
void drawEnableScissor ()
void drawDisableScissor ()
void drawBackground ()
void drawCameraStand ()
void drawPreview ()
void drawOverlay ()
void drawScene ()
void drawToolGadgets ()
void mult3DMatrix ()
void initializeGL () override
void resizeGL (int width, int height) override
void paintGL () override
void showEvent (QShowEvent *) override
void hideEvent (QHideEvent *) override
void gestureEvent (QGestureEvent *e)
void touchEvent (QTouchEvent *e, int type)
void tabletEvent (QTabletEvent *) override
void leaveEvent (QEvent *) override
void enterEvent (QEvent *) override
void mouseMoveEvent (QMouseEvent *event) override
void mousePressEvent (QMouseEvent *event) override
void mouseReleaseEvent (QMouseEvent *event) override
void mouseDoubleClickEvent (QMouseEvent *event) override
void onPress (const TMouseEvent &event)
void onMove (const TMouseEvent &event)
void onRelease (const TMouseEvent &event)
void onContextMenu (const QPoint &pos, const QPoint &globalPos)
void onEnter ()
void onLeave ()
void wheelEvent (QWheelEvent *) override
void keyPressEvent (QKeyEvent *event) override
void keyReleaseEvent (QKeyEvent *event) override
void contextMenuEvent (QContextMenuEvent *event) override
void inputMethodEvent (QInputMethodEvent *) override
void drawCompared ()
bool event (QEvent *event) override
void panQt (const QPointF &delta)
void zoomQt (const QPoint &center, double scaleFactor)
void pan (const TPointD &delta) override
void zoom (const TPointD &center, double factor) override
void rotate (const TPointD &center, double angle) override
void rotate3D (double dPhi, double dTheta) override
TAffine getToolMatrix () const
int pick (const TPointD &point) override
int posToColumnIndex (const TPointD &p, double distance, bool includeInvisible=true) const override
void posToColumnIndexes (const TPointD &p, std::vector< int > &indexes, double distance, bool includeInvisible=true) const override
int posToRow (const TPointD &p, double distance, bool includeInvisible=true, bool currentColumnOnly=false) const override
void dragEnterEvent (QDragEnterEvent *event) override
void dropEvent (QDropEvent *event) override
void resetInputMethod () override
void set3DLeftSideView ()
void set3DRightSideView ()
void set3DTopView ()
void setFocus () override
void registerContext ()
Protected Attributes
TAffine m_drawCameraAff
TAffine m_drawTableAff
bool m_draw3DMode
bool m_drawCameraTest
bool m_drawIsTableVisible
bool m_drawEditingLevel
TRect m_actualClipRect
Protected Attributes inherited from TTool::Viewer
ImagePainter::VisualSettings m_visualSettings
Settings used by the Viewer to draw scene contents.
int guidedStrokePickMode = 0
int m_guidedFrontStroke = -1
int m_guidedBackStroke = -1
Additional Inherited Members
Public Attributes inherited from Previewer::Listener
QTimer m_refreshTimer
Detailed Description
Member Enumeration Documentation
PreviewMode
enum SceneViewer::PreviewMode
{ NO_PREVIEW = 0, FULL_PREVIEW = 1, SUBCAMERA_PREVIEW = 2 };
ReferenceMode
enum SceneViewer::ReferenceMode
                     {
    NORMAL_REFERENCE   = 1,
    CAMERA3D_REFERENCE = 2,
    CAMERA_REFERENCE   = 3,
    LEVEL_MODE         = 128,
  };
ViewMode
enum SceneViewer::ViewMode
{ SCENE_VIEWMODE = 0, LEVEL_VIEWMODE = 1 };
Constructor & Destructor Documentation
SceneViewer()
SceneViewer::SceneViewer (ImageUtils::FullScreenWidget * parent)
    : GLWidgetForHighDpi(parent)
    , m_pressure(0)
    , m_lastMousePos(0, 0)
    , m_mouseButton(Qt::NoButton)
    , m_foregroundDrawing(false)
    , m_tabletEvent(false)
    , m_tabletMove(false)
    , m_buttonClicked(false)
    , m_referenceMode(NORMAL_REFERENCE)
    , m_previewMode(NO_PREVIEW)
    , m_isMouseEntered(false)
    , m_forceGlFlush(true)
    , m_freezedStatus(NO_FREEZED)
    , m_viewGrabImage(0)
    , m_FPS(0)
    , m_hRuler(0)
    , m_vRuler(0)
    , m_viewMode(SCENE_VIEWMODE)
    , m_pos(0, 0)
    , m_pan3D(TPointD(0, 0))
    , m_zoomScale3D(0.1)
    , m_theta3D(20)
    , m_phi3D(30)
    , m_dpiScale(TPointD(1, 1))
    , m_compareSettings()
    , m_minZ(0)
    , m_tableDLId(-1)
    , m_groupIndexToBeEntered(-1)
    , m_pixelSize(1)
    , m_eraserPointerOn(false)
    , m_backupTool("")
    , m_clipRect()
    , m_isPicking(false)
    , m_current3DDevice(NONE)
    , m_sideRasterPos()
    , m_topRasterPos()
    , m_toolDisableReason("")
    , m_editPreviewSubCamera(false)
    , m_locator(NULL)
    , m_isLocator(false)
    , m_isBusyOnTabletMove(false)
    , m_timer(nullptr) {
  m_visualSettings.m_sceneProperties =
      TApp::instance()->getCurrentScene()->getScene()->getProperties();
#if defined(x64)
  m_stopMotion = StopMotion::instance();
#endif
  // Enables multiple key input.
  setAttribute(Qt::WA_KeyCompression);
  // Enables input methods for Asian languages.
  setAttribute(Qt::WA_InputMethodEnabled);
  setFocusPolicy(Qt::StrongFocus);
  setAcceptDrops(true);
  this->setMouseTracking(true);
// introduced from Qt 5.9
#if QT_VERSION >= 0x050900
  this->setTabletTracking(true);
#endif
  for (int i = 0; i < m_viewAff.size(); ++i) {
    setViewMatrix(getNormalZoomScale(), i);
    m_rotationAngle[i] = 0.0;
  }
  m_3DSideR = rasterFromQPixmap(svgToPixmap(":Resources/3Dside_r.svg"));
  m_3DSideL = rasterFromQPixmap(svgToPixmap(":Resources/3Dside_l.svg"));
  m_3DTop   = rasterFromQPixmap(svgToPixmap(":Resources/3Dtop.svg"));
  setAttribute(Qt::WA_AcceptTouchEvents);
  grabGesture(Qt::SwipeGesture);
  grabGesture(Qt::PanGesture);
  grabGesture(Qt::PinchGesture);
  setUpdateBehavior(QOpenGLWidget::PartialUpdate);
  if (Preferences::instance()->isColorCalibrationEnabled())
    m_lutCalibrator = new LutCalibrator();
  if (Preferences::instance()->is30bitDisplayEnabled())
    setTextureFormat(TGL_TexFmt10);
}
~SceneViewer()
SceneViewer::~SceneViewer ()
{
  // notify FilmStripFrames and safely disconnect with this
  emit aboutToBeDestroyed();
  if (m_fbo) delete m_fbo;
  // release all the registered context (once when exit the software)
  std::set<TGlContext>::iterator ct, cEnd(l_contexts.end());
  for (ct = l_contexts.begin(); ct != cEnd; ++ct)
    TGLDisplayListsManager::instance()->releaseContext(*ct);
  l_contexts.clear();
}
Member Function Documentation
bindFBO()
void SceneViewer::bindFBO () override virtual
Reimplemented from TTool::Viewer.
{
  if (m_fbo) m_fbo->bind();
}
canSwapCompared()
bool SceneViewer::canSwapCompared () const
{
  return m_visualSettings.m_doCompare && m_previewMode != NO_PREVIEW;
}
contextMenuEvent()
void SceneViewer::contextMenuEvent (QContextMenuEvent * event) override protected
{
  if (m_tabletEvent) return;
#ifndef _WIN32
  /* On windows the widget receive the release event before the menu
     is shown, on linux and osx the release event is lost, never
     received by the widget */
  QMouseEvent fakeRelease(QEvent::MouseButtonRelease, e->pos(), Qt::RightButton,
                          Qt::NoButton, Qt::NoModifier);
  QApplication::instance()->sendEvent(this, &fakeRelease);
#endif
  onContextMenu(e->pos(), e->globalPos());
}
doDeleteSubCamera
void SceneViewer::doDeleteSubCamera () slot
delete preview - subcamera executed from context menu
{
  PreviewSubCameraManager::instance()->deleteSubCamera(this);
}
References PreviewSubCameraManager::deleteSubCamera().
dragEnterEvent()
void SceneViewer::dragEnterEvent (QDragEnterEvent * event) override protected
{
  if (m_freezedStatus != NO_FREEZED) return;
  const QMimeData *mimeData = event->mimeData();
  if (acceptResourceOrFolderDrop(mimeData->urls())) {
    // Force CopyAction
    event->setDropAction(Qt::CopyAction);
    event->accept();
  } else {
    event->ignore();
  }
}
drawBackground()
void SceneViewer::drawBackground () protected
{
  TApp *app         = TApp::instance();
  ToonzScene *scene = app->getCurrentScene()->getScene();
  if (m_visualSettings.m_colorMask == 0) {
    TPixel32 bgColor;
    if (isPreviewEnabled())
      bgColor = Preferences::instance()->getPreviewBgColor();
    else
      bgColor = Preferences::instance()->getViewerBgColor();
    glClearColor(bgColor.r / 255.0f, bgColor.g / 255.0f, bgColor.b / 255.0f,
                 1.0);
  } else
    glClearColor(0, 0, 0, 1.0);
  glClear(GL_COLOR_BUFFER_BIT);
  if (glGetError() == GL_INVALID_FRAMEBUFFER_OPERATION) {
    /*  GL_FRAMEBUFFER_COMPLETE  invalid operation
     *   */
    GLenum status = 0;
#ifdef _WIN32
    PROC proc = wglGetProcAddress("glCheckFramebufferStatusEXT");
    if (proc != nullptr)
      status = reinterpret_cast<PFNGLCHECKFRAMEBUFFERSTATUSEXTPROC>(proc)(
          GL_FRAMEBUFFER);
#else
    status = glCheckFramebufferStatus(GL_FRAMEBUFFER);
#endif
    printf("GL_INVALID_FRAMEBUFFER_OPERATION: framebuffer:%d\n", status);
  }
}
drawBuildVars()
void SceneViewer::drawBuildVars () protected
{
  TApp *app = TApp::instance();
  int frame    = app->getCurrentFrame()->getFrame();
  TXsheet *xsh = app->getCurrentXsheet()->getXsheet();
  // Camera affine
  TStageObjectId cameraId = xsh->getStageObjectTree()->getCurrentCameraId();
  TStageObject *camera    = xsh->getStageObject(cameraId);
  TAffine cameraPlacement = camera->getPlacement(frame);
  double cameraZ          = camera->getZ(frame);
  m_drawCameraAff =
      getViewMatrix() * cameraPlacement * TScale((1000 + cameraZ) / 1000);
  // Table affine
  TStageObject *table    = xsh->getStageObject(TStageObjectId::TableId);
  TAffine tablePlacement = table->getPlacement(frame);
  double tableZ          = table->getZ(frame);
  TAffine placement;
  m_drawIsTableVisible = TStageObject::perspective(
      placement, cameraPlacement, cameraZ, tablePlacement, tableZ, 0);
  m_drawTableAff = getViewMatrix() * tablePlacement;
  // Camera test check
  m_drawCameraTest = CameraTestCheck::instance()->isEnabled();
  if (m_previewMode == NO_PREVIEW) {
    m_drawEditingLevel = app->getCurrentFrame()->isEditingLevel();
    m_viewMode         = m_drawEditingLevel ? LEVEL_VIEWMODE : SCENE_VIEWMODE;
    m_draw3DMode       = is3DView() && (m_previewMode != SUBCAMERA_PREVIEW);
  } else {
    m_drawEditingLevel = false;
    m_viewMode         = app->getCurrentFrame()->isEditingLevel();
    m_draw3DMode       = false;
  }
  // Clip rect
  if (!m_clipRect.isEmpty() && !m_draw3DMode) {
    m_actualClipRect = getActualClipRect(getViewMatrix());
    m_actualClipRect += TPoint(width() * 0.5, height() * 0.5);
  }
  TTool *tool = app->getCurrentTool()->getTool();
  if (tool && !m_isLocator) tool->setViewer(this);
}
drawCameraStand()
void SceneViewer::drawCameraStand () protected
{
  GLint e = glGetError();
  check_framebuffer_status();
  assert(e == GL_NO_ERROR);
  TXshSimpleLevel::m_rasterizePli = rasterizePliToggle.getStatus();
  // clear
  if (m_draw3DMode) {
    glEnable(GL_DEPTH_TEST);
    glDepthFunc(GL_ALWAYS);
    glClear(GL_DEPTH_BUFFER_BIT);
    glPushMatrix();
    mult3DMatrix();
  } else
    glDisable(GL_DEPTH_TEST);
  assert(glGetError() == GL_NO_ERROR);
  // draw table
  if (!m_draw3DMode && viewTableToggle.getStatus() && m_drawIsTableVisible &&
      m_visualSettings.m_colorMask == 0 && m_drawEditingLevel == false &&
      !m_drawCameraTest) {
    glPushMatrix();
    tglMultMatrix(m_drawTableAff);
    ViewerDraw::drawDisk(m_tableDLId);
    glPopMatrix();
  }
  // draw colorcard (with camera BG color)
  // Hide camera BG when level editing mode.
  if (m_drawEditingLevel == false && viewClcToggle.getStatus() &&
      !m_drawCameraTest) {
    glPushMatrix();
    tglMultMatrix(m_drawCameraAff);
    glEnable(GL_BLEND);
    glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
    ViewerDraw::drawColorcard(m_visualSettings.m_colorMask);
    glDisable(GL_BLEND);
    glPopMatrix();
  }
  // Show white background when level editing mode.
  TTool *tool = TApp::instance()->getCurrentTool()->getTool();
  if (m_drawEditingLevel && tool && tool->isEnabled()) {
    if (!m_isLocator) tool->setViewer(this);
    glPushMatrix();
    if (m_referenceMode == CAMERA3D_REFERENCE) {
      mult3DMatrix();
      tglMultMatrix(tool->getMatrix());
    } else {
      tglMultMatrix(getViewMatrix() * tool->getMatrix());
    }
    glScaled(m_dpiScale.x, m_dpiScale.y, 1);
    TImageP image = tool->getImage(false);
    TToonzImageP ti  = image;
    TRasterImageP ri = image;
    if (ti) {
      TRect imgRect(0, 0, ti->getSize().lx - 1, ti->getSize().ly - 1);
      TRectD bbox = ToonzImageUtils::convertRasterToWorld(imgRect, ti);
      TPixel32 imgRectColor;
      // draw black rectangle instead, if the BlackBG check is ON
      if (ToonzCheck::instance()->getChecks() & ToonzCheck::eBlackBg)
        imgRectColor = TPixel::Black;
      else
        imgRectColor = Preferences::instance()->getLevelEditorBoxColor();
      ToolUtils::fillRect(bbox * ti->getSubsampling(), imgRectColor);
    } else if (ri) {
      TRectD bbox = ri->getBBox();
      bbox.x0 -= ri->getBBox().getLx() * 0.5;
      bbox.x1 -= ri->getBBox().getLx() * 0.5;
      bbox.y0 -= ri->getBBox().getLy() * 0.5;
      bbox.y1 -= ri->getBBox().getLy() * 0.5;
      TPixel32 imgRectColor;
      // draw black rectangle instead, if the BlackBG check is ON
      if (ToonzCheck::instance()->getChecks() & ToonzCheck::eBlackBg)
        imgRectColor = TPixel::Black;
      else
        imgRectColor = Preferences::instance()->getLevelEditorBoxColor();
      ToolUtils::fillRect(bbox * ri->getSubsampling(), imgRectColor);
    }
    glPopMatrix();
  }
  // draw 3dframe
  if (m_draw3DMode) {
    glDepthFunc(GL_LEQUAL);
    ViewerDraw::draw3DFrame(m_minZ, m_phi3D);
    glDepthFunc(GL_ALWAYS);
  }
  // draw scene
  assert(glGetError() == GL_NO_ERROR);
  drawScene();
  assert((glGetError()) == GL_NO_ERROR);
}
drawDisableScissor()
void SceneViewer::drawDisableScissor () protected
{
  if (!m_clipRect.isEmpty() && !m_draw3DMode) {
    glDisable(GL_SCISSOR_TEST);
  }
  // clear the clipping rect
  m_clipRect.empty();
}
drawEnableScissor()
void SceneViewer::drawEnableScissor () protected
{
  if (!m_clipRect.isEmpty() && !m_draw3DMode) {
    glEnable(GL_SCISSOR_TEST);
    glScissor(m_actualClipRect.x0, m_actualClipRect.y0,
              m_actualClipRect.getLx(), m_actualClipRect.getLy());
  }
}
drawOverlay()
void SceneViewer::drawOverlay () protected
cameraTest
{
  TApp *app = TApp::instance();
  // draw camera mask
  if (m_referenceMode == CAMERA_REFERENCE && !m_drawCameraTest) {
    glPushMatrix();
    tglMultMatrix(m_drawCameraAff);
    ViewerDraw::drawCameraMask(this);
    glPopMatrix();
  }
  // draw FieldGuide
  if (fieldGuideToggle.getStatus()) {
    glPushMatrix();
    tglMultMatrix(m_drawTableAff);
    ViewerDraw::drawFieldGuide();
    glPopMatrix();
  }
  if (!m_drawCameraTest) {
    // draw grid & guides
    if (viewGuideToggle.getStatus() &&
        ((m_vRuler && m_vRuler->getGuideCount()) ||
         (m_hRuler && m_hRuler->getGuideCount()))) {
      glPushMatrix();
      tglMultMatrix(getViewMatrix());
      ViewerDraw::drawGridAndGuides(
          this, (m_draw3DMode) ? m_zoomScale3D : m_viewAff[m_viewMode].det(),
          m_vRuler, m_hRuler, false);
      glPopMatrix();
    }
    // draw camera
    if (viewCameraToggle.getStatus() && m_drawEditingLevel == false) {
      unsigned long f = 0;
      if (m_referenceMode == CAMERA_REFERENCE)
        f |= ViewerDraw::CAMERA_REFERENCE;
      if (m_draw3DMode) f |= ViewerDraw::CAMERA_3D;
      if (m_previewMode == SUBCAMERA_PREVIEW || m_editPreviewSubCamera)
        f |= ViewerDraw::SUBCAMERA;
      if (m_draw3DMode)
        ViewerDraw::draw3DCamera(f, m_minZ, m_phi3D);
      else {
        glPushMatrix();
        tglMultMatrix(m_drawCameraAff);
        m_pixelSize = sqrt(tglGetPixelSize2()) * getDevPixRatio();
        ViewerDraw::drawCamera(f, m_pixelSize);
        glPopMatrix();
      }
    }
#ifdef WITH_CANON
    if (m_stopMotion->m_liveViewStatus == StopMotion::LiveViewOpen &&
        app->getCurrentFrame()->getFrame() ==
            m_stopMotion->getXSheetFrameNumber() - 1) {
      int x0, x1, y0, y1;
      rect().getCoords(&x0, &y0, &x1, &y1);
      x0 = (-(x1 / 2)) + 15;
      y0 = ((y1 / 2)) - 15;
      tglDrawDisk(TPointD(x0, y0), 10);
    }
    // draw Stop Motion Zoom Box
    if (m_stopMotion->m_liveViewStatus == 2 &&
        m_stopMotion->m_canon->m_pickLiveViewZoom) {
      glPushMatrix();
      tglMultMatrix(m_drawCameraAff);
      m_pixelSize = sqrt(tglGetPixelSize2()) * getDevPixRatio();
      TRect rect  = m_stopMotion->m_canon->m_zoomRect;
      glColor3d(1.0, 0.0, 0.0);
      // border
      glBegin(GL_LINE_STRIP);
      glVertex2d(rect.x0, rect.y0);
      glVertex2d(rect.x0, rect.y1 - m_pixelSize);
      glVertex2d(rect.x1 - m_pixelSize, rect.y1 - m_pixelSize);
      glVertex2d(rect.x1 - m_pixelSize, rect.y0);
      glVertex2d(rect.x0, rect.y0);
      glEnd();
      glPopMatrix();
    }
#endif
    // safe area
    if (safeAreaToggle.getStatus() && m_drawEditingLevel == false &&
        !is3DView()) {
      glPushMatrix();
      tglMultMatrix(m_drawCameraAff);
      ViewerDraw::drawSafeArea();
      glPopMatrix();
    }
    // record fps (frame per second)
    if (app->getCurrentFrame()->isPlaying())
      m_FPS = getActualFrameRate();
    else
      m_FPS = 0;
    if (m_freezedStatus != NO_FREEZED) {
      tglColor(TPixel32::Red);
      tglDrawText(TPointD(0, 0), "FROZEN");
    }
    assert(glGetError() == GL_NO_ERROR);
  }
  // draw 3d Top/Side Buttons
  if (m_draw3DMode && !m_isPicking) {
    tglColor(TPixel32::Black);
    GLdouble modelView3D[16];
    GLdouble projection3D[16];
    GLint viewport3D[4];
    glGetDoublev(GL_MODELVIEW_MATRIX, modelView3D);
    glGetDoublev(GL_PROJECTION_MATRIX, projection3D);
    glGetIntegerv(GL_VIEWPORT, viewport3D);
    if (m_phi3D > 0) {
      T3DPointD topRasterPos3D = computeNew3DPosition(
          T3DPointD(500, 500, 1000), TPointD(-10, -10), m_topRasterPos,
          modelView3D, projection3D, viewport3D, getDevPixRatio());
      glRasterPos3f(topRasterPos3D.x, topRasterPos3D.y, topRasterPos3D.z);
      glPixelStorei(GL_UNPACK_ROW_LENGTH, 0);
      glDrawPixels(m_3DTop->getWrap(), m_3DTop->getLy(), TGL_FMT, TGL_TYPE,
                   m_3DTop->getRawData());
      T3DPointD sideRasterPos3D = computeNew3DPosition(
          T3DPointD(-500, -500, 1000), TPointD(-10, -10), m_sideRasterPos,
          modelView3D, projection3D, viewport3D, getDevPixRatio());
      glRasterPos3f(sideRasterPos3D.x, sideRasterPos3D.y, sideRasterPos3D.z);
      glPixelStorei(GL_UNPACK_ROW_LENGTH, 0);
      glDrawPixels(m_3DSideR->getWrap(), m_3DSideR->getLy(), TGL_FMT, TGL_TYPE,
                   m_3DSideR->getRawData());
    } else {
      T3DPointD topRasterPos3D = computeNew3DPosition(
          T3DPointD(-500, 500, 1000), TPointD(-10, -10), m_topRasterPos,
          modelView3D, projection3D, viewport3D, getDevPixRatio());
      glRasterPos3f(topRasterPos3D.x, topRasterPos3D.y, topRasterPos3D.z);
      glPixelStorei(GL_UNPACK_ROW_LENGTH, 0);
      glDrawPixels(m_3DTop->getWrap(), m_3DTop->getLy(), TGL_FMT, TGL_TYPE,
                   m_3DTop->getRawData());
      T3DPointD sideRasterPos3D = computeNew3DPosition(
          T3DPointD(500, -500, 1000), TPointD(-10, -10), m_sideRasterPos,
          modelView3D, projection3D, viewport3D, getDevPixRatio());
      glRasterPos3f(sideRasterPos3D.x, sideRasterPos3D.y, sideRasterPos3D.z);
      glPixelStorei(GL_UNPACK_ROW_LENGTH, 0);
      glDrawPixels(m_3DSideL->getWrap(), m_3DSideL->getLy(), TGL_FMT, TGL_TYPE,
                   m_3DSideL->getRawData());
    }
  }
  if (m_draw3DMode) {
    glDisable(GL_DEPTH_TEST);
    glPopMatrix();
    assert(glGetError() == GL_NO_ERROR);
  }
  // draw tool gadgets
  TTool *tool         = app->getCurrentTool()->getTool();
  TXshSimpleLevel *sl = app->getCurrentLevel()->getSimpleLevel();
  // Call tool->draw() even if the level is read only (i.e. to show hooks)
  if (tool && (tool->isEnabled() || (sl && sl->isReadOnly()))) {
    // tool->setViewer(this);                            // Moved at
    // drawBuildVars(), before drawing anything
    glPushMatrix();
    if (m_draw3DMode) {
      mult3DMatrix();
      tglMultMatrix(tool->getMatrix());
    } else
      tglMultMatrix(getViewMatrix() * tool->getMatrix());
    if (tool->getToolType() & TTool::LevelTool &&
        !app->getCurrentObject()->isSpline())
      glScaled(m_dpiScale.x, m_dpiScale.y, 1);
    m_pixelSize = sqrt(tglGetPixelSize2()) * getDevPixRatio();
    tool->draw();
    glPopMatrix();
    // Used (only in the T_RGBPicker tool) to notify and set the currentColor
    // outside the draw() methods:
    // using special style there was a conflict between the draw() methods of
    // the tool
    // and the generation of the icon inside the style editor (makeIcon()) which
    // use
    // another glContext
    if (tool->getName() == "T_RGBPicker") tool->onImageChanged();
    // draw cross at the center of the locator window
    if (m_isLocator) {
      glColor3d(1.0, 0.0, 0.0);
      tglDrawSegment(TPointD(-4, 0), TPointD(5, 0));
      tglDrawSegment(TPointD(0, -4), TPointD(0, 5));
    }
  }
}
References TTool::draw(), TApp::getCurrentFrame(), TApp::getCurrentLevel(), TApp::getCurrentObject(), TApp::getCurrentTool(), getViewMatrix(), TApp::instance(), TTool::onImageChanged(), and TRectT< T >::x0.
drawPreview()
void SceneViewer::drawPreview () protected
{
  const double inch   = Stage::inch;
  TApp *app           = TApp::instance();
  int row             = app->getCurrentFrame()->getFrame();
  TCamera *currCamera = app->getCurrentScene()->getScene()->getCurrentCamera();
  TDimensionD cameraSize = currCamera->getSize();
  Previewer *previewer =
      Previewer::instance(m_previewMode == SUBCAMERA_PREVIEW);
  TRasterP ras =
      previewer->getRaster(row, m_visualSettings.m_recomputeIfNeeded);
  if (ras) {
    TRectD previewStageRectD, cameraStageRectD = currCamera->getStageRect();
    TRect subCameraRect(currCamera->getInterestRect());
    if (m_previewMode == SUBCAMERA_PREVIEW && subCameraRect.getLx() > 0 &&
        subCameraRect.getLy() > 0)
      previewStageRectD = currCamera->getInterestStageRect();
    else
      previewStageRectD = cameraStageRectD;
    TAffine rasterToStageRef(
        previewStageRectD.getLx() / ras->getLx(), 0.0,
        previewStageRectD.x0 + 0.5 * previewStageRectD.getLx(), 0.0,
        previewStageRectD.getLy() / ras->getLy(),
        previewStageRectD.y0 + 0.5 * previewStageRectD.getLy());
    TDimension dim(width(), height());
    TAffine finalAff              = m_drawCameraAff * rasterToStageRef;
    m_visualSettings.m_useTexture = !Preferences::instance()->useDrawPixel();
    ImagePainter::paintImage(TRasterImageP(ras), ras->getSize(), dim, finalAff,
                             m_visualSettings, m_compareSettings, TRect());
  }
  glPushMatrix();
  tglMultMatrix(m_drawCameraAff);
  TRectD frameRect(cameraSize);
  frameRect.x1 *= inch;
  frameRect.y1 *= inch;
  frameRect -= 0.5 * (frameRect.getP00() + frameRect.getP11());
  if (m_visualSettings.m_blankColor != TPixel::Transparent) {
    tglColor(m_visualSettings.m_blankColor);
    tglFillRect(frameRect);
  }
  if (!previewer->isFrameReady(row) ||
      (app->getCurrentFrame()->isPlaying() && previewer->isBusy())) {
    glColor3d(1, 0, 0);
    tglDrawRect(frameRect);
    tglDrawRect(frameRect.enlarge(5));
  }
  glPopMatrix();
}
drawScene()
void SceneViewer::drawScene () protected
{
  TApp *app         = TApp::instance();
  ToonzScene *scene = app->getCurrentScene()->getScene();
  int frame         = app->getCurrentFrame()->getFrame();
  TXsheet *xsh      = app->getCurrentXsheet()->getXsheet();
  TRect clipRect    = getActualClipRect(getViewMatrix());
  clipRect += TPoint(width() * 0.5, height() * 0.5);
  ChildStack *childStack = scene->getChildStack();
  bool editInPlace       = editInPlaceToggle.getStatus() &&
                     !app->getCurrentFrame()->isEditingLevel();
  bool fillFullColorRaster = TXshSimpleLevel::m_fillFullColorRaster;
  TXshSimpleLevel::m_fillFullColorRaster = false;
  // Guided Drawing Check
  int useGuidedDrawing  = Preferences::instance()->getGuidedDrawingType();
  TTool *tool           = app->getCurrentTool()->getTool();
  int guidedFrontStroke = tool ? tool->getViewer()->getGuidedFrontStroke() : -1;
  int guidedBackStroke  = tool ? tool->getViewer()->getGuidedBackStroke() : -1;
  m_minZ = 0;
  if (is3DView()) {
    Stage::OpenGlPainter painter(getViewMatrix(), clipRect, m_visualSettings,
                                 true, false);
    painter.enableCamera3D(true);
    painter.setPhi(m_phi3D);
    int xsheetLevel = 0;
    std::pair<TXsheet *, int> xr;
    if (editInPlace) {
      xr          = childStack->getAncestor(frame);
      xsheetLevel = childStack->getAncestorCount();
    } else
      xr = std::make_pair(xsh, frame);
    Stage::VisitArgs args;
    args.m_scene       = scene;
    args.m_xsh         = xr.first;
    args.m_row         = xr.second;
    args.m_col         = app->getCurrentColumn()->getColumnIndex();
    OnionSkinMask osm  = app->getCurrentOnionSkin()->getOnionSkinMask();
    args.m_osm         = &osm;
    args.m_camera3d    = true;
    args.m_xsheetLevel = xsheetLevel;
    args.m_currentFrameId =
        app->getCurrentXsheet()
            ->getXsheet()
            ->getCell(app->getCurrentFrame()->getFrame(), args.m_col)
            .getFrameId();
    args.m_isGuidedDrawingEnabled = useGuidedDrawing;
    args.m_guidedFrontStroke      = guidedFrontStroke;
    args.m_guidedBackStroke       = guidedBackStroke;
    // args.m_currentFrameId = app->getCurrentFrame()->getFid();
    Stage::visit(painter, args);
    m_minZ = painter.getMinZ();
  } else {
    // camera 2D (normale)
    TDimension viewerSize(width(), height());
    TAffine viewAff = getViewMatrix();
    if (editInPlace) {
      TAffine aff;
      if (scene->getChildStack()->getAncestorAffine(aff, frame))
        viewAff = viewAff * aff.inv();
    }
    m_visualSettings.m_showBBox = viewBBoxToggle.getStatus();
    Stage::RasterPainter painter(viewerSize, viewAff, clipRect,
                                 m_visualSettings, true);
    // darken blended view mode for viewing the non-cleanuped and stacked
    // drawings
    painter.setRasterDarkenBlendedView(
        Preferences::instance()
            ->isShowRasterImagesDarkenBlendedInViewerEnabled());
    TFrameHandle *frameHandle = TApp::instance()->getCurrentFrame();
    if (app->getCurrentFrame()->isEditingLevel()) {
      Stage::visit(painter, app->getCurrentLevel()->getLevel(),
                   app->getCurrentFrame()->getFid(),
                   app->getCurrentOnionSkin()->getOnionSkinMask(),
                   frameHandle->isPlaying(), useGuidedDrawing, guidedBackStroke,
                   guidedFrontStroke);
    } else {
      std::pair<TXsheet *, int> xr;
      int xsheetLevel = 0;
      if (editInPlace) {
        xr          = scene->getChildStack()->getAncestor(frame);
        xsheetLevel = scene->getChildStack()->getAncestorCount();
      } else
        xr = std::make_pair(xsh, frame);
      Stage::VisitArgs args;
      args.m_scene       = scene;
      args.m_xsh         = xr.first;
      args.m_row         = xr.second;
      args.m_col         = app->getCurrentColumn()->getColumnIndex();
      OnionSkinMask osm  = app->getCurrentOnionSkin()->getOnionSkinMask();
      args.m_osm         = &osm;
      args.m_xsheetLevel = xsheetLevel;
      args.m_isPlaying   = frameHandle->isPlaying();
      if (app->getCurrentLevel() && app->getCurrentLevel()->getLevel() &&
          !app->getCurrentLevel()->getLevel()->getSoundLevel())
        args.m_currentFrameId =
            app->getCurrentXsheet()
                ->getXsheet()
                ->getCell(app->getCurrentFrame()->getFrame(), args.m_col)
                .getFrameId();
      args.m_isGuidedDrawingEnabled = useGuidedDrawing;
      args.m_guidedFrontStroke      = guidedFrontStroke;
      args.m_guidedBackStroke       = guidedBackStroke;
#if defined(x64)
      if (m_stopMotion->m_alwaysUseLiveViewImages &&
          m_stopMotion->m_liveViewStatus > 0 &&
          frame != m_stopMotion->getXSheetFrameNumber() - 1 &&
          m_hasStopMotionImage && !m_stopMotion->m_reviewTimer->isActive()) {
        TRaster32P image;
        bool hasImage = m_stopMotion->loadLiveViewImage(frame, image);
        if (hasImage) {
          Stage::Player smPlayer;
          double dpiX, dpiY;
          m_stopMotionImage->getDpi(dpiX, dpiY);
          smPlayer.m_dpiAff    = TScale(Stage::inch / dpiX, Stage::inch / dpiY);
          smPlayer.m_opacity   = 255;
          smPlayer.m_sl        = m_stopMotion->m_sl;
          args.m_liveViewImage = static_cast<TRasterImageP>(image);
          args.m_liveViewPlayer = smPlayer;
          // painter.onRasterImage(static_cast<TRasterImageP>(image).getPointer(),
          //                      smPlayer);
        }
      }
      if (
          m_stopMotion->m_liveViewStatus == 2 &&
          (
              frame == m_stopMotion->getXSheetFrameNumber() - 1)) {
        if (m_hasStopMotionLineUpImage && m_stopMotion->m_showLineUpImage) {
          Stage::Player smPlayer;
          double dpiX, dpiY;
          m_stopMotionLineUpImage->getDpi(dpiX, dpiY);
          smPlayer.m_dpiAff   = TScale(Stage::inch / dpiX, Stage::inch / dpiY);
          smPlayer.m_opacity  = 255;
          smPlayer.m_sl       = m_stopMotion->m_sl;
          args.m_lineupImage  = m_stopMotionLineUpImage;
          args.m_lineupPlayer = smPlayer;
          // painter.onRasterImage(m_stopMotionLineUpImage.getPointer(),
          // smPlayer);
        }
        if (m_hasStopMotionImage) {
          Stage::Player smPlayer;
          double dpiX, dpiY;
          m_stopMotionImage->getDpi(dpiX, dpiY);
          smPlayer.m_dpiAff = TScale(Stage::inch / dpiX, Stage::inch / dpiY);
          bool hide_opacity = false;
#ifdef WITH_CANON
          hide_opacity = m_stopMotion->m_canon->m_zooming ||
                         m_stopMotion->m_canon->m_pickLiveViewZoom ||
                         !m_hasStopMotionLineUpImage;
#endif
          smPlayer.m_opacity =
              hide_opacity ? 255.0 : m_stopMotion->getOpacity();
          smPlayer.m_sl         = m_stopMotion->m_sl;
          args.m_liveViewImage  = m_stopMotionImage;
          args.m_liveViewPlayer = smPlayer;
          // painter.onRasterImage(m_stopMotionImage.getPointer(), smPlayer);
        }
      }
#endif  // x64
      Stage::visit(painter, args);
    }
    assert(glGetError() == 0);
    painter.flushRasterImages();
    TXshSimpleLevel::m_fillFullColorRaster = fillFullColorRaster;
    assert(glGetError() == 0);
    if (m_viewMode != LEVEL_VIEWMODE)
      drawSpline(getViewMatrix(), clipRect,
                 m_referenceMode == CAMERA3D_REFERENCE, m_pixelSize);
    assert(glGetError() == 0);
    // gather animated guide strokes' bounding boxes
    // it is used for updating viewer next time
    std::vector<TStroke *> guidedStrokes = painter.getGuidedStrokes();
    for (auto itr = guidedStrokes.begin(); itr != guidedStrokes.end(); ++itr) {
      m_guidedDrawingBBox += (*itr)->getBBox();
    }
  }
}
dropEvent()
void SceneViewer::dropEvent (QDropEvent * event) override protected
{
  if (m_freezedStatus != NO_FREEZED) return;
  const QMimeData *mimeData = e->mimeData();
  if (mimeData->hasUrls()) {
    IoCmd::LoadResourceArguments args;
    for (const QUrl &url : mimeData->urls()) {
      TFilePath fp(url.toLocalFile().toStdWString());
      args.resourceDatas.push_back(fp);
    }
    IoCmd::loadResources(args);
    if (acceptResourceOrFolderDrop(mimeData->urls())) {
      // Force Copy Action
      e->setDropAction(Qt::CopyAction);
      // For files, don't accept original proposed action in case it's a move
      e->accept();
      return;
    }
  }
  e->acceptProposedAction();
}
enablePreview
void SceneViewer::enablePreview (int previewMode) slot
{
  if (m_previewMode == previewMode) return;
  TApp *app = TApp::instance();
  if (app->getCurrentFrame()->isEditingLevel() && previewMode != NO_PREVIEW)
    app->getCurrentFrame()->setFrame(app->getCurrentFrame()->getFrame());
  if (m_freezedStatus != NO_FREEZED) {
    freeze(false);
    emit freezeStateChanged(false);
  }
  if (m_previewMode != NO_PREVIEW)
    Previewer::instance(m_previewMode == SUBCAMERA_PREVIEW)
        ->removeListener(this);
  // Schedule as a listener to Previewer.
  if (previewMode != NO_PREVIEW) {
    Previewer *previewer =
        Previewer::instance(previewMode == SUBCAMERA_PREVIEW);
    previewer->addListener(this);
    previewer->update();
  }
  m_previewMode = previewMode;
  GLInvalidateAll();
  // for updating the title bar
  emit previewToggled();
}
enterEvent()
void SceneViewer::enterEvent (QEvent *) override protected
{ onEnter(); }
event()
bool SceneViewer::event (QEvent * event) override protected
{
  /*
  switch (e->type()) {
  //    case QEvent::Enter:
  //    qDebug() << "[enter] ************************** Enter";
  //    break;
  //    case QEvent::Leave:
  //    qDebug() << "[enter] ************************** Leave";
  //    break;
  case QEvent::TabletPress: {
    QTabletEvent *te = static_cast<QTabletEvent *>(e);
    qDebug() << "[enter] ************************** TabletPress mouseState("
             << m_mouseState << ") tabletState(" << m_tabletState
             << ") pressure(" << m_pressure << ") pointerType("
             << te->pointerType() << ") device(" << te->device() << ")";
  } break;
  //    case QEvent::TabletMove:
  //    qDebug() << "[enter] ************************** TabletMove
  //mouseState("<<m_mouseState<<") tabletState("<<m_tabletState<<") pressure("
  //<< m_pressure << ")";
  //    break;
  case QEvent::TabletRelease:
    qDebug() << "[enter] ************************** TabletRelease mouseState("
             << m_mouseState << ") tabletState(" << m_tabletState << ")";
    break;
  case QEvent::TouchBegin:
    qDebug() << "[enter] ************************** TouchBegin";
    break;
  case QEvent::TouchEnd:
    qDebug() << "[enter] ************************** TouchEnd";
    break;
  case QEvent::TouchCancel:
    qDebug() << "[enter] ************************** TouchCancel";
    break;
  case QEvent::Gesture:
    qDebug() << "[enter] ************************** Gesture";
    break;
  case QEvent::MouseButtonPress:
    qDebug()
        << "[enter] ************************** MouseButtonPress mouseState("
        << m_mouseState << ") tabletState(" << m_tabletState << ") pressure("
        << m_pressure << ") tabletEvent(" << m_tabletEvent << ")";
    break;
  //    case QEvent::MouseMove:
  //    qDebug() << "[enter] ************************** MouseMove mouseState("
  //<< m_mouseState << ") tabletState("<<m_tabletState<<") pressure(" <<
  //m_pressure << ")";
  //    break;
  case QEvent::MouseButtonRelease:
    qDebug()
        << "[enter] ************************** MouseButtonRelease mouseState("
        << m_mouseState << ") tabletState(" << m_tabletState << ")";
    break;
  case QEvent::MouseButtonDblClick:
    qDebug() << "[enter] ============================== MouseButtonDblClick";
    break;
  }
  */
  if (e->type() == QEvent::Gesture && CommandManager::instance()
                                          ->getAction(MI_TouchGestureControl)
                                          ->isChecked()) {
    gestureEvent(static_cast<QGestureEvent *>(e));
    return true;
  }
  if ((e->type() == QEvent::TouchBegin || e->type() == QEvent::TouchEnd ||
       e->type() == QEvent::TouchCancel || e->type() == QEvent::TouchUpdate) &&
      CommandManager::instance()
          ->getAction(MI_TouchGestureControl)
          ->isChecked()) {
    touchEvent(static_cast<QTouchEvent *>(e), e->type());
    m_gestureActive = true;
    return true;
  }
  if (e->type() == QEvent::ShortcutOverride || e->type() == QEvent::KeyPress) {
    if (!((QKeyEvent *)e)->isAutoRepeat()) {
      TApp::instance()->getCurrentTool()->storeTool();
    }
  }
  if (e->type() == QEvent::ShortcutOverride) {
    TTool *tool = TApp::instance()->getCurrentTool()->getTool();
    if (tool && tool->isEnabled() && tool->getName() == T_Type &&
        tool->isActive())
      e->accept();
    // for other tools, check if the pressed keys should be catched instead of
    // triggering the shortcut command actions
    else if (tool && tool->isEventAcceptable(e)) {
      e->accept();
    }
    // if the Shift & Trace mode is active, then override F1, F2 and F3 key
    // actions by flipping feature
    else if (CommandManager::instance()
                 ->getAction(MI_ShiftTrace)
                 ->isChecked() &&
             TTool::getTool("T_ShiftTrace", TTool::ToonzImage)
                 ->isEventAcceptable(e)) {
      e->accept();
    }
    // Disable keyboard shortcuts while the tool is busy with a mouse drag
    // operation.
    if (tool->isDragging()) {
      e->accept();
    }
    return true;
  }
  if (e->type() == QEvent::KeyRelease) {
    if (!((QKeyEvent *)e)->isAutoRepeat()) {
      QWidget *focusWidget = QApplication::focusWidget();
      if (focusWidget == 0 ||
          QString(focusWidget->metaObject()->className()) == "SceneViewer")
        TApp::instance()->getCurrentTool()->restoreTool();
    }
  }
  // discard too frequent move events
  static QTime clock;
  if (e->type() == QEvent::MouseButtonPress)
    clock.start();
  else if (e->type() == QEvent::MouseMove) {
    if (clock.isValid() && clock.elapsed() < 10) {
      e->accept();
      return true;
    }
    clock.start();
  }
  return QOpenGLWidget::event(e);
}
fitToCamera
void SceneViewer::fitToCamera () slot
{
  // Reset the view scale to 1:1.
  bool tempIsFlippedX = m_isFlippedX;
  bool tempIsFlippedY = m_isFlippedY;
  resetSceneViewer();
  m_isFlippedX = tempIsFlippedX;
  m_isFlippedY = tempIsFlippedY;
  TXsheet *xsh            = TApp::instance()->getCurrentXsheet()->getXsheet();
  int frame               = TApp::instance()->getCurrentFrame()->getFrame();
  TStageObjectId cameraId = xsh->getStageObjectTree()->getCurrentCameraId();
  TStageObject *camera    = xsh->getStageObject(cameraId);
  TAffine cameraPlacement = camera->getPlacement(frame);
  double cameraZ          = camera->getZ(frame);
  TAffine cameraAff =
      getViewMatrix() * cameraPlacement * TScale((1000 + cameraZ) / 1000);
  QRect viewRect    = rect();
  TRectD cameraRect = ViewerDraw::getCameraRect();
  TPointD P00       = cameraAff * cameraRect.getP00();
  TPointD P10       = cameraAff * cameraRect.getP10();
  TPointD P01       = cameraAff * cameraRect.getP01();
  TPointD P11       = cameraAff * cameraRect.getP11();
  TPointD p0        = TPointD(std::min({P00.x, P01.x, P10.x, P11.x}),
                       std::min({P00.y, P01.y, P10.y, P11.y}));
  TPointD p1        = TPointD(std::max({P00.x, P01.x, P10.x, P11.x}),
                       std::max({P00.y, P01.y, P10.y, P11.y}));
  cameraRect        = TRectD(p0.x, p0.y, p1.x, p1.y);
  // Pan
  if (!is3DView()) {
    TPointD cameraCenter = (cameraRect.getP00() + cameraRect.getP11()) * 0.5;
    panQt(QPoint(-cameraCenter.x, cameraCenter.y));
  }
  double xratio = (double)viewRect.width() / cameraRect.getLx();
  double yratio = (double)viewRect.height() / cameraRect.getLy();
  double ratio  = std::min(xratio, yratio);
  if (ratio == 0.0) return;
  if (tempIsFlippedX)
    setViewMatrix(TScale(-1, 1) * m_viewAff[m_viewMode], m_viewMode);
  if (tempIsFlippedY)
    setViewMatrix(TScale(1, -1) * m_viewAff[m_viewMode], m_viewMode);
  // Scale and center on the center of \a rect.
  QPoint c = viewRect.center();
  zoom(TPointD(c.x(), c.y()), ratio);
  emit onFlipHChanged(m_isFlippedX);
  emit onFlipVChanged(m_isFlippedY);
}
fitToCameraOutline
void SceneViewer::fitToCameraOutline () slot
{
  TXsheet *xsh            = TApp::instance()->getCurrentXsheet()->getXsheet();
  int frame               = TApp::instance()->getCurrentFrame()->getFrame();
  TStageObjectId cameraId = xsh->getStageObjectTree()->getCurrentCameraId();
  TStageObject *camera    = xsh->getStageObject(cameraId);
  TAffine cameraPlacement = camera->getPlacement(frame);
  double cameraZ          = camera->getZ(frame);
  TAffine cameraAff =
      getViewMatrix() * cameraPlacement * TScale((1000 + cameraZ) / 1000);
  QRect viewRect    = rect();
  TRectD cameraRect = ViewerDraw::getCameraRect();
  TPointD P00       = cameraAff * cameraRect.getP00();
  TPointD P10       = cameraAff * cameraRect.getP10();
  TPointD P01       = cameraAff * cameraRect.getP01();
  TPointD P11       = cameraAff * cameraRect.getP11();
  TPointD p0        = TPointD(std::min({P00.x, P01.x, P10.x, P11.x}),
                       std::min({P00.y, P01.y, P10.y, P11.y}));
  TPointD p1        = TPointD(std::max({P00.x, P01.x, P10.x, P11.x}),
                       std::max({P00.y, P01.y, P10.y, P11.y}));
  cameraRect        = TRectD(p0.x, p0.y, p1.x, p1.y);
  // Pan
  if (!is3DView()) {
    TPointD cameraCenter = (cameraRect.getP00() + cameraRect.getP11()) * 0.5;
    panQt(QPoint(-cameraCenter.x, cameraCenter.y));
  }
  double xratio = (double)viewRect.width() / cameraRect.getLx();
  double yratio = (double)viewRect.height() / cameraRect.getLy();
  double ratio  = std::min(xratio, yratio);
  if (ratio == 0.0) return;
  // Scale and center on the center of \a rect.
  QPoint c = viewRect.center();
  zoom(TPointD(c.x(), c.y()), ratio);
  zoom(TPointD(c.x(), c.y()), 0.95);
}
flipX
void SceneViewer::flipX () slot
{
  double flipAngle0 = (m_rotationAngle[0] * -1) * 2;
  double flipAngle1 = (m_rotationAngle[1] * -1) * 2;
  m_rotationAngle[0] += flipAngle0;
  m_rotationAngle[1] += flipAngle1;
  if (m_isFlippedX != m_isFlippedY) {
    flipAngle0 = -flipAngle0;
    flipAngle1 = -flipAngle1;
  }
  m_viewAff[0] = m_viewAff[0] * TRotation(flipAngle0) * TScale(-1, 1);
  m_viewAff[1] = m_viewAff[1] * TRotation(flipAngle1) * TScale(-1, 1);
  m_viewAff[0].a13 *= -1;
  m_viewAff[1].a13 *= -1;
  m_isFlippedX = !m_isFlippedX;
  invalidateAll();
  emit onZoomChanged();
  emit onFlipHChanged(m_isFlippedX);
}
flipY
void SceneViewer::flipY () slot
{
  double flipAngle0 = (m_rotationAngle[0] * -1) * 2;
  double flipAngle1 = (m_rotationAngle[1] * -1) * 2;
  m_rotationAngle[0] += flipAngle0;
  m_rotationAngle[1] += flipAngle1;
  if (m_isFlippedX != m_isFlippedY) {
    flipAngle0 = -flipAngle0;
    flipAngle1 = -flipAngle1;
  }
  m_viewAff[0] = m_viewAff[0] * TRotation(flipAngle0) * TScale(1, -1);
  m_viewAff[1] = m_viewAff[1] * TRotation(flipAngle1) * TScale(1, -1);
  m_viewAff[0].a23 *= -1;
  m_viewAff[1].a23 *= -1;
  m_isFlippedY = !m_isFlippedY;
  invalidateAll();
  emit onZoomChanged();
  emit onFlipVChanged(m_isFlippedY);
}
freeze
void SceneViewer::freeze (bool on) slot
{
  if (!on) {
    m_viewGrabImage = TRaster32P();
    m_freezedStatus = NO_FREEZED;
  } else {
    setCursor(Qt::ForbiddenCursor);
    m_freezedStatus = UPDATE_FREEZED;
  }
  GLInvalidateAll();
}
gestureEvent()
void SceneViewer::gestureEvent (QGestureEvent * e) protected
{
  m_gestureActive = false;
  if (QGesture *swipe = e->gesture(Qt::SwipeGesture)) {
    m_gestureActive = true;
  } else if (QGesture *pan = e->gesture(Qt::PanGesture)) {
    m_gestureActive = true;
  }
  if (QGesture *pinch = e->gesture(Qt::PinchGesture)) {
    QPinchGesture *gesture = static_cast<QPinchGesture *>(pinch);
    QPinchGesture::ChangeFlags changeFlags = gesture->changeFlags();
    QPoint firstCenter                     = gesture->centerPoint().toPoint();
    if (m_touchDevice == QTouchDevice::TouchScreen)
      firstCenter = mapFromGlobal(firstCenter);
    if (gesture->state() == Qt::GestureStarted) {
      m_gestureActive = true;
    } else if (gesture->state() == Qt::GestureFinished) {
      m_gestureActive = false;
      m_rotating      = false;
      m_zooming       = false;
      m_scaleFactor   = 0.0;
      m_rotationDelta = 0.0;
    } else {
      if (changeFlags & QPinchGesture::ScaleFactorChanged) {
        double scaleFactor = gesture->scaleFactor();
        // the scale factor makes for too sensitive scaling
        // divide the change in half
        if (scaleFactor > 1) {
          double decimalValue = scaleFactor - 1;
          decimalValue /= 1.5;
          scaleFactor = 1 + decimalValue;
        } else if (scaleFactor < 1) {
          double decimalValue = 1 - scaleFactor;
          decimalValue /= 1.5;
          scaleFactor = 1 - decimalValue;
        }
        if (!m_rotating && !m_zooming) {
          double delta = scaleFactor - 1;
          m_scaleFactor += delta;
          if (m_scaleFactor > .2 || m_scaleFactor < -.2) {
            m_zooming = true;
          }
        }
        if (m_zooming) {
          zoomQt(firstCenter * getDevPixRatio(), scaleFactor);
          m_panning = false;
        }
        m_gestureActive = true;
      }
      if (changeFlags & QPinchGesture::RotationAngleChanged) {
        qreal rotationDelta =
            gesture->rotationAngle() - gesture->lastRotationAngle();
        if (m_isFlippedX != m_isFlippedY) rotationDelta = -rotationDelta;
        TAffine aff    = getViewMatrix().inv();
        TPointD center = aff * TPointD(0, 0);
        if (!m_rotating && !m_zooming) {
          m_rotationDelta += rotationDelta;
          double absDelta = std::abs(m_rotationDelta);
          if (absDelta >= 10) {
            m_rotating = true;
          }
        }
        if (m_rotating) {
          rotate(center, -rotationDelta);
        }
      }
      if (changeFlags & QPinchGesture::CenterPointChanged) {
        QPointF centerDelta = (gesture->centerPoint() * getDevPixRatio()) -
                              (gesture->lastCenterPoint() * getDevPixRatio());
        if (centerDelta.manhattanLength() > 1) {
          // panQt(centerDelta.toPoint());
        }
        m_gestureActive = true;
      }
    }
  }
  e->accept();
}
getActualClipRect()
TRect SceneViewer::getActualClipRect (const TAffine & aff)
{
  TDimensionD viewerSize(width(), height());
  TRectD clipRect(viewerSize);
  if (is3DView()) {
    TPointD p00 = winToWorld(clipRect.getP00());
    TPointD p01 = winToWorld(clipRect.getP01());
    TPointD p10 = winToWorld(clipRect.getP10());
    TPointD p11 = winToWorld(clipRect.getP11());
    clipRect = TRectD(TPointD(std::min(p00.x, p01.x), std::min(p00.y, p10.y)),
                      TPointD(std::max(p11.x, p10.x), std::max(p11.y, p01.y)));
  }
  // this condition will catch both cases of m_clipRect == empty and
  // m_clipRect == InvalidateAllRect
  else if (m_clipRect.isEmpty())
    clipRect -= TPointD(viewerSize.lx / 2, viewerSize.ly / 2);
  else {
    TRectD app = aff * (m_clipRect.enlarge(3));
    clipRect =
        TRectD(tceil(app.x0), tceil(app.y0), tfloor(app.x1), tfloor(app.y1));
  }
  return convert(clipRect);
}
getDpiFactor()
double SceneViewer::getDpiFactor ()
a factor for getting pixel-based zoom ratio
{
  // When the current unit is "pixels", always use a standard dpi
  double cameraDpi = TApp::instance()
                         ->getCurrentScene()
                         ->getScene()
                         ->getCurrentCamera()
                         ->getDpi()
                         .x;
  if (Preferences::instance()->getPixelsOnly()) {
    return Stage::inch / Stage::standardDpi;
  }
  // When preview mode, use a camera DPI
  else if (isPreviewEnabled()) {
    return Stage::inch / cameraDpi;
  }
  // When level editing mode, use an image DPI
  else if (TApp::instance()->getCurrentFrame()->isEditingLevel()) {
    TXshSimpleLevel *sl;
    sl = TApp::instance()->getCurrentLevel()->getSimpleLevel();
    if (!sl) return Stage::inch / cameraDpi;
    if (sl->getType() == PLI_XSHLEVEL) return Stage::inch / cameraDpi;
    if (sl->getImageDpi() != TPointD())
      return Stage::inch / sl->getImageDpi().x;
    if (sl->getDpi() != TPointD()) return Stage::inch / sl->getDpi().x;
    // no valid dpi, use camera dpi
    return Stage::inch / cameraDpi;
  }
  // When the special case in the scene editing mode:
  // If the option "ActualPixelViewOnSceneEditingMode" is ON,
  // use  current level's DPI set in the level settings.
  else if (Preferences::instance()
               ->isActualPixelViewOnSceneEditingModeEnabled()) {
    if (CleanupPreviewCheck::instance()->isEnabled() ||
        CameraTestCheck::instance()->isEnabled()) {
      double cleanupCameraDpi = TApp::instance()
                                    ->getCurrentScene()
                                    ->getScene()
                                    ->getProperties()
                                    ->getCleanupParameters()
                                    ->m_camera.getDpi()
                                    .x;
      return Stage::inch / cleanupCameraDpi;
    } else {
      TXshSimpleLevel *sl;
      sl = TApp::instance()->getCurrentLevel()->getSimpleLevel();
      if (!sl) return Stage::inch / cameraDpi;
      if (sl->getType() == PLI_XSHLEVEL) return Stage::inch / cameraDpi;
      if (sl->getDpi() == TPointD()) return Stage::inch / cameraDpi;
      // use default value for the argument of getDpi() (=TFrameId::NO_FRAME
      // so that the dpi of the first frame in the level will be returned.
      return Stage::inch / sl->getDpi().x;
    }
  }
  // When the scene editing mode without any option, use the camera dpi
  else {
    return Stage::inch / cameraDpi;
  }
}
References TSceneProperties::getCleanupParameters(), ToonzScene::getCurrentCamera(), TApp::getCurrentLevel(), TApp::getCurrentScene(), TCamera::getDpi(), ToonzScene::getProperties(), TXshLevel::getType(), Stage::inch, CameraTestCheck::instance(), CleanupPreviewCheck::instance(), and TApp::instance().
getDpiScale()
TPointD SceneViewer::getDpiScale () const inline override virtual
Implements TTool::Viewer.
{ return m_dpiScale; }
getFPS()
int SceneViewer::getFPS () inline
{ return m_FPS; }
getGeometry()
TRectD SceneViewer::getGeometry () const override virtual
return the viewer geometry in order to avoid picking the style outside of the viewer when using the stylepicker and the finger tools
Implements TTool::Viewer.
{
  int devPixRatio = getDevPixRatio();
  TTool *tool     = TApp::instance()->getCurrentTool()->getTool();
  TPointD topLeft =
      tool->getMatrix().inv() * winToWorld(geometry().topLeft() * devPixRatio);
  TPointD bottomRight = tool->getMatrix().inv() *
                        winToWorld(geometry().bottomRight() * devPixRatio);
  TObjectHandle *objHandle = TApp::instance()->getCurrentObject();
  if (tool->getToolType() & TTool::LevelTool && !objHandle->isSpline()) {
    topLeft.x /= m_dpiScale.x;
    topLeft.y /= m_dpiScale.y;
    bottomRight.x /= m_dpiScale.x;
    bottomRight.y /= m_dpiScale.y;
  }
  return TRectD(topLeft, bottomRight);
}
References TApp::getCurrentObject(), TApp::getCurrentTool(), TApp::instance(), and TAffine::inv().
getHGuide()
double SceneViewer::getHGuide (int index) override virtual
Implements TTool::Viewer.
{ return m_hRuler->getGuide(index); }
getHGuideCount()
int SceneViewer::getHGuideCount () override virtual
Implements TTool::Viewer.
{
  if (viewGuideToggle.getStatus())
    return m_hRuler->getGuideCount();
  else
    return 0;
}
getIsFlippedX()
bool SceneViewer::getIsFlippedX () const inline override virtual
Implements TTool::Viewer.
{ return m_isFlippedX; }
getIsFlippedY()
bool SceneViewer::getIsFlippedY () const inline override virtual
Implements TTool::Viewer.
{ return m_isFlippedY; }
getNormalZoomScale()
TAffine SceneViewer::getNormalZoomScale ()
{
  return TScale(getDpiFactor()).inv();
}
getPan3D()
TPointD SceneViewer::getPan3D () const inline
{ return m_pan3D; }
getPixelSize()
double SceneViewer::getPixelSize () const inline override virtual
Returns the length of a pixel in current OpenGL coordinates
Implements TTool::Viewer.
{ return m_pixelSize; }
getPreviewMode()
int SceneViewer::getPreviewMode () const inline
{ return m_previewMode; }
getPreviewRect()
TRectD SceneViewer::getPreviewRect () const override virtual
Implements Previewer::Listener.
{
  TApp *app               = TApp::instance();
  int row                 = app->getCurrentFrame()->getFrame();
  TXsheet *xsh            = app->getCurrentXsheet()->getXsheet();
  TStageObjectId cameraId = xsh->getStageObjectTree()->getCurrentCameraId();
  double cameraZ          = xsh->getZ(cameraId, row);
  TAffine cameraAff =
      xsh->getPlacement(cameraId, row) * TScale((1000 + cameraZ) / 1000);
  TDimensionD cameraSize =
      app->getCurrentScene()->getScene()->getCurrentCamera()->getSize();
  TDimension cameraRes =
      app->getCurrentScene()->getScene()->getCurrentCamera()->getRes();
  TScale cameraScale(Stage::inch * cameraSize.lx / cameraRes.lx,
                     Stage::inch * cameraSize.ly / cameraRes.ly);
  TRectD viewRect(-width() * 0.5, -height() * 0.5, width() * 0.5,
                  height() * 0.5);
  return (getViewMatrix() * cameraAff * cameraScale).inv() * viewRect;
}
getSceneMatrix()
TAffine SceneViewer::getSceneMatrix () const
Return the view matrix. The view matrix is a matrix contained in m_viewAff
{
  int viewMode = TApp::instance()->getCurrentFrame()->isEditingLevel()
                     ? LEVEL_VIEWMODE
                     : SCENE_VIEWMODE;
  if (is3DView()) return TAffine();
  return m_viewAff[viewMode];
}
References TApp::getCurrentFrame(), and TApp::instance().
getVGuide()
double SceneViewer::getVGuide (int index) override virtual
Implements TTool::Viewer.
{ return m_vRuler->getGuide(index); }
getVGuideCount()
int SceneViewer::getVGuideCount () override virtual
Implements TTool::Viewer.
{
  if (viewGuideToggle.getStatus())
    return m_vRuler->getGuideCount();
  else
    return 0;
}
getViewMatrix()
TAffine SceneViewer::getViewMatrix () const override virtual
Return the view matrix. The view matrix is a matrix contained in m_viewAff; if the SceneViewer in showing images in Camera view Mode (m_referenceMode = CAMERA_REFERENCE) the returned affine is composed with camera transformation.
Reimplemented from TTool::Viewer.
{
  int viewMode = TApp::instance()->getCurrentFrame()->isEditingLevel()
                     ? LEVEL_VIEWMODE
                     : SCENE_VIEWMODE;
  if (is3DView()) return TAffine();
  if (m_referenceMode == CAMERA_REFERENCE) {
    int frame    = TApp::instance()->getCurrentFrame()->getFrame();
    TXsheet *xsh = TApp::instance()->getCurrentXsheet()->getXsheet();
    TAffine aff  = xsh->getCameraAff(frame);
    return m_viewAff[viewMode] * aff.inv();
  } else
    return m_viewAff[viewMode];
}
References TXsheet::getCameraAff(), TApp::getCurrentFrame(), TApp::getCurrentXsheet(), TApp::instance(), and TAffine::inv().
Referenced by drawOverlay(), posToRow(), and worldToPos().
getViewportSize()
TDimension SceneViewer::getViewportSize () const inline
{ return TDimension(width(), height()); }
getZoomScale3D()
double SceneViewer::getZoomScale3D () const inline
{ return m_zoomScale3D; }
getZoomScaleFittingWithScreen()
double SceneViewer::getZoomScaleFittingWithScreen ()
when showing the viewer with full-screen mode, add a zoom factor which can show image fitting with the screen size
{
  TDimension imgSize;
  // get the image size to be rendered
  if (isPreviewEnabled())
    imgSize = TApp::instance()
                  ->getCurrentScene()
                  ->getScene()
                  ->getCurrentCamera()
                  ->getRes();
  else if (TApp::instance()->getCurrentFrame()->isEditingLevel()) {
    TXshSimpleLevel *sl = TApp::instance()->getCurrentLevel()->getSimpleLevel();
    if (!sl || sl->getType() == PLI_XSHLEVEL || sl->getImageDpi() == TPointD())
      return 0.0;
    imgSize = sl->getResolution();
  } else if (Preferences::instance()
                 ->isActualPixelViewOnSceneEditingModeEnabled() &&
             !CleanupPreviewCheck::instance()->isEnabled() &&
             !CameraTestCheck::instance()->isEnabled()) {
    TXshSimpleLevel *sl = TApp::instance()->getCurrentLevel()->getSimpleLevel();
    if (!sl || sl->getType() == PLI_XSHLEVEL || sl->getDpi() == TPointD())
      return 0.0;
    imgSize = sl->getResolution();
  } else  // SCENE_VIEWMODE
    return 0.0;
  // add small margin on the edge of the image
  int margin = 20;
  // get the desktop resolution
  QRect rec = QApplication::desktop()->screenGeometry();
  // fit to either direction
  int moni_x = rec.width() - (margin * 2);
  int moni_y = rec.height() - (margin * 2);
  return std::min((double)moni_x / (double)imgSize.lx,
                  (double)moni_y / (double)imgSize.ly);
}
References ToonzScene::getCurrentCamera(), TApp::getCurrentLevel(), TApp::getCurrentScene(), TCamera::getRes(), TXshLevel::getType(), CameraTestCheck::instance(), CleanupPreviewCheck::instance(), and TApp::instance().
GLInvalidateAll()
void SceneViewer::GLInvalidateAll () override virtual
Redraws the entire viewer, bypassing Qt's event system
Implements TTool::Viewer.
{
  m_clipRect = InvalidateAllRect;
  update();
  if (m_vRuler) m_vRuler->update();
  if (m_hRuler) m_hRuler->update();
}
Referenced by onToolChanged().
GLInvalidateRect()
void SceneViewer::GLInvalidateRect (const TRectD & rect) override virtual
Same as GLInvalidateAll(),
Implements TTool::Viewer.
{
  // in case that GLInvalidateAll is called just before coming here,
  // ignore the clip rect and refresh entire viewer
  if (m_clipRect == InvalidateAllRect)
    return;
  else if (rect.isEmpty())
    m_clipRect = InvalidateAllRect;
  else {
    m_clipRect += rect;
    if (!m_guidedDrawingBBox.isEmpty()) {
      TTool *tool         = TApp::instance()->getCurrentTool()->getTool();
      TPointD topLeft     = tool->getMatrix() * m_guidedDrawingBBox.getP00();
      TPointD bottomRight = tool->getMatrix() * m_guidedDrawingBBox.getP11();
      m_clipRect += TRectD(topLeft, bottomRight);
    }
  }
  update();
  if (m_vRuler) m_vRuler->update();
  if (m_hRuler) m_hRuler->update();
  m_guidedDrawingBBox.empty();
}
References TApp::getCurrentTool(), TApp::instance(), and TRectT< T >::isEmpty().
hideEvent()
void SceneViewer::hideEvent (QHideEvent *) override protected
{
  // Se il viewer e' hide e il preview e' attivo rimuovo il listner dal preview
  if (m_previewMode != NO_PREVIEW)
    Previewer::instance(m_previewMode == SUBCAMERA_PREVIEW)
        ->removeListener(this);
  TApp *app = TApp::instance();
  TSceneHandle *sceneHandle = app->getCurrentScene();
  if (sceneHandle) sceneHandle->disconnect(this);
  TFrameHandle *frameHandle = app->getCurrentFrame();
  if (frameHandle) frameHandle->disconnect(this);
  TPaletteHandle *paletteHandle =
      app->getPaletteController()->getCurrentLevelPalette();
  if (paletteHandle) paletteHandle->disconnect(this);
  TObjectHandle *objectHandle = app->getCurrentObject();
  if (objectHandle) objectHandle->disconnect(this);
  TOnionSkinMaskHandle *onionHandle = app->getCurrentOnionSkin();
  if (onionHandle) onionHandle->disconnect(this);
  TXshLevelHandle *levelHandle = app->getCurrentLevel();
  if (levelHandle) levelHandle->disconnect(this);
  TXsheetHandle *xsheetHandle = app->getCurrentXsheet();
  if (xsheetHandle) xsheetHandle->disconnect(this);
  ToolHandle *toolHandle = app->getCurrentTool();
  if (toolHandle) toolHandle->disconnect(this);
  disconnect(app, SIGNAL(tabletLeft()), this, SLOT(resetTabletStatus()));
#if defined(x64)
  if (m_stopMotion) {
    disconnect(m_stopMotion, SIGNAL(newImageReady()), this,
               SLOT(onNewStopMotionImageReady()));
    disconnect(m_stopMotion, SIGNAL(liveViewStopped()), this,
               SLOT(onStopMotionLiveViewStopped()));
  }
#endif
  // hide locator
  if (m_locator && m_locator->isVisible()) m_locator->hide();
}
initializeGL()
void SceneViewer::initializeGL () override protected
{
  initializeOpenGLFunctions();
  registerContext();
  // to be computed once through the software
  if (m_lutCalibrator && !m_lutCalibrator->isInitialized()) {
    m_lutCalibrator->initialize();
    connect(context(), SIGNAL(aboutToBeDestroyed()), this,
            SLOT(onContextAboutToBeDestroyed()));
  }
  // glClearColor(1.0,1.0,1.0,1);
  glClear(GL_COLOR_BUFFER_BIT);
  if (m_firstInitialized)
    m_firstInitialized = false;
  else {
    resizeGL(width(), height());
    update();
  }
  // re-computing the display list for the table
  m_tableDLId = -1;
}
inputMethodEvent()
void SceneViewer::inputMethodEvent (QInputMethodEvent * e) override protected
{
  TTool *tool = TApp::instance()->getCurrentTool()->getTool();
  if (tool && tool->isEnabled()) {
    tool->onInputText(e->preeditString().toStdWString(),
                      e->commitString().toStdWString(), e->replacementStart(),
                      e->replacementLength());
  }
}
invalidateAll()
void SceneViewer::invalidateAll () override virtual
Redraws the entire viewer, passing through Qt's event system
Implements TTool::Viewer.
{
  m_clipRect = InvalidateAllRect;
  update();
  if (m_vRuler) m_vRuler->update();
  if (m_hRuler) m_hRuler->update();
}
invalidateToolStatus()
void SceneViewer::invalidateToolStatus () override virtual
for a specific clipping rect Forces the viewer to update the perceived status of tools
Implements TTool::Viewer.
{
  TTool *tool = TApp::instance()->getCurrentTool()->getTool();
  if (tool) {
    m_toolDisableReason = tool->updateEnabled();
    if (tool->isEnabled()) {
      setToolCursor(this, tool->getCursorId());
      tool->setViewer(this);
      tool->updateMatrix();
    } else
      setCursor(Qt::ForbiddenCursor);
  } else
    setCursor(Qt::ForbiddenCursor);
}
References TApp::getCurrentTool(), TTool::getCursorId(), TApp::instance(), TTool::updateEnabled(), and TTool::updateMatrix().
Referenced by onLevelSwitched().
is3DView()
bool SceneViewer::is3DView () const override virtual
Implements TTool::Viewer.
{
  bool isCameraTest = CameraTestCheck::instance()->isEnabled();
  return (m_referenceMode == CAMERA3D_REFERENCE && !isCameraTest);
}
isEditPreviewSubcamera()
bool SceneViewer::isEditPreviewSubcamera () const inline
{ return m_editPreviewSubCamera; }
isPreviewEnabled()
bool SceneViewer::isPreviewEnabled () const inline
{ return m_previewMode != NO_PREVIEW; }
keyPressEvent()
void SceneViewer::keyPressEvent (QKeyEvent * event) override protected
{
  if (m_freezedStatus != NO_FREEZED) return;
  int key = event->key();
#ifdef WITH_CANON
  if ((m_stopMotion->m_canon->m_pickLiveViewZoom ||
       m_stopMotion->m_canon->m_zooming) &&
      (key == Qt::Key_Left || key == Qt::Key_Right || key == Qt::Key_Up ||
       key == Qt::Key_Down || key == Qt::Key_2 || key == Qt::Key_4 ||
       key == Qt::Key_6 || key == Qt::Key_8)) {
    if (m_stopMotion->m_canon->m_liveViewZoomReadyToPick == true) {
      if (key == Qt::Key_Left || key == Qt::Key_4) {
        m_stopMotion->m_canon->m_liveViewZoomPickPoint.x -= 10;
      }
      if (key == Qt::Key_Right || key == Qt::Key_6) {
        m_stopMotion->m_canon->m_liveViewZoomPickPoint.x += 10;
      }
      if (key == Qt::Key_Up || key == Qt::Key_8) {
        m_stopMotion->m_canon->m_liveViewZoomPickPoint.y += 10;
      }
      if (key == Qt::Key_Down || key == Qt::Key_2) {
        m_stopMotion->m_canon->m_liveViewZoomPickPoint.y -= 10;
      }
      if (m_stopMotion->m_canon->m_zooming) {
        m_stopMotion->m_canon->setZoomPoint();
      }
    }
    m_stopMotion->m_canon->calculateZoomPoint();
    event->accept();
    return;
  } else if (m_stopMotion->m_canon->m_pickLiveViewZoom &&
             (key == Qt::Key_Escape || key == Qt::Key_Enter ||
              key == Qt::Key_Return)) {
    m_stopMotion->m_canon->toggleZoomPicking();
    event->accept();
    return;
  } else
#endif
#if defined(x64)
      if (m_stopMotion->m_liveViewStatus == 2 &&
          (key == Qt::Key_Enter || key == Qt::Key_Return)) {
    m_stopMotion->captureImage();
    event->accept();
    return;
  }
#endif
  // resolving priority and tool-specific key events in this lambda
  auto ret = [&]() -> bool {
    TTool *tool = TApp::instance()->getCurrentTool()->getTool();
    if (!tool) return false;
    bool isTextToolActive = tool->getName() == T_Type && tool->isActive();
    if (!isTextToolActive) {
      if (ViewerZoomer(this).exec(event)) return true;
      if (SceneViewerShortcutReceiver(this).exec(event)) return true;
      // If this object is child of Viewer or ComboViewer
      // (m_isStyleShortcutSelective = true),
      // then consider about shortcut for the current style selection.
      if (m_isStyleShortcutSwitchable &&
          Preferences::instance()->isUseNumpadForSwitchingStylesEnabled() &&
          (event->modifiers() == Qt::NoModifier ||
           event->modifiers() == Qt::ShiftModifier ||
           event->modifiers() == Qt::KeypadModifier) &&
          ((Qt::Key_0 <= key && key <= Qt::Key_9) || key == Qt::Key_Tab ||
           key == Qt::Key_Backtab)) {
        // When the viewer is in full screen mode, directly call the style
        // shortcut function since the viewer is retrieved from the parent
        // panel.
        if (parentWidget() &&
            parentWidget()->windowState() & Qt::WindowFullScreen) {
          StyleShortcutSwitchablePanel::onKeyPress(event);
          return true;
        }
        event->ignore();
        return true;
      }
      // pressing F1, F2 or F3 key will flip between corresponding ghost
      if (CommandManager::instance()->getAction(MI_ShiftTrace)->isChecked() &&
          (Qt::Key_F1 <= key && key <= Qt::Key_F3)) {
        OnionSkinMask osm =
            TApp::instance()->getCurrentOnionSkin()->getOnionSkinMask();
        if (osm.getGhostFlipKey() != key) {
          osm.appendGhostFlipKey(key);
          TApp::instance()->getCurrentOnionSkin()->setOnionSkinMask(osm);
          TApp::instance()->getCurrentOnionSkin()->notifyOnionSkinMaskChanged();
        }
        return true;
      }
    }
    if (!tool->isEnabled()) return false;
    tool->setViewer(this);
    if (key == Qt::Key_Shift || key == Qt::Key_Control || key == Qt::Key_Alt ||
        key == Qt::Key_AltGr) {
      // quando l'utente preme shift/ctrl ecc. alcuni tool (es. pinch) devono
      // cambiare subito la forma del cursore, senza aspettare il prossimo move
      TMouseEvent toonzEvent;
      initToonzEvent(toonzEvent, event);
      toonzEvent.m_pos = TPointD(m_lastMousePos.x(),
                                 (double)(height() - 1) - m_lastMousePos.y());
      TPointD pos = tool->getMatrix().inv() * winToWorld(m_lastMousePos);
      TObjectHandle *objHandle = TApp::instance()->getCurrentObject();
      if (tool->getToolType() & TTool::LevelTool && !objHandle->isSpline()) {
        pos.x /= m_dpiScale.x;
        pos.y /= m_dpiScale.y;
      }
      tool->mouseMove(pos, toonzEvent);
      setToolCursor(this, tool->getCursorId());
    }
    if (key == Qt::Key_Menu || key == Qt::Key_Meta) return false;
    return tool->keyDown(event);
  }();
  if (!ret) {
    if (changeFrameSkippingHolds(event)) return;
    TFrameHandle *fh = TApp::instance()->getCurrentFrame();
    int origFrame    = fh->getFrame();
    if (key == Qt::Key_Up || key == Qt::Key_Left)
      fh->prevFrame();
    else if (key == Qt::Key_Down || key == Qt::Key_Right) {
      // If on a level frame pass the frame id after the last frame to allow
      // creating a new frame with the down arrow key
      TFrameId newId = 0;
      if (Preferences::instance()->getDownArrowLevelStripNewFrame() &&
          fh->getFrameType() == TFrameHandle::LevelFrame) {
        TXshSimpleLevel *level =
            TApp::instance()->getCurrentLevel()->getLevel()->getSimpleLevel();
        if (level) {
          std::vector<TFrameId> fids;
          level->getFids(fids);
          if (!fids.empty()) {
            int frameCount = (int)fids.size();
            newId          = level->index2fid(frameCount);
          }
        }
      }
      fh->nextFrame(newId);
    } else if (key == Qt::Key_Home)
      fh->firstFrame();
    else if (key == Qt::Key_End)
      fh->lastFrame();
    // Use arrow keys to shift the cell selection.
    if (Preferences::instance()->isUseArrowKeyToShiftCellSelectionEnabled() &&
        fh->getFrameType() != TFrameHandle::LevelFrame) {
      TCellSelection *cellSel =
          dynamic_cast<TCellSelection *>(TSelection::getCurrent());
      if (cellSel && !cellSel->isEmpty()) {
        int r0, c0, r1, c1;
        cellSel->getSelectedCells(r0, c0, r1, c1);
        int shiftFrame = fh->getFrame() - origFrame;
        cellSel->selectCells(r0 + shiftFrame, c0, r1 + shiftFrame, c1);
        TApp::instance()->getCurrentSelection()->notifySelectionChanged();
      }
    }
  }
  update();
  // TODO: devo accettare l'evento?
}
keyReleaseEvent()
void SceneViewer::keyReleaseEvent (QKeyEvent * event) override protected
{
  if (m_freezedStatus != NO_FREEZED) return;
  TTool *tool = TApp::instance()->getCurrentTool()->getTool();
  if (!tool || !tool->isEnabled()) return;
  tool->setViewer(this);
  int key = event->key();
  if (key == Qt::Key_Shift || key == Qt::Key_Control || key == Qt::Key_Alt ||
      key == Qt::Key_AltGr) {
    // quando l'utente preme shift/ctrl ecc. alcuni tool (es. pinch) devono
    // cambiare subito la forma del cursore, senza aspettare il prossimo move
    TMouseEvent toonzEvent;
    initToonzEvent(toonzEvent, event);
    toonzEvent.m_pos = TPointD(m_lastMousePos.x(),
                               (double)(height() - 1) - m_lastMousePos.y());
    TPointD pos = tool->getMatrix().inv() * winToWorld(m_lastMousePos);
    TObjectHandle *objHandle = TApp::instance()->getCurrentObject();
    if (tool->getToolType() & TTool::LevelTool && !objHandle->isSpline()) {
      pos.x /= m_dpiScale.x;
      pos.y /= m_dpiScale.y;
    }
    tool->mouseMove(pos, toonzEvent);
    setToolCursor(this, tool->getCursorId());
  }
  if (CommandManager::instance()->getAction(MI_ShiftTrace)->isChecked() &&
      (Qt::Key_F1 <= key && key <= Qt::Key_F3)) {
    OnionSkinMask osm =
        TApp::instance()->getCurrentOnionSkin()->getOnionSkinMask();
    osm.removeGhostFlipKey(key);
    TApp::instance()->getCurrentOnionSkin()->setOnionSkinMask(osm);
    TApp::instance()->getCurrentOnionSkin()->notifyOnionSkinMaskChanged();
  }
  if (tool->getName() == T_Type)
    event->accept();
  else
    event->ignore();
}
leaveEvent()
void SceneViewer::leaveEvent (QEvent *) override protected
{ onLeave(); }
mouseDoubleClickEvent()
void SceneViewer::mouseDoubleClickEvent (QMouseEvent * event) override protected
{
  if (m_gestureActive) {
    fitToCamera();
    m_gestureActive = false;
    return;
  }
  if (m_freezedStatus != NO_FREEZED) return;
  int frame = TApp::instance()->getCurrentFrame()->getFrame();
  if (frame == -1) return;
  TTool *tool = TApp::instance()->getCurrentTool()->getTool();
  if (!tool || !tool->isEnabled()) return;
  TMouseEvent toonzEvent;
  initToonzEvent(toonzEvent, event, height(), 1.0, getDevPixRatio());
  TPointD pos =
      tool->getMatrix().inv() * winToWorld(event->pos() * getDevPixRatio());
  TObjectHandle *objHandle = TApp::instance()->getCurrentObject();
  if (tool->getToolType() & TTool::LevelTool && !objHandle->isSpline()) {
    pos.x /= m_dpiScale.x;
    pos.y /= m_dpiScale.y;
  }
  if (event->button() == Qt::LeftButton)
    tool->leftButtonDoubleClick(pos, toonzEvent);
}
mouseMoveEvent()
void SceneViewer::mouseMoveEvent (QMouseEvent * event) override protected
{
  // if this is called just after tabletEvent, skip the execution
  if (m_tabletEvent) return;
  // and touchscreens but not touchpads...
  if (m_gestureActive && m_touchDevice == QTouchDevice::TouchScreen) {
    return;
  }
  // there are three cases to come here :
  // 1. on mouse is moved (no tablet is used)
  // 2. on tablet is moved, with middle or right button is pressed
  // 3. on tablet is moved, BUT tabletEvent was not called
  // 4. on tablet is moved without pen touching (i.e. floating move)
  // the case 3 sometimes occurs on OSX. (reporteed in QTBUG-26532 for Qt4, but
  // not confirmed in Qt5)
  // the case 4 can be removed once start using Qt5.9 and call
  // setTabletTracking(true).
  TMouseEvent mouseEvent;
  initToonzEvent(mouseEvent, event, height(), 1.0, getDevPixRatio());
  onMove(mouseEvent);
}
mousePressEvent()
void SceneViewer::mousePressEvent (QMouseEvent * event) override protected
{
  // source can be useful for detecting touch vs mouse,
  // but has reports of being unreliable on mac
  // so m_gestureActive is the marker for rejecting touch events
  int source = event->source();
  // if this is called just after tabletEvent, skip the execution
  if (m_tabletEvent) return;
  // and touchscreens but not touchpads...
  if (m_gestureActive && m_touchDevice == QTouchDevice::TouchScreen) {
    return;
  }
  // For now OSX has a critical problem that mousePressEvent is called just
  // after releasing the stylus, which causes the irregular stroke while
  // float-moving.
  // In such case resetTabletStatus() will be called on
  // QEvent::TabletLeaveProximity
  // and will cancel the onPress operation called here.
  TMouseEvent mouseEvent;
  m_mouseState = Touched;
  initToonzEvent(mouseEvent, event, height(), 1.0, getDevPixRatio());
  onPress(mouseEvent);
}
mouseReleaseEvent()
void SceneViewer::mouseReleaseEvent (QMouseEvent * event) override protected
{
  // if this is called just after tabletEvent, skip the execution
  if (m_tabletEvent) {
    // mouseRelease should not clear flag if we are starting or in middle of
    // stroke
    // initiated by tableEvent. All other cases, it's ok to clear flag
    if (m_tabletState == Released || m_tabletState == None)
      m_tabletEvent = false;
    return;
  }
  // for touchscreens but not touchpads...
  if (m_gestureActive && m_touchDevice == QTouchDevice::TouchScreen) {
    m_gestureActive = false;
    m_rotating      = false;
    m_zooming       = false;
    m_panning       = false;
    m_scaleFactor   = 0.0;
    m_rotationDelta = 0.0;
    return;
  }
  TMouseEvent mouseEvent;
  if (m_mouseState != None) m_mouseState = Released;
  initToonzEvent(mouseEvent, event, height(), 1.0, getDevPixRatio());
  onRelease(mouseEvent);
}
mult3DMatrix()
void SceneViewer::mult3DMatrix () protected
{
  glTranslated(m_pan3D.x, m_pan3D.y, 0);
  glScaled(m_zoomScale3D, m_zoomScale3D, 1);
  glRotated(m_theta3D, 1, 0, 0);
  glRotated(m_phi3D, 0, 1, 0);
}
navigatorPan()
void SceneViewer::navigatorPan (const QPoint & delta)
Pan the viewer by using "navigator" (red rectangle) in level strip
{
  panQt(delta);
  m_pos += delta;
}
onButtonPressed
void SceneViewer::onButtonPressed (FlipConsole::EGadget button) slot
{
  if (m_freezedStatus != NO_FREEZED) return;
  switch (button) {
  case FlipConsole::eSaveImg: {
    if (m_previewMode == NO_PREVIEW) {
      DVGui::warning(QObject::tr(
          "It is not possible to save images in camera stand view."));
      return;
    }
    TApp *app = TApp::instance();
    int row   = app->getCurrentFrame()->getFrame();
    Previewer *previewer =
        Previewer::instance(m_previewMode == SUBCAMERA_PREVIEW);
    if (!previewer->isFrameReady(row)) {
      DVGui::warning(QObject::tr("The preview images are not ready yet."));
      return;
    }
    TRasterP ras =
        previewer->getRaster(row, m_visualSettings.m_recomputeIfNeeded);
    TImageCache::instance()->add(QString("TnzCompareImg"),
                                 TRasterImageP(ras->clone()));
    break;
  }
  case FlipConsole::eSave:
    Previewer::instance(m_previewMode == SUBCAMERA_PREVIEW)
        ->saveRenderedFrames();
    break;
  case FlipConsole::eHisto: {
    QAction *action = CommandManager::instance()->getAction(MI_Histogram);
    action->trigger();
    break;
  }
  case FlipConsole::eDefineSubCamera:
    m_editPreviewSubCamera = !m_editPreviewSubCamera;
    update();
    break;
  // open locator. Create one for the first time
  case FlipConsole::eLocator:
    if (!m_locator) m_locator = new LocatorPopup(this);
    m_locator->show();
    m_locator->raise();
    m_locator->activateWindow();
    break;
  case FlipConsole::eZoomIn:
    zoomIn();
    break;
  case FlipConsole::eZoomOut:
    zoomOut();
    break;
  case FlipConsole::eFlipHorizontal:
    flipX();
    break;
  case FlipConsole::eFlipVertical:
    flipY();
    break;
  case FlipConsole::eResetView:
    resetSceneViewer();
    break;
  default:
    break;
  }
}
onContextAboutToBeDestroyed
void SceneViewer::onContextAboutToBeDestroyed () slot
{
  if (!m_lutCalibrator) return;
  makeCurrent();
  m_lutCalibrator->cleanup();
  doneCurrent();
  disconnect(context(), SIGNAL(aboutToBeDestroyed()), this,
             SLOT(onContextAboutToBeDestroyed()));
}
onContextMenu()
void SceneViewer::onContextMenu (const QPoint & pos, const QPoint & globalPos) protected
{
  if (m_freezedStatus != NO_FREEZED) return;
  if (m_isLocator) return;
  static bool menuVisible = false;
  if (menuVisible) return;
  menuVisible     = true;
  int devPixRatio = getDevPixRatio();
  TPoint winPos(pos.x() * devPixRatio, height() - pos.y() * devPixRatio);
  std::vector<int> columnIndices;
  // enable to select all the columns regardless of the click position
  for (int i = 0;
       i < TApp::instance()->getCurrentXsheet()->getXsheet()->getColumnCount();
       i++)
    columnIndices.push_back(i);
  SceneViewerContextMenu *menu = new SceneViewerContextMenu(this);
  TTool *tool = TApp::instance()->getCurrentTool()->getTool();
  TPointD p   = ((tool) ? tool->getMatrix().inv() : TAffine()) *
              winToWorld(pos * devPixRatio);
  menu->addEnterGroupCommands(p);
  menu->addLevelCommands(columnIndices);
  ComboViewerPanel *cvp =
      qobject_cast<ComboViewerPanel *>(parentWidget()->parentWidget());
  if (cvp) {
    menu->addSeparator();
    cvp->addShowHideContextMenu(menu);
  }
  SceneViewerPanel *svp = qobject_cast<SceneViewerPanel *>(
      parentWidget()->parentWidget()->parentWidget());
  if (svp) {
    menu->addSeparator();
    svp->addShowHideContextMenu(menu);
  }
  menu->exec(globalPos);
  delete menu;
  menuVisible = false;
}
onEnter()
void SceneViewer::onEnter () protected
{
  if (m_isMouseEntered) return;
  m_isMouseEntered = true;
  TApp *app = TApp::instance();
  app->setActiveViewer(this);
  TTool *tool      = app->getCurrentTool()->getTool();
  TXshLevel *level = app->getCurrentLevel()->getLevel();
  if (level && level->getSimpleLevel())
    m_dpiScale =
        getCurrentDpiScale(level->getSimpleLevel(), tool->getCurrentFid());
  else
    m_dpiScale = TPointD(1, 1);
  if (m_freezedStatus != NO_FREEZED) return;
  invalidateToolStatus();
  if (tool && tool->isEnabled()) {
    tool->setViewer(this);
    tool->updateMatrix();
    tool->onEnter();
  }
  // grab the focus, unless a line-edit is focused currently
  bool shouldSetFocus = true;
  QWidget *focusWidget = qApp->focusWidget();
  if (focusWidget) {
    QLineEdit *lineEdit = dynamic_cast<QLineEdit *>(focusWidget);
    if (lineEdit) {
      shouldSetFocus = false;
    }
  }
  if (shouldSetFocus) {
    setFocus();
  }
  update();
}
onFrameSwitched
void SceneViewer::onFrameSwitched () slot
{
  invalidateToolStatus();
  TTool *tool = TApp::instance()->getCurrentTool()->getTool();
  if (tool && tool->isEnabled()) {
    tool->setViewer(this);
    tool->updateMatrix();
    tool->onEnter();
  }
  GLInvalidateAll();
}
onLeave()
void SceneViewer::onLeave () protected
{
  if (!m_isMouseEntered) return;
  m_isMouseEntered = false;
  if (m_freezedStatus != NO_FREEZED) return;
  TTool *tool = TApp::instance()->getCurrentTool()->getTool();
  if (tool && tool->isEnabled()) tool->onLeave();
  // force reset the flipping of shift & trace
  if (CommandManager::instance()->getAction(MI_ShiftTrace)->isChecked())
    TTool::getTool("T_ShiftTrace", TTool::ToonzImage)->onLeave();
  update();
}
onLevelChanged
void SceneViewer::onLevelChanged () slot
{
  TTool *tool = TApp::instance()->getCurrentTool()->getTool();
  if (tool) {
    TXshLevel *level = TApp::instance()->getCurrentLevel()->getLevel();
    if (level && level->getSimpleLevel())
      m_dpiScale =
          getCurrentDpiScale(level->getSimpleLevel(), tool->getCurrentFid());
    else
      m_dpiScale = TPointD(1, 1);
  }
}
onLevelSwitched
void SceneViewer::onLevelSwitched () slot
when level is switched, update m_dpiScale in order to show white background for Ink&Paint work properly
{
  invalidateToolStatus();
  TApp *app        = TApp::instance();
  TTool *tool      = app->getCurrentTool()->getTool();
  TXshLevel *level = app->getCurrentLevel()->getLevel();
  if (level && level->getSimpleLevel())
    m_dpiScale =
        getCurrentDpiScale(level->getSimpleLevel(), tool->getCurrentFid());
  else
    m_dpiScale = TPointD(1, 1);
}
References TTool::getCurrentFid(), TApp::getCurrentLevel(), TApp::getCurrentTool(), TXshLevel::getSimpleLevel(), TApp::instance(), and invalidateToolStatus().
onMove()
void SceneViewer::onMove (const TMouseEvent & event) protected
{
  if (m_freezedStatus != NO_FREEZED) return;
  int devPixRatio = getDevPixRatio();
  QPointF curPos  = event.mousePos() * devPixRatio;
  bool cursorSet  = false;
  m_lastMousePos  = curPos;
  if (m_editPreviewSubCamera) {
    if (!PreviewSubCameraManager::instance()->mouseMoveEvent(this, event))
      return;
  }
  // if the "compare with snapshot" mode is activated, change the mouse cursor
  // on the border handle
  if (m_visualSettings.m_doCompare && isPreviewEnabled()) {
    if (std::abs(curPos.x() - width() * m_compareSettings.m_compareX) < 20) {
      cursorSet = true;
      setToolCursor(this, ToolCursor::ScaleHCursor);
    } else if (std::abs((height() - curPos.y()) -
                        height() * m_compareSettings.m_compareY) < 20) {
      cursorSet = true;
      setToolCursor(this, ToolCursor::ScaleVCursor);
    }
    // control of the border handle when the "compare with snapshot" mode is
    // activated
    if (m_compareSettings.m_dragCompareX || m_compareSettings.m_dragCompareY) {
      if (m_compareSettings.m_dragCompareX)
        m_compareSettings.m_compareX +=
            ((double)(curPos.x() - m_pos.x())) / width();
      else if (m_compareSettings.m_dragCompareY)
        m_compareSettings.m_compareY -=
            ((double)(curPos.y() - m_pos.y())) / height();
      m_compareSettings.m_compareX =
          tcrop(m_compareSettings.m_compareX, 0.0, 1.0);
      m_compareSettings.m_compareY =
          tcrop(m_compareSettings.m_compareY, 0.0, 1.0);
      update();
      m_pos = curPos;
    }
  } else if (m_mouseButton == Qt::NoButton || m_mouseButton == Qt::LeftButton) {
    if (is3DView()) {
      if (m_current3DDevice != NONE && m_mouseButton == Qt::LeftButton)
        return;
      else if (m_mouseButton == Qt::NoButton) {
        TRectD rect = TRectD(TPointD(m_topRasterPos.x, m_topRasterPos.y),
                             TDimensionD(20 * devPixRatio, 20 * devPixRatio));
        if (rect.contains(TPointD(curPos.x(), curPos.y())))
          m_current3DDevice = TOP_3D;
        else {
          rect = TRectD(TPointD(m_sideRasterPos.x, m_sideRasterPos.y),
                        TDimensionD(20 * devPixRatio, 20 * devPixRatio));
          if (rect.contains(TPointD(curPos.x(), curPos.y()))) {
            if (m_phi3D > 0)
              m_current3DDevice = SIDE_RIGHT_3D;
            else
              m_current3DDevice = SIDE_LEFT_3D;
          } else
            m_current3DDevice = NONE;
        }
        if (m_current3DDevice != NONE) {
          cursorSet = true;
          setToolCursor(this, ToolCursor::CURSOR_ARROW);
        }
      }
    }
    // if the middle mouse button is pressed while dragging, then do panning
    if (event.buttons() & Qt::MidButton) {
      // panning
      QPointF p = curPos - m_pos;
      if (m_pos == QPointF() && p.manhattanLength() > 300) return;
      panQt(curPos - m_pos);
      m_pos = curPos;
      return;
    }
    TTool *tool = TApp::instance()->getCurrentTool()->getTool();
    if (!tool || !tool->isEnabled()) {
      m_tabletEvent = false;
      return;
    }
    tool->setViewer(this);
    TPointD worldPos = winToWorld(curPos);
    TPointD pos      = tool->getMatrix().inv() * worldPos;
#ifdef WITH_CANON
    // grab screen picking for stop motion live view zoom
    if ((event.buttons() & Qt::LeftButton) &&
        StopMotion::instance()->m_canon->m_pickLiveViewZoom) {
      StopMotion::instance()->m_canon->makeZoomPoint(pos);
      return;
    }
#endif
    if (m_locator) {
      m_locator->onChangeViewAff(worldPos);
    }
    TObjectHandle *objHandle = TApp::instance()->getCurrentObject();
    if (tool->getToolType() & TTool::LevelTool && !objHandle->isSpline()) {
      pos.x /= m_dpiScale.x;
      pos.y /= m_dpiScale.y;
    }
    // qDebug() << "mouseMoveEvent. "  << (m_tabletEvent?"tablet":"mouse")
    //         << " pressure=" << m_pressure << " mouseButton=" << m_mouseButton
    //         << " buttonClicked=" << m_buttonClicked;
    // separate tablet events from mouse events
    if (m_tabletEvent &&
        (m_tabletState == OnStroke || m_tabletState == StartStroke) &&
        m_tabletMove) {
      if (m_toolSwitched) tool->leftButtonDown(pos, event);
      tool->leftButtonDrag(pos, event);
      m_tabletState = OnStroke;
    }
    else if (m_mouseButton == Qt::LeftButton) {
      // sometimes the mousePressedEvent is postponed to a wrong  mouse move
      // event!
      //      if (m_buttonClicked && !m_toolSwitched) tool->leftButtonDrag(pos,
      //      event);
      if (m_toolSwitched) tool->leftButtonDown(pos, event);
      tool->leftButtonDrag(pos, event);
      m_mouseState = OnStroke;
    } else if (m_pressure == 0.0) {
      tool->mouseMove(pos, event);
    }
    if (!cursorSet) setToolCursor(this, tool->getCursorId());
#ifdef WITH_CANON
    if (StopMotion::instance()->m_canon->m_pickLiveViewZoom)
      setToolCursor(this, ToolCursor::ZoomCursor);
#endif
    m_pos          = curPos;
    m_tabletMove   = false;
    m_toolSwitched = false;
  } else if (m_mouseButton == Qt::MidButton) {
    if ((event.buttons() & Qt::MidButton) == 0) m_mouseButton = Qt::NoButton;
    // scrub with shift and middle click
    else if (event.isShiftPressed() && event.isCtrlPressed()) {
      if (curPos.x() > m_pos.x()) {
        CommandManager::instance()->execute("MI_NextFrame");
      } else if (curPos.x() < m_pos.x()) {
        CommandManager::instance()->execute("MI_PrevFrame");
      }
    } else {
      // panning
      panQt(curPos - m_pos);
    }
    m_pos = curPos;
    return;
  }
}
onObjectSwitched
void SceneViewer::onObjectSwitched () slot
{
  TTool *tool = TApp::instance()->getCurrentTool()->getTool();
  if (tool && tool->isEnabled()) tool->updateMatrix();
  onLevelChanged();
  GLInvalidateAll();
}
onOnionSkinMaskChanged
void SceneViewer::onOnionSkinMaskChanged () inline slot
{ GLInvalidateAll(); }
onPreferenceChanged
void SceneViewer::onPreferenceChanged (const QString & prefName) slot
{
  if (prefName == "ColorCalibration") {
    if (Preferences::instance()->isColorCalibrationEnabled()) {
      // if the window is so shriked that the gl widget is empty,
      // showEvent can be called before creating the context.
      if (!context()) return;
      makeCurrent();
      if (!m_lutCalibrator)
        m_lutCalibrator = new LutCalibrator();
      else
        m_lutCalibrator->cleanup();
      m_lutCalibrator->initialize();
      connect(context(), SIGNAL(aboutToBeDestroyed()), this,
              SLOT(onContextAboutToBeDestroyed()));
      if (m_lutCalibrator->isValid() && !m_fbo) {
        if (Preferences::instance()->is30bitDisplayEnabled()) {
          QOpenGLFramebufferObjectFormat format;
          format.setInternalTextureFormat(TGL_TexFmt10);
          m_fbo = new QOpenGLFramebufferObject(width(), height(), format);
        } else  // normally, initialize with GL_RGBA8 format
          m_fbo = new QOpenGLFramebufferObject(width(), height());
      }
      doneCurrent();
    }
    update();
  }
}
onPress()
void SceneViewer::onPress (const TMouseEvent & event) protected
{
  if (m_mouseButton != Qt::NoButton) {
    if (event.m_isTablet && m_mouseState != None) {
      //      qDebug() << "[onPress] Switched from MousePress to TabletPress";
      // TabletPress came immediately after MousePress. Let's switch to
      // tabletPress but not end the prior action or it leaves an extra
      // stroke
      m_mouseState    = None;
      m_buttonClicked = false;
    } else {
      // if some button is pressed while another button being active,
      // finish the action for the previous button first.
      TMouseEvent preEvent = event;
      preEvent.m_button    = m_mouseButton;
      onRelease(preEvent);
    }
  }
  // evita i press ripetuti
  if (m_buttonClicked) return;
  m_buttonClicked = true;
  m_toolSwitched  = false;
  if (m_freezedStatus != NO_FREEZED) return;
  m_pos         = event.mousePos() * getDevPixRatio();
  m_mouseButton = event.button();
  // when using tablet, avoid unexpected drawing behavior occurs when
  // middle-click
  if (m_tabletEvent && m_mouseButton == Qt::MidButton &&
      event.isLeftButtonPressed()) {
    return;
  }
  if (is3DView() && m_current3DDevice != NONE &&
      m_mouseButton == Qt::LeftButton)
    return;
  else if (m_mouseButton == Qt::LeftButton && m_editPreviewSubCamera) {
    if (!PreviewSubCameraManager::instance()->mousePressEvent(this, event))
      return;
  } else if (m_mouseButton == Qt::LeftButton && m_visualSettings.m_doCompare) {
    if (std::abs(m_pos.x() - width() * m_compareSettings.m_compareX) < 20) {
      m_compareSettings.m_dragCompareX = true;
      m_compareSettings.m_dragCompareY = false;
      m_compareSettings.m_compareY     = ImagePainter::DefaultCompareValue;
      update();
      m_tabletEvent = false;
      m_tabletState = None;
      return;
    } else if (std::abs((height() - m_pos.y()) -
                        height() * m_compareSettings.m_compareY) < 20) {
      m_compareSettings.m_dragCompareY = true;
      m_compareSettings.m_dragCompareX = false;
      m_compareSettings.m_compareX     = ImagePainter::DefaultCompareValue;
      update();
      m_tabletEvent = false;
      m_tabletState = None;
      return;
    } else
      m_compareSettings.m_dragCompareX = m_compareSettings.m_dragCompareY =
          false;
  }
  if (m_freezedStatus != NO_FREEZED) return;
  TTool *tool = TApp::instance()->getCurrentTool()->getTool();
  if (!tool || !tool->isEnabled()) {
    m_tabletEvent = false;
    m_tabletState = None;
    return;
  }
  tool->setViewer(this);
  if (m_mouseButton == Qt::LeftButton && tool->preLeftButtonDown()) {
    tool = TApp::instance()->getCurrentTool()->getTool();
    if (!tool || !tool->isEnabled()) {
      m_tabletEvent = false;
      m_tabletState = None;
      return;
    }
    tool->setViewer(this);
  }
  // if(!m_tabletEvent) qDebug() << "-----------------MOUSE PRESS 'PURO'.
  // POSSIBILE EMBOLO";
  TPointD pos = tool->getMatrix().inv() * winToWorld(m_pos);
  TObjectHandle *objHandle = TApp::instance()->getCurrentObject();
  if (tool->getToolType() & TTool::LevelTool && !objHandle->isSpline()) {
    pos.x /= m_dpiScale.x;
    pos.y /= m_dpiScale.y;
  }
#ifdef WITH_CANON
  // grab screen picking for stop motion live view zoom
  if (StopMotion::instance()->m_canon->m_pickLiveViewZoom) {
    StopMotion::instance()->m_canon->makeZoomPoint(pos);
    return;
  }
#endif
  // separate tablet and mouse events
  if (m_tabletEvent && m_tabletState == Touched) {
    TApp::instance()->getCurrentTool()->setToolBusy(true);
    m_tabletState = StartStroke;
    tool->leftButtonDown(pos, event);
  } else if (m_mouseButton == Qt::LeftButton) {
    m_mouseState = StartStroke;
    TApp::instance()->getCurrentTool()->setToolBusy(true);
    tool->leftButtonDown(pos, event);
  }
  if (m_mouseButton == Qt::RightButton) tool->rightButtonDown(pos, event);
}
onPreviewUpdate()
void SceneViewer::onPreviewUpdate () override virtual
Reimplemented from Previewer::Listener.
{
  update();
  emit previewStatusChanged();
}
onRelease()
void SceneViewer::onRelease (const TMouseEvent & event) protected
{
  // evita i release ripetuti
  if (!m_buttonClicked) return;
  m_buttonClicked = false;
  TTool *tool = TApp::instance()->getCurrentTool()->getTool();
  if (!tool || !tool->isEnabled()) {
    if (!m_toolDisableReason.isEmpty() && m_mouseButton == Qt::LeftButton &&
        !m_editPreviewSubCamera)
      DVGui::warning(m_toolDisableReason);
  }
  if (m_freezedStatus != NO_FREEZED) return;
  if (m_mouseButton != event.button()) return;
  if (m_current3DDevice != NONE) {
    m_mouseButton = Qt::NoButton;
    m_tabletEvent = false;
    m_pressure    = 0;
    if (m_current3DDevice == SIDE_LEFT_3D)
      set3DLeftSideView();
    else if (m_current3DDevice == SIDE_RIGHT_3D)
      set3DRightSideView();
    else if (m_current3DDevice == TOP_3D)
      set3DTopView();
    return;
  }
  if (m_mouseButton == Qt::LeftButton && m_editPreviewSubCamera) {
    if (!PreviewSubCameraManager::instance()->mouseReleaseEvent(this))
      goto quit;
  }
  if (m_compareSettings.m_dragCompareX || m_compareSettings.m_dragCompareY) {
    m_compareSettings.m_dragCompareX = m_compareSettings.m_dragCompareY = false;
    goto quit;
  }
  m_pos = QPointF();
  if (!tool || !tool->isEnabled()) goto quit;
  tool->setViewer(this);
  {
    TPointD pos = tool->getMatrix().inv() *
                  winToWorld(event.mousePos() * getDevPixRatio());
    TObjectHandle *objHandle = TApp::instance()->getCurrentObject();
    if (tool->getToolType() & TTool::LevelTool && !objHandle->isSpline()) {
      pos.x /= m_dpiScale.x;
      pos.y /= m_dpiScale.y;
    }
    if (m_mouseButton == Qt::LeftButton || m_tabletState == Released) {
      if (!m_toolSwitched) tool->leftButtonUp(pos, event);
      TApp::instance()->getCurrentTool()->setToolBusy(false);
    }
  }
quit:
  m_mouseButton = Qt::NoButton;
  // Leave m_tabletEvent as-is in order to check whether the onRelease is called
  // from tabletEvent or not in mouseReleaseEvent.
  if (m_tabletState == Released)  // only clear if tabletRelease event
    m_tabletEvent = false;
  // If m_tabletState is "Touched", we've been called by tabletPress event.
  // Don't clear it out table state so the tablePress event will process
  // correctly.
  if (m_tabletState != Touched) m_tabletState = None;
  m_mouseState = None;
  m_tabletMove = false;
  m_pressure   = 0;
}
onRenderCompleted()
void SceneViewer::onRenderCompleted (int frame) override virtual
Reimplemented from Previewer::Listener.
{
  invalidateAll();
  emit previewStatusChanged();
}
onRenderStarted()
void SceneViewer::onRenderStarted (int frame) override virtual
Reimplemented from Previewer::Listener.
{ emit previewStatusChanged(); }
onSceneChanged
void SceneViewer::onSceneChanged () slot
{
  onLevelChanged();
  GLInvalidateAll();
}
onToolChanged
void SceneViewer::onToolChanged () slot
when tool options are changed, update tooltip immediately
{
  TTool *tool = TApp::instance()->getCurrentTool()->getTool();
  if (tool) setToolCursor(this, tool->getCursorId());
  GLInvalidateAll();
}
References TApp::getCurrentTool(), TTool::getCursorId(), GLInvalidateAll(), and TApp::instance().
onToolSwitched
void SceneViewer::onToolSwitched () slot
{
  m_forceGlFlush = true;
  m_toolSwitched = true;
  invalidateToolStatus();
  TTool *tool = TApp::instance()->getCurrentTool()->getTool();
  if (tool) {
    tool->updateMatrix();
    if (tool->getViewer()) tool->getViewer()->setGuidedStrokePickerMode(0);
  }
  onLevelChanged();
  update();
}
onXsheetChanged
void SceneViewer::onXsheetChanged () slot
{
  m_forceGlFlush = true;
  TTool *tool    = TApp::instance()->getCurrentTool()->getTool();
  if (tool && tool->isEnabled()) tool->updateMatrix();
  onLevelChanged();
  GLInvalidateAll();
}
paintGL()
void SceneViewer::paintGL () override protected
{
#ifdef _DEBUG
  if (!check_framebuffer_status()) {
    /* QGLWidget  widget /(platform ?)
     * GL_FRAMEBUFFER_UNDEFINED  paintGL()  */
    return;
  }
#endif
#ifdef MACOSX
  // following lines are necessary to solve a problem on iMac20
  // It seems that for some errors in the openGl implementation, buffers are not
  // set correctly.
  if (m_isMouseEntered && m_forceGlFlush) {
    m_isMouseEntered = false;
    m_forceGlFlush   = false;
    glDrawBuffer(GL_FRONT);
    glFlush();
    glDrawBuffer(GL_BACK);
  }
#endif
#ifdef FPS_HISTOGRAM
  QTime time;
  time.start();
#endif
  if (!m_isPicking && m_lutCalibrator && m_lutCalibrator->isValid())
    m_fbo->bind();
  if (m_hRuler && m_vRuler) {
    if (!viewRulerToggle.getStatus() &&
        (m_hRuler->isVisible() || m_vRuler->isVisible())) {
      m_hRuler->hide();
      m_vRuler->hide();
    } else if (viewRulerToggle.getStatus() &&
               (!m_hRuler->isVisible() || !m_vRuler->isVisible())) {
      m_hRuler->show();
      m_vRuler->show();
    }
  }
  // Il freezed e' attivo ed e' in stato "normale": mostro l'immagine grabbata.
  if (m_freezedStatus == NORMAL_FREEZED) {
    assert(!!m_viewGrabImage);
    m_viewGrabImage->lock();
    glPushMatrix();
    glLoadIdentity();
    glRasterPos2d(0, 0);
    glPixelStorei(GL_UNPACK_ROW_LENGTH, 0);
    glDrawPixels(m_viewGrabImage->getLx(), m_viewGrabImage->getLy(), TGL_FMT,
                 TGL_TYPE, m_viewGrabImage->getRawData());
    glPopMatrix();
    m_viewGrabImage->unlock();
    if (!m_isPicking && m_lutCalibrator && m_lutCalibrator->isValid())
      m_lutCalibrator->onEndDraw(m_fbo);
    return;
  }
  drawBuildVars();
  // This seems not to be necessary for now.
  // copyFrontBufferToBackBuffer();
  drawEnableScissor();
  drawBackground();
  if (m_previewMode != FULL_PREVIEW) {
    drawCameraStand();
  }
  if (isPreviewEnabled()) drawPreview();
  drawOverlay();
  drawDisableScissor();
  // Il freezed e' attivo ed e' in stato "update": faccio il grab del viewer.
  if (m_freezedStatus == UPDATE_FREEZED) {
    m_viewGrabImage = rasterFromQImage(grabFramebuffer());
    m_freezedStatus = NORMAL_FREEZED;
  }
#ifdef FPS_HISTOGRAM
  int t0 = time.elapsed();
  glFlush();
  glFinish();
  int t1 = time.elapsed();
  drawFpsGraph(t0, t1);
#endif
  // TOfflineGL::setContextManager(0);
  if (!m_isPicking && m_lutCalibrator && m_lutCalibrator->isValid())
    m_lutCalibrator->onEndDraw(m_fbo);
  // wait to achieve precise fps
  if (m_timer && m_timer->isValid()) {
    qint64 currentInstant = m_timer->nsecsElapsed();
    while (currentInstant < m_targetInstant) {
      currentInstant = m_timer->nsecsElapsed();
    }
  }
}
pan()
void SceneViewer::pan (const TPointD & delta) inline override protected virtual
Implements TTool::Viewer.
{ panQt(QPointF(delta.x, delta.y)); }
panQt()
void SceneViewer::panQt (const QPointF & delta) protected
{
  if (delta == QPointF()) return;
  if (is3DView())
    m_pan3D += TPointD(delta.x(), -delta.y());
  else {
    // TAffine &viewAff = m_viewAff[m_viewMode];
    // viewAff = TTranslation(delta.x(), -delta.y()) * viewAff;
    setViewMatrix(TTranslation(delta.x(), -delta.y()) * m_viewAff[m_viewMode],
                  m_viewMode);
  }
  invalidateAll();
  emit refreshNavi();
}
pick()
int SceneViewer::pick (const TPointD & point) override protected virtual
return the column index of the drawing intersecting point p (window coordinate, pixels, bottom-left origin)
Implements TTool::Viewer.
{
  // pick is typically called in a mouse event handler.
  // QGLWidget::makeCurrent() is not automatically called in these events.
  // (to exploit the bug: open the FxEditor preview and then select the edit
  // tool)
  m_isPicking = true;
  makeCurrent();
  assert(glGetError() == GL_NO_ERROR);
  GLint viewport[4];
  glGetIntegerv(GL_VIEWPORT, viewport);
  std::array<GLuint, 512> selectBuffer;
  glSelectBuffer(selectBuffer.size(), selectBuffer.data());
  glRenderMode(GL_SELECT);
  // definisco la matrice di proiezione
  glMatrixMode(GL_PROJECTION);
  GLdouble mat[16];
  glGetDoublev(GL_PROJECTION_MATRIX, mat);
  glPushMatrix();
  glLoadIdentity();
  gluPickMatrix(point.x, point.y, 5, 5, viewport);
  glMultMatrixd(mat);
  assert(glGetError() == GL_NO_ERROR);
  // disegno la scena
  glMatrixMode(GL_MODELVIEW);
  glPushMatrix();
  glInitNames();
  assert(glGetError() == GL_NO_ERROR);
  // WARNING: We have to draw the scene in CAMERASTAND mode. Observe that the
  // preview mode may
  // invoke event processing - therefore triggering other pick events while in
  // GL_SELECT
  // render mode...
  int previewMode = m_previewMode;
  m_previewMode   = NO_PREVIEW;
  //   OPTIMIZATION / QUICK FIX
  // A 1x1 clipping rect around the picked pos can very well be used instead of
  // redrawing
  // the *entire viewer*.
  // This is needed especially since some graphic cards (all NVidias we have
  // tested) are
  // very slow otherwise. This could be due to this particular rendering mode -
  // or because
  // we could be painting OUTSIDE a paintEvent()...
  TRectD oldClipRect(m_clipRect);
  m_clipRect = TRectD(point.x, point.y, point.x + 1, point.y + 1);
  paintGL();  // draw identifiable objects
  m_clipRect = oldClipRect;
  m_previewMode = previewMode;
  assert(glGetError() == GL_NO_ERROR);
  glPopMatrix();
  // rimetto a posto la matrice di proiezione
  glMatrixMode(GL_PROJECTION);
  glPopMatrix();
  glMatrixMode(GL_MODELVIEW);
  assert(glGetError() == GL_NO_ERROR);
  // conto gli hits
  int ret      = -1;
  int hitCount = glRenderMode(GL_RENDER);
  GLuint *p    = selectBuffer.data();
  for (int i = 0; i < hitCount; ++i) {
    GLuint nameCount = *p++;
    GLuint zmin      = *p++;
    GLuint zmax      = *p++;
    if (nameCount > 0) {
      GLuint name = *p;
      ret         = name;  // items.push_back(PickItem(name, zmin, zmax));
    }
    p += nameCount;
  }
  assert(glGetError() == GL_NO_ERROR);
  m_isPicking = false;
  return ret;
}
posToColumnIndex()
int SceneViewer::posToColumnIndex (const TPointD & p, double distance, bool includeInvisible = true) const override protected virtual
return the column indexes of the drawings intersecting point p (window coordinate, pixels, bottom-left origin)
Implements TTool::Viewer.
{
  std::vector<int> ret;
  posToColumnIndexes(p, ret, distance, includeInvisible);
  return ret.empty() ? -1 : ret.back();
}
posToColumnIndexes()
void SceneViewer::posToColumnIndexes (const TPointD & p, std::vector< int > & indexes, double distance, bool includeInvisible = true) const override protected virtual
Implements TTool::Viewer.
{
  int oldRasterizePli    = TXshSimpleLevel::m_rasterizePli;
  TApp *app              = TApp::instance();
  ToonzScene *scene      = app->getCurrentScene()->getScene();
  TXsheet *xsh           = app->getCurrentXsheet()->getXsheet();
  int frame              = app->getCurrentFrame()->getFrame();
  int currentColumnIndex = app->getCurrentColumn()->getColumnIndex();
  OnionSkinMask osm      = app->getCurrentOnionSkin()->getOnionSkinMask();
  TPointD pos = TPointD(p.x - width() / 2, p.y - height() / 2);
  Stage::Picker picker(getViewMatrix(), pos, m_visualSettings,
                       getDevPixRatio());
  picker.setMinimumDistance(distance);
  TXshSimpleLevel::m_rasterizePli = 0;
  Stage::VisitArgs args;
  args.m_scene       = scene;
  args.m_xsh         = xsh;
  args.m_row         = frame;
  args.m_col         = currentColumnIndex;
  args.m_osm         = &osm;
  args.m_onlyVisible = includeInvisible;
  Stage::visit(picker, args); /*
picker,
scene,
xsh,
frame,
currentColumnIndex,
osm,
false,
0,
false,
includeInvisible);
*/
  TXshSimpleLevel::m_rasterizePli = oldRasterizePli;
  picker.getColumnIndexes(indexes);
}
posToRow()
int SceneViewer::posToRow (const TPointD & p, double distance, bool includeInvisible = true, bool currentColumnOnly = false) const override protected virtual
return the row of the drawings intersecting point p (used with onion skins) (window coordinate, pixels, bottom-left origin)
Implements TTool::Viewer.
{
  int oldRasterizePli = TXshSimpleLevel::m_rasterizePli;
  TApp *app           = TApp::instance();
  OnionSkinMask osm   = app->getCurrentOnionSkin()->getOnionSkinMask();
  TPointD pos = TPointD(p.x - width() / 2, p.y - height() / 2);
  Stage::Picker picker(getViewMatrix(), pos, m_visualSettings,
                       getDevPixRatio());
  picker.setMinimumDistance(distance);
  if (app->getCurrentFrame()->isEditingLevel()) {
    Stage::visit(picker, app->getCurrentLevel()->getLevel(),
                 app->getCurrentFrame()->getFid(), osm,
                 app->getCurrentFrame()->isPlaying(), false);
  } else {
    ToonzScene *scene      = app->getCurrentScene()->getScene();
    TXsheet *xsh           = app->getCurrentXsheet()->getXsheet();
    int frame              = app->getCurrentFrame()->getFrame();
    int currentColumnIndex = app->getCurrentColumn()->getColumnIndex();
    TXshSimpleLevel::m_rasterizePli = 0;
    Stage::VisitArgs args;
    args.m_scene       = scene;
    args.m_xsh         = xsh;
    args.m_row         = frame;
    args.m_col         = currentColumnIndex;
    args.m_osm         = &osm;
    args.m_onlyVisible = includeInvisible;
    if (currentColumnOnly) picker.setCurrentColumnIndex(currentColumnIndex);
    Stage::visit(picker, args);
  }
  TXshSimpleLevel::m_rasterizePli = oldRasterizePli;
  return picker.getRow();
}
References TApp::getCurrentColumn(), TApp::getCurrentFrame(), TApp::getCurrentLevel(), TApp::getCurrentOnionSkin(), TApp::getCurrentScene(), TApp::getCurrentXsheet(), getViewMatrix(), TApp::instance(), TTool::Viewer::m_visualSettings, and Stage::visit().
projectToZ()
double SceneViewer::projectToZ (const TPointD & delta) override virtual
Implements TTool::Viewer.
{
  glPushMatrix();
  mult3DMatrix();
  GLint viewport[4];
  double modelview[16], projection[16];
  glGetIntegerv(GL_VIEWPORT, viewport);
  for (int i = 0; i < 16; i++)
    projection[i] = (double)m_projectionMatrix.constData()[i];
  glGetDoublev(GL_MODELVIEW_MATRIX, modelview);
  double ax, ay, az, bx, by, bz;
  gluProject(0, 0, 0, modelview, projection, viewport, &ax, &ay, &az);
  gluProject(0, 0, 1, modelview, projection, viewport, &bx, &by, &bz);
  glPopMatrix();
  TPointD zdir(bx - ax, by - ay);
  double zdirLength2 = norm2(zdir);
  if (zdirLength2 > 0.0) {
    double dz = (delta * zdir) / zdirLength2;
    return dz;
  } else
    return 0.0;
}
regeneratePreview
void SceneViewer::regeneratePreview () slot
{
  Previewer::instance(m_previewMode == SUBCAMERA_PREVIEW)->clear();
  update();
}
regeneratePreviewFrame
void SceneViewer::regeneratePreviewFrame () slot
{
  Previewer::instance(m_previewMode == SUBCAMERA_PREVIEW)
      ->clear(TApp::instance()->getCurrentFrame()->getFrame());
  update();
}
registerContext()
void SceneViewer::registerContext () protected
{
  // release the old context, if any
  // this will be happen when dock / float the viewer panel.
  bool hasOldContext;
#ifdef _WIN32
  hasOldContext =
      (m_currentContext.first != nullptr && m_currentContext.second != nullptr);
#else
  hasOldContext = m_currentContext != nullptr;
#endif
  if (hasOldContext) {
    int ret = l_contexts.erase(m_currentContext);
    if (ret)
      TGLDisplayListsManager::instance()->releaseContext(m_currentContext);
  }
  // then, register context and the space Id correspondent to it.
  int displayListId;
  if (TApp::instance()->getMainWindow() &&
      TApp::instance()->getMainWindow()->isAncestorOf(this) &&
      QThread::currentThread() == qGuiApp->thread()) {
    // obtain displaySpaceId for main thread
    if (l_mainDisplayListsSpaceId == -1)
      l_mainDisplayListsSpaceId =
          TGLDisplayListsManager::instance()->storeProxy(new DummyProxy);
    displayListId = l_mainDisplayListsSpaceId;
  }
  // for the other cases (such as for floating viewer), it can't share the
  // context so
  // obtain different id
  else
    displayListId =
        TGLDisplayListsManager::instance()->storeProxy(new DummyProxy);
  TGlContext tglContext(tglGetCurrentContext());
  TGLDisplayListsManager::instance()->attachContext(displayListId, tglContext);
  l_contexts.insert(tglContext);
}
releaseBusyOnTabletMove
void SceneViewer::releaseBusyOnTabletMove () inline slot
{ m_isBusyOnTabletMove = false; }
releaseFBO()
void SceneViewer::releaseFBO () override virtual
Reimplemented from TTool::Viewer.
{
  if (m_fbo) m_fbo->release();
}
resetInputMethod()
void SceneViewer::resetInputMethod () override protected virtual
Implements TTool::Viewer.
{
#if QT_VERSION >= 0x050000
  QGuiApplication::inputMethod()->reset();
#else
  qApp->inputContext()->reset();
#endif
}
resetPosition
void SceneViewer::resetPosition () slot
{
  m_viewAff[m_viewMode].a13 = 0.0;
  m_viewAff[m_viewMode].a23 = 0.0;
  invalidateAll();
}
resetRotation
void SceneViewer::resetRotation () slot
{
  double reverseRotatation = m_rotationAngle[m_viewMode] * -1;
  if (m_isFlippedX) reverseRotatation *= -1;
  if (m_isFlippedY) reverseRotatation *= -1;
  TTool *tool    = TApp::instance()->getCurrentTool()->getTool();
  TPointD center = m_viewAff[m_viewMode].inv() * TPointD(0, 0);
  if (tool->getName() == "T_Rotate" &&
      tool->getProperties(0)
              ->getProperty("Rotate On Camera Center")
              ->getValueAsString() == "1")
    center = TPointD(0, 0);
  rotate(center, reverseRotatation);
}
resetSceneViewer
void SceneViewer::resetSceneViewer () slot
{
  m_visualSettings.m_sceneProperties =
      TApp::instance()->getCurrentScene()->getScene()->getProperties();
  for (int i = 0; i < m_viewAff.size(); ++i) {
    setViewMatrix(getNormalZoomScale(), i);
    m_rotationAngle[i] = 0.0;
  }
  m_pos         = QPoint(0, 0);
  m_pan3D       = TPointD(0, 0);
  m_zoomScale3D = 0.1;
  m_theta3D     = 20;
  m_phi3D       = 30;
  m_isFlippedX  = false;
  m_isFlippedY  = false;
  fitToCameraOutline();
  emit onZoomChanged();
  emit onFlipHChanged(m_isFlippedX);
  emit onFlipVChanged(m_isFlippedY);
  invalidateAll();
}
resetTabletStatus
void SceneViewer::resetTabletStatus () slot
{
  if (!m_buttonClicked) return;
  m_mouseButton   = Qt::NoButton;
  m_tabletEvent   = false;
  m_tabletState   = None;
  m_tabletMove    = false;
  m_pressure      = 0;
  m_buttonClicked = false;
  if (TApp::instance()->getCurrentTool()->isToolBusy())
    TApp::instance()->getCurrentTool()->setToolBusy(false);
}
resetZoom
void SceneViewer::resetZoom () slot
{
  TPointD realCenter(m_viewAff[m_viewMode].a13, m_viewAff[m_viewMode].a23);
  TAffine aff =
      getNormalZoomScale() * TRotation(realCenter, m_rotationAngle[m_viewMode]);
  aff.a13 = realCenter.x;
  aff.a23 = realCenter.y;
  if (m_isFlippedX) aff = aff * TScale(-1, 1);
  if (m_isFlippedY) aff = aff * TScale(1, -1);
  setViewMatrix(aff, m_viewMode);
  invalidateAll();
  emit onZoomChanged();
}
resizeGL()
void SceneViewer::resizeGL (int width, int height) override protected
{
  w *= getDevPixRatio();
  h *= getDevPixRatio();
  glViewport(0, 0, w, h);
  glMatrixMode(GL_PROJECTION);
  glLoadIdentity();
  glOrtho(0, w, 0, h, -4000, 4000);
  m_projectionMatrix.setToIdentity();
  m_projectionMatrix.ortho(0, w, 0, h, -4000, 4000);
  glMatrixMode(GL_MODELVIEW);
  glLoadIdentity();
  glTranslatef(0.375, 0.375, 0.0);
  // make the center of the viewer = origin
  glTranslated(w * 0.5, h * 0.5, 0);
  if (m_freezedStatus == NORMAL_FREEZED) m_freezedStatus = UPDATE_FREEZED;
  if (m_previewMode != NO_PREVIEW) requestTimedRefresh();
  // remake fbo with new size
  if (m_lutCalibrator && m_lutCalibrator->isValid()) {
    if (m_fbo) delete m_fbo;
    if (Preferences::instance()->is30bitDisplayEnabled()) {
      QOpenGLFramebufferObjectFormat format;
      format.setInternalTextureFormat(TGL_TexFmt10);
      m_fbo = new QOpenGLFramebufferObject(w, h, format);
    } else  // normally, initialize with GL_RGBA8 format
      m_fbo = new QOpenGLFramebufferObject(w, h);
  }
  // for updating the navigator in levelstrip
  emit refreshNavi();
}
rotate()
void SceneViewer::rotate (const TPointD & center, double angle) override protected virtual
Implements TTool::Viewer.
{
  if (angle == 0) return;
  if (m_isFlippedX != m_isFlippedY) angle = -angle;
  m_rotationAngle[m_viewMode] += angle;
  TPointD realCenter = m_viewAff[m_viewMode] * center;
  setViewMatrix(TRotation(realCenter, angle) * m_viewAff[m_viewMode],
                m_viewMode);
  invalidateAll();
}
rotate3D()
void SceneViewer::rotate3D (double dPhi, double dTheta) override protected virtual
Implements TTool::Viewer.
{
  if (dPhi == 0 && dTheta == 0) return;
  m_phi3D   = (float)tcrop(m_phi3D + dPhi, -90.0, 90.0);
  m_theta3D = (float)tcrop(m_theta3D + dTheta, 0.0, 90.0);
  invalidateAll();
}
set3DLeftSideView()
void SceneViewer::set3DLeftSideView () protected
{
  m_phi3D   = -90;
  m_theta3D = 0;
  invalidateAll();
}
set3DRightSideView()
void SceneViewer::set3DRightSideView () protected
{
  m_phi3D   = 90;
  m_theta3D = 0;
  invalidateAll();
}
set3DTopView()
void SceneViewer::set3DTopView () protected
{
  m_phi3D   = 0;
  m_theta3D = 90;
  invalidateAll();
}
setActualPixelSize
void SceneViewer::setActualPixelSize () slot
{
  TApp *app           = TApp::instance();
  TXshLevel *l        = app->getCurrentLevel()->getLevel();
  TXshSimpleLevel *sl = l ? l->getSimpleLevel() : 0;
  if (!sl) return;
  TFrameId fid(app->getCurrentFrame()->getFid());
  TPointD dpi;
  if (CleanupPreviewCheck::instance()->isEnabled()) {
    // The previewed cleanup image has no image infos yet - retrieve the dpi
    // through
    // the cleanup camera data
    CleanupParameters *cleanupParams = app->getCurrentScene()
                                           ->getScene()
                                           ->getProperties()
                                           ->getCleanupParameters();
    TDimension dim(0, 0);
    cleanupParams->getOutputImageInfo(dim, dpi.x, dpi.y);
  } else
    dpi = sl->getDpi(fid);
  const double inch = Stage::inch;
  TAffine tempAff   = getNormalZoomScale();
  if (m_isFlippedX) tempAff = tempAff * TScale(-1, 1);
  if (m_isFlippedY) tempAff = tempAff * TScale(1, -1);
  TPointD tempScale = dpi;
  if (m_isFlippedX) tempScale.x = -tempScale.x;
  if (m_isFlippedY) tempScale.y = -tempScale.y;
  for (int i = 0; i < m_viewAff.size(); ++i)
    setViewMatrix(dpi == TPointD(0, 0)
                      ? tempAff
                      : TScale(tempScale.x / inch, tempScale.y / inch),
                  i);
  m_pos         = QPoint(0, 0);
  m_pan3D       = TPointD(0, 0);
  m_zoomScale3D = 0.1;
  m_theta3D     = 20;
  m_phi3D       = 30;
  emit onZoomChanged();
  invalidateAll();
}
setEditPreviewSubcamera()
void SceneViewer::setEditPreviewSubcamera (bool enabled) inline
{
    m_editPreviewSubCamera = enabled;
  }
setFocus() [1/2]
void SceneViewer::setFocus () inline override protected virtual
Implements TTool::Viewer.
{ QWidget::setFocus(); };
setFocus() [2/2]
void SceneViewer::setFocus (Qt::FocusReason reason) inline
{ QWidget::setFocus(reason); };
setIsLocator()
void SceneViewer::setIsLocator () inline
{ m_isLocator = true; }
setIsStyleShortcutSwitchable()
void SceneViewer::setIsStyleShortcutSwitchable () inline
{ m_isStyleShortcutSwitchable = true; }
setReferenceMode
void SceneViewer::setReferenceMode (int referenceMode) slot
{
  if (m_referenceMode == referenceMode) return;
  TApp *app = TApp::instance();
  if (app->getCurrentFrame()->isEditingLevel())
    app->getCurrentFrame()->setFrame(app->getCurrentFrame()->getFrame());
  if (m_freezedStatus != NO_FREEZED) {
    freeze(false);
    emit freezeStateChanged(false);
  }
  m_referenceMode = referenceMode;
  invalidateAll();
  emit onZoomChanged();
}
setRulers()
void SceneViewer::setRulers (Ruler * v, Ruler * h) inline
{
    m_vRuler = v;
    m_hRuler = h;
  }
setTimerAndTargetInstant()
void SceneViewer::setTimerAndTargetInstant (QElapsedTimer * timer, qint64 target) inline
{
    m_timer         = timer;
    m_targetInstant = target;
  }
setViewMatrix()
void SceneViewer::setViewMatrix (const TAffine & aff, int viewMode)
{
  m_viewAff[viewMode] = aff;
  // In case the previewer is on, request a delayed update
  if (m_previewMode != NO_PREVIEW) requestTimedRefresh();
}
setVisual()
void SceneViewer::setVisual (const ImagePainter::VisualSettings & settings)
{
  // m_visualSettings.m_blankColor = settings.m_blankColor;//for the blank
  // frames, I don't have to repaint the viewer are using updateGl!
  bool repaint     = m_visualSettings.needRepaint(settings);
  m_visualSettings = settings;
  m_visualSettings.m_sceneProperties =
      TApp::instance()->getCurrentScene()->getScene()->getProperties();
  if (repaint) GLInvalidateAll();
}
showEvent()
void SceneViewer::showEvent (QShowEvent *) override protected
{
  m_visualSettings.m_sceneProperties =
      TApp::instance()->getCurrentScene()->getScene()->getProperties();
  // Se il viewer e' show e il preview e' attivo aggiungo il listner al preview
  if (m_previewMode != NO_PREVIEW)
    Previewer::instance(m_previewMode == SUBCAMERA_PREVIEW)->addListener(this);
  TApp *app = TApp::instance();
  TSceneHandle *sceneHandle = app->getCurrentScene();
  bool ret = connect(sceneHandle, SIGNAL(sceneSwitched()), this,
                     SLOT(resetSceneViewer()));
  ret      = ret && connect(sceneHandle, SIGNAL(sceneChanged()), this,
                       SLOT(onSceneChanged()));
  ret = ret && connect(sceneHandle, SIGNAL(preferenceChanged(const QString &)),
                       this, SLOT(onPreferenceChanged(const QString &)));
  TFrameHandle *frameHandle = app->getCurrentFrame();
  ret = ret && connect(frameHandle, SIGNAL(frameSwitched()), this,
                       SLOT(onFrameSwitched()));
  TPaletteHandle *paletteHandle =
      app->getPaletteController()->getCurrentLevelPalette();
  ret = ret && connect(paletteHandle, SIGNAL(colorStyleChanged(bool)), this,
                       SLOT(update()));
  ret = ret && connect(app->getCurrentObject(), SIGNAL(objectSwitched()), this,
                       SLOT(onObjectSwitched()));
  ret = ret && connect(app->getCurrentObject(), SIGNAL(objectChanged(bool)),
                       this, SLOT(update()));
  ret =
      ret && connect(app->getCurrentOnionSkin(), SIGNAL(onionSkinMaskChanged()),
                     this, SLOT(onOnionSkinMaskChanged()));
  ret = ret && connect(app->getCurrentLevel(), SIGNAL(xshLevelChanged()), this,
                       SLOT(update()));
  ret = ret && connect(app->getCurrentLevel(), SIGNAL(xshCanvasSizeChanged()),
                       this, SLOT(update()));
  // when level is switched, update m_dpiScale in order to show white background
  // for Ink&Paint work properly
  ret = ret &&
        connect(app->getCurrentLevel(), SIGNAL(xshLevelSwitched(TXshLevel *)),
                this, SLOT(onLevelSwitched()));
  ret = ret && connect(app->getCurrentXsheet(), SIGNAL(xsheetChanged()), this,
                       SLOT(onXsheetChanged()));
  ret = ret && connect(app->getCurrentXsheet(), SIGNAL(xsheetSwitched()), this,
                       SLOT(update()));
  // update tooltip when tool options are changed
  ret = ret && connect(app->getCurrentTool(), SIGNAL(toolChanged()), this,
                       SLOT(onToolChanged()));
  ret = ret && connect(app->getCurrentTool(), SIGNAL(toolCursorTypeChanged()),
                       this, SLOT(onToolChanged()));
  ret = ret &&
        connect(app, SIGNAL(tabletLeft()), this, SLOT(resetTabletStatus()));
#if defined(x64)
  if (m_stopMotion) {
    ret = ret && connect(m_stopMotion, SIGNAL(newLiveViewImageReady()), this,
                         SLOT(onNewStopMotionImageReady()));
    ret = ret && connect(m_stopMotion, SIGNAL(liveViewStopped()), this,
                         SLOT(onStopMotionLiveViewStopped()));
  }
#endif
  assert(ret);
  if (m_hRuler && m_vRuler) {
    if (!viewRulerToggle.getStatus()) {
      m_hRuler->hide();
      m_vRuler->hide();
    } else {
      m_hRuler->show();
      m_vRuler->show();
    }
  }
  if (m_shownOnce == false) {
    fitToCamera();
    m_shownOnce = true;
  }
  TApp::instance()->setActiveViewer(this);
  onPreferenceChanged("ColorCalibration");
  update();
}
swapCompared
void SceneViewer::swapCompared () slot
{
  m_compareSettings.m_swapCompared = !m_compareSettings.m_swapCompared;
  update();
}
tabletEvent()
void SceneViewer::tabletEvent (QTabletEvent * e) override protected
{
  if (m_freezedStatus != NO_FREEZED) return;
  m_tabletEvent = true;
  m_pressure    = e->pressure();
  m_tabletMove  = false;
  // Management of the Eraser pointer
  ToolHandle *toolHandle = TApp::instance()->getCurrentTool();
  if (e->pointerType() == QTabletEvent::Eraser) {
    if (!m_eraserPointerOn) {
      if (toolHandle->getTool()->getName() != T_Eraser) {
        // Save the current tool
        m_backupTool = QString::fromStdString(toolHandle->getTool()->getName());
        // Switch to the Eraser tool
        toolHandle->setTool(T_Eraser);
        m_eraserPointerOn = true;
      }
    }
  } else {
    if (m_eraserPointerOn) {
      // Restore the previous tool
      toolHandle->setTool(m_backupTool);
      m_eraserPointerOn = false;
    }
  }
  switch (e->type()) {
  case QEvent::TabletPress: {
#ifdef MACOSX
    // In OSX tablet action may cause only tabletEvent, not followed by
    // mousePressEvent.
    // So call onPress here in order to enable processing.
    if (e->button() == Qt::LeftButton) m_tabletState = Touched;
    TMouseEvent mouseEvent;
    initToonzEvent(mouseEvent, e, height(), m_pressure, getDevPixRatio());
    onPress(mouseEvent);
    // create context menu on right click here
    if (e->button() == Qt::RightButton) {
      m_mouseButton = Qt::NoButton;
      onContextMenu(e->pos(), e->globalPos());
    }
#else
    // for Windows, use tabletEvent only for the left Button
    // (regular pen touch), because
    // the current Qt seems to fail to catch the Wacom's button binding properly
    // with QTabletEvent->button() when pressing middle or right button.
    // So, in such case set m_tabletEvent = FALSE and let the mousePressEvent to
    // work.
    if (e->button() == Qt::LeftButton) {
      // Process the 1st tabletPress encountered and ignore back-to-back
      // tabletPress events. Treat it as if it happened so a following
      // mousePressEvent gets ignored
      if (m_tabletState == Released || m_tabletState == None) {
        TMouseEvent mouseEvent;
        initToonzEvent(mouseEvent, e, height(), m_pressure, getDevPixRatio());
        m_tabletState = Touched;
        onPress(mouseEvent);
      } else if (m_tabletState == Touched) {
        m_tabletState = StartStroke;
      }
    } else
      m_tabletEvent = false;
#endif
#if defined(LINUX) || defined(FREEBSD)
    // for Linux, create context menu on right click here.
    // could possibly merge with OSX code above
    if (e->button() == Qt::RightButton) {
      m_mouseButton = Qt::NoButton;
      onContextMenu(e->pos(), e->globalPos());
    }
#endif
  } break;
  case QEvent::TabletRelease: {
#ifdef MACOSX
    if (m_tabletState == StartStroke || m_tabletState == OnStroke)
      m_tabletState = Released;
    TMouseEvent mouseEvent;
    initToonzEvent(mouseEvent, e, height(), m_pressure, getDevPixRatio());
    onRelease(mouseEvent);
    if (TApp::instance()->getCurrentTool()->isToolBusy())
      TApp::instance()->getCurrentTool()->setToolBusy(false);
#else
    if (m_tabletState == StartStroke || m_tabletState == OnStroke) {
      m_tabletState = Released;
      TMouseEvent mouseEvent;
      initToonzEvent(mouseEvent, e, height(), m_pressure, getDevPixRatio());
      onRelease(mouseEvent);
    } else
      m_tabletEvent = false;
#endif
  } break;
  case QEvent::TabletMove: {
#ifdef MACOSX
    // for now OSX seems to fail to call enter/leaveEvent properly while
    // the tablet is floating
    bool isHoveringInsideViewer =
        !rect().marginsRemoved(QMargins(5, 5, 5, 5)).contains(e->pos());
    // call the fake enter event
    if (isHoveringInsideViewer) onEnter();
#else
    // for Windowsm, use tabletEvent only for the left Button
    if (m_tabletState != StartStroke && m_tabletState != OnStroke) {
      m_tabletEvent = false;
      break;
    }
#endif
    QPointF curPos = e->posF() * getDevPixRatio();
#if defined(_WIN32) && QT_VERSION >= QT_VERSION_CHECK(5, 10, 0)
    // Use the application attribute Qt::AA_CompressTabletEvents instead of the
    // delay timer
    // 21/4/2021 High frequent tablet event caused slowness when deforming with
    // Raster Selection Tool. So I re-introduced the delay timer to make
    // necessary interval for it. Deformation will be processed at interval of
    // 20msec. (See RasterSelectionTool::leftButtonDrag())
    if (curPos != m_lastMousePos) {
      TMouseEvent mouseEvent;
      initToonzEvent(mouseEvent, e, height(), m_pressure, getDevPixRatio(),
                     m_isBusyOnTabletMove);
      if (!m_isBusyOnTabletMove) {
        m_isBusyOnTabletMove = true;
        QTimer::singleShot(20, this, SLOT(releaseBusyOnTabletMove()));
      }
#else
    // It seems that the tabletEvent is called more often than mouseMoveEvent.
    // So I fire the interval timer in order to limit the following process
    // to be called in 50fps in maximum.
    if (curPos != m_lastMousePos && !m_isBusyOnTabletMove) {
      m_isBusyOnTabletMove = true;
      TMouseEvent mouseEvent;
      initToonzEvent(mouseEvent, e, height(), m_pressure, getDevPixRatio());
      QTimer::singleShot(20, this, SLOT(releaseBusyOnTabletMove()));
#endif
      // cancel stroke to prevent drawing while floating
      // 23/1/2018 There is a case that the pressure becomes zero at the start
      // and the end of stroke. For such case, stroke should not be cancelled.
      // So, added a process to finish stroke here instead of cancelling.
      // This will be called only if the state is OnStroke so at the start
      // of the stroke this condition will be passed.
      if (m_tabletState == OnStroke && m_pressure == 0.0) {
        m_tabletState       = Released;
        mouseEvent.m_button = Qt::LeftButton;
        onRelease(mouseEvent);
      } else {
        m_tabletMove = true;
        onMove(mouseEvent);  // m_tabletState is set to OnStrole here
      }
    }
#ifdef MACOSX
    // call the fake leave event if the pen is hovering the viewer edge
    if (!isHoveringInsideViewer) onLeave();
#endif
  } break;
  default:
    break;
  }
  e->accept();
}
touchEvent()
void SceneViewer::touchEvent (QTouchEvent * e, int type) protected
{
  if (type == QEvent::TouchBegin) {
    if (m_tabletEvent) return;
    m_touchActive   = true;
    m_firstPanPoint = e->touchPoints().at(0).pos();
    m_undoPoint     = m_firstPanPoint;
    // obtain device type
    m_touchDevice = e->device()->type();
  } else if (m_touchActive) {
    // touchpads must have 2 finger panning for tools and navigation to be
    // functional
    // on other devices, 1 finger panning is preferred
    if ((e->touchPoints().count() == 2 &&
         m_touchDevice == QTouchDevice::TouchPad) ||
        (e->touchPoints().count() == 1 &&
         m_touchDevice == QTouchDevice::TouchScreen)) {
      QTouchEvent::TouchPoint panPoint = e->touchPoints().at(0);
      if (!m_panning) {
        QPointF deltaPoint = panPoint.pos() - m_firstPanPoint;
        // minimize accidental and jerky zooming/rotating during 2 finger
        // panning
        if ((deltaPoint.manhattanLength() > 100) && !m_zooming && !m_rotating) {
          m_panning = true;
        }
      }
      if (m_panning) {
        QPointF centerDelta = (panPoint.pos() * getDevPixRatio()) -
                              (panPoint.lastPos() * getDevPixRatio());
        panQt(centerDelta.toPoint());
      }
    } else if (e->touchPoints().count() == 3) {
      QPointF newPoint = e->touchPoints().at(0).pos();
      if (m_undoPoint.x() - newPoint.x() > 100) {
        CommandManager::instance()->execute("MI_Undo");
        m_undoPoint = newPoint;
      }
      if (m_undoPoint.x() - newPoint.x() < -100) {
        CommandManager::instance()->execute("MI_Redo");
        m_undoPoint = newPoint;
      }
    }
  }
  if (type == QEvent::TouchEnd || type == QEvent::TouchCancel) {
    m_touchActive = false;
    m_panning     = false;
  }
  e->accept();
}
wheelEvent()
void SceneViewer::wheelEvent (QWheelEvent * event) override protected
{
  if (m_freezedStatus != NO_FREEZED) return;
  int delta = 0;
  switch (event->source()) {
  case Qt::MouseEventNotSynthesized: {
    if (event->modifiers() & Qt::AltModifier)
      delta = event->angleDelta().x();
    else
      delta = event->angleDelta().y();
    break;
  }
  case Qt::MouseEventSynthesizedBySystem: {
    QPoint numPixels  = event->pixelDelta();
    QPoint numDegrees = event->angleDelta() / 8;
    if (!numPixels.isNull()) {
      delta = event->pixelDelta().y();
    } else if (!numDegrees.isNull()) {
      QPoint numSteps = numDegrees / 15;
      delta           = numSteps.y();
    }
    break;
  }
  default:  // Qt::MouseEventSynthesizedByQt,
            // Qt::MouseEventSynthesizedByApplication
  {
    std::cout << "not supported event: Qt::MouseEventSynthesizedByQt, "
                 "Qt::MouseEventSynthesizedByApplication"
              << std::endl;
    break;
  }
  }  // end switch
  if (abs(delta) > 0) {
    // scrub with mouse wheel
    if ((event->modifiers() & Qt::AltModifier) &&
        (event->modifiers() & Qt::ShiftModifier) &&
        (event->modifiers() & Qt::ControlModifier)) {
      if (delta < 0) {
        CommandManager::instance()->execute("MI_NextStep");
      } else if (delta > 0) {
        CommandManager::instance()->execute("MI_PrevStep");
      }
    } else if ((event->modifiers() & Qt::ControlModifier) &&
               (event->modifiers() & Qt::ShiftModifier)) {
      if (delta < 0) {
        CommandManager::instance()->execute("MI_NextFrame");
      } else if (delta > 0) {
        CommandManager::instance()->execute("MI_PrevFrame");
      }
    } else if ((event->modifiers() & Qt::ShiftModifier) &&
               (event->modifiers() & Qt::AltModifier)) {
      if (delta < 0) {
        CommandManager::instance()->execute("MI_NextDrawing");
      } else if (delta > 0) {
        CommandManager::instance()->execute("MI_PrevDrawing");
      }
    }
    // Mouse wheel zoom interfered with touchpad panning (touch enabled)
    // Now if touch is enabled, touchpads ignore the mouse wheel zoom
    else if ((m_gestureActive == true &&
              m_touchDevice == QTouchDevice::TouchScreen) ||
             m_gestureActive == false) {
      zoomQt(event->pos() * getDevPixRatio(), exp(0.001 * delta));
      m_panning = false;
    }
  }
  event->accept();
}
winToWorld() [1/2]
TPointD SceneViewer::winToWorld (const QPointF & pos) const
{
  // coordinate window (origine in alto a sinistra) -> coordinate colonna
  // (origine al centro dell'immagine)
  TPointD pp(pos.x() - (double)width() / 2.0,
             -pos.y() + (double)height() / 2.0);
  if (is3DView()) {
    TXsheet *xsh            = TApp::instance()->getCurrentXsheet()->getXsheet();
    TStageObjectId cameraId = xsh->getStageObjectTree()->getCurrentCameraId();
    double z                = xsh->getStageObject(cameraId)->getZ(
        TApp::instance()->getCurrentFrame()->getFrame());
    TPointD p(pp.x - m_pan3D.x, pp.y - m_pan3D.y);
    p               = p * (1 / m_zoomScale3D);
    double theta    = m_theta3D * M_PI_180;
    double phi      = m_phi3D * M_PI_180;
    double cs_phi   = cos(phi);
    double sn_phi   = sin(phi);
    double cs_theta = cos(theta);
    double sn_theta = sin(theta);
    TPointD a(cs_phi, sn_theta * sn_phi);   // proiezione di (1,0,0)
    TPointD b(0, cs_theta);                 // proiezione di (0,1,0)
    TPointD c(sn_phi, -sn_theta * cs_phi);  // proiezione di (0,0,1)
    TPointD aa = rotate90(a);
    TPointD bb = rotate90(b);
    double abb = a * bb;
    double baa = b * aa;
    if (fabs(abb) > 0.001 && fabs(baa) > 0.001) {
      p -= c * z;
      TPointD g((p * bb) / (a * bb), (p * aa) / (b * aa));
      return TAffine() * g;
    } else
      return TAffine() * TPointD(0, 0);
  }
  return getViewMatrix().inv() * pp;
}
winToWorld() [2/2]
TPointD SceneViewer::winToWorld (const TPointD & winPos) const override virtual
Implements TTool::Viewer.
{
  return winToWorld(QPointF(winPos.x, height() - winPos.y));
}
worldToPos()
TPointD SceneViewer::worldToPos (const TPointD & worldPos) const override virtual
return pos in pixel, bottom-left origin
Implements TTool::Viewer.
{
  TPointD p = getViewMatrix() * worldPos;
  return TPointD(width() / 2 + p.x, height() / 2 + p.y);
}
References getViewMatrix().
zoom()
void SceneViewer::zoom (const TPointD & center, double factor) override protected virtual
Implements TTool::Viewer.
{
  zoomQt(QPoint(center.x, height() - center.y), factor);
}
zoomIn
void SceneViewer::zoomIn () slot
{
  m_lastMousePos = rect().center();
  zoomQt(true, false);
}
zoomOut
void SceneViewer::zoomOut () slot
{
  m_lastMousePos = rect().center();
  zoomQt(false, false);
}
zoomQt() [1/2]
void SceneViewer::zoomQt (bool forward, bool reset)
{
  TPointD delta(m_lastMousePos.x() - width() / 2,
                -m_lastMousePos.y() + height() / 2);
  if (is3DView()) {
    if (reset || ((m_zoomScale3D < 500 || !forward) &&
                  (m_zoomScale3D > 0.01 || forward))) {
      double oldZoomScale = m_zoomScale3D;
      m_zoomScale3D =
          reset ? 1
                : ImageUtils::getQuantizedZoomFactor(m_zoomScale3D, forward);
      m_pan3D = -(m_zoomScale3D / oldZoomScale) * -m_pan3D;
    }
  } else {
    // a factor for getting pixel-based zoom ratio
    double dpiFactor = getDpiFactor();
    // when showing the viewer with full-screen mode,
    // add a zoom factor which can show image fitting with the screen size
    double zoomScaleFittingWithScreen = 0.0f;
    if (dpiFactor != 1.0) {
      // check if the viewer is in full screen mode
      ImageUtils::FullScreenWidget *fsWidget =
          dynamic_cast<ImageUtils::FullScreenWidget *>(parentWidget());
      if (fsWidget && (fsWidget->windowState() & Qt::WindowFullScreen) != 0)
        zoomScaleFittingWithScreen = getZoomScaleFittingWithScreen();
    }
    int i;
    for (i = 0; i < 2; i++) {
      TAffine &viewAff = m_viewAff[i];
      if (m_isFlippedX) viewAff = viewAff * TScale(-1, 1);
      if (m_isFlippedX) viewAff = viewAff * TScale(1, -1);
      double scale2 = std::abs(viewAff.det());
      if (m_isFlippedX) viewAff = viewAff * TScale(-1, 1);
      if (m_isFlippedX) viewAff = viewAff * TScale(1, -1);
      if (reset || ((scale2 < 100000 || !forward) &&
                    (scale2 > 0.001 * 0.05 || forward))) {
        double oldZoomScale = sqrt(scale2) * dpiFactor;
        double zoomScale =
            reset ? 1
                  : ImageUtils::getQuantizedZoomFactor(oldZoomScale, forward);
        // threshold value -0.001 is intended to absorb the error of calculation
        if ((oldZoomScale - zoomScaleFittingWithScreen) *
                (zoomScale - zoomScaleFittingWithScreen) <
            -0.001)
          zoomScale = zoomScaleFittingWithScreen;
        // zoom center = viewer center
        if (Preferences::instance()->getViewerZoomCenter())
          setViewMatrix(TScale(zoomScale / oldZoomScale) * viewAff, i);
        // zoom center = mouse pos
        else
          setViewMatrix(TTranslation(delta) * TScale(zoomScale / oldZoomScale) *
                            TTranslation(-delta) * viewAff,
                        i);
      }
    }
  }
  GLInvalidateAll();
  emit onZoomChanged();
}
zoomQt() [2/2]
void SceneViewer::zoomQt (const QPoint & center, double scaleFactor) protected
{
  if (factor == 1.0) return;
  TPointD delta(center.x() - width() / 2, -center.y() + height() / 2);
  double oldZoomScale = m_zoomScale3D;
  if (is3DView()) {
    if ((m_zoomScale3D < 500 || factor < 1) &&
        (m_zoomScale3D > 0.01 || factor > 1)) {
      m_zoomScale3D *= factor;
      m_pan3D = -(m_zoomScale3D / oldZoomScale) * (delta - m_pan3D) + delta;
    }
  } else {
    int i;
    for (i = 0; i < 2; i++) {
      TAffine &viewAff = m_viewAff[i];
      double scale2    = fabs(viewAff.det());
      if ((scale2 < 100000 || factor < 1) &&
          (scale2 > 0.001 * 0.05 || factor > 1)) {
        if (i == m_viewMode) {
          // viewAff = TTranslation(delta) * TScale(factor) *
          // TTranslation(-delta) * viewAff;
          setViewMatrix(TTranslation(delta) * TScale(factor) *
                            TTranslation(-delta) * viewAff,
                        i);
        } else {
          // viewAff = TScale(factor) * viewAff;
          setViewMatrix(TScale(factor) * viewAff, i);
        }
      }
    }
  }
  GLInvalidateAll();
  emit onZoomChanged();
}
Member Data Documentation
m_actualClipRect
TRect SceneViewer::m_actualClipRect protected
m_draw3DMode
bool SceneViewer::m_draw3DMode protected
m_drawCameraAff
TAffine SceneViewer::m_drawCameraAff protected
m_drawCameraTest
bool SceneViewer::m_drawCameraTest protected
m_drawEditingLevel
bool SceneViewer::m_drawEditingLevel protected
m_drawIsTableVisible
bool SceneViewer::m_drawIsTableVisible protected
m_drawTableAff
TAffine SceneViewer::m_drawTableAff protected
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/toonz/sceneviewer.h
E:/opentoonz/toonz/sources/toonz/sceneviewer.cpp
E:/opentoonz/toonz/sources/toonz/sceneviewerevents.cpp