opentoonz: StyleEditor Class Reference
StyleEditor Class Reference final
Public Member Functions
StyleEditor (PaletteController *, QWidget *parent=0)
void setPaletteHandle (TPaletteHandle *paletteHandle)
TPaletteHandle * getPaletteHandle () const
void setLevelHandle (TXshLevelHandle *levelHandle)
TPalette * getPalette ()
int getStyleIndex ()
void setRootPath (const TFilePath &rootPath)
void enableAutopaintToggle (bool enabled)
virtual void save (QSettings &settings) const override
virtual void load (QSettings &settings) override
void updateColorCalibration ()
virtual void save (QSettings &settings) const =0
virtual void load (QSettings &settings)=0
Protected Slots
void onStyleSwitched ()
void onStyleChanged (bool isDragging)
void onCleanupStyleChanged (bool isDragging)
void onOldStyleClicked ()
void onNewStyleClicked ()
void updateOrientationButton ()
void checkPaletteLock ()
void enableColorAutoApply (bool enabled)
void setColorSample (const TPixel32 &color)
void onColorChanged (const ColorModel &, bool isDragging)
void selectStyle (const TColorStyle &style)
void applyButtonClicked ()
void autoCheckChanged (bool value)
void setPage (int index)
void onColorParamChanged ()
void onParamStyleChanged (bool isDragging)
void onHexChanged ()
void onSpecialButtonToggled (bool on)
void onCustomButtonToggled (bool on)
void onVectorBrushButtonToggled (bool on)
void onSliderAppearanceSelected (QAction *)
void onPopupMenuAboutToShow ()
Protected Member Functions
bool setStyle (TColorStyle *currentStyle)
void setEditedStyleToStyle (const TColorStyle *style)
void setOldStyleToStyle (const TColorStyle *style)
int getColorParam () const
void enable (bool enabled, bool enabledOnlyFirstTab=false, bool enabledFirstAndLastTab=false)
void showEvent (QShowEvent *) override
void hideEvent (QHideEvent *) override
Detailed Description
Constructor & Destructor Documentation
StyleEditor()
StyleEditor::StyleEditor (PaletteController * paletteController, QWidget * parent = 0)
    : QWidget(parent)
    , m_paletteController(paletteController)
    , m_paletteHandle(paletteController->getCurrentPalette())
    , m_cleanupPaletteHandle(paletteController->getCurrentCleanupPalette())
    , m_toolBar(0)
    , m_enabled(false)
    , m_enabledOnlyFirstTab(false)
    , m_enabledFirstAndLastTab(false)
    , m_oldStyle(0)
    , m_parent(parent)
    , m_editedStyle(0) {
  setFocusPolicy(Qt::NoFocus);
  // TOGLIERE
  TFilePath libraryPath = ToonzFolder::getLibraryFolder();
  setRootPath(libraryPath);
  m_styleBar = new DVGui::TabBar(this);
  m_styleBar->setDrawBase(false);
  m_styleBar->setObjectName("StyleEditorTabBar");
  // This widget is used to set the background color of the tabBar
  // using the styleSheet.
  // It is also used to take 6px on the left before the tabBar
  // and to draw the two lines on the bottom size
  m_tabBarContainer        = new TabBarContainter(this);
  m_colorParameterSelector = new ColorParameterSelector(this);
  m_plainColorPage          = new PlainColorPage(0);
  m_textureStylePage        = new TextureStyleChooserPage(0);
  m_specialStylePage        = new SpecialStyleChooserPage(0);
  m_customStylePage         = new CustomStyleChooserPage(0);
  m_vectorBrushesStylePage  = new VectorBrushStyleChooserPage(0);
  m_mypaintBrushesStylePage = new MyPaintBrushStyleChooserPage(0);
  m_settingsPage            = new SettingsPage(0);
  QWidget *emptyPage = new StyleEditorPage(0);
  // For the plainColorPage and the settingsPage
  // I create a "fake" QScrollArea (without ScrollingBar
  // in order to use the styleSheet to stylish its background
  QScrollArea *plainArea   = makeChooserPageWithoutScrollBar(m_plainColorPage);
  QScrollArea *textureArea = makeChooserPage(m_textureStylePage);
  QScrollArea *mypaintBrushesArea = makeChooserPage(m_mypaintBrushesStylePage);
  QScrollArea *settingsArea = makeChooserPageWithoutScrollBar(m_settingsPage);
  QScrollArea *vectorOutsideArea =
      makeChooserPageWithoutScrollBar(createVectorPage());
  vectorOutsideArea->setMinimumWidth(50);
  m_styleChooser = new QStackedWidget(this);
  m_styleChooser->addWidget(plainArea);
  m_styleChooser->addWidget(textureArea);
  m_styleChooser->addWidget(vectorOutsideArea);
  m_styleChooser->addWidget(mypaintBrushesArea);
  m_styleChooser->addWidget(settingsArea);
  m_styleChooser->addWidget(makeChooserPageWithoutScrollBar(emptyPage));
  m_styleChooser->setFocusPolicy(Qt::NoFocus);
  QFrame *bottomWidget = createBottomWidget();
  /* ------- layout ------- */
  QGridLayout *mainLayout = new QGridLayout;
  mainLayout->setMargin(0);
  mainLayout->setSpacing(0);
  {
    QHBoxLayout *hLayout = new QHBoxLayout;
    hLayout->setMargin(0);
    {
      hLayout->addSpacing(0);
      hLayout->addWidget(m_styleBar);
      hLayout->addStretch();
    }
    m_tabBarContainer->setLayout(hLayout);
    mainLayout->addWidget(m_tabBarContainer, 0, 0, 1, 2);
    mainLayout->addWidget(m_styleChooser, 1, 0, 1, 2);
    mainLayout->addWidget(bottomWidget, 2, 0, 1, 2);
    // mainLayout->addWidget(m_toolBar, 3, 0);
    // mainLayout->addWidget(displayToolbar, 3, 1);
  }
  mainLayout->setColumnStretch(0, 1);
  mainLayout->setRowStretch(1, 1);
  setLayout(mainLayout);
  /* ------- signal-slot connections ------- */
  bool ret = true;
  ret      = ret && connect(m_styleBar, SIGNAL(currentChanged(int)), this,
                       SLOT(setPage(int)));
  ret = ret && connect(m_colorParameterSelector, SIGNAL(colorParamChanged()),
                       this, SLOT(onColorParamChanged()));
  ret = ret &&
        connect(m_textureStylePage, SIGNAL(styleSelected(const TColorStyle &)),
                this, SLOT(selectStyle(const TColorStyle &)));
  ret = ret &&
        connect(m_specialStylePage, SIGNAL(styleSelected(const TColorStyle &)),
                this, SLOT(selectStyle(const TColorStyle &)));
  ret = ret &&
        connect(m_customStylePage, SIGNAL(styleSelected(const TColorStyle &)),
                this, SLOT(selectStyle(const TColorStyle &)));
  ret = ret && connect(m_vectorBrushesStylePage,
                       SIGNAL(styleSelected(const TColorStyle &)), this,
                       SLOT(selectStyle(const TColorStyle &)));
  ret = ret && connect(m_mypaintBrushesStylePage,
                       SIGNAL(styleSelected(const TColorStyle &)), this,
                       SLOT(selectStyle(const TColorStyle &)));
  ret = ret && connect(m_settingsPage, SIGNAL(paramStyleChanged(bool)), this,
                       SLOT(onParamStyleChanged(bool)));
  ret = ret && connect(m_plainColorPage,
                       SIGNAL(colorChanged(const ColorModel &, bool)), this,
                       SLOT(onColorChanged(const ColorModel &, bool)));
  assert(ret);
  /* ------- initial conditions ------- */
  enable(false, false, false);
  // set to the empty page
  m_styleChooser->setCurrentIndex(m_styleChooser->count() - 1);
}
~StyleEditor()
StyleEditor::~StyleEditor ()
{}
Member Function Documentation
applyButtonClicked
void StyleEditor::applyButtonClicked () protected slot
{
  TPalette *palette = getPalette();
  int styleIndex    = getStyleIndex();
  if (!palette || styleIndex < 0 || styleIndex > palette->getStyleCount())
    return;
  copyEditedStyleToPalette(false);
}
autoCheckChanged
void StyleEditor::autoCheckChanged (bool value) protected slot
{
  m_paletteController->enableColorAutoApply(value);
  if (!m_enabled) return;
  m_applyButton->setDisabled(value);
}
checkPaletteLock
void StyleEditor::checkPaletteLock () protected slot
{
  if (getPalette() && getPalette()->isLocked()) {
    m_applyButton->setEnabled(false);
    m_autoButton->setEnabled(false);
  } else {
    m_applyButton->setDisabled(m_autoButton->isChecked());
    m_autoButton->setEnabled(true);
  }
}
enable()
void StyleEditor::enable (bool enabled, bool enabledOnlyFirstTab = false, bool enabledFirstAndLastTab = false) protected
Set StyleEditor view to enabled. If enabledOnlyFirstTab or if enabledFirstAndLastTab is true hide other tab, pay attention enabled must be true or StyleEditor is disabled.
{
  if (m_enabled != enabled || m_enabledOnlyFirstTab != enabledOnlyFirstTab ||
      m_enabledFirstAndLastTab != enabledFirstAndLastTab) {
    m_enabled                = enabled;
    m_enabledOnlyFirstTab    = enabledOnlyFirstTab;
    m_enabledFirstAndLastTab = enabledFirstAndLastTab;
    updateTabBar();
    m_autoButton->setEnabled(enabled);
    m_applyButton->setDisabled(!enabled || m_autoButton->isChecked());
    m_oldColor->setEnable(enabled);
    m_newColor->setEnable(enabled);
    m_hexLineEdit->setEnabled(enabled);
    if (enabled == false) {
      m_oldColor->setColor(TPixel32::Transparent);
      m_newColor->setColor(TPixel32::Transparent);
    }
  }
  // lock button behavior
  TPalette *palette = getPalette();
  if (palette && enabled) {
    // when the palette is locked
    if (palette->isLocked()) {
      m_applyButton->setEnabled(false);
      m_autoButton->setEnabled(false);
    } else  // when the palette is unlocked
    {
      m_applyButton->setDisabled(m_autoButton->isChecked());
      m_autoButton->setEnabled(true);
    }
  }
}
enableAutopaintToggle()
void StyleEditor::enableAutopaintToggle (bool enabled) inline
{
    m_settingsPage->enableAutopaintToggle(enabled);
  }
enableColorAutoApply
void StyleEditor::enableColorAutoApply (bool enabled) protected slot
{
  if (m_autoButton->isChecked() != enabled) {
    m_autoButton->setChecked(enabled);
  }
}
getColorParam()
int StyleEditor::getColorParam () const inline protected
that as the previously current one.
Todo:
Why is this not assimilated to setCurrentStyleToStyle()?
Return style parameter index selected in ColorParameterSelector.
{ return m_colorParameterSelector->getSelected(); }
Referenced by setStyle().
getPalette()
TPalette * StyleEditor::getPalette () inline
{ return m_paletteHandle->getPalette(); }
getPaletteHandle()
TPaletteHandle * StyleEditor::getPaletteHandle () const inline
{ return m_paletteHandle; }
getStyleIndex()
int StyleEditor::getStyleIndex () inline
{ return m_paletteHandle->getStyleIndex(); }
hideEvent()
void StyleEditor::hideEvent (QHideEvent *) override protected
{
  disconnect(m_paletteHandle, 0, this, 0);
  if (m_cleanupPaletteHandle) disconnect(m_cleanupPaletteHandle, 0, this, 0);
  disconnect(m_paletteController, 0, this, 0);
}
load()
void StyleEditor::load (QSettings & settings) override virtual
Implements SaveLoadQSettings.
{
  QVariant isVertical = settings.value("isVertical");
  if (isVertical.canConvert(QVariant::Bool)) {
    m_colorPageIsVertical = isVertical.toBool();
    m_plainColorPage->setIsVertical(m_colorPageIsVertical);
  }
  QVariant visibleParts = settings.value("visibleParts");
  if (visibleParts.canConvert(QVariant::Int)) {
    int visiblePartsInt = visibleParts.toInt();
    if (visiblePartsInt & 0x01)
      m_wheelAction->setChecked(true);
    else
      m_wheelAction->setChecked(false);
    if (visiblePartsInt & 0x02)
      m_hsvAction->setChecked(true);
    else
      m_hsvAction->setChecked(false);
    if (visiblePartsInt & 0x04)
      m_alphaAction->setChecked(true);
    else
      m_alphaAction->setChecked(false);
    if (visiblePartsInt & 0x08)
      m_rgbAction->setChecked(true);
    else
      m_rgbAction->setChecked(false);
    if (visiblePartsInt & 0x10)
      m_hexAction->setChecked(true);
    else
      m_hexAction->setChecked(false);
  }
  QVariant splitterState = settings.value("splitterState");
  if (splitterState.canConvert(QVariant::ByteArray))
    m_plainColorPage->setSplitterState(splitterState.toByteArray());
}
onCleanupStyleChanged
void StyleEditor::onCleanupStyleChanged (bool isDragging) protected slot
{
  if (!m_cleanupPaletteHandle) return;
  onStyleChanged(isDragging);
}
onColorChanged
void StyleEditor::onColorChanged (const ColorModel & color, bool isDragging) protected slot
{
  TPalette *palette = getPalette();
  if (!palette) return;
  int styleIndex = getStyleIndex();
  if (styleIndex < 0 || styleIndex > palette->getStyleCount()) return;
  setEditedStyleToStyle(palette->getStyle(styleIndex));  // CLONES the argument
  if (m_editedStyle)  // Should be styleIndex's style at this point
  {
    TPixel tColor = color.getTPixel();
    if (m_editedStyle->hasMainColor()) {
      int index = getColorParam(), count = m_editedStyle->getColorParamCount();
      if (0 <= index && index < count)
        m_editedStyle->setColorParamValue(index, tColor);
      else
        m_editedStyle->setMainColor(tColor);
      m_editedStyle->invalidateIcon();
    } else {
      // The argument has NO (main) COLOR. Since color data is being updated, a
      // 'fake'
      // solid style will be created and operated on.
      TSolidColorStyle *style = new TSolidColorStyle(tColor);
      style->assignNames(m_editedStyle.getPointer());
      setEditedStyleToStyle(style);  // CLONES the argument
      delete style;
    }
    m_newColor->setStyle(*m_editedStyle, getColorParam());
    m_colorParameterSelector->setStyle(*m_editedStyle);
    m_hexLineEdit->setStyle(*m_editedStyle, getColorParam());
    // Auto Button should be disabled with locked palette
    if (m_autoButton->isEnabled() && m_autoButton->isChecked()) {
      copyEditedStyleToPalette(isDragging);
    }
  }
}
onColorParamChanged
void StyleEditor::onColorParamChanged () protected slot
{
  TPalette *palette = getPalette();
  if (!palette) return;
  int styleIndex = getStyleIndex();
  if (styleIndex < 0 || palette->getStyleCount() <= styleIndex) return;
  if (*m_oldStyle != *m_editedStyle) applyButtonClicked();
  m_paletteHandle->setStyleParamIndex(getColorParam());
  if (TColorStyle *currentStyle = palette->getStyle(styleIndex)) {
    setEditedStyleToStyle(currentStyle);
    m_colorParameterSelector->setStyle(*m_editedStyle);
    m_newColor->setStyle(*m_editedStyle, getColorParam());
    m_oldColor->setStyle(*m_editedStyle, getColorParam());
    m_plainColorPage->setColor(*m_editedStyle, getColorParam());
    m_settingsPage->setStyle(m_editedStyle);
    m_hexLineEdit->setStyle(*m_editedStyle, getColorParam());
  }
}
onCustomButtonToggled
void StyleEditor::onCustomButtonToggled (bool on) protected slot
{
  m_customStylePage->setVisible(on);
  m_vectorArea->widget()->resize(m_vectorArea->widget()->sizeHint());
  qApp->processEvents();
}
onHexChanged
void StyleEditor::onHexChanged () protected slot
{
  if (m_hexLineEdit->fromText(m_hexLineEdit->text())) {
    ColorModel cm;
    cm.setTPixel(m_hexLineEdit->getColor());
    onColorChanged(cm, false);
    m_hexLineEdit->selectAll();
  }
}
onNewStyleClicked
void StyleEditor::onNewStyleClicked () protected slot
{ applyButtonClicked(); }
onOldStyleClicked
void StyleEditor::onOldStyleClicked () protected slot
{
  if (!m_enabled) return;
  selectStyle(*(m_oldColor->getStyle()));
}
onParamStyleChanged
void StyleEditor::onParamStyleChanged (bool isDragging) protected slot
{
  TPalette *palette = getPalette();
  if (!palette) return;
  int styleIndex = getStyleIndex();
  if (styleIndex < 0 || styleIndex > palette->getStyleCount()) return;
  if (m_autoButton->isChecked()) copyEditedStyleToPalette(isDragging);
  m_editedStyle->invalidateIcon();  // Refresh the new color icon
  m_newColor->setStyle(*m_editedStyle, getColorParam());
  m_hexLineEdit->setStyle(*m_editedStyle, getColorParam());
}
onPopupMenuAboutToShow
void StyleEditor::onPopupMenuAboutToShow () protected slot
{
  // sync radio button state to the current user env settings
  for (auto action : m_sliderAppearanceAG->actions()) {
    bool ok          = true;
    int appearanceId = action->data().toInt(&ok);
    if (ok && appearanceId == StyleEditorColorSliderAppearance)
      action->setChecked(true);
  }
}
onSliderAppearanceSelected
void StyleEditor::onSliderAppearanceSelected (QAction * action) protected slot
{
  bool ok          = true;
  int appearanceId = action->data().toInt(&ok);
  if (!ok) return;
  if (appearanceId == StyleEditorColorSliderAppearance) return;
  StyleEditorColorSliderAppearance = appearanceId;
  ColorSlider::s_slider_appearance = appearanceId;
  m_plainColorPage->update();
}
onSpecialButtonToggled
void StyleEditor::onSpecialButtonToggled (bool on) protected slot
{
  m_specialStylePage->setVisible(on);
  m_vectorArea->widget()->resize(m_vectorArea->widget()->sizeHint());
  qApp->processEvents();
}
onStyleChanged
void StyleEditor::onStyleChanged (bool isDragging) protected slot
{
  TPalette *palette = getPalette();
  if (!palette) return;
  int styleIndex = getStyleIndex();
  assert(0 <= styleIndex && styleIndex < palette->getStyleCount());
  setEditedStyleToStyle(palette->getStyle(styleIndex));
  if (!isDragging) {
    setOldStyleToStyle(
        m_editedStyle
            .getPointer());  // This line is needed for proper undo behavior
  }
  m_plainColorPage->setColor(*m_editedStyle, getColorParam());
  m_colorParameterSelector->setStyle(*m_editedStyle);
  m_settingsPage->setStyle(m_editedStyle);
  m_newColor->setStyle(*m_editedStyle, getColorParam());
  m_oldColor->setStyle(
      *m_oldStyle,
      getColorParam());  // This line is needed for proper undo behavior
  m_hexLineEdit->setStyle(*m_editedStyle, getColorParam());
}
onStyleSwitched
void StyleEditor::onStyleSwitched () protected slot
{
  TPalette *palette = getPalette();
  if (!palette) {
    // set the current page to empty
    m_styleChooser->setCurrentIndex(m_styleChooser->count() - 1);
    enable(false);
    m_colorParameterSelector->clear();
    m_oldStyle    = TColorStyleP();
    m_editedStyle = TColorStyleP();
    m_parent->setWindowTitle(tr("No Style Selected"));
    return;
  }
  int styleIndex = getStyleIndex();
  setEditedStyleToStyle(palette->getStyle(styleIndex));
  bool isStyleNull    = setStyle(m_editedStyle.getPointer());
  bool isColorInField = palette->getPaletteName() == L"EmptyColorFieldPalette";
  bool isValidIndex   = styleIndex > 0 || isColorInField;
  bool isCleanUpPalette = palette->isCleanupPalette();
  /* ------ update the status text ------ */
  if (!isStyleNull && isValidIndex) {
    QString statusText;
    // palette type
    if (isCleanUpPalette)
      statusText = tr("Cleanup ");
    else if (palette->getGlobalName() != L"")
      statusText = tr("Studio ");
    else
      statusText = tr("Level ");
    // palette name
    statusText += tr("Palette") + " : " +
                  QString::fromStdWString(palette->getPaletteName());
    // style name
    statusText += QString::fromStdWString(L" | #");
    statusText += QString::number(styleIndex);
    statusText += QString::fromStdWString(L" : " + m_editedStyle->getName());
    TPoint pickedPos = m_editedStyle->getPickedPosition().pos;
    if (pickedPos != TPoint())
      statusText +=
          QString(" (Picked from %1,%2)").arg(pickedPos.x).arg(pickedPos.y);
    m_parent->setWindowTitle(statusText);
  } else {
    m_parent->setWindowTitle(tr("Style Editor - No Valid Style Selected"));
  }
  enable(!isStyleNull && isValidIndex, isColorInField, isCleanUpPalette);
}
onVectorBrushButtonToggled
void StyleEditor::onVectorBrushButtonToggled (bool on) protected slot
{
  m_vectorBrushesStylePage->setVisible(on);
  m_vectorArea->widget()->resize(m_vectorArea->widget()->sizeHint());
  qApp->processEvents();
}
save()
void StyleEditor::save (QSettings & settings) const override virtual
Implements SaveLoadQSettings.
{
  settings.setValue("isVertical", m_plainColorPage->getIsVertical());
  int visibleParts = 0;
  if (m_wheelAction->isChecked()) visibleParts |= 0x01;
  if (m_hsvAction->isChecked()) visibleParts |= 0x02;
  if (m_alphaAction->isChecked()) visibleParts |= 0x04;
  if (m_rgbAction->isChecked()) visibleParts |= 0x08;
  if (m_hexAction->isChecked()) visibleParts |= 0x10;
  settings.setValue("visibleParts", visibleParts);
  settings.setValue("splitterState", m_plainColorPage->getSplitterState());
}
selectStyle
void StyleEditor::selectStyle (const TColorStyle & style) protected slot
{
  TPalette *palette = m_paletteHandle->getPalette();
  if (!palette) return;
  int styleIndex = m_paletteHandle->getStyleIndex();
  if (styleIndex < 0 || palette->getStyleCount() <= styleIndex) return;
  // Register the new previous/edited style pairs
  setOldStyleToStyle(palette->getStyle(styleIndex));
  setEditedStyleToStyle(&newStyle);
  m_editedStyle->assignNames(
      m_oldStyle.getPointer());  // Copy original name stored in the palette
  // For convenience's sake, copy the main color from the old color, if both
  // have one
  if (m_oldStyle && m_oldStyle->hasMainColor() && m_editedStyle &&
      m_editedStyle->hasMainColor())
    m_editedStyle->setMainColor(m_oldStyle->getMainColor());
  if (m_autoButton->isChecked()) {
    // If the adited style is linked to the studio palette, then activate the
    // edited flag
    if (m_editedStyle->getGlobalName() != L"" &&
        m_editedStyle->getOriginalName() != L"")
      m_editedStyle->setIsEditedFlag(true);
    // Apply new style, if required
    TUndoManager::manager()->add(new UndoPaletteChange(
        m_paletteHandle, styleIndex, *m_oldStyle, *m_editedStyle));
    palette->setStyle(styleIndex, m_editedStyle->clone());
    m_paletteHandle->notifyColorStyleChanged(false);
    palette->setDirtyFlag(true);
  }
  // Update editor widgets
  m_colorParameterSelector->setStyle(*m_editedStyle);
  m_newColor->setStyle(*m_editedStyle, getColorParam());
  m_plainColorPage->setColor(*m_editedStyle, getColorParam());
  m_settingsPage->setStyle(m_editedStyle);
  m_hexLineEdit->setStyle(*m_editedStyle, getColorParam());
}
setColorSample
void StyleEditor::setColorSample (const TPixel32 & color) protected slot
{
  // m_colorParameterSelector->setColor(*style);
  ColorModel cm;
  cm.setTPixel(color);
  onColorChanged(cm, true);
}
setEditedStyleToStyle()
void StyleEditor::setEditedStyleToStyle (const TColorStyle * style) protected
Clones the supplied style and
{
  if (style == m_editedStyle.getPointer()) return;
  m_editedStyle = TColorStyleP(style->clone());
}
References TColorStyle::clone().
setLevelHandle()
void StyleEditor::setLevelHandle (TXshLevelHandle * levelHandle) inline
{
    m_levelHandle = levelHandle;
  }
setOldStyleToStyle()
void StyleEditor::setOldStyleToStyle (const TColorStyle * style) protected
considers that as the edited one. Clones the supplied style and considers
{
  if (style == m_oldStyle.getPointer()) return;
  m_oldStyle = TColorStyleP(style->clone());
}
References TColorStyle::clone().
Referenced by setStyle().
setPage
void StyleEditor::setPage (int index) protected slot
{
  if (!m_enabledFirstAndLastTab) {
    m_styleChooser->setCurrentIndex(index);
    return;
  }
  // Se sono nel caso first and last page enable e index == 1 la pagina che
  // voglio settare e' l'ultima!
  if (index == 1)
    index = m_styleChooser->count() -
            2;  // 2 perche' alla fine c'e' una pagina vuota
  m_styleChooser->setCurrentIndex(index);
}
setRootPath()
void StyleEditor::setRootPath (const TFilePath & rootPath)
rootPath generally is STUFFDIR/Library. Contains directories 'textures' and 'custom styles'
{
  m_textureStylePage->setRootPath(rootPath);
}
References StyleEditorGUI::StyleChooserPage::setRootPath().
setStyle()
bool StyleEditor::setStyle (TColorStyle * currentStyle) protected
Return false if style is linked and style must be set to null.
{
  assert(currentStyle);
  bool isStyleNull = false;
  QString gname = QString::fromStdWString(currentStyle->getGlobalName());
  // if(!gname.isEmpty() && gname == "ColorFieldSimpleColor")
  //    isStyleNull = true;
  // else
  if (!gname.isEmpty() && gname[0] != L'-') {
    currentStyle = 0;
    isStyleNull  = true;
  }
  if (currentStyle) {
    m_colorParameterSelector->setStyle(*currentStyle);
    m_plainColorPage->setColor(*currentStyle, getColorParam());
    m_oldColor->setStyle(*currentStyle, getColorParam());
    m_newColor->setStyle(*currentStyle, getColorParam());
    m_hexLineEdit->setStyle(*m_editedStyle, getColorParam());
    setOldStyleToStyle(currentStyle);
  }
  // Va fatto anche se non c'e' lo style perche' svuota la pagina
  m_settingsPage->setStyle(m_editedStyle);
  return isStyleNull;
}
References getColorParam(), TColorStyle::getGlobalName(), and setOldStyleToStyle().
showEvent()
void StyleEditor::showEvent (QShowEvent *) override protected
{
  m_autoButton->setChecked(m_paletteController->isColorAutoApplyEnabled());
  onStyleSwitched();
  bool ret = true;
  ret      = ret && connect(m_paletteHandle, SIGNAL(colorStyleSwitched()),
                       SLOT(onStyleSwitched()));
  ret      = ret && connect(m_paletteHandle, SIGNAL(colorStyleChanged(bool)),
                       SLOT(onStyleChanged(bool)));
  ret      = ret && connect(m_paletteHandle, SIGNAL(paletteSwitched()), this,
                       SLOT(onStyleSwitched()));
  ret = ret && connect(m_paletteController, SIGNAL(checkPaletteLock()), this,
                       SLOT(checkPaletteLock()));
  if (m_cleanupPaletteHandle)
    ret =
        ret && connect(m_cleanupPaletteHandle, SIGNAL(colorStyleChanged(bool)),
                       SLOT(onCleanupStyleChanged(bool)));
  ret = ret && connect(m_paletteController, SIGNAL(colorAutoApplyEnabled(bool)),
                       this, SLOT(enableColorAutoApply(bool)));
  ret = ret && connect(m_paletteController,
                       SIGNAL(colorSampleChanged(const TPixel32 &)), this,
                       SLOT(setColorSample(const TPixel32 &)));
  m_plainColorPage->m_wheelFrame->setVisible(m_wheelAction->isChecked());
  m_plainColorPage->m_hsvFrame->setVisible(m_hsvAction->isChecked());
  m_plainColorPage->m_alphaFrame->setVisible(m_alphaAction->isChecked());
  m_plainColorPage->m_rgbFrame->setVisible(m_rgbAction->isChecked());
  m_hexLineEdit->setVisible(m_hexAction->isChecked());
  updateOrientationButton();
  assert(ret);
}
updateColorCalibration()
void StyleEditor::updateColorCalibration ()
{
  m_plainColorPage->updateColorCalibration();
}
updateOrientationButton
void StyleEditor::updateOrientationButton () protected slot
{
  if (m_plainColorPage->getIsVertical()) {
    m_toggleOrientationAction->setIcon(createQIcon("orientation_h"));
  } else {
    m_toggleOrientationAction->setIcon(createQIcon("orientation_v"));
  }
}
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/toonzqt/styleeditor.h
E:/opentoonz/toonz/sources/toonzqt/styleeditor.cpp