opentoonz: Skeleton Class Reference
Skeleton Class Reference
The Skeleton is the data structure used by the Skeleton Tool.
#include <skeleton.h>
Classes
class Bone
Public Member Functions
void build (TXsheet *xsh, int row, int col, const std::set< int > &tempPinnedColumns=std::set< int >())
void clear ()
reset the skeleton
int getBoneCount () const
Bone * getBone (int index) const
Bone * getBoneByColumnIndex (int columnIndex) const
Bone * getRootBone () const
the root is the ancestor of each bone in the skeleton
bool isIKEnabled () const
bool hasPinnedRanges () const
Some bone has a not empty pinned range.
void clearAllPinnedRanges ()
Detailed Description
The Skeleton is the data structure used by the Skeleton Tool.
Constructor & Destructor Documentation
Skeleton()
Skeleton::Skeleton ()
: m_rootBone(0) {}
~Skeleton()
Skeleton::~Skeleton ()
{ clearPointerContainer(m_bones); }
Member Function Documentation
build()
void Skeleton::build (TXsheet * xsh, int row, int col, const std::set< int > & tempPinnedColumns = std::set<int>())
create a skeleton containing 'col'. tempPinnedColumns contains the column indices of the temporarily pinned bones
{
  // clear
  m_rootBone = 0;
  clearPointerContainer(m_bones);
  // antenato (colonna) della colonna corrente
  TStageObjectId ancestorId = getAncestor(xsh, TStageObjectId::ColumnId(col));
  // costruisco le "ossa"
  std::map<TStageObjectId, Bone *> boneTable;
  int columnCount = xsh->getColumnCount();
  int pinnedCount = 0;
  for (int i = 0; i < columnCount; i++) {
    TStageObjectId columnId(TStageObjectId::ColumnId(i));
    if (getAncestor(xsh, columnId) != ancestorId) continue;
    TAffine aff         = xsh->getPlacement(columnId, row);
    TPointD center      = Stage::inch * xsh->getCenter(columnId, row);
    TPointD p           = aff * center;
    TStageObject *obj   = xsh->getStageObject(columnId);
    Bone *bone          = new Bone(obj, p);
    boneTable[columnId] = bone;
    m_bones.push_back(bone);
    if (columnId == ancestorId) m_rootBone = bone;
    if (obj->getPinnedRangeSet()->isPinned(row)) {
      pinnedCount++;
      bone->setPinnedStatus(Bone::PINNED);
    } else if (tempPinnedColumns.count(i) > 0)
      bone->setPinnedStatus(Bone::TEMP_PINNED);
  }
  // if no bone is pinned then the root is considered pinned
  if (pinnedCount == 0 && m_rootBone) m_rootBone->setPinnedStatus(Bone::PINNED);
  // The skeleton could possibly be empty
  if (boneTable.empty()) {
    assert(!m_rootBone);
    return;
  }
  // assign parents
  std::map<TStageObjectId, Bone *>::iterator it, sit;
  for (it = boneTable.begin(); it != boneTable.end(); ++it) {
    sit = boneTable.find(xsh->getStageObjectParent(it->first));
    if (sit != boneTable.end()) it->second->setParent(sit->second);
  }
  // select the "active chain", i.e. the starting bone (columnIndex=col) and the
  // ancestors
  it = boneTable.find(TStageObjectId::ColumnId(col));
  if (it != boneTable.end()) {
    Bone *bone = it->second;
    while (bone) {
      bone->select();
      bone = bone->getParent();
    }
  }
}
References TXsheet::getCenter(), TXsheet::getColumnCount(), TXsheet::getPlacement(), TXsheet::getStageObject(), TXsheet::getStageObjectParent(), and Stage::inch.
clear()
void Skeleton::clear ()
reset the skeleton
                     {
  clearPointerContainer(m_bones);
  m_rootBone = 0;
}
clearAllPinnedRanges()
void Skeleton::clearAllPinnedRanges ()
{
  for (int i = 0; i < getBoneCount(); i++) {
    TStageObject *obj = getBone(i)->getStageObject();
    obj->getPinnedRangeSet()->removeAllRanges();
    obj->invalidate();
  }
}
getBone()
Skeleton::Bone * Skeleton::getBone (int index) const
{
  assert(0 <= index && index < (int)m_bones.size());
  return m_bones[index];
}
getBoneByColumnIndex()
Skeleton::Bone * Skeleton::getBoneByColumnIndex (int columnIndex) const
{
  for (int i = 0; i < (int)m_bones.size(); i++)
    if (m_bones[i]->getColumnIndex() == columnIndex) return m_bones[i];
  return 0;
}
getBoneCount()
int Skeleton::getBoneCount () const inline
{ return m_bones.size(); }
getRootBone()
Bone * Skeleton::getRootBone () const inline
the root is the ancestor of each bone in the skeleton
{ return m_rootBone; }
hasPinnedRanges()
bool Skeleton::hasPinnedRanges () const
Some bone has a not empty pinned range.
{
  for (int i = 0; i < getBoneCount(); i++) {
    TStageObject *obj = getBone(i)->getStageObject();
    if (obj->getPinnedRangeSet()->getRangeCount() > 0) return true;
  }
  return false;
}
isIKEnabled()
bool Skeleton::isIKEnabled () const
helper functions. see TPinnedRangeSet the root status is TStageObject::IK
{
  return m_rootBone &&
         m_rootBone->getStageObject()->getStatus() == TStageObject::IK;
}
References TStageObject::getStatus(), and TStageObject::IK.
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/toonz/skeleton.h
E:/opentoonz/toonz/sources/toonzlib/skeleton.cpp