opentoonz: TVectorBrushStyle Class Reference
TVectorBrushStyle Class Reference final
Public Member Functions
TVectorBrushStyle (const std::string &brushName, TVectorImageP vi=TVectorImageP())
TColorStyle * clone () const override
Polymorphic clone of the style.
QString getDescription () const override
Return a brief description of the style.
void loadBrush (const std::string &brushName)
int getTagId () const override
Returns an unique number representing the style.
TVectorImageP getImage () const
bool isRegionStyle () const override
Returns whether the style applies on regions.
bool isStrokeStyle () const override
Returns whether the style applies on strokes.
TStrokeProp * makeStrokeProp (const TStroke *stroke) override
TRegionProp * makeRegionProp (const TRegion *region) override
used to draw the style on the specified stroke object.
bool hasMainColor () const override
Returns whether the style has a reference main color.
TPixel32 getMainColor () const override
Returns the style's main color, or black if none.
void setMainColor (const TPixel32 &color) override
Sets the main color, if it has one.
int getColorParamCount () const override
Returns the number of colors (if any) of the style.
TPixel32 getColorParamValue (int index) const override
Returns the value of the color of index index.
void setColorParamValue (int index, const TPixel32 &color) override
Sets the index-th color value.
Public Member Functions inherited from TColorStyle
TColorStyle (const TColorStyle &other)
Copies another style except its icon.
virtual TColorStyle * clone () const =0
Polymorphic clone of the style.
virtual TColorStyle & copy (const TColorStyle &other)
bool operator== (const TColorStyle &cs) const
bool operator!= (const TColorStyle &cs)
virtual TStrokeProp * makeStrokeProp (const TStroke *stroke)=0
virtual TRegionProp * makeRegionProp (const TRegion *region)=0
used to draw the style on the specified stroke object.
virtual bool isRasterStyle () const
used to draw the style on the specified region object.
virtual TRasterStyleFx * getRasterStyleFx ()
virtual bool isRegionStyle () const =0
Returns whether the style applies on regions.
virtual bool isStrokeStyle () const =0
Returns whether the style applies on strokes.
void setName (std::wstring name)
Sets the style's user-defined name.
std::wstring getName () const
Returns the style's user-defined name.
void setGlobalName (std::wstring name)
Sets the global name of the style.
std::wstring getGlobalName () const
Returns the global name of the style.
void setOriginalName (std::wstring name)
If the style is originally copied from studio palette, set this.
std::wstring getOriginalName () const
Returns the original name of the style.
void setIsEditedFlag (bool edited)
bool getIsEditedFlag () const
style is edited from the original one.
void assignNames (const TColorStyle *src)
Copies the style names from src.
unsigned int getFlags () const
Sets color attributes.
void setFlags (unsigned int flags)
Returns color attributes.
void setPickedPosition (const TPoint &pos, const int index=0)
void setPickedPosition (const PickedPosition &pos)
PickedPosition getPickedPosition () const
virtual bool hasMainColor () const
Returns whether the style has a reference main color.
virtual TPixel32 getMainColor () const
Returns the style's main color, or black if none.
virtual void setMainColor (const TPixel32 &color)
Sets the main color, if it has one.
virtual int getColorParamCount () const
Returns the number of colors (if any) of the style.
virtual TPixel32 getColorParamValue (int index) const
Returns the value of the color of index index.
virtual void setColorParamValue (int index, const TPixel32 &color)
Sets the index-th color value.
virtual TPixel32 getAverageColor () const
Returns a color representing the average of all the style's colors.
virtual int getParamCount () const
virtual ParamType getParamType (int paramIdx) const
Returns the type of the specified parameter.
virtual bool hasParamDefault (int index) const
Value of parameter can be reset to default.
virtual void setParamDefault (int index)
Reset value of parameter to default.
virtual bool isParamDefault (int index) const
Check if current value of parameter equals to default.
virtual void setParamValue (int index, bool value)
Assigns a value to the specified bool parameter.
virtual bool getParamValue (bool_tag, int index) const
Retrieves the specified bool parameter value.
virtual void setParamValue (int index, int value)
Assigns a value to the specified int parameter.
virtual int getParamValue (int_tag, int index) const
Retrieves the specified int parameter value.
virtual void getParamRange (int index, int &min, int &max) const
Retrieves the specified int parameter range.
virtual void getParamRange (int pIndex, QStringList &stringItems) const
virtual void setParamValue (int index, double value)
extension value in text form.
virtual double getParamValue (double_tag, int index) const
Retrieves the specified double parameter value.
virtual void getParamRange (int index, double &min, double &max) const
Retrieves the specified double parameter range.
virtual void setParamValue (int index, const TFilePath &fp)
Assigns a value to the specified TFilePath parameter.
virtual TFilePath getParamValue (TFilePath_tag, int index) const
Retrieves the specified TFilePath parameter value.
void assignBlend (const TColorStyle &a, const TColorStyle &b, double t)
virtual QString getDescription () const =0
Return a brief description of the style.
virtual QString getParamNames (int index) const
Return the string that identifies the index-th parameter.
virtual int getTagId () const =0
Returns an unique number representing the style.
virtual void getObsoleteTagIds (std::vector< int > &) const
void save (TOutputStreamInterface &) const
void invalidateIcon ()
Sets a flag that defines the style's icon validity.
virtual const TRaster32P & getIcon (const TDimension &d)
Returns an image representing the style.
bool isEnabled () const
Returns whether the style can be used.
void enable (bool on)
Sets the style's enabled status.
int getVersionNumber () const
Returns the version number of the style.
Public Member Functions inherited from TSmartObject
TSmartObject (ClassCode classCode)
void addRef ()
void release ()
TINT32 getRefCount () const
Static Public Member Functions
static TFilePath getRootDir ()
static void setRootDir (const TFilePath &path)
Static Public Member Functions inherited from TColorStyle
static TColorStyle * load (TInputStreamInterface &)
static TColorStyle * create (int tagId)
Creates a new style with identifier equal to tagId.
static void declare (TColorStyle *style)
Puts the style in the table of actual styles.
static void getAllTags (std::vector< int > &tags)
Static Public Member Functions inherited from TSmartObject
static TINT32 getInstanceCount (ClassCode code)
Protected Member Functions
void loadData (TInputStreamInterface &) override
void saveData (TOutputStreamInterface &) const override
Protected Member Functions inherited from TColorStyle
virtual void makeIcon (const TDimension &d)
virtual void loadData (TInputStreamInterface &)=0
virtual void saveData (TOutputStreamInterface &) const =0
virtual void loadData (int, TInputStreamInterface &)
void updateVersionNumber ()
TColorStyle & operator= (const TColorStyle &other)
Copies another style except its icon.
Additional Inherited Members
Public Types inherited from TColorStyle
enum ParamType {
BOOL , INT , ENUM , DOUBLE ,
FILEPATH
}
Public Types inherited from TSmartObject
typedef short ClassCode
Static Public Attributes inherited from TColorStyle
static int m_currentFrame = 0
Protected Attributes inherited from TColorStyle
TRaster32P m_icon
Icon shown on TPalette viewers.
bool m_validIcon
Icon's validity status.
Detailed Description
Constructor & Destructor Documentation
TVectorBrushStyle() [1/2]
TVectorBrushStyle::TVectorBrushStyle ()
: m_colorCount(0) {}
TVectorBrushStyle() [2/2]
TVectorBrushStyle::TVectorBrushStyle (const std::string & brushName, TVectorImageP vi = TVectorImageP())
    : m_brush(vi) {
  loadBrush(brushName);
}
~TVectorBrushStyle()
TVectorBrushStyle::~TVectorBrushStyle ()
{}
Member Function Documentation
clone()
TColorStyle * TVectorBrushStyle::clone () const override virtual
Polymorphic clone of the style.
Implements TColorStyle.
{
  TVectorImageP brush;
  if (m_brush) {
    // Clone m_brush and its palette
    brush = m_brush->clone();  // NOTE: This does NOT clone the palette, too.
    brush->setPalette(m_brush->getPalette()->clone());
  }
  TVectorBrushStyle *theClone = new TVectorBrushStyle(m_brushName, brush);
  theClone->assignNames(this);
  theClone->setFlags(getFlags());
  return theClone;
}
References TColorStyle::assignNames(), TColorStyle::getFlags(), and TColorStyle::setFlags().
getColorParamCount()
int TVectorBrushStyle::getColorParamCount () const override virtual
Returns the number of colors (if any) of the style.
\detail For example a bubble styles has two colors. By default it returns 1 if the style has only a main color else returns 0 if the style has no color.
Reimplemented from TColorStyle.
{ return m_colorCount; }
getColorParamValue()
TPixel32 TVectorBrushStyle::getColorParamValue (int index) const override virtual
Returns the value of the color of index index.
\detail Returns the main color by default.
Reimplemented from TColorStyle.
{
  TPalette *pal = m_brush->getPalette();
  assert(pal);
  int styleId              = getColorStyleId(index);
  if (styleId < 0) styleId = 1;
  return pal->getStyle(styleId)->getMainColor();
}
References TColorStyle::getMainColor(), and TPalette::getStyle().
getDescription()
QString TVectorBrushStyle::getDescription () const override virtual
Return a brief description of the style.
\detail For example for a stroke style we have "Constant", "Chain", "Rope", "Tulle", etc...
Implements TColorStyle.
{ return "VectorBrushStyle"; }
getImage()
TVectorImageP TVectorBrushStyle::getImage () const inline
{ return m_brush; }
getMainColor()
TPixel32 TVectorBrushStyle::getMainColor () const override virtual
Returns the style's main color, or black if none.
Reimplemented from TColorStyle.
{
  if (!m_brush) return TPixel32::Transparent;
  TPalette *pal = m_brush->getPalette();
  return pal->getStyle(1)->getMainColor();
}
References TColorStyle::getMainColor(), and TPalette::getStyle().
getRootDir()
static TFilePath TVectorBrushStyle::getRootDir () inline static
{ return m_rootDir; }
getTagId()
int TVectorBrushStyle::getTagId () const inline override virtual
Returns an unique number representing the style.
Implements TColorStyle.
{ return 3000; }
hasMainColor()
bool TVectorBrushStyle::hasMainColor () const inline override virtual
Returns whether the style has a reference main color.
\detail Raster or vector pattern image styles, for example, return false.
Reimplemented from TColorStyle.
{ return true; }
isRegionStyle()
bool TVectorBrushStyle::isRegionStyle () const inline override virtual
Returns whether the style applies on regions.
Implements TColorStyle.
{ return false; }
isStrokeStyle()
bool TVectorBrushStyle::isStrokeStyle () const inline override virtual
Returns whether the style applies on strokes.
Implements TColorStyle.
{ return true; }
loadBrush()
void TVectorBrushStyle::loadBrush (const std::string & brushName)
{
  m_brushName  = brushName;
  m_colorCount = 0;
  if (brushName.empty()) return;
  if (!m_brush) {
    // Load the image associated with fp
    TFilePath fp(m_rootDir + TFilePath(brushName + ".pli"));
    TLevelReaderP lr(fp);
    TLevelP level = lr->loadInfo();
    m_brush = lr->getFrameReader(level->begin()->first)->load();
    assert(m_brush);
    TPalette *palette = level->getPalette();
    m_brush->setPalette(palette);
  }
  assert(m_brush);
  m_colorCount =
      m_brush->getPalette()->getStyleInPagesCount() - 1;  // No transparent
}
loadData()
void TVectorBrushStyle::loadData (TInputStreamInterface & isi) override protected virtual
Implements TColorStyle.
{
  std::string str;
  isi >> str;
  assert(!str.empty());
  loadBrush(str);
  int colorCount;
  isi >> colorCount;
  if (colorCount != m_colorCount)
    return;  // Palette mismatch! Just skip palette loading...
  // WARNING: Is it needed to read all colors nonetheless?
  // Load palette colors
  TPalette *pal = m_brush->getPalette();
  assert(pal);
  TPixel32 color;
  int p, pagesCount = pal->getPageCount();
  for (p = 0; p < pagesCount; ++p) {
    TPalette::Page *page = pal->getPage(p);
    int s, stylesCount = page->getStyleCount();
    for (s = 0; s < stylesCount; ++s) {
      isi >> color;
      page->getStyle(s)->setMainColor(color);
    }
  }
}
makeRegionProp()
TRegionProp * TVectorBrushStyle::makeRegionProp (const TRegion * region) inline override virtual
used to draw the style on the specified stroke object.
Allocates a new derived TRegionProp instance
Implements TColorStyle.
{
    assert(false);
    return 0;
  }
makeStrokeProp()
TStrokeProp * TVectorBrushStyle::makeStrokeProp (const TStroke * stroke) override virtual
Allocates a new derived TStrokeProp instance
Implements TColorStyle.
{
  return new VectorBrushProp(stroke, this);
}
saveData()
void TVectorBrushStyle::saveData (TOutputStreamInterface & osi) const override protected virtual
Implements TColorStyle.
{
  osi << m_brushName;
  // Save palette
  osi << m_colorCount;
  TPalette *pal = m_brush->getPalette();
  assert(pal);
  int p, pagesCount = pal->getPageCount();
  for (p = 0; p < pagesCount; ++p) {
    TPalette::Page *page = pal->getPage(p);
    int s, stylesCount = page->getStyleCount();
    for (s = 0; s < stylesCount; ++s) osi << page->getStyle(s)->getMainColor();
  }
}
setColorParamValue()
void TVectorBrushStyle::setColorParamValue (int index, const TPixel32 & color) override virtual
Sets the index-th color value.
Reimplemented from TColorStyle.
{
  TPalette *pal = m_brush->getPalette();
  assert(pal);
  int styleId              = getColorStyleId(index);
  if (styleId < 0) styleId = 1;
  return pal->getStyle(styleId)->setMainColor(color);
}
References TPalette::getStyle(), and TColorStyle::setMainColor().
setMainColor()
void TVectorBrushStyle::setMainColor (const TPixel32 & color) override virtual
Sets the main color, if it has one.
Reimplemented from TColorStyle.
{
  if (!m_brush) return;
  TPalette *pal = m_brush->getPalette();
  pal->getStyle(1)->setMainColor(color);
}
References TPalette::getStyle(), and TColorStyle::setMainColor().
setRootDir()
static void TVectorBrushStyle::setRootDir (const TFilePath & path) inline static
{
    m_rootDir = path + "vector brushes";
  }
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/tvectorbrushstyle.h
E:/opentoonz/toonz/sources/common/tvrender/tvectorbrushstyle.cpp