opentoonz: XsheetViewer Class Reference
XsheetViewer Class Reference final
#include <xsheetviewer.h>
Public Types
enum FrameDisplayStyle { Frame = 0 , SecAndFrame , SixSecSheet , ThreeSecSheet }
Public Slots
void positionSections ()
void onSceneSwitched ()
void onXsheetChanged ()
void onCurrentFrameSwitched ()
void onPlayingStatusChanged ()
void onCurrentColumnSwitched ()
void onSelectionSwitched (TSelection *oldSelection, TSelection *newSelection)
void onSelectionChanged (TSelection *selection)
void updateAllAree (bool isDragging=false)
void updateColumnArea ()
void updateCellColumnAree ()
void updateCellRowAree ()
void onScrubStopped ()
void onPreferenceChanged (const QString &prefName)
void changeWindowTitle ()
Aggiorna il "titolo" del widget.
void resetXsheetNotes ()
void onOrientationChanged (const Orientation *newOrientation)
void onPrepareToScrollOffset (const QPointF &offset)
void onZoomScrollAdjust (QPointF &offset, bool toZoom)
void setFrameZoomFactor (int f)
int getFrameZoomFactor () const
QPoint getFrameZoomAdjustment ()
void zoomOnFrame (int frame, int factor)
Signals
void orientationChanged (const Orientation *newOrientation)
Public Member Functions
XsheetViewer (QWidget *parent=0, Qt::WFlags flags=0)
TColumnSelection * getColumnSelection () const
TCellSelection * getCellSelection () const
TKeyframeSelection * getKeyframeSelection () const
TCellKeyframeSelection * getCellKeyframeSelection () const
bool areCellsSelectedEmpty ()
bool areSoundCellsSelected ()
bool areSoundTextCellsSelected ()
bool areCameraCellsSelected ()
XsheetGUI::DragTool * getDragTool () const
void setDragTool (XsheetGUI::DragTool *dragTool)
void dragToolClick (QMouseEvent *)
void dragToolDrag (QMouseEvent *)
void dragToolRelease (QMouseEvent *)
void dragToolLeave (QEvent *)
void dragToolClick (QDropEvent *)
void dragToolDrag (QDropEvent *)
void dragToolRelease (QDropEvent *)
void setQtModifiers (Qt::KeyboardModifiers value)
void setScrubHighlight (int row, int starRow, int col)
void resetScrubHighlight ()
void getScrubHeighlight (int &R0, int &R1)
bool isScrubHighlighted (int row, int col)
TXsheet * getXsheet () const
int getCurrentColumn () const
int getCurrentRow () const
TStageObjectId getObjectId (int col) const
Restituisce la objectId corrispondente alla colonna col.
void setCurrentColumn (int col)
void setCurrentRow (int row)
void scroll (QPoint delta)
void setAutoPanSpeed (const QPoint &speed)
void setAutoPanSpeed (const QRect &widgetBounds, const QPoint &mousePos)
void stopAutoPan ()
bool isAutoPanning () const
const Orientation * orientation () const
void flipOrientation ()
CellPosition xyToPosition (const QPoint &point) const
CellPosition xyToPosition (const TPoint &point) const
CellPosition xyToPosition (const TPointD &point) const
QPoint positionToXY (const CellPosition &pos) const
int colToTimelineLayerAxis (int layer) const
int columnToLayerAxis (int layer) const
int rowToFrameAxis (int frame) const
CellRange xyRectToRange (const QRect &rect) const
QRect rangeToXYRect (const CellRange &range) const
void drawPredefinedPath (QPainter &p, PredefinedPath which, const CellPosition &pos, optional< QColor > fill, optional< QColor > outline) const
void drawPredefinedPath (QPainter &p, PredefinedPath which, QPoint xy, optional< QColor > fill, optional< QColor > outline) const
void updateCells ()
void updateRows ()
void updateColumns ()
bool refreshContentSize (int scrollDx, int scrollDy)
void updateAreeSize ()
QList< XsheetGUI::NoteWidget * > getNotesWidget () const
void addNoteWidget (XsheetGUI::NoteWidget *w)
int getCurrentNoteIndex () const
void clearNoteWidgets ()
Clear notes widgets std::vector.
void updateNoteWidgets ()
Update notes widgets and update cell.
void discardNoteWidget ()
Discard Note Widget.
void setCurrentNoteIndex (int currentNoteIndex)
void scrollTo (int row, int col)
void setLightLightBGColor (const QColor &color)
QColor getLightLightBGColor () const
void setLightBGColor (const QColor &color)
QColor getLightBGColor () const
void setBGColor (const QColor &color)
QColor getBGColor () const
void setDarkBGColor (const QColor &color)
QColor getDarkBGColor () const
void setLightLineColor (const QColor &color)
QColor getLightLineColor () const
void setDarkLineColor (const QColor &color)
QColor getDarkLineColor () const
QColor getColumnIconLineColor () const
void setColumnIconLineColor (const QColor &color)
QColor getTimelineIconLineColor () const
void setTimelineIconLineColor (const QColor &color)
QColor getFrameRangeMarkerLineColor () const
void setFrameRangeMarkerLineColor (const QColor &color)
void setCurrentRowBgColor (const QColor &color)
QColor getCurrentRowBgColor () const
void setMarkerLineColor (const QColor &color)
QColor getMarkerLineColor () const
void setVerticalLineColor (const QColor &color)
QColor getVerticalLineColor () const
void setVerticalLineHeadColor (const QColor &color)
QColor getVerticalLineHeadColor () const
void setTextColor (const QColor &color)
QColor getTextColor () const
void setErrorTextColor (const QColor &color)
QColor getErrorTextColor () const
void setPreviewFrameTextColor (const QColor &color)
QColor getPreviewFrameTextColor () const
void setOnionSkinAreaBgColor (const QColor &color)
QColor getOnionSkinAreaBgColor () const
void setEmptyColumnHeadColor (const QColor &color)
QColor getEmptyColumnHeadColor () const
QColor getSelectedColumnTextColor () const
void setEmptyCellColor (const QColor &color)
QColor getEmptyCellColor () const
void setNotEmptyColumnColor (const QColor &color)
QColor getNotEmptyColumnColor () const
void setSelectedEmptyCellColor (const QColor &color)
QColor getSelectedEmptyCellColor () const
void setCellFocusColor (const QColor &color)
QColor getCellFocusColor () const
QColor getPlayRangeColor () const
void setPlayRangeColor (const QColor &color)
void setLevelColumnColor (const QColor &color)
void setLevelColumnBorderColor (const QColor &color)
void setSelectedLevelColumnColor (const QColor &color)
QColor getLevelColumnColor () const
QColor getLevelColumnBorderColor () const
QColor getSelectedLevelColumnColor () const
void setVectorColumnColor (const QColor &color)
void setVectorColumnBorderColor (const QColor &color)
void setSelectedVectorColumnColor (const QColor &color)
QColor getVectorColumnColor () const
QColor getVectorColumnBorderColor () const
QColor getSelectedVectorColumnColor () const
void setChildColumnColor (const QColor &color)
void setChildColumnBorderColor (const QColor &color)
void setSelectedChildColumnColor (const QColor &color)
QColor getChildColumnColor () const
QColor getChildColumnBorderColor () const
QColor getSelectedChildColumnColor () const
void setFullcolorColumnColor (const QColor &color)
void setFullcolorColumnBorderColor (const QColor &color)
void setSelectedFullcolorColumnColor (const QColor &color)
QColor getFullcolorColumnColor () const
QColor getFullcolorColumnBorderColor () const
QColor getSelectedFullcolorColumnColor () const
void setFxColumnColor (const QColor &color)
void setFxColumnBorderColor (const QColor &color)
void setSelectedFxColumnColor (const QColor &color)
QColor getFxColumnColor () const
QColor getFxColumnBorderColor () const
QColor getSelectedFxColumnColor () const
void setReferenceColumnColor (const QColor &color)
void setReferenceColumnBorderColor (const QColor &color)
void setSelectedReferenceColumnColor (const QColor &color)
QColor getReferenceColumnColor () const
QColor getReferenceColumnBorderColor () const
QColor getSelectedReferenceColumnColor () const
void setPaletteColumnColor (const QColor &color)
void setPaletteColumnBorderColor (const QColor &color)
void setSelectedPaletteColumnColor (const QColor &color)
QColor getPaletteColumnColor () const
QColor getPaletteColumnBorderColor () const
QColor getSelectedPaletteColumnColor () const
void setMeshColumnColor (const QColor &color)
void setMeshColumnBorderColor (const QColor &color)
void setSelectedMeshColumnColor (const QColor &color)
QColor getMeshColumnColor () const
QColor getMeshColumnBorderColor () const
QColor getSelectedMeshColumnColor () const
void setSoundTextColumnColor (const QColor &color)
void setSoundTextColumnBorderColor (const QColor &color)
void setSelectedSoundTextColumnColor (const QColor &color)
QColor getSoundTextColumnColor () const
QColor getSoundTextColumnBorderColor () const
QColor getSelectedSoundTextColumnColor () const
QColor getSoundColumnHlColor () const
QColor getSoundColumnTrackColor () const
void setColumnHeadPastelizer (const QColor &color)
QColor getColumnHeadPastelizer () const
void setSelectedColumnHead (const QColor &color)
QColor getSelectedColumnHead () const
void getCellTypeAndColors (int &ltype, QColor &cellColor, QColor &sideColor, const TXshCell &cell, bool isSelected=false)
void getColumnColor (QColor &color, QColor &sidecolor, int index, TXsheet *xsh)
QColor getFoldedColumnBGColor () const
QColor getFoldedColumnLineColor () const
void setFoldedColumnBGColor (const QColor &color)
void setFoldedColumnLineColor (const QColor &color)
void setXsheetColumnNameBgColor (const QColor &color)
void setXsheetDragBarHighlightColor (const QColor &color)
QColor getXsheetColumnNameBgColor () const
QColor getXsheetDragBarHighlightColor () const
void setActiveCameraColor (const QColor &color)
void setSelectedActiveCameraColor (const QColor &color)
QColor getActiveCameraColor () const
QColor getSelectedActiveCameraColor () const
void setOtherCameraColor (const QColor &color)
void setSelectedOtherCameraColor (const QColor &color)
QColor getOtherCameraColor () const
QColor getSelectedOtherCameraColor () const
void setXsheetPreviewButtonBgOnColor (const QColor &color)
void setXsheetPreviewButtonOnImage (const QImage &image)
void setXsheetPreviewButtonBgOffColor (const QColor &color)
void setXsheetPreviewButtonOffImage (const QImage &image)
QColor getXsheetPreviewButtonBgOnColor () const
QImage getXsheetPreviewButtonOnImage () const
QColor getXsheetPreviewButtonBgOffColor () const
QImage getXsheetPreviewButtonOffImage () const
void setXsheetCamstandButtonBgOnColor (const QColor &color)
void setXsheetCamstandButtonOnImage (const QImage &image)
void setXsheetCamstandButtonTranspImage (const QImage &image)
void setXsheetCamstandButtonBgOffColor (const QColor &color)
void setXsheetCamstandButtonOffImage (const QImage &image)
QColor getXsheetCamstandButtonBgOnColor () const
QImage getXsheetCamstandButtonOnImage () const
QImage getXsheetCamstandButtonTranspImage () const
QColor getXsheetCamstandButtonBgOffColor () const
QImage getXsheetCamstandButtonOffImage () const
void setXsheetLockButtonBgOnColor (const QColor &color)
void setXsheetLockButtonOnImage (const QImage &image)
void setXsheetLockButtonBgOffColor (const QColor &color)
void setXsheetLockButtonOffImage (const QImage &image)
QColor getXsheetLockButtonBgOnColor () const
QImage getXsheetLockButtonOnImage () const
QColor getXsheetLockButtonBgOffColor () const
QImage getXsheetLockButtonOffImage () const
void setXsheetConfigButtonBgColor (const QColor &color)
void setXsheetConfigButtonImage (const QImage &image)
QColor getXsheetConfigButtonBgColor () const
QImage getXsheetConfigButtonImage () const
void setTimelinePreviewButtonBgOnColor (const QColor &color)
void setTimelinePreviewButtonOnImage (const QImage &image)
void setTimelinePreviewButtonBgOffColor (const QColor &color)
void setTimelinePreviewButtonOffImage (const QImage &image)
QColor getTimelinePreviewButtonBgOnColor () const
QImage getTimelinePreviewButtonOnImage () const
QColor getTimelinePreviewButtonBgOffColor () const
QImage getTimelinePreviewButtonOffImage () const
void setTimelineCamstandButtonBgOnColor (const QColor &color)
void setTimelineCamstandButtonOnImage (const QImage &image)
void setTimelineCamstandButtonTranspImage (const QImage &image)
void setTimelineCamstandButtonBgOffColor (const QColor &color)
void setTimelineCamstandButtonOffImage (const QImage &image)
QColor getTimelineCamstandButtonBgOnColor () const
QImage getTimelineCamstandButtonOnImage () const
QImage getTimelineCamstandButtonTranspImage () const
QColor getTimelineCamstandButtonBgOffColor () const
QImage getTimelineCamstandButtonOffImage () const
void setTimelineLockButtonBgOnColor (const QColor &color)
void setTimelineLockButtonOnImage (const QImage &image)
void setTimelineLockButtonBgOffColor (const QColor &color)
void setTimelineLockButtonOffImage (const QImage &image)
QColor getTimelineLockButtonBgOnColor () const
QImage getTimelineLockButtonOnImage () const
QColor getTimelineLockButtonBgOffColor () const
QImage getTimelineLockButtonOffImage () const
void setTimelineConfigButtonBgColor (const QColor &color)
void setTimelineConfigButtonImage (const QImage &image)
QColor getTimelineConfigButtonBgColor () const
QImage getTimelineConfigButtonImage () const
void setLayerHeaderPreviewImage (const QImage &image)
void setLayerHeaderPreviewOverImage (const QImage &image)
void setLayerHeaderCamstandImage (const QImage &image)
void setLayerHeaderCamstandOverImage (const QImage &image)
void setLayerHeaderLockImage (const QImage &image)
void setLayerHeaderLockOverImage (const QImage &image)
QImage getLayerHeaderPreviewImage () const
QImage getLayerHeaderPreviewOverImage () const
QImage getLayerHeaderCamstandImage () const
QImage getLayerHeaderCamstandOverImage () const
QImage getLayerHeaderLockImage () const
QImage getLayerHeaderLockOverImage () const
void getButton (const int &btype, QColor &bgColor, QImage &iconImage, bool isTimeline=false)
QString getFrameNumberWithLetters (int frame)
void setFrameDisplayStyle (FrameDisplayStyle style)
FrameDisplayStyle getFrameDisplayStyle ()
virtual void save (QSettings &settings) const override
virtual void load (QSettings &settings) override
QString getXsheetLayout () const
QList< int > availableFramesPerPage ()
void zoomToFramesPerPage (int frames)
virtual void save (QSettings &settings) const =0
virtual void load (QSettings &settings)=0
Protected Member Functions
void scrollToColumn (int col)
void scrollToHorizontalRange (int x0, int x1)
void scrollToRow (int row)
void scrollToVerticalRange (int y0, int y1)
void showEvent (QShowEvent *) override
void hideEvent (QHideEvent *) override
void resizeEvent (QResizeEvent *event) override
void keyPressEvent (QKeyEvent *event) override
void keyReleaseEvent (QKeyEvent *event) override
void enterEvent (QEvent *) override
void wheelEvent (QWheelEvent *event) override
void timerEvent (QTimerEvent *) override
void disconnectScrollBars ()
void connectScrollBars ()
void connectOrDisconnectScrollBars (bool toConnect)
void connectOrDisconnect (bool toConnect, QWidget *sender, const char *signal, QWidget *receiver, const char *slot)
Properties
QColor LightLightBGColor
QColor LightBGColor
QColor BGColor
QColor DarkBGColor
QColor LightLineColor
QColor DarkLineColor
QColor ColumnIconLineColor
QColor TimelineIconLineColor
QColor CurrentRowBgColor
QColor MarkerLineColor
QColor VerticalLineColor
QColor VerticalLineHeadColor
QColor TextColor
QColor ErrorTextColor
QColor PreviewFrameTextColor
QColor OnionSkinAreaBgColor
QColor FrameRangeMarkerLineColor
QColor EmptyColumnHeadColor
QColor EmptyCellColor
QColor NotEmptyColumnColor
QColor SelectedEmptyCellColor
QColor CellFocusColor
QColor PlayRangeColor
QColor LevelColumnColor
QColor LevelColumnBorderColor
QColor SelectedLevelColumnColor
QColor VectorColumnColor
QColor VectorColumnBorderColor
QColor SelectedVectorColumnColor
QColor ChildColumnColor
QColor ChildColumnBorderColor
QColor SelectedChildColumnColor
QColor FullcolorColumnColor
QColor FullcolorColumnBorderColor
QColor SelectedFullcolorColumnColor
QColor FxColumnColor
QColor FxColumnBorderColor
QColor SelectedFxColumnColor
QColor ReferenceColumnColor
QColor ReferenceColumnBorderColor
QColor SelectedReferenceColumnColor
QColor PaletteColumnColor
QColor PaletteColumnBorderColor
QColor SelectedPaletteColumnColor
QColor MeshColumnColor
QColor MeshColumnBorderColor
QColor SelectedMeshColumnColor
QColor SoundTextColumnColor
QColor SoundTextColumnBorderColor
QColor SelectedSoundTextColumnColor
QColor SoundColumnColor
QColor SoundColumnBorderColor
QColor SelectedSoundColumnColor
QColor SoundColumnHlColor
QColor SoundColumnTrackColor
QColor ColumnHeadPastelizer
QColor SelectedColumnHead
QColor FoldedColumnBGColor
QColor FoldedColumnLineColor
QColor XsheetColumnNameBgColor
QColor XsheetDragBarHighlightColor
QColor ActiveCameraColor
QColor SelectedActiveCameraColor
QColor OtherCameraColor
QColor SelectedOtherCameraColor
QColor XsheetPreviewButtonBgOnColor
QImage XsheetPreviewButtonOnImage
QColor XsheetPreviewButtonBgOffColor
QImage XsheetPreviewButtonOffImage
QColor XsheetCamstandButtonBgOnColor
QImage XsheetCamstandButtonOnImage
QImage XsheetCamstandButtonTranspImage READ getXsheetCamstandButtonTranspImage WRITE setXsheetCamstandButtonTranspImage Q_PROPERTYQColor XsheetCamstandButtonBgOffColor READ getXsheetCamstandButtonBgOffColor WRITE setXsheetCamstandButtonBgOffColor Q_PROPERTY QImage XsheetCamstandButtonOffImage
QColor XsheetLockButtonBgOnColor
QImage XsheetLockButtonOnImage
QColor XsheetLockButtonBgOffColor
QImage XsheetLockButtonOffImage
QColor XsheetConfigButtonBgColor
QImage XsheetConfigButtonImage
QColor TimelinePreviewButtonBgOnColor READ getTimelinePreviewButtonBgOnColor WRITE setTimelinePreviewButtonBgOnColor Q_PROPERTY QImage TimelinePreviewButtonOnImage
QColor TimelinePreviewButtonBgOffColor READ getTimelinePreviewButtonBgOffColor WRITE setTimelinePreviewButtonBgOffColor Q_PROPERTY QImage TimelinePreviewButtonOffImage
QColor TimelineCamstandButtonBgOnColor READ getTimelineCamstandButtonBgOnColor WRITE setTimelineCamstandButtonBgOnColor Q_PROPERTY QImage TimelineCamstandButtonOnImage
QImage TimelineCamstandButtonTranspImage READ getTimelineCamstandButtonTranspImage WRITE setTimelineCamstandButtonTranspImage Q_PROPERTYQColor TimelineCamstandButtonBgOffColor READ getTimelineCamstandButtonBgOffColor WRITE setTimelineCamstandButtonBgOffColor Q_PROPERTYQImage TimelineCamstandButtonOffImage READ getTimelineCamstandButtonOffImage WRITE setTimelineCamstandButtonOffImage QColor m_timelineLockButtonBgOnColor QImage m_timelineLockButtonOnImage QColor m_timelineLockButtonBgOffColor QImage m_timelineLockButtonOffImage Q_PROPERTY QColor TimelineLockButtonBgOnColor
QImage TimelineLockButtonOnImage
QColor TimelineLockButtonBgOffColor
QImage TimelineLockButtonOffImage
QColor TimelineConfigButtonBgColor
QImage TimelineConfigButtonImage
QImage LayerHeaderPreviewImage
QImage LayerHeaderPreviewOverImage
QImage LayerHeaderCamstandImage
QImage LayerHeaderCamstandOverImage
QImage LayerHeaderLockImage
QImage LayerHeaderLockOverImage
Detailed Description
Note: some refactoring is needed. XsheetViewer is going to derive from SpreadsheetViewer.
Member Enumeration Documentation
FrameDisplayStyle
enum XsheetViewer::FrameDisplayStyle
{ Frame = 0, SecAndFrame, SixSecSheet, ThreeSecSheet };
Constructor & Destructor Documentation
XsheetViewer()
XsheetViewer::XsheetViewer (QWidget * parent = 0, Qt::WFlags flags = 0)
    : QFrame(parent)
    , m_timerId(0)
    , m_autoPanSpeed(0, 0)
    , m_dragTool(0)
    , m_columnSelection(new TColumnSelection())
    , m_cellKeyframeSelection(new TCellKeyframeSelection(
          new TCellSelection(), new TKeyframeSelection()))
    , m_scrubCol(-1)
    , m_scrubRow0(-1)
    , m_scrubRow1(-1)
    , m_isCurrentFrameSwitched(false)
    , m_isCurrentColumnSwitched(false)
    , m_isComputingSize(false)
    , m_currentNoteIndex(0)
    , m_qtModifiers(0)
    , m_frameDisplayStyle(to_enum(FrameDisplayStyleInXsheetRowArea))
    , m_orientation(nullptr)
    , m_xsheetLayout("Classic")
    , m_frameZoomFactor(100) {
  m_xsheetLayout = Preferences::instance()->getLoadedXsheetLayout();
  setFocusPolicy(Qt::StrongFocus);
  setFrameStyle(QFrame::StyledPanel);
  setObjectName("XsheetViewer");
  m_orientation = Orientations::topToBottom();
  m_cellKeyframeSelection->setXsheetHandle(
      TApp::instance()->getCurrentXsheet());
  m_toolbarScrollArea = new XsheetScrollArea(this);
  m_toolbarScrollArea->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
  m_toolbarScrollArea->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
  m_toolbar = new XsheetGUI::XSheetToolbar(this, 0, true);
  m_toolbarScrollArea->setWidget(m_toolbar);
  m_noteArea       = new XsheetGUI::NoteArea(this);
  m_noteScrollArea = new XsheetScrollArea(this);
  m_noteScrollArea->setObjectName("xsheetArea");
  m_noteScrollArea->setWidget(m_noteArea);
  m_noteScrollArea->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
  m_noteScrollArea->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
  m_cellArea       = new XsheetGUI::CellArea(this);
  m_cellScrollArea = new XsheetScrollArea(this);
  m_cellScrollArea->setObjectName("xsheetArea");
  m_cellScrollArea->setWidget(m_cellArea);
  m_cellScrollArea->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOn);
  m_cellScrollArea->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOn);
  m_columnArea       = new XsheetGUI::ColumnArea(this);
  m_columnScrollArea = new XsheetScrollArea(this);
  m_columnScrollArea->setObjectName("xsheetArea");
  m_columnScrollArea->setWidget(m_columnArea);
  m_columnScrollArea->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
  m_columnScrollArea->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
  m_rowArea       = new XsheetGUI::RowArea(this);
  m_rowScrollArea = new XsheetScrollArea(this);
  m_rowScrollArea->setObjectName("xsheetArea");
  m_rowScrollArea->setWidget(m_rowArea);
  m_rowScrollArea->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
  m_rowScrollArea->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
  m_layerFooterPanel = new LayerFooterPanel(this, this);
  m_frameScroller.setFrameScrollArea(m_cellScrollArea);
  connect(&m_frameScroller, &Spreadsheet::FrameScroller::prepareToScrollOffset,
          this, &XsheetViewer::onPrepareToScrollOffset);
  connect(&m_frameScroller, &Spreadsheet::FrameScroller::zoomScrollAdjust, this,
          &XsheetViewer::onZoomScrollAdjust);
  connectScrollBars();
  connect(this, &XsheetViewer::orientationChanged, this,
          &XsheetViewer::onOrientationChanged);
  connect(m_toolbar, SIGNAL(updateVisibility()), this,
          SLOT(positionSections()));
  emit orientationChanged(orientation());
  onPreferenceChanged("XsheetCamera");
}
~XsheetViewer()
XsheetViewer::~XsheetViewer ()
{
  delete m_cellKeyframeSelection;
  delete m_dragTool;
}
Member Function Documentation
addNoteWidget()
void XsheetViewer::addNoteWidget (XsheetGUI::NoteWidget * w)
{
  m_noteWidgets.push_back(w);
  m_noteArea->updateButtons();
}
areCameraCellsSelected()
bool XsheetViewer::areCameraCellsSelected ()
{
  int r0, c0, r1, c1;
  getCellSelection()->getSelectedCells(r0, c0, r1, c1);
  return c0 < 0;
}
areCellsSelectedEmpty()
bool XsheetViewer::areCellsSelectedEmpty ()
{
  int r0, c0, r1, c1;
  getCellSelection()->getSelectedCells(r0, c0, r1, c1);
  int i, j;
  for (i = r0; i <= r1; i++)
    for (j = c0; j <= c1; j++)
      if (!getXsheet()->getCell(i, j).isEmpty()) return false;
  return true;
}
areSoundCellsSelected()
bool XsheetViewer::areSoundCellsSelected ()
Return true if selection contain only sound cell.
{
  int r0, c0, r1, c1;
  getCellSelection()->getSelectedCells(r0, c0, r1, c1);
  if (c0 < 0) return false;
  int i, j;
  for (i = r0; i <= r1; i++)
    for (j = c0; j <= c1; j++) {
      TXshCell cell = getXsheet()->getCell(i, j);
      if (cell.isEmpty() || cell.getSoundLevel()) continue;
      return false;
    }
  return !areCellsSelectedEmpty();
}
References TXsheet::getCell(), TXshCell::getSoundLevel(), and TXshCell::isEmpty().
areSoundTextCellsSelected()
bool XsheetViewer::areSoundTextCellsSelected ()
{
  int r0, c0, r1, c1;
  getCellSelection()->getSelectedCells(r0, c0, r1, c1);
  if (c0 < 0) return false;
  int i, j;
  for (i = r0; i <= r1; i++)
    for (j = c0; j <= c1; j++) {
      TXshCell cell = getXsheet()->getCell(i, j);
      if (cell.isEmpty() || cell.getSoundTextLevel()) continue;
      return false;
    }
  return !areCellsSelectedEmpty();
}
availableFramesPerPage()
QList< int > XsheetViewer::availableFramesPerPage ()
{
  int frameRate = TApp::instance()
                      ->getCurrentScene()
                      ->getScene()
                      ->getProperties()
                      ->getOutputProperties()
                      ->getFrameRate();
  // 1sec, 1.5sec, 2sec, 3sec, 4sec, 6sec
  QList<int> ret;
  ret << frameRate;
  if (frameRate % 2 == 0) ret << frameRate * 3 / 2;
  ret << frameRate * 2;
  ret << frameRate * 3;
  ret << frameRate * 4;
  ret << frameRate * 6;
  // visible area size
  int size = (orientation()->isVerticalTimeline())
                 ? m_cellScrollArea->viewport()->height()
                 : m_cellScrollArea->viewport()->width();
  int scaleMin = (orientation()->isVerticalTimeline()) ? 50 : 20;
  int scaleMax = 100;
  int frameMin = (int)std::ceil(
      (double)size /
      ((double)orientation()->dimension(PredefinedDimension::FRAME) *
       (double)scaleMax / 100.0));
  int frameMax = (int)std::floor(
      (double)size /
      ((double)orientation()->dimension(PredefinedDimension::FRAME) *
       (double)scaleMin / 100.0));
  for (auto itr = ret.begin(); itr != ret.end();) {
    // erase unavailable items
    if (*itr < frameMin || *itr > frameMax) {
      itr = ret.erase(itr);
      continue;
    }
    itr++;
  }
  return ret;
}
changeWindowTitle
void XsheetViewer::changeWindowTitle () slot
Aggiorna il "titolo" del widget.
{
  TApp *app         = TApp::instance();
  ToonzScene *scene = app->getCurrentScene()->getScene();
  if (!scene || !app->getCurrentFrame()->isEditingScene()) return;
  TProject *project = scene->getProject();
  QString sceneName = QString::fromStdWString(scene->getSceneName());
  if (sceneName.isEmpty()) sceneName = tr("Untitled");
  if (app->getCurrentScene()->getDirtyFlag()) sceneName += QString("*");
  QString name   = tr("Scene: ") + sceneName;
  int frameCount = scene->getFrameCount();
  name           = name + "   ::   " + tr(std::to_string(frameCount).c_str()) +
         (frameCount == 1 ? tr(" Frame") : tr(" Frames"));
  // subXsheet or not
  ChildStack *childStack = scene->getChildStack();
  if (childStack && childStack->getAncestorCount() > 0) {
    name += tr("  (Sub)");
  }
  // current level name
  TXshLevel *level = app->getCurrentLevel()->getLevel();
  if (level) {
    QString levelName = QString::fromStdWString(level->getName());
    name += tr("  Level: ") + levelName;
  }
  // cell selection range
  if ((TSelection *)getCellSelection() ==
          app->getCurrentSelection()->getSelection() &&
      !getCellSelection()->isEmpty()) {
    int r0, r1, c0, c1;
    getCellSelection()->getSelectedCells(r0, c0, r1, c1);
    name += tr("   Selected: ") + QString::number(r1 - r0 + 1) +
            ((r1 - r0 + 1 == 1) ? tr(" frame : ") : tr(" frames * ")) +
            QString::number(c1 - c0 + 1) +
            ((c1 - c0 + 1 == 1) ? tr(" column") : tr(" columns"));
  }
  parentWidget()->setWindowTitle(name);
}
References ToonzScene::getChildStack(), TApp::getCurrentFrame(), TApp::getCurrentLevel(), TApp::getCurrentScene(), TApp::getCurrentSelection(), ToonzScene::getFrameCount(), TXshLevel::getName(), ToonzScene::getProject(), ToonzScene::getSceneName(), and TApp::instance().
Referenced by onSelectionChanged().
clearNoteWidgets()
void XsheetViewer::clearNoteWidgets ()
Clear notes widgets std::vector.
{
  int i;
  for (i = 0; i < m_noteWidgets.size(); i++) delete m_noteWidgets.at(i);
  m_noteWidgets.clear();
}
colToTimelineLayerAxis()
int XsheetViewer::colToTimelineLayerAxis (int layer) const
{
  const Orientation *o = orientation();
  TXsheet *xsh         = getXsheet();
  if (!xsh) return 0;
  ColumnFan *fan = xsh->getColumnFan(o);
  int yBottom = o->colToLayerAxis(layer, fan) +
                (fan->isActive(layer) ? o->cellHeight() : o->foldedCellSize()) -
                1;
  int columnCount = std::max(1, xsh->getColumnCount());
  int layerHeightActual =
      m_columnArea->height() - 2;  // o->colToLayerAxis(columnCount, fan) - 1;
  return layerHeightActual - yBottom;
}
columnToLayerAxis()
int XsheetViewer::columnToLayerAxis (int layer) const
{
  const Orientation *o = orientation();
  TXsheet *xsh         = getXsheet();
  if (!xsh) return 0;
  if (o->isVerticalTimeline())
    return o->colToLayerAxis(layer, xsh->getColumnFan(o));
  else
    return colToTimelineLayerAxis(layer);
}
connectOrDisconnect()
void XsheetViewer::connectOrDisconnect (bool toConnect, QWidget * sender, const char * signal, QWidget * receiver, const char * slot) protected
{
  if (toConnect)
    connect(sender, signal, receiver, slot);
  else
    disconnect(sender, signal, receiver, slot);
}
connectOrDisconnectScrollBars()
void XsheetViewer::connectOrDisconnectScrollBars (bool toConnect) protected
{
  const Orientation *o = orientation();
  bool isVertical      = o->isVerticalTimeline();
  QWidget *scrolledVertically =
      (isVertical ? m_rowScrollArea : m_columnScrollArea)->verticalScrollBar();
  QWidget *scrolledHorizontally =
      (isVertical ? m_columnScrollArea : m_rowScrollArea)
          ->horizontalScrollBar();
  connectOrDisconnect(toConnect, scrolledVertically, SIGNAL(valueChanged(int)),
                      m_cellScrollArea->verticalScrollBar(),
                      SLOT(setValue(int)));
  connectOrDisconnect(toConnect, m_cellScrollArea->verticalScrollBar(),
                      SIGNAL(valueChanged(int)), scrolledVertically,
                      SLOT(setValue(int)));
  connectOrDisconnect(
      toConnect, scrolledHorizontally, SIGNAL(valueChanged(int)),
      m_cellScrollArea->horizontalScrollBar(), SLOT(setValue(int)));
  connectOrDisconnect(toConnect, m_cellScrollArea->horizontalScrollBar(),
                      SIGNAL(valueChanged(int)), scrolledHorizontally,
                      SLOT(setValue(int)));
  connectOrDisconnect(
      toConnect, m_cellScrollArea->verticalScrollBar(),
      SIGNAL(valueChanged(int)), this,
      isVertical ? SLOT(updateCellRowAree()) : SLOT(updateCellColumnAree()));
  connectOrDisconnect(
      toConnect, m_cellScrollArea->horizontalScrollBar(),
      SIGNAL(valueChanged(int)), this,
      isVertical ? SLOT(updateCellColumnAree()) : SLOT(updateCellRowAree()));
}
connectScrollBars()
void XsheetViewer::connectScrollBars () protected
{ connectOrDisconnectScrollBars(true); }
discardNoteWidget()
void XsheetViewer::discardNoteWidget ()
Discard Note Widget.
{
  if (m_currentNoteIndex == -1) return;
  TXshNoteSet *notes = getXsheet()->getNotes();
  int i;
  for (i = m_currentNoteIndex + 1; i < m_noteWidgets.size(); i++) {
    XsheetGUI::NoteWidget *w = m_noteWidgets.at(i);
    int index                = w->getNoteIndex();
    w->setNoteIndex(index - 1);
    w->update();
  }
  delete m_noteWidgets.at(m_currentNoteIndex);
  m_noteWidgets.removeAt(m_currentNoteIndex);
  m_noteArea->updateButtons();
  updateCells();
}
disconnectScrollBars()
void XsheetViewer::disconnectScrollBars () protected
{
  connectOrDisconnectScrollBars(false);
}
dragToolClick() [1/2]
void XsheetViewer::dragToolClick (QDropEvent * e)
{
  if (m_dragTool) m_dragTool->onClick(e);
}
dragToolClick() [2/2]
void XsheetViewer::dragToolClick (QMouseEvent * e)
{
  if (m_dragTool) m_dragTool->onClick(e);
}
dragToolDrag() [1/2]
void XsheetViewer::dragToolDrag (QDropEvent * e)
{
  if (m_dragTool) m_dragTool->onDrag(e);
}
dragToolDrag() [2/2]
void XsheetViewer::dragToolDrag (QMouseEvent * e)
{
  if (m_dragTool) m_dragTool->onDrag(e);
}
dragToolLeave()
void XsheetViewer::dragToolLeave (QEvent * e)
{
  if (m_dragTool) {
    delete getDragTool();
    m_dragTool = 0;
  }
}
dragToolRelease() [1/2]
void XsheetViewer::dragToolRelease (QDropEvent * e)
{
  if (m_dragTool) {
    m_dragTool->onRelease(e);
    delete getDragTool();
    m_dragTool = 0;
  }
}
dragToolRelease() [2/2]
void XsheetViewer::dragToolRelease (QMouseEvent * e)
{
  if (m_dragTool) {
    m_dragTool->onRelease(e);
    delete getDragTool();
    m_dragTool = 0;
  }
}
drawPredefinedPath() [1/2]
void XsheetViewer::drawPredefinedPath (QPainter & p, PredefinedPath which, const CellPosition & pos, optional< QColor > fill, optional< QColor > outline) const
{
  QPoint xy         = positionToXY(pos);
  QPainterPath path = orientation()->path(which).translated(xy);
  if (fill) p.fillPath(path, QBrush(*fill));
  if (outline) {
    p.setPen(*outline);
    p.drawPath(path);
  }
}
drawPredefinedPath() [2/2]
void XsheetViewer::drawPredefinedPath (QPainter & p, PredefinedPath which, QPoint xy, optional< QColor > fill, optional< QColor > outline) const
{
  QPainterPath path = orientation()->path(which).translated(xy);
  if (fill) p.fillPath(path, QBrush(*fill));
  if (outline) {
    p.setPen(*outline);
    p.drawPath(path);
  }
}
enterEvent()
void XsheetViewer::enterEvent (QEvent *) override protected
{
  m_cellArea->onControlPressed(false);
  m_columnArea->onControlPressed(false);
  TApp *app = TApp::instance();
  app->setCurrentXsheetViewer(this);
}
flipOrientation()
void XsheetViewer::flipOrientation ()
{
  m_orientation = orientation()->next();
  int factor = (m_orientation->isVerticalTimeline()) ? m_frameZoomFactor : 100;
  TApp::instance()->getCurrentXsheet()->notifyZoomScaleChanged(factor);
  emit orientationChanged(orientation());
}
getActiveCameraColor()
QColor XsheetViewer::getActiveCameraColor () const inline
{ return m_ActiveCameraColor; }
getBGColor()
QColor XsheetViewer::getBGColor () const inline
{ return m_bgColor; }
getButton()
void XsheetViewer::getButton (const int & btype, QColor & bgColor, QImage & iconImage, bool isTimeline = false)
{
  switch (btype) {
  case PREVIEW_ON_XSHBUTTON:
    bgColor = (isTimeline) ? getTimelinePreviewButtonBgOnColor()
                           : getXsheetPreviewButtonBgOnColor();
    iconImage = (isTimeline) ? getTimelinePreviewButtonOnImage()
                             : getXsheetPreviewButtonOnImage();
    break;
  case PREVIEW_OFF_XSHBUTTON:
    bgColor = (isTimeline) ? getTimelinePreviewButtonBgOffColor()
                           : getXsheetPreviewButtonBgOffColor();
    iconImage = (isTimeline) ? getTimelinePreviewButtonOffImage()
                             : getXsheetPreviewButtonOffImage();
    break;
  case CAMSTAND_ON_XSHBUTTON:
    bgColor = (isTimeline) ? getTimelineCamstandButtonBgOnColor()
                           : getXsheetCamstandButtonBgOnColor();
    iconImage = (isTimeline) ? getTimelineCamstandButtonOnImage()
                             : getXsheetCamstandButtonOnImage();
    break;
  case CAMSTAND_TRANSP_XSHBUTTON:
    bgColor = (isTimeline) ? getTimelineCamstandButtonBgOnColor()
                           : getXsheetCamstandButtonBgOnColor();
    iconImage = (isTimeline) ? getTimelineCamstandButtonTranspImage()
                             : getXsheetCamstandButtonTranspImage();
    break;
  case CAMSTAND_OFF_XSHBUTTON:
    bgColor = (isTimeline) ? getTimelineCamstandButtonBgOffColor()
                           : getXsheetCamstandButtonBgOffColor();
    iconImage = (isTimeline) ? getTimelineCamstandButtonOffImage()
                             : getXsheetCamstandButtonOffImage();
    break;
  case LOCK_ON_XSHBUTTON:
    bgColor = (isTimeline) ? getTimelineLockButtonBgOnColor()
                           : getXsheetLockButtonBgOnColor();
    iconImage = (isTimeline) ? getTimelineLockButtonOnImage()
                             : getXsheetLockButtonOnImage();
    break;
  case LOCK_OFF_XSHBUTTON:
    bgColor = (isTimeline) ? getTimelineLockButtonBgOffColor()
                           : getXsheetLockButtonBgOffColor();
    iconImage = (isTimeline) ? getTimelineLockButtonOffImage()
                             : getXsheetLockButtonOffImage();
    break;
  case CONFIG_XSHBUTTON:
    bgColor = (isTimeline) ? getTimelineConfigButtonBgColor()
                           : getXsheetConfigButtonBgColor();
    iconImage = (isTimeline) ? getTimelineConfigButtonImage()
                             : getXsheetConfigButtonImage();
    break;
  default:
    bgColor = grey210;
    static QImage iconignored;
    iconImage = iconignored;
  }
}
getCellFocusColor()
QColor XsheetViewer::getCellFocusColor () const inline
{ return m_cellFocusColor; }
getCellKeyframeSelection()
TCellKeyframeSelection * XsheetViewer::getCellKeyframeSelection () const inline
{
    return m_cellKeyframeSelection;
  }
getCellSelection()
TCellSelection * XsheetViewer::getCellSelection () const inline
{
    return m_cellKeyframeSelection->getCellSelection();
  }
getCellTypeAndColors()
void XsheetViewer::getCellTypeAndColors (int & ltype, QColor & cellColor, QColor & sideColor, const TXshCell & cell, bool isSelected = false)
{
  if (cell.isEmpty())
    ltype = NO_XSHLEVEL;
  else {
    ltype = cell.m_level->getType();
    switch (ltype) {
    case TZI_XSHLEVEL:
    case OVL_XSHLEVEL:
      cellColor = (isSelected) ? getSelectedFullcolorColumnColor()
                               : getFullcolorColumnColor();
      sideColor = getFullcolorColumnBorderColor();
      break;
    case PLI_XSHLEVEL:
      cellColor = (isSelected) ? getSelectedVectorColumnColor()
                               : getVectorColumnColor();
      sideColor = getVectorColumnBorderColor();
      break;
    case TZP_XSHLEVEL:
      cellColor =
          (isSelected) ? getSelectedLevelColumnColor() : getLevelColumnColor();
      sideColor = getLevelColumnBorderColor();
      break;
    case ZERARYFX_XSHLEVEL:
      cellColor =
          (isSelected) ? getSelectedFxColumnColor() : getFxColumnColor();
      sideColor = getFxColumnBorderColor();
      break;
    case CHILD_XSHLEVEL:
      cellColor =
          (isSelected) ? getSelectedChildColumnColor() : getChildColumnColor();
      sideColor = getChildColumnBorderColor();
      break;
    case SND_XSHLEVEL:
      cellColor =
          (isSelected) ? m_selectedSoundColumnColor : m_soundColumnColor;
      sideColor = m_soundColumnBorderColor;
      break;
    case SND_TXT_XSHLEVEL:
      cellColor = (isSelected) ? getSelectedSoundTextColumnColor()
                               : getSoundTextColumnColor();
      sideColor = getSoundTextColumnBorderColor();
      break;
    case MESH_XSHLEVEL:
      cellColor =
          (isSelected) ? getSelectedMeshColumnColor() : getMeshColumnColor();
      sideColor = getMeshColumnBorderColor();
      break;
    case UNKNOWN_XSHLEVEL:
    case NO_XSHLEVEL:
    default:
      // non dovrebbe succedere
      cellColor = grey210;
      sideColor = grey150;
    }
  }
}
getChildColumnBorderColor()
QColor XsheetViewer::getChildColumnBorderColor () const inline
{ return m_childColumnBorderColor; }
getChildColumnColor()
QColor XsheetViewer::getChildColumnColor () const inline
{ return m_childColumnColor; }
getColumnColor()
void XsheetViewer::getColumnColor (QColor & color, QColor & sidecolor, int index, TXsheet * xsh)
{
  if (index < 0 || xsh->isColumnEmpty(index)) return;
  int r0, r1;
  xsh->getCellRange(index, r0, r1);
  if (0 <= r0 && r0 <= r1) {
    // column color depends on the level type in the top-most occupied cell
    if (xsh->getColumn(index)->getSoundColumn()) {
      color     = m_soundColumnColor;
      sideColor = m_soundColumnBorderColor;
    } else {
      TXshCell cell = xsh->getCell(r0, index);
      int ltype;
      getCellTypeAndColors(ltype, color, sideColor, cell);
    }
  }
  if (xsh->getColumn(index)->isMask()) color = QColor(255, 0, 255);
}
getColumnHeadPastelizer()
QColor XsheetViewer::getColumnHeadPastelizer () const inline
{ return m_columnHeadPastelizer; }
getColumnIconLineColor()
QColor XsheetViewer::getColumnIconLineColor () const inline
{ return m_columnIconLineColor; }
getColumnSelection()
TColumnSelection * XsheetViewer::getColumnSelection () const inline
{ return m_columnSelection; }
getCurrentColumn()
int XsheetViewer::getCurrentColumn () const
{
  return TApp::instance()->getCurrentColumn()->getColumnIndex();
}
getCurrentNoteIndex()
int XsheetViewer::getCurrentNoteIndex () const
{ return m_currentNoteIndex; }
getCurrentRow()
int XsheetViewer::getCurrentRow () const
{
  return TApp::instance()->getCurrentFrame()->getFrame();
}
getCurrentRowBgColor()
QColor XsheetViewer::getCurrentRowBgColor () const inline
{ return m_currentRowBgColor; }
getDarkBGColor()
QColor XsheetViewer::getDarkBGColor () const inline
{ return m_darkBgColor; }
getDarkLineColor()
QColor XsheetViewer::getDarkLineColor () const inline
{ return m_darkLineColor; }
getDragTool()
XsheetGUI::DragTool * XsheetViewer::getDragTool () const inline
{ return m_dragTool; };
getEmptyCellColor()
QColor XsheetViewer::getEmptyCellColor () const inline
{ return m_emptyCellColor; }
getEmptyColumnHeadColor()
QColor XsheetViewer::getEmptyColumnHeadColor () const inline
{ return m_emptyColumnHeadColor; }
getErrorTextColor()
QColor XsheetViewer::getErrorTextColor () const inline
{ return m_errorTextColor; }
getFoldedColumnBGColor()
QColor XsheetViewer::getFoldedColumnBGColor () const inline
{ return m_foldedColumnBGColor; }
getFoldedColumnLineColor()
QColor XsheetViewer::getFoldedColumnLineColor () const inline
{ return m_foldedColumnLineColor; }
getFrameDisplayStyle()
FrameDisplayStyle XsheetViewer::getFrameDisplayStyle () inline
{ return m_frameDisplayStyle; }
getFrameNumberWithLetters()
QString XsheetViewer::getFrameNumberWithLetters (int frame)
convert the last one digit of the frame number to alphabet Ex. 12 -> 1B 21 -> 2A 30 -> 3
{
  int letterNum = frame % 10;
  QChar letter;
  switch (letterNum) {
  case 0:
    letter = QChar();
    break;
  case 1:
    letter = 'A';
    break;
  case 2:
    letter = 'B';
    break;
  case 3:
    letter = 'C';
    break;
  case 4:
    letter = 'D';
    break;
  case 5:
    letter = 'E';
    break;
  case 6:
    letter = 'F';
    break;
  case 7:
    letter = 'G';
    break;
  case 8:
    letter = 'H';
    break;
  case 9:
    letter = 'I';
    break;
  default:
    letter = QChar();
    break;
  }
  QString number;
  if (frame >= 10) {
    number = QString::number(frame);
    number.chop(1);
  } else
    number = "0";
  return (QChar(letter).isNull()) ? number : number.append(letter);
}
getFrameRangeMarkerLineColor()
QColor XsheetViewer::getFrameRangeMarkerLineColor () const inline
{
    return m_frameRangeMarkerLineColor;
  }
getFrameZoomAdjustment
QPoint XsheetViewer::getFrameZoomAdjustment () slot
{
  // if (orientation()->isVerticalTimeline()) return 0;
  QRect frameRect = orientation()->rect(PredefinedRect::FRAME_HEADER);
  int adj;
  if (orientation()->isVerticalTimeline()) {
    adj = frameRect.height() -
          ((frameRect.height() * getFrameZoomFactor()) / 100) - 1;
    return QPoint(0, std::max(0, adj));
  } else {
    adj = frameRect.width() -
          ((frameRect.width() * getFrameZoomFactor()) / 100) - 1;
    return QPoint(std::max(0, adj), 0);
  }
}
getFrameZoomFactor
int XsheetViewer::getFrameZoomFactor () const slot
{
  if (orientation()->isVerticalTimeline())
    return 50 + (m_frameZoomFactor - 20) * 5 / 8;
  return m_frameZoomFactor;
}
getFullcolorColumnBorderColor()
QColor XsheetViewer::getFullcolorColumnBorderColor () const inline
{
    return m_fullcolorColumnBorderColor;
  }
getFullcolorColumnColor()
QColor XsheetViewer::getFullcolorColumnColor () const inline
{ return m_fullcolorColumnColor; }
getFxColumnBorderColor()
QColor XsheetViewer::getFxColumnBorderColor () const inline
{ return m_fxColumnBorderColor; }
getFxColumnColor()
QColor XsheetViewer::getFxColumnColor () const inline
{ return m_fxColumnColor; }
getKeyframeSelection()
TKeyframeSelection * XsheetViewer::getKeyframeSelection () const inline
{
    return m_cellKeyframeSelection->getKeyframeSelection();
  }
getLayerHeaderCamstandImage()
QImage XsheetViewer::getLayerHeaderCamstandImage () const inline
{
    return m_layerHeaderCamstandImage;
  }
getLayerHeaderCamstandOverImage()
QImage XsheetViewer::getLayerHeaderCamstandOverImage () const inline
{
    return m_layerHeaderCamstandOverImage;
  }
getLayerHeaderLockImage()
QImage XsheetViewer::getLayerHeaderLockImage () const inline
{ return m_layerHeaderLockImage; }
getLayerHeaderLockOverImage()
QImage XsheetViewer::getLayerHeaderLockOverImage () const inline
{
    return m_layerHeaderLockOverImage;
  }
getLayerHeaderPreviewImage()
QImage XsheetViewer::getLayerHeaderPreviewImage () const inline
{
    return m_layerHeaderPreviewImage;
  }
getLayerHeaderPreviewOverImage()
QImage XsheetViewer::getLayerHeaderPreviewOverImage () const inline
{
    return m_layerHeaderPreviewOverImage;
  }
getLevelColumnBorderColor()
QColor XsheetViewer::getLevelColumnBorderColor () const inline
{ return m_levelColumnBorderColor; }
getLevelColumnColor()
QColor XsheetViewer::getLevelColumnColor () const inline
{ return m_levelColumnColor; }
getLightBGColor()
QColor XsheetViewer::getLightBGColor () const inline
{ return m_lightBgColor; }
getLightLightBGColor()
QColor XsheetViewer::getLightLightBGColor () const inline
{ return m_lightLightBgColor; }
getLightLineColor()
QColor XsheetViewer::getLightLineColor () const inline
{ return m_lightLineColor; }
getMarkerLineColor()
QColor XsheetViewer::getMarkerLineColor () const inline
{ return m_markerLineColor; }
getMeshColumnBorderColor()
QColor XsheetViewer::getMeshColumnBorderColor () const inline
{ return m_meshColumnBorderColor; }
getMeshColumnColor()
QColor XsheetViewer::getMeshColumnColor () const inline
{ return m_meshColumnColor; }
getNotEmptyColumnColor()
QColor XsheetViewer::getNotEmptyColumnColor () const inline
{ return m_notEmptyColumnColor; }
getNotesWidget()
QList< XsheetGUI::NoteWidget * > XsheetViewer::getNotesWidget () const
{
  return m_noteWidgets;
}
getObjectId()
TStageObjectId XsheetViewer::getObjectId (int col) const
Restituisce la objectId corrispondente alla colonna col.
{
  TXsheet *xsh = getXsheet();
  if (col < 0) return TStageObjectId::CameraId(xsh->getCameraColumnIndex());
  return TStageObjectId::ColumnId(col);
}
getOnionSkinAreaBgColor()
QColor XsheetViewer::getOnionSkinAreaBgColor () const inline
{ return m_onionSkinAreaBgColor; }
getOtherCameraColor()
QColor XsheetViewer::getOtherCameraColor () const inline
{ return m_OtherCameraColor; }
getPaletteColumnBorderColor()
QColor XsheetViewer::getPaletteColumnBorderColor () const inline
{
    return m_paletteColumnBorderColor;
  }
getPaletteColumnColor()
QColor XsheetViewer::getPaletteColumnColor () const inline
{ return m_paletteColumnColor; }
getPlayRangeColor()
QColor XsheetViewer::getPlayRangeColor () const inline
{ return m_playRangeColor; }
getPreviewFrameTextColor()
QColor XsheetViewer::getPreviewFrameTextColor () const inline
{ return m_previewFrameTextColor; }
getReferenceColumnBorderColor()
QColor XsheetViewer::getReferenceColumnBorderColor () const inline
{
    return m_referenceColumnBorderColor;
  }
getReferenceColumnColor()
QColor XsheetViewer::getReferenceColumnColor () const inline
{ return m_referenceColumnColor; }
getScrubHeighlight()
void XsheetViewer::getScrubHeighlight (int & R0, int & R1)
{
  R0 = m_scrubRow0;
  R1 = m_scrubRow1;
  return;
}
getSelectedActiveCameraColor()
QColor XsheetViewer::getSelectedActiveCameraColor () const inline
{
    return m_SelectedActiveCameraColor;
  }
getSelectedChildColumnColor()
QColor XsheetViewer::getSelectedChildColumnColor () const inline
{
    return m_selectedChildColumnColor;
  }
getSelectedColumnHead()
QColor XsheetViewer::getSelectedColumnHead () const inline
{ return m_selectedColumnHead; }
getSelectedColumnTextColor()
QColor XsheetViewer::getSelectedColumnTextColor () const
{
  // get colors
  TPixel currentColumnPixel;
  Preferences::instance()->getCurrentColumnData(currentColumnPixel);
  QColor currentColumnColor((int)currentColumnPixel.r,
                            (int)currentColumnPixel.g,
                            (int)currentColumnPixel.b, 255);
  return currentColumnColor;
}
getSelectedEmptyCellColor()
QColor XsheetViewer::getSelectedEmptyCellColor () const inline
{ return m_selectedEmptyCellColor; }
getSelectedFullcolorColumnColor()
QColor XsheetViewer::getSelectedFullcolorColumnColor () const inline
{
    return m_selectedFullcolorColumnColor;
  }
getSelectedFxColumnColor()
QColor XsheetViewer::getSelectedFxColumnColor () const inline
{ return m_selectedFxColumnColor; }
getSelectedLevelColumnColor()
QColor XsheetViewer::getSelectedLevelColumnColor () const inline
{
    return m_selectedLevelColumnColor;
  }
getSelectedMeshColumnColor()
QColor XsheetViewer::getSelectedMeshColumnColor () const inline
{
    return m_selectedMeshColumnColor;
  }
getSelectedOtherCameraColor()
QColor XsheetViewer::getSelectedOtherCameraColor () const inline
{
    return m_SelectedOtherCameraColor;
  }
getSelectedPaletteColumnColor()
QColor XsheetViewer::getSelectedPaletteColumnColor () const inline
{
    return m_selectedPaletteColumnColor;
  }
getSelectedReferenceColumnColor()
QColor XsheetViewer::getSelectedReferenceColumnColor () const inline
{
    return m_selectedReferenceColumnColor;
  }
getSelectedSoundTextColumnColor()
QColor XsheetViewer::getSelectedSoundTextColumnColor () const inline
{
    return m_selectedSoundTextColumnColor;
  }
getSelectedVectorColumnColor()
QColor XsheetViewer::getSelectedVectorColumnColor () const inline
{
    return m_selectedVectorColumnColor;
  }
getSoundColumnHlColor()
QColor XsheetViewer::getSoundColumnHlColor () const inline
{ return m_soundColumnHlColor; }
getSoundColumnTrackColor()
QColor XsheetViewer::getSoundColumnTrackColor () const inline
{ return m_soundColumnTrackColor; }
getSoundTextColumnBorderColor()
QColor XsheetViewer::getSoundTextColumnBorderColor () const inline
{
    return m_soundTextColumnBorderColor;
  }
getSoundTextColumnColor()
QColor XsheetViewer::getSoundTextColumnColor () const inline
{ return m_soundTextColumnColor; }
getTextColor()
QColor XsheetViewer::getTextColor () const inline
{ return m_textColor; }
getTimelineCamstandButtonBgOffColor()
QColor XsheetViewer::getTimelineCamstandButtonBgOffColor () const inline
{
    return m_timelineCamstandButtonBgOffColor;
  }
getTimelineCamstandButtonBgOnColor()
QColor XsheetViewer::getTimelineCamstandButtonBgOnColor () const inline
{
    return m_timelineCamstandButtonBgOnColor;
  }
getTimelineCamstandButtonOffImage()
QImage XsheetViewer::getTimelineCamstandButtonOffImage () const inline
{
    return m_timelineCamstandButtonOffImage;
  }
getTimelineCamstandButtonOnImage()
QImage XsheetViewer::getTimelineCamstandButtonOnImage () const inline
{
    return m_timelineCamstandButtonOnImage;
  }
getTimelineCamstandButtonTranspImage()
QImage XsheetViewer::getTimelineCamstandButtonTranspImage () const inline
{
    return m_timelineCamstandButtonTranspImage;
  }
getTimelineConfigButtonBgColor()
QColor XsheetViewer::getTimelineConfigButtonBgColor () const inline
{
    return m_timelineConfigButtonBgColor;
  }
getTimelineConfigButtonImage()
QImage XsheetViewer::getTimelineConfigButtonImage () const inline
{
    return m_timelineConfigButtonImage;
  }
getTimelineIconLineColor()
QColor XsheetViewer::getTimelineIconLineColor () const inline
{ return m_timelineIconLineColor; }
getTimelineLockButtonBgOffColor()
QColor XsheetViewer::getTimelineLockButtonBgOffColor () const inline
{
    return m_timelineLockButtonBgOffColor;
  }
getTimelineLockButtonBgOnColor()
QColor XsheetViewer::getTimelineLockButtonBgOnColor () const inline
{
    return m_timelineLockButtonBgOnColor;
  }
getTimelineLockButtonOffImage()
QImage XsheetViewer::getTimelineLockButtonOffImage () const inline
{
    return m_timelineLockButtonOffImage;
  }
getTimelineLockButtonOnImage()
QImage XsheetViewer::getTimelineLockButtonOnImage () const inline
{
    return m_timelineLockButtonOnImage;
  }
getTimelinePreviewButtonBgOffColor()
QColor XsheetViewer::getTimelinePreviewButtonBgOffColor () const inline
{
    return m_timelinePreviewButtonBgOffColor;
  }
getTimelinePreviewButtonBgOnColor()
QColor XsheetViewer::getTimelinePreviewButtonBgOnColor () const inline
{
    return m_timelinePreviewButtonBgOnColor;
  }
getTimelinePreviewButtonOffImage()
QImage XsheetViewer::getTimelinePreviewButtonOffImage () const inline
{
    return m_timelinePreviewButtonOffImage;
  }
getTimelinePreviewButtonOnImage()
QImage XsheetViewer::getTimelinePreviewButtonOnImage () const inline
{
    return m_timelinePreviewButtonOnImage;
  }
getVectorColumnBorderColor()
QColor XsheetViewer::getVectorColumnBorderColor () const inline
{
    return m_vectorColumnBorderColor;
  }
getVectorColumnColor()
QColor XsheetViewer::getVectorColumnColor () const inline
{ return m_vectorColumnColor; }
getVerticalLineColor()
QColor XsheetViewer::getVerticalLineColor () const inline
{ return m_verticalLineColor; }
getVerticalLineHeadColor()
QColor XsheetViewer::getVerticalLineHeadColor () const inline
{ return m_verticalLineHeadColor; }
getXsheet()
TXsheet * XsheetViewer::getXsheet () const
{
  return TApp::instance()->getCurrentXsheet()->getXsheet();
}
getXsheetCamstandButtonBgOffColor()
QColor XsheetViewer::getXsheetCamstandButtonBgOffColor () const inline
{
    return m_xsheetCamstandButtonBgOffColor;
  }
getXsheetCamstandButtonBgOnColor()
QColor XsheetViewer::getXsheetCamstandButtonBgOnColor () const inline
{
    return m_xsheetCamstandButtonBgOnColor;
  }
getXsheetCamstandButtonOffImage()
QImage XsheetViewer::getXsheetCamstandButtonOffImage () const inline
{
    return m_xsheetCamstandButtonOffImage;
  }
getXsheetCamstandButtonOnImage()
QImage XsheetViewer::getXsheetCamstandButtonOnImage () const inline
{
    return m_xsheetCamstandButtonOnImage;
  }
getXsheetCamstandButtonTranspImage()
QImage XsheetViewer::getXsheetCamstandButtonTranspImage () const inline
{
    return m_xsheetCamstandButtonTranspImage;
  }
getXsheetColumnNameBgColor()
QColor XsheetViewer::getXsheetColumnNameBgColor () const inline
{
    return m_xsheetColumnNameBgColor;
  }
getXsheetConfigButtonBgColor()
QColor XsheetViewer::getXsheetConfigButtonBgColor () const inline
{
    return m_xsheetConfigButtonBgColor;
  }
getXsheetConfigButtonImage()
QImage XsheetViewer::getXsheetConfigButtonImage () const inline
{
    return m_xsheetConfigButtonImage;
  }
getXsheetDragBarHighlightColor()
QColor XsheetViewer::getXsheetDragBarHighlightColor () const inline
{
    return m_xsheetDragBarHighlightColor;
  }
getXsheetLayout()
QString XsheetViewer::getXsheetLayout () const inline
{ return m_xsheetLayout; }
getXsheetLockButtonBgOffColor()
QColor XsheetViewer::getXsheetLockButtonBgOffColor () const inline
{
    return m_xsheetLockButtonBgOffColor;
  }
getXsheetLockButtonBgOnColor()
QColor XsheetViewer::getXsheetLockButtonBgOnColor () const inline
{
    return m_xsheetLockButtonBgOnColor;
  }
getXsheetLockButtonOffImage()
QImage XsheetViewer::getXsheetLockButtonOffImage () const inline
{
    return m_xsheetLockButtonOffImage;
  }
getXsheetLockButtonOnImage()
QImage XsheetViewer::getXsheetLockButtonOnImage () const inline
{
    return m_xsheetLockButtonOnImage;
  }
getXsheetPreviewButtonBgOffColor()
QColor XsheetViewer::getXsheetPreviewButtonBgOffColor () const inline
{
    return m_xsheetPreviewButtonBgOffColor;
  }
getXsheetPreviewButtonBgOnColor()
QColor XsheetViewer::getXsheetPreviewButtonBgOnColor () const inline
{
    return m_xsheetPreviewButtonBgOnColor;
  }
getXsheetPreviewButtonOffImage()
QImage XsheetViewer::getXsheetPreviewButtonOffImage () const inline
{
    return m_xsheetPreviewButtonOffImage;
  }
getXsheetPreviewButtonOnImage()
QImage XsheetViewer::getXsheetPreviewButtonOnImage () const inline
{
    return m_xsheetPreviewButtonOnImage;
  }
hideEvent()
void XsheetViewer::hideEvent (QHideEvent *) override protected
{
  m_frameScroller.unregisterFrameScroller();
  TApp *app = TApp::instance();
  disconnect(app->getCurrentColumn(), SIGNAL(columnIndexSwitched()), this,
             SLOT(onCurrentColumnSwitched()));
  disconnect(app->getCurrentFrame(), SIGNAL(frameSwitched()), this,
             SLOT(onCurrentFrameSwitched()));
  disconnect(app->getCurrentFrame(), SIGNAL(scrubStopped()), this,
             SLOT(onScrubStopped()));
  disconnect(app->getCurrentObject(), SIGNAL(objectChanged(bool)), this,
             SLOT(updateAllAree(bool)));
  TSceneHandle *sceneHandle = app->getCurrentScene();
  disconnect(sceneHandle, SIGNAL(sceneSwitched()), this,
             SLOT(onSceneSwitched()));
  disconnect(sceneHandle, SIGNAL(nameSceneChanged()), this,
             SLOT(changeWindowTitle()));
  TXsheetHandle *xsheetHandle = app->getCurrentXsheet();
  disconnect(xsheetHandle, SIGNAL(xsheetSwitched()), this,
             SLOT(updateAllAree()));
  disconnect(xsheetHandle, SIGNAL(xsheetChanged()), this,
             SLOT(onXsheetChanged()));
  disconnect(xsheetHandle, SIGNAL(xsheetChanged()), this,
             SLOT(changeWindowTitle()));
  disconnect(app->getCurrentSelection(),
             SIGNAL(selectionSwitched(TSelection *, TSelection *)), this,
             SLOT(onSelectionSwitched(TSelection *, TSelection *)));
  disconnect(app->getCurrentSelection(), SIGNAL(selectionChanged(TSelection *)),
             this, SLOT(onSelectionChanged(TSelection *)));
  disconnect(app->getCurrentLevel(), SIGNAL(xshLevelSwitched(TXshLevel *)),
             this, SLOT(changeWindowTitle()));
  disconnect(IconGenerator::instance(), SIGNAL(iconGenerated()), this,
             SLOT(updateColumnArea()));
  xsheetHandle->notifyZoomScaleChanged(100);
}
isAutoPanning()
bool XsheetViewer::isAutoPanning () const inline
{
    return m_autoPanSpeed.x() != 0 || m_autoPanSpeed.y() != 0;
  }
isScrubHighlighted()
bool XsheetViewer::isScrubHighlighted (int row, int col)
{
  if (m_scrubCol == col && m_scrubRow0 <= row && row <= m_scrubRow1)
    return true;
  return false;
}
keyPressEvent()
void XsheetViewer::keyPressEvent (QKeyEvent * event) override protected
{
  struct Locals {
    XsheetViewer *m_this;
    void scrollVertTo(double y, const QRect &visibleRect) {
      int deltaY = (y < visibleRect.top()) ? y - visibleRect.top()
                                           : y - visibleRect.bottom();
      m_this->scroll(QPoint(0, deltaY));
    }
    void scrollHorizTo(double x, const QRect &visibleRect) {
      int deltaX = (x < visibleRect.left()) ? x - visibleRect.left()
                                            : x - visibleRect.right();
      m_this->scroll(QPoint(deltaX, 0));
    }
  } locals = {this};
  if (changeFrameSkippingHolds(event)) return;
  int frameCount = getXsheet()->getFrameCount();
  CellPosition now(getCurrentRow(), getCurrentColumn());
  CellPosition shift = orientation()->arrowShift(event->key());
  CellPosition stride(1, 1);  // stride in row and column axes
  TCellSelection *cellSel =
      dynamic_cast<TCellSelection *>(TSelection::getCurrent());
  int firstCol =
      Preferences::instance()->isXsheetCameraColumnVisible() ? -1 : 0;
  // Use arrow keys to shift the cell selection. Ctrl + arrow keys to resize the
  // selection range.
  if (Preferences::instance()->isUseArrowKeyToShiftCellSelectionEnabled() &&
      cellSel && !cellSel->isEmpty()) {
    int r0, c0, r1, c1;
    cellSel->getSelectedCells(r0, c0, r1, c1);
    stride.setFrame(cellSel->getSelectedCells().getRowCount());
    if (m_cellArea->isControlPressed()) {  // resize
      if (r0 == r1 && shift.frame() < 0) return;
      if (c0 == c1 && shift.layer() < firstCol) return;
      cellSel->selectCells(r0, c0, r1 + shift.frame(), c1 + shift.layer());
      updateCells();
      TApp::instance()->getCurrentSelection()->notifySelectionChanged();
      return;
    } else {  // shift
      CellPosition offset(shift * stride);
      int movedR0   = std::max(0, r0 + offset.frame());
      int movedC0   = std::max(firstCol, c0 + offset.layer());
      int diffFrame = movedR0 - r0;
      int diffLayer = movedC0 - c0;
      cellSel->selectCells(r0 + diffFrame, c0 + diffLayer, r1 + diffFrame,
                           c1 + diffLayer);
      TApp::instance()->getCurrentSelection()->notifySelectionChanged();
    }
  }
  if (shift) {
    now = now + shift * stride;
    now.ensureValid();
    if (now.layer() < firstCol) now.setLayer(firstCol);
    setCurrentRow(now.frame());
    setCurrentColumn(now.layer());
    return;
  }
  switch (int key = event->key()) {
  case Qt::Key_Control:
    // display the upper-directional smart tab only when the ctrl key is pressed
    m_cellArea->onControlPressed(true);
    m_columnArea->onControlPressed(true);
    m_layerFooterPanel->onControlPressed(true);
    break;
  default: {
    QRect visibleRect   = m_cellArea->visibleRegion().boundingRect();
    int visibleRowCount = visibleRect.height() / orientation()->cellHeight();
    switch (key) {
    case Qt::Key_PageUp:
      locals.scrollVertTo(
          visibleRect.top() - visibleRowCount * orientation()->cellHeight(),
          visibleRect);
      break;
    case Qt::Key_PageDown:
      locals.scrollVertTo(
          visibleRect.bottom() + visibleRowCount * orientation()->cellHeight(),
          visibleRect);
      break;
    case Qt::Key_Home:
      if (orientation()->isVerticalTimeline())
        locals.scrollVertTo(0, visibleRect);
      else
        locals.scrollHorizTo(0, visibleRect);
      break;
    case Qt::Key_End:
      if (orientation()->isVerticalTimeline()) {
        int y = (((frameCount + 1) * orientation()->cellHeight()) *
                 getFrameZoomFactor()) /
                100;
        locals.scrollVertTo(y, visibleRect);
      } else {
        int x = (((frameCount + 1) * orientation()->cellWidth()) *
                 getFrameZoomFactor()) /
                100;
        locals.scrollHorizTo(x, visibleRect);
      }
      break;
    }
    break;
  }
  }
}
keyReleaseEvent()
void XsheetViewer::keyReleaseEvent (QKeyEvent * event) override protected
{
  if (event->key() == Qt::Key_Control) {
    m_cellArea->onControlPressed(false);
    m_columnArea->onControlPressed(false);
    m_layerFooterPanel->onControlPressed(false);
  }
}
load()
void XsheetViewer::load (QSettings & settings) override virtual
Implements SaveLoadQSettings.
{
  QVariant zoomFactor = settings.value("frameZoomFactor");
  QVariant name       = settings.value("orientation");
  if (zoomFactor.canConvert(QVariant::Int)) {
    m_frameZoomFactor = zoomFactor.toInt();
    m_layerFooterPanel->setZoomSliderValue(m_frameZoomFactor);
  }
  if (name.canConvert(QVariant::String)) {
    m_orientation = Orientations::byName(name.toString());
    emit orientationChanged(orientation());
  }
}
onCurrentColumnSwitched
void XsheetViewer::onCurrentColumnSwitched () slot
{
  int col           = TApp::instance()->getCurrentColumn()->getColumnIndex();
  QRect visibleRect = m_columnArea->visibleRegion().boundingRect();
  if (visibleRect.isEmpty()) {
    m_isCurrentColumnSwitched = true;
    return;
  }
  m_isCurrentColumnSwitched = false;
  scrollToColumn(col);
}
onCurrentFrameSwitched
void XsheetViewer::onCurrentFrameSwitched () slot
{
  int row           = TApp::instance()->getCurrentFrame()->getFrame();
  QRect visibleRect = m_cellArea->visibleRegion().boundingRect();
  if (visibleRect.isEmpty()) {
    m_isCurrentFrameSwitched = true;
    return;
  }
  m_isCurrentFrameSwitched = false;
  scrollToRow(row);
}
onOrientationChanged
void XsheetViewer::onOrientationChanged (const Orientation * newOrientation) slot
{
  disconnectScrollBars();
  positionSections();
  m_frameScroller.setOrientation(newOrientation);
  refreshContentSize(0, 0);
  connectScrollBars();
  update();
}
onPlayingStatusChanged
void XsheetViewer::onPlayingStatusChanged () slot
{
  if (!Preferences::instance()->isXsheetAutopanEnabled())
    onCurrentFrameSwitched();
}
onPreferenceChanged
void XsheetViewer::onPreferenceChanged (const QString & prefName) slot
{
  if (prefName == "XSheetToolbar") {
    positionSections();
    refreshContentSize(0, 0);
  } else if (prefName == "XsheetCamera") {
    refreshContentSize(0, 0);
  }
}
onPrepareToScrollOffset
void XsheetViewer::onPrepareToScrollOffset (const QPointF & offset) slot
{
  refreshContentSize((int)offset.x(), (int)offset.y());
}
onSceneSwitched
void XsheetViewer::onSceneSwitched () slot
{
  refreshContentSize(0, 0);
  updateAreeSize();
  updateAllAree();
  clearNoteWidgets();
  m_noteArea->updateButtons();
}
onScrubStopped
void XsheetViewer::onScrubStopped () slot
{
  resetScrubHighlight();
  updateCells();
}
onSelectionChanged
void XsheetViewer::onSelectionChanged (TSelection * selection) slot
update display of the cell selection range in title bar
{
  if ((TSelection *)getCellSelection() == selection) {
    changeWindowTitle();
    if (Preferences::instance()->isInputCellsWithoutDoubleClickingEnabled()) {
      TCellSelection *cellSel = getCellSelection();
      if (cellSel->isEmpty())
        m_cellArea->hideRenameField();
      else
        m_cellArea->showRenameField(
            cellSel->getSelectedCells().m_r0, cellSel->getSelectedCells().m_c0,
            cellSel->getSelectedCells().getColCount() > 1);
    }
  }
}
References changeWindowTitle().
onSelectionSwitched
void XsheetViewer::onSelectionSwitched (TSelection * oldSelection, TSelection * newSelection) slot
{
  if ((TSelection *)getCellSelection() == oldSelection) {
    m_cellArea->update(m_cellArea->visibleRegion());
    m_rowArea->update(m_rowArea->visibleRegion());
    changeWindowTitle();
  } else if ((TSelection *)m_columnSelection == oldSelection)
    m_columnArea->update(m_columnArea->visibleRegion());
}
onXsheetChanged
void XsheetViewer::onXsheetChanged () slot
{
  refreshContentSize(0, 0);
  updateAllAree();
}
onZoomScrollAdjust
void XsheetViewer::onZoomScrollAdjust (QPointF & offset, bool toZoom) slot
{
  double frameZoomFactor = (double)getFrameZoomFactor();
  if (orientation()->isVerticalTimeline()) {
    // toZoom = true: Adjust standardized offset down to zoom factor
    // toZoom = false: Adjust zoomed offset up to standardized offset
    double newY;
    if (toZoom)
      newY = (offset.y() * frameZoomFactor) / 100.0;
    else
      newY = (offset.y() * 100.0) / frameZoomFactor;
    offset.setY(newY);
  } else {
    // toZoom = true: Adjust standardized offset down to zoom factor
    // toZoom = false: Adjust zoomed offset up to standardized offset
    double newX;
    if (toZoom)
      newX = (offset.x() * frameZoomFactor) / 100.0;
    else
      newX = (offset.x() * 100.0) / frameZoomFactor;
    offset.setX(newX);
  }
}
orientation()
const Orientation * XsheetViewer::orientation () const
{
  if (!m_orientation) throw std::runtime_error("!m_orientation");
  return m_orientation;
}
positionSections
void XsheetViewer::positionSections () slot
{
  if (!isVisible()) return;
  const Orientation *o = orientation();
  QRect size           = QRect(QPoint(0, 0), geometry().size());
  NumberRange allLayer = o->layerSide(size);
  NumberRange allFrame = o->frameSide(size);
  NumberRange headerLayer = o->range(PredefinedRange::HEADER_LAYER);
  NumberRange headerFrame = o->range(PredefinedRange::HEADER_FRAME);
  NumberRange bodyLayer(headerLayer.to(), allLayer.to());
  NumberRange bodyFrame(headerFrame.to(), allFrame.to());
  if (Preferences::instance()->isShowXSheetToolbarEnabled()) {
    m_toolbar->showToolbar(true);
    int w = visibleRegion().boundingRect().width();
    m_toolbarScrollArea->setGeometry(0, 0, w, XsheetGUI::TOOLBAR_HEIGHT);
    m_toolbar->setFixedWidth(w);
    if (o->isVerticalTimeline()) {
      headerFrame = headerFrame.adjusted(XsheetGUI::TOOLBAR_HEIGHT,
                                         XsheetGUI::TOOLBAR_HEIGHT);
      bodyFrame   = bodyFrame.adjusted(XsheetGUI::TOOLBAR_HEIGHT, 0);
    } else {
      headerLayer = headerLayer.adjusted(XsheetGUI::TOOLBAR_HEIGHT,
                                         XsheetGUI::TOOLBAR_HEIGHT);
      bodyLayer   = bodyLayer.adjusted(XsheetGUI::TOOLBAR_HEIGHT, 0);
    }
  } else {
    m_toolbar->showToolbar(false);
  }
  m_noteScrollArea->setGeometry(o->frameLayerRect(headerFrame, headerLayer));
  m_cellScrollArea->setGeometry(o->frameLayerRect(bodyFrame, bodyLayer));
  m_columnScrollArea->setGeometry(
      o->frameLayerRect(headerFrame.adjusted(-1, -1),
                        bodyLayer.adjusted(0, -XsheetGUI::SCROLLBAR_WIDTH)));
  m_rowScrollArea->setGeometry(o->frameLayerRect(
      bodyFrame.adjusted(0, -XsheetGUI::SCROLLBAR_WIDTH), headerLayer));
  if (o->isVerticalTimeline()) {
    m_layerFooterPanel->setGeometry(m_columnScrollArea->geometry().right() + 1,
                                    m_columnScrollArea->geometry().top(), 14,
                                    m_columnScrollArea->height());
  } else {
    m_layerFooterPanel->setGeometry(0,
                                    m_columnScrollArea->geometry().bottom() + 1,
                                    m_columnScrollArea->width(), 14);
  }
  m_layerFooterPanel->showOrHide(o);
}
positionToXY()
QPoint XsheetViewer::positionToXY (const CellPosition & pos) const
{
  const Orientation *o = orientation();
  TXsheet *xsh         = getXsheet();
  if (!xsh) return QPoint(0, 0);
  ColumnFan *fan  = xsh->getColumnFan(o);
  QPoint usePoint = o->positionToXY(pos, fan);
  if (o->isVerticalTimeline())
    usePoint.setY((usePoint.y() * getFrameZoomFactor()) / 100);
  else
    usePoint.setX((usePoint.x() * getFrameZoomFactor()) / 100);
  if (o->isVerticalTimeline()) return usePoint;
  // For timeline mode, we need to base the Y axis on the bottom of the column
  // area
  // since the layers are flipped
  usePoint.setY(
      usePoint.y() - o->cellHeight() +
      (fan->isActive(pos.layer()) ? o->cellHeight() : o->foldedCellSize()));
  int columnCount = std::max(1, xsh->getColumnCount());
  int colsHeight  = o->colToLayerAxis(columnCount, fan);
  if (colsHeight)
    usePoint.setY(colsHeight - usePoint.y() - o->cellHeight());
  else
    usePoint.setY(0);
  return usePoint;
}
rangeToXYRect()
QRect XsheetViewer::rangeToXYRect (const CellRange & range) const
{
  QPoint from = positionToXY(range.from());
  QPoint to   = positionToXY(range.to());
  QPoint topLeft =
      QPoint(std::min(from.x(), to.x()), std::min(from.y(), to.y()));
  QPoint bottomRight =
      QPoint(std::max(from.x(), to.x()), std::max(from.y(), to.y()));
  return QRect(topLeft, bottomRight);
}
refreshContentSize()
bool XsheetViewer::refreshContentSize (int scrollDx, int scrollDy)
{
  QSize viewportSize = m_cellScrollArea->viewport()->size();
  QPoint offset      = m_cellArea->pos();
  offset             = QPoint(std::min(0, offset.x() - dx),
                  std::min(0, offset.y() - dy));  // what?
  TXsheet *xsh    = getXsheet();
  int frameCount  = xsh ? xsh->getFrameCount() : 0;
  int columnCount = xsh ? xsh->getColumnCount() : 0;
  QPoint contentSize;
  if (m_orientation->isVerticalTimeline())
    contentSize = positionToXY(CellPosition(frameCount + 1, columnCount + 1));
  else {
    int firstCol =
        Preferences::instance()->isXsheetCameraColumnVisible() ? -1 : 0;
    contentSize = positionToXY(CellPosition(frameCount + 1, firstCol));
    ColumnFan *fan = xsh->getColumnFan(m_orientation);
    contentSize.setY(contentSize.y() + 1 +
                     (fan->isActive(firstCol)
                          ? m_orientation->cellHeight()
                          : m_orientation->foldedCellSize()));
  }
  QSize actualSize(contentSize.x(), contentSize.y());
  int x = viewportSize.width() - offset.x();  // wtf is going on
  int y = viewportSize.height() - offset.y();
  if (x > actualSize.width()) actualSize.setWidth(x);
  if (m_orientation->isVerticalTimeline() && y > actualSize.height())
    actualSize.setHeight(y);
  if (actualSize == m_cellArea->size())
    return false;
  else {
    const Orientation *o    = orientation();
    NumberRange allLayer    = o->layerSide(QRect(QPoint(0, 0), actualSize));
    NumberRange allFrame    = o->frameSide(QRect(QPoint(0, 0), actualSize));
    NumberRange headerLayer = o->range(PredefinedRange::HEADER_LAYER);
    NumberRange headerFrame = o->range(PredefinedRange::HEADER_FRAME);
    m_isComputingSize = true;
    m_noteArea->setFixedSize(o->rect(PredefinedRect::NOTE_AREA).size());
    m_cellArea->setFixedSize(actualSize);
    m_rowArea->setFixedSize(o->frameLayerRect(allFrame, headerLayer).size());
    m_columnArea->setFixedSize(o->frameLayerRect(headerFrame, allLayer).size());
    m_isComputingSize = false;
    return true;
  }
}
resetScrubHighlight()
void XsheetViewer::resetScrubHighlight ()
{
  m_scrubCol = m_scrubRow0 = m_scrubRow1 = -1;
  return;
}
resetXsheetNotes
void XsheetViewer::resetXsheetNotes () slot
{ m_noteArea->updateButtons(); }
resizeEvent()
void XsheetViewer::resizeEvent (QResizeEvent * event) override protected
{
  positionSections();
  //(New Layout Manager) introduced automatic refresh
  refreshContentSize(
      0,
      0);  // Don't updateAreeSize because you have to account scrollbars
  updateAllAree();
}
rowToFrameAxis()
int XsheetViewer::rowToFrameAxis (int frame) const
{
  int result = orientation()->rowToFrameAxis(frame);
  // if (!orientation()->isVerticalTimeline())
  result = (result * getFrameZoomFactor()) / 100;
  return result;
}
save()
void XsheetViewer::save (QSettings & settings) const override virtual
Implements SaveLoadQSettings.
{
  settings.setValue("orientation", orientation()->name());
  settings.setValue("frameZoomFactor", m_frameZoomFactor);
}
scroll()
void XsheetViewer::scroll (QPoint delta)
{
  int x = delta.x();
  int y = delta.y();
  int valueH    = m_cellScrollArea->horizontalScrollBar()->value() + x;
  int valueV    = m_cellScrollArea->verticalScrollBar()->value() + y;
  int maxValueH = m_cellScrollArea->horizontalScrollBar()->maximum();
  int maxValueV = m_cellScrollArea->verticalScrollBar()->maximum();
  bool notUpdateSizeH = maxValueH > valueH && x >= 0;
  bool notUpdateSizeV = maxValueV > valueV && y >= 0;
  if (!notUpdateSizeH && !notUpdateSizeV)  // Resize orizzontale e verticale
    refreshContentSize(x, y);
  else if (notUpdateSizeH && !notUpdateSizeV)  // Resize verticale
    refreshContentSize(0, y);
  else if (!notUpdateSizeH && notUpdateSizeV)  // Resize orizzontale
    refreshContentSize(x, 0);
  // Recheck in case refreshContentSize changed the max
  if (!notUpdateSizeH)
    maxValueH = m_cellScrollArea->horizontalScrollBar()->maximum();
  if (!notUpdateSizeV)
    maxValueV = m_cellScrollArea->verticalScrollBar()->maximum();
  if (valueH > maxValueH && x > 0)  // Se il valore e' maggiore del max e x>0
                                    // scrollo al massimo valore orizzontale
    valueH = m_cellScrollArea->horizontalScrollBar()->maximum();
  if (valueV > maxValueV && y > 0)  // Se il valore e' maggiore del max e y>0
                                    // scrollo al massimo valore verticale
    valueV = m_cellScrollArea->verticalScrollBar()->maximum();
  m_cellScrollArea->horizontalScrollBar()->setValue(valueH);
  m_cellScrollArea->verticalScrollBar()->setValue(valueV);
}
scrollTo()
void XsheetViewer::scrollTo (int row, int col)
scroll the cell area to make a cell at (row,col) visible
{
  QRect visibleRect = m_cellArea->visibleRegion().boundingRect();
  QPoint topLeft    = positionToXY(CellPosition(row, col));
  QRect cellRect(
      topLeft, QSize(orientation()->cellWidth(), orientation()->cellHeight()));
  int deltaX = 0;
  int deltaY = 0;
  if (cellRect.left() < visibleRect.left())
    deltaX = cellRect.left() - visibleRect.left();
  else if (cellRect.right() > visibleRect.right())
    deltaX = cellRect.left() - visibleRect.left();
  if (cellRect.top() < visibleRect.top())
    deltaY = cellRect.top() - visibleRect.top();
  else if (cellRect.bottom() > visibleRect.bottom())
    deltaY = cellRect.bottom() - visibleRect.bottom();
  if (deltaX != 0 || deltaY != 0) {
    scroll(QPoint(deltaX, deltaY));
  }
}
scrollToColumn()
void XsheetViewer::scrollToColumn (int col) protected
{
  int colNext = col + (m_orientation->isVerticalTimeline() ? 1 : -1);
  if (colNext < 0) colNext = -1;
  int x0 = columnToLayerAxis(col);
  int x1 = columnToLayerAxis(colNext);
  if (orientation()->isVerticalTimeline())
    scrollToHorizontalRange(x0, x1);
  else {
    if (colNext == col) x1 += m_orientation->cellHeight();
    scrollToVerticalRange(x0, x1);
  }
}
scrollToHorizontalRange()
void XsheetViewer::scrollToHorizontalRange (int x0, int x1) protected
{
  QRect visibleRect = m_cellArea->visibleRegion().boundingRect();
  if (visibleRect.isEmpty()) return;
  int visibleLeft  = visibleRect.left();
  int visibleRight = visibleRect.right();
  if (visibleLeft > x0) {  // If they are out of left visible region
    int deltaX = x0 - visibleLeft;
    if (!TApp::instance()->getCurrentFrame()->isPlaying() ||
        Preferences::instance()->isXsheetAutopanEnabled()) {
      scroll(QPoint(deltaX, 0));
      return;
    }
  }
  if (visibleRight < x1) {  // If they are out of right visible region
    int deltaX = x1 + 2 - visibleRight;
    if (!TApp::instance()->getCurrentFrame()->isPlaying() ||
        Preferences::instance()->isXsheetAutopanEnabled()) {
      scroll(QPoint(deltaX, 0));
      return;
    }
  }
  if (orientation()->isVerticalTimeline())
    updateCellColumnAree();
  else
    updateCellRowAree();
}
scrollToRow()
void XsheetViewer::scrollToRow (int row) protected
{
  int y0 = rowToFrameAxis(row);
  int y1 = rowToFrameAxis(row + 1);
  if (orientation()->isVerticalTimeline())
    scrollToVerticalRange(y0, y1);
  else
    scrollToHorizontalRange(y0, y1);
}
scrollToVerticalRange()
void XsheetViewer::scrollToVerticalRange (int y0, int y1) protected
{
  int yMin          = std::min(y0, y1);
  int yMax          = std::max(y0, y1);
  QRect visibleRect = m_cellArea->visibleRegion().boundingRect();
  if (visibleRect.isEmpty()) return;
  int visibleTop    = visibleRect.top();
  int visibleBottom = visibleRect.bottom();
  if (visibleTop > yMin) {  // If they are out of top visible region
    int deltaY = yMin - visibleTop;
    if (!TApp::instance()->getCurrentFrame()->isPlaying() ||
        Preferences::instance()->isXsheetAutopanEnabled()) {
      scroll(QPoint(0, deltaY));
      return;
    }
  }
  if (visibleBottom < yMax) {  // If they are out of bottom visible region
    int deltaY = yMax + 2 - visibleBottom;
    if (!TApp::instance()->getCurrentFrame()->isPlaying() ||
        Preferences::instance()->isXsheetAutopanEnabled()) {
      scroll(QPoint(0, deltaY));
      return;
    }
  }
  if (orientation()->isVerticalTimeline())
    updateCellRowAree();
  else
    updateCellColumnAree();
}
setActiveCameraColor()
void XsheetViewer::setActiveCameraColor (const QColor & color) inline
{
    m_ActiveCameraColor = color;
  }
setAutoPanSpeed() [1/2]
void XsheetViewer::setAutoPanSpeed (const QPoint & speed)
{
  bool wasAutoPanning = isAutoPanning();
  m_autoPanSpeed      = speed;
  if (isAutoPanning() && !wasAutoPanning && m_timerId == 0)
    m_timerId = startTimer(40);
  else if (!isAutoPanning() && wasAutoPanning && m_timerId != 0) {
    killTimer(m_timerId);
    m_timerId = 0;
  }
}
setAutoPanSpeed() [2/2]
void XsheetViewer::setAutoPanSpeed (const QRect & widgetBounds, const QPoint & mousePos)
{
  QPoint speed;
  int limit = 100, factor = 30;
  if (mousePos.x() < widgetBounds.left())
    speed.setX(-getAutoPanSpeed(widgetBounds.left() - mousePos.x()));
  else if (mousePos.x() > widgetBounds.right())
    speed.setX(getAutoPanSpeed(mousePos.x() - widgetBounds.right()));
  if (mousePos.y() < widgetBounds.top())
    speed.setY(-getAutoPanSpeed(widgetBounds.top() - mousePos.y()));
  else if (mousePos.y() > widgetBounds.bottom())
    speed.setY(getAutoPanSpeed(mousePos.y() - widgetBounds.bottom()));
  setAutoPanSpeed(speed);
  m_lastAutoPanPos = mousePos;
}
setBGColor()
void XsheetViewer::setBGColor (const QColor & color) inline
{ m_bgColor = color; }
setCellFocusColor()
void XsheetViewer::setCellFocusColor (const QColor & color) inline
{ m_cellFocusColor = color; }
setChildColumnBorderColor()
void XsheetViewer::setChildColumnBorderColor (const QColor & color) inline
{
    m_childColumnBorderColor = color;
  }
setChildColumnColor()
void XsheetViewer::setChildColumnColor (const QColor & color) inline
{ m_childColumnColor = color; }
setColumnHeadPastelizer()
void XsheetViewer::setColumnHeadPastelizer (const QColor & color) inline
{
    m_columnHeadPastelizer = color;
  }
setColumnIconLineColor()
void XsheetViewer::setColumnIconLineColor (const QColor & color) inline
{
    m_columnIconLineColor = color;
  }
setCurrentColumn()
void XsheetViewer::setCurrentColumn (int col)
{
  TColumnHandle *columnHandle = TApp::instance()->getCurrentColumn();
  if (col != columnHandle->getColumnIndex()) {
    columnHandle->setColumnIndex(col);
    // E' necessario per il caso in cui si passa da colonna di camera a altra
    // colonna
    // o nel caso in cui si passa da una spline a una colonna.
    TObjectHandle *objectHandle = TApp::instance()->getCurrentObject();
    if (col >= 0 && objectHandle->isSpline()) objectHandle->setIsSpline(false);
    updateCellColumnAree();
    if (col >= 0) {
      objectHandle->setObjectId(TStageObjectId::ColumnId(col));
      TXsheet *xsh       = getXsheet();
      TXshColumn *column = xsh->getColumn(col);
      if (!column || !column->getZeraryFxColumn()) return;
      TFx *fx = column->getZeraryFxColumn()->getZeraryColumnFx();
      TApp::instance()->getCurrentFx()->setFx(fx);
    }
    return;
  }
}
setCurrentNoteIndex()
void XsheetViewer::setCurrentNoteIndex (int currentNoteIndex)
{
  m_currentNoteIndex = currentNoteIndex;
  m_noteArea->updateButtons();
  if (currentNoteIndex < 0) return;
  TXshNoteSet *notes = getXsheet()->getNotes();
  int row            = notes->getNoteRow(currentNoteIndex);
  int col            = notes->getNoteCol(currentNoteIndex);
  TPointD pos        = notes->getNotePos(currentNoteIndex);
  QPoint topLeft = positionToXY(CellPosition(row, col)) +
                   QPoint(pos.x, pos.y);  // actually xy
  QSize size(XsheetGUI::NoteWidth, XsheetGUI::NoteHeight);
  QRect noteRect(topLeft, size);
  scrollToHorizontalRange(noteRect.left(), noteRect.right());
  scrollToVerticalRange(noteRect.top(), noteRect.bottom());
}
setCurrentRow()
void XsheetViewer::setCurrentRow (int row)
{
  // POTREBBE NON ESSER PIU' NECESSARIO CON LE NUOVE MODIFICHE PER CLEANUP A
  // COLORI
  /*TFrameHandle* frameHandle = TApp::instance()->getCurrentFrame();
if(row == frameHandle->getFrameIndex() && frameHandle->getFrameType() ==
TFrameHandle::SceneFrame)
{
//E' necessario per il caso in cui la paletta corrente e' la paletta di cleanup.
TPaletteHandle* levelPaletteHandle =
TApp::instance()->getPaletteController()->getCurrentLevelPalette();
TXshLevel *xl = TApp::instance()->getCurrentLevel()->getLevel();
if(xl && xl->getSimpleLevel())
                  levelPaletteHandle->setPalette(xl->getSimpleLevel()->getPalette());
else if(xl && xl->getPaletteLevel())
                  levelPaletteHandle->setPalette(xl->getPaletteLevel()->getPalette());
else
levelPaletteHandle->setPalette(0);
return;
}
frameHandle->setFrame(row);*/
  TApp::instance()->getCurrentFrame()->setFrame(row);
}
setCurrentRowBgColor()
void XsheetViewer::setCurrentRowBgColor (const QColor & color) inline
{
    m_currentRowBgColor = color;
  }
setDarkBGColor()
void XsheetViewer::setDarkBGColor (const QColor & color) inline
{ m_darkBgColor = color; }
setDarkLineColor()
void XsheetViewer::setDarkLineColor (const QColor & color) inline
{ m_darkLineColor = color; }
setDragTool()
void XsheetViewer::setDragTool (XsheetGUI::DragTool * dragTool)
{
  assert(m_dragTool == 0);
  m_dragTool = dragTool;
}
setEmptyCellColor()
void XsheetViewer::setEmptyCellColor (const QColor & color) inline
{ m_emptyCellColor = color; }
setEmptyColumnHeadColor()
void XsheetViewer::setEmptyColumnHeadColor (const QColor & color) inline
{
    m_emptyColumnHeadColor = color;
  }
setErrorTextColor()
void XsheetViewer::setErrorTextColor (const QColor & color) inline
{ m_errorTextColor = color; }
setFoldedColumnBGColor()
void XsheetViewer::setFoldedColumnBGColor (const QColor & color) inline
{
    m_foldedColumnBGColor = color;
  }
setFoldedColumnLineColor()
void XsheetViewer::setFoldedColumnLineColor (const QColor & color) inline
{
    m_foldedColumnLineColor = color;
  }
setFrameDisplayStyle()
void XsheetViewer::setFrameDisplayStyle (FrameDisplayStyle style)
{
  m_frameDisplayStyle              = style;
  FrameDisplayStyleInXsheetRowArea = (int)style;
}
setFrameRangeMarkerLineColor()
void XsheetViewer::setFrameRangeMarkerLineColor (const QColor & color) inline
{
    m_frameRangeMarkerLineColor = color;
  }
setFrameZoomFactor
void XsheetViewer::setFrameZoomFactor (int f) inline slot
{ m_frameZoomFactor = f; }
setFullcolorColumnBorderColor()
void XsheetViewer::setFullcolorColumnBorderColor (const QColor & color) inline
{
    m_fullcolorColumnBorderColor = color;
  }
setFullcolorColumnColor()
void XsheetViewer::setFullcolorColumnColor (const QColor & color) inline
{
    m_fullcolorColumnColor = color;
  }
setFxColumnBorderColor()
void XsheetViewer::setFxColumnBorderColor (const QColor & color) inline
{
    m_fxColumnBorderColor = color;
  }
setFxColumnColor()
void XsheetViewer::setFxColumnColor (const QColor & color) inline
{ m_fxColumnColor = color; }
setLayerHeaderCamstandImage()
void XsheetViewer::setLayerHeaderCamstandImage (const QImage & image) inline
{
    m_layerHeaderCamstandImage = image;
  }
setLayerHeaderCamstandOverImage()
void XsheetViewer::setLayerHeaderCamstandOverImage (const QImage & image) inline
{
    m_layerHeaderCamstandOverImage = image;
  }
setLayerHeaderLockImage()
void XsheetViewer::setLayerHeaderLockImage (const QImage & image) inline
{
    m_layerHeaderLockImage = image;
  }
setLayerHeaderLockOverImage()
void XsheetViewer::setLayerHeaderLockOverImage (const QImage & image) inline
{
    m_layerHeaderLockOverImage = image;
  }
setLayerHeaderPreviewImage()
void XsheetViewer::setLayerHeaderPreviewImage (const QImage & image) inline
{
    m_layerHeaderPreviewImage = image;
  }
setLayerHeaderPreviewOverImage()
void XsheetViewer::setLayerHeaderPreviewOverImage (const QImage & image) inline
{
    m_layerHeaderPreviewOverImage = image;
  }
setLevelColumnBorderColor()
void XsheetViewer::setLevelColumnBorderColor (const QColor & color) inline
{
    m_levelColumnBorderColor = color;
  }
setLevelColumnColor()
void XsheetViewer::setLevelColumnColor (const QColor & color) inline
{ m_levelColumnColor = color; }
setLightBGColor()
void XsheetViewer::setLightBGColor (const QColor & color) inline
{ m_lightBgColor = color; }
setLightLightBGColor()
void XsheetViewer::setLightLightBGColor (const QColor & color) inline
{
    m_lightLightBgColor = color;
  }
setLightLineColor()
void XsheetViewer::setLightLineColor (const QColor & color) inline
{ m_lightLineColor = color; }
setMarkerLineColor()
void XsheetViewer::setMarkerLineColor (const QColor & color) inline
{ m_markerLineColor = color; }
setMeshColumnBorderColor()
void XsheetViewer::setMeshColumnBorderColor (const QColor & color) inline
{
    m_meshColumnBorderColor = color;
  }
setMeshColumnColor()
void XsheetViewer::setMeshColumnColor (const QColor & color) inline
{ m_meshColumnColor = color; }
setNotEmptyColumnColor()
void XsheetViewer::setNotEmptyColumnColor (const QColor & color) inline
{
    m_notEmptyColumnColor = color;
  }
setOnionSkinAreaBgColor()
void XsheetViewer::setOnionSkinAreaBgColor (const QColor & color) inline
{
    m_onionSkinAreaBgColor = color;
  }
setOtherCameraColor()
void XsheetViewer::setOtherCameraColor (const QColor & color) inline
{ m_OtherCameraColor = color; }
setPaletteColumnBorderColor()
void XsheetViewer::setPaletteColumnBorderColor (const QColor & color) inline
{
    m_paletteColumnBorderColor = color;
  }
setPaletteColumnColor()
void XsheetViewer::setPaletteColumnColor (const QColor & color) inline
{
    m_paletteColumnColor = color;
  }
setPlayRangeColor()
void XsheetViewer::setPlayRangeColor (const QColor & color) inline
{ m_playRangeColor = color; }
setPreviewFrameTextColor()
void XsheetViewer::setPreviewFrameTextColor (const QColor & color) inline
{
    m_previewFrameTextColor = color;
  }
setQtModifiers()
void XsheetViewer::setQtModifiers (Qt::KeyboardModifiers value) inline
{ m_qtModifiers = value; }
setReferenceColumnBorderColor()
void XsheetViewer::setReferenceColumnBorderColor (const QColor & color) inline
{
    m_referenceColumnBorderColor = color;
  }
setReferenceColumnColor()
void XsheetViewer::setReferenceColumnColor (const QColor & color) inline
{
    m_referenceColumnColor = color;
  }
setScrubHighlight()
void XsheetViewer::setScrubHighlight (int row, int starRow, int col)
{
  if (m_scrubCol == -1) m_scrubCol = col;
  m_scrubRow0 = std::min(row, startRow);
  m_scrubRow1 = std::max(row, startRow);
  return;
}
setSelectedActiveCameraColor()
void XsheetViewer::setSelectedActiveCameraColor (const QColor & color) inline
{
    m_SelectedActiveCameraColor = color;
  }
setSelectedChildColumnColor()
void XsheetViewer::setSelectedChildColumnColor (const QColor & color) inline
{
    m_selectedChildColumnColor = color;
  }
setSelectedColumnHead()
void XsheetViewer::setSelectedColumnHead (const QColor & color) inline
{
    m_selectedColumnHead = color;
  }
setSelectedEmptyCellColor()
void XsheetViewer::setSelectedEmptyCellColor (const QColor & color) inline
{
    m_selectedEmptyCellColor = color;
  }
setSelectedFullcolorColumnColor()
void XsheetViewer::setSelectedFullcolorColumnColor (const QColor & color) inline
{
    m_selectedFullcolorColumnColor = color;
  }
setSelectedFxColumnColor()
void XsheetViewer::setSelectedFxColumnColor (const QColor & color) inline
{
    m_selectedFxColumnColor = color;
  }
setSelectedLevelColumnColor()
void XsheetViewer::setSelectedLevelColumnColor (const QColor & color) inline
{
    m_selectedLevelColumnColor = color;
  }
setSelectedMeshColumnColor()
void XsheetViewer::setSelectedMeshColumnColor (const QColor & color) inline
{
    m_selectedMeshColumnColor = color;
  }
setSelectedOtherCameraColor()
void XsheetViewer::setSelectedOtherCameraColor (const QColor & color) inline
{
    m_SelectedOtherCameraColor = color;
  }
setSelectedPaletteColumnColor()
void XsheetViewer::setSelectedPaletteColumnColor (const QColor & color) inline
{
    m_selectedPaletteColumnColor = color;
  }
setSelectedReferenceColumnColor()
void XsheetViewer::setSelectedReferenceColumnColor (const QColor & color) inline
{
    m_selectedReferenceColumnColor = color;
  }
setSelectedSoundTextColumnColor()
void XsheetViewer::setSelectedSoundTextColumnColor (const QColor & color) inline
{
    m_selectedSoundTextColumnColor = color;
  }
setSelectedVectorColumnColor()
void XsheetViewer::setSelectedVectorColumnColor (const QColor & color) inline
{
    m_selectedVectorColumnColor = color;
  }
setSoundTextColumnBorderColor()
void XsheetViewer::setSoundTextColumnBorderColor (const QColor & color) inline
{
    m_soundTextColumnBorderColor = color;
  }
setSoundTextColumnColor()
void XsheetViewer::setSoundTextColumnColor (const QColor & color) inline
{
    m_soundTextColumnColor = color;
  }
setTextColor()
void XsheetViewer::setTextColor (const QColor & color) inline
{ m_textColor = color; }
setTimelineCamstandButtonBgOffColor()
void XsheetViewer::setTimelineCamstandButtonBgOffColor (const QColor & color) inline
{
    m_timelineCamstandButtonBgOffColor = color;
  }
setTimelineCamstandButtonBgOnColor()
void XsheetViewer::setTimelineCamstandButtonBgOnColor (const QColor & color) inline
{
    m_timelineCamstandButtonBgOnColor = color;
  }
setTimelineCamstandButtonOffImage()
void XsheetViewer::setTimelineCamstandButtonOffImage (const QImage & image) inline
{
    m_timelineCamstandButtonOffImage = image;
  }
setTimelineCamstandButtonOnImage()
void XsheetViewer::setTimelineCamstandButtonOnImage (const QImage & image) inline
{
    m_timelineCamstandButtonOnImage = image;
  }
setTimelineCamstandButtonTranspImage()
void XsheetViewer::setTimelineCamstandButtonTranspImage (const QImage & image) inline
{
    m_timelineCamstandButtonTranspImage = image;
  }
setTimelineConfigButtonBgColor()
void XsheetViewer::setTimelineConfigButtonBgColor (const QColor & color) inline
{
    m_timelineConfigButtonBgColor = color;
  }
setTimelineConfigButtonImage()
void XsheetViewer::setTimelineConfigButtonImage (const QImage & image) inline
{
    m_timelineConfigButtonImage = image;
  }
setTimelineIconLineColor()
void XsheetViewer::setTimelineIconLineColor (const QColor & color) inline
{
    m_timelineIconLineColor = color;
  }
setTimelineLockButtonBgOffColor()
void XsheetViewer::setTimelineLockButtonBgOffColor (const QColor & color) inline
{
    m_timelineLockButtonBgOffColor = color;
  }
setTimelineLockButtonBgOnColor()
void XsheetViewer::setTimelineLockButtonBgOnColor (const QColor & color) inline
{
    m_timelineLockButtonBgOnColor = color;
  }
setTimelineLockButtonOffImage()
void XsheetViewer::setTimelineLockButtonOffImage (const QImage & image) inline
{
    m_timelineLockButtonOffImage = image;
  }
setTimelineLockButtonOnImage()
void XsheetViewer::setTimelineLockButtonOnImage (const QImage & image) inline
{
    m_timelineLockButtonOnImage = image;
  }
setTimelinePreviewButtonBgOffColor()
void XsheetViewer::setTimelinePreviewButtonBgOffColor (const QColor & color) inline
{
    m_timelinePreviewButtonBgOffColor = color;
  }
setTimelinePreviewButtonBgOnColor()
void XsheetViewer::setTimelinePreviewButtonBgOnColor (const QColor & color) inline
{
    m_timelinePreviewButtonBgOnColor = color;
  }
setTimelinePreviewButtonOffImage()
void XsheetViewer::setTimelinePreviewButtonOffImage (const QImage & image) inline
{
    m_timelinePreviewButtonOffImage = image;
  }
setTimelinePreviewButtonOnImage()
void XsheetViewer::setTimelinePreviewButtonOnImage (const QImage & image) inline
{
    m_timelinePreviewButtonOnImage = image;
  }
setVectorColumnBorderColor()
void XsheetViewer::setVectorColumnBorderColor (const QColor & color) inline
{
    m_vectorColumnBorderColor = color;
  }
setVectorColumnColor()
void XsheetViewer::setVectorColumnColor (const QColor & color) inline
{
    m_vectorColumnColor = color;
  }
setVerticalLineColor()
void XsheetViewer::setVerticalLineColor (const QColor & color) inline
{
    m_verticalLineColor = color;
  }
setVerticalLineHeadColor()
void XsheetViewer::setVerticalLineHeadColor (const QColor & color) inline
{
    m_verticalLineHeadColor = color;
  }
setXsheetCamstandButtonBgOffColor()
void XsheetViewer::setXsheetCamstandButtonBgOffColor (const QColor & color) inline
{
    m_xsheetCamstandButtonBgOffColor = color;
  }
setXsheetCamstandButtonBgOnColor()
void XsheetViewer::setXsheetCamstandButtonBgOnColor (const QColor & color) inline
{
    m_xsheetCamstandButtonBgOnColor = color;
  }
setXsheetCamstandButtonOffImage()
void XsheetViewer::setXsheetCamstandButtonOffImage (const QImage & image) inline
{
    m_xsheetCamstandButtonOffImage = image;
  }
setXsheetCamstandButtonOnImage()
void XsheetViewer::setXsheetCamstandButtonOnImage (const QImage & image) inline
{
    m_xsheetCamstandButtonOnImage = image;
  }
setXsheetCamstandButtonTranspImage()
void XsheetViewer::setXsheetCamstandButtonTranspImage (const QImage & image) inline
{
    m_xsheetCamstandButtonTranspImage = image;
  }
setXsheetColumnNameBgColor()
void XsheetViewer::setXsheetColumnNameBgColor (const QColor & color) inline
{
    m_xsheetColumnNameBgColor = color;
  }
setXsheetConfigButtonBgColor()
void XsheetViewer::setXsheetConfigButtonBgColor (const QColor & color) inline
{
    m_xsheetConfigButtonBgColor = color;
  }
setXsheetConfigButtonImage()
void XsheetViewer::setXsheetConfigButtonImage (const QImage & image) inline
{
    m_xsheetConfigButtonImage = image;
  }
setXsheetDragBarHighlightColor()
void XsheetViewer::setXsheetDragBarHighlightColor (const QColor & color) inline
{
    m_xsheetDragBarHighlightColor = color;
  }
setXsheetLockButtonBgOffColor()
void XsheetViewer::setXsheetLockButtonBgOffColor (const QColor & color) inline
{
    m_xsheetLockButtonBgOffColor = color;
  }
setXsheetLockButtonBgOnColor()
void XsheetViewer::setXsheetLockButtonBgOnColor (const QColor & color) inline
{
    m_xsheetLockButtonBgOnColor = color;
  }
setXsheetLockButtonOffImage()
void XsheetViewer::setXsheetLockButtonOffImage (const QImage & image) inline
{
    m_xsheetLockButtonOffImage = image;
  }
setXsheetLockButtonOnImage()
void XsheetViewer::setXsheetLockButtonOnImage (const QImage & image) inline
{
    m_xsheetLockButtonOnImage = image;
  }
setXsheetPreviewButtonBgOffColor()
void XsheetViewer::setXsheetPreviewButtonBgOffColor (const QColor & color) inline
{
    m_xsheetPreviewButtonBgOffColor = color;
  }
setXsheetPreviewButtonBgOnColor()
void XsheetViewer::setXsheetPreviewButtonBgOnColor (const QColor & color) inline
{
    m_xsheetPreviewButtonBgOnColor = color;
  }
setXsheetPreviewButtonOffImage()
void XsheetViewer::setXsheetPreviewButtonOffImage (const QImage & image) inline
{
    m_xsheetPreviewButtonOffImage = image;
  }
setXsheetPreviewButtonOnImage()
void XsheetViewer::setXsheetPreviewButtonOnImage (const QImage & image) inline
{
    m_xsheetPreviewButtonOnImage = image;
  }
showEvent()
void XsheetViewer::showEvent (QShowEvent *) override protected
{
  m_frameScroller.registerFrameScroller();
  if (m_isCurrentFrameSwitched) onCurrentFrameSwitched();
  if (m_isCurrentColumnSwitched) onCurrentColumnSwitched();
  m_isCurrentFrameSwitched = false;
  TApp *app = TApp::instance();
  bool ret = connect(app->getCurrentColumn(), SIGNAL(columnIndexSwitched()),
                     this, SLOT(onCurrentColumnSwitched()));
  ret = ret && connect(app->getCurrentFrame(), SIGNAL(frameSwitched()), this,
                       SLOT(onCurrentFrameSwitched()));
  ret = ret && connect(app->getCurrentFrame(), SIGNAL(isPlayingStatusChanged()),
                       this, SLOT(onPlayingStatusChanged()));
  ret = ret && connect(app->getCurrentFrame(), SIGNAL(scrubStopped()), this,
                       SLOT(onScrubStopped()));
  ret = ret && connect(app->getCurrentObject(), SIGNAL(objectChanged(bool)),
                       this, SLOT(updateAllAree(bool)));
  TSceneHandle *sceneHandle = app->getCurrentScene();
  ret = ret && connect(sceneHandle, SIGNAL(sceneSwitched()), this,
                       SLOT(onSceneSwitched()));
  ret = ret && connect(sceneHandle, SIGNAL(nameSceneChanged()), this,
                       SLOT(changeWindowTitle()));
  ret = ret && connect(sceneHandle, SIGNAL(preferenceChanged(const QString &)),
                       this, SLOT(onPreferenceChanged(const QString &)));
  TXsheetHandle *xsheetHandle = app->getCurrentXsheet();
  ret = ret && connect(xsheetHandle, SIGNAL(xsheetSwitched()), this,
                       SLOT(updateAllAree()));
  ret = ret && connect(xsheetHandle, SIGNAL(xsheetSwitched()), this,
                       SLOT(resetXsheetNotes()));
  ret = ret && connect(xsheetHandle, SIGNAL(xsheetChanged()), this,
                       SLOT(onXsheetChanged()));
  ret = ret && connect(xsheetHandle, SIGNAL(xsheetChanged()), this,
                       SLOT(changeWindowTitle()));
  ret = ret &&
        connect(app->getCurrentSelection(),
                SIGNAL(selectionSwitched(TSelection *, TSelection *)), this,
                SLOT(onSelectionSwitched(TSelection *, TSelection *)));
  // update titlebar when the cell selection region is changed
  ret = ret && connect(app->getCurrentSelection(),
                       SIGNAL(selectionChanged(TSelection *)), this,
                       SLOT(onSelectionChanged(TSelection *)));
  // show the current level name to title bar
  ret = ret &&
        connect(app->getCurrentLevel(), SIGNAL(xshLevelSwitched(TXshLevel *)),
                this, SLOT(changeWindowTitle()));
  ret = ret && connect(IconGenerator::instance(), SIGNAL(iconGenerated()), this,
                       SLOT(updateColumnArea()));
  assert(ret);
  refreshContentSize(0, 0);
  changeWindowTitle();
  xsheetHandle->notifyZoomScaleChanged(m_frameZoomFactor);
}
stopAutoPan()
void XsheetViewer::stopAutoPan () inline
{ setAutoPanSpeed(QPoint()); }
timerEvent()
void XsheetViewer::timerEvent (QTimerEvent *) override protected
{
  if (!isAutoPanning()) return;
  scroll(m_autoPanSpeed);
  if (!m_dragTool) return;
  QMouseEvent mouseEvent(QEvent::MouseMove, m_lastAutoPanPos - m_autoPanSpeed,
                         Qt::NoButton, 0, m_qtModifiers);
  m_dragTool->onDrag(&mouseEvent);
  m_lastAutoPanPos += m_autoPanSpeed;
}
updateAllAree
void XsheetViewer::updateAllAree (bool isDragging = false) slot
{
  m_cellArea->update(m_cellArea->visibleRegion());
  if (!isDragging) {
    m_rowArea->update(m_rowArea->visibleRegion());
    m_columnArea->update(m_columnArea->visibleRegion());
  }
  m_toolbar->update(m_toolbar->visibleRegion());
}
updateAreeSize()
void XsheetViewer::updateAreeSize ()
{
  const Orientation *o = orientation();
  QRect viewArea(QPoint(0, 0), m_cellScrollArea->geometry()
                                   .adjusted(0, 0, -XsheetGUI::SCROLLBAR_WIDTH,
                                             -XsheetGUI::SCROLLBAR_WIDTH)
                                   .size());
  QPoint areaFilled(0, 0);
  TXsheet *xsh = getXsheet();
  if (xsh) {
    if (o->isVerticalTimeline())
      areaFilled = positionToXY(
          CellPosition(xsh->getFrameCount() + 1, xsh->getColumnCount() + 1));
    else {
      int firstCol =
          Preferences::instance()->isXsheetCameraColumnVisible() ? -1 : 0;
      areaFilled =
          positionToXY(CellPosition(xsh->getFrameCount() + 1, firstCol));
      ColumnFan *fan = xsh->getColumnFan(m_orientation);
      areaFilled.setY(
          areaFilled.y() + 1 +
          (fan->isActive(firstCol) ? o->cellHeight() : o->foldedCellSize()));
    }
  }
  if (viewArea.width() < areaFilled.x()) viewArea.setWidth(areaFilled.x());
  if (viewArea.height() < areaFilled.y() ||
      (!o->isVerticalTimeline() && viewArea.height() != areaFilled.y()))
    viewArea.setHeight(areaFilled.y());
  NumberRange allLayer    = o->layerSide(viewArea);
  NumberRange allFrame    = o->frameSide(viewArea);
  NumberRange headerLayer = o->range(PredefinedRange::HEADER_LAYER);
  NumberRange headerFrame = o->range(PredefinedRange::HEADER_FRAME);
  m_cellArea->setFixedSize(viewArea.size());
  m_rowArea->setFixedSize(o->frameLayerRect(allFrame, headerLayer).size());
  m_columnArea->setFixedSize(o->frameLayerRect(headerFrame, allLayer).size());
}
updateCellColumnAree
void XsheetViewer::updateCellColumnAree () slot
{
  if (!m_isComputingSize) refreshContentSize(0, 0);
  m_columnArea->update(m_columnArea->visibleRegion());
  m_cellArea->update(m_cellArea->visibleRegion());
}
updateCellRowAree
void XsheetViewer::updateCellRowAree () slot
{
  if (!m_isComputingSize) refreshContentSize(0, 0);
  m_rowArea->update(m_rowArea->visibleRegion());
  m_cellArea->update(m_cellArea->visibleRegion());
}
updateCells()
void XsheetViewer::updateCells () inline
{ m_cellArea->update(m_cellArea->visibleRegion()); }
updateColumnArea
void XsheetViewer::updateColumnArea () slot
{
  m_columnArea->update(m_columnArea->visibleRegion());
}
updateColumns()
void XsheetViewer::updateColumns () inline
{ m_columnArea->update(m_columnArea->visibleRegion()); }
updateNoteWidgets()
void XsheetViewer::updateNoteWidgets ()
Update notes widgets and update cell.
{
  int i;
  for (i = 0; i < m_noteWidgets.size(); i++) m_noteWidgets.at(i)->update();
  m_noteArea->updatePopup();
  updateCells();
}
updateRows()
void XsheetViewer::updateRows () inline
{ m_rowArea->update(m_rowArea->visibleRegion()); }
wheelEvent()
void XsheetViewer::wheelEvent (QWheelEvent * event) override protected
{
  switch (event->source()) {
  case Qt::MouseEventNotSynthesized: {
    if (0 != (event->modifiers() & Qt::ControlModifier) &&
        event->angleDelta().y() != 0) {
      QPoint pos(event->pos().x() - m_columnArea->geometry().width() +
                     m_cellArea->visibleRegion().boundingRect().left(),
                 event->pos().y());
      int targetFrame = xyToPosition(pos).frame();
      int newFactor =
          getFrameZoomFactor() + ((event->angleDelta().y() > 0 ? 1 : -1) * 10);
      if (newFactor > XsheetGUI::ZOOM_FACTOR_MAX)
        newFactor = XsheetGUI::ZOOM_FACTOR_MAX;
      else if (newFactor < XsheetGUI::ZOOM_FACTOR_MIN)
        newFactor = XsheetGUI::ZOOM_FACTOR_MIN;
      zoomOnFrame(targetFrame, newFactor);
      event->accept();
      return;
    }
    int markerDistance = 0, markerOffset = 0;
    TApp::instance()
        ->getCurrentScene()
        ->getScene()
        ->getProperties()
        ->getMarkers(markerDistance, markerOffset);
    if (event->angleDelta().x() == 0) {  // vertical scroll
      if (!orientation()->isVerticalTimeline()) markerDistance = 1;
      int scrollPixels = (event->angleDelta().y() > 0 ? 1 : -1) *
                         markerDistance * orientation()->cellHeight();
      scroll(QPoint(0, -scrollPixels));
    } else {  // horizontal scroll
      if (orientation()->isVerticalTimeline()) markerDistance = 1;
      int scrollPixels = (event->angleDelta().x() > 0 ? 1 : -1) *
                         markerDistance * orientation()->cellWidth();
      scroll(QPoint(-scrollPixels, 0));
    }
    break;
  }
  case Qt::MouseEventSynthesizedBySystem:  // macbook touch-pad
  {
    QPoint numPixels  = event->pixelDelta();
    QPoint numDegrees = event->angleDelta() / 8;
    if (!numPixels.isNull()) {
      scroll(-numPixels);
    } else if (!numDegrees.isNull()) {
      QPoint numSteps = numDegrees / 15;
      scroll(-numSteps);
    }
    break;
  }
  default:  // Qt::MouseEventSynthesizedByQt,
            // Qt::MouseEventSynthesizedByApplication
  {
    std::cout << "not supported event: Qt::MouseEventSynthesizedByQt, "
                 "Qt::MouseEventSynthesizedByApplication"
              << std::endl;
    break;
  }
  }  // end switch
}
xyRectToRange()
CellRange XsheetViewer::xyRectToRange (const QRect & rect) const
{
  CellPosition topLeft     = xyToPosition(rect.topLeft());
  CellPosition bottomRight = xyToPosition(rect.bottomRight());
  return CellRange(topLeft, bottomRight);
}
xyToPosition() [1/3]
CellPosition XsheetViewer::xyToPosition (const QPoint & point) const
{
  const Orientation *o = orientation();
  QPoint usePoint      = point;
  TXsheet *xsh         = getXsheet();
  if (!xsh) return CellPosition(0, 0);
  ColumnFan *fan = xsh->getColumnFan(o);
  if (o->isVerticalTimeline())
    usePoint.setY((usePoint.y() * 100) / getFrameZoomFactor());
  else
    usePoint.setX((usePoint.x() * 100) / getFrameZoomFactor());
  if (o->isVerticalTimeline()) return o->xyToPosition(usePoint, fan);
  // For timeline mode, we need to base the Y axis on the bottom of the column
  // area
  // since the layers are flipped
  int columnCount   = std::max(1, xsh->getColumnCount());
  int colAreaHeight = o->colToLayerAxis(columnCount, fan);
  usePoint.setY(colAreaHeight - usePoint.y());
  CellPosition resultCP = o->xyToPosition(usePoint, fan);
  if (point.y() > colAreaHeight) {
    int colsBelow = ((point.y() - colAreaHeight) / o->cellHeight()) + 1;
    resultCP.setLayer(-colsBelow);
  }
  return resultCP;
}
xyToPosition() [2/3]
CellPosition XsheetViewer::xyToPosition (const TPoint & point) const
{
  return xyToPosition(QPoint(point.x, point.y));
}
xyToPosition() [3/3]
CellPosition XsheetViewer::xyToPosition (const TPointD & point) const
{
  return xyToPosition(QPoint((int)point.x, (int)point.y));
}
zoomOnFrame
void XsheetViewer::zoomOnFrame (int frame, int factor) slot
{
  QPoint xyOrig = positionToXY(CellPosition(frame, -1));
  m_frameZoomFactor = factor;
  m_layerFooterPanel->setZoomSliderValue(m_frameZoomFactor);
  QPoint xyNew = positionToXY(CellPosition(frame, -1));
  scroll(xyNew - xyOrig);
  TApp::instance()->getCurrentXsheet()->notifyXsheetChanged();
  if (orientation()->isVerticalTimeline())
    TApp::instance()->getCurrentXsheet()->notifyZoomScaleChanged(factor);
  m_rowArea->update();
}
zoomToFramesPerPage()
void XsheetViewer::zoomToFramesPerPage (int frames)
{
  int size = (orientation()->isVerticalTimeline())
                 ? m_cellScrollArea->viewport()->height()
                 : m_cellScrollArea->viewport()->width();
  int frameDim = orientation()->dimension(PredefinedDimension::FRAME);
  double scale = (double)size / ((double)frameDim * (double)frames);
  // convert to factor value
  int factor;
  if (orientation()->isVerticalTimeline())
    factor = (int)std::round((0.2 + (scale - 0.5) * 8.0 / 5.0) * 100);
  else
    factor = (int)std::round(scale * 100);
  zoomOnFrame(getCurrentRow(), factor);
}
Property Documentation
ActiveCameraColor
QColor XsheetViewer::ActiveCameraColor read
BGColor
QColor XsheetViewer::BGColor read write
CellFocusColor
QColor XsheetViewer::CellFocusColor read write
ChildColumnBorderColor
QColor XsheetViewer::ChildColumnBorderColor read
ChildColumnColor
QColor XsheetViewer::ChildColumnColor read
ColumnHeadPastelizer
QColor XsheetViewer::ColumnHeadPastelizer read
ColumnIconLineColor
QColor XsheetViewer::ColumnIconLineColor read
CurrentRowBgColor
QColor XsheetViewer::CurrentRowBgColor read
DarkBGColor
QColor XsheetViewer::DarkBGColor read write
DarkLineColor
QColor XsheetViewer::DarkLineColor read write
EmptyCellColor
QColor XsheetViewer::EmptyCellColor read write
EmptyColumnHeadColor
QColor XsheetViewer::EmptyColumnHeadColor read
ErrorTextColor
QColor XsheetViewer::ErrorTextColor read write
FoldedColumnBGColor
QColor XsheetViewer::FoldedColumnBGColor read
FoldedColumnLineColor
QColor XsheetViewer::FoldedColumnLineColor read
FrameRangeMarkerLineColor
QColor XsheetViewer::FrameRangeMarkerLineColor read write
FullcolorColumnBorderColor
QColor XsheetViewer::FullcolorColumnBorderColor read
FullcolorColumnColor
QColor XsheetViewer::FullcolorColumnColor read
FxColumnBorderColor
QColor XsheetViewer::FxColumnBorderColor read
FxColumnColor
QColor XsheetViewer::FxColumnColor read write
LayerHeaderCamstandImage
QImage XsheetViewer::LayerHeaderCamstandImage read write
LayerHeaderCamstandOverImage
QImage XsheetViewer::LayerHeaderCamstandOverImage read write
LayerHeaderLockImage
QImage XsheetViewer::LayerHeaderLockImage read
LayerHeaderLockOverImage
QImage XsheetViewer::LayerHeaderLockOverImage read write
LayerHeaderPreviewImage
QImage XsheetViewer::LayerHeaderPreviewImage read write
LayerHeaderPreviewOverImage
QImage XsheetViewer::LayerHeaderPreviewOverImage read write
LevelColumnBorderColor
QColor XsheetViewer::LevelColumnBorderColor read
LevelColumnColor
QColor XsheetViewer::LevelColumnColor read
LightBGColor
QColor XsheetViewer::LightBGColor read write
LightLightBGColor
QColor XsheetViewer::LightLightBGColor read
LightLineColor
QColor XsheetViewer::LightLineColor read write
MarkerLineColor
QColor XsheetViewer::MarkerLineColor read write
MeshColumnBorderColor
QColor XsheetViewer::MeshColumnBorderColor read
MeshColumnColor
QColor XsheetViewer::MeshColumnColor read write
NotEmptyColumnColor
QColor XsheetViewer::NotEmptyColumnColor read
OnionSkinAreaBgColor
QColor XsheetViewer::OnionSkinAreaBgColor read
OtherCameraColor
QColor XsheetViewer::OtherCameraColor read
PaletteColumnBorderColor
QColor XsheetViewer::PaletteColumnBorderColor read write
PaletteColumnColor
QColor XsheetViewer::PaletteColumnColor read
PlayRangeColor
QColor XsheetViewer::PlayRangeColor read write
PreviewFrameTextColor
QColor XsheetViewer::PreviewFrameTextColor read
ReferenceColumnBorderColor
QColor XsheetViewer::ReferenceColumnBorderColor read
ReferenceColumnColor
QColor XsheetViewer::ReferenceColumnColor read
SelectedActiveCameraColor
QColor XsheetViewer::SelectedActiveCameraColor read write
SelectedChildColumnColor
QColor XsheetViewer::SelectedChildColumnColor read write
SelectedColumnHead
QColor XsheetViewer::SelectedColumnHead read
SelectedEmptyCellColor
QColor XsheetViewer::SelectedEmptyCellColor read
SelectedFullcolorColumnColor
QColor XsheetViewer::SelectedFullcolorColumnColor read write
SelectedFxColumnColor
QColor XsheetViewer::SelectedFxColumnColor read
SelectedLevelColumnColor
QColor XsheetViewer::SelectedLevelColumnColor read write
SelectedMeshColumnColor
QColor XsheetViewer::SelectedMeshColumnColor read write
SelectedOtherCameraColor
QColor XsheetViewer::SelectedOtherCameraColor read write
SelectedPaletteColumnColor
QColor XsheetViewer::SelectedPaletteColumnColor read
SelectedReferenceColumnColor
QColor XsheetViewer::SelectedReferenceColumnColor read write
SelectedSoundColumnColor
QColor XsheetViewer::SelectedSoundColumnColor
SelectedSoundTextColumnColor
QColor XsheetViewer::SelectedSoundTextColumnColor read write
SelectedVectorColumnColor
QColor XsheetViewer::SelectedVectorColumnColor read write
SoundColumnBorderColor
QColor XsheetViewer::SoundColumnBorderColor
SoundColumnColor
QColor XsheetViewer::SoundColumnColor
SoundColumnHlColor
QColor XsheetViewer::SoundColumnHlColor
SoundColumnTrackColor
QColor XsheetViewer::SoundColumnTrackColor
SoundTextColumnBorderColor
QColor XsheetViewer::SoundTextColumnBorderColor read
SoundTextColumnColor
QColor XsheetViewer::SoundTextColumnColor read
TextColor
QColor XsheetViewer::TextColor read write
TimelineCamstandButtonOnImage
QColor TimelineCamstandButtonBgOnColor READ getTimelineCamstandButtonBgOnColor WRITE setTimelineCamstandButtonBgOnColor Q_PROPERTY QImage XsheetViewer::TimelineCamstandButtonOnImage read write
TimelineConfigButtonBgColor
QColor XsheetViewer::TimelineConfigButtonBgColor read write
TimelineConfigButtonImage
QImage XsheetViewer::TimelineConfigButtonImage read write
TimelineIconLineColor
QColor XsheetViewer::TimelineIconLineColor read
TimelineLockButtonBgOffColor
QColor XsheetViewer::TimelineLockButtonBgOffColor read write
TimelineLockButtonBgOnColor
QImage TimelineCamstandButtonTranspImage READ getTimelineCamstandButtonTranspImage WRITE setTimelineCamstandButtonTranspImage Q_PROPERTYQColor TimelineCamstandButtonBgOffColor READ getTimelineCamstandButtonBgOffColor WRITE setTimelineCamstandButtonBgOffColor Q_PROPERTYQImage TimelineCamstandButtonOffImage READ getTimelineCamstandButtonOffImage WRITE setTimelineCamstandButtonOffImage QColor m_timelineLockButtonBgOnColor QImage m_timelineLockButtonOnImage QColor m_timelineLockButtonBgOffColor QImage m_timelineLockButtonOffImage Q_PROPERTY QColor XsheetViewer::TimelineLockButtonBgOnColor read write
TimelineLockButtonOffImage
QImage XsheetViewer::TimelineLockButtonOffImage read
TimelineLockButtonOnImage
QImage XsheetViewer::TimelineLockButtonOnImage read write
TimelinePreviewButtonOffImage
QColor TimelinePreviewButtonBgOffColor READ getTimelinePreviewButtonBgOffColor WRITE setTimelinePreviewButtonBgOffColor Q_PROPERTY QImage XsheetViewer::TimelinePreviewButtonOffImage read write
TimelinePreviewButtonOnImage
QColor TimelinePreviewButtonBgOnColor READ getTimelinePreviewButtonBgOnColor WRITE setTimelinePreviewButtonBgOnColor Q_PROPERTY QImage XsheetViewer::TimelinePreviewButtonOnImage read write
VectorColumnBorderColor
QColor XsheetViewer::VectorColumnBorderColor read write
VectorColumnColor
QColor XsheetViewer::VectorColumnColor read
VerticalLineColor
QColor XsheetViewer::VerticalLineColor read
VerticalLineHeadColor
QColor XsheetViewer::VerticalLineHeadColor read
XsheetCamstandButtonBgOnColor
QColor XsheetViewer::XsheetCamstandButtonBgOnColor read write
XsheetCamstandButtonOffImage
QImage XsheetCamstandButtonTranspImage READ getXsheetCamstandButtonTranspImage WRITE setXsheetCamstandButtonTranspImage Q_PROPERTYQColor XsheetCamstandButtonBgOffColor READ getXsheetCamstandButtonBgOffColor WRITE setXsheetCamstandButtonBgOffColor Q_PROPERTY QImage XsheetViewer::XsheetCamstandButtonOffImage read write
XsheetCamstandButtonOnImage
QImage XsheetViewer::XsheetCamstandButtonOnImage read write
XsheetColumnNameBgColor
QColor XsheetViewer::XsheetColumnNameBgColor read write
XsheetConfigButtonBgColor
QColor XsheetViewer::XsheetConfigButtonBgColor read write
XsheetConfigButtonImage
QImage XsheetViewer::XsheetConfigButtonImage read write
XsheetDragBarHighlightColor
QColor XsheetViewer::XsheetDragBarHighlightColor read write
XsheetLockButtonBgOffColor
QColor XsheetViewer::XsheetLockButtonBgOffColor read
XsheetLockButtonBgOnColor
QColor XsheetViewer::XsheetLockButtonBgOnColor read write
XsheetLockButtonOffImage
QImage XsheetViewer::XsheetLockButtonOffImage read write
XsheetLockButtonOnImage
QImage XsheetViewer::XsheetLockButtonOnImage read write
XsheetPreviewButtonBgOffColor
QColor XsheetViewer::XsheetPreviewButtonBgOffColor read write
XsheetPreviewButtonBgOnColor
QColor XsheetViewer::XsheetPreviewButtonBgOnColor read write
XsheetPreviewButtonOffImage
QImage XsheetViewer::XsheetPreviewButtonOffImage read write
XsheetPreviewButtonOnImage
QImage XsheetViewer::XsheetPreviewButtonOnImage read
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/toonz/xsheetviewer.h
E:/opentoonz/toonz/sources/toonz/xsheetviewer.cpp