opentoonz: StylePicker Class Reference
StylePicker Class Reference
Public Member Functions
StylePicker (const TImageP &image)
StylePicker (const TImageP &image, const TPaletteP &palette)
int pickStyleId (const TPointD &point, double radius, double scale2, int mode=2) const
int pickTone (const TPointD &pos) const
TPixel32 pickColor (const TPointD &point, double radius, double scale2) const
TPixel64 pickColor16 (const TPointD &point, double radius, double scale2) const
TPixel32 pickAverageColor (const TRectD &rect) const
TPixel64 pickAverageColor16 (const TRectD &rect) const
TPixel32 pickColor (const TRectD &area) const
TPixel32 pickColor (TStroke *stroke) const
TPoint getRasterPoint (const TPointD &p) const
Detailed Description
Constructor & Destructor Documentation
StylePicker() [1/3]
StylePicker::StylePicker () inline
{}
StylePicker() [2/3]
StylePicker::StylePicker (const TImageP & image)
    : m_image(image), m_palette(image->getPalette()) {}
StylePicker() [3/3]
StylePicker::StylePicker (const TImageP & image, const TPaletteP & palette)
    : m_image(image), m_palette(palette) {}
Member Function Documentation
getRasterPoint()
TPoint StylePicker::getRasterPoint (const TPointD & p) const
dpiScale.getSx()),
dpiScale.getSy()));
{
  if (TToonzImageP ti = m_image) {
    // DpiScale dpiScale(ti);
    TDimension size = ti->getSize();
    return TPoint(tround(0.5 * size.lx + p.x),
                  tround(0.5 * size.ly + p.y));
  } else if (TRasterImageP ri = m_image) {
    // DpiScale dpiScale(ri);
    TDimension size = ri->getRaster()->getSize();
    return TPoint(tround(0.5 * size.lx + p.x),   // /dpiScale.getSx()),
                  tround(0.5 * size.ly + p.y));  // /dpiScale.getSy()));
  } else
    return TPoint(tround(p.x), tround(p.y));
}
Referenced by ColorModelViewer::pick(), and pickStyleId().
pickAverageColor()
TPixel32 StylePicker::pickAverageColor (const TRectD & rect) const
{
  TRasterImageP ri = m_image;
  assert(ri);
  if (!!ri) {
    TRasterP raster;
    raster = ri->getRaster();
    TPoint topLeft     = getRasterPoint(rect.getP00());
    TPoint bottomRight = getRasterPoint(rect.getP11());
    if (!raster->getBounds().overlaps(TRect(topLeft, bottomRight)))
      return TPixel32::Transparent;
    topLeft.x     = std::max(0, topLeft.x);
    topLeft.y     = std::max(0, topLeft.y);
    bottomRight.x = std::min(raster->getLx(), bottomRight.x);
    bottomRight.y = std::min(raster->getLy(), bottomRight.y);
    TRaster32P raster32 = raster;
    assert(raster32);
    if (raster32) {
      UINT r = 0, g = 0, b = 0, m = 0, size = 0;
      for (int y = topLeft.y; y < bottomRight.y; y++) {
        TPixel32 *p = &raster32->pixels(y)[topLeft.x];
        for (int x = topLeft.x; x < bottomRight.x; x++, p++) {
          r += p->r;
          g += p->g;
          b += p->b;
          m += p->m;
          size++;
        }
      }
      if (size)
        return TPixel32(r / size, g / size, b / size, m / size);
      else
        return TPixel32::Transparent;
    }
  }
  return TPixel32::Transparent;
}
pickAverageColor16()
TPixel64 StylePicker::pickAverageColor16 (const TRectD & rect) const
{
  TRasterImageP ri = m_image;
  assert(ri);
  if (!ri) return TPixel64::Transparent;
  TRasterP raster;
  raster = ri->getRaster();
  if (raster->getPixelSize() != 8) return TPixel64::Transparent;
  TPoint topLeft     = getRasterPoint(rect.getP00());
  TPoint bottomRight = getRasterPoint(rect.getP11());
  if (!raster->getBounds().overlaps(TRect(topLeft, bottomRight)))
    return TPixel64::Transparent;
  topLeft.x     = std::max(0, topLeft.x);
  topLeft.y     = std::max(0, topLeft.y);
  bottomRight.x = std::min(raster->getLx(), bottomRight.x);
  bottomRight.y = std::min(raster->getLy(), bottomRight.y);
  TRaster64P raster64 = raster;
  assert(raster64);
  if (!raster64) return TPixel64::Transparent;
  UINT r = 0, g = 0, b = 0, m = 0, size = 0;
  for (int y = topLeft.y; y < bottomRight.y; y++) {
    TPixel64 *p = &raster64->pixels(y)[topLeft.x];
    for (int x = topLeft.x; x < bottomRight.x; x++, p++) {
      r += p->r;
      g += p->g;
      b += p->b;
      m += p->m;
      size++;
    }
  }
  if (size)
    return TPixel64(r / size, g / size, b / size, m / size);
  else
    return TPixel64::Transparent;
}
pickColor() [1/3]
TPixel32 StylePicker::pickColor (const TPointD & point, double radius, double scale2) const
{
  TToonzImageP ti  = m_image;
  TRasterImageP ri = m_image;
  TVectorImageP vi = m_image;
  if (!!ri)  // !!ti || !!ri)
  {
    TRasterP raster;
    // if(ti)
    //  raster = ti->getRGBM(true);
    // else
    raster = ri->getRaster();
    TPoint point = getRasterPoint(pos);
    if (!raster->getBounds().contains(point)) return TPixel32::Transparent;
    TRaster32P raster32 = raster;
    if (raster32) return raster32->pixels(point.y)[point.x];
    TRasterGR8P rasterGR8 = raster;
    if (rasterGR8) return toPixel32(rasterGR8->pixels(point.y)[point.x]);
  } else if (vi) {
    const TPalette *palette = m_palette.getPointer();
    if (!palette) return TPixel32::Transparent;
    int styleId = pickStyleId(pos, radius, scale2);
    if (0 <= styleId && styleId < palette->getStyleCount())
      return palette->getStyle(styleId)->getAverageColor();
  } else if (ti) {
    const TPalette *palette = m_palette.getPointer();
    if (!palette) return TPixel32::Transparent;
    int paintId = pickStyleId(pos, radius, scale2, 0);
    int inkId   = pickStyleId(pos, radius, scale2, 1);
    int tone    = pickTone(pos);
    TPixel32 ink, paint;
    if (0 <= inkId && inkId < palette->getStyleCount())
      ink = palette->getStyle(inkId)->getAverageColor();
    if (0 <= paintId && paintId < palette->getStyleCount())
      paint = palette->getStyle(paintId)->getAverageColor();
    if (tone == 0)
      return ink;
    else if (tone == 255)
      return paint;
    else
      return blend(ink, paint, tone, TPixelCM32::getMaxTone());
  }
  return TPixel32::Transparent;
}
pickColor() [2/3]
TPixel32 StylePicker::pickColor (const TRectD & area) const
{
  // TRectD rect=area.enlarge(-1,-1);
  return getAverageColor(convert(area));
}
pickColor() [3/3]
TPixel32 StylePicker::pickColor (TStroke * stroke) const
{
  return getAverageColor(stroke);
}
pickColor16()
TPixel64 StylePicker::pickColor16 (const TPointD & point, double radius, double scale2) const
{
  TToonzImageP ti  = m_image;
  TRasterImageP ri = m_image;
  TVectorImageP vi = m_image;
  assert(ri && !ti && !vi);
  if (!ri || ti || vi) return TPixel64::Transparent;
  TRasterP raster = ri->getRaster();
  if (raster->getPixelSize() != 8) return TPixel64::Transparent;
  TPoint point = getRasterPoint(pos);
  if (!raster->getBounds().contains(point)) return TPixel64::Transparent;
  TRaster64P raster64 = raster;
  if (!raster64) return TPixel64::Transparent;
  return raster64->pixels(point.y)[point.x];
}
pickStyleId()
int StylePicker::pickStyleId (const TPointD & point, double radius, double scale2, int mode = 2) const
funzionerebbe ancora meglio con un getNearestStroke che considera
{
  int styleId = 0;
  if (TToonzImageP ti = m_image) {
    TRasterCM32P ras = ti->getRaster();
    TPoint point     = getRasterPoint(pos);
    if (!ras->getBounds().contains(point)) return -1;
    TPixelCM32 col = ras->pixels(point.y)[point.x];
    switch (mode) {
    case 0:  // AREAS
      styleId = col.getPaint();
      break;
    case 1:  // LINES
      styleId = col.getInk();
      break;
    case 2:  // ALL (Line & Area)
    default:
      styleId = col.isPurePaint() ? col.getPaint() : col.getInk();
      break;
    }
  } else if (TRasterImageP ri = m_image) {
    const TPalette *palette = m_palette.getPointer();
    if (!palette) return -1;
    TRaster32P ras = ri->getRaster();
    if (!ras) return -1;
    TPoint point = getRasterPoint(pos);
    if (!ras->getBounds().contains(point)) return -1;
    TPixel32 col = ras->pixels(point.y)[point.x];
    styleId      = palette->getClosestStyle(col);
  } else if (TVectorImageP vi = m_image) {
    // prima cerca lo stile della regione piu' vicina
    TRegion *r = vi->getRegion(pos);
    if (r) styleId = r->getStyle();
    bool strokeFound;
    double dist2, w, thick;
    UINT index;
    // la thickness, cioe' la min distance dalla outline e non dalla centerLine
    strokeFound = vi->getNearestStroke(pos, w, index, dist2);
    if (strokeFound) {
      int devPixRatio = getDevPixRatio();
      dist2 *= scale2;
      TStroke *stroke = vi->getStroke(index);
      thick           = stroke->getThickPoint(w).thick;
      double len2     = thick * thick * scale2;
      const double minDist2 =
          (styleId == 0) ? radius * radius * (double)(devPixRatio * devPixRatio)
                         : 0;
      double checkDist = std::max(minDist2, len2);
      if (dist2 < checkDist) {
        assert(stroke);
        styleId = stroke->getStyle();
      }
    }
  }
  return styleId;
}
References getRasterPoint(), TRegion::getRegion(), TStroke::getStyle(), and TStroke::getThickPoint().
Referenced by ColorModelViewer::pick().
pickTone()
int StylePicker::pickTone (const TPointD & pos) const
{
  if (TToonzImageP ti = m_image) {
    TRasterCM32P ras = ti->getRaster();
    if (!ras) return -1;
    TPoint point = getRasterPoint(pos);
    if (!ras->getBounds().contains(point)) return -1;
    TPixelCM32 col = ras->pixels(point.y)[point.x];
    return col.getTone();
  } else
    return -1;
}
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/tools/stylepicker.h
E:/opentoonz/toonz/sources/tnztools/stylepicker.cpp