opentoonz: ScenePalette Class Reference
ScenePalette Class Reference final
#include <sceneresources.h>
Public Member Functions
ScenePalette (ToonzScene *scene, TXshPaletteLevel *pl)
void save () override
void updatePath () override
void rollbackPath () override
void accept (ResourceProcessor *processor) override
visitor pattern
bool isDirty () override
QStringList getResourceName () override
Public Member Functions inherited from SceneResource
SceneResource (ToonzScene *scene)
virtual ~SceneResource ()
virtual void save ()=0
virtual void updatePath ()=0
change the resource internal path, according to the scene
virtual void rollbackPath ()=0
change back the resource internal path to its original value
virtual void accept (ResourceProcessor *processor)=0
visitor pattern
void updatePath (TFilePath &fp)
virtual bool isDirty ()=0
virtual QStringList getResourceName ()=0
Additional Inherited Members
Protected Attributes inherited from SceneResource
ToonzScene * m_scene
bool m_untitledScene
TFilePath m_oldSavePath
Detailed Description
The ScenePalette class provides a container for scene palette resource and allows its management.
Inherits SceneResource.
The class, more than SceneResources, contains a pointer to a palette level TXshPaletteLevel, two path for old save path, one decoded and one no, two path for old scanned path, one decoded and one no. The class allows to save simple level save() and to update or to restore old path (save and scan) updatePath() rollbackPath().
Constructor & Destructor Documentation
ScenePalette()
ScenePalette::ScenePalette (ToonzScene * scene, TXshPaletteLevel * pl)
Constructs SceneLevel with ToonzScene scene and TXshPaletteLevel pl.
    : SceneResource(scene)
    , m_pl(pl)
    , m_oldPath(pl->getPath())
    , m_oldActualPath(scene->decodeFilePath(pl->getPath())) {}
Member Function Documentation
accept()
void ScenePalette::accept (ResourceProcessor * processor) inline override virtual
visitor pattern
Implements SceneResource.
{
    processor->process(m_pl);
  }
getResourceName()
QStringList ScenePalette::getResourceName () override virtual
Implements SceneResource.
{
  return QStringList(QString::fromStdString(m_pl->getPath().getLevelName()));
}
isDirty()
bool ScenePalette::isDirty () override virtual
Implements SceneResource.
{ return m_pl->getPalette()->getDirtyFlag(); }
rollbackPath()
void ScenePalette::rollbackPath () override virtual
Set simple level path to old path.
Implements SceneResource.
{ m_pl->setPath(m_oldPath); }
References TXshPaletteLevel::setPath().
save()
void ScenePalette::save () override virtual
Save simple level in right path.
Implements SceneResource.
{
  assert(m_oldPath != TFilePath());
  TFilePath fp = m_oldPath;
  SceneResource::updatePath(fp);
  TFilePath actualFp = m_scene->decodeFilePath(fp);
  try {
    TSystem::touchParentDir(actualFp);
    if (actualFp != m_oldActualPath &&
        TSystem::doesExistFileOrLevel(m_oldActualPath)) {
      TSystem::copyFile(actualFp, m_oldActualPath);
    }
    m_pl->save();  // actualFp non so perche' era cosi'
  } catch (...) {
    TLogger::error() << "Can't save " << actualFp;
  }
}
References ToonzScene::decodeFilePath(), TXshPaletteLevel::save(), and SceneResource::updatePath().
updatePath()
void ScenePalette::updatePath () override virtual
Update simple level path.
Implements SceneResource.
{
  TFilePath fp = m_oldPath;
  SceneResource::updatePath(fp);
  if (fp != m_oldPath) m_pl->setPath(fp);
}
References TXshPaletteLevel::setPath(), and SceneResource::updatePath().
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/toonz/sceneresources.h
E:/opentoonz/toonz/sources/toonzlib/sceneresources.cpp