opentoonz: DVGui::Dialog Class Reference
DVGui::Dialog Class Reference
The Dialog class is the base class of dialog windows.
Signals
void dialogClosed ()
Public Member Functions
Dialog (QWidget *parent=0, bool hasButton=false, bool hasFixedSize=true, const QString &name=QString())
void beginVLayout ()
void endVLayout ()
void beginHLayout ()
void endHLayout ()
void addWidget (QWidget *widget, bool isRight=true)
void addWidgets (QWidget *firstW, QWidget *secondW)
void addWidget (QString labelName, QWidget *widget)
void addLayout (QLayout *layout, bool isRight=true)
void addWidgetLayout (QWidget *widget, QLayout *layout)
void addLayout (QString labelName, QLayout *layout)
void addLayouts (QLayout *firstL, QLayout *secondL)
void addSpacing (int spacing)
void addSeparator (QString name=QString())
void setAlignment (Qt::Alignment alignment)
void setTopMargin (int margin)
void setTopSpacing (int spacing)
void setLabelWidth (int labelWidth)
int getLabelWidth () const
void setLayoutInsertedSpacing (int spacing)
int getLayoutInsertedSpacing ()
void setButtonBarMargin (int margin)
void setButtonBarSpacing (int spacing)
void addButtonBarWidget (QWidget *widget)
void addButtonBarWidget (QWidget *first, QWidget *second)
void addButtonBarWidget (QWidget *first, QWidget *second, QWidget *third)
void addButtonBarWidget (QWidget *first, QWidget *second, QWidget *third, QWidget *fourth)
void hideEvent (QHideEvent *event) override
void clearButtonBar ()
Public Attributes
QVBoxLayout * m_topLayout
QFrame * m_mainFrame
QFrame * m_buttonFrame
QHBoxLayout * m_mainHLayout
bool m_isMainHLayout
QVBoxLayout * m_leftVLayout
QVBoxLayout * m_rightVLayout
bool m_isMainVLayout
int m_layoutSpacing
int m_layoutMargin
int m_labelWidth
std::vector< QWidget * > m_buttonBarWidgets
Protected Member Functions
void resizeEvent (QResizeEvent *e) override
Protected Attributes
QHBoxLayout * m_buttonLayout
QList< QLabel * > m_labelList
Detailed Description
The Dialog class is the base class of dialog windows.
Inherits QDialog.
A dialog window is a top-level window, defined in QDialog, this class provides a collection of functions to manage QDialog widget visualization. Dialog window can be modal or modeless, from this it depends dialog visualization. You set your dialog to modal or modeless directly in constructor, with bool hasButton, in fact if the dialog has button then is modal too.
If dialog is modal it's composed of two part, two QFrame; the first, main part at top of dialog, contains a vertical box layout QVBoxLayout, the second, button part at bottom, contains an horizontal box layout QHBoxLayout. Else if dialog is modeless it is composed only of first part, to be more precise, it is composed of a QFrame containing a vertical box layout QVBoxLayout.
            The first part of dialog can be implemented using different
objects. You can manage directly vertical box layout, insert widget addWidget(), or layout addLayout(), set border and spacing, using setTopMargin() and setTopSpacing(), or insert a spece, addSpacing().
If you need an horizontal layout you can use an implemented horizontal box layout; the function beginHLayout() initialize the horizontal box layout, a collection of function permit to insert object in this layout; at the end you must recall endVLayout(), this add horizontal layout to first part of dialog. This struct permit you to align the object you insert.
If you need vertical layout you can use an implemented vertical box layout composed of two column, the function beginVLayout() initialize the vertical box layout, a collection of function permit to insert object in this layout. All this functions insert a pair of object in two vertical layout and permit to align the objects, all pairs you insert are tabulated. At the end you must recall endVLayout(), this add vertical layout to first part of dialog.
The second part of dialog may be implemented if dialog is modal. It's possible insert one, two or three widget in its horizontal box layout using addButtonBarWidget(), or clear all widget using clearButtonBar(). You can also set margin and spacing with setButtonBarMargin() and setButtonBarSpacing() functions.
Constructor & Destructor Documentation
Dialog()
Dialog::Dialog (QWidget * parent = 0, bool hasButton = false, bool hasFixedSize = true, const QString & name = QString())
    : QDialog(parent, Qt::CustomizeWindowHint | Qt::WindowTitleHint |
                          Qt::WindowCloseButtonHint)
    , m_hasButton(hasButton)
    , m_mainHLayout(0)
    , m_leftVLayout(0)
    , m_rightVLayout(0)
    , m_isMainVLayout(false)
    , m_isMainHLayout(false)
    , m_layoutSpacing(5)
    , m_layoutMargin(0)
    , m_labelWidth(100)
    , m_name() {
  QVBoxLayout *mainLayout = new QVBoxLayout;
  mainLayout->setMargin(0);
  mainLayout->setSpacing(0);
  m_mainFrame = new QFrame(this);
  m_mainFrame->setObjectName("dialogMainFrame");
  m_mainFrame->setMinimumHeight(41);
  m_mainFrame->setFrameStyle(QFrame::StyledPanel);
  m_topLayout = new QVBoxLayout;
  m_topLayout->setMargin(12);
  m_topLayout->setSpacing(m_layoutSpacing);
  m_topLayout->setAlignment(Qt::AlignCenter);
  m_mainFrame->setLayout(m_topLayout);
  mainLayout->addWidget(m_mainFrame);
  if (m_hasButton) {
    // The dialog is modal
    setModal(true);
    m_buttonFrame = new QFrame(this);
    m_buttonFrame->setObjectName("dialogButtonFrame");
    m_buttonFrame->setFrameStyle(QFrame::StyledPanel);
    m_buttonFrame->setFixedHeight(45);
    m_buttonLayout = new QHBoxLayout;
    m_buttonLayout->setMargin(0);
    m_buttonLayout->setSpacing(20);
    m_buttonLayout->setAlignment(Qt::AlignHCenter);
    QVBoxLayout *buttonFrameLayout = new QVBoxLayout;
    buttonFrameLayout->setAlignment(Qt::AlignVCenter);
    buttonFrameLayout->addLayout(m_buttonLayout);
    m_buttonFrame->setLayout(buttonFrameLayout);
    mainLayout->addWidget(m_buttonFrame);
  }
  if (hasFixedSize)
    mainLayout->setSizeConstraint(QLayout::SetFixedSize);
  else
    mainLayout->setSizeConstraint(QLayout::SetMinimumSize);
  setLayout(mainLayout);
// this->setGeometry(30, 30, 300, 300);
#ifdef MACOSX
  setWindowFlags(Qt::Tool);
#endif
  if (settingsPath.isEmpty()) {
    TFilePath savePath =
        ToonzFolder::getMyModuleDir() + TFilePath("popups.ini");
    settingsPath = QString::fromStdWString(savePath.getWideString());
  }
  QSettings settings(settingsPath, QSettings::IniFormat);
  if (name == QString()) return;
  m_name      = name + "DialogGeometry";
  QString geo = settings.value(m_name).toString();
  if (geo != QString()) {
    QStringList values = geo.split(" ");
    assert(values.size() == 4);
    // Ensure that the dialog is visible in the screen.
    // The dialog opens with some offset to bottom-right direction
    // if a flag Qt::WindowMaximizeButtonHint is set. (e.g. PencilTestPopup)
    // Therefore, if the dialog is moved to the bottom-end of the screen,
    // it will be got out of the screen on the next launch.
    // The following position adjustment will also prevent such behavior.
    // try and get active screen
    if (parent != NULL) {
      m_currentScreen = QApplication::desktop()->screenNumber(parent);
    }
    QRect screen = QApplication::desktop()->availableGeometry(m_currentScreen);
    int x        = values.at(0).toInt();
    int y        = values.at(1).toInt();
    // make sure that the window is visible on the screen
    // all popups will popup on the active window the first time
    // so popups moved to other monitors will be moved back
    // when restarting OpenToonz.
    // This may be somewhat annoying if a user REALLY wants the popup
    // on another monitor by default, but this is better than
    // a user thinking the program is broken because they didn't notice
    // the popup on another monitor
    if (x > screen.right() - 50) x = screen.right() - 50;
    if (x < screen.left()) x = screen.left();
    if (y > screen.bottom() - 90) y = screen.bottom() - 90;
    if (y < screen.top()) y = screen.top();
    setGeometry(x, y, values.at(2).toInt(), values.at(3).toInt());
    settings.setValue(m_name, QString::number(x) + " " + QString::number(y) +
                                  " " + QString::number(values.at(2).toInt()) +
                                  " " + QString::number(values.at(3).toInt()));
  }
}
~Dialog()
Dialog::~Dialog ()
                {
  if (m_name == QString()) return;
  QRect r = geometry();
  QSettings settings(settingsPath, QSettings::IniFormat);
  settings.setValue(m_name, QString::number(r.left()) + " " +
                                QString::number(r.top()) + " " +
                                QString::number(r.width()) + " " +
                                QString::number(r.height()));
}
Member Function Documentation
addButtonBarWidget() [1/4]
void Dialog::addButtonBarWidget (QWidget * first, QWidget * second)
Add two widget to the button part of dialog.
{
  first->setMinimumSize(65, 25);
  second->setMinimumSize(65, 25);
  assert(m_hasButton);
  if (m_hasButton) {
    m_buttonLayout->addWidget(first);
    m_buttonLayout->addWidget(second);
  }
}
addButtonBarWidget() [2/4]
void Dialog::addButtonBarWidget (QWidget * first, QWidget * second, QWidget * third)
Add three widget to the button part of dialog.
{
  first->setMinimumSize(65, 25);
  second->setMinimumSize(65, 25);
  third->setMinimumSize(65, 25);
  assert(m_hasButton);
  if (m_hasButton) {
    m_buttonLayout->addWidget(first);
    m_buttonLayout->addWidget(second);
    m_buttonLayout->addWidget(third);
  }
}
addButtonBarWidget() [3/4]
void Dialog::addButtonBarWidget (QWidget * first, QWidget * second, QWidget * third, QWidget * fourth)
Add four widget to the button part of dialog.
{
  first->setMinimumSize(65, 25);
  second->setMinimumSize(65, 25);
  third->setMinimumSize(65, 25);
  assert(m_hasButton);
  if (m_hasButton) {
    m_buttonLayout->addWidget(first);
    m_buttonLayout->addWidget(second);
    m_buttonLayout->addWidget(third);
    m_buttonLayout->addWidget(fourth);
  }
}
addButtonBarWidget() [4/4]
void Dialog::addButtonBarWidget (QWidget * widget)
Add a widget to the button part of dialog.
{
  widget->setMinimumSize(65, 25);
  assert(m_hasButton);
  if (m_hasButton) {
    m_buttonLayout->addWidget(widget);
    m_buttonBarWidgets.push_back(widget);
  }
}
Referenced by LoadFolderPopup::LoadFolderPopup(), and DVGui::ValidatedChoiceDialog::ValidatedChoiceDialog().
addLayout() [1/2]
void Dialog::addLayout (QLayout * layout, bool isRight = true)
Add a layout layout to main part of dialog. If vertical layout is initialized add widget in right column if isRight is true, otherwise in left column. isRight by default is true.
{
  if (m_isMainVLayout) {
    assert(m_leftVLayout && m_rightVLayout);
    int h = layout->itemAt(0)->widget()->height() + m_layoutSpacing;
    if (isRight) {
      m_leftVLayout->addSpacing(h);
      m_rightVLayout->addLayout(layout);
    } else {
      m_leftVLayout->addLayout(layout);
      m_rightVLayout->addSpacing(h);
    }
    return;
  } else if (m_isMainHLayout) {
    assert(m_mainHLayout);
    m_mainHLayout->addLayout(layout);
    return;
  }
  m_topLayout->addLayout(layout);
}
Referenced by addLayouts(), addWidgetLayout(), addWidgets(), endHLayout(), and endVLayout().
addLayout() [2/2]
void Dialog::addLayout (QString labelName, QLayout * layout)
Add a pair [label,layout] to main part of dialog, label is created from QString nameLabel.
Recall addWidgetLayout(QWdiget* widget, QWdiget* layout).
{
  QLabel *label = new QLabel(labelName);
  m_labelList.push_back(label);
  label->setFixedWidth(m_labelWidth);
  label->setAlignment(Qt::AlignRight | Qt::AlignVCenter);
  addWidgetLayout(label, layout);
}
References addWidgetLayout().
addLayouts()
void Dialog::addLayouts (QLayout * firstL, QLayout * secondL)
Add a pair [layout,layout] to main part of dialog.
If vertical and horizontal layout are not initialized create an horizontal box layout containing the two layouts and recall addLayout(). If vertical layout is current add the pair [layout,layout] to vertical layout of main part, firstL on first column and secondL on second column. Else if horizontal layout is current create an horizontal box layout containing firstL and secondL and add it to horizontal layout.
{
  firstL->setMargin(m_layoutMargin);
  firstL->setSpacing(m_layoutSpacing);
  secondL->setMargin(m_layoutMargin);
  secondL->setSpacing(m_layoutSpacing);
  if (m_isMainVLayout) {
    assert(m_leftVLayout && m_rightVLayout);
    m_leftVLayout->addLayout(firstL);
    m_rightVLayout->addLayout(secondL);
    return;
  }
  QHBoxLayout *pairLayout = new QHBoxLayout;
  pairLayout->setMargin(m_layoutMargin);
  pairLayout->setSpacing(m_layoutSpacing);
  pairLayout->addLayout(firstL);
  pairLayout->addLayout(secondL);
  if (m_isMainHLayout) {
    assert(m_mainHLayout);
    m_mainHLayout->addLayout(pairLayout);
    return;
  }
  addLayout(pairLayout);
}
References addLayout().
addSeparator()
void Dialog::addSeparator (QString name = QString())
Add a separator Separator to main part of dialog. If vertical layout is initialized add an horizontal separator. If horizontal layout is initialized add a vertical separator.
{
  Separator *separator = new Separator(name);
  if (m_isMainVLayout) {
    assert(m_leftVLayout && m_rightVLayout);
    endVLayout();
    addWidget(separator);
    beginVLayout();
    return;
  } else if (m_isMainHLayout) {
    assert(m_mainHLayout);
    separator->setOrientation(false);
    m_mainHLayout->addWidget(separator);
    return;
  }
  addWidget(separator);
}
References addWidget(), beginVLayout(), endVLayout(), and DVGui::Separator::setOrientation().
addSpacing()
void Dialog::addSpacing (int spacing)
Add spacing spacing to main part of dialog.
{
  if (m_isMainVLayout) {
    assert(m_leftVLayout && m_rightVLayout);
    m_leftVLayout->addSpacing(spacing);
    m_rightVLayout->addSpacing(spacing);
    return;
  } else if (m_isMainHLayout) {
    assert(m_mainHLayout);
    m_mainHLayout->addSpacing(spacing);
    return;
  }
  m_topLayout->addSpacing(spacing);
}
addWidget() [1/2]
void Dialog::addWidget (QString labelName, QWidget * widget)
Add a pair [label,widget] to main part of dialog, label is created from QString nameLabel.
Recall addWidgets(QWdiget* firstW, QWdiget* secondW).
{
  QLabel *label = new QLabel(labelName);
  m_labelList.push_back(label);
  label->setAlignment(Qt::AlignRight | Qt::AlignVCenter);
  label->setFixedSize(m_labelWidth, widget->height());
  addWidgets(label, widget);
}
References addWidgets().
addWidget() [2/2]
void Dialog::addWidget (QWidget * widget, bool isRight = true)
Add a widget widget to main part of dialog. If vertical layout is initialized add widget in right column if isRight is true, otherwise in left column. isRight by default is true.
{
  if (m_isMainVLayout) {
    assert(m_leftVLayout && m_rightVLayout);
    QWidget *w = new QWidget();
    int h      = widget->height() + m_layoutSpacing;
    if (isRight) {
      m_leftVLayout->addSpacing(h);
      m_rightVLayout->addWidget(widget);
    } else {
      m_leftVLayout->addWidget(widget, 1, Qt::AlignRight);
      m_rightVLayout->addSpacing(h);
    }
    return;
  } else if (m_isMainHLayout) {
    assert(m_mainHLayout);
    m_mainHLayout->addWidget(widget);
    return;
  }
  m_topLayout->addWidget(widget);
}
Referenced by addSeparator(), LoadFolderPopup::LoadFolderPopup(), and DVGui::ValidatedChoiceDialog::ValidatedChoiceDialog().
addWidgetLayout()
void Dialog::addWidgetLayout (QWidget * widget, QLayout * layout)
Add a pair [widget,layout] to main part of dialog.
If vertical and horizontal layout are not initialized create an horizontal box layout containing widget and layout and recall addLayout(). If vertical layout is current add the pair [label,layout] to vertical layout of main part, label on first column and layout on second column. Else if horizontal layout is current create an horizontal box layout containing widget and layout and add it to horizontal layout.
{
  layout->setMargin(m_layoutMargin);
  layout->setSpacing(m_layoutSpacing);
  if (m_isMainVLayout) {
    assert(m_leftVLayout && m_rightVLayout);
    m_leftVLayout->addWidget(widget);
    m_rightVLayout->addLayout(layout);
    return;
  }
  QHBoxLayout *pairLayout = new QHBoxLayout;
  pairLayout->setMargin(m_layoutMargin);
  pairLayout->setSpacing(m_layoutSpacing);
  pairLayout->addWidget(widget);
  pairLayout->addLayout(layout);
  if (m_isMainHLayout) {
    assert(m_mainHLayout);
    m_mainHLayout->addLayout(pairLayout);
    return;
  }
  addLayout(pairLayout);
}
References addLayout().
Referenced by addLayout().
addWidgets()
void Dialog::addWidgets (QWidget * firstW, QWidget * secondW)
Add a pair [widget,widget] to main part of dialog.
If vertical and horizontal layout are not initialized create an horizontal box layout containing the two widgets and recall addLayout(). If vertical layout is current add the pair to vertical layout of main part, firstW on first column and secondW on second column. Else if horizontal layout is current create an horizontal box layout containing firstW and secondW and add it to horizontal layout.
{
  if (m_isMainVLayout) {
    assert(m_leftVLayout && m_rightVLayout);
    m_leftVLayout->addWidget(firstW);
    m_rightVLayout->addWidget(secondW);
    return;
  }
  QHBoxLayout *pairLayout = new QHBoxLayout;
  pairLayout->setMargin(m_layoutMargin);
  pairLayout->setSpacing(m_layoutSpacing);
  pairLayout->addWidget(firstW);
  pairLayout->addWidget(secondW);
  if (m_isMainHLayout) {
    assert(m_mainHLayout);
    m_mainHLayout->addLayout(pairLayout);
    return;
  }
  addLayout(pairLayout);
}
References addLayout().
Referenced by addWidget().
beginHLayout()
void Dialog::beginHLayout ()
Create a new Horizontal Layout for main part of dialog.
{
  m_isMainHLayout = true;
  m_mainHLayout   = new QHBoxLayout;
  m_mainHLayout->setMargin(m_layoutMargin);
  m_mainHLayout->setSpacing(m_layoutSpacing);
}
beginVLayout()
void Dialog::beginVLayout ()
Create the new layouts (2 Vertical) for main part of dialog.
{
  m_isMainVLayout = true;
  m_leftVLayout = new QVBoxLayout;
  m_leftVLayout->setMargin(m_layoutMargin);
  m_leftVLayout->setSpacing(m_layoutSpacing);
  m_rightVLayout = new QVBoxLayout;
  m_rightVLayout->setMargin(m_layoutMargin);
  m_rightVLayout->setSpacing(m_layoutSpacing);
}
Referenced by addSeparator(), and DVGui::ValidatedChoiceDialog::ValidatedChoiceDialog().
clearButtonBar()
void Dialog::clearButtonBar ()
Remove all widget from the button part of dialog.
{
  for (int i = 0; i < (int)m_buttonBarWidgets.size(); i++) {
    m_buttonLayout->removeWidget(m_buttonBarWidgets[i]);
  }
  m_buttonBarWidgets.clear();
}
endHLayout()
void Dialog::endHLayout ()
Add to main part of dialog the Horizontal Layout and set it to 0.
{
  m_isMainHLayout = false;
  if (!m_mainHLayout) return;
  addLayout(m_mainHLayout);
  m_mainHLayout = 0;
}
References addLayout().
endVLayout()
void Dialog::endVLayout ()
Add to main part of dialog the Vertical Layouts ,insert them in a orizontal layout to form two column, set Vertical Layouts to 0 .
{
  if (!m_leftVLayout || !m_rightVLayout) return;
  m_isMainVLayout = false;
  QHBoxLayout *layout = new QHBoxLayout;
  layout->setMargin(m_layoutMargin);
  layout->setSpacing(m_layoutSpacing);
  layout->setSizeConstraint(QLayout::SetFixedSize);
  layout->addLayout(m_leftVLayout);
  layout->setAlignment(m_leftVLayout, Qt::AlignLeft);
  layout->addLayout(m_rightVLayout);
  layout->setAlignment(m_rightVLayout, Qt::AlignLeft);
  addLayout(layout);
  m_leftVLayout  = 0;
  m_rightVLayout = 0;
}
References addLayout().
Referenced by addSeparator().
getLabelWidth()
int DVGui::Dialog::getLabelWidth () const inline
{ return m_labelWidth; };
getLayoutInsertedSpacing()
int Dialog::getLayoutInsertedSpacing ()
Return the spacing of all layout inserted in main part of dialog, horizontal layout and vertical layout.
{ return m_layoutSpacing; }
hideEvent()
void Dialog::hideEvent (QHideEvent * event) override
By default, QDialogs always reset position/size upon hide events. However, we want to prevent such behaviour on Toonz Dialogs - this method is reimplemented for this purpose.
{
  int x = pos().rx();
  int y = pos().ry();
  // make sure the dialog is actually visible on a screen
  int screenCount = QApplication::desktop()->screenCount();
  int currentScreen;
  for (int i = 0; i < screenCount; i++) {
    if (QApplication::desktop()->screenGeometry(i).contains(pos())) {
      currentScreen = i;
      break;
    } else {
      // if not - put it back on the main window
      currentScreen = m_currentScreen;
    }
  }
  QRect screen = QApplication::desktop()->availableGeometry(currentScreen);
  if (x > screen.right() - 50) x = screen.right() - 50;
  if (x < screen.left()) x = screen.left();
  if (y > screen.bottom() - 90) y = screen.bottom() - 90;
  if (y < screen.top()) y = screen.top();
  move(QPoint(x, y));
  resize(size());
  QRect r = geometry();
  QSettings settings(settingsPath, QSettings::IniFormat);
  settings.setValue(m_name, QString::number(r.left()) + " " +
                                QString::number(r.top()) + " " +
                                QString::number(r.width()) + " " +
                                QString::number(r.height()));
  emit dialogClosed();
}
resizeEvent()
void Dialog::resizeEvent (QResizeEvent * e) override protected
{
  if (Preferences::instance()->getCurrentLanguage() != "English") {
    QSize t = this->size();
    for (QLabel *s : m_labelList) s->setFixedWidth(t.width() * .35);
  }
}
setAlignment()
void Dialog::setAlignment (Qt::Alignment alignment)
Set the alignment of the main layout
{
  m_mainFrame->layout()->setAlignment(alignment);
}
setButtonBarMargin()
void Dialog::setButtonBarMargin (int margin)
Set to margin margin of button part of dialog.
{
  m_buttonLayout->setMargin(margin);
}
setButtonBarSpacing()
void Dialog::setButtonBarSpacing (int spacing)
Set to spacing spacing of button part of dialog.
{
  m_buttonLayout->setSpacing(spacing);
}
setLabelWidth()
void Dialog::setLabelWidth (int labelWidth)
{ m_labelWidth = labelWidth; }
setLayoutInsertedSpacing()
void Dialog::setLayoutInsertedSpacing (int spacing)
Set to spacing spacing of all layout inserted in main part of dialog, horizontal layout and vertical layout.
{
  m_layoutSpacing = spacing;
}
setTopMargin()
void Dialog::setTopMargin (int margin)
Set to margin margin of main part of dialog.
{ m_topLayout->setMargin(margin); }
setTopSpacing()
void Dialog::setTopSpacing (int spacing)
Set to spacing spacing of main part of dialog.
{
  m_layoutSpacing = spacing;
  m_topLayout->setSpacing(spacing);
}
Member Data Documentation
m_buttonBarWidgets
std::vector<QWidget *> DVGui::Dialog::m_buttonBarWidgets
m_buttonFrame
QFrame * DVGui::Dialog::m_buttonFrame
m_buttonLayout
QHBoxLayout* DVGui::Dialog::m_buttonLayout protected
m_isMainHLayout
bool DVGui::Dialog::m_isMainHLayout
m_isMainVLayout
bool DVGui::Dialog::m_isMainVLayout
m_labelList
QList<QLabel *> DVGui::Dialog::m_labelList protected
m_labelWidth
int DVGui::Dialog::m_labelWidth
m_layoutMargin
int DVGui::Dialog::m_layoutMargin
m_layoutSpacing
int DVGui::Dialog::m_layoutSpacing
m_leftVLayout
QVBoxLayout* DVGui::Dialog::m_leftVLayout
m_mainFrame
QFrame* DVGui::Dialog::m_mainFrame
m_mainHLayout
QHBoxLayout* DVGui::Dialog::m_mainHLayout
m_rightVLayout
QVBoxLayout * DVGui::Dialog::m_rightVLayout
m_topLayout
QVBoxLayout* DVGui::Dialog::m_topLayout
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/toonzqt/dvdialog.h
E:/opentoonz/toonz/sources/toonzqt/dvdialog.cpp