opentoonz: SceneSound Class Reference
SceneSound Class Reference final
#include <sceneresources.h>
Public Member Functions
SceneSound (ToonzScene *scene, TXshSoundLevel *sl)
void save () override
void updatePath () override
void rollbackPath () override
void accept (ResourceProcessor *processor) override
visitor pattern
bool isDirty () override
QStringList getResourceName () override
Public Member Functions inherited from SceneResource
SceneResource (ToonzScene *scene)
virtual ~SceneResource ()
virtual void save ()=0
virtual void updatePath ()=0
change the resource internal path, according to the scene
virtual void rollbackPath ()=0
change back the resource internal path to its original value
virtual void accept (ResourceProcessor *processor)=0
visitor pattern
void updatePath (TFilePath &fp)
virtual bool isDirty ()=0
virtual QStringList getResourceName ()=0
Additional Inherited Members
Protected Attributes inherited from SceneResource
ToonzScene * m_scene
bool m_untitledScene
TFilePath m_oldSavePath
Detailed Description
The SceneSoundtrack class provides a container for scene sound track resource and allows its management.
Inherits SceneResource.
The class, more than SceneResources, contains a pointer to a sound column TXshSoundColumn, two path for old save path, one decoded and one no. The class allows to save sound track save() and to update or to restore old path updatePath(), rollbackPath().
Constructor & Destructor Documentation
SceneSound()
SceneSound::SceneSound (ToonzScene * scene, TXshSoundLevel * sl)
Constructs SceneSoundtrack with ToonzScene scene and TXshSoundLevel sl.
    : SceneResource(scene)
    , m_sl(sl)
    , m_oldPath(sl->getPath())
    , m_oldActualPath(scene->decodeFilePath(sl->getPath())) {}
Member Function Documentation
accept()
void SceneSound::accept (ResourceProcessor * processor) inline override virtual
visitor pattern
Implements SceneResource.
{
    processor->process(m_sl);
  }
getResourceName()
QStringList SceneSound::getResourceName () inline override virtual
Implements SceneResource.
{ return QStringList(); }
isDirty()
bool SceneSound::isDirty () inline override virtual
Implements SceneResource.
{ return false; }
rollbackPath()
void SceneSound::rollbackPath () override virtual
Set sound track path to old path.
Implements SceneResource.
{ m_sl->setPath(m_oldPath); }
save()
void SceneSound::save () override virtual
Save sound column in right path.
Implements SceneResource.
                      {
  assert(m_oldPath != TFilePath());
  TFilePath fp = m_oldPath;
  SceneResource::updatePath(fp);
  TFilePath actualFp = m_scene->decodeFilePath(fp);
  try {
    TSystem::touchParentDir(actualFp);
    if (!TSystem::doesExistFileOrLevel(m_oldActualPath)) {
      m_sl->save(actualFp);
    } else if (actualFp != m_oldActualPath) {
      TSystem::copyFile(actualFp, m_oldActualPath);
    }
  } catch (...) {
    DVGui::warning(QObject::tr("Can't save") +
                   QString::fromStdWString(L": " + actualFp.getLevelNameW()));
  }
}
References ToonzScene::decodeFilePath(), TXshSoundLevel::save(), and SceneResource::updatePath().
updatePath()
void SceneSound::updatePath () override virtual
Update sound track path.
Implements SceneResource.
{
  TFilePath fp = m_oldPath;
  SceneResource::updatePath(fp);
  if (fp != m_oldPath) m_sl->setPath(fp);
}
References SceneResource::updatePath().
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/toonz/sceneresources.h
E:/opentoonz/toonz/sources/toonzlib/sceneresources.cpp