opentoonz: StudioPalette Class Reference
StudioPalette Class Reference
Classes
class Listener
class Palette
Public Member Functions
TPalette * getPalette (const TFilePath &path, bool loadRefImg=false)
int getChildren (std::vector< TFilePath > &fps, const TFilePath &folderPath)
int getChildCount (const TFilePath &folderPath)
bool isFolder (const TFilePath &path)
bool isPalette (const TFilePath &path)
bool isReadOnly (const TFilePath &path)
bool isLevelPalette (const TFilePath &path)
bool hasGlobalName (const TFilePath &path)
TFilePath createFolder (const TFilePath &parentFolderPath)
void createFolder (const TFilePath &parentFolderPath, std::wstring name)
TFilePath createPalette (const TFilePath &folderPath, std::string paletteName="")
void setPalette (const TFilePath &palettePath, const TPalette *palette, bool notifyPaletteChanged)
void deletePalette (const TFilePath &palettePath)
void deleteFolder (const TFilePath &folderPath)
TFilePath importPalette (const TFilePath &dstFolder, const TFilePath &srcPath)
void movePalette (const TFilePath &dstPath, const TFilePath &srcPath)
TFilePath getLevelPalettesRoot ()
TFilePath getProjectPalettesRoot ()
bool updateLinkedColors (TPalette *palette)
void setStylesGlobalNames (TPalette *palette)
TFilePath getPalettePath (std::wstring paletteId)
TPalette * getPalette (std::wstring paletteId)
TColorStyle * getStyle (std::wstring styleId)
std::pair< TFilePath, int > getSourceStyle (TColorStyle *cs)
void addListener (Listener *listener)
void removeListener (Listener *listener)
void notifyTreeChange ()
void notifyMove (const TFilePath &dstPath, const TFilePath &srcPath)
void notifyPaletteChange (const TFilePath &name)
void save (const TFilePath &path, TPalette *palette)
void removeEntry (const std::wstring paletteId)
void addEntry (const std::wstring paletteId, const TFilePath &path)
Static Public Member Functions
static StudioPalette * instance ()
static bool isEnabled ()
static void enable (bool enabled)
Detailed Description
Constructor & Destructor Documentation
~StudioPalette()
StudioPalette::~StudioPalette ()
{}
Member Function Documentation
addEntry()
void StudioPalette::addEntry (const std::wstring paletteId, const TFilePath & path)
{
  TFilePath rootFps[2] = {m_root, getProjectPalettesRoot()};
  for (auto rootFp : rootFps) {
    if (rootFp.isEmpty()) continue;
    if (!rootFp.isAncestorOf(path)) continue;
    TFilePath tablePath = rootFp + pathTableFileName;
    QSettings tableSettings(QString::fromStdWString(tablePath.getWideString()),
                            QSettings::IniFormat);
    QString pathValue = (path - rootFp).getQString();
    tableSettings.setValue(QString::fromStdWString(paletteId), pathValue);
  }
}
addListener()
void StudioPalette::addListener (Listener * listener)
{
  if (std::find(m_listeners.begin(), m_listeners.end(), listener) ==
      m_listeners.end())
    m_listeners.push_back(listener);
}
createFolder() [1/2]
TFilePath StudioPalette::createFolder (const TFilePath & parentFolderPath)
{
  TFilePath path = makeUniqueName(parentFolderPath + "new folder");
  try {
    TSystem::mkDir(path);
  } catch (...) {
    return TFilePath();
  }
  FolderListenerManager::instance()->notifyFolderChanged(parentFolderPath);
  notifyTreeChange();
  return path;
}
createFolder() [2/2]
void StudioPalette::createFolder (const TFilePath & parentFolderPath, std::wstring name)
{
  TFilePath fp = parentFolderPath + name;
  if (TFileStatus(fp).doesExist()) return;
  try {
    TSystem::mkDir(fp);
  } catch (...) {
    return;
  }
  FolderListenerManager::instance()->notifyFolderChanged(parentFolderPath);
  notifyTreeChange();
}
createPalette()
TFilePath StudioPalette::createPalette (const TFilePath & folderPath, std::string paletteName = "")
{
  TPalette *palette = 0;
  if (name == "") name = "new palette";
  palette      = new TPalette();
  TFilePath fp = makeUniqueName(folderPath + (name + ".tpl"));
  time_t ltime;
  time(&ltime);
  std::wstring gname = std::to_wstring(ltime) + L"_" + std::to_wstring(rand());
  palette->setGlobalName(gname);
  setStylesGlobalNames(palette);
  try {
    save(fp, palette);
  } catch (...) {
    delete palette;
    throw;
  }
  delete palette;
  notifyTreeChange();
  return fp;
}
deleteFolder()
void StudioPalette::deleteFolder (const TFilePath & folderPath)
{
  try {
    TSystem::rmDirTree(path);
  } catch (...) {
  }
  notifyTreeChange();
}
deletePalette()
void StudioPalette::deletePalette (const TFilePath & palettePath)
{
  assert(palettePath.getType() == "tpl");
  try {
    TSystem::deleteFile(palettePath);
  } catch (...) {
    return;
  }
  notifyTreeChange();
}
enable()
void StudioPalette::enable (bool enabled) static
{
  assert(studioPaletteHasBeenReferred == false);
  m_enabled = enabled;
}
getChildCount()
int StudioPalette::getChildCount (const TFilePath & folderPath)
{
  TFilePathSet q;
  try {
    TSystem::readDirectory(q, folderPath);
  } catch (...) {
  }
  return q.size();
}
getChildren()
int StudioPalette::getChildren (std::vector< TFilePath > & fps, const TFilePath & folderPath)
{
  TFilePathSet q;
  if (TFileStatus(folderPath).isDirectory()) {
    try {
      TSystem::readDirectory(q, folderPath, false, false);
    } catch (...) {
    }
  }
  // put the folders above the palette items
  std::vector<TFilePath> palettes;
  for (TFilePathSet::iterator i = q.begin(); i != q.end(); ++i) {
    if (isFolder(*i))
      fps.push_back(*i);
    else if (isPalette(*i))
      palettes.push_back(*i);
  }
  if (!palettes.empty()) {
    fps.reserve(fps.size() + palettes.size());
    std::copy(palettes.begin(), palettes.end(), std::back_inserter(fps));
  }
  //  fps.push_back(m_root+"butta.tpl");
  return fps.size();
}
getLevelPalettesRoot()
TFilePath StudioPalette::getLevelPalettesRoot ()
{
  return m_root + "Global Palettes";
}
getPalette() [1/2]
TPalette * StudioPalette::getPalette (const TFilePath & path, bool loadRefImg = false)
{
  try {
    if (path.getType() != "tpl") return 0;
    TPalette *palette = load(path);
    if (!palette) return 0;
    if (loadRefImgFlag) loadRefImg(palette, path.getParentDir());
    // palette->addRef(); // ci va??
    return palette;
  } catch (...) {
    return 0;
  }
}
getPalette() [2/2]
TPalette * StudioPalette::getPalette (std::wstring paletteId)
{
  TFilePath palettePath = getPalettePath(paletteId);
  if (palettePath != TFilePath())
    return getPalette(palettePath);
  else
    return 0;
}
getPalettePath()
TFilePath StudioPalette::getPalettePath (std::wstring paletteId)
{
  std::map<std::wstring, TFilePath>::iterator it = table.find(paletteId);
  if (it != table.end()) return it->second;
  TFilePath fp;
  // not found in the verified table, then check for the cached table
  it = table_cached.find(paletteId);
  // found in the cached table
  if (it != table_cached.end()) {
    fp = it->second;
    // verify if cached path is correct
    if (fp.getType() != "tpl" ||
        readPaletteGlobalName(it->second) != paletteId) {
      fp = TFilePath();
      // erase the entry
      it = table_cached.erase(it);
      removeEntry(paletteId);
    }
  }
  if (fp.isEmpty()) {
    fp = searchPalette(m_root, paletteId);
    if (fp.isEmpty()) fp = searchPalette(getProjectPalettesRoot(), paletteId);
    addEntry(paletteId, fp);
  }
  table[paletteId] = fp;
  return fp;
}
getProjectPalettesRoot()
TFilePath StudioPalette::getProjectPalettesRoot ()
{
  TProjectP p          = TProjectManager::instance()->getCurrentProject();
  TFilePath folderName = p->getFolder(TProject::Palettes);
  if (folderName.isEmpty()) return TFilePath();
  if (folderName.isAbsolute()) return folderName;
  return p->getProjectFolder() + folderName;
}
getSourceStyle()
std::pair< TFilePath, int > StudioPalette::getSourceStyle (TColorStyle * cs)
{
  std::pair<TFilePath, int> ret(TFilePath(), -1);
  if (!cs) return ret;
  std::wstring gname = cs->getGlobalName();
  if (gname == L"") return ret;
  int k = gname.find_first_of(L'-', 1);
  if (k == (int)std::wstring::npos) return ret;
  std::wstring paletteId = gname.substr(1, k - 1);
  ret.first              = getPalettePath(paletteId) - m_root;
  ret.second             = std::stoi(gname.substr(k + 1));
  return ret;
}
getStyle()
TColorStyle * StudioPalette::getStyle (std::wstring styleId)
{ return 0; }
hasGlobalName()
bool StudioPalette::hasGlobalName (const TFilePath & path)
check if the palette is studio palette or level palette in order to separate icons in the StudioPaletteTree.
{
  return (readPaletteGlobalName(path) != L"");
}
importPalette()
TFilePath StudioPalette::importPalette (const TFilePath & dstFolder, const TFilePath & srcPath)
{
  TPaletteP palette;
  std::string ext = srcPath.getType();
  try {
    if (ext == "plt")
      palette = loadToonz46Palette(srcPath);
    else if (ext == "pli")
      palette = loadPliPalette(srcPath);
    else if (ext == "tpl")
      palette = loadTplPalette(srcPath);
  } catch (...) {
  }
  if (!palette) return TFilePath();
  std::wstring name = srcPath.getWideName();
  assert(!palette->isCleanupPalette());
  //    convertToLevelPalette(palette.getPointer());
  TFilePath fp = makeUniqueName(dstFolder + (name + L".tpl"));
  time_t ltime;
  time(&ltime);
  std::wstring gname = std::to_wstring(ltime) + L"_" + std::to_wstring(rand());
  palette->setGlobalName(gname);
  setStylesGlobalNames(palette.getPointer());
  TSystem::touchParentDir(fp);
  save(fp, palette.getPointer());
  notifyTreeChange();
  return fp;
}
instance()
StudioPalette * StudioPalette::instance () static
{
  static StudioPalette _instance;
  studioPaletteHasBeenReferred = true;
  assert(m_enabled);
  return &_instance;
}
isEnabled()
static bool StudioPalette::isEnabled () inline static
{ return m_enabled; };
isFolder()
bool StudioPalette::isFolder (const TFilePath & path)
{
  return TFileStatus(path).isDirectory();
}
isLevelPalette()
bool StudioPalette::isLevelPalette (const TFilePath & path)
{
  TPalette *palette = getPalette(path);
  if (!palette) return false;
  bool ret = !palette->isCleanupPalette();
  delete palette;
  return ret;
}
isPalette()
bool StudioPalette::isPalette (const TFilePath & path)
{
  return path.getType() == "tpl";
}
isReadOnly()
bool StudioPalette::isReadOnly (const TFilePath & path)
{
  return !TFileStatus(path).isWritable();
}
movePalette()
void StudioPalette::movePalette (const TFilePath & dstPath, const TFilePath & srcPath)
{
  try {
    // do not allow overwrite palette
    TSystem::renameFile(dstPath, srcPath, false);
  } catch (...) {
    throw;
  }
  std::wstring id = readPaletteGlobalName(dstPath);
  table.erase(id);
  removeEntry(id);
  FolderListenerManager::instance()->notifyFolderChanged(
      dstPath.getParentDir());
  notifyMove(dstPath, srcPath);
}
notifyMove()
void StudioPalette::notifyMove (const TFilePath & dstPath, const TFilePath & srcPath)
{
  for (std::vector<Listener *>::iterator it = m_listeners.begin();
       it != m_listeners.end(); ++it)
    (*it)->onStudioPaletteMove(dstPath, srcPath);
}
notifyPaletteChange()
void StudioPalette::notifyPaletteChange (const TFilePath & name)
{
  for (std::vector<Listener *>::iterator it = m_listeners.begin();
       it != m_listeners.end(); ++it)
    (*it)->onStudioPaletteChange(palette);
}
notifyTreeChange()
void StudioPalette::notifyTreeChange ()
{
  for (std::vector<Listener *>::iterator it = m_listeners.begin();
       it != m_listeners.end(); ++it)
    (*it)->onStudioPaletteTreeChange();
}
removeEntry()
void StudioPalette::removeEntry (const std::wstring paletteId)
{
  TFilePath rootFps[2] = {m_root, getProjectPalettesRoot()};
  for (auto rootFp : rootFps) {
    if (rootFp.isEmpty()) continue;
    TFilePath tablePath = rootFp + pathTableFileName;
    if (!TFileStatus(tablePath).doesExist()) continue;
    QSettings tableSettings(QString::fromStdWString(tablePath.getWideString()),
                            QSettings::IniFormat);
    if (tableSettings.contains(QString::fromStdWString(paletteId))) {
      tableSettings.remove(QString::fromStdWString(paletteId));
      break;
    }
  }
}
removeListener()
void StudioPalette::removeListener (Listener * listener)
{
  m_listeners.erase(
      std::remove(m_listeners.begin(), m_listeners.end(), listener),
      m_listeners.end());
}
save()
void StudioPalette::save (const TFilePath & path, TPalette * palette)
{
  TFileStatus fs(path);
  if (fs.doesExist() && !fs.isWritable()) {
    throw TSystemException(path,
                           "The studio palette cannot be saved: it is a read "
                           "only studio palette.");
  }
  TOStream os(path);
  if (!os) {
    throw TSystemException(path,
                           "The studio palette cannot be saved: the output "
                           "stream status is invalid.");
  }
  std::map<std::string, std::string> attr;
  attr["name"] = ::to_string(palette->getGlobalName());
  os.openChild("palette", attr);
  palette->saveData(os);
  os.closeChild();
}
setPalette()
void StudioPalette::setPalette (const TFilePath & palettePath, const TPalette * palette, bool notifyPaletteChanged)
{
  assert(palettePath.getType() == "tpl");
  TPalette *palette = plt->clone();
  palette->setIsLocked(plt->isLocked());
  palette->addRef();
  std::wstring pgn = palette->getGlobalName();
  if (TFileStatus(palettePath).doesExist())
    pgn = readPaletteGlobalName(palettePath);
  palette->setGlobalName(pgn);
  setStylesGlobalNames(palette);
  try {
    save(palettePath, palette);
  } catch (...) {
    palette->release();
    throw;
  }
  palette->release();
  if (notifyPaletteChanged) notifyPaletteChange(palettePath);
}
setStylesGlobalNames()
void StudioPalette::setStylesGlobalNames (TPalette * palette)
{
  for (int i = 0; i < palette->getStyleCount(); i++) {
    TColorStyle *cs = palette->getStyle(i);
    // set global name only to the styles of which the global name is empty
    if (cs->getGlobalName() == L"") {
      std::wstring gname =
          L"-" + palette->getGlobalName() + L"-" + std::to_wstring(i);
      cs->setGlobalName(gname);
    }
  }
}
updateLinkedColors()
bool StudioPalette::updateLinkedColors (TPalette * palette)
return if any style in the palette is changed
{
  bool paletteIsChanged = false;
  std::map<std::wstring, TPaletteP> table;
  for (int i = 0; i < palette->getStyleCount(); i++) {
    TColorStyle *cs    = palette->getStyle(i);
    std::wstring gname = cs->getGlobalName();
    if (gname == L"" || gname[0] != L'+') continue;
    int k = gname.find_first_of(L'-', 1);
    if (k == (int)std::wstring::npos) continue;
    std::wstring paletteId = gname.substr(1, k - 1);
    std::map<std::wstring, TPaletteP>::iterator it;
    it                  = table.find(paletteId);
    TPalette *spPalette = 0;
    if (it == table.end()) {
      spPalette = getPalette(paletteId);
      if (!spPalette) continue;
      table[paletteId] = spPalette;
      // spPalette->release();
      assert(spPalette->getRefCount() == 1);
    } else
      spPalette = it->second.getPointer();
    int j = std::stoi(gname.substr(k + 1));
    if (spPalette && 0 <= j && j < spPalette->getStyleCount()) {
      TColorStyle *spStyle = spPalette->getStyle(j);
      assert(spStyle);
      spStyle = spStyle->clone();
      spStyle->setGlobalName(gname);
      // put the style name in the studio palette into the original name
      spStyle->setOriginalName(spStyle->getName());
      //.. and keep the style name unchanged
      spStyle->setName(cs->getName());
      palette->setStyle(i, spStyle);
      paletteIsChanged = true;
    }
  }
  return paletteIsChanged;
}
References TColorStyle::clone(), TColorStyle::getGlobalName(), TColorStyle::getName(), TPalette::getStyle(), TColorStyle::setGlobalName(), TColorStyle::setName(), and TColorStyle::setOriginalName().
Referenced by TXshSimpleLevel::load().
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/toonz/studiopalette.h
E:/opentoonz/toonz/sources/toonzlib/studiopalette.cpp