opentoonz: TVectorImagePatternStrokeStyle Class Reference
TVectorImagePatternStrokeStyle Class Reference final
Public Member Functions
TVectorImagePatternStrokeStyle (const std::string &patternName)
bool isRegionStyle () const override
Returns whether the style applies on regions.
bool isStrokeStyle () const override
Returns whether the style applies on strokes.
int getLevelFrameCount ()
void computeTransformations (std::vector< TAffine > &positions, const TStroke *stroke) const
void drawStroke (const TVectorRenderData &rd, const std::vector< TAffine > &positions, const TStroke *stroke) const
void invalidate ()
TColorStyle * clone () const override
Polymorphic clone of the style.
QString getDescription () const override
Return a brief description of the style.
bool hasMainColor () const override
Returns whether the style has a reference main color.
TPixel32 getMainColor () const override
Returns the style's main color, or black if none.
void setMainColor (const TPixel32 &) override
Sets the main color, if it has one.
TStrokeProp * makeStrokeProp (const TStroke *stroke) override
TRegionProp * makeRegionProp (const TRegion *) override
used to draw the style on the specified stroke object.
int getTagId () const override
Returns an unique number representing the style.
void getObsoleteTagIds (std::vector< int > &ids) const override
void loadLevel (const std::string &patternName)
int getParamCount () const override
TColorStyle::ParamType getParamType (int index) const override
Returns the type of the specified parameter.
QString getParamNames (int index) const override
Return the string that identifies the index-th parameter.
void getParamRange (int index, double &min, double &max) const override
Retrieves the specified double parameter range.
double getParamValue (TColorStyle::double_tag, int index) const override
Retrieves the specified double parameter value.
void setParamValue (int index, double value) override
extension value in text form.
Public Member Functions inherited from TColorStyle
TColorStyle (const TColorStyle &other)
Copies another style except its icon.
virtual TColorStyle * clone () const =0
Polymorphic clone of the style.
virtual TColorStyle & copy (const TColorStyle &other)
bool operator== (const TColorStyle &cs) const
bool operator!= (const TColorStyle &cs)
virtual TStrokeProp * makeStrokeProp (const TStroke *stroke)=0
virtual TRegionProp * makeRegionProp (const TRegion *region)=0
used to draw the style on the specified stroke object.
virtual bool isRasterStyle () const
used to draw the style on the specified region object.
virtual TRasterStyleFx * getRasterStyleFx ()
virtual bool isRegionStyle () const =0
Returns whether the style applies on regions.
virtual bool isStrokeStyle () const =0
Returns whether the style applies on strokes.
void setName (std::wstring name)
Sets the style's user-defined name.
std::wstring getName () const
Returns the style's user-defined name.
void setGlobalName (std::wstring name)
Sets the global name of the style.
std::wstring getGlobalName () const
Returns the global name of the style.
void setOriginalName (std::wstring name)
If the style is originally copied from studio palette, set this.
std::wstring getOriginalName () const
Returns the original name of the style.
void setIsEditedFlag (bool edited)
bool getIsEditedFlag () const
style is edited from the original one.
void assignNames (const TColorStyle *src)
Copies the style names from src.
unsigned int getFlags () const
Sets color attributes.
void setFlags (unsigned int flags)
Returns color attributes.
void setPickedPosition (const TPoint &pos, const int index=0)
void setPickedPosition (const PickedPosition &pos)
PickedPosition getPickedPosition () const
virtual bool hasMainColor () const
Returns whether the style has a reference main color.
virtual TPixel32 getMainColor () const
Returns the style's main color, or black if none.
virtual void setMainColor (const TPixel32 &color)
Sets the main color, if it has one.
virtual int getColorParamCount () const
Returns the number of colors (if any) of the style.
virtual TPixel32 getColorParamValue (int index) const
Returns the value of the color of index index.
virtual void setColorParamValue (int index, const TPixel32 &color)
Sets the index-th color value.
virtual TPixel32 getAverageColor () const
Returns a color representing the average of all the style's colors.
virtual int getParamCount () const
virtual ParamType getParamType (int paramIdx) const
Returns the type of the specified parameter.
virtual bool hasParamDefault (int index) const
Value of parameter can be reset to default.
virtual void setParamDefault (int index)
Reset value of parameter to default.
virtual bool isParamDefault (int index) const
Check if current value of parameter equals to default.
virtual void setParamValue (int index, bool value)
Assigns a value to the specified bool parameter.
virtual bool getParamValue (bool_tag, int index) const
Retrieves the specified bool parameter value.
virtual void setParamValue (int index, int value)
Assigns a value to the specified int parameter.
virtual int getParamValue (int_tag, int index) const
Retrieves the specified int parameter value.
virtual void getParamRange (int index, int &min, int &max) const
Retrieves the specified int parameter range.
virtual void getParamRange (int pIndex, QStringList &stringItems) const
virtual void setParamValue (int index, double value)
extension value in text form.
virtual double getParamValue (double_tag, int index) const
Retrieves the specified double parameter value.
virtual void getParamRange (int index, double &min, double &max) const
Retrieves the specified double parameter range.
virtual void setParamValue (int index, const TFilePath &fp)
Assigns a value to the specified TFilePath parameter.
virtual TFilePath getParamValue (TFilePath_tag, int index) const
Retrieves the specified TFilePath parameter value.
void assignBlend (const TColorStyle &a, const TColorStyle &b, double t)
virtual QString getDescription () const =0
Return a brief description of the style.
virtual QString getParamNames (int index) const
Return the string that identifies the index-th parameter.
virtual int getTagId () const =0
Returns an unique number representing the style.
virtual void getObsoleteTagIds (std::vector< int > &) const
void save (TOutputStreamInterface &) const
void invalidateIcon ()
Sets a flag that defines the style's icon validity.
virtual const TRaster32P & getIcon (const TDimension &d)
Returns an image representing the style.
bool isEnabled () const
Returns whether the style can be used.
void enable (bool on)
Sets the style's enabled status.
int getVersionNumber () const
Returns the version number of the style.
Public Member Functions inherited from TSmartObject
TSmartObject (ClassCode classCode)
void addRef ()
void release ()
TINT32 getRefCount () const
Static Public Member Functions
static TFilePath getRootDir ()
static void setRootDir (const TFilePath &path)
static void clearGlDisplayLists ()
Static Public Member Functions inherited from TColorStyle
static TColorStyle * load (TInputStreamInterface &)
static TColorStyle * create (int tagId)
Creates a new style with identifier equal to tagId.
static void declare (TColorStyle *style)
Puts the style in the table of actual styles.
static void getAllTags (std::vector< int > &tags)
Static Public Member Functions inherited from TSmartObject
static TINT32 getInstanceCount (ClassCode code)
Protected Member Functions
void makeIcon (const TDimension &d) override
void loadData (TInputStreamInterface &) override
void loadData (int oldId, TInputStreamInterface &) override
void saveData (TOutputStreamInterface &) const override
Protected Member Functions inherited from TColorStyle
virtual void makeIcon (const TDimension &d)
virtual void loadData (TInputStreamInterface &)=0
virtual void saveData (TOutputStreamInterface &) const =0
virtual void loadData (int, TInputStreamInterface &)
void updateVersionNumber ()
TColorStyle & operator= (const TColorStyle &other)
Copies another style except its icon.
Protected Attributes
TLevelP m_level
std::string m_name
double m_space
double m_rotation
Protected Attributes inherited from TColorStyle
TRaster32P m_icon
Icon shown on TPalette viewers.
bool m_validIcon
Icon's validity status.
Additional Inherited Members
Public Types inherited from TColorStyle
enum ParamType {
BOOL , INT , ENUM , DOUBLE ,
FILEPATH
}
Public Types inherited from TSmartObject
typedef short ClassCode
Static Public Attributes inherited from TColorStyle
static int m_currentFrame = 0
Detailed Description
Constructor & Destructor Documentation
TVectorImagePatternStrokeStyle() [1/2]
TVectorImagePatternStrokeStyle::TVectorImagePatternStrokeStyle ()
    : m_level(), m_name(""), m_space(0), m_rotation(0) {}
TVectorImagePatternStrokeStyle() [2/2]
TVectorImagePatternStrokeStyle::TVectorImagePatternStrokeStyle (const std::string & patternName)
    : m_level(), m_name(patternName), m_space(20), m_rotation(0) {
  loadLevel(patternName);
}
Member Function Documentation
clearGlDisplayLists()
void TVectorImagePatternStrokeStyle::clearGlDisplayLists () static
{
#ifdef _WIN32
  DisplayListManager *pmgr = DisplayListManager::instance();
  assert(pmgr);
  pmgr->clearLists();
#endif
}
clone()
TColorStyle * TVectorImagePatternStrokeStyle::clone () const override virtual
Polymorphic clone of the style.
Implements TColorStyle.
{
  return new TVectorImagePatternStrokeStyle(*this);
}
computeTransformations()
void TVectorImagePatternStrokeStyle::computeTransformations (std::vector< TAffine > & positions, const TStroke * stroke) const
{
  const int frameCount = m_level->getFrameCount();
  if (frameCount == 0) return;
  transformations.clear();
  const double length = stroke->getLength();
  assert(m_level->begin() != m_level->end());
  TLevel::Iterator lit = m_level->begin();
  double s             = 0;
  while (s < length) {
    TFrameId fid      = lit->first;
    TVectorImageP img = m_level->frame(fid);
    if (++lit == m_level->end()) lit = m_level->begin();
    assert(img);
    if (img->getType() != TImage::VECTOR) return;
    double t       = stroke->getParameterAtLength(s);
    TThickPoint p  = stroke->getThickPoint(t);
    TPointD v      = stroke->getSpeed(t);
    double ang     = rad2degree(atan(v)) + m_rotation;
    TRectD bbox    = img->getBBox();
    TPointD center = 0.5 * (bbox.getP00() + bbox.getP11());
    double ry      = bbox.getLy() * 0.5;
    if (ry * ry < 1e-5) ry = p.thick;
    double sc = p.thick / ry;
    if (sc < 0.0001) sc = 0.0001;
    TAffine aff =
        TTranslation(p) * TRotation(ang) * TScale(sc) * TTranslation(-center);
    transformations.push_back(aff);
    double ds = std::max(2.0, sc * bbox.getLx() + m_space);
    s += ds;
  }
}
drawStroke()
void TVectorImagePatternStrokeStyle::drawStroke (const TVectorRenderData & rd, const std::vector< TAffine > & positions, const TStroke * stroke) const
{
  const int frameCount = m_level->getFrameCount();
  if (frameCount == 0) return;
  //------------------------------------------
  // if the average thickness of the stroke, with the current pixelSize,
  // is less than 2, do not drow anything
  UINT cpCount    = stroke->getControlPointCount();
  UINT sampleStep = (cpCount < 10) ? 1 : (UINT)((double)cpCount / 10.0);
  double thickSum = 0;
  UINT count      = 0;
  for (UINT cp = 0; cp < cpCount; cp += sampleStep) {
    thickSum += stroke->getControlPoint(cp).thick;
    count++;
  }
  double averageThick = thickSum / (double)count;
  glPushMatrix();
  tglMultMatrix(rd.m_aff);
  double pixelSize2 = tglGetPixelSize2();
  glPopMatrix();
  if (averageThick * averageThick < 4 * pixelSize2) {
    CHECK_GL_ERROR
    glPushMatrix();
    CHECK_GL_ERROR
    tglMultMatrix(rd.m_aff);
    TLevel::Iterator lit = m_level->begin();
    TFrameId fid      = lit->first;
    TVectorImageP img = m_level->frame(fid);
    std::set<int> styles;
    img->getUsedStyles(styles);
    std::set<int>::iterator si = styles.begin();
    // Calcolo media dei colori utilizzati
    int numStyles  = 0, styleID;
    int averageRed = 0, averageBlue = 0, averageGreen = 0;
    TPixel32 color, averageColor;
    TColorStyle *colorStyle;
    for (; si != styles.end(); si++) {
      styleID = (int)*si;
      if (styleID != 0) {
        colorStyle = m_level->getPalette()->getStyle(styleID);
        color      = colorStyle->getAverageColor();
        if (color.m != 0) {
          numStyles++;
          averageRed += color.r;
          averageGreen += color.g;
          averageBlue += color.b;
        }
      }
    }
    if (numStyles != 0) {
      averageColor.r = averageRed / numStyles;
      averageColor.g = averageGreen / numStyles;
      averageColor.b = averageBlue / numStyles;
    } else
      averageColor = TPixel32::Black;
    tglColor(averageColor);
    glLineStipple(2, 0xAAAA);
    glEnable(GL_LINE_STIPPLE);
    UINT n = stroke->getLength() *
             0.05;  // TODO: funzione di stroke length e pixelsize
    glBegin(GL_LINE_STRIP);
    for (UINT i = 0; i < n; i++) {
      if (n != 1) {
        TThickPoint p = stroke->getPoint(i / (double)(n - 1));
        glVertex2d(p.x, p.y);
      }
    }
    glEnd();
    glDisable(GL_LINE_STIPPLE);
    CHECK_GL_ERROR
    glPopMatrix();
  } else {
    //--------------------------------------------
    assert(m_level->begin() != m_level->end());
    TLevel::Iterator lit = m_level->begin();
    UINT i, size = transformations.size();
    for (i = 0; i < size; i++) {
      TFrameId fid      = lit->first;
      TVectorImageP img = m_level->frame(fid);
      if (++lit == m_level->end()) lit = m_level->begin();
      assert(img);
      if (!img) continue;
      if (img->getType() != TImage::VECTOR) return;
      TVectorImage *imgPointer    = img.getPointer();
      TAffine totalTransformation = rd.m_aff * transformations[i];
      if (rd.m_clippingRect != TRect() && !rd.m_is3dView &&
          !(convert(totalTransformation * imgPointer->getBBox())
                .overlaps(rd.m_clippingRect)))
        continue;
      // drawing
      CHECK_GL_ERROR
      glPushMatrix();
      CHECK_GL_ERROR
      tglMultMatrix(totalTransformation);
      CHECK_GL_ERROR
#ifdef _WIN32
      // currently drawing with the display list doesn't work properly
      // GLuint listId = DisplayListManager::instance()->getDisplayListId(
      //    imgPointer, m_name, fid, rd);
      // if (listId != 0) {
      //  CHECK_GL_ERROR
      //  glCallList(listId);
      //  CHECK_GL_ERROR
      //} else
#endif
      {
        TAffine identity;
        TRect rect;
        TPalette *vPalette = imgPointer->getPalette();
        assert(vPalette);
        TVectorRenderData rd2(identity, rect, vPalette, rd.m_cf, true, true);
        CHECK_GL_ERROR
        tglDraw(rd2, imgPointer);
        CHECK_GL_ERROR
      }
      glPopMatrix();
    }
  }
}
getDescription()
QString TVectorImagePatternStrokeStyle::getDescription () const inline override virtual
Return a brief description of the style.
\detail For example for a stroke style we have "Constant", "Chain", "Rope", "Tulle", etc...
Implements TColorStyle.
{
    return "TVectorImagePatternStrokeStyle";
  }
getLevelFrameCount()
int TVectorImagePatternStrokeStyle::getLevelFrameCount () inline
{ return m_level->getFrameCount(); }
getMainColor()
TPixel32 TVectorImagePatternStrokeStyle::getMainColor () const inline override virtual
Returns the style's main color, or black if none.
Reimplemented from TColorStyle.
{ return TPixel32::Black; }
getObsoleteTagIds()
void TVectorImagePatternStrokeStyle::getObsoleteTagIds (std::vector< int > & ids) const override virtual
Reimplemented from TColorStyle.
{
  // ids.push_back(100);
}
getParamCount()
int TVectorImagePatternStrokeStyle::getParamCount () const override virtual
\detail For example: a the general cleanup style has two parameters, brightness and contrast and a black cleanup style has in addition a black and white threshold, therefore 4 parameters. Returns the number of parameters necessary to describe the style.
Reimplemented from TColorStyle.
{ return 2; }
Referenced by getParamNames(), getParamRange(), getParamType(), getParamValue(), and setParamValue().
getParamNames()
QString TVectorImagePatternStrokeStyle::getParamNames (int index) const override virtual
Return the string that identifies the index-th parameter.
Reimplemented from TColorStyle.
{
  assert(0 <= index && index < getParamCount());
  return (index == 0) ? QCoreApplication::translate(
                            "TVectorImagePatternStrokeStyle", "Distance")
                      : QCoreApplication::translate(
                            "TVectorImagePatternStrokeStyle", "Rotation");
}
References getParamCount().
getParamRange()
void TVectorImagePatternStrokeStyle::getParamRange (int index, double & min, double & max) const override virtual
Retrieves the specified double parameter range.
Reimplemented from TColorStyle.
{
  assert(0 <= index && index < getParamCount());
  if (index == 0) {
    min = -50;
    max = 50;
  } else {
    min = -180;
    max = 180;
  }
}
References getParamCount().
getParamType()
TColorStyle::ParamType TVectorImagePatternStrokeStyle::getParamType (int paramIdx) const override virtual
Returns the type of the specified parameter.
Reimplemented from TColorStyle.
                     {
  assert(0 <= index && index < getParamCount());
  return TColorStyle::DOUBLE;
}
References TColorStyle::DOUBLE, and getParamCount().
getParamValue()
double TVectorImagePatternStrokeStyle::getParamValue (TColorStyle::double_tag , int index) const override virtual
Retrieves the specified double parameter value.
Reimplemented from TColorStyle.
{
  assert(0 <= index && index < getParamCount());
  return index == 0 ? m_space : m_rotation;
}
References getParamCount().
getRootDir()
TFilePath TVectorImagePatternStrokeStyle::getRootDir () static
{ return m_rootDir; }
getTagId()
int TVectorImagePatternStrokeStyle::getTagId () const inline override virtual
Returns an unique number representing the style.
Implements TColorStyle.
{ return 2800; };
hasMainColor()
bool TVectorImagePatternStrokeStyle::hasMainColor () const inline override virtual
Returns whether the style has a reference main color.
\detail Raster or vector pattern image styles, for example, return false.
Reimplemented from TColorStyle.
{ return false; }
invalidate()
void TVectorImagePatternStrokeStyle::invalidate () inline
{};
isRegionStyle()
bool TVectorImagePatternStrokeStyle::isRegionStyle () const inline override virtual
Returns whether the style applies on regions.
Implements TColorStyle.
{ return false; }
isStrokeStyle()
bool TVectorImagePatternStrokeStyle::isStrokeStyle () const inline override virtual
Returns whether the style applies on strokes.
Implements TColorStyle.
{ return true; }
loadData() [1/2]
void TVectorImagePatternStrokeStyle::loadData (int , TInputStreamInterface &) override protected virtual
Deprecated:
Backward compatibility
Reimplemented from TColorStyle.
{
  if (ids != 100)
    throw TException("image pattern stroke style: unknown obsolete format");
  m_level = TLevelP();
  m_name  = "";
  std::string name;
  is >> name;
  if (name != "") {
    try {
      loadLevel(name);
    } catch (...) {
    }
  }
}
loadData() [2/2]
void TVectorImagePatternStrokeStyle::loadData (TInputStreamInterface & is) override protected virtual
Implements TColorStyle.
{
  m_level = TLevelP();
  m_name  = "";
  std::string name;
  is >> name >> m_space >> m_rotation;
  if (name != "") {
    try {
      loadLevel(name);
    } catch (...) {
    }
  }
}
loadLevel()
void TVectorImagePatternStrokeStyle::loadLevel (const std::string & patternName)
{
  m_level = TLevelP();
  m_name  = patternName;
  assert(!getRootDir()
              .isEmpty());  // se e' vuota, non si e' chiamata la setRoot(..)
  TFilePath fp = getRootDir() + (patternName + ".pli");
  TLevelReaderP lr(fp);
  m_level = lr->loadInfo();
  TLevel::Iterator frameIt;
  std::map<TPixel32, int> colors;
  for (frameIt = m_level->begin(); frameIt != m_level->end(); ++frameIt) {
    TVectorImageP img = lr->getFrameReader(frameIt->first)->load();
    if (img) m_level->setFrame(frameIt->first, img);
  }
}
makeIcon()
void TVectorImagePatternStrokeStyle::makeIcon (const TDimension & d) override protected virtual
Reimplemented from TColorStyle.
{
  TLevel::Iterator frameIt = m_level->begin();
  if (frameIt == m_level->end()) {
    TRaster32P icon(size);
    icon->fill(TPixel32::Black);
    int lx = icon->getLx();
    int ly = icon->getLy();
    for (int y = 0; y < ly; y++) {
      int x = ((lx - 1 - 10) * y / ly);
      icon->extractT(x, y, x + 5, y)->fill(TPixel32::Red);
    }
    m_icon = icon;
    return;
  }
  TFrameId fid      = frameIt->first;
  TVectorImageP img = m_level->frame(fid);
  if (!img) {
    TRaster32P icon(size);
    icon->fill(TPixel32::Black);
    int lx = icon->getLx();
    int ly = icon->getLy();
    for (int y = 0; y < ly; y++) {
      int x = ((lx - 1 - 10) * y / ly);
      icon->extractT(x, y, x + 5, y)->fill(TPixel32::Red);
    }
    m_icon = icon;
    return;
  }
  // img->setPalette(m_level->getPalette());
  TPalette *vPalette = m_level->getPalette();
  assert(vPalette);
  img->setPalette(vPalette);
  TOfflineGL *glContext = TOfflineGL::getStock(size);
  glContext->clear(TPixel32::White);
  TRectD bbox = img->getBBox();
  double scx  = 0.8 * size.lx / bbox.getLx();
  double scy  = 0.8 * size.ly / bbox.getLy();
  double sc   = std::min(scx, scy);
  double dx   = (size.lx - bbox.getLx() * sc) * 0.5;
  double dy   = (size.ly - bbox.getLy() * sc) * 0.5;
  TAffine aff = TScale(sc) * TTranslation(-bbox.getP00() + TPointD(dx, dy));
  TVectorRenderData rd(aff, size, vPalette, 0, true);
  glContext->draw(img, rd);
  if (!m_icon || m_icon->getSize() != size)
    m_icon = glContext->getRaster()->clone();
  else
    m_icon->copy(glContext->getRaster());
}
makeRegionProp()
TRegionProp * TVectorImagePatternStrokeStyle::makeRegionProp (const TRegion * region) inline override virtual
used to draw the style on the specified stroke object.
Allocates a new derived TRegionProp instance
Implements TColorStyle.
{
    assert(false);
    return 0;
  };
makeStrokeProp()
TStrokeProp * TVectorImagePatternStrokeStyle::makeStrokeProp (const TStroke * stroke) override virtual
Allocates a new derived TStrokeProp instance
Implements TColorStyle.
{
  return new TVectorImagePatternStrokeProp(stroke, this);
}
saveData()
void TVectorImagePatternStrokeStyle::saveData (TOutputStreamInterface & os) const override protected virtual
Implements TColorStyle.
{
  os << m_name << m_space << m_rotation;
}
setMainColor()
void TVectorImagePatternStrokeStyle::setMainColor (const TPixel32 & color) inline override virtual
Sets the main color, if it has one.
Reimplemented from TColorStyle.
{}
setParamValue()
void TVectorImagePatternStrokeStyle::setParamValue (int index, double value) override virtual
extension value in text form.
Assigns a value to the specified double parameter.
Reimplemented from TColorStyle.
{
  assert(0 <= index && index < getParamCount());
  if (index == 0) {
    if (m_space != value) {
      updateVersionNumber();  // aggiorna il vettore di affini
    }
    m_space = value;
  } else {
    if (m_rotation != value) {
      updateVersionNumber();  // aggiorna il vettore di affini
    }
    m_rotation = value;
  }
}
References getParamCount().
setRootDir()
static void TVectorImagePatternStrokeStyle::setRootDir (const TFilePath & path) inline static
{
    m_rootDir = path + "custom styles";
  }
Member Data Documentation
m_level
TLevelP TVectorImagePatternStrokeStyle::m_level protected
m_name
std::string TVectorImagePatternStrokeStyle::m_name protected
m_rotation
double TVectorImagePatternStrokeStyle::m_rotation protected
m_space
double TVectorImagePatternStrokeStyle::m_space protected
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/tsimplecolorstyles.h
E:/opentoonz/toonz/sources/common/tvrender/tsimplecolorstyles.cpp