opentoonz: EditTool Class Reference
EditTool Class Reference final
Public Member Functions
ToolType getToolType () const override
bool doesApply () const
void saveOldValues ()
bool transformEnabled () const
const TStroke * getSpline () const
void rotate ()
void move ()
void moveCenter ()
void scale ()
void isoScale ()
void squeeze ()
void shear (const TPointD &pos, bool single)
void updateTranslation () override
void leftButtonDown (const TPointD &pos, const TMouseEvent &) override
void leftButtonDrag (const TPointD &pos, const TMouseEvent &) override
void leftButtonUp (const TPointD &pos, const TMouseEvent &) override
void mouseMove (const TPointD &, const TMouseEvent &e) override
void draw () override
Draws the tool on the viewer.
void transform (const TAffine &aff)
void onActivate () override
Callback invoked whenever the tool activates.
void onDeactivate () override
Callback for tool deactivation, includes tool switch.
bool onPropertyChanged (std::string propertyName) override
void computeBBox ()
int getCursorId () const override
Returns the type of cursor used by the tool.
TPropertyGroup * getProperties (int targetType) override
void updateMatrix () override
void drawText (const TPointD &p, double unit, std::string text)
QString updateEnabled (int rowIndex, int columnIndex) override
Public Member Functions inherited from TTool
TTool (std::string toolName)
every tool (invoking updateTranslation() for each).
virtual ToolType getToolType () const =0
ToolTargetType getTargetType () const
std::string getName () const
virtual ToolOptionsBox * createOptionsBox ()
void setViewer (Viewer *viewer)
Viewer * getViewer () const
double getPixelSize () const
void invalidate (const TRectD &rect=TRectD())
int pick (const TPointD &p)
bool isPicking () const
virtual void updateTranslation ()
virtual bool preLeftButtonDown ()
virtual void mouseMove (const TPointD &, const TMouseEvent &)
virtual void leftButtonDown (const TPointD &, const TMouseEvent &)
virtual void leftButtonDrag (const TPointD &, const TMouseEvent &)
virtual void leftButtonUp (const TPointD &, const TMouseEvent &)
virtual void leftButtonDoubleClick (const TPointD &, const TMouseEvent &)
virtual void rightButtonDown (const TPointD &, const TMouseEvent &)
virtual bool keyDown (QKeyEvent *)
virtual void onInputText (std::wstring, std::wstring, int, int)
virtual void onSetViewer ()
virtual void onActivate ()
Callback invoked whenever the tool activates.
virtual void onDeactivate ()
Callback for tool deactivation, includes tool switch.
virtual void onImageChanged ()
Notifies changes in the image in use.
virtual void onEnter ()
Callback for the mouse entering the viewer area.
virtual void onLeave ()
Callback for the mouse leaving the viewer area.
virtual void onFrameSwitched ()
virtual void reset ()
virtual void draw ()
Draws the tool on the viewer.
bool isActive () const
Used to know if a tool is active, (used in TextTool only).
void setActive (bool active)
virtual TPropertyGroup * getProperties (int)
virtual bool onPropertyChanged (std::string propertyName)
virtual TSelection * getSelection ()
Returns a pointer to the tool selection.
virtual int getCursorId () const
Returns the type of cursor used by the tool.
virtual bool isEventAcceptable (QEvent *e)
TXsheet * getXsheet () const
Returns a pointer to the actual Xsheet.
int getFrame ()
Returns the actual frame in use.
int getColumnIndex ()
Returns the actual column index.
TStageObjectId getObjectId () const
Returns a pointer to the actual stage object.
void notifyImageChanged ()
void notifyImageChanged (const TFrameId &fid)
images on the level view.
TFrameId getCurrentFid () const
Returns the number of the actual editing frame.
const TAffine & getMatrix () const
void setMatrix (const TAffine &matrix)
TAffine getCurrentColumnMatrix (int frame=-1) const
TAffine getCurrentColumnParentMatrix () const
TAffine getCurrentObjectParentMatrix () const
TAffine getCurrentObjectParentMatrix2 () const
TAffine getColumnMatrix (int index, int frame=-1) const
virtual void updateMatrix ()
virtual void addContextMenuItems (QMenu *menu)
void enable (bool on)
bool isEnabled () const
QString updateEnabled ()
virtual QString updateEnabled (int rowIndex, int columnIndex)
bool isColumnLocked (int columnIndex) const
void resetInputMethod ()
Resets Input Context (IME)
virtual bool isPencilModeActive ()
virtual bool isDragging () const
void setSelectedFrames (const std::set< TFrameId > &selectedFrames)
void tweenSelectedGuideStrokes ()
void tweenGuideStrokeToSelected ()
void flipGuideStrokeDirection (int mode)
Additional Inherited Members
Public Types inherited from TTool
enum ToolType {
GenericTool = 1 , ColumnTool = 2 , LevelReadTool = 4 , LevelWriteTool ,
LevelTool = LevelReadTool | LevelWriteTool
}
Tool editing type.
enum ToolTargetType {
NoTarget = 0x0 , VectorImage = 0x1 , ToonzImage = 0x2 , RasterImage = 0x4 ,
MeshImage = 0x8 , Splines = 0x10 , LevelColumns = 0x20 , MeshColumns = 0x40 ,
EmptyTarget = 0x80 , CommonImages = VectorImage | ToonzImage | RasterImage , AllImages = CommonImages | MeshImage , Vectors = VectorImage | Splines ,
CommonLevels = CommonImages | LevelColumns , MeshLevels = MeshImage | MeshColumns , AllTargets = 0xffffffff
}
Object types the tool can operate on.
typedef TApplication Application
Static Public Member Functions inherited from TTool
static TTool * getTool (std::string toolName, ToolTargetType targetType)
static TApplication * getApplication ()
static void setApplication (TApplication *application)
static TXshCell getImageCell ()
Returns the level-frame pair to be edited by the tool.
static TImage * getImage (bool toBeModified, int subsampling=0)
Returns the image to be edited by the tool.
static TImage * touchImage ()
static void updateToolsPropertiesTranslation ()
static const std::set< TFrameId > & getSelectedFrames ()
Static Public Attributes inherited from TTool
static std::vector< CellOps > m_cellsData
static bool m_isLevelCreated = false
static bool m_isFrameCreated = false
static std::vector< TFrameId > m_oldFids
static std::vector< TFrameId > m_newFids
static bool m_isLevelRenumbererd = false
Protected Member Functions inherited from TTool
void bind (int targetType)
virtual void onSelectedFramesChanged ()
virtual QString disableString ()
Returns a custom reason to disable the tool.
Protected Attributes inherited from TTool
std::string m_name
The tool's name.
Viewer * m_viewer
Tool's current viewer.
TAffine m_matrix
World-to-window reference change affine.
int m_targetType
The tool's image type target.
bool m_enabled
Whether the tool allows user interaction.
bool m_active
bool m_picking
Static Protected Attributes inherited from TTool
static TApplication * m_application = 0
static std::set< TFrameId > m_selectedFrames = std::set<TFrameId>()
Detailed Description
Constructor & Destructor Documentation
EditTool()
EditTool::EditTool ()
    : TTool("T_Edit")
    , m_active(false)
    , m_what(Translation)
    , m_highlightedDevice(None)
    , m_currentScaleFactor(1)
    , m_fxGadgetController(0)
    , m_keyFrameAdded(false)
    , m_scaleConstraint("Scale Constraint:")  // W_ToolOptions_ScaleConstraint
    , m_autoSelect("Auto Select Column")      // W_ToolOptions_AutoSelect
    , m_globalKeyframes("Global Key", false)  // W_ToolsOptions_GlobalKeyframes
    , m_lockCenterX("Lock Center X", false)
    , m_lockCenterY("Lock Center Y", false)
    , m_lockPositionX("Lock Position X", false)
    , m_lockPositionY("Lock Position Y", false)
    , m_lockRotation("Lock Rotation", false)
    , m_lockShearH("Lock Shear H", false)
    , m_lockShearV("Lock Shear V", false)
    , m_lockScaleH("Lock Scale H", false)
    , m_lockScaleV("Lock Scale V", false)
    , m_lockGlobalScale("Lock Global Scale", false)
    , m_showEWNSposition("X and Y Positions", true)
    , m_showZposition("Z Position", true)
    , m_showSOposition("SO", true)
    , m_showRotation("Rotation", true)
    , m_showGlobalScale("Global Scale", true)
    , m_showHVscale("Horizontal and Vertical Scale", true)
    , m_showShear("Shear", true)
    , m_showCenterPosition("Center Position", true)
    , m_dragTool(0)
    , m_firstTime(true)
    , m_activeAxis("Active Axis")
    , m_isAltPressed(false) {
  bind(TTool::AllTargets);
  m_prop.bind(m_scaleConstraint);
  m_prop.bind(m_autoSelect);
  m_prop.bind(m_globalKeyframes);
  m_prop.bind(m_lockCenterX);
  m_prop.bind(m_lockCenterY);
  m_prop.bind(m_lockPositionX);
  m_prop.bind(m_lockPositionY);
  m_prop.bind(m_lockRotation);
  m_prop.bind(m_lockShearH);
  m_prop.bind(m_lockShearV);
  m_prop.bind(m_lockScaleH);
  m_prop.bind(m_lockScaleV);
  m_prop.bind(m_lockGlobalScale);
  m_prop.bind(m_showEWNSposition);
  m_prop.bind(m_showZposition);
  m_prop.bind(m_showSOposition);
  m_prop.bind(m_showRotation);
  m_prop.bind(m_showGlobalScale);
  m_prop.bind(m_showHVscale);
  m_prop.bind(m_showShear);
  m_prop.bind(m_showCenterPosition);
  m_scaleConstraint.addValue(L"None");
  m_scaleConstraint.addValue(L"A/R");
  m_scaleConstraint.addValue(L"Mass");
  m_scaleConstraint.setValue(L"None");
  m_autoSelect.addValue(L"None");
  m_autoSelect.addValue(L"Column");
  m_autoSelect.addValue(L"Pegbar");
  m_autoSelect.setValue(L"None");
  m_globalKeyframes.setId("GlobalKey");
  m_autoSelect.setId("AutoSelect");
  m_prop.bind(m_activeAxis);
  m_activeAxis.addValue(L"Position", "edit_position");
  m_activeAxis.addValue(L"Rotation", "edit_rotation");
  m_activeAxis.addValue(L"Scale", "edit_scale");
  m_activeAxis.addValue(L"Shear", "edit_shear");
  m_activeAxis.addValue(L"Center", "edit_center");
  m_activeAxis.addValue(L"All", "edit_all");
  m_activeAxis.setValue(L"Position");
  m_activeAxis.setId("EditToolActiveAxis");
}
~EditTool()
EditTool::~EditTool ()
                    {
  delete m_dragTool;
  delete m_fxGadgetController;
}
Member Function Documentation
doesApply()
bool EditTool::doesApply () const
{
  TXsheet *xsh = TTool::getApplication()->getCurrentXsheet()->getXsheet();
  assert(xsh);
  TStageObjectId objId =
      TTool::getApplication()->getCurrentObject()->getObjectId();
  if (objId.isColumn()) {
    TXshColumn *column = xsh->getColumn(objId.getIndex());
    if (column && column->getSoundColumn()) return false;
  }
  return true;
}
draw()
void EditTool::draw () override virtual
Draws the tool on the viewer.
Reimplemented from TTool.
                    {
  // the tool is using the coordinate system of the parent object
  // glColor3d(1,0,1);
  // tglDrawCircle(crossHair,50);
  /*-- Show nothing on Level Editing mode --*/
  if (TTool::getApplication()->getCurrentFrame()->isEditingLevel()) return;
  // if the column and its children are all hidden, only draw fx gadgets
  if (!transformEnabled()) {
    m_fxGadgetController->draw(isPicking());
    return;
  }
  const TPixel32 normalColor(250, 127, 240);
  const TPixel32 highlightedColor(150, 255, 140);
  // collect information
  TXsheet *xsh = getXsheet();
  /*-- Obtain ID of the current editing stage object --*/
  TStageObjectId objId = getObjectId();
  int frame         = getFrame();
  TAffine parentAff = xsh->getParentPlacement(objId, frame);
  TAffine aff       = xsh->getPlacement(objId, frame);
  TPointD center    = Stage::inch * xsh->getCenter(objId, frame);
  /*-- Enable Z translation on 3D view --*/
  if (getViewer()->is3DView()) {
    glPushMatrix();
    glPushName(ZTranslation);
    tglColor(m_highlightedDevice == ZTranslation ? highlightedColor
                                                 : normalColor);
    glPushMatrix();
    double z = xsh->getZ(objId, frame);
    glTranslated(0, -1, z);
    drawArrow(50, isPicking());
    glPopName();
    glPopMatrix();
    glPopMatrix();
    return;
  }
  // Edit-all
  if (m_activeAxis.getValue() == L"All") {
    if (!m_fxGadgetController->isEditingNonZeraryFx()) drawMainHandle();
    m_fxGadgetController->draw(isPicking());
    return;
  }
  double unit = getPixelSize();
  /*-- Obtain object's center position --*/
  glPushMatrix();
  tglMultMatrix(parentAff.inv() * TTranslation(aff * TPointD(0.0, 0.0)));
  tglColor(normalColor);
  tglDrawDisk(TPointD(0.0, 0.0), unit * 4);
  glPopMatrix();
  /*-- Z translation : Draw arrow mark (placed at the camera center) --*/
  if (m_activeAxis.getValue() == L"Position" &&
      m_highlightedDevice == ZTranslation) {
    tglColor(normalColor);
    glPushMatrix();
    TStageObjectId currentCamId =
        TStageObjectId::CameraId(xsh->getCameraColumnIndex());
    TAffine camParentAff = xsh->getParentPlacement(currentCamId, frame);
    TAffine camAff       = xsh->getPlacement(currentCamId, frame);
    tglMultMatrix(camParentAff.inv() *
                  TTranslation(camAff * TPointD(0.0, 0.0)));
    glScaled(unit * 8, unit * 8, 1);
    drawZArrow();
    glPopMatrix();
  }
  /*-- Rotation, Position : Draw vertical and horizontal lines --*/
  else if (m_activeAxis.getValue() == L"Rotation" ||
           m_activeAxis.getValue() == L"Position") {
    glPushMatrix();
    tglMultMatrix(parentAff.inv() * aff * TTranslation(center));
    glScaled(unit, unit, 1);
    tglColor(normalColor);
    glBegin(GL_LINE_STRIP);
    glVertex2i(-800, 0);
    glVertex2i(800, 0);
    glEnd();
    glBegin(GL_LINE_STRIP);
    glVertex2i(0, -100);
    glVertex2i(0, 100);
    glEnd();
    glPopMatrix();
  }
  glPushMatrix();
  tglMultMatrix(parentAff.inv() * TTranslation(aff * center));
  center = TPointD();
  bool dragging = m_dragTool != 0;
  // draw center
  tglColor(normalColor);
  glPushName(Center);
  {
    tglDrawCircle(center, unit * 10);
    tglDrawCircle(center, unit * 8);
    /*-- Draw crossed lines in the circle. It's already translated to the center
     * position. --*/
    glBegin(GL_LINE_STRIP);
    glVertex2d(-unit * 8, 0.0);
    glVertex2d(unit * 8, 0.0);
    glEnd();
    glBegin(GL_LINE_STRIP);
    glVertex2d(0.0, -unit * 8);
    glVertex2d(0.0, unit * 8);
    glEnd();
  }
  glPopName();
  // draw label (column/pegbar name; possibly camera icon)
  tglColor(normalColor);
  glPushMatrix();
  glTranslated(center.x + unit * 10, center.y - unit * 20, 0);
  /*-- Object name --*/
  TStageObject *pegbar = xsh->getStageObject(objId);
  std::string name     = pegbar->getFullName();
  if (objId.isColumn() || objId.isPegbar() || objId.isTable()) {
    glScaled(unit * 2, unit * 1.5, 1);
    tglDrawText(TPointD(0, 0), name);
  } else if (objId.isCamera()) {
    glPushMatrix();
    glScaled(unit * 2, unit * 1.5, 1);
    tglDrawText(TPointD(12, 0), name);
    glPopMatrix();
    glScaled(unit, unit, 1);
    drawCameraIcon();
  }
  glPopMatrix();
  /*--- When editing non-active camera, draw its camera frame ---*/
  if (objId.isCamera()) {
    if (xsh->getStageObjectTree()->getCurrentCameraId() != objId) {
      // TODO : glLineStipple has been deprecated in the OpenGL APIs. Need to be
      // replaced. 2016/1/20 shun_iwasawa
      glEnable(GL_LINE_STIPPLE);
      glColor3d(1.0, 0.0, 1.0);
      glLineStipple(1, 0x1111);
      TRectD cameraRect = TTool::getApplication()
                              ->getCurrentScene()
                              ->getScene()
                              ->getCurrentCamera()
                              ->getStageRect();
      glPushMatrix();
      tglDrawRect(cameraRect);
      glPopMatrix();
      glDisable(GL_LINE_STIPPLE);
    }
  }
  glPopMatrix();
  m_fxGadgetController->draw(isPicking());
}
References TXsheet::getCenter(), ToonzScene::getCurrentCamera(), TStageObjectTree::getCurrentCameraId(), TTool::getFrame(), TStageObject::getFullName(), TTool::getObjectId(), TXsheet::getParentPlacement(), TXsheet::getPlacement(), TXsheet::getStageObject(), TXsheet::getStageObjectTree(), TCamera::getStageRect(), TTool::getXsheet(), TXsheet::getZ(), Stage::inch, TAffine::inv(), TStageObjectId::isCamera(), TStageObjectId::isColumn(), TStageObjectId::isPegbar(), and TStageObjectId::isTable().
drawText()
void EditTool::drawText (const TPointD & p, double unit, std::string text)
{
  glPushMatrix();
  glTranslated(p.x, p.y, 0.0);
  double sc = unit * 1.6;
  /*
double w = sc * tglGetTextWidth(text, GLUT_STROKE_ROMAN);
double h = sc;
glEnable(GL_BLEND);
glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
glColor4d(0.9,0.9,0.1,0.5);
glRectd(0,0,w,h);
glDisable(GL_BLEND);
glColor3d(0,0,0);
*/
  glScaled(sc, sc, 1);
  tglDrawText(TPointD(8, -3), text);
  glPopMatrix();
}
getCursorId()
int EditTool::getCursorId () const override virtual
Returns the type of cursor used by the tool.
See also
For a list of cursor ids cursor.h
Reimplemented from TTool.
{
  int ret;
  // cursor for controlling the fx gadget
  if (m_highlightedDevice >= 1000)
    ret = ToolCursor::FxGadgetCursor;
  else if (transformEnabled()) {
    // switch cursors depending on the active axis
    std::wstring activeAxis = m_activeAxis.getValue();
    if (activeAxis == L"Position") {
      if (m_highlightedDevice == ZTranslation)
        ret = ToolCursor::MoveZCursor;
      else if (LockPositionX && LockPositionY)
        return ToolCursor::DisableCursor;
      else if (LockPositionX)
        ret = ToolCursor::MoveNSCursor;
      else if (LockPositionY)
        ret = ToolCursor::MoveEWCursor;
      else
        ret = ToolCursor::MoveCursor;
    } else if (activeAxis == L"Rotation") {
      ret = ToolCursor::RotCursor;
    } else if (activeAxis == L"Scale") {
      if (m_highlightedDevice == ScaleXY) {
        if (LockScaleH && LockScaleV)
          return ToolCursor::DisableCursor;
        else if (LockScaleH)
          ret = ToolCursor::ScaleVCursor;
        else if (LockScaleV)
          ret = ToolCursor::ScaleHCursor;
        else
          ret = ToolCursor::ScaleHVCursor;
      } else
        ret = ToolCursor::ScaleGlobalCursor;
    } else if (activeAxis == L"Shear") {
      if (LockShearH && LockShearV)
        return ToolCursor::DisableCursor;
      else if (LockShearH)
        ret = ToolCursor::ScaleVCursor;
      else if (LockShearV)
        ret = ToolCursor::ScaleHCursor;
      else
        ret = ToolCursor::ScaleCursor;
    } else if (activeAxis == L"Center") {
      if (LockCenterX && LockCenterY)
        return ToolCursor::DisableCursor;
      else if (LockCenterX)
        ret = ToolCursor::MoveNSCursor;
      else if (LockCenterY)
        ret = ToolCursor::MoveEWCursor;
      else
        ret = ToolCursor::MoveCursor;
    } else
      ret = ToolCursor::StrokeSelectCursor;
  } else
    return ToolCursor::DisableCursor;
  // precise control with pressing Alt key
  if (m_isAltPressed) ret = ret | ToolCursor::Ex_Precise;
  return ret;
}
getProperties()
TPropertyGroup * EditTool::getProperties (int targetType) inline override virtual
Reimplemented from TTool.
{ return &m_prop; }
getSpline()
const TStroke * EditTool::getSpline () const
{
  TTool::Application *app    = TTool::getApplication();
  TXsheet *xsh               = app->getCurrentXsheet()->getXsheet();
  TStageObjectId objId       = app->getCurrentObject()->getObjectId();
  TStageObject *pegbar       = xsh->getStageObject(objId);
  TStageObjectSpline *spline = pegbar ? pegbar->getSpline() : 0;
  return spline ? spline->getStroke() : 0;
}
getToolType()
ToolType EditTool::getToolType () const inline override virtual
Implements TTool.
{ return TTool::ColumnTool; }
leftButtonDown()
void EditTool::leftButtonDown (const TPointD & pos, const TMouseEvent & e) override virtual
Reimplemented from TTool.
{
  TPointD pos = ppos;
  /*-- Sound --*/
  if (!doesApply()) return;
  if (m_activeAxis.getValue() == L"Position")
    if (e.isCtrlPressed())
      m_what = ZTranslation;
    else
      m_what = Translation;
  else if (m_activeAxis.getValue() == L"Scale")
    if (e.isCtrlPressed())
      m_what = ScaleXY;
    else
      m_what = Scale;
  else if (m_activeAxis.getValue() == L"All")
    onEditAllLeftButtonDown(pos, e);
  int scaleConstraint = 0;
  if (m_scaleConstraint.getValue() == L"A/R")
    scaleConstraint = ScaleConstraints::AspectRatio;
  else if (m_scaleConstraint.getValue() == L"Mass")
    scaleConstraint = ScaleConstraints::Mass;
  assert(m_dragTool == 0);
  if (m_highlightedDevice >= 1000) {
    m_dragTool = m_fxGadgetController->createDragTool(m_highlightedDevice);
  }
  if (!m_dragTool && transformEnabled()) {
    switch (m_what) {
    case Center:
      m_dragTool = new DragCenterTool(m_lockCenterX.getValue(),
                                      m_lockCenterY.getValue());
      break;
    case Translation:
      if (const TStroke *spline = getSpline())
        m_dragTool = new DragSplinePositionTool(
            spline, m_globalKeyframes.getValue(), getPixelSize());
      else
        m_dragTool = new DragPositionTool(m_lockPositionX.getValue(),
                                          m_lockPositionY.getValue(),
                                          m_globalKeyframes.getValue());
      break;
    case Rotation:
      m_dragTool = new DragRotationTool(m_lockRotation.getValue(),
                                        m_globalKeyframes.getValue());
      break;
    case Scale:
      m_dragTool = new DragIsotropicScaleTool(m_lockGlobalScale.getValue(),
                                              m_globalKeyframes.getValue());
      break;
    case ScaleXY:
      m_dragTool = new DragScaleTool(scaleConstraint, m_lockScaleH.getValue(),
                                     m_lockScaleV.getValue(),
                                     m_globalKeyframes.getValue());
      break;
    case Shear:
      m_dragTool =
          new DragShearTool(m_lockShearH.getValue(), m_lockShearV.getValue(),
                            m_globalKeyframes.getValue());
      break;
    case ZTranslation:
      m_dragTool = new DragZTool(m_viewer, m_globalKeyframes.getValue());
      break;
    }
  }
  if (m_dragTool) {
    m_dragTool->enableGlobalKeyframes(m_globalKeyframes.getValue());
    TUndoManager::manager()->beginBlock();
    m_dragTool->leftButtonDown(pos, e);
  }
  invalidate();
}
leftButtonDrag()
void EditTool::leftButtonDrag (const TPointD & pos, const TMouseEvent & e) override virtual
Reimplemented from TTool.
{
  if (!m_dragTool) return;
  m_dragTool->leftButtonDrag(pos, e);
  TTool::getApplication()->getCurrentObject()->notifyObjectIdChanged(true);
  invalidate();
}
leftButtonUp()
void EditTool::leftButtonUp (const TPointD & pos, const TMouseEvent & e) override virtual
Reimplemented from TTool.
{
  if (m_dragTool) {
    m_dragTool->leftButtonUp(pos, e);
    TUndoManager::manager()->endBlock();
    delete m_dragTool;
    m_dragTool = 0;
    TTool::getApplication()->getCurrentObject()->notifyObjectIdChanged(false);
  }
  m_keyFrameAdded = false;
}
mouseMove()
void EditTool::mouseMove (const TPointD & , const TMouseEvent & e) override virtual
Reimplemented from TTool.
{
  /*-- return while left dragging --*/
  if (e.isLeftButtonPressed()) return;
  /*-- Pick screen only when the FxGadget is displayed or
       when the "All" axis is selected. --*/
  int selectedDevice = -1;
  if (m_fxGadgetController->hasGadget() || m_activeAxis.getValue() == L"All")
    selectedDevice = pick(e.m_pos);
  if (selectedDevice <= 0) {
    selectedDevice = m_what;
    if (m_what == Translation && e.isCtrlPressed())
      selectedDevice = ZTranslation;
    else if (
        m_what == ZTranslation &&
        !e.isCtrlPressed()) /*--Z--*/
      selectedDevice = Translation;
    else if (m_what == Scale && e.isCtrlPressed())
      selectedDevice = ScaleXY;
    else if (m_what == ScaleXY && !e.isCtrlPressed())
      selectedDevice = Scale;
  }
  if (selectedDevice != m_highlightedDevice) {
    m_highlightedDevice = selectedDevice;
    m_fxGadgetController->selectById(selectedDevice);
    invalidate();
  }
  // for adding decoration to the cursor while pressing Alt key
  m_isAltPressed = e.isAltPressed();
}
onActivate()
void EditTool::onActivate () override virtual
Callback invoked whenever the tool activates.
Reimplemented from TTool.
{
  if (m_firstTime) {
    m_lockCenterX.setValue(LockCenterX ? 1 : 0);
    m_lockCenterY.setValue(LockCenterY ? 1 : 0);
    m_lockPositionX.setValue(LockPositionX ? 1 : 0);
    m_lockPositionY.setValue(LockPositionY ? 1 : 0);
    m_lockRotation.setValue(LockRotation ? 1 : 0);
    m_lockShearH.setValue(LockShearH ? 1 : 0);
    m_lockShearV.setValue(LockShearV ? 1 : 0);
    m_lockScaleH.setValue(LockScaleH ? 1 : 0);
    m_lockScaleV.setValue(LockScaleV ? 1 : 0);
    m_lockGlobalScale.setValue(LockGlobalScale ? 1 : 0);
    m_showEWNSposition.setValue(ShowEWNSposition ? 1 : 0);
    m_showZposition.setValue(ShowZposition ? 1 : 0);
    m_showSOposition.setValue(ShowSOposition ? 1 : 0);
    m_showRotation.setValue(ShowRotation ? 1 : 0);
    m_showGlobalScale.setValue(ShowGlobalScale ? 1 : 0);
    m_showHVscale.setValue(ShowHVscale ? 1 : 0);
    m_showShear.setValue(ShowShear ? 1 : 0);
    m_showCenterPosition.setValue(ShowCenterPosition ? 1 : 0);
    m_fxGadgetController = new FxGadgetController(this);
    /*
m_foo.setTool(this);
m_foo.setFxHandle(getApplication()->getCurrentFx());
*/
    m_firstTime = false;
  }
  TStageObjectId objId = getObjectId();
  if (objId == TStageObjectId::NoneId) {
    int index    = getColumnIndex();
    TXsheet *xsh = TTool::getApplication()->getCurrentXsheet()->getXsheet();
    if (index == -1)
      objId = TStageObjectId::CameraId(xsh->getCameraColumnIndex());
    else
      objId = TStageObjectId::ColumnId(index);
  }
  TTool::getApplication()->getCurrentObject()->setObjectId(objId);
}
References TTool::getColumnIndex(), and TTool::getObjectId().
onDeactivate()
void EditTool::onDeactivate () override virtual
Callback for tool deactivation, includes tool switch.
Reimplemented from TTool.
{
  if (m_dragTool) {
    m_dragTool->leftButtonUp();
    TUndoManager::manager()->endBlock();
    delete m_dragTool;
    m_dragTool = nullptr;
  }
}
onPropertyChanged()
bool EditTool::onPropertyChanged (std::string propertyName) override virtual
 Does the tasks associated to changes in \p propertyName and returns \p
true; Does the tasks associated to changes in propertyName and returns true.
Reimplemented from TTool.
{
  if (propertyName == m_lockCenterX.getName())
    LockCenterX = (int)m_lockCenterX.getValue();
  else if (propertyName == m_lockCenterY.getName())
    LockCenterY = (int)m_lockCenterY.getValue();
  else if (propertyName == m_lockPositionX.getName())
    LockPositionX = (int)m_lockPositionX.getValue();
  else if (propertyName == m_lockPositionY.getName())
    LockPositionY = (int)m_lockPositionY.getValue();
  else if (propertyName == m_lockRotation.getName())
    LockRotation = (int)m_lockRotation.getValue();
  else if (propertyName == m_lockShearH.getName())
    LockShearH = (int)m_lockShearH.getValue();
  else if (propertyName == m_lockShearV.getName())
    LockShearV = (int)m_lockShearV.getValue();
  else if (propertyName == m_lockScaleH.getName())
    LockScaleH = (int)m_lockScaleH.getValue();
  else if (propertyName == m_lockScaleV.getName())
    LockScaleV = (int)m_lockScaleV.getValue();
  else if (propertyName == m_lockGlobalScale.getName())
    LockGlobalScale = (int)m_lockGlobalScale.getValue();
  else if (propertyName == m_showEWNSposition.getName())
    ShowEWNSposition = (int)m_showEWNSposition.getValue();
  else if (propertyName == m_showZposition.getName())
    ShowZposition = (int)m_showZposition.getValue();
  else if (propertyName == m_showSOposition.getName())
    ShowSOposition = (int)m_showSOposition.getValue();
  else if (propertyName == m_showRotation.getName())
    ShowRotation = (int)m_showRotation.getValue();
  else if (propertyName == m_showGlobalScale.getName())
    ShowGlobalScale = (int)m_showGlobalScale.getValue();
  else if (propertyName == m_showHVscale.getName())
    ShowHVscale = (int)m_showHVscale.getValue();
  else if (propertyName == m_showShear.getName())
    ShowShear = (int)m_showShear.getValue();
  else if (propertyName == m_showCenterPosition.getName())
    ShowCenterPosition = (int)m_showCenterPosition.getValue();
  /*-- Active Axis  --*/
  else if (propertyName == m_activeAxis.getName()) {
    std::wstring activeAxis = m_activeAxis.getValue();
    if (activeAxis == L"Position")
      m_what = Translation;
    else if (activeAxis == L"Rotation")
      m_what = Rotation;
    else if (activeAxis == L"Scale")
      m_what = Scale;
    else if (activeAxis == L"Shear")
      m_what = Shear;
    else if (activeAxis == L"Center")
      m_what = Center;
    else if (activeAxis == L"All")
      m_what = None;
  }
  return true;
}
transformEnabled()
bool EditTool::transformEnabled () const
{
  // check if the column transformation is enabled
  TXsheet *xsh = getXsheet();
  TStageObjectId objId(getObjectId());
  TStageObject *pegbar = xsh->getStageObject(objId);
  return (!objId.isColumn() || hasVisibleChildColumn(pegbar, xsh));
}
updateEnabled()
QString EditTool::updateEnabled (int rowIndex, int columnIndex) override virtual
Reimplemented from TTool.
{
  // toolType = TTool::ColumnTool
  // targetType = TTool::AllTargets;
  // Disable every tool during playback
  if (m_application->getCurrentFrame()->isPlaying())
    return (enable(false), QString());
  // Disable in Level Strip
  if (m_application->getCurrentFrame()->isEditingLevel())
    return (
        enable(false),
        QObject::tr("The current tool cannot be used in Level Strip mode."));
  // if an object other than column is selected, then enable the tool
  // regardless of the current column state
  TStageObjectId objId = m_application->getCurrentObject()->getObjectId();
  if (!objId.isColumn()) return (enable(true), QString());
  // Retrieve vars and view modes
  TXsheet *xsh = m_application->getCurrentXsheet()->getXsheet();
  // if a column object is selected, switch the inspected column to it
  TXshColumn *column = xsh->getColumn(objId.getIndex());
  // disable if the column is empty
  if (!column || column->isEmpty()) return (enable(false), QString());
  if (column->getSoundColumn())
    return (enable(false),
            QObject::tr("It is not possible to edit the audio column."));
  else if (column->getSoundTextColumn())
    return (enable(false),
            QObject::tr(
                "Note columns can only be edited in the xsheet or timeline."));
  // Enable to control Fx gadgets even on the locked or hidden columns
  if (m_fxGadgetController && m_fxGadgetController->hasGadget())
    return (enable(true), QString());
  // Check against unplaced columns
  if (column->isLocked())
    return (enable(false), QObject::tr("The current column is locked."));
  // check if the current column and all of its child columns are hidden
  if (!hasVisibleChildColumn(xsh->getStageObject(objId), xsh))
    return (enable(false), QObject::tr("The current column is hidden."));
  return (enable(true), QString());
}
updateMatrix()
void EditTool::updateMatrix () inline override virtual
Updates the current matrix transformation with the actual column matrix transformation.
See also
getCurrentColumnMatrix().
Reimplemented from TTool.
{
    setMatrix(
        getCurrentObjectParentMatrix2());  // getCurrentObjectParentMatrix());
  }
updateTranslation()
void EditTool::updateTranslation () override virtual
Reimplemented from TTool.
{
  m_scaleConstraint.setQStringName(tr("Scale Constraint:"));
  m_scaleConstraint.setItemUIName(L"None", tr("None"));
  m_scaleConstraint.setItemUIName(L"A/R", tr("A/R"));
  m_scaleConstraint.setItemUIName(L"Mass", tr("Mass"));
  m_autoSelect.setQStringName(tr("Auto Select Column"));
  m_autoSelect.setItemUIName(L"None", tr("None"));
  m_autoSelect.setItemUIName(L"Column", tr("Column"));
  m_autoSelect.setItemUIName(L"Pegbar", tr("Pegbar"));
  m_globalKeyframes.setQStringName(tr("Global Key"));
  m_lockCenterX.setQStringName(tr("Lock Center X"));
  m_lockCenterY.setQStringName(tr("Lock Center Y"));
  m_lockPositionX.setQStringName(tr("Lock Position X"));
  m_lockPositionY.setQStringName(tr("Lock Position Y"));
  m_lockRotation.setQStringName(tr("Lock Rotation"));
  m_lockShearH.setQStringName(tr("Lock Shear H"));
  m_lockShearV.setQStringName(tr("Lock Shear V"));
  m_lockScaleH.setQStringName(tr("Lock Scale H"));
  m_lockScaleV.setQStringName(tr("Lock Scale V"));
  m_lockGlobalScale.setQStringName(tr("Lock Global Scale"));
  m_showEWNSposition.setQStringName(tr("X and Y Positions"));
  m_showZposition.setQStringName(tr("Z Position"));
  m_showSOposition.setQStringName(tr("SO"));
  m_showRotation.setQStringName(tr("Rotation"));
  m_showGlobalScale.setQStringName(tr("Global Scale"));
  m_showHVscale.setQStringName(tr("Horizontal and Vertical Scale"));
  m_showShear.setQStringName(tr("Shear"));
  m_showCenterPosition.setQStringName(tr("Center Position"));
  m_activeAxis.setQStringName(tr("Active Axis"));
  m_activeAxis.setItemUIName(L"Position", tr("Position"));
  m_activeAxis.setItemUIName(L"Rotation", tr("Rotation"));
  m_activeAxis.setItemUIName(L"Scale", tr("Scale"));
  m_activeAxis.setItemUIName(L"Shear", tr("Shear"));
  m_activeAxis.setItemUIName(L"Center", tr("Center"));
  m_activeAxis.setItemUIName(L"All", tr("All"));
}
The documentation for this class was generated from the following file:
E:/opentoonz/toonz/sources/tnztools/edittool.cpp