opentoonz: TXsheet Class Reference
TXsheet Class Reference final
#include <txsheet.h>
Classes
class SoundProperties
struct TXsheetImp
Public Member Functions
unsigned long id () const
Returns a unique identifier associated with the xsheet instance.
int getFrameCount () const
bool isRectEmpty (const CellPosition &pos0, const CellPosition &pos1) const
const TXshCell & getCell (int row, int col) const
const TXshCell & getCell (const CellPosition &pos) const
bool setCell (int row, int col, const TXshCell &cell)
void getCells (int row, int col, int rowCount, TXshCell cells[]) const
bool setCells (int row, int col, int rowCount, const TXshCell cells[])
void insertCells (int row, int col, int rowCount=1)
void removeCells (int row, int col, int rowCount=1)
void clearCells (int row, int col, int rowCount=1)
void clearAll ()
int getCellRange (int col, int &r0, int &r1) const
int getMaxFrame (int col) const
bool isColumnEmpty (int col) const
void getUsedLevels (std::set< TXshLevel * > &levels) const
bool isLevelUsed (TXshLevel *) const
TStageObject * getStageObject (const TStageObjectId &id) const
TStageObjectTree * getStageObjectTree () const
TAffine getPlacement (const TStageObjectId &id, int frame) const
double getZ (const TStageObjectId &id, int frame) const
double getNoScaleZ (const TStageObjectId &id) const
TAffine getParentPlacement (const TStageObjectId &id, int frame) const
TPointD getCenter (const TStageObjectId &id, int frame) const
void setCenter (const TStageObjectId &id, int frame, const TPointD &center)
TStageObjectId getStageObjectParent (const TStageObjectId &id)
void setStageObjectParent (const TStageObjectId &id, const TStageObjectId &parentId)
bool hasChildren (const TStageObjectId &id) const
TAffine getCameraAff (int frame) const
void reverseCells (int r0, int c0, int r1, int c1)
void swingCells (int r0, int c0, int r1, int c1)
bool incrementCells (int r0, int c0, int r1, int c1, std::vector< std::pair< TRect, TXshCell > > &forUndo)
void duplicateCells (int r0, int c0, int r1, int c1, int upTo)
void stepCells (int r0, int c0, int r1, int c1, int type)
void increaseStepCells (int r0, int c0, int &r1, int c1)
void decreaseStepCells (int r0, int c0, int &r1, int c1)
void resetStepCells (int r0, int c0, int r1, int c1)
void eachCells (int r0, int c0, int r1, int c1, int type)
void rollupCells (int r0, int c0, int r1, int c1)
void rolldownCells (int r0, int c0, int r1, int c1)
void timeStretch (int r0, int c0, int r1, int c1, int nr)
int reframeCells (int r0, int r1, int col, int type, int withBlank=-1)
int exposeLevel (int row, int col, TXshLevel *xl, bool overwrite=false)
int exposeLevel (int row, int col, TXshLevel *xl, std::vector< TFrameId > &fIds_, TFrameId xFrom=TFrameId(), TFrameId xTo=TFrameId(), int step=-1, int inc=-1, int frameCount=-1, bool doesFileActuallyExist=true)
void exposeLevel (int row, int col, TXshLevel *xl, std::vector< TFrameId > fids, bool overwrite)
void updateFrameCount ()
void loadData (TIStream &is) override
void saveData (TOStream &os) override
void insertColumn (int index, TXshColumn::ColumnType type=TXshColumn::eLevelType)
void insertColumn (int index, TXshColumn *column)
void removeColumn (int index)
void moveColumn (int srcIndex, int dstIndex)
TXshColumn * getColumn (int index) const
int getColumnCount () const
int getFirstFreeColumnIndex () const
TSoundTrack * makeSound (SoundProperties *properties)
void scrub (int frame, bool isPreview=false)
void stopScrub ()
void play (TSoundTrackP soundtrack, int s0, int s1, bool loop)
FxDag * getFxDag () const
ColumnFan * getColumnFan (const Orientation *o) const
ToonzScene * getScene () const
void setScene (ToonzScene *scene)
TXshNoteSet * getNotes () const
bool checkCircularReferences (const TXshCell &cellCandidate)
bool checkCircularReferences (TXshColumn *columnCandidate)
void invalidateSound ()
TRectD getBBox (int row) const
Returns the xsheet content's camstand bbox at the specified row.
void autoInputCellNumbers (int increment, int interval, int step, int repeat, int from, int to, int r0, int r1, bool isOverwrite, std::vector< int > columnIndices, std::vector< TXshLevelP > levels, int rowsCount)
void setCameraColumnIndex (int index)
int getCameraColumnIndex ()
void setCameraColumnLocked (bool locked)
bool isCameraColumnLocked ()
ExpressionReferenceMonitor * getExpRefMonitor () const
void setObserver (TXsheetColumnChangeObserver *observer)
void notify (const TXsheetColumnChange &change)
void notifyFxAdded (const std::vector< TFx * > &fxs)
void notifyStageObjectAdded (const TStageObjectId id)
bool isReferenceManagementIgnored (TDoubleParam *)
Public Member Functions inherited from TSmartObject
TSmartObject (ClassCode classCode)
void addRef ()
void release ()
TINT32 getRefCount () const
Public Member Functions inherited from TPersist
virtual void loadData (TIStream &is)=0
virtual void saveData (TOStream &os)=0
std::string getStreamTag () const
virtual const TPersistDeclaration * getDeclaration () const =0
Protected Member Functions
bool checkCircularReferences (TXsheet *childCandidate)
Additional Inherited Members
Public Types inherited from TSmartObject
typedef short ClassCode
Public Types inherited from TPersist
typedef TPersist * CreateProc()
Static Public Member Functions inherited from TSmartObject
static TINT32 getInstanceCount (ClassCode code)
Static Public Member Functions inherited from TPersist
static void declare (CreateProc *)
static TPersist * create (const std::string &name)
Detailed Description
This is the base class for an xsheet. An Xsheet is composed of columns of frames.
Inherits TSmartObject and TPersist.
    The class provides a collection of functions that returns xsheet
elements, defined in struct TXsheetImp, and enables manipulation of these. Most important xsheet elements are: a column set TColumnSetT, a pegbar tree TStageObjectTree, a fx dag FxDag, a sound track TSoundTrack and a scene ToonzScene.
            For purposes of this class, a Column is a graphics layer, and a
row is a frame number. (Whether horizontal or vertical is a matter of displaying).
A column set contains all xsheet columns. A collection of functions, concerning column set, allows to manage xsheet column. It's possible to know xsheet column count, getColumnCount(), know first non empty column index, getFirstFreeColumnIndex(), or know if column in datum index is empty, isColumnEmpty(). You can work on single xsheet column, getColumn(), using its indexes: insert and remove a column with insertColumn() and removeColumn() or move column from an index to another using moveColumn().
    You can manage also column visualization in xsheet, using the xsheet
object ColumnFan getColumnFan(), and find column icon getColumnIcon().
    cell positions will be identified by a pair of row+column index,
which is a separate class.
    It's possible work on xsheet cells directly, getCell() and setCell() or
getCells() and setCells(); cells are identified in xsheet by two index one for row and one for column. You can insert, remove or clear cells using insertCells(), removeCells() or clearCells(); the difference between the remove and the clear function is the shift of remains cells. Also there are functions to manipulate cells reverseCells(), swingCells(), incrementCells(), duplicateCells(), int upTo, stepCells(), eachCells().
About pegbar tree TStageObjectTree, it's possible to manage it through the stage object's related functions.
The fx dag FxDag getFxDag() is not managed with direct functions but is always up to date; in fact same functions update it. For example insertColumn(), if necessary, insert column index in fx dag, the same happen in setCells().
The sound track TSoundTrack contain a mixed sound, computed using makeSound(), of all TXshSoundColumn present in xsheet.
It's possible take and know the scene ToonzScene to which the xsheet refers using getScene() and setScene().
Constructor & Destructor Documentation
TXsheet()
TXsheet::TXsheet ()
    : TSmartObject(m_classCode)
    , m_player(0)
    , m_imp(new TXsheet::TXsheetImp)
    , m_notes(new TXshNoteSet())
    , m_cameraColumnIndex(0)
    , m_observer(nullptr) {
  // extern TSyntax::Grammar *createXsheetGrammar(TXsheet*);
  m_soundProperties      = new TXsheet::SoundProperties();
  m_imp->m_handleManager = new XshHandleManager(this);
  m_imp->m_pegTree->setHandleManager(m_imp->m_handleManager);
  m_imp->m_pegTree->createGrammar(this);
  // Dummy camera column
  m_cameraColumn          = TXshColumn::createEmpty(0);
  m_cameraColumn->m_index = -1;
  m_cameraColumn->setXsheet(this);
}
~TXsheet()
TXsheet::~TXsheet ()
                  {
  texture_utils::invalidateTextures(this);
  assert(m_imp);
  if (m_notes) delete m_notes;
  if (m_soundProperties) delete m_soundProperties;
}
Member Function Documentation
autoInputCellNumbers()
void TXsheet::autoInputCellNumbers (int increment, int interval, int step, int repeat, int from, int to, int r0, int r1, bool isOverwrite, std::vector< int > columnIndices, std::vector< TXshLevelP > levels, int rowsCount)
{
  int rowUpTo = (r1 == -1) ? rowsCount - 1
                           : ((isOverwrite) ? std::min(r1, r0 + rowsCount - 1)
                                            : r0 + rowsCount - 1);
  // for each column
  for (int c = 0; c < columnIndices.size(); c++) {
    int columnIndex  = columnIndices.at(c);
    TXshLevelP level = levels.at(c);
    // on insertion, insert empty cells first
    if (!isOverwrite) insertCells(r0, columnIndex, rowsCount);
    // obtain fids to be input
    std::vector<TFrameId> fids;
    if (increment == 0) {
      std::vector<TFrameId> wholeFids;
      level->getFids(wholeFids);
      if (from <= to) {
        for (auto itr = wholeFids.begin(); itr != wholeFids.end(); ++itr) {
          if ((*itr).getNumber() >= from && (*itr).getNumber() <= to)
            fids.push_back(*itr);
          else if ((*itr).getNumber() > to)
            break;
        }
      } else {  // from > to
        for (auto itr = wholeFids.rbegin(); itr != wholeFids.rend(); ++itr) {
          if ((*itr).getNumber() <= from && (*itr).getNumber() >= to)
            fids.push_back(*itr);
          else if ((*itr).getNumber() < to)
            break;
        }
      }
    } else {  // increment != 0
      int f = from;
      if (from <= to) {
        while (f <= to) {
          fids.push_back(TFrameId(f));
          f += increment;
        }
      } else {  // from > to
        while (f >= to) {
          fids.push_back(TFrameId(f));
          f -= increment;
        }
      }
    }
    // input cells
    int row             = r0;
    int repeat_itr      = 0;
    int fid_itr         = 0;
    int step_interv_itr = 0;
    while (row <= rowUpTo) {
      // input cell
      if (step_interv_itr < step)
        setCell(row, columnIndex, TXshCell(level, fids.at(fid_itr)));
      // .. or set empty cell as interval
      else
        setCell(row, columnIndex, TXshCell());
      // increment
      step_interv_itr++;
      // next frame
      if (step_interv_itr == step + interval) {
        fid_itr++;
        step_interv_itr = 0;
      }
      // next repeat cycle
      if (fid_itr == fids.size()) {
        repeat_itr++;
        fid_itr = 0;
      }
      if (repeat_itr == repeat) break;
      row++;
    }
  }
}
checkCircularReferences() [1/3]
bool TXsheet::checkCircularReferences (const TXshCell & cellCandidate)
Returns true if the cellCandidate creates a circular reference. A circular reference is obtained when cellCandidate is a subXsheet cell and contains or matches with this XSheet.
{
  if (cellCandidate.isEmpty() || !cellCandidate.m_level->getChildLevel())
    return false;
  TXsheet *childCandidate = cellCandidate.m_level->getChildLevel()->getXsheet();
  return checkCircularReferences(childCandidate);
}
References checkCircularReferences(), TXshLevel::getChildLevel(), TXshChildLevel::getXsheet(), and TXshCell::isEmpty().
Referenced by checkCircularReferences(), and StageObjectsData::checkCircularReferences().
checkCircularReferences() [2/3]
bool TXsheet::checkCircularReferences (TXshColumn * columnCandidate)
Returns true if the columnCandidate creates a circular reference. A circular reference is obtained when columnCandidate is a subXsheet column and contains or matches with this XSheet.
{
  if (!columnCandidate || !columnCandidate->getLevelColumn()) return false;
  TXshLevelColumn *lc = columnCandidate->getLevelColumn();
  int r0 = 0, r1 = -1;
  if (lc->getRange(r0, r1) <= 0) return false;
  int r;
  TXshCell oldCell;
  for (r = r0; r <= r1; r++) {
    TXshCell cell = lc->getCell(r);
    // to speed up:
    if (cell.m_level.getPointer() == oldCell.m_level.getPointer()) continue;
    if (checkCircularReferences(cell)) return true;
    oldCell = cell;
  }
  return false;
}
References checkCircularReferences(), TXshCellColumn::getCell(), and TXshCellColumn::getRange().
checkCircularReferences() [3/3]
bool TXsheet::checkCircularReferences (TXsheet * childCandidate) protected
{
  if (this == childCandidate) return true;
  if (childCandidate == 0) return false;
  int i;
  for (i = 0; i < childCandidate->getColumnCount(); i++)
    if (checkCircularReferences(childCandidate->getColumn(i))) return true;
  return false;
}
clearAll()
void TXsheet::clearAll ()
Clears xsheet. It sets to default values all xsheet elements contained in struct TXsheetImp.
                       {
  int c0 = 0, c1 = m_imp->m_columnSet.getColumnCount() - 1;
  int r0 = 0, r1 = getFrameCount() - 1;
  m_imp->m_columnSet.clear();
  if (m_imp->m_pegTree) {
    delete m_imp->m_pegTree;
    m_imp->m_pegTree = new TStageObjectTree();
    m_imp->m_pegTree->setHandleManager(m_imp->m_handleManager);
    m_imp->m_pegTree->createGrammar(this);
  }
  if (m_imp->m_fxDag) {
    delete m_imp->m_fxDag;
    m_imp->m_fxDag = new FxDag();
  }
  m_imp->m_frameCount = 0;
  m_imp->m_mixedSound = 0;
}
References getFrameCount().
Referenced by ChildStack::clear(), and loadData().
clearCells()
void TXsheet::clearCells (int row, int col, int rowCount = 1)
If column identified by index col is not empty, is a TXshCellColumn and is not locked, clear rowCount cells starting from row and it recalls TXshCellColumn::clearCells(). Clears cells and it shifts remaining cells. Xsheet's frame count is updated.
See also
removeCells(), insertCells()
{
  const TXshColumnP &column = m_imp->m_columnSet.getColumn(col);
  if (!column || column->isLocked()) return;
  TXshCellColumn *xshCellColumn = column->getCellColumn();
  if (!xshCellColumn) return;
  int oldColRowCount = xshCellColumn->getMaxFrame() + 1;
  xshCellColumn->clearCells(row, rowCount);
  // aggiornamento framecount
  if (oldColRowCount == m_imp->m_frameCount) updateFrameCount();
}
References TXshCellColumn::clearCells(), TXshCellColumn::getMaxFrame(), and updateFrameCount().
Referenced by eachCells(), reframeCells(), and stepCells().
decreaseStepCells()
void TXsheet::decreaseStepCells (int r0, int c0, int & r1, int c1)
For each sequence of frame with same number, contained in rect delimited by first row r0, last row r1 and first column c0, a frame with same number is removed.
{
  int c, size = r1 - r0 + 1;
  QList<int> ends;
  for (c = c0; c <= c1; c++) {
    int r = r0, i = 0, rEnd = r1;
    while (r <= rEnd) {
      TXshCell cell = getCell(CellPosition(r, c));
      if (!cell.isEmpty()) {
        r++;
        bool removed = false;
        while (cell == getCell(CellPosition(r, c)) && r <= rEnd) {
          if (!removed) {
            removed = true;
            removeCells(r, c);
            rEnd--;
          } else
            r++;
        }
      } else
        r++;
      i++;
    }
    ends.append(rEnd);
  }
  if (ends.isEmpty()) return;
  // controllo se devo cambiare la selezione
  bool allDecreaseIsEqual = true;
  for (c = 0; c < ends.size() - 1 && allDecreaseIsEqual; c++)
    allDecreaseIsEqual = allDecreaseIsEqual && ends[c] == ends[c + 1];
  if (allDecreaseIsEqual) r1 = ends[0];
}
References getCell(), TXshCell::isEmpty(), and removeCells().
duplicateCells()
void TXsheet::duplicateCells (int r0, int c0, int r1, int c1, int upTo)
A copy of cells, contained in rect delimited by first row r0, last row r1 and first column c0, is made in row cells from r1+1 to upTo. The duplicated cells will be inserted by shifting the other down.
{
  assert(upTo >= r1 + 1);
  int chunk = r1 - r0 + 1;
  for (int j = c0; j <= c1; j++) {
    insertCells(r1 + 1, j, upTo - (r1 + 1) + 1);
    for (int i = r1 + 1; i <= upTo; i++)
      setCell(i, j, getCell(CellPosition(r0 + ((i - (r1 + 1)) % chunk), j)));
  }
}
References getCell(), and insertCells().
eachCells()
void TXsheet::eachCells (int r0, int c0, int r1, int c1, int type)
Only one cell each step type, of the cells, contained in rect delimited by first row r0, last row r1 and first column c0, are preserved, the others are deleted.
{
  int nr = r1 - r0 + 1;
  int nc = c1 - c0 + 1;
  if (nr < type || nc <= 0) return;
  int newRows = nr % type ? nr / type + 1 : nr / type;
  int size = newRows * nc;
  assert(size > 0);
  std::unique_ptr<TXshCell[]> cells(new TXshCell[size]);
  assert(cells);
  int i, j, k;
  for (j = r0, i = 0; i < size;
       j += type)  // in cells copio il contenuto delle celle che mi interessano
  {
    for (k = c0; k <= c1; k++, i++) cells[i] = getCell(CellPosition(j, k));
  }
  int c;
  for (c = c0; c <= c1; ++c) removeCells(r0 + newRows, c, nr - newRows);
  for (i = r0, k = 0; i < r0 + newRows && k < size; i++)
    for (j = c0; j <= c1; j++) {
      //----110523 iwasawa
      // Each
      if (cells[k].isEmpty())
        clearCells(i, j);
      else
        setCell(i, j, cells[k]);
      k++;
    }
}
References clearCells(), getCell(), and removeCells().
exposeLevel() [1/3]
int TXsheet::exposeLevel (int row, int col, TXshLevel * xl, bool overwrite = false)
Exposes level xl in xsheet starting from cell identified by row and col. Returns the number of the inserted cells.
{
  if (!xl) return 0;
  std::vector<TFrameId> fids;
  xl->getFids(fids);
  int frameCount = 1;
  if (fids.empty()) {
    setCell(row, col, TXshCell(xl, TFrameId(1)));
    updateFrameCount();
    return frameCount;
  }
  exposeLevel(row, col, xl, fids, overwrite);
  return (int)fids.size();
}
References exposeLevel(), and updateFrameCount().
Referenced by VectorizerPopup::apply(), SaveLevelAsPopup::execute(), and exposeLevel().
exposeLevel() [2/3]
int TXsheet::exposeLevel (int row, int col, TXshLevel * xl, std::vector< TFrameId > & fIds_, TFrameId xFrom = TFrameId(), TFrameId xTo = TFrameId(), int step = -1, int inc = -1, int frameCount = -1, bool doesFileActuallyExist = true)
{
  if (!xl) return 0;
  std::vector<TFrameId> fids;
  if (doesFileActuallyExist)
    xl->getFids(fids);
  else {
    for (int i = 0; i < (int)fIds_.size(); i++) {
      fids.push_back(fIds_[i]);
    }
  }
  // multiple exposing
  if (frameCount < 0 || xFrom < 0 || xTo < 0 || step < 0 || inc < 0) {
    insertCells(row, col, xl->getFrameCount());
    frameCount = 1;
    if (fids.empty())
      setCell(row, col, TXshCell(xl, TFrameId(1)));
    else {
      frameCount = (int)fids.size();
      insertCells(row, col, frameCount);
      std::vector<TFrameId>::iterator it;
      for (it = fids.begin(); it != fids.end(); ++it)
        setCell(row++, col, TXshCell(xl, *it));
    }
    updateFrameCount();
    return frameCount;
  }
  // single exposing
  insertCells(row, col, frameCount);
  if (fids.empty()) {
    setCell(row, col, TXshCell(xl, TFrameId(1)));
  } else {
    if (inc == 0)  // inc = Auto
    {
      std::vector<TFrameId>::iterator it;
      it = fids.begin();
      while (*it < xFrom) it++;
      if (step == 0)  // Step = Auto
      {
        std::vector<TFrameId>::iterator next_it;
        next_it = it;
        next_it++;
        for (int f = 0; f < frameCount; f++) {
          setCell(row++, col, TXshCell(xl, *it));
          if (next_it != fids.end()) {
            it++;
            next_it++;
          }
        }
      }
      else  // Step != Auto
      {
        int loopCount = frameCount / step;
        for (int loop = 0; loop < loopCount; loop++) {
          for (int s = 0; s < step; s++) {
            setCell(row++, col, TXshCell(xl, *it));
          }
          it++;
        }
      }
    } else  // inc != Auto
    {
      int loopCount;
      if (step == 0)  // Step = Auto
        step = inc;
      loopCount = frameCount / step;
      for (int loop = 0; loop < loopCount; loop++) {
        TFrameId id(xFrom.getNumber() + loop * inc, xFrom.getLetter());
        for (int s = 0; s < step; s++) {
          setCell(row++, col, TXshCell(xl, id));
        }
      }
    }
  }
  updateFrameCount();
  return frameCount;
}
exposeLevel() [3/3]
void TXsheet::exposeLevel (int row, int col, TXshLevel * xl, std::vector< TFrameId > fids, bool overwrite)
Exposes level xl fids in xsheet starting from cell identified by row and col.
{
  int frameCount = (int)fids.size();
  if (!overwrite) insertCells(row, col, frameCount);
  std::vector<TFrameId>::iterator it;
  for (it = fids.begin(); it != fids.end(); ++it)
    setCell(row++, col, TXshCell(xl, *it));
  updateFrameCount();
}
References insertCells(), and updateFrameCount().
getBBox()
TRectD TXsheet::getBBox (int row) const
Returns the xsheet content's camstand bbox at the specified row.
{
  static const double maxDouble = (std::numeric_limits<double>::max)();
  static const TRectD voidRect(maxDouble, maxDouble, -maxDouble, -maxDouble);
  //-----------------------------------------------------------------------
  struct locals {
    static TRectD getBBox(const TXsheet *xsh, int r, int c) {
      // Discriminate cell content
      const TXshCell &cell = xsh->getCell(CellPosition(r, c));
      if (cell.isEmpty()) return voidRect;
      if (TXshChildLevel *cl = cell.getChildLevel())
        return cl->getXsheet()->getBBox(cell.getFrameId().getNumber() - 1);
      TXshSimpleLevel *sl = cell.getSimpleLevel();
      if (!sl ||
          !(sl->getType() &
            LEVELCOLUMN_XSHLEVEL))  // Avoid other mesh levels - which could
        return voidRect;            // be deformed too...
      // Retrieve column affine
      TAffine columnZaff;
      {
        TStageObject *colObj = xsh->getStageObject(TStageObjectId::ColumnId(c));
        const TAffine &columnAff = colObj->getPlacement(r);  // ...
        double columnZ           = colObj->getZ(r);          // ...
        double columnNoScaleZ    = colObj->getGlobalNoScaleZ();
        TStageObjectId cameraId =
            xsh->getStageObjectTree()->getCurrentCameraId();
        TStageObject *camera = xsh->getStageObject(cameraId);
        const TAffine &cameraAff = camera->getPlacement(r);  // ...
        double cameraZ           = camera->getZ(r);          // ...
        if (!TStageObject::perspective(columnZaff, cameraAff, cameraZ,
                                       columnAff, columnZ, columnNoScaleZ))
          return voidRect;
      }
      const TRectD &bbox = sl->getBBox(cell.getFrameId());
      if (bbox.getLx() <= 0.0 || bbox.getLy() <= 0.0) return voidRect;
      return columnZaff * TScale(Stage::inch, Stage::inch) * bbox;
    }
  };
  //-----------------------------------------------------------------------
  // Initialize a union-neutral rect
  TRectD bbox(voidRect);
  // Traverse the xsheet's columns, adding the bbox of each
  int c, cCount = getColumnCount();
  for (c = 0; c != cCount; ++c) {
    // Skip empty or invisible columns
    TXshColumn *column = getColumn(c);
    if (column->isEmpty() || !column->isCamstandVisible()) continue;
    const TRectD &colBBox = locals::getBBox(this, r, c);
    // Make the union
    bbox.x0 = std::min(bbox.x0, colBBox.x0);
    bbox.y0 = std::min(bbox.y0, colBBox.y0);
    bbox.x1 = std::max(bbox.x1, colBBox.x1);
    bbox.y1 = std::max(bbox.y1, colBBox.y1);
  }
  return bbox;
}
References TXshSimpleLevel::getBBox(), getBBox(), getCell(), TXshCell::getChildLevel(), getColumn(), getColumnCount(), TStageObjectTree::getCurrentCameraId(), TXshCell::getFrameId(), TStageObject::getGlobalNoScaleZ(), TXshCell::getSimpleLevel(), getStageObject(), getStageObjectTree(), TXshLevel::getType(), TStageObject::getZ(), Stage::inch, TXshCell::isEmpty(), TStageObject::perspective(), and TRectT< T >::x0.
Referenced by getBBox(), and texture_utils::getTextureData().
getCameraAff()
TAffine TXsheet::getCameraAff (int frame) const
Returns current camera's transformation matrix TAffine related to frame frame, inclusive of zdepth. It Doesn't take care of transformation matrix related to pegbar linked to camera.
Note
Used only in tab code, "the Tab" has just one camera while "Toonz 5.2 Harlequin" manages several camera.
{
  TStageObjectId cameraId = getStageObjectTree()->getCurrentCameraId();
  TAffine cameraAff       = getPlacement(cameraId, frame);
  double cameraZ          = getZ(cameraId, frame);
  TAffine aff             = cameraAff * TScale((1000 + cameraZ) / 1000);
  return aff;
}
References TStageObjectTree::getCurrentCameraId(), getPlacement(), getStageObjectTree(), and getZ().
Referenced by SceneViewer::getViewMatrix().
getCameraColumnIndex()
int TXsheet::getCameraColumnIndex () inline
{ return m_cameraColumnIndex; }
getCell() [1/2]
const TXshCell & TXsheet::getCell (const CellPosition & pos) const
{
  static const TXshCell emptyCell;
  TXshColumnP column = m_imp->m_columnSet.getColumn(pos.layer());
  if (!column) return emptyCell;
  TXshCellColumn *xshColumn = column->getCellColumn();
  if (!xshColumn) return emptyCell;
  return xshColumn->getCell(pos.frame());
}
getCell() [2/2]
const TXshCell & TXsheet::getCell (int row, int col) const
Returns the TXshCell cell in row identified by index row and column identified by index col. If column TXshColumnP in col is empty return an empty cell.
See also
setCell(), getCells(), setCells()
{
  return getCell(CellPosition(row, col));
}
References getCell().
Referenced by StageBuilder::addCell(), StageBuilder::addCellWithOnionSkin(), VectorizerPopup::apply(), XsheetViewer::areSoundCellsSelected(), ChildStack::closeChild(), ChildStack::createChild(), decreaseStepCells(), PlasticDeformerFx::doDryCompute(), HookTool::draw(), SkeletonTool::draw(), duplicateCells(), eachCells(), ExportLevelPopup::execute(), SaveLevelAsPopup::execute(), ReplaceLevelPopup::execute(), ReplaceParentDirectoryPopup::execute(), getBBox(), getCell(), TTool::getCurrentFid(), TApp::getCurrentImageType(), increaseStepCells(), incrementCells(), isRectEmpty(), TTool::notifyImageChanged(), XsheetGUI::CellArea::onReplaceByCastedLevel(), ChildStack::openChild(), reframeCells(), resetStepCells(), rolldownCells(), rollupCells(), stepCells(), swingCells(), TTool::touchImage(), LevelSettingsPopup::updateLevelSettings(), and Toolbar::updateToolbar().
getCellRange()
int TXsheet::getCellRange (int col, int & r0, int & r1) const
Returns cell range of column identified by index col and set r0 and r1 respectively to first and last not empty cell, it then recalls TXshCellColumn::getRange(). If column is empty or is not a TXshCellColumn this method returns zero and sets r0 to 0 and r1 to -1.
{
  r0                 = 0;
  r1                 = -1;
  TXshColumnP column = m_imp->m_columnSet.getColumn(col);
  if (!column) return 0;
  TXshCellColumn *cellColumn = column->getCellColumn();
  if (!cellColumn) return 0;
  return cellColumn->getRange(r0, r1);
}
References TXshCellColumn::getRange().
Referenced by ExportLevelPopup::execute(), SaveLevelAsPopup::execute(), TApp::getCurrentImageType(), ChildStack::openChild(), TTool::touchImage(), LevelSettingsPopup::updateLevelSettings(), and Toolbar::updateToolbar().
getCells()
void TXsheet::getCells (int row, int col, int rowCount, TXshCell cells[]) const
Set cells[] to rowCount cells of column identified by index col starting from row identified by index row. If column is empty or is not a TXshCellColumn set cells[] to rowCount empty cells.
See also
getCells(), setCells(), getCell()
{
  static const TXshCell emptyCell;
  int i;
  TXshColumnP column = m_imp->m_columnSet.getColumn(col);
  if (!column) {
    for (i = 0; i < rowCount; i++) cells[i] = emptyCell;
    return;
  }
  TXshCellColumn *xshColumn = column->getCellColumn();
  if (!xshColumn) {
    for (i = 0; i < rowCount; i++) cells[i] = emptyCell;
    return;
  }
  xshColumn->getCells(row, rowCount, cells);
}
Referenced by timeStretch().
getCenter()
TPointD TXsheet::getCenter (const TStageObjectId & id, int frame) const
Returns the center related to pegbar TStageObject with id TStageObjectId specialization in frame frame; it calls TStageObject::getCenter().
See also
setCenter()
{
  assert(id != TStageObjectId::NoneId);
  return m_imp->m_pegTree->getStageObject(id)->getCenter(frame);
}
Referenced by Skeleton::build(), and EditTool::draw().
getColumn()
TXshColumn * TXsheet::getColumn (int index) const
Returns a pointer to the TXshColumn identified in xsheet by index index.
{
  if (col < 0) return m_cameraColumn;
  return m_imp->m_columnSet.getColumn(col).getPointer();
}
Referenced by StageBuilder::addCell(), StageBuilder::addFrame(), TCellData::canChange(), getBBox(), TCellData::getCells(), TApp::getCurrentImageType(), ToonzScene::getSoundColumns(), getUsedLevels(), ColorModelViewer::loadCurrentFrame(), moveColumn(), removeColumn(), TColumnDataElement::restoreColumn(), FxsData::setFxs(), TXshChildLevel::setScene(), TColumnDataElement::storeColumn(), StageObjectsData::storeObjects(), and TTool::touchImage().
getColumnCount()
int TXsheet::getColumnCount () const
Returns xsheet column count, i.e the number of xsheet column used, it calls TColumnSetT::getColumnCount().
See also
getColumn() and getMaxFrame().
{
  return m_imp->m_columnSet.getColumnCount();
}
Referenced by StageBuilder::addCell(), StageBuilder::addFrame(), Skeleton::build(), SaveLevelAsPopup::execute(), getBBox(), getFirstFreeColumnIndex(), ToonzScene::getSoundColumns(), getUsedLevels(), and TXshChildLevel::setScene().
getColumnFan()
ColumnFan * TXsheet::getColumnFan (const Orientation * o) const
Returns a pointer to object ColumnFan contained in TXsheetImp, this object allows the user to manage columns visualization in xsheet. TXsheet maintains one column fan per each orientation.
{
  int index = o->dimension(PredefinedDimension::INDEX);
  return &m_imp->m_columnFans[index];
}
Referenced by TStageObjectTree::loadData(), saveData(), and TStageObjectTree::saveData().
getExpRefMonitor()
ExpressionReferenceMonitor * TXsheet::getExpRefMonitor () const
{
  return m_imp->m_expRefMonitor;
}
getFirstFreeColumnIndex()
int TXsheet::getFirstFreeColumnIndex () const
Returns first not empty column index in xsheet.
{
  int i = getColumnCount();
  while (i > 0 && isColumnEmpty(i - 1)) --i;
  return i;
}
References getColumnCount(), and isColumnEmpty().
Referenced by VectorizerPopup::apply(), SaveLevelAsPopup::execute(), and saveData().
getFrameCount()
int TXsheet::getFrameCount () const
Returns max frame number used in xsheet.
See also
getMaxFrame()
{ return m_imp->m_frameCount; }
Referenced by clearAll(), ChildStack::closeChild(), ReplaceLevelPopup::execute(), ReplaceParentDirectoryPopup::execute(), ToonzScene::getFrameCount(), TXshChildLevel::getFrameCount(), texture_utils::invalidateTextures(), ToonzScene::save(), and LevelSettingsPopup::updateLevelSettings().
getFxDag()
FxDag * TXsheet::getFxDag () const
Returns a pointer to object FxDag contained in TXsheetImp, this object allows the user to manage all fx dag, i.e. all element of fx schematic.
{ return m_imp->m_fxDag; }
Referenced by insertColumn(), FxSelection::isConnected(), TXshColumn::isControl(), TXshColumn::isRendered(), FxSchematicPort::linkTo(), removeColumn(), saveData(), MultimediaRenderer::Imp::scanSceneForColumns(), MultimediaRenderer::Imp::scanSceneForLayers(), setCells(), StageObjectsData::storeColumnFxs(), StageObjectsData::storeFxs(), and StageObjectsData::storeObjects().
getMaxFrame()
int TXsheet::getMaxFrame (int col) const
Returns the max frame number of xsheet column identified by col and calls TXshColumn::getMaxFrame().
See also
getFrameCount()
{
  TXshColumnP column = m_imp->m_columnSet.getColumn(col);
  if (!column) return 0;
  return column->getMaxFrame();
}
getNoScaleZ()
double TXsheet::getNoScaleZ (const TStageObjectId & id) const
{
  assert(id != TStageObjectId::NoneId);
  return m_imp->m_pegTree->getStageObject(id)->getNoScaleZ();
}
getNotes()
TXshNoteSet * TXsheet::getNotes () const inline
{ return m_notes; }
getParentPlacement()
TAffine TXsheet::getParentPlacement (const TStageObjectId & id, int frame) const
Returns transformation matrix TAffine related to parent of pegbar TStageObject with id TStageObjectId specialization in frame frame, it calls TStageObject::getParentPlacement().
See also
getPlacement()
{
  assert(id != TStageObjectId::NoneId);
  return m_imp->m_pegTree->getStageObject(id)->getParentPlacement(frame);
}
Referenced by EditTool::draw().
getPlacement()
TAffine TXsheet::getPlacement (const TStageObjectId & id, int frame) const
Returns transformation matrix TAffine related to pegbar TStageObject with id TStageObjectId specialization in frame frame, it calls TStageObject::getPlacement().
See also
getParentPlacement()
{
  assert(id != TStageObjectId::NoneId);
  return m_imp->m_pegTree->getStageObject(id)->getPlacement(frame);
}
Referenced by Skeleton::build(), EditTool::draw(), getCameraAff(), TTool::getColumnMatrix(), TTool::getCurrentColumnParentMatrix(), texture_utils::getTextureData(), and ToonzScene::renderFrame().
getScene()
ToonzScene * TXsheet::getScene () const
Returns a pointer to ToonzScene contained in TXsheetImp, that is the scene to which the xsheet refers.
See also
setScene()
{ return m_imp->m_scene; }
Referenced by texture_utils::getTextureData(), RasterSelection::pasteSelection(), and TXshSoundColumn::setXsheet().
getStageObject()
TStageObject * TXsheet::getStageObject (const TStageObjectId & id) const
The method retrieves a pegbar TStageObject with the passed id TStageObjectId specialization, calling TStageObjectTree::getStageObject().
See also
getStageObjectTree()
{
  assert(id != TStageObjectId::NoneId);
  return m_imp->m_pegTree->getStageObject(id);
}
Referenced by StageBuilder::addCell(), StageBuilder::addCellWithOnionSkin(), StageBuilder::addFrame(), Skeleton::build(), PlasticDeformerFx::doDryCompute(), EditTool::draw(), SkeletonTool::draw(), IoCmd::exposeComment(), getBBox(), TTool::getColumnMatrix(), loadData(), TTool::notifyImageChanged(), OutputSettingsPopup::onAddPresetButtonPressed(), TColumnDataElement::restoreColumn(), TCellKeyframeSelection::selectCellsKeyframes(), TColumnDataElement::storeColumn(), ArrowToolOptionsBox::syncCurrentStageObjectComboItem(), ArrowToolOptionsBox::updateStageObjectComboItems(), and Stage::visit().
getStageObjectParent()
TStageObjectId TXsheet::getStageObjectParent (const TStageObjectId & id)
Returns parent related to pegbar TStageObject with id TStageObjectId specialization; it calls TStageObject::getParent().
See also
setStageObjectParent()
{
  assert(id != TStageObjectId::NoneId);
  return m_imp->m_pegTree->getStageObject(id)->getParent();
}
Referenced by Skeleton::build(), SkeletonTool::draw(), and TTool::getCurrentColumnParentMatrix().
getStageObjectTree()
TStageObjectTree * TXsheet::getStageObjectTree () const
The method retrieves the pegbar tree TStageObjectTree contained in struct TXsheetImp.
See also
getStageObject()
{
  return m_imp->m_pegTree;
}
Referenced by StageBuilder::addCell(), ToonzScene::createNewLevel(), EditTool::draw(), getBBox(), getCameraAff(), TTool::getColumnMatrix(), ToonzScene::getCurrentCamera(), texture_utils::getTextureData(), TProjectManager::initializeScene(), loadData(), ToonzScene::loadLevel(), OutputSettingsPopup::onAddPresetButtonPressed(), OutputSettingsPopup::onCameraChanged(), ToonzScene::renderFrame(), TCameraDataElement::restoreCamera(), TColumnDataElement::restoreColumn(), TStageObjectDataElement::restoreObject(), TProjectManager::saveTemplate(), TCameraDataElement::storeCamera(), TStageObjectDataElement::storeObject(), StageObjectsData::storeSplines(), OutputSettingsPopup::updateField(), StageSchematicScene::updateScene(), ArrowToolOptionsBox::updateStageObjectComboItems(), and Stage::visit().
getUsedLevels()
void TXsheet::getUsedLevels (std::set< TXshLevel * > & levels) const
Sets the level set levels with all current xsheet levels used, it includes in levels sub-xsheet levels too.
See also
isLevelUsed()
{
  set<const TXsheet *> visitedXshs;
  vector<const TXsheet *> todoXshs;
  visitedXshs.insert(this);
  todoXshs.push_back(this);
  while (!todoXshs.empty()) {
    const TXsheet *xsh = todoXshs.back();
    todoXshs.pop_back();
    int c0 = 0, c1 = xsh->getColumnCount() - 1;
    for (int c = c0; c <= c1; ++c) {
      TXshColumnP column = const_cast<TXsheet *>(xsh)->getColumn(c);
      if (!column) continue;
      TXshCellColumn *cellColumn = column->getCellColumn();
      if (!cellColumn) continue;
      int r0, r1;
      if (!cellColumn->getRange(r0, r1)) continue;
      TXshLevel *level = 0;
      for (int r = r0; r <= r1; r++) {
        TXshCell cell = cellColumn->getCell(r);
        if (cell.isEmpty() || !cell.m_level) continue;
        if (level != cell.m_level.getPointer()) {
          level = cell.m_level.getPointer();
          levels.insert(level);
          if (level->getChildLevel()) {
            TXsheet *childXsh = level->getChildLevel()->getXsheet();
            if (visitedXshs.count(childXsh) == 0) {
              visitedXshs.insert(childXsh);
              todoXshs.push_back(childXsh);
            }
          }
        }
      }
    }
  }
}
References TXshCellColumn::getCell(), TXshLevel::getChildLevel(), getColumn(), getColumnCount(), TXshCellColumn::getRange(), TXshChildLevel::getXsheet(), and TXshCell::isEmpty().
Referenced by isLevelUsed(), and ToonzScene::save().
getZ()
double TXsheet::getZ (const TStageObjectId & id, int frame) const
Returns z value related to pegbar TStageObject with id specialization TStageObjectId in frame frame, it calls TStageObject::getZ().
{
  assert(id != TStageObjectId::NoneId);
  return m_imp->m_pegTree->getStageObject(id)->getZ(frame);
}
Referenced by EditTool::draw(), getCameraAff(), and TTool::getColumnMatrix().
hasChildren()
bool TXsheet::hasChildren (const TStageObjectId & id) const
Returns true if pegbar TStageObject with id TStageObjectId specialization has children, that is if pegbar is a parent of another pegbar; it calls TStageObject::hasChildren().
See also
getStageObjectParent() and setStageObjectParent()
{
  assert(id != TStageObjectId::NoneId);
  return m_imp->m_pegTree->getStageObject(id)->hasChildren();
}
id()
unsigned long TXsheet::id () const
Returns a unique identifier associated with the xsheet instance.
{ return m_imp->m_id; }
increaseStepCells()
void TXsheet::increaseStepCells (int r0, int c0, int & r1, int c1)
For each sequence of frame with same number, contained in rect delimited by first row r0, last row r1 and first column c0, a frame with same number is inserted.
{
  int c, size = r1 - r0 + 1;
  QList<int> ends;
  for (c = c0; c <= c1; c++) {
    int r = r0, i = 0, rEnd = r1;
    while (r <= rEnd) {
      TXshCell cell = getCell(CellPosition(r, c));
      if (!cell.isEmpty()) {
        insertCells(r, c);
        setCell(r, c, cell);
        rEnd++;
        r++;
        while (cell == getCell(CellPosition(r, c)) && r <= rEnd) r++;
      } else
        r++;
      i++;
    }
    ends.append(rEnd);
  }
  if (ends.isEmpty()) return;
  // controllo se devo cambiare la selezione
  bool allIncreaseIsEqual = true;
  for (c = 0; c < ends.size() - 1 && allIncreaseIsEqual; c++)
    allIncreaseIsEqual = allIncreaseIsEqual && ends[c] == ends[c + 1];
  if (allIncreaseIsEqual) r1 = ends[0];
}
References getCell(), insertCells(), and TXshCell::isEmpty().
incrementCells()
bool TXsheet::incrementCells (int r0, int c0, int r1, int c1, std::vector< std::pair< TRect, TXshCell > > & forUndo)
If cells is increasingly numbered and belong from same level return true; otherwise return false.
If returns true, the cells, contained in rect delimited by first row r0, last row r1 and first column c0, are repeated as if filling the numbering gap between two subsequence cell. For example if the command is applied to two cell with TFrameId number equal to 2 and 5, the result will be four cells: a cell with TFrameId number equal to 2 repeated three times and one cell with TFrameId number equal to 5.
This method inserts in forUndo vector all the inserted cells, it is useful for the undo process.
{
  for (int j = c0; j <= c1; j++) {
    int i = r0;
    while (getCell(CellPosition(i, j)).isEmpty() && i <= r1 - 1) i++;
    for (; i <= r1 - 1; i++) {
      if (getCell(CellPosition(i + 1, j)).isEmpty()) break;
      const TXshCell &ce1 = getCell(CellPosition(i, j)),
                     &ce2 = getCell(CellPosition(i + 1, j));
      if (ce2.getSimpleLevel() != ce1.getSimpleLevel() ||
          ce2.getFrameId().getNumber() < ce1.getFrameId().getNumber())
        return false;
    }
    i = r0;
    while (getCell(CellPosition(i, j)).isEmpty() && i <= r1 - 1) i++;
    int count;
    for (; i <= r1 - 1; i++) {
      count = 1;
      if (getCell(CellPosition(i + 1, j)).isEmpty()) continue;
      int frame1 = getCell(CellPosition(i, j)).getFrameId().getNumber();
      if (frame1 == -1) break;
      while (!getCell(CellPosition(i + 1, j)).isEmpty() &&
             getCell(CellPosition(i + 1, j)).getFrameId().getNumber() ==
                 getCell(CellPosition(i, j)).getFrameId().getNumber())
        i++, count++;
      int frame2 = getCell(CellPosition(i + 1, j)).getFrameId().getNumber();
      if (frame2 == -1) break;
      if (frame1 + count == frame2)
        continue;
      else if (frame1 + count < frame2)  // add
      {
        int numCells = frame2 - frame1 - count;
        insertCells(i + 1, j, numCells);
        forUndo.push_back(std::pair<TRect, TXshCell>(
            TRect(i + 1, j, i + 1 + numCells - 1, j), TXshCell()));
        for (int k = 1; k <= numCells; k++)
          setCell(i + k, j, getCell(CellPosition(i, j)));
        i += numCells;
        r1 += numCells;
      } else  // remove
      {
        int numCells = count - frame2 + frame1;
        i            = i - numCells;
        forUndo.push_back(
            std::pair<TRect, TXshCell>(TRect(i + 1, j, i + 1 + numCells - 1, j),
                                       getCell(CellPosition(i + 1, j))));
        removeCells(i + 1, j, numCells);
        r1 -= numCells;
      }
    }
  }
  return true;
}
References getCell(), TXshCell::getFrameId(), TXshSimpleLevel::getFrameId(), TXshCell::getSimpleLevel(), insertCells(), and removeCells().
insertCells()
void TXsheet::insertCells (int row, int col, int rowCount = 1)
If column identified by index col is not empty, is a TXshCellColumn and is not locked this method inserts in row identified by index row rowCount empty cells, it calls TXshCellColumn::insertEmptyCells(). An update of xsheet's frame count is performed.
See also
setCells(), removeCells()
{
  TXshColumnP column = m_imp->m_columnSet.getColumn(col);
  if (!column || column->isLocked()) return;
  TXshCellColumn *xshColumn = column->getCellColumn();
  if (!xshColumn) return;
  xshColumn->insertEmptyCells(row, rowCount);
  // aggiorno il frame count
  int fc = xshColumn->getMaxFrame() + 1;
  if (fc > m_imp->m_frameCount) m_imp->m_frameCount = fc;
}
Referenced by ChildStack::closeChild(), duplicateCells(), exposeLevel(), TCellData::getCells(), increaseStepCells(), incrementCells(), reframeCells(), resetStepCells(), rolldownCells(), rollupCells(), stepCells(), swingCells(), and timeStretch().
insertColumn() [1/2]
void TXsheet::insertColumn (int index, TXshColumn * column)
Insert column in column index. Insert column in the column set, in the pegbarTree TStageObjectTree contained in TXsheetImp and if column fx TFx is not empty in fx dag, calling FxDag::addToXsheet().
See also
removeColumn()
{
  if (col < 0) col = 0;
  column->setXsheet(this);
  m_imp->m_columnSet.insertColumn(col, column);
  m_imp->m_pegTree->insertColumn(col);
  if (column->getPaletteColumn() ==
      0)  // palette column are not connected to the xsheet fx node
  {
    TFx *fx = column->getFx();
    if (fx) getFxDag()->addToXsheet(fx);
  }
  for (ColumnFan &columnFan : m_imp->m_columnFans) {
    columnFan.rollRightFoldedState(col,
                                   m_imp->m_columnSet.getColumnCount() - col);
  }
  notify(TXsheetColumnChange(TXsheetColumnChange::Insert, col));
}
References getFxDag().
insertColumn() [2/2]
void TXsheet::insertColumn (int index, TXshColumn::ColumnType type = TXshColumn::eLevelType)
Inserts an empty column in index calling insertColumn().
{
  insertColumn(col, TXshColumn::createEmpty(type));
}
References TXshColumn::createEmpty(), and insertColumn().
Referenced by VectorizerPopup::apply(), IoCmd::exposeComment(), insertColumn(), TColumnDataElement::restoreColumn(), and setCells().
invalidateSound()
void TXsheet::invalidateSound ()
{ m_imp->m_mixedSound = TSoundTrackP(); }
isCameraColumnLocked()
bool TXsheet::isCameraColumnLocked () inline
{ return m_cameraColumn->isLocked(); }
isColumnEmpty()
bool TXsheet::isColumnEmpty (int col) const
Returns true if xsheet column identified by col is empty, it calls TXshColumn::isEmpty(), otherwise returns false.
{
  TXshColumnP column = m_imp->m_columnSet.getColumn(col);
  return column ? column->isEmpty() : true;
}
Referenced by SaveLevelAsPopup::execute(), getFirstFreeColumnIndex(), setCells(), ArrowToolOptionsBox::updateStageObjectComboItems(), and Toolbar::updateToolbar().
isLevelUsed()
bool TXsheet::isLevelUsed (TXshLevel * level) const
Returns true if level is used in current xsheet or in sub-xsheet, otherwise returns false. It verifies if level is contained in level set getUsedLevels().
{
  set<TXshLevel *> levels;
  getUsedLevels(levels);
  return levels.count(level) > 0;
}
References getUsedLevels().
Referenced by Filmstrip::updateChooseLevelComboItems().
isRectEmpty()
bool TXsheet::isRectEmpty (const CellPosition & pos0, const CellPosition & pos1) const
Returns true if all cells in rect delimited by first frame pos0.frame, last frame pos1.frame and first layer pos0.layer, last layer pos1.layer are empty; otherwise, false.
{
  for (int frame = pos0.frame(); frame <= pos1.frame(); frame++)
    for (int layer = pos0.layer(); layer <= pos1.layer(); layer++)
      if (!getCell(CellPosition(frame, layer)).isEmpty()) return false;
  return true;
}
References getCell().
isReferenceManagementIgnored()
bool TXsheet::isReferenceManagementIgnored (TDoubleParam * param)
{
  if (m_observer) return m_observer->isIgnored(param);
  return false;
}
loadData()
void TXsheet::loadData (TIStream & is) override virtual
Clears xsheet calling clearAll() and sets all xsheet elements, contained in TXsheetImp, to information contained in TIStream is.
See also
saveData()
Implements TPersist.
{
  clearAll();
  TStageObjectId cameraId   = TStageObjectId::CameraId(0);
  TStageObject *firstCamera = getStageObject(cameraId);
  m_imp->m_pegTree->removeStageObject(cameraId);
  int col = 0;
  string tagName;
  while (is.openChild(tagName)) {
    if (tagName == "columns") {
      while (!is.eos()) {
        TPersist *p = 0;
        is >> p;
        TXshColumn *column = dynamic_cast<TXshColumn *>(p);
        if (!column) throw TException("expected xsheet column");
        m_imp->m_columnSet.insertColumn(col++, column);
        column->setXsheet(this);
        if (TXshZeraryFxColumn *zc =
                dynamic_cast<TXshZeraryFxColumn *>(column)) {
          TFx *fx         = zc->getZeraryColumnFx()->getZeraryFx();
          int fxTypeCount = m_imp->m_fxDag->getFxTypeCount(fx);
          int maxFxTypeId = std::max(fxTypeCount, fx->getAttributes()->getId());
          m_imp->m_fxDag->updateFxTypeTable(fx, maxFxTypeId);
          m_imp->m_fxDag->updateFxIdTable(fx);
          for (int j = 0; j < fx->getParams()->getParamCount(); j++) {
            TParam *param = fx->getParams()->getParam(j);
            if (TDoubleParam *dp = dynamic_cast<TDoubleParam *>(param))
              getStageObjectTree()->setGrammar(dp);
            else if (dynamic_cast<TPointParam *>(param) ||
                     dynamic_cast<TRangeParam *>(param) ||
                     dynamic_cast<TPixelParam *>(param)) {
              TParamSet *paramSet = dynamic_cast<TParamSet *>(param);
              assert(paramSet);
              int f;
              for (f = 0; f < paramSet->getParamCount(); f++) {
                TDoubleParam *dp = dynamic_cast<TDoubleParam *>(
                    paramSet->getParam(f).getPointer());
                if (!dp) continue;
                getStageObjectTree()->setGrammar(dp);
              }
            }
          }
        }
      }
    } else if (tagName == "cameraColumn") {
      while (is.openChild(tagName)) {
        if (!m_cameraColumn->getCellColumn()->loadCellMarks(tagName, is))
          throw TException("Camera Column, unknown tag: " + tagName);
        is.closeChild();
      }
    } else if (tagName == "pegbars") {
      TPersist *p = m_imp->m_pegTree;
      m_imp->m_pegTree->loadData(is, this);
    } else if (tagName == "fxnodes") {
      m_imp->m_fxDag->loadData(is);
      std::vector<TFx *> fxs;
      m_imp->m_fxDag->getFxs(fxs);
      for (int i = 0; i < (int)fxs.size(); i++) {
        TFx *fx = fxs[i];
        for (int j = 0; j < fx->getParams()->getParamCount(); j++) {
          TParam *param = fx->getParams()->getParam(j);
          if (TDoubleParam *dp = dynamic_cast<TDoubleParam *>(param))
            getStageObjectTree()->setGrammar(dp);
          else if (dynamic_cast<TPointParam *>(param) ||
                   dynamic_cast<TRangeParam *>(param) ||
                   dynamic_cast<TPixelParam *>(param)) {
            TParamSet *paramSet = dynamic_cast<TParamSet *>(param);
            assert(paramSet);
            int f;
            for (f = 0; f < paramSet->getParamCount(); f++) {
              TDoubleParam *dp = dynamic_cast<TDoubleParam *>(
                  paramSet->getParam(f).getPointer());
              if (!dp) continue;
              getStageObjectTree()->setGrammar(dp);
            }
          }
        }
      }
      if (is.matchEndTag()) continue;
      // was ist dass?
      TFxSet fxSet;
      fxSet.loadData(is);
    } else if (tagName == "columnFan") {
      m_imp->m_columnFans[0].loadData(is);
      m_imp->copyFoldedState();
    } else if (tagName == "noteSet") {
      m_notes->loadData(is);
    } else {
      throw TException("xsheet, unknown tag: " + tagName);
    }
    is.closeChild();
  }
  updateFrameCount();
}
References clearAll(), TIStream::closeChild(), TIStream::eos(), getStageObject(), getStageObjectTree(), TIStream::matchEndTag(), TIStream::openChild(), and updateFrameCount().
makeSound()
TSoundTrack * TXsheet::makeSound (SoundProperties * properties)
{
  std::vector<TXshSoundColumn *> sounds;
  searchAudioColumn(this, sounds, properties->m_isPreview);
  if (!m_imp->m_mixedSound || *properties != *m_soundProperties) {
    if (!sounds.empty() && properties->m_fromFrame <= properties->m_toFrame)
      m_imp->m_mixedSound = sounds[0]->mixingTogether(
          sounds, properties->m_fromFrame, properties->m_toFrame,
          properties->m_frameRate);
    else
      m_imp->m_mixedSound = 0;
    delete m_soundProperties;
    m_soundProperties = properties;
  } else
    delete properties;
  return m_imp->m_mixedSound.getPointer();
}
moveColumn()
void TXsheet::moveColumn (int srcIndex, int dstIndex)
Moves column from xsheet column index srcIndex to dstIndex, columns between srcIndex+1 and dstIndex (included) are shifted of -1.
See also
insertColumn() and removeColumn()
{
  if (srcIndex == dstIndex) return;
  assert(srcIndex >= 0);
  assert(dstIndex >= 0);
  int col = std::max(srcIndex, dstIndex);
  if (col >= m_imp->m_columnSet.getColumnCount()) {
    int n = m_imp->m_columnSet.getColumnCount();
    touchColumn(col, TXshColumn::eLevelType);
    while (n <= col) {
      TXshColumn *column = getColumn(n);
      assert(column);
      column->setXsheet(this);
      n++;
    }
  }
  assert(m_imp->m_columnSet.getColumnCount() > srcIndex);
  assert(m_imp->m_columnSet.getColumnCount() > dstIndex);
  if (srcIndex < dstIndex) {
    int c0 = srcIndex;
    int c1 = dstIndex;
    assert(c0 < c1);
    m_imp->m_columnSet.rollLeft(c0, c1 - c0 + 1);
    for (ColumnFan &columnFan : m_imp->m_columnFans)
      columnFan.rollLeftFoldedState(c0, c1 - c0 + 1);
    for (int c = c0; c < c1; ++c) m_imp->m_pegTree->swapColumns(c, c + 1);
  } else {
    int c0 = dstIndex;
    int c1 = srcIndex;
    assert(c0 < c1);
    m_imp->m_columnSet.rollRight(c0, c1 - c0 + 1);
    for (ColumnFan &columnFan : m_imp->m_columnFans)
      columnFan.rollRightFoldedState(c0, c1 - c0 + 1);
    for (int c = c1 - 1; c >= c0; --c) m_imp->m_pegTree->swapColumns(c, c + 1);
  }
  notify(TXsheetColumnChange(TXsheetColumnChange::Move, srcIndex, dstIndex));
}
References getColumn().
notify()
void TXsheet::notify (const TXsheetColumnChange & change)
{
  if (m_observer) m_observer->onChange(change);
}
notifyFxAdded()
void TXsheet::notifyFxAdded (const std::vector< TFx * > & fxs)
{
  if (m_observer) m_observer->onFxAdded(fxs);
}
notifyStageObjectAdded()
void TXsheet::notifyStageObjectAdded (const TStageObjectId id)
{
  if (m_observer) m_observer->onStageObjectAdded(id);
}
play()
void TXsheet::play (TSoundTrackP soundtrack, int s0, int s1, bool loop)
{
  if (!TSoundOutputDevice::installed()) return;
  if (!m_player) m_player = new TSoundOutputDevice();
  if (m_player) {
    try {
      m_player->play(soundtrack, s0, s1, loop);
    } catch (TSoundDeviceException &) {
    }
  }
}
reframeCells()
int TXsheet::reframeCells (int r0, int r1, int col, int type, int withBlank = -1)
force cells order in n-steps. returns the row amount after process
{
  // Row amount in the selection
  int nr = r1 - r0 + 1;
  if (nr < 1) return 0;
  QVector<TXshCell> cells;
  cells.clear();
  for (int r = r0; r <= r1; r++) {
    if (cells.size() == 0 || cells.last() != getCell(CellPosition(r, col)))
      cells.push_back(getCell(CellPosition(r, col)));
  }
  // if withBlank is greater than -1, remove empty cells from cell order
  if (withBlank >= 0) {
    auto itr = cells.begin();
    while (itr != cells.end()) {
      if ((*itr).isEmpty())
        itr = cells.erase(itr);
      else
        itr++;
    }
  }
  if (cells.empty()) return 0;
  // row amount after n-step
  int nrows = cells.size() * type;
  if (withBlank > 0) {
    nrows += cells.size() * withBlank * type;
  }
  // if needed, insert cells
  if (nr < nrows) {
    insertCells(r1 + 1, col, nrows - nr);
  }
  // if needed, remove cells
  else if (nr > nrows) {
    removeCells(r0 + nrows, col, nr - nrows);
  }
  for (int i = r0, k = 0; i < r0 + nrows; k++) {
    for (int i1 = 0; i1 < type; i1++) {
      if (cells[k].isEmpty())
        clearCells(i + i1, col);
      else
        setCell(i + i1, col, cells[k]);
    }
    i += type;  // dipende dal tipo di step (2 o 3 per ora)
    if (withBlank > 0) {
      for (int i1 = 0; i1 < withBlank * type; i1++) {
        clearCells(i + i1, col);
      }
      i += withBlank * type;
    }
  }
  return nrows;  // return row amount after process
}
References clearCells(), getCell(), insertCells(), and removeCells().
removeCells()
void TXsheet::removeCells (int row, int col, int rowCount = 1)
If column identified by index col is not empty, is a TXshCellColumn and is not locked, this method removes rowCount cells starting from row, it calls TXshCellColumn::removeCells(). It removes cells without shift remaining cells. An update of xsheet's frame count is performed.
See also
clearCells(), insertCells()
{
  TXshColumnP column = m_imp->m_columnSet.getColumn(col);
  if (!column || column->isLocked()) return;
  TXshCellColumn *xshCellColumn = column->getCellColumn();
  if (!xshCellColumn) return;
  int oldColRowCount = xshCellColumn->getMaxFrame() + 1;
  xshCellColumn->removeCells(row, rowCount);
  // aggiornamento framecount
  if (oldColRowCount == m_imp->m_frameCount) updateFrameCount();
  TNotifier::instance()->notify(TXsheetChange());
}
References TXshCellColumn::getMaxFrame(), TXshCellColumn::removeCells(), and updateFrameCount().
Referenced by decreaseStepCells(), eachCells(), incrementCells(), reframeCells(), resetStepCells(), rolldownCells(), rollupCells(), and timeStretch().
removeColumn()
void TXsheet::removeColumn (int index)
Removes column identified by index from xsheet column. If column in index is not empty and it has a TFx fx, removes column from fx dag, calls FxDag::removeFromXsheet() and disconnects fx column from all output fx TFx, than removes column from column set and from pegbarTree TStageObjectTree contained in TXsheetImp.
See also
insertColumn()
{
  TXshColumn *column = getColumn(col);
  if (column) {
    TFx *fx = column->getFx();
    if (fx) {
      getFxDag()->removeFromXsheet(fx);
      // disconnetto dal columnFx tutti gli effetti connessi in uscita
      TFxPort *outPort = 0;
      while ((outPort = fx->getOutputConnection(0))) outPort->setFx(0);
    }
  }
  m_imp->m_columnSet.removeColumn(col);
  m_imp->m_pegTree->removeColumn(col);
  for (ColumnFan &columnFan : m_imp->m_columnFans) {
    columnFan.rollLeftFoldedState(col,
                                  m_imp->m_columnSet.getColumnCount() - col);
  }
  notify(TXsheetColumnChange(TXsheetColumnChange::Remove, col));
}
References getColumn(), and getFxDag().
Referenced by setCells().
resetStepCells()
void TXsheet::resetStepCells (int r0, int c0, int r1, int c1)
The cells, contained in rect delimited by first row r0, last row r1 and first column c0, are reset in order to have no sequential frame duplication.
{
  int c, size = r1 - r0 + 1;
  for (c = c0; c <= c1; c++) {
    int r = r0, i = 0;
    TXshCell *cells = new TXshCell[size];
    while (r <= r1) {
      // mi prendo le celle che mi servono
      cells[i] = getCell(CellPosition(r, c));
      r++;
      while (cells[i] == getCell(CellPosition(r, c)) && r <= r1) r++;
      i++;
    }
    size = i;
    removeCells(r0, c, r1 - r0 + 1);
    insertCells(r0, c, i);
    i = 0;
    r = r0;
    for (i = 0; i < size; i++, r++) setCell(r, c, cells[i]);
  }
}
References getCell(), insertCells(), and removeCells().
reverseCells()
void TXsheet::reverseCells (int r0, int c0, int r1, int c1)
{
  int rowCount = r1 - r0;
  if (rowCount < 0 || c1 - c0 < 0) return;
  for (int j = c0; j <= c1; j++) {
    int i1, i2;
    for (i1 = r0, i2 = r1; i1 < i2; i1++, i2--) {
      TXshCell app1 = getCell(CellPosition(i1, j));
      TXshCell app2 = getCell(CellPosition(i2, j));
      setCell(i1, j, app2);
      setCell(i2, j, app1);
    }
  }
}
rolldownCells()
void TXsheet::rolldownCells (int r0, int c0, int r1, int c1)
Roll last cells of rect r0,c0,r1,c1. Move cells contained in last row to first row.
{
  int nc   = c1 - c0 + 1;
  int size = 1 * nc;
  assert(size > 0);
  std::unique_ptr<TXshCell[]> cells(new TXshCell[size]);
  assert(cells);
  // in cells copio il contenuto delle celle che mi interessano
  int k;
  for (k = c0; k <= c1; k++) cells[k - c0] = getCell(CellPosition(r1, k));
  for (k = c0; k <= c1; k++) removeCells(r1, k, 1);
  for (k = c0; k <= c1; k++) {
    insertCells(r0, k, 1);
    setCell(r0, k, cells[k - c0]);  // setto le celle
  }
}
References getCell(), insertCells(), and removeCells().
rollupCells()
void TXsheet::rollupCells (int r0, int c0, int r1, int c1)
Roll first cells of rect r0,c0,r1,c1. Move cells contained in first row to last row.
{
  int nc   = c1 - c0 + 1;
  int size = 1 * nc;
  assert(size > 0);
  std::unique_ptr<TXshCell[]> cells(new TXshCell[size]);
  assert(cells);
  // in cells copio il contenuto delle celle che mi interessano
  int k;
  for (k = c0; k <= c1; k++) cells[k - c0] = getCell(CellPosition(r0, k));
  for (k = c0; k <= c1; k++) removeCells(r0, k, 1);
  for (k = c0; k <= c1; k++) {
    insertCells(r1, k, 1);
    setCell(r1, k, cells[k - c0]);  // setto le celle
  }
}
References getCell(), insertCells(), and removeCells().
saveData()
void TXsheet::saveData (TOStream & os) override virtual
Save all xsheet elements information, contained in TXsheetImp, in TOStream os.
See also
loadData()
Implements TPersist.
{
  os.openChild("columns");
  for (int c = 0; c < m_imp->m_columnSet.getColumnCount(); ++c) {
    TXshColumnP column = m_imp->m_columnSet.getColumn(c);
    if (column && c < getFirstFreeColumnIndex()) os << column.getPointer();
  }
  os.closeChild();
  // save cell marks in the camera column
  if (!m_cameraColumn->getCellColumn()->getCellMarks().isEmpty()) {
    os.openChild("cameraColumn");
    m_cameraColumn->getCellColumn()->saveCellMarks(os);
    os.closeChild();
  }
  os.openChild("pegbars");
  m_imp->m_pegTree->saveData(os, getFirstFreeColumnIndex(), this);
  // os << *(m_imp->m_pegTree);
  os.closeChild();
  FxDag *fxDag = getFxDag();
  os.openChild("fxnodes");
  fxDag->saveData(os, getFirstFreeColumnIndex());
  os.closeChild();
  // does not matter which Orientation to take, as all fans share folded data
  ColumnFan *columnFan = getColumnFan(Orientations::topToBottom());
  if (!columnFan->isEmpty()) {
    os.openChild("columnFan");
    columnFan->saveData(os);
    os.closeChild();
  }
  TXshNoteSet *notes = getNotes();
  if (notes->getCount() > 0) {
    os.openChild("noteSet");
    notes->saveData(os);
    os.closeChild();
  }
}
References TOStream::closeChild(), getColumnFan(), getFirstFreeColumnIndex(), getFxDag(), and TOStream::openChild().
scrub()
void TXsheet::scrub (int frame, bool isPreview = false)
{
  try {
    double fps =
        getScene()->getProperties()->getOutputProperties()->getFrameRate();
    TXsheet::SoundProperties *prop = new TXsheet::SoundProperties();
    prop->m_isPreview              = isPreview;
    TSoundTrack *st = makeSound(prop);  // Absorbs prop's ownership
    if (!st) return;
    double samplePerFrame = st->getSampleRate() / fps;
    double s0 = frame * samplePerFrame, s1 = s0 + samplePerFrame;
    // if (m_player && m_player->isPlaying()) {
    //    try {
    //        m_player->stop();
    //    }
    //    catch (const std::runtime_error& e) {
    //        int i = 0;
    //    }
    //    catch (const std::exception& e) {
    //        int i = 0;
    //    }
    //    catch (...) {
    //        int i = 0;
    //    }
    //}
    play(st, s0, s1, false);
  } catch (TSoundDeviceException &e) {
    if (e.getType() == TSoundDeviceException::NoDevice) {
      std::cout << ::to_string(e.getMessage()) << std::endl;
    } else {
      throw TSoundDeviceException(e.getType(), e.getMessage());
    }
  }
}
setCameraColumnIndex()
void TXsheet::setCameraColumnIndex (int index) inline
{ m_cameraColumnIndex = index; }
setCameraColumnLocked()
void TXsheet::setCameraColumnLocked (bool locked) inline
{ m_cameraColumn->lock(locked); }
setCell()
bool TXsheet::setCell (int row, int col, const TXshCell & cell)
{
  if (row < 0 || col < 0) return false;
  bool wasColumnEmpty = isColumnEmpty(col);
  TXshCellColumn *cellColumn;
  if (!cell.isEmpty()) {
    TXshLevel *level = cell.m_level.getPointer();
    assert(level);
    int levelType               = level->getType();
    TXshColumn::ColumnType type = TXshColumn::eLevelType;
    if (levelType == SND_XSHLEVEL)
      type = TXshColumn::eSoundType;
    else if (levelType == SND_TXT_XSHLEVEL)
      type = TXshColumn::eSoundTextType;
    else if (levelType == PLT_XSHLEVEL)
      type = TXshColumn::ePaletteType;
    else if (levelType == ZERARYFX_XSHLEVEL)
      type = TXshColumn::eZeraryFxType;
    else if (levelType == MESH_XSHLEVEL)
      type = TXshColumn::eMeshType;
    cellColumn = touchColumn(col, type)->getCellColumn();
  } else {
    TXshColumn *column = getColumn(col);
    cellColumn         = column ? column->getCellColumn() : 0;
  }
  if (!cellColumn || cellColumn->isLocked()) return false;
  cellColumn->setXsheet(this);
  if (!cellColumn->setCell(row, cell)) {
    if (wasColumnEmpty) {
      removeColumn(col);
      insertColumn(col);
    }
    return false;
  }
  TFx *fx = cellColumn->getFx();
  if (wasColumnEmpty && fx && fx->getOutputConnectionCount() == 0 &&
      cellColumn->getPaletteColumn() == 0)
    getFxDag()->addToXsheet(fx);
  if (cell.isEmpty())
    updateFrameCount();
  else if (row >= m_imp->m_frameCount)
    m_imp->m_frameCount = row + 1;
  TNotifier::instance()->notify(TXsheetChange());
  return true;
}
setCells()
bool TXsheet::setCells (int row, int col, int rowCount, const TXshCell cells[])
If column identified by index col is a TXshCellColumn or is empty and is not locked, this method sets to cells[] the given rowCount cells of column col starting from row row. If column in col is empty it creates a new column recalling TColumnSetT::touchColumn() and sets the new cells to cells[], and on creating a new column it adds it to fx dag FxDag. If cells in row and col are not empty recalls TXshCellColumn::setCells(), insert the new cells cells[] in row col and shift old cells. If xsheet change it updates xsheet's frame count. Return false if cannot set cells.
See also
getCells(), setCell(), getCell()
{
  static const TXshCell emptyCell;
  int i = 0;
  while (i < rowCount && cells[i].isEmpty()) i++;
  // inserito da Elisa verso novembre 2009.
  // cosi' ha il difetto che se assegno celle vuote non fa nulla
  // per ora lo commento. bisogna indagare se questo rompe qualcosa
  // ho modificato il seguito per gestire il caso in cui i>=rowCount
  // => niente livelli dentro cells
  // if(i>=rowCount)
  //  return false;
  TXshColumn::ColumnType type = TXshColumn::eLevelType;
  if (i < rowCount) {
    TXshLevel *level = cells[i].m_level.getPointer();
    int levelType    = level->getType();
    if (levelType == SND_XSHLEVEL)
      type = TXshColumn::eSoundType;
    else if (levelType == SND_TXT_XSHLEVEL)
      type = TXshColumn::eSoundTextType;
    else if (levelType == PLT_XSHLEVEL)
      type = TXshColumn::ePaletteType;
    else if (levelType == ZERARYFX_XSHLEVEL)
      type = TXshColumn::eZeraryFxType;
    else if (levelType == MESH_XSHLEVEL)
      type = TXshColumn::eMeshType;
  }
  bool wasColumnEmpty = isColumnEmpty(col);
  if (col < 0) return false;
  TXshCellColumn *column = touchColumn(col, type)->getCellColumn();
  if (!column) return false;
  int oldColRowCount = column->getMaxFrame() + 1;
  bool ret           = column->setCells(row, rowCount, cells);
  if (!ret || column->isLocked()) {
    if (wasColumnEmpty) {
      removeColumn(col);
      insertColumn(col);
    }
    return false;
  }
  int newColRowCount = column->getMaxFrame() + 1;
  TFx *fx = column->getFx();
  if (wasColumnEmpty && fx && fx->getOutputConnectionCount() == 0)
    getFxDag()->addToXsheet(fx);
  column->setXsheet(this);
  if (newColRowCount > m_imp->m_frameCount)
    m_imp->m_frameCount = newColRowCount;
  else {
    if (oldColRowCount == m_imp->m_frameCount &&
        newColRowCount < m_imp->m_frameCount)
      updateFrameCount();
  }
  return true;
}
References getFxDag(), TXshLevel::getType(), insertColumn(), isColumnEmpty(), removeColumn(), and updateFrameCount().
Referenced by TCellData::getCells().
setCenter()
void TXsheet::setCenter (const TStageObjectId & id, int frame, const TPointD & center)
Sets the center of pegbar TStageObject with id TStageObjectId specialization in frame frame, to center; it calls TStageObject::setCenter().
See also
getCenter()
{
  assert(id != TStageObjectId::NoneId);
  m_imp->m_pegTree->getStageObject(id)->setCenter(frame, center);
}
setObserver()
void TXsheet::setObserver (TXsheetColumnChangeObserver * observer)
{
  m_observer = observer;
}
setScene()
void TXsheet::setScene (ToonzScene * scene)
Set scene ToonzScene contained in TXsheetImp to scene, change the scene to which the xsheet refers.
See also
setScene()
{ m_imp->m_scene = scene; }
Referenced by ChildStack::ChildStack(), ChildStack::clear(), ToonzScene::createNewLevel(), and TXshChildLevel::setScene().
setStageObjectParent()
void TXsheet::setStageObjectParent (const TStageObjectId & id, const TStageObjectId & parentId)
Sets parent of pegbar TStageObject with id TStageObjectId specialization to parentId; it calls TStageObject::setParent().
See also
getStageObjectParent()
{
  assert(id != TStageObjectId::NoneId);
  m_imp->m_pegTree->getStageObject(id)->setParent(parentId);
}
stepCells()
void TXsheet::stepCells (int r0, int c0, int r1, int c1, int type)
The cells, contained in rect delimited by first row r0, last row r1 and first column c0, are repeated in order to have a step type. The duplicated cells will be inserted by shifting the other down.
{
  int nr = r1 - r0 + 1;
  int nc = c1 - c0 + 1;
  if (nr < 1 || nc <= 0) return;
  int size = nr * nc;
  std::unique_ptr<TXshCell[]> cells(new TXshCell[size]);
  if (!cells) return;
  // salvo il contenuto delle celle in cells
  int k = 0;
  for (int r = r0; r <= r1; r++)
    for (int c = c0; c <= c1; c++) {
      cells[k++] = getCell(CellPosition(r, c));
    }
  int nrows = nr * (type - 1);
  for (int c = c0; c <= c1; ++c) insertCells(r1 + 1, c, nrows);
  for (int j = c0; j <= c1; j++) {
    int i, k;
    for (i = r0, k = j - c0; k < size; k += nc) {
      for (int i1 = 0; i1 < type; i1++) {
        if (cells[k].isEmpty())
          clearCells(i + i1, j);
        else
          setCell(i + i1, j, cells[k]);
      }
      i += type;  // dipende dal tipo di step (2 o 3 per ora)
    }
  }
}
References clearCells(), getCell(), and insertCells().
stopScrub()
void TXsheet::stopScrub ()
{
  if (m_player) m_player->stop();
}
swingCells()
void TXsheet::swingCells (int r0, int c0, int r1, int c1)
The cells, contained in rect delimited by first row r0, last row r1 and first column c0, are appended at the end of the rect in a reversed order. The last cell of rect will not be repeated.
{
  int rowCount = r1 - r0;
  if (rowCount < 0 || c1 - c0 < 0) return;
  int r0Mod = r1 + 1;
  for (int c = c0; c <= c1; ++c) insertCells(r0Mod, c, rowCount);
  for (int j = c0; j <= c1; j++) {
    for (int i1 = r0Mod, i2 = r1 - 1; i2 >= r0; i1++, i2--) {
      TXshCell cell = getCell(CellPosition(i2, j));
      setCell(i1, j, cell);
    }
  }
}
References getCell(), and insertCells().
timeStretch()
void TXsheet::timeStretch (int r0, int c0, int r1, int c1, int nr)
Stretch cells contained in rect r0,c0,r1,c1, from r1-r0+1 to nr. If nr>r1-r0+1 add cells, otherwise remove cells.
{
  int oldNr = r1 - r0 + 1;
  if (nr > oldNr) /* ingrandisce */
  {
    int c;
    for (c = c0; c <= c1; c++) {
      int dn = nr - oldNr;
      assert(oldNr > 0);
      std::unique_ptr<TXshCell[]> cells(new TXshCell[oldNr]);
      assert(cells);
      getCells(r0, c, oldNr, cells.get());
      insertCells(r0 + 1, c, dn);
      int i;
      for (i = nr - 1; i >= 0; i--) {
        int j = i * double(oldNr) / double(nr);
        if (j < i) setCell(i + r0, c, cells[j]);
      }
    }
  } else /* rimpicciolisce */
  {
    int c;
    for (c = c0; c <= c1; c++) {
      int dn = oldNr - nr;
      std::unique_ptr<TXshCell[]> cells(new TXshCell[oldNr]);
      assert(cells);
      getCells(r0, c, oldNr, cells.get());
      int i;
      for (i = 0; i < nr; i++) {
        int j = i * double(oldNr) / double(nr);
        if (j > i) setCell(i + r0, c, cells[j]);
      }
      removeCells(r1 - dn + 1, c, dn);
    }
  }
}
References getCells(), insertCells(), and removeCells().
updateFrameCount()
void TXsheet::updateFrameCount ()
Updates xsheet frame count, find max frame count between all xsheet column, using getMaxFrame().
{
  m_imp->m_frameCount = 0;
  for (int i = 0; i < m_imp->m_columnSet.getColumnCount(); ++i) {
    TXshColumnP cc = m_imp->m_columnSet.getColumn(i);
    if (cc && !cc->isEmpty())
      m_imp->m_frameCount =
          std::max(m_imp->m_frameCount, cc->getMaxFrame() + 1);
  }
}
Referenced by clearCells(), ChildStack::closeChild(), exposeLevel(), loadData(), ToonzScene::loadNoResources(), ToonzScene::loadResources(), TXshSoundColumn::modifyCellRange(), removeCells(), TColumnDataElement::restoreColumn(), and setCells().
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/toonz/txsheet.h
E:/opentoonz/toonz/sources/toonzlib/txsheet.cpp