opentoonz: TStripeFillStyle Class Reference
TStripeFillStyle Class Reference final
Public Member Functions
TStripeFillStyle (const TPixel32 &bgColor, const TPixel32 &pointColor, const double Dist, const double Angle, const double Thickness)
TStripeFillStyle (const TPixel32 &color)
TColorStyle * clone () const override
Polymorphic clone of the style.
int getColorParamCount () const override
Returns the number of colors (if any) of the style.
TPixel32 getColorParamValue (int index) const override
Returns the value of the color of index index.
void setColorParamValue (int index, const TPixel32 &color) override
Sets the index-th color value.
bool isRegionStyle () const override
Returns whether the style applies on regions.
bool isStrokeStyle () const override
Returns whether the style applies on strokes.
int getParamCount () const override
TColorStyle::ParamType getParamType (int index) const override
Returns the type of the specified parameter.
QString getParamNames (int index) const override
Return the string that identifies the index-th parameter.
void getParamRange (int index, double &min, double &max) const override
Retrieves the specified double parameter range.
double getParamValue (TColorStyle::double_tag, int index) const override
Retrieves the specified double parameter value.
void setParamValue (int index, double value) override
extension value in text form.
void drawRegion (const TColorFunction *cf, const bool antiAliasing, TRegionOutline &boundary) const override
int getTagId () const override
Returns an unique number representing the style.
QString getDescription () const override
Return a brief description of the style.
Public Member Functions inherited from TSolidColorStyle
TSolidColorStyle (const TPixel32 &color=TPixel32::Black)
TSolidColorStyle (const TSolidColorStyle &)
TColorStyle * clone () const override
Polymorphic clone of the style.
QString getDescription () const override
Return a brief description of the style.
bool hasMainColor () const override
Returns whether the style has a reference main color.
TPixel32 getMainColor () const override
Returns the style's main color, or black if none.
void setMainColor (const TPixel32 &color) override
Sets the main color, if it has one.
void drawRegion (const TColorFunction *cf, const bool antiAliasing, TRegionOutline &outline) const override
void drawStroke (const TColorFunction *cf, TStrokeOutline *outline, const TStroke *s) const override
int getTagId () const override
Returns an unique number representing the style.
Public Member Functions inherited from TOutlineStyle
TOutlineStyle (const TOutlineStyle &)
RegionOutlineModifier * getRegionOutlineModifier () const
void setRegionOutlineModifier (RegionOutlineModifier *modifier)
bool isRegionStyle () const override
Returns whether the style applies on regions.
bool isStrokeStyle () const override
Returns whether the style applies on strokes.
virtual void computeOutline (const TStroke *stroke, TStrokeOutline &outline, TOutlineUtil::OutlineParameter param) const
TStrokeProp * makeStrokeProp (const TStroke *stroke) override
TRegionProp * makeRegionProp (const TRegion *region) override
used to draw the style on the specified stroke object.
virtual void drawRegion (const TColorFunction *cf, const bool antiAliasing, TRegionOutline &outline) const =0
virtual void drawStroke (const TColorFunction *cf, TStrokeOutline *outline, const TStroke *stroke) const =0
Public Member Functions inherited from TColorStyle
TColorStyle (const TColorStyle &other)
Copies another style except its icon.
virtual TColorStyle * clone () const =0
Polymorphic clone of the style.
virtual TColorStyle & copy (const TColorStyle &other)
bool operator== (const TColorStyle &cs) const
bool operator!= (const TColorStyle &cs)
virtual TStrokeProp * makeStrokeProp (const TStroke *stroke)=0
virtual TRegionProp * makeRegionProp (const TRegion *region)=0
used to draw the style on the specified stroke object.
virtual bool isRasterStyle () const
used to draw the style on the specified region object.
virtual TRasterStyleFx * getRasterStyleFx ()
virtual bool isRegionStyle () const =0
Returns whether the style applies on regions.
virtual bool isStrokeStyle () const =0
Returns whether the style applies on strokes.
void setName (std::wstring name)
Sets the style's user-defined name.
std::wstring getName () const
Returns the style's user-defined name.
void setGlobalName (std::wstring name)
Sets the global name of the style.
std::wstring getGlobalName () const
Returns the global name of the style.
void setOriginalName (std::wstring name)
If the style is originally copied from studio palette, set this.
std::wstring getOriginalName () const
Returns the original name of the style.
void setIsEditedFlag (bool edited)
bool getIsEditedFlag () const
style is edited from the original one.
void assignNames (const TColorStyle *src)
Copies the style names from src.
unsigned int getFlags () const
Sets color attributes.
void setFlags (unsigned int flags)
Returns color attributes.
void setPickedPosition (const TPoint &pos, const int index=0)
void setPickedPosition (const PickedPosition &pos)
PickedPosition getPickedPosition () const
virtual bool hasMainColor () const
Returns whether the style has a reference main color.
virtual TPixel32 getMainColor () const
Returns the style's main color, or black if none.
virtual void setMainColor (const TPixel32 &color)
Sets the main color, if it has one.
virtual int getColorParamCount () const
Returns the number of colors (if any) of the style.
virtual TPixel32 getColorParamValue (int index) const
Returns the value of the color of index index.
virtual void setColorParamValue (int index, const TPixel32 &color)
Sets the index-th color value.
virtual TPixel32 getAverageColor () const
Returns a color representing the average of all the style's colors.
virtual int getParamCount () const
virtual ParamType getParamType (int paramIdx) const
Returns the type of the specified parameter.
virtual bool hasParamDefault (int index) const
Value of parameter can be reset to default.
virtual void setParamDefault (int index)
Reset value of parameter to default.
virtual bool isParamDefault (int index) const
Check if current value of parameter equals to default.
virtual void setParamValue (int index, bool value)
Assigns a value to the specified bool parameter.
virtual bool getParamValue (bool_tag, int index) const
Retrieves the specified bool parameter value.
virtual void setParamValue (int index, int value)
Assigns a value to the specified int parameter.
virtual int getParamValue (int_tag, int index) const
Retrieves the specified int parameter value.
virtual void getParamRange (int index, int &min, int &max) const
Retrieves the specified int parameter range.
virtual void getParamRange (int pIndex, QStringList &stringItems) const
virtual void setParamValue (int index, double value)
extension value in text form.
virtual double getParamValue (double_tag, int index) const
Retrieves the specified double parameter value.
virtual void getParamRange (int index, double &min, double &max) const
Retrieves the specified double parameter range.
virtual void setParamValue (int index, const TFilePath &fp)
Assigns a value to the specified TFilePath parameter.
virtual TFilePath getParamValue (TFilePath_tag, int index) const
Retrieves the specified TFilePath parameter value.
void assignBlend (const TColorStyle &a, const TColorStyle &b, double t)
virtual QString getDescription () const =0
Return a brief description of the style.
virtual QString getParamNames (int index) const
Return the string that identifies the index-th parameter.
virtual int getTagId () const =0
Returns an unique number representing the style.
virtual void getObsoleteTagIds (std::vector< int > &) const
void save (TOutputStreamInterface &) const
void invalidateIcon ()
Sets a flag that defines the style's icon validity.
virtual const TRaster32P & getIcon (const TDimension &d)
Returns an image representing the style.
bool isEnabled () const
Returns whether the style can be used.
void enable (bool on)
Sets the style's enabled status.
int getVersionNumber () const
Returns the version number of the style.
Public Member Functions inherited from TSmartObject
TSmartObject (ClassCode classCode)
void addRef ()
void release ()
TINT32 getRefCount () const
Protected Member Functions
void loadData (TInputStreamInterface &is) override
void saveData (TOutputStreamInterface &os) const override
void makeIcon (const TDimension &d) override
Protected Member Functions inherited from TSolidColorStyle
void makeIcon (const TDimension &d) override
void loadData (TInputStreamInterface &) override
void saveData (TOutputStreamInterface &) const override
Protected Member Functions inherited from TOutlineStyle
TOutlineStyle & operator= (const TOutlineStyle &)
Protected Member Functions inherited from TColorStyle
virtual void makeIcon (const TDimension &d)
virtual void loadData (TInputStreamInterface &)=0
virtual void saveData (TOutputStreamInterface &) const =0
virtual void loadData (int, TInputStreamInterface &)
void updateVersionNumber ()
TColorStyle & operator= (const TColorStyle &other)
Copies another style except its icon.
Additional Inherited Members
Public Types inherited from TColorStyle
enum ParamType {
BOOL , INT , ENUM , DOUBLE ,
FILEPATH
}
Public Types inherited from TSmartObject
typedef short ClassCode
Static Public Member Functions inherited from TColorStyle
static TColorStyle * load (TInputStreamInterface &)
static TColorStyle * create (int tagId)
Creates a new style with identifier equal to tagId.
static void declare (TColorStyle *style)
Puts the style in the table of actual styles.
static void getAllTags (std::vector< int > &tags)
Static Public Member Functions inherited from TSmartObject
static TINT32 getInstanceCount (ClassCode code)
Static Public Attributes inherited from TColorStyle
static int m_currentFrame = 0
Protected Attributes inherited from TOutlineStyle
RegionOutlineModifier * m_regionOutlineModifier
Protected Attributes inherited from TColorStyle
TRaster32P m_icon
Icon shown on TPalette viewers.
bool m_validIcon
Icon's validity status.
Detailed Description
Constructor & Destructor Documentation
TStripeFillStyle() [1/2]
TStripeFillStyle::TStripeFillStyle (const TPixel32 & bgColor, const TPixel32 & pointColor, const double Dist, const double Angle, const double Thickness)
    : TSolidColorStyle(bgColor)
    , m_pointColor(pointColor)
    , m_Dist(Dist)
    , m_Angle(Angle)
    , m_Thickness(Thickness) {}
TStripeFillStyle() [2/2]
TStripeFillStyle::TStripeFillStyle (const TPixel32 & color)
    : TSolidColorStyle(TPixel32::Transparent)
    , m_pointColor(color)
    , m_Dist(15.0)
    , m_Angle(0.0)
    , m_Thickness(6.0) {}
Member Function Documentation
clone()
TColorStyle * TStripeFillStyle::clone () const override virtual
Polymorphic clone of the style.
Implements TColorStyle.
{
  return new TStripeFillStyle(*this);
}
drawRegion()
void TStripeFillStyle::drawRegion (const TColorFunction * cf, const bool antiAliasing, TRegionOutline & boundary) const override virtual
Implements TOutlineStyle.
{
  const bool isTransparent = m_pointColor.m < 255;
  TStencilControl *stenc = TStencilControl::instance();
  TPixel32 backgroundColor = TSolidColorStyle::getMainColor();
  if (cf) backgroundColor  = (*(cf))(backgroundColor);
  if (backgroundColor.m == 0) {  // only to create stencil mask
    TSolidColorStyle appStyle(TPixel32::White);
    stenc->beginMask();
    appStyle.drawRegion(0, false, boundary);
  } else {
    stenc->beginMask(TStencilControl::DRAW_ALSO_ON_SCREEN);
    TSolidColorStyle::drawRegion(cf, antiAliasing, boundary);
  }
  stenc->endMask();
  stenc->enableMask(TStencilControl::SHOW_INSIDE);
  if (isTransparent) {
    // glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
    // glEnable(GL_BLEND);
  }
  TPixel32 color;
  if (cf)
    color = (*(cf))(m_pointColor);
  else
    color = m_pointColor;
  tglColor(color);
  // Horizontal Lines
  if (fabs(m_Angle) != 90) {
    double lx = boundary.m_bbox.x1 - boundary.m_bbox.x0;
    // double ly=boundary.m_bbox.y1-boundary.m_bbox.y0;
    double beg  = boundary.m_bbox.y0;
    double end  = boundary.m_bbox.y1;
    beg         = m_Angle <= 0 ? beg : beg - lx * tan(degree2rad(m_Angle));
    end         = m_Angle >= 0 ? end : end - lx * tan(degree2rad(m_Angle));
    double dist = m_Dist / cos(degree2rad(m_Angle));
    double y;
    TStencilControl *stenc2 = TStencilControl::instance();
    stenc2->beginMask(TStencilControl::DRAW_ALSO_ON_SCREEN);
    glBegin(GL_QUADS);
    for (y = beg; y <= end; y += dist) {
      TPointD p0, p1, p2, p3;
      getThickline(TPointD(boundary.m_bbox.x0, y), lx, p0, p1, p2, p3);
      tglVertex(p0);
      tglVertex(p1);
      tglVertex(p2);
      tglVertex(p3);
    }
    glEnd();
    stenc2->endMask();
    stenc2->enableMask(TStencilControl::SHOW_OUTSIDE);
    if (m_Angle != 0)  // ANTIALIASING
    {
      // glHint(GL_LINE_SMOOTH_HINT, GL_NICEST);
      // glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
      // glEnable(GL_BLEND);
      // glEnable(GL_LINE_SMOOTH);
      tglEnableLineSmooth();
      // NOTE: Trimming the fat lines is necessary outside the (-60, 60) angles
      // interval
      // seemingly due to a bug in MAC-Leopard's openGL implementation...
      glBegin(GL_LINES);
      for (y = beg; y <= end; y += dist) {
        TPointD p0, p1, p2, p3;
        getThickline(TPointD(boundary.m_bbox.x0, y), lx, p0, p1, p2, p3);
        trim(p1, p2, boundary.m_bbox.y0, boundary.m_bbox.y1);
        tglVertex(p1);
        tglVertex(p2);
        trim(p0, p3, boundary.m_bbox.y0, boundary.m_bbox.y1);
        tglVertex(p0);
        tglVertex(p3);
      }
      glEnd();
    }
    stenc2->disableMask();
  } else {
    double beg = boundary.m_bbox.x0;
    double end = boundary.m_bbox.x1;
    double y0  = boundary.m_bbox.y0;
    double y1  = boundary.m_bbox.y1;
    glBegin(GL_QUADS);
    for (double x = beg; x <= end; x += m_Dist) {
      TPointD p0(x, y0);
      TPointD p1(x + m_Thickness, y0);
      TPointD p2(x, y1);
      TPointD p3(x + m_Thickness, y1);
      tglVertex(p0);
      tglVertex(p1);
      tglVertex(p3);
      tglVertex(p2);
    }
    glEnd();
  }
  // tglColor(TPixel32::White);
  stenc->disableMask();
}
getColorParamCount()
int TStripeFillStyle::getColorParamCount () const inline override virtual
Returns the number of colors (if any) of the style.
\detail For example a bubble styles has two colors. By default it returns 1 if the style has only a main color else returns 0 if the style has no color.
Reimplemented from TColorStyle.
{ return 2; }
getColorParamValue()
TPixel32 TStripeFillStyle::getColorParamValue (int index) const override virtual
Returns the value of the color of index index.
\detail Returns the main color by default.
Reimplemented from TColorStyle.
{
  return index == 0 ? m_pointColor : TSolidColorStyle::getMainColor();
}
References TSolidColorStyle::getMainColor().
getDescription()
QString TStripeFillStyle::getDescription () const inline override virtual
Return a brief description of the style.
\detail For example for a stroke style we have "Constant", "Chain", "Rope", "Tulle", etc...
Implements TColorStyle.
{
    return QCoreApplication::translate("TStripeFillStyle", "Banded");
  }
getParamCount()
int TStripeFillStyle::getParamCount () const override virtual
\detail For example: a the general cleanup style has two parameters, brightness and contrast and a black cleanup style has in addition a black and white threshold, therefore 4 parameters. Returns the number of parameters necessary to describe the style.
Reimplemented from TColorStyle.
{ return 3; }
Referenced by getParamType().
getParamNames()
QString TStripeFillStyle::getParamNames (int index) const override virtual
Return the string that identifies the index-th parameter.
Reimplemented from TColorStyle.
{
  assert(0 <= index && index < 3);
  QString value;
  switch (index) {
  case 0:
    value = QCoreApplication::translate("TStripeFillStyle", "Distance");
    break;
  case 1:
    value = QCoreApplication::translate("TStripeFillStyle", "Angle");
    break;
  case 2:
    value = QCoreApplication::translate("TStripeFillStyle", "Thickness");
    break;
  }
  return value;
}
getParamRange()
void TStripeFillStyle::getParamRange (int index, double & min, double & max) const override virtual
Retrieves the specified double parameter range.
Reimplemented from TColorStyle.
{
  assert(0 <= index && index < 3);
  switch (index) {
  case 0:
    min = 1.0;
    max = 100.0;
    break;
  case 1:
    min = -90.0;
    max = 90.0;
    break;
  case 2:
    min = 0.5;
    max = 100.0;
    break;
  }
}
getParamType()
TColorStyle::ParamType TStripeFillStyle::getParamType (int paramIdx) const override virtual
Returns the type of the specified parameter.
Reimplemented from TColorStyle.
{
  assert(0 <= index && index < getParamCount());
  return TColorStyle::DOUBLE;
}
References TColorStyle::DOUBLE, and getParamCount().
getParamValue()
double TStripeFillStyle::getParamValue (TColorStyle::double_tag , int index) const override virtual
Retrieves the specified double parameter value.
Reimplemented from TColorStyle.
{
  assert(0 <= index && index < 3);
  switch (index) {
  case 0:
    return m_Dist;
  case 1:
    return m_Angle;
  case 2:
    return m_Thickness;
  }
  return 0.0;
}
getTagId()
int TStripeFillStyle::getTagId () const inline override virtual
Returns an unique number representing the style.
Implements TColorStyle.
{ return 1137; };
isRegionStyle()
bool TStripeFillStyle::isRegionStyle () const inline override virtual
Returns whether the style applies on regions.
Implements TColorStyle.
{ return true; }
isStrokeStyle()
bool TStripeFillStyle::isStrokeStyle () const inline override virtual
Returns whether the style applies on strokes.
Implements TColorStyle.
{ return false; }
loadData()
void TStripeFillStyle::loadData (TInputStreamInterface & is) override protected virtual
Implements TColorStyle.
{
  TSolidColorStyle::loadData(is);
  is >> m_Dist;
  is >> m_Angle;
  is >> m_Thickness;
  is >> m_pointColor;
}
makeIcon()
void TStripeFillStyle::makeIcon (const TDimension & d) override protected virtual
Reimplemented from TColorStyle.
{
  // Saves the values of member variables and sets the right icon values
  double LDist      = m_Dist;
  double LAngle     = m_Angle;
  double LThickness = m_Thickness;
  m_Dist *= 1.33;
  m_Thickness *= 1.66;
  TColorStyle::makeIcon(d);
  m_Dist      = LDist;
  m_Angle     = LAngle;
  m_Thickness = LThickness;
}
saveData()
void TStripeFillStyle::saveData (TOutputStreamInterface & os) const override protected virtual
Implements TColorStyle.
{
  TSolidColorStyle::saveData(os);
  os << m_Dist;
  os << m_Angle;
  os << m_Thickness;
  os << m_pointColor;
}
setColorParamValue()
void TStripeFillStyle::setColorParamValue (int index, const TPixel32 & color) override virtual
Sets the index-th color value.
Reimplemented from TColorStyle.
{
  if (index == 0)
    m_pointColor = color;
  else {
    TSolidColorStyle::setMainColor(color);
  }
}
References TSolidColorStyle::setMainColor().
setParamValue()
void TStripeFillStyle::setParamValue (int index, double value) override virtual
extension value in text form.
Assigns a value to the specified double parameter.
Reimplemented from TColorStyle.
{
  assert(0 <= index && index < 3);
  switch (index) {
  case 0:
    m_Dist = value;
    break;
  case 1:
    m_Angle = value;
    break;
  case 2:
    m_Thickness = value;
    break;
  }
}
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/colorfx/regionstyles.h
E:/opentoonz/toonz/sources/colorfx/regionstyles.cpp