opentoonz: ThumbnailViewer Class Reference
ThumbnailViewer Class Reference
Classes
class NameField
Public Member Functions
ThumbnailViewer (TWidget *parent, string name="thumbnailViewer")
void addItem (Thumbnail *item)
void removeItem (Thumbnail *item)
removes the item from the ThumbnailViewer. It doesn't destroy the item
TDimension getIconSize () const
int getItemCount () const
Thumbnail * getItem (int index) const
int getColumnCount () const
find the max number of thumbnails which fit the current widget width
TPoint getItemPos (int index)
TRect getItemBounds (int index)
int findItem (const TPoint &pos)
void configureNotify (const TDimension &d)
void drawFrame (int index)
draw the index-th thumbnail current frame
void drawItem (int index)
draw the index-th thumbnail
void drawBackground ()
draw the empty space around and between thumbnails
void repaint ()
void leftButtonDown (const TMouseEvent &e)
void leftButtonDrag (const TMouseEvent &e)
void leftButtonUp (const TMouseEvent &e)
void leftButtonDoubleClick (const TMouseEvent &e)
void onTimer (int)
void startPlaying ()
void stopPlaying ()
void select (int)
int getSelectedItemIndex ()
void clearItems ()
void loadDirectory (const TFilePath &dirPath, const vector< string > &fileTypes)
void updateContentSize ()
void middleButtonDown (const TMouseEvent &e)
void middleButtonDrag (const TMouseEvent &e)
void middleButtonUp (const TMouseEvent &e)
void scrollPage (int y)
virtual void onDoubleClick (int index)
virtual void onSelect (int index)
Public Member Functions inherited from TScrollView
TScrollView (TWidget *parent, std::string name="scrollview")
void middleButtonDown (const TMouseEvent &e)
void middleButtonDrag (const TMouseEvent &e)
void middleButtonUp (const TMouseEvent &e)
void configureNotify (const TDimension &d)
void doScrollTo (const TPoint &p)
void doScrollTo (int x, int y)
void doScrollTo_x (int x)
void doScrollTo_y (int y)
virtual void scrollTo (const TPoint &p)
void scrollTo (int x, int y)
TPoint getScrollPosition () const
void setScrollbars (TScrollbar *hsb, TScrollbar *vsb)
void setContentSize (const TDimension &d)
TDimension getContentSize () const
void onVsbChange (int value)
void onHsbChange (int value)
void onTimer (int t)
void startAutopanning ()
void stopAutopanning ()
bool isAutopanning () const
virtual void autopanningDrag (const TPoint &pos)
void updateScrollbars ()
Public Member Functions inherited from TWidget
TWidget (TWidget *parent=0, std::string name="unnamed")
const TRect & getGeometry () const
TPoint getPosition () const
virtual TPoint getHotSpot () const
TDimension getSize () const
TRect getBounds () const
int getLx () const
int getLy () const
void setPlacement (const TRect &rect)
void setGeometry (int x0, int y0, int x1, int y1)
virtual void setGeometry (const TRect &rect)
void setGeometry (const TPoint &pos, const TDimension &size)
void setSize (int w, int h)
void setSize (const TDimension &size)
void setPosition (int x, int y)
void setPosition (const TPoint &pt)
bool contains (int x, int y) const
bool contains (const TPoint &p) const
TPoint getScreenPosition () const
TWidget * getParent () const
std::string getName () const
virtual void setParent (TWidget *p)
virtual void addSon (TWidget *son)
virtual void removeSon (TWidget *son)
int getSonCount () const
TWidget * getSon (int i) const
std::wstring getLongHelp () const
std::wstring getShortHelp () const
void setHelp (std::string shortHelp, std::string longHelp)
void setHelp (std::wstring shortHelp, std::wstring longHelp)
virtual std::string getContextHelpReference (const TPoint &)
void setContextHelpReference (std::string s)
virtual std::wstring getTooltipString (const TPoint &)
bool isHidden () const
bool isMapped () const
void enable ()
void disable ()
bool isEnabled () const
void show ()
void hide ()
virtual void map ()
virtual void unmap ()
virtual void doModal ()
virtual void undock ()
virtual void dock (TWidget *parent)
virtual TWidget * findSubWidget (const TPoint &pt)
virtual void repaint ()
void sendRepaint ()
void sendRepaint (const TRect &)
virtual void paste ()
virtual void startDragAndDrop (std::string stringToDrop)
CursorIndex getCurrentCursor ()
void changeCursor (CursorIndex new_cur)
TWidgetImp * getImp ()
void startTimer (TINT32 period)
void stopTimer ()
virtual void getSelection ()
virtual void onFocusChange (bool on)
virtual bool getFocus ()
virtual void circulateFocus ()
virtual void copyRegion (const TPoint &dst, const TPoint &src, const TDimension &size)
void flush ()
virtual void draw ()
virtual void invalidate ()
virtual void invalidate (const TRect &rect)
void getClipRect (TRect &rect)
virtual void clear ()
virtual void drawText (const TPoint &p, std::string text)
virtual void drawText (const TPoint &p, std::wstring text)
virtual void drawText (const TRect &r, std::string text, Alignment alignment=CENTER)
virtual void drawText (const TRect &r, std::wstring text, Alignment alignment=CENTER)
virtual void drawMultiLineText (const TRect &r, std::string text)
virtual void drawMultiLineText (const TRect &r, std::wstring text)
virtual TDimension getTextSize (std::string text)
virtual TDimension getTextSize (std::wstring text)
virtual TDimension getTextSize (std::string text, std::string font, int fontSize)
virtual TDimension getTextSize (std::wstring text, std::string font, int fontSize)
void drawPoint (int x, int y)
virtual void drawLine (const TPoint &p0, const TPoint &p1)
void drawLine (int x0, int y0, int x1, int y1)
virtual void drawVLine (const TPoint &p0, int length)
virtual void drawHLine (const TPoint &p0, int length)
virtual void drawDottedLine (const TPoint &p0, const TPoint &p1)
void drawDottedLine (int x0, int y0, int x1, int y1)
virtual void drawRect (const TRect &)
virtual void fillRect (const TRect &)
virtual void drawRect (int x0, int y0, int x1, int y1)
virtual void fillRect (int x0, int y0, int x1, int y1)
virtual void draw3DRect (const TRect &, bool pressed=false, int border=1)
virtual void fill3DRect (const TRect &, bool pressed=false, int border=1)
virtual void drawDottedRect (const TRect &)
virtual void drawDottedRect (int x0, int y0, int x1, int y1)
virtual void fillPolygon (const TGuiColor &fillColor, const TGuiColor &borderColor, const TPoint points[], int pointCount)
virtual void clear (const TRect &)
virtual void drawImage (int index, const TPoint &)
virtual void setColor (const TGuiColor &, int shade=0)
virtual void setBackgroundColor (const TGuiColor &)
TGuiColor getBackgroundColor () const
TGuiColor getForegroundColor () const
virtual void rectwrite (const TRaster32P &, const TPoint &)
virtual void setFontSize (int size)
virtual void setFont (std::string name, int size=0, int orientation=0)
virtual void enter (const TPoint &)
virtual void leave (const TPoint &)
virtual void mouseMove (const TMouseEvent &)
virtual void leftButtonDown (const TMouseEvent &)
virtual void leftButtonDrag (const TMouseEvent &)
virtual void leftButtonUp (const TMouseEvent &)
virtual void rightButtonDown (const TMouseEvent &)
virtual void rightButtonDrag (const TMouseEvent &)
virtual void rightButtonUp (const TMouseEvent &)
virtual void middleButtonDown (const TMouseEvent &)
virtual void middleButtonDrag (const TMouseEvent &)
virtual void middleButtonUp (const TMouseEvent &)
virtual void leftButtonDoubleClick (const TMouseEvent &)
virtual void middleButtonDoubleClick (const TMouseEvent &)
virtual void rightButtonDoubleClick (const TMouseEvent &)
virtual void mouseWheel (const TMouseEvent &, int wheel)
virtual void keyDown (int, TUINT32, const TPoint &)
virtual void configureNotify (const TDimension &)
virtual void onPaste (std::string)
virtual void onDrop (std::string)
virtual std::string getToolTip ()
virtual void onTimer (int)
virtual void onChildrenChanged ()
virtual bool onNcPaint (bool is_active, const TDimension &window_size, const TRect &caption_rect)
virtual FocusHandling getFocusHandling () const
virtual void maximize (TWidget *)
virtual bool isMaximized (TWidget *)
void enableDropTarget (TDragDropListener *dragDropListener)
TDragDropListener * getDragDropListener () const
TPoint getAbsolutePosition () const
TPoint getMouseRelativePosition () const
bool isMenuRelated () const
Additional Inherited Members
Public Types inherited from TWidget
enum Alignment { BEGIN , CENTER , END }
enum FocusHandling { IGNORE_FOCUS , STOP_FOCUS , LISTEN_TO_FOCUS }
typedef unsigned int CursorIndex
Static Public Member Functions inherited from TWidget
static void setFocusOwner (TWidget *w)
static TWidget * getFocusOwner ()
static void placeInteractively (TRect &)
static void yield ()
static void setMode (int mode)
static TPoint getMouseAbsolutePosition ()
static void processAllPendingMessages ()
static void processAllPendingMessages2 ()
static TDimension getScreenSize ()
static void getScreenPlacement (std::vector< TRectI > &)
Static Public Attributes inherited from TWidget
static const TGuiColor White
static const TGuiColor Black
Protected Member Functions inherited from TWidget
virtual void create ()
virtual void setDecoration ()
virtual void destroyImp ()
void createSons ()
Protected Attributes inherited from TWidget
TRect m_placement
int m_xoff
int m_yoff
bool m_mapped
bool m_hidden
bool m_childrenChanged
TWidget * m_parent
TWidget * m_sonKeeper
std::string m_name
std::string m_contextHelpReference
std::wstring m_shortHelp
std::wstring m_longHelp
int m_cursorIdx
TWidgetList * m_sons
TWidgetImp * m_imp
TGuiColor m_backgroundColor
TGuiColor m_foregroundColor
bool m_popupMode
bool m_menuMode
bool m_fixedSize
bool m_fullColor
bool m_openGL
bool m_enabled
bool m_menuRelated
TDragDropListener * m_dragDropListener
std::string m_fontName
int m_fontSize
int m_fontOrientation
Static Protected Attributes inherited from TWidget
static TWidget * m_selectionOwner
static TWidget * m_focusOwner
Detailed Description
Constructor & Destructor Documentation
ThumbnailViewer()
ThumbnailViewer::ThumbnailViewer (TWidget * parent, string name = "thumbnailViewer")
    : TScrollView(parent, name)
    , m_selectedItemIndex(-1)
    , m_itemSize(94, 100)
    , m_itemSpace(10, 10)
    , m_margins(10, 10)
    , m_playButtonBox(TPoint(85, 2), TDimension(10, 10))
    , m_iconBox(TPoint(2 + 4 - 3, 20 + 4), TDimension(96 - 8, 78 - 8))
    , m_textBox(TPoint(2 + 4 + 2 + 10, 2 + 2), TDimension(65, 18))
    , m_flag(false)
    , m_playing(false)
    , m_loading(false)
    , m_timerActive(false)
    , m_dragDropArmed(false)
    , m_oldPos(0, 0) {
  setBackgroundColor(White);
  m_nameField = new NameField(this);
  m_nameField->hide();
}
~ThumbnailViewer()
ThumbnailViewer::~ThumbnailViewer ()
{ clearPointerContainer(m_items); }
Member Function Documentation
addItem()
void ThumbnailViewer::addItem (Thumbnail * item)
{ m_items.push_back(item); }
clearItems()
void ThumbnailViewer::clearItems ()
{
  clearPointerContainer(m_items);
  m_selectedItemIndex = -1;
  m_playing           = false;
  m_loading           = false;
  if (m_timerActive) {
    stopTimer();
    m_timerActive = false;
  }
}
configureNotify()
void ThumbnailViewer::configureNotify (const TDimension & d) virtual
Reimplemented from TScrollView.
{
  TScrollView::configureNotify(d);
  // m_nameField->setGeometry(TPoint(10,10), TDimension(100,30));
  updateContentSize();
  invalidate();
}
drawBackground()
void ThumbnailViewer::drawBackground ()
draw the empty space around and between thumbnails
{
  int itemCount   = m_items.size();
  int columnCount = getColumnCount();
  int rowCount    = (itemCount + columnCount - 1) / columnCount;
  TRect clipRect;
  getClipRect(clipRect);  // coordinate window
  clipRect -= TPoint(m_xoff, m_yoff);
  TRect rect;
  rect.x0 = m_margins.lx;
  rect.x1 = m_margins.lx + (m_itemSize.lx + m_itemSpace.lx) * columnCount -
            m_itemSpace.lx - 1;
  rect.y1 = getLy() - m_margins.ly - 1;
  rect.y0 = rect.y1 - (m_itemSize.ly + m_itemSpace.ly) * rowCount +
            m_itemSpace.ly + 1;
  setColor(getBackgroundColor());
  // alto
  if (rect.y1 + 1 <= clipRect.y1)
    fillRect(clipRect.x0, rect.y1 + 1, clipRect.x1, clipRect.y1);
  // basso
  if (clipRect.y0 <= rect.y0 - 1)
    fillRect(clipRect.x0, clipRect.y0, clipRect.x1, rect.y0 - 1);
  int y0 = tmax(clipRect.y0, rect.y0);
  int y1 = tmin(clipRect.y1, rect.y1);
  if (y0 <= y1) {
    // sinistra
    if (clipRect.x0 <= rect.x0 - 1) fillRect(clipRect.x0, y0, rect.x0 - 1, y1);
    // destra
    if (rect.x1 + 1 <= clipRect.x1) fillRect(rect.x1 + 1, y0, clipRect.x1, y1);
  }
  // interlinee verticali
  for (int r = 0; r < rowCount; r++) {
    int y1 = rect.y1 - (m_itemSize.ly + m_itemSpace.ly) * r + m_itemSpace.ly;
    int y0 = y1 - m_itemSpace.ly + 1;
    fillRect(clipRect.x0, y0, clipRect.x1, y1);
  }
  for (int c = 0; c < columnCount - 1; c++) {
    int x0 =
        m_margins.lx + (m_itemSize.lx + m_itemSpace.lx) * c + m_itemSize.lx;
    int x1 = x0 + m_itemSpace.lx - 1;
    fillRect(x0, clipRect.y0, x1, clipRect.y1);
  }
  // ultima riga
  c = itemCount % columnCount;
  if (c != 0) {
    TRect box = getItemBounds(itemCount - 1);
    if (box.y0 <= clipRect.y1 && box.y1 >= clipRect.y0 &&
        box.x1 + 1 <= clipRect.x1)
      fillRect(box.x1 + 1, box.y0, clipRect.x1, box.y1);
  }
}
References getColumnCount(), and TRectT< T >::x0.
drawFrame()
void ThumbnailViewer::drawFrame (int index)
draw the index-th thumbnail current frame
{
  TPoint base = getItemPos(index);
  assert(0 <= index && index < (int)m_items.size());
  assert(m_items[index]->getRaster());
  assert(m_iconBox.getSize() == m_items[index]->getRaster()->getSize());
  rectwrite(m_items[index]->getRaster(), base + m_iconBox.getP00());
}
References getItemPos().
drawItem()
void ThumbnailViewer::drawItem (int index)
draw the index-th thumbnail
{
  TPoint base = getItemPos(index);
  if (index < 0 || index >= (int)m_items.size()) {
    setColor(getBackgroundColor());
    fillRect(TRect(base, m_itemSize));
    return;
  }
  // setColor(Black);
  // fillRect(TRect(base, m_itemSize));
  Thumbnail *item = m_items[index];
  bool selected   = item != 0 && index == m_selectedItemIndex;
  TRect r0(base, m_itemSize);
  TRect r1 = m_iconBox + base;
  TRect r2 = m_textBox + base;
  setColor(selected ? Cyan : getBackgroundColor());
  fillRect(r0.x0, r1.y0, r1.x0 - 1, r1.y1);  // sinistra
  fillRect(r1.x1 + 1, r1.y0, r0.x1, r1.y1);  // destra
  fillRect(r0.x0, r0.y0, r0.x1, r1.y0 - 1);  // sotto
  // fillRect(r1.x0,r1.y1+1,r1.x1,r0.y1); // sopra
  TRect topLine(r0.x0, r1.y1 + 1, r0.x1, r0.y1);
  TRect sceneLine = topLine;
  sceneLine.y0    = sceneLine.y1 - 3;
  topLine.y1      = sceneLine.y0 - 1;
  fillRect(topLine);
  if (item->getType() == Thumbnail::SCENE) {
    setColor(Black);
    drawRect(sceneLine);
    setColor(White);
    fillRect(sceneLine.enlarge(-1));
    int x;
    setColor(Black);
    for (x = sceneLine.x0 + 5; x + 5 < sceneLine.x1; x += 10) {
      int y = sceneLine.y0 + 1;
      drawLine(x, y, x + 4, y);
      y++;
      x++;
      drawLine(x, y, x + 4, y);
    }
  } else {
    setColor(White);
    fillRect(sceneLine);
  }
  string name   = item->getName();
  int maxWidth  = r2.getLx() - 4;
  TDimension ts = getTextSize(name);
  if (ts.lx > maxWidth) {
    do {
      name.pop_back();
      ts = getTextSize(name);
    } while (name.size() > 1 && ts.lx > maxWidth);
  }
  TPoint textOrigin = r2.getP00() + TPoint(2 - 10, (r2.getLy() - ts.ly) / 2);
  setColor(Black);
  string fname          = name;
  string type           = item->getPath().getType();
  if (type != "") fname = fname + "." + type;
  fname = item->getPath().getLevelName();
  drawText(textOrigin, fname);
  if (selected) {
    TRect r = m_playButtonBox + base;
    setColor(Blue);
    if (m_playing) {
      int x0 = r.x0, x3 = r.x1;
      int x1 = (x0 + x3) / 2 - 1;
      int x2 = x3 - (x1 - x0);
      drawRect(x0, r.y0, x1, r.y1);
      drawRect(x2, r.y0, x3, r.y1);
    } else {
      vector<TPoint> pts;
      int d = (r.y1 - r.y0 + 1) / 2;
      int x = r.x0;
      int y = r.y0;
      pts.push_back(TPoint(x, y));
      pts.push_back(TPoint(x + d, y + d));
      pts.push_back(TPoint(x, y + d * 2));
      fillPolygon(Cyan, Blue, &pts[0], 3);
    }
  }
  assert(0 <= index && index < (int)m_items.size());
  assert(m_items[index]->getRaster());
  assert(m_iconBox.getSize() == m_items[index]->getRaster()->getSize());
  rectwrite(m_items[index]->getRaster(), base + m_iconBox.getP00());
}
References getItemPos(), TFilePath::getLevelName(), TFilePath::getType(), and TRectT< T >::x0.
findItem()
int ThumbnailViewer::findItem (const TPoint & pos)
{
  int columnCount = getColumnCount();
  int col         = (pos.x - m_margins.lx) / (m_itemSize.lx + m_itemSpace.lx);
  int row         = (getLy() - m_margins.ly - m_itemSpace.ly - pos.y) /
            (m_itemSize.ly + m_itemSpace.ly);
  int index = row * columnCount + col;
  if (0 <= index && index < (int)m_items.size() &&
      getItemBounds(index).contains(pos))
    return index;
  else
    return -1;
}
getColumnCount()
int ThumbnailViewer::getColumnCount () const
find the max number of thumbnails which fit the current widget width
{
  int columnWidth    = m_itemSize.lx + m_itemSpace.lx;
  int availableWidth = getLx() - m_margins.lx * 2 + m_itemSpace.lx;
  return tmax(1, (availableWidth) / columnWidth);
}
Referenced by drawBackground(), and getItemPos().
getIconSize()
TDimension ThumbnailViewer::getIconSize () const inline
{ return m_iconBox.getSize(); }
getItem()
Thumbnail * ThumbnailViewer::getItem (int index) const
{
  assert(0 <= index && index < (int)m_items.size());
  return m_items[index];
}
getItemBounds()
TRect ThumbnailViewer::getItemBounds (int index)
{
  return TRect(getItemPos(index), m_itemSize);
}
getItemCount()
int ThumbnailViewer::getItemCount () const
{ return m_items.size(); }
getItemPos()
TPoint ThumbnailViewer::getItemPos (int index)
find the bottom-left corner coordinate of the index-th thumbnail (icon+controls)
{
  int columnCount = getColumnCount();
  int row         = index / columnCount;
  int col         = index % columnCount;
  int x           = m_margins.lx + col * (m_itemSize.lx + m_itemSpace.lx);
  int y           = getLy() - m_margins.ly - m_itemSize.ly -
          row * (m_itemSize.ly + m_itemSpace.ly);
  return TPoint(x, y);
}
References getColumnCount().
Referenced by drawFrame(), and drawItem().
getSelectedItemIndex()
int ThumbnailViewer::getSelectedItemIndex () inline
{ return m_selectedItemIndex; }
leftButtonDoubleClick()
void ThumbnailViewer::leftButtonDoubleClick (const TMouseEvent & e) virtual
Reimplemented from TWidget.
{
  TPoint pos = e.m_pos - TPoint(m_xoff, m_yoff);
  m_nameField->hide();
  int index = findItem(pos);
  if (index >= 0) onDoubleClick(index);
}
leftButtonDown()
void ThumbnailViewer::leftButtonDown (const TMouseEvent & e) virtual
Reimplemented from TWidget.
{
  TPoint pos      = e.m_pos - TPoint(m_xoff, m_yoff);
  m_oldPos        = e.m_pos;
  m_dragDropArmed = false;
  m_nameField->hide();
  //  if(setGeometry(m_textBox + bounds.getP00());
  //           m_nameField->setText(m_items[index]->getName());
  //           m_nameField->show();
  int index = findItem(pos);
  if (index >= 0) {
    if (m_selectedItemIndex == index) {
      TRect bounds = getItemBounds(index);
      pos -= bounds.getP00();
      if (m_playButtonBox.contains(pos)) {
        if (!m_playing)
          startPlaying();
        else
          stopPlaying();
        invalidate();
      } else if (m_textBox.contains(pos)) {
        stopPlaying();
        m_nameField->setGeometry(m_textBox + bounds.getP00() + TPoint(-10, 0));
        m_nameField->setThumbnail(m_items[index]);
        m_nameField->show();
        setFocusOwner(m_nameField);
      } else {
        m_dragDropArmed = true;
      }
    } else {
      select(index);
      m_dragDropArmed = true;
    }
  } else
    select(-1);
  invalidate();
}
leftButtonDrag()
void ThumbnailViewer::leftButtonDrag (const TMouseEvent & e) virtual
Reimplemented from TWidget.
{
  if (!m_dragDropArmed || m_selectedItemIndex < 0) return;
  if (norm2(e.m_pos - m_oldPos) < 100) return;
  m_dragDropArmed = false;
  Thumbnail *item = m_items[m_selectedItemIndex];
  TFilePath path  = item->getPath();
  if (path.getWideString() != toWideString("")) {
    TDropSource dropSource;
    std::vector<std::string> v;
    v.push_back(toString(path.getWideString()));
    TDataObject data(v);
    dropSource.doDragDrop(data);
  }
}
leftButtonUp()
void ThumbnailViewer::leftButtonUp (const TMouseEvent & e) virtual
Reimplemented from TWidget.
{
  m_dragDropArmed = false;
}
loadDirectory()
void ThumbnailViewer::loadDirectory (const TFilePath & dirPath, const vector< string > & fileTypes)
{
  clearItems();
  TFilePathSet fps;
  try {
    fps = TSystem::readDirectory(dirPath);
  } catch (...) {
    TMessage::error(toString(dirPath.getWideString()) +
                    ": can't read directory");
    updateContentSize();
    return;
  }
  fps = TSystem::packLevelNames(fps);
  fps.sort();
  for (TFilePathSet::iterator it = fps.begin(); it != fps.end(); it++) {
    try {
      TFilePath fp = *it;
      if (fp.getType() == "bmp" && fp.getName().find("_icon") != string::npos)
        continue;
      if (std::find(fileTypes.begin(), fileTypes.end(), fp.getType()) ==
          fileTypes.end())
        continue;
      Thumbnail *item = FileThumbnail::create(m_iconBox.getSize(), fp);
      if (item) m_items.push_back(item);
    } catch (...) {
      TMessage::error(toString(it->getWideString()) + ": can't read thumbnail");
    }
  }
  updateContentSize();
}
middleButtonDown()
void ThumbnailViewer::middleButtonDown (const TMouseEvent & e) inline virtual
Reimplemented from TScrollView.
{}
middleButtonDrag()
void ThumbnailViewer::middleButtonDrag (const TMouseEvent & e) inline virtual
Reimplemented from TScrollView.
{}
middleButtonUp()
void ThumbnailViewer::middleButtonUp (const TMouseEvent & e) inline virtual
Reimplemented from TScrollView.
{}
onDoubleClick()
virtual void ThumbnailViewer::onDoubleClick (int index) inline virtual
{}
onSelect()
virtual void ThumbnailViewer::onSelect (int index) inline virtual
{}
onTimer()
void ThumbnailViewer::onTimer (int) virtual
Reimplemented from TScrollView.
{
  stopTimer();
  m_timerActive = false;
  if (m_playing && m_selectedItemIndex >= 0) {
    Thumbnail *thumbnail = m_items[m_selectedItemIndex];
    bool ret             = thumbnail->nextFrame();
    if (ret) {
      m_timerActive = true;
      startTimer(100);
    } else {
      thumbnail->gotoFrame(0);
      thumbnail->setPlaying(false);
      m_playing = false;
    }
    invalidate();
  } else if (m_loading) {
    for (int i = 0; i < (int)m_items.size(); i++)
      if (!m_items[i]->isIconLoaded()) {
        m_items[i]->loadIcon();
        invalidate();
        return;
      }
  }
}
removeItem()
void ThumbnailViewer::removeItem (Thumbnail * item)
removes the item from the ThumbnailViewer. It doesn't destroy the item
{
  std::vector<Thumbnail *>::iterator it =
      std::find(m_items.begin(), m_items.end(), item);
  if (it != m_items.end()) m_items.erase(it);
  m_selectedItemIndex = -1;
}
repaint()
void ThumbnailViewer::repaint () virtual
Reimplemented from TWidget.
{
  if (m_flag) {
    if (m_selectedItemIndex) drawFrame(m_selectedItemIndex);
  } else {
    // m_loadingDirectory = false;
    // setColor(Black);
    // fillRect(getBounds());
    drawBackground();
    TRect clipRect;
    getClipRect(clipRect);  // coordinate window
    clipRect -= TPoint(m_xoff, m_yoff);
    bool loading = false;
    for (int i = 0; i < (int)m_items.size(); i++) {
      TRect bounds = getItemBounds(i);
      if (bounds.overlaps(clipRect)) {
        drawItem(i);
        if (m_items[i]->isIconLoaded() == false) loading = true;
      }
    }
    if (loading) {
      m_loading = true;
      if (!m_timerActive) {
        m_timerActive = true;
        startTimer(200);
      }
    }
  }
}
scrollPage()
void ThumbnailViewer::scrollPage (int y)
{ doScrollTo_y(tmax(y, 0)); }
select()
void ThumbnailViewer::select (int index)
{
  assert(index == -1 || 0 <= index && index < (int)m_items.size());
  m_playing = false;
  if (m_timerActive) {
    m_timerActive = false;
    stopTimer();
  }
  Thumbnail *thumbnail;
  if (m_selectedItemIndex >= 0) {
    thumbnail = m_items[m_selectedItemIndex];
    thumbnail->setPlaying(false);
  }
  m_selectedItemIndex = index;
  onSelect(m_selectedItemIndex);
}
startPlaying()
void ThumbnailViewer::startPlaying ()
{
  if (m_playing) return;
  if (m_selectedItemIndex < 0) return;
  m_playing = true;
  assert(0 <= m_selectedItemIndex && m_selectedItemIndex < (int)m_items.size());
  m_items[m_selectedItemIndex]->setPlaying(true);
  if (!m_timerActive) {
    m_timerActive = true;
    startTimer(200);
  }
}
stopPlaying()
void ThumbnailViewer::stopPlaying ()
{
  if (!m_playing) return;
  m_playing = false;
  if (m_selectedItemIndex >= 0) {
    assert(0 <= m_selectedItemIndex &&
           m_selectedItemIndex < (int)m_items.size());
    m_items[m_selectedItemIndex]->gotoFrame(0);
    m_items[m_selectedItemIndex]->setPlaying(false);
  }
  if (m_timerActive) {
    m_timerActive = false;
    stopTimer();
  }
}
updateContentSize()
void ThumbnailViewer::updateContentSize ()
{
  int itemCount   = m_items.size();
  int columnCount = getColumnCount();
  int rowCount    = (itemCount + columnCount - 1) / columnCount;
  TRect rect;
  int yrange = rowCount * (m_itemSize.ly + m_itemSpace.ly) - m_itemSpace.ly +
               m_margins.ly * 2;
  setContentSize(TDimension(getLx(), yrange));
}
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/toonzfarm/tfarmclient/thumbnailviewer.h
E:/opentoonz/toonz/sources/toonzfarm/tfarmclient/thumbnailviewer.cpp