opentoonz: ShadingContext Class Reference
ShadingContext Class Reference
Classes
struct Imp
Public Types
enum Support { OK , NO_PIXEL_BUFFER , NO_SHADERS }
Public Member Functions
ShadingContext (QOffscreenSurface *)
bool isValid () const
void makeCurrent ()
void doneCurrent ()
void resize (int lx, int ly, const QOpenGLFramebufferObjectFormat &fmt=QOpenGLFramebufferObjectFormat())
QOpenGLFramebufferObjectFormat format () const
TDimension size () const
void addShaderProgram (const QString &shaderName, QOpenGLShaderProgram *program)
void addShaderProgram (const QString &shaderName, QOpenGLShaderProgram *program, const QDateTime &lastModified)
bool removeShaderProgram (const QString &shaderName)
QOpenGLShaderProgram * shaderProgram (const QString &shaderName) const
QDateTime lastModified (const QString &shaderName) const
std::pair< QOpenGLShaderProgram *, QDateTime > shaderData (const QString &shaderName) const
GLuint loadTexture (const TRasterP &src, GLuint texUnit)
void unloadTexture (GLuint texId)
Releases the specified texture id.
void draw (const TRasterP &dst)
Renders the active shader program to the specified raster.
void transformFeedback (int varyingsCount, const GLsizeiptr *varyingSizes, GLvoid **bufs)
Performs transform feedback with the specified varying variables.
Static Public Member Functions
static Support support ()
Returns the status of OpenGL shading support.
Detailed Description
Member Enumeration Documentation
Support
enum ShadingContext::Support
{ OK, NO_PIXEL_BUFFER, NO_SHADERS };
Constructor & Destructor Documentation
ShadingContext()
ShadingContext::ShadingContext (QOffscreenSurface * surface)
                                                         : m_imp(new Imp) {
  m_imp->m_surface = surface;
  m_imp->m_surface->create();
  QSurfaceFormat format;
  m_imp->m_context->setFormat(format);
  m_imp->m_context->create();
  m_imp->m_context->makeCurrent(m_imp->m_surface);
  // m_imp->m_pixelBuffer->context()->create();
  // m_imp->m_fbo(new QOpenGLFramebufferObject(1, 1));
  makeCurrent();
   if( GLEW_VERSION_3_2 ) {
       glewExperimental = GL_TRUE;
   }
  glewInit();
  doneCurrent();
}
~ShadingContext()
ShadingContext::~ShadingContext ()
{
  // Destructor of QGLPixelBuffer calls QOpenGLContext::makeCurrent()
  // internally,
  // so the current thread must be the owner of QGLPixelBuffer context,
  // when the destructor of m_imp->m_context is called.
  m_imp->m_context->moveToThread(QThread::currentThread());
}
Member Function Documentation
addShaderProgram() [1/2]
void ShadingContext::addShaderProgram (const QString & shaderName, QOpenGLShaderProgram * program)
Surrenders ownership of the supplied shader program to the shading context.
{
  std::map<QString, CompiledShader>::iterator st =
      m_imp->m_shaderPrograms
          .insert(std::make_pair(shaderName, CompiledShader()))
          .first;
  st->second.m_program.reset(program);
}
addShaderProgram() [2/2]
void ShadingContext::addShaderProgram (const QString & shaderName, QOpenGLShaderProgram * program, const QDateTime & lastModified)
{
  std::map<QString, CompiledShader>::iterator st =
      m_imp->m_shaderPrograms
          .insert(std::make_pair(shaderName, CompiledShader()))
          .first;
  st->second.m_program.reset(program);
  st->second.m_lastModified = lastModified;
}
doneCurrent()
void ShadingContext::doneCurrent ()
{
  m_imp->m_context->moveToThread(0);
  m_imp->m_context->doneCurrent();
}
draw()
void ShadingContext::draw (const TRasterP & dst)
Renders the active shader program to the specified raster.
{
  assert("ShadingContext::resize() must be invoked at least once before this" &&
         m_imp->m_fbo.get());
  int lx = dst->getLx(),
      ly = dst->getLy();  // NOTE: We're not using m_imp->m_fbo's size, since
                          // it could be possibly greater than the required
                          // destination surface.
  m_imp->initMatrix(lx, ly);  // This call sets the OpenGL viewport to this
                              // size - and matches (1, 1) to dst's (lx, ly)
  {
    glBegin(GL_QUADS);
    glVertex2f(0.0, 0.0);
    glVertex2f(lx, 0.0);
    glVertex2f(lx, ly);
    glVertex2f(0.0, ly);
    glEnd();
  }
  glPixelStorei(GL_PACK_ROW_LENGTH, dst->getWrap());
  // Read the fbo to dst
  if (TRaster32P ras32 = dst)
    glReadPixels(0, 0, lx, ly, GL_BGRA_EXT, GL_UNSIGNED_BYTE,
                 dst->getRawData());
  else {
    assert(TRaster64P(dst));
    glReadPixels(0, 0, lx, ly, GL_BGRA_EXT, GL_UNSIGNED_SHORT,
                 dst->getRawData());
  }
  assert(glGetError() == GL_NO_ERROR);
}
References TRaster::getRawData(), and TRaster::getWrap().
format()
QOpenGLFramebufferObjectFormat ShadingContext::format () const
{
  QOpenGLFramebufferObject *fbo = m_imp->m_fbo.get();
  return fbo ? m_imp->m_fbo->format() : QOpenGLFramebufferObjectFormat();
}
isValid()
bool ShadingContext::isValid () const
{ return m_imp->m_context->isValid(); }
lastModified()
QDateTime ShadingContext::lastModified (const QString & shaderName) const
{
  std::map<QString, CompiledShader>::iterator st =
      m_imp->m_shaderPrograms.find(shaderName);
  return (st != m_imp->m_shaderPrograms.end()) ? st->second.m_lastModified
                                               : QDateTime();
}
loadTexture()
GLuint ShadingContext::loadTexture (const TRasterP & src, GLuint texUnit)
Loads a texture and binds it to
{
  glActiveTexture(GL_TEXTURE0 + texUnit);
  GLuint texId;
  glGenTextures(1, &texId);
  glBindTexture(GL_TEXTURE_2D, texId);
  glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S,
                  GL_CLAMP);  // These must be used on a bound texture,
  glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T,
                  GL_CLAMP);  // and are remembered in the OpenGL context.
  glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER,
                  GL_NEAREST);  // They can be set here, no need for
  glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER,
                  GL_NEAREST);  // the user to do it.
  glPixelStorei(GL_UNPACK_ROW_LENGTH, src->getWrap());
  glPixelStorei(GL_UNPACK_ALIGNMENT, 1);
  GLenum chanType = TRaster32P(src) ? GL_UNSIGNED_BYTE : GL_UNSIGNED_SHORT;
  glTexImage2D(GL_TEXTURE_2D,
               0,             // one level only
               GL_RGBA,       // pixel channels count
               src->getLx(),  // width
               src->getLy(),  // height
               0,             // border size
               TGL_FMT,       // pixel format
               chanType,      // channel data type
               (GLvoid *)src->getRawData());
  assert(glGetError() == GL_NO_ERROR);
  return texId;
}
References TRaster::getRawData(), and TRaster::getWrap().
makeCurrent()
void ShadingContext::makeCurrent ()
{
  m_imp->m_context->moveToThread(QThread::currentThread());
  m_imp->m_context.reset(new QOpenGLContext());
  QSurfaceFormat format;
  m_imp->m_context->setFormat(format);
  m_imp->m_context->create();
  m_imp->m_context->makeCurrent(m_imp->m_surface);
}
removeShaderProgram()
bool ShadingContext::removeShaderProgram (const QString & shaderName)
{
  return (m_imp->m_shaderPrograms.erase(shaderName) > 0);
}
resize()
void ShadingContext::resize (int lx, int ly, const QOpenGLFramebufferObjectFormat & fmt = QOpenGLFramebufferObjectFormat())
Resizes the output buffer to the specified size. Requires that the context is made current before invocation. In case lx or ly are 0, the context's output buffer is destroyed.
{
  if (m_imp->m_fbo.get() && m_imp->m_fbo->width() == lx &&
      m_imp->m_fbo->height() == ly && m_imp->m_fbo->format() == fmt)
    return;
  if (lx == 0 || ly == 0) {
    m_imp->m_fbo.reset(0);
  } else {
    bool get                         = m_imp->m_fbo.get();
    QOpenGLContext *currContext      = m_imp->m_context->currentContext();
    bool yes                         = false;
    if (currContext) bool yes        = true;
    while (!currContext) currContext = m_imp->m_context->currentContext();
    m_imp->m_fbo.reset(new QOpenGLFramebufferObject(lx, ly, fmt));
    assert(m_imp->m_fbo->isValid());
    m_imp->m_fbo->bind();
  }
}
shaderData()
std::pair< QOpenGLShaderProgram *, QDateTime > ShadingContext::shaderData (const QString & shaderName) const
{
  std::map<QString, CompiledShader>::iterator st =
      m_imp->m_shaderPrograms.find(shaderName);
  return (st != m_imp->m_shaderPrograms.end())
             ? std::make_pair(st->second.m_program.get(),
                              st->second.m_lastModified)
             : std::make_pair((QOpenGLShaderProgram *)0, QDateTime());
}
shaderProgram()
QOpenGLShaderProgram * ShadingContext::shaderProgram (const QString & shaderName) const
{
  std::map<QString, CompiledShader>::iterator st =
      m_imp->m_shaderPrograms.find(shaderName);
  return (st != m_imp->m_shaderPrograms.end()) ? st->second.m_program.get() : 0;
}
size()
TDimension ShadingContext::size () const
{
  QOpenGLFramebufferObject *fbo = m_imp->m_fbo.get();
  return fbo ? TDimension(fbo->width(), fbo->height()) : TDimension();
}
support()
ShadingContext::Support ShadingContext::support () static
Returns the status of OpenGL shading support.
{
  // return !QGLPixelBuffer::hasOpenGLPbuffers()
  //           ? NO_PIXEL_BUFFER
  //           : !QOpenGLShaderProgram::hasOpenGLShaderPrograms() ? NO_SHADERS :
  //           OK;
  return !QOpenGLShaderProgram::hasOpenGLShaderPrograms() ? NO_SHADERS : OK;
}
transformFeedback()
void ShadingContext::transformFeedback (int varyingsCount, const GLsizeiptr * varyingSizes, GLvoid ** bufs)
Performs transform feedback with the specified varying variables.
{
  // Generate buffer objects
  std::vector<GLuint> bufferObjectNames(varyingsCount, 0);
  glGenBuffers(varyingsCount, &bufferObjectNames[0]);
  for (int v = 0; v != varyingsCount; ++v) {
    glBindBuffer(GL_ARRAY_BUFFER, bufferObjectNames[v]);
    glBufferData(GL_ARRAY_BUFFER, varyingSizes[v], bufs[v], GL_STATIC_READ);
    glBindBuffer(GL_ARRAY_BUFFER, 0);
    glBindBufferBase(GL_TRANSFORM_FEEDBACK_BUFFER, v, bufferObjectNames[v]);
  }
  // Draw
  GLuint Query = 0;
  glGenQueries(1, &Query);
  {
    // Disable rasterization, vertices processing only!
    glEnable(GL_RASTERIZER_DISCARD);
    glBeginQuery(GL_TRANSFORM_FEEDBACK_PRIMITIVES_WRITTEN, Query);
    glBeginTransformFeedback(GL_POINTS);
    glBegin(GL_POINTS);
    glVertex2f(0.0f, 0.0f);
    glEnd();
    glEndTransformFeedback();
    glEndQuery(GL_TRANSFORM_FEEDBACK_PRIMITIVES_WRITTEN);
    glDisable(GL_RASTERIZER_DISCARD);
  }
  GLint count = 0;
  glGetQueryObjectiv(Query, GL_QUERY_RESULT, &count);
  glDeleteQueries(1, &Query);
  // Retrieve transformed data
  for (int v = 0; v != varyingsCount; ++v) {
    glBindBuffer(GL_ARRAY_BUFFER, bufferObjectNames[v]);
    glGetBufferSubData(GL_ARRAY_BUFFER, 0, varyingSizes[v], bufs[v]);
  }
  glBindBuffer(GL_ARRAY_BUFFER, 0);
  // Delete buffer objects
  glDeleteBuffers(varyingsCount, &bufferObjectNames[0]);
}
unloadTexture()
void ShadingContext::unloadTexture (GLuint texId)
Releases the specified texture id.
the specified texture unit.
Returns
The OpenGL texture id of the loaded texture.
Parameters
src Loaded texture.
texUnit Unit the texture will be bound to.
{
  glDeleteTextures(1, &texId);
}
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/stdfx/shadingcontext.h
E:/opentoonz/toonz/sources/stdfx/shadingcontext.cpp