opentoonz: Filmstrip Class Reference
Filmstrip Class Reference final
Public Slots
void onLevelSwitched (TXshLevel *oldLevel)
void onSliderMoved (int)
void onLevelChanged ()
void updateChooseLevelComboItems ()
void onChooseLevelComboChanged (int index)
void onFrameSwitched ()
void orientationToggled (bool)
void comboBoxToggled ()
void navigatorToggled ()
Public Member Functions
Filmstrip (QWidget *parent=0, Qt::WFlags flags=0)
virtual void save (QSettings &settings) const override
virtual void load (QSettings &settings) override
virtual void save (QSettings &settings) const =0
virtual void load (QSettings &settings)=0
Protected Member Functions
void setOrientation (bool isVertical)
void showEvent (QShowEvent *) override
void hideEvent (QHideEvent *) override
void resizeEvent (QResizeEvent *) override
Detailed Description
Constructor & Destructor Documentation
Filmstrip()
Filmstrip::Filmstrip (QWidget * parent = 0, Qt::WFlags flags = 0)
    : QWidget(parent) {
  setSizePolicy(QSizePolicy::Minimum, QSizePolicy::Minimum);
  m_frameArea        = new QScrollArea(this);
  m_chooseLevelCombo = new QComboBox(this);
  m_frames           = new FilmstripFrames(m_frameArea);
  //----
  m_frames->m_isVertical = m_isVertical;
  m_frameArea->setObjectName("filmScrollArea");
  m_frameArea->setFrameStyle(QFrame::StyledPanel);
  setOrientation(m_isVertical);
  m_frameArea->setWidget(m_frames);
  m_chooseLevelCombo->setMaxVisibleItems(50);
  m_chooseLevelCombo->setObjectName("filmLevelCombo");
  // layout
  QVBoxLayout *mainLayout = new QVBoxLayout();
  mainLayout->setMargin(0);
  mainLayout->setSpacing(0);
  {
    mainLayout->addWidget(m_chooseLevelCombo, 0);
    mainLayout->addWidget(m_frameArea, 1);
  }
  setLayout(mainLayout);
  setFocusProxy(m_frames);
  onLevelSwitched(0);
  // signal-slot connections
  // switch the current level when the current index of m_chooseLevelCombo is
  // changed
  connect(m_chooseLevelCombo, SIGNAL(activated(int)), this,
          SLOT(onChooseLevelComboChanged(int)));
  connect(m_frames, SIGNAL(orientationToggledSignal(bool)), this,
          SLOT(orientationToggled(bool)));
  connect(m_frames, SIGNAL(comboBoxToggledSignal()), this,
          SLOT(comboBoxToggled()));
  connect(m_frames, SIGNAL(navigatorToggledSignal()), this,
          SLOT(navigatorToggled()));
  connect(m_frames, SIGNAL(levelSelectedSignal(int)), this,
          SLOT(onChooseLevelComboChanged(int)));
}
~Filmstrip()
Filmstrip::~Filmstrip ()
                      {
  for (auto level : m_levels) level->release();
  m_levels.clear();
}
Member Function Documentation
comboBoxToggled
void Filmstrip::comboBoxToggled () slot
{
  if (m_chooseLevelCombo->isHidden())
    m_chooseLevelCombo->show();
  else
    m_chooseLevelCombo->hide();
  m_showComboBox = !m_chooseLevelCombo->isHidden();
  m_frames->setComboBox(m_showComboBox);
}
hideEvent()
void Filmstrip::hideEvent (QHideEvent *) override protected
{
  TApp *app                    = TApp::instance();
  TXshLevelHandle *levelHandle = app->getCurrentLevel();
  disconnect(levelHandle, SIGNAL(xshLevelSwitched(TXshLevel *)), this,
             SLOT(onLevelSwitched(TXshLevel *)));
  disconnect(levelHandle, SIGNAL(xshLevelChanged()), this,
             SLOT(onLevelChanged()));
  disconnect(TApp::instance()->getPaletteController()->getCurrentLevelPalette(),
             SIGNAL(colorStyleChangedOnMouseRelease()), this,
             SLOT(onLevelChanged()));
  disconnect(levelHandle, SIGNAL(xshLevelTitleChanged()), this,
             SLOT(onLevelChanged()));
  disconnect(m_frameArea->verticalScrollBar(), SIGNAL(valueChanged(int)), this,
             SLOT(onSliderMoved(int)));
  TSceneHandle *sceneHandle = TApp::instance()->getCurrentScene();
  disconnect(sceneHandle, SIGNAL(sceneSwitched()), this,
             SLOT(updateChooseLevelComboItems()));
  disconnect(sceneHandle, SIGNAL(castChanged()), this,
             SLOT(updateChooseLevelComboItems()));
  disconnect(TApp::instance()->getCurrentXsheet(), SIGNAL(xsheetChanged()),
             this, SLOT(updateChooseLevelComboItems()));
  disconnect(TApp::instance()->getCurrentFrame(), SIGNAL(frameSwitched()), this,
             SLOT(onFrameSwitched()));
}
load()
void Filmstrip::load (QSettings & settings) override virtual
Implements SaveLoadQSettings.
{
  UINT orientation = settings.value("vertical", 1).toUInt();
  m_isVertical     = orientation == 1;
  setOrientation(m_isVertical);
  UINT navigator  = settings.value("navigator", 1).toUInt();
  m_showNavigator = navigator == 1;
  m_frames->setNavigator(m_showNavigator);
  UINT showCombo = settings.value("showCombo", 1).toUInt();
  m_showComboBox = showCombo == 1;
  if (showCombo == 1) {
    m_chooseLevelCombo->show();
  } else {
    m_chooseLevelCombo->hide();
  }
  m_frames->setComboBox(m_showComboBox);
}
navigatorToggled
void Filmstrip::navigatorToggled () slot
{
  m_showNavigator = !m_showNavigator;
  m_frames->setNavigator(m_showNavigator);
}
onChooseLevelComboChanged
void Filmstrip::onChooseLevelComboChanged (int index) slot
switch the current level when the current index of m_chooseLevelCombo is changed
{
  TApp *tapp = TApp::instance();
  // empty level
  if (index == m_chooseLevelCombo->findText(tr("- No Current Level -")))
    tapp->getCurrentLevel()->setLevel(0);
  else {
    std::vector<TFrameId> fids;
    m_levels[index]->getFids(fids);
    tapp->getCurrentFrame()->setFrameIds(fids);
    // retrieve to the current working frame of the level
    TFrameId WF;
    std::map<TXshSimpleLevel *, TFrameId>::iterator WFit;
    WFit = m_workingFrames.find(m_levels[index]);
    if (WFit != m_workingFrames.end())
      WF = WFit->second;
    else
      WF = fids[0];
    // this function emits xshLevelSwitched() signal and eventually calls
    // FlipConsole::UpdateRange
    // it may move the current frame so we need to keep the current frameId
    // before calling setLevel.
    tapp->getCurrentLevel()->setLevel(m_levels[index]);
    if (tapp->getCurrentSelection()->getSelection())
      tapp->getCurrentSelection()->getSelection()->selectNone();
    // move to the current working frame
    tapp->getCurrentFrame()->setFid(WF);
    QApplication::setOverrideCursor(Qt::WaitCursor);
    invalidateIcons(m_levels[index], fids);
    QApplication::restoreOverrideCursor();
  }
}
References TApp::getCurrentFrame(), TApp::getCurrentLevel(), TApp::getCurrentSelection(), and TApp::instance().
onFrameSwitched
void Filmstrip::onFrameSwitched () slot
{
  TFrameHandle *fh = TApp::instance()->getCurrentFrame();
  if (!fh->isEditingLevel()) return;
  TXshSimpleLevel *level = m_frames->getLevel();
  std::map<TXshSimpleLevel *, TFrameId>::iterator WFit;
  WFit = m_workingFrames.find(level);
  if (WFit == m_workingFrames.end()) return;
  WFit->second = fh->getFid();
  QString levelName = QString::fromStdWString(level->getName());
  if (level->getProperties()->getDirtyFlag()) levelName += " *";
  if (fh->getFid().getNumber() >= 0)
    levelName += QString("  [#") + QString::number(fh->getFid().getNumber()) +
                 QString("]");
  m_chooseLevelCombo->setItemText(m_chooseLevelCombo->currentIndex(),
                                  levelName);
}
onLevelChanged
void Filmstrip::onLevelChanged () slot
{ updateWindowTitle(); }
onLevelSwitched
void Filmstrip::onLevelSwitched (TXshLevel * oldLevel) slot
Aggiorna il "titolo" del widget e rinfresca la filmstrip se c'e' qualche "check" attivo.
{
  updateWindowTitle();
  int tc = ToonzCheck::instance()->getChecks();
  if (tc & (ToonzCheck::eInk | ToonzCheck::ePaint)) {
    TXshLevel *sl = TApp::instance()->getCurrentLevel()->getLevel();
    if (!sl) return;
    std::vector<TFrameId> fids;
    sl->getFids(fids);
    removeIcons(sl, fids, true);
  }
  update();
}
References ToonzCheck::eInk, ToonzCheck::ePaint, TApp::getCurrentLevel(), and TApp::instance().
onSliderMoved
void Filmstrip::onSliderMoved (int val) slot
{
  int oneFrameHeight = m_frames->getIconSize().height() + fs_frameSpacing +
                       fs_iconMarginTop + fs_iconMarginBottom;
  int oneFrameWidth =
      m_frames->getIconSize().width() + fs_frameSpacing + fs_iconMarginLR;
  if (m_isVertical) {
    int tmpVal =
        (int)((float)val / (float)oneFrameHeight + 0.5f) * oneFrameHeight;
    m_frameArea->verticalScrollBar()->setValue(tmpVal);
  } else {
    int tmpVal =
        (int)((float)val / (float)oneFrameWidth + 0.5f) * oneFrameWidth;
    m_frameArea->horizontalScrollBar()->setValue(tmpVal);
  }
}
orientationToggled
void Filmstrip::orientationToggled (bool isVertical) slot
{
  setOrientation(isVertical);
}
resizeEvent()
void Filmstrip::resizeEvent (QResizeEvent * e) override protected
{
  if (m_isVertical) {
    m_frames->updateContentHeight();
    m_frameArea->verticalScrollBar()->setSingleStep(
        m_frames->getOneFrameHeight());
  } else {
    m_frames->updateContentWidth();
    m_frameArea->horizontalScrollBar()->setSingleStep(
        m_frames->getOneFrameWidth());
  }
}
save()
void Filmstrip::save (QSettings & settings) const override virtual
Implements SaveLoadQSettings.
{
  UINT orientation = 0;
  orientation      = m_isVertical ? 1 : 0;
  settings.setValue("vertical", orientation);
  UINT showCombo = 0;
  showCombo      = m_chooseLevelCombo->isHidden() ? 0 : 1;
  settings.setValue("showCombo", showCombo);
  UINT navigator = 0;
  navigator      = m_showNavigator ? 1 : 0;
  settings.setValue("navigator", navigator);
}
setOrientation()
void Filmstrip::setOrientation (bool isVertical) protected
{
  m_isVertical = isVertical;
  if (isVertical) {
    m_frameArea->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
    m_frameArea->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOn);
    m_frameArea->verticalScrollBar()->setObjectName("LevelStripScrollBar");
  } else {
    m_frameArea->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOn);
    m_frameArea->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
    m_frameArea->horizontalScrollBar()->setObjectName("LevelStripScrollBar");
  }
  m_frames->setOrientation(m_isVertical);
  dynamic_cast<TPanel *>(parentWidget())->setCanFixWidth(m_isVertical);
}
showEvent()
void Filmstrip::showEvent (QShowEvent *) override protected
{
  TApp *app                    = TApp::instance();
  TXshLevelHandle *levelHandle = app->getCurrentLevel();
  bool ret = connect(levelHandle, SIGNAL(xshLevelSwitched(TXshLevel *)),
                     SLOT(onLevelSwitched(TXshLevel *)));
  ret      = ret &&
        connect(levelHandle, SIGNAL(xshLevelChanged()), SLOT(onLevelChanged()));
  // updateWindowTitle is called in the onLevelChanged
  ret = ret && connect(app->getPaletteController()->getCurrentLevelPalette(),
                       SIGNAL(colorStyleChangedOnMouseRelease()),
                       SLOT(onLevelChanged()));
  ret = ret && connect(levelHandle, SIGNAL(xshLevelTitleChanged()),
                       SLOT(onLevelChanged()));
  ret =
      ret && connect(m_frameArea->verticalScrollBar(),
                     SIGNAL(valueChanged(int)), this, SLOT(onSliderMoved(int)));
  TSceneHandle *sceneHandle = TApp::instance()->getCurrentScene();
  ret = ret && connect(sceneHandle, SIGNAL(sceneSwitched()), this,
                       SLOT(updateChooseLevelComboItems()));
  ret = ret && connect(sceneHandle, SIGNAL(castChanged()), this,
                       SLOT(updateChooseLevelComboItems()));
  ret = ret &&
        connect(TApp::instance()->getCurrentXsheet(), SIGNAL(xsheetChanged()),
                this, SLOT(updateChooseLevelComboItems()));
  ret = ret && connect(app->getCurrentFrame(), SIGNAL(frameSwitched()), this,
                       SLOT(onFrameSwitched()));
  assert(ret);
  updateChooseLevelComboItems();
  onFrameSwitched();
  onLevelSwitched(0);
}
updateChooseLevelComboItems
void Filmstrip::updateChooseLevelComboItems () slot
update combo items when the contents of scene cast are changed
{
  // clear items
  m_chooseLevelCombo->clear();
  for (auto oldLevel : m_levels) oldLevel->release();
  m_levels.clear();
  std::map<TXshSimpleLevel *, TFrameId> new_workingFrames;
  // correct and register items
  ToonzScene *scene = TApp::instance()->getCurrentScene()->getScene();
  if (scene) {
    std::vector<TXshLevel *> levels;
    scene->getLevelSet()->listLevels(levels);
    std::vector<TXshLevel *>::iterator it;
    for (it = levels.begin(); it != levels.end(); ++it) {
      // register only TLV and PLI
      TXshSimpleLevel *sl = (*it)->getSimpleLevel();
      if (sl) {
        // register only used level in xsheet
        if (!scene->getTopXsheet()->isLevelUsed(sl)) continue;
        sl->addRef();
        m_levels.push_back(sl);
        // create new m_workingFrames map with the new levelset
        TFrameId fId;
        std::map<TXshSimpleLevel *, TFrameId>::iterator WFit =
            m_workingFrames.find(sl);
        if (WFit != m_workingFrames.end())
          fId = WFit->second;
        else
          fId = sl->getFirstFid();
        new_workingFrames.insert(std::make_pair(sl, fId));
        QString levelName = QString::fromStdWString(sl->getName());
        if (sl->getProperties()->getDirtyFlag()) levelName += " *";
        // append the current working frame number to the item name
        if (fId != sl->getFirstFid() && fId.getNumber() >= 0)
          levelName +=
              QString("  [#") + QString::number(fId.getNumber()) + QString("]");
        m_chooseLevelCombo->addItem(levelName);
      }
    }
  }
  if (m_chooseLevelCombo->count() == 0)
    m_chooseLevelCombo->addItem(tr("- No Current Level -"));
  // swap the list
  m_workingFrames.clear();
  m_workingFrames = new_workingFrames;
  // synchronize the current index of combo to the current level
  updateCurrentLevelComboItem();
}
References TApp::getCurrentScene(), LevelProperties::getDirtyFlag(), TXshSimpleLevel::getFirstFid(), ToonzScene::getLevelSet(), TXshLevel::getName(), TXshSimpleLevel::getProperties(), TXshSimpleLevel::getSimpleLevel(), ToonzScene::getTopXsheet(), TApp::instance(), and TXsheet::isLevelUsed().
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/toonz/filmstrip.h
E:/opentoonz/toonz/sources/toonz/filmstrip.cpp