opentoonz: DVGui::DoubleValuePairField Class Reference
DVGui::DoubleValuePairField Class Reference
The DoubleValuePairField class provides to view an object to manage a pair of double parameter.
#include <doublepairfield.h>
Signals
void valuesChanged (bool isDragging)
Public Member Functions
DoubleValuePairField (QWidget *parent, bool isMaxRangeLimited, DoubleValueLineEdit *leftLineEdit, DoubleValueLineEdit *rightLineEdit)
void setValues (const std::pair< double, double > &values)
std::pair< double, double > getValues () const
void setLeftText (const QString &text)
void setRightText (const QString &text)
void setLabelsEnabled (bool enable)
void setRange (double minValue, double maxValue)
void getRange (double &minValue, double &maxValue)
QPixmap getHandleLeftPixmap () const
void setHandleLeftPixmap (const QPixmap &pixmap)
QPixmap getHandleRightPixmap () const
void setHandleRightPixmap (const QPixmap &pixmap)
QPixmap getHandleLeftGrayPixmap () const
void setHandleLeftGrayPixmap (const QPixmap &pixmap)
QPixmap getHandleRightGrayPixmap () const
void setHandleRightGrayPixmap (const QPixmap &pixmap)
void setLightLineColor (const QColor &color)
QColor getLightLineColor () const
void setDarkLineColor (const QColor &color)
QColor getDarkLineColor () const
void setMiddleLineColor (const QColor &color)
QColor getMiddleLineColor () const
void setLightLineEdgeColor (const QColor &color)
QColor getLightLineEdgeColor () const
Protected Slots
void onLeftEditingFinished ()
void onRightEditingFinished ()
Protected Member Functions
double pos2value (int x) const
int value2pos (double v) const
void setValue (double v)
void paintEvent (QPaintEvent *) override
void mousePressEvent (QMouseEvent *event) override
void mouseMoveEvent (QMouseEvent *event) override
void mouseReleaseEvent (QMouseEvent *event) override
void setLinearSlider (bool linear)
Protected Attributes
QPixmap m_handleLeftPixmap
QPixmap m_handleRightPixmap
QPixmap m_handleLeftGrayPixmap
QPixmap m_handleRightGrayPixmap
QColor m_lightLineColor
QColor m_darkLineColor
QColor m_middleLineColor
QColor m_lightLineEdgeColor
DoubleValueLineEdit * m_leftLineEdit
DoubleValueLineEdit * m_rightLineEdit
QLabel * m_leftLabel
QLabel * m_rightLabel
std::pair< double, double > m_values
double m_minValue
double m_maxValue
int m_grabOffset
int m_grabIndex
int m_leftMargin
int m_rightMargin
bool m_isMaxRangeLimited
bool m_isLinear
Properties
QPixmap HandleLeftPixmap
QPixmap HandleRightPixmap
QPixmap HandleLeftGrayPixmap
QPixmap HandleRightGrayPixmap
QColor LightLineColor
QColor DarkLineColor
QColor MiddleLineColor
QColor LightLineEdgeColor
Detailed Description
The DoubleValuePairField class provides to view an object to manage a pair of double parameter.
Inherits QWidget.
The object is composed of an horizontal layout QHBoxLayout which contains two pair [label, text field] and a slider with two grab, one for each double value to manage. [label, text field] are a QLabel and a DoubleLineEdit. Objects are inserted in the following order: a label and respective text field, the slider and the other pair [lebel,text field]. Object size width is not fixed, while height is equal to DVGui::WidgetHeight, 20; labels width depend from its text length, text fields has fixed size, while slider width change in according with widget size.
Objects contained in this widget are connected, so if you change one value the other automatically change, if it is necessary. You can set current value, getValues(), minimum and max value, getRange(), using setValues(), setRange().
         To know when one of two double parameter value change class
provides a signal, valuesChanged(); class emit signal when a grab slider position change or when editing text field, left or right is finished and current value is changed. Editing text field finished may occur if focus is lost or enter key is pressed. See SLOT: onLeftEditingFinished() and onRightEditingFinished().
Constructor & Destructor Documentation
DoubleValuePairField()
DoubleValuePairField::DoubleValuePairField (QWidget * parent, bool isMaxRangeLimited, DoubleValueLineEdit * leftLineEdit, DoubleValueLineEdit * rightLineEdit)
    : QWidget(parent)
    , m_values(0, 0)
    , m_minValue(0)
    , m_maxValue(100)
    , m_grabOffset(0)
    , m_grabIndex(-1)
    , m_leftMargin(72)
    , m_rightMargin(72)
    , m_isMaxRangeLimited(isMaxRangeLimited)
    , m_leftLineEdit(leftLineEdit)
    , m_rightLineEdit(rightLineEdit)
    , m_isLinear(true) {
  assert(m_leftLineEdit);
  assert(m_rightLineEdit);
  setObjectName("DoublePairField");
  setFixedHeight(WidgetHeight);
  m_leftLabel  = new QLabel("", this);
  m_rightLabel = new QLabel("", this);
  m_leftLineEdit->setFixedWidth(60);
  m_rightLineEdit->setFixedWidth(60);
  //---- layout
  QHBoxLayout *m_mainLayout = new QHBoxLayout;
  m_mainLayout->setMargin(0);
  m_mainLayout->setSpacing(3);
  {
    m_mainLayout->addWidget(m_leftLabel, 1);
    m_mainLayout->addWidget(m_leftLineEdit, 1, Qt::AlignLeft);
    m_mainLayout->addSpacing(35);
    m_mainLayout->addStretch(100);
    m_mainLayout->addWidget(m_rightLabel, 1);
    m_mainLayout->addWidget(m_rightLineEdit, 1, Qt::AlignRight);
  }
  setLayout(m_mainLayout);
  //---- signal-slot connections
  bool ret = connect(m_leftLineEdit, SIGNAL(editingFinished()),
                     SLOT(onLeftEditingFinished()));
  ret      = ret && connect(m_rightLineEdit, SIGNAL(editingFinished()),
                       SLOT(onRightEditingFinished()));
  assert(ret);
}
~DoubleValuePairField()
DVGui::DoubleValuePairField::~DoubleValuePairField () inline
{}
Member Function Documentation
getDarkLineColor()
QColor DVGui::DoubleValuePairField::getDarkLineColor () const inline
{ return m_darkLineColor; }
getHandleLeftGrayPixmap()
QPixmap DVGui::DoubleValuePairField::getHandleLeftGrayPixmap () const inline
{ return m_handleLeftGrayPixmap; }
getHandleLeftPixmap()
QPixmap DVGui::DoubleValuePairField::getHandleLeftPixmap () const inline
{ return m_handleLeftPixmap; }
getHandleRightGrayPixmap()
QPixmap DVGui::DoubleValuePairField::getHandleRightGrayPixmap () const inline
{ return m_handleRightGrayPixmap; }
getHandleRightPixmap()
QPixmap DVGui::DoubleValuePairField::getHandleRightPixmap () const inline
{ return m_handleRightPixmap; }
getLightLineColor()
QColor DVGui::DoubleValuePairField::getLightLineColor () const inline
{ return m_lightLineColor; }
getLightLineEdgeColor()
QColor DVGui::DoubleValuePairField::getLightLineEdgeColor () const inline
{ return m_lightLineEdgeColor; }
getMiddleLineColor()
QColor DVGui::DoubleValuePairField::getMiddleLineColor () const inline
{ return m_middleLineColor; }
getRange()
void DoubleValuePairField::getRange (double & minValue, double & maxValue)
Set minValue and maxValue to DoublePairField range.
{
  minValue = m_minValue;
  maxValue = m_maxValue;
}
getValues()
std::pair< double, double > DVGui::DoubleValuePairField::getValues () const inline
Return a pair containing current values.
{ return m_values; }
mouseMoveEvent()
void DoubleValuePairField::mouseMoveEvent (QMouseEvent * event) override protected
{
  if (event->buttons()) {
    std::pair<double, double> oldValues = m_values;
    int x                               = event->pos().x() + m_grabOffset;
    setValue(pos2value(x));
    if (oldValues != m_values) {
      emit valuesChanged(true);
      update();
    }
  }
}
mousePressEvent()
void DoubleValuePairField::mousePressEvent (QMouseEvent * event) override protected
{
  if (event->button() == Qt::LeftButton) {
    int x = event->pos().x();
    int cur0, cur1;
    if (m_values.first > m_maxValue)
      cur0 = value2pos(m_maxValue) - 5;
    else
      cur0 = value2pos(m_values.first);
    if (m_values.second > m_maxValue)
      cur1 = value2pos(m_maxValue);
    else
      cur1 = value2pos(m_values.second);
    int d0 = abs(cur0 - x);
    int d1 = abs(cur1 - x);
    int d, cur;
    if (d0 < d1 || (d0 == d1 && x < cur0)) {
      d           = abs(d0);
      cur         = cur0;
      m_grabIndex = 0;
    } else {
      d           = abs(d1);
      cur         = cur1;
      m_grabIndex = 1;
    }
    if (d < 6)
      m_grabOffset = cur - x;
    else {
      m_grabOffset = 0;
      setValue(pos2value(x));
      emit valuesChanged(true);
      update();
    }
  }
}
mouseReleaseEvent()
void DoubleValuePairField::mouseReleaseEvent (QMouseEvent * event) override protected
{
  m_grabOffset = 0;
  m_grabIndex  = 0;
  emit valuesChanged(false);
}
onLeftEditingFinished
void DoubleValuePairField::onLeftEditingFinished () protected slot
Set current left value to value in left text field; if necessary, if left value is greater than right, change also current right value.
This protected slot is called when text editing is finished.
Emit valuesChanged().
If current left value is equal to left text field value, return and do nothing.
{
  double value = m_leftLineEdit->getValue();
  if (value == m_values.first) return;
  if (!m_isMaxRangeLimited && value < m_minValue)
    value = m_minValue;
  else if (m_isMaxRangeLimited)
    value = tcrop(value, m_minValue, m_maxValue);
  m_values.first = value;
  if (m_values.first > m_values.second) {
    m_values.second = m_values.first;
    m_rightLineEdit->setValue(m_values.second);
  }
  emit valuesChanged(false);
  update();
}
References valuesChanged().
onRightEditingFinished
void DoubleValuePairField::onRightEditingFinished () protected slot
Set current right value to value in right text field; if necessary, if right value is lower than left, change also current left value.
This protected slot is called when text editing is finished.
Emit valuesChanged().
If current right value is equal to right text field value return and do nothing.
{
  double value = m_rightLineEdit->getValue();
  if (value == m_values.second) return;
  if (m_isMaxRangeLimited) value = tcrop(value, m_minValue, m_maxValue);
  m_values.second = value;
  if (m_values.second < m_values.first) {
    m_values.first = m_values.second;
    m_leftLineEdit->setValue(m_values.first);
  }
  emit valuesChanged(false);
  update();
}
References valuesChanged().
paintEvent()
void DoubleValuePairField::paintEvent (QPaintEvent *) override protected
{
  QPainter p(this);
  p.setBrush(Qt::NoBrush);
  int x0 = value2pos(m_minValue);
  int x1 = value2pos(m_maxValue);
  int y  = height() / 2;
  p.setPen(QPen(getDarkLineColor(), 4));
  p.drawLine(x0 - 1, y, x1, y);
  p.setPen(Qt::black);
  int y1 = height() - 1;
  int x;
  x                = value2pos(m_values.first);
  QRect sliderRect = QRect(x0, -5, x1 - x0 + 1, 10);
  if (sliderRect.contains(QPoint(x, 0)))
    p.drawPixmap(x - m_handleLeftPixmap.width() + 1, 2, m_handleLeftPixmap);
  else
    p.drawPixmap(sliderRect.right() - m_handleLeftPixmap.width() + 1, 2,
                 m_handleLeftGrayPixmap);
  x = value2pos(m_values.second);
  if (sliderRect.contains(QPoint(x, 0)))
    p.drawPixmap(x, 2, m_handleRightPixmap);
  else
    p.drawPixmap(sliderRect.right(), 2, m_handleRightGrayPixmap);
}
pos2value()
double DoubleValuePairField::pos2value (int x) const protected
Return value corresponding x position.
{
  int xMin = m_leftMargin, xMax = width() - m_rightMargin - 1;
  if (m_isLinear)
    return m_minValue + (m_maxValue - m_minValue) * (x - xMin) / (xMax - xMin);
  // nonlinear slider case
  double posRatio = (double)(x - xMin) / (double)(xMax - xMin);
  double t;
  if (posRatio <= 0.5)
    t = 0.04 * posRatio;
  else if (posRatio <= 0.75)
    t = -0.02 + 0.08 * posRatio;
  else if (posRatio <= 0.9)
    t = -0.26 + 0.4 * posRatio;
  else
    t = -8.0 + 9.0 * posRatio;
  return m_minValue + (m_maxValue - m_minValue) * t;
}
setDarkLineColor()
void DVGui::DoubleValuePairField::setDarkLineColor (const QColor & color) inline
{ m_darkLineColor = color; }
setHandleLeftGrayPixmap()
void DVGui::DoubleValuePairField::setHandleLeftGrayPixmap (const QPixmap & pixmap) inline
{
    m_handleLeftGrayPixmap = pixmap;
  }
setHandleLeftPixmap()
void DVGui::DoubleValuePairField::setHandleLeftPixmap (const QPixmap & pixmap) inline
{
    m_handleLeftPixmap = pixmap;
  }
setHandleRightGrayPixmap()
void DVGui::DoubleValuePairField::setHandleRightGrayPixmap (const QPixmap & pixmap) inline
{
    m_handleRightGrayPixmap = pixmap;
  }
setHandleRightPixmap()
void DVGui::DoubleValuePairField::setHandleRightPixmap (const QPixmap & pixmap) inline
{
    m_handleRightPixmap = pixmap;
  }
setLabelsEnabled()
void DoubleValuePairField::setLabelsEnabled (bool enable)
{
  if (!enable) {
    m_rightLabel->hide();
    m_leftLabel->hide();
  } else {
    m_rightLabel->show();
    m_leftLabel->show();
  }
}
setLeftText()
void DoubleValuePairField::setLeftText (const QString & text)
Set left label string to QString text. Recompute left margin adding label width.
{
  QString oldText = m_leftLabel->text();
  int oldLabelSize = fontMetrics().width(oldText);
  int newLabelSize = fontMetrics().width(text);
  int labelSize    = newLabelSize - oldLabelSize;
  m_leftMargin += labelSize + MARGIN_OFFSET;
  m_leftLabel->setText(text);
  update();
}
setLightLineColor()
void DVGui::DoubleValuePairField::setLightLineColor (const QColor & color) inline
{ m_lightLineColor = color; }
setLightLineEdgeColor()
void DVGui::DoubleValuePairField::setLightLineEdgeColor (const QColor & color) inline
{
    m_lightLineEdgeColor = color;
  }
setLinearSlider()
void DVGui::DoubleValuePairField::setLinearSlider (bool linear) inline protected
{ m_isLinear = linear; }
setMiddleLineColor()
void DVGui::DoubleValuePairField::setMiddleLineColor (const QColor & color) inline
{ m_middleLineColor = color; }
setRange()
void DoubleValuePairField::setRange (double minValue, double maxValue)
Set range of DoublePairField to minValue, maxValue.
{
  m_minValue = minValue;
  m_maxValue = maxValue;
  if (!m_isMaxRangeLimited) maxValue = (std::numeric_limits<int>::max)();
  m_leftLineEdit->setRange(minValue, maxValue);
  m_rightLineEdit->setRange(minValue, maxValue);
  update();
}
setRightText()
void DoubleValuePairField::setRightText (const QString & text)
Set right label string to QString text. Recompute right margin adding label width.
{
  QString oldText = m_rightLabel->text();
  int oldLabelSize = fontMetrics().width(oldText);
  int newLabelSize = fontMetrics().width(text);
  int labelSize    = newLabelSize - oldLabelSize;
  m_rightMargin += labelSize + MARGIN_OFFSET;
  m_rightLabel->setText(text);
  update();
}
setValue()
void DoubleValuePairField::setValue (double v) protected
Set current value to value. Set left or right value, or both, to value depending on current slider grab edited and value.
{
  int decimals = std::min(m_leftLineEdit->getDecimals(), 4);
  value = tround(value * std::pow(10, decimals)) * std::pow(0.1, decimals);
  value = tcrop(value, m_minValue, m_maxValue);
  if (m_grabIndex == 0)  // Left grab
  {
    m_values.first = value;
    m_leftLineEdit->setValue(m_values.first);
    if (value > m_values.second) {
      m_values.second = value;
      m_rightLineEdit->setValue(m_values.second);
    }
  } else  // Right grab
  {
    m_values.second = value;
    m_rightLineEdit->setValue(m_values.second);
    if (value < m_values.first) {
      m_values.first = value;
      m_leftLineEdit->setValue(m_values.first);
    }
  }
}
setValues()
void DoubleValuePairField::setValues (const std::pair< double, double > & values)
Set current values to values.
{
  assert(values.first <= values.second);
  m_values.first = tcrop(values.first, m_minValue, m_maxValue);
  m_leftLineEdit->setValue(m_values.first);
  m_values.second = values.second;
  if (m_isMaxRangeLimited)
    m_values.second = tcrop(values.second, m_values.first, m_maxValue);
  m_rightLineEdit->setValue(m_values.second);
  update();
}
value2pos()
int DoubleValuePairField::value2pos (double v) const protected
Return x position corresponding value.
{
  int xMin = m_leftMargin, xMax = width() - m_rightMargin - 1;
  if (m_isLinear)
    return xMin + (int)(((xMax - xMin) * (v - m_minValue)) /
                        (m_maxValue - m_minValue));
  // nonlinear slider case
  double valueRatio =
      (v - (double)m_minValue) / (double)(m_maxValue - m_minValue);
  double t;
  if (valueRatio <= 0.02)
    t = valueRatio / 0.04;
  else if (valueRatio <= 0.04)
    t = (valueRatio + 0.02) / 0.08;
  else if (valueRatio <= 0.1)
    t = (valueRatio + 0.26) / 0.4;
  else
    t = (valueRatio + 8.0) / 9.0;
  return xMin + (int)(t * (double)(xMax - xMin));
}
valuesChanged
void DVGui::DoubleValuePairField::valuesChanged (bool isDragging) signal
This signal is emitted when change one of two DoubleField value; if one slider grab position change or if one text field editing is finished.
Referenced by onLeftEditingFinished(), and onRightEditingFinished().
Member Data Documentation
m_darkLineColor
QColor DVGui::DoubleValuePairField::m_darkLineColor protected
m_grabIndex
int DVGui::DoubleValuePairField::m_grabIndex protected
m_grabOffset
int DVGui::DoubleValuePairField::m_grabOffset protected
m_handleLeftGrayPixmap
QPixmap DVGui::DoubleValuePairField::m_handleLeftGrayPixmap protected
m_handleLeftPixmap
QPixmap DVGui::DoubleValuePairField::m_handleLeftPixmap protected
m_handleRightGrayPixmap
QPixmap DVGui::DoubleValuePairField::m_handleRightGrayPixmap protected
m_handleRightPixmap
QPixmap DVGui::DoubleValuePairField::m_handleRightPixmap protected
m_isLinear
bool DVGui::DoubleValuePairField::m_isLinear protected
m_isMaxRangeLimited
bool DVGui::DoubleValuePairField::m_isMaxRangeLimited protected
m_leftLabel
QLabel* DVGui::DoubleValuePairField::m_leftLabel protected
m_leftLineEdit
DoubleValueLineEdit* DVGui::DoubleValuePairField::m_leftLineEdit protected
m_leftMargin
int DVGui::DoubleValuePairField::m_leftMargin protected
m_lightLineColor
QColor DVGui::DoubleValuePairField::m_lightLineColor protected
m_lightLineEdgeColor
QColor DVGui::DoubleValuePairField::m_lightLineEdgeColor protected
m_maxValue
double DVGui::DoubleValuePairField::m_maxValue protected
m_middleLineColor
QColor DVGui::DoubleValuePairField::m_middleLineColor protected
m_minValue
double DVGui::DoubleValuePairField::m_minValue protected
m_rightLabel
QLabel * DVGui::DoubleValuePairField::m_rightLabel protected
m_rightLineEdit
DoubleValueLineEdit* DVGui::DoubleValuePairField::m_rightLineEdit protected
m_rightMargin
int DVGui::DoubleValuePairField::m_rightMargin protected
m_values
std::pair<double, double> DVGui::DoubleValuePairField::m_values protected
Property Documentation
DarkLineColor
QColor DVGui::DoubleValuePairField::DarkLineColor read write
HandleLeftGrayPixmap
QPixmap DVGui::DoubleValuePairField::HandleLeftGrayPixmap read
HandleLeftPixmap
QPixmap DVGui::DoubleValuePairField::HandleLeftPixmap read
HandleRightGrayPixmap
QPixmap DVGui::DoubleValuePairField::HandleRightGrayPixmap read
HandleRightPixmap
QPixmap DVGui::DoubleValuePairField::HandleRightPixmap read
LightLineColor
QColor DVGui::DoubleValuePairField::LightLineColor read write
LightLineEdgeColor
QColor DVGui::DoubleValuePairField::LightLineEdgeColor read
MiddleLineColor
QColor DVGui::DoubleValuePairField::MiddleLineColor read write
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/toonzqt/doublepairfield.h
E:/opentoonz/toonz/sources/toonzqt/doublepairfield.cpp