opentoonz: TCellKeyframeSelection Class Reference
TCellKeyframeSelection Class Reference final
Public Member Functions
TCellKeyframeSelection (TCellSelection *cellSelection, TKeyframeSelection *keyframeSelection)
TCellSelection * getCellSelection ()
TKeyframeSelection * getKeyframeSelection ()
void setXsheetHandle (TXsheetHandle *xsheetHandle)
void enableCommands () override
bool isEmpty () const override
void copyCellsKeyframes ()
void pasteCellsKeyframes ()
void deleteCellsKeyframes ()
void cutCellsKeyframes ()
void selectCellsKeyframes (int r0, int c0, int r1, int c1)
void selectCellKeyframe (int row, int col)
void selectNone () override
Public Member Functions inherited from TSelection
virtual void enableCommands ()
void enableCommand (CommandId cmdId, CommandHandlerInterface *handler)
template<class T >
void enableCommand (T *target, CommandId cmdId, void(T::*method)())
template<class T , typename R >
void enableCommand (T *target, CommandId cmdId, void(T::*method)(R), R value)
void makeCurrent ()
void makeNotCurrent ()
virtual bool isEmpty () const =0
virtual void selectNone ()=0
virtual bool addMenuActions (QMenu *menu)
void addMenuAction (QMenu *menu, CommandId cmdId)
void setView (View *view)
View * getView () const
void notifyView ()
Additional Inherited Members
Static Public Member Functions inherited from TSelection
static TSelection * getCurrent ()
static void setCurrent (TSelection *selection)
Detailed Description
Constructor & Destructor Documentation
TCellKeyframeSelection()
TCellKeyframeSelection::TCellKeyframeSelection (TCellSelection * cellSelection, TKeyframeSelection * keyframeSelection)
    : m_cellSelection(cellSelection)
    , m_keyframeSelection(keyframeSelection)
    , m_xsheetHandle(0) {}
~TCellKeyframeSelection()
TCellKeyframeSelection::~TCellKeyframeSelection ()
{
  delete m_cellSelection;
  delete m_keyframeSelection;
}
Member Function Documentation
copyCellsKeyframes()
void TCellKeyframeSelection::copyCellsKeyframes ()
{
  TCellKeyframeData *data = new TCellKeyframeData();
  // Copy cells
  int r0, c0, r1, c1;
  m_cellSelection->getSelectedCells(r0, c0, r1, c1);
  if (!isEmpty()) {
    int colCount = c1 - c0 + 1;
    int rowCount = r1 - r0 + 1;
    if (colCount <= 0 || rowCount <= 0) return;
    TXsheet *xsh        = m_xsheetHandle->getXsheet();
    TCellData *cellData = new TCellData();
    cellData->setCells(xsh, r0, c0, r1, c1);
    data->setCellData(cellData);
  }
  // Copy keyframes
  if (!isEmpty()) {
    QClipboard *clipboard       = QApplication::clipboard();
    TXsheet *xsh                = m_xsheetHandle->getXsheet();
    TKeyframeData *keyframeData = new TKeyframeData();
    TKeyframeData::Position startPos(r0, c0);
    keyframeData->setKeyframes(m_keyframeSelection->getSelection(), xsh,
                               startPos);
    data->setKeyframeData(keyframeData);
  }
  // Set the clipboard
  QClipboard *clipboard = QApplication::clipboard();
  clipboard->setMimeData(data, QClipboard::Clipboard);
}
cutCellsKeyframes()
void TCellKeyframeSelection::cutCellsKeyframes ()
{
  copyCellsKeyframes();
  TUndoManager::manager()->beginBlock();
  int r0, r1, c0, c1;
  m_cellSelection->getSelectedCells(r0, c0, r1, c1);
  m_cellSelection->cutCells(true);
  m_keyframeSelection->deleteKeyframesWithShift(r0, r1, c0, c1);
  TUndoManager::manager()->endBlock();
}
deleteCellsKeyframes()
void TCellKeyframeSelection::deleteCellsKeyframes ()
{
  TUndoManager::manager()->beginBlock();
  m_cellSelection->deleteCells();
  m_keyframeSelection->deleteKeyframes();
  TUndoManager::manager()->endBlock();
}
enableCommands()
void TCellKeyframeSelection::enableCommands () override virtual
Reimplemented from TSelection.
{
  enableCommand(this, MI_Copy, &TCellKeyframeSelection::copyCellsKeyframes);
  enableCommand(this, MI_Paste, &TCellKeyframeSelection::pasteCellsKeyframes);
  enableCommand(this, MI_Cut, &TCellKeyframeSelection::cutCellsKeyframes);
  enableCommand(this, MI_Clear, &TCellKeyframeSelection::deleteCellsKeyframes);
}
getCellSelection()
TCellSelection * TCellKeyframeSelection::getCellSelection () inline
{ return m_cellSelection; }
getKeyframeSelection()
TKeyframeSelection * TCellKeyframeSelection::getKeyframeSelection () inline
{ return m_keyframeSelection; }
isEmpty()
bool TCellKeyframeSelection::isEmpty () const override virtual
Implements TSelection.
{
  return m_keyframeSelection->isEmpty() && m_cellSelection->isEmpty();
}
pasteCellsKeyframes()
void TCellKeyframeSelection::pasteCellsKeyframes ()
{
  m_cellSelection->pasteCells();
}
selectCellKeyframe()
void TCellKeyframeSelection::selectCellKeyframe (int row, int col)
{
  m_cellSelection->selectCell(row, col);
  TXsheet *xsh = m_xsheetHandle->getXsheet();
  TStageObjectId id =
      col < 0 ? TStageObjectId::CameraId(xsh->getCameraColumnIndex())
              : TStageObjectId::ColumnId(col);
  TStageObject *stObj = xsh->getStageObject(id);
  m_keyframeSelection->clear();
  if (stObj->isKeyframe(row)) m_keyframeSelection->select(row, col);
}
selectCellsKeyframes()
void TCellKeyframeSelection::selectCellsKeyframes (int r0, int c0, int r1, int c1)
Note
: puo' anche essere r0>r1 o c0>c1
{
  m_cellSelection->selectCells(r0, c0, r1, c1);
  TXsheet *xsh = m_xsheetHandle->getXsheet();
  m_xsheetHandle->getXsheet();
  if (r1 < r0) std::swap(r0, r1);
  if (c1 < c0) std::swap(c0, c1);
  m_keyframeSelection->clear();
  int r, c;
  for (c = c0; c <= c1; c++)
    for (r = r0; r <= r1; r++) {
      TStageObjectId id =
          c < 0 ? TStageObjectId::CameraId(xsh->getCameraColumnIndex())
                : TStageObjectId::ColumnId(c);
      TStageObject *stObj = xsh->getStageObject(id);
      if (stObj->isKeyframe(r)) m_keyframeSelection->select(r, c);
    }
}
References TXsheet::getStageObject(), TStageObject::isKeyframe(), and TCellSelection::selectCells().
selectNone()
void TCellKeyframeSelection::selectNone () override virtual
Implements TSelection.
{
  m_cellSelection->selectNone();
  m_keyframeSelection->selectNone();
}
setXsheetHandle()
void TCellKeyframeSelection::setXsheetHandle (TXsheetHandle * xsheetHandle) inline
{
    m_xsheetHandle = xsheetHandle;
  }
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/toonz/cellkeyframeselection.h
E:/opentoonz/toonz/sources/toonz/cellkeyframeselection.cpp