opentoonz: TToonzImage Class Reference
TToonzImage Class Reference final
An image containing a Toonz raster.
#include <ttoonzimage.h>
Public Member Functions
TToonzImage (const TRasterCM32P &raster, const TRect &saveBox)
TImage::Type getType () const override
Return the type of the image.
TDimension getSize () const
Return the size of the Image.
void getDpi (double &dpix, double &dpiy) const
Get the dpi values of the image for x and y axes.
void setDpi (double dpix, double dpiy)
Set the dpi values of the image for x and y axes.
int getSubsampling () const
void setSubsampling (int s)
TRect getSavebox () const
Return the savebox of the image.
void setSavebox (const TRect &rect)
Set the savebox of the image.
TRectD getBBox () const override
Return the bounding box of the image.
TPoint getOffset () const
Return the offset point of the image.
void setOffset (const TPoint &offset)
Set the offset point of the image.
TImage * cloneImage () const override
Return raster hPos m_hPos.
TRasterCM32P getCMapped () const
Return the image's raster.
void getCMapped (const TRasterCM32P &ras)
Return a copy of the image's raster.
void setCMapped (const TRasterCM32P &ras)
Set the image's raster.
TRasterCM32P getRaster () const
Return the image's raster.
TRasterP raster () const override
TToonzImageP clone () const
Return a clone of the current image.
Public Member Functions inherited from TImage
TImage ()
virtual Type getType () const =0
virtual TRectD getBBox () const =0
virtual TImage * cloneImage () const =0
virtual TRasterP raster () const
TPalette * getPalette () const
virtual void setPalette (TPalette *palette)
Public Member Functions inherited from TSmartObject
TSmartObject (ClassCode classCode)
void addRef ()
void release ()
TINT32 getRefCount () const
Additional Inherited Members
Public Types inherited from TImage
enum Type {
NONE = 0 , RASTER = 1 , VECTOR = 2 , TOONZ_RASTER = 3 ,
MESH = 4
}
Public Types inherited from TSmartObject
typedef short ClassCode
Static Public Member Functions inherited from TSmartObject
static TINT32 getInstanceCount (ClassCode code)
Detailed Description
An image containing a Toonz raster.
Constructor & Destructor Documentation
TToonzImage() [1/2]
TToonzImage::TToonzImage ()
    : m_ras()
    , m_dpix(0)
    , m_dpiy(0)
    , m_subsampling(1)
    , m_name("")
    , m_savebox()
    //, m_hPos(0.0)
    , m_offset(0, 0)
    , m_size() {}
TToonzImage() [2/2]
TToonzImage::TToonzImage (const TRasterCM32P & raster, const TRect & saveBox)
    : m_ras(ras)
    , m_size(ras->getSize())
    , m_dpix(0)
    , m_dpiy(0)
    , m_subsampling(1)
    , m_name("")
    , m_savebox(saveBox)
    //, m_hPos(0.0)
    , m_offset(0, 0) {
  assert(ras->getBounds().contains(saveBox));
}
~TToonzImage()
TToonzImage::~TToonzImage ()
{}
Member Function Documentation
clone()
TToonzImageP TToonzImage::clone () const
Return a clone of the current image.
{ return TToonzImageP(cloneImage()); }
References cloneImage().
cloneImage()
TImage * TToonzImage::cloneImage () const override virtual
Return raster hPos m_hPos.
Return a clone of image Return a clone of the current image
Implements TImage.
{ return new TToonzImage(*this); }
Referenced by clone().
getBBox()
TRectD TToonzImage::getBBox () const inline override virtual
Return the bounding box of the image.
Implements TImage.
{ return convert(m_savebox); }
getCMapped() [1/2]
TRasterCM32P TToonzImage::getCMapped () const
Return the image's raster.
{
  /*
if (readOnly)
{
{
QMutexLocker sl(m_mutex);
if (m_ras)
  return m_ras->clone();
}
return decompress();
}
else
*/
  {
    // QMutexLocker sl(&m_mutex);
    return m_ras;
  }
}
getCMapped() [2/2]
void TToonzImage::getCMapped (const TRasterCM32P & ras)
Return a copy of the image's raster.
{
  assert(ras && ras->getSize() == m_size);
  QMutexLocker sl(&m_mutex);
  if (m_ras) ras->copy(m_ras);
  /*
else
decompress(ras);
*/
}
getDpi()
void TToonzImage::getDpi (double & dpix, double & dpiy) const inline
Get the dpi values of the image for x and y axes.
{
    dpix = m_dpix;
    dpiy = m_dpiy;
  }
getOffset()
TPoint TToonzImage::getOffset () const inline
Return the offset point of the image.
{ return m_offset; }
getRaster()
TRasterCM32P TToonzImage::getRaster () const inline
Return the image's raster.
Call the getCMapped() method.
{ return getCMapped(); }
Referenced by Stage::RasterPainter::onToonzImage().
getSavebox()
TRect TToonzImage::getSavebox () const inline
Return the savebox of the image.
{ return m_savebox; }
Referenced by Stage::RasterPainter::onToonzImage().
getSize()
TDimension TToonzImage::getSize () const inline
Return the size of the Image.
{ return m_size; }
getSubsampling()
int TToonzImage::getSubsampling () const inline
{ return m_subsampling; }
getType()
TImage::Type TToonzImage::getType () const inline override virtual
Return the type of the image.
Implements TImage.
{ return TImage::TOONZ_RASTER; }
References TImage::TOONZ_RASTER.
raster()
TRasterP TToonzImage::raster () const inline override virtual
 Returns a pointer to the palette associated to this image. A palette
is a limited set of colors, identified by indexes and composed by a combination of primitive colors, i.e. RGB color.
Reimplemented from TImage.
{ return (TRasterP)getCMapped(); }
setCMapped()
void TToonzImage::setCMapped (const TRasterCM32P & ras)
Set the image's raster.
{
  QMutexLocker sl(&m_mutex);
  m_ras     = ras;
  m_size    = ras->getSize();
  m_savebox = ras->getBounds();
  // delete [] m_compressedBuffer;
  // m_compressedBuffer = 0;
  // m_compressedBufferSize = 0;
}
setDpi()
void TToonzImage::setDpi (double dpix, double dpiy) inline
Set the dpi values of the image for x and y axes.
{
    m_dpix = dpix;
    m_dpiy = dpiy;
  }
setOffset()
void TToonzImage::setOffset (const TPoint & offset) inline
Set the offset point of the image.
{ m_offset = offset; }
setSavebox()
void TToonzImage::setSavebox (const TRect & rect)
Set the savebox of the image.
The set savebox is the intersection between rect and the image box.
{
  QMutexLocker sl(&m_mutex);
  // assert(m_lockCount>0);
  assert(m_ras);
  m_savebox = TRect(m_size) * rect;
  assert(TRect(m_size).contains(m_savebox));
}
setSubsampling()
void TToonzImage::setSubsampling (int s)
{ m_subsampling = s; }
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/ttoonzimage.h
E:/opentoonz/toonz/sources/common/ttoonzimage/ttonzimage.cpp