opentoonz: CleanupSettingsModel Class Reference
CleanupSettingsModel Class Reference final
#include <cleanupsettingsmodel.h>
Public Types
enum { LISTENER = 0x1 , PREVIEWER = 0x2 , CAMERATEST = 0x4 }
enum CommitMask { NONE = 0 , INTERFACE , POSTPROCESS , FULLPROCESS }
Public Slots
void commitChanges ()
void promptSave ()
Prompts to save current settings.
void promptLoad ()
Prompts to load settings.
void restoreGlobalSettings ()
Signals
void modelChanged (bool needsPostProcess)
void imageSwitched ()
Emitted every time the cleanup focus switches to a new image.
void previewDataChanged ()
void clnLoaded ()
Public Member Functions
CleanupParameters * getCurrentParameters ()
void getCleanupFrame (TXshSimpleLevel *&sl, TFrameId &fid)
const TFilePath & clnPath () const
void attach (int objectFlag, bool doPreview=true)
void detach (int objectFlag)
void getPreviewData (TRasterImageP &original, TRasterImageP &transformed, TAffine &transform)
void getCameraTestData (TRasterImageP &original, TRasterImageP &transformed)
void setCommitMask (CommitMask allowedProcessing)
void saveSettings (const TFilePath &clnPath)
bool loadSettings (const TFilePath &clnPath)
bool saveSettingsIfNeeded ()
Static Public Member Functions
static CleanupSettingsModel * instance ()
static TFilePath getInputPath (TXshSimpleLevel *sl)
static TFilePath getOutputPath (TXshSimpleLevel *sl, const CleanupParameters *params)
static TFilePath getClnPath (TXshSimpleLevel *sl)
static void saveSettings (CleanupParameters *params, const TFilePath &clnPath)
cln file.
static bool loadSettings (CleanupParameters *params, const TFilePath &clnPath)
Detailed Description
The CleanupSettingsModel is the class responsible for concrete management of cleanup settings in Toonz.
In Toonz, the interface to cleanup settings follows the model/view architecture, where each Cleanup Settings panel is a view to a singleton model of this class.
The CleanupSettingsModel is responsible for handling signals that involve cleanup changes, such as user changes in the parameters coming from views, settings reset or switches from commands, and so on.
A cleanup operation is roughly split in 2 parts: main processing and post-processing.
The main processing part takes the full original image and applies geometric transforms and other full-image analysis and processing. This is typically slow, and is thus performed by this class once for all views.
Post-processing performs further local or pixel-per-pixel adjustments that are sufficiently fast to be carried out by single views on their preview area. This includes colors recognition, colors adjustment, despeckling <\I> and antialiasing-related effects.
Note
This class also acts as a wrapper to CleanupParameters' palette, attaching to the "current cleanup palette handle" accessible through the TPaletteController.
Member Enumeration Documentation
anonymous enum
anonymous enum
{ LISTENER = 0x1, PREVIEWER = 0x2, CAMERATEST = 0x4 };
CommitMask
enum CleanupSettingsModel::CommitMask
{ NONE = 0, INTERFACE, POSTPROCESS, FULLPROCESS };
Constructor & Destructor Documentation
CleanupSettingsModel()
CleanupSettingsModel::CleanupSettingsModel ()
    : m_listenersCount(0)
    , m_previewersCount(0)
    , m_cameraTestsCount(0)
    , m_allowedActions(FULLPROCESS)
    , m_action(NONE)
    , m_c(-1)
    , m_sl(0) {
  CleanupParameters *currentParams = getCurrentParameters();
  // Don't clone the palette. Palette changes are tracked through
  // palette handle signals.
  m_backupParams.assign(currentParams, false);
  TSceneHandle *sceneHandle = TApp::instance()->getCurrentScene();
  bool ret = true;
  ret      = ret &&
        connect(sceneHandle, SIGNAL(sceneSwitched()), SLOT(onSceneSwitched()));
  assert(ret);
  onSceneSwitched();
}
~CleanupSettingsModel()
CleanupSettingsModel::~CleanupSettingsModel ()
{}
Member Function Documentation
attach()
void CleanupSettingsModel::attach (int objectFlag, bool doPreview = true)
Attaches an object to the model. It is not necessary to supply the object itself, but a description of its role is required. The object could be any combination of the LISTENER, PREVIEWER or CAMERATEST flags. The role information is used to activate centralized preview or camera test processing.
{
  if ((objectFlag & LISTENER) && (m_listenersCount++ <= 0)) connectSignals();
  bool doRebuild = false;
  if ((objectFlag & PREVIEWER) && (m_previewersCount++ <= 0)) doRebuild = true;
  if ((objectFlag & CAMERATEST) && (m_cameraTestsCount++ <= 0))
    doRebuild = true;
  if (doRebuild && doPreview) rebuildPreview();
}
clnLoaded
void CleanupSettingsModel::clnLoaded () signal
Emitted when the model loads (or unloads) a cln settings file. It is also invoked when a cln is saved, since saving should put us in the same situation we have after a cln has been loaded.
Referenced by restoreGlobalSettings().
clnPath()
const TFilePath & CleanupSettingsModel::clnPath () const inline
{ return m_clnPath; }
commitChanges
void CleanupSettingsModel::commitChanges () slot
Informs the model that current settings have changed. Settings analysis and cleanup refreshes ensue. The modelChanged() signal is then emitted to inform connected views of said change.
{
  CleanupParameters *currentParams = getCurrentParameters();
  int action = NONE;
  // Analyze param changes
  {
    // Check for simple changes
    if (currentParams->m_path != m_backupParams.m_path) action = INTERFACE;
    // Check post-processing-related changes
    if (currentParams->m_transparencyCheckEnabled !=
            m_backupParams.m_transparencyCheckEnabled ||
        currentParams->m_noAntialias != m_backupParams.m_noAntialias ||
        currentParams->m_postAntialias != m_backupParams.m_postAntialias ||
        currentParams->m_despeckling != m_backupParams.m_despeckling ||
        currentParams->m_aaValue != m_backupParams.m_aaValue)
      action = POSTPROCESS;
    // Check for full preview rebuilds
    if (currentParams->m_lineProcessingMode !=
            m_backupParams.m_lineProcessingMode ||
        currentParams->m_autocenterType != m_backupParams.m_autocenterType ||
        currentParams->m_autoAdjustMode != m_backupParams.m_autoAdjustMode ||
        currentParams->m_camera.getRes() != m_backupParams.m_camera.getRes() ||
        currentParams->m_camera.getSize() !=
            m_backupParams.m_camera.getSize() ||
        currentParams->m_rotate != m_backupParams.m_rotate ||
        currentParams->m_flipx != m_backupParams.m_flipx ||
        currentParams->m_flipy != m_backupParams.m_flipy ||
        currentParams->m_offx != m_backupParams.m_offx ||
        currentParams->m_offy != m_backupParams.m_offy ||
        currentParams->m_sharpness != m_backupParams.m_sharpness ||
        currentParams->m_closestField != m_backupParams.m_closestField)
      action = FULLPROCESS;
    if (currentParams->m_autocenterType != CleanupTypes::AUTOCENTER_NONE) {
      // Check Autocenter changes
      if (!(currentParams->getFdgInfo() == m_backupParams.getFdgInfo()) ||
          currentParams->m_pegSide != m_backupParams.m_pegSide)
        action = FULLPROCESS;
    }
  }
  commitChanges(action);
}
References commitChanges(), TCamera::getRes(), and TCamera::getSize().
Referenced by commitChanges(), and setCommitMask().
detach()
void CleanupSettingsModel::detach (int objectFlag)
The inverse of attach(), it's used to deactivate the specified role activities when no more attached objects to that role remain.
{
  if ((objectFlag & LISTENER) && (--m_listenersCount <= 0)) disconnectSignals();
  if ((objectFlag & PREVIEWER) && (--m_previewersCount <= 0)) {
    m_previewTransformed = TRasterImageP();
    m_transform          = TAffine();
  }
  if ((objectFlag & CAMERATEST) && (--m_cameraTestsCount <= 0))
    m_cameraTestTransformed = TRasterImageP();
  assert(m_listenersCount >= 0);
  assert(m_previewersCount >= 0);
  assert(m_cameraTestsCount >= 0);
}
getCameraTestData()
void CleanupSettingsModel::getCameraTestData (TRasterImageP & original, TRasterImageP & transformed) inline
Returns the interesting info about a camera test process. This includes both the original and affine-transformed image.
{
    original    = m_original;
    transformed = m_cameraTestTransformed;
  }
getCleanupFrame()
void CleanupSettingsModel::getCleanupFrame (TXshSimpleLevel *& sl, TFrameId & fid)
{
  TApp *app = TApp::instance();
  int r = app->getCurrentFrame()->getFrame();
  int c = app->getCurrentColumn()->getColumnIndex();
  TXsheet *xsh = app->getCurrentXsheet()->getXsheet();
  assert(xsh);
  const TXshCell &cell = xsh->getCell(r, c);
  fid = cell.getFrameId();
  sl  = cell.isEmpty() ? 0 : cell.getSimpleLevel();
}
getClnPath()
TFilePath CleanupSettingsModel::getClnPath (TXshSimpleLevel * sl) static
encoded output cleanup path for the specified level. Returns the decoded path for the level's
{
  if (!sl) return TFilePath();
  TFilePath clnPath(sl->getScannedPath());
  if (clnPath == TFilePath()) clnPath = sl->getPath();
  ToonzScene *scene = TApp::instance()->getCurrentScene()->getScene();
  return scene->decodeFilePath(clnPath).withNoFrame().withType("cln");
}
References ToonzScene::decodeFilePath(), TApp::getCurrentScene(), TXshSimpleLevel::getPath(), TApp::instance(), and TFilePath::withType().
Referenced by promptLoad(), and promptSave().
getCurrentParameters()
CleanupParameters * CleanupSettingsModel::getCurrentParameters ()
{
  ToonzScene *scene = TApp::instance()->getCurrentScene()->getScene();
  return scene ? scene->getProperties()->getCleanupParameters() : 0;
}
getInputPath()
TFilePath CleanupSettingsModel::getInputPath (TXshSimpleLevel * sl) static
Returns the encoded input cleanup
{
  const TFilePath &scannedPath = sl->getScannedPath();
  return scannedPath.isEmpty() ? sl->getPath() : scannedPath;
}
References TXshSimpleLevel::getPath().
Referenced by getOutputPath().
getOutputPath()
TFilePath CleanupSettingsModel::getOutputPath (TXshSimpleLevel * sl, const CleanupParameters * params) static
path for the specified level. Returns the
{
  const TFilePath &inPath = getInputPath(sl);  // Used just to get level name
  if (inPath.isEmpty() || !params) return TFilePath();
  bool lineProcessing = (params->m_lineProcessingMode != lpNone);
  ToonzScene *scene   = TApp::instance()->getCurrentScene()->getScene();
  // Check if the cleaned up level already exists
  const TFilePath &outDir = params->getPath(scene);
  return lineProcessing ? (outDir + inPath.getWideName()).withType("tlv")
                        : (outDir + inPath.getLevelNameW())
                              .withType(params->m_lpNoneFormat);
}
References TApp::getCurrentScene(), getInputPath(), and TApp::instance().
getPreviewData()
void CleanupSettingsModel::getPreviewData (TRasterImageP & original, TRasterImageP & transformed, TAffine & transform) inline
Returns the interesting info about a cleanup preview process. Specifically, we have both the original and affine-transformed images, and the applied transform.
{
    original    = m_original;
    transformed = m_previewTransformed;
    transform   = m_transform;
  }
instance()
CleanupSettingsModel * CleanupSettingsModel::instance () static
{
  static CleanupSettingsModel theInstance;
  return &theInstance;
}
loadSettings() [1/2]
bool CleanupSettingsModel::loadSettings (CleanupParameters * params, const TFilePath & clnPath) static
{
  assert(params);
  if (clnPath.isEmpty() || !TSystem::doesExistFileOrLevel(clnPath))
    return false;
  TIStream *is = new TIStream(clnPath);
  CleanupParameters defaultParameters;
  params->assign(&defaultParameters);
  std::string tagName;
  is->matchTag(tagName);
  if (tagName == "version") {
    int minor, major;
    *is >> major >> minor;
    is->matchEndTag();
    is->setVersion(VersionNumber(major, minor));
  } else {
    delete is;
    is = new TIStream(clnPath);
  }
  params->loadData(*is, false);
  delete is;
  return true;
}
loadSettings() [2/2]
bool CleanupSettingsModel::loadSettings (const TFilePath & clnPath)
{
  CleanupParameters *cp = getCurrentParameters();
  if (!loadSettings(cp, clnPath)) return false;
  // The same as restoreGlobalSettings()
  TApp::instance()
      ->getPaletteController()
      ->getCurrentCleanupPalette()
      ->setPalette(cp->m_cleanupPalette.getPointer());
  /*---
   * LoadSettingsPopupGlobal---*/
  if (m_clnPath.isEmpty()) {
    TApp::instance()->getCurrentScene()->setDirtyFlag(
        true);  // This should be moved outside... sadly not supported at the
                // moment...
    CleanupParameters::GlobalParameters.assign(
        cp);  // The global settings are being changed
  }
  m_backupParams.assign(cp, false);
  if (m_previewersCount > 0 || m_cameraTestsCount > 0) rebuildPreview();
  emit modelChanged(false);
  emit clnLoaded();
  return true;
}
modelChanged
void CleanupSettingsModel::modelChanged (bool needsPostProcess) signal
Emitted whenever the model has finished processing a cleanup settings change. This happens after an explicit commitChange() has been invoked from a view, or other command-related settings change occur.
Referenced by restoreGlobalSettings().
previewDataChanged
void CleanupSettingsModel::previewDataChanged () signal
Emitted when the data retrievable with getPreviewData() and getCameraTestData() have been updated.
promptLoad
void CleanupSettingsModel::promptLoad () slot
Prompts to load settings.
{
  static LoadSettingsPopup *loadPopup = 0;
  if (!loadPopup) loadPopup = new LoadSettingsPopup;
  loadPopup->setPath(getClnPath(m_sl));
  loadPopup->exec();
}
References getClnPath().
promptSave
void CleanupSettingsModel::promptSave () slot
Prompts to save current settings.
{
  static SaveSettingsPopup *savePopup = 0;
  if (!savePopup) savePopup = new SaveSettingsPopup;
  savePopup->setPath(getClnPath(m_sl));
  savePopup->exec();
}
References getClnPath().
Referenced by saveSettingsIfNeeded().
restoreGlobalSettings
void CleanupSettingsModel::restoreGlobalSettings () slot
Reloads the project's cleanup settings (no prompts)
{
  CleanupParameters *currentParams = getCurrentParameters();
  currentParams->assign(&CleanupParameters::GlobalParameters);
  // Make sure that the current cleanup palette is set to currentParams' palette
  TApp::instance()
      ->getPaletteController()
      ->getCurrentCleanupPalette()
      ->setPalette(currentParams->m_cleanupPalette.getPointer());
  m_clnPath = TFilePath();
  m_backupParams.assign(currentParams, false);
  if (m_previewersCount > 0 || m_cameraTestsCount > 0) rebuildPreview();
  emit modelChanged(false);
  emit clnLoaded();
}
References clnLoaded(), TApp::instance(), and modelChanged().
saveSettings() [1/2]
void CleanupSettingsModel::saveSettings (CleanupParameters * params, const TFilePath & clnPath) static
cln file.
{
  if (clnPath.isEmpty() || !params) return;
  TOStream os(clnPath);
  os.openChild("version");
  os << 1 << 19;
  os.closeChild();
  params->saveData(os);
  params->setDirtyFlag(false);
}
References TOStream::closeChild(), and TOStream::openChild().
saveSettings() [2/2]
void CleanupSettingsModel::saveSettings (const TFilePath & clnPath)
{
  saveSettings(getCurrentParameters(), clnPath);
  // Saving current settings should put the model in the same situation we
  // have after a model is loaded (ie see loadSettings(clnPath))
  m_clnPath = clnPath;
  emit clnLoaded();
}
saveSettingsIfNeeded()
bool CleanupSettingsModel::saveSettingsIfNeeded ()
Prompts to save current settings in case they have been modified. Returns false if the user decided to keep the settings and stop (cancel) any action affecting them.
{
  CleanupParameters *params = getCurrentParameters();
  if (params->getDirtyFlag() && !m_clnPath.isEmpty() &&
      TFileStatus(m_clnPath).doesExist()) {
    QString question(
        QObject::tr("The cleanup settings for the current level have been "
                    "modified...\n\nDo you want to save your changes?"));
    int ret = DVGui::MsgBox(question, QObject::tr("Save"),
                            QObject::tr("Discard"), QObject::tr("Cancel"), 0);
    if (ret == 1) {
      // WARNING: This is legacy behavior, but is it really needed? I think
      // there should be no further
      // request of user interaction - why invoking the popup to choose the save
      // path?
      promptSave();
    } else if (ret == 3)
      return false;
  }
  return true;
}
References promptSave().
setCommitMask()
void CleanupSettingsModel::setCommitMask (CommitMask allowedProcessing)
Specifies the model behavior upon a cleanup parameters change commit. Once the model receives a commitChanges() notification, it tracks the changed parameters and decides how deep the image under cleanup focus must be re-processed to stick to the changes. The commit mask can be specified to force the model to limit the performed cleanup up to the specified stage. This is especially useful in case a parameter changes frequently enough that only the last of a long sequence of updates should be processed (e.g. when dragging a parameter slider).
{
  m_allowedActions = allowedProcessing;
  commitChanges();
}
References commitChanges().
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/toonz/cleanupsettingsmodel.h
E:/opentoonz/toonz/sources/toonz/cleanupsettingsmodel.cpp