opentoonz: VectorSelectionTool Class Reference
VectorSelectionTool Class Reference final
Selection tool for Toonz's vector images.
#include <vectorselectiontool.h>
Public Member Functions
VectorSelectionTool (int targetType)
void setNewFreeDeformer () override
void setCanEnterGroup (bool value)
bool isConstantThickness () const override
bool isLevelType () const override
bool isSelectedFramesType () const override
bool isSameStyleType () const override
bool isModifiableSelectionType () const override
const std::set< int > & selectedStyles () const
std::set< int > & selectedStyles ()
int getSelectionCount () const
void selectionOutlineStyle (int &capStyle, int &joinStyle)
const StrokeSelection & strokeSelection () const
const LevelSelection & levelSelection () const
TSelection * getSelection () override
Returns a pointer to the tool selection.
bool isSelectionEmpty () override
void computeBBox () override
TPropertyGroup * getProperties (int targetType) override
void setResetCenter (bool update)
bool canResetCenter ()
bool isSelectionEditable () override
Public Member Functions inherited from SelectionTool
SelectionTool (int targetType)
ToolType getToolType () const override
TPointD getCenter (int index=0) const
void setCenter (const TPointD &center, int index=0)
int getBBoxsCount () const
DragSelectionTool::FourPoints getBBox (int index=0) const
virtual void setBBox (const DragSelectionTool::FourPoints &points, int index=0)
FreeDeformer * getFreeDeformer (int index=0) const
virtual void setNewFreeDeformer ()=0
void clearDeformers ()
int getSelectedPoint () const
virtual bool isConstantThickness () const
virtual bool isLevelType () const
virtual bool isSelectedFramesType () const
virtual bool isSameStyleType () const
virtual bool isModifiableSelectionType () const
virtual bool isFloating () const
virtual QSet< int > getSelectedStyles () const
void leftButtonDown (const TPointD &pos, const TMouseEvent &) override
void leftButtonDrag (const TPointD &pos, const TMouseEvent &) override=0
void leftButtonUp (const TPointD &pos, const TMouseEvent &) override=0
void mouseMove (const TPointD &pos, const TMouseEvent &e) override
void leftButtonDoubleClick (const TPointD &, const TMouseEvent &e) override=0
bool keyDown (QKeyEvent *) override
int getCursorId () const override
Returns the type of cursor used by the tool.
void draw () override=0
Draws the tool on the viewer.
TSelection * getSelection () override=0
Returns a pointer to the tool selection.
virtual bool isSelectionEmpty ()=0
virtual void computeBBox ()=0
void onActivate () override
Callback invoked whenever the tool activates.
void onDeactivate () override
Callback for tool deactivation, includes tool switch.
void onImageChanged () override=0
Notifies changes in the image in use.
void onSelectionChanged () override
TPropertyGroup * getProperties (int targetType) override
bool onPropertyChanged (std::string propertyName) override
bool isEventAcceptable (QEvent *e) override
virtual bool isSelectionEditable ()
Public Member Functions inherited from TTool
TTool (std::string toolName)
every tool (invoking updateTranslation() for each).
virtual ToolType getToolType () const =0
ToolTargetType getTargetType () const
std::string getName () const
virtual ToolOptionsBox * createOptionsBox ()
void setViewer (Viewer *viewer)
Viewer * getViewer () const
double getPixelSize () const
void invalidate (const TRectD &rect=TRectD())
int pick (const TPointD &p)
bool isPicking () const
virtual void updateTranslation ()
virtual bool preLeftButtonDown ()
virtual void mouseMove (const TPointD &, const TMouseEvent &)
virtual void leftButtonDown (const TPointD &, const TMouseEvent &)
virtual void leftButtonDrag (const TPointD &, const TMouseEvent &)
virtual void leftButtonUp (const TPointD &, const TMouseEvent &)
virtual void leftButtonDoubleClick (const TPointD &, const TMouseEvent &)
virtual void rightButtonDown (const TPointD &, const TMouseEvent &)
virtual bool keyDown (QKeyEvent *)
virtual void onInputText (std::wstring, std::wstring, int, int)
virtual void onSetViewer ()
virtual void onActivate ()
Callback invoked whenever the tool activates.
virtual void onDeactivate ()
Callback for tool deactivation, includes tool switch.
virtual void onImageChanged ()
Notifies changes in the image in use.
virtual void onEnter ()
Callback for the mouse entering the viewer area.
virtual void onLeave ()
Callback for the mouse leaving the viewer area.
virtual void onFrameSwitched ()
virtual void reset ()
virtual void draw ()
Draws the tool on the viewer.
bool isActive () const
Used to know if a tool is active, (used in TextTool only).
void setActive (bool active)
virtual TPropertyGroup * getProperties (int)
virtual bool onPropertyChanged (std::string propertyName)
virtual TSelection * getSelection ()
Returns a pointer to the tool selection.
virtual int getCursorId () const
Returns the type of cursor used by the tool.
virtual bool isEventAcceptable (QEvent *e)
TXsheet * getXsheet () const
Returns a pointer to the actual Xsheet.
int getFrame ()
Returns the actual frame in use.
int getColumnIndex ()
Returns the actual column index.
TStageObjectId getObjectId () const
Returns a pointer to the actual stage object.
void notifyImageChanged ()
void notifyImageChanged (const TFrameId &fid)
images on the level view.
TFrameId getCurrentFid () const
Returns the number of the actual editing frame.
const TAffine & getMatrix () const
void setMatrix (const TAffine &matrix)
TAffine getCurrentColumnMatrix (int frame=-1) const
TAffine getCurrentColumnParentMatrix () const
TAffine getCurrentObjectParentMatrix () const
TAffine getCurrentObjectParentMatrix2 () const
TAffine getColumnMatrix (int index, int frame=-1) const
virtual void updateMatrix ()
virtual void addContextMenuItems (QMenu *menu)
void enable (bool on)
bool isEnabled () const
QString updateEnabled ()
virtual QString updateEnabled (int rowIndex, int columnIndex)
bool isColumnLocked (int columnIndex) const
void resetInputMethod ()
Resets Input Context (IME)
virtual bool isPencilModeActive ()
virtual bool isDragging () const
void setSelectedFrames (const std::set< TFrameId > &selectedFrames)
void tweenSelectedGuideStrokes ()
void tweenGuideStrokeToSelected ()
void flipGuideStrokeDirection (int mode)
Public Member Functions inherited from TSelection::View
virtual void onSelectionChanged ()=0
virtual void enableCommands ()
Public Attributes
bool m_resetCenter
Public Attributes inherited from SelectionTool
DragSelectionTool::DeformValues m_deformValues
Protected Member Functions
void onActivate () override
Callback invoked whenever the tool activates.
void onDeactivate () override
Callback for tool deactivation, includes tool switch.
void leftButtonDrag (const TPointD &pos, const TMouseEvent &) override
void leftButtonDown (const TPointD &pos, const TMouseEvent &) override
void leftButtonUp (const TPointD &pos, const TMouseEvent &) override
void leftButtonDoubleClick (const TPointD &, const TMouseEvent &e) override
void addContextMenuItems (QMenu *menu) override
void draw () override
Draws the tool on the viewer.
void updateAction (TPointD pos, const TMouseEvent &e) override
void onSelectedFramesChanged () override
bool onPropertyChanged (std::string propertyName) override
void onImageChanged () override
Notifies changes in the image in use.
int getCursorId () const override
Returns the type of cursor used by the tool.
bool isDragging () const override
Protected Member Functions inherited from SelectionTool
virtual void updateAction (TPointD pos, const TMouseEvent &e)
virtual void modifySelectionOnClick (TImageP image, const TPointD &pos, const TMouseEvent &e)=0
virtual void doOnActivate ()=0
virtual void doOnDeactivate ()=0
void startFreehand (const TPointD &pos)
void freehandDrag (const TPointD &pos)
Viene aggiunto pos a m_track e disegnato un altro pezzetto del lazzo.
void closeFreehand (const TPointD &pos)
void addPointPolyline (const TPointD &pos)
Viene aggiunto un punto al vettore m_polyline.
void closePolyline (const TPointD &pos)
void updateTranslation () override
void drawPolylineSelection ()
void drawRectSelection (const TImage *image)
void drawFreehandSelection ()
void drawCommandHandle (const TImage *image)
Protected Member Functions inherited from TTool
void bind (int targetType)
virtual void onSelectedFramesChanged ()
virtual QString disableString ()
Returns a custom reason to disable the tool.
Additional Inherited Members
Public Types inherited from TTool
enum ToolType {
GenericTool = 1 , ColumnTool = 2 , LevelReadTool = 4 , LevelWriteTool ,
LevelTool = LevelReadTool | LevelWriteTool
}
Tool editing type.
enum ToolTargetType {
NoTarget = 0x0 , VectorImage = 0x1 , ToonzImage = 0x2 , RasterImage = 0x4 ,
MeshImage = 0x8 , Splines = 0x10 , LevelColumns = 0x20 , MeshColumns = 0x40 ,
EmptyTarget = 0x80 , CommonImages = VectorImage | ToonzImage | RasterImage , AllImages = CommonImages | MeshImage , Vectors = VectorImage | Splines ,
CommonLevels = CommonImages | LevelColumns , MeshLevels = MeshImage | MeshColumns , AllTargets = 0xffffffff
}
Object types the tool can operate on.
typedef TApplication Application
Static Public Member Functions inherited from TTool
static TTool * getTool (std::string toolName, ToolTargetType targetType)
static TApplication * getApplication ()
static void setApplication (TApplication *application)
static TXshCell getImageCell ()
Returns the level-frame pair to be edited by the tool.
static TImage * getImage (bool toBeModified, int subsampling=0)
Returns the image to be edited by the tool.
static TImage * touchImage ()
static void updateToolsPropertiesTranslation ()
static const std::set< TFrameId > & getSelectedFrames ()
Static Public Attributes inherited from TTool
static std::vector< CellOps > m_cellsData
static bool m_isLevelCreated = false
static bool m_isFrameCreated = false
static std::vector< TFrameId > m_oldFids
static std::vector< TFrameId > m_newFids
static bool m_isLevelRenumbererd = false
Protected Types inherited from SelectionTool
enum {
Outside , Inside , DEFORM , ROTATION ,
MOVE_CENTER , SCALE , SCALE_X , SCALE_Y ,
GLOBAL_THICKNESS , ADD_SELECTION
}
enum {
P00 = 0 , P10 = 1 , P11 = 2 , P01 = 3 ,
PM0 = 4 , P1M = 5 , PM1 = 6 , P0M = 7 ,
NONE
}
Protected Attributes inherited from SelectionTool
bool m_firstTime
DragSelectionTool::DragTool * m_dragTool
StrokeGenerator m_track
std::vector< TPointD > m_polyline
TPointD m_mousePosition
TStroke * m_stroke
TPointD m_curPos
TPointD m_firstPos
bool m_selecting
bool m_justSelected
bool m_shiftPressed
enum SelectionTool:: { ... } m_what
enum SelectionTool:: { ... } m_selectedPoint
int m_cursorId
bool m_leftButtonMousePressed
DragSelectionTool::FourPoints m_selectingRect
std::vector< DragSelectionTool::FourPoints > m_bboxs
std::vector< TPointD > m_centers
std::vector< FreeDeformer * > m_freeDeformers
TEnumProperty m_strokeSelectionType
TPropertyGroup m_prop
Protected Attributes inherited from TTool
std::string m_name
The tool's name.
Viewer * m_viewer
Tool's current viewer.
TAffine m_matrix
World-to-window reference change affine.
int m_targetType
The tool's image type target.
bool m_enabled
Whether the tool allows user interaction.
bool m_active
bool m_picking
Static Protected Attributes inherited from TTool
static TApplication * m_application = 0
static std::set< TFrameId > m_selectedFrames = std::set<TFrameId>()
Detailed Description
Selection tool for Toonz's vector images.
Constructor & Destructor Documentation
VectorSelectionTool()
VectorSelectionTool::VectorSelectionTool (int targetType)
    : SelectionTool(targetType)
    , m_selectionTarget("Mode:")
    , m_includeIntersection("Include Intersection", false)
    , m_constantThickness("Preserve Thickness", false)
    , m_levelSelection(m_strokeSelection)
    , m_capStyle("Cap")
    , m_joinStyle("Join")
    , m_miterJoinLimit("Miter:", 0, 100, 4)
    , m_selectionCount(0)
    , m_canEnterGroup(true)
    , m_resetCenter(true) {
  assert(targetType == TTool::Vectors);
  m_prop.bind(m_selectionTarget);
  m_prop.bind(m_includeIntersection);
  m_prop.bind(m_constantThickness);
  m_selectionTarget.addValue(NORMAL_TYPE);
  m_selectionTarget.addValue(SELECTED_FRAMES_TYPE);
  m_selectionTarget.addValue(ALL_LEVEL_TYPE);
  m_selectionTarget.addValue(SAME_STYLE_TYPE);
  m_selectionTarget.addValue(STYLE_SELECTED_FRAMES_TYPE);
  m_selectionTarget.addValue(STYLE_LEVEL_TYPE);
  m_selectionTarget.addValue(BOUNDARY_TYPE);
  m_selectionTarget.addValue(BOUNDARY_SELECTED_FRAMES_TYPE);
  m_selectionTarget.addValue(BOUNDARY_LEVEL_TYPE);
  m_strokeSelection.setView(this);
  m_includeIntersection.setId("IncludeIntersection");
  m_constantThickness.setId("PreserveThickness");
  m_selectionTarget.setId("SelectionMode");
  m_capStyle.addValue(BUTT_WSTR, QString::fromStdWString(BUTT_WSTR));
  m_capStyle.addValue(ROUNDC_WSTR, QString::fromStdWString(ROUNDC_WSTR));
  m_capStyle.addValue(PROJECTING_WSTR,
                      QString::fromStdWString(PROJECTING_WSTR));
  m_capStyle.setId("Cap");
  m_joinStyle.addValue(MITER_WSTR, QString::fromStdWString(MITER_WSTR));
  m_joinStyle.addValue(ROUNDJ_WSTR, QString::fromStdWString(ROUNDJ_WSTR));
  m_joinStyle.addValue(BEVEL_WSTR, QString::fromStdWString(BEVEL_WSTR));
  m_joinStyle.setId("Join");
  m_miterJoinLimit.setId("Miter");
  m_outlineProps.bind(m_capStyle);
  m_outlineProps.bind(m_joinStyle);
  m_outlineProps.bind(m_miterJoinLimit);
}
Member Function Documentation
addContextMenuItems()
void VectorSelectionTool::addContextMenuItems (QMenu * menu) override protected virtual
Add a context menu to the actual tool, as for example pressing right mouse button with the stroke selection tool.
Reimplemented from TTool.
{
  menu->addAction(CommandManager::instance()->getAction(MI_RemoveEndpoints));
  menu->addSeparator();
  m_strokeSelection.getGroupCommand()->addMenuItems(menu);
}
canResetCenter()
bool VectorSelectionTool::canResetCenter () inline
{ return m_resetCenter; }
computeBBox()
void VectorSelectionTool::computeBBox () override virtual
Implements SelectionTool.
{
  m_bboxs.clear();
  if (canResetCenter()) m_centers.clear();
  TVectorImageP vi = getImage(false);
  if (!vi) return;
  if (isLevelType() || isSelectedFramesType()) {
    double maxThickness = 0;
    // Calculate current image's bbox - it is always the first one (index 0)
    if (vi && (isLevelType() || m_selectedFrames.count(getCurrentFid()) > 0)) {
      FourPoints bbox =
          getFourPointsFromVectorImage(vi, selectedStyles(), maxThickness);
      m_bboxs.push_back(bbox);
      m_centers.push_back((bbox.getP00() + bbox.getP11()) * 0.5);
    }
    // All subsequent SELECTED frames' bboxes come sequentially starting from 1
    if (TXshSimpleLevel *level =
            TTool::getApplication()->getCurrentLevel()->getSimpleLevel()) {
      std::vector<TFrameId> fids;
      level->getFids(fids);
      for (int i = 0; i < (int)fids.size(); ++i) {
        if (getCurrentFid() == fids[i] ||
            (isSelectedFramesType() && m_selectedFrames.count(fids[i]) == 0))
          continue;
        TVectorImageP vi = level->getFrame(fids[i], false);
        if (!vi) continue;
        FourPoints p =
            getFourPointsFromVectorImage(vi, selectedStyles(), maxThickness);
        m_bboxs.push_back(p);
        m_centers.push_back(0.5 * (p.getP00() + p.getP11()));
        m_deformValues.m_maxSelectionThickness = maxThickness;
      }
    }
  } else if (vi) {
    TRectD newBbox;
    double maxThickness = 0;
    for (int i = 0; i < (int)vi->getStrokeCount(); i++) {
      TStroke *stroke = vi->getStroke(i);
      if (m_strokeSelection.isSelected(i)) {
        newBbox += stroke->getBBox();
        for (int j = 0; j < stroke->getControlPointCount(); j++) {
          double thick = stroke->getControlPoint(j).thick;
          if (maxThickness < thick) maxThickness = thick;
        }
      }
    }
    m_deformValues.m_maxSelectionThickness = maxThickness;
    FourPoints bbox;
    bbox = newBbox;
    m_bboxs.push_back(bbox);
    if (canResetCenter())
      m_centers.push_back(0.5 * (bbox.getP11() + bbox.getP00()));
  }
  ++m_selectionCount;
}
draw()
void VectorSelectionTool::draw () override protected virtual
Draws the tool on the viewer.
Implements SelectionTool.
{
  TVectorImageP vi = getImage(false);
  if (!vi) return;
  if (isLevelType() || isSelectedFramesType()) {
    drawInLevelType(*vi);
    return;
  }
  glPushMatrix();
  if (m_strokeSelection.isEmpty())  // o_o  WTF!?
    m_bboxs.clear();                //
  // common draw
  if (getBBoxsCount() > 0) drawCommandHandle(vi.getPointer());
  if (m_selecting && !m_selectingRect.isEmpty())
    drawRectSelection(vi.getPointer());
  TRectD bbox = vi->getBBox();
  TPixel32 frameColor(140, 140, 140);
  tglColor(frameColor);
  drawRect(bbox, frameColor, 0x5555, true);
  drawSelectedStrokes(*vi);
  if (m_strokeSelectionType.getIndex() == POLYLINE_SELECTION_IDX)
    drawPolylineSelection();
  else if (m_strokeSelectionType.getIndex() == FREEHAND_SELECTION_IDX)
    drawFreehandSelection();
  if (m_levelSelection.isEmpty()) drawGroup(*vi);
  glPopMatrix();
}
References TRectT< T >::isEmpty().
getCursorId()
int VectorSelectionTool::getCursorId () const inline override protected virtual
Returns the type of cursor used by the tool.
See also
For a list of cursor ids cursor.h
Reimplemented from SelectionTool.
{
    if (m_viewer && m_viewer->getGuidedStrokePickerMode())
      return m_viewer->getGuidedStrokePickerCursor();
    return m_cursorId;
  }
References TTool::m_viewer.
getProperties()
TPropertyGroup * VectorSelectionTool::getProperties (int targetType) override virtual
Reimplemented from SelectionTool.
{
  switch (idx) {
  case 0:
    return &m_prop;
  case 1:
    return &m_outlineProps;
  default:
    return 0;
  };
}
getSelection()
TSelection * VectorSelectionTool::getSelection () override virtual
Returns a pointer to the tool selection.
Implements SelectionTool.
{
  TImage *image    = getImage(false);
  TVectorImageP vi = image;
  if (!vi) return 0;
  return &m_strokeSelection;
}
getSelectionCount()
int VectorSelectionTool::getSelectionCount () const inline
{ return m_selectionCount; }
isConstantThickness()
bool VectorSelectionTool::isConstantThickness () const inline override virtual
Reimplemented from SelectionTool.
{
    return m_constantThickness.getValue();
  }
isDragging()
bool VectorSelectionTool::isDragging () const override protected virtual
Reimplemented from TTool.
{
  return m_enabled && m_leftButtonMousePressed;
}
isLevelType()
bool VectorSelectionTool::isLevelType () const override virtual
Reimplemented from SelectionTool.
{
  return m_levelSelection.framesMode() == LevelSelection::FRAMES_ALL;
}
isModifiableSelectionType()
bool VectorSelectionTool::isModifiableSelectionType () const override virtual
Reimplemented from SelectionTool.
{
  return (m_levelSelection.isEmpty() ||
          m_levelSelection.filter() == LevelSelection::SELECTED_STYLES);
}
isSameStyleType()
bool VectorSelectionTool::isSameStyleType () const override virtual
Reimplemented from SelectionTool.
{
  return m_levelSelection.filter() == LevelSelection::SELECTED_STYLES;
}
isSelectedFramesType()
bool VectorSelectionTool::isSelectedFramesType () const override virtual
Reimplemented from SelectionTool.
{
  return m_levelSelection.framesMode() == LevelSelection::FRAMES_SELECTED;
}
isSelectionEditable()
bool VectorSelectionTool::isSelectionEditable () inline override virtual
Reimplemented from SelectionTool.
{ return m_strokeSelection.isEditable(); }
isSelectionEmpty()
bool VectorSelectionTool::isSelectionEmpty () override virtual
Implements SelectionTool.
{
  TVectorImageP vi =
      getImage(false);  // We want at least current image to be visible.
  if (!vi)              // This is somewhat in line to preventing tool actions
    return true;        // on non-visible levels.
  return m_strokeSelection
      .isEmpty();  // Same here, something should be visibly selected.
}
leftButtonDoubleClick()
void VectorSelectionTool::leftButtonDoubleClick (const TPointD & pos, const TMouseEvent & e) override protected virtual
Implements SelectionTool.
{
  TVectorImageP vi = getImage(false);
  if (!vi) return;
  if (m_strokeSelectionType.getIndex() == POLYLINE_SELECTION_IDX &&
      !m_polyline.empty()) {
    closePolyline(pos);
    selectRegionVectorImage(m_includeIntersection.getValue());
    m_selecting = false;
    invalidate();
    return;
  }
  int strokeIndex;
  if ((strokeIndex = vi->pickGroup(pos)) >= 0) {
    if (vi->canEnterGroup(strokeIndex) && m_canEnterGroup) {
      if (vi->enterGroup(strokeIndex)) {
        clearSelectedStrokes();
        TUndoManager::manager()->add(new UndoEnterGroup(vi, strokeIndex));
      }
    }
  } else if ((strokeIndex = vi->exitGroup()) >= 0)
    TUndoManager::manager()->add(new UndoExitGroup(vi, strokeIndex));
  finalizeSelection();
  invalidate();
}
leftButtonDown()
void VectorSelectionTool::leftButtonDown (const TPointD & pos, const TMouseEvent & e) override protected virtual
Reimplemented from SelectionTool.
{
  if (getViewer() && getViewer()->getGuidedStrokePickerMode()) {
    getViewer()->doPickGuideStroke(pos);
    return;
  }
  SelectionTool::leftButtonDown(pos, e);
}
leftButtonDrag()
void VectorSelectionTool::leftButtonDrag (const TPointD & pos, const TMouseEvent & e) override protected virtual
Implements SelectionTool.
{
  if (m_dragTool) {
    if (!m_strokeSelection.isEditable()) return;
    m_dragTool->leftButtonDrag(pos, e);
    return;
  }
  TVectorImageP vi = getImage(false);
  if (!vi) return;
  double pixelSize        = getPixelSize();
  TTool::Application *app = TTool::getApplication();
  if (!app || m_justSelected || !m_selecting ||
      tdistance2(pos, m_curPos) < 9.0 * pixelSize * pixelSize)
    return;
  m_curPos = pos;
  if (m_strokeSelectionType.getIndex() == FREEHAND_SELECTION_IDX) {
    freehandDrag(pos);
    invalidate();
  } else if (m_strokeSelectionType.getIndex() == RECT_SELECTION_IDX) {
    bool selectOverlappingStroke = (m_firstPos.x > pos.x);
    TRectD rect(m_firstPos, pos);
    m_selectingRect = rect;
    std::set<int> oldSelection;
    if (m_shiftPressed) oldSelection = m_strokeSelection.getSelection();
    clearSelectedStrokes();
    QMutexLocker lock(vi->getMutex());
    m_strokeSelection.setImage(vi);  // >_<  Shouldn't be done here...?
    bool selectionChanged = false;
    int s, sCount = vi->getStrokeCount();
    for (s = 0; s != sCount; ++s) {
      if (!vi->isEnteredGroupStroke(s)) continue;
      TStroke *stroke = vi->getStroke(s);
      if (m_strokeSelection.isSelected(s)) continue;
      bool inSelection = selectOverlappingStroke
                             ? rect.overlaps(stroke->getBBox())
                             : rect.contains(stroke->getBBox());
      if (inSelection || (m_shiftPressed && oldSelection.count(s)))
        selectionChanged = (selectStroke(s, false) || selectionChanged);
    }
    if (selectionChanged) finalizeSelection();
    invalidate();
  }
}
leftButtonUp()
void VectorSelectionTool::leftButtonUp (const TPointD & pos, const TMouseEvent & e) override protected virtual
Implements SelectionTool.
{
  m_leftButtonMousePressed = false;
  m_shiftPressed           = false;
  if (m_dragTool) {
    if (!m_strokeSelection.isEditable()) {
      delete m_dragTool;
      m_dragTool = 0;
      return;
    }
    m_dragTool->leftButtonUp(pos, e);
    delete m_dragTool;
    m_dragTool = 0;
    invalidate();
    return;
  }
  if (!m_selecting) return;
  // Complete selection
  TVectorImageP vi = getImage(false);
  if (vi) {
    if (m_strokeSelectionType.getIndex() == RECT_SELECTION_IDX)
      notifySelectionChanged();
    else if (m_strokeSelectionType.getIndex() == FREEHAND_SELECTION_IDX) {
      QMutexLocker lock(vi->getMutex());
      closeFreehand(pos);
      if (m_stroke->getControlPointCount() > 3)
        selectRegionVectorImage(m_includeIntersection.getValue());
      delete m_stroke;  // >:(
      m_stroke = 0;
      m_track.clear();
    }
  }
  m_selecting    = false;
  m_justSelected = false;
  invalidate();
}
levelSelection()
const LevelSelection & VectorSelectionTool::levelSelection () const inline
{ return m_levelSelection; }
onActivate()
void VectorSelectionTool::onActivate () override protected virtual
Callback invoked whenever the tool activates.
Reimplemented from SelectionTool.
{
  if (m_firstTime) {
    m_includeIntersection.setValue(l_strokeSelectIncludeIntersection ? 1 : 0);
    m_constantThickness.setValue(l_strokeSelectConstantThickness ? 1 : 0);
    m_strokeSelection.setSceneHandle(
        TTool::getApplication()->getCurrentScene());
  }
  SelectionTool::onActivate();
}
References SelectionTool::onActivate().
onDeactivate()
void VectorSelectionTool::onDeactivate () override protected virtual
Callback for tool deactivation, includes tool switch.
Reimplemented from SelectionTool.
{
  if (isLevelType()) return;
  SelectionTool::onDeactivate();
}
References SelectionTool::onDeactivate().
onImageChanged()
void VectorSelectionTool::onImageChanged () override protected virtual
Notifies changes in the image in use.
Implements SelectionTool.
{
  TVectorImageP vi          = getImage(false);
  TVectorImageP selectedImg = m_strokeSelection.getImage();
  if (vi != selectedImg) {
    m_strokeSelection.selectNone();
    m_strokeSelection.setImage(vi);
    if (!(vi && selectedImg)  // Retain the styles selection ONLY
        || vi->getPalette() !=
               selectedImg->getPalette())  // if palettes still match
      selectedStyles().clear();
  } else {
    // Remove any eventual stroke index outside the valid range
    if (!m_strokeSelection.isEmpty()) {
      const std::set<int> &indexes = m_strokeSelection.getSelection();
      int strokesCount             = selectedImg->getStrokeCount();
      std::set<int>::const_iterator it;
      for (it = indexes.begin(); it != indexes.end(); ++it) {
        int index = *it;
        if (index >= strokesCount) m_strokeSelection.select(index, false);
      }
    }
  }
  finalizeSelection();
}
onPropertyChanged()
bool VectorSelectionTool::onPropertyChanged (std::string propertyName) override protected virtual
 Does the tasks associated to changes in \p propertyName and returns \p
true; Does the tasks associated to changes in propertyName and returns true.
Reimplemented from SelectionTool.
{
  if (!m_strokeSelection.isEditable()) return false;
  if (SelectionTool::onPropertyChanged(propertyName)) return true;
  if (propertyName == m_includeIntersection.getName())
    l_strokeSelectIncludeIntersection = (int)(m_includeIntersection.getValue());
  if (propertyName == m_constantThickness.getName())
    l_strokeSelectConstantThickness = (int)(m_constantThickness.getValue());
  else if (propertyName == m_selectionTarget.getName())
    doOnActivate();
  else if (propertyName == m_capStyle.getName()) {
    if (m_strokeSelection.isEmpty()) return true;
    TXshSimpleLevel *level =
        TTool::getApplication()->getCurrentLevel()->getSimpleLevel();
    UndoChangeOutlineStyle *undo =
        new UndoChangeOutlineStyle(level, getCurrentFid(), this);
    int newCapStyle = m_capStyle.getIndex();
    TVectorImageP vi = m_strokeSelection.getImage();
    const std::set<int> &indices = m_strokeSelection.getSelection();
    std::set<int>::iterator it;
    for (it = indices.begin(); it != indices.end(); ++it) {
      TStroke *stroke = vi->getStroke(*it);
      stroke->outlineOptions().m_capStyle =
          (TStroke::OutlineOptions::CapStyle)newCapStyle;
      stroke->invalidate();
    }
    computeBBox();
    invalidate();
    level->setDirtyFlag(true);
    undo->registerStrokes();
    TUndoManager::manager()->add(undo);
    notifyImageChanged();
  } else if (propertyName == m_joinStyle.getName()) {
    if (m_strokeSelection.isEmpty()) return true;
    TXshSimpleLevel *level =
        TTool::getApplication()->getCurrentLevel()->getSimpleLevel();
    UndoChangeOutlineStyle *undo =
        new UndoChangeOutlineStyle(level, getCurrentFid(), this);
    int newJoinStyle = m_joinStyle.getIndex();
    TVectorImageP vi = m_strokeSelection.getImage();
    const std::set<int> &indices = m_strokeSelection.getSelection();
    std::set<int>::iterator it;
    for (it = indices.begin(); it != indices.end(); ++it) {
      TStroke *stroke = vi->getStroke(*it);
      stroke->outlineOptions().m_joinStyle =
          (TStroke::OutlineOptions::JoinStyle)newJoinStyle;
      stroke->invalidate();
    }
    computeBBox();
    invalidate();
    level->setDirtyFlag(true);
    undo->registerStrokes();
    TUndoManager::manager()->add(undo);
    notifyImageChanged();
  } else if (propertyName == m_miterJoinLimit.getName()) {
    if (m_strokeSelection.isEmpty()) return true;
    TXshSimpleLevel *level =
        TTool::getApplication()->getCurrentLevel()->getSimpleLevel();
    UndoChangeOutlineStyle *undo =
        new UndoChangeOutlineStyle(level, getCurrentFid(), this);
    int upper = m_miterJoinLimit.getValue();
    TVectorImageP vi = m_strokeSelection.getImage();
    const std::set<int> &indices = m_strokeSelection.getSelection();
    std::set<int>::iterator it;
    for (it = indices.begin(); it != indices.end(); ++it) {
      TStroke *stroke = vi->getStroke(*it);
      stroke->outlineOptions().m_miterUpper = upper;
      stroke->invalidate();
    }
    computeBBox();
    invalidate();
    level->setDirtyFlag(true);
    undo->registerStrokes();
    TUndoManager::manager()->add(undo);
    notifyImageChanged();
  } else
    return false;
  return true;
}
References TStroke::invalidate(), SelectionTool::onPropertyChanged(), and TXshSimpleLevel::setDirtyFlag().
onSelectedFramesChanged()
void VectorSelectionTool::onSelectedFramesChanged () override protected virtual
Reimplemented from TTool.
{
  if (isSelectedFramesType())  // False also in case m_levelSelection is not
                               // current
    finalizeSelection();
}
selectedStyles() [1/2]
std::set< int > & VectorSelectionTool::selectedStyles () inline
{ return m_levelSelection.styles(); }
selectedStyles() [2/2]
const std::set< int > & VectorSelectionTool::selectedStyles () const inline
{
    return m_levelSelection.styles();
  }
selectionOutlineStyle()
void VectorSelectionTool::selectionOutlineStyle (int & capStyle, int & joinStyle)
{
  // Check the selection's outline style group validity
  const std::set<int> &selection = m_strokeSelection.getSelection();
  if (selection.empty()) {
    capStyle = joinStyle = -1;
    return;
  }
  TVectorImageP vi = m_strokeSelection.getImage();
  const TStroke::OutlineOptions &beginOptions =
      vi->getStroke(*selection.begin())->outlineOptions();
  capStyle  = beginOptions.m_capStyle;
  joinStyle = beginOptions.m_joinStyle;
  std::set<int>::const_iterator it;
  for (it = selection.begin(); it != selection.end(); ++it) {
    const TStroke::OutlineOptions &options =
        vi->getStroke(*it)->outlineOptions();
    if (capStyle != options.m_capStyle) capStyle = -1;
    if (joinStyle != options.m_joinStyle) joinStyle = -1;
    if (capStyle < 0 && joinStyle < 0) return;
  }
}
setCanEnterGroup()
void VectorSelectionTool::setCanEnterGroup (bool value) inline
{ m_canEnterGroup = value; }
setNewFreeDeformer()
void VectorSelectionTool::setNewFreeDeformer () override virtual
Implements SelectionTool.
{
  clearDeformers();
  TVectorImageP vi =
      getImage(true);  // BAD: Should not be done at tool creation...
  if (!vi) return;
  // Current freeDeformer always at index 0
  m_freeDeformers.push_back(
      new VectorFreeDeformer(vi, m_strokeSelection.getSelection()));
  if (isLevelType() || isSelectedFramesType()) {
    TXshSimpleLevel *level =
        TTool::getApplication()->getCurrentLevel()->getSimpleLevel();
    // All SELECTED frames' subsequent freeDeformers are stored sequentially
    // after that
    std::vector<TFrameId> fids;
    level->getFids(fids);
    fids.erase(std::remove_if(
                   fids.begin(), fids.end(),
                   boost::bind(::currentOrNotSelected, boost::cref(*this), _1)),
               fids.end());
    std::vector<TFrameId>::iterator ft, fEnd = fids.end();
    for (ft = fids.begin(); ft != fEnd; ++ft) {
      if (TVectorImageP levelVi = level->getFrame(*ft, false)) {
        const std::vector<int> &selectedStrokeIdxs =
            ::getSelectedStrokes(*levelVi, m_levelSelection);
        std::set<int> strokesIndices(selectedStrokeIdxs.begin(),
                                     selectedStrokeIdxs.end());
        m_freeDeformers.push_back(
            new VectorFreeDeformer(levelVi, strokesIndices));
      }
    }
  }
}
setResetCenter()
void VectorSelectionTool::setResetCenter (bool update) inline
{ m_resetCenter = update; }
strokeSelection()
const StrokeSelection & VectorSelectionTool::strokeSelection () const inline
{ return m_strokeSelection; }
updateAction()
void VectorSelectionTool::updateAction (TPointD pos, const TMouseEvent & e) override protected virtual
Reimplemented from SelectionTool.
{
  TImageP image    = getImage(false);
  TVectorImageP vi = (TVectorImageP)image;
  if (!vi) return;
  SelectionTool::updateAction(pos, e);
  if (m_what != Outside || m_cursorId != ToolCursor::StrokeSelectCursor) return;
  if (!m_strokeSelection.isEditable()) return;
  FourPoints bbox = getBBox();
  UINT index      = 0;
  if ((isLevelType() &&
       bbox.contains(pos))  // What about isSelectedFramesType()??
      || (getStrokeIndexFromPos(index, vi, pos, getPixelSize(),
                                getViewer()->getViewMatrix()) &&
          m_strokeSelection.isSelected(index))) {
    m_what = Inside;
    m_cursorId =
        isLevelType() ? ToolCursor::LevelSelectCursor : ToolCursor::MoveCursor;
  }
}
Member Data Documentation
m_resetCenter
bool VectorSelectionTool::m_resetCenter
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/tnztools/vectorselectiontool.h
E:/opentoonz/toonz/sources/tnztools/vectorselectiontool.cpp