opentoonz: TCenterLineStrokeStyle Class Reference
TCenterLineStrokeStyle Class Reference final
#include <tsimplecolorstyles.h>
Public Member Functions
TCenterLineStrokeStyle (const TPixel32 &color=TPixel32(0, 0, 0, 255), USHORT stipple=0x0, double width=1.0)
TColorStyle * clone () const override
Polymorphic clone of the style.
QString getDescription () const override
Return a brief description of the style.
TPixel32 getColor () const
USHORT getStipple () const
void drawStroke (const TColorFunction *cf, const TStroke *stroke) const override
bool hasMainColor () const override
Returns whether the style has a reference main color.
TPixel32 getMainColor () const override
Returns the style's main color, or black if none.
void setMainColor (const TPixel32 &color) override
Sets the main color, if it has one.
int getParamCount () const override
TColorStyle::ParamType getParamType (int index) const override
Returns the type of the specified parameter.
QString getParamNames (int index) const override
Return the string that identifies the index-th parameter.
void getParamRange (int index, double &min, double &max) const override
Retrieves the specified double parameter range.
double getParamValue (TColorStyle::double_tag, int index) const override
Retrieves the specified double parameter value.
void setParamValue (int index, double value) override
extension value in text form.
int getTagId () const override
Returns an unique number representing the style.
Public Member Functions inherited from TSimpleStrokeStyle
bool isRegionStyle () const override
Returns whether the style applies on regions.
bool isStrokeStyle () const override
Returns whether the style applies on strokes.
TStrokeProp * makeStrokeProp (const TStroke *stroke) override
TRegionProp * makeRegionProp (const TRegion *) override
used to draw the style on the specified stroke object.
virtual void drawStroke (const TColorFunction *cf, const TStroke *stroke) const =0
Public Member Functions inherited from TColorStyle
TColorStyle (const TColorStyle &other)
Copies another style except its icon.
virtual TColorStyle * clone () const =0
Polymorphic clone of the style.
virtual TColorStyle & copy (const TColorStyle &other)
bool operator== (const TColorStyle &cs) const
bool operator!= (const TColorStyle &cs)
virtual TStrokeProp * makeStrokeProp (const TStroke *stroke)=0
virtual TRegionProp * makeRegionProp (const TRegion *region)=0
used to draw the style on the specified stroke object.
virtual bool isRasterStyle () const
used to draw the style on the specified region object.
virtual TRasterStyleFx * getRasterStyleFx ()
virtual bool isRegionStyle () const =0
Returns whether the style applies on regions.
virtual bool isStrokeStyle () const =0
Returns whether the style applies on strokes.
void setName (std::wstring name)
Sets the style's user-defined name.
std::wstring getName () const
Returns the style's user-defined name.
void setGlobalName (std::wstring name)
Sets the global name of the style.
std::wstring getGlobalName () const
Returns the global name of the style.
void setOriginalName (std::wstring name)
If the style is originally copied from studio palette, set this.
std::wstring getOriginalName () const
Returns the original name of the style.
void setIsEditedFlag (bool edited)
bool getIsEditedFlag () const
style is edited from the original one.
void assignNames (const TColorStyle *src)
Copies the style names from src.
unsigned int getFlags () const
Sets color attributes.
void setFlags (unsigned int flags)
Returns color attributes.
void setPickedPosition (const TPoint &pos, const int index=0)
void setPickedPosition (const PickedPosition &pos)
PickedPosition getPickedPosition () const
virtual bool hasMainColor () const
Returns whether the style has a reference main color.
virtual TPixel32 getMainColor () const
Returns the style's main color, or black if none.
virtual void setMainColor (const TPixel32 &color)
Sets the main color, if it has one.
virtual int getColorParamCount () const
Returns the number of colors (if any) of the style.
virtual TPixel32 getColorParamValue (int index) const
Returns the value of the color of index index.
virtual void setColorParamValue (int index, const TPixel32 &color)
Sets the index-th color value.
virtual TPixel32 getAverageColor () const
Returns a color representing the average of all the style's colors.
virtual int getParamCount () const
virtual ParamType getParamType (int paramIdx) const
Returns the type of the specified parameter.
virtual bool hasParamDefault (int index) const
Value of parameter can be reset to default.
virtual void setParamDefault (int index)
Reset value of parameter to default.
virtual bool isParamDefault (int index) const
Check if current value of parameter equals to default.
virtual void setParamValue (int index, bool value)
Assigns a value to the specified bool parameter.
virtual bool getParamValue (bool_tag, int index) const
Retrieves the specified bool parameter value.
virtual void setParamValue (int index, int value)
Assigns a value to the specified int parameter.
virtual int getParamValue (int_tag, int index) const
Retrieves the specified int parameter value.
virtual void getParamRange (int index, int &min, int &max) const
Retrieves the specified int parameter range.
virtual void getParamRange (int pIndex, QStringList &stringItems) const
virtual void setParamValue (int index, double value)
extension value in text form.
virtual double getParamValue (double_tag, int index) const
Retrieves the specified double parameter value.
virtual void getParamRange (int index, double &min, double &max) const
Retrieves the specified double parameter range.
virtual void setParamValue (int index, const TFilePath &fp)
Assigns a value to the specified TFilePath parameter.
virtual TFilePath getParamValue (TFilePath_tag, int index) const
Retrieves the specified TFilePath parameter value.
void assignBlend (const TColorStyle &a, const TColorStyle &b, double t)
virtual QString getDescription () const =0
Return a brief description of the style.
virtual QString getParamNames (int index) const
Return the string that identifies the index-th parameter.
virtual int getTagId () const =0
Returns an unique number representing the style.
virtual void getObsoleteTagIds (std::vector< int > &) const
void save (TOutputStreamInterface &) const
void invalidateIcon ()
Sets a flag that defines the style's icon validity.
virtual const TRaster32P & getIcon (const TDimension &d)
Returns an image representing the style.
bool isEnabled () const
Returns whether the style can be used.
void enable (bool on)
Sets the style's enabled status.
int getVersionNumber () const
Returns the version number of the style.
Public Member Functions inherited from TSmartObject
TSmartObject (ClassCode classCode)
void addRef ()
void release ()
TINT32 getRefCount () const
Protected Member Functions
void loadData (TInputStreamInterface &) override
void saveData (TOutputStreamInterface &) const override
Protected Member Functions inherited from TColorStyle
virtual void makeIcon (const TDimension &d)
virtual void loadData (TInputStreamInterface &)=0
virtual void saveData (TOutputStreamInterface &) const =0
virtual void loadData (int, TInputStreamInterface &)
void updateVersionNumber ()
TColorStyle & operator= (const TColorStyle &other)
Copies another style except its icon.
Additional Inherited Members
Public Types inherited from TColorStyle
enum ParamType {
BOOL , INT , ENUM , DOUBLE ,
FILEPATH
}
Public Types inherited from TSmartObject
typedef short ClassCode
Static Public Member Functions inherited from TColorStyle
static TColorStyle * load (TInputStreamInterface &)
static TColorStyle * create (int tagId)
Creates a new style with identifier equal to tagId.
static void declare (TColorStyle *style)
Puts the style in the table of actual styles.
static void getAllTags (std::vector< int > &tags)
Static Public Member Functions inherited from TSmartObject
static TINT32 getInstanceCount (ClassCode code)
Static Public Attributes inherited from TColorStyle
static int m_currentFrame = 0
Protected Attributes inherited from TColorStyle
TRaster32P m_icon
Icon shown on TPalette viewers.
bool m_validIcon
Icon's validity status.
Detailed Description
Constant thickness stroke style.
Constructor & Destructor Documentation
TCenterLineStrokeStyle()
TCenterLineStrokeStyle::TCenterLineStrokeStyle (const TPixel32 & color = TPixel32(0, 0, 0, 255), USHORT stipple = 0x0, double width = 1.0)
    : m_color(color), m_stipple(stipple), m_width(width) {}
Member Function Documentation
clone()
TColorStyle * TCenterLineStrokeStyle::clone () const override virtual
Polymorphic clone of the style.
Implements TColorStyle.
{
  return new TCenterLineStrokeStyle(*this);
}
drawStroke()
void TCenterLineStrokeStyle::drawStroke (const TColorFunction * cf, const TStroke * stroke) const override virtual
Implements TSimpleStrokeStyle.
{
  if (!stroke) return;
  // center line
  int i, n = stroke->getChunkCount();
  if (n == 0) return;
  TPixel32 color = m_color;
  if (cf) color = (*cf)(m_color);
  if (color.m == 0) return;
  tglColor(color);
  double pixelSize = sqrt(tglGetPixelSize2());
  if (m_stipple != 0) {
    glEnable(GL_LINE_STIPPLE);
    glLineStipple(1, m_stipple);
  }
  const TThickQuadratic *q = 0;
  q                        = stroke->getChunk(0);
  GLfloat rangeValue[2];
  glGetFloatv(GL_LINE_WIDTH_RANGE, &rangeValue[0]);
  float width = float(m_width);
  if (width < rangeValue[0])
    width = rangeValue[0];
  else if (width > rangeValue[1])
    width = rangeValue[1];
  width = 2 * width;
  if (width <= 1.0) {
    if (m_width != 0.0) width /= pixelSize;
    if (width ==
        0.F)  // http://www.opengl.org/sdk/docs/man/xhtml/glLineWidth.xml
      width = 0.00001;
    glLineWidth(width);
    glBegin(GL_LINE_STRIP);
    for (i = 0; i < n; i++) {
      q           = stroke->getChunk(i);
      double step = computeStep(*q, pixelSize);
      for (double t = 0; t < 1; t += step) tglVertex(q->getPoint(t));
    }
    assert(q);
    tglVertex(q->getP2());
    glEnd();
  } else {
    double s      = 0;
    double length = stroke->getLength();
    TPointD pos1, pos4;
    std::vector<TPointD> pv;
    width = width / 2.;
    while (s <= length) {
      double step = 1.0;
      double w    = stroke->getParameterAtLength(s);
      if (w <= 0) {
        s += 0.01;
        continue;
      }  // per tamponare il baco della getParameterAtLength()
      TPointD u = stroke->getSpeed(w);
      if (norm2(u) == 0) {
        s += 0.1;
        continue;
      }  // non dovrebbe succedere mai, ma per prudenza....
      TThickPoint pos = stroke->getThickPoint(w);
      u               = normalize(u);
      TPointD v       = rotate90(u) * (width);
      pos1            = pos + v;
      pos4            = pos - v;
      pv.push_back(pos1);
      pv.push_back(pos4);
      s += step;
    }
    double w = stroke->getParameterAtLength(length);
    if (w > 0) {
      TPointD u = stroke->getSpeed(w);
      if (norm2(u) != 0) {
        TThickPoint pos = stroke->getThickPoint(w);
        u               = normalize(u);
        TPointD v       = rotate90(u) * (width);
        pos1            = pos + v;
        pos4            = pos - v;
        pv.push_back(pos1);
        pv.push_back(pos4);
      }
    }
    if (pv.size() > 2) {
      glColor4ub(color.r, color.g, color.b, color.m);
      glBegin(QUAD_PRIMITIVE);
      std::vector<TPointD>::iterator it = pv.begin();
      for (; it != pv.end(); ++it) {
        tglVertex(*it);
      }
      glEnd();
      glBegin(GL_LINE_STRIP);
      std::vector<TPointD>::iterator it1 = pv.begin();
      for (; it1 != pv.end(); ++it1) {
        ++it1;
        tglVertex(*it1);
      }
      glEnd();
      glBegin(GL_LINE_STRIP);
      std::vector<TPointD>::iterator it2 = pv.begin();
      if (it2 != pv.end()) ++it2;
      for (; it2 != pv.end() - 1; ++it2) {
        ++it2;
        tglVertex(*it2);
      }
      glEnd();
    }
  }
  if (m_stipple != 0) glDisable(GL_LINE_STIPPLE);
  glLineWidth(1.0);
}
getColor()
TPixel32 TCenterLineStrokeStyle::getColor () const inline
{ return m_color; }
getDescription()
QString TCenterLineStrokeStyle::getDescription () const override virtual
Return a brief description of the style.
\detail For example for a stroke style we have "Constant", "Chain", "Rope", "Tulle", etc...
Implements TColorStyle.
{
  return QCoreApplication::translate("TCenterLineStrokeStyle", "Constant");
}
getMainColor()
TPixel32 TCenterLineStrokeStyle::getMainColor () const inline override virtual
Returns the style's main color, or black if none.
Reimplemented from TColorStyle.
{ return m_color; }
getParamCount()
int TCenterLineStrokeStyle::getParamCount () const override virtual
\detail For example: a the general cleanup style has two parameters, brightness and contrast and a black cleanup style has in addition a black and white threshold, therefore 4 parameters. Returns the number of parameters necessary to describe the style.
Reimplemented from TColorStyle.
{ return 1; }
Referenced by getParamRange(), getParamType(), getParamValue(), and setParamValue().
getParamNames()
QString TCenterLineStrokeStyle::getParamNames (int index) const override virtual
Return the string that identifies the index-th parameter.
Reimplemented from TColorStyle.
{
  return QCoreApplication::translate("TCenterLineStrokeStyle", "Thickness");
}
getParamRange()
void TCenterLineStrokeStyle::getParamRange (int index, double & min, double & max) const override virtual
Retrieves the specified double parameter range.
Reimplemented from TColorStyle.
{
  assert(0 <= index && index < getParamCount());
  min = 0.0, max = 10.0;
}
References getParamCount().
getParamType()
TColorStyle::ParamType TCenterLineStrokeStyle::getParamType (int paramIdx) const override virtual
Returns the type of the specified parameter.
Reimplemented from TColorStyle.
{
  assert(0 <= index && index < getParamCount());
  return TColorStyle::DOUBLE;
}
References TColorStyle::DOUBLE, and getParamCount().
getParamValue()
double TCenterLineStrokeStyle::getParamValue (TColorStyle::double_tag , int index) const override virtual
Retrieves the specified double parameter value.
Reimplemented from TColorStyle.
{
  assert(0 <= index && index < getParamCount());
  return m_width;
}
References getParamCount().
getStipple()
USHORT TCenterLineStrokeStyle::getStipple () const inline
{ return m_stipple; }
getTagId()
int TCenterLineStrokeStyle::getTagId () const override virtual
Returns an unique number representing the style.
Implements TColorStyle.
{ return 2; }
hasMainColor()
bool TCenterLineStrokeStyle::hasMainColor () const inline override virtual
Returns whether the style has a reference main color.
\detail Raster or vector pattern image styles, for example, return false.
Reimplemented from TColorStyle.
{ return true; }
loadData()
void TCenterLineStrokeStyle::loadData (TInputStreamInterface & is) override protected virtual
Implements TColorStyle.
{
  is >> m_color >> m_stipple >> m_width;
}
saveData()
void TCenterLineStrokeStyle::saveData (TOutputStreamInterface & os) const override protected virtual
Implements TColorStyle.
{
  os << m_color << m_stipple << m_width;
}
setMainColor()
void TCenterLineStrokeStyle::setMainColor (const TPixel32 & color) inline override virtual
Sets the main color, if it has one.
Reimplemented from TColorStyle.
{ m_color = color; }
setParamValue()
void TCenterLineStrokeStyle::setParamValue (int index, double value) override virtual
extension value in text form.
Assigns a value to the specified double parameter.
Reimplemented from TColorStyle.
{
  assert(0 <= index && index < getParamCount());
  m_width = value;
}
References getParamCount().
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/tsimplecolorstyles.h
E:/opentoonz/toonz/sources/common/tvrender/tsimplecolorstyles.cpp