opentoonz: VectorTapeTool Class Reference
VectorTapeTool Class Reference final
Public Member Functions
ToolType getToolType () const override
bool onPropertyChanged (std::string propertyName) override
void updateTranslation () override
TPropertyGroup * getProperties (int targetType) override
void draw () override
Draws the tool on the viewer.
void mouseMove (const TPointD &pos, const TMouseEvent &) override
void leftButtonDown (const TPointD &pos, const TMouseEvent &) override
void leftButtonDrag (const TPointD &pos, const TMouseEvent &) override
void joinPointToPoint (const TVectorImageP &vi, std::vector< TFilledRegionInf > *fillInfo)
void joinPointToLine (const TVectorImageP &vi, std::vector< TFilledRegionInf > *fillInfo)
void joinLineToLine (const TVectorImageP &vi, std::vector< TFilledRegionInf > *fillInfo)
void rearrangeClosingPoints (const TVectorImageP &vi, std::pair< int, double > &closingPoint, const TPointD &p)
void tapeRect (const TVectorImageP &vi, const TRectD &rect)
int doTape (const TVectorImageP &vi, std::vector< TFilledRegionInf > *fillInformation, bool joinStrokes)
void leftButtonUp (const TPointD &, const TMouseEvent &) override
void onEnter () override
Callback for the mouse entering the viewer area.
void onLeave () override
Callback for the mouse leaving the viewer area.
void onActivate () override
Callback invoked whenever the tool activates.
int getCursorId () const override
Returns the type of cursor used by the tool.
Public Member Functions inherited from TTool
TTool (std::string toolName)
every tool (invoking updateTranslation() for each).
virtual ToolType getToolType () const =0
ToolTargetType getTargetType () const
std::string getName () const
virtual ToolOptionsBox * createOptionsBox ()
void setViewer (Viewer *viewer)
Viewer * getViewer () const
double getPixelSize () const
void invalidate (const TRectD &rect=TRectD())
int pick (const TPointD &p)
bool isPicking () const
virtual void updateTranslation ()
virtual bool preLeftButtonDown ()
virtual void mouseMove (const TPointD &, const TMouseEvent &)
virtual void leftButtonDown (const TPointD &, const TMouseEvent &)
virtual void leftButtonDrag (const TPointD &, const TMouseEvent &)
virtual void leftButtonUp (const TPointD &, const TMouseEvent &)
virtual void leftButtonDoubleClick (const TPointD &, const TMouseEvent &)
virtual void rightButtonDown (const TPointD &, const TMouseEvent &)
virtual bool keyDown (QKeyEvent *)
virtual void onInputText (std::wstring, std::wstring, int, int)
virtual void onSetViewer ()
virtual void onActivate ()
Callback invoked whenever the tool activates.
virtual void onDeactivate ()
Callback for tool deactivation, includes tool switch.
virtual void onImageChanged ()
Notifies changes in the image in use.
virtual void onEnter ()
Callback for the mouse entering the viewer area.
virtual void onLeave ()
Callback for the mouse leaving the viewer area.
virtual void onFrameSwitched ()
virtual void reset ()
virtual void draw ()
Draws the tool on the viewer.
bool isActive () const
Used to know if a tool is active, (used in TextTool only).
void setActive (bool active)
virtual TPropertyGroup * getProperties (int)
virtual bool onPropertyChanged (std::string propertyName)
virtual TSelection * getSelection ()
Returns a pointer to the tool selection.
virtual int getCursorId () const
Returns the type of cursor used by the tool.
virtual bool isEventAcceptable (QEvent *e)
TXsheet * getXsheet () const
Returns a pointer to the actual Xsheet.
int getFrame ()
Returns the actual frame in use.
int getColumnIndex ()
Returns the actual column index.
TStageObjectId getObjectId () const
Returns a pointer to the actual stage object.
void notifyImageChanged ()
void notifyImageChanged (const TFrameId &fid)
images on the level view.
TFrameId getCurrentFid () const
Returns the number of the actual editing frame.
const TAffine & getMatrix () const
void setMatrix (const TAffine &matrix)
TAffine getCurrentColumnMatrix (int frame=-1) const
TAffine getCurrentColumnParentMatrix () const
TAffine getCurrentObjectParentMatrix () const
TAffine getCurrentObjectParentMatrix2 () const
TAffine getColumnMatrix (int index, int frame=-1) const
virtual void updateMatrix ()
virtual void addContextMenuItems (QMenu *menu)
void enable (bool on)
bool isEnabled () const
QString updateEnabled ()
virtual QString updateEnabled (int rowIndex, int columnIndex)
bool isColumnLocked (int columnIndex) const
void resetInputMethod ()
Resets Input Context (IME)
virtual bool isPencilModeActive ()
virtual bool isDragging () const
void setSelectedFrames (const std::set< TFrameId > &selectedFrames)
void tweenSelectedGuideStrokes ()
void tweenGuideStrokeToSelected ()
void flipGuideStrokeDirection (int mode)
Additional Inherited Members
Public Types inherited from TTool
enum ToolType {
GenericTool = 1 , ColumnTool = 2 , LevelReadTool = 4 , LevelWriteTool ,
LevelTool = LevelReadTool | LevelWriteTool
}
Tool editing type.
enum ToolTargetType {
NoTarget = 0x0 , VectorImage = 0x1 , ToonzImage = 0x2 , RasterImage = 0x4 ,
MeshImage = 0x8 , Splines = 0x10 , LevelColumns = 0x20 , MeshColumns = 0x40 ,
EmptyTarget = 0x80 , CommonImages = VectorImage | ToonzImage | RasterImage , AllImages = CommonImages | MeshImage , Vectors = VectorImage | Splines ,
CommonLevels = CommonImages | LevelColumns , MeshLevels = MeshImage | MeshColumns , AllTargets = 0xffffffff
}
Object types the tool can operate on.
typedef TApplication Application
Static Public Member Functions inherited from TTool
static TTool * getTool (std::string toolName, ToolTargetType targetType)
static TApplication * getApplication ()
static void setApplication (TApplication *application)
static TXshCell getImageCell ()
Returns the level-frame pair to be edited by the tool.
static TImage * getImage (bool toBeModified, int subsampling=0)
Returns the image to be edited by the tool.
static TImage * touchImage ()
static void updateToolsPropertiesTranslation ()
static const std::set< TFrameId > & getSelectedFrames ()
Static Public Attributes inherited from TTool
static std::vector< CellOps > m_cellsData
static bool m_isLevelCreated = false
static bool m_isFrameCreated = false
static std::vector< TFrameId > m_oldFids
static std::vector< TFrameId > m_newFids
static bool m_isLevelRenumbererd = false
Protected Member Functions inherited from TTool
void bind (int targetType)
virtual void onSelectedFramesChanged ()
virtual QString disableString ()
Returns a custom reason to disable the tool.
Protected Attributes inherited from TTool
std::string m_name
The tool's name.
Viewer * m_viewer
Tool's current viewer.
TAffine m_matrix
World-to-window reference change affine.
int m_targetType
The tool's image type target.
bool m_enabled
Whether the tool allows user interaction.
bool m_active
bool m_picking
Static Protected Attributes inherited from TTool
static TApplication * m_application = 0
static std::set< TFrameId > m_selectedFrames = std::set<TFrameId>()
Detailed Description
Constructor & Destructor Documentation
VectorTapeTool()
VectorTapeTool::VectorTapeTool () inline
      : TTool("T_Tape")
      , m_secondPoint(false)
      , m_strokeIndex1(-1)
      , m_strokeIndex2(-1)
      , m_w1(-1.0)
      , m_w2(-1.0)
      , m_pixelSize(1)
      , m_draw(false)
      , m_smooth("Smooth", false)  // W_ToolOptions_Smooth
      , m_joinStrokes("JoinStrokes", false)
      , m_mode("Mode")
      , m_type("Type")
      , m_autocloseFactor("Distance", 0.1, 100, 0.5)
      , m_firstTime(true)
      , m_selectionRect()
      , m_startRect() {
    bind(TTool::Vectors);
    m_prop.bind(m_type);
    m_prop.bind(m_mode);
    m_prop.bind(m_autocloseFactor);
    m_prop.bind(m_joinStrokes);
    m_prop.bind(m_smooth);
    m_mode.addValue(POINT2POINT);
    m_mode.addValue(POINT2LINE);
    m_mode.addValue(LINE2LINE);
    m_smooth.setId("Smooth");
    m_type.addValue(NORMAL);
    m_type.addValue(RECT);
    m_mode.setId("Mode");
    m_type.setId("Type");
    m_joinStrokes.setId("JoinVectors");
    m_autocloseFactor.setId("Distance");
  }
Member Function Documentation
doTape()
int VectorTapeTool::doTape (const TVectorImageP & vi, std::vector< TFilledRegionInf > * fillInformation, bool joinStrokes) inline
{
    int type;
    if (!joinStrokes)
      type = l2l;
    else {
      type = (m_w1 == 0.0 || m_w1 == 1.0)
                 ? ((m_w2 == 0.0 || m_w2 == 1.0) ? p2p : p2l)
                 : ((m_w2 == 0.0 || m_w2 == 1.0) ? l2p : l2l);
      if (type == l2p) {
        std::swap(m_strokeIndex1, m_strokeIndex2);
        std::swap(m_w1, m_w2);
        type = p2l;
      }
    }
    switch (type) {
    case p2p:
      joinPointToPoint(vi, fillInformation);
      break;
    case p2l:
      joinPointToLine(vi, fillInformation);
      break;
    case l2l:
      joinLineToLine(vi, fillInformation);
      break;
    default:
      assert(false);
      break;
    }
    return type;
  }
draw()
void VectorTapeTool::draw () inline override virtual
Draws the tool on the viewer.
Reimplemented from TTool.
                       {
    TVectorImageP vi(getImage(false));
    if (!m_draw) return;
    if (!vi) return;
    // TAffine viewMatrix = getViewer()->getViewMatrix();
    // glPushMatrix();
    // tglMultMatrix(viewMatrix);
    if (m_type.getValue() == RECT) {
      if (!m_selectionRect.isEmpty())
        ToolUtils::drawRect(m_selectionRect, TPixel::Black, 0x3F33, true);
      return;
    }
    if (m_strokeIndex1 == -1 || m_strokeIndex1 >= (int)(vi->getStrokeCount()))
      return;
    tglColor(TPixelD(0.1, 0.9, 0.1));
    TStroke *stroke1   = vi->getStroke(m_strokeIndex1);
    TThickPoint point1 = stroke1->getPoint(m_w1);
    // TThickPoint point1 = stroke1->getControlPoint(m_cpIndex1);
    m_pixelSize  = getPixelSize();
    double thick = std::max(6.0 * m_pixelSize, point1.thick);
    tglDrawCircle(point1, thick);
    TThickPoint point2;
    if (m_secondPoint) {
      if (m_strokeIndex2 != -1) {
        TStroke *stroke2 = vi->getStroke(m_strokeIndex2);
        point2           = stroke2->getPoint(m_w2);
        thick            = std::max(6.0 * m_pixelSize, point2.thick);
      } else {
        tglColor(TPixelD(0.6, 0.7, 0.4));
        thick  = 4 * m_pixelSize;
        point2 = m_pos;
      }
      tglDrawCircle(point2, thick);
      tglDrawSegment(point1, point2);
    }
    // glPopMatrix();
  }
References TTool::getImage(), TStroke::getPoint(), and TRectT< T >::isEmpty().
getCursorId()
int VectorTapeTool::getCursorId () const inline override virtual
Returns the type of cursor used by the tool.
See also
For a list of cursor ids cursor.h
Reimplemented from TTool.
{
    int ret = ToolCursor::TapeCursor;
    if (m_type.getValue() == RECT) ret = ret | ToolCursor::Ex_Rectangle;
    if (ToonzCheck::instance()->getChecks() & ToonzCheck::eBlackBg)
      ret = ret | ToolCursor::Ex_Negate;
    return ret;
  }
References ToonzCheck::eBlackBg.
getProperties()
TPropertyGroup * VectorTapeTool::getProperties (int targetType) inline override virtual
Reimplemented from TTool.
{ return &m_prop; }
getToolType()
ToolType VectorTapeTool::getToolType () const inline override virtual
Implements TTool.
{ return TTool::LevelWriteTool; }
joinLineToLine()
void VectorTapeTool::joinLineToLine (const TVectorImageP & vi, std::vector< TFilledRegionInf > * fillInfo) inline
{
    if (TTool::getApplication()->getCurrentObject()->isSpline())
      return;  // Caanot add vectros to spline... Spline can be only one
               // std::vector
    TThickPoint p1 = vi->getStroke(m_strokeIndex1)->getThickPoint(m_w1);
    TThickPoint p2 = vi->getStroke(m_strokeIndex2)->getThickPoint(m_w2);
    UndoAutoclose *autoCloseUndo = 0;
    std::vector<int> v(2);
    v[0] = m_strokeIndex1;
    v[1] = m_strokeIndex2;
    TXshSimpleLevel *level =
        TTool::getApplication()->getCurrentLevel()->getSimpleLevel();
    autoCloseUndo =
        new UndoAutoclose(level, getCurrentFid(), -1, -1, fillInfo, v);
    std::vector<TThickPoint> points(3);
    points[0]          = p1;
    points[1]          = 0.5 * (p1 + p2);
    points[2]          = p2;
    TStroke *auxStroke = new TStroke(points);
    auxStroke->setStyle(TTool::getApplication()->getCurrentLevelStyleIndex());
    auxStroke->outlineOptions() =
        vi->getStroke(m_strokeIndex1)->outlineOptions();
    int pos = vi->addStrokeToGroup(auxStroke, m_strokeIndex1);
    if (pos < 0) return;
    VIStroke *newStroke = vi->getVIStroke(pos);
    autoCloseUndo->m_newStrokePos = pos;
    autoCloseUndo->m_newStroke    = cloneVIStroke(newStroke);
    autoCloseUndo->m_newStrokeId  = vi->getStroke(pos)->getId();
    vi->notifyChangedStrokes(v, std::vector<TStroke *>());
    notifyImageChanged();
    TUndoManager::manager()->add(autoCloseUndo);
  }
joinPointToLine()
void VectorTapeTool::joinPointToLine (const TVectorImageP & vi, std::vector< TFilledRegionInf > * fillInfo) inline
{
    TUndo *undo                  = 0;
    UndoAutoclose *autoCloseUndo = 0;
    if (TTool::getApplication()->getCurrentObject()->isSpline())
      undo =
          new UndoPath(getXsheet()->getStageObject(getObjectId())->getSpline());
    else {
      std::vector<int> v(2);
      v[0] = m_strokeIndex1;
      v[1] = m_strokeIndex2;
      TXshSimpleLevel *level =
          TTool::getApplication()->getCurrentLevel()->getSimpleLevel();
      autoCloseUndo = new UndoAutoclose(level, getCurrentFid(), m_strokeIndex1,
                                        -1, fillInfo, v);
    }
    VIStroke *newStroke;
    newStroke = vi->extendStroke(
        m_strokeIndex1, vi->getStroke(m_strokeIndex2)->getThickPoint(m_w2),
        (m_w1 == 0.0)
            ? 0
            : vi->getStroke(m_strokeIndex1)->getControlPointCount() - 1,
        m_smooth.getValue());
    if (autoCloseUndo) {
      autoCloseUndo->m_newStroke   = cloneVIStroke(newStroke);
      autoCloseUndo->m_newStrokeId = vi->getStroke(m_strokeIndex1)->getId();
      undo                         = autoCloseUndo;
    }
    vi->notifyChangedStrokes(m_strokeIndex1);
    notifyImageChanged();
    TUndoManager::manager()->add(undo);
  }
joinPointToPoint()
void VectorTapeTool::joinPointToPoint (const TVectorImageP & vi, std::vector< TFilledRegionInf > * fillInfo) inline
{
    int minindex = std::min(m_strokeIndex1, m_strokeIndex2);
    int maxindex = std::max(m_strokeIndex1, m_strokeIndex2);
    UndoAutoclose *autoCloseUndo = 0;
    TUndo *undo                  = 0;
    if (TTool::getApplication()->getCurrentObject()->isSpline())
      undo =
          new UndoPath(getXsheet()->getStageObject(getObjectId())->getSpline());
    else {
      TXshSimpleLevel *level =
          TTool::getApplication()->getCurrentLevel()->getSimpleLevel();
      std::vector<int> v(1);
      v[0]          = minindex;
      autoCloseUndo = new UndoAutoclose(level, getCurrentFid(), minindex,
                                        maxindex, fillInfo, v);
    }
    VIStroke *newStroke = vi->joinStroke(
        m_strokeIndex1, m_strokeIndex2,
        (m_w1 == 0.0)
            ? 0
            : vi->getStroke(m_strokeIndex1)->getControlPointCount() - 1,
        (m_w2 == 0.0)
            ? 0
            : vi->getStroke(m_strokeIndex2)->getControlPointCount() - 1,
        m_smooth.getValue());
    if (autoCloseUndo) {
      autoCloseUndo->m_newStroke   = cloneVIStroke(newStroke);
      autoCloseUndo->m_newStrokeId = vi->getStroke(minindex)->getId();
      undo                         = autoCloseUndo;
    }
    vi->notifyChangedStrokes(minindex);
    notifyImageChanged();
    TUndoManager::manager()->add(undo);
  }
leftButtonDown()
void VectorTapeTool::leftButtonDown (const TPointD & pos, const TMouseEvent &) inline override virtual
Reimplemented from TTool.
{
    if (!(TVectorImageP)getImage(false)) return;
    if (m_type.getValue() == RECT) {
      m_startRect = pos;
    } else if (m_strokeIndex1 != -1)
      m_secondPoint = true;
  }
leftButtonDrag()
void VectorTapeTool::leftButtonDrag (const TPointD & pos, const TMouseEvent &) inline override virtual
Reimplemented from TTool.
{
    TVectorImageP vi(getImage(false));
    if (!vi) return;
    if (m_type.getValue() == RECT) {
      m_selectionRect = TRectD(
          std::min(m_startRect.x, pos.x), std::min(m_startRect.y, pos.y),
          std::max(m_startRect.x, pos.x), std::max(m_startRect.y, pos.y));
      invalidate();
      return;
    }
    if (m_strokeIndex1 == -1 || !m_secondPoint) return;
    double minDistance2 = 900 * m_pixelSize;
    int i, strokeNumber = vi->getStrokeCount();
    TStroke *stroke;
    double distance2, outW;
    TPointD point;
    int cpMax;
    m_strokeIndex2 = -1;
    for (i = 0; i < strokeNumber; i++) {
      if (!vi->sameGroup(m_strokeIndex1, i) &&
          (vi->isStrokeGrouped(m_strokeIndex1) || vi->isStrokeGrouped(i)))
        continue;
      stroke = vi->getStroke(i);
      if (m_mode.getValue() != POINT2POINT) {
        if (stroke->getNearestW(pos, outW, distance2) &&
            distance2 < minDistance2) {
          minDistance2   = distance2;
          m_strokeIndex2 = i;
          if (areAlmostEqual(outW, 0.0, 1e-3))
            m_w2 = 0.0;
          else if (areAlmostEqual(outW, 1.0, 1e-3))
            m_w2 = 1.0;
          else
            m_w2 = outW;
        }
      }
      if (!stroke->isSelfLoop()) {
        cpMax = stroke->getControlPointCount() - 1;
        if (!(m_strokeIndex1 == i && (m_w1 == 0.0 || cpMax < 3))) {
          point = stroke->getControlPoint(0);
          if ((distance2 = tdistance2(pos, point)) < minDistance2) {
            minDistance2   = distance2;
            m_strokeIndex2 = i;
            m_w2           = 0.0;
          }
        }
        if (!(m_strokeIndex1 == i && (m_w1 == 1.0 || cpMax < 3))) {
          point = stroke->getControlPoint(cpMax);
          if ((distance2 = tdistance2(pos, point)) < minDistance2) {
            minDistance2   = distance2;
            m_strokeIndex2 = i;
            m_w2           = 1.0;
          }
        }
      }
    }
    m_pos = pos;
    invalidate();
  }
leftButtonUp()
void VectorTapeTool::leftButtonUp (const TPointD & , const TMouseEvent &) inline override virtual
Reimplemented from TTool.
{
    TVectorImageP vi(getImage(true));
    if (vi && m_type.getValue() == RECT) {
      tapeRect(vi, m_selectionRect);
      m_selectionRect = TRectD();
      m_startRect     = TPointD();
      notifyImageChanged();
      invalidate();
      return;
    }
    if (!vi || m_strokeIndex1 == -1 || !m_secondPoint || m_strokeIndex2 == -1) {
      m_strokeIndex1 = -1;
      m_strokeIndex2 = -1;
      m_w1           = -1.0;
      m_w2           = -1.0;
      m_secondPoint  = false;
      return;
    }
    QMutexLocker lock(vi->getMutex());
    m_secondPoint = false;
    std::vector<TFilledRegionInf> *fillInformation =
        new std::vector<TFilledRegionInf>;
    ImageUtils::getFillingInformationOverlappingArea(
        vi, *fillInformation,
        vi->getStroke(m_strokeIndex1)->getBBox() +
            vi->getStroke(m_strokeIndex2)->getBBox());
    doTape(vi, fillInformation, m_joinStrokes.getValue());
    invalidate();
    m_strokeIndex2 = -1;
    m_w1           = -1.0;
    m_w2           = -1.0;
  }
mouseMove()
void VectorTapeTool::mouseMove (const TPointD & pos, const TMouseEvent &) inline override virtual
Reimplemented from TTool.
{
    TVectorImageP vi(getImage(false));
    if (!vi) return;
    // BUTTA e rimetti (Dava problemi con la penna)
    if (!m_draw) return;  // Questa riga potrebbe non essere messa
    // m_draw=true;   //Perche'??? Non basta dargli true in onEnter??
    if (m_type.getValue() == RECT) return;
    double minDistance2 = 10000000000.;
    m_strokeIndex1 = -1;
    m_secondPoint  = false;
    int i, strokeNumber = vi->getStrokeCount();
    TStroke *stroke;
    double distance2, outW;
    TPointD point;
    int cpMax;
    for (i = 0; i < strokeNumber; i++) {
      stroke = vi->getStroke(i);
      if (m_mode.getValue() == LINE2LINE) {
        if (stroke->getNearestW(pos, outW, distance2) &&
            distance2 < minDistance2) {
          minDistance2   = distance2;
          m_strokeIndex1 = i;
          if (areAlmostEqual(outW, 0.0, 1e-3))
            m_w1 = 0.0;
          else if (areAlmostEqual(outW, 1.0, 1e-3))
            m_w1 = 1.0;
          else
            m_w1 = outW;
        }
      } else if (!stroke->isSelfLoop()) {
        point = stroke->getControlPoint(0);
        if ((distance2 = tdistance2(pos, point)) < minDistance2) {
          minDistance2   = distance2;
          m_strokeIndex1 = i;
          m_w1           = 0.0;
          // m_cpIndex1=0;
        }
        cpMax = stroke->getControlPointCount() - 1;
        point = stroke->getControlPoint(cpMax);
        if ((distance2 = tdistance2(pos, point)) < minDistance2) {
          minDistance2   = distance2;
          m_strokeIndex1 = i;
          m_w1           = 1.0;
          // m_cpIndex1=cpMax;
        }
      }
    }
    invalidate();
  }
onActivate()
void VectorTapeTool::onActivate () inline override virtual
Callback invoked whenever the tool activates.
Reimplemented from TTool.
{
    // enable drawing if we are in a scene viewer
    QWidget *focusWidget = QApplication::focusWidget();
    if (focusWidget &&
        QString(focusWidget->metaObject()->className()) == "SceneViewer")
      m_draw = true;
    if (!m_firstTime) return;
    std::wstring s = ::to_wstring(TapeMode.getValue());
    if (s != L"") m_mode.setValue(s);
    s = ::to_wstring(TapeType.getValue());
    if (s != L"") m_type.setValue(s);
    m_autocloseFactor.setValue(AutocloseFactor);
    m_smooth.setValue(TapeSmooth ? 1 : 0);
    m_joinStrokes.setValue(TapeJoinStrokes ? 1 : 0);
    m_firstTime     = false;
    m_selectionRect = TRectD();
    m_startRect     = TPointD();
  }
onEnter()
void VectorTapeTool::onEnter () inline override virtual
Callback for the mouse entering the viewer area.
Reimplemented from TTool.
{
    //      getApplication()->editImage();
    m_draw          = true;
    m_selectionRect = TRectD();
    m_startRect     = TPointD();
  }
onLeave()
void VectorTapeTool::onLeave () inline override virtual
Callback for the mouse leaving the viewer area.
Reimplemented from TTool.
{
    m_draw = false;
    // m_strokeIndex1=-1;
  }
onPropertyChanged()
bool VectorTapeTool::onPropertyChanged (std::string propertyName) inline override virtual
 Does the tasks associated to changes in \p propertyName and returns \p
true; Does the tasks associated to changes in propertyName and returns true.
Reimplemented from TTool.
{
    TapeMode       = ::to_string(m_mode.getValue());
    TapeSmooth     = (int)(m_smooth.getValue());
    std::wstring s = m_type.getValue();
    if (!s.empty()) TapeType = ::to_string(s);
    TapeJoinStrokes = (int)(m_joinStrokes.getValue());
    AutocloseFactor = (double)(m_autocloseFactor.getValue());
    m_selectionRect = TRectD();
    m_startRect     = TPointD();
    if (propertyName == "Distance" &&
        (ToonzCheck::instance()->getChecks() & ToonzCheck::eAutoclose))
      notifyImageChanged();
    return true;
  }
References ToonzCheck::eAutoclose, and TTool::notifyImageChanged().
rearrangeClosingPoints()
void VectorTapeTool::rearrangeClosingPoints (const TVectorImageP & vi, std::pair< int, double > & closingPoint, const TPointD & p) inline
{
    int erasedIndex = std::max(m_strokeIndex1, m_strokeIndex2);
    int joinedIndex = std::min(m_strokeIndex1, m_strokeIndex2);
    if (closingPoint.first == joinedIndex)
      closingPoint.second = vi->getStroke(joinedIndex)->getW(p);
    else if (closingPoint.first == erasedIndex) {
      closingPoint.first  = joinedIndex;
      closingPoint.second = vi->getStroke(joinedIndex)->getW(p);
    } else if (closingPoint.first > erasedIndex)
      closingPoint.first--;
  }
tapeRect()
void VectorTapeTool::tapeRect (const TVectorImageP & vi, const TRectD & rect) inline
{
    std::vector<TFilledRegionInf> *fillInformation =
        new std::vector<TFilledRegionInf>;
    ImageUtils::getFillingInformationOverlappingArea(vi, *fillInformation,
                                                     rect);
    bool initUndoBlock = false;
    std::vector<std::pair<int, double>> startPoints, endPoints;
    getClosingPoints(rect, m_autocloseFactor.getValue(), vi, startPoints,
                     endPoints);
    assert(startPoints.size() == endPoints.size());
    std::vector<TPointD> startP(startPoints.size()), endP(startPoints.size());
    if (!startPoints.empty()) {
      TUndoManager::manager()->beginBlock();
      for (UINT i = 0; i < startPoints.size(); i++) {
        startP[i] = vi->getStroke(startPoints[i].first)
                        ->getPoint(startPoints[i].second);
        endP[i] =
            vi->getStroke(endPoints[i].first)->getPoint(endPoints[i].second);
      }
    }
    for (UINT i = 0; i < startPoints.size(); i++) {
      m_strokeIndex1 = startPoints[i].first;
      m_strokeIndex2 = endPoints[i].first;
      m_w1           = startPoints[i].second;
      m_w2           = endPoints[i].second;
      int type       = doTape(vi, fillInformation, m_joinStrokes.getValue());
      if (type == p2p && m_strokeIndex1 != m_strokeIndex2) {
        for (UINT j = i + 1; j < startPoints.size(); j++) {
          rearrangeClosingPoints(vi, startPoints[j], startP[j]);
          rearrangeClosingPoints(vi, endPoints[j], endP[j]);
        }
      } else if (type == p2l ||
                 (type == p2p && m_strokeIndex1 == m_strokeIndex2)) {
        for (UINT j = i + 1; j < startPoints.size(); j++) {
          if (startPoints[j].first == m_strokeIndex1)
            startPoints[j].second =
                vi->getStroke(m_strokeIndex1)->getW(startP[j]);
          if (endPoints[j].first == m_strokeIndex1)
            endPoints[j].second = vi->getStroke(m_strokeIndex1)->getW(endP[j]);
        }
      }
    }
    if (!startPoints.empty()) TUndoManager::manager()->endBlock();
  }
updateTranslation()
void VectorTapeTool::updateTranslation () inline override virtual
Reimplemented from TTool.
{
    m_smooth.setQStringName(tr("Smooth"));
    m_joinStrokes.setQStringName(tr("Join Vectors"));
    m_autocloseFactor.setQStringName(tr("Distance"));
    m_mode.setQStringName(tr("Mode:"));
    m_mode.setItemUIName(POINT2POINT, tr("Endpoint to Endpoint"));
    m_mode.setItemUIName(POINT2LINE, tr("Endpoint to Line"));
    m_mode.setItemUIName(LINE2LINE, tr("Line to Line"));
    m_type.setQStringName(tr("Type:"));
    m_type.setItemUIName(NORMAL, tr("Normal"));
    m_type.setItemUIName(RECT, tr("Rectangular"));
  }
The documentation for this class was generated from the following file:
E:/opentoonz/toonz/sources/tnztools/vectortapetool.cpp