opentoonz: TTextureMesh Class Reference
TTextureMesh Class Reference final
Public Member Functions
TTextureMesh (const TTextureMesh &)
TTextureMesh & operator= (const TTextureMesh &)
int faceContaining (const TPointD &p) const
bool faceContains (int f, const TPointD &p) const
TRectD getBBox () const
void saveData (TOStream &os) override
void loadData (TIStream &is) override
Public Member Functions inherited from tcg::TriMesh< TTextureVertex, tcg::Edge, tcg::FaceN< 3 > >
TriMesh (int verticesHint)
int addFace (TTextureVertex &v1, TTextureVertex &v2, TTextureVertex &v3)
int addFace (int v1, int v2, int v3)
int otherFaceVertex (int f, int e) const
int otherFaceVertex (int f, int v1, int v2) const
int otherFaceEdge (int f, int v) const
void faceVertices (int f, int &v1, int &v2, int &v3) const
int swapEdge (int e)
Swaps the specified edge in the two adjacent faces.
int collapseEdge (int e)
Collapses the specified edge.
int splitEdge (int e)
Splits the specified edge, inserting a new vertex at the middle.
Public Member Functions inherited from tcg::Mesh< TTextureVertex, tcg::Edge, tcg::FaceN< 3 > >
bool empty () const
void clear ()
int verticesCount () const
int edgesCount () const
int facesCount () const
const vertices_container & vertices () const
vertices_container & vertices ()
const edges_container & edges () const
edges_container & edges ()
const faces_container & faces () const
faces_container & faces ()
int addVertex (const TTextureVertex &v)
int addEdge (const tcg::Edge &e)
int addFace (const tcg::FaceN< 3 > &f)
void removeVertex (int v)
void removeEdge (int e)
void removeFace (int f)
const TTextureVertex & vertex (int v) const
TTextureVertex & vertex (int v)
const tcg::Edge & edge (int e) const
tcg::Edge & edge (int e)
const tcg::FaceN< 3 > & face (int f) const
tcg::FaceN< 3 > & face (int f)
const TTextureVertex & edgeVertex (int e, int i) const
TTextureVertex & edgeVertex (int e, int i)
Returns the i-th vertex in the edge of index e.
const tcg::FaceN< 3 > & edgeFace (int e, int i) const
tcg::FaceN< 3 > & edgeFace (int e, int i)
Returns the i-th face in the edge of index e.
const TTextureVertex & otherEdgeVertex (int e, int v) const
TTextureVertex & otherEdgeVertex (int e, int v)
Retrieves the vertex adjacent to e whose index is not v.
const tcg::FaceN< 3 > & otherEdgeFace (int e, int f) const
tcg::FaceN< 3 > & otherEdgeFace (int e, int f)
Retrieves the face adjacent to e whose index is not f.
int edgeInciding (int v1, int v2, int n=0) const
Returns the edge index of the.
void squeeze ()
Eliminates unused list nodes in the representation of vertices, edges and faces.
Public Member Functions inherited from TSmartObject
TSmartObject (ClassCode classCode)
void addRef ()
void release ()
TINT32 getRefCount () const
Public Member Functions inherited from TPersist
virtual void loadData (TIStream &is)=0
virtual void saveData (TOStream &os)=0
std::string getStreamTag () const
virtual const TPersistDeclaration * getDeclaration () const =0
Additional Inherited Members
Public Types inherited from tcg::Mesh< TTextureVertex, tcg::Edge, tcg::FaceN< 3 > >
typedef TTextureVertex vertex_type
typedef tcg::Edge edge_type
typedef tcg::FaceN< 3 > face_type
typedef list< TTextureVertex > vertices_container
typedef list< tcg::Edge > edges_container
typedef list< tcg::FaceN< 3 > > faces_container
Public Types inherited from TSmartObject
typedef short ClassCode
Public Types inherited from TPersist
typedef TPersist * CreateProc()
Static Public Member Functions inherited from TSmartObject
static TINT32 getInstanceCount (ClassCode code)
Static Public Member Functions inherited from TPersist
static void declare (CreateProc *)
static TPersist * create (const std::string &name)
Protected Attributes inherited from tcg::Mesh< TTextureVertex, tcg::Edge, tcg::FaceN< 3 > >
vertices_container m_vertices
edges_container m_edges
faces_container m_faces
Detailed Description
Constructor & Destructor Documentation
TTextureMesh() [1/2]
TTextureMesh::TTextureMesh ()
: TSmartObject(m_classCode) {}
TTextureMesh() [2/2]
TTextureMesh::TTextureMesh (const TTextureMesh & other)
    : TriMesh_base(other), TSmartObject(m_classCode) {}
Member Function Documentation
faceContaining()
int TTextureMesh::faceContaining (const TPointD & p) const
{
  int f, fCount = facesCount();
  for (f = 0; f < fCount; ++f)
    if (faceContains(f, p)) return f;
  return -1;
}
faceContains()
bool TTextureMesh::faceContains (int f, const TPointD & p) const
{
  int v0, v1, v2;
  this->faceVertices(f, v0, v1, v2);
  const TPointD &p0 = vertex(v0).P();
  const TPointD &p1 = vertex(v1).P();
  const TPointD &p2 = vertex(v2).P();
  bool clockwise = (tcg::point_ops::cross(p2 - p0, p1 - p0) >= 0);
  return ((tcg::point_ops::cross(p - p0, p1 - p0) >= 0) == clockwise) &&
         ((tcg::point_ops::cross(p - p1, p2 - p1) >= 0) == clockwise) &&
         ((tcg::point_ops::cross(p - p2, p0 - p2) >= 0) == clockwise);
}
getBBox()
TRectD TTextureMesh::getBBox () const
{
  // TODO: Should be cached...
  const double max = (std::numeric_limits<double>::max)();
  TRectD result(max, max, -max, -max);
  // Iterate all meshes
  assert(m_vertices.size() == m_vertices.nodesCount());
  int v, vCount = int(m_vertices.size());
  for (v = 0; v != vCount; ++v) {
    const TTextureVertex &vx = m_vertices[v];
    result.x0 = std::min(result.x0, vx.P().x);
    result.y0 = std::min(result.y0, vx.P().y);
    result.x1 = std::max(result.x1, vx.P().x);
    result.y1 = std::max(result.y1, vx.P().y);
  }
  return result;
}
loadData()
void TTextureMesh::loadData (TIStream & is) override virtual
 This is a pure virtual function and must be overridden with a method
that implements the object loading from a stream (i.e take the object's features from a formatted data stream). For example the TStageObject class use his implementation to take the values of the parameters that characterizes a stage object as name, coordinates, etc... from a file. is is an input file stream
Implements TPersist.
{
  typedef tcg::Mesh<vertex_type, edge_type, face_type> mesh_type;
  std::string str;
  int i, size;
  while (is.openChild(str)) {
    if (str == "V") {
      is >> size;
      m_vertices.reserve(size);
      TTextureMesh::vertex_type v;
      for (i = 0; i < size; ++i) {
        is >> v.P().x >> v.P().y;
        mesh_type::addVertex(v);
      }
      is.closeChild();
    } else if (str == "E") {
      is >> size;
      m_edges.reserve(size);
      int v0, v1;
      for (i = 0; i < size; ++i) {
        is >> v0 >> v1;
        mesh_type::addEdge(TTextureMesh::edge_type(v0, v1));
      }
      is.closeChild();
    } else if (str == "F") {
      is >> size;
      m_faces.reserve(size);
      int e[3];
      for (i = 0; i < size; ++i) {
        is >> e[0] >> e[1] >> e[2];
        mesh_type::addFace(TTextureMesh::face_type(e));
      }
      is.closeChild();
    } else if (str == "rigidities") {
      is >> size;
      size = std::min(size, this->verticesCount());
      for (i = 0; i < size; ++i) is >> m_vertices[i].P().rigidity;
      is.closeChild();
    } else {
      assert(false);
      is.skipCurrentTag();
    }
  }
}
References TIStream::closeChild(), TIStream::openChild(), and TIStream::skipCurrentTag().
operator=()
TTextureMesh & TTextureMesh::operator= (const TTextureMesh & other)
{
  TriMesh_base::operator=(other);
  return *this;
}
saveData()
void TTextureMesh::saveData (TOStream & os) override virtual
 This is a pure virtual function and must be overridden with a method
that implements the object saving to a data stream (i.e put the object's features on a formatted data stream). For example the TStageObject class use his implementation to save the values of the parameters that characterizes a stage object as name, coordinates, etc... on a file os is an output file stream.
Implements TPersist.
{
  struct locals {
    static inline bool hasNon1Rigidity(const TTextureMesh &mesh) {
      int v, vCount = int(mesh.verticesCount());
      for (v = 0; v != vCount; ++v)
        if (mesh.vertex(v).P().rigidity != 1.0) return true;
      return false;
    }
  };
  // NOTE: Primitives saved by INDEX iteration is NOT COINCIDENTAL - since
  // the lists' internal linking could have been altered to mismatch the
  // natural indexing referred to by primitives' data.
  if (m_vertices.size() != m_vertices.nodesCount() ||
      m_edges.size() != m_edges.nodesCount() ||
      m_faces.size() != m_faces.nodesCount()) {
    // Ensure the mesh is already squeezed - save a squeezed
    // copy if necessary
    TTextureMesh mesh(*this);
    mesh.squeeze();
    mesh.saveData(os);
    return;
  }
  assert(m_vertices.size() == m_vertices.nodesCount());
  assert(m_edges.size() == m_edges.nodesCount());
  assert(m_faces.size() == m_faces.nodesCount());
  // Store Vertices
  os.openChild("V");
  {
    int vCount = int(m_vertices.size());
    os << vCount;
    for (int v = 0; v != vCount; ++v) {
      TTextureMesh::vertex_type &vx = m_vertices[v];
      os << vx.P().x << vx.P().y;
    }
  }
  os.closeChild();
  // Store Edges
  os.openChild("E");
  {
    int eCount = int(m_edges.size());
    os << eCount;
    for (int e = 0; e != eCount; ++e) {
      TTextureMesh::edge_type &ed = m_edges[e];
      os << ed.vertex(0) << ed.vertex(1);
    }
  }
  os.closeChild();
  // Store Faces
  os.openChild("F");
  {
    int fCount = int(m_faces.size());
    os << fCount;
    for (int f = 0; f != fCount; ++f) {
      TTextureMesh::face_type &fc = m_faces[f];
      int e, eCount = fc.edgesCount();
      for (e = 0; e < eCount; ++e) os << fc.edge(e);
    }
  }
  os.closeChild();
  // Store rigidities
  if (locals::hasNon1Rigidity(*this)) {
    os.openChild("rigidities");
    {
      int vCount = int(m_vertices.size());
      os << vCount;
      for (int v = 0; v != vCount; ++v) os << m_vertices[v].P().rigidity;
    }
    os.closeChild();
  }
}
References TOStream::closeChild(), TOStream::openChild(), saveData(), and tcg::Mesh< V, E, F >::squeeze().
Referenced by saveData().
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/tmeshimage.h
E:/opentoonz/toonz/sources/common/tmeshimage/tmeshimage.cpp