opentoonz: TStageObjectTree Class Reference
TStageObjectTree Class Reference final
#include <tstageobjecttree.h>
Classes
struct TStageObjectTreeImp
Public Member Functions
TStageObject * getStageObject (const TStageObjectId &id, bool create=true)
void insertColumn (int index)
void removeColumn (int index)
void removeStageObject (const TStageObjectId &id)
void insertStageObject (TStageObject *object)
void swapColumns (int i, int j)
void loadData (TIStream &is, TXsheet *xsh)
void loadData (TIStream &is) override
void saveData (TOStream &os, int occupiedColumnCount, TXsheet *xsh)
void saveData (TOStream &os) override
int getStageObjectCount () const
TStageObject * getStageObject (int index) const
TStageObjectId getCurrentCameraId () const
TStageObjectId getCurrentPreviewCameraId () const
void setCurrentCameraId (const TStageObjectId &id)
void setCurrentPreviewCameraId (const TStageObjectId &id)
void invalidateAll ()
void setHandleManager (HandleManager *hm)
TPointD getHandlePos (const TStageObjectId &id, std::string handle, int row) const
int getSplineCount () const
TStageObjectSpline * getSpline (int index) const
TStageObjectSpline * getSplineById (int splineId) const
TStageObjectSpline * createSpline ()
void assignUniqueSplineId (TStageObjectSpline *spline)
void removeSpline (TStageObjectSpline *spline)
bool containsSpline (TStageObjectSpline *) const
void insertSpline (TStageObjectSpline *)
void createGrammar (TXsheet *xsh)
void setGrammar (const TDoubleParamP &param)
TSyntax::Grammar * getGrammar () const
int getCameraCount () const
int getNewGroupId ()
TCamera * getCamera (const TStageObjectId &cameraId)
TCamera * getCamera (int cameraIndex)
TCamera * getCurrentCamera ()
TCamera * getCurrentPreviewCamera ()
void setDagGridDimension (int dim)
int getDagGridDimension () const
Public Member Functions inherited from TPersist
virtual void loadData (TIStream &is)=0
virtual void saveData (TOStream &os)=0
std::string getStreamTag () const
virtual const TPersistDeclaration * getDeclaration () const =0
Additional Inherited Members
Public Types inherited from TPersist
typedef TPersist * CreateProc()
Static Public Member Functions inherited from TPersist
static void declare (CreateProc *)
static TPersist * create (const std::string &name)
Detailed Description
The class TStageObjectTree permits to collect a set of a stage object in a hierarchical tree structure.
Inherits TPersist.
In each tree each index for each type of TStageObjectId is unique.
The class provides a collection of functions that returns stage object tree element, defined in struct TStageObjectTreeImp, and enables manipulation of these.
     Same class methods allows to menage generic stage objects through
specialization, getStageObject(const TStageObjectId &id, bool create= true), or through them tree index, getStageObject(); it's possible to remove or insert stage object in the tree, removeStageObject() and insertStageObject() respectively.
Others methods concerns specific stage object; it's possible to insert or remove directly TStageObjectId::ColumnId using insertColumn() or removeColumn() and swap columns through swapColumns().
The tree cameras, stage object type: TStageObjectId::CameraId, can be manages using specialization, getCamera(const TStageObjectId &cameraId), or tree index, getCamera(int cameraIndex); it's possible to know current camera, getCurrentCameraId() or getCurrentCamera(), and set the tree current camera setCurrentCameraId().
Tree can contains also TStageObjectSpline getSpline(). Spline can be added in tree by using insertSpline(), insert a given spline, or createSpline(), insert a new spline,and remove it by using removeSpline(). It's possible to know if spline is in tree using containsSpline().
The class allows to manage tree stage object handle setHandleManager(), and to know stage object handle position getHandlePos().
Constructor & Destructor Documentation
TStageObjectTree()
TStageObjectTree::TStageObjectTree ()
                                   : m_imp(new TStageObjectTreeImp) {
  getStageObject(TStageObjectId::CameraId(0), true);
  getStageObject(TStageObjectId::TableId, true);
/*
  static bool firstTime = true;
  if(firstTime)
  {
    firstTime = false;
    Grammar*grammar = ExprGrammar::instance();
    grammar->addPattern("leaf", new ParamReferencePattern());
  }
*/
#ifndef NDEBUG
  checkIntegrity();
#endif
}
~TStageObjectTree()
TStageObjectTree::~TStageObjectTree ()
{}
Member Function Documentation
assignUniqueSplineId()
void TStageObjectTree::assignUniqueSplineId (TStageObjectSpline * spline)
Assign a unique id to the passed spline
{
  if (!spline) return;
  spline->setId(m_imp->m_splineCount++);
}
containsSpline()
bool TStageObjectTree::containsSpline (TStageObjectSpline * s) const
 Returns    \e true if \b \e spline is present in the tree,
otherwise returns false.
{
  assert(s->getId() >= 0);
  std::map<int, TStageObjectSpline *> &splines     = m_imp->m_splines;
  std::map<int, TStageObjectSpline *>::iterator it = splines.find(s->getId());
  return it != splines.end() && s == it->second;
}
Referenced by insertSpline(), and removeSpline().
createGrammar()
void TStageObjectTree::createGrammar (TXsheet * xsh)
{
  assert(!m_imp->m_grammar);
  m_imp->m_grammar = createXsheetGrammar(xsh);
  std::map<TStageObjectId, TStageObject *>::iterator it;
  for (it = m_imp->m_pegbarTable.begin(); it != m_imp->m_pegbarTable.end();
       ++it) {
    TStageObject *obj = it->second;
    int c, cCount = TStageObject::T_ChannelCount;
    for (c = 0; c != cCount; ++c)
      obj->getParam((TStageObject::Channel)c)->setGrammar(m_imp->m_grammar);
    if (const PlasticSkeletonDeformationP &sd =
            obj->getPlasticSkeletonDeformation())
      sd->setGrammar(m_imp->m_grammar);
  }
}
createSpline()
TStageObjectSpline * TStageObjectTree::createSpline ()
Create a new spline and add it in stage object tree; returns a pointer to the new spline.
See also
insertSpline() and removeSpline()
{
  TStageObjectSpline *spline = new TStageObjectSpline();
  spline->setId(m_imp->m_splineCount++);
  m_imp->m_splines[spline->getId()] = spline;
  spline->addRef();
  return spline;
}
Referenced by TColumnDataElement::restoreColumn(), and TStageObject::setStatus().
getCamera() [1/2]
TCamera * TStageObjectTree::getCamera (const TStageObjectId & cameraId)
      Returns a pointer to stage object tree camera \b TCamera identified by
TStageObjectId cameraId.
{
  assert(cameraId.isCamera());
  TStageObject *cameraPegbar = getStageObject(cameraId);
  assert(cameraPegbar);
  return cameraPegbar->getCamera();
}
References TStageObject::getCamera(), getStageObject(), and TStageObjectId::isCamera().
getCamera() [2/2]
TCamera * TStageObjectTree::getCamera (int cameraIndex) inline
      Return a pointer to stage object tree camera \b TCamera identified by
index cameraIndex.
See also
getCurrentCamera()
{
    return getCamera(TStageObjectId::CameraId(cameraIndex));
  }
getCameraCount()
int TStageObjectTree::getCameraCount () const
Returns the number of camera objects in the tree.
{ return m_imp->m_cameraCount; }
Referenced by TSceneProperties::cloneCamerasFrom(), OutputSettingsPopup::onCameraChanged(), and OutputSettingsPopup::updateField().
getCurrentCamera()
TCamera * TStageObjectTree::getCurrentCamera () inline
Return a pointer to current stage object tree camera TCamera.
See also
getCamera() and getCurrentCameraId()
{ return getCamera(getCurrentCameraId()); }
Referenced by ToonzScene::getCurrentCamera(), and ToonzScene::renderFrame().
getCurrentCameraId()
TStageObjectId TStageObjectTree::getCurrentCameraId () const
      Returns \b TStageObjectId of stage object tree current camera.
See also
setCurrentCameraId() and getCurrentCamera()
{
  return m_imp->m_currentCameraId;
}
Referenced by StageBuilder::addCell(), EditTool::draw(), TXsheet::getBBox(), TXsheet::getCameraAff(), TTool::getColumnMatrix(), texture_utils::getTextureData(), ToonzScene::loadLevel(), OutputSettingsPopup::onAddPresetButtonPressed(), OutputSettingsPopup::onCameraChanged(), ToonzScene::renderFrame(), OutputSettingsPopup::updateField(), and Stage::visit().
getCurrentPreviewCamera()
TCamera * TStageObjectTree::getCurrentPreviewCamera () inline
{
    return getCamera(getCurrentPreviewCameraId());
  }
getCurrentPreviewCameraId()
TStageObjectId TStageObjectTree::getCurrentPreviewCameraId () const
{
  return m_imp->m_currentPreviewCameraId;
}
getDagGridDimension()
int TStageObjectTree::getDagGridDimension () const
{
  return m_imp->m_dagGridDimension;
}
getGrammar()
TSyntax::Grammar * TStageObjectTree::getGrammar () const
{
  return m_imp->m_grammar;
}
getHandlePos()
TPointD TStageObjectTree::getHandlePos (const TStageObjectId & id, std::string handle, int row) const
 Returns the point position of the handle \b \e handle.
 If an Handle Manager has not been implemented this method returns a
point of coordinates (0,0).
See also
setHandleManager().
{
  if (m_imp->m_handleManager)
    return m_imp->m_handleManager->getHandlePos(id, handle, row);
  else
    return TPointD();
}
getNewGroupId()
int TStageObjectTree::getNewGroupId ()
{ return ++m_imp->m_groupIdCount; }
getSpline()
TStageObjectSpline * TStageObjectTree::getSpline (int index) const
Returns stage object tree spline TStageObjectSpline identified by tree index index.
See also
insertSpline(), createSpline() and removeSpline()
{
  assert(0 <= index && index < getSplineCount());
  std::map<int, TStageObjectSpline *>::iterator it = m_imp->m_splines.begin();
  for (int i = 0; i < index; i++) it++;
  return it->second;
}
References getSplineCount().
Referenced by StageSchematicScene::updateScene().
getSplineById()
TStageObjectSpline * TStageObjectTree::getSplineById (int splineId) const
Returns stage object tree spline TStageObjectSpline identified splineId. Returns 0 if StageObjectTree doesn't contains the spline.
See also
insertSpline(), createSpline() and removeSpline()
{
  std::map<int, TStageObjectSpline *>::iterator it =
      m_imp->m_splines.find(splineId);
  if (it != m_imp->m_splines.end()) return it->second;
  return 0;
}
Referenced by StageObjectsData::storeSplines().
getSplineCount()
int TStageObjectTree::getSplineCount () const
Returns the number of the spline's objects in the tree.
{ return m_imp->m_splines.size(); }
Referenced by getSpline(), and StageSchematicScene::updateScene().
getStageObject() [1/2]
TStageObject * TStageObjectTree::getStageObject (const TStageObjectId & id, bool create = true)
 The method retrieves a stage object with the passed TStageObjectId \b
id, if the second parameter is true it creates the stage object if it doesn't exist in the TStageObjectTree and returns a pointer to it.
{
  std::map<TStageObjectId, TStageObject *> &pegbars     = m_imp->m_pegbarTable;
  std::map<TStageObjectId, TStageObject *>::iterator it = pegbars.find(id);
  if (it != pegbars.end()) {
    TStageObject *pegbar = it->second;
    return pegbar;
  } else if (create) {
    TStageObject *pegbar = new TStageObject(this, id);
    if (id.isColumn()) {
      int index = id.getIndex();
      // mi assicuro che esistano tutte le colonne con indici inferiori
      if (index > 0) getStageObject(TStageObjectId::ColumnId(index - 1));
      // assegno il parent (per una colonna dev'essere la table)
      TStageObjectId parentId = TStageObjectId::TableId;
      pegbar->setParent(parentId);
      // mi assicuro che il padre esista
      getStageObject(parentId);
    } else if (id.isPegbar()) {
      pegbar->setParent(TStageObjectId::TableId);
    } else if (id.isCamera())
      m_imp->m_cameraCount++;
    pegbars[id] = pegbar;
    pegbar->addRef();
#ifndef NDEBUG
    checkIntegrity();
#endif
    return pegbar;
  } else
    return 0L;
}
References TPersist::create(), getStageObject(), and TStageObject::setParent().
Referenced by TStageObject::clone(), TSceneProperties::cloneCamerasFrom(), TSceneProperties::cloneCamerasTo(), getCamera(), getStageObject(), insertColumn(), loadData(), OutputSettingsPopup::onCameraChanged(), TCameraDataElement::restoreCamera(), TStageObjectDataElement::restoreObject(), TStageObject::setParent(), TCameraDataElement::storeCamera(), TStageObjectDataElement::storeObject(), swapColumns(), OutputSettingsPopup::updateField(), StageSchematicScene::updateScene(), and ArrowToolOptionsBox::updateStageObjectComboItems().
getStageObject() [2/2]
TStageObject * TStageObjectTree::getStageObject (int index) const
 Returns a pointer to a generic stage object \b TStageObject of index
index in the stage object tree. Index must be positive and less then the number of the objects.
{
  assert(0 <= index && index < getStageObjectCount());
  std::map<TStageObjectId, TStageObject *>::const_iterator it;
  int i = 0;
  for (it = m_imp->m_pegbarTable.begin();
       it != m_imp->m_pegbarTable.end() && i < index; ++it, ++i) {
  }
  assert(it != m_imp->m_pegbarTable.end());
  return it->second;
}
References getStageObjectCount().
getStageObjectCount()
int TStageObjectTree::getStageObjectCount () const
Returns the numbers of the objects in the tree.
{
  return m_imp->m_pegbarTable.size();
}
Referenced by getStageObject(), and StageSchematicScene::updateScene().
insertColumn()
void TStageObjectTree::insertColumn (int index)
      Inserts in current stage object tree a column object
(TStageObjectId::ColumnId()) with index index.
See also
removeColumn() and insertStageObject()
{
  assert(0 <= index);
#ifndef NDEBUG
  checkIntegrity();
#endif
  TStageObjectId id       = TStageObjectId::ColumnId(index);
  TStageObject *pegbar    = new TStageObject(this, id);
  TStageObjectId parentId = TStageObjectId::TableId;
  pegbar->setParent(parentId);
  // mi assicuro che il padre esista
  getStageObject(parentId);
  // mi assicuro che esistano tutte le colonne di indice inferiore
  for (int k = 0; k < index; k++) getStageObject(TStageObjectId::ColumnId(k));
  std::map<TStageObjectId, TStageObject *> &pegbars = m_imp->m_pegbarTable;
  std::vector<std::pair<TStageObjectId, TStageObject *>> tmp(pegbars.begin(),
                                                             pegbars.end());
  std::vector<std::pair<TStageObjectId, TStageObject *>>::iterator it;
  for (it = tmp.begin(); it != tmp.end(); ++it) {
    TStageObjectId j = it->first;
    if (j.isColumn() && j.getIndex() >= index) {
      it->first = TStageObjectId::ColumnId(j.getIndex() + 1);
      it->second->setId(it->first);
    }
  }
  pegbars.clear();
  pegbars.insert(tmp.begin(), tmp.end());
  pegbars[id] = pegbar;
  pegbar->addRef();
#ifndef NDEBUG
  checkIntegrity();
#endif
}
References getStageObject(), and TStageObject::setParent().
insertSpline()
void TStageObjectTree::insertSpline (TStageObjectSpline * s)
Inserts in the stage object tree the spline spline. If spline is already present it does nothing, otherwise it gets ownership of the spline object.
See also
removeSpline() and createSpline()
{
  assert(s->getId() >= 0);
  std::map<int, TStageObjectSpline *> &splines = m_imp->m_splines;
  if (containsSpline(s)) return;
  splines[s->getId()]  = s;
  m_imp->m_splineCount = std::max(m_imp->m_splineCount, s->getId() + 1);
  s->addRef();
}
References containsSpline().
Referenced by loadData().
insertStageObject()
void TStageObjectTree::insertStageObject (TStageObject * object)
      Inserts in current stage object tree the object \b \e object.
      The \b \e object must exist.
See also
removeStageObject() and insertColumn()
{
  TStageObject *imp = dynamic_cast<TStageObject *>(pegbar);
  assert(imp);
  TStageObjectId id = imp->getId();
  std::map<TStageObjectId, TStageObject *> &pegbars = m_imp->m_pegbarTable;
  assert(pegbars.count(id) == 0);
  pegbars[id] = imp;
  imp->addRef();
  imp->setParent(imp->getParent());
  if (id.isCamera()) m_imp->m_cameraCount++;
#ifndef NDEBUG
  checkIntegrity();
#endif
}
References TStageObject::getId(), TStageObject::getParent(), and TStageObject::setParent().
invalidateAll()
void TStageObjectTree::invalidateAll ()
Calls TStageObject::invalidate() for all objects in the table.
{
  std::map<TStageObjectId, TStageObject *>::iterator it;
  for (it = m_imp->m_pegbarTable.begin(); it != m_imp->m_pegbarTable.end();
       ++it) {
    it->second->invalidate();
  }
}
loadData() [1/2]
void TStageObjectTree::loadData (TIStream & is) inline override virtual
 This is a pure virtual function and must be overridden with a method
that implements the object loading from a stream (i.e take the object's features from a formatted data stream). For example the TStageObject class use his implementation to take the values of the parameters that characterizes a stage object as name, coordinates, etc... from a file. is is an input file stream
Implements TPersist.
{};  // not used
loadData() [2/2]
void TStageObjectTree::loadData (TIStream & is, TXsheet * xsh)
    Retrieves  object's data from a tagged data stream \b \e is.
See also
saveData()
{
  std::string tagName;
  while (is.matchTag(tagName)) {
    if (tagName == "splines") {
      while (!is.eos()) {
        TPersist *p = 0;
        is >> p;
        TStageObjectSpline *spline = dynamic_cast<TStageObjectSpline *>(p);
        insertSpline(spline);
      }
      is.matchEndTag();
    } else if (tagName == "pegbar") {
      std::string idStr = is.getTagAttribute("id");
      if (idStr == "")  // vecchio formato
      {
        is >> idStr;
      }
      TStageObjectId id = toStageObjectId(idStr);
      if (id.isCamera() && is.getTagAttribute("active") == "yes")
        m_imp->m_currentCameraId = id;
      else if (id.isCamera() && is.getTagAttribute("activepreview") == "yes")
        m_imp->m_currentPreviewCameraId = id;
      else if (id.isCamera() && is.getTagAttribute("activeboth") == "yes")
        m_imp->m_currentPreviewCameraId = m_imp->m_currentCameraId = id;
      if (id.isCamera()) {
        if (is.getTagAttribute("columnLocked") == "yes")
          xsh->setCameraColumnLocked(true);
        if (is.getTagAttribute("columnFolded") == "yes")
          xsh->getColumnFan(Orientations::topToBottom())->deactivate(-1);
      }
      TStageObject *pegbar =
          dynamic_cast<TStageObject *>(getStageObject(id, true));
      if (!pegbar)
        throw TException("TStageObjectTree::loadData. can't create the pegbar");
      pegbar->loadData(is);
      if (pegbar->isGrouped() && m_imp->m_groupIdCount < pegbar->getGroupId())
        m_imp->m_groupIdCount = pegbar->getGroupId();
      is.matchEndTag();
      std::string name = pegbar->getName();
    } else if (tagName == "grid_dimension") {
      is >> m_imp->m_dagGridDimension;
      is.matchEndTag();
    } else
      throw TException("pegbartree: unexpected tag : " + tagName);
  }
#ifndef NDEBUG
  checkIntegrity();
#endif
}
References ColumnFan::deactivate(), TIStream::eos(), TXsheet::getColumnFan(), getStageObject(), TIStream::getTagAttribute(), insertSpline(), TIStream::matchEndTag(), and TIStream::matchTag().
removeColumn()
void TStageObjectTree::removeColumn (int index)
      Removes from the current stage object tree the stage object column
(TStageObjectId::ColumnId), of index index. Children of the removed column are linked to the parent of the removed column.
See also
insertColumn() and removeStageObject()
{
  assert(0 <= index);
  TStageObjectId id = TStageObjectId::ColumnId(index);
  std::map<TStageObjectId, TStageObject *> &pegbars = m_imp->m_pegbarTable;
  std::map<TStageObjectId, TStageObject *>::iterator pit;
  pit                           = pegbars.find(id);
  TStageObject *imp             = 0;
  if (pit != pegbars.end()) imp = pit->second;
  if (imp) {
    // i figli della colonna rimossa si attaccano al "nonno"
    TStageObjectId parentId = imp->getParent();
    imp->detachFromParent();
    /* while(! m_children.empty())
{
TStageObject*son = *imp->m_children.begin();
son->setParent(parentId);
}*/
    imp->attachChildrenToParent(parentId);
    imp->release();
  }
  imp = 0;
  pegbars.erase(id);
  std::vector<std::pair<TStageObjectId, TStageObject *>> tmp(pegbars.begin(),
                                                             pegbars.end());
  std::vector<std::pair<TStageObjectId, TStageObject *>>::iterator it;
  for (it = tmp.begin(); it != tmp.end(); ++it) {
    TStageObjectId j = it->first;
    if (j.isColumn() && j.getIndex() > index) {
      it->first = TStageObjectId::ColumnId(j.getIndex() - 1);
      it->second->setId(it->first);
    }
  }
  pegbars.clear();
  pegbars.insert(tmp.begin(), tmp.end());
#ifndef NDEBUG
  checkIntegrity();
#endif
}
References TStageObject::attachChildrenToParent(), TStageObject::detachFromParent(), and TStageObject::getParent().
removeSpline()
void TStageObjectTree::removeSpline (TStageObjectSpline * spline)
Removes from stage object tree the spline spline. It deletes the object.
See also
insertSpline() and createSpline()
{
  assert(spline->getId() >= 0);
  std::map<int, TStageObjectSpline *> &splines = m_imp->m_splines;
  std::map<int, TStageObjectSpline *>::iterator it;
  it = splines.find(spline->getId());
  if (it == splines.end()) return;
  splines.erase(it);
  assert(!containsSpline(spline));
  spline->release();
}
References containsSpline().
removeStageObject()
void TStageObjectTree::removeStageObject (const TStageObjectId & id)
      Remove from current stage object tree the stage object with \b
TStageObjectId id.
It doesn't delete the stage object.
See also
insertStageObject() and removeColumn()
{
  std::map<TStageObjectId, TStageObject *> &pegbars = m_imp->m_pegbarTable;
  assert(pegbars.count(id) > 0);
  TStageObject *obj = pegbars[id];
  obj->attachChildrenToParent(obj->getParent());
  obj->detachFromParent();
  obj->release();
  pegbars.erase(id);
  if (id.isCamera()) m_imp->m_cameraCount--;
#ifndef NDEBUG
  checkIntegrity();
#endif
}
References TStageObject::attachChildrenToParent(), TStageObject::detachFromParent(), and TStageObject::getParent().
saveData() [1/2]
void TStageObjectTree::saveData (TOStream & os) inline override virtual
 This is a pure virtual function and must be overridden with a method
that implements the object saving to a data stream (i.e put the object's features on a formatted data stream). For example the TStageObject class use his implementation to save the values of the parameters that characterizes a stage object as name, coordinates, etc... on a file os is an output file stream.
Implements TPersist.
{};  // not used
saveData() [2/2]
void TStageObjectTree::saveData (TOStream & os, int occupiedColumnCount, TXsheet * xsh)
 Saves object's data (name, center coords, etc ) to a tagged data
stream os saved on a file. This method call iteratively all stage objects in the tree and save their data.
{
  std::map<TStageObjectId, TStageObject *>::iterator it;
  std::map<TStageObjectId, TStageObject *> &pegbars = m_imp->m_pegbarTable;
  if (!m_imp->m_splines.empty()) {
    os.openChild("splines");
    std::map<int, TStageObjectSpline *>::iterator it;
    for (it = m_imp->m_splines.begin(); it != m_imp->m_splines.end(); it++) {
      os << it->second;
    }
    os.closeChild();
  }
  for (it = pegbars.begin(); it != pegbars.end(); ++it) {
    TStageObjectId objectId = it->first;
    TStageObject *pegbar    = it->second;
    if (objectId.isColumn() && objectId.getIndex() >= occupiedColumnCount)
      continue;
    std::map<std::string, std::string> attr;
    attr["id"] = objectId.toString();
    if (objectId == m_imp->m_currentCameraId &&
        objectId == m_imp->m_currentPreviewCameraId)
      attr["activeboth"] = "yes";
    else if (objectId == m_imp->m_currentCameraId)
      attr["active"] = "yes";
    else if (objectId == m_imp->m_currentPreviewCameraId)
      attr["activepreview"] = "yes";
    // Since we don't have a real column and we want the files to open in
    // older versions, we'll store column settings on the camera pegbar
    if ((objectId == m_imp->m_currentCameraId ||
         objectId == m_imp->m_currentPreviewCameraId)) {
      if (xsh->isCameraColumnLocked()) attr["columnLocked"] = "yes";
      if (!xsh->getColumnFan(Orientations::topToBottom())->isActive(-1))
        attr["columnFolded"] = "yes";
    }
    os.openChild("pegbar", attr);
    pegbar->saveData(os);
    os.closeChild();
  }
  os.child("grid_dimension") << (int)m_imp->m_dagGridDimension;
}
References TOStream::child(), TOStream::closeChild(), TXsheet::getColumnFan(), ColumnFan::isActive(), TStageObjectId::isColumn(), TOStream::openChild(), and TStageObjectId::toString().
setCurrentCameraId()
void TStageObjectTree::setCurrentCameraId (const TStageObjectId & id)
      Sets stage object tree current camera to \b TStageObjectId \b id.
See also
getCurrentCameraId()
{
  assert(id.isCamera());
  m_imp->m_currentCameraId = id;
}
Referenced by OutputSettingsPopup::onCameraChanged().
setCurrentPreviewCameraId()
void TStageObjectTree::setCurrentPreviewCameraId (const TStageObjectId & id)
{
  assert(id.isCamera());
  m_imp->m_currentPreviewCameraId = id;
}
setDagGridDimension()
void TStageObjectTree::setDagGridDimension (int dim)
{
  m_imp->m_dagGridDimension = dim;
}
setGrammar()
void TStageObjectTree::setGrammar (const TDoubleParamP & param)
{
  if (m_imp->m_grammar) param->setGrammar(m_imp->m_grammar);
}
setHandleManager()
void TStageObjectTree::setHandleManager (HandleManager * hm)
 Sets the handle manager to be \b \e hm.
 An Handle Manager is an object that implements a method to retrieve
the point position of the handle given its id and its name. See TStageObject::getHandle() for an explanation of what a handle is.
{
  m_imp->m_handleManager = hm;
}
swapColumns()
void TStageObjectTree::swapColumns (int i, int j)
This method swaps column i with column j. Columns i and j must exist.
{
  if (i == j) return;
  if (i > j) std::swap(i, j);
  std::map<TStageObjectId, TStageObject *> &pegbars = m_imp->m_pegbarTable;
  std::map<TStageObjectId, TStageObject *>::iterator iti, itj;
  std::map<TStageObjectId, TStageObject *>::const_iterator end = pegbars.end();
  TStageObjectId idi = TStageObjectId::ColumnId(i);
  TStageObjectId idj = TStageObjectId::ColumnId(j);
  assert(checkId(this, idi));
  assert(checkId(this, idj));
  iti = pegbars.find(idi);
  itj = pegbars.find(idj);
  if (iti == end && itj == end) {
  } else if (iti != end && itj != end) {
    assert(iti->second);
    assert(itj->second);
    std::swap(iti->second, itj->second);
    iti->second->setId(iti->first);
    itj->second->setId(itj->first);
  } else if (iti == end) {
    // iti e' il minore. Se manca iti deve mancare anche itj
    assert(0);
  } else {
    // manca itj, ma iti c'e'. Devo crearne uno per evitare i buchi
    assert(iti != end);
    assert(iti->second);
    assert(itj == end);
    pegbars[idj] = iti->second;
    iti->second->setId(idj);
    pegbars.erase(iti);
    // creo
    getStageObject(idi, true);
  }
  assert(checkId(this, idi));
  assert(checkId(this, idj));
#ifndef NDEBUG
  checkIntegrity();
#endif
}
References getStageObject().
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/toonz/tstageobjecttree.h
E:/opentoonz/toonz/sources/toonzlib/tstageobjecttree.cpp