opentoonz: RasterTapeTool Class Reference
RasterTapeTool Class Reference final
Public Member Functions
ToolType getToolType () const override
void updateTranslation () override
void leftButtonDrag (const TPointD &pos, const TMouseEvent &e) override
bool applyAutoclose (const TToonzImageP &ti, const TRectD &selRect=TRectD(), TStroke *stroke=0)
TRectD interpolateRect (const TRectD &r1, const TRectD &r2, double t)
void multiApplyAutoclose (TFrameId firstFid, TFrameId lastFid, TRectD firstRect, TRectD lastRect, TStroke *firstStroke=0, TStroke *lastStroke=0)
void multiApplyAutoclose (TFrameId firstFrameId, TFrameId lastFrameId)
void leftButtonUp (const TPointD &pos, const TMouseEvent &e) override
void draw () override
Draws the tool on the viewer.
bool onPropertyChanged (std::string propertyName) override
void resetMulti ()
void onImageChanged () override
Notifies changes in the image in use.
void leftButtonDown (const TPointD &pos, const TMouseEvent &) override
void leftButtonDoubleClick (const TPointD &pos, const TMouseEvent &e) override
void mouseMove (const TPointD &pos, const TMouseEvent &e) override
void onEnter () override
Callback for the mouse entering the viewer area.
TPropertyGroup * getProperties (int targetType) override
void onActivate () override
Callback invoked whenever the tool activates.
void onDeactivate () override
Callback for tool deactivation, includes tool switch.
int getCursorId () const override
Returns the type of cursor used by the tool.
void startFreehand (const TPointD &pos)
void freehandDrag (const TPointD &pos)
void closeFreehand (const TPointD &pos)
void addPointPolyline (const TPointD &pos)
Viene aggiunto un punto al vettore m_polyline.
void closePolyline (const TPointD &pos)
void checkSegments (std::vector< TAutocloser::Segment > &segments, TStroke *stroke, const TRasterCM32P &ras, const TPoint &delta)
Elimina i segmenti che non sono contenuti all'interno dello stroke!!!
void multiAutocloseRegion (TStroke *stroke, const TMouseEvent &e)
void doClose (double t, const TImageP &img, const TVectorImageP &firstImage, const TVectorImageP &lastImage)
Public Member Functions inherited from TTool
TTool (std::string toolName)
every tool (invoking updateTranslation() for each).
virtual ToolType getToolType () const =0
ToolTargetType getTargetType () const
std::string getName () const
virtual ToolOptionsBox * createOptionsBox ()
void setViewer (Viewer *viewer)
Viewer * getViewer () const
double getPixelSize () const
void invalidate (const TRectD &rect=TRectD())
int pick (const TPointD &p)
bool isPicking () const
virtual void updateTranslation ()
virtual bool preLeftButtonDown ()
virtual void mouseMove (const TPointD &, const TMouseEvent &)
virtual void leftButtonDown (const TPointD &, const TMouseEvent &)
virtual void leftButtonDrag (const TPointD &, const TMouseEvent &)
virtual void leftButtonUp (const TPointD &, const TMouseEvent &)
virtual void leftButtonDoubleClick (const TPointD &, const TMouseEvent &)
virtual void rightButtonDown (const TPointD &, const TMouseEvent &)
virtual bool keyDown (QKeyEvent *)
virtual void onInputText (std::wstring, std::wstring, int, int)
virtual void onSetViewer ()
virtual void onActivate ()
Callback invoked whenever the tool activates.
virtual void onDeactivate ()
Callback for tool deactivation, includes tool switch.
virtual void onImageChanged ()
Notifies changes in the image in use.
virtual void onEnter ()
Callback for the mouse entering the viewer area.
virtual void onLeave ()
Callback for the mouse leaving the viewer area.
virtual void onFrameSwitched ()
virtual void reset ()
virtual void draw ()
Draws the tool on the viewer.
bool isActive () const
Used to know if a tool is active, (used in TextTool only).
void setActive (bool active)
virtual TPropertyGroup * getProperties (int)
virtual bool onPropertyChanged (std::string propertyName)
virtual TSelection * getSelection ()
Returns a pointer to the tool selection.
virtual int getCursorId () const
Returns the type of cursor used by the tool.
virtual bool isEventAcceptable (QEvent *e)
TXsheet * getXsheet () const
Returns a pointer to the actual Xsheet.
int getFrame ()
Returns the actual frame in use.
int getColumnIndex ()
Returns the actual column index.
TStageObjectId getObjectId () const
Returns a pointer to the actual stage object.
void notifyImageChanged ()
void notifyImageChanged (const TFrameId &fid)
images on the level view.
TFrameId getCurrentFid () const
Returns the number of the actual editing frame.
const TAffine & getMatrix () const
void setMatrix (const TAffine &matrix)
TAffine getCurrentColumnMatrix (int frame=-1) const
TAffine getCurrentColumnParentMatrix () const
TAffine getCurrentObjectParentMatrix () const
TAffine getCurrentObjectParentMatrix2 () const
TAffine getColumnMatrix (int index, int frame=-1) const
virtual void updateMatrix ()
virtual void addContextMenuItems (QMenu *menu)
void enable (bool on)
bool isEnabled () const
QString updateEnabled ()
virtual QString updateEnabled (int rowIndex, int columnIndex)
bool isColumnLocked (int columnIndex) const
void resetInputMethod ()
Resets Input Context (IME)
virtual bool isPencilModeActive ()
virtual bool isDragging () const
void setSelectedFrames (const std::set< TFrameId > &selectedFrames)
void tweenSelectedGuideStrokes ()
void tweenGuideStrokeToSelected ()
void flipGuideStrokeDirection (int mode)
Additional Inherited Members
Public Types inherited from TTool
enum ToolType {
GenericTool = 1 , ColumnTool = 2 , LevelReadTool = 4 , LevelWriteTool ,
LevelTool = LevelReadTool | LevelWriteTool
}
Tool editing type.
enum ToolTargetType {
NoTarget = 0x0 , VectorImage = 0x1 , ToonzImage = 0x2 , RasterImage = 0x4 ,
MeshImage = 0x8 , Splines = 0x10 , LevelColumns = 0x20 , MeshColumns = 0x40 ,
EmptyTarget = 0x80 , CommonImages = VectorImage | ToonzImage | RasterImage , AllImages = CommonImages | MeshImage , Vectors = VectorImage | Splines ,
CommonLevels = CommonImages | LevelColumns , MeshLevels = MeshImage | MeshColumns , AllTargets = 0xffffffff
}
Object types the tool can operate on.
typedef TApplication Application
Static Public Member Functions inherited from TTool
static TTool * getTool (std::string toolName, ToolTargetType targetType)
static TApplication * getApplication ()
static void setApplication (TApplication *application)
static TXshCell getImageCell ()
Returns the level-frame pair to be edited by the tool.
static TImage * getImage (bool toBeModified, int subsampling=0)
Returns the image to be edited by the tool.
static TImage * touchImage ()
static void updateToolsPropertiesTranslation ()
static const std::set< TFrameId > & getSelectedFrames ()
Static Public Attributes inherited from TTool
static std::vector< CellOps > m_cellsData
static bool m_isLevelCreated = false
static bool m_isFrameCreated = false
static std::vector< TFrameId > m_oldFids
static std::vector< TFrameId > m_newFids
static bool m_isLevelRenumbererd = false
Protected Member Functions inherited from TTool
void bind (int targetType)
virtual void onSelectedFramesChanged ()
virtual QString disableString ()
Returns a custom reason to disable the tool.
Protected Attributes inherited from TTool
std::string m_name
The tool's name.
Viewer * m_viewer
Tool's current viewer.
TAffine m_matrix
World-to-window reference change affine.
int m_targetType
The tool's image type target.
bool m_enabled
Whether the tool allows user interaction.
bool m_active
bool m_picking
Static Protected Attributes inherited from TTool
static TApplication * m_application = 0
static std::set< TFrameId > m_selectedFrames = std::set<TFrameId>()
Detailed Description
Constructor & Destructor Documentation
RasterTapeTool()
RasterTapeTool::RasterTapeTool () inline
      : TTool("T_Tape")
      , m_closeType("Type:")                    // W_ToolOptions_CloseType
      , m_distance("Distance:", 1, 100, 10)     // W_ToolOptions_Distance
      , m_angle("Angle:", 1, 180, 60)           // W_ToolOptions_Angle
      , m_inkIndex("Style Index:", L"current")  // W_ToolOptions_InkIndex
      , m_opacity("Opacity:", 1, 255, 255)
      , m_multi("Frame Range", false)  // W_ToolOptions_FrameRange
      , m_selecting(false)
      , m_selectingRect()
      , m_firstRect()
      , m_level(0)
      , m_firstFrameSelected(false)
      , m_isXsheetCell(false)
      , m_currCell(-1, -1)
      , m_firstPos()
      , m_mousePosition()
      , m_thick(0.5)
      , m_stroke(0)
      , m_firstStroke(0)
      , m_firstTime(true) {
    bind(TTool::ToonzImage);
    m_prop.bind(m_closeType);
    m_closeType.addValue(NORMAL_CLOSE);
    m_closeType.addValue(RECT_CLOSE);
    m_closeType.addValue(FREEHAND_CLOSE);
    m_closeType.addValue(POLYLINE_CLOSE);
    m_prop.bind(m_multi);
    m_prop.bind(m_distance);
    m_prop.bind(m_angle);
    m_prop.bind(m_inkIndex);
    m_prop.bind(m_opacity);
    m_multi.setId("FrameRange");
    m_closeType.setId("Type");
  }
Member Function Documentation
addPointPolyline()
void RasterTapeTool::addPointPolyline (const TPointD & pos) inline
Viene aggiunto un punto al vettore m_polyline.
{
    m_firstPos = pos;
    m_polyline.push_back(pos);
  }
applyAutoclose()
bool RasterTapeTool::applyAutoclose (const TToonzImageP & ti, const TRectD & selRect = TRectD(), TStroke * stroke = 0) inline
{
    if (!ti) return false;
    // inizializzo gli AutocloseParameters
    AutocloseParameters params;
    params.m_closingDistance = (int)(m_distance.getValue());
    params.m_spotAngle       = (int)(m_angle.getValue());
    params.m_opacity         = m_opacity.getValue();
    std::string inkString    = ::to_string(m_inkIndex.getValue());
    int inkIndex =
        TTool::getApplication()
            ->getCurrentLevelStyleIndex();  // TApp::instance()->getCurrentPalette()->getStyleIndex();
    if (isInt(inkString)) inkIndex = std::stoi(inkString);
    params.m_inkIndex = inkIndex;
    TPoint delta;
    TRasterCM32P ras, raux = ti->getRaster();
    if (m_closeType.getValue() == RECT_CLOSE && raux && !selRect.isEmpty()) {
      TRectD selArea = selRect;
      if (selRect.x0 > selRect.x1) {
        selArea.x1 = selRect.x0;
        selArea.x0 = selRect.x1;
      }
      if (selRect.y0 > selRect.y1) {
        selArea.y1 = selRect.y0;
        selArea.y0 = selRect.y1;
      }
      TRect myRect(ToonzImageUtils::convertWorldToRaster(selArea, ti));
      ras   = raux->extract(myRect);
      delta = myRect.getP00();
    } else if ((m_closeType.getValue() == FREEHAND_CLOSE ||
                m_closeType.getValue() == POLYLINE_CLOSE) &&
               stroke) {
      TRectD selArea = stroke->getBBox();
      TRect myRect(ToonzImageUtils::convertWorldToRaster(selArea, ti));
      ras   = raux->extract(myRect);
      delta = myRect.getP00();
    } else
      ras = raux;
    if (!ras) return false;
    TAutocloser ac(ras, params.m_closingDistance, params.m_spotAngle,
                   params.m_inkIndex, params.m_opacity);
    std::vector<TAutocloser::Segment> segments;
    ac.compute(segments);
    if ((m_closeType.getValue() == FREEHAND_CLOSE ||
         m_closeType.getValue() == POLYLINE_CLOSE) &&
        stroke)
      checkSegments(segments, stroke, raux, delta);
    std::vector<TAutocloser::Segment> segments2(segments);
    /*-- segmentfalse --*/
    if (segments2.empty()) return false;
    int i;
    if (delta != TPoint(0, 0))
      for (i = 0; i < (int)segments2.size(); i++) {
        segments2[i].first += delta;
        segments2[i].second += delta;
      }
    TTileSetCM32 *tileSet = new TTileSetCM32(raux->getSize());
    for (i = 0; i < (int)segments2.size(); i++) {
      TRect bbox(segments2[i].first, segments2[i].second);
      bbox = bbox.enlarge(2);
      tileSet->add(raux, bbox);
    }
    TXshSimpleLevel *sl =
        TTool::getApplication()->getCurrentLevel()->getSimpleLevel();
    TFrameId id = getCurrentFid();
    TUndoManager::manager()->add(
        new RasterAutocloseUndo(tileSet, params, segments2, sl, id));
    ac.draw(segments);
    ToolUtils::updateSaveBox();
    return true;
  }
checkSegments()
void RasterTapeTool::checkSegments (std::vector< TAutocloser::Segment > & segments, TStroke * stroke, const TRasterCM32P & ras, const TPoint & delta) inline
Elimina i segmenti che non sono contenuti all'interno dello stroke!!!
{
    TVectorImage vi;
    TStroke *app = new TStroke();
    *app         = *stroke;
    app->transform(TTranslation(convert(ras->getCenter())));
    vi.addStroke(app);
    vi.findRegions();
    std::vector<TAutocloser::Segment>::iterator it = segments.begin();
    for (; it < segments.end(); it++) {
      if (it == segments.end()) break;
      int i;
      bool isContained = false;
      for (i = 0; i < (int)vi.getRegionCount(); i++) {
        TRegion *reg = vi.getRegion(i);
        if (reg->contains(convert(it->first + delta)) &&
            reg->contains(convert(it->second + delta))) {
          isContained = true;
          break;
        }
      }
      if (!isContained) {
        it = segments.erase(it);
        if (it != segments.end() && it != segments.begin())
          it--;
        else if (it == segments.end())
          break;
      }
    }
  }
References TVectorImage::addStroke(), TVectorImage::getRegion(), TVectorImage::getRegionCount(), and TStroke::transform().
closeFreehand()
void RasterTapeTool::closeFreehand (const TPointD & pos) inline
Viene chiuso il lazzo (si aggiunge l'ultimo punto ad m_track) e viene creato lo stroke rappresentante il lazzo.
{
    if (m_track.isEmpty()) return;
    double pixelSize2 = getPixelSize() * getPixelSize();
    m_track.add(TThickPoint(m_firstPos, m_thick), pixelSize2);
    m_track.filterPoints();
    double error = (30.0 / 11) * sqrt(pixelSize2);
    m_stroke     = m_track.makeStroke(error);
    m_stroke->setStyle(1);
  }
References StrokeGenerator::add(), StrokeGenerator::filterPoints(), StrokeGenerator::isEmpty(), StrokeGenerator::makeStroke(), and TStroke::setStyle().
closePolyline()
void RasterTapeTool::closePolyline (const TPointD & pos) inline
Agginge l'ultimo pos a m_polyline e chiude la spezzata (aggiunge m_polyline.front() alla fine del vettore)
{
    if (m_polyline.size() <= 1) return;
    if (m_polyline.back() != pos) m_polyline.push_back(pos);
    if (m_polyline.back() != m_polyline.front())
      m_polyline.push_back(m_polyline.front());
    invalidate();
  }
References TTool::invalidate().
doClose()
void RasterTapeTool::doClose (double t, const TImageP & img, const TVectorImageP & firstImage, const TVectorImageP & lastImage) inline
{
    if (t == 0)
      applyAutoclose(img, TRectD(), firstImage->getStroke(0));
    else if (t == 1)
      applyAutoclose(img, TRectD(), lastImage->getStroke(0));
    else {
      assert(firstImage->getStrokeCount() == 1);
      assert(lastImage->getStrokeCount() == 1);
      TVectorImageP vi = TInbetween(firstImage, lastImage).tween(t);
      assert(vi->getStrokeCount() == 1);
      applyAutoclose(img, TRectD(), vi->getStroke(0));
    }
  }
draw()
void RasterTapeTool::draw () inline override virtual
Draws the tool on the viewer.
Reimplemented from TTool.
                       {
    double pixelSize2 = getPixelSize() * getPixelSize();
    m_thick           = sqrt(pixelSize2) / 2.0;
    if (m_closeType.getValue() == RECT_CLOSE) {
      TPixel color = ToonzCheck::instance()->getChecks() & ToonzCheck::eBlackBg
                         ? TPixel32::White
                         : TPixel32::Black;
      if (m_multi.getValue() && m_firstFrameSelected)
        drawRect(m_firstRect, color, 0x3F33, true);
      if (m_selecting || (m_multi.getValue() && !m_firstFrameSelected))
        drawRect(m_selectingRect, color, 0x3F33, true);
    }
    if ((m_closeType.getValue() == FREEHAND_CLOSE ||
         m_closeType.getValue() == POLYLINE_CLOSE) &&
        m_multi.getValue() && m_firstStroke) {
      TPixel color = ToonzCheck::instance()->getChecks() & ToonzCheck::eBlackBg
                         ? TPixel32::White
                         : TPixel32::Black;
      tglColor(color);
      drawStrokeCenterline(*m_firstStroke, 1);
    }
    if (m_closeType.getValue() == POLYLINE_CLOSE && !m_polyline.empty()) {
      TPixel color = ToonzCheck::instance()->getChecks() & ToonzCheck::eBlackBg
                         ? TPixel32::White
                         : TPixel32::Black;
      tglColor(color);
      tglDrawCircle(m_polyline[0], 2);
      glBegin(GL_LINE_STRIP);
      for (UINT i = 0; i < m_polyline.size(); i++) tglVertex(m_polyline[i]);
      tglVertex(m_mousePosition);
      glEnd();
    } else if (m_closeType.getValue() == FREEHAND_CLOSE && !m_track.isEmpty()) {
      TPixel color = ToonzCheck::instance()->getChecks() & ToonzCheck::eBlackBg
                         ? TPixel32::White
                         : TPixel32::Black;
      tglColor(color);
      m_track.drawAllFragments();
    } else if (m_multi.getValue() && m_firstFrameSelected)
      drawCross(m_firstPoint, 5);
  }
References StrokeGenerator::drawAllFragments(), ToonzCheck::eBlackBg, and StrokeGenerator::isEmpty().
freehandDrag()
void RasterTapeTool::freehandDrag (const TPointD & pos) inline
Viene aggiunto pos a m_track e disegnato un altro pezzetto del lazzo.
{
    double pixelSize2 = getPixelSize() * getPixelSize();
    m_track.add(TThickPoint(pos, m_thick), pixelSize2);
  }
References StrokeGenerator::add().
getCursorId()
int RasterTapeTool::getCursorId () const inline override virtual
Returns the type of cursor used by the tool.
See also
For a list of cursor ids cursor.h
Reimplemented from TTool.
{
    int ret = ToolCursor::TapeCursor;
    if (m_closeType.getValue() == FREEHAND_CLOSE)
      ret = ret | ToolCursor::Ex_FreeHand;
    else if (m_closeType.getValue() == POLYLINE_CLOSE)
      ret = ret | ToolCursor::Ex_PolyLine;
    else if (m_closeType.getValue() == RECT_CLOSE)
      ret = ret | ToolCursor::Ex_Rectangle;
    if (ToonzCheck::instance()->getChecks() & ToonzCheck::eBlackBg)
      ret = ret | ToolCursor::Ex_Negate;
    return ret;
  }
References ToonzCheck::eBlackBg.
getProperties()
TPropertyGroup * RasterTapeTool::getProperties (int targetType) inline override virtual
Reimplemented from TTool.
{ return &m_prop; }
getToolType()
ToolType RasterTapeTool::getToolType () const inline override virtual
Implements TTool.
{ return TTool::LevelWriteTool; }
interpolateRect()
TRectD RasterTapeTool::interpolateRect (const TRectD & r1, const TRectD & r2, double t) inline
{
    return TRectD(r1.x0 + (r2.x0 - r1.x0) * t, r1.y0 + (r2.y0 - r1.y0) * t,
                  r1.x1 + (r2.x1 - r1.x1) * t, r1.y1 + (r2.y1 - r1.y1) * t);
  }
leftButtonDoubleClick()
void RasterTapeTool::leftButtonDoubleClick (const TPointD & pos, const TMouseEvent & e) inline override virtual
Reimplemented from TTool.
{
    TToonzImageP ti = TToonzImageP(getImage(true));
    if (m_closeType.getValue() == POLYLINE_CLOSE && ti) {
      closePolyline(pos);
      std::vector<TThickPoint> strokePoints;
      for (UINT i = 0; i < m_polyline.size() - 1; i++) {
        strokePoints.push_back(TThickPoint(m_polyline[i], 1));
        strokePoints.push_back(
            TThickPoint(0.5 * (m_polyline[i] + m_polyline[i + 1]), 1));
      }
      strokePoints.push_back(TThickPoint(m_polyline.back(), 1));
      m_polyline.clear();
      m_stroke = new TStroke(strokePoints);
      assert(m_stroke->getPoint(0) == m_stroke->getPoint(1));
      if (m_multi.getValue())
        multiAutocloseRegion(m_stroke, e);
      else
        applyAutoclose(ti, TRectD(), m_stroke);
      invalidate();
    }
    if (m_stroke) {
      delete m_stroke;
      m_stroke = 0;
    }
  }
leftButtonDown()
void RasterTapeTool::leftButtonDown (const TPointD & pos, const TMouseEvent &) inline override virtual
Reimplemented from TTool.
{
    TToonzImageP ti = TToonzImageP(getImage(true));
    if (!ti) return;
    if (m_closeType.getValue() == RECT_CLOSE) {
      m_selecting        = true;
      m_selectingRect.x0 = pos.x;
      m_selectingRect.y0 = pos.y;
      m_selectingRect.x1 = pos.x + 1;
      m_selectingRect.y1 = pos.y + 1;
      return;
    } else if (m_closeType.getValue() == FREEHAND_CLOSE) {
      startFreehand(pos);
      return;
    } else if (m_closeType.getValue() == POLYLINE_CLOSE) {
      addPointPolyline(pos);
      return;
    } else if (m_closeType.getValue() == NORMAL_CLOSE) {
      if (m_multi.getValue()) {
        TTool::Application *app = TTool::getApplication();
        if (m_firstFrameSelected) {
          multiApplyAutoclose(m_firstFrameId, getFrameId());
          invalidate();
          if (m_isXsheetCell) {
            app->getCurrentColumn()->setColumnIndex(m_currCell.first);
            app->getCurrentFrame()->setFrame(m_currCell.second);
          } else
            app->getCurrentFrame()->setFid(m_veryFirstFrameId);
          resetMulti();
        } else {
          m_isXsheetCell = app->getCurrentFrame()->isEditingScene();
          // if (m_isXsheetCell)
          m_currCell = std::pair<int, int>(getColumnIndex(), getFrame());
          m_firstFrameSelected = true;
          m_firstPoint         = pos;
        }
        invalidate();
        return;
      }
      m_selecting = false;
      applyAutoclose(ti);
      invalidate();
      notifyImageChanged();
    }
  }
leftButtonDrag()
void RasterTapeTool::leftButtonDrag (const TPointD & pos, const TMouseEvent & e) inline override virtual
Reimplemented from TTool.
{
    if (m_closeType.getValue() == RECT_CLOSE) {
      if (!m_selecting) return;
      m_selectingRect.x1 = pos.x;
      m_selectingRect.y1 = pos.y;
      invalidate();
    } else if (m_closeType.getValue() == FREEHAND_CLOSE) {
      freehandDrag(pos);
      invalidate();
    }
  }
leftButtonUp()
void RasterTapeTool::leftButtonUp (const TPointD & pos, const TMouseEvent & e) inline override virtual
Reimplemented from TTool.
{
    TToonzImageP ti = TToonzImageP(getImage(true));
    if (!ti) return;
    /*-- Rect --*/
    if (m_selectingRect.x0 > m_selectingRect.x1)
      std::swap(m_selectingRect.x1, m_selectingRect.x0);
    if (m_selectingRect.y0 > m_selectingRect.y1)
      std::swap(m_selectingRect.y1, m_selectingRect.y0);
    TTool::Application *app = TTool::getApplication();
    m_selecting = false;
    TRasterCM32P ras;
    if (m_closeType.getValue() == RECT_CLOSE) {
      if (m_multi.getValue()) {
        if (m_firstFrameSelected) {
          multiApplyAutoclose(m_firstFrameId, getFrameId(), m_firstRect,
                              m_selectingRect);
          invalidate(m_selectingRect.enlarge(2));
          if (e.isShiftPressed()) {
            m_firstRect    = m_selectingRect;
            m_firstFrameId = getFrameId();
          } else {
            if (m_isXsheetCell) {
              app->getCurrentColumn()->setColumnIndex(m_currCell.first);
              app->getCurrentFrame()->setFrame(m_currCell.second);
            } else
              app->getCurrentFrame()->setFid(m_veryFirstFrameId);
            resetMulti();
          }
        } else {
          m_isXsheetCell = app->getCurrentFrame()->isEditingScene();
          // if (m_isXsheetCell)
          m_currCell = std::pair<int, int>(getColumnIndex(), this->getFrame());
        }
        return;
      }
      /*-- AutoClose --*/
      if (!applyAutoclose(ti, m_selectingRect)) {
        if (m_stroke) {
          delete m_stroke;
          m_stroke = 0;
        }
        invalidate();
        return;
      }
      invalidate();
      notifyImageChanged();
    } else if (m_closeType.getValue() == FREEHAND_CLOSE) {
      closeFreehand(pos);
      if (m_multi.getValue())
        multiAutocloseRegion(m_stroke, e);
      else
        applyAutoclose(ti, TRectD(), m_stroke);
      m_track.clear();
      invalidate();
    }
    if (m_stroke) {
      delete m_stroke;
      m_stroke = 0;
    }
  }
mouseMove()
void RasterTapeTool::mouseMove (const TPointD & pos, const TMouseEvent & e) inline override virtual
Reimplemented from TTool.
{
    if (m_closeType.getValue() == POLYLINE_CLOSE) {
      m_mousePosition = pos;
      invalidate();
    }
  }
multiApplyAutoclose() [1/2]
void RasterTapeTool::multiApplyAutoclose (TFrameId firstFid, TFrameId lastFid, TRectD firstRect, TRectD lastRect, TStroke * firstStroke = 0, TStroke * lastStroke = 0) inline
{
    bool backward = false;
    if (firstFid > lastFid) {
      std::swap(firstFid, lastFid);
      backward = true;
    }
    assert(firstFid <= lastFid);
    std::vector<TFrameId> allFids;
    m_level->getFids(allFids);
    std::vector<TFrameId>::iterator i0 = allFids.begin();
    while (i0 != allFids.end() && *i0 < firstFid) i0++;
    if (i0 == allFids.end()) return;
    std::vector<TFrameId>::iterator i1 = i0;
    while (i1 != allFids.end() && *i1 <= lastFid) i1++;
    assert(i0 < i1);
    std::vector<TFrameId> fids(i0, i1);
    int m = fids.size();
    assert(m > 0);
    TVectorImageP firstImage;
    TVectorImageP lastImage;
    if ((m_closeType.getValue() == FREEHAND_CLOSE ||
         m_closeType.getValue() == POLYLINE_CLOSE) &&
        firstStroke && lastStroke) {
      TStroke *first = new TStroke(*firstStroke);
      TStroke *last  = new TStroke(*lastStroke);
      firstImage     = new TVectorImage();
      lastImage      = new TVectorImage();
      firstImage->addStroke(first);
      lastImage->addStroke(last);
    }
    TUndoManager::manager()->beginBlock();
    for (int i = 0; i < m; ++i) {
      TFrameId fid     = fids[i];
      TToonzImageP img = (TToonzImageP)m_level->getFrame(fid, true);
      if (!img) continue;
      double t = m > 1 ? (double)i / (double)(m - 1) : 0.5;
      if (m_closeType.getValue() == RECT_CLOSE)
        applyAutoclose(img, interpolateRect(firstRect, lastRect, t));
      else if ((m_closeType.getValue() == FREEHAND_CLOSE ||
                m_closeType.getValue() == POLYLINE_CLOSE) &&
               firstStroke && lastStroke)
        doClose(t, img, firstImage, lastImage);
      m_level->getProperties()->setDirtyFlag(true);
    }
    TUndoManager::manager()->endBlock();
    TTool::getApplication()->getCurrentXsheet()->notifyXsheetChanged();
    //      TNotifier::instance()->notify(TLevelChange());
    //      TNotifier::instance()->notify(TStageChange());
  }
multiApplyAutoclose() [2/2]
void RasterTapeTool::multiApplyAutoclose (TFrameId firstFrameId, TFrameId lastFrameId) inline
{
    int r0 = firstFrameId.getNumber();
    int r1 = lastFrameId.getNumber();
    if (r0 > r1) {
      std::swap(r0, r1);
      std::swap(firstFrameId, lastFrameId);
    }
    if ((r1 - r0) < 2) return;
    TUndoManager::manager()->beginBlock();
    for (int i = r0; i <= r1; ++i) {
      TFrameId fid(i);
      TImageP img = m_level->getFrame(fid, true);
      applyAutoclose(img);
    }
    TUndoManager::manager()->endBlock();
    TTool::getApplication()->getCurrentXsheet()->notifyXsheetChanged();
    //      TNotifier::instance()->notify(TLevelChange());
    //      TNotifier::instance()->notify(TStageChange());
  }
multiAutocloseRegion()
void RasterTapeTool::multiAutocloseRegion (TStroke * stroke, const TMouseEvent & e) inline
{
    TTool::Application *app = TTool::getApplication();
    if (m_firstStroke) {
      multiApplyAutoclose(m_firstFrameId, getFrameId(), TRectD(), TRectD(),
                          m_firstStroke, stroke);
      invalidate();
      if (e.isShiftPressed()) {
        delete m_firstStroke;
        m_firstStroke  = new TStroke(*stroke);
        m_firstFrameId = getFrameId();
      } else {
        if (m_isXsheetCell) {
          app->getCurrentColumn()->setColumnIndex(m_currCell.first);
          app->getCurrentFrame()->setFrame(m_currCell.second);
        } else
          app->getCurrentFrame()->setFid(m_veryFirstFrameId);
        resetMulti();
      }
    } else {
      m_isXsheetCell = app->getCurrentFrame()->isEditingScene();
      // if (m_isXsheetCell)
      m_currCell    = std::pair<int, int>(getColumnIndex(), getFrame());
      m_firstStroke = new TStroke(*stroke);
    }
    return;
  }
onActivate()
void RasterTapeTool::onActivate () inline override virtual
Callback invoked whenever the tool activates.
Reimplemented from TTool.
{
    if (m_firstTime) {
      m_closeType.setValue(::to_wstring(AutocloseVectorType.getValue()));
      m_distance.setValue(AutocloseDistance);
      m_angle.setValue(AutocloseAngle);
      m_opacity.setValue(AutocloseOpacity);
      m_multi.setValue(AutocloseRange ? 1 : 0);
      m_firstTime = false;
    }
    //          getApplication()->editImage();
    resetMulti();
  }
onDeactivate()
void RasterTapeTool::onDeactivate () inline override virtual
Callback for tool deactivation, includes tool switch.
Reimplemented from TTool.
{}
onEnter()
void RasterTapeTool::onEnter () inline override virtual
Callback for the mouse entering the viewer area.
Reimplemented from TTool.
{
    //      getApplication()->editImage();
  }
onImageChanged()
void RasterTapeTool::onImageChanged () inline override virtual
Notifies changes in the image in use.
Reimplemented from TTool.
{
    if (!m_multi.getValue()) return;
    TTool::Application *app = TTool::getApplication();
    TXshSimpleLevel *xshl   = 0;
    if (app->getCurrentLevel()->getLevel())
      xshl = app->getCurrentLevel()->getSimpleLevel();
    if (!xshl || m_level.getPointer() != xshl ||
        (m_closeType.getValue() == RECT_CLOSE && m_selectingRect.isEmpty()) ||
        ((m_closeType.getValue() == FREEHAND_CLOSE ||
          m_closeType.getValue() == POLYLINE_CLOSE) &&
         !m_firstStroke))
      resetMulti();
    else if (m_firstFrameId == getFrameId())
      m_firstFrameSelected = false;  // nel caso sono passato allo stato 1 e
                                     // torno all'immagine iniziale, torno allo
                                     // stato iniziale
    else {                           // cambio stato.
      m_firstFrameSelected = true;
      if (m_closeType.getValue() == RECT_CLOSE) {
        assert(!m_selectingRect.isEmpty());
        m_firstRect = m_selectingRect;
      }
    }
  }
References TRectT< T >::isEmpty().
onPropertyChanged()
bool RasterTapeTool::onPropertyChanged (std::string propertyName) inline override virtual
 Does the tasks associated to changes in \p propertyName and returns \p
true; Does the tasks associated to changes in propertyName and returns true.
Reimplemented from TTool.
{
    if (propertyName == m_closeType.getName()) {
      AutocloseVectorType = ::to_string(m_closeType.getValue());
      resetMulti();
    }
    else if (propertyName == m_distance.getName())
      AutocloseDistance = m_distance.getValue();
    else if (propertyName == m_angle.getName())
      AutocloseAngle = m_angle.getValue();
    else if (propertyName == m_inkIndex.getName()) {
    }
    else if (propertyName == m_opacity.getName())
      AutocloseOpacity = m_opacity.getValue();
    else if (propertyName == m_multi.getName()) {
      AutocloseRange = (int)((m_multi.getValue()));
      resetMulti();
    }
    if (ToonzCheck::instance()->getChecks() & ToonzCheck::eAutoclose)
      notifyImageChanged();
    return true;
  }
References ToonzCheck::eAutoclose, and TTool::notifyImageChanged().
resetMulti()
void RasterTapeTool::resetMulti () inline
                    {
    m_firstFrameSelected = false;
    m_firstRect.empty();
    m_firstPoint = TPointD();
    m_selectingRect.empty();
    TTool::Application *app = TTool::getApplication();
    m_level                 = app->getCurrentLevel()->getLevel()
                  ? app->getCurrentLevel()->getSimpleLevel()
                  : 0;
    m_firstFrameId = m_veryFirstFrameId = getFrameId();
    m_firstStroke                       = 0;
  }
startFreehand()
void RasterTapeTool::startFreehand (const TPointD & pos) inline
Viene aggiunto pos a m_track e disegnato il primo pezzetto del lazzo. Viene inizializzato m_firstPos
{
    m_track.clear();
    m_firstPos        = pos;
    double pixelSize2 = getPixelSize() * getPixelSize();
    m_track.add(TThickPoint(pos, m_thick), pixelSize2);
  }
References StrokeGenerator::add(), and StrokeGenerator::clear().
updateTranslation()
void RasterTapeTool::updateTranslation () inline override virtual
Reimplemented from TTool.
{
    m_closeType.setQStringName(tr("Type:"));
    m_closeType.setItemUIName(NORMAL_CLOSE, tr("Normal"));
    m_closeType.setItemUIName(RECT_CLOSE, tr("Rectangular"));
    m_closeType.setItemUIName(FREEHAND_CLOSE, tr("Freehand"));
    m_closeType.setItemUIName(POLYLINE_CLOSE, tr("Polyline"));
    m_distance.setQStringName(tr("Distance:"));
    m_inkIndex.setQStringName(tr("Style Index:"));
    m_inkIndex.setValue(tr("current").toStdWString());
    m_opacity.setQStringName(tr("Opacity:"));
    m_multi.setQStringName(tr("Frame Range"));
    m_angle.setQStringName(tr("Angle:"));
  }
The documentation for this class was generated from the following file:
E:/opentoonz/toonz/sources/tnztools/rastertapetool.cpp