opentoonz: TLevelWriter Class Reference
TLevelWriter Class Reference
Public Member Functions
TLevelWriter (const TFilePath &path, TPropertyGroup *winfo=0)
void setCreator (const QString &creator)
virtual void setPalette (TPalette *)
virtual void setOverwritePaletteFlag (bool overwrite)
virtual void renumberFids (const std::map< TFrameId, TFrameId > &table)
Maps a list of existing level frames to a new list of frames.
virtual void setIconSize (TDimension)
virtual TDimension getIconSize () const
virtual TImageWriterP getFrameWriter (TFrameId)
TImageWriterP getFrameWriter (int f)
TPropertyGroup * getProperties ()
void save (const TLevelP &level)
virtual void saveSoundTrack (TSoundTrack *st)
virtual void setFrameRate (double fps)
TFilePath getFilePath () const
const TContentHistory * getContentHistory () const
TContentHistory * getContentHistory ()
void setContentHistory (TContentHistory *contentHistory)
Public Member Functions inherited from TSmartObject
TSmartObject (ClassCode classCode)
void addRef ()
void release ()
TINT32 getRefCount () const
Static Public Member Functions
static void getSupportedFormats (QStringList &names, bool onlyRenderFormats)
static void define (QString extension, TLevelWriterCreateProc *proc, bool isRenderFormat)
Static Public Member Functions inherited from TSmartObject
static TINT32 getInstanceCount (ClassCode code)
Protected Attributes
TFilePath m_path
double m_frameRate
TPropertyGroup * m_properties
TContentHistory * m_contentHistory
QString m_creator
Additional Inherited Members
Public Types inherited from TSmartObject
typedef short ClassCode
Detailed Description
Constructor & Destructor Documentation
TLevelWriter()
TLevelWriter::TLevelWriter (const TFilePath & path, TPropertyGroup * winfo = 0)
    : TSmartObject(m_classCode)
    , m_path(path)
    , m_properties(prop)
    , m_contentHistory(0) {
  string ext = path.getType();
  if (!prop) m_properties = Tiio::makeWriterProperties(ext);
}
~TLevelWriter()
TLevelWriter::~TLevelWriter () virtual
{
  delete m_properties;
  delete m_contentHistory;
}
Member Function Documentation
define()
void TLevelWriter::define (QString extension, TLevelWriterCreateProc * proc, bool isRenderFormat) static
{
  LevelWriterTable[extension] =
      std::pair<TLevelWriterCreateProc *, bool>(proc, isRenderFormat);
  // cout << "LevelWriter " << extension << " registered" << endl;
}
getContentHistory() [1/2]
TContentHistory * TLevelWriter::getContentHistory () inline
{ return m_contentHistory; }
getContentHistory() [2/2]
const TContentHistory * TLevelWriter::getContentHistory () const inline
{ return m_contentHistory; }
getFilePath()
TFilePath TLevelWriter::getFilePath () const inline
{ return m_path; }
getFrameWriter() [1/2]
TImageWriterP TLevelWriter::getFrameWriter (int f) inline
{ return getFrameWriter(TFrameId(f)); }
getFrameWriter() [2/2]
TImageWriterP TLevelWriter::getFrameWriter (TFrameId fid) virtual
{
  TImageWriterP iw(m_path.withFrame(fid));
  iw->setProperties(m_properties);
  return iw;
}
getIconSize()
virtual TDimension TLevelWriter::getIconSize () const inline virtual
{ return TDimension(); };
getProperties()
TPropertyGroup * TLevelWriter::getProperties () inline
{ return m_properties; }
getSupportedFormats()
void TLevelWriter::getSupportedFormats (QStringList & names, bool onlyRenderFormats) static
{
  for (std::map<QString, std::pair<TLevelWriterCreateProc *, bool>>::iterator
           it = LevelWriterTable.begin();
       it != LevelWriterTable.end(); ++it) {
    if (!onlyRenderFormats || it->second.second) names.push_back(it->first);
  }
}
renumberFids()
void TLevelWriter::renumberFids (const std::map< TFrameId, TFrameId > & table) virtual
Maps a list of existing level frames to a new list of frames.
This function allows an existing level to reorganize (or discard) its disk content. It is typically implemented by TLevelWriters that support random access writing <\I>, which can therefore write new frames on top of an existing level.
This function requires that frames present on disk and in the table be remapped, while frames on disk not in the table be deleted. Eventual frames present in the table but not on disk are ignored.
The default implementation provides renumbering for standard Toonz multi-file level types (levelName.####c.ext), and does nothing if the specified path is not compatible with the multi-file format.
Reimplemented in TLevelWriterTzl.
{
  typedef std::map<TFrameId, TFrameId> Table;
  struct locals {
    static inline QString qstring(const TFilePath &fp) {
      return QString::fromStdWString(fp.getWideString());
    }
    static inline QString temp(const QString &str) {
      return str + QString("_");
    }
  };
  if (m_path.getDots() == "..") {
    try {
      // Extract all image file paths of the level
      QDir parentDir(
          QString::fromStdWString(m_path.getParentDir().getWideString()));
      parentDir.setFilter(QDir::Files);
      QStringList nameFilters;
      // check for both period and underscore
      nameFilters << QString::fromStdWString(m_path.getWideName()) + ".*." +
                         QString::fromStdString(m_path.getType())
                  << QString::fromStdWString(m_path.getWideName()) + "_*." +
                         QString::fromStdString(m_path.getType());
      parentDir.setNameFilters(nameFilters);
      TFilePathSet fpset;
      TSystem::readDirectory(fpset, parentDir, false);  // Could throw
      // Traverse each file, trying to match it with a table entry
      std::vector<QString> storedDstPaths;
      TFilePathSet::iterator st, sEnd(fpset.end());
      for (st = fpset.begin(); st != sEnd; ++st) {
        const QString &src  = locals::qstring(*st);
        const TFrameId &fid = st->getFrame();  // Could throw ! (and I'm quite
                                               // appalled of that  o.o')
        Table::const_iterator dt(table.find(fid));
        if (dt == table.end()) {
          // The frame must be removed
          QFile::remove(src);
        } else {
          if (fid == dt->second) continue;
          // The frame must be renumbered
          const QString &dst = locals::qstring(st->withFrame(dt->second));
          if (!QFile::rename(src, dst)) {
            // Use a temporary file rename to ensure that other frames to be
            // renumbered
            // are not overwritten.
            if (QFile::rename(locals::qstring(*st), locals::temp(dst)))
              storedDstPaths.push_back(dst);
            // If the second rename did not happen, the problem was not on dst,
            // but on src.
            // Alas, it means that rename on source is not possible - skip.
          }
        }
      }
      // At this point, temporaries should be restored to originals. In case the
      // rename of one of those files cannot be finalized, leave the temporary -
      // as
      // it may be impossible to roll back (another frame could have been
      // renumbered
      // to the would-roll-back frame) !
      std::vector<QString>::iterator dt, dEnd(storedDstPaths.end());
      for (dt = storedDstPaths.begin(); dt != dEnd; ++dt)
        QFile::rename(locals::temp(*dt), *dt);
    } catch (...) {
      // Could not read the directory - skip silently
    }
  }
}
References TFilePath::getDots(), TFilePath::getParentDir(), and TFilePath::getType().
save()
void TLevelWriter::save (const TLevelP & level)
{
  for (TLevel::Iterator it = level->begin(); it != level->end(); it++) {
    if (it->second) getFrameWriter(it->first)->save(it->second);
  }
}
saveSoundTrack()
void TLevelWriter::saveSoundTrack (TSoundTrack * st) virtual
{
  return;
  throw TException("The level format doesn't support soundtracks");
}
setContentHistory()
void TLevelWriter::setContentHistory (TContentHistory * contentHistory)
{
  if (contentHistory != m_contentHistory) {
    delete m_contentHistory;
    m_contentHistory = contentHistory;
  }
}
setCreator()
void TLevelWriter::setCreator (const QString & creator) inline
{ m_creator = creator; }
setFrameRate()
void TLevelWriter::setFrameRate (double fps) virtual
{ m_frameRate = fps; }
setIconSize()
virtual void TLevelWriter::setIconSize (TDimension) inline virtual
Reimplemented in TLevelWriterTzl.
{};
setOverwritePaletteFlag()
virtual void TLevelWriter::setOverwritePaletteFlag (bool overwrite) inline virtual
{};
setPalette()
virtual void TLevelWriter::setPalette (TPalette *) inline virtual
{};
Member Data Documentation
m_contentHistory
TContentHistory* TLevelWriter::m_contentHistory protected
m_creator
QString TLevelWriter::m_creator protected
m_frameRate
double TLevelWriter::m_frameRate protected
m_path
TFilePath TLevelWriter::m_path protected
m_properties
TPropertyGroup* TLevelWriter::m_properties protected
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/tlevel_io.h
E:/opentoonz/toonz/sources/common/timage_io/tlevel_io.cpp