opentoonz: TVectorImage Class Reference
TVectorImage Class Reference final
#include <tvectorimage.h>
Classes
class Imp
struct IntersectionBranch
Public Member Functions
TVectorImage (bool loaded=false)
if the vectorimage is loaded from disc, loaded=true
TImage::Type getType () const override
void validateRegions (bool state=false)
bool areValidRegions ()
Get valid regions flags.
TVectorImageP clone () const
Return a clone of image.
TImage * cloneImage () const override
Create a new TImage.
void transform (const TAffine &aff, bool doChangeThickness=false)
Transform a stroke using an affine TAffine.
void putRegion (TRegion *region)
Put a region in the regions' container.
UINT getRegionCount () const
Return the regions' count.
TRegion * getRegion (UINT index) const
Get a region at index position.
TRegion * getRegion (TRegionId) const
Get a region at TRegionId id.
TRegion * findRegion (const TRegion &region) const
returns the region equivalent to region, 0 if does not exists.
void findRegions (const TRectD &rect)
UINT getStrokeCount () const
Return the strokes' count.
TStroke * getStroke (UINT index) const
Get a TStroke stroke at index position.
VIStroke * getVIStroke (UINT index) const
Get a VIStroke stroke at index position.
VIStroke * getStrokeById (int id) const
Get a VIStroke stroke at id.
int getStrokeIndexById (int id) const
Get the stroke index by id.
int getStrokeIndex (TStroke *stroke) const
Get the stroke index by id.
void group (int fromIndex, int count)
Group strokes in the fromIndex - toIndex range.
int ungroup (int index)
Ungroup all the strokes in the group of index index.
bool isStrokeGrouped (UINT index) const
int getGroupDepth (UINT index) const
bool sameSubGroup (int strokeIndex0, int strokeIndex1) const
int getCommonGroupDepth (int strokeIndex0, int strokeIndex1) const
int areDifferentGroup (UINT index1, bool isRegion1, UINT index2, bool isRegion2) const
Return -1 if two object are contained in the same group.
bool sameParentGroupStrokes (UINT index1, UINT index2) const
Return true if two strokes has common parent groups.
bool sameGroup (UINT index1, UINT index2) const
Return true if two objects are contained into the same group.
bool sameGroupStrokeAndRegion (UINT strokeIndex, UINT regionIndex) const
Return true if a stroke and a region have common parent groups.
bool inCurrentGroup (int strokeIndex) const
bool canEnterGroup (int strokeIndex) const
bool selectable (int strokeIndex) const
bool enterGroup (int index)
int exitGroup ()
bool isEnteredGroupStroke (int index) const
bool canMoveStrokes (int strokeIndex, int count, int moveBefore) const
int isInsideGroup () const
int pickGroup (const TPointD &pos) const
int getGroupByStroke (UINT index) const
int getGroupByRegion (UINT index) const
bool getNearestStroke (const TPointD &p, double &outw, UINT &strokeIndex, double &dist2, bool inCurrentGroup=true) const
TStroke * removeStroke (int index, bool doComputeRegions=true)
void removeStrokes (const std::vector< int > &tobeRemoved, bool deleteThem, bool recomputeRegions)
Remove the strokes identified by indexes in the vector toBeRemoved.
void deleteStroke (int index)
Delete the TStroke stroke of index index.
void deleteStroke (VIStroke *stroke)
Delete the VIStroke stroke.
int addStroke (TStroke *, bool discardPoints=true)
int addStrokeToGroup (TStroke *stroke, int strokeIndex)
void replaceStroke (int index, TStroke *newStroke)
Replace the stroke at index index with newStroke.
void insertStrokeAt (VIStroke *vs, int strokeIndex, bool recomputeRegions=true)
Insert a VIStroke vs at index strokeIndex.
void moveStrokes (int fromIndex, int count, int moveBefore)
void findRegions ()
Find regions of a TVectorImage.
TRaster32P render (bool onlyStrokes)
TRegion * getRegion (const TPointD &p)
int fill (const TPointD &p, int styleId, bool onlyEmpty=false)
bool selectFill (const TRectD &selectArea, TStroke *s, int styleId, bool onlyUnfilled, bool fillAreas, bool fillLines)
void areaFill (TStroke *stroke, int styleIndex, bool onlyUnfilled)
Fill all regions contained in the stroke area with styleIndex.
int fillStrokes (const TPointD &p, int newStyleId)
bool isComputedRegionAlmostOnce () const
Return true if computeRegion method was called.
TRectD getBBox () const override
Return the image bounding box in the image coordinate system.
void notifyChangedStrokes (const std::vector< int > &strokeIndexArray, const std::vector< TStroke * > &oldStrokeArray, bool areFlipped=false)
void notifyChangedStrokes (int strokeIndex, TStroke *oldStroke=0, bool isFlipped=false)
Call the following method after stroke modification.
UINT getFillData (std::unique_ptr< IntersectionBranch[]> &v)
void setFillData (std::unique_ptr< IntersectionBranch[]> const &v, UINT size, bool doComputeRegions=true)
void drawAutocloses (const TVectorRenderData &rd) const
void enableRegionComputing (bool enabled, bool notIntersectingStrokes)
void enableMinimizeEdges (bool enabled)
TVectorImageP splitSelected (bool removeFlag)
int mergeImage (const TVectorImageP &img, const TAffine &affine, bool sameStrokeId=true)
Merge the image with the img.
int mergeImage (const TVectorImageP &img, const TAffine &affine, const std::map< int, int > &styleTable, bool sameStrokeId=true)
void mergeImage (const std::vector< const TVectorImage * > &images)
Merge the image with the vector of image images.
void insertImage (const TVectorImageP &img, const std::vector< int > &dstIndices)
Insert the TVectorImageP img.
TVectorImageP splitImage (const std::vector< int > &indices, bool removeFlag)
void getUsedStyles (std::set< int > &styles) const
Return the used styles in the image.
void reassignStyles (std::map< int, int > &table)
Reassign all stroke's style.
void setEdgeColors (int strokeIndex, int leftColorIndex, int rightColorIndex)
void splitStroke (int strokeIndex, const std::vector< DoublePair > &sortedWRanges)
VIStroke * joinStroke (int index1, int index2, int cpIndex1, int cpIndex2, bool isSmooth)
VIStroke * extendStroke (int index, const TThickPoint &p, int cpIndex, bool isSmooth)
TStroke * removeEndpoints (int strokeIndex)
void restoreEndpoints (int index, TStroke *oldStroke)
void setAutocloseTolerance (double val)
Set the autoclose tolerance to the specified value.
double getAutocloseTolerance () const
Return the autoclose tolerance.
void recomputeRegionsIfNeeded ()
void eraseStyleIds (const std::vector< int > styleIds)
TThread::Mutex * getMutex () const
void computeRegion (const TPointD &p, int styleId)
Public Member Functions inherited from TImage
TImage ()
virtual Type getType () const =0
virtual TRectD getBBox () const =0
virtual TImage * cloneImage () const =0
virtual TRasterP raster () const
TPalette * getPalette () const
virtual void setPalette (TPalette *palette)
Public Member Functions inherited from TSmartObject
TSmartObject (ClassCode classCode)
void addRef ()
void release ()
TINT32 getRefCount () const
Static Public Member Functions
static void enableStrokeStyle (int index, bool enable)
Enable or disable the style of a stroke according to the enable param.
static bool isStrokeStyleEnabled (int index)
Return true if the style of the stroke identified by index is enabled.
static void transferStrokeColors (TVectorImageP sourceImage, int sourceStroke, TVectorImageP destinationImage, int destinationStroke)
Static Public Member Functions inherited from TSmartObject
static TINT32 getInstanceCount (ClassCode code)
Public Attributes
std::unique_ptr< Imp > m_imp
Related Functions
(Note that these are not member functions.)
Imp (TVectorImage *vi)
Additional Inherited Members
Public Types inherited from TImage
enum Type {
NONE = 0 , RASTER = 1 , VECTOR = 2 , TOONZ_RASTER = 3 ,
MESH = 4
}
Public Types inherited from TSmartObject
typedef short ClassCode
Detailed Description
TVectorImage: describe a vector image. A vector image is a set of strokes and regions.
Constructor & Destructor Documentation
TVectorImage()
TVectorImage::TVectorImage (bool loaded = false)
if the vectorimage is loaded from disc, loaded=true
                                      : m_imp(new TVectorImage::Imp(this)) {
  if (loaded) m_imp->m_justLoaded = true;
}
Referenced by cloneImage(), and splitSelected().
~TVectorImage()
TVectorImage::~TVectorImage () virtual
{}
Member Function Documentation
addStroke()
int TVectorImage::addStroke (TStroke * stroke, bool discardPoints = true)
Add a stroke at the end of the vector; returns position of the stroke (or -1 if not added)
{
  if (discardPoints) {
    TRectD bBox = stroke->getBBox();
    if (bBox.x0 == bBox.x1 && bBox.y0 == bBox.y1)  // empty stroke: discard
      return -1;
  }
  if (m_imp->m_insideGroup != TGroupId()) {
    int i;
    for (i = m_imp->m_strokes.size() - 1; i >= 0; i--)
      if (m_imp->m_insideGroup.isParentOf(m_imp->m_strokes[i]->m_groupId)) {
        m_imp->insertStrokeAt(
            new VIStroke(stroke, m_imp->m_strokes[i]->m_groupId), i + 1);
        return i + 1;
      }
  }
  TGroupId gid;
  if (m_imp->m_strokes.empty() ||
      m_imp->m_strokes.back()->m_groupId.isGrouped() != 0)
    gid = TGroupId(this, true);
  else
    gid = m_imp->m_strokes.back()->m_groupId;
  m_imp->m_strokes.push_back(new VIStroke(stroke, gid));
  m_imp->m_areValidRegions = false;
  return m_imp->m_strokes.size() - 1;
}
References TStroke::getBBox(), and TRectT< T >::x0.
Referenced by areaFill(), RasterTapeTool::checkSegments(), TImageReaderSvg::load(), and AreaFiller::strokeFill().
addStrokeToGroup()
int TVectorImage::addStrokeToGroup (TStroke * stroke, int strokeIndex)
{
  if (!m_imp->m_strokes[strokeIndex]->m_groupId.isGrouped())
    return addStroke(stroke, true);
  for (int i = m_imp->m_strokes.size() - 1; i >= 0; i--)
    if (m_imp->m_strokes[i]->m_groupId ==
        m_imp->m_strokes[strokeIndex]->m_groupId) {
      m_imp->insertStrokeAt(
          new VIStroke(stroke, m_imp->m_strokes[i]->m_groupId), i + 1);
      return i + 1;
    }
  assert(false);
  return -1;
}
areaFill()
void TVectorImage::areaFill (TStroke * stroke, int styleIndex, bool onlyUnfilled)
Fill all regions contained in the stroke area with styleIndex.
{
  TVectorImage v;
  v.addStroke(stroke);
  v.findRegions();
  for (UINT i = 0; i < v.getRegionCount(); i++)
    for (UINT j = 0; j < getRegionCount(); j++) {
      if (m_imp->m_insideGroup != TGroupId() &&
          !m_imp->m_insideGroup.isParentOf(
              m_imp->m_strokes[getRegion(j)->getEdge(0)->m_index]->m_groupId))
        continue;
      if (v.getRegion(i)->contains(*getRegion(j)))
        getRegion(j)->setStyle(index);
    }
  v.removeStroke(0);
}
References addStroke(), getRegion(), getRegionCount(), and removeStroke().
areDifferentGroup()
int TVectorImage::areDifferentGroup (UINT index1, bool isRegion1, UINT index2, bool isRegion2) const
Return -1 if two object are contained in the same group.
Objects can be strokes or regions: they are identified by index1 and index2. If objects aren't in the same group, the method return the number of equal level into the nested groups.
{
  return m_imp->areDifferentGroup(index1, isRegion1, index2, isRegion2);
}
areValidRegions()
bool TVectorImage::areValidRegions ()
Get valid regions flags.
Call validateRegions() after region/stroke changes
canEnterGroup()
bool TVectorImage::canEnterGroup (int strokeIndex) const
{
  VIStroke *vs = m_imp->m_strokes[strokeIndex];
  if (!vs->m_groupId.isGrouped()) return false;
  return m_imp->m_insideGroup == TGroupId() ||
         vs->m_groupId != m_imp->m_insideGroup;
}
canMoveStrokes()
bool TVectorImage::canMoveStrokes (int strokeIndex, int count, int moveBefore) const
{
  return m_imp->canMoveStrokes(strokeIndex, count, moveBefore);
}
clone()
TVectorImageP TVectorImage::clone () const
Return a clone of image.
{
  return TVectorImageP(cloneImage());
}
References cloneImage().
Referenced by Stage::RasterPainter::onVectorImage().
cloneImage()
TImage * TVectorImage::cloneImage () const override virtual
Create a new TImage.
Implements TImage.
{
  TVectorImage *out = new TVectorImage;
  out->m_imp->m_autocloseTolerance = m_imp->m_autocloseTolerance;
  out->m_imp->m_maxGroupId         = m_imp->m_maxGroupId;
  out->m_imp->m_maxGhostGroupId    = m_imp->m_maxGhostGroupId;
  for (int i = 0; i < (int)m_imp->m_strokes.size(); i++) {
    out->m_imp->m_strokes.push_back(new VIStroke(*(m_imp->m_strokes[i])));
    out->m_imp->m_strokes.back()->m_s->setId(m_imp->m_strokes[i]->m_s->getId());
  }
  m_imp->cloneRegions(*out->m_imp);
  out->setPalette(getPalette());
  out->m_imp->m_computedAlmostOnce = m_imp->m_computedAlmostOnce;
  out->m_imp->m_justLoaded         = m_imp->m_justLoaded;
  return out;
}
References TImage::setPalette(), and TVectorImage().
Referenced by clone().
deleteStroke() [1/2]
void TVectorImage::deleteStroke (int index)
Delete the TStroke stroke of index index.
{
  TStroke *stroke = removeStroke(index);
  delete stroke;
}
References removeStroke().
Referenced by deleteStroke().
deleteStroke() [2/2]
void TVectorImage::deleteStroke (VIStroke * stroke)
Delete the VIStroke stroke.
{
  UINT index = 0;
  for (; index < m_imp->m_strokes.size(); index++)
    if (m_imp->m_strokes[index] == stroke) {
      deleteStroke(index);
      return;
    }
}
References deleteStroke().
enableMinimizeEdges()
void TVectorImage::enableMinimizeEdges (bool enabled)
if enabled, region edges are joined together when possible. for flash render, should be disabled!
{
  m_imp->m_minimizeEdges = enabled;
}
enableRegionComputing()
void TVectorImage::enableRegionComputing (bool enabled, bool notIntersectingStrokes)
Includes a (transformed) copy of imgs in this. If setSelected==true then selects imported strokes. It also includes the color information. Try to assign the same stroke ids (if unused)
{
  m_imp->m_computeRegions         = enabled;
  m_imp->m_notIntersectingStrokes = notIntersectingStrokes;
}
enableStrokeStyle()
void TVectorImage::enableStrokeStyle (int index, bool enable) static
Enable or disable the style of a stroke according to the enable param.
{
  DisabledStrokeStyles &disabledSet = getDisabledStrokeStyleSet();
  if (enable)
    disabledSet.erase(index);
  else
    disabledSet.insert(index);
}
enterGroup()
bool TVectorImage::enterGroup (int index)
{
  VIStroke *vs = getVIStroke(index);
  if (!vs->m_groupId.isGrouped()) return false;
  int newDepth = vs->m_groupId.getCommonParentDepth(m_imp->m_insideGroup) + 1;
  TGroupId newGroupId = vs->m_groupId;
  while (newGroupId.getDepth() > newDepth) newGroupId = newGroupId.getParent();
  if (newGroupId == m_imp->m_insideGroup) return false;
  m_imp->m_insideGroup = newGroupId;
  return true;
}
eraseStyleIds()
void TVectorImage::eraseStyleIds (const std::vector< int > styleIds)
Remove all image strokes and all image regions with style index contained in styleIds vector.
{
  int j;
  for (j = 0; j < (int)styleIds.size(); j++) {
    int styleId = styleIds[j];
    int strokeCount = getStrokeCount();
    int i;
    for (i = strokeCount - 1; i >= 0; i--) {
      TStroke *stroke = getStroke(i);
      if (stroke && stroke->getStyle() == styleId) removeStroke(i);
    }
    int regionCount = getRegionCount();
    for (i = 0; i < regionCount; i++) {
      TRegion *region = getRegion(i);
      if (!region || region->getStyle() != styleId) continue;
      TPointD p;
      if (region->getInternalPoint(p)) fill(p, 0);
    }
  }
}
References fill(), getRegion(), getRegionCount(), getStroke(), getStrokeCount(), TStroke::getStyle(), and removeStroke().
exitGroup()
int TVectorImage::exitGroup ()
{
  if (m_imp->m_insideGroup == TGroupId()) return -1;
  int i, ret = -1;
  for (i = 0; i < (int)m_imp->m_strokes.size(); i++) {
    if (m_imp->m_strokes[i]->m_groupId.getCommonParentDepth(
            m_imp->m_insideGroup) >= m_imp->m_insideGroup.getDepth()) {
      ret = i;
      break;
    }
  }
  assert(i != m_imp->m_strokes.size());
  m_imp->m_insideGroup = m_imp->m_insideGroup.getParent();
  return ret;
}
extendStroke()
VIStroke * TVectorImage::extendStroke (int index, const TThickPoint & p, int cpIndex, bool isSmooth)
{
  if (isSmooth)
    return m_imp->extendStrokeSmoothly(index, p, cpIndex);
  else
    return m_imp->extendStroke(index, p, cpIndex);
}
fill()
int TVectorImage::fill (const TPointD & p, int styleId, bool onlyEmpty = false)
Fill the region which contains p with styleId. it returns the style of the region before filling or -1 if not filled.
{
  TRegion *r = getRegion(p);
  if (onlyEmpty && r && r->getStyle() != 0) return -1;
  if (!m_imp->m_areValidRegions) m_imp->computeRegions();
  return m_imp->fill(p, newStyleId);
}
References getRegion().
Referenced by eraseStyleIds().
fillStrokes()
int TVectorImage::fillStrokes (const TPointD & p, int newStyleId)
Fill the stroke which contains p with newStyleId; it returns the style of stroke before filling or -1 if not filled.
{
  UINT index;
  double outW, dist2;
  if (getNearestStroke(p, outW, index, dist2, true)) {
    double thick = getStroke(index)->getThickPoint(outW).thick * 1.25;
    if (thick < 0.5) thick = 0.5;
    if (dist2 > thick * thick) return -1;
    assert(index >= 0 && index < m_imp->m_strokes.size());
    int ret = m_imp->m_strokes[index]->m_s->getStyle();
    m_imp->m_strokes[index]->m_s->setStyle(styleId);
    return ret;
  }
  return -1;
}
References getNearestStroke(), getStroke(), and TStroke::getThickPoint().
findRegion()
TRegion * TVectorImage::findRegion (const TRegion & region) const
returns the region equivalent to region, 0 if does not exists.
{
  TRegion *ret = 0;
  for (std::vector<TRegion *>::iterator it = m_imp->m_regions.begin();
       it != m_imp->m_regions.end(); ++it)
    if ((ret = (*it)->findRegion(region)) != 0) return ret;
  return 0;
}
References TRegion::findRegion().
findRegions()
void TVectorImage::findRegions ()
Find regions of a TVectorImage.
{
  // for (int i=0; i<(int)m_imp->m_strokes.size(); i++)
  //  {
  //  m_imp->eraseIntersection(i);
  //      m_imp->m_strokes[i]->m_isNewForFill=true;
  //  }
  if (m_imp->m_areValidRegions) return;
  // m_imp->m_regions.clear();
  // compute regions...
  m_imp->computeRegions();  // m_imp->m_strokes, m_imp->m_regions);
}
getAutocloseTolerance()
double TVectorImage::getAutocloseTolerance () const
Return the autoclose tolerance.
{
  return m_imp->m_autocloseTolerance;
}
getBBox()
TRectD TVectorImage::getBBox () const override virtual
Return the image bounding box in the image coordinate system.
Implements TImage.
{
  UINT strokeCount = m_imp->m_strokes.size();
  if (strokeCount == 0) return TRectD();
  TPalette *plt = getPalette();
  TRectD bbox;
  for (UINT i = 0; i < strokeCount; ++i) {
    TRectD r           = m_imp->m_strokes[i]->m_s->getBBox();
    TColorStyle *style = 0;
    if (plt) style = plt->getStyle(m_imp->m_strokes[i]->m_s->getStyle());
    if (dynamic_cast<TRasterImagePatternStrokeStyle *>(style) ||
        dynamic_cast<TVectorImagePatternStrokeStyle *>(
            style))  // con i pattern style, il render a volte taglia sulla bbox
                     // dello stroke....
      // aumento la bbox della meta' delle sue dimensioni:pezzaccia.
      r = r.enlarge(std::max(r.getLx() * 0.25, r.getLy() * 0.25));
    bbox = ((i == 0) ? r : bbox + r);
  }
  return bbox;
}
References TPalette::getStyle().
Referenced by Stage::RasterPainter::onVectorImage(), and render().
getCommonGroupDepth()
int TVectorImage::getCommonGroupDepth (int strokeIndex0, int strokeIndex1) const
{
  if (index0 < 0 || index1 < 0) return 0;
  return m_imp->m_strokes[index0]->m_groupId.getCommonParentDepth(
      m_imp->m_strokes[index1]->m_groupId);
}
getFillData()
UINT TVectorImage::getFillData (std::unique_ptr< IntersectionBranch[]> & v)
{
  return m_imp->getFillData(v);
}
getGroupByRegion()
int TVectorImage::getGroupByRegion (UINT index) const
{
  TRegion *r = m_imp->m_regions[index];
  for (UINT i = 0; i < r->getEdgeCount(); i++)
    if (r->getEdge(i)->m_index >= 0) {
      return m_imp->m_strokes[r->getEdge(i)->m_index]->m_groupId.m_id.back();
    }
  return -1;
}
getGroupByStroke()
int TVectorImage::getGroupByStroke (UINT index) const
{
  VIStroke *viStroke = getVIStroke(index);
  return viStroke->m_groupId.m_id.back();
}
getGroupDepth()
int TVectorImage::getGroupDepth (UINT index) const
Return a value grater of zero if stroke of index index is contained in a group
The returned number is the depth of the nested group containing the stroke.
{
  assert(index < m_imp->m_strokes.size());
  return m_imp->m_strokes[index]->m_groupId.isGrouped();
}
getMutex()
TThread::Mutex * TVectorImage::getMutex () const
{ return m_imp->m_mutex; }
getNearestStroke()
bool TVectorImage::getNearestStroke (const TPointD & p, double & outw, UINT & strokeIndex, double & dist2, bool inCurrentGroup = true) const
get the stroke nearest at point
Note
outw is stroke parameter w in [0,1]
p [input] is point nearest stroke
outw [output] is parameter of minimum in stroke
strokeIndex [output] is index of stroke in vector image
dist2 [output] is the square value of distance
\ret true if a value is found
{
  dist2       = (std::numeric_limits<double>::max)();
  strokeIndex = getStrokeCount();
  outW        = -1;
  double tempdis2, tempPar;
  for (int i = 0; i < (int)m_imp->m_strokes.size(); ++i) {
    if (onlyInCurrentGroup && !inCurrentGroup(i)) continue;
    TStroke *s = m_imp->m_strokes[i]->m_s;
    tempPar    = s->getW(p);
    tempdis2 = tdistance2(TThickPoint(p, 0), s->getThickPoint(tempPar));
    if (tempdis2 < dist2) {
      outW        = tempPar;
      dist2       = tempdis2;
      strokeIndex = i;
    }
  }
  return dist2 < (std::numeric_limits<double>::max)();
}
References getStrokeCount(), TStroke::getThickPoint(), and TStroke::getW().
Referenced by fillStrokes().
getRegion() [1/3]
TRegion * TVectorImage::getRegion (const TPointD & p)
Return the region which contains p, if none regions contains p return 0
{
#ifndef NEW_REGION_FILL
  if (!isComputedRegionAlmostOnce()) return 0;
  if (!m_imp->m_areValidRegions) m_imp->computeRegions();
#endif
  return m_imp->getRegion(p);
}
References isComputedRegionAlmostOnce().
getRegion() [2/3]
TRegion * TVectorImage::getRegion (TRegionId regId) const
Get a region at TRegionId id.
{
  int index = getStrokeIndexById(regId.m_strokeId);
  assert(m_imp->m_areValidRegions);
  TRegion *reg = m_imp->getRegion(regId, index);
  // assert( reg );
  return reg;
}
References getStrokeIndexById().
getRegion() [3/3]
TRegion * TVectorImage::getRegion (UINT index) const
Get a region at index position.
{
  assert(index < m_imp->m_regions.size());
  //  assert( m_imp->m_areValidRegions );
  return m_imp->m_regions[index];
}
Referenced by areaFill(), RasterTapeTool::checkSegments(), eraseStyleIds(), fill(), and AreaFiller::strokeFill().
getRegionCount()
UINT TVectorImage::getRegionCount () const
Return the regions' count.
{
  //  assert( m_imp->m_areValidRegions || m_imp->m_regions.empty());
  return m_imp->m_regions.size();
}
Referenced by areaFill(), RasterTapeTool::checkSegments(), eraseStyleIds(), and AreaFiller::strokeFill().
getStroke()
TStroke * TVectorImage::getStroke (UINT index) const
Get a TStroke stroke at index position.
{
  assert(index < m_imp->m_strokes.size());
  return m_imp->m_strokes[index]->m_s;
}
Referenced by eraseStyleIds(), PaletteCmd::eraseStyles(), fillStrokes(), notifyChangedStrokes(), and reassignStyles().
getStrokeById()
VIStroke * TVectorImage::getStrokeById (int id) const
Get a VIStroke stroke at id.
{
  int n = m_imp->m_strokes.size();
  for (int i = 0; i < n; i++)
    if (m_imp->m_strokes[i]->m_s->getId() == id) return m_imp->m_strokes[i];
  return 0;
}
Referenced by insertImage(), and mergeImage().
getStrokeCount()
UINT TVectorImage::getStrokeCount () const
Return the strokes' count.
{ return m_imp->m_strokes.size(); }
Referenced by eraseStyleIds(), PaletteCmd::eraseStyles(), getNearestStroke(), getUsedStyles(), TImageReaderSvg::load(), mergeImage(), Stage::RasterPainter::onVectorImage(), reassignStyles(), and splitSelected().
getStrokeIndex()
int TVectorImage::getStrokeIndex (TStroke * stroke) const
Get the stroke index by id.
{
  int n = m_imp->m_strokes.size();
  for (int i = 0; i < n; i++)
    if (m_imp->m_strokes[i]->m_s == stroke) return i;
  return -1;
}
getStrokeIndexById()
int TVectorImage::getStrokeIndexById (int id) const
Get the stroke index by id.
{
  int n = m_imp->m_strokes.size();
  for (int i = 0; i < n; i++)
    if (m_imp->m_strokes[i]->m_s->getId() == id) return i;
  return -1;
}
Referenced by getRegion().
getType()
TImage::Type TVectorImage::getType () const inline override virtual
This method must return the type of the image.
See also
Type.
Implements TImage.
{ return VECTOR; }
References TImage::VECTOR.
getUsedStyles()
void TVectorImage::getUsedStyles (std::set< int > & styles) const
Return the used styles in the image.
{
  UINT strokeCount = getStrokeCount();
  UINT i           = 0;
  for (; i < strokeCount; ++i) {
    VIStroke *srcStroke = m_imp->m_strokes[i];
    int styleId         = srcStroke->m_s->getStyle();
    if (styleId != 0) styles.insert(styleId);
    std::list<TEdge *>::const_iterator it = srcStroke->m_edgeList.begin();
    for (; it != srcStroke->m_edgeList.end(); ++it) {
      styleId = (*it)->m_styleId;
      if (styleId != 0) styles.insert(styleId);
    }
  }
}
References getStrokeCount(), and TStroke::getStyle().
getVIStroke()
VIStroke * TVectorImage::getVIStroke (UINT index) const
Get a VIStroke stroke at index position.
{
  assert(index < m_imp->m_strokes.size());
  return m_imp->m_strokes[index];
}
group()
void TVectorImage::group (int fromIndex, int count)
Group strokes in the fromIndex - toIndex range.
Only adjacent strokes can be grouped
{
  int i;
  assert(count >= 0);
  std::vector<int> changedStroke;
  TGroupId parent = TGroupId(this, false);
  for (i = 0; i < count; i++) {
    m_imp->m_strokes[fromIndex + i]->m_groupId =
        TGroupId(parent, m_imp->m_strokes[fromIndex + i]->m_groupId);
    changedStroke.push_back(fromIndex + i);
  }
  m_imp->rearrangeMultiGroup();  // see method's comment
  m_imp->regroupGhosts(changedStroke);
  notifyChangedStrokes(changedStroke, std::vector<TStroke *>(), false);
#ifdef _DEBUG
  m_imp->checkGroups();
#endif
}
References notifyChangedStrokes().
Referenced by TImageReaderSvg::load().
inCurrentGroup()
bool TVectorImage::inCurrentGroup (int strokeIndex) const
{
  return m_imp->inCurrentGroup(strokeIndex);
}
insertImage()
void TVectorImage::insertImage (const TVectorImageP & img, const std::vector< int > & dstIndices)
Insert the TVectorImageP img.
{
  UINT i;
  UINT imageSize = img->getStrokeCount();
  assert(dstIndices.size() == imageSize);
  // img->m_imp->reindexGroups(*m_imp);
  std::vector<int> changedStrokeArray(imageSize);
  std::vector<VIStroke *>::iterator it = m_imp->m_strokes.begin();
  for (i = 0; i < imageSize; i++) {
    assert(i == 0 || dstIndices[i] > dstIndices[i - 1]);
    VIStroke *srcStroke = img->m_imp->m_strokes[i];
    VIStroke *tarStroke = new VIStroke(*srcStroke);
    int strokeId        = srcStroke->m_s->getId();
    if (getStrokeById(strokeId) == 0) tarStroke->m_s->setId(strokeId);
    advance(it, (i == 0) ? dstIndices[i] : dstIndices[i] - dstIndices[i - 1]);
    it = m_imp->m_strokes.insert(it, tarStroke);
    changedStrokeArray[i] = dstIndices[i];
  }
  m_imp->reindexEdges(changedStrokeArray, true);
  notifyChangedStrokes(changedStrokeArray, std::vector<TStroke *>(), false);
  // m_imp->computeRegions();
}
References getStrokeById(), and notifyChangedStrokes().
insertStrokeAt()
void TVectorImage::insertStrokeAt (VIStroke * vs, int strokeIndex, bool recomputeRegions = true)
Insert a VIStroke vs at index strokeIndex.
{
  m_imp->insertStrokeAt(vs, strokeIndex, recomputeRegions);
}
isComputedRegionAlmostOnce()
bool TVectorImage::isComputedRegionAlmostOnce () const
Return true if computeRegion method was called.
{
  return m_imp->m_computedAlmostOnce;
}
Referenced by getRegion().
isEnteredGroupStroke()
bool TVectorImage::isEnteredGroupStroke (int index) const
{
  return m_imp->m_insideGroup.isParentOf(getVIStroke(index)->m_groupId);
}
isInsideGroup()
int TVectorImage::isInsideGroup () const
{
  return m_imp->m_insideGroup.getDepth();
}
isStrokeGrouped()
bool TVectorImage::isStrokeGrouped (UINT index) const inline
{ return getGroupDepth(index) > 0; }
isStrokeStyleEnabled()
bool TVectorImage::isStrokeStyleEnabled (int index) static
Return true if the style of the stroke identified by index is enabled.
{
  return isStrokeStyleEnabled__(index);
}
joinStroke()
VIStroke * TVectorImage::joinStroke (int index1, int index2, int cpIndex1, int cpIndex2, bool isSmooth)
{
  int finalStyle = -1;
  if (index1 > index2) {
    finalStyle = getStroke(index1)->getStyle();
    std::swap(index1, index2);
    std::swap(cpIndex1, cpIndex2);
  }
  /*
if (index1==index2) //selfLoop!
{
if (index1>0 && index1<(int)getStrokeCount()-1 &&
  !getStroke(index1-1)->isSelfLoop() &&
  !getStroke(index1+1)->isSelfLoop())
{
for (UINT i = index1+2; i<getStrokeCount() && !getStroke(i)->isSelfLoop(); i++)
  ;
moveStroke(index1, i-1);
index1 = index2 = i-1;
}
}
*/
  VIStroke *ret;
  if (isSmooth)
    ret = m_imp->joinStrokeSmoothly(index1, index2, cpIndex1, cpIndex2);
  else
    ret = m_imp->joinStroke(index1, index2, cpIndex1, cpIndex2);
  if (finalStyle != -1) getStroke(index1)->setStyle(finalStyle);
  return ret;
}
mergeImage() [1/3]
void TVectorImage::mergeImage (const std::vector< const TVectorImage * > & images)
Merge the image with the vector of image images.
{
  UINT oldSize = getStrokeCount();
  std::vector<int> changedStrokeArray;
  const TVectorImage *img;
  int index;
  if (m_imp->m_insideGroup != TGroupId()) {
    for (index = m_imp->m_strokes.size() - 1; index > -1; index--)
      if (m_imp->m_insideGroup.isParentOf(m_imp->m_strokes[index]->m_groupId))
        break;
    assert(index > -1);
  } else
    index = getStrokeCount() - 1;
  for (UINT j = 0; j < images.size(); ++j) {
    img = images[j];
    if (img->getStrokeCount() == 0) continue;
    img->m_imp->reindexGroups(*m_imp);
    int i = 0;
    /*if (!m_imp->m_strokes.empty() &&
m_imp->m_strokes[index-1]->m_groupId.isGrouped(true)!=0 &&
img->m_imp->m_strokes[0]->m_groupId.isGrouped(true)!=0)
{
assert(false);
TGroupId idNew = m_imp->m_strokes[index]->m_groupId, idOld =
img->m_imp->m_strokes[0]->m_groupId;
for  (;i<(int)img->m_imp->m_strokes.size() &&
img->m_imp->m_strokes[i]->m_groupId==idOld; i++)
img->m_imp->m_strokes[i]->m_groupId==idNew;
}*/
    int strokeCount = img->getStrokeCount();
    m_imp->m_computedAlmostOnce |= img->m_imp->m_computedAlmostOnce;
    for (i = 0; i < strokeCount; i++) {
      VIStroke *srcStroke = img->m_imp->m_strokes[i];
      VIStroke *tarStroke = new VIStroke(*srcStroke);
      int strokeId        = srcStroke->m_s->getId();
      if (getStrokeById(strokeId) == 0) tarStroke->m_s->setId(strokeId);
      index++;
      if (m_imp->m_insideGroup == TGroupId())
        m_imp->m_strokes.push_back(tarStroke);
      else  // if we are inside a group, the images must become part of that
            // group
      {
        tarStroke->m_groupId =
            TGroupId(m_imp->m_insideGroup, tarStroke->m_groupId);
        m_imp->insertStrokeAt(tarStroke, index);
      }
      changedStrokeArray.push_back(index);
    }
  }
  notifyChangedStrokes(changedStrokeArray, std::vector<TStroke *>(), false);
}
References getStrokeById(), getStrokeCount(), and notifyChangedStrokes().
mergeImage() [2/3]
int TVectorImage::mergeImage (const TVectorImageP & img, const TAffine & affine, bool sameStrokeId = true)
Merge the image with the img.
{
  QMutexLocker sl(m_imp->m_mutex);
#ifdef _DEBUG
  checkIntersections();
#endif
  TPalette *tarPlt = getPalette();
  TPalette *srcPlt = img->getPalette();
  assert(tarPlt);
  assert(tarPlt->getPageCount() > 0);
  // merge della palette
  std::map<int, int> styleTable;
  std::set<int> usedStyles;
  img->getUsedStyles(usedStyles);
  // gmt, 16/10/07. Quando si copia e incolla un path su uno stroke succede
  // che la palette dell'immagine sorgente sia vuota. Non mi sembra sbagliato
  // mettere comunque un test qui
  if (srcPlt) mergePalette(tarPlt, styleTable, srcPlt, usedStyles);
  return mergeImage(img, affine, styleTable, sameStrokeId);
}
References TPalette::getPageCount(), and mergeImage().
Referenced by mergeImage().
mergeImage() [3/3]
int TVectorImage::mergeImage (const TVectorImageP & img, const TAffine & affine, const std::map< int, int > & styleTable, bool sameStrokeId = true)
{
  int imageSize = img->getStrokeCount();
  if (imageSize == 0) return 0;
  QMutexLocker sl(m_imp->m_mutex);
  m_imp->m_computedAlmostOnce |= img->m_imp->m_computedAlmostOnce;
  std::vector<int> changedStrokeArray(imageSize);
  img->m_imp->reindexGroups(*m_imp);
  int i;
  int insertAt = 0;
  if (m_imp->m_insideGroup !=
      TGroupId())  // if is inside a group, new image is put in that group.
  {
    TGroupId groupId;
    for (i = m_imp->m_strokes.size() - 1; i >= 0; i--) {
      if (m_imp->m_insideGroup.isParentOf(m_imp->m_strokes[i]->m_groupId)) {
        insertAt = i + 1;
        groupId  = m_imp->m_strokes[i]->m_groupId;
        break;
      }
    }
    if (insertAt != 0) {
      for (i = 0; i < (int)img->m_imp->m_strokes.size(); i++) {
        if (!img->m_imp->m_strokes[i]->m_groupId.isGrouped()) {
          img->m_imp->m_strokes[i]->m_groupId = groupId;
        } else {
          img->m_imp->m_strokes[i]->m_groupId =
              TGroupId(groupId, img->m_imp->m_strokes[i]->m_groupId);
        }
      }
    }
  }
  // si fondono l'ultimo gruppo ghost della vecchia a e il primo della nuova
  else if (!m_imp->m_strokes.empty() &&
           m_imp->m_strokes.back()->m_groupId.isGrouped(true) != 0 &&
           img->m_imp->m_strokes[0]->m_groupId.isGrouped(true) != 0) {
    TGroupId idNew = m_imp->m_strokes.back()->m_groupId,
             idOld = img->m_imp->m_strokes[0]->m_groupId;
    for (i = 0; i < (int)img->m_imp->m_strokes.size() &&
                img->m_imp->m_strokes[i]->m_groupId == idOld;
         i++)
      img->m_imp->m_strokes[i]->m_groupId = idNew;
  }
  // merge dell'immagine
  std::map<int, int>::const_iterator styleTableIt;
  int oldSize = getStrokeCount();
  for (i = 0; i < imageSize; i++) {
    VIStroke *srcStroke = img->m_imp->m_strokes[i];
    VIStroke *tarStroke = new VIStroke(*srcStroke, sameStrokeId);
    int styleId;
    // cambio i colori delle regioni
    std::list<TEdge *>::const_iterator it   = tarStroke->m_edgeList.begin(),
                                       it_e = tarStroke->m_edgeList.end();
    for (; it != it_e; ++it) {
      int styleId  = (*it)->m_styleId;
      styleTableIt = styleTable.find(styleId);
      assert(styleTableIt != styleTable.end());
      if (styleTableIt != styleTable.end())
        (*it)->m_styleId = styleTableIt->second;
    }
    tarStroke->m_s->transform(affine, true);
    int strokeId = srcStroke->m_s->getId();
    if (getStrokeById(strokeId) == 0) tarStroke->m_s->setId(strokeId);
    // cambio i colori dello stroke
    styleId      = srcStroke->m_s->getStyle();
    styleTableIt = styleTable.find(styleId);
    assert(styleTableIt != styleTable.end());
    if (styleTableIt != styleTable.end())
      tarStroke->m_s->setStyle(styleTableIt->second);
    if (insertAt == 0) {
      m_imp->m_strokes.push_back(tarStroke);
      changedStrokeArray[i] = oldSize + i;
    } else {
      std::vector<VIStroke *>::iterator it = m_imp->m_strokes.begin();
      advance(it, insertAt + i);
      m_imp->m_strokes.insert(it, tarStroke);
      changedStrokeArray[i] = insertAt + i;
    }
  }
  if (insertAt > 0) {
    // for (i=changedStrokeArray.back()+1; i<m_imp->m_strokes.size(); i++)
    //  changedStrokeArray.push_back(i);
    m_imp->reindexEdges(changedStrokeArray, true);
  }
  notifyChangedStrokes(changedStrokeArray, std::vector<TStroke *>(), false);
#ifdef _DEBUG
  checkIntersections();
#endif
  return insertAt;
}
moveStrokes()
void TVectorImage::moveStrokes (int fromIndex, int count, int moveBefore)
Move count strokes starting from fromIndex before the stroke identified by the moveBefore index.
{
#ifdef _DEBUG
  m_imp->checkGroups();
#endif
  m_imp->moveStrokes(fromIndex, count, moveBefore, true);
#ifdef _DEBUG
  m_imp->checkGroups();
#endif
}
notifyChangedStrokes() [1/2]
void TVectorImage::notifyChangedStrokes (const std::vector< int > & strokeIndexArray, const std::vector< TStroke * > & oldStrokeArray, bool areFlipped = false)
Call the following method after stroke modification
Note
you must specify, using the second argument, whether the modification was a reflection
{
  std::vector<TStroke *> aux;
  /*
if (oldStrokeArray.empty())
{
  for (int i=0; i<(int)strokeIndexArray.size(); i++)
    {
          TStroke *s = getStroke(strokeIndexArray[i]);
    aux.push_back(s);
          }
m_imp->notifyChangedStrokes(strokeIndexArray, aux, areFlipped);
  }
else*/
  m_imp->notifyChangedStrokes(strokeIndexArray, oldStrokeArray, areFlipped);
}
Referenced by group(), insertImage(), mergeImage(), and ungroup().
notifyChangedStrokes() [2/2]
void TVectorImage::notifyChangedStrokes (int strokeIndex, TStroke * oldStroke = 0, bool isFlipped = false)
Call the following method after stroke modification.
{
  std::vector<int> app(1);
  app[0] = strokeIndexArray;
  std::vector<TStroke *> oldStrokeArray(1);
  oldStrokeArray[0] = oldStroke ? oldStroke : getStroke(strokeIndexArray);
  m_imp->notifyChangedStrokes(app, oldStrokeArray, isFlipped);
}
References getStroke().
pickGroup()
int TVectorImage::pickGroup (const TPointD & pos) const
{
  int index;
  if ((index = pickGroup(pos, true)) == -1) return pickGroup(pos, false);
  return index;
}
putRegion()
void TVectorImage::putRegion (TRegion * region)
Put a region in the regions' container.
{
  m_imp->m_regions.push_back(region);
}
reassignStyles()
void TVectorImage::reassignStyles (std::map< int, int > & table)
Reassign all stroke's style.
{
  UINT i;
  UINT strokeCount = getStrokeCount();
  // UINT regionCount = getRegionCount();
  for (i = 0; i < strokeCount; ++i) {
    TStroke *stroke = getStroke(i);
    int styleId     = stroke->getStyle();
    if (styleId != 0) {
      map<int, int>::iterator it = table.find(styleId);
      if (it != table.end()) stroke->setStyle(it->second);
    }
  }
  Intersection *p1;
  IntersectedStroke *p2;
  for (p1 = m_imp->m_intersectionData->m_intList.first(); p1; p1 = p1->next())
    for (p2 = (*p1).m_strokeList.first(); p2; p2 = p2->next())
      if (p2->m_edge.m_styleId != 0) {
        map<int, int>::iterator it = table.find(p2->m_edge.m_styleId);
        if (it != table.end()) p2->m_edge.m_styleId = it->second;
        // assert(it->second<100);
      }
}
References getStroke(), getStrokeCount(), TStroke::getStyle(), and TStroke::setStyle().
recomputeRegionsIfNeeded()
void TVectorImage::recomputeRegionsIfNeeded ()
forces the recomputing of all regions (it is actually done only after having loaded the vectorimage)
{
  if (!m_imp->m_justLoaded) return;
  m_imp->m_justLoaded = false;
  std::vector<int> v(m_imp->m_strokes.size());
  int i;
  for (i = 0; i < (int)m_imp->m_strokes.size(); i++) v[i] = i;
  m_imp->notifyChangedStrokes(v, std::vector<TStroke *>(), false);
}
Referenced by Stage::RasterPainter::onVectorImage().
removeEndpoints()
TStroke * TVectorImage::removeEndpoints (int strokeIndex)
this method removes the parts of the stroke that are not bounds of regions. only ending parts are removed. If the entire stroke is not bounding any region, it is kept entitely. it returns the original stroke (for undo)
{
  return m_imp->removeEndpoints(strokeIndex);
}
removeStroke()
TStroke * TVectorImage::removeStroke (int index, bool doComputeRegions = true)
Remove the stroke of index index and if doComputeRegions is true recompute the regions
{
  return m_imp->removeStroke(index, doComputeRegions);
}
Referenced by areaFill(), deleteStroke(), eraseStyleIds(), and AreaFiller::strokeFill().
removeStrokes()
void TVectorImage::removeStrokes (const std::vector< int > & tobeRemoved, bool deleteThem, bool recomputeRegions)
Remove the strokes identified by indexes in the vector toBeRemoved.
If deleteThem is true strokes are really delete; if doComputeRegions is true recompute the regions
{
  m_imp->removeStrokes(toBeRemoved, deleteThem, recomputeRegions);
}
Referenced by splitSelected().
render()
TRaster32P TVectorImage::render (bool onlyStrokes)
Make the rendering of the vector image, return a TRaster32P with the image rendered
{
  TRect bBox = convert(getBBox());
  if (bBox.isEmpty()) return (TRaster32P)0;
  std::unique_ptr<TOfflineGL> offlineGlContext(new TOfflineGL(bBox.getSize()));
  offlineGlContext->clear(TPixel32(0, 0, 0, 0));
  offlineGlContext->makeCurrent();
  TVectorRenderData rd(TTranslation(-convert(bBox.getP00())),
                       TRect(bBox.getSize()), getPalette(), 0, true, true);
  rd.m_drawRegions = !onlyStrokes;
  offlineGlContext->draw(this, rd, false);
  return offlineGlContext->getRaster()->clone();
  // hardRenderVectorImage(rd,ras,this);
}
References getBBox(), TRectT< T >::isEmpty(), and TVectorRenderData::m_drawRegions.
replaceStroke()
void TVectorImage::replaceStroke (int index, TStroke * newStroke)
Replace the stroke at index index with newStroke.
{
  if ((int)m_imp->m_strokes.size() <= index) return;
  delete m_imp->m_strokes[index]->m_s;
  m_imp->m_strokes[index]->m_s = newStroke;
  Intersection *p1;
  IntersectedStroke *p2;
  for (p1 = m_imp->m_intersectionData->m_intList.first(); p1; p1 = p1->next())
    for (p2 = (*p1).m_strokeList.first(); p2; p2      = p2->next())
      if (p2->m_edge.m_index == index) p2->m_edge.m_s = newStroke;
}
restoreEndpoints()
void TVectorImage::restoreEndpoints (int index, TStroke * oldStroke)
this method replaces the stroke at index with oldstroke. Oldstroke is supposed to contain existing stroke. this method is used for undoing removeEndpoints .
{
  m_imp->restoreEndpoints(index, oldStroke);
}
sameGroup()
bool TVectorImage::sameGroup (UINT index1, UINT index2) const inline
Return true if two objects are contained into the same group.
{
    return areDifferentGroup(index1, false, index2, false) == -1;
  }
sameGroupStrokeAndRegion()
bool TVectorImage::sameGroupStrokeAndRegion (UINT strokeIndex, UINT regionIndex) const inline
Return true if a stroke and a region have common parent groups.
{
    return areDifferentGroup(strokeIndex, false, regionIndex, true) == -1;
  }
sameParentGroupStrokes()
bool TVectorImage::sameParentGroupStrokes (UINT index1, UINT index2) const inline
Return true if two strokes has common parent groups.
{
    int ret = areDifferentGroup(index1, false, index2, false);
    return (ret == -1 || ret >= 1);
  }
sameSubGroup()
bool TVectorImage::sameSubGroup (int strokeIndex0, int strokeIndex1) const
it says if two strokes are in the same group, even qhen the image is entered in a group.
{
  if (index0 < 0 || index1 < 0) return 0;
  return m_imp->m_strokes[index0]->m_groupId.getCommonParentDepth(
             m_imp->m_strokes[index1]->m_groupId) >
         m_imp->m_insideGroup.getDepth();
}
selectable()
bool TVectorImage::selectable (int strokeIndex) const
{
  return (m_imp->m_insideGroup != m_imp->m_strokes[strokeIndex]->m_groupId &&
          inCurrentGroup(strokeIndex));
}
selectFill()
bool TVectorImage::selectFill (const TRectD & selectArea, TStroke * s, int styleId, bool onlyUnfilled, bool fillAreas, bool fillLines)
Fill all the regions and strokes contained in selectArea or contained into the regions formed by the stroke s with the style styleId.
If onlyUnfilled is true, only regions filled with the style 0 are filled with the new stile. If fillAreas is true regions are filled. If fillLines is true stroke are filled.
{
  if (!m_imp->m_areValidRegions) m_imp->computeRegions();
  return m_imp->selectFill(selArea, s, newStyleId, onlyUnfilled, fillAreas,
                           fillLines);
}
Referenced by TImageReaderSvg::load(), and Stage::RasterPainter::onVectorImage().
setAutocloseTolerance()
void TVectorImage::setAutocloseTolerance (double val)
Set the autoclose tolerance to the specified value.
{
  m_imp->m_autocloseTolerance = val;
}
setEdgeColors()
void TVectorImage::setEdgeColors (int strokeIndex, int leftColorIndex, int rightColorIndex)
Set the edges of the stroke identified by strokeIndex with the styles leftColorIndex and \brightColorIndex.
{
  std::list<TEdge *> &ll = m_imp->m_strokes[strokeIndex]->m_edgeList;
  std::list<TEdge *>::const_iterator l   = ll.begin();
  std::list<TEdge *>::const_iterator l_e = ll.end();
  for (; l != l_e; ++l) {
    // double w0 = (*l)->m_w0, w1 = (*l)->m_w1;
    if ((*l)->m_w0 > (*l)->m_w1) {
      if (leftColorIndex != -1)
        (*l)->m_styleId = leftColorIndex;
      else if (rightColorIndex != -1)
        (*l)->m_styleId = rightColorIndex;
    } else {
      if (rightColorIndex != -1)
        (*l)->m_styleId = rightColorIndex;
      else if (leftColorIndex != -1)
        (*l)->m_styleId = leftColorIndex;
    }
  }
}
setFillData()
void TVectorImage::setFillData (std::unique_ptr< IntersectionBranch[]> const & v, UINT size, bool doComputeRegions = true)
{
  m_imp->setFillData(v, branchCount, doComputeRegions);
}
splitImage()
TVectorImageP TVectorImage::splitImage (const std::vector< int > & indices, bool removeFlag)
{
  TVectorImageP out             = new TVectorImage;
  out->m_imp->m_maxGroupId      = m_imp->m_maxGroupId;
  out->m_imp->m_maxGhostGroupId = m_imp->m_maxGhostGroupId;
  std::vector<int> toBeRemoved;
  TPalette *vp = getPalette();
  if (vp) out->setPalette(vp->clone());
  for (UINT i = 0; i < indices.size(); ++i) {
    VIStroke *ref = m_imp->m_strokes[indices[i]];
    assert(ref);
    VIStroke *vs       = new VIStroke(*ref);
    vs->m_isNewForFill = true;
    out->m_imp->m_strokes.push_back(vs);
  }
  if (removeFlag) removeStrokes(indices, true, true);
  out->m_imp->m_areValidRegions    = false;
  out->m_imp->m_computedAlmostOnce = m_imp->m_computedAlmostOnce;
  return out;
}
splitSelected()
TVectorImageP TVectorImage::splitSelected (bool removeFlag)
Creates a new Image using the selected strokes. If removeFlag==true then removes selected strokes It includes (in the new image) the color information too. It maintains stroke ids.
{
  TVectorImageP out = new TVectorImage;
  std::vector<int> toBeRemoved;
  for (UINT i = 0; i < getStrokeCount(); ++i) {
    VIStroke *ref = m_imp->m_strokes[i];
    assert(ref);
    if (ref->m_s->getFlag(TStroke::c_selected_flag)) {
      VIStroke *stroke = new VIStroke(*ref);
      out->m_imp->m_strokes.push_back(stroke);
      if (removeFlag) {
        toBeRemoved.push_back(i);
        //        removeStroke(i);
        //          delete ref;
        //        i--;
      }
    }
  }
  removeStrokes(toBeRemoved, true, true);
  out->m_imp->m_areValidRegions = false;
  return out;
}
References TStroke::getFlag(), getStrokeCount(), removeStrokes(), and TVectorImage().
splitStroke()
void TVectorImage::splitStroke (int strokeIndex, const std::vector< DoublePair > & sortedWRanges)
This functions splits stroke with index 'strokeIndex' in n+1 strokes, where n is the size of vector sortedW, cutting it in points w specified in sortedW. SortedW must be sorted in ascending order. Resulting strokes are put in VectorImage in position strokeIndex,strokeIndex+1, ... strokeIndex+n. Information on fill colors are maintened, as much as possible.
{
  m_imp->splitStroke(strokeIndex, sortedWRanges);
}
transferStrokeColors()
void TVectorImage::transferStrokeColors (TVectorImageP sourceImage, int sourceStroke, TVectorImageP destinationImage, int destinationStroke) static
Transfer the stroke style of the sourceStroke in the sourceImage to the style
{
  std::list<TEdge *> *sourceList =
      &(sourceImage->m_imp->m_strokes[sourceStroke]->m_edgeList);
  std::list<TEdge *> *destinationList =
      &(destinationImage->m_imp->m_strokes[destinationStroke]->m_edgeList);
  transferColors(*sourceList, *destinationList, true, false, false);
}
transform()
void TVectorImage::transform (const TAffine & aff, bool doChangeThickness = false)
Transform a stroke using an affine TAffine.
{
  UINT i;
  for (i = 0; i < m_imp->m_strokes.size(); ++i)
    m_imp->m_strokes[i]->m_s->transform(aff, doChangeThickness);
  map<int, VIStroke *>::iterator it =
      m_imp->m_intersectionData->m_autocloseMap.begin();
  for (; it != m_imp->m_intersectionData->m_autocloseMap.end(); ++it)
    it->second->m_s->transform(aff, false);
  for (i = 0; i < m_imp->m_regions.size(); ++i)
    invalidateRegionPropAndBBox(m_imp->m_regions[i]);
}
ungroup()
int TVectorImage::ungroup (int index)
Ungroup all the strokes in the group of index index.
Return the number of ungroped stroke.
{
  m_imp->m_insideGroup = TGroupId();
  assert(m_imp->m_strokes[fromIndex]->m_groupId.isGrouped() != 0);
  std::vector<int> changedStrokes;
  int toIndex = fromIndex + 1;
  while (toIndex < (int)m_imp->m_strokes.size() &&
         m_imp->m_strokes[fromIndex]->m_groupId.getCommonParentDepth(
             m_imp->m_strokes[toIndex]->m_groupId) >= 1)
    toIndex++;
  toIndex--;
  TGroupId groupId;
  if (fromIndex > 0 &&
      m_imp->m_strokes[fromIndex - 1]->m_groupId.isGrouped(true) != 0)
    groupId = m_imp->m_strokes[fromIndex - 1]->m_groupId;
  else if (toIndex < (int)m_imp->m_strokes.size() - 1 &&
           m_imp->m_strokes[toIndex + 1]->m_groupId.isGrouped(true) != 0)
    groupId = m_imp->m_strokes[toIndex + 1]->m_groupId;
  else
    groupId = TGroupId(this, true);
  for (int i = fromIndex;
       i <= toIndex || (i < (int)m_imp->m_strokes.size() &&
                        m_imp->m_strokes[i]->m_groupId.isGrouped(true) != 0);
       i++) {
    m_imp->m_strokes[i]->m_groupId.ungroup(groupId);
    changedStrokes.push_back(i);
  }
  notifyChangedStrokes(changedStrokes, std::vector<TStroke *>(), false);
  return toIndex - fromIndex + 1;
}
References notifyChangedStrokes().
validateRegions()
void TVectorImage::validateRegions (bool state = false)
Set valid regions flags call validateRegions() after region/stroke changes
{
  m_imp->m_areValidRegions = state;
}
Friends And Related Function Documentation
Imp()
Imp (TVectorImage * vi) related
Permette di copiare effettuare delle copie delle curve
TVectorImage::Imp: implementation of TVectorImage class
    : m_areValidRegions(false)
    , m_notIntersectingStrokes(false)
    , m_computeRegions(true)
    , m_autocloseTolerance(c_newAutocloseTolerance)
    , m_maxGroupId(1)
    , m_maxGhostGroupId(1)
    , m_mutex(new TThread::Mutex())
    , m_vi(vi)
    , m_intersectionData(0)
    , m_computedAlmostOnce(false)
    , m_justLoaded(false)
    , m_insideGroup(TGroupId())
    , m_minimizeEdges(true)
#ifdef NEW_REGION_FILL
    , m_regionFinder(0)
#endif
{
#ifdef NEW_REGION_FILL
  resetRegionFinder();
#endif
  initRegionsData();
}
Member Data Documentation
m_imp
std::unique_ptr<Imp> TVectorImage::m_imp
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/tvectorimage.h
E:/opentoonz/toonz/sources/common/tvectorimage/tcomputeregions.cpp
E:/opentoonz/toonz/sources/common/tvectorimage/tvectorimage.cpp