opentoonz: TFx Class Reference
TFx Class Reference abstract
Public Types
typedef TFx * CreateProc()
Public Types inherited from TSmartObject
typedef short ClassCode
Public Types inherited from TPersist
typedef TPersist * CreateProc()
Public Member Functions
virtual std::wstring getName () const
void setName (std::wstring name)
std::wstring getFxId () const
void setFxId (std::wstring id)
TParamContainer * getParams ()
const TParamContainer * getParams () const
void addParamVar (TParamVar *var)
virtual TFx * clone (bool recursive=true) const
TFx * clone (TFx *fx, bool recursive) const
void unlinkParams ()
virtual void linkParams (TFx *src)
TFx * getLinkedFx () const
bool addInputPort (const std::string &name, TFxPort &p)
bool addInputPort (const std::string &name, TFxPort *p, int groupIndex)
bool removeInputPort (const std::string &name)
returns false on duplicate names. Ownership is transferred to the group.
bool renamePort (const std::string &oldName, const std::string &newName)
if not found.
bool connect (const std::string &name, TFx *other)
Equivalent to getInputPort(name)->setFx(other).
bool disconnect (const std::string &name)
Equivalent to getInputPort(name)->setFx(0).
int getInputPortCount () const
TFxPort * getInputPort (int index) const
TFxPort * getInputPort (const std::string &name) const
std::string getInputPortName (int index) const
virtual int dynamicPortGroupsCount () const
virtual const TFxPortDG * dynamicPortGroup (int g) const
bool hasDynamicPortGroups () const
void clearDynamicPortGroup (int g)
bool addOutputConnection (TFxPort *port)
bool removeOutputConnection (TFxPort *port)
virtual bool isZerary () const
virtual int getReferenceColumnIndex () const
virtual TFxPort * getXsheetPort () const
int getOutputConnectionCount () const
TFxPort * getOutputConnection (int i) const
virtual TFxTimeRegion getTimeRegion () const
void setActiveTimeRegion (const TFxTimeRegion &tr)
TFxTimeRegion getActiveTimeRegion () const
virtual bool checkActiveTimeRegion () const
void disconnectAll ()
virtual void getParamUIs (TParamUIConcept *&params, int &length)
std::string getFxType () const
virtual std::string getPluginId () const =0
void onChange (const TParamChange &c) override
void addObserver (TFxObserver *)
void removeObserver (TFxObserver *)
void notify (const TFxChange &change)
void notify (const TFxPortAdded &change)
void notify (const TFxPortRemoved &change)
void notify (const TFxParamAdded &change)
void notify (const TFxParamRemoved &change)
void loadData (TIStream &is) override
void saveData (TOStream &os) override
void loadPreset (TIStream &is)
void savePreset (TOStream &os)
TFxAttributes * getAttributes () const
virtual std::string getAlias (double frame, const TRenderSettings &info) const
virtual void compatibilityTranslatePort (int majorVersion, int minorVersion, std::string &portName)
virtual int getPreferredInputPort ()
virtual void callStartRenderHandler ()
virtual void callEndRenderHandler ()
virtual void callStartRenderFrameHandler (const TRenderSettings *rs, double frame)
virtual void callEndRenderFrameHandler (const TRenderSettings *rs, double frame)
virtual void onObsoleteParamLoaded (const std::string &paramName)
void setFxVersion (int)
int getFxVersion () const
unsigned long getIdentifier () const
void setIdentifier (unsigned long id)
void setNewIdentifier ()
Public Member Functions inherited from TSmartObject
TSmartObject (ClassCode classCode)
void addRef ()
void release ()
TINT32 getRefCount () const
Public Member Functions inherited from TPersist
virtual void loadData (TIStream &is)=0
virtual void saveData (TOStream &os)=0
std::string getStreamTag () const
virtual const TPersistDeclaration * getDeclaration () const =0
virtual void onChange (const TParamChange &)=0
Static Public Member Functions
static void listFxs (std::vector< TFxInfo > &fxInfos)
static TFxInfo getFxInfo (const std::string &fxIdentifier)
static TFx * create (std::string name)
Static Public Member Functions inherited from TSmartObject
static TINT32 getInstanceCount (ClassCode code)
Static Public Member Functions inherited from TPersist
static void declare (CreateProc *)
static TPersist * create (const std::string &name)
Detailed Description
Member Typedef Documentation
CreateProc
typedef TFx * TFx::CreateProc()
Constructor & Destructor Documentation
TFx()
TFx::TFx ()
    : TSmartObject(m_classCode)  // TPersist(TFxImp::m_instances)
    , m_imp(new TFxImp(this)) {}
~TFx()
TFx::~TFx () virtual
          {
  for (std::set<TFxPort *>::iterator it = m_imp->m_outputPort.begin();
       it != m_imp->m_outputPort.end(); ++it) {
    TFxPort *port = *it;
    port->setFx(0);
  }
  delete m_imp;
}
Member Function Documentation
addInputPort() [1/2]
bool TFx::addInputPort (const std::string & name, TFxPort & p)
Adds a port with given name,
{
  PortTable::iterator it = m_imp->m_portTable.find(name);
  if (it != m_imp->m_portTable.end()) return false;
  m_imp->m_portTable[name] = &port;
  m_imp->m_portArray.push_back(NamePort(name, &port));
  port.setOwnerFx(this);  // back pointer to the owner...
  return true;
}
References TFxImp::m_portArray, and TFxImp::m_portTable.
Referenced by FxSchematicNode::addDynamicInputPort(), addInputPort(), loadData(), and TMacroFx::loadData().
addInputPort() [2/2]
bool TFx::addInputPort (const std::string & name, TFxPort * p, int groupIndex)
returns false on duplicate names. Ownership of the port belongs to derived implementations of TFx. Adds a port with given name to the specified dynamic group,
{
  if (!port) {
    assert(port);
    return false;
  }
  if (groupIndex >= dynamicPortGroupsCount()) {
    assert(groupIndex < dynamicPortGroupsCount());
    return false;
  }
  if (!addInputPort(name, *port)) return false;
  // Assign the port to the associated group
  port->m_groupIdx = groupIndex;
  TFxPortDG *group = const_cast<TFxPortDG *>(dynamicPortGroup(groupIndex));
  group->addPort(port);
  assert(name.find(group->m_portsPrefix) == 0);
  return true;
}
References addInputPort(), and TFxPort::m_groupIdx.
addObserver()
void TFx::addObserver (TFxObserver * obs)
{ m_imp->m_observers.insert(obs); }
addOutputConnection()
bool TFx::addOutputConnection (TFxPort * port)
{
  assert(port->getFx() == this);
  return m_imp->m_outputPort.insert(port).second;
}
callEndRenderFrameHandler()
virtual void TFx::callEndRenderFrameHandler (const TRenderSettings * rs, double frame) inline virtual
                                                       {}
callEndRenderHandler()
virtual void TFx::callEndRenderHandler () inline virtual
{}
callStartRenderFrameHandler()
virtual void TFx::callStartRenderFrameHandler (const TRenderSettings * rs, double frame) inline virtual
                                                         {}
callStartRenderHandler()
virtual void TFx::callStartRenderHandler () inline virtual
{}
checkActiveTimeRegion()
virtual bool TFx::checkActiveTimeRegion () const inline virtual
{ return true; }
clearDynamicPortGroup()
void TFx::clearDynamicPortGroup (int g)
Warning
Users must ensure that the group's minimal ports count is respected - this method does not.
{
  TFxPortDG *dg = const_cast<TFxPortDG *>(this->dynamicPortGroup(g));
  const std::string &prefix = dg->portsPrefix();
  std::string prefixEnd = prefix;
  ++prefixEnd[prefixEnd.size() - 1];
  {
    // Delete all associated ports from the ports table
    PortTable::iterator pBegin(m_imp->m_portTable.lower_bound(prefix));
    PortTable::iterator pEnd(m_imp->m_portTable.lower_bound(prefixEnd));
    m_imp->m_portTable.erase(pBegin, pEnd);
    // Traverse the ports array and remove all ports in the group
    IsPrefix func = {prefix};
    m_imp->m_portArray.resize(std::remove_if(m_imp->m_portArray.begin(),
                                             m_imp->m_portArray.end(), func) -
                              m_imp->m_portArray.begin());
  }
  dg->clear();  // Has ports ownership, so deletes them
}
References TFxImp::m_portArray, TFxImp::m_portTable, and TFxPortDynamicGroup::portsPrefix().
clone() [1/2]
TFx * TFx::clone (bool recursive = true) const virtual
{
  TFx *fx = TFx::create(getFxType());
  assert(fx);
  return this->clone(fx, recursive);
}
clone() [2/2]
TFx * TFx::clone (TFx * fx, bool recursive) const
{
  // Copy misc stuff
  fx->m_imp->m_activeTimeRegion = m_imp->m_activeTimeRegion;
  fx->setIdentifier(getIdentifier());
  fx->getParams()->copy(getParams());
  fx->setFxId(getFxId());
  fx->setName(getName());
  // Copy attributes
  *fx->getAttributes() = *getAttributes();
  // Clone the dynamic ports pool
  if (hasDynamicPortGroups()) {
    int p, pCount = m_imp->m_portArray.size();
    for (p = 0; p != pCount; ++p) {
      const NamePort &namedPort = m_imp->m_portArray[p];
      int groupIdx = namedPort.second->getGroupIndex();
      if (groupIdx >= 0 && !fx->getInputPort(namedPort.first))
        fx->addInputPort(namedPort.first, new TRasterFxPort, groupIdx);
    }
    assert(pCount == fx->getInputPortCount());
  }
  // copia ricorsiva sulle porte
  if (recursive) {
    int p, pCount = getInputPortCount();
    for (p = 0; p != pCount; ++p) {
      TFxPort *port = getInputPort(p);
      if (port->getFx())
        fx->connect(getInputPortName(p), port->getFx()->clone(true));
    }
  }
  return fx;
}
compatibilityTranslatePort()
virtual void TFx::compatibilityTranslatePort (int majorVersion, int minorVersion, std::string & portName) inline virtual
Compatibility function - used to translate a port name from older Toonz versions into its current form.
Reimplemented in TImageCombinationFx, TMacroFx, Iwa_TiledParticlesFx, and ParticlesFx.
                                                               {}
Referenced by TMacroFx::compatibilityTranslatePort(), and loadData().
connect()
bool TFx::connect (const std::string & name, TFx * other)
Equivalent to getInputPort(name)->setFx(other).
{
  TFxPort *port = getInputPort(name);
  if (!port) return false;
  port->setFx(fx);
  return true;
}
create()
TFx * TFx::create (std::string name) static
{
  return TFxFactory::instance()->create(name);
}
disconnect()
bool TFx::disconnect (const std::string & name)
Equivalent to getInputPort(name)->setFx(0).
{
  TFxPort *port = getInputPort(name);
  if (!port) return false;
  port->setFx(0);
  return true;
}
disconnectAll()
void TFx::disconnectAll ()
{
  int p, pCount = getInputPortCount();
  for (p = 0; p != pCount; ++p) getInputPort(p)->setFx(0);
}
dynamicPortGroup()
virtual const TFxPortDG * TFx::dynamicPortGroup (int g) const inline virtual
{ return 0; }
dynamicPortGroupsCount()
virtual int TFx::dynamicPortGroupsCount () const inline virtual
{ return 0; }
getActiveTimeRegion()
TFxTimeRegion TFx::getActiveTimeRegion () const
{
  return m_imp->m_activeTimeRegion;
}
getAlias()
virtual std::string TFx::getAlias (double frame, const TRenderSettings & info) const inline virtual
{
    return "";
  }
getAttributes()
TFxAttributes * TFx::getAttributes () const
{ return &m_imp->m_attributes; }
getFxId()
std::wstring TFx::getFxId () const
{ return m_imp->m_fxId; }
getFxInfo()
TFxInfo TFx::getFxInfo (const std::string & fxIdentifier) static
Returns info associated to
{
  return TFxFactory::instance()->getFxInfo(fxIdentifier);
}
getFxType()
std::string TFx::getFxType () const inline
{ return getDeclaration()->getId(); }
getFxVersion()
int TFx::getFxVersion () const
{ return m_imp->m_attributes.getFxVersion(); }
getIdentifier()
unsigned long TFx::getIdentifier () const
{ return m_imp->m_id; }
getInputPort() [1/2]
TFxPort * TFx::getInputPort (const std::string & name) const
{
  PortTable::iterator it = m_imp->m_portTable.find(name);
  if (it == m_imp->m_portTable.end()) return 0;
  return m_imp->m_portTable[name];
}
getInputPort() [2/2]
TFxPort * TFx::getInputPort (int index) const
{
  assert(0 <= index && index < (int)m_imp->m_portArray.size());
  return m_imp->m_portArray[index].second;
}
getInputPortCount()
int TFx::getInputPortCount () const
{ return m_imp->m_portArray.size(); }
getInputPortName()
std::string TFx::getInputPortName (int index) const
{
  assert(0 <= index && index < (int)(m_imp->m_portArray.size()));
  return m_imp->m_portArray[index].first;
}
getLinkedFx()
TFx * TFx::getLinkedFx () const
{
  assert(m_imp->m_next);
  assert(m_imp->m_next->m_prev == m_imp);
  assert(m_imp->m_next->m_fx != 0);
  return m_imp->m_next->m_fx;
}
getName()
std::wstring TFx::getName () const virtual
{ return m_imp->m_name; }
getOutputConnection()
TFxPort * TFx::getOutputConnection (int i) const
{
  assert(0 <= i && i <= (int)m_imp->m_outputPort.size());
  std::set<TFxPort *>::iterator it = m_imp->m_outputPort.begin();
  std::advance(it, i);
  if (it == m_imp->m_outputPort.end()) return 0;
  return *it;
}
getOutputConnectionCount()
int TFx::getOutputConnectionCount () const
{ return m_imp->m_outputPort.size(); }
getParams() [1/2]
TParamContainer * TFx::getParams ()
{ return &m_imp->m_paramContainer; }
getParams() [2/2]
const TParamContainer * TFx::getParams () const
{
  return &m_imp->m_paramContainer;
}
getParamUIs()
virtual void TFx::getParamUIs (TParamUIConcept *& params, int & length) inline virtual
Returns a list of User Interface Concepts to be displayed when editing the fx parameters.
Note
Ownership of the returned array allocated with new[] is passed to callers.
Reimplemented in CheckBoardFx, DiamondGradientFx, FourPointsGradientFx, FreeDistortBaseFx, ino_radial_blur, ino_spin_blur, Iwa_BarrelDistortFx, Iwa_BloomFx, Iwa_CorridorGradientFx, Iwa_DirectionalBlurFx, Iwa_FractalNoiseFx, Iwa_GlareFx, Iwa_LinearGradientFx, Iwa_TiledParticlesFx, Iwa_PerspectiveDistortFx, Iwa_PNPerspectiveFx, Iwa_RainbowFx, Iwa_SpinGradientFx, Iwa_TextFx, Iwa_TimeCodeFx, DirectionalBlurFx, ParticlesFx, PerlinNoiseFx, RadialBlurFx, RandomWaveFx, BaseRaylitFx, RippleFx, SpinBlurFx, SquareGradientFx, MultiLinearGradientFx, LinearGradientFx, RadialGradientFx, MultiRadialGradientFx, LightSpotFx, and ShaderFx.
{
    params = 0, length = 0;
  }
getPreferredInputPort()
virtual int TFx::getPreferredInputPort () inline virtual
{ return 0; }
getReferenceColumnIndex()
int TFx::getReferenceColumnIndex () const virtual
{
  if (!m_imp->m_portArray.empty()) {
    TFx *fx = m_imp->m_portArray[0].second->getFx();
    if (fx) return fx->getReferenceColumnIndex();
  }
  return -1;
}
getTimeRegion()
TFxTimeRegion TFx::getTimeRegion () const virtual
{
  if (m_imp->m_portTable.empty()) return TFxTimeRegion::createUnlimited();
  TFxTimeRegion tr((std::numeric_limits<double>::max)(),
                   -(std::numeric_limits<double>::max)());
  PortTable::iterator it = m_imp->m_portTable.begin();
  for (; it != m_imp->m_portTable.end(); ++it) {
    TFxPort *port = it->second;
    if (port && port->isConnected() && !port->isaControlPort()) {
      TFx *fx = port->getFx();
      assert(fx);
      tr += fx->getTimeRegion();
    }
  }
  return tr;
}
getXsheetPort()
virtual TFxPort * TFx::getXsheetPort () const inline virtual
{ return 0; }
hasDynamicPortGroups()
bool TFx::hasDynamicPortGroups () const inline
{ return (dynamicPortGroupsCount() > 0); }
isZerary()
virtual bool TFx::isZerary () const inline virtual
an fx identifier, or an unnamed one if none was found.
Reimplemented in Iwa_TiledParticlesFx, Iwa_TimeCodeFx, ParticlesFx, TextAwareBaseFx, and RasterFxPluginHost.
{ return getInputPortCount() == 0; }
linkParams()
void TFx::linkParams (TFx * src) virtual
{
  if (this == fx) return;
  getParams()->link(fx->getParams());
  m_imp->m_activeTimeRegion = fx->m_imp->m_activeTimeRegion;
  // aggiorno i link
  assert(m_imp->checkLinks());
  assert(fx->m_imp->checkLinks());
  std::swap(m_imp->m_next, fx->m_imp->m_next);
  std::swap(m_imp->m_next->m_prev, fx->m_imp->m_next->m_prev);
  assert(m_imp->checkLinks());
  assert(fx->m_imp->checkLinks());
}
listFxs()
void TFx::listFxs (std::vector< TFxInfo > & fxInfos) static
{
  TFxFactory::instance()->getFxInfos(info);
}
loadData()
void TFx::loadData (TIStream & is) override virtual
 This is a pure virtual function and must be overridden with a method
that implements the object loading from a stream (i.e take the object's features from a formatted data stream). For example the TStageObject class use his implementation to take the values of the parameters that characterizes a stage object as name, coordinates, etc... from a file. is is an input file stream
Implements TPersist.
Reimplemented in TMacroFx, TLevelColumnFx, and TZeraryColumnFx.
{
  // default version of fx is 1
  setFxVersion(1);
  std::string tagName;
  VersionNumber tnzVersion = is.getVersion();
  // Prevent to load "params" tag under "super" tag on saving macro fx.
  // For now "params" tag is no longer saved under "super" tag.
  // This is for keeping compatibility with older versions.
  bool isInSuperTag = (is.getCurrentTagName() == "super");
  QList<int> groupIds;
  QList<std::wstring> groupNames;
  while (is.openChild(tagName)) {
    if (tagName == "params") {
      if (isInSuperTag) {  // skip loading "params" tag under "super" tag
        is.skipCurrentTag();
        continue;
      }
      while (!is.eos()) {
        std::string paramName;
        while (is.openChild(paramName)) {
          TParamVar *paramVar = getParams()->getParamVar(paramName);
          if (paramVar && paramVar->getParam()) {
            paramVar->getParam()->loadData(is);
            if (paramVar->isObsolete())
              onObsoleteParamLoaded(paramVar->getParam()->getName());
          } else  // il parametro non e' presente -> skip
            skipChild(is);
          is.closeChild();
        }
      }
    } else if (tagName == "paramsLinkedTo") {
      TPersist *p = 0;
      is >> p;
      TFx *fx = dynamic_cast<TFx *>(p);
      if (fx == 0) throw TException("Missing linkedSetRoot");
      linkParams(fx);
    } else if (tagName == "ports") {
      std::string portName;
      while (!is.eos()) {
        while (is.openChild(portName)) {
          VersionNumber version = is.getVersion();
          compatibilityTranslatePort(version.first, version.second, portName);
          // Try to find the specified port
          TFxPort *port = getInputPort(portName);
          if (!port) {
            // Scan dynamic port groups for a containing one - add a port there
            // if found
            int g, gCount = dynamicPortGroupsCount();
            for (g = 0; g != gCount; ++g) {
              TFxPortDG *group = const_cast<TFxPortDG *>(dynamicPortGroup(g));
              if (group->contains(portName)) {
                addInputPort(portName, port = new TRasterFxPort, g);
                break;
              }
            }
          }
          // Could not find (or add) a port with the corresponding name - throw
          if (!port)
            throw TException(std::string("port '") + portName +
                             "' is not present");
          if (!is.eos()) {
            TPersist *p = 0;
            is >> p;
            TFx *fx = dynamic_cast<TFx *>(p);
            port->setFx(fx);
          }
          is.closeChild();
        }
      }
    } else if (tagName == "dagNodePos") {
      TPointD p;
      is >> p.x >> p.y;
      m_imp->m_attributes.setDagNodePos(updateDagPosition(p, tnzVersion));
    } else if (tagName == "numberId") {
      int numberId = 0;
      is >> numberId;
      m_imp->m_attributes.setId(numberId);
    } else if (tagName == "passiveCacheId") {
      int passiveCacheId = 0;
      is >> passiveCacheId;
      assert(passiveCacheId > 0);
      TPassiveCacheManager::instance()->declareCached(this, passiveCacheId);
    } else if (tagName == "name") {
      // passo attraverso un filepath solo per evitare i problemi di blank
      // o caratteri strani dentro il nome (sospetto che tfilepath sia gestito
      // correttamente mentre wstring no
      TFilePath tmp;
      is >> tmp;
      setName(tmp.getWideName());
    } else if (tagName == "fxId") {
      TFilePath tmp;
      is >> tmp;
      setFxId(tmp.getWideName());
    } else if (tagName == "enabled") {
      int flag = 1;
      is >> flag;
      m_imp->m_attributes.enable(flag != 0);
    } else if (tagName == "opened") {
      int opened = 1;
      is >> opened;
      m_imp->m_attributes.setIsOpened(opened);
    } else if (tagName == "groupIds") {
      int groupId;
      while (!is.eos()) {
        is >> groupId;
        groupIds.append(groupId);
      }
    } else if (tagName == "groupNames") {
      std::wstring groupName;
      while (!is.eos()) {
        is >> groupName;
        groupNames.append(groupName);
      }
    } else if (tagName == "fxVersion") {
      int version = 1;
      is >> version;
      setFxVersion(version);
    } else {
      throw TException("Unknown tag!");
    }
    is.closeChild();
  }
  if (!groupIds.isEmpty()) {
    assert(groupIds.size() == groupNames.size());
    int i;
    for (i = 0; i < groupIds.size(); i++) {
      m_imp->m_attributes.setGroupId(groupIds[i]);
      m_imp->m_attributes.setGroupName(groupNames[i]);
    }
  }
}
References addInputPort(), TIStream::closeChild(), compatibilityTranslatePort(), TIStream::eos(), TParam::getName(), TIStream::getVersion(), TPersist::loadData(), TIStream::openChild(), and TIStream::skipCurrentTag().
Referenced by TExternalProgramFx::loadData(), TMacroFx::loadData(), TLevelColumnFx::loadData(), and TZeraryColumnFx::loadData().
loadPreset()
void TFx::loadPreset (TIStream & is)
{
  std::string tagName;
  while (is.openChild(tagName)) {
    if (tagName == "dvpreset") {
      std::string fxId = is.getTagAttribute("fxId");
      if (fxId != getFxType())
        throw TException("Preset doesn't match the fx type");
    } else if (tagName == "params") {
      while (!is.eos()) {
        std::string paramName;
        while (is.openChild(paramName)) {
          try {
            TParamP param = getParams()->getParam(paramName);
            param->loadData(is);
          } catch (TException &) { /*skip*/
          }                        // il parametro non e' presente
          is.closeChild();
        }
      }
    } else {
      throw TException("Fx preset unknown tag!");
    }
  }
}
notify() [1/5]
void TFx::notify (const TFxChange & change)
{
  for (std::set<TFxObserver *>::iterator it = m_imp->m_observers.begin();
       it != m_imp->m_observers.end(); ++it)
    (*it)->onChange(change);
}
notify() [2/5]
void TFx::notify (const TFxParamAdded & change)
{
  for (std::set<TFxObserver *>::iterator it = m_imp->m_observers.begin();
       it != m_imp->m_observers.end(); ++it)
    (*it)->onChange(change);
}
notify() [3/5]
void TFx::notify (const TFxParamRemoved & change)
{
  for (std::set<TFxObserver *>::iterator it = m_imp->m_observers.begin();
       it != m_imp->m_observers.end(); ++it)
    (*it)->onChange(change);
}
notify() [4/5]
void TFx::notify (const TFxPortAdded & change)
{
  for (std::set<TFxObserver *>::iterator it = m_imp->m_observers.begin();
       it != m_imp->m_observers.end(); ++it)
    (*it)->onChange(change);
}
notify() [5/5]
void TFx::notify (const TFxPortRemoved & change)
{
  for (std::set<TFxObserver *>::iterator it = m_imp->m_observers.begin();
       it != m_imp->m_observers.end(); ++it)
    (*it)->onChange(change);
}
onChange()
void TFx::onChange (const TParamChange & c) override virtual
Implements TParamObserver.
{
  TFxParamChange change(this, c);
  notify(change);
}
onObsoleteParamLoaded()
virtual void TFx::onObsoleteParamLoaded (const std::string & paramName) inline virtual
{}
removeInputPort()
bool TFx::removeInputPort (const std::string & name)
returns false on duplicate names. Ownership is transferred to the group.
Removes the port with given name, returns false
{
  m_imp->m_portTable.erase(name);
  PortArray::iterator it = std::find_if(
      m_imp->m_portArray.begin(), m_imp->m_portArray.end(), PortNameEq(name));
  if (it == m_imp->m_portArray.end()) return false;
  TFxPort *port = it->second;
  port->setOwnerFx(0);
  if (port->m_groupIdx >= 0) {
    TFxPortDG *group =
        const_cast<TFxPortDG *>(this->dynamicPortGroup(port->m_groupIdx));
    group->removePort(port);  // The port is DELETED here
  }
  m_imp->m_portArray.erase(it);
  return true;
}
References TFxPort::m_groupIdx, TFxImp::m_portArray, and TFxImp::m_portTable.
Referenced by FxSchematicNode::removeDynamicInputPort().
removeObserver()
void TFx::removeObserver (TFxObserver * obs)
{ m_imp->m_observers.erase(obs); }
removeOutputConnection()
bool TFx::removeOutputConnection (TFxPort * port)
{
  std::set<TFxPort *>::iterator it = m_imp->m_outputPort.find(port);
  if (it == m_imp->m_outputPort.end()) return false;
  m_imp->m_outputPort.erase(it);
  return true;
}
renamePort()
bool TFx::renamePort (const std::string & oldName, const std::string & newName)
if not found.
{
  PortTable::iterator it = m_imp->m_portTable.find(oldName);
  if (it == m_imp->m_portTable.end()) return false;
  TFxPort *port = it->second;
  m_imp->m_portTable.erase(it);
  m_imp->m_portTable[newName] = port;
  PortArray::iterator it2;
  for (it2 = m_imp->m_portArray.begin(); it2 != m_imp->m_portArray.end();
       ++it2) {
    if (it2->first != oldName) continue;
    it2->first = newName;
    break;
  }
  return true;
}
References TFxImp::m_portArray, and TFxImp::m_portTable.
saveData()
void TFx::saveData (TOStream & os) override virtual
 This is a pure virtual function and must be overridden with a method
that implements the object saving to a data stream (i.e put the object's features on a formatted data stream). For example the TStageObject class use his implementation to save the values of the parameters that characterizes a stage object as name, coordinates, etc... on a file os is an output file stream.
Implements TPersist.
Reimplemented in TMacroFx, TLevelColumnFx, and TZeraryColumnFx.
{
  // Prevent to save "params" tag under "super" tag on saving macro fx.
  // Parameters for macro fx are saved in "nodes" tag and corrected upon
  // loading. Therefore, "params" tag is not needed and even causes crash if
  // macrofx contains CurveFx (See the issue #2424)
  bool isInSuperTag  = (os.getCurrentTagName() == "super");
  TFx *linkedSetRoot = this;
  if (m_imp->m_next != m_imp) {
    TFxImp *imp = m_imp->m_next;
    int guard   = 0;
    while (guard++ < 1000 && imp != m_imp) {
      if (imp->m_fx < linkedSetRoot) linkedSetRoot = imp->m_fx;
      imp = imp->m_next;
    }
    assert(imp == m_imp);
    assert(linkedSetRoot);
  }
  if (linkedSetRoot == this) {
    if (!isInSuperTag) {  // skip saving "params" tag under "super" tag
      os.openChild("params");
      for (int i = 0; i < getParams()->getParamCount(); i++) {
        std::string paramName     = getParams()->getParamName(i);
        const TParamVar *paramVar = getParams()->getParamVar(i);
        // skip saving for the obsolete parameters
        if (paramVar->isObsolete()) continue;
        os.openChild(paramName);
        paramVar->getParam()->saveData(os);
        os.closeChild();
      }
      os.closeChild();
    }
  } else {
    os.openChild("paramsLinkedTo");
    os << linkedSetRoot;
    os.closeChild();
  }
  os.openChild("ports");
  for (auto &namePort : m_imp->m_portArray) {
    os.openChild(namePort.first);
    if (namePort.second->isConnected())
      os << TFxP(namePort.second->getFx()).getPointer();
    os.closeChild();
  }
  os.closeChild();
  TPointD p = m_imp->m_attributes.getDagNodePos();
  if (p != TConst::nowhere) os.child("dagNodePos") << p.x << p.y;
  int numberId = m_imp->m_attributes.getId();
  os.child("numberId") << numberId;
  bool cacheEnabled = TPassiveCacheManager::instance()->cacheEnabled(this);
  if (cacheEnabled)
    os.child("passiveCacheId")
        << TPassiveCacheManager::instance()->getPassiveCacheId(this);
  std::wstring name = getName();
  if (name != L"") os.child("name") << TFilePath(name);
  std::wstring fxId = getFxId();
  os.child("fxId") << fxId;
  if (!m_imp->m_attributes.isEnabled()) os.child("enabled") << 0;
  os.child("opened") << (int)m_imp->m_attributes.isOpened();
  if (m_imp->m_attributes.isGrouped()) {
    os.openChild("groupIds");
    QStack<int> groupIdStack = m_imp->m_attributes.getGroupIdStack();
    int i;
    for (i = 0; i < groupIdStack.size(); i++) os << groupIdStack[i];
    os.closeChild();
    os.openChild("groupNames");
    QStack<std::wstring> groupNameStack =
        m_imp->m_attributes.getGroupNameStack();
    for (i = 0; i < groupNameStack.size(); i++) os << groupNameStack[i];
    os.closeChild();
  }
  if (getFxVersion() != 1) os.child("fxVersion") << getFxVersion();
}
References TOStream::child(), TOStream::closeChild(), TFxImp::m_fx, TFxImp::m_next, TFxImp::m_portArray, TOStream::openChild(), and TPersist::saveData().
Referenced by TExternalProgramFx::saveData(), TMacroFx::saveData(), TLevelColumnFx::saveData(), and TZeraryColumnFx::saveData().
savePreset()
void TFx::savePreset (TOStream & os)
{
  std::map<std::string, std::string> attributes;
  attributes.insert(std::make_pair(std::string("ver"), std::string("1.0")));
  attributes.insert(std::make_pair(std::string("fxId"), getFxType()));
  os.openChild("dvpreset", attributes);
  os.openChild("params");
  for (int i = 0; i < getParams()->getParamCount(); i++) {
    std::string paramName = getParams()->getParamName(i);
    TParam *param         = getParams()->getParam(i);
    os.openChild(paramName);
    param->saveData(os);
    os.closeChild();
  }
  os.closeChild();
  os.closeChild();
}
setActiveTimeRegion()
void TFx::setActiveTimeRegion (const TFxTimeRegion & tr)
{
  m_imp->m_activeTimeRegion = tr;
}
setFxId()
void TFx::setFxId (std::wstring id)
{ m_imp->m_fxId = id; }
setFxVersion()
void TFx::setFxVersion (int v)
{ m_imp->m_attributes.setFxVersion(v); }
setIdentifier()
void TFx::setIdentifier (unsigned long id)
{ m_imp->m_id = id; }
setName()
void TFx::setName (std::wstring name)
{ m_imp->m_name = name; }
setNewIdentifier()
void TFx::setNewIdentifier ()
{ m_imp->m_id = ++m_imp->m_nextId; }
unlinkParams()
void TFx::unlinkParams ()
                       {
  // clone dei parametri
  getParams()->unlink();
  assert(m_imp->m_prev);
  assert(m_imp->m_next);
  assert(m_imp->m_prev->m_next == m_imp);
  assert(m_imp->m_next->m_prev == m_imp);
  m_imp->m_prev->m_next = m_imp->m_next;
  m_imp->m_next->m_prev = m_imp->m_prev;
  m_imp->m_next = m_imp->m_prev = m_imp;
  notify(TFxParamsUnlinked(this));
}
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/tfx.h
E:/opentoonz/toonz/sources/common/tfx/tfx.cpp