opentoonz: MagnetTool Class Reference
MagnetTool Class Reference final
Public Member Functions
ToolType getToolType () const override
void updateTranslation () override
void onEnter () override
Callback for the mouse entering the viewer area.
void leftButtonDown (const TPointD &pos, const TMouseEvent &e) override
void leftButtonDrag (const TPointD &p, const TMouseEvent &) override
void mouseMove (const TPointD &p, const TMouseEvent &e) override
void leftButtonUp (const TPointD &, const TMouseEvent &) override
void draw () override
Draws the tool on the viewer.
void onActivate () override
Callback invoked whenever the tool activates.
TPropertyGroup * getProperties (int targetType) override
int getCursorId () const override
Returns the type of cursor used by the tool.
bool onPropertyChanged (std::string propertyName) override
Public Member Functions inherited from TTool
TTool (std::string toolName)
every tool (invoking updateTranslation() for each).
virtual ToolType getToolType () const =0
ToolTargetType getTargetType () const
std::string getName () const
virtual ToolOptionsBox * createOptionsBox ()
void setViewer (Viewer *viewer)
Viewer * getViewer () const
double getPixelSize () const
void invalidate (const TRectD &rect=TRectD())
int pick (const TPointD &p)
bool isPicking () const
virtual void updateTranslation ()
virtual bool preLeftButtonDown ()
virtual void mouseMove (const TPointD &, const TMouseEvent &)
virtual void leftButtonDown (const TPointD &, const TMouseEvent &)
virtual void leftButtonDrag (const TPointD &, const TMouseEvent &)
virtual void leftButtonUp (const TPointD &, const TMouseEvent &)
virtual void leftButtonDoubleClick (const TPointD &, const TMouseEvent &)
virtual void rightButtonDown (const TPointD &, const TMouseEvent &)
virtual bool keyDown (QKeyEvent *)
virtual void onInputText (std::wstring, std::wstring, int, int)
virtual void onSetViewer ()
virtual void onActivate ()
Callback invoked whenever the tool activates.
virtual void onDeactivate ()
Callback for tool deactivation, includes tool switch.
virtual void onImageChanged ()
Notifies changes in the image in use.
virtual void onEnter ()
Callback for the mouse entering the viewer area.
virtual void onLeave ()
Callback for the mouse leaving the viewer area.
virtual void onFrameSwitched ()
virtual void reset ()
virtual void draw ()
Draws the tool on the viewer.
bool isActive () const
Used to know if a tool is active, (used in TextTool only).
void setActive (bool active)
virtual TPropertyGroup * getProperties (int)
virtual bool onPropertyChanged (std::string propertyName)
virtual TSelection * getSelection ()
Returns a pointer to the tool selection.
virtual int getCursorId () const
Returns the type of cursor used by the tool.
virtual bool isEventAcceptable (QEvent *e)
TXsheet * getXsheet () const
Returns a pointer to the actual Xsheet.
int getFrame ()
Returns the actual frame in use.
int getColumnIndex ()
Returns the actual column index.
TStageObjectId getObjectId () const
Returns a pointer to the actual stage object.
void notifyImageChanged ()
void notifyImageChanged (const TFrameId &fid)
images on the level view.
TFrameId getCurrentFid () const
Returns the number of the actual editing frame.
const TAffine & getMatrix () const
void setMatrix (const TAffine &matrix)
TAffine getCurrentColumnMatrix (int frame=-1) const
TAffine getCurrentColumnParentMatrix () const
TAffine getCurrentObjectParentMatrix () const
TAffine getCurrentObjectParentMatrix2 () const
TAffine getColumnMatrix (int index, int frame=-1) const
virtual void updateMatrix ()
virtual void addContextMenuItems (QMenu *menu)
void enable (bool on)
bool isEnabled () const
QString updateEnabled ()
virtual QString updateEnabled (int rowIndex, int columnIndex)
bool isColumnLocked (int columnIndex) const
void resetInputMethod ()
Resets Input Context (IME)
virtual bool isPencilModeActive ()
virtual bool isDragging () const
void setSelectedFrames (const std::set< TFrameId > &selectedFrames)
void tweenSelectedGuideStrokes ()
void tweenGuideStrokeToSelected ()
void flipGuideStrokeDirection (int mode)
Additional Inherited Members
Public Types inherited from TTool
enum ToolType {
GenericTool = 1 , ColumnTool = 2 , LevelReadTool = 4 , LevelWriteTool ,
LevelTool = LevelReadTool | LevelWriteTool
}
Tool editing type.
enum ToolTargetType {
NoTarget = 0x0 , VectorImage = 0x1 , ToonzImage = 0x2 , RasterImage = 0x4 ,
MeshImage = 0x8 , Splines = 0x10 , LevelColumns = 0x20 , MeshColumns = 0x40 ,
EmptyTarget = 0x80 , CommonImages = VectorImage | ToonzImage | RasterImage , AllImages = CommonImages | MeshImage , Vectors = VectorImage | Splines ,
CommonLevels = CommonImages | LevelColumns , MeshLevels = MeshImage | MeshColumns , AllTargets = 0xffffffff
}
Object types the tool can operate on.
typedef TApplication Application
Static Public Member Functions inherited from TTool
static TTool * getTool (std::string toolName, ToolTargetType targetType)
static TApplication * getApplication ()
static void setApplication (TApplication *application)
static TXshCell getImageCell ()
Returns the level-frame pair to be edited by the tool.
static TImage * getImage (bool toBeModified, int subsampling=0)
Returns the image to be edited by the tool.
static TImage * touchImage ()
static void updateToolsPropertiesTranslation ()
static const std::set< TFrameId > & getSelectedFrames ()
Static Public Attributes inherited from TTool
static std::vector< CellOps > m_cellsData
static bool m_isLevelCreated = false
static bool m_isFrameCreated = false
static std::vector< TFrameId > m_oldFids
static std::vector< TFrameId > m_newFids
static bool m_isLevelRenumbererd = false
Protected Member Functions inherited from TTool
void bind (int targetType)
virtual void onSelectedFramesChanged ()
virtual QString disableString ()
Returns a custom reason to disable the tool.
Protected Attributes inherited from TTool
std::string m_name
The tool's name.
Viewer * m_viewer
Tool's current viewer.
TAffine m_matrix
World-to-window reference change affine.
int m_targetType
The tool's image type target.
bool m_enabled
Whether the tool allows user interaction.
bool m_active
bool m_picking
Static Protected Attributes inherited from TTool
static TApplication * m_application = 0
static std::set< TFrameId > m_selectedFrames = std::set<TFrameId>()
Detailed Description
Constructor & Destructor Documentation
MagnetTool()
MagnetTool::MagnetTool () inline
      : TTool("T_Magnet")
      , m_active(false)
      , m_oldStrokesArray()
      , m_toolSize("Size:", 10, 1000, 20)  // W_ToolOptions_MagnetTool
  {
    bind(TTool::Vectors);
    m_toolSize.setNonLinearSlider();
    m_prop.bind(m_toolSize);
  }
Member Function Documentation
draw()
void MagnetTool::draw () inline override virtual
Draws the tool on the viewer.
Reimplemented from TTool.
                       {
    TVectorImageP vi = TImageP(getImage(true));
    if (!vi) return;
    // TAffine viewMatrix = getViewer()->getViewMatrix();
    // glPushMatrix();
    // tglMultMatrix(viewMatrix);
    double pointSize = m_toolSize.getValue();
    tglColor(TPixel32::Red);
    tglDrawCircle(m_pointAtMove, pointSize);
    if (!m_active) {
      // glPopMatrix();
      return;
    }
    TPointD delta = m_pointAtMouseDown - m_startingPos;
    //    glPushMatrix();
    // tglMultMatrix(m_referenceMatrix);
    if (!m_strokeHit.empty())
      for (UINT i = 0; i < m_strokeHit.size(); ++i)
        drawStrokeCenterline(*m_strokeHit[i], getPixelSize());
    tglColor(TPixel32::Red);
    UINT i, j;
    for (i = 0; i < m_strokeToModify.size(); ++i)
      for (j = 0; j < m_strokeToModify[i].m_splittedToMove.size(); ++j) {
        TStroke *temp = m_strokeToModify[i].m_splittedToMove[j];
        drawStrokeCenterline(*temp, getPixelSize());
      }
    //    glPopMatrix();
    // glPopMatrix();
  }
References TTool::getImage().
getCursorId()
int MagnetTool::getCursorId () const inline override virtual
Returns the type of cursor used by the tool.
See also
For a list of cursor ids cursor.h
Reimplemented from TTool.
{
    if (m_viewer && m_viewer->getGuidedStrokePickerMode())
      return m_viewer->getGuidedStrokePickerCursor();
    return m_cursorId;
  }
References TTool::m_viewer.
getProperties()
TPropertyGroup * MagnetTool::getProperties (int targetType) inline override virtual
Reimplemented from TTool.
{ return &m_prop; }
getToolType()
ToolType MagnetTool::getToolType () const inline override virtual
Implements TTool.
{ return TTool::LevelWriteTool; }
leftButtonDown()
void MagnetTool::leftButtonDown (const TPointD & pos, const TMouseEvent & e) inline override virtual
Reimplemented from TTool.
{
    TPointD p(pos);
    if (getViewer() && getViewer()->getGuidedStrokePickerMode()) {
      getViewer()->doPickGuideStroke(p);
      return;
    }
    m_oldPos = pos;
    m_pointAtMouseDown = p;
    m_startingPos      = p;
    m_active           = false;
    TVectorImageP vi   = TImageP(getImage(true));
    if (!vi) return;
    QMutexLocker lock(vi->getMutex());
    m_active = true;
    m_pointAtMove = m_pointAtMouseDown = p;
    m_strokeHit.clear();
    m_changedStrokes.clear();
    m_strokeToModify.clear();
    std::vector<TStroke *> strokeUndo;
    TStroke *ref;
    m_hitStrokeCorners.clear();
    m_strokeToModifyCorners.clear();
    double pointSize = m_toolSize.getValue();
    UINT i = 0;
    for (; i < vi->getStrokeCount(); ++i) {
      if (!vi->inCurrentGroup(i)) continue;
      TStroke *stroke = vi->getStroke(i);
      ref             = stroke;
      //  calcola le intersezioni
      std::vector<double> intersections;
      intersect(*ref, p, pointSize, intersections);
      if (intersections.empty()) {
        if (increaseControlPoints(*ref,
                                  TStrokePointDeformation(p, pointSize))) {
          m_changedStrokes.push_back(i);
          m_strokeHit.push_back(ref);
          std::vector<int> *corners = new std::vector<int>;
          corners->push_back(0);
          detectCorners(ref, 20, *corners);
          corners->push_back(ref->getChunkCount());
          m_hitStrokeCorners.push_back(corners);
          ref->disableComputeOfCaches();
          strokeUndo.push_back(ref);
        }
      } else {
        strokeUndo.push_back(ref);
        MagnetTool::strokeCollection sc;
        sc.m_parent = ref;
        splitStroke(*sc.m_parent, intersections, sc.m_splitted);
        selectStrokeToMove(sc.m_splitted, p, pointSize, sc.m_splittedToMove);
        for (UINT ii = 0; ii < sc.m_splittedToMove.size(); ++ii) {
          TStroke *temp = sc.m_splittedToMove[ii];
          bool test     = increaseControlPoints(
              *temp, TStrokePointDeformation(p, pointSize));
          assert(test);
          std::vector<int> *corners = new std::vector<int>;
          corners->push_back(0);
          detectCorners(temp, 20, *corners);
          corners->push_back(temp->getChunkCount());
          m_strokeToModifyCorners.push_back(corners);
        }
        m_strokeToModify.push_back(sc);
        m_changedStrokes.push_back(i);
      }
    }
    m_oldStrokesArray.resize(m_changedStrokes.size());
    for (i = 0; i < m_changedStrokes.size(); i++)
      m_oldStrokesArray[i] = new TStroke(*(vi->getStroke(m_changedStrokes[i])));
    if (!strokeUndo.empty()) {
      if (TTool::getApplication()->getCurrentObject()->isSpline())
        m_undo = new UndoPath(
            getXsheet()->getStageObject(getObjectId())->getSpline());
      else {
        TXshSimpleLevel *sl =
            TTool::getApplication()->getCurrentLevel()->getSimpleLevel();
        assert(sl);
        TFrameId id = getCurrentFid();
        m_undo      = new UndoModifyListStroke(sl, id, strokeUndo);
      }
    }
    invalidate();
    // vi->validateRegionEdges(ref, true);
  };
leftButtonDrag()
void MagnetTool::leftButtonDrag (const TPointD & p, const TMouseEvent &) inline override virtual
Reimplemented from TTool.
{
    if (!m_active) return;
    //      double dx = p.x - m_pointAtMouseDown.x;
    double pixelSize = getPixelSize();
    if (tdistance2(p, m_oldPos) < 9.0 * pixelSize * pixelSize) return;
    m_oldPos           = p;
    m_pointAtMouseDown = p;
    // double sc = exp(0.001 * (double)dx);
    TVectorImageP vi = TImageP(getImage(true));
    if (!vi) return;
    QMutexLocker lock(vi->getMutex());
    TPointD offset = p - m_pointAtMove;
    /*
if(tdistance2(m_pointAtMouseDown, p) > sq(m_pointSize * 0.5)) // reincremento
{
leftButtonUp(p);
lefrightButtonDown(p);
}
*/
    double pointSize = m_toolSize.getValue();
    UINT i, j;
    for (i = 0; i < m_strokeHit.size(); ++i)
      modifyControlPoints(
          *m_strokeHit[i],
          TStrokePointDeformation(offset, m_pointAtMouseDown, pointSize * 0.7));
    for (i = 0; i < m_strokeToModify.size(); ++i)
      for (j = 0; j < m_strokeToModify[i].m_splittedToMove.size(); ++j) {
        TStroke *temp = m_strokeToModify[i].m_splittedToMove[j];
        modifyControlPoints(*temp,
                            TStrokePointDeformation(offset, m_pointAtMouseDown,
                                                    pointSize * 0.7));
      }
    m_pointAtMove = p;
    invalidate();
  };
leftButtonUp()
void MagnetTool::leftButtonUp (const TPointD & , const TMouseEvent &) inline override virtual
Reimplemented from TTool.
{
    if (!m_active) return;
    m_active           = false;
    m_pointAtMouseDown = m_pointAtMove = TConsts::napd;
    TStroke *ref;
    TVectorImageP vi = TImageP(getImage(true));
    if (!vi) return;
    QMutexLocker lock(vi->getMutex());
    UINT i, j;
    for (i = 0; i < m_strokeHit.size(); ++i) {
      ref = m_strokeHit[i];
      ref->enableComputeOfCaches();
      ref->reduceControlPoints(getPixelSize() * ReduceControlPointCorrection,
                               *(m_hitStrokeCorners[i]));
      // vi->validateRegionEdges(ref, false);
    }
    clearPointerContainer(m_hitStrokeCorners);
    m_hitStrokeCorners.clear();
    UINT count = 0;
    for (i = 0; i < m_strokeToModify.size(); ++i) {
      // recupero la stroke collection
      MagnetTool::strokeCollection &sc = m_strokeToModify[i];
      for (j = 0; j < sc.m_splittedToMove.size(); ++j) {
        ref = sc.m_splittedToMove[j];
        ref->enableComputeOfCaches();
        ref->reduceControlPoints(getPixelSize() * ReduceControlPointCorrection,
                                 *(m_strokeToModifyCorners[count++]));
      }
      // ricostruisco una stroke con quella data
      ref = merge(sc.m_splitted);
      if (sc.m_parent->isSelfLoop()) {
        int cpCount      = ref->getControlPointCount();
        TThickPoint p1   = ref->getControlPoint(0);
        TThickPoint p2   = ref->getControlPoint(cpCount - 1);
        TThickPoint midP = (p1 + p2) * 0.5;
        ref->setControlPoint(0, midP);
        ref->setControlPoint(cpCount - 1, midP);
        ref->setSelfLoop(true);
      }
      sc.m_parent->swapGeometry(*ref);
      delete ref;  // elimino la curva temporanea
      clearPointerContainer(
          sc.m_splitted);           // pulisco le stroke trovate con lo split
      sc.m_splittedToMove.clear();  // pulisco il contenitore ( le stroke
                                    // che erano contenute qua sono state
                                    // eliminate nella clearPointer....
    }
    clearPointerContainer(m_strokeToModifyCorners);
    m_strokeToModifyCorners.clear();
    for (i = 0; i < vi->getStrokeCount(); ++i) {
      ref = vi->getStroke(i);
      ref->invalidate();
    }
    vi->notifyChangedStrokes(m_changedStrokes, m_oldStrokesArray);
    notifyImageChanged();
    if (m_undo) TUndoManager::manager()->add(m_undo);
    m_undo = 0;
    clearPointerContainer(m_oldStrokesArray);
    m_oldStrokesArray.clear();
    invalidate();
  };
mouseMove()
void MagnetTool::mouseMove (const TPointD & p, const TMouseEvent & e) inline override virtual
Reimplemented from TTool.
{
    m_pointAtMove    = p;
    double pixelSize = getPixelSize();
    if (tdistance2(p, m_oldPos) < 9.0 * pixelSize * pixelSize) return;
    m_oldPos = p;
    invalidate();
  }
onActivate()
void MagnetTool::onActivate () inline override virtual
Callback invoked whenever the tool activates.
Reimplemented from TTool.
{
    //        getApplication()->editImageOrSpline();
  }
onEnter()
void MagnetTool::onEnter () inline override virtual
Callback for the mouse entering the viewer area.
Reimplemented from TTool.
{
    if ((TVectorImageP)getImage(false))
      m_cursorId = ToolCursor::MagnetCursor;
    else
      m_cursorId = ToolCursor::CURSOR_NO;
  }
References TTool::getImage().
onPropertyChanged()
bool MagnetTool::onPropertyChanged (std::string propertyName) inline override virtual
 Does the tasks associated to changes in \p propertyName and returns \p
true; Does the tasks associated to changes in propertyName and returns true.
Reimplemented from TTool.
{
    if (propertyName == m_toolSize.getName()) {
      invalidate();
    }
    return true;
  }
References TTool::invalidate().
updateTranslation()
void MagnetTool::updateTranslation () inline override virtual
Reimplemented from TTool.
{ m_toolSize.setQStringName(tr("Size:")); }
The documentation for this class was generated from the following file:
E:/opentoonz/toonz/sources/tnztools/magnettool.cpp