opentoonz: TRasterImagePatternStrokeStyle Class Reference
TRasterImagePatternStrokeStyle Class Reference final
Public Member Functions
TRasterImagePatternStrokeStyle (const std::string &patternName)
bool isRegionStyle () const override
Returns whether the style applies on regions.
bool isStrokeStyle () const override
Returns whether the style applies on strokes.
int getLevelFrameCount ()
void computeTransformations (std::vector< TAffine > &positions, const TStroke *stroke) const
void drawStroke (const TVectorRenderData &rd, const std::vector< TAffine > &positions, const TStroke *stroke) const
void invalidate ()
TColorStyle * clone () const override
Polymorphic clone of the style.
QString getDescription () const override
Return a brief description of the style.
bool hasMainColor () const override
Returns whether the style has a reference main color.
TPixel32 getMainColor () const override
Returns the style's main color, or black if none.
void setMainColor (const TPixel32 &) override
Sets the main color, if it has one.
TStrokeProp * makeStrokeProp (const TStroke *stroke) override
TRegionProp * makeRegionProp (const TRegion *) override
used to draw the style on the specified stroke object.
int getTagId () const override
Returns an unique number representing the style.
void getObsoleteTagIds (std::vector< int > &ids) const override
void loadLevel (const std::string &patternName)
int getParamCount () const override
TColorStyle::ParamType getParamType (int index) const override
Returns the type of the specified parameter.
QString getParamNames (int index) const override
Return the string that identifies the index-th parameter.
void getParamRange (int index, double &min, double &max) const override
Retrieves the specified double parameter range.
double getParamValue (TColorStyle::double_tag, int index) const override
Retrieves the specified double parameter value.
void setParamValue (int index, double value) override
extension value in text form.
Public Member Functions inherited from TColorStyle
TColorStyle (const TColorStyle &other)
Copies another style except its icon.
virtual TColorStyle * clone () const =0
Polymorphic clone of the style.
virtual TColorStyle & copy (const TColorStyle &other)
bool operator== (const TColorStyle &cs) const
bool operator!= (const TColorStyle &cs)
virtual TStrokeProp * makeStrokeProp (const TStroke *stroke)=0
virtual TRegionProp * makeRegionProp (const TRegion *region)=0
used to draw the style on the specified stroke object.
virtual bool isRasterStyle () const
used to draw the style on the specified region object.
virtual TRasterStyleFx * getRasterStyleFx ()
virtual bool isRegionStyle () const =0
Returns whether the style applies on regions.
virtual bool isStrokeStyle () const =0
Returns whether the style applies on strokes.
void setName (std::wstring name)
Sets the style's user-defined name.
std::wstring getName () const
Returns the style's user-defined name.
void setGlobalName (std::wstring name)
Sets the global name of the style.
std::wstring getGlobalName () const
Returns the global name of the style.
void setOriginalName (std::wstring name)
If the style is originally copied from studio palette, set this.
std::wstring getOriginalName () const
Returns the original name of the style.
void setIsEditedFlag (bool edited)
bool getIsEditedFlag () const
style is edited from the original one.
void assignNames (const TColorStyle *src)
Copies the style names from src.
unsigned int getFlags () const
Sets color attributes.
void setFlags (unsigned int flags)
Returns color attributes.
void setPickedPosition (const TPoint &pos, const int index=0)
void setPickedPosition (const PickedPosition &pos)
PickedPosition getPickedPosition () const
virtual bool hasMainColor () const
Returns whether the style has a reference main color.
virtual TPixel32 getMainColor () const
Returns the style's main color, or black if none.
virtual void setMainColor (const TPixel32 &color)
Sets the main color, if it has one.
virtual int getColorParamCount () const
Returns the number of colors (if any) of the style.
virtual TPixel32 getColorParamValue (int index) const
Returns the value of the color of index index.
virtual void setColorParamValue (int index, const TPixel32 &color)
Sets the index-th color value.
virtual TPixel32 getAverageColor () const
Returns a color representing the average of all the style's colors.
virtual int getParamCount () const
virtual ParamType getParamType (int paramIdx) const
Returns the type of the specified parameter.
virtual bool hasParamDefault (int index) const
Value of parameter can be reset to default.
virtual void setParamDefault (int index)
Reset value of parameter to default.
virtual bool isParamDefault (int index) const
Check if current value of parameter equals to default.
virtual void setParamValue (int index, bool value)
Assigns a value to the specified bool parameter.
virtual bool getParamValue (bool_tag, int index) const
Retrieves the specified bool parameter value.
virtual void setParamValue (int index, int value)
Assigns a value to the specified int parameter.
virtual int getParamValue (int_tag, int index) const
Retrieves the specified int parameter value.
virtual void getParamRange (int index, int &min, int &max) const
Retrieves the specified int parameter range.
virtual void getParamRange (int pIndex, QStringList &stringItems) const
virtual void setParamValue (int index, double value)
extension value in text form.
virtual double getParamValue (double_tag, int index) const
Retrieves the specified double parameter value.
virtual void getParamRange (int index, double &min, double &max) const
Retrieves the specified double parameter range.
virtual void setParamValue (int index, const TFilePath &fp)
Assigns a value to the specified TFilePath parameter.
virtual TFilePath getParamValue (TFilePath_tag, int index) const
Retrieves the specified TFilePath parameter value.
void assignBlend (const TColorStyle &a, const TColorStyle &b, double t)
virtual QString getDescription () const =0
Return a brief description of the style.
virtual QString getParamNames (int index) const
Return the string that identifies the index-th parameter.
virtual int getTagId () const =0
Returns an unique number representing the style.
virtual void getObsoleteTagIds (std::vector< int > &) const
void save (TOutputStreamInterface &) const
void invalidateIcon ()
Sets a flag that defines the style's icon validity.
virtual const TRaster32P & getIcon (const TDimension &d)
Returns an image representing the style.
bool isEnabled () const
Returns whether the style can be used.
void enable (bool on)
Sets the style's enabled status.
int getVersionNumber () const
Returns the version number of the style.
Public Member Functions inherited from TSmartObject
TSmartObject (ClassCode classCode)
void addRef ()
void release ()
TINT32 getRefCount () const
Static Public Member Functions
static TFilePath getRootDir ()
static void setRootDir (const TFilePath &path)
Static Public Member Functions inherited from TColorStyle
static TColorStyle * load (TInputStreamInterface &)
static TColorStyle * create (int tagId)
Creates a new style with identifier equal to tagId.
static void declare (TColorStyle *style)
Puts the style in the table of actual styles.
static void getAllTags (std::vector< int > &tags)
Static Public Member Functions inherited from TSmartObject
static TINT32 getInstanceCount (ClassCode code)
Protected Member Functions
void makeIcon (const TDimension &d) override
void loadData (TInputStreamInterface &) override
void loadData (int oldId, TInputStreamInterface &) override
void saveData (TOutputStreamInterface &) const override
Protected Member Functions inherited from TColorStyle
virtual void makeIcon (const TDimension &d)
virtual void loadData (TInputStreamInterface &)=0
virtual void saveData (TOutputStreamInterface &) const =0
virtual void loadData (int, TInputStreamInterface &)
void updateVersionNumber ()
TColorStyle & operator= (const TColorStyle &other)
Copies another style except its icon.
Protected Attributes
TLevelP m_level
std::string m_name
double m_space
double m_rotation
Protected Attributes inherited from TColorStyle
TRaster32P m_icon
Icon shown on TPalette viewers.
bool m_validIcon
Icon's validity status.
Additional Inherited Members
Public Types inherited from TColorStyle
enum ParamType {
BOOL , INT , ENUM , DOUBLE ,
FILEPATH
}
Public Types inherited from TSmartObject
typedef short ClassCode
Static Public Attributes inherited from TColorStyle
static int m_currentFrame = 0
Detailed Description
Constructor & Destructor Documentation
TRasterImagePatternStrokeStyle() [1/2]
TRasterImagePatternStrokeStyle::TRasterImagePatternStrokeStyle ()
    : m_level(), m_name(""), m_space(0), m_rotation(0) {}
TRasterImagePatternStrokeStyle() [2/2]
TRasterImagePatternStrokeStyle::TRasterImagePatternStrokeStyle (const std::string & patternName)
    : m_level(), m_name(patternName), m_space(20), m_rotation(0) {
  if (m_name != "") loadLevel(m_name);
}
Member Function Documentation
clone()
TColorStyle * TRasterImagePatternStrokeStyle::clone () const override virtual
Polymorphic clone of the style.
Implements TColorStyle.
{
  return new TRasterImagePatternStrokeStyle(*this);
}
computeTransformations()
void TRasterImagePatternStrokeStyle::computeTransformations (std::vector< TAffine > & positions, const TStroke * stroke) const
{
  const int frameCount = m_level->getFrameCount();
  if (frameCount == 0) return;
  transformations.clear();
  const double length = stroke->getLength();
  std::vector<TDimensionD> images;
  assert(m_level->begin() != m_level->end());
  TLevel::Iterator lit;
  for (lit = m_level->begin(); lit != m_level->end(); ++lit) {
    TRasterImageP ri = lit->second;
    if (!ri) continue;
    TDimension d = ri->getRaster()->getSize();
    images.push_back(TDimensionD(d.lx, d.ly));
  }
  assert(!images.empty());
  if (images.empty()) return;
  double s  = 0;
  int index = 0;
  int m     = images.size();
  while (s < length) {
    double t      = stroke->getParameterAtLength(s);
    TThickPoint p = stroke->getThickPoint(t);
    TPointD v     = stroke->getSpeed(t);
    double ang    = rad2degree(atan(v)) + m_rotation;
    int ly    = std::max(1.0, images[index].ly);
    double sc = p.thick / ly;
    transformations.push_back(TTranslation(p) * TRotation(ang) * TScale(sc));
    double ds = std::max(2.0, sc * images[index].lx * 2 + m_space);
    s += ds;
  }
}
drawStroke()
void TRasterImagePatternStrokeStyle::drawStroke (const TVectorRenderData & rd, const std::vector< TAffine > & positions, const TStroke * stroke) const
{
  TStopWatch sw;
  sw.start();
  CHECK_GL_ERROR
  const int frameCount = m_level->getFrameCount();
  if (frameCount == 0) return;
  // lo stroke viene disegnato ripetendo size volte le frameCount immagini
  // contenute in level, posizionando ognuna secondo transformations[i]
  UINT size = transformations.size();
  glEnable(GL_TEXTURE_2D);
  glEnable(GL_BLEND);
  glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
  GLuint texId;
  glGenTextures(1, &texId);
  glBindTexture(GL_TEXTURE_2D, texId);
  glTexParameterf(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_REPEAT);
  glTexParameterf(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_REPEAT);
  glTexParameterf(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
  glTexParameterf(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
  // l'utilizzo di modulate, con un colore di 1,1,1,1 permette di
  // tenere in conto il canale alfa delle texture
  glTexEnvf(GL_TEXTURE_ENV, GL_TEXTURE_ENV_MODE, GL_MODULATE);
  glPixelStorei(GL_UNPACK_ROW_LENGTH, 0);
  // visto che cambiare texture costa tempo il ciclo esterno e' sulle textures
  // piuttosto che sulle trasformazioni
  TLevel::Iterator frameIt = m_level->begin();
  for (int i = 0; i < (int)size && frameIt != m_level->end(); ++i, ++frameIt) {
    TRasterImageP ri = frameIt->second;
    TRasterP ras;
    if (ri) ras = ri->getRaster();
    if (!ras) continue;
    TextureInfoForGL texInfo;
    TRasterP texImage = prepareTexture(ras, texInfo);
    glTexImage2D(GL_TEXTURE_2D,
                 0,                       // one level only
                 texInfo.internalformat,  // pixel channels count
                 texInfo.width,           // width
                 texInfo.height,          // height
                 0,                       // border size
                 texInfo.type,    // pixel format           // crappy names
                 texInfo.format,  // pixel data type        // oh, SO much
                 texImage->getRawData());
    for (int j = i; j < (int)size; j += frameCount) {
      TAffine aff = rd.m_aff * transformations[j];
      glPushMatrix();
      tglMultMatrix(aff);
      double rx = ras->getLx();
      double ry = ras->getLy();
      glColor4d(1, 1, 1, 1);
      glBegin(QUAD_PRIMITIVE);
      glTexCoord2d(0, 0);
      glVertex2d(-rx, -ry);
      glTexCoord2d(1, 0);
      glVertex2d(rx, -ry);
      glTexCoord2d(0, 1);
      glVertex2d(-rx, ry);
      glTexCoord2d(1, 1);
      glVertex2d(rx, ry);
      glEnd();
      glPopMatrix();
    }
  }
  glDeleteTextures(1, &texId);
  glDisable(GL_TEXTURE_2D);
  glDisable(GL_BLEND);
}
getDescription()
QString TRasterImagePatternStrokeStyle::getDescription () const inline override virtual
Return a brief description of the style.
\detail For example for a stroke style we have "Constant", "Chain", "Rope", "Tulle", etc...
Implements TColorStyle.
{
    return "TRasterImagePatternStrokeStyle";
  }
getLevelFrameCount()
int TRasterImagePatternStrokeStyle::getLevelFrameCount () inline
{ return m_level->getFrameCount(); }
getMainColor()
TPixel32 TRasterImagePatternStrokeStyle::getMainColor () const inline override virtual
Returns the style's main color, or black if none.
Reimplemented from TColorStyle.
{ return TPixel32::Black; }
getObsoleteTagIds()
void TRasterImagePatternStrokeStyle::getObsoleteTagIds (std::vector< int > & ids) const override virtual
Reimplemented from TColorStyle.
{
  ids.push_back(100);
}
getParamCount()
int TRasterImagePatternStrokeStyle::getParamCount () const override virtual
\detail For example: a the general cleanup style has two parameters, brightness and contrast and a black cleanup style has in addition a black and white threshold, therefore 4 parameters. Returns the number of parameters necessary to describe the style.
Reimplemented from TColorStyle.
{ return 2; }
Referenced by getParamNames(), getParamRange(), getParamType(), getParamValue(), and setParamValue().
getParamNames()
QString TRasterImagePatternStrokeStyle::getParamNames (int index) const override virtual
Return the string that identifies the index-th parameter.
Reimplemented from TColorStyle.
{
  assert(0 <= index && index < getParamCount());
  return (index == 0) ? QCoreApplication::translate(
                            "TRasterImagePatternStrokeStyle", "Distance")
                      : QCoreApplication::translate(
                            "TRasterImagePatternStrokeStyle", "Rotation");
}
References getParamCount().
getParamRange()
void TRasterImagePatternStrokeStyle::getParamRange (int index, double & min, double & max) const override virtual
Retrieves the specified double parameter range.
Reimplemented from TColorStyle.
{
  assert(0 <= index && index < getParamCount());
  if (index == 0) {
    min = -50;
    max = 50;
  } else {
    min = -180;
    max = 180;
  }
}
References getParamCount().
getParamType()
TColorStyle::ParamType TRasterImagePatternStrokeStyle::getParamType (int paramIdx) const override virtual
Returns the type of the specified parameter.
Reimplemented from TColorStyle.
                     {
  assert(0 <= index && index < getParamCount());
  return TColorStyle::DOUBLE;
}
References TColorStyle::DOUBLE, and getParamCount().
getParamValue()
double TRasterImagePatternStrokeStyle::getParamValue (TColorStyle::double_tag , int index) const override virtual
Retrieves the specified double parameter value.
Reimplemented from TColorStyle.
{
  assert(0 <= index && index < getParamCount());
  return (index == 0) ? m_space : m_rotation;
}
References getParamCount().
getRootDir()
TFilePath TRasterImagePatternStrokeStyle::getRootDir () static
{ return m_rootDir; }
getTagId()
int TRasterImagePatternStrokeStyle::getTagId () const inline override virtual
Returns an unique number representing the style.
Implements TColorStyle.
{ return 2000; };
hasMainColor()
bool TRasterImagePatternStrokeStyle::hasMainColor () const inline override virtual
Returns whether the style has a reference main color.
\detail Raster or vector pattern image styles, for example, return false.
Reimplemented from TColorStyle.
{ return false; }
invalidate()
void TRasterImagePatternStrokeStyle::invalidate () inline
{};
isRegionStyle()
bool TRasterImagePatternStrokeStyle::isRegionStyle () const inline override virtual
Returns whether the style applies on regions.
Implements TColorStyle.
{ return false; }
isStrokeStyle()
bool TRasterImagePatternStrokeStyle::isStrokeStyle () const inline override virtual
Returns whether the style applies on strokes.
Implements TColorStyle.
{ return true; }
loadData() [1/2]
void TRasterImagePatternStrokeStyle::loadData (int , TInputStreamInterface &) override protected virtual
Deprecated:
Backward compatibility
Reimplemented from TColorStyle.
{
  if (ids != 100)
    throw TException("image pattern stroke style: unknown obsolete format");
  m_level = TLevelP();
  m_name  = "";
  std::string name;
  is >> name;
  if (name != "") {
    try {
      loadLevel(name);
    } catch (...) {
    }
  }
}
loadData() [2/2]
void TRasterImagePatternStrokeStyle::loadData (TInputStreamInterface & is) override protected virtual
Implements TColorStyle.
{
  m_level = TLevelP();
  m_name  = "";
  std::string name;
  is >> name >> m_space >> m_rotation;
  if (name != "") {
    try {
      loadLevel(name);
    } catch (...) {
    }
  }
}
loadLevel()
void TRasterImagePatternStrokeStyle::loadLevel (const std::string & patternName)
{
  struct locals {
    static TAffine getAffine(const TDimension &srcSize,
                             const TDimension &dstSize) {
      double scx = 1 * dstSize.lx / (double)srcSize.lx;
      double scy = 1 * dstSize.ly / (double)srcSize.ly;
      double sc  = std::min(scx, scy);
      double dx  = (dstSize.lx - srcSize.lx * sc) * 0.5;
      double dy  = (dstSize.ly - srcSize.ly * sc) * 0.5;
      return TScale(sc) * TTranslation(0.5 * TPointD(srcSize.lx, srcSize.ly) +
                                       TPointD(dx, dy));
    }
  };  // locals
  // button l'eventuale livello
  m_level = TLevelP();
  // aggiorno il nome
  m_name = patternName;
  // getRootDir() e' nulla se non si e' chiamata la setRoot(..)
  assert(!getRootDir().isEmpty());
  // leggo tutti i livelli contenuti
  TFilePathSet fps;
  TSystem::readDirectory(fps, getRootDir());
  // prendo il primo livello il cui nome sia patternName
  // (puo' essere un pli, ma anche un png, ecc.)
  TFilePath fp;
  TFilePathSet::iterator fpIt;
  for (fpIt = fps.begin(); fpIt != fps.end(); ++fpIt) {
    if (fpIt->getName() == patternName) {
      fp = *fpIt;
      break;
    }
  }
  // se non ho trovato nulla esco
  if (fp == TFilePath() || !TSystem::doesExistFileOrLevel(fp)) return;
  // Leggo i frames del livello e ne ricavo delle textures
  // che memorizzo in m_level come TRasterImage
  TLevelReaderP lr(fp);
  TLevelP level = lr->loadInfo();
  TLevel::Iterator frameIt;
  TOfflineGL *glContext = 0;
  for (frameIt = level->begin(); frameIt != level->end(); ++frameIt) {
    TImageP img = lr->getFrameReader(frameIt->first)->load();
    if (TRasterImageP ri = img) {
      // se il frame e' raster...
      TRaster32P ras = ri->getRaster();
      if (!ras) continue;
      // aggiusta le dimensioni
      ras = makeTexture(ras);
      if (!ras) continue;
      m_level->setFrame(frameIt->first, new TRasterImage(ras));
    } else if (TVectorImageP vi = img) {
      // se il frame e' vettoriale
      // lo rasterizzo creando una texture 256x256 (N.B. le dimensioni
      // delle textures openGL devono essere potenze di due)
      TRaster32P ras(256, 256);
      // se serve creo il contesto OpenGL offline (l'idea e' di crearne
      // uno solo per tutto il livello
      if (!glContext) glContext = new TOfflineGL(ras->getSize());
      // camera di default 640x480. probabilmente non e' la scelta
      // migliore.
      // TDimension cameraSize(768, 576);
      TDimension cameraSize(1920, 1080);
      // definisco i renderdata
      const TVectorRenderData rd(locals::getAffine(cameraSize, ras->getSize()),
                                 TRect(), level->getPalette(), 0, true, true);
      // rasterizzo
      glContext->draw(vi, rd);
      ras->copy(glContext->getRaster());
      m_level->setFrame(frameIt->first, new TRasterImage(ras));
    }
  }
  // cancello il contesto offline (se e' stato creato)
  delete glContext;
}
makeIcon()
void TRasterImagePatternStrokeStyle::makeIcon (const TDimension & d) override protected virtual
Reimplemented from TColorStyle.
{
  if (!m_level) loadLevel(m_name);
  m_icon                   = TRaster32P();
  TLevel::Iterator frameIt = m_level->begin();
  if (frameIt != m_level->end()) {
    TRasterImageP img = frameIt->second;
    TRaster32P src;
    if (img) src = img->getRaster();
    if (src && src->getLx() > 1 && src->getLy() > 1) {
      TRaster32P icon(size);
      icon->fill(TPixel32::White);
      double sx = (double)icon->getLx() / (double)src->getLx();
      double sy = (double)icon->getLy() / (double)src->getLy();
      double sc = 0.8 * std::min(sx, sy);
      TRop::resample(icon, src,
                     TScale(sc).place(src->getCenterD(), icon->getCenterD()));
      TRop::addBackground(icon, TPixel32::White);
      m_icon = icon;
    }
  }
  if (!m_icon) {
    TRaster32P icon(size);
    icon->fill(TPixel32::Black);
    int lx = icon->getLx();
    int ly = icon->getLy();
    for (int y = 0; y < ly; y++) {
      int x = ((lx - 1 - 10) * y / ly);
      icon->extractT(x, y, x + 5, y)->fill(TPixel32::Red);
    }
    m_icon = icon;
    return;
  }
}
makeRegionProp()
TRegionProp * TRasterImagePatternStrokeStyle::makeRegionProp (const TRegion * region) inline override virtual
used to draw the style on the specified stroke object.
Allocates a new derived TRegionProp instance
Implements TColorStyle.
{
    assert(false);
    return 0;
  };
makeStrokeProp()
TStrokeProp * TRasterImagePatternStrokeStyle::makeStrokeProp (const TStroke * stroke) override virtual
Allocates a new derived TStrokeProp instance
Implements TColorStyle.
{
  return new TRasterImagePatternStrokeProp(stroke, this);
}
saveData()
void TRasterImagePatternStrokeStyle::saveData (TOutputStreamInterface & os) const override protected virtual
Implements TColorStyle.
{
  os << m_name << m_space << m_rotation;
}
setMainColor()
void TRasterImagePatternStrokeStyle::setMainColor (const TPixel32 & color) inline override virtual
Sets the main color, if it has one.
Reimplemented from TColorStyle.
{}
setParamValue()
void TRasterImagePatternStrokeStyle::setParamValue (int index, double value) override virtual
extension value in text form.
Assigns a value to the specified double parameter.
Reimplemented from TColorStyle.
{
  assert(0 <= index && index < getParamCount());
  if (index == 0) {
    if (m_space != value) {
      updateVersionNumber();  // aggiorna il vettore di affini
    }
    m_space = value;
  } else {
    if (m_rotation != value) {
      updateVersionNumber();  // aggiorna il vettore di affini
    }
    m_rotation = value;
  }
}
References getParamCount().
setRootDir()
static void TRasterImagePatternStrokeStyle::setRootDir (const TFilePath & path) inline static
{
    m_rootDir = path + "custom styles";
  }
Member Data Documentation
m_level
TLevelP TRasterImagePatternStrokeStyle::m_level protected
m_name
std::string TRasterImagePatternStrokeStyle::m_name protected
m_rotation
double TRasterImagePatternStrokeStyle::m_rotation protected
m_space
double TRasterImagePatternStrokeStyle::m_space protected
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/tsimplecolorstyles.h
E:/opentoonz/toonz/sources/common/tvrender/tsimplecolorstyles.cpp