opentoonz: FullColorBrushTool Class Reference
FullColorBrushTool Class Reference final
Public Member Functions
FullColorBrushTool (std::string name)
ToolType getToolType () const override
ToolOptionsBox * createOptionsBox () override
void updateTranslation () override
void onActivate () override
Callback invoked whenever the tool activates.
void onDeactivate () override
Callback for tool deactivation, includes tool switch.
bool askRead (const TRect &rect) override
bool askWrite (const TRect &rect) override
bool preLeftButtonDown () override
void leftButtonDown (const TPointD &pos, const TMouseEvent &e) override
void leftButtonDrag (const TPointD &pos, const TMouseEvent &e) override
void leftButtonUp (const TPointD &pos, const TMouseEvent &e) override
void mouseMove (const TPointD &pos, const TMouseEvent &e) override
void draw () override
Draws the tool on the viewer.
void onEnter () override
Callback for the mouse entering the viewer area.
void onLeave () override
Callback for the mouse leaving the viewer area.
int getCursorId () const override
Returns the type of cursor used by the tool.
TPropertyGroup * getProperties (int targetType) override
bool onPropertyChanged (std::string propertyName) override
void onImageChanged () override
Notifies changes in the image in use.
void setWorkAndBackupImages ()
void updateWorkAndBackupRasters (const TRect &rect)
void initPresets ()
void loadPreset ()
void addPreset (QString name)
void removePreset ()
void loadLastBrush ()
void onCanvasSizeChanged ()
void onColorStyleChanged ()
TMyPaintBrushStyle * getBrushStyle ()
Public Member Functions inherited from TTool
TTool (std::string toolName)
every tool (invoking updateTranslation() for each).
virtual ToolType getToolType () const =0
ToolTargetType getTargetType () const
std::string getName () const
virtual ToolOptionsBox * createOptionsBox ()
void setViewer (Viewer *viewer)
Viewer * getViewer () const
double getPixelSize () const
void invalidate (const TRectD &rect=TRectD())
int pick (const TPointD &p)
bool isPicking () const
virtual void updateTranslation ()
virtual bool preLeftButtonDown ()
virtual void mouseMove (const TPointD &, const TMouseEvent &)
virtual void leftButtonDown (const TPointD &, const TMouseEvent &)
virtual void leftButtonDrag (const TPointD &, const TMouseEvent &)
virtual void leftButtonUp (const TPointD &, const TMouseEvent &)
virtual void leftButtonDoubleClick (const TPointD &, const TMouseEvent &)
virtual void rightButtonDown (const TPointD &, const TMouseEvent &)
virtual bool keyDown (QKeyEvent *)
virtual void onInputText (std::wstring, std::wstring, int, int)
virtual void onSetViewer ()
virtual void onActivate ()
Callback invoked whenever the tool activates.
virtual void onDeactivate ()
Callback for tool deactivation, includes tool switch.
virtual void onImageChanged ()
Notifies changes in the image in use.
virtual void onEnter ()
Callback for the mouse entering the viewer area.
virtual void onLeave ()
Callback for the mouse leaving the viewer area.
virtual void onFrameSwitched ()
virtual void reset ()
virtual void draw ()
Draws the tool on the viewer.
bool isActive () const
Used to know if a tool is active, (used in TextTool only).
void setActive (bool active)
virtual TPropertyGroup * getProperties (int)
virtual bool onPropertyChanged (std::string propertyName)
virtual TSelection * getSelection ()
Returns a pointer to the tool selection.
virtual int getCursorId () const
Returns the type of cursor used by the tool.
virtual bool isEventAcceptable (QEvent *e)
TXsheet * getXsheet () const
Returns a pointer to the actual Xsheet.
int getFrame ()
Returns the actual frame in use.
int getColumnIndex ()
Returns the actual column index.
TStageObjectId getObjectId () const
Returns a pointer to the actual stage object.
void notifyImageChanged ()
void notifyImageChanged (const TFrameId &fid)
images on the level view.
TFrameId getCurrentFid () const
Returns the number of the actual editing frame.
const TAffine & getMatrix () const
void setMatrix (const TAffine &matrix)
TAffine getCurrentColumnMatrix (int frame=-1) const
TAffine getCurrentColumnParentMatrix () const
TAffine getCurrentObjectParentMatrix () const
TAffine getCurrentObjectParentMatrix2 () const
TAffine getColumnMatrix (int index, int frame=-1) const
virtual void updateMatrix ()
virtual void addContextMenuItems (QMenu *menu)
void enable (bool on)
bool isEnabled () const
QString updateEnabled ()
virtual QString updateEnabled (int rowIndex, int columnIndex)
bool isColumnLocked (int columnIndex) const
void resetInputMethod ()
Resets Input Context (IME)
virtual bool isPencilModeActive ()
virtual bool isDragging () const
void setSelectedFrames (const std::set< TFrameId > &selectedFrames)
void tweenSelectedGuideStrokes ()
void tweenGuideStrokeToSelected ()
void flipGuideStrokeDirection (int mode)
virtual bool askRead (const TRect &rect)
virtual bool askWrite (const TRect &rect)
Protected Attributes
TPropertyGroup m_prop
TIntPairProperty m_thickness
TBoolProperty m_pressure
TDoublePairProperty m_opacity
TDoubleProperty m_hardness
TDoubleProperty m_modifierSize
TDoubleProperty m_modifierOpacity
TBoolProperty m_modifierEraser
TBoolProperty m_modifierLockAlpha
TEnumProperty m_preset
TPixel32 m_currentColor
bool m_enabledPressure
int m_minCursorThick
int m_maxCursorThick
TPointD m_mousePos
Current mouse position, in world coordinates.
TPointD m_brushPos
World position the brush will be painted at.
TRasterP m_backUpRas
TRaster32P m_workRaster
TRect m_strokeRect
TRect m_strokeSegmentRect
TRect m_lastRect
MyPaintToonzBrush * m_toonz_brush
QElapsedTimer m_brushTimer
TTileSetFullColor * m_tileSet
TTileSaverFullColor * m_tileSaver
BrushPresetManager m_presetsManager
Manager for presets of this tool instance.
FullColorBrushToolNotifier * m_notifier
bool m_presetsLoaded
bool m_firstTime
bool m_mousePressed = false
TMouseEvent m_mouseEvent
bool m_propertyUpdating = false
Protected Attributes inherited from TTool
std::string m_name
The tool's name.
Viewer * m_viewer
Tool's current viewer.
TAffine m_matrix
World-to-window reference change affine.
int m_targetType
The tool's image type target.
bool m_enabled
Whether the tool allows user interaction.
bool m_active
bool m_picking
Additional Inherited Members
Public Types inherited from TTool
enum ToolType {
GenericTool = 1 , ColumnTool = 2 , LevelReadTool = 4 , LevelWriteTool ,
LevelTool = LevelReadTool | LevelWriteTool
}
Tool editing type.
enum ToolTargetType {
NoTarget = 0x0 , VectorImage = 0x1 , ToonzImage = 0x2 , RasterImage = 0x4 ,
MeshImage = 0x8 , Splines = 0x10 , LevelColumns = 0x20 , MeshColumns = 0x40 ,
EmptyTarget = 0x80 , CommonImages = VectorImage | ToonzImage | RasterImage , AllImages = CommonImages | MeshImage , Vectors = VectorImage | Splines ,
CommonLevels = CommonImages | LevelColumns , MeshLevels = MeshImage | MeshColumns , AllTargets = 0xffffffff
}
Object types the tool can operate on.
typedef TApplication Application
Static Public Member Functions inherited from TTool
static TTool * getTool (std::string toolName, ToolTargetType targetType)
static TApplication * getApplication ()
static void setApplication (TApplication *application)
static TXshCell getImageCell ()
Returns the level-frame pair to be edited by the tool.
static TImage * getImage (bool toBeModified, int subsampling=0)
Returns the image to be edited by the tool.
static TImage * touchImage ()
static void updateToolsPropertiesTranslation ()
static const std::set< TFrameId > & getSelectedFrames ()
Static Public Attributes inherited from TTool
static std::vector< CellOps > m_cellsData
static bool m_isLevelCreated = false
static bool m_isFrameCreated = false
static std::vector< TFrameId > m_oldFids
static std::vector< TFrameId > m_newFids
static bool m_isLevelRenumbererd = false
Protected Member Functions inherited from TTool
void bind (int targetType)
virtual void onSelectedFramesChanged ()
virtual QString disableString ()
Returns a custom reason to disable the tool.
Static Protected Attributes inherited from TTool
static TApplication * m_application = 0
static std::set< TFrameId > m_selectedFrames = std::set<TFrameId>()
Detailed Description
Constructor & Destructor Documentation
FullColorBrushTool()
FullColorBrushTool::FullColorBrushTool (std::string name)
    : TTool(name)
    , m_thickness("Size", 1, 1000, 1, 5, false)
    , m_pressure("Pressure", true)
    , m_opacity("Opacity", 0, 100, 100, 100, true)
    , m_hardness("Hardness:", 0, 100, 100)
    , m_modifierSize("ModifierSize", -3, 3, 0, true)
    , m_modifierOpacity("ModifierOpacity", 0, 100, 100, true)
    , m_modifierEraser("ModifierEraser", false)
    , m_modifierLockAlpha("Lock Alpha", false)
    , m_preset("Preset:")
    , m_minCursorThick(0)
    , m_maxCursorThick(0)
    , m_enabledPressure(false)
    , m_toonz_brush(0)
    , m_tileSet(0)
    , m_tileSaver(0)
    , m_notifier(0)
    , m_presetsLoaded(false)
    , m_firstTime(true) {
  bind(TTool::RasterImage | TTool::EmptyTarget);
  m_thickness.setNonLinearSlider();
  m_prop.bind(m_thickness);
  m_prop.bind(m_hardness);
  m_prop.bind(m_opacity);
  m_prop.bind(m_modifierSize);
  m_prop.bind(m_modifierOpacity);
  m_prop.bind(m_modifierEraser);
  m_prop.bind(m_modifierLockAlpha);
  m_prop.bind(m_pressure);
  m_prop.bind(m_preset);
  m_preset.setId("BrushPreset");
  m_modifierEraser.setId("RasterEraser");
  m_modifierLockAlpha.setId("LockAlpha");
  m_pressure.setId("PressureSensitivity");
  m_brushTimer.start();
}
Member Function Documentation
addPreset()
void FullColorBrushTool::addPreset (QString name)
{
  // Build the preset
  BrushData preset(name.toStdWString());
  preset.m_min               = m_thickness.getValue().first;
  preset.m_max               = m_thickness.getValue().second;
  preset.m_hardness          = m_hardness.getValue();
  preset.m_opacityMin        = m_opacity.getValue().first;
  preset.m_opacityMax        = m_opacity.getValue().second;
  preset.m_pressure          = m_pressure.getValue();
  preset.m_modifierSize      = m_modifierSize.getValue();
  preset.m_modifierOpacity   = m_modifierOpacity.getValue();
  preset.m_modifierEraser    = m_modifierEraser.getValue();
  preset.m_modifierLockAlpha = m_modifierLockAlpha.getValue();
  // Pass the preset to the manager
  m_presetsManager.addPreset(preset);
  // Reinitialize the associated preset enum
  initPresets();
  // Set the value to the specified one
  m_preset.setValue(preset.m_name);
  FullcolorBrushPreset = m_preset.getValueAsString();
}
askRead()
bool FullColorBrushTool::askRead (const TRect & rect) override virtual
Reimplemented from RasterController.
{ return askWrite(rect); }
askWrite()
bool FullColorBrushTool::askWrite (const TRect & rect) override virtual
Reimplemented from RasterController.
{
  if (rect.isEmpty()) return true;
  m_strokeRect += rect;
  m_strokeSegmentRect += rect;
  updateWorkAndBackupRasters(rect);
  m_tileSaver->save(rect);
  return true;
}
createOptionsBox()
ToolOptionsBox * FullColorBrushTool::createOptionsBox () override virtual
The default returns a generic box containing the options for property group 0).
See also
See tooloptions.h for more details. Factory function returning a newly created GUI options box to be displayed for the tool
Reimplemented from TTool.
{
  TPaletteHandle *currPalette =
      TTool::getApplication()->getPaletteController()->getCurrentLevelPalette();
  ToolHandle *currTool = TTool::getApplication()->getCurrentTool();
  return new BrushToolOptionsBox(0, this, currPalette, currTool);
}
draw()
void FullColorBrushTool::draw () override virtual
Draws the tool on the viewer.
Reimplemented from TTool.
{
  if (TRasterImageP ri = TRasterImageP(getImage(false))) {
    // If toggled off, don't draw brush outline
    if (!Preferences::instance()->isCursorOutlineEnabled()) return;
    TRasterP ras = ri->getRaster();
    double alpha       = 1.0;
    double alphaRadius = 3.0;
    double pixelSize   = sqrt(tglGetPixelSize2());
    // circles with lesser radius looks more bold
    // to avoid these effect we'll reduce alpha for small radiuses
    double minX     = m_minCursorThick / (alphaRadius * pixelSize);
    double maxX     = m_maxCursorThick / (alphaRadius * pixelSize);
    double minAlpha = alpha * (1.0 - 1.0 / (1.0 + minX));
    double maxAlpha = alpha * (1.0 - 1.0 / (1.0 + maxX));
    glPushAttrib(GL_ALL_ATTRIB_BITS);
    tglEnableBlending();
    tglEnableLineSmooth(true, 0.5);
    if (m_minCursorThick < m_maxCursorThick - pixelSize) {
      glColor4d(1.0, 1.0, 1.0, minAlpha);
      tglDrawCircle(m_brushPos, (m_minCursorThick + 1) * 0.5 - pixelSize);
      glColor4d(0.0, 0.0, 0.0, minAlpha);
      tglDrawCircle(m_brushPos, (m_minCursorThick + 1) * 0.5);
    }
    glColor4d(1.0, 1.0, 1.0, maxAlpha);
    tglDrawCircle(m_brushPos, (m_maxCursorThick + 1) * 0.5 - pixelSize);
    glColor4d(0.0, 0.0, 0.0, maxAlpha);
    tglDrawCircle(m_brushPos, (m_maxCursorThick + 1) * 0.5);
    glPopAttrib();
  }
}
References TTool::getImage(), and m_brushPos.
getBrushStyle()
TMyPaintBrushStyle * FullColorBrushTool::getBrushStyle ()
{
  if (TTool::Application *app = getApplication())
    return dynamic_cast<TMyPaintBrushStyle *>(app->getCurrentLevelStyle());
  return 0;
}
getCursorId()
int FullColorBrushTool::getCursorId () const inline override virtual
Returns the type of cursor used by the tool.
See also
For a list of cursor ids cursor.h
Reimplemented from TTool.
{ return ToolCursor::PenCursor; }
getProperties()
TPropertyGroup * FullColorBrushTool::getProperties (int targetType) override virtual
Reimplemented from TTool.
{
  if (!m_presetsLoaded) initPresets();
  return &m_prop;
}
getToolType()
ToolType FullColorBrushTool::getToolType () const inline override virtual
Implements TTool.
{ return TTool::LevelWriteTool; }
initPresets()
void FullColorBrushTool::initPresets ()
{
  if (!m_presetsLoaded) {
    // If necessary, load the presets from file
    m_presetsLoaded = true;
    m_presetsManager.load(TEnv::getConfigDir() + "brush_raster.txt");
  }
  // Rebuild the presets property entries
  const std::set<BrushData> &presets = m_presetsManager.presets();
  m_preset.deleteAllValues();
  m_preset.addValue(CUSTOM_WSTR);
  m_preset.setItemUIName(CUSTOM_WSTR, tr("<custom>"));
  std::set<BrushData>::const_iterator it, end = presets.end();
  for (it = presets.begin(); it != end; ++it) m_preset.addValue(it->m_name);
}
leftButtonDown()
void FullColorBrushTool::leftButtonDown (const TPointD & pos, const TMouseEvent & e) override virtual
Reimplemented from TTool.
{
  TPointD previousBrushPos = m_brushPos;
  m_brushPos = m_mousePos = pos;
  m_mousePressed          = true;
  m_mouseEvent            = e;
  Viewer *viewer          = getViewer();
  if (!viewer) return;
  TRasterImageP ri = (TRasterImageP)getImage(true);
  if (!ri) ri = (TRasterImageP)touchImage();
  if (!ri) return;
  /* update color here since the current style might be switched with numpad
   * shortcut keys */
  updateCurrentStyle();
  TRasterP ras = ri->getRaster();
  if (!(m_workRaster && m_backUpRas)) setWorkAndBackupImages();
  m_workRaster->lock();
  TPointD rasCenter = ras->getCenterD();
  TPointD point(pos + rasCenter);
  double pressure;
  if (getApplication()->getCurrentLevelStyle()->getTagId() ==
      4001)  // mypaint brush case
    pressure = m_enabledPressure && e.isTablet() ? e.m_pressure : 0.5;
  else
    pressure = m_enabledPressure ? e.m_pressure : 1.0;
  m_tileSet   = new TTileSetFullColor(ras->getSize());
  m_tileSaver = new TTileSaverFullColor(ras, m_tileSet);
  mypaint::Brush mypaintBrush;
  applyToonzBrushSettings(mypaintBrush);
  m_toonz_brush = new MyPaintToonzBrush(m_workRaster, *this, mypaintBrush);
  m_strokeRect.empty();
  m_strokeSegmentRect.empty();
  m_toonz_brush->beginStroke();
  m_toonz_brush->strokeTo(point, pressure, restartBrushTimer());
  TRect updateRect = m_strokeSegmentRect * ras->getBounds();
  if (!updateRect.isEmpty())
    ras->extract(updateRect)->copy(m_workRaster->extract(updateRect));
  TPointD thickOffset(m_maxCursorThick * 0.5, m_maxCursorThick * 0.5);
  TRectD invalidateRect = convert(m_strokeSegmentRect) - rasCenter;
  invalidateRect += TRectD(m_brushPos - thickOffset, m_brushPos + thickOffset);
  invalidateRect +=
      TRectD(previousBrushPos - thickOffset, previousBrushPos + thickOffset);
  invalidate(invalidateRect.enlarge(2.0));
}
leftButtonDrag()
void FullColorBrushTool::leftButtonDrag (const TPointD & pos, const TMouseEvent & e) override virtual
Reimplemented from TTool.
{
  TPointD previousBrushPos = m_brushPos;
  m_brushPos = m_mousePos = pos;
  m_mouseEvent            = e;
  TRasterImageP ri        = (TRasterImageP)getImage(true);
  if (!ri) return;
  if (!m_toonz_brush) return;
  TRasterP ras      = ri->getRaster();
  TPointD rasCenter = ras->getCenterD();
  TPointD point(pos + rasCenter);
  double pressure;
  if (getApplication()->getCurrentLevelStyle()->getTagId() ==
      4001)  // mypaint brush case
    pressure = m_enabledPressure && e.isTablet() ? e.m_pressure : 0.5;
  else
    pressure = m_enabledPressure ? e.m_pressure : 1.0;
  m_strokeSegmentRect.empty();
  m_toonz_brush->strokeTo(point, pressure, restartBrushTimer());
  TRect updateRect = m_strokeSegmentRect * ras->getBounds();
  if (!updateRect.isEmpty())
    ras->extract(updateRect)->copy(m_workRaster->extract(updateRect));
  TPointD thickOffset(m_maxCursorThick * 0.5, m_maxCursorThick * 0.5);
  TRectD invalidateRect = convert(m_strokeSegmentRect) - rasCenter;
  invalidateRect += TRectD(m_brushPos - thickOffset, m_brushPos + thickOffset);
  invalidateRect +=
      TRectD(previousBrushPos - thickOffset, previousBrushPos + thickOffset);
  invalidate(invalidateRect.enlarge(2.0));
}
leftButtonUp()
void FullColorBrushTool::leftButtonUp (const TPointD & pos, const TMouseEvent & e) override virtual
Reimplemented from TTool.
{
  TPointD previousBrushPos = m_brushPos;
  m_brushPos = m_mousePos = pos;
  TRasterImageP ri = (TRasterImageP)getImage(true);
  if (!ri) return;
  if (!m_toonz_brush) return;
  TRasterP ras      = ri->getRaster();
  TPointD rasCenter = ras->getCenterD();
  TPointD point(pos + rasCenter);
  double pressure;
  if (getApplication()->getCurrentLevelStyle()->getTagId() ==
      4001)  // mypaint brush case
    pressure = m_enabledPressure && e.isTablet() ? e.m_pressure : 0.5;
  else
    pressure = m_enabledPressure ? e.m_pressure : 1.0;
  m_strokeSegmentRect.empty();
  m_toonz_brush->strokeTo(point, pressure, restartBrushTimer());
  m_toonz_brush->endStroke();
  TRect updateRect = m_strokeSegmentRect * ras->getBounds();
  if (!updateRect.isEmpty())
    ras->extract(updateRect)->copy(m_workRaster->extract(updateRect));
  TPointD thickOffset(m_maxCursorThick * 0.5, m_maxCursorThick * 0.5);
  TRectD invalidateRect = convert(m_strokeSegmentRect) - rasCenter;
  invalidateRect += TRectD(m_brushPos - thickOffset, m_brushPos + thickOffset);
  invalidateRect +=
      TRectD(previousBrushPos - thickOffset, previousBrushPos + thickOffset);
  invalidate(invalidateRect.enlarge(2.0));
  if (m_toonz_brush) {
    delete m_toonz_brush;
    m_toonz_brush = 0;
  }
  m_lastRect.empty();
  m_workRaster->unlock();
  if (m_tileSet->getTileCount() > 0) {
    delete m_tileSaver;
    TTool::Application *app   = TTool::getApplication();
    TXshLevel *level          = app->getCurrentLevel()->getLevel();
    TXshSimpleLevelP simLevel = level->getSimpleLevel();
    TFrameId frameId          = getCurrentFid();
    TRasterP subras           = ras->extract(m_strokeRect)->clone();
    TUndoManager::manager()->add(new FullColorBrushUndo(
        m_tileSet, simLevel.getPointer(), frameId, m_isFrameCreated, subras,
        m_strokeRect.getP00()));
  }
  notifyImageChanged();
  m_strokeRect.empty();
  m_mousePressed = false;
}
loadLastBrush()
void FullColorBrushTool::loadLastBrush ()
{
  m_thickness.setValue(
      TIntPairProperty::Value(FullcolorBrushMinSize, FullcolorBrushMaxSize));
  m_pressure.setValue(FullcolorPressureSensitivity ? 1 : 0);
  m_opacity.setValue(
      TDoublePairProperty::Value(FullcolorMinOpacity, FullcolorMaxOpacity));
  m_hardness.setValue(FullcolorBrushHardness);
  m_modifierSize.setValue(FullcolorModifierSize);
  m_modifierOpacity.setValue(FullcolorModifierOpacity);
  m_modifierEraser.setValue(FullcolorModifierEraser ? true : false);
  m_modifierLockAlpha.setValue(FullcolorModifierLockAlpha ? true : false);
}
loadPreset()
void FullColorBrushTool::loadPreset ()
{
  const std::set<BrushData> &presets = m_presetsManager.presets();
  std::set<BrushData>::const_iterator it;
  it = presets.find(BrushData(m_preset.getValue()));
  if (it == presets.end()) return;
  const BrushData &preset = *it;
  try  // Don't bother with RangeErrors
  {
    m_thickness.setValue(
        TIntPairProperty::Value(std::max((int)preset.m_min, 1), preset.m_max));
    m_hardness.setValue(preset.m_hardness, true);
    m_opacity.setValue(
        TDoublePairProperty::Value(preset.m_opacityMin, preset.m_opacityMax));
    m_pressure.setValue(preset.m_pressure);
    m_modifierSize.setValue(preset.m_modifierSize);
    m_modifierOpacity.setValue(preset.m_modifierOpacity);
    m_modifierEraser.setValue(preset.m_modifierEraser);
    m_modifierLockAlpha.setValue(preset.m_modifierLockAlpha);
  } catch (...) {
  }
}
mouseMove()
void FullColorBrushTool::mouseMove (const TPointD & pos, const TMouseEvent & e) override virtual
Reimplemented from TTool.
{
  struct Locals {
    FullColorBrushTool *m_this;
    void setValue(TIntPairProperty &prop,
                  const TIntPairProperty::Value &value) {
      prop.setValue(value);
      m_this->onPropertyChanged(prop.getName());
      TTool::getApplication()->getCurrentTool()->notifyToolChanged();
    }
    void addMinMax(TIntPairProperty &prop, double add) {
      const TIntPairProperty::Range &range = prop.getRange();
      TIntPairProperty::Value value = prop.getValue();
      value.second =
          tcrop<double>(value.second + add, range.first, range.second);
      value.first = tcrop<double>(value.first + add, range.first, range.second);
      setValue(prop, value);
    }
    void addMinMaxSeparate(TIntPairProperty &prop, double min, double max) {
      if (min == 0.0 && max == 0.0) return;
      const TIntPairProperty::Range &range = prop.getRange();
      TIntPairProperty::Value value = prop.getValue();
      value.first += min;
      value.second += max;
      if (value.first > value.second) value.first = value.second;
      value.first  = tcrop<double>(value.first, range.first, range.second);
      value.second = tcrop<double>(value.second, range.first, range.second);
      setValue(prop, value);
    }
  } locals = {this};
  // if (e.isAltPressed() && !e.isCtrlPressed()) {
  // const TPointD &diff = pos - m_mousePos;
  // double add = (fabs(diff.x) > fabs(diff.y)) ? diff.x : diff.y;
  // locals.addMinMax(m_thickness, int(add));
  //} else
  if (e.isCtrlPressed() && e.isAltPressed()) {
    const TPointD &diff = pos - m_mousePos;
    double max          = diff.x / 2;
    double min          = diff.y / 2;
    locals.addMinMaxSeparate(m_thickness, int(min), int(max));
  } else {
    m_brushPos = pos;
  }
  m_mousePos = pos;
  invalidate();
}
onActivate()
void FullColorBrushTool::onActivate () override virtual
Callback invoked whenever the tool activates.
Reimplemented from TTool.
{
  if (!m_notifier) m_notifier = new FullColorBrushToolNotifier(this);
  updateCurrentStyle();
  if (m_firstTime) {
    m_firstTime = false;
    std::wstring wpreset =
        QString::fromStdString(FullcolorBrushPreset.getValue()).toStdWString();
    if (wpreset != CUSTOM_WSTR) {
      initPresets();
      if (!m_preset.isValue(wpreset)) wpreset = CUSTOM_WSTR;
      m_preset.setValue(wpreset);
      FullcolorBrushPreset = m_preset.getValueAsString();
      loadPreset();
    } else
      loadLastBrush();
  }
  setWorkAndBackupImages();
  onColorStyleChanged();
}
onCanvasSizeChanged()
void FullColorBrushTool::onCanvasSizeChanged ()
{
  onDeactivate();
  setWorkAndBackupImages();
}
onColorStyleChanged()
void FullColorBrushTool::onColorStyleChanged ()
{
  getApplication()->getCurrentTool()->notifyToolChanged();
}
onDeactivate()
void FullColorBrushTool::onDeactivate () override virtual
Callback for tool deactivation, includes tool switch.
Reimplemented from TTool.
{
  if (m_mousePressed) leftButtonUp(m_mousePos, m_mouseEvent);
  m_workRaster = TRaster32P();
  m_backUpRas  = TRasterP();
}
References m_mousePos.
onEnter()
void FullColorBrushTool::onEnter () override virtual
Callback for the mouse entering the viewer area.
Reimplemented from TTool.
{ updateCurrentStyle(); }
onImageChanged()
void FullColorBrushTool::onImageChanged () override virtual
Notifies changes in the image in use.
Reimplemented from TTool.
{ setWorkAndBackupImages(); }
onLeave()
void FullColorBrushTool::onLeave () override virtual
Callback for the mouse leaving the viewer area.
Reimplemented from TTool.
{
  m_minCursorThick = 0;
  m_maxCursorThick = 0;
}
onPropertyChanged()
bool FullColorBrushTool::onPropertyChanged (std::string propertyName) override virtual
 Does the tasks associated to changes in \p propertyName and returns \p
true; Does the tasks associated to changes in propertyName and returns true.
Reimplemented from TTool.
{
  if (m_propertyUpdating) return true;
  updateCurrentStyle();
  if (propertyName == "Preset:") {
    if (m_preset.getValue() != CUSTOM_WSTR)
      loadPreset();
    else  // Chose <custom>, go back to last saved brush settings
      loadLastBrush();
    FullcolorBrushPreset = m_preset.getValueAsString();
    m_propertyUpdating   = true;
    getApplication()->getCurrentTool()->notifyToolChanged();
    m_propertyUpdating = false;
    return true;
  }
  FullcolorBrushMinSize        = m_thickness.getValue().first;
  FullcolorBrushMaxSize        = m_thickness.getValue().second;
  FullcolorPressureSensitivity = m_pressure.getValue();
  FullcolorBrushHardness       = m_hardness.getValue();
  FullcolorMinOpacity          = m_opacity.getValue().first;
  FullcolorMaxOpacity          = m_opacity.getValue().second;
  FullcolorModifierSize        = m_modifierSize.getValue();
  FullcolorModifierOpacity     = m_modifierOpacity.getValue();
  FullcolorModifierEraser      = m_modifierEraser.getValue() ? 1 : 0;
  FullcolorModifierLockAlpha   = m_modifierLockAlpha.getValue() ? 1 : 0;
  if (m_preset.getValue() != CUSTOM_WSTR) {
    m_preset.setValue(CUSTOM_WSTR);
    FullcolorBrushPreset = m_preset.getValueAsString();
    m_propertyUpdating   = true;
    getApplication()->getCurrentTool()->notifyToolChanged();
    m_propertyUpdating = false;
  }
  return true;
}
References ToolHandle::notifyToolChanged().
preLeftButtonDown()
bool FullColorBrushTool::preLeftButtonDown () override virtual
This method is called before leftButtonDown() and can be used e.g. to create the image if needed. return true if the method execution can have changed the current tool
Reimplemented from TTool.
{
  touchImage();
  if (m_isFrameCreated) {
    setWorkAndBackupImages();
    // When the xsheet frame is selected, whole viewer will be updated from
    // SceneViewer::onXsheetChanged() on adding a new frame.
    // We need to take care of a case when the level frame is selected.
    if (m_application->getCurrentFrame()->isEditingLevel()) invalidate();
  }
  return true;
}
References TTool::invalidate(), TTool::m_isFrameCreated, and TTool::touchImage().
removePreset()
void FullColorBrushTool::removePreset ()
{
  std::wstring name(m_preset.getValue());
  if (name == CUSTOM_WSTR) return;
  m_presetsManager.removePreset(name);
  initPresets();
  // No parameter change, and set the preset value to custom
  m_preset.setValue(CUSTOM_WSTR);
  FullcolorBrushPreset = m_preset.getValueAsString();
}
setWorkAndBackupImages()
void FullColorBrushTool::setWorkAndBackupImages ()
{
  TRasterImageP ri = (TRasterImageP)getImage(false, 1);
  if (!ri) return;
  TRasterP ras   = ri->getRaster();
  TDimension dim = ras->getSize();
  if (!m_workRaster || m_workRaster->getLx() != dim.lx ||
      m_workRaster->getLy() != dim.ly)
    m_workRaster = TRaster32P(dim);
  if (!m_backUpRas || m_backUpRas->getLx() != dim.lx ||
      m_backUpRas->getLy() != dim.ly ||
      m_backUpRas->getPixelSize() != ras->getPixelSize())
    m_backUpRas = ras->create(dim.lx, dim.ly);
  m_strokeRect.empty();
  m_lastRect.empty();
}
updateTranslation()
void FullColorBrushTool::updateTranslation () override virtual
Reimplemented from TTool.
{
  m_thickness.setQStringName(tr("Size"));
  m_pressure.setQStringName(tr("Pressure"));
  m_opacity.setQStringName(tr("Opacity"));
  m_hardness.setQStringName(tr("Hardness:"));
  m_preset.setQStringName(tr("Preset:"));
  m_modifierSize.setQStringName(tr("Size"));
  m_modifierOpacity.setQStringName(tr("Opacity"));
  m_modifierEraser.setQStringName(tr("Eraser"));
  m_modifierLockAlpha.setQStringName(tr("Lock Alpha"));
}
updateWorkAndBackupRasters()
void FullColorBrushTool::updateWorkAndBackupRasters (const TRect & rect)
{
  if (rect.isEmpty()) return;
  TRasterImageP ri = TImageP(getImage(false, 1));
  if (!ri) return;
  TRasterP ras = ri->getRaster();
  const int denominator = 8;
  TRect enlargedRect    = rect + m_lastRect;
  int dx                = (enlargedRect.getLx() - 1) / denominator + 1;
  int dy                = (enlargedRect.getLy() - 1) / denominator + 1;
  if (m_lastRect.isEmpty()) {
    enlargedRect.x0 -= dx;
    enlargedRect.y0 -= dy;
    enlargedRect.x1 += dx;
    enlargedRect.y1 += dy;
    TRect _rect = enlargedRect * ras->getBounds();
    if (_rect.isEmpty()) return;
    m_workRaster->extract(_rect)->copy(ras->extract(_rect));
    m_backUpRas->extract(_rect)->copy(ras->extract(_rect));
  } else {
    if (enlargedRect.x0 < m_lastRect.x0) enlargedRect.x0 -= dx;
    if (enlargedRect.y0 < m_lastRect.y0) enlargedRect.y0 -= dy;
    if (enlargedRect.x1 > m_lastRect.x1) enlargedRect.x1 += dx;
    if (enlargedRect.y1 > m_lastRect.y1) enlargedRect.y1 += dy;
    TRect _rect = enlargedRect * ras->getBounds();
    if (_rect.isEmpty()) return;
    TRect _lastRect    = m_lastRect * ras->getBounds();
    QList<TRect> rects = ToolUtils::splitRect(_rect, _lastRect);
    for (int i = 0; i < rects.size(); i++) {
      m_workRaster->extract(rects[i])->copy(ras->extract(rects[i]));
      m_backUpRas->extract(rects[i])->copy(ras->extract(rects[i]));
    }
  }
  m_lastRect = enlargedRect;
}
Member Data Documentation
m_backUpRas
TRasterP FullColorBrushTool::m_backUpRas protected
m_brushPos
TPointD FullColorBrushTool::m_brushPos protected
World position the brush will be painted at.
Referenced by draw().
m_brushTimer
QElapsedTimer FullColorBrushTool::m_brushTimer protected
m_currentColor
TPixel32 FullColorBrushTool::m_currentColor protected
m_enabledPressure
bool FullColorBrushTool::m_enabledPressure protected
m_firstTime
bool FullColorBrushTool::m_firstTime protected
m_hardness
TDoubleProperty FullColorBrushTool::m_hardness protected
m_lastRect
TRect FullColorBrushTool::m_lastRect protected
m_maxCursorThick
int FullColorBrushTool::m_maxCursorThick protected
m_minCursorThick
int FullColorBrushTool::m_minCursorThick protected
m_modifierEraser
TBoolProperty FullColorBrushTool::m_modifierEraser protected
m_modifierLockAlpha
TBoolProperty FullColorBrushTool::m_modifierLockAlpha protected
m_modifierOpacity
TDoubleProperty FullColorBrushTool::m_modifierOpacity protected
m_modifierSize
TDoubleProperty FullColorBrushTool::m_modifierSize protected
m_mouseEvent
TMouseEvent FullColorBrushTool::m_mouseEvent protected
m_mousePos
TPointD FullColorBrushTool::m_mousePos protected
Current mouse position, in world coordinates.
Referenced by onDeactivate().
m_mousePressed
bool FullColorBrushTool::m_mousePressed = false protected
m_notifier
FullColorBrushToolNotifier* FullColorBrushTool::m_notifier protected
m_opacity
TDoublePairProperty FullColorBrushTool::m_opacity protected
m_preset
TEnumProperty FullColorBrushTool::m_preset protected
m_presetsLoaded
bool FullColorBrushTool::m_presetsLoaded protected
m_presetsManager
BrushPresetManager FullColorBrushTool::m_presetsManager protected
Manager for presets of this tool instance.
m_pressure
TBoolProperty FullColorBrushTool::m_pressure protected
m_prop
TPropertyGroup FullColorBrushTool::m_prop protected
m_propertyUpdating
bool FullColorBrushTool::m_propertyUpdating = false protected
m_strokeRect
TRect FullColorBrushTool::m_strokeRect protected
m_strokeSegmentRect
TRect FullColorBrushTool::m_strokeSegmentRect protected
m_thickness
TIntPairProperty FullColorBrushTool::m_thickness protected
m_tileSaver
TTileSaverFullColor* FullColorBrushTool::m_tileSaver protected
m_tileSet
TTileSetFullColor* FullColorBrushTool::m_tileSet protected
m_toonz_brush
MyPaintToonzBrush* FullColorBrushTool::m_toonz_brush protected
m_workRaster
TRaster32P FullColorBrushTool::m_workRaster protected
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/tnztools/fullcolorbrushtool.h
E:/opentoonz/toonz/sources/tnztools/fullcolorbrushtool.cpp