opentoonz: LevelProperties Class Reference
LevelProperties Class Reference
Stores the possible properties of a Toonz level.
#include <levelproperties.h>
Public Types
enum DpiPolicy { DP_ImageDpi = LevelOptions::DP_ImageDpi , DP_CustomDpi = LevelOptions::DP_CustomDpi }
Alias for LevelOptions::DpiPolicy provided for backward compatibility.
Public Member Functions
const LevelOptions & options () const
Returns user-accessible options.
LevelOptions & options ()
Returns user-accessible options.
void setSubsampling (int s)
Sets the level subsampling.
int getSubsampling () const
Returns the level subsampling.
void setDirtyFlag (bool on)
Sets the level's dirty flag.
bool getDirtyFlag () const
Returns the level's dirty flag
void setDpiPolicy (DpiPolicy dpiPolicy)
Sets the level's DpiPolicy.
DpiPolicy getDpiPolicy () const
Returns the level's DpiPolicy.
void setImageDpi (const TPointD &dpi)
Sets the level's image dpi.
TPointD getImageDpi () const
Returns the level's image dpi.
void setDpi (const TPointD &dpi)
Sets the level's custom dpi.
void setDpi (double dpi)
Sets a uniform custom level dpi.
TPointD getDpi () const
Returns the level's custom dpi.
void setImageRes (const TDimension &d)
Sets the level's known image resolution.
TDimension getImageRes () const
Returns the level's known image resolution.
void setBpp (int bpp)
Sets the level's known bits-per-pixel.
int getBpp () const
Returns the level's known bits-per-pixel.
void setHasAlpha (bool hasAlpha)
Sets whether the level has an alpha channel.
bool hasAlpha () const
Returns whether the level has an alpha channel.
void setCreator (const std::string &creator)
Sets the level's creator string.
std::string getCreator () const
Returns the level's creator string.
void setIsForbidden (bool forbidden)
Sets whether it is forbidden to edit a level.
bool isForbidden () const
Returns whether the level is forbidden for editing.
void setDoPremultiply (bool doPremultiply)
Sets whether premultiplication must be applied.
bool doPremultiply () const
Returns whether premultiplication must be applied.
void setDoAntialias (int softness)
int antialiasSoftness () const
void setWhiteTransp (bool whiteTransp)
bool whiteTransp () const
void setIsStopMotion (bool isStopMotion)
bool isStopMotionLevel () const
Detailed Description
Stores the possible properties of a Toonz level.
Member Enumeration Documentation
DpiPolicy
enum LevelProperties::DpiPolicy
Alias for LevelOptions::DpiPolicy provided for backward compatibility.
Deprecated:
Use LevelOptions::DpiPolicy instead.
                 {
    DP_ImageDpi  = LevelOptions::DP_ImageDpi,
    DP_CustomDpi = LevelOptions::DP_CustomDpi
  };
Constructor & Destructor Documentation
LevelProperties()
LevelProperties::LevelProperties ()
    : m_imageDpi()
    , m_creator("")
    , m_imageRes(0, 0)
    , m_bpp(32)
    , m_loadAtOnce(false)
    , m_dirtyFlag(true)
    , m_forbidden(false)
    , m_hasAlpha(false) {}
Member Function Documentation
antialiasSoftness()
int LevelProperties::antialiasSoftness () const inline
Returns the amount of morphological antialiasing to be applied.
  {
    return m_options.m_antialias;
  }
doPremultiply()
bool LevelProperties::doPremultiply () const inline
Returns whether premultiplication must be applied.
  {
    return m_options.m_premultiply;
  }
Referenced by Stage::RasterPainter::onRasterImage().
getBpp()
int LevelProperties::getBpp () const
Returns the level's known bits-per-pixel.
{ return m_bpp; }
Referenced by LevelUpdater::open().
getCreator()
std::string LevelProperties::getCreator () const inline
Returns the level's creator string.
  {
    return m_creator;
  }
getDirtyFlag()
bool LevelProperties::getDirtyFlag () const
Returns the level's dirty flag
{ return m_dirtyFlag; }
Referenced by SceneLevel::save(), and Filmstrip::updateChooseLevelComboItems().
getDpi()
TPointD LevelProperties::getDpi () const
Returns the level's custom dpi.
{
  return TPointD(m_options.m_dpi, m_options.m_dpi);
}
References LevelOptions::m_dpi.
Referenced by TXshSimpleLevel::saveData().
getDpiPolicy()
LevelProperties::DpiPolicy LevelProperties::getDpiPolicy () const
Returns the level's DpiPolicy.
{
  return LevelProperties::DpiPolicy(m_options.m_dpiPolicy);
}
References LevelOptions::m_dpiPolicy.
Referenced by ToonzScene::loadLevel().
getImageDpi()
TPointD LevelProperties::getImageDpi () const
Returns the level's image dpi.
{ return m_imageDpi; }
Referenced by TXshSimpleLevel::createEmptyFrame().
getImageRes()
TDimension LevelProperties::getImageRes () const
Returns the level's known image resolution.
{ return m_imageRes; }
Referenced by TXshSimpleLevel::createEmptyFrame().
getSubsampling()
int LevelProperties::getSubsampling () const
Returns the level subsampling.
{ return m_options.m_subsampling; }
References LevelOptions::m_subsampling.
hasAlpha()
bool LevelProperties::hasAlpha () const inline
Returns whether the level has an alpha channel.
  {
    return m_hasAlpha;
  }
Referenced by LevelUpdater::open().
isForbidden()
bool LevelProperties::isForbidden () const inline
Returns whether the level is forbidden for editing.
isStopMotionLevel()
bool LevelProperties::isStopMotionLevel () const inline
{ return m_options.m_isStopMotionLevel; }
options() [1/2]
LevelOptions & LevelProperties::options () inline
Returns user-accessible options.
  {
    return m_options;
  }
options() [2/2]
const LevelOptions & LevelProperties::options () const inline
Returns user-accessible options.
  {
    return m_options;
  }
Referenced by ToonzScene::loadLevel().
setBpp()
void LevelProperties::setBpp (int bpp)
Sets the level's known bits-per-pixel.
{ m_bpp = bpp; }
setCreator()
void LevelProperties::setCreator (const std::string & creator) inline
Sets the level's creator string.
  {
    m_creator = creator;
  }
Referenced by TXshSimpleLevel::load().
setDirtyFlag()
void LevelProperties::setDirtyFlag (bool on)
Sets the level's dirty flag.
The dirty flag is the boolean value specifying whether a level has been altered in any way. Saving operations on levels whose dirty flag is false are no-op.
{ m_dirtyFlag = on; }
Referenced by TXshSimpleLevel::load().
setDoAntialias()
void LevelProperties::setDoAntialias (int softness) inline
See http://visual-computing.intel-research.net/publications/papers/2009/mlaa/mlaa.pdf for an in-depth explanation of the morphological antialiasing technique.
Sets the amount of morphological antialiasing to be applied.
  {
    m_options.m_antialias = softness;
  }
setDoPremultiply()
void LevelProperties::setDoPremultiply (bool doPremultiply) inline
Sets whether premultiplication must be applied.
Parameters
doPremultiply Whether Toonz must perform premultiplication - ie image pixels are not already premultiplied.
Images with an alpha channel may or may not store pixels in premultiplied form. See the Wikipedia entry on alhpa compositing for further information: http://en.wikipedia.org/wiki/Alpha_compositing
Already premultiplied images do not require Toonz to perform additional premultiplication on its own to perform alpha compositing.
  {
    m_options.m_premultiply = doPremultiply;
  }
setDpi() [1/2]
void LevelProperties::setDpi (const TPointD & dpi)
Sets the level's custom dpi.
{ m_options.m_dpi = dpi.x; }
References LevelOptions::m_dpi.
Referenced by ToonzScene::loadLevel().
setDpi() [2/2]
void LevelProperties::setDpi (double dpi)
Sets a uniform custom level dpi.
{ m_options.m_dpi = dpi; }
References LevelOptions::m_dpi.
setDpiPolicy()
void LevelProperties::setDpiPolicy (LevelProperties::DpiPolicy dpiPolicy)
Sets the level's DpiPolicy.
{
  m_options.m_dpiPolicy = LevelOptions::DpiPolicy(dpiPolicy);
}
References LevelOptions::m_dpiPolicy.
Referenced by ToonzScene::loadLevel().
setHasAlpha()
void LevelProperties::setHasAlpha (bool hasAlpha) inline
Sets whether the level has an alpha channel.
  {
    m_hasAlpha = hasAlpha;
  }
setImageDpi()
void LevelProperties::setImageDpi (const TPointD & dpi)
Sets the level's image dpi.
{
  m_imageDpi = dpi;
  if (dpi.x <= 0 || dpi.y <= 0)
    m_options.m_dpiPolicy = LevelOptions::DP_CustomDpi;
}
References LevelOptions::DP_CustomDpi, and LevelOptions::m_dpiPolicy.
setImageRes()
void LevelProperties::setImageRes (const TDimension & d)
Sets the level's known image resolution.
{ m_imageRes = d; }
setIsForbidden()
void LevelProperties::setIsForbidden (bool forbidden) inline
Sets whether it is forbidden to edit a level.
A level is forbidden if it has been created with a uncompatible application version (e.g. it was created with Student and loaded with Toonz).
  {
    m_forbidden = forbidden;
  }
Referenced by TXshSimpleLevel::load().
setIsStopMotion()
void LevelProperties::setIsStopMotion (bool isStopMotion) inline
  {
    m_options.m_isStopMotionLevel = isStopMotion;
  }
setSubsampling()
void LevelProperties::setSubsampling (int s)
Sets the level subsampling.
The level subsampling is the integer value (strictly greater than 1) denoting the fraction of pixels to be displayed for its images while in camera stand mode. For example, a value of 2 will halve the original image resolution.
Note that only the crudest algorithm will be applied for resampling, as this feature is explicitly intended to improve visualization speed as much as possible.
{ m_options.m_subsampling = s; }
References LevelOptions::m_subsampling.
Referenced by ToonzScene::loadLevel().
setWhiteTransp()
void LevelProperties::setWhiteTransp (bool whiteTransp) inline
White substitution is currently an exact feature in Toonz - ie only fully white pixels will be replaced with transparent. This implicityl restrains its applicability to images without antialias. This is therefore coupled with antialiasing settings.
See also
The setDoAntialias() method.
Whether full white pixels should be intended as transparent.
  {
    m_options.m_whiteTransp = whiteTransp;
  }
whiteTransp()
bool LevelProperties::whiteTransp () const inline
{ return m_options.m_whiteTransp; }
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/toonz/levelproperties.h
E:/opentoonz/toonz/sources/toonzlib/levelproperties.cpp