opentoonz: SetScanCropboxTool Class Reference
SetScanCropboxTool Class Reference final
Public Member Functions
ToolType getToolType () const override
void draw () override
Draws the tool on the viewer.
void mouseMove (const TPointD &p, const TMouseEvent &e) override
void leftButtonDown (const TPointD &pos, const TMouseEvent &e) override
void leftButtonDrag (const TPointD &pos, const TMouseEvent &e) override
int getCursorId () const override
Returns the type of cursor used by the tool.
void onActivate () override
Callback invoked whenever the tool activates.
void onEnter () override
Callback for the mouse entering the viewer area.
Public Member Functions inherited from TTool
TTool (std::string toolName)
every tool (invoking updateTranslation() for each).
virtual ToolType getToolType () const =0
ToolTargetType getTargetType () const
std::string getName () const
virtual ToolOptionsBox * createOptionsBox ()
void setViewer (Viewer *viewer)
Viewer * getViewer () const
double getPixelSize () const
void invalidate (const TRectD &rect=TRectD())
int pick (const TPointD &p)
bool isPicking () const
virtual void updateTranslation ()
virtual bool preLeftButtonDown ()
virtual void mouseMove (const TPointD &, const TMouseEvent &)
virtual void leftButtonDown (const TPointD &, const TMouseEvent &)
virtual void leftButtonDrag (const TPointD &, const TMouseEvent &)
virtual void leftButtonUp (const TPointD &, const TMouseEvent &)
virtual void leftButtonDoubleClick (const TPointD &, const TMouseEvent &)
virtual void rightButtonDown (const TPointD &, const TMouseEvent &)
virtual bool keyDown (QKeyEvent *)
virtual void onInputText (std::wstring, std::wstring, int, int)
virtual void onSetViewer ()
virtual void onActivate ()
Callback invoked whenever the tool activates.
virtual void onDeactivate ()
Callback for tool deactivation, includes tool switch.
virtual void onImageChanged ()
Notifies changes in the image in use.
virtual void onEnter ()
Callback for the mouse entering the viewer area.
virtual void onLeave ()
Callback for the mouse leaving the viewer area.
virtual void onFrameSwitched ()
virtual void reset ()
virtual void draw ()
Draws the tool on the viewer.
bool isActive () const
Used to know if a tool is active, (used in TextTool only).
void setActive (bool active)
virtual TPropertyGroup * getProperties (int)
virtual bool onPropertyChanged (std::string propertyName)
virtual TSelection * getSelection ()
Returns a pointer to the tool selection.
virtual int getCursorId () const
Returns the type of cursor used by the tool.
virtual bool isEventAcceptable (QEvent *e)
TXsheet * getXsheet () const
Returns a pointer to the actual Xsheet.
int getFrame ()
Returns the actual frame in use.
int getColumnIndex ()
Returns the actual column index.
TStageObjectId getObjectId () const
Returns a pointer to the actual stage object.
void notifyImageChanged ()
void notifyImageChanged (const TFrameId &fid)
images on the level view.
TFrameId getCurrentFid () const
Returns the number of the actual editing frame.
const TAffine & getMatrix () const
void setMatrix (const TAffine &matrix)
TAffine getCurrentColumnMatrix (int frame=-1) const
TAffine getCurrentColumnParentMatrix () const
TAffine getCurrentObjectParentMatrix () const
TAffine getCurrentObjectParentMatrix2 () const
TAffine getColumnMatrix (int index, int frame=-1) const
virtual void updateMatrix ()
virtual void addContextMenuItems (QMenu *menu)
void enable (bool on)
bool isEnabled () const
QString updateEnabled ()
virtual QString updateEnabled (int rowIndex, int columnIndex)
bool isColumnLocked (int columnIndex) const
void resetInputMethod ()
Resets Input Context (IME)
virtual bool isPencilModeActive ()
virtual bool isDragging () const
void setSelectedFrames (const std::set< TFrameId > &selectedFrames)
void tweenSelectedGuideStrokes ()
void tweenGuideStrokeToSelected ()
void flipGuideStrokeDirection (int mode)
Additional Inherited Members
Public Types inherited from TTool
enum ToolType {
GenericTool = 1 , ColumnTool = 2 , LevelReadTool = 4 , LevelWriteTool ,
LevelTool = LevelReadTool | LevelWriteTool
}
Tool editing type.
enum ToolTargetType {
NoTarget = 0x0 , VectorImage = 0x1 , ToonzImage = 0x2 , RasterImage = 0x4 ,
MeshImage = 0x8 , Splines = 0x10 , LevelColumns = 0x20 , MeshColumns = 0x40 ,
EmptyTarget = 0x80 , CommonImages = VectorImage | ToonzImage | RasterImage , AllImages = CommonImages | MeshImage , Vectors = VectorImage | Splines ,
CommonLevels = CommonImages | LevelColumns , MeshLevels = MeshImage | MeshColumns , AllTargets = 0xffffffff
}
Object types the tool can operate on.
typedef TApplication Application
Static Public Member Functions inherited from TTool
static TTool * getTool (std::string toolName, ToolTargetType targetType)
static TApplication * getApplication ()
static void setApplication (TApplication *application)
static TXshCell getImageCell ()
Returns the level-frame pair to be edited by the tool.
static TImage * getImage (bool toBeModified, int subsampling=0)
Returns the image to be edited by the tool.
static TImage * touchImage ()
static void updateToolsPropertiesTranslation ()
static const std::set< TFrameId > & getSelectedFrames ()
Static Public Attributes inherited from TTool
static std::vector< CellOps > m_cellsData
static bool m_isLevelCreated = false
static bool m_isFrameCreated = false
static std::vector< TFrameId > m_oldFids
static std::vector< TFrameId > m_newFids
static bool m_isLevelRenumbererd = false
Protected Member Functions inherited from TTool
void bind (int targetType)
virtual void onSelectedFramesChanged ()
virtual QString disableString ()
Returns a custom reason to disable the tool.
Protected Attributes inherited from TTool
std::string m_name
The tool's name.
Viewer * m_viewer
Tool's current viewer.
TAffine m_matrix
World-to-window reference change affine.
int m_targetType
The tool's image type target.
bool m_enabled
Whether the tool allows user interaction.
bool m_active
bool m_picking
Static Protected Attributes inherited from TTool
static TApplication * m_application = 0
static std::set< TFrameId > m_selectedFrames = std::set<TFrameId>()
Detailed Description
Constructor & Destructor Documentation
SetScanCropboxTool()
SetScanCropboxTool::SetScanCropboxTool () inline
      : TTool("T_SetScanCropbox")
      , m_imgId("setScanCropboxId")
      , m_scaling(eNone)
      , m_lastPos() {
    bind(TTool::AllTargets);  // Deals with tool deactivation internally
  }
Member Function Documentation
draw()
void SetScanCropboxTool::draw () inline override virtual
Draws the tool on the viewer.
Reimplemented from TTool.
                       {
    TRasterImageP ri = TImageCache::instance()->get(m_imgId, false);
    if (ri) {
      TPointD center = ri->getRaster()->getCenterD();
      GLRasterPainter::drawRaster(
          TScale(Stage::inch / previewDPI, Stage::inch / previewDPI), ri, true);
    }
    TRectD cropBox   = rect2pix(m_parameters->getCropBox());
    double pixelSize = getPixelSize();
    tglColor(TPixel::Red);
    glLineStipple(1, 0xFFFF);
    glEnable(GL_LINE_STIPPLE);
    tglDrawRect(cropBox);
    TPointD size(10, 10);
    tglColor(TPixel::Red);
    ToolUtils::drawSquare(cropBox.getP00(), pixelSize * 4, TPixel::Red);
    ToolUtils::drawSquare(cropBox.getP01(), pixelSize * 4, TPixel::Red);
    ToolUtils::drawSquare(cropBox.getP10(), pixelSize * 4, TPixel::Red);
    ToolUtils::drawSquare(cropBox.getP11(), pixelSize * 4, TPixel::Red);
    TPointD center = (cropBox.getP00() + cropBox.getP11()) * 0.5;
    ToolUtils::drawSquare(TPointD(center.x, cropBox.y0), pixelSize * 4,
                          TPixel::Red);  // draw M0 handle
    ToolUtils::drawSquare(TPointD(cropBox.x1, center.y), pixelSize * 4,
                          TPixel::Red);  // draw 1M handle
    ToolUtils::drawSquare(TPointD(center.x, cropBox.y1), pixelSize * 4,
                          TPixel::Red);  // draw M1 handle
    ToolUtils::drawSquare(TPointD(cropBox.x0, center.y), pixelSize * 4,
                          TPixel::Red);  // draw 0M handle
    glDisable(GL_LINE_STIPPLE);
  }
References TImageCache::get(), Stage::inch, and TRectT< T >::x0.
getCursorId()
int SetScanCropboxTool::getCursorId () const inline override virtual
Returns the type of cursor used by the tool.
See also
For a list of cursor ids cursor.h
Reimplemented from TTool.
{
    switch (m_scaling) {
    case eNone:
      return ToolCursor::StrokeSelectCursor;
    case eMove:
      return ToolCursor::MoveCursor;
    case e11:
    case e00:
      return ToolCursor::ScaleCursor;
    case e10:
    case e01:
      return ToolCursor::ScaleInvCursor;
    case e1M:
    case e0M:
      return ToolCursor::ScaleHCursor;
    case eM1:
    case eM0:
      return ToolCursor::ScaleVCursor;
    default:
      assert(false);
    }
    return 0;
  }
getToolType()
ToolType SetScanCropboxTool::getToolType () const inline override virtual
Implements TTool.
{ return TTool::GenericTool; }
leftButtonDown()
void SetScanCropboxTool::leftButtonDown (const TPointD & pos, const TMouseEvent & e) inline override virtual
Reimplemented from TTool.
{
    m_lastPos = pos;
  }
leftButtonDrag()
void SetScanCropboxTool::leftButtonDrag (const TPointD & pos, const TMouseEvent & e) inline override virtual
Reimplemented from TTool.
{
    TPointD dp         = pos - m_lastPos;
    double scaleFactor = Stage::inch / previewDPI;
    dp.x               = ((dp.x / scaleFactor) * 25.4) / previewDPI;
    dp.y               = ((dp.y / scaleFactor) * 25.4) / previewDPI;
    TRectD scanArea = m_parameters->getScanArea();
    TRectD cropBox  = m_parameters->getCropBox();
    if (m_scaling != eNone && m_scaling != eMove) {
      if ((m_scaling == eM1 ||
           ((m_scaling == e11 || m_scaling == e01) && !e.isShiftPressed())) &&
          cropBox.x0 - dp.y < cropBox.x1)
        cropBox.x0 -= dp.y;
      if ((m_scaling == eM0 ||
           ((m_scaling == e10 || m_scaling == e00) && !e.isShiftPressed())) &&
          cropBox.x1 - dp.y > cropBox.x0)
        cropBox.x1 -= dp.y;
      if ((m_scaling == e0M ||
           ((m_scaling == e00 || m_scaling == e01) && !e.isShiftPressed())) &&
          cropBox.y1 - dp.x > cropBox.y0)
        cropBox.y1 -= dp.x;
      if ((m_scaling == e1M ||
           ((m_scaling == e11 || m_scaling == e10) && !e.isShiftPressed())) &&
          cropBox.y0 - dp.x < cropBox.y1)
        cropBox.y0 -= dp.x;
      if (e.isShiftPressed()) {
        TPointD delta;
        delta.x = (fabs(dp.x) > fabs(dp.y)) ? dp.x : dp.y;
        delta.y = delta.x * scanArea.getLx() / scanArea.getLy();
        if (m_scaling == e11) {
          if (cropBox.y0 - delta.x < cropBox.y1) cropBox.y0 -= delta.x;
          if (cropBox.x0 - delta.y < cropBox.x1) cropBox.x0 -= delta.y;
        } else if (m_scaling == e00) {
          if (cropBox.y1 - delta.x > cropBox.y0) cropBox.y1 -= delta.x;
          if (cropBox.x1 - delta.y > cropBox.x0) cropBox.x1 -= delta.y;
        } else if (m_scaling == e01) {
          if (cropBox.y1 - delta.x > cropBox.y0) cropBox.y1 -= delta.x;
          if (cropBox.x0 - delta.y < cropBox.x1) cropBox.x0 -= delta.y;
        }
        if (m_scaling == e10) {
          if (cropBox.y0 - delta.x < cropBox.y1) cropBox.y0 -= delta.x;
          if (cropBox.x1 - delta.y > cropBox.x0) cropBox.x1 -= delta.y;
        }
      }
      cropBox *= scanArea;
      if (cropBox != m_parameters->getCropBox()) {
        m_parameters->setCropBox(cropBox);
        m_lastPos = pos;
      }
    } else if (m_scaling == eMove) {
      cropBox += TPointD(-dp.y, 0);
      if (scanArea.contains(cropBox)) m_parameters->setCropBox(cropBox);
      cropBox += TPointD(0, -dp.x);
      if (scanArea.contains(cropBox)) m_parameters->setCropBox(cropBox);
      m_lastPos = pos;
    }
    invalidate();
  }
mouseMove()
void SetScanCropboxTool::mouseMove (const TPointD & p, const TMouseEvent & e) inline override virtual
Reimplemented from TTool.
{
    double pixelSize = getPixelSize();
    TPointD size(10 * pixelSize, 10 * pixelSize);
    TRectD cropBox = rect2pix(m_parameters->getCropBox());
    double maxDist = 5 * pixelSize;
    if (TRectD(cropBox.getP00() - size, cropBox.getP00() + size).contains(p))
      m_scaling = e00;
    else if (TRectD(cropBox.getP01() - size, cropBox.getP01() + size)
                 .contains(p))
      m_scaling = e01;
    else if (TRectD(cropBox.getP11() - size, cropBox.getP11() + size)
                 .contains(p))
      m_scaling = e11;
    else if (TRectD(cropBox.getP10() - size, cropBox.getP10() + size)
                 .contains(p))
      m_scaling = e10;
    else if (isCloseToSegment(p, TSegment(cropBox.getP00(), cropBox.getP10()),
                              maxDist))
      m_scaling = eM0;
    else if (isCloseToSegment(p, TSegment(cropBox.getP10(), cropBox.getP11()),
                              maxDist))
      m_scaling = e1M;
    else if (isCloseToSegment(p, TSegment(cropBox.getP11(), cropBox.getP01()),
                              maxDist))
      m_scaling = eM1;
    else if (isCloseToSegment(p, TSegment(cropBox.getP01(), cropBox.getP00()),
                              maxDist))
      m_scaling = e0M;
    else if (cropBox.contains(p))
      m_scaling = eMove;
    else
      m_scaling = eNone;
  }
onActivate()
void SetScanCropboxTool::onActivate () inline override virtual
Callback invoked whenever the tool activates.
Reimplemented from TTool.
{
    m_parameters = TTool::getApplication()
                       ->getCurrentScene()
                       ->getScene()
                       ->getProperties()
                       ->getScanParameters();
  }
References ToonzScene::getProperties(), and TSceneProperties::getScanParameters().
onEnter()
void SetScanCropboxTool::onEnter () inline override virtual
Callback for the mouse entering the viewer area.
Reimplemented from TTool.
{
    m_parameters = TTool::getApplication()
                       ->getCurrentScene()
                       ->getScene()
                       ->getProperties()
                       ->getScanParameters();
  }
References ToonzScene::getProperties(), and TSceneProperties::getScanParameters().
The documentation for this class was generated from the following file:
E:/opentoonz/toonz/sources/toonz/scanpopup.cpp