opentoonz: TDoubleParam Class Reference
TDoubleParam Class Reference final
Classes
class Imp
Public Member Functions
TDoubleParam (double v=0.0)
TDoubleParam (const TDoubleParam &src)
TDoubleParam & operator= (const TDoubleParam &)
TParam * clone () const override
void copy (TParam *src) override
std::string getMeasureName () const
void setMeasureName (std::string name)
TMeasure * getMeasure () const
void setValueRange (double min, double max, double step=1.0)
bool getValueRange (double &min, double &max, double &step) const
double getDefaultValue () const
void setDefaultValue (double value)
double getValue (double frame, bool leftmost=false) const
bool setValue (double frame, double value)
TPointD getSpeedIn (int kIndex) const
TPointD getSpeedOut (int kIndex) const
const TSyntax::Grammar * getGrammar () const
void setGrammar (const TSyntax::Grammar *grammar)
void accept (TSyntax::CalculatorNodeVisitor &visitor)
void enableCycle (bool enabled)
cycle controls extrapolation after the last keyframe
bool isCycleEnabled () const
int getKeyframeCount () const
void getKeyframes (std::set< double > &frames) const override
double keyframeIndexToFrame (int index) const override
const TDoubleKeyframe & getKeyframe (int index) const
const TDoubleKeyframe & getKeyframeAt (double frame) const
void setKeyframe (int kIndex, const TDoubleKeyframe &k)
void setKeyframes (const std::map< int, TDoubleKeyframe > &ks)
void setKeyframe (const TDoubleKeyframe &k)
create a keyframe in k.m_frame (if is needed) and assign k to it
bool isKeyframe (double frame) const override
bool hasKeyframes () const override
void deleteKeyframe (double frame) override
void clearKeyframes () override
int getClosestKeyframe (double frame) const
int getNextKeyframe (double frame) const override
int getPrevKeyframe (double frame) const override
void assignKeyframe (double frame, const TParamP &src, double srcFrame, bool changedOnly) override
bool isAnimatable () const override
void addObserver (TParamObserver *observer) override
void removeObserver (TParamObserver *observer) override
const std::set< TParamObserver * > & observers () const
bool isDefault () const
no keyframes, default value not changed
void loadData (TIStream &is) override
void saveData (TOStream &os) override
std::string getStreamTag () const
std::string getValueAlias (double frame, int precision) override
Public Member Functions inherited from TParam
TParam (std::string name="", std::string description="", std::string label="")
std::string getName () const
void setName (const std::string &name)
std::string getDescription () const
void setDescription (const std::string &description)
bool hasUILabel () const
void setUILabel (const std::string &l)
std::string getUILabel () const
virtual TParam * clone () const =0
virtual void copy (TParam *src)=0
virtual void addObserver (TParamObserver *)=0
virtual void removeObserver (TParamObserver *)=0
virtual void enableNotification (bool on)
virtual bool isNotificationEnabled () const
virtual std::string getValueAlias (double frame, int precision)=0
virtual bool isAnimatable () const =0
virtual bool isKeyframe (double frame) const =0
virtual void deleteKeyframe (double frame)=0
virtual void clearKeyframes ()=0
virtual void assignKeyframe (double frame, const TSmartPointerT< TParam > &src, double srcFrame, bool changedOnly=false)=0
virtual void getKeyframes (std::set< double > &frames) const
virtual bool hasKeyframes () const
virtual int getNextKeyframe (double frame) const
virtual int getPrevKeyframe (double frame) const
virtual double keyframeIndexToFrame (int index) const
Public Member Functions inherited from TSmartObject
TSmartObject (ClassCode classCode)
void addRef ()
void release ()
TINT32 getRefCount () const
Public Member Functions inherited from TPersist
virtual void loadData (TIStream &is)=0
virtual void saveData (TOStream &os)=0
std::string getStreamTag () const
virtual const TPersistDeclaration * getDeclaration () const =0
Additional Inherited Members
Public Types inherited from TSmartObject
typedef short ClassCode
Public Types inherited from TPersist
typedef TPersist * CreateProc()
Static Public Member Functions inherited from TSmartObject
static TINT32 getInstanceCount (ClassCode code)
Static Public Member Functions inherited from TPersist
static void declare (CreateProc *)
static TPersist * create (const std::string &name)
Detailed Description
Constructor & Destructor Documentation
TDoubleParam() [1/2]
TDoubleParam::TDoubleParam (double v = 0.0)
: m_imp(new TDoubleParam::Imp(v)) {}
TDoubleParam() [2/2]
TDoubleParam::TDoubleParam (const TDoubleParam & src)
    : TParam(src.getName()), m_imp(new TDoubleParam::Imp()) {
  m_imp->copy(src.m_imp);
}
~TDoubleParam()
TDoubleParam::~TDoubleParam ()
{}
Member Function Documentation
accept()
void TDoubleParam::accept (TSyntax::CalculatorNodeVisitor & visitor)
{
  for (int i = 0; i < (int)m_imp->m_keyframes.size(); i++)
    if (m_imp->m_keyframes[i].m_type == TDoubleKeyframe::Expression ||
        m_imp->m_keyframes[i].m_type == TDoubleKeyframe::SimilarShape)
      m_imp->m_keyframes[i].m_expression.accept(visitor);
}
addObserver()
void TDoubleParam::addObserver (TParamObserver *) override virtual
 An observer is a generic class that takes care and manages of canghes
in the parameters. This method must be implemented with a function that add objects to an observer internal list.
Implements TParam.
{
  m_imp->m_observers.insert(observer);
}
assignKeyframe()
void TDoubleParam::assignKeyframe (double frame, const TParamP & src, double srcFrame, bool changedOnly) override virtual
Makes the frame associated to this parameter a keyframe
Implements TParam.
{
  TDoubleParamP dp = src;
  if (!dp) return;
  double value = dp->getValue(srcFrame);
  if (!changedOnly || getValue(frame) != value) setValue(frame, value);
}
clearKeyframes()
void TDoubleParam::clearKeyframes () override virtual
Removes all keyframes from this parameter.
Implements TParam.
{
  m_imp->m_keyframes.clear();
  m_imp->notify(TParamChange(this, 0, 0, true, false, false));
}
clone()
TParam * TDoubleParam::clone () const inline override virtual
 This method must be implemented with a clone function, i.e a function
that make a new copy of the parameter.
Implements TParam.
{ return new TDoubleParam(*this); }
copy()
void TDoubleParam::copy (TParam * src) override virtual
Performs a copy function of the parameter in an existing object.
Implements TParam.
{
  TDoubleParam *p = dynamic_cast<TDoubleParam *>(src);
  if (!p) throw TException("invalid source for copy");
  setName(src->getName());
  m_imp->copy(p->m_imp);
  m_imp->notify(TParamChange(this, 0, 0, true, false, false));
}
References TParam::getName(), and TParam::setName().
deleteKeyframe()
void TDoubleParam::deleteKeyframe (double frame) override virtual
 Removes \e frame from the list of the keyframes associated to this
parameter.
Implements TParam.
{
  DoubleKeyframeVector &keyframes = m_imp->m_keyframes;
  DoubleKeyframeVector::iterator it;
  it = std::lower_bound(keyframes.begin(), keyframes.end(),
                        TDoubleKeyframe(frame));
  if (it == keyframes.end() || it->m_frame != frame) return;
  TDoubleKeyframe::Type type                = it->m_prevType;
  it                                        = m_imp->m_keyframes.erase(it);
  if (it != keyframes.end()) it->m_prevType = type;
  m_imp->notify(TParamChange(this, 0, 0, true, false, false));
}
enableCycle()
void TDoubleParam::enableCycle (bool enabled)
cycle controls extrapolation after the last keyframe
{
  m_imp->m_cycleEnabled = enabled;
  m_imp->notify(TParamChange(this, 0, 0, true, false, false));
}
getClosestKeyframe()
int TDoubleParam::getClosestKeyframe (double frame) const
{
  DoubleKeyframeVector &keyframes = m_imp->m_keyframes;
  typedef DoubleKeyframeVector::iterator Iterator;
  Iterator it = std::lower_bound(keyframes.begin(), keyframes.end(),
                                 TDoubleKeyframe(frame));
  if (it == keyframes.end()) {
    // frame > k.m_frame per qualsiasi k.
    // ritorna l'indice dell'ultimo keyframe (o -1 se l'array e' vuoto)
    return keyframes.size() - 1;
  } else {
    int index = std::distance<Iterator>(keyframes.begin(), it);
    if (it->m_frame == frame || index == 0)
      return index;
    else {
      double nextFrame = it->m_frame;
      double prevFrame = keyframes[index - 1].m_frame;
      assert(prevFrame < frame && frame < nextFrame);
      return (nextFrame - frame < frame - prevFrame) ? index : index - 1;
    }
  }
}
getDefaultValue()
double TDoubleParam::getDefaultValue () const
{
  assert(m_imp);
  return m_imp->m_defaultValue;
}
getGrammar()
const TSyntax::Grammar * TDoubleParam::getGrammar () const
{
  return m_imp->m_grammar;
}
getKeyframe()
const TDoubleKeyframe & TDoubleParam::getKeyframe (int index) const
{
  assert(0 <= index && index < (int)m_imp->m_keyframes.size());
  return m_imp->m_keyframes[index];
}
getKeyframeAt()
const TDoubleKeyframe & TDoubleParam::getKeyframeAt (double frame) const
{
  static TDoubleKeyframe k;
  k     = TDoubleKeyframe();
  int i = 0;
  for (i = 0; i < (int)m_imp->m_keyframes.size(); i++)
    if (m_imp->m_keyframes[i].m_frame >= frame) break;
  if (i < (int)m_imp->m_keyframes.size() &&
      m_imp->m_keyframes[i].m_frame == frame) {
    k = m_imp->m_keyframes[i];
    return k;
  }
  k.m_frame      = frame;
  k.m_value      = getValue(frame);
  k.m_isKeyframe = false;
  return k;
}
getKeyframeCount()
int TDoubleParam::getKeyframeCount () const
{ return m_imp->m_keyframes.size(); }
getKeyframes()
void TDoubleParam::getKeyframes (std::set< double > & frames) const override virtual
 This function must be overridden with a method that returns as a
reference a list of keyframes in the form of a standard list.
Reimplemented from TParam.
{
  for (DoubleKeyframeVector::iterator it = m_imp->m_keyframes.begin();
       it != m_imp->m_keyframes.end(); ++it)
    frames.insert(it->m_frame);
}
Referenced by FunctionSheetColumnHeadViewer::mouseMoveEvent().
getMeasure()
TMeasure * TDoubleParam::getMeasure () const
{ return m_imp->m_measure; }
getMeasureName()
string TDoubleParam::getMeasureName () const
{ return m_imp->m_measureName; }
getNextKeyframe()
int TDoubleParam::getNextKeyframe (double frame) const override virtual
 This method must return the index of the keyframe (if any) after the
frame, otherwiswe returns -1.
Reimplemented from TParam.
{
  TDoubleKeyframe k(frame);
  typedef DoubleKeyframeVector::const_iterator Iterator;
  Iterator it =
      std::upper_bound(m_imp->m_keyframes.begin(), m_imp->m_keyframes.end(), k);
  if (it == m_imp->m_keyframes.end()) return -1;
  int index = std::distance<Iterator>(m_imp->m_keyframes.begin(), it);
  if (it->m_frame == frame) {
    ++index;
    return index < getKeyframeCount() ? index : -1;
  }
  return index;
}
getPrevKeyframe()
int TDoubleParam::getPrevKeyframe (double frame) const override virtual
 This method must return the index of the keyframe (if any) before the
frame, otherwiswe returns -1.
Reimplemented from TParam.
{
  TDoubleKeyframe k(frame);
  typedef DoubleKeyframeVector::const_iterator Iterator;
  Iterator it =
      std::lower_bound(m_imp->m_keyframes.begin(), m_imp->m_keyframes.end(), k);
  if (it == m_imp->m_keyframes.end()) return m_imp->m_keyframes.size() - 1;
  int index = std::distance<Iterator>(m_imp->m_keyframes.begin(), it);
  return index - 1;
}
getSpeedIn()
TPointD TDoubleParam::getSpeedIn (int kIndex) const
{
  return m_imp->getSpeedIn(kIndex);
}
getSpeedOut()
TPointD TDoubleParam::getSpeedOut (int kIndex) const
{
  return m_imp->getSpeedOut(kIndex);
}
getStreamTag()
string TDoubleParam::getStreamTag () const
{ return "doubleParam"; }
getValue()
double TDoubleParam::getValue (double frame, bool leftmost = false) const
{
  double value = 0;
  assert(m_imp);
  const DoubleKeyframeVector &keyframes = m_imp->m_keyframes;
  if (keyframes.empty()) {
    // no keyframes: return the default value
    value = m_imp->m_defaultValue;
  } else if (keyframes.size() == 1) {
    // a single keyframe. Type must be keyframe based (no expression/file)
    value = keyframes[0].m_value;
  } else {
    // keyframes range is [f0,f1]
    double f0 = keyframes.begin()->m_frame;
    double f1 = keyframes.back().m_frame;
    if (frame < f0)
      frame = f0;
    else if (frame > f1 && !m_imp->m_cycleEnabled)
      frame            = f1;
    double valueOffset = 0;
    if (m_imp->m_cycleEnabled) {
      double dist   = (f1 - f0);
      double dvalue = keyframes.back().m_value - keyframes.begin()->m_value;
      while (frame >= f1) {
        if (frame != f1 || !leftmost) {
          frame -= dist;
          valueOffset += dvalue;
        } else
          break;
      }
    }
    // frame is in [f0,f1]
    assert(f0 <= frame && frame <= f1);
    DoubleKeyframeVector::const_iterator b;
    b = std::lower_bound(keyframes.begin(), keyframes.end(),
                         TDoubleKeyframe(frame));
    assert(b != keyframes.end());
    DoubleKeyframeVector::const_iterator a;
    if (b->m_frame == frame && (b + 1) != keyframes.end()) {
      a = b;
      b++;
    } else {
      assert(b != keyframes.begin());
      a = b - 1;
    }
    if (leftmost && frame - a->m_frame < 0.00001 && a != keyframes.begin()) {
      a--;
      b--;
    }
    // segment (a,b) contains frame
    assert(a != keyframes.end());
    assert(b != keyframes.end());
    assert(a->m_frame <= frame);
    assert(b->m_frame >= frame);
    int kIndex = std::distance(keyframes.begin(), a);
    vector<TActualDoubleKeyframe> tmpKeyframe(3);
    // if segment is keyframe based ....
    if (TDoubleKeyframe::isKeyframeBased(a->m_type)) {
      // .. and next segment is not then update the b value
      if ((b + 1) != keyframes.end() &&
          !TDoubleKeyframe::isKeyframeBased(b->m_type)) {
        tmpKeyframe[0] = *b;
        if (b->m_type != TDoubleKeyframe::Expression ||
            !b->m_expression.isCycling())
          tmpKeyframe[0].m_value = getValue(b->m_frame);
        b                        = tmpKeyframe.begin();
      }
      // .. and/or if prev segment is not then update the a value
      if (a != keyframes.begin() &&
          !TDoubleKeyframe::isKeyframeBased(a[-1].m_type)) {
        tmpKeyframe[1]         = *a;
        tmpKeyframe[1].m_value = getValue(a->m_frame, true);
        a                      = tmpKeyframe.begin() + 1;
      }
    }
    if (a->m_step > 1) {
      tmpKeyframe[2] = *b;
      b              = tmpKeyframe.begin() + 2;
      int relPos = tfloor(b->m_frame - a->m_frame),
          step   = std::min(a->m_step, relPos);
      tmpKeyframe[2].m_frame        = a->m_frame + tfloor(relPos, step);
      if (frame > b->m_frame) frame = b->m_frame;
      frame = a->m_frame + tfloor(tfloor(frame - a->m_frame), step);
    }
    assert(0 <= kIndex && kIndex + 1 < (int)m_imp->m_keyframes.size());
    value            = m_imp->m_defaultValue;
    bool convertUnit = false;
    switch (a->m_type) {
    case TDoubleKeyframe::Constant:
      value = getConstantValue(*a, *b, frame);
      break;
    case TDoubleKeyframe::Linear:
      value = getLinearValue(*a, *b, frame);
      break;
    case TDoubleKeyframe::SpeedInOut:
      value = getSpeedInOutValue(*a, *b, getSpeedOut(kIndex),
                                 getSpeedIn(kIndex + 1), frame);
      break;
    case TDoubleKeyframe::EaseInOut:
      value = getEaseInOutValue(*a, *b, frame, false);
      break;
    case TDoubleKeyframe::EaseInOutPercentage:
      value = getEaseInOutValue(*a, *b, frame, true);
      break;
    case TDoubleKeyframe::Exponential:
      value = getExponentialValue(*a, *b, frame);
      break;
    case TDoubleKeyframe::Expression:
      value       = getExpressionValue(*a, *b, frame, m_imp->m_measure);
      convertUnit = true;
      break;
    case TDoubleKeyframe::File:
      value       = a->m_fileData.getValue(frame, m_imp->m_defaultValue);
      convertUnit = true;
      break;
    case TDoubleKeyframe::SimilarShape:
      value = getSimilarShapeValue(*a, *b, frame, m_imp->m_measure);
      // convertUnit = true;
      break;
    default:
      value = 0.0;
    }
    value += valueOffset;
    if (convertUnit) value = a->convertFrom(m_imp->m_measure, value);
  }
  // if (cropped)
  //  value = tcrop(value, m_imp->m_minValue, m_imp->m_maxValue);
  return value;
}
getValueAlias()
string TDoubleParam::getValueAlias (double frame, int precision) override virtual
 This pure virtual method must return a string with the value of the
parameter and the precision needed.
Implements TParam.
{
  return ::to_string(getValue(frame), precision);
}
getValueRange()
bool TDoubleParam::getValueRange (double & min, double & max, double & step) const
{
  min  = m_imp->m_minValue;
  max  = m_imp->m_maxValue;
  step = 1;  // m_imp->m_valueStep;
  return min < max;
}
hasKeyframes()
bool TDoubleParam::hasKeyframes () const override virtual
 This method must return true if there are keyframes associated to this
parameter.
Reimplemented from TParam.
{ return !m_imp->m_keyframes.empty(); }
Referenced by FunctionTreeModel::ChannelGroup::applyShowFilter(), and FunctionTreeModel::ChannelGroup::displayAnimatedChannels().
isAnimatable()
bool TDoubleParam::isAnimatable () const inline override virtual
Implements TParam.
{ return true; }
isCycleEnabled()
bool TDoubleParam::isCycleEnabled () const
{ return m_imp->m_cycleEnabled; }
isDefault()
bool TDoubleParam::isDefault () const
no keyframes, default value not changed
{
  return m_imp->m_keyframes.empty() &&
         // m_imp->m_type == Keyframes &&
         m_imp->m_defaultValue == 0;
}
isKeyframe()
bool TDoubleParam::isKeyframe (double frame) const override virtual
It must returns true if the frame is a keyframe.
Implements TParam.
{
  return std::binary_search(m_imp->m_keyframes.begin(),
                            m_imp->m_keyframes.end(), TDoubleKeyframe(frame));
}
Referenced by ToolOptionParamRelayField::onValueChanged().
keyframeIndexToFrame()
double TDoubleParam::keyframeIndexToFrame (int index) const override virtual
 This method must returns a frame given the index \e index. A frame is
a double value representing a frame.
Reimplemented from TParam.
{
  assert(0 <= index && index < getKeyframeCount());
  return getKeyframe(index).m_frame;
}
Referenced by FunctionSheetCellViewer::createDragTool(), and ExportCurvePopup::execute().
loadData()
void TDoubleParam::loadData (TIStream & is) override virtual
 This is a pure virtual function and must be overridden with a method
that implements the object loading from a stream (i.e take the object's features from a formatted data stream). For example the TStageObject class use his implementation to take the values of the parameters that characterizes a stage object as name, coordinates, etc... from a file. is is an input file stream
Implements TPersist.
{
  string tagName;
  /*
if(is.matchTag(tagName))
{
// nuovo formato (29 agosto 2005)
if(tagName!="type") throw TException("expected <type>");
int type = 0;
is >> type;
// m_imp->m_type = TDoubleParam::Type(type);
if(!is.matchEndTag()) throw TException(tagName + " : missing endtag");
//if(!is.matchTag(tagName) || tagName != "default") throw TException("expected
<default>");
//is >> m_imp->m_defaultValue;
//if(!is.matchEndTag()) throw TException(tagName + " : missing endtag");
//if(!is.matchTag(tagName) || tagName != "default") throw TException("expected
<default>");
}
else
{
// vecchio formato
is >> m_imp->m_defaultValue;
}
*/
  m_imp->m_keyframes.clear();
  int oldType = -1;
  while (is.matchTag(tagName)) {
    if (tagName == "type") {
      // (old) format 5.2. Since 6.0 param type is no used anymore
      is >> oldType;
    } else if (tagName == "default") {
      is >> m_imp->m_defaultValue;
    } else if (tagName == "cycle") {
      string dummy;
      is >> dummy;
      m_imp->m_cycleEnabled = true;
      // setExtrapolationAfter(Loop);
    } else if (tagName == "k") {
      // vecchio formato
      if (oldType != 0) continue;
      int linkStatus = 0;
      TActualDoubleKeyframe k;
      is >> k.m_frame >> k.m_value >> k.m_speedIn.x >> k.m_speedIn.y >>
          k.m_speedOut.x >> k.m_speedOut.y >> linkStatus;
      k.m_isKeyframe    = true;
      k.m_linkedHandles = (linkStatus & 1) != 0;
      if ((linkStatus & 1) != 0)
        k.m_type = TDoubleKeyframe::SpeedInOut;
      else if ((linkStatus & 2) != 0 || (linkStatus & 4) != 0)
        k.m_type = TDoubleKeyframe::EaseInOut;
      else
        k.m_type = TDoubleKeyframe::Linear;
      k.m_expression.setGrammar(m_imp->m_grammar);
      k.m_expression.setOwnerParameter(this);
      k.m_prevType = m_imp->m_keyframes.empty()
                         ? TDoubleKeyframe::None
                         : m_imp->m_keyframes.back().m_type;
      m_imp->m_keyframes.push_back(k);
    } else if (tagName == "expr") {
      // vecchio formato
      if (oldType != 1) continue;
      string text    = is.getTagAttribute("text");
      string enabled = is.getTagAttribute("enabled");
      TDoubleKeyframe kk1, kk2;
      kk1.m_frame          = -1000;
      kk2.m_frame          = 1000;
      kk1.m_isKeyframe     = true;
      kk2.m_isKeyframe     = true;
      kk1.m_expressionText = text;
      kk2.m_expressionText = text;
      kk1.m_type           = TDoubleKeyframe::Expression;
      kk2.m_type           = TDoubleKeyframe::Expression;
      TActualDoubleKeyframe k1(kk1);
      TActualDoubleKeyframe k2(kk2);
      k1.m_expression.setGrammar(m_imp->m_grammar);
      k1.m_expression.setOwnerParameter(this);
      k1.m_prevType = m_imp->m_keyframes.empty()
                          ? TDoubleKeyframe::None
                          : m_imp->m_keyframes.back().m_type;
      k2.m_expression.setGrammar(m_imp->m_grammar);
      k2.m_expression.setOwnerParameter(this);
      k2.m_prevType = m_imp->m_keyframes.empty()
                          ? TDoubleKeyframe::None
                          : m_imp->m_keyframes.back().m_type;
      m_imp->m_keyframes.push_back(k1);
      m_imp->m_keyframes.push_back(k2);
      continue;
    } else if (tagName == "file") {
      // vecchio formato
      if (oldType != 2) continue;
      TDoubleKeyframe::FileParams params;
      params.m_path       = TFilePath(is.getTagAttribute("path"));
      params.m_fieldIndex = std::stoi(is.getTagAttribute("index"));
      TActualDoubleKeyframe k1, k2;
      k1.m_frame      = -1000;
      k2.m_frame      = 1000;
      k1.m_isKeyframe = true;
      k2.m_isKeyframe = true;
      k1.m_fileData.setParams(params);
      k2.m_fileData.setParams(params);
      k1.m_type = TDoubleKeyframe::File;
      k2.m_type = TDoubleKeyframe::File;
      k1.m_expression.setGrammar(m_imp->m_grammar);
      k1.m_expression.setOwnerParameter(this);
      k1.m_prevType = m_imp->m_keyframes.empty()
                          ? TDoubleKeyframe::None
                          : m_imp->m_keyframes.back().m_type;
      k2.m_expression.setGrammar(m_imp->m_grammar);
      k2.m_expression.setOwnerParameter(this);
      k2.m_prevType = m_imp->m_keyframes.empty()
                          ? TDoubleKeyframe::None
                          : m_imp->m_keyframes.back().m_type;
      m_imp->m_keyframes.push_back(k1);
      m_imp->m_keyframes.push_back(k2);
      continue;
    } else if (tagName == "step") {
      int step = 0;
      is >> step;
      // if(step>1)
      //  m_imp->m_frameStep = step;
    } else if (tagName == "keyframes") {
      while (!is.eos()) {
        TDoubleKeyframe kk;
        kk.loadData(is);
         // Throw out invalid interpolation types
        if (kk.m_type == TDoubleKeyframe::None) continue;
        TActualDoubleKeyframe k(kk);
        k.m_expression.setGrammar(m_imp->m_grammar);
        k.m_expression.setOwnerParameter(this);
        k.m_prevType = m_imp->m_keyframes.empty()
                           ? TDoubleKeyframe::None
                           : m_imp->m_keyframes.back().m_type;
        m_imp->m_keyframes.push_back(k);
      }
    } else {
      throw TException(tagName + " : unexpected tag");
    }
    if (!is.matchEndTag()) throw TException(tagName + " : missing endtag");
  }
  if (m_imp->m_keyframes.empty() && !is.eos()) {
    // vecchio sistema (prima 16/1/2003)
    while (!is.eos()) {
      double t, v;
      is >> t >> v;
      m_imp->m_keyframes.push_back(TActualDoubleKeyframe(t, v));
    }
    if (!m_imp->m_keyframes.empty()) {
      m_imp->m_keyframes[0].m_prevType = TDoubleKeyframe::None;
      for (int i = 1; i < (int)m_imp->m_keyframes.size(); i++)
        m_imp->m_keyframes[i].m_prevType = m_imp->m_keyframes[i - 1].m_type;
    }
  }
  m_imp->notify(TParamChange(this, 0, 0, true, false, false));
}
References TIStream::eos(), TIStream::getTagAttribute(), TIStream::matchEndTag(), TIStream::matchTag(), and TExpression::setGrammar().
Referenced by LoadCurvePopup::execute().
observers()
const std::set< TParamObserver * > & TDoubleParam::observers () const
{
  return m_imp->m_observers;
}
operator=()
TDoubleParam & TDoubleParam::operator= (const TDoubleParam & dp)
{
  setName(dp.getName());
  m_imp->copy(dp.m_imp);
  return *this;
}
removeObserver()
void TDoubleParam::removeObserver (TParamObserver *) override virtual
Removes this from the observer.
See also
addObserver()
Implements TParam.
{
  m_imp->m_observers.erase(observer);
}
saveData()
void TDoubleParam::saveData (TOStream & os) override virtual
 This is a pure virtual function and must be overridden with a method
that implements the object saving to a data stream (i.e put the object's features on a formatted data stream). For example the TStageObject class use his implementation to save the values of the parameters that characterizes a stage object as name, coordinates, etc... on a file os is an output file stream.
Implements TPersist.
{
  // os.child("type") << (int)m_imp->m_type;
  os.child("default") << m_imp->m_defaultValue;
  if (isCycleEnabled()) os.child("cycle") << std::string("enabled");
  // if(getExtrapolationAfter() == Loop)
  //  os.child("cycle") << string("loop");
  if (!m_imp->m_keyframes.empty()) {
    os.openChild("keyframes");
    DoubleKeyframeVector::const_iterator it;
    for (it = m_imp->m_keyframes.begin(); it != m_imp->m_keyframes.end(); ++it)
      it->saveData(os);
    os.closeChild();
  }
}
References TOStream::child(), TOStream::closeChild(), and TOStream::openChild().
Referenced by SaveCurvePopup::execute().
setDefaultValue()
void TDoubleParam::setDefaultValue (double value)
{
  assert(m_imp);
  if (m_imp->m_defaultValue != value) {
    m_imp->m_defaultValue = value;
    // gmt, 19-6-2010; needed to get a notification in the FxParamsGraphicEditor
    // (Camera Stand)
    // when a param (without keyframes) is changed
    m_imp->notify(TParamChange(this, 0, 0, true, false, false));
  }
}
setGrammar()
void TDoubleParam::setGrammar (const TSyntax::Grammar * grammar)
{
  m_imp->m_grammar = grammar;
  for (int i = 0; i < (int)m_imp->m_keyframes.size(); i++)
    m_imp->m_keyframes[i].m_expression.setGrammar(grammar);
}
setKeyframe() [1/2]
void TDoubleParam::setKeyframe (const TDoubleKeyframe & k)
create a keyframe in k.m_frame (if is needed) and assign k to it
{
  DoubleKeyframeVector &keyframes = m_imp->m_keyframes;
  DoubleKeyframeVector::iterator it;
  it = std::lower_bound(keyframes.begin(), keyframes.end(), k);
  if (it != keyframes.end() && it->m_frame == k.m_frame) {
    // int index = std::distance(keyframes.begin(), it);
    TActualDoubleKeyframe &dst = *it;
    (TDoubleKeyframe &)dst     = k;
    dst.updateUnit(m_imp->m_measure);
  } else {
    it = keyframes.insert(it, TActualDoubleKeyframe(k));
    // int index = std::distance(keyframes.begin(), it);
    // TDoubleKeyframe oldKeyframe = *it;
    it->m_expression.setGrammar(m_imp->m_grammar);
    it->m_expression.setOwnerParameter(this);
    it->updateUnit(m_imp->m_measure);
  }
  it->m_isKeyframe = true;
  if (it->m_type == TDoubleKeyframe::Expression)
    it->m_expression.setText(it->m_expressionText);
  if (it->m_type == TDoubleKeyframe::File)
    it->m_fileData.setParams(it->m_fileParams);
  if (it == keyframes.begin())
    it->m_prevType = TDoubleKeyframe::None;
  else
    it->m_prevType = it[-1].m_type;
  if (it + 1 != keyframes.end()) it[1].m_prevType = it->m_type;
  m_imp->notify(TParamChange(this, 0, 0, true, false, false));
  assert(it == keyframes.begin() || (it - 1)->m_frame < it->m_frame);
  assert(it + 1 == keyframes.end() || (it + 1)->m_frame > it->m_frame);
}
setKeyframe() [2/2]
void TDoubleParam::setKeyframe (int kIndex, const TDoubleKeyframe & k)
assign k to the kIndex-th keyframe; postcondition: m_frame order is maintained
{
  DoubleKeyframeVector &keyframes = m_imp->m_keyframes;
  assert(0 <= index && index < (int)keyframes.size());
  TActualDoubleKeyframe &dst        = keyframes[index];
  TActualDoubleKeyframe oldKeyframe = dst;
  (TDoubleKeyframe &)dst = k;
  dst.updateUnit(m_imp->m_measure);
  if (dst.m_type == TDoubleKeyframe::Expression ||
      dst.m_type == TDoubleKeyframe::SimilarShape)
    dst.m_expression.setText(dst.m_expressionText);
  if (dst.m_type == TDoubleKeyframe::File)
    dst.m_fileData.setParams(dst.m_fileParams);
  m_imp->notify(TParamChange(this, 0, 0, true, false, false));
  assert(0 == index || keyframes[index - 1].m_frame < keyframes[index].m_frame);
  assert(getKeyframeCount() - 1 == index ||
         keyframes[index + 1].m_frame > keyframes[index].m_frame);
  if (index == 0)
    dst.m_prevType = TDoubleKeyframe::None;
  else
    dst.m_prevType = keyframes[index - 1].m_type;
 if (getKeyframeCount() - 1 != index)
    keyframes[index + 1].m_prevType = dst.m_type;
}
References TExpression::setText().
setKeyframes()
void TDoubleParam::setKeyframes (const std::map< int, TDoubleKeyframe > & ks)
call setKeyframe(it.first,it.second) for each it in ks; postcondition: m_frame order is maintained
{
  DoubleKeyframeVector &keyframes = m_imp->m_keyframes;
  std::map<int, TDoubleKeyframe>::const_iterator it;
  for (it = ks.begin(); it != ks.end(); ++it) {
    int index = it->first;
    assert(0 <= index && index < (int)keyframes.size());
    TActualDoubleKeyframe oldKeyframe = keyframes[index];
    TActualDoubleKeyframe &dst        = keyframes[index];
    (TDoubleKeyframe &)dst = it->second;
    dst.updateUnit(m_imp->m_measure);
    if (dst.m_type == TDoubleKeyframe::Expression ||
        dst.m_type == TDoubleKeyframe::SimilarShape)
      dst.m_expression.setText(dst.m_expressionText);
    if (dst.m_type == TDoubleKeyframe::File)
      dst.m_fileData.setParams(dst.m_fileParams);
  }
  if (!keyframes.empty()) {
    keyframes[0].m_prevType = TDoubleKeyframe::None;
    for (int i                = 1; i < (int)keyframes.size(); i++)
      keyframes[i].m_prevType = keyframes[i - 1].m_type;
  }
  m_imp->notify(TParamChange(this, 0, 0, true, false, false));
#ifndef NDEBUG
  for (int i = 0; i + 1 < (int)keyframes.size(); i++) {
    assert(keyframes[i].m_frame <= keyframes[i + 1].m_frame);
  }
#endif
}
References TExpression::setText().
setMeasureName()
void TDoubleParam::setMeasureName (std::string name)
{
  m_imp->m_measureName = name;
  m_imp->m_measure     = TMeasureManager::instance()->get(name);
}
setValue()
bool TDoubleParam::setValue (double frame, double value)
{
  assert(m_imp);
  DoubleKeyframeVector &keyframes = m_imp->m_keyframes;
  DoubleKeyframeVector::iterator it;
  TActualDoubleKeyframe k(frame);
  it           = std::lower_bound(keyframes.begin(), keyframes.end(), k);
  int index    = 0;
  bool created = false;
  /*--  --*/
  if (it != keyframes.end() && it->m_frame == frame) {
    // changing a keyframe value
    index                             = std::distance(keyframes.begin(), it);
    TActualDoubleKeyframe oldKeyframe = *it;
    if (oldKeyframe.m_type == TDoubleKeyframe::Expression ||
        oldKeyframe.m_type == TDoubleKeyframe::File)
      return false;
    it->m_value = value;
    m_imp->notify(TParamChange(this, 0, 0, true, false, false));
  }
  /*--  --*/
  else {
    assert(it == keyframes.end() || it->m_frame > frame);
    // can't change value in a file/expression segment
    if (it != keyframes.end() && it > keyframes.begin() &&
        ((it - 1)->m_type == TDoubleKeyframe::Expression ||
         (it - 1)->m_type == TDoubleKeyframe::File))
      return false;
    // inserting a new keyframe
    k.m_value      = value;
    k.m_isKeyframe = true;
    k.m_expression.setGrammar(m_imp->m_grammar);
    k.m_expression.setOwnerParameter(this);
    it = keyframes.insert(it, k);
    if (it == keyframes.begin())
      it->m_prevType = TDoubleKeyframe::None;
    else {
      it->m_prevType = it[-1].m_type;
      /*-- FxGuiSegmentKeyStep --*/
      it->m_step = it[-1].m_step;
    }
    if (it + 1 != keyframes.end()) it[1].m_prevType = it->m_type;
    index = std::distance(keyframes.begin(), it);
    m_imp->notify(TParamChange(this, 0, 0, true, false, false));
    created = true;
  }
  assert(0 == index || keyframes[index - 1].m_frame < keyframes[index].m_frame);
  assert(getKeyframeCount() - 1 == index ||
         keyframes[index + 1].m_frame > keyframes[index].m_frame);
  return created;
}
setValueRange()
void TDoubleParam::setValueRange (double min, double max, double step = 1.0)
{
  if (min > max) min = max;
  m_imp->m_minValue = min;
  m_imp->m_maxValue = max;
  // m_imp->m_valueStep = step;
}
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/tdoubleparam.h
E:/opentoonz/toonz/sources/common/tparam/tdoubleparam.cpp