opentoonz: ImageManager Class Reference
ImageManager Class Reference
#include <imagemanager.h>
Classes
struct Imp
Public Types
enum {
none = 0x0 , dontPutInCache = 0x1 , forceRebuild = 0x2 , toBeModified ,
toBeSaved = 0x8 , is64bitEnabled = 0x10 , controlFlags = 0xF , imageFlags
}
Public Member Functions
void bind (const std::string &id, ImageBuilder *builder)
bool unbind (const std::string &id)
bool isBound (const std::string &id) const
Returns true if the specified id is bound to an image builder.
bool rebind (const std::string &srcId, const std::string &dstId)
bool renumber (const std::string &srcId, const TFrameId &fid)
void clear ()
void loadAllTlvIconsAndPutInCache (TXshSimpleLevel *, std::vector< TFrameId >, std::vector< std::string >, bool)
TImageP getImage (const std::string &id, int imFlags, void *extData)
TImageInfo * getInfo (const std::string &id, int imFlags, void *extData)
bool invalidate (const std::string &id)
bool setImage (const std::string &id, const TImageP &img)
ImageBuilder * getBuilder (const std::string &id)
bool isCached (const std::string &id)
Returns whether the identifier has an associated image in cache.
bool isModified (const std::string &id)
Static Public Member Functions
static ImageManager * instance ()
Detailed Description
ImageManager is a singleton management class that associates string identifiers to image-building objects, able to fetch images on request.
The ImageManager's purpose is similar to that of TImageCache - which is Toonz's other images storage class - with the difference that users do not supply it directly with the image to be stored, but rather with an object capable of fetching that image.
Said objects must be reimplemented from the base ImageBuilder class, and return an image, and its specifications, upon request.
The role of these image-building objects is that of providing the default image for an identifier on-demand, without prior allocation of resources.
The ImageManager automatically stores built images in the global TImageCache instance (unless the user explicitly requires not to) in order to minimize the images building process.
As long as an image bound in the ImageManager remains unmodified, users can rebuild default images according to different control modifiers (for example, requiring 64-bit preference, or image subsampling).
Images stored in the ImageManager can be modified by the user (using the toBeModified control flag) or even externally supplied using the setImage() method.
When an image is modified, it is assumed to override any default-buildable images - thus it is stored in the cache for retrieval, and any control flag modifier is ignored as long as the image is not invalidated().
Invalidation of an image can be requested to revert any changes to the image and clear the cache.
Please, observe that ImageManager's image caching function is thread-safe - and ensures that image building happens only once in case multiple threads simultaneously require an image that was not cached before. Furthermore, there is no serialization overhead for already cached images or image specifications in read-only access.
See also
The TImageCache and ImageBuilder classes.
Member Enumeration Documentation
anonymous enum
anonymous enum
       {
    none           = 0x0,
    dontPutInCache = 0x1,  // Prevents IM from storing built images in the cache
    forceRebuild   = 0x2,  // Forces rebuild of images (like an invalidate())
    toBeModified =
        0x4,          // Whether the retrieved image will be signed as modified
    toBeSaved = 0x8,  // User will save the image, reverts toBeModified
    is64bitEnabled = 0x10,  // Whether 64-bit rasters are allowed to return
    controlFlags = 0xF,  // Flags dealing with management control
    imageFlags =
        ~controlFlags  // ImageManager flags supportable by custom ImageBuilders
  };
Member Function Documentation
bind()
void ImageManager::bind (const std::string & id, ImageBuilder * builder)
Binds a string identifier to an ImageBuilder instance, which is necessary before any image or image data can be retrieved. If the specified id was already bound, it is first unbound. Binding an id to 0 is equivalent to unbinding it.
{
  if (!builderPtr) {
    unbind(id);
    return;
  }
  QWriteLocker locker(&m_imp->m_tableLock);
  ImageBuilderP &builderP = m_imp->m_builders[id];
  if (builderP && builderP->m_cached) TImageCache::instance()->remove(id);
  builderP = builderPtr;
}
References TImageCache::remove(), and unbind().
Referenced by TXshChildLevel::~TXshChildLevel().
clear()
void ImageManager::clear ()
Unbinds all known identifiers, resetting the image manager to its empty state.
{
  QWriteLocker locker(&m_imp->m_tableLock);
  TImageCache::instance()->clearSceneImages();
  m_imp->clear();
}
References TImageCache::clearSceneImages().
getBuilder()
ImageBuilder * ImageManager::getBuilder (const std::string & id)
Returns the ImageBuilder instance associate to specified id, or 0 if none was found.
Warning
The ImageManger retains ownership of the returned object, which must not be deleted.
{
  QWriteLocker locker(&m_imp->m_tableLock);
  std::map<std::string, ImageBuilderP>::iterator it =
      m_imp->m_builders.find(id);
  return (it == m_imp->m_builders.end()) ? (ImageBuilder *)0
                                         : it->second.getPointer();
}
getImage()
TImageP ImageManager::getImage (const std::string & id, int imFlags, void * extData)
Returns the image built by the object associated with the specified identifier, using the supplied control flags for additional options. Provided the builder type associated to the identifier is known, a further external reference can be supplied to the request. In this case, users should enforce manual invalidate() invocations whenever the supplied data changes.
Warning
Users take responsibility in modifying the returned image's data only when imFlags contains the toBeModified bit.
{
  assert(!((imFlags & ImageManager::toBeModified) &&
           (imFlags & ImageManager::dontPutInCache)));
  assert(!((imFlags & ImageManager::toBeModified) &&
           (imFlags & ImageManager::toBeSaved)));
  // Lock for table read and try to find data in the cache
  QReadLocker tableLocker(&m_imp->m_tableLock);
  std::map<std::string, ImageBuilderP>::iterator it =
      m_imp->m_builders.find(id);
  if (it == m_imp->m_builders.end()) return TImageP();
  ImageBuilderP &builder = it->second;
  bool modified          = builder->m_modified;
  // Analyze imFlags
  bool _putInCache =
      TImageCache::instance()->isEnabled() && !(bool)(imFlags & dontPutInCache);
  bool _toBeModified = (imFlags & toBeModified);
  bool _toBeSaved    = (imFlags & toBeSaved);
  // Update the modified flag according to the specified flags
  if (_toBeModified)
    builder->m_modified = true;
  else if (_toBeSaved)
    builder->m_modified = false;
  // Now, fetch the image.
  TImageP img;
  if (builder->m_cached) {
    if (modified || builder->isImageCompatible(imFlags, extData)) {
      img = TImageCache::instance()->get(id, _toBeModified);
      assert(img);
      if (img) return img;
    }
  }
  // Lock for image building
  QWriteLocker imageBuildingLocker(&builder->m_imageBuildingLock);
  // As multiple threads may block on filesLocker, re-check if the image is now
  // available
  if (builder->m_cached) {
    if (modified || builder->isImageCompatible(imFlags, extData)) {
      img = TImageCache::instance()->get(id, _toBeModified);
      assert(img);
      if (img) return img;
    }
  }
  // The image was either not available or not conforming to the required
  // specifications.
  // We have to build it now, then.
  // Build the image
  img = builder->build(imFlags, extData);
  if (img && _putInCache) {
    builder->m_cached   = true;
    builder->m_modified = _toBeModified;
    TImageCache::instance()->add(id, img, true);
  }
  return img;
}
References TImageCache::add(), TImageCache::get(), and TImageCache::isEnabled().
Referenced by ImageRasterizer::build(), ImageFiller::build(), Stage::Player::image(), and TXshSimpleLevel::renumber().
getInfo()
TImageInfo * ImageManager::getInfo (const std::string & id, int imFlags, void * extData)
Returns the image info associated to the specified identifier.
Warning
The return type is not explicitly const since some of TImageInfo's data (namely, the image's bounding box) may need to be modified by the user together with the associated image. Like in getImage(), users take responsibility in modifying the returned data only when imFlags contains the toBeModified bit.
{
  // Lock for table read and try to find data in the cache
  QReadLocker tableLocker(&m_imp->m_tableLock);
  std::map<std::string, ImageBuilderP>::iterator it =
      m_imp->m_builders.find(id);
  if (it == m_imp->m_builders.end()) return 0;
  ImageBuilderP &builder = it->second;
  assert(!((imFlags & ImageManager::toBeModified) && !builder->m_modified));
  // Check cached data
  if (builder->areInfosCompatible(imFlags, extData)) return &builder->m_info;
  QWriteLocker imageBuildingLocker(&builder->m_imageBuildingLock);
  // Re-check as waiting may have changed the situation
  if (builder->areInfosCompatible(imFlags, extData)) return &builder->m_info;
  TImageInfo info;
  if (builder->getInfo(info, imFlags, extData)) {
    builder->m_info = info;
    return &builder->m_info;
  }
  return 0;
}
Referenced by TXshSimpleLevel::getBBox(), and TXshSimpleLevel::load().
instance()
ImageManager * ImageManager::instance () static
{
  // Re-introdotto possibile baco: voglio controllare se esiste ancora
  static ImageManager theInstance;
  return &theInstance;
}
invalidate()
bool ImageManager::invalidate (const std::string & id)
Invalidates cached data associated to the specified id, forcing the next getInfo() or getImage() to rebuild it.
{
  QWriteLocker locker(&m_imp->m_tableLock);
  std::map<std::string, ImageBuilderP>::iterator it =
      m_imp->m_builders.find(id);
  if (it == m_imp->m_builders.end()) return false;
  ImageBuilderP &builder = it->second;
  builder->invalidate();
  builder->m_cached = builder->m_modified = false;
  TImageCache::instance()->remove(id);
  return true;
}
References TImageCache::remove().
Referenced by TXshSimpleLevel::onPaletteChanged(), setImage(), and TXshSimpleLevel::touchFrame().
isBound()
bool ImageManager::isBound (const std::string & id) const
Returns true if the specified id is bound to an image builder.
{
  QReadLocker locker(&m_imp->m_tableLock);
  return m_imp->m_builders.find(id) != m_imp->m_builders.end();
}
Referenced by TXshSimpleLevel::renumber().
isCached()
bool ImageManager::isCached (const std::string & id)
Returns whether the identifier has an associated image in cache.
{
  QWriteLocker locker(&m_imp->m_tableLock);
  std::map<std::string, ImageBuilderP>::iterator it =
      m_imp->m_builders.find(id);
  return (it == m_imp->m_builders.end()) ? false : it->second->m_cached;
}
isModified()
bool ImageManager::isModified (const std::string & id)
Returns whether the image associated to the specified id has been modified. Observe that modifying an image overrides the build-up of the associated default image - ie any subsequent call to getImage() will ignore control flags and return the stored modified image.
{
  QWriteLocker locker(&m_imp->m_tableLock);
  std::map<std::string, ImageBuilderP>::iterator it =
      m_imp->m_builders.find(id);
  return (it == m_imp->m_builders.end()) ? false : it->second->m_modified;
}
loadAllTlvIconsAndPutInCache()
void ImageManager::loadAllTlvIconsAndPutInCache (TXshSimpleLevel * level, std::vector< TFrameId > fids, std::vector< std::string > iconIds, bool cacheImagesAsWell)
{
  if (fids.empty() || iconIds.empty()) return;
  // number of fid and iconId should be the same
  if ((int)fids.size() != (int)iconIds.size()) return;
  // obtain ImageLoader with the first fId
  TImageInfo info;
  std::map<std::string, ImageBuilderP>::iterator it =
      m_imp->m_builders.find(level->getImageId(fids[0]));
  if (it != m_imp->m_builders.end()) {
    const ImageBuilderP &builder = it->second;
    assert(builder);
    assert(builder->getRefCount() > 0);
    // this function in reimplemented only in ImageLoader
    builder->buildAllIconsAndPutInCache(level, fids, iconIds,
                                        cacheImagesAsWell);
    builder->getInfo(info, ImageManager::none, 0);
  }
  if (cacheImagesAsWell) {
    // reset the savebox
    info.m_x0 = info.m_y0 = 0;
    info.m_x1             = info.m_lx - 1;
    info.m_y1             = info.m_ly - 1;
    // put flags to all builders
    for (int f = 0; f < fids.size(); f++) {
      std::map<std::string, ImageBuilderP>::iterator it =
          m_imp->m_builders.find(level->getImageId(fids[f]));
      if (it != m_imp->m_builders.end()) {
        const ImageBuilderP &builder = it->second;
        builder->setImageCachedAndModified();
        builder->m_info = info;
      }
    }
  }
}
rebind()
bool ImageManager::rebind (const std::string & srcId, const std::string & dstId)
Rebinds to a different builder identifier, returning true if the operation succeeded.
{
  QWriteLocker locker(&m_imp->m_tableLock);
  std::map<std::string, ImageBuilderP>::iterator st =
      m_imp->m_builders.find(srcId);
  if (st == m_imp->m_builders.end()) return false;
  ImageBuilderP builder = st->second;
  m_imp->m_builders.erase(st);
  m_imp->m_builders[dstId] = builder;
  m_imp->m_builders[dstId]->m_cached   = true;
  m_imp->m_builders[dstId]->m_modified = true;
  TImageCache::instance()->remap(dstId, srcId);
  return true;
}
References TImageCache::remap().
Referenced by TXshSimpleLevel::makeTlv(), and TXshSimpleLevel::renumber().
renumber()
bool ImageManager::renumber (const std::string & srcId, const TFrameId & fid)
{
  std::map<std::string, ImageBuilderP>::iterator st =
      m_imp->m_builders.find(srcId);
  if (st == m_imp->m_builders.end()) return false;
  m_imp->m_builders[srcId]->setFid(fid);
  return true;
}
setImage()
bool ImageManager::setImage (const std::string & id, const TImageP & img)
Overrides the image builder, and manually associates an image to the specified identifier, putting the image in cache and updating the stored image info. If the image reference is empty, the result is equivalent to invalidate().
{
  if (!img) return invalidate(id);
  QWriteLocker locker(&m_imp->m_tableLock);
  std::map<std::string, ImageBuilderP>::iterator it =
      m_imp->m_builders.find(id);
  if (it == m_imp->m_builders.end()) return false;
  ImageBuilderP &builder = it->second;
  builder->invalidate();  // WARNING: Not all infos are correctly restored
  ImageBuilder::setImageInfo(
      builder->m_info,
      img.getPointer());  // from supplied image - must investigate further...
  TImageCache::instance()->add(id, img, true);
  builder->m_cached = builder->m_modified = true;
  return true;
}
References TImageCache::add(), and invalidate().
unbind()
bool ImageManager::unbind (const std::string & id)
Unbinds the specified identifier, returning true if the operation succeeded.
{
  QWriteLocker locker(&m_imp->m_tableLock);
  std::map<std::string, ImageBuilderP>::iterator it =
      m_imp->m_builders.find(id);
  if (it == m_imp->m_builders.end()) return false;
  ImageBuilderP &builderP = it->second;
  if (builderP && builderP->m_cached) TImageCache::instance()->remove(id);
  m_imp->m_builders.erase(it);
  return true;
}
References TImageCache::remove().
Referenced by bind().
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/toonz/imagemanager.h
E:/opentoonz/toonz/sources/toonzlib/imagemanager.cpp