opentoonz: TImage Class Reference
TImage Class Reference abstract
This is an abstract class representing an image.
#include <timage.h>
Public Types
enum Type {
NONE = 0 , RASTER = 1 , VECTOR = 2 , TOONZ_RASTER = 3 ,
MESH = 4
}
Public Types inherited from TSmartObject
typedef short ClassCode
Public Member Functions
TImage ()
virtual Type getType () const =0
virtual TRectD getBBox () const =0
virtual TImage * cloneImage () const =0
virtual TRasterP raster () const
TPalette * getPalette () const
virtual void setPalette (TPalette *palette)
Public Member Functions inherited from TSmartObject
TSmartObject (ClassCode classCode)
void addRef ()
void release ()
TINT32 getRefCount () const
Additional Inherited Members
Static Public Member Functions inherited from TSmartObject
static TINT32 getInstanceCount (ClassCode code)
Detailed Description
This is an abstract class representing an image.
Member Enumeration Documentation
Type
enum TImage::Type
This enum
Enumerator
NONE
Not a recognized image (should never happen).
RASTER
A fullcolor raster image.
VECTOR
A vector image.
TOONZ_RASTER
A colormap raster image.
MESH
A textured mesh image.
            {
    NONE         = 0,
    RASTER       = 1,
    VECTOR       = 2,
    TOONZ_RASTER = 3,
    MESH         = 4
  };
Constructor & Destructor Documentation
TImage()
TImage::TImage ()
      This class represents an interface to a generic image object.
      An image can be:
raster, i.e. a data structure representing a generally rectangular grid of pixels, or points of color or a vector image,
vector, i.e. an image represented by geometrical primitives such as points, lines, curves, and shapes or polygon(s), which are all based upon mathematical equations
: TSmartObject(m_classCode), m_palette(0) {}
~TImage()
TImage::~TImage () virtual
                {
  if (m_palette) m_palette->release();
}
Member Function Documentation
cloneImage()
virtual TImage * TImage::cloneImage () const pure virtual
 This method must return a pointer to a newly created image that is a
clone of this.
Implemented in TMeshImage, TRasterImage, TToonzImage, and TVectorImage.
Referenced by TPalette::assign(), PreviewFxManager::freeze(), and ColorModelViewer::loadCurrentFrame().
getBBox()
virtual TRectD TImage::getBBox () const pure virtual
This method must return the bounding box of the image. The bounding box is the minimum rectangle containing the image.
Implemented in TMeshImage, TRasterImage, TToonzImage, and TVectorImage.
Referenced by TXshSimpleLevel::getBBox(), and CustomStyleManager::StyleLoaderTask::run().
getPalette()
TPalette * TImage::getPalette () const inline
{ return m_palette; }
getType()
virtual Type TImage::getType () const pure virtual
This method must return the type of the image.
See also
Type.
Implemented in TMeshImage, TRasterImage, TToonzImage, and TVectorImage.
raster()
virtual TRasterP TImage::raster () const inline virtual
 Returns a pointer to the palette associated to this image. A palette
is a limited set of colors, identified by indexes and composed by a combination of primitive colors, i.e. RGB color.
Reimplemented in TRasterImage, and TToonzImage.
{ return TRasterP(); }
Referenced by ImageViewer::mouseMoveEvent(), and TRasterImage::setIconRaster().
setPalette()
void TImage::setPalette (TPalette * palette) virtual
Sets the palette for this image.
{
  if (m_palette == palette) return;
  if (palette) palette->addRef();
  if (m_palette) m_palette->release();
  m_palette = palette;
}
Referenced by ImageLoader::build(), TVectorImage::cloneImage(), TImageReaderSvg::load(), and TXshSimpleLevel::load().
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/timage.h
E:/opentoonz/toonz/sources/common/timage/timage.cpp