opentoonz: VectorizerPopup Class Reference
VectorizerPopup Class Reference final
The "Convert-To-Vector Settings" popup window.
#include <vectorizerpopup.h>
Public Slots
void onOk ()
Invokes apply(), and closes the popup once done.
Signals
void valuesChanged ()
vectorization.
Signals inherited from DVGui::Dialog
void dialogClosed ()
Public Member Functions
VectorizerPopup (QWidget *parent=0, Qt::WFlags flags=Qt::Tool)
bool apply ()
bool isLevelToConvert (TXshSimpleLevel *level)
Public Member Functions inherited from DVGui::Dialog
Dialog (QWidget *parent=0, bool hasButton=false, bool hasFixedSize=true, const QString &name=QString())
void beginVLayout ()
void endVLayout ()
void beginHLayout ()
void endHLayout ()
void addWidget (QWidget *widget, bool isRight=true)
void addWidgets (QWidget *firstW, QWidget *secondW)
void addWidget (QString labelName, QWidget *widget)
void addLayout (QLayout *layout, bool isRight=true)
void addWidgetLayout (QWidget *widget, QLayout *layout)
void addLayout (QString labelName, QLayout *layout)
void addLayouts (QLayout *firstL, QLayout *secondL)
void addSpacing (int spacing)
void addSeparator (QString name=QString())
void setAlignment (Qt::Alignment alignment)
void setTopMargin (int margin)
void setTopSpacing (int spacing)
void setLabelWidth (int labelWidth)
int getLabelWidth () const
void setLayoutInsertedSpacing (int spacing)
int getLayoutInsertedSpacing ()
void setButtonBarMargin (int margin)
void setButtonBarSpacing (int spacing)
void addButtonBarWidget (QWidget *widget)
void addButtonBarWidget (QWidget *first, QWidget *second)
void addButtonBarWidget (QWidget *first, QWidget *second, QWidget *third)
void addButtonBarWidget (QWidget *first, QWidget *second, QWidget *third, QWidget *fourth)
void hideEvent (QHideEvent *event) override
void clearButtonBar ()
Additional Inherited Members
Public Attributes inherited from DVGui::Dialog
QVBoxLayout * m_topLayout
QFrame * m_mainFrame
QFrame * m_buttonFrame
QHBoxLayout * m_mainHLayout
bool m_isMainHLayout
QVBoxLayout * m_leftVLayout
QVBoxLayout * m_rightVLayout
bool m_isMainVLayout
int m_layoutSpacing
int m_layoutMargin
int m_labelWidth
std::vector< QWidget * > m_buttonBarWidgets
Protected Member Functions inherited from DVGui::Dialog
void resizeEvent (QResizeEvent *e) override
Protected Attributes inherited from DVGui::Dialog
QHBoxLayout * m_buttonLayout
QList< QLabel * > m_labelList
Detailed Description
The "Convert-To-Vector Settings" popup window.
Vectorization interface is segmented among 3 main classes: VectorizerPopup, Vectorizer, and VectorizerCore. VectorizerPopup represents the outermost layer, providing a suitable user interface to choose between available vectorization modes and options, and displays a progress dialog to inform about the status of the underlying process.
In order to launch a suitable vectorization process, an Xsheet or scene cast selection must be active; then the show() method should be called to let the user choose the preferred vectorization options. Each parameter set is passed down to a VectorizerConfiguration class, so see there for more detailed explanations. The apply() method can be alternatively called for default options, avoiding user interaction.
During the process, the progress bar dialog is set on modal behaviour, in order to prevent the user from modifying or removing the frames to be vectorized.
See also
The VectorizerConfiguration, Vectorizer and VectorizerCore classes.
Constructor & Destructor Documentation
VectorizerPopup()
VectorizerPopup::VectorizerPopup (QWidget * parent = 0, Qt::WFlags flags = Qt::Tool)
    : Dialog(TApp::instance()->getMainWindow(), true, false, "Vectorizer")
    , m_sceneHandle(TApp::instance()->getCurrentScene()) {
  struct Locals {
    int m_bit;
    Locals() : m_bit() {}
    static void addParameterGroup(std::vector<ParamGroup> &paramGroups,
                                  int group, int startRow,
                                  int separatorRow = -1) {
      assert(group <= paramGroups.size());
      if (group == paramGroups.size())
        paramGroups.push_back(ParamGroup(startRow, separatorRow));
    }
    void addParameter(std::vector<ParamGroup> &paramGroups,
                      const QString &paramName) {
      paramGroups.back().m_params.push_back(Param(paramName, m_bit++));
    }
  } locals;
  // Su MAC i dialog modali non hanno bottoni di chiusura nella titleBar
  setModal(false);
  setWindowTitle(tr("Convert-to-Vector Settings"));
  setLabelWidth(125);
  setTopMargin(0);
  setTopSpacing(0);
  // Build vertical layout
  beginVLayout();
  QSplitter *splitter = new QSplitter(Qt::Vertical, this);
  splitter->setSizePolicy(QSizePolicy(QSizePolicy::MinimumExpanding,
                                      QSizePolicy::MinimumExpanding));
  addWidget(splitter);
  QToolBar *leftToolBar = new QToolBar, *rightToolBar = new QToolBar;
  leftToolBar->setObjectName("MediumPaddingToolBar");
  rightToolBar->setObjectName("MediumPaddingToolBar");
  leftToolBar->setIconSize(QSize(17, 17));
  rightToolBar->setIconSize(QSize(17, 17));
  {
    QWidget *toolbarsContainer = new QWidget(this);
    toolbarsContainer->setFixedHeight(22);
    addWidget(toolbarsContainer);
    QHBoxLayout *toolbarsLayout = new QHBoxLayout(toolbarsContainer);
    toolbarsContainer->setLayout(toolbarsLayout);
    toolbarsLayout->setMargin(0);
    toolbarsLayout->setSpacing(0);
    QToolBar *spacingToolBar = new QToolBar(
        toolbarsContainer);  // The spacer object must be a toolbar.
    spacingToolBar->setFixedHeight(
        22);  // It's related to qss choices... I know it's stinky
    toolbarsLayout->addWidget(leftToolBar, 0, Qt::AlignLeft);
    toolbarsLayout->addWidget(spacingToolBar, 1);
    toolbarsLayout->addWidget(rightToolBar, 0, Qt::AlignRight);
  }
  endVLayout();
  // Build parameters area
  QScrollArea *paramsArea = new QScrollArea(splitter);
  paramsArea->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
  paramsArea->setWidgetResizable(true);
  splitter->addWidget(paramsArea);
  splitter->setStretchFactor(0, 1);
  m_paramsWidget = new QFrame(paramsArea);
  paramsArea->setWidget(m_paramsWidget);
  m_paramsLayout = new QGridLayout;
  m_paramsWidget->setLayout(m_paramsLayout);
  int group = 0, row = 0;
  locals.addParameterGroup(::l_centerlineParamGroups, group, row);
  locals.addParameterGroup(::l_outlineParamGroups, group++, row);
  // Vectorization mode
  m_typeMenu = new QComboBox(this);
  m_typeMenu->setFixedSize(245, WidgetHeight);
  QStringList formats;
  formats << tr("Centerline") << tr("Outline");
  m_typeMenu->addItems(formats);
  m_typeMenu->setMinimumHeight(WidgetHeight);
  bool isOutline = m_sceneHandle->getScene()
                       ->getProperties()
                       ->getVectorizerParameters()
                       ->m_isOutline;
  m_typeMenu->setCurrentIndex(isOutline ? 1 : 0);
  connect(m_typeMenu, SIGNAL(currentIndexChanged(int)), this,
          SLOT(onTypeChange(int)));
  m_paramsLayout->addWidget(new QLabel(tr("Mode")), row, 0, Qt::AlignRight);
  m_paramsLayout->addWidget(m_typeMenu, row++, 1);
  locals.addParameter(l_centerlineParamGroups, tr("Mode"));
  locals.addParameter(l_outlineParamGroups, tr("Mode"));
  //-------------------- Parameters area - Centerline ------------------------
  locals.addParameterGroup(l_centerlineParamGroups, group++, row);
  // Threshold
  m_cThresholdLabel = new QLabel(tr("Threshold"));
  m_cThreshold      = new IntField(this);
  m_paramsLayout->addWidget(m_cThresholdLabel, row, 0, Qt::AlignRight);
  m_paramsLayout->addWidget(m_cThreshold, row++, 1);
  locals.addParameter(l_centerlineParamGroups, tr("Threshold"));
  // Accuracy
  m_cAccuracyLabel = new QLabel(tr("Accuracy"));
  m_cAccuracy      = new IntField(this);
  m_paramsLayout->addWidget(m_cAccuracyLabel, row, 0, Qt::AlignRight);
  m_paramsLayout->addWidget(m_cAccuracy, row++, 1);
  locals.addParameter(l_centerlineParamGroups, tr("Accuracy"));
  // Despeckling
  m_cDespecklingLabel = new QLabel(tr("Despeckling"));
  m_cDespeckling      = new IntField(this);
  m_paramsLayout->addWidget(m_cDespecklingLabel, row, 0, Qt::AlignRight);
  m_paramsLayout->addWidget(m_cDespeckling, row++, 1);
  locals.addParameter(l_centerlineParamGroups, tr("Despeckling"));
  // Max Thickness
  m_cMaxThicknessLabel = new QLabel(tr("Max Thickness"));
  m_paramsLayout->addWidget(m_cMaxThicknessLabel, row, 0, Qt::AlignRight);
  m_cMaxThickness = new IntField(this);
  m_cMaxThickness->enableSlider(false);
  m_paramsLayout->addWidget(m_cMaxThickness, row++, 1, Qt::AlignLeft);
  locals.addParameter(l_centerlineParamGroups, tr("Max Thickness"));
  // Thickness Calibration
  m_cThicknessRatioLabel = new QLabel(tr("Thickness Calibration"));
  m_paramsLayout->addWidget(m_cThicknessRatioLabel, row, 0, Qt::AlignRight);
  /*m_cThicknessRatio = new IntField(this);
paramsLayout->addWidget(m_cThicknessRatio, row++, 1);*/
  QHBoxLayout *cThicknessRatioLayout = new QHBoxLayout;
  cThicknessRatioLayout->addSpacing(20);
  m_cThicknessRatioFirstLabel = new QLabel(tr("Start:"));
  cThicknessRatioLayout->addWidget(m_cThicknessRatioFirstLabel);
  m_cThicknessRatioFirst = new MeasuredDoubleLineEdit(this);
  m_cThicknessRatioFirst->setMeasure("percentage");
  cThicknessRatioLayout->addWidget(m_cThicknessRatioFirst);
  m_cThicknessRatioLastLabel = new QLabel(tr("End:"));
  cThicknessRatioLayout->addWidget(m_cThicknessRatioLastLabel);
  m_cThicknessRatioLast = new MeasuredDoubleLineEdit(this);
  m_cThicknessRatioLast->setMeasure("percentage");
  cThicknessRatioLayout->addWidget(m_cThicknessRatioLast);
  cThicknessRatioLayout->addStretch(1);
  m_paramsLayout->addLayout(cThicknessRatioLayout, row++, 1);
  locals.addParameter(l_centerlineParamGroups, tr("Thickness Calibration"));
  // Checkboxes
  {
    static const QString name = tr("Preserve Painted Areas");
    locals.addParameter(l_centerlineParamGroups, name);
    m_cPaintFill = new CheckBox(name, this);
    m_cPaintFill->setFixedHeight(WidgetHeight);
    m_paramsLayout->addWidget(m_cPaintFill, row++, 1);
  }
  {
    static const QString name = tr("Align Boundary Strokes Direction");
    locals.addParameter(l_centerlineParamGroups, name);
    m_cAlignBoundaryStrokesDirection = new CheckBox(name, this);
    m_cAlignBoundaryStrokesDirection->setFixedHeight(WidgetHeight);
    m_cAlignBoundaryStrokesDirection->setToolTip(
        tr("Align boundary strokes direction to be the same.\n(clockwise, i.e. "
           "left to right as viewed from inside of the shape)"));
    m_paramsLayout->addWidget(m_cAlignBoundaryStrokesDirection, row++, 1);
  }
  {
    static const QString name = tr("Add Border");
    locals.addParameter(l_centerlineParamGroups, name);
    m_cMakeFrame = new CheckBox(name, this);
    m_cMakeFrame->setFixedHeight(WidgetHeight);
    m_paramsLayout->addWidget(m_cMakeFrame, row++, 1);
  }
  locals.addParameterGroup(l_centerlineParamGroups, group++, row + 1, row);
  m_cNaaSourceSeparator = new Separator(tr("Full color non-AA images"));
  m_paramsLayout->addWidget(m_cNaaSourceSeparator, row++, 0, 1, 2);
  {
    static const QString name = tr("Enhanced ink recognition");
    locals.addParameter(l_centerlineParamGroups, name);
    m_cNaaSource = new CheckBox(name, this);
    m_cNaaSource->setFixedHeight(WidgetHeight);
    m_paramsLayout->addWidget(m_cNaaSource, row++, 1);
  }
  //-------------------- Parameters area - Outline ------------------------
  group = 1;
  locals.addParameterGroup(l_outlineParamGroups, group++, row);
  // Accuracy
  m_oAccuracyLabel = new QLabel(tr("Accuracy"));
  m_oAccuracy      = new IntField(this);
  m_paramsLayout->addWidget(m_oAccuracyLabel, row, 0, Qt::AlignRight);
  m_paramsLayout->addWidget(m_oAccuracy, row++, 1);
  locals.addParameter(l_outlineParamGroups, tr("Accuracy"));
  // Despeckling
  m_oDespecklingLabel = new QLabel(tr("Despeckling"));
  m_oDespeckling      = new IntField(this);
  m_paramsLayout->addWidget(m_oDespecklingLabel, row, 0, Qt::AlignRight);
  m_paramsLayout->addWidget(m_oDespeckling, row++, 1);
  locals.addParameter(l_outlineParamGroups, tr("Despeckling"));
  // Paint Fill
  {
    static const QString name = tr("Preserve Painted Areas");
    locals.addParameter(l_outlineParamGroups, name);
    m_oPaintFill = new CheckBox(name, this);
    m_oPaintFill->setFixedHeight(WidgetHeight);
    m_paramsLayout->addWidget(m_oPaintFill, row++, 1);
  }
  {
    static const QString name = tr("Align Boundary Strokes Direction");
    locals.addParameter(l_outlineParamGroups, name);
    m_oAlignBoundaryStrokesDirection = new CheckBox(name, this);
    m_oAlignBoundaryStrokesDirection->setFixedHeight(WidgetHeight);
    m_oAlignBoundaryStrokesDirection->setToolTip(
        tr("Align boundary strokes direction to be the same.\n(clockwise, i.e. "
           "left to right as viewed from inside of the shape)"));
    m_paramsLayout->addWidget(m_oAlignBoundaryStrokesDirection, row++, 1);
  }
  locals.addParameterGroup(l_outlineParamGroups, group++, row + 1, row);
  m_oCornersSeparator = new Separator(tr("Corners"));
  m_paramsLayout->addWidget(m_oCornersSeparator, row++, 0, 1, 2);
  // Adherence
  m_oAdherenceLabel = new QLabel(tr("Adherence"));
  m_oAdherence      = new IntField(this);
  m_paramsLayout->addWidget(m_oAdherenceLabel, row, 0, Qt::AlignRight);
  m_paramsLayout->addWidget(m_oAdherence, row++, 1);
  locals.addParameter(l_outlineParamGroups, tr("Adherence"));
  // Angle
  m_oAngleLabel = new QLabel(tr("Angle"));
  m_oAngle      = new IntField(this);
  m_paramsLayout->addWidget(m_oAngleLabel, row, 0, Qt::AlignRight);
  m_paramsLayout->addWidget(m_oAngle, row++, 1);
  locals.addParameter(l_outlineParamGroups, tr("Angle"));
  // Relative
  m_oRelativeLabel = new QLabel(tr("Curve Radius"));
  m_oRelative      = new IntField(this);
  m_paramsLayout->addWidget(m_oRelativeLabel, row, 0, Qt::AlignRight);
  m_paramsLayout->addWidget(m_oRelative, row++, 1);
  locals.addParameter(l_outlineParamGroups, tr("Curve Radius"));
  locals.addParameterGroup(l_outlineParamGroups, group++, row + 1, row);
  m_oFullColorSeparator = new Separator(tr("Raster Levels"));
  m_paramsLayout->addWidget(m_oFullColorSeparator, row++, 0, 1, 2);
  // Max Colors
  m_oMaxColorsLabel = new QLabel(tr("Max Colors"));
  m_oMaxColors      = new IntField(this);
  m_paramsLayout->addWidget(m_oMaxColorsLabel, row, 0, Qt::AlignRight);
  m_paramsLayout->addWidget(m_oMaxColors, row++, 1);
  locals.addParameter(l_outlineParamGroups, tr("Max Colors"));
  // Transparent Color
  m_oTransparentColorLabel = new QLabel(tr("Transparent Color"), this);
  m_oTransparentColor = new ColorField(this, true, TPixel32::Transparent, 48);
  m_paramsLayout->addWidget(m_oTransparentColorLabel, row, 0, Qt::AlignRight);
  m_paramsLayout->addWidget(m_oTransparentColor, row++, 1);
  locals.addParameter(l_outlineParamGroups, tr("Transparent Color"));
  locals.addParameterGroup(l_outlineParamGroups, group++, row + 1, row);
  m_oTlvSeparator = new Separator(tr("TLV Levels"));
  m_paramsLayout->addWidget(m_oTlvSeparator, row++, 0, 1, 2);
  // Tone Threshold
  m_oToneThresholdLabel = new QLabel(tr("Tone Threshold"));
  m_oToneThreshold      = new IntField(this);
  m_paramsLayout->addWidget(m_oToneThresholdLabel, row, 0, Qt::AlignRight);
  m_paramsLayout->addWidget(m_oToneThreshold, row++, 1);
  locals.addParameter(l_outlineParamGroups, tr("Tone Threshold"));
  m_paramsLayout->setRowStretch(row, 1);
  //-------------------- Swatch area ------------------------
  m_swatchArea = new VectorizerSwatchArea(this);
  splitter->addWidget(m_swatchArea);
  m_swatchArea->setEnabled(false);  // Initially not enabled
  connect(this, SIGNAL(valuesChanged()), m_swatchArea,
          SLOT(invalidateContents()));
  //---------------------- Toolbar --------------------------
  QAction *swatchAct =
      new QAction(createQIcon("preview"), tr("Toggle Swatch Preview"), this);
  swatchAct->setCheckable(true);
  leftToolBar->addAction(swatchAct);
  QAction *centerlineAct = new QAction(createQIcon("centerline"),
                                       tr("Toggle Centerlines Check"), this);
  centerlineAct->setCheckable(true);
  leftToolBar->addAction(centerlineAct);
  QToolButton *visibilityButton = new QToolButton(this);
  visibilityButton->setIcon(createQIcon("menu"));
  visibilityButton->setText(tr("Options"));
  visibilityButton->setPopupMode(QToolButton::InstantPopup);
  QMenu *visibilityMenu = new QMenu(visibilityButton);
  visibilityButton->setMenu(visibilityMenu);
  rightToolBar->addWidget(visibilityButton);
  rightToolBar->addSeparator();
  QAction *saveAct =
      new QAction(createQIcon("save"), tr("Save Settings"), this);
  rightToolBar->addAction(saveAct);
  QAction *loadAct =
      new QAction(createQIcon("load"), tr("Load Settings"), this);
  rightToolBar->addAction(loadAct);
  rightToolBar->addSeparator();
  QAction *resetAct =
      new QAction(createQIcon("settings_reset"), tr("Reset Settings"), this);
  rightToolBar->addAction(resetAct);
  connect(swatchAct, SIGNAL(triggered(bool)), m_swatchArea,
          SLOT(enablePreview(bool)));
  connect(centerlineAct, SIGNAL(triggered(bool)), m_swatchArea,
          SLOT(enableDrawCenterlines(bool)));
  connect(visibilityMenu, SIGNAL(aboutToShow()), this,
          SLOT(populateVisibilityMenu()));
  connect(saveAct, SIGNAL(triggered()), this, SLOT(saveParameters()));
  connect(loadAct, SIGNAL(triggered()), this, SLOT(loadParameters()));
  connect(resetAct, SIGNAL(triggered()), this, SLOT(resetParameters()));
  //------------------- Convert Button ----------------------
  // Convert Button
  m_okBtn = new QPushButton(QString(tr("Convert")), this);
  connect(m_okBtn, SIGNAL(clicked()), this, SLOT(onOk()));
  addButtonBarWidget(m_okBtn);
  // All detailed signals convey to the unique valuesChanged() signal. That
  // makes it easier
  // to disconnect update notifications whenever we loadConfiguration(..).
  connect(this, SIGNAL(valuesChanged()), this, SLOT(updateSceneSettings()));
  // Connect value changes to update the global
  // VectorizerPopUpSettingsContainer.
  // connect(m_typeMenu,SIGNAL(currentIndexChanged(const QString
  // &)),this,SLOT(updateSceneSettings()));
  connect(m_cThreshold, SIGNAL(valueChanged(bool)), this,
          SLOT(onValueEdited(bool)));
  connect(m_cAccuracy, SIGNAL(valueChanged(bool)), this,
          SLOT(onValueEdited(bool)));
  connect(m_cDespeckling, SIGNAL(valueChanged(bool)), this,
          SLOT(onValueEdited(bool)));
  connect(m_cMaxThickness, SIGNAL(valueChanged(bool)), this,
          SLOT(onValueEdited(bool)));
  // connect(m_cThicknessRatio,SIGNAL(valueChanged(bool)),this,SLOT(onValueEdited(bool)));
  connect(m_cThicknessRatioFirst, SIGNAL(valueChanged()), this,
          SLOT(onValueEdited()));
  connect(m_cThicknessRatioLast, SIGNAL(valueChanged()), this,
          SLOT(onValueEdited()));
  connect(m_cMakeFrame, SIGNAL(stateChanged(int)), this, SLOT(onValueEdited()));
  connect(m_cPaintFill, SIGNAL(stateChanged(int)), this, SLOT(onValueEdited()));
  connect(m_cAlignBoundaryStrokesDirection, SIGNAL(stateChanged(int)), this,
          SLOT(onValueEdited()));
  connect(m_cNaaSource, SIGNAL(stateChanged(int)), this, SLOT(onValueEdited()));
  connect(m_oAccuracy, SIGNAL(valueChanged(bool)), this,
          SLOT(onValueEdited(bool)));
  connect(m_oDespeckling, SIGNAL(valueChanged(bool)), this,
          SLOT(onValueEdited(bool)));
  connect(m_oPaintFill, SIGNAL(stateChanged(int)), this, SLOT(onValueEdited()));
  connect(m_oAlignBoundaryStrokesDirection, SIGNAL(stateChanged(int)), this,
          SLOT(onValueEdited()));
  connect(m_oAdherence, SIGNAL(valueChanged(bool)), this,
          SLOT(onValueEdited(bool)));
  connect(m_oAngle, SIGNAL(valueChanged(bool)), this,
          SLOT(onValueEdited(bool)));
  connect(m_oRelative, SIGNAL(valueChanged(bool)), this,
          SLOT(onValueEdited(bool)));
  connect(m_oDespeckling, SIGNAL(valueChanged(bool)), this,
          SLOT(onValueEdited(bool)));
  connect(m_oMaxColors, SIGNAL(valueChanged(bool)), this,
          SLOT(onValueEdited(bool)));
  connect(m_oTransparentColor, SIGNAL(colorChanged(const TPixel32 &, bool)),
          this, SLOT(onValueEdited(const TPixel32 &, bool)));
  connect(m_oToneThreshold, SIGNAL(valueChanged(bool)), this,
          SLOT(onValueEdited(bool)));
  refreshPopup();
  // Non e' corretto: manca la possibilita' di aggiornare la selezione del
  // livello corrente
  //  connect(TApp::instance()->getCurrentLevel(), SIGNAL(xshLevelChanged()),
  //                                         this, SLOT(updateValues()));
}
Member Function Documentation
apply()
bool VectorizerPopup::apply ()
The main vectorization method - prepares input configuration and runs the vectorization thread.
{
  std::set<TXshLevel *> levels;
  ToonzScene *scene = m_sceneHandle->getScene();
  if (!scene) {
    assert(scene);
    return false;
  }
  TSceneProperties *sceneProp = scene->getProperties();
  if (!sceneProp) return false;
  VectorizerParameters *vectorizerParameters =
      sceneProp->getVectorizerParameters();
  if (!vectorizerParameters) return false;
  int r0               = 0;
  int c0               = 0;
  int r1               = 0;
  int c1               = 0;
  bool isCellSelection = getSelectedLevels(levels, r0, c0, r1, c1);
  if (c0 < 0) c0 = 0;
  if (levels.empty()) {
    error(tr("The current selection is invalid."));
    return false;
  }
  // Initialize Progress bar
  m_progressDialog = new DVGui::ProgressDialog("", "Cancel", 0, 1);
  m_progressDialog->setWindowFlags(
      Qt::Dialog | Qt::WindowTitleHint);  // Don't show ? and X buttons
  m_progressDialog->setWindowTitle(QString("Convert To Vector..."));
  m_progressDialog->setAttribute(Qt::WA_DeleteOnClose);
  m_progressDialog->setWindowModality(
      Qt::WindowModal);  // No user interaction is allowed during vectorization
  m_progressDialog->setFixedSize(200, 100);
  // Initialize vectorizer
  m_vectorizer = new Vectorizer;
  m_vectorizer->setParameters(*vectorizerParameters);
  connect(m_vectorizer, SIGNAL(frameName(QString)), this,
          SLOT(onFrameName(QString)), Qt::QueuedConnection);
  connect(m_vectorizer, SIGNAL(frameDone(int)), this, SLOT(onFrameDone(int)),
          Qt::QueuedConnection);
  connect(m_vectorizer, SIGNAL(partialDone(int, int)), this,
          SLOT(onPartialDone(int, int)), Qt::QueuedConnection);
  // We DON'T want the progress bar to be hidden at cancel press - since its
  // modal
  // behavior prevents the user to interfere with a possibly still active
  // vectorization.
  disconnect(m_progressDialog, SIGNAL(canceled()), m_progressDialog,
             SLOT(onCancel()));
  // We first inform the vectorizer of a cancel press;
  bool ret = connect(m_progressDialog, SIGNAL(canceled()), m_vectorizer,
                     SLOT(cancel()));
  // which eventually transmits the command to vectorization core, allowing
  // full-time cancels
  ret = ret && connect(m_progressDialog, SIGNAL(canceled()), m_vectorizer,
                       SIGNAL(transmitCancel()));
  // Only after the vectorizer has terminated its process - or got cancelled, we
  // are allowed
  // to proceed here.
  ret = ret && connect(m_vectorizer, SIGNAL(finished()), this,
                       SLOT(onFinished()), Qt::QueuedConnection);
  assert(ret);
  std::set<int> newColumnIndices;
  int newIndexColumn = c1 + 1;
  for (auto const level : levels) {
    TXshSimpleLevel *sl = dynamic_cast<TXshSimpleLevel *>(level);
    if (!sl || !sl->getSimpleLevel() || !isLevelToConvert(sl)) {
      QString levelName = tr(::to_string(sl->getName()).c_str());
      QString errorMsg =
          tr("Cannot convert to vector the current selection.") + levelName;
      error(errorMsg);
      continue;
    }
    std::vector<TFrameId> fids;
    if (isCellSelection)
      getSelectedFids(fids, sl, r0, c0, r1, c1);
    else
      sl->getFids(fids);
    assert(fids.size() > 0);
    close();
    // Re-initialize progress Bar
    m_progressDialog->setMaximum(fids.size() * 100);
    m_progressDialog->setValue(0);
    m_currFrame = 0;
    // Re-initialize vectorizer
    m_vectorizer->setLevel(sl);
    m_vectorizer->setFids(fids);
    // Start vectorizing
    m_vectorizer->start();
    m_progressDialog->show();
    // Wait the vectorizer...
    while (!l_quitLoop)
      QCoreApplication::processEvents(QEventLoop::AllEvents |
                                      QEventLoop::WaitForMoreEvents);
    l_quitLoop = false;
    // Assign output X-sheet cells
    TXshSimpleLevel *vl = m_vectorizer->getVectorizedLevel();
    if (isCellSelection && vl) {
      TXsheet *xsheet = TApp::instance()->getCurrentXsheet()->getXsheet();
      xsheet->insertColumn(newIndexColumn);
      int r, c;
      for (c = c0; c <= c1; c++) {
        for (r = r0; r <= r1; r++) {
          TXshCell cell = xsheet->getCell(r, c);
          TXshSimpleLevel *level =
              (!cell.isEmpty()) ? cell.getSimpleLevel() : 0;
          if (level != sl) continue;
          TFrameId curFid = cell.getFrameId();
          std::vector<TFrameId> newFids;
          vl->getFids(newFids);
          for (auto const &fid : newFids) {
            if (fid.getNumber() ==
                    curFid.getNumber() ||  // Hanno stesso numero di frame
                (fid.getNumber() == 1 &&
                 curFid.getNumber() ==
                     -2))  // La vecchia cella non ha numero di frame
              xsheet->setCell(r, newIndexColumn, TXshCell(vl, fid));
          }
        }
      }
      newColumnIndices.insert(newIndexColumn);
      newIndexColumn += 1;
    } else if (vl) {
      std::vector<TFrameId> gomi;
      newColumnIndices.insert(scene->getXsheet()->getFirstFreeColumnIndex());
      scene->getXsheet()->exposeLevel(
          0, scene->getXsheet()->getFirstFreeColumnIndex(), vl, gomi);
    }
    if (m_vectorizer->isCanceled()) break;
  }
  // Add undo object
  if (!m_vectorizer->isCanceled())
    ColumnCmd::addConvertToVectorUndo(newColumnIndices);
  m_progressDialog->close();
  delete m_vectorizer;
  TApp::instance()->getCurrentScene()->notifyCastChange();
  TApp::instance()->getCurrentXsheet()->notifyXsheetChanged();
  return true;
}
References TXsheet::exposeLevel(), TXsheet::getCell(), TApp::getCurrentScene(), TApp::getCurrentXsheet(), TXshSimpleLevel::getFids(), TXsheet::getFirstFreeColumnIndex(), TXshCell::getFrameId(), TXshLevel::getName(), ToonzScene::getProperties(), TXshCell::getSimpleLevel(), TXshSimpleLevel::getSimpleLevel(), TSceneProperties::getVectorizerParameters(), ToonzScene::getXsheet(), TXsheet::insertColumn(), TApp::instance(), Vectorizer::isCanceled(), TXshCell::isEmpty(), isLevelToConvert(), Vectorizer::setFids(), Vectorizer::setLevel(), and Vectorizer::setParameters().
Referenced by onOk().
isLevelToConvert()
bool VectorizerPopup::isLevelToConvert (TXshSimpleLevel * level)
Verifies if specified level supports
{
  return (sl->getPath().getType() != "pli");
}
References TXshSimpleLevel::getPath(), and TFilePath::getType().
Referenced by apply().
onOk
void VectorizerPopup::onOk () slot
Invokes apply(), and closes the popup once done.
{ apply(); }
References apply().
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/toonz/vectorizerpopup.h
E:/opentoonz/toonz/sources/toonz/vectorizerpopup.cpp