opentoonz: FxSelection Class Reference
FxSelection Class Reference final
Signals
void doCollapse (const QList< TFxP > &)
void doExplodeChild (const QList< TFxP > &)
void doDelete ()
void columnPasted (const QList< TXshColumnP > &)
Public Member Functions
FxSelection (const FxSelection &src)
TSelection * clone () const
void setPastePosition (const TPointD &pos)
void enableCommands () override
bool isEmpty () const override
Return true if the selection is empty.
void selectNone () override
Empty the selection.
void select (TFxP fx)
Adds the fx to the m_selectedFxs container;.
void select (int colIndex)
Adds the colIndex to the m_selectedColIndexes container;.
void unselect (TFxP fx)
Removes the fx from the m_selectedFxs container;.
void unselect (int colIndex)
Removes the colIndex from the m_selectedColIndexes container;.
void select (SchematicLink *link)
void unselect (SchematicLink *link)
Removes a QPair<TFxP,TFxP> from the m_selectedLinks container.
bool isSelected (TFxP fx) const
Returns true if the given fx is selected.
bool isSelected (int columnIndex) const
Returns true if the given columnIndex is selected.
bool isSelected (SchematicLink *link)
const QList< TFxP > & getFxs () const
const QList< Link > & getLinks () const
const QList< int > & getColumnIndexes () const
void setXsheetHandle (TXsheetHandle *xshHandle)
void setFxHandle (TFxHandle *fxHandle)
int size ()
void deleteSelection ()
Calls the TFxCommand::deleteSelection() to remove selected links or fxs.
void copySelection ()
Copy selected fxs in the clipboard.
void cutSelection ()
void pasteSelection ()
bool insertPasteSelection ()
bool addPasteSelection ()
bool replacePasteSelection ()
void groupSelection ()
void ungroupSelection ()
void collapseSelection ()
void explodeChild ()
Link getBoundingFxs (SchematicLink *link)
bool isConnected ()
void setFxSchematicScene (FxSchematicScene *schematicScene)
Public Member Functions inherited from TSelection
virtual void enableCommands ()
void enableCommand (CommandId cmdId, CommandHandlerInterface *handler)
template<class T >
void enableCommand (T *target, CommandId cmdId, void(T::*method)())
template<class T , typename R >
void enableCommand (T *target, CommandId cmdId, void(T::*method)(R), R value)
void makeCurrent ()
void makeNotCurrent ()
virtual bool isEmpty () const =0
virtual void selectNone ()=0
virtual bool addMenuActions (QMenu *menu)
void addMenuAction (QMenu *menu, CommandId cmdId)
void setView (View *view)
View * getView () const
void notifyView ()
Additional Inherited Members
Static Public Member Functions inherited from TSelection
static TSelection * getCurrent ()
static void setCurrent (TSelection *selection)
Detailed Description
Constructor & Destructor Documentation
FxSelection() [1/2]
FxSelection::FxSelection ()
    : m_xshHandle(0)
    , m_fxHandle(0)
    , m_pastePosition(TConst::nowhere)
    , m_schematicScene(0) {}
FxSelection() [2/2]
FxSelection::FxSelection (const FxSelection & src)
    : m_selectedFxs(src.m_selectedFxs)
    , m_selectedLinks(src.m_selectedLinks)
    , m_xshHandle(src.m_xshHandle)
    , m_fxHandle(src.m_fxHandle)
    , m_selectedColIndexes(src.m_selectedColIndexes)
    , m_pastePosition(TConst::nowhere)
    , m_schematicScene(src.m_schematicScene) {}
~FxSelection()
FxSelection::~FxSelection ()
{}
Member Function Documentation
addPasteSelection()
bool FxSelection::addPasteSelection ()
Get fxs from the clipboards and calls the TFxCommand::addPasteFxs(const QList<TFxP> &fxs, TXsheetHandle*) to insert fxs in the scene. Fxs are pasted only if they are connected!
{
  QClipboard *clipboard  = QApplication::clipboard();
  const FxsData *fxsData = dynamic_cast<const FxsData *>(clipboard->mimeData());
  m_pastePosition = TConst::nowhere;
  if (!fxsData || !fxsData->isConnected()) return false;
  if (m_selectedFxs.isEmpty()) return true;
  struct Auto {
    bool m_destruct;
    ~Auto() {
      if (m_destruct) TUndoManager::manager()->endBlock();
    }
  } auto_ = {false};
  QList<TFxP> selectedFxs(m_selectedFxs);
  int i, size = selectedFxs.size();
  for (i = 0; i < size; ++i) {
    // Clone the fxs to be inserted
    QList<TFxP> fxs;
    QMap<TFx *, int> zeraryFxColumnSize;
    QList<TXshColumnP> columns;
    fxsData->getFxs(fxs, zeraryFxColumnSize, columns);
    if (fxs.empty() && columns.empty()) return true;
    // auto ends the undo block in its destructor
    if (!auto_.m_destruct)
      auto_.m_destruct = true, TUndoManager::manager()->beginBlock();
    TFx *inFx = selectedFxs[i].getPointer();
    TFxCommand::addPasteFxs(inFx, fxs.toStdList(),
                            zeraryFxColumnSize.toStdMap(), columns.toStdList(),
                            m_xshHandle, m_fxHandle);
  }
  return true;
}
References FxsData::getFxs(), FxsData::isConnected(), and size().
clone()
TSelection * FxSelection::clone () const
{
  assert(0);
  return new FxSelection(*this);
}
collapseSelection()
void FxSelection::collapseSelection ()
{
  if (!m_selectedFxs.isEmpty()) emit doCollapse(m_selectedFxs);
}
copySelection()
void FxSelection::copySelection ()
Copy selected fxs in the clipboard.
{
  QClipboard *clipboard = QApplication::clipboard();
  FxsData *fxsData      = new FxsData();
  fxsData->setFxs(m_selectedFxs, m_selectedLinks, m_selectedColIndexes,
                  m_xshHandle->getXsheet());
  clipboard->setMimeData(fxsData);
}
References FxsData::setFxs().
Referenced by cutSelection().
cutSelection()
void FxSelection::cutSelection ()
Copy selected fxs in the clipboard and alls the TFxCommand::deleteSelection() to remove selected links or fxs.
{
  copySelection();
  deleteSelection();
}
References copySelection(), and deleteSelection().
deleteSelection()
void FxSelection::deleteSelection ()
Calls the TFxCommand::deleteSelection() to remove selected links or fxs.
{
  emit doDelete();
  // std::list<TFxP, std::allocator<TFxP>> fxList = m_selectedFxs.toStdList();
  // TFxCommand::deleteSelection(fxList, m_selectedLinks.toStdList(),
  //                            m_selectedColIndexes.toStdList(), m_xshHandle,
  //                            m_fxHandle);
}
Referenced by cutSelection().
enableCommands()
void FxSelection::enableCommands () override virtual
Reimplemented from TSelection.
{
  enableCommand(this, MI_Clear, &FxSelection::deleteSelection);
  enableCommand(this, MI_Cut, &FxSelection::cutSelection);
  enableCommand(this, MI_Copy, &FxSelection::copySelection);
  enableCommand(this, MI_Paste, &FxSelection::pasteSelection);
  enableCommand(this, MI_Group, &FxSelection::groupSelection);
  enableCommand(this, MI_Ungroup, &FxSelection::ungroupSelection);
  enableCommand(this, MI_Collapse, &FxSelection::collapseSelection);
  enableCommand(this, MI_ExplodeChild, &FxSelection::explodeChild);
}
explodeChild()
void FxSelection::explodeChild ()
{
  if (!m_selectedFxs.isEmpty()) emit doExplodeChild(m_selectedFxs);
}
getBoundingFxs()
Link FxSelection::getBoundingFxs (SchematicLink * link)
{
  Link boundingFxs;
  if (link) {
    SchematicPort *port = link->getStartPort();
    if (!port) return boundingFxs;
    if (port->getType() == 201 || port->getType() == 202 ||
        port->getType() == 203)
      boundingFxs = getBoundingFxs(port, link->getOtherPort(port));
    else if (port->getType() == 200 || port->getType() == 204)
      boundingFxs = getBoundingFxs(link->getOtherPort(port), port);
  }
  return boundingFxs;
}
getColumnIndexes()
const QList< int > & FxSelection::getColumnIndexes () const inline
{ return m_selectedColIndexes; }
getFxs()
const QList< TFxP > & FxSelection::getFxs () const inline
{ return m_selectedFxs; }
getLinks()
const QList< Link > & FxSelection::getLinks () const inline
{ return m_selectedLinks; }
groupSelection()
void FxSelection::groupSelection ()
{
  if (m_selectedFxs.size() <= 1) return;
  TFxCommand::groupFxs(m_selectedFxs.toStdList(), m_xshHandle);
  selectNone();
  m_xshHandle->notifyXsheetChanged();
}
insertPasteSelection()
bool FxSelection::insertPasteSelection ()
Get fxs from the clipboards and calls the TFxCommand::insertPasteFxs(const QList<TFxP> &fxs, TXsheetHandle*) to insert fxs in the scene. Fxs are pasted only if they are connected!
{
  QClipboard *clipboard  = QApplication::clipboard();
  const FxsData *fxsData = dynamic_cast<const FxsData *>(clipboard->mimeData());
  m_pastePosition = TConst::nowhere;
  if (!fxsData || !fxsData->isConnected()) return false;
  if (m_selectedLinks.isEmpty()) return true;
  // Start an undo block and ensure it is appropriately destroyed
  struct Auto {
    bool m_destruct;
    ~Auto() {
      if (m_destruct) TUndoManager::manager()->endBlock();
    }
  } auto_ = {false};
  // Need to make a temporary copy of selected links. It's necessary since the
  // selection will
  // be updated (cleared) after each insertion.
  QList<TFxCommand::Link> selectedLinks(m_selectedLinks);
  int i, size = selectedLinks.size();
  for (i = 0; i < size; ++i) {
    // Clone the fxs to be inserted
    QList<TFxP> fxs;
    QMap<TFx *, int> zeraryFxColumnSize;
    QList<TXshColumnP> columns;
    fxsData->getFxs(fxs, zeraryFxColumnSize, columns);
    if (fxs.empty() && columns.empty()) return true;
    // auto ends the undo block in the destructor.
    if (!auto_.m_destruct) {
      auto_.m_destruct = true;
      TUndoManager::manager()->beginBlock();
      // make sure that the levels contained in the pasted column nodes are
      // registered in the scene cast it may rename the level if there is
      // another level with the same name
      emit columnPasted(columns);
    }
    TFxCommand::insertPasteFxs(selectedLinks[i], fxs.toStdList(),
                               zeraryFxColumnSize.toStdMap(),
                               columns.toStdList(), m_xshHandle, m_fxHandle);
  }
  return true;
}
References FxsData::getFxs(), FxsData::isConnected(), and size().
Referenced by pasteSelection().
isConnected()
bool FxSelection::isConnected ()
Return true if the selection is connected; A selection is connected if nodes and links selected create a connected graph
{
  if (m_selectedFxs.isEmpty()) return false;
  QList<TFx *> visitedFxs;
  visitFx(m_selectedFxs.at(0).getPointer(), visitedFxs);
  bool connected = true;
  QList<TFxP>::const_iterator it;
  TXsheet *xsh        = m_xshHandle->getXsheet();
  TFxSet *internalFxs = xsh->getFxDag()->getInternalFxs();
  for (it = m_selectedFxs.begin(); it != m_selectedFxs.end(); it++) {
    TFx *selectedFx = it->getPointer();
    TColumnFx *cfx  = dynamic_cast<TColumnFx *>(selectedFx);
    if (!cfx && !internalFxs->containsFx(selectedFx)) return false;
    TZeraryColumnFx *zfx = dynamic_cast<TZeraryColumnFx *>(selectedFx);
    if (zfx) selectedFx = zfx->getZeraryFx();
    connected = connected && visitedFxs.contains(selectedFx);
  }
  return connected;
}
References TXsheet::getFxDag().
isEmpty()
bool FxSelection::isEmpty () const inline override virtual
Return true if the selection is empty.
Implements TSelection.
{
    return m_selectedFxs.empty() && m_selectedLinks.empty() &&
           m_selectedColIndexes.isEmpty();
  }
Referenced by FxSchematicScene::simulateDisconnectSelection().
isSelected() [1/3]
bool FxSelection::isSelected (int columnIndex) const
Returns true if the given columnIndex is selected.
{
  return m_selectedColIndexes.contains(columnIndex);
}
isSelected() [2/3]
bool FxSelection::isSelected (SchematicLink * link)
Returns true if the QPair<TFxP,TFxP> of the fxs that bounds the given link is contained in the m_selectedLinks container.
{
  Link boundingFxs = getBoundingFxs(link);
  return m_selectedLinks.contains(boundingFxs);
}
isSelected() [3/3]
bool FxSelection::isSelected (TFxP fx) const
Returns true if the given fx is selected.
{
  int i;
  for (i = 0; i < m_selectedFxs.size(); i++) {
    TFx *selectedFx      = m_selectedFxs[i].getPointer();
    TZeraryColumnFx *zfx = dynamic_cast<TZeraryColumnFx *>(selectedFx);
    if (zfx &&
        (fx.getPointer() == zfx || fx.getPointer() == zfx->getZeraryFx()))
      return true;
    if (fx.getPointer() == selectedFx) return true;
  }
  return false;
}
pasteSelection()
void FxSelection::pasteSelection ()
Get fxs from the clipboards and calls the TFxCommand::pasteFxs(const QList<TFxP> &fxs, TXsheetHandle*) to insert fxs in the scene.
{
  /*--- FxReplace paste ---*/
  if (m_selectedFxs.size() >= 1 && m_selectedLinks.size() == 0 &&
      m_selectedColIndexes.isEmpty())
    replacePasteSelection();
  /*--- LinkInsert paste ---*/
  else if (m_selectedFxs.size() == 0 && m_selectedLinks.size() >= 1 &&
           m_selectedColIndexes.isEmpty())
    insertPasteSelection();
  else {
    QClipboard *clipboard = QApplication::clipboard();
    const FxsData *fxsData =
        dynamic_cast<const FxsData *>(clipboard->mimeData());
    if (!fxsData) return;
    QList<TFxP> fxs;
    QMap<TFx *, int> zeraryFxColumnSize;
    QList<TXshColumnP> columns;
    fxsData->getFxs(fxs, zeraryFxColumnSize, columns);
    if (fxs.isEmpty() && columns.isEmpty()) return;
    // in case of the paste command triggered from short cut key
    if (m_pastePosition == TConst::nowhere && m_schematicScene) {
      SchematicSceneViewer *ssv =
          dynamic_cast<SchematicSceneViewer *>(m_schematicScene->views().at(0));
      if (ssv)
        m_pastePosition =
            TPointD(ssv->getOldScenePos().x(), ssv->getOldScenePos().y());
    }
    if (!columns.isEmpty()) {
      // make sure that the levels contained in the pasted column nodes are
      // registered in the scene cast it may rename the level if there is
      // another level with the same name
      TUndoManager::manager()->beginBlock();
      emit columnPasted(columns);
    }
    TFxCommand::pasteFxs(fxs.toStdList(), zeraryFxColumnSize.toStdMap(),
                         columns.toStdList(), m_pastePosition, m_xshHandle,
                         m_fxHandle);
    if (!columns.isEmpty()) {
      TUndoManager::manager()->endBlock();
    }
    if (m_schematicScene) {
      selectNone();
      for (int i = 0; i < (int)fxs.size(); i++) select(fxs[i]);
      m_schematicScene->selectNodes(fxs);
    }
  }
  m_pastePosition = TConst::nowhere;
}
References FxsData::getFxs(), insertPasteSelection(), replacePasteSelection(), select(), FxSchematicScene::selectNodes(), and selectNone().
replacePasteSelection()
bool FxSelection::replacePasteSelection ()
Get fxs from the clipboards and calls the TFxCommand::replacePasteFxs(const QList<TFxP> &fxs, TXsheetHandle*) to insert fxs in the scene. Fxs are pasted only if they are connected!
{
  QClipboard *clipboard  = QApplication::clipboard();
  const FxsData *fxsData = dynamic_cast<const FxsData *>(clipboard->mimeData());
  m_pastePosition = TConst::nowhere;
  if (!fxsData || !fxsData->isConnected()) return false;
  if (m_selectedFxs.isEmpty()) return true;
  struct Auto {
    bool m_destruct;
    ~Auto() {
      if (m_destruct) TUndoManager::manager()->endBlock();
    }
  } auto_ = {false};
  QList<TFxP> selectedFxs(m_selectedFxs);
  int i, size = selectedFxs.size();
  for (i = 0; i < size; ++i) {
    // Clone the fxs to be inserted
    QList<TFxP> fxs;
    QMap<TFx *, int> zeraryFxColumnSize;
    QList<TXshColumnP> columns;
    fxsData->getFxs(fxs, zeraryFxColumnSize, columns);
    if (fxs.empty() && columns.empty()) return true;
    // auto ends the undo block in its destructor
    if (!auto_.m_destruct) {
      auto_.m_destruct = true, TUndoManager::manager()->beginBlock();
      // make sure that the levels contained in the pasted column nodes are
      // registered in the scene cast it may rename the level if there is
      // another level with the same name
      emit columnPasted(columns);
    }
    TFx *inFx = m_selectedFxs[i].getPointer();
    TFxCommand::replacePasteFxs(inFx, fxs.toStdList(),
                                zeraryFxColumnSize.toStdMap(),
                                columns.toStdList(), m_xshHandle, m_fxHandle);
  }
  return true;
}
References FxsData::getFxs(), FxsData::isConnected(), and size().
Referenced by pasteSelection().
select() [1/3]
void FxSelection::select (int colIndex)
Adds the colIndex to the m_selectedColIndexes container;.
{
  m_selectedColIndexes.append(colIndex);
  std::sort(m_selectedColIndexes.begin(), m_selectedColIndexes.end());
}
select() [2/3]
void FxSelection::select (SchematicLink * link)
Adds a QPair<TFxP,TFxP> to the m_selectedLinks container. The first element of of the QPair is the fx that has the link in input. The second element of of the QPair is the fx that has the link in output
{
  if (link->isLineShaped()) return;
  Link boundingFxs = getBoundingFxs(link);
  if (boundingFxs == Link()) return;
  m_selectedLinks.append(boundingFxs);
}
References SchematicLink::isLineShaped().
select() [3/3]
void FxSelection::select (TFxP fx)
Adds the fx to the m_selectedFxs container;.
{ m_selectedFxs.append(fx); }
Referenced by pasteSelection().
selectNone()
void FxSelection::selectNone () inline override virtual
Empty the selection.
Implements TSelection.
{
    m_selectedFxs.clear();
    m_selectedLinks.clear();
    m_selectedColIndexes.clear();
  }
Referenced by pasteSelection().
setFxHandle()
void FxSelection::setFxHandle (TFxHandle * fxHandle) inline
{ m_fxHandle = fxHandle; }
setFxSchematicScene()
void FxSelection::setFxSchematicScene (FxSchematicScene * schematicScene) inline
{
    m_schematicScene = schematicScene;
  }
setPastePosition()
void FxSelection::setPastePosition (const TPointD & pos) inline
{ m_pastePosition = pos; }
setXsheetHandle()
void FxSelection::setXsheetHandle (TXsheetHandle * xshHandle) inline
{ m_xshHandle = xshHandle; }
size()
int FxSelection::size () inline
Returns the size of the selection. The size is the number of fxs and link selected.
{ return m_selectedFxs.size() + m_selectedLinks.size(); }
Referenced by addPasteSelection(), insertPasteSelection(), and replacePasteSelection().
ungroupSelection()
void FxSelection::ungroupSelection ()
{
  if (isEmpty()) return;
  QSet<int> idSet;
  int i;
  for (i = 0; i < m_selectedFxs.size(); i++) {
    int groupId = m_selectedFxs[i]->getAttributes()->getGroupId();
    if (groupId > 0) idSet.insert(groupId);
  }
  TUndoManager::manager()->beginBlock();
  QSet<int>::iterator it;
  for (it = idSet.begin(); it != idSet.end(); it++) {
    TFxCommand::ungroupFxs(*it, m_xshHandle);
  }
  TUndoManager::manager()->endBlock();
  selectNone();
  m_xshHandle->notifyXsheetChanged();
}
unselect() [1/3]
void FxSelection::unselect (int colIndex)
Removes the colIndex from the m_selectedColIndexes container;.
{
  m_selectedColIndexes.removeOne(colIndex);
}
unselect() [2/3]
void FxSelection::unselect (SchematicLink * link)
Removes a QPair<TFxP,TFxP> from the m_selectedLinks container.
{
  Link boundingFxs = getBoundingFxs(link);
  int index        = m_selectedLinks.indexOf(boundingFxs);
  if (index >= 0) m_selectedLinks.removeAt(index);
}
unselect() [3/3]
void FxSelection::unselect (TFxP fx)
Removes the fx from the m_selectedFxs container;.
{
  int index = m_selectedFxs.indexOf(fx);
  if (index >= 0) m_selectedFxs.removeAt(index);
}
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/toonzqt/fxselection.h
E:/opentoonz/toonz/sources/toonzqt/fxselection.cpp