opentoonz: TSoundTrack Class Reference
TSoundTrack Class Reference abstract
#include <tsound.h>
Public Member Functions
TINT32 secondsToSamples (double sec) const
Converts from seconds to samples according to the soundtrack sample rate.
double samplesToSeconds (TINT32 smp) const
Converts from samples to seconds according to the soundtrack sample rate.
TUINT32 getSampleRate () const
int getSampleSize () const
int getChannelCount () const
int getBitPerSample () const
TINT32 getSampleCount () const
double getDuration () const
Returns the duration of the soundtrack in seconds.
virtual bool isSampleSigned () const =0
Returns true if the samples of the soundtrack are signed, false otherwise.
TSoundTrackFormat getFormat () const
Returns the soundtrack format.
const UCHAR * getRawData () const
Returns a pointer to the samples buffer.
void setSampleRate (TUINT32 sampleRate)
virtual TSoundTrackP clone () const =0
Clones the soundtrack.
virtual TSoundTrackP clone (TSound::Channel chan) const =0
Returns a soundtrack that contains just the cloned channel.
virtual TSoundTrackP extract (TINT32 s0, TINT32 s1)=0
Returns a subtrack for the range [s0, s1], s0 and s1 are samples.
TSoundTrackP extract (double t0, double t1)
Returns a subtrack for the range [t0, t1], t0 and t1 are seconds.
virtual void copy (const TSoundTrackP &src, TINT32 dst_s0)=0
void copy (const TSoundTrackP &src, double dst_t0)
virtual void blank (TINT32 s0, TINT32 s1)=0
Blanks the soundtrack in the given range.
void blank (double t0, double t1)
virtual TSoundTrackP apply (TSoundTransform *)=0
virtual double getPressure (TINT32 sample, TSound::Channel chan) const =0
double getPressure (double second, TSound::Channel chan) const
Returns the soundtrack pressure value for the given time and channel.
virtual void getMinMaxPressure (TINT32 s0, TINT32 s1, TSound::Channel chan, double &min, double &max) const =0
void getMinMaxPressure (double t0, double t1, TSound::Channel chan, double &min, double &max) const
void getMinMaxPressure (TSound::Channel chan, double &min, double &max) const
Returns the soundtrack pressure min and max values for the given channel.
virtual double getMaxPressure (TINT32 s0, TINT32 s1, TSound::Channel chan) const =0
double getMaxPressure (double t0, double t1, TSound::Channel chan) const
double getMaxPressure (TSound::Channel chan) const
Returns the soundtrack pressure max value for the given channel.
virtual double getMinPressure (TINT32 s0, TINT32 s1, TSound::Channel chan) const =0
double getMinPressure (double t0, double t1, TSound::Channel chan) const
double getMinPressure (TSound::Channel chan) const
Returns the soundtrack pressure min value for the given channel.
Public Member Functions inherited from TSmartObject
TSmartObject (ClassCode classCode)
void addRef ()
void release ()
TINT32 getRefCount () const
Static Public Member Functions
static TSoundTrackP create (TUINT32 sampleRate, int bitPerSample, int channelCount, TINT32 sampleCount, bool signedSample=true)
static TSoundTrackP create (TUINT32 sampleRate, int bitPerSample, int channelCount, TINT32 sampleCount, void *buffer, bool signedSample=true)
static TSoundTrackP create (const TSoundTrackFormat &format, TINT32 sampleCount)
static TSoundTrackP create (const TSoundTrackFormat &format, TINT32 sampleCount, void *buffer)
Static Public Member Functions inherited from TSmartObject
static TINT32 getInstanceCount (ClassCode code)
Protected Member Functions
TSoundTrack (TUINT32 sampleRate, int bitPerSample, int channelCount, int sampleSize, TINT32 sampleCount, bool isSampleSigned)
TSoundTrack (TUINT32 sampleRate, int bitPerSample, int channelCount, int sampleSize, TINT32 sampleCount, UCHAR *buffer, TSoundTrack *parent)
Protected Attributes
TUINT32 m_sampleRate
int m_sampleSize
int m_bitPerSample
TINT32 m_sampleCount
int m_channelCount
TSoundTrack * m_parent
UCHAR * m_buffer
bool m_bufferOwner
Additional Inherited Members
Public Types inherited from TSmartObject
typedef short ClassCode
Detailed Description
The class TSoundTrack contains all features about a sound track and gives all methods to access to these information
Constructor & Destructor Documentation
TSoundTrack() [1/3]
TSoundTrack::TSoundTrack () protected
    : TSmartObject(m_classCode)
    , m_parent(0)
    , m_buffer(0)
    , m_bufferOwner(false) {}
TSoundTrack() [2/3]
TSoundTrack::TSoundTrack (TUINT32 sampleRate, int bitPerSample, int channelCount, int sampleSize, TINT32 sampleCount, bool isSampleSigned) protected
    : TSmartObject(m_classCode)
    , m_sampleRate(sampleRate)
    , m_sampleSize(sampleSize)
    , m_bitPerSample(bitPerSample)
    , m_sampleCount(sampleCount)
    , m_channelCount(channelCount)
    , m_parent(0)
    , m_bufferOwner(true) {
  m_buffer = (UCHAR *)malloc(sampleCount * m_sampleSize);
  if (!m_buffer) return;
  // m_buffer = new UCHAR[sampleCount*m_sampleSize];
  if (isSampleSigned)
    memset(m_buffer, 0, sampleCount * sampleSize);
  else
    memset(m_buffer, 127, sampleCount * sampleSize);
}
TSoundTrack() [3/3]
TSoundTrack::TSoundTrack (TUINT32 sampleRate, int bitPerSample, int channelCount, int sampleSize, TINT32 sampleCount, UCHAR * buffer, TSoundTrack * parent) protected
    : TSmartObject(m_classCode)
    , m_sampleRate(sampleRate)
    , m_sampleSize(sampleSize)
    , m_bitPerSample(bitPerSample)
    , m_sampleCount(sampleCount)
    , m_channelCount(channelCount)
    , m_parent(parent)
    , m_buffer(buffer)
    , m_bufferOwner(false) {
  if (m_parent) m_parent->addRef();
}
~TSoundTrack()
TSoundTrack::~TSoundTrack ()
{
  if (m_parent) m_parent->release();
  // if (m_buffer && m_bufferOwner) delete [] m_buffer;
  if (m_buffer && m_bufferOwner) free(m_buffer);
}
Member Function Documentation
apply()
virtual TSoundTrackP TSoundTrack::apply (TSoundTransform *) pure virtual
Returns a new soundtrack obtained applying the given sound transform to the soundtrack
Implemented in TSoundTrackT< T >.
Referenced by TSop::crossFade(), TSop::fadeIn(), TSop::fadeOut(), TSop::gate(), TSop::mix(), TSop::resample(), TSop::reverb(), and TSop::timeStretch().
blank() [1/2]
void TSoundTrack::blank (double t0, double t1)
Blanks the soundtrack in the given range. Range is expressed in seconds.
{
  blank(secondsToSamples(t0), secondsToSamples(t1));
}
References blank(), and secondsToSamples().
blank() [2/2]
virtual void TSoundTrack::blank (TINT32 s0, TINT32 s1) pure virtual
Blanks the soundtrack in the given range.
Implemented in TSoundTrackT< T >.
Referenced by blank(), and TSop::convert().
clone() [1/2]
virtual TSoundTrackP TSoundTrack::clone () const pure virtual
Clones the soundtrack.
Implemented in TSoundTrackT< T >.
Referenced by TSoundTrackT< T >::clone(), and TSop::remove().
clone() [2/2]
virtual TSoundTrackP TSoundTrack::clone (TSound::Channel chan) const pure virtual
Returns a soundtrack that contains just the cloned channel.
Implemented in TSoundTrackT< T >.
copy() [1/2]
void TSoundTrack::copy (const TSoundTrackP & src, double dst_t0)
Copies the all samples of the source soundtrack to the object, starting from dst_t0. dst_t0 is expressed in seconds.
{
  copy(src, secondsToSamples(dst_t0));
}
References copy(), and secondsToSamples().
copy() [2/2]
virtual void TSoundTrack::copy (const TSoundTrackP & src, TINT32 dst_s0) pure virtual
Copies the all samples of the source soundtrack to the object, starting from dst_s0. dst_s0 is expressed in samples.
Implemented in TSoundTrackT< T >.
Referenced by TSoundTrackT< T >::clone(), and copy().
create() [1/4]
TSoundTrackP TSoundTrack::create (const TSoundTrackFormat & format, TINT32 sampleCount) static
Create a new soundtrack according to the format and number of samples specified as inputs
{
  return TSoundTrack::create((int)format.m_sampleRate, format.m_bitPerSample,
                             format.m_channelCount, sampleCount,
                             format.m_signedSample);
}
References create().
create() [2/4]
TSoundTrackP TSoundTrack::create (const TSoundTrackFormat & format, TINT32 sampleCount, void * buffer) static
{
  return TSoundTrack::create((int)format.m_sampleRate, format.m_bitPerSample,
                             format.m_channelCount, sampleCount, buffer,
                             format.m_signedSample);
}
create() [3/4]
TSoundTrackP TSoundTrack::create (TUINT32 sampleRate, int bitPerSample, int channelCount, TINT32 sampleCount, bool signedSample = true) static
Create a new soundtrack according to the sample rate, bits per sample, number of channels and number of samples specified as inputs. signedSample must be true for tracks whose samples are signed
{
  TSoundTrackP st;
  int type = bitPerSample + channelCount;
  switch (type) {
  case TRK_M8:
    if (signedSample)
      st = new TSoundTrackMono8Signed(sampleRate, channelCount, sampleCount);
    else
      st = new TSoundTrackMono8Unsigned(sampleRate, channelCount, sampleCount);
    break;
  case TRK_S8:
    if (signedSample)
      st = new TSoundTrackStereo8Signed(sampleRate, channelCount, sampleCount);
    else
      st =
          new TSoundTrackStereo8Unsigned(sampleRate, channelCount, sampleCount);
    break;
  case TRK_M16:
    st = new TSoundTrackMono16(sampleRate, channelCount, sampleCount);
    break;
  case TRK_S16:
    st = new TSoundTrackStereo16(sampleRate, channelCount, sampleCount);
    break;
  case TRK_M24:
    st = new TSoundTrackMono24(sampleRate, channelCount, sampleCount);
    break;
  case TRK_S24:
    st = new TSoundTrackStereo24(sampleRate, channelCount, sampleCount);
    break;
  default:
    std::string s;
    s = "Type " + std::to_string(sampleRate) + " Hz " +
        std::to_string(bitPerSample) + " bits ";
    if (channelCount == 1)
      s += "mono: ";
    else
      s += "stereo: ";
    s += "Unsupported\n";
    throw TException(s);
  }
  if (!st->getRawData()) {
    return 0;
  }
  return st;
}
References getRawData().
Referenced by TSoundTrackT< T >::clone(), TSop::convert(), create(), TSop::insertBlank(), TSoundTrackReaderWav::load(), TXshSoundColumn::play(), TSop::remove(), and TSoundInputDevice::stop().
create() [4/4]
TSoundTrackP TSoundTrack::create (TUINT32 sampleRate, int bitPerSample, int channelCount, TINT32 sampleCount, void * buffer, bool signedSample = true) static
{
  TSoundTrackP st;
  int type = bitPerSample + channelCount;
  switch (type) {
  case TRK_M8:
    if (signedSample)
      st = new TSoundTrackMono8Signed(sampleRate, channelCount, sampleCount,
                                      (TMono8SignedSample *)buffer, 0);
    else
      st = new TSoundTrackMono8Unsigned(sampleRate, channelCount, sampleCount,
                                        (TMono8UnsignedSample *)buffer, 0);
    break;
  case TRK_S8:
    if (signedSample)
      st = new TSoundTrackStereo8Signed(sampleRate, channelCount, sampleCount,
                                        (TStereo8SignedSample *)buffer, 0);
    else
      st = new TSoundTrackStereo8Unsigned(sampleRate, channelCount, sampleCount,
                                          (TStereo8UnsignedSample *)buffer, 0);
    break;
  case TRK_M16:
    st = new TSoundTrackMono16(sampleRate, channelCount, sampleCount,
                               (TMono16Sample *)buffer, 0);
    break;
  case TRK_S16:
    st = new TSoundTrackStereo16(sampleRate, channelCount, sampleCount,
                                 (TStereo16Sample *)buffer, 0);
    break;
  case TRK_M24:
    st = new TSoundTrackMono24(sampleRate, channelCount, sampleCount,
                               (TMono24Sample *)buffer, 0);
    break;
  case TRK_S24:
    st = new TSoundTrackStereo24(sampleRate, channelCount, sampleCount,
                                 (TStereo24Sample *)buffer, 0);
    break;
  default:
    std::string s;
    s = "Type " + std::to_string(sampleRate) + " Hz " +
        std::to_string(bitPerSample) + " bits ";
    if (channelCount == 1)
      s += "mono: ";
    else
      s += "stereo: ";
    s += "Unsupported\n";
    throw TException(s);
  }
  return st;
}
extract() [1/2]
TSoundTrackP TSoundTrack::extract (double t0, double t1)
Returns a subtrack for the range [t0, t1], t0 and t1 are seconds.
{
  return extract(secondsToSamples(t0), secondsToSamples(t1));
}
References extract(), and secondsToSamples().
extract() [2/2]
virtual TSoundTrackP TSoundTrack::extract (TINT32 s0, TINT32 s1) pure virtual
Returns a subtrack for the range [s0, s1], s0 and s1 are samples.
Implemented in TSoundTrackT< T >.
Referenced by extract(), TSoundOutputDevice::play(), and TSop::remove().
getBitPerSample()
int TSoundTrack::getBitPerSample () const inline
{ return m_bitPerSample; }
getChannelCount()
int TSoundTrack::getChannelCount () const inline
{ return m_channelCount; }
getDuration()
double TSoundTrack::getDuration () const
Returns the duration of the soundtrack in seconds.
{
  return samplesToSeconds(m_sampleCount);
}
References samplesToSeconds().
getFormat()
TSoundTrackFormat TSoundTrack::getFormat () const
Returns the soundtrack format.
{
  return TSoundTrackFormat(getSampleRate(), getBitPerSample(),
                           getChannelCount(), isSampleSigned());
}
References isSampleSigned().
Referenced by TSoundTrackT< T >::clone(), TSop::insertBlank(), TSoundOutputDevice::open(), TSoundOutputDevice::play(), TXshSoundColumn::play(), WavehdrQueue::put(), TSoundInputDevice::record(), and TSop::remove().
getMaxPressure() [1/3]
double TSoundTrack::getMaxPressure (double t0, double t1, TSound::Channel chan) const
Returns the soundtrack pressure min value in the given range and channel. Range in seconds
{
  return getMaxPressure(secondsToSamples(t0), secondsToSamples(t1), chan);
}
References getMaxPressure(), and secondsToSamples().
getMaxPressure() [2/3]
virtual double TSoundTrack::getMaxPressure (TINT32 s0, TINT32 s1, TSound::Channel chan) const pure virtual
Returns the soundtrack pressure max value in the given sample range and channel
Implemented in TSoundTrackT< T >.
Referenced by getMaxPressure().
getMaxPressure() [3/3]
double TSoundTrack::getMaxPressure (TSound::Channel chan) const
Returns the soundtrack pressure max value for the given channel.
{
  return getMaxPressure(0, (TINT32)(getSampleCount() - 1), chan);
}
References getMaxPressure().
getMinMaxPressure() [1/3]
void TSoundTrack::getMinMaxPressure (double t0, double t1, TSound::Channel chan, double & min, double & max) const
Returns the soundtrack pressure min and max values in the given range and channel. Range in seconds
{
  getMinMaxPressure(secondsToSamples(t0), secondsToSamples(t1), chan, min, max);
}
References getMinMaxPressure(), and secondsToSamples().
getMinMaxPressure() [2/3]
virtual void TSoundTrack::getMinMaxPressure (TINT32 s0, TINT32 s1, TSound::Channel chan, double & min, double & max) const pure virtual
Returns the soundtrack pressure max and min values in the given sample range and channel
Implemented in TSoundTrackT< T >.
Referenced by getMinMaxPressure().
getMinMaxPressure() [3/3]
void TSoundTrack::getMinMaxPressure (TSound::Channel chan, double & min, double & max) const
Returns the soundtrack pressure min and max values for the given channel.
{
  getMinMaxPressure(0, (TINT32)(getSampleCount() - 1), chan, min, max);
}
References getMinMaxPressure().
getMinPressure() [1/3]
double TSoundTrack::getMinPressure (double t0, double t1, TSound::Channel chan) const
Returns the soundtrack pressure mix value in the given sample range and channel Range in seconds
{
  return getMinPressure(secondsToSamples(t0), secondsToSamples(t1), chan);
}
References getMinPressure(), and secondsToSamples().
getMinPressure() [2/3]
virtual double TSoundTrack::getMinPressure (TINT32 s0, TINT32 s1, TSound::Channel chan) const pure virtual
Returns the soundtrack pressure max value in the given sample range and channel
Implemented in TSoundTrackT< T >.
Referenced by getMinPressure().
getMinPressure() [3/3]
double TSoundTrack::getMinPressure (TSound::Channel chan) const
Returns the soundtrack pressure min value for the given channel.
{
  return getMinPressure(0, (TINT32)(getSampleCount() - 1), chan);
}
References getMinPressure().
getPressure() [1/2]
double TSoundTrack::getPressure (double second, TSound::Channel chan) const
Returns the soundtrack pressure value for the given time and channel.
{
  return getPressure(secondsToSamples(second), chan);
}
References getPressure(), and secondsToSamples().
getPressure() [2/2]
virtual double TSoundTrack::getPressure (TINT32 sample, TSound::Channel chan) const pure virtual
Returns the soundtrack pressure value for the given sample and channel: range [-1,1]
Implemented in TSoundTrackT< T >.
Referenced by TSoundTrackT< T >::getMaxPressure(), TSoundTrackT< T >::getMinMaxPressure(), TSoundTrackT< T >::getMinPressure(), and getPressure().
getRawData()
const UCHAR * TSoundTrack::getRawData () const inline
Returns a pointer to the samples buffer.
{ return m_buffer; };
Referenced by create(), TSop::insertBlank(), TSoundTrackReaderAiff::load(), TSoundTrackReaderMp3::load(), TSoundTrackReaderRaw::load(), TSoundTrackReaderWav::load(), WavehdrQueue::put(), TSoundInputDevice::record(), TSop::remove(), TSoundTrackWriterAiff::save(), TSoundTrackWriterRaw::save(), TSoundTrackWriterWav::save(), and TSoundInputDevice::stop().
getSampleCount()
TINT32 TSoundTrack::getSampleCount () const inline
{ return m_sampleCount; }
getSampleRate()
TUINT32 TSoundTrack::getSampleRate () const inline
{ return m_sampleRate; }
getSampleSize()
int TSoundTrack::getSampleSize () const inline
{ return m_sampleSize; }
isSampleSigned()
virtual bool TSoundTrack::isSampleSigned () const pure virtual
Returns true if the samples of the soundtrack are signed, false otherwise.
Implemented in TSoundTrackT< T >.
Referenced by TSop::convert(), getFormat(), WavehdrQueue::put(), TSoundTrackWriterAiff::save(), and TSoundTrackWriterWav::save().
samplesToSeconds()
double TSoundTrack::samplesToSeconds (TINT32 smp) const
Converts from samples to seconds according to the soundtrack sample rate.
{
  return f / (double)m_sampleRate;
}
Referenced by getDuration().
secondsToSamples()
TINT32 TSoundTrack::secondsToSamples (double sec) const
Converts from seconds to samples according to the soundtrack sample rate.
{
  double dsamp = s * m_sampleRate;
  TINT32 lsamp = (TINT32)dsamp;
  if ((double)lsamp < dsamp - TConsts::epsilon) lsamp++;
  return lsamp;
}
Referenced by blank(), copy(), extract(), getMaxPressure(), getMinMaxPressure(), getMinPressure(), getPressure(), TSop::insertBlank(), TSoundOutputDevice::play(), and TSop::remove().
setSampleRate()
void TSoundTrack::setSampleRate (TUINT32 sampleRate) inline
{ m_sampleRate = sampleRate; }
Member Data Documentation
m_bitPerSample
int TSoundTrack::m_bitPerSample protected
m_buffer
UCHAR* TSoundTrack::m_buffer protected
m_bufferOwner
bool TSoundTrack::m_bufferOwner protected
m_channelCount
int TSoundTrack::m_channelCount protected
m_parent
TSoundTrack* TSoundTrack::m_parent protected
m_sampleCount
TINT32 TSoundTrack::m_sampleCount protected
m_sampleRate
TUINT32 TSoundTrack::m_sampleRate protected
m_sampleSize
int TSoundTrack::m_sampleSize protected
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/tsound.h
E:/opentoonz/toonz/sources/common/tsound/tsound.cpp