opentoonz: Stage::RasterPainter Class Reference
Stage::RasterPainter Class Reference final
#include <stagevisitor.h>
Public Member Functions
RasterPainter (const TDimension &dim, const TAffine &viewAff, const TRect &rect, const ImagePainter::VisualSettings &vs, bool checkFlags)
void onImage (const Stage::Player &data) override
void onVectorImage (TVectorImage *vi, const Stage::Player &data)
void onRasterImage (TRasterImage *ri, const Stage::Player &data) override
void onToonzImage (TToonzImage *ri, const Stage::Player &data)
void beginMask () override
Utilizzato solo per TAB Pro.
void endMask () override
Utilizzato solo per TAB Pro.
void enableMask () override
Utilizzato solo per TAB Pro.
void disableMask () override
Utilizzato solo per TAB Pro.
int getNodesCount ()
void clearNodes ()
TRasterP getRaster (int index, QMatrix &matrix)
void flushRasterImages ()
void drawRasterImages (QPainter &p, QPolygon cameraRect)
void enableSingleColumn (bool on)
bool isSingleColumnEnabled () const
void setRasterDarkenBlendedView (bool on)
std::vector< TStroke * > & getGuidedStrokes ()
Public Member Functions inherited from Stage::Visitor
Visitor (const ImagePainter::VisualSettings &vs)
virtual void onImage (const Player &player)=0
The visitation function.
virtual void onRasterImage (TRasterImage *ri, const Stage::Player &data)=0
virtual void enableMask ()=0
virtual void disableMask ()=0
virtual void beginMask ()=0
virtual void endMask ()=0
Additional Inherited Members
Public Attributes inherited from Stage::Visitor
const ImagePainter::VisualSettings & m_vs
Generic painting visual options.
Detailed Description
Stage::RasterPainter is the object responsible for drawing scene contents on a standard Toonz SceneViewer panel.
This class performs standard camera-stand <\I> scene renderization. It renders every supported Toonz image type (including Plastic's texturized mesh-based image deformation), deals with onion-skin, and other stuff.
Warning
The RasterPainter visitor expects an active OpenGL context.
Constructor & Destructor Documentation
RasterPainter()
RasterPainter::RasterPainter (const TDimension & dim, const TAffine & viewAff, const TRect & rect, const ImagePainter::VisualSettings & vs, bool checkFlags)
    : Visitor(vs)
    , m_dim(dim)
    , m_viewAff(viewAff)
    , m_clipRect(rect)
    , m_maskLevel(0)
    , m_singleColumnEnabled(false)
    , m_checkFlags(checkFlags)
    , m_doRasterDarkenBlendedView(false) {}
Member Function Documentation
beginMask()
void RasterPainter::beginMask () override virtual
Utilizzato solo per TAB Pro.
Implements Stage::Visitor.
{
  flushRasterImages();  // per evitare che venga fatto dopo il beginMask
  ++m_maskLevel;
  TStencilControl::instance()->beginMask();
}
clearNodes()
void RasterPainter::clearNodes ()
{ m_nodes.clear(); }
disableMask()
void RasterPainter::disableMask () override virtual
Utilizzato solo per TAB Pro.
Implements Stage::Visitor.
{
  flushRasterImages();  // se ci sono delle immagini raster mascherate devono
                        // uscire ora
  TStencilControl::instance()->disableMask();
}
drawRasterImages()
void RasterPainter::drawRasterImages (QPainter & p, QPolygon cameraPol)
Make frame visualization in QPainter.
Draw in painter mode just raster image in m_nodes.
Onon-skin or channel mode are not considered.
{
  if (m_nodes.empty()) return;
  double delta = sqrt(fabs(m_nodes[0].m_aff.det()));
  TRectD bbox  = m_nodes[0].m_bbox.enlarge(delta);
  int i;
  for (i = 1; i < (int)m_nodes.size(); i++) {
    delta = sqrt(fabs(m_nodes[i].m_aff.det()));
    bbox += m_nodes[i].m_bbox.enlarge(delta);
  }
  TRect rect(tfloor(bbox.x0), tfloor(bbox.y0), tceil(bbox.x1), tceil(bbox.y1));
  rect = rect * TRect(0, 0, m_dim.lx - 1, m_dim.ly - 1);
  TRect r = rect - rect.getP00();
  TAffine flipY(1, 0, 0, 0, -1, m_dim.ly);
  p.setClipRegion(QRegion(cameraPol));
  for (i = 0; i < (int)m_nodes.size(); i++) {
    if (m_nodes[i].m_onionMode != Node::eOnionSkinNone) continue;
    p.resetTransform();
    TRasterP ras = m_nodes[i].m_raster;
    TAffine aff  = TTranslation(-rect.x0, -rect.y0) * flipY * m_nodes[i].m_aff;
    QMatrix matrix(aff.a11, aff.a21, aff.a12, aff.a22, aff.a13, aff.a23);
    QImage image = rasterToQImage(ras);
    if (image.isNull()) continue;
    p.setMatrix(matrix);
    p.drawImage(rect.getP00().x, rect.getP00().y, image);
  }
  p.resetTransform();
  m_nodes.clear();
}
References TRectT< T >::x0.
enableMask()
void RasterPainter::enableMask () override virtual
Utilizzato solo per TAB Pro.
Implements Stage::Visitor.
{
  TStencilControl::instance()->enableMask(TStencilControl::SHOW_INSIDE);
}
enableSingleColumn()
void Stage::RasterPainter::enableSingleColumn (bool on) inline
{ m_singleColumnEnabled = on; }
endMask()
void RasterPainter::endMask () override virtual
Utilizzato solo per TAB Pro.
Implements Stage::Visitor.
{
  flushRasterImages();  // se ci sono delle immagini raster nella maschera
                        // devono uscire ora
  --m_maskLevel;
  TStencilControl::instance()->endMask();
}
flushRasterImages()
void RasterPainter::flushRasterImages ()
{
  if (m_nodes.empty()) return;
  // Build nodes bbox union
  double delta = sqrt(fabs(m_nodes[0].m_aff.det()));
  TRectD bbox  = m_nodes[0].m_bbox.enlarge(delta);
  int i, nodesCount = m_nodes.size();
  for (i = 1; i < nodesCount; ++i) {
    delta = sqrt(fabs(m_nodes[i].m_aff.det()));
    bbox += m_nodes[i].m_bbox.enlarge(delta);
  }
  TRect rect(tfloor(bbox.x0), tfloor(bbox.y0), tceil(bbox.x1), tceil(bbox.y1));
  rect = rect * TRect(0, 0, m_dim.lx - 1, m_dim.ly - 1);
  int lx = rect.getLx(), ly = rect.getLy();
  TDimension dim(lx, ly);
  // this is needed since a stop motion live view
  // doesn't register as a node correctly
  // there is probably a better way to do this.
  if (rect.getLx() == 0 && lx == 0) {
    rect = m_clipRect;
    dim  = m_dim;
  }
  // Build a raster buffer of sufficient size to hold said union.
  // The buffer is per-thread cached in order to improve the rendering speed.
  if (!threadBuffers.hasLocalData())
    threadBuffers.setLocalData(new std::vector<char>());
  int size = dim.lx * dim.ly * sizeof(TPixel32);
  std::vector<char> *vbuff = (std::vector<char> *)threadBuffers.localData();
  if (size > (int)vbuff->size()) vbuff->resize(size);
  TRaster32P ras(dim.lx, dim.ly, dim.lx, (TPixel32 *)&(*vbuff)[0]);
  TRaster32P ras2;
  if (m_vs.m_colorMask != 0) {
    ras2 = TRaster32P(ras->getSize());
    ras->clear();
  } else
    ras2 = ras;
  // Clear the buffer - it will hold all the stacked nodes content to be overed
  // on top of the OpenGL buffer through a glDrawPixel()
  ras->lock();
  ras->clear();  // ras is typically reused - and we need it transparent first
  TRect r                 = rect - rect.getP00();
  TRaster32P viewedRaster = ras->extract(r);
  int current = -1;
  // Retrieve preferences-related data
  int tc    = m_checkFlags ? ToonzCheck::instance()->getChecks() : 0;
  int index = ToonzCheck::instance()->getColorIndex();
  TPixel32 frontOnionColor, backOnionColor;
  bool onionInksOnly;
  Preferences::instance()->getOnionData(frontOnionColor, backOnionColor,
                                        onionInksOnly);
  // Stack every node on top of the raster buffer
  for (i = 0; i < nodesCount; ++i) {
    if (m_nodes[i].m_isCurrentColumn) current = i;
    TAffine aff         = TTranslation(-rect.x0, -rect.y0) * m_nodes[i].m_aff;
    TDimension imageDim = m_nodes[i].m_raster->getSize();
    TPointD offset(0.5, 0.5);
    aff *= TTranslation(offset);  // very quick and very dirty fix: in
                                  // camerastand the images seems shifted of an
                                  // half pixel...it's a quickput approximation?
    TPixel32 colorscale = TPixel32(0, 0, 0, m_nodes[i].m_alpha);
    int inksOnly;
    if (m_nodes[i].m_onionMode != Node::eOnionSkinNone) {
      inksOnly = onionInksOnly;
      if (m_nodes[i].m_onionMode == Node::eOnionSkinFront)
        colorscale = TPixel32(frontOnionColor.r, frontOnionColor.g,
                              frontOnionColor.b, m_nodes[i].m_alpha);
      else if (m_nodes[i].m_onionMode == Node::eOnionSkinBack)
        colorscale = TPixel32(backOnionColor.r, backOnionColor.g,
                              backOnionColor.b, m_nodes[i].m_alpha);
    } else {
      if (m_nodes[i].m_filterColor != TPixel32::Black) {
        colorscale   = m_nodes[i].m_filterColor;
        colorscale.m = m_nodes[i].m_alpha;
      }
      inksOnly = tc & ToonzCheck::eInksOnly;
    }
    if (TRaster32P src32 = m_nodes[i].m_raster)
      TRop::quickPut(viewedRaster, src32, aff, colorscale,
                     m_nodes[i].m_doPremultiply, m_nodes[i].m_whiteTransp,
                     m_nodes[i].m_isFirstColumn, m_doRasterDarkenBlendedView);
    else if (TRasterGR8P srcGr8 = m_nodes[i].m_raster)
      TRop::quickPut(viewedRaster, srcGr8, aff, colorscale);
    else if (TRasterCM32P srcCm = m_nodes[i].m_raster) {
      assert(m_nodes[i].m_palette);
      int oldframe = m_nodes[i].m_palette->getFrame();
      m_nodes[i].m_palette->setFrame(m_nodes[i].m_frame);
      TPaletteP plt;
      int styleIndex = -1;
      if ((tc & ToonzCheck::eGap || tc & ToonzCheck::eAutoclose) &&
          m_nodes[i].m_isCurrentColumn) {
        srcCm      = srcCm->clone();
        plt        = m_nodes[i].m_palette->clone();
        styleIndex = plt->addStyle(TPixel::Magenta);
        if (tc & ToonzCheck::eAutoclose)
          TAutocloser(srcCm, AutocloseDistance, AutocloseAngle, styleIndex,
                      AutocloseOpacity)
              .exec();
        if (tc & ToonzCheck::eGap)
          AreaFiller(srcCm).rectFill(m_nodes[i].m_savebox, 1, true, true,
                                     false);
      } else
        plt = m_nodes[i].m_palette;
      if (tc == 0 || tc == ToonzCheck::eBlackBg ||
          !m_nodes[i].m_isCurrentColumn)
        TRop::quickPut(viewedRaster, srcCm, plt, aff, colorscale, inksOnly);
      else {
        TRop::CmappedQuickputSettings settings;
        settings.m_globalColorScale = colorscale;
        settings.m_inksOnly         = inksOnly;
        settings.m_transparencyCheck =
            tc & (ToonzCheck::eTransparency | ToonzCheck::eGap);
        settings.m_blackBgCheck = tc & ToonzCheck::eBlackBg;
        /*-- InkCheck, Ink#1Check, PaintCheck --*/
        settings.m_inkIndex =
            m_nodes[i].m_isCurrentColumn
                ? (tc & ToonzCheck::eInk ? index
                                         : (tc & ToonzCheck::eInk1 ? 1 : -1))
                : -1;
        settings.m_paintIndex = m_nodes[i].m_isCurrentColumn
                                    ? (tc & ToonzCheck::ePaint ? index : -1)
                                    : -1;
        Preferences::instance()->getTranspCheckData(
            settings.m_transpCheckBg, settings.m_transpCheckInk,
            settings.m_transpCheckPaint);
        settings.m_isOnionSkin = m_nodes[i].m_onionMode != Node::eOnionSkinNone;
        settings.m_gapCheckIndex = styleIndex;
        TRop::quickPut(viewedRaster, srcCm, plt, aff, settings);
      }
      srcCm = TRasterCM32P();
      plt   = TPaletteP();
      m_nodes[i].m_palette->setFrame(oldframe);
    } else
      assert(!"Cannot use quickput with this raster combination!");
  }
  if (m_vs.m_colorMask != 0) {
    TRop::setChannel(ras, ras, m_vs.m_colorMask, false);
    TRop::quickPut(ras2, ras, TAffine());
  }
  // Now, output the raster buffer on top of the OpenGL buffer
  glPushAttrib(GL_COLOR_BUFFER_BIT);  // Preserve blending and stuff
  glEnable(GL_BLEND);
  glBlendFunc(GL_ONE,
              GL_ONE_MINUS_SRC_ALPHA);  // The raster buffer is intended in
  // premultiplied form - thus the GL_ONE on src
  glDisable(GL_DEPTH_TEST);
  glDisable(GL_DITHER);
  glDisable(GL_LOGIC_OP);
/* disable, since these features are never enabled, and cause OpenGL to assert
 * on systems that don't support them: see #591 */
#if 0
#ifdef GL_EXT_convolution
  if( GLEW_EXT_convolution ) {
    glDisable(GL_CONVOLUTION_1D_EXT);
    glDisable(GL_CONVOLUTION_2D_EXT);
    glDisable(GL_SEPARABLE_2D_EXT);
  }
#endif
#ifdef GL_EXT_histogram
  if( GLEW_EXT_histogram ) {
    glDisable(GL_HISTOGRAM_EXT);
    glDisable(GL_MINMAX_EXT);
  }
#endif
#endif
#ifdef GL_EXT_texture3D
  if (GL_EXT_texture3D) {
    glDisable(GL_TEXTURE_3D_EXT);
  }
#endif
  glPushMatrix();
  glLoadIdentity();
  glRasterPos2d(rect.x0, rect.y0);
  glPixelStorei(GL_UNPACK_ROW_LENGTH, 0);
  glPixelStorei(GL_UNPACK_ALIGNMENT, 1);
  glDrawPixels(ras2->getLx(), ras2->getLy(),            // Perform the over
               TGL_FMT, TGL_TYPE, ras2->getRawData());  //
  ras->unlock();
  glPopMatrix();
  glPopAttrib();  // Restore blending status
  if (m_vs.m_showBBox && current > -1) {
    glPushMatrix();
    glLoadIdentity();
    tglColor(TPixel(200, 200, 200));
    tglMultMatrix(m_nodes[current].m_aff);
    tglDrawRect(m_nodes[current].m_raster->getBounds());
    glPopMatrix();
  }
  m_nodes.clear();
}
getGuidedStrokes()
std::vector< TStroke * > & Stage::RasterPainter::getGuidedStrokes () inline
{ return m_guidedStrokes; }
getNodesCount()
int RasterPainter::getNodesCount ()
{ return m_nodes.size(); }
getRaster()
TRasterP RasterPainter::getRaster (int index, QMatrix & matrix)
{
  if ((int)m_nodes.size() <= index) return TRasterP();
  if (m_nodes[index].m_onionMode != Node::eOnionSkinNone) return TRasterP();
  if (m_nodes.empty()) return TRasterP();
  double delta = sqrt(fabs(m_nodes[0].m_aff.det()));
  TRectD bbox  = m_nodes[0].m_bbox.enlarge(delta);
  int i;
  for (i = 1; i < (int)m_nodes.size(); i++) {
    delta = sqrt(fabs(m_nodes[i].m_aff.det()));
    bbox += m_nodes[i].m_bbox.enlarge(delta);
  }
  TRect rect(tfloor(bbox.x0), tfloor(bbox.y0), tceil(bbox.x1), tceil(bbox.y1));
  rect = rect * TRect(0, 0, m_dim.lx - 1, m_dim.ly - 1);
  TAffine aff = TTranslation(-rect.x0, -rect.y0) * m_nodes[index].m_aff;
  matrix      = QMatrix(aff.a11, aff.a21, aff.a12, aff.a22, aff.a13, aff.a23);
  return m_nodes[index].m_raster;
}
isSingleColumnEnabled()
bool Stage::RasterPainter::isSingleColumnEnabled () const inline
{ return m_singleColumnEnabled; }
onImage()
void RasterPainter::onImage (const Stage::Player & player) override virtual
Take image from Stage::Player data and recall the right method for this kind of image, for vector image recall onVectorImage(), for raster image recall onRasterImage() for toonz image recall onToonzImage().
Implements Stage::Visitor.
{
  if (m_singleColumnEnabled && !player.m_isCurrentColumn) return;
  // Attempt Plastic-deformed drawing
  // For now generating icons of plastic-deformed image causes crash as
  // QOffscreenSurface is created outside the gui thread.
  // As a quick workaround, ignore the deformation if this is called from
  // non-gui thread (i.e. icon generator thread)
  // 12/1/2018 Now the scene icon is rendered without deformation either
  // since it causes unknown error with opengl contexts..
  TStageObject *obj =
      ::plasticDeformedObj(player, m_vs.m_plasticVisualSettings);
  if (obj && QThread::currentThread() == qGuiApp->thread() &&
      !m_vs.m_forSceneIcon) {
    flushRasterImages();
    ::onPlasticDeformedImage(obj, player, m_vs, m_viewAff);
  } else {
    // Common image draw
    const TImageP &img = player.image();
    if (TVectorImageP vi = img)
      onVectorImage(vi.getPointer(), player);
    else if (TRasterImageP ri = img)
      onRasterImage(ri.getPointer(), player);
    else if (TToonzImageP ti = img)
      onToonzImage(ti.getPointer(), player);
    else if (TMeshImageP mi = img) {
      flushRasterImages();
      ::onMeshImage(mi.getPointer(), player, m_vs, m_viewAff);
    }
  }
}
References Stage::Player::image(), Stage::Player::m_isCurrentColumn, ImagePainter::VisualSettings::m_plasticVisualSettings, Stage::Visitor::m_vs, onRasterImage(), onToonzImage(), and onVectorImage().
onRasterImage()
void RasterPainter::onRasterImage (TRasterImage * ri, const Stage::Player & player) override virtual
Create a Node and put it in m_nodes.
Implements Stage::Visitor.
{
  TRasterP r = ri->getRaster();
  TAffine aff;
  aff = m_viewAff * player.m_placement * player.m_dpiAff;
  aff = TTranslation(m_dim.lx * 0.5, m_dim.ly * 0.5) * aff *
        TTranslation(-r->getCenterD() +
                     convert(ri->getOffset()));  // this offset is !=0 only if
                                                 // in cleanup camera test mode
  TRectD bbox = TRectD(0, 0, m_dim.lx, m_dim.ly);
  bbox *= convert(m_clipRect);
  if (bbox.isEmpty()) return;
  int alpha                 = 255;
  Node::OnionMode onionMode = Node::eOnionSkinNone;
  if (player.m_onionSkinDistance != c_noOnionSkin) {
    // GetOnionSkinFade va bene per il vettoriale mentre il raster funziona al
    // contrario
    // 1 opaco -> 0 completamente trasparente
    // inverto quindi il risultato della funzione stando attento al caso 0
    // (in cui era scolpito il valore 0.9)
    double onionSkiFade = player.m_onionSkinDistance == 0
                              ? 0.9
                              : (1.0 - OnionSkinMask::getOnionSkinFade(
                                           player.m_onionSkinDistance));
    alpha = tcrop(tround(onionSkiFade * 255.0), 0, 255);
    if (player.m_isShiftAndTraceEnabled &&
        !Preferences::instance()->areOnionColorsUsedForShiftAndTraceGhosts())
      onionMode = Node::eOnionSkinNone;
    else {
      onionMode =
          (player.m_onionSkinDistance > 0)
              ? Node::eOnionSkinFront
              : ((player.m_onionSkinDistance < 0) ? Node::eOnionSkinBack
                                                  : Node::eOnionSkinNone);
    }
  } else if (player.m_opacity < 255)
    alpha = player.m_opacity;
  TXshSimpleLevel *sl = player.m_sl;
  bool doPremultiply  = false;
  bool whiteTransp    = false;
  if (sl) {
    LevelProperties *levelProp = sl->getProperties();
    if (levelProp->doPremultiply())
      doPremultiply = true;
    else if (levelProp->whiteTransp())
      whiteTransp = true;
  }
  bool ignoreAlpha =
      (Preferences::instance()->isIgnoreAlphaonColumn1Enabled() &&
       player.m_column == 0 &&
       isSubsheetChainOnColumn0(sl->getScene()->getTopXsheet(), player.m_xsh,
                                player.m_frame));
  m_nodes.push_back(Node(r, 0, alpha, aff, ri->getSavebox(), bbox,
                         player.m_frame, player.m_isCurrentColumn, onionMode,
                         doPremultiply, whiteTransp, ignoreAlpha,
                         player.m_filterColor));
}
References LevelProperties::doPremultiply(), TRasterImage::getOffset(), OnionSkinMask::getOnionSkinFade(), TXshSimpleLevel::getProperties(), TRasterImage::getRaster(), TRasterImage::getSavebox(), TXshLevel::getScene(), ToonzScene::getTopXsheet(), TRectT< T >::isEmpty(), Stage::Player::m_column, Stage::Player::m_dpiAff, Stage::Player::m_frame, Stage::Player::m_isCurrentColumn, Stage::Player::m_onionSkinDistance, Stage::Player::m_opacity, Stage::Player::m_placement, Stage::Player::m_sl, and Stage::Player::m_xsh.
Referenced by onImage().
onToonzImage()
void RasterPainter::onToonzImage (TToonzImage * ti, const Stage::Player & player)
Create a Node and put it in m_nodes.
{
  TRasterCM32P r = ti->getRaster();
  if (!ti->getPalette()) return;
  TAffine aff = m_viewAff * player.m_placement * player.m_dpiAff;
  aff         = TTranslation(m_dim.lx / 2.0, m_dim.ly / 2.0) * aff *
        TTranslation(-r->getCenterD());
  TRectD bbox = TRectD(0, 0, m_dim.lx, m_dim.ly);
  bbox *= convert(m_clipRect);
  if (bbox.isEmpty()) return;
  int alpha                 = 255;
  Node::OnionMode onionMode = Node::eOnionSkinNone;
  if (player.m_onionSkinDistance != c_noOnionSkin) {
    // GetOnionSkinFade is good for the vector while the raster works at the
    //    Opposite 1 opaque -> 0 completely transparent
    //    I therefore reverse the result of the function by being attentive to
    //    case 0
    //    (where the value 0.9 was carved)
    double onionSkiFade = player.m_onionSkinDistance == 0
                              ? 0.9
                              : (1.0 - OnionSkinMask::getOnionSkinFade(
                                           player.m_onionSkinDistance));
    alpha = tcrop(tround(onionSkiFade * 255.0), 0, 255);
    if (player.m_isShiftAndTraceEnabled &&
        !Preferences::instance()->areOnionColorsUsedForShiftAndTraceGhosts())
      onionMode = Node::eOnionSkinNone;
    else {
      onionMode =
          (player.m_onionSkinDistance > 0)
              ? Node::eOnionSkinFront
              : ((player.m_onionSkinDistance < 0) ? Node::eOnionSkinBack
                                                  : Node::eOnionSkinNone);
    }
  } else if (player.m_opacity < 255)
    alpha = player.m_opacity;
  m_nodes.push_back(Node(r, ti->getPalette(), alpha, aff, ti->getSavebox(),
                         bbox, player.m_frame, player.m_isCurrentColumn,
                         onionMode, false, false, false, player.m_filterColor));
}
References OnionSkinMask::getOnionSkinFade(), TToonzImage::getRaster(), TToonzImage::getSavebox(), TRectT< T >::isEmpty(), Stage::Player::m_dpiAff, Stage::Player::m_frame, Stage::Player::m_isCurrentColumn, Stage::Player::m_onionSkinDistance, Stage::Player::m_opacity, and Stage::Player::m_placement.
Referenced by onImage().
onVectorImage()
void RasterPainter::onVectorImage (TVectorImage * vi, const Stage::Player & player)
View a vector cell images.
If onion-skin is active compute TOnionFader value. Create and boot a TVectorRenderData and recall tglDraw().
{
  flushRasterImages();
  // When loaded, vectorimages needs to have regions recomputed, but doing that
  // while loading them
  // is quite slow (think about loading whole scenes!..). They are recomputed
  // the first time they
  // are selected and shown on screen...except when playing back, to avoid
  // slowness!
  // (Daniele) This function should *NOT* be responsible of that.
  //           It's the *image itself* that should recalculate or initialize
  //           said data
  //           if queried about it and turns out it's not available...
  if (!player.m_isPlaying && player.m_isCurrentColumn)
    vi->recomputeRegionsIfNeeded();
  const Preferences &prefs = *Preferences::instance();
  TColorFunction *cf = 0, *guidedCf = 0;
  TPalette *vPalette = vi->getPalette();
  TPixel32 bgColor   = TPixel32::White;
  int tc = (m_checkFlags && player.m_isCurrentColumn)
               ? ToonzCheck::instance()->getChecks()
               : 0;
  bool inksOnly = tc & ToonzCheck::eInksOnly;
  int oldFrame = vPalette->getFrame();
  vPalette->setFrame(player.m_frame);
  if (player.m_onionSkinDistance != c_noOnionSkin) {
    TPixel32 frontOnionColor, backOnionColor;
    if (player.m_onionSkinDistance != 0 &&
        (!player.m_isShiftAndTraceEnabled ||
         Preferences::instance()->areOnionColorsUsedForShiftAndTraceGhosts())) {
      prefs.getOnionData(frontOnionColor, backOnionColor, inksOnly);
      bgColor =
          (player.m_onionSkinDistance < 0) ? backOnionColor : frontOnionColor;
    }
    double m[4] = {1.0, 1.0, 1.0, 1.0}, c[4];
    // Weighted addition to RGB and matte multiplication
    m[3] = 1.0 -
           ((player.m_onionSkinDistance == 0)
                ? 0.1
                : OnionSkinMask::getOnionSkinFade(player.m_onionSkinDistance));
    c[0] = (1.0 - m[3]) * bgColor.r, c[1] = (1.0 - m[3]) * bgColor.g,
    c[2] = (1.0 - m[3]) * bgColor.b;
    c[3] = 0.0;
    cf = new TGenericColorFunction(m, c);
  } else if (player.m_filterColor != TPixel::Black) {
    TPixel32 colorScale = player.m_filterColor;
    colorScale.m        = player.m_opacity;
    cf                  = new TColumnColorFilterFunction(colorScale);
  } else if (player.m_opacity < 255)
    cf = new TTranspFader(player.m_opacity / 255.0);
  TVectorRenderData rd(m_viewAff * player.m_placement, TRect(), vPalette, cf,
                       true  // alpha enabled
  );
  rd.m_drawRegions           = !inksOnly;
  rd.m_inkCheckEnabled       = tc & ToonzCheck::eInk;
  rd.m_ink1CheckEnabled      = tc & ToonzCheck::eInk1;
  rd.m_paintCheckEnabled     = tc & ToonzCheck::ePaint;
  rd.m_blackBgEnabled        = tc & ToonzCheck::eBlackBg;
  rd.m_colorCheckIndex       = ToonzCheck::instance()->getColorIndex();
  rd.m_show0ThickStrokes     = prefs.getShow0ThickLines();
  rd.m_regionAntialias       = prefs.getRegionAntialias();
  rd.m_animatedGuidedDrawing = prefs.getAnimatedGuidedDrawing();
  if (player.m_onionSkinDistance != 0 &&
      (player.m_isCurrentColumn || player.m_isCurrentXsheetLevel)) {
    if (player.m_isGuidedDrawingEnabled == 3         // show guides on all
        || (player.m_isGuidedDrawingEnabled == 1 &&  // show guides on closest
            (player.m_onionSkinDistance == player.m_firstBackOnionSkin ||
             player.m_onionSkinDistance == player.m_firstFrontOnionSkin)) ||
        (player.m_isGuidedDrawingEnabled == 2 &&  // show guides on farthest
         (player.m_onionSkinDistance == player.m_onionSkinBackSize ||
          player.m_onionSkinDistance == player.m_onionSkinFrontSize)) ||
        (player.m_isEditingLevel &&  // fix for level editing mode sending extra
                                     // players
         player.m_isGuidedDrawingEnabled == 2 &&
         player.m_onionSkinDistance == player.m_lastBackVisibleSkin)) {
      rd.m_showGuidedDrawing = player.m_isGuidedDrawingEnabled > 0;
      int currentStrokeCount = 0;
      int totalStrokes       = vi->getStrokeCount();
      TXshSimpleLevel *sl    = player.m_sl;
      if (sl) {
        TImageP image          = sl->getFrame(player.m_currentFrameId, false);
        TVectorImageP vecImage = image;
        if (vecImage) currentStrokeCount = vecImage->getStrokeCount();
        if (currentStrokeCount < 0) currentStrokeCount = 0;
        if (player.m_guidedFrontStroke != -1 &&
            (player.m_onionSkinDistance == player.m_onionSkinFrontSize ||
             player.m_onionSkinDistance == player.m_firstFrontOnionSkin))
          rd.m_indexToHighlight = player.m_guidedFrontStroke;
        else if (player.m_guidedBackStroke != -1 &&
                 (player.m_onionSkinDistance == player.m_onionSkinBackSize ||
                  player.m_onionSkinDistance == player.m_firstBackOnionSkin))
          rd.m_indexToHighlight = player.m_guidedBackStroke;
        else if (currentStrokeCount < totalStrokes)
          rd.m_indexToHighlight = currentStrokeCount;
        double guidedM[4] = {1.0, 1.0, 1.0, 1.0}, guidedC[4];
        TPixel32 bgColor  = TPixel32::Blue;
        guidedM[3] =
            1.0 -
            ((player.m_onionSkinDistance == 0)
                 ? 0.1
                 : OnionSkinMask::getOnionSkinFade(player.m_onionSkinDistance));
        guidedC[0] = (1.0 - guidedM[3]) * bgColor.r,
        guidedC[1] = (1.0 - guidedM[3]) * bgColor.g,
        guidedC[2] = (1.0 - guidedM[3]) * bgColor.b;
        guidedC[3] = 0.0;
        guidedCf      = new TGenericColorFunction(guidedM, guidedC);
        rd.m_guidedCf = guidedCf;
      }
    }
  }
  if (tc & (ToonzCheck::eTransparency | ToonzCheck::eGap)) {
    TPixel dummy;
    rd.m_tcheckEnabled = true;
    if (rd.m_blackBgEnabled)
      prefs.getTranspCheckData(rd.m_tCheckInk, dummy, rd.m_tCheckPaint);
    else
      prefs.getTranspCheckData(dummy, rd.m_tCheckInk, rd.m_tCheckPaint);
  }
  if (m_vs.m_colorMask != 0) {
    glColorMask((m_vs.m_colorMask & TRop::RChan) ? GL_TRUE : GL_FALSE,
                (m_vs.m_colorMask & TRop::GChan) ? GL_TRUE : GL_FALSE,
                (m_vs.m_colorMask & TRop::BChan) ? GL_TRUE : GL_FALSE, GL_TRUE);
  }
  TVectorImageP viDelete;
  if (tc & ToonzCheck::eGap) {
    viDelete = vi->clone();
    vi       = viDelete.getPointer();
    vi->selectFill(vi->getBBox(), 0, 1, true, true, false);
  }
  TStroke *guidedStroke = 0;
  if (m_maskLevel > 0)
    tglDrawMask(rd, vi);
  else
    tglDraw(rd, vi, &guidedStroke);
  if (tc & ToonzCheck::eAutoclose) drawAutocloses(vi, rd);
  glColorMask(GL_TRUE, GL_TRUE, GL_TRUE, GL_TRUE);
  vPalette->setFrame(oldFrame);
  delete cf;
  delete guidedCf;
  if (guidedStroke) m_guidedStrokes.push_back(guidedStroke);
}
References TVectorImage::clone(), ToonzCheck::eAutoclose, ToonzCheck::eBlackBg, ToonzCheck::eGap, ToonzCheck::eInk, ToonzCheck::eInk1, ToonzCheck::eInksOnly, ToonzCheck::ePaint, ToonzCheck::eTransparency, TVectorImage::getBBox(), ToonzCheck::getColorIndex(), TPalette::getFrame(), OnionSkinMask::getOnionSkinFade(), TVectorImage::getStrokeCount(), TVectorRenderData::m_blackBgEnabled, TVectorRenderData::m_colorCheckIndex, ImagePainter::VisualSettings::m_colorMask, TVectorRenderData::m_drawRegions, Stage::Player::m_frame, TVectorRenderData::m_ink1CheckEnabled, TVectorRenderData::m_inkCheckEnabled, Stage::Player::m_isCurrentColumn, Stage::Player::m_isCurrentXsheetLevel, Stage::Player::m_isPlaying, Stage::Player::m_onionSkinDistance, Stage::Player::m_opacity, TVectorRenderData::m_paintCheckEnabled, Stage::Player::m_placement, TVectorRenderData::m_regionAntialias, TVectorRenderData::m_show0ThickStrokes, Stage::Player::m_sl, TVectorRenderData::m_tcheckEnabled, TVectorRenderData::m_tCheckInk, TVectorRenderData::m_tCheckPaint, Stage::Visitor::m_vs, TVectorImage::recomputeRegionsIfNeeded(), TVectorImage::selectFill(), and TPalette::setFrame().
Referenced by onImage().
setRasterDarkenBlendedView()
void Stage::RasterPainter::setRasterDarkenBlendedView (bool on) inline
{ m_doRasterDarkenBlendedView = on; }
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/toonz/stagevisitor.h
E:/opentoonz/toonz/sources/toonzlib/stagevisitor.cpp