opentoonz: TExpression Class Reference
TExpression Class Reference
This class manages a generic expression.
#include <texpression.h>
Classes
class Imp
Public Member Functions
TExpression (const TExpression &)
TExpression & operator= (TExpression)
void setGrammar (const TSyntax::Grammar *grammar)
Sets the expression's grammar - does not acquire ownership.
const TSyntax::Grammar * getGrammar () const
void setText (std::string text)
std::string getText () const
TSyntax::Calculator * getCalculator ()
bool isValid ()
std::string getError () const
std::pair< int, int > getErrorPos () const
void accept (TSyntax::CalculatorNodeVisitor &visitor)
void setOwnerParameter (TDoubleParam *param)
TDoubleParam * getOwnerParameter () const
bool isCycling () const
Detailed Description
This class manages a generic expression.
An expression is a sequence of characthers and contains:
a CalcNode that is a basic element of the expression that must be evaluated;
a Grammar that is a sequence of string patterns that define operations on nodes;
a Builder that is a sequence or a tree of calcnodes and operations on that;
Constructor & Destructor Documentation
TExpression() [1/2]
TExpression::TExpression ()
: m_imp(new Imp()) {}
~TExpression()
TExpression::~TExpression ()
{}
TExpression() [2/2]
TExpression::TExpression (const TExpression & src)
                                               : m_imp(new Imp()) {
  m_imp->m_grammar       = src.m_imp->m_grammar;
  m_imp->m_param         = src.m_imp->m_param;
  m_imp->m_text          = src.m_imp->m_text;
  m_imp->m_calculator    = 0;
  m_imp->m_isValid       = src.m_imp->m_isValid;
  m_imp->m_error         = src.m_imp->m_error;
  m_imp->m_errorPos      = src.m_imp->m_errorPos;
  m_imp->m_hasBeenParsed = false;
  m_imp->m_hasReference  = src.m_imp->m_hasReference;
}
Member Function Documentation
accept()
void TExpression::accept (TSyntax::CalculatorNodeVisitor & visitor)
{
  if (!m_imp->m_hasBeenParsed) parse();
  if (m_imp->m_isValid && m_imp->m_calculator)
    m_imp->m_calculator->accept(visitor);
}
getCalculator()
TSyntax::Calculator * TExpression::getCalculator ()
{
  if (!m_imp->m_hasBeenParsed) parse();
  if (m_imp->m_isValid && m_imp->m_calculator)
    return m_imp->m_calculator;
  else
    return 0;
}
getError()
std::string TExpression::getError () const
{ return m_imp->m_error; }
getErrorPos()
std::pair< int, int > TExpression::getErrorPos () const
{
  return m_imp->m_errorPos;
}
getGrammar()
const TSyntax::Grammar * TExpression::getGrammar () const
{
  return m_imp->m_grammar;
}
getOwnerParameter()
TDoubleParam * TExpression::getOwnerParameter () const
{ return m_imp->m_param; }
getText()
std::string TExpression::getText () const
{ return m_imp->m_text; }
isCycling()
bool TExpression::isCycling () const
{
  // TODO: this is a quick&dirty implementation to be replaced with a more
  // "semantic" one
  return getText().find("cycle") != std::string::npos;
}
isValid()
bool TExpression::isValid ()
      Returns whether the expression is valid according to actual
grammar syntax (i.e. it has at least one calculator node).
{
  if (!m_imp->m_hasBeenParsed) parse();
  return m_imp->m_isValid;
}
operator=()
TExpression & TExpression::operator= (TExpression copy)
{
  std::swap(copy.m_imp, m_imp);
  return *this;
}
setGrammar()
void TExpression::setGrammar (const TSyntax::Grammar * grammar)
Sets the expression's grammar - does not acquire ownership.
{
  m_imp->m_grammar       = grammar;
  m_imp->m_hasBeenParsed = false;
}
Referenced by FunctionExpressionSegmentPage::getGuiValues(), and TDoubleParam::loadData().
setOwnerParameter()
void TExpression::setOwnerParameter (TDoubleParam * param)
{
  m_imp->m_param = param;
  if (m_imp->m_calculator) m_imp->m_calculator->setOwnerParameter(param);
}
setText()
void TExpression::setText (std::string text)
Sets the expression's text - a mix of mathematical expressions and grammar-recognized patterns that is able to calculate the expression's value at a given frame.
{
  if (m_imp->m_text != text || m_imp->m_hasReference) {
    m_imp->m_text = text;
    delete m_imp->m_calculator;
    m_imp->m_calculator    = 0;
    m_imp->m_isValid       = false;
    m_imp->m_hasReference  = false;
    m_imp->m_hasBeenParsed = false;
    m_imp->m_error         = "";
    m_imp->m_errorPos      = std::make_pair(0, -1);
  }
}
Referenced by FunctionExpressionSegmentPage::getGuiValues(), TDoubleParam::setKeyframe(), and TDoubleParam::setKeyframes().
The documentation for this class was generated from the following files:
E:/opentoonz/toonz/sources/include/texpression.h
E:/opentoonz/toonz/sources/common/expressions/texpression.cpp