opentoonz: TSop Namespace Reference
TSop Namespace Reference
Functions
DVAPI void convert (TSoundTrackP &dst, const TSoundTrackP &src)
DVAPI TSoundTrackP convert (const TSoundTrackP &src, const TSoundTrackFormat &dstFormat)
DVAPI TSoundTrackP resample (TSoundTrackP src, TINT32 sampleRate)
DVAPI TSoundTrackP reverb (TSoundTrackP src, double delayTime, double decayFactor, double extendTime)
DVAPI TSoundTrackP gate (TSoundTrackP src, double threshold, double holdTime, double releaseTime)
DVAPI void echo (TSoundTrackP &dst, const TSoundTrackP &src, double delayTime, double decayFactor, double extendTime)
DVAPI TSoundTrackP timeStretch (TSoundTrackP src, double ratio)
DVAPI TSoundTrackP mix (const TSoundTrackP &st1, const TSoundTrackP &st2, double a1, double a2)
DVAPI TSoundTrackP insertBlank (TSoundTrackP src, TINT32 s0, TINT32 l)
DVAPI TSoundTrackP insertBlank (TSoundTrackP src, double t0, double l)
DVAPI TSoundTrackP remove (TSoundTrackP src, TINT32 s0, TINT32 s1, TSoundTrackP &paste)
DVAPI TSoundTrackP remove (TSoundTrackP src, double t0, double t1, TSoundTrackP &paste)
DVAPI TSoundTrackP fadeIn (const TSoundTrackP src, double riseFactor)
DVAPI TSoundTrackP fadeOut (const TSoundTrackP src, double decayFactor)
DVAPI TSoundTrackP crossFade (const TSoundTrackP src1, const TSoundTrackP src2, double crossFactor)
DVAPI TSoundTrackP crossFade (double crossFactor, const TSoundTrackP src1, const TSoundTrackP src2)
Detailed Description
Function Documentation
convert() [1/2]
TSoundTrackP TSop::convert (const TSoundTrackP & src, const TSoundTrackFormat & dstFormat)
Convert the soundtrack src to the format specified in dstFormat and return the new soundtrack
{
  TINT32 dstSampleCount =
      (TINT32)(src->getSampleCount() *
               (dstFormat.m_sampleRate / (double)src->getSampleRate()));
  TSoundTrackP dst = TSoundTrack::create(dstFormat, dstSampleCount);
  TSop::convert(dst, src);
  return dst;
}
References convert(), and TSoundTrack::create().
convert() [2/2]
void TSop::convert (TSoundTrackP & dst, const TSoundTrackP & src)
Convert the soundtrack src to the format of the soundtrack dst
{
  int src_reslen, dst_reslen;
  int src_bits, dst_bits;
  int src_chans, dst_chans;
  TSoundTrackP tmp, tmq;
  RESORDER_TYPE order;
  assert(src->getSampleCount() >= 0 && dst->getSampleCount() >= 0);
  if (!dst->getSampleCount()) return;
  if (!src->getSampleCount()) {
    dst->blank(0L, (TINT32)(dst->getSampleCount() - 1));
    return;
  }
  if (src->getSampleRate() == dst->getSampleRate()) {
    src_reslen = dst->getSampleCount();
    notMoreThan((int)src->getSampleCount(), src_reslen);
    dst_reslen = src_reslen;
    convertWithoutResampling(dst, src);
  } else {
    src_reslen = FULL_INT_MUL_DIV(dst->getSampleCount(), src->getSampleRate(),
                                  dst->getSampleRate());
    if (src_reslen > src->getSampleCount()) {
      src_reslen = src->getSampleCount();
      dst_reslen = FULL_INT_MUL_DIV(src_reslen, dst->getSampleRate(),
                                    src->getSampleRate());
    } else
      dst_reslen = dst->getSampleCount();
    src_chans = src->getChannelCount();
    dst_chans = dst->getChannelCount();
    src_bits  = src->getBitPerSample();
    dst_bits  = dst->getBitPerSample();
    if (src_chans == dst_chans && src_bits == dst_bits)
      if (src->isSampleSigned() == dst->isSampleSigned())
        order = RESORDER_RATE;
      else
        order = RESORDER_SIGN;
    else if (src_chans < dst_chans) {
      if (src_bits < dst_bits)
        order = RESORDER_BITS_RATE_CHANS;
      else
        order = RESORDER_RATE_BITS_CHANS;
    } else if (src_chans > dst_chans) {
      if (src_bits > dst_bits)
        order = RESORDER_CHANS_RATE_BITS;
      else
        order = RESORDER_CHANS_BITS_RATE;
    } else {
      if (src_bits > dst_bits)
        order = RESORDER_RATE_BITS;
      else
        order = RESORDER_BITS_RATE;
    }
    switch (order) {
    case RESORDER_CHANS_RATE_BITS:
    case RESORDER_BITS_RATE_CHANS:
      int chans, bitPerSample;
      if (src->getChannelCount() <= dst->getChannelCount())
        chans = src->getChannelCount();
      else
        chans = dst->getChannelCount();
      if (src->getBitPerSample() >= dst->getBitPerSample())
        bitPerSample = src->getBitPerSample();
      else
        bitPerSample = dst->getBitPerSample();
      tmp = TSoundTrack::create((int)src->getSampleRate(), bitPerSample, chans,
                                src_reslen * src->getSampleSize());
      convertWithoutResampling(tmp, src);
      tmq = TSop::resample(tmp, (TINT32)dst->getSampleRate());
      convertWithoutResampling(dst, tmq);
      break;
    case RESORDER_RATE_BITS_CHANS:
    case RESORDER_RATE_BITS:
    case RESORDER_RATE_CHANS:
      tmp = TSop::resample(src, (TINT32)dst->getSampleRate());
      convertWithoutResampling(dst, tmp);
      break;
    case RESORDER_CHANS_BITS_RATE:
    case RESORDER_BITS_RATE:
    case RESORDER_CHANS_RATE:
    case RESORDER_SIGN:
      tmp = TSoundTrack::create((int)src->getSampleRate(),
                                dst->getBitPerSample(), dst->getChannelCount(),
                                src_reslen * dst->getSampleSize(),
                                dst->isSampleSigned());
      convertWithoutResampling(tmp, src);
      dst = TSop::resample(tmp, (TINT32)dst->getSampleRate());
      break;
    case RESORDER_RATE:
      dst = TSop::resample(src, (TINT32)dst->getSampleRate());
      break;
    default:
      assert(false);
      break;
    }
  }
  if (dst_reslen < dst->getSampleCount())
    dst->blank((TINT32)dst_reslen, (TINT32)(dst->getSampleCount() - 1));
}
References TSoundTrack::blank(), TSoundTrack::create(), TSoundTrack::isSampleSigned(), and resample().
Referenced by convert().
crossFade() [1/2]
TSoundTrackP TSop::crossFade (const TSoundTrackP src1, const TSoundTrackP src2, double crossFactor)
Returns a soundtrack that has just the crossFactor of sample of src2. The samples of the output soundTrack come from the value of the last sample of src1 to the value of the first sample of src2
{
  TSoundTrackCrossFader *fader = new TSoundTrackCrossFader(src2, crossFactor);
  TSoundTrackP out             = src1->apply(fader);
  delete fader;
  return out;
}
References TSoundTrack::apply().
Referenced by WavehdrQueue::put().
crossFade() [2/2]
TSoundTrackP TSop::crossFade (double crossFactor, const TSoundTrackP src1, const TSoundTrackP src2)
Returns a soundtrack that has the sampleCount of src2. But the first crossFactor of samples come from the value of the last sample of src1 to the value of the crossFactor-th sample of src2
{
  TSoundTrackCrossFaderOverWrite *fader =
      new TSoundTrackCrossFaderOverWrite(src2, crossFactor);
  TSoundTrackP out = src1->apply(fader);
  delete fader;
  return out;
}
References TSoundTrack::apply().
echo()
void TSop::echo (TSoundTrackP & dst, const TSoundTrackP & src, double delayTime, double decayFactor, double extendTime)
Does the echo effect to the soundtrack src with the specified feature
{
  TSoundTrackMono8Signed *srcM8S;
  srcM8S = dynamic_cast<TSoundTrackMono8Signed *>(src.getPointer());
  if (srcM8S)
    dst = doEcho(srcM8S, delayTime, decayFactor, extendTime);
  else {
    TSoundTrackMono8Unsigned *srcM8U;
    srcM8U = dynamic_cast<TSoundTrackMono8Unsigned *>(src.getPointer());
    if (srcM8U)
      dst = doEcho(srcM8U, delayTime, decayFactor, extendTime);
    else {
      TSoundTrackStereo8Signed *srcS8S;
      srcS8S = dynamic_cast<TSoundTrackStereo8Signed *>(src.getPointer());
      if (srcS8S)
        dst = doEcho(srcS8S, delayTime, decayFactor, extendTime);
      else {
        TSoundTrackStereo8Unsigned *srcS8U;
        srcS8U = dynamic_cast<TSoundTrackStereo8Unsigned *>(src.getPointer());
        if (srcS8U)
          dst = doEcho(srcS8U, delayTime, decayFactor, extendTime);
        else {
          TSoundTrackMono16 *srcM16;
          srcM16 = dynamic_cast<TSoundTrackMono16 *>(src.getPointer());
          if (srcM16)
            dst = doEcho(srcM16, delayTime, decayFactor, extendTime);
          else {
            TSoundTrackStereo16 *srcS16;
            srcS16 = dynamic_cast<TSoundTrackStereo16 *>(src.getPointer());
            if (srcS16)
              dst = doEcho(srcS16, delayTime, decayFactor, extendTime);
            else {
              TSoundTrackMono24 *srcM24;
              srcM24 = dynamic_cast<TSoundTrackMono24 *>(src.getPointer());
              if (srcM24)
                dst = doEcho(srcM24, delayTime, decayFactor, extendTime);
              else {
                TSoundTrackStereo24 *srcS24;
                srcS24 = dynamic_cast<TSoundTrackStereo24 *>(src.getPointer());
                if (srcS24)
                  dst = doEcho(srcS24, delayTime, decayFactor, extendTime);
              }
            }
          }
        }
      }
    }
  }
}
fadeIn()
TSoundTrackP TSop::fadeIn (const TSoundTrackP src, double riseFactor)
Returns a soundtrack that has just the riseFactor of sample of src. The samples of the output soundTrack come from the "zero" sample to the value of the first sample of src
{
  TSoundTrackFaderIn *fader = new TSoundTrackFaderIn(riseFactor);
  TSoundTrackP out          = src->apply(fader);
  delete fader;
  return out;
}
References TSoundTrack::apply().
Referenced by WavehdrQueue::put().
fadeOut()
TSoundTrackP TSop::fadeOut (const TSoundTrackP src, double decayFactor)
Returns a soundtrack that has just the decayFactor of sample of src. The samples of the output soundTrack come from the value of the last sample of src to the "zero" sample
{
  TSoundTrackFaderOut *fader = new TSoundTrackFaderOut(decayFactor);
  TSoundTrackP out           = src->apply(fader);
  delete fader;
  return out;
}
References TSoundTrack::apply().
Referenced by WavehdrQueue::put().
gate()
TSoundTrackP TSop::gate (TSoundTrackP src, double threshold, double holdTime, double releaseTime)
Gates the soundtrack src with the specified feature and returns the obtained soundtrack
{
  TSoundGate *gate = new TSoundGate(threshold, holdTime, releaseTime);
  assert(gate);
  if (!gate) return TSoundTrackP();
  TSoundTrackP dst = src->apply(gate);
  delete gate;
  return dst;
}
References TSoundTrack::apply(), and gate().
Referenced by gate().
insertBlank() [1/2]
TSoundTrackP TSop::insertBlank (TSoundTrackP src, double t0, double l)
Inserts a blank portion of duration l into the soundtrack, starting from t0. t0 and l are expressed in seconds.
{
  return insertBlank(src, src->secondsToSamples(t0),
                     src->secondsToSamples(len));
}
References insertBlank(), and TSoundTrack::secondsToSamples().
insertBlank() [2/2]
TSoundTrackP TSop::insertBlank (TSoundTrackP src, TINT32 s0, TINT32 l)
Inserts l blank samples starting from the sample s0 of the soundtrack.
{
  assert(len >= 0);
  if (len == 0) return src;
  TINT32 ss0 = tcrop<TINT32>(s0, 0, src->getSampleCount());
  TSoundTrackFormat format = src->getFormat();
  TSoundTrackP dst = TSoundTrack::create(format, (src->getSampleCount() + len));
  UCHAR *dstRawData = (UCHAR *)dst->getRawData();
  UCHAR *srcRawData = (UCHAR *)src->getRawData();
  int bytePerSample = dst->getSampleSize();
  memcpy(dstRawData, srcRawData, ss0 * bytePerSample);
  if (format.m_signedSample)
    memset(dstRawData + ss0 * bytePerSample, 0, len * bytePerSample);
  else
    memset(dstRawData + ss0 * bytePerSample, 127, len * bytePerSample);
  memcpy(dstRawData + (ss0 + len) * bytePerSample,
         srcRawData + ss0 * bytePerSample,
         (src->getSampleCount() - ss0) * bytePerSample);
  return dst;
}
References TSoundTrack::create(), TSoundTrack::getFormat(), and TSoundTrack::getRawData().
Referenced by insertBlank().
mix()
TSoundTrackP TSop::mix (const TSoundTrackP & st1, const TSoundTrackP & st2, double a1, double a2)
Do the mixing between the two soundtrack a1 and a2 must be inside [0.0,1.0]
{
  TSoundTrackMixer *converter;
  a1               = tcrop<double>(a1, 0.0, 1.0);
  a2               = tcrop<double>(a2, 0.0, 1.0);
  converter        = new TSoundTrackMixer(a1, a2, st2);
  TSoundTrackP snd = st1->apply(converter);
  delete converter;
  return (snd);
}
References TSoundTrack::apply().
Referenced by TXshSoundColumn::play().
remove() [1/2]
TSoundTrackP TSop::remove (TSoundTrackP src, double t0, double t1, TSoundTrackP & paste)
Remove the portion of soundtrack in the range [t0, t1]. t0 and t1 are expressed in seconds. Returns a soundtrack that contains just the portion that has been removed.
{
  return remove(src, src->secondsToSamples(t0), src->secondsToSamples(t1),
                paste);
}
References remove(), and TSoundTrack::secondsToSamples().
remove() [2/2]
TSoundTrackP TSop::remove (TSoundTrackP src, TINT32 s0, TINT32 s1, TSoundTrackP & paste)
Removes from the soundtrack the samples in the range [s0, s1]. Returns a soundtrack that contains just the samples that have been removed
{
  TINT32 ss0, ss1;
  ss0 = std::max<TINT32>((TINT32)0, s0);
  ss1 = std::min(s1, (TINT32)(src->getSampleCount() - 1));
  TSoundTrackP soundTrackSlice;
  if (ss0 <= ss1) soundTrackSlice = src->extract(ss0, ss1);
  if (!soundTrackSlice) {
    paste = TSoundTrackP();
    return src;
  }
  paste = soundTrackSlice->clone();
  TSoundTrackFormat format = src->getFormat();
  TSoundTrackP dst =
      TSoundTrack::create(format, (src->getSampleCount() - (ss1 - ss0 + 1)));
  TINT32 dstSampleSize = dst->getSampleSize();
  UCHAR *newRowData    = (UCHAR *)dst->getRawData();
  UCHAR *srcRowData    = (UCHAR *)src->getRawData();
  memcpy(newRowData, srcRowData, ss0 * dstSampleSize);
  memcpy(newRowData + (ss0 * dstSampleSize),
         srcRowData + (ss1 + 1) * dstSampleSize,
         (src->getSampleCount() - ss1 - 1) * dst->getSampleSize());
  return dst;
}
References TSoundTrack::clone(), TSoundTrack::create(), TSoundTrack::extract(), TSoundTrack::getFormat(), and TSoundTrack::getRawData().
Referenced by remove().
resample()
TSoundTrackP TSop::resample (TSoundTrackP src, TINT32 sampleRate)
Resampls the soundtrack src at the specified sampleRate and returns the obtained soundtrack
{
  TSoundTrackResample *resample =
      new TSoundTrackResample(sampleRate, FLT_HAMMING3);
  TSoundTrackP dst = src->apply(resample);
  delete resample;
  return dst;
}
References TSoundTrack::apply().
Referenced by convert().
reverb()
TSoundTrackP TSop::reverb (TSoundTrackP src, double delayTime, double decayFactor, double extendTime)
Reverbs the soundtrack src with the specified feature and returns the obtained soundtrack
{
  TSoundReverb *reverb = new TSoundReverb(delayTime, decayFactor, extendTime);
  assert(reverb);
  if (!reverb) return TSoundTrackP();
  TSoundTrackP dst = src->apply(reverb);
  delete reverb;
  return dst;
}
References TSoundTrack::apply(), and reverb().
Referenced by reverb().
timeStretch()
TSoundTrackP TSop::timeStretch (TSoundTrackP src, double ratio)
Stretches the soundtrack src with the specified feature and returns the obtained soundtrack
{
  TINT32 sampleRate = (TINT32)(src->getSampleRate() * ratio);
  if (sampleRate > 100000) sampleRate = 100000;
  TSoundTrackP st;
  if (sampleRate > 0) {
    TSoundTrackResample *resample =
        new TSoundTrackResample(sampleRate, FLT_TRIANGLE);
    st = src->apply(resample);
    delete resample;
    st->setSampleRate(src->getSampleRate());
  }
  return st;
}
References TSoundTrack::apply().