opentoonz: IoCmd Namespace Reference
IoCmd Namespace Reference
Contains command functions related to Toonz I/O.
Classes
class ConvertingPopup
struct ExportLevelOptions
Collection of options accepted by the export level command.
struct LoadResourceArguments
Composite data used describing a group of Toonz resources to be loaded.
struct OverwriteCallbacks
struct ProgressCallbacks
Enumerations
enum SaveSceneFlags { SILENTLY_OVERWRITE = 0x1 , SAVE_SUBXSHEET = 0x2 , AUTO_SAVE = 0x4 }
Functions
TImageP exportedImage (const std::string &ext, const TXshSimpleLevel &sl, const TFrameId &fid, const ExportLevelOptions &opts=ExportLevelOptions())
Intended for preview purposes, computes the image that will be exported by the exportLevel() command.
bool exportLevel (const TFilePath &path, TXshSimpleLevel *sl=0, ExportLevelOptions opts=ExportLevelOptions(), OverwriteCallbacks *overwriteCB=0, ProgressCallbacks *progressCB=0)
Exports passed level to the specified path.
void newScene ()
bool loadScene (ToonzScene &scene, const TFilePath &scenePath, bool import)
bool loadScene (const TFilePath &scenePath, bool updateRecentFile=true, bool checkSaveOldScene=true)
bool loadScene ()
bool loadSubScene ()
bool loadSubScene (const TFilePath &scenePath)
bool saveScene (const TFilePath &fp, int flags)
bool saveScene (int flags=0)
bool saveLevel (const TFilePath &fp)
bool saveLevel ()
bool saveLevel (const TFilePath &fp, TXshSimpleLevel *sl, bool overwrite)
bool saveLevel (TXshSimpleLevel *sl)
bool saveAll (int flags=0)
void saveNonSceneFiles ()
bool saveSound (const TFilePath &fp, TXshSoundLevel *sc, bool overwrite)
bool saveSound (TXshSoundLevel *sc)
int loadResources (LoadResourceArguments &args, bool updateRecentFiles=true, LoadResourceArguments::ScopedBlock *sb=0)
int loadResourceFolders (LoadResourceArguments &args, LoadResourceArguments::ScopedBlock *sb=0)
bool exposeLevel (TXshSimpleLevel *sl, int row, int col, bool insert=false, bool overWrite=false)
bool exposeLevel (TXshSimpleLevel *sl, int row, int col, const std::vector< TFrameId > &fids, bool insert=false, bool overWrite=false)
bool saveSceneIfNeeded (QString msg)
bool exposeComment (int row, int &col, QList< QString > commentList, QString fileName)
Create and expose column with comment in commentList.
bool importLipSync (TFilePath levelPath, QList< TFrameId > frameList, QList< QString > commentList, QString fileName)
bool takeCareSceneFolderItemsOnSaveSceneAs (ToonzScene *scene, const TFilePath &newPath, TXsheet *subxsh, QHash< TXshLevel *, TFilePath > &orgLevelPaths)
Detailed Description
Contains command functions related to Toonz I/O.
Enumeration Type Documentation
SaveSceneFlags
enum IoCmd::SaveSceneFlags
                    {
  SILENTLY_OVERWRITE = 0x1,
  SAVE_SUBXSHEET     = 0x2,
  AUTO_SAVE          = 0x4
};
Function Documentation
exportedImage()
TImageP IoCmd::exportedImage (const std::string & ext, const TXshSimpleLevel & sl, const TFrameId & fid, const ExportLevelOptions & opts = ExportLevelOptions())
Intended for preview purposes, computes the image that will be exported by the exportLevel() command.
Remarks
Supplied image may be the one retrievable by sl, depending on whether the specified options require it to be modified.
Returns
The image that will be exported by the exportLevel() command.
Parameters
ext File extension - like tga, tlv, png, etc...
sl Level host of the image to be exported.
fid Frame of the image in sl.
opts Export options.
{
  ImageExporter exporter(sl, opts);
  return exporter.exportedImage(fid, (ext == "tlv") ? TZP_TYPE : OVL_TYPE);
}
exportLevel()
bool IoCmd::exportLevel (const TFilePath & path, TXshSimpleLevel * sl = 0, ExportLevelOptions opts = ExportLevelOptions(), OverwriteCallbacks * overwriteCB = 0, ProgressCallbacks * progressCB = 0)
Exports passed level to the specified path.
Returns
Whether the level was successfully exported in its entirety. User cancels are reported as failures, even if a part of the level has been successfully exported.
This function performs level export depending on the specified path's extension, and optional parameters. If no input level is specified for the export, this function attempts the export of currently active level (if any).
This function allows external callbacks to deal with overwrite and progress notifications. If no callback is supplied to the function, default ones will be used.
Parameters
path File path to export the level to.
sl Level to export; if 0, current level will be used.
opts Export options.
overwriteCB External callbacks to overwrite requests.
progressCB External callbacks to progress notifications.
{
  struct Locals {
    const TFilePath &m_path;
    TXshSimpleLevel *m_sl;
    const ExportLevelOptions &m_opts;
    OverwriteCallbacks *m_overwriteCB;
    ProgressCallbacks *m_progressCB;
    bool exportToMultifile() {
      ImageExporter exporter(*m_sl, m_opts);
      TXshLevelType outputLevelType =
          (m_path.getType() == "tlv") ? TZP_TYPE : OVL_TYPE;
      bool firstTime = true;
      for (int i = 0; i < m_sl->getFrameCount(); ++i) {
        if (m_progressCB->canceled()) return false;
        // Prepare frame export path
        TFilePath fpout;
        if (m_opts.m_forRetas) {
          QString pathOut =
              QString::fromStdWString(m_path.getParentDir().getWideString()) +
              "\\" + QString::fromStdString(m_path.getName()) +
              QString::fromStdString(m_sl->index2fid(i).expand()) + "." +
              QString::fromStdString(m_path.getType());
          fpout = TFilePath(pathOut.toStdString());
        } else
          fpout = TFilePath(m_path.withFrame(m_sl->index2fid(i)));
        // Ask for overwrite permission in case a level with the built path
        // already exists
        if (firstTime) {
          firstTime = false;
          if (TSystem::doesExistFileOrLevel(fpout)) {
            QApplication::restoreOverrideCursor();
            bool overwrite = m_overwriteCB->overwriteRequest(fpout);
            QApplication::setOverrideCursor(Qt::WaitCursor);
            if (!overwrite) return false;
          }
        }
        // Retrieve the image to export at current frame
        TImageP img =
            exporter.exportedImage(m_sl->index2fid(i), outputLevelType);
        assert(img);
        // Save the prepared fullcolor image to file
        TImageWriter iw(fpout);
        iw.setProperties(m_opts.m_props);
        iw.save(img);
        m_progressCB->setValue(i + 1);
      }
      return true;
    }
    bool exportToTlv() {
      TFilePath fp(m_path.withNoFrame());
      // Remove any existing level
      if (TSystem::doesExistFileOrLevel(fp)) {
        bool overwrite = m_overwriteCB->overwriteRequest(fp);
        if (!overwrite) return false;
        TSystem::deleteFile(fp);
      }
      TSystem::removeFileOrLevel(fp.withType("tpl"));
      // Export level
      TLevelWriterP lw(fp);
      ImageExporter exporter(*m_sl, m_opts);
      for (int i = 0; i < m_sl->getFrameCount(); ++i) {
        if (m_progressCB->canceled()) return false;
        const TFrameId &fid = m_sl->index2fid(i);
        TImageP img = exporter.exportedImage(fid, TZP_TYPE);
        assert(img);
        lw->getFrameWriter(fid)->save(img);
        m_progressCB->setValue(i + 1);
      }
      return true;
    }
  };  // Locals
  // Use default values in case some were not specified by input
  // Level
  if (!sl) {
    sl = TApp::instance()->getCurrentLevel()->getSimpleLevel();
    if (!sl) {
      DVGui::error(QObject::tr("No level selected!"));
      return false;
    }
  }
  if (sl->isEmpty()) return false;
  // Output properties
  if (!opts.m_props) {
    ToonzScene *scene = TApp::instance()->getCurrentScene()->getScene();
    opts.m_props =
        scene->getProperties()->getOutputProperties()->getFileFormatProperties(
            path.getType());
  }
  // Camera (todo)
  assert(opts.m_camera.getRes().lx > 0 && opts.m_camera.getRes().ly > 0);
  // Callbacks
  std::unique_ptr<OverwriteCallbacks> overwriteDefault(
      overwriteCB ? 0 : (overwriteCB = new ExportOverwriteCB()));
  std::unique_ptr<ProgressCallbacks> progressDefault(
      progressCB ? 0 : (progressCB = new ExportProgressCB()));
  // Initialize variables
  Locals locals = {path, sl, opts, overwriteCB, progressCB};
  progressCB->setProcessedName(QString::fromStdWString(path.getWideString()));
  progressCB->setRange(0, sl->getFrameCount());
  // Export level
  BusyCursorOverride cursorOverride;
  QCoreApplication::processEvents();  // Refresh screen.   ...But WHY is this
                                      //                      necessary?
  try {
    return (path.getType() == "tlv") ? assert(sl->getType() == PLI_XSHLEVEL),
           locals.exportToTlv() : locals.exportToMultifile();
  } catch (...) {
    return false;
  }
}
References TApp::getCurrentLevel(), TApp::getCurrentScene(), TOutputProperties::getFileFormatProperties(), TXshSimpleLevel::getFrameCount(), TFilePath::getName(), TSceneProperties::getOutputProperties(), TFilePath::getParentDir(), ToonzScene::getProperties(), TCamera::getRes(), TFilePath::getType(), TXshLevel::getType(), TXshSimpleLevel::index2fid(), TApp::instance(), TXshSimpleLevel::isEmpty(), IoCmd::ExportLevelOptions::m_camera, IoCmd::ExportLevelOptions::m_forRetas, IoCmd::ExportLevelOptions::m_props, IoCmd::OverwriteCallbacks::overwriteRequest(), TFilePath::withFrame(), and TFilePath::withType().
Referenced by ExportLevelPopup::execute().
exposeComment()
bool IoCmd::exposeComment (int row, int & col, QList< QString > commentList, QString fileName)
Create and expose column with comment in commentList.
{
  TApp *app                         = TApp::instance();
  TXsheet *xsh                      = app->getCurrentXsheet()->getXsheet();
  TXshSoundTextColumn *textSoundCol = new TXshSoundTextColumn();
  textSoundCol->setXsheet(xsh);
  textSoundCol->createSoundTextLevel(row, commentList);
  bool columnInserted = beforeCellsInsert(xsh, row, col, commentList.size(),
                                          TXshColumn::eSoundTextType);
  xsh->insertColumn(col, textSoundCol);
  // Setto il nome di dafult della colonna al nome del file magpie.
  TStageObject *obj = xsh->getStageObject(TStageObjectId::ColumnId(col));
  std::string str   = fileName.toStdString();
  obj->setName(str);
  TUndoManager::manager()->add(
      new ExposeCommentUndo(textSoundCol, col, columnInserted, fileName));
  return true;
}
References TApp::getCurrentXsheet(), TXsheet::getStageObject(), TXsheet::insertColumn(), TApp::instance(), and TXshColumn::setXsheet().
exposeLevel() [1/2]
bool IoCmd::exposeLevel (TXshSimpleLevel * sl, int row, int col, bool insert = false, bool overWrite = false)
{
  TApp *app    = TApp::instance();
  TXsheet *xsh = app->getCurrentXsheet()->getXsheet();
  assert(xsh);
  std::vector<TFrameId> fids;
  sl->getFids(fids);
  return exposeLevel(sl, row, col, fids, insert, overWrite);
}
exposeLevel() [2/2]
bool IoCmd::exposeLevel (TXshSimpleLevel * sl, int row, int col, const std::vector< TFrameId > & fids, bool insert = false, bool overWrite = false)
{
  assert(sl);
  TApp *app    = TApp::instance();
  TXsheet *xsh = app->getCurrentXsheet()->getXsheet();
  assert(xsh);
  int frameCount         = fids.size();
  bool insertEmptyColumn = false;
  if (!insert && !overWrite)
    insertEmptyColumn = beforeCellsInsert(
        xsh, row, col, fids.size(), TXshColumn::toColumnType(sl->getType()));
  ExposeType type = eNone;
  if (insert) type = eShiftCells;
  if (overWrite) type = eOverWrite;
  ExposeLevelUndo *undo =
      new ExposeLevelUndo(sl, row, col, frameCount, insertEmptyColumn, type);
  xsh->exposeLevel(row, col, sl, fids, overWrite);
  undo->setFids(fids);
  TUndoManager::manager()->add(undo);
  app->getCurrentXsheet()->notifyXsheetChanged();
  return true;
}
importLipSync()
bool IoCmd::importLipSync (TFilePath levelPath, QList< TFrameId > frameList, QList< QString > commentList, QString fileName)
{
  TApp *app = TApp::instance();
  int col   = app->getCurrentColumn()->getColumnIndex();
  int row   = app->getCurrentFrame()->getFrameIndex();
  IoCmd::LoadResourceArguments args;
  IoCmd::LoadResourceArguments::ScopedBlock sb;
  // Create text column
  IoCmd::exposeComment(row, col, commentList, fileName);
  // Load Level
  args.resourceDatas.push_back(levelPath);
  args.expose = false;
  if (!IoCmd::loadResources(args, false, &sb)) {
    DVGui::error(QObject::tr("It is not possible to load the level %1")
                     .arg(toQString(levelPath)));
    return false;
  }
  // Expose Level in xsheet
  assert(args.loadedLevels.size() == 1);
  TXshLevel *loadedLevel = args.loadedLevels.at(0);
  std::vector<TFrameId> fids;
  for (int i = 0; i < frameList.size(); i++) fids.push_back(frameList.at(i));
  if (!IoCmd::exposeLevel(loadedLevel->getSimpleLevel(), row, col, fids)) {
    DVGui::error(QObject::tr("It is not possible to load the level %1")
                     .arg(toQString(levelPath)));
    return false;
  }
  return true;
}
loadResourceFolders()
int IoCmd::loadResourceFolders (LoadResourceArguments & args, LoadResourceArguments::ScopedBlock * sb = 0)
Loads the specified folders in current xsheet.
Returns
The actually loaded levels count.
Parameters
args Resource folders to be loaded.
sb Load block. May be nonzero in order to extend block data access and finalization.
{
  struct locals {
    static LRArgs::ResourceData toResourceData(const Resource &rsrc) {
      LRArgs::ResourceData rd(rsrc.m_path.absoluteResourcePath());
      rd.m_options = rsrc.m_levelOptions;
      return rd;
    }
    static bool isExternPath(const ToonzScene &scene,
                             const LRArgs::ResourceData &rd) {
      return scene.isExternPath(rd.m_path);
    }
  };  // locals
  boost::optional<LRArgs::ScopedBlock> sb_;
  if (!sb) sb = (sb_ = boost::in_place()).get_ptr();
  ToonzScene *scene = TApp::instance()->getCurrentScene()->getScene();
  assert(scene);
  // Loading options popup
  // Deal with import decision
  bool import = false;
  {
    if (std::any_of(
            args.resourceDatas.begin(), args.resourceDatas.end(),
            boost::bind(locals::isExternPath, boost::cref(*scene), _1))) {
      // Ask for data import in this case
      int resolutionButton = DVGui::MsgBox(
          QObject::tr("Selected folders don't belong to the current project.\n"
                      "Do you want to import them or load from their original "
                      "location?"),
          QObject::tr("Load"), QObject::tr("Import"), QObject::tr("Cancel"));
      enum { CLOSED, LOAD, IMPORT, CANCELED };
      switch (resolutionButton) {
      case CLOSED:
      case CANCELED:
        return 0;
      case IMPORT:
        import = true;
      }
    }
  }
  // Select resources to be loaded
  std::vector<Resource> resources;
  boost::for_each(
      args.resourceDatas |
          boost::adaptors::transformed(boost::bind<const TFilePath &>(
              &LRArgs::ResourceData::m_path, _1)),
      boost::bind(::buildResources, boost::ref(resources), _1, TFilePath()));
  // Import them if required
  if (import) ::import(*scene, resources, *sb);
  // Temporarily substitute args' import policy
  struct SubstImportPolicy {
    LRArgs &m_args;
    LRArgs::ImportPolicy m_policy;
    SubstImportPolicy(LRArgs &args, LRArgs::ImportPolicy policy)
        : m_args(args), m_policy(args.importPolicy) {
      args.importPolicy = policy;
    }
    ~SubstImportPolicy() { m_args.importPolicy = m_policy; }
  } substImportPolicy(args, import ? LRArgs::IMPORT : LRArgs::LOAD);
  // Perform loading via loadResources()
  args.resourceDatas.assign(
      boost::make_transform_iterator(resources.begin(), locals::toResourceData),
      boost::make_transform_iterator(resources.end(), locals::toResourceData));
  return IoCmd::loadResources(args, false, sb);
}
References TApp::getCurrentScene(), TApp::instance(), ToonzScene::isExternPath(), loadResources(), and IoCmd::LoadResourceArguments::resourceDatas.
Referenced by loadResources().
loadResources()
int IoCmd::loadResources (LoadResourceArguments & args, bool updateRecentFiles = true, LoadResourceArguments::ScopedBlock * sb = 0)
Note
Will fallback to loadResourceFolders() in case all argument paths are folders.
Parameters
args Resources to be loaded.
updateRecentFiles Whether Toonz's Recent Files list must be updated.
sb Load block. May be nonzero in order to extend block data access and finalization. Loads a group of resources by path.
Returns
The actually loaded levels count.
{
  struct locals {
    static bool isDir(const LoadResourceArguments::ResourceData &rd) {
      return QFileInfo(rd.m_path.getQString()).isDir();
    }
  };  // locals
  if (args.resourceDatas.empty()) return 0;
  // Redirect to resource folders loading in case they're all dirs
  if (std::all_of(args.resourceDatas.begin(), args.resourceDatas.end(),
                  locals::isDir))
    return loadResourceFolders(args, sb);
  boost::optional<LoadScopedBlock> sb_;
  if (!sb) sb = (sb_ = boost::in_place()).get_ptr();
  int &row0 = args.row0, &col0 = args.col0, &row1 = args.row1,
      &col1 = args.col1;
  // Setup local variables
  TApp *app         = TApp::instance();
  ToonzScene *scene = app->getCurrentScene()->getScene();
  TXsheet *xsh      = scene->getXsheet();
  // use current frame/column if row/col is not set
  if (row0 == -1) row0 = app->getCurrentFrame()->getFrameIndex();
  if (col0 == -1) col0 = app->getCurrentColumn()->getColumnIndex();
  int rCount = args.resourceDatas.size(), loadedCount = 0;
  bool isSoundLevel = false;
  // show wait cursor in case of caching all images because it is time consuming
  if (args.cachingBehavior == LoadResourceArguments::ALL_ICONS_AND_IMAGES)
    QApplication::setOverrideCursor(Qt::WaitCursor);
  // Initialize progress dialog
  DVGui::ProgressDialog *progressDialog =
      (rCount > 1) ? &sb->progressDialog() : 0;
  if (progressDialog) {
    progressDialog->setModal(true);
    progressDialog->setMinimum(0);
    progressDialog->setMaximum(rCount);
    progressDialog->show();
  }
  // Initialize import dialog
  ResourceImportDialog importDialog;
  if (args.importPolicy != LoadResourceArguments::ASK_USER) {
    importDialog.setImportEnabled(args.importPolicy ==
                                  LoadResourceArguments::IMPORT);
  }
  std::vector<TFilePath> paths;
  int all = 0;
  // Loop for all the resources to load
  for (int r = 0; r != rCount; ++r) {
    if (importDialog.aborted()) break;
    QString origName =
        args.resourceDatas[r].m_path.withoutParentDir().getQString();
    LoadResourceArguments::ResourceData rd(args.resourceDatas[r]);
    TFilePath &path = rd.m_path;
    if (!rd.m_path.isLevelName())
      path = TFilePath(path.getLevelNameW()).withParentDir(path.getParentDir());
    if (std::find(paths.begin(), paths.end(), path) != paths.end()) {
      if (!all) {
        QString question =
            QObject::tr(
                "File '%1' will reload level '%2' as a duplicate column in the "
                "xsheet.\n\nAllow duplicate?")
                .arg(origName)
                .arg(QString::fromStdString(path.getName()));
        QString Yes    = QObject::tr("Allow");
        QString YesAll = QObject::tr("Allow All Dups");
        QString No     = QObject::tr("No");
        QString NoAll  = QObject::tr("No to All Dups");
        int ret        = DVGui::MsgBox(question, Yes, YesAll, No, NoAll, 0);
        switch (ret) {
        case 2:
          all = 1;  // YesAll
        case 1:
          break;  // Yes
        case 4:
          all = 2;  // NoAll
        case 3:
          continue;
        }
      } else if (all == 2)
        continue;
    }
    paths.push_back(path);
    if (progressDialog) {
      if (progressDialog->wasCanceled())
        break;
      else {
        progressDialog->setLabelText(
            DVGui::ProgressDialog::tr("Loading \"%1\"...")
                .arg(path.getQString()));
        progressDialog->setValue(r);
        QCoreApplication::processEvents();
      }
    }
    bool isLastResource = (r == rCount - 1);
    importDialog.setIsLastResource(isLastResource);
    bool isScene = (TFileType::getInfo(path) == TFileType::TOONZSCENE);
    if (scene->isExternPath(path) || isScene) {
      // extern resource: import or link?
      int ret = importDialog.askImportQuestion(path);
      if (ret == ResourceImportDialog::A_CANCEL) break;
    }
    // for the scene file
    TXshLevel *xl = 0;
    if (isScene) {
      TFilePath oldDstFolder = importDialog.getDstFolder();
      TFilePath dstFolder = (Preferences::instance()->isSubsceneFolderEnabled())
                                ? TFilePath(path.getName())
                                : TFilePath();
      importDialog.setDstFolder(dstFolder);
      importDialog.setIsLastResource(false);
      // load the scene as subXsheet
      try {
        xl = loadChildLevel(scene, path, row0, col0, importDialog);
        if (dstFolder != TFilePath())
          app->getCurrentScene()->notifyCastFolderAdded(
              scene->getLevelSet()->getDefaultFolder() + dstFolder);
        // increment the number of resources actually loaded
        ++loadedCount;
        // move the column to the right
        ++col0;
        // register the loaded level to args
        args.loadedLevels.push_back(xl);
        app->getCurrentXsheet()->notifyXsheetSoundChanged();
      } catch (...) {
      }
      importDialog.setIsLastResource(isLastResource);
      importDialog.setDstFolder(oldDstFolder);
      app->getCurrentColumn()->setColumnIndex(col0);
      continue;
    }
    // for other level files
    else {
      try {
        path = importDialog.process(scene, 0, path);
        // path = scene->decodeFilePath(codedPath);
      } catch (std::string msg) {
        error(QString::fromStdString(msg));
        continue;
      }
      if (importDialog.aborted()) break;
    }
    if (path.getType() == "psd") {
      static PsdSettingsPopup *popup = 0;
      if (!popup) {
        popup = new PsdSettingsPopup();
      }
      popup->setPath(path);
      int ret = popup->exec();
      if (ret == 0) continue;
      loadedCount += loadPSDResource(args, updateRecentFile, popup);
      if (updateRecentFile)
        RecentFiles::instance()->addFilePath(
            toQString(scene->decodeFilePath(path)), RecentFiles::Level);
    } else {
      // reuse TFrameIds retrieved by FileBrowser
      std::vector<TFrameId> fIds;
      if ((int)args.frameIdsSet.size() > r)  // if there is fIds to be reused
      {
        fIds = args.frameIdsSet[r];
      }
      try {
        xl = ::loadResource(
            scene, rd, args.castFolder, row0, col0, row1, col1, args.expose,
#if (__cplusplus > 199711L)
            std::move(fIds),
#else
            fIds,
#endif
            args.xFrom, args.xTo, args.levelName, args.step, args.inc,
            args.frameCount, args.doesFileActuallyExist);
        if (updateRecentFile) {
          RecentFiles::instance()->addFilePath(
              toQString(scene->decodeFilePath(path)), RecentFiles::Level);
        }
      } catch (TException &e) {
        error(QString::fromStdWString(e.getMessage()));
      }
      // if load success
      if (xl) {
        isSoundLevel = isSoundLevel || xl->getType() == SND_XSHLEVEL;
        // register the loaded level to args
        args.loadedLevels.push_back(xl);
        // increment the number of loaded resources
        ++loadedCount;
        // load the image data of all frames to cache at the beginning
        if (args.cachingBehavior != LoadResourceArguments::ON_DEMAND) {
          TXshSimpleLevel *simpleLevel = xl->getSimpleLevel();
          if (simpleLevel && simpleLevel->getType() == TZP_XSHLEVEL) {
            bool cacheImagesAsWell =
                (args.cachingBehavior ==
                 LoadResourceArguments::ALL_ICONS_AND_IMAGES);
            simpleLevel->loadAllIconsAndPutInCache(cacheImagesAsWell);
          }
        }
      }
    }
  }
  if (loadedCount) app->getCurrentFrame()->setFrameIndex(row0);
  sb->data().m_loadedCount += loadedCount;
  sb->data().m_hasSoundLevel = sb->data().m_hasSoundLevel || isSoundLevel;
  // revert the cursor
  if (args.cachingBehavior == LoadResourceArguments::ALL_ICONS_AND_IMAGES)
    QApplication::restoreOverrideCursor();
  return loadedCount;
}
References IoCmd::LoadResourceArguments::castFolder, IoCmd::LoadResourceArguments::col0, IoCmd::LoadResourceArguments::col1, IoCmd::LoadResourceArguments::ScopedBlock::data(), ToonzScene::decodeFilePath(), IoCmd::LoadResourceArguments::expose, TApp::getCurrentColumn(), TApp::getCurrentFrame(), TApp::getCurrentScene(), TApp::getCurrentXsheet(), ToonzScene::getLevelSet(), TFilePath::getName(), TFilePath::getParentDir(), TXshLevel::getSimpleLevel(), TFilePath::getType(), TXshLevel::getType(), ToonzScene::getXsheet(), IoCmd::LoadResourceArguments::importPolicy, TApp::instance(), ToonzScene::isExternPath(), IoCmd::LoadResourceArguments::loadedLevels, loadResourceFolders(), LoadScopedBlock::Data::m_hasSoundLevel, LoadScopedBlock::Data::m_loadedCount, IoCmd::LoadResourceArguments::ResourceData::m_path, IoCmd::LoadResourceArguments::ScopedBlock::progressDialog(), IoCmd::LoadResourceArguments::resourceDatas, IoCmd::LoadResourceArguments::row0, IoCmd::LoadResourceArguments::row1, and TFilePath::withParentDir().
Referenced by LoadLevelPopup::execute(), SaveLevelAsPopup::execute(), ReplaceLevelPopup::execute(), and loadResourceFolders().
loadScene() [1/3]
bool IoCmd::loadScene ()
                      {
  TSelection *oldSelection =
      TApp::instance()->getCurrentSelection()->getSelection();
  FileSelection *fileSelection =
      dynamic_cast<FileSelection *>(TSelection::getCurrent());
  if (fileSelection) {
    std::vector<TFilePath> files;
    fileSelection->getSelectedFiles(files);
    if (files.size() == 1 && files[0] != TFilePath() &&
        files[0].getType() == "tnz")
      return loadScene(files[0]);
  }
  static LoadScenePopup *popup = 0;
  if (!popup) {
    popup = new LoadScenePopup();
  }
  int ret = popup->exec();
  if (ret == QDialog::Accepted) {
    return true;
  } else {
    TApp::instance()->getCurrentSelection()->setSelection(oldSelection);
    return false;
  }
}
loadScene() [2/3]
bool IoCmd::loadScene (const TFilePath & scenePath, bool updateRecentFile = true, bool checkSaveOldScene = true)
{
  RenderingSuspender suspender;
  if (checkSaveOldScene)
    if (!saveSceneIfNeeded(QApplication::tr("Load Scene"))) return false;
  assert(!path.isEmpty());
  TFilePath scenePath = path;
  bool importScene    = false;
  bool isXdts         = scenePath.getType() == "xdts";
  if (scenePath.getType() == "") scenePath = scenePath.withType("tnz");
  if (scenePath.getType() != "tnz" && !isXdts) {
    QString msg;
    msg = QObject::tr("File %1 doesn't look like a TOONZ Scene")
              .arg(QString::fromStdWString(scenePath.getWideString()));
    DVGui::error(msg);
    return false;
  }
  if (!TSystem::doesExistFileOrLevel(scenePath)) return false;
  TFilePath scenePathTemp(scenePath.getWideString() +
                          QString(".tmp").toStdWString());
  if (TSystem::doesExistFileOrLevel(scenePathTemp)) {
    QString question =
        QObject::tr(
            "A prior save of Scene '%1' was critically interrupted. \n\
\nA partial save file was generated and changes may be manually salvaged from '%2'.\n\
\nDo you wish to continue loading the last good save or stop and try to salvage the prior save?")
            .arg(QString::fromStdWString(scenePath.getWideString()))
            .arg(QString::fromStdWString(scenePathTemp.getWideString()));
    QString continueAnswer = QObject::tr("Continue");
    QString cancelAnswer   = QObject::tr("Cancel");
    int ret = DVGui::MsgBox(question, continueAnswer, cancelAnswer, 0);
    if (ret == 2)
      return false;
    else
      TSystem::removeFileOrLevel(scenePathTemp);
  }
  TProjectManager *pm    = TProjectManager::instance();
  TProjectP sceneProject = pm->loadSceneProject(scenePath);
  if (!sceneProject) {
    QString msg;
    msg = QObject::tr(
              "It is not possible to load the scene %1 because it does not "
              "belong to any project.")
              .arg(QString::fromStdWString(scenePath.getWideString()));
    DVGui::warning(msg);
  }
  if (sceneProject && !sceneProject->isCurrent()) {
    QString currentProjectName = QString::fromStdWString(
        pm->getCurrentProject()->getName().getWideString());
    QString sceneProjectName =
        QString::fromStdWString(sceneProject->getName().getWideString());
    /*QString question = "The Scene '"
            + QString::fromStdWString(scenePath.getWideString())
+ "' belongs to project '" + sceneProjectName + "'.\n"
+ "What do you want to do?";*/
    QString question =
        QObject::tr(
            "The Scene '%1' belongs to project '%2'.\nWhat do you want to do?")
            .arg(QString::fromStdWString(scenePath.getWideString()))
            .arg(sceneProjectName);
    QString importAnswer        = QObject::tr("Import Scene");
    QString switchProjectAnswer = QObject::tr("Change Project");
    QString cancelAnswer        = QObject::tr("Cancel");
    int ret = DVGui::MsgBox(question, importAnswer, switchProjectAnswer,
                            cancelAnswer, 0);
    if (ret == 3 || ret == 0) {
      newScene();
      return false;
    }
    if (ret == 2)
      pm->setCurrentProjectPath(sceneProject->getProjectPath());
    else
      importScene = true;
  }
  QApplication::setOverrideCursor(Qt::WaitCursor);
  TUndoManager::manager()->reset();
  IconGenerator::instance()->clearRequests();
  IconGenerator::instance()->clearSceneIcons();
  ImageManager::instance()->clear();
  CacheFxCommand::instance()->onNewScene();
#ifdef USE_SQLITE_HDPOOL
  // INTERMEDIATE CACHE RESULTS MANAGEMENT: Clear all resources not accessed in
  // the last 2 sessions
  TCacheResourcePool::instance()->clearAccessedAfterSessions(
      1);  // 0 would be after this session
#endif
  ToonzScene *scene = new ToonzScene();
  TImageStyle::setCurrentScene(scene);
  printf("%s:%s Progressing:\n", __FILE__, __FUNCTION__);
  try {
    if (isXdts)
      XdtsIo::loadXdtsScene(scene, scenePath);
    else
      /*-- Load --*/
      scene->load(scenePath);
    // import if needed
    TProjectManager *pm      = TProjectManager::instance();
    TProjectP currentProject = pm->getCurrentProject();
    if (!scene->getProject() || scene->getProject()->getProjectPath() !=
                                    currentProject->getProjectPath()) {
      ResourceImportDialog resourceLoader;
      // resourceLoader.setImportEnabled(true);
      ResourceImporter importer(scene, currentProject.getPointer(),
                                resourceLoader);
      SceneResources resources(scene, scene->getXsheet());
      resources.accept(&importer);
      scene->setScenePath(importer.getImportedScenePath());
      scene->setProject(currentProject.getPointer());
    }
    VersionControlManager::instance()->setFrameRange(scene->getLevelSet());
  } catch (...) {
    printf("%s:%s Exception ...:\n", __FILE__, __FUNCTION__);
    QString msg;
    msg = QObject::tr(
              "There were problems loading the scene %1.\n Some files may be "
              "missing.")
              .arg(QString::fromStdWString(scenePath.getWideString()));
    DVGui::warning(msg);
  }
  printf("%s:%s end load:\n", __FILE__, __FUNCTION__);
  TProject *project = scene->getProject();
  if (!project) {
    project = new TProject();
    project->setFolder("project", scenePath);
    scene->setProject(project);
  }
  TApp *app = TApp::instance();
  app->getCurrentScene()->setScene(scene);
  app->getCurrentScene()->notifyNameSceneChange();
  app->getCurrentFrame()->setFrame(0);
  app->getCurrentColumn()->setColumnIndex(0);
  TPalette *palette = 0;
  if (app->getCurrentLevel() && app->getCurrentLevel()->getSimpleLevel())
    palette = app->getCurrentLevel()->getSimpleLevel()->getPalette();
  app->getCurrentPalette()->setPalette(palette);
  app->getCurrentXsheet()->notifyXsheetSoundChanged();
  app->getCurrentObject()->setIsSpline(false);
  Previewer::clearAll();
  PreviewFxManager::instance()->reset();
  // updateCleanupSettingsPopup();
  /*- CleanupParameter -*/
  CleanupParameters *cp = scene->getProperties()->getCleanupParameters();
  CleanupParameters::GlobalParameters.assign(cp);
  CacheFxCommand::instance()->onSceneLoaded();
#ifdef USE_SQLITE_HDPOOL
  TCacheResourcePool::instance()->setPath(
      QString::fromStdWString(
          ToonzFolder::getCacheRootFolder().getWideString()),
      QString::fromStdWString(project->getName().getWideName()),
      QString::fromStdWString(scene->getSceneName()));
#endif
  UnitParameters::setFieldGuideAspectRatio(
      scene->getProperties()->getFieldGuideAspectRatio());
  IconGenerator::instance()->invalidateSceneIcon();
  DvDirModel::instance()->refreshFolder(scenePath.getParentDir());
  // set dirty for xdts files since converted tnz is not yet saved
  TApp::instance()->getCurrentScene()->setDirtyFlag(isXdts);
  History::instance()->addItem(scenePath);
  if (updateRecentFile)
    RecentFiles::instance()->addFilePath(
        toQString(scenePath), RecentFiles::Scene,
        QString::fromStdString(scene->getProject()->getName().getName()));
  QApplication::restoreOverrideCursor();
  int forbiddenLevelCount = 0;
  for (int i = 0; i < scene->getLevelSet()->getLevelCount(); i++) {
    TXshLevel *xl = scene->getLevelSet()->getLevel(i);
    if (xl && xl->getSimpleLevel() &&
        xl->getSimpleLevel()->getProperties()->isForbidden())
      forbiddenLevelCount++;
  }
  if (forbiddenLevelCount > 0) {
    QString msg;
    msg = QObject::tr(
              "There were problems loading the scene %1.\nSome levels have not "
              "been loaded because their version is not supported")
              .arg(QString::fromStdWString(scenePath.getWideString()));
    DVGui::warning(msg);
  }
  bool exist = TSystem::doesExistFileOrLevel(
      scene->decodeFilePath(scene->getScenePath()));
  QAction *act = CommandManager::instance()->getAction(MI_RevertScene);
  if (act) act->setEnabled(exist);
  // check if the output dpi is incompatible with pixels only mode
  if (Preferences::instance()->getPixelsOnly()) {
    TPointD dpi = scene->getCurrentCamera()->getDpi();
    if (!areAlmostEqual(dpi.x, Stage::standardDpi, 0.1) ||
        !areAlmostEqual(dpi.y, Stage::standardDpi, 0.1)) {
      QString question = QObject::tr(
          "This scene is incompatible with pixels only mode of the current "
          "OpenToonz version.\nWhat would you like to do?");
      QString turnOffPixelAnswer = QObject::tr("Turn off pixels only mode");
      QString resizeSceneAnswer =
          QObject::tr("Keep pixels only mode on and resize the scene");
      int ret =
          DVGui::MsgBox(question, turnOffPixelAnswer, resizeSceneAnswer, 0);
      if (ret == 0) {
      }                     // do nothing
      else if (ret == 1) {  // Turn off pixels only mode
        Preferences::instance()->setValue(pixelsOnly, false);
        app->getCurrentScene()->notifyPixelUnitSelected(false);
      } else {  // ret = 2 : Resize the scene
        TDimensionD camSize = scene->getCurrentCamera()->getSize();
        TDimension camRes(camSize.lx * Stage::standardDpi,
                          camSize.ly * Stage::standardDpi);
        scene->getCurrentCamera()->setRes(camRes);
        app->getCurrentScene()->setDirtyFlag(true);
        app->getCurrentXsheet()->notifyXsheetChanged();
      }
    }
  }
  // Check if the scene saved with the previous version AND the premultiply
  // option is set to PNG level setting
  if (scene->getVersionNumber() <
      VersionNumber(71, 1)) {  // V1.4 = 71.0 , V1.5 = 71.1
    QStringList modifiedPNGLevelNames;
    std::vector<TXshLevel *> levels;
    scene->getLevelSet()->listLevels(levels);
    for (auto level : levels) {
      if (!level || !level->getSimpleLevel()) continue;
      TFilePath path = level->getPath();
      if (path.isEmpty() || path.getType() != "png") continue;
      if (level->getSimpleLevel()->getProperties()->doPremultiply()) {
        level->getSimpleLevel()->getProperties()->setDoPremultiply(false);
        modifiedPNGLevelNames.append(QString::fromStdWString(level->getName()));
      }
    }
    if (!modifiedPNGLevelNames.isEmpty()) {
      DVGui::info(QObject::tr("The Premultiply options in the following levels "
                              "are disabled, since PNG files are premultiplied "
                              "on loading in the current version: %1")
                      .arg(modifiedPNGLevelNames.join(", ")));
      app->getCurrentScene()->setDirtyFlag(true);
    }
  }
  printf("%s:%s loadScene() completed :\n", __FILE__, __FUNCTION__);
  return true;
}
loadScene() [3/3]
bool IoCmd::loadScene (ToonzScene & scene, const TFilePath & scenePath, bool import)
{
  if (!TSystem::doesExistFileOrLevel(scenePath)) return false;
  scene.load(scenePath);
  // import if needed
  TProjectManager *pm      = TProjectManager::instance();
  TProjectP currentProject = pm->getCurrentProject();
  if (!scene.getProject()) return false;
  if (scene.getProject()->getProjectPath() !=
      currentProject->getProjectPath()) {
    ResourceImportDialog resourceLoader;
    // resourceLoader.setImportEnabled(true);
    ResourceImporter importer(&scene, currentProject.getPointer(),
                              resourceLoader);
    SceneResources resources(&scene, scene.getXsheet());
    resources.accept(&importer);
    scene.setScenePath(importer.getImportedScenePath());
    scene.setProject(currentProject.getPointer());
  }
  return true;
}
loadSubScene() [1/2]
bool IoCmd::loadSubScene ()
{
  TSelection *oldSelection =
      TApp::instance()->getCurrentSelection()->getSelection();
  FileSelection *fileSelection =
      dynamic_cast<FileSelection *>(TSelection::getCurrent());
  if (fileSelection) {
    IoCmd::LoadResourceArguments args;
    {
      std::vector<TFilePath> filePaths;
      fileSelection->getSelectedFiles(filePaths);
      args.resourceDatas.assign(filePaths.begin(), filePaths.end());
    }
    if (args.resourceDatas.size() == 1 &&
        args.resourceDatas[0].m_path != TFilePath() &&
        args.resourceDatas[0].m_path.getType() == "tnz") {
      loadResources(args);
      return true;
    }
  } else {
    static LoadSubScenePopup *popup = 0;
    if (!popup) {
      popup = new LoadSubScenePopup();
      popup->addFilterType("tnz");
    }
    int ret = popup->exec();
    if (ret == QDialog::Accepted) {
      TApp::instance()->getCurrentScene()->setDirtyFlag(false);
      return true;
    } else {
      TApp::instance()->getCurrentSelection()->setSelection(oldSelection);
      return false;
    }
  }
  return false;
}
loadSubScene() [2/2]
bool IoCmd::loadSubScene (const TFilePath & scenePath)
{
  IoCmd::LoadResourceArguments args(scenePath);
  if (args.resourceDatas.size() == 1 &&
      args.resourceDatas[0].m_path != TFilePath() &&
      args.resourceDatas[0].m_path.getType() == "tnz") {
    loadResources(args);
    return true;
  }
  return false;
}
newScene()
void IoCmd::newScene ()
                     {
  RenderingSuspender suspender;
  TApp *app        = TApp::instance();
  double cameraDpi = 120;  // used to be 64 and 53.33333
  if (!saveSceneIfNeeded(QApplication::tr("New Scene"))) return;
  IconGenerator::instance()->clearRequests();
  IconGenerator::instance()->clearSceneIcons();
  ImageManager::instance()->clear();
  FullColorPalette::instance()->clear();
  CacheFxCommand::instance()->onNewScene();
  CacheFxCommand::instance()->onSceneLoaded();
#ifdef USE_SQLITE_HDPOOL
  // INTERMEDIATE CACHE RESULTS MANAGEMENT: Clear all resources not accessed in
  // the last 2 sessions
  TCacheResourcePool::instance()->clearAccessedAfterSessions(
      1);  // 0 would be after this session
#endif
  ToonzScene *scene = new ToonzScene();
  TImageStyle::setCurrentScene(scene);
  TCamera *camera = scene->getCurrentCamera();
  TDimension res(1920, 1080);
  // TDimension res(768, 576);
  camera->setRes(res);
  camera->setSize(
      TDimensionD((double)res.lx / cameraDpi, (double)res.ly / cameraDpi));
  scene->getProperties()->setBgColor(TPixel32::White);
  TProjectManager::instance()->initializeScene(scene);
  if (Preferences::instance()->getPixelsOnly()) {
    TCamera *updateCamera = scene->getCurrentCamera();
    TDimension updateRes  = updateCamera->getRes();
    updateCamera->setSize(TDimensionD((double)updateRes.lx / cameraDpi,
                                      (double)updateRes.ly / cameraDpi));
  }
  // Must set current scene after initializeScene!!
  app->getCurrentScene()->setScene(scene);
  // initializeScene() load project cleanup palette: set it to cleanup palette
  // handle.
  TPalette *palette = scene->getProperties()
                          ->getCleanupParameters()
                          ->m_cleanupPalette.getPointer();
  PaletteController *paletteController = app->getPaletteController();
  paletteController->getCurrentCleanupPalette()->setPalette(palette, -1);
  paletteController->editLevelPalette();
  TFilePath scenePath = scene->getScenePath();
  DvDirModel::instance()->refreshFolder(scenePath.getParentDir());
  Previewer::clearAll();
  PreviewFxManager::instance()->reset();
  app->getCurrentScene()->notifyNameSceneChange();
  IconGenerator::instance()->invalidateSceneIcon();
  ToolHandle *toolH = TApp::instance()->getCurrentTool();
  if (toolH && toolH->getTool()) toolH->getTool()->reset();
  CommandManager::instance()->execute("T_Hand");
  CommandManager::instance()->enable(MI_SaveSubxsheetAs, false);
  app->getCurrentScene()->notifySceneChanged();
  app->getCurrentScene()->setDirtyFlag(false);
  app->getCurrentObject()->setIsSpline(false);
  app->getCurrentColumn()->setColumnIndex(0);
  CleanupParameters *cp = scene->getProperties()->getCleanupParameters();
  CleanupParameters::GlobalParameters.assign(cp);
  // updateCleanupSettingsPopup();
  CleanupPreviewCheck::instance()->setIsEnabled(false);
  CameraTestCheck::instance()->setIsEnabled(false);
  SetScanCropboxCheck::instance()->setIsEnabled(false);
  if (!TApp::instance()->isApplicationStarting())
    QApplication::clipboard()->clear();
  TSelection::setCurrent(0);
  TUndoManager::manager()->reset();
  bool exist = TSystem::doesExistFileOrLevel(
      scene->decodeFilePath(scene->getScenePath()));
  QAction *act = CommandManager::instance()->getAction(MI_RevertScene);
  if (act) act->setEnabled(exist);
}
saveAll()
bool IoCmd::saveAll (int flags = 0)
{
  // try to save as much as possible
  // if anything is wrong, return false
  bool result = saveScene(flags);
  TApp *app         = TApp::instance();
  ToonzScene *scene = app->getCurrentScene()->getScene();
  bool untitled     = scene->isUntitled();
  SceneResources resources(scene, 0);
  resources.save(scene->getScenePath());
  resources.updatePaths();
  // for update title bar
  app->getCurrentLevel()->notifyLevelTitleChange();
  app->getCurrentPalette()->notifyPaletteTitleChanged();
  if (untitled) scene->setUntitled();
  return result;
}
saveLevel() [1/4]
bool IoCmd::saveLevel ()
                      {
  TApp *app = TApp::instance();
  TXshSimpleLevel *sl =
      dynamic_cast<TXshSimpleLevel *>(app->getCurrentLevel()->getLevel());
  if (!sl) return false;
  if (sl->getPath() == TFilePath()) return false;
  TFilePath path =
      app->getCurrentScene()->getScene()->decodeFilePath(sl->getPath());
  if (path == TFilePath()) return false;
  if (path.getWideString()[0] == L'+') return false;
  if (!path.isAbsolute()) return false;
  if (!saveLevel(path, sl, true)) return false;
  sl->setDirtyFlag(false);
  // for update title bar
  app->getCurrentLevel()->notifyLevelChange();
  return true;
}
saveLevel() [2/4]
bool IoCmd::saveLevel (const TFilePath & fp)
{
  assert(!path.isEmpty());
  TApp *app = TApp::instance();
  TXshSimpleLevel *sl =
      dynamic_cast<TXshSimpleLevel *>(app->getCurrentLevel()->getLevel());
  if (!sl) return false;
  std::string ext    = sl->getPath().getType();
  std::string dotts  = sl->getPath().getDots();
  TFilePath realPath = path;
  if (realPath.getType() == "")
    realPath = TFilePath(realPath.getWideString() + ::to_wstring(dotts + ext));
  bool ret = saveLevel(realPath, sl, false);
  if (!ret) {  // save level failed
    return false;
  }
  RecentFiles::instance()->addFilePath(toQString(realPath), RecentFiles::Level);
  TApp::instance()
      ->getPaletteController()
      ->getCurrentLevelPalette()
      ->notifyPaletteSwitched();
  return true;
}
saveLevel() [3/4]
bool IoCmd::saveLevel (const TFilePath & fp, TXshSimpleLevel * sl, bool overwrite)
{
  assert(sl);
  bool fileDoesExist = TSystem::doesExistFileOrLevel(fp);
  if (!overwrite && fileDoesExist) {
    QString question;
    question = QObject::tr(
                   "The level %1 already exists.\nDo you want to overwrite it?")
                   .arg(toQString(fp));
    int ret = DVGui::MsgBox(question, QObject::tr("Overwrite"),
                            QObject::tr("Cancel"), 0);
    if (ret == 2 || ret == 0) return false;
  }
  bool overwritePalette = false;
  // Confirmation of Overwrite palette
  // open dialog IF  1) the level is dirty, and 2) confirmation of overwrite
  // palette haven't been asked
  // for PLI file, do nothing
  if (sl->getPalette() && sl->getPalette()->getAskOverwriteFlag() &&
      sl->getPath().getType() != "pli") {
    /*--  --*/
    if (!fileDoesExist)
      overwritePalette = true;
    else {
      QString question;
      question =
          "Palette " +
          QString::fromStdWString(sl->getPalette()->getPaletteName()) +
          ".tpl has been modified. Do you want to overwrite palette as well ?";
      int ret =
          DVGui::MsgBox(question, QObject::tr("Overwrite Palette") /*ret = 1*/,
                        QObject::tr("Don't Overwrite Palette") /*ret = 2*/, 0);
      if (ret == 1) overwritePalette = true;
    }
  }
  QApplication::setOverrideCursor(Qt::WaitCursor);
  try {
    sl->save(fp, TFilePath(), overwritePalette);
  } catch (TSystemException se) {
    QApplication::restoreOverrideCursor();
    DVGui::warning(QString::fromStdWString(se.getMessage()));
    return false;
  } catch (...) {
    QApplication::restoreOverrideCursor();
    DVGui::error(QObject::tr("Couldn't save %1").arg(toQString(fp)));
    return false;
  }
  IconGenerator::instance()->invalidate(fp);
  FileBrowser::refreshFolder(fp.getParentDir());
  History::instance()->addItem(fp);
  if (sl->getPalette()) {
    if (overwritePalette || sl->getPath().getType() == "pli")
      sl->getPalette()->setDirtyFlag(false);
    else  // ask only once for save palette
      sl->getPalette()->setAskOverwriteFlag(false);
  }
  RecentFiles::instance()->addFilePath(toQString(fp), RecentFiles::Level);
  QApplication::restoreOverrideCursor();
  TApp::instance()->getCurrentLevel()->notifyLevelTitleChange();
  TApp::instance()
      ->getPaletteController()
      ->getCurrentLevelPalette()
      ->notifyPaletteTitleChanged();
  return true;
}
saveLevel() [4/4]
bool IoCmd::saveLevel (TXshSimpleLevel * sl)
{
  return saveLevel(sl->getPath(), sl, true);
}
saveNonSceneFiles()
void IoCmd::saveNonSceneFiles ()
{
  // try to save non scene files
  TApp *app         = TApp::instance();
  ToonzScene *scene = app->getCurrentScene()->getScene();
  bool untitled     = scene->isUntitled();
  SceneResources resources(scene, 0);
  resources.save(scene->getScenePath());
  if (untitled) scene->setUntitled();
  resources.updatePaths();
  // for update title bar
  app->getCurrentLevel()->notifyLevelTitleChange();
  app->getCurrentPalette()->notifyPaletteTitleChanged();
}
saveScene() [1/2]
bool IoCmd::saveScene (const TFilePath & fp, int flags)
{
  bool overwrite     = (flags & SILENTLY_OVERWRITE) != 0;
  bool saveSubxsheet = (flags & SAVE_SUBXSHEET) != 0;
  bool isAutosave    = (flags & AUTO_SAVE) != 0;
  TApp *app          = TApp::instance();
  assert(!path.isEmpty());
  TFilePath scenePath = path;
  if (scenePath.getType() == "") scenePath = scenePath.withType("tnz");
  if (scenePath.getType() != "tnz") {
    error(
        QObject::tr("%1 has an invalid file extension.").arg(toQString(path)));
    return false;
  }
  TFileStatus dirStatus(scenePath.getParentDir());
  if (!(dirStatus.doesExist() && dirStatus.isWritable())) {
    error(QObject::tr("%1 is an invalid path.")
              .arg(toQString(scenePath.getParentDir())));
    return false;
  }
  // notify user if the scene will be saved including any "broken" expression
  // reference
  if (!ExpressionReferenceManager::instance()->askIfParamIsIgnoredOnSave(
          saveSubxsheet))
    return false;
  if (!overwrite && TFileStatus(scenePath).doesExist()) {
    QString question;
    question = QObject::tr(
                   "The scene %1 already exists.\nDo you want to overwrite it?")
                   .arg(QString::fromStdString(scenePath.getName()));
    int ret = DVGui::MsgBox(question, QObject::tr("Overwrite"),
                            QObject::tr("Cancel"), 0);
    if (ret == 2 || ret == 0) return false;
  }
  ToonzScene *scene = TApp::instance()->getCurrentScene()->getScene();
  TXsheet *xsheet = 0;
  if (saveSubxsheet) xsheet = TApp::instance()->getCurrentXsheet()->getXsheet();
  // Automatically remove unused levels
  if (!saveSubxsheet && !isAutosave &&
      Preferences::instance()->isAutoRemoveUnusedLevelsEnabled()) {
    if (LevelCmd::removeUnusedLevelsFromCast(false))
      DVGui::info(
          QObject::tr("Removed unused levels from the scene cast. (This "
                      "behavior can be disabled in Preferences.)"));
  }
  // If the scene will be saved in the different folder, check out the scene
  // cast.
  // if the cast contains the level specified with $scenefolder alias,
  // open a warning popup notifying that such level will lose link.
  // in case of saving subxsheet, the current scene will not be switched to the
  // saved one
  // so the level paths are needed to be reverted after saving
  QHash<TXshLevel *, TFilePath> orgLevelPaths;
  auto revertOrgLevelPaths = [&] {
    QHash<TXshLevel *, TFilePath>::const_iterator i =
        orgLevelPaths.constBegin();
    while (i != orgLevelPaths.constEnd()) {
      if (TXshSimpleLevel *sil = i.key()->getSimpleLevel())
        sil->setPath(i.value(), true);
      else if (TXshPaletteLevel *pal = i.key()->getPaletteLevel())
        pal->setPath(i.value());
      else if (TXshSoundLevel *sol = i.key()->getSoundLevel())
        sol->setPath(i.value());
      ++i;
    }
  };
  if (!overwrite) {
    bool ret = takeCareSceneFolderItemsOnSaveSceneAs(scene, scenePath, xsheet,
                                                     orgLevelPaths);
    if (!ret) {
      revertOrgLevelPaths();
      return false;
    }
  }
  TFilePath oldFullPath = scene->decodeFilePath(scene->getScenePath());
  TFilePath newFullPath = scene->decodeFilePath(scenePath);
  QApplication::setOverrideCursor(Qt::WaitCursor);
  if (app->getCurrentScene()->getDirtyFlag())
    scene->getContentHistory(true)->modifiedNow();
  if (oldFullPath != newFullPath) {
    IconGenerator::instance()->clearRequests();
    IconGenerator::instance()->clearSceneIcons();
#ifdef USE_SQLITE_HDPOOL
    // Open the new cache resources HD pool
    TCacheResourcePool::instance()->setPath(
        QString::fromStdWString(
            ToonzFolder::getCacheRootFolder().getWideString()),
        QString::fromStdWString(scene->getProject()->getName().getWideName()),
        QString::fromStdWString(scene->getSceneName()));
#endif
  }
  CleanupParameters *cp = scene->getProperties()->getCleanupParameters();
  CleanupParameters oldCP(*cp);
  cp->assign(&CleanupParameters::GlobalParameters);
  try {
    scene->save(scenePath, xsheet);
  } catch (const TSystemException &se) {
    DVGui::warning(QString::fromStdWString(se.getMessage()));
  } catch (...) {
    DVGui::error(QObject::tr("Couldn't save %1").arg(toQString(scenePath)));
  }
  cp->assign(&oldCP);
  // in case of saving subxsheet, revert the level paths after saving
  revertOrgLevelPaths();
  if (!overwrite && !saveSubxsheet)
    app->getCurrentScene()->notifyNameSceneChange();
  FileBrowser::refreshFolder(scenePath.getParentDir());
  IconGenerator::instance()->invalidate(scenePath);
  // Le seguenti notifiche non cambiano il dirty flag del livello o della
  // paletta
  // ma sono necessarie per aggiornare le titlebar dei pannelli.
  app->getCurrentLevel()->notifyLevelTitleChange();
  app->getCurrentPalette()->notifyPaletteTitleChanged();
  app->getCurrentScene()->setDirtyFlag(false);
  History::instance()->addItem(scenePath);
  RecentFiles::instance()->addFilePath(
      toQString(scenePath), RecentFiles::Scene,
      QString::fromStdString(app->getCurrentScene()
                                 ->getScene()
                                 ->getProject()
                                 ->getName()
                                 .getName()));
  QApplication::restoreOverrideCursor();
  bool exist = TSystem::doesExistFileOrLevel(
      scene->decodeFilePath(scene->getScenePath()));
  QAction *act = CommandManager::instance()->getAction(MI_RevertScene);
  if (act) act->setEnabled(exist);
  return true;
}
saveScene() [2/2]
bool IoCmd::saveScene (int flags = 0)
{
  TSelection *oldSelection =
      TApp::instance()->getCurrentSelection()->getSelection();
  ToonzScene *scene = TApp::instance()->getCurrentScene()->getScene();
  if (scene->isUntitled()) {
    static SaveSceneAsPopup *popup = 0;
    if (!popup) popup = new SaveSceneAsPopup();
    int ret = popup->exec();
    if (ret == QDialog::Accepted) {
      TApp::instance()->getCurrentScene()->setDirtyFlag(false);
      return true;
    } else {
      TApp::instance()->getCurrentSelection()->setSelection(oldSelection);
      return false;
    }
  } else {
    TFilePath fp = scene->getScenePath();
    // salva la scena con il nome fp. se fp esiste gia' lo sovrascrive
    return saveScene(fp, SILENTLY_OVERWRITE | flags);
  }
}
saveSceneIfNeeded()
bool IoCmd::saveSceneIfNeeded (QString msg)
{
  TApp *app = TApp::instance();
  if (app->getCurrentScene()->getDirtyFlag()) {
    QString question;
    question = QObject::tr(
                   "%1: the current scene has been modified.\n"
                   "What would you like to do?")
                   .arg(msg);
    int ret = DVGui::MsgBox(
        question, QObject::tr("Save All"), QObject::tr("Save Scene Only"),
        QObject::tr("Discard Changes"), QObject::tr("Cancel"), 0);
    if (ret == 0 || ret == 4) {
      // cancel (or closed message box window)
      return false;
    } else if (ret == 1) {
      // save all
      if (!IoCmd::saveAll()) return false;
    } else if (ret == 2) {
      // save
      if (!IoCmd::saveScene()) return false;
    } else if (ret == 3) {
    }
  }
  ToonzScene *scene = app->getCurrentScene()->getScene();
  if (scene) {
    QStringList dirtyResources;
    {
      SceneResources resources(scene, 0);
      resources.getDirtyResources(dirtyResources);
    }
    if (!dirtyResources.empty()) {
      // show up to 5 items
      int extraCount = dirtyResources.count() - 5;
      if (extraCount > 0) {
        dirtyResources = dirtyResources.mid(0, 5);
        dirtyResources.append(
            QObject::tr("and %1 more item(s).").arg(extraCount));
      }
      QString question;
      question = msg + ":" +
                 QObject::tr(" The following file(s) have been modified.\n\n");
      question += "  " + dirtyResources.join("\n  ");
      question += "\n" + QObject::tr("\nWhat would you like to do? ");
      int ret =
          DVGui::MsgBox(question, QObject::tr("Save Changes"),
                        msg + QObject::tr(" Anyway"), QObject::tr("Cancel"), 0);
      if (ret == 0 || ret == 3) {
        // cancel (or closed message box window)
        return false;
      } else if (ret == 1) {
        // save non scene files
        IoCmd::saveNonSceneFiles();
      } else if (ret == 2) {
        // do nothing and continue
      }
    }
    RenderingSuspender suspender;
    TFilePath scenePath(scene->getScenePath());
    scene->clear();  // note: this (possibly) removes the "untitled" folder
    app->getCurrentScene()->notifyCastChange();
    // Si deve notificare anche il cambiamento che ha subito l'xsheet.
    app->getCurrentXsheet()->notifyXsheetSwitched();
    FileBrowser::refreshFolder(scenePath.getParentDir());
  }
  app->getCurrentScene()->setDirtyFlag(false);
  return true;
}
saveSound() [1/2]
bool IoCmd::saveSound (const TFilePath & fp, TXshSoundLevel * sc, bool overwrite)
{
  if (!overwrite && TSystem::doesExistFileOrLevel(fp)) {
    QString question;
    question =
        QObject::tr(
            "The soundtrack %1 already exists.\nDo you want to overwrite it?")
            .arg(toQString(fp));
    int ret = DVGui::MsgBox(question, QObject::tr("Overwrite"),
                            QObject::tr("Cancel"), 0);
    if (ret == 2 || ret == 0) return false;
  }
  try {
    sl->save(fp);
  } catch (...) {
    DVGui::error(QObject::tr("Couldn't save %1").arg(toQString(fp)));
    return false;
  }
  QApplication::setOverrideCursor(Qt::WaitCursor);
  FileBrowser::refreshFolder(fp.getParentDir());
  History::instance()->addItem(fp);
  QApplication::restoreOverrideCursor();
  return true;
}
saveSound() [2/2]
bool IoCmd::saveSound (TXshSoundLevel * sc)
{
  return saveSound(sl->getPath(), sl, true);
}
takeCareSceneFolderItemsOnSaveSceneAs()
bool IoCmd::takeCareSceneFolderItemsOnSaveSceneAs (ToonzScene * scene, const TFilePath & newPath, TXsheet * subxsh, QHash< TXshLevel *, TFilePath > & orgLevelPaths)
{
  auto setPathToLevel = [&](TXshLevel *level, TFilePath fp) {
    // in case of saving subxsheet, the current scene will not be switched to
    // the saved one
    // so the level paths are needed to be reverted after saving
    if (subxsh) orgLevelPaths.insert(level, level->getPath());
    if (TXshSimpleLevel *sil = level->getSimpleLevel())
      sil->setPath(fp, true);
    else if (TXshPaletteLevel *pal = level->getPaletteLevel())
      pal->setPath(fp);
    else if (TXshSoundLevel *sol = level->getSoundLevel())
      sol->setPath(fp);
  };
  TFilePath oldSceneFolder =
      scene->decodeFilePath(scene->getScenePath()).getParentDir();
  TFilePath newSceneFolder = scene->decodeFilePath(newPath).getParentDir();
  // in case of saving in the same folder
  if (oldSceneFolder == newSceneFolder) return true;
  TLevelSet *levelSet = scene->getLevelSet();
  std::vector<TXshLevel *> levels;
  // in case of saving subxsheet, checking only used levels.
  if (subxsh) {
    std::set<TXshLevel *> saveSet;
    subxsh->getUsedLevels(saveSet);
    levels = std::vector<TXshLevel *>(saveSet.begin(), saveSet.end());
  }
  // in case of saving the scene (i.e. top xsheet)
  else
    levelSet->listLevels(levels);
  QList<TXshLevel *> sceneFolderLevels;
  QString str;
  int count = 0;
  for (TXshLevel *level : levels) {
    if (!level->getPath().isEmpty() &&
        TFilePath("$scenefolder").isAncestorOf(level->getPath())) {
      TFilePath levelFullPath = scene->decodeFilePath(level->getPath());
      // check if the path can be re-coded with the new scene folder path
      if (newSceneFolder.isAncestorOf(levelFullPath)) {
        // just replace the path without warning
        TFilePath fp =
            TFilePath("$scenefolder") + (levelFullPath - newSceneFolder);
        setPathToLevel(level, fp);
      }
      // if re-coding is not possible, then it needs to ask user's preference
      else {
        sceneFolderLevels.append(level);
        if (count < 10) {
          str.append("    " + QString::fromStdWString(level->getName()) + " (" +
                     level->getPath().getQString() + ")\n");
        }
        count++;
      }
    }
  }
  // list maximum 10 levels
  if (count > 10)
    str.append(QObject::tr("    + %1 more level(s) \n").arg(count - 10));
  // in case there is no items with $scenefolder
  if (sceneFolderLevels.isEmpty()) return true;
  str = QObject::tr(
            "The following level(s) use path with $scenefolder alias.\n\n") +
        str +
        QObject::tr(
            "\nThey will not be opened properly when you load the "
            "scene next time.\nWhat do you want to do?");
  int ret = DVGui::MsgBox(
      str, QObject::tr("Copy the levels to correspondent paths"),
      QObject::tr("Decode all $scenefolder aliases"),
      QObject::tr("Save the scene only"), QObject::tr("Cancel"), 0);
  if (ret == 4 || ret == 0) return false;
  if (ret == 1) {  // copy the levels case
    enum OVERWRITEPOLICY { ASK, YES_FOR_ALL, NO_FOR_ALL } policy = ASK;
    for (int i = 0; i < sceneFolderLevels.size(); i++) {
      TXshLevel *level = sceneFolderLevels.at(i);
      TFilePath fp     = level->getPath() - TFilePath("$scenefolder");
      fp               = fp.withParentDir(newSceneFolder);
      // check the level existence
      if (TSystem::doesExistFileOrLevel(fp)) {
        bool overwrite = (policy == YES_FOR_ALL);
        if (policy == ASK) {
          QString question =
              QObject::tr(
                  "File %1 already exists.\nDo you want to overwrite it?")
                  .arg(fp.getQString());
          int ret_overwrite = DVGui::MsgBox(
              question, QObject::tr("Overwrite"),
              QObject::tr("Overwrite for All"), QObject::tr("Don't Overwrite"),
              QObject::tr("Don't Overwrite for All"), 0);
          if (ret_overwrite == 0) return false;
          if (ret_overwrite == 1)
            overwrite = true;
          else if (ret_overwrite == 2) {
            overwrite = true;
            policy    = YES_FOR_ALL;
          } else if (ret_overwrite == 4)
            policy = NO_FOR_ALL;
        }
        if (!overwrite) continue;
      }
      TFilePath srcFp = scene->decodeFilePath(level->getPath());
      if (!TSystem::copyFileOrLevel(fp, srcFp))
        warning(QObject::tr("Failed to overwrite %1").arg(fp.getQString()));
      // copy the palette as well
      if (level->getType() == TZP_XSHLEVEL) {
        if (!TSystem::copyFileOrLevel(fp.withType("tpl"),
                                      srcFp.withType("tpl")))
          warning(QObject::tr("Failed to overwrite %1")
                      .arg(fp.withType("tpl").getQString()));
      }
    }
  } else if (ret == 2) {  // decode $scenefolder aliases case
    Preferences::PathAliasPriority oldPriority =
        Preferences::instance()->getPathAliasPriority();
    Preferences::instance()->setValue(pathAliasPriority,
                                      Preferences::ProjectFolderOnly);
    for (int i = 0; i < sceneFolderLevels.size(); i++) {
      TXshLevel *level = sceneFolderLevels.at(i);
      // decode and code again
      TFilePath fp =
          scene->codeFilePath(scene->decodeFilePath(level->getPath()));
      setPathToLevel(level, fp);
    }
    Preferences::instance()->setValue(pathAliasPriority, oldPriority);
  }
  // Save the scene only case (ret == 3), do nothing
  return true;
}