opentoonz: tcg::poly_ops Namespace Reference
tcg::poly_ops Namespace Reference
Contains useful functions for operating with polynomials.
Functions
template<typename Scalar >
Scalar evaluate (const Scalar poly[], int deg, Scalar x)
Evaluates a polynomial using Horner's algorithm.
template<typename Scalar >
void reduceDegree (const Scalar poly[], int &deg, Scalar tolerance)
Reduces the degree of the input polynomial, discarding all leading coefficients whose absolute value is below the specified tolerance threshold.
template<typename A , typename B , typename C , int deg>
void add (const A(&poly1)[deg], const B(&poly2)[deg], C(&result)[deg])
Adds two polynomials and returns the sum.
template<typename A , typename B , typename C , int deg>
void sub (const A(&poly1)[deg], const B(&poly2)[deg], C(&result)[deg])
Subtracts two polynomials /p poly1 and poly2 and returns the difference poly1 - poly2.
template<typename A , typename B , typename C , int deg1, int deg2, int degR>
void mul (const A(&poly1)[deg1], const B(&poly2)[deg2], C(&result)[degR])
Multiplies two polynomials into a polynomial whose degree is the sum of the multiplicands' degrees.
template<typename A , typename B , typename C , int deg1, int deg2, int degR>
void chain (const A(&poly1)[deg1], const B(&poly2)[deg2], C(&result)[degR])
Calculates the chaining poly1 o poly2 of two given polynomial poly1 and poly2.
template<typename A , typename B , int deg, int degR>
void derivative (const A(&poly)[deg], B(&result)[degR])
template<typename Scalar >
unsigned int solve_1 (Scalar c[2], Scalar s[1], Scalar tol=0)
Solves the 1st degree equation: $c[1] t + c[0] = 0$.
template<typename Scalar >
unsigned int solve_2 (Scalar c[3], Scalar s[2], Scalar tol=0)
Solves the 2nd degree equation: $c[2] t^2 + c[1] t + c[0] = 0$.
template<typename Scalar >
unsigned int solve_3 (Scalar c[4], Scalar s[3], Scalar tol=0)
Solves the 3rd degree equation: $c[3]t^3 + c[2] t^2 + c[1] t + c[0] = 0$.
Detailed Description
Contains useful functions for operating with polynomials.
Function Documentation
add()
template<typename A , typename B , typename C , int deg> void tcg::poly_ops::add (const A(&) poly1[deg], const B(&) poly2[deg], C(&) result[deg])
Adds two polynomials and returns the sum.
Remarks
The supplied polynomials can actually be the same.
Parameters
poly1 First polynomial addendum.
poly2 Second polynomial addendum.
result Resulting sum.
{
  for (int d = 0; d != deg; ++d) result[d] = poly1[d] + poly2[d];
}
chain()
template<typename A , typename B , typename C , int deg1, int deg2, int degR> void tcg::poly_ops::chain (const A(&) poly1[deg1], const B(&) poly2[deg2], C(&) result[degR])
Calculates the chaining poly1 o poly2 of two given polynomial poly1 and poly2.
Warning
The resulting polynomial is currently not allowed to be one of the multiplicands.
This function is still untested.
Parameters
poly1 First polynomial.
poly2 Second polynomial.
result Resulting polynomial.
{
  for (int a = 0; a != deg1; ++a) {
    B pow[degR][2] = {{}};
    // Build poly2 powers
    {
      std::copy(poly2, poly2 + deg2, pow[1]);
      for (int p = 1; p < a; ++p) poly_mul(pow[p % 2], poly2, pow[(p + 1) % 2]);
    }
    B(&pow_add)[degR] = pow[a % 2];
    // multiply by poly1[a]
    C addendum[degR];
    for (int c = 0; c != degR; ++c) addendum[c] = poly1[c] * pow_add[c];
    poly_add(addendum, result);
  }
}
derivative()
template<typename A , typename B , int deg, int degR> void tcg::poly_ops::derivative (const A(&) poly[deg], B(&) result[degR])
Parameters
poly Polynomial to be derived.
result Resulting derivative polynomial.
{
  TCG_STATIC_ASSERT(degR == deg - 1);
  for (int c = 1; c != deg; ++c) result[c - 1] = c * poly[c];
}
References TCG_STATIC_ASSERT.
evaluate()
template<typename Scalar > Scalar tcg::poly_ops::evaluate (const Scalar poly[], int deg, Scalar x)
Evaluates a polynomial using Horner's algorithm.
Returns
The value of the input polynomial at the specified parameter
Parameters
poly Coefficients of the input polynomial, indexed by degree
deg Degree of the polynomial function
x Parameter the polynomial will be evaluated on
{
  // ((poly[deg] * x) + poly[deg-1]) * x + poly[deg - 2] + ...
  Scalar value = poly[deg];
  for (int d = deg - 1; d >= 0; --d) value = value * x + poly[d];
  return value;
}
mul()
template<typename A , typename B , typename C , int deg1, int deg2, int degR> void tcg::poly_ops::mul (const A(&) poly1[deg1], const B(&) poly2[deg2], C(&) result[degR])
Multiplies two polynomials into a polynomial whose degree is the sum of the multiplicands' degrees.
Warning
The resulting polynomial is currently not allowed to be one of the multiplicands.
Parameters
poly1 First multiplicand.
poly2 Second multiplicand.
result Resulting polynomial.
{
  TCG_STATIC_ASSERT(degR == deg1 + deg2 - 1);
  for (int a = 0; a != deg1; ++a) {
    for (int b = 0; b != deg2; ++b) result[a + b] += poly1[a] * poly2[b];
  }
}
References TCG_STATIC_ASSERT.
reduceDegree()
template<typename Scalar > void tcg::poly_ops::reduceDegree (const Scalar poly[], int & deg, Scalar tolerance)
Reduces the degree of the input polynomial, discarding all leading coefficients whose absolute value is below the specified tolerance threshold.
Parameters
poly Input polynomial to be reduced.
deg Input/output polynomial degree.
tolerance Coefficients threshold to reduce the polynomial with.
      {
  while ((deg > 0) && (std::abs(poly[deg]) < tolerance)) --deg;
}
solve_1()
template<typename Scalar > unsigned int tcg::poly_ops::solve_1 (Scalar c[2], Scalar s[1], Scalar tol = 0) inline
Solves the 1st degree equation: $c[1] t + c[0] = 0$.
Returns
The number of solutions found under the specified divide-by tolerance
Parameters
c Polynomial coefficients array
s Solutions array
tol Leading coefficient tolerance, the equation has no solution if the leading coefficient is below this threshold
{
  if (std::abs(c[1]) <= tol) return 0;
  s[0] = -c[0] / c[1];
  return 1;
}
Referenced by solve_2().
solve_2()
template<typename Scalar > unsigned int tcg::poly_ops::solve_2 (Scalar c[3], Scalar s[2], Scalar tol = 0)
Solves the 2nd degree equation: $c[2] t^2 + c[1] t + c[0] = 0$.
Returns
The number of #real# solutions found under the specified divide-by tolerance
Remarks
The returned solutions are sorted, with $s[0] <= s[1]$
Parameters
c Polynomial coefficients array
s Solutions array
tol Leading coefficient tolerance, the equation has no solution if the leading coefficient is below this threshold
{
  if (std::abs(c[2]) <= tol)
    return solve_1(c, s, tol);  // Reduces to first degree
  Scalar nc[2] = {
      c[0] / c[2],
      c[1] / (c[2] + c[2])};  // NOTE: nc[1] gets further divided by 2
  Scalar delta = nc[1] * nc[1] - nc[0];
  if (delta < 0) return 0;
  delta = sqrt(delta);
  s[0] = -delta - nc[1];
  s[1] = delta - nc[1];
  return 2;
}
References solve_1().
Referenced by solve_3().
solve_3()
template<typename Scalar > unsigned int tcg::poly_ops::solve_3 (Scalar c[4], Scalar s[3], Scalar tol = 0)
Solves the 3rd degree equation: $c[3]t^3 + c[2] t^2 + c[1] t + c[0] = 0$.
Returns
The number of #real# solutions found under the specified divide-by tolerance
Remarks
The returned solutions are sorted, with $s[0] <= s[1] <= s[2]$ if the leading coefficient is below this threshold
Parameters
c Polynomial coefficients array
s Solutions array
tol Leading coefficient tolerance, the equation is reduced to 2nd degree
{
  if (std::abs(c[3]) <= tol)
    return solve_2(c, s, tol);  // Reduces to second degree
  Scalar nc[3] = {c[0] / c[3], c[1] / c[3], c[2] / c[3]};
  Scalar b2     = nc[2] * nc[2];
  Scalar p      = nc[1] - b2 / 3;
  Scalar q      = nc[2] * (b2 + b2 - 9 * nc[1]) / 27 + nc[0];
  Scalar p3     = p * p * p;
  Scalar d      = q * q + 4 * p3 / 27;
  Scalar offset = -nc[2] / 3;
  if (d >= 0) {
    // Single solution
    Scalar z = sqrt(d);
    Scalar u = (-q + z) / 2;
    Scalar v = (-q - z) / 2;
    u = (u < 0) ? -pow(-u, 1 / Scalar(3)) : pow(u, 1 / Scalar(3));
    v = (v < 0) ? -pow(-v, 1 / Scalar(3)) : pow(v, 1 / Scalar(3));
    s[0] = offset + u + v;
    return 1;
  }
  assert(p3 < 0);
  Scalar u = sqrt(-p / Scalar(3));
  Scalar v = acos(-sqrt(-27 / p3) * q / Scalar(2)) / Scalar(3);
  Scalar m = cos(v), n = sin(v) * 1.7320508075688772935274463415059;  // sqrt(3)
  s[0] = offset - u * (n + m);
  s[1] = offset + u * (n - m);
  s[2] = offset + u * (m + m);
  assert(s[0] <= s[1] && s[1] <= s[2]);
  return 3;
}
References solve_2().
sub()
template<typename A , typename B , typename C , int deg> void tcg::poly_ops::sub (const A(&) poly1[deg], const B(&) poly2[deg], C(&) result[deg])
Subtracts two polynomials /p poly1 and poly2 and returns the difference poly1 - poly2.
Parameters
poly1 First polynomial addendum.
poly2 Second polynomial addendum.
result Resulting difference.
{
  for (int d = 0; d != deg; ++d) result[d] = poly1[d] - poly2[d];
}