opentoonz: TRop Namespace Reference
TRop Namespace Reference
Classes
class CmappedQuickputSettings
struct RaylitParams
Enumerations
enum ResampleFilterType {
None , Triangle , Mitchell , Cubic5 ,
Cubic75 , Cubic1 , Hann2 , Hann3 ,
Hamming2 , Hamming3 , Lanczos2 , Lanczos3 ,
Gauss , ClosestPixel , Bilinear , HowMany
}
enum ColorMask { RChan = 0x1 , GChan = 0x2 , BChan = 0x4 , MChan = 0x8 }
enum ErodilateMaskType { ED_rectangular , ED_circular }
Functions
DVAPI void rgbmScale (TRasterP rout, TRasterP rin, const double *k, const double *a, const int *out0, const int *out1)
Applies first order mappings to each of rin's channels.
DVAPI void rgbmScale (TRasterP rout, TRasterP rin, double kr, double kg, double kb, double km, double ar=0.0, double ag=0.0, double ab=0.0, double am=0.0)
DVAPI void rgbmAdjust (TRasterP rout, TRasterP rin, const int *in0, const int *in1, const int *out0, const int *out1)
DVAPI void checkBoard (TRasterP rout, const TPixel32 &, const TPixel32 &, const TDimensionD &, const TPointD &)
Make a checkoboard in rout.
DVAPI void over (const TRasterP &out, const TRasterP &dn, const TRasterP &up)
DVAPI void over (const TRasterP &out, const TRasterP &up, const TPoint &pos=TPoint())
DVAPI void over (const TRasterP &out, const TRasterP &up, const TAffine &aff, ResampleFilterType filterType=Triangle)
Make the image over of the up raster on the out raster.
DVAPI void over (const TRasterP &out, const TRasterP &up, const TPoint &pos, const TAffine &aff, ResampleFilterType filterType=Triangle)
DVAPI void over (const TRasterP &out, const TRasterP &dn, const TRasterP &up, const TRasterGR8P &mask)
DVAPI void over (TRaster32P rout, const TRasterGR8P &rup, const TPixel32 &color)
DVAPI void over (TRasterP rout, const TRasterCM32P &rup, TPalette *palette, const TPoint &point=TPoint(), const TAffine &aff=TAffine())
DVAPI void resample (const TRasterP &out, const TRasterP &in, const TAffine &aff, ResampleFilterType filterType=Triangle, double blur=1.)
DVAPI void quickPut (const TRasterP &out, const TRasterP &up, const TAffine &aff, const TPixel32 &colorScale=TPixel::Black, bool doPremultiply=false, bool whiteTransp=false, bool firstColumn=false, bool doRasterDarkenBlendedView=false)
Like the over function, but only uses closest_pixel filter.
DVAPI void quickPut (const TRasterP &out, const TRasterCM32P &up, const TPaletteP &plt, const TAffine &aff, const TPixel32 &globalColorScale=TPixel::Black, bool inksOnly=false)
Like the over function but up image must be cmapped.
DVAPI void quickPut (const TRasterP &dn, const TRasterCM32P &upCM32, const TPaletteP &plt, const TAffine &aff, const CmappedQuickputSettings &settings)
DVAPI void quickResampleColorFilter (const TRasterP &dn, const TRasterP &up, const TAffine &aff, const TPaletteP &plt, UCHAR colorMask)
DVAPI void convolve_3_i (TRasterP rout, TRasterP rin, int dx, int dy, double conv[])
DVAPI void convolve_i (TRasterP rout, TRasterP rin, int dx, int dy, double conv[], int radius)
DVAPI void fracmove (TRasterP rout, TRasterP rin, double dx, double dy)
DVAPI void convert (TRasterP dst, const TRasterP &src)
Convert src raster in raster type dst.
DVAPI void copy (TRasterP dst, const TRasterP &src)
Copy src in dst.
DVAPI void brush (TRaster32P ras, const TPoint &a, const TPoint &b, int radius, const TPixel32 &color)
DVAPI void computeBBox (TRasterP ras, TRect &bbox)
Get bbox of ras raster.
DVAPI void addBackground (TRasterP ras, const TPixel32 &col)
Add background of color col to the ras raster.
DVAPI bool isOpaque (TRasterP ras)
Return true if ras is opaque.
DVAPI void invert (TRasterP ras, bool invRed=true, bool invGreen=true, bool invBlue=true, bool invMatte=false)
DVAPI void add (const TRasterP &rup, const TRasterP &rdown, const TRasterP &rout, double v)
DVAPI void add (const TRasterP &rup, const TRasterP &rdown, const TRasterP &rout)
Add rdown pixels to rup pixels and put the resulting raster in rout.
DVAPI void colordodge (const TRasterP &rup, const TRasterP &rdown, const TRasterP &rout)
DVAPI void colorburn (const TRasterP &rup, const TRasterP &rdown, const TRasterP &rout)
DVAPI void screen (const TRasterP &rup, const TRasterP &rdown, const TRasterP &rout)
DVAPI void sub (const TRasterP &rup, const TRasterP &rdown, const TRasterP &rout, bool matte)
DVAPI void mult (const TRasterP &rup, const TRasterP &rdown, const TRasterP &rout, int v, bool matte)
DVAPI void ropin (const TRasterP &source, const TRasterP &matte, const TRasterP &rout)
DVAPI void ropout (const TRasterP &source, const TRasterP &matte, const TRasterP &rout)
DVAPI void atop (const TRasterP &rup, const TRasterP &rdown, const TRasterP &rout)
DVAPI void txor (const TRasterP &rup, const TRasterP &rdown, const TRasterP &rout)
DVAPI void crossDissolve (const TRasterP &rup, const TRasterP &rdown, const TRasterP &rout, UCHAR v)
DVAPI void lighten (const TRasterP &rup, const TRasterP &rdown, const TRasterP &rout)
DVAPI void darken (const TRasterP &rup, const TRasterP &rdown, const TRasterP &rout)
DVAPI void ropmin (const TRasterP &rup, const TRasterP &rdown, const TRasterP &rout, bool matte)
DVAPI void ropmax (const TRasterP &rup, const TRasterP &rdown, const TRasterP &rout)
DVAPI void linearburn (const TRasterP &rup, const TRasterP &rdown, const TRasterP &rout)
DVAPI void overlay (const TRasterP &rup, const TRasterP &rdown, const TRasterP &rout)
DVAPI void premultiply (const TRasterP &ras)
Make a premultiply of all raster pixels.
DVAPI void depremultiply (const TRasterP &ras)
Make a depremultiply of all raster pixels.
DVAPI void expandColor (const TRaster32P &ras32, bool precise)
DVAPI void whiteTransp (const TRasterP &ras)
all white pixels are set to transparent
DVAPI void applyColorScale (const TRasterP &ras, const TPixel32 &colorScale)
apply color filter and semi-transparency of column to the render result
DVAPI TRasterP shrink (TRasterP rin, int shrink)
DVAPI void gammaCorrect (TRasterP raster, double gamma)
Make a gamma correct in the raster.
DVAPI void gammaCorrectRGBM (TRasterP raster, double gammar, double gammag, double gammab, double gammam)
Make a gamma correct in the raster.
DVAPI int getBlurBorder (double blur)
Return the pixel size of the blur border.
DVAPI void antialias (const TRasterP &src, const TRasterP &dst, int threshold, int softness)
DVAPI void majorityDespeckle (const TRasterP &ras, int sizeThreshold)
DVAPI void blur (const TRasterP &dstRas, const TRasterP &srcRas, double blur, int dx, int dy, bool useSSE=false)
Make blur effect on srcRas raster and put the result in dstRas.
DVAPI void raylit (const TRasterP &dstRas, const TRasterP &srcRas, const RaylitParams &params)
Make raylit effect on srcRas raster and put the result in dstRas.
DVAPI void glassRaylit (const TRasterP &dstRas, const TRasterP &srcRas, const RaylitParams &params)
DVAPI void despeckle (const TRasterP &ras, int sizeThreshold, bool check, bool trasparentIsWhite=false)
DVAPI void despeckle (const TRasterP &rout, const TRasterP &rin, int sizeThreshold, bool check)
DVAPI TRaster32P copyAndSwapRBChannels (const TRaster32P &srcRaster)
Return a raster with r b channels swapped.
DVAPI void makeStereoRaster (const TRasterP &left, const TRasterP &right)
DVAPI void setChannel (const TRasterP &rin, TRasterP rout, UCHAR chan, bool greytones)
DVAPI void erodilate (const TRasterP &rin, const TRasterP &rout, double radius, ErodilateMaskType type)
DVAPI _RASTER * convertRaster50to46 (const TRasterP &inRas, const TPaletteP &inPalette)
Convert TRasterP in an old toonz raster!
DVAPI void releaseRaster46 (_RASTER *&r, bool doReleaseBuffer=false)
Release the old toonz raster.
DVAPI _RASTER * readRaster46 (const char *filename)
Read an image in the path filename and put it in an old toonz raster.
DVAPI void lockRaster (_RASTER *raster)
DVAPI void unlockRaster (_RASTER *raster)
DVAPI void convert (const TRaster32P &rasOut, const TRasterCM32P &rasIn, const TPaletteP palette, bool transparencyCheck=false)
DVAPI void convert (const TRaster32P &rasOut, const TRasterCM32P &rasIn, TPaletteP palette, const TRect &theClipRect, bool transparencyCheck=false, bool applyFx=false)
DVAPI void convert (const TTile &dst, const TTile &src, const TPaletteP plt, bool transparencyCheck, bool applyFxs)
DVAPI void applyMatchLines (TRasterCM32P rasOut, const TRasterCM32P &rasUp, const TPaletteP &pltOut, const TPaletteP &matchPlt, int inkIndex, int matchlinePrevalence, std::map< int, int > &usedInks)
DVAPI void mergeCmapped (TRasterCM32P rasOut, const TRasterCM32P &rasUp, const TPaletteP &pltOut, int matchlinePrevalence, std::map< int, int > &usedColors)
DVAPI void overlayCmapped (TRasterCM32P rasOut, const TRasterCM32P &rasUp, const TPaletteP &pltOut, const TPaletteP &upPlt, std::map< int, int > &usedColors)
DVAPI void eraseColors (TRasterCM32P ras, std::vector< int > *colorIds, bool eraseInks, bool noGap=false)
DVAPI void eraseStyleIds (TToonzImage *image, const std::vector< int > styleIds)
DVAPI void resample (const TRasterP &out, const TRasterCM32P &in, const TPaletteP palette, const TAffine &aff, ResampleFilterType filterType=Triangle, double blur=1.)
DVAPI void convolve_3_i (TRasterP rout, TRasterCM32P rin, const TPaletteP &palette, int dx, int dy, double conv[])
DVAPI void convolve_i (TRasterP rout, TRasterCM32P rin, const TPaletteP &palette, int dx, int dy, double conv[], int radius)
DVAPI void fracmove (TRasterP rout, TRasterCM32P rin, const TPaletteP &palette, double dx, double dy)
DVAPI void zoomOutCm32Rgbm (const TRasterCM32P &rin, TRaster32P &rout, const TPalette &plt, int x1, int y1, int x2, int y2, int newx, int newy, int absZoomLevel)
DVAPI void makeIcon (TRasterCM32P &rout, const TRasterCM32P &rin)
DVAPI void expandPaint (const TRasterCM32P &rasCM)
Detailed Description
The TRop namespace provides various algorithms to operate with Toonz's raster types
The TRop::borders namespace contains functions and classes that perform contours extraction of a specified raster (either greyscale, fullcolor or colormap).
Image contours are currently extracted in a not-hierarchycal fashion (ie in succession) and supplied through a reimplementable reader class.
Enumeration Type Documentation
ColorMask
enum TRop::ColorMask
{ RChan = 0x1, GChan = 0x2, BChan = 0x4, MChan = 0x8 };
ErodilateMaskType
enum TRop::ErodilateMaskType
{ ED_rectangular, ED_circular };
ResampleFilterType
enum TRop::ResampleFilterType
Enumerator
Triangle
triangle filter
Mitchell
Mitchell-Netravali filter.
Cubic5
cubic convolution, a = .5
Cubic75
cubic convolution, a = .75
Cubic1
cubic convolution, a = 1
Hann2
Hann window, rad = 2.
Hann3
Hann window, rad = 3.
Hamming2
Hamming window, rad = 2.
Hamming3
Hamming window, rad = 3.
Lanczos2
Lanczos window, rad = 2.
Lanczos3
Lanczos window, rad = 3.
Gauss
Gaussian convolution.
ClosestPixel
'Quick' filter
Bilinear
'Quick' filter
{
  None,
  Triangle,
  Mitchell,
  Cubic5,
  Cubic75,
  Cubic1,
  Hann2,
  Hann3,
  Hamming2,
  Hamming3,
  Lanczos2,
  Lanczos3,
  Gauss,
  ClosestPixel,
  Bilinear,
  HowMany
};
Function Documentation
add() [1/2]
void TRop::add (const TRasterP & rup, const TRasterP & rdown, const TRasterP & rout)
Add rdown pixels to rup pixels and put the resulting raster in rout.
{
  TRaster32P up32   = rup;
  TRaster32P down32 = rdown;
  TRaster32P out32  = rout;
  if (up32 && down32 && out32) {
    FOR_EACH_PIXEL_32_BEGIN_LOOP
    USHORT r, g, b, m;
    r = downPix->r + upPix->r;
    g = downPix->g + upPix->g;
    b = downPix->b + upPix->b;
    m = downPix->m + upPix->m;
    outPix->r = (UCHAR)tcrop<USHORT>(r, 0, 255);
    outPix->g = (UCHAR)tcrop<USHORT>(g, 0, 255);
    outPix->b = (UCHAR)tcrop<USHORT>(b, 0, 255);
    outPix->m = (UCHAR)tcrop<USHORT>(m, 0, 255);
    FOR_EACH_PIXEL_32_END_LOOP
  } else {
    TRaster64P up64   = rup;
    TRaster64P down64 = rdown;
    TRaster64P out64  = rout;
    if (up64 && down64 && out64) {
      FOR_EACH_PIXEL_64_BEGIN_LOOP
      TINT32 r, g, b, m;
      r = downPix->r + upPix->r;
      g = downPix->g + upPix->g;
      b = downPix->b + upPix->b;
      m = downPix->m + upPix->m;
      outPix->r = (USHORT)tcrop<TINT32>(r, 0, 0xffff);
      outPix->g = (USHORT)tcrop<TINT32>(g, 0, 0xffff);
      outPix->b = (USHORT)tcrop<TINT32>(b, 0, 0xffff);
      outPix->m = (USHORT)tcrop<TINT32>(m, 0, 0xffff);
      FOR_EACH_PIXEL_64_END_LOOP
    } else {
      TRasterGR8P up8   = rup;
      TRasterGR8P down8 = rdown;
      TRasterGR8P out8  = rout;
      if (up8 && down8 && out8) {
        FOR_EACH_PIXEL_8_BEGIN_LOOP
        USHORT value = upPix->value + downPix->value;
        outPix->value = (UCHAR)tcrop<USHORT>(value, 0, 255);
        FOR_EACH_PIXEL_8_END_LOOP
      } else
        throw TRopException("TRop::add invalid raster combination");
    }
  }
}
add() [2/2]
void TRop::add (const TRasterP & rup, const TRasterP & rdown, const TRasterP & rout, double v)
Add rdown pixels to rup pixels in according with the factor v and put the resulting raster in rout
{
  TRaster32P up32   = rup;
  TRaster32P down32 = rdown;
  TRaster32P out32  = rout;
  if (up32 && down32 && out32) {
    FOR_EACH_PIXEL_32_BEGIN_LOOP
    TINT32 r, g, b, m;
    if (upPix->m == 0)
      *outPix = *downPix;
    else {
      r         = downPix->r + tround(upPix->r * v);
      g         = downPix->g + tround(upPix->g * v);
      b         = downPix->b + tround(upPix->b * v);
      m         = downPix->m + tround(upPix->m * v);
      outPix->r = (UCHAR)tcrop<TINT32>(r, (TINT32)0, (TINT32)255);
      outPix->g = (UCHAR)tcrop<TINT32>(g, (TINT32)0, (TINT32)255);
      outPix->b = (UCHAR)tcrop<TINT32>(b, (TINT32)0, (TINT32)255);
      outPix->m = (UCHAR)tcrop<TINT32>(m, (TINT32)0, (TINT32)255);
    }
    FOR_EACH_PIXEL_32_END_LOOP
  } else {
    TRaster64P up64   = rup;
    TRaster64P down64 = rdown;
    TRaster64P out64  = rout;
    if (up64 && down64 && out64) {
      FOR_EACH_PIXEL_64_BEGIN_LOOP
      TINT32 r, g, b, m;
      r = downPix->r + tround(upPix->r * v);
      g = downPix->g + tround(upPix->g * v);
      b = downPix->b + tround(upPix->b * v);
      m = downPix->m + tround(upPix->m * v);
      outPix->r = (USHORT)tcrop<TINT32>(r, 0, 0xffff);
      outPix->g = (USHORT)tcrop<TINT32>(g, 0, 0xffff);
      outPix->b = (USHORT)tcrop<TINT32>(b, 0, 0xffff);
      outPix->m = (USHORT)tcrop<TINT32>(m, 0, 0xffff);
      FOR_EACH_PIXEL_64_END_LOOP
    } else {
      TRasterGR8P up8   = rup;
      TRasterGR8P down8 = rdown;
      TRasterGR8P out8  = rout;
      if (up8 && down8 && out8) {
        FOR_EACH_PIXEL_8_BEGIN_LOOP
        USHORT value = troundp(upPix->value * v) + downPix->value;
        outPix->value = (UCHAR)tcrop<USHORT>(value, 0, 255);
        FOR_EACH_PIXEL_8_END_LOOP
      } else
        throw TRopException("TRop::add invalid raster combination");
    }
  }
}
Referenced by AddFx::process().
addBackground()
void TRop::addBackground (TRasterP ras, const TPixel32 & col)
Add background of color col to the ras raster.
{
  TRaster32P ras32 = ras;
  if (ras32)
    addBackground32(ras32, col);
  else
    throw TRopException("unsupported pixel type");
}
Referenced by TCleanupper::process(), and CustomStyleManager::StyleLoaderTask::run().
antialias()
void TRop::antialias (const TRasterP & src, const TRasterP & dst, int threshold, int softness)
Inserts antialias around jaggy lines. Threshold is a pixel distance intended from 0 to 256. Softness may vary from 0 to 100.
{
  assert(src->getSize() == dst->getSize());
  TRaster32P src32(src), dst32(dst);
  if (src32 && dst32) {
    makeAntialias<TPixel32>(src32, dst32, threshold, softness);
    return;
  }
  TRaster64P src64(src), dst64(dst);
  if (src64 && dst64) {
    makeAntialias<TPixel64>(src64, dst64, threshold << 8, softness);
    return;
  }
  TRasterCM32P srcCM(src), dstCM(dst);
  if (srcCM && dstCM) {
    makeAntialias<TPixelCM32>(srcCM, dstCM, threshold, softness);
    return;
  }
  assert(!"Source and destination rasters must be of the same type!");
}
applyColorScale()
void TRop::applyColorScale (const TRasterP & ras, const TPixel32 & colorScale)
apply color filter and semi-transparency of column to the render result
{
  ras->lock();
  TRop::depremultiply(ras);
  TRaster32P ras32 = ras;
  int maxCh        = TPixel32::maxChannelValue;
  if (ras32) {
    TPixel32 *endPix, *upPix = 0, *upRow = ras32->pixels();
    TPixel32 *lastPix =
        upRow + ras32->getWrap() * (ras32->getLy() - 1) + ras32->getLx();
    while (upPix < lastPix) {
      upPix  = upRow;
      endPix = upPix + ras32->getLx();
      while (upPix < endPix) {
        int maxCh = TPixel32::maxChannelValue;
        int r  = maxCh - (maxCh - (*upPix).r) * (maxCh - colorScale.r) / maxCh;
        int g  = maxCh - (maxCh - (*upPix).g) * (maxCh - colorScale.g) / maxCh;
        int b  = maxCh - (maxCh - (*upPix).b) * (maxCh - colorScale.b) / maxCh;
        int m  = (*upPix).m * colorScale.m / maxCh;
        *upPix = TPixel32(r, g, b, m);
        ++upPix;
      }
      upRow += ras32->getWrap();
    }
  } else {
    TRaster64P ras64 = ras;
    if (ras64) {
      TPixel64 *endPix, *upPix = 0, *upRow = ras64->pixels();
      TPixel64 *lastPix =
          upRow + ras64->getWrap() * (ras64->getLy() - 1) + ras64->getLx();
      int maxCh64 = TPixel64::maxChannelValue;
      while (upPix < lastPix) {
        upPix  = upRow;
        endPix = upPix + ras64->getLx();
        while (upPix < endPix) {
          int r =
              maxCh64 - (maxCh64 - (*upPix).r) * (maxCh - colorScale.r) / maxCh;
          int g =
              maxCh64 - (maxCh64 - (*upPix).g) * (maxCh - colorScale.g) / maxCh;
          int b =
              maxCh64 - (maxCh64 - (*upPix).b) * (maxCh - colorScale.b) / maxCh;
          int m  = (*upPix).m * colorScale.m / maxCh;
          *upPix = TPixel64(r, g, b, m);
          ++upPix;
        }
        upRow += ras64->getWrap();
      }
    } else {
      ras->unlock();
      throw TException("TRop::premultiply invalid raster type");
    }
  }
  TRop::premultiply(ras);
  ras->unlock();
}
References depremultiply(), and premultiply().
applyMatchLines()
void TRop::applyMatchLines (TRasterCM32P rasOut, const TRasterCM32P & rasUp, const TPaletteP & pltOut, const TPaletteP & matchPlt, int inkIndex, int matchlinePrevalence, std::map< int, int > & usedInks)
{
  assert(matchlinePrevalence >= 0);
  if (inkIndex == -1)
    doMergeCmapped(rasOut, rasUp, pltOut, matchPlt, true, matchlinePrevalence,
                   usedInks, false);
  else if (inkIndex == -2)
    doMergeCmapped(rasOut, rasUp, pltOut, matchPlt, true, matchlinePrevalence,
                   usedInks, true);
  else
    doApplyMatchLines(rasOut, rasUp, inkIndex, matchlinePrevalence);
}
atop()
void TRop::atop (const TRasterP & rup, const TRasterP & rdown, const TRasterP & rout)
{
  // calcola rup ATOP rdown
  // da ottimizzare...
  TRaster32P up32   = rup;
  TRaster32P down32 = rdown;
  TRaster32P out32  = rout;
  TRaster64P up64   = rup;
  TRaster64P down64 = rdown;
  TRaster64P out64  = rout;
  if (up32 && down32 && out32) {
    FOR_EACH_PIXEL_32_BEGIN_LOOP
    TPixel32 tmpPix(0, 0, 0, 0);
    if (downPix->m != 0) {
      const int MAGICFAC = (257U * 256U + 1U);
      UINT fac           = MAGICFAC * downPix->m;
      tmpPix.r = (UINT)(upPix->r * fac + (1U << 23)) >> 24;
      tmpPix.g = (UINT)(upPix->g * fac + (1U << 23)) >> 24;
      tmpPix.b = (UINT)(upPix->b * fac + (1U << 23)) >> 24;
      tmpPix.m = (UINT)(upPix->m * fac + (1U << 23)) >> 24;
    }
    overPix<TPixel32, UCHAR>(*outPix, *downPix, tmpPix);
    FOR_EACH_PIXEL_32_END_LOOP
  } else if (up64 && down64 && out64) {
    FOR_EACH_PIXEL_64_BEGIN_LOOP
    TPixel64 tmpPix(0, 0, 0, 0);
    if (downPix->m != 0) {
      double fac = downPix->m / 65535.0;
      tmpPix.r = (USHORT)(upPix->r * fac);
      tmpPix.g = (USHORT)(upPix->g * fac);
      tmpPix.b = (USHORT)(upPix->b * fac);
      tmpPix.m = (USHORT)(upPix->m * fac);
    }
    overPix<TPixel64, USHORT>(*outPix, *downPix, tmpPix);
    FOR_EACH_PIXEL_64_END_LOOP
  } else
    throw TRopException("TRop::atop invalid raster combination");
}
blur()
void TRop::blur (const TRasterP & dstRas, const TRasterP & srcRas, double blur, int dx, int dy, bool useSSE = false)
Make blur effect on srcRas raster and put the result in dstRas.
{
  TRaster32P dstRas32 = dstRas;
  TRaster32P srcRas32 = srcRas;
  if (dstRas32 && srcRas32)
    doBlurRgb<TPixel32, UCHAR, float>(dstRas32, srcRas32, blur, dx, dy, useSSE);
  else {
    TRaster64P dstRas64 = dstRas;
    TRaster64P srcRas64 = srcRas;
    if (dstRas64 && srcRas64)
      doBlurRgb<TPixel64, USHORT, double>(dstRas64, srcRas64, blur, dx, dy,
                                          useSSE);
    else {
      TRasterGR8P dstRasGR8 = dstRas;
      TRasterGR8P srcRasGR8 = srcRas;
      if (dstRasGR8 && srcRasGR8)
        doBlurGray<TPixelGR8>(dstRasGR8, srcRasGR8, blur, dx, dy);
      else {
        TRasterGR16P dstRasGR16 = dstRas;
        TRasterGR16P srcRasGR16 = srcRas;
        if (dstRasGR16 && srcRasGR16)
          doBlurGray<TPixelGR16>(dstRasGR16, srcRasGR16, blur, dx, dy);
        else
          throw TException("TRop::blur unsupported pixel type");
      }
    }
  }
}
brush()
void TRop::brush (TRaster32P ras, const TPoint & a, const TPoint & b, int radius, const TPixel32 & color)
{
  TPoint a = aa;
  TPoint b = bb;
  if (a.y > b.y) std::swap(a, b);  //  a e' piu' in basso di b
  int lx = ras->getLx();
  int ly = ras->getLy();
  ras->lock();
  // ----- radius = 0
  if (radius == 0) {
    //  k = +1/-1 se il rettangolo e' inclinato positivamente
    //  (0<=m)/negativamente (m<0)
    //  (se k<0 viene fatta una riflessione sulle ascisse prima di tornare alle
    //  coordinate "di schermo")
    int k  = 1;
    int dy = b.y - a.y;
    int dx = b.x - a.x;
    if (dx < 0) {
      dx = -dx;
      k  = -1;
    }
    assert(dx >= 0);
    assert(dy >= 0);
    double m;  //  m sara' definita solo per dx!=0)
    if (dx > 0) {
      m = dy / (double)dx;
    }
    // double length = sqrt(dx*dx + dy*dy);
    const int alpha = dy, beta = -dx;
    const int incE  = alpha;
    const int incNE = alpha + beta;
    const int incN  = beta;
    //  N.B. le coordinate sono relative ad un sist. di rif. con l'origine in a
    //  l'eq. della retta e' alpha * x + beta * y = 0
    int yMin = std::max(a.y, 0) - a.y;  //  clipping y + cambio  riferimento
    int yMax = std::min(b.y, ly - 1) - a.y;  //  (trasporto dell'origine in a)
    if (dx > 0 && m <= 1) {
      //  midpoint algorithm
      TPoint segm;
      if (dy == 0)  //  segmento orizzontale: inizializza segm
      {
        segm.x = 0;
        segm.y = yMin;
      } else  //  0<m<=1 :  inizializza segm
      {
        segm.x = tceil((yMin - 0.5) / m);
        segm.y = yMin;
      }
      int dSegm = tfloor(alpha * (segm.x + 1) + beta * (segm.y + 0.5));
      while (segm.y <= yMax) {
        int count =
            0;  //  i trati orizzontali di segm vengono disegnati in "blocco"
        while (dSegm < 0 && segm.x <= dx)  //  Est:  segm.x<=dx evita il ciclo
        {                                  //  infinito quando m=0 (incE=0)
          dSegm = dSegm + incE;
          segm.x++;
          count++;
        }
        //  NordEst
        int xMin, xMax;
        if (k > 0) {
          xMin = std::max(
              {a.x + segm.x - count, a.x, 0});  //  clipping x + ritorno alle
          xMax = std::min(
              {a.x + segm.x, b.x, lx - 1});  //  coordinate "di schermo"
        } else {
          xMin = std::max({a.x - segm.x, a.x - dx,
                           0});  //  clipping x + riflessione + ritorno
          xMax = std::min({a.x - segm.x + count, a.x,
                           lx - 1});  //  alle  coordinate "di schermo"
        }
        TPixel32 *p = ras->pixels(segm.y + a.y) + xMin;
        TPixel32 *q = p + (xMax - xMin);
        while (p <= q) *p++ = col;
        dSegm = dSegm + incNE;
        segm.x++;
        segm.y++;
      }
    } else  //  m>1 oppure segmento verticale
    {
      //  midpoint algorithm
      TPoint segm;
      if (dx == 0)  //  segmento verticale: inizializza segm
      {
        segm.x = 0;
        segm.y = yMin;
      } else  //  m>1 :  inizializza segm
      {
        segm.x = tround(yMin / m);
        segm.y = yMin;
      }
      int dSegm = tfloor(alpha * (segm.x + 0.5) + beta * (segm.y + 1));
      while (segm.y <= yMax) {
        int xMin, xMax;
        if (k > 0) {
          xMin = std::max(a.x + segm.x, 0);       //  clipping x + ritorno alle
          xMax = std::min(a.x + segm.x, lx - 1);  //  coordinate "di schermo"
        } else {
          xMin =
              std::max(a.x - segm.x, 0);  //  clipping x + riflessione + ritorno
          xMax =
              std::min(a.x - segm.x, lx - 1);  //  alle  coordinate "di schermo"
        }
        TPixel32 *p = ras->pixels(segm.y + a.y) + xMin;
        TPixel32 *q = p + (xMax - xMin);
        while (p <= q) *p++ = col;
        if (dSegm <= 0)  //  NordEst
        {
          dSegm = dSegm + incNE;
          segm.x++;
        } else  //  Nord
        {
          dSegm = dSegm + incN;
        }
        segm.y++;
      }
    }
    ras->unlock();
    return;
  }
  HalfCord halfCord(radius);
  int x, y;
  // ----- punti iniziali coincidenti: disegna un cerchio
  if (a == b) {
    int yMin = std::max(a.y - radius, 0);       //  clipping y
    int yMax = std::min(a.y + radius, ly - 1);  //  clipping y
    for (y = yMin; y <= yMax; y++) {
      int deltay = abs(y - a.y);
      int xMin   = std::max(a.x - halfCord.getCord(deltay), 0);  //  clipping x
      int xMax =
          std::min(a.x + halfCord.getCord(deltay), lx - 1);  //  clipping x
      TPixel32 *p         = ras->pixels(y) + xMin;
      TPixel32 *q         = p + (xMax - xMin);
      while (p <= q) *p++ = col;
    }
    ras->unlock();
    return;
  }
  // -----  rettangolo orizzontale (a.y = b.y, a.x != b.x)
  if (a.y == b.y) {
    int yMin   = std::max((a.y - radius), 0);       //  clipping y
    int yMax   = std::min((a.y + radius), ly - 1);  //  clipping y
    int xLeft  = std::min(a.x, b.x);
    int xRight = std::max(a.x, b.x);
    for (y = yMin; y <= yMax; y++) {
      int deltay = abs(y - a.y);
      int xMin = std::max(xLeft - halfCord.getCord(deltay), 0);  //  clipping x
      int xMax =
          std::min(xRight + halfCord.getCord(deltay), lx - 1);  //  clipping x
      TPixel32 *p         = ras->pixels(y) + xMin;
      TPixel32 *q         = p + (xMax - xMin);
      while (p <= q) *p++ = col;
    }
    ras->unlock();
    return;
  }
  // -----  rettangolo verticale (a.x = b.x, a.y != b.y)
  if (a.x == b.x) {
    int xMin = std::max(a.x - radius, 0);       //  clipping x
    int xMax = std::min(a.x + radius, lx - 1);  //  clipping x
    for (x = xMin; x <= xMax; x++) {
      int deltax = abs(x - a.x);
      int yMin   = std::max(a.y - halfCord.getCord(deltax), 0);  //  clipping y
      int yMax =
          std::min(b.y + halfCord.getCord(deltax), ly - 1);  //  clipping y
      if (yMin <= yMax) {
        TPixel32 *p = ras->pixels(yMin) + x;
        TPixel32 *q = ras->pixels(yMax) + x;
        int wrap    = ras->getWrap();
        while (p <= q) {
          *p = col;
          p += wrap;
        }
      }
    }
    ras->unlock();
    return;
  }
  // -----  rettangolo inclinato
  //    k = +1/-1 se il rettangolo e' inclinato positivamente/negativamente
  int k  = 1;
  int dx = b.x - a.x;
  if (dx < 0) {
    dx = -dx;
    k  = -1;
  }
  int dy = b.y - a.y;
  assert(dx > 0);
  assert(dy > 0);
  double length  = sqrt((double)(dx * dx + dy * dy));
  const double m = dy / (double)dx;
  // punto di tangenza superiore nel sistema di riferimento del cerchio
  TPointD up(-radius * dy / length, radius * dx / length);
  // semi-ampiezza orizzontale delle "calotte" circolari
  int halfAmplCap = tfloor(-up.x);
  //  A meno di intersezioni relative tra le diverse zone:
  //  le scanline della "calotta" circolare superiore sono
  //  (b.y+cutExt,b.y+radius]
  //  le scanline del trapezoide circolare superiore sono [b.y-cutIn,b.y+cutExt]
  //  le scanline del parallelogramma sono (a.y+cutIn,b.y-cutIn)
  //  le scanline del trapezoide circolare inferiore sono [a.y-cutExt,a.y+cutIn]
  //  le scanline della "calotta" circolare inferiore sono
  //  [a.y-radius,a.y-cutExt)
  int cutExt, cutIn;
  // vertici del parallelogramma
  TPointD rightUp;
  TPointD rightDown;
  TPointD leftUp;
  TPointD leftDown;
  double mParall;  // coeff. angolare parallelogramma
  //  NOTA BENE:  halfAmplCap=0 <=> (radius=0 (caso a parte) , 1)
  if (radius > 1) {
    for (cutExt = radius;
         cutExt >= 0 && halfCord.getCord(cutExt) <= halfAmplCap; cutExt--)
      ;
    cutIn       = cutExt;  //  vedi else successivo
    rightUp.x   = dx + halfCord.getCord(cutIn);
    rightUp.y   = dy - cutIn;
    rightDown.x = halfCord.getCord(cutIn);
    rightDown.y = -cutIn;
    leftUp.x    = dx - halfCord.getCord(cutIn);
    leftUp.y    = dy + cutIn;
    leftDown.x  = -halfCord.getCord(cutIn);
    leftDown.y  = cutIn;
    mParall     = dy / (double)dx;
  } else  //  N.B. cutExt != cutIn solo quando radius=1
  {
    cutExt = radius;  //  radius=1 => halfAmplCap=0 (non ci sono mai le
                      //  "calotte" circolari)
    cutIn = 0;        //  anche per radius=1 il limite "interno" dei trapezoidi
                      //  circolari e' < radius
    rightUp.x   = dx - up.x;
    rightUp.y   = dy - up.y;
    rightDown.x = -up.x;
    rightDown.y = -up.y;
    leftUp.x    = dx + up.x;
    leftUp.y    = dy + up.y;
    leftDown.x  = up.x;
    leftDown.y  = up.y;
    mParall     = m;
  }
  // -----  riempie "calotte" circolari
  // -----  riempie "calotta" circolare inferiore
  int yMin = std::max(a.y - radius, 0);           //  clipping y
  int yMax = std::min(a.y - cutExt - 1, ly - 1);  //  clipping y
  for (y = yMin; y <= yMax; y++) {
    int r               = halfCord.getCord(a.y - y);
    int xMin            = std::max(a.x - r, 0);       //  clipping x
    int xMax            = std::min(a.x + r, lx - 1);  //  clipping x
    TPixel32 *p         = ras->pixels(y) + xMin;
    TPixel32 *q         = p + (xMax - xMin);
    while (p <= q) *p++ = col;
  }
  // -----  riempie "calotta" circolare superiore
  yMin = std::max(b.y + cutExt + 1, 0);   //  clipping y
  yMax = std::min(b.y + radius, ly - 1);  //  clipping y
  for (y = yMin; y <= yMax; y++) {
    int r               = halfCord.getCord(y - b.y);
    int xMin            = std::max(b.x - r, 0);       //  clipping x
    int xMax            = std::min(b.x + r, lx - 1);  //  clipping x
    TPixel32 *p         = ras->pixels(y) + xMin;
    TPixel32 *q         = p + (xMax - xMin);
    while (p <= q) *p++ = col;
  }
  // -----  riempie trapezoidi
  // (se k<0 viene fatta una riflessione sulle ascisse prima di tornare alle
  // coordinate "di schermo")
  //  limite destro assoluto delle scanline trapezoide:
  int xSegmMax = tround(dx - up.x);  //  coordinata x del punto di tangenza
                                     //  inferiore sul cerchio superiore
  //  limite sinistro assoluto delle scanline:
  int xSegmMin = tround(up.x);  //  coordinata x del punto di tangenza superiore
                                //  sul cerchio inferiore
  // -----  riempie trapezoide inferiore
  // N.B. le coordinate sono relative ad un sist. di rif. con l'origine sul
  // centro
  // del cerchio inferiore
  yMin = std::max(a.y - cutExt, 0) - a.y;                         //  clipping y
  yMax = std::min({a.y + cutIn, b.y - cutIn - 1, ly - 1}) - a.y;  //  clipping y
  // l'eq. della retta e' alpha * x + beta * y + gammaRight = 0
  const int alpha = dy, beta = -dx;
  const double gammaRight = rightDown.y * dx - rightDown.x * dy;
  const int incE          = alpha;
  const int incNE         = alpha + beta;
  const int incN          = beta;
  if (m <= 1) {
    //  midpoint algorithm; le scanline vengono disegnate solo
    //  sul NordEst. L'ultima scanline non viene disegnata
    TPoint segmRight(
        tceil((yMin + 0.5 - rightDown.y) / mParall + rightDown.x) - 1, yMin);
    int dSegmRight = tfloor(alpha * (segmRight.x + 1) +
                            beta * (segmRight.y + 0.5) + gammaRight);
    while (segmRight.y <= yMax) {
      if (dSegmRight < 0)  //  Est
      {
        dSegmRight = dSegmRight + incE;
        segmRight.x++;
      } else  //  NordEst
      {
        int xMin, xMax;
        if (k > 0) {
          xMin = std::max(a.x - halfCord.getCord(abs(segmRight.y)),
                          0);  //  clipping x
          xMax = std::min(a.x + std::min(segmRight.x, xSegmMax),
                          lx - 1);  //  clipping x
        } else {
          xMin = std::max(a.x - std::min(segmRight.x, xSegmMax),
                          0);  //  clipping x + ritorno alle
          xMax = std::min(a.x + halfCord.getCord(abs(segmRight.y)),
                          lx - 1);  //   coordinate "di schermo"
        }
        TPixel32 *p         = ras->pixels(segmRight.y + a.y) + xMin;
        TPixel32 *q         = p + (xMax - xMin);
        while (p <= q) *p++ = col;
        dSegmRight = dSegmRight + incNE;
        segmRight.x++;
        segmRight.y++;
      }
    }
  } else  //  m>1
  {
    //  midpoint algorithm; le scanline vengono disegnate sempre
    TPoint segmRight(tround((yMin - rightDown.y) / mParall + rightDown.x),
                     yMin);
    int dSegmRight = tfloor(alpha * (segmRight.x + 0.5) +
                            beta * (segmRight.y + 1) + gammaRight);
    while (segmRight.y <= yMax) {
      int xMin, xMax;
      if (k > 0) {
        xMin = std::max(a.x - halfCord.getCord(abs(segmRight.y)),
                        0);                          //  clipping x
        xMax = std::min(a.x + segmRight.x, lx - 1);  //  clipping x
      } else {
        xMin = std::max(a.x - segmRight.x,
                        0);  //  clipping x + ritorno alle coordinate
        xMax = std::min(a.x + halfCord.getCord(abs(segmRight.y)),
                        lx - 1);  //  "di schermo"
      }
      TPixel32 *p         = ras->pixels(segmRight.y + a.y) + xMin;
      TPixel32 *q         = p + (xMax - xMin);
      while (p <= q) *p++ = col;
      if (dSegmRight <= 0)  //  NordEst
      {
        dSegmRight = dSegmRight + incNE;
        segmRight.x++;
      } else  //  Nord
      {
        dSegmRight = dSegmRight + incN;
      }
      segmRight.y++;
    }
  }
  // -----  riempie trapezoide superiore
  //  N.B. le coordinate sono relative ad un sist. di rif. con l'origine sul
  //  centro
  //  del cerchio superiore
  yMin = std::max({b.y - cutIn, a.y + cutIn + 1, 0}) - b.y;  //  clipping y
  yMax = std::min(b.y + cutExt, ly - 1) - b.y;               //  clipping y
  //   l'eq. della retta e' alpha * x + beta * y + gammaLeft = 0
  const double gammaLeft = leftDown.y * dx - leftDown.x * dy;
  if (m <= 1) {
    //  midpoint algorithm; le scanline vengono disegnate solo
    //  sul NordEst. L'ultima scanline non viene disegnata
    TPoint segmLeft(tceil((yMin - 0.5 - leftDown.y) / mParall + leftDown.x),
                    yMin);
    int dSegmLeft = tfloor(alpha * (segmLeft.x + 1) +
                           beta * (segmLeft.y + 0.5) + gammaLeft);
    while (segmLeft.y <= yMax) {
      int xMin, xMax;
      if (k > 0) {
        xMin = std::max(b.x + std::max(segmLeft.x, xSegmMin - dx),
                        0);  //  clipping x
        xMax = std::min(b.x + halfCord.getCord(abs(segmLeft.y)),
                        lx - 1);  //  clipping x
      } else {
        xMin = std::max(b.x - halfCord.getCord(abs(segmLeft.y)),
                        0);  //  clipping x + ritorno alle
        xMax = std::min(b.x - std::max(segmLeft.x, xSegmMin - dx),
                        lx - 1);  //   coordinate "di schermo"
      }
      TPixel32 *p = ras->pixels(segmLeft.y + b.y) + xMin;
      TPixel32 *q = p + (xMax - xMin);
      while (p <= q) *p++ = col;
      while (dSegmLeft < 0) {
        dSegmLeft = dSegmLeft + incE;
        segmLeft.x++;
      }
      dSegmLeft = dSegmLeft + incNE;
      segmLeft.x++;
      segmLeft.y++;
    }
  } else  //  m>1
  {
    //  midpoint algorithm; le scanline vengono disegnate sempre
    TPoint segmLeft(tround((yMin - leftDown.y) / mParall + leftDown.x), yMin);
    int dSegmLeft = tfloor(alpha * (segmLeft.x + 0.5) +
                           beta * (segmLeft.y + 1) + gammaLeft);
    while (segmLeft.y <= yMax) {
      int xMin, xMax;
      if (k > 0) {
        xMin = std::max(b.x + segmLeft.x, 0);  //  clipping x
        xMax = std::min(b.x + halfCord.getCord(abs(segmLeft.y)),
                        lx - 1);  //  clipping x
      } else {
        xMin = std::max(b.x - halfCord.getCord(abs(segmLeft.y)),
                        0);  //  clipping x + ritorno alle
        xMax = std::min(b.x - segmLeft.x, lx - 1);  //   coordinate "di schermo"
      }
      TPixel32 *p = ras->pixels(segmLeft.y + b.y) + xMin;
      TPixel32 *q = p + (xMax - xMin);
      while (p <= q) *p++ = col;
      if (dSegmLeft <= 0)  //  NordEst
      {
        dSegmLeft = dSegmLeft + incNE;
        segmLeft.x++;
      } else  //  Nord
      {
        dSegmLeft = dSegmLeft + incN;
      }
      segmLeft.y++;
    }
  }
  // -----  parallelogramma (in alternativa a "parallelogrammoide circolare")
  // N.B. le coordinate sono relative ad un sist. di rif. con l'origine sul
  // centro
  // del cerchio inferiore
  //  retta destra di equaz.   alpha * x + beta * y + gammaRight = 0
  //  retta sinistra di equaz. alpha * x + beta * y + gammaLeft = 0
  yMin = std::max(a.y + cutIn + 1, 0) - a.y;       // clipping y
  yMax = std::min(b.y - cutIn - 1, ly - 1) - a.y;  // clipping y
  if (m <= 1) {
    //  midpoint algorithm; le scanline vengono disegnate solo
    //  sul NordEst. L'ultima scanline non viene disegnata
    TPoint segmRight(
        tceil((yMin + 0.5 - rightDown.y) / mParall + rightDown.x) - 1, yMin);
    TPoint segmLeft =
        TPoint(tceil((yMin - 0.5 - leftDown.y) / mParall + leftDown.x), yMin);
    int dSegmRight = tfloor(alpha * (segmRight.x + 1) +
                            beta * (segmRight.y + 0.5) + gammaRight);
    int dSegmLeft = tfloor(alpha * (segmLeft.x + 1) +
                           beta * (segmLeft.y + 0.5) + gammaLeft);
    while (segmRight.y <= yMax) {
      if (dSegmRight < 0)  //  segmRight a Est
      {
        dSegmRight = dSegmRight + incE;
        segmRight.x++;
      } else  //  segmRight a NordEst
      {
        int xMin, xMax;
        if (k > 0) {
          xMin =
              std::max(a.x + std::max(segmLeft.x, xSegmMin), 0);  //  clipping x
          xMax = std::min(a.x + std::min(segmRight.x, xSegmMax),
                          lx - 1);  //  clipping x
        } else {
          xMin = std::max(a.x - std::min(segmRight.x, xSegmMax),
                          0);  //  clipping x + ritorno alle
          xMax = std::min(a.x - std::max(segmLeft.x, xSegmMin),
                          lx - 1);  //   coordinate "di schermo"
        }
        TPixel32 *p = ras->pixels(segmRight.y + a.y) + xMin;
        TPixel32 *q = p + (xMax - xMin);
        while (p <= q) *p++ = col;
        dSegmRight = dSegmRight + incNE;
        segmRight.x++;
        segmRight.y++;
        while (dSegmLeft < 0)  //  segmLeft a Est
        {
          dSegmLeft = dSegmLeft + incE;
          segmLeft.x++;
        }
        //  segmLeft a NordEst
        dSegmLeft = dSegmLeft + incNE;
        segmLeft.x++;
        segmLeft.y++;
      }
    }
  } else  //  m>1
  {
    //  midpoint algorithm; le scanline vengono disegnate sempre
    TPoint segmRight(tround((yMin - rightDown.y) / mParall + rightDown.x),
                     yMin);
    TPoint segmLeft(tround((yMin - leftDown.y) / mParall + leftDown.x), yMin);
    int dSegmRight = tfloor(alpha * (segmRight.x + 0.5) +
                            beta * (segmRight.y + 1) + gammaRight);
    int dSegmLeft = tfloor(alpha * (segmLeft.x + 0.5) +
                           beta * (segmLeft.y + 1) + gammaLeft);
    while (segmRight.y <= yMax) {
      int xMin, xMax;
      if (k > 0) {
        xMin = std::max(a.x + segmLeft.x, 0);        //  clipping x
        xMax = std::min(a.x + segmRight.x, lx - 1);  //  clipping x
      } else {
        xMin = std::max(a.x - segmRight.x, 0);  //  clipping x + ritorno alle
        xMax = std::min(a.x - segmLeft.x, lx - 1);  //   coordinate "di schermo"
      }
      TPixel32 *p = ras->pixels(segmRight.y + a.y) + xMin;
      TPixel32 *q = p + (xMax - xMin);
      while (p <= q) *p++ = col;
      if (dSegmRight <= 0)  //  segmRight a NordEst
      {
        dSegmRight = dSegmRight + incNE;
        segmRight.x++;
      } else  //  segmRight a Nord
      {
        dSegmRight = dSegmRight + incN;
      }
      segmRight.y++;
      if (dSegmLeft <= 0)  //  segmLeft a NordEst
      {
        dSegmLeft = dSegmLeft + incNE;
        segmLeft.x++;
      } else  //  segmLeft a Nord
      {
        dSegmLeft = dSegmLeft + incN;
      }
    }
  }
  // ----  parallelogrammoide circolare (in alternativa a parallelogramma)
  // N.B. coordinate di schermo (riflessione per k<0 )
  yMin = std::max(b.y - cutIn, 0);
  yMax = std::min(a.y + cutIn, ly - 1);
  for (y = yMin; y <= yMax; y++) {
    int xMin, xMax;
    if (k > 0) {
      xMin = std::max(a.x - halfCord.getCord(abs(y - a.y)), 0);  //  clipping x
      xMax = std::min(b.x + halfCord.getCord(abs(b.y - y)),
                      lx - 1);  //  clipping x
    } else {
      xMin = std::max(b.x - halfCord.getCord(abs(b.y - y)),
                      0);  //  clipping x + ritorno alle
      xMax = std::min(a.x + halfCord.getCord(abs(y - a.y)),
                      lx - 1);  //   coordinate "di schermo"
    }
    TPixel32 *p         = ras->pixels(y) + xMin;
    TPixel32 *q         = p + (xMax - xMin);
    while (p <= q) *p++ = col;
  }
  ras->unlock();
}
checkBoard()
void TRop::checkBoard (TRasterP rout, const TPixel32 & pix1, const TPixel32 & pix2, const TDimensionD & dim, const TPointD & offset)
Make a checkoboard in rout.
Two variables TPixel32 describe the checkboard color, TDimension are checkboard dimension and TPoinD the position
{
  // assert(offset.x<=dim.lx && offset.y<=dim.ly);
  TRaster32P rout32 = rout;
  if (rout32)
    do_checkBoard<TPixel32>(rout32, pix1, pix2, dim, offset);
  else {
    TRaster64P rout64 = rout;
    if (rout64)
      do_checkBoard<TPixel64>(rout64, toPixel64(pix1), toPixel64(pix2), dim,
                              offset);
    else
      throw TRopException("unsupported pixel type");
  }
}
colorburn()
void TRop::colorburn (const TRasterP & rup, const TRasterP & rdown, const TRasterP & rout)
{
  TRaster32P up32   = rup;
  TRaster32P down32 = rdown;
  TRaster32P out32  = rout;
  if (up32 && down32 && out32) {
    FOR_EACH_PIXEL_32_BEGIN_LOOP
    //  downPix->r=0;
    //  downPix->g=255;
    //  downPix->b=0;
    double r, g, b;
    if (upPix->m) {
      if (downPix->r == 0 || downPix->r == 255)
        r = downPix->r;
      else if (upPix->r)
        r = 255 - (((255 - downPix->r) << 8) / (double)upPix->r);
      else
        r = 0;
      if (downPix->g == 0 || downPix->g == 255)
        g = downPix->g;
      else if (upPix->g)
        g = 255 - (((255 - downPix->g) << 8) / (double)upPix->g);
      else
        g = 0;
      if (downPix->b == 0 || downPix->b == 255)
        b = downPix->b;
      else if (upPix->b)
        b = 255 - (((255 - downPix->b) << 8) / (double)upPix->b);
      else
        b = 0;
      if (upPix->m != 255) {
        TPixel32 tmpPix;
        tmpPix.r = (UCHAR)tcrop<double>(r, .0, 255.0);
        tmpPix.g = (UCHAR)tcrop<double>(g, .0, 255.0);
        tmpPix.b = (UCHAR)tcrop<double>(b, .0, 255.0);
        tmpPix.m = upPix->m;
        ;
        overPix<TPixel32, UCHAR>(*outPix, *downPix, tmpPix);
      } else {
        outPix->r = (UCHAR)tcrop<double>(r, .0, 255.0);
        outPix->g = (UCHAR)tcrop<double>(g, .0, 255.0);
        outPix->b = (UCHAR)tcrop<double>(b, .0, 255.0);
        outPix->m = downPix->m;
      }
    } else {
      outPix = downPix;
    }
    FOR_EACH_PIXEL_32_END_LOOP
  } else {
    TRaster64P up64   = rup;
    TRaster64P down64 = rdown;
    TRaster64P out64  = rout;
    if (up64 && down64 && out64) {
      FOR_EACH_PIXEL_64_BEGIN_LOOP
      double r, g, b;
      if (upPix->m) {
        if (downPix->r == 0 || downPix->r == 65535)
          r = downPix->r;
        else if (upPix->r)
          r = 65535 - 65536 * ((65535.0 - downPix->r) / (double)upPix->r);
        else
          r = 0;
        if (downPix->g == 0 || downPix->g == 65535)
          g = downPix->g;
        else if (upPix->g)
          g = 65535 - 65536 * ((65535.0 - downPix->g) / (double)upPix->g);
        else
          g = 0;
        if (downPix->b == 0 || downPix->b == 65535)
          b = downPix->b;
        else if (upPix->b)
          b = 65535 - 65536 * ((65535.0 - downPix->b) / (double)upPix->b);
        else
          b = 0;
        if (upPix->m != 65535) {
          TPixel64 tmpPix;
          tmpPix.r = (USHORT)tcrop<double>(r, .0, 65535.0);
          tmpPix.g = (USHORT)tcrop<double>(g, .0, 65535.0);
          tmpPix.b = (USHORT)tcrop<double>(b, .0, 65535.0);
          tmpPix.m = upPix->m;
          overPix<TPixel64, USHORT>(*outPix, *downPix, tmpPix);
        } else {
          outPix->r = (USHORT)tcrop<double>(r, .0, 65535.0);
          outPix->g = (USHORT)tcrop<double>(g, .0, 65535.0);
          outPix->b = (USHORT)tcrop<double>(b, .0, 65535.0);
          outPix->m = downPix->m;
        }
      } else {
        outPix = downPix;
      }
      FOR_EACH_PIXEL_64_END_LOOP
    } else
      throw TRopException("TRop::color burn invalid raster combination");
  }
}
colordodge()
void TRop::colordodge (const TRasterP & rup, const TRasterP & rdown, const TRasterP & rout)
{
  TRaster32P up32   = rup;
  TRaster32P down32 = rdown;
  TRaster32P out32  = rout;
  if (up32 && down32 && out32) {
    FOR_EACH_PIXEL_32_BEGIN_LOOP
    USHORT r, g, b, m;
    r = (USHORT)((downPix->r << 8) / (256.0 - upPix->r));
    g = (USHORT)((downPix->g << 8) / (256.0 - upPix->g));
    b = (USHORT)((downPix->b << 8) / (256.0 - upPix->b));
    m = downPix->m + upPix->m;
    outPix->r = (UCHAR)tcrop<USHORT>(r, 0, 255);
    outPix->g = (UCHAR)tcrop<USHORT>(g, 0, 255);
    outPix->b = (UCHAR)tcrop<USHORT>(b, 0, 255);
    outPix->m = (UCHAR)tcrop<USHORT>(m, 0, 255);
    FOR_EACH_PIXEL_32_END_LOOP
  } else {
    TRaster64P up64   = rup;
    TRaster64P down64 = rdown;
    TRaster64P out64  = rout;
    if (up64 && down64 && out64) {
      FOR_EACH_PIXEL_64_BEGIN_LOOP
      TINT32 r, g, b, m;
      r = (TINT32)(65536.0 * (downPix->r / (65536.0 - upPix->r)));
      g = (TINT32)(65536.0 * (downPix->g / (65536.0 - upPix->g)));
      b = (TINT32)(65536.0 * (downPix->b / (65536.0 - upPix->b)));
      m = downPix->m + upPix->m;
      outPix->r = (USHORT)tcrop<TINT32>(r, 0, 0xffff);
      outPix->g = (USHORT)tcrop<TINT32>(g, 0, 0xffff);
      outPix->b = (USHORT)tcrop<TINT32>(b, 0, 0xffff);
      outPix->m = (USHORT)tcrop<TINT32>(m, 0, 0xffff);
      FOR_EACH_PIXEL_64_END_LOOP
    } else {
      TRasterGR8P up8   = rup;
      TRasterGR8P down8 = rdown;
      TRasterGR8P out8  = rout;
      if (up8 && down8 && out8) {
        FOR_EACH_PIXEL_8_BEGIN_LOOP
        USHORT value;
        if (downPix->value)
          value = (USHORT)((downPix->value << 8) / (255.0 - upPix->value));
        outPix->value = (UCHAR)tcrop<USHORT>(value, 0, 255);
        FOR_EACH_PIXEL_8_END_LOOP
      } else
        throw TRopException("TRop::color dodge invalid raster combination");
    }
  }
}
computeBBox()
void TRop::computeBBox (TRasterP ras, TRect & bbox)
Get bbox of ras raster.
{
  TRaster32P ras32 = ras;
  if (ras32) {
    ::computeBBox<TPixel32, UCHAR>(ras32, bbox);
    return;
  }
  TRaster64P ras64 = ras;
  if (ras64) {
    ::computeBBox<TPixel64, USHORT>(ras64, bbox);
    return;
  }
  TRasterCM32P rasCM32 = ras;
  if (rasCM32) {
    computeBBoxCM32(rasCM32, bbox);
    return;
  }
  TRasterGR8P ras8 = ras;
  if (ras8) {
    bbox = ras->getBounds();
    return;
  }
  assert(0);
}
convert() [1/4]
void TRop::convert (const TRaster32P & rasOut, const TRasterCM32P & rasIn, const TPaletteP palette, bool transparencyCheck = false)
{
  int count = palette->getStyleCount();
  int count2 =
      std::max({count, TPixelCM32::getMaxInk(), TPixelCM32::getMaxPaint()});
  // per poter utilizzare lo switch (piu' efficiente) si utilizza 255
  // anziche' TPixelCM32::getMaxTone()
  assert(TPixelCM32::getMaxTone() == 255);
  int rasLx = rasOut->getLx();
  int rasLy = rasOut->getLy();
  rasOut->lock();
  rasIn->lock();
#ifdef USE_SSE2
  if (TSystem::getCPUExtensions() & TSystem::CpuSupportsSse2) {
    __m128i zeros = _mm_setzero_si128();
    TPixelFloat *paints =
        (TPixelFloat *)_aligned_malloc(count2 * sizeof(TPixelFloat), 16);
    TPixelFloat *inks =
        (TPixelFloat *)_aligned_malloc(count2 * sizeof(TPixelFloat), 16);
    std::vector<TPixel32> paints2(count2);
    std::vector<TPixel32> inks2(count2);
    if (transparencyCheck) {
      for (int i = 0; i < palette->getStyleCount(); i++) {
        paints2[i] = c_transparencyCheckPaint;
        inks2[i]   = c_transparencyCheckInk;
        paints[i]  = TPixelFloat(paints2[i]);
        inks[i]    = TPixelFloat(inks2[i]);
      }
      paints2[0] = TPixel32::Transparent;
      paints[0]  = TPixelFloat(TPixel32::Transparent);
    }
    /*
else if (true)
{
            for(int i=0;i<palette->getStyleCount();i++)
{
paints2[i] = c_transparencyCheckPaint;
                    inks2[i]   = c_transparencyCheckInk;
paints[i]  = TPixelFloat(paints2[i]);
                    inks[i]    = TPixelFloat(inks2[i]);
            paints2[i] = TPixel32::Transparent;
            paints[i] = TPixelFloat(TPixel32::Transparent);
}
            paints2[0] = TPixel32::Transparent;
            paints[0] = TPixelFloat(TPixel32::Transparent);
}
*/
    else
      for (int i = 0; i < palette->getStyleCount(); i++) {
        TPixel32 color = ::premultiply(palette->getStyle(i)->getAverageColor());
        paints[i] = inks[i] = TPixelFloat(color);
        paints2[i] = inks2[i] = color;
      }
    float maxTone     = (float)TPixelCM32::getMaxTone();
    __m128 den_packed = _mm_load1_ps(&maxTone);
    for (int y = 0; y < rasLy; ++y) {
      TPixel32 *pix32   = rasOut->pixels(y);
      TPixelCM32 *pixIn = rasIn->pixels(y);
      TPixelCM32 *endPixIn = pixIn + rasLx;
      while (pixIn < endPixIn) {
        int tt = pixIn->getTone();
        int p  = pixIn->getPaint();
        int i  = pixIn->getInk();
        switch (tt) {
        case 255:
          *pix32++ = paints2[p];
          break;
        case 0:
          *pix32++ = inks2[i];
          break;
        default: {
          float t         = (float)tt;
          __m128 a_packed = _mm_load_ps((float *)&(inks[i]));
          __m128 b_packed = _mm_load_ps((float *)&(paints[p]));
          __m128 num_packed  = _mm_load1_ps(&t);
          __m128 diff_packed = _mm_sub_ps(den_packed, num_packed);
          // calcola in modo vettoriale out = ((den-num)*a + num*b)/den
          __m128 outPix_packed = _mm_mul_ps(diff_packed, a_packed);
          __m128 tmpPix_packed = _mm_mul_ps(num_packed, b_packed);
          outPix_packed = _mm_add_ps(outPix_packed, tmpPix_packed);
          outPix_packed = _mm_div_ps(outPix_packed, den_packed);
          // converte i canali da float a char
          __m128i outPix_packed_i = _mm_cvtps_epi32(outPix_packed);
          outPix_packed_i         = _mm_packs_epi32(outPix_packed_i, zeros);
          outPix_packed_i         = _mm_packus_epi16(outPix_packed_i, zeros);
          *(DWORD *)(pix32) = _mm_cvtsi128_si32(outPix_packed_i);
          ++pix32;
        }
        }
        ++pixIn;
      }
    }
    _aligned_free(paints);
    _aligned_free(inks);
  } else  // SSE2 not supported
#endif    // _WIN32
  {
    std::vector<TPixel32> paints(count2, TPixel32(255, 0, 0));
    std::vector<TPixel32> inks(count2, TPixel32(255, 0, 0));
    if (transparencyCheck) {
      for (int i = 0; i < palette->getStyleCount(); i++) {
        paints[i] = c_transparencyCheckPaint;
        inks[i]   = c_transparencyCheckInk;
      }
      paints[0] = TPixel32::Transparent;
    } else
      for (int i = 0; i < palette->getStyleCount(); i++)
        paints[i] = inks[i] =
            ::premultiply(palette->getStyle(i)->getAverageColor());
    for (int y = 0; y < rasLy; ++y) {
      TPixel32 *pix32      = rasOut->pixels(y);
      TPixelCM32 *pixIn    = rasIn->pixels(y);
      TPixelCM32 *endPixIn = pixIn + rasLx;
      while (pixIn < endPixIn) {
        int t = pixIn->getTone();
        int p = pixIn->getPaint();
        int i = pixIn->getInk();
        if (t == TPixelCM32::getMaxTone())
          *pix32++ = paints[p];
        else if (t == 0)
          *pix32++ = inks[i];
        else
          *pix32++ = blend(inks[i], paints[p], t, TPixelCM32::getMaxTone());
        ++pixIn;
      }
    }
  }
  rasOut->unlock();
  rasIn->unlock();
}
convert() [2/4]
void TRop::convert (const TRaster32P & rasOut, const TRasterCM32P & rasIn, TPaletteP palette, const TRect & theClipRect, bool transparencyCheck = false, bool applyFx = false)
{
  assert(palette);
  assert(rasIn && rasOut);
  TRect clipRect(theClipRect);
  if (clipRect.isEmpty())
    clipRect = rasIn->getBounds();
  else {
    if (!clipRect.overlaps(rasIn->getBounds())) return;
    clipRect = clipRect * rasIn->getBounds();
  }
  if (clipRect.isEmpty()) return;
  TRect clipRectIn, clipRectOut;
  if (applyFx && palette->getFxRects(clipRect, clipRectIn, clipRectOut)) {
    TRect rAux = clipRectIn;
    TRasterP rAuxIn =
        rasIn->extract(clipRectIn);  // la extract modifica clipRectIn
    if (rAux != clipRectIn && rAux != rasIn->getBounds()) {
      TRasterCM32P rNew(rAux.getSize());
      TRect tmpRect = clipRectIn - rAux.getP00();
      rNew->extract(tmpRect)->copy(rAuxIn);
      rAuxIn     = rNew;
      clipRectIn = rAux;
    }
    TTile tileIn(rAuxIn, ::convert(clipRectIn.getP00()));
    rAux = clipRectOut;
    TRasterP rAuxOut =
        rasOut->extract(clipRectOut);  // la extract modifica clipRectOut
    TTile tileOut(rAuxOut, ::convert(clipRectOut.getP00()));
    TRop::convert(tileOut, tileIn, palette, transparencyCheck, true);
  } else {
    TRect clipRectIn  = clipRect;
    TRect clipRectOut = clipRect;
    TRasterP _rasOut  = rasOut->extract(clipRectOut);
    TRasterP _rasIn   = rasIn->extract(clipRectIn);
    TTile t1(_rasOut, ::convert(clipRectOut.getP00()));
    TTile t2(_rasIn, ::convert(clipRectIn.getP00()));
    TRop::convert(t1, t2, palette, transparencyCheck, false);
  }
}
convert() [3/4]
void TRop::convert (const TTile & dst, const TTile & src, const TPaletteP plt, bool transparencyCheck, bool applyFxs)
{
  // if (dst->getSize() != src->getSize())
  //  throw TRopException("convert: size mismatch");
  // assert(plt);
  if ((TRaster32P)dst.getRaster())
    do_convert(dst, src, plt, transparencyCheck, applyFxs);
  else if ((TRaster64P)dst.getRaster()) {
    TRaster32P aux(dst.getRaster()->getLx(), dst.getRaster()->getLy());
    TTile taux(aux, dst.m_pos);
    do_convert(taux, src, plt, transparencyCheck, applyFxs);
    TRop::convert(dst.getRaster(), aux);
  } else
    throw TRopException("unsupported pixel type");
}
convert() [4/4]
void TRop::convert (TRasterP dst, const TRasterP & src)
Convert src raster in raster type dst.
{
  if (dst->getSize() != src->getSize())
    throw TRopException("convert: size mismatch");
  TRaster32P dst32   = dst;
  TRasterGR8P dst8   = dst;
  TRasterGR16P dst16 = dst;
  TRaster64P dst64   = dst;
  TRasterCM32P dstCm = dst;
  TRaster32P src32      = src;
  TRasterGR8P src8      = src;
  TRaster64P src64      = src;
  TRasterYUV422P srcYUV = src;
  TRasterYUV422P dstYUV = dst;
  src->lock();
  dst->lock();
  if (dst64 && src32)
    do_convert(dst64, src32);
  else if (dst8 && src32)
    do_convert(dst8, src32);
  else if (dst16 && src32)
    do_convert(dst16, src32);
  else if (dst32 && src64)
    ditherConvert(src64, dst32);
  else if (dst16 && src64)
    do_convert(dst16, src64);
  else if (dst32 && src8)
    do_convert(dst32, src8);
  else if (dstYUV && src32)
    do_convert(dstYUV, src32);  // Obsolete conversions
  else if (dst32 && srcYUV)
    do_convert(dst32, srcYUV);  //
  else if (dstCm && src32)
    do_convert(dstCm, src32);  //
  else if (dstCm && src8)
    do_convert(dstCm, src8);  //
  else {
    dst->unlock();
    src->unlock();
    throw TRopException("unsupported pixel type");
  }
  dst->unlock();
  src->unlock();
}
Referenced by copy(), over(), resample(), and MovieRenderer::Imp::saveFrame().
convertRaster50to46()
_RASTER * TRop::convertRaster50to46 (const TRasterP & inRas, const TPaletteP & inPalette)
Convert TRasterP in an old toonz raster!
Use the same buffer, not creates a new raster (the palette is new instead!)
{
  int lx   = inRas->getLx();
  int ly   = inRas->getLy();
  int wrap = inRas->getWrap();
  assert(lx > 0 && ly > 0);
  assert(inRas->getRawData());
  TRasterGR8P rgr8   = (TRasterGR8P)inRas;
  TRasterGR16P rgr16 = (TRasterGR16P)inRas;
  TRaster32P r32     = (TRaster32P)inRas;
  TRaster64P r64     = (TRaster64P)inRas;
  TRasterCM32P rcm   = (TRasterCM32P)inRas;
  RASTER *rout = new RASTER;
  memset(rout, 0, sizeof(RASTER));
  std::string id(TImageCache::instance()->getUniqueId());
  rout->cacheIdLength = id.size();
  rout->cacheId       = new char[rout->cacheIdLength];
  memcpy(rout->cacheId, id.data(), sizeof(char) * rout->cacheIdLength);
  {
    TImageP img;
    if (rcm)
      img = TToonzImageP(rcm, rcm->getBounds());  // saveBox is not considered
                                                  // in RASTER struct anyway
    else
      img = TRasterImageP(inRas);
    TImageCache::instance()->add(id, img);
  }
  inRas->addRef();
  rout->buffer        = inRas->getRawData();
  TRasterP parent     = inRas->getParent();
  rout->native_buffer = (parent) ? parent->getRawData() : inRas->getRawData();
  rout->lx            = lx;
  rout->ly            = ly;
  rout->wrap          = wrap;
  if (rgr8)
    rout->type = RAS_GR8;
  else if (rgr16)
    rout->type = RAS_GR16;
  else if (r32)
    rout->type = RAS_RGBM;
  else if (r64)
    rout->type = RAS_RGBM64;
  else if (rcm)
    rout->type = RAS_CM32;
  else
    assert(!"raster type not convertible!");
  if (rout->type != RAS_CM32) return rout;
  if (!inPalette) {
    assert(!"missing palette!");
    return NULL;
  }
  rout->cmap.info   = Tcm_32_default_info;
  rout->cmap.buffer = new LPIXEL[TCM_CMAP_PENBUFFER_SIZE(rout->cmap.info)];
  // rout->cmap.penbuffer = new LPIXEL[TCM_CMAP_PENBUFFER_SIZE
  // (rout->cmap.info)];
  // rout->cmap.colbuffer = new LPIXEL[TCM_CMAP_COLBUFFER_SIZE
  // (rout->cmap.info)];
  for (int i = 0; i < inPalette->getStyleCount(); i++)
    rout->cmap.buffer[i] =
        ::premultiplyLPIXEL(inPalette->getStyle(i)->getAverageColor());
  // fillCmapRamp (rout->cmap, inPalette->getStyle(i)->getMainColor(), i);
  return rout;
}
References TImageCache::add(), TColorStyle::getAverageColor(), TRaster::getRawData(), TPalette::getStyle(), TPalette::getStyleCount(), and TRaster::getWrap().
Referenced by readRaster46().
convolve_3_i() [1/2]
void TRop::convolve_3_i (TRasterP rout, TRasterCM32P rin, const TPaletteP & palette, int dx, int dy, double conv[])
{
  TRaster32P rout32 = rout;
  if (rout32) {
    doConvolve_cm32_3_i<TPixel32>(rout32, rin, palette, dx, dy, conv);
    return;
  }
  TRaster64P rout64 = rout;
  if (rout64) {
    doConvolve_cm32_3_i<TPixel64>(rout64, rin, palette, dx, dy, conv);
    return;
  }
  throw TRopException("TRop::convolve_3_i: unsupported pixel type");
}
convolve_3_i() [2/2]
void TRop::convolve_3_i (TRasterP rout, TRasterP rin, int dx, int dy, double conv[])
{
  TRaster32P rin32 = rin;
  if (rin32) {
    TRaster32P rout32 = rout;
    if (rout32) {
      doConvolve_3_i<TPixel32, TPixel32>(rout32, rin32, dx, dy, conv);
      return;
    }
    TRaster64P rout64 = rout;
    if (rout64) {
      doConvolve_3_i<TPixel64, TPixel32>(rout64, rin32, dx, dy, conv);
      return;
    }
  } else {
    TRaster64P rin64 = rin;
    if (rin64) {
      TRaster32P rout32 = rout;
      if (rout32) {
        doConvolve_3_i<TPixel32, TPixel64>(rout32, rin64, dx, dy, conv);
        return;
      }
      TRaster64P rout64 = rout;
      if (rout64) {
        doConvolve_3_i<TPixel64, TPixel64>(rout64, rin64, dx, dy, conv);
        return;
      }
    }
  }
  throw TRopException("TRop::convolve_3_i: unsupported pixel type");
}
convolve_i() [1/2]
void TRop::convolve_i (TRasterP rout, TRasterCM32P rin, const TPaletteP & palette, int dx, int dy, double conv[], int radius)
{
  TRaster32P rout32 = rout;
  if (rout32) {
    doConvolve_cm32_i<TPixel32>(rout32, rin, palette, dx, dy, conv, radius);
    return;
  }
  TRaster64P rout64 = rout;
  if (rout64) {
    doConvolve_cm32_i<TPixel64>(rout64, rin, palette, dx, dy, conv, radius);
    return;
  }
  throw TRopException("TRop::convolve_i: unsupported pixel type");
}
convolve_i() [2/2]
void TRop::convolve_i (TRasterP rout, TRasterP rin, int dx, int dy, double conv[], int radius)
{
  TRaster32P rin32 = rin;
  if (rin32) {
    TRaster32P rout32 = rout;
    if (rout32) {
      doConvolve_i<TPixel32, TPixel32>(rout32, rin32, dx, dy, conv, radius);
      return;
    }
    TRaster64P rout64 = rout;
    if (rout64) {
      doConvolve_i<TPixel64, TPixel32>(rout64, rin32, dx, dy, conv, radius);
      return;
    }
  } else {
    TRaster64P rin64 = rin;
    if (rin64) {
      TRaster32P rout32 = rout;
      if (rout32) {
        doConvolve_i<TPixel32, TPixel64>(rout32, rin64, dx, dy, conv, radius);
        return;
      }
      TRaster64P rout64 = rout;
      if (rout64) {
        doConvolve_i<TPixel64, TPixel64>(rout64, rin64, dx, dy, conv, radius);
        return;
      }
    }
  }
  throw TRopException("TRop::convolve_i: unsupported pixel type");
}
copy()
void TRop::copy (TRasterP dst, const TRasterP & src)
Copy src in dst.
{
  assert(!((TRasterCM32P)src) || (TRasterCM32P)dst);
  if (dst->getPixelSize() == src->getPixelSize())
    dst->copy(src);
  else {
    if (dst->getBounds() != src->getBounds()) {
      TRect rect = dst->getBounds() * src->getBounds();
      if (rect.isEmpty()) return;
      TRop::convert(dst->extract(rect), src->extract(rect));
    } else
      TRop::convert(dst, src);
  }
}
References convert(), TRaster::copy(), and TRectT< T >::isEmpty().
Referenced by TCacheResource::download(), over(), TCleanupper::process(), and TCacheResource::upload().
copyAndSwapRBChannels()
TRaster32P TRop::copyAndSwapRBChannels (const TRaster32P & srcRaster)
Return a raster with r b channels swapped.
{
  TRaster32P newRaster(srcRaster->getSize());
  int lx = srcRaster->getLx();
  int y  = srcRaster->getLy();
  srcRaster->lock();
  newRaster->lock();
  while (--y >= 0) {
    TPixel32 *pix    = srcRaster->pixels(y);
    TPixel32 *newpix = newRaster->pixels(y);
    TPixel32 *endPix = pix + lx;
    while (pix < endPix) {
      newpix->r = pix->b;
      newpix->g = pix->g;
      newpix->b = pix->r;
      newpix->m = pix->m;
      ++pix;
      ++newpix;
    }
  }
  srcRaster->unlock();
  newRaster->unlock();
  return newRaster;
}
crossDissolve()
void TRop::crossDissolve (const TRasterP & rup, const TRasterP & rdown, const TRasterP & rout, UCHAR v)
{
  TRaster32P up32   = rup;
  TRaster32P down32 = rdown;
  TRaster32P out32  = rout;
  TRaster64P up64   = rup;
  TRaster64P down64 = rdown;
  TRaster64P out64  = rout;
  if (up32 && down32 && out32) {
    FOR_EACH_PIXEL_32_BEGIN_LOOP
    outPix->r = (upPix->r * v + downPix->r * (255 - v)) / 255;
    outPix->g = (upPix->g * v + downPix->g * (255 - v)) / 255;
    outPix->b = (upPix->b * v + downPix->b * (255 - v)) / 255;
    outPix->m = (upPix->m * v + downPix->m * (255 - v)) / 255;
    FOR_EACH_PIXEL_32_END_LOOP
  } else if (up64 && down64 && out64) {
    USHORT vv = v * 257;
    FOR_EACH_PIXEL_64_BEGIN_LOOP
    outPix->r = (upPix->r * vv + downPix->r * (65535 - vv)) / 65535;
    outPix->g = (upPix->g * vv + downPix->g * (65535 - vv)) / 65535;
    outPix->b = (upPix->b * vv + downPix->b * (65535 - vv)) / 65535;
    outPix->m = (upPix->m * vv + downPix->m * (65535 - vv)) / 65535;
    FOR_EACH_PIXEL_64_END_LOOP
  } else
    throw TRopException("TRop::crossDissolve invalid raster combination");
}
darken()
void TRop::darken (const TRasterP & rup, const TRasterP & rdown, const TRasterP & rout)
{
  TRaster32P up32   = rup;
  TRaster32P down32 = rdown;
  TRaster32P out32  = rout;
  TRaster64P up64   = rup;
  TRaster64P down64 = rdown;
  TRaster64P out64  = rout;
  if (up32 && down32 && out32) {
    FOR_EACH_PIXEL_32_BEGIN_LOOP
    double value0 = luminance(upPix);
    double value1 = luminance(downPix);
    if (value0 < value1)
      *outPix = *upPix;
    else
      *outPix = *downPix;
    FOR_EACH_PIXEL_32_END_LOOP
  } else if (up64 && down64 && out64) {
    FOR_EACH_PIXEL_64_BEGIN_LOOP
    double value0 = luminance(upPix);
    double value1 = luminance(downPix);
    if (value0 < value1)
      *outPix = *upPix;
    else
      *outPix = *downPix;
    FOR_EACH_PIXEL_64_END_LOOP
  } else
    throw TRopException("TRop::darken invalid raster combination");
}
depremultiply()
void TRop::depremultiply (const TRasterP & ras)
Make a depremultiply of all raster pixels.
{
  ras->lock();
  TRaster32P ras32 = ras;
  if (ras32) {
    TPixel32 *endPix, *upPix = 0, *upRow = ras32->pixels();
    TPixel32 *lastPix =
        upRow + ras32->getWrap() * (ras32->getLy() - 1) + ras32->getLx();
    while (upPix < lastPix) {
      upPix  = upRow;
      endPix = upPix + ras32->getLx();
      while (upPix < endPix) {
        if (upPix->m != 0) depremult(*upPix);
        ++upPix;
      }
      upRow += ras32->getWrap();
    }
  } else {
    TRaster64P ras64 = ras;
    if (ras64) {
      TPixel64 *endPix, *upPix = 0, *upRow = ras64->pixels();
      TPixel64 *lastPix =
          upRow + ras64->getWrap() * (ras64->getLy() - 1) + ras64->getLx();
      while (upPix < lastPix) {
        upPix  = upRow;
        endPix = upPix + ras64->getLx();
        while (upPix < endPix) {
          if (upPix->m != 0) depremult(*upPix);
          ++upPix;
        }
        upRow += ras64->getWrap();
      }
    } else {
      ras->unlock();
      throw TException("TRop::depremultiply invalid raster type");
    }
  }
  ras->unlock();
}
Referenced by applyColorScale(), and texture_utils::getTextureData().
eraseColors()
void TRop::eraseColors (TRasterCM32P ras, std::vector< int > * colorIds, bool eraseInks, bool noGap = false)
{
  // noGap option is available only when erasing Inks
  assert(eraseInks || !noGap);
  if (colorIds) std::sort(colorIds->begin(), colorIds->end());
  bool hasGapPixel = false;
  for (int y = 0; y < ras->getLy(); y++) {
    TPixelCM32 *pix = ras->pixels(y), *endPix = pix + ras->getLx();
    for (; pix < endPix; pix++) {
      unsigned int i = 0;
      int color      = eraseInks ? pix->getInk() : pix->getPaint();
      if (color == 0) continue;
      if (colorIds &&
          !std::binary_search(colorIds->begin(), colorIds->end(), color))
        continue;
      if (eraseInks) {
        // no-gap case.
        // even if some area is filled under the solid line, delete it and
        // expand-fill again to make sure the colors will be separated at the
        // center of the lines.
        if (noGap && pix->getTone() == 0) {
          pix->setPaint(
              TPixelCM32::getMaxPaint());  // use paintId = 4095 as mark of
                                           // pixels to be filled
          hasGapPixel = true;
        }
        pix->setInk(0);
        pix->setTone(TPixelCM32::getMaxTone());
      } else
        pix->setPaint(0);
    }
  }
  if (hasGapPixel) expandAreaAndFillGaps(ras);
}
eraseStyleIds()
void TRop::eraseStyleIds (TToonzImage * image, const std::vector< int > styleIds)
{
  assert(image);
  TRasterCM32P ras = image->getRaster();
  int i;
  for (i = 0; i < (int)styleIds.size(); i++) {
    int styleId = styleIds[i];
    ras->lock();
    for (int y = 0; y < ras->getLy(); y++) {
      TPixelCM32 *pix = ras->pixels(y), *endPix = pix + ras->getLx();
      while (pix < endPix) {
        bool isPaint = (pix->getPaint() == styleId);
        bool isInk   = (pix->getInk() == styleId);
        if (!isPaint && !isInk) {
          pix++;
          continue;
        } else if (isPaint && !isInk)
          *pix = TPixelCM32(pix->getInk(), 0, pix->getTone());
        else if (!isPaint && isInk)
          *pix = TPixelCM32(0, pix->getPaint(), TPixelCM32::getMaxTone());
        else if (isPaint && isInk)
          *pix = TPixelCM32(0, 0, pix->getTone());
        else
          assert(0);
        pix++;
      }
    }
    ras->unlock();
  }
}
erodilate()
void TRop::erodilate (const TRasterP & rin, const TRasterP & rout, double radius, ErodilateMaskType type)
Applies classical morphological erosion/dilation to the specified input raster.
Note
Supports rin == rout.
{
  assert(src->getSize() == dst->getSize());
  src->lock(), dst->lock();
  if ((TRaster32P)src && (TRaster32P)dst) switch (type) {
    case ED_rectangular:
      ::rect_erodilate<TPixel32>(src, dst, radius);
      break;
    case ED_circular:
      ::circular_erodilate<TPixel32>(src, dst, radius);
      break;
    default:
      assert(!"Unknown mask type");
      break;
    }
  else if ((TRaster64P)src && (TRaster64P)dst)
    switch (type) {
    case ED_rectangular:
      ::rect_erodilate<TPixel64>(src, dst, radius);
      break;
    case ED_circular:
      ::circular_erodilate<TPixel64>(src, dst, radius);
      break;
    default:
      assert(!"Unknown mask type");
      break;
    }
  else
    assert(!"Unsupported raster type!");
  src->unlock(), dst->unlock();
}
expandColor()
void TRop::expandColor (const TRaster32P & ras32, bool precise)
{
  struct locals {
    static void copyRGB(TPixel32 *dst, TPixel32 *src) {
      dst->r = src->r;
      dst->g = src->g;
      dst->b = src->b;
    }
  };  // locals
  ras32->lock();
  TPixel32 *endPix, *upPix = 0, *upRow = ras32->pixels();
  TPixel32 *lastPix =
      upRow + ras32->getWrap() * (ras32->getLy() - 1) + ras32->getLx();
  int currentRow = 0;
  while (upPix < lastPix) {
    upPix  = upRow;
    endPix = upPix + ras32->getLx();
    while (upPix < endPix) {
      if (upPix->m == 0) {
        // search 4-neighbor pixels
        // left
        if (upPix != upRow && (upPix - 1)->m != 0)
          locals::copyRGB(upPix, upPix - 1);
        // right
        else if (upPix != endPix - 1 && (upPix + 1)->m != 0)
          locals::copyRGB(upPix, upPix + 1);
        // up
        else if (currentRow != 0 && (upPix - ras32->getWrap())->m != 0)
          locals::copyRGB(upPix, upPix - ras32->getWrap());
        // down
        else if (currentRow != ras32->getLy() - 1 &&
                 (upPix + ras32->getWrap())->m != 0)
          locals::copyRGB(upPix, upPix + ras32->getWrap());
        // search 8-neighbor pixels
        else if (precise) {
          // upper left
          if (currentRow != 0 && upPix != upRow &&
              (upPix - ras32->getWrap() - 1)->m != 0)
            locals::copyRGB(upPix, upPix - ras32->getWrap() - 1);
          // upper right
          else if (currentRow != 0 && upPix != endPix - 1 &&
                   (upPix - ras32->getWrap() + 1)->m != 0)
            locals::copyRGB(upPix, upPix - ras32->getWrap() + 1);
          // lower left
          else if (currentRow != ras32->getLy() - 1 && upPix != upRow &&
                   (upPix + ras32->getWrap() - 1)->m != 0)
            locals::copyRGB(upPix, upPix + ras32->getWrap() - 1);
          // lower right
          else if (currentRow != ras32->getLy() - 1 && upPix != endPix - 1 &&
                   (upPix + ras32->getWrap() + 1)->m != 0)
            locals::copyRGB(upPix, upPix + ras32->getWrap() + 1);
        }
      }
      ++upPix;
    }
    upRow += ras32->getWrap();
    currentRow++;
  }
  ras32->unlock();
}
expandPaint()
void TRop::expandPaint (const TRasterCM32P & rasCM)
{
  distanceTransform(rasCM, SomePaint(), CopyPaint());
}
fracmove() [1/2]
void TRop::fracmove (TRasterP rout, TRasterCM32P rin, const TPaletteP & palette, double dx, double dy)
{
  double w[4] = {1, 0, 0, 0};
  double sum  = 0;
  int idx      = tfloor(dx);
  int idy      = tfloor(dy);
  double fracX = dx - idx;
  double fracY = dy - idy;
  int i, j;
  for (i = 0; i < 2; ++i)
    for (j                = 0; j < 2; ++j)
      sum += w[j + 2 * i] = fabs(fracX - j) * fabs(fracY - i);
  for (i = 0; i < 4; ++i) w[i] /= sum;
  TRop::convolve_i(rout, rin, idx, idy, w, 2);
}
fracmove() [2/2]
void TRop::fracmove (TRasterP rout, TRasterP rin, double dx, double dy)
{
  // Using a bilinear filter is best - consider that only 4 pixels should
  // contribute
  // to a fractionarily shifted one, with weights proportional to the
  // intersection areas.
  double w[4] = {1, 0, 0, 0};
  double sum  = 0;
  int idx      = tfloor(dx);
  int idy      = tfloor(dy);
  double fracX = dx - idx;
  double fracY = dy - idy;
  int i, j;
  for (i = 0; i < 2; ++i)
    for (j                = 0; j < 2; ++j)
      sum += w[j + 2 * i] = fabs(fracX - j) * fabs(fracY - i);
  for (i = 0; i < 4; ++i) w[i] /= sum;
  TRop::convolve_i(rout, rin, idx, idy, w, 2);
}
gammaCorrect()
void TRop::gammaCorrect (TRasterP raster, double gamma)
Make a gamma correct in the raster.
{
  if (gamma <= 0) gamma = 0.01;
  raster->lock();
  if ((TRaster32P)raster)
    doGammaCorrect<TPixel32, UCHAR>(raster, gamma);
  else if ((TRaster64P)raster)
    doGammaCorrect<TPixel64, USHORT>(raster, gamma);
  else {
    raster->unlock();
    throw TRopException("isOpaque: unsupported pixel type");
  }
  raster->unlock();
}
Referenced by Previewer::Imp::onRenderRasterCompleted(), and MovieRenderer::Imp::saveFrame().
gammaCorrectRGBM()
void TRop::gammaCorrectRGBM (TRasterP raster, double gammar, double gammag, double gammab, double gammam)
Make a gamma correct in the raster.
{
  if (gammar <= 0) gammar = 0.01;
  if (gammag <= 0) gammag = 0.01;
  if (gammab <= 0) gammab = 0.01;
  if (gammam <= 0) gammam = 0.01;
  raster->lock();
  if ((TRaster32P)raster)
    doGammaCorrectRGBM<TPixel32, UCHAR>(raster, gammar, gammag, gammab, gammam);
  else if ((TRaster64P)raster)
    doGammaCorrectRGBM<TPixel64, USHORT>(raster, gammar, gammag, gammab,
                                         gammam);
  else {
    raster->unlock();
    throw TRopException("isOpaque: unsupported pixel type");
  }
  raster->unlock();
}
getBlurBorder()
int TRop::getBlurBorder (double blur)
Return the pixel size of the blur border.
{
  int brad = (int)ceil(blur); /* number of pixels involved in the filtering */
  int border = brad * 2;  // per sicurezza
  return border;
}
glassRaylit()
void TRop::glassRaylit (const TRasterP & dstRas, const TRasterP & srcRas, const RaylitParams & params)
{
  if ((TRaster32P)dstRas && (TRaster32P)srcRas)
    doRaylit<TPixel32>(srcRas, dstRas, params, &performColorRaylit<TPixel32>);
  else if ((TRaster64P)dstRas && (TRaster64P)srcRas)
    doRaylit<TPixel64>(srcRas, dstRas, params, &performColorRaylit<TPixel64>);
  else
    throw TException("TRop::raylit unsupported pixel type");
}
invert()
void TRop::invert (TRasterP ras, bool invRed = true, bool invGreen = true, bool invBlue = true, bool invMatte = false)
Invert ras color in according with invRed, invGreen, invBlue, invMatte
{
  if (!invRed && !invGreen && !invBlue) return;
  bool flag = invRed && invGreen && invBlue && !invMatte;
  TRaster32P ras32 = ras;
  ras->lock();
  if (ras32)
    if (flag)
      do_invert<TPixel32>(ras32);
    else
      do_invert<TPixel32>(ras, invRed, invGreen, invBlue, invMatte);
  else {
    TRaster64P ras64 = ras;
    if (ras64)
      if (flag)
        do_invert<TPixel64>(ras64);
      else
        do_invert<TPixel64>(ras64, invRed, invGreen, invBlue, invMatte);
    else {
      TRasterGR8P ras8 = ras;
      if (ras8)
        do_invert<TPixelGR8>(ras8);
      else {
        ras->unlock();
        throw TRopException("unsupported pixel type");
      }
    }
  }
  ras->unlock();
}
isOpaque()
bool TRop::isOpaque (TRasterP ras)
Return true if ras is opaque.
{
  TRaster32P ras32 = ras;
  if (ras32)
    return isOpaque32(ras32);
  else if (TRasterGR8P(ras))
    return true;
  else
    throw TRopException("isOpaque: unsupported pixel type");
}
lighten()
void TRop::lighten (const TRasterP & rup, const TRasterP & rdown, const TRasterP & rout)
{
  TRaster32P up32   = rup;
  TRaster32P down32 = rdown;
  TRaster32P out32  = rout;
  TRaster64P up64   = rup;
  TRaster64P down64 = rdown;
  TRaster64P out64  = rout;
  if (up32 && down32 && out32) {
    FOR_EACH_PIXEL_32_BEGIN_LOOP
    double value0 = luminance(upPix);
    double value1 = luminance(downPix);
    if (value0 > value1) {
      TINT32 r, g, b, m;
      if (upPix->m == 0)
        *outPix = *downPix;
      else {
        r         = downPix->r + upPix->r;
        g         = downPix->g + upPix->g;
        b         = downPix->b + upPix->b;
        m         = downPix->m + upPix->m;
        outPix->r = (UCHAR)tcrop<TINT32>(r, (TINT32)0, (TINT32)255);
        outPix->g = (UCHAR)tcrop<TINT32>(g, (TINT32)0, (TINT32)255);
        outPix->b = (UCHAR)tcrop<TINT32>(b, (TINT32)0, (TINT32)255);
        outPix->m = (UCHAR)tcrop<TINT32>(m, (TINT32)0, (TINT32)255);
      }
    } else {
      *outPix = *downPix;
    }
    FOR_EACH_PIXEL_32_END_LOOP
  } else if (up64 && down64 && out64) {
    FOR_EACH_PIXEL_64_BEGIN_LOOP
    double value0 = luminance(upPix);
    double value1 = luminance(downPix);
    if (value0 > value1) {
      TINT32 r, g, b, m;
      if (upPix->m == 0)
        *outPix = *downPix;
      else {
        r         = downPix->r + upPix->r;
        g         = downPix->g + upPix->g;
        b         = downPix->b + upPix->b;
        m         = downPix->m + upPix->m;
        outPix->r = (USHORT)tcrop<TINT32>(r, (TINT32)0, (TINT32)65535);
        outPix->g = (USHORT)tcrop<TINT32>(g, (TINT32)0, (TINT32)65535);
        outPix->b = (USHORT)tcrop<TINT32>(b, (TINT32)0, (TINT32)65535);
        outPix->m = (USHORT)tcrop<TINT32>(m, (TINT32)0, (TINT32)65535);
      }
    } else {
      *outPix = *downPix;
    }
    FOR_EACH_PIXEL_64_END_LOOP
  } else
    throw TRopException("TRop::lighten invalid raster combination");
}
linearburn()
void TRop::linearburn (const TRasterP & rup, const TRasterP & rdown, const TRasterP & rout)
{
  TRaster32P up32   = rup;
  TRaster32P down32 = rdown;
  TRaster32P out32  = rout;
  if (up32 && down32 && out32) {
    FOR_EACH_PIXEL_32_BEGIN_LOOP
    if (upPix->m) {
      TPixel32 app;
      if (downPix->m) {
        TINT32 r, g, b, m;
        TPixel32 tmpPix;
        tmpPix = depremultiply(*downPix);
        r      = tmpPix.r + upPix->r - 255;
        g      = tmpPix.g + upPix->g - 255;
        b      = tmpPix.b + upPix->b - 255;
        m      = tmpPix.m + upPix->m - 255;
        app.r = (UCHAR)tcrop<TINT32>(r, (TINT32)0, (TINT32)255);
        app.g = (UCHAR)tcrop<TINT32>(g, (TINT32)0, (TINT32)255);
        app.b = (UCHAR)tcrop<TINT32>(b, (TINT32)0, (TINT32)255);
        // app.m = (UCHAR)tcrop<TINT32> (m, (TINT32)0, (TINT32)255);
        app.m = upPix->m;
      } else
        app = *upPix;
      overPix<TPixel32, UCHAR>(*outPix, *downPix, app);
    }
    FOR_EACH_PIXEL_32_END_LOOP
  } else {
    TRaster64P up64   = rup;
    TRaster64P down64 = rdown;
    TRaster64P out64  = rout;
    if (up64 && down64 && out64) {
      FOR_EACH_PIXEL_64_BEGIN_LOOP
      if (upPix->m) {
        TPixel64 app;
        if (downPix->m) {
          TINT32 r, g, b, m;
          TPixel64 tmpPix;
          tmpPix = depremultiply(*downPix);
          r      = tmpPix.r + upPix->r - 65535;
          g      = tmpPix.g + upPix->g - 65535;
          b      = tmpPix.b + upPix->b - 65535;
          m      = tmpPix.m + upPix->m - 65535;
          app.r = (USHORT)tcrop<TINT32>(r, 0, 0xffff);
          app.g = (USHORT)tcrop<TINT32>(g, 0, 0xffff);
          app.b = (USHORT)tcrop<TINT32>(b, 0, 0xffff);
          // app.m = (UCHAR)tcrop<TINT32> (m, (TINT32)0, (TINT32)255);
          app.m = upPix->m;
        } else
          app = *upPix;
        overPix<TPixel64, USHORT>(*outPix, *downPix, app);
      }
      FOR_EACH_PIXEL_64_END_LOOP
    } else {
      TRasterGR8P up8   = rup;
      TRasterGR8P down8 = rdown;
      TRasterGR8P out8  = rout;
      if (up8 && down8 && out8) {
        FOR_EACH_PIXEL_8_BEGIN_LOOP
        USHORT value = troundp(upPix->value + downPix->value - 255);
        outPix->value = (UCHAR)tcrop<USHORT>(value, 0, 255);
        FOR_EACH_PIXEL_8_END_LOOP
      } else
        throw TRopException("TRop::max invalid raster combination");
    }
  }
}
lockRaster()
void TRop::lockRaster (_RASTER * raster)
Retrieves the input raster from Toonz internal cache. Need to call it before using the raster.
{
  TImageP img(TImageCache::instance()->get(
      std::string(raster->cacheId, raster->cacheIdLength), true));
  TRasterP cacheRas;
  if (raster->type == RAS_CM32)
    cacheRas = TToonzImageP(img)->getRaster();
  else
    cacheRas = TRasterImageP(img)->getRaster();
  cacheRas->addRef();
  raster->buffer  = cacheRas->getRawData();
  TRasterP parent = cacheRas->getParent();
  raster->native_buffer =
      (parent) ? parent->getRawData() : cacheRas->getRawData();
}
References TRaster::getRawData().
majorityDespeckle()
DVAPI void TRop::majorityDespeckle (const TRasterP & ras, int sizeThreshold)
Performs despeckling by replacing the color of small uniform areas (those enclosable in a square of specified edge length) with that most occurring along the area border.
makeIcon()
void TRop::makeIcon (TRasterCM32P & rout, const TRasterCM32P & rin)
{
  int i, j;
  int lx = rin->getLx();
  int ly = rin->getLy();
  TDimension dim(_rout->getSize());
  TRasterCM32P rout;
  rout = _rout;
  rout->lock();
  rin->lock();
  TPixelCM32 *pixOut0 = (TPixelCM32 *)rout->getRawData();
  int countY  = 0;
  bool newRow = true;
  for (i = 0; i < ly; i++) {
    TPixelCM32 *pixIn  = (TPixelCM32 *)rin->pixels(i);
    TPixelCM32 *pixOut = pixOut0;
    int countX         = 0;
    bool newColumn     = true;
    for (j = 0; j < lx; j++) {
      if ((newRow && newColumn) || pixOut->getTone() > pixIn->getTone())
        *pixOut = *pixIn;
      pixIn++;
      countX += dim.lx;
      if (countX >= lx) {
        countX -= lx, pixOut++;
        newColumn = true;
      } else
        newColumn = false;
    }
    countY += dim.ly;
    if (countY >= ly) {
      countY -= ly;
      pixOut0 += rout->getWrap();
      newRow = true;
    } else
      newRow = false;
  }
  rout->unlock();
  rin->unlock();
}
makeStereoRaster()
void TRop::makeStereoRaster (const TRasterP & left, const TRasterP & right)
{
  assert(left->getSize() == right->getSize());
  left->lock();
  if ((TRaster32P)left && (TRaster32P)right)
    doMakeStereoRaster<TPixel32>(left, right);
  else if ((TRaster64P)left && (TRaster64P)right)
    doMakeStereoRaster<TPixel64>(left, right);
  else {
    left->unlock();
    throw TRopException("setChannel: unsupported pixel type");
  }
  left->unlock();
}
mult()
void TRop::mult (const TRasterP & rup, const TRasterP & rdown, const TRasterP & rout, int v, bool matte)
{
  /*
Let U be 'up', D be 'down' and M be 'multiplied' (the result), and suppose for
the moment
that pixels are both NOT premultiplied and normalized to [0, 1].
The additional value v is used to add to RGB components of the U pixel:
U'_rgb = (U_rgb + v / 255)
The matte component is either U_m D_m in case (matte == true), or D_m in case
(matte == false).
Please, observe that in the case (matte == false) that choice makes the product
NOT COMMUTATIVE,
but I think that's justified - it's simply the most obvious use case.
In case (matte == true), each channel is multiplied independently, and that's
it.
The matter is more complicated when (matte == false). The problem in this case
is dealing with rgb
components when U and D both have some transparency.  When U is fully
transparent, we expect the
result to be D, and vice-versa, which is non-trivial.
We REQUIRE that (let's denote r only here):
M_r = M_r_u = U_r (1 - D_m) + U_r D_r D_m,   when  U_m == 1    (When U is fully
opaque, M_r is a D_m-linear
                                                                combination of
U_r and U_r D_r)
M_r = M_r_d = D_r (1 - U_m) + U_r D_r U_m,   when  D_m == 1    (Vice-versa, when
it's D that is fully opaque)
Finally, we're building a weighted sum, by U_m and D_m of the two above:
M_r = (M_r_u * U_m + M_r_d * D_m) / (U_m + D_m) =
    = (...) =
    = [ U_r U_m (1 - D_m) + D_r D_m (1 - U_m) + 2 U_r U_m  D_r D_m ] / (U_m +
D_m)
*/
  // 32-bit images case
  TRaster32P up32 = rup, down32 = rdown, out32 = rout;
  if (up32 && down32 && out32) {
    static const float maxChannelF = float(TPixel32::maxChannelValue);
    static const UCHAR maxChannelC = UCHAR(TPixel32::maxChannelValue);
    float vf = v;
    if (matte) {
      float dnMf, upMf_norm, outMf;
      FOR_EACH_PIXEL_32_BEGIN_LOOP  // Awful... should be explicit...
          dnMf  = downPix->m;
      upMf_norm = upPix->m / maxChannelF;
      outMf = downPix->m * upMf_norm;
      outPix->r =
          tcrop((upPix->r / upMf_norm + vf) * (downPix->r / dnMf), 0.0f, outMf);
      outPix->g =
          tcrop((upPix->g / upMf_norm + vf) * (downPix->g / dnMf), 0.0f, outMf);
      outPix->b =
          tcrop((upPix->b / upMf_norm + vf) * (downPix->b / dnMf), 0.0f, outMf);
      outPix->m = outMf;
      // NOTE:  + 0.5f in the crop arguments could take care of rounding...
      FOR_EACH_PIXEL_32_END_LOOP
    } else {
      float umf_norm, dmf_norm, umdmf_norm, outMf;
      float mSumf, uf, df, ufdf, normalizer;
      FOR_EACH_PIXEL_32_BEGIN_LOOP
      mSumf = upPix->m + float(downPix->m);
      if (mSumf > 0.0f) {
        umf_norm = upPix->m / maxChannelF, dmf_norm = downPix->m / maxChannelF;
        outMf = upPix->m +
                (1.0f - umf_norm) *
                    downPix->m;  // umf_norm should be ensured in [0.0, 1.0].
        // Convex combination should be in the conversion range.
        normalizer = outMf / (maxChannelF * mSumf);
        umdmf_norm = umf_norm * dmf_norm;
        uf = upPix->r + vf * umdmf_norm, df = downPix->r, ufdf = uf * df;
        outPix->r = tcrop((uf * (maxChannelC - downPix->m) +
                           df * (maxChannelC - upPix->m) + ufdf + ufdf) *
                              normalizer,
                          0.0f, outMf);
        uf = upPix->g + vf * umdmf_norm, df = downPix->g, ufdf = uf * df;
        outPix->g = tcrop((uf * (maxChannelC - downPix->m) +
                           df * (maxChannelC - upPix->m) + ufdf + ufdf) *
                              normalizer,
                          0.0f, outMf);
        uf = upPix->b + vf * umdmf_norm, df = downPix->b, ufdf = uf * df;
        outPix->b = tcrop((uf * (maxChannelC - downPix->m) +
                           df * (maxChannelC - upPix->m) + ufdf + ufdf) *
                              normalizer,
                          0.0f, outMf);
        outPix->m = outMf;
      } else
        *outPix = TPixel32::Transparent;
      FOR_EACH_PIXEL_32_END_LOOP
    }
    return;
  }
  // 64-bit images case
  TRaster64P up64 = rup, down64 = rdown, out64 = rout;
  if (up64 && down64 && out64) {
    static const double maxChannelF = double(TPixel64::maxChannelValue);
    static const USHORT maxChannelC = USHORT(TPixel64::maxChannelValue);
    double vf =
        v * (TPixel64::maxChannelValue / double(TPixel32::maxChannelValue));
    if (matte) {
      double dnMf, upMf_norm, outMf;
      FOR_EACH_PIXEL_64_BEGIN_LOOP
      dnMf      = downPix->m;
      upMf_norm = upPix->m / maxChannelF;
      outMf = downPix->m * upMf_norm;
      outPix->r =
          tcrop((upPix->r / upMf_norm + vf) * (downPix->r / dnMf), 0.0, outMf);
      outPix->g =
          tcrop((upPix->g / upMf_norm + vf) * (downPix->g / dnMf), 0.0, outMf);
      outPix->b =
          tcrop((upPix->b / upMf_norm + vf) * (downPix->b / dnMf), 0.0, outMf);
      outPix->m = outMf;
      FOR_EACH_PIXEL_64_END_LOOP
    } else {
      double umf_norm, dmf_norm, umdmf_norm, outMf;
      double mSumf, uf, df, ufdf, normalizer;
      FOR_EACH_PIXEL_64_BEGIN_LOOP
      mSumf = upPix->m + double(downPix->m);
      if (mSumf > 0.0) {
        umf_norm = upPix->m / maxChannelF, dmf_norm = downPix->m / maxChannelF;
        outMf = upPix->m + (1.0 - umf_norm) * downPix->m;
        normalizer = outMf / (maxChannelF * mSumf);
        umdmf_norm = umf_norm * dmf_norm;
        uf = upPix->r + vf * umdmf_norm, df = downPix->r, ufdf = uf * df;
        outPix->r = tcrop((uf * (maxChannelC - downPix->m) +
                           df * (maxChannelC - upPix->m) + ufdf + ufdf) *
                              normalizer,
                          0.0, outMf);
        uf = upPix->g + vf * umdmf_norm, df = downPix->g, ufdf = uf * df;
        outPix->g = tcrop((uf * (maxChannelC - downPix->m) +
                           df * (maxChannelC - upPix->m) + ufdf + ufdf) *
                              normalizer,
                          0.0, outMf);
        uf = upPix->b + vf * umdmf_norm, df = downPix->b, ufdf = uf * df;
        outPix->b = tcrop((uf * (maxChannelC - downPix->m) +
                           df * (maxChannelC - upPix->m) + ufdf + ufdf) *
                              normalizer,
                          0.0, outMf);
        outPix->m = outMf;
      } else
        *outPix = TPixel64::Transparent;
      FOR_EACH_PIXEL_64_END_LOOP
    }
    return;
  }
  // According to the specifics, throw an exception. I think it's not
  // appropriate, though.
  throw TRopException("TRop::mult invalid raster combination");
}
over() [1/7]
void TRop::over (const TRasterP & out, const TRasterP & dn, const TRasterP & up)
Make the image over of the up raster on the dn raster and put the resulting raster in rout
{
  TRect rect = rout->getBounds() * rdn->getBounds() * rup->getBounds();
  if (rect.isEmpty()) return;
  TRasterP cRout = rout->extract(rect);
  TRasterP cRdn  = rdn->extract(rect);
  TRasterP cRup  = rup->extract(rect);
  rout->lock();
  rdn->lock();
  rup->lock();
  TRaster32P rout32 = cRout, rdn32 = cRdn, rup32 = cRup;
  TRaster64P rout64 = cRout, rdn64 = cRdn, rup64 = cRup;
  if (rout32 && rdn32 && rup32)
    do_overT3<TPixel32>(rout32, rdn32, rup32);
  else if (rout64 && rdn64 && rup64)
    do_overT3<TPixel64>(rout64, rdn64, rup64);
  else {
    rout->unlock();
    rdn->unlock();
    rup->unlock();
    throw TRopException("unsupported pixel type");
  }
  rout->unlock();
  rdn->unlock();
  rup->unlock();
}
References TRectT< T >::isEmpty().
Referenced by over(), OverFx::process(), and ToonzScene::renderFrame().
over() [2/7]
void TRop::over (const TRasterP & out, const TRasterP & dn, const TRasterP & up, const TRasterGR8P & mask)
Make the image over of the up raster on the dn raster using a mask and put the resulting raster in rout
{
  out->lock();
  up->lock();
  dn->lock();
  TRaster32P out32 = out;
  TRaster32P dn32  = dn;
  TRaster32P up32  = up;
  if (out32 && dn32 && up32)
    do_over<TPixel32, TPixel32, TPixel32>(out32, dn32, up32, mask);
  else {
    TRaster64P out64 = out;
    TRaster64P dn64  = dn;
    TRaster64P up64  = up;
    if (out64 && dn64 && up64)
      do_over<TPixel64, TPixel64, TPixel64>(out64, dn64, up64, mask);
    else
      throw TRopException("unsupported pixel type");
  }
  out->unlock();
  up->unlock();
  dn->unlock();
}
over() [3/7]
void TRop::over (const TRasterP & out, const TRasterP & up, const TAffine & aff, ResampleFilterType filterType = Triangle)
Make the image over of the up raster on the out raster.
{
  out->lock();
  up->lock();
  if (filterType == ClosestPixel || filterType == Bilinear)
    ::quickPut(out, up, aff, filterType);
  else {
    TRect rasterBounds = up->getBounds();
    TRectD dbounds(rasterBounds.x0, rasterBounds.y0, rasterBounds.x1 + 1,
                   rasterBounds.y1 + 1);
    dbounds = aff * dbounds;
    TRect bounds(tfloor(dbounds.x0), tfloor(dbounds.y0), tceil(dbounds.x1) - 1,
                 tceil(dbounds.y1) - 1);
    TRasterP tmp = up->create(bounds.getLx(), bounds.getLy());
    resample(tmp, up, TTranslation(-bounds.x0, -bounds.y0) * aff, filterType);
    over(out, tmp, bounds.getP00());
  }
  out->unlock();
  up->unlock();
}
References Bilinear, ClosestPixel, resample(), and TRectT< T >::x0.
over() [4/7]
void TRop::over (const TRasterP & out, const TRasterP & up, const TPoint & pos, const TAffine & aff, ResampleFilterType filterType = Triangle)
Make the image over of the up raster on the out raster starting from pos. Position pos must be already transformed using aff.
{
  if (aff.isIdentity())
    // simple over with offset
    TRop::over(out, up, pos);
  else {
    TRect rasterBounds = up->getBounds();
    TRectD dbounds(rasterBounds.x0, rasterBounds.y0, rasterBounds.x1,
                   rasterBounds.y1);
    dbounds = aff * dbounds;
    TRect bounds(tfloor(dbounds.x0), tfloor(dbounds.y0), tceil(dbounds.x1),
                 tceil(dbounds.y1));
    TRasterP tmp = up->create(bounds.getLx(), bounds.getLy());
    resample(tmp, up, TTranslation(-dbounds.getP00()) * aff, filterType);
    TRop::over(out, tmp, pos);
  }
}
References TAffine::isIdentity(), over(), resample(), and TRectT< T >::x0.
over() [5/7]
void TRop::over (const TRasterP & out, const TRasterP & up, const TPoint & pos = TPoint())
Make the image over of the up raster on the out raster starting from pos
{
  TRect outRect(rout->getBounds());
  TRect upRect(rup->getBounds() + pos);
  TRect intersection = outRect * upRect;
  if (intersection.isEmpty()) return;
  TRasterP cRout = rout->extract(intersection);
  TRect r        = intersection - pos;
  TRasterP cRup  = rup->extract(r);
  TRaster32P rout32 = cRout, rup32 = cRup;
  TRaster64P rout64 = cRout, rup64 = cRup;
  TRasterGR8P rout8 = cRout, rup8 = cRup;
  TRasterCM32P routCM32 = cRout, rupCM32 = cRup;
  rout->lock();
  rup->lock();
  // TRaster64P rout64 = rout, rin64 = rin;
  if (rout32 && rup32) {
#ifdef USE_SSE2
    if (TSystem::getCPUExtensions() & TSystem::CpuSupportsSse2)
      do_over_SSE2(rout32, rup32);
    else
#endif
      do_overT2<TPixel32, UCHAR>(rout32, rup32);
  } else if (rout64) {
    if (!rup64) {
      TRaster64P raux(cRup->getSize());
      TRop::convert(raux, cRup);
      rup64 = raux;
    }
    do_overT2<TPixel64, USHORT>(rout64, rup64);
  } else if (rout32 && rup8)
    do_over(rout32, rup8);
  else if (rout8 && rup32)
    do_over(rout8, rup32);
  else if (rout8 && rup8)
    TRop::copy(rout8, rup8);
  else if (routCM32 && rupCM32)
    do_over(routCM32, rupCM32);
  else {
    rout->unlock();
    rup->unlock();
    throw TRopException("unsupported pixel type");
  }
  rout->unlock();
  rup->unlock();
}
References convert(), and copy().
over() [6/7]
void TRop::over (TRaster32P rout, const TRasterGR8P & rup, const TPixel32 & color)
Make a coloring of rup with color and put the resulting raster in rout
{
  rout->lock();
  do_over(rout, rup, color);
  rout->unlock();
}
over() [7/7]
void TRop::over (TRasterP rout, const TRasterCM32P & rup, TPalette * palette, const TPoint & point = TPoint(), const TAffine & aff = TAffine())
{
  TRaster32P app(rup->getSize());
  TRop::convert(app, rup, palette);
  TRop::over(rout, app, point, aff);
}
overlay()
void TRop::overlay (const TRasterP & rup, const TRasterP & rdown, const TRasterP & rout)
{
  TRaster32P up32   = rup;
  TRaster32P down32 = rdown;
  TRaster32P out32  = rout;
  if (up32 && down32 && out32) {
    FOR_EACH_PIXEL_32_BEGIN_LOOP
    if (upPix->m) {
      TPixel32 app;
      TPixel32 tmpPix, tmp2Pix;
      if (downPix->m) {
        tmpPix  = *downPix;
        tmp2Pix = depremultiply(*upPix);
        if (tmpPix.r < 128)
          app.r = troundp(2 * tmp2Pix.r * (tmpPix.r / 255.0));
        else {
          SHORT r =
              255 *
              (1 - 2 * (1.0 - tmpPix.r / 255.0) * (1.0 - tmp2Pix.r / 255.0));
          app.r = (UCHAR)tcrop<SHORT>(r, 0, 255);
        }
        if (tmpPix.g < 128)
          app.g = troundp(2 * tmp2Pix.g * (tmpPix.g / 255.0));
        else {
          SHORT g =
              255 *
              (1 - 2 * (1.0 - tmpPix.g / 255.0) * (1.0 - tmp2Pix.g / 255.0));
          app.g = (UCHAR)tcrop<SHORT>(g, 0, 255);
        }
        if (tmpPix.b < 128)
          app.b = troundp(2 * tmp2Pix.b * (tmpPix.b / 255.0));
        else {
          SHORT b =
              255 *
              (1 - 2 * (1.0 - tmpPix.b / 255.0) * (1.0 - tmp2Pix.b / 255.0));
          app.b = (UCHAR)tcrop<SHORT>(b, 0, 255);
        }
        app.m = tmp2Pix.m;
        app   = premultiply(app);
      } else
        app = *upPix;
      overPix<TPixel32, UCHAR>(*outPix, *downPix, app);
    }
    FOR_EACH_PIXEL_32_END_LOOP
  } else {
    TRaster64P up64   = rup;
    TRaster64P down64 = rdown;
    TRaster64P out64  = rout;
    if (up64 && down64 && out64) {
      FOR_EACH_PIXEL_64_BEGIN_LOOP
      if (upPix->m) {
        TPixel64 app;
        TPixel64 tmpPix, tmp2Pix;
        if (downPix->m) {
          tmpPix  = *downPix;
          tmp2Pix = depremultiply(*upPix);
          if (tmpPix.r < 32768)
            app.r = troundp(2 * tmp2Pix.r * (tmpPix.r / 65535.0));
          else {
            SHORT r = 65535 * (1 -
                               2 * (1.0 - tmpPix.r / 65535.0) *
                                   (1.0 - tmp2Pix.r / 65535.0));
            app.r = (USHORT)tcrop<TINT32>(r, 0, 65535);
          }
          if (tmpPix.g < 32768)
            app.g = troundp(2 * tmp2Pix.g * (tmpPix.g / 65535.0));
          else {
            SHORT g = 65535 * (1 -
                               2 * (1.0 - tmpPix.g / 65535.0) *
                                   (1.0 - tmp2Pix.g / 65535.0));
            app.g = (USHORT)tcrop<TINT32>(g, 0, 65535);
          }
          if (tmpPix.b < 32768)
            app.b = troundp(2 * tmp2Pix.b * (tmpPix.b / 65535.0));
          else {
            SHORT b = 65535 * (1 -
                               2 * (1.0 - tmpPix.b / 65535.0) *
                                   (1.0 - tmp2Pix.b / 65535.0));
            app.b = (USHORT)tcrop<TINT32>(b, 0, 65535);
          }
          app.m = tmp2Pix.m;
          app   = premultiply(app);
        } else
          app = *upPix;
        overPix<TPixel64, USHORT>(*outPix, *downPix, app);
      }
      FOR_EACH_PIXEL_64_END_LOOP
    } else {
      TRasterGR8P up8   = rup;
      TRasterGR8P down8 = rdown;
      TRasterGR8P out8  = rout;
      if (up8 && down8 && out8) {
        FOR_EACH_PIXEL_8_BEGIN_LOOP
        USHORT value;
        if (downPix->value < 128)
          value = troundp(2 * upPix->value * (downPix->value / 255.0));
        else
          value = 255 * (1 -
                         2 * (1.0 - downPix->value / 255.0) *
                             (1.0 - upPix->value / 255.0));
        outPix->value = (UCHAR)tcrop<USHORT>(value, 0, 255);
        FOR_EACH_PIXEL_8_END_LOOP
      } else
        throw TRopException("TRop::max invalid raster combination");
    }
  }
}
overlayCmapped()
void TRop::overlayCmapped (TRasterCM32P rasOut, const TRasterCM32P & rasUp, const TPaletteP & pltOut, const TPaletteP & upPlt, std::map< int, int > & usedColors)
{
  assert(rasOut && rasUp);
  assert(rasOut->getSize() == rasUp->getSize());
  TPaletteP downPlt = pltOut->clone();
  std::map<int, int>::iterator it;
  for (it = usedColors.begin(); it != usedColors.end(); it++)
    downPlt->getPage(0)->addStyle(TPixel32::Red);
  for (int y = 0; y < rasOut->getLy(); y++) {
    TPixelCM32 *pixDown = rasOut->pixels(y);
    TPixelCM32 *pixUp   = rasUp->pixels(y);
    for (int x = 0; x < rasOut->getLx(); x++, pixUp++, pixDown++) {
      if (isTransparent(pixUp))  // WARNING! cannot check transparent pixels
                                 // with *pixup==TPixelCM32() since also
                                 // 0x183000ff i.e., is a valid transparent
                                 // value
        continue;
      int tone = pixUp->getTone();
      if (isTransparent(pixDown) || tone == 255 || tone == 0 ||
          pixUp->getPaint() !=
              0)  // up e' punto interno, o esterno non antialiasato
      {
        addColors(*pixUp, downPlt, upPlt, usedColors);
        pixDown->setInk(usedColors[pixUp->getInk()]);
        pixDown->setPaint(usedColors[pixUp->getPaint()]);
        pixDown->setTone(tone);
      } else if (tone <= pixDown->getTone() || tone < 128)  // up e' bordo
                                                            // esterno
                                                            // antialiasato piu'
                                                            // opaco di down
      {
        int ink = pixUp->getInk();
        if (usedColors.find(ink) == usedColors.end())
          addColor(downPlt, ink, upPlt, usedColors);
        pixDown->setInk(usedColors[ink]);
        pixDown->setTone(tone < 128 ? 0 : tone);
      }
    }
  }
}
premultiply()
void TRop::premultiply (const TRasterP & ras)
Make a premultiply of all raster pixels.
{
  ras->lock();
  TRaster32P ras32 = ras;
  if (ras32) {
    TPixel32 *endPix, *upPix = 0, *upRow = ras32->pixels();
    TPixel32 *lastPix =
        upRow + ras32->getWrap() * (ras32->getLy() - 1) + ras32->getLx();
    while (upPix < lastPix) {
      upPix  = upRow;
      endPix = upPix + ras32->getLx();
      while (upPix < endPix) {
        premult(*upPix);
        ++upPix;
      }
      upRow += ras32->getWrap();
    }
  } else {
    TRaster64P ras64 = ras;
    if (ras64) {
      TPixel64 *endPix, *upPix = 0, *upRow = ras64->pixels();
      TPixel64 *lastPix =
          upRow + ras64->getWrap() * (ras64->getLy() - 1) + ras64->getLx();
      while (upPix < lastPix) {
        upPix  = upRow;
        endPix = upPix + ras64->getLx();
        while (upPix < endPix) {
          premult(*upPix);
          ++upPix;
        }
        upRow += ras64->getWrap();
      }
    } else {
      ras->unlock();
      throw TException("TRop::premultiply invalid raster type");
    }
  }
  ras->unlock();
}
Referenced by applyColorScale().
quickPut() [1/3]
void TRop::quickPut (const TRasterP & dn, const TRasterCM32P & upCM32, const TPaletteP & plt, const TAffine & aff, const CmappedQuickputSettings & settings)
{
  TRaster32P dn32 = dn;
  if (dn32 && upCM32)
    doQuickPutCmapped(dn32, upCM32, plt, aff,
                      settings);  // globalColorScale, inksOnly,
                                  // transparencyCheck, blackBgCheck, inkIndex,
                                  // paintIndex);
  else
    throw TRopException("raster type mismatch");
}
quickPut() [2/3]
void TRop::quickPut (const TRasterP & out, const TRasterCM32P & up, const TPaletteP & plt, const TAffine & aff, const TPixel32 & globalColorScale = TPixel::Black, bool inksOnly = false)
Like the over function but up image must be cmapped.
Only uses closest_pixel filter. GlobalMatte is the opacity, used for onionskinning
{
  TRaster32P dn32 = dn;
  if (dn32 && upCM32)
    if (areAlmostEqual(aff.a12, 0) && areAlmostEqual(aff.a21, 0))
      doQuickPutCmapped(dn32, upCM32, plt, aff.a11, aff.a22, aff.a13, aff.a23,
                        globalColorScale, inksOnly);
    else
      doQuickPutCmapped(dn32, upCM32, plt, aff, globalColorScale, inksOnly);
  else
    throw TRopException("raster type mismatch");
}
quickPut() [3/3]
void TRop::quickPut (const TRasterP & out, const TRasterP & up, const TAffine & aff, const TPixel32 & colorScale = TPixel::Black, bool doPremultiply = false, bool whiteTransp = false, bool firstColumn = false, bool doRasterDarkenBlendedView = false)
Like the over function, but only uses closest_pixel filter.
{
  ::quickPut(out, up, aff, ClosestPixel, colorScale, doPremultiply, whiteTransp,
             firstColumn, doRasterDarkenBlendedView);
}
References ClosestPixel, and whiteTransp().
quickResampleColorFilter()
void TRop::quickResampleColorFilter (const TRasterP & dn, const TRasterP & up, const TAffine & aff, const TPaletteP & plt, UCHAR colorMask)
{
  TRaster32P dn32     = dn;
  TRaster32P up32     = up;
  TRaster64P up64     = up;
  TRasterCM32P upCM32 = up;
  if (dn32 && up32)
    doQuickResampleColorFilter(dn32, up32, aff, colorMask);
  else if (dn32 && upCM32)
    doQuickResampleColorFilter(dn32, upCM32, plt, aff, colorMask);
  else if (dn32 && up64)
    doQuickResampleColorFilter(dn32, up64, aff, colorMask);
  // else if (dn32 && upCM32)
  //  doQuickResampleColorFilter(dn32, upCM32, aff, plt, colorMask);
  else
    throw TRopException("raster type mismatch");
}
raylit()
void TRop::raylit (const TRasterP & dstRas, const TRasterP & srcRas, const RaylitParams & params)
Make raylit effect on srcRas raster and put the result in dstRas.
{
  if ((TRaster32P)dstRas && (TRaster32P)srcRas)
    doRaylit<TPixel32>(srcRas, dstRas, params,
                       &performStandardRaylit<TPixel32>);
  else if ((TRaster64P)dstRas && (TRaster64P)srcRas)
    doRaylit<TPixel64>(srcRas, dstRas, params,
                       &performStandardRaylit<TPixel64>);
  else
    throw TException("TRop::raylit unsupported pixel type");
}
readRaster46()
_RASTER * TRop::readRaster46 (const char * filename)
Read an image in the path filename and put it in an old toonz raster.
{
  // No more called in Toonz...
  TImageP img;
  TImageReader::load(TFilePath(filename), img);
  if ((TToonzImageP)img) return 0;
  TRasterImageP rimg = (TRasterImageP)img;
  if (!rimg) return 0;
  TRasterP ras = rimg->getRaster();
  return TRop::convertRaster50to46(ras, 0);
}
References convertRaster50to46(), and TImageReader::load().
releaseRaster46()
void TRop::releaseRaster46 (_RASTER *& r, bool doReleaseBuffer = false)
Release the old toonz raster.
If the doReleaseBuffer is true, the buffer is released (the palette is always deleted!)
{
  // Buffer release no more supported. These are now intended as smart
  // pointers to rasters - they release themselves on their own.
  assert(!doReleaseBuffer);
  if (r->type == RAS_CM32) {
    delete[] r->cmap.buffer;
    // delete [] r->cmap.penbuffer;
    // delete [] r->cmap.colbuffer;
  }
  if (doReleaseBuffer && r->native_buffer == r->buffer)
    delete r->buffer;  // Should not happen
  // Unlock if locked, and remove the cache reference
  if (r->buffer) unlockRaster(r);
  TImageCache::instance()->remove(std::string(r->cacheId, r->cacheIdLength));
  delete[] r->cacheId;
  delete r;
  r = 0;
}
References TImageCache::remove(), and unlockRaster().
resample() [1/2]
void TRop::resample (const TRasterP & out, const TRasterCM32P & in, const TPaletteP palette, const TAffine & aff, TRop::ResampleFilterType filterType = Triangle, double blur = 1.)
{
  TRasterP rin      = in;
  TRaster32P rout32 = out;
  in->lock();
  out->lock();
  if (rout32)
    rop_resample_rgbm_2<TPixel32>(rout32, rin, aff, filterType, blur,
                                  palette.getPointer());
  else {
    TRaster64P rout64 = out;
    if (rout64)
      rop_resample_rgbm_2<TPixel64>(rout64, rin, aff, filterType, blur,
                                    palette.getPointer());
    else {
      in->unlock();
      out->unlock();
      throw TRopException("unsupported pixel type");
      return;
    }
  }
  in->unlock();
  out->unlock();
}
resample() [2/2]
void TRop::resample (const TRasterP & out, const TRasterP & in, const TAffine & aff, ResampleFilterType filterType = Triangle, double blur = 1.)
Apply the transformation aff to the raster in and put the resulting raster in rout
It can be specified a resample filter type and a blur factor.
{
  rin->lock();
  rout->lock();
  if (filterType == ClosestPixel || filterType == Bilinear) {
    if ((TRaster64P)rout || (TRaster64P)rin)
      filterType = Triangle;
    else {
      quickResample(rout, rin, aff, filterType);
      rin->unlock();
      rout->unlock();
      return;
    }
  }
  TRaster32P rout32 = rout, rin32 = rin;
  if (rout32) {
    if (!rin32) {
      rin32 = TRaster32P(rin->getLx(), rin->getLy());
      TRop::convert(rin32, rin);
    }
    do_resample<TPixel32>(rout32, rin32, aff, filterType, blur);
  } else {
#ifndef TNZCORE_LIGHT
    TRasterCM32P routCM32 = rout, rinCM32 = rin;
    if (routCM32 && rinCM32)
      do_resample(routCM32, rinCM32, aff);
    else
#endif
    {
      TRaster64P rout64 = rout, rin64 = rin;
      if (rout64) {
        if (!rin64) {
          rin64 = TRaster64P(rin->getLx(), rin->getLy());
          TRop::convert(rin64, rin);
        }
        do_resample<TPixel64>(rout64, rin64, aff, filterType, blur);
      } else {
        TRasterGR8P routGR8 = rout, rinGR8 = rin;
        TRaster32P rin32 = rin;
        if (routGR8 && rinGR8)
          do_resample(routGR8, rinGR8, aff, filterType, blur);
        else if (routGR8 && rin32)
          do_resample(routGR8, rin32, aff, filterType, blur);
        else {
          rin->unlock();
          rout->unlock();
          throw TRopException("unsupported pixel type");
        }
      }
    }
  }
  rin->unlock();
  rout->unlock();
}
References Bilinear, ClosestPixel, convert(), and Triangle.
Referenced by TRasterImage::makeIcon(), over(), TCleanupper::process(), and CustomStyleManager::StyleLoaderTask::run().
rgbmAdjust()
void TRop::rgbmAdjust (TRasterP rout, TRasterP rin, const int * in0, const int * in1, const int * out0, const int * out1)
Transforms each input channel interval into the corresponding channel interval, cropping values if necessary.
Specified pointers are associated to int[5] arrays representing the 5-ple (RGB, R, G, B, M) - where RGBM adjustment apply first. Then, Global apply equally on RGB channels (but not on M).
Note
The input and output rasters must have the same size and pixel type. Supports rout == rin.
{
  if (rout->getSize() != rin->getSize()) throw TRopException("size mismatch");
  rout->lock();
  rin->lock();
  if ((TRaster32P)rout && (TRaster32P)rin)
    do_rgbmAdjust<TPixel32>(rout, rin, &do_rgbmScale_lut<TPixel32>, in0, in1,
                            out0, out1);
  else if ((TRaster64P)rout && (TRaster64P)rin) {
    if (rin->getLx() * rin->getLy() < TPixel64::maxChannelValue)
      do_rgbmAdjust<TPixel64>(rout, rin, &do_rgbmScale<TPixel64>, in0, in1,
                              out0, out1);
    else
      do_rgbmAdjust<TPixel64>(rout, rin, &do_rgbmScale_lut<TPixel64>, in0, in1,
                              out0, out1);
  } else if ((TRasterGR8P)rout && (TRasterGR8P)rin)
    do_greyAdjust<TPixelGR8>(rout, rin, in0[0], in1[0], out0[0], out1[0]);
  else if ((TRasterGR16P)rout && (TRasterGR16P)rin)
    do_greyAdjust<TPixelGR16>(rout, rin, in0[0], in1[0], out0[0], out1[0]);
  else {
    rout->unlock();
    rin->unlock();
    throw TRopException("pixel type mismatch");
  }
  rout->unlock();
  rin->unlock();
}
rgbmScale() [1/2]
void TRop::rgbmScale (TRasterP rout, TRasterP rin, const double * k, const double * a, const int * out0, const int * out1)
Applies first order mappings to each of rin's channels.
Note
The input and output rasters must have the same size and pixel type. Supports rout == rin.
{
  if (rout->getSize() != rin->getSize()) throw TRopException("size mismatch");
  rout->lock();
  rin->lock();
  if ((TRaster32P)rout && (TRaster32P)rin)
    do_rgbmScale_lut<TPixel32>(rout, rin, a, k, out0, out1);
  else if ((TRaster64P)rout && (TRaster64P)rin) {
    if (rin->getLx() * rin->getLy() < TPixel64::maxChannelValue)
      do_rgbmScale<TPixel64>(rout, rin, a, k, out0, out1);
    else
      do_rgbmScale_lut<TPixel64>(rout, rin, a, k, out0, out1);
  } else if ((TRasterGR8P)rout && (TRasterGR8P)rin)
    do_greyScale_lut<TPixelGR8>(rout, rin, a[0], k[0], out0[0], out1[0]);
  else if ((TRasterGR16P)rout && (TRasterGR16P)rin)
    do_greyScale_lut<TPixelGR16>(rout, rin, a[0], k[0], out0[0], out1[0]);
  else {
    rout->unlock();
    rin->unlock();
    throw TRopException("pixel type mismatch");
  }
  rout->unlock();
  rin->unlock();
}
rgbmScale() [2/2]
void TRop::rgbmScale (TRasterP rout, TRasterP rin, double kr, double kg, double kb, double km, double ar = 0.0, double ag = 0.0, double ab = 0.0, double am = 0.0)
{
  double k[4], a[4];
  a[0] = ar, a[1] = ag, a[2] = ab, a[3] = am;
  k[0] = kr, k[1] = kg, k[2] = kb, k[3] = km;
  int out0[4], out1[4];
  out0[0] = out0[1] = out0[2] = out0[3] = 0;
  out1[0] = out1[1] = out1[2] = out1[3] = 255;
  rgbmScale(rout, rin, k, a, out0, out1);
}
ropin()
void TRop::ropin (const TRasterP & source, const TRasterP & matte, const TRasterP & rout)
{
  TRaster32P source32 = source;
  TRaster32P matte32  = matte;
  TRaster32P out32    = rout;
  TRaster64P source64 = source;
  TRaster64P matte64  = matte;
  TRaster64P out64    = rout;
  if (source32 && matte32 && out32) {
    FOR_EACH_PIXEL_BEGIN_LOOP(TPixelRGBM32, source32, TPixelRGBM32, matte32,
                              TPixelRGBM32, out32)
    if (downPix->m == 0)
      outPix->r = outPix->g = outPix->b = outPix->m = 0;
    else if (downPix->m == 255)
      *outPix = *upPix;
    else {
      /*
__m128i zeros = _mm_setzero_si128();
__m128i upPix_packed_i= _mm_unpacklo_epi8(_mm_cvtsi32_si128(*(DWORD*)upPix),
zeros);
__m128  upPix_packed  = _mm_cvtepi32_ps(_mm_unpacklo_epi16(upPix_packed_i,
zeros));
float fac = downPix->m / 255.0;
__m128 fac_packed = _mm_load1_ps(&fac);
upPix_packed = _mm_mul_ps(upPix_packed, fac_packed);
__m128i outPix_packed_i = _mm_cvtps_epi32(upPix_packed);
outPix_packed_i = _mm_packs_epi32(outPix_packed_i, zeros);
outPix_packed_i = _mm_packus_epi16(outPix_packed_i, zeros);
*(DWORD*)(outPix) = _mm_cvtsi128_si32(outPix_packed_i);
*/
      const int MAGICFAC = (257U * 256U + 1U);
      UINT fac           = MAGICFAC * downPix->m;
      outPix->r = (UINT)(upPix->r * fac + (1U << 23)) >> 24;
      outPix->g = (UINT)(upPix->g * fac + (1U << 23)) >> 24;
      outPix->b = (UINT)(upPix->b * fac + (1U << 23)) >> 24;
      outPix->m = (UINT)(upPix->m * fac + (1U << 23)) >> 24;
    }
    FOR_EACH_PIXEL_END_LOOP(source32, matte32, out32)
  } else if (source64 && matte64 && out64)
  {
    FOR_EACH_PIXEL_BEGIN_LOOP(TPixelRGBM64, source64, TPixelRGBM64, matte64,
                              TPixelRGBM64, out64)
    if (downPix->m == 0)
      outPix->r = outPix->g = outPix->b = outPix->m = 0;
    else if (downPix->m == 65535)
      *outPix = *upPix;
    else {
      /*
__m128i zeros = _mm_setzero_si128();
__m128i upPix_packed_i= _mm_unpacklo_epi8(_mm_cvtsi32_si128(*(DWORD*)upPix),
zeros);
__m128  upPix_packed  = _mm_cvtepi32_ps(_mm_unpacklo_epi16(upPix_packed_i,
zeros));
float fac = downPix->m / 255.0;
__m128 fac_packed = _mm_load1_ps(&fac);
upPix_packed = _mm_mul_ps(upPix_packed, fac_packed);
__m128i outPix_packed_i = _mm_cvtps_epi32(upPix_packed);
outPix_packed_i = _mm_packs_epi32(outPix_packed_i, zeros);
outPix_packed_i = _mm_packus_epi16(outPix_packed_i, zeros);
*(DWORD*)(outPix) = _mm_cvtsi128_si32(outPix_packed_i);
*/
      double fac = downPix->m / 65535.0;
      outPix->r = (USHORT)(upPix->r * fac);
      outPix->g = (USHORT)(upPix->g * fac);
      outPix->b = (USHORT)(upPix->b * fac);
      outPix->m = (USHORT)(upPix->m * fac);
    }
    FOR_EACH_PIXEL_END_LOOP(source64, matte64, out64)
  } else
    throw TRopException("TRop::in invalid raster combination");
}
ropmax()
void TRop::ropmax (const TRasterP & rup, const TRasterP & rdown, const TRasterP & rout)
{
  TRaster32P up32   = rup;
  TRaster32P down32 = rdown;
  TRaster32P out32  = rout;
  if (up32 && down32 && out32) {
    FOR_EACH_PIXEL_32_BEGIN_LOOP
    outPix->r = upPix->r > downPix->r ? upPix->r : downPix->r;
    outPix->g = upPix->g > downPix->g ? upPix->g : downPix->g;
    outPix->b = upPix->b > downPix->b ? upPix->b : downPix->b;
    outPix->m = upPix->m > downPix->m ? upPix->m : downPix->m;
    FOR_EACH_PIXEL_32_END_LOOP
  } else {
    TRaster64P up64   = rup;
    TRaster64P down64 = rdown;
    TRaster64P out64  = rout;
    if (up64 && down64 && out64) {
      FOR_EACH_PIXEL_64_BEGIN_LOOP
      outPix->r = upPix->r > downPix->r ? upPix->r : downPix->r;
      outPix->g = upPix->g > downPix->g ? upPix->g : downPix->g;
      outPix->b = upPix->b > downPix->b ? upPix->b : downPix->b;
      outPix->m = upPix->m > downPix->m ? upPix->m : downPix->m;
      FOR_EACH_PIXEL_64_END_LOOP
    } else {
      TRasterGR8P up8   = rup;
      TRasterGR8P down8 = rdown;
      TRasterGR8P out8  = rout;
      if (up8 && down8 && out8) {
        FOR_EACH_PIXEL_8_BEGIN_LOOP
        outPix->value =
            upPix->value > downPix->value ? upPix->value : downPix->value;
        FOR_EACH_PIXEL_8_END_LOOP
      } else
        throw TRopException("TRop::max invalid raster combination");
    }
  }
}
ropmin()
void TRop::ropmin (const TRasterP & rup, const TRasterP & rdown, const TRasterP & rout, bool matte)
{
  TRaster32P up32   = rup;
  TRaster32P down32 = rdown;
  TRaster32P out32  = rout;
  if (up32 && down32 && out32) {
    if (matte) {
      FOR_EACH_PIXEL_32_BEGIN_LOOP
      outPix->r = upPix->r < downPix->r ? upPix->r : downPix->r;
      outPix->g = upPix->g < downPix->g ? upPix->g : downPix->g;
      outPix->b = upPix->b < downPix->b ? upPix->b : downPix->b;
      outPix->m = upPix->m < downPix->m ? upPix->m : downPix->m;
      FOR_EACH_PIXEL_32_END_LOOP
    } else {
      FOR_EACH_PIXEL_32_BEGIN_LOOP
      if (upPix->m >= 255) {
        outPix->r = upPix->r < downPix->r ? upPix->r : downPix->r;
        outPix->g = upPix->g < downPix->g ? upPix->g : downPix->g;
        outPix->b = upPix->b < downPix->b ? upPix->b : downPix->b;
        outPix->m = upPix->m < downPix->m ? upPix->m : downPix->m;
      } else if (upPix->m) {
        TPixel32 tmp;
        tmp.r = upPix->r < downPix->r ? upPix->r : downPix->r;
        tmp.g = upPix->g < downPix->g ? upPix->g : downPix->g;
        tmp.b = upPix->b < downPix->b ? upPix->b : downPix->b;
        // tmp.m = upPix->m < downPix->m ? upPix->m : downPix->m;
        outPix->r = upPix->m * (tmp.r - downPix->r) / 255.0 + downPix->r;
        outPix->g = upPix->m * (tmp.g - downPix->g) / 255.0 + downPix->g;
        outPix->b = upPix->m * (tmp.b - downPix->b) / 255.0 + downPix->b;
        outPix->m = upPix->m * (tmp.m - downPix->m) / 255.0 + downPix->m;
      } else
        *outPix = *downPix;
      FOR_EACH_PIXEL_32_END_LOOP
    }
  } else {
    TRaster64P up64   = rup;
    TRaster64P down64 = rdown;
    TRaster64P out64  = rout;
    if (up64 && down64 && out64) {
      if (matte) {
        FOR_EACH_PIXEL_64_BEGIN_LOOP
        outPix->r = upPix->r < downPix->r ? upPix->r : downPix->r;
        outPix->g = upPix->g < downPix->g ? upPix->g : downPix->g;
        outPix->b = upPix->b < downPix->b ? upPix->b : downPix->b;
        outPix->m = upPix->m < downPix->m ? upPix->m : downPix->m;
        FOR_EACH_PIXEL_64_END_LOOP
      } else {
        FOR_EACH_PIXEL_32_BEGIN_LOOP
        if (upPix->m >= 65535) {
          outPix->r = upPix->r < downPix->r ? upPix->r : downPix->r;
          outPix->g = upPix->g < downPix->g ? upPix->g : downPix->g;
          outPix->b = upPix->b < downPix->b ? upPix->b : downPix->b;
          outPix->m = upPix->m < downPix->m ? upPix->m : downPix->m;
        } else if (upPix->m) {
          TPixel32 tmp;
          tmp.r = upPix->r < downPix->r ? upPix->r : downPix->r;
          tmp.g = upPix->g < downPix->g ? upPix->g : downPix->g;
          tmp.b = upPix->b < downPix->b ? upPix->b : downPix->b;
          // tmp.m = upPix->m < downPix->m ? upPix->m : downPix->m;
          outPix->r = upPix->m * (tmp.r - downPix->r) / 65535.0 + downPix->r;
          outPix->g = upPix->m * (tmp.g - downPix->g) / 65535.0 + downPix->g;
          outPix->b = upPix->m * (tmp.b - downPix->b) / 65535.0 + downPix->b;
          outPix->m = upPix->m * (tmp.m - downPix->m) / 65535.0 + downPix->m;
        } else
          *outPix = *downPix;
        FOR_EACH_PIXEL_32_END_LOOP
      }
    } else {
      TRasterGR8P up8   = rup;
      TRasterGR8P down8 = rdown;
      TRasterGR8P out8  = rout;
      if (up8 && down8 && out8) {
        FOR_EACH_PIXEL_8_BEGIN_LOOP
        outPix->value =
            upPix->value < downPix->value ? upPix->value : downPix->value;
        FOR_EACH_PIXEL_8_END_LOOP
      } else
        throw TRopException("TRop::min invalid raster combination");
    }
  }
}
ropout()
void TRop::ropout (const TRasterP & source, const TRasterP & matte, const TRasterP & rout)
{
  TRaster32P source32 = source;
  TRaster32P matte32  = matte;
  TRaster32P out32    = rout;
  TRaster64P source64 = source;
  TRaster64P matte64  = matte;
  TRaster64P out64    = rout;
  if (source32 && matte32 && out32) {
    FOR_EACH_PIXEL_BEGIN_LOOP(TPixelRGBM32, source32, TPixelRGBM32, matte32,
                              TPixelRGBM32, out32)
    if (downPix->m == 255)
      outPix->r = outPix->g = outPix->b = outPix->m = 0;
    else if (downPix->m == 0)
      *outPix = *upPix;
    else {
      const int MAGICFAC = (257U * 256U + 1U);
      UINT fac           = MAGICFAC * (255 - downPix->m);
      outPix->r = (UINT)(upPix->r * fac + (1U << 23)) >> 24;
      outPix->g = (UINT)(upPix->g * fac + (1U << 23)) >> 24;
      outPix->b = (UINT)(upPix->b * fac + (1U << 23)) >> 24;
      outPix->m = (UINT)(upPix->m * fac + (1U << 23)) >> 24;
    }
    FOR_EACH_PIXEL_END_LOOP(source32, matte32, out32)
  } else if (source64 && matte64 && out64) {
    FOR_EACH_PIXEL_BEGIN_LOOP(TPixelRGBM64, source64, TPixelRGBM64, matte64,
                              TPixelRGBM64, out64)
    if (downPix->m == 65535)
      outPix->r = outPix->g = outPix->b = outPix->m = 0;
    else if (downPix->m == 0)
      *outPix = *upPix;
    else {
      double fac = (65535 - downPix->m) / 65535.0;
      outPix->r = (USHORT)(upPix->r * fac);
      outPix->g = (USHORT)(upPix->g * fac);
      outPix->b = (USHORT)(upPix->b * fac);
      outPix->m = (USHORT)(upPix->m * fac);
    }
    FOR_EACH_PIXEL_END_LOOP(source64, matte64, out64)
  } else
    throw TRopException("TRop::out invalid raster combination");
}
screen()
void TRop::screen (const TRasterP & rup, const TRasterP & rdown, const TRasterP & rout)
{
  TRaster32P up32   = rup;
  TRaster32P down32 = rdown;
  TRaster32P out32  = rout;
  if (up32 && down32 && out32) {
    FOR_EACH_PIXEL_32_BEGIN_LOOP
    double r, g, b;
    r = 256 - ((256 - upPix->r) * (256 - downPix->r) >> 8);
    g = 256 - ((256 - upPix->g) * (256 - downPix->g) >> 8);
    b = 256 - ((256 - upPix->b) * (256 - downPix->b) >> 8);
    if (upPix->m != 255) {
      double m;
      m = 256 - ((256 - upPix->m) * (256 - downPix->m) >> 8);
      TPixel32 tmpPix;
      tmpPix.r = (UCHAR)tcrop<double>(r, 0, 255);
      tmpPix.g = (UCHAR)tcrop<double>(g, 0, 255);
      tmpPix.b = (UCHAR)tcrop<double>(b, 0, 255);
      tmpPix.m = (UCHAR)tcrop<double>(m, 0, 255);
      overPix<TPixel32, UCHAR>(*outPix, *downPix, tmpPix);
    } else {
      outPix->r = (UCHAR)tcrop<double>(r, 0, 255);
      outPix->g = (UCHAR)tcrop<double>(g, 0, 255);
      outPix->b = (UCHAR)tcrop<double>(b, 0, 255);
      outPix->m = upPix->m;
    }
    FOR_EACH_PIXEL_32_END_LOOP
  } else {
    TRaster64P up64   = rup;
    TRaster64P down64 = rdown;
    TRaster64P out64  = rout;
    if (up64 && down64 && out64) {
      FOR_EACH_PIXEL_64_BEGIN_LOOP
      double r, g, b;
      r = 65536 - (65536 - upPix->r) * ((65536 - downPix->r) / 65536.0);
      g = 65536 - (65536 - upPix->g) * ((65536 - downPix->g) / 65536.0);
      b = 65536 - (65536 - upPix->b) * ((65536 - downPix->b) / 65536.0);
      if (upPix->m != 65535) {
        double m;
        m = 65536 - (65536 - upPix->m) * ((65536 - downPix->m) / 65536.0);
        TPixel64 tmpPix;
        tmpPix.r = (USHORT)tcrop<double>(r, 0, 65535);
        tmpPix.g = (USHORT)tcrop<double>(g, 0, 65535);
        tmpPix.b = (USHORT)tcrop<double>(b, 0, 65535);
        tmpPix.m = (USHORT)tcrop<double>(m, 0, 65535);
        overPix<TPixel64, USHORT>(*outPix, *downPix, tmpPix);
      } else {
        outPix->r = (USHORT)tcrop<double>(r, 0, 65535);
        outPix->g = (USHORT)tcrop<double>(g, 0, 65535);
        outPix->b = (USHORT)tcrop<double>(b, 0, 65535);
        outPix->m = upPix->m;
      }
      FOR_EACH_PIXEL_64_END_LOOP
    } else {
      TRasterGR8P up8   = rup;
      TRasterGR8P down8 = rdown;
      TRasterGR8P out8  = rout;
      if (up8 && down8 && out8) {
        FOR_EACH_PIXEL_8_BEGIN_LOOP
        USHORT value;
        if (downPix->value)
          value = (USHORT)((downPix->value << 8) / (255.0 - upPix->value));
        outPix->value = (UCHAR)tcrop<USHORT>(value, 0, 255);
        FOR_EACH_PIXEL_8_END_LOOP
      } else
        throw TRopException("TRop::color dodge invalid raster combination");
    }
  }
}
setChannel()
void TRop::setChannel (const TRasterP & rin, TRasterP rout, UCHAR chan, bool greytones)
{
  assert(rin->getSize() == rout->getSize());
  rout->lock();
  if ((TRaster32P)rin && (TRaster32P)rout)
    doSetChannel<TPixel32>(rin, rout, chan, greytones);
  else if ((TRaster64P)rin && (TRaster64P)rout)
    doSetChannel<TPixel64>(rin, rout, chan, greytones);
  else {
    rout->unlock();
    throw TRopException("setChannel: unsupported pixel type");
  }
  rout->unlock();
}
shrink()
TRasterP TRop::shrink (TRasterP rin, int shrink)
{
  int pixelSize = rin->getPixelSize();
  int lx = (rin->getLx() - 1) / shrink + 1;
  int ly = (rin->getLy() - 1) / shrink + 1;
  TRasterP rout;
  if ((TRaster32P)rin)
    rout = TRaster32P(lx, ly);
  else if ((TRaster64P)rin)
    rout                      = TRaster64P(lx, ly);
  if ((TRasterCM32P)rin) rout = TRasterCM32P(lx, ly);
  if ((TRasterGR8P)rin) rout  = TRasterGR8P(lx, ly);
  int i, j;
  for (i = 0; i < ly; i++) {
    UCHAR *bufin =
        (UCHAR *)rin->getRawData() + (i * shrink) * rin->getWrap() * pixelSize;
    UCHAR *bufout =
        (UCHAR *)rout->getRawData() + i * rout->getWrap() * pixelSize;
    for (j = 0; j < lx; j++) {
      memcpy(bufout, bufin, pixelSize);
      bufin += shrink * pixelSize;
      bufout += pixelSize;
    }
  }
  return rout;
}
sub()
void TRop::sub (const TRasterP & rup, const TRasterP & rdown, const TRasterP & rout, bool matte)
Subtract rdown pixels to rup pixels and put the resulting raster in rout
{
  TRaster32P up32   = rup;
  TRaster32P down32 = rdown;
  TRaster32P out32  = rout;
  if (matte) {
    if (up32 && down32 && out32) {
      FOR_EACH_PIXEL_32_BEGIN_LOOP
      SHORT r = downPix->r - upPix->r;
      SHORT g = downPix->g - upPix->g;
      SHORT b = downPix->b - upPix->b;
      SHORT m = downPix->m - upPix->m;
      outPix->r = (UCHAR)tcrop<SHORT>(r, 0, 255);
      outPix->g = (UCHAR)tcrop<SHORT>(g, 0, 255);
      outPix->b = (UCHAR)tcrop<SHORT>(b, 0, 255);
      outPix->m = (UCHAR)tcrop<SHORT>(m, 0, 255);
      FOR_EACH_PIXEL_32_END_LOOP
    } else {
      TRaster64P up64   = rup;
      TRaster64P down64 = rdown;
      TRaster64P out64  = rout;
      if (up64 && down64 && out64) {
        FOR_EACH_PIXEL_64_BEGIN_LOOP
        TINT32 r  = downPix->r - upPix->r;
        TINT32 g  = downPix->g - upPix->g;
        TINT32 b  = downPix->b - upPix->b;
        TINT32 m  = downPix->m - upPix->m;
        outPix->r = (USHORT)tcrop<TINT32>(r, 0, 0xffff);
        outPix->g = (USHORT)tcrop<TINT32>(g, 0, 0xffff);
        outPix->b = (USHORT)tcrop<TINT32>(b, 0, 0xffff);
        outPix->m = (USHORT)tcrop<TINT32>(m, 0, 0xffff);
        FOR_EACH_PIXEL_64_END_LOOP
      } else {
        TRasterGR8P up8   = rup;
        TRasterGR8P down8 = rdown;
        TRasterGR8P out8  = rout;
        if (up8 && down8 && out8) {
          FOR_EACH_PIXEL_8_BEGIN_LOOP
          SHORT value   = upPix->value - downPix->value;
          outPix->value = (UCHAR)tcrop<SHORT>(value, 0, 255);
          FOR_EACH_PIXEL_8_END_LOOP
        } else
          throw TRopException("TRop::sub invalid raster combination");
      }
    }
  } else {
    if (up32 && down32 && out32) {
      FOR_EACH_PIXEL_32_BEGIN_LOOP
      SHORT r = downPix->r - upPix->r;
      SHORT g = downPix->g - upPix->g;
      SHORT b = downPix->b - upPix->b;
      SHORT m = downPix->m;  // - upPix->m;
      outPix->r = (UCHAR)tcrop<SHORT>(r, 0, 255);
      outPix->g = (UCHAR)tcrop<SHORT>(g, 0, 255);
      outPix->b = (UCHAR)tcrop<SHORT>(b, 0, 255);
      outPix->m = (UCHAR)tcrop<SHORT>(m, 0, 255);
      FOR_EACH_PIXEL_32_END_LOOP
    } else {
      TRaster64P up64   = rup;
      TRaster64P down64 = rdown;
      TRaster64P out64  = rout;
      if (up64 && down64 && out64) {
        FOR_EACH_PIXEL_64_BEGIN_LOOP
        TINT32 r  = downPix->r - upPix->r;
        TINT32 g  = downPix->g - upPix->g;
        TINT32 b  = downPix->b - upPix->b;
        TINT32 m  = downPix->m;  // - upPix->m;
        outPix->r = (USHORT)tcrop<TINT32>(r, 0, 0xffff);
        outPix->g = (USHORT)tcrop<TINT32>(g, 0, 0xffff);
        outPix->b = (USHORT)tcrop<TINT32>(b, 0, 0xffff);
        outPix->m = (USHORT)tcrop<TINT32>(m, 0, 0xffff);
        FOR_EACH_PIXEL_64_END_LOOP
      } else {
        TRasterGR8P up8   = rup;
        TRasterGR8P down8 = rdown;
        TRasterGR8P out8  = rout;
        if (up8 && down8 && out8) {
          FOR_EACH_PIXEL_8_BEGIN_LOOP
          SHORT value   = upPix->value - downPix->value;
          outPix->value = (UCHAR)tcrop<SHORT>(value, 0, 255);
          FOR_EACH_PIXEL_8_END_LOOP
        } else
          throw TRopException("TRop::sub invalid raster combination");
      }
    }
  }
}
Referenced by SubFx::process().
txor()
void TRop::txor (const TRasterP & rup, const TRasterP & rdown, const TRasterP & rout)
{
  // da ottimizzare...
  TRaster32P up32   = rup;
  TRaster32P down32 = rdown;
  TRaster32P out32  = rout;
  TRaster64P up64   = rup;
  TRaster64P down64 = rdown;
  TRaster64P out64  = rout;
  if (up32 && down32 && out32) {
    FOR_EACH_PIXEL_32_BEGIN_LOOP
    TUINT32 notUpM   = 255 - upPix->m;
    TUINT32 notDownM = 255 - downPix->m;
    TUINT32 r = notUpM + upPix->r * (notDownM);
    TUINT32 g = notUpM + upPix->g * (notDownM);
    TUINT32 b = notUpM + upPix->b * (notDownM);
    outPix->r = (UCHAR)tcrop<TUINT32>(0, 255, r);
    outPix->g = (UCHAR)tcrop<TUINT32>(0, 255, g);
    outPix->b = (UCHAR)tcrop<TUINT32>(0, 255, b);
    FOR_EACH_PIXEL_32_END_LOOP
  } else if (up64 && down64 && out64) {
    FOR_EACH_PIXEL_64_BEGIN_LOOP
    TUINT32 notUpM   = 65535 - upPix->m;
    TUINT32 notDownM = 65535 - downPix->m;
    TUINT32 r = notUpM + upPix->r * (notDownM);
    TUINT32 g = notUpM + upPix->g * (notDownM);
    TUINT32 b = notUpM + upPix->b * (notDownM);
    outPix->r = (USHORT)tcrop<TUINT32>(0, 65535, r);
    outPix->g = (USHORT)tcrop<TUINT32>(0, 65535, g);
    outPix->b = (USHORT)tcrop<TUINT32>(0, 65535, b);
    FOR_EACH_PIXEL_64_END_LOOP
  } else
    throw TRopException("TRop::xor invalid raster combination");
}
unlockRaster()
void TRop::unlockRaster (_RASTER * raster)
Surrenders the input raster's buffer to the cache. Should be called before inactivity periods.
{
  TImageP img(TImageCache::instance()->get(
      std::string(raster->cacheId, raster->cacheIdLength), true));
  TRasterP cacheRas;
  if (raster->type == RAS_CM32)
    cacheRas = TToonzImageP(img)->getRaster();
  else
    cacheRas = TRasterImageP(img)->getRaster();
  cacheRas->release();
  raster->buffer        = 0;
  raster->native_buffer = 0;
}
Referenced by releaseRaster46().
whiteTransp()
void TRop::whiteTransp (const TRasterP & ras)
all white pixels are set to transparent
{
  ras->lock();
  TRaster32P ras32 = ras;
  if (ras32) {
    TPixel32 *endPix, *upPix = 0, *upRow = ras32->pixels();
    TPixel32 *lastPix =
        upRow + ras32->getWrap() * (ras32->getLy() - 1) + ras32->getLx();
    while (upPix < lastPix) {
      upPix  = upRow;
      endPix = upPix + ras32->getLx();
      while (upPix < endPix) {
        if (*upPix == TPixel::White) *upPix = TPixel::Transparent;
        ++upPix;
      }
      upRow += ras32->getWrap();
    }
  } else {
    TRaster64P ras64 = ras;
    if (ras64) {
      TPixel64 *endPix, *upPix = 0, *upRow = ras64->pixels();
      TPixel64 *lastPix =
          upRow + ras64->getWrap() * (ras64->getLy() - 1) + ras64->getLx();
      while (upPix < lastPix) {
        upPix  = upRow;
        endPix = upPix + ras64->getLx();
        while (upPix < endPix) {
          if (*upPix == TPixel64::White) *upPix = TPixel64::Transparent;
          ++upPix;
        }
        upRow += ras64->getWrap();
      }
    } else {
      ras->unlock();
      throw TException("TRop::premultiply invalid raster type");
    }
  }
  ras->unlock();
}
Referenced by quickPut().