opentoonz: PaletteCmd Namespace Reference
PaletteCmd Namespace Reference
Provides a collection of methods to manage TPalette.
Classes
struct ColorModelLoadingConfiguration
Enumerations
enum ColorModelPltBehavior { KeepColorModelPlt = 0 , ReplaceColorModelPlt , AddColorModelPlt }
enum ColorModelRasterPickType { PickEveryColors = 0 , IntegrateSimilarColors , PickColorChipGrid }
enum ColorChipOrder { UpperLeft = 0 , LowerLeft , LeftUpper }
Functions
DVAPI void arrangeStyles (TPaletteHandle *paletteHandle, int dstPageIndex, int dstIndexInPage, int srcPageIndex, const std::set< int > &srcIndicesInPage)
DVAPI void createStyle (TPaletteHandle *paletteHandle, TPalette::Page *page)
DVAPI void addStyles (TPaletteHandle *paletteHandle, int pageIndex, int indexInPage, const std::vector< TColorStyle * > &styles)
DVAPI void eraseStyles (const std::set< TXshSimpleLevel * > &levels, const std::vector< int > &styleIds)
Erases image entities whose style is any of the specified ones.
DVAPI void addPage (TPaletteHandle *paletteHandle, std::wstring name=L"", bool withUndo=true)
DVAPI void destroyPage (TPaletteHandle *paletteHandle, int pageIndex)
DVAPI int loadReferenceImage (TPaletteHandle *paletteHandle, const ColorModelLoadingConfiguration &config, const TFilePath &_fp, ToonzScene *scene, const std::vector< int > &frames=std::vector< int >())
DVAPI void removeReferenceImage (TPaletteHandle *paletteHandle)
DVAPI void movePalettePage (TPaletteHandle *paletteHandle, int srcIndex, int dstIndex)
DVAPI void renamePalettePage (TPaletteHandle *paletteHandle, int pageIndex, const std::wstring &newName)
DVAPI void renamePaletteStyle (TPaletteHandle *paletteHandle, const std::wstring &newName)
DVAPI void organizePaletteStyle (TPaletteHandle *paletteHandle, int styleId, const TColorStyle::PickedPosition &point)
DVAPI void pickColorByUsingPickedPosition (TPaletteHandle *paletteHandle, TImageP img, int frame)
Detailed Description
Provides a collection of methods to manage TPalette.
Enumeration Type Documentation
ColorChipOrder
enum PaletteCmd::ColorChipOrder
{ UpperLeft = 0, LowerLeft, LeftUpper };
ColorModelPltBehavior
enum PaletteCmd::ColorModelPltBehavior
{
  KeepColorModelPlt = 0,
  ReplaceColorModelPlt,
  AddColorModelPlt
};
ColorModelRasterPickType
enum PaletteCmd::ColorModelRasterPickType
{
  PickEveryColors = 0,
  IntegrateSimilarColors,
  PickColorChipGrid
};
Function Documentation
addPage()
void PaletteCmd::addPage (TPaletteHandle * paletteHandle, std::wstring name = L"", bool withUndo = true)
{
  TPalette *palette = paletteHandle->getPalette();
  if (name == L"")
    name = L"page " + std::to_wstring(palette->getPageCount() + 1);
  TPalette::Page *page = palette->addPage(name);
  palette->setDirtyFlag(true);
  paletteHandle->notifyPaletteChanged();
  if (withUndo)
    TUndoManager::manager()->add(
        new AddPageUndo(paletteHandle, page->getIndex(), name));
}
addStyles()
void PaletteCmd::addStyles (TPaletteHandle * paletteHandle, int pageIndex, int indexInPage, const std::vector< TColorStyle * > & styles)
{
  TPalette *palette = paletteHandle->getPalette();
  assert(0 <= pageIndex && pageIndex < palette->getPageCount());
  TPalette::Page *page = palette->getPage(pageIndex);
  assert(page);
  assert(0 <= indexInPage && indexInPage <= page->getStyleCount());
  int count = styles.size();
  for (int i = 0; i < count; i++) {
    page->insertStyle(indexInPage + i, styles[i]->clone());
    /*-- StudioPaletteから持ち込んだ場合、その元の名前をoriginalNameに入れる
     * --*/
    if (styles[i]->getGlobalName() != L"") {
      /*--
       * もし元のStyleにOriginalNameが無ければ（コピー元がStudioPaletteからということ）--*/
      if (styles[i]->getOriginalName() == L"") {
        /*-- 元のStyleの名前をペースト先のOriginalNameに入れる --*/
        page->getStyle(indexInPage + i)->setOriginalName(styles[i]->getName());
      }
    }
    /*--
     * それ以外の場合は、clone()でそれぞれの名前をコピーしているので、そのままでOK
     * --*/
  }
  TUndoManager::manager()->add(
      new AddStylesUndo(palette, pageIndex, indexInPage, count, paletteHandle));
  palette->setDirtyFlag(true);
}
arrangeStyles()
void PaletteCmd::arrangeStyles (TPaletteHandle * paletteHandle, int dstPageIndex, int dstIndexInPage, int srcPageIndex, const std::set< int > & srcIndicesInPage)
{
  if (dstPageIndex == srcPageIndex &&
      dstIndexInPage == *srcIndicesInPage.begin())
    return;
  ArrangeStylesUndo *undo =
      new ArrangeStylesUndo(paletteHandle, dstPageIndex, dstIndexInPage,
                            srcPageIndex, srcIndicesInPage);
  undo->redo();
  TUndoManager::manager()->add(undo);
}
createStyle()
void PaletteCmd::createStyle (TPaletteHandle * paletteHandle, TPalette::Page * page)
{
  int index         = paletteHandle->getStyleIndex();
  TPalette *palette = paletteHandle->getPalette();
  int newIndex;
  int UnpagedId = palette->getFirstUnpagedStyle();
  if (UnpagedId != -1 && !palette->isCleanupPalette()) {
    if (index == -1)
      palette->getStyle(UnpagedId)->setMainColor(TPixel32::Black);
    else
      palette->getStyle(UnpagedId)->setMainColor(
          palette->getStyle(index)->getMainColor());
    newIndex = page->addStyle(UnpagedId);
  } else if (!palette->isCleanupPalette()) {
    if (index == -1)
      newIndex = page->addStyle(TPixel32::Black);
    else {
      TColorStyle *style          = palette->getStyle(index);
      TCleanupStyle *cleanupStyle = dynamic_cast<TCleanupStyle *>(style);
      if ((cleanupStyle || index == 0) && palette->isCleanupPalette()) {
        TColorCleanupStyle *newCleanupStyle = new TColorCleanupStyle();
        if (cleanupStyle) {
          int i;
          for (i = 0; i < cleanupStyle->getParamCount(); i++)
            newCleanupStyle->setColorParamValue(
                i, cleanupStyle->getColorParamValue(i));
        }
        newIndex = page->addStyle(newCleanupStyle);
      } else
        newIndex = page->addStyle(style->getMainColor());
    }
  } else /*- CleanupPaletteの場合 -*/
  {
    newIndex = page->addStyle(new TColorCleanupStyle(TPixel32::Red));
  }
  int newStyleId = page->getStyleId(newIndex);
  /*-  StudioPalette上でStyleを追加した場合、GlobalNameを自動で割り振る -*/
  if (palette->getGlobalName() != L"") {
    TColorStyle *cs = palette->getStyle(newStyleId);
    std::wstring gname =
        L"-" + palette->getGlobalName() + L"-" + std::to_wstring(newStyleId);
    cs->setGlobalName(gname);
  }
  page->getStyle(newIndex)->setName(
      QString("color_%1").arg(newStyleId).toStdWString());
  paletteHandle->setStyleIndex(newStyleId);
  palette->setDirtyFlag(true);
  paletteHandle->notifyPaletteChanged();
  TUndoManager::manager()->add(new CreateStyleUndo(
      paletteHandle, page->getIndex(), page->getStyleId(newIndex)));
}
destroyPage()
void PaletteCmd::destroyPage (TPaletteHandle * paletteHandle, int pageIndex)
{
  TPalette *palette = paletteHandle->getPalette();
  assert(0 <= pageIndex && pageIndex < palette->getPageCount());
  TUndoManager::manager()->add(new DestroyPageUndo(paletteHandle, pageIndex));
  palette->erasePage(pageIndex);
  palette->setDirtyFlag(true);
  paletteHandle->notifyPaletteChanged();
}
eraseStyles()
void PaletteCmd::eraseStyles (const std::set< TXshSimpleLevel * > & levels, const std::vector< int > & styleIds)
Erases image entities whose style is any of the specified ones.
This function applies to all objects contained in the images of a level; for example, all strokes and regions of the TVectorImages in a level.
Remarks
This command does not provide an undo for level types whose images are raster-based (specifically, fullcolor and TLV images), due to memory occupation concerns.
{
  typedef std::pair<const TXshSimpleLevelP, std::vector<TVectorImageP>>
      LevelImages;
  struct Undo final : public TUndo {
    std::set<TXshSimpleLevel *> m_levels;
    std::vector<int> m_styleIds;
    mutable std::map<TXshSimpleLevelP, std::vector<TVectorImageP>>
        m_imagesByLevel;
  public:
    Undo(const std::set<TXshSimpleLevel *> &levels,
         const std::vector<int> &styleIds)
        : m_levels(levels), m_styleIds(styleIds) {
      tcg::substitute(m_imagesByLevel,
                      levels | boost::adaptors::filtered(isVector) |
                          boost::adaptors::transformed(toEmptyLevelImages));
    }
    bool isValid() const { return !m_levels.empty(); }
    void redo() const override {
      std::for_each(m_imagesByLevel.begin(), m_imagesByLevel.end(),
                    cloneImages);
      eraseStylesInLevels(m_levels, m_styleIds);
    }
    void undo() const override {
      std::for_each(m_imagesByLevel.begin(), m_imagesByLevel.end(),
                    restoreImages);
    }
    int getSize() const override { return 10 << 20; }  // At max 10 per 100 MB
  private:
    static bool isVector(const TXshSimpleLevel *level) {
      return (assert(level), level->getType() == PLI_XSHLEVEL);
    }
    static LevelImages toEmptyLevelImages(TXshSimpleLevel *level) {
      return LevelImages(level, std::vector<TVectorImageP>());
    }
    static void copyStrokeIds(const TVectorImage &src, TVectorImage &dst) {
      UINT s, sCount = src.getStrokeCount();
      for (s = 0; s != sCount; ++s)
        dst.getStroke(s)->setId(src.getStroke(s)->getId());
    }
    static TVectorImageP cloneImage(const TXshSimpleLevel &level, int f) {
      TVectorImageP src = static_cast<TVectorImageP>(
          level.getFrame(level.getFrameId(f), false));
      TVectorImageP dst = src->clone();
      copyStrokeIds(*src, *dst);
      return dst;
    }
    static void cloneImages(LevelImages &levelImages) {
      tcg::substitute(
          levelImages.second,
          boost::counting_range(0, levelImages.first->getFrameCount()) |
              boost::adaptors::transformed(boost::bind(
                  cloneImage, boost::cref(*levelImages.first), _1)));
    }
    static void restoreImage(const TXshSimpleLevelP &level, int f,
                             const TVectorImageP &vi) {
      level->setFrame(level->getFrameId(f), vi.getPointer());
    }
    static void restoreImages(LevelImages &levelImages) {
      int f, fCount = std::min(levelImages.first->getFrameCount(),
                               int(levelImages.second.size()));
      for (f = 0; f != fCount; ++f)
        restoreImage(levelImages.first, f, levelImages.second[f]);
    }
  };  // Undo
  if (levels.empty() || styleIds.empty()) return;
  std::unique_ptr<TUndo> undo(new Undo(levels, styleIds));
  if (static_cast<Undo &>(*undo).isValid()) {
    undo->redo();
    TUndoManager::manager()->add(undo.release());
  }
}
References TXshSimpleLevel::getFrameId(), TVectorImage::getStroke(), TVectorImage::getStrokeCount(), and TXshLevel::getType().
loadReferenceImage()
int PaletteCmd::loadReferenceImage (TPaletteHandle * paletteHandle, const ColorModelLoadingConfiguration & config, const TFilePath & _fp, ToonzScene * scene, const std::vector< int > & frames = std::vector<int>())
{
  TPaletteP levelPalette = paletteHandle->getPalette();
  if (!levelPalette) return 2;
  int ret =
      loadRefImage(paletteHandle, config, levelPalette, _fp, scene, frames);
  if (ret != 0) return ret;
  // when choosing replace(Keep the destination palette), dirty flag is
  // unchanged
  if (config.behavior != ReplaceColorModelPlt) {
    levelPalette->setDirtyFlag(true);
    paletteHandle->notifyPaletteDirtyFlagChanged();
  }
  return 0;
}
movePalettePage()
void PaletteCmd::movePalettePage (TPaletteHandle * paletteHandle, int srcIndex, int dstIndex)
{
  TPaletteP palette = paletteHandle->getPalette();
  palette->movePage(palette->getPage(srcIndex), dstIndex);
  TUndoManager::manager()->add(
      new MovePageUndo(paletteHandle, srcIndex, dstIndex));
  paletteHandle->notifyPaletteChanged();
}
organizePaletteStyle()
void PaletteCmd::organizePaletteStyle (TPaletteHandle * paletteHandle, int styleId, const TColorStyle::PickedPosition & point)
{
  if (!paletteHandle) return;
  TPalette *palette = paletteHandle->getPalette();
  if (!palette) return;
  // if the style is already in the first page, then do nothing
  TPalette::Page *page = palette->getStylePage(styleId);
  if (!page || page->getIndex() == 0) return;
  int indexInPage = page->search(styleId);
  TUndoManager::manager()->beginBlock();
  // call arrangeStyles() to move style to the first page
  arrangeStyles(paletteHandle, 0, palette->getPage(0)->getStyleCount(),
                page->getIndex(), {indexInPage});
  // then set the picked position
  setStylePickedPositionUndo *undo =
      new setStylePickedPositionUndo(paletteHandle, styleId, point);
  undo->redo();
  TUndoManager::manager()->add(undo);
  TUndoManager::manager()->endBlock();
}
pickColorByUsingPickedPosition()
void PaletteCmd::pickColorByUsingPickedPosition (TPaletteHandle * paletteHandle, TImageP img, int frame)
{
  TRasterImageP ri = img;
  if (!ri) return;
  TPalette *currentPalette = paletteHandle->getPalette();
  if (!currentPalette) return;
  TDimension imgSize = ri->getRaster()->getSize();
  QHash<int, QPair<TPixel32, TPixel32>> styleList;
  // For all styles (starting from #1 as #0 is reserved for the transparent)
  for (int sId = 1; sId < currentPalette->getStyleCount(); sId++) {
    TColorStyle *style = currentPalette->getStyle(sId);
    TPoint pp          = style->getPickedPosition().pos;
    int pickedFrame    = style->getPickedPosition().frame;
    // If style has a valid picked position
    if (pp != TPoint() && frame == pickedFrame && pp.x >= 0 &&
        pp.x < imgSize.lx && pp.y >= 0 && pp.y < imgSize.ly &&
        style->hasMainColor()) {
      TPixel32 beforeColor = style->getMainColor();
      TPixel32 afterColor  = pickColor(ri, pp);
      style->setMainColor(afterColor);
      //... store the style in the list for undo
      styleList.insert(sId, QPair<TPixel32, TPixel32>(beforeColor, afterColor));
    }
  }
  // if some style has been changed, then register undo and notify changes
  if (!styleList.isEmpty()) {
    pickColorByUsingPickedPositionUndo *undo =
        new pickColorByUsingPickedPositionUndo(paletteHandle, styleList);
    TUndoManager::manager()->add(undo);
    paletteHandle->notifyColorStyleChanged(false, true);  // set dirty flag here
  }
}
removeReferenceImage()
void PaletteCmd::removeReferenceImage (TPaletteHandle * paletteHandle)
{
  TPaletteP levelPalette = paletteHandle->getPalette();
  if (!levelPalette) return;
  TUndo *undo = new SetReferenceImageUndo(levelPalette, paletteHandle);
  levelPalette->setRefImg(TImageP());
  levelPalette->setRefImgPath(TFilePath());
  std::vector<TFrameId> fids;
  levelPalette->setRefLevelFids(fids, false);
  levelPalette->setDirtyFlag(true);
  paletteHandle->notifyPaletteChanged();
  TUndoManager::manager()->add(undo);
}
renamePalettePage()
void PaletteCmd::renamePalettePage (TPaletteHandle * paletteHandle, int pageIndex, const std::wstring & newName)
{
  if (!paletteHandle) return;
  TPalette *palette = paletteHandle->getPalette();
  if (!palette) return;
  if (pageIndex < 0 || pageIndex >= palette->getPageCount()) return;
  RenamePageUndo *undo = new RenamePageUndo(paletteHandle, pageIndex, newName);
  paletteHandle->notifyPaletteChanged();
  TPalette::Page *page = palette->getPage(pageIndex);
  assert(page);
  page->setName(newName);
  palette->setDirtyFlag(true);
  paletteHandle->notifyPaletteChanged();
  TUndoManager::manager()->add(undo);
}
renamePaletteStyle()
void PaletteCmd::renamePaletteStyle (TPaletteHandle * paletteHandle, const std::wstring & newName)
{
  if (!paletteHandle) return;
  TPalette *palette = paletteHandle->getPalette();
  if (!palette) return;
  TColorStyle *style = paletteHandle->getStyle();
  if (!style) return;
  if (style->getName() == newName) return;
  RenamePaletteStyleUndo *undo =
      new RenamePaletteStyleUndo(paletteHandle, newName);
  style->setName(newName);
  palette->setDirtyFlag(true);
  paletteHandle->notifyColorStyleChanged(false);
  TUndoManager::manager()->add(undo);
}