opentoonz: Stage Namespace Reference
Stage Namespace Reference
The Stage namespace provides a set of objects, class and method, useful to view images in display.
Classes
class OpenGlPainter
The derived Stage::Visitor responsible for camera-stand rendering in 3D mode.
class Picker
class Player
class RasterPainter
struct VisitArgs
class Visitor
Functions
DVAPI void visit (Visitor &visitor, const VisitArgs &args)
DVAPI void visit (Visitor &visitor, ToonzScene *scene, TXsheet *xsh, int row)
DVAPI void visit (Visitor &visitor, TXshSimpleLevel *level, const TFrameId &fid, const OnionSkinMask &osm, bool isPlaying, int isGuidedDrawingEnabled=0, int guidedBackStroke=-1, int guidedFrontStroke=-1)
DVAPI void visit (Visitor &visitor, TXshLevel *level, const TFrameId &fid, const OnionSkinMask &osm, bool isPlaying, double isGuidedDrawingEnabled=0.0, int guidedBackStroke=-1, int guidedFrontStroke=-1)
DVAPI void visit (Visitor &visitor, TXshSimpleLevel *level, const TFrameId &fid, const OnionSkinMask &osm, bool isPlaying)
DVAPI void visit (Visitor &visitor, TXshLevel *level, const TFrameId &fid, const OnionSkinMask &osm, bool isPlaying)
Variables
DVVAR const double inch = 53.33333
DVVAR const double standardDpi = 120
DVVAR const double bigBoxSize [] = {500, 500, 1000}
Detailed Description
The Stage namespace provides a set of objects, class and method, useful to view images in display.
The Stage namespace provides objects, classes and methods useful to view or display images.
Function Documentation
visit() [1/4]
void Stage::visit (Visitor & visitor, const VisitArgs & args)
Declare a StageBuilder object and recall StageBuilder::addFrame() and StageBuilder::visit().
{
  ToonzScene *scene        = args.m_scene;
  TXsheet *xsh             = args.m_xsh;
  int row                  = args.m_row;
  int col                  = args.m_col;
  const OnionSkinMask *osm = args.m_osm;
  bool camera3d            = args.m_camera3d;
  int xsheetLevel          = args.m_xsheetLevel;
  bool isPlaying           = args.m_isPlaying;
  StageBuilder sb;
  sb.m_vs                     = &visitor.m_vs;
  TStageObjectId cameraId     = xsh->getStageObjectTree()->getCurrentCameraId();
  TStageObject *camera        = xsh->getStageObject(cameraId);
  TAffine cameraAff           = camera->getPlacement(row);
  double z                    = camera->getZ(row);
  sb.m_cameraPlacement        = ZPlacement(cameraAff, z);
  sb.m_camera3d               = camera3d;
  sb.m_currentColumnIndex     = col;
  sb.m_xsheetLevel            = xsheetLevel;
  sb.m_onionSkinMask          = *osm;
  sb.m_currentFrameId         = args.m_currentFrameId;
  sb.m_isGuidedDrawingEnabled = args.m_isGuidedDrawingEnabled;
  sb.m_guidedFrontStroke      = args.m_guidedFrontStroke;
  sb.m_guidedBackStroke       = args.m_guidedBackStroke;
#if defined(x64)
  if (args.m_liveViewImage) {
    sb.m_liveViewImage  = args.m_liveViewImage;
    sb.m_liveViewPlayer = args.m_liveViewPlayer;
  }
  if (args.m_lineupImage) {
    sb.m_lineupImage  = args.m_lineupImage;
    sb.m_lineupPlayer = args.m_lineupPlayer;
  }
#endif
  Player::m_onionSkinFrontSize     = 0;
  Player::m_onionSkinBackSize      = 0;
  Player::m_firstFrontOnionSkin    = 0;
  Player::m_firstBackOnionSkin     = 0;
  Player::m_lastBackVisibleSkin    = 0;
  Player::m_isShiftAndTraceEnabled = osm->isShiftTraceEnabled();
  sb.addFrame(sb.m_players, scene, xsh, row, 0, args.m_onlyVisible,
              args.m_checkPreviewVisibility);
  updateOnionSkinSize(sb.m_players);
  sb.visit(sb.m_players, visitor, isPlaying);
}
References StageBuilder::addFrame(), TStageObjectTree::getCurrentCameraId(), TXsheet::getStageObject(), TXsheet::getStageObjectTree(), TStageObject::getZ(), Stage::Visitor::m_vs, and StageBuilder::visit().
Referenced by SceneViewer::posToRow(), and ToonzScene::renderFrame().
visit() [2/4]
void Stage::visit (Visitor & visitor, ToonzScene * scene, TXsheet * xsh, int row)
{
  Stage::VisitArgs args;
  args.m_scene = scene;
  args.m_xsh   = xsh;
  args.m_row   = row;
  args.m_col   = -1;
  OnionSkinMask osm;
  args.m_osm = &osm;
  visit(visitor, args);  // scene, xsh, row, -1, OnionSkinMask(), false, 0);
}
visit() [3/4]
void Stage::visit (Visitor & visitor, TXshLevel * level, const TFrameId & fid, const OnionSkinMask & osm, bool isPlaying, double isGuidedDrawingEnabled = 0.0, int guidedBackStroke = -1, int guidedFrontStroke = -1)
{
  if (level && level->getSimpleLevel())
    visit(visitor, level->getSimpleLevel(), fid, osm, isPlaying,
          (int)isGuidedDrawingEnabled, guidedBackStroke, guidedFrontStroke);
}
visit() [4/4]
void Stage::visit (Visitor & visitor, TXshSimpleLevel * level, const TFrameId & fid, const OnionSkinMask & osm, bool isPlaying, int isGuidedDrawingEnabled = 0, int guidedBackStroke = -1, int guidedFrontStroke = -1)
Declare a StageBuilder object and recall StageBuilder::addSimpleLevelFrame() and StageBuilder::visit().
{
  StageBuilder sb;
  sb.m_vs                          = &visitor.m_vs;
  sb.m_onionSkinMask               = osm;
  sb.m_currentFrameId              = fid;
  sb.m_isGuidedDrawingEnabled      = isGuidedDrawingEnabled;
  sb.m_guidedFrontStroke           = guidedFrontStroke;
  sb.m_guidedBackStroke            = guidedBackStroke;
  Player::m_onionSkinFrontSize     = 0;
  Player::m_onionSkinBackSize      = 0;
  Player::m_firstFrontOnionSkin    = 0;
  Player::m_firstBackOnionSkin     = 0;
  Player::m_lastBackVisibleSkin    = 0;
  Player::m_isShiftAndTraceEnabled = osm.isShiftTraceEnabled();
  sb.addSimpleLevelFrame(sb.m_players, level, fid);
  updateOnionSkinSize(sb.m_players);
  sb.visit(sb.m_players, visitor, isPlaying);
}
References StageBuilder::addSimpleLevelFrame(), Stage::Visitor::m_vs, and StageBuilder::visit().
Variable Documentation
bigBoxSize
const double Stage::bigBoxSize = {500, 500, 1000}
inch
Stage::inch = 53.33333 extern
For historical reasons camera stand is defined in a coordinate system in which an inch is equal to 'Stage::inch' unit. Pay attention: modify this value condition apparent line thickness of images .pli.
Referenced by Skeleton::build(), PlasticDeformerFx::doDryCompute(), EditTool::draw(), CameraTestTool::draw(), SetScanCropboxTool::draw(), TXshSimpleLevel::getBBox(), TXsheet::getBBox(), TCamera::getCameraToStageRef(), SceneViewer::getDpiFactor(), TCamera::getStageRect(), TCamera::getStageToCameraRef(), ToonzScene::renderFrame(), and VectorizationSwatchTask::run().
standardDpi
const double Stage::standardDpi = 120 extern