opentoonz: tcg::point_ops Namespace Reference
tcg::point_ops Namespace Reference
Functions
template<typename Point >
Point NaP ()
template<typename Point >
Point operator+ (const Point &a, const Point &b)
template<typename Point >
Point operator- (const Point &a, const Point &b)
template<typename Point , typename Scalar >
Point operator* (Scalar a, const Point &b)
template<typename Point , typename Scalar >
Point operator/ (const Point &a, Scalar b)
template<typename Point >
point_traits< Point >::value_type operator* (const Point &a, const Point &b)
template<typename Point >
point_traits< Point >::value_type cross (const Point &a, const Point &b)
template<typename Point >
point_traits< Point >::value_type norm2 (const Point &a)
template<typename Point >
point_traits< Point >::float_type norm (const Point &a)
template<typename Point >
point_traits< Point >::value_type dist2 (const Point &a, const Point &b)
template<typename Point >
point_traits< Point >::value_type dist (const Point &a, const Point &b)
template<typename Point >
point_traits< Point >::value_type absDist (const Point &a, const Point &b)
template<typename Point >
Point normalized (const Point &v)
template<typename Point >
Point normalized (const Point &v, typename point_traits< Point >::value_type tol)
template<typename Point >
void normalize (Point &v)
template<typename Point >
bool normalize (Point &v, typename point_traits< Point >::value_type tol)
template<typename Point >
Point direction (const Point &a, const Point &b)
template<typename Point >
Point direction (const Point &a, const Point &b, typename point_traits< Point >::value_type tol)
template<typename Point >
Point ortLeft (const Point &p)
Returns the left orthogonal of passed point.
template<typename Point >
Point ortRight (const Point &p)
Returns the right orthogonal of passed point.
template<typename Point >
Point bisecant (const Point &d0, const Point &d1)
template<typename Point >
Point projection (const Point &p, const Point &a, const Point &d)
Returns the projection of point p on line a -> d
template<typename Point >
Point ortCoords (const Point &p, const Point &p0, const Point &p1)
Returns res: p = p0 + res.x * (p1 - p0) + res.y * (p1 - p0)_orth
template<typename Point >
Point triCoords (const Point &p, const Point &p0, const Point &p1, const Point &p2)
Returns res: p = p0 + res.x * (p1 - p0) + res.y * (p2 - p0)
template<typename Point >
point_traits< Point >::value_type lineSignedDist (const Point &p, const Point &a, const Point &d)
template<typename Point >
point_traits< Point >::value_type lineDist (const Point &p, const Point &a, const Point &d)
Returns the distance of point p from line a->d
template<typename Point >
int lineSide (const Point &p, const Point &a, const Point &d, typename point_traits< Point >::value_type tol=0)
Returns the side of line a->d where point p lies, where 1 means left, -1 right, and 0 below tolerance (ie on the line).
template<typename Point >
point_traits< Point >::value_type segDist (const Point &a, const Point &b, const Point &p)
template<typename Point >
point_traits< Point >::value_type rad (const Point &p)
template<typename Point >
point_traits< Point >::value_type angle (const Point &v1, const Point &v2)
template<typename Point >
point_traits< Point >::value_type segCoord (const Point &p, const Point &p0, const Point &p1)
template<typename Point >
bool intersectionCoords (const Point &a, const Point &v, const Point &c, const Point &w, typename point_traits< Point >::value_type &s, typename point_traits< Point >::value_type &t, typename point_traits< Point >::value_type detTol=0)
template<typename Point >
bool intersectionSegCoords (const Point &a, const Point &b, const Point &c, const Point &d, typename point_traits< Point >::value_type &s, typename point_traits< Point >::value_type &t, typename point_traits< Point >::value_type detTol=0)
template<typename Point >
bool affineMap (const Point &p0, const Point &p1, const Point &p2, const Point &q0, const Point &q1, const Point &q2, typename point_traits< Point >::value_type affValues[], typename point_traits< Point >::value_type detTol=0)
Stores the 6 values of the bidimensional affine transform mapping p0, p1, p2 into q0, q1, q1.
template<typename Point >
bool bestFit (const Point &p, Point &v, typename point_traits< Point >::value_type sums_x, typename point_traits< Point >::value_type sums_y, typename point_traits< Point >::value_type sums2_x, typename point_traits< Point >::value_type sums2_y, typename point_traits< Point >::value_type sums_xy, typename point_traits< Point >::value_type n)
Calculates the best fit line passing through p whose n samples have the specified coordinate sums.
template<typename Point >
bool bestFit (Point &p, Point &v, typename point_traits< Point >::value_type sums_x, typename point_traits< Point >::value_type sums_y, typename point_traits< Point >::value_type sums2_x, typename point_traits< Point >::value_type sums2_y, typename point_traits< Point >::value_type sums_xy, typename point_traits< Point >::value_type n)
template<typename Point_ref , typename Point , typename point_iterator >
bool bestFit (Point_ref p, Point &d, point_iterator begin, point_iterator end)
Detailed Description
Contains useful functions to deal with planar objects (two dimensions) up to points and lines.
Function Documentation
absDist()
template<typename Point > point_traits< Point >::value_type tcg::point_ops::absDist (const Point & a, const Point & b) inline
{
  typename point_traits<Point>::value_type xDist = std::abs(b.x - a.x),
                                           yDist = std::abs(b.y - a.y);
  return (xDist < yDist) ? yDist : xDist;
}
affineMap()
template<typename Point > bool tcg::point_ops::affineMap (const Point & p0, const Point & p1, const Point & p2, const Point & q0, const Point & q1, const Point & q2, typename point_traits< Point >::value_type affValues[], typename point_traits< Point >::value_type detTol = 0)
Stores the 6 values of the bidimensional affine transform mapping p0, p1, p2 into q0, q1, q1.
Returned values are in row-major order, with the translational component at multiple of 3 indexes.
Returns numeric_ops::NaN() on each entry if the system could not be solved under the specified determinant threshold.
Returns
Whether the affine could be solved under the specified constraints
{
  typedef typename point_traits<Point>::value_type value_type;
  // Build the linear transform mapping (p1-p0) and (p2-p0) into (q1-q0) and
  // (q2-q0)
  value_type p1_p0_x = p1.x - p0.x, p1_p0_y = p1.y - p0.y;
  value_type p2_p0_x = p2.x - p0.x, p2_p0_y = p2.y - p0.y;
  value_type det = p1_p0_x * p2_p0_y - p1_p0_y * p2_p0_x;
  if (std::abs(det) < detTol) {
    affValues[0] = affValues[1] = affValues[2] = affValues[3] = affValues[4] =
        affValues[5] = numeric_ops::NaN<value_type>();
    return false;
  }
  value_type q1_q0_x = q1.x - q0.x, q1_q0_y = q1.y - q0.y;
  value_type q2_q0_x = q2.x - q0.x, q2_q0_y = q2.y - q0.y;
  affValues[2] = p2_p0_y / det;
  affValues[5] = -p2_p0_x / det;  // 2 and 5 used as temps here
  affValues[3] = -p1_p0_y / det;
  affValues[4] = p1_p0_x / det;
  affValues[0] = q1_q0_x * affValues[2] + q2_q0_x * affValues[3];
  affValues[1] = q1_q0_x * affValues[5] + q2_q0_x * affValues[4];
  affValues[3] = q1_q0_y * affValues[2] + q2_q0_y * affValues[3];
  affValues[4] = q1_q0_y * affValues[5] + q2_q0_y * affValues[4];
  // Finally, add the translational component
  affValues[2] = q0.x - affValues[0] * p0.x - affValues[1] * p0.y;
  affValues[5] = q0.y - affValues[3] * p0.x - affValues[4] * p0.y;
  return true;
}
angle()
template<typename Point > point_traits< Point >::value_type tcg::point_ops::angle (const Point & v1, const Point & v2) inline
Computes the angle, in radians, between unnormalized directions v1 and v2.
Returns
The angle between the specified directions, in the range [-consts::pi, consts::pi].
{
  return numeric_ops::mod<typename point_traits<Point>::value_type>(
      rad(v2) - rad(v1), -M_PI, M_PI);
}
Referenced by PlasticSkeletonDeformation::Imp::updateBranchPositions().
bestFit() [1/3]
template<typename Point > bool tcg::point_ops::bestFit (const Point & p, Point & v, typename point_traits< Point >::value_type sums_x, typename point_traits< Point >::value_type sums_y, typename point_traits< Point >::value_type sums2_x, typename point_traits< Point >::value_type sums2_y, typename point_traits< Point >::value_type sums_xy, typename point_traits< Point >::value_type n)
Calculates the best fit line passing through p whose n samples have the specified coordinate sums.
Note
Returned unnormalized direction v may be NaP() in case no preferential direction could be chosen
{
  typedef typename point_traits<Point>::value_type value_type;
  sums_x /= n;
  sums_y /= n;
  sums2_x /= n;
  sums2_y /= n;
  sums_xy /= n;
  value_type a = sums2_x - 2.0 * p.x * sums_x + sq(p.x);  // Always >= 0
  value_type b = sums_xy - p.x * sums_y - p.y * sums_x + p.x * p.y;
  value_type c = sums2_y - 2.0 * p.y * sums_y + sq(p.y);  // Always >= 0
  // The best-fit direction is an eigenvector of matrix [a, b; b, c]'s highest
  // eigenvalue.
  double trace = 0.5 * (a + c);
  double det   = a * c - b * b;
  double traceSq = trace * trace;
  if (traceSq < det) {
    v = NaP<Point>();
    return false;
  }
  double eigen = trace + sqrt(traceSq - det);  // plus takes the greater eigen
  a -= eigen, c -= eigen;
  // Take the most 'normed' obvious eigenvector
  if (std::abs(a) > std::abs(c))
    v.x = b, v.y = -a;
  else
    v.x = -c, v.y = b;
  return true;
}
Referenced by bestFit().
bestFit() [2/3]
template<typename Point > bool tcg::point_ops::bestFit (Point & p, Point & v, typename point_traits< Point >::value_type sums_x, typename point_traits< Point >::value_type sums_y, typename point_traits< Point >::value_type sums2_x, typename point_traits< Point >::value_type sums2_y, typename point_traits< Point >::value_type sums_xy, typename point_traits< Point >::value_type n)
Calculates the best fit line whose n samples have the specified coordinate sums.
Note
Returned point p is the samples mean, while (not normalized) direction v may be NaP in case no preferential direction could be chosen.
{
  p.x = sums_x / n, p.y = sums_y / n;
  return bestFit((const Point &)p, v, sums_x, sums_y, sums2_x, sums2_y, sums_xy,
                 n);
}
References bestFit().
bestFit() [3/3]
template<typename Point_ref , typename Point , typename point_iterator > bool tcg::point_ops::bestFit (Point_ref p, Point & d, point_iterator begin, point_iterator end)
Calculates the best fit line of the specified points. This is a mostly overloaded version of bestFit without explicit sums.
{
  typedef typename point_traits<Point>::value_type value_type;
  value_type sums_x, sums_y, sums2_x, sums2_y, sums_xy;
  sums_x = sums_y = sums2_x = sums2_y = sums_xy = 0;
  size_t n = 0;
  point_iterator it;
  for (it = begin; it != end; ++it, ++n) {
    const Point &p = *it;
    sums_x += p.x, sums_y += p.y;
    sums2_x += p.x * p.x, sums2_y += p.y * p.y;
    sums_xy += p.x * p.y;
  }
  return bestFit(p, d, sums_x, sums_y, sums2_x, sums2_y, sums_xy, n);
}
References bestFit().
bisecant()
template<typename Point > Point tcg::point_ops::bisecant (const Point & d0, const Point & d1) inline
Returns the bisecting direction bd between d0 and d1, in the plane region where d x d1 > 0
{
  Point sum   = d0 + d1;
  double norm = sum * sum;
  if (norm < 1)
    sum = ortLeft(d0 - d1), norm = sum * sum;
  else if (cross(d0, d1) < 0)
    sum.x = -sum.x, sum.y = -sum.y;
  norm = sqrt(norm);
  sum.x /= norm, sum.y /= norm;
  return sum;
}
References ortLeft().
cross()
template<typename Point > point_traits< Point >::value_type tcg::point_ops::cross (const Point & a, const Point & b) inline
{
  return a.x * b.y - a.y * b.x;
}
direction() [1/2]
template<typename Point > Point tcg::point_ops::direction (const Point & a, const Point & b) inline
{
  return normalized(b - a);
}
direction() [2/2]
template<typename Point > Point tcg::point_ops::direction (const Point & a, const Point & b, typename point_traits< Point >::value_type tol) inline
{
  return normalized<Point>(b - a, tol);
}
dist()
template<typename Point > point_traits< Point >::value_type tcg::point_ops::dist (const Point & a, const Point & b) inline
{
  return norm(b - a);
}
dist2()
template<typename Point > point_traits< Point >::value_type tcg::point_ops::dist2 (const Point & a, const Point & b) inline
{
  return norm2(b - a);
}
intersectionCoords()
template<typename Point > bool tcg::point_ops::intersectionCoords (const Point & a, const Point & v, const Point & c, const Point & w, typename point_traits< Point >::value_type & s, typename point_traits< Point >::value_type & t, typename point_traits< Point >::value_type detTol = 0)
Calculates scalars s and t: a + s * v == c + t * w
Returns
Whether the calculation succeeded with the specified tolerance parameter.
Note
In case the absolute value of the system's determinant is less or equal to the passed tolerance, the values numeric_ops::NaN() are returned for s and t.
{
  typedef typename point_traits<Point>::value_type value_type;
  value_type det = v.y * w.x - v.x * w.y;
  if (std::abs(det) < detTol) {
    s = t = numeric_ops::NaN<value_type>();
    return false;
  }
  value_type c_aX = c.x - a.x, c_aY = c.y - a.y;
  s = (w.x * c_aY - w.y * c_aX) / det;
  t = (v.x * c_aY - v.y * c_aX) / det;
  return true;
}
Referenced by intersectionSegCoords().
intersectionSegCoords()
template<typename Point > bool tcg::point_ops::intersectionSegCoords (const Point & a, const Point & b, const Point & c, const Point & d, typename point_traits< Point >::value_type & s, typename point_traits< Point >::value_type & t, typename point_traits< Point >::value_type detTol = 0) inline
Calculates scalars s and t: a + s * (b-a) == c + t * (d-c)
Returns
Whether the calculation succeeded with the specified tolerance parameter.
Note
In case the absolute value of the system's determinant is less or equal to the passed tolerance, the values numeric_ops::NaN() are returned for s and t.
{
  return intersectionCoords(a, b - a, c, d - c, s, t, detTol);
}
References intersectionCoords().
lineDist()
template<typename Point > point_traits< Point >::value_type tcg::point_ops::lineDist (const Point & p, const Point & a, const Point & d) inline
Returns the distance of point p from line a->d
{
  return std::abs(lineSignedDist(p, a, d));
}
References lineSignedDist().
lineSide()
template<typename Point > int tcg::point_ops::lineSide (const Point & p, const Point & a, const Point & d, typename point_traits< Point >::value_type tol = 0) inline
Returns the side of line a->d where point p lies, where 1 means left, -1 right, and 0 below tolerance (ie on the line).
{
  typename point_traits<Point>::value_type dist = lineSignedDist(p, a, d);
  return (dist > tol) ? 1 : (dist < -tol) ? -1 : 0;
}
References lineSignedDist().
lineSignedDist()
template<typename Point > point_traits< Point >::value_type tcg::point_ops::lineSignedDist (const Point & p, const Point & a, const Point & d) inline
Returns the signed distance of point p from line a->d, where positive means at its left.
{
  return (p.y - a.y) * d.x - (p.x - a.x) * d.y;
}
Referenced by lineDist(), and lineSide().
NaP()
template<typename Point > Point tcg::point_ops::NaP () inline
                   {
  return Point(numeric_ops::NaN<typename point_traits<Point>::value_type>(),
               numeric_ops::NaN<typename point_traits<Point>::value_type>());
}
norm()
template<typename Point > point_traits< Point >::float_type tcg::point_ops::norm (const Point & a) inline
{
  return sqrt(typename point_traits<Point>::float_type(a * a));
}
norm2()
template<typename Point > point_traits< Point >::value_type tcg::point_ops::norm2 (const Point & a) inline
{
  return a * a;
}
normalize() [1/2]
template<typename Point > void tcg::point_ops::normalize (Point & v) inline
{
  v = normalized(v);
}
normalize() [2/2]
template<typename Point > bool tcg::point_ops::normalize (Point & v, typename point_traits< Point >::value_type tol) inline
{
  typename point_traits<Point>::value_type vNorm = norm(v);
  return (vNorm >= tol) ? (v = v / vNorm, true) : (v = NaP<Point>(), false);
}
normalized() [1/2]
template<typename Point > Point tcg::point_ops::normalized (const Point & v) inline
{
  return v / norm(v);
}
normalized() [2/2]
template<typename Point > Point tcg::point_ops::normalized (const Point & v, typename point_traits< Point >::value_type tol) inline
{
  typename point_traits<Point>::value_type vNorm = norm(v);
  return (vNorm >= tol) ? v / vNorm : NaP<Point>();
}
operator*() [1/2]
template<typename Point > point_traits< Point >::value_type tcg::point_ops::operator* (const Point & a, const Point & b) inline
{
  return a.x * b.x + a.y * b.y;
}
operator*() [2/2]
template<typename Point , typename Scalar > Point tcg::point_ops::operator* (Scalar a, const Point & b) inline
{
  return Point(a * b.x, a * b.y);
}
operator+()
template<typename Point > Point tcg::point_ops::operator+ (const Point & a, const Point & b) inline
{
  return Point(a.x + b.x, a.y + b.y);
}
operator-()
template<typename Point > Point tcg::point_ops::operator- (const Point & a, const Point & b) inline
{
  return Point(a.x - b.x, a.y - b.y);
}
operator/()
template<typename Point , typename Scalar > Point tcg::point_ops::operator/ (const Point & a, Scalar b) inline
{
  return Point(a.x / b, a.y / b);
}
ortCoords()
template<typename Point > Point tcg::point_ops::ortCoords (const Point & p, const Point & p0, const Point & p1)
Returns res: p = p0 + res.x * (p1 - p0) + res.y * (p1 - p0)_orth
{
  Point v01(p1.x - p0.x, p1.y - p0.y);
  Point v02(p.x - p0.x, p.y - p0.y);
  typename point_traits<Point>::value_type den = v01.x * v01.x + v01.y * v01.y;
  return Point((v01.x * v02.x + v01.y * v02.y) / den,
               (v01.y * v02.x - v01.x * v02.y) / den);
}
ortLeft()
template<typename Point > Point tcg::point_ops::ortLeft (const Point & p) inline
Returns the left orthogonal of passed point.
{
  return Point(-p.y, p.x);
}
Referenced by bisecant().
ortRight()
template<typename Point > Point tcg::point_ops::ortRight (const Point & p) inline
Returns the right orthogonal of passed point.
{
  return Point(p.y, -p.x);
}
projection()
template<typename Point > Point tcg::point_ops::projection (const Point & p, const Point & a, const Point & d) inline
Returns the projection of point p on line a -> d
{
  return a + ((p.x - a.x) * d.x + (p.y - a.y) * d.y) * d;
}
rad()
template<typename Point > point_traits< Point >::value_type tcg::point_ops::rad (const Point & p) inline
{
  return atan2(p.y, p.x);
}
segCoord()
template<typename Point > point_traits< Point >::value_type tcg::point_ops::segCoord (const Point & p, const Point & p0, const Point & p1) inline
{
  Point p1_p0 = p1 - p0;
  return ((p - p0) * p1_p0) / (p1_p0 * p1_p0);
}
segDist()
template<typename Point > point_traits< Point >::value_type tcg::point_ops::segDist (const Point & a, const Point & b, const Point & p)
{
  Point v(b - a), w;
  v = v / norm(v);
  if ((w = p - a) * v < 0) return norm(w);
  if ((w = p - b) * (-v) < 0) return norm(w);
  v = Point(-v.y, v.x);
  return std::abs((p - a) * v);
}
triCoords()
template<typename Point > Point tcg::point_ops::triCoords (const Point & p, const Point & p0, const Point & p1, const Point & p2)
Returns res: p = p0 + res.x * (p1 - p0) + res.y * (p2 - p0)
{
  Point v01(p1.x - p0.x, p1.y - p0.y);
  Point v02(p2.x - p0.x, p2.y - p0.y);
  Point p_p0(p.x - p0.x, p.y - p0.y);
  typename point_traits<Point>::value_type det = v01.x * v02.y - v02.x * v01.y;
  return Point((v02.y * p_p0.x - v02.x * p_p0.y) / det,
               (v01.x * p_p0.y - v01.y * p_p0.x) / det);
}