opentoonz: tipc Namespace Reference
tipc Namespace Reference
Classes
class DefaultMessageParser
class Message
class MessageParser
class Server
class ShMemReader
class ShMemWriter
class SocketController
class Stream
Enumerations
enum DefMsgEnum {
SHMEM_REQUEST , SHMEM_RELEASE , TMPFILE_REQUEST , TMPFILE_RELEASE ,
QUIT_ON_ERROR
}
Functions
Message & clr (Message &msg)
Message & reset (Message &msg)
DVAPI bool startBackgroundProcess (QString cmdline)
DVAPI QString applicationSpecificServerName (QString srvName)
DVAPI bool startSlaveConnection (QLocalSocket *socket, QString srvName, int msecs=-1, QString cmdline=QString(), QString threadName=QString())
DVAPI bool startSlaveServer (QString srvName, QString cmdline)
DVAPI QString readMessage (Stream &stream, Message &msg, int msecs=-1)
DVAPI QString readMessageNB (Stream &stream, Message &msg, int msecs=-1, QEventLoop::ProcessEventsFlag flag=QEventLoop::AllEvents)
DVAPI int shm_maxSegmentSize ()
Returns the maximum size of a shared memory segment allowed by the system.
DVAPI int shm_maxSegmentCount ()
Returns the maximum number of shared segments allowed by the system.
DVAPI int shm_maxSharedPages ()
DVAPI int shm_maxSharedCount ()
DVAPI void shm_set (int maxSegmentSize, int maxSegmentCount, int maxSharedSize, int maxSharedCount)
DVAPI QString uniqueId ()
DVAPI int create (QSharedMemory &shmem, int size, bool strictSize=false)
DVAPI bool readShMemBuffer (Stream &stream, Message &msg, ShMemReader *dataReader)
DVAPI bool writeShMemBuffer (Stream &stream, Message &msg, int bufSize, ShMemWriter *dataWriter)
Detailed Description
The tipc namespace provides facilities to deal with inter-process communication tasks. The tipc inner workings make use of Qt's QLocalServer/QLocalSocket standard ipc framework; but moreover, it helps the user hiding some of the intricacies of ipc management. \m \m The tipc model assumes there is a server process running to which several processes can connect to in order to require services through appropriate server-supported commands. Communication happens by sending tipc::Message instances through a tipc::Stream constructed on a QLocalSocket device connected to the server in a Qt-like manner.
Messages encapsulate an atomic communication that must be received in its entirety to be understood by the receiver. Any message sent by a client must provide a QString header to identify the message type, which must be recognizable by the server side to be appropriately parsed. Each message understood by the server process will be replied with a message to ensure the client that the parsing has been completed.
A tipc::Server instance must be used on the server side to process supported messages. Message parsing is responsibility of specific subclasses of the tipc::MessageParser base class, which must be implemented and added to the server.
Tipc standard messages include requests for temporary files or shared memory segments, which must be released after use.
Enumeration Type Documentation
DefMsgEnum
enum tipc::DefMsgEnum
                {
  SHMEM_REQUEST,
  SHMEM_RELEASE,
  TMPFILE_REQUEST,
  TMPFILE_RELEASE,
  QUIT_ON_ERROR
};
Function Documentation
applicationSpecificServerName()
QString tipc::applicationSpecificServerName (QString srvName)
Appends the invoking process' pid to the passed srvName.
{
  return srvName + QString::number(QCoreApplication::applicationPid());
}
clr()
Message & tipc::clr (Message & msg) inline
{
  msg.clear();
  return msg;
}
create()
int tipc::create (QSharedMemory & shmem, int size, bool strictSize = false)
Creates a shared memory segment for passed QSharedMemory.
This function attempts creation of a shared memory segment in the form of Qt's QSharedMemory, with the following UNIX-specific distinctions:
If the segment size is beyond that supported by the system, the function can be set to either fail or return a segment with the maximum supported size. <\LI>
Unlike QSharedMemory::create, this function attempts to reclaim an already existing memory id before creating a new one. <\LI>
{
  bool ok, retried = false;
  if (!strictSize) size = std::min(size, (int)shm_maxSegmentSize());
  tipc_debug(qDebug() << "shMem create: size =" << size);
retry:
  ok = shmem.create(size);
  if (!ok) {
    tipc_debug(qDebug() << "Error: Shared Segment could not be created: #"
                        << shmem.errorString());
    // Unix-specific error recovery follows. See Qt's docs about it.
    // Try to recover error #AlreadyExists - supposedly, the server crashed in a
    // previous instance.
    // As shared memory segments that happen to go this way are owned by the
    // server process with 1
    // reference count, detaching it now may solve the issue.
    if (shmem.error() == QSharedMemory::AlreadyExists && !retried) {
      retried = true;  // We're trying this only once... for now it works.
      shmem.attach();
      shmem.detach();
      goto retry;
    }
    return -1;
  }
  return size;
}
References shm_maxSegmentSize().
Referenced by writeShMemBuffer().
readMessage()
QString tipc::readMessage (Stream & stream, Message & msg, int msecs = -1)
Waits and reads the next message from stream. This function is mainly a useful macro that encapsulates the following steps in one call:
Flush the write buffer (output messages)
Wait until an input message is completely readable
Read the message from stream
Read the first string from the message and return it
This function returns an empty QString if the message could not be entirely retrieved from the stream.
{
  msg.clear();
  stream.flush();
  if (!stream.readMessage(msg, msecs)) return QString();
  QString res;
  msg >> res;
  return res;
}
References tipc::Stream::flush(), and tipc::Stream::readMessage().
Referenced by readShMemBuffer(), startSlaveServer(), and writeShMemBuffer().
readMessageNB()
QString tipc::readMessageNB (Stream & stream, Message & msg, int msecs = -1, QEventLoop::ProcessEventsFlag flag = QEventLoop::AllEvents)
The non-blocking equivalent to tipc::readMessage.
{
  msg.clear();
  if (!stream.readMessageNB(msg, msecs, flag)) return QString();
  QString res;
  msg >> res;
  return res;
}
References tipc::Stream::readMessageNB().
readShMemBuffer()
bool tipc::readShMemBuffer (Stream & stream, Message & msg, ShMemReader * dataReader)
Reads data through a shared memory segment medium.
{
  tipc_debug(QTime time; time.start(););
  tipc_debug(qDebug("tipc::readShMemBuffer entry"));
  // Read the id from stream
  QString res(tipc::readMessage(stream, msg));
  if (res != "shm") {
    tipc_debug(qDebug("tipc::readShMemBuffer exit (res != \"shm\")"));
    return false;
  }
  // Read message and reply
  QString id, chkStr;
  int bufSize;
  msg >> id >> bufSize >> chkStr;
  // Data is ready to be read - attach to the shared memory segment.
  QSharedMemory shmem(id);
  shmem.attach();
  if (!shmem.isAttached()) {
    tipc_debug(qDebug("tipc::readShMemBuffer exit (shmem not attached)"));
    return false;
  }
  // Start reading from it
  int chunkData, remainingData = bufSize;
  while (true) {
    msg >> chunkData;
    tipc_debug(QTime xchTime; xchTime.start());
    shmem.lock();
    remainingData -= dataReader->read((const char *)shmem.data(), chunkData);
    shmem.unlock();
    tipc_debug(qDebug() << "exchange time:" << xchTime.elapsed());
    // Data was read. Inform the writer
    stream << (msg << clr << QString("ok"));
    stream.flush();
    if (remainingData <= 0) break;
    // Wait for more chunks
    if (tipc::readMessage(stream, msg) != "chk") {
      tipc_debug(
          qDebug("tipc::readShMemBuffer exit (unexpected chunk absence)"));
      return false;
    }
  }
  shmem.detach();
  tipc_debug(qDebug("tipc::readShMemBuffer exit"));
  tipc_debug(qDebug() << "tipc::readShMemBuffer time:" << time.elapsed());
  return true;
}
References tipc::Stream::flush(), and readMessage().
reset()
Message & tipc::reset (Message & msg) inline
{
  msg.ds().device()->seek(0);
  return msg;
}
shm_maxSegmentCount()
int tipc::shm_maxSegmentCount ()
Returns the maximum number of shared segments allowed by the system.
{
  if (shm_seg < 0) {
#ifdef MACOSX
    size_t valSize = sizeof(TINT64);
    TINT64 val;
    sysctlbyname("kern.sysv.shmseg", &val, &valSize, NULL, 0);
    shm_seg = std::min(val, (TINT64)(std::numeric_limits<int>::max)());
#else
    // Windows case: no such limit - again, using limit against max due to Qt
    shm_seg = (std::numeric_limits<int>::max)();
#endif
  }
  return shm_seg;
}
Referenced by writeShMemBuffer().
shm_maxSegmentSize()
int tipc::shm_maxSegmentSize ()
Returns the maximum size of a shared memory segment allowed by the system.
{
  if (shm_max < 0) {
#ifdef MACOSX
    // Retrieve it by invoking sysctl
    size_t valSize = sizeof(TINT64);
    TINT64 val;
    sysctlbyname("kern.sysv.shmmax", &val, &valSize, NULL, 0);
    shm_max = std::min(val, (TINT64)(std::numeric_limits<int>::max)());
#else
    // Windows case: no such limit
    // Observe that QSharedMemory accepts only an int size - so the num_lim is
    // against int.
    shm_max = (std::numeric_limits<int>::max)();
#endif
  }
  return shm_max;
}
Referenced by create().
shm_maxSharedCount()
int tipc::shm_maxSharedCount ()
{
  if (shm_mni < 0) {
#ifdef MACOSX
    size_t valSize = sizeof(TINT64);
    TINT64 val;
    sysctlbyname("kern.sysv.shmmni", &val, &valSize, NULL, 0);
    shm_mni = std::min(val, (TINT64)(std::numeric_limits<int>::max)());
#else
    shm_mni = (std::numeric_limits<int>::max)();
#endif
  }
  return shm_mni;
}
shm_maxSharedPages()
int tipc::shm_maxSharedPages ()
{
  if (shm_all < 0) {
#ifdef MACOSX
    size_t valSize = sizeof(TINT64);
    TINT64 val;
    sysctlbyname("kern.sysv.shmall", &val, &valSize, NULL, 0);
    shm_all = std::min(val, (TINT64)(std::numeric_limits<int>::max)());
#else
    shm_all = (std::numeric_limits<int>::max)();
#endif
  }
  return shm_all;
}
shm_set()
void tipc::shm_set (int shmmax, int shmseg, int shmall, int shmmni)
Attempts to set the shared memory parameters to the system. This is only working on MAC's SystemV shm, it's a no-op on Win. This function will fail anyway if the process is not owned by an admin.
{
  tipc_debug(qDebug("shmmax: %i, shmseg: %i, shmall: %i, shmmni: %i", shmmax,
                    shmseg, shmall, shmmni));
#ifdef MACOSX
  TINT64 val;
  int err;
  if (shmmax > 0) {
    val = shmmax;
    err = sysctlbyname("kern.sysv.shmmax", NULL, NULL, &val, sizeof(TINT64));
    if (!err) shm_max = shmmax;
  }
  if (shmseg > 0) {
    val = shmseg;
    err = sysctlbyname("kern.sysv.shmseg", NULL, NULL, &val, sizeof(TINT64));
    if (!err) shm_seg = shmseg;
  }
  if (shmall > 0) {
    val = shmall;
    err = sysctlbyname("kern.sysv.shmall", NULL, NULL, &val, sizeof(TINT64));
    if (!err) shm_all = shmall;
  }
  if (shmmni > 0) {
    val = shmmni;
    err = sysctlbyname("kern.sysv.shmmni", NULL, NULL, &val, sizeof(TINT64));
    if (!err) shm_mni = shmmni;
  }
#endif
}
startBackgroundProcess()
bool tipc::startBackgroundProcess (QString cmdline)
{
#ifdef _WIN32
  QProcess *proc = new QProcess;
  proc->start(cmdline);
  if (proc->state() == QProcess::NotRunning) {
    delete proc;
    return false;
  }
  QObject::connect(proc, SIGNAL(finished(int, QProcess::ExitStatus)), proc,
                   SLOT(deleteLater()));
  QObject::connect(proc, SIGNAL(error(QProcess::ProcessError)), proc,
                   SLOT(deleteLater()));
  return true;
#else
  return QProcess::startDetached(cmdline);
  ;
#endif
}
startSlaveConnection()
bool tipc::startSlaveConnection (QLocalSocket * socket, QString srvName, int msecs = -1, QString cmdline = QString(), QString threadName = QString())
Connects the passed socket to the server with name <srvName> + <threadName>. Awaits for the connection up to msecs milliseconds before returning false. If no server was found, a new slave server is started by invoking the supplied command line and connection is re-attempted. Returns true on success, false otherwise.
Warning
Please, observe that a correct slave server name should be ensured to be unique to the parent process.
{
  QTime time;
  time.start();
  if (msecs == -1) msecs = (std::numeric_limits<int>::max)();
  QString fullSrvName(srvName + threadName);
  socket->connectToServer(fullSrvName);
  // If the socket is not connecting, the server lookup table returned that the
  // no server with
  // the passed name exists. This means that a server must be created.
  if (socket->state() == QLocalSocket::UnconnectedState && !cmdline.isEmpty()) {
    // Completely serialize the server start
    static QMutex mutex;
    QMutexLocker locker(&mutex);
    // Retry connection - this is required due to the mutex
    socket->connectToServer(fullSrvName);
    if (socket->state() != QLocalSocket::UnconnectedState) goto connecting;
    // Invoke the supplied command line to start the server
    if (!tipc::startSlaveServer(srvName, cmdline)) return false;
    // Reconnect to the server
    socket->connectToServer(fullSrvName);
    if (socket->state() == QLocalSocket::UnconnectedState) return false;
  }
connecting:
  // Now, the server is connecting or already connected. Wait until the socket
  // is connected.
  socket->waitForConnected(msecs - time.elapsed());
  if (socket->state() != QLocalSocket::ConnectedState) return false;
  return true;
}
References startSlaveServer().
startSlaveServer()
bool tipc::startSlaveServer (QString srvName, QString cmdline)
Invokes the passed command line to run a slave server. A slave server is hereby intended as a 'child' server process which automatically destroys itself in case the calling application crashes. This process MUST support one server, running in the MAIN THREAD, whose name is <srvName>_main. This function waits until the main server is up and ready to listen for incoming connections - no timeout accepted.
Warning
Please, observe that a correct slave server name should be ensured to be unique to the system.
{
  if (!tipc::startBackgroundProcess(cmdline)) return false;
  QString mainSrvName(srvName + "_main");
  // Establish a dummy socket connection to provide a mean for the process
  // to tell whether the calling process exited unexpectedly.
  QLocalSocket *dummySock = new QLocalSocket;
  dummySock->connectToServer(mainSrvName);
  // Wait up to msecs until the socket is connecting. Wait a small amount of
  // time
  // until the server is up and listening to connection (there is no other way
  // to tell).
  while (dummySock->state() == QLocalSocket::UnconnectedState) {
#ifdef _WIN32
    Sleep(10);
#else
    usleep(10 << 10);  // 10.24 msecs
#endif
    dummySock->connectToServer(mainSrvName);
  }
  dummySock->waitForConnected(-1);
  tipc::Stream stream(dummySock);
  tipc::Message msg;
  // Supply the 'quit if this socket connection fails' command
  // This command ensure termination of the child process in case of some errors
  // or ending of the program
  stream << (msg << QString("$quit_on_error"));
  if (tipc::readMessage(stream, msg, 3000) == QString()) {
    std::cout << "tipc::startSlaveServer - tipc::readMessage TIMEOUT"
              << std::endl;
    return false;
  }
  // The server should die if dummyDock is destroyed. This should happen when
  // the *MAIN* thread
  // in *this process* exits. So, if this is not the main thread, we must move
  // the socket there.
  if (QCoreApplication::instance() &&
      QThread::currentThread() != QCoreApplication::instance()->thread())
    dummySock->moveToThread(QCoreApplication::instance()->thread());
  // If a connection error takes place, release the dummy socket.
  // Please, observe that this QObject::connect is invoked *AFTER* the
  // connection trials above...
  QObject::connect(dummySock, SIGNAL(error(QLocalSocket::LocalSocketError)),
                   dummySock, SLOT(deleteLater()));
  return true;
}
References readMessage().
Referenced by startSlaveConnection().
uniqueId()
QString tipc::uniqueId ()
Returns an inter-process unique id string; the returned id should be used to create QSharedMemory objects.
                       {
  static QAtomicInt count;
  count.ref();
  return QString::number(QCoreApplication::applicationPid()) + "_" +
         QString::number((int)count);
}
Referenced by writeShMemBuffer().
writeShMemBuffer()
bool tipc::writeShMemBuffer (Stream & stream, Message & msg, int bufSize, ShMemWriter * dataWriter)
Writes data through a shared memory segment medium.
{
  tipc_debug(QTime time; time.start());
  tipc_debug(qDebug("tipc::writeShMemBuffer entry"));
  static QSemaphore sem(tipc::shm_maxSegmentCount());
  sem.acquire(1);
  {
    // Create a shared memory segment, possibly of passed size
    QSharedMemory shmem(tipc::uniqueId());
    bool ok = (tipc::create(shmem, bufSize) > 0);
    if (!ok) goto err;
    // Communicate the shared memory id and bufSize to the reader
    msg << QString("shm") << shmem.key() << bufSize;
    // Fill in data until all the buffer has been sent
    int chunkData, remainingData = bufSize;
    while (remainingData > 0) {
      // Write to the shared memory segment
      tipc_debug(QTime xchTime; xchTime.start());
      shmem.lock();
      remainingData -= chunkData = dataWriter->write(
          (char *)shmem.data(), std::min(shmem.size(), remainingData));
      shmem.unlock();
      tipc_debug(qDebug() << "exchange time:" << xchTime.elapsed());
      stream << (msg << QString("chk") << chunkData);
      if (tipc::readMessage(stream, msg) != "ok") goto err;
      msg.clear();
    }
  }
  sem.release(1);
  tipc_debug(qDebug("tipc::writeShMemBuffer exit"));
  tipc_debug(qDebug() << "tipc::writeShMemBuffer time:" << time.elapsed());
  return true;
err:
  tipc_debug(qDebug("tipc::writeShMemBuffer exit (error)"));
  msg.clear();
  sem.release(1);
  return false;
}
References create(), readMessage(), shm_maxSegmentCount(), and uniqueId().