opentoonz: tcg::numeric_ops Namespace Reference
tcg::numeric_ops Namespace Reference
Functions
template<typename Scalar >
Scalar NaN ()
template<typename Scalar >
int sign (Scalar val, Scalar tol=0)
template<typename Scalar >
Scalar trunc (Scalar val)
Computes the nearest integer not greater in magnitude than the given value.
template<typename Scalar >
Scalar truncStrict (Scalar val)
template<typename Scalar >
Scalar grow (Scalar val)
Computes the nearest integer not lesser in magnitude than the given value.
template<typename Scalar >
Scalar growStrict (Scalar val)
template<typename Scalar >
bool areNear (Scalar a, Scalar b, Scalar tolerance)
template<typename Scalar >
std::enable_if<!tcg::is_floating_point< Scalar >::value, Scalar >::type mod (Scalar val, Scalar mod)
template<typename Scalar >
std::enable_if< tcg::is_floating_point< Scalar >::value, Scalar >::type mod (Scalar val, Scalar mod)
template<typename Scalar >
Scalar mod (Scalar val, Scalar a, Scalar b)
template<typename Scalar >
Scalar modShift (Scalar val1, Scalar val2, Scalar m)
template<typename Scalar >
Scalar modShift (Scalar val1, Scalar val2, Scalar a, Scalar b)
template<typename Scalar >
std::enable_if<!tcg::is_floating_point< Scalar >::value, Scalar >::type div (Scalar val, Scalar d)
template<typename Scalar >
std::enable_if< tcg::is_floating_point< Scalar >::value, Scalar >::type div (Scalar val, Scalar d)
template<typename Scalar >
Scalar div (Scalar val, Scalar a, Scalar b)
template<typename T , typename Scalar >
T lerp (const T &v0, const T &v1, Scalar t)
Linear interpolation of values v0 and v1 with parameter t.
template<typename T , typename Scalar >
T bezier (const T &c0, const T &c1, const T &c2, Scalar t)
Computes the second degree Bezier curve of control points c0, c1 and c2 at parameter t.
template<typename UScalar >
UScalar GE_2Power (UScalar val)
Detailed Description
Contains small function snippets to manipulate scalars or numerical objects.
Function Documentation
areNear()
template<typename Scalar > bool tcg::numeric_ops::areNear (Scalar a, Scalar b, Scalar tolerance) inline
{
  return (std::abs(b - a) < tolerance);
}
bezier()
template<typename T , typename Scalar > T tcg::numeric_ops::bezier (const T & c0, const T & c1, const T & c2, Scalar t) inline
Computes the second degree Bezier curve of control points c0, c1 and c2 at parameter t.
{
  Scalar one_t = 1 - t, t_one_t = t * one_t;  // 3  Scalar-Scalar products
  return (one_t * one_t) * c0 + (t_one_t + t_one_t) * c1 +
         (t * t) * c2;  // 3  Scalar-T products
  // return (c0 * one_t + c1 * t) * one_t + (c1 * one_t + c2 * t) * t;
  // // 6 Scalar-T products
}
div() [1/3]
template<typename Scalar > Scalar tcg::numeric_ops::div (Scalar val, Scalar a, Scalar b) inline
Returns the quotient associated to the remainder calculated with mod().
Returns
Integral quotient of the division of val by (b-a).
{
  return div(val - a, b - a);
}
References div().
div() [2/3]
template<typename Scalar > std::enable_if<!tcg::is_floating_point< Scalar >::value, Scalar >::type tcg::numeric_ops::div (Scalar val, Scalar d) inline
Returns the quotient associated to the remainder calculated with mod().
Returns
Integral quotient of the division of val by d.
{
  TCG_STATIC_ASSERT(-3 / 5 == 0);
  TCG_STATIC_ASSERT(3 / -5 == 0);
  return (val < 0 || d < 0) ? (val / d) - 1 : val / d;
}
References TCG_STATIC_ASSERT.
Referenced by div().
div() [3/3]
template<typename Scalar > std::enable_if< tcg::is_floating_point< Scalar >::value, Scalar >::type tcg::numeric_ops::div (Scalar val, Scalar d) inline
Returns the quotient associated to the remainder calculated with mod().
Returns
Integral quotient of the division of val by d.
{
  return std::floor(val / d);
}
GE_2Power()
template<typename UScalar > UScalar tcg::numeric_ops::GE_2Power (UScalar val) inline
Deprecated:
{
  if (!val) return 0;
  --val;
  UScalar i;
  for (i = 0; val; ++i) val = val >> 1;
  return 1 << i;
}
Referenced by MeshTexturizer::bindTexture().
grow()
template<typename Scalar > Scalar tcg::numeric_ops::grow (Scalar val)
Computes the nearest integer not lesser in magnitude than the given value.
{
  return (val < 0) ? std::floor(val) : std::ceil(val);
}
growStrict()
template<typename Scalar > Scalar tcg::numeric_ops::growStrict (Scalar val)
Computes the nearest integer strictly not lesser in magnitude than the given value
{
  return (val < 0) ? std::ceil(val - 1) : std::floor(val + 1);
}
lerp()
template<typename T , typename Scalar > T tcg::numeric_ops::lerp (const T & v0, const T & v1, Scalar t) inline
Linear interpolation of values v0 and v1 with parameter t.
{
  return (1 - t) * v0 + t * v1;
}
mod() [1/3]
template<typename Scalar > Scalar tcg::numeric_ops::mod (Scalar val, Scalar a, Scalar b) inline
{
  return a + mod(val - a, b - a);
}
mod() [2/3]
template<typename Scalar > std::enable_if<!tcg::is_floating_point< Scalar >::value, Scalar >::type tcg::numeric_ops::mod (Scalar val, Scalar mod) inline
{
  Scalar m = val % mod;
  return (m >= 0) ? m : m + mod;
}
mod() [3/3]
template<typename Scalar > std::enable_if< tcg::is_floating_point< Scalar >::value, Scalar >::type tcg::numeric_ops::mod (Scalar val, Scalar mod) inline
{
  Scalar m = fmod(val, mod);
  return (m >= 0) ? m : m + mod;
}
modShift() [1/2]
template<typename Scalar > Scalar tcg::numeric_ops::modShift (Scalar val1, Scalar val2, Scalar a, Scalar b) inline
Returns the modular shift value with minimal abs: mod(val2, a, b) = mod(val1 + shift, a, b)
{
  return modShift(val1 - a, val2 - a, b - a);
}
References modShift().
modShift() [2/2]
template<typename Scalar > Scalar tcg::numeric_ops::modShift (Scalar val1, Scalar val2, Scalar m) inline
Returns the modular shift value with minimal abs: mod(val2, m) = mod(val1 + shift, m)
{
  Scalar shift1 = mod(val2 - val1, m), shift2 = m - shift1;
  return (shift2 < shift1) ? -shift2 : shift1;
}
Referenced by modShift().
NaN()
template<typename Scalar > Scalar tcg::numeric_ops::NaN () inline
                    {
  return (std::numeric_limits<Scalar>::max)();
}
sign()
template<typename Scalar > int tcg::numeric_ops::sign (Scalar val, Scalar tol = 0) inline
Calculates the sign of a scalar.
Remarks
This function returns the integral values 1 in case the input value is positive, -1 in case it's negative, and 0 in case it's exactly 0.
Returns
The sign of the input scalar.
{
  return (val > tol) ? 1 : (val < -tol) ? -1 : 0;
}
trunc()
template<typename Scalar > Scalar tcg::numeric_ops::trunc (Scalar val)
Computes the nearest integer not greater in magnitude than the given value.
{
  return (val < 0) ? std::ceil(val) : std::floor(val);
}
truncStrict()
template<typename Scalar > Scalar tcg::numeric_ops::truncStrict (Scalar val)
Computes the nearest integer strictly not greater in magnitude than the given value
{
  return (val < 0) ? std::floor(val + 1) : std::ceil(val - 1);
}