opentoonz: StudioPaletteCmd Namespace Reference
StudioPaletteCmd Namespace Reference
Provides a collection of methods to manage StudioPalette.
Functions
DVAPI void loadIntoCurrentPalette (TPaletteHandle *paletteHandle, const TFilePath &fp)
DVAPI void loadIntoCurrentPalette (TPaletteHandle *paletteHandle, TPalette *palette)
DVAPI void loadIntoCurrentPalette (TPaletteHandle *paletteHandle, TPalette *palette, TXshLevelHandle *currentLevelHandle, int tolerance)
DVAPI void mergeIntoCurrentPalette (TPaletteHandle *paletteHandle, const TFilePath &fp)
DVAPI void mergeIntoCurrentPalette (TPaletteHandle *paletteHandle, TPalette *palette)
DVAPI void replaceWithCurrentPalette (TPaletteHandle *paletteHandle, TPaletteHandle *stdPaletteHandle, const TFilePath &fp)
DVAPI void updateAllLinkedStyles (TPaletteHandle *paletteHandle, TXsheetHandle *xsheetHandle)
DVAPI void deletePalette (const TFilePath &fp)
DVAPI void movePalette (const TFilePath &dstPath, const TFilePath &srcPath)
DVAPI TFilePath createPalette (const TFilePath &folderPath, std::string paletteName, const TPalette *palette)
DVAPI TFilePath addFolder (const TFilePath &parentFolderPath)
DVAPI void deleteFolder (const TFilePath &folderPath)
DVAPI void scanPalettes (const TFilePath &folder, const TFilePath &sourcePath)
void loadIntoCurrentPalette ()
void loadIntoCurrentPalette (const TFilePath &fp)
void mergeIntoCurrentPalette (const TFilePath &fp)
void replaceWithCurrentPalette (const TFilePath &fp)
void loadIntoCleanupPalette (const TFilePath &fp)
void replaceWithCleanupPalette (const TFilePath &fp)
void updateAllLinkedStyles ()
TFilePath createPalette (const TFilePath &folderPath, string paletteName, const TPalette *palette)
Detailed Description
Provides a collection of methods to manage StudioPalette.
Function Documentation
addFolder()
TFilePath StudioPaletteCmd::addFolder (const TFilePath & parentFolderPath)
Add a folder in StudioPalette TFilePath parentFolderPath. If there are any problems send an error message.
{
  TFilePath folderPath;
  try {
    folderPath = StudioPalette::instance()->createFolder(parentFolderPath);
    TUndoManager::manager()->add(new CreateFolderUndo(folderPath));
  } catch (TException &e) {
    error("Can't create palette folder: " +
          QString(toString(e.getMessage()).c_str()));
  } catch (...) {
    error("Can't create palette folder");
  }
  return folderPath;
}
Referenced by StudioPaletteTreeViewer::addNewFolder().
createPalette() [1/2]
TFilePath StudioPaletteCmd::createPalette (const TFilePath & folderName, std::string paletteName, const TPalette * palette)
Create palette palette in folder folderName with name paletteName. If there are any problems send an error message.
{
  TFilePath palettePath;
  TFileStatus status(folderName);
  // exception will be caught either in StudioPaletteTreeViewer::addNewPalette()
  // or StudioPaletteTreeViewer::dropEvent()
  if (!status.isDirectory()) throw TException("Select a folder.");
  if (!status.doesExist()) {
    TSystem::mkDir(folderName);
    FolderListenerManager::instance()->notifyFolderChanged(
        folderName.getParentDir());
  }
  // StudioPalette::setPalette() and createPalette() may throw exception on
  // saving, it will be caught in the upper functions as wel
  palettePath =
      StudioPalette::instance()->createPalette(folderName, paletteName);
  if (palette)
    StudioPalette::instance()->setPalette(palettePath, palette, true);
  TUndoManager::manager()->add(new CreatePaletteUndo(palettePath));
  return palettePath;
}
References TFilePath::getParentDir().
Referenced by StudioPaletteTreeViewer::addNewPalette(), StudioPaletteTreeViewer::addNewPlt(), and StudioPaletteTreeViewer::dropEvent().
createPalette() [2/2]
TFilePath StudioPaletteCmd::createPalette (const TFilePath & folderName, string paletteName, const TPalette * palette)
Create palette palette in folder folderName with name paletteName. If there are any problems send an error message.
{
  TFilePath palettePath;
  try {
    if (!TFileStatus(folderName).doesExist()) TSystem::mkDir(folderName);
    palettePath =
        StudioPalette::instance()->createPalette(folderName, paletteName);
    if (palette) StudioPalette::instance()->setPalette(palettePath, palette);
    TUndoManager::manager()->add(new CreatePaletteUndo(palettePath));
  } catch (TException &e) {
    error("Can't create palette: " + QString(toString(e.getMessage()).c_str()));
  } catch (...) {
    error("Can't create palette");
  }
  return palettePath;
}
deleteFolder()
void StudioPaletteCmd::deleteFolder (const TFilePath & folderPath)
Delete folder folderPath. If there are any problems in deleting send an error message.
{
  TUndo *undo = new DeleteFolderUndo(folderPath);
  try {
    StudioPalette::instance()->deleteFolder(folderPath);
    TUndoManager::manager()->add(undo);
  } catch (TException &e) {
    delete undo;
    error("Can't delete palette: " + QString(toString(e.getMessage()).c_str()));
  } catch (...) {
    delete undo;
    error("Can't delete palette");
  }
}
Referenced by StudioPaletteTreeViewer::deleteItem().
deletePalette()
void StudioPaletteCmd::deletePalette (const TFilePath & fp)
Delete palette identified by fp in StudioPalette. If there are any problems in loading send an error message.
{
  TUndo *undo = new DeletePaletteUndo(fp);
  try {
    StudioPalette::instance()->deletePalette(fp);
    TUndoManager::manager()->add(undo);
  } catch (TException &e) {
    delete undo;
    error("Can't delete palette: " + QString(toString(e.getMessage()).c_str()));
  } catch (...) {
    delete undo;
    error("Can't delete palette");
  }
}
Referenced by StudioPaletteTreeViewer::deleteItem().
loadIntoCleanupPalette()
void StudioPaletteCmd::loadIntoCleanupPalette (const TFilePath & fp)
{
  // DA FARE
  //  ColorController *cc = ColorController::instance();
  //  int styleId = cc->getCurrentStyleIndex();
  TPalette *palette = StudioPalette::instance()->getPalette(fp, true);
  if (!palette) return;
  // DA FARE
  //  TPalette *current = cc->getCleanupPalette();
  TPalette *current = TApp::instance()
                          ->getCurrentScene()
                          ->getScene()
                          ->getProperties()
                          ->getCleanupPalette();
  assert(current);
  TPalette *old = current->clone();
  current->assign(palette);
  // DA FARE
  //  if(cc->getCurrentStylePalette() == current &&
  //  styleId>=current->getStyleCount())
  //    cc->setCurrentStyle(1);
  TUndoManager::manager()->add(
      new PaletteAssignUndo(current, old, current->clone()));
  TApp::instance()->getCurrentPalette()->notifyPaletteChanged();
}
loadIntoCurrentPalette() [1/5]
void StudioPaletteCmd::loadIntoCurrentPalette ()
{
  // DA FARE
  //  ColorController *cc = ColorController::instance();
  //  TPalette *palette = cc->getStudioPalette();
  TPalette *palette = TApp::instance()->getCurrentPalette()->getPalette();
  wstring gname = palette->getGlobalName();
  TFilePath fp  = StudioPalette::instance()->getPalettePath(gname);
  if (fp != TFilePath()) loadIntoCurrentPalette(fp);
  // DA FARE
  if (!palette->isCleanupPalette())
    TApp::instance()->getCurrentLevel()->getLevel()->setPaletteDirtyFlag(true);
  else
    TApp::instance()->getCurrentScene()->setDirtyFlag(true);
  TApp::instance()->getCurrentPalette()->notifyPaletteChanged();
}
loadIntoCurrentPalette() [2/5]
void StudioPaletteCmd::loadIntoCurrentPalette (const TFilePath & fp)
{
  // DA FARE
  //  ColorController *cc = ColorController::instance();
  //  int styleId = cc->getCurrentStyleIndex();
  TApp *app   = TApp::instance();
  int styleId = app->getCurrentPalette()->getStyleIndex();
  TPalette *palette = StudioPalette::instance()->getPalette(fp, true);
  if (!palette) return;
  // DA FARE
  TPalette *current = !palette->isCleanupPalette()
                          ? app->getCurrentPalette()->getPalette()
                          : app->getCurrentScene()
                                ->getScene()
                                ->getProperties()
                                ->getCleanupPalette();
  //    ? cc->getCleanupPalette()
  //    : cc->getLevelPalette();
  if (!current) return;
  TPalette *old = current->clone();
  while (palette->getStyleCount() < current->getStyleCount()) {
    int index = palette->getStyleCount();
    assert(index < current->getStyleCount());
    TColorStyle *style = current->getStyle(index)->clone();
    palette->addStyle(style);
  }
  current->assign(palette);
  // DA FARE
  //  if(cc->getCurrentStylePalette() == current &&
  //  styleId>=current->getStyleCount())
  //    cc->setCurrentStyle(1);
  TUndoManager::manager()->add(
      new PaletteAssignUndo(current, old, current->clone()));
  // DA FARE
  if (  // current == cc->getCurrentStylePalette() &&
      app->getCurrentLevel()->getLevel()) {
    TXshSimpleLevel *sl = app->getCurrentLevel()->getSimpleLevel();
    if (sl) {
      sl->invalidateIcons();
      sl->setDirtyFlag(true);
    }
    app->instance()->getCurrentLevel()->notifyLevelChange();
  }
  app->getCurrentPalette()->notifyPaletteChanged();
}
loadIntoCurrentPalette() [3/5]
void StudioPaletteCmd::loadIntoCurrentPalette (TPaletteHandle * paletteHandle, const TFilePath & fp)
{
  TPalette *palette = StudioPalette::instance()->getPalette(fp, false);
  if (!palette) return;
  loadIntoCurrentPalette(paletteHandle, palette);
}
loadIntoCurrentPalette() [4/5]
void StudioPaletteCmd::loadIntoCurrentPalette (TPaletteHandle * paletteHandle, TPalette * palette)
{
  assert(paletteHandle);
  TPalette *current = paletteHandle->getPalette();
  if (!current) return;
  int styleId = paletteHandle->getStyleIndex();
  TPalette *old = current->clone();
  while (palette->getStyleCount() < current->getStyleCount()) {
    int index = palette->getStyleCount();
    assert(index < current->getStyleCount());
    TColorStyle *style = current->getStyle(index)->clone();
    palette->addStyle(style);
  }
  // keep the color model path unchanged
  TFilePath oldRefImagePath = current->getRefImgPath();
  std::wstring oldGlobalName = current->getGlobalName();
  current->assign(palette, true);
  // keep global name unchanged
  current->setGlobalName(oldGlobalName);
  current->setDirtyFlag(true);
  current->setRefImgPath(oldRefImagePath);
  if (paletteHandle->getPalette() == current &&
      styleId >= current->getStyleCount())
    paletteHandle->setStyleIndex(1);
  TUndoManager::manager()->add(
      new PaletteAssignUndo(current, old, current->clone(), paletteHandle));
  palette->setDirtyFlag(true);
  paletteHandle->notifyPaletteChanged();
}
loadIntoCurrentPalette() [5/5]
void StudioPaletteCmd::loadIntoCurrentPalette (TPaletteHandle * paletteHandle, TPalette * palette, TXshLevelHandle * currentLevelHandle, int tolerance)
{
  adaptLevelToPalette(currentLevelHandle, paletteHandle, plt, tolerance, false);
}
mergeIntoCurrentPalette() [1/3]
void StudioPaletteCmd::mergeIntoCurrentPalette (const TFilePath & fp)
{
  //  ColorController *cc = ColorController::instance();
  TPalette *palette = StudioPalette::instance()->getPalette(fp);
  TApp *app = TApp::instance();
  // DA FARE
  TPalette *current = !palette->isCleanupPalette()
                          ? app->getCurrentPalette()->getPalette()
                          : app->getCurrentScene()
                                ->getScene()
                                ->getProperties()
                                ->getCleanupPalette();
  //    ? cc->getCleanupPalette()
  //    : cc->getLevelPalette();
  if (!current) return;
  TPalette *old = current->clone();
  current->merge(palette);
  TUndoManager::manager()->add(
      new PaletteAssignUndo(current, old, current->clone()));
  app->getCurrentPalette()->notifyPaletteChanged();
  // DA FARE
  if (  // current == cc->getCurrentStylePalette() &&
      app->getCurrentLevel()->getLevel())
    app->getCurrentLevel()->getLevel()->setDirtyFlag(true);
}
mergeIntoCurrentPalette() [2/3]
void StudioPaletteCmd::mergeIntoCurrentPalette (TPaletteHandle * paletteHandle, const TFilePath & fp)
{
  TPalette *palette = StudioPalette::instance()->getPalette(fp);
  if (!palette) return;
  mergeIntoCurrentPalette(paletteHandle, palette);
}
mergeIntoCurrentPalette() [3/3]
void StudioPaletteCmd::mergeIntoCurrentPalette (TPaletteHandle * paletteHandle, TPalette * palette)
{
  assert(paletteHandle);
  TPalette *current = paletteHandle->getPalette();
  if (!current) return;
  if (current->isLocked()) return;
  TPalette *old = current->clone();
  current->merge(palette, true);
  TUndoManager::manager()->add(
      new PaletteAssignUndo(current, old, current->clone(), paletteHandle));
  current->setDirtyFlag(true);
  paletteHandle->notifyPaletteChanged();
}
movePalette()
void StudioPaletteCmd::movePalette (const TFilePath & dstPath, const TFilePath & srcPath)
Move palette from TFilePath srcPath to TFilePath dstPath. If there are any problems in moving send an error message.
{
  try {
    TSystem::touchParentDir(dstPath);
    StudioPalette::instance()->movePalette(dstPath, srcPath);
    TUndoManager::manager()->add(new MovePaletteUndo(dstPath, srcPath));
  } catch (TException &e) {
    error("Can't rename palette: " + QString(toString(e.getMessage()).c_str()));
  } catch (...) {
    error("Can't rename palette");
  }
}
Referenced by StudioPaletteTreeViewer::dropEvent(), and StudioPaletteTreeViewer::onItemChanged().
replaceWithCleanupPalette()
void StudioPaletteCmd::replaceWithCleanupPalette (const TFilePath & fp)
{
  // DA FARE
  // ColorController *cc = ColorController::instance();
  StudioPalette *sp = StudioPalette::instance();
  TPalette *palette = sp->getPalette(fp);
  // DA FARE
  // TPalette *current = cc->getCleanupPalette();
  TPalette *current = TApp::instance()
                          ->getCurrentScene()
                          ->getScene()
                          ->getProperties()
                          ->getCleanupPalette();
  if (!current) return;
  TPalette *old = palette->clone();
  palette->assign(current);
  sp->setPalette(fp, current);
  TUndoManager::manager()->add(
      new StudioPaletteAssignUndo(fp, old, current->clone()));
  TApp::instance()->getCurrentPalette()->notifyPaletteSwitched();
}
replaceWithCurrentPalette() [1/2]
void StudioPaletteCmd::replaceWithCurrentPalette (const TFilePath & fp)
{
  // DA FARE
  // ColorController *cc = ColorController::instance();
  StudioPalette *sp = StudioPalette::instance();
  TPalette *palette = sp->getPalette(fp);
  // DA FARE
  TPalette *current = !palette->isCleanupPalette()
                          ? TApp::instance()->getCurrentPalette()->getPalette()
                          : TApp::instance()
                                ->getCurrentScene()
                                ->getScene()
                                ->getProperties()
                                ->getCleanupPalette();
  //    ? cc->getCleanupPalette()
  //    : cc->getLevelPalette();
  if (!current) return;
  TPalette *old = palette->clone();
  palette->assign(current);
  sp->setPalette(fp, current);
  TUndoManager::manager()->add(
      new StudioPaletteAssignUndo(fp, old, current->clone()));
  // DA FARE
  // Cambio la studioPalette corrente
  //  ColorController::instance()->setStudioPalette(palette);
  DAFARE::setCurrentStudioPalette(current);
  DAFARE::setDirtyFlag(true);
  TApp::instance()->getCurrentPalette()->notifyPaletteSwitched();
}
replaceWithCurrentPalette() [2/2]
void StudioPaletteCmd::replaceWithCurrentPalette (TPaletteHandle * paletteHandle, TPaletteHandle * stdPaletteHandle, const TFilePath & fp)
{
  StudioPalette *sp = StudioPalette::instance();
  TPalette *palette = sp->getPalette(fp);
  if (!palette || palette->isLocked()) return;
  assert(paletteHandle);
  TPalette *current = paletteHandle->getPalette();
  if (!current) return;
  // keep the studio palette's global name unchanged
  std::wstring oldGlobalName = palette->getGlobalName();
  TPalette *old = palette->clone();
  palette->assign(current);
  // put back the global name
  palette->setGlobalName(oldGlobalName);
  if (!trySetStudioPalette(fp, current, true)) {
    palette->assign(old);
    return;
  }
  TUndoManager::manager()->add(
      new StudioPaletteAssignUndo(fp, old, current->clone(), paletteHandle));
  // Cambio la studioPalette correntette(palette);
  stdPaletteHandle->setPalette(palette);
  stdPaletteHandle->notifyPaletteSwitched();
}
scanPalettes()
void StudioPaletteCmd::scanPalettes (const TFilePath & folder, const TFilePath & sourcePath)
{
  error("uh oh");
}
updateAllLinkedStyles() [1/2]
void StudioPaletteCmd::updateAllLinkedStyles ()
{
  StudioPalette *sp   = StudioPalette::instance();
  TApp *app           = TApp::instance();
  ToonzScene *scene   = app->getCurrentScene()->getScene();
  TLevelSet *levelSet = scene->getLevelSet();
  for (int i = 0; i < levelSet->getLevelCount(); i++) {
    TXshLevel *xl       = levelSet->getLevel(i);
    TXshSimpleLevel *sl = xl ? xl->getSimpleLevel() : 0;
    if (!sl) continue;
    TPalette *palette = sl->getPalette();
    if (palette) {
      sp->updateLinkedColors(palette);
      if (sl->getType() == TZP_XSHLEVEL) {
        std::vector<TFrameId> fids;
        sl->getFids(fids);
        std::vector<TFrameId>::iterator it;
        for (it = fids.begin(); it != fids.end(); ++it) {
          TFrameId fid = *it;
          string id    = sl->getImageId(fid);
          IconGenerator::instance()->invalidate(sl, fid);
          // ImageManager::instance()->invalidate(id);
        }
      }
    }
  }
  TApp::instance()->getCurrentPalette()->notifyPaletteChanged();
}
updateAllLinkedStyles() [2/2]
void StudioPaletteCmd::updateAllLinkedStyles (TPaletteHandle * paletteHandle, TXsheetHandle * xsheetHandle)
{
  if (!xsheetHandle) return;
  TXsheet *xsheet = xsheetHandle->getXsheet();
  if (!xsheet) return;
  ToonzScene *scene = xsheet->getScene();
  if (!scene) return;
  // emit signal only if something changed
  bool somethingChanged = false;
  StudioPalette *sp   = StudioPalette::instance();
  TLevelSet *levelSet = scene->getLevelSet();
  for (int i = 0; i < levelSet->getLevelCount(); i++) {
    TXshLevel *xl       = levelSet->getLevel(i);
    TXshSimpleLevel *sl = xl ? xl->getSimpleLevel() : 0;
    if (!sl) continue;
    TPalette *palette = sl->getPalette();
    if (palette) {
      somethingChanged = somethingChanged | sp->updateLinkedColors(palette);
      if (sl->getType() == TZP_XSHLEVEL) {
        std::vector<TFrameId> fids;
        sl->getFids(fids);
        std::vector<TFrameId>::iterator it;
        for (it = fids.begin(); it != fids.end(); ++it) {
          TFrameId fid   = *it;
          std::string id = sl->getImageId(fid);
        }
      }
    }
  }
  if (!paletteHandle || !paletteHandle->getPalette()) return;
  if (somethingChanged) paletteHandle->notifyColorStyleChanged();
}