opentoonz: ToonzExt Namespace Reference
ToonzExt Namespace Reference
Toonz Extension namespace.
Classes
class CompositeStatus
This class maintains internal data for Dragger manipulator.
struct ContextStatus
This class maintains data required from manipulator.
class CornerDeformation
class DeformationSelector
This class is a Singleton that selects the correct StrokeDeformationImpl that will use StrokeDeformation.
class Designer
This class is a visitor to manage properly Draw method.
class EvenInt
This class is an abstraction to wrap all odd number.
class InterfaceStatus
class LinearPotential
class NotSymmetricBezierPotential
class NotSymmetricExpPotential
class OddInt
This class is an abstraction to wrap all odd number.
class OverallDesigner
class Potential
Potential is an abstraction to maintain a mathematical potential function.
class Selector
class SmoothDeformation
class SquarePotential
class StraightCornerDeformation
class StrokeDeformation
This class is the interface for manipulation algorithms.
class StrokeDeformationImpl
class StrokeParametricDeformer
This class implements new deformer.
class StrokeStatus
This class maintains internal data for Dragger manipulator.
Typedefs
typedef std::pair< double, double > Interval
An useful alias for a pair of double.
typedef std::vector< Interval > Intervals
List of intervals.
Functions
DVAPI bool straightCornersDetector (const TStroke *stroke, std::vector< double > &corners)
Like cornersDetector but for straight corners.
DVAPI bool detectStraightIntervals (const TStroke *stroke, ToonzExt::Intervals &intervals, double tolerance=TConsts::epsilon)
Find intervals where stroke is a straight line.
DVAPI bool findNearestStraightCorners (const TStroke *s, double actualW, Interval &out, const ToonzExt::Intervals *const cl=0, double tolerance=TConsts::epsilon)
Retrieve parameters for straight intervals near actualW parameter.
DVAPI bool isAStraightCorner (const TStroke *s, double actualW, const ToonzExt::Intervals *const cl=0, double tolerance=TConsts::epsilon)
DVAPI bool cornersDetector (const TStroke *stroke, int minDegree, std::vector< double > &corners)
Enhanced version of Toonz detect corners.
DVAPI bool detectSpireIntervals (const TStroke *stroke, ToonzExt::Intervals &intervals, int minDegree)
Find intervals where stroke has limited from spire.
DVAPI bool findNearestSpireCorners (const TStroke *s, double actualW, Interval &out, int cornerSize, const ToonzExt::Intervals *const cl=0, double tolerance=TConsts::epsilon)
Retrieve parameters for corners near actualW parameter.
DVAPI bool isASpireCorner (const TStroke *s, double w, int cornerSize, const ToonzExt::Intervals *const cl=0, double tolerance=TConsts::epsilon)
DVAPI void findCorners (const TStroke *stroke, Intervals &corners, Intervals &intervals, int angle, double tolerance)
Retrieve corners of a TStroke.
DVAPI bool findNearestCorners (const TStroke *stroke, double w, Interval &out, const Intervals &values, double tolerance=TConsts::epsilon)
Retrieve corners of a TStroke.
DVAPI TStroke * rotateControlPoint (const TStroke *stroke, const ToonzExt::EvenInt &even, double atLength)
Rotate the control point at even position [0,2,4,...] in a new position along the close path of a selfLoop stroke.
DVAPI bool getAllW (const TStroke *stroke, const TPointD &pnt, double &dist2, std::vector< double > &parameters)
DVAPI bool replaceStroke (TStroke *old_stroke, TStroke *new_stroke, unsigned int n_, TVectorImageP &vi)
Replace a stroke in a vector image.
void cloneStrokeStatus (const TStroke *from, TStroke *to)
Copy several parameters that are not copied with operator=.
template<class T >
bool isValid (const T *s)
bool isValid (double w)
std::ostream & operator<< (std::ostream &os, const Interval &interval)
Detailed Description
Toonz Extension namespace.
This namespace contains a lot of class and functions to manipulate strokes.
Typedef Documentation
Interval
typedef std::pair<double, double> ToonzExt::Interval
An useful alias for a pair of double.
Intervals
typedef std::vector<Interval> ToonzExt::Intervals
List of intervals.
Function Documentation
cloneStrokeStatus()
void ToonzExt::cloneStrokeStatus (const TStroke * from, TStroke * to)
Copy several parameters that are not copied with operator=.
{
  if (!ToonzExt::isValid(from) || !ToonzExt::isValid(to)) return;
  to->setId(from->getId());
  to->setSelfLoop(from->isSelfLoop());
  to->setStyle(from->getStyle());
  to->setAverageThickness(from->getAverageThickness());
  to->invalidate();
  to->enableComputeOfCaches();
}
References TStroke::getAverageThickness(), TStroke::getStyle(), TStroke::invalidate(), TStroke::isSelfLoop(), TStroke::setAverageThickness(), TStroke::setSelfLoop(), and TStroke::setStyle().
Referenced by ToonzExt::StrokeDeformationImpl::deactivate_impl().
cornersDetector()
DVAPI bool ToonzExt::cornersDetector (const TStroke * stroke, int minDegree, std::vector< double > & corners)
Enhanced version of Toonz detect corners.
{
  assert(stroke);
  if (!stroke) return false;
  assert(corners.empty());
  if (!corners.empty()) corners.clear();
  assert(0 <= minDegree && minDegree <= 180);
  minDegree = normalizeAngle(minDegree);
  const double minSin = degree2sin(minDegree), minCos = degree2cos(minDegree);
  assert(0.0 <= minSin && minSin <= 1.0);
  // first step remove chunks with null length
  const TThickQuadratic *quad1 = 0, *quad2 = 0;
  UINT chunkCount = stroke->getChunkCount();
  quad1 = stroke->getChunk(0);
  assert(quad1);
  if (!quad1) return false;
  bool error = false, check = false;
  std::set<double> internal_corners;
  double t;
  if (curveIsStraight(quad1, t)) {
    if (t != -1) {
      check = mapValueInStroke(stroke, quad1, t, t);
      assert(check);
      if (check) internal_corners.insert(t);
    }
  }
  for (UINT j = 1; j < chunkCount; j++) {
    quad2 = stroke->getChunk(j);
    if (curveIsStraight(quad2, t)) {
      if (t != -1) {
        check = mapValueInStroke(stroke, quad2, t, t);
        assert(check);
        if (check) internal_corners.insert(t);
      }
    }
    assert(quad2);
    if (!quad2) error = true;
    double tmp = stroke->getW(quad2->getP0());
    // jump zero length curves
    if (!isAlmostZero(quad1->getLength()) &&
        !isAlmostZero(quad2->getLength()) &&
        isThereACornerMinusThan(minCos, minSin, quad1, quad2))
      internal_corners.insert(tmp);
    if (!isAlmostZero(quad2->getLength())) quad1 = quad2;
  }
  if (stroke->isSelfLoop() && chunkCount > 0) {
    quad2 = stroke->getChunk(0);
    quad1 = stroke->getChunk(chunkCount - 1);
    if (isThereACornerMinusThan(minCos, minSin, quad1, quad2))
      internal_corners.insert(0.0);
  } else {
    internal_corners.insert(0.0);
    internal_corners.insert(1.0);
  }
  if (error) return false;
  std::copy(internal_corners.begin(), internal_corners.end(),
            std::back_inserter(corners));
#ifdef _DEBUG
  double temp = 0;
  for (unsigned int k = 0; k < corners.size(); ++k) {
    assert(corners[k] >= temp);
    temp = corners[k];
  }
#endif
  return !corners.empty();
}
Referenced by ToonzExt::CornerDeformation::check_().
detectSpireIntervals()
DVAPI bool ToonzExt::detectSpireIntervals (const TStroke * stroke, ToonzExt::Intervals & intervals, int minDegree)
Find intervals where stroke has limited from spire.
These intervals are stored in an vector od Interval.
{
  if (!ToonzExt::isValid(stroke)) return false;
  minDegree = normalizeAngle(minDegree);
  std::vector<double> corners;
  bool found = ToonzExt::cornersDetector(stroke, minDegree, corners);
  if (!found) return false;
  assert(!corners.empty());
  intervals.clear();
  double first = corners[0], last = first;
  int size = corners.size();
  for (int i = 1; i < size; ++i) {
    last = corners[i];
    intervals.push_back(ToonzExt::Interval(first, last));
    first = last;
  }
  // intervals.push_back( ToonzExt::Interval(last,1.0));
  if (stroke->isSelfLoop()) {
    if (corners.size() == 1) {
      double val = corners[0];
      intervals.push_back(ToonzExt::Interval(val, val));
    } else if (!intervals.empty()) {
      ToonzExt::Interval first = intervals.front(), last = intervals.back();
      intervals.insert(intervals.begin(),
                       ToonzExt::Interval(last.second, first.first));
    }
  }
  return !intervals.empty();
}
detectStraightIntervals()
DVAPI bool ToonzExt::detectStraightIntervals (const TStroke * stroke, ToonzExt::Intervals & intervals, double tolerance = TConsts::epsilon)
Find intervals where stroke is a straight line.
These intervals are stored in an vector od Interval.
{
  if (!ToonzExt::isValid(stroke)) return false;
  assert(tolerance > 0.0 && tolerance < 1.0 &&
         "Strange tolerance are you sure???");
  intervals.clear();
  // first step:
  //  store information about chunk and straight interval
  typedef std::pair<const TThickQuadratic *, ToonzExt::Intervals>
      ChunkStraights;
  std::map<int, ChunkStraights> arrayOfChunkIntervals;
  int chunkCount = stroke->getChunkCount();
  int counter    = 0;
  for (int i = 0; i < chunkCount; ++i) {
    ToonzExt::Intervals values;
    const TThickQuadratic *chunk = stroke->getChunk(i);
    if (chunk->getLength() == 0.0) continue;
    int howMany = detectStraightIntervals_(chunk, values, tolerance);
    if (howMany > 0) {
      arrayOfChunkIntervals[counter] = ChunkStraights(chunk, values);
    }
    ++counter;
  }
  // second step:
  //  add intervals vs stroke
  std::map<int, ChunkStraights>::iterator it = arrayOfChunkIntervals.begin(),
                                          end = arrayOfChunkIntervals.end(),
                                          aux;
  ToonzExt::Interval myRange = ToonzExt::Interval(-1, -1);
  for (; it != end; ++it) {
    aux = it;
    std::advance(aux, 1);
    ChunkStraights &cs1 = it->second;
    if (aux != end) {
      ChunkStraights &cs2 = aux->second;
      const int i1 = it->first, i2 = aux->first;
      // if chunk are a sequence
      if ((i1 + 1 == i2) && !corner(cs1.first, cs2.first, tolerance)) {
        const ToonzExt::Intervals &cs1Intervals = cs1.second;
        const int size = cs1Intervals.size();
        int i;
        ToonzExt::Interval tmp;
        for (i = 0; i < size; ++i) {
          tmp = cs1Intervals[i];
          if (tmp.second == 1.0) break;
          ToonzExt::Interval stroke_interval;
          if (mapIntervalInStroke(stroke, cs1.first, tmp, stroke_interval))
            intervals.push_back(stroke_interval);
        }
        // assert( i == size-1 );
        if (myRange.first == -1) {
          if (!mapValueInStroke(stroke, cs1.first, tmp.first, myRange.first))
            assert(!"Ops problemone!!!");
          // remove value added to merge
          //  adjacent straight interval
          cs1.second.pop_back();
        }
        tmp = cs2.second.front();
        if (!mapValueInStroke(stroke, cs2.first, tmp.second, myRange.second))
          assert(!"Ops problemone!!!");
        cs2.second.erase(cs2.second.begin());
      } else {
        if (myRange.first != -1 && myRange.second != -1) {
          intervals.push_back(myRange);
          myRange = ToonzExt::Interval(-1, -1);
        }
        // add remaining interval of current stroke
        addQuadraticIntervalInStroke(stroke, intervals, cs1.first, cs1.second);
      }
    } else {
      if (myRange.first != -1 && myRange.second != -1) {
        intervals.push_back(myRange);
        myRange = ToonzExt::Interval(-1, -1);
      }
      // add remaining interval of current stroke
      addQuadraticIntervalInStroke(stroke, intervals, cs1.first, cs1.second);
    }
  }
  if (stroke->isSelfLoop()) {
    TPointD v0 = stroke->getSpeed(0.0), vn = stroke->getSpeed(1.0);
    if (areParallel(v0, vn) && areInSameDirection(v0, vn) &&
        intervals.size() > 1) {
      // then first interval probably can be merged
      ToonzExt::Interval first = intervals.front(), last = intervals.back();
      if (first.first == 0.0 && last.second == 0.0) {
        intervals.pop_back();
        first.first  = last.first;
        intervals[0] = first;
      }
    }
  }
  return !intervals.empty();
}
findCorners()
DVAPI void ToonzExt::findCorners (const TStroke * stroke, ToonzExt::Intervals & corners, ToonzExt::Intervals & intervals, int angle, double tolerance)
Retrieve corners of a TStroke.
{
  assert(stroke && "Stroke is null!!!");
  if (!ToonzExt::isValid(stroke)) return;
  angle = normalizeAngle(angle);
  ToonzExt::detectSpireIntervals(stroke, corners, angle);
  // a corner SPIRE is also a STRAIGHT
  ToonzExt::detectStraightIntervals(stroke, intervals, tolerance);
}
findNearestCorners()
DVAPI bool ToonzExt::findNearestCorners (const TStroke * stroke, double w, ToonzExt::Interval & out, const Intervals & values, double tolerance = TConsts::epsilon)
Retrieve corners of a TStroke.
{
  out = ToonzExt::Interval(-1.0, -1.0);
  if (!ToonzExt::isValid(stroke) || !ToonzExt::isValid(w) || values.empty())
    return false;
  ToonzExt::Interval prev = values[0], curr = prev;
  if (!stroke->isSelfLoop() && areAlmostEqual(w, prev.first, tolerance)) {
    out = prev;
    return true;
  }
  const int size = values.size();
  for (int i = 1; i <= size; ++i) {
    if (i < size)
      curr = values[i];
    else
      curr = values[0];
    // this case, w is an extreme and needs to be considered
    //  the nearest external interval
    if (areAlmostEqual(w, curr.first, tolerance) &&
        (prev.second == curr.first)) {
      if (isWGood(prev.first, w, curr.second, stroke) ||
          (prev.first == curr.second)) {
        out.first  = prev.first;
        out.second = curr.second;
        return true;
      }
    }
    // normal case
    if (isWGood(curr.first, w, curr.second, stroke)) {
      out = curr;
      return true;
    }
    prev = curr;
  }
  curr = values.back();
  // last point
  if (!stroke->isSelfLoop() && areAlmostEqual(curr.second, w, tolerance)) {
    out = curr;
    return true;
  }
  return false;
}
findNearestSpireCorners()
DVAPI bool ToonzExt::findNearestSpireCorners (const TStroke * s, double actualW, ToonzExt::Interval & out, int cornerSize, const ToonzExt::Intervals *const cl = 0, double tolerance = TConsts::epsilon)
Retrieve parameters for corners near actualW parameter.
{
  if (!ToonzExt::isValid(stroke) || !ToonzExt::isValid(w)) return false;
  const ToonzExt::Intervals *values = cl;
  ToonzExt::Intervals tmpValues;
  if (!cl) {
    cornerSize = normalizeAngle(cornerSize);
    if (!ToonzExt::detectSpireIntervals(stroke, tmpValues, cornerSize))
      return false;
    values = &tmpValues;
  }
  if (!values || values->empty()) {
    return false;
  }
  return findNearestCorners(stroke, w, out, *values, tolerance);
}
Referenced by ToonzExt::CornerDeformation::findExtremes_(), ToonzExt::SmoothDeformation::findExtremes_(), and ToonzExt::StraightCornerDeformation::findExtremes_().
findNearestStraightCorners()
DVAPI bool ToonzExt::findNearestStraightCorners (const TStroke * s, double actualW, ToonzExt::Interval & out, const ToonzExt::Intervals *const cl = 0, double tolerance = TConsts::epsilon)
Retrieve parameters for straight intervals near actualW parameter.
Returns
If not found return [-1,-1] interval, else the correct interval.
{
  if (!stroke || w < 0.0 || w > 1.0) return false;
  const ToonzExt::Intervals *values = cl;
  ToonzExt::Intervals tmpValues;
  if (!cl) {
    if (!ToonzExt::detectStraightIntervals(stroke, tmpValues, tolerance))
      return false;
    values = &tmpValues;
  }
  if (!values || values->empty()) {
    return false;
  }
  return findNearestCorners(stroke, w, out, *values, tolerance);
}
Referenced by ToonzExt::StraightCornerDeformation::check_(), and ToonzExt::StraightCornerDeformation::findExtremes_().
getAllW()
DVAPI bool ToonzExt::getAllW (const TStroke * stroke, const TPointD & pnt, double & dist2, std::vector< double > & parameters)
Retrieve all parameters where stroke has a minimum.
{
  assert(!"To be finished!!!");
  std::set<double> tmp;
  assert(stroke);
  if (ToonzExt::isValid(stroke)) return false;
  double outT, w;
  const TThickQuadratic *tq = 0;
  int chunkFound = -1;
  double distance2;
  if (stroke->getNearestChunk(pnt, outT, chunkFound, distance2, false)) {
    dist2 = distance2;
    tq    = stroke->getChunk(chunkFound);
    if (tq) {
      w = stroke->getW(tq->getPoint(outT));
      if (ToonzExt::isValid(w)) tmp.insert(w);
    }
  }
  int i, chunkCount = stroke->getChunkCount();
  for (i = 0; i < chunkCount; i++) {
    if (i != chunkFound) {
      tq              = stroke->getChunk(i);
      TPointD tmp_pnt = tq->getPoint(tq->getT(pnt));
      if (areAlmostEqual(tdistance2(tmp_pnt, pnt), dist2)) {
        w = stroke->getW(tmp_pnt);
        if (ToonzExt::isValid(w)) tmp.insert(w);
      }
    }
  }
  std::copy(tmp.begin(), tmp.end(), std::back_inserter(parameters));
  return !tmp.empty();
}
isASpireCorner()
DVAPI bool ToonzExt::isASpireCorner (const TStroke * s, double w, int cornerSize, const ToonzExt::Intervals *const cl = 0, double tolerance = TConsts::epsilon)
{
  if (!ToonzExt::isValid(s) || !ToonzExt::isValid(w)) return false;
  ToonzExt::Intervals tmpValues;
  const ToonzExt::Intervals *values = cl;
  if (!cl) {
    if (!ToonzExt::detectSpireIntervals(s, tmpValues, cornerSize)) return false;
    values = &tmpValues;
  }
  if (!values || values->empty()) {
    return false;
  }
  return isCorner(*values, w, tolerance);
}
isAStraightCorner()
DVAPI bool ToonzExt::isAStraightCorner (const TStroke * s, double actualW, const ToonzExt::Intervals *const cl = 0, double tolerance = TConsts::epsilon)
{
  if (!ToonzExt::isValid(stroke) || !ToonzExt::isValid(w)) return false;
  ToonzExt::Intervals tmpValues;
  const ToonzExt::Intervals *values = cl;
  if (!cl) {
    if (!ToonzExt::detectStraightIntervals(stroke, tmpValues, tolerance))
      return false;
    values = &tmpValues;
  }
  if (!values || values->empty()) {
    return false;
  }
  return isCorner(*values, w, tolerance);
}
isValid() [1/2]
template<class T > bool ToonzExt::isValid (const T * s) inline
{
  assert(0 != s);
  if (!s) return false;
  return true;
}
isValid() [2/2]
bool ToonzExt::isValid (double w) inline
{
  assert(0.0 <= w && w <= 1.0);
  if (w < 0.0 || w > 1.0) return false;
  return true;
}
operator<<()
std::ostream & ToonzExt::operator<< (std::ostream & os, const Interval & interval) inline
{
  return os << '[' << interval.first << ',' << interval.second << ']';
}
replaceStroke()
DVAPI bool ToonzExt::replaceStroke (TStroke * old_stroke, TStroke * new_stroke, unsigned int n_, TVectorImageP & vi)
Replace a stroke in a vector image.
{
  if (!ToonzExt::isValid(old_stroke) || !ToonzExt::isValid(new_stroke) || !vi)
    return false;
  const unsigned int strokesCount = vi->getStrokeCount();
  assert(n_ <= strokesCount);
  if (n_ > strokesCount) return false;
  assert(vi->getStroke(n_) == old_stroke);
  if (vi->getStroke(n_) != old_stroke) return false;
  // stroke is replaced (old stroke is deleted)
  // in vector image
  vi->replaceStroke(n_, new_stroke);
  int new_id = getStrokeId(new_stroke, vi);
  if (new_id == -1) return false;
  n_ = new_id;
  return true;
}
rotateControlPoint()
TStroke * ToonzExt::rotateControlPoint (const TStroke * stroke, const ToonzExt::EvenInt & even, double atLength)
Rotate the control point at even position [0,2,4,...] in a new position along the close path of a selfLoop stroke.
The new position is: atLength.
Returns
0 if some problem occurs, else the new stroke.
Todo:
Some refactoring required, code duplication.
{
  if (!stroke || !stroke->isSelfLoop() || !evenControlPoint.isEven()) return 0;
#ifdef _DEBUG
  TThickPoint tp1 = stroke->getControlPoint(0);
  TThickPoint tp2 = stroke->getControlPoint(stroke->getControlPointCount() - 1);
#endif
  int controlPoint = (int)evenControlPoint;
  const double length = stroke->getLength();
  // invalid length
  if (0.0 > atLength || atLength > length) return 0;
  const int cpCountAtBegin = stroke->getControlPointCount();
  // invalid control point
  if (0 > controlPoint || controlPoint > cpCountAtBegin) return 0;
  // identity
  if ((controlPoint == 0 || controlPoint == (cpCountAtBegin - 1)) &&
      (areAlmostEqual(atLength, length) || isAlmostZero(atLength)))
    return new TStroke(*stroke);
  TStroke tmpStroke(*stroke);
  std::vector<TThickPoint> cp;
  {
    int count = stroke->getControlPointCount();
    for (int i = 0; i < count; ++i) {
      cp.push_back(stroke->getControlPoint(i));
    }
  }
  // add a control point where is necessary to have rotation (head_queue cp)
  tmpStroke.insertControlPointsAtLength(atLength);
#ifdef _DEBUG
  {
    int count  = stroke->getControlPointCount(),
        count2 = tmpStroke.getControlPointCount();
    int i, firstDifference = -1;
    for (i = 0; i < count; ++i) {
      if ((tp1 = stroke->getControlPoint(i)) !=
          (tp2 = tmpStroke.getControlPoint(i))) {
        firstDifference = i;
        break;
      }
    }
    for (i = 0; i < count; ++i) {
      if (i < firstDifference)
        assert((tp1 = stroke->getControlPoint(i)) ==
               (tp2 = tmpStroke.getControlPoint(i)));
      else {
        //        assert( (tp1=stroke->getControlPoint(i)) ==
        //                (tp2=tmpStroke.getControlPoint(i+2)));
      }
      tp1 = stroke->getControlPoint(i);
      tp2 = tmpStroke.getControlPoint(i);
    }
  }
#endif
  const int cpCount = tmpStroke.getControlPointCount();
  double w = tmpStroke.getParameterAtLength(atLength);
  double butta = tmpStroke.getLength(w);
  assert(areAlmostEqual(butta, atLength));
  // retrieve head_queue control point
  TThickPoint head_queue = tmpStroke.getControlPointAtParameter(w);
  // recover index
  int i;
  for (i = 0; i < cpCount; ++i) {
    if (head_queue == tmpStroke.getControlPoint(i)) break;
  }
  const int head_index = i;
  // uhmmm really strange
  if (head_index == cpCount) {
    assert(!"Error on procedure!!! Not control point found!!!"
                " Wrong insert control point!!!");
    return 0;
  }
  // head_index is the new head of stroke
  std::vector<TThickPoint> new_stroke_cp;
  for (i = head_index; i < cpCount; ++i) {
    TThickPoint to_add = tmpStroke.getControlPoint(i);
    new_stroke_cp.push_back(to_add);
  }
  TThickPoint tmpCP = tmpStroke.getControlPoint(0);
  bool check = areAlmostEqual(new_stroke_cp.back(), tmpCP, 0.01);
  // relaxed check
  assert(check);
  if (!check) {
    assert(!"Error on procedure!!! Please verify algorithm!!!");
    return 0;
  }
  // 0 position is already inserted
  for (i = 1; i < head_index; ++i) {
    TThickPoint to_add = tmpStroke.getControlPoint(i);
    new_stroke_cp.push_back(to_add);
  }
  // now add queue == head cp
  new_stroke_cp.push_back(new_stroke_cp[0]);
  assert((int)new_stroke_cp.size() == cpCount);
  if (new_stroke_cp.back() != tmpStroke.getControlPoint(head_index)) {
    assert(!"Error on procedure!!! Please verify algorithm!!!");
    return 0;
  }
  TStroke *out = new TStroke(new_stroke_cp);
  out->setSelfLoop();
  return out;
}
References TStroke::getControlPoint(), TStroke::getControlPointAtParameter(), TStroke::getControlPointCount(), TStroke::getLength(), TStroke::getParameterAtLength(), TStroke::insertControlPointsAtLength(), ToonzExt::EvenInt::isEven(), TStroke::isSelfLoop(), and TStroke::setSelfLoop().
straightCornersDetector()
DVAPI bool ToonzExt::straightCornersDetector (const TStroke * stroke, std::vector< double > & corners)
Like cornersDetector but for straight corners.
{
  ToonzExt::Intervals intervals;
  assert(corners.empty());
  if (!corners.empty()) corners.clear();
  if (!ToonzExt::detectStraightIntervals(stroke, intervals)) return false;
  assert(!intervals.empty() && "Intervals are empty!!!");
  if (intervals.empty()) return false;
  double first;
  ToonzExt::Interval prev = intervals[0], curr;
  if (stroke->isSelfLoop()) first = prev.first;
  int size = intervals.size();
  for (int i = 1; i < size; ++i) {
    curr = intervals[i];
    if (prev.second == curr.first) corners.push_back(curr.first);
    prev = curr;
  }
  if (stroke->isSelfLoop() && curr.second == first) corners.push_back(first);
  return !corners.empty();
}