opentoonz: E:/opentoonz/toonz/sources/include/tcg/boost/range_utility.h File Reference
range_utility.h File Reference
Contains utilities to be used with Boost.Range objects.
#include <boost/range.hpp>
Functions
template<typename C , typename Rng >
C & tcg::substitute (C &c, const Rng &rng)
Substitutes a container's content with the one inside a Boost range.
template<typename C , typename Rng >
C & tcg::insert2 (C &c, const Rng &rng)
Inserts a range inside an associative container.
Detailed Description
Contains utilities to be used with Boost.Range objects.
Definition in file range_utility.h.
Macro Definition Documentation
TCG_BOOST_RANGE_UTILITY_H
#define TCG_BOOST_RANGE_UTILITY_H
Function Documentation
insert2()
template<typename C , typename Rng > C & tcg::insert2 (C & c, const Rng & rng)
Inserts a range inside an associative container.
The container type requires an insert() method accepting a pair of iterators.
Note
For insertion in a sequential container, use boost::insert.
{
  c.insert(boost::begin(rng), boost::end(rng));
  return c;
}
References tcg::insert2().
Referenced by tcg::insert2().
substitute()
template<typename C , typename Rng > C & tcg::substitute (C & c, const Rng & rng)
Substitutes a container's content with the one inside a Boost range.
The container type requires construction with an iterator pair and the swap() method.
{
  C(boost::begin(rng), boost::end(rng)).swap(c);
  return c;
}
References tcg::substitute().
Referenced by tcg::substitute().