opentoonz: PlasticSkeletonVertex Struct Reference
PlasticSkeletonVertex Struct Reference final
PlasticSkeletonVertex is the vertex of a plastic skeleton object.
#include <plasticskeleton.h>
Public Member Functions
PlasticSkeletonVertex (const TPointD &pos)
operator PlasticHandle () const
operator TPointD () const
const QString & name () const
int number () const
int parent () const
void saveData (TOStream &os) override
void loadData (TIStream &is) override
Public Member Functions inherited from tcg::Vertex< TPointD >
Vertex (const point_type &p)
void setIndex (int idx)
int getIndex () const
const tcg::list< int > & edges () const
tcg::list< int > & edges ()
int edgesCount () const
int edge (int e) const
void addEdge (int e)
edges_iterator eraseEdge (edges_iterator it)
edges_const_iterator edgesBegin () const
edges_iterator edgesBegin ()
edges_const_iterator edgesEnd () const
edges_iterator edgesEnd ()
void setP (const point_type &p)
const point_type & P () const
point_type & P ()
bool operator== (const Vertex &v) const
bool operator!= (const Vertex &v) const
Public Member Functions inherited from TPersist
virtual void loadData (TIStream &is)=0
virtual void saveData (TOStream &os)=0
std::string getStreamTag () const
virtual const TPersistDeclaration * getDeclaration () const =0
Public Attributes
double m_minAngle
double m_maxAngle
position with the mouse. In degrees.
bool m_interpolate
Friends
class PlasticSkeleton
Additional Inherited Members
Public Types inherited from tcg::Vertex< TPointD >
typedef TPointD point_type
typedef tcg::list< int >::const_iterator edges_const_iterator
typedef tcg::list< int >::iterator edges_iterator
Public Types inherited from TPersist
typedef TPersist * CreateProc()
Static Public Member Functions inherited from TPersist
static void declare (CreateProc *)
static TPersist * create (const std::string &name)
Protected Attributes inherited from tcg::Vertex< TPointD >
TPointD m_p
int m_index
tcg::list< int > m_edgeList
Detailed Description
PlasticSkeletonVertex is the vertex of a plastic skeleton object.
Constructor & Destructor Documentation
PlasticSkeletonVertex() [1/2]
PlasticSkeletonVertex::PlasticSkeletonVertex ()
    : tcg::Vertex<TPointD>()
    , m_number(-1)
    , m_parent(-1)
    , m_minAngle(-(std::numeric_limits<double>::max)())
    , m_maxAngle((std::numeric_limits<double>::max)())
    , m_interpolate(true) {}
PlasticSkeletonVertex() [2/2]
PlasticSkeletonVertex::PlasticSkeletonVertex (const TPointD & pos) explicit
    : tcg::Vertex<TPointD>(pos)
    , m_number(-1)
    , m_parent(-1)
    , m_minAngle(-(std::numeric_limits<double>::max)())
    , m_maxAngle((std::numeric_limits<double>::max)())
    , m_interpolate(true) {}
Member Function Documentation
loadData()
void PlasticSkeletonVertex::loadData (TIStream & is) override virtual
 This is a pure virtual function and must be overridden with a method
that implements the object loading from a stream (i.e take the object's features from a formatted data stream). For example the TStageObject class use his implementation to take the values of the parameters that characterizes a stage object as name, coordinates, etc... from a file. is is an input file stream
Implements TPersist.
{
  int val;
  std::string tagName;
  while (is.openChild(tagName)) {
    if (tagName == "name")
      is >> m_name, is.matchEndTag();
    else if (tagName == "number")
      is >> m_number, is.matchEndTag();
    else if (tagName == "pos")
      is >> this->P().x >> this->P().y, is.matchEndTag();
    else if (tagName == "interpolate")
      is >> val, m_interpolate = (bool)val, is.matchEndTag();
    else if (tagName == "minAngle")
      is >> m_minAngle, is.matchEndTag();
    else if (tagName == "maxAngle")
      is >> m_maxAngle, is.matchEndTag();
    else
      is.skipCurrentTag();
  }
}
References m_interpolate, m_maxAngle, TIStream::matchEndTag(), TIStream::openChild(), and TIStream::skipCurrentTag().
name()
const QString & PlasticSkeletonVertex::name () const inline
{ return m_name; }
number()
int PlasticSkeletonVertex::number () const inline
{ return m_number; }  // Should be removed
operator PlasticHandle()
PlasticSkeletonVertex::operator PlasticHandle () const
{
  PlasticHandle result(P());
  result.m_interpolate = m_interpolate;
  return result;
}
operator TPointD()
PlasticSkeletonVertex::operator TPointD () const inline
{ return P(); }
parent()
int PlasticSkeletonVertex::parent () const inline
{ return m_parent; }
saveData()
void PlasticSkeletonVertex::saveData (TOStream & os) override virtual
 This is a pure virtual function and must be overridden with a method
that implements the object saving to a data stream (i.e put the object's features on a formatted data stream). For example the TStageObject class use his implementation to save the values of the parameters that characterizes a stage object as name, coordinates, etc... on a file os is an output file stream.
Implements TPersist.
{
  os.child("name") << m_name;
  os.child("number") << m_number;
  os.child("pos") << this->P().x << this->P().y;
  os.child("interpolate") << (int)this->m_interpolate;
  if (m_minAngle != -(std::numeric_limits<double>::max)())
    os.child("minAngle") << m_minAngle;
  if (m_maxAngle != (std::numeric_limits<double>::max)())
    os.child("maxAngle") << m_maxAngle;
}
References TOStream::child(), m_interpolate, and m_maxAngle.
Friends And Related Function Documentation
PlasticSkeleton
friend class PlasticSkeleton friend
Member Data Documentation
m_interpolate
bool PlasticSkeletonVertex::m_interpolate
Whether the vertex needs to be interpolated (see plasticdeformer.h)
Referenced by loadData(), and saveData().
m_maxAngle
double PlasticSkeletonVertex::m_maxAngle
position with the mouse. In degrees.
Minimum and maximum accepted angles when updating the vertex
Referenced by loadData(), PlasticTool::onPropertyChanged(), and saveData().
m_minAngle
double PlasticSkeletonVertex::m_minAngle
The documentation for this struct was generated from the following files:
E:/opentoonz/toonz/sources/include/ext/plasticskeleton.h
E:/opentoonz/toonz/sources/tnzext/plasticskeleton.cpp