opentoonz: BrushData Struct Reference
BrushData Struct Reference final
Public Member Functions
BrushData (const std::wstring &name)
bool operator< (const BrushData &other) const
void saveData (TOStream &os) override
void loadData (TIStream &is) override
Public Member Functions inherited from TPersist
virtual void loadData (TIStream &is)=0
virtual void saveData (TOStream &os)=0
std::string getStreamTag () const
virtual const TPersistDeclaration * getDeclaration () const =0
Public Attributes
std::wstring m_name
double m_min
double m_max
double m_smooth
double m_hardness
double m_opacityMin
double m_opacityMax
bool m_pencil
bool m_pressure
int m_drawOrder
double m_modifierSize
double m_modifierOpacity
bool m_modifierEraser
bool m_modifierLockAlpha
Additional Inherited Members
Public Types inherited from TPersist
typedef TPersist * CreateProc()
Static Public Member Functions inherited from TPersist
static void declare (CreateProc *)
static TPersist * create (const std::string &name)
Detailed Description
Constructor & Destructor Documentation
BrushData() [1/2]
BrushData::BrushData ()
    : m_name()
    , m_min(0.0)
    , m_max(0.0)
    , m_smooth(0.0)
    , m_hardness(0.0)
    , m_opacityMin(0.0)
    , m_opacityMax(0.0)
    , m_drawOrder(0)
    , m_pencil(false)
    , m_pressure(false)
    , m_modifierSize(0.0)
    , m_modifierOpacity(0.0)
    , m_modifierEraser(0.0)
    , m_modifierLockAlpha(0.0) {}
BrushData() [2/2]
BrushData::BrushData (const std::wstring & name)
    : m_name(name)
    , m_min(0.0)
    , m_max(0.0)
    , m_smooth(0.0)
    , m_hardness(0.0)
    , m_opacityMin(0.0)
    , m_opacityMax(0.0)
    , m_drawOrder(0)
    , m_pencil(false)
    , m_pressure(false)
    , m_modifierSize(0.0)
    , m_modifierOpacity(0.0)
    , m_modifierEraser(0.0)
    , m_modifierLockAlpha(0.0) {}
Member Function Documentation
loadData()
void BrushData::loadData (TIStream & is) override virtual
 This is a pure virtual function and must be overridden with a method
that implements the object loading from a stream (i.e take the object's features from a formatted data stream). For example the TStageObject class use his implementation to take the values of the parameters that characterizes a stage object as name, coordinates, etc... from a file. is is an input file stream
Implements TPersist.
{
  std::string tagName;
  int val;
  while (is.matchTag(tagName)) {
    if (tagName == "Name")
      is >> m_name, is.matchEndTag();
    else if (tagName == "Thickness")
      is >> m_min >> m_max, is.matchEndTag();
    else if (tagName == "Smooth")
      is >> m_smooth, is.matchEndTag();
    else if (tagName == "Hardness")
      is >> m_hardness, is.matchEndTag();
    else if (tagName == "Opacity")
      is >> m_opacityMin >> m_opacityMax, is.matchEndTag();
    else if (tagName == "Selective" ||
             tagName == "Draw_Order")  // "Selective" is left to keep backward
                                       // compatibility
      is >> m_drawOrder, is.matchEndTag();
    else if (tagName == "Pencil")
      is >> val, m_pencil = val, is.matchEndTag();
    else if (tagName == "Pressure_Sensitivity")
      is >> val, m_pressure = val, is.matchEndTag();
    else if (tagName == "Modifier_Size")
      is >> m_modifierSize, is.matchEndTag();
    else if (tagName == "Modifier_Opacity")
      is >> m_modifierOpacity, is.matchEndTag();
    else if (tagName == "Modifier_Eraser")
      is >> val, m_modifierEraser = val, is.matchEndTag();
    else if (tagName == "Modifier_LockAlpha")
      is >> val, m_modifierLockAlpha = val, is.matchEndTag();
    else
      is.skipCurrentTag();
  }
}
References TIStream::matchEndTag(), TIStream::matchTag(), and TIStream::skipCurrentTag().
operator<()
bool BrushData::operator< (const BrushData & other) const inline
{ return m_name < other.m_name; }
saveData()
void BrushData::saveData (TOStream & os) override virtual
 This is a pure virtual function and must be overridden with a method
that implements the object saving to a data stream (i.e put the object's features on a formatted data stream). For example the TStageObject class use his implementation to save the values of the parameters that characterizes a stage object as name, coordinates, etc... on a file os is an output file stream.
Implements TPersist.
{
  os.openChild("Name");
  os << m_name;
  os.closeChild();
  os.openChild("Thickness");
  os << m_min << m_max;
  os.closeChild();
  os.openChild("Smooth");
  os << m_smooth;
  os.closeChild();
  os.openChild("Hardness");
  os << m_hardness;
  os.closeChild();
  os.openChild("Opacity");
  os << m_opacityMin << m_opacityMax;
  os.closeChild();
  os.openChild("Draw_Order");
  os << m_drawOrder;
  os.closeChild();
  os.openChild("Pencil");
  os << (int)m_pencil;
  os.closeChild();
  os.openChild("Pressure_Sensitivity");
  os << (int)m_pressure;
  os.closeChild();
  os.openChild("Modifier_Size");
  os << m_modifierSize;
  os.closeChild();
  os.openChild("Modifier_Opacity");
  os << m_modifierOpacity;
  os.closeChild();
  os.openChild("Modifier_Eraser");
  os << (int)m_modifierEraser;
  os.closeChild();
  os.openChild("Modifier_LockAlpha");
  os << (int)m_modifierLockAlpha;
  os.closeChild();
}
References TOStream::closeChild(), and TOStream::openChild().
Member Data Documentation
m_drawOrder
int BrushData::m_drawOrder
m_hardness
double BrushData::m_hardness
m_max
double BrushData::m_max
m_min
double BrushData::m_min
m_modifierEraser
bool BrushData::m_modifierEraser
m_modifierLockAlpha
bool BrushData::m_modifierLockAlpha
m_modifierOpacity
double BrushData::m_modifierOpacity
m_modifierSize
double BrushData::m_modifierSize
m_name
std::wstring BrushData::m_name
m_opacityMax
double BrushData::m_opacityMax
m_opacityMin
double BrushData::m_opacityMin
m_pencil
bool BrushData::m_pencil
m_pressure
bool BrushData::m_pressure
m_smooth
double BrushData::m_smooth
The documentation for this struct was generated from the following files:
E:/opentoonz/toonz/sources/tnztools/toonzrasterbrushtool.h
E:/opentoonz/toonz/sources/tnztools/toonzrasterbrushtool.cpp