opentoonz: VectorBrushData Struct Reference
VectorBrushData Struct Reference final
Public Member Functions
VectorBrushData (const std::wstring &name)
bool operator< (const VectorBrushData &other) const
void saveData (TOStream &os) override
void loadData (TIStream &is) override
Public Member Functions inherited from TPersist
virtual void loadData (TIStream &is)=0
virtual void saveData (TOStream &os)=0
std::string getStreamTag () const
virtual const TPersistDeclaration * getDeclaration () const =0
Public Attributes
std::wstring m_name
double m_min
double m_max
double m_acc
double m_smooth
bool m_breakAngles
bool m_pressure
int m_cap
int m_join
int m_miter
Additional Inherited Members
Public Types inherited from TPersist
typedef TPersist * CreateProc()
Static Public Member Functions inherited from TPersist
static void declare (CreateProc *)
static TPersist * create (const std::string &name)
Detailed Description
Constructor & Destructor Documentation
VectorBrushData() [1/2]
VectorBrushData::VectorBrushData ()
    : m_name()
    , m_min(0.0)
    , m_max(0.0)
    , m_acc(0.0)
    , m_smooth(0.0)
    , m_breakAngles(false)
    , m_pressure(false)
    , m_cap(0)
    , m_join(0)
    , m_miter(0) {}
VectorBrushData() [2/2]
VectorBrushData::VectorBrushData (const std::wstring & name)
    : m_name(name)
    , m_min(0.0)
    , m_max(0.0)
    , m_acc(0.0)
    , m_smooth(0.0)
    , m_breakAngles(false)
    , m_pressure(false)
    , m_cap(0)
    , m_join(0)
    , m_miter(0) {}
Member Function Documentation
loadData()
void VectorBrushData::loadData (TIStream & is) override virtual
 This is a pure virtual function and must be overridden with a method
that implements the object loading from a stream (i.e take the object's features from a formatted data stream). For example the TStageObject class use his implementation to take the values of the parameters that characterizes a stage object as name, coordinates, etc... from a file. is is an input file stream
Implements TPersist.
{
  std::string tagName;
  int val;
  while (is.matchTag(tagName)) {
    if (tagName == "Name")
      is >> m_name, is.matchEndTag();
    else if (tagName == "Thickness")
      is >> m_min >> m_max, is.matchEndTag();
    else if (tagName == "Accuracy")
      is >> m_acc, is.matchEndTag();
    else if (tagName == "Smooth")
      is >> m_smooth, is.matchEndTag();
    else if (tagName == "Break_Sharp_Angles")
      is >> val, m_breakAngles = val, is.matchEndTag();
    else if (tagName == "Pressure_Sensitivity")
      is >> val, m_pressure = val, is.matchEndTag();
    else if (tagName == "Cap")
      is >> m_cap, is.matchEndTag();
    else if (tagName == "Join")
      is >> m_join, is.matchEndTag();
    else if (tagName == "Miter")
      is >> m_miter, is.matchEndTag();
    else
      is.skipCurrentTag();
  }
}
References TIStream::matchEndTag(), TIStream::matchTag(), and TIStream::skipCurrentTag().
operator<()
bool VectorBrushData::operator< (const VectorBrushData & other) const inline
{
    return m_name < other.m_name;
  }
saveData()
void VectorBrushData::saveData (TOStream & os) override virtual
 This is a pure virtual function and must be overridden with a method
that implements the object saving to a data stream (i.e put the object's features on a formatted data stream). For example the TStageObject class use his implementation to save the values of the parameters that characterizes a stage object as name, coordinates, etc... on a file os is an output file stream.
Implements TPersist.
{
  os.openChild("Name");
  os << m_name;
  os.closeChild();
  os.openChild("Thickness");
  os << m_min << m_max;
  os.closeChild();
  os.openChild("Accuracy");
  os << m_acc;
  os.closeChild();
  os.openChild("Smooth");
  os << m_smooth;
  os.closeChild();
  os.openChild("Break_Sharp_Angles");
  os << (int)m_breakAngles;
  os.closeChild();
  os.openChild("Pressure_Sensitivity");
  os << (int)m_pressure;
  os.closeChild();
  os.openChild("Cap");
  os << m_cap;
  os.closeChild();
  os.openChild("Join");
  os << m_join;
  os.closeChild();
  os.openChild("Miter");
  os << m_miter;
  os.closeChild();
}
References TOStream::closeChild(), and TOStream::openChild().
Member Data Documentation
m_acc
double VectorBrushData::m_acc
m_breakAngles
bool VectorBrushData::m_breakAngles
m_cap
int VectorBrushData::m_cap
m_join
int VectorBrushData::m_join
m_max
double VectorBrushData::m_max
m_min
double VectorBrushData::m_min
m_miter
int VectorBrushData::m_miter
m_name
std::wstring VectorBrushData::m_name
m_pressure
bool VectorBrushData::m_pressure
m_smooth
double VectorBrushData::m_smooth
The documentation for this struct was generated from the following files:
E:/opentoonz/toonz/sources/tnztools/toonzvectorbrushtool.h
E:/opentoonz/toonz/sources/tnztools/toonzvectorbrushtool.cpp