opentoonz: TStroke::Imp Struct Reference
TStroke::Imp Struct Reference
Public Member Functions
Imp (const vector< TPointD > &v)
Imp (const vector< TThickPoint > &v)
void init ()
double getW (int index)
TRectD computeCenterlineBBox ()
void computeMaxThickness ()
TRectD computeSubBBox (double w0, double w1) const
QuadStrokeChunkArray & getTQArray ()
void swapGeometry (TStroke::Imp &other) throw ()
void computeCacheVector ()
compute cache vector
void computeParameterInControlPoint ()
void updateParameterValue (double w, UINT chunk, TThickQuadratic *tq1, TThickQuadratic *tq2)
bool retrieveChunkAndItsParamameter (double w, int &chunk, double &t)
bool retrieveChunkAndItsParamameterAtLength (double s, int &chunk, double &t)
int retrieveChunkFromControlPointIndex (int n)
DoublePair retrieveParametersFromChunk (UINT chunk)
void print (ostream &os)
int getChunkCount () const
int getControlPointCount () const
TThickQuadratic * getChunk (int index)
Public Attributes
BYTE m_flag
bool m_isValidLength
bool m_isOutlineValid
bool m_areDisabledComputeOfCaches
Control calculus of cache vector.
TRectD m_bBox
Bounding Box of a stroke.
DoubleArray m_partialLengthArray
This vector contains length computed for each control point of stroke.
DoubleArray m_parameterValueAtControlPoint
This vector contains parameter computed for each control point of stroke.
QuadStrokeChunkArray m_centerLineArray
This vector contains outline of stroke.
bool m_selfLoop
int m_negativeThicknessPoints
double m_averageThickness
double m_maxThickness
int m_id
int m_styleId
TStrokeProp * m_prop
TStroke::OutlineOptions m_outlineOptions
Detailed Description
Constructor & Destructor Documentation
Imp() [1/3]
TStroke::Imp::Imp ()
{ init(); }
Imp() [2/3]
TStroke::Imp::Imp (const vector< TPointD > & v)
{
  buildChunksFromControlPoints(m_centerLineArray, v);
  roundNegativeThickess(m_centerLineArray);
  init();
}
Imp() [3/3]
TStroke::Imp::Imp (const vector< TThickPoint > & v)
{
  buildChunksFromControlPoints(m_centerLineArray, v);
  roundNegativeThickess(m_centerLineArray);
  init();
}
~Imp()
TStroke::Imp::~Imp () inline
         {
    delete m_prop;
    clearPointerContainer(m_centerLineArray);
    // delete m_style;
  }
Member Function Documentation
computeCacheVector()
void TStroke::Imp::computeCacheVector ()
compute cache vector
{
  // se la stroke e' stata invalidata a causa dell'inserimento di punti
  //  di controllo o dal ricampionamento
  if (!m_areDisabledComputeOfCaches && !m_isValidLength) {
    if (getChunkCount() > 0)  // se ci sono cionchi
    {
      // (re)inizializzo un vettore
      m_partialLengthArray.resize(getControlPointCount(),
                                  (std::numeric_limits<double>::max)());
      m_partialLengthArray[0] = 0.0;
      double length = 0.0;
      int j         = 0;
      const TThickQuadratic *tq;
      TQuadraticLengthEvaluator lengthEvaluator;
      for (int i = 0; i < getChunkCount(); ++i) {
        assert(j <= getControlPointCount());
        tq = getChunk(i);
        lengthEvaluator.setQuad(*tq);
        m_partialLengthArray[j++] = length;
        m_partialLengthArray[j++] = length + lengthEvaluator.getLengthAt(0.5);
        length += lengthEvaluator.getLengthAt(1.0);
      }
      m_partialLengthArray[j++] = length;
      assert(j == getControlPointCount());
      // assert( m_parameterValueAtControlPoint.size() ==
      // m_partialLengthArray.size() );
    }
    m_isValidLength = true;
  }
}
References TStroke::getChunk(), TStroke::getChunkCount(), and TStroke::getControlPointCount().
computeCenterlineBBox()
TRectD TStroke::Imp::computeCenterlineBBox ()
{
  UINT n = m_centerLineArray.size();
  if (m_centerLineArray.empty()) return TRectD();
  TQuadratic q(m_centerLineArray[0]->getP0(), m_centerLineArray[0]->getP1(),
               m_centerLineArray[0]->getP2());
  TRectD bbox = q.getBBox();
  for (UINT i = 1; i < n; i++) {
    q = TQuadratic(m_centerLineArray[i]->getP0(), m_centerLineArray[i]->getP1(),
                   m_centerLineArray[i]->getP2());
    bbox += q.getBBox();
  }
  return bbox;
}
computeMaxThickness()
void TStroke::Imp::computeMaxThickness ()
It computes the bounding box of the subStroke in the parameter range w0-w1.
{
  m_maxThickness = m_centerLineArray[0]->getThickP0().thick;
  for (UINT i = 0; i < m_centerLineArray.size(); i++)
    m_maxThickness =
        std::max({m_maxThickness, m_centerLineArray[i]->getThickP1().thick,
                  m_centerLineArray[i]->getThickP2().thick});
}
computeParameterInControlPoint()
void TStroke::Imp::computeParameterInControlPoint ()
Set value in m_parameterValueAtControlPoint
{
  if (!m_areDisabledComputeOfCaches) {
    // questa funzione ricalcola i valori dei parametri nei cionchi
    //  N.B. deve essere richiamata quando si effettuano inserimenti
    //    di punti di controllo che cambiano la lunghezza della curva
    //  insert, push e costruttore
    if (!getChunkCount()) {
      m_parameterValueAtControlPoint.clear();
      return;
    }
    int controlPointCount = getControlPointCount();
    m_parameterValueAtControlPoint.resize(controlPointCount, 0);
    // N.B. number of control point is reduced of 1
    --controlPointCount;
    double val = 0.0;
    assert(controlPointCount >= 0.0);
    for (int i = 0; i <= controlPointCount; ++i) {
      val                               = i / (double)controlPointCount;
      m_parameterValueAtControlPoint[i] = val;
    }
  }
}
References TStroke::getChunkCount(), and TStroke::getControlPointCount().
Referenced by init().
computeSubBBox()
TRectD TStroke::Imp::computeSubBBox (double w0, double w1) const
{
  if (m_centerLineArray.empty()) return TRectD();
  int n = m_centerLineArray.size();
  TRectD bBox;
  const double eps = 0.000000001;
  int i;
  if (w0 > w1) std::swap(w0, w1);
  double nw0 = w0 * n;
  double nw1 = w1 * n;
  int i0 = (int)nw0;  // indice della quadrica che contiene w0
  int i1 = (int)nw1;  // idem per w1
  double t0 =
      nw0 -
      (double)i0;  // parametro di w0 rispetto alla quadrica che lo contiene
  double t1 = nw1 - (double)i1;  // idem per w1
  if (t0 < eps)  // se t0 e' quasi uguale a zero, evito di fare lo split e
                 // considero tutta la quadrica i0
  {
    i0--;
    t0 = 1.0;
  }
  if (t1 > (1 - eps))  // se t1 e' quasi uguale a uno, evito di fare lo split e
                       // considero tutta la quadrica i1
  {
    i1++;
    t1 = 0.0;
  }
  TThickQuadratic quadratic1, quadratic2, quadratic3;
  if (i0 == i1)  // i due punti di taglio capitano nella stessa quadratica
  {
    if (t0 < eps && t1 > (1 - eps)) return m_centerLineArray[i0]->getBBox();
    if (t0 < eps) {
      m_centerLineArray[i0]->split(t1, quadratic1, quadratic2);
      return quadratic1.getBBox();
    }
    if (t1 > (1 - eps)) {
      m_centerLineArray[i0]->split(t0, quadratic1, quadratic2);
      return quadratic2.getBBox();
    }
    // quadratic1 e' la quadratica risultante dallo split tra t0 e t1 di
    // m_centerLineArray[i0]
    m_centerLineArray[i0]->split(t0, quadratic1, quadratic2);
    quadratic2.split((t1 - t0) / (1 - t0), quadratic1, quadratic3);
    return quadratic1.getBBox();
  }
  // se i due punti di taglio capitano in quadratiche diverse
  // sommo le bbox di quelle interne
  for (i = i0 + 1; i < i1; i++) bBox += m_centerLineArray[i]->getBBox();
  // e sommo le bbox delle quadratiche splittate agli estremi se non sono
  // irrilevanti
  if (i0 >= 0 && t0 < (1 - eps)) {
    m_centerLineArray[i0]->split(t0, quadratic1, quadratic2);
    bBox += quadratic2.getBBox();
  }
  if (i1 < n && t1 > eps) {
    m_centerLineArray[i1]->split(t1, quadratic1, quadratic2);
    bBox += quadratic1.getBBox();
  }
  return bBox;
}
getChunk()
TThickQuadratic * TStroke::Imp::getChunk (int index) inline
{
    if (0 <= index && index < getChunkCount()) return m_centerLineArray[index];
    return 0;
  }
getChunkCount()
int TStroke::Imp::getChunkCount () const inline
{ return m_centerLineArray.size(); }
getControlPointCount()
int TStroke::Imp::getControlPointCount () const inline
{
    UINT out = 2 * getChunkCount() + 1;
    return out;
  }
getTQArray()
QuadStrokeChunkArray & TStroke::Imp::getTQArray () inline
{ return m_centerLineArray; }
getW()
double TStroke::Imp::getW (int index) inline
{
    return ((int)m_parameterValueAtControlPoint.size() > index)
               ? m_parameterValueAtControlPoint[index]
               : m_parameterValueAtControlPoint.back();
  }
init()
void TStroke::Imp::init ()
init() is required to initialize all variable Call init after centerline initialization, because it's necessary to compute BBox
                      {
  m_flag = c_dirty_flag;
  m_styleId = 1;  // DefaultStrokeStyle;
  m_prop    = 0;
  m_id                         = ++maxStrokeId;
  m_isValidLength              = false;
  m_isOutlineValid             = false;
  m_areDisabledComputeOfCaches = false;
  m_selfLoop                   = false;
  m_averageThickness           = 0;
  m_maxThickness               = -1;
  m_negativeThicknessPoints    = 0;
  for (UINT j = 0; j < m_centerLineArray.size(); j++) {
    if (m_centerLineArray[j]->getThickP0().thick <= 0)
      m_negativeThicknessPoints++;
    if (m_centerLineArray[j]->getThickP1().thick <= 0)
      m_negativeThicknessPoints++;
  }
  if (!m_centerLineArray.empty() &&
      m_centerLineArray.back()->getThickP2().thick <= 0)
    m_negativeThicknessPoints++;
  computeParameterInControlPoint();
}
References computeParameterInControlPoint(), m_areDisabledComputeOfCaches, m_centerLineArray, m_isOutlineValid, and m_isValidLength.
print()
void TStroke::Imp::print (ostream & os)
{
#if defined(_DEBUG) || defined(DEBUG)
  os << "m_isValidLength:" << m_isValidLength << endl;
  os << "m_isOutlineValid:" << m_isOutlineValid << endl;
  os << "m_areDisabledComputeOfCaches:" << m_areDisabledComputeOfCaches << endl;
  os << "m_bBox:" << m_bBox << endl;
  os << "m_partialLengthArray";
  printContainer(os, m_partialLengthArray);
  os << endl;
  os << "m_parameterValueAtControlPoint";
  printContainer(os, m_parameterValueAtControlPoint);
  os << endl;
  os << "m_centerLineArray";
  // os.setf(myIOFlags::scientific);
  printContainerOfPointer(os, m_centerLineArray);
  os << endl;
/*
  vector<TPixel> m_outlineColorArray;
    vector<TPointD> m_texArray;
      TFilePath m_filePath;
      TRasterP  m_texture;
  */
// TSystem::outputDebug(os.str());
#else
#endif
}
retrieveChunkAndItsParamameter()
bool TStroke::Imp::retrieveChunkAndItsParamameter (double w, int & chunk, double & t)
From parameter w retrieves chunk and its parameter (t in [0,1]). Return true -> error (parameter w out of range, etc) false -> ok
{
  vector<double>::iterator first;
  // trova l'iteratore alla prima posizione che risulta maggiore o uguale a w
  first = std::lower_bound(m_parameterValueAtControlPoint.begin(),
                           m_parameterValueAtControlPoint.end(), w);
  // se non e' stato possibile trovare w nel vettore ritorna errore
  if (first == m_parameterValueAtControlPoint.end()) return true;
  /* FAB
double
found = *first;
assert(found  <=  *first);
//*/
  // individuo il punto di controllo che compete alla posizione nel vettore
  int controlPointOffset =
      distance(m_parameterValueAtControlPoint.begin(), first);
  // individuo il cionco relativo al punto di controllo
  chunk = retrieveChunkFromControlPointIndex(controlPointOffset);
  // calcolo il parametro relativo al cionco
  DoublePair p = retrieveParametersFromChunk(chunk);
  /* FAB
assert(p.first <= w &&
    w <= p.second );
#ifdef  _DEBUG
chunk = retrieveChunkFromControlPointIndex(controlPointOffset);
p = retrieveParametersFromChunk(chunk);
#endif
//*/
  if (w < p.first || w > p.second) {
    t = (p.first + p.second) * 0.5;
  } else
    t = proportion(1.0, w - p.first, p.second - p.first);
  /* FAB
assert(0.0 <= t && t <= 1.0);
//*/
  return false;
}
retrieveChunkAndItsParamameterAtLength()
bool TStroke::Imp::retrieveChunkAndItsParamameterAtLength (double s, int & chunk, double & t)
From length s retrieves chunk and its parameter (t in [0,1]). Return true -> error (parameter w out of range, etc) false -> ok
{
  vector<double>::iterator first;
  // cerco nella cache la posizione che compete alla lunghezza s
  first = std::upper_bound(m_partialLengthArray.begin(),
                           m_partialLengthArray.end(), s);
  // se s e' interna al vettore di cache
  if (first != m_partialLengthArray.end()) {
    // individuo il punto di controllo della stroke...
    int controlPointOffset = distance(m_partialLengthArray.begin(), first);
    // ...e da questo il cionco relativo.
    chunk = retrieveChunkFromControlPointIndex(controlPointOffset);
    if (first != m_partialLengthArray.begin() && s == *(first - 1)) {
      controlPointOffset--;
      if (controlPointOffset & 1) {
        const DoublePair &p = retrieveParametersFromChunk(chunk);
        t = proportion(1.0, getW(controlPointOffset) - p.first,
                       p.second - p.first);
      } else
        t = 0.0;
      return false;
    }
    // fisso un offset per l'algoritmo di bisezione
    double offset = (first == m_partialLengthArray.begin())
                        ? s
                        : s - m_partialLengthArray[chunk * 2];
    // cerco il parametro minimo a meno di una tolleranza epsilon
    const double tol = TConsts::epsilon * 0.1;
    int err;
    computeOffset_ op(getChunk(chunk), offset);
    computeSpeed_ op2(getChunk(chunk));
    if (!findZero_Newton(0.0, 1.0, op, op2, tol, tol, 100, t, err))
      t = -1;  // if can not find a good value set parameter to error value
    // se l'algoritmo di ricerca ha fallito fissa il valore ad uno dei due
    // estremi
    if (t == -1) {
      if (s <= m_partialLengthArray[controlPointOffset]) t = 0.0;
      t                                                    = 1.0;
    }
    return false;
  }
  if (s <= 0.0) {
    chunk = 0;
    t     = 0.0;
  } else if (s >= m_partialLengthArray.back()) {
    chunk = getChunkCount() - 1;
    t     = 1.0;
  }
  return false;
}
References TStroke::getChunk(), TStroke::getChunkCount(), and TStroke::getW().
retrieveChunkFromControlPointIndex()
int TStroke::Imp::retrieveChunkFromControlPointIndex (int n) inline
Retrieve chunk which contains the n-th control point of stroke. If control point is between two chunks return the left point.
{
    assert(0 <= n && n < getControlPointCount());
    if (n & 1) ++n;
    n >>= 1;
    return n ? n - 1 : n;
  };
retrieveParametersFromChunk()
DoublePair TStroke::Imp::retrieveParametersFromChunk (UINT chunk) inline
Retrieve range for a chunk.
{
    DoublePair outPar;
    int nFirst, nSecond;
    nFirst  = chunk * 2;
    nSecond = (chunk + 1) * 2;
    outPar.first  = getW(nFirst);
    outPar.second = getW(nSecond);
    return outPar;
  }
swapGeometry()
void TStroke::Imp::swapGeometry (TStroke::Imp & other) throw ()
Swaps the geometrical infos only
{
  std::swap(m_flag, other.m_flag);
  std::swap(m_isValidLength, other.m_isValidLength);
  std::swap(m_isOutlineValid, other.m_isOutlineValid);
  std::swap(m_areDisabledComputeOfCaches, other.m_areDisabledComputeOfCaches);
  std::swap(m_bBox, other.m_bBox);
  std::swap(m_partialLengthArray, other.m_partialLengthArray);
  std::swap(m_parameterValueAtControlPoint,
            other.m_parameterValueAtControlPoint);
  std::swap(m_centerLineArray, other.m_centerLineArray);
  std::swap(m_selfLoop, other.m_selfLoop);
  std::swap(m_negativeThicknessPoints, other.m_negativeThicknessPoints);
  std::swap(m_averageThickness, other.m_averageThickness);
  std::swap(m_maxThickness, other.m_maxThickness);
}
updateParameterValue()
void TStroke::Imp::updateParameterValue (double w, UINT chunk, TThickQuadratic * tq1, TThickQuadratic * tq2)
Update parameter in m_parameterValueAtControlPoint after insert of control point in stroke.
{
  DoublePair p = retrieveParametersFromChunk(chunk);
  UINT controlPointToErase = 2 * chunk + 1;
  DoubleIt it              = m_parameterValueAtControlPoint.begin();
  std::advance(it, controlPointToErase);
  m_parameterValueAtControlPoint.erase(it);
  double normalizedParam = tq2->getT(tq2->getP1());
  std::vector<double>::iterator first;
  normalizedParam = proportion(p.second, normalizedParam, 1.0, w);
  first =
      std::upper_bound(m_parameterValueAtControlPoint.begin(),
                       m_parameterValueAtControlPoint.end(), normalizedParam);
  if (first != m_parameterValueAtControlPoint.end()) {
    first = m_parameterValueAtControlPoint.insert(first, normalizedParam);
    first = m_parameterValueAtControlPoint.insert(first, w);
    normalizedParam = tq1->getT(tq1->getP1());
    normalizedParam = proportion(w, normalizedParam, 1.0, p.first);
    m_parameterValueAtControlPoint.insert(first, normalizedParam);
  }
  /* FAB
assert(getControlPointCount() <=
    (int)m_parameterValueAtControlPoint.size() );
//*/
}
References TQuadratic::getP1(), and TQuadratic::getT().
Member Data Documentation
m_areDisabledComputeOfCaches
bool TStroke::Imp::m_areDisabledComputeOfCaches
Control calculus of cache vector.
Referenced by init().
m_averageThickness
double TStroke::Imp::m_averageThickness
m_bBox
TRectD TStroke::Imp::m_bBox
Bounding Box of a stroke.
m_centerLineArray
QuadStrokeChunkArray TStroke::Imp::m_centerLineArray
This vector contains outline of stroke.
Referenced by init().
m_flag
BYTE TStroke::Imp::m_flag
m_id
int TStroke::Imp::m_id
m_isOutlineValid
bool TStroke::Imp::m_isOutlineValid
This flag checks if changes occurs and if it is necessary to update outline.
Referenced by init().
m_isValidLength
bool TStroke::Imp::m_isValidLength
This flag checks if changes occurs and if it is necessary to update length.
Referenced by init().
m_maxThickness
double TStroke::Imp::m_maxThickness
m_negativeThicknessPoints
int TStroke::Imp::m_negativeThicknessPoints
m_outlineOptions
TStroke::OutlineOptions TStroke::Imp::m_outlineOptions
m_parameterValueAtControlPoint
DoubleArray TStroke::Imp::m_parameterValueAtControlPoint
This vector contains parameter computed for each control point of stroke.
m_partialLengthArray
DoubleArray TStroke::Imp::m_partialLengthArray
This vector contains length computed for each control point of stroke.
m_prop
TStrokeProp* TStroke::Imp::m_prop
m_selfLoop
bool TStroke::Imp::m_selfLoop
m_styleId
int TStroke::Imp::m_styleId
The documentation for this struct was generated from the following file:
E:/opentoonz/toonz/sources/common/tvectorimage/tstroke.cpp