opentoonz: PlasticSkeletonVertexDeformation Struct Reference
PlasticSkeletonVertexDeformation Struct Reference final
The deformation of a plastic skeleton vertex.
#include <plasticskeletondeformation.h>
Classes
struct Keyframe
Public Types
enum Params { ANGLE = 0 , DISTANCE , SO , PARAMS_COUNT }
Public Types inherited from TPersist
typedef TPersist * CreateProc()
Public Member Functions
Keyframe getKeyframe (double frame) const
void setKeyframe (double frame)
bool setKeyframe (const Keyframe &values)
bool setKeyframe (const Keyframe &values, double frame, double easeIn=-1.0, double easeOut=-1.0)
bool isKeyframe (double frame) const
bool isFullKeyframe (double frame) const
void deleteKeyframe (double frame)
void saveData (TOStream &os) override
void loadData (TIStream &is) override
Public Member Functions inherited from TPersist
virtual void loadData (TIStream &is)=0
virtual void saveData (TOStream &os)=0
std::string getStreamTag () const
virtual const TPersistDeclaration * getDeclaration () const =0
Public Attributes
TDoubleParamP m_params [PARAMS_COUNT]
Additional Inherited Members
Static Public Member Functions inherited from TPersist
static void declare (CreateProc *)
static TPersist * create (const std::string &name)
Detailed Description
The deformation of a plastic skeleton vertex.
Member Enumeration Documentation
Params
enum PlasticSkeletonVertexDeformation::Params
Enumerator
ANGLE
Distance from parent vertex (delta)
DISTANCE
Angle with parent edge (delta)
SO
Vertex's stacking order.
              {
    ANGLE = 0,
    DISTANCE,
    SO,
    PARAMS_COUNT
  };
Member Function Documentation
deleteKeyframe()
void SkVD::deleteKeyframe (double frame)
{
  for (int p = 0; p < PARAMS_COUNT; ++p) m_params[p]->deleteKeyframe(frame);
}
getKeyframe()
SkVD::Keyframe SkVD::getKeyframe (double frame) const
{
  Keyframe kf;
  for (int p          = 0; p < PARAMS_COUNT; ++p)
    kf.m_keyframes[p] = m_params[p]->getKeyframeAt(frame);
  return kf;
}
isFullKeyframe()
bool SkVD::isFullKeyframe (double frame) const
{
  for (int p = 0; p < PARAMS_COUNT; ++p)
    if (!m_params[p]->isKeyframe(frame)) return false;
  return true;
}
isKeyframe()
bool SkVD::isKeyframe (double frame) const
{
  for (int p = 0; p < PARAMS_COUNT; ++p)
    if (m_params[p]->isKeyframe(frame)) return true;
  return false;
}
loadData()
void SkVD::loadData (TIStream & is) override virtual
 This is a pure virtual function and must be overridden with a method
that implements the object loading from a stream (i.e take the object's features from a formatted data stream). For example the TStageObject class use his implementation to take the values of the parameters that characterizes a stage object as name, coordinates, etc... from a file. is is an input file stream
Implements TPersist.
{
  std::string tagName;
  while (is.matchTag(tagName)) {
    int p;
    for (p = 0; p < PARAMS_COUNT; ++p) {
      if (tagName == parNames[p]) {
        is >> *m_params[p], is.matchEndTag();
        break;
      }
    }
    if (p >= PARAMS_COUNT) is.skipCurrentTag();
  }
}
References TIStream::matchEndTag(), TIStream::matchTag(), and TIStream::skipCurrentTag().
saveData()
void SkVD::saveData (TOStream & os) override virtual
 This is a pure virtual function and must be overridden with a method
that implements the object saving to a data stream (i.e put the object's features on a formatted data stream). For example the TStageObject class use his implementation to save the values of the parameters that characterizes a stage object as name, coordinates, etc... on a file os is an output file stream.
Implements TPersist.
{
  for (int p = 0; p < PARAMS_COUNT; ++p)
    if (!m_params[p]->isDefault()) os.child(::parNames[p]) << *m_params[p];
}
References TOStream::child().
setKeyframe() [1/3]
bool SkVD::setKeyframe (const Keyframe & values)
{
  bool keyWasSet = false;
  for (int p = 0; p < PARAMS_COUNT; ++p)
    if (values.m_keyframes[p].m_isKeyframe) {
      m_params[p]->setKeyframe(values.m_keyframes[p]);
      keyWasSet = true;
    }
  return keyWasSet;
}
setKeyframe() [2/3]
bool SkVD::setKeyframe (const Keyframe & values, double frame, double easeIn = -1.0, double easeOut = -1.0)
{
  bool keyWasSet = false;
  for (int p = 0; p < PARAMS_COUNT; ++p)
    if (values.m_keyframes[p].m_isKeyframe) {
      TDoubleKeyframe kf(values.m_keyframes[p]);
      kf.m_frame = frame;
      if (easeIn >= 0.0) kf.m_speedIn   = TPointD(-easeIn, kf.m_speedIn.y);
      if (easeOut >= 0.0) kf.m_speedOut = TPointD(easeOut, kf.m_speedOut.y);
      m_params[p]->setKeyframe(kf);
      keyWasSet = true;
    }
  return keyWasSet;
}
setKeyframe() [3/3]
void SkVD::setKeyframe (double frame)
{
  for (int p = 0; p < PARAMS_COUNT; ++p)
    m_params[p]->setKeyframe(m_params[p]->getKeyframeAt(frame));
}
Member Data Documentation
m_params
TDoubleParamP PlasticSkeletonVertexDeformation::m_params[PARAMS_COUNT]
The documentation for this struct was generated from the following files:
E:/opentoonz/toonz/sources/include/ext/plasticskeletondeformation.h
E:/opentoonz/toonz/sources/tnzext/plasticskeletondeformation.cpp