opentoonz: E:/opentoonz/toonz/sources/include/toonz/textureutils.h File Reference
textureutils.h File Reference
#include "ext/ttexturesstorage.h"
Functions
DrawableTextureDataP texture_utils::getTextureData (const TXshSimpleLevel *sl, const TFrameId &fid, int subsampling)
void texture_utils::invalidateTexture (const TXshSimpleLevel *sl, const TFrameId &fid)
void texture_utils::invalidateTextures (const TXshSimpleLevel *sl)
Invalidates any currently stored texture associated with sl.
DrawableTextureDataP texture_utils::getTextureData (const TXsheet *xsh, int frame)
void texture_utils::invalidateTexture (const TXsheet *xsh, int frame)
void texture_utils::invalidateTextures (const TXsheet *xsh)
Invalidates any currently stored texture associated with sl.
Macro Definition Documentation
TEXTUREUTILS_H
#define TEXTUREUTILS_H
Function Documentation
getTextureData() [1/2]
DrawableTextureDataP texture_utils::getTextureData (const TXsheet * xsh, int frame)
Returns the OpenGL data of a loaded texture corresponding to xsh's content at the specified frame.
{
  // Check if an xsheet texture already exists
  const std::string &texId = ::getImageId(xsh, frame);
  DrawableTextureDataP data(
      TTexturesStorage::instance()->getTextureData(texId));
  if (data) return data;
  // No available texture - we must build and load it
  TRaster32P tex(
      1024,
      1024);  // Fixed texture size. It's the same that currently happens with
              // vector images' textures - and justified since this is camstand
  // mode, and besides we want to make sure that textures are limited.
  // Retrieve the sub-xsheet bbox (world coordinates of the sub-xsheet)
  TRectD bbox(xsh->getBBox(frame));
  // Since xsh represents a sub-xsheet, its camera affine must be applied
  const TAffine &cameraAff =
      xsh->getPlacement(xsh->getStageObjectTree()->getCurrentCameraId(), frame);
  bbox = (cameraAff.inv() * bbox).enlarge(1.0);
// Render the xsheet on the specified bbox
#ifdef MACOSX
  xsh->getScene()->renderFrame(tex, frame, xsh, bbox, TAffine());
#else
  // The call below will change context (I know, it's a shame :( )
  TGlContext currentContext = tglGetCurrentContext();
  {
    tglDoneCurrent(currentContext);
    xsh->getScene()->renderFrame(tex, frame, xsh, bbox, TAffine());
    tglMakeCurrent(currentContext);
  }
#endif
  TRop::depremultiply(tex);  // Stored textures are rendered nonpremultiplied
  // Store the texture for future retrieval
  return TTexturesStorage::instance()->loadTexture(texId, tex, bbox);
}
References TRop::depremultiply(), TXsheet::getBBox(), TStageObjectTree::getCurrentCameraId(), TXsheet::getPlacement(), TXsheet::getScene(), TXsheet::getStageObjectTree(), texture_utils::getTextureData(), TAffine::inv(), TTexturesStorage::loadTexture(), and ToonzScene::renderFrame().
getTextureData() [2/2]
DrawableTextureDataP texture_utils::getTextureData (const TXshSimpleLevel * sl, const TFrameId & fid, int subsampling)
Returns the OpenGL data of a loaded texture corresponding to sl's content at fid with specified subsampling.
{
  const std::string &texId = sl->getImageId(fid);
  // Now, we must associate a texture
  DrawableTextureDataP data(
      TTexturesStorage::instance()->getTextureData(texId));
  if (data) return data;
  // There was no associated texture. We must bind the texture and repeat
  // First, retrieve the image to be used as texture
  TRasterImageP ri(::getTexture(sl, fid, subsampling));
  if (!ri) return DrawableTextureDataP();
  TRaster32P ras(ri->getRaster());
  assert(ras);
  TRectD geom(0, 0, ras->getLx(), ras->getLy());
  geom = TScale(ri->getSubsampling()) *
         TTranslation(convert(ri->getOffset()) - ras->getCenterD()) * geom;
  return TTexturesStorage::instance()->loadTexture(texId, ras, geom);
}
References TPointT< T >::convert(), texture_utils::getTextureData(), and TTexturesStorage::loadTexture().
Referenced by texture_utils::getTextureData().
invalidateTexture() [1/2]
void texture_utils::invalidateTexture (const TXsheet * xsh, int frame)
Invalidates any currently stored texture associated with xsh at the specified frame.
{
  const std::string &texId = ::getImageId(xsh, frame);
  TTexturesStorage::instance()->unloadTexture(texId);
}
References texture_utils::invalidateTexture(), and TTexturesStorage::unloadTexture().
invalidateTexture() [2/2]
void texture_utils::invalidateTexture (const TXshSimpleLevel * sl, const TFrameId & fid)
Invalidates any currently stored texture associated with sl at the specified fid.
{
  const std::string &texId = sl->getImageId(fid);
  TTexturesStorage::instance()->unloadTexture(texId);
}
References texture_utils::invalidateTexture(), and TTexturesStorage::unloadTexture().
Referenced by texture_utils::invalidateTexture(), and texture_utils::invalidateTextures().
invalidateTextures() [1/2]
void texture_utils::invalidateTextures (const TXsheet * xsh)
Invalidates any currently stored texture associated with sl.
{
  int f, fCount = xsh->getFrameCount();
  for (f = 0; f != fCount; ++f) invalidateTexture(xsh, f);
}
References TXsheet::getFrameCount(), texture_utils::invalidateTexture(), and texture_utils::invalidateTextures().
invalidateTextures() [2/2]
void texture_utils::invalidateTextures (const TXshSimpleLevel * sl)
Invalidates any currently stored texture associated with sl.
{
  int f, fCount = sl->getFrameCount();
  for (f = 0; f != fCount; ++f) invalidateTexture(sl, sl->getFrameId(f));
}
References TXshSimpleLevel::getFrameCount(), TXshSimpleLevel::getFrameId(), texture_utils::invalidateTexture(), and texture_utils::invalidateTextures().
Referenced by texture_utils::invalidateTextures().